GravityView: data-source.php File Reference
Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/admin/metaboxes/views/data-source.php File Reference
Namespaces
GravityView
GPL2+
Variables
$current_form = gravityview_get_form_id($post->ID)
$forms = gravityview_get_forms()
Variable Documentation
$current_form = gravityview_get_form_id($post->ID)
Definition at line 14 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/admin/metaboxes/views/data-source.php.
Referenced by GravityView_Field_Time\_get_time_format(), GravityView_Admin_Views\add_view_dropdown(), and GravityView_Admin_Metaboxes\get_data_source_header().
$forms = gravityview_get_forms()
Definition at line 17 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/admin/metaboxes/views/data-source.php.
Referenced by GravityView_Admin_Views\add_view_dropdown(), GravityView_Cache\get_cache_key_prefix(), GravityView_Admin_ApproveEntries\get_first_form_id(), GVCommon\get_forms(), GravityView_Ajax\import_form(), and GravityView_Ajax\pre_get_form_fields().