GravityView: delete_link.php File Reference
Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/delete-entry/fields/delete_link.php File Reference
Variables
$attributes
$gravityview_view = GravityView_View::getInstance()
$href = GravityView_Delete_Entry::get_delete_link($entry, $view_id)
if(!GravityView_Delete_Entry::check_user_cap_delete_entry($entry, $field_settings)) $link_text = empty($field_settings['delete_link']) ? __('Delete Entry', 'gravityview') : $field_settings['delete_link']
$view_id = $gravityview_view->getViewId()
Variable Documentation
$attributes
Initial value:
= array(
    'onclick' => GravityView_Delete_Entry::get_confirm_dialog()
)
Definition at line 20 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/delete-entry/fields/delete_link.php.
Referenced by GravityView_Delete_Entry\add_delete_button(), and GravityView_Settings\settings_submit().
$gravityview_view = GravityView_View::getInstance()
Definition at line 3 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/delete-entry/fields/delete_link.php.
Referenced by GravityView_Delete_Entry\check_user_cap_delete_entry(), GravityView_API\directory_link(), GravityView_Widget_Search\enqueue_datepicker(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_API\field_label(), GravityView_API\field_value(), GravityView_Field_Notes\get_add_note_part(), GravityView_Field_Notes\get_note_emails_array(), GravityView_Widget_Search\get_search_class(), GravityView_Widget_Search\get_search_filter_details(), GravityView_Widget_Search\get_search_form_action(), GravityView_Shortcode\get_view_detail(), gravityview_back_link(), GravityView_API\no_results(), GravityView_Widget\pre_render_frontend(), GravityView_Widget_Search\prepare_field_filter(), GravityView_Edit_Entry_Render\print_scripts(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Pagination_Info\render_frontend(), GravityView_Widget_Poll\render_frontend(), GravityView_frontend\render_view(), GravityView_Edit_Entry_Render\setup_vars(), and GravityView_Widget_Search\the_clear_search_button().
$href = GravityView_Delete_Entry::get_delete_link($entry, $view_id)
Definition at line 18 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/delete-entry/fields/delete_link.php.
Referenced by GravityView_API\entry_link_html(), GVCommon\get_link_html(), gravityview_back_link(), and gravityview_get_link().
$link_text = empty($field_settings['delete_link']) ? __('Delete Entry', 'gravityview') : $field_settings['delete_link']
Definition at line 14 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/delete-entry/fields/delete_link.php.
Referenced by gravityview_get_map_link(), and GravityView_Entry_Link_Shortcode\shortcode().
$view_id = $gravityview_view->getViewId()
Definition at line 5 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/delete-entry/fields/delete_link.php.
Referenced by GravityView_frontend\add_scripts_and_styles(), GravityView_View_Data\add_view(), GravityView_Edit_Entry\check_user_cap_edit_entry(), GravityView_Search_WP_Widget\form(), GravityView_Edit_Entry\get_edit_link(), GravityView_View_Data\get_fields(), get_gravityview(), GravityView_View_Data\get_id_from_atts(), GVCommon\get_meta_form_id(), GVCommon\get_meta_template_id(), GravityView_Edit_Entry\get_nonce_key(), GravityView_Migrate\get_search_fields(), GravityView_View_Data\get_view(), gravityview_get_current_view_data(), gravityview_get_form_id(), gv_container_class(), GravityView_frontend\insert_view_in_content(), GravityView_View_Data\is_valid_embed_id(), GravityView_frontend\render_view(), GravityView_frontend\set_context_view_id(), GravityView_frontend\single_entry_title(), the_gravityview(), and GravityView_View_Data\view_exists().