GravityView: notes.php File Reference
Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php File Reference
Namespaces
GravityView
includes
Variables
$container_class = (sizeof($notes) > 0 ? 'gv-has-notes' : 'gv-no-notes')
$entry = $gravityview_view->getCurrentEntry()
$entry_slug = GravityView_API::get_entry_slug($entry['id'], $entry)
$gravityview_view = GravityView_View::getInstance()
$notes = GravityView_Entry_Notes::get_notes($entry['id'])
$show_add = ! empty($visibility_settings['add'])
$show_delete = (! empty($visibility_settings['delete']) && GVCommon::has_cap('gravityview_delete_entry_notes'))
$show_notes = $show_notes_logged_out || (! empty($visibility_settings['view']) && GVCommon::has_cap('gravityview_view_entry_notes'))
$show_notes_logged_out = (! empty($visibility_settings['view']) && ! empty($visibility_settings['view_loggedout']))
$strings = GravityView_Field_Notes::strings()
$visibility_settings = $gravityview_view->getCurrentFieldSetting('notes')
if (!GVCommon::has_cap(array('gravityview_view_entry_notes', 'gravityview_add_entry_notes', 'gravityview_delete_entry_notes'))&&!$show_notes_logged_out) = apply_filters('gravityview/fields/custom/content_after', $content)
Variable Documentation
$container_class = (sizeof($notes) > 0 ? 'gv-has-notes' : 'gv-no-notes')
Definition at line 36 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
Referenced by GravityView_Admin_View_Item\getOutput().
$entry = $gravityview_view->getCurrentEntry()
Definition at line 27 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
Referenced by GravityView_Field\_filter_gform_replace_merge_tags(), GravityView_Entry_Link_Shortcode_Test\_test_delete(), GravityView_Entry_Link_Shortcode_Test\_test_edit(), GravityView_Entry_Approval\add_approval_status_updated_note(), GravityView_Admin_ApproveEntries\add_entry_approved_hidden_input(), GravityView_Admin_Bar\add_floaty_icon(), GravityView_Edit_Entry_User_Registration\add_hooks(), GravityView_Cache\add_hooks(), GravityView_Field_Notes\add_note(), GravityView_Change_Entry_Creator\add_select(), GravityView_Entry_Approval\after_submission(), GravityView_Entry_Approval\after_update_entry_update_approved_meta(), GravityView_Change_Entry_Creator\assign_new_user_to_lead(), GVCommon\check_entry_display(), GravityView_Edit_Entry\check_user_cap_edit_entry(), NotGettexted\command_extract(), GravityView_Field_Is_Approved\custom_merge_tags(), GravityView_Plugin_Hooks_Gravity_Forms_Signature\edit_entry_field_input(), GravityView_Field_Post_Category\edit_entry_post_category_choices(), GravityView_API\entry_create_custom_slug(), GravityView_Cache\entry_created(), StringExtractor\entry_from_call(), GravityView_API\entry_link(), GravityView_API\entry_link_html(), GravityView_Field_Post_Image\explode_value(), StringExtractor\extract_from_code(), GravityView_API\field_class(), GravityView_API\field_label(), GravityView_Field_FileUpload\field_options(), GravityView_API\field_value(), GravityView_Plugin_Hooks_Gravity_Forms_Survey\fix_survey_field_value(), GravityView_Field_Notes\get_add_note_part(), GravityView_Field_Payment_Amount\get_content(), GravityView_API\get_custom_entry_slug(), GravityView_Edit_Entry\get_edit_link(), GVCommon\get_entry(), GravityView_API\get_entry_slug(), GravityView_Entry_Approval\get_entry_status(), GVCommon\get_form_from_entry_id(), GravityView_Entry_List\get_item_output(), GravityView_Field_Notes\get_note_emails_array(), GravityView_Entry_List\get_output(), GravityView_GFFormsModel\get_post_field_images(), GravityView_GFFormsModel\get_post_fields(), GravityView_View\getCurrentEntry(), gravityview_field_output(), gravityview_get_field_value(), gv_class(), gv_entry_link(), gv_label(), gv_value(), PotExtMeta\load_from_file(), GravityView_Field_Notes\maybe_send_entry_notes(), GravityView_Field_Workflow_Step\modify_entry_value_workflow_step(), GravityView_Plugin_Hooks_Gravity_Flow\modify_entry_value_workflow_step(), GravityView_Field_Notes\process_add_note(), GravityView_Merge_Tags\replace_get_variables(), GravityView_Merge_Tags\replace_gv_merge_tags(), GravityView_Field_Payment_Amount\replace_merge_tag(), GravityView_Field_Created_By\replace_merge_tag(), GravityView_Field_Date_Created\replace_merge_tag(), GravityView_Field_Is_Fulfilled\replace_merge_tag(), GravityView_Field\replace_merge_tag(), GravityView_API\replace_variables(), GravityView_Merge_Tags\replace_variables(), GravityView_Edit_Entry_User_Registration\restore_display_name(), GVCommon\send_email(), GravityView_Field_Post_Category\set_post_categories(), GravityView_Field_Custom\show_field_in_edit_entry(), GravityView_Entry_List\skip_entry(), GravityView_View_Test\test_BackLinkLabel(), GVCommon_Test\test_format_date(), GravityView_Merge_Tags_Test\test_gf_merge_tags(), GravityView_Merge_Tags_Test\test_replace_date_created(), GravityView_Merge_Tags_Test\test_replace_field_custom_merge_tags(), GravityView_Merge_Tags_Test\test_replace_user_variables_created_by(), GravityView_Entry_Link_Shortcode_Test\test_shortcode(), GravityView_Entry_Approval_Test\test_update_bulk(), GravityView_Entry_Approval\update_approved(), GV_UnitTest_Factory_For_Entry\update_object(), and GravityView_Edit_Entry_User_Registration\update_user().
$entry_slug = GravityView_API::get_entry_slug($entry['id'], $entry)
Definition at line 30 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
Referenced by GravityView_API\entry_link(), GravityView_Field_FileUpload\field_options(), GravityView_Field_Notes\get_add_note_part(), GravityView_Delete_Entry\get_delete_link(), GVCommon\get_entry(), GVCommon\get_form_from_entry_id(), GravityView_Field_Notes\get_note_email_fields(), gravityview_get_entry(), gravityview_get_form_from_entry_id(), GravityView_Delete_Entry\process_delete(), and GravityView_Theme_Hooks_WPML\wpml_ls_filter().
$gravityview_view = GravityView_View::getInstance()
Definition at line 9 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
$notes = GravityView_Entry_Notes::get_notes($entry['id'])
Definition at line 28 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
Referenced by GravityView_Uninstall_Test\_check_deleted_entry_notes(), GravityView_Uninstall_Test\_set_up_notes(), and GravityView_Entry_Notes\get_notes().
$show_add = ! empty($visibility_settings['add'])
Definition at line 32 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
$show_delete = (! empty($visibility_settings['delete']) && GVCommon::has_cap('gravityview_delete_entry_notes'))
Definition at line 33 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
Referenced by GravityView_Field_Notes\display_note().
$show_notes = $show_notes_logged_out || (! empty($visibility_settings['view']) && GVCommon::has_cap('gravityview_view_entry_notes'))
Definition at line 34 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
$show_notes_logged_out = (! empty($visibility_settings['view']) && ! empty($visibility_settings['view_loggedout']))
Definition at line 12 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
$strings = GravityView_Field_Notes::strings()
Definition at line 29 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
Referenced by GravityView_Field_Notes\enqueue_scripts(), GravityView_Field_Notes\get_note_email_fields(), GravityView_Field_Notes\strings(), and GV_License_Handler\strings().
$visibility_settings = $gravityview_view->getCurrentFieldSetting('notes')
Definition at line 11 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
Referenced by GravityView_Field_Notes\get_add_note_part().
if = apply_filters('gravityview/fields/custom/content_after', $content)
Runs Filter:
gravityview/fields/custom/decode_shortcodes Decode brackets in shortcodes
Since
1.16.5
Parameters
boolean $decode Enable/Disable decoding of brackets in the content (default: false)
string $content HTML content of field
Runs Filter:
gravityview/fields/custom/content_after Modify Custom Content field output after Merge Tag variables get replaced, before shortcodes get processed
Since
1.6.2
Parameters
string $content HTML content of field
Definition at line 14 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/entry-notes/fields/notes.php.
Referenced by GravityView_Welcome\getting_started_screen().