GravityView: edit_link.php File Reference
Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/edit-entry/fields/edit_link.php File Reference
Variables
$gravityview_view = GravityView_View::getInstance()
$href = GravityView_Edit_Entry::get_edit_link($entry, $view_id)
$link_atts = empty($field_settings['new_window']) ? '' : 'target="_blank"'
if(!GravityView_Edit_Entry::check_user_cap_edit_entry($entry)) $link_text = empty($field_settings['edit_link']) ? __('Edit Entry', 'gravityview') : $field_settings['edit_link']
$output = apply_filters('gravityview_entry_link', GravityView_API::replace_variables($link_text, $form, $entry))
$view_id = $gravityview_view->getViewId()
Variable Documentation
$gravityview_view = GravityView_View::getInstance()
Definition at line 3 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/edit-entry/fields/edit_link.php.
$href = GravityView_Edit_Entry::get_edit_link($entry, $view_id)
Definition at line 20 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/edit-entry/fields/edit_link.php.
$link_atts = empty($field_settings['new_window']) ? '' : 'target="_blank"'
Definition at line 16 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/edit-entry/fields/edit_link.php.
Referenced by GravityView_Field_FileUpload\field_options(), GravityView_API\field_value(), GravityView_Entry_Link_Shortcode\get_link_atts(), and GravityView_Entry_Link_Shortcode\shortcode().
if (!GravityView_Edit_Entry::check_user_cap_edit_entry($entry)) $link_text = empty($field_settings['edit_link']) ? __('Edit Entry', 'gravityview') : $field_settings['edit_link']
Definition at line 14 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/edit-entry/fields/edit_link.php.
$output = apply_filters('gravityview_entry_link', GravityView_API::replace_variables($link_text, $form, $entry))
Definition at line 18 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/edit-entry/fields/edit_link.php.
Referenced by GravityView_Admin_Views\add_custom_column_content(), GravityView_Change_Entry_Creator\add_select(), GravityView_Admin_Notices\admin_notice(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), MakePOT\bb(), MakePOT\bp(), GravityView_frontend\context_not_configured_warning(), GravityView_Field_Notes\display_note(), GravityView_API\entry_link_html(), GravityView_API\field_value(), GravityView_Edit_Entry_Render\fill_post_template(), GravityView_Field_Is_Approved\filter_field_value(), GV_License_Handler\generate_license_box(), MakePOT\generic(), GravityView_Admin_Views\get_connected_form_links(), GravityView_Field_Payment_Amount\get_content(), GravityView_Field_Transaction_Type\get_content(), GravityView_Field_Date_Created\get_content(), GravityView_Field_Is_Fulfilled\get_content(), GravityView_Field_Notes\get_email_footer(), GravityView_Admin_View_Item\get_item_info(), GVCommon\get_link_html(), GravityView_Entry_List\get_output(), GVLogic_Shortcode\get_output(), GVCommon\get_sortable_fields(), GV_License_Handler\get_upgrade_html(), GravityView_Admin_View_Item\getOutput(), MakePOT\glotpress(), gravityview_convert_value_to_term_list(), gravityview_get_the_term_list(), gv_selected(), GVCommon\js_encrypt(), GravityView_Field_Workflow_Final_Status\modify_entry_value_workflow_final_status(), GravityView_Plugin_Hooks_Gravity_Flow\modify_entry_value_workflow_final_status(), GravityView_Field_Workflow_Step\modify_entry_value_workflow_step(), GravityView_Plugin_Hooks_Gravity_Flow\modify_entry_value_workflow_step(), MakePOT\mu(), GravityView_API\no_results(), GravityView_Admin\no_views_text(), GravityView_Entry_List\output(), GravityView_Field_Section\prevent_empty_field(), GravityView_Debug_Bar\render(), GravityView_Admin_Views\render_available_fields(), GravityView_Render_Settings\render_checkbox_option(), GravityView_Admin_Views\render_directory_active_areas(), GravityView_Render_Settings\render_field_option(), GravityView_Render_Settings\render_field_options(), GravityView_Widget_Pagination_Info\render_frontend(), GravityView_Debug_Bar\render_item(), GravityView_Admin_Metaboxes\render_merge_tags_scripts(), GravityView_Widget_Search\render_searchable_fields(), GravityView_Render_Settings\render_select_option(), GravityView_frontend\render_view(), GravityView_Admin_Views\render_widgets_active_areas(), GravityView_View\renderZone(), MakePOT\rosetta(), settings_save(), GVLogic_Shortcode\shortcode(), GravityView_API_Test\test_gravityview_field_output(), GravityView_API_Test\test_gv_container_class(), GravityView_Recent_Entries_Widget\widget(), MakePOT\wp_admin(), MakePOT\wp_core(), MakePOT\wp_frontend(), MakePOT\wp_generic(), MakePOT\wp_ms(), MakePOT\wp_network_admin(), GruntMakePOT\wp_plugin(), MakePOT\wp_plugin(), GruntMakePOT\wp_theme(), MakePOT\wp_theme(), MakePOT\wp_tz(), and MakePOT\wporg_bb_forums().
$view_id = $gravityview_view->getViewId()
Definition at line 5 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/extensions/edit-entry/fields/edit_link.php.