GravityView: about.php File Reference
about.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$locale = str_replace('_', '-', get_locale())
$title = __('About')
if(current_user_can('install_plugins')) $video_url = 'https://videopress.com/embed/J44FHXvg?hd=true'
if(current_user_can('install_plugins')) else
endif
Home Go to Dashboard wp admin admin footer php Maintenance Release Maintenance Releases Security Release Security Releases Maintenance and Security Release Maintenance and Security Releases< strong > Version s</strong > addressed one security issue< strong > Version s</strong > addressed some security issues< strong > Version</strong > addressed bug< strong > Version</strong > addressed bugs< strong > Version</strong > addressed a security issue and fixed bug< strong > Version</strong > addressed a security issue and fixed bugs< strong > Version</strong > addressed some security issues and fixed bug< strong > Version</strong > addressed some security issues and fixed bugs For more information
Variable Documentation
$locale = str_replace('_', '-', get_locale())
Definition at line 25 of file about.php.
Referenced by do_core_upgrade(), do_dismiss_core_update(), do_undismiss_core_update(), find_core_update(), get_locale(), get_locale_stylesheet_uri(), GFAddOn\init(), load_default_textdomain(), load_muplugin_textdomain(), GravityView_Extension\load_plugin_textdomain(), GravityView_Plugin\load_plugin_textdomain(), load_plugin_textdomain(), load_theme_textdomain(), remove_accents(), undismiss_core_update(), wp_credits(), wp_dropdown_languages(), wp_get_popular_importers(), wp_load_translations_early(), wp_maybe_decline_date(), wp_timezone_choice(), and wp_version_check().
$title = __('About')
Definition at line 33 of file about.php.
if (current_user_can('install_plugins')) $video_url = 'https://videopress.com/embed/J44FHXvg?hd=true'
Definition at line 24 of file about.php.
if (current_user_can('install_plugins')) else
Initial value:
{
                                $plugin_link = '<a href="https://wordpress.org/plugins/rest-api">WordPress REST API</a>'
Definition at line 143 of file about.php.
endif
Definition at line 191 of file about.php.
Home Go to Dashboard wp admin admin footer php Maintenance Release Maintenance Releases Security Release Security Releases Maintenance and Security Release Maintenance and Security Releases<strong> Version s</strong> addressed one security issue<strong> Version s</strong> addressed some security issues<strong> Version</strong> addressed bug<strong> Version</strong> addressed bugs<strong> Version</strong> addressed a security issue and fixed bug<strong> Version</strong> addressed a security issue and fixed bugs<strong> Version</strong> addressed some security issues and fixed bug<strong> Version</strong> addressed some security issues and fixed bugs For more information
Definition at line 231 of file about.php.