GravityView: admin-bar.php File Reference
admin-bar.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_admin_bar_bump_cb ()
Default admin bar callback.
_get_admin_bar_pref ($context= 'front', $user=0)
Retrieve the admin bar display preference of a user.
_wp_admin_bar_init ()
Instantiate the admin bar object and set it up as a global for access elsewhere.
is_admin_bar_showing ()
Determine whether the admin bar should be showing.
show_admin_bar ($show)
Set the display status of the admin bar.
wp_admin_bar_add_secondary_groups ($wp_admin_bar)
Add secondary menus.
wp_admin_bar_appearance_menu ($wp_admin_bar)
Add appearance submenu items to the "Site Name" menu.
wp_admin_bar_comments_menu ($wp_admin_bar)
Add edit comments link with awaiting moderation count bubble.
wp_admin_bar_customize_menu ($wp_admin_bar)
Adds the "Customize" link to the Toolbar.
wp_admin_bar_edit_menu ($wp_admin_bar)
Provide an edit link for posts and terms.
wp_admin_bar_header ()
Style and scripts for the admin bar.
wp_admin_bar_my_account_item ($wp_admin_bar)
Add the "My Account" item.
wp_admin_bar_my_account_menu ($wp_admin_bar)
Add the "My Account" submenu items.
wp_admin_bar_my_sites_menu ($wp_admin_bar)
Add the "My Sites/[Site Name]" menu and all submenus.
wp_admin_bar_new_content_menu ($wp_admin_bar)
Add "Add New" menu.
wp_admin_bar_render ()
Render the admin bar to the page based on the $wp_admin_bar->menu member var.
wp_admin_bar_search_menu ($wp_admin_bar)
Add search form.
wp_admin_bar_shortlink_menu ($wp_admin_bar)
Provide a shortlink.
wp_admin_bar_sidebar_toggle ($wp_admin_bar)
Add the sidebar toggle button.
wp_admin_bar_site_menu ($wp_admin_bar)
Add the "Site Name" menu.
wp_admin_bar_updates_menu ($wp_admin_bar)
Provide an update link if theme/plugin/core updates are available.
wp_admin_bar_wp_menu ($wp_admin_bar)
Add the WordPress logo menu.
Function Documentation
_admin_bar_bump_cb ()
Default admin bar callback.
Since
3.1.0
Definition at line 863 of file admin-bar.php.
References margin, and width.
_get_admin_bar_pref ($context = 'front', $user = 0)
Retrieve the admin bar display preference of a user.
Since
3.1.0 private
Parameters
string $context Context of this preference check. Defaults to 'front'. The 'admin' preference is no longer used.
int $user Optional. ID of the user to check, defaults to 0 for current user.
Returns
bool Whether the admin bar should be showing for this user.
Definition at line 950 of file admin-bar.php.
References $user, and get_user_option().
Referenced by is_admin_bar_showing().
_wp_admin_bar_init ()
Instantiate the admin bar object and set it up as a global for access elsewhere.
UNHOOKING THIS FUNCTION WILL NOT PROPERLY REMOVE THE ADMIN BAR. For that, use show_admin_bar(false) or the 'show_admin_bar' filter.
Since
3.1.0 private
WP_Admin_Bar $wp_admin_bar
Returns
bool Whether the admin bar was successfully initialized.
Filter the admin bar class to instantiate.
Since
3.1.0
Parameters
string $wp_admin_bar_class Admin bar class to use. Default 'WP_Admin_Bar'.
Definition at line 23 of file admin-bar.php.
References ABSPATH, apply_filters(), is_admin_bar_showing(), and WPINC.
is_admin_bar_showing ()
Determine whether the admin bar should be showing.
Since
3.1.0
WP_Admin_Bar $wp_admin_bar string $pagenow
Returns
bool Whether the admin bar should be showing.
Filter whether to show the admin bar.
Returning false to this hook is the recommended way to hide the admin bar. The user's display preference is used for logged in users.
Since
3.1.0
Parameters
bool $show_admin_bar Whether the admin bar should be shown. Default false.
Definition at line 901 of file admin-bar.php.
References $pagenow, _get_admin_bar_pref(), apply_filters(), is_admin(), and is_embed().
Referenced by _wp_admin_bar_init(), _wp_admin_html_begin(), get_body_class(), and wp_admin_bar_render().
show_admin_bar ($show)
Set the display status of the admin bar.
This can be called immediately upon plugin load. It does not need to be called from a function hooked to the init action.
Since
3.1.0
WP_Admin_Bar $wp_admin_bar
Parameters
bool $show Whether to allow the admin bar to show.
Definition at line 886 of file admin-bar.php.
Referenced by iframe_header(), and WP_Customize_Manager\setup_theme().
wp_admin_bar_add_secondary_groups ($wp_admin_bar)
Add secondary menus.
Since
3.3.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 831 of file admin-bar.php.
wp_admin_bar_appearance_menu ($wp_admin_bar)
Add appearance submenu items to the "Site Name" menu.
Since
3.1.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 715 of file admin-bar.php.
References __, admin_url(), current_theme_supports(), and current_user_can().
Referenced by wp_admin_bar_site_menu().
wp_admin_bar_comments_menu ($wp_admin_bar)
Add edit comments link with awaiting moderation count bubble.
Since
3.1.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 689 of file admin-bar.php.
References $title, _n(), admin_url(), current_user_can(), number_format_i18n(), and wp_count_comments().
wp_admin_bar_customize_menu ($wp_admin_bar)
Adds the "Customize" link to the Toolbar.
Since
4.3.0
Parameters
WP_Admin_Bar $wp_admin_bar WP_Admin_Bar instance.
Definition at line 348 of file admin-bar.php.
References $_SERVER, $customize_url, __, add_action(), add_query_arg(), current_user_can(), is_admin(), is_ssl(), and wp_customize_url().
wp_admin_bar_edit_menu ($wp_admin_bar)
Provide an edit link for posts and terms.
Since
3.1.0
WP_Term $tag WP_Query $wp_the_query
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 546 of file admin-bar.php.
References $current_screen, $post, $post_type_object, $tax, current_user_can(), elseif, esc_url, get_current_screen(), get_edit_post_link(), get_edit_term_link(), get_permalink(), get_post(), get_post_type_object(), get_preview_post_link(), get_taxonomy(), get_term_link(), is_admin(), is_wp_error(), and set_url_scheme().
wp_admin_bar_header ()
Style and scripts for the admin bar.
Since
3.1.0
Definition at line 853 of file admin-bar.php.
wp_admin_bar_my_account_item ($wp_admin_bar)
Add the "My Account" item.
Since
3.3.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 181 of file admin-bar.php.
References $class, $current_user, $user_id, __, current_user_can(), elseif, get_current_user_id(), get_dashboard_url(), get_edit_profile_url(), and is_multisite().
wp_admin_bar_my_account_menu ($wp_admin_bar)
Add the "My Account" submenu items.
Since
3.1.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 218 of file admin-bar.php.
References $current_user, $user_id, __, current_user_can(), elseif, get_current_user_id(), get_dashboard_url(), get_edit_profile_url(), is_multisite(), and wp_logout_url().
wp_admin_bar_my_sites_menu ($wp_admin_bar)
Add the "My Sites/[Site Name]" menu and all submenus.
Since
3.1.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 375 of file admin-bar.php.
References $blog, __, admin_url(), current_user_can(), get_admin_url(), get_home_url(), get_post_type_object(), home_url(), is_multisite(), is_super_admin(), network_admin_url(), restore_current_blog(), and switch_to_blog().
wp_admin_bar_new_content_menu ($wp_admin_bar)
Add "Add New" menu.
Since
3.1.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 625 of file admin-bar.php.
References $action, $id, $link, $title, _x, admin_url(), current_user_can(), and get_post_types().
wp_admin_bar_render ()
Render the admin bar to the page based on the $wp_admin_bar->menu member var.
This is called very late on the footer actions so that it will render after anything else being added to the footer.
It includes the action "admin_bar_menu" which should be used to hook in and add new menus to the admin bar. That way you can be sure that you are adding at most optimal point, right before the admin bar is rendered. This also gives you access to the $post global, among others.
Since
3.1.0
WP_Admin_Bar $wp_admin_bar
Load all necessary admin bar items.
This is the hook used to add, remove, or manipulate admin bar items.
Since
3.1.0
Parameters
WP_Admin_Bar $wp_admin_bar WP_Admin_Bar instance, passed by reference
Fires before the admin bar is rendered.
Since
3.1.0
Fires after the admin bar is rendered.
Since
3.1.0
Definition at line 66 of file admin-bar.php.
References do_action(), do_action_ref_array(), and is_admin_bar_showing().
wp_admin_bar_search_menu ($wp_admin_bar)
Add search form.
Since
3.3.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 803 of file admin-bar.php.
References $form, __, esc_url, home_url(), and is_admin().
wp_admin_bar_shortlink_menu ($wp_admin_bar)
Provide a shortlink.
Since
3.1.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 519 of file admin-bar.php.
References $id, __, esc_attr(), and wp_get_shortlink().
wp_admin_bar_sidebar_toggle ($wp_admin_bar)
Add the sidebar toggle button.
Since
3.8.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 164 of file admin-bar.php.
References __, and is_admin().
wp_admin_bar_site_menu ($wp_admin_bar)
Add the "Site Name" menu.
Since
3.3.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 278 of file admin-bar.php.
References $title, __, admin_url(), current_user_can(), elseif, esc_html, get_bloginfo(), get_current_blog_id(), get_current_site(), get_home_url(), home_url(), is_admin(), is_blog_admin(), is_multisite(), is_network_admin(), is_super_admin(), is_user_admin(), is_user_member_of_blog(), network_admin_url(), wp_admin_bar_appearance_menu(), and wp_html_excerpt().
wp_admin_bar_updates_menu ($wp_admin_bar)
Provide an update link if theme/plugin/core updates are available.
Since
3.1.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 776 of file admin-bar.php.
References $title, $update_data, network_admin_url(), number_format_i18n(), and wp_get_update_data().
wp_admin_bar_wp_menu ($wp_admin_bar)
Add the WordPress logo menu.
Since
3.3.0
Parameters
WP_Admin_Bar $wp_admin_bar
Definition at line 107 of file admin-bar.php.
References __, and self_admin_url().