GravityView: admin-ajax.php File Reference
admin-ajax.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$core_actions_get
$core_actions_post
$core_actions_post [] = 'wp-fullscreen-save-post'
const DOING_AJAX true
Executing AJAX process.
if(is_user_logged_in()) else
if (!defined('WP_ADMIN'))
Load WordPress Bootstrap.
if(!empty($_GET['action'])&&in_array($_GET['action'], $core_actions_get)) add_action('wp_ajax_'.$_GET['action'] str_replace ('-', '_', $_GET['action'])
if(!empty($_POST['action'])&&in_array($_POST['action'], $core_actions_post)) add_action('wp_ajax_'.$_POST['action'] str_replace ('-', '_', $_POST['action'])
Variable Documentation
$core_actions_get
Initial value:
= array(
    'fetch-list', 'ajax-tag-search', 'wp-compression-test', 'imgedit-preview', 'oembed-cache',
    'autocomplete-user', 'dashboard-widgets', 'logged-in',
)
Definition at line 46 of file admin-ajax.php.
$core_actions_post
Initial value:
= array(
    'oembed-cache', 'image-editor', 'delete-comment', 'delete-tag', 'delete-link',
    'delete-meta', 'delete-post', 'trash-post', 'untrash-post', 'delete-page', 'dim-comment',
    'add-link-category', 'add-tag', 'get-tagcloud', 'get-comments', 'replyto-comment',
    'edit-comment', 'add-menu-item', 'add-meta', 'add-user', 'closed-postboxes',
    'hidden-columns', 'update-welcome-panel', 'menu-get-metabox', 'wp-link-ajax',
    'menu-locations-save', 'menu-quick-search', 'meta-box-order', 'get-permalink',
    'sample-permalink', 'inline-save', 'inline-save-tax', 'find_posts', 'widgets-order',
    'save-widget', 'delete-inactive-widgets', 'set-post-thumbnail', 'date_format', 'time_format',
    'wp-remove-post-lock', 'dismiss-wp-pointer', 'upload-attachment', 'get-attachment',
    'query-attachments', 'save-attachment', 'save-attachment-compat', 'send-link-to-editor',
    'send-attachment-to-editor', 'save-attachment-order', 'heartbeat', 'get-revision-diffs',
    'save-user-color-scheme', 'update-widget', 'query-themes', 'parse-embed', 'set-attachment-thumbnail',
    'parse-media-shortcode', 'destroy-sessions', 'install-plugin', 'update-plugin', 'press-this-save-post',
    'press-this-add-category', 'crop-image', 'generate-password', 'save-wporg-username',
)
Definition at line 51 of file admin-ajax.php.
$core_actions_post[] = 'wp-fullscreen-save-post'
Definition at line 69 of file admin-ajax.php.
const DOING_AJAX true
Executing AJAX process.
Since
2.1.0
Definition at line 16 of file admin-ajax.php.
Referenced by GFLocking\__construct(), check_upload_size(), WP_Terms_List_Table\column_name(), GFForms\deprecate_add_on_methods(), GravityView_API\directory_link(), WP_Customize_Manager\doing_ajax(), GF_Field_FileUpload\get_field_input(), WP_Terms_List_Table\handle_row_actions(), GFForms\init(), GravityView_Plugin\is_admin(), GFForms\is_gravity_ajax_action(), GV_License_Handler\license_call(), WP_Comments_List_Table\prepare_items(), GFForms\process_exterior_pages(), WP_Ajax_Response\send(), WP_List_Table\set_pagination_args(), GravityView_Extension\settings(), themes_api(), wp_die(), and wp_send_json().
if (is_user_logged_in()) else
Initial value:
{
    do_action( 'wp_ajax_nopriv_' . $_REQUEST['action'] )
Definition at line 90 of file admin-ajax.php.
if(!defined('WP_ADMIN'))
Load WordPress Bootstrap.
Definition at line 17 of file admin-ajax.php.
if (!empty($_GET['action'])&&in_array($_GET['action'], $core_actions_get)) add_action('wp_ajax_'.$_GET['action'] str_replace('-', '_', $_GET['action'])
Definition at line 73 of file admin-ajax.php.
Referenced by GF_Installation_Wizard\__construct(), WP_Customize_Setting\__construct(), getid3_handler\__construct(), _autop_newline_preservation_helper(), Text_Diff_Renderer_inline\_changed(), _copy_image_file(), ftp\_data_prepare(), _deep_replace(), _fix_attachment_links(), _get_page_link(), _get_template_edit_filename(), GravityView_Field_Time\_modify_query_sort_by_time_hack(), _post_format_get_term(), _post_format_get_terms(), _post_format_link(), _post_format_wp_get_object_terms(), Text_Diff_Renderer_inline\_splitOnWords(), WP_Text_Diff_Renderer_inline\_splitOnWords(), WP_oEmbed\_strip_newlines(), _wp_ajax_add_hierarchical_term(), _wp_handle_upload(), _wp_relative_upload_path(), _wp_specialchars(), GFPaymentAddOn\add_creditcard_token_input(), WP_Press_This\add_editor_style(), add_editor_style(), GFSettings\add_settings_page(), Custom_Background\admin_page(), getid3_apetag\Analyze(), getid3_id3v2\Analyze(), getid3_asf\Analyze(), antispambot(), attachment_submitbox_metadata(), attachment_url_to_postid(), WP_Embed\autoembed(), WP_Http\block_request(), bulk_edit_posts(), WP_REST_Request\canonicalize_header_name(), capital_P_dangit(), AtomParser\cdata(), Plugin_Upgrader\check_package(), Theme_Upgrader\check_package(), GFAutoUpgrade\check_update(), clean_pre(), WP_MS_Users_List_Table\column_blogs(), WP_Customize_Theme_Control\content_template(), GFFormsModel\copy_post_image(), getid3_lib\CopyTagsToComments(), WP_Site_Icon\create_attachment_object(), Custom_Image_Header\create_attachment_object(), GFFormsModel\create_post(), customize_themes_print_templates(), SMTP\data(), WP_Filesystem_Direct\delete(), GFFormsModel\delete_physical_file(), getid3_id3v2\DeUnsynchronise(), PHPMailer\DKIM_Add(), PHPMailer\DKIM_BodyC(), WP_Styles\do_item(), do_trackbacks(), SMTP\edebug(), PHPMailer\edebug(), edit_post(), _WP_Editors\editor_settings(), PHPMailer\encodeHeader(), PHPMailer\encodeQ(), PHPMailer\encodeQP(), WP_Customize_Widgets\enqueue_scripts(), ent2ncr(), esc_js(), esc_url(), export_wp(), WP_Plugins_List_Table\extra_tablenav(), WP_Filesystem_Base\find_folder(), PHPMailer\fixEOL(), force_balance_tags(), GravityView_Merge_Tags\format_date(), GravityView_oEmbed\generate_entry_output(), WP_Rewrite\generate_rewrite_rules(), get_adjacent_post_link(), get_adjacent_post_rel_link(), get_attachment_link(), get_author_posts_url(), get_bloginfo(), get_blogs_of_user(), get_body_class(), get_boundary_post_rel_link(), GF_Field_CAPTCHA\get_captcha(), get_category_by_path(), get_comment_author_url_link(), get_comment_excerpt(), WP_Comment_Query\get_comment_ids(), get_comments_number_text(), GFFormDisplay\get_conditional_logic(), get_day_link(), get_feed_link(), GFFormDisplay\get_field(), GFFormDisplay\get_field_content(), WP_Widget\get_field_id(), GF_Field_FileUpload\get_field_input(), get_file_data(), GFFormsModel\get_file_upload_path(), GravityView_Field_FileUpload\get_files_array(), GF_Field\get_first_input_id(), GFFormsModel\get_form_id(), GravityView_Merge_Tags\get_format_from_modifiers(), get_home_path(), get_inline_data(), GF_Field_CAPTCHA\get_math_captcha(), get_month_link(), WP_Rewrite\get_month_permastruct(), get_page_by_path(), get_parent_post_rel_link(), get_permalink(), GFFormsModel\get_post_field_value(), get_post_format(), get_post_permalink(), WP_Query\get_posts(), GFFormsModel\get_prepared_input_value(), WP_oEmbed\get_provider(), get_sample_permalink(), get_sample_permalink_html(), GravityView_Widget_Search\get_search_filter_details(), get_search_link(), get_shortcut_link(), WP_Meta_Query\get_sql(), get_stylesheet_directory_uri(), WP_Theme\get_stylesheet_directory_uri(), wpdb\get_table_from_query(), get_template_directory_uri(), WP_Theme\get_template_directory_uri(), get_term_link(), get_the_content_feed(), get_theme_root_uri(), GF_Field_Post_Image\get_value_entry_detail(), GF_Field_FileUpload\get_value_entry_detail(), GF_Field_Address\get_value_entry_detail(), GF_Field_Address\get_value_export(), GF_Field_Post_Image\get_value_merge_tag(), GF_Field_FileUpload\get_value_merge_tag(), GF_Field_CreditCard\get_value_save_entry(), GF_Field_Checkbox\get_value_submission(), GF_Field\get_value_submission(), WP_Media_List_Table\get_views(), get_year_link(), WP_Rewrite\get_year_permastruct(), GFFormDisplay\gform_footer(), ftp_base\glob_pattern_match(), gravityview_field_output(), gravityview_format_link(), gravityview_get_map_link(), GFFormDisplay\handle_confirmation(), getid3_lib\hash_data(), getid3_asf\HeaderExtensionObjectDataParse(), WP_Press_This\html(), iframe_header(), image_add_caption(), image_downsize(), getid3_lib\ImageExtFromMime(), WP_Locale\init(), WP_Upgrader\install_package(), GFFormsModel\is_duplicate(), GF_Field\is_value_submission_empty(), TracTickets\isTracTicketClosed(), like_escape(), GravityView_Edit_Entry\load_components(), WP_Filesystem_MockFS\locate_parent_node(), login_header(), getid3_id3v1\LookupGenreID(), getid3_lyrics3\Lyrics3LyricsTimestampParse(), Gettext_Translations\make_headers(), Gettext_Translations\make_plural_form_function(), make_site_theme_from_oldschool(), make_url_footnote(), GFAddOn\maybe_override_field_value(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), WP_Filesystem_MockFS\mkdir(), WP_Rewrite\mod_rewrite_rules(), ms_site_check(), PHPMailer\msgHTML(), network_step2(), next_post(), normalize_whitespace(), getid3_lib\NormalizeBinaryPoint(), getID3\openfile(), paginate_links(), WP_Query\parse_query(), WP\parse_request(), WP_Query\parse_search(), GFForms\parse_shortcode(), getid3_id3v2\ParseID3v2Frame(), getid3_id3v2\ParseID3v2GenreString(), getid3_flac\parseMETAdata(), getid3_flac\parsePICTURE(), getid3_riff\ParseRIFF(), wp_xmlrpc_server\pingback_ping(), post_tags_meta_box(), post_trackback_meta_box(), wpdb\prepare(), GravityView_Widget_Search\prepare_field_filter(), WP_MS_Sites_List_Table\prepare_items(), WP_Plugins_List_Table\prepare_items(), PHPMailer\preSend(), previous_post(), WP_Http\processHeaders(), redirect_canonical(), remove_accents(), GFPaymentAddOn\remove_spaces_from_card_number(), WP_Customize_Control\render(), WP_Widget_Area_Customize_Control\render_content(), WP_Customize_Control\render_content(), WP_Screen\render_per_page_options(), GravityView_Merge_Tags\replace_get_variables(), GravityView_Field_Payment_Amount\replace_merge_tag(), GravityView_Field_Created_By\replace_merge_tag(), GravityView_Field_Date_Created\replace_merge_tag(), GravityView_Field_Is_Fulfilled\replace_merge_tag(), GravityView_Field\replace_merge_tag(), GFFormDisplay\replace_save_variables(), safecss_filter_attr(), sanitize_file_name(), sanitize_option(), sanitize_post_field(), sanitize_text_field(), sanitize_title_with_dashes(), GFFormsModel\save_input(), getid3_handler\saveAttachment(), search_theme_directories(), PHPMailer\secureHeader(), send_confirmation_on_profile_email(), WP_Automatic_Updater\send_debug_email(), WP_HTTP_Proxy\send_through_proxy(), SMTP\sendCommand(), WP_Screen\set_parentage(), set_screen_options(), GFSettings\settings_page(), WP_Query\setup_postdata(), WP_Ajax_UnitTestCase\setUpBeforeClass(), WP_Embed\shortcode(), WP_Press_This\side_load_images(), GFExport\start_export(), Custom_Image_Header\step_2(), Custom_Image_Header\step_3(), POP3\strip_clf(), Custom_Image_Header\take_action(), the_content(), the_content_rss(), Text_Diff\trimNewlines(), twentyfifteen_nav_description(), twentyfifteen_search_form_modify(), twentytwelve_mce_css(), SimplePie_Net_IPv6\uncompress(), update_core(), update_option_new_admin_email(), upgrade_350(), GFAsyncUpload\upload(), url_shorten(), url_to_postid(), GF_Field_CAPTCHA\validate(), wp_ajax_ajax_tag_search(), wp_ajax_crop_image(), wp_basename(), wp_crop_image(), wp_debug_backtrace_summary(), wp_delete_attachment(), wp_encode_emoji(), wp_filter_oembed_result(), wp_generate_attachment_metadata(), wp_generate_tag_cloud(), wp_get_attachment_thumb_file(), wp_get_attachment_thumb_url(), wp_get_attachment_url(), wp_guess_url(), wp_iso_descrambler(), wp_kses_attr_check(), wp_kses_normalize_entities(), wp_kses_split2(), wp_link_pages(), wp_list_bookmarks(), wp_make_content_images_responsive(), wp_match_mime_types(), wp_mime_type_icon(), wp_mkdir_p(), wp_nonce_url(), wp_normalize_path(), wp_page_menu(), wp_post_mime_type_where(), wp_prepare_attachment_for_js(), wp_prepare_revisions_for_js(), wp_replace_in_html_tags(), wp_set_post_terms(), wp_simplepie_autoload(), wp_sprintf(), wp_star_rating(), wp_staticize_emoji(), wp_staticize_emoji_for_email(), wp_timezone_choice(), wp_trim_excerpt(), wp_unique_filename(), wp_update_user(), wp_upload_bits(), wp_upload_dir(), wp_video_shortcode(), wp_widget_rss_form(), wpautop(), wpmu_create_blog(), wpmu_welcome_notification(), wpmu_welcome_user_notification(), wptexturize(), wptexturize_primes(), and AtomParser\xml_escape().
if (!empty($_POST['action'])&&in_array($_POST['action'], $core_actions_post)) add_action('wp_ajax_'.$_POST['action'] str_replace('-', '_', $_POST['action'])
Definition at line 76 of file admin-ajax.php.