GravityView: admin-footer.php File Reference
admin-footer.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$text = sprintf(__('Thank you for creating with <a href="%s">WordPress</a>.'), __('https://wordpress.org/'))
Variable Documentation
$text = sprintf(__('Thank you for creating with <a href="%s">WordPress</a>.'), __('https://wordpress.org/'))
Definition at line 29 of file admin-footer.php.
Referenced by __(), _c(), _e(), _ex(), GravityView_Field\_filter_gform_replace_merge_tags(), _wptexturize_pushpop_element(), _x(), adjacent_image_link(), MagpieRSS\append(), MagpieRSS\append_content(), attribute_escape(), balanceTags(), cancel_comment_reply_link(), capital_P_dangit(), clean_pre(), convert_smilies(), edit_comment_link(), edit_post_link(), ent2ncr(), getid3_handler\error(), esc_attr(), esc_attr__(), esc_attr_e(), esc_attr_x(), esc_html(), esc_html__(), esc_html_e(), esc_html_x(), esc_js(), wpdb\esc_like(), esc_textarea(), MagpieRSS\feed_cdata(), force_balance_tags(), format_for_editor(), funky_javascript_fix(), get_archives_link(), get_cancel_comment_reply_link(), GFAutoUpgrade\get_changelog(), get_submit_button(), WP_Press_This\get_suggested_content(), WP_Theme_Install_List_Table\get_views(), WP_Plugin_Install_List_Table\get_views(), WP_MS_Themes_List_Table\get_views(), WP_Plugins_List_Table\get_views(), PHPMailer\has8bitChars(), WP_Filesystem_Base\is_binary(), js_escape(), like_escape(), make_clickable(), GravityView_Widget\maybe_do_shortcode(), next_image_link(), PHPMailer\normalizeBreaks(), popuplinks(), previous_image_link(), GravityView_Merge_Tags\replace_get_variables(), GravityView_Merge_Tags\replace_gv_merge_tags(), GravityView_Field_Payment_Amount\replace_merge_tag(), GravityView_Field_Created_By\replace_merge_tag(), GravityView_Field_Date_Created\replace_merge_tag(), GravityView_Field_Is_Fulfilled\replace_merge_tag(), GravityView_Field\replace_merge_tag(), GFFormDisplay\replace_save_variables(), GravityView_Merge_Tags\replace_variables(), GravityView_API\replace_variables(), request_filesystem_credentials(), WP_List_Table\search_box(), GF_Installation_Wizard_Step\set_field_validation_result(), GF_Installation_Wizard_Step\set_validation_summary(), GravityView_Settings\settings_edd_license(), shortcode_parse_atts(), POP3\strip_clf(), SimplePie_Sanitize\strip_tag(), submit_button(), the_media_upload_tabs(), the_shortlink(), translate(), translate_with_context(), translate_with_gettext_context(), GFFormsModel\try_convert_float(), getid3_handler\warning(), welcome_user_msg_filter(), WP_Widget_Text\widget(), wp_dashboard_right_now(), wp_get_archives(), wp_get_attachment_link(), wp_page_menu(), wp_pre_kses_less_than(), wp_rel_nofollow(), wp_rel_nofollow_callback(), wp_richedit_pre(), wp_staticize_emoji(), wp_trim_excerpt(), wp_trim_words(), and wptexturize().