GravityView: admin-post.php File Reference
admin-post.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$action = empty($_REQUEST['action']) ? '' : $_REQUEST['action']
else
Variable Documentation
$action = empty($_REQUEST['action']) ? '' : $_REQUEST['action']
Definition at line 31 of file admin-post.php.
Referenced by WP_Terms_List_Table\__construct(), GV_License_Handler\_get_edd_settings(), WP_Ajax_UnitTestCase\_handleAjax(), _redirect_to_about_wordpress(), _wp_ajax_add_hierarchical_term(), _wp_handle_upload(), WP_Ajax_Response\add(), GFPaymentAddOn\add_pending_payment(), GFPaymentAddOn\add_subscription_payment(), GFPaymentAddOn\cancel_subscription(), WP_MS_Users_List_Table\column_blogs(), GFPaymentAddOn\complete_payment(), WP_Themes_List_Table\display_rows(), doing_action(), WP_Customize_Manager\doing_ajax(), GFPaymentAddOn\expire_subscription(), GFPaymentAddOn\fail_payment(), GFPaymentAddOn\fail_subscription_payment(), GFFeedAddOn\feed_list_page(), GFFormList\form_list_page(), GFForms\get_addon_info(), GFFeedAddOn\get_bulk_action(), GravityView_Admin_Duplicate_View\get_clone_view_link(), get_delete_post_link(), get_edit_post_link(), GF_Field_Password\get_field_input(), GF_Field_CreditCard\get_field_input(), GFFormDisplay\get_form(), WP_Theme_Install_List_Table\get_views(), WP_Plugin_Install_List_Table\get_views(), WP_Comments_List_Table\handle_row_actions(), GFEntryList\leads_page(), maybe_process_confirmation_list_action(), GFForms\parse_shortcode(), plugins_api(), GFPaymentAddOn\post_payment_action(), post_submit_meta_box(), GFFeedAddOn\process_bulk_action(), GFPaymentAddOn\process_callback_action(), GFFeedAddOn\process_single_action(), GFPaymentAddOn\refund_payment(), GFFormDisplay\replace_save_variables(), WP_List_Table\row_actions(), WP_Customize_Manager\save(), WP_Ajax_UnitTestCase\setUpBeforeClass(), WP_Theme_Install_List_Table\single_row(), themes_api(), GFPaymentAddOn\void_authorization(), wp_admin_bar_new_content_menu(), wp_ajax_add_link_category(), wp_ajax_add_user(), wp_ajax_delete_page(), wp_ajax_delete_post(), wp_ajax_get_comments(), wp_ajax_replyto_comment(), wp_ajax_trash_post(), wp_ajax_untrash_post(), wp_handle_sideload(), wp_handle_upload(), wp_media_attach_action(), wp_network_dashboard_right_now(), wp_nonce_ays(), wp_nonce_field(), and wp_nonce_url().
else
Definition at line 19 of file admin-post.php.