GravityView: ajax-actions.php File Reference
ajax-actions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_ajax_add_hierarchical_term ()
Ajax handler for adding a hierarchical term.
_wp_ajax_delete_comment_response ($comment_id, $delta=-1)
Sends back current comment total and new page links if they need to be updated.
wp_ajax_add_link_category ($action)
Ajax handler for deleting a link category.
wp_ajax_add_menu_item ()
Ajax handler for adding a menu item.
wp_ajax_add_meta ()
Ajax handler for adding meta.
wp_ajax_add_tag ()
Ajax handler to add a tag.
wp_ajax_add_user ($action)
Ajax handler for adding a user.
wp_ajax_ajax_tag_search ()
Ajax handler for tag search.
wp_ajax_autocomplete_user ()
Ajax handler for user autocomplete.
wp_ajax_closed_postboxes ()
Ajax handler for closed post boxes.
wp_ajax_crop_image ()
AJAX handler for cropping an image.
wp_ajax_dashboard_widgets ()
Ajax handler for dashboard widgets.
wp_ajax_date_format ()
Ajax handler for date formatting.
wp_ajax_delete_comment ()
Ajax handler for deleting a comment.
wp_ajax_delete_inactive_widgets ()
Ajax handler for removing inactive widgets.
wp_ajax_delete_link ()
Ajax handler for deleting a link.
wp_ajax_delete_meta ()
Ajax handler for deleting meta.
wp_ajax_delete_page ($action)
wp_ajax_delete_post ($action)
Ajax handler for deleting a post.
wp_ajax_delete_tag ()
Ajax handler for deleting a tag.
wp_ajax_destroy_sessions ()
AJAX handler for destroying multiple open sessions for a user.
wp_ajax_dim_comment ()
Ajax handler to dim a comment.
wp_ajax_dismiss_wp_pointer ()
Ajax handler for dismissing a WordPress pointer.
wp_ajax_edit_comment ()
Ajax handler for editing a comment.
wp_ajax_fetch_list ()
Ajax handler for fetching a list table.
wp_ajax_find_posts ()
Ajax handler for querying posts for the Find Posts modal.
wp_ajax_generate_password ()
Ajax handler for generating a password.
wp_ajax_get_attachment ()
Ajax handler for getting an attachment.
wp_ajax_get_comments ($action)
Ajax handler for getting comments.
wp_ajax_get_permalink ()
Ajax handler to retrieve a permalink.
wp_ajax_get_revision_diffs ()
Ajax handler for getting revision diffs.
wp_ajax_get_tagcloud ()
Ajax handler for getting a tagcloud.
wp_ajax_heartbeat ()
Ajax handler for the Heartbeat API.
wp_ajax_hidden_columns ()
Ajax handler for hidden columns.
wp_ajax_image_editor ()
Ajax handler for image editing.
wp_ajax_imgedit_preview ()
Ajax handler for image editor previews.
wp_ajax_inline_save ()
Ajax handler for Quick Edit saving a post from a list table.
wp_ajax_inline_save_tax ()
Ajax handler for quick edit saving for a term.
wp_ajax_logged_in ()
Ajax handler for Customizer preview logged-in status.
wp_ajax_menu_get_metabox ()
Ajax handler for retrieving menu meta boxes.
wp_ajax_menu_locations_save ()
Ajax handler for menu locations save.
wp_ajax_menu_quick_search ()
Ajax handler for menu quick searching.
wp_ajax_meta_box_order ()
Ajax handler for saving the meta box order.
wp_ajax_nopriv_heartbeat ()
Ajax handler for the Heartbeat API in the no-privilege context.
wp_ajax_oembed_cache ()
Ajax handler for oEmbed caching.
wp_ajax_parse_embed ()
Apply [embed] AJAX handlers to a string.
wp_ajax_parse_media_shortcode ()
wp_ajax_press_this_add_category ()
AJAX handler for creating new category from Press This.
wp_ajax_press_this_save_post ()
AJAX handler for saving a post from Press This.
wp_ajax_query_attachments ()
Ajax handler for querying attachments.
wp_ajax_query_themes ()
Ajax handler for getting themes from themes_api().
wp_ajax_replyto_comment ($action)
Ajax handler for replying to a comment.
wp_ajax_sample_permalink ()
Ajax handler to retrieve a sample permalink.
wp_ajax_save_attachment ()
Ajax handler for updating attachment attributes.
wp_ajax_save_attachment_compat ()
Ajax handler for saving backwards compatible attachment attributes.
wp_ajax_save_attachment_order ()
Ajax handler for saving the attachment order.
wp_ajax_save_user_color_scheme ()
Ajax handler for auto-saving the selected color scheme for a user's own profile.
wp_ajax_save_widget ()
Ajax handler for saving a widget.
wp_ajax_save_wporg_username ()
Ajax handler for saving the user's WordPress.org username.
wp_ajax_send_attachment_to_editor ()
Ajax handler for sending an attachment to the editor.
wp_ajax_send_link_to_editor ()
Ajax handler for sending a link to the editor.
wp_ajax_set_attachment_thumbnail ()
AJAX handler for setting the featured image for an attachment.
wp_ajax_set_post_thumbnail ()
Ajax handler for setting the featured image.
wp_ajax_time_format ()
Ajax handler for time formatting.
wp_ajax_trash_post ($action)
Ajax handler for sending a post to the trash.
wp_ajax_untrash_post ($action)
Ajax handler to restore a post from the trash.
wp_ajax_update_plugin ()
AJAX handler for updating a plugin.
wp_ajax_update_welcome_panel ()
Ajax handler for updating whether to display the welcome panel.
wp_ajax_update_widget ()
Ajax handler for saving a widget.
wp_ajax_upload_attachment ()
Ajax handler for uploading attachments.
wp_ajax_widgets_order ()
Ajax handler for saving the widgets order.
wp_ajax_wp_compression_test ()
Ajax handler for compression testing.
wp_ajax_wp_fullscreen_save_post ()
Ajax handler for saving posts from the fullscreen editor.
wp_ajax_wp_link_ajax ()
Ajax handler for internal linking.
wp_ajax_wp_remove_post_lock ()
Ajax handler for removing a post lock.
Function Documentation
_wp_ajax_add_hierarchical_term ()
Ajax handler for adding a hierarchical term.
Since
3.1.0
Definition at line 435 of file ajax-actions.php.
References $action, current_user_can(), elseif, get_taxonomy(), get_term(), if, is_wp_error(), sanitize_title(), str_replace, term_exists(), wp_die(), wp_dropdown_categories(), wp_insert_term(), wp_popular_terms_checklist(), and wp_terms_checklist().
_wp_ajax_delete_comment_response ($comment_id, $delta = -1)
Sends back current comment total and new page links if they need to be updated.
Contrary to normal success AJAX response ("1"), die with time() on success.
Since
2.7.0
Parameters
int $comment_id
int $delta
Definition at line 344 of file ajax-actions.php.
References $comment, $page, $post_id, $url, _n(), _nx(), esc_url_raw(), get_comment(), number_format_i18n(), and wp_count_comments().
Referenced by wp_ajax_delete_comment(), and wp_ajax_dim_comment().
wp_ajax_add_link_category ($action)
Ajax handler for deleting a link category.
Since
3.1.0
Parameters
string $action Action to perform.
Definition at line 777 of file ajax-actions.php.
References $action, current_user_can(), elseif, esc_attr(), esc_html, is_wp_error(), sanitize_title(), term_exists(), wp_die(), wp_insert_term(), and wp_unslash().
wp_ajax_add_menu_item ()
Ajax handler for adding a menu item.
Since
3.1.0
This filter is documented in wp-admin/includes/nav-menu.php
Definition at line 1139 of file ajax-actions.php.
References $menu_items, ABSPATH, apply_filters(), current_user_can(), get_post(), get_post_type_object(), get_term(), is_wp_error(), walk_nav_menu_tree(), wp_die(), wp_save_nav_menu_items(), and wp_setup_nav_menu_item().
wp_ajax_add_meta ()
Ajax handler for adding meta.
Since
3.1.0
Definition at line 1220 of file ajax-actions.php.
References $now, $post, $value, __, _list_meta_row(), add_meta(), current_time(), current_user_can(), date, edit_post(), elseif, get_metadata_by_mid(), get_post(), is_protected_meta(), is_wp_error(), update_metadata_by_mid(), wp_die(), and wp_unslash().
wp_ajax_add_tag ()
Ajax handler to add a tag.
Since
3.1.0
WP_List_Table $wp_list_table
Definition at line 815 of file ajax-actions.php.
References $message, $tax, $wp_list_table, __, _get_list_table(), current_user_can(), get_ancestors(), get_taxonomy(), get_term(), is_taxonomy_hierarchical(), is_wp_error(), wp_die(), and wp_insert_term().
wp_ajax_add_user ($action)
Ajax handler for adding a user.
Since
3.1.0
WP_List_Table $wp_list_table
Parameters
string $action Action to perform.
Definition at line 1314 of file ajax-actions.php.
References $action, $user_id, $wp_list_table, __, _get_list_table(), current_user_can(), edit_user(), elseif, is_wp_error(), and wp_die().
wp_ajax_ajax_tag_search ()
Ajax handler for tag search.
Since
3.1.0
Filter the minimum number of characters required to fire a tag search via AJAX.
Since
4.0.0
Parameters
int $characters The minimum number of characters required. Default 2.
object $tax The taxonomy object.
string $s The search term.
Definition at line 108 of file ajax-actions.php.
References $s, $tax, _x, apply_filters(), current_user_can(), get_taxonomy(), get_terms(), sanitize_key(), str_replace, wp_die(), and wp_unslash().
wp_ajax_autocomplete_user ()
Ajax handler for user autocomplete.
Since
3.4.0
This filter is documented in wp-admin/user-new.php
Definition at line 245 of file ajax-actions.php.
References $field, $id, $user, _x, absint(), apply_filters(), current_user_can(), get_current_blog_id(), get_users(), is_multisite(), is_super_admin(), wp_die(), wp_is_large_network(), and wp_json_encode().
wp_ajax_closed_postboxes ()
Ajax handler for closed post boxes.
Since
3.1.0
Definition at line 1358 of file ajax-actions.php.
References $page, $user, sanitize_key(), update_user_option(), and wp_die().
wp_ajax_crop_image ()
AJAX handler for cropping an image.
Since
4.3.0
WP_Site_Icon $wp_site_icon
This filter is documented in wp-admin/custom-header.php
Fires before a cropped image is saved.
Allows to add filters to modify the way a cropped image is saved.
Since
4.3.0
Parameters
string $context The Customizer control requesting the cropped image.
int $attachment_id The attachment ID of the original image.
string $cropped Path to the cropped image file.
This filter is documented in wp-admin/custom-header.php
Filter the cropped image attachment metadata.
Since
4.3.0
See also
wp_generate_attachment_metadata()
Parameters
array $metadata Attachment metadata.
Filter the attachment ID for a cropped image.
Since
4.3.0
Parameters
int $attachment_id The attachment ID of the cropped image.
string $context The Customizer control requesting the cropped image.
Definition at line 3185 of file ajax-actions.php.
References $metadata, $size, $url, __, absint(), ABSPATH, add_filter(), apply_filters(), current_user_can(), do_action(), get_post_meta(), is_wp_error(), remove_filter(), str_replace, wp_crop_image(), wp_delete_file(), wp_generate_attachment_metadata(), wp_get_attachment_url(), wp_insert_attachment(), wp_prepare_attachment_for_js(), wp_send_json_error(), wp_send_json_success(), and wp_update_attachment_metadata().
wp_ajax_dashboard_widgets ()
Ajax handler for dashboard widgets.
Since
3.4.0
Definition at line 305 of file ajax-actions.php.
References $pagenow, ABSPATH, set_current_screen(), wp_dashboard_primary(), and wp_die().
wp_ajax_date_format ()
Ajax handler for date formatting.
Since
3.1.0
Definition at line 2194 of file ajax-actions.php.
References date_i18n(), sanitize_option(), wp_die(), and wp_unslash().
wp_ajax_delete_comment ()
Ajax handler for deleting a comment.
Since
3.1.0
Definition at line 527 of file ajax-actions.php.
References $comment, $id, _wp_ajax_delete_comment_response(), current_user_can(), elseif, get_comment(), wp_delete_comment(), wp_die(), wp_get_comment_status(), wp_spam_comment(), wp_trash_comment(), wp_unspam_comment(), and wp_untrash_comment().
wp_ajax_delete_inactive_widgets ()
Ajax handler for removing inactive widgets.
Since
4.4.0
Definition at line 1947 of file ajax-actions.php.
References $sidebars_widgets, current_user_can(), do_action(), get_option(), update_option(), wp_die(), wp_get_sidebars_widgets(), and wp_set_sidebars_widgets().
wp_ajax_delete_link ()
Ajax handler for deleting a link.
Since
3.1.0
Definition at line 600 of file ajax-actions.php.
References $id, $link, current_user_can(), get_bookmark(), is_wp_error(), wp_delete_link(), and wp_die().
wp_ajax_delete_meta ()
Ajax handler for deleting meta.
Since
3.1.0
Definition at line 622 of file ajax-actions.php.
References $id, current_user_can(), delete_meta(), get_metadata_by_mid(), is_protected_meta(), and wp_die().
wp_ajax_delete_page ($action)
Since
3.1.0
Parameters
string $action
Definition at line 709 of file ajax-actions.php.
References $action, $id, current_user_can(), get_post(), wp_delete_post(), and wp_die().
wp_ajax_delete_post ($action)
Ajax handler for deleting a post.
Since
3.1.0
Parameters
string $action Action to perform.
Definition at line 643 of file ajax-actions.php.
References $action, $id, current_user_can(), get_post(), wp_delete_post(), and wp_die().
wp_ajax_delete_tag ()
Ajax handler for deleting a tag.
Since
3.1.0
Definition at line 575 of file ajax-actions.php.
References $tax, current_user_can(), get_taxonomy(), get_term(), is_wp_error(), wp_delete_term(), and wp_die().
wp_ajax_destroy_sessions ()
AJAX handler for destroying multiple open sessions for a user.
Since
4.1.0
Definition at line 3027 of file ajax-actions.php.
References $message, $user, __, current_user_can(), elseif, get_current_user_id(), WP_Session_Tokens\get_instance(), wp_get_session_token(), wp_send_json_error(), and wp_send_json_success().
wp_ajax_dim_comment ()
Ajax handler to dim a comment.
Since
3.1.0
Definition at line 732 of file ajax-actions.php.
References $comment, $id, __, _wp_ajax_delete_comment_response(), current_user_can(), get_comment(), is_wp_error(), wp_die(), wp_get_comment_status(), and wp_set_comment_status().
wp_ajax_dismiss_wp_pointer ()
Ajax handler for dismissing a WordPress pointer.
Since
3.1.0
Definition at line 2286 of file ajax-actions.php.
References get_current_user_id(), get_user_meta(), sanitize_key(), update_user_meta(), and wp_die().
wp_ajax_edit_comment ()
Ajax handler for editing a comment.
Since
3.1.0
WP_List_Table $wp_list_table
Definition at line 1094 of file ajax-actions.php.
References $comment, $wp_list_table, __, _get_list_table(), current_user_can(), edit_comment(), get_comment(), and wp_die().
wp_ajax_fetch_list ()
Ajax handler for fetching a list table.
Since
3.1.0
WP_List_Table $wp_list_table
Definition at line 85 of file ajax-actions.php.
References $wp_list_table, _get_list_table(), and wp_die().
wp_ajax_find_posts ()
Ajax handler for querying posts for the Find Posts modal.
See also
window.findPosts
Since
3.1.0
Definition at line 1738 of file ajax-actions.php.
References $alt, $post, $s, $title, __, esc_attr(), esc_html, get_post_types(), get_posts(), mysql2date(), wp_send_json_error(), wp_send_json_success(), and wp_unslash().
wp_ajax_generate_password ()
Ajax handler for generating a password.
Since
4.4.0
Definition at line 3297 of file ajax-actions.php.
References wp_send_json_success().
wp_ajax_get_attachment ()
Ajax handler for getting an attachment.
Since
3.5.0
Definition at line 2310 of file ajax-actions.php.
References $id, $post, absint(), current_user_can(), get_post(), wp_prepare_attachment_for_js(), wp_send_json_error(), and wp_send_json_success().
wp_ajax_get_comments ($action)
Ajax handler for getting comments.
Since
3.1.0
WP_List_Table $wp_list_table int $post_id
Parameters
string $action Action to perform.
Definition at line 921 of file ajax-actions.php.
References $action, $comment, $id, $post_id, $wp_list_table, _get_list_table(), absint(), current_user_can(), get_comment(), and wp_die().
wp_ajax_get_permalink ()
Ajax handler to retrieve a permalink.
Since
3.1.0
Definition at line 1562 of file ajax-actions.php.
References $post_id, get_preview_post_link(), and wp_die().
wp_ajax_get_revision_diffs ()
Ajax handler for getting revision diffs.
Since
3.6.0
Definition at line 2749 of file ajax-actions.php.
References $post, ABSPATH, current_user_can(), get_post(), wp_get_post_revisions(), wp_get_revision_ui_diff(), wp_send_json_error(), and wp_send_json_success().
wp_ajax_get_tagcloud ()
Ajax handler for getting a tagcloud.
Since
3.1.0
Definition at line 872 of file ajax-actions.php.
References $tags, $tax, current_user_can(), get_taxonomy(), get_terms(), is_wp_error(), sanitize_key(), wp_die(), and wp_generate_tag_cloud().
wp_ajax_heartbeat ()
Ajax handler for the Heartbeat API.
Runs when the user is logged in.
Since
3.6.0
Filter the Heartbeat response received.
Since
3.6.0
Parameters
array $response The Heartbeat response.
array $data The $_POST data sent.
string $screen_id The screen id.
Filter the Heartbeat response sent.
Since
3.6.0
Parameters
array $response The Heartbeat response.
string $screen_id The screen id.
Fires when Heartbeat ticks in logged-in environments.
Allows the transport to be easily replaced with long-polling.
Since
3.6.0
Parameters
array $response The Heartbeat response.
string $screen_id The screen id.
Definition at line 2674 of file ajax-actions.php.
References apply_filters(), do_action(), sanitize_key(), wp_send_json(), wp_send_json_error(), and wp_unslash().
wp_ajax_hidden_columns ()
Ajax handler for hidden columns.
Since
3.1.0
Definition at line 1390 of file ajax-actions.php.
References $page, $user, sanitize_key(), update_user_option(), and wp_die().
wp_ajax_image_editor ()
Ajax handler for image editing.
Since
3.1.0
Definition at line 2075 of file ajax-actions.php.
References $msg, ABSPATH, current_user_can(), wp_die(), wp_image_editor(), wp_json_encode(), wp_restore_image(), and wp_save_image().
wp_ajax_imgedit_preview ()
Ajax handler for image editor previews.
Since
3.1.0
Definition at line 214 of file ajax-actions.php.
References $post_id, ABSPATH, current_user_can(), stream_preview_image(), and wp_die().
wp_ajax_inline_save ()
Ajax handler for Quick Edit saving a post from a list table.
Since
3.1.0
WP_List_Table $wp_list_table
This filter is documented in wp-admin/includes/class-wp-posts-list-table.php
Definition at line 1588 of file ajax-actions.php.
References $mode, $post, $post_ID, $wp_list_table, __, _get_list_table(), apply_filters(), ARRAY_A, current_user_can(), edit_post(), esc_html, get_current_user_id(), get_post(), get_taxonomy(), wp_check_post_lock(), wp_die(), wp_slash(), and wp_unique_post_slug().
wp_ajax_inline_save_tax ()
Ajax handler for quick edit saving for a term.
Since
3.1.0
WP_List_Table $wp_list_table
Definition at line 1686 of file ajax-actions.php.
References $id, $tax, $updated, $wp_list_table, __, _get_list_table(), current_user_can(), get_taxonomy(), get_term(), is_wp_error(), sanitize_key(), wp_die(), and wp_update_term().
wp_ajax_logged_in ()
Ajax handler for Customizer preview logged-in status.
Since
3.4.0
Definition at line 326 of file ajax-actions.php.
References wp_die().
wp_ajax_menu_get_metabox ()
Ajax handler for retrieving menu meta boxes.
Since
3.1.0
This filter is documented in wp-admin/includes/nav-menu.php
Definition at line 1427 of file ajax-actions.php.
References ABSPATH, apply_filters(), current_user_can(), elseif, get_post_types(), get_taxonomies(), null, wp_die(), and wp_json_encode().
wp_ajax_menu_locations_save ()
Ajax handler for menu locations save.
Since
3.1.0
Definition at line 1501 of file ajax-actions.php.
References current_user_can(), set_theme_mod(), and wp_die().
wp_ajax_menu_quick_search ()
Ajax handler for menu quick searching.
Since
3.1.0
Definition at line 1546 of file ajax-actions.php.
References _wp_ajax_menu_quick_search(), ABSPATH, current_user_can(), and wp_die().
wp_ajax_meta_box_order ()
Ajax handler for saving the meta box order.
Since
3.1.0
Definition at line 1516 of file ajax-actions.php.
References $page, $user, sanitize_key(), update_user_option(), and wp_die().
wp_ajax_nopriv_heartbeat ()
Ajax handler for the Heartbeat API in the no-privilege context.
Runs when the user is not logged in.
Since
3.6.0
Filter Heartbeat AJAX response in no-privilege environments.
Since
3.6.0
Parameters
array | object $response The no-priv Heartbeat response object or array.
array $data An array of data passed via $_POST.
string $screen_id The screen id.
Filter Heartbeat AJAX response when no data is passed.
Since
3.6.0
Parameters
array | object $response The Heartbeat response object or array.
string $screen_id The screen id.
Fires when Heartbeat ticks in no-privilege environments.
Allows the transport to be easily replaced with long-polling.
Since
3.6.0
Parameters
array | object $response The no-priv Heartbeat response.
string $screen_id The screen id.
Definition at line 22 of file ajax-actions.php.
References apply_filters(), do_action(), sanitize_key(), wp_send_json(), and wp_unslash().
wp_ajax_oembed_cache ()
Ajax handler for oEmbed caching.
Since
3.1.0
WP_Embed $wp_embed
Definition at line 235 of file ajax-actions.php.
References $GLOBALS, and wp_die().
wp_ajax_parse_embed ()
Apply [embed] AJAX handlers to a string.
Since
4.0.0
WP_Post $post Global $post. WP_Embed $wp_embed Embed API instance. WP_Scripts $wp_scripts
Definition at line 2870 of file ajax-actions.php.
References $post, $styles, $url, $wp_scripts, __, current_user_can(), do_shortcode(), elseif, esc_html, get_post(), get_shortcode_regex(), has_shortcode(), is_ssl(), setup_postdata(), shortcode_parse_atts(), wp_print_scripts(), wp_send_json_error(), wp_send_json_success(), wp_unslash(), and wpview_media_sandbox_styles().
wp_ajax_parse_media_shortcode ()
Since
4.0.0
WP_Post $post WP_Scripts $wp_scripts
Definition at line 2962 of file ajax-actions.php.
References $post, $styles, $wp_scripts, __, current_user_can(), do_shortcode(), get_post(), setup_postdata(), wp_print_scripts(), wp_send_json_error(), wp_send_json_success(), wp_underscore_playlist_templates(), wp_unslash(), and wpview_media_sandbox_styles().
wp_ajax_press_this_add_category ()
AJAX handler for creating new category from Press This.
Since
4.2.0
WP_Press_This $wp_press_this
Definition at line 3170 of file ajax-actions.php.
References $GLOBALS, and ABSPATH.
wp_ajax_press_this_save_post ()
AJAX handler for saving a post from Press This.
Since
4.2.0
WP_Press_This $wp_press_this
Definition at line 3155 of file ajax-actions.php.
References $GLOBALS, and ABSPATH.
wp_ajax_query_attachments ()
Ajax handler for querying attachments.
Since
3.5.0
Filter the arguments passed to WP_Query during an AJAX call for querying attachments.
Since
3.7.0
See also
WP_Query::parse_query()
Parameters
array $query An array of query variables.
Definition at line 2337 of file ajax-actions.php.
References $keys, apply_filters(), current_user_can(), get_post_type_object(), get_taxonomies_for_attachments(), wp_send_json_error(), and wp_send_json_success().
wp_ajax_query_themes ()
Ajax handler for getting themes from themes_api().
Since
3.9.0
array $themes_allowedtags array $theme_field_defaults
This filter is documented in wp-admin/includes/class-wp-theme-install-list-table.php
Definition at line 2812 of file ajax-actions.php.
References $theme, $theme_field_defaults, $themes_allowedtags, $user, add_query_arg(), apply_filters(), current_user_can(), get_user_option(), is_wp_error(), network_admin_url(), number_format_i18n(), set_url_scheme(), themes_api(), wp_kses(), wp_parse_args(), wp_send_json_error(), wp_send_json_success(), wp_star_rating(), and wp_unslash().
wp_ajax_replyto_comment ($action)
Ajax handler for replying to a comment.
Since
3.1.0
WP_List_Table $wp_list_table
Parameters
string $action Action to perform.
Definition at line 973 of file ajax-actions.php.
References $action, $comment, $post, $user, $user_ID, $wp_list_table, __, _get_list_table(), _n(), _nx(), _wp_dashboard_recent_comments_row(), absint(), ABSPATH, current_user_can(), elseif, get_comment(), get_post(), kses_init_filters(), kses_remove_filters(), number_format_i18n(), wp_count_comments(), wp_die(), wp_new_comment(), wp_set_comment_status(), and wp_slash().
wp_ajax_sample_permalink ()
Ajax handler to retrieve a sample permalink.
Since
3.1.0
Definition at line 1573 of file ajax-actions.php.
References $post_id, $title, get_sample_permalink_html(), null, and wp_die().
wp_ajax_save_attachment ()
Ajax handler for updating attachment attributes.
Since
3.5.0
Definition at line 2389 of file ajax-actions.php.
References $alt, $id, $label, $post, absint(), ARRAY_A, current_user_can(), get_post(), get_post_meta(), sanitize_text_field(), update_post_meta(), wp_attachment_is(), wp_delete_post(), wp_get_attachment_id3_keys(), wp_get_attachment_metadata(), wp_send_json_error(), wp_send_json_success(), wp_slash(), wp_strip_all_tags(), wp_unslash(), wp_update_attachment_metadata(), and wp_update_post().
wp_ajax_save_attachment_compat ()
Ajax handler for saving backwards compatible attachment attributes.
Since
3.5.0
This filter is documented in wp-admin/includes/media.php
Definition at line 2463 of file ajax-actions.php.
References $errors, $id, $post, absint(), apply_filters(), ARRAY_A, current_user_can(), get_attachment_taxonomies(), get_post(), wp_prepare_attachment_for_js(), wp_send_json_error(), wp_send_json_success(), wp_set_object_terms(), and wp_update_post().
wp_ajax_save_attachment_order ()
Ajax handler for saving the attachment order.
Since
3.5.0
Definition at line 2510 of file ajax-actions.php.
References $attachments, $post_id, absint(), current_user_can(), get_post(), wp_send_json_error(), wp_send_json_success(), and wp_update_post().
wp_ajax_save_user_color_scheme ()
Ajax handler for auto-saving the selected color scheme for a user's own profile.
Since
3.8.0
array $_wp_admin_css_colors
Definition at line 2784 of file ajax-actions.php.
References get_current_user_id(), get_user_meta(), sanitize_key(), update_user_meta(), wp_send_json_error(), and wp_send_json_success().
wp_ajax_save_widget ()
Ajax handler for saving a widget.
Since
3.1.0
array $wp_registered_widgets array $wp_registered_widget_controls array $wp_registered_widget_updates
Fires early when editing the widgets displayed in sidebars.
Since
2.8.0
Fires early when editing the widgets displayed in sidebars.
Since
2.8.0
This action is documented in wp-admin/widgets.php
This action is documented in wp-admin/widgets.php
Definition at line 1842 of file ajax-actions.php.
References $form, $name, $wp_registered_widget_controls, $wp_registered_widget_updates, $wp_registered_widgets, __, current_user_can(), do_action(), elseif, wp_die(), wp_get_sidebars_widgets(), and wp_set_sidebars_widgets().
wp_ajax_save_wporg_username ()
Ajax handler for saving the user's WordPress.org username.
Since
4.4.0
Definition at line 3306 of file ajax-actions.php.
References current_user_can(), get_current_user_id(), update_user_meta(), wp_send_json_error(), wp_send_json_success(), and wp_unslash().
wp_ajax_send_attachment_to_editor ()
Ajax handler for sending an attachment to the editor.
Generates the HTML to send an attachment to the editor. Backwards compatible with the media_send_to_editor filter and the chain of filters that follow.
Since
3.5.0
This filter is documented in wp-admin/includes/media.php
Definition at line 2550 of file ajax-actions.php.
References $alt, $caption, $id, $post, $size, $title, $url, apply_filters(), current_user_can(), elseif, esc_attr(), esc_url, get_attachment_link(), get_image_send_to_editor(), get_post(), remove_filter(), stripslashes_deep(), wp_attachment_is(), wp_send_json_error(), wp_send_json_success(), wp_unslash(), and wp_update_post().
wp_ajax_send_link_to_editor ()
Ajax handler for sending a link to the editor.
Generates the HTML to send a non-image embed link to the editor.
Backwards compatible with the following filters:
file_send_to_editor_url
audio_send_to_editor_url
video_send_to_editor_url
Since
3.5.0
WP_Post $post WP_Embed $wp_embed
This filter is documented in wp-admin/includes/media.php
Definition at line 2621 of file ajax-actions.php.
References $link_text, $post, apply_filters(), elseif, esc_url, esc_url_raw(), get_post(), wp_basename(), wp_ext2type(), wp_send_json_error(), wp_send_json_success(), and wp_unslash().
wp_ajax_set_attachment_thumbnail ()
AJAX handler for setting the featured image for an attachment.
Since
4.0.0
See also
set_post_thumbnail()
Definition at line 2145 of file ajax-actions.php.
References $post_id, $thumbnail_id, $url, attachment_url_to_postid(), current_user_can(), set_post_thumbnail(), wp_send_json_error(), and wp_send_json_success().
wp_ajax_set_post_thumbnail ()
Ajax handler for setting the featured image.
Since
3.1.0
Definition at line 2107 of file ajax-actions.php.
References $post_ID, $thumbnail_id, _wp_post_thumbnail_html(), current_user_can(), delete_post_thumbnail(), null, set_post_thumbnail(), wp_die(), and wp_send_json_success().
wp_ajax_time_format ()
Ajax handler for time formatting.
Since
3.1.0
Definition at line 2203 of file ajax-actions.php.
References date_i18n(), sanitize_option(), wp_die(), and wp_unslash().
wp_ajax_trash_post ($action)
Ajax handler for sending a post to the trash.
Since
3.1.0
Parameters
string $action Action to perform.
Definition at line 668 of file ajax-actions.php.
References $action, $id, current_user_can(), get_post(), wp_die(), wp_trash_post(), and wp_untrash_post().
Referenced by wp_ajax_untrash_post().
wp_ajax_untrash_post ($action)
Ajax handler to restore a post from the trash.
Since
3.1.0
Parameters
string $action Action to perform.
Definition at line 698 of file ajax-actions.php.
References $action, and wp_ajax_trash_post().
wp_ajax_update_plugin ()
AJAX handler for updating a plugin.
Since
4.2.0
See also
Plugin_Upgrader
Definition at line 3065 of file ajax-actions.php.
References $plugin, __, ABSPATH, current_user_can(), get_plugin_data(), get_plugins(), is_wp_error(), sanitize_key(), wp_send_json_error(), wp_send_json_success(), and wp_update_plugins().
wp_ajax_update_welcome_panel ()
Ajax handler for updating whether to display the welcome panel.
Since
3.1.0
Definition at line 1411 of file ajax-actions.php.
References current_user_can(), get_current_user_id(), update_user_meta(), and wp_die().
wp_ajax_update_widget ()
Ajax handler for saving a widget.
Since
3.9.0
WP_Customize_Manager $wp_customize
Definition at line 1937 of file ajax-actions.php.
References $wp_customize.
wp_ajax_upload_attachment ()
Ajax handler for uploading attachments.
Since
3.3.0
Definition at line 1982 of file ajax-actions.php.
References $post_id, __, current_user_can(), is_wp_error(), media_handle_upload(), null, update_post_meta(), wp_check_filetype_and_ext(), wp_die(), wp_json_encode(), wp_match_mime_types(), and wp_prepare_attachment_for_js().
wp_ajax_widgets_order ()
Ajax handler for saving the widgets order.
Since
3.1.0
Definition at line 1802 of file ajax-actions.php.
References current_user_can(), wp_die(), and wp_set_sidebars_widgets().
wp_ajax_wp_compression_test ()
Ajax handler for compression testing.
Since
3.1.0
Definition at line 164 of file ajax-actions.php.
References $_SERVER, $force_gzip, $out, current_user_can(), elseif, update_site_option(), and wp_die().
wp_ajax_wp_fullscreen_save_post ()
Ajax handler for saving posts from the fullscreen editor.
Since
3.1.0
Definition at line 2213 of file ajax-actions.php.
References $post, $post_id, __, date_i18n(), edit_post(), esc_html, get_post(), get_post_meta(), is_wp_error(), mysql2date(), null, wp_send_json_error(), and wp_send_json_success().
wp_ajax_wp_link_ajax ()
Ajax handler for internal linking.
Since
3.1.0
Definition at line 1475 of file ajax-actions.php.
References absint(), ABSPATH, wp_die(), wp_json_encode(), _WP_Editors\wp_link_query(), wp_unslash(), and WPINC.
wp_ajax_wp_remove_post_lock ()
Ajax handler for removing a post lock.
Since
3.1.0
Filter the post lock window duration.
Since
3.3.0
Parameters
int $interval The interval in seconds the post lock duration should last, plus 5 seconds. Default 150.
Definition at line 2252 of file ajax-actions.php.
References $post, $post_id, apply_filters(), current_user_can(), get_current_user_id(), get_post(), update_post_meta(), and wp_die().