GravityView: rest-api.php File Reference
api-core/rest-api.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
rest_api_activation ($network_wide)
Registers routes and flush the rewrite rules on activation.
rest_api_deactivation ($network_wide)
Flushes the rewrite rules on deactivation.
rest_api_maybe_flush_rewrites ()
Main API functions.
Variables
if(file_exists(ABSPATH.WPINC. '/class-wp-http-response.php')) else
Compatibility shims for PHP functions.
const REST_API_VERSION '2.0'
Function Documentation
rest_api_activation ($network_wide)
Registers routes and flush the rewrite rules on activation.
Since
4.4.0
Parameters
bool $network_wide ?
Definition at line 68 of file api-core/rest-api.php.
References is_multisite(), null, rest_api_register_rewrites(), restore_current_blog(), switch_to_blog(), update_option(), and wp_get_sites().
Referenced by GV_Unit_Tests_Bootstrap\load_rest_api().
rest_api_deactivation ($network_wide)
Flushes the rewrite rules on deactivation.
Since
4.4.0
Parameters
bool $network_wide ?
Definition at line 94 of file api-core/rest-api.php.
References delete_option(), is_multisite(), restore_current_blog(), switch_to_blog(), and wp_get_sites().
Referenced by GV_Unit_Tests_Bootstrap\load_rest_api().
rest_api_maybe_flush_rewrites ()
Main API functions.
WP_REST_Server class WP_HTTP_Response class WP_REST_Response class WP_REST_Request class REST filters Determines if the rewrite rules should be flushed.
Since
4.4.0
Definition at line 51 of file api-core/rest-api.php.
References flush_rewrite_rules(), get_option(), null, REST_API_VERSION, and update_option().
Referenced by GV_Unit_Tests_Bootstrap\load_rest_api().
Variable Documentation
if (file_exists(ABSPATH.WPINC. '/class-wp-http-response.php')) else
Initial value:
{
    include_once( dirname( __FILE__ ) . '/wp-includes/class-wp-http-response.php' )
Compatibility shims for PHP functions.
Core HTTP Request API
Definition at line 22 of file api-core/rest-api.php.
const REST_API_VERSION '2.0'
Definition at line 14 of file api-core/rest-api.php.
Referenced by _upgrade_440_force_deactivate_incompatible_plugins(), GV_Unit_Tests_Bootstrap\load_rest_api(), and rest_api_maybe_flush_rewrites().