GravityView: rest-api.php File Reference
api-core/wp-includes/rest-api.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
get_rest_url ($blog_id=null, $path= '/', $scheme= 'rest')
Retrieves the URL to a REST endpoint on a site.
rest_api_default_filters ()
Registers the default REST API filters.
rest_api_init ()
Registers rewrite rules for the API.
rest_api_register_rewrites ()
Adds REST rewrite rules.
rest_cookie_check_errors ($result)
Checks for errors when using cookie-based authentication.
rest_cookie_collect_status ()
Collects cookie authentication status.
rest_do_request ($request)
Do a REST request.
rest_ensure_request ($request)
Ensures request arguments are a request object (for consistency).
rest_ensure_response ($response)
Ensures a REST response is a response object (for consistency).
rest_get_date_with_gmt ($date, $force_utc=false)
Retrieves a local date with its GMT equivalent, in MySQL datetime format.
rest_get_url_prefix ()
Retrieves the URL prefix for any API resource.
rest_handle_deprecated_argument ($function, $replacement, $version)
Handles _deprecated_argument() errors.
rest_handle_deprecated_function ($function, $replacement, $version)
Handles _deprecated_function() errors.
rest_handle_options_request ($response, $handler, $request)
Handles OPTIONS requests for the server.
rest_output_link_header ()
Sends a Link header for the REST API.
rest_output_link_wp_head ()
Outputs the REST API link tag into page header.
rest_output_rsd ()
Adds the REST API URL to the WP RSD endpoint.
rest_parse_date ($date, $force_utc=false)
Parses an RFC3339 timestamp into a DateTime.
rest_send_allow_header ($response, $server, $request)
Sends the "Allow" header to state all methods that can be sent to the current route.
rest_send_cors_headers ($value)
Sends Cross-Origin Resource Sharing headers with API requests.
rest_url ($path= '', $scheme= 'json')
Retrieves the URL to a REST endpoint.
Variables
const REST_API_VERSION '2.0'
Function Documentation
get_rest_url ($blog_id = null, $path = '/', $scheme = 'rest')
Retrieves the URL to a REST endpoint on a site.
Note: The returned URL is NOT escaped.
Since
4.4.0
Parameters
int $blog_id Optional. Blog ID. Default of null returns URL for current blog.
string $path Optional. REST route. Default '/'.
string $scheme Optional. Sanitization scheme. Default 'rest'.
Returns
string Full URL to the endpoint.
Filter the REST URL.
Use this filter to adjust the url returned by the get_rest_url function.
Since
4.4.0
Parameters
string $url REST URL.
string $path REST route.
int $blog_id Blog ID.
string $scheme Sanitization scheme.
Definition at line 210 of file api-core/wp-includes/rest-api.php.
References $_SERVER, $blog_id, $path, $url, add_query_arg(), apply_filters(), get_blog_option(), get_home_url(), get_option(), is_multisite(), is_ssl(), rest_get_url_prefix(), set_url_scheme(), and trailingslashit().
Referenced by rest_output_link_header(), rest_output_link_wp_head(), rest_output_rsd(), rest_url(), Tests_REST_API\test_rest_url_generation(), and Tests_REST_API\test_rest_url_scheme().
rest_api_default_filters ()
Registers the default REST API filters.
Attached to the {
See also
'rest_api_init'} action to make testing and disabling these filters easier.
Since
4.4.0
Definition at line 108 of file api-core/wp-includes/rest-api.php.
References add_action(), and add_filter().
rest_api_init ()
Registers rewrite rules for the API.
Since
4.4.0
See also
rest_api_register_rewrites() WP $wp Current WordPress environment instance.
Definition at line 81 of file api-core/wp-includes/rest-api.php.
References $wp, and rest_api_register_rewrites().
Referenced by Tests_REST_API\test_rest_route_query_var().
rest_api_register_rewrites ()
Adds REST rewrite rules.
Since
4.4.0
See also
add_rewrite_rule()
Definition at line 95 of file api-core/wp-includes/rest-api.php.
References add_rewrite_rule(), and rest_get_url_prefix().
Referenced by GV_Unit_Tests_Bootstrap\load_rest_api(), rest_api_activation(), and rest_api_init().
rest_cookie_check_errors ($result)
Checks for errors when using cookie-based authentication.
WordPress' built-in cookie authentication is always active for logged in users. However, the API has to check nonces for each request to ensure users are not vulnerable to CSRF.
Since
4.4.0
mixed $wp_rest_auth_cookie
Parameters
WP_Error | mixed $result Error from another authentication handler, null if we should handle it, or another value if not.
Returns
WP_Error|mixed|bool WP_Error if the cookie is invalid, the $result, otherwise true.
Definition at line 539 of file api-core/wp-includes/rest-api.php.
References $_SERVER, __, elseif, and null.
rest_cookie_collect_status ()
Collects cookie authentication status.
Collects errors from wp_validate_auth_cookie for use by rest_cookie_check_errors.
Since
4.4.0
See also
current_action() mixed $wp_rest_auth_cookie
Definition at line 590 of file api-core/wp-includes/rest-api.php.
References current_action().
rest_do_request ($request)
Do a REST request.
Used primarily to route internal requests through WP_REST_Server.
Since
4.4.0
WP_REST_Server $wp_rest_server ResponseHandler instance (usually WP_REST_Server).
Parameters
WP_REST_Request | string $request Request.
Returns
WP_REST_Response REST response.
Definition at line 275 of file api-core/wp-includes/rest-api.php.
References rest_ensure_request().
rest_ensure_request ($request)
Ensures request arguments are a request object (for consistency).
Since
4.4.0
Parameters
array | WP_REST_Request $request Request to check.
Returns
WP_REST_Request REST request instance.
Definition at line 289 of file api-core/wp-includes/rest-api.php.
Referenced by rest_do_request().
rest_ensure_response ($response)
Ensures a REST response is a response object (for consistency).
This implements WP_HTTP_Response, allowing usage of set_status/header/etc without needing to double-check the object. Will also allow WP_Error to indicate error responses, so users should immediately check for this value.
Since
4.4.0
Parameters
WP_Error | WP_HTTP_Response | mixed $response Response to check.
Returns
mixed WP_Error if response generated an error, WP_HTTP_Response if response is a already an instance, otherwise returns a new WP_REST_Response instance.
Definition at line 310 of file api-core/wp-includes/rest-api.php.
References is_wp_error().
Referenced by WP_REST_Server\dispatch(), WP_REST_Server\envelope_response(), WP_REST_Server\get_namespace_index(), WP_REST_Server\serve_request(), and Tests_REST_Server\test_get_namespace_index().
rest_get_date_with_gmt ($date, $force_utc = false)
Retrieves a local date with its GMT equivalent, in MySQL datetime format.
Since
4.4.0
See also
rest_parse_date()
Parameters
string $date RFC3339 timestamp.
bool $force_utc Whether a UTC timestamp should be forced. Default false.
Returns
array|null Local and UTC datetime strings, in MySQL datetime format (Y-m-d H:i:s), null on failure.
Definition at line 639 of file api-core/wp-includes/rest-api.php.
References date, get_date_from_gmt(), null, and rest_parse_date().
rest_get_url_prefix ()
Retrieves the URL prefix for any API resource.
Since
4.4.0
Returns
string Prefix.
Filter the REST URL prefix.
Since
4.4.0
Parameters
string $prefix URL prefix. Default 'wp-json'.
Definition at line 185 of file api-core/wp-includes/rest-api.php.
References apply_filters().
Referenced by get_rest_url(), and rest_api_register_rewrites().
rest_handle_deprecated_argument ($function, $replacement, $version)
Handles _deprecated_argument() errors.
Since
4.4.0
Parameters
string $function Function name.
string $replacement Replacement function name.
string $version Version.
Definition at line 352 of file api-core/wp-includes/rest-api.php.
References __.
rest_handle_deprecated_function ($function, $replacement, $version)
Handles _deprecated_function() errors.
Since
4.4.0
Parameters
string $function Function name.
string $replacement Replacement function name.
string $version Version.
Definition at line 331 of file api-core/wp-includes/rest-api.php.
References __.
rest_handle_options_request ($response, $handler, $request)
Handles OPTIONS requests for the server.
This is handled outside of the server code, as it doesn't obey normal route mapping.
Since
4.4.0
Parameters
mixed $response Current response, either response or null to indicate pass-through.
WP_REST_Server $handler ResponseHandler instance (usually WP_REST_Server).
WP_REST_Request $request The request that was used to make current response.
Returns
WP_REST_Response Modified response, either response or null to indicate pass-through.
Definition at line 397 of file api-core/wp-includes/rest-api.php.
Referenced by Tests_REST_API\test_options_request(), and Tests_REST_API\test_options_request_not_options().
rest_output_link_header ()
Sends a Link header for the REST API.
Since
4.4.0
Definition at line 510 of file api-core/wp-includes/rest-api.php.
References esc_url_raw(), and get_rest_url().
rest_output_link_wp_head ()
Outputs the REST API link tag into page header.
Since
4.4.0
See also
get_rest_url()
Definition at line 495 of file api-core/wp-includes/rest-api.php.
References esc_url, and get_rest_url().
rest_output_rsd ()
Adds the REST API URL to the WP RSD endpoint.
Since
4.4.0
See also
get_rest_url()
Definition at line 477 of file api-core/wp-includes/rest-api.php.
References get_rest_url(), and name.
rest_parse_date ($date, $force_utc = false)
Parses an RFC3339 timestamp into a DateTime.
Since
4.4.0
Parameters
string $date RFC3339 timestamp.
bool $force_utc Optional. Whether to force UTC timezone instead of using the timestamp's timezone. Default false.
Returns
DateTime DateTime instance.
Definition at line 613 of file api-core/wp-includes/rest-api.php.
Referenced by rest_get_date_with_gmt().
rest_send_allow_header ($response, $server, $request)
Sends the "Allow" header to state all methods that can be sent to the current route.
Since
4.4.0
Parameters
WP_REST_Response $response Current response being served.
WP_REST_Server $server ResponseHandler instance (usually WP_REST_Server).
WP_REST_Request $request The request that was used to make current response.
Returns
WP_REST_Response Response to be served, with "Allow" header if route has allowed methods.
Definition at line 434 of file api-core/wp-includes/rest-api.php.
References $value.
rest_send_cors_headers ($value)
Sends Cross-Origin Resource Sharing headers with API requests.
Since
4.4.0
Parameters
mixed $value Response data.
Returns
mixed Response data.
Definition at line 372 of file api-core/wp-includes/rest-api.php.
References $value, esc_url_raw(), and get_http_origin().
rest_url ($path = '', $scheme = 'json')
Retrieves the URL to a REST endpoint.
Note: The returned URL is NOT escaped.
Since
4.4.0
Parameters
string $path Optional. REST route. Default empty.
string $scheme Optional. Sanitization scheme. Default 'json'.
Returns
string Full URL to the endpoint.
Definition at line 259 of file api-core/wp-includes/rest-api.php.
References $path, get_rest_url(), and null.
Referenced by WP_REST_Server\embed_links(), WP_REST_Server\get_data_for_route(), WP_REST_Server\get_namespace_index(), get_oembed_endpoint_url(), Tests_REST_Server\test_link_embedding(), Tests_REST_Server\test_link_embedding_error(), Tests_REST_Server\test_link_embedding_params(), and Tests_REST_Server\test_link_embedding_self().
Variable Documentation
const REST_API_VERSION '2.0'
Definition at line 15 of file api-core/wp-includes/rest-api.php.