GravityView: async-upload.php File Reference
async-upload.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
if(isset($_REQUEST['post_id'])) $id = media_handle_upload('async-upload', $post_id)
$post_id = 0
else
if (!(isset($_REQUEST['action'])&& 'upload-attachment'==$_REQUEST['action']))
Variable Documentation
if (isset($_REQUEST['post_id'])) $id = media_handle_upload('async-upload', $post_id)
Definition at line 91 of file async-upload.php.
Referenced by GravityView_Default_Template_List\__construct(), GravityView_Preset_Business_Data\__construct(), GravityView_Preset_Business_Listings\__construct(), GravityView_Preset_Event_Listings\__construct(), GravityView_Preset_Issue_Tracker\__construct(), GravityView_Preset_Job_Board\__construct(), GravityView_Preset_Profiles\__construct(), GravityView_Preset_Resume_Board\__construct(), GravityView_Preset_Staff_Profiles\__construct(), GravityView_Preset_Website_Showcase\__construct(), GravityView_Template\__construct(), WP_User\__construct(), _delete_all_posts(), _delete_attachment_theme_mod(), WP_Admin_Bar\_get_node(), _get_non_cached_ids(), _get_widget_id_base(), WP_UnitTestCase\_make_attachment(), _nav_menu_item_id_use_once(), _pad_term_counts(), _register_widget_form_callback(), _show_post_preview(), WP_Admin_Bar\_unset_node(), _wp_json_sanity_check(), _wp_menu_output(), WP_Ajax_Response\add(), WP_Object_Cache\add(), add_blog_option(), WP_Customize_Manager\add_control(), add_meta_box(), WP_Customize_Manager\add_panel(), WP_Customize_Manager\add_section(), WP_Customize_Manager\add_setting(), add_settings_field(), add_settings_section(), GravityView_View_Data\add_view(), getid3_asf\ASFIndexObjectIndexTypeLookup(), getid3_flv\audioBitDepthLookup(), getid3_flv\audioFormatLookup(), getid3_flv\audioRateLookup(), WP_Customize_Nav_Menus\available_items_template(), category_exists(), clean_attachment_cache(), clean_category_cache(), clean_comment_cache(), clean_object_term_cache(), clean_page_cache(), clean_term_cache(), GFExport\cleanup(), comment_id_fields(), comments_popup_link(), comments_template(), GFFormsModel\convert_confirmation(), count_many_users_posts(), count_users(), WP_UnitTest_Factory_For_Attachment\create_upload_object(), PasswordHash\crypt_private(), GravityView_Admin_Duplicate_View\current_user_can_copy(), WP_Customize_Manager\customize_pane_settings(), WP_Customize_Manager\customize_preview_settings(), delete_blog_option(), GFFeedAddOn\delete_feed(), Walker_Comment\display_element(), Walker\display_element(), do_meta_boxes(), GFFeedAddOn\duplicate_feed(), dynamic_sidebar(), edit_post_link(), WP_Users_List_Table\extra_tablenav(), feed_links_extra(), GravityView_API\field_html_attr_id(), GFForms\forms(), gallery_shortcode(), GravityView_Metabox_Tabs\get(), get_attachment_icon(), get_attachment_icon_src(), get_attachment_innerHTML(), get_blog_id_from_url(), get_blog_option(), get_blog_status(), get_category_children(), get_category_parents(), get_category_to_edit(), GF_Field_Checkbox\get_checkbox_choices(), GravityView_Admin_Duplicate_View\get_clone_view_link(), WP_List_Table\get_column_info(), get_comment_id_fields(), get_comment_to_edit(), get_compat_media_markup(), WP_Customize_Manager\get_control(), GravityView_API\get_custom_entry_slug(), GF_Field_Date\get_day_dropdown(), get_delete_post_link(), get_edit_post_link(), GFFeedAddOn\get_feed(), GFFormDisplay\get_field(), GFFormsModel\get_field_filters_where(), GF_Field_SingleShipping\get_field_input(), GF_Field_Total\get_field_input(), GF_Field_Hidden\get_field_input(), GF_Field_Post_Image\get_field_input(), GF_Field_HiddenProduct\get_field_input(), GF_Field_Checkbox\get_field_input(), GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Post_Tags\get_field_input(), GF_Field_Calculation\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_Select\get_field_input(), GF_Field_SingleProduct\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Post_Title\get_field_input(), GF_Field_Name\get_field_input(), GF_Field_Donation\get_field_input(), GF_Field_Radio\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Password\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_MultiSelect\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GF_Field_Number\get_field_input(), GF_Field_FileUpload\get_first_input_id(), GF_Field\get_first_input_id(), get_image_send_to_editor(), get_image_tag(), GFFormsModel\get_input(), WP_Comment\get_instance(), get_linkcatname(), get_media_item(), get_media_items(), GF_Field_Date\get_month_dropdown(), WP_Admin_Bar\get_node(), get_notification(), GFFormLocking\get_object_id(), GFEntryLocking\get_object_id(), GFLocking\get_object_id(), get_object_term_cache(), get_page_template(), get_pages(), WP_Customize_Manager\get_panel(), get_pending_comments_num(), get_post_ancestors(), get_post_permalink(), get_post_to_edit(), get_posts_by_author_sql(), GF_Field_Radio\get_radio_choices(), get_sample_permalink(), get_sample_permalink_html(), GravityView_Widget_Search\get_search_input_types(), WP_Customize_Manager\get_section(), WP_Customize_Manager\get_setting(), WP_Customize_Widgets\get_setting_args(), GVCommon\get_sortable_fields(), GVCommon\get_sortable_fields_array(), GF_Field_Address\get_state_field(), get_submit_button(), get_term_to_edit(), get_the_attachment_link(), get_the_category(), get_the_guid(), get_the_tag_list(), get_the_tags(), get_the_term_list(), get_the_title(), get_user_metavalues(), get_users_of_blog(), GF_Field_Select\get_value_export(), GF_Field_MultiSelect\get_value_export(), GF_Field_Radio\get_value_export(), GF_Field_Name\get_value_export(), GF_Field\get_value_export(), GF_Field_List\get_value_export(), GF_Field_FileUpload\get_value_export(), GF_Field_Address\get_value_export(), GF_Field_Date\get_year_dropdown(), GravityView_Admin_Views\gform_toolbar_menu(), gravity_form(), gravityview_get_permalink_query_args(), has_excerpt(), image_add_caption(), image_downsize(), GFFormsModel\insert_form_view(), is_archived(), is_local_attachment(), GF_Field_FileUpload\is_value_submission_empty(), load_template(), GravityView_View_Data\maybe_get_view_id(), media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), media_sideload_image(), media_upload_type_form(), getid3_asf\metadataLibraryObjectDataTypeLookup(), GravityView_Edit_Entry_Render\modify_edit_field_input(), wp_xmlrpc_server\mw_newMediaObject(), WP_Rewrite\page_uri_index(), GFForms\parse_shortcode(), postbox_classes(), WP_Customize_Manager\prepare_controls(), WP_List_Table\print_column_headers(), redirect_canonical(), refresh_user_details(), WP_Embed\register_handler(), register_importer(), register_sidebar_widget(), register_widget_control(), rel_canonical(), WP_Customize_Manager\remove_control(), WP_Admin_Bar\remove_menu(), remove_meta_box(), WP_Admin_Bar\remove_node(), WP_Customize_Manager\remove_panel(), WP_Customize_Manager\remove_section(), WP_Customize_Manager\remove_setting(), GravityView_Admin_Views\render_available_fields(), GravityView_Admin_Views\render_available_widgets(), GravityView_Render_Settings\render_checkbox_option(), GravityView_Widget_Search\render_searchable_fields(), GravityView_Render_Settings\render_select_option(), GravityView_Admin_Views\render_setting_row(), GravityView_Render_Settings\render_text_option(), GravityView_Render_Settings\render_textarea_option(), WP_Object_Cache\replace(), retrieve_widgets(), GravityView_Admin_Duplicate_View\save_as_new_view(), WP_Query\setup_postdata(), WP_Embed\shortcode(), signup_nonce_fields(), WP_MS_Themes_List_Table\single_row(), Walker_Nav_Menu\start_el(), the_attachment_link(), the_editor(), the_guid(), the_terms(), GFForms\top_toolbar(), WP_Embed\unregister_handler(), unregister_sidebar_widget(), unregister_widget_control(), Walker\unset_children(), update_archived(), update_blog_option(), GFFeedAddOn\update_feed_active(), GFFeedAddOn\update_feed_meta(), GFForms\update_lead_status(), update_meta_cache(), update_object_term_cache(), update_post_thumbnail_cache(), update_user_status(), upgrade_160(), upgrade_230(), upgrade_330(), upload_space_setting(), url_to_postid(), GF_Field_FileUpload\validate(), GF_Field_Number\validate(), getid3_flv\videoCodecLookup(), wp_admin_bar_new_content_menu(), wp_admin_bar_shortlink_menu(), wp_ajax_autocomplete_user(), wp_ajax_delete_comment(), wp_ajax_delete_link(), wp_ajax_delete_meta(), wp_ajax_delete_page(), wp_ajax_delete_post(), wp_ajax_dim_comment(), wp_ajax_get_attachment(), wp_ajax_get_comments(), wp_ajax_inline_save_tax(), wp_ajax_save_attachment(), wp_ajax_save_attachment_compat(), wp_ajax_send_attachment_to_editor(), wp_ajax_trash_post(), wp_create_categories(), wp_create_category(), wp_create_term(), wp_delete_user(), wp_dropdown_categories(), wp_dropdown_users(), wp_embed_register_handler(), wp_embed_unregister_handler(), wp_get_attachment_link(), wp_get_shortlink(), wp_import_cleanup(), wp_import_handle_upload(), wp_insert_comment(), wp_list_widget_controls_dynamic_sidebar(), wp_media_upload_handler(), wp_nav_menu(), wp_nav_menu_post_type_meta_boxes(), wp_nav_menu_taxonomy_meta_boxes(), wp_old_slug_redirect(), wp_playlist_shortcode(), wp_popular_terms_checklist(), wp_prepare_attachment_for_js(), wp_register_sidebar_widget(), wp_register_widget_control(), wp_revoke_user(), wp_sidebar_description(), wp_unregister_sidebar_widget(), wp_unregister_widget_control(), wp_widget_description(), wp_widget_rss_form(), and wpmu_delete_user().
$post_id = 0
Definition at line 84 of file async-upload.php.
Referenced by WP_Comments_List_Table\__construct(), _close_comments_for_old_post(), _publish_post_hook(), _reset_front_page_settings_for_post(), _update_blog_date_on_post_delete(), _update_posts_count_on_delete(), _wp_ajax_delete_comment_response(), _wp_check_split_terms_in_menus(), _wp_preview_terms_filter(), _wp_translate_postdata(), GravityView_Admin_Views\add_custom_column_content(), GFAPI\add_entry(), GravityView_Widget_Search\add_no_permalink_fields(), add_ping(), add_post_meta(), WP_UnitTest_Factory_For_Term\add_post_terms(), attachment_url_to_postid(), check_and_publish_future_post(), comment_class(), comment_form(), WP_List_Table\comments_bubble(), comments_open(), GFFormsModel\copy_post_image(), GFFormsModel\create_post(), WP_UnitTest_Factory_For_Comment\create_post_comments(), WP_Site_Icon\delete_attachment_data(), delete_post_meta(), GravityView_API\directory_link(), do_trackbacks(), GravityView_API\entry_link(), GravityView_Search_WP_Widget\form(), WP_Canonical_UnitTestCase\generate_shared_fixtures(), generic_ping(), WP_Screen\get(), get_approved_comments(), get_blog_permalink(), get_blog_post(), get_body_class(), WP_Comments_List_Table\get_columns(), get_comment_class(), get_comment_count(), WP_Comment_Query\get_comment_ids(), get_comments_link(), get_comments_number(), wp_xmlrpc_server\get_custom_fields(), get_default_post_to_edit(), GravityView_Delete_Entry\get_delete_link(), GVCommon\get_directory_fields(), GravityView_Edit_Entry\get_edit_link(), get_enclosed(), WP_Post\get_instance(), WP_oEmbed_Controller\get_item(), get_media_items(), WP_UnitTest_Factory_For_Post\get_object_by_id(), get_page_template_slug(), get_pending_comments_num(), get_post_class(), get_post_comments_feed_link(), get_post_custom(), get_post_custom_keys(), get_post_custom_values(), get_post_meta(), WP_Site_Icon\get_post_metadata(), GravityView_oEmbed\get_postid_from_url_and_slug(), get_pung(), GravityView_Widget_Search\get_search_form_action(), get_tags_to_edit(), GVCommon\get_template_setting(), GVCommon\get_template_settings(), get_terms_to_edit(), get_the_category_list(), get_to_ping(), get_upload_iframe_src(), GravityView_Entry_Link_Shortcode\get_url(), WP_Comments_List_Table\get_views(), gravityview_get_directory_fields(), gravityview_get_template_id(), gravityview_get_template_setting(), gravityview_get_template_settings(), gravityview_get_the_term_list(), gv_entry_link(), GFForms\handle_ajax_do_shortcode(), image_get_intermediate_size(), is_sticky(), GravityView_View_Data\is_valid_embed_id(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), media_sideload_image(), media_upload_form(), media_upload_header(), media_upload_type_form(), media_upload_type_url_form(), wp_xmlrpc_server\mw_newMediaObject(), GravityView_View_Data\parse_post_meta(), pings_open(), post_class(), post_comments_feed_link(), post_permalink(), WP_Comments_List_Table\prepare_items(), redirect_guess_404_permalink(), GravityView_Admin_Views\render_directory_active_areas(), GravityView_Admin_Views\render_widgets_active_areas(), sanitize_post_field(), WP_Press_This\save_post(), GravityView_Admin_Views\save_postdata(), wp_xmlrpc_server\set_custom_fields(), set_post_type(), GravityView_oEmbed\set_vars(), WP_Press_This\side_load_images(), stick_post(), sticky_class(), stream_preview_image(), GravityView_API_Test\test_directory_link(), GravityView_Edit_Entry_Test\test_get_edit_link(), GravityView_Entry_Link_Shortcode_Test\test_shortcode(), the_category(), trackback_url_list(), unstick_post(), WP_Customize_Nav_Menu_Item_Setting\update(), GFAPI\update_entry(), update_gallery_tab(), WP_UnitTest_Factory_For_Post\update_object(), update_post_meta(), upgrade_230(), user_can_delete_post(), user_can_delete_post_comments(), user_can_edit_post(), user_can_edit_post_comments(), user_can_edit_post_date(), WP_Customize_Nav_Menu_Item_Setting\value_as_wp_post_nav_menu_item(), wp_add_post_tags(), wp_ajax_get_comments(), wp_ajax_get_permalink(), wp_ajax_imgedit_preview(), wp_ajax_sample_permalink(), wp_ajax_save_attachment_order(), wp_ajax_set_attachment_thumbnail(), wp_ajax_upload_attachment(), wp_ajax_wp_fullscreen_save_post(), wp_ajax_wp_remove_post_lock(), wp_attachment_is(), wp_audio_shortcode(), wp_category_checklist(), wp_check_for_changed_slugs(), wp_check_locked_posts(), wp_comment_form_unfiltered_html_nonce(), wp_count_comments(), wp_create_categories(), wp_delete_attachment(), wp_delete_comment(), wp_delete_user(), wp_xmlrpc_server\wp_deletePost(), wp_xmlrpc_server\wp_editPost(), wp_get_attachment_metadata(), wp_get_attachment_thumb_file(), wp_get_attachment_thumb_url(), wp_get_attachment_url(), wp_get_post_autosave(), wp_get_post_categories(), wp_get_post_revisions(), wp_get_post_tags(), wp_get_post_terms(), wp_get_shortlink(), wp_xmlrpc_server\wp_getCommentCount(), wp_xmlrpc_server\wp_getComments(), wp_xmlrpc_server\wp_getPost(), wp_xmlrpc_server\wp_getRevisions(), wp_image_editor(), wp_list_post_revisions(), wp_mime_type_icon(), wp_xmlrpc_server\wp_newComment(), wp_refresh_post_lock(), wp_refresh_post_nonces(), wp_restore_image(), wp_restore_post_revision(), wp_save_image(), wp_save_image_file(), wp_save_post_revision(), wp_scheduled_delete(), wp_set_post_tags(), wp_set_post_terms(), wp_stream_image(), wp_terms_checklist(), wp_trash_post(), wp_trash_post_comments(), wp_untrash_post(), wp_untrash_post_comments(), wp_update_attachment_metadata(), wp_update_comment_count(), wp_update_comment_count_now(), wp_video_shortcode(), and wpmu_delete_user().
if (is_wp_error($id)) if ($_REQUEST['short']) else
Initial value:
{
    $type = $_REQUEST['type']
Definition at line 20 of file async-upload.php.
if(!(isset($_REQUEST['action'])&& 'upload-attachment'==$_REQUEST['action']))
Definition at line 22 of file async-upload.php.