GravityView: author-template.php File Reference
author-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
__clear_multi_author_cache ()
Helper function to clear the cache for number of authors.
get_author_posts_url ($author_id, $author_nicename= '')
Retrieve the URL to the author page for the user with the ID provided.
get_the_author ($deprecated= '')
Retrieve the author of the current post.
get_the_author_link ()
Retrieve either author's link or author's name.
get_the_author_meta ($field= '', $user_id=false)
Retrieve the requested data of the author of the current post.
get_the_author_posts ()
Retrieve the number of posts by the author of the current post.
get_the_author_posts_link ()
Retrieves an HTML link to the author page of the current post's author.
get_the_modified_author ()
Retrieve the author who last edited the current post.
is_multi_author ()
Does this site have more than one author.
the_author ($deprecated= '', $deprecated_echo=true)
Display the name of the author of the current post.
the_author_link ()
Display either author's link or author's name.
the_author_meta ($field= '', $user_id=false)
Outputs the field from the user's DB object.
the_author_posts ()
Display the number of posts by the author of the current post.
the_author_posts_link ($deprecated= '')
Displays an HTML link to the author page of the current post's author.
the_modified_author ()
Display the name of the author who last edited the current post, if the author's ID is available.
wp_list_authors ($args= '')
List all the authors of the blog, with several options available.
Function Documentation
__clear_multi_author_cache () private
Helper function to clear the cache for number of authors.
Definition at line 497 of file author-template.php.
References delete_transient().
get_author_posts_url ($author_id, $author_nicename = '')
Retrieve the URL to the author page for the user with the ID provided.
Since
2.1.0
WP_Rewrite $wp_rewrite
Parameters
int $author_id Author ID.
string $author_nicename Optional. The author's nicename (slug). Default empty.
Returns
string The URL to the author's page.
Filter the URL to the author's page.
Since
2.1.0
Parameters
string $link The URL to the author's page.
int $author_id The author's id.
string $author_nicename The author's nice name.
Definition at line 296 of file author-template.php.
References $file, $link, $user, $wp_rewrite, apply_filters(), home_url(), str_replace, and user_trailingslashit().
Referenced by get_author_feed_link(), get_author_link(), get_oembed_response_data(), get_the_author_posts_link(), redirect_canonical(), Twenty_Fourteen_Ephemera_Widget\widget(), and wp_list_authors().
get_the_author ($deprecated = '')
Retrieve the author of the current post.
Since
1.5.0
object $authordata The current author's DB object.
Parameters
string $deprecated Deprecated.
Returns
string|null The author's display name.
Filter the display name of the current post's author.
Since
2.9.0
Parameters
string $authordata-,>display_name The author's display name.
Definition at line 23 of file author-template.php.
References $deprecated, _deprecated_argument(), apply_filters(), and null.
Referenced by WP_Media_List_Table\column_author(), WP_Posts_List_Table\column_author(), get_the_archive_title(), get_the_author_link(), get_the_author_posts_link(), the_author(), and Twenty_Fourteen_Ephemera_Widget\widget().
get_the_author_link ()
Retrieve either author's link or author's name.
If the author has a home page set, return an HTML link, otherwise just return the author's name.
Returns
string|null An HTML link if the author's url exist in user meta, else the result of get_the_author().
Definition at line 189 of file author-template.php.
References __, esc_attr(), esc_url, get_the_author(), and get_the_author_meta().
Referenced by the_author_link().
get_the_author_meta ($field = '', $user_id = false)
Retrieve the requested data of the author of the current post.
2.8.0 object $authordata The current author's DB object. string $field selects the field of the users record. int $user_id Optional. User ID. string The author's field from the current author's DB object.
Filter the value of the requested user metadata.
The filter name is dynamic and depends on the $field parameter of the function.
Since
2.8.0
4.3.0 The $original_user_id parameter was added.
Parameters
string $value The value of the metadata.
int $user_id The user ID for the value.
int | bool $original_user_id The original user ID, as passed to the function.
Definition at line 124 of file author-template.php.
References $field, $user_id, $value, and apply_filters().
Referenced by WP_Media_List_Table\column_author(), WP_Posts_List_Table\column_author(), feed_links_extra(), get_author_name(), get_profile(), get_the_author_aim(), get_the_author_description(), get_the_author_email(), get_the_author_firstname(), get_the_author_icq(), get_the_author_ID(), get_the_author_lastname(), get_the_author_link(), get_the_author_login(), get_the_author_msn(), get_the_author_nickname(), get_the_author_url(), get_the_author_yim(), the_author_meta(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_post_revision_title_expanded(), and wp_prepare_revisions_for_js().
get_the_author_posts ()
Retrieve the number of posts by the author of the current post.
Since
1.5.0
Returns
int The number of posts by the author.
Definition at line 218 of file author-template.php.
References $post, count_user_posts(), and get_post().
Referenced by the_author_posts().
get_the_author_posts_link ()
Retrieves an HTML link to the author page of the current post's author.
Returns an HTML-formatted link using get_author_posts_url().
Since
4.4.0
object $authordata The current author's DB object.
Returns
string An HTML link to the author page.
Filter the link to the author page of the author of the current post.
Since
2.9.0
Parameters
string $link HTML link.
Definition at line 247 of file author-template.php.
References $link, __, apply_filters(), esc_attr(), esc_url, get_author_posts_url(), and get_the_author().
Referenced by the_author_posts_link().
get_the_modified_author ()
Retrieve the author who last edited the current post.
Since
2.8.0
Returns
string|void The author's display name.
Filter the display name of the author who last edited the current post.
Since
2.8.0
Parameters
string $last_user-,>display_name The author's display name.
Definition at line 86 of file author-template.php.
References apply_filters(), get_post(), and get_post_meta().
Referenced by the_modified_author().
is_multi_author ()
Does this site have more than one author.
Checks to see if more than one author has published posts.
Since
3.2.0
wpdb $wpdb WordPress database abstraction object.
Returns
bool Whether or not we have more than one author
Filter whether the site has more than one author with published posts.
Since
3.2.0
Parameters
bool $is_multi_author Whether $is_multi_author should evaluate as true.
Definition at line 473 of file author-template.php.
References $wpdb, apply_filters(), get_transient(), and set_transient().
Referenced by twentyeleven_body_classes(), twentyfourteen_body_classes(), twentythirteen_body_class(), and twentytwelve_body_class().
the_author ($deprecated = '', $deprecated_echo = true)
Display the name of the author of the current post.
The behavior of this function is based off of old functionality predating get_the_author(). This function is not deprecated, but is designed to echo the value from get_the_author() and as an result of any old theme that might still use the old behavior will also pass the value from get_the_author().
The normal, expected behavior of this function is to echo the author and not return it. However, backwards compatibility has to be maintained.
Since
0.71
See also
get_the_author() string $deprecated Deprecated. string $deprecated_echo Deprecated. Use get_the_author(). Echo the string or return it. string|null The author's display name, from get_the_author().
Definition at line 58 of file author-template.php.
References $deprecated, __, _deprecated_argument(), and get_the_author().
the_author_link ()
Display either author's link or author's name.
If the author has a home page set, echo an HTML link, otherwise just echo the author's name.
2.1.0
Definition at line 207 of file author-template.php.
References get_the_author_link().
the_author_meta ($field = '', $user_id = false)
Outputs the field from the user's DB object.
Defaults to current post's author.
2.8.0 string $field selects the field of the users record. int $user_id Optional. User ID.
The value of the requested user metadata.
The filter name is dynamic and depends on the $field parameter of the function.
Since
2.8.0
Parameters
string $author_meta The value of the metadata.
int $user_id The user ID.
Definition at line 164 of file author-template.php.
References $field, $user_id, apply_filters(), and get_the_author_meta().
Referenced by the_author_aim(), the_author_description(), the_author_email(), the_author_firstname(), the_author_icq(), the_author_ID(), the_author_lastname(), the_author_login(), the_author_msn(), the_author_nickname(), the_author_url(), and the_author_yim().
the_author_posts ()
Display the number of posts by the author of the current post.
0.71
Definition at line 232 of file author-template.php.
References get_the_author_posts().
the_author_posts_link ($deprecated = '')
Displays an HTML link to the author page of the current post's author.
Since
1.2.0
4.4.0 Converted into a wrapper for get_the_author_posts_link()
Parameters
string $deprecated Unused.
Definition at line 278 of file author-template.php.
References $deprecated, _deprecated_argument(), and get_the_author_posts_link().
the_modified_author ()
Display the name of the author who last edited the current post, if the author's ID is available.
Since
2.8.0
See also
get_the_author()
Definition at line 109 of file author-template.php.
References get_the_modified_author().
wp_list_authors ($args = '')
List all the authors of the blog, with several options available.
1.2.0 wpdb $wpdb WordPress database abstraction object. string|array $args { Optional. Array or string of default arguments. string $orderby How to sort the authors. Accepts 'nicename', 'email', 'url', 'registered', 'user_nicename', 'user_email', 'user_url', 'user_registered', 'name', 'display_name', 'post_count', 'ID', 'meta_value', 'user_login'. Default 'name'. string $order Sorting direction for $orderby. Accepts 'ASC', 'DESC'. Default 'ASC'. int $number Maximum authors to return or display. Default empty (all authors). bool $optioncount Show the count in parenthesis next to the author's name. Default false. bool $exclude_admin Whether to exclude the 'admin' account, if it exists. Default false. bool $show_fullname Whether to show the author's full name. Default false. bool $hide_empty Whether to hide any authors with no posts. Default true. string $feed If not empty, show a link to the author's feed and use this text as the alt parameter of the link. Default empty. string $feed_image If not empty, show a link to the author's feed and use this image URL as clickable anchor. Default empty. string $feed_type The feed type to link to, such as 'rss2'. Defaults to default feed type. bool $echo Whether to output the result or instead return it. Default true. string $style If 'list', each author is wrapped in an <li> element, otherwise the authors will be separated by commas. bool $html Whether to list the items in HTML form or plaintext. Default true. string $exclude An array, comma-, or space-separated list of author IDs to exclude. Default empty. string $exclude An array, comma-, or space-separated list of author IDs to include. Default empty. } string|void The output, if echo is set to false.
Definition at line 363 of file author-template.php.
References $alt, $authors, $link, $name, $wpdb, __, esc_attr(), esc_url, get_author_feed_link(), get_author_posts_url(), get_private_posts_cap_sql(), get_users(), wp_array_slice_assoc(), and wp_parse_args().
Referenced by list_authors().