GravityView: bookmark-template.php File Reference
bookmark-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_walk_bookmarks ($bookmarks, $args= '')
The formatted output of a list of bookmarks.
wp_list_bookmarks ($args= '')
Retrieve or echo all of the bookmarks.
Function Documentation
_walk_bookmarks ($bookmarks, $args = '')
The formatted output of a list of bookmarks.
The $bookmarks array must contain bookmark objects and will be iterated over to retrieve the bookmark to be used in the output.
The output is formatted as HTML with no way to change that format. However, what is between, before, and after can be changed. The link itself will be HTML.
This function is used internally by wp_list_bookmarks() and should not be used by themes.
Since
2.1.0 private
Parameters
array $bookmarks List of bookmarks to traverse.
string | array $args { Optional. Bookmarks arguments.
int|bool $show_updated Whether to show the time the bookmark was last updated. Accepts 1|true or 0|false. Default 0|false. int|bool $show_description Whether to show the bookmakr description. Accepts 1|true, Accepts 1|true or 0|false. Default 0|false. int|bool $show_images Whether to show the link image if available. Accepts 1|true or 0|false. Default 1|true. int|bool $show_name Whether to show link name if available. Accepts 1|true or 0|false. Default 0|false. string $before The HTML or text to prepend to each bookmark. Default <li>. string $after The HTML or text to append to each bookmark. Default </li>. string $link_before The HTML or text to prepend to each bookmark inside the anchor tags. Default empty. string $link_after The HTML or text to append to each bookmark inside the anchor tags. Default empty. string $between The string for use in between the link, description, and image. Default "\n". int|bool $show_rating Whether to show the link rating. Accepts 1|true or 0|false. Default 0|false.
}
Returns
string Formatted output in HTML
Definition at line 51 of file bookmark-template.php.
References $alt, $bookmarks, $name, $output, $title, __, date, esc_attr(), esc_url, get_option(), null, sanitize_bookmark_field(), and wp_parse_args().
Referenced by wp_list_bookmarks().
wp_list_bookmarks ($args = '')
Retrieve or echo all of the bookmarks.
List of default arguments are as follows:
These options define how the Category name will appear before the category links are displayed, if 'categorize' is 1. If 'categorize' is 0, then it will display for only the 'title_li' string and only if 'title_li' is not empty.
Since
2.1.0
See also
_walk_bookmarks()
Parameters
string | array $args { Optional. String or array of arguments to list bookmarks.
string $orderby How to order the links by. Accepts post fields. Default 'name'. string $order Whether to order bookmarks in ascending or descending order. Accepts 'ASC' (ascending) or 'DESC' (descending). Default 'ASC'. int $limit Amount of bookmarks to display. Accepts 1+ or -1 for all. Default -1. string $category Comma-separated list of category ids to include links from. Default empty. string $category_name Category to retrieve links for by name. Default empty. int|bool $hide_invisible Whether to show or hide links marked as 'invisible'. Accepts 1|true or 0|false. Default 1|true. int|bool $show_updated Whether to display the time the bookmark was last updated. Accepts 1|true or 0|false. Default 0|false. int|bool $echo Whether to echo or return the formatted bookmarks. Accepts 1|true (echo) or 0|false (return). Default 1|true. int|bool $categorize Whether to show links listed by category or in a single column. Accepts 1|true (by category) or 0|false (one column). Default 1|true. int|bool $show_description Whether to show the bookmark descriptions. Accepts 1|true or 0|false. Default 0|false. string $title_li What to show before the links appear. Default 'Bookmarks'. string $title_before The HTML or text to prepend to the $title_li string. Default '
'. string $title_after The HTML or text to append to the $title_li string. Default '
'. string $class The CSS class to use for the $title_li. Default 'linkcat'. string $category_before The HTML or text to prepend to $title_before if $categorize is true. String must contain 'id' and 'class' to inherit the category ID and the $class argument used for formatting in themes. Default ''. string $category_after The HTML or text to append to $title_after if $categorize is true. Default ''. string $category_orderby How to order the bookmark category based on term scheme if $categorize is true. Default 'name'. string $category_order Whether to order categories in ascending or descending order if $categorize is true. Accepts 'ASC' (ascending) or 'DESC' (descending). Default 'ASC'. }
Returns
string|void Will only return if echo option is set to not echo. Default is not return anything.
Filter the bookmarks category name.
Since
2.2.0
Parameters
string $cat_name The category name of bookmarks.
Filter the bookmarks list before it is echoed or returned.
Since
2.5.0
Parameters
string $html The HTML list of bookmarks.
Definition at line 200 of file bookmark-template.php.
References $bookmarks, $cats, $output, __, _walk_bookmarks(), apply_filters(), get_bookmarks(), get_terms(), str_replace, and wp_parse_args().
Referenced by WP_Widget_Links\widget(), wp_get_links(), and wp_get_linksbyname().