GravityView: cache.php File Reference
cache.php File Reference
Data Structures
class WP_Object_Cache
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
wp_cache_add ($key, $data, $group= '', $expire=0)
Adds data to the cache, if the cache key doesn't already exist.
wp_cache_add_global_groups ($groups)
Adds a group or set of groups to the list of global groups.
wp_cache_add_non_persistent_groups ($groups)
Adds a group or set of groups to the list of non-persistent groups.
wp_cache_close ()
Closes the cache.
wp_cache_decr ($key, $offset=1, $group= '')
Decrements numeric cache item's value.
wp_cache_delete ($key, $group= '')
Removes the cache contents matching key and group.
wp_cache_flush ()
Removes all cache items.
wp_cache_get ($key, $group= '', $force=false, &$found=null)
Retrieves the cache contents from the cache by key and group.
wp_cache_incr ($key, $offset=1, $group= '')
Increment numeric cache item's value.
wp_cache_init ()
Sets up Object Cache Global and assigns it.
wp_cache_replace ($key, $data, $group= '', $expire=0)
Replaces the contents of the cache with new data.
wp_cache_reset ()
Reset internal cache keys and structures.
wp_cache_set ($key, $data, $group= '', $expire=0)
Saves the data to the cache.
wp_cache_switch_to_blog ($blog_id)
Switches the interal blog ID.
Function Documentation
wp_cache_add ($key, $data, $group = '', $expire = 0)
Adds data to the cache, if the cache key doesn't already exist.
Since
2.0.0
See also
WP_Object_Cache::add() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
int | string $key The cache key to use for retrieval later.
mixed $data The data to add to the cache.
string $group Optional. The group to add the cache to. Enables the same key to be used across groups. Default empty.
int $expire Optional. When the cache data should expire, in seconds. Default 0 (no expiration).
Returns
bool False if cache key and group already exist, true on success.
Definition at line 27 of file cache.php.
Referenced by WP_Theme\cache_add(), get_all_category_ids(), get_all_page_ids(), get_bookmark(), WP_Network\get_by_path(), WP_Comment_Query\get_comments(), GravityView_Entry_Link_Shortcode\get_entry(), get_inline_data(), WP_Network\get_instance(), WP_Term\get_instance(), WP_Comment\get_instance(), WP_Post\get_instance(), get_main_network_id(), get_option(), get_term_by(), get_terms(), get_terms_to_edit(), get_the_terms(), update_comment_cache(), update_meta_cache(), update_object_term_cache(), update_post_cache(), update_term_cache(), update_user_caches(), wp_load_alloptions(), and wp_mime_type_icon().
wp_cache_add_global_groups ($groups)
Adds a group or set of groups to the list of global groups.
Since
2.6.0
See also
WP_Object_Cache::add_global_groups() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
string | array $groups A group or an array of groups to add.
Definition at line 230 of file cache.php.
Referenced by WP_Theme\__construct(), WP_UnitTestCase\flush_cache(), restore_current_blog(), switch_to_blog(), and wp_start_object_cache().
wp_cache_add_non_persistent_groups ($groups)
Adds a group or set of groups to the list of non-persistent groups.
Since
2.6.0
Parameters
string | array $groups A group or an array of groups to add.
Definition at line 243 of file cache.php.
Referenced by WP_Theme\__construct(), WP_UnitTestCase\flush_cache(), restore_current_blog(), switch_to_blog(), and wp_start_object_cache().
wp_cache_close ()
Closes the cache.
This function has ceased to do anything since WordPress 2.5. The functionality was removed along with the rest of the persistent cache.
This does not mean that plugins can't implement this function when they need to make sure that the cache is cleaned up after WordPress no longer needs it.
Since
2.0.0
Returns
true Always returns true.
Definition at line 46 of file cache.php.
Referenced by shutdown_action_hook().
wp_cache_decr ($key, $offset = 1, $group = '')
Decrements numeric cache item's value.
Since
3.3.0
See also
WP_Object_Cache::decr() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
int | string $key The cache key to decrement.
int $offset Optional. The amount by which to decrement the item's value. Default 1.
string $group Optional. The group the key is in. Default empty.
Returns
false|int False on failure, the item's new value on success.
Definition at line 63 of file cache.php.
wp_cache_delete ($key, $group = '')
Removes the cache contents matching key and group.
Since
2.0.0
See also
WP_Object_Cache::delete() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
int | string $key What the contents in the cache are called.
string $group Optional. Where the cache contents are grouped. Default empty.
Returns
bool True on successful removal, false on failure.
Definition at line 81 of file cache.php.
Referenced by _transition_post_status(), _wp_upgrade_revisions_of_post(), add_metadata(), add_user_to_blog(), WP_Theme\cache_delete(), clean_attachment_cache(), clean_blog_cache(), clean_bookmark_cache(), clean_comment_cache(), clean_object_term_cache(), clean_post_cache(), clean_term_cache(), clean_user_cache(), delete_get_calendar_cache(), delete_metadata(), delete_metadata_by_mid(), delete_network_option(), delete_option(), delete_site_transient(), delete_transient(), delete_usermeta(), Twenty_Eleven_Ephemera_Widget\flush_widget_cache(), get_blog_details(), populate_network(), update_core(), update_metadata(), update_metadata_by_mid(), update_usermeta(), wp_clean_plugins_cache(), wp_insert_user(), wp_remove_object_terms(), wp_set_object_terms(), wp_update_comment_count_now(), and wp_update_user().
wp_cache_flush ()
Removes all cache items.
Since
2.0.0
See also
WP_Object_Cache::flush() WP_Object_Cache $wp_object_cache Object cache global instance.
Returns
bool False on failure, true on success
Definition at line 97 of file cache.php.
Referenced by WP_UnitTestCase\flush_cache(), and update_core().
wp_cache_get ($key, $group = '', $force = false, & $found = null)
Retrieves the cache contents from the cache by key and group.
Since
2.0.0
See also
WP_Object_Cache::get() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
int | string $key The key under which the cache contents are stored.
string $group Optional. Where the cache contents are grouped. Default empty.
bool $force Optional. Whether to force an update of the local cache from the persistent cache. Default false.
bool $found Optional. Whether the key was found in the cache. Disambiguates a return of false, a storable value. Passed by reference. Default null.
Returns
bool|mixed False on failure to retrieve contents or the cache contents on success
Definition at line 120 of file cache.php.
Referenced by _get_cron_lock(), _get_last_post_time(), _get_non_cached_ids(), add_network_option(), add_option(), WP_Theme\cache_get(), WP_MS_Sites_List_Table\column_users(), GravityView_API\directory_link(), get_adjacent_post(), get_all_category_ids(), get_all_page_ids(), get_blog_details(), get_blog_id_from_url(), get_bookmark(), get_bookmarks(), WP_Network\get_by_path(), get_calendar(), WP_Comment_Query\get_comments(), WP_User\get_data_by(), GravityView_Entry_Link_Shortcode\get_entry(), get_id_from_blogname(), WP_Network\get_instance(), WP_Term\get_instance(), WP_Comment\get_instance(), WP_Post\get_instance(), get_main_network_id(), get_metadata(), get_network_option(), get_object_term_cache(), get_option(), get_pages(), get_plugins(), get_site_transient(), get_terms(), get_transient(), get_usermeta(), is_blog_installed(), metadata_exists(), GravityView_API_Test\test_directory_link(), Twenty_Eleven_Ephemera_Widget\update(), update_meta_cache(), update_network_option(), update_object_term_cache(), update_option(), Twenty_Eleven_Ephemera_Widget\widget(), wp_count_comments(), wp_count_posts(), wp_get_archives(), wp_load_alloptions(), and wp_mime_type_icon().
wp_cache_incr ($key, $offset = 1, $group = '')
Increment numeric cache item's value.
Since
3.3.0
See also
WP_Object_Cache::incr() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
int | string $key The key for the cache contents that should be incremented.
int $offset Optional. The amount by which to increment the item's value. Default 1.
string $group Optional. The group the key is in. Default empty.
Returns
false|int False on failure, the item's new value on success.
Definition at line 139 of file cache.php.
wp_cache_init ()
Sets up Object Cache Global and assigns it.
Since
2.0.0
WP_Object_Cache $wp_object_cache
Definition at line 152 of file cache.php.
References $GLOBALS.
Referenced by restore_current_blog(), switch_to_blog(), and wp_start_object_cache().
wp_cache_replace ($key, $data, $group = '', $expire = 0)
Replaces the contents of the cache with new data.
Since
2.0.0
See also
WP_Object_Cache::replace() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
int | string $key The key for the cache data that should be replaced.
mixed $data The new data to store in the cache.
string $group Optional. The group for the cache data that should be replaced. Default empty.
int $expire Optional. When to expire the cache contents, in seconds. Default 0 (no expiration).
Returns
bool False if original value does not exist, true if contents were replaced
Definition at line 172 of file cache.php.
wp_cache_reset ()
Reset internal cache keys and structures.
If the cache backend uses global blog or site IDs as part of its cache keys, this function instructs the backend to reset those keys and perform any cleanup since blog or site IDs have changed since cache init.
This function is deprecated. Use wp_cache_switch_to_blog() instead of this function when preparing the cache for a blog switch. For clearing the cache during unit tests, consider using wp_cache_init(). wp_cache_init() is not recommended outside of unit tests as the performance penality for using it is high.
Since
2.6.0
WP_Object_Cache $wp_object_cache Object cache global instance.
Definition at line 266 of file cache.php.
References _deprecated_function().
wp_cache_set ($key, $data, $group = '', $expire = 0)
Saves the data to the cache.
Differs from wp_cache_add() and wp_cache_replace() in that it will always write data.
Since
2.0.0
See also
WP_Object_Cache::set() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
int | string $key The cache key to use for retrieval later.
mixed $data The contents to store in the cache.
string $group Optional. Where to group the cache contents. Enables the same key to be used across groups. Default empty.
int $expire Optional. When to expire the cache contents, in seconds. Default 0 (no expiration).
Returns
bool False on failure, true on success
Definition at line 196 of file cache.php.
Referenced by _get_last_post_time(), add_network_option(), add_option(), add_term_meta(), clean_comment_cache(), clean_post_cache(), clean_term_cache(), WP_MS_Sites_List_Table\column_users(), delete_option(), delete_term_meta(), GravityView_API\directory_link(), get_adjacent_post(), get_blog_details(), get_blog_id_from_url(), get_bookmarks(), get_calendar(), WP_Comment_Query\get_comments(), get_id_from_blogname(), get_network_option(), get_option(), get_pages(), get_plugins(), get_terms(), is_blog_installed(), is_object_in_term(), set_site_transient(), set_transient(), update_network_option(), update_option(), update_term_meta(), Twenty_Eleven_Ephemera_Widget\widget(), wp_count_comments(), wp_count_posts(), wp_get_archives(), wp_insert_comment(), and wp_load_core_site_options().
wp_cache_switch_to_blog ($blog_id)
Switches the interal blog ID.
This changes the blog id used to create keys in blog specific groups.
Since
3.5.0
See also
WP_Object_Cache::switch_to_blog() WP_Object_Cache $wp_object_cache Object cache global instance.
Parameters
int $blog_id Blog ID.
Definition at line 214 of file cache.php.
References $blog_id.
Referenced by restore_current_blog(), switch_to_blog(), and wp_start_object_cache().