GravityView: canonical.php File Reference
canonical.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_remove_qs_args_if_not_in_url ($query_string, Array $args_to_check, $url)
Removes arguments from a query string if they are not present in a URL DO NOT use this in plugin code.
redirect_canonical ($requested_url=null, $do_redirect=true)
Redirects incoming links to the proper URL based on the site url.
redirect_guess_404_permalink ()
Attempts to guess the correct URL based on query vars.
strip_fragment_from_url ($url)
Strips the #fragment from a URL, if one is present.
wp_redirect_admin_locations ()
Redirects a variety of shorthand URLs to the admin.
Function Documentation
_remove_qs_args_if_not_in_url ($query_string, Array $args_to_check, $url)
Removes arguments from a query string if they are not present in a URL DO NOT use this in plugin code.
Since
3.4.0 private
Parameters
string $query_string
array $args_to_check
string $url
Returns
string The altered query string
Definition at line 531 of file canonical.php.
References $url, and remove_query_arg().
Referenced by redirect_canonical().
redirect_canonical ($requested_url = null, $do_redirect = true)
Redirects incoming links to the proper URL based on the site url.
Search engines consider www.somedomain.com and somedomain.com to be two different URLs when they both go to the same location. This SEO enhancement prevents penalty for duplicate content by redirecting all incoming links to one or the other.
Prevents redirection for feeds, trackbacks, searches, and admin URLs. Does not redirect on non-pretty-permalink-supporting IIS 7+, page/post previews, WP admin, Trackbacks, robots.txt, searches, or on POST requests.
Will also attempt to find the correct link when a user enters a URL that does not exist based on exact WordPress query. Will instead try to parse the URL or query in an attempt to figure the correct page to go to.
Since
2.3.0
WP_Rewrite $wp_rewrite bool $is_IIS WP_Query $wp_query wpdb $wpdb WordPress database abstraction object.
Parameters
string $requested_url Optional. The URL that was requested, used to figure if redirect is needed.
bool $do_redirect Optional. Redirect to the new URL.
Returns
string|void The string of the URL, if redirect needed.
This filter is documented in wp-login.php
Filter the canonical redirect URL.
Returning false to this filter will cancel the redirect.
Since
2.3.0
Parameters
string $redirect_url The redirect URL.
string $requested_url The requested URL.
Definition at line 41 of file canonical.php.
References $_SERVER, $id, $is_IIS, $page, $paged, $redirect, $wp, $wp_rewrite, $wpdb, _remove_qs_args_if_not_in_url(), add_query_arg(), apply_filters(), elseif, exit, false, get_attachment_link(), get_author_posts_url(), get_category_by_path(), get_day_link(), get_default_feed(), get_feed_link(), get_month_link(), get_option(), get_permalink(), get_post(), get_post_comments_feed_link(), get_post_status(), get_post_type_object(), get_queried_object_id(), get_query_var(), get_taxonomy(), get_term_link(), get_year_link(), home_url(), iis7_supports_permalinks(), is_404, is_admin(), is_attachment(), is_author(), is_category(), is_day(), is_feed(), is_front_page(), is_home(), is_month(), is_multisite(), is_page(), is_preview(), is_robots(), is_search(), is_single(), is_singular(), is_ssl(), is_tag(), is_tax(), is_trackback(), is_wp_error(), is_year(), network_site_url(), rawurlencode_deep(), redirect_guess_404_permalink(), remove_query_arg(), str_replace, strip_fragment_from_url(), trailingslashit(), user_trailingslashit(), wp_checkdate(), wp_get_object_terms(), and wp_registration_url().
Referenced by WP_Canonical_UnitTestCase\get_canonical().
redirect_guess_404_permalink ()
Attempts to guess the correct URL based on query vars.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Returns
false|string The correct URL if one is found. False on failure.
Definition at line 579 of file canonical.php.
References $post_id, $wpdb, elseif, get_permalink(), get_post_comments_feed_link(), get_post_types(), get_query_var(), trailingslashit(), and user_trailingslashit().
Referenced by redirect_canonical().
strip_fragment_from_url ($url)
Strips the #fragment from a URL, if one is present.
Since
4.4.0
Parameters
string $url The URL to strip.
Returns
string The altered URL.
Definition at line 553 of file canonical.php.
References $url.
Referenced by redirect_canonical().
wp_redirect_admin_locations ()
Redirects a variety of shorthand URLs to the admin.
If a user visits example.com/admin, they'll be redirected to /wp-admin. Visiting /login redirects to /wp-login.php, and so on.
Since
3.4.0
WP_Rewrite $wp_rewrite
Definition at line 622 of file canonical.php.
References $_SERVER, $wp_rewrite, admin_url(), exit, home_url(), is_404, site_url(), untrailingslashit(), and wp_login_url().