GravityView: capabilities.php File Reference
capabilities.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
add_role ($role, $display_name, $capabilities=array())
Add role, if it does not exist.
author_can ($post, $capability)
Whether author of supplied post has capability or role.
current_user_can ($capability)
Whether the current user has a specific capability.
current_user_can_for_blog ($blog_id, $capability)
Whether current user has a capability or role for a given blog.
get_role ($role)
Retrieve role object.
get_super_admins ()
Retrieve a list of super admins.
is_super_admin ($user_id=false)
Determine if user is a site admin.
map_meta_cap ($cap, $user_id)
Map meta capabilities to primitive capabilities.
remove_role ($role)
Remove role, if it exists.
user_can ($user, $capability)
Whether a particular user has capability or role.
wp_roles ()
Retrieves the global WP_Roles instance and instantiates it if necessary.
Function Documentation
add_role ($role, $display_name, $capabilities = array())
Add role, if it does not exist.
Since
2.0.0
Parameters
string $role Role name.
string $display_name Display name for role.
array $capabilities List of capabilities, e.g. array('edit_posts' => true, 'delete_posts' => false);
Returns
WP_Role|null WP_Role object if role is added, null if already exists.
Definition at line 554 of file capabilities.php.
References wp_roles().
Referenced by GV_Unit_Tests_Bootstrap\create_stubs(), and populate_roles_160().
author_can ($post, $capability)
Whether author of supplied post has capability or role.
Since
2.9.0
Parameters
int | object $post Post ID or post object.
string $capability Capability or role name.
Returns
bool
Definition at line 477 of file capabilities.php.
References $capability, $post, and get_post().
current_user_can ($capability)
Whether the current user has a specific capability.
While checking against particular roles in place of a capability is supported in part, this practice is discouraged as it may produce unreliable results.
Since
2.0.0
See also
WP_User::has_cap()
map_meta_cap()
Parameters
string $capability Capability name.
int $object_id Optional. ID of the specific object to check against if $capability is a "meta" cap. "Meta" capabilities, e.g. 'edit_post', 'edit_user', etc., are capabilities used by map_meta_cap() to map to other "primitive" capabilities, e.g. 'edit_posts', 'edit_others_posts', etc. Accessed via func_get_args() and passed to WP_User::has_cap(), then map_meta_cap().
Returns
bool Whether the current user has the given capability. If $capability is a meta cap and $object_id is passed, whether the current user has the given meta capability for the given object.
Definition at line 423 of file capabilities.php.
References $capability, and $current_user.
Referenced by WP_Posts_List_Table\__construct(), GravityView_Edit_Entry_Test\_add_and_remove_caps_test(), _count_posts_cache_key(), WP_Media_List_Table\_get_row_actions(), wp_xmlrpc_server\_getOptions(), wp_xmlrpc_server\_insert_post(), GravityView_Support_Port\_localize_script(), wp_xmlrpc_server\_toggle_sticky(), _wp_ajax_add_hierarchical_term(), _wp_dashboard_recent_comments_row(), _wp_handle_upload(), _wp_translate_postdata(), WP_Press_This\add_category(), add_menu_page(), add_meta(), add_submenu_page(), add_users_page(), Custom_Background\admin_page(), Custom_Image_Header\admin_page(), Plugin_Upgrader_Skin\after(), Custom_Image_Header\ajax_header_add(), Custom_Image_Header\ajax_header_crop(), Custom_Image_Header\ajax_header_remove(), WP_Customize_Nav_Menus\ajax_load_available_items(), WP_Customize_Nav_Menus\ajax_search_available_items(), WP_MS_Users_List_Table\ajax_user_can(), WP_Theme_Install_List_Table\ajax_user_can(), WP_Plugin_Install_List_Table\ajax_user_can(), WP_Links_List_Table\ajax_user_can(), WP_Themes_List_Table\ajax_user_can(), WP_MS_Sites_List_Table\ajax_user_can(), WP_Media_List_Table\ajax_user_can(), WP_Plugins_List_Table\ajax_user_can(), WP_Comments_List_Table\ajax_user_can(), WP_Users_List_Table\ajax_user_can(), WP_Terms_List_Table\ajax_user_can(), WP_MS_Themes_List_Table\ajax_user_can(), WP_Posts_List_Table\ajax_user_can(), attachment_submit_meta_box(), wp_xmlrpc_server\blogger_deletePost(), wp_xmlrpc_server\blogger_editPost(), wp_xmlrpc_server\blogger_getPost(), wp_xmlrpc_server\blogger_getRecentPosts(), wp_xmlrpc_server\blogger_getUserInfo(), wp_xmlrpc_server\blogger_getUsersBlogs(), wp_xmlrpc_server\blogger_newPost(), bulk_edit_posts(), WP_Press_This\categories_html(), check_comment_flood_db(), WP_Terms_List_Table\column_cb(), WP_Media_List_Table\column_cb(), WP_Posts_List_Table\column_cb(), WP_MS_Themes_List_Table\column_name(), WP_Media_List_Table\column_parent(), WP_Comments_List_Table\column_response(), WP_Media_List_Table\column_title(), WP_Posts_List_Table\column_title(), confirm_delete_users(), core_update_footer(), GFForms\create_menu(), WP_Themes_List_Table\display_rows(), WP_Plugin_Install_List_Table\display_rows(), edit_bookmark_link(), edit_comment(), edit_comment_link(), edit_link(), edit_post(), edit_term_link(), edit_user(), _WP_Editors\editor(), WP_Internal_Pointers\enqueue_scripts(), WP_Media_List_Table\extra_tablenav(), WP_Users_List_Table\extra_tablenav(), WP_Comments_List_Table\extra_tablenav(), WP_Posts_List_Table\extra_tablenav(), get_adjacent_post(), get_allowed_mime_types(), WP_MS_Users_List_Table\get_bulk_actions(), WP_MS_Sites_List_Table\get_bulk_actions(), WP_Users_List_Table\get_bulk_actions(), WP_MS_Themes_List_Table\get_bulk_actions(), WP_Posts_List_Table\get_bulk_actions(), WP_Plugins_List_Table\get_bulk_actions(), get_compat_media_markup(), wp_xmlrpc_server\get_custom_fields(), get_delete_post_link(), get_edit_bookmark_link(), get_edit_comment_link(), get_edit_post_link(), get_edit_term_link(), get_edit_user_link(), GFFormDisplay\get_form(), get_inline_data(), get_media_item(), WP_Query\get_posts(), get_posts_by_author_sql(), get_sample_permalink_html(), get_theme_feature_list(), get_theme_update_available(), GFForms\handle_ajax_do_shortcode(), WP_Terms_List_Table\handle_row_actions(), WP_MS_Users_List_Table\handle_row_actions(), WP_MS_Sites_List_Table\handle_row_actions(), WP_Posts_List_Table\handle_row_actions(), GravityView_Roles_Capabilities\has_cap(), WP_Press_This\html(), WP_Terms_List_Table\inline_edit(), WP_Posts_List_Table\inline_edit(), install_plugin_install_status(), kses_init(), kses_init_filters(), link_submit_meta_box(), maintenance_nag(), media_upload_form_handler(), media_upload_max_image_resize(), meta_form(), wp_xmlrpc_server\mt_getCategoryList(), wp_xmlrpc_server\mt_getPostCategories(), wp_xmlrpc_server\mt_getRecentPostTitles(), wp_xmlrpc_server\mt_publishPost(), wp_xmlrpc_server\mt_setPostCategories(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_getCategories(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), wp_xmlrpc_server\mw_newMediaObject(), wp_xmlrpc_server\mw_newPost(), WP_Themes_List_Table\no_items(), WP_Plugins_List_Table\no_items(), post_categories_meta_box(), post_custom_meta_box(), post_submit_meta_box(), post_tags_meta_box(), WP_Plugin_Install_List_Table\prepare_items(), WP_Plugins_List_Table\prepare_items(), WP_MS_Themes_List_Table\prepare_items(), WP_Customize_Header_Image_Control\render_content(), WP_Customize_Nav_Menus\render_menu(), WP_Screen\render_meta_boxes_preferences(), GF_Field_HTML\sanitize_settings(), WP_Press_This\save_post(), wp_xmlrpc_server\set_custom_fields(), WP_Customize_Manager\setup_theme(), WP_Press_This\side_load_images(), WP_Users_List_Table\single_row(), WP_Comments_List_Table\single_row(), WP_Plugins_List_Table\single_row(), Custom_Image_Header\step_1(), WP_Press_This\tags_html(), Custom_Image_Header\take_action(), WP_Customize_Media_Control\to_json(), WP_Widget_Text\update(), update_nag(), update_right_now_message(), GravityView_Support_Port\update_user_meta_value(), user_can_access_admin_page(), GravityView_Support_Port\user_field(), GFForms\user_has_cap(), validate_active_plugins(), wp_add_dashboard_widget(), wp_admin_bar_appearance_menu(), wp_admin_bar_comments_menu(), wp_admin_bar_customize_menu(), wp_admin_bar_edit_menu(), wp_admin_bar_my_account_item(), wp_admin_bar_my_account_menu(), wp_admin_bar_my_sites_menu(), wp_admin_bar_new_content_menu(), wp_admin_bar_site_menu(), wp_ajax_add_link_category(), wp_ajax_add_menu_item(), wp_ajax_add_meta(), wp_ajax_add_tag(), wp_ajax_add_user(), wp_ajax_ajax_tag_search(), wp_ajax_autocomplete_user(), wp_ajax_crop_image(), wp_ajax_delete_comment(), wp_ajax_delete_inactive_widgets(), wp_ajax_delete_link(), wp_ajax_delete_meta(), wp_ajax_delete_page(), wp_ajax_delete_post(), wp_ajax_delete_tag(), wp_ajax_destroy_sessions(), wp_ajax_dim_comment(), wp_ajax_edit_comment(), wp_ajax_get_attachment(), wp_ajax_get_comments(), wp_ajax_get_revision_diffs(), wp_ajax_get_tagcloud(), wp_ajax_image_editor(), wp_ajax_imgedit_preview(), wp_ajax_inline_save(), wp_ajax_inline_save_tax(), wp_ajax_menu_get_metabox(), wp_ajax_menu_locations_save(), wp_ajax_menu_quick_search(), wp_ajax_parse_embed(), wp_ajax_parse_media_shortcode(), wp_ajax_query_attachments(), wp_ajax_query_themes(), wp_ajax_replyto_comment(), wp_ajax_save_attachment(), wp_ajax_save_attachment_compat(), wp_ajax_save_attachment_order(), wp_ajax_save_widget(), wp_ajax_save_wporg_username(), wp_ajax_send_attachment_to_editor(), wp_ajax_set_attachment_thumbnail(), wp_ajax_set_post_thumbnail(), wp_ajax_trash_post(), wp_ajax_update_plugin(), wp_ajax_update_welcome_panel(), WP_Customize_Widgets\wp_ajax_update_widget(), wp_ajax_upload_attachment(), wp_ajax_widgets_order(), wp_ajax_wp_compression_test(), wp_ajax_wp_remove_post_lock(), wp_check_locked_posts(), wp_comment_form_unfiltered_html_nonce(), wp_comment_reply(), wp_count_posts(), wp_dashboard_quick_press(), wp_dashboard_right_now(), wp_dashboard_setup(), wp_xmlrpc_server\wp_deleteCategory(), wp_xmlrpc_server\wp_deleteComment(), wp_xmlrpc_server\wp_deletePage(), wp_xmlrpc_server\wp_deletePost(), wp_xmlrpc_server\wp_deleteTerm(), wp_edit_attachments_query_vars(), wp_xmlrpc_server\wp_editComment(), wp_xmlrpc_server\wp_editPage(), wp_xmlrpc_server\wp_editProfile(), wp_xmlrpc_server\wp_editTerm(), wp_get_update_data(), wp_xmlrpc_server\wp_getAuthors(), wp_xmlrpc_server\wp_getComment(), wp_xmlrpc_server\wp_getCommentCount(), wp_xmlrpc_server\wp_getComments(), wp_xmlrpc_server\wp_getCommentStatusList(), wp_xmlrpc_server\wp_getMediaItem(), wp_xmlrpc_server\wp_getMediaLibrary(), wp_xmlrpc_server\wp_getPage(), wp_xmlrpc_server\wp_getPageList(), wp_xmlrpc_server\wp_getPages(), wp_xmlrpc_server\wp_getPageStatusList(), wp_xmlrpc_server\wp_getPageTemplates(), wp_xmlrpc_server\wp_getPost(), wp_xmlrpc_server\wp_getPostFormats(), wp_xmlrpc_server\wp_getPosts(), wp_xmlrpc_server\wp_getPostStatusList(), wp_xmlrpc_server\wp_getPostType(), wp_xmlrpc_server\wp_getPostTypes(), wp_xmlrpc_server\wp_getProfile(), wp_xmlrpc_server\wp_getRevisions(), wp_xmlrpc_server\wp_getTags(), wp_xmlrpc_server\wp_getTaxonomies(), wp_xmlrpc_server\wp_getTaxonomy(), wp_xmlrpc_server\wp_getTerm(), wp_xmlrpc_server\wp_getTerms(), wp_xmlrpc_server\wp_getUser(), wp_xmlrpc_server\wp_getUsers(), wp_xmlrpc_server\wp_getUsersBlogs(), wp_handle_comment_submission(), wp_insert_post(), wp_link_manager_disabled_message(), wp_list_post_revisions(), wp_media_attach_action(), wp_network_dashboard_right_now(), wp_xmlrpc_server\wp_newCategory(), wp_xmlrpc_server\wp_newTerm(), wp_plugin_update_row(), wp_plugin_update_rows(), wp_popular_terms_checklist(), wp_post_revision_title(), wp_post_revision_title_expanded(), wp_prepare_attachment_for_js(), wp_prepare_revisions_for_js(), wp_prepare_themes_for_js(), wp_refresh_post_lock(), wp_refresh_post_nonces(), wp_register(), wp_xmlrpc_server\wp_restoreRevision(), wp_xmlrpc_server\wp_setOptions(), wp_xmlrpc_server\wp_suggestCategories(), wp_terms_checklist(), wp_theme_update_row(), wp_theme_update_rows(), wp_upload_bits(), wp_widget_rss_output(), and wp_write_post().
current_user_can_for_blog ($blog_id, $capability)
Whether current user has a capability or role for a given blog.
Since
3.0.0
Parameters
int $blog_id Blog ID
string $capability Capability or role name.
Returns
bool
Definition at line 444 of file capabilities.php.
References $blog_id, $capability, $current_user, $switched, is_multisite(), restore_current_blog(), and switch_to_blog().
get_role ($role)
Retrieve role object.
Since
2.0.0
Parameters
string $role Role name.
Returns
WP_Role|null WP_Role object if found, null if the role does not exist.
Definition at line 540 of file capabilities.php.
References wp_roles().
Referenced by populate_roles_160(), populate_roles_210(), populate_roles_230(), populate_roles_250(), populate_roles_260(), populate_roles_270(), populate_roles_280(), populate_roles_300(), sanitize_option(), and wp_xmlrpc_server\wp_getUsers().
get_super_admins ()
Retrieve a list of super admins.
Since
3.0.0
array $super_admins
Returns
array List of super admin logins
Definition at line 581 of file capabilities.php.
References get_site_option().
Referenced by WP_MS_Users_List_Table\column_username(), confirm_delete_users(), WP_MS_Users_List_Table\get_views(), WP_MS_Users_List_Table\handle_row_actions(), is_super_admin(), WP_MS_Users_List_Table\prepare_items(), and wpmu_delete_user().
is_super_admin ($user_id = false)
Determine if user is a site admin.
Since
3.0.0
Parameters
int $user_id (Optional) The ID of a user. Defaults to the current user.
Returns
bool True if the user is a site admin.
Definition at line 598 of file capabilities.php.
References $user, $user_id, get_current_user_id(), get_super_admins(), and is_multisite().
Referenced by check_import_new_users(), GravityView_Admin_Notices\check_show_multisite_notices(), WP_MS_Users_List_Table\column_cb(), GFForms\dashboard(), get_dashboard_url(), WP_User\has_cap(), WP_Posts_List_Table\inline_edit(), is_site_admin(), map_meta_cap(), ms_site_check(), populate_network(), GFSettings\settings_uninstall_page(), site_admin_notice(), GFForms\user_has_cap(), wp_admin_bar_my_sites_menu(), wp_admin_bar_site_menu(), wp_ajax_autocomplete_user(), wp_dashboard_quick_press(), wp_set_all_user_settings(), wp_user_settings(), wpmu_create_blog(), and wpmu_validate_blog_signup().
map_meta_cap ($cap, $user_id)
Map meta capabilities to primitive capabilities.
This does not actually compare whether the user ID has the actual capability, just what the capability or capabilities are. Meta capability list value can be 'delete_user', 'edit_user', 'remove_user', 'promote_user', 'delete_post', 'delete_page', 'edit_post', 'edit_page', 'read_post', or 'read_page'.
Since
2.0.0
Parameters
string $cap Capability name.
int $user_id User ID.
int $object_id Optional. ID of the specific object to check against if $cap is a "meta" cap. "Meta" capabilities, e.g. 'edit_post', 'edit_user', etc., are capabilities used by map_meta_cap() to map to other "primitive" capabilities, e.g. 'edit_posts', 'edit_others_posts', etc. The parameter is accessed via func_get_args().
Returns
array Actual capabilities for meta capability.
Filter whether the user is allowed to add post meta to a post.
The dynamic portion of the hook name, $meta_key, refers to the meta key passed to {
See also
map_meta_cap()}.
Since
3.3.0
Parameters
bool $allowed Whether the user can add the post meta. Default false.
string $meta_key The meta key.
int $post_id Post ID.
int $user_id User ID.
string $cap Capability name.
array $caps User capabilities.
Filter a user's capabilities depending on specific context and/or privilege.
Since
2.8.0
Parameters
array $caps Returns the user's actual capabilities.
string $cap Capability name.
int $user_id The user ID.
array $args Adds the context to the cap. Typically the object ID.
Definition at line 27 of file capabilities.php.
References $comment, $post, $post_type, $user_id, __, _doing_it_wrong(), _post_type_meta_capabilities(), apply_filters(), elseif, get_comment(), get_option(), get_post(), get_post_meta(), get_post_status_object(), get_post_type_object(), get_site_option(), has_filter(), is_multisite(), is_protected_meta(), is_super_admin(), and user_can().
remove_role ($role)
Remove role, if it exists.
Since
2.0.0
Parameters
string $role Role name.
Definition at line 568 of file capabilities.php.
References wp_roles().
user_can ($user, $capability)
Whether a particular user has capability or role.
Since
3.1.0
Parameters
int | object $user User ID or object.
string $capability Capability or role name.
Returns
bool
Definition at line 501 of file capabilities.php.
References $capability, and $user.
Referenced by WP_Comments_List_Table\column_author(), WP_Comments_List_Table\column_cb(), WP_Comments_List_Table\column_comment(), get_allowed_mime_types(), WP_Comments_List_Table\handle_row_actions(), GravityView_Roles_Capabilities\has_cap(), map_meta_cap(), and WP_Comments_List_Table\single_row().
wp_roles ()
Retrieves the global WP_Roles instance and instantiates it if necessary.
Since
4.3.0
WP_Roles $wp_roles WP_Roles global instance.
Returns
WP_Roles WP_Roles global instance if not already instantiated.
Definition at line 523 of file capabilities.php.
Referenced by WP_Role\add_cap(), add_role(), count_users(), edit_user(), get_editable_roles(), get_role(), WP_User\get_role_caps(), WP_Users_List_Table\get_role_list(), WP_Users_List_Table\get_views(), WP_Role\remove_cap(), remove_role(), restore_current_blog(), switch_to_blog(), upgrade_440(), and wp_get_users_with_no_role().