GravityView: category-template.php File Reference
category-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_usort_terms_by_ID ($a, $b)
Sort categories by ID.
_usort_terms_by_name ($a, $b)
Sort categories by name.
_wp_object_count_sort_cb ($a, $b)
Serves as a callback for comparing objects based on count.
_wp_object_name_sort_cb ($a, $b)
Serves as a callback for comparing objects based on name.
category_description ($category=0)
Retrieve category description.
default_topic_count_scale ($count)
Default topic count scaling for tag links.
get_category_link ($category)
Retrieve category link URL.
get_category_parents ($id, $link=false, $separator= '/', $nicename=false, $visited=array())
Retrieve category parents with separator.
get_tag_link ($tag)
Retrieve the link to the tag.
get_the_category ($id=false)
Retrieve post categories.
get_the_category_by_ID ($cat_ID)
Retrieve category name based on category ID.
get_the_category_list ($separator= '', $parents='', $post_id=false)
Retrieve category list in either HTML list or custom format.
get_the_tag_list ($before= '', $sep= '', $after= '', $id=0)
Retrieve the tags for a post formatted as a string.
get_the_tags ($id=0)
Retrieve the tags for a post.
get_the_term_list ($id, $taxonomy, $before= '', $sep= '', $after= '')
Retrieve a post's terms as a list with specified format.
get_the_terms ($post, $taxonomy)
Retrieve the terms of the taxonomy that are attached to the post.
has_category ($category= '', $post=null)
Check if the current post has any of given category.
has_tag ($tag= '', $post=null)
Check if the current post has any of given tags.
has_term ($term= '', $taxonomy= '', $post=null)
Check if the current post has any of given terms.
in_category ($category, $post=null)
Check if the current post in within any of the given categories.
tag_description ($tag=0)
Retrieve tag description.
term_description ($term=0, $taxonomy= 'post_tag')
Retrieve term description.
the_category ($separator= '', $parents='', $post_id=false)
Display the category list for the post.
the_tags ($before=null, $sep= ', ', $after= '')
Retrieve the tags for a post.
the_terms ($id, $taxonomy, $before= '', $sep= ', ', $after= '')
Display the terms in a list.
walk_category_dropdown_tree ()
Retrieve HTML dropdown (select) content for category list.
walk_category_tree ()
Retrieve HTML list content for category list.
wp_dropdown_categories ($args= '')
Display or retrieve the HTML dropdown list of categories.
wp_generate_tag_cloud ($tags, $args= '')
Generates a tag cloud (heatmap) from provided data.
wp_list_categories ($args= '')
Display or retrieve the HTML list of categories.
wp_tag_cloud ($args= '')
Display tag cloud.
Function Documentation
_usort_terms_by_ID ($a, $b)
Sort categories by ID.
Used by usort() as a callback, should not be used directly. Can actually be used to sort any term object.
Since
2.3.0 private
Parameters
object $a
object $b
Returns
int
Definition at line 132 of file category-template.php.
References elseif.
_usort_terms_by_name ($a, $b)
Sort categories by name.
Used by usort() as a callback, should not be used directly. Can actually be used to sort any term object.
Since
2.3.0 private
Parameters
object $a
object $b
Returns
int
Definition at line 115 of file category-template.php.
_wp_object_count_sort_cb ($a, $b)
Serves as a callback for comparing objects based on count.
Used with uasort().
Since
3.1.0 private
Parameters
object $a The first object to compare.
object $b The second object to compare.
Returns
bool Whether the count value for $a is greater than the count value for $b.
Definition at line 988 of file category-template.php.
_wp_object_name_sort_cb ($a, $b)
Serves as a callback for comparing objects based on name.
Used with uasort().
Since
3.1.0 private
Parameters
object $a The first object to compare.
object $b The second object to compare.
Returns
int Negative number if $a->name is less than $b->name, zero if they are equal, or greater than zero if $a->name is greater than $b->name.
Definition at line 972 of file category-template.php.
category_description ($category = 0)
Retrieve category description.
Since
1.0.0
Parameters
int $category Optional. Category ID. Will use global category ID by default.
Returns
string Category description, available.
Definition at line 303 of file category-template.php.
References term_description().
default_topic_count_scale ($count)
Default topic count scaling for tag links.
Parameters
int $count number of posts with that tag
Returns
int scaled count
Definition at line 753 of file category-template.php.
References $count.
get_category_link ($category)
Retrieve category link URL.
Since
1.0.0
See also
get_term_link()
Parameters
int | object $category Category ID or object.
Returns
string Link on success, empty string if category does not exist.
Definition at line 19 of file category-template.php.
References get_term_link(), and is_wp_error().
Referenced by get_category_parents(), get_the_category_list(), and wp_xmlrpc_server\mw_getCategories().
get_category_parents ($id, $link = false, $separator = '/', $nicename = false, $visited = array())
Retrieve category parents with separator.
Since
1.2.0
Parameters
int $id Category ID.
bool $link Optional, default is false. Whether to format with link.
string $separator Optional, default is '/'. How to separate categories.
bool $nicename Optional, default is false. Whether to use nice name for display.
array $visited Optional. Already linked to categories to prevent duplicates.
Returns
string|WP_Error A list of category parents on success, WP_Error on failure.
Definition at line 43 of file category-template.php.
References $id, $link, $name, esc_url, get_category_link(), get_term(), and is_wp_error().
Referenced by get_permalink(), and get_the_category_list().
get_tag_link ($tag)
Retrieve the link to the tag.
Since
2.3.0
See also
get_term_link()
Parameters
int | object $tag Tag ID or object.
Returns
string Link on success, empty string if tag does not exist.
Definition at line 1047 of file category-template.php.
References get_term_link(), and is_wp_error().
Referenced by wp_xmlrpc_server\wp_getTags().
get_the_category ($id = false)
Retrieve post categories.
This tag may be used outside The Loop by passing a post id as the parameter.
Note: This function only returns results from the default "category" taxonomy. For custom taxonomies use get_the_terms().
Since
0.71
Parameters
int $id Optional, default to current post ID. The post ID.
Returns
array Array of objects, one for each category assigned to the post.
Filter the array of categories to return for a post.
Since
3.1.0
4.4.0 Added $id parameter.
Parameters
array $categories An array of categories to return for the post.
int $id ID of the post.
Definition at line 79 of file category-template.php.
References $id, _make_cat_compat(), apply_filters(), get_the_terms(), and is_wp_error().
Referenced by get_permalink(), get_the_category_list(), get_the_category_rss(), the_category_head(), and the_category_ID().
get_the_category_by_ID ($cat_ID)
Retrieve category name based on category ID.
Since
0.71
Parameters
int $cat_ID Category ID.
Returns
string|WP_Error Category name on success, WP_Error on failure.
Definition at line 149 of file category-template.php.
References get_term(), and is_wp_error().
Referenced by the_category_head().
get_the_category_list ($separator = '', $parents = '', $post_id = false)
Retrieve category list in either HTML list or custom format.
Since
1.5.1
WP_Rewrite $wp_rewrite
Parameters
string $separator Optional, default is empty string. Separator for between the categories.
string $parents Optional. How to display the parents.
int $post_id Optional. Post ID to retrieve categories.
Returns
string
This filter is documented in wp-includes/category-template.php
Filter the categories before building the category list.
Since
4.4.0
Parameters
array $categories An array of the post's categories.
int | bool $post_id ID of the post we're retrieving categories for. When false, we assume the current post in the loop.
This filter is documented in wp-includes/category-template.php
Filter the category or list of categories.
Since
1.2.0
Parameters
array $thelist List of categories for the current post.
string $separator Separator used between the categories.
string $parents How to display the category parents. Accepts 'multiple', 'single', or empty.
Definition at line 171 of file category-template.php.
References $i, $post_id, $wp_rewrite, __, apply_filters(), esc_url, get_category_link(), get_category_parents(), get_post_type(), get_the_category(), and is_object_in_taxonomy().
Referenced by the_category().
get_the_tag_list ($before = '', $sep = '', $after = '', $id = 0)
Retrieve the tags for a post formatted as a string.
Since
2.3.0
Parameters
string $before Optional. Before tags.
string $sep Optional. Between tags.
string $after Optional. After tags.
int $id Optional. Post ID. Defaults to the current post.
Returns
string|false|WP_Error A list of tags on success, false if there are no terms, WP_Error on failure.
Filter the tags list for a given post.
Since
2.3.0
Parameters
string $tag_list List of tags.
string $before String to use before tags.
string $sep String to use between the tags.
string $after String to use after tags.
int $id Post ID.
Definition at line 1092 of file category-template.php.
References $id, apply_filters(), and get_the_term_list().
Referenced by the_tags().
get_the_tags ($id = 0)
Retrieve the tags for a post.
Since
2.3.0
Parameters
int $id Post ID.
Returns
array|false|WP_Error Array of tag objects on success, false on failure.
Filter the array of tags for the given post.
Since
2.3.0
See also
get_the_terms()
Parameters
array $terms An array of tags for the given post.
Definition at line 1067 of file category-template.php.
References $id, apply_filters(), and get_the_terms().
Referenced by get_the_category_rss().
get_the_term_list ($id, $taxonomy, $before = '', $sep = '', $after = '')
Retrieve a post's terms as a list with specified format.
Since
2.5.0
Parameters
int $id Post ID.
string $taxonomy Taxonomy name.
string $before Optional. Before list.
string $sep Optional. Separate items using this.
string $after Optional. After list.
Returns
string|false|WP_Error A list of terms on success, false if there are no terms, WP_Error on failure.
Filter the term links for a given taxonomy.
The dynamic portion of the filter name, $taxonomy, refers to the taxonomy slug.
Since
2.5.0
Parameters
array $links An array of term links.
Definition at line 1215 of file category-template.php.
References $id, $link, apply_filters(), esc_url, get_term_link(), get_the_terms(), and is_wp_error().
Referenced by get_the_tag_list(), gravityview_get_the_term_list(), and the_terms().
get_the_terms ($post, $taxonomy)
Retrieve the terms of the taxonomy that are attached to the post.
Since
2.5.0
Parameters
int | object $post Post ID or object.
string $taxonomy Taxonomy name.
Returns
array|false|WP_Error Array of term objects on success, false if there are no terms or the post does not exist, WP_Error on failure.
Filter the list of terms attached to the given post.
Since
3.1.0
Parameters
array | WP_Error $terms List of attached terms, or WP_Error on failure.
int $post_id Post ID.
string $taxonomy Name of the taxonomy.
Definition at line 1166 of file category-template.php.
References $post, apply_filters(), get_object_term_cache(), get_post(), is_wp_error(), wp_cache_add(), and wp_get_object_terms().
Referenced by WP_Post\__get(), WP_Media_List_Table\column_default(), WP_Posts_List_Table\column_default(), get_post_class(), get_post_format(), get_the_category(), get_the_tags(), and get_the_term_list().
has_category ($category = '', $post = null)
Check if the current post has any of given category.
Since
3.1.0
Parameters
string | int | array $category Optional. The category name/term_id/slug or array of them to check for.
int | object $post Optional. Post to check instead of the current post.
Returns
bool True if the current post has any of the given categories (or any category, if no category specified).
Definition at line 1290 of file category-template.php.
References $post, and has_term().
Referenced by in_category().
has_tag ($tag = '', $post = null)
Check if the current post has any of given tags.
The given tags are checked against the post's tags' term_ids, names and slugs. Tags given as integers will only be checked against the post's tags' term_ids. If no tags are given, determines if post has any tags.
Prior to v2.7 of WordPress, tags given as integers would also be checked against the post's tags' names and slugs (in addition to term_ids) Prior to v2.7, this function could only be used in the WordPress Loop. As of 2.7, the function can be used anywhere if it is provided a post ID or post object.
Since
2.6.0
Parameters
string | int | array $tag Optional. The tag name/term_id/slug or array of them to check for.
int | object $post Optional. Post to check instead of the current post. (since 2.7.0)
Returns
bool True if the current post has any of the given tags (or any tag, if no tag specified).
Definition at line 1311 of file category-template.php.
References $post, and has_term().
has_term ($term = '', $taxonomy = '', $post = null)
Check if the current post has any of given terms.
The given terms are checked against the post's terms' term_ids, names and slugs. Terms given as integers will only be checked against the post's terms' term_ids. If no terms are given, determines if post has any terms.
Since
3.1.0
Parameters
string | int | array $term Optional. The term name/term_id/slug or array of them to check for.
string $taxonomy Taxonomy name
int | object $post Optional. Post to check instead of the current post.
Returns
bool True if the current post has any of the given tags (or any tag, if no tag specified).
Definition at line 1329 of file category-template.php.
References $post, get_post(), is_object_in_term(), and is_wp_error().
Referenced by has_category(), has_post_format(), and has_tag().
in_category ($category, $post = null)
Check if the current post in within any of the given categories.
The given categories are checked against the post's categories' term_ids, names and slugs. Categories given as integers will only be checked against the post's categories' term_ids.
Prior to v2.5 of WordPress, category names were not supported. Prior to v2.7, category slugs were not supported. Prior to v2.7, only one category could be compared: in_category($single_category). Prior to v2.7, this function could only be used in the WordPress Loop. As of 2.7, the function can be used anywhere if it is provided a post ID or post object.
Since
1.2.0
Parameters
int | string | array $category Category ID, name or slug, or array of said.
int | object $post Optional. Post to check instead of the current post. (since 2.7.0)
Returns
bool True if the current post is in any of the given categories.
Definition at line 275 of file category-template.php.
References $post, and has_category().
tag_description ($tag = 0)
Retrieve tag description.
Since
2.8.0
Parameters
int $tag Optional. Tag ID. Will use global tag ID by default.
Returns
string Tag description, available.
Definition at line 1131 of file category-template.php.
References term_description().
term_description ($term = 0, $taxonomy = 'post_tag')
Retrieve term description.
Since
2.8.0
Parameters
int $term Optional. Term ID. Will use global term ID by default.
string $taxonomy Optional taxonomy name. Defaults to 'post_tag'.
Returns
string Term description, available.
Definition at line 1144 of file category-template.php.
References $description, get_queried_object(), get_term_field(), is_category(), is_tag(), is_tax(), and is_wp_error().
Referenced by category_description(), get_the_archive_description(), and tag_description().
the_category ($separator = '', $parents = '', $post_id = false)
Display the category list for the post.
Since
0.71
Parameters
string $separator Optional, default is empty string. Separator for between the categories.
string $parents Optional. How to display the parents.
int $post_id Optional. Post ID to retrieve categories.
Definition at line 291 of file category-template.php.
References $post_id, and get_the_category_list().
the_tags ($before = null, $sep = ', ' , $after = '')
Retrieve the tags for a post.
Since
2.3.0
Parameters
string $before Optional. Before list.
string $sep Optional. Separate items using this.
string $after Optional. After list.
Definition at line 1117 of file category-template.php.
References __, get_the_tag_list(), and null.
the_terms ($id, $taxonomy, $before = '', $sep = ', ' , $after = '')
Display the terms in a list.
Since
2.5.0
Parameters
int $id Post ID.
string $taxonomy Taxonomy name.
string $before Optional. Before list.
string $sep Optional. Separate items using this.
string $after Optional. After list.
Returns
false|void False on WordPress error.
Filter the list of terms to display.
Since
2.9.0
Parameters
array $term_list List of terms to display.
string $taxonomy The taxonomy name.
string $before String to use before the terms.
string $sep String to use between the terms.
string $after String to use after the terms.
Definition at line 1261 of file category-template.php.
References $id, apply_filters(), get_the_term_list(), and is_wp_error().
walk_category_dropdown_tree ()
Retrieve HTML dropdown (select) content for category list.
Walker_CategoryDropdown to create HTML dropdown content.
Since
2.1.0
See also
Walker_CategoryDropdown::walk() for parameters and return description.
Returns
string
Definition at line 1023 of file category-template.php.
Referenced by wp_dropdown_categories().
walk_category_tree ()
Retrieve HTML list content for category list.
Walker_Category to create HTML list content.
Since
2.1.0
See also
Walker_Category::walk() for parameters and return description.
Returns
string
Definition at line 1004 of file category-template.php.
Referenced by wp_list_categories().
wp_dropdown_categories ($args = '')
Display or retrieve the HTML dropdown list of categories.
The 'hierarchical' argument, which is disabled by default, will override the depth argument, unless it is true. When the argument is false, it will display all of the categories. When it is enabled it will use the value in the 'depth' argument.
Since
2.1.0
4.2.0 Introduced the value_field argument.
Parameters
string | array $args { Optional. Array or string of arguments to generate a categories drop-down element.
string $show_option_all Text to display for showing all categories. Default empty. string $show_option_none Text to display for showing no categories. Default empty. string $option_none_value Value to use when no category is selected. Default empty. string $orderby Which column to use for ordering categories. See get_terms() for a list of accepted values. Default 'id' (term_id). string $order Whether to order terms in ascending or descending order. Accepts 'ASC' or 'DESC'. Default 'ASC'. bool $pad_counts See get_terms() for an argument description. Default false. bool|int $show_count Whether to include post counts. Accepts 0, 1, or their bool equivalents. Default 0. bool|int $hide_empty Whether to hide categories that don't have any posts. Accepts 0, 1, or their bool equivalents. Default 1. int $child_of Term ID to retrieve child terms of. See get_terms(). Default 0. array|string $exclude Array or comma/space-separated string of term ids to exclude. If $include is non-empty, $exclude is ignored. Default empty array. bool|int $echo Whether to echo or return the generated markup. Accepts 0, 1, or their bool equivalents. Default 1. bool|int $hierarchical Whether to traverse the taxonomy hierarchy. Accepts 0, 1, or their bool equivalents. Default 0. int $depth Maximum depth. Default 0. int $tab_index Tab index for the select element. Default 0 (no tabindex). string $name Value for the 'name' attribute of the select element. Default 'cat'. string $id Value for the 'id' attribute of the select element. Defaults to the value of $name. string $class Value for the 'class' attribute of the select element. Default 'postform'. int|string $selected Value of the option that should be selected. Default 0. string $value_field Term field that should be used to populate the 'value' attribute of the option elements. Accepts any valid term field: 'term_id', 'name', 'slug', 'term_group', 'term_taxonomy_id', 'taxonomy', 'description', 'parent', 'count'. Default 'term_id'. string|array $taxonomy Name of the category or categories to retrieve. Default 'category'. bool $hide_if_empty True to skip generating markup if no categories are found. Default false (create select element even if no categories are found). }
Returns
string HTML content only if 'echo' argument is 0.
Filter a taxonomy drop-down display element.
A variety of taxonomy drop-down display elements can be modified just prior to display via this filter. Filterable arguments include 'show_option_none', 'show_option_all', and various forms of the term name.
Since
1.2.0
See also
wp_dropdown_categories()
Parameters
string $element Taxonomy element to list.
This filter is documented in wp-includes/category-template.php
This filter is documented in wp-includes/category-template.php
Filter the taxonomy drop-down output.
Since
2.1.0
Parameters
string $output HTML output.
array $r Arguments used to build the drop-down.
Definition at line 357 of file category-template.php.
References $class, $id, $name, $output, __, _deprecated_argument(), apply_filters(), esc_attr(), get_query_var(), get_terms(), is_category(), selected(), walk_category_dropdown_tree(), and wp_parse_args().
Referenced by _wp_ajax_add_hierarchical_term(), WP_Press_This\categories_html(), dropdown_cats(), WP_Links_List_Table\extra_tablenav(), WP_Posts_List_Table\extra_tablenav(), post_categories_meta_box(), and WP_Widget_Categories\widget().
wp_generate_tag_cloud ($tags, $args = '')
Generates a tag cloud (heatmap) from provided data.
The text size is set by the 'smallest' and 'largest' arguments, which will use the 'unit' argument value for the CSS text size unit. The 'format' argument can be 'flat' (default), 'list', or 'array'. The flat value for the 'format' argument will separate tags with spaces. The list value for the 'format' argument will format the tags in a UL HTML list. The array value for the 'format' argument will return in PHP array type format.
The 'tag_cloud_sort' filter allows you to override the sorting. Passed to the filter: $tags array and $args array, has to return the $tags array after sorting it.
The 'orderby' argument will accept 'name' or 'count' and defaults to 'name'. The 'order' is the direction to sort, defaults to 'ASC' and can be 'DESC' or 'RAND'.
The 'number' argument is how many tags to return. By default, the limit will be to return the entire tag cloud list.
The 'topic_count_text' argument is a nooped plural from _n_noop() to generate the text for the tooltip of the tag link.
The 'topic_count_text_callback' argument is a function, which given the count of the posts with that tag returns a text for the tooltip of the tag link.
Parameters
array $tags List of tags.
string | array $args Optional, override default arguments.
Returns
string|array Tag cloud as a string or an array, depending on 'format' argument.
Filter how the items in a tag cloud are sorted.
Since
2.8.0
Parameters
array $tags Ordered array of terms.
array $args An array of tag cloud arguments.
Filter the data used to generate the tag cloud.
Since
4.3.0
Parameters
array $tags_data An array of term data for term used to generate the tag cloud.
Filter the generated output of a tag cloud.
The filter is only evaluated if a true value is passed to the $filter argument in wp_generate_tag_cloud().
Since
2.3.0
See also
wp_generate_tag_cloud()
Parameters
array | string $return String containing the generated HTML tag cloud output or an array of tag links if the 'format' argument equals 'array'.
array $tags An array of terms used in the tag cloud.
array $args An array of wp_generate_tag_cloud() arguments.
Definition at line 791 of file category-template.php.
References $class, $count, $tags, $title, _n_noop(), apply_filters(), elseif, esc_attr(), esc_html, esc_url, null, number_format_i18n(), str_replace, translate_nooped_plural(), and wp_parse_args().
Referenced by install_dashboard(), wp_ajax_get_tagcloud(), and wp_tag_cloud().
wp_list_categories ($args = '')
Display or retrieve the HTML list of categories.
Since
2.1.0
4.4.0 Introduced the hide_title_if_empty and separator arguments. The current_category argument was modified to optionally accept an array of values.
Parameters
string | array $args { Array of optional arguments.
string $show_option_all Text to display for showing all categories. Default empty string. string $show_option_none Text to display for the 'no categories' option. Default 'No categories'. string $orderby The column to use for ordering categories. Default 'ID'. string $order Which direction to order categories. Accepts 'ASC' or 'DESC'. Default 'ASC'. bool|int $show_count Whether to show how many posts are in the category. Default 0. bool|int $hide_empty Whether to hide categories that don't have any posts attached to them. Default 1. bool|int $use_desc_for_title Whether to use the category description as the title attribute. Default 1. string $feed Text to use for the feed link. Default 'Feed for all posts filed under [cat name]'. string $feed_type Feed type. Used to build feed link. See get_term_feed_link(). Default empty string (default feed). string $feed_image URL of an image to use for the feed link. Default empty string. int $child_of Term ID to retrieve child terms of. See get_terms(). Default 0. array|string $exclude Array or comma/space-separated string of term IDs to exclude. If $hierarchical is true, descendants of $exclude terms will also be excluded; see $exclude_tree. See get_terms(). Default empty string. array|string $exclude_tree Array or comma/space-separated string of term IDs to exclude, along with their descendants. See get_terms(). Default empty string. bool|int $echo True to echo markup, false to return it. Default 1. int|array $current_category ID of category, or array of IDs of categories, that should get the 'current-cat' class. Default 0. bool $hierarchical Whether to include terms that have non-empty descendants. See get_terms(). Default true. string $title_li Text to use for the list title <li> element. Pass an empty string to disable. Default 'Categories'. bool $hide_title_if_empty Whether to hide the $title_li element if there are no terms in the list. Default false (title will always be shown). int $depth Category depth. Used for tab indentation. Default 0. string $taxonomy Taxonomy name. Default 'category'. string $separator Separator between links. Default '
'. }
Returns
false|string HTML content only if 'echo' argument is 0.
Filter the HTML output of a taxonomy list.
Since
2.1.0
Parameters
string $output HTML output.
array $args An array of taxonomy-listing arguments.
Definition at line 527 of file category-template.php.
References $output, __, apply_filters(), esc_attr(), esc_url, get_categories(), get_option(), get_permalink(), get_post_type_archive_link(), get_post_type_object(), get_queried_object(), get_queried_object_id(), get_taxonomy(), home_url(), is_category(), is_tag(), is_tax(), taxonomy_exists(), walk_category_tree(), wp_parse_args(), and wp_parse_id_list().
Referenced by WP_Widget_Categories\widget(), and wp_list_cats().
wp_tag_cloud ($args = '')
Display tag cloud.
The text size is set by the 'smallest' and 'largest' arguments, which will use the 'unit' argument value for the CSS text size unit. The 'format' argument can be 'flat' (default), 'list', or 'array'. The flat value for the 'format' argument will separate tags with spaces. The list value for the 'format' argument will format the tags in a UL HTML list. The array value for the 'format' argument will return in PHP array type format.
The 'orderby' argument will accept 'name' or 'count' and defaults to 'name'. The 'order' is the direction to sort, defaults to 'ASC' and can be 'DESC'.
The 'number' argument is how many tags to return. By default, the limit will be to return the top 45 tags in the tag cloud list.
The 'topic_count_text' argument is a nooped plural from _n_noop() to generate the text for the tooltip of the tag link.
The 'topic_count_text_callback' argument is a function, which given the count of the posts with that tag returns a text for the tooltip of the tag link.
The 'post_type' argument is used only when 'link' is set to 'edit'. It determines the post_type passed to edit.php for the popular tags edit links.
The 'exclude' and 'include' arguments are used for the get_tags() function. Only one should be used, because only one will be used and the other ignored, if they are both set.
Since
2.3.0
Parameters
array | string | null $args Optional. Override default arguments.
Returns
void|array Generated tag cloud, only if no failures and 'array' is set for the 'format' argument. Otherwise, this function outputs the tag cloud.
Filter the tag cloud output.
Since
2.3.0
Parameters
string $return HTML output of the tag cloud.
array $args An array of tag cloud arguments.
Definition at line 704 of file category-template.php.
References $link, $tags, apply_filters(), get_edit_term_link(), get_term_link(), get_terms(), is_wp_error(), wp_generate_tag_cloud(), and wp_parse_args().
Referenced by WP_Widget_Tag_Cloud\widget().