GravityView: checkbox.php File Reference
checkbox.php File Reference
Namespaces
GravityView
GPL2+
Variables
$field_value = gravityview_get_field_value($entry, $field_id, $display_value)
$gravityview_view = GravityView_View::getInstance()
$is_single_input = floor($field_id) !== floatval($field_id)
$output = ''
if(! $is_single_input) else
switch ($display_type)
Variable Documentation
$field_value
$field_value = gravityview_get_field_value($entry, $field_id, $display_value)
Definition at line 24 of file checkbox.php.
Referenced by GravityView_Field_List\column_value(), GravityView_Field_Post_Custom_Field\edit_entry_field_value(), GravityView_Edit_Entry_Render\fix_multiselect_value_serialization(), GravityView_Plugin_Hooks_Gravity_Forms_Survey\fix_survey_field_value(), GravityView_Field_FileUpload\get_field_input(), GVCommon\get_field_label(), GravityView_Edit_Entry_Render\get_field_value(), GravityView_Field_FileUpload\get_files_array(), gravityview_get_field_label(), GravityView_GFFormsModel\is_value_match(), GravityView_Edit_Entry_Render\unselect_default_values(), GravityView_Edit_Entry_Render\unset_hidden_field_values(), and GravityView_Edit_Entry_Render\verify_user_can_edit_post().
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Definition at line 10 of file checkbox.php.
$is_single_input
$is_single_input = floor($field_id) !== floatval($field_id)
Definition at line 14 of file checkbox.php.
$output
$output = ''
Definition at line 16 of file checkbox.php.
else
if (! $is_single_input) else
Initial value:
{
    $display_type = \GV\Utils::get( $field_settings, 'choice_display' )
Definition at line 20 of file checkbox.php.
switch
switch($display_type)
Definition at line 26 of file checkbox.php.