GravityView: WP_Object_Cache Class Reference
WP_Object_Cache Class Reference
Public Member Functions
__construct ()
Sets up object properties; PHP 5 style constructor.
__destruct ()
Saves the object cache before object is completely destroyed.
__get ($name)
Makes private properties readable for backwards compatibility.
__isset ($name)
Makes private properties checkable for backwards compatibility.
__set ($name, $value)
Makes private properties settable for backwards compatibility.
__unset ($name)
Makes private properties un-settable for backwards compatibility.
add ($key, $data, $group= 'default', $expire=0)
Adds data to the cache if it doesn't already exist.
add_global_groups ($groups)
Sets the list of global cache groups.
decr ($key, $offset=1, $group= 'default')
Decrements numeric cache item's value.
delete ($key, $group= 'default', $deprecated=false)
Removes the contents of the cache key in the group.
flush ()
Clears the object cache of all data.
get ($key, $group= 'default', $force=false, &$found=null)
Retrieves the cache contents, if it exists.
incr ($key, $offset=1, $group= 'default')
Increments numeric cache item's value.
replace ($key, $data, $group= 'default', $expire=0)
Replaces the contents in the cache, if contents already exist.
reset ()
Resets cache keys.
set ($key, $data, $group= 'default', $expire=0)
Sets the data contents into the cache.
stats ()
Echoes the stats of the caching.
switch_to_blog ($blog_id)
Switches the interal blog ID.
Data Fields
$cache_misses = 0
Protected Member Functions
_exists ($key, $group)
Serves as a utility function to determine whether a key exists in the cache.
Protected Attributes
$global_groups = array()
Private Attributes
$blog_prefix
$cache = array()
$cache_hits = 0
$multisite
Detailed Description
Definition at line 290 of file cache.php.
Constructor & Destructor Documentation
__construct ()
Sets up object properties; PHP 5 style constructor.
Since
2.0.8
int $blog_id Global blog ID.
Definition at line 735 of file cache.php.
References $blog_id, and is_multisite().
__destruct ()
Saves the object cache before object is completely destroyed.
Called upon object destruction, which should be when PHP ends.
Since
2.0.8
Returns
true Always returns true.
Definition at line 758 of file cache.php.
Member Function Documentation
__get ($name)
Makes private properties readable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to get.
Returns
mixed Property.
Definition at line 355 of file cache.php.
__isset ($name)
Makes private properties checkable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to check if set.
Returns
bool Whether the property is set.
Definition at line 382 of file cache.php.
References $name.
__set ($name, $value)
Makes private properties settable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to set.
mixed $value Property value.
Returns
mixed Newly-set property.
Definition at line 369 of file cache.php.
References $name, and $value.
__unset ($name)
Makes private properties un-settable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to unset.
Definition at line 394 of file cache.php.
References $name.
_exists ($key, $group) protected
Serves as a utility function to determine whether a key exists in the cache.
Since
3.4.0 protected
Parameters
int | string $key Cache key to check for existence.
string $group Cache group for the key existence check.
Returns
bool Whether the key exists in the cache for the given group.
Definition at line 724 of file cache.php.
Referenced by add(), decr(), delete(), get(), incr(), and replace().
add ($key, $data, $group = 'default', $expire = 0)
Adds data to the cache if it doesn't already exist.
Since
2.0.0 public
WP_Object_Cache::_exists() Checks to see if the cache already has data. WP_Object_Cache::set() Sets the data after the checking the cache contents existence.
Parameters
int | string $key What to call the contents in the cache.
mixed $data The contents to store in the cache.
string $group Optional. Where to group the cache contents. Default 'default'.
int $expire Optional. When to expire the cache contents. Default 0 (no expiration).
Returns
bool False if cache key and group already exist, true on success
Definition at line 414 of file cache.php.
References $id, _exists(), set(), and wp_suspend_cache_addition().
add_global_groups ($groups)
Sets the list of global cache groups.
Since
3.0.0 public
Parameters
array $groups List of groups that are global.
Definition at line 439 of file cache.php.
decr ($key, $offset = 1, $group = 'default')
Decrements numeric cache item's value.
Since
3.3.0 public
Parameters
int | string $key The cache key to decrement.
int $offset Optional. The amount by which to decrement the item's value. Default 1.
string $group Optional. The group the key is in. Default 'default'.
Returns
false|int False on failure, the item's new value on success.
Definition at line 457 of file cache.php.
References _exists().
delete ($key, $group = 'default', $deprecated = false)
Removes the contents of the cache key in the group.
If the cache key does not exist in the group, then nothing will happen.
Since
2.0.0 public
Parameters
int | string $key What the contents in the cache are called.
string $group Optional. Where the cache contents are grouped. Default 'default'.
bool $deprecated Optional. Unused. Default false.
Returns
bool False if the contents weren't deleted and true on success.
Definition at line 493 of file cache.php.
References _exists().
flush ()
Clears the object cache of all data.
Since
2.0.0 public
Returns
true Always returns true.
Definition at line 515 of file cache.php.
get ($key, $group = 'default', $force = false, & $found = null)
Retrieves the cache contents, if it exists.
The contents will be first attempted to be retrieved by searching by the key in the cache group. If the cache is hit (success) then the contents are returned.
On failure, the number of cache misses will be incremented.
Since
2.0.0 public
Parameters
int | string $key What the contents in the cache are called.
string $group Optional. Where the cache contents are grouped. Default 'default'.
string $force Optional. Unused. Whether to force a refetch rather than relying on the local cache. Default false.
bool $found Optional. Whether the key was found in the cache. Disambiguates a return of false, a storable value. Passed by reference. Default null.
Returns
false|mixed False on failure to retrieve contents or the cache contents on success.
Definition at line 541 of file cache.php.
References _exists().
incr ($key, $offset = 1, $group = 'default')
Increments numeric cache item's value.
Since
3.3.0 public
Parameters
int | string $key The cache key to increment
int $offset Optional. The amount by which to increment the item's value. Default 1.
string $group Optional. The group the key is in. Default 'default'.
Returns
false|int False on failure, the item's new value on success.
Definition at line 573 of file cache.php.
References _exists().
replace ($key, $data, $group = 'default', $expire = 0)
Replaces the contents in the cache, if contents already exist.
Since
2.0.0 public
See also
WP_Object_Cache::set()
Parameters
int | string $key What to call the contents in the cache.
mixed $data The contents to store in the cache.
string $group Optional. Where to group the cache contents. Default 'default'.
int $expire Optional. When to expire the cache contents. Default 0 (no expiration).
Returns
bool False if not exists, true if contents were replaced.
Definition at line 610 of file cache.php.
References $id, _exists(), and set().
reset ()
Resets cache keys.
Since
3.0.0 public
Definition at line 633 of file cache.php.
References _deprecated_function().
set ($key, $data, $group = 'default', $expire = 0)
Sets the data contents into the cache.
The cache contents is grouped by the $group parameter followed by the $key. This allows for duplicate ids in unique groups. Therefore, naming of the group should be used with care and should follow normal function naming guidelines outside of core WordPress usage.
The $expire parameter is not used, because the cache will automatically expire for each time a page is accessed and PHP finishes. The method is more for cache plugins which use files.
Since
2.0.0 public
Parameters
int | string $key What to call the contents in the cache.
mixed $data The contents to store in the cache.
string $group Optional. Where to group the cache contents. Default 'default'.
int $expire Not Used.
Returns
true Always returns true.
Definition at line 664 of file cache.php.
Referenced by add(), and replace().
stats ()
Echoes the stats of the caching.
Gives the cache hits, and cache misses. Also prints every cached group, key and the data.
Since
2.0.0 public
Definition at line 687 of file cache.php.
References $cache.
switch_to_blog ($blog_id)
Switches the interal blog ID.
This changes the blog ID used to create keys in blog specific groups.
Since
3.5.0 public
Parameters
int $blog_id Blog ID.
Definition at line 709 of file cache.php.
References $blog_id.
Field Documentation
$blog_prefix private
Definition at line 335 of file cache.php.
$cache = array() private
Definition at line 299 of file cache.php.
Referenced by stats().
$cache_hits = 0 private
Definition at line 308 of file cache.php.
$cache_misses = 0
Definition at line 317 of file cache.php.
$global_groups = array() protected
Definition at line 326 of file cache.php.
$multisite private
Definition at line 344 of file cache.php.
The documentation for this class was generated from the following file:
cache.php