GravityView: RGXML Class Reference
RGXML Class Reference
Public Member Functions
__construct ($options=array())
serialize ($parent_node_name, $data, $path="")
unserialize ($xml_string)
Private Member Functions
get_children ($values, $parent_index)
has_identical_tags ($nodes)
indent ($path)
is_assoc ($array)
is_attribute ($path)
to_singular ($str)
unserialize_node ($values, $index)
xml_attribute ($value)
xml_cdata ($value)
xml_content ($value)
xml_is_cdata ($node_name)
xml_value ($node_name, $value)
Private Attributes
$options = array()
Detailed Description
Definition at line 6 of file xml.php.
Constructor & Destructor Documentation
__construct ($options = array())
Definition at line 9 of file xml.php.
References $options.
Member Function Documentation
get_children ($values, $parent_index) private
Definition at line 156 of file xml.php.
References $count, and $i.
Referenced by unserialize_node().
has_identical_tags ($nodes) private
Definition at line 174 of file xml.php.
Referenced by unserialize_node().
indent ($path) private
Definition at line 13 of file xml.php.
References $path.
Referenced by serialize().
is_assoc ($array) private
Definition at line 219 of file xml.php.
Referenced by serialize().
is_attribute ($path) private
Definition at line 185 of file xml.php.
References $option, and $path.
Referenced by serialize().
serialize ($parent_node_name, $data, $path = "")
Definition at line 21 of file xml.php.
References $option, $path, $value, indent(), is_assoc(), is_attribute(), to_singular(), xml_attribute(), and xml_value().
to_singular ($str) private
Definition at line 223 of file xml.php.
Referenced by serialize().
unserialize ($xml_string)
Definition at line 89 of file xml.php.
References $errors, $xml_parser, and unserialize_node().
unserialize_node ($values, $index) private
Definition at line 111 of file xml.php.
References get_children(), and has_identical_tags().
Referenced by unserialize().
xml_attribute ($value) private
Definition at line 203 of file xml.php.
References $value, and esc_attr().
Referenced by serialize().
xml_cdata ($value) private
Definition at line 207 of file xml.php.
References $value.
Referenced by xml_value().
xml_content ($value) private
Definition at line 211 of file xml.php.
References $value.
Referenced by xml_value().
xml_is_cdata ($node_name) private
Definition at line 215 of file xml.php.
Referenced by xml_value().
xml_value ($node_name, $value) private
Definition at line 191 of file xml.php.
References $value, xml_cdata(), xml_content(), and xml_is_cdata().
Referenced by serialize().
Field Documentation
$options = array() private
Definition at line 7 of file xml.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
xml.php