GravityView: WP_REST_Server Class Reference
WP_REST_Server Class Reference
Core class used to implement the WordPress REST API server.
Public Member Functions
__construct ()
Instantiates the REST server.
__construct ()
Instantiates the REST server.
check_authentication ()
Checks the authentication headers if supplied.
check_authentication ()
Checks the authentication headers if supplied.
dispatch ($request)
Matches the request to a callback and call it.
dispatch ($request)
Matches the request to a callback and call it.
envelope_response ($response, $embed)
Wraps the response in an envelope.
envelope_response ($response, $embed)
Wraps the response in an envelope.
get_data_for_route ($route, $callbacks, $context= 'view')
Retrieves publicly-visible data for the route.
get_data_for_route ($route, $callbacks, $context= 'view')
Retrieves publicly-visible data for the route.
get_data_for_routes ($routes, $context= 'view')
Retrieves the publicly-visible data for routes.
get_data_for_routes ($routes, $context= 'view')
Retrieves the publicly-visible data for routes.
get_headers ($server)
Extracts headers from a PHP-style $_SERVER array.
get_headers ($server)
Extracts headers from a PHP-style $_SERVER array.
get_index ($request)
Retrieves the site index.
get_index ($request)
Retrieves the site index.
get_namespace_index ($request)
Retrieves the index for a namespace.
get_namespace_index ($request)
Retrieves the index for a namespace.
get_namespaces ()
Retrieves namespaces registered on the server.
get_namespaces ()
Retrieves namespaces registered on the server.
get_route_options ($route)
Retrieves specified options for a route.
get_route_options ($route)
Retrieves specified options for a route.
get_routes ()
Retrieves the route map.
get_routes ()
Retrieves the route map.
register_route ($namespace, $route, $route_args, $override=false)
Registers a route to the server.
register_route ($namespace, $route, $route_args, $override=false)
Registers a route to the server.
response_to_data ($response, $embed)
Converts a response to data to send.
response_to_data ($response, $embed)
Converts a response to data to send.
send_header ($key, $value)
Sends an HTTP header.
send_header ($key, $value)
Sends an HTTP header.
send_headers ($headers)
Sends multiple HTTP headers.
send_headers ($headers)
Sends multiple HTTP headers.
serve_request ($path=null)
Handles serving an API request.
serve_request ($path=null)
Handles serving an API request.
Static Public Member Functions
static get_raw_data ()
Retrieves the raw request entity (body).
static get_raw_data ()
Retrieves the raw request entity (body).
static get_response_links ($response)
Retrieves links from a response.
static get_response_links ($response)
Retrieves links from a response.
Data Fields
const ALLMETHODS = 'GET, POST, PUT, PATCH, DELETE'
const CREATABLE = 'POST'
const DELETABLE = 'DELETE'
const EDITABLE = 'POST, PUT, PATCH'
const READABLE = 'GET'
Protected Member Functions
embed_links ($data)
Embeds the links from the data into the request.
embed_links ($data)
Embeds the links from the data into the request.
error_to_response ($error)
Converts an error to a response object.
error_to_response ($error)
Converts an error to a response object.
get_json_last_error ()
Returns if an error occurred during most recent JSON encode/decode.
get_json_last_error ()
Returns if an error occurred during most recent JSON encode/decode.
json_error ($code, $message, $status=null)
Retrieves an appropriate error representation in JSON.
json_error ($code, $message, $status=null)
Retrieves an appropriate error representation in JSON.
set_status ($code)
Sends an HTTP status code.
set_status ($code)
Sends an HTTP status code.
Protected Attributes
$endpoints = array()
$namespaces = array()
$route_options = array()
Detailed Description
Core class used to implement the WordPress REST API server.
Since
4.4.0
Definition at line 15 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
Constructor & Destructor Documentation
__construct ()
Instantiates the REST server.
Since
4.4.0 public
Definition at line 90 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
__construct ()
Instantiates the REST server.
Since
4.4.0 public
Definition at line 90 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
Member Function Documentation
check_authentication ()
Checks the authentication headers if supplied.
Since
4.4.0 public
Returns
WP_Error|null WP_Error indicates unsuccessful login, null indicates successful or no authentication provided
Pass an authentication error to the API
This is used to pass a WP_Error from an authentication method back to the API.
Authentication methods should check first if they're being used, as multiple authentication methods can be enabled on a site (cookies, HTTP basic auth, OAuth). If the authentication method hooked in is not actually being attempted, null should be returned to indicate another authentication method should check instead. Similarly, callbacks should ensure the value is null before checking for errors.
A WP_Error instance can be returned if an error occurs, and this should match the format used by API methods internally (that is, the status data should be used). A callback can return true to indicate that the authentication method was used, and it succeeded.
Since
4.4.0
Parameters
WP_Error|null|bool WP_Error if authentication error, null if authentication method wasn't used, true if authentication succeeded.
Definition at line 115 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References apply_filters(), and null.
Referenced by serve_request().
check_authentication ()
Checks the authentication headers if supplied.
Since
4.4.0 public
Returns
WP_Error|null WP_Error indicates unsuccessful login, null indicates successful or no authentication provided
Pass an authentication error to the API
This is used to pass a WP_Error from an authentication method back to the API.
Authentication methods should check first if they're being used, as multiple authentication methods can be enabled on a site (cookies, HTTP basic auth, OAuth). If the authentication method hooked in is not actually being attempted, null should be returned to indicate another authentication method should check instead. Similarly, callbacks should ensure the value is null before checking for errors.
A WP_Error instance can be returned if an error occurs, and this should match the format used by API methods internally (that is, the status data should be used). A callback can return true to indicate that the authentication method was used, and it succeeded.
Since
4.4.0
Parameters
WP_Error|null|bool WP_Error if authentication error, null if authentication method wasn't used, true if authentication succeeded.
Definition at line 115 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References apply_filters(), and null.
dispatch ($request)
Matches the request to a callback and call it.
Since
4.4.0 public
Parameters
WP_REST_Request $request Request to attempt dispatching.
Returns
WP_REST_Response Response returned by the callback.
Filter the pre-calculated result of a REST dispatch request.
Allow hijacking the request before dispatching by returning a non-empty. The returned value will be used to serve the request instead.
Since
4.4.0
Parameters
mixed $result Response to replace the requested version with. Can be anything a normal endpoint can return, or null to not hijack the request.
WP_REST_Server $this Server instance.
WP_REST_Request $request Request used to generate the response.
Filter the REST dispatch request result.
Allow plugins to override dispatching the request.
Since
4.4.0
Parameters
bool $dispatch_result Dispatch result, will be used if not empty.
WP_REST_Request $request Request used to generate the response.
Definition at line 763 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $options, $path, __, apply_filters(), error_to_response(), get_routes(), is_wp_error(), null, and rest_ensure_response().
dispatch ($request)
Matches the request to a callback and call it.
Since
4.4.0 public
Parameters
WP_REST_Request $request Request to attempt dispatching.
Returns
WP_REST_Response Response returned by the callback.
Filter the pre-calculated result of a REST dispatch request.
Allow hijacking the request before dispatching by returning a non-empty. The returned value will be used to serve the request instead.
Since
4.4.0
Parameters
mixed $result Response to replace the requested version with. Can be anything a normal endpoint can return, or null to not hijack the request.
WP_REST_Server $this Server instance.
WP_REST_Request $request Request used to generate the response.
Filter the REST dispatch request result.
Allow plugins to override dispatching the request.
Since
4.4.0
Parameters
bool $dispatch_result Dispatch result, will be used if not empty.
WP_REST_Request $request Request used to generate the response.
Definition at line 763 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $options, $path, __, apply_filters(), error_to_response(), get_routes(), is_wp_error(), null, and rest_ensure_response().
Referenced by embed_links(), and serve_request().
embed_links ($data) protected
Embeds the links from the data into the request.
Since
4.4.0 protected
Parameters
array $data Data from the request.
Returns
array { Data with sub-requests embedded.
array [$_links] Links. array [$_embedded] Embeddeds. }
Definition at line 490 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References dispatch(), response_to_data(), rest_url(), stripslashes_deep(), and untrailingslashit().
Referenced by response_to_data().
embed_links ($data) protected
Embeds the links from the data into the request.
Since
4.4.0 protected
Parameters
array $data Data from the request.
Returns
array { Data with sub-requests embedded.
array [$_links] Links. array [$_embedded] Embeddeds. }
Definition at line 490 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References dispatch(), response_to_data(), rest_url(), stripslashes_deep(), and untrailingslashit().
envelope_response ($response, $embed)
Wraps the response in an envelope.
The enveloping technique is used to work around browser/client compatibility issues. Essentially, it converts the full HTTP response to data instead.
Since
4.4.0 public
Parameters
WP_REST_Response $response Response object.
bool $embed Whether links should be embedded.
Returns
WP_REST_Response New response with wrapped data
Filter the enveloped form of a response.
Since
4.4.0
Parameters
array $envelope Envelope data.
WP_REST_Response $response Original response data.
Definition at line 575 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References apply_filters(), response_to_data(), and rest_ensure_response().
Referenced by serve_request().
envelope_response ($response, $embed)
Wraps the response in an envelope.
The enveloping technique is used to work around browser/client compatibility issues. Essentially, it converts the full HTTP response to data instead.
Since
4.4.0 public
Parameters
WP_REST_Response $response Response object.
bool $embed Whether links should be embedded.
Returns
WP_REST_Response New response with wrapped data
Filter the enveloped form of a response.
Since
4.4.0
Parameters
array $envelope Envelope data.
WP_REST_Response $response Original response data.
Definition at line 575 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References apply_filters(), response_to_data(), and rest_ensure_response().
error_to_response ($error) protected
Converts an error to a response object.
This iterates over all error codes and messages to change it into a flat array. This enables simpler client behaviour, as it is represented as a list in JSON rather than an object/map.
Since
4.4.0 protected
Parameters
WP_Error $error WP_Error instance.
Returns
WP_REST_Response List of associative arrays with code and message keys.
Definition at line 156 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $errors, $message, and $messages.
Referenced by dispatch(), and serve_request().
error_to_response ($error) protected
Converts an error to a response object.
This iterates over all error codes and messages to change it into a flat array. This enables simpler client behaviour, as it is represented as a list in JSON rather than an object/map.
Since
4.4.0 protected
Parameters
WP_Error $error WP_Error instance.
Returns
WP_REST_Response List of associative arrays with code and message keys.
Definition at line 156 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $errors, $message, and $messages.
get_data_for_route ($route, $callbacks, $context = 'view')
Retrieves publicly-visible data for the route.
Since
4.4.0 public
Parameters
string $route Route to get data for.
array $callbacks Callbacks to convert to data.
string $context Optional. Context for the data. Accepts 'view' or 'help'. Default 'view'.
Returns
array|null Data for the route, or null if no publicly-visible data.
Definition at line 1050 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $options, null, and rest_url().
Referenced by get_data_for_routes().
get_data_for_route ($route, $callbacks, $context = 'view')
Retrieves publicly-visible data for the route.
Since
4.4.0 public
Parameters
string $route Route to get data for.
array $callbacks Callbacks to convert to data.
string $context Optional. Context for the data. Accepts 'view' or 'help'. Default 'view'.
Returns
array|null Data for the route, or null if no publicly-visible data.
Definition at line 1050 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $options, null, and rest_url().
get_data_for_routes ($routes, $context = 'view')
Retrieves the publicly-visible data for routes.
Since
4.4.0 public
Parameters
array $routes Routes to get data for.
string $context Optional. Context for data. Accepts 'view' or 'help'. Default 'view'.
Returns
array Route data to expose in indexes.
Filter the REST endpoint data.
Since
4.4.0
Parameters
WP_REST_Request $request Request data. The namespace is passed as the 'namespace' parameter.
Filter the publicly-visible data for routes.
This data is exposed on indexes and can be used by clients or developers to investigate the site and find out how to use it. It acts as a form of self-documentation.
Since
4.4.0
Parameters
array $available Map of route to route data.
array $routes Internal route data as an associative array.
Definition at line 1004 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References apply_filters(), and get_data_for_route().
Referenced by get_index(), and get_namespace_index().
get_data_for_routes ($routes, $context = 'view')
Retrieves the publicly-visible data for routes.
Since
4.4.0 public
Parameters
array $routes Routes to get data for.
string $context Optional. Context for data. Accepts 'view' or 'help'. Default 'view'.
Returns
array Route data to expose in indexes.
Filter the REST endpoint data.
Since
4.4.0
Parameters
WP_REST_Request $request Request data. The namespace is passed as the 'namespace' parameter.
Filter the publicly-visible data for routes.
This data is exposed on indexes and can be used by clients or developers to investigate the site and find out how to use it. It acts as a form of self-documentation.
Since
4.4.0
Parameters
array $available Map of route to route data.
array $routes Internal route data as an associative array.
Definition at line 1004 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References apply_filters(), and get_data_for_route().
get_headers ($server)
Extracts headers from a PHP-style $_SERVER array.
Since
4.4.0 public
Parameters
array $server Associative array similar to $_SERVER.
Returns
array Headers extracted from the input.
Definition at line 1199 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $value, and elseif.
Referenced by serve_request().
get_headers ($server)
Extracts headers from a PHP-style $_SERVER array.
Since
4.4.0 public
Parameters
array $server Associative array similar to $_SERVER.
Returns
array Headers extracted from the input.
Definition at line 1199 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $value, and elseif.
get_index ($request)
Retrieves the site index.
This endpoint describes the capabilities of the site.
Since
4.4.0 public
Parameters
array $request { Request.
string $context Context. }
Returns
array Index entity
Filter the API root index data.
This contains the data describing the API. This includes information about supported authentication schemes, supported namespaces, routes available on the API, and a small amount of data about the site.
Since
4.4.0
Parameters
WP_REST_Response $response Response data.
Definition at line 922 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References apply_filters(), get_data_for_routes(), get_option(), and get_routes().
get_index ($request)
Retrieves the site index.
This endpoint describes the capabilities of the site.
Since
4.4.0 public
Parameters
array $request { Request.
string $context Context. }
Returns
array Index entity
Filter the API root index data.
This contains the data describing the API. This includes information about supported authentication schemes, supported namespaces, routes available on the API, and a small amount of data about the site.
Since
4.4.0
Parameters
WP_REST_Response $response Response data.
Definition at line 922 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References apply_filters(), get_data_for_routes(), get_option(), and get_routes().
get_json_last_error () protected
Returns if an error occurred during most recent JSON encode/decode.
Strings to be translated will be in format like "Encoding error: Maximum stack depth exceeded".
Since
4.4.0 protected
Returns
bool|string Boolean false or string error message.
Definition at line 892 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
get_json_last_error () protected
Returns if an error occurred during most recent JSON encode/decode.
Strings to be translated will be in format like "Encoding error: Maximum stack depth exceeded".
Since
4.4.0 protected
Returns
bool|string Boolean false or string error message.
Definition at line 892 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
Referenced by serve_request().
get_namespace_index ($request)
Retrieves the index for a namespace.
Since
4.4.0 public
Parameters
WP_REST_Request $request REST request instance.
Returns
WP_REST_Response|WP_Error WP_REST_Response instance if the index was found, WP_Error if the namespace isn't set.
Filter the namespace index data.
This typically is just the route data for the namespace, but you can add any data you'd like here.
Since
4.4.0
Parameters
WP_REST_Response $response Response data.
WP_REST_Request $request Request data. The namespace is passed as the 'namespace' parameter.
Definition at line 961 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $endpoints, __, apply_filters(), get_data_for_routes(), get_routes(), rest_ensure_response(), and rest_url().
get_namespace_index ($request)
Retrieves the index for a namespace.
Since
4.4.0 public
Parameters
WP_REST_Request $request REST request instance.
Returns
WP_REST_Response|WP_Error WP_REST_Response instance if the index was found, WP_Error if the namespace isn't set.
Filter the namespace index data.
This typically is just the route data for the namespace, but you can add any data you'd like here.
Since
4.4.0
Parameters
WP_REST_Response $response Response data.
WP_REST_Request $request Request data. The namespace is passed as the 'namespace' parameter.
Definition at line 961 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $endpoints, __, apply_filters(), get_data_for_routes(), get_routes(), rest_ensure_response(), and rest_url().
get_namespaces ()
Retrieves namespaces registered on the server.
Since
4.4.0 public
Returns
array List of registered namespaces.
Definition at line 733 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
get_namespaces ()
Retrieves namespaces registered on the server.
Since
4.4.0 public
Returns
array List of registered namespaces.
Definition at line 733 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
static get_raw_data () static
Retrieves the raw request entity (body).
Since
4.4.0 public
string $HTTP_RAW_POST_DATA Raw post data.
Returns
string Raw request data.
Definition at line 1176 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
static get_raw_data () static
Retrieves the raw request entity (body).
Since
4.4.0 public
string $HTTP_RAW_POST_DATA Raw post data.
Returns
string Raw request data.
Definition at line 1176 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
Referenced by serve_request().
static get_response_links ($response) static
Retrieves links from a response.
Extracts the links from a response into a structured hash, suitable for direct output.
Since
4.4.0 public
Parameters
WP_REST_Response $response Response to extract links from.
Returns
array Map of link relation to list of link hashes.
Definition at line 454 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $attributes.
Referenced by response_to_data().
static get_response_links ($response) static
Retrieves links from a response.
Extracts the links from a response into a structured hash, suitable for direct output.
Since
4.4.0 public
Parameters
WP_REST_Response $response Response to extract links from.
Returns
array Map of link relation to list of link hashes.
Definition at line 454 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $attributes.
get_route_options ($route)
Retrieves specified options for a route.
Since
4.4.0 public
Parameters
string $route Route pattern to fetch options for.
Returns
array|null Data as an associative array if found, or null if not found.
Definition at line 746 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References null.
get_route_options ($route)
Retrieves specified options for a route.
Since
4.4.0 public
Parameters
string $route Route pattern to fetch options for.
Returns
array|null Data as an associative array if found, or null if not found.
Definition at line 746 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References null.
get_routes ()
Retrieves the route map.
The route map is an associative array with path regexes as the keys. The value is an indexed array with the callback function/method as the first item, and a bitmask of HTTP methods as the second item (see the class constants).
Each route can be mapped to more than one callback by using an array of the indexed arrays. This allows mapping e.g. GET requests to one callback and POST requests to another.
Note that the path regexes (array keys) must have @ escaped, as this is used as the delimiter with preg_match()
Since
4.4.0 public
Returns
array `'/path/regex' => array($callback, $bitmask)or '/path/regex' => array(array($callback, $bitmask), ...)`.
Filter the array of available endpoints.
Since
4.4.0
Parameters
array $endpoints The available endpoints. An array of matching regex patterns, each mapped to an array of callbacks for the endpoint. These take the format `'/path/regex' => array($callback, $bitmask)or '/path/regex' => array(array($callback, $bitmask).
Definition at line 660 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $endpoints, apply_filters(), and wp_parse_args().
get_routes ()
Retrieves the route map.
The route map is an associative array with path regexes as the keys. The value is an indexed array with the callback function/method as the first item, and a bitmask of HTTP methods as the second item (see the class constants).
Each route can be mapped to more than one callback by using an array of the indexed arrays. This allows mapping e.g. GET requests to one callback and POST requests to another.
Note that the path regexes (array keys) must have @ escaped, as this is used as the delimiter with preg_match()
Since
4.4.0 public
Returns
array `'/path/regex' => array($callback, $bitmask)or '/path/regex' => array(array($callback, $bitmask), ...)`.
Filter the array of available endpoints.
Since
4.4.0
Parameters
array $endpoints The available endpoints. An array of matching regex patterns, each mapped to an array of callbacks for the endpoint. These take the format `'/path/regex' => array($callback, $bitmask)or '/path/regex' => array(array($callback, $bitmask).
Definition at line 660 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $endpoints, apply_filters(), and wp_parse_args().
Referenced by dispatch(), get_index(), and get_namespace_index().
json_error ($code, $message, $status = null) protected
Retrieves an appropriate error representation in JSON.
Note: This should only be used in WP_REST_Server::serve_request(), as it cannot handle WP_Error internally. All callbacks and other internal methods should instead return a WP_Error with the data set to an array that includes a 'status' key, with the value being the HTTP status to send.
Since
4.4.0 protected
Parameters
string $code WP_Error-style code.
string $message Human-readable message.
int $status Optional. HTTP status code to send. Default null.
Returns
string JSON representation of the error
Definition at line 201 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References set_status(), and wp_json_encode().
Referenced by serve_request().
json_error ($code, $message, $status = null) protected
Retrieves an appropriate error representation in JSON.
Note: This should only be used in WP_REST_Server::serve_request(), as it cannot handle WP_Error internally. All callbacks and other internal methods should instead return a WP_Error with the data set to an array that includes a 'status' key, with the value being the HTTP status to send.
Since
4.4.0 protected
Parameters
string $code WP_Error-style code.
string $message Human-readable message.
int $status Optional. HTTP status code to send. Default null.
Returns
string JSON representation of the error
Definition at line 201 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References set_status(), and wp_json_encode().
register_route ($namespace, $route, $route_args, $override = false)
Registers a route to the server.
Since
4.4.0 public
Parameters
string $namespace Namespace.
string $route The REST route.
array $route_args Route arguments.
bool $override Optional. Whether the route should be overriden if it already exists. Default false.
Definition at line 608 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
Referenced by register_route().
register_route ($namespace, $route, $route_args, $override = false)
Registers a route to the server.
Since
4.4.0 public
Parameters
string $namespace Namespace.
string $route The REST route.
array $route_args Route arguments.
bool $override Optional. Whether the route should be overriden if it already exists. Default false.
Definition at line 608 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References register_route().
response_to_data ($response, $embed)
Converts a response to data to send.
Since
4.4.0 public
Parameters
WP_REST_Response $response Response object.
bool $embed Whether links should be embedded.
Returns
array { Data with sub-requests embedded.
array [$_links] Links. array [$_embedded] Embeddeds. }
Definition at line 421 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References embed_links(), get_response_links(), and wp_is_numeric_array().
response_to_data ($response, $embed)
Converts a response to data to send.
Since
4.4.0 public
Parameters
WP_REST_Response $response Response object.
bool $embed Whether links should be embedded.
Returns
array { Data with sub-requests embedded.
array [$_links] Links. array [$_embedded] Embeddeds. }
Definition at line 421 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References embed_links(), get_response_links(), and wp_is_numeric_array().
Referenced by embed_links(), envelope_response(), and serve_request().
send_header ($key, $value)
Sends an HTTP header.
Since
4.4.0 public
Parameters
string $key Header key.
string $value Header value.
Definition at line 1140 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $value.
Referenced by send_headers(), and serve_request().
send_header ($key, $value)
Sends an HTTP header.
Since
4.4.0 public
Parameters
string $key Header key.
string $value Header value.
Definition at line 1140 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $value.
send_headers ($headers)
Sends multiple HTTP headers.
Since
4.4.0 public
Parameters
array $headers Map of header name to header value.
Definition at line 1160 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $value, and send_header().
Referenced by serve_request().
send_headers ($headers)
Sends multiple HTTP headers.
Since
4.4.0 public
Parameters
array $headers Map of header name to header value.
Definition at line 1160 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $value, and send_header().
serve_request ($path = null)
Handles serving an API request.
Matches the current server URI to a route and runs the first matching callback then outputs a JSON representation of the returned value.
Since
4.4.0 public
See also
WP_REST_Server::dispatch()
Parameters
string $path Optional. The request route. If not set, `$_SERVER['PATH_INFO']` will be used. Default null.
Returns
false|null Null if not served and a HEAD request, false otherwise.
Send nocache headers on authenticated requests.
Since
4.4.0
Parameters
bool $rest_send_nocache_headers Whether to send no-cache headers.
Filter whether the REST API is enabled.
Since
4.4.0
Parameters
bool $rest_enabled Whether the REST API is enabled. Default true.
Filter whether jsonp is enabled.
Since
4.4.0
Parameters
bool $jsonp_enabled Whether jsonp is enabled. Default true.
Filter the API response.
Allows modification of the response before returning.
Since
4.4.0
Parameters
WP_HTTP_Response $result Result to send to the client. Usually a WP_REST_Response.
WP_REST_Server $this Server instance.
WP_REST_Request $request Request used to generate the response.
Filter whether the request has already been served.
Allow sending the request manually - by returning true, the API result will not be sent to the client.
Since
4.4.0
Parameters
bool $served Whether the request has already been served. Default false.
WP_HTTP_Response $result Result to send to the client. Usually a WP_REST_Response.
WP_REST_Request $request Request used to generate the response.
WP_REST_Server $this Server instance.
Definition at line 226 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References $_SERVER, $path, __, apply_filters(), check_authentication(), dispatch(), elseif, envelope_response(), error_to_response(), get_headers(), get_json_last_error(), get_option(), get_raw_data(), is_wp_error(), json_error(), null, response_to_data(), rest_ensure_response(), send_header(), send_headers(), set_status(), wp_get_nocache_headers(), wp_json_encode(), and wp_unslash().
serve_request ($path = null)
Handles serving an API request.
Matches the current server URI to a route and runs the first matching callback then outputs a JSON representation of the returned value.
Since
4.4.0 public
See also
WP_REST_Server::dispatch()
Parameters
string $path Optional. The request route. If not set, `$_SERVER['PATH_INFO']` will be used. Default null.
Returns
false|null Null if not served and a HEAD request, false otherwise.
Send nocache headers on authenticated requests.
Since
4.4.0
Parameters
bool $rest_send_nocache_headers Whether to send no-cache headers.
Filter whether the REST API is enabled.
Since
4.4.0
Parameters
bool $rest_enabled Whether the REST API is enabled. Default true.
Filter whether jsonp is enabled.
Since
4.4.0
Parameters
bool $jsonp_enabled Whether jsonp is enabled. Default true.
Filter the API response.
Allows modification of the response before returning.
Since
4.4.0
Parameters
WP_HTTP_Response $result Result to send to the client. Usually a WP_REST_Response.
WP_REST_Server $this Server instance.
WP_REST_Request $request Request used to generate the response.
Filter whether the request has already been served.
Allow sending the request manually - by returning true, the API result will not be sent to the client.
Since
4.4.0
Parameters
bool $served Whether the request has already been served. Default false.
WP_HTTP_Response $result Result to send to the client. Usually a WP_REST_Response.
WP_REST_Request $request Request used to generate the response.
WP_REST_Server $this Server instance.
Definition at line 226 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References $_SERVER, $path, __, apply_filters(), check_authentication(), dispatch(), elseif, envelope_response(), error_to_response(), get_headers(), get_json_last_error(), get_option(), get_raw_data(), is_wp_error(), json_error(), null, response_to_data(), rest_ensure_response(), send_header(), send_headers(), set_status(), wp_get_nocache_headers(), wp_json_encode(), and wp_unslash().
set_status ($code) protected
Sends an HTTP status code.
Since
4.4.0 protected
Parameters
int $code HTTP status.
Definition at line 1127 of file wordpress/wp-includes/rest-api/class-wp-rest-server.php.
References status_header().
set_status ($code) protected
Sends an HTTP status code.
Since
4.4.0 protected
Parameters
int $code HTTP status.
Definition at line 1127 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
References status_header().
Referenced by json_error(), and serve_request().
Field Documentation
$endpoints = array() protected
Definition at line 73 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
Referenced by get_namespace_index(), Spy_REST_Server\get_raw_endpoint_data(), and get_routes().
$namespaces = array() protected
Definition at line 64 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
$route_options = array() protected
Definition at line 82 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
const ALLMETHODS = 'GET, POST, PUT, PATCH, DELETE'
Definition at line 55 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
const CREATABLE = 'POST'
Definition at line 31 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
const DELETABLE = 'DELETE'
Definition at line 47 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
Referenced by Tests_REST_Server\test_get_index(), and Tests_REST_Server\test_get_namespace_index().
const EDITABLE = 'POST, PUT, PATCH'
Definition at line 39 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
const READABLE = 'GET'
Definition at line 23 of file api-core/wp-includes/rest-api/class-wp-rest-server.php.
Referenced by WP_oEmbed_Controller\register_routes(), Tests_REST_Server\test_get_index(), Tests_REST_Server\test_get_namespace_index(), and Tests_REST_Server\test_get_namespaces().
The documentation for this class was generated from the following file:
api-core/wp-includes/rest-api/class-wp-rest-server.php