GravityView: Custom_Background Class Reference
Custom_Background Class Reference
Public Member Functions
__construct ($admin_header_callback= '', $admin_image_div_callback= '')
Constructor - Register administration header callback.
admin_load ()
Set up the enqueue for the CSS & JavaScript files.
admin_page ()
Display the custom background page.
ajax_background_add ()
AJAX handler for adding custom background context to an attachment.
attachment_fields_to_edit ($form_fields)
filter_upload_tabs ($tabs)
handle_upload ()
Handle an Image upload for the background image.
init ()
Set up the hooks for the Custom Background admin page.
take_action ()
Execute custom background modification.
wp_set_background_image ()
Data Fields
$admin_header_callback
$admin_image_div_callback
Private Attributes
$updated
Detailed Description
Definition at line 16 of file custom-background.php.
Constructor & Destructor Documentation
__construct ($admin_header_callback = '', $admin_image_div_callback = '')
Constructor - Register administration header callback.
Since
3.0.0
Parameters
callable $admin_header_callback
callable $admin_image_div_callback Optional custom image div output callback.
Definition at line 50 of file custom-background.php.
References $admin_header_callback, $admin_image_div_callback, and add_action().
Member Function Documentation
admin_load ()
Set up the enqueue for the CSS & JavaScript files.
Since
3.0.0
Definition at line 87 of file custom-background.php.
References __, get_current_screen(), wp_enqueue_media(), wp_enqueue_script(), and wp_enqueue_style().
admin_page ()
Display the custom background page.
Since
3.0.0
Definition at line 180 of file custom-background.php.
References __, _e, admin_url(), color, current_user_can(), esc_url, get_background_color(), get_background_image(), get_theme_mod(), home_url(), image, set_url_scheme(), and str_replace.
ajax_background_add ()
AJAX handler for adding custom background context to an attachment.
Triggered when the user adds a new background image from the Media Manager.
Since
4.1.0
Definition at line 420 of file custom-background.php.
attachment_fields_to_edit ($form_fields)
Since
3.4.0
Parameters
array $form_fields
Returns
array $form_fields
Definition at line 445 of file custom-background.php.
filter_upload_tabs ($tabs)
Since
3.4.0
Parameters
array $tabs
Returns
array $tabs
Definition at line 457 of file custom-background.php.
handle_upload ()
Handle an Image upload for the background image.
Since
3.0.0
This action is documented in wp-admin/custom-header.php
Definition at line 364 of file custom-background.php.
init ()
Set up the hooks for the Custom Background admin page.
Since
3.0.0
Definition at line 67 of file custom-background.php.
References $page, __, add_action(), and add_theme_page().
take_action ()
Execute custom background modification.
Since
3.0.0
Definition at line 114 of file custom-background.php.
References remove_theme_mod(), and set_theme_mod().
wp_set_background_image ()
Since
3.4.0
This filter is documented in wp-admin/includes/media.php
Definition at line 466 of file custom-background.php.
Field Documentation
$admin_header_callback
Definition at line 24 of file custom-background.php.
Referenced by __construct().
$admin_image_div_callback
Definition at line 32 of file custom-background.php.
Referenced by __construct().
$updated private
Definition at line 41 of file custom-background.php.
The documentation for this class was generated from the following file:
custom-background.php