GravityView: WP_Scripts Class Reference
WP_Scripts Class Reference
Public Member Functions
__construct ()
Constructor.
all_deps ($handles, $recursion=false, $group=false)
do_footer_items ()
do_head_items ()
do_item ($handle, $group=false)
in_default_dir ($src)
init ()
Initialize the class.
localize ($handle, $object_name, $l10n)
Localizes a script, only if the script has already been added.
print_extra_script ($handle, $echo=true)
print_scripts ($handles=false, $group=false)
Prints scripts.
print_scripts_l10n ($handle, $echo=true)
reset ()
public
set_group ($handle, $recursion, $group=false)
Public Member Functions inherited from WP_Dependencies
add ($handle, $src, $deps=array(), $ver=false, $args=null)
Register an item.
add_data ($handle, $key, $value)
Add extra item data.
all_deps ($handles, $recursion=false, $group=false)
Determine dependencies.
dequeue ($handles)
Dequeue an item or items.
do_item ($handle)
Process a dependency.
do_items ($handles=false, $group=false)
Process the items and dependencies.
enqueue ($handles)
Queue an item or items.
get_data ($handle, $key)
Get extra item data.
query ($handle, $list= 'registered')
Query list for an item.
remove ($handles)
Un-register an item or items.
set_group ($handle, $recursion, $group)
Set item group, unless already in a lower group.
Data Fields
$base_url
$concat = ''
$concat_version = ''
$content_url
$default_dirs
$default_version
$do_concat = false
$ext_handles = ''
$ext_version = ''
$in_footer = array()
$print_code = ''
$print_html = ''
Data Fields inherited from WP_Dependencies
$args = array()
$done = array()
$group = 0
$groups = array()
$queue = array()
$registered = array()
$to_do = array()
Additional Inherited Members
Protected Member Functions inherited from WP_Dependencies
recurse_deps ($queue, $handle)
Recursively search the passed dependency tree for $handle.
Detailed Description
Definition at line 19 of file class.wp-scripts.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Since
2.6.0 public
Definition at line 39 of file class.wp-scripts.php.
References add_action(), and init().
Member Function Documentation
all_deps ($handles, $recursion = false, $group = false)
Parameters
mixed $handles Item handle and argument (string) or item handles and arguments (array of strings).
bool $recursion Internal flag that function is calling itself.
mixed $group Group level: (int) level, (false) no groups.
Returns
bool True on success, false on failure.
Filter the list of script dependencies left to print.
Since
2.3.0
Parameters
array $to_do An array of script dependencies.
Definition at line 276 of file class.wp-scripts.php.
References apply_filters().
do_footer_items ()
Returns
array
Definition at line 302 of file class.wp-scripts.php.
References WP_Dependencies\$done, and WP_Dependencies\do_items().
do_head_items ()
Returns
array
Definition at line 294 of file class.wp-scripts.php.
References WP_Dependencies\$done, and WP_Dependencies\do_items().
do_item ($handle, $group = false)
Parameters
string $handle Name of the item. Should be unique.
int | bool $group
Returns
bool True on success, false if not set.
Filter the script loader source.
Since
2.2.0
Parameters
string $src Script loader source path.
string $handle Script handle.
This filter is documented in wp-includes/class.wp-scripts.php
Filter the HTML script tag of an enqueued script.
Since
4.1.0
Parameters
string $tag The <script> tag for the enqueued script.
string $handle The script's registered handle.
string $src The script's source URL.
Definition at line 115 of file class.wp-scripts.php.
References $default_version, WP_Dependencies\$group, add_query_arg(), apply_filters(), content_url(), esc_url, WP_Dependencies\get_data(), in_default_dir(), null, print_extra_script(), and registered.
in_default_dir ($src)
Parameters
string $src
Returns
bool
Definition at line 311 of file class.wp-scripts.php.
References WPINC.
Referenced by do_item().
init ()
Initialize the class.
Since
3.4.0 public
Fires when the WP_Scripts instance is initialized.
Since
2.6.0
Parameters
WP_Scripts &$this WP_Scripts instance, passed by reference.
Definition at line 50 of file class.wp-scripts.php.
References do_action_ref_array().
Referenced by __construct().
localize ($handle, $object_name, $l10n)
Localizes a script, only if the script has already been added.
Parameters
string $handle
string $object_name
array $l10n
Returns
bool
Definition at line 223 of file class.wp-scripts.php.
References $value, WP_Dependencies\add_data(), WP_Dependencies\get_data(), and wp_json_encode().
print_extra_script ($handle, $echo = true)
Parameters
string $handle
bool $echo
Returns
bool|string|void
Definition at line 94 of file class.wp-scripts.php.
References $output, and WP_Dependencies\get_data().
Referenced by do_item(), and print_scripts_l10n().
print_scripts ($handles = false, $group = false)
Prints scripts.
Prints the scripts passed to it or the print queue. Also prints all necessary dependencies.
Parameters
mixed $handles Optional. Scripts to be printed. (void) prints queue, (string) prints that script, (array of strings) prints those scripts. Default false.
int $group Optional. If scripts were queued in groups prints this group number. Default false.
Returns
array Scripts that have been printed.
Definition at line 72 of file class.wp-scripts.php.
References WP_Dependencies\$group, and WP_Dependencies\do_items().
print_scripts_l10n ($handle, $echo = true)
Parameters
string $handle
bool $echo
Returns
bool|string|void
Definition at line 84 of file class.wp-scripts.php.
References _deprecated_function(), and print_extra_script().
reset ()
public
Definition at line 331 of file class.wp-scripts.php.
set_group ($handle, $recursion, $group = false)
Parameters
string $handle Name of the item. Should be unique.
bool $recursion Internal flag that calling function was called recursively.
mixed $group Group level.
Returns
bool Not already in the group or a lower group
Definition at line 258 of file class.wp-scripts.php.
References WP_Dependencies\$group, WP_Dependencies\get_data(), and registered.
Field Documentation
$base_url
Definition at line 20 of file class.wp-scripts.php.
$concat = ''
Definition at line 24 of file class.wp-scripts.php.
$concat_version = ''
Definition at line 25 of file class.wp-scripts.php.
$content_url
Definition at line 21 of file class.wp-scripts.php.
$default_dirs
Definition at line 31 of file class.wp-scripts.php.
$default_version
Definition at line 22 of file class.wp-scripts.php.
Referenced by do_item().
$do_concat = false
Definition at line 26 of file class.wp-scripts.php.
$ext_handles = ''
Definition at line 29 of file class.wp-scripts.php.
$ext_version = ''
Definition at line 30 of file class.wp-scripts.php.
$in_footer = array()
Definition at line 23 of file class.wp-scripts.php.
$print_code = ''
Definition at line 28 of file class.wp-scripts.php.
$print_html = ''
Definition at line 27 of file class.wp-scripts.php.
The documentation for this class was generated from the following file:
class.wp-scripts.php