GravityView: GravityView_Admin_Views Class Reference
GravityView_Admin_Views Class Reference
If this file is called directly, abort.
Public Member Functions
__construct ()
add_custom_column_content ($column_name=null, $post_id=0)
Add the Data Source information.
add_gf_version_css_class ($class)
Allow targeting different versions of Gravity Forms using CSS selectors.
add_post_type_columns ($columns)
Add the Data Source column to the Views page.
add_view_dropdown ()
Adds dropdown selects to filter Views by connected form and layout.
default_field_blacklist ($array, $context)
default_field_blocklist ($array=array(), $context=NULL)
List the field types without presentation properties (on a View context)
filter_pre_get_posts (&$query)
get_available_fields ($form='', $zone=NULL)
Calculate the available fields.
get_entry_default_fields ($form, $zone)
Retrieve the default fields id, label and type.
get_registered_widgets ()
Get the list of registered widgets.
register_no_conflict ($registered)
Add GravityView scripts and styles to Gravity Forms and GravityView No-Conflict modes.
render_active_areas ($template_id, $type, $zone, $rows, $values)
Generic function to render rows and columns of active areas for widgets & fields.
render_additional_fields ($form=0, $context='single')
Render html for displaying additional fields based on a Form ID.
render_available_fields ($form=0, $context='single')
Render html for displaying available fields based on a Form ID.
render_available_widgets ()
Render html for displaying available widgets.
render_directory_active_areas ($template_id='', $context='single', $post_id='', $echo=false)
Render the Template Active Areas and configured active fields for a given template id and post id.
render_field_pickers ($context='directory', $form_ids=array())
Renders "Add Field" tooltips.
render_label ()
render_widgets_active_areas ($template_id='', $zone='', $post_id='')
Render the widget active areas.
save_postdata ($post_id)
Save View configuration.
suggest_support_articles ($localization_data=array())
When on the Add/Edit View screen, suggest most popular articles related to that.
tooltips ($tooltips=array())
Add tooltip text for use throughout the UI.
Static Public Member Functions
static add_scripts_and_styles ($hook)
Enqueue scripts and styles at Views editor.
static enqueue_gravity_forms_scripts ()
Enqueue Gravity Forms scripts, needed for Merge Tags.
static get_connected_form_links ($form, $include_form_link=true)
Get HTML links relating to a connected form, like Edit, Entries, Settings, Preview.
static gform_toolbar_menu ($menu_items=array(), $id=NULL)
Add a GravityView menu to the Form Toolbar with connected views.
static render_field_option ($name='', $option=array(), $curr_value=null)
static render_setting_row ($key='', $current_settings=array(), $override_input=null, $name='template_settings[%s]', $id='gravityview_se_%s')
Detailed Description
If this file is called directly, abort.
Definition at line 19 of file class-admin-views.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 23 of file class-admin-views.php.
Member Function Documentation
add_custom_column_content()
add_custom_column_content ($column_name = null, $post_id = 0)
Add the Data Source information.
Parameters
null $column_name Name of the column in the Views table.
int $post_id Post ID.
Returns
void
Definition at line 432 of file class-admin-views.php.
References GV\$form, $form_id, $output, $template, $templates, gravityview(), gravityview_get_form(), gravityview_get_form_id(), gravityview_get_registered_templates(), and gravityview_get_template_id().
add_gf_version_css_class()
add_gf_version_css_class ($class)
Allow targeting different versions of Gravity Forms using CSS selectors.
Adds specific version class: .gf-version-2.6.1.3 as well as point updates: .gf-minor-version-2.6.
Definition at line 78 of file class-admin-views.php.
References $class.
Referenced by GravityView_Welcome\getting_started_screen().
add_post_type_columns()
add_post_type_columns ($columns)
Add the Data Source column to the Views page.
Parameters
array $columns Columns array
Definition at line 564 of file class-admin-views.php.
References GVCommon\has_cap().
add_scripts_and_styles()
static add_scripts_and_styles ($hook) static
Enqueue scripts and styles at Views editor.
Parameters
mixed $hook
Returns
void
Definition at line 1265 of file class-admin-views.php.
References gravityview(), and GRAVITYVIEW_FILE.
add_view_dropdown()
add_view_dropdown ()
Adds dropdown selects to filter Views by connected form and layout.
Returns
void
Definition at line 173 of file class-admin-views.php.
References $current_form, GV\$form, $forms, Utils\_GET(), gravityview_get_forms(), and gravityview_get_registered_templates().
default_field_blacklist()
default_field_blacklist ($array, $context)
Definition at line 358 of file class-admin-views.php.
References default_field_blocklist().
default_field_blocklist()
default_field_blocklist ($array = array(), $context = NULL)
List the field types without presentation properties (on a View context)
Since
2.14
Parameters
array $array Existing field types to add to a blocklist
string | null $context Context for the blocklist. Default: NULL.
Returns
array Default blocklist fields merged with existing blocklist fields
Definition at line 341 of file class-admin-views.php.
Referenced by default_field_blacklist().
enqueue_gravity_forms_scripts()
static enqueue_gravity_forms_scripts () static
Enqueue Gravity Forms scripts, needed for Merge Tags.
Since
1.0.5-beta
Returns
void
Definition at line 1342 of file class-admin-views.php.
filter_pre_get_posts()
filter_pre_get_posts (& $query)
Since
1.15
Parameters
WP_Query $query
Definition at line 126 of file class-admin-views.php.
References $form_id, and Utils\_GET().
get_available_fields()
get_available_fields ($form = '', $zone = NULL)
Calculate the available fields.
Parameters
string | array $form form_ID or form object
string $zone Either 'single', 'directory', 'header', 'footer'
Returns
array fields
Runs Filter:
gravityview/admin/available_fields Modify the available fields that can be used in a View.
Parameters
array $fields The fields.
string | array $form form_ID or form object
string $zone Either 'single', 'directory', 'header', 'footer'
Definition at line 857 of file class-admin-views.php.
References $field, GV\$form, $gv_field, Utils\get(), GV\get(), GravityView_Fields\get_all(), get_entry_default_fields(), gravityview(), gravityview_get_entry_meta(), and gravityview_get_form_fields().
Referenced by render_active_areas(), and render_available_fields().
get_connected_form_links()
static get_connected_form_links ($form, $include_form_link = true) static
Get HTML links relating to a connected form, like Edit, Entries, Settings, Preview.
Parameters
array | int $form Gravity Forms forms array, or the form ID
boolean $include_form_link Whether to include the bold name of the form in the output
Returns
string HTML links
Runs Filter:
gravityview_connected_form_links Modify the links shown in the Connected Form links
Since
1.6
Parameters
array $links Links to show
array $form Gravity Forms form array
Definition at line 492 of file class-admin-views.php.
References GV\$form, $form_id, $output, gravityview_get_form(), and GVCommon\has_cap().
Referenced by GravityView_Admin_Metaboxes\get_data_source_header().
get_entry_default_fields()
get_entry_default_fields ($form, $zone)
Retrieve the default fields id, label and type.
Parameters
string | array $form form_ID or form object
string $zone Either 'single', 'directory', 'header', 'footer'
Returns
array
Runs Filter:
gravityview_entry_default_fields Modify the default fields for each zone and context
Parameters
array $entry_default_fields Array of fields shown by default
string | array $form form_ID or form object
string $zone Either 'single', 'directory', 'header', 'footer'
Definition at line 826 of file class-admin-views.php.
References GV\$form, and GravityView_Fields\get_all().
Referenced by get_available_fields().
get_registered_widgets()
get_registered_widgets ()
Get the list of registered widgets.
Each item is used to instantiate a GravityView_Admin_View_Widget object
Since
1.13.1
Returns
array
Definition at line 929 of file class-admin-views.php.
gform_toolbar_menu()
static gform_toolbar_menu ($menu_items = array(), $id = NULL) static
Add a GravityView menu to the Form Toolbar with connected views.
Parameters
array $menu_items Menu items, as set in GFForms::top_toolbar()
int $id ID of the current Gravity form
Returns
array Modified array
Definition at line 250 of file class-admin-views.php.
References $label, gravityview_get_connected_views(), and GVCommon\has_cap().
register_no_conflict()
register_no_conflict ($registered)
Add GravityView scripts and styles to Gravity Forms and GravityView No-Conflict modes.
Parameters
array $registered Existing scripts or styles that have been registered (array of the handles)
Returns
array
Definition at line 1367 of file class-admin-views.php.
render_active_areas()
render_active_areas ($template_id, $type, $zone, $rows, $values)
Generic function to render rows and columns of active areas for widgets & fields.
Parameters
string $template_id The current slug of the selected View template
string $type Either 'widget' or 'field'
string $zone Either 'single', 'directory', 'edit', 'header', 'footer'
array $rows The layout structure: rows, columns and areas
array $values Saved objects
Returns
void
Definition at line 945 of file class-admin-views.php.
References $field, GV\$form, $form_id, $post, endforeach, View\from_post(), get_available_fields(), gravityview(), gravityview_get_form_id(), gravityview_get_joined_forms(), GravityView_Ajax\pre_get_form_fields(), Widget\registered(), and GravityView_Render_Settings\render_field_options().
Referenced by render_directory_active_areas(), and render_widgets_active_areas().
render_additional_fields()
render_additional_fields ($form = 0, $context = 'single')
Render html for displaying additional fields based on a Form ID.
Parameters
int $form Gravity Forms Form ID (default: '')
string $context (default: 'single')
Returns
void
Runs Filter:
gravityview_additional_fields non-standard Fields to show at the bottom of the field picker
Parameters
array $additional_fields Associative array of field arrays, with label_text, desc, field_id, label_type, input_type, field_options, and settings_html keys
Definition at line 773 of file class-admin-views.php.
References GV\$form, and $settings.
Referenced by render_available_fields().
render_available_fields()
render_available_fields ($form = 0, $context = 'single')
Render html for displaying available fields based on a Form ID.
See also
GravityView_Ajax::get_available_fields_html() Triggers gravityview_render_available_fields action
Parameters
int $form Gravity Forms Form ID (default: '')
string $context (default: 'single')
Returns
void
Runs Filter:
gravityview_blocklist_field_types Modify the types of fields that shouldn't be shown in a View.
Parameters
array $blocklist_field_types Array of field types which are not proper to be shown for the $context.
string $context View context ('single', 'directory', or 'edit').
Since
2.9
Definition at line 709 of file class-admin-views.php.
References GV\$form, $output, get_available_fields(), gravityview(), GravityView_Ajax\pre_get_form_fields(), and render_additional_fields().
render_available_widgets()
render_available_widgets ()
Render html for displaying available widgets.
Returns
string html
Definition at line 909 of file class-admin-views.php.
References Widget\registered().
render_directory_active_areas()
render_directory_active_areas ($template_id = '', $context = 'single', $post_id = '', $echo = false)
Render the Template Active Areas and configured active fields for a given template id and post id.
Parameters
string $template_id (default: '') Template ID, like default_list, default_table, preset_business_data, etc. {
See also
GravityView_Template::__construct()}
Parameters
string $post_id (default: '')
string $context (default: 'single')
Returns
string HTML of the active areas
Runs Filter:
gravityview_template_active_areas
See also
GravityView_Template::assign_active_areas()
Parameters
array $template_areas Empty array, to be filled in by the template class
string $template_id Template ID, like default_list, default_table, preset_business_data, etc. {
See also
GravityView_Template::__construct()}
Parameters
string $context Current View context: directory, single, or edit (default: 'single')
Definition at line 1217 of file class-admin-views.php.
References $output, gravityview(), gravityview_get_directory_fields(), and render_active_areas().
render_field_option()
static render_field_option ($name = '', $option = array(), $curr_value = null) static
Definition at line 238 of file class-admin-views.php.
References $name, and GravityView_Render_Settings\render_field_option().
render_field_pickers()
render_field_pickers ($context = 'directory', $form_ids = array())
Renders "Add Field" tooltips.
Since
2.0.11
Parameters
string $context "directory", "single", or "edit"
array $form_ids (default: array) Array of form IDs
Returns
void
Definition at line 1168 of file class-admin-views.php.
References $form_id, $post, View\get_joined_forms(), and gravityview_get_form_id().
render_label()
render_label ()
Definition at line 695 of file class-admin-views.php.
render_setting_row()
static render_setting_row ($key = '', $current_settings = array(), $override_input = null, $name = 'template_settings[%s]', $id = 'gravityview_se_%s') static
Definition at line 229 of file class-admin-views.php.
References $current_settings, $name, and GravityView_Render_Settings\render_setting_row().
render_widgets_active_areas()
render_widgets_active_areas ($template_id = '', $zone = '', $post_id = '')
Render the widget active areas.
Parameters
string $template_id The current slug of the selected View template
string $zone Either 'header' or 'footer'
string $post_id Current Post ID (view)
Returns
string html
Runs Filter:
gravityview/view/widgets/default Modify the default widgets for new Views
Parameters
array $widgets A Widget configuration array
string $zone The widget zone that's being requested
int $post_id The auto-draft post ID
Definition at line 1090 of file class-admin-views.php.
References $output, Widget\get_default_widget_areas(), gravityview_get_directory_widgets(), and render_active_areas().
save_postdata()
save_postdata ($post_id)
Save View configuration.
Parameters
int $post_id Currently saved Post ID
Returns
void
Runs Actions:
gravityview_view_saved After a View has been saved in the admin
Parameters
int $post_id ID of the View that has been saved
array $statii Array of statuses of the post meta saving processes. If saving worked, each key should be mapped to a value of the post ID (directory_widgets => 124). If failed (or didn't change), the value will be false.
Since
1.17.2
Definition at line 599 of file class-admin-views.php.
References $form_id, _gravityview_process_posted_fields(), gravityview(), gravityview_set_directory_widgets(), and GVCommon\has_cap().
suggest_support_articles()
suggest_support_articles ($localization_data = array())
When on the Add/Edit View screen, suggest most popular articles related to that.
Parameters
array $localization_data Data to be passed to the Support Port JS
Returns
array
Definition at line 102 of file class-admin-views.php.
References gravityview().
tooltips()
tooltips ($tooltips = array())
Add tooltip text for use throughout the UI.
Parameters
array $tooltips Array of Gravity Forms tooltips
Returns
array Modified tooltips array
Runs Filter:
gravityview_tooltips The tooltips GravityView adds to the Gravity Forms tooltip array
Parameters
array $gv_tooltips Associative array with unique keys containing array of title and value keys, as expected by gform_tooltips filter
Runs Filter:
gravityview/metaboxes/tooltips The tooltips GravityView adds to the Gravity Forms tooltip array
Parameters
array $gv_tooltips Associative array with unique keys containing array of title and value keys, as expected by gform_tooltips filter
Definition at line 368 of file class-admin-views.php.
References $title, and View_Settings\defaults().
The documentation for this class was generated from the following file:
class-admin-views.php