GravityView: SimplePie_Item Class Reference
SimplePie_Item Class Reference
Public Member Functions
__construct ($feed, $data)
Create a new item object.
__destruct ()
Remove items that link back to this before destroying this object.
__toString ()
Get a string representation of the item.
get_author ($key=0)
Get an author for the item.
get_authors ()
Get all authors for the item.
get_base ($element=array())
Get the base URL value from the parent feed.
get_categories ()
Get all categories for the item.
get_category ($key=0)
Get a category for the item.
get_content ($content_only=false)
Get the content for the item.
get_contributor ($key=0)
Get a contributor for the item.
get_contributors ()
Get all contributors for the item.
get_copyright ()
Get the copyright info for the item.
get_date ($date_format= 'j F Y, g:i a')
Get the posting date/time for the item.
get_description ($description_only=false)
Get the content for the item.
get_enclosure ($key=0, $prefer=null)
Get an enclosure from the item.
get_enclosures ()
Get all available enclosures (podcasts, etc.)
get_feed ()
Get the parent feed.
get_gmdate ($date_format= 'j F Y, g:i a')
Get the posting date/time for the item (UTC time)
get_id ($hash=false)
Get the unique identifier for the item.
get_item_tags ($namespace, $tag)
Get data for an item-level element.
get_latitude ()
Get the latitude coordinates for the item.
get_link ($key=0, $rel= 'alternate')
Get a single link for the item.
get_links ($rel= 'alternate')
Get all links for the item.
get_local_date ($date_format= '%c')
Get the localized posting date/time for the item.
get_longitude ()
Get the longitude coordinates for the item.
get_permalink ()
Get the permalink for the item.
get_source ()
Get the <atom:source> for the item.
get_title ()
Get the title of the item.
get_updated_date ($date_format= 'j F Y, g:i a')
Get the update date/time for the item.
get_updated_gmdate ($date_format= 'j F Y, g:i a')
Get the update date/time for the item (UTC time)
sanitize ($data, $type, $base= '')
Sanitize feed data.
set_registry (SimplePie_Registry $registry)
Set the registry handler.
Data Fields
$data = array()
$feed
Protected Attributes
$registry
Detailed Description
Definition at line 56 of file Item.php.
Constructor & Destructor Documentation
__construct ($feed, $data)
Create a new item object.
This is usually used by {
See also
SimplePie::get_items} and {
SimplePie::get_item}. Avoid creating this manually.
Parameters
SimplePie $feed Parent feed
array $data Raw data
Definition at line 91 of file Item.php.
References $data, and $feed.
__destruct ()
Remove items that link back to this before destroying this object.
Definition at line 123 of file Item.php.
Member Function Documentation
__toString ()
Get a string representation of the item.
Returns
string
Definition at line 115 of file Item.php.
get_author ($key = 0)
Get an author for the item.
Since
Beta 2
Parameters
int $key The author that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Author|null
Definition at line 502 of file Item.php.
References $authors, get_authors(), and null.
get_authors ()
Get all authors for the item.
Uses <atom:author>, <author>, <dc:creator> or <itunes:author>
Since
Beta 2
Returns
array|null List of {
See also
SimplePie_Author} objects
Definition at line 609 of file Item.php.
References $authors, $name, $url, elseif, get_base(), get_item_tags(), get_source(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_ITUNES, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_author().
get_base ($element = array())
Get the base URL value from the parent feed.
Uses <xml:base>
Parameters
array $element
Returns
string
Definition at line 165 of file Item.php.
Referenced by get_authors(), get_content(), get_contributors(), get_copyright(), get_description(), get_enclosures(), get_links(), and get_title().
get_categories ()
Get all categories for the item.
Uses <atom:category>, <category> or <dc:subject>
Since
Beta 3
Returns
array|null List of {
See also
SimplePie_Category} objects
Definition at line 438 of file Item.php.
References $label, get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_category().
get_category ($key = 0)
Get a category for the item.
Since
Beta 3 (previously called get_categories() since Beta 2)
Parameters
int $key The category that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Category|null
Definition at line 417 of file Item.php.
References get_categories(), and null.
get_content ($content_only = false)
Get the content for the item.
Prefers full content over summaries, but will return a summary if full content does not exist.
To prefer summaries instead, use {
See also
get_description}
Uses <atom:content> or <content:encoded> (RSS 1.0 Content Module)
Since
1.0
Parameters
boolean $content_only Should we avoid falling back to the description?
Returns
string|null
Definition at line 386 of file Item.php.
References elseif, get_base(), get_description(), get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, and SIMPLEPIE_NAMESPACE_RSS_10_MODULES_CONTENT.
Referenced by get_description().
get_contributor ($key = 0)
Get a contributor for the item.
Since
1.1
Parameters
int $key The contrbutor that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Author|null
Definition at line 522 of file Item.php.
References get_contributors(), and null.
get_contributors ()
Get all contributors for the item.
Uses <atom:contributor>
Since
1.1
Returns
array|null List of {
See also
SimplePie_Author} objects
Definition at line 543 of file Item.php.
References $name, $url, get_base(), get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, and SIMPLEPIE_NAMESPACE_ATOM_10.
Referenced by get_contributor().
get_copyright ()
Get the copyright info for the item.
Uses <atom:rights> or <dc:rights>
Since
1.1
Returns
string
Definition at line 699 of file Item.php.
References elseif, get_base(), get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, and SIMPLEPIE_NAMESPACE_DC_11.
get_date ($date_format = 'j F Y, g:i a')
Get the posting date/time for the item.
Uses <atom:published>, <atom:updated>, <atom:issued>, <atom:modified>, <pubDate> or <dc:date>
Note: obeys PHP's timezone setting. To get a UTC date/time, use {
See also
get_gmdate}
Since
Beta 2 (previously called get_item_date since 0.8)
Parameters
string $date_format Supports any PHP date format from {
See also
http://php.net/date} (empty for the raw data)
Returns
int|string|null
Definition at line 733 of file Item.php.
References $date_format, date, elseif, get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_gmdate(), and get_local_date().
get_description ($description_only = false)
Get the content for the item.
Prefers summaries over full content , but will return full content if a summary does not exist.
To prefer full content instead, use {
See also
get_content}
Uses <atom:summary>, <description>, <dc:description> or <itunes:subtitle>
Since
0.8
Parameters
boolean $description_only Should we avoid falling back to the content?
Returns
string|null
Definition at line 323 of file Item.php.
References elseif, get_base(), get_content(), get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_content().
get_enclosure ($key = 0, $prefer = null)
Get an enclosure from the item.
Supports the <enclosure> RSS tag, as well as Media RSS and iTunes RSS.
Since
Beta 2
Definition at line 1059 of file Item.php.
References get_enclosures(), and null.
Referenced by get_permalink().
get_enclosures ()
Get all available enclosures (podcasts, etc.)
Supports the <enclosure> RSS tag, as well as Media RSS and iTunes RSS.
At this point, we're pretty much assuming that all enclosures for an item are the same content. Anything else is too complicated to properly support.
Since
Beta 2
Definition at line 1086 of file Item.php.
References $caption, $content, $credits, $description, $duration, $label, $lang, $link, $ratings, $title, $url, $value, elseif, get_base(), get_feed(), get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_MEDIARSS, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_enclosure().
get_feed ()
Get the parent feed.
Note: this may not work as you think for multifeeds!
1.0 SimplePie
Definition at line 194 of file Item.php.
References $feed.
Referenced by get_enclosures().
get_gmdate ($date_format = 'j F Y, g:i a')
Get the posting date/time for the item (UTC time)
See also
get_date
Parameters
string $date_format Supports any PHP date format from {
See also
http://php.net/date}
Returns
int|string|null
Definition at line 888 of file Item.php.
References $date_format, get_date(), and null.
get_id ($hash = false)
Get the unique identifier for the item.
This is usually used when writing code to check for new items in a feed.
Uses <atom:id>, <guid>, <dc:identifier> or the about attribute for RDF. If none of these are supplied (or $hash is true), creates an MD5 hash based on the permalink and title. If either of those are not supplied, creates a hash based on the full feed data.
Since
Beta 2
Parameters
boolean $hash Should we force using a hash instead of the supplied ID?
Returns
string
Definition at line 213 of file Item.php.
References elseif, get_item_tags(), get_permalink(), get_title(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RDF, and SIMPLEPIE_NAMESPACE_RSS_20.
get_item_tags ($namespace, $tag)
Get data for an item-level element.
This method allows you to get access to ANY element/attribute that is a sub-element of the item/entry tag.
See {
See also
SimplePie::get_feed_tags()} for a description of the return value
Since
1.0
See also
http://simplepie.org/wiki/faq/supported_xml_namespaces
Parameters
string $namespace The URL of the XML namespace of the elements you're trying to access
string $tag Tag name
Returns
array
Definition at line 145 of file Item.php.
References null.
Referenced by get_authors(), get_categories(), get_content(), get_contributors(), get_copyright(), get_date(), get_description(), get_enclosures(), get_id(), get_latitude(), get_links(), get_longitude(), get_source(), get_title(), and get_updated_date().
get_latitude ()
Get the latitude coordinates for the item.
Compatible with the W3C WGS84 Basic Geo and GeoRSS specifications
Uses <geo:lat> or <georss:point>
Since
1.0 W3C WGS84 Basic Geo http://www.georss.org/ GeoRSS string|null
Definition at line 2898 of file Item.php.
References elseif, get_item_tags(), null, SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
get_link ($key = 0, $rel = 'alternate')
Get a single link for the item.
Since
Beta 3
Parameters
int $key The link that you want to return. Remember that arrays begin with 0, not 1
string $rel The relationship of the link to return
Returns
string|null Link URL
Definition at line 953 of file Item.php.
References get_links(), and null.
Referenced by get_permalink().
get_links ($rel = 'alternate')
Get all links for the item.
Uses <atom:link>, <link> or <guid>
Since
Beta 2
Parameters
string $rel The relationship of links to return
Returns
array|null Links found for the item (strings)
Definition at line 975 of file Item.php.
References $keys, $link, elseif, get_base(), get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_IANA_LINK_RELATIONS_REGISTRY, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_link().
get_local_date ($date_format = '%c')
Get the localized posting date/time for the item.
Returns the date formatted in the localized language. To display in languages other than the server's default, you need to change the locale with setlocale(). The available localizations depend on which ones are installed on your web server.
Since
1.0
Parameters
string $date_format Supports any PHP date format from {
See also
http://php.net/strftime} (empty for the raw data)
Returns
int|string|null
Definition at line 865 of file Item.php.
References $date_format, elseif, get_date(), null, sanitize(), and SIMPLEPIE_CONSTRUCT_TEXT.
get_longitude ()
Get the longitude coordinates for the item.
Compatible with the W3C WGS84 Basic Geo and GeoRSS specifications
Uses <geo:long>, <geo:lon> or <georss:point>
Since
1.0 W3C WGS84 Basic Geo http://www.georss.org/ GeoRSS string|null
Definition at line 2926 of file Item.php.
References elseif, get_item_tags(), null, SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
get_permalink ()
Get the permalink for the item.
Returns the first link available with a relationship of "alternate". Identical to {
See also
get_link()} with key 0
get_link
Since
0.8
Returns
string|null Permalink URL
Definition at line 927 of file Item.php.
References $link, elseif, get_enclosure(), get_link(), and null.
Referenced by get_id().
get_source ()
Get the <atom:source> for the item.
Since
1.1
Returns
SimplePie_Source|null
Definition at line 2952 of file Item.php.
References get_item_tags(), null, and SIMPLEPIE_NAMESPACE_ATOM_10.
Referenced by get_authors().
get_title ()
Get the title of the item.
Uses <atom:title>, <title> or <dc:title>
Since
Beta 2 (previously called get_item_title since 0.8)
Returns
string|null
Definition at line 268 of file Item.php.
References elseif, get_base(), get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_id().
get_updated_date ($date_format = 'j F Y, g:i a')
Get the update date/time for the item.
Uses <atom:updated>
Note: obeys PHP's timezone setting. To get a UTC date/time, use {
See also
get_gmdate}
Parameters
string $date_format Supports any PHP date format from {
See also
http://php.net/date} (empty for the raw data)
Returns
int|string|null
Definition at line 812 of file Item.php.
References $date_format, date, get_item_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, and SIMPLEPIE_NAMESPACE_ATOM_10.
Referenced by get_updated_gmdate().
get_updated_gmdate ($date_format = 'j F Y, g:i a')
Get the update date/time for the item (UTC time)
See also
get_updated_date
Parameters
string $date_format Supports any PHP date format from {
See also
http://php.net/date}
Returns
int|string|null
Definition at line 906 of file Item.php.
References $date_format, get_updated_date(), and null.
sanitize ($data, $type, $base = '')
Sanitize feed data.
private
See also
SimplePie::sanitize()
Parameters
string $data Data to sanitize
int $type One of the SIMPLEPIE_CONSTRUCT_* constants
string $base Base URL to resolve URLs against
Returns
string Sanitized data
Definition at line 180 of file Item.php.
Referenced by get_authors(), get_categories(), get_content(), get_contributors(), get_copyright(), get_date(), get_description(), get_enclosures(), get_id(), get_links(), get_local_date(), get_title(), and get_updated_date().
set_registry (SimplePie_Registry $registry)
Set the registry handler.
This is usually used by {
See also
SimplePie_Registry::create}
Since
1.3
Parameters
SimplePie_Registry $registry
Definition at line 105 of file Item.php.
References $registry.
Field Documentation
$data = array()
Definition at line 72 of file Item.php.
Referenced by __construct().
$feed
Definition at line 64 of file Item.php.
Referenced by __construct(), and get_feed().
$registry protected
Definition at line 80 of file Item.php.
Referenced by set_registry().
The documentation for this class was generated from the following file:
Item.php