GravityView: GravityView_Entry_Link_Shortcode_Test Class Reference
GravityView_Entry_Link_Shortcode_Test Class Reference
entry_link_shortcode shortcode
Public Member Functions
_test_delete ($view, $entry, $atts)
GravityView_Entry_Link_Shortcode::delete_shortcode
_test_edit ($view, $entry, $atts)
GravityView_Entry_Link_Shortcode::edit_shortcode
_test_read ($view, $entry, $atts)
GravityView_Entry_Link_Shortcode::read_shortcode
setUp ()
test_add_hooks ()
GravityView_Entry_Link_Shortcode::__construct GravityView_Entry_Link_Shortcode::add_hooks
test_shortcode ()
GravityView_Entry_Link_Shortcode::shortcode
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Data Fields
$object
GravityView_Entry_Link_Shortcode
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
entry_link_shortcode shortcode
Since
1.15
Definition at line 10 of file GravityView_Entry_Link_Shortcode_Test.php.
Member Function Documentation
_test_delete ($view, $entry, $atts)
GravityView_Entry_Link_Shortcode::delete_shortcode
Definition at line 94 of file GravityView_Entry_Link_Shortcode_Test.php.
References GravityView_Delete_Entry\get_delete_link().
Referenced by test_shortcode().
_test_edit ($view, $entry, $atts)
GravityView_Entry_Link_Shortcode::edit_shortcode
Definition at line 122 of file GravityView_Entry_Link_Shortcode_Test.php.
References GravityView_Edit_Entry\get_nonce_key(), and GravityView_View_Data\getInstance().
Referenced by test_shortcode().
_test_read ($view, $entry, $atts)
GravityView_Entry_Link_Shortcode::read_shortcode
Definition at line 78 of file GravityView_Entry_Link_Shortcode_Test.php.
References GravityView_View_Data\getInstance().
Referenced by test_shortcode().
setUp ()
Definition at line 15 of file GravityView_Entry_Link_Shortcode_Test.php.
References GravityView_Entry_Link_Shortcode.
test_add_hooks ()
GravityView_Entry_Link_Shortcode::__construct GravityView_Entry_Link_Shortcode::add_hooks
Definition at line 24 of file GravityView_Entry_Link_Shortcode_Test.php.
test_shortcode ()
GravityView_Entry_Link_Shortcode::shortcode
Definition at line 33 of file GravityView_Entry_Link_Shortcode_Test.php.
References _test_delete(), _test_edit(), and _test_read().
Field Documentation
$object
GravityView_Entry_Link_Shortcode
Definition at line 13 of file GravityView_Entry_Link_Shortcode_Test.php.
The documentation for this class was generated from the following file:
GravityView_Entry_Link_Shortcode_Test.php