GravityView: GFFormsModel Class Reference
GFFormsModel Class Reference
Static Public Member Functions
static add_default_properties ($form)
static add_email_to_incomplete_sumbmission ($token, $email)
static add_note ($lead_id, $user_id, $user_name, $note, $note_type= 'note')
static build_lead_array ($results, $use_long_values=true)
static choice_value_match ($field, $choice, $value)
static choices_value_match ($field, $choices, $value)
static convert_confirmation ($form)
v1.7 introduces conditional confirmations.
static convert_field_objects ($form)
static count_search_leads ($form_id, $search_criteria=array())
static create_lead ($form)
static create_post ($form, &$lead)
static dbDelta ($sql)
static delete_custom_choice ($name)
static delete_field ($form_id, $field_id)
static delete_file ($entry_id, $field_id, $file_index=0)
static delete_files ($lead_id, $form=null)
static delete_files_by_form ($form_id, $status= '')
static delete_form ($form_id)
static delete_forms ($forms)
static delete_incomplete_submission ($token)
static delete_lead ($lead_id)
static delete_leads ($leads)
static delete_leads_by_form ($form_id, $status= '')
static delete_note ($note_id)
static delete_notes ($notes)
static delete_password ($entry, $form)
static delete_views ($form_id)
static drop_tables ()
static duplicate_form ($form_id)
static ensure_tables_exist ()
static flush_confirmations ()
static flush_current_forms ()
static flush_current_lead ()
static get_choice_text ($field, $value, $input_id=0)
static get_current_lead ()
Return the current lead being processed.
static get_current_page_url ($force_ssl=false)
static get_custom_choices ()
static get_custom_field_names ()
static get_db_charset ()
static get_default_value ($field, $input_id)
static get_encrypted_fields ($entry_id)
static get_entry_meta ($form_ids)
static get_field ($form, $field_id)
static get_field_value (&$field, $field_values=array(), $get_from_post=true)
static get_field_value_long ($lead, $field_number, $form, $apply_filter=true)
static get_fields_by_type ($form, $types, $use_input_type=false)
Returns an array containing the form fields of the specified type or types.
static get_file_upload_path ($form_id, $file_name)
static get_fileupload_value ($form_id, $input_name)
static get_form ($form_id, $allow_trash=false)
static get_form_confirmations ($form_id)
static get_form_count ()
static get_form_counts ($form_id)
static get_form_db_columns ()
static get_form_id ($form_title)
static get_form_ids ($active=true, $trash=false)
static get_form_meta ($form_id)
static get_form_meta_by_id ($ids)
static get_form_payment_totals ($form_id)
static get_form_summary ()
static get_form_table_name ()
static get_form_unique_id ($form_id)
static get_form_view_table_name ()
static get_forms ($is_active=null, $sort_column= 'title', $sort_dir= 'ASC', $is_trash=false)
static get_forms_by_id ($ids)
static get_grid_column_meta ($form_id)
static get_grid_columns ($form_id, $input_label_only=false)
static get_incomplete_submission_values ($token)
static get_incomplete_submissions_table_name ()
static get_input ($field, $id)
static get_input_masks ()
static get_input_type ($field)
static get_ip ()
static get_label ($field, $input_id=0, $input_only=false, $allow_admin_label=true)
static get_lead ($lead_id)
static get_lead_count ($form_id, $search, $star=null, $read=null, $start_date=null, $end_date=null, $status=null, $payment_status=null)
static get_lead_count_all_forms ($status= 'active')
static get_lead_detail_id ($current_fields, $field_number)
static get_lead_details_long_table_name ()
static get_lead_details_table_name ()
static get_lead_field_value ($lead, $field)
static get_lead_ids ($form_id, $search, $star=null, $read=null, $start_date=null, $end_date=null, $status=null, $payment_status=null)
static get_lead_meta_table_name ()
static get_lead_notes ($lead_id)
static get_lead_notes_table_name ()
static get_lead_table_name ()
static get_lead_view_name ()
static get_leads ($form_id, $sort_field_number=0, $sort_direction= 'DESC', $search= '', $offset=0, $page_size=30, $star=null, $read=null, $is_numeric_sort=false, $start_date=null, $end_date=null, $status= 'active', $payment_status=false)
static get_leads_by_meta ($meta_key, $meta_value)
static get_leads_count ($form_id)
static get_leads_where_sql ($args)
static get_meta_table_name ()
static get_page_by_number ($form, $page_number)
static get_parameter_value ($name, $field_values, $field)
static get_prepared_input_value ($form, $field, $lead, $input_id)
static get_section ($form, $field_id)
static get_submitted_fields ($form_id)
static get_tables ()
static get_temp_filename ($form_id, $input_name)
static get_upload_path ($form_id)
static get_upload_root ()
static get_upload_url ($form_id)
static get_upload_url_root ()
static get_uuid ($s= '')
Returns a UUID.
static has_input ($field, $input_id)
static insert_form ($form_title)
static insert_form_view ($form_id, $ip)
static is_checkbox_checked ($field_id, $field_label, $lead, $form)
static is_duplicate ($form_id, $field, $value)
static is_encrypted_field ($entry_id, $field_id)
static is_field_hidden ($form, $field, $field_values, $lead=null)
Check whether a field is hidden via conditional logic.
static is_html5_enabled ()
static is_page_hidden ($form, $page_number, $field_values, $lead=null)
static is_unique_title ($title)
static is_valid_index ($index_name)
static is_valid_operator ($operator)
static is_valid_table ($table_name)
static is_value_match ($field_value, $target_value, $operation= 'is', $source_field=null, $rule=null, $form=null)
static load_confirmations ($form)
static matches_operation ($val1, $val2, $operation)
static maybe_sanitize_form_settings ($form)
static maybe_trim_input ($value, $form_id, $field)
static mu_drop_tables ($drop_tables)
static prepare_date ($date_format, $value)
static prepare_value ($form, $field, $value, $input_name, $lead_id, $lead=array())
Prepare the value before saving it to the lead.
static purge_expired_incomplete_submissions ($expiration_days=30)
static refresh_lead_field_value ($lead_id, $field_id)
static refresh_product_cache ($form, $lead, $use_choice_text=false, $use_admin_label=false)
static restore_form ($form_id)
static restore_forms ($form_ids)
static sanitize_conditional_logic ($logic)
static sanitize_settings ($form)
static save_custom_choice ($previous_name, $new_name, $choices)
static save_form_confirmations ($form_id, $confirmations)
static save_form_notifications ($form_id, $notifications)
static save_incomplete_submission ($form, $entry, $field_values, $page_number, $files, $form_unique_id, $ip, $source_url, $resume_token= '')
static save_input ($form, $field, &$lead, $current_fields, $input_id)
static save_key ($key)
static save_lead ($form, &$lead)
static search_lead_ids ($form_id, $search_criteria=array())
static search_leads ($form_id, $search_criteria=array(), $sorting=null, $paging=null)
static set_current_lead ($lead)
Set RGFormsModel::$lead for use in hooks where $lead is not explicitly passed.
static set_encrypted_fields ($entry_id, $field_ids)
static set_entry_meta ($lead, $form)
static set_permissions ($path)
static trash_form ($form_id)
static trash_forms ($form_ids)
static trim_conditional_logic_values ($meta_array, $form, &$updated=false)
Trims values from an array of elements e.g.
static trim_conditional_logic_values_from_element ($element, $form=array(), &$updated=false)
Trims values from elements e.g.
static trim_form_meta_values ($form, &$form_updated=false)
Trims values inside choice texts, choice values, input labels, field labels and field conditionalLogic.
static unserialize ($string)
static update_confirmation_active ($form_id, $confirmation_id, $is_active)
static update_form_active ($form_id, $is_active)
static update_form_meta ($form_id, $form_meta, $meta_name= 'display_meta')
static update_forms_active ($forms, $is_active)
static update_grid_column_meta ($form_id, $columns)
static update_lead ($lead)
static update_lead_field_value ($form, $lead, $field, $lead_detail_id, $input_id, $value)
Updates an existing field value in the database.
static update_lead_property ($lead_id, $property_name, $property_value, $update_akismet=true, $disable_hook=false)
static update_leads_property ($leads, $property_name, $property_value)
static update_notification_active ($form_id, $notification_id, $is_active)
static upload_file ($form_id, $file)
Static Public Attributes
static $unique_ids = array()
static $uploaded_files = array()
Static Private Member Functions
static convert_property_to_merge_tag ($form, $array, $target_property, $source_property)
static copy_post_image ($url, $post_id)
static delete_physical_file ($file_url)
static get_custom_field ($form, $meta_name, $meta_index)
static get_date_range_where ($search_criteria)
static get_default_post_title ()
static get_field_display ($form, $field, $field_values, $lead=null)
static get_field_filters_where ($form_id, $search_criteria)
static get_field_merge_tag ($form, $field_id)
static get_form_id_where ($form_id)
static get_info_search_where ($search_criteria)
static get_lead_db_columns ()
static get_post_field_value ($field, $lead)
static get_post_fields ($form, $lead)
static get_search_operator ($search_criteria)
static get_search_where ($form_id, $search_criteria)
static load_notifications_from_legacy ($form)
static load_notifications_to_legacy ($form)
static media_handle_upload ($url, $post_id, $post_data=array())
static move_temp_file ($form_id, $tempfile_info)
static sort_by_column_query ($form_id, $search_criteria, $sorting, $paging)
static sort_by_custom_field_query ($form_id, $sort_field_number=0, $sort_direction= 'DESC', $search= '', $offset=0, $page_size=30, $star=null, $read=null, $is_numeric_sort=false, $status= 'active', $payment_status=false)
static sort_by_default_field_query ($form_id, $sort_field, $sort_direction= 'DESC', $search= '', $offset=0, $page_size=30, $star=null, $read=null, $is_numeric_sort=false, $start_date=null, $end_date=null, $status= 'active', $payment_status=false)
static sort_by_field_query ($form_id, $search_criteria, $sorting, $paging)
static truncate ($str, $length)
static try_convert_float ($text)
Static Private Attributes
static $_confirmations = array()
static $_current_forms = array()
An in-memory cache for the form meta for the current blog.
static $_current_lead = null
Detailed Description
Definition at line 12 of file forms_model.php.
Member Function Documentation
static add_default_properties ($form) static
Definition at line 533 of file forms_model.php.
References $field, $form, _deprecated_function(), and wp_parse_args().
Referenced by GVCommon\get_form_fields().
static add_email_to_incomplete_sumbmission ($token, $email) static
Definition at line 2135 of file forms_model.php.
References $wpdb.
Referenced by GFFormDisplay\process_send_resume_link().
static add_note ($lead_id, $user_id, $user_name, $note, $note_type = 'note') static
Definition at line 1309 of file forms_model.php.
References $user_id, $wpdb, and do_action().
Referenced by GravityView_Entry_Notes\add_note(), GFAddOn\add_note(), and GFEntryDetail\lead_detail_page().
static build_lead_array ($results, $use_long_values = true) static
Definition at line 3735 of file forms_model.php.
References $field, $form, $form_id, $leads, $value, get_entry_meta(), get_field_value_long(), get_form_meta(), gform_get_meta_values_for_entries(), GFORMS_MAX_FIELD_LENGTH, and if.
Referenced by search_leads().
static choice_value_match ($field, $choice, $value) static
Definition at line 2554 of file forms_model.php.
References $ary, $field, $value, get_input_type(), maybe_trim_input(), wp_kses(), and wp_kses_allowed_html().
Referenced by GF_Field_Checkbox\get_checkbox_choices(), GF_Field_Radio\get_radio_choices(), and GF_Field_Checkbox\get_value_submission().
static choices_value_match ($field, $choices, $value) static
Definition at line 2588 of file forms_model.php.
References $field, and $value.
Referenced by GF_Field_Radio\get_radio_choices().
static convert_confirmation ($form) static
v1.7 introduces conditional confirmations.
If the form's "confirmations" key is empty, grab the existing confirmation and populate it in the form's "confirmations" property.
Parameters
mixed $form
Returns
array
Definition at line 4123 of file forms_model.php.
References $form, $id, and esc_html__().
static convert_field_objects ($form) static
Definition at line 372 of file forms_model.php.
References $field, $form, and GF_Fields\create().
Referenced by GFExport\add_default_export_fields(), and GFExport\cleanup().
static convert_property_to_merge_tag ($form, $array, $target_property, $source_property) static private
Definition at line 514 of file forms_model.php.
References $form, and $merge_tag.
static copy_post_image ($url, $post_id) static private
Filter the media upload location.
Parameters
array $upload_dir The current upload directorys path and url.
int $form_id The ID of the form currently being processed.
int $post_id The ID of the post created from the entry currently being processed.
Definition at line 2852 of file forms_model.php.
References $form_id, $name, $path, $post, $post_id, $url, current_time(), delete_transient(), get_post(), get_post_meta(), is_multisite(), str_replace, wp_check_filetype(), wp_mkdir_p(), wp_unique_filename(), and wp_upload_dir().
static count_search_leads ($form_id, $search_criteria = array()) static
Definition at line 4823 of file forms_model.php.
References $form_id, $wpdb, get_lead_details_table_name(), and get_lead_table_name().
Referenced by GFAPI\count_entries().
static create_lead ($form) static
Allow the currency code to be overridden.
Parameters
string $currency The three character ISO currency code to be stored in the entry. Default is value returned by GFCommon::get_currency()
array $form The form currently being processed.
Definition at line 1501 of file forms_model.php.
References $_SERVER, $current_user, $field, $form, esc_url_raw(), is_field_hidden(), null, and sanitize_text_field().
Referenced by GFFormDisplay\update_confirmation(), and GFPaymentAddOn\validation().
static create_post ($form, & $lead) static
Fires after a post, from a form with post fields, is created
Parameters
int $form,['id'] The ID of the form where the new post was created
int $post_id The new Post ID created after submission
array $lead The Lead Object
array $form The Form Object for the form used to create the post
Definition at line 2598 of file forms_model.php.
References $field, $form, $image, $image_meta, $post, $post_id, $post_title, $value, add_post_meta(), current_theme_supports(), do_shortcode(), get_field(), get_input_type(), get_post(), get_theme_support(), maybe_unserialize(), media_handle_upload(), set_post_format(), set_post_thumbnail(), str_replace, wp_insert_post(), and wp_update_post().
static dbDelta ($sql) static
Definition at line 4853 of file forms_model.php.
References $wpdb, ABSPATH, add_filter(), and remove_filter().
Referenced by GFPaymentAddOn\upgrade_payment().
static delete_custom_choice ($name) static
Definition at line 1930 of file forms_model.php.
References $name, and update_option().
static delete_field ($form_id, $field_id) static
Fires after a field is deleted
Parameters
int $form_id The form ID where the form was deleted
int $field_id The ID of the field that was deleted
Definition at line 1145 of file forms_model.php.
References $columns, $count, $field, $field_id, $form, $form_id, $i, $wpdb, do_action(), and null.
static delete_file ($entry_id, $field_id, $file_index = 0) static
Definition at line 1091 of file forms_model.php.
References $field, $field_id, $form, $form_id, and $wpdb.
Referenced by GFForms\delete_file().
static delete_files ($lead_id, $form = null) static
Definition at line 1032 of file forms_model.php.
References $field, $file, $form, $value, and null.
static delete_files_by_form ($form_id, $status = '') static
Definition at line 1067 of file forms_model.php.
References $form, $form_id, $wpdb, and ARRAY_A.
static delete_form ($form_id) static
Definition at line 855 of file forms_model.php.
References $form_id, $wpdb, and do_action().
Referenced by GFFormList\form_list_page().
static delete_forms ($forms) static
Definition at line 753 of file forms_model.php.
References $form_id, and $forms.
Referenced by GFAPI\delete_forms(), and GFFormList\form_list_page().
static delete_incomplete_submission ($token) static
Definition at line 1987 of file forms_model.php.
References $wpdb.
Referenced by GFFormDisplay\handle_submission().
static delete_lead ($lead_id) static
Definition at line 1266 of file forms_model.php.
References $wpdb, do_action(), and gform_delete_meta().
Referenced by GFAPI\delete_entry(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), and GFForms\update_lead_status().
static delete_leads ($leads) static
Definition at line 747 of file forms_model.php.
References $leads.
Referenced by GFEntryList\leads_page().
static delete_leads_by_form ($form_id, $status = '') static
Fires when you delete entries for a specific form
Parameters
int $form_id The form ID to specify from which form to delete entries
string $status Allows you to set the form entries to a deleted status
Definition at line 771 of file forms_model.php.
References $form_id, $wpdb, and do_action().
Referenced by GFFormList\form_list_page(), and GFEntryList\leads_page().
static delete_note ($note_id) static
Fires before a note is deleted
Parameters
int $note_id The Current note ID
int $lead_id The current lead ID
Definition at line 1320 of file forms_model.php.
References $wpdb, and do_action().
Referenced by GravityView_Entry_Notes\delete_note().
static delete_notes ($notes) static
Definition at line 1339 of file forms_model.php.
Referenced by GravityView_Entry_Notes\delete_notes(), and GFEntryDetail\lead_detail_page().
static delete_password ($entry, $form) static
Definition at line 5070 of file forms_model.php.
References $form, and GFAPI\update_entry().
static delete_physical_file ($file_url) static private
Definition at line 1126 of file forms_model.php.
References $ary, $url, get_site_option(), is_multisite(), str_replace, and WP_CONTENT_DIR.
static delete_views ($form_id) static
Definition at line 843 of file forms_model.php.
References $form_id, $wpdb, and do_action().
Referenced by GFFormList\form_list_page().
static drop_tables () static
Definition at line 3290 of file forms_model.php.
References $wpdb.
Referenced by gravityview_shutdown(), and GFSettings\settings_uninstall_page().
static duplicate_form ($form_id) static
Fires after a form is duplicated
Parameters
int $form_id The original form's ID
int $new_id The ID of the new, duplicated form
Definition at line 918 of file forms_model.php.
References $count, $form, $form_id, $title, $wpdb, do_action(), and esc_html__().
Referenced by GFFormList\form_list_page().
static ensure_tables_exist () static
Definition at line 981 of file forms_model.php.
References $wpdb, get_current_blog_id(), and GFForms\setup_database().
Referenced by save_new_form().
static flush_confirmations () static
Definition at line 38 of file forms_model.php.
References null.
static flush_current_forms () static
Definition at line 30 of file forms_model.php.
References null.
Referenced by delete_confirmation().
static flush_current_lead () static
Definition at line 34 of file forms_model.php.
References null.
static get_choice_text ($field, $value, $input_id = 0) static
Definition at line 2537 of file forms_model.php.
References $field, and $value.
Referenced by GF_Field_Select\get_value_merge_tag(), GF_Field_Checkbox\get_value_merge_tag(), and GF_Field_Radio\get_value_merge_tag().
static get_current_lead () static
Return the current lead being processed.
Should only be called when a form has been submitted. If called before the "real" lead has been saved to the database, uses self::create_lead() to create a temporary lead to work with.
Definition at line 4090 of file forms_model.php.
References $form, $form_id, and absint().
Referenced by GFFormDisplay\maybe_add_review_page(), and GFFormDisplay\process_form().
static get_current_page_url ($force_ssl = false) static
Definition at line 4023 of file forms_model.php.
References $_SERVER, and GFForms\get().
Referenced by GFAPI\add_entry(), GF_Field_CreditCard\get_form_inline_script_on_page_render(), GFFormDisplay\process_form(), GFFormDisplay\replace_save_variables(), and GFAPI\update_entry().
static get_custom_choices () static
Definition at line 1921 of file forms_model.php.
References get_option().
static get_custom_field ($form, $meta_name, $meta_index) static private
Definition at line 2836 of file forms_model.php.
References $field, and $form.
static get_custom_field_names () static
Definition at line 2328 of file forms_model.php.
References $keys, and $wpdb.
static get_date_range_where ($search_criteria) static private
Definition at line 4723 of file forms_model.php.
References $wpdb.
static get_db_charset () static
Definition at line 4866 of file forms_model.php.
References $charset_collate, and $wpdb.
Referenced by GFPaymentAddOn\upgrade_payment().
static get_default_post_title () static private
Definition at line 2361 of file forms_model.php.
References $count, $title, and $wpdb.
static get_default_value ($field, $input_id) static
Definition at line 2181 of file forms_model.php.
References $count, $field, $i, and get_input().
static get_encrypted_fields ($entry_id) static
Definition at line 5025 of file forms_model.php.
References gform_get_meta().
static get_entry_meta ($form_ids) static
Definition at line 4188 of file forms_model.php.
References $form_id, and apply_filters().
Referenced by GFAPI\add_entry(), build_lead_array(), GFFormSettings\confirmations_edit_page(), GVCommon\get_entry_meta(), GFExport\get_entry_meta(), get_grid_columns(), get_selectable_entry_meta(), notification_edit_page(), sort_by_column_query(), and GFAPI\update_entry().
static get_field ($form, $field_id) static
Parameters
$form
$field_id
Returns
GF_Field
Definition at line 4057 of file forms_model.php.
References $field, $field_id, $form, and null.
Referenced by GravityView_Field_List\_filter_field_label(), GravityView_Field_Time\_get_time_format_for_field(), GravityView_frontend\_override_sorting_id_by_field_type(), create_post(), GravityView_API\field_label(), GFForms\fix_checkbox_value(), GFPaymentAddOn\get_column_value_amount(), GVCommon\get_field(), get_field_display(), GFAddOn\get_field_value(), get_field_value_long(), is_checkbox_checked(), GravityView_frontend\is_field_sortable(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), GFExport\start_export(), GravityView_API_Test\test_field_class(), trim_conditional_logic_values_from_element(), GFAPI\update_entry(), GFAPI\update_entry_field(), and GFAsyncUpload\upload().
static get_field_display ($form, $field, $field_values, $lead = null) static private
Parameters
$form
GF_Field $field
$field_values
null $lead
Returns
string
Definition at line 1889 of file forms_model.php.
References $field, $form, and get_field().
static get_field_filters_where ($form_id, $search_criteria) static private
Definition at line 4489 of file forms_model.php.
References $field, $form, $form_id, $forms, $id, $wpdb, elseif, GFAPI\get_form(), GFAPI\get_forms(), get_lead_details_table_name(), and get_lead_meta_table_name().
static get_field_merge_tag ($form, $field_id) static private
Definition at line 524 of file forms_model.php.
References $field, $field_id, and $form.
static get_field_value (& $field, $field_values = array(), $get_from_post = true) static
Parameters
GF_Field $field
array $field_values
bool $get_from_post Whether to get the value from the $_POST array as opposed to $field_values
Returns
array|mixed|string|void
Definition at line 1959 of file forms_model.php.
References $field, $value, and GF_Fields\create().
Referenced by GravityView_Edit_Entry_Render\custom_validation(), GravityView_Edit_Entry_Render\get_field_value(), GFFormDisplay\get_form(), GFFormDisplay\get_state(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), save_incomplete_submission(), and GFFormDisplay\validate().
static get_field_value_long ($lead, $field_number, $form, $apply_filter = true) static
Definition at line 3499 of file forms_model.php.
References $field, $form, $wpdb, and get_field().
Referenced by build_lead_array().
static get_fields_by_type ($form, $types, $use_input_type = false) static
Returns an array containing the form fields of the specified type or types.
Since
1.9.9.10
Parameters
array $form
array | string $types
bool $use_input_type
Returns
GF_Field[]
Definition at line 5235 of file forms_model.php.
References $field, $form, and $types.
Referenced by GFAPI\get_fields_by_type().
static get_file_upload_path ($form_id, $file_name) static
Definition at line 3209 of file forms_model.php.
References $form_id, absint(), current_time(), sanitize_file_name(), str_replace, and wp_mkdir_p().
Referenced by GF_Field_FileUpload\move_temp_file(), and GF_Field_FileUpload\upload_file().
static get_fileupload_value ($form_id, $input_name) static
Definition at line 2470 of file forms_model.php.
References $form_id, and _deprecated_function().
static get_form ($form_id, $allow_trash = false) static
Definition at line 307 of file forms_model.php.
References $form_id, and $wpdb.
Referenced by GFAPI\get_form(), GFFormDisplay\get_form(), and GFForms\maybe_process_form().
static get_form_confirmations ($form_id) static
Definition at line 4154 of file forms_model.php.
References $_confirmations, $form_id, $wpdb, ARRAY_A, and get_meta_table_name().
static get_form_count () static
Definition at line 274 of file forms_model.php.
References $wpdb.
Referenced by GFFormList\form_list_page().
static get_form_counts ($form_id) static
Definition at line 201 of file forms_model.php.
References $form_id, $wpdb, and ARRAY_A.
Referenced by GFEntryList\get_filter_links().
static get_form_db_columns () static
Definition at line 162 of file forms_model.php.
Referenced by GFFormList\form_list_page(), and GFAPI\update_forms_property().
static get_form_id ($form_title) static
Definition at line 295 of file forms_model.php.
References $form, $forms, and str_replace.
Referenced by GFFormDisplay\get_embedded_forms(), and GFFormDisplay\get_form().
static get_form_id_where ($form_id) static private
Definition at line 4414 of file forms_model.php.
References $form_id, and $wpdb.
static get_form_ids ($active = true, $trash = false) static
Definition at line 4179 of file forms_model.php.
References $wpdb.
Referenced by GFAPI\get_forms().
static get_form_meta ($form_id) static
Definition at line 327 of file forms_model.php.
References $form, $form_id, $wpdb, ARRAY_A, get_current_blog_id(), and null.
Referenced by GFAPI\add_entry(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), build_lead_array(), GFFormSettings\confirmations_edit_page(), GFFormSettings\confirmations_list_page(), delete_confirmation(), GFForms\enqueue_form_scripts(), GFForms\fix_checkbox_value(), GFFormDisplay\footer_init_scripts(), GFFormSettings\form_settings_ui(), get_confirmation_ui_settings(), GFAddOn\get_current_form(), GFFormDisplay\get_embedded_forms(), GVCommon\get_form(), GFAPI\get_form(), get_lead_field_value(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GFExport\maybe_export(), notification_edit_page(), page_header(), GFFormDisplay\process_send_resume_link(), GFForms\resend_notifications(), GFSelectColumns\select_columns_page(), GFForms\select_export_form(), GFFeedAddOn\trim_conditional_logic_vales(), update_confirmation_active(), GFAPI\update_entry(), and update_notification_active().
static get_form_meta_by_id ($ids) static
Definition at line 391 of file forms_model.php.
References $form, $wpdb, and ARRAY_A.
Referenced by GFExport\maybe_export().
static get_form_payment_totals ($form_id) static
Definition at line 172 of file forms_model.php.
References $form_id, $wpdb, and ARRAY_A.
static get_form_summary () static
Definition at line 222 of file forms_model.php.
References $count, $forms, $i, $wpdb, and ARRAY_A.
Referenced by GFForms\dashboard().
static get_form_table_name () static
Definition at line 42 of file forms_model.php.
References $wpdb.
Referenced by GFAPI\form_id_exists(), is_valid_table(), GFForms\setup_database(), and GFAPI\update_forms_property().
static get_form_unique_id ($form_id) static
Definition at line 2500 of file forms_model.php.
References $form_id, and elseif.
Referenced by GFFormDisplay\gform_footer(), and GFFormDisplay\process_form().
static get_form_view_table_name () static
Definition at line 54 of file forms_model.php.
References $wpdb.
Referenced by is_valid_table(), and GFForms\setup_database().
static get_forms ($is_active = null, $sort_column = 'title', $sort_dir = 'ASC', $is_trash = false) static
Definition at line 102 of file forms_model.php.
References $count, $form, $forms, $wpdb, and null.
Referenced by GFEntryList\all_leads_page(), GFExport\export_form_page(), GFExport\export_lead_page(), GFFormList\form_list_page(), GFForms\get_shortcodes(), and GFForms\top_toolbar().
static get_forms_by_id ($ids) static
Definition at line 166 of file forms_model.php.
References _deprecated_function().
static get_grid_column_meta ($form_id) static
Definition at line 558 of file forms_model.php.
References $form_id, $wpdb, and maybe_unserialize().
static get_grid_columns ($form_id, $input_label_only = false) static
Definition at line 3878 of file forms_model.php.
References $columns, $field, $field_id, $field_ids, $form, $form_id, apply_filters(), esc_html__(), and get_entry_meta().
Referenced by GFEntryList\leads_page(), and sort_by_default_field_query().
static get_incomplete_submission_values ($token) static
Definition at line 2123 of file forms_model.php.
References $wpdb, and ARRAY_A.
Referenced by GFFormDisplay\get_form(), GFFormDisplay\handle_save_email_confirmation(), and GFFormDisplay\process_send_resume_link().
static get_incomplete_submissions_table_name () static
Definition at line 96 of file forms_model.php.
References $wpdb.
Referenced by is_valid_table(), and GFForms\setup_database().
static get_info_search_where ($search_criteria) static private
Definition at line 4767 of file forms_model.php.
References $value, and $wpdb.
static get_input ($field, $id) static
Parameters
GF_Field $field
$id
Returns
null
Definition at line 3997 of file forms_model.php.
References $field, $id, and null.
Referenced by GravityView_API\field_label(), GF_Field_Name\get_css_class(), GF_Field_Address\get_css_class(), get_default_value(), GF_Field_Name\get_field_input(), GF_Field_Password\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_Name\get_input_property(), GF_Field_Address\get_input_property(), and GF_Field_Address\get_state_field().
static get_input_masks () static
Definition at line 2346 of file forms_model.php.
References apply_filters().
static get_input_type ($field) static
Parameters
GF_Field $field
Returns
string
Definition at line 2217 of file forms_model.php.
References $field.
Referenced by GFPaymentAddOn\add_creditcard_token_input(), choice_value_match(), GFExport\cleanup(), create_post(), GravityView_Edit_Entry_Render\custom_validation(), GravityView_API\field_value(), GFFormDisplay\get_chosen_init_script(), GFFormDisplay\get_field(), GFFormDisplay\get_field_content(), GVCommon\get_field_type(), GFFormDisplay\get_number_formats_script(), get_parameter_value(), GFFormDisplay\has_currency_format_number_field(), GFFormDisplay\has_datepicker_field(), GFFormDisplay\has_enhanced_dropdown(), GFFormDisplay\has_field_input_mask(), GFFormDisplay\has_fileupload_field(), GFFormDisplay\has_price_field(), is_duplicate(), GFEntryList\leads_page(), GFExport\maybe_export(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), GFAPI\update_entry(), GFAsyncUpload\upload(), GFFormDisplay\upload_files(), and GFFormDisplay\validate().
static get_ip () static
Definition at line 1349 of file forms_model.php.
References $_SERVER.
Referenced by GFAPI\add_entry(), GFFormDisplay\process_form(), and GFAPI\update_entry().
static get_label ($field, $input_id = 0, $input_only = false, $allow_admin_label = true) static
Parameters
GF_Field $field
int $input_id
bool $input_only
Returns
string
Definition at line 3976 of file forms_model.php.
References $field, GF_Fields\create(), and null.
Referenced by GFPaymentAddOn\get_payment_choices().
static get_lead ($lead_id) static
Definition at line 3387 of file forms_model.php.
References $leads, and $wpdb.
Referenced by GravityView_Edit_Entry_Render\after_update(), GFAPI\delete_entry(), GF_Field_Total\get_value_save_entry(), GF_Field_Calculation\get_value_save_entry(), GF_Field_Number\get_value_save_entry(), GFFormDisplay\handle_submission(), GFEntryDetail\lead_detail_page(), GFForms\resend_notifications(), and save_lead().
static get_lead_count ($form_id, $search, $star = null, $read = null, $start_date = null, $end_date = null, $status = null, $payment_status = null) static
Definition at line 3827 of file forms_model.php.
References $form_id, and $wpdb.
Referenced by GFFormDisplay\validate_entry_limit().
static get_lead_count_all_forms ($status = 'active') static
Definition at line 4840 of file forms_model.php.
References $wpdb.
static get_lead_db_columns () static private
Definition at line 4763 of file forms_model.php.
static get_lead_detail_id ($current_fields, $field_number) static
Definition at line 574 of file forms_model.php.
References $field.
Referenced by GFAPI\update_entry().
static get_lead_details_long_table_name () static
Definition at line 84 of file forms_model.php.
References $wpdb.
Referenced by GFForms\fix_leading_and_trailing_spaces(), is_valid_table(), and GFForms\setup_database().
static get_lead_details_table_name () static
Definition at line 78 of file forms_model.php.
References $wpdb.
Referenced by count_search_leads(), GFForms\fix_checkbox_value(), GFForms\fix_leading_and_trailing_spaces(), get_field_filters_where(), is_valid_table(), search_lead_ids(), GFForms\setup_database(), sort_by_column_query(), sort_by_field_query(), GFAPI\update_entry(), and GFAPI\update_entry_field().
static get_lead_field_value ($lead, $field) static
Parameters
$lead
$field GF_Field
Returns
array|bool|mixed|string|void
Definition at line 3431 of file forms_model.php.
References $field, $field_id, $form, $value, absint(), apply_filters(), get_form_meta(), and GFORMS_MAX_FIELD_LENGTH.
Referenced by GVCommon\check_entry_display(), GravityView_API\field_value(), GFEntryDetail\lead_detail_edit(), and GFEntryDetail\lead_detail_grid().
static get_lead_ids ($form_id, $search, $star = null, $read = null, $start_date = null, $end_date = null, $status = null, $payment_status = null) static
Definition at line 3847 of file forms_model.php.
References $form_id, and $wpdb.
static get_lead_meta_table_name () static
Definition at line 66 of file forms_model.php.
References $wpdb.
Referenced by GravityView_Uninstall\delete_entry_meta(), GFForms\fix_lead_meta_form_id_values(), get_field_filters_where(), gform_add_meta(), gform_delete_meta(), gform_get_meta(), gform_get_meta_values_for_entries(), gform_update_meta(), is_valid_table(), GFForms\setup_database(), and sort_by_column_query().
static get_lead_notes ($lead_id) static
Definition at line 3406 of file forms_model.php.
References $wpdb.
Referenced by GravityView_Entry_Notes\get_notes(), gform_default_entry_content(), and GFEntryDetail\lead_detail_page().
static get_lead_notes_table_name () static
Definition at line 72 of file forms_model.php.
References $wpdb.
Referenced by GravityView_Uninstall\delete_entry_notes(), is_valid_table(), and GFForms\setup_database().
static get_lead_table_name () static
Definition at line 60 of file forms_model.php.
References $wpdb.
Referenced by GFAPI\add_entry(), count_search_leads(), GFForms\fix_lead_meta_form_id_values(), gform_add_meta(), gform_update_meta(), is_valid_table(), save_lead(), search_lead_ids(), GFForms\setup_database(), sort_by_column_query(), sort_by_field_query(), and GFAPI\update_entry().
static get_lead_view_name () static
Definition at line 90 of file forms_model.php.
References $wpdb.
static get_leads ($form_id, $sort_field_number = 0, $sort_direction = 'DESC', $search = '', $offset = 0, $page_size = 30, $star = null, $read = null, $is_numeric_sort = false, $start_date = null, $end_date = null, $status = 'active', $payment_status = false) static
Definition at line 3540 of file forms_model.php.
References $form_id, $leads, and $wpdb.
static get_leads_by_meta ($meta_key, $meta_value) static
Definition at line 3522 of file forms_model.php.
References $leads, and $wpdb.
static get_leads_count ($form_id) static
Definition at line 3564 of file forms_model.php.
static get_leads_where_sql ($args) static
Definition at line 3677 of file forms_model.php.
References $wpdb, null, and wp_parse_args().
static get_meta_table_name () static
Definition at line 48 of file forms_model.php.
References $wpdb.
Referenced by GFForms\fix_leading_and_trailing_spaces(), get_form_confirmations(), is_valid_table(), GFForms\setup_database(), and GFAPI\update_form().
static get_page_by_number ($form, $page_number) static
Definition at line 1740 of file forms_model.php.
References $field, $form, and null.
static get_parameter_value ($name, $field_values, $field) static
Definition at line 2155 of file forms_model.php.
References $field, $name, $value, and get_input_type().
Referenced by GFFormDisplay\get_conditional_logic(), GF_Field\get_input_value_submission(), GF_Field_Checkbox\get_value_submission(), and GravityView_Edit_Entry_Render\modify_edit_field_input().
static get_post_field_value ($field, $lead) static private
Definition at line 2226 of file forms_model.php.
References $field, $value, and str_replace.
static get_post_fields ($form, $lead) static private
Definition at line 2250 of file forms_model.php.
References $ary, $caption, $description, $field, $form, $tags, $title, $url, and $value.
static get_prepared_input_value ($form, $field, $lead, $input_id) static
Definition at line 1599 of file forms_model.php.
References $field, $form, $url, $value, and str_replace.
static get_search_operator ($search_criteria) static private
Definition at line 4752 of file forms_model.php.
static get_search_where ($form_id, $search_criteria) static private
Definition at line 4428 of file forms_model.php.
References $form_id, and $wpdb.
static get_section ($form, $field_id) static
Definition at line 1751 of file forms_model.php.
References $field, $field_id, $form, and null.
Referenced by GFFormDisplay\get_conditional_logic().
static get_submitted_fields ($form_id) static
Definition at line 4035 of file forms_model.php.
References $field, $form_id, and $wpdb.
static get_tables () static
Definition at line 3276 of file forms_model.php.
static get_temp_filename ($form_id, $input_name) static
Definition at line 2518 of file forms_model.php.
References $form_id.
Referenced by GF_Field_Post_Image\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_FileUpload\get_single_file_value(), GF_Field_FileUpload\is_value_submission_empty(), and GFFormDisplay\upload_files().
static get_upload_path ($form_id) static
Definition at line 3197 of file forms_model.php.
References $form_id, and absint().
Referenced by GFFormDisplay\clean_up_files(), GF_Field_FileUpload\get_multifile_value(), GF_Field_CAPTCHA\get_simple_captcha(), GF_Field_FileUpload\get_single_file_value(), GF_Field_FileUpload\move_temp_file(), GFAsyncUpload\upload(), and GFFormDisplay\upload_files().
static get_upload_root () static
Definition at line 3177 of file forms_model.php.
References $dir, null, and wp_upload_dir().
Referenced by GFForms\add_security_files(), GFForms\check_upload_folder(), GFForms\do_self_healing(), GFSettings\settings_uninstall_page(), and GFAsyncUpload\upload().
static get_upload_url ($form_id) static
Definition at line 3202 of file forms_model.php.
References $dir, $form_id, absint(), and wp_upload_dir().
Referenced by GF_Field_CAPTCHA\get_captcha(), and GF_Field_CAPTCHA\get_math_captcha().
static get_upload_url_root () static
Definition at line 3187 of file forms_model.php.
References $dir, null, and wp_upload_dir().
static get_uuid ($s = '') static
Returns a UUID.
Uses openssl_random_pseudo_bytes() if available and falls back to mt_rand().
source: http://stackoverflow.com/questions/2040240/php-function-to-generate-v4-uuid
Parameters
string $s The separator e.g. '-'
Returns
string
Definition at line 2089 of file forms_model.php.
static has_input ($field, $input_id) static
Definition at line 4009 of file forms_model.php.
References $field.
static insert_form ($form_title) static
Definition at line 991 of file forms_model.php.
References $wpdb.
Referenced by GFAPI\add_form(), and GFExport\import_xml().
static insert_form_view ($form_id, $ip) static
Definition at line 3301 of file forms_model.php.
References $form_id, $id, and $wpdb.
Referenced by GFFormDisplay\get_form().
static is_checkbox_checked ($field_id, $field_label, $lead, $form) static
Definition at line 2437 of file forms_model.php.
References $ary, $field, $field_id, $form, absint(), and get_field().
static is_duplicate ($form_id, $field, $value) static
Definition at line 3323 of file forms_model.php.
References $count, $field, $form_id, $value, $wpdb, get_input_type(), GFORMS_MAX_FIELD_LENGTH, null, and str_replace.
Referenced by GFFormDisplay\validate().
static is_encrypted_field ($entry_id, $field_id) static
Determines if an entry field is stored encrypted. Use this hook to change the default behavior of decrypting fields that have been encrypted or to completely disable the process if checking for encrypted fields.
Parameters
int $entry_id The current Entry ID
int $field_id The current Field ID.
Definition at line 5051 of file forms_model.php.
References $field_id, and apply_filters().
static is_field_hidden ($form, $field, $field_values, $lead = null) static
Check whether a field is hidden via conditional logic.
Parameters
array $form Form object.
GF_Field $field Field object.
array $field_values Default field values for this form. Used when form has not yet been submitted. Pass an array if no default field values are available/required.
array $lead Optional, default is null. If lead object is available, pass the lead.
Returns
mixed
Definition at line 1697 of file forms_model.php.
References $field, and $form.
Referenced by create_lead(), GF_Field_Select\get_value_merge_tag(), GF_Field_Checkbox\get_value_merge_tag(), GF_Field_Radio\get_value_merge_tag(), save_lead(), and GFFormDisplay\validate().
static is_html5_enabled () static
Definition at line 4081 of file forms_model.php.
References get_option().
Referenced by GF_Field_Calculation\get_field_input(), GF_Field_SingleProduct\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_Number\get_field_input(), GFFormDisplay\get_form(), GFFormDisplay\get_form_button(), and GFFormDisplay\replace_save_variables().
static is_page_hidden ($form, $page_number, $field_values, $lead = null) static
Definition at line 1728 of file forms_model.php.
References $form, and $page.
Referenced by GFFormDisplay\get_target_page().
static is_unique_title ($title) static
Definition at line 970 of file forms_model.php.
References $form, $forms, and $title.
Referenced by GFAPI\add_form(), and GFExport\import_xml().
static is_valid_index ($index_name) static
Definition at line 4893 of file forms_model.php.
Referenced by GFForms\drop_index().
static is_valid_operator ($operator) static
Definition at line 5256 of file forms_model.php.
static is_valid_table ($table_name) static
Definition at line 4880 of file forms_model.php.
References $wpdb, get_form_table_name(), get_form_view_table_name(), get_incomplete_submissions_table_name(), get_lead_details_long_table_name(), get_lead_details_table_name(), get_lead_meta_table_name(), get_lead_notes_table_name(), get_lead_table_name(), and get_meta_table_name().
Referenced by GFForms\drop_index().
static is_value_match ($field_value, $target_value, $operation = 'is', $source_field = null, $rule = null, $form = null) static
Definition at line 1771 of file forms_model.php.
References $form_id, apply_filters(), and maybe_trim_input().
Referenced by GVCommon\check_entry_display().
static load_confirmations ($form) static
Definition at line 4140 of file forms_model.php.
References $form.
static load_notifications_from_legacy ($form) static private
Definition at line 455 of file forms_model.php.
References $form, and esc_html__().
static load_notifications_to_legacy ($form) static private
Definition at line 421 of file forms_model.php.
References $form.
static matches_operation ($val1, $val2, $operation) static
Definition at line 1827 of file forms_model.php.
Referenced by GVCommon\matches_operation().
static maybe_sanitize_form_settings ($form) static
Definition at line 5082 of file forms_model.php.
References $form.
Referenced by GFFormSettings\form_settings_ui().
static maybe_trim_input ($value, $form_id, $field) static
Definition at line 2145 of file forms_model.php.
References $field, $form_id, $value, and apply_filters().
Referenced by choice_value_match(), GF_Field\get_input_value_submission(), GFFormDisplay\get_state(), and is_value_match().
static media_handle_upload ($url, $post_id, $post_data = array()) static private
Definition at line 2921 of file forms_model.php.
References $content, $file, $id, $image_meta, $name, $post_id, $title, $url, ABSPATH, is_wp_error(), sanitize_title(), wp_generate_attachment_metadata(), wp_insert_attachment(), wp_read_image_metadata(), and wp_update_attachment_metadata().
static move_temp_file ($form_id, $tempfile_info) static private
Definition at line 3132 of file forms_model.php.
References $form_id, and _deprecated_function().
static mu_drop_tables ($drop_tables) static
Definition at line 3297 of file forms_model.php.
static prepare_date ($date_format, $value) static
Definition at line 2376 of file forms_model.php.
References $date_format, $format, and $value.
Referenced by GF_Field_Date\get_value_save_entry().
static prepare_value ($form, $field, $value, $input_name, $lead_id, $lead = array()) static
Prepare the value before saving it to the lead.
Parameters
mixed $form
GF_Field $field
mixed $value
mixed $input_name
mixed $lead_id the current lead ID, used for fields that are processed after other fields have been saved (ie Total, Calculations)
mixed $lead passed by the RGFormsModel::create_lead() method, lead ID is not available for leads created by this function
Returns
mixed
Definition at line 2400 of file forms_model.php.
References $ary, $field, $form, $label, $value, get_term(), and is_wp_error().
Referenced by GravityView_Edit_Entry_Render\maybe_update_post_fields().
static purge_expired_incomplete_submissions ($expiration_days = 30) static
Definition at line 1974 of file forms_model.php.
References $wpdb, and apply_filters().
Referenced by GFFormDisplay\handle_submission().
static refresh_lead_field_value ($lead_id, $field_id) static
Definition at line 3420 of file forms_model.php.
References $field_id.
Referenced by GravityView_Edit_Entry_Render\after_update().
static refresh_product_cache ($form, $lead, $use_choice_text = false, $use_admin_label = false) static
Definition at line 1659 of file forms_model.php.
References $field, $form, gform_delete_meta(), and gform_get_meta().
static restore_form ($form_id) static
Definition at line 901 of file forms_model.php.
References $form_id, $wpdb, do_action(), get_current_blog_id(), and null.
Referenced by GFFormList\form_list_page().
static restore_forms ($form_ids) static
Definition at line 765 of file forms_model.php.
References $form_id.
Referenced by GFFormList\form_list_page().
static sanitize_conditional_logic ($logic) static
Definition at line 5190 of file forms_model.php.
References apply_filters(), and wp_strip_all_tags().
Referenced by handle_confirmation_edit_submission(), notification_edit_page(), and GF_Field\sanitize_settings_conditional_logic().
static sanitize_settings ($form) static
Definition at line 5089 of file forms_model.php.
References $field, $form, GFForms\$version, absint(), apply_filters(), sanitize_text_field(), wp_kses(), and wp_kses_allowed_html().
static save_custom_choice ($previous_name, $new_name, $choices) static
Definition at line 1939 of file forms_model.php.
References update_option().
static save_form_confirmations ($form_id, $confirmations) static
Definition at line 4171 of file forms_model.php.
References $form_id.
Referenced by activate_save(), deactivate_save(), delete_confirmation(), and handle_confirmation_edit_submission().
static save_form_notifications ($form_id, $notifications) static
Definition at line 4175 of file forms_model.php.
References $form_id.
Referenced by activate_save(), deactivate_save(), and notification_edit_page().
static save_incomplete_submission ($form, $entry, $field_values, $page_number, $files, $form_unique_id, $ip, $source_url, $resume_token = '') static
Definition at line 1996 of file forms_model.php.
References $count, $field, $form, $wpdb, apply_filters(), current_time(), do_action(), and get_field_value().
Referenced by GFFormDisplay\process_form().
static save_input ($form, $field, & $lead, $current_fields, $input_id) static
Definition at line 2973 of file forms_model.php.
References $field, $form, $form_id, $uploaded_files, $value, null, RG_CURRENT_VIEW, and str_replace.
static save_key ($key) static
Definition at line 3817 of file forms_model.php.
References delete_option(), get_option(), and update_option().
Referenced by GFForms\maybe_populate_keys().
static save_lead ($form, & $lead) static
Allow the currency code to be overridden.
Parameters
string $currency The three character ISO currency code to be stored in the entry. Default is value returned by GFCommon::get_currency()
array $form The form currently being processed.
Definition at line 1367 of file forms_model.php.
References $_SERVER, $current_user, $field, $form, $user_id, $wpdb, esc_html__(), get_lead(), get_lead_table_name(), is_field_hidden(), null, RG_CURRENT_VIEW, and sanitize_text_field().
Referenced by GFFormDisplay\handle_submission(), GFEntryDetail\lead_detail_page(), and GravityView_Edit_Entry_Render\process_save().
static search_lead_ids ($form_id, $search_criteria = array()) static
Definition at line 4249 of file forms_model.php.
References $form_id, $wpdb, get_lead_details_table_name(), and get_lead_table_name().
Referenced by GVCommon\get_entry_ids(), GFEntryList\leads_page(), and GFForms\resend_notifications().
static search_leads ($form_id, $search_criteria = array(), $sorting = null, $paging = null) static
Definition at line 4225 of file forms_model.php.
References $form_id, $leads, $wpdb, and build_lead_array().
Referenced by GFAPI\get_entries().
static set_current_lead ($lead) static
Set RGFormsModel::$lead for use in hooks where $lead is not explicitly passed.
Parameters
mixed $lead
Definition at line 4111 of file forms_model.php.
Referenced by GFFormDisplay\handle_submission().
static set_encrypted_fields ($entry_id, $field_ids) static
Definition at line 5038 of file forms_model.php.
References $field_ids, and gform_update_meta().
Referenced by GF_Field_Password\get_value_save_entry().
static set_entry_meta ($lead, $form) static
Definition at line 4210 of file forms_model.php.
References $form, $keys, $value, and gform_update_meta().
Referenced by GravityView_Edit_Entry_Render\after_update(), GFFormDisplay\handle_submission(), and GFEntryDetail\lead_detail_page().
static set_permissions ($path) static
Definition at line 3147 of file forms_model.php.
References $path, and apply_filters().
Referenced by GF_Field_FileUpload\set_permissions(), GFAsyncUpload\upload(), and GFFormDisplay\upload_files().
static sort_by_column_query ($form_id, $search_criteria, $sorting, $paging) static private
Definition at line 4342 of file forms_model.php.
References $form_id, $wpdb, get_entry_meta(), get_lead_details_table_name(), get_lead_meta_table_name(), and get_lead_table_name().
static sort_by_custom_field_query ($form_id, $sort_field_number = 0, $sort_direction = 'DESC', $search = '', $offset = 0, $page_size = 30, $star = null, $read = null, $is_numeric_sort = false, $status = 'active', $payment_status = false) static private
Definition at line 3567 of file forms_model.php.
References $form_id, and $wpdb.
static sort_by_default_field_query ($form_id, $sort_field, $sort_direction = 'DESC', $search = '', $offset = 0, $page_size = 30, $star = null, $read = null, $is_numeric_sort = false, $start_date = null, $end_date = null, $status = 'active', $payment_status = false) static private
Definition at line 3620 of file forms_model.php.
References $form_id, $wpdb, and get_grid_columns().
static sort_by_field_query ($form_id, $search_criteria, $sorting, $paging) static private
Definition at line 4276 of file forms_model.php.
References $form_id, $wpdb, get_lead_details_table_name(), and get_lead_table_name().
static trash_form ($form_id) static
Fires after a form is trashed
Parameters
int $form_id The ID of a form you can can check which form was trashed
Definition at line 880 of file forms_model.php.
References $form_id, $wpdb, do_action(), get_current_blog_id(), and null.
Referenced by GFFormList\form_list_page().
static trash_forms ($form_ids) static
Definition at line 759 of file forms_model.php.
References $form_id.
Referenced by GFFormList\form_list_page().
static trim_conditional_logic_values ($meta_array, $form, & $updated = false) static
Trims values from an array of elements e.g.
notifications and confirmations
Parameters
array $meta_array Form object.
array $form Form object.
bool $updated Output parameter.
Returns
array $meta_array
Definition at line 4966 of file forms_model.php.
References $form, and $updated.
Referenced by GFForms\fix_leading_and_trailing_spaces(), GFExport\import_xml(), and trim_form_meta_values().
static trim_conditional_logic_values_from_element ($element, $form = array(), & $updated = false) static
Trims values from elements e.g.
fields, notifications and confirmations
Parameters
array $element Form object.
array $form Form object.
bool $updated Output parameter.
Returns
array $element
Definition at line 4989 of file forms_model.php.
References $field, $form, $updated, $value, apply_filters(), and get_field().
Referenced by handle_confirmation_edit_submission(), notification_edit_page(), and GFFeedAddOn\trim_conditional_logic_vales().
static trim_form_meta_values ($form, & $form_updated = false) static
Trims values inside choice texts, choice values, input labels, field labels and field conditionalLogic.
Parameters
array $form Form object.
bool $form_updated Output parameter.
Returns
array $form
Definition at line 4911 of file forms_model.php.
References $field, $form, $form_id, apply_filters(), and trim_conditional_logic_values().
Referenced by GFForms\fix_leading_and_trailing_spaces(), and GFExport\import_xml().
static truncate ($str, $length) static private
Definition at line 739 of file forms_model.php.
static try_convert_float ($text) static private
Definition at line 1806 of file forms_model.php.
References $text.
static unserialize ($string) static
Definition at line 316 of file forms_model.php.
References is_serialized().
Referenced by GFForms\fix_leading_and_trailing_spaces().
static update_confirmation_active ($form_id, $confirmation_id, $is_active) static
Definition at line 629 of file forms_model.php.
References $form, $form_id, __, get_form_meta(), and update_form_meta().
Referenced by GFForms\update_confirmation_active().
static update_form_active ($form_id, $is_active) static
Fires after an inactive form gets marked as active
Parameters
int $form_id The Form ID used to specify which form to activate
Fires after an active form gets marked as inactive
Parameters
int $form_id The Form ID used to specify which form to activate
Definition at line 584 of file forms_model.php.
References $form_id, $wpdb, and do_action().
Referenced by GFFormList\form_list_page(), and GFForms\update_form_active().
static update_form_meta ($form_id, $form_meta, $meta_name = 'display_meta') static
Fires after form meta has been updated for any form
Parameters
mixed $form_meta The Form Meta object from the database
int $form_id The ID of the form data was updated
string $meta_name The name of the meta updated
Definition at line 1003 of file forms_model.php.
References $form_id, $wpdb, get_current_blog_id(), and null.
Referenced by GFAPI\add_form(), GFForms\fix_leading_and_trailing_spaces(), GFExport\import_xml(), update_confirmation_active(), GFAPI\update_form(), and update_notification_active().
static update_forms_active ($forms, $is_active) static
Definition at line 645 of file forms_model.php.
References $form_id, and $forms.
static update_grid_column_meta ($form_id, $columns) static
Definition at line 566 of file forms_model.php.
References $columns, $form_id, $wpdb, maybe_serialize(), and stripslashes_deep().
Referenced by GFEntryList\leads_page().
static update_lead ($lead) static
Definition at line 698 of file forms_model.php.
References $wpdb, and _deprecated_function().
static update_lead_field_value ($form, $lead, $field, $lead_detail_id, $input_id, $value) static
Updates an existing field value in the database.
Parameters
array $form
array $lead
GF_Field $field
int $lead_detail_id
string $input_id
string $value
Returns
bool
Definition at line 3033 of file forms_model.php.
References $field, $form, $form_id, $value, $wpdb, get_option(), and GFORMS_MAX_FIELD_LENGTH.
Referenced by GFAPI\add_entry(), GFAPI\update_entry(), and GFAPI\update_entry_field().
static update_lead_property ($lead_id, $property_name, $property_value, $update_akismet = true, $disable_hook = false) static
Definition at line 657 of file forms_model.php.
References $form, $wpdb, do_action(), and GFAPI\get_form().
Referenced by GravityView_Change_Entry_Creator\assign_new_user_to_lead(), GFFormDisplay\handle_submission(), GFEntryDetail\lead_detail_page(), GravityView_Change_Entry_Creator\update_entry_creator(), GFAPI\update_entry_property(), GFForms\update_lead_property(), and GFForms\update_lead_status().
static update_leads_property ($leads, $property_name, $property_value) static
Definition at line 651 of file forms_model.php.
References $leads.
Referenced by GFEntryList\leads_page().
static update_notification_active ($form_id, $notification_id, $is_active) static
Definition at line 609 of file forms_model.php.
References $form, $form_id, __, do_action(), get_form_meta(), and update_form_meta().
Referenced by GFForms\update_notification_active().
static upload_file ($form_id, $file) static
Definition at line 3154 of file forms_model.php.
References $file, $form_id, and _deprecated_function().
Field Documentation
$_confirmations = array() static private
Definition at line 17 of file forms_model.php.
Referenced by get_form_confirmations().
array $_current_forms = array() static private
An in-memory cache for the form meta for the current blog.
Use "{Blog ID}_{Form ID}" as the key. Example: $_current_forms['1_2']
Definition at line 26 of file forms_model.php.
$_current_lead = null static private
Definition at line 28 of file forms_model.php.
$unique_ids = array() static
Definition at line 15 of file forms_model.php.
Referenced by GFFormDisplay\get_form(), and GFFormDisplay\gform_footer().
$uploaded_files = array() static
Definition at line 14 of file forms_model.php.
Referenced by GravityView_Edit_Entry_Render\custom_validation(), GF_Field_FileUpload\get_field_input(), GFFormDisplay\get_form(), GF_Field_FileUpload\get_multifile_value(), GFFormDisplay\gform_footer(), GF_Field_FileUpload\is_value_submission_empty(), GFEntryDetail\lead_detail_page(), GFFormDisplay\process_form(), GravityView_Edit_Entry_Render\process_save_process_files(), save_input(), and GF_Field_FileUpload\validate().
The documentation for this class was generated from the following file:
forms_model.php