GravityView: GF_Field Class Reference
GF_Field Class Reference
If this file is called directly, abort.
Public Member Functions
__get ($key)
A proxy getter for the backing GravityView field.
get_label (View $view=null, Source $source=null, Entry $entry=null, Request $request=null)
Retrieve the label for this field.
get_value (View $view=null, Source $source=null, Entry $entry=null, Request $request=null)
Retrieve the value for this field.
Public Member Functions inherited from Field
__get ($key)
Get one of the extra configuration keys via property accessors.
__isset ($key)
Is this set?
as_configuration ()
Return an array of the old format as used by callers of GVCommon:get_directory_fields() for example.
get_label (View $view=null, Source $source=null, Entry $entry=null, Request $request=null)
Retrieve the label for this field.
get_value (View $view=null, Source $source=null, Entry $entry=null, Request $request=null)
Retrieve the value for this field.
is_visible ($view=null)
Whether or not this field is visible.
update_configuration ($configuration)
Update configuration.
Static Public Member Functions
static by_id ($form, $field_id)
Get a by and Field ID.
static from_configuration ($configuration)
Create self from a configuration array.
Static Public Member Functions inherited from Field
static get ($source, $args)
An alias for ::get_field()
Data Fields
$field
Data Fields inherited from Field
$cap = ''
$custom_class = ''
$custom_label = ''
$ID = ''
$label = ''
$position = ''
$search_filter = false
$show_as_link = false
$show_label = true
$UID = ''
Additional Inherited Members
Protected Member Functions inherited from Field
get_value_filters ($value, View $view=null, Source $source=null, Entry $entry=null, Request $request=null)
Apply all the required filters after get_value() was called.
Detailed Description
If this file is called directly, abort.
The Gravity Forms {
See also
} field object wrapper.
Definition at line 12 of file class-gv-field-gravityforms.php.
Member Function Documentation
__get()
__get ($key)
A proxy getter for the backing GravityView field.
The view field configuration is checked first, though.
Parameters
string $key The property to get.
Returns
mixed The value of the Gravity View field property, or null if not exists.
Definition at line 161 of file class-gv-field-gravityforms.php.
References $value.
by_id()
static by_id ($form, $field_id) static
Get a by and Field ID.
Parameters
\GV\GF_Form $form The Gravity Form form.
int $field_id The Gravity Form field ID for the $form.
Returns
|null The requested field or null if not found.
Definition at line 59 of file class-gv-field-gravityforms.php.
References $field, $field_id, GV\$form, $gv_field, and gravityview().
Referenced by gvfield\callback(), GravityView_Field_Survey\field_options(), View\get_unions(), Views_Route\prepare_entry_for_response(), GravityView_Widget_Search\prepare_field_filter(), and View\template_redirect().
from_configuration()
static from_configuration ($configuration) static
Create self from a configuration array.
Parameters
array $configuration The configuration array.
See also
::as_configuration()
Definition at line 29 of file class-gv-field-gravityforms.php.
References $field, GV\$form, and gravityview().
get_label()
get_label (View $view = null, Source $source = null, Entry $entry = null, Request $request = null)
Retrieve the label for this field.
Requires a in this implementation.
Parameters
\GV\View $view The view for this context if applicable.
\GV\Source $source The source (form) for this context if applicable.
\GV\Entry $entry The entry for this context if applicable.
\GV\Request $request The request for this context if applicable.
Returns
string The label for this Gravity Forms field.
This is a complex Gravity Forms input.
This is a field with one label.
Definition at line 98 of file class-gv-field-gravityforms.php.
References $entry, $label, and gravityview().
get_value()
get_value (View $view = null, Source $source = null, Entry $entry = null, Request $request = null)
Retrieve the value for this field.
Requires a in this implementation.
Parameters
\GV\View $view The view for this context if applicable.
\GV\Source $source The source (form) for this context if applicable.
\GV\Entry $entry The entry for this context if applicable.
\GV\Request $request The request for this context if applicable.
Returns
mixed The value for this field.
Apply parent filters.
Definition at line 140 of file class-gv-field-gravityforms.php.
References $entry, $field, $value, and gravityview().
Field Documentation
$field
$field
Definition at line 17 of file class-gv-field-gravityforms.php.
The documentation for this class was generated from the following file:
class-gv-field-gravityforms.php