GravityView: NotGettexted Class Reference
NotGettexted Class Reference
Public Member Functions
cli ()
cli_die ($msg)
command_extract ()
command_replace ()
ignore_token ($token, $s= '')
list_php_files ($dir)
logmsg ()
make_mo_replacer ($global_mo_name)
make_string_aggregator ($global_array_name, $filename)
stderr ($msg, $nl=true)
unchanged_token ($token, $s= '')
usage ()
walk_tokens (&$tokens, $string_action, $other_action, $register_action=null)
Data Fields
$commands = array('extract' => 'command_extract', 'replace' => 'command_replace')
$enable_logging = false
$STAGE_END_COMMENT = 4
$STAGE_OUTSIDE = 0
$STAGE_START_COMMENT = 1
$STAGE_STRING = 3
$STAGE_WHITESPACE_AFTER = 4
$STAGE_WHITESPACE_BEFORE = 2
Detailed Description
Definition at line 21 of file not-gettexted.php.
Member Function Documentation
cli ()
Definition at line 227 of file not-gettexted.php.
References $commands, and usage().
cli_die ($msg)
Definition at line 44 of file not-gettexted.php.
References stderr().
Referenced by command_extract(), and command_replace().
command_extract ()
Definition at line 147 of file not-gettexted.php.
References $entry, cli_die(), make_string_aggregator(), and walk_tokens().
Referenced by MakePOT\wp_generic().
command_replace ()
Definition at line 188 of file not-gettexted.php.
References cli_die(), make_mo_replacer(), and walk_tokens().
ignore_token ($token, $s = '')
Definition at line 53 of file not-gettexted.php.
list_php_files ($dir)
Definition at line 57 of file not-gettexted.php.
Referenced by MakePOT\wp_generic().
logmsg ()
Definition at line 33 of file not-gettexted.php.
Referenced by walk_tokens().
make_mo_replacer ($global_mo_name)
Definition at line 80 of file not-gettexted.php.
Referenced by command_replace().
make_string_aggregator ($global_array_name, $filename)
Definition at line 75 of file not-gettexted.php.
Referenced by command_extract().
stderr ($msg, $nl = true)
Definition at line 40 of file not-gettexted.php.
Referenced by cli_die(), and usage().
unchanged_token ($token, $s = '')
Definition at line 49 of file not-gettexted.php.
usage ()
Definition at line 219 of file not-gettexted.php.
References stderr().
Referenced by cli().
walk_tokens (& $tokens, $string_action, $other_action, $register_action = null)
Definition at line 85 of file not-gettexted.php.
References $STAGE_END_COMMENT, $STAGE_OUTSIDE, $STAGE_START_COMMENT, $STAGE_WHITESPACE_AFTER, $STAGE_WHITESPACE_BEFORE, and logmsg().
Referenced by command_extract(), and command_replace().
Field Documentation
$commands = array('extract' => 'command_extract', 'replace' => 'command_replace')
Definition at line 31 of file not-gettexted.php.
Referenced by cli().
$enable_logging = false
Definition at line 22 of file not-gettexted.php.
$STAGE_END_COMMENT = 4
Definition at line 29 of file not-gettexted.php.
Referenced by walk_tokens().
$STAGE_OUTSIDE = 0
Definition at line 24 of file not-gettexted.php.
Referenced by walk_tokens().
$STAGE_START_COMMENT = 1
Definition at line 25 of file not-gettexted.php.
Referenced by walk_tokens().
$STAGE_STRING = 3
Definition at line 27 of file not-gettexted.php.
$STAGE_WHITESPACE_AFTER = 4
Definition at line 28 of file not-gettexted.php.
Referenced by walk_tokens().
$STAGE_WHITESPACE_BEFORE = 2
Definition at line 26 of file not-gettexted.php.
Referenced by walk_tokens().
The documentation for this class was generated from the following file:
not-gettexted.php