GravityView: WP_List_Table Class Reference
WP_List_Table Class Reference
Base class for displaying a list of items in an ajaxified HTML table.
Public Member Functions
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($args=array())
Constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
_js_vars ()
Send required variables to JavaScript land.
ajax_response ()
Handle an incoming ajax request (called from admin-ajax.php)
ajax_user_can ()
Checks the current user's permissions.
current_action ()
Get the current action selected from the bulk actions dropdown.
display ()
Display the table.
display_rows ()
Generate the table rows.
display_rows_or_placeholder ()
Generate the tbody element for the list table.
get_column_count ()
Return number of visible columns.
get_columns ()
Get a list of columns.
get_pagenum ()
Get the current page number.
get_pagination_arg ($key)
Access the pagination args.
get_primary_column ()
Public wrapper for WP_List_Table::get_default_primary_column_name().
has_items ()
Whether the table has items to display or not.
no_items ()
Message to be displayed when there are no items.
prepare_items ()
Prepares the list of items for displaying.
print_column_headers ($with_id=true)
Print column headers, accounting for hidden and sortable columns.
search_box ($text, $input_id)
Display the search box.
single_row ($item)
Generates content for a single row of the table.
views ()
Display the list of views available on this table.
Data Fields
$items
Protected Member Functions
bulk_actions ($which= '')
Display the bulk actions dropdown.
column_cb ($item)
column_default ($item, $column_name)
comments_bubble ($post_id, $pending_comments)
Display a comment count bubble.
display_tablenav ($which)
Generate the table navigation above or below the table.
extra_tablenav ($which)
Extra controls to be displayed between bulk actions and pagination.
get_bulk_actions ()
Get an associative array (option_name => option_title) with the list of bulk actions available on this table.
get_column_info ()
Get a list of all, hidden and sortable columns, with filter applied.
get_default_primary_column_name ()
Gets the name of the default primary column.
get_items_per_page ($option, $default=20)
Get number of items to display on a single page.
get_primary_column_name ()
Gets the name of the primary column.
get_sortable_columns ()
Get a list of sortable columns.
get_table_classes ()
Get a list of CSS classes for the WP_List_Table table tag.
get_views ()
Get an associative array (id => link) with the list of views available on this table.
handle_row_actions ($item, $column_name, $primary)
Generates and display row actions links for the list table.
months_dropdown ($post_type)
Display a monthly dropdown for filtering items.
pagination ($which)
Display the pagination.
row_actions ($actions, $always_visible=false)
Generate row actions div.
set_pagination_args ($args)
An internal method that sets all the necessary pagination arguments.
single_row_columns ($item)
Generates the columns for a single row of the table.
view_switcher ($current_mode)
Display a view switcher.
Protected Attributes
$_args
$_column_headers
$_pagination_args = array()
$compat_fields = array('_args', '_pagination_args', 'screen', '_actions', '_pagination')
{
$compat_methods
{
$modes = array()
$screen
Private Attributes
$_actions
$_pagination
Detailed Description
Base class for displaying a list of items in an ajaxified HTML table.
Since
3.1.0 private
Definition at line 16 of file class-wp-list-table.php.
Constructor & Destructor Documentation
__construct ($args = array())
Constructor.
The child class should call this constructor from its own constructor to override the default $args.
Since
3.1.0 public
Parameters
array | string $args { Array or string of arguments.
string $plural Plural value used for labels and the objects being listed. This affects things such as CSS class-names and nonces used in the list table, e.g. 'posts'. Default empty. string $singular Singular label for an object being listed, e.g. 'post'. Default empty bool $ajax Whether the list table supports AJAX. This includes loading and sorting data, for example. If true, the class will call the {
See also
_js_vars()} method in the footer to provide variables to any scripts handling AJAX events. Default false. string $screen String containing the hook name used to determine the current screen. If left null, the current screen will be automatically set. Default null. }
Definition at line 135 of file class-wp-list-table.php.
References __, add_action(), add_filter(), convert_to_screen(), null, sanitize_key(), and wp_parse_args().
Member Function Documentation
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
Since
4.0.0 public
Parameters
callable $name Method to call.
array $arguments Arguments to pass when calling.
Returns
mixed|bool Return value of the callback, false otherwise.
Definition at line 238 of file class-wp-list-table.php.
References $name.
__get ($name)
Make private properties readable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to get.
Returns
mixed Property.
Definition at line 177 of file class-wp-list-table.php.
References $name.
__isset ($name)
Make private properties checkable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to check if set.
Returns
bool Whether the property is set.
Definition at line 208 of file class-wp-list-table.php.
References $name.
__set ($name, $value)
Make private properties settable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to check if set.
mixed $value Property value.
Returns
mixed Newly-set property.
Definition at line 193 of file class-wp-list-table.php.
References $name, and $value.
__unset ($name)
Make private properties un-settable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to unset.
Definition at line 222 of file class-wp-list-table.php.
References $name.
_js_vars ()
Send required variables to JavaScript land.
public
Definition at line 1366 of file class-wp-list-table.php.
References wp_json_encode().
ajax_response ()
Handle an incoming ajax request (called from admin-ajax.php)
Since
3.1.0 public
Definition at line 1333 of file class-wp-list-table.php.
References _n(), display_rows(), display_rows_or_placeholder(), number_format_i18n(), prepare_items(), and wp_json_encode().
ajax_user_can ()
Checks the current user's permissions.
Since
3.1.0 public
Definition at line 252 of file class-wp-list-table.php.
bulk_actions ($which = '') protected
Display the bulk actions dropdown.
Since
3.1.0 protected
Parameters
string $which The location of the bulk actions: 'top' or 'bottom'. This is designated as optional for backwards-compatibility.
Filter the list table Bulk Actions drop-down.
The dynamic portion of the hook name, $this->screen->id, refers to the ID of the current screen, usually a string.
This filter can currently only be used to remove bulk actions.
Since
3.5.0
Parameters
array $actions An array of the available bulk actions.
Definition at line 437 of file class-wp-list-table.php.
References $class, $name, $title, __, apply_filters(), esc_attr(), get_bulk_actions(), and submit_button().
Referenced by display_tablenav().
column_cb ($item) protected
Parameters
object $item
Definition at line 1257 of file class-wp-list-table.php.
Referenced by single_row_columns().
column_default ($item, $column_name) protected
Parameters
object $item
string $column_name
Definition at line 1251 of file class-wp-list-table.php.
Referenced by single_row_columns().
comments_bubble ($post_id, $pending_comments) protected
Display a comment count bubble.
Since
3.1.0 protected
Parameters
int $post_id The post ID.
int $pending_comments Number of pending comments.
Definition at line 648 of file class-wp-list-table.php.
References $post_id, __, _n(), add_query_arg(), admin_url(), elseif, esc_url, get_comments_number(), and number_format_i18n().
Referenced by WP_Media_List_Table\column_comments(), WP_Posts_List_Table\column_comments(), and WP_Comments_List_Table\column_response().
current_action ()
Get the current action selected from the bulk actions dropdown.
Since
3.1.0 public
Returns
string|false The action name or False if no action was selected
Definition at line 486 of file class-wp-list-table.php.
display ()
Display the table.
Since
3.1.0 public
Definition at line 1123 of file class-wp-list-table.php.
References display_rows_or_placeholder(), display_tablenav(), and print_column_headers().
display_rows ()
Generate the table rows.
Since
3.1.0 public
Definition at line 1227 of file class-wp-list-table.php.
References single_row().
Referenced by ajax_response(), and display_rows_or_placeholder().
display_rows_or_placeholder ()
Generate the tbody element for the list table.
Since
3.1.0 public
Definition at line 1211 of file class-wp-list-table.php.
References display_rows(), get_column_count(), has_items(), and no_items().
Referenced by ajax_response(), WP_Post_Comments_List_Table\display(), WP_Plugin_Install_List_Table\display(), WP_Comments_List_Table\display(), display(), and GFConfirmationTable\display().
display_tablenav ($which) protected
Generate the table navigation above or below the table.
Since
3.1.0 protected
Parameters
string $which
Definition at line 1174 of file class-wp-list-table.php.
References bulk_actions(), endif, extra_tablenav(), has_items(), pagination(), and wp_nonce_field().
Referenced by WP_Comments_List_Table\display(), and display().
extra_tablenav ($which) protected
Extra controls to be displayed between bulk actions and pagination.
Since
3.1.0 protected
Parameters
string $which
Definition at line 1203 of file class-wp-list-table.php.
Referenced by display_tablenav().
get_bulk_actions () protected
Get an associative array (option_name => option_title) with the list of bulk actions available on this table.
Since
3.1.0 protected
Returns
array
Definition at line 424 of file class-wp-list-table.php.
Referenced by bulk_actions().
get_column_count ()
Return number of visible columns.
Since
3.1.0 public
Returns
int
Definition at line 1033 of file class-wp-list-table.php.
References $columns, and get_column_info().
Referenced by WP_Terms_List_Table\display_rows_or_placeholder(), and display_rows_or_placeholder().
get_column_info () protected
Get a list of all, hidden and sortable columns, with filter applied.
Since
3.1.0 protected
Returns
array
Filter the list table sortable columns for a specific screen.
The dynamic portion of the hook name, $this->screen->id, refers to the ID of the current screen, usually a string.
Since
3.5.0
Parameters
array $sortable_columns An array of sortable columns.
Definition at line 978 of file class-wp-list-table.php.
References $_column_headers, $columns, $id, $value, apply_filters(), get_column_headers(), get_hidden_columns(), get_primary_column_name(), and get_sortable_columns().
Referenced by get_column_count(), WP_Terms_List_Table\inline_edit(), WP_Posts_List_Table\inline_edit(), print_column_headers(), WP_Users_List_Table\single_row(), WP_Plugins_List_Table\single_row(), WP_MS_Themes_List_Table\single_row_columns(), and single_row_columns().
get_columns ()
Get a list of columns.
The format is: 'internal-name' => 'Title'
Since
3.1.0 public
Returns
array
Definition at line 872 of file class-wp-list-table.php.
Referenced by get_default_primary_column_name().
get_default_primary_column_name () protected
Gets the name of the default primary column.
Since
4.3.0 protected
Returns
string Name of the default primary column, in this case, an empty string.
Definition at line 901 of file class-wp-list-table.php.
References $columns, and get_columns().
Referenced by _WP_List_Table_Compat\get_column_info(), and get_primary_column_name().
get_items_per_page ($option, $default = 20) protected
Get number of items to display on a single page.
Since
3.1.0 protected
Parameters
string $option
int $default
Returns
int
Filter the number of items to be displayed on each page of the list table.
The dynamic hook name, $option, refers to the per_page option depending on the type of list table in use. Possible values include: 'edit_comments_per_page', 'sites_network_per_page', 'site_themes_network_per_page', 'themes_network_per_page', 'users_network_per_page', 'edit_post_per_page', 'edit_page_per_page', 'edit_{$post_type}_per_page', etc.
Since
2.9.0
Parameters
int $per_page Number of items to be displayed. Default 20.
Definition at line 718 of file class-wp-list-table.php.
References $default, $option, apply_filters(), and get_user_option().
Referenced by WP_Comments_List_Table\get_per_page(), WP_MS_Users_List_Table\prepare_items(), WP_MS_Sites_List_Table\prepare_items(), WP_Plugins_List_Table\prepare_items(), WP_Terms_List_Table\prepare_items(), WP_Users_List_Table\prepare_items(), WP_MS_Themes_List_Table\prepare_items(), and WP_Posts_List_Table\prepare_items().
get_pagenum ()
Get the current page number.
Since
3.1.0 public
Returns
int
Definition at line 699 of file class-wp-list-table.php.
References $pagenum, and absint().
Referenced by WP_Plugins_List_Table\__construct(), WP_MS_Themes_List_Table\__construct(), WP_Themes_List_Table\_js_vars(), WP_Posts_List_Table\display_rows(), get_pagination_arg(), pagination(), GFPaymentStatsTable\pagination(), WP_MS_Users_List_Table\prepare_items(), WP_Theme_Install_List_Table\prepare_items(), WP_Themes_List_Table\prepare_items(), WP_MS_Sites_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), WP_Terms_List_Table\prepare_items(), WP_Comments_List_Table\prepare_items(), WP_Users_List_Table\prepare_items(), and set_pagination_args().
get_pagination_arg ($key)
Access the pagination args.
Since
3.1.0 public
Parameters
string $key Pagination argument to retrieve. Common values include 'total_items', 'total_pages', 'per_page', or 'infinite_scroll'.
Returns
int Number of items that correspond to the given pagination argument.
Definition at line 305 of file class-wp-list-table.php.
References get_pagenum().
Referenced by GFPaymentStatsTable\pagination(), and WP_Themes_List_Table\tablenav().
get_primary_column ()
Public wrapper for WP_List_Table::get_default_primary_column_name().
Since
4.4.0 public
Returns
string Name of the default primary column.
Definition at line 931 of file class-wp-list-table.php.
References get_primary_column_name().
get_primary_column_name () protected
Gets the name of the primary column.
Since
4.3.0 protected
Returns
string The name of the primary column.
Filter the name of the primary column for the current list table.
Since
4.3.0
Parameters
string $default Column name default for the specific list table, e.g. 'name'.
string $context Screen ID for specific list table, e.g. 'plugins'.
Definition at line 943 of file class-wp-list-table.php.
References $columns, $default, apply_filters(), get_column_headers(), and get_default_primary_column_name().
Referenced by get_column_info(), and get_primary_column().
get_sortable_columns () protected
Get a list of sortable columns.
The format is: 'internal-name' => 'orderby' or 'internal-name' => array('orderby', true)
The second format will make the initial sorting order be descending
Since
3.1.0 protected
Returns
array
Definition at line 889 of file class-wp-list-table.php.
Referenced by get_column_info().
get_table_classes () protected
Get a list of CSS classes for the WP_List_Table table tag.
Since
3.1.0 protected
Returns
array List of CSS classes for the table tag.
Definition at line 1163 of file class-wp-list-table.php.
get_views () protected
Get an associative array (id => link) with the list of views available on this table.
Since
3.1.0 protected
Returns
array
Definition at line 378 of file class-wp-list-table.php.
Referenced by views().
handle_row_actions ($item, $column_name, $primary) protected
Generates and display row actions links for the list table.
Since
4.3.0 protected
Parameters
object $item The item being acted upon.
string $column_name Current column name.
string $primary Primary column name.
Returns
string The row actions HTML, or an empty string if the current column is the primary column.
Definition at line 1323 of file class-wp-list-table.php.
References __.
Referenced by single_row_columns().
has_items ()
Whether the table has items to display or not.
Since
3.1.0 public
Returns
bool
Definition at line 323 of file class-wp-list-table.php.
Referenced by WP_Themes_List_Table\display_rows_or_placeholder(), display_rows_or_placeholder(), display_tablenav(), WP_Users_List_Table\extra_tablenav(), WP_MS_Themes_List_Table\no_items(), WP_MS_Themes_List_Table\prepare_items(), and search_box().
months_dropdown ($post_type) protected
Display a monthly dropdown for filtering items.
Since
3.1.0 protected
wpdb $wpdb WP_Locale $wp_locale
Parameters
string $post_type
Filter whether to remove the 'Months' drop-down from the post list table.
Since
4.2.0
Parameters
bool $disable Whether to disable the drop-down. Default false.
string $post_type The post type.
Filter the 'Months' drop-down results.
Since
3.7.0
Parameters
object $months The months drop-down query results.
string $post_type The post type.
Definition at line 540 of file class-wp-list-table.php.
References $post_type, $wp_locale, $wpdb, __, _e, apply_filters(), elseif, esc_attr(), label, month, name, selected(), and zeroise().
Referenced by WP_Media_List_Table\extra_tablenav(), and WP_Posts_List_Table\extra_tablenav().
no_items ()
Message to be displayed when there are no items.
Since
3.1.0 public
Definition at line 333 of file class-wp-list-table.php.
References _e.
Referenced by display_rows_or_placeholder().
pagination ($which) protected
Display the pagination.
Since
3.1.0 protected
Parameters
string $which
Definition at line 747 of file class-wp-list-table.php.
References $_pagination, $_SERVER, $output, $total_pages, __, _n(), _x, add_query_arg(), esc_url, get_pagenum(), number_format_i18n(), remove_query_arg(), and set_url_scheme().
Referenced by WP_Theme_Install_List_Table\display(), WP_Plugin_Install_List_Table\display_tablenav(), display_tablenav(), and WP_Themes_List_Table\tablenav().
prepare_items ()
Prepares the list of items for displaying.
WP_List_Table::set_pagination_args()
Since
3.1.0 public
Definition at line 264 of file class-wp-list-table.php.
Referenced by ajax_response().
print_column_headers ($with_id = true)
Print column headers, accounting for hidden and sortable columns.
Since
3.1.0 public
int $cb_counter
Parameters
bool $with_id Whether to set the id attribute or not
Definition at line 1049 of file class-wp-list-table.php.
References $_SERVER, $class, $columns, $id, __, add_query_arg(), elseif, esc_url, get_column_info(), remove_query_arg(), and set_url_scheme().
Referenced by WP_Comments_List_Table\display(), display(), and GFConfirmationTable\display().
row_actions ($actions, $always_visible = false) protected
Generate row actions div.
Since
3.1.0 protected
Parameters
array $actions The list of actions
bool $always_visible Whether the actions should be always visible
Returns
string
Definition at line 509 of file class-wp-list-table.php.
References $action, $i, $link, $out, and __.
Referenced by WP_MS_Themes_List_Table\column_name(), WP_Links_List_Table\handle_row_actions(), WP_Terms_List_Table\handle_row_actions(), WP_MS_Users_List_Table\handle_row_actions(), WP_MS_Sites_List_Table\handle_row_actions(), WP_Posts_List_Table\handle_row_actions(), WP_Users_List_Table\single_row(), and WP_Plugins_List_Table\single_row().
search_box ($text, $input_id)
Display the search box.
Since
3.1.0 public
Parameters
string $text The search button text
string $input_id The search input id
Definition at line 346 of file class-wp-list-table.php.
References $text, esc_attr(), has_items(), input, label, name, and submit_button().
set_pagination_args ($args) protected
An internal method that sets all the necessary pagination arguments.
Since
3.1.0 protected
Parameters
array | string $args Array or string of arguments with information about the pagination.
Definition at line 276 of file class-wp-list-table.php.
References add_query_arg(), DOING_AJAX, exit, get_pagenum(), and wp_parse_args().
Referenced by WP_MS_Users_List_Table\prepare_items(), WP_Theme_Install_List_Table\prepare_items(), WP_Themes_List_Table\prepare_items(), WP_MS_Sites_List_Table\prepare_items(), WP_Media_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), WP_Plugins_List_Table\prepare_items(), WP_Terms_List_Table\prepare_items(), WP_Comments_List_Table\prepare_items(), WP_Users_List_Table\prepare_items(), WP_MS_Themes_List_Table\prepare_items(), WP_Posts_List_Table\prepare_items(), and GFPaymentStatsTable\prepare_items().
single_row ($item)
Generates content for a single row of the table.
Since
3.1.0 public
Parameters
object $item The current item
Definition at line 1240 of file class-wp-list-table.php.
References single_row_columns().
Referenced by display_rows().
single_row_columns ($item) protected
Generates the columns for a single row of the table.
Since
3.1.0 protected
Parameters
object $item The current item
Definition at line 1267 of file class-wp-list-table.php.
References $attributes, $columns, column_cb(), column_default(), elseif, get_column_info(), handle_row_actions(), and wp_strip_all_tags().
Referenced by WP_Links_List_Table\display_rows(), WP_MS_Users_List_Table\display_rows(), WP_MS_Sites_List_Table\display_rows(), WP_Media_List_Table\display_rows(), WP_Terms_List_Table\single_row(), WP_Comments_List_Table\single_row(), WP_Posts_List_Table\single_row(), single_row(), and GFConfirmationTable\single_row().
view_switcher ($current_mode) protected
Display a view switcher.
Since
3.1.0 protected
Parameters
string $current_mode
Definition at line 618 of file class-wp-list-table.php.
References $mode, $title, add_query_arg(), esc_url, input, and name.
Referenced by WP_MS_Users_List_Table\pagination(), WP_MS_Sites_List_Table\pagination(), and WP_Media_List_Table\views().
views ()
Display the list of views available on this table.
Since
3.1.0 public
Filter the list of available list table views.
The dynamic portion of the hook name, $this->screen->id, refers to the ID of the current screen, usually a string.
Since
3.5.0
Parameters
array $views An array of available list table views.
Definition at line 388 of file class-wp-list-table.php.
References $class, apply_filters(), and get_views().
Field Documentation
$_actions private
Definition at line 61 of file class-wp-list-table.php.
$_args protected
Definition at line 34 of file class-wp-list-table.php.
$_column_headers protected
Definition at line 88 of file class-wp-list-table.php.
Referenced by get_column_info().
$_pagination private
Definition at line 70 of file class-wp-list-table.php.
Referenced by pagination(), and GFPaymentStatsTable\pagination().
$_pagination_args = array() protected
Definition at line 43 of file class-wp-list-table.php.
$compat_fields = array('_args', '_pagination_args', 'screen', '_actions', '_pagination') protected
{
Definition at line 96 of file class-wp-list-table.php.
$compat_methods protected
Initial value:
= array('set_pagination_args', 'get_views', 'get_bulk_actions', 'bulk_actions',
        'row_actions', 'months_dropdown', 'view_switcher', 'comments_bubble', 'get_items_per_page', 'pagination',
        'get_sortable_columns', 'get_column_info', 'get_table_classes', 'display_tablenav', 'extra_tablenav',
        'single_row_columns' )
{
Definition at line 104 of file class-wp-list-table.php.
$items
Definition at line 25 of file class-wp-list-table.php.
Referenced by WP_Themes_List_Table\display_rows(), and WP_Theme_Install_List_Table\display_rows().
$modes = array() protected
Definition at line 79 of file class-wp-list-table.php.
$screen protected
Definition at line 52 of file class-wp-list-table.php.
Referenced by _WP_List_Table_Compat\__construct(), WP_Posts_List_Table\inline_edit(), WP_Plugins_List_Table\prepare_items(), and WP_Plugins_List_Table\single_row().
The documentation for this class was generated from the following file:
class-wp-list-table.php