GravityView: GV_UnitTest_Factory_For_User Class Reference
GV_UnitTest_Factory_For_User Class Reference
Public Member Functions
_add_gravityview_caps (WP_User $user)
Add GravityView user caps based on role.
create ($args=array(), $generation_definitions=array())
create_and_get ($args=array(), $generation_definitions=null)
create_and_set ($args=array(), $generation_definitions=null)
Create the user, then set the current user to the created user.
create_object ($args)
set ($user_id)
Alias for wp_set_current_user()
Detailed Description
Definition at line 108 of file factory.php.
Member Function Documentation
_add_gravityview_caps (WP_User $user)
Add GravityView user caps based on role.
Since
1.15
Parameters
WP_User $user
Definition at line 137 of file factory.php.
References GravityView_Roles_Capabilities\all_caps().
Referenced by create(), and set().
create ($args = array(), $generation_definitions = array())
Definition at line 110 of file factory.php.
References _add_gravityview_caps().
Referenced by create_and_set().
create_and_get ($args = array(), $generation_definitions = null)
Parameters
array $args
null $generation_definitions
Returns
WP_User
Definition at line 153 of file factory.php.
create_and_set ($args = array(), $generation_definitions = null)
Create the user, then set the current user to the created user.
Parameters
array $args
null $generation_definitions
Returns
bool|WP_User
Definition at line 165 of file factory.php.
References create(), and set().
create_object ($args)
Definition at line 128 of file factory.php.
set ($user_id)
Alias for wp_set_current_user()
See also
wp_set_current_user()
Parameters
$user_id
Returns
WP_User
Definition at line 185 of file factory.php.
References _add_gravityview_caps().
Referenced by create_and_set().
The documentation for this class was generated from the following file:
factory.php