GravityView: WP_REST_Response Class Reference
WP_REST_Response Class Reference
Core class used to implement a REST response object.
Public Member Functions
add_link ($rel, $href, $attributes=array())
Adds a link to the response.
add_link ($rel, $href, $attributes=array())
Adds a link to the response.
add_links ($links)
Adds multiple links to the response.
add_links ($links)
Adds multiple links to the response.
as_error ()
Retrieves a WP_Error object from the response.
as_error ()
Retrieves a WP_Error object from the response.
get_links ()
Retrieves links for the response.
get_links ()
Retrieves links for the response.
get_matched_handler ()
Retrieves the handler that was used to generate the response.
get_matched_handler ()
Retrieves the handler that was used to generate the response.
get_matched_route ()
Retrieves the route that was used.
get_matched_route ()
Retrieves the route that was used.
is_error ()
Checks if the response is an error, i.e.
is_error ()
Checks if the response is an error, i.e.
link_header ($rel, $link, $other=array())
Sets a single link header.
link_header ($rel, $link, $other=array())
Sets a single link header.
remove_link ($rel, $href=null)
Removes a link from the response.
remove_link ($rel, $href=null)
Removes a link from the response.
set_matched_handler ($handler)
Retrieves the handler that was responsible for generating the response.
set_matched_handler ($handler)
Retrieves the handler that was responsible for generating the response.
set_matched_route ($route)
Sets the route (regex for path) that caused the response.
set_matched_route ($route)
Sets the route (regex for path) that caused the response.
Public Member Functions inherited from WP_HTTP_Response
__construct ($data=null, $status=200, $headers=array())
Constructor.
__construct ($data=null, $status=200, $headers=array())
Constructor.
get_data ()
Retrieves the response data.
get_data ()
Retrieves the response data.
get_headers ()
Retrieves headers associated with the response.
get_headers ()
Retrieves headers associated with the response.
get_status ()
Retrieves the HTTP return code for the response.
get_status ()
Retrieves the HTTP return code for the response.
header ($key, $value, $replace=true)
Sets a single HTTP header.
header ($key, $value, $replace=true)
Sets a single HTTP header.
jsonSerialize ()
Retrieves the response data for JSON serialization.
jsonSerialize ()
Retrieves the response data for JSON serialization.
set_data ($data)
Sets the response data.
set_data ($data)
Sets the response data.
set_headers ($headers)
Sets all header values.
set_headers ($headers)
Sets all header values.
set_status ($code)
Sets the 3-digit HTTP status code.
set_status ($code)
Sets the 3-digit HTTP status code.
Protected Attributes
$links = array()
$matched_handler = null
$matched_route = ''
Additional Inherited Members
Data Fields inherited from WP_HTTP_Response
$data
$headers
$status
Detailed Description
Core class used to implement a REST response object.
Since
4.4.0
See also
WP_HTTP_Response
Definition at line 17 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
Member Function Documentation
add_link ($rel, $href, $attributes = array())
Adds a link to the response.
Definition at line 62 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References $attributes, and $href.
Referenced by add_links().
add_link ($rel, $href, $attributes = array())
Adds a link to the response.
Definition at line 62 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References $attributes, and $href.
add_links ($links)
Adds multiple links to the response.
Link data should be an associative array with link relation as the key. The value can either be an associative array of link attributes (including href with the URL for the response), or a list of these associative arrays.
Since
4.4.0 public
Parameters
array $links Map of link relation to list of links.
Definition at line 117 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References $attributes, $links, and add_link().
add_links ($links)
Adds multiple links to the response.
Link data should be an associative array with link relation as the key. The value can either be an associative array of link attributes (including href with the URL for the response), or a list of these associative arrays.
Since
4.4.0 public
Parameters
array $links Map of link relation to list of links.
Definition at line 117 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References $attributes, and add_link().
as_error ()
Retrieves a WP_Error object from the response.
Since
4.4.0 public
Returns
WP_Error|null WP_Error or null on not an errored response.
Definition at line 238 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References WP_HTTP_Response\$data, WP_HTTP_Response\get_data(), WP_HTTP_Response\get_status(), is_error(), and null.
as_error ()
Retrieves a WP_Error object from the response.
Since
4.4.0 public
Returns
WP_Error|null WP_Error or null on not an errored response.
Definition at line 238 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References WP_HTTP_Response\$data, WP_HTTP_Response\get_data(), WP_HTTP_Response\get_status(), is_error(), and null.
get_links ()
Retrieves links for the response.
Since
4.4.0 public
Returns
array List of links.
Definition at line 138 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References $links.
get_links ()
Retrieves links for the response.
Since
4.4.0 public
Returns
array List of links.
Definition at line 138 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References $links.
get_matched_handler ()
Retrieves the handler that was used to generate the response.
Since
4.4.0 public
Returns
null|array The handler that was used to create the response.
Definition at line 202 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References $matched_handler.
get_matched_handler ()
Retrieves the handler that was used to generate the response.
Since
4.4.0 public
Returns
null|array The handler that was used to create the response.
Definition at line 202 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References $matched_handler.
get_matched_route ()
Retrieves the route that was used.
Since
4.4.0 public
Returns
string The matched route.
Definition at line 178 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References $matched_route.
get_matched_route ()
Retrieves the route that was used.
Since
4.4.0 public
Returns
string The matched route.
Definition at line 178 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References $matched_route.
is_error ()
Checks if the response is an error, i.e.
>= 400 response code.
Since
4.4.0 public
Returns
bool Whether the response is an error.
Definition at line 226 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References WP_HTTP_Response\get_status().
is_error ()
Checks if the response is an error, i.e.
>= 400 response code.
Since
4.4.0 public
Returns
bool Whether the response is an error.
Definition at line 226 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References WP_HTTP_Response\get_status().
Referenced by as_error().
link_header ($rel, $link, $other = array())
Sets a single link header.
Definition at line 158 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References $link, $value, and WP_HTTP_Response\header().
link_header ($rel, $link, $other = array())
Sets a single link header.
Definition at line 158 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References $link, $value, and WP_HTTP_Response\header().
remove_link ($rel, $href = null)
Removes a link from the response.
Since
4.4.0 public
Parameters
string $rel Link relation. Either an IANA registered type, or an absolute URL.
string $href Optional. Only remove links for the relation matching the given href. Default null.
Definition at line 88 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
References $href, and wp_list_filter().
remove_link ($rel, $href = null)
Removes a link from the response.
Since
4.4.0 public
Parameters
string $rel Link relation. Either an IANA registered type, or an absolute URL.
string $href Optional. Only remove links for the relation matching the given href. Default null.
Definition at line 88 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
References $href, and wp_list_filter().
set_matched_handler ($handler)
Retrieves the handler that was responsible for generating the response.
Since
4.4.0 public
Parameters
array $handler The matched handler.
Definition at line 214 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
set_matched_handler ($handler)
Retrieves the handler that was responsible for generating the response.
Since
4.4.0 public
Parameters
array $handler The matched handler.
Definition at line 214 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
set_matched_route ($route)
Sets the route (regex for path) that caused the response.
Since
4.4.0 public
Parameters
string $route Route name.
Definition at line 190 of file wordpress/wp-includes/rest-api/class-wp-rest-response.php.
set_matched_route ($route)
Sets the route (regex for path) that caused the response.
Since
4.4.0 public
Parameters
string $route Route name.
Definition at line 190 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
Field Documentation
$links = array() protected
Definition at line 26 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
Referenced by add_links(), and get_links().
$matched_handler = null protected
Definition at line 44 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
Referenced by get_matched_handler().
$matched_route = '' protected
Definition at line 35 of file api-core/wp-includes/rest-api/class-wp-rest-response.php.
Referenced by get_matched_route().
The documentation for this class was generated from the following file:
api-core/wp-includes/rest-api/class-wp-rest-response.php