GravityView: TrustedLogin Class Reference
TrustedLogin Class Reference
Public Member Functions
add_gk_submenu_item ()
Adds Settings submenu to the GravityKit top-level admin menu.
add_tl_key_to_helpscout_beacon ($configuration)
Updates Help Scout beacon with TL access key.
get_config ()
Returns TrustedLogin configuration.
log ($message, $method='', $level='debug', $data=[])
Overrides TL's internal logging with Foundation's logging.
Static Public Member Functions
static get_instance ()
Returns class instance.
Data Fields
const ID = 'gk_foundation_trustedlogin'
const TL_API_KEY = '3b3dc46c0714cc8e'
Private Member Functions
__construct ()
Class constructor.
Private Attributes
$_capability = 'manage_options'
$_trustedlogin_client
Static Private Attributes
static $_instance
Detailed Description
Definition at line 22 of file TrustedLogin.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Class constructor.
Since
1.0.0
Returns
void
Definition at line 55 of file TrustedLogin.php.
References TrustedLogin\add_gk_submenu_item(), and TrustedLogin\get_config().
Member Function Documentation
add_gk_submenu_item()
add_gk_submenu_item ()
Adds Settings submenu to the GravityKit top-level admin menu.
Since
1.0.0
Exceptions
Exception TrustedLoginConfig throws an exception when the config object is empty (do not apply to us),
Returns
void
Definition at line 102 of file TrustedLogin.php.
References AdminMenu\add_submenu_item(), and TrustedLogin\get_config().
Referenced by TrustedLogin\__construct().
add_tl_key_to_helpscout_beacon()
add_tl_key_to_helpscout_beacon ($configuration)
Updates Help Scout beacon with TL access key.
Since
1.0.0
Parameters
array $configuration
Returns
array
Definition at line 223 of file TrustedLogin.php.
References Arr\set().
get_config()
get_config ()
Returns TrustedLogin configuration.
Since
1.0.0
Returns
array
Runs Filter:
gk/foundation/integrations/trustedlogin/capabilities Modifies the capabilities added/removed by TL.
Since
1.0.0
Parameters
array $capabilities
Definition at line 125 of file TrustedLogin.php.
References Arr\get(), LicenseManager\get_instance(), and Arr\set().
Referenced by TrustedLogin\__construct(), and TrustedLogin\add_gk_submenu_item().
get_instance()
static get_instance () static
Returns class instance.
Since
1.0.0
Returns
TrustedLogin
Definition at line 85 of file TrustedLogin.php.
Referenced by Core\init().
log()
log ($message, $method = '', $level = 'debug', $data = [])
Overrides TL's internal logging with Foundation's logging.
Definition at line 210 of file TrustedLogin.php.
Field Documentation
$_capability
$_capability = 'manage_options' private
Definition at line 32 of file TrustedLogin.php.
$_instance
$_instance static private
Definition at line 46 of file TrustedLogin.php.
$_trustedlogin_client
$_trustedlogin_client private
Definition at line 39 of file TrustedLogin.php.
ID
const ID = 'gk_foundation_trustedlogin'
Definition at line 23 of file TrustedLogin.php.
TL_API_KEY
const TL_API_KEY = '3b3dc46c0714cc8e'
Definition at line 25 of file TrustedLogin.php.
The documentation for this class was generated from the following file:
TrustedLogin.php