GravityView: GFAddOn Class Reference
GFAddOn Class Reference
Public Member Functions
__construct ()
Class constructor which hooks the instance into the WordPress init action.
add_form_settings_menu ($tabs, $form_id)
Add the form settings tab.
add_note ($entry_id, $note, $note_type=null)
app_settings_fields ()
Override this function to specify the settings fields to be rendered on the plugin settings page.
app_settings_tab ()
app_tab_page ()
Handles the rendering of app menu items that implement the tabs UI.
build_choices ($key_value_pairs)
create_app_menu ()
Creates a top level app menu.
create_plugin_page_menu ($menus)
Creates plugin page menu item Target of gform_addon_navigation filter.
enqueue_preview_styles ($preview_styles, $form)
Target of gform_preview_styles.
enqueue_print_styles ($print_styles, $form)
Target of gform_print_styles.
enqueue_scripts ($form= '', $is_ajax=false)
Target of admin_enqueue_scripts and gform_enqueue_scripts hooks.
field_map_table_header ()
filter_settings ($fields, $settings)
Filter settings fields.
form_settings_page ()
Renders the form settings page.
get_app_settings_tabs ()
Returns the tabs for the settings app menu item.
get_base_path ($full_path= '')
Returns the physical path of the plugins root folder.
get_base_url ($full_path= '')
Returns the url of the root folder of the current Add-On.
get_field_value ($form, $entry, $field_id)
Returns the value of the selected field.
get_first_field_by_type ($field_type, $subfield_id=null, $form_id=null, $return_first_only=true)
Returns the field ID of the first field of the desired type.
get_form_fields_as_choices ($form, $args=array())
Retrieve an array of form fields formatted for select, radio and checkbox settings fields.
get_locking_config ()
Returns the configuration for locking.
get_locking_object_id ()
Returns the ID of the object to be locked.
get_mapped_field_name ($parent_field, $field_name)
get_plugin_setting ($setting_name)
Get plugin setting Returns the plugin setting specified by the $setting_name parameter.
get_plugin_settings ()
Returns the currently saved plugin settings.
get_results_page_config ()
Returns the configuration for the results page.
get_select_options ($choices, $selected_value)
Prepares an HTML string of options for a drop down field.
has_app_menu ()
Checks whether the current Add-On has a top level app menu.
has_app_settings ()
Checks whether the current Add-On has a settings page.
has_deprecated_elements ()
has_plugin_settings_page ()
Checks whether the current Add-On has a settings page.
init ()
Plugin starting point.
is_gravityforms_installed ()
Checks whether the Gravity Forms is installed.
is_gravityforms_supported ($min_gravityforms_version= '')
Checks whether the current version of Gravity Forms is supported.
is_locking_edit_page ()
Returns TRUE if the current page is the edit page.
is_locking_list_page ()
Returns TRUE if the current page is the list page.
is_locking_view_page ()
Returns TRUE if the current page is the view page.
is_object_locked ($object_id)
Checked whether an object is locked.
list_row_class ($object_id, $echo=true)
Outputs class for the row for the specified Object ID on the list page.
load_screen_options ()
Override this function to load custom screen options.
lock_info ($object_id, $echo=true)
Outputs information about the user currently editing the specified object.
log_debug ($message)
Writes an error message to the Gravity Forms log.
log_error ($message)
Writes an error message to the Gravity Forms log.
maybe_override_field_value ($field_value, $form, $entry, $field_id)
Enables use of the gform_SLUG_field_value filter to override the field value.
maybe_save_form_settings ($form)
maybe_uninstall ()
Not intended to be overridden or called directly by Add-Ons.
members_get_capabilities ($caps)
Not intended to be overridden or called directly by Add-Ons.
note_avatar ()
Override this function to specify a custom avatar (i.e.
notes_avatar ($avatar, $note)
plugin_message ()
Returns the message that will be displayed if the current version of Gravity Forms is not supported.
plugin_page_container ()
Plugin page container Target of the plugin menu left nav icon.
plugin_row ()
Target for the after_plugin_row action hook.
plugin_settings_fields ()
Override this function to specify the settings fields to be rendered on the plugin settings page.
plugin_settings_link ($links, $file)
plugin_settings_page ()
Plugin settings page.
plugin_settings_title ()
pre_init ()
Gets executed before all init functions.
register_noconflict_scripts ($scripts)
Target for the gform_noconflict_scripts filter.
register_noconflict_styles ($styles)
Target for the gform_noconflict_styles filter.
render_uninstall ()
Override this function to customize the markup for the uninstall section on the plugin settings page.
save_form_settings ($form, $settings)
set_logging_supported ($plugins)
settings_checkbox_and_select ($field, $echo=true)
Renders and initializes a checkbox field that displays a select field when checked based on the $field array.
settings_dynamic_field_map ($field, $echo=true)
settings_field_map ($field, $echo=true)
settings_field_map_select ($field, $form_id)
settings_field_select ($field, $echo=true)
Renders and initializes a drop down field based on the $field array whose choices are populated by the form's fields.
table_exists ($table_name)
uninstall_addon ()
Removes all settings and deactivates the Add-On.
Static Public Member Functions
static display_plugin_message ($message, $is_error=false)
Formats and outs a message for the plugin row.
static get_all_deprecated_protected_methods ($add_on_class_name= '')
static get_deprecated_protected_methods_for_base_class ($base_class_name, $add_on_class_name= '')
static get_dynamic_field_map_fields ($feed, $field_name)
static get_field_map_choices ($form_id, $field_type=null, $exclude_field_types=null)
static get_field_map_fields ($feed, $field_name)
static get_gfaddon_base_path ()
Returns the physical path of the Add-On Framework root folder.
static get_gfaddon_base_url ()
Returns the url of the Add-On Framework root folder.
static get_registered_addons ()
Gets all active, registered Add-Ons.
static init_addons ()
Initializes all addons.
static register ($class, $overrides=null)
Registers an addon so that it gets initialized appropriately.
Data Fields
$app_hook_suffix
Protected Member Functions
add_default_save_button ($sections)
add_field ($name, $fields, $settings, $pos)
add_field_after ($name, $fields, $settings)
add_field_before ($name, $fields, $settings)
app_settings ()
Override this function to add a custom app settings page.
app_settings_icon ()
Override this function to specific a custom app settings icon.
app_settings_title ()
Override this function to specific a custom app settings title.
app_settings_uninstall_tab ()
Renders the app settings uninstall tab.
app_tab_page_footer ()
Renders the footer for the tabs UI.
app_tab_page_header ($tabs, $current_tab, $title, $message= '')
Renders the header for the tabs UI.
checkbox_input ($choice, $attributes, $value, $tooltip)
Returns the markup for an individual checkbox input and its associated label.
checkbox_item ($choice, $horizontal_class, $attributes, $value, $tooltip, $error_icon='')
Returns the markup for an individual checkbox item give the parameters.
current_user_can_any ($caps)
Checks whether the current user is assigned to a capability or role.
field_failed_validation ($field)
Checks if the specified field failed validation.
field_map_title ()
form_settings ($form)
Custom form settings page Override this function to implement a complete custom form settings page.
form_settings_fields ($form)
Override this function to specify the settings fields to be rendered on the form settings page.
form_settings_icon ()
Override this function to customize the form settings icon.
form_settings_init ()
Initializes form settings page Hooks up the required scripts and actions for the Form Settings page.
form_settings_page_title ()
Custom form settings title Override this function to display a custom title on the Form Settings Page.
get_app_menu_icon ()
Override this function to specify a custom icon for the top level app menu.
get_app_menu_items ()
Override this function to create a top level app menu.
get_app_setting ($setting_name)
Get app setting Returns the app setting specified by the $setting_name parameter.
get_app_settings ()
Returns the currently saved plugin settings.
get_choice_attributes ($choice, $field_attributes, $default_choice_attributes=array())
Parses the properties of the $choice meta array and returns a set of HTML attributes to be added to the HTML element.
get_current_form ()
Returns the current form object based on the id query var.
get_current_settings ()
get_entry_meta ($entry_meta, $form_id)
Override this method to activate and configure entry meta.
get_error_icon ($field)
Gets the invalid field icon Returns the markup for an alert icon to indicate and highlight invalid fields.
get_field ($name, $settings)
get_field_attributes ($field, $default=array())
Parses the properties of the $field meta array and returns a set of HTML attributes to be added to the HTML element.
get_field_errors ($field=false)
Gets the validation errors for a field.
get_form_settings ($form)
Returns the form settings for the Add-On.
get_full_address ($entry, $field_id)
Returns the combined value of the specified Address field.
get_full_name ($entry, $field_id)
Returns the combined value of the specified Name field.
get_list_field_value ($entry, $field_id, $field)
Returns the value of the specified List field.
get_mapped_field_value ($setting_name, $form, $entry, $settings=false)
Returns the value of the mapped field.
get_plugin_settings_url ()
Returns the unescaped URL for the plugin settings tab associated with this plugin.
get_posted_settings ()
get_previous_settings ()
get_required_indicator ($field)
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
get_save_button ($sections)
get_save_error_message ($sections)
get_save_success_message ($sections)
get_select_option ($choice, $selected_value)
Prepares an HTML string for a single drop down field option.
get_setting ($setting_name, $default_value= '', $settings=false)
get_short_title ()
Returns this plugin's short title.
has_members_plugin ()
Checks whether the Members plugin is installed and activated.
has_setting_field_type ($type, $fields)
init_admin ()
Override this function to add initialization code (i.e.
init_ajax ()
Override this function to add AJAX hooks or to add initialization code when an AJAX request is being performed.
init_frontend ()
Override this function to add initialization code (i.e.
is_app_settings ($tab= '')
Returns TRUE if the current page is the app settings main page, or a specific apps settings tab (specified by the $tab parameter).
is_entry_edit ()
Returns TRUE if the current page is the entry edit page.
is_entry_list ()
is_entry_view ()
Returns TRUE if the current page is the entry view page.
is_form_editor ()
Returns TRUE if the current page is the form editor page.
is_form_settings ($tab=null)
Returns TRUE if the current page is the form settings page, or a specific form settings tab (specified by the $tab parameter).
is_plugin_page ()
Returns TRUE if the current page is the plugin page.
is_plugin_settings ($tab= '')
Returns TRUE if the current page is the plugin settings main page, or a specific plugin settings tab (specified by the $tab parameter).
is_postback ()
Returns TRUE if the current request is a postback, otherwise returns FALSE.
is_preview ()
Returns TRUE if the current page is the preview page.
is_print ()
Returns TRUE if the current page is the print page.
is_results ()
Returns TRUE if the current page is the results page.
is_save_postback ()
Returns TRUE if the settings "Save" button was pressed.
maybe_save_app_settings ()
Saves the plugin settings if the submit button was pressed.
maybe_save_plugin_settings ()
Saves the plugin settings if the submit button was pressed.
method_is_overridden ($method_name, $base_class= 'GFAddOn')
plugin_page ()
Override this function to create a custom plugin page.
plugin_page_icon ()
Override this function to customize the plugin page icon.
plugin_page_init ()
Initializes plugin settings page Hooks up the required scripts and actions for the Plugin Settings page.
plugin_page_title ()
Override this function to customize the plugin page title.
plugin_settings ()
Override this function to add a custom settings page.
plugin_settings_icon ()
plugin_settings_init ()
prepend_attribute ($name, $attribute, $current_attribute)
remove_field ($name, $settings)
render_settings ($sections)
replace_field ($name, $fields, $settings)
results_page_init ($results_page_config)
Initializes the result page functionality.
scripts ()
Override this function to provide a list of scripts to be enqueued.
set_field_error ($field, $error_message= '')
Sets the validation error message Sets the error message to be displayed when a field fails validation.
set_previous_settings ($settings)
set_settings ($settings)
setting_dependency_met ($dependency)
settings ($sections)
settings_checkbox ($field, $echo=true)
settings_fields_only ($settings_type= 'plugin')
Returns an flattened array of field settings for the specified settings type ignoring sections.
settings_hidden ($field, $echo=true)
settings_radio ($field, $echo=true)
settings_save ($field, $echo=true)
settings_select ($field, $echo=true)
settings_select_custom ($field, $echo=true)
Renders and initializes a drop down field with a input field for custom input based on the $field array.
settings_text ($field, $echo=true)
settings_textarea ($field, $echo=true)
setup ()
Performs upgrade tasks when the version of the Add-On changes.
simple_condition ($setting_name_root)
Helper to create a simple conditional logic set of fields.
single_section ($section, $is_first=false)
single_setting ($field)
single_setting_label ($field)
Displays the label for a field, including the tooltip and requirement indicator.
single_setting_row ($field)
single_setting_row_save ($field)
styles ()
Override this function to provide a list of styles to be enqueued.
uninstall ()
Called when the user chooses to uninstall the Add-On - after permissions have been checked and before removing all Add-On settings and Form settings.
uninstall_confirm_message ()
uninstall_warning_message ()
update_app_settings ($settings)
Updates app settings with the provided settings.
update_plugin_settings ($settings)
Updates plugin settings with the provided settings.
upgrade ($previous_version)
Override this function to add to add database update scripts or any other code to be executed when the Add-On version changes.
validate_checkbox_settings ($field, $settings)
validate_field_map_settings ($field, $settings)
validate_select_custom_settings ($field, $settings)
validate_settings ($fields, $settings)
Validates settings fields.
Static Protected Member Functions
static is_json ($value)
static maybe_decode_json ($value)
Protected Attributes
$_capabilities = array()
$_capabilities_app_menu = array()
$_capabilities_app_settings = array()
$_capabilities_form_settings = array()
$_capabilities_plugin_page = array()
$_capabilities_settings_page = array()
$_capabilities_uninstall = array()
$_enable_rg_autoupgrade = false
$_full_path
$_min_gravityforms_version
$_path
$_short_title
$_slug
$_title
$_url
$_version
Private Member Functions
_can_enqueue_script ($enqueue_conditions, $form, $is_ajax)
_field_condition_matches ($field_types, $form)
_page_condition_matches ($pages, $tab)
_request_condition_matches ($request, $query)
_tab_matches ($tabs)
add_no_conflict_scripts ($scripts)
Adds scripts to the list of white-listed no conflict scripts.
add_no_conflict_styles ($styles)
Adds styles to the list of white-listed no conflict styles.
get_parent_menu ($menu_items, $addon_menus)
Returns the parent menu item.
has_form_settings_page ()
Checks whether the current Add-On has a form settings page.
has_plugin_page ()
Checks whether the current Add-On has a plugin page.
Static Private Member Functions
static _get_base_path ()
Returns the physical path of the Add-On Framework root folder.
static _get_base_url ()
Returns the URL of the Add-On Framework root folder.
Private Attributes
$_no_conflict_scripts = array()
$_no_conflict_styles = array()
$_preview_styles = array()
$_previous_settings = array()
$_print_styles = array()
$_saved_settings = array()
$_setting_field_errors = array()
Static Private Attributes
static $_registered_addons = array('active' => array(), 'inactive' => array())
Detailed Description
Definition at line 14 of file class-gf-addon.php.
Constructor & Destructor Documentation
__construct ()
Class constructor which hooks the instance into the WordPress init action.
Definition at line 110 of file class-gf-addon.php.
References add_action(), is_gravityforms_supported(), and pre_init().
Member Function Documentation
_can_enqueue_script ($enqueue_conditions, $form, $is_ajax) private
Definition at line 615 of file class-gf-addon.php.
References $form, _field_condition_matches(), _page_condition_matches(), and _request_condition_matches().
Referenced by enqueue_print_styles(), and enqueue_scripts().
_field_condition_matches ($field_types, $form) private
Definition at line 741 of file class-gf-addon.php.
References $form, and GFAPI\get_fields_by_type().
Referenced by _can_enqueue_script().
static _get_base_path () static private
Returns the physical path of the Add-On Framework root folder.
Returns
string
Definition at line 4533 of file class-gf-addon.php.
static _get_base_url () static private
Returns the URL of the Add-On Framework root folder.
Returns
string
Definition at line 4544 of file class-gf-addon.php.
_page_condition_matches ($pages, $tab) private
Definition at line 664 of file class-gf-addon.php.
References $page, is_app_settings(), is_entry_edit(), is_entry_list(), is_entry_view(), is_form_editor(), is_form_settings(), is_plugin_page(), is_plugin_settings(), and is_results().
Referenced by _can_enqueue_script().
_request_condition_matches ($request, $query) private
Definition at line 638 of file class-gf-addon.php.
References $value.
Referenced by _can_enqueue_script().
_tab_matches ($tabs) private
Definition at line 4660 of file class-gf-addon.php.
References $tabs, and null.
add_default_save_button ($sections) protected
Definition at line 1264 of file class-gf-addon.php.
Referenced by render_settings().
add_field ($name, $fields, $settings, $pos) protected
Definition at line 2829 of file class-gf-addon.php.
add_field_after ($name, $fields, $settings) protected
Definition at line 2825 of file class-gf-addon.php.
add_field_before ($name, $fields, $settings) protected
Definition at line 2821 of file class-gf-addon.php.
add_form_settings_menu ($tabs, $form_id)
Add the form settings tab.
Override this function to add the tab conditionally.
Parameters
$tabs
$form_id
Returns
array
Definition at line 3429 of file class-gf-addon.php.
add_no_conflict_scripts ($scripts) private
Adds scripts to the list of white-listed no conflict scripts.
Parameters
$scripts
Definition at line 601 of file class-gf-addon.php.
Referenced by enqueue_scripts().
add_no_conflict_styles ($styles) private
Adds styles to the list of white-listed no conflict styles.
Parameters
$styles
Definition at line 611 of file class-gf-addon.php.
References $styles.
Referenced by enqueue_print_styles(), and enqueue_scripts().
add_note ($entry_id, $note, $note_type = null)
Definition at line 4461 of file class-gf-addon.php.
References $user_id, and GFFormsModel\add_note().
Referenced by GFPaymentAddOn\add_pending_payment(), GFPaymentAddOn\add_subscription_payment(), GFPaymentAddOn\cancel_subscription(), GFPaymentAddOn\complete_payment(), GFPaymentAddOn\expire_subscription(), GFPaymentAddOn\fail_payment(), GFPaymentAddOn\fail_subscription_payment(), GFPaymentAddOn\process_subscription(), GFPaymentAddOn\refund_payment(), GFPaymentAddOn\start_subscription(), and GFPaymentAddOn\void_authorization().
app_settings () protected
Override this function to add a custom app settings page.
Definition at line 3838 of file class-gf-addon.php.
app_settings_fields ()
Override this function to specify the settings fields to be rendered on the plugin settings page.
Returns
array
Definition at line 3909 of file class-gf-addon.php.
app_settings_icon () protected
Override this function to specific a custom app settings icon.
Returns
string
Definition at line 3822 of file class-gf-addon.php.
app_settings_tab ()
Definition at line 3765 of file class-gf-addon.php.
app_settings_title () protected
Override this function to specific a custom app settings title.
Returns
string
Definition at line 3813 of file class-gf-addon.php.
app_settings_uninstall_tab () protected
Renders the app settings uninstall tab.
Not intended to be overridden or called directly by add-ons.
Definition at line 3653 of file class-gf-addon.php.
app_tab_page ()
Handles the rendering of app menu items that implement the tabs UI.
Not intended to be overridden or called directly by add-ons.
Definition at line 3336 of file class-gf-addon.php.
app_tab_page_footer () protected
Renders the footer for the tabs UI.
Definition at line 3745 of file class-gf-addon.php.
app_tab_page_header ($tabs, $current_tab, $title, $message = '') protected
Renders the header for the tabs UI.
Parameters
$tabs
$current_tab
$title
string $message
Definition at line 3702 of file class-gf-addon.php.
build_choices ($key_value_pairs)
Definition at line 2894 of file class-gf-addon.php.
checkbox_input ($choice, $attributes, $value, $tooltip) protected
Returns the markup for an individual checkbox input and its associated label.
Parameters
$choice - Choice array with all configured properties
$attributes - String containing all the attributes for the input tag.
$value - Currently selection (1 if field has been checked. 0 or null otherwise)
$tooltip - String containing a tooltip for this checkbox item.
Returns
string - The markup of an individual checkbox input and its associated label
Definition at line 1523 of file class-gf-addon.php.
checkbox_item ($choice, $horizontal_class, $attributes, $value, $tooltip, $error_icon = '') protected
Returns the markup for an individual checkbox item give the parameters.
Parameters
$choice - Choice array with all configured properties
$horizontal_class - CSS class to style checkbox items horizontally
$attributes - String containing all the attributes for the input tag.
$value - Currently selection (1 if field has been checked. 0 or null otherwise)
$tooltip - String containing a tooltip for this checkbox item.
Returns
string - The markup of an individual checkbox item
Definition at line 1496 of file class-gf-addon.php.
create_app_menu ()
Creates a top level app menu.
Adds the app settings page automatically if it's configured. Target of the WordPress admin_menu action. Not intended to be overridden or called directly by add-ons.
Filters through addon menus (filter by addon slugs)
Parameters
array $addon_menus A modifiable array of admin addon menus
Modify the menu position of an add-on menu
Parameters
int $menu_position The Menu position of the add-on menu
Definition at line 3190 of file class-gf-addon.php.
create_plugin_page_menu ($menus)
Creates plugin page menu item Target of gform_addon_navigation filter.
Creates a menu item in the left nav, linking to the plugin page
Parameters
$menus - Current list of menu items
Returns
array - Returns a new list of menu items
Definition at line 2955 of file class-gf-addon.php.
current_user_can_any ($caps) protected
Checks whether the current user is assigned to a capability or role.
Parameters
string | array $caps An string or array of capabilities to check
Returns
bool Returns true if the current user is assigned to any of the capabilities.
Definition at line 893 of file class-gf-addon.php.
Referenced by init_admin(), and GFFeedAddOn\maybe_save_feed_settings().
static display_plugin_message ($message, $is_error = false) static
Formats and outs a message for the plugin row.
Not intended to be overridden or called directly by Add-Ons.
Parameters
$message
bool $is_error
Definition at line 4106 of file class-gf-addon.php.
References $message.
Referenced by GFAutoUpgrade\rg_plugin_row().
enqueue_preview_styles ($preview_styles, $form)
Target of gform_preview_styles.
Enqueue styles to the preview page. Not intended to be overridden by child classes
Definition at line 563 of file class-gf-addon.php.
enqueue_print_styles ($print_styles, $form)
Target of gform_print_styles.
Enqueue styles to the print entry page. Not intended to be overridden by child classes
Definition at line 574 of file class-gf-addon.php.
References $form, $styles, _can_enqueue_script(), _print_styles(), add_no_conflict_styles(), styles(), and wp_register_style().
enqueue_scripts ($form = '', $is_ajax = false)
Target of admin_enqueue_scripts and gform_enqueue_scripts hooks.
Not intended to be overridden by child classes. In order to enqueue scripts and styles, override the scripts() and styles() functions
Definition at line 509 of file class-gf-addon.php.
References $form, $styles, _can_enqueue_script(), _print_styles(), add_no_conflict_scripts(), add_no_conflict_styles(), elseif, get_current_form(), is_preview(), is_print(), scripts(), styles(), wp_enqueue_script(), wp_enqueue_style(), wp_localize_script(), wp_register_script(), and wp_register_style().
field_failed_validation ($field) protected
Checks if the specified field failed validation.
Parameters
$field - The field meta to be checked
Returns
bool|mixed - Returns a validation error string if the field has failed validation. Otherwise returns false
Definition at line 2778 of file class-gf-addon.php.
Referenced by settings_text(), and settings_textarea().
field_map_table_header ()
Definition at line 1780 of file class-gf-addon.php.
field_map_title () protected
Definition at line 1813 of file class-gf-addon.php.
filter_settings ($fields, $settings)
Filter settings fields.
Runs through each field and applies the 'save_callback', if set, before saving the settings. To specify a custom save filter, use the 'save_callback' field meta property and implement the save filter function with the custom logic.
Parameters
$fields - A list of all fields from the field meta configuration
$settings - A list of submitted settings values
Returns
$settings - The updated settings values.
Definition at line 2794 of file class-gf-addon.php.
Referenced by GFFeedAddOn\maybe_save_feed_settings().
form_settings ($form) protected
Custom form settings page Override this function to implement a complete custom form settings page.
Before overriding this function, consider using the form_settings_fields() and specifying your field meta.
Definition at line 3101 of file class-gf-addon.php.
form_settings_fields ($form) protected
Override this function to specify the settings fields to be rendered on the form settings page.
Definition at line 3439 of file class-gf-addon.php.
form_settings_icon () protected
Override this function to customize the form settings icon.
Definition at line 3117 of file class-gf-addon.php.
form_settings_init () protected
Initializes form settings page Hooks up the required scripts and actions for the Form Settings page.
Definition at line 2921 of file class-gf-addon.php.
Referenced by init_admin().
form_settings_page ()
Renders the form settings page.
Not intended to be overridden or called directly by Add-Ons. Sets up the form settings page.
Definition at line 2970 of file class-gf-addon.php.
form_settings_page_title () protected
Custom form settings title Override this function to display a custom title on the Form Settings Page.
By default, the first section in the configuration done in form_settings_fields() will be used as the page title. Use this function to override that behavior and add a custom page title.
Definition at line 3110 of file class-gf-addon.php.
static get_all_deprecated_protected_methods ($add_on_class_name = '') static
Definition at line 4799 of file class-gf-addon.php.
References $deprecated.
Referenced by GFForms\deprecate_add_on_methods(), and has_deprecated_elements().
get_app_menu_icon () protected
Override this function to specify a custom icon for the top level app menu.
Accepts a dashicon class or a URL.
Returns
string
Definition at line 3308 of file class-gf-addon.php.
get_app_menu_items () protected
Override this function to create a top level app menu.
e.g. $menu_item['name'] = 'gravitycontacts'; $menu_item['label'] = __("Contacts", 'gravitycontacts'); $menu_item['permission'] = 'gravitycontacts_view_contacts'; $menu_item['callback'] = array($this, 'app_menu');
Returns
array The array of menu items
Definition at line 3298 of file class-gf-addon.php.
get_app_setting ($setting_name) protected
Get app setting Returns the app setting specified by the $setting_name parameter.
Parameters
string $setting_name - Plugin setting to be returned
Returns
mixed - Returns the specified plugin setting or null if the setting doesn't exist
Definition at line 3857 of file class-gf-addon.php.
get_app_settings () protected
Returns the currently saved plugin settings.
Returns
mixed
Definition at line 3845 of file class-gf-addon.php.
get_app_settings_tabs ()
Returns the tabs for the settings app menu item.
Not intended to be overridden or called directly by add-ons.
Returns
array|mixed|void
Definition at line 3631 of file class-gf-addon.php.
get_base_path ($full_path = '')
Returns the physical path of the plugins root folder.
Parameters
string $full_path
Returns
string
Definition at line 4519 of file class-gf-addon.php.
get_base_url ($full_path = '')
Returns the url of the root folder of the current Add-On.
Parameters
string $full_path Optional. The full path the the plugin file.
Returns
string
Definition at line 4486 of file class-gf-addon.php.
References null, and plugins_url().
get_choice_attributes ($choice, $field_attributes, $default_choice_attributes = array()) protected
Parses the properties of the $choice meta array and returns a set of HTML attributes to be added to the HTML element.
Parameters
array $choice - current choice meta to be parsed.
array $field_attributes - current field's attributes.
Returns
array - resulting HTML attributes ready to be included in the HTML element.
Definition at line 2529 of file class-gf-addon.php.
get_current_form () protected
Returns the current form object based on the id query var.
Otherwise returns false
Definition at line 4610 of file class-gf-addon.php.
References GFFormsModel\get_form_meta().
Referenced by enqueue_scripts(), GFPaymentAddOn\feed_list_message(), GFPaymentAddOn\get_column_value_amount(), GFPaymentAddOn\product_amount_choices(), GFPaymentAddOn\recurring_amount_choices(), GFPaymentAddOn\settings_setup_fee(), and GFPaymentAddOn\settings_trial().
get_current_settings () protected
Definition at line 1145 of file class-gf-addon.php.
References $_saved_settings, and get_posted_settings().
Referenced by get_setting().
static get_deprecated_protected_methods_for_base_class ($base_class_name, $add_on_class_name = '') static
Definition at line 4807 of file class-gf-addon.php.
References $class, and $deprecated.
static get_dynamic_field_map_fields ($feed, $field_name) static
Definition at line 1947 of file class-gf-addon.php.
get_entry_meta ($entry_meta, $form_id) protected
Override this method to activate and configure entry meta.
Parameters
array $entry_meta An array of entry meta already registered with the gform_entry_meta filter.
int $form_id The form id
Returns
array The filtered entry meta array.
Definition at line 799 of file class-gf-addon.php.
get_error_icon ($field) protected
Gets the invalid field icon Returns the markup for an alert icon to indicate and highlight invalid fields.
Parameters
array $field - The field meta.
Returns
string - The full markup for the icon
Definition at line 2747 of file class-gf-addon.php.
Referenced by settings_text(), and settings_textarea().
get_field ($name, $settings) protected
Definition at line 2882 of file class-gf-addon.php.
get_field_attributes ($field, $default = array()) protected
Parses the properties of the $field meta array and returns a set of HTML attributes to be added to the HTML element.
Parameters
array $field - current field meta to be parsed.
array $default - default set of properties. Will be appended to the properties specified in the $field array
Returns
array - resulting HTML attributes ready to be included in the HTML element.
Each nonstandard property will be extracted from the $props array so it is not auto-output in the field HTML
Parameters
array $field The current field meta to be parsed
Definition at line 2455 of file class-gf-addon.php.
Referenced by settings_hidden(), GravityView_Settings\settings_submit(), settings_text(), and settings_textarea().
get_field_errors ($field = false) protected
Gets the validation errors for a field.
Returns validation errors associated with the specified field or a list of all validation messages (if a field isn't specified)
Parameters
array | boolean $field - Optional. The field meta. When specified, errors for this field will be returned
Returns
mixed - If a field is specified, a string containing the error message will be returned. Otherwise, an array of all errors will be returned
Definition at line 2730 of file class-gf-addon.php.
static get_field_map_choices ($form_id, $field_type = null, $exclude_field_types = null) static
Definition at line 1817 of file class-gf-addon.php.
static get_field_map_fields ($feed, $field_name) static
Definition at line 1932 of file class-gf-addon.php.
get_field_value ($form, $entry, $field_id)
Returns the value of the selected field.
private
Parameters
array $form
array $entry
string $field_id
Returns
string field value
Definition at line 4278 of file class-gf-addon.php.
References $field, $field_id, $form, elseif, and GFFormsModel\get_field().
Referenced by GFPaymentAddOn\get_submission_data().
get_first_field_by_type ($field_type, $subfield_id = null, $form_id = null, $return_first_only = true)
Returns the field ID of the first field of the desired type.
public
Parameters
string $field_type
int $subfield_id (default: null)
int $form_id (default: null)
Returns
string
Definition at line 4409 of file class-gf-addon.php.
References $form, $form_id, GFAPI\get_fields_by_type(), GFAPI\get_form(), and null.
get_form_fields_as_choices ($form, $args = array())
Retrieve an array of form fields formatted for select, radio and checkbox settings fields.
public
Parameters
array $form - The form object
array $args - Additional settings to check for (field and input types to include, callback for applicable input type)
Returns
array The array of formatted form fields
Definition at line 2158 of file class-gf-addon.php.
get_form_settings ($form) protected
Returns the form settings for the Add-On.
Parameters
$form
Returns
string
Definition at line 3414 of file class-gf-addon.php.
get_full_address ($entry, $field_id) protected
Returns the combined value of the specified Address field.
Parameters
array $entry
string $field_id
Returns
string
Definition at line 4368 of file class-gf-addon.php.
References $field_id, and GF_Fields\get().
get_full_name ($entry, $field_id) protected
Returns the combined value of the specified Name field.
Parameters
array $entry
string $field_id
Returns
string
Definition at line 4381 of file class-gf-addon.php.
References $field_id, and GF_Fields\get().
static get_gfaddon_base_path () static final
Returns the physical path of the Add-On Framework root folder.
Returns
string
Definition at line 4508 of file class-gf-addon.php.
static get_gfaddon_base_url () static final
Returns the url of the Add-On Framework root folder.
Returns
string
Definition at line 4499 of file class-gf-addon.php.
References null, and plugins_url().
Referenced by scripts(), GFPaymentAddOn\scripts(), and styles().
get_list_field_value ($entry, $field_id, $field) protected
Returns the value of the specified List field.
Parameters
array $entry
string $field_id
object $field
Returns
string
Definition at line 4395 of file class-gf-addon.php.
References $field, and $field_id.
get_locking_config ()
Returns the configuration for locking.
e.g.
array("object_type" => 'contact', "capabilities" => array("gravityforms_contacts_edit_contacts"), "redirect_url" => admin_url("admin.php?page=gf_contacts"), "edit_url" => admin_url(sprintf("admin.php?page=gf_contacts&id=%d", $contact_id)), "strings" => $strings);
Override this method to implement locking
Definition at line 4158 of file class-gf-addon.php.
Referenced by init_admin(), and init_ajax().
get_locking_object_id ()
Returns the ID of the object to be locked.
E.g. Form ID
Override this method to implement locking
Definition at line 4195 of file class-gf-addon.php.
get_mapped_field_name ($parent_field, $field_name)
Definition at line 1928 of file class-gf-addon.php.
get_mapped_field_value ($setting_name, $form, $entry, $settings = false) protected
Returns the value of the mapped field.
Parameters
string $setting_name
array $form
array $entry
mixed $settings
Returns
string
Definition at line 4260 of file class-gf-addon.php.
References $field_id, and $form.
get_parent_menu ($menu_items, $addon_menus) private
Returns the parent menu item.
Parameters
$menu_items
$addon_menus
Returns
array|bool The parent menu araray or false if none
Definition at line 3264 of file class-gf-addon.php.
get_plugin_setting ($setting_name)
Get plugin setting Returns the plugin setting specified by the $setting_name parameter.
Parameters
string $setting_name - Plugin setting to be returned
Returns
mixed - Returns the specified plugin setting or null if the setting doesn't exist
Definition at line 3565 of file class-gf-addon.php.
get_plugin_settings ()
Returns the currently saved plugin settings.
Returns
mixed
Definition at line 3553 of file class-gf-addon.php.
get_plugin_settings_url () protected
Returns the unescaped URL for the plugin settings tab associated with this plugin.
Definition at line 4603 of file class-gf-addon.php.
References add_query_arg(), and admin_url().
get_posted_settings () protected
Definition at line 1107 of file class-gf-addon.php.
References $value, and stripslashes_deep().
Referenced by get_current_settings(), and GFFeedAddOn\maybe_save_feed_settings().
get_previous_settings () protected
Definition at line 1099 of file class-gf-addon.php.
References $_previous_settings.
static get_registered_addons () static
Gets all active, registered Add-Ons.
Returns
array - Active, registered Add-Ons
Definition at line 157 of file class-gf-addon.php.
Referenced by GFForms\enqueue_form_scripts().
get_required_indicator ($field) protected
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
Parameters
$field - The field meta.
Returns
string - Returns markup of the required indicator symbol
Definition at line 2767 of file class-gf-addon.php.
Referenced by single_setting_label().
get_results_page_config ()
Returns the configuration for the results page.
By default this is not activated. To activate the results page override this function and return an array with the configuration data.
Example: public function get_results_page_config() { return array("title" => 'Quiz Results', "capabilities" => array("gravityforms_quiz_results"), "callbacks" => array("fields" => array($this, 'results_fields'), "calculation" => array($this, 'results_calculation'), "markup" => array($this, 'results_markup'),)); }
Definition at line 823 of file class-gf-addon.php.
Referenced by init_admin(), and init_ajax().
get_save_button ($sections) protected
Definition at line 1282 of file class-gf-addon.php.
References $field.
Referenced by GFFeedAddOn\get_save_error_message(), get_save_error_message(), GFFeedAddOn\get_save_success_message(), and get_save_success_message().
get_save_error_message ($sections) protected
Definition at line 1276 of file class-gf-addon.php.
References esc_html__(), and get_save_button().
get_save_success_message ($sections) protected
Definition at line 1270 of file class-gf-addon.php.
References esc_html__(), and get_save_button().
get_select_option ($choice, $selected_value) protected
Prepares an HTML string for a single drop down field option.
protected
Parameters
array $choice - Array containing the settings for the drop down option
string $selected_value - The value currently selected for the field
Returns
string The HTML for the select choice
Definition at line 1720 of file class-gf-addon.php.
get_select_options ($choices, $selected_value)
Prepares an HTML string of options for a drop down field.
Parameters
array $choices - Array containing all the options for the drop down field
string $selected_value - The value currently selected for the field
Returns
string The HTML for the select options
Definition at line 1687 of file class-gf-addon.php.
get_setting ($setting_name, $default_value = '', $settings = false) protected
Definition at line 1166 of file class-gf-addon.php.
References get_current_settings().
Referenced by GFPaymentAddOn\feed_settings_fields(), setting_dependency_met(), GFPaymentAddOn\settings_billing_cycle(), settings_hidden(), GFPaymentAddOn\settings_setup_fee(), GravityView_Settings\settings_submit(), settings_text(), settings_textarea(), and GFPaymentAddOn\settings_trial().
get_short_title () protected
Returns this plugin's short title.
Used to display the plugin title in small areas such as tabs
Definition at line 4595 of file class-gf-addon.php.
Referenced by GFFeedAddOn\feed_list_title().
has_app_menu ()
Checks whether the current Add-On has a top level app menu.
Returns
bool
Definition at line 3181 of file class-gf-addon.php.
has_app_settings ()
Checks whether the current Add-On has a settings page.
Returns
bool
Definition at line 3831 of file class-gf-addon.php.
has_deprecated_elements ()
Definition at line 4790 of file class-gf-addon.php.
References $deprecated, and get_all_deprecated_protected_methods().
has_form_settings_page () private
Checks whether the current Add-On has a form settings page.
Returns
bool
Definition at line 3092 of file class-gf-addon.php.
has_members_plugin () protected
Checks whether the Members plugin is installed and activated.
Not intended to be overridden or called directly by Add-Ons.
Returns
bool
Definition at line 867 of file class-gf-addon.php.
has_plugin_page () private
Checks whether the current Add-On has a plugin page.
Returns
bool
Definition at line 3126 of file class-gf-addon.php.
has_plugin_settings_page ()
Checks whether the current Add-On has a settings page.
Returns
bool
Definition at line 3545 of file class-gf-addon.php.
has_setting_field_type ($type, $fields) protected
Definition at line 1251 of file class-gf-addon.php.
References $field.
Referenced by render_settings().
init ()
Plugin starting point.
Handles hooks and loading of language files.
Definition at line 193 of file class-gf-addon.php.
References $locale, add_filter(), apply_filters(), elseif, get_locale(), init_admin(), init_ajax(), init_frontend(), is_admin(), is_gravityforms_supported(), load_plugin_textdomain(), and load_textdomain().
static init_addons () static
Initializes all addons.
Definition at line 164 of file class-gf-addon.php.
Referenced by GFForms\loaded().
init_admin () protected
Override this function to add initialization code (i.e.
hooks) for the admin site (WP dashboard)
Definition at line 225 of file class-gf-addon.php.
References add_action(), add_filter(), current_user_can_any(), form_settings_init(), get_locking_config(), get_results_page_config(), is_gravityforms_supported(), method_is_overridden(), plugin_page_init(), plugin_settings_init(), results_page_init(), and setup().
Referenced by init().
init_ajax () protected
Override this function to add AJAX hooks or to add initialization code when an AJAX request is being performed.
Definition at line 311 of file class-gf-addon.php.
References add_action(), elseif, get_locking_config(), get_results_page_config(), and method_is_overridden().
Referenced by init().
init_frontend () protected
Override this function to add initialization code (i.e.
hooks) for the public (customer facing) site
Definition at line 298 of file class-gf-addon.php.
References add_action(), add_filter(), and setup().
Referenced by init().
is_app_settings ($tab = '') protected
Returns TRUE if the current page is the app settings main page, or a specific apps settings tab (specified by the $tab parameter).
Otherwise returns FALSE
Parameters
string $tab - Specifies a specific app setting page/tab.
Returns
bool
Definition at line 4704 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_entry_edit () protected
Returns TRUE if the current page is the entry edit page.
Otherwise, returns FALSE
Returns
bool
Definition at line 4741 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_entry_list () protected
Definition at line 4749 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_entry_view () protected
Returns TRUE if the current page is the entry view page.
Otherwise, returns FALSE
Returns
bool
Definition at line 4729 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_form_editor () protected
Returns TRUE if the current page is the form editor page.
Otherwise, returns FALSE
Definition at line 4632 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_form_settings ($tab = null) protected
Returns TRUE if the current page is the form settings page, or a specific form settings tab (specified by the $tab parameter).
Otherwise returns FALSE
Parameters
string $tab - Specifies a specific form setting page/tab
Returns
bool
Definition at line 4648 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_gravityforms_installed ()
Checks whether the Gravity Forms is installed.
Returns
bool
Definition at line 4555 of file class-gf-addon.php.
is_gravityforms_supported ($min_gravityforms_version = '')
Checks whether the current version of Gravity Forms is supported.
Parameters
$min_gravityforms_version
Returns
bool|mixed
Definition at line 4574 of file class-gf-addon.php.
Referenced by __construct(), init(), init_admin(), and pre_init().
static is_json ($value) static protected
Definition at line 1134 of file class-gf-addon.php.
References $value, and ARRAY_A.
is_locking_edit_page ()
Returns TRUE if the current page is the edit page.
Otherwise, returns FALSE
Override this method to implement locking on the edit page.
Definition at line 4168 of file class-gf-addon.php.
is_locking_list_page ()
Returns TRUE if the current page is the list page.
Otherwise, returns FALSE
Override this method to display locking info on the list page.
Definition at line 4177 of file class-gf-addon.php.
is_locking_view_page ()
Returns TRUE if the current page is the view page.
Otherwise, returns FALSE
Override this method to display locking info on the view page.
Definition at line 4186 of file class-gf-addon.php.
is_object_locked ($object_id)
Checked whether an object is locked.
Parameters
int | mixed $object_id The object ID
Returns
bool
Definition at line 4242 of file class-gf-addon.php.
is_plugin_page () protected
Returns TRUE if the current page is the plugin page.
Otherwise returns FALSE
Returns
bool
Definition at line 4720 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_plugin_settings ($tab = '') protected
Returns TRUE if the current page is the plugin settings main page, or a specific plugin settings tab (specified by the $tab parameter).
Otherwise returns FALSE
Parameters
string $tab - Specifies a specific plugin setting page/tab.
Returns
bool
Definition at line 4685 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_postback () protected
Returns TRUE if the current request is a postback, otherwise returns FALSE.
Definition at line 4618 of file class-gf-addon.php.
is_preview () protected
Returns TRUE if the current page is the preview page.
Otherwise, returns FALSE
Definition at line 4782 of file class-gf-addon.php.
Referenced by enqueue_scripts().
is_print () protected
Returns TRUE if the current page is the print page.
Otherwise, returns FALSE
Definition at line 4771 of file class-gf-addon.php.
Referenced by enqueue_scripts().
is_results () protected
Returns TRUE if the current page is the results page.
Otherwise, returns FALSE
Definition at line 4760 of file class-gf-addon.php.
Referenced by _page_condition_matches().
is_save_postback () protected
Returns TRUE if the settings "Save" button was pressed.
Definition at line 4625 of file class-gf-addon.php.
Referenced by GravityView_Settings\maybe_save_app_settings().
list_row_class ($object_id, $echo = true)
Outputs class for the row for the specified Object ID on the list page.
Parameters
int $object_id The object ID
bool $echo Whether to echo
Returns
string The markup for the class
Definition at line 4225 of file class-gf-addon.php.
References $class.
load_screen_options ()
Override this function to load custom screen options.
e.g. $screen = get_current_screen(); if(!is_object($screen) || $screen->id != $this->app_hook_suffix) return;
if($this->is_contact_list_page()){ $args = array('label' => __('Contacts per page', 'gravitycontacts'), 'default' => 20, 'option' => 'gcontacts_per_page'); add_screen_option('per_page', $args);
Definition at line 3328 of file class-gf-addon.php.
lock_info ($object_id, $echo = true)
Outputs information about the user currently editing the specified object.
Parameters
int $object_id The Object ID
bool $echo Whether to echo
Returns
string The markup for the lock info
Definition at line 4207 of file class-gf-addon.php.
log_debug ($message)
Writes an error message to the Gravity Forms log.
Requires the Gravity Forms logging Add-On.
Not intended to be overridden by Add-Ons.
Definition at line 4134 of file class-gf-addon.php.
References $message.
Referenced by GFPaymentAddOn\add_pending_payment(), GFPaymentAddOn\add_subscription_payment(), GFPaymentAddOn\cancel_subscription(), GFPaymentAddOn\complete_payment(), GFPaymentAddOn\expire_subscription(), GFPaymentAddOn\fail_payment(), GFPaymentAddOn\fail_subscription_payment(), GFPaymentAddOn\insert_transaction(), GFPaymentAddOn\maybe_process_callback(), GFFeedAddOn\maybe_process_feed(), GFPaymentAddOn\post_payment_action(), GFPaymentAddOn\process_callback_action(), GFPaymentAddOn\process_capture(), GFPaymentAddOn\process_subscription(), GFPaymentAddOn\refund_payment(), GFPaymentAddOn\start_subscription(), GFPaymentAddOn\validation(), and GFPaymentAddOn\void_authorization().
log_error ($message)
Writes an error message to the Gravity Forms log.
Requires the Gravity Forms logging Add-On.
Not intended to be overridden by Add-Ons.
Definition at line 4120 of file class-gf-addon.php.
References $message.
static maybe_decode_json ($value) static protected
Definition at line 1126 of file class-gf-addon.php.
References $value, and ARRAY_A.
maybe_override_field_value ($field_value, $form, $entry, $field_id)
Enables use of the gform_SLUG_field_value filter to override the field value.
Override this function to prevent the filter being used or to implement a custom filter.
Parameters
string $field_value
array $form
array $entry
string $field_id
Returns
string
Definition at line 4349 of file class-gf-addon.php.
References $field_id, $form, and str_replace.
maybe_save_app_settings () protected
Saves the plugin settings if the submit button was pressed.
Definition at line 3876 of file class-gf-addon.php.
maybe_save_form_settings ($form)
Definition at line 3036 of file class-gf-addon.php.
maybe_save_plugin_settings () protected
Saves the plugin settings if the submit button was pressed.
Definition at line 3584 of file class-gf-addon.php.
maybe_uninstall ()
Not intended to be overridden or called directly by Add-Ons.
Definition at line 3982 of file class-gf-addon.php.
members_get_capabilities ($caps)
Not intended to be overridden or called directly by Add-Ons.
Parameters
$caps
Returns
array
Definition at line 880 of file class-gf-addon.php.
method_is_overridden ($method_name, $base_class = 'GFAddOn') final protected
Definition at line 4472 of file class-gf-addon.php.
References $name.
Referenced by init_admin(), init_ajax(), and pre_init().
note_avatar ()
Override this function to specify a custom avatar (i.e.
the payment gateway logo) for entry notes created by the Add-On
Returns
string - A fully qualified URL for the avatar
Definition at line 4449 of file class-gf-addon.php.
notes_avatar ($avatar, $note)
Definition at line 4453 of file class-gf-addon.php.
plugin_message ()
Returns the message that will be displayed if the current version of Gravity Forms is not supported.
Override this method to display a custom message.
Definition at line 4090 of file class-gf-addon.php.
plugin_page () protected
Override this function to create a custom plugin page.
Definition at line 3133 of file class-gf-addon.php.
plugin_page_container ()
Plugin page container Target of the plugin menu left nav icon.
Displays the outer plugin page markup and calls plugin_page() to render the actual page. Override plugin_page() in order to provide a custom plugin page
Definition at line 3155 of file class-gf-addon.php.
plugin_page_icon () protected
Override this function to customize the plugin page icon.
Definition at line 3139 of file class-gf-addon.php.
plugin_page_init () protected
Initializes plugin settings page Hooks up the required scripts and actions for the Plugin Settings page.
Definition at line 2938 of file class-gf-addon.php.
Referenced by init_admin().
plugin_page_title () protected
Override this function to customize the plugin page title.
Definition at line 3146 of file class-gf-addon.php.
plugin_row ()
Target for the after_plugin_row action hook.
Checks whether the current version of Gravity Forms is supported and outputs a message just below the plugin info on the plugins page.
Not intended to be overridden or called directly by Add-Ons.
Definition at line 4078 of file class-gf-addon.php.
plugin_settings () protected
Override this function to add a custom settings page.
Definition at line 3537 of file class-gf-addon.php.
plugin_settings_fields ()
Override this function to specify the settings fields to be rendered on the plugin settings page.
Returns
array
Definition at line 3617 of file class-gf-addon.php.
plugin_settings_icon () protected
Definition at line 3530 of file class-gf-addon.php.
plugin_settings_init () protected
Definition at line 3446 of file class-gf-addon.php.
Referenced by init_admin().
plugin_settings_link ($links, $file)
Definition at line 3464 of file class-gf-addon.php.
plugin_settings_page ()
Plugin settings page.
Definition at line 3477 of file class-gf-addon.php.
plugin_settings_title ()
Definition at line 3526 of file class-gf-addon.php.
pre_init ()
Gets executed before all init functions.
Override this function to perform initialization tasks that must be done prior to init
Definition at line 179 of file class-gf-addon.php.
References add_filter(), is_gravityforms_supported(), and method_is_overridden().
Referenced by __construct().
prepend_attribute ($name, $attribute, $current_attribute) protected
Definition at line 2563 of file class-gf-addon.php.
References $name.
static register ($class, $overrides = null) static
Registers an addon so that it gets initialized appropriately.
Parameters
string $class - The class name
string $overrides - Specify the class to replace/override
Definition at line 129 of file class-gf-addon.php.
References $class.
register_noconflict_scripts ($scripts)
Target for the gform_noconflict_scripts filter.
Adds scripts to the list of white-listed no conflict scripts.
Not intended to be overridden or called directed by Add-Ons.
Parameters
array $scripts Array of scripts to be white-listed
Returns
array
Definition at line 765 of file class-gf-addon.php.
register_noconflict_styles ($styles)
Target for the gform_noconflict_styles filter.
Adds styles to the list of white-listed no conflict scripts.
Not intended to be overridden or called directed by Add-Ons.
Parameters
array $styles Array of styles to be white-listed
Returns
array
Definition at line 781 of file class-gf-addon.php.
References $styles.
remove_field ($name, $settings) protected
Definition at line 2849 of file class-gf-addon.php.
render_settings ($sections) protected
Definition at line 905 of file class-gf-addon.php.
References add_default_save_button(), has_setting_field_type(), settings(), and wp_nonce_field().
Referenced by GFFeedAddOn\feed_edit_page().
render_uninstall ()
Override this function to customize the markup for the uninstall section on the plugin settings page.
Definition at line 3945 of file class-gf-addon.php.
replace_field ($name, $fields, $settings) protected
Definition at line 2863 of file class-gf-addon.php.
results_page_init ($results_page_config) protected
Initializes the result page functionality.
To activate result page functionality, override the get_results_page_config() function.
Parameters
$results_page_config - configuration returned by get_results_page_config()
Definition at line 832 of file class-gf-addon.php.
References add_filter().
Referenced by init_admin().
save_form_settings ($form, $settings)
Definition at line 3080 of file class-gf-addon.php.
scripts () protected
Override this function to provide a list of scripts to be enqueued.
When overriding this function, be sure to call parent::scripts() to ensure the base class scripts are enqueued. Following is an example of the array that is expected to be returned by this function:
    array(
        array(  "handle" => 'maskedinput',
                "src" => GFCommon::get_base_url() . '/js/jquery.maskedinput-1.3.min.js',
                "version" => GFCommon::$version,
                "deps" => array("jquery"),
                "in_footer" => false,
                //Determines where the script will be enqueued. The script will be enqueued if any of the conditions match
                "enqueue" => array(
                                    //admin_page - Specified one or more pages (known pages) where the script is supposed to be enqueued.
                                    //To enqueue scripts in the front end (public website), simply don't define this setting
                                    array("admin_page" => array("form_settings", 'plugin_settings') ),
                                    //tab - Specifies a form settings or plugin settings tab in which the script is supposed to be enqueued. If none is specified, the script will be enqueued in any of the form settings or plugin_settings page
                                    array("tab" => 'signature'),
                                    //query - Specifies a set of query string ($_GET) values. If all specified query string values match the current requested page, the script will be enqueued
                                    array("query" => 'page=gf_edit_forms&view=settings&id=_notempty_')
                                    //post - Specifies a set of post ($_POST) values. If all specified posted values match the current request, the script will be enqueued
                                    array("post" => 'posted_field=val')
                                    )
            ),
        array(
            "handle" => 'super_signature_script',
            "src" => $this->get_base_url() . '/super_signature/ss.js',
            "version" => $this->_version,
            "deps" => array("jquery"),
            "callback" => array($this, 'localize_scripts'),
            "strings" => array(
                               // Accessible in JavaScript using the global variable "[script handle]_strings"
                               "stringKey1" => __("The string", 'gravityforms'),
                               "stringKey2" => __("Another string.", 'gravityforms')
                               )
            "enqueue" => array(
                                //field_types - Specifies one or more field types that requires this script. The script will only be enqueued if the current form has a field of any of the specified field types. Only applies when a current form is available.
                                array("field_types" => array("signature"))
                                )
        )
  );
Definition at line 440 of file class-gf-addon.php.
References $min, and get_gfaddon_base_url().
Referenced by enqueue_scripts().
set_field_error ($field, $error_message = '') protected
Sets the validation error message Sets the error message to be displayed when a field fails validation.
When implementing a custom validation callback function, use this function to specify the error message to be displayed.
Parameters
array $field - The current field meta
string $error_message - The error message to be displayed
Definition at line 2712 of file class-gf-addon.php.
set_logging_supported ($plugins)
Definition at line 849 of file class-gf-addon.php.
References $_slug, $_title, and $plugins.
set_previous_settings ($settings) protected
Definition at line 1095 of file class-gf-addon.php.
Referenced by GFFeedAddOn\maybe_save_feed_settings().
set_settings ($settings) protected
Definition at line 1085 of file class-gf-addon.php.
Referenced by GFFeedAddOn\feed_edit_page().
setting_dependency_met ($dependency) protected
Definition at line 1210 of file class-gf-addon.php.
References get_setting().
Referenced by settings(), and single_section().
string array A string or an array of capabilities or roles that have access to the form settings ($sections) protected
Definition at line 927 of file class-gf-addon.php.
References setting_dependency_met(), and single_section().
Referenced by render_settings().
settings_checkbox ($field, $echo = true) protected
Definition at line 1446 of file class-gf-addon.php.
Referenced by GFPaymentAddOn\settings_setup_fee(), and GFPaymentAddOn\settings_trial().
settings_checkbox_and_select ($field, $echo = true)
Renders and initializes a checkbox field that displays a select field when checked based on the $field array.
public
Parameters
array $field - Field array containing the configuration options of this field
bool $echo = true - true to echo the output to the screen, false to simply return the contents as a string
Returns
string The HTML for the field
Definition at line 2256 of file class-gf-addon.php.
settings_dynamic_field_map ($field, $echo = true)
Definition at line 1970 of file class-gf-addon.php.
settings_field_map ($field, $echo = true)
Definition at line 1733 of file class-gf-addon.php.
settings_field_map_select ($field, $form_id)
Definition at line 1789 of file class-gf-addon.php.
settings_field_select ($field, $echo = true)
Renders and initializes a drop down field based on the $field array whose choices are populated by the form's fields.
Parameters
array $field - Field array containing the configuration options of this field
bool $echo = true - true to echo the output to the screen, false to simply return the contents as a string
Returns
string The HTML for the field
Definition at line 2101 of file class-gf-addon.php.
settings_fields_only ($settings_type = 'plugin') protected
Returns an flattened array of field settings for the specified settings type ignoring sections.
Parameters
string $settings_type The settings type. e.g. 'plugin'
Returns
array
Definition at line 3921 of file class-gf-addon.php.
settings_hidden ($field, $echo = true) protected
Definition at line 1413 of file class-gf-addon.php.
References $attributes, $field, $value, esc_attr(), get_field_attributes(), and get_setting().
settings_radio ($field, $echo = true) protected
Definition at line 1543 of file class-gf-addon.php.
settings_save ($field, $echo = true) protected
Definition at line 2335 of file class-gf-addon.php.
settings_select ($field, $echo = true) protected
Definition at line 1596 of file class-gf-addon.php.
Referenced by GFPaymentAddOn\settings_billing_cycle(), GFPaymentAddOn\settings_setup_fee(), and GFPaymentAddOn\settings_trial().
settings_select_custom ($field, $echo = true) protected
Renders and initializes a drop down field with a input field for custom input based on the $field array.
Parameters
array $field - Field array containing the configuration options of this field
bool $echo = true - true to echo the output to the screen, false to simply return the contents as a string
Returns
string The HTML for the field
Definition at line 1627 of file class-gf-addon.php.
settings_text ($field, $echo = true) protected
Definition at line 1305 of file class-gf-addon.php.
References $attributes, $field, $name, $value, elseif, esc_attr(), field_failed_validation(), get_error_icon(), get_field_attributes(), get_setting(), and gform_tooltip().
Referenced by GFPaymentAddOn\settings_trial().
settings_textarea ($field, $echo = true) protected
Definition at line 1361 of file class-gf-addon.php.
References $attributes, $field, $name, $value, esc_attr(), esc_html, field_failed_validation(), get_error_icon(), get_field_attributes(), get_setting(), gform_tooltip(), and wp_editor().
setup () protected
Performs upgrade tasks when the version of the Add-On changes.
To add additional upgrade tasks, override the upgrade() function, which will only get executed when the plugin version has changed.
Definition at line 332 of file class-gf-addon.php.
References get_option(), GFForms\get_wp_option(), update_option(), and upgrade().
Referenced by init_admin(), and init_frontend().
simple_condition ($setting_name_root) protected
Helper to create a simple conditional logic set of fields.
It creates one row of conditional logic with Field/Operator/Value inputs.
Parameters
mixed $setting_name_root - The root name to be used for inputs. It will be used as a prefix to the inputs that make up the conditional logic fields.
Returns
string The HTML
Definition at line 2366 of file class-gf-addon.php.
single_section ($section, $is_first = false) protected
Definition at line 944 of file class-gf-addon.php.
References $class, $description, $field, $title, endif, gform_tooltip(), setting_dependency_met(), single_setting_row(), and wp_parse_args().
Referenced by settings().
single_setting ($field) protected
Definition at line 1070 of file class-gf-addon.php.
References $field, elseif, esc_html, and esc_html__().
Referenced by single_setting_row(), and single_setting_row_save().
single_setting_label ($field) protected
Displays the label for a field, including the tooltip and requirement indicator.
Definition at line 1039 of file class-gf-addon.php.
References $field, get_required_indicator(), and gform_tooltip().
Referenced by single_setting_row().
single_setting_row ($field) protected
Definition at line 1018 of file class-gf-addon.php.
References $field, single_setting(), and single_setting_label().
Referenced by single_section().
single_setting_row_save ($field) protected
Definition at line 1053 of file class-gf-addon.php.
References $field, and single_setting().
styles () protected
Override this function to provide a list of styles to be enqueued.
When overriding this function, be sure to call parent::styles() to ensure the base class scripts are enqueued. See scripts() for an example of the format expected to be returned.
Definition at line 365 of file class-gf-addon.php.
References $min, and get_gfaddon_base_url().
Referenced by enqueue_print_styles(), and enqueue_scripts().
table_exists ($table_name)
Definition at line 4559 of file class-gf-addon.php.
References $count, and $wpdb.
Referenced by GFFeedAddOn\setup().
uninstall () protected
Called when the user chooses to uninstall the Add-On - after permissions have been checked and before removing all Add-On settings and Form settings.
Override this method to perform additional functions such as dropping database tables.
Return false to cancel the uninstall request.
Definition at line 4064 of file class-gf-addon.php.
uninstall_addon ()
Removes all settings and deactivates the Add-On.
Not intended to be overridden or called directly by Add-Ons.
Definition at line 3999 of file class-gf-addon.php.
uninstall_confirm_message () protected
Definition at line 3974 of file class-gf-addon.php.
uninstall_warning_message () protected
Definition at line 3970 of file class-gf-addon.php.
update_app_settings ($settings) protected
Updates app settings with the provided settings.
Parameters
array $settings - App settings to be saved
Definition at line 3868 of file class-gf-addon.php.
update_plugin_settings ($settings) protected
Updates plugin settings with the provided settings.
Parameters
array $settings - Plugin settings to be saved
Definition at line 3576 of file class-gf-addon.php.
bool Used by Rocketgenius plugins to activate auto upgrade ($previous_version) protected
Override this function to add to add database update scripts or any other code to be executed when the Add-On version changes.
Definition at line 353 of file class-gf-addon.php.
Referenced by setup().
validate_checkbox_settings ($field, $settings) protected
Definition at line 2635 of file class-gf-addon.php.
validate_field_map_settings ($field, $settings) protected
Definition at line 2678 of file class-gf-addon.php.
validate_select_custom_settings ($field, $settings) protected
Definition at line 2655 of file class-gf-addon.php.
array Stores a copy of setting fields that failed validation only populated after validate_settings ($fields, $settings) protected
Validates settings fields.
Validates that all fields are valid. Fields can be invalid when they are blank and marked as required or if it fails a custom validation check. To specify a custom validation, use the 'validation_callback' field meta property and implement the validation function with the custom logic.
Parameters
$fields - A list of all fields from the field meta configuration
$settings - A list of submitted settings values
Returns
bool - Returns true if all fields have passed validation, and false otherwise.
Definition at line 2577 of file class-gf-addon.php.
Referenced by GFFeedAddOn\maybe_save_feed_settings().
Field Documentation
$_capabilities = array() protected
Definition at line 51 of file class-gf-addon.php.
$_capabilities_app_menu = array() protected
Definition at line 81 of file class-gf-addon.php.
$_capabilities_app_settings = array() protected
Definition at line 85 of file class-gf-addon.php.
$_capabilities_form_settings = array() protected
Definition at line 73 of file class-gf-addon.php.
$_capabilities_plugin_page = array() protected
Definition at line 77 of file class-gf-addon.php.
$_capabilities_settings_page = array() protected
Definition at line 69 of file class-gf-addon.php.
$_capabilities_uninstall = array() protected
Definition at line 89 of file class-gf-addon.php.
$_enable_rg_autoupgrade = false protected
Definition at line 97 of file class-gf-addon.php.
$_full_path protected
Definition at line 35 of file class-gf-addon.php.
$_min_gravityforms_version protected
Definition at line 23 of file class-gf-addon.php.
$_no_conflict_scripts = array() private
Definition at line 101 of file class-gf-addon.php.
$_no_conflict_styles = array() private
Definition at line 102 of file class-gf-addon.php.
$_path protected
Definition at line 31 of file class-gf-addon.php.
$_preview_styles = array() private
Definition at line 103 of file class-gf-addon.php.
$_previous_settings = array() private
Definition at line 58 of file class-gf-addon.php.
Referenced by get_previous_settings().
$_print_styles = array() private
Definition at line 104 of file class-gf-addon.php.
$_registered_addons = array('active' => array(), 'inactive' => array()) static private
Definition at line 105 of file class-gf-addon.php.
$_saved_settings = array() private
Definition at line 57 of file class-gf-addon.php.
Referenced by get_current_settings().
$_setting_field_errors = array() private
Definition at line 63 of file class-gf-addon.php.
$_short_title protected
Definition at line 47 of file class-gf-addon.php.
$_slug protected
Definition at line 27 of file class-gf-addon.php.
Referenced by GFPaymentAddOn\is_payment_gateway(), GFFeedAddOn\maybe_process_feed(), set_logging_supported(), and GFPaymentAddOn\setup().
$_title protected
Definition at line 43 of file class-gf-addon.php.
Referenced by set_logging_supported().
$_url protected
Definition at line 39 of file class-gf-addon.php.
$_version protected
Definition at line 19 of file class-gf-addon.php.
$app_hook_suffix
Definition at line 55 of file class-gf-addon.php.
The documentation for this class was generated from the following file:
class-gf-addon.php