GravityView: _WP_Editors Class Reference
_WP_Editors Class Reference
Static Public Member Functions
static editor ($content, $editor_id, $settings=array())
Outputs the HTML for a single instance of the editor.
static editor_js ()
string $wp_version string $tinymce_version bool $concatenate_scripts bool $compress_scripts
static editor_settings ($editor_id, $set)
string $wp_version string $tinymce_version
static enqueue_scripts ()
static parse_settings ($editor_id, $settings)
Parse default arguments for the editor instance.
static wp_fullscreen_html ()
int $content_width
static wp_link_dialog ()
Dialog for internal linking.
static wp_link_query ($args=array())
Performs post queries for internal linking.
static wp_mce_translation ($mce_locale= '', $json_only=false)
Translates the default TinyMCE strings and returns them as JSON encoded object ready to be loaded with tinymce.addI18n().
Static Public Attributes
static $mce_locale
Private Member Functions
__construct ()
Static Private Member Functions
static _parse_init ($init)
Static Private Attributes
static $baseurl
static $drag_drop_upload = false
static $editor_buttons_css = true
static $ext_plugins
static $first_init
static $has_medialib = false
static $has_quicktags = false
static $has_tinymce = false
static $mce_settings = array()
static $old_dfw_compat = false
static $plugins = array()
static $qt_buttons = array()
static $qt_settings = array()
static $this_quicktags = false
static $this_tinymce = false
Detailed Description
Definition at line 11 of file class-wp-editor.php.
Constructor & Destructor Documentation
__construct () private
Definition at line 30 of file class-wp-editor.php.
Member Function Documentation
static _parse_init ($init) static private
Parameters
array $init
Returns
string
Definition at line 749 of file class-wp-editor.php.
References $options, and elseif.
static editor ($content, $editor_id, $settings = array()) static
Outputs the HTML for a single instance of the editor.
Parameters
string $content The initial content of the editor.
string $editor_id ID for the textarea and TinyMCE and Quicktags instances (can contain only ASCII letters and numbers).
array $settings See the _parse_settings() method for description.
Fires after the default media button(s) are displayed.
Since
2.5.0
Parameters
string $editor_id Unique editor identifier, e.g. 'content'.
Filter the HTML markup output that displays the editor.
Since
2.1.0
Parameters
string $output Editor's HTML markup.
Filter the default editor content.
Since
2.1.0
Parameters
string $content Default editor content.
string $default_editor The default editor for the current user. Either 'html' or 'tinymce'.
Definition at line 145 of file class-wp-editor.php.
References $content, $GLOBALS, __, _deprecated_function(), _x, ABSPATH, add_filter(), apply_filters(), current_user_can(), do_action(), elseif, esc_attr(), has_filter(), remove_filter(), wp_default_editor(), and wp_print_styles().
Referenced by wp_editor().
static editor_js () static
string $wp_version string $tinymce_version bool $concatenate_scripts bool $compress_scripts
Filter "tiny_mce_version" is deprecated
The tiny_mce_version filter is not needed since external plugins are loaded directly by TinyMCE. These plugins can be refreshed by appending query string to the URL passed to "mce_external_plugins" filter. If the plugin has a popup dialog, a query string can be added to the button action that opens it (in the plugin's code).
Fires immediately before the TinyMCE settings are printed.
Since
3.2.0
Parameters
array $mce_settings TinyMCE settings array.
Fires after tinymce.js is loaded, but before any TinyMCE editor instances are created.
Since
3.9.0
Parameters
array $mce_settings TinyMCE settings array.
Fires after any core TinyMCE editor instances are created.
Since
3.2.0
Parameters
array $mce_settings TinyMCE settings array.
Definition at line 1129 of file class-wp-editor.php.
References $_SERVER, $baseurl, $options, $plugins, $tinymce_version, $wp_version, admin_url(), do_action(), init(), is_admin(), and script_concat_settings().
static editor_settings ($editor_id, $set) static
string $wp_version string $tinymce_version
Parameters
string $editor_id
array $set
Filter the Quicktags settings.
Since
3.3.0
Parameters
array $qtInit Quicktags settings.
string $editor_id The unique editor ID, e.g. 'content'.
This filter is documented in wp-admin/includes/media.php
Filter the list of teenyMCE plugins.
Since
2.7.0
Parameters
array $plugins An array of teenyMCE plugins.
string $editor_id Unique editor identifier, e.g. 'content'.
Filter the list of TinyMCE external plugins.
The filter takes an associative array of external plugins for TinyMCE in the form 'plugin_name' => 'url'.
The url should be absolute, and should include the js filename to be loaded. For example: 'myplugin' => 'http://mysite.com/wp-content/plugins/myfolder/mce_plugin.js'.
If the external plugin adds a button, it should be added with one of the 'mce_buttons' filters.
Since
2.5.0
Parameters
array $external_plugins An array of external TinyMCE plugins.
Filter the list of default TinyMCE plugins.
The filter specifies which of the default plugins included in WordPress should be added to the TinyMCE instance.
Since
3.3.0
Parameters
array $plugins An array of default TinyMCE plugins.
Filter the translations loaded for external TinyMCE 3.x plugins.
The filter takes an associative array ('plugin_name' => 'path') where 'path' is the include path to the file.
The language file should follow the same format as wp_mce_translation(), and should define a variable ($strings) that holds all translated strings.
Since
2.5.0
Parameters
array $translations Translations for external TinyMCE plugins.
Filter the comma-delimited list of stylesheets to load in TinyMCE.
Since
2.1.0
Parameters
string $stylesheets Comma-delimited list of stylesheets.
Filter the list of teenyMCE buttons (Text tab).
Since
2.7.0
Parameters
array $buttons An array of teenyMCE buttons.
string $editor_id Unique editor identifier, e.g. 'content'.
Filter the first-row list of TinyMCE buttons (Visual tab).
Since
2.0.0
Parameters
array $buttons First-row list of buttons.
string $editor_id Unique editor identifier, e.g. 'content'.
Filter the second-row list of TinyMCE buttons (Visual tab).
Since
2.0.0
Parameters
array $buttons Second-row list of buttons.
string $editor_id Unique editor identifier, e.g. 'content'.
Filter the third-row list of TinyMCE buttons (Visual tab).
Since
2.0.0
Parameters
array $buttons Third-row list of buttons.
string $editor_id Unique editor identifier, e.g. 'content'.
Filter the fourth-row list of TinyMCE buttons (Visual tab).
Since
2.5.0
Parameters
array $buttons Fourth-row list of buttons.
string $editor_id Unique editor identifier, e.g. 'content'.
Filter the teenyMCE config before init.
Since
2.7.0
Parameters
array $mceInit An array with teenyMCE config.
string $editor_id Unique editor identifier, e.g. 'content'.
Filter the TinyMCE config before init.
Since
2.5.0
Parameters
array $mceInit An array with TinyMCE config.
string $editor_id Unique editor identifier, e.g. 'content'.
Definition at line 304 of file class-wp-editor.php.
References $body_class, $ext_plugins, $mce_locale, $name, $path, $plugins, $plugins, $post, $tinymce_version, $url, $wp_version, add_action(), apply_filters(), content_url(), current_theme_supports(), get_bloginfo(), get_editor_stylesheets(), get_locale(), get_post(), get_post_format(), includes_url(), is_admin(), is_wp_error(), post_type_supports(), sanitize_html_class(), set_url_scheme(), str_replace, trailingslashit(), WP_CONTENT_DIR, wp_is_mobile(), and wp_json_encode().
Referenced by wp_tiny_mce().
static enqueue_scripts () static
Fires when scripts and styles are enqueued for the editor.
Since
3.9.0
Parameters
array $to_load An array containing boolean values whether TinyMCE and Quicktags are being loaded.
Definition at line 771 of file class-wp-editor.php.
References $plugins, add_thickbox(), do_action(), wp_enqueue_script(), and wp_enqueue_style().
static parse_settings ($editor_id, $settings) static
Parse default arguments for the editor instance.
Parameters
string $editor_id ID for the current editor instance.
array $settings { Array of editor arguments.
bool $wpautop Whether to use wpautop(). Default true. bool $media_buttons Whether to show the Add Media/other media buttons. string $default_editor When both TinyMCE and Quicktags are used, set which editor is shown on page load. Default empty. bool $drag_drop_upload Whether to enable drag & drop on the editor uploading. Default false. Requires the media modal. string $textarea_name Give the textarea a unique name here. Square brackets can be used here. Default $editor_id. int $textarea_rows Number rows in the editor textarea. Default 20. string|int $tabindex Tabindex value to use. Default empty. string $tabfocus_elements The previous and next element ID to move the focus to when pressing the Tab key in TinyMCE. Default ':prev,:next'. string $editor_css Intended for extra styles for both Visual and Text editors. Should include <style> tags, and can use "scoped". Default empty. string $editor_class Extra classes to add to the editor textarea element. Default empty. bool $teeny Whether to output the minimal editor config. Examples include Press This and the Comment editor. Default false. bool $dfw Deprecated in 4.1. Since 4.3 used only to enqueue wp-fullscreen-stub.js for backwards compatibility. bool|array $tinymce Whether to load TinyMCE. Can be used to pass settings directly to TinyMCE using an array. Default true. bool|array $quicktags Whether to load Quicktags. Can be used to pass settings directly to Quicktags using an array. Default true. }
Returns
array Parsed arguments array.
Filter the wp_editor() settings.
Since
4.0.0
See also
_WP_Editors()::parse_settings()
Parameters
array $settings Array of editor arguments.
string $editor_id ID for the current editor instance.
Definition at line 65 of file class-wp-editor.php.
References _deprecated_argument(), apply_filters(), elseif, get_user_setting(), user_can_richedit(), and wp_parse_args().
Referenced by wp_tiny_mce().
static wp_fullscreen_html () static
int $content_width
Definition at line 1297 of file class-wp-editor.php.
References _deprecated_function().
static wp_link_dialog () static
Dialog for internal linking.
Since
3.1.0
Definition at line 1398 of file class-wp-editor.php.
References _e, get_user_setting(), input, label, name, and wp_nonce_field().
static wp_link_query ($args = array()) static
Performs post queries for internal linking.
Since
3.1.0
Parameters
array $args Optional. Accepts 'pagenum' and 's' (search) arguments.
Returns
false|array Results.
Filter the link query arguments.
Allows modification of the link query arguments before querying.
See also
WP_Query for a full list of arguments
Since
3.7.0
Parameters
array $query An array of WP_Query arguments.
Filter the link query results.
Allows modification of the returned link query results.
Since
3.7.0
See also
'wp_link_query_args' filter
Parameters
array $results { An associative array of query results.
array { int $ID Post ID. string $title The trimmed, escaped post title. string $permalink Post permalink. string $info A 'Y/m/d'-formatted date for 'post' post type, the 'singular_name' post type label otherwise. } }
Parameters
array $query An array of WP_Query arguments.
Definition at line 1310 of file class-wp-editor.php.
References $post, __, absint(), apply_filters(), esc_html, get_permalink(), get_post_types(), get_the_title(), mysql2date(), and WP_Query\query().
Referenced by wp_ajax_wp_link_ajax().
static wp_mce_translation ($mce_locale = '', $json_only = false) static
Translates the default TinyMCE strings and returns them as JSON encoded object ready to be loaded with tinymce.addI18n().
Can be used directly (_WP_Editors::wp_mce_translation()) by passing the same locale as set in the TinyMCE init object.
Parameters
string $mce_locale The locale used for the editor.
bool $json_only optional Whether to include the JavaScript calls to tinymce.addI18n() and tinymce.ScriptLoader.markDone().
Returns
string Translation object, JSON encoded.
Link plugin (not included): Insert link Target New window Text to display The URL you entered seems to be an email address. Do you want to add the required mailto: prefix? The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix? Url
Filter translated strings prepared for TinyMCE.
Since
3.9.0
Parameters
array $mce_translation Key/value pairs of strings.
string $mce_locale Locale.
Definition at line 816 of file class-wp-editor.php.
References $baseurl, $mce_locale, $value, __, _x, apply_filters(), includes_url(), is_rtl(), and wp_json_encode().
Field Documentation
$baseurl static private
Definition at line 19 of file class-wp-editor.php.
Referenced by editor_js(), and wp_mce_translation().
$drag_drop_upload = false static private
Definition at line 27 of file class-wp-editor.php.
$editor_buttons_css = true static private
Definition at line 26 of file class-wp-editor.php.
$ext_plugins static private
Definition at line 18 of file class-wp-editor.php.
Referenced by editor_settings().
$first_init static private
Definition at line 20 of file class-wp-editor.php.
$has_medialib = false static private
Definition at line 25 of file class-wp-editor.php.
$has_quicktags = false static private
Definition at line 24 of file class-wp-editor.php.
$has_tinymce = false static private
Definition at line 23 of file class-wp-editor.php.
$mce_locale static
Definition at line 12 of file class-wp-editor.php.
Referenced by editor_settings(), and wp_mce_translation().
$mce_settings = array() static private
Definition at line 14 of file class-wp-editor.php.
$old_dfw_compat = false static private
Definition at line 28 of file class-wp-editor.php.
$plugins = array() static private
Definition at line 16 of file class-wp-editor.php.
Referenced by editor_settings().
$qt_buttons = array() static private
Definition at line 17 of file class-wp-editor.php.
$qt_settings = array() static private
Definition at line 15 of file class-wp-editor.php.
$this_quicktags = false static private
Definition at line 22 of file class-wp-editor.php.
$this_tinymce = false static private
Definition at line 21 of file class-wp-editor.php.
The documentation for this class was generated from the following file:
class-wp-editor.php