GravityView: class-wp-customize-manager.php File Reference
class-wp-customize-manager.php File Reference
Data Structures
class WP_Customize_Manager
Customize Manager class.
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
maybe_hash_hex_color ($color)
Ensures that any hex color is properly hashed.
sanitize_hex_color ($color)
Sanitizes a hex color.
sanitize_hex_color_no_hash ($color)
Sanitizes a hex color without a hash.
Function Documentation
maybe_hash_hex_color ($color)
Ensures that any hex color is properly hashed.
Otherwise, returns value untouched.
This method should only be necessary if using sanitize_hex_color_no_hash().
Since
3.4.0
Parameters
string $color
Returns
string
Definition at line 2176 of file class-wp-customize-manager.php.
References sanitize_hex_color_no_hash().
sanitize_hex_color ($color)
Sanitizes a hex color.
Returns either '', a 3 or 6 digit hex color (with #), or nothing. For sanitizing values without a #, see sanitize_hex_color_no_hash().
Since
3.4.0
Parameters
string $color
Returns
string|void
Definition at line 2133 of file class-wp-customize-manager.php.
Referenced by sanitize_hex_color_no_hash().
sanitize_hex_color_no_hash ($color)
Sanitizes a hex color without a hash.
Use sanitize_hex_color() when possible.
Saving hex colors without a hash puts the burden of adding the hash on the UI, which makes it difficult to use or upgrade to other color types such as rgba, hsl, rgb, and html color names.
Returns either '', a 3 or 6 digit hex color (without a #), or null.
Since
3.4.0
Parameters
string $color
Returns
string|null
Definition at line 2156 of file class-wp-customize-manager.php.
References null, and sanitize_hex_color().
Referenced by WP_Customize_Manager\_sanitize_header_textcolor(), and maybe_hash_hex_color().