GravityView: SimplePie_File Class Reference
SimplePie_File Class Reference
Public Member Functions
__construct ($url, $timeout=10, $redirects=5, $headers=null, $useragent=null, $force_fsockopen=false)
Data Fields
$body
$error
$headers = array()
$method = SIMPLEPIE_FILE_SOURCE_NONE
$redirects = 0
$status_code
$success = true
$url
$useragent
Detailed Description
Definition at line 56 of file wp-includes/SimplePie/file.php.
Constructor & Destructor Documentation
__construct ($url, $timeout = 10, $redirects = 5, $headers = null, $useragent = null, $force_fsockopen = false)
Definition at line 68 of file wp-includes/SimplePie/file.php.
References $location, $out, $redirects, $url, $useragent, $value, SimplePie_Misc\absolutize_url(), SimplePie_Misc\compress_parse_url(), SimplePie_Misc\get_curl_version(), null, SimplePie_Misc\parse_url(), SIMPLEPIE_FILE_SOURCE_CURL, SIMPLEPIE_FILE_SOURCE_FILE_GET_CONTENTS, SIMPLEPIE_FILE_SOURCE_FSOCKOPEN, SIMPLEPIE_FILE_SOURCE_LOCAL, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Field Documentation
$body
Definition at line 62 of file wp-includes/SimplePie/file.php.
$error
Definition at line 65 of file wp-includes/SimplePie/file.php.
$headers = array()
Definition at line 61 of file wp-includes/SimplePie/file.php.
Referenced by WP_SimplePie_File\__construct().
$method = SIMPLEPIE_FILE_SOURCE_NONE
Definition at line 66 of file wp-includes/SimplePie/file.php.
$redirects = 0
Definition at line 64 of file wp-includes/SimplePie/file.php.
Referenced by __construct(), and WP_SimplePie_File\__construct().
$status_code
Definition at line 63 of file wp-includes/SimplePie/file.php.
$success = true
Definition at line 60 of file wp-includes/SimplePie/file.php.
$url
Definition at line 58 of file wp-includes/SimplePie/file.php.
Referenced by __construct(), and WP_SimplePie_File\__construct().
$useragent
Definition at line 59 of file wp-includes/SimplePie/file.php.
Referenced by __construct(), and WP_SimplePie_File\__construct().
The documentation for this class was generated from the following file:
wp-includes/SimplePie/file.php