GravityView: WP_Theme_Install_List_Table Class Reference
WP_Theme_Install_List_Table Class Reference
Core class used to implement displaying themes to install in a list table.
Public Member Functions
_js_vars ($extra_args=array())
Send required variables to JavaScript land.
ajax_user_can ()
display ()
public
display_rows ()
public
install_theme_info ($theme)
Prints the info for a theme (to be used in the theme installer modal).
no_items ()
public
prepare_items ()
array $tabs string $tab int $paged string $type array $theme_field_defaults
single_row ($theme)
Prints a theme from the WordPress.org API.
theme_installer ()
Prints the wrapper for the theme installer.
theme_installer_single ($theme)
Prints the wrapper for the theme installer with a provided theme's data.
Public Member Functions inherited from WP_Themes_List_Table
__construct ($args=array())
Constructor.
_js_vars ($extra_args=array())
Send required variables to JavaScript land.
ajax_user_can ()
display ()
public
display_rows ()
public
display_rows_or_placeholder ()
public
get_columns ()
no_items ()
public
prepare_items ()
public
search_theme ($theme)
tablenav ($which= 'top')
Public Member Functions inherited from WP_List_Table
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($args=array())
Constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
_js_vars ()
Send required variables to JavaScript land.
ajax_response ()
Handle an incoming ajax request (called from admin-ajax.php)
ajax_user_can ()
Checks the current user's permissions.
current_action ()
Get the current action selected from the bulk actions dropdown.
display ()
Display the table.
display_rows ()
Generate the table rows.
display_rows_or_placeholder ()
Generate the tbody element for the list table.
get_column_count ()
Return number of visible columns.
get_columns ()
Get a list of columns.
get_pagenum ()
Get the current page number.
get_pagination_arg ($key)
Access the pagination args.
get_primary_column ()
Public wrapper for WP_List_Table::get_default_primary_column_name().
has_items ()
Whether the table has items to display or not.
no_items ()
Message to be displayed when there are no items.
prepare_items ()
Prepares the list of items for displaying.
print_column_headers ($with_id=true)
Print column headers, accounting for hidden and sortable columns.
search_box ($text, $input_id)
Display the search box.
single_row ($item)
Generates content for a single row of the table.
views ()
Display the list of views available on this table.
Data Fields
$features = array()
Data Fields inherited from WP_Themes_List_Table
$features = array()
Data Fields inherited from WP_List_Table
$items
Protected Member Functions
get_views ()
array $tabs string $tab
Protected Member Functions inherited from WP_List_Table
bulk_actions ($which= '')
Display the bulk actions dropdown.
column_cb ($item)
column_default ($item, $column_name)
comments_bubble ($post_id, $pending_comments)
Display a comment count bubble.
display_tablenav ($which)
Generate the table navigation above or below the table.
extra_tablenav ($which)
Extra controls to be displayed between bulk actions and pagination.
get_bulk_actions ()
Get an associative array (option_name => option_title) with the list of bulk actions available on this table.
get_column_info ()
Get a list of all, hidden and sortable columns, with filter applied.
get_default_primary_column_name ()
Gets the name of the default primary column.
get_items_per_page ($option, $default=20)
Get number of items to display on a single page.
get_primary_column_name ()
Gets the name of the primary column.
get_sortable_columns ()
Get a list of sortable columns.
get_table_classes ()
Get a list of CSS classes for the WP_List_Table table tag.
get_views ()
Get an associative array (id => link) with the list of views available on this table.
handle_row_actions ($item, $column_name, $primary)
Generates and display row actions links for the list table.
months_dropdown ($post_type)
Display a monthly dropdown for filtering items.
pagination ($which)
Display the pagination.
row_actions ($actions, $always_visible=false)
Generate row actions div.
set_pagination_args ($args)
An internal method that sets all the necessary pagination arguments.
single_row_columns ($item)
Generates the columns for a single row of the table.
view_switcher ($current_mode)
Display a view switcher.
Private Member Functions
_get_theme_status ($theme)
Check to see if the theme is already installed.
Additional Inherited Members
Protected Attributes inherited from WP_Themes_List_Table
$search_terms = array()
Protected Attributes inherited from WP_List_Table
$_args
$_column_headers
$_pagination_args = array()
$compat_fields = array('_args', '_pagination_args', 'screen', '_actions', '_pagination')
{
$compat_methods
{
$modes = array()
$screen
Detailed Description
Core class used to implement displaying themes to install in a list table.
Since
3.1.0 private
See also
WP_Thenes_List_Table
Definition at line 18 of file class-wp-theme-install-list-table.php.
Member Function Documentation
_get_theme_status ($theme) private
Check to see if the theme is already installed.
Since
3.4.0 private
Parameters
object $theme - A WordPress.org Theme API object.
Returns
string Theme status.
Definition at line 457 of file class-wp-theme-install-list-table.php.
References $theme, elseif, and wp_get_theme().
Referenced by install_theme_info(), and single_row().
_js_vars ($extra_args = array())
Send required variables to JavaScript land.
Since
3.4.0 public
string $tab Current tab within Themes->Install screen string $type Type of search.
Parameters
array $extra_args Unused.
Definition at line 443 of file class-wp-theme-install-list-table.php.
ajax_user_can ()
Returns
bool
Definition at line 26 of file class-wp-theme-install-list-table.php.
References current_user_can().
display ()
public
Fires in the Install Themes list table header.
Since
2.8.0
Definition at line 185 of file class-wp-theme-install-list-table.php.
References WP_Themes_List_Table\display_rows_or_placeholder(), do_action(), WP_List_Table\pagination(), WP_Themes_List_Table\tablenav(), and wp_nonce_field().
display_rows ()
public
Definition at line 214 of file class-wp-theme-install-list-table.php.
References WP_List_Table\$items, $theme, single_row(), and theme_installer().
get_views () protected
array $tabs string $tab
Returns
array
Definition at line 169 of file class-wp-theme-install-list-table.php.
References $action, $class, $href, $tabs, $text, and self_admin_url().
install_theme_info ($theme)
Prints the info for a theme (to be used in the theme installer modal).
array $themes_allowedtags
Parameters
object $theme - A WordPress.org Theme API object.
Definition at line 376 of file class-wp-theme-install-list-table.php.
References $name, $theme, $themes_allowedtags, __, _e, _get_theme_status(), _x, add_query_arg(), endif, esc_attr(), esc_attr__(), esc_url, input, self_admin_url(), wp_kses(), wp_nonce_url(), and wp_star_rating().
Referenced by single_row(), and theme_installer_single().
no_items ()
public
Definition at line 159 of file class-wp-theme-install-list-table.php.
References _e.
prepare_items ()
array $tabs string $tab int $paged string $type array $theme_field_defaults
This filter is documented in wp-admin/theme-install.php
Filter tabs not associated with a menu item on the Install Themes screen.
Since
2.8.0
Parameters
array $nonmenu_tabs The tabs that don't have a menu item on the Install Themes screen.
Filter API request arguments for each Install Themes screen tab.
The dynamic portion of the hook name, $tab, refers to the theme install tabs. Default tabs are 'dashboard', 'search', 'upload', 'featured', 'new', and 'updated'.
Since
3.7.0
Parameters
array $args An array of themes API arguments.
Definition at line 38 of file class-wp-theme-install-list-table.php.
References $features, $paged, WP_Themes_List_Table\$search_terms, $tabs, $theme_field_defaults, __, _x, ABSPATH, add_action(), apply_filters(), WP_List_Table\get_pagenum(), is_wp_error(), WP_List_Table\set_pagination_args(), themes_api(), wp_die(), wp_reset_vars(), and wp_unslash().
single_row ($theme)
Prints a theme from the WordPress.org API.
array $themes_allowedtags
Parameters
object $theme An object that contains theme data returned by the WordPress.org API.
Example theme data: object(stdClass)[59] public 'name' => string 'Magazine Basic' public 'slug' => string 'magazine-basic' public 'version' => string '1.1' public 'author' => string 'tinkerpriest' public 'preview_url' => string 'http://wp-themes.com/?magazine-basic' public 'screenshot_url' => string 'http://wp-themes.com/wp-content/themes/magazine-basic/screenshot.png' public 'rating' => float 80 public 'num_ratings' => int 1 public 'homepage' => string 'http://wordpress.org/themes/magazine-basic' public 'description' => string 'A basic magazine style layout with a fully customizable layout through a backend interface. Designed by c.bavota of Tinker Priest Media.' public 'download_link' => string 'http://wordpress.org/themes/download/magazine-basic.1.1.zip'
Filter the install action links for a theme in the Install Themes list table.
Since
3.4.0
Parameters
array $actions An array of theme action hyperlinks. Defaults are links to Install Now, Preview, and Details.
WP_Theme $theme Theme object.
Definition at line 247 of file class-wp-theme-install-list-table.php.
References $action, $name, $preview_url, $theme, $themes_allowedtags, __, _e, _get_theme_status(), _x, add_query_arg(), apply_filters(), endforeach, esc_attr(), esc_attr__(), esc_url, install_theme_info(), li, self_admin_url(), width, wp_kses(), and wp_nonce_url().
Referenced by display_rows().
theme_installer ()
Prints the wrapper for the theme installer.
Definition at line 327 of file class-wp-theme-install-list-table.php.
References _e, and label.
Referenced by display_rows().
theme_installer_single ($theme)
Prints the wrapper for the theme installer with a provided theme's data.
Used to make the theme installer work for no-js.
Parameters
object $theme - A WordPress.org Theme API object.
Definition at line 356 of file class-wp-theme-install-list-table.php.
References $theme, and install_theme_info().
Field Documentation
$features = array()
Definition at line 20 of file class-wp-theme-install-list-table.php.
Referenced by prepare_items().
The documentation for this class was generated from the following file:
class-wp-theme-install-list-table.php