GravityView: GravityView_Admin_Installer Class Reference
GravityView_Admin_Installer Class Reference
GravityView_Admin_Installer Class.
Public Member Functions
__construct ()
activate_download ()
Handle AJAX request to activate extension.
add_admin_menu ()
Add new admin menu.
add_downloads_data_filters ()
Modify plugins data with custom GV extension info.
deactivate_download ()
Handle AJAX request to deactivate extension.
delete_downloads_data ()
Delete downloads data transient.
get_downloads_data ()
Get downloads data from transient or from API; save transient after getting data from API.
maybe_enqueue_scripts_and_styles ()
Register and enqueue assets; localize script.
maybe_modify_license_notice ($notice='')
When on the Installer page, show a different notice than on the Settings page.
register_noconflict ($items)
Let us operate when GF no-conflict is enabled.
render_screen ()
Display a grid of available downloads and controls to install/activate/deactivate them.
set_downloads_data ($data)
Save downloads data in a time-bound transient.
Static Public Member Functions
static get_wp_plugins_data ($textdomain=null)
Get an array of plugins with textdomains as keys.
Data Fields
$minimum_capability = 'install_plugins'
const DOWNLOADS_DATA_TRANSIENT = 'gv_downloads_data'
const DOWNLOADS_DATA_TRANSIENT_EXPIRY = DAY_IN_SECONDS
const EDD_API_KEY = 'e4c7321c4dcf342c9cb078e27bf4ba97'
const EDD_API_TOKEN = 'e031fd350b03bc223b10f04d8b5dde42'
const EDD_API_URL = 'https://gravityview.co/edd-api/products/'
Protected Member Functions
render_download ($download, $wp_plugins)
Outputs the HTML of a single download.
Private Member Functions
get_download_base_price ($download)
Returns the base price for an extension.
get_download_display_details ($download, $wp_plugins)
Generates details array for the download to keep the render_download() method a bit tidier.
render_section ($section_slug, $heading, $downloads_data, $wp_plugins=array())
Renders each category of download (Add-Ons, Extensions, Layouts)
Detailed Description
GravityView_Admin_Installer Class.
A general class for About page.
Since
2.1
Definition at line 16 of file class-admin-installer.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 33 of file class-admin-installer.php.
References add_downloads_data_filters().
Member Function Documentation
activate_download()
activate_download ()
Handle AJAX request to activate extension.
Returns
void Exits with JSON response
Definition at line 585 of file class-admin-installer.php.
References Utils\_POST().
add_admin_menu()
add_admin_menu ()
Add new admin menu.
Returns
void
Definition at line 98 of file class-admin-installer.php.
add_downloads_data_filters()
add_downloads_data_filters ()
Modify plugins data with custom GV extension info.
Returns
void
Definition at line 67 of file class-admin-installer.php.
References $args.
Referenced by __construct().
deactivate_download()
deactivate_download ()
Handle AJAX request to deactivate extension.
Returns
void Send JSON response status and error message
Definition at line 608 of file class-admin-installer.php.
References Utils\_POST().
delete_downloads_data()
delete_downloads_data ()
Delete downloads data transient.
Returns
bool true if successful, false otherwise
Definition at line 269 of file class-admin-installer.php.
get_download_base_price()
get_download_base_price ($download) private
Returns the base price for an extension.
Parameters
array $download
Returns
float Base price for an extension. If not for sale separately, returns 0
Definition at line 565 of file class-admin-installer.php.
References Utils\get().
Referenced by get_download_display_details().
get_download_display_details()
get_download_display_details ($download, $wp_plugins) private
Generates details array for the download to keep the render_download() method a bit tidier.
Since
2.10 Allow managing installed add-ons whether or not the user's license shows they have access.
Parameters
array $download Single download, as returned by {
See also
get_downloads_data}
Parameters
array $wp_plugins All active plugins, as returned by {
See also
get_plugins()}
Returns
array {
Parameters
array $download_info
string $plugin_path
string $status License status returned by Easy Digital Downloads ("active", "inactive", "expired", "revoked", etc)
string $status_label
string $button_title Title attribute to show when hovering over the download's button
string $button_class CSS class to use for the button
string $button_label Text to use for the download's anchor link
string $href URL for the download's button
bool $spinner Whether to show the spinner icon
string $item_class CSS class for the download container
string $required_license The name of the required license for the download ("All Access" or "Core + Extensions")
bool $is_active Is the current GravityView license (as entered in Settings) active? }
Definition at line 450 of file class-admin-installer.php.
References $href, Utils\get(), GV\get(), get_download_base_price(), and gravityview().
Referenced by render_download().
get_downloads_data()
get_downloads_data ()
Get downloads data from transient or from API; save transient after getting data from API.
Returns
WP_Error|array If error, returns WP_Error. If not valid JSON, empty array. Otherwise, this structure: {
Parameters
array $info {
string $id int 17
string $slug Extension slug
string $title Extension title
string $create_date in '2018-07-19 20:03:10' format
string $modified_date
string $status
string $link URL to public plugin page
string $content
string $excerpt
string $thumbnail URL to thumbnail
array $category Taxonomy details for the plugin's category {
int $term_id => int 30
string $name => string 'Plugins' (length=7)
string $slug => string 'plugins' (length=7)
int $term_group => int 0
int $term_taxonomy_id => int 30
string $taxonomy => string 'download_category' (length=17)
string $description => string '' (length=0)
int $parent => int 0
int $count => int 4
string $filter => string 'raw' (length=3) }
array $tags {see $category above}
string $textdomain string 'gravityview' (length=11) }
array $pricing array of price_name_slugs => '00.00' values, if price options exist
array $licensing {
bool $enabled Is licensing enabled for the extension
string $version Version number
string $exp_unit Expiration unit ('years')
string $exp_length Expiration length ('1') }
array $files Array of files. Empty if user has no access to the file. {
string $file string URL of the file download } }
Definition at line 208 of file class-admin-installer.php.
References gravityview(), and set_downloads_data().
Referenced by render_screen().
get_wp_plugins_data()
static get_wp_plugins_data ($textdomain = null) static
Get an array of plugins with textdomains as keys.
Since
2.1
2.10 Added $textdomain argument. Converted to static method. Made method public (from protected).
Parameters
string $textdomain If set, only return plugins that have a matching textdomain.
Returns
array {
Parameters
string $path Path to the plugin.
string $version What version is the plugin.
bool $activated Is the plugin activated. }
Definition at line 144 of file class-admin-installer.php.
References Utils\get().
maybe_enqueue_scripts_and_styles()
maybe_enqueue_scripts_and_styles ()
Register and enqueue assets; localize script.
Returns
void
Definition at line 631 of file class-admin-installer.php.
References gravityview(), and GRAVITYVIEW_URL.
maybe_modify_license_notice()
maybe_modify_license_notice ($notice = '')
When on the Installer page, show a different notice than on the Settings page.
Parameters
array $notice
Returns
string License notice
Definition at line 121 of file class-admin-installer.php.
References gravityview().
register_noconflict()
register_noconflict ($items)
Let us operate when GF no-conflict is enabled.
Parameters
array $items Scripts or styles to exclude from no-conflict
Returns
array
Definition at line 54 of file class-admin-installer.php.
render_download()
render_download ($download, $wp_plugins) protected
Outputs the HTML of a single download.
Parameters
array $download Download data, as returned from EDD API
array $wp_plugins
Returns
void
Definition at line 382 of file class-admin-installer.php.
References Utils\get(), GV\get(), and get_download_display_details().
Referenced by render_section().
render_screen()
render_screen ()
Display a grid of available downloads and controls to install/activate/deactivate them.
Since
2.1
Returns
void
Definition at line 280 of file class-admin-installer.php.
References get_downloads_data(), and render_section().
render_section()
render_section ($section_slug, $heading, $downloads_data, $wp_plugins = array()) private
Renders each category of download (Add-Ons, Extensions, Layouts)
Since
2.10
Parameters
string $section_slug The slug to display downloads from (based on the category slug on gravityview.co)
string $heading The section heading text ("GravityView Layouts", "GravityView Extensions", "Gravity Forms Add-Ons")
array $downloads_data Downloads data from gravityview.co EDD API {
See also
get_downloads_data}
Parameters
array $wp_plugins All active plugins, as returned by {
See also
()}
Definition at line 348 of file class-admin-installer.php.
References $output, GV\get(), and render_download().
Referenced by render_screen().
set_downloads_data()
set_downloads_data ($data)
Save downloads data in a time-bound transient.
Parameters
array $data
Returns
true if successful, false otherwise
Definition at line 260 of file class-admin-installer.php.
Referenced by get_downloads_data().
Field Documentation
$minimum_capability
$minimum_capability = 'install_plugins'
Definition at line 31 of file class-admin-installer.php.
DOWNLOADS_DATA_TRANSIENT
const DOWNLOADS_DATA_TRANSIENT = 'gv_downloads_data'
Definition at line 24 of file class-admin-installer.php.
DOWNLOADS_DATA_TRANSIENT_EXPIRY
const DOWNLOADS_DATA_TRANSIENT_EXPIRY = DAY_IN_SECONDS
Definition at line 26 of file class-admin-installer.php.
EDD_API_KEY
const EDD_API_KEY = 'e4c7321c4dcf342c9cb078e27bf4ba97'
Definition at line 20 of file class-admin-installer.php.
EDD_API_TOKEN
const EDD_API_TOKEN = 'e031fd350b03bc223b10f04d8b5dde42'
Definition at line 22 of file class-admin-installer.php.
EDD_API_URL
const EDD_API_URL = 'https://gravityview.co/edd-api/products/'
Definition at line 18 of file class-admin-installer.php.
The documentation for this class was generated from the following file:
class-admin-installer.php