GravityView: View_Settings Class Reference
View_Settings Class Reference
If this file is called directly, abort.
Public Member Functions
as_atts ()
Turn to an $atts array as used around the old codebase.
Public Member Functions inherited from Settings
__construct ($settings=array())
Create with new.
all ()
Returns all the objects in this collection as an an array.
get ($key, $default=null)
Set an setting.
set ($key, $value)
Set a setting.
update ($settings)
Mass update values from the allowed ones.
Static Public Member Functions
static defaults ($detailed=false, $group=null)
Retrieve the default View settings.
static with_defaults ($detailed=false)
Retrieve an instance of the settings with default values.
Detailed Description
If this file is called directly, abort.
The View Settings class.
Definition at line 12 of file class-gv-settings-view.php.
Member Function Documentation
as_atts()
as_atts ()
Turn to an $atts array as used around the old codebase.
Definition at line 559 of file class-gv-settings-view.php.
References GV\defaults().
defaults()
static defaults ($detailed = false, $group = null) static
Retrieve the default View settings.
Parameters
bool $detailed Whether to return detailed setting meta information or just the value.
string $group Retrieve settings of a particular group.
Since
2.0
Returns
array The default settings along with their values.
Parameters
[out] string $label Setting label shown in admin
[out] string $type Gravity Forms field type
[out] string $group The field group the setting is associated with. Default: "default"
[out] mixed $value The default value for the setting
[out] string $tooltip Tooltip displayed for the setting
[out] boolean $show_in_shortcode Whether to show the setting in the shortcode configuration modal
[out] array $options Array of values to use when generating select, multiselect, radio, or checkboxes fields
[out] boolean $full_width True: Display the input and label together when rendering. False: Display label and input in separate columns when rendering.
Runs Filter:
gravityview_default_args Modify the default settings for new Views
Parameters
[in,out] array $default_args Array of default args.
See also
filter gravityview/view/settings/defaults
Runs Filter:
gravityview/view/defaults Modify the default settings for new Views
Parameters
[in,out] array $default_settings Array of default settings.
Definition at line 47 of file class-gv-settings-view.php.
References $value, and gravityview().
Referenced by GravityView_Admin_Add_Shortcode\add_shortcode_popup(), GravityView_View_Data\get_default_arg(), GravityView_Shortcode\parse_and_sanitize_atts(), gravityview\parse_and_sanitize_atts(), and GravityView_Admin_Views\tooltips().
with_defaults()
static with_defaults ($detailed = false) static
Retrieve an instance of the settings with default values.
Parameters
bool $detailed Whether to return detailed setting meta information or just the value.
Since
2.0
Returns
Definition at line 22 of file class-gv-settings-view.php.
References $settings, and GV\defaults().
Referenced by GravityView_View_Data\get_id_from_atts(), and GravityView_Render_Settings\render_setting_row().
The documentation for this class was generated from the following file:
class-gv-settings-view.php