GravityView: GFEntryList Class Reference
GFEntryList Class Reference
Static Public Member Functions
static all_leads_page ()
static get_filter_links ($form, $include_counts=true)
static get_icon_url ($path)
static leads_page ($form_id)
Static Private Member Functions
static display_paging_links ($which, $page_links, $first_item_index, $page_size, $total_lead_count)
Detailed Description
Definition at line 7 of file entry_list.php.
Member Function Documentation
static all_leads_page () static
Fires before the entry list content is generated.
Echoed content would appear above the page title.
int $form_id The ID of the form the entry list is being displayed for.
Fires after the entry list content is generated.
Echoed content would appear after the bulk actions/paging links below the entry list table.
int $form_id The ID of the form the entry list is being displayed for.
Definition at line 8 of file entry_list.php.
References $form_id, $forms, do_action(), esc_html__(), GFForms\get(), GFFormsModel\get_forms(), and null.
Referenced by GFForms\all_leads_page().
static display_paging_links ($which, $page_links, $first_item_index, $page_size, $total_lead_count) static private
Definition at line 1459 of file entry_list.php.
References esc_html__().
static get_filter_links ($form, $include_counts = true) static
—Provisional and may be subject to change—
Allow the row of filter links to be modified.
Array elements: selected - bool filter - string label - string
Parameters
array $filter_links The filter links.
Definition at line 1484 of file entry_list.php.
References $form, $form_id, absint(), apply_filters(), esc_html__(), esc_html_x(), and GFFormsModel\get_form_counts().
Referenced by GFEntryDetail\lead_detail_page(), and GFForms\update_lead_status().
static get_icon_url ($path) static
Definition at line 1354 of file entry_list.php.
References $path.
Referenced by GF_Field_Post_Image\get_value_entry_list(), and GF_Field_FileUpload\get_value_entry_list().
static leads_page ($form_id) static
Allow the entry list search criteria to be overridden.
Since
1.9.14.30
Parameters
array $search_criteria An array containing the search criteria.
int $form_id The ID of the current form.
Allows for the modification of the Entry apply button HTML (When modifying entries)
Parameters
string $apply_button The Entry apply button HTML
Allows for the modification of the Entry apply button HTML (When modifying entries)
Parameters
string $apply_button The Entry apply button HTML
Definition at line 50 of file entry_list.php.
References $action, $columns, $dir, $field, $field_id, $form, $form_id, $leads, $message, $min, $wpdb, __, a, absint(), admin_url(), align, apply_filters(), checked(), column, GFFormsModel\delete_lead(), GFFormsModel\delete_leads(), GFFormsModel\delete_leads_by_form(), esc_attr(), esc_attr__(), esc_attr_e(), esc_html, esc_html__(), esc_html_e, GFAPI\get_entries(), GFFormsModel\get_field(), GFFormsModel\get_form_meta(), GFFormsModel\get_grid_columns(), GFFormsModel\get_input_type(), gform_tooltip(), input, label, li, name, null, page, paginate_links(), GFForms\post(), GFFormsModel\search_lead_ids(), space, spam, GFForms\top_toolbar(), GFFormsModel\update_grid_column_meta(), GFFormsModel\update_leads_property(), UpdateCount(), width, wp_nonce_field(), wp_nonce_url(), and wp_print_styles().
Referenced by GFForms\forms().
The documentation for this class was generated from the following file:
entry_list.php