GravityView: GFAPI Class Reference
GFAPI Class Reference
Static Public Member Functions
static add_entries ($entries, $form_id=null)
Adds multiple Entry objects.
static add_entry ($entry)
Adds a single Entry object.
static add_feed ($form_id, $feed_meta, $addon_slug)
Adds a feed with the given Feed object.
static add_form ($form_meta)
Adds a new form using the given Form object.
static add_forms ($forms)
Adds multiple form objects.
static count_entries ($form_ids, $search_criteria=array())
Returns the total number of entries for the given search criteria.
static current_user_can_any ($capabilities)
Checks the permissions for the current user.
static delete_entry ($entry_id)
Deletes a single Entry.
static delete_feed ($feed_id)
Deletes a single Feed.
static delete_form ($form_id)
Deletes the form with the given Form ID.
static delete_forms ($form_ids)
Deletes the forms with the given Form IDs.
static form_id_exists ($form_id)
Private.
static get_entries ($form_ids, $search_criteria=array(), $sorting=null, $paging=null, &$total_count=null)
Returns an array of Entry objects for the given search criteria.
static get_entry ($entry_id)
Returns the Entry object for a given Entry ID.
static get_feeds ($feed_ids=null, $form_id=null, $addon_slug=null, $is_active=true)
Returns all the feeds for the given criteria.
static get_fields_by_type ($form, $types, $use_input_type=false)
Returns an array containing the form fields of the specified type or types.
static get_form ($form_id)
Returns the form object for a given Form ID.
static get_forms ($active=true, $trash=false)
Returns all the form objects.
static send_notifications ($form, $entry, $event= 'form_submission')
Sends all active notifications for a form given an entry object and an event.
static submit_form ($form_id, $input_values, $field_values=array(), $target_page=0, $source_page=1)
Submits a form.
static update_entries ($entries)
Updates multiple Entry objects.
static update_entry ($entry, $entry_id=null)
Updates a single Entry object.
static update_entry_field ($entry_id, $input_id, $value)
Updates a single field of an entry.
static update_entry_property ($entry_id, $property, $value)
Updates a single property of an entry.
static update_feed ($feed_id, $feed_meta, $form_id=null)
static update_form ($form, $form_id=null)
Updates the form with a given form object.
static update_form_property ($form_id, $property_key, $value)
Updates the property of one form - columns in the main forms table.
static update_forms ($forms)
Updates the forms with an array of form objects.
static update_forms_property ($form_ids, $property_key, $value)
Updates a form property - a column in the main forms table.
Static Private Member Functions
static set_property_as_key ($array, $property)
Private.
Detailed Description
Definition at line 19 of file api.php.
Member Function Documentation
static add_entries ($entries, $form_id = null) static
Adds multiple Entry objects.
Since
1.8 public
Parameters
array $entries The Entry objects
int $form_id Optional. If specified, the form_id in the Entry objects will be ignored
Returns
mixed Either an array of new Entry IDs or a WP_Error instance
Definition at line 519 of file api.php.
References $entries, $form_id, and is_wp_error().
static add_entry ($entry) static
Adds a single Entry object.
Intended to be used for importing an entry object. The usual hooks that are triggered while saving entries are not fired here. Checks that the form id, field ids and entry meta exist and ignores legacy values (i.e. values for fields that no longer exist).
Since
1.8 public
Parameters
array $entry The Entry object
Returns
mixed Either the new Entry ID or a WP_Error instance
Fires after the Entry is added using the API.
Since
1.9.14.26
Parameters
array $entry
array $form
Definition at line 770 of file api.php.
References $current_user, $field, $field_id, $form, $form_id, $post_id, $user_id, $wpdb, __, absint(), do_action(), esc_sql(), esc_url_raw(), GFFormsModel\get_current_page_url(), get_entry(), GFFormsModel\get_entry_meta(), GFFormsModel\get_form_meta(), GFFormsModel\get_ip(), GFFormsModel\get_lead_table_name(), gform_update_meta(), and GFFormsModel\update_lead_field_value().
Referenced by GF_UnitTest_Factory_For_Entry\create_object(), and GV_Unit_Tests_Bootstrap\create_stubs().
static add_feed ($form_id, $feed_meta, $addon_slug) static
Adds a feed with the given Feed object.
Since
1.8 public
Parameters
int $form_id The ID of the Form to which the Feed belongs
array $feed_meta The Feed object
string $addon_slug The slug of the add-on to which the Feeds belong
Returns
mixed Either the ID of the newly created Feed or a WP_Error instance
Definition at line 1204 of file api.php.
References $form_id, $wpdb, and __.
static add_form ($form_meta) static
Adds a new form using the given Form object.
Warning, little checking is done to make sure it's a valid Form object.
Since
1.8 public
Parameters
array $form_meta The Form object
Returns
mixed Either the new Form ID or a WP_Error instance
Definition at line 317 of file api.php.
References $count, $form_id, $title, $wpdb, __, GFFormsModel\insert_form(), GFFormsModel\is_unique_title(), and GFFormsModel\update_form_meta().
Referenced by GF_UnitTest_Factory_For_Form\create_object(), and GV_Unit_Tests_Bootstrap\create_stubs().
static add_forms ($forms) static
Adds multiple form objects.
Since
1.8 public
Parameters
array $forms The Form objects
Returns
mixed Either an array of new form IDs or a WP_Error instance
Definition at line 289 of file api.php.
References $form, $forms, __, and is_wp_error().
Referenced by GFExport\import_json().
static count_entries ($form_ids, $search_criteria = array()) static
Returns the total number of entries for the given search criteria.
See get_entries() for examples of the search criteria.
Since
1.8 public
Parameters
int | array $form_ids The ID of the Form or an array of Form IDs
array $search_criteria Optional. An array containing the search criteria
Returns
int The total count
Definition at line 478 of file api.php.
References GFFormsModel\count_search_leads().
Referenced by GVCommon\get_entries(), GFExport\start_export(), and GravityView_Uninstall_Test\test_fire_everything().
static current_user_can_any ($capabilities) static
Checks the permissions for the current user.
Returns true if the current user has any of the specified capabilities. IMPORTANT: Call this before calling any of the other API Functions as permission checks are not performed at lower levels.
Since
1.8.5.10 public
Parameters
array | string $capabilities An array of capabilities, or a single capability
Returns
bool Returns true if the current user has any of the specified capabilities
Definition at line 1286 of file api.php.
static delete_entry ($entry_id) static
Deletes a single Entry.
Since
1.8 public
Parameters
int $entry_id The ID of the Entry object
Returns
mixed Either true for success or a WP_Error instance
Definition at line 896 of file api.php.
References __, GFFormsModel\delete_lead(), and GFFormsModel\get_lead().
Referenced by GravityView_Delete_Entry\delete_or_trash_entry().
static delete_feed ($feed_id) static
Deletes a single Feed.
Since
1.8 public
Parameters
int $feed_id The ID of the Feed to delete
Returns
mixed Either an array of Feed objects or a WP_Error instance
Definition at line 1147 of file api.php.
References $wpdb, and __.
static delete_form ($form_id) static
Deletes the form with the given Form ID.
Since
1.8 public
Parameters
int $form_id The ID of the Form to delete
Returns
mixed True for success, or a WP_Error instance
Definition at line 105 of file api.php.
References $form, $form_id, and __.
static delete_forms ($form_ids) static
Deletes the forms with the given Form IDs.
Since
1.8 public
Parameters
array $form_ids An array of form IDs to delete
Definition at line 89 of file api.php.
References GFFormsModel\delete_forms().
static form_id_exists ($form_id) static
Private.
Since
1.8 private
Definition at line 1317 of file api.php.
References $form_id, $wpdb, and GFFormsModel\get_form_table_name().
static get_entries ($form_ids, $search_criteria = array(), $sorting = null, $paging = null, & $total_count = null) static
Returns an array of Entry objects for the given search criteria.
The search criteria array is constructed as follows:
Filter by status $search_criteria['status'] = 'active';
Filter by date range $search_criteria['start_date'] = $start_date; $search_criteria['end_date'] = $end_date;
Filter by any column in the main table $search_criteria['field_filters'][] = array("key" => 'currency', value => 'USD'); $search_criteria['field_filters'][] = array("key" => 'is_read', value => true);
Filter by Field Values $search_criteria['field_filters'][] = array('key' => '1', 'value' => 'gquiz159982170');
Filter Operators Supported operators for scalar values: is/=, isnot/<>, contains $search_criteria['field_filters'][] = array('key' => '1', 'operator' => 'contains', value' => 'Steve'); Supported operators for array values: in/=, not in/<>/!= $search_criteria['field_filters'][] = array('key' => '1', 'operator' => 'not in', value' => array('Alex', 'David', 'Dana');
Filter by a checkbox value (not recommended) $search_criteria['field_filters'][] = array('key' => '2.2', 'value' => 'gquiz246fec995'); note: this will work for checkboxes but it won't work if the checkboxes have been re-ordered - best to use the following examples below
Filter by a checkbox value (recommended) $search_criteria['field_filters'][] = array('key' => '2', 'value' => 'gquiz246fec995'); $search_criteria['field_filters'][] = array('key' => '2', 'operator' => 'not in', value' => array('First Choice', 'Third Choice');
Filter by a global search of values of any form field $search_criteria['field_filters'][] = array('value' => $search_value); OR $search_criteria['field_filters'][] = array('key' => 0, 'value' => $search_value);
Filter entries by Entry meta (added using the gform_entry_meta hook) $search_criteria['field_filters'][] = array('key' => 'gquiz_score', 'value' => '1'); $search_criteria['field_filters'][] = array('key' => 'gquiz_is_pass', 'value' => '1');
Filter by ALL / ANY of the field filters $search_criteria['field_filters']['mode'] = 'all'; // default $search_criteria['field_filters']['mode'] = 'any';
Sorting: column, field or entry meta $sorting = array('key' => $sort_field, 'direction' => 'ASC');
Paging $paging = array('offset' => 0, 'page_size' => 20);
Since
1.8 public
Parameters
int | array $form_ids The ID of the form or an array IDs of the Forms. Zero for all forms.
array $search_criteria Optional. An array containing the search criteria
array $sorting Optional. An array containing the sorting criteria
array $paging Optional. An array containing the paging criteria
int $total_count Optional. An output parameter containing the total number of entries. Pass a non-null value to get the total count.
Returns
mixed Either an array of the Entry objects or a WP_Error instance
Definition at line 449 of file api.php.
References $entries, and GFFormsModel\search_leads().
Referenced by GravityView_Uninstall_Test\_check_entries(), GVCommon\get_entries(), GVCommon\get_entry_id_from_slug(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), and GFExport\start_export().
static get_entry ($entry_id) static
Returns the Entry object for a given Entry ID.
Since
1.8 public
Parameters
int $entry_id The ID of the Entry
Returns
mixed The Entry object or a WP_Error instance
Definition at line 493 of file api.php.
References $entries, __, and null.
Referenced by add_entry(), GravityView_Admin_ApproveEntries\after_update_entry_update_approved_meta(), GFPaymentAddOn\ajax_cancel_subscription(), GV_Unit_Tests_Bootstrap\create_stubs(), GVCommon\get_entry(), GF_UnitTest_Factory_For_Entry\get_object_by_id(), GFEntryDetail\lead_detail_page(), GFPaymentAddOn\process_callback_action(), GFForms\update_lead_status(), and GravityView_Edit_Entry_User_Registration\update_user().
static get_feeds ($feed_ids = null, $form_id = null, $addon_slug = null, $is_active = true) static
Returns all the feeds for the given criteria.
Since
1.8 public
Parameters
mixed $feed_ids The ID of the Feed or an array of Feed IDs
int $form_id The ID of the Form to which the Feeds belong
string $addon_slug The slug of the add-on to which the Feeds belong
bool $is_active
Returns
mixed Either an array of Feed objects or a WP_Error instance
Definition at line 1098 of file api.php.
References $form_id, $wpdb, __, and ARRAY_A.
static get_fields_by_type ($form, $types, $use_input_type = false) static
Returns an array containing the form fields of the specified type or types.
Since
1.9.9.8
Parameters
array $form
array | string $types
bool $use_input_type
Returns
GF_Field[]
Definition at line 1303 of file api.php.
References $form, $types, and GFFormsModel\get_fields_by_type().
Referenced by GFAddOn\_field_condition_matches(), GF_Field_Password\delete_passwords(), GFPaymentAddOn\get_credit_card_field(), GFExport\get_field_row_count(), GFAddOn\get_first_field_by_type(), GFPaymentAddOn\get_payment_choices(), and GVCommon\has_product_field().
static get_form ($form_id) static
Returns the form object for a given Form ID.
Since
1.8 public
Parameters
int $form_id The ID of the Form
Returns
mixed The form meta array or false
Definition at line 34 of file api.php.
References $form, $form_id, absint(), GFFormsModel\get_form(), and GFFormsModel\get_form_meta().
Referenced by GravityView_Field_Time\_get_time_format_for_field(), GFPaymentAddOn\add_creditcard_token_input(), GFPaymentAddOn\ajax_cancel_subscription(), GFPaymentAddOn\before_delete_field(), GV_Unit_Tests_Bootstrap\create_stubs(), GFFormsModel\get_field_filters_where(), GFAddOn\get_first_field_by_type(), GVCommon\get_form(), GFFormDisplay\get_form(), get_forms(), GF_UnitTest_Factory_For_Form\get_object_by_id(), GFPaymentAddOn\post_payment_action(), GFFormDisplay\process_form(), submit_form(), GFFormsModel\update_lead_property(), GFForms\update_lead_status(), and GFAsyncUpload\upload().
static get_forms ($active = true, $trash = false) static
Returns all the form objects.
Since
1.8.11.5 public
Parameters
bool $active
bool $trash
Returns
mixed The array of Forms
Definition at line 65 of file api.php.
References $form_id, $forms, get_form(), and GFFormsModel\get_form_ids().
Referenced by GFFormsModel\get_field_filters_where(), GVCommon\get_forms(), GravityView_Uninstall_Test\test_fire_everything(), and GVCommon_Test\test_get_forms().
static send_notifications ($form, $entry, $event = 'form_submission') static
Sends all active notifications for a form given an entry object and an event.
Parameters
$form
$entry
string $event Default = 'form_submission'
Returns
array
Definition at line 1231 of file api.php.
References $form, and elseif.
Referenced by GFPaymentAddOn\post_payment_action().
static set_property_as_key ($array, $property) static private
Private.
Since
1.8 private
Definition at line 374 of file api.php.
static submit_form ($form_id, $input_values, $field_values = array(), $target_page = 0, $source_page = 1) static
Submits a form.
Use this function to send input values through the complete form submission process. Supports field validation, notifications, confirmations, multiple-pages and save & continue.
Example usage: $input_values['input_1'] = 'Single line text'; $input_values['input_2_3'] = 'First name'; $input_values['input_2_6'] = 'Last name'; $input_values['input_5'] = 'A paragraph of text.'; //$input_values['gform_save'] = true; // support for save and continue
$result = GFAPI::submit_form(52, $input_values);
Example output for a successful submission: 'is_valid' => boolean true 'page_number' => int 0 'source_page_number' => int 1 'confirmation_message' => string 'confirmation message [snip]'
Example output for failed validation: 'is_valid' => boolean false 'validation_messages' => array (size=1) 2 => string 'This field is required. Please enter the first and last name.' 'page_number' => int 1 'source_page_number' => int 1 'confirmation_message' => string ''
Example output for save and continue: 'is_valid' => boolean true 'page_number' => int 1 'source_page_number' => int 1 'confirmation_message' => string 'Please use the following link to return to your form from any computer. [snip]' 'resume_token' => string '045f941cc4c04d479556bab1db6d3495'
Parameters
int $form_id The Form ID
array $input_values An array of values.
array $field_values Optional.
int $target_page Optional.
int $source_page Optional.
Returns
array An array containing the result of the submission.
Definition at line 1017 of file api.php.
References $field, $form, $form_id, GFFormDisplay\$submission, __, absint(), get_form(), GFFormDisplay\process_form(), and GFFormDisplay\replace_save_variables().
static update_entries ($entries) static
Updates multiple Entry objects.
Since
1.8 public
Parameters
array $entries The Entry objects
Returns
mixed Either True for success, or a WP_Error instance
Definition at line 547 of file api.php.
References $entries, and is_wp_error().
static update_entry ($entry, $entry_id = null) static
Updates a single Entry object.
Since
1.8 public
Parameters
array $entry The Entry object
int $entry_id Optional. If specified, the ID in the Entry object will be ignored
Returns
mixed Either True or a WP_Error instance
Fires after the Entry is updated.
Parameters
array $lead The entry object after being updated.
array $original_entry The entry object before being updated.
Definition at line 573 of file api.php.
References $current_user, $field, $field_id, $form, $form_id, $post_id, $user_id, $wpdb, __, absint(), apply_filters(), esc_sql(), GFFormsModel\get_current_page_url(), GFFormsModel\get_entry_meta(), GFFormsModel\get_field(), GFFormsModel\get_form_meta(), GFFormsModel\get_input_type(), GFFormsModel\get_ip(), GFFormsModel\get_lead_detail_id(), GFFormsModel\get_lead_details_table_name(), GFFormsModel\get_lead_table_name(), gform_delete_meta(), gform_update_meta(), is_wp_error(), and GFFormsModel\update_lead_field_value().
Referenced by GFPaymentAddOn\complete_payment(), GFFormsModel\delete_password(), GFPaymentAddOn\process_subscription(), GFPaymentAddOn\start_subscription(), and GF_UnitTest_Factory_For_Entry\update_object().
static update_entry_field ($entry_id, $input_id, $value) static
Updates a single field of an entry.
Since
1.9 public
Parameters
int $entry_id The ID of the Entry object
string $input_id The id of the input to be updated. For single input fields such as text, paragraph, website, drop down etc... this will be the same as the field ID. For multi input fields such as name, address, checkboxes, etc... the input id will be in the format {FIELD_ID}.{INPUT NUMBER}. (i.e. "1.3") The $input_id can be obtained by inspecting the key for the specified field in the $entry object.
mixed $value The value to which the field should be set
Returns
bool Whether the entry property was updated successfully
Definition at line 940 of file api.php.
References $field, $form, $value, $wpdb, GFFormsModel\get_field(), GFFormsModel\get_lead_details_table_name(), is_wp_error(), and GFFormsModel\update_lead_field_value().
Referenced by GF_Field_Password\delete_passwords().
static update_entry_property ($entry_id, $property, $value) static
Updates a single property of an entry.
Since
1.8.3.1 public
Parameters
int $entry_id The ID of the Entry object
string $property The property of the Entry object to be updated
mixed $value The value to which the property should be set
Returns
bool Whether the entry property was updated successfully
Definition at line 920 of file api.php.
References $value, and GFFormsModel\update_lead_property().
Referenced by GFPaymentAddOn\add_pending_payment(), GFPaymentAddOn\cancel_subscription(), GravityView_Delete_Entry\delete_or_trash_entry(), GFPaymentAddOn\expire_subscription(), GFPaymentAddOn\fail_payment(), GFPaymentAddOn\fail_subscription_payment(), GFPaymentAddOn\refund_payment(), and GFPaymentAddOn\void_authorization().
static update_feed ($feed_id, $feed_meta, $form_id = null) static
Definition at line 1167 of file api.php.
References $form_id, $wpdb, and __.
static update_form ($form, $form_id = null) static
Updates the form with a given form object.
Since
1.8 public
Parameters
array $form The Form object
int $form_id Optional. If specified, then the ID in the Form object will be ignored
Returns
mixed True for success, or a WP_Error instance
Definition at line 150 of file api.php.
References $field, $form, $form_id, $wpdb, __, GFFormsModel\get_meta_table_name(), and GFFormsModel\update_form_meta().
static update_form_property ($form_id, $property_key, $value) static
Updates the property of one form - columns in the main forms table.
e.g. is_trash, is_active, title
Since
1.8.3.15 public
Parameters
array | int $form_id The ID of the forms to update
string $property_key The name of the column in the database e.g. is_trash, is_active, title
string $value The new value
Returns
mixed Either a WP_Error instance or the result of the query
Definition at line 273 of file api.php.
References $form_id, and $value.
static update_forms ($forms) static
Updates the forms with an array of form objects.
Since
1.8 public
Parameters
array $forms The Form objects
Returns
mixed True for success, or a WP_Error instance
Definition at line 126 of file api.php.
References $form, $forms, and is_wp_error().
static update_forms_property ($form_ids, $property_key, $value) static
Updates a form property - a column in the main forms table.
e.g. is_trash, is_active, title
Since
1.8.3.15 public
Parameters
array $form_ids The IDs of the forms to update
array $property_key The name of the column in the database e.g. is_trash, is_active, title
array $value The new value
Returns
mixed Either a WP_Error instance or the result of the query
Definition at line 231 of file api.php.
References $value, $wpdb, __, esc_sql(), GFFormsModel\get_form_db_columns(), and GFFormsModel\get_form_table_name().
The documentation for this class was generated from the following file:
api.php