GravityView: GravityView_Roles_Capabilities_Test Class Reference
GravityView_Roles_Capabilities_Test Class Reference
roles capabilities caps
Public Member Functions
authorless_view_statuses ()
test_all_caps ()
GravityView_Roles_Capabilities::all_caps
test_authorless_view ($status)
27020 authorless_view_statuses
test_get_instance ()
GravityView_Roles_Capabilities::get_instance
test_has_cap_cap_parameter ()
GravityView_Roles_Capabilities::has_cap GVCommon::has_cap
test_has_cap_gravityview_full_access ()
Test global gravityview_full_access permissions using the We create a user with no caps, check GravityView_Roles_Capabilities::has_cap GVCommon::has_cap.
test_has_cap_single_post_cap ()
GravityView_Roles_Capabilities::has_cap GVCommon::has_cap metacaps
test_has_cap_user_id_parameter ()
Test using the third $user->ID parameter for has_cap(), which checks against a provided $user_id We create a user with no caps, check GravityView_Roles_Capabilities::has_cap GVCommon::has_cap.
test_maybe_add_full_access_caps ()
GravityView_Roles_Capabilities::maybe_add_full_access_caps
test_merge_with_all_caps ()
GravityView_Roles_Capabilities::merge_with_all_caps
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
roles capabilities caps
Definition at line 10 of file GravityView_Roles_Capabilities_Test.php.
Member Function Documentation
authorless_view_statuses ()
Definition at line 111 of file GravityView_Roles_Capabilities_Test.php.
test_all_caps ()
GravityView_Roles_Capabilities::all_caps
Definition at line 48 of file GravityView_Roles_Capabilities_Test.php.
References GravityView_Roles_Capabilities\all_caps().
test_authorless_view ($status)
27020 authorless_view_statuses
Definition at line 119 of file GravityView_Roles_Capabilities_Test.php.
References $post.
test_get_instance ()
GravityView_Roles_Capabilities::get_instance
Definition at line 15 of file GravityView_Roles_Capabilities_Test.php.
References GravityView_Roles_Capabilities\get_instance().
test_has_cap_cap_parameter ()
GravityView_Roles_Capabilities::has_cap GVCommon::has_cap
Definition at line 89 of file GravityView_Roles_Capabilities_Test.php.
References GravityView_Roles_Capabilities\all_caps(), and GravityView_Roles_Capabilities\has_cap().
test_has_cap_gravityview_full_access ()
Test global gravityview_full_access permissions using the We create a user with no caps, check GravityView_Roles_Capabilities::has_cap GVCommon::has_cap.
Definition at line 179 of file GravityView_Roles_Capabilities_Test.php.
References GravityView_Roles_Capabilities\all_caps(), and GravityView_Roles_Capabilities\has_cap().
test_has_cap_single_post_cap ()
GravityView_Roles_Capabilities::has_cap GVCommon::has_cap metacaps
Definition at line 207 of file GravityView_Roles_Capabilities_Test.php.
References GravityView_Roles_Capabilities\has_cap().
test_has_cap_user_id_parameter ()
Test using the third $user->ID parameter for has_cap(), which checks against a provided $user_id We create a user with no caps, check GravityView_Roles_Capabilities::has_cap GVCommon::has_cap.
Definition at line 144 of file GravityView_Roles_Capabilities_Test.php.
References GravityView_Roles_Capabilities\all_caps(), and GravityView_Roles_Capabilities\has_cap().
test_maybe_add_full_access_caps ()
GravityView_Roles_Capabilities::maybe_add_full_access_caps
Definition at line 67 of file GravityView_Roles_Capabilities_Test.php.
References GravityView_Roles_Capabilities\maybe_add_full_access_caps().
test_merge_with_all_caps ()
GravityView_Roles_Capabilities::merge_with_all_caps
Definition at line 24 of file GravityView_Roles_Capabilities_Test.php.
References GravityView_Roles_Capabilities\all_caps(), and GravityView_Roles_Capabilities\merge_with_all_caps().
The documentation for this class was generated from the following file:
GravityView_Roles_Capabilities_Test.php