GravityView: Language_Pack_Upgrader Class Reference
Language_Pack_Upgrader Class Reference
Core class used for updating/installing language packs (translations) for plugins, themes, and core.
Public Member Functions
bulk_upgrade ($language_updates=array(), $args=array())
Bulk upgrade language packs.
check_package ($source, $remote_source)
Check the package source to make sure there are .mo and .po files.
get_name_for_update ($update)
Get the name of an item being updated.
upgrade ($update=false, $args=array())
Upgrade a language pack.
upgrade_strings ()
Initialize the upgrade strings.
Public Member Functions inherited from WP_Upgrader
__construct ($skin=null)
Construct the upgrader with a skin.
clear_destination ($remote_destination)
Clears the directory where this item is going to be installed into.
download_package ($package)
Download a package.
fs_connect ($directories=array(), $allow_relaxed_file_ownership=false)
Connect to the filesystem.
generic_strings ()
Add the generic strings to WP_Upgrader::$strings.
init ()
Initialize the upgrader.
install_package ($args=array())
Install a package.
maintenance_mode ($enable=false)
Toggle maintenance mode for the site.
run ($options)
Run an upgrade/install.
unpack_package ($package, $delete_package=true)
Unpack a compressed package file.
Static Public Member Functions
static async_upgrade ($upgrader=false)
Asynchronously upgrades language packs after other upgrades have been made.
Data Fields
$bulk = true
Whether a bulk upgrade/install is being performed.
$result
Result of the language pack upgrade.
Data Fields inherited from WP_Upgrader
$result = array()
$skin = null
The upgrader skin being used.
$strings = array()
The error/notification strings used to update the user on the progress.
$update_count = 0
The total number of updates being performed.
$update_current = 0
Detailed Description
Core class used for updating/installing language packs (translations) for plugins, themes, and core.
Since
3.7.0
See also
WP_Upgrader
Definition at line 1819 of file class-wp-upgrader.php.
Member Function Documentation
static async_upgrade ($upgrader = false) static
Asynchronously upgrades language packs after other upgrades have been made.
Hooked to the {
See also
'upgrader_process_complete'} action by default.
Since
3.7.0 public
Parameters
false | WP_Upgrader $upgrader Optional. WP_Upgrader instance or false. If $upgrader is a Language_Pack_Upgrader instance, the method will bail to avoid recursion. Otherwise unused. Default false.
Filter whether to asynchronously update translation for core, a plugin, or a theme.
Since
4.0.0
Parameters
bool $update Whether to update.
object $language_update The update offer.
Definition at line 1853 of file class-wp-upgrader.php.
References WP_Upgrader\$skin, $update, apply_filters(), WP_CONTENT_DIR, and wp_get_translation_updates().
bulk_upgrade ($language_updates = array(), $args = array())
Bulk upgrade language packs.
Since
3.7.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
array $language_updates Optional. Language pack updates. Default empty array.
array $args { Optional. Other arguments for upgrading multiple language packs. Default empty array
bool $clear_update_cache Whether to clear the update cache when done. Default true. }
Returns
array|bool|WP_Error Will return an array of results, or true if there are no updates, false or WP_Error for initial errors.
Definition at line 1968 of file class-wp-upgrader.php.
References $options, $result, add_filter(), current_filter(), elseif, WP_Upgrader\fs_connect(), WP_Upgrader\init(), remove_all_filters(), remove_filter(), WP_Upgrader\run(), upgrade_strings(), wp_clean_update_cache(), WP_CONTENT_DIR, wp_get_translation_updates(), and wp_parse_args().
Referenced by upgrade().
check_package ($source, $remote_source)
Check the package source to make sure there are .mo and .po files.
Hooked to the {
See also
'upgrader_source_selection'} filter by {
Language_Pack_Upgrader::bulk_upgrade()}.
Since
3.7.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string | WP_Error $source
string $remote_source
Definition at line 2089 of file class-wp-upgrader.php.
References $file, __, elseif, and is_wp_error().
get_name_for_update ($update)
Get the name of an item being updated.
Since
3.7.0 public
Parameters
object $update The data for an update.
Returns
string The name of the item being updated.
Definition at line 2129 of file class-wp-upgrader.php.
References $theme, $update, get_plugins(), and wp_get_theme().
upgrade ($update = false, $args = array())
Upgrade a language pack.
Since
3.7.0 public
Parameters
string | false $update Optional. Whether an update offer is available. Default false.
array $args Optional. Other optional arguments, see {
See also
Language_Pack_Upgrader::bulk_upgrade()}. Default empty array.
Returns
array|bool|WP_Error The result of the upgrade, or a {
See also
wP_Error} object instead.
Definition at line 1936 of file class-wp-upgrader.php.
References $update, and bulk_upgrade().
upgrade_strings ()
Initialize the upgrade strings.
Since
3.7.0 public
Definition at line 1915 of file class-wp-upgrader.php.
References __.
Referenced by bulk_upgrade().
Field Documentation
bool $bulk = true
Whether a bulk upgrade/install is being performed.
Since
3.7.0 public
Definition at line 1838 of file class-wp-upgrader.php.
array WP_Error $result
Result of the language pack upgrade.
Since
3.7.0 public
See also
WP_Upgrader::$result
Definition at line 1829 of file class-wp-upgrader.php.
Referenced by bulk_upgrade().
The documentation for this class was generated from the following file:
class-wp-upgrader.php