GravityView: WP_Site_Icon Class Reference
WP_Site_Icon Class Reference
Core class used to implement site icon functionality.
Public Member Functions
__construct ()
Registers actions and filters.
additional_sizes ($sizes=array())
Adds additional sizes to be made when creating the site_icon images.
create_attachment_object ($cropped, $parent_attachment_id)
Creates an attachment 'object'.
delete_attachment_data ($post_id)
Deletes the Site Icon when the image file is deleted.
get_post_metadata ($value, $post_id, $meta_key, $single)
Adds custom image sizes when meta data for an image is requested, that happens to be used as Site Icon.
insert_attachment ($object, $file)
Inserts an attachment.
intermediate_image_sizes ($sizes=array())
Adds Site Icon sizes to the array of image sizes on demand.
Data Fields
$min_size = 512
$page_crop = 512
$site_icon_sizes
Detailed Description
Core class used to implement site icon functionality.
Since
4.3.0
Definition at line 15 of file class-wp-site-icon.php.
Constructor & Destructor Documentation
__construct ()
Registers actions and filters.
Since
4.3.0 public
Definition at line 75 of file class-wp-site-icon.php.
References add_action(), and add_filter().
Member Function Documentation
additional_sizes ($sizes = array())
Adds additional sizes to be made when creating the site_icon images.
Since
4.3.0 public
Parameters
array $sizes List of additional sizes.
Returns
array Additional image sizes.
Filter the different dimensions that a site icon is saved in.
Since
4.3.0
Parameters
array $site_icon_sizes Sizes available for the Site Icon.
Definition at line 147 of file class-wp-site-icon.php.
References $name, $size, and apply_filters().
create_attachment_object ($cropped, $parent_attachment_id)
Creates an attachment 'object'.
Since
4.3.0
Parameters
string $cropped Cropped image URL.
int $parent_attachment_id Attachment ID of parent image.
Returns
array Attachment object.
Definition at line 89 of file class-wp-site-icon.php.
References $size, $url, get_post(), str_replace, and wp_get_attachment_url().
delete_attachment_data ($post_id)
Deletes the Site Icon when the image file is deleted.
Since
4.3.0 public
Parameters
int $post_id Attachment ID.
Definition at line 210 of file class-wp-site-icon.php.
References $post_id, delete_option(), and get_option().
get_post_metadata ($value, $post_id, $meta_key, $single)
Adds custom image sizes when meta data for an image is requested, that happens to be used as Site Icon.
Since
4.3.0 public
Parameters
null | array | string $value The value get_metadata() should return a single metadata value, or an array of values.
int $post_id Post ID.
string $meta_key Meta key.
string | array $single Meta value, or an array of values.
Returns
array|null|string The attachment metadata value, array of values, or null.
Definition at line 231 of file class-wp-site-icon.php.
References $post_id, $value, add_filter(), and get_option().
insert_attachment ($object, $file)
Inserts an attachment.
Since
4.3.0 public
Parameters
array $object Attachment object.
string $file File path of the attached image.
Returns
int Attachment ID
Filter the site icon attachment metadata.
Since
4.3.0
See also
wp_generate_attachment_metadata()
Parameters
array $metadata Attachment metadata.
Definition at line 119 of file class-wp-site-icon.php.
References $file, $metadata, apply_filters(), wp_generate_attachment_metadata(), wp_insert_attachment(), and wp_update_attachment_metadata().
intermediate_image_sizes ($sizes = array())
Adds Site Icon sizes to the array of image sizes on demand.
Since
4.3.0 public
Parameters
array $sizes List of image sizes.
Returns
array List of intermediate image sizes.
This filter is documented in wp-admin/includes/class-wp-site-icon.php
Definition at line 192 of file class-wp-site-icon.php.
References $size, and apply_filters().
Field Documentation
$min_size = 512
Definition at line 24 of file class-wp-site-icon.php.
$page_crop = 512
Definition at line 33 of file class-wp-site-icon.php.
$site_icon_sizes
Initial value:
= array(
        270,
        192,
        180,
        32,
    )
Definition at line 42 of file class-wp-site-icon.php.
The documentation for this class was generated from the following file:
class-wp-site-icon.php