GravityView: GravityView_Admin_ApproveEntries Class Reference
GravityView_Admin_ApproveEntries Class Reference
Public Member Functions
__construct ()
add_field_buttons ($field_groups)
Inject new add field buttons in the gravity form editor page.
add_scripts_and_styles ($hook)
after_submission ($entry, $form)
Update the is_approved meta whenever the entry is submitted (and it contains a User Opt-in field)
after_update_entry_update_approved_meta ($form, $entry_id=NULL)
Update the is_approved meta whenever the entry is updated.
filter_links_entry_list ($filter_links=array(), $form=array(), $include_counts=true)
Add filter links to the Entries page.
process_bulk_action ()
Capture bulk actions - gf_entries table.
register_gform_noconflict_script ($scripts)
register_gform_noconflict_style ($styles)
set_defaults ()
At edit form page, set the field Approve defaults.
tooltips ($tooltips)
Add the GravityView Fields group tooltip.
Static Public Member Functions
static add_entry_approved_hidden_input ($form_id, $field_id, $value, $entry, $query_string)
Add a hidden input that is used in the Javascript to show approved/disapproved entries checkbox.
static get_approved_column ($form)
Calculate the approve field.input id.
Data Fields
$bulk_update_message = ''
Private Member Functions
add_hooks ()
get_bulk_actions ($form_id)
Get an array of options to be added to the Gravity Forms "Bulk action" dropdown in a "GravityView" option group.
get_first_form_id ()
Get the first form ID from Gravity Forms, sorted in the same order as in the All Forms page.
get_form_id ()
Get the form ID of the form currently being displayed.
get_gv_bulk_action ()
Get the Bulk Action submitted value if it is a GravityView Approve/Unapprove action.
show_approve_entry_column ($form_id)
Should the Approve/Reject Entry column be shown in the GF Entries page?
Static Private Member Functions
static update_approved_meta ($entry_id, $is_approved, $form_id=0)
Update the is_approved entry meta value.
static update_bulk ($entries, $approved, $form_id)
Process a bulk of entries to update the approve field/property.
Private Attributes
$bulk_action_prefixes
Detailed Description
Definition at line 15 of file class-admin-approve-entries.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 29 of file class-admin-approve-entries.php.
References add_hooks().
Member Function Documentation
static add_entry_approved_hidden_input ($form_id, $field_id, $value, $entry, $query_string) static
Add a hidden input that is used in the Javascript to show approved/disapproved entries checkbox.
See the /assets/js/admin-entries-list.js setInitialApprovedEntries method
Parameters
$form_id
$field_id
$value
$entry
$query_string
Returns
void
Definition at line 660 of file class-admin-approve-entries.php.
References $entry, and GVCommon\has_cap().
add_field_buttons ($field_groups)
Inject new add field buttons in the gravity form editor page.
public
Parameters
mixed $field_groups
Returns
array Array of fields
Definition at line 161 of file class-admin-approve-entries.php.
add_hooks () private
Edit Gravity Form page
gf_entries page - entries table screen
Definition at line 35 of file class-admin-approve-entries.php.
Referenced by __construct().
add_scripts_and_styles ($hook)
Definition at line 720 of file class-admin-approve-entries.php.
References $form_id, get_bulk_actions(), get_form_id(), GRAVITYVIEW_FILE, GVCommon\has_cap(), show_approve_entry_column(), and GravityView_Plugin\version.
after_submission ($entry, $form)
Update the is_approved meta whenever the entry is submitted (and it contains a User Opt-in field)
Since
1.16.6
Parameters
$entry array Gravity Forms entry object
$form array Gravity Forms form object
Definition at line 470 of file class-admin-approve-entries.php.
References $entry, and after_update_entry_update_approved_meta().
after_update_entry_update_approved_meta ($form, $entry_id = NULL)
Update the is_approved meta whenever the entry is updated.
Since
1.7.6.1 Was previously named update_approved_meta
Parameters
array $form Gravity Forms form array
int $entry_id ID of the Gravity Forms entry
Returns
void
If the form doesn't contain the approve field, don't assume anything.
Definition at line 485 of file class-admin-approve-entries.php.
References $entry.
Referenced by after_submission().
filter_links_entry_list ($filter_links = array(), $form = array(), $include_counts = true)
Add filter links to the Entries page.
Can be disabled by returning false on the gravityview/approve_entries/show_filter_links_entry_list filter
Since
1.17.1
Parameters
array $filter_links Array of links to include in the subsubsub filter list. Includes id, field_filters, count, and label keys
array $form GF Form object of current form
bool $include_counts Whether to include counts in the output
Returns
array Filter links, with GravityView approved/disapproved links added
Runs Filter:
gravityview/approve_entries/show_filter_links_entry_list Disable filter links
Since
1.17.1
Parameters
bool $show_filter_links True: show the "approved"/"disapproved" filter links. False: hide them.
array $form GF Form object of current form
Definition at line 85 of file class-admin-approve-entries.php.
References gravityview_get_entry_ids().
static get_approved_column ($form) static
Calculate the approve field.input id.
public
Parameters
mixed $form GF Form or Form ID
Returns
false|null|string Returns the input ID of the approved field. Returns NULL if no approved fields were found. Returns false if $form_id wasn't set.
Definition at line 614 of file class-admin-approve-entries.php.
References $field, and GVCommon\get_form().
get_bulk_actions ($form_id) private
Get an array of options to be added to the Gravity Forms "Bulk action" dropdown in a "GravityView" option group.
Since
1.16.3
Parameters
int $form_id ID of the form currently being displayed
Returns
array Array of actions to be added to the GravityView option group
Runs Filter:
gravityview/approve_entries/bulk_actions Modify the GravityView "Bulk action" dropdown list. Return an empty array to hide.
See also
https://gist.github.com/zackkatz/82785402c996b51b4dc9 for an example of how to use this filter
Since
1.16.3
Parameters
array $bulk_actions Associative array of actions to be added to "Bulk action" dropdown inside GravityView <optgroup>. Parent array key is the <optgroup> label, then each child array must have label (displayed text) and value (input value) keys
int $form_id ID of the form currently being displayed
Definition at line 772 of file class-admin-approve-entries.php.
References $form_id.
Referenced by add_scripts_and_styles().
get_first_form_id () private
Get the first form ID from Gravity Forms, sorted in the same order as in the All Forms page.
See also
GFEntryList::all_entries_page() This method is based on the form-selecting code here
Since
1.17.2
Returns
int ID of the first form, sorted by title. 0 if no forms were found.
Definition at line 703 of file class-admin-approve-entries.php.
References $form_id, and $forms.
Referenced by get_form_id().
get_form_id () private
Get the form ID of the form currently being displayed.
Since
1.17.1
Returns
int ID of the current form being displayed. 0 is returned if no forms are found.
Definition at line 682 of file class-admin-approve-entries.php.
References $form_id, and get_first_form_id().
Referenced by add_scripts_and_styles().
get_gv_bulk_action () private
Get the Bulk Action submitted value if it is a GravityView Approve/Unapprove action.
Since
1.17.1
Returns
string|false If the bulk action was GravityView Approve/Unapprove, return the full string (gvapprove-16, gvunapprove-16). Otherwise, return false.
Definition at line 254 of file class-admin-approve-entries.php.
Referenced by process_bulk_action().
process_bulk_action ()
Capture bulk actions - gf_entries table.
GravityView_frontend::get_search_criteria() Convert the $_POST search request into a properly formatted request. public
Returns
void|boolean
The extra '-' is to make sure that there are at least two items in array.
See also
https://github.com/katzwebservices/GravityView/issues/370
Definition at line 280 of file class-admin-approve-entries.php.
References $entries, $form_id, get_gv_bulk_action(), GravityView_frontend\get_search_criteria(), and gravityview_get_entry_ids().
register_gform_noconflict_script ($scripts)
Definition at line 846 of file class-admin-approve-entries.php.
register_gform_noconflict_style ($styles)
Definition at line 851 of file class-admin-approve-entries.php.
set_defaults ()
At edit form page, set the field Approve defaults.
Definition at line 196 of file class-admin-approve-entries.php.
show_approve_entry_column ($form_id) private
Should the Approve/Reject Entry column be shown in the GF Entries page?
Since
1.7.2
Parameters
int $form_id The ID of the Gravity Forms form for which entries are being shown
Returns
bool True: Show column; False: hide column
Runs Filter:
gravityview/approve_entries/hide-if-no-connections Return true to hide reject/approve if there are no connected Views
Since
1.7.2
Parameters
boolean $hide_if_no_connections
Runs Filter:
gravityview/approve_entries/show-column Override whether the column is shown
Parameters
boolean $show_approve_column Whether the column will be shown
int $form_id The ID of the Gravity Forms form for which entries are being shown
Definition at line 816 of file class-admin-approve-entries.php.
References $form_id, gravityview_get_connected_views(), and GVCommon\has_cap().
Referenced by add_scripts_and_styles().
tooltips ($tooltips)
Add the GravityView Fields group tooltip.
Parameters
$tooltips
Returns
array Tooltips array with GravityView fields tooltip
Definition at line 143 of file class-admin-approve-entries.php.
static update_approved_meta ($entry_id, $is_approved, $form_id = 0) static private
Update the is_approved entry meta value.
Since
1.7.6.1 after_update_entry_update_approved_meta was previously to be named update_approved_meta
1.17.1 Added $form_id parameter
Parameters
int $entry_id ID of the Gravity Forms entry
string $is_approved String whether entry is approved or not. 0 for not approved, Approved for approved.
int $form_id ID of the form of the entry being updated. Improves query performance.
Returns
void
Make sure that the "User Opt-in" and the Admin Approve/Reject entry set the same meta value
Since
1.16.6
Runs Actions:
gravityview/approve_entries/updated Triggered when an entry approval is updated
Since
1.7.6.1
Parameters
int $entry_id ID of the Gravity Forms entry
string $is_approved String whether entry is approved or not. 0 for not approved, Approved for approved.
Runs Actions:
gravityview/approve_entries/disapproved Triggered when an entry is rejected
Since
1.7.6.1
Parameters
int $entry_id ID of the Gravity Forms entry
Runs Actions:
gravityview/approve_entries/approved Triggered when an entry is approved
Since
1.7.6.1
Parameters
int $entry_id ID of the Gravity Forms entry
Definition at line 514 of file class-admin-approve-entries.php.
References $form_id.
static update_bulk ($entries, $approved, $form_id) static private
Process a bulk of entries to update the approve field/property.
private
Parameters
array | boolean $entries If array, array of entry IDs that are to be updated. If true: update all entries.
int $approved Approved status. If 0: unapproved, if not empty, Approved
int $form_id The Gravity Forms Form ID
Returns
boolean|void
Definition at line 365 of file class-admin-approve-entries.php.
References $entries, $form_id, and GVCommon\has_cap().
Field Documentation
$bulk_action_prefixes private
Initial value:
= array(
        'approve' => 'gvapprove',
        'unapprove' => 'gvunapprove',
    )
Definition at line 24 of file class-admin-approve-entries.php.
$bulk_update_message = ''
Definition at line 18 of file class-admin-approve-entries.php.
The documentation for this class was generated from the following file:
class-admin-approve-entries.php