GravityView: GravityView_Field_FileUpload Class Reference
GravityView_Field_FileUpload Class Reference
Add custom options for date fields.
Public Member Functions
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Public Member Functions inherited from GravityView_Field
__construct ()
add_field_support ($key= '', &$field_options)
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Tap in here to modify field options.
Static Public Member Functions
static get_files_array ($value, $gv_class)
Return an array of files prepared for output.
Data Fields
$name = 'fileupload'
Data Fields inherited from GravityView_Field
$contexts = array('single', 'multiple', 'edit', 'export')
$description
$group
$is_numeric
$is_searchable
$is_sortable
$label
$name
$search_operators
Additional Inherited Members
Protected Attributes inherited from GravityView_Field
$_field_id = ''
$_field_options = array()
$_gf_field_class_name
Detailed Description
Add custom options for date fields.
Definition at line 10 of file includes/fields/fileupload.php.
Member Function Documentation
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Definition at line 14 of file includes/fields/fileupload.php.
static get_files_array ($value, $gv_class) static
Return an array of files prepared for output.
Processes files by file type and generates unique output for each. Returns array for each file, with the following keys:
file_path => The file path of the file, with a line break
html => The file output HTML formatted
Since
1.2
Runs Filter:
gravityview_audio_settings Modify the settings passed to the wp_video_shortcode() function
Since
1.2
Parameters
array $audio_settings Array with src and class keys
Generate the audio shortcode
See also
http://codex.wordpress.org/Audio_Shortcode
https://developer.wordpress.org/reference/functions/wp_audio_shortcode/
Runs Filter:
gravityview_video_settings Modify the settings passed to the wp_video_shortcode() function
Since
1.2
Parameters
array $video_settings Array with src and class keys
Generate the video shortcode
See also
http://codex.wordpress.org/Video_Shortcode
https://developer.wordpress.org/reference/functions/wp_video_shortcode/
Runs Filter:
gravityview/fields/fileupload/link_atts Modify the link attributes for a file upload field
Parameters
array | string $link_atts Array or attributes string
array $field Current GravityView field array
Runs Filter:
gravityview/fields/fileupload/disable_link Filter to alter the default behaviour of wrapping images (or image names) with a link to the content object
Since
1.5.1
Parameters
bool $disable_wrapped_link whether to wrap the content with a link to the content object.
array $gravityview_view-,>field_data
See also
GravityView_API:field_value() for info about $gravityview_view->field_data
Modify the link text (defaults to the file name)
Since
1.7
Parameters
string $content The existing anchor content. Could be <img> tag, audio/video embed or the file name
array $field GravityView array of the current field being processed
Runs Filter:
gravityview/fields/fileupload/files_array Modify the files array
Since
1.7
Parameters
array $output_arr Associative array of files
string $file_path The path to the file as stored in Gravity Forms
string $content The generated output for the file
array $field GravityView array of the current field being processed
Definition at line 46 of file includes/fields/fileupload.php.
References $content, $field, $field_settings, $gravityview_view, $image, $link_atts, $value, GravityView_API\entry_link(), GravityView_View\getInstance(), gravityview_get_context(), and gravityview_get_link().
Referenced by gravityview_get_files_array().
Field Documentation
$name = 'fileupload'
Definition at line 12 of file includes/fields/fileupload.php.
The documentation for this class was generated from the following file:
includes/fields/fileupload.php