GravityView: Admin Class Reference
Admin Class Reference
Public Member Functions
__construct (Config $config, Logging $logging)
Admin constructor.
admin_bar_add_toolbar_items ($admin_bar)
Adds a "Revoke TrustedLogin" menu item to the admin toolbar.
admin_menu_auth_link_page ()
Generates the auth link page.
admin_notice_revoked ()
Notice: Shown when a support user is manually revoked by admin;.
admin_notices ()
Add admin_notices hooks.
generate_button ($atts=array(), $print=true)
Output the TrustedLogin Button and required scripts.
get_auth_header_html ()
get_auth_screen ()
Output the contents of the Auth Link Page in wp-admin.
get_button ($atts=array())
Generates HTML for a TrustedLogin Grant Access button.
init ()
maybe_print_request_screen ()
If the current request is a valid login screen override, print the TrustedLogin request screen.
output_support_users ($print=true, $atts=array())
Outputs table of created support users.
print_auth_screen ()
Outputs the TrustedLogin authorization screen.
print_request_screen ()
register_assets ()
Register the required scripts and styles.
translations ()
Helper function: Build translate-able strings for alert messages.
user_row_action_revoke ($actions, $user_object)
Filter: Update the actions on the users.php list for our support users.
Data Fields
const ABOUT_LIVE_ACCESS_URL = 'https://www.trustedlogin.com/about/live-access/'
const ABOUT_TL_URL = 'https://www.trustedlogin.com/about/easy-and-safe/'
URL pointing to the "About TrustedLogin" page, shown below the Grant Access dialog.
Private Member Functions
get_caps_html ()
Get role capabilities HTML the Auth form.
get_caps_section ($caps_array, $heading='', $dashicon='')
Generate additional/removed capabilities sections.
get_details_html ()
get_footer_html ()
Returns the HTML for the footer in the Auth form.
get_header_html ()
get_intro ()
get_login_inline_css ()
Returns inline CSS overrides for the common CSS dependency.
get_logo_html ()
get_notices_html ()
Generates HTML for notices about current server environment perhaps not being accessible.
get_reference_html ()
Shows the current site URL and, if passed as $_GET['ref'], a support reference ID.
is_login_screen ()
Is this a login screen and should TrustedLogin override the login screen for the current namespace?
prepare_output ($template, $content, $wp_kses=true)
Private Attributes
$config
$logging
$site_access
$support_user
Detailed Description
Definition at line 25 of file Admin.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Logging $logging)
Admin constructor.
Parameters
Config $config
Definition at line 59 of file Admin.php.
References Admin\$config, and Admin\$logging.
Member Function Documentation
admin_bar_add_toolbar_items()
admin_bar_add_toolbar_items ($admin_bar)
Adds a "Revoke TrustedLogin" menu item to the admin toolbar.
Parameters
WP_Admin_Bar $admin_bar
Returns
void
Definition at line 158 of file Admin.php.
admin_menu_auth_link_page()
admin_menu_auth_link_page ()
Generates the auth link page.
This simulates the addition of an admin submenu item with null as the menu location
Since
1.0.0
Returns
void
Definition at line 203 of file Admin.php.
admin_notice_revoked()
admin_notice_revoked ()
Notice: Shown when a support user is manually revoked by admin;.
Returns
void
Definition at line 1194 of file Admin.php.
admin_notices()
admin_notices ()
Add admin_notices hooks.
Returns
void
Definition at line 1185 of file Admin.php.
generate_button()
generate_button ($atts = array(), $print = true)
Output the TrustedLogin Button and required scripts.
Since
1.0.0
Parameters
array $atts {
See also
get_button()} for configuration array
Parameters
bool $print Should results be printed and returned (true) or only returned (false)
Returns
string the HTML output
Definition at line 826 of file Admin.php.
References Admin\get_button(), Client\get_reference_id(), Endpoint\REVOKE_SUPPORT_QUERY_PARAM, and Admin\translations().
Referenced by Admin\get_auth_screen().
get_auth_header_html()
get_auth_header_html ()
Definition at line 344 of file Admin.php.
References $content, Admin\$support_user, $template, and Admin\prepare_output().
Referenced by Admin\get_auth_screen().
get_auth_screen()
get_auth_screen ()
Output the contents of the Auth Link Page in wp-admin.
Since
1.0.0
Returns
string HTML of the Auth screen
Filter trustedlogin/{ns}/template/auth
Parameters
string $output_template The Auth form HTML
Definition at line 383 of file Admin.php.
References $content, $output, Admin\generate_button(), Admin\get_auth_header_html(), Admin\get_details_html(), Admin\get_footer_html(), Admin\get_header_html(), Admin\get_intro(), Admin\get_notices_html(), Admin\get_reference_html(), and Admin\prepare_output().
Referenced by Admin\print_auth_screen(), and Admin\print_request_screen().
get_button()
get_button ($atts = array())
Generates HTML for a TrustedLogin Grant Access button.
Parameters
array $atts {
string $text Button text to grant access. Sanitized using esc_html(). Default: "Grant %s Access" (s replaced with vendor/title setting)
string $exists_text Button text when vendor already has a support account. Sanitized using esc_html(). Default: "Extend %s Access" (s replaced with vendor/title setting)
string $size WordPress CSS button size. Options: 'small', 'normal', 'large', 'hero'. Default: "hero"
string $class CSS class added to the button. Default: "button-primary"
string $tag Tag used to display the button. Options: 'a', 'button', 'span'. Default: "a"
bool $powered_by Whether to display the TrustedLogin badge on the button. Default: true
string $support_url The URL to use as a backup if JavaScript fails or isn't available. Sanitized using esc_url(). Default: vendor/support_url configuration setting URL. }
Returns
string
Definition at line 888 of file Admin.php.
References $href, and $value.
Referenced by Admin\generate_button().
get_caps_html()
get_caps_html () private
Get role capabilities HTML the Auth form.
Returns
string Empty string if there are no caps defined. Otherwise, HTML of caps in lists.
Definition at line 567 of file Admin.php.
References Admin\get_caps_section().
Referenced by Admin\get_details_html().
get_caps_section()
get_caps_section ($caps_array, $heading = '', $dashicon = '') private
Generate additional/removed capabilities sections.
Parameters
array $caps_array Associative array of cap => reason why cap is set
string $heading Text to show for the heading of the caps section
string $dashicon CSS class for the specific dashicon
Returns
string
Definition at line 592 of file Admin.php.
References $output.
Referenced by Admin\get_caps_html().
get_details_html()
get_details_html () private
Definition at line 510 of file Admin.php.
References $content, Admin\get_caps_html(), Admin\output_support_users(), and Admin\prepare_output().
Referenced by Admin\get_auth_screen().
get_footer_html()
get_footer_html () private
Returns the HTML for the footer in the Auth form.
Returns
string
Filter trustedlogin/template/auth/footer_links
Used to add/remove Footer Links on grantlink page
Since
1.0.0
Parameters
array Array of links to show in auth footer (Key is anchor text; Value is URL)
Definition at line 679 of file Admin.php.
References $link, Client\get_reference_id(), and Client\VERSION.
Referenced by Admin\get_auth_screen().
get_header_html()
get_header_html () private
Definition at line 439 of file Admin.php.
References Admin\get_logo_html(), Admin\is_login_screen(), and Admin\prepare_output().
Referenced by Admin\get_auth_screen().
get_intro()
get_intro () private
Definition at line 486 of file Admin.php.
References Admin\is_login_screen().
Referenced by Admin\get_auth_screen().
get_login_inline_css()
get_login_inline_css () private
Returns inline CSS overrides for the common CSS dependency.
Since
1.0.0
Returns
string
Definition at line 315 of file Admin.php.
Referenced by Admin\print_request_screen().
get_logo_html()
get_logo_html () private
Returns
string
Definition at line 654 of file Admin.php.
Referenced by Admin\get_header_html().
get_notices_html()
get_notices_html () private
Generates HTML for notices about current server environment perhaps not being accessible.
Returns
string
Definition at line 621 of file Admin.php.
References $content, and Admin\prepare_output().
Referenced by Admin\get_auth_screen().
get_reference_html()
get_reference_html () private
Shows the current site URL and, if passed as $_GET['ref'], a support reference ID.
Returns
string
Definition at line 463 of file Admin.php.
References $content, $template, Client\get_reference_id(), Admin\is_login_screen(), and Admin\prepare_output().
Referenced by Admin\get_auth_screen().
init()
init ()
Definition at line 67 of file Admin.php.
is_login_screen()
is_login_screen () private
Is this a login screen and should TrustedLogin override the login screen for the current namespace?
Returns
bool
Definition at line 250 of file Admin.php.
Referenced by Admin\get_header_html(), Admin\get_intro(), Admin\get_reference_html(), Admin\maybe_print_request_screen(), and Admin\output_support_users().
maybe_print_request_screen()
maybe_print_request_screen ()
If the current request is a valid login screen override, print the TrustedLogin request screen.
Returns
void
Definition at line 259 of file Admin.php.
References Admin\is_login_screen(), and Admin\print_request_screen().
output_support_users()
output_support_users ($print = true, $atts = array())
Outputs table of created support users.
Since
1.0.0
Parameters
bool $print Whether to print and return (true) or return (false) the results. Default: true
array $atts Settings for the table. {
bool $current_url Whether to generate Revoke links based on the current URL. Default: false. }
Returns
string HTML table of active support users for vendor. Empty string if current user can't create_users
Definition at line 1113 of file Admin.php.
References Admin\is_login_screen().
Referenced by Admin\get_details_html().
prepare_output()
prepare_output ($template, $content, $wp_kses = true) private
Definition at line 726 of file Admin.php.
References $content, $template, and $value.
Referenced by Admin\get_auth_header_html(), Admin\get_auth_screen(), Admin\get_details_html(), Admin\get_header_html(), Admin\get_notices_html(), and Admin\get_reference_html().
print_auth_screen()
print_auth_screen ()
Outputs the TrustedLogin authorization screen.
Since
1.0.0
Returns
void
Definition at line 340 of file Admin.php.
References Admin\get_auth_screen().
print_request_screen()
print_request_screen ()
Definition at line 278 of file Admin.php.
References Admin\get_auth_screen(), and Admin\get_login_inline_css().
Referenced by Admin\maybe_print_request_screen().
register_assets()
register_assets ()
Register the required scripts and styles.
Since
1.0.0
Definition at line 123 of file Admin.php.
References Client\VERSION.
translations()
translations ()
Helper function: Build translate-able strings for alert messages.
Since
1.0.0
Returns
array of Translations and strings to be localized to JS variables
Filter: Allow for adding into GET parameters on support_url
Since
1.0.0
$url_query_args = [
  'message' => (string) What error should be sent to the support system.
];
Parameters
array $url_query_args {
string $message What error should be sent to the support system.
string | null $ref A sanitized reference ID, if passed. Otherwise, null. }
Definition at line 974 of file Admin.php.
References Client\get_reference_id(), and Endpoint\REVOKE_SUPPORT_QUERY_PARAM.
Referenced by Admin\generate_button().
user_row_action_revoke()
user_row_action_revoke ($actions, $user_object)
Filter: Update the actions on the users.php list for our support users.
Since
1.0.0
Parameters
array $actions
WP_User $user_object
Returns
array
Definition at line 101 of file Admin.php.
Field Documentation
$config
$config private
Definition at line 37 of file Admin.php.
Referenced by Admin\__construct().
$logging
null Logging $logging private
Definition at line 52 of file Admin.php.
Referenced by Admin\__construct().
$site_access
SiteAccess $site_access private
Definition at line 42 of file Admin.php.
$support_user
SupportUser $support_user private
Definition at line 47 of file Admin.php.
Referenced by Admin\get_auth_header_html().
ABOUT_LIVE_ACCESS_URL
const ABOUT_LIVE_ACCESS_URL = 'https://www.trustedlogin.com/about/live-access/'
Definition at line 32 of file Admin.php.
ABOUT_TL_URL
const ABOUT_TL_URL = 'https://www.trustedlogin.com/about/easy-and-safe/'
URL pointing to the "About TrustedLogin" page, shown below the Grant Access dialog.
Definition at line 30 of file Admin.php.
The documentation for this class was generated from the following file:
Admin.php