GravityView: GravityView_Plugin_Hooks_Gravity_Flow Class Reference
GravityView_Plugin_Hooks_Gravity_Flow Class Reference
Public Member Functions
add_hooks ()
Filter the values shown in GravityView frontend.
modify_search_bar_fields_dropdown ($fields, $form_id)
Get the list of active Workflow Steps and Workflow Step Statuses.
Public Member Functions inherited from GravityView_Plugin_and_Theme_Hooks
__construct ()
GravityView_Theme_Support constructor.
_wp_loaded ()
Fired when all themes and plugins have been loaded.
merge_content_meta_keys ($meta_keys=array(), $post_id=0)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_noconflict_scripts ($handles)
Merge plugin or theme scripts with existing no-conflict scripts.
merge_noconflict_styles ($handles)
Merge plugin or theme styles with existing no-conflict styles.
merge_post_type_support ($supports=array(), $is_hierarchical=false)
Merge plugin or theme post type support definitions with existing support values.
Static Public Member Functions
static get_status_options ($form_id=0, $status_key='workflow_final_status')
Get the available status choices from Gravity Flow.
Protected Attributes
$constant_name = 'GRAVITY_FLOW_VERSION'
Protected Attributes inherited from GravityView_Plugin_and_Theme_Hooks
$class_name = false
string Optional.
$constant_name = false
string Optional.
$content_meta_keys = array()
Define the keys to be parsed by the gravityview/data/parse/meta_keys hook.
$function_name = false
string Optional.
$post_type_support = array()
Define features in the admin editor used by the theme or plugin to be used when registering the GravityView post type.
$script_handles = array()
Define script handles used by the theme or plugin to be parsed by the gravityview/data/parse/meta_keys hook.
$style_handles = array()
Define style handles used by the theme or plugin to be parsed by the gravityview/data/parse/meta_keys hook.
Additional Inherited Members
Protected Member Functions inherited from GravityView_Plugin_and_Theme_Hooks
add_hooks ()
Add filters for meta key and script/style handles, if defined.
Detailed Description
Since
1.17
Definition at line 19 of file class-gravityview-plugin-hooks-gravity-flow.php.
Member Function Documentation
add_hooks()
add_hooks ()
Filter the values shown in GravityView frontend.
Since
1.17
Definition at line 32 of file class-gravityview-plugin-hooks-gravity-flow.php.
get_status_options()
static get_status_options ($form_id = 0, $status_key = 'workflow_final_status') static
Get the available status choices from Gravity Flow.
Gravity_Flow::get_entry_meta()
Since
1.17.3
Parameters
int $form_id
string $status_key By default, get all statuses
Returns
array
Definition at line 53 of file class-gravityview-plugin-hooks-gravity-flow.php.
References $form_id, and GravityView_View\getInstance().
Referenced by GravityView_Field_Workflow_Step\modify_frontend_search_fields(), and GravityView_Field_Workflow_Final_Status\modify_search_filters().
modify_search_bar_fields_dropdown()
modify_search_bar_fields_dropdown ($fields, $form_id)
Get the list of active Workflow Steps and Workflow Step Statuses.
Since
1.17.3
Gravity_Flow_API::get_current_step
Parameters
array $fields Array of searchable fields
int $form_id
Returns
array Updated Array of searchable fields
Definition at line 77 of file class-gravityview-plugin-hooks-gravity-flow.php.
References $form_id.
Field Documentation
$constant_name
$constant_name = 'GRAVITY_FLOW_VERSION' protected
Definition at line 24 of file class-gravityview-plugin-hooks-gravity-flow.php.
The documentation for this class was generated from the following file:
class-gravityview-plugin-hooks-gravity-flow.php