GravityView: IXR_Server Class Reference
IXR_Server Class Reference
Public Member Functions
__construct ($callbacks=false, $data=false, $wait=false)
PHP5 constructor.
call ($methodname, $args)
error ($error, $message=false)
getCapabilities ($args)
hasMethod ($method)
IXR_Server ($callbacks=false, $data=false, $wait=false)
PHP4 constructor.
listMethods ($args)
multiCall ($methodcalls)
output ($xml)
serve ($data=false)
setCallbacks ()
setCapabilities ()
Data Fields
$callbacks = array()
$capabilities
$data
$message
Detailed Description
Definition at line 414 of file class-IXR.php.
Constructor & Destructor Documentation
__construct ($callbacks = false, $data = false, $wait = false)
PHP5 constructor.
Definition at line 424 of file class-IXR.php.
References $callbacks, serve(), setCallbacks(), and setCapabilities().
Member Function Documentation
call ($methodname, $args)
Definition at line 498 of file class-IXR.php.
References hasMethod().
Referenced by multiCall(), and serve().
error ($error, $message = false)
Definition at line 537 of file class-IXR.php.
References output().
Referenced by wp_xmlrpc_server\blogger_deletePost(), wp_xmlrpc_server\blogger_getPost(), wp_xmlrpc_server\blogger_getRecentPosts(), wp_xmlrpc_server\login(), wp_xmlrpc_server\minimum_args(), wp_xmlrpc_server\mt_getPostCategories(), wp_xmlrpc_server\mt_getRecentPostTitles(), wp_xmlrpc_server\mt_publishPost(), wp_xmlrpc_server\mt_setPostCategories(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_newMediaObject(), serve(), wp_xmlrpc_server\wp_deleteCategory(), wp_xmlrpc_server\wp_deletePage(), wp_xmlrpc_server\wp_deletePost(), wp_xmlrpc_server\wp_deleteTerm(), wp_xmlrpc_server\wp_editPost(), wp_xmlrpc_server\wp_editTerm(), wp_xmlrpc_server\wp_getMediaItem(), wp_xmlrpc_server\wp_getOptions(), wp_xmlrpc_server\wp_getPages(), wp_xmlrpc_server\wp_getTerm(), wp_xmlrpc_server\wp_restoreRevision(), wp_xmlrpc_server\wp_setOptions(), and wp_xmlrpc_server\wp_suggestCategories().
getCapabilities ($args)
Definition at line 588 of file class-IXR.php.
References $capabilities.
hasMethod ($method)
Definition at line 564 of file class-IXR.php.
Referenced by call().
IXR_Server ($callbacks = false, $data = false, $wait = false)
PHP4 constructor.
Definition at line 439 of file class-IXR.php.
Referenced by wp_xmlrpc_server\serve_request().
listMethods ($args)
Definition at line 600 of file class-IXR.php.
multiCall ($methodcalls)
Definition at line 607 of file class-IXR.php.
References call().
output ($xml)
Definition at line 546 of file class-IXR.php.
References $charset, date, exit, and get_option().
Referenced by error(), and serve().
serve ($data = false)
Definition at line 443 of file class-IXR.php.
References $_SERVER, call(), error(), output(), and status_header().
Referenced by __construct().
setCallbacks ()
Definition at line 593 of file class-IXR.php.
Referenced by __construct().
setCapabilities ()
Definition at line 569 of file class-IXR.php.
Referenced by __construct().
Field Documentation
$callbacks = array()
Definition at line 417 of file class-IXR.php.
Referenced by __construct().
$capabilities
Definition at line 419 of file class-IXR.php.
Referenced by getCapabilities().
$data
Definition at line 416 of file class-IXR.php.
Referenced by wp_xmlrpc_server\_getOptions(), wp_xmlrpc_server\escape(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newMediaObject(), wp_xmlrpc_server\mw_newPost(), and wp_xmlrpc_server\wp_getPostFormats().
$message
Definition at line 418 of file class-IXR.php.
Referenced by wp_xmlrpc_server\pingback_error().
The documentation for this class was generated from the following file:
class-IXR.php