GravityView: getid3_id3v1 Class Reference
getid3_id3v1 Class Reference
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Public Member Functions
Analyze ()
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Static Public Member Functions
static ArrayOfGenres ($allowSCMPXextended=false)
static cutfield ($str)
static GenerateID3v1Tag ($title, $artist, $album, $year, $genreid, $comment, $track='')
static LookupGenreID ($genre, $allowSCMPXextended=false)
static LookupGenreName ($genreid, $allowSCMPXextended=true)
static StandardiseID3v1GenreName ($OriginalGenre)
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Definition at line 18 of file module.tag.id3v1.php.
Member Function Documentation
Analyze ()
Definition at line 21 of file module.tag.id3v1.php.
References $value, cutfield(), elseif, getid3_handler\fread(), getid3_handler\fseek(), GenerateID3v1Tag(), getid3_lib\intValueSupported(), LookupGenreID(), and LookupGenreName().
static ArrayOfGenres ($allowSCMPXextended = false) static
Definition at line 110 of file module.tag.id3v1.php.
static cutfield ($str) static
Definition at line 106 of file module.tag.id3v1.php.
Referenced by Analyze().
static GenerateID3v1Tag ($title, $artist, $album, $year, $genreid, $comment, $track = '') static
Definition at line 328 of file module.tag.id3v1.php.
References $comment, and $title.
Referenced by Analyze().
static LookupGenreID ($genre, $allowSCMPXextended = false) static
Definition at line 310 of file module.tag.id3v1.php.
References $value, and str_replace.
Referenced by Analyze().
static LookupGenreName ($genreid, $allowSCMPXextended = true) static
Definition at line 294 of file module.tag.id3v1.php.
Referenced by Analyze(), getid3_id3v2\ParseID3v2GenreString(), and getid3_quicktime\QuicktimeParseAtom().
static StandardiseID3v1GenreName ($OriginalGenre) static
Definition at line 321 of file module.tag.id3v1.php.
The documentation for this class was generated from the following file:
module.tag.id3v1.php