GravityView: WP_Roles Class Reference
WP_Roles Class Reference
Core class used to implement a user roles API.
Public Member Functions
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ()
Constructor.
add_cap ($role, $cap, $grant=true)
Add capability to role.
add_role ($role, $display_name, $capabilities=array())
Add role name with capabilities to list.
get_names ()
Retrieve list of role names.
get_role ($role)
Retrieve role object by name.
is_role ($role)
Whether role name is currently in the list of available roles.
reinit ()
Reinitialize the object.
remove_cap ($role, $cap)
Remove capability from role.
remove_role ($role)
Remove role by name.
Data Fields
$role_key
$role_names = array()
$role_objects = array()
$roles
$use_db = true
Protected Member Functions
_init ()
Set up the object properties.
Detailed Description
Core class used to implement a user roles API.
The role option is simple, the structure is organized by role name that store the name in value of the 'name' key. The capabilities are stored as an array in the value of the 'capability' key.
array (
    'rolename' => array (
        'name' => 'rolename',
        'capabilities' => array()
    )
)
Since
2.0.0
Definition at line 26 of file class-wp-roles.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Since
2.0.0
Definition at line 77 of file class-wp-roles.php.
References _init().
Member Function Documentation
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
Since
4.0.0 public
Parameters
callable $name Method to call.
array $arguments Arguments to pass when calling.
Returns
mixed|false Return value of the callback, false otherwise.
Definition at line 91 of file class-wp-roles.php.
References $name.
_init () protected
Set up the object properties.
The role key is set to the current prefix for the $wpdb object with 'user_roles' appended. If the $wp_user_roles global is set, then it will be used and the role option will not be updated or used.
Since
2.1.0 protected
wpdb $wpdb WordPress database abstraction object. array $wp_user_roles Used to set the 'roles' property value.
Definition at line 111 of file class-wp-roles.php.
References $wpdb, and get_option().
Referenced by __construct().
add_cap ($role, $cap, $grant = true)
Add capability to role.
Since
2.0.0 public
Parameters
string $role Role name.
string $cap Capability name.
bool $grant Optional, default is true. Whether role is capable of performing capability.
Definition at line 229 of file class-wp-roles.php.
References update_option().
add_role ($role, $display_name, $capabilities = array())
Add role name with capabilities to list.
Updates the list of roles, if the role doesn't already exist.
The capabilities are defined in the following format `array('read' => true);` To explicitly deny a role a capability you set the value for that capability to false.
Since
2.0.0 public
Parameters
string $role Role name.
string $display_name Role display name.
array $capabilities List of role capabilities in the above format.
Returns
WP_Role|void WP_Role object, if role is added.
Definition at line 180 of file class-wp-roles.php.
References update_option().
get_names ()
Retrieve list of role names.
Since
2.0.0 public
Returns
array List of role names.
Definition at line 280 of file class-wp-roles.php.
References $role_names.
get_role ($role)
Retrieve role object by name.
Since
2.0.0 public
Parameters
string $role Role name.
Returns
WP_Role|null WP_Role object if found, null if the role does not exist.
Definition at line 265 of file class-wp-roles.php.
References null.
is_role ($role)
Whether role name is currently in the list of available roles.
Since
2.0.0 public
Parameters
string $role Role name to look up.
Returns
bool
Definition at line 293 of file class-wp-roles.php.
reinit ()
Reinitialize the object.
Recreates the role objects. This is typically called only by switch_to_blog() after switching wpdb to a new blog ID.
Since
3.5.0 public
wpdb $wpdb WordPress database abstraction object.
Definition at line 143 of file class-wp-roles.php.
References $wpdb, and get_option().
remove_cap ($role, $cap)
Remove capability from role.
Since
2.0.0 public
Parameters
string $role Role name.
string $cap Capability name.
Definition at line 247 of file class-wp-roles.php.
References update_option().
remove_role ($role)
Remove role by name.
Since
2.0.0 public
Parameters
string $role Role name.
Definition at line 204 of file class-wp-roles.php.
References get_option(), and update_option().
Field Documentation
$role_key
Definition at line 61 of file class-wp-roles.php.
$role_names = array()
Definition at line 52 of file class-wp-roles.php.
Referenced by get_names().
$role_objects = array()
Definition at line 43 of file class-wp-roles.php.
$roles
Definition at line 34 of file class-wp-roles.php.
$use_db = true
Definition at line 70 of file class-wp-roles.php.
The documentation for this class was generated from the following file:
class-wp-roles.php