GravityView: GFForms Class Reference
GFForms Class Reference
Static Public Member Functions
static action_print_media_templates ()
static add_field ()
static add_form_button ()
static add_mce_popup ()
static add_security_files ()
static add_settings_page ($name, $handle= '', $icon_path= '')
static addons_page ()
static admin_bar ()
static ajax_parse_request ($wp)
static all_leads_page ()
static captcha_image ()
static change_input_type ()
static check_update ($update_plugins_option)
static check_upload_folder ()
static create_menu ()
static dashboard ()
static dashboard_dismiss_upgrade ()
static dashboard_setup ()
static dashboard_update_message ()
static dbdelta_fix_case ($cqueries)
static deactivation_hook ()
static delete_confirmation ()
static delete_custom_choice ()
static delete_field ()
static delete_file ()
static deprecate_add_on_methods ()
static display_changelog ()
static drop_index ($table, $index)
static duplicate_field ()
static enqueue_admin_scripts ($hook)
static enqueue_form_scripts ($form_id, $is_ajax=false)
static enqueue_scripts ()
static export_page ()
static form_list_page ()
static format_toolbar_menu_items ($menu_items, $compact=false)
static forms ()
static forms_page ($form_id)
static get ($name, $array=null)
static get_addon_info ($api, $action, $args)
static get_addon_nonces ()
static get_admin_icon_b64 ($color=false)
static get_changelog ()
static get_form ($form_id, $display_title=true, $display_description=true, $force_display=false, $field_values=null, $ajax=false, $tabindex=1)
static get_form_settings_sub_menu_items ($form_id)
static get_notification_post_category_values ()
static get_page ()
Gets current page name.
static get_parent_menu ($addon_menus)
static get_post_category_values ()
static get_shortcodes ()
static get_toolbar_menu_items ($form_id, $compact=false)
static get_view ($template)
static get_wp_option ($option_name)
static handle_ajax_do_shortcode ()
Shortcode UI.
static has_members_plugin ()
static help_page ()
static include_addon_framework ()
static include_feed_addon_framework ()
static include_gravity_api ()
static include_payment_addon_framework ()
static init ()
static is_auto_update_disabled ()
static is_gravity_ajax_action ()
static is_gravity_page ()
static load_first ()
static loaded ()
static maybe_auto_update ($update, $item)
static maybe_display_installation_wizard ()
Displays the installation wizard on single site installations and on multisite.
static maybe_process_form ()
static members_get_capabilities ($caps)
static modify_admin_title ($admin_title, $title)
static modify_tiny_mce_4 ($init)
static new_form ()
static no_conflict_mode_script ()
static no_conflict_mode_style ()
static page_supports_add_form_button ()
static parse_shortcode ($attributes, $content=null)
static plugin_row ($plugin_name)
static plugin_settings_link ($links, $file)
static post ($name, $do_stripslashes=true)
static premium_update ($premium_update)
static premium_update_push ($premium_update)
static print_form_scripts ($form, $ajax)
static process_exterior_pages ()
static refresh_field_preview ()
static register_scripts ()
static resend_notifications ()
static save_confirmation ()
static save_custom_choice ()
static save_form ()
static save_new_form ()
static select_export_form ()
static set_logging_supported ($plugins)
static settings_page ()
static setup ($force_setup=false)
static setup_database ()
static start_export ()
static toolbar_sub_menu_items ($menu_items, $compact=false)
static top_toolbar ()
static update_confirmation_active ()
static update_form_active ()
static update_lead_property ()
static update_lead_status ()
static update_notification_active ()
static update_page ()
static upgrade_license ()
static user_has_cap ($all_caps, $cap, $args)
static validate_upgrade ($do_upgrade, $hook_extra)
Static Public Attributes
static $version = '1.9.15'
Static Private Member Functions
static add_script_dependencies ($registered, $scripts)
static do_self_healing ()
static fix_checkbox_value ()
static fix_lead_meta_form_id_values ()
static fix_leading_and_trailing_spaces ()
static has_database_permission (&$error)
static heal_wp_upload_dir ()
static maybe_import_forms ()
static maybe_import_theme_forms ()
static maybe_populate_keys ()
static no_conflict_mode (&$wp_objects, $wp_required_objects, $gf_required_objects, $type= 'scripts')
static rename_suspicious_files_recursive ($dir, $flag_security_alert=false)
Renames files with a .bak extension if they have a file extension that is not allowed in the Gravity Forms uploads folder.
static toolbar_class ($item)
Detailed Description
Definition at line 115 of file gravityforms.php.
Member Function Documentation
static action_print_media_templates () static
Definition at line 3003 of file gravityforms.php.
References get_view().
static add_field () static
Definition at line 2378 of file gravityforms.php.
static add_form_button () static
Definition at line 1373 of file gravityforms.php.
References $version, esc_attr__(), esc_url, and get_bloginfo().
static add_mce_popup () static
Definition at line 1415 of file gravityforms.php.
static add_script_dependencies ($registered, $scripts) static private
Definition at line 938 of file gravityforms.php.
References $registered.
static add_security_files () static
Definition at line 622 of file gravityforms.php.
References GFFormsModel\get_upload_root().
Referenced by GFAsyncUpload\upload().
static add_settings_page ($name, $handle = '', $icon_path = '') static
Definition at line 1994 of file gravityforms.php.
References $name, and GFSettings\add_settings_page().
static addons_page () static
Definition at line 2019 of file gravityforms.php.
References $options, $plugin, $plugins, esc_html__(), get_bloginfo(), get_plugins(), is_plugin_active(), is_wp_error(), wp_nonce_url(), and wp_print_styles().
static admin_bar () static
Definition at line 2852 of file gravityforms.php.
References admin_url(), and esc_attr__().
static ajax_parse_request ($wp) static
Definition at line 1345 of file gravityforms.php.
References $description, $form_id, $title, absint(), and GFFormDisplay\get_form().
static all_leads_page () static
Fires when viewing entries of a certain form
Definition at line 2108 of file gravityforms.php.
References $form_id, GFEntryList\all_leads_page(), do_action(), and GFEntryDetail\lead_detail_page().
static captcha_image () static
Definition at line 2284 of file gravityforms.php.
References $field, $image, ABSPATH, GF_Fields\create(), and wp_stream_image().
static change_input_type () static
Definition at line 2393 of file gravityforms.php.
static check_update ($update_plugins_option) static
Definition at line 367 of file gravityforms.php.
static check_upload_folder () static
Definition at line 1112 of file gravityforms.php.
References GFFormsModel\get_upload_root().
static create_menu () static
Definition at line 1150 of file gravityforms.php.
References __, add_menu_page(), add_submenu_page(), apply_filters(), current_user_can(), esc_attr(), esc_html, and is_gravity_page().
static dashboard () static
Definition at line 1531 of file gravityforms.php.
References $form, $forms, absint(), endif, esc_html, esc_html__(), esc_html_e, GFFormsModel\get_form_summary(), is_multisite(), and is_super_admin().
static dashboard_dismiss_upgrade () static
Definition at line 1627 of file gravityforms.php.
References $ary, get_option(), and update_option().
static dashboard_setup () static
Definition at line 1525 of file gravityforms.php.
References __, apply_filters(), and wp_add_dashboard_widget().
static dashboard_update_message () static
Definition at line 1592 of file gravityforms.php.
References $message, esc_html__(), esc_html_e, and get_option().
static dbdelta_fix_case ($cqueries) static
Definition at line 829 of file gravityforms.php.
static deactivation_hook () static
Definition at line 299 of file gravityforms.php.
static delete_confirmation () static
Definition at line 2468 of file gravityforms.php.
References delete_confirmation().
static delete_custom_choice () static
Definition at line 2403 of file gravityforms.php.
static delete_field () static
Definition at line 2388 of file gravityforms.php.
static delete_file () static
Definition at line 2414 of file gravityforms.php.
References $field_id, and GFFormsModel\delete_file().
static deprecate_add_on_methods () static
Definition at line 2942 of file gravityforms.php.
References $deprecated, _deprecated_function(), DOING_AJAX, DOING_CRON, GFAddOn\get_all_deprecated_protected_methods(), and WP_INSTALLING.
static display_changelog () static
Definition at line 1482 of file gravityforms.php.
References exit.
static do_self_healing () static private
Definition at line 634 of file gravityforms.php.
References GFFormsModel\get_upload_root(), and update_option().
static drop_index ($table, $index) static
Definition at line 996 of file gravityforms.php.
References $wpdb, GFFormsModel\is_valid_index(), and GFFormsModel\is_valid_table().
Referenced by GFPaymentAddOn\upgrade_payment().
static duplicate_field () static
Definition at line 2383 of file gravityforms.php.
static enqueue_admin_scripts ($hook) static
A filter that allows the enabling (false) or disabling (true) of a shortcode preview of a form
Definition at line 1684 of file gravityforms.php.
References $page, apply_filters(), esc_html__(), get_page(), wp_enqueue_script(), wp_enqueue_style(), wp_is_mobile(), and wp_localize_script().
static enqueue_form_scripts ($form_id, $is_ajax = false) static
Definition at line 3156 of file gravityforms.php.
References $form, $form_id, GFFormDisplay\enqueue_form_scripts(), GFFormsModel\get_form_meta(), and GFAddOn\get_registered_addons().
Referenced by gravity_form_enqueue_scripts().
static enqueue_scripts () static
Definition at line 1969 of file gravityforms.php.
References GFFormDisplay\enqueue_scripts().
static export_page () static
Definition at line 2004 of file gravityforms.php.
References GFExport\export_page().
static fix_checkbox_value () static private
Definition at line 1058 of file gravityforms.php.
References $field, $form, $wpdb, GFFormsModel\get_field(), GFFormsModel\get_form_meta(), and GFFormsModel\get_lead_details_table_name().
static fix_lead_meta_form_id_values () static private
Definition at line 816 of file gravityforms.php.
References $wpdb, GFFormsModel\get_lead_meta_table_name(), and GFFormsModel\get_lead_table_name().
static fix_leading_and_trailing_spaces () static private
Definition at line 706 of file gravityforms.php.
References $form, $form_id, $wpdb, ARRAY_A, GFFormsModel\get_lead_details_long_table_name(), GFFormsModel\get_lead_details_table_name(), GFFormsModel\get_meta_table_name(), GFFormsModel\trim_conditional_logic_values(), GFFormsModel\trim_form_meta_values(), GFFormsModel\unserialize(), and GFFormsModel\update_form_meta().
static form_list_page () static
Definition at line 2134 of file gravityforms.php.
References GFFormList\form_list_page().
static format_toolbar_menu_items ($menu_items, $compact = false) static
A filter to allow the modification of the HTML link to delete a form
Parameters
string $link The HTML "Delete Form" Link
Definition at line 2608 of file gravityforms.php.
References $keys, $label, $link, $menu_items, $output, $title, $url, apply_filters(), elseif, esc_attr(), esc_html, esc_js(), and esc_url.
static forms () static
Definition at line 2139 of file gravityforms.php.
References $id, do_action(), GFFormSettings\form_settings_page(), get(), GFEntryDetail\lead_detail_page(), and GFEntryList\leads_page().
static forms_page ($form_id) static
Definition at line 1979 of file gravityforms.php.
References $form_id.
static get ($name, $array = null) static
Definition at line 2175 of file gravityforms.php.
References $name.
Referenced by GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GFEntryList\all_leads_page(), GVCommon\calculate_get_entries_criteria(), GFFormList\form_list_page(), forms(), GFFormsModel\get_current_page_url(), GF_Field_Name\get_field_input(), GFFormDisplay\get_form(), GF_Field\get_value_submission(), GravityView_Edit_Entry_Render\is_edit_entry(), and GravityView_Delete_Entry\process_delete().
static get_addon_info ($api, $action, $args) static
Definition at line 2053 of file gravityforms.php.
References $action, $plugin, and is_wp_error().
static get_addon_nonces () static
Definition at line 2076 of file gravityforms.php.
References is_wp_error().
static get_admin_icon_b64 ($color = false) static
Definition at line 1196 of file gravityforms.php.
static get_changelog () static
Definition at line 1493 of file gravityforms.php.
References $options, esc_html__(), get_bloginfo(), get_option(), and is_wp_error().
Referenced by GFUpdate\update_page().
static get_form ($form_id, $display_title = true, $display_description = true, $force_display = false, $field_values = null, $ajax = false, $tabindex = 1) static
Definition at line 1954 of file gravityforms.php.
References $form_id, and GFFormDisplay\get_form().
Referenced by gravity_form().
static get_form_settings_sub_menu_items ($form_id) static
Definition at line 2785 of file gravityforms.php.
References $form_id, $tabs, admin_url(), and get_tabs().
static get_notification_post_category_values () static
Definition at line 2103 of file gravityforms.php.
static get_page () static
Gets current page name.
Returns
bool|string Page name or false Page names:
new_form form_list form_editor form_settings confirmation notification_list notification_new notification_edit entry_list entry_detail entry_detail_edit settings addons export_entry export_form import_form updates
Definition at line 1881 of file gravityforms.php.
Referenced by GravityView_Admin_ApproveEntries\add_scripts_and_styles(), and GFLocking\is_page().
static get_parent_menu ($addon_menus) static
Definition at line 1212 of file gravityforms.php.
static get_post_category_values () static
Definition at line 2098 of file gravityforms.php.
static get_shortcodes () static
Filters through the shortcode builder actions (ajax, tabeindex, form title) for adding a new form to a post, page, etc.
Definition at line 3057 of file gravityforms.php.
References $form, $forms, __, absint(), apply_filters(), esc_html, and GFFormsModel\get_forms().
static get_toolbar_menu_items ($form_id, $compact = false) static
Definition at line 2689 of file gravityforms.php.
References $form_id, $menu_items, __, absint(), site_url(), and trailingslashit().
static get_view ($template) static
Definition at line 3008 of file gravityforms.php.
References $template.
Referenced by action_print_media_templates().
static get_wp_option ($option_name) static
Definition at line 809 of file gravityforms.php.
References $wpdb.
Referenced by GFAddOn\setup().
static handle_ajax_do_shortcode () static
Shortcode UI.
Output a shortcode. ajax callback for displaying the shortcode in the TinyMCE editor.
Returns
null
Definition at line 2964 of file gravityforms.php.
References $form_id, $post, $post_id, current_user_can(), do_shortcode(), esc_html__(), exit, get_post(), image, null, sanitize_text_field(), setup_postdata(), wp_print_scripts(), and wp_print_styles().
static has_database_permission (& $error) static private
Definition at line 1026 of file gravityforms.php.
References $wpdb.
Referenced by validate_upgrade().
static has_members_plugin () static
Definition at line 132 of file gravityforms.php.
static heal_wp_upload_dir () static private
Definition at line 682 of file gravityforms.php.
References wp_upload_dir().
static help_page () static
Definition at line 1999 of file gravityforms.php.
References GFHelp\help_page().
static include_addon_framework () static
Definition at line 1326 of file gravityforms.php.
static include_feed_addon_framework () static
Definition at line 1330 of file gravityforms.php.
static include_gravity_api () static
Definition at line 1338 of file gravityforms.php.
Referenced by GFSettings\action_delete_option_rg_gforms_key(), GFSettings\filter_pre_update_option_rg_gforms_key(), and GFSettings\settings_uninstall_page().
static include_payment_addon_framework () static
Definition at line 1334 of file gravityforms.php.
static init () static
Definition at line 137 of file gravityforms.php.
References $current_user, add_action(), add_filter(), add_shortcode(), DOING_AJAX, GF_SUPPORTED_WP_VERSION, is_multisite(), GFExport\maybe_export(), and WP_DEBUG.
static is_auto_update_disabled () static
Filter to disable Gravity Forms Automatic updates
Parameters
bool $enabled Check if automatic updates are enabled, and then disable it
Definition at line 2898 of file gravityforms.php.
References apply_filters(), and get_option().
static is_gravity_ajax_action () static
Definition at line 1120 of file gravityforms.php.
References DOING_AJAX.
static is_gravity_page () static
Definition at line 1140 of file gravityforms.php.
Referenced by create_menu(), and GravityView_Admin\include_required_files().
static load_first () static
Definition at line 288 of file gravityforms.php.
References get_option(), and update_option().
static loaded () static
Fires when Gravity Forms has loaded. When developing Add-Ons, use this hook to initialize any functionality that depends on Gravity Forms functionality
Definition at line 119 of file gravityforms.php.
References do_action(), and GFAddOn\init_addons().
static maybe_auto_update ($update, $item) static
Definition at line 2869 of file gravityforms.php.
References $update, and $version.
static maybe_display_installation_wizard () static
Displays the installation wizard on single site installations and on multisite.
Returns
bool Was the installation wizard displayed?
Definition at line 3172 of file gravityforms.php.
References GF_Installation_Wizard\display(), get_option(), is_main_site(), and is_multisite().
static maybe_import_forms () static private
Definition at line 748 of file gravityforms.php.
References get_option(), GFExport\import_file(), and update_option().
static maybe_import_theme_forms () static private
Definition at line 759 of file gravityforms.php.
References $theme, get_option(), get_stylesheet_directory(), get_template(), GFExport\import_file(), and update_option().
static maybe_populate_keys () static private
Definition at line 785 of file gravityforms.php.
References $gf_license_key, $gf_recaptcha_private_key, $gf_recaptcha_public_key, GFFormsModel\save_key(), and update_option().
static maybe_process_form () static
Definition at line 309 of file gravityforms.php.
References $form_id, absint(), elseif, GFFormsModel\get_form(), GFFormDisplay\process_form(), and GFFormDisplay\process_send_resume_link().
static members_get_capabilities ($caps) static
Definition at line 1107 of file gravityforms.php.
static modify_admin_title ($admin_title, $title) static
Definition at line 1242 of file gravityforms.php.
References $admin_title, $form_id, __, esc_html, and get_tabs().
static modify_tiny_mce_4 ($init) static
Definition at line 3026 of file gravityforms.php.
References $base_url, $min, and elseif.
static new_form () static
Definition at line 1960 of file gravityforms.php.
static no_conflict_mode (& $wp_objects, $wp_required_objects, $gf_required_objects, $type = 'scripts') static private
Definition at line 890 of file gravityforms.php.
References $registered, and apply_filters().
static no_conflict_mode_script () static
Definition at line 868 of file gravityforms.php.
References $wp_scripts, and get_option().
static no_conflict_mode_style () static
Definition at line 846 of file gravityforms.php.
References $wp_styles, and get_option().
static page_supports_add_form_button () static
Definition at line 1364 of file gravityforms.php.
References apply_filters().
static parse_shortcode ($attributes, $content = null) static
Definition at line 1270 of file gravityforms.php.
References $action, $attributes, $content, $description, $id, $name, $title, apply_filters(), shortcode_atts(), str_replace, and stripslashes_deep().
static plugin_row ($plugin_name) static
Definition at line 1467 of file gravityforms.php.
References admin_url(), and esc_html__().
static plugin_settings_link ($links, $file) static
Definition at line 1456 of file gravityforms.php.
References $file, admin_url(), esc_html__(), esc_url, and plugin_basename().
static post ($name, $do_stripslashes = true) static
Definition at line 2187 of file gravityforms.php.
References $name, and stripslashes_deep().
Referenced by GFFormList\form_list_page(), GFFormDisplay\get_source_page(), GFFormDisplay\get_target_page(), GravityView_Edit_Entry_Render\is_edit_entry(), GFFormDisplay\is_last_page(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GravityView_Admin_ApproveEntries\process_bulk_action(), GFFormDisplay\process_form(), GravityView_Edit_Entry_Render\process_save_process_files(), and GravityView_Edit_Entry_Render\validate().
static premium_update ($premium_update) static
Definition at line 977 of file gravityforms.php.
References $update, ABSPATH, and get_plugin_data().
static premium_update_push ($premium_update) static
Definition at line 958 of file gravityforms.php.
References $update, ABSPATH, and get_plugin_data().
static print_form_scripts ($form, $ajax) static
Definition at line 1974 of file gravityforms.php.
References $form, and GFFormDisplay\print_form_scripts().
static process_exterior_pages () static
Definition at line 326 of file gravityforms.php.
References $_SERVER, $page, _doing_it_wrong(), DOING_AJAX, and exit.
static refresh_field_preview () static
Definition at line 2398 of file gravityforms.php.
static register_scripts () static
Definition at line 1641 of file gravityforms.php.
References $base_url, $min, $version, esc_html__(), includes_url(), wp_localize_script(), wp_register_script(), and wp_register_style().
Referenced by GravityView_Admin_Views\enqueue_gravity_forms_scripts().
static rename_suspicious_files_recursive ($dir, $flag_security_alert = false) static private
Renames files with a .bak extension if they have a file extension that is not allowed in the Gravity Forms uploads folder.
Definition at line 653 of file gravityforms.php.
References $dir, $file, and elseif.
static resend_notifications () static
Definition at line 2197 of file gravityforms.php.
References $form, $form_id, $leads, _e, absint(), esc_html__(), GFFormsModel\get_form_meta(), GFFormsModel\get_lead(), null, and GFFormsModel\search_lead_ids().
static save_confirmation () static
Definition at line 2463 of file gravityforms.php.
static save_custom_choice () static
Definition at line 2408 of file gravityforms.php.
static save_form () static
Definition at line 2373 of file gravityforms.php.
static save_new_form () static
Definition at line 2474 of file gravityforms.php.
References save_new_form().
static select_export_form () static
Filters through the Form Export Page
Parameters
int $form_id The ID of the form to export
int $form The Form Object of the form to export
Definition at line 2425 of file gravityforms.php.
References $field, $form, $form_id, GFExport\add_default_export_fields(), and GFFormsModel\get_form_meta().
static set_logging_supported ($plugins) static
Definition at line 303 of file gravityforms.php.
References $plugins.
static settings_page () static
Definition at line 1984 of file gravityforms.php.
References GFSettings\settings_page().
static setup ($force_setup = false) static
Definition at line 376 of file gravityforms.php.
References $blog_id, delete_transient(), get_current_blog_id(), get_option(), and update_option().
Referenced by GV_Unit_Tests_Bootstrap\load().
static setup_database () static
Definition at line 430 of file gravityforms.php.
References $charset_collate, $wpdb, ABSPATH, add_filter(), dbDelta(), drop_index(), GFFormsModel\get_form_table_name(), GFFormsModel\get_form_view_table_name(), GFFormsModel\get_incomplete_submissions_table_name(), GFFormsModel\get_lead_details_long_table_name(), GFFormsModel\get_lead_details_table_name(), GFFormsModel\get_lead_meta_table_name(), GFFormsModel\get_lead_notes_table_name(), GFFormsModel\get_lead_table_name(), GFFormsModel\get_meta_table_name(), get_option(), GFORMS_MAX_FIELD_LENGTH, and remove_filter().
Referenced by GFFormsModel\ensure_tables_exist(), and GV_UnitTestCase\setUp().
static start_export () static
Definition at line 2093 of file gravityforms.php.
References GFExport\start_export().
static toolbar_class ($item) static private
Definition at line 2808 of file gravityforms.php.
static toolbar_sub_menu_items ($menu_items, $compact = false) static
Definition at line 2760 of file gravityforms.php.
References $label, $menu_items, $url, esc_attr(), esc_html, and esc_url.
static top_toolbar () static
Definition at line 2479 of file gravityforms.php.
References $forms, $id, $menu_items, apply_filters(), esc_html, esc_html_e, GFFormsModel\get_forms(), label, li, name, null, and RG_CURRENT_VIEW.
Referenced by GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), and page_header().
static update_confirmation_active () static
Definition at line 2313 of file gravityforms.php.
References GFFormsModel\update_confirmation_active().
static update_form_active () static
Definition at line 2303 of file gravityforms.php.
References GFFormsModel\update_form_active().
static update_lead_property () static
Definition at line 2318 of file gravityforms.php.
References GFFormsModel\update_lead_property().
static update_lead_status () static
Definition at line 2323 of file gravityforms.php.
References $form, $id, GFFormsModel\delete_lead(), GFAPI\get_entry(), GFEntryList\get_filter_links(), GFAPI\get_form(), and GFFormsModel\update_lead_property().
static update_notification_active () static
Definition at line 2308 of file gravityforms.php.
References GFFormsModel\update_notification_active().
static update_page () static
Definition at line 2014 of file gravityforms.php.
References GFUpdate\update_page().
static upgrade_license () static
Definition at line 2367 of file gravityforms.php.
References GFSettings\upgrade_license().
static user_has_cap ($all_caps, $cap, $args) static
Definition at line 1075 of file gravityforms.php.
References $capability, current_user_can(), and is_super_admin().
static validate_upgrade ($do_upgrade, $hook_extra) static
Definition at line 1017 of file gravityforms.php.
References has_database_permission().
Field Documentation
$version = '1.9.15' static
Definition at line 117 of file gravityforms.php.
Referenced by GravityView_Support_Port\_localize_script(), add_form_button(), maybe_auto_update(), GFExport\maybe_export(), register_scripts(), and GFFormsModel\sanitize_settings().
The documentation for this class was generated from the following file:
gravityforms.php