GravityView: WP_MatchesMapRegex Class Reference
WP_MatchesMapRegex Class Reference
Helper class to remove the need to use eval to replace $matches[] in query strings.
Public Member Functions
__construct ($subject, $matches)
constructor
callback ($matches)
preg_replace_callback hook
Static Public Member Functions
static apply ($subject, $matches)
Substitute substring matches in subject.
Data Fields
$_pattern = '(\$matches\[[1-9]+[0-9]*\])'
$output
Private Member Functions
_map ()
do the actual mapping
Private Attributes
$_matches
$_subject
Detailed Description
Helper class to remove the need to use eval to replace $matches[] in query strings.
Since
2.9.0
Definition at line 712 of file class-wp.php.
Constructor & Destructor Documentation
__construct ($subject, $matches)
constructor
Parameters
string $subject subject if regex
array $matches data to use in map
Definition at line 750 of file class-wp.php.
References _map(), and output().
Member Function Documentation
_map () private
do the actual mapping
private
Returns
string
Definition at line 779 of file class-wp.php.
Referenced by __construct().
static apply ($subject, $matches) static
Substitute substring matches in subject.
static helper function to ease use
public
Parameters
string $subject subject
array $matches data used for substitution
Returns
string
Definition at line 768 of file class-wp.php.
Referenced by WP\parse_request(), and url_to_postid().
callback ($matches)
preg_replace_callback hook
public
Parameters
array $matches preg_replace regexp matches
Returns
string
Definition at line 791 of file class-wp.php.
Field Documentation
$_matches private
Definition at line 719 of file class-wp.php.
$_pattern = '(\$matches\[[1-9]+[0-9]*\])'
Definition at line 742 of file class-wp.php.
$_subject private
Definition at line 735 of file class-wp.php.
$output
Definition at line 727 of file class-wp.php.
The documentation for this class was generated from the following file:
class-wp.php