GravityView: WP_Customize_Nav_Menu_Item_Setting Class Reference
WP_Customize_Nav_Menu_Item_Setting Class Reference
Customize Setting to represent a nav_menu.
Public Member Functions
__construct (WP_Customize_Manager $manager, $id, array $args=array())
Constructor.
amend_customize_save_response ($data)
Export data for the JS client.
filter_wp_get_nav_menu_items ($items, $menu, $args)
Filter the wp_get_nav_menu_items() result to supply the previewed menu items.
flush_cached_value ($menu_id, $menu_item_id)
Clear the cached value when this nav menu item is updated.
preview ()
Handle previewing the setting.
sanitize ($menu_item_value)
Sanitize an input.
value ()
Get the instance data for a given nav_menu_item setting.
value_as_wp_post_nav_menu_item ()
Get the value emulated into a WP_Post and set up as a nav_menu_item.
Public Member Functions inherited from WP_Customize_Setting
__construct ($manager, $id, $args=array())
Constructor.
_clear_aggregated_multidimensional_preview_applied_flag ()
Clear out the previewed-applied flag for a multidimensional-aggregated value whenever its post value is updated.
_multidimensional_preview_filter ($original)
Callback function to filter multidimensional theme mods and options.
_preview_filter ($original)
Callback function to filter non-multidimensional theme mods and options.
check_capabilities ()
Validate user capabilities whether the theme supports the setting.
id_data ()
Get parsed ID data for multidimensional setting.
is_current_blog_previewed ()
Return true if the current blog is not the same as the previewed blog.
js_value ()
Sanitize the setting's value for use in JavaScript.
post_value ($default=null)
Fetch and sanitize the $_POST value for the setting.
preview ()
Add filters to supply the setting's value when accessed.
sanitize ($value)
Sanitize an input.
save ()
Check user capabilities and theme supports, and then save the value of the setting.
value ()
Fetch the value of the setting.
Static Public Member Functions
static sort_wp_get_nav_menu_items ($items, $menu, $args)
Re-apply the tail logic also applied on $items by wp_get_nav_menu_items().
Data Fields
$default
$original_nav_menu_term_id
$post_id
$previous_post_id
$transport = 'postMessage'
$type = self::TYPE
$update_error
$update_status
const ID_PATTERN = '/^nav_menu_item\[(?P<id>-?\d+)\]$/'
const POST_TYPE = 'nav_menu_item'
const TYPE = 'nav_menu_item'
Data Fields inherited from WP_Customize_Setting
$capability = 'edit_theme_options'
$default = ''
$dirty = false
$id
$manager
$sanitize_callback = ''
$sanitize_js_callback = ''
$theme_supports = ''
$transport = 'refresh'
$type = 'theme_mod'
Protected Member Functions
populate_value ()
Ensure that the value is fully populated with the necessary properties.
update ($value)
Create/update the nav_menu_item post for this setting.
Protected Member Functions inherited from WP_Customize_Setting
_update_option ()
Deprecated method.
_update_theme_mod ()
Deprecated method.
aggregate_multidimensional ()
Set up the setting for aggregated multidimensional values.
get_root_value ($default=null)
Get the root value for a setting, especially for multidimensional ones.
multidimensional (&$root, $keys, $create=false)
Multidimensional helper function.
multidimensional_get ($root, $keys, $default=null)
Will attempt to fetch a specific value from a multidimensional array.
multidimensional_isset ($root, $keys)
Will attempt to check if a specific value in a multidimensional array is set.
multidimensional_replace ($root, $keys, $value)
Will attempt to replace a specific value in a multidimensional array.
set_root_value ($value)
Set the root value for a setting, especially for multidimensional ones.
update ($value)
Save the value of the setting, using the related API.
Protected Attributes
$is_updated = false
$value
Protected Attributes inherited from WP_Customize_Setting
$_original_value
$_previewed_blog_id
$id_data = array()
$is_multidimensional_aggregated = false
$is_previewed = false
Additional Inherited Members
Static Protected Attributes inherited from WP_Customize_Setting
static $aggregated_multidimensionals = array()
Detailed Description
Customize Setting to represent a nav_menu.
Subclass of WP_Customize_Setting to represent a nav_menu taxonomy term, and the IDs for the nav_menu_items associated with the nav menu.
Since
4.3.0
See also
WP_Customize_Setting
Definition at line 20 of file class-wp-customize-nav-menu-item-setting.php.
Constructor & Destructor Documentation
__construct (WP_Customize_Manager $manager, $id, array $args = array())
Constructor.
Any supplied $args override class property defaults.
Since
4.3.0 public
Parameters
WP_Customize_Manager $manager Bootstrap Customizer instance.
string $id An specific ID of the setting. Can be a theme mod or option name.
array $args Optional. Setting arguments.
Exceptions
Exception If $id is not valid for this setting type.
Definition at line 173 of file class-wp-customize-nav-menu-item-setting.php.
References WP_Customize_Setting\$id, add_action(), populate_value(), and value().
Member Function Documentation
amend_customize_save_response ($data)
Export data for the JS client.
Since
4.3.0 public
See also
WP_Customize_Nav_Menu_Item_Setting::update()
Parameters
array $data Additional information passed back to the 'saved' event on wp.customize.
Returns
array Save response data.
Definition at line 808 of file class-wp-customize-nav-menu-item-setting.php.
References null.
filter_wp_get_nav_menu_items ($items, $menu, $args)
Filter the wp_get_nav_menu_items() result to supply the previewed menu items.
Since
4.3.0 public
See also
wp_get_nav_menu_items()
Parameters
array $items An array of menu item post objects.
object $menu The menu object.
array $args An array of arguments used to retrieve menu item objects.
Returns
array Array of menu items,
Definition at line 418 of file class-wp-customize-nav-menu-item-setting.php.
References $menu, $original_nav_menu_term_id, $value, value(), and value_as_wp_post_nav_menu_item().
flush_cached_value ($menu_id, $menu_item_id)
Clear the cached value when this nav menu item is updated.
Since
4.3.0 public
Parameters
int $menu_id The term ID for the menu.
int $menu_item_id The post ID for the menu item.
Definition at line 206 of file class-wp-customize-nav-menu-item-setting.php.
References null, and value().
populate_value () protected
Ensure that the value is fully populated with the necessary properties.
Translates some properties added by wp_setup_nav_menu_item() and removes others.
Since
4.3.0 protected
See also
WP_Customize_Nav_Menu_Item_Setting::value()
Definition at line 269 of file class-wp-customize-nav-menu-item-setting.php.
References elseif, get_bloginfo(), get_term_field(), get_the_title(), is_wp_error(), post_type_exists(), WP_Customize_Nav_Menu_Setting\TAXONOMY, taxonomy_exists(), value(), and wp_get_post_terms().
Referenced by __construct(), and value().
preview ()
Handle previewing the setting.
Since
4.3.0
4.4.0 Added boolean return value. public
See also
WP_Customize_Manager::post_value()
Returns
bool False if method short-circuited due to no-op.
Definition at line 376 of file class-wp-customize-nav-menu-item-setting.php.
References add_filter(), get_current_blog_id(), has_filter(), WP_Customize_Setting\post_value(), and value().
sanitize ($menu_item_value)
Sanitize an input.
Note that parent::sanitize() erroneously does wp_unslash() on $value, but we remove that in this override.
Since
4.3.0 public
Parameters
array $menu_item_value The value to sanitize.
Returns
array|false|null Null if an input isn't valid. False if it is marked for deletion. Otherwise the sanitized value.
This filter is documented in wp-includes/class-wp-customize-setting.php
Definition at line 588 of file class-wp-customize-nav-menu-item-setting.php.
References $default, $value, apply_filters(), esc_url_raw(), null, sanitize_key(), sanitize_text_field(), and wp_array_slice_assoc().
static sort_wp_get_nav_menu_items ($items, $menu, $args) static
Re-apply the tail logic also applied on $items by wp_get_nav_menu_items().
Since
4.3.0 public
See also
wp_get_nav_menu_items()
Parameters
array $items An array of menu item post objects.
object $menu The menu object.
array $args An array of arguments used to retrieve menu item objects.
Returns
array Array of menu items,
Definition at line 493 of file class-wp-customize-nav-menu-item-setting.php.
References $GLOBALS, $i, ARRAY_A, and is_admin().
update ($value) protected
Create/update the nav_menu_item post for this setting.
Any created menu items will have their assigned post IDs exported to the client via the customize_save_response filter. Likewise, any errors will be exported to the client via the customize_save_response() filter.
To delete a menu, the client can send false as the value.
Since
4.3.0 protected
See also
wp_update_nav_menu_item()
Parameters
array | false $value The menu item array to update. If false, then the menu item will be deleted entirely. See WP_Customize_Nav_Menu_Item_Setting::$default for what the value should consist of.
Returns
null|void
Definition at line 675 of file class-wp-customize-nav-menu-item-setting.php.
References $post_id, $value, add_filter(), is_wp_error(), wp_delete_post(), and wp_update_nav_menu_item().
value ()
Get the instance data for a given nav_menu_item setting.
Since
4.3.0 public
See also
wp_setup_nav_menu_item()
Returns
array|false Instance data array, or false if the item is marked for deletion.
Definition at line 223 of file class-wp-customize-nav-menu-item-setting.php.
References WP_Customize_Setting\$_original_value, $default, $post, $value, get_current_blog_id(), get_post(), populate_value(), WP_Customize_Setting\post_value(), and wp_setup_nav_menu_item().
Referenced by __construct(), filter_wp_get_nav_menu_items(), flush_cached_value(), populate_value(), and preview().
value_as_wp_post_nav_menu_item ()
Get the value emulated into a WP_Post and set up as a nav_menu_item.
Since
4.3.0 public
Returns
WP_Post With wp_setup_nav_menu_item() applied.
This filter is documented in wp-includes/nav-menu.php
This filter is documented in wp-includes/nav-menu.php
Definition at line 523 of file class-wp-customize-nav-menu-item-setting.php.
References $post, $post_id, __, apply_filters(), elseif, get_current_user_id(), get_post_type_object(), get_taxonomy(), object, and wp_trim_words().
Referenced by filter_wp_get_nav_menu_items().
Field Documentation
$default
Initial value:
= array(
        'object_id'        => 0,
        'object'           => '',
        'menu_item_parent' => 0,
        'position'         => 0,
        'type'             => 'custom',
        'title'            => '',
        'url'              => '',
        'target'           => '',
        'attr_title'       => '',
        'description'      => '',
        'classes'          => '',
        'xfn'              => '',
        'status'           => 'publish',
        'original_title'   => '',
        'nav_menu_term_id' => 0,
        '_invalid'         => false,
    )
Definition at line 46 of file class-wp-customize-nav-menu-item-setting.php.
Referenced by value().
$is_updated = false protected
Definition at line 129 of file class-wp-customize-nav-menu-item-setting.php.
$original_nav_menu_term_id
Definition at line 120 of file class-wp-customize-nav-menu-item-setting.php.
Referenced by filter_wp_get_nav_menu_items().
$post_id
Definition at line 84 of file class-wp-customize-nav-menu-item-setting.php.
$previous_post_id
Definition at line 110 of file class-wp-customize-nav-menu-item-setting.php.
$transport = 'postMessage'
Definition at line 73 of file class-wp-customize-nav-menu-item-setting.php.
$type = self::TYPE
Definition at line 35 of file class-wp-customize-nav-menu-item-setting.php.
$update_error
Definition at line 156 of file class-wp-customize-nav-menu-item-setting.php.
$update_status
Definition at line 144 of file class-wp-customize-nav-menu-item-setting.php.
$value protected
Definition at line 93 of file class-wp-customize-nav-menu-item-setting.php.
Referenced by filter_wp_get_nav_menu_items(), and value().
const ID_PATTERN = '/^nav_menu_item\[(?P<id>-?\d+)\]$/'
Definition at line 22 of file class-wp-customize-nav-menu-item-setting.php.
Referenced by WP_Customize_Nav_Menus\filter_dynamic_setting_args().
const POST_TYPE = 'nav_menu_item'
Definition at line 24 of file class-wp-customize-nav-menu-item-setting.php.
const TYPE = 'nav_menu_item'
Definition at line 26 of file class-wp-customize-nav-menu-item-setting.php.
Referenced by WP_Customize_Nav_Menus\filter_dynamic_setting_args(), and WP_Customize_Nav_Menus\filter_dynamic_setting_class().
The documentation for this class was generated from the following file:
class-wp-customize-nav-menu-item-setting.php