GravityView: WP_Locale Class Reference
WP_Locale Class Reference
Class that loads the calendar locale.
Public Member Functions
__construct ()
Constructor which calls helper methods to set up object variables.
_strings_for_pot ()
Register date/time format strings for general POT.
get_meridiem ($meridiem)
Retrieve translated version of meridiem string.
get_month ($month_number)
Retrieve the full translated month by month number.
get_month_abbrev ($month_name)
Retrieve translated version of month abbreviation string.
get_weekday ($weekday_number)
Retrieve the full translated weekday word.
get_weekday_abbrev ($weekday_name)
Retrieve the translated weekday abbreviation.
get_weekday_initial ($weekday_name)
Retrieve the translated weekday initial.
init ()
Sets up the translated strings and object properties.
is_rtl ()
Checks if current locale is RTL.
register_globals ()
Global variables are deprecated.
rtl_src_admin_notice ()
Outputs an admin notice if the /build directory must be used for RTL.
Data Fields
$meridiem
$month
$month_abbrev
$number_format
$start_of_week
$text_direction = 'ltr'
$weekday
$weekday_abbrev
$weekday_initial
Detailed Description
Class that loads the calendar locale.
Since
2.1.0
Definition at line 14 of file locale.php.
Constructor & Destructor Documentation
__construct ()
Constructor which calls helper methods to set up object variables.
Since
2.1.0
Definition at line 361 of file locale.php.
References init(), and register_globals().
Member Function Documentation
_strings_for_pot ()
Register date/time format strings for general POT.
Private, unused method to add some date/time formats translated on wp-admin/options-general.php to the general POT that would otherwise be added to the admin POT.
Since
3.6.0
Definition at line 385 of file locale.php.
References __.
get_meridiem ($meridiem)
Retrieve translated version of meridiem string.
The $meridiem parameter is expected to not be translated.
Since
2.1.0 public
Parameters
string $meridiem Either 'am', 'pm', 'AM', or 'PM'. Not translated version.
Returns
string Translated version
Definition at line 330 of file locale.php.
References $meridiem.
get_month ($month_number)
Retrieve the full translated month by month number.
The $month_number parameter has to be a string because it must have the '0' in front of any number that is less than 10. Starts from '01' and ends at '12'.
You can use an integer instead and it will add the '0' before the numbers less than 10 for you.
Since
2.1.0 public
Parameters
string | int $month_number '01' through '12'
Returns
string Translated full month name
Definition at line 299 of file locale.php.
References month, and zeroise().
get_month_abbrev ($month_name)
Retrieve translated version of month abbreviation string.
The $month_name parameter is expected to be the translated or translatable version of the month.
Since
2.1.0 public
Parameters
string $month_name Translated month to get abbreviated version
Returns
string Translated abbreviated month
Definition at line 315 of file locale.php.
get_weekday ($weekday_number)
Retrieve the full translated weekday word.
Week starts on translated Sunday and can be fetched by using 0 (zero). So the week starts with 0 (zero) and ends on Saturday with is fetched by using 6 (six).
Since
2.1.0 public
Parameters
int $weekday_number 0 for Sunday through 6 Saturday
Returns
string Full translated weekday
Definition at line 244 of file locale.php.
get_weekday_abbrev ($weekday_name)
Retrieve the translated weekday abbreviation.
The weekday abbreviation is retrieved by the translated full weekday word.
Since
2.1.0 public
Parameters
string $weekday_name Full translated weekday word
Returns
string Translated weekday abbreviation
Definition at line 278 of file locale.php.
get_weekday_initial ($weekday_name)
Retrieve the translated weekday initial.
The weekday initial is retrieved by the translated full weekday word. When translating the weekday initial pay attention to make sure that the starting letter does not conflict.
Since
2.1.0 public
Parameters
string $weekday_name
Returns
string
Definition at line 262 of file locale.php.
init ()
Sets up the translated strings and object properties.
The method creates the translatable strings for various calendar elements. Which allows for specifying locale specific calendar names and text direction.
Since
2.1.0 private
string $text_direction string $wp_version
Definition at line 110 of file locale.php.
References $GLOBALS, __, _x, add_action(), elseif, month, and str_replace.
Referenced by __construct().
is_rtl ()
Checks if current locale is RTL.
Since
3.0.0
Returns
bool Whether locale is RTL.
Definition at line 372 of file locale.php.
References $text_direction.
register_globals ()
Global variables are deprecated.
For backwards compatibility only.
array $weekday array $weekday_initial array $weekday_abbrev array $month array $month_abbrev
Since
2.1.0
Definition at line 348 of file locale.php.
References $GLOBALS, $month, $month_abbrev, $weekday, $weekday_abbrev, and $weekday_initial.
Referenced by __construct().
rtl_src_admin_notice ()
Outputs an admin notice if the /build directory must be used for RTL.
Since
3.8.0 public
Definition at line 226 of file locale.php.
References __.
Field Documentation
$meridiem
Definition at line 76 of file locale.php.
Referenced by get_meridiem().
$month
Definition at line 58 of file locale.php.
Referenced by register_globals().
$month_abbrev
Definition at line 66 of file locale.php.
Referenced by register_globals().
$number_format
Definition at line 95 of file locale.php.
$start_of_week
Definition at line 50 of file locale.php.
$text_direction = 'ltr'
Definition at line 86 of file locale.php.
Referenced by is_rtl().
$weekday
Definition at line 21 of file locale.php.
Referenced by register_globals().
$weekday_abbrev
Definition at line 42 of file locale.php.
Referenced by register_globals().
$weekday_initial
Definition at line 34 of file locale.php.
Referenced by register_globals().
The documentation for this class was generated from the following file:
locale.php