GravityView: Endpoint Class Reference
Endpoint Class Reference
Public Member Functions
__construct (Config $config, Logging $logging)
Logger constructor.
add ()
Hooked Action: Add a unique endpoint to WP if a support agent exists.
delete ()
generate_secret_id ($site_identifier_hash, $endpoint_hash='')
Generate the secret_id parameter as a hash of the endpoint with the identifier.
get ()
Get the site option value at {.
get_hash ($site_identifier_hash)
Generate the endpoint parameter as a hash of the site URL with the identifier.
init ()
maybe_login_support ()
Check if the endpoint is hit and has a valid identifier before automatically logging in support agent.
maybe_revoke_support ()
Hooked Action to maybe revoke support if $_REQUEST[ SupportUser::ID_QUERY_PARAM ] == {namespace} Can optionally check for $_REQUEST[ SupportUser::ID_QUERY_PARAM ] for revoking a specific user by their identifier.
update ($endpoint)
Updates the site's endpoint to listen for logins.
Data Fields
const PERMALINK_FLUSH_OPTION_NAME = 'tl_permalinks_flushed'
const POST_ACTION_KEY = 'action'
const POST_ACTION_VALUE = 'trustedlogin'
const POST_ENDPOINT_KEY = 'endpoint'
const POST_IDENTIFIER_KEY = 'identifier'
const REVOKE_SUPPORT_QUERY_PARAM = 'revoke-tl'
Private Member Functions
get_trustedlogin_request ()
Returns sanitized data from a TrustedLogin login $_POST request.
Private Attributes
$config
$logging
$option_name
$support_user
Detailed Description
Definition at line 21 of file Endpoint.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Logging $logging)
Logger constructor.
Filter: Set endpoint setting name
Since
1.0.0
Parameters
string
Config $config
Definition at line 74 of file Endpoint.php.
References Endpoint\$config, Endpoint\$logging, and Config\ns().
Member Function Documentation
add()
add ()
Hooked Action: Add a unique endpoint to WP if a support agent exists.
Since
1.0.0
See also
Endpoint::init() Called via init hook
Definition at line 271 of file Endpoint.php.
References Endpoint\get_trustedlogin_request().
Referenced by Endpoint\init().
delete()
delete ()
Returns
void
Definition at line 393 of file Endpoint.php.
generate_secret_id()
generate_secret_id ($site_identifier_hash, $endpoint_hash = '')
Generate the secret_id parameter as a hash of the endpoint with the identifier.
Parameters
string $site_identifier_hash
string $endpoint_hash
Returns
string|WP_Error This hash will be used as an identifier in TrustedLogin SaaS. Or something went wrong.
Definition at line 349 of file Endpoint.php.
References Endpoint\get_hash(), and Encryption\hash().
get()
get ()
Get the site option value at {.
See also
option_name}
Returns
string
Definition at line 308 of file Endpoint.php.
get_hash()
get_hash ($site_identifier_hash)
Generate the endpoint parameter as a hash of the site URL with the identifier.
Parameters
$site_identifier_hash
Returns
string This hash will be used as the first part of the URL and also a part of $secret_id
Definition at line 369 of file Endpoint.php.
References Encryption\hash().
Referenced by Endpoint\generate_secret_id().
get_trustedlogin_request()
get_trustedlogin_request () private
Returns sanitized data from a TrustedLogin login $_POST request.
Note: This is not a security check. It is only used to determine whether the request contains the expected keys.
Since
1.1
Returns
false|array{action:string, endpoint:string, identifier: string} If false, the request is not from TrustedLogin. If the request is from TrustedLogin, an array with the posted keys, santiized.
Definition at line 321 of file Endpoint.php.
Referenced by Endpoint\add(), and Endpoint\maybe_login_support().
init()
init ()
Definition at line 96 of file Endpoint.php.
References Endpoint\add().
maybe_login_support()
maybe_login_support ()
Check if the endpoint is hit and has a valid identifier before automatically logging in support agent.
Since
1.0.0
Returns
void
Runs before the support user is (maybe) logged-in
Parameters
string $user_identifier Unique identifier for support user.
Runs after the identifier fails security checks
Parameters
string $user_identifier Unique identifier for support user.
WP_Error $is_verified The error encountered when verifying the identifier.
Runs after the support user fails to log in
Parameters
string $user_identifier Unique Identifier for support user.
WP_Error $is_logged_in The error encountered when logging-in.
Runs after the support user is logged-in
Parameters
string $user_identifier Unique Identifier for support user.
Definition at line 116 of file Endpoint.php.
References Endpoint\get_trustedlogin_request().
maybe_revoke_support()
maybe_revoke_support ()
Hooked Action to maybe revoke support if $_REQUEST[ SupportUser::ID_QUERY_PARAM ] == {namespace} Can optionally check for $_REQUEST[ SupportUser::ID_QUERY_PARAM ] for revoking a specific user by their identifier.
Since
1.0.0
Trigger action to revoke access based on Support User identifier.
Hooked into by Cron::revoke
Parameters
string $user_identifier Unique ID for TrustedLogin support user or "all".
Only triggered when all access has been successfully revoked and no users exist with identifier $identifer.
Parameters
string $user_identifier Unique TrustedLogin ID for the Support User or "all"
Definition at line 203 of file Endpoint.php.
References SupportUser\ID_QUERY_PARAM.
update()
update ($endpoint)
Updates the site's endpoint to listen for logins.
Flushes rewrite rules after updating.
Parameters
string $endpoint
Returns
bool True: updated; False: didn't change, or didn't update
Definition at line 380 of file Endpoint.php.
Field Documentation
$config
Config $config private
Definition at line 50 of file Endpoint.php.
Referenced by Endpoint\__construct().
$logging
Logging $logging private
Definition at line 69 of file Endpoint.php.
Referenced by Endpoint\__construct().
$option_name
$option_name private
Definition at line 57 of file Endpoint.php.
$support_user
$support_user private
Definition at line 63 of file Endpoint.php.
PERMALINK_FLUSH_OPTION_NAME
const PERMALINK_FLUSH_OPTION_NAME = 'tl_permalinks_flushed'
Definition at line 31 of file Endpoint.php.
POST_ACTION_KEY
const POST_ACTION_KEY = 'action'
Definition at line 39 of file Endpoint.php.
POST_ACTION_VALUE
const POST_ACTION_VALUE = 'trustedlogin'
Definition at line 36 of file Endpoint.php.
POST_ENDPOINT_KEY
const POST_ENDPOINT_KEY = 'endpoint'
Definition at line 42 of file Endpoint.php.
POST_IDENTIFIER_KEY
const POST_IDENTIFIER_KEY = 'identifier'
Definition at line 45 of file Endpoint.php.
REVOKE_SUPPORT_QUERY_PARAM
const REVOKE_SUPPORT_QUERY_PARAM = 'revoke-tl'
Definition at line 26 of file Endpoint.php.
Referenced by Admin\generate_button(), SupportUser\get_revoke_url(), and Admin\translations().
The documentation for this class was generated from the following file:
Endpoint.php