GravityView: WP_Customize_Setting Class Reference
WP_Customize_Setting Class Reference
Customize Setting class.
Public Member Functions
__construct ($manager, $id, $args=array())
Constructor.
_clear_aggregated_multidimensional_preview_applied_flag ()
Clear out the previewed-applied flag for a multidimensional-aggregated value whenever its post value is updated.
_multidimensional_preview_filter ($original)
Callback function to filter multidimensional theme mods and options.
_preview_filter ($original)
Callback function to filter non-multidimensional theme mods and options.
check_capabilities ()
Validate user capabilities whether the theme supports the setting.
id_data ()
Get parsed ID data for multidimensional setting.
is_current_blog_previewed ()
Return true if the current blog is not the same as the previewed blog.
js_value ()
Sanitize the setting's value for use in JavaScript.
post_value ($default=null)
Fetch and sanitize the $_POST value for the setting.
preview ()
Add filters to supply the setting's value when accessed.
sanitize ($value)
Sanitize an input.
save ()
Check user capabilities and theme supports, and then save the value of the setting.
value ()
Fetch the value of the setting.
Data Fields
$capability = 'edit_theme_options'
$default = ''
$dirty = false
$id
$manager
$sanitize_callback = ''
$sanitize_js_callback = ''
$theme_supports = ''
$transport = 'refresh'
$type = 'theme_mod'
Protected Member Functions
_update_option ()
Deprecated method.
_update_theme_mod ()
Deprecated method.
aggregate_multidimensional ()
Set up the setting for aggregated multidimensional values.
get_root_value ($default=null)
Get the root value for a setting, especially for multidimensional ones.
multidimensional (&$root, $keys, $create=false)
Multidimensional helper function.
multidimensional_get ($root, $keys, $default=null)
Will attempt to fetch a specific value from a multidimensional array.
multidimensional_isset ($root, $keys)
Will attempt to check if a specific value in a multidimensional array is set.
multidimensional_replace ($root, $keys, $value)
Will attempt to replace a specific value in a multidimensional array.
set_root_value ($value)
Set the root value for a setting, especially for multidimensional ones.
update ($value)
Save the value of the setting, using the related API.
Protected Attributes
$_original_value
$_previewed_blog_id
$id_data = array()
$is_multidimensional_aggregated = false
$is_previewed = false
Static Protected Attributes
static $aggregated_multidimensionals = array()
Detailed Description
Customize Setting class.
Handles saving and sanitizing of settings.
Since
3.4.0
See also
WP_Customize_Manager
Definition at line 19 of file class-wp-customize-setting.php.
Constructor & Destructor Documentation
__construct ($manager, $id, $args = array())
Constructor.
Any supplied $args override class property defaults.
Since
3.4.0
Parameters
WP_Customize_Manager $manager
string $id An specific ID of the setting. Can be a theme mod or option name.
array $args Setting arguments.
Definition at line 124 of file class-wp-customize-setting.php.
References $id, $keys, $manager, $type, add_filter(), aggregate_multidimensional(), id_data(), and str_replace.
Member Function Documentation
_clear_aggregated_multidimensional_preview_applied_flag () final
Clear out the previewed-applied flag for a multidimensional-aggregated value whenever its post value is updated.
This ensures that the new value will get sanitized and used the next time that WP_Customize_Setting::_multidimensional_preview_filter() is called for this setting.
Since
4.4.0 private
See also
WP_Customize_Manager::set_post_value()
WP_Customize_Setting::_multidimensional_preview_filter()
Definition at line 369 of file class-wp-customize-setting.php.
References id_data().
_multidimensional_preview_filter ($original) final
Callback function to filter multidimensional theme mods and options.
For all multidimensional settings of a given type, the preview filter for the first setting previewed will be used to apply the values for the others.
Since
4.4.0 private
See also
WP_Customize_Setting::$aggregated_multidimensionals
Parameters
mixed $original Original root value.
Returns
mixed New or old value.
Definition at line 418 of file class-wp-customize-setting.php.
References $type, $value, id_data(), and is_current_blog_previewed().
_preview_filter ($original)
Callback function to filter non-multidimensional theme mods and options.
If switch_to_blog() was called after the preview() method, and the current blog is now not the same blog, then this method does a no-op and returns the original value.
Since
3.4.0
Parameters
mixed $original Old value.
Returns
mixed New or old value.
Definition at line 385 of file class-wp-customize-setting.php.
References $default, $value, is_current_blog_previewed(), and post_value().
_update_option () protected
Deprecated method.
Since
3.4.0
Definition at line 620 of file class-wp-customize-setting.php.
References _deprecated_function().
_update_theme_mod () protected
Deprecated method.
Since
3.4.0
Definition at line 610 of file class-wp-customize-setting.php.
References _deprecated_function().
aggregate_multidimensional () protected
Set up the setting for aggregated multidimensional values.
When a multidimensional setting gets aggregated, all of its preview and update calls get combined into one call, greatly improving performance.
Since
4.4.0 protected
Definition at line 189 of file class-wp-customize-setting.php.
References $type, add_action(), get_root_value(), and id_data().
Referenced by __construct().
check_capabilities () final
Validate user capabilities whether the theme supports the setting.
Since
3.4.0
Returns
bool False if theme doesn't support the setting or user can't change setting, otherwise true.
Definition at line 695 of file class-wp-customize-setting.php.
Referenced by save().
get_root_value ($default = null) protected
Get the root value for a setting, especially for multidimensional ones.
Since
4.4.0 protected
Parameters
mixed $default Value to return if root does not exist.
Returns
mixed
Definition at line 521 of file class-wp-customize-setting.php.
References $default, get_option(), get_theme_mod(), and id_data().
Referenced by aggregate_multidimensional(), and value().
id_data () final
Get parsed ID data for multidimensional setting.
Since
4.4.0 public
Returns
array { ID data for multidimensional setting.
string $base ID base array $keys Keys for multidimensional array. }
Definition at line 176 of file class-wp-customize-setting.php.
References $id_data.
Referenced by __construct(), _clear_aggregated_multidimensional_preview_applied_flag(), _multidimensional_preview_filter(), aggregate_multidimensional(), get_root_value(), preview(), save(), set_root_value(), update(), and value().
is_current_blog_previewed ()
Return true if the current blog is not the same as the previewed blog.
Since
4.2.0 public
Returns
bool If preview() has been called.
Definition at line 226 of file class-wp-customize-setting.php.
References get_current_blog_id().
Referenced by _multidimensional_preview_filter(), and _preview_filter().
js_value ()
Sanitize the setting's value for use in JavaScript.
Since
3.4.0
Returns
mixed The requested escaped value.
Filter a Customize setting value for use in JavaScript.
The dynamic portion of the hook name, $this->id, refers to the setting ID.
Since
3.4.0
Parameters
mixed $value The setting value.
WP_Customize_Setting $this {
See also
WP_Customize_Setting} instance.
Definition at line 668 of file class-wp-customize-setting.php.
References $value, apply_filters(), and value().
multidimensional (& $root, $keys, $create = false) final protected
Multidimensional helper function.
Since
3.4.0
Parameters
$root
$keys
bool $create Default is false.
Returns
array|void Keys are 'root', 'node', and 'key'.
Definition at line 715 of file class-wp-customize-setting.php.
References $keys.
Referenced by multidimensional_get(), and multidimensional_replace().
multidimensional_get ($root, $keys, $default = null) final protected
Will attempt to fetch a specific value from a multidimensional array.
Since
3.4.0
Parameters
$root
$keys
mixed $default A default value which is used as a fallback. Default is null.
Returns
mixed The requested value or the default value.
Definition at line 789 of file class-wp-customize-setting.php.
References $default, $keys, and multidimensional().
Referenced by multidimensional_isset(), preview(), and value().
multidimensional_isset ($root, $keys) final protected
Will attempt to check if a specific value in a multidimensional array is set.
Since
3.4.0
Parameters
$root
$keys
Returns
bool True if value is set, false if not.
Definition at line 806 of file class-wp-customize-setting.php.
References $keys, and multidimensional_get().
multidimensional_replace ($root, $keys, $value) final protected
Will attempt to replace a specific value in a multidimensional array.
Since
3.4.0
Parameters
$root
$keys
mixed $value The value to update.
Returns
mixed
Definition at line 765 of file class-wp-customize-setting.php.
References $keys, $value, elseif, and multidimensional().
Referenced by update().
post_value ($default = null) final
Fetch and sanitize the $_POST value for the setting.
Since
3.4.0
Parameters
mixed $default A default value which is used as a fallback. Default is null.
Returns
mixed The default value on failure, otherwise the sanitized value.
Definition at line 486 of file class-wp-customize-setting.php.
References $default.
Referenced by _preview_filter(), WP_Customize_Nav_Menu_Setting\preview(), preview(), WP_Customize_Nav_Menu_Item_Setting\preview(), save(), WP_Customize_Nav_Menu_Setting\value(), and WP_Customize_Nav_Menu_Item_Setting\value().
preview ()
Add filters to supply the setting's value when accessed.
If the setting already has a pre-existing value and there is no incoming post value for the setting, then this method will short-circuit since there is no change to preview.
Since
3.4.0
4.4.0 Added boolean return value. public
Returns
bool False when preview short-circuits due no change needing to be previewed.
Fires when the {
See also
WP_Customize_Setting::preview()} method is called for settings not handled as theme_mods or options.
The dynamic portion of the hook name, $this->id, refers to the setting ID.
Since
3.4.0
Parameters
WP_Customize_Setting $this {
See also
WP_Customize_Setting} instance.
Fires when the {
See also
WP_Customize_Setting::preview()} method is called for settings not handled as theme_mods or options.
The dynamic portion of the hook name, $this->type, refers to the setting type.
Since
4.1.0
Parameters
WP_Customize_Setting $this {
See also
WP_Customize_Setting} instance.
Definition at line 255 of file class-wp-customize-setting.php.
References $default, $id, $type, $value, add_action(), add_filter(), do_action(), get_current_blog_id(), has_action(), id_data(), multidimensional_get(), null, post_value(), and value().
sanitize ($value)
Sanitize an input.
Since
3.4.0
Parameters
string | array $value The value to sanitize.
Returns
string|array|null Null if an input isn't valid, otherwise the sanitized value.
Filter a Customize setting value in un-slashed form.
Since
3.4.0
Parameters
mixed $value Value of the setting.
WP_Customize_Setting $this WP_Customize_Setting instance.
Definition at line 498 of file class-wp-customize-setting.php.
References $value, apply_filters(), and wp_unslash().
save () final
Check user capabilities and theme supports, and then save the value of the setting.
Since
3.4.0
Returns
false|void False if cap check fails or value isn't set.
Fires when the WP_Customize_Setting::save() method is called.
The dynamic portion of the hook name, `$this->id_data['base']` refers to the base slug of the setting name.
Since
3.4.0
Parameters
WP_Customize_Setting $this {
See also
WP_Customize_Setting} instance.
Definition at line 457 of file class-wp-customize-setting.php.
References $value, check_capabilities(), do_action(), id_data(), post_value(), and update().
set_root_value ($value) protected
Set the root value for a setting, especially for multidimensional ones.
Since
4.4.0 protected
Parameters
mixed $value Value to set as root of multidimensional setting.
Returns
bool Whether the multidimensional root was updated successfully.
Definition at line 546 of file class-wp-customize-setting.php.
References $type, $value, id_data(), set_theme_mod(), and update_option().
Referenced by update().
update ($value) protected
Save the value of the setting, using the related API.
Since
3.4.0
Parameters
mixed $value The value to update.
Returns
bool The result of saving the value.
Fires when the {
See also
WP_Customize_Setting::update()} method is called for settings not handled as theme_mods or options.
The dynamic portion of the hook name, $this->type, refers to the type of setting.
Since
3.4.0
Parameters
mixed $value Value of the setting.
WP_Customize_Setting $this WP_Customize_Setting instance.
Definition at line 575 of file class-wp-customize-setting.php.
References $type, $value, do_action(), has_action(), id_data(), multidimensional_replace(), and set_root_value().
Referenced by save().
value ()
Fetch the value of the setting.
Since
3.4.0
Returns
mixed The value.
Filter a Customize setting value not handled as a theme_mod or option.
The dynamic portion of the hook name, `$this->id_date['base']`, refers to the base slug of the setting name.
For settings handled as theme_mods or options, see those corresponding functions for available hooks.
Since
3.4.0
Parameters
mixed $default The setting default value. Default empty.
Definition at line 631 of file class-wp-customize-setting.php.
References $type, $value, apply_filters(), get_root_value(), id_data(), and multidimensional_get().
Referenced by js_value(), and preview().
Field Documentation
$_original_value protected
Definition at line 240 of file class-wp-customize-setting.php.
Referenced by WP_Customize_Nav_Menu_Setting\value(), and WP_Customize_Nav_Menu_Item_Setting\value().
$_previewed_blog_id protected
Definition at line 216 of file class-wp-customize-setting.php.
$aggregated_multidimensionals = array() static protected
Definition at line 101 of file class-wp-customize-setting.php.
$capability = 'edit_theme_options'
Definition at line 45 of file class-wp-customize-setting.php.
$default = ''
Definition at line 54 of file class-wp-customize-setting.php.
Referenced by _preview_filter(), get_root_value(), multidimensional_get(), post_value(), and preview().
$dirty = false
Definition at line 77 of file class-wp-customize-setting.php.
$id
Definition at line 32 of file class-wp-customize-setting.php.
Referenced by __construct(), WP_Customize_Nav_Menu_Setting\__construct(), WP_Customize_Nav_Menu_Item_Setting\__construct(), and preview().
$id_data = array() protected
Definition at line 82 of file class-wp-customize-setting.php.
Referenced by id_data().
$is_multidimensional_aggregated = false protected
Definition at line 110 of file class-wp-customize-setting.php.
$is_previewed = false protected
Definition at line 91 of file class-wp-customize-setting.php.
$manager
Definition at line 24 of file class-wp-customize-setting.php.
Referenced by __construct().
$sanitize_callback = ''
Definition at line 62 of file class-wp-customize-setting.php.
$sanitize_js_callback = ''
Definition at line 63 of file class-wp-customize-setting.php.
$theme_supports = ''
Definition at line 53 of file class-wp-customize-setting.php.
$transport = 'refresh'
Definition at line 55 of file class-wp-customize-setting.php.
$type = 'theme_mod'
Definition at line 38 of file class-wp-customize-setting.php.
Referenced by __construct(), _multidimensional_preview_filter(), aggregate_multidimensional(), preview(), set_root_value(), update(), and value().
The documentation for this class was generated from the following file:
class-wp-customize-setting.php