GravityView: Text_Diff_Engine_shell Class Reference
Text_Diff_Engine_shell Class Reference
Public Member Functions
_getLines (&$text_lines, &$line_no, $end=false)
Get lines from either the old or new text.
diff ($from_lines, $to_lines)
Returns the array of differences.
Data Fields
$_diffCommand = 'diff'
Detailed Description
Definition at line 17 of file shell.php.
Member Function Documentation
_getLines (& $text_lines, & $line_no, $end = false)
Get lines from either the old or new text.
private
Parameters
array &$text_lines Either $from_lines or $to_lines
int &$line_no Current line number
int $end Optional end line, when we want to chop more than one line.
Returns
array The chopped lines
Definition at line 145 of file shell.php.
Referenced by diff().
diff ($from_lines, $to_lines)
Returns the array of differences.
Parameters
array $from_lines lines of text from old file
array $to_lines lines of text from new file
Returns
array all changes made (array with Text_Diff_Op_* objects)
Definition at line 34 of file shell.php.
References $temp_dir, _getLines(), and Text_Diff\_getTempDir().
Field Documentation
$_diffCommand = 'diff'
Definition at line 24 of file shell.php.
The documentation for this class was generated from the following file:
shell.php