GravityView: GravityView_Admin Class Reference
GravityView_Admin Class Reference
Public Member Functions
__construct ()
backend_actions ()
Function to launch admin objects.
Static Public Member Functions
static add_notice ($notice=array())
Add a notice to be displayed in the admin.
static check_gravityforms ()
Check if Gravity Forms plugin is active and show notice if not.
static connected_form_warning ($form_id=0)
Display error HTML in Edit View when the form is in the trash or no longer exists in Gravity Forms.
static get_floaty ()
Get an image of our intrepid explorer friend.
static get_notices ()
Get admin notices.
static get_plugin_status ($location='')
Check if specified plugin is active, inactive or not installed.
static is_admin_page ($hook='', $page=NULL)
Is the current admin page a GravityView-related page?
static no_views_text ()
Get text for no views found.
static plugin_action_links ($links)
Modify plugin action links at plugins screen.
Private Member Functions
add_hooks ()
include_required_files ()
Detailed Description
Definition at line 3 of file class-admin.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 5 of file class-admin.php.
References add_hooks(), include_required_files(), and GravityView_Compatibility\is_valid().
Member Function Documentation
add_hooks()
add_hooks () private
Since
1.7.5
Returns
void
Definition at line 45 of file class-admin.php.
References GRAVITYVIEW_FILE.
Referenced by __construct().
add_notice()
static add_notice ($notice = array()) static
Add a notice to be displayed in the admin.
Parameters
array $notice Array with class and message keys. The message is not escaped.
Definition at line 281 of file class-admin.php.
References GravityView_Admin_Notices\add_notice().
backend_actions()
backend_actions ()
Function to launch admin objects.
public
Returns
void
"GRAVITYVIEW_DIR" "../"
Runs Actions:
gravityview_include_backend_actions Triggered after all GravityView admin files are loaded
Nice place to insert extensions' backend stuff
Definition at line 131 of file class-admin.php.
References GRAVITYVIEW_DIR.
check_gravityforms()
static check_gravityforms () static
Check if Gravity Forms plugin is active and show notice if not.
See also
GravityView_Compatibility::get_plugin_status()
Returns
boolean True: checks have been passed; GV is fine to run; False: checks have failed, don't continue loading
Definition at line 292 of file class-admin.php.
References GravityView_Compatibility\check_gravityforms().
connected_form_warning()
static connected_form_warning ($form_id = 0) static
Display error HTML in Edit View when the form is in the trash or no longer exists in Gravity Forms.
Since
1.19
Parameters
int $form_id Gravity Forms
Returns
void
Definition at line 94 of file class-admin.php.
References $form_id, gravityview_get_floaty(), and gravityview_get_link().
get_floaty()
static get_floaty () static
Get an image of our intrepid explorer friend.
Returns
string HTML image tag with floaty's cute mug on it
Definition at line 181 of file class-admin.php.
References GV\$form, $image, $post, gravityview_get_floaty(), gravityview_get_form(), and gravityview_get_form_id().
Referenced by GravityView_Search_WP_Widget\form(), oEmbed\render_admin(), and oEmbed\render_preview_notice().
get_notices()
static get_notices () static
Get admin notices.
Returns
array
Definition at line 272 of file class-admin.php.
References GravityView_Admin_Notices\get_notices().
get_plugin_status()
static get_plugin_status ($location = '') static
Check if specified plugin is active, inactive or not installed.
See also
GravityView_Compatibility::get_plugin_status()
Returns
boolean|string True: plugin is active; False: plugin file doesn't exist at path; 'inactive' it's inactive
Definition at line 304 of file class-admin.php.
References GravityView_Compatibility\get_plugin_status().
include_required_files()
include_required_files () private
Since
1.15
Returns
void
Since
1.15
1.6
1.17
Definition at line 22 of file class-admin.php.
References GRAVITYVIEW_DIR.
Referenced by __construct().
is_admin_page()
static is_admin_page ($hook = '', $page = NULL) static
Is the current admin page a GravityView-related page?
Parameters
string $hook
null | string $page Optional. String return value of page to compare against.
Returns
bool|string If false, not a GravityView page. true if $page is passed and is the same as current page. Otherwise, the name of the page (single, settings, or views)
Definition at line 317 of file class-admin.php.
References gravityview().
no_views_text()
static no_views_text () static
Get text for no views found.
Since
1.18 Moved to GravityView_Admin
Returns
string HTML message with no container tags.
Definition at line 65 of file class-admin.php.
References $image, $output, and GVCommon\has_cap().
Referenced by GravityView_Admin_Add_Shortcode\add_shortcode_popup(), GravityView_Search_WP_Widget\form(), GravityView_Recent_Entries_Widget\form(), and View\register_post_type().
plugin_action_links()
static plugin_action_links ($links) static
Modify plugin action links at plugins screen.
Since
1.15 Added check for gravityview_view_settings and gravityview_support_port capabilities public
Parameters
array $links Array of action links under GravityView on the plugin page
Returns
array Action links with Settings and Support included, if the user has the appropriate caps
Definition at line 162 of file class-admin.php.
References GVCommon\has_cap().
The documentation for this class was generated from the following file:
class-admin.php