GravityView: GravityView_Image_Test Class Reference
GravityView_Image_Test Class Reference
gravityview_image
Public Member Functions
get_extensions ($group= 'all')
Get the allowed extensions for the image.
get_loaded_image ()
Get a GravityView_Image object with attributes set.
test_construct ()
GravityView_Image::__construct
test_html ()
GravityView_Image::html
test_set_image_size ()
GravityView_Image::set_image_size()
test_validate_image_src ()
GravityView_Image::validate_image_src
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
gravityview_image
Definition at line 8 of file GravityView_Image_Test.php.
Member Function Documentation
get_extensions ($group = 'all')
Get the allowed extensions for the image.
Parameters
string $group
Returns
array
Definition at line 163 of file GravityView_Image_Test.php.
Referenced by test_validate_image_src().
get_loaded_image ()
Get a GravityView_Image object with attributes set.
Returns
GravityView_Image
Definition at line 15 of file GravityView_Image_Test.php.
Referenced by test_construct(), and test_html().
test_construct ()
GravityView_Image::__construct
Definition at line 34 of file GravityView_Image_Test.php.
References get_loaded_image().
test_html ()
GravityView_Image::html
Definition at line 51 of file GravityView_Image_Test.php.
References get_loaded_image().
test_set_image_size ()
GravityView_Image::set_image_size()
Definition at line 65 of file GravityView_Image_Test.php.
test_validate_image_src ()
GravityView_Image::validate_image_src
Definition at line 89 of file GravityView_Image_Test.php.
References get_extensions().
The documentation for this class was generated from the following file:
GravityView_Image_Test.php