GravityView: MagpieRSS Class Reference
MagpieRSS Class Reference
Public Member Functions
__construct ($source)
PHP5 constructor.
append ($el, $text)
append_content ($text)
concat (&$str1, $str2="")
error ($errormsg, $lvl=E_USER_WARNING)
feed_cdata ($p, $text)
feed_end_element ($p, $el)
feed_start_element ($p, $element, &$attrs)
is_atom ()
is_rss ()
MagpieRSS ($source)
PHP4 constructor.
map_attrs ($k, $v)
normalize ()
Data Fields
$_CONTENT_CONSTRUCTS = array('content', 'summary', 'info', 'title', 'tagline', 'copyright')
$channel = array()
$current_field = ''
$current_item = array()
$current_namespace = false
$feed_type
$feed_version
$image = array()
$inchannel = false
$incontent = false
$inimage = false
$initem = false
$intextinput = false
$items = array()
$parser
$stack = array()
$textinput = array()
Detailed Description
Definition at line 34 of file rss.php.
Constructor & Destructor Documentation
__construct ($source)
PHP5 constructor.
Definition at line 61 of file rss.php.
References $parser, error(), and normalize().
Member Function Documentation
append ($el, $text)
Definition at line 295 of file rss.php.
References $text, concat(), elseif, and image.
Referenced by feed_cdata(), and feed_start_element().
append_content ($text)
Definition at line 285 of file rss.php.
References $text, concat(), and elseif.
Referenced by feed_cdata(), feed_end_element(), and feed_start_element().
concat (& $str1, $str2 = "")
Definition at line 278 of file rss.php.
Referenced by append(), and append_content().
error ($errormsg, $lvl = E_USER_WARNING)
Definition at line 389 of file rss.php.
Referenced by __construct().
feed_cdata ($p, $text)
Definition at line 221 of file rss.php.
References $text, append(), append_content(), and ATOM.
feed_end_element ($p, $el)
Definition at line 233 of file rss.php.
References $current_item, append_content(), ATOM, elseif, and RSS.
feed_start_element ($p, $element, & $attrs)
Definition at line 110 of file rss.php.
References append(), append_content(), ATOM, elseif, and RSS.
is_atom ()
Definition at line 376 of file rss.php.
References $feed_version, and ATOM.
Referenced by normalize().
is_rss ()
Definition at line 367 of file rss.php.
References $feed_version, and RSS.
Referenced by normalize().
MagpieRSS ($source)
PHP4 constructor.
Definition at line 106 of file rss.php.
map_attrs ($k, $v)
Definition at line 385 of file rss.php.
normalize ()
Definition at line 339 of file rss.php.
References $i, elseif, is_atom(), and is_rss().
Referenced by __construct().
Field Documentation
$_CONTENT_CONSTRUCTS = array('content', 'summary', 'info', 'title', 'tagline', 'copyright')
Definition at line 56 of file rss.php.
$channel = array()
Definition at line 38 of file rss.php.
$current_field = ''
Definition at line 51 of file rss.php.
$current_item = array()
Definition at line 36 of file rss.php.
Referenced by feed_end_element().
$current_namespace = false
Definition at line 52 of file rss.php.
$feed_type
Definition at line 41 of file rss.php.
$feed_version
Definition at line 42 of file rss.php.
Referenced by is_atom(), and is_rss().
$image = array()
Definition at line 40 of file rss.php.
$inchannel = false
Definition at line 46 of file rss.php.
$incontent = false
Definition at line 48 of file rss.php.
$inimage = false
Definition at line 50 of file rss.php.
$initem = false
Definition at line 47 of file rss.php.
$intextinput = false
Definition at line 49 of file rss.php.
$items = array()
Definition at line 37 of file rss.php.
$parser
Definition at line 35 of file rss.php.
Referenced by __construct().
$stack = array()
Definition at line 45 of file rss.php.
$textinput = array()
Definition at line 39 of file rss.php.
The documentation for this class was generated from the following file:
rss.php