GravityView: Cron Class Reference
Cron Class Reference
Public Member Functions
__construct (Config $config, Logging $logging)
Cron constructor.
init ()
reschedule ($expiration_timestamp, $site_identifier_hash)
revoke ($identifier_hash)
Hooked Action: Revokes access for a specific support user.
schedule ($expiration_timestamp, $identifier_hash)
Private Attributes
$config
$hook_name
$logging
Detailed Description
Definition at line 21 of file Cron.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Logging $logging)
Cron constructor.
Parameters
Config $config
Logging | null $logging
Definition at line 44 of file Cron.php.
References Cron\$config, and Cron\$logging.
Member Function Documentation
init()
init ()
Definition at line 54 of file Cron.php.
reschedule()
reschedule ($expiration_timestamp, $site_identifier_hash)
Parameters
int $expiration_timestamp
string $site_identifier_hash
Returns
bool
Definition at line 89 of file Cron.php.
References Cron\schedule().
revoke()
revoke ($identifier_hash)
Hooked Action: Revokes access for a specific support user.
Since
1.0.0
Parameters
string $identifier_hash Identifier hash for the user associated with the cron job
Returns
void
Definition at line 110 of file Cron.php.
schedule()
schedule ($expiration_timestamp, $identifier_hash)
Parameters
int $expiration_timestamp
string $identifier_hash
Returns
bool
Definition at line 64 of file Cron.php.
References $args, and Encryption\hash().
Referenced by Cron\reschedule().
Field Documentation
$config
$config private
Definition at line 26 of file Cron.php.
Referenced by Cron\__construct().
$hook_name
$hook_name private
Definition at line 31 of file Cron.php.
$logging
null TrustedLogin Logging $logging private
Definition at line 36 of file Cron.php.
Referenced by Cron\__construct().
The documentation for this class was generated from the following file:
Cron.php