GravityView: WP_UnitTest_Factory_For_Attachment Class Reference
WP_UnitTest_Factory_For_Attachment Class Reference
Public Member Functions
create_object ($file, $parent=0, $args=array())
create_upload_object ($file, $parent=0)
Public Member Functions inherited from WP_UnitTest_Factory_For_Post
__construct ($factory=null)
create_object ($args)
get_object_by_id ($post_id)
update_object ($post_id, $fields)
Public Member Functions inherited from WP_UnitTest_Factory_For_Thing
__construct ($factory, $default_generation_definitions=array())
Creates a new factory, which will create objects of a specific Thing.
addslashes_deep ($value)
apply_callbacks ($callbacks, $created)
callback ($function)
create ($args=array(), $generation_definitions=null)
create_and_get ($args=array(), $generation_definitions=null)
create_many ($count, $args=array(), $generation_definitions=null)
create_object ($args)
generate_args ($args=array(), $generation_definitions=null, &$callbacks=null)
get_object_by_id ($object_id)
update_object ($object, $fields)
Additional Inherited Members
Data Fields inherited from WP_UnitTest_Factory_For_Thing
$default_generation_definitions
$factory
Detailed Description
Definition at line 92 of file tmp/wordpress-tests-lib/includes/factory.php.
Member Function Documentation
create_object ($file, $parent = 0, $args = array())
Definition at line 94 of file tmp/wordpress-tests-lib/includes/factory.php.
References $file, and wp_insert_attachment().
create_upload_object ($file, $parent = 0)
Definition at line 98 of file tmp/wordpress-tests-lib/includes/factory.php.
References $file, $id, $mime, null, wp_check_filetype(), wp_generate_attachment_metadata(), wp_insert_attachment(), wp_update_attachment_metadata(), and wp_upload_bits().
The documentation for this class was generated from the following file:
tmp/wordpress-tests-lib/includes/factory.php