GravityView: WP_Filesystem_ftpsockets Class Reference
WP_Filesystem_ftpsockets Class Reference
Public Member Functions
__construct ($opt= '')
public
__destruct ()
public
atime ($file)
public
chdir ($file)
public
chmod ($file, $mode=false, $recursive=false)
public
connect ()
public
copy ($source, $destination, $overwrite=false, $mode=false)
public
cwd ()
public
delete ($file, $recursive=false, $type=false)
public
dirlist ($path= '.', $include_hidden=true, $recursive=false)
public
exists ($file)
public
get_contents ($file)
Retrieves the file contents.
get_contents_array ($file)
public
getchmod ($file)
public
group ($file)
public
is_dir ($path)
public
is_file ($file)
public
is_readable ($file)
public
is_writable ($file)
public
mkdir ($path, $chmod=false, $chown=false, $chgrp=false)
public
move ($source, $destination, $overwrite=false)
public
mtime ($file)
public
owner ($file)
public
put_contents ($file, $contents, $mode=false)
public
rmdir ($path, $recursive=false)
public
size ($file)
touch ($file, $time=0, $atime=0)
public
Public Member Functions inherited from WP_Filesystem_Base
abspath ()
Return the path on the remote filesystem of ABSPATH.
atime ($file)
Gets the file's last access time.
chdir ($dir)
Change current directory.
chgrp ($file, $group, $recursive=false)
Change the file group.
chmod ($file, $mode=false, $recursive=false)
Change filesystem permissions.
chown ($file, $owner, $recursive=false)
Change the ownership of a file / folder.
connect ()
Connect filesystem.
copy ($source, $destination, $overwrite=false, $mode=false)
Copy a file.
cwd ()
Get the current working directory.
delete ($file, $recursive=false, $type=false)
Delete a file or directory.
dirlist ($path, $include_hidden=true, $recursive=false)
Get details for files in a directory or a specific file.
exists ($file)
Check if a file or directory exists.
find_base_dir ($base= '.', $echo=false)
Locate a folder on the remote filesystem.
find_folder ($folder)
Locate a folder on the remote filesystem.
get_base_dir ($base= '.', $echo=false)
Locate a folder on the remote filesystem.
get_contents ($file)
Read entire file into a string.
get_contents_array ($file)
Read entire file into an array.
getchmod ($file)
Gets the permissions of the specified file or filepath in their octal format.
gethchmod ($file)
Return the *nix-style file permissions for a file.
getnumchmodfromh ($mode)
Convert *nix-style file permissions to a octal number.
group ($file)
Get the file's group.
is_binary ($text)
Determine if the string provided contains binary characters.
is_dir ($path)
Check if resource is a directory.
is_file ($file)
Check if resource is a file.
is_readable ($file)
Check if a file is readable.
is_writable ($file)
Check if a file or directory is writable.
mkdir ($path, $chmod=false, $chown=false, $chgrp=false)
Create a directory.
move ($source, $destination, $overwrite=false)
Move a file.
mtime ($file)
Gets the file modification time.
owner ($file)
Get the file owner.
put_contents ($file, $contents, $mode=false)
Write a string to a file.
rmdir ($path, $recursive=false)
Delete a directory.
search_for_folder ($folder, $base= '.', $loop=false)
Locate a folder on the remote filesystem.
size ($file)
Gets the file size (in bytes).
touch ($file, $time=0, $atime=0)
Set the access and modification times of a file.
wp_content_dir ()
Return the path on the remote filesystem of WP_CONTENT_DIR.
wp_lang_dir ()
Return the path on the remote filesystem of WP_LANG_DIR.
wp_plugins_dir ()
Return the path on the remote filesystem of WP_PLUGIN_DIR.
wp_themes_dir ($theme=false)
Return the path on the remote filesystem of the Themes Directory.
Data Fields
$ftp
Data Fields inherited from WP_Filesystem_Base
$cache = array()
$errors = null
public
$method = ''
$options = array()
public
$verbose = false
Detailed Description
Definition at line 17 of file class-wp-filesystem-ftpsockets.php.
Constructor & Destructor Documentation
__construct ($opt = '')
public
Parameters
array $opt
Definition at line 29 of file class-wp-filesystem-ftpsockets.php.
References __, and ABSPATH.
__destruct ()
public
Definition at line 539 of file class-wp-filesystem-ftpsockets.php.
References ftp_base\quit().
Member Function Documentation
atime ($file)
public
Parameters
string $file
Returns
bool
Definition at line 410 of file class-wp-filesystem-ftpsockets.php.
chdir ($file)
public
Parameters
string $file
Returns
bool
Definition at line 221 of file class-wp-filesystem-ftpsockets.php.
References $file, and ftp_base\chdir().
Referenced by is_dir().
chmod ($file, $mode = false, $recursive = false)
public
Parameters
string $file
int | bool $mode
bool $recursive
Returns
bool
Definition at line 233 of file class-wp-filesystem-ftpsockets.php.
References $file, $mode, ftp_base\chmod(), dirlist(), elseif, is_dir(), and is_file().
Referenced by mkdir(), and put_contents().
connect ()
public
Returns
bool
Definition at line 66 of file class-wp-filesystem-ftpsockets.php.
References __, ftp_base\connect(), ftp_base\login(), ftp_base\Passive(), ftp_base\SetServer(), and ftp_base\SetType().
copy ($source, $destination, $overwrite = false, $mode = false)
public
Parameters
string $source
string $destination
bool $overwrite
int | bool $mode
Returns
bool
Definition at line 296 of file class-wp-filesystem-ftpsockets.php.
References $content, $mode, exists(), get_contents(), and put_contents().
cwd ()
public
Returns
string
Definition at line 208 of file class-wp-filesystem-ftpsockets.php.
References ftp_base\pwd(), and trailingslashit().
Referenced by is_dir().
delete ($file, $recursive = false, $type = false)
public
Parameters
string $file
bool $recursive
string $type
Returns
bool
Definition at line 327 of file class-wp-filesystem-ftpsockets.php.
References $file, ftp_base\delete(), is_file(), ftp_base\mdel(), and ftp_base\rmdir().
dirlist ($path = '.', $include_hidden = true, $recursive = false)
public
Parameters
string $path
bool $include_hidden
bool $recursive
Returns
bool|array
Definition at line 484 of file class-wp-filesystem-ftpsockets.php.
References $list, $path, ftp_base\dirlist(), exists(), WP_Filesystem_Base\getnumchmodfromh(), is_file(), mbstring_binary_safe_encoding(), and reset_mbstring_encoding().
Referenced by chmod(), getchmod(), group(), and owner().
exists ($file)
public
Parameters
string $file
Returns
bool
Definition at line 344 of file class-wp-filesystem-ftpsockets.php.
References $file, $list, is_dir(), and ftp_base\nlist().
Referenced by copy(), dirlist(), get_contents(), and is_file().
get_contents ($file)
Retrieves the file contents.
Since
2.5.0 public
Parameters
string $file Filename.
Returns
string|false File contents on success, false if no temp file could be opened, or if the file doesn't exist.
Definition at line 118 of file class-wp-filesystem-ftpsockets.php.
References $file, exists(), ftp_base\fget(), mbstring_binary_safe_encoding(), reset_mbstring_encoding(), and wp_tempnam().
Referenced by copy(), and get_contents_array().
get_contents_array ($file)
public
Parameters
string $file
Returns
array
Definition at line 157 of file class-wp-filesystem-ftpsockets.php.
References $file, and get_contents().
getchmod ($file)
public
Parameters
string $file
Returns
string
Definition at line 271 of file class-wp-filesystem-ftpsockets.php.
References $dir, $file, and dirlist().
group ($file)
public
Parameters
string $file
Returns
string
Definition at line 282 of file class-wp-filesystem-ftpsockets.php.
References $dir, $file, and dirlist().
is_dir ($path)
public
Parameters
string $path
Returns
bool
Definition at line 375 of file class-wp-filesystem-ftpsockets.php.
References $path, chdir(), and cwd().
Referenced by chmod(), exists(), and is_file().
is_file ($file)
public
Parameters
string $file
Returns
bool
Definition at line 361 of file class-wp-filesystem-ftpsockets.php.
References $file, exists(), and is_dir().
Referenced by chmod(), delete(), and dirlist().
is_readable ($file)
public
Parameters
string $file
Returns
bool
Definition at line 390 of file class-wp-filesystem-ftpsockets.php.
is_writable ($file)
public
Parameters
string $file
Returns
bool
Definition at line 400 of file class-wp-filesystem-ftpsockets.php.
mkdir ($path, $chmod = false, $chown = false, $chgrp = false)
public
Parameters
string $path
mixed $chmod
mixed $chown
mixed $chgrp
Returns
bool
Definition at line 453 of file class-wp-filesystem-ftpsockets.php.
References $path, chmod(), ftp_base\mkdir(), and untrailingslashit().
move ($source, $destination, $overwrite = false)
public
Parameters
string $source
string $destination
bool $overwrite
Returns
bool
Definition at line 315 of file class-wp-filesystem-ftpsockets.php.
References ftp_base\rename().
mtime ($file)
public
Parameters
string $file
Returns
int
Definition at line 420 of file class-wp-filesystem-ftpsockets.php.
References $file, and ftp_base\mdtm().
owner ($file)
public
Parameters
string $file
Returns
string
Definition at line 260 of file class-wp-filesystem-ftpsockets.php.
References $dir, $file, and dirlist().
put_contents ($file, $contents, $mode = false)
public
Parameters
string $file
string $contents
int | bool $mode
Returns
bool
Definition at line 169 of file class-wp-filesystem-ftpsockets.php.
References $file, $mode, chmod(), ftp_base\fput(), mbstring_binary_safe_encoding(), reset_mbstring_encoding(), and wp_tempnam().
Referenced by copy().
rmdir ($path, $recursive = false)
public
Parameters
string $path
bool $recursive
Definition at line 472 of file class-wp-filesystem-ftpsockets.php.
References $path.
size ($file)
Parameters
string $file
Returns
int
Definition at line 428 of file class-wp-filesystem-ftpsockets.php.
References $file, and ftp_base\filesize().
touch ($file, $time = 0, $atime = 0)
public
Parameters
string $file
int $time
int $atime
Returns
bool
Definition at line 440 of file class-wp-filesystem-ftpsockets.php.
Field Documentation
$ftp
Definition at line 22 of file class-wp-filesystem-ftpsockets.php.
The documentation for this class was generated from the following file:
class-wp-filesystem-ftpsockets.php