GravityView: GFFormDisplay Class Reference
GFFormDisplay Class Reference
Static Public Member Functions
static add_init_script ($form_id, $script_name, $location, $script)
static clean_up_files ($form)
static enqueue_form_scripts ($form, $ajax=false)
static enqueue_scripts ()
static failed_state_validation ($form_id, $field, $value)
static footer_init_scripts ($form_id)
static get_calculations_init_script ($form)
static get_chosen_init_script ($form)
static get_conditional_logic_fields ($form, $fieldId)
static get_copy_values_init_script ($form)
static get_counter_init_script ($form)
static get_currency_format_init_script ($form)
static get_current_page ($form_id)
static get_embedded_forms ($post_content, &$ajax)
static get_field ($field, $value= '', $force_frontend_label=false, $form=null, $field_values=null)
static get_field_content ($field, $value= '', $force_frontend_label=false, $form_id=0, $form=null)
static get_form ($form_id, $display_title=true, $display_description=true, $force_display=false, $field_values=null, $ajax=false, $tabindex=1)
static get_form_button ($form_id, $button_input_id, $button, $default_text, $class, $alt, $target_page_number, $onclick= '')
static get_form_init_scripts ($form)
static get_input_mask_init_script ($form)
static get_max_field_id ($form)
static get_max_page_number ($form)
static get_number_formats_script ($form)
Generates a map of fields IDs and their corresponding number formats used by the GFCalc JS object for correctly converting field values to clean numbers.
static get_password_strength_init_script ($form)
static get_placeholders_init_script ($form)
static get_pricing_init_script ($form)
static get_source_page ($form_id)
static get_state ($form, $field_values)
static get_target_page ($form, $current_page, $field_values)
static gform_footer ($form, $class, $ajax, $field_values, $previous_button, $display_title, $display_description, $tabindex=1)
static handle_confirmation ($form, $lead, $ajax=false)
static handle_save_confirmation ($form, $resume_token, $confirmation_message, $ajax)
static handle_save_email_confirmation ($form, $ajax)
static handle_submission ($form, &$lead, $ajax=false)
static has_calculation_field ($form)
static has_conditional_logic ($form)
static has_field_input_mask ($field)
static has_input_mask ($form, $field=false)
static insert_review_page ($form, $review_page)
Insert review page into form.
static is_empty ($field, $form_id=0)
Used to determine the required validation result.
static is_form_empty ($form)
static is_last_page ($form, $mode= 'submit')
Determine if the last page for the current form object is being submitted or rendered (depending on the provided $mode).
static maybe_add_review_page ($form)
Get form object and insert review page, if necessary.
static print_form_scripts ($form, $ajax)
static process_form ($form_id)
static process_send_resume_link ()
static replace_save_variables ($text, $form, $resume_token, $email=null)
static send_emails ($form, $lead)
static set_current_page ($form_id, $page_number)
static update_confirmation ($form, $lead=null, $event= '')
static validate (&$form, $field_values, $page_number=0, &$failed_validation_page=0)
static validate_entry_limit ($form)
Validates the form's entry limit settings.
static validate_form_schedule ($form)
Data Fields
const ON_CONDITIONAL_LOGIC = 2
const ON_PAGE_RENDER = 1
Static Public Attributes
static $submission = array()
Static Private Member Functions
static get_conditional_logic ($form, $field_values=array())
Get init script and all necessary data for conditional logic.
static get_honeypot_field ($form)
static get_honeypot_labels ()
static get_js_redirect_confirmation ($url, $ajax)
static get_limit_period_dates ($period)
static get_progress_bar ($form, $form_id, $confirmation_message)
static has_character_counter ($form)
static has_conditional_logic_legwork ($form)
static has_currency_copy_values_option ($form)
static has_currency_format_number_field ($form)
static has_datepicker_field ($form)
static has_enhanced_dropdown ($form)
static has_fileupload_field ($form)
static has_other_choice ($form)
static has_pages ($form)
Determine if form has any pages.
static has_password_strength ($form)
static has_placeholder ($form)
static has_price_field ($form)
static has_recaptcha_field ($form)
static is_page_active ($form_id, $page_number)
static prev_field_has_description ($form, $field_id)
static register_form_init_scripts ($form, $field_values=array(), $is_ajax=false)
Enqueue and retrieve all inline scripts that should be executed when the form is rendered.
static set_submission_if_null ($form_id, $key, $val)
static upload_files ($form, $files)
static validate_honeypot ($form)
Static Private Attributes
static $init_scripts = array()
static $printed_scripts = array()
Detailed Description
Definition at line 7 of file form_display.php.
Member Function Documentation
static add_init_script ($form_id, $script_name, $location, $script) static
Definition at line 1031 of file form_display.php.
References $form_id, and $location.
Referenced by GF_Field\register_form_init_scripts().
static clean_up_files ($form) static
Filter through the experiation days of a incomplete form submission
Definition at line 1265 of file form_display.php.
References $file, $form, apply_filters(), and GFFormsModel\get_upload_path().
static enqueue_form_scripts ($form, $ajax = false) static
Fires before any scripts are enqueued (form specific using the ID as well)
Parameters
array $form The Form Object
bool $ajax Whether AJAX is on or off (True or False)
Definition at line 1586 of file form_display.php.
References $form, $min, get_option(), is_rtl(), null, wp_enqueue_script(), wp_enqueue_style(), and wp_script_is().
Referenced by GFForms\enqueue_form_scripts(), and GravityView_Edit_Entry_Render\print_scripts().
static enqueue_scripts () static
Definition at line 1550 of file form_display.php.
References $form, $forms, and $post.
Referenced by GFForms\enqueue_scripts().
static failed_state_validation ($form_id, $field, $value) static
Definition at line 1492 of file form_display.php.
References $field, $value, wp_kses(), and wp_kses_allowed_html().
static footer_init_scripts ($form_id) static
A filter to allow modification of scripts that fire in the footer
Parameters
int $form_id The Form ID to filter through
string $form_string Get the form scripts in a string
array $form The Form object to filter through
int $current_page The Current form page ID (If paging is enabled)
Definition at line 1003 of file form_display.php.
References $form, $form_id, apply_filters(), and GFFormsModel\get_form_meta().
static get_calculations_init_script ($form) static
Definition at line 2237 of file form_display.php.
References $field, and $form.
static get_chosen_init_script ($form) static
Definition at line 2128 of file form_display.php.
References $field, $form, __, esc_attr(), and GFFormsModel\get_input_type().
static get_conditional_logic ($form, $field_values = array()) static private
Get init script and all necessary data for conditional logic.
Parameters
$form
array $field_values
Returns
string
Definition at line 1799 of file form_display.php.
References $field, $form, $format, $wp_locale, elseif, esc_attr(), GFFormsModel\get_parameter_value(), GFFormsModel\get_section(), null, and str_replace.
static get_conditional_logic_fields ($form, $fieldId) static
Definition at line 2438 of file form_display.php.
References $field, and $form.
static get_copy_values_init_script ($form) static
Definition at line 2151 of file form_display.php.
static get_counter_init_script ($form) static
Definition at line 2169 of file form_display.php.
References $field, $field_id, $form, __, and esc_js().
static get_currency_format_init_script ($form) static
Definition at line 2140 of file form_display.php.
References $field, and $form.
static get_current_page ($form_id) static
Definition at line 504 of file form_display.php.
References $form_id.
static get_embedded_forms ($post_content, & $ajax) static
Definition at line 1564 of file form_display.php.
References $form_id, $forms, GFFormsModel\get_form_id(), GFFormsModel\get_form_meta(), and shortcode_parse_atts().
static get_field ($field, $value = '', $force_frontend_label = false, $form = null, $field_values = null) static
Definition at line 2480 of file form_display.php.
References $field, $field_id, $form, $id, $value, __, GFFormsModel\get_input_type(), is_ssl(), null, and str_replace.
static get_field_content ($field, $value = '', $force_frontend_label = false, $form_id = 0, $form = null) static
Parameters
GF_Field $field
string $value
bool $force_frontend_label
int $form_id
null | array $form
Returns
string
Definition at line 2609 of file form_display.php.
References $field, $form, $form_id, $value, apply_filters(), esc_html, esc_html__(), GFFormsModel\get_input_type(), is_ssl(), and str_replace.
static get_form ($form_id, $display_title = true, $display_description = true, $force_display = false, $field_values = null, $ajax = false, $tabindex = 1) static
Provides the ability to modify the options used to display the form
Parameters
array An array of Form Arguments when adding it to a page/post (Like the ID, Title, AJAX or not, etc)
A filter that allows disabling of the form view counter
Parameters
int $form_id The Form ID to filter when disabling the form view counter
bool Default set to false (view counter enabled), can be set to true to disable the counter
Filter through the form previous button when paged
Parameters
int $form_id The Form ID to filter through
string $previous_button The HTML rendered button (rendered with the form ID and the function get_form_button)
array $form The Form object to filter through
Definition at line 576 of file form_display.php.
References $_SERVER, $action, $class, $count, $field, $form, $form_id, $i, GFFormsModel\$unique_ids, GFFormsModel\$uploaded_files, $wp_scripts, __, add_action(), apply_filters(), current_user_can(), elseif, esc_html__(), esc_url, GFForms\get(), GFFormsModel\get_field_value(), GFAPI\get_form(), GFFormsModel\get_form(), GFFormsModel\get_form_id(), GFFormsModel\get_incomplete_submission_values(), GFFormsModel\insert_form_view(), GFFormsModel\is_html5_enabled(), is_wp_error(), null, remove_query_arg(), and sanitize_key().
Referenced by GFForms\ajax_parse_request(), GFForms\get_form(), and GravityView_Edit_Entry_Render\render_edit_form().
static get_form_button ($form_id, $button_input_id, $button, $default_text, $class, $alt, $target_page_number, $onclick = '') static
Definition at line 1044 of file form_display.php.
References $class, esc_attr(), and GFFormsModel\is_html5_enabled().
static get_form_init_scripts ($form) static
Definition at line 2081 of file form_display.php.
References $form, $init_scripts, apply_filters(), and wp_script_is().
static get_honeypot_field ($form) static private
Definition at line 1149 of file form_display.php.
References $field, $form, __, and GF_Fields\create().
static get_honeypot_labels () static private
Definition at line 1169 of file form_display.php.
static get_input_mask_init_script ($form) static
Definition at line 2214 of file form_display.php.
References $field, $form, and esc_js().
static get_js_redirect_confirmation ($url, $ajax) static private
Definition at line 1358 of file form_display.php.
References apply_filters().
static get_limit_period_dates ($period) static private
Definition at line 538 of file form_display.php.
References null.
static get_max_field_id ($form) static
Definition at line 1158 of file form_display.php.
References $field, and $form.
Referenced by GFPaymentAddOn\maybe_validate().
static get_max_page_number ($form) static
Definition at line 1137 of file form_display.php.
References $field, and $form.
static get_number_formats_script ($form) static
Generates a map of fields IDs and their corresponding number formats used by the GFCalc JS object for correctly converting field values to clean numbers.
Number fields have a 'numberFormat' setting (w/ UI).
Single-input product fields (i.e. 'singleproduct', 'calculation', 'price' and 'hiddenproduct') should default to the number format of the configured currency.
All other product fields will default to 'decimal_dot' for the number format.
All other fields will have no format (false) and inherit the format of the formula field when the formula is calculated.
Parameters
mixed $form
Returns
string
Definition at line 2274 of file form_display.php.
References $field, $form, $format, and GFFormsModel\get_input_type().
static get_password_strength_init_script ($form) static
Definition at line 2200 of file form_display.php.
References $field, $field_id, $form, __, and esc_js().
static get_placeholders_init_script ($form) static
Definition at line 2160 of file form_display.php.
static get_pricing_init_script ($form) static
Definition at line 2191 of file form_display.php.
static get_progress_bar ($form, $form_id, $confirmation_message) static private
Definition at line 2639 of file form_display.php.
References $form, $form_id, $page_count, apply_filters(), and esc_html__().
static get_source_page ($form_id) static
Definition at line 494 of file form_display.php.
References GFForms\post().
static get_state ($form, $field_values) static
Definition at line 307 of file form_display.php.
References $field, $form, $value, GFFormsModel\get_field_value(), and GFFormsModel\maybe_trim_input().
static get_target_page ($form, $current_page, $field_values) static
Definition at line 475 of file form_display.php.
References $form, GFFormsModel\is_page_hidden(), and GFForms\post().
static gform_footer ($form, $class, $ajax, $field_values, $previous_button, $display_title, $display_description, $tabindex = 1) static
Definition at line 1083 of file form_display.php.
References $class, $form, $form_id, GFFormsModel\$unique_ids, GFFormsModel\$uploaded_files, __, absint(), esc_attr(), GFFormsModel\get_form_unique_id(), sanitize_key(), str_replace, and wp_nonce_field().
static handle_confirmation ($form, $lead, $ajax = false) static
Definition at line 1294 of file form_display.php.
References $form, $url, get_permalink(), and str_replace.
static handle_save_confirmation ($form, $resume_token, $confirmation_message, $ajax) static
Definition at line 2955 of file form_display.php.
References $form, $form_id, absint(), and null.
static handle_save_email_confirmation ($form, $ajax) static
Definition at line 2915 of file form_display.php.
References $form, $form_id, $submission, absint(), and GFFormsModel\get_incomplete_submission_values().
static handle_submission ($form, & $lead, $ajax = false) static
A filter to set if an entry is spam
Parameters
int $form,['id'] The Form ID to filter through (take directly from the form object)
bool $is_spam True or false to filter if the entry is spam
array $form The Form object to filer through
array $lead The Lead object to filter through
Definition at line 1196 of file form_display.php.
References $form, GFFormsModel\delete_incomplete_submission(), do_action(), GFFormsModel\get_lead(), null, GFFormsModel\purge_expired_incomplete_submissions(), GFFormsModel\save_lead(), GFFormsModel\set_current_lead(), GFFormsModel\set_entry_meta(), and GFFormsModel\update_lead_property().
static has_calculation_field ($form) static
Definition at line 2421 of file form_display.php.
References $field, and $form.
static has_character_counter ($form) static private
Definition at line 391 of file form_display.php.
References $field, and $form.
static has_conditional_logic ($form) static
A filter that runs through a form that has conditional logic
Parameters
bool $has_conditional_logic True or False if the user has conditional logic active in their current form settings
array $form The Current form object
Definition at line 1754 of file form_display.php.
References $form, and apply_filters().
static has_conditional_logic_legwork ($form) static private
Definition at line 1766 of file form_display.php.
References $field, and $form.
static has_currency_copy_values_option ($form) static private
Definition at line 2361 of file form_display.php.
References $field, and $form.
static has_currency_format_number_field ($form) static private
Definition at line 2348 of file form_display.php.
References $field, $form, and GFFormsModel\get_input_type().
static has_datepicker_field ($form) static private
Definition at line 2312 of file form_display.php.
References $field, $form, and GFFormsModel\get_input_type().
static has_enhanced_dropdown ($form) static private
Definition at line 429 of file form_display.php.
References $field, $form, and GFFormsModel\get_input_type().
static has_field_input_mask ($field) static
Definition at line 2407 of file form_display.php.
References $field, and GFFormsModel\get_input_type().
static has_fileupload_field ($form) static private
Definition at line 2335 of file form_display.php.
References $field, $form, and GFFormsModel\get_input_type().
static has_input_mask ($form, $field = false) static
Definition at line 2385 of file form_display.php.
References $field, and $form.
static has_other_choice ($form) static private
Definition at line 459 of file form_display.php.
References $field, and $form.
static has_pages ($form) static private
Determine if form has any pages.
private
Parameters
array $form - The form object
Returns
bool - If form object has any pages
Definition at line 387 of file form_display.php.
References $form.
static has_password_strength ($form) static private
Definition at line 444 of file form_display.php.
References $field, and $form.
static has_placeholder ($form) static private
Definition at line 406 of file form_display.php.
References $field, and $form.
static has_price_field ($form) static private
Definition at line 2325 of file form_display.php.
References $field, $form, and GFFormsModel\get_input_type().
static has_recaptcha_field ($form) static private
Definition at line 2373 of file form_display.php.
References $field, and $form.
static insert_review_page ($form, $review_page) static
Insert review page into form.
public
Parameters
array $form - The current Form object
array $review_page - The review page
Returns
array $form
Definition at line 2995 of file form_display.php.
References $form.
static is_empty ($field, $form_id = 0) static
Used to determine the required validation result.
Parameters
GF_Field $field
int $form_id
Returns
bool
Definition at line 1181 of file form_display.php.
References $field, and $form_id.
Referenced by GravityView_Edit_Entry_Render\custom_validation().
static is_form_empty ($form) static
Definition at line 1481 of file form_display.php.
References $field, and $form.
static is_last_page ($form, $mode = 'submit') static
Determine if the last page for the current form object is being submitted or rendered (depending on the provided $mode).
Parameters
array $form A Gravity Forms form object.
string $mode Mode to check for: 'submit' or 'render'
Returns
boolean
Definition at line 522 of file form_display.php.
References $form, $mode, and GFForms\post().
Referenced by GFPaymentAddOn\maybe_validate().
static is_page_active ($form_id, $page_number) static private
Definition at line 510 of file form_display.php.
References $form_id.
static maybe_add_review_page ($form) static
Get form object and insert review page, if necessary.
Parameters
array $form The current Form object
Returns
mixed The form meta array or false
GFFormsModel::create_lead() caches the field value and conditional logic visibility which can create issues when 3rd parties use hooks later in the process to modify the form. Let's flush the cache avoid any weirdness.
A filter for setting up the review page
Parameters
array $review_page The review page parameters
array $form The current form object
array | false $partial_entry The partial entry for the form or false on initial form display.
Definition at line 210 of file form_display.php.
References $form, __, GFFormsModel\get_current_lead(), and has_filter().
static prev_field_has_description ($form, $field_id) static private
Definition at line 2584 of file form_display.php.
References $field, $field_id, $form, and null.
static print_form_scripts ($form, $ajax) static
Definition at line 1672 of file form_display.php.
References $form, $min, get_option(), is_rtl(), null, wp_enqueue_script(), wp_enqueue_style(), wp_print_scripts(), wp_print_styles(), wp_script_is(), and wp_style_is().
Referenced by GFForms\print_form_scripts().
static process_form ($form_id) static
Filter the form before GF begins to process the submission.
Parameters
array $form The Form Object
Fires after the form processing is completed. Form processing happens when submitting a page on a multi-page form (i.e. going to the "Next" or "Previous" page), or when submitting a single page form.
Parameters
array $form The Form Object
int $page_number In a multi-page form, this variable contains the current page number.
int $source_page_number In a multi-page form, this parameters contains the number of the page that the submission came from. For example, when clicking "Next" on page 1, this parameter will be set to 1. When clicking "Previous" on page 2, this parameter will be set to 2.
Definition at line 15 of file form_display.php.
References $form, $form_id, GFFormsModel\$uploaded_files, elseif, esc_url_raw(), exit, GFFormsModel\get_current_lead(), GFFormsModel\get_current_page_url(), GFAPI\get_form(), GFFormsModel\get_form_unique_id(), GFFormsModel\get_ip(), null, GFForms\post(), sanitize_key(), and GFFormsModel\save_incomplete_submission().
Referenced by GFForms\maybe_process_form(), and GFAPI\submit_form().
static process_send_resume_link () static
Definition at line 2779 of file form_display.php.
References $form, $form_id, $submission, absint(), GFFormsModel\add_email_to_incomplete_sumbmission(), GFFormsModel\get_form_meta(), GFFormsModel\get_incomplete_submission_values(), sanitize_key(), and wp_die().
Referenced by GFForms\maybe_process_form().
static register_form_init_scripts ($form, $field_values = array(), $is_ajax = false) static private
Enqueue and retrieve all inline scripts that should be executed when the form is rendered.
Use add_init_script() function to enqueue scripts.
Parameters
array $form
array $field_values
bool $is_ajax
Definition at line 2012 of file form_display.php.
References $field, and $form.
static replace_save_variables ($text, $form, $resume_token, $email = null) static
Definition at line 2830 of file form_display.php.
References $action, $form, $form_id, $options, $text, add_query_arg(), apply_filters(), esc_attr(), esc_html__(), esc_url, GFFormsModel\get_current_page_url(), GFFormsModel\is_html5_enabled(), remove_query_arg(), sanitize_key(), shortcode_parse_atts(), str_replace, and wp_nonce_field().
Referenced by GFAPI\submit_form().
static send_emails ($form, $lead) static
Definition at line 1369 of file form_display.php.
References $form, and _deprecated_function().
static set_current_page ($form_id, $page_number) static
Definition at line 500 of file form_display.php.
References $form_id.
Referenced by GFPaymentAddOn\validation().
static set_submission_if_null ($form_id, $key, $val) static private
Definition at line 264 of file form_display.php.
References $form_id.
static update_confirmation ($form, $lead = null, $event = '') static
Definition at line 2727 of file form_display.php.
References $form, GFFormsModel\create_lead(), and wp_filter_object_list().
static upload_files ($form, $files) static private
Definition at line 270 of file form_display.php.
References $field, $form, GFFormsModel\get_input_type(), GFFormsModel\get_temp_filename(), GFFormsModel\get_upload_path(), GFFormsModel\set_permissions(), and wp_mkdir_p().
static validate (& $form, $field_values, $page_number = 0, & $failed_validation_page = 0) static
Definition at line 1374 of file form_display.php.
References $field, $form, $value, __, esc_html__(), GFFormsModel\get_field_value(), GFFormsModel\get_input_type(), GFFormsModel\is_duplicate(), and GFFormsModel\is_field_hidden().
Referenced by GravityView_Edit_Entry_Render\validate().
static validate_entry_limit ($form) static
Validates the form's entry limit settings.
Returns the entry limit message if entry limit exceeded.
Parameters
array $form current GF form object
Returns
string If entry limit exceeded returns entry limit setting.
Definition at line 2693 of file form_display.php.
References $form, esc_html__(), GFFormsModel\get_lead_count(), and null.
static validate_form_schedule ($form) static
Definition at line 2708 of file form_display.php.
References $form, $now, current_time(), elseif, and esc_html__().
static validate_honeypot ($form) static private
Definition at line 1190 of file form_display.php.
References $form.
Field Documentation
$init_scripts = array() static private
Definition at line 10 of file form_display.php.
Referenced by get_form_init_scripts().
$printed_scripts = array() static private
Definition at line 1670 of file form_display.php.
$submission = array() static
Definition at line 9 of file form_display.php.
Referenced by handle_save_email_confirmation(), process_send_resume_link(), and GFAPI\submit_form().
const ON_CONDITIONAL_LOGIC = 2
Definition at line 13 of file form_display.php.
const ON_PAGE_RENDER = 1
Definition at line 12 of file form_display.php.
Referenced by GF_Field\register_form_init_scripts().
The documentation for this class was generated from the following file:
form_display.php