GravityView: GVFuture_Test Class Reference
GVFuture_Test Class Reference
All future tests live here for now...
Public Member Functions
setUp ()
test_entry_endpoint_rewrite_name ()
::add_rewrite_endpoint() ::get_endpoint_name()
test_plugin_activate ()
::activate()
test_plugin_dir_and_url ()
::dir() ::url()
test_plugin_is_compatible ()
::is_compatible() ::is_compatible_wordpress() ::is_compatible_gravityforms() ::is_compatible_php()
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
All future tests live here for now...
...at least until the future Test component appears.
gvfuture
Definition at line 12 of file GravityView_Future_Test.php.
Member Function Documentation
setUp ()
The future branch of GravityView requires PHP 5.3+ namespaces.
Not being loaded by the plugin yet.
Definition at line 13 of file GravityView_Future_Test.php.
test_entry_endpoint_rewrite_name ()
::add_rewrite_endpoint() ::get_endpoint_name()
Deprecated, but an alias.
Deprecated back-compatibility insurance.
Make sure oEmbed handler registration doesn't error out with ::get_endpoint_name, and works.
Make sure is_single_entry works without error, too. Uses ::get_endpoint_name
Definition at line 103 of file GravityView_Future_Test.php.
References Entry\add_rewrite_endpoint(), GravityView_Post_Types\get_entry_var_name(), GravityView_Post_Types\init_rewrite(), and GravityView_frontend\is_single_entry().
test_plugin_activate ()
::activate()
Trigger an activation. By default, during tests these are not triggered.
Deprecated.
Definition at line 127 of file GravityView_Future_Test.php.
References GravityView_Plugin\activate(), gravityview(), and GravityView_Plugin\version.
test_plugin_dir_and_url ()
::dir() ::url()
Due to how WP_PLUGIN_DIR is different in test mode, we are only able to check bits of the URL
Definition at line 33 of file GravityView_Future_Test.php.
References gravityview(), and GRAVITYVIEW_DIR.
test_plugin_is_compatible ()
::is_compatible() ::is_compatible_wordpress() ::is_compatible_gravityforms() ::is_compatible_php()
Under normal testing conditions this should pass.
Simulate various other conditions, including failure conditions.
Cleanup used overrides.
Test deprecations and stubs in the old code.
Definition at line 51 of file GravityView_Future_Test.php.
References GravityView_Compatibility\check_gravityforms(), GravityView_Compatibility\check_php(), GravityView_Compatibility\check_wordpress(), gravityview(), and GravityView_Compatibility\is_valid().
The documentation for this class was generated from the following file:
GravityView_Future_Test.php