GravityView: GFFormSettings Class Reference
GFFormSettings Class Reference
Static Public Member Functions
static confirmations_edit_page ($form_id, $confirmation_id)
static confirmations_list_page ($form_id)
static confirmations_page ()
static form_settings_page ()
static form_settings_ui ()
Detailed Description
Definition at line 7 of file form_settings.php.
Member Function Documentation
static confirmations_edit_page ($form_id, $confirmation_id) static
Definition at line 1050 of file form_settings.php.
References $count, $form, $form_id, $name, __, align, apply_filters(), endif, get_confirmation_ui_settings(), GFFormsModel\get_entry_meta(), GFFormsModel\get_form_meta(), handle_confirmation_edit_submission(), is_unique_name(), label, output_field_scripts(), and page_header().
static confirmations_list_page ($form_id) static
Definition at line 984 of file form_settings.php.
References $form, $form_id, __, _e, add_query_arg(), GFFormsModel\get_form_meta(), input, maybe_process_confirmation_list_action(), name, page_footer(), page_header(), ToggleActive(), and wp_nonce_field().
static confirmations_page () static
Definition at line 974 of file form_settings.php.
References $form_id.
static form_settings_page () static
Definition at line 9 of file form_settings.php.
References do_action(), and notification_page().
Referenced by GFForms\forms().
static form_settings_ui () static
New Form Settings Functions
These variables are used to convenient "wrap" child form settings in the appropriate HTML.
Definition at line 29 of file form_settings.php.
References $form, $form_id, $i, $label, $value, __, _e, activate_save(), apply_filters(), deactivate_save(), do_action(), elseif, esc_attr(), esc_html, GFFormsModel\get_form_meta(), gform_tooltip(), input, GFFormsModel\maybe_sanitize_form_settings(), name, null, output_field_scripts(), page_footer(), page_header(), and wp_nonce_field().
The documentation for this class was generated from the following file:
form_settings.php