GravityView: GravityForms Class Reference
GravityForms Class Reference
Public Member Functions
modify_system_report ($system_report)
Adds GravityKit products to GF's system report.
Static Public Member Functions
static get_instance ()
Returns class instance.
Private Member Functions
__construct ()
Static Private Attributes
static $_instance
Detailed Description
Definition at line 15 of file GravityForms.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Definition at line 23 of file GravityForms.php.
Member Function Documentation
get_instance()
static get_instance () static
Returns class instance.
Since
1.0.3
Returns
GravityForms
Definition at line 34 of file GravityForms.php.
Referenced by Core\init().
modify_system_report()
modify_system_report ($system_report)
Adds GravityKit products to GF's system report.
Since
1.0.3
Parameters
array $system_report
Returns
array
Controls whether to include a GravityKit product in GF's system report.
Runs Filter:
gk/foundation/integrations/gravityforms/add-to-system-report
Since
1.0.3
Parameters
bool $include_in_system_report Default: true.
string $text_domain Product text domain.
Definition at line 51 of file GravityForms.php.
References Arr\get(), and Core\get_instance().
Field Documentation
$_instance
$_instance static private
Definition at line 21 of file GravityForms.php.
The documentation for this class was generated from the following file:
GravityForms.php