GravityView: WP_Theme Class Reference
WP_Theme Class Reference
Public Member Functions
__construct ($theme_dir, $theme_root, $_child=null)
Constructor for WP_Theme.
__get ($offset)
__get() magic method for properties formerly returned by current_theme_info()
__isset ($offset)
__isset() magic method for properties formerly returned by current_theme_info()
__toString ()
When converting the object to a string, the theme name is returned.
cache_delete ()
Clears the cache for the theme.
display ($header, $markup=true, $translate=true)
Gets a theme header, formatted and translated for display.
errors ()
Returns errors property.
exists ()
Whether the theme exists.
get ($header)
Get a raw, unformatted theme header.
get_files ($type=null, $depth=0, $search_parent=false)
Return files in the theme's directory.
get_page_templates ($post=null)
Returns the theme's page templates.
get_screenshot ($uri= 'uri')
Returns the main screenshot file for the theme.
get_stylesheet ()
The directory name of the theme's "stylesheet" files, inside the theme root.
get_stylesheet_directory ()
Returns the absolute path to the directory of a theme's "stylesheet" files.
get_stylesheet_directory_uri ()
Returns the URL to the directory of a theme's "stylesheet" files.
get_template ()
The directory name of the theme's "template" files, inside the theme root.
get_template_directory ()
Returns the absolute path to the directory of a theme's "template" files.
get_template_directory_uri ()
Returns the URL to the directory of a theme's "template" files.
get_theme_root ()
The absolute path to the directory of the theme root.
get_theme_root_uri ()
Returns the URL to the directory of the theme root.
is_allowed ($check= 'both', $blog_id=null)
Whether the theme is allowed (multisite only).
load_textdomain ()
Loads the theme's textdomain.
offsetExists ($offset)
Method to implement ArrayAccess for keys formerly returned by get_themes()
offsetGet ($offset)
Method to implement ArrayAccess for keys formerly returned by get_themes().
offsetSet ($offset, $value)
Method to implement ArrayAccess for keys formerly returned by get_themes()
offsetUnset ($offset)
Method to implement ArrayAccess for keys formerly returned by get_themes()
parent ()
Returns reference to the parent theme.
Static Public Member Functions
static get_allowed ($blog_id=null)
Returns array of stylesheet names of themes allowed on the site or network.
static get_allowed_on_network ()
Returns array of stylesheet names of themes allowed on the network.
static get_allowed_on_site ($blog_id=null)
Returns array of stylesheet names of themes allowed on the site.
static get_core_default_theme ()
Determines the latest WordPress default theme that is installed.
static sort_by_name (&$themes)
Sort themes by name.
Data Fields
$update = false
Private Member Functions
cache_add ($key, $data)
Adds theme data to cache.
cache_get ($key)
Gets theme data from cache.
markup_header ($header, $value, $translate)
Mark up a theme header.
sanitize_header ($header, $value)
Sanitize a theme header.
translate_header ($header, $value)
Translate a theme header.
Static Private Member Functions
static _name_sort ($a, $b)
Callback function for usort() to naturally sort themes by name.
static _name_sort_i18n ($a, $b)
Name sort (with translation).
static scandir ($path, $extensions=null, $depth=0, $relative_path= '')
Scans a directory for files of a certain extension.
Private Attributes
$cache_hash
$errors
$headers = array()
$headers_sanitized
$name_translated
$parent
$stylesheet
$template
$textdomain_loaded
$theme_root
$theme_root_uri
URL to the theme root, usually an absolute URL to wp-content/themes.
Static Private Attributes
static $cache_expiration = 1800
static $default_themes
static $file_headers
static $persistently_cache
static $tag_map
Detailed Description
Definition at line 9 of file class-wp-theme.php.
Constructor & Destructor Documentation
__construct ($theme_dir, $theme_root, $_child = null)
Constructor for WP_Theme.
array $wp_theme_directories
Parameters
string $theme_dir Directory of the theme within the theme_root.
string $theme_root Theme root.
WP_Error | void $_child If this theme is a parent theme, the child may be passed for validation purposes.
This action is documented in wp-includes/theme.php
Definition at line 201 of file class-wp-theme.php.
References $stylesheet, $template, $theme_root, __, apply_filters(), cache_add(), cache_get(), elseif, errors(), esc_html, get_file_data(), null, parent(), search_theme_directories(), wp_cache_add_global_groups(), and wp_cache_add_non_persistent_groups().
Referenced by cache_delete().
Member Function Documentation
__get ($offset)
__get() magic method for properties formerly returned by current_theme_info()
Parameters
string $offset Property to get.
Returns
mixed Property value.
Definition at line 356 of file class-wp-theme.php.
References display(), get_screenshot(), get_stylesheet(), get_stylesheet_directory(), get_template(), get_template_directory(), get_theme_root(), get_theme_root_uri(), offsetGet(), and parent().
__isset ($offset)
__isset() magic method for properties formerly returned by current_theme_info()
array $properties
Returns
bool
Definition at line 341 of file class-wp-theme.php.
__toString ()
When converting the object to a string, the theme name is returned.
Returns
string Theme name, ready for display (translated)
Definition at line 330 of file class-wp-theme.php.
References display().
static _name_sort ($a, $b) static private
Callback function for usort() to naturally sort themes by name.
Accesses the Name header directly from the class for maximum speed. Would choke on HTML but we don't care enough to slow it down with strip_tags().
Since
3.4.0
private
Returns
int
Definition at line 1314 of file class-wp-theme.php.
static _name_sort_i18n ($a, $b) static private
Name sort (with translation).
Since
3.4.0
private
Returns
int
Definition at line 1328 of file class-wp-theme.php.
cache_add ($key, $data) private
Adds theme data to cache.
Cache entries keyed by the theme and the type of data.
Since
3.4.0 private
Parameters
string $key Type of data to store (theme, screenshot, headers, page_templates)
string $data Data to store
Returns
bool Return value from wp_cache_add()
Definition at line 534 of file class-wp-theme.php.
References wp_cache_add().
Referenced by __construct(), get(), get_page_templates(), and get_screenshot().
cache_delete ()
Clears the cache for the theme.
Since
3.4.0 public
Definition at line 559 of file class-wp-theme.php.
References __construct(), errors(), null, parent(), and wp_cache_delete().
cache_get ($key) private
Gets theme data from cache.
Cache entries are keyed by the theme and the type of data.
Since
3.4.0 private
Parameters
string $key Type of data to retrieve (theme, screenshot, headers, page_templates)
Returns
mixed Retrieved data
Definition at line 549 of file class-wp-theme.php.
References wp_cache_get().
Referenced by __construct(), get(), get_page_templates(), and get_screenshot().
display ($header, $markup = true, $translate = true)
Gets a theme header, formatted and translated for display.
Since
3.4.0 public
Parameters
string $header Theme header. Name, Description, Author, Version, ThemeURI, AuthorURI, Status, Tags.
bool $markup Optional. Whether to mark up the header. Defaults to true.
bool $translate Optional. Whether to translate the header. Defaults to true.
Returns
string|false Processed header, false on failure.
Definition at line 620 of file class-wp-theme.php.
References $value, load_textdomain(), markup_header(), and translate_header().
Referenced by __get(), __toString(), markup_header(), and offsetGet().
errors ()
Returns errors property.
Since
3.4.0 public
Returns
WP_Error|false WP_Error if there are errors, or false.
Definition at line 491 of file class-wp-theme.php.
References is_wp_error().
Referenced by __construct(), cache_delete(), exists(), get_page_templates(), and get_stylesheet_directory().
exists ()
Whether the theme exists.
A theme with errors exists. A theme with the error of 'theme_not_found', meaning that the theme's directory was not found, does not exist.
Since
3.4.0 public
Returns
bool Whether the theme exists.
Definition at line 506 of file class-wp-theme.php.
References errors().
get ($header)
Get a raw, unformatted theme header.
The header is sanitized, but is not translated, and is not marked up for display. To get a theme header for display, use the display() method.
Use the get_template() method, not the 'Template' header, for finding the template. The 'Template' header is only good for what was written in the style.css, while get_template() takes into account where WordPress actually located the theme and whether it is actually valid.
Since
3.4.0 public
Parameters
string $header Theme header. Name, Description, Author, Version, ThemeURI, AuthorURI, Status, Tags.
Returns
string|false String on success, false on failure.
Definition at line 584 of file class-wp-theme.php.
References cache_add(), cache_get(), and sanitize_header().
static get_allowed ($blog_id = null) static
Returns array of stylesheet names of themes allowed on the site or network.
Since
3.4.0
public
Parameters
int $blog_id Optional. Defaults to current blog.
Returns
array Array of stylesheet names.
Filter the array of themes allowed on the site or network.
Since
MU
Parameters
array $allowed_themes An array of theme stylesheet names.
Definition at line 1183 of file class-wp-theme.php.
References $blog_id, and apply_filters().
Referenced by wp_get_themes().
static get_allowed_on_network () static
Returns array of stylesheet names of themes allowed on the network.
Since
3.4.0
public
array $allowed_themes
Returns
array Array of stylesheet names.
Definition at line 1207 of file class-wp-theme.php.
References get_site_option().
Referenced by get_site_allowed_themes(), and wp_get_themes().
static get_allowed_on_site ($blog_id = null) static
Returns array of stylesheet names of themes allowed on the site.
Since
3.4.0
public
array $allowed_themes
Parameters
int $blog_id Optional. Defaults to current blog.
Returns
array Array of stylesheet names.
Definition at line 1227 of file class-wp-theme.php.
References $blog_id, $stylesheet, delete_option(), get_current_blog_id(), get_option(), is_admin(), is_multisite(), restore_current_blog(), switch_to_blog(), update_option(), and wp_get_themes().
Referenced by wp_get_themes(), and wpmu_get_blog_allowedthemes().
static get_core_default_theme () static
Determines the latest WordPress default theme that is installed.
This hits the filesystem.
Returns
WP_Theme|false Object, or false if no theme is installed, which would be bad.
Definition at line 1162 of file class-wp-theme.php.
References $name, $theme, and wp_get_theme().
Referenced by populate_network(), populate_options(), and validate_current_theme().
get_files ($type = null, $depth = 0, $search_parent = false)
Return files in the theme's directory.
Since
3.4.0 public
Parameters
mixed $type Optional. Array of extensions to return. Defaults to all files (null).
int $depth Optional. How deep to search for files. Defaults to a flat scan (0 depth). -1 depth is infinite.
bool $search_parent Optional. Whether to return parent files. Defaults to false.
Returns
array Array of files, keyed by the path to the file relative to the theme's directory, with the values being absolute paths.
Definition at line 975 of file class-wp-theme.php.
References get_stylesheet_directory(), get_template_directory(), and parent().
Referenced by get_page_templates(), and offsetGet().
get_page_templates ($post = null)
Returns the theme's page templates.
Since
3.4.0 public
Parameters
WP_Post | null $post Optional. The post being edited, provided for context.
Returns
array Array of page templates, keyed by filename, with the value of the translated header name.
Filter list of page templates for a theme.
Since
3.9.0
4.4.0 Converted to allow complete control over the $page_templates array.
Parameters
array $page_templates Array of page templates. Keys are filenames, values are translated names.
WP_Theme $this The theme object.
WP_Post | null $post The post being edited, provided for context, or null.
Definition at line 993 of file class-wp-theme.php.
References $file, $post, _cleanup_header_comment(), apply_filters(), cache_add(), cache_get(), errors(), get_files(), load_textdomain(), parent(), and translate_header().
get_screenshot ($uri = 'uri')
Returns the main screenshot file for the theme.
The main screenshot is called screenshot.png. gif and jpg extensions are also allowed.
Screenshots for a theme must be in the stylesheet directory. (In the case of child themes, parent theme screenshots are not inherited.)
Since
3.4.0 public
Parameters
string $uri Type of URL to return, either 'relative' or an absolute URI. Defaults to absolute URI.
Returns
string|false Screenshot file. False if the theme does not have a screenshot.
Definition at line 940 of file class-wp-theme.php.
References cache_add(), cache_get(), elseif, get_stylesheet_directory(), and get_stylesheet_directory_uri().
Referenced by __get(), and offsetGet().
get_stylesheet ()
The directory name of the theme's "stylesheet" files, inside the theme root.
In the case of a child theme, this is directory name of the child theme. Otherwise, get_stylesheet() is the same as get_template().
Since
3.4.0 public
Returns
string Stylesheet
Definition at line 802 of file class-wp-theme.php.
References $stylesheet.
Referenced by __get(), is_allowed(), markup_header(), and offsetGet().
get_stylesheet_directory ()
Returns the absolute path to the directory of a theme's "stylesheet" files.
In the case of a child theme, this is the absolute path to the directory of the child theme's files.
Since
3.4.0 public
Returns
string Absolute path of the stylesheet directory.
Definition at line 832 of file class-wp-theme.php.
References $stylesheet, and errors().
Referenced by __get(), get_files(), get_screenshot(), load_textdomain(), and offsetGet().
get_stylesheet_directory_uri ()
Returns the URL to the directory of a theme's "stylesheet" files.
In the case of a child theme, this is the URL to the directory of the child theme's files.
Since
3.4.0 public
Returns
string URL to the stylesheet directory.
Definition at line 870 of file class-wp-theme.php.
References get_theme_root_uri(), and str_replace.
Referenced by get_screenshot().
get_template ()
The directory name of the theme's "template" files, inside the theme root.
In the case of a child theme, this is the directory name of the parent theme. Otherwise, the get_template() is the same as get_stylesheet().
Since
3.4.0 public
Returns
string Template
Definition at line 817 of file class-wp-theme.php.
References $template.
Referenced by __get(), and offsetGet().
get_template_directory ()
Returns the absolute path to the directory of a theme's "template" files.
In the case of a child theme, this is the absolute path to the directory of the parent theme's files.
Since
3.4.0 public
Returns
string Absolute path of the template directory.
Definition at line 850 of file class-wp-theme.php.
References $template, $theme_root, and parent().
Referenced by __get(), get_files(), and offsetGet().
get_template_directory_uri ()
Returns the URL to the directory of a theme's "template" files.
In the case of a child theme, this is the URL to the directory of the parent theme's files.
Since
3.4.0 public
Returns
string URL to the template directory.
Definition at line 885 of file class-wp-theme.php.
References $theme_root_uri, get_theme_root_uri(), parent(), and str_replace.
get_theme_root ()
The absolute path to the directory of the theme root.
This is typically the absolute path to wp-content/themes.
Since
3.4.0 public
Returns
string Theme root.
Definition at line 904 of file class-wp-theme.php.
References $theme_root.
Referenced by __get(), and offsetGet().
get_theme_root_uri ()
Returns the URL to the directory of the theme root.
This is typically the absolute URL to wp-content/themes. This forms the basis for all other URLs returned by WP_Theme, so we pass it to the public function get_theme_root_uri() and allow it to run the theme_root_uri filter.
Since
3.4.0 public
Returns
string Theme root URI.
Definition at line 920 of file class-wp-theme.php.
References $theme_root_uri.
Referenced by __get(), get_stylesheet_directory_uri(), get_template_directory_uri(), and offsetGet().
is_allowed ($check = 'both', $blog_id = null)
Whether the theme is allowed (multisite only).
Since
3.4.0 public
Parameters
string $check Optional. Whether to check only the 'network'-wide settings, the 'site' settings, or 'both'. Defaults to 'both'.
int $blog_id Optional. Ignored if only network-wide settings are checked. Defaults to current blog.
Returns
bool Whether the theme is allowed for the network. Returns true in single-site.
Definition at line 1136 of file class-wp-theme.php.
References $blog_id, get_stylesheet(), and is_multisite().
load_textdomain ()
Loads the theme's textdomain.
Translation files are not inherited from the parent theme. Todo: if this fails for the child theme, it should probably try to load the parent theme's translations.
Since
3.4.0 public
Returns
bool True if the textdomain was successfully loaded or has already been loaded. False if no textdomain was specified in the file headers, or if the domain could not be loaded.
Definition at line 1100 of file class-wp-theme.php.
References $path, $textdomain_loaded, get_stylesheet_directory(), is_textdomain_loaded(), and load_theme_textdomain().
Referenced by display(), and get_page_templates().
markup_header ($header, $value, $translate) private
Mark up a theme header.
Since
3.4.0 private
string $comma
Parameters
string $header Theme header. Name, Description, Author, Version, ThemeURI, AuthorURI, Status, Tags.
string $value Value to mark up.
string $translate Whether the header has been translated.
Returns
string Value, marked up.
Definition at line 710 of file class-wp-theme.php.
References $value, __, display(), elseif, esc_url, get_stylesheet(), null, and wptexturize().
Referenced by display().
offsetExists ($offset)
Method to implement ArrayAccess for keys formerly returned by get_themes()
array $keys
Parameters
mixed $offset
Returns
bool
Definition at line 415 of file class-wp-theme.php.
References $keys.
offsetGet ($offset)
Method to implement ArrayAccess for keys formerly returned by get_themes().
Author, Author Name, Author URI, and Description did not previously return translated data. We are doing so now as it is safe to do. However, as Name and Title could have been used as the key for get_themes(), both remain untranslated for back compatibility. This means that ['Name'] is not ideal, and care should be taken to use $theme->display('Name') to get a properly translated header.
Parameters
mixed $offset
Returns
mixed
Definition at line 438 of file class-wp-theme.php.
References display(), get_files(), get_screenshot(), get_stylesheet(), get_stylesheet_directory(), get_template(), get_template_directory(), get_theme_root(), get_theme_root_uri(), null, and parent().
Referenced by __get().
offsetSet ($offset, $value)
Method to implement ArrayAccess for keys formerly returned by get_themes()
Parameters
mixed $offset
mixed $value
Definition at line 398 of file class-wp-theme.php.
offsetUnset ($offset)
Method to implement ArrayAccess for keys formerly returned by get_themes()
Parameters
mixed $offset
Definition at line 405 of file class-wp-theme.php.
parent ()
Returns reference to the parent theme.
Since
3.4.0 public
Returns
WP_Theme|false Parent theme, or false if the current theme is not a child theme.
Definition at line 518 of file class-wp-theme.php.
Referenced by __construct(), __get(), cache_delete(), get_files(), get_page_templates(), get_template_directory(), get_template_directory_uri(), and offsetGet().
sanitize_header ($header, $value) private
Sanitize a theme header.
Since
3.4.0 private
array $header_tags array $header_tags_with_a
Parameters
string $header Theme header. Name, Description, Author, Version, ThemeURI, AuthorURI, Status, Tags.
string $value Value to sanitize.
Returns
mixed
Definition at line 651 of file class-wp-theme.php.
References $value, esc_url_raw(), and wp_kses().
Referenced by get().
static scandir ($path, $extensions = null, $depth = 0, $relative_path = '') static private
Scans a directory for files of a certain extension.
Since
3.4.0
private
Parameters
string $path Absolute path to search.
array | string | null $extensions Optional. Array of extensions to find, string of a single extension, or null for all extensions. Default null.
int $depth Optional. How many levels deep to search for files. Accepts 0, 1+, or -1 (infinite depth). Default 0.
string $relative_path Optional. The basename of the absolute path. Used to control the returned path for the found files, particularly when this function recurses to lower depths. Default empty.
Returns
array|false Array of files, keyed by the path to the file relative to the $path directory prepended with $relative_path, with the values being absolute paths. False otherwise.
Definition at line 1056 of file class-wp-theme.php.
References $path, elseif, and trailingslashit().
static sort_by_name (& $themes) static
Sort themes by name.
Since
3.4.0
public
Definition at line 1293 of file class-wp-theme.php.
References get_locale().
Referenced by WP_Themes_List_Table\prepare_items(), WP_MS_Themes_List_Table\prepare_items(), and wp_prepare_themes_for_js().
translate_header ($header, $value) private
Translate a theme header.
Since
3.4.0 private
array $tags_list
Parameters
string $header Theme header. Name, Description, Author, Version, ThemeURI, AuthorURI, Status, Tags.
string $value Value to translate.
Returns
string Translated value.
Definition at line 755 of file class-wp-theme.php.
References $feature_list, $name_translated, $tags, $tags_list, $value, elseif, get_theme_feature_list(), and translate().
Referenced by display(), and get_page_templates().
Field Documentation
$cache_expiration = 1800 static private
Definition at line 190 of file class-wp-theme.php.
$cache_hash private
Definition at line 168 of file class-wp-theme.php.
$default_themes static private
Initial value:
= array(
        'classic'        => 'WordPress Classic',
        'default'        => 'WordPress Default',
        'twentyten'      => 'Twenty Ten',
        'twentyeleven'   => 'Twenty Eleven',
        'twentytwelve'   => 'Twenty Twelve',
        'twentythirteen' => 'Twenty Thirteen',
        'twentyfourteen' => 'Twenty Fourteen',
        'twentyfifteen'  => 'Twenty Fifteen',
        'twentysixteen'  => 'Twenty Sixteen',
    )
Definition at line 50 of file class-wp-theme.php.
$errors private
Definition at line 114 of file class-wp-theme.php.
$file_headers static private
Initial value:
= array(
        'Name'        => 'Theme Name',
        'ThemeURI'    => 'Theme URI',
        'Description' => 'Description',
        'Author'      => 'Author',
        'AuthorURI'   => 'Author URI',
        'Version'     => 'Version',
        'Template'    => 'Template',
        'Status'      => 'Status',
        'Tags'        => 'Tags',
        'TextDomain'  => 'Text Domain',
        'DomainPath'  => 'Domain Path',
    )
Definition at line 29 of file class-wp-theme.php.
$headers = array() private
Definition at line 88 of file class-wp-theme.php.
$headers_sanitized private
Definition at line 96 of file class-wp-theme.php.
$name_translated private
Definition at line 106 of file class-wp-theme.php.
Referenced by translate_header().
$parent private
Definition at line 144 of file class-wp-theme.php.
$persistently_cache static private
Definition at line 179 of file class-wp-theme.php.
$stylesheet private
Definition at line 125 of file class-wp-theme.php.
Referenced by __construct(), get_allowed_on_site(), get_stylesheet(), and get_stylesheet_directory().
$tag_map static private
Initial value:
= array(
        'fixed-width'    => 'fixed-layout',
        'flexible-width' => 'fluid-layout',
    )
Definition at line 69 of file class-wp-theme.php.
$template private
Definition at line 136 of file class-wp-theme.php.
Referenced by __construct(), get_template(), and get_template_directory().
$textdomain_loaded private
Definition at line 160 of file class-wp-theme.php.
Referenced by load_textdomain().
$theme_root private
Definition at line 80 of file class-wp-theme.php.
Referenced by __construct(), get_template_directory(), and get_theme_root().
$theme_root_uri private
URL to the theme root, usually an absolute URL to wp-content/themes.
private var string
Definition at line 152 of file class-wp-theme.php.
Referenced by get_template_directory_uri(), and get_theme_root_uri().
$update = false
Definition at line 20 of file class-wp-theme.php.
The documentation for this class was generated from the following file:
class-wp-theme.php