GravityView: WP_Comment Class Reference
WP_Comment Class Reference
Core class used to organize comments as instantiated objects with defined members.
Public Member Functions
__construct ($comment)
Constructor.
__get ($name)
Magic getter.
__isset ($name)
Check whether a non-public property is set.
add_child (WP_Comment $child)
Add a child to the comment.
get_child ($child_id)
Get a child comment by ID.
get_children ($args=array())
Get the children of a comment.
populated_children ($set)
Set the 'populated_children' flag.
to_array ()
Convert object to array.
Static Public Member Functions
static get_instance ($id)
Retrieves a WP_Comment instance.
Data Fields
$comment_agent = ''
$comment_approved = '1'
$comment_author = ''
$comment_author_email = ''
$comment_author_IP = ''
$comment_author_url = ''
$comment_content
$comment_date = '0000-00-00 00:00:00'
$comment_date_gmt = '0000-00-00 00:00:00'
$comment_ID
$comment_karma = 0
$comment_parent = 0
$comment_post_ID = 0
$comment_type = ''
$user_id = 0
Protected Attributes
$children
$populated_children = false
$post_fields = array('post_author', 'post_date', 'post_date_gmt', 'post_content', 'post_title', 'post_excerpt', 'post_status', 'comment_status', 'ping_status', 'post_name', 'to_ping', 'pinged', 'post_modified', 'post_modified_gmt', 'post_content_filtered', 'post_parent', 'guid', 'menu_order', 'post_type', 'post_mime_type', 'comment_count')
Detailed Description
Core class used to organize comments as instantiated objects with defined members.
Since
4.4.0
Definition at line 15 of file class-wp-comment.php.
Constructor & Destructor Documentation
__construct ($comment)
Constructor.
Populates properties with object vars.
Since
4.4.0 public
Parameters
WP_Comment $comment Comment object.
Definition at line 224 of file class-wp-comment.php.
References $comment, and $value.
Member Function Documentation
__get ($name)
Magic getter.
If $name matches a post field, the comment post will be loaded and the post's value returned.
Since
4.4.0 public
Parameters
string $name
Returns
mixed
Definition at line 389 of file class-wp-comment.php.
References $name, $post, and get_post().
__isset ($name)
Check whether a non-public property is set.
If $name matches a post field, the comment post will be loaded and the post's value checked.
Since
4.4.0 public
Parameters
string $name Property name.
Returns
bool
Definition at line 371 of file class-wp-comment.php.
References $name, $post, and get_post().
add_child (WP_Comment $child)
Add a child to the comment.
Used by WP_Comment_Query when bulk-filling descendants.
Since
4.4.0 public
Parameters
WP_Comment $child Child comment.
Definition at line 325 of file class-wp-comment.php.
get_child ($child_id)
Get a child comment by ID.
Since
4.4.0 public
Parameters
int $child_id ID of the child.
Returns
WP_Comment|bool Returns the comment object if found, otherwise false.
Definition at line 338 of file class-wp-comment.php.
get_children ($args = array())
Get the children of a comment.
Since
4.4.0 public
Parameters
array $args { Array of arguments used to pass to get_comments() and determine format.
string $format Return value format. 'tree' for a hierarchical tree, 'flat' for a flattened array. Default 'tree'. string $status Comment status to limit results by. Accepts 'hold' (comment_status=0), 'approve' (comment_status=1), 'all', or a custom comment status. Default 'all'. string $hierarchical Whether to include comment descendants in the results. 'threaded' returns a tree, with each comment's children stored in a children property on the WP_Comment object. 'flat' returns a flat array of found comments plus their children. Pass false to leave out descendants. The parameter is ignored (forced to false) when $fields is 'ids' or 'counts'. Accepts 'threaded', 'flat', or false. Default: 'threaded'. string|array $orderby Comment status or array of statuses. To use 'meta_value' or 'meta_value_num', $meta_key must also be defined. To sort by a specific $meta_query clause, use that clause's array key. Accepts 'comment_agent', 'comment_approved', 'comment_author', 'comment_author_email', 'comment_author_IP', 'comment_author_url', 'comment_content', 'comment_date', 'comment_date_gmt', 'comment_ID', 'comment_karma', 'comment_parent', 'comment_post_ID', 'comment_type', 'user_id', 'comment__in', 'meta_value', 'meta_value_num', the value of $meta_key, and the array keys of $meta_query. Also accepts false, an empty array, or 'none' to disable ORDER BY clause. }
Returns
array Array of WP_Comment objects.
Definition at line 279 of file class-wp-comment.php.
References $children, $comment_ID, get_comments(), populated_children(), and wp_parse_args().
static get_instance ($id) static
Retrieves a WP_Comment instance.
Since
4.4.0 public
wpdb $wpdb WordPress database abstraction object.
Parameters
int $id Comment ID.
Returns
WP_Comment|false Comment object, otherwise false.
Definition at line 191 of file class-wp-comment.php.
References $id, $wpdb, wp_cache_add(), and wp_cache_get().
Referenced by get_comment().
populated_children ($set)
Set the 'populated_children' flag.
This flag is important for ensuring that calling get_children() on a childless comment will not trigger unneeded database queries.
Since
4.4.0
Parameters
bool $set Whether the comment's children have already been populated.
Definition at line 356 of file class-wp-comment.php.
Referenced by get_children().
to_array ()
Convert object to array.
Since
4.4.0 public
Returns
array Object as array.
Definition at line 238 of file class-wp-comment.php.
Field Documentation
$children protected
Definition at line 159 of file class-wp-comment.php.
Referenced by get_children().
$comment_agent = ''
Definition at line 123 of file class-wp-comment.php.
$comment_approved = '1'
Definition at line 114 of file class-wp-comment.php.
$comment_author = ''
Definition at line 42 of file class-wp-comment.php.
$comment_author_email = ''
Definition at line 51 of file class-wp-comment.php.
$comment_author_IP = ''
Definition at line 69 of file class-wp-comment.php.
$comment_author_url = ''
Definition at line 60 of file class-wp-comment.php.
$comment_content
Definition at line 96 of file class-wp-comment.php.
$comment_date = '0000-00-00 00:00:00'
Definition at line 78 of file class-wp-comment.php.
$comment_date_gmt = '0000-00-00 00:00:00'
Definition at line 87 of file class-wp-comment.php.
$comment_ID
Definition at line 24 of file class-wp-comment.php.
Referenced by get_children().
$comment_karma = 0
Definition at line 105 of file class-wp-comment.php.
$comment_parent = 0
Definition at line 141 of file class-wp-comment.php.
$comment_post_ID = 0
Definition at line 33 of file class-wp-comment.php.
$comment_type = ''
Definition at line 132 of file class-wp-comment.php.
$populated_children = false protected
Definition at line 168 of file class-wp-comment.php.
$post_fields = array('post_author', 'post_date', 'post_date_gmt', 'post_content', 'post_title', 'post_excerpt', 'post_status', 'comment_status', 'ping_status', 'post_name', 'to_ping', 'pinged', 'post_modified', 'post_modified_gmt', 'post_content_filtered', 'post_parent', 'guid', 'menu_order', 'post_type', 'post_mime_type', 'comment_count') protected
Definition at line 177 of file class-wp-comment.php.
$user_id = 0
Definition at line 150 of file class-wp-comment.php.
The documentation for this class was generated from the following file:
class-wp-comment.php