GravityView: Automatic_Upgrader_Skin Class Reference
Automatic_Upgrader_Skin Class Reference
Public Member Functions
feedback ($data)
footer ()
public
get_upgrade_messages ()
public
header ()
public
request_filesystem_credentials ($error=false, $context= '', $allow_relaxed_file_ownership=false)
Public Member Functions inherited from WP_Upgrader_Skin
__construct ($args=array())
add_strings ()
public
after ()
public
before ()
public
bulk_footer ()
public
bulk_header ()
public
error ($errors)
feedback ($string)
footer ()
public
header ()
public
request_filesystem_credentials ($error=false, $context=false, $allow_relaxed_file_ownership=false)
set_result ($result)
set_upgrader (&$upgrader)
Protected Attributes
$messages = array()
Additional Inherited Members
Data Fields inherited from WP_Upgrader_Skin
$done_footer = false
$done_header = false
$options = array()
$result = false
$upgrader
Protected Member Functions inherited from WP_Upgrader_Skin
decrement_update_count ($type)
Output JavaScript that calls function to decrement the update counts.
Detailed Description
Definition at line 861 of file class-wp-upgrader-skins.php.
Member Function Documentation
feedback ($data)
Parameters
string | array | WP_Error $data
Definition at line 895 of file class-wp-upgrader-skins.php.
References elseif, is_wp_error(), and wp_kses().
footer ()
public
Definition at line 941 of file class-wp-upgrader-skins.php.
References $output, and Bulk_Upgrader_Skin\feedback().
get_upgrade_messages ()
public
Returns
array
Definition at line 888 of file class-wp-upgrader-skins.php.
References $messages.
header ()
public
Definition at line 934 of file class-wp-upgrader-skins.php.
request_filesystem_credentials ($error = false, $context = '', $allow_relaxed_file_ownership = false)
Parameters
bool $error
string $context
bool $allow_relaxed_file_ownership
Returns
bool
Definition at line 871 of file class-wp-upgrader-skins.php.
Field Documentation
$messages = array() protected
Definition at line 862 of file class-wp-upgrader-skins.php.
The documentation for this class was generated from the following file:
class-wp-upgrader-skins.php