GravityView: getid3_ac3 Class Reference
getid3_ac3 Class Reference
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Public Member Functions
Analyze ()
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Static Public Member Functions
static audioCodingModeLookup ($acmod)
static bitrateLookup ($frmsizecod)
static centerMixLevelLookup ($cmixlev)
static channelsEnabledLookup ($acmod, $lfeon)
static dolbySurroundModeLookup ($dsurmod)
static frameSizeLookup ($frmsizecod, $fscod)
static heavyCompression ($compre)
static roomTypeLookup ($roomtyp)
static sampleRateCodeLookup ($fscod)
static serviceTypeLookup ($bsmod, $acmod)
static surroundMixLevelLookup ($surmixlev)
Data Fields
const syncword = "\x0B\x77"
Private Member Functions
readHeaderBSI ($length)
Private Attributes
$AC3header = array()
$BSIoffset = 0
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Definition at line 18 of file module.audio.ac3.php.
Member Function Documentation
Analyze ()
AH
Definition at line 25 of file module.audio.ac3.php.
References $value, getid3_lib\BigEndian2Bin(), getid3_handler\error(), getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\isDependencyFor(), getid3_lib\LittleEndian2Int(), getid3_lib\PrintHexBytes(), and readHeaderBSI().
static audioCodingModeLookup ($acmod) static
Definition at line 275 of file module.audio.ac3.php.
static bitrateLookup ($frmsizecod) static
Definition at line 446 of file module.audio.ac3.php.
static centerMixLevelLookup ($cmixlev) static
Definition at line 290 of file module.audio.ac3.php.
static channelsEnabledLookup ($acmod, $lfeon) static
Definition at line 326 of file module.audio.ac3.php.
static dolbySurroundModeLookup ($dsurmod) static
Definition at line 316 of file module.audio.ac3.php.
static frameSizeLookup ($frmsizecod, $fscod) static
Definition at line 411 of file module.audio.ac3.php.
static heavyCompression ($compre) static
Definition at line 351 of file module.audio.ac3.php.
References getid3_lib\RGADamplitude2dB().
readHeaderBSI ($length) private
Definition at line 237 of file module.audio.ac3.php.
Referenced by Analyze().
static roomTypeLookup ($roomtyp) static
Definition at line 401 of file module.audio.ac3.php.
static sampleRateCodeLookup ($fscod) static
Definition at line 244 of file module.audio.ac3.php.
static serviceTypeLookup ($bsmod, $acmod) static
Definition at line 254 of file module.audio.ac3.php.
References $i.
static surroundMixLevelLookup ($surmixlev) static
Definition at line 303 of file module.audio.ac3.php.
Field Documentation
$AC3header = array() private
Definition at line 20 of file module.audio.ac3.php.
$BSIoffset = 0 private
Definition at line 21 of file module.audio.ac3.php.
const syncword = "\x0B\x77"
Definition at line 23 of file module.audio.ac3.php.
Referenced by getid3_riff\ParseRIFF().
The documentation for this class was generated from the following file:
module.audio.ac3.php