GravityView: wp_xmlrpc_server Class Reference
wp_xmlrpc_server Class Reference
Public Member Functions
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ()
Register all of the XMLRPC methods that XMLRPC server understands.
_getOptions ($options)
Retrieve blog options value from list.
add_enclosure_if_new ($post_ID, $enclosure)
Adds an enclosure to a post if it's new.
addTwoNumbers ($args)
Test XMLRPC API by adding two numbers for client.
attach_uploads ($post_ID, $post_content)
Attach upload to a post.
blogger_deletePost ($args)
Remove a post.
blogger_editPost ($args)
Edit a post.
blogger_getPost ($args)
Retrieve post.
blogger_getRecentPosts ($args)
Retrieve list of recent posts.
blogger_getTemplate ($args)
Deprecated.
blogger_getUserInfo ($args)
Retrieve user's data.
blogger_getUsersBlogs ($args)
Retrieve blogs that user owns.
blogger_newPost ($args)
Creates new post.
blogger_setTemplate ($args)
Deprecated.
escape (&$data)
Escape string or array of strings for database.
get_custom_fields ($post_id)
Retrieve custom fields for post.
initialise_blog_option_info ()
Set up blog options property.
login ($username, $password)
Log user in.
login_pass_ok ($username, $password)
Check user's credentials.
mt_getCategoryList ($args)
Retrieve list of all categories on blog.
mt_getPostCategories ($args)
Retrieve post categories.
mt_getRecentPostTitles ($args)
Retrieve the post titles of recent posts.
mt_getTrackbackPings ($post_ID)
Retrieve trackbacks sent to a given post.
mt_publishPost ($args)
Sets a post's publish status to 'publish'.
mt_setPostCategories ($args)
Sets categories for a post.
mt_supportedMethods ()
Retrieve an array of methods supported by this server.
mt_supportedTextFilters ()
Retrieve an empty array because we don't support per-post text filters.
mw_editPost ($args)
Edit a post.
mw_getCategories ($args)
Retrieve the list of categories on a given blog.
mw_getPost ($args)
Retrieve post.
mw_getRecentPosts ($args)
Retrieve list of recent posts.
mw_newMediaObject ($args)
Uploads a file, following your settings.
mw_newPost ($args)
Create a new post.
pingback_extensions_getPingbacks ($url)
Retrieve array of URLs that pingbacked the given URL.
pingback_ping ($args)
Retrieves a pingback and registers it.
sayHello ()
Test XMLRPC API by saying, "Hello!" to client.
serve_request ()
Serves the XML-RPC request.
set_custom_fields ($post_id, $fields)
Set custom fields for post.
wp_deleteCategory ($args)
Remove category.
wp_deleteComment ($args)
Delete a comment.
wp_deletePage ($args)
Delete page.
wp_deletePost ($args)
Delete a post for any registered post type.
wp_deleteTerm ($args)
Delete a term.
wp_editComment ($args)
Edit comment.
wp_editPage ($args)
Edit page.
wp_editPost ($args)
Edit a post for any registered post type.
wp_editProfile ($args)
Edit user's profile.
wp_editTerm ($args)
Edit a term.
wp_getAuthors ($args)
Retrieve authors list.
wp_getComment ($args)
Retrieve comment.
wp_getCommentCount ($args)
Retrieve comment count.
wp_getComments ($args)
Retrieve comments.
wp_getCommentStatusList ($args)
Retrieve all of the comment status.
wp_getMediaItem ($args)
Retrieve a media item by ID.
wp_getMediaLibrary ($args)
Retrieves a collection of media library items (or attachments)
wp_getOptions ($args)
Retrieve blog options.
wp_getPage ($args)
Retrieve page.
wp_getPageList ($args)
Retrieve page list.
wp_getPages ($args)
Retrieve Pages.
wp_getPageStatusList ($args)
Retrieve page statuses.
wp_getPageTemplates ($args)
Retrieve page templates.
wp_getPost ($args)
Retrieve a post.
wp_getPostFormats ($args)
Retrieves a list of post formats used by the site.
wp_getPosts ($args)
Retrieve posts.
wp_getPostStatusList ($args)
Retrieve post statuses.
wp_getPostType ($args)
Retrieves a post type.
wp_getPostTypes ($args)
Retrieves a post types.
wp_getProfile ($args)
Retrieve information about the requesting user.
wp_getRevisions ($args)
Retrieve revisions for a specific post.
wp_getTags ($args)
Get list of all tags.
wp_getTaxonomies ($args)
Retrieve all taxonomies.
wp_getTaxonomy ($args)
Retrieve a taxonomy.
wp_getTerm ($args)
Retrieve a term.
wp_getTerms ($args)
Retrieve all terms for a taxonomy.
wp_getUser ($args)
Retrieve a user.
wp_getUsers ($args)
Retrieve users.
wp_getUsersBlogs ($args)
Retrieve the blogs of the user.
wp_newCategory ($args)
Create new category.
wp_newComment ($args)
Create new comment.
wp_newPage ($args)
Create new page.
wp_newPost ($args)
Create a new post for any registered post type.
wp_newTerm ($args)
Create a new term.
wp_restoreRevision ($args)
Restore a post revision.
wp_setOptions ($args)
Update blog options.
wp_suggestCategories ($args)
Retrieve category list.
Public Member Functions inherited from IXR_Server
__construct ($callbacks=false, $data=false, $wait=false)
PHP5 constructor.
call ($methodname, $args)
error ($error, $message=false)
getCapabilities ($args)
hasMethod ($method)
IXR_Server ($callbacks=false, $data=false, $wait=false)
PHP4 constructor.
listMethods ($args)
multiCall ($methodcalls)
output ($xml)
serve ($data=false)
setCallbacks ()
setCapabilities ()
Data Fields
$blog_options
$error
$methods
Data Fields inherited from IXR_Server
$callbacks = array()
$capabilities
$data
$message
Protected Member Functions
_convert_date ($date)
Convert a WordPress date string to an IXR_Date object.
_convert_date_gmt ($date_gmt, $date)
Convert a WordPress GMT date string to an IXR_Date object.
_insert_post ($user, $content_struct)
Helper method for wp_newPost() and wp_editPost(), containing shared logic.
_multisite_getUsersBlogs ($args)
Private function for retrieving a users blogs for multisite setups.
_prepare_comment ($comment)
Prepares comment data for return in an XML-RPC object.
_prepare_media_item ($media_item, $thumbnail_size= 'thumbnail')
Prepares media item data for return in an XML-RPC object.
_prepare_page ($page)
Prepares page data for return in an XML-RPC object.
_prepare_post ($post, $fields)
Prepares post data for return in an XML-RPC object.
_prepare_post_type ($post_type, $fields)
Prepares post data for return in an XML-RPC object.
_prepare_taxonomy ($taxonomy, $fields)
Prepares taxonomy data for return in an XML-RPC object.
_prepare_term ($term)
Prepares term data for return in an XML-RPC object.
_prepare_user ($user, $fields)
Prepares user data for return in an XML-RPC object.
minimum_args ($args, $count)
Checks if the method received at least the minimum number of arguments.
pingback_error ($code, $message)
Sends a pingback error based on the given error code and message.
Protected Attributes
$auth_failed = false
Private Member Functions
_is_greater_than_one ($count)
Helper method for filtering out elements from an array.
_toggle_sticky ($post_data, $update=false)
Encapsulate the logic for sticking a post and determining if the user has permission to do so.
Detailed Description
Definition at line 23 of file class-wp-xmlrpc-server.php.
Constructor & Destructor Documentation
__construct ()
Register all of the XMLRPC methods that XMLRPC server understands.
Sets up server and method property. Passes XMLRPC methods through the 'xmlrpc_methods' filter to allow plugins to extend or replace XMLRPC methods.
Since
1.5.0
Filter the methods exposed by the XML-RPC server.
This filter can be used to add new methods, and remove built-in methods.
Since
1.5.0
Parameters
array $methods An array of XML-RPC methods.
Definition at line 65 of file class-wp-xmlrpc-server.php.
References apply_filters(), initialise_blog_option_info(), and methods.
Member Function Documentation
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
Since
4.0.0 public
Parameters
callable $name Method to call.
array $arguments Arguments to pass when calling.
Returns
array|IXR_Error|false Return value of the callback, false otherwise.
Definition at line 183 of file class-wp-xmlrpc-server.php.
References $name.
_convert_date ($date) protected
Convert a WordPress date string to an IXR_Date object.
protected
Parameters
string $date Date string to convert.
Returns
IXR_Date IXR_Date object.
Definition at line 746 of file class-wp-xmlrpc-server.php.
References mysql2date().
Referenced by _convert_date_gmt(), _prepare_page(), _prepare_post(), blogger_getPost(), blogger_getRecentPosts(), mt_getRecentPostTitles(), mw_getPost(), mw_getRecentPosts(), wp_editPost(), wp_getPageList(), and wp_newPost().
_convert_date_gmt ($date_gmt, $date) protected
Convert a WordPress GMT date string to an IXR_Date object.
protected
Parameters
string $date_gmt WordPress GMT date string.
string $date Date string.
Returns
IXR_Date IXR_Date object.
Definition at line 762 of file class-wp-xmlrpc-server.php.
References _convert_date(), get_gmt_from_date(), and mysql2date().
Referenced by _prepare_comment(), _prepare_page(), _prepare_post(), mt_getRecentPostTitles(), mw_getPost(), mw_getRecentPosts(), and wp_getPageList().
_getOptions ($options)
Retrieve blog options value from list.
Since
2.6.0
Parameters
array $options Options to retrieve.
Returns
array
Definition at line 3807 of file class-wp-xmlrpc-server.php.
References IXR_Server\$data, $option, $options, current_user_can(), and get_option().
Referenced by wp_getOptions(), and wp_setOptions().
_insert_post ($user, $content_struct) protected
Helper method for wp_newPost() and wp_editPost(), containing shared logic.
Since
3.4.0 protected
See also
wp_insert_post()
Parameters
WP_User $user The post author if post_author isn't set in $content_struct.
array | IXR_Error $content_struct Post data to insert.
Returns
IXR_Error|string
Filter post data array to be inserted via XML-RPC.
Since
3.4.0
Parameters
array $post_data Parsed array of post data.
array $content_struct Post data array.
Definition at line 1281 of file class-wp-xmlrpc-server.php.
References $error, $format, $post_ID, $post_type, $update, $user, __, _toggle_sticky(), absint(), add_enclosure_if_new(), apply_filters(), attach_uploads(), current_user_can(), delete_post_thumbnail(), elseif, get_date_from_gmt(), get_default_post_to_edit(), get_object_taxonomies(), get_post(), get_post_status_object(), get_post_type(), get_post_type_object(), get_term_by(), get_terms(), is_taxonomy_hierarchical(), is_wp_error(), iso8601_to_datetime(), null, set_custom_fields(), set_post_format(), set_post_thumbnail(), wp_insert_post(), wp_insert_term(), wp_parse_args(), and wp_update_post().
Referenced by wp_editPost(), and wp_newPost().
_is_greater_than_one ($count) private
Helper method for filtering out elements from an array.
Since
3.4.0
Parameters
int $count Number to compare to one.
Definition at line 1227 of file class-wp-xmlrpc-server.php.
References $count.
_multisite_getUsersBlogs ($args) protected
Private function for retrieving a users blogs for multisite setups.
Since
3.0.0 protected
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
string $username Username. string $password Password. }
Returns
array|IXR_Error
Definition at line 4344 of file class-wp-xmlrpc-server.php.
References $_SERVER, $blog, $blogs, $current_blog, $path, get_blog_details(), and set_url_scheme().
Referenced by blogger_getUsersBlogs().
_prepare_comment ($comment) protected
Prepares comment data for return in an XML-RPC object.
protected
Parameters
object $comment The unprepared comment data.
Returns
array The prepared comment data.
Filter XML-RPC-prepared data for the given comment.
Since
3.4.0
Parameters
array $_comment An array of prepared comment data.
WP_Comment $comment Comment object.
Definition at line 1047 of file class-wp-xmlrpc-server.php.
References $comment, _convert_date_gmt(), apply_filters(), elseif, get_comment_link(), and get_the_title().
Referenced by wp_getComment(), and wp_getComments().
_prepare_media_item ($media_item, $thumbnail_size = 'thumbnail') protected
Prepares media item data for return in an XML-RPC object.
protected
Parameters
object $media_item The unprepared media item data.
string $thumbnail_size The image size to use for the thumbnail URL.
Returns
array The prepared media item data.
Filter XML-RPC-prepared data for the given media item.
Since
3.4.0
Parameters
array $_media_item An array of media item data.
object $media_item Media item object.
string $thumbnail_size Image size.
Definition at line 927 of file class-wp-xmlrpc-server.php.
References apply_filters(), image_downsize(), wp_get_attachment_metadata(), and wp_get_attachment_url().
Referenced by _prepare_post(), mw_newMediaObject(), wp_getMediaItem(), and wp_getMediaLibrary().
_prepare_page ($page) protected
Prepares page data for return in an XML-RPC object.
protected
Parameters
object $page The unprepared page data.
Returns
array The prepared page data.
Filter XML-RPC-prepared data for the given page.
Since
3.4.0
Parameters
array $_page An array of page data.
WP_Post $page Page object.
Definition at line 966 of file class-wp-xmlrpc-server.php.
References $link, $page, _convert_date(), _convert_date_gmt(), apply_filters(), comments_open(), get_cat_name(), get_extended(), get_page_template_slug(), get_permalink(), get_post(), is_object_in_taxonomy(), pings_open(), and wp_get_post_categories().
Referenced by wp_getPage(), and wp_getPages().
_prepare_post ($post, $fields) protected
Prepares post data for return in an XML-RPC object.
protected
Parameters
array $post The unprepared post data.
array $fields The subset of post type fields to return.
Returns
array The prepared post data.
Filter XML-RPC-prepared date for the given post.
Since
3.4.0
Parameters
array $_post An array of modified post data.
array $post An array of post data.
array $fields An array of post fields.
Definition at line 778 of file class-wp-xmlrpc-server.php.
References $post, $thumbnail_id, _convert_date(), _convert_date_gmt(), _prepare_media_item(), _prepare_term(), apply_filters(), current_theme_supports(), get_custom_fields(), get_object_taxonomies(), get_permalink(), get_post(), get_post_format(), get_post_meta(), get_post_thumbnail_id(), is_sticky(), and wp_get_object_terms().
Referenced by wp_getPost(), wp_getPosts(), and wp_getRevisions().
_prepare_post_type ($post_type, $fields) protected
Prepares post data for return in an XML-RPC object.
protected
Parameters
object $post_type Post type object.
array $fields The subset of post fields to return.
Returns
array The prepared post type data.
Filter XML-RPC-prepared date for the given post type.
Since
3.4.0
Parameters
array $_post_type An array of post type data.
object $post_type Post type object.
Definition at line 877 of file class-wp-xmlrpc-server.php.
References $post_type, apply_filters(), get_all_post_type_supports(), and get_object_taxonomies().
Referenced by wp_getPostType(), and wp_getPostTypes().
_prepare_taxonomy ($taxonomy, $fields) protected
Prepares taxonomy data for return in an XML-RPC object.
protected
Parameters
object $taxonomy The unprepared taxonomy data.
array $fields The subset of taxonomy fields to return.
Returns
array The prepared taxonomy data.
Filter XML-RPC-prepared data for the given taxonomy.
Since
3.4.0
Parameters
array $_taxonomy An array of taxonomy data.
object $taxonomy Taxonomy object.
array $fields The subset of taxonomy fields to return.
Definition at line 671 of file class-wp-xmlrpc-server.php.
References apply_filters(), and if.
Referenced by wp_getTaxonomies(), and wp_getTaxonomy().
_prepare_term ($term) protected
Prepares term data for return in an XML-RPC object.
protected
Parameters
array | object $term The unprepared term data.
Returns
array The prepared term data.
Filter XML-RPC-prepared data for the given term.
Since
3.4.0
Parameters
array $_term An array of term data.
array | object $term Term object or array.
Definition at line 713 of file class-wp-xmlrpc-server.php.
References apply_filters().
Referenced by _prepare_post(), wp_getTerm(), and wp_getTerms().
_prepare_user ($user, $fields) protected
Prepares user data for return in an XML-RPC object.
protected
Parameters
WP_User $user The unprepared user object.
array $fields The subset of user fields to return.
Returns
array The prepared user data.
Filter XML-RPC-prepared data for the given user.
Since
3.5.0
Parameters
array $_user An array of user data.
WP_User $user User object.
array $fields An array of user fields.
Definition at line 1097 of file class-wp-xmlrpc-server.php.
References $user, and apply_filters().
Referenced by wp_getProfile(), wp_getUser(), and wp_getUsers().
_toggle_sticky ($post_data, $update = false) private
Encapsulate the logic for sticking a post and determining if the user has permission to do so.
Since
4.3.0 private
Parameters
array $post_data
bool $update
Returns
void|IXR_Error
Definition at line 1242 of file class-wp-xmlrpc-server.php.
References $post_type, $sticky, $update, __, current_user_can(), elseif, get_post_type_object(), stick_post(), unstick_post(), and wp_validate_boolean().
Referenced by _insert_post(), mw_editPost(), and mw_newPost().
add_enclosure_if_new ($post_ID, $enclosure)
Adds an enclosure to a post if it's new.
Since
2.8.0
Parameters
integer $post_ID Post ID.
array $enclosure Enclosure data.
Definition at line 5089 of file class-wp-xmlrpc-server.php.
References $post_ID, add_post_meta(), and get_post_meta().
Referenced by _insert_post(), mw_editPost(), and mw_newPost().
addTwoNumbers ($args)
Test XMLRPC API by adding two numbers for client.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $number1 A number to add. int $number2 A second number to add. }
Returns
int Sum of the two given numbers.
Definition at line 224 of file class-wp-xmlrpc-server.php.
attach_uploads ($post_ID, $post_content)
Attach upload to a post.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_ID Post ID.
string $post_content Post Content for attachment.
Definition at line 5117 of file class-wp-xmlrpc-server.php.
References $attachments, $file, $post_ID, and $wpdb.
Referenced by _insert_post(), blogger_editPost(), blogger_newPost(), mw_editPost(), and mw_newPost().
blogger_deletePost ($args)
Remove a post.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) int $post_ID string $username string $password }
Returns
true|IXR_Error True when post is deleted.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a post has been successfully deleted via the XML-RPC Blogger API.
Since
3.4.0
Parameters
int $post_ID ID of the deleted post.
array $args An array of arguments to delete the post.
Definition at line 4717 of file class-wp-xmlrpc-server.php.
References $post_ID, $user, __, ARRAY_A, current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), login(), and wp_delete_post().
blogger_editPost ($args)
Edit a post.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) int $post_ID string $username string $password string $content bool $publish }
Returns
true|IXR_Error true when done.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a post has been successfully updated via the XML-RPC Blogger API.
Since
3.4.0
Parameters
int $post_ID ID of the updated post.
array $args An array of arguments for the post to edit.
Definition at line 4641 of file class-wp-xmlrpc-server.php.
References $content, $error, $post_ID, $user, __, ARRAY_A, attach_uploads(), current_user_can(), do_action(), escape(), get_post(), login(), wp_update_post(), xmlrpc_getpostcategory(), xmlrpc_getposttitle(), and xmlrpc_removepostdata().
blogger_getPost ($args)
Retrieve post.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) int $post_ID string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 4425 of file class-wp-xmlrpc-server.php.
References $content, $post_ID, $user, __, _convert_date(), ARRAY_A, current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), login(), wp_get_post_categories(), and wp_unslash().
blogger_getRecentPosts ($args)
Retrieve list of recent posts.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
string $appkey (unused) int $blog_id (unused) string $username string $password int $numberposts (optional) }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 4477 of file class-wp-xmlrpc-server.php.
References $content, $error, $user, __, _convert_date(), absint(), current_user_can(), do_action(), IXR_Server\error(), escape(), login(), wp_get_post_categories(), wp_get_recent_posts(), and wp_unslash().
blogger_getTemplate ($args)
Deprecated.
Since
1.5.0
Parameters
array $args Unused.
Returns
IXR_Error Error object.
Definition at line 4537 of file class-wp-xmlrpc-server.php.
References __.
blogger_getUserInfo ($args)
Retrieve user's data.
Gives your client some info about you, so you don't have to.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 4384 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), escape(), and login().
blogger_getUsersBlogs ($args)
Retrieve blogs that user owns.
Will make more sense once we support multiple blogs.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 4302 of file class-wp-xmlrpc-server.php.
References $error, $user, _multisite_getUsersBlogs(), current_user_can(), do_action(), escape(), get_option(), is_multisite(), login(), and site_url().
Referenced by wp_getUsersBlogs().
blogger_newPost ($args)
Creates new post.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
string $appkey (unused) int $blog_id (unused) string $username string $password string $content string $publish }
Returns
int|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a new post has been successfully created via the XML-RPC Blogger API.
Since
3.4.0
Parameters
int $post_ID ID of the new post.
array $args An array of new post arguments.
Definition at line 4571 of file class-wp-xmlrpc-server.php.
References $content, $error, $post_ID, $post_title, $user, __, attach_uploads(), current_time(), current_user_can(), do_action(), escape(), get_post_type_object(), is_wp_error(), login(), wp_insert_post(), xmlrpc_getpostcategory(), xmlrpc_getposttitle(), and xmlrpc_removepostdata().
blogger_setTemplate ($args)
Deprecated.
Since
1.5.0
Parameters
array $args Unused.
Returns
IXR_Error Error object.
Definition at line 4550 of file class-wp-xmlrpc-server.php.
References __.
escape (& $data)
Escape string or array of strings for database.
Since
1.5.2
Parameters
string | array $data Escape single string or array of strings.
Returns
string|void Returns with string is passed, alters by-reference when array is passed.
Definition at line 317 of file class-wp-xmlrpc-server.php.
References IXR_Server\$data, elseif, and wp_slash().
Referenced by blogger_deletePost(), blogger_editPost(), blogger_getPost(), blogger_getRecentPosts(), blogger_getUserInfo(), blogger_getUsersBlogs(), blogger_newPost(), mt_getCategoryList(), mt_getPostCategories(), mt_getRecentPostTitles(), mt_publishPost(), mt_setPostCategories(), mw_editPost(), mw_getCategories(), mw_getPost(), mw_getRecentPosts(), mw_newMediaObject(), mw_newPost(), pingback_extensions_getPingbacks(), pingback_ping(), wp_deleteCategory(), wp_deleteComment(), wp_deletePage(), wp_deletePost(), wp_deleteTerm(), wp_editComment(), wp_editPage(), wp_editPost(), wp_editProfile(), wp_editTerm(), wp_getAuthors(), wp_getComment(), wp_getCommentCount(), wp_getComments(), wp_getCommentStatusList(), wp_getMediaItem(), wp_getMediaLibrary(), wp_getOptions(), wp_getPage(), wp_getPageList(), wp_getPages(), wp_getPageStatusList(), wp_getPageTemplates(), wp_getPost(), wp_getPostFormats(), wp_getPosts(), wp_getPostStatusList(), wp_getPostType(), wp_getPostTypes(), wp_getProfile(), wp_getRevisions(), wp_getTags(), wp_getTaxonomies(), wp_getTaxonomy(), wp_getTerm(), wp_getTerms(), wp_getUser(), wp_getUsers(), wp_getUsersBlogs(), wp_newCategory(), wp_newComment(), wp_newPage(), wp_newPost(), wp_newTerm(), wp_restoreRevision(), wp_setOptions(), and wp_suggestCategories().
get_custom_fields ($post_id)
Retrieve custom fields for post.
Since
2.5.0
Parameters
int $post_id Post ID.
Returns
array Custom fields, if exist.
Definition at line 337 of file class-wp-xmlrpc-server.php.
References $post_id, current_user_can(), and has_meta().
Referenced by _prepare_post().
initialise_blog_option_info ()
Set up blog options property.
Passes property through {
See also
'xmlrpc_blog_options'} filter.
Since
2.6.0
string $wp_version
Filter the XML-RPC blog options property.
Since
2.6.0
Parameters
array $blog_options An array of XML-RPC blog options.
Definition at line 397 of file class-wp-xmlrpc-server.php.
References $wp_version, __, apply_filters(), current_theme_supports(), get_admin_url(), and wp_login_url().
Referenced by __construct().
login ($username, $password)
Log user in.
Since
2.8.0
Parameters
string $username User's username.
string $password User's password.
Returns
WP_User|bool WP_User object if authentication passed, false otherwise
Filter whether XML-RPC is enabled.
This is the proper filter for turning off XML-RPC.
Since
3.5.0
Parameters
bool $enabled Whether XML-RPC is enabled. Default true.
Filter the XML-RPC user login error message.
Since
3.5.0
Parameters
string $error The XML-RPC error message.
WP_User $user WP_User object.
Definition at line 239 of file class-wp-xmlrpc-server.php.
References $user, __, apply_filters(), IXR_Server\error(), and is_wp_error().
Referenced by blogger_deletePost(), blogger_editPost(), blogger_getPost(), blogger_getRecentPosts(), blogger_getUserInfo(), blogger_getUsersBlogs(), blogger_newPost(), login_pass_ok(), mt_getCategoryList(), mt_getPostCategories(), mt_getRecentPostTitles(), mt_publishPost(), mt_setPostCategories(), mw_editPost(), mw_getCategories(), mw_getPost(), mw_getRecentPosts(), mw_newMediaObject(), mw_newPost(), wp_deleteCategory(), wp_deleteComment(), wp_deletePage(), wp_deletePost(), wp_deleteTerm(), wp_editComment(), wp_editPage(), wp_editPost(), wp_editProfile(), wp_editTerm(), wp_getAuthors(), wp_getComment(), wp_getCommentCount(), wp_getComments(), wp_getCommentStatusList(), wp_getMediaItem(), wp_getMediaLibrary(), wp_getOptions(), wp_getPage(), wp_getPageList(), wp_getPages(), wp_getPageStatusList(), wp_getPageTemplates(), wp_getPost(), wp_getPostFormats(), wp_getPosts(), wp_getPostStatusList(), wp_getPostType(), wp_getPostTypes(), wp_getProfile(), wp_getRevisions(), wp_getTags(), wp_getTaxonomies(), wp_getTaxonomy(), wp_getTerm(), wp_getTerms(), wp_getUser(), wp_getUsers(), wp_getUsersBlogs(), wp_newCategory(), wp_newComment(), wp_newPage(), wp_newPost(), wp_newTerm(), wp_restoreRevision(), wp_setOptions(), and wp_suggestCategories().
login_pass_ok ($username, $password)
Check user's credentials.
Deprecated.
Since
1.5.0
Parameters
string $username User's username.
string $password User's password.
Returns
bool Whether authentication passed.
Definition at line 304 of file class-wp-xmlrpc-server.php.
References login().
minimum_args ($args, $count) protected
Checks if the method received at least the minimum number of arguments.
Since
3.4.0 protected
Parameters
string | array $args Sanitize single string or array of strings.
int $count Minimum number of arguments.
Returns
bool if $args contains at least $count arguments.
Definition at line 653 of file class-wp-xmlrpc-server.php.
References $count, __, and IXR_Server\error().
Referenced by wp_deletePost(), wp_deleteTerm(), wp_editPost(), wp_editProfile(), wp_editTerm(), wp_getPost(), wp_getPosts(), wp_getPostType(), wp_getPostTypes(), wp_getProfile(), wp_getRevisions(), wp_getTaxonomies(), wp_getTaxonomy(), wp_getTerm(), wp_getTerms(), wp_getUser(), wp_getUsers(), wp_newPost(), wp_newTerm(), and wp_restoreRevision().
mt_getCategoryList ($args)
Retrieve list of all categories on blog.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 5916 of file class-wp-xmlrpc-server.php.
References $cats, $error, $user, __, current_user_can(), do_action(), escape(), get_categories(), and login().
mt_getPostCategories ($args)
Retrieve post categories.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $post_ID string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 5960 of file class-wp-xmlrpc-server.php.
References $post_ID, $user, __, current_user_can(), do_action(), IXR_Server\error(), escape(), get_cat_name(), get_post(), login(), and wp_get_post_categories().
mt_getRecentPostTitles ($args)
Retrieve the post titles of recent posts.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $numberposts }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 5857 of file class-wp-xmlrpc-server.php.
References $error, $user, __, _convert_date(), _convert_date_gmt(), absint(), current_user_can(), do_action(), IXR_Server\error(), escape(), login(), and wp_get_recent_posts().
mt_getTrackbackPings ($post_ID)
Retrieve trackbacks sent to a given post.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_ID
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 6083 of file class-wp-xmlrpc-server.php.
References $comment, $content, $post_ID, $title, $wpdb, __, ARRAY_A, do_action(), and get_post().
mt_publishPost ($args)
Sets a post's publish status to 'publish'.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $post_ID string $username string $password }
Returns
int|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 6129 of file class-wp-xmlrpc-server.php.
References $cats, $post_ID, $user, __, ARRAY_A, current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), login(), wp_get_post_categories(), and wp_update_post().
mt_setPostCategories ($args)
Sets categories for a post.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $post_ID string $username string $password array $categories }
Returns
true|IXR_Error True on success.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 6010 of file class-wp-xmlrpc-server.php.
References $post_ID, $user, __, current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), login(), and wp_set_post_categories().
mt_supportedMethods ()
Retrieve an array of methods supported by this server.
Since
1.5.0
Returns
array
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 6047 of file class-wp-xmlrpc-server.php.
References do_action(), and methods.
mt_supportedTextFilters ()
Retrieve an empty array because we don't support per-post text filters.
Since
1.5.0
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Filter the MoveableType text filters list for XML-RPC.
Since
2.2.0
Parameters
array $filters An array of text filters.
Definition at line 6059 of file class-wp-xmlrpc-server.php.
References apply_filters(), and do_action().
mw_editPost ($args)
Edit a post.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $content_struct int $publish }
Returns
bool|IXR_Error True on success.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a post has been successfully updated via the XML-RPC MovableType API.
Since
3.4.0
Parameters
int $post_ID ID of the updated post.
array $args An array of arguments to update the post.
Definition at line 5146 of file class-wp-xmlrpc-server.php.
References IXR_Server\$data, $error, $ID, $post_ID, $post_title, $post_type, $user, __, _toggle_sticky(), add_enclosure_if_new(), ARRAY_A, attach_uploads(), current_user_can(), delete_post_thumbnail(), do_action(), elseif, escape(), get_cat_ID(), get_date_from_gmt(), get_default_comment_status(), get_post(), get_post_format_strings(), is_wp_error(), iso8601_to_datetime(), login(), null, sanitize_key(), set_custom_fields(), set_post_format(), set_post_thumbnail(), and wp_update_post().
Referenced by wp_editPage().
mw_getCategories ($args)
Retrieve the list of categories on a given blog.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 5695 of file class-wp-xmlrpc-server.php.
References $cats, $error, $user, __, current_user_can(), do_action(), esc_html, escape(), get_categories(), get_category_feed_link(), get_category_link(), and login().
mw_getPost ($args)
Retrieve post.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) int $post_ID string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 5447 of file class-wp-xmlrpc-server.php.
References $link, $post, $post_ID, $sticky, $tags, $user, __, _convert_date(), _convert_date_gmt(), ARRAY_A, current_user_can(), do_action(), IXR_Server\error(), escape(), get_cat_name(), get_extended(), get_permalink(), get_post(), get_post_custom(), get_post_format(), get_post_thumbnail_id(), is_sticky(), login(), wp_get_post_categories(), and wp_get_post_tags().
mw_getRecentPosts ($args)
Retrieve list of recent posts.
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $numberposts }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 5578 of file class-wp-xmlrpc-server.php.
References $error, $link, $post, $tags, $user, __, _convert_date(), _convert_date_gmt(), absint(), current_user_can(), do_action(), escape(), get_cat_name(), get_extended(), get_permalink(), get_post_format(), get_post_thumbnail_id(), is_sticky(), login(), wp_get_post_categories(), wp_get_post_tags(), and wp_get_recent_posts().
mw_newMediaObject ($args)
Uploads a file, following your settings.
Adapted from a patch by Johann Richard.
1.5.0 wpdb $wpdb WordPress database abstraction object. array $args { Method arguments. Note: arguments must be ordered as documented. int $blog_id (unused) string $username string $password array $data } array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Filter whether to preempt the XML-RPC media upload.
Passing a truthy value will effectively short-circuit the media upload, returning that value as a 500 error instead.
Since
2.1.0
Parameters
bool $error Whether to pre-empt the media upload. Default false.
Fires after a new attachment has been added via the XML-RPC MovableType API.
Since
3.4.0
Parameters
int $id ID of the new attachment.
array $args An array of arguments to add the attachment.
Definition at line 5751 of file class-wp-xmlrpc-server.php.
References IXR_Server\$data, $error, $id, $name, $post_id, $user, $wpdb, __, _prepare_media_item(), apply_filters(), current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), is_multisite(), login(), null, sanitize_file_name(), upload_is_user_over_quota(), wp_generate_attachment_metadata(), wp_insert_attachment(), wp_update_attachment_metadata(), and wp_upload_bits().
mw_newPost ($args)
Create a new post.
The 'content_struct' argument must contain:
title
description
mt_excerpt
mt_text_more
mt_keywords
mt_tb_ping_urls
categories
Also, it can optionally contain:
wp_slug
wp_password
wp_page_parent_id
wp_page_order
wp_author_id
post_status | page_status - can be 'draft', 'private', 'publish', or 'pending'
mt_allow_comments - can be 'open' or 'closed'
mt_allow_pings - can be 'open' or 'closed'
date_created_gmt
dateCreated
wp_post_thumbnail
Since
1.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $content_struct int $publish }
Returns
int|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a new post has been successfully created via the XML-RPC MovableType API.
Since
3.4.0
Parameters
int $post_ID ID of the new post.
array $args An array of arguments to create the new post.
Definition at line 4801 of file class-wp-xmlrpc-server.php.
References IXR_Server\$data, $error, $post_ID, $post_title, $post_type, $user, __, _toggle_sticky(), add_enclosure_if_new(), attach_uploads(), current_user_can(), do_action(), elseif, escape(), get_cat_ID(), get_date_from_gmt(), get_default_comment_status(), get_default_post_to_edit(), get_post_format_strings(), get_post_type_object(), is_wp_error(), iso8601_to_datetime(), login(), null, sanitize_key(), set_custom_fields(), set_post_format(), set_post_thumbnail(), and wp_insert_post().
Referenced by wp_newPage().
pingback_error ($code, $message) protected
Sends a pingback error based on the given error code and message.
Since
3.6.0
Parameters
int $code Error code.
string $message Error message.
Returns
IXR_Error Error object.
Filter the XML-RPC pingback error return.
Since
3.5.1
Parameters
IXR_Error $error An IXR_Error object containing the error code and message.
Definition at line 6428 of file class-wp-xmlrpc-server.php.
References IXR_Server\$message, and apply_filters().
Referenced by pingback_extensions_getPingbacks(), and pingback_ping().
pingback_extensions_getPingbacks ($url)
Retrieve array of URLs that pingbacked the given URL.
Specs on http://www.aquarionics.com/misc/archives/blogite/0198.html
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $url
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 6384 of file class-wp-xmlrpc-server.php.
References $comment, $post_ID, $url, $wpdb, __, ARRAY_A, do_action(), escape(), get_post(), pingback_error(), and url_to_postid().
pingback_ping ($args)
Retrieves a pingback and registers it.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object. string $wp_version
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
string $pagelinkedfrom string $pagelinkedto }
Returns
string|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Filter the pingback source URI.
Since
3.6.0
Parameters
string $pagelinkedfrom URI of the page linked from.
string $pagelinkedto URI of the page linked to.
This filter is documented in wp-includes/class-http.php
Filter the pingback remote source.
Since
2.5.0
Parameters
string $linea Response object for the page linked from.
string $pagelinkedto URL of the page linked to.
Fires after a post pingback has been sent.
Since
0.71
Parameters
int $comment_ID Comment ID.
Definition at line 6179 of file class-wp-xmlrpc-server.php.
References $_SERVER, $excerpt, $post, $post_ID, $title, $wp_version, $wpdb, __, apply_filters(), do_action(), elseif, esc_html, escape(), get_bloginfo(), get_option(), get_post(), pingback_error(), pings_open(), str_replace, url_to_postid(), wp_new_comment(), wp_remote_retrieve_body(), and wp_safe_remote_get().
sayHello ()
Test XMLRPC API by saying, "Hello!" to client.
Since
1.5.0
Returns
string Hello string response.
Definition at line 207 of file class-wp-xmlrpc-server.php.
serve_request ()
Serves the XML-RPC request.
Since
2.9.0 public
Definition at line 196 of file class-wp-xmlrpc-server.php.
References IXR_Server\IXR_Server(), and methods.
set_custom_fields ($post_id, $fields)
Set custom fields for post.
Since
2.5.0
Parameters
int $post_id Post ID.
array $fields Custom fields.
Definition at line 365 of file class-wp-xmlrpc-server.php.
References $post_id, add_post_meta(), current_user_can(), delete_metadata_by_mid(), elseif, get_metadata_by_mid(), update_metadata_by_mid(), and wp_unslash().
Referenced by _insert_post(), mw_editPost(), and mw_newPost().
wp_deleteCategory ($args)
Remove category.
Since
2.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $category_id }
Returns
bool|IXR_Error See wp_delete_term() for return info.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a category has been successfully deleted via XML-RPC.
Since
3.4.0
Parameters
int $category_id ID of the deleted category.
array $args An array of arguments to delete the category.
Definition at line 3098 of file class-wp-xmlrpc-server.php.
References $user, __, current_user_can(), do_action(), IXR_Server\error(), escape(), login(), and wp_delete_term().
wp_deleteComment ($args)
Delete a comment.
By default, the comment will be moved to the trash instead of deleted. See wp_delete_comment() for more information on this behavior.
Since
2.7.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $comment_ID }
Returns
bool|IXR_Error wp_delete_comment()
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a comment has been successfully deleted via XML-RPC.
Since
3.4.0
Parameters
int $comment_ID ID of the deleted comment.
array $args An array of arguments to delete the comment.
Definition at line 3327 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), escape(), get_comment(), login(), and wp_delete_comment().
wp_deletePage ($args)
Delete page.
Since
2.2.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $page_id }
Returns
true|IXR_Error True, if success.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a page has been successfully deleted via XML-RPC.
Since
3.4.0
Parameters
int $page_id ID of the deleted page.
array $args An array of arguments to delete the page.
Definition at line 2757 of file class-wp-xmlrpc-server.php.
References $user, __, ARRAY_A, current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), login(), and wp_delete_post().
wp_deletePost ($args)
Delete a post for any registered post type.
Since
3.4.0
See also
wp_delete_post()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. int $post_id Post ID. }
Returns
true|IXR_Error True on success, IXR_Error instance on failure.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 1596 of file class-wp-xmlrpc-server.php.
References $error, $post, $post_id, $user, __, ARRAY_A, current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), login(), minimum_args(), and wp_delete_post().
wp_deleteTerm ($args)
Delete a term.
Since
3.4.0
See also
wp_delete_term()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. string $taxnomy_name Taxonomy name. int $term_id Term ID. }
Returns
bool|IXR_Error True on success, IXR_Error instance on failure.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2019 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), IXR_Server\error(), escape(), get_taxonomy(), get_term(), is_wp_error(), login(), minimum_args(), taxonomy_exists(), and wp_delete_term().
wp_editComment ($args)
Edit comment.
Besides the common blog_id (unused), username, and password arguments, it takes a comment_id integer and a content_struct array as last argument.
The allowed keys in the content_struct array are:
'author'
'author_url'
'author_email'
'content'
'date_created_gmt'
'status'. Common statuses are 'approve', 'hold', 'spam'. See get_comment_statuses() for more details
Since
2.7.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $comment_ID array $content_struct }
Returns
true|IXR_Error True, on success.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a comment has been successfully updated via XML-RPC.
Since
3.4.0
Parameters
int $comment_ID ID of the updated comment.
array $args An array of arguments to update the comment.
Definition at line 3393 of file class-wp-xmlrpc-server.php.
References $comment, $error, $user, __, current_user_can(), do_action(), escape(), get_comment(), get_comment_statuses(), get_date_from_gmt(), is_wp_error(), iso8601_to_datetime(), login(), and wp_update_comment().
wp_editPage ($args)
Edit page.
Since
2.2.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) int $page_id string $username string $password string $content string $publish }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2815 of file class-wp-xmlrpc-server.php.
References $content, $error, $user, __, ARRAY_A, current_user_can(), do_action(), escape(), get_post(), login(), and mw_editPost().
wp_editPost ($args)
Edit a post for any registered post type.
The $content_struct parameter only needs to contain fields that should be changed. All other fields will retain their existing values.
Since
3.4.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. int $post_id Post ID. array $content_struct Extra content arguments. }
Returns
true|IXR_Error True on success, IXR_Error on failure.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 1528 of file class-wp-xmlrpc-server.php.
References $error, $post, $post_id, $user, __, _convert_date(), _insert_post(), ARRAY_A, do_action(), IXR_Server\error(), escape(), get_post(), login(), minimum_args(), and mysql2date().
wp_editProfile ($args)
Edit user's profile.
wp_update_user()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $content_struct It can optionally contain:
'first_name'
'last_name'
'website'
'display_name'
'nickname'
'nicename'
'bio' }
Returns
true|IXR_Error True, on success.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2556 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), escape(), is_wp_error(), login(), minimum_args(), and wp_update_user().
wp_editTerm ($args)
Edit a term.
Since
3.4.0
See also
wp_update_term()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. int $term_id Term ID. array $content_struct Content struct for editing a term. The struct must contain the term ''taxonomy'. Optional accepted values include 'name', 'parent', 'description', and 'slug'. }
Returns
true|IXR_Error True on success, IXR_Error instance on failure.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 1923 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), IXR_Server\error(), escape(), get_taxonomy(), get_term(), is_wp_error(), login(), minimum_args(), taxonomy_exists(), and wp_update_term().
wp_getAuthors ($args)
Retrieve authors list.
Since
2.2.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2932 of file class-wp-xmlrpc-server.php.
References $authors, $error, $user, __, current_user_can(), do_action(), escape(), get_users(), and login().
wp_getComment ($args)
Retrieve comment.
Since
2.7.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $comment_id }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3191 of file class-wp-xmlrpc-server.php.
References $comment, $error, $user, __, _prepare_comment(), current_user_can(), do_action(), escape(), get_comment(), and login().
wp_getCommentCount ($args)
Retrieve comment count.
Since
2.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $post_id }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3638 of file class-wp-xmlrpc-server.php.
References $count, $error, $post, $post_id, $user, __, ARRAY_A, current_user_can(), do_action(), escape(), get_post(), login(), and wp_count_comments().
wp_getComments ($args)
Retrieve comments.
Besides the common blog_id (unused), username, and password arguments, it takes a filter array as last argument.
Accepted 'filter' keys are 'status', 'post_id', 'offset', and 'number'.
The defaults are as follows:
'status' - Default is ''. Filter by status (e.g., 'approve', 'hold')
'post_id' - Default is ''. The post where the comment is posted. Empty string shows all comments.
'number' - Default is 10. Total number of media items to retrieve.
'offset' - Default is 0. See WP_Query::query() for more.
Since
2.7.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $struct }
Returns
array|IXR_Error Contains a collection of comments. See wp_xmlrpc_server::wp_getComment() for a description of each item contents
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3242 of file class-wp-xmlrpc-server.php.
References $comment, $error, $post_id, $post_type, $post_type_object, $user, __, _prepare_comment(), absint(), current_user_can(), do_action(), escape(), get_comments(), get_post_type_object(), login(), and post_type_supports().
wp_getCommentStatusList ($args)
Retrieve all of the comment status.
Since
2.7.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3603 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), escape(), get_comment_statuses(), and login().
wp_getMediaItem ($args)
Retrieve a media item by ID.
Since
3.1.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $attachment_id }
Returns
array|IXR_Error Associative array contains:
'date_created_gmt'
'parent'
'link'
'thumbnail'
'title'
'caption'
'description'
'metadata'
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3894 of file class-wp-xmlrpc-server.php.
References $user, __, _prepare_media_item(), current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), and login().
wp_getMediaLibrary ($args)
Retrieves a collection of media library items (or attachments)
Besides the common blog_id (unused), username, and password arguments, it takes a filter array as last argument.
Accepted 'filter' keys are 'parent_id', 'mime_type', 'offset', and 'number'.
The defaults are as follows:
'number' - Default is 5. Total number of media items to retrieve.
'offset' - Default is 0. See WP_Query::query() for more.
'parent_id' - Default is ''. The post where the media item is attached. Empty string shows all media items. 0 shows unattached media items.
'mime_type' - Default is ''. Filter by mime type (e.g., 'image/jpeg', 'application/pdf')
Since
3.1.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $struct }
Returns
array|IXR_Error Contains a collection of media items. See wp_xmlrpc_server::wp_getMediaItem() for a description of each item contents
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3942 of file class-wp-xmlrpc-server.php.
References $attachments, $error, $user, __, _prepare_media_item(), absint(), current_user_can(), do_action(), escape(), get_posts(), and login().
wp_getOptions ($args)
Retrieve blog options.
Since
2.6.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $options }
Returns
array|IXR_Error
Definition at line 3782 of file class-wp-xmlrpc-server.php.
References $options, $user, _getOptions(), IXR_Server\error(), escape(), and login().
wp_getPage ($args)
Retrieve page.
Since
2.2.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) int $page_id string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2627 of file class-wp-xmlrpc-server.php.
References $error, $page, $user, __, _prepare_page(), current_user_can(), do_action(), escape(), get_post(), and login().
wp_getPageList ($args)
Retrieve page list.
Since
2.2.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2874 of file class-wp-xmlrpc-server.php.
References $error, $i, $user, $wpdb, __, _convert_date(), _convert_date_gmt(), current_user_can(), do_action(), escape(), and login().
wp_getPages ($args)
Retrieve Pages.
Since
2.2.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $num_pages }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2673 of file class-wp-xmlrpc-server.php.
References $page, $user, __, _prepare_page(), current_user_can(), do_action(), IXR_Server\error(), escape(), get_posts(), and login().
wp_getPageStatusList ($args)
Retrieve page statuses.
Since
2.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3717 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), escape(), get_page_statuses(), and login().
wp_getPageTemplates ($args)
Retrieve page templates.
Since
2.6.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
Definition at line 3749 of file class-wp-xmlrpc-server.php.
References $error, $templates, $user, __, current_user_can(), escape(), get_page_templates(), and login().
wp_getPost ($args)
Retrieve a post.
Since
3.4.0
The optional $fields parameter specifies what fields will be included in the response array. This should be a list of field names. 'post_id' will always be included in the response regardless of the value of $fields.
Instead of, or in addition to, individual field names, conceptual group names can be used to specify multiple fields. The available conceptual groups are 'post' (all basic fields), 'taxonomies', 'custom_fields', and 'enclosure'.
See also
get_post()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. int $post_id Post ID. array $fields The subset of post type fields to return. }
Returns
array|IXR_Error Array contains (based on $fields parameter):
'post_id'
'post_title'
'post_date'
'post_date_gmt'
'post_modified'
'post_modified_gmt'
'post_status'
'post_type'
'post_name'
'post_author'
'post_password'
'post_excerpt'
'post_content'
'link'
'comment_status'
'ping_status'
'sticky'
'custom_fields'
'terms'
'categories'
'tags'
'enclosure'
Filter the list of post query fields used by the given XML-RPC method.
Since
3.4.0
Parameters
array $fields Array of post fields. Default array contains 'post', 'terms', and 'custom_fields'.
string $method Method name.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 1679 of file class-wp-xmlrpc-server.php.
References $error, $post, $post_id, $user, __, _prepare_post(), apply_filters(), ARRAY_A, current_user_can(), do_action(), escape(), get_post(), login(), and minimum_args().
wp_getPostFormats ($args)
Retrieves a list of post formats used by the site.
Since
3.1.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error List of post formats, otherwise IXR_Error object.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3987 of file class-wp-xmlrpc-server.php.
References IXR_Server\$data, $error, $user, __, current_theme_supports(), current_user_can(), do_action(), escape(), get_post_format_strings(), get_theme_support(), and login().
wp_getPosts ($args)
Retrieve posts.
Since
3.4.0
See also
wp_get_recent_posts()
wp_getPost() for more on $fields
get_posts() for more on $filter values
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. array $filter Optional. Modifies the query used to retrieve posts. Accepts 'post_type', 'post_status', 'number', 'offset', 'orderby', 's', and 'order'. Default empty array. array $fields Optional. The subset of post type fields to return in the response array. }
Returns
array|IXR_Error Array contains a collection of posts.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 1742 of file class-wp-xmlrpc-server.php.
References $error, $post, $post_type, $user, __, _prepare_post(), absint(), apply_filters(), current_user_can(), do_action(), escape(), get_post_type_object(), login(), minimum_args(), and wp_get_recent_posts().
wp_getPostStatusList ($args)
Retrieve post statuses.
Since
2.5.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3685 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), escape(), get_post_statuses(), and login().
wp_getPostType ($args)
Retrieves a post type.
Since
3.4.0
See also
get_post_type_object()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password string $post_type_name array $fields (optional) }
Returns
array|IXR_Error Array contains:
'labels'
'description'
'capability_type'
'cap'
'map_meta_cap'
'hierarchical'
'menu_position'
'taxonomies'
'supports'
Filter the default query fields used by the given XML-RPC method.
Since
3.4.0
Parameters
array $fields An array of post type query fields for the given method.
string $method The method name.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 4049 of file class-wp-xmlrpc-server.php.
References $error, $post_type, $user, __, _prepare_post_type(), apply_filters(), current_user_can(), do_action(), escape(), get_post_type_object(), login(), minimum_args(), and post_type_exists().
wp_getPostTypes ($args)
Retrieves a post types.
Since
3.4.0
See also
get_post_types()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $filter (optional) array $fields (optional) }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 4108 of file class-wp-xmlrpc-server.php.
References $error, $post_type, $user, _prepare_post_type(), apply_filters(), current_user_can(), do_action(), escape(), get_post_types(), login(), and minimum_args().
wp_getProfile ($args)
Retrieve information about the requesting user.
get_userdata()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $fields (optional) }
Returns
array|IXR_Error (
See also
wp_getUser)
This action is documented in wp-includes/class-wp-xmlrpc-server.php
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2504 of file class-wp-xmlrpc-server.php.
References $error, $user, __, _prepare_user(), apply_filters(), current_user_can(), do_action(), escape(), login(), and minimum_args().
wp_getRevisions ($args)
Retrieve revisions for a specific post.
Since
3.5.0
The optional $fields parameter specifies what fields will be included in the response array.
wp_get_post_revisions()
See also
wp_getPost() for more on $fields
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $post_id array $fields (optional) }
Returns
array|IXR_Error contains a collection of posts.
Filter the default revision query fields used by the given XML-RPC method.
Since
3.5.0
Parameters
array $field An array of revision query fields.
string $method The method name.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 4167 of file class-wp-xmlrpc-server.php.
References $error, $post, $post_id, $user, __, _prepare_post(), apply_filters(), current_user_can(), do_action(), escape(), get_post(), login(), minimum_args(), wp_get_post_revisions(), wp_is_post_autosave(), and wp_revisions_enabled().
wp_getTags ($args)
Get list of all tags.
Since
2.7.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2973 of file class-wp-xmlrpc-server.php.
References $error, $tags, $user, __, current_user_can(), do_action(), esc_html, escape(), get_tag_feed_link(), get_tag_link(), get_tags(), and login().
wp_getTaxonomies ($args)
Retrieve all taxonomies.
Since
3.4.0
See also
get_taxonomies()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. array $filter Optional. An array of arguments for retrieving taxonomies. array $fields Optional. The subset of taxonomy fields to return. }
Returns
array|IXR_Error An associative array of taxonomy data with returned fields determined by $fields, or an IXR_Error instance on failure.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2290 of file class-wp-xmlrpc-server.php.
References $error, $user, _prepare_taxonomy(), apply_filters(), current_user_can(), do_action(), escape(), get_taxonomies(), login(), and minimum_args().
wp_getTaxonomy ($args)
Retrieve a taxonomy.
Since
3.4.0
See also
get_taxonomy()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. string $taxnomy Taxonomy name. array $fields Optional. Array of taxonomy fields to limit to in the return. Accepts 'labels', 'cap', 'menu', and 'object_type'. Default empty array. }
Returns
array|IXR_Error An array of taxonomy data on success, IXR_Error instance otherwise.
Filter the taxonomy query fields used by the given XML-RPC method.
Since
3.4.0
Parameters
array $fields An array of taxonomy fields to retrieve.
string $method The method name.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2230 of file class-wp-xmlrpc-server.php.
References $error, $user, __, _prepare_taxonomy(), apply_filters(), current_user_can(), do_action(), escape(), get_taxonomy(), login(), minimum_args(), and taxonomy_exists().
wp_getTerm ($args)
Retrieve a term.
Since
3.4.0
See also
get_term()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. string $taxnomy Taxonomy name. string $term_id Term ID. }
Returns
array|IXR_Error IXR_Error on failure, array on success, containing:
'term_id'
'name'
'slug'
'term_group'
'term_taxonomy_id'
'taxonomy'
'description'
'parent'
'count'
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2090 of file class-wp-xmlrpc-server.php.
References $error, $user, __, _prepare_term(), ARRAY_A, current_user_can(), do_action(), IXR_Server\error(), escape(), get_taxonomy(), get_term(), is_wp_error(), login(), minimum_args(), and taxonomy_exists().
wp_getTerms ($args)
Retrieve all terms for a taxonomy.
Since
3.4.0
The optional $filter parameter modifies the query used to retrieve terms. Accepted keys are 'number', 'offset', 'orderby', 'order', 'hide_empty', and 'search'.
See also
get_terms()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. string $taxnomy Taxonomy name. array $filter Optional. Modifies the query used to retrieve posts. Accepts 'number', 'offset', 'orderby', 'order', 'hide_empty', and 'search'. Default empty array. }
Returns
array|IXR_Error An associative array of terms data on success, IXR_Error instance otherwise.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2148 of file class-wp-xmlrpc-server.php.
References $error, $user, __, _prepare_term(), absint(), current_user_can(), do_action(), escape(), get_taxonomy(), get_terms(), is_wp_error(), login(), minimum_args(), and taxonomy_exists().
wp_getUser ($args)
Retrieve a user.
The optional $fields parameter specifies what fields will be included in the response array. This should be a list of field names. 'user_id' will always be included in the response regardless of the value of $fields.
Instead of, or in addition to, individual field names, conceptual group names can be used to specify multiple fields. The available conceptual groups are 'basic' and 'all'.
get_userdata()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $user_id array $fields (optional) }
Returns
array|IXR_Error Array contains (based on $fields parameter):
'user_id'
'username'
'first_name'
'last_name'
'registered'
'bio'
'email'
'nickname'
'nicename'
'url'
'display_name'
'roles'
Filter the default user query fields used by the given XML-RPC method.
Since
3.5.0
Parameters
array $fields User query fields for given method. Default 'all'.
string $method The method name.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2365 of file class-wp-xmlrpc-server.php.
References $error, $user, $user_id, __, _prepare_user(), apply_filters(), current_user_can(), do_action(), escape(), login(), and minimum_args().
wp_getUsers ($args)
Retrieve users.
The optional $filter parameter modifies the query used to retrieve users. Accepted keys are 'number' (default: 50), 'offset' (default: 0), 'role', 'who', 'orderby', and 'order'.
The optional $fields parameter specifies what fields will be included in the response array.
get_users()
See also
wp_getUser() for more on $fields and return values
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $filter (optional) array $fields (optional) }
Returns
array|IXR_Error users data
This action is documented in wp-includes/class-wp-xmlrpc-server.php
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2430 of file class-wp-xmlrpc-server.php.
References $error, $user, __, _prepare_user(), absint(), apply_filters(), current_user_can(), do_action(), escape(), get_role(), get_users(), login(), minimum_args(), and null.
wp_getUsersBlogs ($args)
Retrieve the blogs of the user.
Since
2.6.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
string $username Username. string $password Password. }
Returns
array|IXR_Error Array contains:
'isAdmin'
'isPrimary' - whether the blog is the user's primary blog
'url'
'blogid'
'blogName'
'xmlrpc' - url of xmlrpc endpoint
Fires after the XML-RPC user has been authenticated but before the rest of the method logic begins.
All built-in XML-RPC methods use the action xmlrpc_call, with a parameter equal to the method's name, e.g., wp.getUsersBlogs, wp.newPost, etc.
Since
2.5.0
Parameters
string $name The method name.
Definition at line 580 of file class-wp-xmlrpc-server.php.
References $blog, $blog_id, $blogs, $error, $user, blogger_getUsersBlogs(), current_user_can(), do_action(), escape(), get_active_blog_for_user(), get_blogs_of_user(), get_current_site(), get_option(), home_url(), is_multisite(), login(), restore_current_blog(), site_url(), and switch_to_blog().
wp_newCategory ($args)
Create new category.
Since
2.2.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $category }
Returns
int|IXR_Error Category ID.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a new category has been successfully created via XML-RPC.
Since
3.4.0
Parameters
int $cat_id ID of the new category.
array $args An array of new category arguments.
Definition at line 3022 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), elseif, escape(), is_wp_error(), login(), and wp_insert_category().
wp_newComment ($args)
Create new comment.
Since
2.7.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password string|int $post array $content_struct }
Returns
int|IXR_Error wp_new_comment()
Filter whether to allow anonymous comments over XML-RPC.
Since
2.7.0
Parameters
bool $allow Whether to allow anonymous commenting via XML-RPC. Default false.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Fires after a new comment has been successfully created via XML-RPC.
Since
3.4.0
Parameters
int $comment_ID ID of the new comment.
array $args An array of new comment arguments.
Definition at line 3484 of file class-wp-xmlrpc-server.php.
References $comment, $error, $post, $post_id, $user, __, absint(), apply_filters(), comments_open(), do_action(), elseif, escape(), get_option(), get_post(), is_email(), login(), null, url_to_postid(), and wp_new_comment().
wp_newPage ($args)
Create new page.
Since
2.2.0
See also
wp_xmlrpc_server::mw_newPost()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $content_struct }
Returns
int|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 2724 of file class-wp-xmlrpc-server.php.
References $error, $user, do_action(), escape(), login(), and mw_newPost().
wp_newPost ($args)
Create a new post for any registered post type.
Since
3.4.0
for information on RSS enclosures. array $args { Method arguments. Note: top-level arguments must be ordered as documented. int $blog_id Blog ID (unused). string $username Username. string $password Password. array $content_struct { Content struct for adding a new post. See wp_insert_post() for information on additional post fields string $post_type Post type. Default 'post'. string $post_status Post status. Default 'draft' string $post_title Post title. int $post_author Post author ID. string $post_excerpt Post excerpt. string $post_content Post content. string $post_date_gmt Post date in GMT. string $post_date Post date. string $post_password Post password (20-character limit). string $comment_status Post comment enabled status. Accepts 'open' or 'closed'. string $ping_status Post ping status. Accepts 'open' or 'closed'. bool $sticky Whether the post should be sticky. Automatically false if $post_status is 'private'. int $post_thumbnail ID of an image to use as the post thumbnail/featured image. array $custom_fields Array of meta key/value pairs to add to the post. array $terms Associative array with taxonomy names as keys and arrays of term IDs as values. array $terms_names Associative array with taxonomy names as keys and arrays of term names as values. array $enclosure { Array of feed enclosure data to add to post meta. string $url URL for the feed enclosure. int $length Size in bytes of the enclosure. string $type Mime-type for the enclosure. } } } int|IXR_Error Post ID on success, IXR_Error instance otherwise.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 1184 of file class-wp-xmlrpc-server.php.
References $error, $user, _convert_date(), _insert_post(), do_action(), escape(), login(), and minimum_args().
wp_newTerm ($args)
Create a new term.
Since
3.4.0
See also
wp_insert_term()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id Blog ID (unused). string $username Username. string $password Password. array $content_struct Content struct for adding a new term. The struct must contain the term 'name' and 'taxonomy'. Optional accepted values include 'parent', 'description', and 'slug'. }
Returns
int|IXR_Error The term ID on success, or an IXR_Error object on failure.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 1837 of file class-wp-xmlrpc-server.php.
References $error, $user, __, current_user_can(), do_action(), escape(), get_taxonomy(), get_term(), is_wp_error(), login(), minimum_args(), taxonomy_exists(), and wp_insert_term().
wp_restoreRevision ($args)
Restore a post revision.
Since
3.5.0
wp_restore_post_revision()
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password int $revision_id }
Returns
bool|IXR_Error false if there was an error restoring, true if success.
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 4245 of file class-wp-xmlrpc-server.php.
References $error, $post, $revision_id, $user, __, current_user_can(), do_action(), IXR_Server\error(), escape(), get_post(), login(), minimum_args(), wp_get_post_revision(), wp_is_post_autosave(), wp_restore_post_revision(), and wp_revisions_enabled().
wp_setOptions ($args)
Update blog options.
Since
2.6.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $options }
Returns
array|IXR_Error
Definition at line 3842 of file class-wp-xmlrpc-server.php.
References $options, $user, __, _getOptions(), current_user_can(), IXR_Server\error(), escape(), login(), update_option(), and wp_unslash().
wp_suggestCategories ($args)
Retrieve category list.
Since
2.2.0
Parameters
array $args { Method arguments. Note: arguments must be ordered as documented.
int $blog_id (unused) string $username string $password array $category int $max_results }
Returns
array|IXR_Error
This action is documented in wp-includes/class-wp-xmlrpc-server.php
Definition at line 3147 of file class-wp-xmlrpc-server.php.
References $user, __, current_user_can(), do_action(), IXR_Server\error(), escape(), get_categories(), and login().
Field Documentation
$auth_failed = false protected
Definition at line 54 of file class-wp-xmlrpc-server.php.
$blog_options
Definition at line 38 of file class-wp-xmlrpc-server.php.
$error
Definition at line 46 of file class-wp-xmlrpc-server.php.
Referenced by _insert_post(), blogger_editPost(), blogger_getRecentPosts(), blogger_getUserInfo(), blogger_getUsersBlogs(), blogger_newPost(), mt_getCategoryList(), mt_getRecentPostTitles(), mw_editPost(), mw_getCategories(), mw_getRecentPosts(), mw_newMediaObject(), mw_newPost(), wp_deleteComment(), wp_deletePost(), wp_deleteTerm(), wp_editComment(), wp_editPage(), wp_editPost(), wp_editProfile(), wp_editTerm(), wp_getAuthors(), wp_getComment(), wp_getCommentCount(), wp_getComments(), wp_getCommentStatusList(), wp_getMediaLibrary(), wp_getPage(), wp_getPageList(), wp_getPageStatusList(), wp_getPageTemplates(), wp_getPost(), wp_getPostFormats(), wp_getPosts(), wp_getPostStatusList(), wp_getPostType(), wp_getPostTypes(), wp_getProfile(), wp_getRevisions(), wp_getTags(), wp_getTaxonomies(), wp_getTaxonomy(), wp_getTerm(), wp_getTerms(), wp_getUser(), wp_getUsers(), wp_getUsersBlogs(), wp_newCategory(), wp_newComment(), wp_newPage(), wp_newPost(), wp_newTerm(), and wp_restoreRevision().
$methods
Definition at line 30 of file class-wp-xmlrpc-server.php.
The documentation for this class was generated from the following file:
class-wp-xmlrpc-server.php