GravityView: WP_Posts_List_Table Class Reference
WP_Posts_List_Table Class Reference
Core class used to implement displaying posts in a list table.
Public Member Functions
__construct ($args=array())
Constructor.
ajax_user_can ()
column_author ($post)
Handles the post author column output.
column_cb ($post)
Handles the checkbox column output.
column_comments ($post)
Handles the comments column output.
column_date ($post)
Handles the post date column output.
column_default ($post, $column_name)
Handles the default column output.
column_title ($post)
Handles the title column output.
current_action ()
display_rows ($posts=array(), $level=0)
WP_Query $wp_query int $per_page
get_columns ()
has_items ()
inline_edit ()
Outputs the hidden row displayed when inline editing.
no_items ()
public
prepare_items ()
array $avail_post_stati WP_Query $wp_query int $per_page string $mode
set_hierarchical_display ($display)
Sets whether the table layout should be hierarchical or not.
single_row ($post, $level=0)
WP_Post $post
Public Member Functions inherited from WP_List_Table
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($args=array())
Constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
_js_vars ()
Send required variables to JavaScript land.
ajax_response ()
Handle an incoming ajax request (called from admin-ajax.php)
ajax_user_can ()
Checks the current user's permissions.
current_action ()
Get the current action selected from the bulk actions dropdown.
display ()
Display the table.
display_rows ()
Generate the table rows.
display_rows_or_placeholder ()
Generate the tbody element for the list table.
get_column_count ()
Return number of visible columns.
get_columns ()
Get a list of columns.
get_pagenum ()
Get the current page number.
get_pagination_arg ($key)
Access the pagination args.
get_primary_column ()
Public wrapper for WP_List_Table::get_default_primary_column_name().
has_items ()
Whether the table has items to display or not.
no_items ()
Message to be displayed when there are no items.
prepare_items ()
Prepares the list of items for displaying.
print_column_headers ($with_id=true)
Print column headers, accounting for hidden and sortable columns.
search_box ($text, $input_id)
Display the search box.
single_row ($item)
Generates content for a single row of the table.
views ()
Display the list of views available on this table.
Protected Member Functions
_column_title ($post, $classes, $data, $primary)
extra_tablenav ($which)
int $cat
get_bulk_actions ()
get_default_primary_column_name ()
Gets the name of the default primary column.
get_edit_link ($args, $label, $class= '')
Helper to create links to edit.php with params.
get_sortable_columns ()
get_table_classes ()
get_views ()
array $locked_post_status This seems to be deprecated.
handle_row_actions ($post, $column_name, $primary)
Generates and displays row action links.
is_base_request ()
Determine if the current view is the "All" view.
Protected Member Functions inherited from WP_List_Table
bulk_actions ($which= '')
Display the bulk actions dropdown.
column_cb ($item)
column_default ($item, $column_name)
comments_bubble ($post_id, $pending_comments)
Display a comment count bubble.
display_tablenav ($which)
Generate the table navigation above or below the table.
extra_tablenav ($which)
Extra controls to be displayed between bulk actions and pagination.
get_bulk_actions ()
Get an associative array (option_name => option_title) with the list of bulk actions available on this table.
get_column_info ()
Get a list of all, hidden and sortable columns, with filter applied.
get_default_primary_column_name ()
Gets the name of the default primary column.
get_items_per_page ($option, $default=20)
Get number of items to display on a single page.
get_primary_column_name ()
Gets the name of the primary column.
get_sortable_columns ()
Get a list of sortable columns.
get_table_classes ()
Get a list of CSS classes for the WP_List_Table table tag.
get_views ()
Get an associative array (id => link) with the list of views available on this table.
handle_row_actions ($item, $column_name, $primary)
Generates and display row actions links for the list table.
months_dropdown ($post_type)
Display a monthly dropdown for filtering items.
pagination ($which)
Display the pagination.
row_actions ($actions, $always_visible=false)
Generate row actions div.
set_pagination_args ($args)
An internal method that sets all the necessary pagination arguments.
single_row_columns ($item)
Generates the columns for a single row of the table.
view_switcher ($current_mode)
Display a view switcher.
Protected Attributes
$comment_pending_count
$current_level = 0
$hierarchical_display
Protected Attributes inherited from WP_List_Table
$_args
$_column_headers
$_pagination_args = array()
$compat_fields = array('_args', '_pagination_args', 'screen', '_actions', '_pagination')
{
$compat_methods
{
$modes = array()
$screen
Private Member Functions
_display_rows ($posts, $level=0)
_display_rows_hierarchical ($pages, $pagenum=1, $per_page=20)
wpdb $wpdb WP_Post $post
_page_rows (&$children_pages, &$count, $parent, $level, $pagenum, $per_page, &$to_display)
Given a top level page ID, display the nested hierarchy of sub-pages together with paging support.
Private Attributes
$is_trash
$sticky_posts_count = 0
$user_posts_count
Additional Inherited Members
Data Fields inherited from WP_List_Table
$items
Detailed Description
Core class used to implement displaying posts in a list table.
Since
3.1.0 private
See also
WP_List_Table
Definition at line 18 of file class-wp-posts-list-table.php.
Constructor & Destructor Documentation
__construct ($args = array())
Constructor.
Since
3.1.0 public
See also
WP_List_Table::__construct() for more information on default arguments.
object $post_type_object wpdb $wpdb
Parameters
array $args An associative array of arguments.
Definition at line 80 of file class-wp-posts-list-table.php.
References $post_type, $post_type_object, $wpdb, current_user_can(), get_current_user_id(), get_option(), get_post_stati(), get_post_type_object(), and null.
Member Function Documentation
_column_title ($post, $classes, $data, $primary) protected
Since
4.3.0 protected
Parameters
WP_Post $post
string $classes
string $data
string $primary
Definition at line 817 of file class-wp-posts-list-table.php.
References $post, column_title(), and handle_row_actions().
_display_rows ($posts, $level = 0) private
Parameters
array $posts
int $level
Definition at line 618 of file class-wp-posts-list-table.php.
References $post, get_pending_comments_num(), and single_row().
Referenced by display_rows().
_display_rows_hierarchical ($pages, $pagenum = 1, $per_page = 20) private
wpdb $wpdb WP_Post $post
Parameters
array $pages
int $pagenum
int $per_page
Definition at line 638 of file class-wp-posts-list-table.php.
References $count, $GLOBALS, $page, $pagenum, $wpdb, _page_rows(), _prime_post_caches(), clean_post_cache(), get_pages(), and single_row().
Referenced by display_rows().
_page_rows (& $children_pages, & $count, $parent, $level, $pagenum, $per_page, & $to_display) private
Given a top level page ID, display the nested hierarchy of sub-pages together with paging support.
Since
3.1.0 (Standalone function exists since 2.6.0)
4.2.0 Added the $to_display parameter.
Parameters
array $children_pages
int $count
int $parent
int $level
int $pagenum
int $per_page
array $to_display List of pages to be displayed. Passed by reference.
Definition at line 743 of file class-wp-posts-list-table.php.
References $count, $page, $pagenum, and get_post().
Referenced by _display_rows_hierarchical().
ajax_user_can ()
Returns
bool
Definition at line 127 of file class-wp-posts-list-table.php.
References current_user_can(), and get_post_type_object().
column_author ($post)
Handles the post author column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 1007 of file class-wp-posts-list-table.php.
References $post, get_edit_link(), get_the_author(), and get_the_author_meta().
column_cb ($post)
Handles the checkbox column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 798 of file class-wp-posts-list-table.php.
References $post, __, _draft_or_post_title(), current_user_can(), endif, input, label, and name.
column_comments ($post)
Handles the comments column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 987 of file class-wp-posts-list-table.php.
References $post, and WP_List_Table\comments_bubble().
column_date ($post)
Handles the post date column output.
Since
4.3.0 public
string $mode
Parameters
WP_Post $post The current WP_Post object.
Filter the published time of the post.
If $mode equals 'excerpt', the published time and date are both displayed. If $mode equals 'list' (default), the publish date is displayed, with the time and date together available as an abbreviation definition.
Since
2.5.1
Parameters
string $t_time The published time.
WP_Post $post Post object.
string $column_name The column name.
string $mode The list display mode ('excerpt' or 'list').
This filter is documented in wp-admin/includes/class-wp-posts-list-table.php
Definition at line 924 of file class-wp-posts-list-table.php.
References $mode, $post, __, _e, apply_filters(), elseif, get_post_time(), get_the_time(), human_time_diff(), and mysql2date().
column_default ($post, $column_name)
Handles the default column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
string $column_name The current column name.
Fires in each custom column on the Posts list table.
This hook only fires if the current post type is hierarchical, such as pages.
Since
2.5.0
Parameters
string $column_name The name of the column to display.
int $post_id The current post ID.
Fires in each custom column in the Posts list table.
This hook only fires if the current post type is non-hierarchical, such as posts.
Since
1.5.0
Parameters
string $column_name The name of the column to display.
int $post_id The current post ID.
Fires for each custom column of a specific post type in the Posts list table.
The dynamic portion of the hook name, $post->post_type, refers to the post type.
Since
3.1.0
Parameters
string $column_name The name of the column to display.
int $post_id The current post ID.
Definition at line 1024 of file class-wp-posts-list-table.php.
References $label, $out, $post, __, do_action(), elseif, esc_html, get_edit_link(), get_taxonomy(), get_the_terms(), is_post_type_hierarchical(), and sanitize_term_field().
column_title ($post)
Handles the title column output.
Since
4.3.0 public
string $mode
Parameters
WP_Post $post The current WP_Post object.
This filter is documented in wp-includes/post-template.php
Definition at line 834 of file class-wp-posts-list-table.php.
References $format, $label, $mode, $post, $post_type_object, $title, __, _draft_or_post_title(), _post_states(), apply_filters(), current_user_can(), esc_attr(), esc_html, get_edit_link(), get_edit_post_link(), get_inline_data(), get_post(), get_post_format(), get_post_format_string(), get_post_type_object(), if, is_post_type_hierarchical(), the_excerpt(), and wp_check_post_lock().
Referenced by _column_title().
current_action ()
Returns
string
Definition at line 478 of file class-wp-posts-list-table.php.
References current_action().
display_rows ($posts = array(), $level = 0)
WP_Query $wp_query int $per_page
Parameters
array $posts
int $level
Definition at line 599 of file class-wp-posts-list-table.php.
References _display_rows(), _display_rows_hierarchical(), add_filter(), and WP_List_Table\get_pagenum().
extra_tablenav ($which) protected
int $cat
Parameters
string $which
Fires before the Filter button on the Posts and Pages list tables.
The Filter button allows sorting by date and/or category on the Posts list table, and sorting by date on the Pages list table.
Since
2.1.0
4.4.0 The $post_type parameter was added.
Parameters
string $post_type The post type slug.
Fires immediately following the closing "actions" div in the tablenav for the posts list table.
Since
4.4.0
Parameters
string $which The location of the extra table nav markup: 'top' or 'bottom'.
Definition at line 418 of file class-wp-posts-list-table.php.
References __, current_user_can(), do_action(), get_post_type_object(), is_object_in_taxonomy(), is_singular(), WP_List_Table\months_dropdown(), submit_button(), and wp_dropdown_categories().
get_bulk_actions () protected
Returns
array
Definition at line 391 of file class-wp-posts-list-table.php.
References __, current_user_can(), and get_post_type_object().
get_columns ()
Returns
array
Filter the taxonomy columns in the Posts list table.
The dynamic portion of the hook name, $post_type, refers to the post type slug.
Since
3.5.0
Parameters
array $taxonomies Array of taxonomies to show columns for.
string $post_type The post type.
Filter the columns displayed in the Pages list table.
Since
2.5.0
Parameters
array $post_columns An array of column names.
Filter the columns displayed in the Posts list table.
Since
1.5.0
Parameters
array $posts_columns An array of column names.
string $post_type The post type slug.
Filter the columns displayed in the Posts list table for a specific post type.
The dynamic portion of the hook name, $post_type, refers to the post type slug.
Since
3.0.0
Parameters
array $post_columns An array of column names.
Definition at line 497 of file class-wp-posts-list-table.php.
References $post_type, __, _x, apply_filters(), elseif, esc_attr__(), get_object_taxonomies(), get_taxonomy(), post_type_supports(), and wp_filter_object_list().
get_default_primary_column_name () protected
Gets the name of the default primary column.
Since
4.3.0 protected
Returns
string Name of the default primary column, in this case, 'title'.
Definition at line 1149 of file class-wp-posts-list-table.php.
get_edit_link ($args, $label, $class = '') protected
Helper to create links to edit.php with params.
Since
4.4.0 protected
Parameters
array $args URL parameters for the link.
string $label Link text.
string $class Optional. Class attribute. Default empty string.
Returns
string The formatted link string.
Definition at line 239 of file class-wp-posts-list-table.php.
References $class, $label, $url, add_query_arg(), esc_attr(), and esc_url.
Referenced by column_author(), column_default(), column_title(), and get_views().
get_sortable_columns () protected
Returns
array
Definition at line 584 of file class-wp-posts-list-table.php.
get_table_classes () protected
Returns
array
Definition at line 489 of file class-wp-posts-list-table.php.
References is_post_type_hierarchical().
get_views () protected
array $locked_post_status This seems to be deprecated.
array $avail_post_stati
Returns
array
Definition at line 264 of file class-wp-posts-list-table.php.
References $class, $post_type, _nx(), get_current_user_id(), get_edit_link(), get_post_stati(), is_base_request(), number_format_i18n(), translate_nooped_plural(), and wp_count_posts().
handle_row_actions ($post, $column_name, $primary) protected
Generates and displays row action links.
Since
4.3.0 protected
Parameters
object $post Post being acted upon.
string $column_name Current column name.
string $primary Primary column name.
Returns
string Row actions output for posts.
Filter the array of row action links on the Pages list table.
The filter is evaluated only for hierarchical post types.
Since
2.8.0
Parameters
array $actions An array of row action links. Defaults are 'Edit', 'Quick Edit', 'Restore, 'Trash', 'Delete Permanently', 'Preview', and 'View'.
WP_Post $post The post object.
Filter the array of row action links on the Posts list table.
The filter is evaluated only for non-hierarchical post types.
Since
2.8.0
Parameters
array $actions An array of row action links. Defaults are 'Edit', 'Quick Edit', 'Restore, 'Trash', 'Delete Permanently', 'Preview', and 'View'.
WP_Post $post The post object.
Definition at line 1164 of file class-wp-posts-list-table.php.
References $post, $post_type_object, $title, __, _draft_or_post_title(), _x, admin_url(), apply_filters(), current_user_can(), elseif, esc_attr(), esc_attr__(), esc_url, get_delete_post_link(), get_edit_post_link(), get_permalink(), get_post_type_object(), get_preview_post_link(), is_post_type_hierarchical(), is_post_type_viewable(), WP_List_Table\row_actions(), set_url_scheme(), and wp_nonce_url().
Referenced by _column_title().
has_items ()
Returns
bool
Definition at line 194 of file class-wp-posts-list-table.php.
References have_posts().
inline_edit ()
Outputs the hidden row displayed when inline editing.
Since
3.1.0
string $mode
Filter whether the current taxonomy should be shown in the Quick Edit panel.
Since
4.2.0
Parameters
bool $show_in_quick_edit Whether to show the current taxonomy in Quick Edit.
string $taxonomy_name Taxonomy name.
string $post_type Post type of current Quick Edit post.
Filter the arguments used to generate the Quick Edit page-parent drop-down.
Since
2.7.0
See also
wp_dropdown_pages()
Parameters
array $dropdown_args An array of arguments.
This filter is documented in wp-admin/includes/meta-boxes.php
Fires once for each column in Bulk Edit mode.
Since
2.7.0
Parameters
string $column_name Name of the column to edit.
WP_Post $post_type The post type slug.
Fires once for each column in Quick Edit mode.
Since
2.7.0
Parameters
string $column_name Name of the column to edit.
string $post_type The post type slug.
Definition at line 1242 of file class-wp-posts-list-table.php.
References $authors, $columns, $dropdown_args, $format, $mode, $post, $post_formats, $post_type_object, WP_List_Table\$screen, __, _e, _ex(), apply_filters(), current_theme_supports(), current_user_can(), do_action(), endforeach, endif, esc_html, WP_List_Table\get_column_info(), get_default_post_to_edit(), get_object_taxonomies(), get_post_format_string(), get_post_type_object(), get_taxonomy(), get_theme_support(), input, is_super_admin(), label, name, null, page_template_dropdown(), post_type_supports(), submit_button(), textarea, touch_time(), wp_dropdown_pages(), wp_dropdown_users(), wp_nonce_field(), and wp_terms_checklist().
is_base_request () protected
Determine if the current view is the "All" view.
Since
4.2.0
Returns
bool Whether the current view is the "All" view.
Definition at line 215 of file class-wp-posts-list-table.php.
References elseif.
Referenced by get_views().
no_items ()
public
Definition at line 201 of file class-wp-posts-list-table.php.
References get_post_type_object().
prepare_items ()
array $avail_post_stati WP_Query $wp_query int $per_page string $mode
This filter is documented in wp-admin/includes/post.php
Definition at line 138 of file class-wp-posts-list-table.php.
References $mode, $post_type, $sticky_posts_count, $user_posts_count, apply_filters(), elseif, get_current_user_id(), WP_List_Table\get_items_per_page(), get_post_stati(), get_user_setting(), is_post_type_hierarchical(), set_hierarchical_display(), WP_List_Table\set_pagination_args(), set_user_setting(), wp_count_posts(), and wp_edit_posts_query().
set_hierarchical_display ($display)
Sets whether the table layout should be hierarchical or not.
Since
4.2.0
Parameters
bool $display Whether the table layout should be hierarchical.
Definition at line 119 of file class-wp-posts-list-table.php.
Referenced by prepare_items().
single_row ($post, $level = 0)
WP_Post $post
Parameters
int | WP_Post $post
int $level
Definition at line 1111 of file class-wp-posts-list-table.php.
References $count, $GLOBALS, $post, get_current_user_id(), get_post(), get_post_ancestors(), setup_postdata(), WP_List_Table\single_row_columns(), and wp_check_post_lock().
Referenced by _display_rows(), and _display_rows_hierarchical().
Field Documentation
$comment_pending_count protected
Definition at line 36 of file class-wp-posts-list-table.php.
$current_level = 0 protected
Definition at line 65 of file class-wp-posts-list-table.php.
$hierarchical_display protected
Definition at line 27 of file class-wp-posts-list-table.php.
$is_trash private
Definition at line 56 of file class-wp-posts-list-table.php.
$sticky_posts_count = 0 private
Definition at line 54 of file class-wp-posts-list-table.php.
Referenced by prepare_items().
$user_posts_count private
Definition at line 45 of file class-wp-posts-list-table.php.
Referenced by prepare_items().
The documentation for this class was generated from the following file:
class-wp-posts-list-table.php