GravityView: GF_Form Class Reference
GF_Form Class Reference
If this file is called directly, abort.
Public Member Functions
__get ($key)
Proxies.
get_fields ()
Get an array of GV Fields for this data source.
offsetExists ($offset)
ArrayAccess compatibility layer with a Gravity Forms form array.
offsetGet ($offset)
ArrayAccess compatibility layer with a Gravity Forms form array.
offsetSet ($offset, $value)
ArrayAccess compatibility layer with a Gravity Forms form array.
offsetUnset ($offset)
ArrayAccess compatibility layer with a Gravity Forms form array.
Public Member Functions inherited from Form
__get ($key)
Magic shortcuts.
get_entries ()
Get all entries for this form.
Static Public Member Functions
static by_id ($form_id)
Construct a instance by ID.
static from_form ($form)
Construct a instance from a Gravity Forms form array.
static get_field ()
Get a by Form and Field ID for this data source.
Static Public Member Functions inherited from Form
static by_id ($form_id)
Construct a instance by ID.
Static Public Member Functions inherited from Source
static get_field ()
Get a instance by ID.
Static Public Attributes
static $backend = self::BACKEND_GRAVITYFORMS
Static Public Attributes inherited from Source
static $backend = null
Private Member Functions
__construct ()
Initialization.
Additional Inherited Members
Data Fields inherited from Form
$ID = null
Data Fields inherited from Source
const BACKEND_GRAVITYFORMS = 'gravityforms'
const BACKEND_INTERNAL = 'internal'
Detailed Description
If this file is called directly, abort.
The Gravity Forms Form class implementation.
Accessible as an array for back-compatibility.
Definition at line 14 of file class-gv-form-gravityforms.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Initialization.
Definition at line 26 of file class-gv-form-gravityforms.php.
References gravityview().
Member Function Documentation
__get()
__get ($key)
Proxies.
Parameters
string $key The property to get.
Returns
mixed
Definition at line 203 of file class-gv-form-gravityforms.php.
by_id()
static by_id ($form_id) static
Construct a instance by ID.
Parameters
int | string $form_id The internal form ID.
Since
2.0
Returns
|null An instance of this form or null if not found.
Definition at line 41 of file class-gv-form-gravityforms.php.
References GV\$form, and $form_id.
Referenced by GV\Mocks\GravityView_API_field_label(), GV\Mocks\GravityView_API_field_value(), and GV\Mocks\GravityView_frontend_get_view_entries().
from_form()
static from_form ($form) static
Construct a instance from a Gravity Forms form array.
Since
2.0.7
Parameters
array $form The form array
Returns
|null An instance of this form or null if not found.
Definition at line 72 of file class-gv-form-gravityforms.php.
References $entries, $entry, $filter, GV\$form, and $search_criteria.
get_field()
static get_field () static
Get a by Form and Field ID for this data source.
Parameters
\GV\GF_Form $form The Gravity Form form ID.
int $field_id The Gravity Form field ID for the $form_id.
Returns
|null The requested field or null if not found.
Unwrap the arguments.
Wrap it up into a .
Definition at line 161 of file class-gv-form-gravityforms.php.
References $field_id, GV\$form, and gravityview().
get_fields()
get_fields ()
Get an array of GV Fields for this data source.
Returns
[]|array Empty array if no fields
Definition at line 181 of file class-gv-form-gravityforms.php.
References $field.
offsetExists()
offsetExists ($offset)
ArrayAccess compatibility layer with a Gravity Forms form array.
Definition at line 220 of file class-gv-form-gravityforms.php.
offsetGet()
offsetGet ($offset)
ArrayAccess compatibility layer with a Gravity Forms form array.
Maps the old keys to the new data;
Definition at line 235 of file class-gv-form-gravityforms.php.
offsetSet()
offsetSet ($offset, $value)
ArrayAccess compatibility layer with a Gravity Forms form array.
Definition at line 248 of file class-gv-form-gravityforms.php.
References gravityview().
offsetUnset()
offsetUnset ($offset)
ArrayAccess compatibility layer with a Gravity Forms form array.
Definition at line 260 of file class-gv-form-gravityforms.php.
References gravityview().
Field Documentation
$backend
$backend = self::BACKEND_GRAVITYFORMS static
Definition at line 21 of file class-gv-form-gravityforms.php.
The documentation for this class was generated from the following file:
class-gv-form-gravityforms.php