GravityView: SimplePie_HTTP_Parser Class Reference
SimplePie_HTTP_Parser Class Reference
Public Member Functions
__construct ($data)
Create an instance of the class with the input data.
parse ()
Parse the input data.
Data Fields
$body = ''
$headers = array()
$http_version = 0.0
$reason = ''
$status_code = 0
Protected Member Functions
body ()
Parse the body.
chunked ()
Parsed a "Transfer-Encoding: chunked" body.
has_data ()
Check whether there is data beyond the pointer.
http_version ()
Parse the HTTP version.
is_linear_whitespace ()
See if the next character is LWS.
linear_whitespace ()
Parse LWS, replacing consecutive LWS characters with a single space.
name ()
Parse a header name.
new_line ()
Deal with a new line, shifting data around as needed.
quote ()
See what state to move to while within quoted header values.
quote_char ()
Parse a header value while within quotes.
quote_escaped ()
Parse an escaped character within quotes.
reason ()
Parse the reason phrase.
status ()
Parse the status code.
value ()
See what state to move to while within non-quoted header values.
value_char ()
Parse a header value while outside quotes.
Protected Attributes
$data = ''
$data_length = 0
$name = ''
$position = 0
$state = 'http_version'
$value = ''
Detailed Description
Definition at line 52 of file HTTP/Parser.php.
Constructor & Destructor Documentation
__construct ($data)
Create an instance of the class with the input data.
Parameters
string $data Input data
Definition at line 136 of file HTTP/Parser.php.
References $data.
Member Function Documentation
body () protected
Parse the body.
Definition at line 441 of file HTTP/Parser.php.
Referenced by chunked(), and parse().
chunked () protected
Parsed a "Transfer-Encoding: chunked" body.
Definition at line 458 of file HTTP/Parser.php.
References $body, and body().
has_data () protected
Check whether there is data beyond the pointer.
Returns
bool true if there is further data, false if not
Definition at line 175 of file HTTP/Parser.php.
References $data_length.
Referenced by linear_whitespace(), and parse().
http_version () protected
Parse the HTTP version.
Definition at line 197 of file HTTP/Parser.php.
Referenced by parse().
is_linear_whitespace () protected
See if the next character is LWS.
Returns
bool true if the next character is LWS, false if not
Definition at line 185 of file HTTP/Parser.php.
References $position.
Referenced by linear_whitespace(), quote(), and value().
linear_whitespace () protected
Parse LWS, replacing consecutive LWS characters with a single space.
Definition at line 315 of file HTTP/Parser.php.
References elseif, has_data(), is_linear_whitespace(), and value().
Referenced by quote(), and value().
name () protected
Parse a header name.
Definition at line 289 of file HTTP/Parser.php.
Referenced by new_line(), and value().
new_line () protected
Deal with a new line, shifting data around as needed.
Definition at line 252 of file HTTP/Parser.php.
References $name, $value, elseif, name(), and value().
parse ()
Parse the input data.
Returns
bool true on success, false on failure
Definition at line 147 of file HTTP/Parser.php.
References $state, body(), has_data(), http_version(), and reason().
quote () protected
See what state to move to while within quoted header values.
Definition at line 385 of file HTTP/Parser.php.
References is_linear_whitespace(), and linear_whitespace().
quote_char () protected
Parse a header value while within quotes.
Definition at line 420 of file HTTP/Parser.php.
References value().
quote_escaped () protected
Parse an escaped character within quotes.
Definition at line 431 of file HTTP/Parser.php.
References $position, and value().
reason () protected
Parse the reason phrase.
Definition at line 241 of file HTTP/Parser.php.
Referenced by parse().
status () protected
Parse the status code.
Definition at line 224 of file HTTP/Parser.php.
value () protected
See what state to move to while within non-quoted header values.
Definition at line 335 of file HTTP/Parser.php.
References is_linear_whitespace(), linear_whitespace(), and name().
Referenced by linear_whitespace(), new_line(), quote_char(), quote_escaped(), and value_char().
value_char () protected
Parse a header value while outside quotes.
Definition at line 374 of file HTTP/Parser.php.
References value().
Field Documentation
$body = ''
Definition at line 87 of file HTTP/Parser.php.
Referenced by chunked().
$data = '' protected
Definition at line 101 of file HTTP/Parser.php.
Referenced by __construct().
$data_length = 0 protected
Definition at line 108 of file HTTP/Parser.php.
Referenced by has_data().
$headers = array()
Definition at line 80 of file HTTP/Parser.php.
$http_version = 0.0
Definition at line 59 of file HTTP/Parser.php.
$name = '' protected
Definition at line 122 of file HTTP/Parser.php.
Referenced by new_line().
$position = 0 protected
Definition at line 115 of file HTTP/Parser.php.
Referenced by is_linear_whitespace(), and quote_escaped().
$reason = ''
Definition at line 73 of file HTTP/Parser.php.
$state = 'http_version' protected
Definition at line 94 of file HTTP/Parser.php.
Referenced by parse().
$status_code = 0
Definition at line 66 of file HTTP/Parser.php.
$value = '' protected
Definition at line 129 of file HTTP/Parser.php.
Referenced by new_line().
The documentation for this class was generated from the following file:
HTTP/Parser.php