GravityView: AbstractLogger Class Reference
AbstractLogger Class Reference
This is a simple Logger implementation that other Loggers can inherit from.
Public Member Functions
alert ($message, array $context=array())
Action must be taken immediately.
critical ($message, array $context=array())
Critical conditions.
debug ($message, array $context=array())
Detailed debug information.
emergency ($message, array $context=array())
System is unusable.
error ($message, array $context=array())
Runtime errors that do not require immediate action but should typically be logged and monitored.
info ($message, array $context=array())
Interesting events.
notice ($message, array $context=array())
Normal but significant events.
warning ($message, array $context=array())
Exceptional occurrences that are not errors.
Public Member Functions inherited from LoggerInterface
log ($level, $message, array $context=array())
Logs with an arbitrary level.
Detailed Description
This is a simple Logger implementation that other Loggers can inherit from.
It simply delegates all log-level-specific methods to the log method to reduce boilerplate code that a simple Logger that does the same thing with messages regardless of the error level has to implement.
Definition at line 18 of file AbstractLogger.php.
Member Function Documentation
alert()
alert ($message, array $context = array())
Action must be taken immediately.
Example: Entire website down, database unavailable, etc. This should trigger the SMS alerts and wake you up.
Parameters
string $message
mixed[] $context
Returns
void
Implements LoggerInterface.
Definition at line 44 of file AbstractLogger.php.
References LogLevel\ALERT, and LoggerInterface\log().
critical()
critical ($message, array $context = array())
Critical conditions.
Example: Application component unavailable, unexpected exception.
Parameters
string $message
mixed[] $context
Returns
void
Implements LoggerInterface.
Definition at line 59 of file AbstractLogger.php.
References LogLevel\CRITICAL, and LoggerInterface\log().
debug()
debug ($message, array $context = array())
Detailed debug information.
Parameters
string $message
mixed[] $context
Returns
void
Implements LoggerInterface.
Definition at line 130 of file AbstractLogger.php.
References LogLevel\DEBUG, and LoggerInterface\log().
emergency()
emergency ($message, array $context = array())
System is unusable.
Parameters
string $message
mixed[] $context
Returns
void
Implements LoggerInterface.
Definition at line 28 of file AbstractLogger.php.
References LogLevel\EMERGENCY, and LoggerInterface\log().
error()
error ($message, array $context = array())
Runtime errors that do not require immediate action but should typically be logged and monitored.
Parameters
string $message
mixed[] $context
Returns
void
Implements LoggerInterface.
Definition at line 73 of file AbstractLogger.php.
References LogLevel\ERROR, and LoggerInterface\log().
info()
info ($message, array $context = array())
Interesting events.
Example: User logs in, SQL logs.
Parameters
string $message
mixed[] $context
Returns
void
Implements LoggerInterface.
Definition at line 117 of file AbstractLogger.php.
References LogLevel\INFO, and LoggerInterface\log().
notice()
notice ($message, array $context = array())
Normal but significant events.
Parameters
string $message
mixed[] $context
Returns
void
Implements LoggerInterface.
Definition at line 102 of file AbstractLogger.php.
References LoggerInterface\log(), and LogLevel\NOTICE.
warning()
warning ($message, array $context = array())
Exceptional occurrences that are not errors.
Example: Use of deprecated APIs, poor use of an API, undesirable things that are not necessarily wrong.
Parameters
string $message
mixed[] $context
Returns
void
Implements LoggerInterface.
Definition at line 89 of file AbstractLogger.php.
References LoggerInterface\log(), and LogLevel\WARNING.
The documentation for this class was generated from the following file:
AbstractLogger.php