GravityView: Framework Class Reference
Framework Class Reference
Public Member Functions
add_gk_submenu_item ()
Adds Settings submenu to the GravityKit top-level admin menu.
are_setting_requirements_met ($plugin_setting, $settings)
Determines if a setting's requirements are met based on the value(s) of other setting(s).
configure_ajax_routes (array $routes)
Configures AJAX routes handled by this class.
enqueue_assets ($page)
Enqueues UI assets.
get_all_settings ($site_id=null)
Gets settings for all GravityKit plugins.
get_default_settings ($plugin_id=null)
Returns default settings for a plugin all plugins.
get_plugin_setting ($plugin, $plugin_setting_name, $default=null, $site_id=null)
Gets a single setting for a GravityKit plugin.
get_plugin_settings ($plugin, $site_id=null)
Get all settings for a GravityKit plugin.
get_plugin_settings_url ($plugin_id)
Returns link to the plugin settings page.
get_plugins_settings_data ()
Returns settings data object for all plugins.
init ()
Initializes Settings framework.
save_all_settings (array $settings, $site_id=null)
Saves settings for all GravityKit plugins.
save_plugin_setting ($plugin, $plugin_setting_name, $plugin_setting_value, $site_id=null)
Saves a single setting for a GravityKit plugin.
save_plugin_settings ($plugin, array $plugin_settings, $site_id=null)
Saves all settings for a GravityKit plugin.
save_ui_settings (array $settings_data)
Saves UI settings.
Static Public Member Functions
static get_instance ()
Returns class instance.
Data Fields
const AJAX_ROUTER = 'settings'
const ID = 'gk_settings'
Private Member Functions
__construct ()
Private Attributes
$_capability = 'manage_options'
$_settings_data = []
$_validator
Static Private Attributes
static $_instance
Detailed Description
Definition at line 19 of file Settings/Framework.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Runs Filter:
gk/foundation/settings/capability Modifies capability to access GravityKit Settings.
Since
1.0.0
Parameters
string $capability Capability.
Definition at line 54 of file Settings/Framework.php.
Member Function Documentation
add_gk_submenu_item()
add_gk_submenu_item ()
Adds Settings submenu to the GravityKit top-level admin menu.
Since
1.0.0
Returns
void
Definition at line 341 of file Settings/Framework.php.
References AdminMenu\add_submenu_item().
Referenced by Framework\init().
are_setting_requirements_met()
are_setting_requirements_met ($plugin_setting, $settings)
Determines if a setting's requirements are met based on the value(s) of other setting(s).
Since
1.0.0
Parameters
array $plugin_setting Individual plugin setting as configured using the gk/foundation/settings/data/plugins filter.
array $settings Setting ID:value pairs.
Returns
bool
Definition at line 582 of file Settings/Framework.php.
References $settings, and Helpers\compare_values().
Referenced by Framework\save_ui_settings().
configure_ajax_routes()
configure_ajax_routes (array $routes)
Configures AJAX routes handled by this class.
Since
1.0.0
See also
FoundationCore::process_ajax_request()
Parameters
array $routes AJAX route to class method map.
Returns
array
Definition at line 121 of file Settings/Framework.php.
enqueue_assets()
enqueue_assets ($page)
Enqueues UI assets.
Since
1.0.0
Parameters
string $page Current page.
Returns
void
Runs Filter:
gk/foundation/settings/data/config Modifies global settings configuration.
Since
1.0.0 Introduced but not (yet) used.
Parameters
array $config Configuration.
Definition at line 379 of file Settings/Framework.php.
References Framework\get_plugin_settings_url(), Framework\get_plugins_settings_data(), Arr\pluck(), and AdminMenu\remove_submenu_item().
get_all_settings()
get_all_settings ($site_id = null)
Gets settings for all GravityKit plugins.
Since
1.0.0
Parameters
int | null $site_id (optional) Site ID for which to get settings. Default is null (i.e, current site ID).
Returns
array
Definition at line 136 of file Settings/Framework.php.
References Framework\get_default_settings(), and Framework\get_plugins_settings_data().
Referenced by Framework\get_plugin_settings(), and Framework\save_plugin_settings().
get_default_settings()
get_default_settings ($plugin_id = null)
Returns default settings for a plugin all plugins.
Default settings are defined in the plugin's settings object under the defaults key.
Since
1.0.3
Parameters
$plugin_id
Returns
array|array[]
Definition at line 199 of file Settings/Framework.php.
References Arr\get(), and Framework\get_plugins_settings_data().
Referenced by Framework\get_all_settings().
get_instance()
static get_instance () static
Returns class instance.
Since
1.0.0
Returns
Framework
Definition at line 74 of file Settings/Framework.php.
get_plugin_setting()
get_plugin_setting ($plugin, $plugin_setting_name, $default = null, $site_id = null)
Gets a single setting for a GravityKit plugin.
Since
1.0.0
Parameters
string $plugin Plugin ID as specified in the settings object.
string $plugin_setting_name Setting name as specified in the settings object.
null | array | mixed $default (optional) Default value to return if the setting is not found. Default is null.
int | null $site_id (optional) Site ID for which to get settings. Default is null (i.e., current site ID). *
Returns
mixed|null
Definition at line 245 of file Settings/Framework.php.
References Framework\get_plugin_settings().
get_plugin_settings()
get_plugin_settings ($plugin, $site_id = null)
Get all settings for a GravityKit plugin.
Since
1.0.0
Parameters
string $plugin
int | null $site_id (optional) Site ID for which to get settings. Default is null (i.e., current site ID).
Returns
array
Definition at line 294 of file Settings/Framework.php.
References $settings, and Framework\get_all_settings().
Referenced by Framework\get_plugin_setting(), and Framework\save_plugin_setting().
get_plugin_settings_url()
get_plugin_settings_url ($plugin_id)
Returns link to the plugin settings page.
Since
1.0.3
Parameters
string $plugin_id
Returns
string
Definition at line 363 of file Settings/Framework.php.
Referenced by Framework\enqueue_assets().
get_plugins_settings_data()
get_plugins_settings_data ()
Returns settings data object for all plugins.
Since
1.0.3
Returns
array
Runs Filter:
gk/foundation/settings/data/plugins Modifies plugins' settings.
Since
1.0.0
Parameters
array $plugins_data Plugins data.
Definition at line 169 of file Settings/Framework.php.
Referenced by Framework\enqueue_assets(), Framework\get_all_settings(), Framework\get_default_settings(), and Framework\save_ui_settings().
init()
init ()
Initializes Settings framework.
Since
1.0.0
Returns
void
Runs Actions:
gk/foundation/settings/initialized Fires when the class has finished initializing.
Since
1.0.0
Parameters
$this
Definition at line 89 of file Settings/Framework.php.
References Framework\add_gk_submenu_item().
save_all_settings()
save_all_settings (array $settings, $site_id = null)
Saves settings for all GravityKit plugins.
Since
1.0.0
Parameters
array $settings
int | null $site_id (optional) Site ID for which to save settings. Default is null (i.e., current site ID).
Returns
bool
Definition at line 225 of file Settings/Framework.php.
References $settings.
Referenced by Framework\save_plugin_settings().
save_plugin_setting()
save_plugin_setting ($plugin, $plugin_setting_name, $plugin_setting_value, $site_id = null)
Saves a single setting for a GravityKit plugin.
Since
1.0.0
Parameters
string $plugin
string $plugin_setting_name
mixed $plugin_setting_value
int | null $site_id (optional) Site ID for which to save settings. Default is null (i.e., current site ID).
Returns
bool
Definition at line 274 of file Settings/Framework.php.
References Framework\get_plugin_settings(), and Framework\save_plugin_settings().
save_plugin_settings()
save_plugin_settings ($plugin, array $plugin_settings, $site_id = null)
Saves all settings for a GravityKit plugin.
Since
1.0.0
Parameters
string $plugin
array $plugin_settings
int | null $site_id (optional) Site ID for which to save settings. Default is null (i.e, current site ID).
Returns
bool
Runs Filter:
gk/foundation/settings/{plugin}/save/before Modifies plugin settings object before saving.
Since
1.0.0
Parameters
array $settings Plugin settings.
Definition at line 313 of file Settings/Framework.php.
References Framework\get_all_settings(), and Framework\save_all_settings().
Referenced by Framework\save_plugin_setting(), and Framework\save_ui_settings().
save_ui_settings()
save_ui_settings (array $settings_data)
Saves UI settings.
Since
1.0.0
Parameters
array $settings_data
Exceptions
Exception
Returns
mixed|void Exit with JSON response or return response message.
Runs Filter:
gk/foundation/settings/${plugin}/validation/before Modifies plugin settings object before validation.
Since
1.0.0
Parameters
array $ui_settings Settings.
Runs Filter:
gk/foundation/settings/${plugin}/validation/after Modifies plugin settings object after validation.
Since
1.0.0
Parameters
array $ui_settings Settings.
Definition at line 470 of file Settings/Framework.php.
References $value, Framework\are_setting_requirements_met(), Framework\get_plugins_settings_data(), and Framework\save_plugin_settings().
Field Documentation
$_capability
$_capability = 'manage_options' private
Definition at line 38 of file Settings/Framework.php.
$_instance
$_instance static private
Definition at line 31 of file Settings/Framework.php.
$_settings_data
$_settings_data = [] private
Definition at line 52 of file Settings/Framework.php.
$_validator
$_validator private
Definition at line 45 of file Settings/Framework.php.
AJAX_ROUTER
const AJAX_ROUTER = 'settings'
Definition at line 22 of file Settings/Framework.php.
ID
const ID = 'gk_settings'
Definition at line 20 of file Settings/Framework.php.
The documentation for this class was generated from the following file:
Settings/Framework.php