GravityView: WP_Query Class Reference
WP_Query Class Reference
The WordPress Query class.
Public Member Functions
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($query= '')
Constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
fill_query_vars ($array)
Fills in the query variables, which do not exist within the parameter.
get ($query_var, $default= '')
Retrieve query variable.
get_posts ()
Retrieve the posts based on query variables.
get_queried_object ()
Retrieve queried object.
get_queried_object_id ()
Retrieve ID of the current queried object.
have_comments ()
Whether there are more comments available.
have_posts ()
Whether there are more posts available in the loop.
init ()
Initiates object properties and sets default values.
is_404 ()
Is the query a 404 (returns no results)?
is_archive ()
Is the query for an existing archive page?
is_attachment ($attachment= '')
Is the query for an existing attachment page?
is_author ($author= '')
Is the query for an existing author archive page?
is_category ($category= '')
Is the query for an existing category archive page?
is_comment_feed ()
Is the query for a comments feed?
is_comments_popup ()
Whether the current URL is within the comments popup window.
is_date ()
Is the query for an existing date archive?
is_day ()
Is the query for an existing day archive?
is_embed ()
Is the query for an embedded post?
is_feed ($feeds= '')
Is the query for a feed?
is_front_page ()
Is the query for the front page of the site?
is_home ()
Is the query for the blog homepage?
is_main_query ()
Is the query the main query?
is_month ()
Is the query for an existing month archive?
is_page ($page= '')
Is the query for an existing single page?
is_paged ()
Is the query for paged result and not for the first page?
is_post_type_archive ($post_types= '')
Is the query for an existing post type archive page?
is_preview ()
Is the query for a post or page preview?
is_robots ()
Is the query for the robots file?
is_search ()
Is the query for a search?
is_single ($post= '')
Is the query for an existing single post?
is_singular ($post_types= '')
Is the query for an existing single post of any post type (post, attachment, page, ...
is_tag ($tag= '')
Is the query for an existing tag archive page?
is_tax ($taxonomy= '', $term= '')
Is the query for an existing taxonomy archive page?
is_time ()
Is the query for a specific time?
is_trackback ()
Is the query for a trackback endpoint call?
is_year ()
Is the query for an existing year archive?
lazyload_comment_meta ($check, $comment_id)
Lazy-load comment meta when inside of a WP_Query loop.
lazyload_term_meta ($check, $term_id)
Lazy-loads termmeta for located posts.
next_comment ()
Iterate current comment index and return WP_Comment object.
next_post ()
Set up the next post and iterate current post index.
parse_query ($query= '')
Parse a query string and set query type booleans.
parse_query_vars ()
Reparse the query vars.
parse_tax_query (&$q)
Parses various taxonomy related query vars.
query ($query)
Sets up the WordPress query by parsing query string.
reset_postdata ()
After looping through a nested query, this function restores the $post global to the current post in this query.
rewind_comments ()
Rewind the comments, resets the comment index and comment to first.
rewind_posts ()
Rewind the posts and reset post index.
set ($query_var, $value)
Set query variable.
set_404 ()
Sets the 404 property and saves whether query is feed.
setup_postdata ($post)
Set up global post data.
the_comment ()
Sets up the current comment.
the_post ()
Sets up the current post.
Data Fields
$comment
$comment_count = 0
$comments
$current_comment = -1
$current_post = -1
$date_query = false
$found_posts = 0
$in_the_loop = false
$is_404 = false
$is_admin = false
$is_archive = false
$is_attachment = false
$is_author = false
$is_category = false
$is_comment_feed = false
$is_date = false
$is_day = false
$is_embed = false
$is_feed = false
$is_home = false
$is_month = false
$is_page = false
$is_paged = false
$is_post_type_archive = false
$is_posts_page = false
$is_preview = false
$is_robots = false
$is_search = false
$is_single = false
$is_singular = false
$is_tag = false
$is_tax = false
$is_time = false
$is_trackback = false
$is_year = false
$max_num_comment_pages = 0
$max_num_pages = 0
$meta_query = false
$post
$post_count = 0
$posts
$queried_object
$queried_object_id
$query
$query_vars = array()
$request
$tax_query
$thumbnails_cached = false
$updated_comment_meta_cache = false
$updated_term_meta_cache = false
Protected Member Functions
get_search_stopwords ()
Retrieve stopwords used when parsing search terms.
parse_order ($order)
Parse an 'order' query variable and cast it to ASC or DESC as necessary.
parse_orderby ($orderby)
If the passed orderby value is allowed, convert the alias to a properly-prefixed orderby value.
parse_search (&$q)
Generate SQL for the WHERE clause based on passed search terms.
parse_search_order (&$q)
Generate SQL for the ORDER BY condition based on passed search terms.
parse_search_terms ($terms)
Check if the terms are suitable for searching.
Private Member Functions
init_query_flags ()
Resets query flags to false.
set_found_posts ($q, $limits)
Set up the amount of found posts and the number of pages (if limit clause was used) for the current query.
Private Attributes
$compat_fields = array('query_vars_hash', 'query_vars_changed')
$compat_methods = array('init_query_flags', 'parse_tax_query')
$query_vars_changed = true
Whether query vars have changed since the initial parse_query() call.
$query_vars_hash = false
$stopwords
Detailed Description
The WordPress Query class.
Codex page. 1.5.0 4.5.0 Removed the $comments_popup property.
Definition at line 847 of file query.php.
Constructor & Destructor Documentation
__construct ($query = '')
Constructor.
Sets up the WordPress query, if parameter is not empty.
Since
1.5.0 public
Parameters
string | array $query URL query string or array of vars.
Definition at line 4094 of file query.php.
References $query, and query().
Member Function Documentation
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
Since
4.0.0 public
Parameters
callable $name Method to call.
array $arguments Arguments to pass when calling.
Returns
mixed|false Return value of the callback, false otherwise.
Definition at line 4140 of file query.php.
References $name.
__get ($name)
Make private properties readable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to get.
Returns
mixed Property.
Definition at line 4109 of file query.php.
References $name.
__isset ($name)
Make private properties checkable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to check if set.
Returns
bool Whether the property is set.
Definition at line 4124 of file query.php.
References $name.
fill_query_vars ($array)
Fills in the query variables, which do not exist within the parameter.
Since
2.1.0
4.4.0 Removed the comments_popup public query variable. public
Parameters
array $array Defined query variables.
Returns
array Complete query variables with undefined ones filled in empty.
Definition at line 1421 of file query.php.
References $keys.
Referenced by get_posts(), and parse_query().
get ($query_var, $default = '')
Retrieve query variable.
Since
1.5.0
3.9.0 The $default argument was introduced.
public
Parameters
string $query_var Query variable key.
mixed $default Optional. Value to return if the query variable is not set. Default empty.
Returns
mixed Contents of the query variable.
Definition at line 2437 of file query.php.
References $default.
get_posts ()
Retrieve the posts based on query variables.
There are a few filters and actions that can be used to modify the post database query.
Since
1.5.0 public
wpdb $wpdb WordPress database abstraction object.
Returns
array List of posts.
Fires after the query variable object is created, but before the actual query is run.
Note: If using conditional tags, use the method versions within the passed instance (e.g. $this->is_main_query() instead of is_main_query()). This is because the functions like is_main_query() test against the global $wp_query instance, not the passed one.
Since
2.0.0
Parameters
WP_Query &$this The WP_Query instance (passed by reference).
Filter the search SQL that is used in the WHERE clause of WP_Query.
Since
3.0.0
Parameters
string $search Search SQL for WHERE clause.
WP_Query $this The current WP_Query object.
Filter the ORDER BY used when ordering search results.
Since
3.7.0
Parameters
string $search_orderby The ORDER BY clause.
WP_Query $this The current WP_Query instance.
Filter the WHERE clause of the query.
Since
1.5.0
Parameters
string $where The WHERE clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the JOIN clause of the query.
Since
1.5.0
Parameters
string $where The JOIN clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the JOIN clause of the comments feed query before sending.
Since
2.2.0
Parameters
string $cjoin The JOIN clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the WHERE clause of the comments feed query before sending.
Since
2.2.0
Parameters
string $cwhere The WHERE clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the GROUP BY clause of the comments feed query before sending.
Since
2.2.0
Parameters
string $cgroupby The GROUP BY clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the ORDER BY clause of the comments feed query before sending.
Since
2.8.0
Parameters
string $corderby The ORDER BY clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the LIMIT clause of the comments feed query before sending.
Since
2.8.0
Parameters
string $climits The JOIN clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the WHERE clause of the query.
Specifically for manipulating paging queries.
Since
1.5.0
Parameters
string $where The WHERE clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the GROUP BY clause of the query.
Since
2.0.0
Parameters
string $groupby The GROUP BY clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the JOIN clause of the query.
Specifically for manipulating paging queries.
Since
1.5.0
Parameters
string $join The JOIN clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the ORDER BY clause of the query.
Since
1.5.1
Parameters
string $orderby The ORDER BY clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the DISTINCT clause of the query.
Since
2.1.0
Parameters
string $distinct The DISTINCT clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the LIMIT clause of the query.
Since
2.1.0
Parameters
string $limits The LIMIT clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the SELECT clause of the query.
Since
2.1.0
Parameters
string $fields The SELECT clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter all query clauses at once, for convenience.
Covers the WHERE, GROUP BY, JOIN, ORDER BY, DISTINCT, fields (SELECT), and LIMITS clauses.
Since
3.1.0
Parameters
array $clauses The list of clauses for the query.
WP_Query &$this The WP_Query instance (passed by reference).
Fires to announce the query's current selection parameters.
For use by caching plugins.
Since
2.3.0
Parameters
string $selection The assembled selection query.
Filter the WHERE clause of the query.
For use by caching plugins.
Since
2.5.0
Parameters
string $where The WHERE clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the GROUP BY clause of the query.
For use by caching plugins.
Since
2.5.0
Parameters
string $groupby The GROUP BY clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the JOIN clause of the query.
For use by caching plugins.
Since
2.5.0
Parameters
string $join The JOIN clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the ORDER BY clause of the query.
For use by caching plugins.
Since
2.5.0
Parameters
string $orderby The ORDER BY clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the DISTINCT clause of the query.
For use by caching plugins.
Since
2.5.0
Parameters
string $distinct The DISTINCT clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the SELECT clause of the query.
For use by caching plugins.
Since
2.5.0
Parameters
string $fields The SELECT clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the LIMIT clause of the query.
For use by caching plugins.
Since
2.5.0
Parameters
string $limits The LIMIT clause of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter all query clauses at once, for convenience.
For use by caching plugins.
Covers the WHERE, GROUP BY, JOIN, ORDER BY, DISTINCT, fields (SELECT), and LIMITS clauses.
Since
3.1.0
Parameters
array $pieces The pieces of the query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the completed SQL query before sending.
Since
2.0.0
Parameters
array $request The complete SQL query.
WP_Query &$this The WP_Query instance (passed by reference).
Filter whether to split the query.
Splitting the query will cause it to fetch just the IDs of the found posts (and then individually fetch each post by ID), rather than fetching every complete row at once. One massive result vs. many small results.
Since
3.4.0
Parameters
bool $split_the_query Whether or not to split the query.
WP_Query $this The WP_Query instance.
Filter the Post IDs SQL request before sending.
Since
3.4.0
Parameters
string $request The post ID request.
WP_Query $this The WP_Query instance.
Filter the raw post results array, prior to status checks.
Since
2.3.0
Parameters
array $posts The post results array.
WP_Query &$this The WP_Query instance (passed by reference).
This filter is documented in wp-includes/query.php
This filter is documented in wp-includes/query.php
This filter is documented in wp-includes/query.php
This filter is documented in wp-includes/query.php
This filter is documented in wp-includes/query.php
Filter the single post for preview mode.
Since
2.7.0
Parameters
WP_Post $post_preview The Post object.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the array of retrieved posts after they've been fetched and internally processed.
Since
1.5.0
Parameters
array $posts The array of retrieved posts.
WP_Query &$this The WP_Query instance (passed by reference).
Definition at line 2471 of file query.php.
References $authors, $comment, $comments, $date_query, $i, $is_search, $page, $post, $post_type, $post_type_object, $posts, $queried_object_id, $query_vars, $user_id, $wpdb, __, _deprecated_argument(), _prime_post_caches(), absint(), add_filter(), addslashes_gpc(), apply_filters(), apply_filters_ref_array(), comments, current_time(), current_user_can(), do_action(), do_action_ref_array(), elseif, fill_query_vars(), get_current_user_id(), get_object_taxonomies(), get_option(), get_page_by_path(), get_post(), get_post_stati(), get_post_status(), get_post_status_object(), get_post_type_object(), get_post_types(), get_taxonomies_for_attachments(), get_term_by(), is_admin(), is_archive(), is_attachment(), is_comment_feed(), is_feed(), is_home(), is_page(), is_preview(), is_search(), is_single(), is_singular(), is_tax(), OBJECT, parse_order(), parse_orderby(), parse_query(), parse_search(), parse_search_order(), parse_tax_query(), post_type, posts, query(), sanitize_title_for_query(), set(), set_found_posts(), str_replace, update_post_caches(), wp_basename(), wp_post_mime_type_where(), and wp_using_ext_object_cache().
Referenced by query().
get_queried_object ()
Retrieve queried object.
If queried object is not set, then the queried object will be set from the category, tag, taxonomy, posts page, single post, page, or author query variable. After it is set up, it will be returned.
Since
1.5.0 public
Returns
object
Definition at line 4000 of file query.php.
References $post, $post_type, $queried_object, $query, _make_cat_compat(), elseif, get_option(), get_post(), get_post_type_object(), get_term(), get_term_by(), if, is_author(), is_category(), is_post_type_archive(), is_singular(), is_tag(), is_tax(), is_wp_error(), null, and wp_list_filter().
Referenced by get_queried_object_id(), is_attachment(), is_author(), is_category(), is_page(), is_single(), is_singular(), is_tag(), and is_tax().
get_queried_object_id ()
Retrieve ID of the current queried object.
Since
1.5.0 public
Returns
int
Definition at line 4074 of file query.php.
References $queried_object_id, and get_queried_object().
Referenced by setup_postdata().
get_search_stopwords () protected
Retrieve stopwords used when parsing search terms.
Since
3.7.0
Returns
array Stopwords.
Filter stopwords used when parsing search terms.
Since
3.7.0
Parameters
array $stopwords Stopwords.
Definition at line 2222 of file query.php.
References $stopwords, _x, and apply_filters().
Referenced by parse_search_terms().
have_comments ()
Whether there are more comments available.
Automatically rewinds comments when finished.
Since
2.2.0 public
Returns
bool True, if more comments. False, if no more posts.
Definition at line 3950 of file query.php.
References elseif, and rewind_comments().
have_posts ()
Whether there are more posts available in the loop.
Calls action 'loop_end', when the loop is complete.
Since
1.5.0 public
Returns
bool True if posts are available, false if end of loop.
Fires once the loop has ended.
Since
2.0.0
Parameters
WP_Query &$this The WP_Query instance (passed by reference).
Definition at line 3870 of file query.php.
References do_action_ref_array(), elseif, in_the_loop(), and rewind_posts().
init ()
Initiates object properties and sets default values.
Since
1.5.0 public
Definition at line 1379 of file query.php.
References comment, comments, in_the_loop(), init_query_flags(), posts, and query().
Referenced by parse_query(), and query().
init_query_flags () private
Resets query flags to false.
The query flags are what page info WordPress was able to figure out.
Since
2.0.0 private
Definition at line 1344 of file query.php.
References is_404(), is_admin(), is_archive(), is_attachment(), is_author(), is_category(), is_comment_feed(), is_date(), is_day(), is_feed(), is_home(), is_month(), is_page(), is_paged(), is_post_type_archive(), is_preview(), is_robots(), is_search(), is_single(), is_singular(), is_tag(), is_tax(), is_time(), is_trackback(), and is_year().
Referenced by init(), and set_404().
is_404 ()
Is the query a 404 (returns no results)?
Since
3.1.0
Returns
bool
Definition at line 4676 of file query.php.
References $is_404.
Referenced by init_query_flags(), parse_query(), and set_404().
is_archive ()
Is the query for an existing archive page?
Month, Year, Category, Author, Post Type archive...
Since
3.1.0
Returns
bool
Definition at line 4156 of file query.php.
References $is_archive.
Referenced by get_posts(), init_query_flags(), and parse_query().
is_attachment ($attachment = '')
Is the query for an existing attachment page?
Since
3.1.0
Parameters
mixed $attachment Attachment ID, title, slug, or array of such.
Returns
bool
Definition at line 4188 of file query.php.
References elseif, and get_queried_object().
Referenced by get_posts(), init_query_flags(), and parse_query().
is_author ($author = '')
Is the query for an existing author archive page?
If the $author parameter is specified, this function will additionally check if the query is for one of the authors specified.
Since
3.1.0
Parameters
mixed $author Optional. User ID, nickname, nicename, or array of User IDs, nicknames, and nicenames
Returns
bool
Definition at line 4222 of file query.php.
References elseif, and get_queried_object().
Referenced by get_queried_object(), init_query_flags(), and parse_query().
is_category ($category = '')
Is the query for an existing category archive page?
If the $category parameter is specified, this function will additionally check if the query is for one of the categories specified.
Since
3.1.0
Parameters
mixed $category Optional. Category ID, name, slug, or array of Category IDs, names, and slugs.
Returns
bool
Definition at line 4254 of file query.php.
References elseif, and get_queried_object().
Referenced by get_queried_object(), init_query_flags(), and parse_query().
is_comment_feed ()
Is the query for a comments feed?
Since
3.1.0
Returns
bool
Definition at line 4413 of file query.php.
References $is_comment_feed.
Referenced by get_posts(), init_query_flags(), and parse_query().
is_comments_popup ()
Whether the current URL is within the comments popup window.
Since
3.1.0
Returns
bool
Definition at line 4361 of file query.php.
References _deprecated_function().
is_date ()
Is the query for an existing date archive?
Since
3.1.0
Returns
bool
Definition at line 4374 of file query.php.
References $is_date.
Referenced by init_query_flags(), and parse_query().
is_day ()
Is the query for an existing day archive?
Since
3.1.0
Returns
bool
Definition at line 4385 of file query.php.
References $is_day.
Referenced by init_query_flags(), and parse_query().
is_embed ()
Is the query for an embedded post?
Since
4.4.0
Returns
bool
Definition at line 4687 of file query.php.
References $is_embed.
Referenced by parse_query().
is_feed ($feeds = '')
Is the query for a feed?
Since
3.1.0
Parameters
string | array $feeds Optional feed types to check.
Returns
bool
Definition at line 4397 of file query.php.
References $is_feed, and get_default_feed().
Referenced by get_posts(), init_query_flags(), parse_query(), set_404(), and setup_postdata().
is_front_page ()
Is the query for the front page of the site?
This is for what is displayed at your site's main URL.
Depends on the site's "Front page displays" Reading Settings 'show_on_front' and 'page_on_front'.
If you set a static page for the front page of your site, this function will return true when viewing that page.
Otherwise the same as
See also
WP_Query::is_home()
Since
3.1.0
Returns
bool True, if front of site.
Definition at line 4433 of file query.php.
References elseif, get_option(), is_home(), and is_page().
is_home ()
Is the query for the blog homepage?
This is the page which shows the time based blog content of your site.
Depends on the site's "Front page displays" Reading Settings 'show_on_front' and 'page_for_posts'.
If you set a static page for the front page of your site, this function will return true only on the page you set as the "Posts page".
See also
WP_Query::is_front_page()
Since
3.1.0
Returns
bool True if blog view homepage.
Definition at line 4459 of file query.php.
References $is_home.
Referenced by get_posts(), init_query_flags(), is_front_page(), and parse_query().
is_main_query ()
Is the query the main query?
Since
3.3.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 4700 of file query.php.
Referenced by parse_search().
is_month ()
Is the query for an existing month archive?
Since
3.1.0
Returns
bool
Definition at line 4470 of file query.php.
References $is_month.
Referenced by init_query_flags(), and parse_query().
is_page ($page = '')
Is the query for an existing single page?
If the $page parameter is specified, this function will additionally check if the query is for one of the pages specified.
See also
WP_Query::is_single()
WP_Query::is_singular()
Since
3.1.0
Parameters
int | string | array $page Optional. Page ID, title, slug, path, or array of such. Default empty.
Returns
bool Whether the query is for an existing single page.
Definition at line 4488 of file query.php.
References $page, elseif, get_page_by_path(), and get_queried_object().
Referenced by get_posts(), init_query_flags(), is_front_page(), parse_query(), and setup_postdata().
is_paged ()
Is the query for paged result and not for the first page?
Since
3.1.0
Returns
bool
Definition at line 4528 of file query.php.
References $is_paged.
Referenced by init_query_flags(), and parse_query().
is_post_type_archive ($post_types = '')
Is the query for an existing post type archive page?
Since
3.1.0
Parameters
mixed $post_types Optional. Post type or array of posts types to check against.
Returns
bool
Definition at line 4168 of file query.php.
References $is_post_type_archive, $post_type, $post_type_object, and get_post_type_object().
Referenced by get_queried_object(), init_query_flags(), and parse_query().
is_preview ()
Is the query for a post or page preview?
Since
3.1.0
Returns
bool
Definition at line 4539 of file query.php.
References $is_preview.
Referenced by get_posts(), init_query_flags(), and parse_query().
is_robots ()
Is the query for the robots file?
Since
3.1.0
Returns
bool
Definition at line 4550 of file query.php.
References $is_robots.
Referenced by init_query_flags(), and parse_query().
is_search ()
Is the query for a search?
Since
3.1.0
Returns
bool
Definition at line 4561 of file query.php.
References $is_search.
Referenced by get_posts(), init_query_flags(), and parse_query().
is_single ($post = '')
Is the query for an existing single post?
Works for any post type, except attachments and pages
If the $post parameter is specified, this function will additionally check if the query is for one of the Posts specified.
See also
WP_Query::is_page()
WP_Query::is_singular()
Since
3.1.0
Parameters
int | string | array $post Optional. Post ID, title, slug, path, or array of such. Default empty.
Returns
bool Whether the query is for an existing single post.
Definition at line 4581 of file query.php.
References $post, elseif, get_page_by_path(), get_queried_object(), and OBJECT.
Referenced by get_posts(), init_query_flags(), parse_query(), and setup_postdata().
is_singular ($post_types = '')
Is the query for an existing single post of any post type (post, attachment, page, ...
)?
If the $post_types parameter is specified, this function will additionally check if the query is for one of the Posts Types specified.
See also
WP_Query::is_page()
WP_Query::is_single()
Since
3.1.0
Parameters
string | array $post_types Optional. Post type or array of post types. Default empty.
Returns
bool Whether the query is for an existing single post of any of the given post types.
Definition at line 4627 of file query.php.
References $is_singular, and get_queried_object().
Referenced by get_posts(), get_queried_object(), init_query_flags(), parse_query(), and parse_tax_query().
is_tag ($tag = '')
Is the query for an existing tag archive page?
If the $tag parameter is specified, this function will additionally check if the query is for one of the tags specified.
Since
3.1.0
Parameters
mixed $tag Optional. Tag ID, name, slug, or array of Tag IDs, names, and slugs.
Returns
bool
Definition at line 4286 of file query.php.
References elseif, and get_queried_object().
Referenced by get_queried_object(), init_query_flags(), and parse_query().
is_tax ($taxonomy = '', $term = '')
Is the query for an existing taxonomy archive page?
If the $taxonomy parameter is specified, this function will additionally check if the query is for that specific $taxonomy.
If the $term parameter is specified in addition to the $taxonomy parameter, this function will additionally check if the query is for one of the terms specified.
Since
3.1.0
array $wp_taxonomies
Parameters
mixed $taxonomy Optional. Taxonomy slug or slugs.
mixed $term Optional. Term ID, name, slug or array of Term IDs, names, and slugs.
Returns
bool
Definition at line 4325 of file query.php.
References $queried_object, and get_queried_object().
Referenced by get_posts(), get_queried_object(), init_query_flags(), and parse_query().
is_time ()
Is the query for a specific time?
Since
3.1.0
Returns
bool
Definition at line 4643 of file query.php.
References $is_time.
Referenced by init_query_flags(), and parse_query().
is_trackback ()
Is the query for a trackback endpoint call?
Since
3.1.0
Returns
bool
Definition at line 4654 of file query.php.
References $is_trackback.
Referenced by init_query_flags(), and parse_query().
is_year ()
Is the query for an existing year archive?
Since
3.1.0
Returns
bool
Definition at line 4665 of file query.php.
References $is_year.
Referenced by init_query_flags(), and parse_query().
lazyload_comment_meta ($check, $comment_id)
Lazy-load comment meta when inside of a WP_Query loop.
This method is public so that it can be used as a filter callback. As a rule, there is no need to invoke it directly, from either inside or outside the WP_Query object.
Since
4.4.0
Parameters
mixed $check The $check param passed from the 'get_comment_metadata' hook.
int $comment_id ID of the comment whose metadata is being cached.
Returns
mixed The original value of $check, to not affect 'get_comment_metadata'.
Definition at line 4915 of file query.php.
References $comment, comments, elseif, and update_meta_cache().
lazyload_term_meta ($check, $term_id)
Lazy-loads termmeta for located posts.
As a rule, term queries (get_terms() and wp_get_object_terms()) prime the metadata cache for matched terms by default. However, this can cause a slight performance penalty, especially when that metadata is not actually used. In the context of a WP_Query instance, we're able to avoid this potential penalty. update_object_term_cache(), called from update_post_caches(), does not 'update_term_meta_cache'. Instead, the first time get_term_meta() is called from within a WP_Query loop, the current method detects the fact, and then primes the metadata cache for all terms attached to all posts in the loop, with a single database query.
This method is public so that it can be used as a filter callback. As a rule, there is no need to invoke it directly, from either inside or outside the WP_Query object.
Since
4.4.0 public
Parameters
mixed $check The $check param passed from the 'get_term_metadata' hook.
int $term_id ID of the term whose metadata is being cached.
Returns
mixed In order not to short-circuit get_metadata(). Generally, this is null, but it could be another value if filtered by a plugin.
Definition at line 4849 of file query.php.
References $post, $posts, get_object_taxonomies(), get_object_term_cache(), posts, and update_termmeta_cache().
next_comment ()
Iterate current comment index and return WP_Comment object.
Since
2.2.0 public
Returns
WP_Comment Comment object.
Definition at line 3911 of file query.php.
References $comment, $current_comment, comment, and comments.
Referenced by the_comment().
next_post ()
Set up the next post and iterate current post index.
Since
1.5.0 public
Returns
WP_Post Next post.
Definition at line 3823 of file query.php.
References $current_post, $post, and posts.
Referenced by the_post().
parse_order ($order) protected
Parse an 'order' query variable and cast it to ASC or DESC as necessary.
Since
4.0.0 protected
Parameters
string $order The 'order' query variable.
Returns
string The sanitized 'order' query variable.
Definition at line 2398 of file query.php.
Referenced by get_posts().
parse_orderby ($orderby) protected
If the passed orderby value is allowed, convert the alias to a properly-prefixed orderby value.
Since
4.0.0 protected
wpdb $wpdb WordPress database abstraction object.
Parameters
string $orderby Alias for the field to order by.
Returns
string|false Table-prefixed value to used in the ORDER clause. False otherwise.
Definition at line 2316 of file query.php.
References $wpdb, and sanitize_key().
Referenced by get_posts().
parse_query ($query = '')
Parse a query string and set query type booleans.
Since
1.5.0
4.2.0 Introduced the ability to order by specific clauses of a $meta_query, by passing the clause's array key to $orderby.
4.4.0 Introduced $post_name__in and $title parameters. $s was updated to support excluded search terms, by prepending a hyphen.
4.5.0 Removed the $comments_popup parameter. public
Parameters
string | array $query { Optional. Array or string of Query parameters.
int $attachment_id Attachment post ID. Used for 'attachment' post_type. int|string $author Author ID, or comma-separated list of IDs. string $author_name User 'user_nicename'. array $author__in An array of author IDs to query from. array $author__not_in An array of author IDs not to query from. bool $cache_results Whether to cache post information. Default true. int|string $cat Category ID or comma-separated list of IDs (this or any children). array $category__and An array of category IDs (AND in). array $category__in An array of category IDs (OR in, no children). array $category__not_in An array of category IDs (NOT in). string $category_name Use category slug (not name, this or any children). int $comments_per_page The number of comments to return per page. Default 'comments_per_page' option. array $date_query An associative array of WP_Date_Query arguments. {
See also
WP_Date_Query::__construct()} int $day Day of the month. Default empty. Accepts numbers 1-31. bool $exact Whether to search by exact keyword. Default false. string|array $fields Which fields to return. Single field or all fields (string), or array of fields. 'id=>parent' uses 'id' and 'post_parent'. Default all fields. Accepts 'ids', 'id=>parent'. int $hour Hour of the day. Default empty. Accepts numbers 0-23. int|bool $ignore_sticky_posts Whether to ignore sticky posts or not. Setting this to false excludes stickies from 'post__in'. Accepts 1|true, 0|false. Default 0|false. int $m Combination YearMonth. Accepts any four-digit year and month numbers 1-12. Default empty. string $meta_compare Comparison operator to test the 'meta_value'. string $meta_key Custom field key. array $meta_query An associative array of WP_Meta_Query arguments. {
WP_Meta_Query} string $meta_value Custom field value. int $meta_value_num Custom field value number. int $menu_order The menu order of the posts. int $monthnum The two-digit month. Default empty. Accepts numbers 1-12. string $name Post slug. bool $nopaging Show all posts (true) or paginate (false). Default false. bool $no_found_rows Whether to skip counting the total rows found. Enabling can improve performance. Default false. int $offset The number of posts to offset before retrieval. string $order Designates ascending or descending order of posts. Default 'DESC'. Accepts 'ASC', 'DESC'. string|array $orderby Sort retrieved posts by parameter. One or more options may be passed. To use 'meta_value', or 'meta_value_num', 'meta_key=keyname' must be also be defined. To sort by a specific $meta_query clause, use that clause's array key. Default 'date'. Accepts 'none', 'name', 'author', 'date', 'title', 'modified', 'menu_order', 'parent', 'ID', 'rand', 'comment_count', 'meta_value', 'meta_value_num', 'post__in', and the array keys of $meta_query. int $p Post ID. int $page Show the number of posts that would show up on page X of a static front page. int $paged The number of the current page. int $page_id Page ID. string $pagename Page slug. string $perm Show posts if user has the appropriate capability. array $post__in An array of post IDs to retrieve, sticky posts will be included string $post_mime_type The mime type of the post. Used for 'attachment' post_type. array $post__not_in An array of post IDs not to retrieve. Note: a string of comma- separated IDs will NOT work. int $post_parent Page ID to retrieve child pages for. Use 0 to only retrieve top-level pages. array $post_parent__in An array containing parent page IDs to query child pages from. array $post_parent__not_in An array containing parent page IDs not to query child pages from. string|array $post_type A post type slug (string) or array of post type slugs. Default 'any' if using 'tax_query'. string|array $post_status A post status (string) or array of post statuses. int $posts_per_page The number of posts to query for. Use -1 to request all posts. int $posts_per_archive_page The number of posts to query for by archive page. Overrides 'posts_per_page' when is_archive(), or is_search() are true. array $post_name__in An array of post slugs that results must match. string $s Search keyword(s). Prepending a term with a hyphen will exclude posts matching that term. Eg, 'pillow -sofa' will return posts containing 'pillow' but not 'sofa'. int $second Second of the minute. Default empty. Accepts numbers 0-60. bool $sentence Whether to search by phrase. Default false. bool $suppress_filters Whether to suppress filters. Default false. string $tag Tag slug. Comma-separated (either), Plus-separated (all). array $tag__and An array of tag ids (AND in). array $tag__in An array of tag ids (OR in). array $tag__not_in An array of tag ids (NOT in). int $tag_id Tag id or comma-separated list of IDs. array $tag_slug__and An array of tag slugs (AND in). array $tag_slug__in An array of tag slugs (OR in). unless 'ignore_sticky_posts' is true. Note: a string of comma-separated IDs will NOT work. array $tax_query An associative array of WP_Tax_Query arguments. {
WP_Tax_Query->queries} string $title Post title. bool $update_post_meta_cache Whether to update the post meta cache. Default true. bool $update_post_term_cache Whether to update the post term cache. Default true. int $w The week number of the year. Default empty. Accepts numbers 0-53. int $year The four-digit year. Default empty. Accepts any four-digit year. }
Fires after the main query vars have been parsed.
Since
1.5.0
Parameters
WP_Query &$this The WP_Query instance (passed by reference).
Definition at line 1585 of file query.php.
References $is_404, $is_attachment, $post, $query, $query_vars, $tax_query, absint(), do_action_ref_array(), elseif, fill_query_vars(), get_option(), get_page_by_path(), get_post_type_object(), init(), is_404(), is_admin(), is_archive(), is_attachment(), is_author(), is_category(), is_comment_feed(), is_date(), is_day(), is_embed(), is_feed(), is_home(), is_month(), is_page(), is_paged(), is_post_type_archive(), is_preview(), is_robots(), is_search(), is_single(), is_singular(), is_tag(), is_tax(), is_time(), is_trackback(), is_year(), OBJECT, parse_tax_query(), query(), sanitize_key(), set_404(), str_replace, wp_checkdate(), and wp_parse_args().
Referenced by get_posts(), and parse_query_vars().
parse_query_vars ()
Reparse the query vars.
Since
1.5.0 public
Definition at line 1407 of file query.php.
References parse_query().
parse_search (& $q) protected
Generate SQL for the WHERE clause based on passed search terms.
Since
3.7.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $q Query variables.
Returns
string WHERE clause.
Definition at line 2117 of file query.php.
References $wpdb, is_main_query(), parse_search_terms(), and str_replace.
Referenced by get_posts().
parse_search_order (& $q) protected
Generate SQL for the ORDER BY condition based on passed search terms.
wpdb $wpdb WordPress database abstraction object.
Parameters
array $q Query variables.
Returns
string ORDER BY clause.
Definition at line 2259 of file query.php.
References $wpdb.
Referenced by get_posts().
parse_search_terms ($terms) protected
Check if the terms are suitable for searching.
Uses an array of stopwords (terms) that are excluded from the separate term matching when searching for posts. The list of English stopwords is the approximate search engines list, and is translatable.
Since
3.7.0
Parameters
array $terms Terms to check.
Returns
array Terms that are not stopwords.
Definition at line 2189 of file query.php.
References $stopwords, and get_search_stopwords().
Referenced by parse_search().
parse_tax_query (& $q)
Parses various taxonomy related query vars.
For BC, this method is not marked as protected. See [28987].
protected
Since
3.1.0
Parameters
array $q The query variables. Passed by reference.
Fires after taxonomy-related query vars have been parsed.
Since
3.7.0
Parameters
WP_Query $this The WP_Query instance.
Definition at line 1887 of file query.php.
References $tags, $tax_query, absint(), do_action(), elseif, get_taxonomies(), is_singular(), sanitize_term_field(), and wp_basename().
Referenced by get_posts(), and parse_query().
query ($query)
Sets up the WordPress query by parsing query string.
Since
1.5.0 public
Parameters
string $query URL query string.
Returns
array List of posts.
Definition at line 3982 of file query.php.
References $query, get_posts(), init(), and wp_parse_args().
Referenced by __construct(), get_posts(), get_posts(), init(), parse_query(), _WP_Editors\wp_link_query(), and wp_nav_menu_item_post_type_meta_box().
reset_postdata ()
After looping through a nested query, this function restores the $post global to the current post in this query.
Since
3.7.0
WP_Post $post
Definition at line 4820 of file query.php.
References $GLOBALS, $post, and setup_postdata().
rewind_comments ()
Rewind the comments, resets the comment index and comment to first.
Since
2.2.0 public
Definition at line 3966 of file query.php.
References comment, and comments.
Referenced by have_comments().
rewind_posts ()
Rewind the posts and reset post index.
Since
1.5.0 public
Definition at line 3896 of file query.php.
References posts.
Referenced by have_posts().
set ($query_var, $value)
Set query variable.
Since
1.5.0 public
Parameters
string $query_var Query variable key.
mixed $value Query variable value.
Definition at line 2454 of file query.php.
References $value.
Referenced by get_posts().
set_404 ()
Sets the 404 property and saves whether query is feed.
Since
2.0.0 public
Definition at line 2416 of file query.php.
References $is_feed, init_query_flags(), is_404(), and is_feed().
Referenced by parse_query().
set_found_posts ($q, $limits) private
Set up the amount of found posts and the number of pages (if limit clause was used) for the current query.
Since
3.5.0 private
wpdb $wpdb WordPress database abstraction object.
Parameters
array $q Query variables.
string $limits LIMIT clauses of the query.
Filter the query to run for retrieving the found posts.
Since
2.1.0
Parameters
string $found_posts The query to run to find the found posts.
WP_Query &$this The WP_Query instance (passed by reference).
Filter the number of found posts for the query.
Since
2.1.0
Parameters
int $found_posts The number of posts found.
WP_Query &$this The WP_Query instance (passed by reference).
Definition at line 3779 of file query.php.
References $wpdb, apply_filters_ref_array(), and posts.
Referenced by get_posts().
setup_postdata ($post)
Set up global post data.
Since
4.1.0
4.4.0 Added the ability to pass a post ID to $post.
int $id WP_User $authordata string|int|bool $currentday string|int|bool $currentmonth int $page array $pages int $multipage int $more int $numpages
Parameters
WP_Post | object | int $post WP_Post instance or Post ID/object.
Returns
true True when finished.
Filter the "pages" derived from splitting the post content.
"Pages" are determined by splitting the post content based on the presence of `` tags.
Since
4.4.0
Parameters
array $pages Array of "pages" derived from the post content. of `` tags..
WP_Post $post Current post object.
Fires once the post data has been setup.
Since
2.8.0
4.1.0 Introduced $this parameter.
Parameters
WP_Post &$post The Post object (passed by reference).
WP_Query &$this The current Query object (passed by reference).
Definition at line 4724 of file query.php.
References $content, $id, $more, $page, $post, apply_filters(), do_action_ref_array(), elseif, get_post(), get_queried_object_id(), is_feed(), is_page(), is_single(), mysql2date(), and str_replace.
Referenced by reset_postdata(), and the_post().
the_comment ()
Sets up the current comment.
Since
2.2.0 public WP_Comment $comment Current comment.
Fires once the comment loop is started.
Since
2.2.0
Definition at line 3925 of file query.php.
References $comment, do_action(), and next_comment().
the_post ()
Sets up the current post.
Retrieves the next post, sets up the post, sets the 'in the loop' property to true.
Since
1.5.0 public
WP_Post $post
Fires once the loop is started.
Since
2.0.0
Parameters
WP_Query &$this The WP_Query instance (passed by reference).
Definition at line 3842 of file query.php.
References $post, do_action_ref_array(), in_the_loop(), next_post(), and setup_postdata().
Field Documentation
$comment
Definition at line 1002 of file query.php.
Referenced by get_posts(), lazyload_comment_meta(), next_comment(), and the_comment().
$comment_count = 0
Definition at line 984 of file query.php.
$comments
Definition at line 975 of file query.php.
Referenced by get_posts().
$compat_fields = array('query_vars_hash', 'query_vars_changed') private
Definition at line 1332 of file query.php.
$compat_methods = array('init_query_flags', 'parse_tax_query') private
Definition at line 1334 of file query.php.
$current_comment = -1
Definition at line 993 of file query.php.
Referenced by next_comment().
$current_post = -1
Definition at line 948 of file query.php.
Referenced by next_post().
$date_query = false
Definition at line 892 of file query.php.
Referenced by get_posts().
$found_posts = 0
Definition at line 1013 of file query.php.
$in_the_loop = false
Definition at line 957 of file query.php.
$is_404 = false
Definition at line 1202 of file query.php.
Referenced by is_404(), and parse_query().
$is_admin = false
Definition at line 1229 of file query.php.
$is_archive = false
Definition at line 1067 of file query.php.
Referenced by is_archive().
$is_attachment = false
Definition at line 1238 of file query.php.
Referenced by parse_query().
$is_author = false
Definition at line 1121 of file query.php.
$is_category = false
Definition at line 1130 of file query.php.
$is_comment_feed = false
Definition at line 1175 of file query.php.
Referenced by is_comment_feed().
$is_date = false
Definition at line 1076 of file query.php.
Referenced by is_date().
$is_day = false
Definition at line 1103 of file query.php.
Referenced by is_day().
$is_embed = false
Definition at line 1211 of file query.php.
Referenced by is_embed().
$is_feed = false
Definition at line 1166 of file query.php.
Referenced by is_feed(), and set_404().
$is_home = false
Definition at line 1193 of file query.php.
Referenced by is_home().
$is_month = false
Definition at line 1094 of file query.php.
Referenced by is_month().
$is_page = false
Definition at line 1058 of file query.php.
$is_paged = false
Definition at line 1220 of file query.php.
Referenced by is_paged().
$is_post_type_archive = false
Definition at line 1276 of file query.php.
Referenced by is_post_type_archive().
$is_posts_page = false
Definition at line 1267 of file query.php.
$is_preview = false
Definition at line 1049 of file query.php.
Referenced by is_preview().
$is_robots = false
Definition at line 1256 of file query.php.
Referenced by is_robots().
$is_search = false
Definition at line 1157 of file query.php.
Referenced by get_posts(), and is_search().
$is_single = false
Definition at line 1040 of file query.php.
$is_singular = false
Definition at line 1247 of file query.php.
Referenced by is_singular().
$is_tag = false
Definition at line 1139 of file query.php.
$is_tax = false
Definition at line 1148 of file query.php.
$is_time = false
Definition at line 1112 of file query.php.
Referenced by is_time().
$is_trackback = false
Definition at line 1184 of file query.php.
Referenced by is_trackback().
$is_year = false
Definition at line 1085 of file query.php.
Referenced by is_year().
$max_num_comment_pages = 0
Definition at line 1031 of file query.php.
$max_num_pages = 0
Definition at line 1022 of file query.php.
$meta_query = false
Definition at line 883 of file query.php.
$post
Definition at line 966 of file query.php.
Referenced by get_posts(), get_queried_object(), is_single(), lazyload_term_meta(), next_post(), parse_query(), reset_postdata(), setup_postdata(), and the_post().
$post_count = 0
Definition at line 939 of file query.php.
$posts
Definition at line 930 of file query.php.
Referenced by get_posts(), and lazyload_term_meta().
$queried_object
Definition at line 903 of file query.php.
Referenced by get_queried_object(), and is_tax().
$queried_object_id
Definition at line 912 of file query.php.
Referenced by get_posts(), and get_queried_object_id().
$query
Definition at line 856 of file query.php.
Referenced by __construct(), get_queried_object(), parse_query(), and query().
$query_vars = array()
Definition at line 865 of file query.php.
Referenced by get_posts(), and parse_query().
$query_vars_changed = true private
Whether query vars have changed since the initial parse_query() call.
Used to catch modifications to query vars made via pre_get_posts hooks.
Since
3.1.1 private
Definition at line 1295 of file query.php.
$query_vars_hash = false private
Definition at line 1286 of file query.php.
$request
Definition at line 921 of file query.php.
$stopwords private
Definition at line 1330 of file query.php.
Referenced by get_search_stopwords(), and parse_search_terms().
$tax_query
Definition at line 874 of file query.php.
Referenced by parse_query(), and parse_tax_query().
$thumbnails_cached = false
Definition at line 1304 of file query.php.
$updated_comment_meta_cache = false
Definition at line 1322 of file query.php.
$updated_term_meta_cache = false
Definition at line 1313 of file query.php.
The documentation for this class was generated from the following file:
query.php