GravityView: MockAction Class Reference
MockAction Class Reference
Public Member Functions
__construct ($debug=0)
PHP5 constructor.
action ($arg)
action2 ($arg)
current_filter ()
filter ($arg)
filter2 ($arg)
filter_append ($arg)
filterall ($tag, $arg=NULL)
get_args ()
get_call_count ($tag='')
get_events ()
get_tags ()
reset ()
Data Fields
$debug
$events
Detailed Description
Definition at line 36 of file utils.php.
Constructor & Destructor Documentation
__construct ($debug = 0)
PHP5 constructor.
Definition at line 43 of file utils.php.
References $debug, and reset().
Member Function Documentation
action ($arg)
Definition at line 59 of file utils.php.
References current_filter(), and dmp().
action2 ($arg)
Definition at line 66 of file utils.php.
References current_filter(), and dmp().
current_filter ()
Definition at line 52 of file utils.php.
References $wp_actions.
Referenced by action(), action2(), filter(), filter2(), filter_append(), and filterall().
filter ($arg)
Definition at line 74 of file utils.php.
References current_filter(), and dmp().
filter2 ($arg)
Definition at line 82 of file utils.php.
References current_filter(), and dmp().
filter_append ($arg)
Definition at line 90 of file utils.php.
References current_filter(), and dmp().
filterall ($tag, $arg = NULL)
Definition at line 98 of file utils.php.
References current_filter(), and dmp().
get_args ()
Definition at line 133 of file utils.php.
References $out.
get_call_count ($tag = '')
Definition at line 112 of file utils.php.
References $count.
get_events ()
Definition at line 107 of file utils.php.
References $events.
get_tags ()
Definition at line 124 of file utils.php.
References $out.
reset ()
Definition at line 48 of file utils.php.
Referenced by __construct().
Field Documentation
$debug
Definition at line 38 of file utils.php.
Referenced by __construct().
$events
Definition at line 37 of file utils.php.
Referenced by get_events().
The documentation for this class was generated from the following file:
utils.php