GravityView: GravityView_Admin_Bar Class Reference
GravityView_Admin_Bar Class Reference
Handle management of the Admin Bar links.
Public Member Functions
__construct ()
add_floaty_icon ()
Add the Floaty icon to the toolbar without loading the whole icon font.
Data Fields
$gravityview_view = null
Private Member Functions
add_hooks ()
Detailed Description
Handle management of the Admin Bar links.
Since
1.13
Definition at line 8 of file class-gravityview-admin-bar.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 15 of file class-gravityview-admin-bar.php.
References add_hooks(), and GravityView_frontend\getInstance().
Member Function Documentation
add_floaty_icon()
add_floaty_icon ()
Add the Floaty icon to the toolbar without loading the whole icon font.
Since
1.17
Returns
void
Definition at line 69 of file class-gravityview-admin-bar.php.
References $entry, $form_id, $view_id, View\by_id(), GravityView_API\get_entry_slug(), GravityView_View_Data\getInstance(), GVCommon\has_cap(), and GV\top.
add_hooks()
add_hooks () private
Since
1.13
Definition at line 25 of file class-gravityview-admin-bar.php.
References GravityView_View_Data\getInstance(), and GVCommon\has_cap().
Referenced by __construct().
Field Documentation
$gravityview_view
$gravityview_view = null
Definition at line 13 of file class-gravityview-admin-bar.php.
The documentation for this class was generated from the following file:
class-gravityview-admin-bar.php