GravityView: GravityView_Plugin Class Reference
GravityView_Plugin Class Reference
The future is here and now.
Public Member Functions
frontend_actions ($force=false)
Function to launch frontend objects.
include_files ()
Include global plugin files.
load_plugin_textdomain ()
Loads the plugin's translated strings.
Static Public Member Functions
static activate ()
Plugin activate function.
static deactivate ()
Plugin deactivate function.
static get_default_widget_areas ()
helper function to define the default widget areas
static getInstance ()
Singleton instance.
static include_extension_framework ()
Include the extension class.
static include_widget_class ()
Load GravityView_Widget class.
static is_admin ()
Check if is_admin(), and make sure not DOING_AJAX.
static is_network_activated ()
Check whether GravityView is network activated.
static log_debug ($message, $data=null)
DEBUG.
static log_error ($message, $data=null)
Logs messages using Gravity Forms logging add-on.
Data Fields
const version = '1.19.4'
Private Member Functions
__construct ()
add_hooks ()
Add hooks to set up the plugin.
Static Private Member Functions
static require_files ()
Include files that are required by the plugin.
Static Private Attributes
static $instance
Detailed Description
The future is here and now.
GravityView_Plugin main class.
Definition at line 80 of file gravityview.php.
Constructor & Destructor Documentation
__construct () private
Definition at line 100 of file gravityview.php.
References add_hooks(), include_files(), and GravityView_Compatibility\is_valid().
Member Function Documentation
static activate () static
Plugin activate function.
public
Returns
void
Deprecate in favor of ::register_post_type.
Deprecate in favor of ::add_rewrite_endpoint.
Deprecate. Handled in ::activate now.
Definition at line 213 of file gravityview.php.
References GravityView_Roles_Capabilities\get_instance(), GravityView_Post_Types\init_post_types(), and GravityView_Post_Types\init_rewrite().
add_hooks () private
Add hooks to set up the plugin.
Since
1.12
Definition at line 134 of file gravityview.php.
Referenced by __construct().
static deactivate () static
Plugin deactivate function.
public
Returns
void
Definition at line 254 of file gravityview.php.
frontend_actions ($force = false)
Function to launch frontend objects.
Since
1.17 Added $force param
public
Parameters
bool $force Whether to force loading, even if GravityView_Plugin::is_admin() returns true
Returns
void
When an entry is created, check if we need to update the custom slug meta todo: move this to its own class..
Runs Actions:
gravityview_include_frontend_actions Triggered after all GravityView frontend files are loaded
Nice place to insert extensions' frontend stuff
Definition at line 329 of file gravityview.php.
References GRAVITYVIEW_DIR.
static get_default_widget_areas () static
helper function to define the default widget areas
Returns
array definition for default widget areas
Runs Filter:
gravityview_widget_active_areas Array of zones available for widgets to be dropped into
Parameters
array $default_areas Definition for default widget areas
Definition at line 359 of file gravityview.php.
Referenced by GravityView_Ajax\get_preset_fields_config(), GravityView_View\render_widget_hooks(), and GravityView_Admin_Views\render_widgets_active_areas().
static getInstance () static
Singleton instance.
Returns
GravityView_Plugin GravityView_Plugin object
Definition at line 91 of file gravityview.php.
static include_extension_framework () static
Include the extension class.
Since
1.5.1
Returns
void
Definition at line 266 of file gravityview.php.
References GRAVITYVIEW_DIR.
include_files ()
Include global plugin files.
Since
1.12
Since
1.8.4
Definition at line 147 of file gravityview.php.
References GRAVITYVIEW_DIR.
Referenced by __construct().
static include_widget_class () static
Load GravityView_Widget class.
Since
1.7.5.1
Definition at line 277 of file gravityview.php.
References GRAVITYVIEW_DIR.
static is_admin () static
Check if is_admin(), and make sure not DOING_AJAX.
Since
1.7.5
Returns
bool
Definition at line 311 of file gravityview.php.
Referenced by GravityView_Widget\add_shortcode(), GravityView_frontend\parse_content(), GravityView_Entry_Link_Shortcode\shortcode(), and GVLogic_Shortcode\shortcode().
static is_network_activated () static
Check whether GravityView is network activated.
Since
1.7.6
Returns
bool
Definition at line 201 of file gravityview.php.
Referenced by add_network_menu(), GravityView_Admin_Notices\check_show_multisite_notices(), and create_app_menu().
load_plugin_textdomain ()
Loads the plugin's translated strings.
public
Returns
void
Definition at line 288 of file gravityview.php.
static log_debug ($message, $data = null) static
DEBUG.
Logs messages using Gravity Forms logging add-on
Parameters
string $message log message
mixed $data Additional data to display
Returns
void
Runs Actions:
gravityview_log_debug Log a debug message that shows up in the Gravity Forms Logging Addon and also the Debug Bar plugin output
Parameters
string $message Message to display
mixed $data Supporting data to print alongside it
Definition at line 380 of file gravityview.php.
static log_error ($message, $data = null) static
Logs messages using Gravity Forms logging add-on.
Parameters
string $message log message
Returns
void
Runs Actions:
gravityview_log_error Log an error message that shows up in the Gravity Forms Logging Addon and also the Debug Bar plugin output
Parameters
string $message Error message to display
mixed $data Supporting data to print alongside it
Definition at line 394 of file gravityview.php.
static require_files () static private
Include files that are required by the plugin.
Since
1.18
Definition at line 117 of file gravityview.php.
References GRAVITYVIEW_DIR.
Field Documentation
$instance static private
Definition at line 84 of file gravityview.php.
const version = '1.19.4'
Definition at line 82 of file gravityview.php.
Referenced by GravityView_Support_Port\_localize_script(), Plugin\activate(), GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Widget_Search\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GravityView_Recent_Entries_Widget\admin_enqueue_scripts(), app_settings_fields(), GravityView_Compatibility\check_php(), GravityView_frontend\enqueue_default_style(), GV_License_Handler\get_site_data(), GravityView_Extension\is_extension_supported(), GravityView_Support_Port\maybe_enqueue_script(), GravityView_Field_Notes\register_scripts(), GravityView_Widget_Search\register_scripts(), GravityView_Field_Entry_Approval\register_scripts_and_styles(), GravityView_Template\register_styles(), styles(), and GravityView_Welcome\tabs().
The documentation for this class was generated from the following file:
gravityview.php