GravityView: WP_REST_Request Class Reference
WP_REST_Request Class Reference
Core class used to implement a REST request object.
Public Member Functions
__construct ($method= '', $route= '', $attributes=array())
Constructor.
__construct ($method= '', $route= '', $attributes=array())
Constructor.
add_header ($key, $value)
Appends a header value for the given header.
add_header ($key, $value)
Appends a header value for the given header.
get_attributes ()
Retrieves the attributes for the request.
get_attributes ()
Retrieves the attributes for the request.
get_body ()
Retrieves the request body content.
get_body ()
Retrieves the request body content.
get_body_params ()
Retrieves parameters from the body.
get_body_params ()
Retrieves parameters from the body.
get_content_type ()
Retrieves the content-type of the request.
get_content_type ()
Retrieves the content-type of the request.
get_default_params ()
Retrieves the default parameters.
get_default_params ()
Retrieves the default parameters.
get_file_params ()
Retrieves multipart file parameters from the body.
get_file_params ()
Retrieves multipart file parameters from the body.
get_header ($key)
Retrieves the given header from the request.
get_header ($key)
Retrieves the given header from the request.
get_header_as_array ($key)
Retrieves header values from the request.
get_header_as_array ($key)
Retrieves header values from the request.
get_headers ()
Retrieves all headers from the request.
get_headers ()
Retrieves all headers from the request.
get_json_params ()
Retrieves the parameters from a JSON-formatted body.
get_json_params ()
Retrieves the parameters from a JSON-formatted body.
get_method ()
Retrieves the HTTP method for the request.
get_method ()
Retrieves the HTTP method for the request.
get_param ($key)
Retrieves a parameter from the request.
get_param ($key)
Retrieves a parameter from the request.
get_params ()
Retrieves merged parameters from the request.
get_params ()
Retrieves merged parameters from the request.
get_query_params ()
Retrieves parameters from the query string.
get_query_params ()
Retrieves parameters from the query string.
get_route ()
Retrieves the route that matched the request.
get_route ()
Retrieves the route that matched the request.
get_url_params ()
Retrieves parameters from the route itself.
get_url_params ()
Retrieves parameters from the route itself.
has_valid_params ()
Checks whether this request is valid according to its attributes.
has_valid_params ()
Checks whether this request is valid according to its attributes.
offsetExists ($offset)
Checks if a parameter is set.
offsetExists ($offset)
Checks if a parameter is set.
offsetGet ($offset)
Retrieves a parameter from the request.
offsetGet ($offset)
Retrieves a parameter from the request.
offsetSet ($offset, $value)
Sets a parameter on the request.
offsetSet ($offset, $value)
Sets a parameter on the request.
offsetUnset ($offset)
Removes a parameter from the request.
offsetUnset ($offset)
Removes a parameter from the request.
remove_header ($key)
Removes all values for a header.
remove_header ($key)
Removes all values for a header.
sanitize_params ()
Sanitizes (where possible) the params on the request.
sanitize_params ()
Sanitizes (where possible) the params on the request.
set_attributes ($attributes)
Sets the attributes for the request.
set_attributes ($attributes)
Sets the attributes for the request.
set_body ($data)
Sets body content.
set_body ($data)
Sets body content.
set_body_params ($params)
Sets parameters from the body.
set_body_params ($params)
Sets parameters from the body.
set_default_params ($params)
Sets default parameters.
set_default_params ($params)
Sets default parameters.
set_file_params ($params)
Sets multipart file parameters from the body.
set_file_params ($params)
Sets multipart file parameters from the body.
set_header ($key, $value)
Sets the header on request.
set_header ($key, $value)
Sets the header on request.
set_headers ($headers, $override=true)
Sets headers on the request.
set_headers ($headers, $override=true)
Sets headers on the request.
set_method ($method)
Sets HTTP method for the request.
set_method ($method)
Sets HTTP method for the request.
set_param ($key, $value)
Sets a parameter on the request.
set_param ($key, $value)
Sets a parameter on the request.
set_query_params ($params)
Sets parameters from the query string.
set_query_params ($params)
Sets parameters from the query string.
set_route ($route)
Sets the route that matched the request.
set_route ($route)
Sets the route that matched the request.
set_url_params ($params)
Sets parameters from the route.
set_url_params ($params)
Sets parameters from the route.
Static Public Member Functions
static canonicalize_header_name ($key)
Canonicalizes the header name.
static canonicalize_header_name ($key)
Canonicalizes the header name.
Protected Member Functions
get_parameter_order ()
Retrieves the parameter priority order.
get_parameter_order ()
Retrieves the parameter priority order.
parse_body_params ()
Parses the request body parameters.
parse_body_params ()
Parses the request body parameters.
parse_json_params ()
Parses the JSON parameters.
parse_json_params ()
Parses the JSON parameters.
Protected Attributes
$attributes = array()
$body = null
$headers = array()
$method = ''
$params
$parsed_body = false
$parsed_json = false
$route
Detailed Description
Core class used to implement a REST request object.
Contains data from the request, to be passed to the callback.
Note: This implements ArrayAccess, and acts as an array of parameters when used in that manner. It does not use ArrayObject (as we cannot rely on SPL), so be aware it may have non-array behaviour in some cases.
Since
4.4.0
See also
ArrayAccess
Definition at line 23 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
Constructor & Destructor Documentation
__construct ($method = '', $route = '', $attributes = array())
Constructor.
Since
4.4.0 public
Parameters
string $method Optional. Request method. Default empty.
string $route Optional. Request route. Default empty.
array $attributes Optional. Request attributes. Default empty array.
Definition at line 115 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes, $method, $route, null, set_attributes(), set_method(), and set_route().
__construct ($method = '', $route = '', $attributes = array())
Constructor.
Since
4.4.0 public
Parameters
string $method Optional. Request method. Default empty.
string $route Optional. Request route. Default empty.
array $attributes Optional. Request attributes. Default empty array.
Definition at line 115 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes, $route, null, set_attributes(), set_method(), and set_route().
Member Function Documentation
add_header ($key, $value)
Appends a header value for the given header.
Since
4.4.0 public
Parameters
string $key Header name.
string $value Header value, or list of values.
Definition at line 263 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $value, and canonicalize_header_name().
add_header ($key, $value)
Appends a header value for the given header.
Since
4.4.0 public
Parameters
string $key Header name.
string $value Header value, or list of values.
Definition at line 263 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $value, and canonicalize_header_name().
static canonicalize_header_name ($key) static
Canonicalizes the header name.
Ensures that header names are always treated the same regardless of source. Header names are always case insensitive.
Note that we treat - (dashes) and _ (underscores) as the same character, as per header parsing rules in both Apache and nginx.
http://wiki.nginx.org/Pitfalls#Missing_.28disappearing.29_HTTP_headers http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers 4.4.0 public string $key Header name. string Canonicalized name.
Definition at line 189 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References str_replace.
Referenced by add_header(), get_header(), get_header_as_array(), and set_header().
static canonicalize_header_name ($key) static
Canonicalizes the header name.
Ensures that header names are always treated the same regardless of source. Header names are always case insensitive.
Note that we treat - (dashes) and _ (underscores) as the same character, as per header parsing rules in both Apache and nginx.
http://wiki.nginx.org/Pitfalls#Missing_.28disappearing.29_HTTP_headers http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers 4.4.0 public string $key Header name. string Canonicalized name.
Definition at line 189 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References str_replace.
get_attributes ()
Retrieves the attributes for the request.
These are the options for the route that was matched.
Since
4.4.0 public
Returns
array Attributes for the request.
Definition at line 752 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes.
Referenced by has_valid_params(), and sanitize_params().
get_attributes ()
Retrieves the attributes for the request.
These are the options for the route that was matched.
Since
4.4.0 public
Returns
array Attributes for the request.
Definition at line 752 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes.
get_body ()
Retrieves the request body content.
Since
4.4.0 public
Returns
string Binary data from the request body.
Definition at line 601 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $body.
get_body ()
Retrieves the request body content.
Since
4.4.0 public
Returns
string Binary data from the request body.
Definition at line 601 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $body.
Referenced by get_parameter_order(), parse_body_params(), and parse_json_params().
get_body_params ()
Retrieves parameters from the body.
These are the parameters you'd typically find in $_POST.
Since
4.4.0 public
Returns
array Parameter map of key to value.
Definition at line 519 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
get_body_params ()
Retrieves parameters from the body.
These are the parameters you'd typically find in $_POST.
Since
4.4.0 public
Returns
array Parameter map of key to value.
Definition at line 519 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
get_content_type ()
Retrieves the content-type of the request.
Since
4.4.0 public
Returns
array Map containing 'value' and 'parameters' keys.
Definition at line 313 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $value, get_header(), and null.
Referenced by parse_body_params(), and parse_json_params().
get_content_type ()
Retrieves the content-type of the request.
Since
4.4.0 public
Returns
array Map containing 'value' and 'parameters' keys.
Definition at line 313 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $value, get_header(), and null.
get_default_params ()
Retrieves the default parameters.
These are the parameters set in the route registration.
Since
4.4.0 public
Returns
array Parameter map of key to value
Definition at line 575 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
get_default_params ()
Retrieves the default parameters.
These are the parameters set in the route registration.
Since
4.4.0 public
Returns
array Parameter map of key to value
Definition at line 575 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
get_file_params ()
Retrieves multipart file parameters from the body.
These are the parameters you'd typically find in $_FILES.
Since
4.4.0 public
Returns
array Parameter map of key to value
Definition at line 547 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
get_file_params ()
Retrieves multipart file parameters from the body.
These are the parameters you'd typically find in $_FILES.
Since
4.4.0 public
Returns
array Parameter map of key to value
Definition at line 547 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
get_header ($key)
Retrieves the given header from the request.
If the header has multiple values, they will be concatenated with a comma as per the HTTP specification. Be aware that some non-compliant headers (notably cookie headers) cannot be joined this way.
Since
4.4.0 public
Parameters
string $key Header name, will be canonicalized to lowercase.
Returns
string|null String value if set, null otherwise.
Definition at line 209 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References canonicalize_header_name(), and null.
Referenced by get_content_type().
get_header ($key)
Retrieves the given header from the request.
If the header has multiple values, they will be concatenated with a comma as per the HTTP specification. Be aware that some non-compliant headers (notably cookie headers) cannot be joined this way.
Since
4.4.0 public
Parameters
string $key Header name, will be canonicalized to lowercase.
Returns
string|null String value if set, null otherwise.
Definition at line 209 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References canonicalize_header_name(), and null.
get_header_as_array ($key)
Retrieves header values from the request.
Since
4.4.0 public
Parameters
string $key Header name, will be canonicalized to lowercase.
Returns
array|null List of string values if set, null otherwise.
Definition at line 228 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References canonicalize_header_name(), and null.
get_header_as_array ($key)
Retrieves header values from the request.
Since
4.4.0 public
Parameters
string $key Header name, will be canonicalized to lowercase.
Returns
array|null List of string values if set, null otherwise.
Definition at line 228 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References canonicalize_header_name(), and null.
get_headers ()
Retrieves all headers from the request.
Since
4.4.0 public
Returns
array Map of key to value. Key is always lowercase, as per HTTP specification.
Definition at line 165 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $headers.
get_headers ()
Retrieves all headers from the request.
Since
4.4.0 public
Returns
array Map of key to value. Key is always lowercase, as per HTTP specification.
Definition at line 165 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $headers.
get_json_params ()
Retrieves the parameters from a JSON-formatted body.
Since
4.4.0 public
Returns
array Parameter map of key to value.
Definition at line 630 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References parse_json_params().
get_json_params ()
Retrieves the parameters from a JSON-formatted body.
Since
4.4.0 public
Returns
array Parameter map of key to value.
Definition at line 630 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References parse_json_params().
get_method ()
Retrieves the HTTP method for the request.
Since
4.4.0 public
Returns
string HTTP method.
Definition at line 141 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $method.
get_method ()
Retrieves the HTTP method for the request.
Since
4.4.0 public
Returns
string HTTP method.
Definition at line 141 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $method.
get_param ($key)
Retrieves a parameter from the request.
Since
4.4.0 public
Parameters
string $key Parameter name.
Returns
mixed|null Value if set, null otherwise.
Definition at line 396 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References get_parameter_order(), and null.
Referenced by has_valid_params(), and offsetGet().
get_param ($key)
Retrieves a parameter from the request.
Since
4.4.0 public
Parameters
string $key Parameter name.
Returns
mixed|null Value if set, null otherwise.
Definition at line 396 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References get_parameter_order(), and null.
get_parameter_order () protected
Retrieves the parameter priority order.
Used when checking parameters in get_param().
Since
4.4.0 protected
Returns
array List of types to check, in order of priority.
Filter the parameter order.
The order affects which parameters are checked when using get_param() and family. This acts similarly to PHP's request_order setting.
Since
4.4.0
Parameters
array $order { An array of types to check, in order of priority.
string $type The type to check. }
WP_REST_Request $this The request object.
Definition at line 348 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $body, apply_filters(), get_body(), parse_body_params(), and parse_json_params().
Referenced by get_param(), get_params(), offsetExists(), offsetUnset(), and sanitize_params().
get_parameter_order () protected
Retrieves the parameter priority order.
Used when checking parameters in get_param().
Since
4.4.0 protected
Returns
array List of types to check, in order of priority.
Filter the parameter order.
The order affects which parameters are checked when using get_param() and family. This acts similarly to PHP's request_order setting.
Since
4.4.0
Parameters
array $order { An array of types to check, in order of priority.
string $type The type to check. }
WP_REST_Request $this The request object.
Definition at line 348 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $body, apply_filters(), get_body(), parse_body_params(), and parse_json_params().
get_params ()
Retrieves merged parameters from the request.
The equivalent of get_param(), but returns all parameters for the request. Handles merging all the available values into a single array.
Since
4.4.0 public
Returns
array Map of key to value.
Definition at line 441 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $params, and get_parameter_order().
get_params ()
Retrieves merged parameters from the request.
The equivalent of get_param(), but returns all parameters for the request. Handles merging all the available values into a single array.
Since
4.4.0 public
Returns
array Map of key to value.
Definition at line 441 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $params, and get_parameter_order().
get_query_params ()
Retrieves parameters from the query string.
These are the parameters you'd typically find in $_GET.
Since
4.4.0 public
Returns
array Parameter map of key to value
Definition at line 491 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
get_query_params ()
Retrieves parameters from the query string.
These are the parameters you'd typically find in $_GET.
Since
4.4.0 public
Returns
array Parameter map of key to value
Definition at line 491 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
get_route ()
Retrieves the route that matched the request.
Since
4.4.0 public
Returns
string Route matching regex.
Definition at line 726 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $route.
get_route ()
Retrieves the route that matched the request.
Since
4.4.0 public
Returns
string Route matching regex.
Definition at line 726 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $route.
get_url_params ()
Retrieves parameters from the route itself.
These are parsed from the URL using the regex.
Since
4.4.0 public
Returns
array Parameter map of key to value.
Definition at line 463 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
get_url_params ()
Retrieves parameters from the route itself.
These are parsed from the URL using the regex.
Since
4.4.0 public
Returns
array Parameter map of key to value.
Definition at line 463 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
has_valid_params ()
Checks whether this request is valid according to its attributes.
Since
4.4.0 public
Returns
bool|WP_Error True if there are no parameters to validate or if all pass validation, WP_Error if required parameters are missing.
Definition at line 813 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes, __, get_attributes(), get_param(), is_wp_error(), and null.
has_valid_params ()
Checks whether this request is valid according to its attributes.
Since
4.4.0 public
Returns
bool|WP_Error True if there are no parameters to validate or if all pass validation, WP_Error if required parameters are missing.
Definition at line 813 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes, __, get_attributes(), get_param(), is_wp_error(), and null.
offsetExists ($offset)
Checks if a parameter is set.
Since
4.4.0 public
Parameters
string $offset Parameter name.
Returns
bool Whether the parameter is set.
Definition at line 876 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References get_parameter_order().
offsetExists ($offset)
Checks if a parameter is set.
Since
4.4.0 public
Parameters
string $offset Parameter name.
Returns
bool Whether the parameter is set.
Definition at line 876 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References get_parameter_order().
offsetGet ($offset)
Retrieves a parameter from the request.
Since
4.4.0 public
Parameters
string $offset Parameter name.
Returns
mixed|null Value if set, null otherwise.
Definition at line 897 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References get_param().
offsetGet ($offset)
Retrieves a parameter from the request.
Since
4.4.0 public
Parameters
string $offset Parameter name.
Returns
mixed|null Value if set, null otherwise.
Definition at line 897 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References get_param().
offsetSet ($offset, $value)
Sets a parameter on the request.
Since
4.4.0 public
Parameters
string $offset Parameter name.
mixed $value Parameter value.
Definition at line 910 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $value, and set_param().
offsetSet ($offset, $value)
Sets a parameter on the request.
Since
4.4.0 public
Parameters
string $offset Parameter name.
mixed $value Parameter value.
Definition at line 910 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $value, and set_param().
offsetUnset ($offset)
Removes a parameter from the request.
Since
4.4.0 public
Parameters
string $offset Parameter name.
Definition at line 922 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References get_parameter_order().
offsetUnset ($offset)
Removes a parameter from the request.
Since
4.4.0 public
Parameters
string $offset Parameter name.
Definition at line 922 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References get_parameter_order().
parse_body_params () protected
Parses the request body parameters.
Parses out URL-encoded bodies for request methods that aren't supported natively by PHP. In PHP 5.x, only POST has these parsed automatically.
Since
4.4.0 protected
Definition at line 683 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $params, get_body(), get_content_type(), and stripslashes_deep().
parse_body_params () protected
Parses the request body parameters.
Parses out URL-encoded bodies for request methods that aren't supported natively by PHP. In PHP 5.x, only POST has these parsed automatically.
Since
4.4.0 protected
Definition at line 683 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $params, get_body(), get_content_type(), and stripslashes_deep().
Referenced by get_parameter_order().
parse_json_params () protected
Parses the JSON parameters.
Avoids parsing the JSON data until we need to access it.
Since
4.4.0 protected
Definition at line 645 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $params, get_body(), get_content_type(), and null.
parse_json_params () protected
Parses the JSON parameters.
Avoids parsing the JSON data until we need to access it.
Since
4.4.0 protected
Definition at line 645 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $params, get_body(), get_content_type(), and null.
Referenced by get_json_params(), and get_parameter_order().
remove_header ($key)
Removes all values for a header.
Since
4.4.0 public
Parameters
string $key Header name.
Definition at line 282 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
remove_header ($key)
Removes all values for a header.
Since
4.4.0 public
Parameters
string $key Header name.
Definition at line 282 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
sanitize_params ()
Sanitizes (where possible) the params on the request.
This is primarily based off the sanitize_callback param on each registered argument.
Since
4.4.0 public
Returns
true|null True if there are no parameters to sanitize, null otherwise.
Definition at line 779 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes, $value, get_attributes(), get_parameter_order(), and null.
sanitize_params ()
Sanitizes (where possible) the params on the request.
This is primarily based off the sanitize_callback param on each registered argument.
Since
4.4.0 public
Returns
true|null True if there are no parameters to sanitize, null otherwise.
Definition at line 779 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes, $value, get_attributes(), get_parameter_order(), and null.
set_attributes ($attributes)
Sets the attributes for the request.
Since
4.4.0 public
Parameters
array $attributes Attributes for the request.
Definition at line 764 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes.
Referenced by __construct().
set_attributes ($attributes)
Sets the attributes for the request.
Since
4.4.0 public
Parameters
array $attributes Attributes for the request.
Definition at line 764 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $attributes.
set_body ($data)
Sets body content.
Since
4.4.0 public
Parameters
string $data Binary data from the request body.
Definition at line 613 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References null.
set_body ($data)
Sets body content.
Since
4.4.0 public
Parameters
string $data Binary data from the request body.
Definition at line 613 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References null.
set_body_params ($params)
Sets parameters from the body.
Typically, this is set from $_POST.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 533 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_body_params ($params)
Sets parameters from the body.
Typically, this is set from $_POST.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 533 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_default_params ($params)
Sets default parameters.
These are the parameters set in the route registration.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 589 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_default_params ($params)
Sets default parameters.
These are the parameters set in the route registration.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 589 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_file_params ($params)
Sets multipart file parameters from the body.
Typically, this is set from $_FILES.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 561 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_file_params ($params)
Sets multipart file parameters from the body.
Typically, this is set from $_FILES.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 561 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_header ($key, $value)
Sets the header on request.
Since
4.4.0 public
Parameters
string $key Header name.
string $value Header value, or list of values.
Definition at line 247 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $value, and canonicalize_header_name().
Referenced by set_headers().
set_header ($key, $value)
Sets the header on request.
Since
4.4.0 public
Parameters
string $key Header name.
string $value Header value, or list of values.
Definition at line 247 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $value, and canonicalize_header_name().
set_headers ($headers, $override = true)
Sets headers on the request.
Since
4.4.0 public
Parameters
array $headers Map of header name to value.
bool $override If true, replace the request's headers. Otherwise, merge with existing.
Definition at line 295 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $headers, $value, and set_header().
set_headers ($headers, $override = true)
Sets headers on the request.
Since
4.4.0 public
Parameters
array $headers Map of header name to value.
bool $override If true, replace the request's headers. Otherwise, merge with existing.
Definition at line 295 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $headers, $value, and set_header().
set_method ($method)
Sets HTTP method for the request.
Since
4.4.0 public
Parameters
string $method HTTP method.
Definition at line 153 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
set_method ($method)
Sets HTTP method for the request.
Since
4.4.0 public
Parameters
string $method HTTP method.
Definition at line 153 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $method.
Referenced by __construct().
set_param ($key, $value)
Sets a parameter on the request.
Since
4.4.0 public
Parameters
string $key Parameter name.
mixed $value Parameter value.
Definition at line 418 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $value.
Referenced by offsetSet().
set_param ($key, $value)
Sets a parameter on the request.
Since
4.4.0 public
Parameters
string $key Parameter name.
mixed $value Parameter value.
Definition at line 418 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $value.
set_query_params ($params)
Sets parameters from the query string.
Typically, this is set from $_GET.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 505 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_query_params ($params)
Sets parameters from the query string.
Typically, this is set from $_GET.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 505 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_route ($route)
Sets the route that matched the request.
Since
4.4.0 public
Parameters
string $route Route matching regex.
Definition at line 738 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $route.
set_route ($route)
Sets the route that matched the request.
Since
4.4.0 public
Parameters
string $route Route matching regex.
Definition at line 738 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $route.
Referenced by __construct().
set_url_params ($params)
Sets parameters from the route.
Typically, this is set after parsing the URL.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 477 of file wordpress/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
set_url_params ($params)
Sets parameters from the route.
Typically, this is set after parsing the URL.
Since
4.4.0 public
Parameters
array $params Parameter map of key to value.
Definition at line 477 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
References $params.
Field Documentation
$attributes = array() protected
Definition at line 83 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
Referenced by __construct(), get_attributes(), has_valid_params(), sanitize_params(), and set_attributes().
$body = null protected
Definition at line 62 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
Referenced by get_body(), and get_parameter_order().
$headers = array() protected
Definition at line 53 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
Referenced by get_headers(), and set_headers().
$method = '' protected
Definition at line 32 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
Referenced by __construct(), get_method(), and set_method().
$params protected
Definition at line 44 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
Referenced by get_params(), parse_body_params(), parse_json_params(), set_body_params(), set_default_params(), set_file_params(), set_query_params(), and set_url_params().
$parsed_body = false protected
Definition at line 103 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
$parsed_json = false protected
Definition at line 94 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
$route protected
Definition at line 71 of file api-core/wp-includes/rest-api/class-wp-rest-request.php.
Referenced by __construct(), get_route(), and set_route().
The documentation for this class was generated from the following file:
api-core/wp-includes/rest-api/class-wp-rest-request.php