GravityView: WP_Upgrader_Skin Class Reference
WP_Upgrader_Skin Class Reference
Public Member Functions
__construct ($args=array())
add_strings ()
public
after ()
public
before ()
public
bulk_footer ()
public
bulk_header ()
public
error ($errors)
feedback ($string)
footer ()
public
header ()
public
request_filesystem_credentials ($error=false, $context=false, $allow_relaxed_file_ownership=false)
set_result ($result)
set_upgrader (&$upgrader)
Data Fields
$done_footer = false
$done_header = false
$options = array()
$result = false
$upgrader
Protected Member Functions
decrement_update_count ($type)
Output JavaScript that calls function to decrement the update counts.
Detailed Description
Definition at line 17 of file class-wp-upgrader-skins.php.
Constructor & Destructor Documentation
__construct ($args = array())
Parameters
array $args
Definition at line 29 of file class-wp-upgrader-skins.php.
References wp_parse_args().
Member Function Documentation
add_strings ()
public
Definition at line 46 of file class-wp-upgrader-skins.php.
Referenced by set_upgrader().
after ()
public
Definition at line 150 of file class-wp-upgrader-skins.php.
before ()
public
Definition at line 145 of file class-wp-upgrader-skins.php.
bulk_footer ()
public
Definition at line 190 of file class-wp-upgrader-skins.php.
bulk_header ()
public
Definition at line 185 of file class-wp-upgrader-skins.php.
decrement_update_count ($type) protected
Output JavaScript that calls function to decrement the update counts.
Since
3.9.0
Parameters
string $type Type of update count to decrement. Likely values include 'plugin', 'theme', 'translation', etc.
Definition at line 160 of file class-wp-upgrader-skins.php.
References is_wp_error().
Referenced by Plugin_Upgrader_Skin\after().
error ($errors)
Parameters
string | WP_Error $errors
Definition at line 105 of file class-wp-upgrader-skins.php.
References $errors, $message, elseif, esc_html, feedback(), header(), and is_wp_error().
feedback ($string)
Parameters
string $string
Definition at line 124 of file class-wp-upgrader-skins.php.
References show_message().
Referenced by Plugin_Upgrader_Skin\after(), and error().
footer ()
public
Definition at line 93 of file class-wp-upgrader-skins.php.
header ()
public
Definition at line 81 of file class-wp-upgrader-skins.php.
Referenced by error().
request_filesystem_credentials ($error = false, $context = false, $allow_relaxed_file_ownership = false)
Parameters
bool $error
string $context
bool $allow_relaxed_file_ownership
Returns
type
Definition at line 64 of file class-wp-upgrader-skins.php.
References $url, and wp_nonce_url().
set_result ($result)
Parameters
string | false | WP_Error $result
Definition at line 53 of file class-wp-upgrader-skins.php.
References $result.
set_upgrader (& $upgrader)
Parameters
WP_Upgrader $upgrader
Definition at line 37 of file class-wp-upgrader-skins.php.
References $upgrader, and add_strings().
Field Documentation
$done_footer = false
Definition at line 21 of file class-wp-upgrader-skins.php.
$done_header = false
Definition at line 20 of file class-wp-upgrader-skins.php.
$options = array()
Definition at line 23 of file class-wp-upgrader-skins.php.
$result = false
Definition at line 22 of file class-wp-upgrader-skins.php.
Referenced by set_result().
$upgrader
Definition at line 19 of file class-wp-upgrader-skins.php.
Referenced by set_upgrader().
The documentation for this class was generated from the following file:
class-wp-upgrader-skins.php