GravityView: class-wp-error.php File Reference
class-wp-error.php File Reference
Data Structures
class WP_Error
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
is_wp_error ($thing)
Check whether variable is a WordPress Error.
Function Documentation
is_wp_error ($thing)
Check whether variable is a WordPress Error.
Returns true if $thing is an object of the WP_Error class.
Since
2.1.0
Parameters
mixed $thing Check if unknown variable is a WP_Error object.
Returns
bool True, if WP_Error. False, if not WP_Error.
Definition at line 216 of file class-wp-error.php.
Referenced by WP_SimplePie_File\__construct(), _copy_dir(), _default_wp_die_handler(), WP_Http\_dispatch_request(), _fetch_remote_file(), _get_term_children(), wp_xmlrpc_server\_insert_post(), GV_License_Handler\_license_get_remote_response(), _make_cat_compat(), _wp_ajax_add_hierarchical_term(), _wp_ajax_menu_quick_search(), _wp_put_post_revision(), activate_plugin(), activate_plugins(), WP_Ajax_Response\add(), WP_Press_This\add_category(), GFAPI\add_entries(), GFAPI\add_forms(), Gravity_Api\add_site(), GFForms\addons_page(), Plugin_Upgrader_Skin\after(), WP_Automatic_Updater\after_core_update(), Custom_Image_Header\ajax_header_crop(), WP_Customize_Nav_Menus\ajax_load_available_items(), WP_UnitTestCase\assertNotWPError(), wp_xmlrpc_server\blogger_newPost(), bulk_edit_posts(), GVCommon\check_entry_display(), Plugin_Upgrader\check_package(), Theme_Upgrader\check_package(), Language_Pack_Upgrader\check_package(), Theme_Upgrader\check_parent_theme_filter(), WP_Tax_Query\clean_query(), WP_Links_List_Table\column_categories(), copy_dir(), WP_UnitTest_Factory_For_Thing\create(), GV_UnitTest_Factory_For_User\create_and_set(), GV_UnitTest_Factory_For_View\create_object(), WP_UnitTest_Factory_For_Term\create_object(), Theme_Upgrader\current_after(), Theme_Upgrader\current_before(), Plugin_Upgrader\deactivate_plugin_before_upgrade(), WP_Upgrader_Skin\decrement_update_count(), Plugin_Upgrader\delete_old_plugin(), Theme_Upgrader\delete_old_theme(), GravityView_Delete_Entry\delete_or_trash_entry(), delete_plugins(), delete_theme(), discover_pingback_server_uri(), WP_REST_Server\dispatch(), do_core_upgrade(), WP_Upgrader\download_package(), download_url(), edit_post(), _WP_Editors\editor_settings(), Gravity_Api\ensure_site_registered(), WP_Upgrader_Skin\error(), Bulk_Upgrader_Skin\error(), WP_Theme\errors(), Automatic_Upgrader_Skin\feedback(), WP_oEmbed\fetch(), WP_Press_This\fetch_source_html(), WP_Upgrader\fs_connect(), GravityView_Cache\get(), GFForms\get_addon_info(), GFForms\get_addon_nonces(), get_adjacent_post(), get_ancestors(), get_avatar_data(), get_body_class(), get_bookmark_field(), WP_Network\get_by_path(), get_cat_name(), get_category(), get_category_by_path(), get_category_children(), get_category_link(), get_category_parents(), GFAutoUpgrade\get_changelog(), GFForms\get_changelog(), wpdb\get_col_charset(), wpdb\get_col_length(), get_core_checksums(), get_edit_term_link(), GVCommon\get_entries(), GVCommon\get_entry(), GFFormDisplay\get_form(), WP_Network\get_instance(), get_password_reset_key(), get_permalink(), get_post_class(), get_post_format_link(), get_post_permalink(), WP_Query\get_queried_object(), WP_Tax_Query\get_sql_for_clause(), get_tag_link(), get_term(), get_term_by(), get_term_feed_link(), get_term_field(), get_term_link(), get_term_to_edit(), get_terms_to_edit(), get_the_category(), get_the_category_by_ID(), get_the_term_list(), get_the_terms(), get_theme_feature_list(), gravityview_convert_value_to_term_list(), has_term(), WP_REST_Request\has_valid_params(), heartbeat_autosave(), image_make_intermediate_size(), image_resize(), GravityView_Ajax\import_fields(), GFExport\import_json(), Plugin_Upgrader\install(), Theme_Upgrader\install(), install_dashboard(), WP_Upgrader\install_package(), install_plugin_information(), install_popular_tags(), install_theme_information(), install_themes_feature_list(), is_nav_menu(), is_nav_menu_item(), is_object_in_term(), GFEntryDetail\lead_detail_page(), WP_Image_Editor_Imagick\load(), WP_Customize_Nav_Menus\load_available_items_query(), wp_xmlrpc_server\login(), maybe_add_existing_user_to_blog(), GFPaymentAddOn\maybe_process_callback(), media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), media_sideload_image(), media_upload_form(), media_upload_type_form(), WP_Image_Editor_GD\multi_resize(), WP_Image_Editor_Imagick\multi_resize(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), network_step1(), network_step2(), plugins_api(), populate_network(), WP_Customize_Nav_Menu_Item_Setting\populate_value(), WP_Theme_Install_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), Gravity_Api\prepare_response_body(), GFFormsModel\prepare_value(), GFPaymentAddOn\process_callback_action(), GravityView_Delete_Entry\process_delete(), wpdb\process_field_charsets(), wpdb\process_field_lengths(), WP_HTTP_IXR_Client\query(), redirect_canonical(), register_importer(), register_new_user(), WP_Http\request(), request_filesystem_credentials(), WP_Image_Editor_GD\resize(), rest_ensure_response(), GravityView_Edit_Entry_User_Registration\restore_display_name(), retrieve_password(), WP_Image_Editor_Imagick\rotate(), WP_Upgrader\run(), sanitize_option(), WP_Image_Editor_GD\save(), WP_Image_Editor_Imagick\save(), WP_Press_This\save_post(), WP_Automatic_Updater\send_debug_email(), WP_Automatic_Updater\send_email(), WP_REST_Server\serve_request(), WP_Image_Editor_Imagick\set_quality(), show_message(), WP_Press_This\side_load_images(), WP_Press_This\source_data_fetch_fallback(), Walker_Nav_Menu_Edit\start_el(), Custom_Image_Header\step_2(), Custom_Image_Header\step_3(), stream_preview_image(), wpdb\strip_invalid_text_for_column(), wpdb\strip_invalid_text_from_query(), WP_Press_This\tags_html(), term_description(), the_terms(), themes_api(), trackback(), translations_api(), WP_Upgrader\unpack_package(), unzip_file(), GravityView_Search_WP_Widget\update(), GravityView_Recent_Entries_Widget\update(), WP_Customize_Nav_Menu_Setting\update(), WP_Customize_Nav_Menu_Item_Setting\update(), WP_Automatic_Updater\update(), update_core(), GFAPI\update_entries(), GFAPI\update_entry(), GFAPI\update_entry_field(), GFAPI\update_forms(), Gravity_Api\update_site(), Plugin_Upgrader\upgrade(), Theme_Upgrader\upgrade(), Core_Upgrader\upgrade(), upgrade_430_fix_comments(), GFAsyncUpload\upload(), url_is_accessable_via_ssl(), user_pass_ok(), GF_Field_FileUpload\validate(), validate_active_plugins(), Featured_Content\validate_settings(), WP_Widget_RSS\widget(), wp_admin_bar_edit_menu(), wp_ajax_add_link_category(), wp_ajax_add_menu_item(), wp_ajax_add_meta(), wp_ajax_add_tag(), wp_ajax_add_user(), wp_ajax_crop_image(), wp_ajax_delete_link(), wp_ajax_delete_tag(), wp_ajax_dim_comment(), wp_ajax_get_tagcloud(), wp_ajax_inline_save_tax(), wp_ajax_query_themes(), wp_ajax_update_plugin(), WP_Customize_Widgets\wp_ajax_update_widget(), wp_ajax_upload_attachment(), wp_ajax_wp_fullscreen_save_post(), wp_authenticate_username_password(), wp_can_install_language_pack(), wp_check_mysql_version(), wp_credits(), wp_crop_image(), wp_delete_nav_menu(), wp_delete_term(), wp_xmlrpc_server\wp_deleteTerm(), wp_download_language_pack(), wp_xmlrpc_server\wp_editComment(), wp_xmlrpc_server\wp_editProfile(), wp_xmlrpc_server\wp_editTerm(), WP_Filesystem(), wp_generate_attachment_metadata(), wp_get_available_translations(), wp_get_http(), wp_get_http_headers(), wp_get_image_editor(), wp_get_nav_menu_items(), wp_get_nav_menu_object(), wp_get_nav_menu_to_edit(), wp_get_post_parent_id(), wp_get_term_taxonomy_parent_id(), wp_xmlrpc_server\wp_getTerm(), wp_xmlrpc_server\wp_getTerms(), wp_insert_category(), wp_insert_term(), wp_media_upload_handler(), wp_nav_menu(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_item_taxonomy_meta_box(), wp_nav_menu_update_menu_items(), wp_xmlrpc_server\wp_newCategory(), wp_xmlrpc_server\wp_newTerm(), wp_remote_fopen(), wp_remote_retrieve_body(), wp_remote_retrieve_cookies(), wp_remote_retrieve_header(), wp_remote_retrieve_headers(), wp_remote_retrieve_response_code(), wp_remote_retrieve_response_message(), wp_remove_object_terms(), wp_restore_post_revision(), wp_save_image(), wp_send_json_error(), wp_set_object_terms(), wp_set_wpdb_vars(), wp_setup_nav_menu_item(), wp_signon(), wp_stream_image(), wp_tag_cloud(), wp_unique_term_slug(), wp_update_nav_menu_item(), wp_update_nav_menu_object(), wp_update_plugins(), wp_update_term(), wp_update_themes(), wp_update_user(), wp_version_check(), wp_widget_rss_output(), wp_widget_rss_process(), wp_write_post(), wpmu_activate_signup(), wpmu_create_user(), and write_post().