GravityView: WP_HTTP_Response Class Reference
WP_HTTP_Response Class Reference
Core class used to prepare HTTP responses.
Public Member Functions
__construct ($data=null, $status=200, $headers=array())
Constructor.
__construct ($data=null, $status=200, $headers=array())
Constructor.
get_data ()
Retrieves the response data.
get_data ()
Retrieves the response data.
get_headers ()
Retrieves headers associated with the response.
get_headers ()
Retrieves headers associated with the response.
get_status ()
Retrieves the HTTP return code for the response.
get_status ()
Retrieves the HTTP return code for the response.
header ($key, $value, $replace=true)
Sets a single HTTP header.
header ($key, $value, $replace=true)
Sets a single HTTP header.
jsonSerialize ()
Retrieves the response data for JSON serialization.
jsonSerialize ()
Retrieves the response data for JSON serialization.
set_data ($data)
Sets the response data.
set_data ($data)
Sets the response data.
set_headers ($headers)
Sets all header values.
set_headers ($headers)
Sets all header values.
set_status ($code)
Sets the 3-digit HTTP status code.
set_status ($code)
Sets the 3-digit HTTP status code.
Data Fields
$data
$headers
$status
Detailed Description
Core class used to prepare HTTP responses.
Since
4.4.0
Definition at line 15 of file api-core/wp-includes/class-wp-http-response.php.
Constructor & Destructor Documentation
__construct ($data = null, $status = 200, $headers = array())
Constructor.
Since
4.4.0 public
Parameters
mixed $data Response data. Default null.
int $status Optional. HTTP status code. Default 200.
array $headers Optional. HTTP header map. Default empty array.
Definition at line 54 of file api-core/wp-includes/class-wp-http-response.php.
References $data, $headers, $status, set_headers(), and set_status().
__construct ($data = null, $status = 200, $headers = array())
Constructor.
Since
4.4.0 public
Parameters
mixed $data Response data. Default null.
int $status Optional. HTTP status code. Default 200.
array $headers Optional. HTTP header map. Default empty array.
Definition at line 54 of file wordpress/wp-includes/class-wp-http-response.php.
References $data, $headers, $status, set_headers(), and set_status().
Member Function Documentation
get_data ()
Retrieves the response data.
Since
4.4.0 public
Returns
mixed Response data.
Definition at line 135 of file api-core/wp-includes/class-wp-http-response.php.
References $data.
Referenced by WP_REST_Response\as_error(), and jsonSerialize().
get_data ()
Retrieves the response data.
Since
4.4.0 public
Returns
mixed Response data.
Definition at line 135 of file wordpress/wp-includes/class-wp-http-response.php.
References $data.
get_headers ()
Retrieves headers associated with the response.
Since
4.4.0 public
Returns
array Map of header name to header value.
Definition at line 68 of file wordpress/wp-includes/class-wp-http-response.php.
References $headers.
get_headers ()
Retrieves headers associated with the response.
Since
4.4.0 public
Returns
array Map of header name to header value.
Definition at line 68 of file api-core/wp-includes/class-wp-http-response.php.
References $headers.
get_status ()
Retrieves the HTTP return code for the response.
Since
4.4.0 public
Returns
int The 3-digit HTTP status code.
Definition at line 111 of file api-core/wp-includes/class-wp-http-response.php.
References $status.
Referenced by WP_REST_Response\as_error(), and WP_REST_Response\is_error().
get_status ()
Retrieves the HTTP return code for the response.
Since
4.4.0 public
Returns
int The 3-digit HTTP status code.
Definition at line 111 of file wordpress/wp-includes/class-wp-http-response.php.
References $status.
header ($key, $value, $replace = true)
Sets a single HTTP header.
Since
4.4.0 public
Parameters
string $key Header name.
string $value Header value.
bool $replace Optional. Whether to replace an existing header of the same name. Default true.
Definition at line 95 of file wordpress/wp-includes/class-wp-http-response.php.
References $value.
header ($key, $value, $replace = true)
Sets a single HTTP header.
Since
4.4.0 public
Parameters
string $key Header name.
string $value Header value.
bool $replace Optional. Whether to replace an existing header of the same name. Default true.
Definition at line 95 of file api-core/wp-includes/class-wp-http-response.php.
References $value.
Referenced by WP_REST_Response\link_header().
jsonSerialize ()
Retrieves the response data for JSON serialization.
It is expected that in most implementations, this will return the same as get_data(), however this may be different if you want to do custom JSON data handling.
Since
4.4.0 public
Returns
mixed Any JSON-serializable value.
Definition at line 162 of file wordpress/wp-includes/class-wp-http-response.php.
References get_data().
jsonSerialize ()
Retrieves the response data for JSON serialization.
It is expected that in most implementations, this will return the same as get_data(), however this may be different if you want to do custom JSON data handling.
Since
4.4.0 public
Returns
mixed Any JSON-serializable value.
Definition at line 162 of file api-core/wp-includes/class-wp-http-response.php.
References get_data().
set_data ($data)
Sets the response data.
Since
4.4.0 public
Parameters
mixed $data Response data.
Definition at line 147 of file wordpress/wp-includes/class-wp-http-response.php.
References $data.
set_data ($data)
Sets the response data.
Since
4.4.0 public
Parameters
mixed $data Response data.
Definition at line 147 of file api-core/wp-includes/class-wp-http-response.php.
References $data.
set_headers ($headers)
Sets all header values.
Since
4.4.0 public
Parameters
array $headers Map of header name to header value.
Definition at line 80 of file wordpress/wp-includes/class-wp-http-response.php.
References $headers.
set_headers ($headers)
Sets all header values.
Since
4.4.0 public
Parameters
array $headers Map of header name to header value.
Definition at line 80 of file api-core/wp-includes/class-wp-http-response.php.
References $headers.
Referenced by __construct().
set_status ($code)
Sets the 3-digit HTTP status code.
Since
4.4.0 public
Parameters
int $code HTTP status.
Definition at line 123 of file wordpress/wp-includes/class-wp-http-response.php.
References absint().
set_status ($code)
Sets the 3-digit HTTP status code.
Since
4.4.0 public
Parameters
int $code HTTP status.
Definition at line 123 of file api-core/wp-includes/class-wp-http-response.php.
References absint().
Referenced by __construct().
Field Documentation
$data
Definition at line 24 of file api-core/wp-includes/class-wp-http-response.php.
Referenced by __construct(), WP_REST_Response\as_error(), get_data(), and set_data().
$headers
Definition at line 33 of file api-core/wp-includes/class-wp-http-response.php.
Referenced by __construct(), get_headers(), and set_headers().
$status
Definition at line 42 of file api-core/wp-includes/class-wp-http-response.php.
Referenced by __construct(), and get_status().
The documentation for this class was generated from the following file:
api-core/wp-includes/class-wp-http-response.php