GravityView: GravityView_Powered_By Class Reference
GravityView_Powered_By Class Reference
If this file is called directly, abort.
Public Member Functions
__construct ()
GravityView_Powered_By constructor.
maybe_add_link ()
Prints a HTML link to GravityView's site if "Powered By" GravityView setting is enabled.
Data Fields
const url = 'https://gravityview.co/powered-by/'
Protected Member Functions
get_url ()
Returns the URL to GravityView.
Detailed Description
If this file is called directly, abort.
Add a Powered By link below Views.
Since
2.5.3
Definition at line 15 of file class-gravityview-powered-by.php.
Constructor & Destructor Documentation
__construct()
__construct ()
GravityView_Powered_By constructor.
Definition at line 22 of file class-gravityview-powered-by.php.
Member Function Documentation
get_url()
get_url () protected
Returns the URL to GravityView.
Returns
string URL to GravityView (not sanitized)
Runs Filter:
gravityview/powered_by/url Modify the URL returned by the Powered By link
Parameters
$url string The URL passed to the Powered By link
Definition at line 60 of file class-gravityview-powered-by.php.
References $url, and gravityview().
Referenced by maybe_add_link().
maybe_add_link()
maybe_add_link ()
Prints a HTML link to GravityView's site if "Powered By" GravityView setting is enabled.
Returns
void
Runs Filter:
gravityview/powered_by/text Modify the anchor text for the Powered By link
Parameters
string $anchor_text Anchor text for the Powered By link. Default: "Powered by GravityView". Will be sanitized before display.
Definition at line 31 of file class-gravityview-powered-by.php.
References $url, get_url(), and gravityview().
Field Documentation
url
const url = 'https://gravityview.co/powered-by/'
Definition at line 17 of file class-gravityview-powered-by.php.
The documentation for this class was generated from the following file:
class-gravityview-powered-by.php