GravityView: Text_Diff_Renderer Class Reference
Text_Diff_Renderer Class Reference
Public Member Functions
__construct ($params=array())
Constructor.
_added ($lines)
_block ($xbeg, $xlen, $ybeg, $ylen, &$edits)
_blockHeader ($xbeg, $xlen, $ybeg, $ylen)
_changed ($orig, $final)
_context ($lines)
_deleted ($lines)
_endBlock ()
_endDiff ()
_lines ($lines, $prefix= ' ')
_startBlock ($header)
_startDiff ()
getParams ()
Get any renderer parameters.
render ($diff)
Renders a diff.
Text_Diff_Renderer ($params=array())
PHP4 constructor.
Data Fields
$_leading_context_lines = 0
Number of leading context "lines" to preserve.
$_trailing_context_lines = 0
Number of trailing context "lines" to preserve.
Detailed Description
Definition at line 15 of file Renderer.php.
Constructor & Destructor Documentation
__construct ($params = array())
Constructor.
Definition at line 36 of file Renderer.php.
References $value.
Member Function Documentation
_added ($lines)
Definition at line 227 of file Renderer.php.
References _lines().
Referenced by _block(), and _changed().
_block ($xbeg, $xlen, $ybeg, $ylen, & $edits)
Definition at line 151 of file Renderer.php.
References $output, _added(), _blockHeader(), _changed(), _context(), _deleted(), _endBlock(), and _startBlock().
Referenced by render().
_blockHeader ($xbeg, $xlen, $ybeg, $ylen)
Definition at line 188 of file Renderer.php.
References elseif.
Referenced by _block().
_changed ($orig, $final)
Definition at line 237 of file Renderer.php.
References _added(), and _deleted().
Referenced by _block().
_context ($lines)
Definition at line 222 of file Renderer.php.
References _lines().
Referenced by _block().
_deleted ($lines)
Definition at line 232 of file Renderer.php.
References _lines().
Referenced by _block(), and _changed().
_endBlock ()
Definition at line 212 of file Renderer.php.
Referenced by _block().
_endDiff ()
Definition at line 183 of file Renderer.php.
Referenced by render().
_lines ($lines, $prefix = ' ')
Definition at line 217 of file Renderer.php.
References $prefix.
Referenced by _added(), _context(), and _deleted().
_startBlock ($header)
Definition at line 207 of file Renderer.php.
Referenced by _block().
_startDiff ()
Definition at line 178 of file Renderer.php.
Referenced by render().
getParams ()
Get any renderer parameters.
Returns
array All parameters of this renderer object.
Definition at line 58 of file Renderer.php.
Referenced by Text_Diff_Renderer_inline\_changed().
render ($diff)
Renders a diff.
Parameters
Text_Diff $diff A Text_Diff object.
Returns
string The formatted output.
Definition at line 77 of file Renderer.php.
References $_leading_context_lines, $_trailing_context_lines, $i, $output, _block(), _endDiff(), and _startDiff().
Text_Diff_Renderer ($params = array())
PHP4 constructor.
Definition at line 49 of file Renderer.php.
Field Documentation
$_leading_context_lines = 0
Number of leading context "lines" to preserve.
This should be left at zero for this class, but subclasses may want to set this to other values.
Definition at line 23 of file Renderer.php.
Referenced by render().
$_trailing_context_lines = 0
Number of trailing context "lines" to preserve.
This should be left at zero for this class, but subclasses may want to set this to other values.
Definition at line 31 of file Renderer.php.
Referenced by render().
The documentation for this class was generated from the following file:
Renderer.php