GravityView: PotExtMeta Class Reference
PotExtMeta Class Reference
Public Member Functions
append ($ext_filename, $pot_filename, $headers=null)
load_from_file ($ext_filename)
usage ()
Data Fields
$headers
Detailed Description
Definition at line 14 of file pot-ext-meta.php.
Member Function Documentation
append ($ext_filename, $pot_filename, $headers = null)
Definition at line 50 of file pot-ext-meta.php.
References $headers, and load_from_file().
Referenced by MakePOT\wp_admin(), GruntMakePOT\wp_plugin(), MakePOT\wp_plugin(), GruntMakePOT\wp_theme(), and MakePOT\wp_theme().
load_from_file ($ext_filename)
Definition at line 32 of file pot-ext-meta.php.
References $entry, MakePOT\get_addon_header(), and MakePOT\get_first_lines().
Referenced by append().
usage ()
Definition at line 26 of file pot-ext-meta.php.
Field Documentation
$headers
Initial value:
= array(
        'Plugin Name',
        'Theme Name',
        'Plugin URI',
        'Theme URI',
        'Description',
        'Author',
        'Author URI',
        'Tags',
    )
Definition at line 15 of file pot-ext-meta.php.
Referenced by append().
The documentation for this class was generated from the following file:
pot-ext-meta.php