GravityView: SimplePie_Registry Class Reference
SimplePie_Registry Class Reference
Public Member Functions
__construct ()
Constructor.
& call ($type, $method, $parameters=array())
Call a static method for a type.
& create ($type, $parameters=array())
Create a new instance of a given type.
get_class ($type)
Get the class registered for a type.
register ($type, $class, $legacy=false)
Register a class.
Protected Attributes
$classes = array()
$default
$legacy = array()
Detailed Description
Definition at line 52 of file Registry.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
No-op
Definition at line 104 of file Registry.php.
Member Function Documentation
& call ($type, $method, $parameters = array())
Call a static method for a type.
Parameters
string $type
string $method
array $parameters
Returns
mixed
Definition at line 202 of file Registry.php.
References get_class().
& create ($type, $parameters = array())
Create a new instance of a given type.
Parameters
string $type
array $parameters Parameters to pass to the constructor
Returns
object Instance of class
Definition at line 160 of file Registry.php.
References $class, and get_class().
get_class ($type)
Get the class registered for a type.
Where possible, use {
See also
create()} or {
call()} instead
Parameters
string $type
Returns
string|null
Definition at line 139 of file Registry.php.
References null.
Referenced by call(), and create().
register ($type, $class, $legacy = false)
Register a class.
Parameters
string $type See {
See also
$default} for names
Parameters
string $class Class name, must subclass the corresponding default
bool $legacy Whether to enable legacy support for this class
Returns
bool Successfulness
Definition at line 114 of file Registry.php.
References $class.
Field Documentation
$classes = array() protected
Definition at line 89 of file Registry.php.
$default protected
Initial value:
= array(
        'Cache' => 'SimplePie_Cache',
        'Locator' => 'SimplePie_Locator',
        'Parser' => 'SimplePie_Parser',
        'File' => 'SimplePie_File',
        'Sanitize' => 'SimplePie_Sanitize',
        'Item' => 'SimplePie_Item',
        'Author' => 'SimplePie_Author',
        'Category' => 'SimplePie_Category',
        'Enclosure' => 'SimplePie_Enclosure',
        'Caption' => 'SimplePie_Caption',
        'Copyright' => 'SimplePie_Copyright',
        'Credit' => 'SimplePie_Credit',
        'Rating' => 'SimplePie_Rating',
        'Restriction' => 'SimplePie_Restriction',
        'Content_Type_Sniffer' => 'SimplePie_Content_Type_Sniffer',
        'Source' => 'SimplePie_Source',
        'Misc' => 'SimplePie_Misc',
        'XML_Declaration_Parser' => 'SimplePie_XML_Declaration_Parser',
        'Parse_Date' => 'SimplePie_Parse_Date',
    )
Definition at line 61 of file Registry.php.
$legacy = array() protected
Definition at line 97 of file Registry.php.
The documentation for this class was generated from the following file:
Registry.php