GravityView: getid3_ogg Class Reference
getid3_ogg Class Reference
Public Member Functions
Analyze ()
ParseOggPageHeader ()
ParseOpusPageHeader (&$filedata, &$filedataoffset, &$oggpageinfo)
ParseVorbisComments ()
ParseVorbisPageHeader (&$filedata, &$filedataoffset, &$oggpageinfo)
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Static Public Member Functions
static get_quality_from_nominal_bitrate ($nominal_bitrate)
static OggPageSegmentLength ($OggInfoArray, $SegmentNumber=1)
static SpeexBandModeLookup ($mode)
static TheoraColorSpace ($colorspace_id)
static TheoraPixelFormat ($pixelformat_id)
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
Definition at line 19 of file module.audio.ogg.php.
Member Function Documentation
Analyze ()
Definition at line 22 of file module.audio.ogg.php.
References getid3_lib\BigEndian2Int(), elseif, getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\ftell(), getid3_lib\intValueSupported(), getid3_lib\LittleEndian2Int(), ParseOggPageHeader(), ParseOpusPageHeader(), ParseVorbisComments(), ParseVorbisPageHeader(), and SpeexBandModeLookup().
static get_quality_from_nominal_bitrate ($nominal_bitrate) static
Definition at line 792 of file module.audio.ogg.php.
References elseif.
static OggPageSegmentLength ($OggInfoArray, $SegmentNumber = 1) static
Definition at line 778 of file module.audio.ogg.php.
References $i, and $value.
Referenced by ParseVorbisComments().
ParseOggPageHeader ()
Definition at line 480 of file module.audio.ogg.php.
References $i, getid3_handler\feof(), getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\ftell(), and getid3_lib\LittleEndian2Int().
Referenced by Analyze(), and ParseVorbisComments().
ParseOpusPageHeader (& $filedata, & $filedataoffset, & $oggpageinfo)
Definition at line 430 of file module.audio.ogg.php.
References getid3_lib\LittleEndian2Int().
Referenced by Analyze().
ParseVorbisComments ()
Definition at line 532 of file module.audio.ogg.php.
References getid3_handler\$getid3, $i, elseif, getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\ftell(), getid3_lib\GetDataImageSize(), getid3_lib\LittleEndian2Int(), getid3_handler\notice(), OggPageSegmentLength(), ParseOggPageHeader(), and getid3_handler\warning().
Referenced by Analyze().
ParseVorbisPageHeader (& $filedata, & $filedataoffset, & $oggpageinfo)
Definition at line 381 of file module.audio.ogg.php.
References getid3_lib\LittleEndian2Int().
Referenced by Analyze().
static SpeexBandModeLookup ($mode) static
Definition at line 767 of file module.audio.ogg.php.
References $mode, and null.
Referenced by Analyze().
static TheoraColorSpace ($colorspace_id) static
Definition at line 815 of file module.audio.ogg.php.
References null.
static TheoraPixelFormat ($pixelformat_id) static
Definition at line 827 of file module.audio.ogg.php.
References null.
The documentation for this class was generated from the following file:
module.audio.ogg.php