GravityView: GravityView_View_Test Class Reference
GravityView_View_Test Class Reference
gravityviewview
Public Member Functions
test__get ()
GravityView_View::__get()
test_add_id_specific_templates ()
GravityView_View::add_id_specific_templates
test_BackLinkLabel ()
GravityView_View::setBackLinkLabel GravityView_View::getBackLinkLabel GravityView_View::setForm GravityView_View::setCurrentEntry
test_getPaginationCounts ()
GravityView_View::getPaginationCounts GravityView_View::getPaging GravityView_View::setPaging
test_TotalEntries ()
GravityView_View::setTotalEntries GravityView_View::getTotalEntries
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
gravityviewview
Since
1.15.2
Definition at line 9 of file GravityView_View_Test.php.
Member Function Documentation
test__get ()
GravityView_View::__get()
Definition at line 14 of file GravityView_View_Test.php.
References GravityView_View\getInstance().
test_add_id_specific_templates ()
GravityView_View::add_id_specific_templates
Definition at line 113 of file GravityView_View_Test.php.
References $templates, and GravityView_View\getInstance().
test_BackLinkLabel ()
GravityView_View::setBackLinkLabel GravityView_View::getBackLinkLabel GravityView_View::setForm GravityView_View::setCurrentEntry
Definition at line 29 of file GravityView_View_Test.php.
References GravityView_View\getInstance().
test_getPaginationCounts ()
GravityView_View::getPaginationCounts GravityView_View::getPaging GravityView_View::setPaging
See also
GravityView_frontend::get_view_entries
Definition at line 80 of file GravityView_View_Test.php.
References GravityView_View\getInstance().
test_TotalEntries ()
GravityView_View::setTotalEntries GravityView_View::getTotalEntries
Definition at line 51 of file GravityView_View_Test.php.
References GravityView_View\getInstance().
The documentation for this class was generated from the following file:
GravityView_View_Test.php