GravityView: SecurityChecks Class Reference
SecurityChecks Class Reference
Public Member Functions
__construct (Config $config, Logging $logging)
in_lockdown ()
Checks if TrustedLogin is currently in lockdown.
verify ($passed_user_identifier='')
Verifies that a provided user identifier is still valid.
Data Fields
const ACCESSKEY_LIMIT_COUNT = 3
const ACCESSKEY_LIMIT_EXPIRY = 36000
const BRUTE_FORCE_ENDPOINT = 'report-brute-force'
const LOCKDOWN_EXPIRY = 72000
const VERIFY_SUPPORT_AGENT_ENDPOINT = 'verify-identifier'
Private Member Functions
check_approved_identifier ($secret_id)
Makes double-y sure the TrustedLogin Server approves this support-agent login.
check_brute_force ($identifier)
Detects if this identifier indicates that the site's access keys may be under a brute force attack.
do_lockdown ()
Locks down the site to new access by TrustedLogin identifiers, reports lockdown to TrustedLogin.
get_ip ()
Returns the IP address of the requester.
in_local_development ()
Is this site in local development mode?
maybe_add_used_accesskey ($user_identifier='')
report_lockdown ()
Notifies the TrustedLogin server that a site may be under a possible brute-force attack.
Private Attributes
$config
$in_lockdown_transient
$logging
$used_accesskey_transient
Detailed Description
Definition at line 17 of file SecurityChecks.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Logging $logging)
Definition at line 64 of file SecurityChecks.php.
References SecurityChecks\$config, and SecurityChecks\$logging.
Member Function Documentation
check_approved_identifier()
check_approved_identifier ($secret_id) private
Makes double-y sure the TrustedLogin Server approves this support-agent login.
This function sends server variables to the TrustedLogin server to help prevent a number of attack vectors. It is only ever triggered as part of the auto-login sequence. The session data synced will only ever be from authorized support teams, or potential attackers.
Parameters
string $secret_id The secret ID for the site.
Returns
true|WP_Error True: the TrustedLogin service was reached and the login remains valid. WP_Error: The service wasn't reachable or the service responded that the secret ID wasn't valid.
This array contains information from the Vendor's support agent as a means of protecting against potential breaches.
No site user/visitor/admin data is sent back to TrustedLogin server.
Definition at line 219 of file SecurityChecks.php.
References SecurityChecks\get_ip().
Referenced by SecurityChecks\verify().
check_brute_force()
check_brute_force ($identifier) private
Detects if this identifier indicates that the site's access keys may be under a brute force attack.
Parameters
string $identifier The identifier provided via {
See also
Endpoint::maybe_login_support()}
Returns
true|WP_Error WP_Error if an anomaly was detected and site may be under attack. Else true.
Definition at line 138 of file SecurityChecks.php.
References SecurityChecks\in_local_development(), and SecurityChecks\maybe_add_used_accesskey().
Referenced by SecurityChecks\verify().
do_lockdown()
do_lockdown () private
Locks down the site to new access by TrustedLogin identifiers, reports lockdown to TrustedLogin.
Runs after the site is locked down to access from the Vendor
Definition at line 293 of file SecurityChecks.php.
References SecurityChecks\report_lockdown().
Referenced by SecurityChecks\verify().
get_ip()
get_ip () private
Returns the IP address of the requester.
Returns
null|string Returns null if REMOTE_ADDR isn't set, string IP address otherwise.
Definition at line 191 of file SecurityChecks.php.
Referenced by SecurityChecks\check_approved_identifier(), and SecurityChecks\report_lockdown().
in_local_development()
in_local_development () private
Is this site in local development mode?
() If available, used to fetch site's development environment
See also
https://developer.wordpress.org/reference/functions/wp_get_environment_type/
To bypass lockdown checks, set a WordPress environment to local or development. Alternately, you may add a constant to the site's wp-config.php file formatted as TRUSTEDLOGIN_TESTING_{EXAMPLE} where {EXAMPLE} is replaced with the project's upper-cased namespace.
Returns
bool True: site is in local or development environment. False: site is live.
Definition at line 328 of file SecurityChecks.php.
Referenced by SecurityChecks\check_brute_force(), and SecurityChecks\in_lockdown().
in_lockdown()
in_lockdown ()
Checks if TrustedLogin is currently in lockdown.
Returns
int|false Int: in lockdown. The value returned is the timestamp when lockdown ends. False: not in lockdown, or overridden by a constant.
Definition at line 358 of file SecurityChecks.php.
References SecurityChecks\in_local_development().
Referenced by SecurityChecks\verify().
maybe_add_used_accesskey()
maybe_add_used_accesskey ($user_identifier = '') private
Parameters
string $user_identifier
Returns
mixed
Definition at line 166 of file SecurityChecks.php.
Referenced by SecurityChecks\check_brute_force().
report_lockdown()
report_lockdown () private
Notifies the TrustedLogin server that a site may be under a possible brute-force attack.
Since
1.0.0
Returns
true|WP_Error If the notification was sent, returns true, otherwise WP_Error on issue.
This array contains identifiable information of either a malicious actor or the Vendor's support agent who is triggering the alert.
No site user/visitor/admin data is sent back to TrustedLogin server.
Definition at line 258 of file SecurityChecks.php.
References SecurityChecks\get_ip().
Referenced by SecurityChecks\do_lockdown().
verify()
verify ($passed_user_identifier = '')
Verifies that a provided user identifier is still valid.
Multiple security checks are performed, including brute-force and known-attacker-list checks
Parameters
string $passed_user_identifier The identifier provided via {
See also
SupportUser::maybe_login()}
Returns
true|WP_Error True if identifier passes checks. WP_Error if not.
Definition at line 82 of file SecurityChecks.php.
References SecurityChecks\check_approved_identifier(), SecurityChecks\check_brute_force(), SecurityChecks\do_lockdown(), Encryption\hash(), and SecurityChecks\in_lockdown().
Field Documentation
$config
Config $config private
Definition at line 27 of file SecurityChecks.php.
Referenced by SecurityChecks\__construct().
$in_lockdown_transient
$in_lockdown_transient private
Definition at line 37 of file SecurityChecks.php.
$logging
Logging $logging private
Definition at line 22 of file SecurityChecks.php.
Referenced by SecurityChecks\__construct().
$used_accesskey_transient
$used_accesskey_transient private
Definition at line 32 of file SecurityChecks.php.
ACCESSKEY_LIMIT_COUNT
const ACCESSKEY_LIMIT_COUNT = 3
Definition at line 42 of file SecurityChecks.php.
ACCESSKEY_LIMIT_EXPIRY
const ACCESSKEY_LIMIT_EXPIRY = 36000
Definition at line 47 of file SecurityChecks.php.
BRUTE_FORCE_ENDPOINT
const BRUTE_FORCE_ENDPOINT = 'report-brute-force'
Definition at line 57 of file SecurityChecks.php.
LOCKDOWN_EXPIRY
const LOCKDOWN_EXPIRY = 72000
Definition at line 52 of file SecurityChecks.php.
VERIFY_SUPPORT_AGENT_ENDPOINT
const VERIFY_SUPPORT_AGENT_ENDPOINT = 'verify-identifier'
Definition at line 62 of file SecurityChecks.php.
The documentation for this class was generated from the following file:
SecurityChecks.php