GravityView: WP_Rewrite Class Reference
WP_Rewrite Class Reference
Core class used to implement a rewrite component API.
Public Member Functions
__construct ()
Constructor - Calls init(), which runs setup.
add_endpoint ($name, $places, $query_var=true)
Adds an endpoint, like /trackback/.
add_external_rule ($regex, $query)
Adds a rewrite rule that doesn't correspond to index.php.
add_permastruct ($name, $struct, $args=array())
Adds a new permalink structure.
add_rewrite_tag ($tag, $regex, $query)
Adds or updates existing rewrite tags (e.g.
add_rule ($regex, $query, $after= 'bottom')
Adds a rewrite rule that transforms a URL structure to a set of query vars.
flush_rules ($hard=true)
Removes rewrite rules and then recreate rewrite rules.
generate_rewrite_rule ($permalink_structure, $walk_dirs=false)
Generates rewrite rules with permalink structure and walking directory only.
generate_rewrite_rules ($permalink_structure, $ep_mask=EP_NONE, $paged=true, $feed=true, $forcomments=false, $walk_dirs=true, $endpoints=true)
Generates rewrite rules from a permalink structure.
get_author_permastruct ()
Retrieves the author permalink structure.
get_category_permastruct ()
Retrieves the permalink structure for categories.
get_comment_feed_permastruct ()
Retrieves the comment feed permalink structure.
get_date_permastruct ()
Retrieves date permalink structure, with year, month, and day.
get_day_permastruct ()
Retrieves the day permalink structure with month and year.
get_extra_permastruct ($name)
Retrieves an extra permalink structure by name.
get_feed_permastruct ()
Retrieves the feed permalink structure.
get_month_permastruct ()
Retrieves the month permalink structure without day and with year.
get_page_permastruct ()
Retrieves the page permalink structure.
get_search_permastruct ()
Retrieves the search permalink structure.
get_tag_permastruct ()
Retrieve the permalink structure for tags.
get_year_permastruct ()
Retrieves the year permalink structure without month and day.
iis7_url_rewrite_rules ($add_parent_tags=false)
Retrieves IIS7 URL Rewrite formatted rewrite rules to write to web.config file.
init ()
Sets up the object's properties.
mod_rewrite_rules ()
Retrieves mod_rewrite-formatted rewrite rules to write to .htaccess.
page_rewrite_rules ()
Retrieves all of the rewrite rules for pages.
page_uri_index ()
Retrieves all page and attachments for pages URIs.
preg_index ($number)
Indexes for matches for usage in preg_*() functions.
remove_permastruct ($name)
Removes a permalink structure.
remove_rewrite_tag ($tag)
Removes an existing rewrite tag.
rewrite_rules ()
Constructs rewrite matches and queries from permalink structure.
set_category_base ($category_base)
Sets the category base for the category permalink.
set_permalink_structure ($permalink_structure)
Sets the main permalink structure for the site.
set_tag_base ($tag_base)
Sets the tag base for the tag permalink.
using_index_permalinks ()
Determines whether permalinks are being used and rewrite module is not enabled.
using_mod_rewrite_permalinks ()
Determines whether permalinks are being used and rewrite module is enabled.
using_permalinks ()
Determines whether permalinks are being used.
wp_rewrite_rules ()
Retrieves the rewrite rules.
Data Fields
$author_base = 'author'
$author_structure
$comment_feed_structure
$comments_base = 'comments'
$comments_pagination_base = 'comment-page'
$date_structure
$endpoints
$extra_permastructs = array()
$extra_rules = array()
$extra_rules_top = array()
$feed_base = 'feed'
$feed_structure
$feeds = array('feed', 'rdf', 'rss', 'rss2', 'atom')
$front
$index = 'index.php'
$matches = ''
$non_wp_rules = array()
$page_structure
$pagination_base = 'page'
$permalink_structure
$queryreplace
$rewritecode
$rewritereplace
$root = ''
$rules
$search_base = 'search'
$search_structure
$use_trailing_slashes
$use_verbose_page_rules = true
$use_verbose_rules = false
Detailed Description
Core class used to implement a rewrite component API.
The WordPress Rewrite class writes the rewrite module rules to the .htaccess file. It also handles parsing the request to get the correct setup for the WordPress Query class.
The Rewrite along with WP class function as a front controller for WordPress. You can add rules to trigger your page view and processing using this component. The full functionality of a front controller does not exist, meaning you can't define how the template files load based on the rewrite rules.
Since
1.5.0
Definition at line 25 of file class-wp-rewrite.php.
Constructor & Destructor Documentation
__construct ()
Constructor - Calls init(), which runs setup.
Since
1.5.0 public
Definition at line 1943 of file class-wp-rewrite.php.
References init().
Member Function Documentation
add_endpoint ($name, $places, $query_var = true)
Adds an endpoint, like /trackback/.
Since
2.1.0
3.9.0 $query_var parameter added.
4.3.0 Added support for skipping query var registration by passing false to $query_var. public
See also
add_rewrite_endpoint() for full documentation. WP $wp
Parameters
string $name Name of the endpoint.
int $places Endpoint mask describing the places the endpoint should be added.
string | bool $query_var Optional. Name of the corresponding query variable. Pass false to skip registering a query_var for this endpoint. Defaults to the value of $name.
Definition at line 1688 of file class-wp-rewrite.php.
References $name, $wp, and null.
add_external_rule ($regex, $query)
Adds a rewrite rule that doesn't correspond to index.php.
Since
2.1.0 public
Parameters
string $regex Regular expression to match request against.
string $query The corresponding query vars for this rewrite rule.
Definition at line 1667 of file class-wp-rewrite.php.
Referenced by add_rule().
add_permastruct ($name, $struct, $args = array())
Adds a new permalink structure.
A permalink structure (permastruct) is an abstract definition of a set of rewrite rules; it is an easy way of expressing a set of regular expressions that rewrite to a set of query strings. The new permastruct is added to the WP_Rewrite::$extra_permastructs array.
When the rewrite rules are built by WP_Rewrite::rewrite_rules(), all of these extra permastructs are passed to WP_Rewrite::generate_rewrite_rules() which transforms them into the regular expressions that many love to hate.
The $args parameter gives you control over how WP_Rewrite::generate_rewrite_rules() works on the new permastruct.
Since
2.5.0 public
Parameters
string $name Name for permalink structure.
string $struct Permalink structure (e.g. category/category%)
array $args { Optional. Arguments for building rewrite rules based on the permalink structure. Default empty array.
bool $with_front Whether the structure should be prepended with WP_Rewrite::$front. Default true. int $ep_mask The endpoint mask defining which endpoints are added to the structure. Accepts EP_NONE, EP_PERMALINK, EP_ATTACHMENT, EP_DATE, EP_YEAR, EP_MONTH, EP_DAY, EP_ROOT, EP_COMMENTS, EP_SEARCH, EP_CATEGORIES, EP_TAGS, EP_AUTHORS, EP_PAGES, EP_ALL_ARCHIVES, and EP_ALL. Default EP_NONE. bool $paged Whether archive pagination rules should be added for the structure. Default true. bool $feed Whether feed rewrite rules should be added for the structure. Default true. bool $forcomments Whether the feed rules should be a query for a comments feed. Default false. bool $walk_dirs Whether the 'directories' making up the structure should be walked over and rewrite rules built for each in-turn. Default true. bool $endpoints Whether endpoints should be applied to the generated rules. Default true. }
Definition at line 1741 of file class-wp-rewrite.php.
References $name, EP_NONE, and wp_parse_args().
add_rewrite_tag ($tag, $regex, $query)
Adds or updates existing rewrite tags (e.g.
postname%).
If the tag already exists, replace the existing pattern and query for that tag, otherwise add the new tag.
Since
1.5.0 public
See also
WP_Rewrite::$rewritecode
WP_Rewrite::$rewritereplace
WP_Rewrite::$queryreplace
Parameters
string $tag Name of the rewrite tag to add or update.
string $regex Regular expression to substitute the tag for in rewrite rules.
string $query String to append to the rewritten query. Must end in '='.
Definition at line 832 of file class-wp-rewrite.php.
References null.
Referenced by page_rewrite_rules().
add_rule ($regex, $query, $after = 'bottom')
Adds a rewrite rule that transforms a URL structure to a set of query vars.
Any value in the $after parameter that isn't 'bottom' will result in the rule being placed at the top of the rewrite rules.
Since
2.1.0
4.4.0 Array support was added to the $query parameter. public
Parameters
string $regex Regular expression to match request against.
string | array $query The corresponding query vars for this rewrite rule.
string $after Optional. Priority of the new rule. Accepts 'top' or 'bottom'. Default 'bottom'.
Definition at line 1635 of file class-wp-rewrite.php.
References $front, $index, add_external_rule(), and add_query_arg().
flush_rules ($hard = true)
Removes rewrite rules and then recreate rewrite rules.
Calls WP_Rewrite::wp_rewrite_rules() after removing the 'rewrite_rules' option. If the function named 'save_mod_rewrite_rules' exists, it will be called.
Since
2.0.1 public
bool $do_hard_later
Parameters
bool $hard Whether to update .htaccess (hard flush) or just update rewrite_rules option (soft flush). Default is true (hard).
Filter whether a "hard" rewrite rule flush should be performed when requested.
A "hard" flush updates .htaccess (Apache) or web.config (IIS).
Since
3.7.0
Parameters
bool $hard Whether to flush rewrite rules "hard". Default true.
Definition at line 1794 of file class-wp-rewrite.php.
References add_action(), apply_filters(), did_action(), iis7_save_url_rewrite_rules(), null, save_mod_rewrite_rules(), update_option(), and wp_rewrite_rules().
generate_rewrite_rule ($permalink_structure, $walk_dirs = false)
Generates rewrite rules with permalink structure and walking directory only.
Shorten version of WP_Rewrite::generate_rewrite_rules() that allows for shorter list of parameters. See the method for longer description of what generating rewrite rules does.
Since
1.5.0 public
See also
WP_Rewrite::generate_rewrite_rules() See for long description and rest of parameters.
Parameters
string $permalink_structure The permalink structure to generate rules.
bool $walk_dirs Optional, default is false. Whether to create list of directories to walk over.
Returns
array
Definition at line 1244 of file class-wp-rewrite.php.
References $permalink_structure, EP_NONE, and generate_rewrite_rules().
generate_rewrite_rules ($permalink_structure, $ep_mask = EP_NONE, $paged = true, $feed = true, $forcomments = false, $walk_dirs = true, $endpoints = true)
Generates rewrite rules from a permalink structure.
The main WP_Rewrite function for building the rewrite rule list. The contents of the function is a mix of black magic and regular expressions, so best just ignore the contents and move to the parameters.
Since
1.5.0 public
Parameters
string $permalink_structure The permalink structure.
int $ep_mask Optional. Endpoint mask defining what endpoints are added to the structure. Accepts EP_NONE, EP_PERMALINK, EP_ATTACHMENT, EP_DATE, EP_YEAR, EP_MONTH, EP_DAY, EP_ROOT, EP_COMMENTS, EP_SEARCH, EP_CATEGORIES, EP_TAGS, EP_AUTHORS, EP_PAGES, EP_ALL_ARCHIVES, and EP_ALL. Default EP_NONE.
bool $paged Optional. Whether archive pagination rules should be added for the structure. Default true.
bool $feed Optional Whether feed rewrite rules should be added for the structure. Default true.
bool $forcomments Optional. Whether the feed rules should be a query for a comments feed. Default false.
bool $walk_dirs Optional. Whether the 'directories' making up the structure should be walked over and rewrite rules built for each in-turn. Default true.
bool $endpoints Optional. Whether endpoints should be applied to the generated rewrite rules. Default true.
Returns
array Rewrite rule list.
Definition at line 894 of file class-wp-rewrite.php.
References $front, $i, $index, $page, $paged, $permalink_structure, $post, elseif, EP_ATTACHMENT, EP_DAY, EP_MONTH, EP_NONE, EP_PAGES, EP_PERMALINK, EP_ROOT, EP_YEAR, get_option(), get_post_types(), is_post_type_hierarchical(), preg_index(), and str_replace.
Referenced by generate_rewrite_rule(), page_rewrite_rules(), and rewrite_rules().
get_author_permastruct ()
Retrieves the author permalink structure.
The permalink structure is front property, author base, and finally '/author'. Will set the author_structure property and then return it without attempting to set the value again.
Since
1.5.0 public
Returns
string|false False if not found. Permalink structure string.
Definition at line 697 of file class-wp-rewrite.php.
References $author_structure.
Referenced by rewrite_rules().
get_category_permastruct ()
Retrieves the permalink structure for categories.
If the category_base property has no value, then the category structure will have the front property value, followed by 'category', and finally 'category'. If it does, then the root property will be used, along with the category_base property value.
Since
1.5.0 public
Returns
string|false False on failure. Category permalink structure.
Definition at line 645 of file class-wp-rewrite.php.
References get_extra_permastruct().
get_comment_feed_permastruct ()
Retrieves the comment feed permalink structure.
The permalink structure is root property, comment base property, feed base and finally '/feed'. Will set the comment_feed_structure property and then return it without attempting to set the value again.
Since
1.5.0 public
Returns
string|false False if not found. Permalink structure string.
Definition at line 801 of file class-wp-rewrite.php.
References $comment_feed_structure.
get_date_permastruct ()
Retrieves date permalink structure, with year, month, and day.
The permalink structure for the date, if not set already depends on the permalink structure. It can be one of three formats. The first is year, month, day; the second is day, month, year; and the last format is month, day, year. These are matched against the permalink structure for which one is used. If none matches, then the default will be used, which is year, month, day.
Prevents post ID and date permalinks from overlapping. In the case of post_id, the date permalink will be prepended with front permalink with 'date/' before the actual permalink to form the complete date permalink structure.
Since
1.5.0 public
Returns
string|false False on no permalink structure. Date permalink structure.
Definition at line 526 of file class-wp-rewrite.php.
References $date_structure, and $front.
Referenced by get_day_permastruct(), get_month_permastruct(), get_year_permastruct(), and rewrite_rules().
get_day_permastruct ()
Retrieves the day permalink structure with month and year.
Keeps date permalink structure with all year, month, and day.
Since
1.5.0 public
Returns
string|false False on failure. Year/Month/Day structure on success.
Definition at line 628 of file class-wp-rewrite.php.
References get_date_permastruct().
get_extra_permastruct ($name)
Retrieves an extra permalink structure by name.
Since
2.5.0 public
Parameters
string $name Permalink structure name.
Returns
string|false False if not found. Permalink structure string.
Definition at line 675 of file class-wp-rewrite.php.
References $name.
Referenced by get_category_permastruct(), and get_tag_permastruct().
get_feed_permastruct ()
Retrieves the feed permalink structure.
The permalink structure is root property, feed base, and finally '/feed'. Will set the feed_structure property and then return it without attempting to set the value again.
Since
1.5.0 public
Returns
string|false False if not found. Permalink structure string.
Definition at line 775 of file class-wp-rewrite.php.
References $feed_structure.
get_month_permastruct ()
Retrieves the month permalink structure without day and with year.
Gets the date permalink structure and strips out the day permalink structures. Keeps the year permalink structure.
Since
1.5.0 public
Returns
false|string False on failure. Year/Month structure on success.
Definition at line 606 of file class-wp-rewrite.php.
References get_date_permastruct(), and str_replace.
get_page_permastruct ()
Retrieves the page permalink structure.
The permalink structure is root property, and 'pagename'. Will set the page_structure property and then return it without attempting to set the value again.
Since
1.5.0 public
Returns
string|false False if not found. Permalink structure string.
Definition at line 749 of file class-wp-rewrite.php.
References $page_structure.
Referenced by page_rewrite_rules().
get_search_permastruct ()
Retrieves the search permalink structure.
The permalink structure is root property, search base, and finally '/search'. Will set the search_structure property and then return it without attempting to set the value again.
Since
1.5.0 public
Returns
string|false False if not found. Permalink structure string.
Definition at line 723 of file class-wp-rewrite.php.
References $search_structure.
Referenced by rewrite_rules().
get_tag_permastruct ()
Retrieve the permalink structure for tags.
If the tag_base property has no value, then the tag structure will have the front property value, followed by 'tag', and finally 'tag'. If it does, then the root property will be used, along with the tag_base property value.
Since
2.3.0 public
Returns
string|false False on failure. Tag permalink structure.
Definition at line 662 of file class-wp-rewrite.php.
References get_extra_permastruct().
get_year_permastruct ()
Retrieves the year permalink structure without month and day.
Gets the date permalink structure and strips out the month and day permalink structures.
Since
1.5.0 public
Returns
false|string False on failure. Year structure on success.
Definition at line 582 of file class-wp-rewrite.php.
References get_date_permastruct(), and str_replace.
iis7_url_rewrite_rules ($add_parent_tags = false)
Retrieves IIS7 URL Rewrite formatted rewrite rules to write to web.config file.
Does not actually write to the web.config file, but creates the rules for the process that will.
Since
2.8.0 public
Parameters
bool $add_parent_tags Optional. Whether to add parent tags to the rewrite rule sets. Default false.
Returns
string IIS7 URL rewrite rule sets.
Filter the list of rewrite rules formatted for output to a web.config.
Since
2.8.0
Parameters
string $rules Rewrite rules formatted for IIS web.config.
Definition at line 1581 of file class-wp-rewrite.php.
References apply_filters(), and using_permalinks().
init ()
Sets up the object's properties.
The 'use_verbose_page_rules' object property will be set to true if the permalink structure begins with one of the following: 'postname', 'category', 'tag', or 'author'.
Since
1.5.0 public
Definition at line 1840 of file class-wp-rewrite.php.
References get_option(), and using_index_permalinks().
Referenced by __construct(), set_category_base(), set_permalink_structure(), and set_tag_base().
mod_rewrite_rules ()
Retrieves mod_rewrite-formatted rewrite rules to write to .htaccess.
Does not actually write to the .htaccess file, but creates the rules for the process that will.
Will add the non_wp_rules property rules to the .htaccess file before the WordPress rewrite rules one.
Since
1.5.0 public
Returns
string
Filter the list of rewrite rules formatted for output to an .htaccess file.
Since
1.5.0
Parameters
string $rules mod_rewrite Rewrite rules formatted for .htaccess.
Filter the list of rewrite rules formatted for output to an .htaccess file.
Since
1.5.0
Parameters
string $rules mod_rewrite Rewrite rules formatted for .htaccess.
Definition at line 1494 of file class-wp-rewrite.php.
References apply_filters(), home_url(), rewrite_rules(), site_url(), str_replace, trailingslashit(), and using_permalinks().
page_rewrite_rules ()
Retrieves all of the rewrite rules for pages.
Since
1.5.0 public
Returns
array Page rewrite rules.
Definition at line 499 of file class-wp-rewrite.php.
References add_rewrite_tag(), EP_PAGES, generate_rewrite_rules(), and get_page_permastruct().
Referenced by rewrite_rules().
page_uri_index ()
Retrieves all page and attachments for pages URIs.
The attachments are for those that have pages as parents and will be retrieved.
Since
2.5.0 public
wpdb $wpdb WordPress database abstraction object.
Returns
array Array of page URIs as first element and attachment URIs as second element.
Definition at line 457 of file class-wp-rewrite.php.
References $attachments, $id, $post, $wpdb, get_page_hierarchy(), and get_page_uri().
preg_index ($number)
Indexes for matches for usage in preg_*() functions.
The format of the string is, with empty matches property value, '$NUM'. The 'NUM' will be replaced with the value in the $number parameter. With the matches property not empty, the value of the returned string will contain that value of the matches property. The format then will be '$MATCHES[NUM]', with MATCHES as the value in the property and NUM the value of the $number parameter.
Since
1.5.0 public
Parameters
int $number Index number.
Returns
string
Definition at line 432 of file class-wp-rewrite.php.
Referenced by generate_rewrite_rules().
remove_permastruct ($name)
Removes a permalink structure.
Since
4.5.0 public
Parameters
string $name Name for permalink structure.
Definition at line 1777 of file class-wp-rewrite.php.
References $name.
remove_rewrite_tag ($tag)
Removes an existing rewrite tag.
Since
4.5.0 public
See also
WP_Rewrite::$rewritecode
WP_Rewrite::$rewritereplace
WP_Rewrite::$queryreplace
Parameters
string $tag Name of the rewrite tag to remove.
Definition at line 857 of file class-wp-rewrite.php.
References null.
rewrite_rules ()
Constructs rewrite matches and queries from permalink structure.
Runs the action 'generate_rewrite_rules' with the parameter that is an reference to the current WP_Rewrite instance to further manipulate the permalink structures and rewrite rules. Runs the 'rewrite_rules_array' filter on the full rewrite rule array.
There are two ways to manipulate the rewrite rules, one by hooking into the 'generate_rewrite_rules' action and gaining full control of the object or just manipulating the rewrite rule array before it is passed from the function.
Since
1.5.0 public
Returns
array An associate array of matches and queries.
Filter rewrite rules used for "post" archives.
Since
1.5.0
Parameters
array $post_rewrite The rewrite rules for posts.
Filter rewrite rules used for date archives.
Likely date archives would include /yyyy/, /yyyy/mm/, and /yyyy/mm/dd/.
Since
1.5.0
Parameters
array $date_rewrite The rewrite rules for date archives.
Filter rewrite rules used for root-level archives.
Likely root-level archives would include pagination rules for the homepage as well as site-wide post feeds (e.g. /feed/, and /feed/atom/).
Since
1.5.0
Parameters
array $root_rewrite The root-level rewrite rules.
Filter rewrite rules used for comment feed archives.
Likely comments feed archives include /comments/feed/, and /comments/feed/atom/.
Since
1.5.0
Parameters
array $comments_rewrite The rewrite rules for the site-wide comments feeds.
Filter rewrite rules used for search archives.
Likely search-related archives include /search/search+query/ as well as pagination and feed paths for a search.
Since
1.5.0
Parameters
array $search_rewrite The rewrite rules for search queries.
Filter rewrite rules used for author archives.
Likely author archives would include /author/author-name/, as well as pagination and feed paths for author archives.
Since
1.5.0
Parameters
array $author_rewrite The rewrite rules for author archives.
Filter rewrite rules used for "page" post type archives.
Since
1.5.0
Parameters
array $page_rewrite The rewrite rules for the "page" post type.
Filter rewrite rules used for individual permastructs.
The dynamic portion of the hook name, $permastructname, refers to the name of the registered permastruct, e.g. 'post_tag' (tags), 'category' (categories), etc.
Since
3.1.0
Parameters
array $rules The rewrite rules generated for the current permastruct.
Filter rewrite rules used specifically for Tags.
Since
2.3.0
Parameters
array $rules The rewrite rules generated for tags.
Fires after the rewrite rules are generated.
Since
1.5.0
Parameters
WP_Rewrite $this Current WP_Rewrite instance, passed by reference.
Filter the full set of generated rewrite rules.
Since
1.5.0
Parameters
array $this-,>rules The compiled array of rewrite rules.
Definition at line 1266 of file class-wp-rewrite.php.
References $home_path, $rules, apply_filters(), do_action_ref_array(), EP_AUTHORS, EP_COMMENTS, EP_DATE, EP_PERMALINK, EP_ROOT, EP_SEARCH, generate_rewrite_rules(), get_author_permastruct(), get_date_permastruct(), get_search_permastruct(), home_url(), is_main_site(), is_multisite(), and page_rewrite_rules().
Referenced by mod_rewrite_rules(), and wp_rewrite_rules().
set_category_base ($category_base)
Sets the category base for the category permalink.
Will update the 'category_base' option, if there is a difference between the current category base and the parameter value. Calls WP_Rewrite::init() after the option is updated.
Since
1.5.0 public
Parameters
string $category_base Category permalink structure base.
Definition at line 1910 of file class-wp-rewrite.php.
References $category_base, get_option(), init(), and update_option().
set_permalink_structure ($permalink_structure)
Sets the main permalink structure for the site.
Will update the 'permalink_structure' option, if there is a difference between the current permalink structure and the parameter value. Calls WP_Rewrite::init() after the option is updated.
Fires the 'permalink_structure_changed' action once the init call has processed passing the old and new values
Since
1.5.0 public
Parameters
string $permalink_structure Permalink structure.
Fires after the permalink structure is updated.
Since
2.8.0
Parameters
string $old_permalink_structure The previous permalink structure.
string $permalink_structure The new permalink structure.
Definition at line 1879 of file class-wp-rewrite.php.
References $permalink_structure, do_action(), init(), and update_option().
set_tag_base ($tag_base)
Sets the tag base for the tag permalink.
Will update the 'tag_base' option, if there is a difference between the current tag base and the parameter value. Calls WP_Rewrite::init() after the option is updated.
Since
2.3.0 public
Parameters
string $tag_base Tag permalink structure base.
Definition at line 1929 of file class-wp-rewrite.php.
References $tag_base, get_option(), init(), and update_option().
using_index_permalinks ()
Determines whether permalinks are being used and rewrite module is not enabled.
Means that permalink links are enabled and index.php is in the URL.
Since
1.5.0 public
Returns
bool Whether permalink links are enabled and index.php is in the URL.
Definition at line 393 of file class-wp-rewrite.php.
Referenced by init(), and using_mod_rewrite_permalinks().
using_mod_rewrite_permalinks ()
Determines whether permalinks are being used and rewrite module is enabled.
Using permalinks and index.php is not in the URL.
Since
1.5.0 public
Returns
bool Whether permalink links are enabled and index.php is NOT in the URL.
Definition at line 412 of file class-wp-rewrite.php.
References using_index_permalinks(), and using_permalinks().
using_permalinks ()
Determines whether permalinks are being used.
This can be either rewrite module or permalink in the HTTP query string.
Since
1.5.0 public
Returns
bool True, if permalinks are enabled.
Definition at line 379 of file class-wp-rewrite.php.
Referenced by iis7_url_rewrite_rules(), mod_rewrite_rules(), and using_mod_rewrite_permalinks().
wp_rewrite_rules ()
Retrieves the rewrite rules.
The difference between this method and WP_Rewrite::rewrite_rules() is that this method stores the rewrite rules in the 'rewrite_rules' option and retrieves it. This prevents having to process all of the permalinks to get the rewrite rules in the form of caching.
Since
1.5.0 public
Returns
array Rewrite rules.
Definition at line 1469 of file class-wp-rewrite.php.
References $rules, get_option(), rewrite_rules(), and update_option().
Referenced by flush_rules().
Field Documentation
$author_base = 'author'
Definition at line 49 of file class-wp-rewrite.php.
$author_structure
Definition at line 58 of file class-wp-rewrite.php.
Referenced by get_author_permastruct().
$comment_feed_structure
Definition at line 138 of file class-wp-rewrite.php.
Referenced by get_comment_feed_permastruct().
$comments_base = 'comments'
Definition at line 103 of file class-wp-rewrite.php.
$comments_pagination_base = 'comment-page'
Definition at line 120 of file class-wp-rewrite.php.
$date_structure
Definition at line 67 of file class-wp-rewrite.php.
Referenced by get_date_permastruct().
$endpoints
Definition at line 257 of file class-wp-rewrite.php.
$extra_permastructs = array()
Definition at line 248 of file class-wp-rewrite.php.
$extra_rules = array()
Definition at line 216 of file class-wp-rewrite.php.
$extra_rules_top = array()
Definition at line 227 of file class-wp-rewrite.php.
$feed_base = 'feed'
Definition at line 129 of file class-wp-rewrite.php.
$feed_structure
Definition at line 147 of file class-wp-rewrite.php.
Referenced by get_feed_permastruct().
$feeds = array('feed', 'rdf', 'rss', 'rss2', 'atom')
Definition at line 367 of file class-wp-rewrite.php.
$front
Definition at line 162 of file class-wp-rewrite.php.
Referenced by add_rule(), generate_rewrite_rules(), and get_date_permastruct().
$index = 'index.php'
Definition at line 187 of file class-wp-rewrite.php.
Referenced by add_rule(), and generate_rewrite_rules().
$matches = ''
Definition at line 196 of file class-wp-rewrite.php.
$non_wp_rules = array()
Definition at line 239 of file class-wp-rewrite.php.
$page_structure
Definition at line 76 of file class-wp-rewrite.php.
Referenced by get_page_permastruct().
$pagination_base = 'page'
Definition at line 111 of file class-wp-rewrite.php.
$permalink_structure
Definition at line 32 of file class-wp-rewrite.php.
Referenced by generate_rewrite_rule(), generate_rewrite_rules(), and set_permalink_structure().
$queryreplace
Initial value:
= array(
        'year=',
        'monthnum=',
        'day=',
        'hour=',
        'minute=',
        'second=',
        'name=',
        'p=',
        'author_name=',
        'pagename=',
        's='
    )
Definition at line 347 of file class-wp-rewrite.php.
$rewritecode
Initial value:
= array(
        '%year%',
        '%monthnum%',
        '%day%',
        '%hour%',
        '%minute%',
        '%second%',
        '%postname%',
        '%post_id%',
        '%author%',
        '%pagename%',
        '%search%'
    )
Definition at line 304 of file class-wp-rewrite.php.
$rewritereplace
Initial value:
= array(
        '([0-9]{4})',
        '([0-9]{1,2})',
        '([0-9]{1,2})',
        '([0-9]{1,2})',
        '([0-9]{1,2})',
        '([0-9]{1,2})',
        '([^/]+)',
        '([0-9]+)',
        '([^/]+)',
        '([^/]+?)',
        '(.+)'
    )
Definition at line 326 of file class-wp-rewrite.php.
$root = ''
Definition at line 178 of file class-wp-rewrite.php.
$rules
Definition at line 205 of file class-wp-rewrite.php.
Referenced by rewrite_rules(), and wp_rewrite_rules().
$search_base = 'search'
Definition at line 85 of file class-wp-rewrite.php.
$search_structure
Definition at line 94 of file class-wp-rewrite.php.
Referenced by get_search_permastruct().
$use_trailing_slashes
Definition at line 40 of file class-wp-rewrite.php.
$use_verbose_page_rules = true
Definition at line 289 of file class-wp-rewrite.php.
$use_verbose_rules = false
Definition at line 271 of file class-wp-rewrite.php.
The documentation for this class was generated from the following file:
class-wp-rewrite.php