GravityView: Plugin_Upgrader_Skin Class Reference
Plugin_Upgrader_Skin Class Reference
Public Member Functions
__construct ($args=array())
after ()
public
Public Member Functions inherited from WP_Upgrader_Skin
__construct ($args=array())
add_strings ()
public
after ()
public
before ()
public
bulk_footer ()
public
bulk_header ()
public
error ($errors)
feedback ($string)
footer ()
public
header ()
public
request_filesystem_credentials ($error=false, $context=false, $allow_relaxed_file_ownership=false)
set_result ($result)
set_upgrader (&$upgrader)
Data Fields
$plugin = ''
$plugin_active = false
$plugin_network_active = false
Data Fields inherited from WP_Upgrader_Skin
$done_footer = false
$done_header = false
$options = array()
$result = false
$upgrader
Additional Inherited Members
Protected Member Functions inherited from WP_Upgrader_Skin
decrement_update_count ($type)
Output JavaScript that calls function to decrement the update counts.
Detailed Description
Definition at line 200 of file class-wp-upgrader-skins.php.
Constructor & Destructor Documentation
__construct ($args = array())
Parameters
array $args
Definition at line 209 of file class-wp-upgrader-skins.php.
References __, is_plugin_active(), is_plugin_active_for_network(), plugin, and wp_parse_args().
Member Function Documentation
after ()
public
Filter the list of action links available following a single plugin update.
Since
2.7.0
Parameters
array $update_actions Array of plugin action links.
string $plugin Path to the plugin file.
Definition at line 224 of file class-wp-upgrader-skins.php.
References __, apply_filters(), current_user_can(), WP_Upgrader_Skin\decrement_update_count(), esc_attr__(), WP_Upgrader_Skin\feedback(), is_wp_error(), plugin, self_admin_url(), and wp_nonce_url().
Field Documentation
$plugin = ''
Definition at line 201 of file class-wp-upgrader-skins.php.
$plugin_active = false
Definition at line 202 of file class-wp-upgrader-skins.php.
$plugin_network_active = false
Definition at line 203 of file class-wp-upgrader-skins.php.
The documentation for this class was generated from the following file:
class-wp-upgrader-skins.php