GravityView: GF_Entry Class Reference
GF_Entry Class Reference
If this file is called directly, abort.
Public Member Functions
offsetExists ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
offsetGet ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
offsetSet ($offset, $value)
ArrayAccess compatibility layer with a Gravity Forms entry array.
offsetUnset ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Public Member Functions inherited from Entry
as_entry ()
Return the backing entry object.
from_field ($field, $fallback=null)
If this is a Multi_Entry filter it by Field.
get_permalink (\GV\View $view=null, \GV\Request $request=null, $track_directory=true)
Return the link to this entry in the supplied context.
get_slug ($apply_filter=false, \GV\View $view=null, \GV\Request $request=null, $track_directory=true)
Get the entry slug.
is_multi ()
Is this a multi-entry (joined entry).
Static Public Member Functions
static by_id ($entry_id, $form_id=0)
Construct a instance by ID.
static by_slug ($entry_slug, $form_id=0)
Construct a instance by slug name.
static from_entry ($entry)
Construct a instance from a Gravity Forms entry array.
Static Public Member Functions inherited from Entry
static add_rewrite_endpoint ()
Adds the necessary rewrites for single Entries.
static by_id ($entry_id)
Construct a instance by ID.
static get_endpoint_name ()
Return the endpoint name for a single Entry.
Static Public Attributes
static $backend = 'gravityforms'
Static Public Attributes inherited from Entry
static $backend = null
Private Member Functions
__construct ()
Initialization.
Additional Inherited Members
Data Fields inherited from Entry
$ID = null
Protected Attributes inherited from Entry
$entry
Detailed Description
If this file is called directly, abort.
The Gravity Forms Entry class implementation.
Accessible as an array for back-compatibility.
Definition at line 14 of file class-gv-entry-gravityforms.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Initialization.
Definition at line 26 of file class-gv-entry-gravityforms.php.
References gravityview().
Member Function Documentation
by_id()
static by_id ($entry_id, $form_id = 0) static
Construct a instance by ID.
Parameters
int | string $entry_id The internal entry ID.
int $form_id The form ID, since slugs can be non-unique. Default: 0.
Since
2.0
Returns
|null An instance of this entry or null if not found.
Always try to grab by numeric ID first.
Hmm, slugs? Must be.
Definition at line 42 of file class-gv-entry-gravityforms.php.
References $entry, and $form_id.
Referenced by gventry\callback(), gvfield\callback(), Views_Route\get_sub_item(), Views_Route\get_sub_item_permissions_check(), GV\Mocks\GravityView_API_field_label(), and GV\Mocks\GravityView_API_field_value().
by_slug()
static by_slug ($entry_slug, $form_id = 0) static
Construct a instance by slug name.
Parameters
int | string $entry_slug The registered slug for the entry.
int $form_id The form ID, since slugs can be non-unique. Default: 0.
Since
2.0
Returns
|null An instance of this entry or null if not found.
Definition at line 72 of file class-gv-entry-gravityforms.php.
References $entry_slug, and $form_id.
from_entry()
static from_entry ($entry) static
Construct a instance from a Gravity Forms entry array.
Parameters
array $entry The entry array
Returns
|null An instance of this entry or null if not found.
Definition at line 108 of file class-gv-entry-gravityforms.php.
References $entry.
Referenced by GravityView_Field_Notes\get_add_note_part(), GravityView_Delete_Entry\get_delete_link(), GravityView_Field_FileUpload\get_files_array(), and GravityView_Field_Sequence\replace_merge_tag().
offsetExists()
offsetExists ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Definition at line 130 of file class-gv-entry-gravityforms.php.
offsetGet()
offsetGet ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Maps the old keys to the new data;
Definition at line 145 of file class-gv-entry-gravityforms.php.
offsetSet()
offsetSet ($offset, $value)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Definition at line 158 of file class-gv-entry-gravityforms.php.
References gravityview().
offsetUnset()
offsetUnset ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Definition at line 170 of file class-gv-entry-gravityforms.php.
References gravityview().
Field Documentation
$backend
$backend = 'gravityforms' static
Definition at line 21 of file class-gv-entry-gravityforms.php.
The documentation for this class was generated from the following file:
class-gv-entry-gravityforms.php