GravityView: Views_Route Class Reference
Views_Route Class Reference
If this file is called directly, abort.
Public Member Functions
get_item ($request)
Get one view.
get_item_permissions_check ($request)
get_items ($request)
Get a collection of views.
get_items_permissions_check ($request)
get_sub_item ($request)
Get one entry from view.
get_sub_item_permissions_check ($request)
get_sub_items_permissions_check ($request)
prepare_entry_for_response ($view, $entry, \WP_REST_Request $request, $context, $class=null)
Prepare the item for the REST response.
prepare_view_for_response ($view_post, \WP_REST_Request $request)
Prepare the item for the REST response.
Public Member Functions inherited from Route
__call ($method, $args)
Fallback if subclass doesn't define routes.
create_item ($request)
Create one item from the collection.
create_item_permissions_check ($request)
Check if a given request has access to create items.
create_sub_item ($request)
Create one item from the collection.
delete_item ($request)
Delete one item from the collection.
delete_item_permissions_check ($request)
Check if a given request has access to delete a specific item.
delete_sub_item ($request)
Delete one item from the collection for sub items.
get_item ($request)
Get one item from the collection.
get_item_permissions_check ($request)
Check if a given request has access to get a specific item.
get_items ($request)
Get a collection of items.
get_items_permissions_check ($request)
Check if a given request has access to get items.
get_sub_item ($request)
Get one item from the collection.
get_sub_items ($request)
Get a collection of items.
prepare_item_for_response ($item, $request)
Prepare the item for the REST response.
register_routes ()
Register the routes for the objects of the controller.
update_item ($request)
Update one item from the collection.
update_item_permissions_check ($request)
Check if a given request has access to update a specific item.
update_sub_item ($request)
Update one item from the collection for sub items.
Protected Attributes
$route_name = 'views'
Route Name.
$sub_type = 'entries'
Protected Attributes inherited from Route
$route_name
$sub_type
Additional Inherited Members
Protected Member Functions inherited from Route
get_route_name ()
Get route name.
get_sub_type ()
Get sub_type.
not_implemented ()
Generic response for routes not yet implemented.
prepare_item_for_database ($request)
Prepare the item for create or update operation.
Detailed Description
If this file is called directly, abort.
Definition at line 18 of file class-gv-rest-views-route.php.
Member Function Documentation
get_item()
get_item ($request)
Get one view.
Callback for /v1/views/{id}/
Since
2.0
Parameters
\WP_REST_Request $request Full data about the request.
Returns
|
Definition at line 81 of file class-gv-rest-views-route.php.
References $url, $view_id, and Views_Route\prepare_view_for_response().
get_item_permissions_check()
get_item_permissions_check ($request)
Parameters
\WP_REST_Request $request
Returns
bool|
Runs Filter:
gravityview/view/output/rest Disable rest output. Final chance.
Parameters
[in,out] bool Enable or not.
\GV\View $view The view.
Definition at line 413 of file class-gv-rest-views-route.php.
References $url, $view_id, and View\by_id().
Referenced by Views_Route\get_sub_items_permissions_check(), and Views_Route\prepare_view_for_response().
get_items()
get_items ($request)
Get a collection of views.
Callback for GET /v1/views/
Parameters
\WP_REST_Request $request Full data about the request.
Returns
|
Definition at line 47 of file class-gv-rest-views-route.php.
References GVCommon\get_all_views(), and Views_Route\prepare_view_for_response().
get_items_permissions_check()
get_items_permissions_check ($request)
Definition at line 496 of file class-gv-rest-views-route.php.
Referenced by Views_Route\get_sub_item_permissions_check().
get_sub_item()
get_sub_item ($request)
Get one entry from view.
Callback for /v1/views/{id}/entries/{id}/
GVCommon::get_entry
Since
2.0
Parameters
\WP_REST_Request $request Full data about the request.
Returns
|
Definition at line 339 of file class-gv-rest-views-route.php.
References $entry, $format, $url, $view_id, GF_Entry\by_id(), View\by_id(), Utils\get(), and Views_Route\prepare_entry_for_response().
get_sub_item_permissions_check()
get_sub_item_permissions_check ($request)
Definition at line 457 of file class-gv-rest-views-route.php.
References $entry, $url, $view_id, GF_Entry\by_id(), View\by_id(), Entry\get_endpoint_name(), Views_Route\get_items_permissions_check(), GVCommon\has_cap(), GravityView_Entry_Approval_Status\is_approved(), and GravityView_Entry_Approval\meta_key.
get_sub_items_permissions_check()
get_sub_items_permissions_check ($request)
Definition at line 501 of file class-gv-rest-views-route.php.
References Views_Route\get_item_permissions_check().
prepare_entry_for_response()
prepare_entry_for_response ($view, $entry, \WP_REST_Request $request, $context, $class = null)
Prepare the item for the REST response.
Since
2.0
Parameters
\GV\View $view The view.
\GV\Entry $entry WordPress representation of the item.
\WP_REST_Request $request Request object.
string $context The context (directory, single)
string $class The value renderer. Default: null (raw value)
Since
2.1 Add value renderer override $class parameter.
Returns
mixed The data that is sent.
Runs Filter:
gravityview/rest/entry/fields Whitelist more entry fields that are output in regular REST requests.
Parameters
[in,out] array $allowed The allowed ones, default by_visible, by_position("context_*"), i.e. as set in the view.
\GV\View $view The view.
\GV\Entry $entry The entry.
\WP_REST_Request $request Request object.
string $context The context (directory, single)
Modify non-unique IDs (custom, id, etc.) to be unique and not gobbled up.
Runs Filter:
gravityview/api/field/key Filter the key name in the results for JSON output.
Parameters
[in,out] string $field_id The ID. Should be unique or keys will be gobbled up.
\GV\View $view The view.
\GV\Entry $entry The entry.
\WP_REST_Request $request Request object.
string $context The context (directory, single)
Custom fields (and perhaps some others) will require rendering as they don't contain an intrinsic value (for custom their value is stored in the view and requires a renderer). We force the CSV template to take over in such cases, it's good enough for most cases.
Definition at line 112 of file class-gv-rest-views-route.php.
References $class, $entries, $entry, $field, $field_id, $format, $output, $post, $url, $view_id, Internal_Field\by_id(), GF_Field\by_id(), View\by_id(), endswitch, View_Collection\from_post(), Utils\get(), and Route\get_sub_items().
Referenced by Views_Route\get_sub_item().
prepare_view_for_response()
prepare_view_for_response ($view_post, \WP_REST_Request $request)
Prepare the item for the REST response.
Since
2.0
Parameters
\WP_Post $view_post WordPress representation of the item.
\WP_REST_Request $request Request object.
Returns
mixed
Definition at line 364 of file class-gv-rest-views-route.php.
References View\from_post(), Views_Route\get_item_permissions_check(), and GVCommon\has_cap().
Referenced by Views_Route\get_item(), and Views_Route\get_items().
Field Documentation
$route_name
$route_name = 'views' protected
Route Name.
Since
2.0
protected
Definition at line 27 of file class-gv-rest-views-route.php.
$sub_type
$sub_type = 'entries' protected
Definition at line 36 of file class-gv-rest-views-route.php.
The documentation for this class was generated from the following file:
class-gv-rest-views-route.php