GravityView: getid3_lib Class Reference
getid3_lib Class Reference
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Static Public Member Functions
static array_max ($arraydata, $returnkey=false)
static array_merge_clobber ($array1, $array2)
static array_merge_noclobber ($array1, $array2)
static array_min ($arraydata, $returnkey=false)
static BigEndian2Bin ($byteword)
static BigEndian2Float ($byteword)
static BigEndian2Int ($byteword, $synchsafe=false, $signed=false)
static BigEndian2String ($number, $minbytes=1, $synchsafe=false, $signed=false)
static Bin2Dec ($binstring, $signed=false)
static Bin2String ($binstring)
static CastAsInt ($floatnum)
static CopyFileParts ($filename_source, $filename_dest, $offset, $length)
static CopyTagsToComments (&$ThisFileInfo)
static CreateDeepArray ($ArrayPath, $Separator, $Value)
static DateMac2Unix ($macdate)
static Dec2Bin ($number)
static DecimalBinary2Float ($binarynumerator)
static DecimalizeFraction ($fraction)
static EmbeddedLookup ($key, $begin, $end, $file, $name)
static fileextension ($filename, $numextensions=1)
static FixedPoint16_16 ($rawdata)
static FixedPoint2_30 ($rawdata)
static FixedPoint8_8 ($rawdata)
static Float2BinaryDecimal ($floatvalue)
static Float2String ($floatvalue, $bits)
static GetDataImageSize ($imgData, &$imageinfo=array())
static getFileSizeSyscall ($path)
static hash_data ($file, $offset, $end, $algorithm)
static iconv_fallback ($in_charset, $out_charset, $string)
static iconv_fallback_int_utf8 ($charval)
static iconv_fallback_iso88591_utf16 ($string)
static iconv_fallback_iso88591_utf16be ($string, $bom=false)
static iconv_fallback_iso88591_utf16le ($string, $bom=false)
static iconv_fallback_iso88591_utf8 ($string, $bom=false)
static iconv_fallback_utf16_iso88591 ($string)
static iconv_fallback_utf16_utf8 ($string)
static iconv_fallback_utf16be_iso88591 ($string)
static iconv_fallback_utf16be_utf8 ($string)
static iconv_fallback_utf16le_iso88591 ($string)
static iconv_fallback_utf16le_utf8 ($string)
static iconv_fallback_utf8_iso88591 ($string)
static iconv_fallback_utf8_utf16 ($string)
static iconv_fallback_utf8_utf16be ($string, $bom=false)
static iconv_fallback_utf8_utf16le ($string, $bom=false)
static ImageExtFromMime ($mime_type)
static ImageTypesLookup ($imagetypeid)
static IncludeDependency ($filename, $sourcefile, $DieOnFailure=false)
static intValueSupported ($num)
static ksort_recursive (&$theArray)
static LittleEndian2Float ($byteword)
static LittleEndian2Int ($byteword, $signed=false)
static LittleEndian2String ($number, $minbytes=1, $synchsafe=false)
static mb_basename ($path, $suffix=null)
Workaround for Bug #37268 (https://bugs.php.net/bug.php?id=37268)
static MultiByteCharString2HTML ($string, $charset='ISO-8859-1')
static NormalizeBinaryPoint ($binarypointnumber, $maxbits=52)
static PlaytimeString ($seconds)
static PrintHexBytes ($string, $hex=true, $spaces=true, $htmlencoding='UTF-8')
static recursiveMultiByteCharString2HTML ($data, $charset='ISO-8859-1')
static RGADadjustmentLookup ($rawadjustment, $signbit)
static RGADamplitude2dB ($amplitude)
static RGADgainString ($namecode, $originatorcode, $replaygain)
static RGADnameLookup ($namecode)
static RGADoriginatorLookup ($originatorcode)
static safe_inc (&$variable, $increment=1)
static SimpleXMLelement2array ($XMLobject)
static trimNullByte ($string)
static trunc ($floatnumber)
static XML2array ($XMLstring)
Detailed Description
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Definition at line 15 of file getid3.lib.php.
Member Function Documentation
static array_max ($arraydata, $returnkey = false) static
Definition at line 493 of file getid3.lib.php.
References $value.
Referenced by getid3_mp3\getOnlyMPEGaudioInfoBruteForce().
static array_merge_clobber ($array1, $array2) static
Definition at line 384 of file getid3.lib.php.
static array_merge_noclobber ($array1, $array2) static
Definition at line 402 of file getid3.lib.php.
References elseif.
Referenced by getid3_id3v2\Analyze(), getid3_asf\Analyze(), and getid3_riff\Analyze().
static array_min ($arraydata, $returnkey = false) static
Definition at line 507 of file getid3.lib.php.
References $value.
static BigEndian2Bin ($byteword) static
Definition at line 297 of file getid3.lib.php.
References $i.
Referenced by getid3_ac3\Analyze(), getid3_dts\Analyze(), getid3_id3v2\ParseID3v2Frame(), and getid3_flac\parseSTREAMINFO().
static BigEndian2Float ($byteword) static
Definition at line 185 of file getid3.lib.php.
References elseif.
Referenced by getid3_riff\Analyze(), getid3_matroska\parseEBML(), getid3_id3v2\ParseID3v2Frame(), and AMFStream\readDouble().
static BigEndian2Int ($byteword, $synchsafe = false, $signed = false) static
Definition at line 263 of file getid3.lib.php.
References $i.
Referenced by getid3_ogg\Analyze(), getid3_id3v2\Analyze(), getid3_quicktime\Analyze(), getid3_riff\Analyze(), getid3_flv\Analyze(), getID3\analyze(), getid3_mp3\decodeMPEGaudioHeader(), getid3_matroska\EBML2Int(), getid3_riff\EitherEndian2Int(), AVCSequenceParameterSetReader\getBit(), getid3_matroska\HandleEMBLClusterBlock(), getid3_matroska\HandleEMBLSimpleTag(), getid3_mp3\MPEGaudioHeaderDecode(), getid3_flac\parseAPPLICATION(), getid3_flac\parseCUESHEET(), getid3_matroska\parseEBML(), getid3_id3v2\ParseID3v2Frame(), getid3_flac\parseMETAdata(), getid3_flac\parsePICTURE(), getid3_flac\parseSEEKTABLE(), getid3_flac\parseSTREAMINFO(), getid3_quicktime\QuicktimeParseAtom(), getid3_quicktime\QuicktimeParseContainerAtom(), getid3_quicktime\QuicktimeParseNikonNCTG(), and AMFStream\readByte().
static BigEndian2String ($number, $minbytes = 1, $synchsafe = false, $signed = false) static
Definition at line 307 of file getid3.lib.php.
static Bin2Dec ($binstring, $signed = false) static
Definition at line 342 of file getid3.lib.php.
References $i.
Referenced by getid3_riff\Analyze(), getid3_id3v2\ParseID3v2Frame(), and getid3_flac\parseSTREAMINFO().
static Bin2String ($binstring) static
Definition at line 358 of file getid3.lib.php.
References $i.
static CastAsInt ($floatnum) static
Definition at line 65 of file getid3.lib.php.
Referenced by getid3_id3v2\Analyze(), getid3_riff\Analyze(), getid3_flv\Analyze(), and getid3_mp3\getOnlyMPEGaudioInfo().
static CopyFileParts ($filename_source, $filename_dest, $offset, $length) static
Definition at line 634 of file getid3.lib.php.
References getID3\FREAD_BUFFER_SIZE.
static CopyTagsToComments (& $ThisFileInfo) static
Definition at line 1202 of file getid3.lib.php.
References $field, $value, elseif, and str_replace.
static CreateDeepArray ($ArrayPath, $Separator, $Value) static
Definition at line 477 of file getid3.lib.php.
static DateMac2Unix ($macdate) static
Definition at line 454 of file getid3.lib.php.
Referenced by getid3_riff\Analyze(), and getid3_quicktime\QuicktimeParseAtom().
static Dec2Bin ($number) static
Definition at line 328 of file getid3.lib.php.
References $i.
Referenced by getid3_riff\Analyze(), and getid3_id3v2\ParseID3v2Frame().
static DecimalBinary2Float ($binarynumerator) static
Definition at line 102 of file getid3.lib.php.
static DecimalizeFraction ($fraction) static
Definition at line 96 of file getid3.lib.php.
static EmbeddedLookup ($key, $begin, $end, $file, $name) static
Definition at line 1274 of file getid3.lib.php.
References $file, $i, and $name.
Referenced by getid3_riff\fourccLookup(), getid3_id3v2\FrameNameLongLookup(), getid3_id3v2\FrameNameShortLookup(), getid3_id3v2\LanguageLookup(), getid3_id3v2\LookupCurrencyCountry(), getid3_id3v2\LookupCurrencyUnits(), getid3_riff\waveSNDMtagLookup(), and getid3_riff\wFormatTagLookup().
static fileextension ($filename, $numextensions = 1) static
Definition at line 428 of file getid3.lib.php.
References $i.
static FixedPoint16_16 ($rawdata) static
Definition at line 466 of file getid3.lib.php.
Referenced by getid3_riff\Analyze(), and getid3_quicktime\QuicktimeParseAtom().
static FixedPoint2_30 ($rawdata) static
Definition at line 471 of file getid3.lib.php.
Referenced by getid3_quicktime\QuicktimeParseAtom().
static FixedPoint8_8 ($rawdata) static
Definition at line 461 of file getid3.lib.php.
Referenced by getid3_quicktime\QuicktimeParseAtom().
static Float2BinaryDecimal ($floatvalue) static
Definition at line 133 of file getid3.lib.php.
static Float2String ($floatvalue, $bits) static
Definition at line 149 of file getid3.lib.php.
static GetDataImageSize ($imgData, & $imageinfo = array()) static
Definition at line 1153 of file getid3.lib.php.
Referenced by getid3_apetag\Analyze(), getid3_asf\ASF_WMpicture(), getid3_id3v2\ParseID3v2Frame(), and getid3_ogg\ParseVorbisComments().
static getFileSizeSyscall ($path) static
Definition at line 1344 of file getid3.lib.php.
References $file, $output, and $path.
Referenced by getID3\openfile().
static hash_data ($file, $offset, $end, $algorithm) static
Definition at line 548 of file getid3.lib.php.
References $file, $size, and str_replace.
Referenced by getID3\getHashdata().
static iconv_fallback ($in_charset, $out_charset, $string) static
Definition at line 943 of file getid3.lib.php.
Referenced by getID3\CharConvert(), getid3_id3v2\ParseID3v2Frame(), getid3_asf\TrimConvert(), and getid3_asf\WMpictureTypeLookup().
static iconv_fallback_int_utf8 ($charval) static
Definition at line 661 of file getid3.lib.php.
References elseif.
static iconv_fallback_iso88591_utf16 ($string) static
Definition at line 726 of file getid3.lib.php.
static iconv_fallback_iso88591_utf16be ($string, $bom = false) static
Definition at line 702 of file getid3.lib.php.
References $i.
static iconv_fallback_iso88591_utf16le ($string, $bom = false) static
Definition at line 714 of file getid3.lib.php.
References $i.
static iconv_fallback_iso88591_utf8 ($string, $bom = false) static
Definition at line 685 of file getid3.lib.php.
References $i.
Referenced by getid3_id3v2\ParseID3v2Frame().
static iconv_fallback_utf16_iso88591 ($string) static
Definition at line 922 of file getid3.lib.php.
References elseif.
static iconv_fallback_utf16_utf8 ($string) static
Definition at line 933 of file getid3.lib.php.
References elseif.
static iconv_fallback_utf16be_iso88591 ($string) static
Definition at line 894 of file getid3.lib.php.
References $i.
static iconv_fallback_utf16be_utf8 ($string) static
Definition at line 866 of file getid3.lib.php.
References $i.
static iconv_fallback_utf16le_iso88591 ($string) static
Definition at line 908 of file getid3.lib.php.
References $i.
static iconv_fallback_utf16le_utf8 ($string) static
Definition at line 880 of file getid3.lib.php.
References $i.
static iconv_fallback_utf8_iso88591 ($string) static
Definition at line 731 of file getid3.lib.php.
References elseif.
static iconv_fallback_utf8_utf16 ($string) static
Definition at line 861 of file getid3.lib.php.
static iconv_fallback_utf8_utf16be ($string, $bom = false) static
Definition at line 775 of file getid3.lib.php.
References elseif.
static iconv_fallback_utf8_utf16le ($string, $bom = false) static
Definition at line 818 of file getid3.lib.php.
References elseif.
static ImageExtFromMime ($mime_type) static
Definition at line 1176 of file getid3.lib.php.
References str_replace.
static ImageTypesLookup ($imagetypeid) static
Definition at line 1181 of file getid3.lib.php.
static IncludeDependency ($filename, $sourcefile, $DieOnFailure = false) static
Definition at line 1320 of file getid3.lib.php.
Referenced by getid3_lyrics3\Analyze(), getid3_riff\Analyze(), and getid3_matroska\Analyze().
static intValueSupported ($num) static
Definition at line 80 of file getid3.lib.php.
References null.
Referenced by getid3_id3v1\Analyze(), getid3_lyrics3\Analyze(), getid3_ogg\Analyze(), getid3_apetag\Analyze(), getid3_quicktime\Analyze(), getid3_handler\fread(), getid3_handler\fseek(), getid3_lyrics3\getLyrics3Data(), and getID3\openfile().
static ksort_recursive (& $theArray) static
Definition at line 418 of file getid3.lib.php.
References $value.
static LittleEndian2Float ($byteword) static
Definition at line 180 of file getid3.lib.php.
Referenced by getid3_riff\Analyze(), and getid3_mp3\decodeMPEGaudioHeader().
static LittleEndian2Int ($byteword, $signed = false) static
Definition at line 292 of file getid3.lib.php.
Referenced by getid3_ogg\Analyze(), getid3_apetag\Analyze(), getid3_ac3\Analyze(), getid3_asf\Analyze(), getid3_riff\Analyze(), getid3_flv\Analyze(), getid3_asf\ASF_WMpicture(), getid3_riff\EitherEndian2Int(), getid3_asf\HeaderExtensionObjectDataParse(), getid3_apetag\parseAPEheaderFooter(), getid3_ogg\ParseOggPageHeader(), getid3_ogg\ParseOpusPageHeader(), getid3_riff\ParseRIFF(), getid3_riff\ParseRIFFAMV(), getid3_ogg\ParseVorbisComments(), getid3_ogg\ParseVorbisPageHeader(), and getid3_riff\parseWavPackHeader().
static LittleEndian2String ($number, $minbytes = 1, $synchsafe = false) static
Definition at line 369 of file getid3.lib.php.
Referenced by getid3_riff\ParseRIFFdata().
static mb_basename ($path, $suffix = null) static
Workaround for Bug #37268 (https://bugs.php.net/bug.php?id=37268)
Parameters
string $path A path.
string $suffix If the name component ends in suffix this will also be cut off.
Returns
string
Definition at line 1375 of file getid3.lib.php.
References $path.
Referenced by getID3\openfile().
static MultiByteCharString2HTML ($string, $charset = 'ISO-8859-1') static
Definition at line 1005 of file getid3.lib.php.
References $charset, $i, and elseif.
static NormalizeBinaryPoint ($binarypointnumber, $maxbits = 52) static
Definition at line 109 of file getid3.lib.php.
References elseif, and str_replace.
static PlaytimeString ($seconds) static
Definition at line 444 of file getid3.lib.php.
Referenced by getID3\ChannelsBitratePlaytimeCalculations().
static PrintHexBytes ($string, $hex = true, $spaces = true, $htmlencoding = 'UTF-8') static
Definition at line 18 of file getid3.lib.php.
References $i.
Referenced by getid3_ac3\Analyze(), getid3_flac\Analyze(), getid3_riff\Analyze(), getid3_dts\Analyze(), getid3_flv\Analyze(), getid3_mp3\FreeFormatFrameLength(), getid3_riff\ParseRIFFAMV(), and getid3_quicktime\QuicktimeParseAtom().
static recursiveMultiByteCharString2HTML ($data, $charset = 'ISO-8859-1') static
Definition at line 991 of file getid3.lib.php.
References $charset, $value, and elseif.
Referenced by getID3\HandleAllTags().
static RGADadjustmentLookup ($rawadjustment, $signbit) static
Definition at line 1124 of file getid3.lib.php.
Referenced by getid3_riff\Analyze(), getid3_mp3\decodeMPEGaudioHeader(), and getid3_id3v2\ParseID3v2Frame().
static RGADamplitude2dB ($amplitude) static
Definition at line 1148 of file getid3.lib.php.
Referenced by getID3\CalculateReplayGain(), getid3_mp3\decodeMPEGaudioHeader(), and getid3_ac3\heavyCompression().
static RGADgainString ($namecode, $originatorcode, $replaygain) static
Definition at line 1133 of file getid3.lib.php.
static RGADnameLookup ($namecode) static
Definition at line 1099 of file getid3.lib.php.
Referenced by getid3_riff\Analyze(), getid3_mp3\decodeMPEGaudioHeader(), and getid3_id3v2\ParseID3v2Frame().
static RGADoriginatorLookup ($originatorcode) static
Definition at line 1111 of file getid3.lib.php.
Referenced by getid3_riff\Analyze(), getid3_mp3\decodeMPEGaudioHeader(), and getid3_id3v2\ParseID3v2Frame().
static safe_inc (& $variable, $increment = 1) static
Definition at line 56 of file getid3.lib.php.
Referenced by getid3_mp3\getOnlyMPEGaudioInfo(), getid3_mp3\getOnlyMPEGaudioInfoBruteForce(), and getid3_flac\parseSEEKTABLE().
static SimpleXMLelement2array ($XMLobject) static
Definition at line 534 of file getid3.lib.php.
References $value.
static trimNullByte ($string) static
Definition at line 1340 of file getid3.lib.php.
Referenced by getid3_matroska\parseEBML().
static trunc ($floatnumber) static
Definition at line 39 of file getid3.lib.php.
References elseif.
static XML2array ($XMLstring) static
Definition at line 521 of file getid3.lib.php.
Referenced by getid3_riff\Analyze().
The documentation for this class was generated from the following file:
getid3.lib.php