GravityView: GravityView_Admin_Metaboxes Class Reference
GravityView_Admin_Metaboxes Class Reference
Register and render the admin metaboxes for GravityView.
Public Member Functions
__construct ()
initialize ()
Add WordPress hooks.
register_metaboxes ()
render_data_source_metabox ($post)
Render html for 'select form' metabox.
render_select_template_metabox ($post)
Render html for 'select template' metabox.
render_shortcode_hint ()
Render shortcode hint in the Publish metabox.
render_view_configuration_metabox ($post)
Render html for 'View Configuration' metabox.
render_view_settings_metabox ($post)
Render html View General Settings.
settings_metabox_render ($post)
Render the View Settings metabox.
update_priority ()
GravityView wants to have the top (normal) metaboxes all to itself, so we move all plugin/theme metaboxes down to advanced
Static Public Member Functions
static render_merge_tags_scripts ($curr_form)
Generate the script tags necessary for the Gravity Forms Merge Tag picker to work.
Data Fields
$post_id = 0
Static Public Attributes
static $metaboxes_dir
Private Member Functions
add_settings_metabox_tabs ()
Add default tabs to the Settings metabox.
get_data_source_header ($post_id)
Generate the title for Data Source, which includes the Action Links once configured.
Detailed Description
Register and render the admin metaboxes for GravityView.
Definition at line 6 of file class-gravityview-admin-metaboxes.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 18 of file class-gravityview-admin-metaboxes.php.
References GRAVITYVIEW_DIR, initialize(), and GravityView_Compatibility\is_valid().
Member Function Documentation
add_settings_metabox_tabs()
add_settings_metabox_tabs () private
Add default tabs to the Settings metabox.
Since
1.8
Runs Filter:
gravityview/metaboxes/default Modify the default settings metabox tabs
Parameters
array $metaboxes
Since
1.8
Definition at line 123 of file class-gravityview-admin-metaboxes.php.
References GravityView_Metabox_Tabs\add().
Referenced by register_metaboxes().
get_data_source_header()
get_data_source_header ($post_id) private
Generate the title for Data Source, which includes the Action Links once configured.
Since
1.8
Parameters
int $post_id ID of the current post
Returns
string "Data Source", plus links if any
Definition at line 204 of file class-gravityview-admin-metaboxes.php.
References $current_form, GravityView_Admin_Views\get_connected_form_links(), and gravityview_get_form_id().
Referenced by register_metaboxes().
initialize()
initialize ()
Add WordPress hooks.
Since
1.7.2
Definition at line 36 of file class-gravityview-admin-metaboxes.php.
Referenced by __construct().
register_metaboxes()
register_metaboxes ()
Definition at line 68 of file class-gravityview-admin-metaboxes.php.
References $post, add_settings_metabox_tabs(), and get_data_source_header().
render_data_source_metabox()
render_data_source_metabox ($post)
Render html for 'select form' metabox.
Parameters
object $post
Returns
void
Definition at line 224 of file class-gravityview-admin-metaboxes.php.
render_merge_tags_scripts()
static render_merge_tags_scripts ($curr_form) static
Generate the script tags necessary for the Gravity Forms Merge Tag picker to work.
Parameters
int $curr_form Form ID
Returns
null|string Merge tags html; NULL if $curr_form isn't defined.
Definition at line 247 of file class-gravityview-admin-metaboxes.php.
References $curr_form, GV\$form, $output, and gravityview_get_form().
render_select_template_metabox()
render_select_template_metabox ($post)
Render html for 'select template' metabox.
Parameters
object $post
Returns
void
Definition at line 236 of file class-gravityview-admin-metaboxes.php.
render_shortcode_hint()
render_shortcode_hint ()
Render shortcode hint in the Publish metabox.
public
Returns
void
Definition at line 324 of file class-gravityview-admin-metaboxes.php.
References $post, gravityview(), gravityview_get_directory_fields(), and gravityview_get_directory_widgets().
render_view_configuration_metabox()
render_view_configuration_metabox ($post)
Render html for 'View Configuration' metabox.
public
Parameters
mixed $post
Returns
void
Definition at line 282 of file class-gravityview-admin-metaboxes.php.
References $curr_form, $post, View\from_post(), gravityview_get_form_id(), and gravityview_get_template_id().
render_view_settings_metabox()
render_view_settings_metabox ($post)
Render html View General Settings.
public
Parameters
object $post
Returns
void
Definition at line 307 of file class-gravityview-admin-metaboxes.php.
References $current_settings, $post, and gravityview_get_template_settings().
settings_metabox_render()
settings_metabox_render ($post)
Render the View Settings metabox.
Since
1.8
Parameters
WP_Post $post
Runs Actions:
gravityview/metaboxes/before_render Before rendering GravityView metaboxes
Since
1.8
Parameters
WP_Post $post
Runs Actions:
gravityview/metaboxes/after_render After rendering GravityView metaboxes
Since
1.8
Parameters
WP_Post $post
Definition at line 97 of file class-gravityview-admin-metaboxes.php.
References $post, and GravityView_Metabox_Tabs\get_all().
update_priority()
update_priority ()
GravityView wants to have the top (normal) metaboxes all to itself, so we move all plugin/theme metaboxes down to advanced
Since
1.15.2
Definition at line 51 of file class-gravityview-admin-metaboxes.php.
Field Documentation
$metaboxes_dir
$metaboxes_dir static
Definition at line 8 of file class-gravityview-admin-metaboxes.php.
$post_id
$post_id = 0
Definition at line 13 of file class-gravityview-admin-metaboxes.php.
The documentation for this class was generated from the following file:
class-gravityview-admin-metaboxes.php