GravityView: GravityView_Field_Date_Created Class Reference
GravityView_Field_Date_Created Class Reference
Public Member Functions
__construct ()
GravityView_Field_Date_Created constructor.
field_options ($field_options, $template_id, $field_id, $context, $input_type)
get_content ($output='', $entry=array(), $field_settings=array(), $field=array())
Filter the value of the field.
replace_merge_tag ($matches=array(), $text='', $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Add {date_created} merge tag and format the values using format_date.
Public Member Functions inherited from GravityView_Field
__construct ()
GravityView_Field constructor.
_filter_gform_custom_merge_tags ($custom_merge_tags=array(), $form_id, $fields=array(), $element_id='')
Add custom merge tags to merge tag options.
_filter_gform_replace_merge_tags ($text, $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Match the merge tag in replacement text for the field.
_filter_sortable_fields ($not_sortable)
Use field settings to modify whether a field is sortable.
add_entry_meta ($entry_meta)
Add the custom entry meta key to make it searchable and sortable.
add_field_support ($key='', &$field_options)
add_sortable_field ($fields)
Add the field to the Filter & Sort available fields.
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Tap in here to modify field options.
replace_merge_tag ($matches=array(), $text='', $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Run GravityView filters when using GFCommon::replace_variables()
set_default_search_label ($label='', $gf_field=null, $field=array())
Allow setting a default search label for search fields based on the field type.
Data Fields
$_custom_merge_tag = 'date_created'
$contexts = array('single', 'multiple', 'export')
$group = 'meta'
$is_searchable = true
$name = 'date_created'
$search_operators = array('less_than', 'greater_than', 'is', 'isnot')
Data Fields inherited from GravityView_Field
$_gf_field_class_name
$contexts = array('single', 'multiple', 'edit', 'export')
$default_search_label
$description
$entry_meta_is_default_column = false
$entry_meta_key = null
$entry_meta_update_callback = null
$group
standard, advanced, post, pricing, meta, gravityview
$is_numeric
boolean Is field content number-based?
$is_searchable = true
$is_sortable = true
boolean Can the field be sorted in search?
$label
$name
$search_operators
Additional Inherited Members
Protected Member Functions inherited from GravityView_Field
custom_merge_tags ($form=array(), $fields=array())
Add custom Merge Tags to Merge Tag options, if custom Merge Tags exist.
is_choice_value_enabled ()
Check whether the enableChoiceValue flag is set for a GF field.
Protected Attributes inherited from GravityView_Field
$_custom_merge_tag = false
$_field_id = ''
$_field_options = array()
Detailed Description
Definition at line 8 of file class-gravityview-field-date-created.php.
Constructor & Destructor Documentation
__construct()
__construct ()
GravityView_Field_Date_Created constructor.
Definition at line 25 of file class-gravityview-field-date-created.php.
References GravityView_Field\$label, and GV\description.
Member Function Documentation
field_options()
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Definition at line 36 of file class-gravityview-field-date-created.php.
References GravityView_Field\add_field_support().
get_content()
get_content ($output = '', $entry = array(), $field_settings = array(), $field = array())
Filter the value of the field.
Since
1.16
Parameters
string $output HTML value output
array $entry The GF entry array
array $field_settings Settings for the particular GV field
array $field Current field being displayed
Returns
String values for this field based on the numeric values used by Gravity Forms
Overridden by a template.
Definition at line 61 of file class-gravityview-field-date-created.php.
References $field, $field_settings, $output, GVCommon\format_date(), and GV\get().
Referenced by GravityView_Field_Payment_Date\get_value().
replace_merge_tag()
replace_merge_tag ($matches = array(), $text = '', $form = array(), $entry = array(), $url_encode = false, $esc_html = false)
Add {date_created} merge tag and format the values using format_date.
Since
1.16
See also
https://docs.gravityview.co/article/331-date-created-merge-tag for usage information
Parameters
array $matches Array of Merge Tag matches found in text by preg_match_all
string $text Text to replace
array $form Gravity Forms form array
array $entry Entry array
bool $url_encode Whether to URL-encode output
Returns
string Original text if {date_created} isn't found. Otherwise, replaced text.
Use $this->name instead of date_created because Payment Date uses this as well
Definition at line 84 of file class-gravityview-field-date-created.php.
References $entry, GravityView_Merge_Tags\format_date(), and Utils\get().
Field Documentation
$_custom_merge_tag
$_custom_merge_tag = 'date_created'
Definition at line 20 of file class-gravityview-field-date-created.php.
$contexts
$contexts = array('single', 'multiple', 'export')
Definition at line 18 of file class-gravityview-field-date-created.php.
$group
$group = 'meta'
Definition at line 16 of file class-gravityview-field-date-created.php.
$is_searchable
$is_searchable = true
Definition at line 12 of file class-gravityview-field-date-created.php.
$name
$name = 'date_created'
Definition at line 10 of file class-gravityview-field-date-created.php.
$search_operators
$search_operators = array('less_than', 'greater_than', 'is', 'isnot')
Definition at line 14 of file class-gravityview-field-date-created.php.
The documentation for this class was generated from the following file:
class-gravityview-field-date-created.php