GravityView: WP_Styles Class Reference
WP_Styles Class Reference
Public Member Functions
__construct ()
_css_href ($src, $ver, $handle)
add_inline_style ($handle, $code)
all_deps ($handles, $recursion=false, $group=false)
do_footer_items ()
do_item ($handle)
in_default_dir ($src)
print_inline_style ($handle, $echo=true)
reset ()
public
Public Member Functions inherited from WP_Dependencies
add ($handle, $src, $deps=array(), $ver=false, $args=null)
Register an item.
add_data ($handle, $key, $value)
Add extra item data.
all_deps ($handles, $recursion=false, $group=false)
Determine dependencies.
dequeue ($handles)
Dequeue an item or items.
do_item ($handle)
Process a dependency.
do_items ($handles=false, $group=false)
Process the items and dependencies.
enqueue ($handles)
Queue an item or items.
get_data ($handle, $key)
Get extra item data.
query ($handle, $list= 'registered')
Query list for an item.
remove ($handles)
Un-register an item or items.
set_group ($handle, $recursion, $group)
Set item group, unless already in a lower group.
Data Fields
$base_url
$concat = ''
$concat_version = ''
$content_url
$default_dirs
$default_version
$do_concat = false
$print_code = ''
$print_html = ''
$text_direction = 'ltr'
Data Fields inherited from WP_Dependencies
$args = array()
$done = array()
$group = 0
$groups = array()
$queue = array()
$registered = array()
$to_do = array()
Additional Inherited Members
Protected Member Functions inherited from WP_Dependencies
recurse_deps ($queue, $handle)
Recursively search the passed dependency tree for $handle.
Detailed Description
Definition at line 19 of file class.wp-styles.php.
Constructor & Destructor Documentation
__construct ()
Fires when the WP_Styles instance is initialized.
Since
2.6.0
Parameters
WP_Styles &$this WP_Styles instance, passed by reference.
Definition at line 31 of file class.wp-styles.php.
References do_action_ref_array().
Member Function Documentation
_css_href ($src, $ver, $handle)
Parameters
string $src
string $ver
string $handle
Returns
string
Filter an enqueued style's fully-qualified URL.
Since
2.6.0
Parameters
string $src The source URL of the enqueued style.
string $handle The style's registered handle.
Definition at line 204 of file class.wp-styles.php.
References add_query_arg(), apply_filters(), content_url(), and esc_url.
Referenced by do_item().
add_inline_style ($handle, $code)
Parameters
string $handle
string $code
Definition at line 139 of file class.wp-styles.php.
References WP_Dependencies\add_data(), and WP_Dependencies\get_data().
all_deps ($handles, $recursion = false, $group = false)
Parameters
mixed $handles
bool $recursion
mixed $group
Returns
bool
Filter the array of enqueued styles before processing for output.
Since
2.6.0
Parameters
array $to_do The list of enqueued styles about to be processed.
Definition at line 183 of file class.wp-styles.php.
References apply_filters().
do_footer_items ()
Returns
array
Definition at line 242 of file class.wp-styles.php.
References WP_Dependencies\$done, and WP_Dependencies\do_items().
do_item ($handle)
Parameters
string $handle
Returns
bool
Filter the HTML link tag of an enqueued style.
Since
2.6.0
4.3.0 Introduced the $href parameter.
Parameters
string $html The link tag for the enqueued style.
string $handle The style's registered handle.
string $href The stylesheet's source URL.
This filter is documented in wp-includes/class.wp-styles.php
Definition at line 46 of file class.wp-styles.php.
References $default_version, $href, $title, _css_href(), apply_filters(), esc_attr(), in_default_dir(), null, print_inline_style(), registered, and str_replace.
in_default_dir ($src)
Parameters
string $src
Returns
bool
Definition at line 228 of file class.wp-styles.php.
Referenced by do_item().
print_inline_style ($handle, $echo = true)
Parameters
string $handle
bool $echo
Returns
bool
Definition at line 159 of file class.wp-styles.php.
References $output, esc_attr(), and WP_Dependencies\get_data().
Referenced by do_item().
reset ()
public
Definition at line 250 of file class.wp-styles.php.
Field Documentation
$base_url
Definition at line 20 of file class.wp-styles.php.
$concat = ''
Definition at line 24 of file class.wp-styles.php.
$concat_version = ''
Definition at line 25 of file class.wp-styles.php.
$content_url
Definition at line 21 of file class.wp-styles.php.
$default_dirs
Definition at line 29 of file class.wp-styles.php.
$default_version
Definition at line 22 of file class.wp-styles.php.
Referenced by do_item().
$do_concat = false
Definition at line 26 of file class.wp-styles.php.
$print_code = ''
Definition at line 28 of file class.wp-styles.php.
$print_html = ''
Definition at line 27 of file class.wp-styles.php.
$text_direction = 'ltr'
Definition at line 23 of file class.wp-styles.php.
The documentation for this class was generated from the following file:
class.wp-styles.php