GravityView: Featured_Content Class Reference
Featured_Content Class Reference
Twenty Fourteen Featured Content.
Static Public Member Functions
static customize_register ($wp_customize)
Add settings to the Customizer.
static delete_post_tag ($tag_id)
Reset tag option when the saved tag is deleted.
static delete_transient ()
Delete featured content ids transient.
static enqueue_scripts ()
Enqueue the tag suggestion script.
static get_featured_post_ids ()
Get featured post IDs.
static get_featured_posts ()
Get featured posts.
static get_setting ($key= 'all')
Get featured content settings.
static get_sticky_posts ()
Return an array with IDs of posts maked as sticky.
static hide_featured_term ($terms, $taxonomies, $args)
Hide featured tag from displaying when global terms are queried from the front-end.
static hide_the_featured_term ($terms, $id, $taxonomy)
Hide featured tag from display when terms associated with a post object are queried from the front-end.
static init ()
Conditionally hook into WordPress.
static pre_get_posts ($query)
Exclude featured posts from the home page blog query.
static register_setting ()
Register custom setting on the Settings -> Reading screen.
static setup ()
Instantiate.
static validate_settings ($input)
Validate featured content settings.
static wp_loaded ()
Hide "featured" tag from the front-end.
Static Public Attributes
static $max_posts = 15
Detailed Description
Twenty Fourteen Featured Content.
This module allows you to define a subset of posts to be displayed in the theme's Featured Content area.
For maximum compatibility with different methods of posting users will designate a featured post tag to associate posts with. Since this tag now has special meaning beyond that of a normal tags, users will have the ability to hide it from the front-end of their site.
Definition at line 13 of file inc/featured-content.php.
Member Function Documentation
static customize_register ($wp_customize) static
Add settings to the Customizer.
public
Since
Twenty Fourteen 1.0
Parameters
WP_Customize_Manager $wp_customize Customizer object.
Definition at line 401 of file inc/featured-content.php.
References $wp_customize, __, _x, add_query_arg(), admin_url(), and esc_url.
static delete_post_tag ($tag_id) static
Reset tag option when the saved tag is deleted.
It's important to mention that the transient needs to be deleted, too. While it may not be obvious by looking at the function alone, the transient is deleted by Featured_Content::validate_settings().
Hooks in the "delete_post_tag" action.
See also
Featured_Content::validate_settings().
public
Since
Twenty Fourteen 1.0
Parameters
int $tag_id The term_id of the tag that has been deleted.
Definition at line 278 of file inc/featured-content.php.
References update_option().
static delete_transient () static
Delete featured content ids transient.
Hooks in the "save_post" action.
See also
Featured_Content::validate_settings().
public
Since
Twenty Fourteen 1.0
Definition at line 213 of file inc/featured-content.php.
static enqueue_scripts () static
Enqueue the tag suggestion script.
public
Since
Twenty Fourteen 1.0
Definition at line 445 of file inc/featured-content.php.
References get_template_directory_uri(), and wp_enqueue_script().
static get_featured_post_ids () static
Get featured post IDs.
This function will return the an array containing the post IDs of all featured posts.
Sets the "featured_content_ids" transient.
public
Since
Twenty Fourteen 1.0
Returns
array Array of post IDs.
Definition at line 153 of file inc/featured-content.php.
References get_posts(), get_term_by(), get_transient(), and set_transient().
static get_featured_posts () static
Get featured posts.
public
Since
Twenty Fourteen 1.0
Returns
array Array of featured posts.
Definition at line 123 of file inc/featured-content.php.
References $featured_posts, and get_posts().
static get_setting ($key = 'all') static
Get featured content settings.
Get all settings recognized by this module. This function will return all settings whether or not they have been stored in the database yet. This ensures that all keys are available at all times.
In the event that you only require one setting, you may pass its name as the first parameter to the function and only that value will be returned.
public
Since
Twenty Fourteen 1.0
Parameters
string $key The key of a recognized setting.
Returns
mixed Array of all settings by default. A single value if passed as first parameter.
Definition at line 468 of file inc/featured-content.php.
References $options, _x, get_option(), and wp_parse_args().
static get_sticky_posts () static
Return an array with IDs of posts maked as sticky.
public
Since
Twenty Fourteen 1.0
Returns
array Array of sticky posts.
Definition at line 198 of file inc/featured-content.php.
References get_option().
static hide_featured_term ($terms, $taxonomies, $args) static
Hide featured tag from displaying when global terms are queried from the front-end.
Hooks into the "get_terms" filter.
public
Since
Twenty Fourteen 1.0
Parameters
array $terms List of term objects. This is the return value of get_terms().
array $taxonomies An array of taxonomy slugs.
Returns
array A filtered array of terms.
Featured_Content::get_setting()
Definition at line 305 of file inc/featured-content.php.
References is_admin().
static hide_the_featured_term ($terms, $id, $taxonomy) static
Hide featured tag from display when terms associated with a post object are queried from the front-end.
Hooks into the "get_the_terms" filter.
public
Since
Twenty Fourteen 1.0
Parameters
array $terms A list of term objects. This is the return value of get_the_terms().
int $id The ID field for the post object that terms are associated with.
array $taxonomy An array of taxonomy slugs.
Returns
array Filtered array of terms.
Featured_Content::get_setting()
Definition at line 354 of file inc/featured-content.php.
References is_admin().
static init () static
Conditionally hook into WordPress.
Theme must declare that they support this module by adding add_theme_support('featured-content'); during after_setup_theme.
If no theme support is found there is no need to hook into WordPress. We'll just return early instead.
public
Since
Twenty Fourteen 1.0
Definition at line 58 of file inc/featured-content.php.
References absint(), add_action(), add_filter(), and get_theme_support().
static pre_get_posts ($query) static
Exclude featured posts from the home page blog query.
Filter the home page posts, and remove any featured post ID's from it. Hooked onto the 'pre_get_posts' action, this changes the parameters of the query before it gets any posts.
public
Since
Twenty Fourteen 1.0
Parameters
WP_Query $query WP_Query object.
Returns
WP_Query Possibly-modified WP_Query.
Definition at line 231 of file inc/featured-content.php.
References $featured, and get_option().
static register_setting () static
Register custom setting on the Settings -> Reading screen.
public
Since
Twenty Fourteen 1.0
Definition at line 388 of file inc/featured-content.php.
static setup () static
Instantiate.
All custom functionality will be hooked into the "init" action.
public
Since
Twenty Fourteen 1.0
Definition at line 41 of file inc/featured-content.php.
References add_action().
static validate_settings ($input) static
Validate featured content settings.
Make sure that all user supplied content is in an expected format before saving to the database. This function will also delete the transient set in Featured_Content::get_featured_content().
public
Since
Twenty Fourteen 1.0
Parameters
array $input Array of settings input.
Returns
array Validated settings output.
Definition at line 501 of file inc/featured-content.php.
References $output, delete_transient(), get_term_by(), is_wp_error(), and wp_create_tag().
static wp_loaded () static
Hide "featured" tag from the front-end.
Has to run on wp_loaded so that the preview filters of the Customizer have a chance to alter the value.
public
Since
Twenty Fourteen 1.0
Definition at line 107 of file inc/featured-content.php.
References add_filter().
Field Documentation
$max_posts = 15 static
Definition at line 30 of file inc/featured-content.php.
The documentation for this class was generated from the following file:
inc/featured-content.php