GravityView: Client Class Reference
Client Class Reference
The TrustedLogin all-in-one drop-in class.
Public Member Functions
__construct (Config $config, $init=true)
TrustedLogin constructor.
add_meta_to_envelope ($metadata=array())
Adds PLAINTEXT metadata to the envelope, including reference ID.
get_access_key ()
Returns the current access key (hashed license key or generated access key.
grant_access ()
This creates a TrustedLogin user ✨
init ()
Initialize all the things!
revoke_access ($identifier='')
Revoke access to a site.
Static Public Member Functions
static get_reference_id ()
Gets the reference ID passed to the $_REQUEST using reference_id or ref keys.
Data Fields
const VERSION = '1.2'
Static Public Attributes
static $valid_config
Private Member Functions
extend_access ($user_id)
Extends the access duration for an existing Support User.
should_init (Config $config)
Should the Client fully initialize?
Private Attributes
$admin
$ajax
$config
$cron
$endpoint
$logging
$remote
$site_access
$support_user
Detailed Description
The TrustedLogin all-in-one drop-in class.
Definition at line 37 of file Client.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, $init = true)
TrustedLogin constructor.
See also
https://docs.trustedlogin.com/ for more information
Parameters
Config $config
bool $init Whether to initialize everything on instantiation
Exceptions
Exception If initializing is prevented via constants or the configuration isn't valid, throws exception.
Returns
void If no errors, returns void. Otherwise, throws exceptions.
Definition at line 107 of file Client.php.
References Client\$config, Client\init(), Client\should_init(), and Config\validate().
Member Function Documentation
add_meta_to_envelope()
add_meta_to_envelope ($metadata = array())
Adds PLAINTEXT metadata to the envelope, including reference ID.
Since
1.0.0
Parameters
array $metadata
Returns
array Array of metadata that will be sent with the Envelope.
Definition at line 541 of file Client.php.
extend_access()
extend_access ($user_id) private
Extends the access duration for an existing Support User.
Since
1.0.0
Parameters
int $user_id The existing Support User ID
Returns
array|WP_Error
Definition at line 365 of file Client.php.
Referenced by Client\grant_access().
get_access_key()
get_access_key ()
Returns the current access key (hashed license key or generated access key.
See also
SiteAccess::get_access_key()
Returns
string|null|WP_Error
Definition at line 193 of file Client.php.
get_reference_id()
static get_reference_id () static
Gets the reference ID passed to the $_REQUEST using reference_id or ref keys.
Since
1.0.0
Returns
string|null Sanitized reference ID (escaped with esc_html) if exists. NULL if not.
Definition at line 559 of file Client.php.
Referenced by Admin\generate_button(), Admin\get_footer_html(), Admin\get_reference_html(), and Admin\translations().
grant_access()
grant_access ()
This creates a TrustedLogin user ✨
Returns
array|WP_Error
Definition at line 207 of file Client.php.
References Client\extend_access(), and Encryption\get_random_hash().
init()
init ()
Initialize all the things!
Definition at line 178 of file Client.php.
Referenced by Client\__construct().
revoke_access()
revoke_access ($identifier = '')
Revoke access to a site.
Parameters
string $identifier Unique ID or "all"
Returns
bool|WP_Error True: Synced to SaaS and user(s) deleted. False: empty identifier. WP_Error: failed to revoke site in SaaS or failed to delete user.
Site was removed in SaaS, user was deleted.
Definition at line 466 of file Client.php.
References $user.
should_init()
should_init (Config $config) private
Should the Client fully initialize?
Parameters
Config $config
Returns
bool
Definition at line 152 of file Client.php.
References Config\ns().
Referenced by Client\__construct().
Field Documentation
$admin
Admin $admin private
Definition at line 83 of file Client.php.
$ajax
$ajax private
Definition at line 88 of file Client.php.
$config
$config private
Definition at line 48 of file Client.php.
Referenced by Client\__construct().
$cron
Cron $cron private
Definition at line 73 of file Client.php.
$endpoint
Endpoint $endpoint private
Definition at line 78 of file Client.php.
$logging
null Logging $logging private
Definition at line 58 of file Client.php.
$remote
Remote $remote private
Definition at line 68 of file Client.php.
$site_access
SiteAccess $site_access private
Definition at line 93 of file Client.php.
$support_user
SupportUser $support_user private
Definition at line 63 of file Client.php.
$valid_config
$valid_config static
Definition at line 53 of file Client.php.
VERSION
const VERSION = '1.2'
Definition at line 43 of file Client.php.
Referenced by Envelope\get(), Admin\get_footer_html(), and Admin\register_assets().
The documentation for this class was generated from the following file:
Client.php