GravityView: RSSCache Class Reference
RSSCache Class Reference
Public Member Functions
__construct ($base= '', $age= '')
PHP5 constructor.
check_cache ($url)
debug ($debugmsg, $lvl=E_USER_NOTICE)
error ($errormsg, $lvl=E_USER_WARNING)
file_name ($url)
get ($url)
RSSCache ($base= '', $age= '')
PHP4 constructor.
serialize ($rss)
set ($url, $rss)
unserialize ($data)
Data Fields
$BASE_CACHE
$ERROR = ''
$MAX_AGE = 43200
Detailed Description
Definition at line 717 of file rss.php.
Constructor & Destructor Documentation
__construct ($base = '', $age = '')
PHP5 constructor.
Definition at line 725 of file rss.php.
References WP_CONTENT_DIR.
Member Function Documentation
check_cache ($url)
Definition at line 784 of file rss.php.
References $url, file_name(), and get_transient().
debug ($debugmsg, $lvl = E_USER_NOTICE)
Definition at line 838 of file rss.php.
References error().
Referenced by get().
error ($errormsg, $lvl = E_USER_WARNING)
Definition at line 825 of file rss.php.
Referenced by debug().
file_name ($url)
Definition at line 817 of file rss.php.
References $url.
Referenced by check_cache(), get(), and set().
get ($url)
Definition at line 763 of file rss.php.
References $url, debug(), file_name(), and get_transient().
RSSCache ($base = '', $age = '')
PHP4 constructor.
Definition at line 739 of file rss.php.
serialize ($rss)
Definition at line 800 of file rss.php.
set ($url, $rss)
Definition at line 749 of file rss.php.
References $url, file_name(), and set_transient().
unserialize ($data)
Definition at line 807 of file rss.php.
Field Documentation
$BASE_CACHE
Definition at line 718 of file rss.php.
$ERROR = ''
Definition at line 720 of file rss.php.
$MAX_AGE = 43200
Definition at line 719 of file rss.php.
The documentation for this class was generated from the following file:
rss.php