GravityView: WP_Admin_Bar Class Reference
WP_Admin_Bar Class Reference
Core class used to implement the Toolbar API.
Public Member Functions
__get ($name)
add_group ($args)
Add a group to a menu node.
add_menu ($node)
add_menus ()
public
add_node ($args)
Add a node to the menu.
get_node ($id)
Gets a node.
get_nodes ()
initialize ()
public
recursive_render ($id, $node)
remove_menu ($id)
remove_node ($id)
Remove a node.
render ()
public
Data Fields
$user
Protected Member Functions
_bind ()
_get_node ($id)
_get_nodes ()
_render ($root)
bool $is_IE
_render_container ($node)
_render_group ($node)
_render_item ($node)
_set_node ($args)
_unset_node ($id)
Private Attributes
$bound = false
$nodes = array()
Detailed Description
Core class used to implement the Toolbar API.
Since
3.1.0
Definition at line 15 of file class-wp-admin-bar.php.
Member Function Documentation
__get ($name)
Parameters
string $name
Returns
string|array|void
Definition at line 24 of file class-wp-admin-bar.php.
References $name, _deprecated_argument(), and is_ssl().
_bind () final protected
Returns
object|void
Definition at line 270 of file class-wp-admin-bar.php.
References $default, _get_node(), _get_nodes(), _set_node(), add_node(), elseif, and remove_node().
Referenced by render().
_get_node ($id) final protected
Parameters
string $id
Returns
object|void
Definition at line 188 of file class-wp-admin-bar.php.
References $id.
Referenced by _bind(), and get_node().
_get_nodes () final protected
Returns
array|void
Definition at line 215 of file class-wp-admin-bar.php.
References $nodes.
Referenced by _bind(), and get_nodes().
_render ($root) final protected
bool $is_IE
Parameters
object $root
Definition at line 396 of file class-wp-admin-bar.php.
References $_SERVER, $class, $is_IE, _e, _render_group(), elseif, endif, is_admin(), label, role, and wp_is_mobile().
Referenced by render().
_render_container ($node) final protected
Parameters
object $node
Definition at line 434 of file class-wp-admin-bar.php.
References _render_group().
Referenced by _render_group().
_render_group ($node) final protected
Parameters
object $node
Definition at line 448 of file class-wp-admin-bar.php.
References $class, _render_container(), _render_item(), and esc_attr().
Referenced by _render(), _render_container(), and _render_item().
_render_item ($node) final protected
Parameters
object $node
Definition at line 471 of file class-wp-admin-bar.php.
References _render_group(), endif, esc_attr(), if, and li.
Referenced by _render_group(), and recursive_render().
_set_node ($args) final protected
Parameters
array $args
Definition at line 169 of file class-wp-admin-bar.php.
References object.
Referenced by _bind(), and add_node().
_unset_node ($id) final protected
Parameters
string $id
Definition at line 254 of file class-wp-admin-bar.php.
References $id.
Referenced by remove_node().
add_group ($args) final
Add a group to a menu node.
Since
3.3.0
Parameters
array $args { Array of arguments for adding a group.
string $id ID of the item. string $parent Optional. ID of the parent node. Default 'root'. array $meta Meta data for the group including the following keys: 'class', 'onclick', 'target', and 'title'. }
Definition at line 236 of file class-wp-admin-bar.php.
References add_node().
add_menu ($node)
Parameters
array $node
Definition at line 87 of file class-wp-admin-bar.php.
References add_node().
add_menus ()
public
Fires after menus are added to the menu bar.
Since
3.1.0
Definition at line 567 of file class-wp-admin-bar.php.
References add_action(), do_action(), is_network_admin(), and is_user_admin().
add_node ($args)
Add a node to the menu.
Since
4.5.0 Added the ability to pass 'lang' and 'dir' meta data.
Parameters
array $args { Arguments for adding a node.
string $id ID of the item. string $title Title of the node. string $parent Optional. ID of the parent node. string $href Optional. Link for the item. bool $group Optional. Whether or not the node is a group. Default false. array $meta Meta data including the following keys: 'html', 'class', 'rel', 'lang', 'dir', 'onclick', 'target', 'title', 'tabindex'. Default empty. }
Definition at line 115 of file class-wp-admin-bar.php.
References __, _deprecated_argument(), _doing_it_wrong(), _set_node(), esc_attr(), get_node(), sanitize_title(), and wp_parse_args().
Referenced by _bind(), add_group(), and add_menu().
get_node ($id) final
Gets a node.
Parameters
string $id
Returns
object Node.
Definition at line 179 of file class-wp-admin-bar.php.
References $id, and _get_node().
Referenced by add_node().
get_nodes () final
Returns
array|void
Definition at line 202 of file class-wp-admin-bar.php.
References $nodes, and _get_nodes().
initialize ()
public
To remove the default padding styles from WordPress for the Toolbar, use the following code: add_theme_support('admin-bar', array('callback' => '__return_false'));
Fires after WP_Admin_Bar is initialized.
Since
3.1.0
Definition at line 38 of file class-wp-admin-bar.php.
References add_action(), current_theme_supports(), do_action(), get_active_blog_for_user(), get_blogs_of_user(), get_current_blog_id(), get_current_user_id(), get_home_url(), get_theme_support(), home_url(), is_multisite(), trailingslashit(), user_admin_url(), wp_enqueue_script(), and wp_enqueue_style().
recursive_render ($id, $node)
Parameters
string $id Unused.
object $node
Definition at line 559 of file class-wp-admin-bar.php.
References _deprecated_function(), and _render_item().
remove_menu ($id)
Parameters
string $id
Definition at line 94 of file class-wp-admin-bar.php.
References $id, and remove_node().
remove_node ($id)
Remove a node.
Parameters
string $id The ID of the item.
Definition at line 247 of file class-wp-admin-bar.php.
References $id, and _unset_node().
Referenced by _bind(), and remove_menu().
render ()
public
Definition at line 261 of file class-wp-admin-bar.php.
References _bind(), and _render().
Field Documentation
$bound = false private
Definition at line 17 of file class-wp-admin-bar.php.
$nodes = array() private
Definition at line 16 of file class-wp-admin-bar.php.
Referenced by _get_nodes(), and get_nodes().
$user
Definition at line 18 of file class-wp-admin-bar.php.
The documentation for this class was generated from the following file:
class-wp-admin-bar.php