GravityView: SimplePie_Sanitize Class Reference
SimplePie_Sanitize Class Reference
Public Member Functions
__construct ()
do_strip_htmltags ($match)
encode_instead_of_strip ($encode=false)
pass_cache_data ($enable_cache=true, $cache_location= './cache', $cache_name_function= 'md5', $cache_class= 'SimplePie_Cache')
pass_file_data ($file_class= 'SimplePie_File', $timeout=10, $useragent= '', $force_fsockopen=false)
remove_div ($enable=true)
replace_urls ($document, $tag, $attributes)
sanitize ($data, $type, $base= '')
set_image_handler ($page=false)
set_output_encoding ($encoding= 'UTF-8')
set_registry (SimplePie_Registry $registry)
set_url_replacements ($element_attribute=null)
Set element/attribute key/value pairs of HTML attributes containing URLs that need to be resolved relative to the feed.
strip_attributes ($attribs=array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc'))
strip_comments ($strip=false)
strip_htmltags ($tags=array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style'))
Data Fields
$base
$cache_location = './cache'
$cache_name_function = 'md5'
$enable_cache = true
$encode_instead_of_strip = false
$force_fsockopen = false
$image_handler = ''
$output_encoding = 'UTF-8'
$remove_div = true
$replace_url_attributes = null
$strip_attributes = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc')
$strip_comments = false
$strip_htmltags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style')
$timeout = 10
$useragent = ''
Protected Member Functions
preprocess ($html, $type)
strip_attr ($attrib, $document)
strip_tag ($tag, $document, $type)
Detailed Description
Definition at line 54 of file Sanitize.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 75 of file Sanitize.php.
References null, and set_url_replacements().
Member Function Documentation
do_strip_htmltags ($match)
Definition at line 434 of file Sanitize.php.
References elseif, and encode_instead_of_strip().
encode_instead_of_strip ($encode = false)
Definition at line 158 of file Sanitize.php.
Referenced by do_strip_htmltags(), and strip_tag().
pass_cache_data ($enable_cache = true, $cache_location = './cache', $cache_name_function = 'md5', $cache_class = 'SimplePie_Cache')
Definition at line 103 of file Sanitize.php.
pass_file_data ($file_class = 'SimplePie_File', $timeout = 10, $useragent = '', $force_fsockopen = false)
Definition at line 121 of file Sanitize.php.
preprocess ($html, $type) protected
Definition at line 384 of file Sanitize.php.
References SIMPLEPIE_CONSTRUCT_XHTML.
Referenced by sanitize().
remove_div ($enable = true)
Definition at line 81 of file Sanitize.php.
Referenced by sanitize().
replace_urls ($document, $tag, $attributes)
Definition at line 407 of file Sanitize.php.
References $attributes, $base, $value, and strip_htmltags().
Referenced by sanitize().
sanitize ($data, $type, $base = '')
Definition at line 225 of file Sanitize.php.
References $_SERVER, $attributes, $base, $comment, $file, $force_fsockopen, $timeout, $useragent, preprocess(), remove_div(), replace_urls(), SIMPLEPIE_CONSTRUCT_BASE64, SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_CONSTRUCT_XHTML, SIMPLEPIE_FILE_SOURCE_REMOTE, SIMPLEPIE_PCRE_HTML_ATTRIBUTE, SIMPLEPIE_PCRE_XML_ATTRIBUTE, strip_attr(), strip_attributes(), strip_comments(), strip_htmltags(), and strip_tag().
set_image_handler ($page = false)
Definition at line 86 of file Sanitize.php.
References $page.
set_output_encoding ($encoding = 'UTF-8')
Definition at line 187 of file Sanitize.php.
set_registry (SimplePie_Registry $registry)
Definition at line 98 of file Sanitize.php.
set_url_replacements ($element_attribute = null)
Set element/attribute key/value pairs of HTML attributes containing URLs that need to be resolved relative to the feed.
Defaults to |a|, |area|, |blockquote|
Definition at line 203 of file Sanitize.php.
References null.
Referenced by __construct().
strip_attr ($attrib, $document) protected
Definition at line 544 of file Sanitize.php.
Referenced by sanitize().
strip_attributes ($attribs = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc'))
Definition at line 163 of file Sanitize.php.
Referenced by sanitize().
strip_comments ($strip = false)
Definition at line 182 of file Sanitize.php.
Referenced by sanitize().
strip_htmltags ($tags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style'))
Definition at line 139 of file Sanitize.php.
References $tags.
Referenced by replace_urls(), and sanitize().
strip_tag ($tag, $document, $type) protected
Definition at line 459 of file Sanitize.php.
References $i, $name, $text, $value, elseif, encode_instead_of_strip(), SIMPLEPIE_CONSTRUCT_HTML, and SIMPLEPIE_CONSTRUCT_XHTML.
Referenced by sanitize().
Field Documentation
$base
Definition at line 57 of file Sanitize.php.
Referenced by replace_urls(), WP_SimplePie_Sanitize_KSES\sanitize(), and sanitize().
$cache_location = './cache'
Definition at line 68 of file Sanitize.php.
$cache_name_function = 'md5'
Definition at line 69 of file Sanitize.php.
$enable_cache = true
Definition at line 67 of file Sanitize.php.
$encode_instead_of_strip = false
Definition at line 63 of file Sanitize.php.
$force_fsockopen = false
Definition at line 72 of file Sanitize.php.
Referenced by sanitize().
$image_handler = ''
Definition at line 61 of file Sanitize.php.
$output_encoding = 'UTF-8'
Definition at line 66 of file Sanitize.php.
$remove_div = true
Definition at line 60 of file Sanitize.php.
$replace_url_attributes = null
Definition at line 73 of file Sanitize.php.
$strip_attributes = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc')
Definition at line 64 of file Sanitize.php.
$strip_comments = false
Definition at line 65 of file Sanitize.php.
$strip_htmltags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style')
Definition at line 62 of file Sanitize.php.
$timeout = 10
Definition at line 70 of file Sanitize.php.
Referenced by sanitize().
$useragent = ''
Definition at line 71 of file Sanitize.php.
Referenced by sanitize().
The documentation for this class was generated from the following file:
Sanitize.php