GravityView: Internal_Source Class Reference
Internal_Source Class Reference
If this file is called directly, abort.
Static Public Member Functions
static get_field ()
Get a by Field ID for this data source.
Static Public Member Functions inherited from Source
static get_field ()
Get a instance by ID.
Static Public Attributes
static $backend = self::BACKEND_INTERNAL
Static Public Attributes inherited from Source
static $backend = null
Additional Inherited Members
Data Fields inherited from Source
const BACKEND_GRAVITYFORMS = 'gravityforms'
const BACKEND_INTERNAL = 'internal'
Detailed Description
If this file is called directly, abort.
The class.
Data that comes from within the View itself (like custom content).
Definition at line 14 of file class-gv-source-internal.php.
Member Function Documentation
get_field()
static get_field () static
Get a by Field ID for this data source.
Parameters
int $field_id The internal field ID (custom content, etc.)
Returns
|null The requested field or null if not found.
Unwrap the arguments.
Wrap it up into a .
Definition at line 31 of file class-gv-source-internal.php.
References $field_id, and gravityview().
Referenced by GV\Mocks\GravityView_API_field_label(), and GV\Mocks\GravityView_API_field_value().
Field Documentation
$backend
$backend = self::BACKEND_INTERNAL static
Definition at line 22 of file class-gv-source-internal.php.
The documentation for this class was generated from the following file:
class-gv-source-internal.php