GravityView: WP_oEmbed_Controller Class Reference
WP_oEmbed_Controller Class Reference
oEmbed API endpoint controller.
Public Member Functions
get_item ($request)
Callback for the API endpoint.
register_routes ()
Register the oEmbed REST API route.
Detailed Description
oEmbed API endpoint controller.
Registers the API route and delivers the response data. The output format (XML or JSON) is handled by the REST API.
Since
4.4.0
Definition at line 18 of file class-wp-oembed-controller.php.
Member Function Documentation
get_item ($request)
Callback for the API endpoint.
Returns the JSON object for the post.
Since
4.4.0
Parameters
WP_REST_Request $request Full data about the request.
Returns
WP_Error|array oEmbed response data or WP_Error on failure.
Filter the determined post ID.
Since
4.4.0
Parameters
int $post_id The post ID.
string $url The requested URL.
Definition at line 66 of file class-wp-oembed-controller.php.
References $post_id, apply_filters(), get_oembed_response_data(), get_status_header_desc(), and url_to_postid().
register_routes ()
Register the oEmbed REST API route.
Since
4.4.0
Filter the maxwidth oEmbed parameter.
Since
4.4.0
Parameters
int $maxwidth Maximum allowed width. Default 600.
Definition at line 24 of file class-wp-oembed-controller.php.
References apply_filters(), and WP_REST_Server\READABLE.
The documentation for this class was generated from the following file:
class-wp-oembed-controller.php