GravityView: Widget_Collection Class Reference
Widget_Collection Class Reference
If this file is called directly, abort.
Public Member Functions
add ($widget)
Add a to this collection.
by_id ($id)
Get a copy of this filtered by ID.
by_position ($position)
Get a copy of this filtered by position.
get ($widget_uid)
Get a from this list by UID.
Public Member Functions inherited from Collection
add ($value)
Add an object to this collection.
all ()
Returns all the objects in this collection as an an array.
clear ()
Clear this collection.
count ()
Returns the count of the objects in this collection.
first ()
Get the first added object.
last ()
Get the last added object.
merge (\GV\Collection $collection)
Merge another collection into here.
Static Public Member Functions
static from_configuration ($configuration)
Parse a configuration array into a Widget_Collection.
Detailed Description
If this file is called directly, abort.
A collection of objects.
Definition at line 12 of file class-gv-collection-widget.php.
Member Function Documentation
add()
add ($widget)
Add a to this collection.
Parameters
\GV\Widget $widget The widget to add to the internal array.
Since
2.0
Returns
void
Definition at line 22 of file class-gv-collection-widget.php.
References gravityview().
by_id()
by_id ($id)
Get a copy of this filtered by ID.
Parameters
string $id The IDs to get the widgets for.
Since
Returns
A filtered collection of , filtered by ID.
Definition at line 83 of file class-gv-collection-widget.php.
References GV\all().
by_position()
by_position ($position)
Get a copy of this filtered by position.
Parameters
string $position The position to get the widgets for. Can be a wildcard *
Since
Returns
A filtered collection of , filtered by position.
Definition at line 60 of file class-gv-collection-widget.php.
References GV\all().
from_configuration()
static from_configuration ($configuration) static
Parse a configuration array into a Widget_Collection.
Parameters
array $configuration The configuration, structured like so:
array(
[other zones]
'footer_right' => array(
[other widgets]
'5372653f25d44' => array(
    @see \GV\Widget::as_configuration() for structure
)
    [other widgets]
)
[other zones])
Returns
A collection of widgets.
Definition at line 119 of file class-gv-collection-widget.php.
References GV\all().
get()
get ($widget_uid)
Get a from this list by UID.
Parameters
int $widget_uid The UID of the widget in the collection to get.
Since
2.0
Returns
|null The with the $widget_uid as the UID, or null if not found.
Definition at line 40 of file class-gv-collection-widget.php.
References GV\all().
The documentation for this class was generated from the following file:
class-gv-collection-widget.php