GravityView: GravityView_Widget_Gravity_Forms Class Reference
GravityView_Widget_Gravity_Forms Class Reference
Widget to display a Gravity Forms form.
Public Member Functions
__construct ()
add_to_allowlist ($allowlist)
Add widget to a list of allowed "Hide Until Searched" items.
render_frontend ($widget_args, $content='', $context='')
Public Member Functions inherited from Widget
add_shortcode ()
Add $this->shortcode_name shortcode to output self::render_frontend()
as_configuration ()
Return an array of the old format.
assign_widget_options ($options=array(), $template='', $widget='')
Assign template specific widget options.
get_setting ($key)
Get a setting by the setting key.
get_settings ()
Get the widget settings.
get_widget_id ()
Get the Widget ID.
is_registered ()
Whether this Widget's been registered already or not.
maybe_do_shortcode ($text, $widget=null)
Do shortcode if the Widget's shortcode exists.
pre_render_frontend ()
General validations when rendering the widget.
register_widget ($widgets)
Register widget to become available in admin.
render_frontend ($widget_args, $content='', $context='')
Frontend logic.
render_shortcode ($atts, $content='', $context='')
Shortcode.
Data Fields
$icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MDguMyA1NTkuNSIgZm9jdXNhYmxlPSJmYWxzZSIgYXJpYS1oaWRkZW49InRydWUiIGNsYXNzPSJkYXNoaWNvbiBkYXNoaWNvbi1ncmF2aXR5Zm9ybXMiIHJvbGU9ImltZyI+PGc+PHBhdGggY2xhc3M9InN0MCIgZD0iTTQ2OCwxMDkuOEwyOTQuNCw5LjZjLTIyLjEtMTIuOC01OC40LTEyLjgtODAuNSwwTDQwLjMsMTA5LjhDMTguMiwxMjIuNiwwLDE1NCwwLDE3OS41VjM4MAljMCwyNS42LDE4LjEsNTYuOSw0MC4zLDY5LjdsMTczLjYsMTAwLjJjMjIuMSwxMi44LDU4LjQsMTIuOCw4MC41LDBMNDY4LDQ0OS44YzIyLjItMTIuOCw0MC4zLTQ0LjIsNDAuMy02OS43VjE3OS42CUM1MDguMywxNTQsNDkwLjIsMTIyLjYsNDY4LDEwOS44eiBNMzk5LjMsMjQ0LjRsLTE5NS4xLDBjLTExLDAtMTkuMiwzLjItMjUuNiwxMGMtMTQuMiwxNS4xLTE4LjIsNDQuNC0xOS4zLDYwLjdIMzQ4di0yNi40aDQ5LjkJdjc2LjNIMTExLjNsLTEuOC0yM2MtMC4zLTMuMy01LjktODAuNywzMi44LTEyMS45YzE2LjEtMTcuMSwzNy4xLTI1LjgsNjIuNC0yNS44aDE5NC43VjI0NC40eiI+PC9wYXRoPjwvZz48L3N2Zz4='
Data Fields inherited from Widget
$configuration
$icon
$position = ''
$UID = ''
Protected Attributes
$show_on_single = true
Protected Attributes inherited from Widget
$defaults = array()
$settings = array()
$shortcode_name
$widget_description = ''
$widget_id = ''
$widget_label = ''
$widget_subtitle = ''
Private Member Functions
_get_form_choices ()
Returns an array of active forms to show as choices for the widget.
Additional Inherited Members
Static Public Member Functions inherited from Widget
static from_configuration ($configuration)
Create the needed widget from a configuration array.
static get_default_widget_areas ()
Default widget areas.
static registered ()
Return all registered widgets.
Protected Member Functions inherited from Widget
get_default_settings ()
Define general widget settings.
Detailed Description
Widget to display a Gravity Forms form.
Definition at line 8 of file class-gravityview-widget-gravityforms.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 18 of file class-gravityview-widget-gravityforms.php.
References Widget\$settings, Utils\_GET(), _get_form_choices(), Utils\_POST(), and gravityview().
Member Function Documentation
_get_form_choices()
_get_form_choices () private
Returns an array of active forms to show as choices for the widget.
Since
2.9.0.1
Returns
array Array with key set to Form ID => Form Title, with 0 as default placeholder.
Definition at line 79 of file class-gravityview-widget-gravityforms.php.
References GV\$form.
Referenced by __construct().
add_to_allowlist()
add_to_allowlist ($allowlist)
Add widget to a list of allowed "Hide Until Searched" items.
Parameters
array $allowlist Array of widgets to show before a search is performed, if the setting is enabled.
Returns
array
Definition at line 110 of file class-gravityview-widget-gravityforms.php.
render_frontend()
render_frontend ($widget_args, $content = '', $context = '')
Parameters
array $widget_args
string $content
string $context
Definition at line 122 of file class-gravityview-widget-gravityforms.php.
References $description, $form_id, $title, Utils\get(), GV\get(), and Widget\pre_render_frontend().
Field Documentation
$icon
$icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MDguMyA1NTkuNSIgZm9jdXNhYmxlPSJmYWxzZSIgYXJpYS1oaWRkZW49InRydWUiIGNsYXNzPSJkYXNoaWNvbiBkYXNoaWNvbi1ncmF2aXR5Zm9ybXMiIHJvbGU9ImltZyI+PGc+PHBhdGggY2xhc3M9InN0MCIgZD0iTTQ2OCwxMDkuOEwyOTQuNCw5LjZjLTIyLjEtMTIuOC01OC40LTEyLjgtODAuNSwwTDQwLjMsMTA5LjhDMTguMiwxMjIuNiwwLDE1NCwwLDE3OS41VjM4MAljMCwyNS42LDE4LjEsNTYuOSw0MC4zLDY5LjdsMTczLjYsMTAwLjJjMjIuMSwxMi44LDU4LjQsMTIuOCw4MC41LDBMNDY4LDQ0OS44YzIyLjItMTIuOCw0MC4zLTQ0LjIsNDAuMy02OS43VjE3OS42CUM1MDguMywxNTQsNDkwLjIsMTIyLjYsNDY4LDEwOS44eiBNMzk5LjMsMjQ0LjRsLTE5NS4xLDBjLTExLDAtMTkuMiwzLjItMjUuNiwxMGMtMTQuMiwxNS4xLTE4LjIsNDQuNC0xOS4zLDYwLjdIMzQ4di0yNi40aDQ5LjkJdjc2LjNIMTExLjNsLTEuOC0yM2MtMC4zLTMuMy01LjktODAuNywzMi44LTEyMS45YzE2LjEtMTcuMSwzNy4xLTI1LjgsNjIuNC0yNS44aDE5NC43VjI0NC40eiI+PC9wYXRoPjwvZz48L3N2Zz4='
Definition at line 10 of file class-gravityview-widget-gravityforms.php.
$show_on_single
$show_on_single = true protected
Definition at line 16 of file class-gravityview-widget-gravityforms.php.
The documentation for this class was generated from the following file:
class-gravityview-widget-gravityforms.php