GravityView: Walker Class Reference
Walker Class Reference
Public Member Functions
display_element ($element, &$children_elements, $max_depth, $depth, $args, &$output)
Traverse elements to create list from elements.
end_el (&$output, $object, $depth=0, $args=array())
Ends the element output, if needed.
end_lvl (&$output, $depth=0, $args=array())
Ends the list of after the elements are added.
get_number_of_root_elements ($elements)
Calculates the total number of root elements.
paged_walk ($elements, $max_depth, $page_num, $per_page)
paged_walk() - produce a page of nested elements
start_el (&$output, $object, $depth=0, $args=array(), $current_object_id=0)
Start the element output.
start_lvl (&$output, $depth=0, $args=array())
Starts the list before the elements are added.
unset_children ($e, &$children_elements)
Unset all the children for a given top level element.
walk ($elements, $max_depth)
Display array of elements hierarchically.
Data Fields
$db_fields
$has_children
$max_pages = 1
$tree_type
Detailed Description
Definition at line 14 of file class-wp-walker.php.
Member Function Documentation
display_element ($element, & $children_elements, $max_depth, $depth, $args, & $output)
Traverse elements to create list from elements.
Display one element if the element doesn't have any children otherwise, display the element and its children. Will only traverse up to the max depth and no ignore elements under that depth. It is possible to set the max depth to include all depths, see walk() method.
This method should not be called directly, use the walk() method instead.
Since
2.5.0
Parameters
object $element Data object.
array $children_elements List of elements to continue traversing.
int $max_depth Max depth to traverse.
int $depth Depth of current element.
array $args An array of arguments.
string $output Passed by reference. Used to append additional content.
Definition at line 131 of file class-wp-walker.php.
References $has_children, $id, and $output.
Referenced by paged_walk(), and walk().
end_el (& $output, $object, $depth = 0, $args = array())
Ends the element output, if needed.
The $args parameter holds additional values that may be used with the child class methods.
Since
2.1.0
Parameters
string $output Passed by reference. Used to append additional content.
object $object The data object.
int $depth Depth of the item.
array $args An array of additional arguments.
Definition at line 110 of file class-wp-walker.php.
end_lvl (& $output, $depth = 0, $args = array())
Ends the list of after the elements are added.
The $args parameter holds additional values that may be used with the child class methods. This method finishes the list at the end of output of the elements.
Since
2.1.0
Parameters
string $output Passed by reference. Used to append additional content.
int $depth Depth of the item.
array $args An array of additional arguments.
Definition at line 78 of file class-wp-walker.php.
get_number_of_root_elements ($elements)
Calculates the total number of root elements.
Since
2.7.0 public
Parameters
array $elements Elements to list.
Returns
int Number of root elements.
Definition at line 393 of file class-wp-walker.php.
paged_walk ($elements, $max_depth, $page_num, $per_page)
paged_walk() - produce a page of nested elements
Given an array of hierarchical elements, the maximum depth, a specific page number, and number of elements per page, this function first determines all top level root elements belonging to that page, then lists them and all of their children in hierarchical order.
$max_depth = 0 means display all levels. $max_depth > 0 specifies the number of display levels.
Since
2.7.0
Parameters
array $elements
int $max_depth The maximum hierarchical depth.
int $page_num The specific page number, beginning with 1.
int $per_page
Returns
string XHTML of the specified page of elements
Definition at line 278 of file class-wp-walker.php.
References $count, $output, display_element(), and unset_children().
start_el (& $output, $object, $depth = 0, $args = array(), $current_object_id = 0)
Start the element output.
The $args parameter holds additional values that may be used with the child class methods. Includes the element output also.
Since
2.1.0
Parameters
string $output Passed by reference. Used to append additional content.
object $object The data object.
int $depth Depth of the item.
array $args An array of additional arguments.
int $current_object_id ID of the current item.
Definition at line 95 of file class-wp-walker.php.
start_lvl (& $output, $depth = 0, $args = array())
Starts the list before the elements are added.
The $args parameter holds additional values that may be used with the child class methods. This method is called at the start of the output list.
Since
2.1.0
Parameters
string $output Passed by reference. Used to append additional content.
int $depth Depth of the item.
array $args An array of additional arguments.
Definition at line 63 of file class-wp-walker.php.
unset_children ($e, & $children_elements)
Unset all the children for a given top level element.
Parameters
object $e
array $children_elements
Definition at line 410 of file class-wp-walker.php.
References $id.
Referenced by paged_walk().
walk ($elements, $max_depth)
Display array of elements hierarchically.
Does not assume any existing order of elements.
$max_depth = -1 means flatly display every element. $max_depth = 0 means display all levels. $max_depth > 0 specifies the number of display levels.
Since
2.1.0
Parameters
array $elements An array of elements.
int $max_depth The maximum hierarchical depth.
Returns
string The hierarchical item output.
Definition at line 190 of file class-wp-walker.php.
References $output, and display_element().
Field Documentation
$db_fields
Definition at line 30 of file class-wp-walker.php.
$has_children
Definition at line 48 of file class-wp-walker.php.
Referenced by display_element().
$max_pages = 1
Definition at line 38 of file class-wp-walker.php.
$tree_type
Definition at line 22 of file class-wp-walker.php.
The documentation for this class was generated from the following file:
class-wp-walker.php