GravityView: Logger Class Reference
Logger Class Reference
Finally, a light, permissions-checking logging class.
Public Member Functions
__construct ($logDirectory, $logLevelThreshold=LogLevel::DEBUG, array $options=array())
Class constructor.
__destruct ()
Class destructor.
getLastLogLine ()
Get the last line logged to the log file.
getLogFilePath ()
Get the file path that the log is currently writing to.
log ($level, $message, array $context=array())
Logs with an arbitrary level.
setDateFormat ($dateFormat)
Sets the date format used by all instances of KLogger.
setFileHandle ($writeMode)
setLogFilePath ($logDirectory)
setLogLevelThreshold ($logLevelThreshold)
Sets the Log Level Threshold.
setLogToStdOut ($stdOutPath)
write ($message)
Writes a line to the log without prepending a status or timestamp.
Public Member Functions inherited from AbstractLogger
alert ($message, array $context=array())
Action must be taken immediately.
critical ($message, array $context=array())
Critical conditions.
debug ($message, array $context=array())
Detailed debug information.
emergency ($message, array $context=array())
System is unusable.
error ($message, array $context=array())
Runtime errors that do not require immediate action but should typically be logged and monitored.
info ($message, array $context=array())
Interesting events.
notice ($message, array $context=array())
Normal but significant events.
warning ($message, array $context=array())
Exceptional occurrences that are not errors.
Protected Member Functions
contextToString ($context)
Takes the given context and coverts it to a string.
formatMessage ($level, $message, $context)
Formats the message for logging.
indent ($string, $indent=' ')
Indents the given string with the given indent.
Protected Attributes
$logLevels
$logLevelThreshold = LogLevel::DEBUG
$options
Private Member Functions
getTimestamp ()
Gets the correctly formatted Date/Time for the log entry.
Private Attributes
$defaultPermissions = 0777
$fileHandle
$lastLine = ''
$logFilePath
$logLineCount = 0
Detailed Description
Finally, a light, permissions-checking logging class.
Originally written for use with wpSearch
Usage: $log = new GravityView('/var/log/', GravityView::INFO); $log->info('Returned a million search results'); //Prints to the log file $log->error('Oh dear.'); //Prints to the log file $log->debug('x = 5'); //Prints nothing due to current severity threshhold
Author
Kenny Katzgrau katzg.nosp@m.rau@.nosp@m.gmail.nosp@m..com
Since
July 26, 2008 1.0.0 Class documentation
Definition at line 35 of file Logger.php.
Constructor & Destructor Documentation
__construct()
__construct ($logDirectory, $logLevelThreshold = LogLevel::DEBUG, array $options = array())
Class constructor.
Parameters
string $logDirectory File path to the logging directory
string $logLevelThreshold The LogLevel Threshold
array $options
Definition at line 118 of file Logger.php.
References Logger\$logLevelThreshold, Logger\$options, Logger\setFileHandle(), Logger\setLogFilePath(), and Logger\setLogToStdOut().
__destruct()
__destruct ()
Class destructor.
Definition at line 180 of file Logger.php.
Member Function Documentation
contextToString()
contextToString ($context) protected
Takes the given context and coverts it to a string.
Parameters
array $context The Context
Returns
string
Definition at line 325 of file Logger.php.
References $value.
Referenced by Logger\formatMessage().
formatMessage()
formatMessage ($level, $message, $context) protected
Formats the message for logging.
Parameters
string $level The Log Level of the message
string $message The message to log
array $context The context
Returns
string
Definition at line 274 of file Logger.php.
References $value, Logger\contextToString(), and Logger\getTimestamp().
Referenced by Logger\log().
getLastLogLine()
getLastLogLine ()
Get the last line logged to the log file.
Returns
string
Definition at line 261 of file Logger.php.
References Logger\$lastLine.
getLogFilePath()
getLogFilePath ()
Get the file path that the log is currently writing to.
Returns
string
Definition at line 251 of file Logger.php.
References Logger\$logFilePath.
getTimestamp()
getTimestamp () private
Gets the correctly formatted Date/Time for the log entry.
PHP DateTime is dump, and you have to resort to trickery to get microseconds to work correctly, so here it is.
Returns
string
Definition at line 310 of file Logger.php.
Referenced by Logger\formatMessage().
indent()
indent ($string, $indent = ' ') protected
Indents the given string with the given indent.
Parameters
string $string The string to indent
string $indent What to use as the indent.
Returns
string
Definition at line 351 of file Logger.php.
log()
log ($level, $message, array $context = array())
Logs with an arbitrary level.
Parameters
mixed $level
string $message
array $context
Returns
null
Implements LoggerInterface.
Definition at line 215 of file Logger.php.
References Logger\formatMessage(), and Logger\write().
setDateFormat()
setDateFormat ($dateFormat)
Sets the date format used by all instances of KLogger.
Parameters
string $dateFormat Valid format string for date()
Definition at line 192 of file Logger.php.
setFileHandle()
setFileHandle ($writeMode)
Parameters
$writeMode
Definition at line 172 of file Logger.php.
Referenced by Logger\__construct().
setLogFilePath()
setLogFilePath ($logDirectory)
Parameters
string $logDirectory
Definition at line 154 of file Logger.php.
Referenced by Logger\__construct().
setLogLevelThreshold()
setLogLevelThreshold ($logLevelThreshold)
Sets the Log Level Threshold.
Parameters
string $logLevelThreshold The log level threshold
Definition at line 202 of file Logger.php.
References Logger\$logLevelThreshold.
setLogToStdOut()
setLogToStdOut ($stdOutPath)
Parameters
string $stdOutPath
Definition at line 147 of file Logger.php.
Referenced by Logger\__construct().
write()
write ($message)
Writes a line to the log without prepending a status or timestamp.
Parameters
string $message Line to write to the log
Returns
void
Definition at line 230 of file Logger.php.
Referenced by Logger\log().
Field Documentation
$defaultPermissions
$defaultPermissions = 0777 private
Definition at line 106 of file Logger.php.
$fileHandle
$fileHandle private
Definition at line 93 of file Logger.php.
$lastLine
$lastLine = '' private
Definition at line 100 of file Logger.php.
Referenced by Logger\getLastLogLine().
$logFilePath
$logFilePath private
Definition at line 60 of file Logger.php.
Referenced by Logger\getLogFilePath().
$logLevels
$logLevels protected
Initial value:
= array(
        LogLevel::EMERGENCY => 0,
        LogLevel::ALERT     => 1,
        LogLevel::CRITICAL  => 2,
        LogLevel::ERROR     => 3,
        LogLevel::WARNING   => 4,
        LogLevel::NOTICE    => 5,
        LogLevel::INFO      => 6,
        LogLevel::DEBUG     => 7
    )
Definition at line 78 of file Logger.php.
$logLevelThreshold
$logLevelThreshold = LogLevel::DEBUG protected
Definition at line 66 of file Logger.php.
Referenced by Logger\__construct(), and Logger\setLogLevelThreshold().
$logLineCount
$logLineCount = 0 private
Definition at line 72 of file Logger.php.
$options
$options protected
Initial value:
= array (
        'extension'      => 'txt',
        'dateFormat'     => 'Y-m-d G:i:s.u',
        'filename'       => false,
        'flushFrequency' => false,
        'prefix'         => 'log_',
        'logFormat'      => false,
        'appendContext'  => true,
    )
Definition at line 46 of file Logger.php.
Referenced by Logger\__construct().
The documentation for this class was generated from the following file:
Logger.php