GravityView: WP_MS_Themes_List_Table Class Reference
WP_MS_Themes_List_Table Class Reference
Core class used to implement displaying themes in a list table for the network admin.
Public Member Functions
__construct ($args=array())
Constructor.
_order_callback ($theme_a, $theme_b)
string $orderby string $order
_search_callback ($theme)
string $term
ajax_user_can ()
column_cb ($theme)
Handles the checkbox column output.
column_default ($theme, $column_name)
Handles default column output.
column_description ($theme)
Handles the description column output.
column_name ($theme)
Handles the name column output.
display_rows ()
public
get_columns ()
no_items ()
public
prepare_items ()
string $status array $totals int $page string $orderby string $order string $s
single_row ($theme)
string $status array $totals
single_row_columns ($item)
Handles the output for a single table row.
Public Member Functions inherited from WP_List_Table
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($args=array())
Constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
_js_vars ()
Send required variables to JavaScript land.
ajax_response ()
Handle an incoming ajax request (called from admin-ajax.php)
ajax_user_can ()
Checks the current user's permissions.
current_action ()
Get the current action selected from the bulk actions dropdown.
display ()
Display the table.
display_rows ()
Generate the table rows.
display_rows_or_placeholder ()
Generate the tbody element for the list table.
get_column_count ()
Return number of visible columns.
get_columns ()
Get a list of columns.
get_pagenum ()
Get the current page number.
get_pagination_arg ($key)
Access the pagination args.
get_primary_column ()
Public wrapper for WP_List_Table::get_default_primary_column_name().
has_items ()
Whether the table has items to display or not.
no_items ()
Message to be displayed when there are no items.
prepare_items ()
Prepares the list of items for displaying.
print_column_headers ($with_id=true)
Print column headers, accounting for hidden and sortable columns.
search_box ($text, $input_id)
Display the search box.
single_row ($item)
Generates content for a single row of the table.
views ()
Display the list of views available on this table.
Data Fields
$is_site_themes
$site_id
Data Fields inherited from WP_List_Table
$items
Protected Member Functions
get_bulk_actions ()
string $status
get_primary_column_name ()
Gets the name of the primary column.
get_sortable_columns ()
get_table_classes ()
get_views ()
array $totals string $status
Protected Member Functions inherited from WP_List_Table
bulk_actions ($which= '')
Display the bulk actions dropdown.
column_cb ($item)
column_default ($item, $column_name)
comments_bubble ($post_id, $pending_comments)
Display a comment count bubble.
display_tablenav ($which)
Generate the table navigation above or below the table.
extra_tablenav ($which)
Extra controls to be displayed between bulk actions and pagination.
get_bulk_actions ()
Get an associative array (option_name => option_title) with the list of bulk actions available on this table.
get_column_info ()
Get a list of all, hidden and sortable columns, with filter applied.
get_default_primary_column_name ()
Gets the name of the default primary column.
get_items_per_page ($option, $default=20)
Get number of items to display on a single page.
get_primary_column_name ()
Gets the name of the primary column.
get_sortable_columns ()
Get a list of sortable columns.
get_table_classes ()
Get a list of CSS classes for the WP_List_Table table tag.
get_views ()
Get an associative array (id => link) with the list of views available on this table.
handle_row_actions ($item, $column_name, $primary)
Generates and display row actions links for the list table.
months_dropdown ($post_type)
Display a monthly dropdown for filtering items.
pagination ($which)
Display the pagination.
row_actions ($actions, $always_visible=false)
Generate row actions div.
set_pagination_args ($args)
An internal method that sets all the necessary pagination arguments.
single_row_columns ($item)
Generates the columns for a single row of the table.
view_switcher ($current_mode)
Display a view switcher.
Private Attributes
$has_items
Additional Inherited Members
Protected Attributes inherited from WP_List_Table
$_args
$_column_headers
$_pagination_args = array()
$compat_fields = array('_args', '_pagination_args', 'screen', '_actions', '_pagination')
{
$compat_methods
{
$modes = array()
$screen
Detailed Description
Core class used to implement displaying themes in a list table for the network admin.
Since
3.1.0 private
See also
WP_List_Table
Definition at line 18 of file class-wp-ms-themes-list-table.php.
Constructor & Destructor Documentation
__construct ($args = array())
Constructor.
Since
3.1.0 public
See also
WP_List_Table::__construct() for more information on default arguments.
string $status int $page
Parameters
array $args An associative array of arguments.
Definition at line 38 of file class-wp-ms-themes-list-table.php.
References $page, WP_List_Table\get_pagenum(), and null.
Member Function Documentation
_order_callback ($theme_a, $theme_b)
string $orderby string $order
Parameters
array $theme_a
array $theme_b
Returns
int
Definition at line 209 of file class-wp-ms-themes-list-table.php.
_search_callback ($theme)
string $term
Parameters
WP_Theme $theme
Returns
bool
Definition at line 181 of file class-wp-ms-themes-list-table.php.
References $field, $theme, null, and wp_unslash().
ajax_user_can ()
Returns
bool
Definition at line 71 of file class-wp-ms-themes-list-table.php.
References current_user_can().
column_cb ($theme)
Handles the checkbox column output.
Since
4.3.0 public
Parameters
WP_Theme $theme The current WP_Theme object.
Definition at line 356 of file class-wp-ms-themes-list-table.php.
References $theme, _e, input, label, and name.
Referenced by single_row_columns().
column_default ($theme, $column_name)
Handles default column output.
Since
4.3.0 public
Parameters
WP_Theme $theme The current WP_Theme object.
string $column_name The current column name.
Fires inside each custom column of the Multisite themes list table.
Since
3.1.0
Parameters
string $column_name Name of the column.
string $stylesheet Directory name of the theme.
WP_Theme $theme Current WP_Theme object.
Definition at line 599 of file class-wp-ms-themes-list-table.php.
References $theme, and do_action().
Referenced by single_row_columns().
column_description ($theme)
Handles the description column output.
Since
4.3.0 public
string $status array $totals
Parameters
WP_Theme $theme The current WP_Theme object.
Filter the array of row meta for each theme in the Multisite themes list table.
Since
3.1.0
Parameters
array $theme_meta An array of the theme's metadata, including the version, author, and theme URI.
string $stylesheet Directory name of the theme.
WP_Theme $theme WP_Theme object.
string $status Status of the theme.
Definition at line 533 of file class-wp-ms-themes-list-table.php.
References $class, $theme, __, apply_filters(), and esc_attr().
Referenced by single_row_columns().
column_name ($theme)
Handles the name column output.
Since
4.3.0 public
string $status int $page string $s
Parameters
WP_Theme $theme The current WP_Theme object.
Filter the action links displayed for each theme in the Multisite themes list table.
The action links displayed are determined by the theme's status, and which Multisite themes list table is being displayed - the Network themes list table (themes.php), which displays all installed themes, or the Site themes list table (site-themes.php), which displays the non-network enabled themes when editing a site in the Network admin.
The default action links for the Network themes list table include 'Network Enable', 'Network Disable', 'Edit', and 'Delete'.
The default action links for the Site themes list table include 'Enable', 'Disable', and 'Edit'.
Since
2.8.0
Parameters
array $actions An array of action links.
WP_Theme $theme The current WP_Theme object.
string $context Status of the theme.
Filter the action links of a specific theme in the Multisite themes list table.
The dynamic portion of the hook name, $stylesheet, refers to the directory name of the theme, which in most cases is synonymous with the template name.
Since
3.1.0
Parameters
array $actions An array of action links.
WP_Theme $theme The current WP_Theme object.
string $context Status of the theme.
Definition at line 376 of file class-wp-ms-themes-list-table.php.
References $page, $s, $theme, $url, __, add_query_arg(), apply_filters(), current_user_can(), esc_attr(), esc_url, get_option(), WP_List_Table\row_actions(), and wp_nonce_url().
Referenced by single_row_columns().
display_rows ()
public
Definition at line 343 of file class-wp-ms-themes-list-table.php.
References $theme, and single_row().
get_bulk_actions () protected
string $status
Returns
array
Definition at line 323 of file class-wp-ms-themes-list-table.php.
References __, and current_user_can().
get_columns ()
Returns
array
Definition at line 239 of file class-wp-ms-themes-list-table.php.
References __.
get_primary_column_name () protected
Gets the name of the primary column.
Since
4.3.0 protected
Returns
string Unalterable name of the primary column name, in this case, 'name'.
Definition at line 265 of file class-wp-ms-themes-list-table.php.
get_sortable_columns () protected
Returns
array
Definition at line 251 of file class-wp-ms-themes-list-table.php.
get_table_classes () protected
Returns
array
Definition at line 62 of file class-wp-ms-themes-list-table.php.
get_views () protected
array $totals string $status
Returns
array
Definition at line 275 of file class-wp-ms-themes-list-table.php.
References $count, $site_id, $text, $url, _n(), _nx(), add_query_arg(), esc_url, and number_format_i18n().
no_items ()
public
Definition at line 227 of file class-wp-ms-themes-list-table.php.
References _e, and WP_List_Table\has_items().
prepare_items ()
string $status array $totals int $page string $orderby string $order string $s
Filter the full array of WP_Theme objects to list in the Multisite themes list table.
Since
3.1.0
Parameters
array $all An array of WP_Theme objects to display in the list table.
Definition at line 87 of file class-wp-ms-themes-list-table.php.
References $list, $page, $s, $theme, apply_filters(), current_user_can(), WP_List_Table\get_items_per_page(), get_site_transient(), WP_List_Table\has_items(), WP_List_Table\set_pagination_args(), WP_Theme\sort_by_name(), wp_get_themes(), and wp_reset_vars().
single_row ($theme)
string $status array $totals
Parameters
WP_Theme $theme
Fires after each row in the Multisite themes list table.
Since
3.1.0
Parameters
string $stylesheet Directory name of the theme.
WP_Theme $theme Current WP_Theme object.
string $status Status of the theme.
Fires after each specific row in the Multisite themes list table.
The dynamic portion of the hook name, $stylesheet, refers to the directory name of the theme, most often synonymous with the template name of the theme.
Since
3.5.0
Parameters
string $stylesheet Directory name of the theme.
WP_Theme $theme Current WP_Theme object.
string $status Status of the theme.
Definition at line 673 of file class-wp-ms-themes-list-table.php.
References $class, $id, $theme, do_action(), remove_action(), sanitize_html_class(), and single_row_columns().
Referenced by display_rows().
single_row_columns ($item)
Handles the output for a single table row.
Since
4.3.0 public
Parameters
WP_Theme $item The current WP_Theme object.
Definition at line 622 of file class-wp-ms-themes-list-table.php.
References $columns, column_cb(), column_default(), column_description(), column_name(), and WP_List_Table\get_column_info().
Referenced by single_row().
Field Documentation
$has_items private
Definition at line 23 of file class-wp-ms-themes-list-table.php.
$is_site_themes
Definition at line 21 of file class-wp-ms-themes-list-table.php.
$site_id
Definition at line 20 of file class-wp-ms-themes-list-table.php.
Referenced by get_views().
The documentation for this class was generated from the following file:
class-wp-ms-themes-list-table.php