GravityView: PclZip Class Reference
PclZip Class Reference
Public Member Functions
__construct ($p_zipname)
add ($p_filelist)
create ($p_filelist)
delete ()
deleteByIndex ($p_index)
duplicate ($p_archive)
errorCode ()
errorInfo ($p_full=false)
errorName ($p_with_code=false)
extract ()
extractByIndex ($p_index)
listContent ()
merge ($p_archive_to_add)
PclZip ($p_zipname)
privAdd ($p_filedescr_list, &$p_result_list, &$p_options)
privAddFile ($p_filedescr, &$p_header, &$p_options)
privAddFileList ($p_filedescr_list, &$p_result_list, &$p_options)
privAddFileUsingTempFile ($p_filedescr, &$p_header, &$p_options)
privAddList ($p_filedescr_list, &$p_result_list, &$p_options)
privCalculateStoredFilename (&$p_filedescr, &$p_options)
privCheckFileHeaders (&$p_local_header, &$p_central_header)
privCheckFormat ($p_level=0)
privCloseFd ()
privConvertHeader2FileInfo ($p_header, &$p_info)
privCreate ($p_filedescr_list, &$p_result_list, &$p_options)
privDeleteByRule (&$p_result_list, &$p_options)
privDirCheck ($p_dir, $p_is_dir=false)
privDisableMagicQuotes ()
privDuplicate ($p_archive_filename)
privErrorLog ($p_error_code=0, $p_error_string='')
privErrorReset ()
privExtractByRule (&$p_file_list, $p_path, $p_remove_path, $p_remove_all_path, &$p_options)
privExtractFile (&$p_entry, $p_path, $p_remove_path, $p_remove_all_path, &$p_options)
privExtractFileAsString (&$p_entry, &$p_string, &$p_options)
privExtractFileInOutput (&$p_entry, &$p_options)
privExtractFileUsingTempFile (&$p_entry, &$p_options)
privFileDescrExpand (&$p_filedescr_list, &$p_options)
privFileDescrParseAtt (&$p_file_list, &$p_filedescr, $v_options, $v_requested_options=false)
privList (&$p_list)
privMerge (&$p_archive_to_add)
privOpenFd ($p_mode)
privOptionDefaultThreshold (&$p_options)
privParseOptions (&$p_options_list, $p_size, &$v_result_list, $v_requested_options=false)
privReadCentralFileHeader (&$p_header)
privReadEndCentralDir (&$p_central_dir)
privReadFileHeader (&$p_header)
privSwapBackMagicQuotes ()
privWriteCentralFileHeader (&$p_header)
privWriteCentralHeader ($p_nb_entries, $p_size, $p_offset, $p_comment)
privWriteFileHeader (&$p_header)
properties ()
Data Fields
$error_code = 1
$error_string = ''
$magic_quotes_status
$zip_fd = 0
$zipname = ''
Detailed Description
Definition at line 190 of file class-pclzip.php.
Constructor & Destructor Documentation
__construct ($p_zipname)
Definition at line 215 of file class-pclzip.php.
Member Function Documentation
add ($p_filelist)
Definition at line 458 of file class-pclzip.php.
References PCLZIP_ATT_FILE_COMMENT, PCLZIP_ATT_FILE_CONTENT, PCLZIP_ATT_FILE_MTIME, PCLZIP_ATT_FILE_NAME, PCLZIP_ATT_FILE_NEW_FULL_NAME, PCLZIP_ATT_FILE_NEW_SHORT_NAME, PCLZIP_CB_POST_ADD, PCLZIP_CB_PRE_ADD, PCLZIP_ERR_INVALID_PARAMETER, PCLZIP_OPT_ADD_COMMENT, PCLZIP_OPT_ADD_PATH, PCLZIP_OPT_COMMENT, PCLZIP_OPT_NO_COMPRESSION, PCLZIP_OPT_PREPEND_COMMENT, PCLZIP_OPT_REMOVE_ALL_PATH, PCLZIP_OPT_REMOVE_PATH, PCLZIP_OPT_TEMP_FILE_OFF, PCLZIP_OPT_TEMP_FILE_ON, PCLZIP_OPT_TEMP_FILE_THRESHOLD, privAdd(), privErrorLog(), privErrorReset(), privFileDescrExpand(), privFileDescrParseAtt(), privOptionDefaultThreshold(), and privParseOptions().
create ($p_filelist)
Definition at line 275 of file class-pclzip.php.
References PCLZIP_ATT_FILE_COMMENT, PCLZIP_ATT_FILE_CONTENT, PCLZIP_ATT_FILE_MTIME, PCLZIP_ATT_FILE_NAME, PCLZIP_ATT_FILE_NEW_FULL_NAME, PCLZIP_ATT_FILE_NEW_SHORT_NAME, PCLZIP_CB_POST_ADD, PCLZIP_CB_PRE_ADD, PCLZIP_ERR_INVALID_PARAMETER, PCLZIP_OPT_ADD_PATH, PCLZIP_OPT_COMMENT, PCLZIP_OPT_NO_COMPRESSION, PCLZIP_OPT_REMOVE_ALL_PATH, PCLZIP_OPT_REMOVE_PATH, PCLZIP_OPT_TEMP_FILE_OFF, PCLZIP_OPT_TEMP_FILE_ON, PCLZIP_OPT_TEMP_FILE_THRESHOLD, privCreate(), privErrorLog(), privErrorReset(), privFileDescrExpand(), privFileDescrParseAtt(), privOptionDefaultThreshold(), and privParseOptions().
delete ()
Definition at line 1010 of file class-pclzip.php.
References PCLZIP_OPT_BY_EREG, PCLZIP_OPT_BY_INDEX, PCLZIP_OPT_BY_NAME, PCLZIP_OPT_BY_PREG, privCheckFormat(), privDeleteByRule(), privDisableMagicQuotes(), privErrorReset(), privParseOptions(), and privSwapBackMagicQuotes().
deleteByIndex ($p_index)
Definition at line 1069 of file class-pclzip.php.
References PCLZIP_OPT_BY_INDEX.
duplicate ($p_archive)
Definition at line 1166 of file class-pclzip.php.
errorCode ()
Definition at line 1276 of file class-pclzip.php.
Referenced by privDeleteByRule(), and privDirCheck().
errorInfo ($p_full = false)
Definition at line 1338 of file class-pclzip.php.
errorName ($p_with_code = false)
Definition at line 1292 of file class-pclzip.php.
extract ()
Definition at line 704 of file class-pclzip.php.
References PCLZIP_CB_POST_EXTRACT, PCLZIP_CB_PRE_EXTRACT, PCLZIP_ERR_INVALID_PARAMETER, PCLZIP_OPT_ADD_PATH, PCLZIP_OPT_BY_EREG, PCLZIP_OPT_BY_INDEX, PCLZIP_OPT_BY_NAME, PCLZIP_OPT_BY_PREG, PCLZIP_OPT_EXTRACT_AS_STRING, PCLZIP_OPT_EXTRACT_DIR_RESTRICTION, PCLZIP_OPT_EXTRACT_IN_OUTPUT, PCLZIP_OPT_PATH, PCLZIP_OPT_REMOVE_ALL_PATH, PCLZIP_OPT_REMOVE_PATH, PCLZIP_OPT_REPLACE_NEWER, PCLZIP_OPT_SET_CHMOD, PCLZIP_OPT_STOP_ON_ERROR, PCLZIP_OPT_TEMP_FILE_OFF, PCLZIP_OPT_TEMP_FILE_ON, PCLZIP_OPT_TEMP_FILE_THRESHOLD, privCheckFormat(), privErrorLog(), privErrorReset(), privExtractByRule(), privOptionDefaultThreshold(), and privParseOptions().
extractByIndex ($p_index)
Definition at line 861 of file class-pclzip.php.
References PCLZIP_CB_POST_EXTRACT, PCLZIP_CB_PRE_EXTRACT, PCLZIP_ERR_INVALID_PARAMETER, PCLZIP_OPT_ADD_PATH, PCLZIP_OPT_BY_INDEX, PCLZIP_OPT_EXTRACT_AS_STRING, PCLZIP_OPT_EXTRACT_DIR_RESTRICTION, PCLZIP_OPT_PATH, PCLZIP_OPT_REMOVE_ALL_PATH, PCLZIP_OPT_REMOVE_PATH, PCLZIP_OPT_REPLACE_NEWER, PCLZIP_OPT_SET_CHMOD, PCLZIP_OPT_STOP_ON_ERROR, PCLZIP_OPT_TEMP_FILE_OFF, PCLZIP_OPT_TEMP_FILE_ON, PCLZIP_OPT_TEMP_FILE_THRESHOLD, privCheckFormat(), privErrorLog(), privErrorReset(), privExtractByRule(), privOptionDefaultThreshold(), and privParseOptions().
listContent ()
Definition at line 647 of file class-pclzip.php.
References privCheckFormat(), privErrorReset(), and privList().
merge ($p_archive_to_add)
Definition at line 1225 of file class-pclzip.php.
PclZip ($p_zipname)
Definition at line 233 of file class-pclzip.php.
Referenced by privDeleteByRule().
privAdd ($p_filedescr_list, & $p_result_list, & $p_options)
Definition at line 2163 of file class-pclzip.php.
Referenced by add().
privAddFile ($p_filedescr, & $p_header, & $p_options)
Definition at line 2529 of file class-pclzip.php.
privAddFileList ($p_filedescr_list, & $p_result_list, & $p_options)
Definition at line 2467 of file class-pclzip.php.
privAddFileUsingTempFile ($p_filedescr, & $p_header, & $p_options)
Definition at line 2800 of file class-pclzip.php.
privAddList ($p_filedescr_list, & $p_result_list, & $p_options)
Definition at line 2403 of file class-pclzip.php.
privCalculateStoredFilename (& $p_filedescr, & $p_options)
Definition at line 2912 of file class-pclzip.php.
privCheckFileHeaders (& $p_local_header, & $p_central_header)
Definition at line 4485 of file class-pclzip.php.
Referenced by privDeleteByRule().
privCheckFormat ($p_level = 0)
Definition at line 1377 of file class-pclzip.php.
Referenced by delete(), extract(), extractByIndex(), listContent(), and properties().
privCloseFd ()
Definition at line 2376 of file class-pclzip.php.
Referenced by privDeleteByRule(), and privMerge().
privConvertHeader2FileInfo ($p_header, & $p_info)
Definition at line 3238 of file class-pclzip.php.
privCreate ($p_filedescr_list, & $p_result_list, & $p_options)
Definition at line 2128 of file class-pclzip.php.
Referenced by create().
privDeleteByRule (& $p_result_list, & $p_options)
Definition at line 4679 of file class-pclzip.php.
References $i, elseif, errorCode(), PclZip(), PCLZIP_ERR_INVALID_ARCHIVE_ZIP, PCLZIP_OPT_BY_INDEX, PCLZIP_OPT_BY_NAME, PCLZIP_OPT_BY_PREG, PCLZIP_OPT_COMMENT, PclZipUtilCopyBlock(), PclZipUtilRename(), privCheckFileHeaders(), privCloseFd(), privErrorLog(), privOpenFd(), privReadCentralFileHeader(), privReadEndCentralDir(), privReadFileHeader(), and privWriteCentralHeader().
Referenced by delete().
privDirCheck ($p_dir, $p_is_dir = false)
Definition at line 4989 of file class-pclzip.php.
References errorCode(), PCLZIP_ERR_DIR_CREATE_FAIL, and privErrorLog().
privDisableMagicQuotes ()
Definition at line 5324 of file class-pclzip.php.
Referenced by delete(), and properties().
privDuplicate ($p_archive_filename)
Definition at line 5229 of file class-pclzip.php.
Referenced by privMerge().
privErrorLog ($p_error_code = 0, $p_error_string = '')
Definition at line 5289 of file class-pclzip.php.
Referenced by add(), create(), extract(), extractByIndex(), privDeleteByRule(), privDirCheck(), privMerge(), and properties().
privErrorReset ()
Definition at line 5306 of file class-pclzip.php.
Referenced by add(), create(), delete(), extract(), extractByIndex(), listContent(), and properties().
privExtractByRule (& $p_file_list, $p_path, $p_remove_path, $p_remove_all_path, & $p_options)
Definition at line 3277 of file class-pclzip.php.
Referenced by extract(), and extractByIndex().
privExtractFile (& $p_entry, $p_path, $p_remove_path, $p_remove_all_path, & $p_options)
Definition at line 3617 of file class-pclzip.php.
privExtractFileAsString (& $p_entry, & $p_string, & $p_options)
Definition at line 4153 of file class-pclzip.php.
privExtractFileInOutput (& $p_entry, & $p_options)
Definition at line 4042 of file class-pclzip.php.
privExtractFileUsingTempFile (& $p_entry, & $p_options)
Definition at line 3966 of file class-pclzip.php.
privFileDescrExpand (& $p_filedescr_list, & $p_options)
Definition at line 2003 of file class-pclzip.php.
Referenced by add(), and create().
privFileDescrParseAtt (& $p_file_list, & $p_filedescr, $v_options, $v_requested_options = false)
Definition at line 1874 of file class-pclzip.php.
Referenced by add(), and create().
privList (& $p_list)
Definition at line 3151 of file class-pclzip.php.
Referenced by listContent().
privMerge (& $p_archive_to_add)
Definition at line 5044 of file class-pclzip.php.
References comment, PCLZIP_ERR_READ_OPEN_FAIL, privCloseFd(), privDuplicate(), privErrorLog(), privOpenFd(), privReadEndCentralDir(), and size.
privOpenFd ($p_mode)
Definition at line 2342 of file class-pclzip.php.
Referenced by privDeleteByRule(), and privMerge().
privOptionDefaultThreshold (& $p_options)
Definition at line 1830 of file class-pclzip.php.
Referenced by add(), create(), extract(), and extractByIndex().
privParseOptions (& $p_options_list, $p_size, & $v_result_list, $v_requested_options = false)
Definition at line 1430 of file class-pclzip.php.
Referenced by add(), create(), delete(), extract(), and extractByIndex().
privReadCentralFileHeader (& $p_header)
Definition at line 4377 of file class-pclzip.php.
Referenced by privDeleteByRule().
privReadEndCentralDir (& $p_central_dir)
Definition at line 4522 of file class-pclzip.php.
Referenced by privDeleteByRule(), and privMerge().
privReadFileHeader (& $p_header)
Definition at line 4274 of file class-pclzip.php.
Referenced by privDeleteByRule().
privSwapBackMagicQuotes ()
Definition at line 5358 of file class-pclzip.php.
Referenced by delete(), and properties().
privWriteCentralFileHeader (& $p_header)
Definition at line 3069 of file class-pclzip.php.
privWriteCentralHeader ($p_nb_entries, $p_size, $p_offset, $p_comment)
Definition at line 3122 of file class-pclzip.php.
Referenced by privDeleteByRule().
privWriteFileHeader (& $p_header)
Definition at line 3024 of file class-pclzip.php.
properties ()
Definition at line 1093 of file class-pclzip.php.
References comment, PCLZIP_ERR_READ_OPEN_FAIL, privCheckFormat(), privDisableMagicQuotes(), privErrorLog(), privErrorReset(), and privSwapBackMagicQuotes().
Field Documentation
$error_code = 1
Definition at line 199 of file class-pclzip.php.
$error_string = ''
Definition at line 200 of file class-pclzip.php.
$magic_quotes_status
Definition at line 205 of file class-pclzip.php.
$zip_fd = 0
Definition at line 196 of file class-pclzip.php.
$zipname = ''
Definition at line 193 of file class-pclzip.php.
The documentation for this class was generated from the following file:
class-pclzip.php