GravityView: SMTP Class Reference
SMTP Class Reference
Public Member Functions
authenticate ($username, $password, $authtype=null, $realm= '', $workstation= '', $OAuth=null)
Perform SMTP authentication.
client_send ($data)
Send raw data to the server.
close ()
Close the socket and clean up the state of the class.
connect ($host, $port=null, $timeout=30, $options=array())
Connect to an SMTP server.
connected ()
Check connection state.
data ($msg_data)
Send an SMTP DATA command.
getDebugLevel ()
Get debug output level.
getDebugOutput ()
Get debug output method.
getError ()
Get the latest error.
getLastReply ()
Get the last reply from the server.
getServerExt ($name)
A multipurpose method The method works in three ways, dependent on argument value and current state.
getServerExtList ()
Get SMTP extensions available on the server public.
getTimeout ()
Get SMTP timeout.
getVerp ()
Get VERP address generation mode.
hello ($host= '')
Send an SMTP HELO or EHLO command.
mail ($from)
Send an SMTP MAIL command.
noop ()
Send an SMTP NOOP command.
quit ($close_on_error=true)
Send an SMTP QUIT command.
recipient ($address)
Send an SMTP RCPT command.
reset ()
Send an SMTP RSET command.
sendAndMail ($from)
Send an SMTP SAML command.
setDebugLevel ($level=0)
Set debug output level.
setDebugOutput ($method= 'echo')
Set debug output method.
setTimeout ($timeout=0)
Set SMTP timeout.
setVerp ($enabled=false)
Enable or disable VERP address generation.
startTLS ()
Initiate a TLS (encrypted) session.
turn ()
Send an SMTP TURN command.
verify ($name)
Send an SMTP VRFY command.
Data Fields
$CRLF = "\r\n"
$Debugoutput = 'echo'
$do_debug = self::DEBUG_OFF
$do_verp = false
$SMTP_PORT = 25
$Timelimit = 300
$Timeout = 300
$Version = '5.2.14'
const CRLF = "\r\n"
const DEBUG_CLIENT = 1
Debug level to show client -> server messages.
const DEBUG_CONNECTION = 3
Debug level to show connection status, client -> server and server -> client messages.
const DEBUG_LOWLEVEL = 4
Debug level to show all messages.
const DEBUG_OFF = 0
Debug level for no output.
const DEBUG_SERVER = 2
Debug level to show client -> server and server -> client messages.
const DEFAULT_SMTP_PORT = 25
const MAX_LINE_LENGTH = 998
const VERSION = '5.2.14'
Protected Member Functions
edebug ($str, $level=0)
Output debugging info via a user-selected method.
get_lines ()
Read the SMTP server's response.
hmac ($data, $key)
Calculate an MD5 HMAC hash.
parseHelloFields ($type)
Parse a reply to HELO/EHLO command to discover server extensions.
sendCommand ($command, $commandstring, $expect)
Send a command to an SMTP server and check its return code.
sendHello ($hello, $host)
Send an SMTP HELO or EHLO command.
setError ($message, $detail= '', $smtp_code= '', $smtp_code_ex= '')
Set error messages and codes.
Protected Attributes
$error
$helo_rply = null
$last_reply = ''
$server_caps = null
$smtp_conn
Detailed Description
Definition at line 27 of file class-smtp.php.
Member Function Documentation
authenticate ($username, $password, $authtype = null, $realm = '', $workstation = '', $OAuth = null)
Perform SMTP authentication.
Must be run after hello().
See also
hello()
Parameters
string $username The user name
string $password The password
string $authtype The auth type (PLAIN, LOGIN, NTLM, CRAM-MD5, XOAUTH2)
string $realm The auth realm for NTLM
string $workstation The auth workstation for NTLM
null | OAuth $OAuth An optional OAuth instance (
See also
PHPMailerOAuth)
Returns
bool True if successfully authenticated.* public
Definition at line 362 of file class-smtp.php.
References elseif, hmac(), sendCommand(), and setError().
client_send ($data)
Send raw data to the server.
Parameters
string $data The data to send public
Returns
integer|boolean The number of bytes sent to the server or false on error
Definition at line 901 of file class-smtp.php.
References edebug().
Referenced by data(), and sendCommand().
close ()
Close the socket and clean up the state of the class.
Don't use this function without first trying to use QUIT.
See also
quit() public
Returns
void
Definition at line 526 of file class-smtp.php.
References edebug(), null, and setError().
Referenced by connected(), and quit().
connect ($host, $port = null, $timeout = 30, $options = array())
Connect to an SMTP server.
Parameters
string $host SMTP server IP or host name
integer $port The port number to connect to
integer $timeout How long to wait for the connection to open
array $options An array of options for stream_context_create() public
Returns
boolean
Definition at line 247 of file class-smtp.php.
References $options, connected(), edebug(), get_lines(), and setError().
connected ()
Check connection state.
public
Returns
boolean True if connected.
Definition at line 501 of file class-smtp.php.
References close(), and edebug().
Referenced by connect(), and sendCommand().
data ($msg_data)
Send an SMTP DATA command.
Issues a data command and sends the msg_data to the server, finializing the mail transaction. $msg_data is the message that is to be send with the headers. Each header needs to be on a single line followed by a <CRLF> with the message headers and the message body being separated by and additional <CRLF>. Implements rfc 821: DATA <CRLF>
Parameters
string $msg_data Message data to send public
Returns
boolean
Definition at line 551 of file class-smtp.php.
References $field, $Timelimit, client_send(), sendCommand(), and str_replace.
edebug ($str, $level = 0) protected
Output debugging info via a user-selected method.
See also
SMTP::$Debugoutput
SMTP::$do_debug
Parameters
string $str Debug string to output
integer $level The debug level of this message; see DEBUG_* constants
Returns
void
Definition at line 202 of file class-smtp.php.
References str_replace.
Referenced by client_send(), close(), connect(), connected(), get_lines(), sendCommand(), and turn().
get_lines () protected
Read the SMTP server's response.
Either before eof or socket timeout occurs on the operation. With SMTP we can tell if we have more lines to read if the 4th character is '-' symbol. If it is a space then we don't need to read anything else. protected
Returns
string
Definition at line 987 of file class-smtp.php.
References $Timelimit, and edebug().
Referenced by connect(), and sendCommand().
getDebugLevel ()
Get debug output level.
Returns
integer
Definition at line 1096 of file class-smtp.php.
References $do_debug.
getDebugOutput ()
Get debug output method.
Returns
string
Definition at line 1078 of file class-smtp.php.
References $Debugoutput.
getError ()
Get the latest error.
public
Returns
array
Definition at line 912 of file class-smtp.php.
References $error.
getLastReply ()
Get the last reply from the server.
public
Returns
string
Definition at line 973 of file class-smtp.php.
References $last_reply.
getServerExt ($name)
A multipurpose method The method works in three ways, dependent on argument value and current state.
HELO/EHLO was not sent - returns null and set up $this->error
HELO was sent $name = 'HELO': returns server name $name = 'EHLO': returns boolean false $name = any string: returns null and set up $this->error
EHLO was sent $name = 'HELO'|'EHLO': returns server name $name = any string: if extension $name exists, returns boolean True or its options. Otherwise returns boolean False In other words, one can use this method to detect 3 conditions:
null returned: handshake was not or we don't know about ext (refer to $this->error)
false returned: the requested feature exactly not exists
positive value returned: the requested feature exists
Parameters
string $name Name of SMTP extension or 'HELO'|'EHLO'
Returns
mixed
Definition at line 946 of file class-smtp.php.
References $name, null, and setError().
getServerExtList ()
Get SMTP extensions available on the server public.
Returns
array|null
Definition at line 922 of file class-smtp.php.
References $server_caps.
getTimeout ()
Get SMTP timeout.
Returns
integer
Definition at line 1114 of file class-smtp.php.
References $Timeout.
getVerp ()
Get VERP address generation mode.
Returns
boolean
Definition at line 1043 of file class-smtp.php.
References $do_verp.
hello ($host = '')
Send an SMTP HELO or EHLO command.
Used to identify the sending server to the receiving server. This makes sure that client and server are in a known state. Implements RFC 821: HELO <SP> <domain> <CRLF> and RFC 2821 EHLO.
Parameters
string $host The host name or IP to connect to public
Returns
boolean
Definition at line 640 of file class-smtp.php.
References sendHello().
hmac ($data, $key) protected
Calculate an MD5 HMAC hash.
Works like hash_hmac('md5', $data, $key) in case that function is not available
Parameters
string $data The data to hash
string $key The key to hash with protected
Returns
string
Definition at line 469 of file class-smtp.php.
Referenced by authenticate().
mail ($from)
Send an SMTP MAIL command.
Starts a mail transaction from the email address specified in $from. Returns true if successful or false otherwise. If True the mail transaction is started and then one or more recipient commands may be called followed by a data command. Implements rfc 821: MAIL <SP> FROM:<reverse-path> <CRLF>
Parameters
string $from Source address of this message public
Returns
boolean
Definition at line 720 of file class-smtp.php.
References $from, and sendCommand().
noop ()
Send an SMTP NOOP command.
Used to keep keep-alives alive, doesn't actually do anything public
Returns
boolean
Definition at line 874 of file class-smtp.php.
References sendCommand().
parseHelloFields ($type) protected
Parse a reply to HELO/EHLO command to discover server extensions.
In case of HELO, the only parameter that can be discovered is a server name. protected
Parameters
string $type - 'HELO' or 'EHLO'
Definition at line 673 of file class-smtp.php.
References $name, and $s.
Referenced by sendHello().
quit ($close_on_error = true)
Send an SMTP QUIT command.
Closes the socket if there is no error or the $close_on_error argument is true. Implements from rfc 821: QUIT <CRLF>
Parameters
boolean $close_on_error Should the connection close if an error occurs? public
Returns
boolean
Definition at line 738 of file class-smtp.php.
References $error, close(), and sendCommand().
recipient ($address)
Send an SMTP RCPT command.
Sets the TO argument to $toaddr. Returns true if the recipient was accepted false if it was rejected. Implements from rfc 821: RCPT <SP> TO:<forward-path> <CRLF>
Parameters
string $address The address the message is being sent to public
Returns
boolean
Definition at line 758 of file class-smtp.php.
References sendCommand().
reset ()
Send an SMTP RSET command.
Abort any transaction that is currently in progress. Implements rfc 821: RSET <CRLF> public
Returns
boolean True on success.
Definition at line 774 of file class-smtp.php.
References sendCommand().
sendAndMail ($from)
Send an SMTP SAML command.
Starts a mail transaction from the email address specified in $from. Returns true if successful or false otherwise. If True the mail transaction is started and then one or more recipient commands may be called followed by a data command. This command will send the message to the users terminal if they are logged in and send them an email. Implements rfc 821: SAML <SP> FROM:<reverse-path> <CRLF>
Parameters
string $from The address the message is from public
Returns
boolean
Definition at line 852 of file class-smtp.php.
References sendCommand().
sendCommand ($command, $commandstring, $expect) protected
Send a command to an SMTP server and check its return code.
Parameters
string $command The command name - not sent to the server
string $commandstring The actual command to send
integer | array $expect One or more expected integer success codes protected
Returns
boolean True on success.
Definition at line 787 of file class-smtp.php.
References client_send(), connected(), edebug(), get_lines(), null, setError(), and str_replace.
Referenced by authenticate(), data(), mail(), noop(), quit(), recipient(), reset(), sendAndMail(), sendHello(), startTLS(), and verify().
sendHello ($hello, $host) protected
Send an SMTP HELO or EHLO command.
Low-level implementation used by hello()
See also
hello()
Parameters
string $hello The HELO string
string $host The hostname to say we are protected
Returns
boolean
Definition at line 655 of file class-smtp.php.
References $last_reply, null, parseHelloFields(), and sendCommand().
Referenced by hello().
setDebugLevel ($level = 0)
Set debug output level.
Parameters
integer $level
Definition at line 1087 of file class-smtp.php.
setDebugOutput ($method = 'echo')
Set debug output method.
Parameters
string | callable $method The name of the mechanism to use for debugging output, or a callable to handle it.
Definition at line 1069 of file class-smtp.php.
setError ($message, $detail = '', $smtp_code = '', $smtp_code_ex = '') protected
Set error messages and codes.
Parameters
string $message The error message
string $detail Further detail on the error
string $smtp_code An associated SMTP error code
string $smtp_code_ex Extended SMTP code
Definition at line 1055 of file class-smtp.php.
References $message.
Referenced by authenticate(), close(), connect(), getServerExt(), sendCommand(), and turn().
setTimeout ($timeout = 0)
Set SMTP timeout.
Parameters
integer $timeout
Definition at line 1105 of file class-smtp.php.
setVerp ($enabled = false)
Enable or disable VERP address generation.
Parameters
boolean $enabled
Definition at line 1034 of file class-smtp.php.
startTLS ()
Initiate a TLS (encrypted) session.
public
Returns
boolean
Definition at line 334 of file class-smtp.php.
References sendCommand().
turn ()
Send an SMTP TURN command.
This is an optional command for SMTP that this class does not support. This method is here to make the RFC821 Definition complete for this class and may be implemented in future Implements from rfc 821: TURN <CRLF> public
Returns
boolean
Definition at line 888 of file class-smtp.php.
References edebug(), and setError().
verify ($name)
Send an SMTP VRFY command.
Parameters
string $name The name to verify public
Returns
boolean
Definition at line 863 of file class-smtp.php.
References sendCommand().
Field Documentation
$CRLF = "\r\n"
Definition at line 100 of file class-smtp.php.
$Debugoutput = 'echo'
Definition at line 127 of file class-smtp.php.
Referenced by getDebugOutput().
$do_debug = self::DEBUG_OFF
Definition at line 112 of file class-smtp.php.
Referenced by getDebugLevel().
$do_verp = false
Definition at line 135 of file class-smtp.php.
Referenced by getVerp().
$error protected
Initial value:
= array(
        'error' => '',
        'detail' => '',
        'smtp_code' => '',
        'smtp_code_ex' => ''
    )
Definition at line 163 of file class-smtp.php.
Referenced by getError(), and quit().
$helo_rply = null protected
Definition at line 175 of file class-smtp.php.
$last_reply = '' protected
Definition at line 192 of file class-smtp.php.
Referenced by getLastReply(), and sendHello().
$server_caps = null protected
Definition at line 186 of file class-smtp.php.
Referenced by getServerExtList().
$smtp_conn protected
Definition at line 157 of file class-smtp.php.
$SMTP_PORT = 25
Definition at line 92 of file class-smtp.php.
$Timelimit = 300
Definition at line 151 of file class-smtp.php.
Referenced by data(), and get_lines().
$Timeout = 300
Definition at line 144 of file class-smtp.php.
Referenced by getTimeout().
$Version = '5.2.14'
Definition at line 84 of file class-smtp.php.
const CRLF = "\r\n"
Definition at line 39 of file class-smtp.php.
const DEBUG_CLIENT = 1
Debug level to show client -> server messages.
Definition at line 61 of file class-smtp.php.
const DEBUG_CONNECTION = 3
Debug level to show connection status, client -> server and server -> client messages.
Definition at line 71 of file class-smtp.php.
const DEBUG_LOWLEVEL = 4
Debug level to show all messages.
Definition at line 76 of file class-smtp.php.
const DEBUG_OFF = 0
Debug level for no output.
Definition at line 56 of file class-smtp.php.
const DEBUG_SERVER = 2
Debug level to show client -> server and server -> client messages.
Definition at line 66 of file class-smtp.php.
const DEFAULT_SMTP_PORT = 25
Definition at line 45 of file class-smtp.php.
const MAX_LINE_LENGTH = 998
Definition at line 51 of file class-smtp.php.
const VERSION = '5.2.14'
Definition at line 33 of file class-smtp.php.
The documentation for this class was generated from the following file:
class-smtp.php