GravityView: GFFormList Class Reference
GFFormList Class Reference
Static Public Member Functions
static form_list_page ()
Data Fields
overflow __pad0__: hidden
body height: 290px !important
Detailed Description
Definition at line 7 of file form_list.php.
Member Function Documentation
static form_list_page () static
Definition at line 9 of file form_list.php.
References $action, $form_id, $forms, $message, $min, $wpdb, __, _n(), add_action(), GFFormsModel\delete_form(), GFFormsModel\delete_forms(), GFFormsModel\delete_leads_by_form(), GFFormsModel\delete_views(), GFFormsModel\duplicate_form(), GFForms\get(), GFFormsModel\get_form_count(), GFFormsModel\get_form_db_columns(), GFFormsModel\get_forms(), height, margin, null, GFForms\post(), GFFormsModel\restore_form(), GFFormsModel\restore_forms(), GFFormsModel\trash_form(), GFFormsModel\trash_forms(), GFFormsModel\update_form_active(), width, and wp_print_styles().
Referenced by GFForms\form_list_page().
Field Documentation
overflow __pad0__
Definition at line 142 of file form_list.php.
body height
Definition at line 141 of file form_list.php.
Referenced by form_list_page().
The documentation for this class was generated from the following file:
form_list.php