GravityView: WP_Canonical_UnitTestCase Class Reference
WP_Canonical_UnitTestCase Class Reference
Public Member Functions
assertCanonical ($test_url, $expected, $ticket=0, $expected_doing_it_wrong=array())
Assert that a given URL is the same a the canonical URL generated by WP.
get_canonical ($test_url)
Get the canonical URL given a raw URL.
setUp ()
Public Member Functions inherited from WP_UnitTestCase
__get ($name)
__isset ($name)
_create_temporary_tables ($query)
_drop_temporary_tables ($query)
_make_attachment ($upload, $parent_post_id=0)
assertDiscardWhitespace ($expected, $actual)
assertEqualFields ($object, $fields)
assertEqualSets ($expected, $actual)
assertEqualSetsWithIndex ($expected, $actual)
assertNotWPError ($actual, $message= '')
assertQueryTrue ()
Check each of the WP_Query is_* functions/properties against expected boolean value.
assertWPError ($actual, $message= '')
clean_up_global_scope ()
delete_folders ($path)
deprecated_function_run ($function)
doing_it_wrong_run ($function)
expectDeprecated ()
expectedDeprecated ()
files_in_dir ($dir)
flush_cache ()
get_wp_die_handler ($handler)
go_to ($url)
knownPluginBug ($ticket_id)
Skips the current test if there is an open plugin ticket with id $ticket_id.
knownUTBug ($ticket_id)
Skips the current test if there is an open unit tests ticket with id $ticket_id.
knownWPBug ($ticket_id)
Skips the current test if there is an open WordPress ticket with id $ticket_id.
prepareTemplate (Text_Template $template)
Define constants after including files.
remove_added_uploads ()
rmdir ($path)
scan_user_uploads ()
scandir ($dir)
set_permalink_structure ($structure= '')
Utility method that resets permalinks and flushes rewrites.
setExpectedDeprecated ($deprecated)
Declare an expected _deprecated_function() or _deprecated_argument() call from within a test.
setExpectedIncorrectUsage ($doing_it_wrong)
Declare an expected _doing_it_wrong() call from within a test.
setUp ()
start_transaction ()
tearDown ()
temp_filename ()
Returns the name of a temporary file.
unlink ($file)
wp_die_handler ($message)
Static Public Member Functions
static delete_shared_fixtures ()
Clean up shared fixtures.
static generate_shared_fixtures ($factory)
Generate fixtures to be shared between canonical tests.
Static Public Member Functions inherited from WP_UnitTestCase
static commit_transaction ()
Commit the queries in a transaction.
static delete_user ($user_id)
Multisite-agnostic way to delete a user from the database.
static forceTicket ($ticket)
static get_called_class ()
static setUpBeforeClass ()
static tearDownAfterClass ()
Data Fields
$structure = '/%year%/%monthnum%/%day%/%postname%/'
This can be defined in a subclass of this class which contains its own data() method.
Static Public Attributes
static $author_id
static $comment_ids = array()
static $old_current_user
static $old_options = array()
static $post_ids = array()
static $term_ids = array()
static $terms = array()
Additional Inherited Members
Protected Member Functions inherited from WP_UnitTestCase
_backup_hooks ()
Saves the action and filter-related globals so they can be restored later.
_microtime_to_float ($microtime)
Helper to Convert a microtime string into a float.
_restore_hooks ()
Restores the hook-related globals to their state at setUp() so that future tests aren't affected by hooks set during this last test.
assertPostConditions ()
Detect post-test failure conditions.
checkRequirements ()
reset_post_statuses ()
Unregister non-built-in post statuses.
reset_post_types ()
Unregister existing post types and register defaults.
reset_taxonomies ()
Unregister existing taxonomies and register defaults.
Static Protected Member Functions inherited from WP_UnitTestCase
static factory ()
Protected Attributes inherited from WP_UnitTestCase
$caught_deprecated = array()
$caught_doing_it_wrong = array()
$expected_deprecated = array()
$expected_doing_it_wrong = array()
Static Protected Attributes inherited from WP_UnitTestCase
static $forced_tickets = array()
static $hooks_saved = array()
static $ignore_files
Detailed Description
Definition at line 3 of file testcase-canonical.php.
Member Function Documentation
assertCanonical ($test_url, $expected, $ticket = 0, $expected_doing_it_wrong = array())
Assert that a given URL is the same a the canonical URL generated by WP.
Since
4.1.0
Parameters
string $test_url Raw URL that will be run through redirect_canonical().
string $expected Expected string.
int $ticket Optional. Trac ticket number.
array $expected_doing_it_wrong Array of class/function names expected to throw _doing_it_wrong() notices.
Definition at line 168 of file testcase-canonical.php.
References WP_UnitTestCase\$expected_doing_it_wrong, $wp, elseif, get_canonical(), WP_UnitTestCase\go_to(), home_url(), WP_UnitTestCase\knownWPBug(), and null.
static delete_shared_fixtures () static
Clean up shared fixtures.
Since
4.1.0
Definition at line 136 of file testcase-canonical.php.
References $tax, null, wp_delete_comment(), wp_delete_post(), and wp_delete_term().
static generate_shared_fixtures ($factory) static
Generate fixtures to be shared between canonical tests.
Abstracted here because it's invoked by setUpBeforeClass() in more than one class.
Since
4.1.0
Definition at line 41 of file testcase-canonical.php.
References $post_id, and get_current_user_id().
get_canonical ($test_url)
Get the canonical URL given a raw URL.
Parameters
string $test_url Should be relative to the site "front", ie /category/uncategorized/ as opposed to http://example.com/category/uncategorized/
Returns
$can_url Returns the original $test_url if no canonical can be generated, otherwise returns the fully-qualified URL as generated by redirect_canonical().
Definition at line 225 of file testcase-canonical.php.
References home_url(), and redirect_canonical().
Referenced by assertCanonical().
setUp ()
Definition at line 18 of file testcase-canonical.php.
References $wp_rewrite, create_initial_taxonomies(), and update_option().
Field Documentation
$author_id static
Definition at line 5 of file testcase-canonical.php.
$comment_ids = array() static
Definition at line 7 of file testcase-canonical.php.
$old_current_user static
Definition at line 4 of file testcase-canonical.php.
$old_options = array() static
Definition at line 10 of file testcase-canonical.php.
$post_ids = array() static
Definition at line 6 of file testcase-canonical.php.
$structure = '/%year%/%monthnum%/%day%/%postname%/'
This can be defined in a subclass of this class which contains its own data() method.
Those tests will be run against the specified permastruct.
Definition at line 16 of file testcase-canonical.php.
$term_ids = array() static
Definition at line 8 of file testcase-canonical.php.
$terms = array() static
Definition at line 9 of file testcase-canonical.php.
The documentation for this class was generated from the following file:
testcase-canonical.php