GravityView: Gettext_Translations Class Reference
Gettext_Translations Class Reference
Public Member Functions
gettext_select_plural_form ($count)
The gettext implementation of select_plural_form.
make_headers ($translation)
make_plural_form_function ($nplurals, $expression)
Makes a function, which will return the right translation index, according to the plural forms header.
nplurals_and_expression_from_header ($header)
parenthesize_plural_exression ($expression)
Adds parentheses to the inner parts of ternary operators in plural expressions, because PHP evaluates ternary oerators from left to right.
set_header ($header, $value)
Detailed Description
Definition at line 165 of file translations.php.
Member Function Documentation
gettext_select_plural_form ($count)
The gettext implementation of select_plural_form.
It lives in this class, because there are more than one descendand, which will use it and they can't share it effectively.
Parameters
int $count
Definition at line 174 of file translations.php.
References $count, get_header(), make_plural_form_function(), and nplurals_and_expression_from_header().
make_headers ($translation)
Parameters
string $translation
Returns
array
Definition at line 247 of file translations.php.
References str_replace.
make_plural_form_function ($nplurals, $expression)
Makes a function, which will return the right translation index, according to the plural forms header.
Parameters
int $nplurals
string $expression
Definition at line 203 of file translations.php.
References str_replace.
Referenced by gettext_select_plural_form(), and set_header().
nplurals_and_expression_from_header ($header)
Parameters
string $header
Returns
array
Definition at line 187 of file translations.php.
References parenthesize_plural_exression().
Referenced by gettext_select_plural_form(), and set_header().
parenthesize_plural_exression ($expression)
Adds parentheses to the inner parts of ternary operators in plural expressions, because PHP evaluates ternary oerators from left to right.
Parameters
string $expression the expression without parentheses
Returns
string the expression with parentheses added
Definition at line 218 of file translations.php.
References $i.
Referenced by nplurals_and_expression_from_header().
set_header ($header, $value)
Parameters
string $header
string $value
Definition at line 264 of file translations.php.
References $value, get_header(), make_plural_form_function(), and nplurals_and_expression_from_header().
The documentation for this class was generated from the following file:
translations.php