GravityView: SimplePie_Locator Class Reference
SimplePie_Locator Class Reference
Public Member Functions
__construct (SimplePie_File $file, $timeout=10, $useragent=null, $max_checked_feeds=10)
autodiscovery ()
body (&$array)
extension (&$array)
find ($type=SIMPLEPIE_LOCATOR_ALL, &$working)
get_base ()
get_links ()
is_feed ($file)
set_registry (SimplePie_Registry $registry)
Data Fields
$base
$base_location = 0
$cached_entities = array()
$checked_feeds = 0
$elsewhere = array()
$file
$http_base
$local = array()
$max_checked_feeds = 10
$timeout
$useragent
Protected Member Functions
search_elements_by_tag ($name, &$done, $feeds)
Protected Attributes
$registry
Detailed Description
Definition at line 53 of file Locator.php.
Constructor & Destructor Documentation
__construct (SimplePie_File $file, $timeout = 10, $useragent = null, $max_checked_feeds = 10)
Definition at line 68 of file Locator.php.
References $file, $max_checked_feeds, $timeout, $useragent, and null.
Member Function Documentation
autodiscovery ()
Definition at line 195 of file Locator.php.
References null, and search_elements_by_tag().
Referenced by find().
body (& $array)
Definition at line 344 of file Locator.php.
References $value, null, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Referenced by find().
extension (& $array)
Definition at line 315 of file Locator.php.
References $value, null, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Referenced by find().
find ($type = SIMPLEPIE_LOCATOR_ALL, & $working)
Definition at line 94 of file Locator.php.
References $file, autodiscovery(), body(), elsewhere, extension(), get_base(), get_links(), is_feed(), null, SIMPLEPIE_FILE_SOURCE_REMOTE, SIMPLEPIE_LOCATOR_AUTODISCOVERY, SIMPLEPIE_LOCATOR_LOCAL_BODY, SIMPLEPIE_LOCATOR_LOCAL_EXTENSION, SIMPLEPIE_LOCATOR_NONE, SIMPLEPIE_LOCATOR_REMOTE_BODY, and SIMPLEPIE_LOCATOR_REMOTE_EXTENSION.
get_base ()
Definition at line 170 of file Locator.php.
References $base, $http_base, and null.
Referenced by find().
get_links ()
Definition at line 264 of file Locator.php.
References $href, $link, elsewhere, and null.
Referenced by find().
is_feed ($file)
Definition at line 145 of file Locator.php.
References elseif, SIMPLEPIE_FILE_SOURCE_LOCAL, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Referenced by find().
search_elements_by_tag ($name, & $done, $feeds) protected
Definition at line 213 of file Locator.php.
References $href, $link, $name, null, and SIMPLEPIE_FILE_SOURCE_REMOTE.
Referenced by autodiscovery().
set_registry (SimplePie_Registry $registry)
Definition at line 89 of file Locator.php.
References $registry.
Field Documentation
$base
Definition at line 62 of file Locator.php.
Referenced by get_base().
$base_location = 0
Definition at line 63 of file Locator.php.
$cached_entities = array()
Definition at line 60 of file Locator.php.
$checked_feeds = 0
Definition at line 64 of file Locator.php.
$elsewhere = array()
Definition at line 59 of file Locator.php.
$file
Definition at line 57 of file Locator.php.
Referenced by __construct(), and find().
$http_base
Definition at line 61 of file Locator.php.
Referenced by get_base().
$local = array()
Definition at line 58 of file Locator.php.
$max_checked_feeds = 10
Definition at line 65 of file Locator.php.
Referenced by __construct().
$registry protected
Definition at line 66 of file Locator.php.
Referenced by set_registry().
$timeout
Definition at line 56 of file Locator.php.
Referenced by __construct().
$useragent
Definition at line 55 of file Locator.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
Locator.php