GravityView: GFSettings Class Reference
GFSettings Class Reference
Static Public Member Functions
static action_delete_option_rg_gforms_key ()
static add_settings_page ($name, $handler, $icon_path)
static filter_pre_update_option_rg_gforms_key ($value, $old_value)
static get_posted_akismet_setting ()
static get_subview ()
static gravityforms_settings_page ()
static page_footer ()
static page_header ($title= '', $message= '')
static settings_page ()
static settings_uninstall_page ()
static upgrade_license ()
Static Public Attributes
static $addon_pages = array()
Detailed Description
Definition at line 7 of file gravityforms/settings.php.
Member Function Documentation
static action_delete_option_rg_gforms_key () static
Definition at line 644 of file gravityforms/settings.php.
References gapi(), and GFForms\include_gravity_api().
static add_settings_page ($name, $handler, $icon_path) static
Definition at line 11 of file gravityforms/settings.php.
References $name, $title, add_action(), str_replace, and wp_parse_args().
Referenced by GFForms\add_settings_page().
static filter_pre_update_option_rg_gforms_key ($value, $old_value) static
Definition at line 652 of file gravityforms/settings.php.
References $value, gapi(), and GFForms\include_gravity_api().
static get_posted_akismet_setting () static
Definition at line 629 of file gravityforms/settings.php.
References elseif.
static get_subview () static
Definition at line 617 of file gravityforms/settings.php.
static gravityforms_settings_page () static
Filters through and allows modification of the Settings save button HTML for the overall Gravity Forms Settings
Parameters
string $save_button The HTML rendered for the save button
Definition at line 146 of file gravityforms/settings.php.
static page_footer () static
Definition at line 594 of file gravityforms/settings.php.
References height.
static page_header ($title = '', $message = '') static
Definition at line 522 of file gravityforms/settings.php.
References $message, $min, $name, $title, __, apply_filters(), esc_html, li, wp_print_styles(), and wp_register_style().
static settings_page () static
Fires in the settings page depending on which page of the settings page you are in (the Subview)
Parameters
mixed $subview The sub-section of the main Form's settings
Definition at line 40 of file gravityforms/settings.php.
References do_action(), page_footer(), page_header(), and str_replace.
Referenced by GFForms\settings_page().
static settings_uninstall_page () static
Allows for the modification of the Gravity Forms uninstall button
Parameters
string $uninstall_button The HTML of the uninstall button
Definition at line 64 of file gravityforms/settings.php.
References $plugin, __, deactivate_plugins(), delete_option(), GFFormsModel\drop_tables(), esc_attr__(), esc_html__(), esc_html_e, esc_js(), gapi(), get_option(), GFFormsModel\get_upload_root(), GFForms\include_gravity_api(), is_multisite(), is_super_admin(), page_header(), and update_option().
static upgrade_license () static
Definition at line 493 of file gravityforms/settings.php.
References $message.
Referenced by GFForms\upgrade_license().
Field Documentation
$addon_pages = array() static
Definition at line 9 of file gravityforms/settings.php.
The documentation for this class was generated from the following file:
gravityforms/settings.php