GravityView: Custom_Image_Header Class Reference
Custom_Image_Header Class Reference
Public Member Functions
__construct ($admin_header_callback, $admin_image_div_callback= '')
Constructor - Register administration header callback.
admin_page ()
Display the page based on the current step.
ajax_header_add ()
Given an attachment ID for a header image, updates its "last used" timestamp to now.
ajax_header_crop ()
Gets attachment uploaded by Media Manager, crops it, then saves it as a new object.
ajax_header_remove ()
Given an attachment ID for a header image, unsets it as a user-uploaded header image for the current theme.
attachment_fields_to_edit ($form_fields)
Unused since 3.5.0.
create_attachment_object ($cropped, $parent_attachment_id)
Create an attachment 'object'.
css_includes ()
Set up the enqueue for the CSS files.
customize_set_last_used ($wp_customize)
filter_upload_tabs ($tabs)
Unused since 3.5.0.
finished ()
Display last step of custom header image page.
get_default_header_images ()
get_header_dimensions ($dimensions)
Calculate width and height based on what the currently selected theme supports.
get_uploaded_header_images ()
help ()
Adds contextual help.
init ()
Set up the hooks for the Custom Header admin page.
insert_attachment ($object, $cropped)
Insert an attachment and its metadata.
js ()
Execute JavaScript depending on step.
js_1 ()
Display JavaScript based on Step 1 and 3.
js_2 ()
Display JavaScript based on Step 2.
js_includes ()
Set up the enqueue for the JavaScript files.
process_default_headers ()
Process the default headers.
remove_header_image ()
Remove a header image.
reset_header_image ()
Reset a header image to the default image for the theme.
set_header_image ($choice)
Choose a header image, selected from existing uploaded and default headers, or provide an array of uploaded header data (either new, or from media library).
show_header_selector ($type= 'default')
Display UI for selecting one of several default headers.
step ()
Get the current step.
step_1 ()
Display first step of custom header image page.
step_2 ()
Display second step of custom header image page.
step_2_manage_upload ()
Upload the file to be cropped in the second step.
step_3 ()
Display third step of custom header image page.
take_action ()
Execute custom header modification.
Data Fields
$admin_header_callback
$admin_image_div_callback
$default_headers = array()
Private Attributes
$updated
Detailed Description
Definition at line 16 of file wp-admin/custom-header.php.
Constructor & Destructor Documentation
__construct ($admin_header_callback, $admin_image_div_callback = '')
Constructor - Register administration header callback.
Since
2.1.0
Parameters
callable $admin_header_callback
callable $admin_image_div_callback Optional custom image div output callback.
Definition at line 59 of file wp-admin/custom-header.php.
References $admin_header_callback, $admin_image_div_callback, and add_action().
Member Function Documentation
admin_page ()
Display the page based on the current step.
Since
2.1.0
Definition at line 935 of file wp-admin/custom-header.php.
References $step, __, current_user_can(), elseif, step(), step_1(), step_2(), step_3(), and wp_die().
ajax_header_add ()
Given an attachment ID for a header image, updates its "last used" timestamp to now.
Triggered when the user tries adds a new header image from the Media Manager, even if s/he doesn't save that change.
Definition at line 1229 of file wp-admin/custom-header.php.
References absint(), current_user_can(), get_stylesheet(), update_post_meta(), wp_send_json_error(), and wp_send_json_success().
ajax_header_crop ()
Gets attachment uploaded by Media Manager, crops it, then saves it as a new object.
Returns JSON-encoded object details.
This filter is documented in wp-admin/custom-header.php
Definition at line 1171 of file wp-admin/custom-header.php.
References __, absint(), apply_filters(), create_attachment_object(), current_theme_supports(), current_user_can(), get_header_dimensions(), insert_attachment(), is_wp_error(), wp_crop_image(), wp_get_attachment_url(), wp_send_json_error(), and wp_send_json_success().
ajax_header_remove ()
Given an attachment ID for a header image, unsets it as a user-uploaded header image for the current theme.
Triggered when the user clicks the overlay "X" button next to each image choice in the Customizer's Header tool.
Definition at line 1255 of file wp-admin/custom-header.php.
References absint(), current_user_can(), delete_post_meta(), get_stylesheet(), wp_send_json_error(), and wp_send_json_success().
attachment_fields_to_edit ($form_fields)
Unused since 3.5.0.
Since
3.4.0
Parameters
array $form_fields
Returns
array $form_fields
Definition at line 955 of file wp-admin/custom-header.php.
create_attachment_object ($cropped, $parent_attachment_id) final
Create an attachment 'object'.
Parameters
string $cropped Cropped image URL.
int $parent_attachment_id Attachment ID of parent image.
Returns
array Attachment object.
Definition at line 1123 of file wp-admin/custom-header.php.
References $size, $url, get_post(), str_replace, and wp_get_attachment_url().
Referenced by ajax_header_crop(), and step_3().
css_includes ()
Set up the enqueue for the CSS files.
Since
2.7.0
Definition at line 176 of file wp-admin/custom-header.php.
References $step, current_theme_supports(), elseif, step(), and wp_enqueue_style().
customize_set_last_used ($wp_customize)
Parameters
WP_Customize_Manager $wp_customize
Definition at line 1278 of file wp-admin/custom-header.php.
References $wp_customize, get_stylesheet(), and update_post_meta().
filter_upload_tabs ($tabs)
Unused since 3.5.0.
Since
3.4.0
Parameters
array $tabs
Returns
array $tabs
Definition at line 967 of file wp-admin/custom-header.php.
References $tabs.
finished ()
Display last step of custom header image page.
Since
2.1.0
Definition at line 925 of file wp-admin/custom-header.php.
References step_1().
Referenced by step_2(), and step_3().
get_default_header_images ()
Returns
array
Definition at line 1294 of file wp-admin/custom-header.php.
References $default, $default_headers, get_stylesheet_directory_uri(), get_template_directory_uri(), get_theme_support(), and process_default_headers().
get_header_dimensions ($dimensions) final
Calculate width and height based on what the currently selected theme supports.
Parameters
array $dimensions
Returns
array dst_height and dst_width of header image.
Definition at line 1071 of file wp-admin/custom-header.php.
References absint(), current_theme_supports(), elseif, get_theme_support(), and null.
Referenced by ajax_header_crop(), and step_3().
get_uploaded_header_images ()
Returns
array
Definition at line 1334 of file wp-admin/custom-header.php.
References $header_image, get_post_meta(), and get_stylesheet().
Referenced by set_header_image(), show_header_selector(), and step_1().
help ()
Adds contextual help.
Since
3.0.0
Definition at line 97 of file wp-admin/custom-header.php.
References __, admin_url(), and get_current_screen().
init ()
Set up the hooks for the Custom Header admin page.
Since
2.1.0
Definition at line 76 of file wp-admin/custom-header.php.
References $page, __, add_action(), and add_theme_page().
insert_attachment ($object, $cropped) final
Insert an attachment and its metadata.
Parameters
array $object Attachment object.
string $cropped Cropped image URL.
Returns
int Attachment ID.
Filter the header image attachment metadata.
Since
3.9.0
See also
wp_generate_attachment_metadata()
Parameters
array $metadata Attachment metadata.
Definition at line 1150 of file wp-admin/custom-header.php.
References $metadata, apply_filters(), wp_generate_attachment_metadata(), wp_insert_attachment(), and wp_update_attachment_metadata().
Referenced by ajax_header_crop(), and step_3().
js ()
Execute JavaScript depending on step.
Since
2.1.0
Definition at line 305 of file wp-admin/custom-header.php.
References $step, current_theme_supports(), elseif, js_1(), js_2(), and step().
js_1 ()
Display JavaScript based on Step 1 and 3.
Since
2.6.0
Definition at line 318 of file wp-admin/custom-header.php.
References checked(), color, current_theme_supports(), display_header_text(), endif, and get_theme_support().
Referenced by js().
js_2 ()
Display JavaScript based on Step 2.
Since
2.6.0
Definition at line 379 of file wp-admin/custom-header.php.
References absint(), current_theme_supports(), and get_theme_support().
Referenced by js().
js_includes ()
Set up the enqueue for the JavaScript files.
Since
2.1.0
Definition at line 158 of file wp-admin/custom-header.php.
References $step, current_theme_supports(), elseif, step(), wp_enqueue_media(), and wp_enqueue_script().
process_default_headers ()
Process the default headers.
Since
3.0.0
array $_wp_default_headers
Definition at line 238 of file wp-admin/custom-header.php.
References get_stylesheet_directory_uri(), and get_template_directory_uri().
Referenced by get_default_header_images(), reset_header_image(), set_header_image(), and step_1().
remove_header_image () final
Remove a header image.
Since
3.4.0
Definition at line 1032 of file wp-admin/custom-header.php.
References set_header_image().
Referenced by reset_header_image(), and take_action().
reset_header_image () final
Reset a header image to the default image for the theme.
This method does not do anything if the theme does not have a default header image.
Since
3.4.0
Definition at line 1043 of file wp-admin/custom-header.php.
References $default, $details, get_stylesheet_directory_uri(), get_template_directory_uri(), get_theme_support(), process_default_headers(), remove_header_image(), and set_theme_mod().
Referenced by take_action().
set_header_image ($choice) final
Choose a header image, selected from existing uploaded and default headers, or provide an array of uploaded header data (either new, or from media library).
Since
3.4.0
Parameters
mixed $choice Which header image to select. Allows for values of 'random-default-image', for randomly cycling among the default images; 'random-uploaded-image', for randomly cycling among the uploaded images; the key of a default image registered for that theme; and the key of an image uploaded for that theme (the basename of the URL). Or an array of arguments: attachment_id, url, width, height. All are required.
Definition at line 983 of file wp-admin/custom-header.php.
References esc_url_raw(), get_stylesheet(), get_uploaded_header_images(), object, process_default_headers(), remove_theme_mod(), set_theme_mod(), and update_post_meta().
Referenced by remove_header_image(), step_2(), step_3(), and take_action().
show_header_selector ($type = 'default')
Display UI for selecting one of several default headers.
Show the random image option if this theme has multiple header images. Random image option is on by default if no header has been set.
Since
3.0.0
Parameters
string $type The header type. One of 'default' (for the Uploaded Images control) or 'uploaded' (for the Uploaded Images control).
Definition at line 268 of file wp-admin/custom-header.php.
References $default_headers, _e, checked(), esc_attr(), get_theme_mod(), get_uploaded_header_images(), is_random_header_image(), and set_url_scheme().
Referenced by step_1().
step ()
Get the current step.
Since
2.6.0
Returns
int Current step
Definition at line 139 of file wp-admin/custom-header.php.
References $step.
Referenced by admin_page(), css_includes(), js(), and js_includes().
step_1 ()
Display first step of custom header image page.
Since
2.1.0
Fires just before the submit button in the custom header options form.
Since
3.1.0
Definition at line 451 of file wp-admin/custom-header.php.
References $header_image, __, _e, _x, add_query_arg(), admin_url(), bloginfo(), checked(), current_theme_supports(), current_user_can(), display_header_text(), do_action(), elseif, endif, esc_attr(), esc_html, esc_url, get_custom_header(), get_header_image(), get_header_textcolor(), get_theme_support(), get_uploaded_header_images(), home_url(), input, label, name, null, process_default_headers(), show_header_selector(), submit_button(), and wp_nonce_field().
Referenced by admin_page(), and finished().
step_2 ()
Display second step of custom header image page.
Since
2.1.0
Fires after the header image is set or an error is returned.
Since
2.1.0
Parameters
string $file Path to the file.
int $attachment_id Attachment ID.
This filter is documented in wp-admin/custom-header.php
Definition at line 690 of file wp-admin/custom-header.php.
References $file, $image, $url, __, _e, absint(), apply_filters(), current_theme_supports(), do_action(), elseif, finished(), get_attached_file(), get_theme_support(), height, input, is_wp_error(), name, set_header_image(), step_2_manage_upload(), str_replace, submit_button(), width, wp_crop_image(), wp_die(), wp_generate_attachment_metadata(), wp_get_attachment_image_src(), wp_get_attachment_metadata(), wp_nonce_field(), and wp_update_attachment_metadata().
Referenced by admin_page().
step_2_manage_upload ()
Upload the file to be cropped in the second step.
Since
3.4.0
Definition at line 808 of file wp-admin/custom-header.php.
References $file, $url, __, wp_check_filetype_and_ext(), wp_die(), wp_handle_upload(), wp_insert_attachment(), and wp_match_mime_types().
Referenced by step_2().
step_3 ()
Display third step of custom header image page.
Since
2.1.0
4.4.0 Switched to using wp_get_attachment_url() instead of the guid for retrieving the header image URL.
This filter is documented in wp-admin/custom-header.php
Definition at line 847 of file wp-admin/custom-header.php.
References $url, __, _copy_image_file(), absint(), apply_filters(), create_attachment_object(), current_theme_supports(), elseif, finished(), get_attached_file(), get_header_dimensions(), insert_attachment(), is_wp_error(), set_header_image(), str_replace, wp_crop_image(), wp_delete_file(), wp_die(), and wp_get_attachment_url().
Referenced by admin_page().
take_action ()
Execute custom header modification.
Since
2.6.0
Definition at line 190 of file wp-admin/custom-header.php.
References current_user_can(), elseif, remove_header_image(), reset_header_image(), set_header_image(), set_theme_mod(), and str_replace.
Field Documentation
$admin_header_callback
Definition at line 24 of file wp-admin/custom-header.php.
Referenced by __construct().
$admin_image_div_callback
Definition at line 32 of file wp-admin/custom-header.php.
Referenced by __construct().
$default_headers = array()
Definition at line 41 of file wp-admin/custom-header.php.
Referenced by get_default_header_images(), and show_header_selector().
$updated private
Definition at line 50 of file wp-admin/custom-header.php.
The documentation for this class was generated from the following file:
wp-admin/custom-header.php