GravityView: GravityView_Plugin_Hooks_Pageviews Class Reference
GravityView_Plugin_Hooks_Pageviews Class Reference
Public Member Functions
add_hooks ()
Filter the values shown in GravityView frontend.
increment_callback ()
Set the increment configuration parameter.
inject_entry_id ($r, $content, $context)
Maybe set self::$next_id from the context.
pageviews ($atts)
Output the Pageviews stuffs.
preload_callback ($preload)
Set the preload text.
remove_autocontent ($r)
Remove the autocontent filter on single entries.
Public Member Functions inherited from GravityView_Plugin_and_Theme_Hooks
__construct ()
GravityView_Theme_Support constructor.
_wp_loaded ()
Fired when all themes and plugins have been loaded.
merge_content_meta_keys ($meta_keys=array(), $post=null, & $views=null)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_meta_keys ($meta_keys=array(), $post_id=0)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_noconflict_scripts ($handles)
Merge plugin or theme scripts with existing no-conflict scripts.
merge_noconflict_styles ($handles)
Merge plugin or theme styles with existing no-conflict styles.
merge_post_type_support ($supports=array(), $is_hierarchical=false)
Merge plugin or theme post type support definitions with existing support values.
Data Fields
$atts = array()
$next_id = false
Protected Attributes
$class_name = 'Pageviews'
Protected Attributes inherited from GravityView_Plugin_and_Theme_Hooks
$class_name = false
string Optional.
$constant_name = false
string Optional.
$content_meta_keys = array()
Define the keys to be parsed by the gravityview/view_collection/from_post/meta_keys hook.
$function_name = false
string Optional.
$meta_keys = array()
Define the keys to be parsed by the gravityview/data/parse/meta_keys hook.
$post_type_support = array()
Define features in the admin editor used by the theme or plugin to be used when registering the GravityView post type.
$script_handles = array()
Define script handles used by the theme or plugin to be added to allowed no-conflict scripts.
$style_handles = array()
Define style handles used by the theme or plugin to be added to allowed no-conflict styles.
Additional Inherited Members
Protected Member Functions inherited from GravityView_Plugin_and_Theme_Hooks
add_hooks ()
Add filters for meta key and script/style handles, if defined.
Detailed Description
Since
1.17
Definition at line 19 of file class-gravityview-plugin-hooks-pageviews.php.
Member Function Documentation
add_hooks()
add_hooks ()
Filter the values shown in GravityView frontend.
Since
1.17
Definition at line 41 of file class-gravityview-plugin-hooks-pageviews.php.
increment_callback()
increment_callback ()
Set the increment configuration parameter.
Definition at line 123 of file class-gravityview-plugin-hooks-pageviews.php.
References $entry, and gravityview().
inject_entry_id()
inject_entry_id ($r, $content, $context)
Maybe set self::$next_id from the context.
Used as sort of an action via the gravityview/fields/custom/decode_shortcodes filter.
Definition at line 70 of file class-gravityview-plugin-hooks-pageviews.php.
pageviews()
pageviews ($atts)
Output the Pageviews stuffs.
Shortcode: [gv_pageviews]
Attributes: id Overload the Entry ID. Default: {entry_id} for the custom content field preload The preload text. Default: ...
Since
develop
Parameters
array $atts The shortcode arguments
Returns
string The content
Definition at line 94 of file class-gravityview-plugin-hooks-pageviews.php.
References $atts, and $output.
preload_callback()
preload_callback ($preload)
Set the preload text.
Definition at line 116 of file class-gravityview-plugin-hooks-pageviews.php.
remove_autocontent()
remove_autocontent ($r)
Remove the autocontent filter on single entries.
We do not need to be outputting the View counter.
Definition at line 58 of file class-gravityview-plugin-hooks-pageviews.php.
References gravityview().
Field Documentation
$atts
$atts = array()
Definition at line 34 of file class-gravityview-plugin-hooks-pageviews.php.
Referenced by pageviews().
$class_name
$class_name = 'Pageviews' protected
Definition at line 24 of file class-gravityview-plugin-hooks-pageviews.php.
$next_id
$next_id = false
Definition at line 29 of file class-gravityview-plugin-hooks-pageviews.php.
The documentation for this class was generated from the following file:
class-gravityview-plugin-hooks-pageviews.php