GravityView: SupportRole Class Reference
SupportRole Class Reference
Public Member Functions
__construct (Config $config, Logging $logging)
SupportUser constructor.
create ($new_role_slug='', $clone_role_slug='')
Creates the custom Support Role if it doesn't already exist.
delete ()
get_cloned_name ()
Get the name (slug) of the role that should be cloned for the TL support role.
get_name ()
Static Public Attributes
static $prevented_caps
Private Member Functions
set_name ()
Private Attributes
$config
$logging
$role_name
Detailed Description
Definition at line 22 of file SupportRole.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Logging $logging)
SupportUser constructor.
Definition at line 57 of file SupportRole.php.
References SupportRole\$config, SupportRole\$logging, and SupportRole\set_name().
Member Function Documentation
create()
create ($new_role_slug = '', $clone_role_slug = '')
Creates the custom Support Role if it doesn't already exist.
Since
1.0.0
1.0.0 removed excluded_caps from generated role
Parameters
string $new_role_slug The slug for the new role (optional). Default: {
See also
SupportRole::get_name()}
Parameters
string $clone_role_slug The slug for the role to clone (optional). Default: {
See also
SupportRole::get_cloned_name()}.
Returns
| Created/pre-existing role, if successful. WP_Error if failure.
Runs Filter:
trustedlogin/{namespace}/support_role/display_name Modify the display name of the created support role
Definition at line 116 of file SupportRole.php.
References $description, SupportRole\get_cloned_name(), and SupportRole\get_name().
delete()
delete ()
Returns
bool|null Null: Role wasn't found; True: Removing role succeeded; False: Role wasn't deleted successfully.
Definition at line 198 of file SupportRole.php.
References SupportRole\get_name().
get_cloned_name()
get_cloned_name ()
Get the name (slug) of the role that should be cloned for the TL support role.
Returns
string
Definition at line 68 of file SupportRole.php.
Referenced by SupportRole\create().
get_name()
get_name ()
Returns
string
Definition at line 81 of file SupportRole.php.
References SupportRole\$role_name.
Referenced by SupportRole\create(), and SupportRole\delete().
set_name()
set_name () private
Returns
string Sanitized with { sanitize_title_with_dashes}
Definition at line 88 of file SupportRole.php.
References SupportRole\$role_name.
Referenced by SupportRole\__construct().
Field Documentation
$config
Config $config private
Definition at line 27 of file SupportRole.php.
Referenced by SupportRole\__construct().
$logging
Logging $logging private
Definition at line 32 of file SupportRole.php.
Referenced by SupportRole\__construct().
$prevented_caps
$prevented_caps static
Initial value:
= array(
        'create_users',
        'delete_users',
        'edit_users',
        'list_users',
        'promote_users',
        'delete_site',
        'remove_users',
    )
Definition at line 44 of file SupportRole.php.
Referenced by Config\validate().
$role_name
$role_name private
Definition at line 38 of file SupportRole.php.
Referenced by SupportRole\get_name(), and SupportRole\set_name().
The documentation for this class was generated from the following file:
SupportRole.php