GravityView: TestLogger Class Reference
TestLogger Class Reference
Used for testing purposes.
Public Member Functions
__call ($method, $args)
hasRecord ($record, $level)
hasRecords ($level)
hasRecordThatContains ($message, $level)
hasRecordThatMatches ($regex, $level)
hasRecordThatPasses (callable $predicate, $level)
log ($level, $message, array $context=[])
Logs with an arbitrary level.
Parameters
mixed $level
string $message
mixed[] $context
Returns
void
Exceptions
reset ()
Public Member Functions inherited from AbstractLogger
alert ($message, array $context=array())
Action must be taken immediately.
critical ($message, array $context=array())
Critical conditions.
debug ($message, array $context=array())
Detailed debug information.
emergency ($message, array $context=array())
System is unusable.
error ($message, array $context=array())
Runtime errors that do not require immediate action but should typically be logged and monitored.
info ($message, array $context=array())
Interesting events.
notice ($message, array $context=array())
Normal but significant events.
warning ($message, array $context=array())
Exceptional occurrences that are not errors.
Data Fields
$records = []
$recordsByLevel = []
Detailed Description
Used for testing purposes.
It records all records and gives you access to them for verification.
bool hasEmergency($record) bool hasAlert($record) bool hasCritical($record) bool hasError($record) bool hasWarning($record) bool hasNotice($record) bool hasInfo($record) bool hasDebug($record)
bool hasEmergencyRecords() bool hasAlertRecords() bool hasCriticalRecords() bool hasErrorRecords() bool hasWarningRecords() bool hasNoticeRecords() bool hasInfoRecords() bool hasDebugRecords()
bool hasEmergencyThatContains($message) bool hasAlertThatContains($message) bool hasCriticalThatContains($message) bool hasErrorThatContains($message) bool hasWarningThatContains($message) bool hasNoticeThatContains($message) bool hasInfoThatContains($message) bool hasDebugThatContains($message)
bool hasEmergencyThatMatches($message) bool hasAlertThatMatches($message) bool hasCriticalThatMatches($message) bool hasErrorThatMatches($message) bool hasWarningThatMatches($message) bool hasNoticeThatMatches($message) bool hasInfoThatMatches($message) bool hasDebugThatMatches($message)
bool hasEmergencyThatPasses($message) bool hasAlertThatPasses($message) bool hasCriticalThatPasses($message) bool hasErrorThatPasses($message) bool hasWarningThatPasses($message) bool hasNoticeThatPasses($message) bool hasInfoThatPasses($message) bool hasDebugThatPasses($message)
Definition at line 63 of file TestLogger.php.
Member Function Documentation
__call()
__call ($method, $args)
Definition at line 135 of file TestLogger.php.
References $args.
hasRecord()
hasRecord ($record, $level)
Definition at line 92 of file TestLogger.php.
References TestLogger\hasRecordThatPasses().
hasRecords()
hasRecords ($level)
Definition at line 87 of file TestLogger.php.
hasRecordThatContains()
hasRecordThatContains ($message, $level)
Definition at line 108 of file TestLogger.php.
References TestLogger\hasRecordThatPasses().
hasRecordThatMatches()
hasRecordThatMatches ($regex, $level)
Definition at line 115 of file TestLogger.php.
References TestLogger\hasRecordThatPasses().
hasRecordThatPasses()
hasRecordThatPasses (callable $predicate, $level)
Definition at line 122 of file TestLogger.php.
References GV\$i.
Referenced by TestLogger\hasRecord(), TestLogger\hasRecordThatContains(), and TestLogger\hasRecordThatMatches().
log()
log ($level, $message, array $context = [])
Logs with an arbitrary level.
Parameters
mixed $level
string $message
mixed[] $context
Returns
void
Exceptions
Implements LoggerInterface.
Definition at line 75 of file TestLogger.php.
reset()
reset ()
Definition at line 148 of file TestLogger.php.
Field Documentation
$records
$records = []
Definition at line 68 of file TestLogger.php.
$recordsByLevel
$recordsByLevel = []
Definition at line 70 of file TestLogger.php.
The documentation for this class was generated from the following file:
TestLogger.php