GravityView: GFPaymentStatsTable Class Reference
GFPaymentStatsTable Class Reference
Public Member Functions
__construct ($columns, $rows, $total_count, $page_size)
column_default ($item, $column)
column_revenue ($item)
get_columns ()
no_items ()
pagination ($which)
prepare_items ()
Public Member Functions inherited from WP_List_Table
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($args=array())
Constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
_js_vars ()
Send required variables to JavaScript land.
ajax_response ()
Handle an incoming ajax request (called from admin-ajax.php)
ajax_user_can ()
Checks the current user's permissions.
current_action ()
Get the current action selected from the bulk actions dropdown.
display ()
Display the table.
display_rows ()
Generate the table rows.
display_rows_or_placeholder ()
Generate the tbody element for the list table.
get_column_count ()
Return number of visible columns.
get_columns ()
Get a list of columns.
get_pagenum ()
Get the current page number.
get_pagination_arg ($key)
Access the pagination args.
get_primary_column ()
Public wrapper for WP_List_Table::get_default_primary_column_name().
has_items ()
Whether the table has items to display or not.
no_items ()
Message to be displayed when there are no items.
prepare_items ()
Prepares the list of items for displaying.
print_column_headers ($with_id=true)
Print column headers, accounting for hidden and sortable columns.
search_box ($text, $input_id)
Display the search box.
single_row ($item)
Generates content for a single row of the table.
views ()
Display the list of views available on this table.
Private Attributes
$_page_size = 10
$_rows = array()
$_total_items = 0
Additional Inherited Members
Data Fields inherited from WP_List_Table
$items
Protected Member Functions inherited from WP_List_Table
bulk_actions ($which= '')
Display the bulk actions dropdown.
column_cb ($item)
column_default ($item, $column_name)
comments_bubble ($post_id, $pending_comments)
Display a comment count bubble.
display_tablenav ($which)
Generate the table navigation above or below the table.
extra_tablenav ($which)
Extra controls to be displayed between bulk actions and pagination.
get_bulk_actions ()
Get an associative array (option_name => option_title) with the list of bulk actions available on this table.
get_column_info ()
Get a list of all, hidden and sortable columns, with filter applied.
get_default_primary_column_name ()
Gets the name of the default primary column.
get_items_per_page ($option, $default=20)
Get number of items to display on a single page.
get_primary_column_name ()
Gets the name of the primary column.
get_sortable_columns ()
Get a list of sortable columns.
get_table_classes ()
Get a list of CSS classes for the WP_List_Table table tag.
get_views ()
Get an associative array (id => link) with the list of views available on this table.
handle_row_actions ($item, $column_name, $primary)
Generates and display row actions links for the list table.
months_dropdown ($post_type)
Display a monthly dropdown for filtering items.
pagination ($which)
Display the pagination.
row_actions ($actions, $always_visible=false)
Generate row actions div.
set_pagination_args ($args)
An internal method that sets all the necessary pagination arguments.
single_row_columns ($item)
Generates the columns for a single row of the table.
view_switcher ($current_mode)
Display a view switcher.
Protected Attributes inherited from WP_List_Table
$_args
$_column_headers
$_pagination_args = array()
$compat_fields = array('_args', '_pagination_args', 'screen', '_actions', '_pagination')
{
$compat_methods
{
$modes = array()
$screen
Detailed Description
Definition at line 2727 of file class-gf-payment-addon.php.
Constructor & Destructor Documentation
__construct ($columns, $rows, $total_count, $page_size)
Definition at line 2733 of file class-gf-payment-addon.php.
References $columns, and esc_html__().
Member Function Documentation
column_default ($item, $column)
Definition at line 2769 of file class-gf-payment-addon.php.
column_revenue ($item)
Definition at line 2773 of file class-gf-payment-addon.php.
get_columns ()
Definition at line 2765 of file class-gf-payment-addon.php.
no_items ()
Definition at line 2761 of file class-gf-payment-addon.php.
References esc_html_e.
pagination ($which)
Definition at line 2777 of file class-gf-payment-addon.php.
References WP_List_Table\$_pagination, $output, $total_pages, _n(), esc_attr__(), esc_html_x(), WP_List_Table\get_pagenum(), WP_List_Table\get_pagination_arg(), and number_format_i18n().
prepare_items ()
Definition at line 2755 of file class-gf-payment-addon.php.
References $_rows, and WP_List_Table\set_pagination_args().
Field Documentation
$_page_size = 10 private
Definition at line 2730 of file class-gf-payment-addon.php.
$_rows = array() private
Definition at line 2729 of file class-gf-payment-addon.php.
Referenced by prepare_items().
$_total_items = 0 private
Definition at line 2731 of file class-gf-payment-addon.php.
The documentation for this class was generated from the following file:
class-gf-payment-addon.php