GravityView: Renderer Class Reference
Renderer Class Reference
If this file is called directly, abort.
Public Member Functions
__construct ()
Initialization.
legacy_template_warning ($view, $path)
Warn about legacy template being used.
Static Public Member Functions
static maybe_print_notices ($gravityview=null)
Print unconfigured notices to admins.
Static Private Member Functions
static maybe_print_configuration_notice ($gravityview)
Check empty configuration.
static maybe_print_entry_approval_notice ($gravityview)
Print notice warning admins that "Show only approved" is enabled.
static maybe_print_reserved_slugs_notice ($gravityview)
Print reserved slug warnings, if they exist.
Detailed Description
If this file is called directly, abort.
The class.
The base for all renderers.
Definition at line 14 of file class-gv-renderer.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Initialization.
Definition at line 18 of file class-gv-renderer.php.
Member Function Documentation
legacy_template_warning()
legacy_template_warning ($view, $path)
Warn about legacy template being used.
Generate a callback that shows which legacy template was at fault. Used in gravityview_before.
Parameters
\GV\View $view The view we're looking at.
string $path The path of the offending template.
Returns
A closure used in the filter.
Definition at line 253 of file class-gv-renderer.php.
maybe_print_configuration_notice()
static maybe_print_configuration_notice ($gravityview) static private
Check empty configuration.
Since
2.10
Parameters
\GV\Template_Context $gravityview The $gravityview template object.
Returns
void
Definition at line 151 of file class-gv-renderer.php.
References $image, $output, $title, and GRAVITYVIEW_FILE.
maybe_print_entry_approval_notice()
static maybe_print_entry_approval_notice ($gravityview) static private
Print notice warning admins that "Show only approved" is enabled.
Since
2.9.5
Parameters
\GV\Template_Context $gravityview The $gravityview template object.
Returns
void
Definition at line 56 of file class-gv-renderer.php.
References GV\$form, GravityView_Entry_Approval_Status\APPROVED, and GRAVITYVIEW_FILE.
maybe_print_notices()
static maybe_print_notices ($gravityview = null) static
Print unconfigured notices to admins.
Print reserved slug warnings. Print entry approval notice.
Parameters
\GV\Template_Context $gravityview The $gravityview template object.
Returns
void
Call the legacy code.
Definition at line 33 of file class-gv-renderer.php.
References GravityView_frontend\getInstance(), and gravityview_get_view_id().
maybe_print_reserved_slugs_notice()
static maybe_print_reserved_slugs_notice ($gravityview) static private
Print reserved slug warnings, if they exist.
Since
2.9.5
Parameters
Template_Context $gravityview The $gravityview template object.
Returns
void
Runs Filter:
gravityview/rewrite/reserved_slugs Modify the reserved embed slugs that trigger a warning.
Since
2.5
Parameters
[in,out] array $reserved_slugs An array of strings, reserved slugs.
\GV\Template_Context $gravityview The context.
Definition at line 196 of file class-gv-renderer.php.
References $output, $title, GV\get(), and gravityview().
The documentation for this class was generated from the following file:
class-gv-renderer.php