GravityView: WP_Http_Streams Class Reference
WP_Http_Streams Class Reference
Core class used to integrate PHP Streams as an HTTP transport.
Public Member Functions
request ($url, $args=array())
Send a HTTP request to a URI using PHP Streams.
Static Public Member Functions
static test ($args=array())
Determines whether this class can be used for retrieving a URL.
static verify_ssl_certificate ($stream, $host)
Verifies the received SSL certificate against its Common Names and subjectAltName fields.
Detailed Description
Core class used to integrate PHP Streams as an HTTP transport.
Since
2.7.0
3.7.0 Combined with the fsockopen transport and switched to stream_socket_client().
Definition at line 16 of file class-wp-http-streams.php.
Member Function Documentation
request ($url, $args = array())
Send a HTTP request to a URI using PHP Streams.
See also
WP_Http::request For default options descriptions.
Since
2.7.0
3.7.0 Combined with the fsockopen transport and switched to stream_socket_client().
public
Parameters
string $url The request URL.
string | array $args Optional. Override the defaults.
Returns
array|WP_Error Array containing 'headers', 'body', 'response', 'cookies', 'filename'. A WP_Error instance upon error
Filter whether SSL should be verified for local requests.
Since
2.8.0
Parameters
bool $ssl_verify Whether to verify the SSL connection. Default true.
Filter whether SSL should be verified for non-local requests.
Since
2.8.0
Parameters
bool $ssl_verify Whether to verify the SSL connection. Default true.
Definition at line 30 of file class-wp-http-streams.php.
References $url, __, apply_filters(), WP_Http\buildCookieHeader(), WP_Http\chunkTransferDecode(), WP_Http_Encoding\decompress(), elseif, WP_Http\handle_redirects(), null, WP_Http\processHeaders(), WP_Http\processResponse(), WP_Http_Encoding\should_decode(), WP_DEBUG, and wp_parse_args().
static test ($args = array()) static
Determines whether this class can be used for retrieving a URL.
public
Since
2.7.0
3.7.0 Combined with the fsockopen transport and switched to stream_socket_client().
Parameters
array $args Optional. Array of request arguments. Default empty array.
Returns
bool False means this class can not be used, true means it can.
Filter whether streams can be used as a transport for retrieving a URL.
Since
2.7.0
Parameters
bool $use_class Whether the class can be used. Default true.
array $args Request arguments.
Definition at line 390 of file class-wp-http-streams.php.
References apply_filters().
static verify_ssl_certificate ($stream, $host) static
Verifies the received SSL certificate against its Common Names and subjectAltName fields.
PHP's SSL verifications only verify that it's a valid Certificate, it doesn't verify if the certificate is valid for the hostname which was requested. This function verifies the requested hostname against certificate's subjectAltName field, if that is empty, or contains no DNS entries, a fallback to the Common Name field is used.
IP Address support is included if the request is being made to an IP address.
Since
3.7.0
Parameters
stream $stream The PHP Stream which the SSL request is being made over
string $host The hostname being requested
Returns
bool If the cerficiate presented in $stream is valid for $host
Definition at line 332 of file class-wp-http-streams.php.
References elseif, and WP_Http\is_ip_address().
The documentation for this class was generated from the following file:
class-wp-http-streams.php