GravityView: WP_Image_Editor Class Reference
WP_Image_Editor Class Reference
Base image editor class from which implementations extend.
Public Member Functions
__construct ($file)
Each instance handles a single file.
crop ($src_x, $src_y, $src_w, $src_h, $dst_w=null, $dst_h=null, $src_abs=false)
Crops Image.
flip ($horz, $vert)
Flips current image.
generate_filename ($suffix=null, $dest_path=null, $extension=null)
Builds an output filename based on current file, and adding proper suffix.
get_quality ()
Gets the Image Compression quality on a 1-100% scale.
get_size ()
Gets dimensions of image.
get_suffix ()
Builds and returns proper suffix for file based on height and width.
load ()
Loads image from $this->file into editor.
multi_resize ($sizes)
Resize multiple images from a single source.
resize ($max_w, $max_h, $crop=false)
Resizes current image.
rotate ($angle)
Rotates current image counter-clockwise by $angle.
save ($destfilename=null, $mime_type=null)
Saves current image to file.
set_quality ($quality=null)
Sets Image Compression quality on a 1-100% scale.
stream ($mime_type=null)
Streams current image to browser.
Static Public Member Functions
static supports_mime_type ($mime_type)
Checks to see if editor supports the mime-type specified.
static test ($args=array())
Checks to see if current environment supports the editor chosen.
Protected Member Functions
get_output_format ($filename=null, $mime_type=null)
Returns preferred mime-type and extension based on provided file's extension and mime, or current file's extension and mime.
make_image ($filename, $function, $arguments)
Either calls editor's save function or handles file as a stream.
update_size ($width=null, $height=null)
Sets current image size.
Static Protected Member Functions
static get_extension ($mime_type=null)
Returns first matched extension from Mime-type, as mapped from wp_get_mime_types()
static get_mime_type ($extension=null)
Returns first matched mime-type from extension, as mapped from wp_get_mime_types()
Protected Attributes
$default_mime_type = 'image/jpeg'
$default_quality = 90
$file = null
$mime_type = null
$quality = false
$size = null
Detailed Description
Base image editor class from which implementations extend.
Since
3.5.0
Definition at line 14 of file class-wp-image-editor.php.
Constructor & Destructor Documentation
__construct ($file)
Each instance handles a single file.
Parameters
string $file Path to the file to load.
Definition at line 27 of file class-wp-image-editor.php.
References $file.
Member Function Documentation
crop ($src_x, $src_y, $src_w, $src_h, $dst_w = null, $dst_h = null, $src_abs = false) abstract
Crops Image.
Since
3.5.0 public
Parameters
int $src_x The start x position to crop from.
int $src_y The start y position to crop from.
int $src_w The width to crop.
int $src_h The height to crop.
int $dst_w Optional. The destination width.
int $dst_h Optional. The destination height.
bool $src_abs Optional. If the source crop points are absolute.
Returns
bool|WP_Error
flip ($horz, $vert) abstract
Flips current image.
Since
3.5.0 public
Parameters
bool $horz Flip along Horizontal Axis
bool $vert Flip along Vertical Axis
Returns
bool|WP_Error
generate_filename ($suffix = null, $dest_path = null, $extension = null)
Builds an output filename based on current file, and adding proper suffix.
Since
3.5.0 public
Parameters
string $suffix
string $dest_path
string $extension
Returns
string filename
Definition at line 373 of file class-wp-image-editor.php.
References $dir, $name, get_suffix(), trailingslashit(), and wp_basename().
Referenced by WP_Image_Editor_GD\_save(), and WP_Image_Editor_Imagick\_save().
static get_extension ($mime_type = null) static protected
Returns first matched extension from Mime-type, as mapped from wp_get_mime_types()
Since
3.5.0
protected
Parameters
string $mime_type
Returns
string|false
Definition at line 486 of file class-wp-image-editor.php.
References $mime_type, and wp_get_mime_types().
Referenced by WP_Image_Editor_Imagick\_save(), get_output_format(), WP_Image_Editor_Imagick\save(), and WP_Image_Editor_Imagick\stream().
static get_mime_type ($extension = null) static protected
Returns first matched mime-type from extension, as mapped from wp_get_mime_types()
Since
3.5.0
protected
Parameters
string $extension
Returns
string|false
Definition at line 458 of file class-wp-image-editor.php.
References wp_get_mime_types().
Referenced by get_output_format(), and WP_Image_Editor_Imagick\load().
get_output_format ($filename = null, $mime_type = null) protected
Returns preferred mime-type and extension based on provided file's extension and mime, or current file's extension and mime.
Will default to $this->default_mime_type if requested is not supported.
Provides corrected filename only if filename is provided.
Since
3.5.0 protected
Parameters
string $filename
string $mime_type
Returns
array { filename|null, extension, mime-type }
Filter default mime type prior to getting the file extension.
See also
wp_get_mime_types()
Since
3.5.0
Parameters
string $mime_type Mime type string.
Definition at line 307 of file class-wp-image-editor.php.
References $dir, $mime_type, apply_filters(), get_extension(), get_mime_type(), null, supports_mime_type(), trailingslashit(), and wp_basename().
Referenced by WP_Image_Editor_GD\_save(), WP_Image_Editor_Imagick\_save(), WP_Image_Editor_GD\stream(), and WP_Image_Editor_Imagick\stream().
get_quality ()
Gets the Image Compression quality on a 1-100% scale.
Since
4.0.0 public
Returns
int $quality Compression Quality. Range: [1,100]
Definition at line 220 of file class-wp-image-editor.php.
References $quality, and set_quality().
Referenced by WP_Image_Editor_GD\_save(), WP_Image_Editor_Imagick\set_quality(), and WP_Image_Editor_GD\stream().
get_size ()
Gets dimensions of image.
Since
3.5.0 public
Returns
array {'width'=>int, 'height'=>int}
Definition at line 190 of file class-wp-image-editor.php.
References $size.
Referenced by get_suffix().
get_suffix ()
Builds and returns proper suffix for file based on height and width.
Since
3.5.0 public
Returns
false|string suffix
Definition at line 399 of file class-wp-image-editor.php.
References get_size().
Referenced by generate_filename().
load () abstract
Loads image from $this->file into editor.
Since
3.5.0 protected
Returns
bool|WP_Error True if loaded; WP_Error on failure.
make_image ($filename, $function, $arguments) protected
Either calls editor's save function or handles file as a stream.
Since
3.5.0 protected
Parameters
string | stream $filename
callable $function
array $arguments
Returns
bool
Definition at line 417 of file class-wp-image-editor.php.
References wp_is_stream(), and wp_mkdir_p().
Referenced by WP_Image_Editor_Imagick\_save().
multi_resize ($sizes) abstract
Resize multiple images from a single source.
Since
3.5.0 public
Parameters
array $sizes { An array of image size arrays. Default sizes are 'small', 'medium', 'large'.
array $size { int $width Image width. int $height Image height. bool $crop Optional. Whether to crop the image. Default false. } }
Returns
array An array of resized images metadata by size.
resize ($max_w, $max_h, $crop = false) abstract
Resizes current image.
At minimum, either a height or width must be provided. If one of the two is set to null, the resize will maintain aspect ratio according to the provided dimension.
Since
3.5.0 public
Parameters
int | null $max_w Image width.
int | null $max_h Image height.
bool $crop
Returns
bool|WP_Error
rotate ($angle) abstract
Rotates current image counter-clockwise by $angle.
Since
3.5.0 public
Parameters
float $angle
Returns
bool|WP_Error
save ($destfilename = null, $mime_type = null) abstract
Saves current image to file.
Since
3.5.0 public
Parameters
string $destfilename
string $mime_type
Returns
array|WP_Error {'path'=>string, 'file'=>string, 'width'=>int, 'height'=>int, 'mime-type'=>string}
set_quality ($quality = null)
Sets Image Compression quality on a 1-100% scale.
Since
3.5.0 public
Parameters
int $quality Compression Quality. Range: [1,100]
Returns
true|WP_Error True if set successfully; WP_Error on failure.
Filter the default image compression quality setting.
Applies only during initial editor instantiation, or when set_quality() is run manually without the $quality argument.
set_quality() has priority over the filter.
Since
3.5.0
Parameters
int $quality Quality level between 1 (low) and 100 (high).
string $mime_type Image mime type.
Filter the JPEG compression quality for backward-compatibility.
Applies only during initial editor instantiation, or when set_quality() is run manually without the $quality argument.
set_quality() has priority over the filter.
The filter is evaluated under two contexts: 'image_resize', and 'edit_image', (when a JPEG image is saved to file).
Since
2.5.0
Parameters
int $quality Quality level between 0 (low) and 100 (high) of the JPEG.
string $context Context of the filter.
Definition at line 237 of file class-wp-image-editor.php.
References $default_quality, $quality, __, apply_filters(), and null.
Referenced by get_quality(), and WP_Image_Editor_GD\load().
stream ($mime_type = null) abstract
Streams current image to browser.
Since
3.5.0 public
Parameters
string $mime_type
Returns
bool|WP_Error
static supports_mime_type ($mime_type) static
Checks to see if editor supports the mime-type specified.
Must be overridden in a sub-class.
Since
3.5.0
public
Parameters
string $mime_type
Returns
bool
Definition at line 61 of file class-wp-image-editor.php.
Referenced by get_output_format().
static test ($args = array()) static
Checks to see if current environment supports the editor chosen.
Must be overridden in a sub-class.
Since
3.5.0
public
Parameters
array $args
Returns
bool
Definition at line 44 of file class-wp-image-editor.php.
update_size ($width = null, $height = null) protected
Sets current image size.
Since
3.5.0 protected
Parameters
int $width
int $height
Returns
true
Definition at line 204 of file class-wp-image-editor.php.
References size.
Field Documentation
$default_mime_type = 'image/jpeg' protected
Definition at line 18 of file class-wp-image-editor.php.
$default_quality = 90 protected
Definition at line 20 of file class-wp-image-editor.php.
Referenced by set_quality().
$file = null protected
Definition at line 15 of file class-wp-image-editor.php.
Referenced by __construct(), WP_Image_Editor_Imagick\load(), and WP_Image_Editor_Imagick\save().
$mime_type = null protected
Definition at line 17 of file class-wp-image-editor.php.
Referenced by WP_Image_Editor_GD\_save(), WP_Image_Editor_Imagick\_save(), get_extension(), get_output_format(), WP_Image_Editor_GD\save(), WP_Image_Editor_Imagick\save(), WP_Image_Editor_GD\stream(), WP_Image_Editor_Imagick\stream(), WP_Image_Editor_GD\supports_mime_type(), and WP_Image_Editor_Imagick\supports_mime_type().
$quality = false protected
Definition at line 19 of file class-wp-image-editor.php.
Referenced by get_quality(), WP_Image_Editor_Imagick\set_quality(), and set_quality().
$size = null protected
Definition at line 16 of file class-wp-image-editor.php.
Referenced by get_size(), WP_Image_Editor_GD\load(), WP_Image_Editor_GD\multi_resize(), WP_Image_Editor_Imagick\multi_resize(), and WP_Image_Editor_Imagick\update_size().
The documentation for this class was generated from the following file:
class-wp-image-editor.php