GravityView: GV_Unit_Tests_Bootstrap Class Reference
GV_Unit_Tests_Bootstrap Class Reference
GravityView Unit Tests Bootstrap.
Public Member Functions
__construct ()
Setup the unit testing environment.
get_entry ()
get_entry_id ()
get_form ()
get_form_id ()
install ()
Setup all Gravity View's files.
load ()
Load GravityView.
test_print_log ($message= '', $data=null)
Static Public Member Functions
static instance ()
Get the single class instance.
Data Fields
$plugin_dir
$tests_dir
$wp_tests_dir
Static Protected Attributes
static $instance = null
Private Member Functions
create_stubs ()
Generate some placeholder values to test against.
Private Attributes
$entry = array()
$entry_id = 0
$form = array()
$form_id = 0
Detailed Description
GravityView Unit Tests Bootstrap.
Since
1.9
Definition at line 7 of file bootstrap.php.
Constructor & Destructor Documentation
__construct ()
Setup the unit testing environment.
Since
1.9
Definition at line 46 of file bootstrap.php.
References install().
Member Function Documentation
create_stubs () private
Generate some placeholder values to test against.
Definition at line 141 of file bootstrap.php.
Referenced by load().
get_entry ()
Returns
array
Definition at line 120 of file bootstrap.php.
References $entry.
get_entry_id ()
Returns
int
Definition at line 127 of file bootstrap.php.
References $entry_id.
get_form ()
Returns
array
Definition at line 113 of file bootstrap.php.
References $form.
get_form_id ()
Returns
int
Definition at line 134 of file bootstrap.php.
References $form_id.
install ()
Setup all Gravity View's files.
Since
1.9
Definition at line 199 of file bootstrap.php.
References GravityView_Plugin\getInstance().
Referenced by __construct().
static instance () static
Get the single class instance.
Since
1.9
Returns
GV_Unit_Tests_Bootstrap
Definition at line 210 of file bootstrap.php.
Referenced by GravityView_Uninstall_Test\setUp(), GravityView_API_Test\setUp(), and GravityView_API_Test\test_replace_variables().
load ()
Load GravityView.
Since
1.9
Definition at line 95 of file bootstrap.php.
References create_stubs().
test_print_log ($message = '', $data = null)
Definition at line 80 of file bootstrap.php.
Field Documentation
$entry = array() private
Definition at line 39 of file bootstrap.php.
Referenced by get_entry().
$entry_id = 0 private
Definition at line 34 of file bootstrap.php.
Referenced by get_entry_id().
$form = array() private
Definition at line 29 of file bootstrap.php.
Referenced by get_form().
$form_id = 0 private
Definition at line 24 of file bootstrap.php.
Referenced by get_form_id().
$instance = null static protected
Definition at line 10 of file bootstrap.php.
$plugin_dir
Definition at line 19 of file bootstrap.php.
$tests_dir
Definition at line 16 of file bootstrap.php.
$wp_tests_dir
Definition at line 13 of file bootstrap.php.
The documentation for this class was generated from the following file:
bootstrap.php