GravityView: WP_Http_Cookie Class Reference
WP_Http_Cookie Class Reference
Core class used to encapsulate a single cookie object for internal use.
Public Member Functions
__construct ($data, $requested_url= '')
Sets up this cookie object.
getFullHeader ()
Retrieve cookie header for usage in the rest of the WordPress HTTP API.
getHeaderValue ()
Convert cookie name and value back to header string.
test ($url)
Confirms that it's OK to send this cookie to the URL checked against.
Data Fields
$domain
$expires
$name
$path
$value
Detailed Description
Core class used to encapsulate a single cookie object for internal use.
Returned cookies are represented using this class, and when cookies are set, if they are not already a WP_Http_Cookie() object, then they are turned into one.
Since
2.8.0
Definition at line 21 of file class-wp-http-cookie.php.
Constructor & Destructor Documentation
__construct ($data, $requested_url = '')
Sets up this cookie object.
The parameter $data should be either an associative array containing the indices names below or a header string detailing it.
Since
2.8.0 public
Parameters
string | array $data { Raw cookie data as header string or data array.
string $name Cookie name. mixed $value Value. Should NOT already be urlencoded. string|int $expires Optional. Unix timestamp or formatted date. Default null. string $path Optional. Path. Default '/'. string $domain Optional. Domain. Default host of parsed $requested_url. int $port Optional. Port. Default null. }
Parameters
string $requested_url The URL which the cookie was set on, used for default $domain and $port values.
Definition at line 85 of file class-wp-http-cookie.php.
References $field, $name, $value, name, and null.
Member Function Documentation
getFullHeader ()
Retrieve cookie header for usage in the rest of the WordPress HTTP API.
public
Since
2.8.0
Returns
string
Definition at line 216 of file class-wp-http-cookie.php.
References getHeaderValue().
getHeaderValue ()
Convert cookie name and value back to header string.
public
Since
2.8.0
Returns
string Header encoded cookie name and value.
Filter the header-encoded cookie value.
Since
3.4.0
Parameters
string $value The cookie value.
string $name The cookie name.
Definition at line 193 of file class-wp-http-cookie.php.
References apply_filters(), and name.
Referenced by getFullHeader().
test ($url)
Confirms that it's OK to send this cookie to the URL checked against.
Decision is based on RFC 2109/2965, so look there for details on validity.
public
Since
2.8.0
Parameters
string $url URL you intend to send this cookie to
Returns
bool true if allowed, false otherwise.
Definition at line 149 of file class-wp-http-cookie.php.
References $domain, $path, $url, name, and null.
Field Documentation
$domain
Definition at line 61 of file class-wp-http-cookie.php.
Referenced by test().
$expires
Definition at line 45 of file class-wp-http-cookie.php.
$name
Definition at line 29 of file class-wp-http-cookie.php.
Referenced by __construct().
$path
Definition at line 53 of file class-wp-http-cookie.php.
Referenced by test().
$value
Definition at line 37 of file class-wp-http-cookie.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
class-wp-http-cookie.php