GravityView: Gravity_Api Class Reference
Gravity_Api Class Reference
Public Member Functions
add_site ($license_key, $is_md5=false)
Retrieves site key and site secret key from remote API and stores them as WP options.
ensure_site_registered ()
get_api_key ($third_party_name)
get_gravity_api_url ()
get_site_key ()
get_site_secret ()
is_site_registered ()
prepare_response_body ($raw_response)
purge_site_credentials ()
request ($resource, $body, $method= 'POST', $options=array())
update_site ($new_license_key_md5)
Static Public Member Functions
static get_instance ()
Static Private Attributes
static $instance = null
Detailed Description
Definition at line 20 of file class-gravity-api.php.
Member Function Documentation
add_site ($license_key, $is_md5 = false)
Retrieves site key and site secret key from remote API and stores them as WP options.
Returns false if license key is invalid; otherwise, returns true.
Since
1.9.? public
Parameters
string $license_key
Returns
bool Success
Definition at line 42 of file class-gravity-api.php.
References get_bloginfo(), is_wp_error(), request(), and update_option().
Referenced by ensure_site_registered().
ensure_site_registered ()
Definition at line 249 of file class-gravity-api.php.
References add_site(), get_site_key(), get_site_secret(), is_site_registered(), and is_wp_error().
Referenced by get_api_key().
get_api_key ($third_party_name)
Definition at line 132 of file class-gravity-api.php.
References ensure_site_registered(), prepare_response_body(), and request().
get_gravity_api_url ()
Definition at line 245 of file class-gravity-api.php.
References trailingslashit().
Referenced by request().
static get_instance () static
Definition at line 24 of file class-gravity-api.php.
References null.
Referenced by gapi().
get_site_key ()
Definition at line 220 of file class-gravity-api.php.
References get_option().
Referenced by ensure_site_registered(), is_site_registered(), and update_site().
get_site_secret ()
Definition at line 234 of file class-gravity-api.php.
References get_option().
Referenced by ensure_site_registered(), is_site_registered(), and update_site().
is_site_registered ()
Definition at line 271 of file class-gravity-api.php.
References get_site_key(), and get_site_secret().
Referenced by ensure_site_registered().
prepare_response_body ($raw_response)
Definition at line 163 of file class-gravity-api.php.
References is_wp_error().
Referenced by get_api_key().
purge_site_credentials ()
Definition at line 185 of file class-gravity-api.php.
References delete_option().
request ($resource, $body, $method = 'POST', $options = array())
Definition at line 191 of file class-gravity-api.php.
References $options, get_bloginfo(), get_gravity_api_url(), get_option(), null, wp_parse_args(), and wp_remote_request().
Referenced by add_site(), get_api_key(), and update_site().
update_site ($new_license_key_md5)
Definition at line 90 of file class-gravity-api.php.
References get_bloginfo(), get_site_key(), get_site_secret(), is_wp_error(), and request().
Field Documentation
$instance = null static private
Definition at line 22 of file class-gravity-api.php.
The documentation for this class was generated from the following file:
class-gravity-api.php