GravityView: WP_Feed_Cache_Transient Class Reference
WP_Feed_Cache_Transient Class Reference
Public Member Functions
__construct ($location, $filename, $extension)
Class instantiator.
load ()
public
mtime ()
public
save ($data)
public
touch ()
public
unlink ()
public
Data Fields
$lifetime = 43200
$mod_name
$name
Detailed Description
Definition at line 23 of file class-feed.php.
Constructor & Destructor Documentation
__construct ($location, $filename, $extension)
Class instantiator.
Parameters
string $location URL location (scheme is used to determine handler).
string $filename Unique identifier for cache object.
string $extension 'spi' or 'spc'.
Filter the transient lifetime of the feed cache.
Since
2.8.0
Parameters
int $lifetime Cache duration in seconds. Default is 43200 seconds (12 hours).
string $filename Unique identifier for the cache object.
Definition at line 35 of file class-feed.php.
References $lifetime, apply_filters(), and name.
Member Function Documentation
load ()
public
Definition at line 67 of file class-feed.php.
References get_transient(), and name.
mtime ()
public
Definition at line 74 of file class-feed.php.
References get_transient().
save ($data)
public
Definition at line 54 of file class-feed.php.
References name, and set_transient().
touch ()
public
Definition at line 81 of file class-feed.php.
References set_transient().
unlink ()
public
Definition at line 88 of file class-feed.php.
References delete_transient(), and name.
Field Documentation
$lifetime = 43200
Definition at line 26 of file class-feed.php.
Referenced by __construct().
$mod_name
Definition at line 25 of file class-feed.php.
$name
Definition at line 24 of file class-feed.php.
The documentation for this class was generated from the following file:
class-feed.php