GravityView: GravityView_Cache Class Reference
GravityView_Cache Class Reference
Handle caching using transients for GravityView.
Public Member Functions
__construct ($form_ids=NULL, $args=array())
add_hooks ()
Add actions for clearing out caches when entries are updated.
blacklist_add ($form_ids)
blacklist_remove ($form_ids)
blocklist_add ($form_ids)
Add form IDs to a "blocklist" to force the cache to be refreshed.
blocklist_remove ($form_ids)
Remove Form IDs from blocklist.
delete ($form_ids=NULL)
Delete cached transients based on form IDs.
delete_expired_transients ()
Delete expired transients.
entry_added ($entry, $form)
Clear the cache when entries are added via GFAPI::add_entry().
entry_created ($entry, $form)
When an entry is created, add the entry's form to the cache blocklist.
entry_status_changed ($lead_id, $property_value='', $previous_value='')
Force refreshing a cache when an entry is deleted.
entry_updated ($form, $lead_id)
When an entry is updated, add the entry's form to the cache blocklist.
get ($key=NULL)
Get transient result.
get_key ()
Allow public access to get transient key.
in_blacklist ($form_ids=NULL)
Is a form ID in the cache blocklist?
in_blocklist ($form_ids=NULL)
Is a form ID in the cache blocklist.
schedule_transient_cleanup ()
Schedule expired transient cleanup twice a day.
set ($content, $filter_name='')
Cache content as a transient.
use_cache ()
Check whether to use cached results, if available.
Data Fields
const BLACKLIST_OPTION_NAME = 'gravityview_cache_blocklist'
const BLOCKLIST_OPTION_NAME = 'gravityview_cache_blocklist'
Protected Member Functions
get_cache_key_prefix ($form_ids=NULL)
Calculate the prefix based on the Form IDs.
set_key ()
Set the transient key based on the form IDs and the arguments passed to the class.
Protected Attributes
$args
$form_ids
Private Attributes
$key = ''
$lead_db_columns = array('id', 'form_id', 'post_id', 'date_created', 'is_starred', 'is_read', 'ip', 'source_url', 'user_agent', 'currency', 'payment_status', 'payment_date', 'payment_amount', 'transaction_id', 'is_fulfilled', 'created_by', 'transaction_type', 'status')
Detailed Description
Handle caching using transients for GravityView.
Definition at line 6 of file class-cache.php.
Constructor & Destructor Documentation
__construct()
__construct ($form_ids = NULL, $args = array())
Parameters
array | int $form_ids Form ID or array of form IDs used in a request
array $args Extra request parameters used to generate the query. This is used to generate the unique transient key.
Definition at line 45 of file class-cache.php.
References $args, $form_ids, add_hooks(), and set_key().
Member Function Documentation
add_hooks()
add_hooks ()
Add actions for clearing out caches when entries are updated.
Since
1.14
See also
RGFormsModel::update_lead_property() Trigger when any entry property changes
Definition at line 62 of file class-cache.php.
Referenced by __construct().
blacklist_add()
blacklist_add ($form_ids)
See also
GravityView_Cache::blocklist_add()}
Parameters
int | array $form_ids Form IDs to force to be updated
Returns
bool Whether the removal was successful
Definition at line 266 of file class-cache.php.
References $form_ids, and blocklist_remove().
blacklist_remove()
blacklist_remove ($form_ids)
See also
GravityView_Cache::blocklist_remove()}
Parameters
int | array $form_ids Form IDs to add
Returns
bool Whether the removal was successful
Definition at line 300 of file class-cache.php.
References $form_ids, and blocklist_remove().
blocklist_add()
blocklist_add ($form_ids)
Add form IDs to a "blocklist" to force the cache to be refreshed.
Parameters
int | array $form_ids Form IDs to force to be updated
Returns
boolean False if value was not updated and true if value was updated.
Definition at line 232 of file class-cache.php.
References $form_ids, and gravityview().
Referenced by entry_added(), entry_created(), entry_status_changed(), and entry_updated().
blocklist_remove()
blocklist_remove ($form_ids)
Remove Form IDs from blocklist.
Parameters
int | array $form_ids Form IDs to remove
Returns
bool Whether the removal was successful
Definition at line 278 of file class-cache.php.
References $form_ids, and gravityview().
Referenced by blacklist_add(), blacklist_remove(), and use_cache().
delete()
delete ($form_ids = NULL)
Delete cached transients based on form IDs.
Parameters
int | array $form_ids Form IDs to delete
Returns
void
Definition at line 438 of file class-cache.php.
References $form_id, $form_ids, $key, and gravityview().
delete_expired_transients()
delete_expired_transients ()
Delete expired transients.
The code is copied from the Delete Expired Transients, with slight modifications to track # of results and to get the blog ID dynamically
See also
https://wordpress.org/plugins/delete-expired-transients/ Plugin where the code was taken from
DelxtransCleaners::clearBlogExpired()
Returns
void
Definition at line 508 of file class-cache.php.
References gravityview().
entry_added()
entry_added ($entry, $form)
Clear the cache when entries are added via GFAPI::add_entry().
Parameters
array $entry The GF Entry array
array $form The GF Form array
Returns
void
Definition at line 163 of file class-cache.php.
References $entry, GV\$form, blocklist_add(), and gravityview().
entry_created()
entry_created ($entry, $form)
When an entry is created, add the entry's form to the cache blocklist.
We don't want old caches; when an entry is added, we want to clear the cache.
Parameters
array $entry GF entry array
array $form GF form array
Returns
void
Definition at line 148 of file class-cache.php.
References $entry, GV\$form, blocklist_add(), and gravityview().
entry_status_changed()
entry_status_changed ($lead_id, $property_value = '', $previous_value = '')
Force refreshing a cache when an entry is deleted.
The gform_delete_lead action is called before the lead is deleted; we fetch the entry to find out the form ID so it can be added to the blocklist.
Since
1.5.1
Parameters
int $lead_id Entry ID
string $property_value Previous value of the lead status passed by gform_update_status hook
string $previous_value Previous value of the lead status passed by gform_update_status hook
Returns
void
Definition at line 107 of file class-cache.php.
References $entry, blocklist_add(), and gravityview().
entry_updated()
entry_updated ($form, $lead_id)
When an entry is updated, add the entry's form to the cache blocklist.
Parameters
array $form GF form array
int $lead_id Entry ID
Returns
void
Definition at line 131 of file class-cache.php.
References GV\$form, blocklist_add(), and gravityview().
get()
get ($key = NULL)
Get transient result.
Parameters
string $key Transient key to fetch
Returns
mixed False: Not using cache or cache was a WP_Error object; NULL: no results found; Mixed: cache value
Definition at line 361 of file class-cache.php.
References $key, gravityview(), and use_cache().
get_cache_key_prefix()
get_cache_key_prefix ($form_ids = NULL) protected
Calculate the prefix based on the Form IDs.
Parameters
int | array $form_ids Form IDs to generate prefix for
Returns
string Prefix for the cache string used in set_key()
Definition at line 180 of file class-cache.php.
References $form_ids, and $forms.
Referenced by set_key().
get_key()
get_key ()
Allow public access to get transient key.
Returns
string Transient key
Definition at line 221 of file class-cache.php.
References $key.
in_blacklist()
in_blacklist ($form_ids = NULL)
Is a form ID in the cache blocklist?
Parameters
int | array $form_ids Form IDs to check if in blocklist
See also
GravityView_Cache::in_blocklist()}
Returns
bool
Definition at line 314 of file class-cache.php.
References $form_ids, and in_blocklist().
in_blocklist()
in_blocklist ($form_ids = NULL)
Is a form ID in the cache blocklist.
Parameters
int | array $form_ids Form IDs to check if in blocklist
Returns
bool
Definition at line 326 of file class-cache.php.
References $form_id, $form_ids, and gravityview().
Referenced by in_blacklist(), and use_cache().
schedule_transient_cleanup()
schedule_transient_cleanup ()
Schedule expired transient cleanup twice a day.
Can be overruled by the gravityview_cleanup_transients filter (returns boolean)
Returns
void
Runs Filter:
gravityview_cleanup_transients Override GravityView cleanup of transients by setting this to false
Parameters
boolean $cleanup Whether to run the GravityView auto-cleanup of transients. Default: true
Definition at line 482 of file class-cache.php.
set()
set ($content, $filter_name = '')
Cache content as a transient.
Cache time defaults to 1 week
Parameters
mixed $content [description]
string $filter_name Name used to modify the cache time. Will be set to gravityview_cache_time_{$filter_name}.
Returns
bool If $content is not set, false. Otherwise, returns true if transient was set and false if not.
Runs Filter:
gravityview_cache_time_{$filter_name} Modify the cache time for a type of cache
Parameters
int $time_in_seconds Default: DAY_IN_SECONDS
Definition at line 405 of file class-cache.php.
References $content, and gravityview().
set_key()
set_key () protected
Set the transient key based on the form IDs and the arguments passed to the class.
Definition at line 200 of file class-cache.php.
References $key, and get_cache_key_prefix().
Referenced by __construct().
use_cache()
use_cache ()
Check whether to use cached results, if available.
If the user can edit posts, they are able to override whether to cache results by adding cache or nocache to the URL requested.
Returns
boolean True: use cache; False: don't use cache
Runs Filter:
gravityview_use_cache Modify whether to use the cache or not
Parameters
boolean $use_cache Previous setting
GravityView_Cache $this The GravityView_Cache object
Definition at line 558 of file class-cache.php.
References $form_ids, blocklist_remove(), gravityview(), GVCommon\has_cap(), and in_blocklist().
Referenced by get().
Field Documentation
$args
$args protected
Definition at line 25 of file class-cache.php.
Referenced by __construct().
$form_ids
$form_ids protected
Definition at line 18 of file class-cache.php.
Referenced by __construct(), blacklist_add(), blacklist_remove(), blocklist_add(), blocklist_remove(), delete(), get_cache_key_prefix(), in_blacklist(), in_blocklist(), and use_cache().
$key
$key = '' private
Definition at line 32 of file class-cache.php.
Referenced by delete(), get(), get_key(), and set_key().
$lead_db_columns
$lead_db_columns = array('id', 'form_id', 'post_id', 'date_created', 'is_starred', 'is_read', 'ip', 'source_url', 'user_agent', 'currency', 'payment_status', 'payment_date', 'payment_amount', 'transaction_id', 'is_fulfilled', 'created_by', 'transaction_type', 'status') private
Definition at line 38 of file class-cache.php.
BLACKLIST_OPTION_NAME
const BLACKLIST_OPTION_NAME = 'gravityview_cache_blocklist'
Definition at line 9 of file class-cache.php.
BLOCKLIST_OPTION_NAME
const BLOCKLIST_OPTION_NAME = 'gravityview_cache_blocklist'
Definition at line 11 of file class-cache.php.
The documentation for this class was generated from the following file:
class-cache.php