GravityView: WP_Embed Class Reference
WP_Embed Class Reference
Public Member Functions
__construct ()
Constructor.
autoembed ($content)
Passes any unlinked URLs that are on their own line to WP_Embed::shortcode() for potential embedding.
autoembed_callback ($match)
Callback function for WP_Embed::autoembed().
cache_oembed ($post_ID)
Triggers a caching of all oEmbed results.
delete_oembed_caches ($post_ID)
Delete all oEmbed caches.
maybe_make_link ($url)
Conditionally makes a hyperlink based on an internal class variable.
maybe_run_ajax_cache ()
If a post/page was saved, then output JavaScript to make an AJAX request that will call WP_Embed::cache_oembed().
register_handler ($id, $regex, $callback, $priority=10)
Register an embed handler.
run_shortcode ($content)
Process the [embed] shortcode.
shortcode ($attr, $url= '')
The do_shortcode() callback function.
unregister_handler ($id, $priority=10)
Unregister a previously registered embed handler.
Data Fields
$handlers = array()
$last_attr = array()
$last_url = ''
$linkifunknown = true
$post_ID
$return_false_on_fail = false
When an URL cannot be embedded, return false instead of returning a link or the URL.
$usecache = true
Detailed Description
Definition at line 9 of file class-wp-embed.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Definition at line 26 of file class-wp-embed.php.
References add_action(), add_filter(), and add_shortcode().
Member Function Documentation
autoembed ($content)
Passes any unlinked URLs that are on their own line to WP_Embed::shortcode() for potential embedding.
WP_Embed::autoembed_callback()
Parameters
string $content The content to be searched.
Returns
string Potentially modified $content.
Definition at line 322 of file class-wp-embed.php.
References $content, str_replace, and wp_replace_in_html_tags().
Referenced by cache_oembed().
autoembed_callback ($match)
Callback function for WP_Embed::autoembed().
Parameters
array $match A regex match array.
Returns
string The embed HTML on success, otherwise the original URL.
Definition at line 339 of file class-wp-embed.php.
References $linkifunknown, and shortcode().
cache_oembed ($post_ID)
Triggers a caching of all oEmbed results.
Parameters
int $post_ID Post ID to do the caching for.
Filter the array of post types to cache oEmbed results for.
Since
2.9.0
Parameters
array $post_types Array of post types to cache oEmbed results for. Defaults to post types with show_ui set to true.
Definition at line 287 of file class-wp-embed.php.
References $content, $post, $post_ID, apply_filters(), autoembed(), get_post(), get_post_types(), and run_shortcode().
delete_oembed_caches ($post_ID)
Delete all oEmbed caches.
Unused by core as of 4.0.0.
Parameters
int $post_ID Post ID to delete the caches for.
Definition at line 271 of file class-wp-embed.php.
References $post_ID, delete_post_meta(), and get_post_custom_keys().
maybe_make_link ($url)
Conditionally makes a hyperlink based on an internal class variable.
Parameters
string $url URL to potentially be linked.
Returns
false|string Linked URL or the original URL. False if 'return_false_on_fail' is true.
Filter the returned, maybe-linked embed URL.
Since
2.9.0
Parameters
string $output The linked or original URL.
string $url The original URL.
Definition at line 354 of file class-wp-embed.php.
References $linkifunknown, $output, $url, apply_filters(), esc_html, and esc_url.
Referenced by shortcode().
maybe_run_ajax_cache ()
If a post/page was saved, then output JavaScript to make an AJAX request that will call WP_Embed::cache_oembed().
Definition at line 75 of file class-wp-embed.php.
References $post, and get_post().
register_handler ($id, $regex, $callback, $priority = 10)
Register an embed handler.
Do not use this function directly, use wp_embed_register_handler() instead. This function should probably also only be used for sites that do not support oEmbed.
Parameters
string $id An internal ID/name for the handler. Needs to be unique.
string $regex The regex that will be used to see if this handler should be used for a URL.
callable $callback The callback function that will be called if the regex is matched.
int $priority Optional. Used to specify the order in which the registered handlers will be tested (default: 10). Lower numbers correspond with earlier testing, and handlers with the same priority are tested in the order in which they were added to the action.
Definition at line 99 of file class-wp-embed.php.
References $id.
run_shortcode ($content)
Process the [embed] shortcode.
Since the [embed] shortcode needs to be run earlier than other shortcodes, this function removes all existing shortcodes, registers the [embed] shortcode, calls do_shortcode(), and then re-registers the old shortcodes.
array $shortcode_tags
Parameters
string $content Content to parse
Returns
string Content with shortcode parsed
Definition at line 53 of file class-wp-embed.php.
References $content, $shortcode_tags, add_shortcode(), do_shortcode(), and remove_all_shortcodes().
Referenced by cache_oembed().
shortcode ($attr, $url = '')
The do_shortcode() callback function.
Attempts to convert a URL into embed HTML. Starts by checking the URL against the regex of the registered embed handlers. If none of the regex matches and it's enabled, then the URL will be given to the WP_oEmbed class.
Parameters
array $attr { Shortcode attributes. Optional.
int $width Width of the embed in pixels. int $height Height of the embed in pixels. }
Parameters
string $url The URL attempting to be embedded.
Returns
string|false The embed HTML on success, otherwise the original URL. ->maybe_make_link() can return false on failure.
Filter the returned embed handler.
Since
2.9.0
See also
WP_Embed::shortcode()
Parameters
mixed $return The shortcode callback function to call.
string $url The attempted embed URL.
array $attr An array of shortcode attributes.
Filter the oEmbed TTL value (time to live).
Since
4.0.0
Parameters
int $time Time to live (in seconds).
string $url The attempted embed URL.
array $attr An array of shortcode attributes.
int $post_ID Post ID.
Filter the cached oEmbed HTML.
Since
2.9.0
See also
WP_Embed::shortcode()
Parameters
mixed $cache The cached HTML result, stored in post meta.
string $url The attempted embed URL.
array $attr An array of shortcode attributes.
int $post_ID Post ID.
Filter whether to inspect the given URL for discoverable link tags.
Since
2.9.0
4.4.0 The default value changed to true.
See also
WP_oEmbed::discover()
Parameters
bool $enable Whether to enable <link> tag discovery. Default true.
This filter is documented in wp-includes/class-wp-embed.php
Definition at line 132 of file class-wp-embed.php.
References $handlers, $id, $post, $post_ID, $url, apply_filters(), elseif, get_post(), get_post_meta(), if, maybe_make_link(), null, str_replace, update_post_meta(), wp_embed_defaults(), wp_oembed_get(), and wp_parse_args().
Referenced by autoembed_callback().
unregister_handler ($id, $priority = 10)
Unregister a previously registered embed handler.
Do not use this function directly, use wp_embed_unregister_handler() instead.
Parameters
string $id The handler ID that should be removed.
int $priority Optional. The priority of the handler to be removed (default: 10).
Definition at line 112 of file class-wp-embed.php.
References $id.
Field Documentation
$handlers = array()
Definition at line 10 of file class-wp-embed.php.
Referenced by shortcode().
$last_attr = array()
Definition at line 14 of file class-wp-embed.php.
$last_url = ''
Definition at line 15 of file class-wp-embed.php.
$linkifunknown = true
Definition at line 13 of file class-wp-embed.php.
Referenced by autoembed_callback(), and maybe_make_link().
$post_ID
Definition at line 11 of file class-wp-embed.php.
Referenced by cache_oembed(), delete_oembed_caches(), and shortcode().
$return_false_on_fail = false
When an URL cannot be embedded, return false instead of returning a link or the URL.
Bypasses the 'embed_maybe_make_link' filter.
Definition at line 21 of file class-wp-embed.php.
$usecache = true
Definition at line 12 of file class-wp-embed.php.
The documentation for this class was generated from the following file:
class-wp-embed.php