GravityView: AMFReader Class Reference
AMFReader Class Reference
Public Member Functions
__construct (&$stream)
readArray ()
readBoolean ()
readData ()
readDate ()
readDouble ()
readLongString ()
readMixedArray ()
readObject ()
readString ()
readTypedObject ()
readXML ()
Data Fields
$stream
Detailed Description
Definition at line 473 of file module.audio-video.flv.php.
Constructor & Destructor Documentation
__construct (& $stream)
Definition at line 476 of file module.audio-video.flv.php.
References $stream.
Member Function Documentation
readArray ()
Definition at line 600 of file module.audio-video.flv.php.
References $i, and readData().
Referenced by readData().
readBoolean ()
Definition at line 554 of file module.audio-video.flv.php.
Referenced by readData().
readData ()
Definition at line 480 of file module.audio-video.flv.php.
References $value, null, readArray(), readBoolean(), readDate(), readDouble(), readLongString(), readMixedArray(), readObject(), readString(), readTypedObject(), and readXML().
Referenced by readArray(), readMixedArray(), and readObject().
readDate ()
Definition at line 610 of file module.audio-video.flv.php.
Referenced by readData().
readDouble ()
Definition at line 550 of file module.audio-video.flv.php.
Referenced by readData().
readLongString ()
Definition at line 616 of file module.audio-video.flv.php.
Referenced by readData().
readMixedArray ()
Definition at line 579 of file module.audio-video.flv.php.
References readData().
Referenced by readData().
readObject ()
Definition at line 562 of file module.audio-video.flv.php.
References readData().
Referenced by readData(), and readTypedObject().
readString ()
Definition at line 558 of file module.audio-video.flv.php.
Referenced by readData().
readTypedObject ()
Definition at line 624 of file module.audio-video.flv.php.
References readObject().
Referenced by readData().
readXML ()
Definition at line 620 of file module.audio-video.flv.php.
Referenced by readData().
Field Documentation
$stream
Definition at line 474 of file module.audio-video.flv.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
module.audio-video.flv.php