GravityView: AVCSequenceParameterSetReader Class Reference
AVCSequenceParameterSetReader Class Reference
Public Member Functions
__construct ($sps)
expGolombSe ()
expGolombUe ()
getBit ()
getBits ($bits)
getHeight ()
getWidth ()
readData ()
skipBits ($bits)
Data Fields
$currentBits = 0
$currentBytes = 0
$height
$sps
$start = 0
$width
Detailed Description
Definition at line 630 of file module.audio-video.flv.php.
Constructor & Destructor Documentation
__construct ($sps)
Definition at line 638 of file module.audio-video.flv.php.
References $sps.
Member Function Documentation
expGolombSe ()
Definition at line 729 of file module.audio-video.flv.php.
References expGolombUe().
Referenced by readData().
expGolombUe ()
Definition at line 714 of file module.audio-video.flv.php.
References getBit(), and getBits().
Referenced by expGolombSe(), and readData().
getBit ()
Definition at line 700 of file module.audio-video.flv.php.
References $currentBits, getid3_lib\BigEndian2Int(), and skipBits().
Referenced by expGolombUe(), and getBits().
getBits ($bits)
Definition at line 706 of file module.audio-video.flv.php.
References $i, and getBit().
Referenced by expGolombUe(), and readData().
getHeight ()
Definition at line 742 of file module.audio-video.flv.php.
References $height.
getWidth ()
Definition at line 738 of file module.audio-video.flv.php.
References $width.
readData ()
Definition at line 642 of file module.audio-video.flv.php.
References $i, elseif, expGolombSe(), expGolombUe(), getBits(), height, skipBits(), and width.
skipBits ($bits)
Definition at line 694 of file module.audio-video.flv.php.
Referenced by getBit(), and readData().
Field Documentation
$currentBits = 0
Definition at line 634 of file module.audio-video.flv.php.
Referenced by getBit().
$currentBytes = 0
Definition at line 633 of file module.audio-video.flv.php.
$height
Definition at line 636 of file module.audio-video.flv.php.
Referenced by getHeight().
$sps
Definition at line 631 of file module.audio-video.flv.php.
Referenced by __construct().
$start = 0
Definition at line 632 of file module.audio-video.flv.php.
$width
Definition at line 635 of file module.audio-video.flv.php.
Referenced by getWidth().
The documentation for this class was generated from the following file:
module.audio-video.flv.php