GravityView: WP_Meta_Query Class Reference
WP_Meta_Query Class Reference
Public Member Functions
__construct ($meta_query=false)
Constructor.
get_cast_for_type ($type= '')
Return the appropriate alias for the given meta type if applicable.
get_clauses ()
Get a flattened list of sanitized meta clauses.
get_sql ($type, $primary_table, $primary_id_column, $context=null)
Generates SQL clauses to be appended to a main query.
get_sql_for_clause (&$clause, $parent_query, $clause_key= '')
Generate SQL JOIN and WHERE clauses for a first-order query clause.
has_or_relation ()
Checks whether the current query has any OR relations.
parse_query_vars ($qv)
Constructs a meta query based on 'meta_*' query vars.
sanitize_query ($queries)
Ensure the 'meta_query' argument passed to the class constructor is well-formed.
Data Fields
$meta_id_column
$meta_table
$primary_id_column
$primary_table
$queries = array()
$relation
Protected Member Functions
find_compatible_table_alias ($clause, $parent_query)
Identify an existing table alias that is compatible with the current query clause.
get_sql_clauses ()
Generate SQL clauses to be appended to a main query.
get_sql_for_query (&$query, $depth=0)
Generate SQL clauses for a single query array.
is_first_order_clause ($query)
Determine whether a query clause is first-order.
Protected Attributes
$clauses = array()
$has_or_relation = false
$table_aliases = array()
Detailed Description
Definition at line 23 of file class-wp-meta-query.php.
Constructor & Destructor Documentation
__construct ($meta_query = false)
Constructor.
Since
3.2.0
4.2.0 Introduced support for naming query clauses by associative array keys.
public
Parameters
array $meta_query { Array of meta query clauses. When first-order clauses use strings as their array keys, they may be referenced in the 'orderby' parameter of the parent query.
string $relation Optional. The MySQL keyword used to join the clauses of the query. Accepts 'AND', or 'OR'. Default 'AND'. array { Optional. An array of first-order clause parameters, or another fully-formed meta query.
string $key Meta key to filter by. string $value Meta value to filter by. string $compare MySQL operator used for comparing the $value. Accepts '=', '!=', '>', '>=', '<', '<=', 'LIKE', 'NOT LIKE', 'IN', 'NOT IN', 'BETWEEN', 'NOT BETWEEN', 'REGEXP', 'NOT REGEXP', or 'RLIKE'. Default is 'IN' when $value is an array, '=' otherwise. string $type MySQL data type that the meta_value column will be CAST to for comparisons. Accepts 'NUMERIC', 'BINARY', 'CHAR', 'DATE', 'DATETIME', 'DECIMAL', 'SIGNED', 'TIME', or 'UNSIGNED'. Default is 'CHAR'. } }
Definition at line 137 of file class-wp-meta-query.php.
References sanitize_query().
Referenced by parse_query_vars().
Member Function Documentation
find_compatible_table_alias ($clause, $parent_query) protected
Identify an existing table alias that is compatible with the current query clause.
We avoid unnecessary table joins by allowing each clause to look for an existing table alias that is compatible with the query that it needs to perform.
An existing alias is compatible if (a) it is a sibling of $clause (ie, it's under the scope of the same relation), and (b) the combination of operator and relation between the clauses allows for a shared table join. In the case of {
See also
WP_Meta_Query}, this only applies to 'IN' clauses that are connected by the relation 'OR'.
Since
4.1.0 protected
Parameters
array $clause Query clause.
array $parent_query Parent query of $clause.
Returns
string|bool Table alias if found, otherwise false.
Filter the table alias identified as compatible with the current clause.
Since
4.1.0
Parameters
string | bool $alias Table alias, or false if none was found.
array $clause First-order query clause.
array $parent_query Parent of $clause.
object $this WP_Meta_Query object.
Definition at line 688 of file class-wp-meta-query.php.
References apply_filters(), elseif, and is_first_order_clause().
Referenced by get_sql_for_clause().
get_cast_for_type ($type = '')
Return the appropriate alias for the given meta type if applicable.
Since
3.7.0 public
Parameters
string $type MySQL type to cast meta_value.
Returns
string MySQL type.
Definition at line 291 of file class-wp-meta-query.php.
Referenced by get_sql_for_clause().
get_clauses ()
Get a flattened list of sanitized meta clauses.
This array should be used for clause lookup, as when the table alias and CAST type must be determined for a value of 'orderby' corresponding to a meta clause.
Since
4.2.0 public
Returns
array Meta clauses.
Definition at line 663 of file class-wp-meta-query.php.
References $clauses.
get_sql ($type, $primary_table, $primary_id_column, $context = null)
Generates SQL clauses to be appended to a main query.
Since
3.2.0 public
Parameters
string $type Type of meta, eg 'user', 'post'.
string $primary_table Database table where the object being filtered is stored (eg wp_users).
string $primary_id_column ID column for the filtered object in $primary_table.
object $context Optional. The main query object.
Returns
false|array { Array containing JOIN and WHERE SQL clauses to append to the main query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Filter the meta query's generated SQL.
Since
3.1.0
Parameters
array $args { An array of meta query SQL arguments.
array $clauses Array containing the query's JOIN and WHERE clauses. array $queries Array of meta queries. string $type Type of meta. string $primary_table Primary table. string $primary_id_column Primary column ID. object $context The main query object. }
Definition at line 323 of file class-wp-meta-query.php.
References $meta_table, $primary_id_column, $primary_table, _get_meta_table(), apply_filters_ref_array(), get_sql_clauses(), sanitize_key(), and str_replace.
get_sql_clauses () protected
Generate SQL clauses to be appended to a main query.
Called by the public {
See also
WP_Meta_Query::get_sql()}, this method is abstracted out to maintain parity with the other Query classes.
Since
4.1.0 protected
Returns
array { Array containing JOIN and WHERE SQL clauses to append to the main query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 379 of file class-wp-meta-query.php.
References $queries, and get_sql_for_query().
Referenced by get_sql().
get_sql_for_clause (& $clause, $parent_query, $clause_key = '')
Generate SQL JOIN and WHERE clauses for a first-order query clause.
"First-order" means that it's an array with a 'key' or 'value'.
Since
4.1.0 public
wpdb $wpdb WordPress database abstraction object.
Parameters
array $clause Query clause, passed by reference.
array $parent_query Parent query array.
string $clause_key Optional. The array key used to name the clause in the original $meta_query parameters. If not provided, a key will be generated automatically.
Returns
array { Array containing JOIN and WHERE SQL clauses to append to a first-order query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 500 of file class-wp-meta-query.php.
References $i, $meta_table, $wpdb, find_compatible_table_alias(), and get_cast_for_type().
Referenced by get_sql_for_query().
get_sql_for_query (& $query, $depth = 0) protected
Generate SQL clauses for a single query array.
If nested subqueries are found, this method recurses the tree to produce the properly nested SQL.
Since
4.1.0 protected
Parameters
array $query Query to parse, passed by reference.
int $depth Optional. Number of tree levels deep we currently are. Used to calculate indentation. Default 0.
Returns
array { Array containing JOIN and WHERE SQL clauses to append to a single query array.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 413 of file class-wp-meta-query.php.
References $i, $relation, elseif, get_sql_for_clause(), and is_first_order_clause().
Referenced by get_sql_clauses().
has_or_relation ()
Checks whether the current query has any OR relations.
In some cases, the presence of an OR relation somewhere in the query will require the use of a DISTINCT or GROUP BY keyword in the SELECT clause. The current method can be used in these cases to determine whether such a clause is necessary.
Since
4.3.0
Returns
bool True if the query contains any OR relations, otherwise false.
Definition at line 745 of file class-wp-meta-query.php.
References $has_or_relation.
Referenced by sanitize_query().
is_first_order_clause ($query) protected
Determine whether a query clause is first-order.
A first-order meta query clause is one that has either a 'key' or a 'value' array key.
Since
4.1.0 protected
Parameters
array $query Meta query arguments.
Returns
bool Whether the query clause is a first-order clause.
Definition at line 230 of file class-wp-meta-query.php.
Referenced by find_compatible_table_alias(), get_sql_for_query(), and sanitize_query().
parse_query_vars ($qv)
Constructs a meta query based on 'meta_*' query vars.
Since
3.2.0 public
Parameters
array $qv The query variables
Definition at line 242 of file class-wp-meta-query.php.
References __construct(), and elseif.
sanitize_query ($queries)
Ensure the 'meta_query' argument passed to the class constructor is well-formed.
Eliminates empty items and ensures that a 'relation' is set.
Since
4.1.0 public
Parameters
array $queries Array of query clauses.
Returns
array Sanitized array of query clauses.
Definition at line 161 of file class-wp-meta-query.php.
References $queries, $relation, elseif, has_or_relation(), and is_first_order_clause().
Referenced by __construct().
Field Documentation
$clauses = array() protected
Definition at line 96 of file class-wp-meta-query.php.
Referenced by get_clauses().
$has_or_relation = false protected
Definition at line 105 of file class-wp-meta-query.php.
Referenced by has_or_relation().
$meta_id_column
Definition at line 60 of file class-wp-meta-query.php.
$meta_table
Definition at line 51 of file class-wp-meta-query.php.
Referenced by get_sql(), and get_sql_for_clause().
$primary_id_column
Definition at line 78 of file class-wp-meta-query.php.
Referenced by get_sql().
$primary_table
Definition at line 69 of file class-wp-meta-query.php.
Referenced by get_sql().
$queries = array()
Definition at line 33 of file class-wp-meta-query.php.
Referenced by get_sql_clauses(), and sanitize_query().
$relation
Definition at line 42 of file class-wp-meta-query.php.
Referenced by get_sql_for_query(), and sanitize_query().
$table_aliases = array() protected
Definition at line 87 of file class-wp-meta-query.php.
The documentation for this class was generated from the following file:
class-wp-meta-query.php