GravityView: getid3_flv Class Reference
getid3_flv Class Reference
Public Member Functions
Analyze ()
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Static Public Member Functions
static audioBitDepthLookup ($id)
static audioFormatLookup ($id)
static audioRateLookup ($id)
static videoCodecLookup ($id)
Data Fields
$max_frames = 100000
const magic = 'FLV'
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
Definition at line 76 of file module.audio-video.flv.php.
Member Function Documentation
Analyze ()
Definition at line 82 of file module.audio-video.flv.php.
References getid3_lib\BigEndian2Int(), getid3_lib\CastAsInt(), elseif, getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\ftell(), GETID3_FLV_TAG_AUDIO, GETID3_FLV_TAG_META, GETID3_FLV_TAG_VIDEO, GETID3_FLV_VIDEO_H263, GETID3_FLV_VIDEO_H264, GETID3_FLV_VIDEO_VP6FLV_ALPHA, H264_AVC_SEQUENCE_HEADER, getid3_lib\LittleEndian2Int(), and getid3_lib\PrintHexBytes().
static audioBitDepthLookup ($id) static
Definition at line 368 of file module.audio-video.flv.php.
References $id.
static audioFormatLookup ($id) static
Definition at line 336 of file module.audio-video.flv.php.
References $id.
static audioRateLookup ($id) static
Definition at line 358 of file module.audio-video.flv.php.
References $id.
static videoCodecLookup ($id) static
Definition at line 376 of file module.audio-video.flv.php.
References $id, GETID3_FLV_VIDEO_H263, GETID3_FLV_VIDEO_H264, GETID3_FLV_VIDEO_SCREEN, GETID3_FLV_VIDEO_SCREENV2, GETID3_FLV_VIDEO_VP6FLV, and GETID3_FLV_VIDEO_VP6FLV_ALPHA.
Field Documentation
$max_frames = 100000
Definition at line 80 of file module.audio-video.flv.php.
const magic = 'FLV'
Definition at line 78 of file module.audio-video.flv.php.
The documentation for this class was generated from the following file:
module.audio-video.flv.php