GravityView: WP_Automatic_Updater Class Reference
WP_Automatic_Updater Class Reference
Core class used for handling automatic background updates.
Public Member Functions
is_disabled ()
Whether the entire automatic updater is disabled.
is_vcs_checkout ($context)
Check for version control checkouts.
run ()
Kicks off the background update process, looping through all pending updates.
should_update ($type, $item, $context)
Tests to see if we can and should update a specific item.
update ($type, $item)
Update an item, if appropriate.
Protected Member Functions
after_core_update ($update_result)
If we tried to perform a core update, check if we should send an email, and if we need to avoid processing future updates.
send_core_update_notification_email ($item)
Notifies an administrator of a core update.
send_debug_email ()
Prepares and sends an email of a full log of background update results, useful for debugging and geekery.
send_email ($type, $core_update, $result=null)
Sends an email upon the completion or failure of a background core update.
Protected Attributes
$update_results = array()
Detailed Description
Core class used for handling automatic background updates.
Since
3.7.0
Definition at line 2612 of file class-wp-upgrader.php.
Member Function Documentation
after_core_update ($update_result) protected
If we tried to perform a core update, check if we should send an email, and if we need to avoid processing future updates.
Since
Unknown protected
string $wp_version
Parameters
object | WP_Error $update_result The result of the core update. Includes the update offer and result.
Definition at line 3110 of file class-wp-upgrader.php.
References $wp_version, elseif, get_site_option(), is_wp_error(), update_site_option(), and wp_schedule_single_event().
is_disabled ()
Whether the entire automatic updater is disabled.
Since
3.7.0 public
Filter whether to entirely disable background updates.
There are more fine-grained filters and controls for selective disabling. This filter parallels the AUTOMATIC_UPDATER_DISABLED constant in name.
This also disables update notification emails. That may change in the future.
Since
3.7.0
Parameters
bool $disabled Whether the updater should be disabled.
Definition at line 2628 of file class-wp-upgrader.php.
References apply_filters(), and wp_installing().
is_vcs_checkout ($context)
Check for version control checkouts.
Checks for Subversion, Git, Mercurial, and Bazaar. It recursively looks up the filesystem to the top of the drive, erring on the side of detecting a VCS checkout somewhere.
ABSPATH is always checked in addition to whatever $context is (which may be the wp-content directory, for example). The underlying assumption is that if you are using version control anywhere, then you should be making decisions for how things get updated.
Since
3.7.0 public
Parameters
string $context The filesystem path to check, in addition to ABSPATH.
Filter whether the automatic updater should consider a filesystem location to be potentially managed by a version control system.
Since
3.7.0
Parameters
bool $checkout Whether a VCS checkout was discovered at $context or ABSPATH, or anywhere higher.
string $context The filesystem context (a path) against which filesystem status should be checked.
Definition at line 2671 of file class-wp-upgrader.php.
References ABSPATH, apply_filters(), and untrailingslashit().
run ()
Kicks off the background update process, looping through all pending updates.
Since
3.7.0 public
wpdb $wpdb string $wp_version
Filter whether to send a debugging email for each automatic background update.
Since
3.7.0
Parameters
bool $development_version By default, emails are sent if the install is a development version. Return false to avoid the email.
Fires after all automatic updates have run.
Since
3.8.0
Parameters
array $update_results The results of all attempted updates.
Definition at line 2969 of file class-wp-upgrader.php.
References $plugin, $theme, $update, $wp_version, $wpdb, apply_filters(), delete_option(), do_action(), find_core_auto_update(), get_option(), get_site_transient(), is_main_network(), is_main_site(), remove_action(), update_option(), wp_clean_plugins_cache(), wp_clean_themes_cache(), wp_clean_update_cache(), wp_get_translation_updates(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
Referenced by wp_maybe_auto_update().
send_core_update_notification_email ($item) protected
Notifies an administrator of a core update.
Since
3.7.0 protected
Parameters
object $item The update offer.
Filter whether to notify the site administrator of a new core update.
By default, administrators are notified when the update offer received from WordPress.org sets a particular flag. This allows some discretion in if and when to notify.
This filter is only evaluated once per release. If the same email address was already notified of the same new version, WordPress won't repeatedly email the administrator.
This filter is also used on about.php to check if a plugin has disabled these notifications.
Since
3.7.0
Parameters
bool $notify Whether the site administrator is notified.
object $item The update offer.
Definition at line 2808 of file class-wp-upgrader.php.
References apply_filters(), and get_site_option().
send_debug_email () protected
Prepares and sends an email of a full log of background update results, useful for debugging and geekery.
Since
3.7.0 protected
Filter the debug email that can be sent following an automatic background core update.
Since
3.8.0
Parameters
array $email { Array of email arguments that will be passed to wp_mail().
string $to The email recipient. An array of emails can be returned, as handled by wp_mail(). string $subject Email subject. string $body Email message body. string $headers Any email headers. Default empty. }
Parameters
int $failures The number of failures encountered while upgrading.
mixed $results The results of all attempted updates.
Definition at line 3396 of file class-wp-upgrader.php.
References $message, $messages, $name, $site_title, $update, __, apply_filters(), get_bloginfo(), get_site_option(), is_wp_error(), network_home_url(), str_replace, wp_list_filter(), wp_list_pluck(), and wp_specialchars_decode().
send_email ($type, $core_update, $result = null) protected
Sends an email upon the completion or failure of a background core update.
Since
3.7.0 protected
string $wp_version
Parameters
string $type The type of email to send. Can be one of 'success', 'fail', 'manual', 'critical'.
object $core_update The update offer that was attempted.
mixed $result Optional. The result for the core update. Can be WP_Error.
Filter whether to send an email following an automatic background core update.
Since
3.7.0
Parameters
bool $send Whether to send the email. Default true.
string $type The type of email to send. Can be one of 'success', 'fail', 'critical'.
object $core_update The update offer that was attempted.
mixed $result The result for the core update. Can be WP_Error.
Filter the email sent following an automatic background core update.
Since
3.7.0
Parameters
array $email { Array of email arguments that will be passed to wp_mail().
string $to The email recipient. An array of emails can be returned, as handled by wp_mail(). string $subject The email's subject. string $body The email message body. string $headers Any email headers, defaults to no headers. }
Parameters
string $type The type of email being sent. Can be one of 'success', 'fail', 'manual', 'critical'.
object $core_update The update offer that was attempted.
mixed $result The result for the core update. Can be WP_Error.
Definition at line 3202 of file class-wp-upgrader.php.
References $errors, $GLOBALS, __, admin_url(), apply_filters(), get_option(), get_plugin_updates(), get_preferred_from_update_core(), get_site_option(), get_theme_updates(), home_url(), is_wp_error(), network_admin_url(), update_site_option(), and wp_specialchars_decode().
should_update ($type, $item, $context)
Tests to see if we can and should update a specific item.
Since
3.7.0 public
wpdb $wpdb WordPress database abstraction object.
Parameters
string $type The type of update being checked: 'core', 'theme', 'plugin', 'translation'.
object $item The update offer.
string $context The filesystem context (a path) against which filesystem access and status should be checked.
Filter whether to automatically update core, a plugin, a theme, or a language.
The dynamic portion of the hook name, $type, refers to the type of update being checked. Can be 'core', 'theme', 'plugin', or 'translation'.
Generally speaking, plugins, themes, and major core versions are not updated by default, while translations and minor and development versions for core are updated by default.
See the {
See also
'allow_dev_auto_core_updates', {
'allow_minor_auto_core_updates'}, and {
'allow_major_auto_core_updates'} filters for a more straightforward way to adjust core updates.
Since
3.7.0
Parameters
bool $update Whether to update.
object $item The update offer.
Definition at line 2730 of file class-wp-upgrader.php.
References $mysql_compat, $php_compat, $update, $wpdb, apply_filters(), Core_Upgrader\should_update_to_version(), and WP_CONTENT_DIR.
Referenced by core_upgrade_preamble().
update ($type, $item)
Update an item, if appropriate.
Since
3.7.0 public
Parameters
string $type The type of update being checked: 'core', 'theme', 'plugin', 'translation'.
object $item The update offer.
Returns
null|WP_Error
Fires immediately prior to an auto-update.
Since
4.4.0
Parameters
string $type The type of update being checked: 'core', 'theme', 'plugin', or 'translation'.
object $item The update offer.
string $context The filesystem context (a path) against which filesystem access and status should be checked.
Definition at line 2855 of file class-wp-upgrader.php.
References $theme, __, ABSPATH, add_filter(), do_action(), get_plugin_data(), get_theme_root(), is_wp_error(), object, WP_CONTENT_DIR, and wp_get_theme().
Field Documentation
$update_results = array() protected
Definition at line 2620 of file class-wp-upgrader.php.
The documentation for this class was generated from the following file:
class-wp-upgrader.php