GravityView: WP_Image_Editor_GD Class Reference
WP_Image_Editor_GD Class Reference
Public Member Functions
__destruct ()
crop ($src_x, $src_y, $src_w, $src_h, $dst_w=null, $dst_h=null, $src_abs=false)
Crops Image.
flip ($horz, $vert)
Flips current image.
load ()
Loads image from $this->file into new GD Resource.
multi_resize ($sizes)
Resize multiple images from a single source.
resize ($max_w, $max_h, $crop=false)
Resizes current image.
rotate ($angle)
Rotates current image counter-clockwise by $angle.
save ($filename=null, $mime_type=null)
Saves current in-memory image to file.
stream ($mime_type=null)
Returns stream of current image.
Public Member Functions inherited from WP_Image_Editor
__construct ($file)
Each instance handles a single file.
crop ($src_x, $src_y, $src_w, $src_h, $dst_w=null, $dst_h=null, $src_abs=false)
Crops Image.
flip ($horz, $vert)
Flips current image.
generate_filename ($suffix=null, $dest_path=null, $extension=null)
Builds an output filename based on current file, and adding proper suffix.
get_quality ()
Gets the Image Compression quality on a 1-100% scale.
get_size ()
Gets dimensions of image.
get_suffix ()
Builds and returns proper suffix for file based on height and width.
load ()
Loads image from $this->file into editor.
multi_resize ($sizes)
Resize multiple images from a single source.
resize ($max_w, $max_h, $crop=false)
Resizes current image.
rotate ($angle)
Rotates current image counter-clockwise by $angle.
save ($destfilename=null, $mime_type=null)
Saves current image to file.
set_quality ($quality=null)
Sets Image Compression quality on a 1-100% scale.
stream ($mime_type=null)
Streams current image to browser.
Static Public Member Functions
static supports_mime_type ($mime_type)
Checks to see if editor supports the mime-type specified.
static test ($args=array())
Checks to see if current environment supports GD.
Static Public Member Functions inherited from WP_Image_Editor
static supports_mime_type ($mime_type)
Checks to see if editor supports the mime-type specified.
static test ($args=array())
Checks to see if current environment supports the editor chosen.
Protected Member Functions
_resize ($max_w, $max_h, $crop=false)
_save ($image, $filename=null, $mime_type=null)
make_image ($filename, $function, $arguments)
Either calls editor's save function or handles file as a stream.
update_size ($width=false, $height=false)
Sets or updates current image size.
Protected Member Functions inherited from WP_Image_Editor
get_output_format ($filename=null, $mime_type=null)
Returns preferred mime-type and extension based on provided file's extension and mime, or current file's extension and mime.
make_image ($filename, $function, $arguments)
Either calls editor's save function or handles file as a stream.
update_size ($width=null, $height=null)
Sets current image size.
Protected Attributes
$image
Protected Attributes inherited from WP_Image_Editor
$default_mime_type = 'image/jpeg'
$default_quality = 90
$file = null
$mime_type = null
$quality = false
$size = null
Additional Inherited Members
Static Protected Member Functions inherited from WP_Image_Editor
static get_extension ($mime_type=null)
Returns first matched extension from Mime-type, as mapped from wp_get_mime_types()
static get_mime_type ($extension=null)
Returns first matched mime-type from extension, as mapped from wp_get_mime_types()
Detailed Description
Definition at line 17 of file class-wp-image-editor-gd.php.
Constructor & Destructor Documentation
__destruct ()
Definition at line 26 of file class-wp-image-editor-gd.php.
References image.
Member Function Documentation
_resize ($max_w, $max_h, $crop = false) protected
Parameters
int $max_w
int $max_h
bool | array $crop
Returns
resource|WP_Error
Definition at line 190 of file class-wp-image-editor-gd.php.
References __, image, image_resize_dimensions(), size, update_size(), and wp_imagecreatetruecolor().
Referenced by multi_resize(), and resize().
_save ($image, $filename = null, $mime_type = null) protected
Parameters
resource $image
string | null $filename
string | null $mime_type
Returns
WP_Error|array
Filter the name of the saved image file.
Since
2.6.0
Parameters
string $filename Name of the file.
Definition at line 400 of file class-wp-image-editor-gd.php.
References $image, WP_Image_Editor\$mime_type, __, apply_filters(), elseif, WP_Image_Editor\generate_filename(), WP_Image_Editor\get_output_format(), WP_Image_Editor\get_quality(), make_image(), null, size, and wp_basename().
Referenced by multi_resize(), and save().
crop ($src_x, $src_y, $src_w, $src_h, $dst_w = null, $dst_h = null, $src_abs = false)
Crops Image.
Since
3.5.0 public
Parameters
int $src_x The start x position to crop from.
int $src_y The start y position to crop from.
int $src_w The width to crop.
int $src_h The height to crop.
int $dst_w Optional. The destination width.
int $dst_h Optional. The destination height.
bool $src_abs Optional. If the source crop points are absolute.
Returns
bool|WP_Error
Definition at line 286 of file class-wp-image-editor-gd.php.
References __, image, update_size(), and wp_imagecreatetruecolor().
flip ($horz, $vert)
Flips current image.
Since
3.5.0 public
Parameters
bool $horz Flip along Horizontal Axis
bool $vert Flip along Vertical Axis
Returns
true|WP_Error
Definition at line 353 of file class-wp-image-editor-gd.php.
References __, image, size, and wp_imagecreatetruecolor().
load ()
Loads image from $this->file into new GD Resource.
Since
3.5.0 protected
Returns
bool|WP_Error True if loaded successfully; WP_Error on failure.
Filter the memory limit allocated for image manipulation.
Since
3.5.0
Parameters
int | string $limit Maximum memory limit to allocate for images. Default WP_MAX_MEMORY_LIMIT. Accepts an integer (bytes), or a shorthand string notation, such as '256M'.
Definition at line 92 of file class-wp-image-editor-gd.php.
References WP_Image_Editor\$size, __, apply_filters(), image, WP_Image_Editor\set_quality(), update_size(), and WP_MAX_MEMORY_LIMIT.
make_image ($filename, $function, $arguments) protected
Either calls editor's save function or handles file as a stream.
Since
3.5.0 protected
Parameters
string | stream $filename
callable $function
array $arguments
Returns
bool
Definition at line 483 of file class-wp-image-editor-gd.php.
References null, and wp_is_stream().
Referenced by _save().
multi_resize ($sizes)
Resize multiple images from a single source.
Since
3.5.0 public
Parameters
array $sizes { An array of image size arrays. Default sizes are 'small', 'medium', 'medium_large', 'large'.
Either a height or width must be provided. If one of the two is set to null, the resize will maintain aspect ratio according to the provided dimension.
array $size { Array of height, width values, and whether to crop.
int $width Image width. Optional if $height is specified. int $height Image height. Optional if $width is specified. bool $crop Optional. Whether to crop the image. Default false. } }
Returns
array An array of resized images' metadata by size.
Definition at line 231 of file class-wp-image-editor-gd.php.
References $image, $metadata, WP_Image_Editor\$size, _resize(), _save(), is_wp_error(), null, and size.
resize ($max_w, $max_h, $crop = false)
Resizes current image.
Wraps _resize, since _resize returns a GD Resource.
At minimum, either a height or width must be provided. If one of the two is set to null, the resize will maintain aspect ratio according to the provided dimension.
Since
3.5.0 public
Parameters
int | null $max_w Image width.
int | null $max_h Image height.
bool $crop
Returns
true|WP_Error
Definition at line 166 of file class-wp-image-editor-gd.php.
References __, _resize(), elseif, image, is_wp_error(), and size.
rotate ($angle)
Rotates current image counter-clockwise by $angle.
Ported from image-edit.php
Since
3.5.0 public
Parameters
float $angle
Returns
true|WP_Error
Definition at line 326 of file class-wp-image-editor-gd.php.
References __, image, and update_size().
save ($filename = null, $mime_type = null)
Saves current in-memory image to file.
Since
3.5.0 public
Parameters
string | null $filename
string | null $mime_type
Returns
array|WP_Error {'path'=>string, 'file'=>string, 'width'=>int, 'height'=>int, 'mime-type'=>string}
Definition at line 383 of file class-wp-image-editor-gd.php.
References WP_Image_Editor\$mime_type, _save(), image, and is_wp_error().
stream ($mime_type = null)
Returns stream of current image.
Since
3.5.0 public
Parameters
string $mime_type
Returns
bool
Definition at line 456 of file class-wp-image-editor-gd.php.
References WP_Image_Editor\$mime_type, WP_Image_Editor\get_output_format(), WP_Image_Editor\get_quality(), image, and null.
static supports_mime_type ($mime_type) static
Checks to see if editor supports the mime-type specified.
Since
3.5.0
public
Parameters
string $mime_type
Returns
bool
Definition at line 70 of file class-wp-image-editor-gd.php.
References WP_Image_Editor\$mime_type.
static test ($args = array()) static
Checks to see if current environment supports GD.
Since
3.5.0
public
Parameters
array $args
Returns
bool
Definition at line 44 of file class-wp-image-editor-gd.php.
update_size ($width = false, $height = false) protected
Sets or updates current image size.
Since
3.5.0 protected
Parameters
int $width
int $height
Returns
true
Definition at line 140 of file class-wp-image-editor-gd.php.
References image.
Referenced by _resize(), crop(), load(), and rotate().
Field Documentation
$image protected
Definition at line 24 of file class-wp-image-editor-gd.php.
Referenced by _save(), and multi_resize().
The documentation for this class was generated from the following file:
class-wp-image-editor-gd.php