GravityView: Config Class Reference
Config Class Reference
Public Member Functions
__construct (array $settings=array())
Config constructor.
get_default_settings ()
Gets the default settings for the Client and define dynamic defaults (like paths/css and paths/js)
get_display_name ()
Returns the display name for the vendor; otherwise, the title.
get_expiration_timestamp ($decay_time=null, $gmt=false)
Returns a timestamp that is the current time + decay time setting.
get_setting ($key, $default=null, $settings=array())
Helper Function: Get a specific setting or return a default value.
is_not_null ($input)
Filter out null input values.
meets_ssl_requirement ()
Checks whether SSL requirements are met.
ns ()
validate ()
Protected Member Functions
parse_settings ($config)
Validate and initialize settings array passed to the Client contructor.
Private Member Functions
get_array_value ($array, $prop, $default=null)
Get a specific property of an array without needing to check if that property exists.
get_multi_array_value ($array, $name, $default=null)
Gets a specific property value within a multidimensional array.
Private Attributes
$default_settings
$settings = array()
Static Private Attributes
static $reserved_namespaces = array('trustedlogin', 'client', 'vendor', 'admin', 'wordpress')
Detailed Description
Definition at line 24 of file Config.php.
Constructor & Destructor Documentation
__construct()
__construct (array $settings = array())
Config constructor.
Parameters
array $settings
Exceptions
Definition at line 99 of file Config.php.
References Config\$settings.
Member Function Documentation
get_array_value()
get_array_value ($array, $prop, $default = null) private
Get a specific property of an array without needing to check if that property exists.
Provide a default value if you want to return a specific value if the property is not set.
Parameters
array $array Array from which the property's value should be retrieved.
string $prop Name of the property to be retrieved.
string $default Optional. Value that should be returned if the property is not set or empty. Defaults to null.
Returns
null|string|mixed The value
Definition at line 370 of file Config.php.
References $value.
Referenced by Config\get_multi_array_value().
get_default_settings()
get_default_settings ()
Gets the default settings for the Client and define dynamic defaults (like paths/css and paths/js)
Since
1.0.0
Returns
array Array of default settings.
Definition at line 281 of file Config.php.
References Config\$default_settings.
Referenced by Config\get_setting(), and Config\parse_settings().
get_display_name()
get_display_name ()
Returns the display name for the vendor; otherwise, the title.
Returns
string
Definition at line 233 of file Config.php.
References Config\get_setting().
get_expiration_timestamp()
get_expiration_timestamp ($decay_time = null, $gmt = false)
Returns a timestamp that is the current time + decay time setting.
Note: This is a server timestamp, not a WordPress timestamp
Parameters
int $decay_time If passed, override the decay setting
bool $gmt Whether to use server time (false) or GMT time (true). Default: false.
Returns
int|false Timestamp in seconds. Default is WEEK_IN_SECONDS from creation (time() + 604800). False if no expiration.
Definition at line 213 of file Config.php.
References Config\get_setting().
get_multi_array_value()
get_multi_array_value ($array, $name, $default = null) private
Gets a specific property value within a multidimensional array.
Parameters
array $array The array to search in.
string $name The name of the property to find.
string $default Optional. Value that should be returned if the property is not set or empty. Defaults to null.
Returns
null|string|mixed The value
Definition at line 344 of file Config.php.
References $name, and Config\get_array_value().
Referenced by Config\get_setting().
get_setting()
get_setting ($key, $default = null, $settings = array())
Helper Function: Get a specific setting or return a default value.
Since
1.0.0
Parameters
string $key The setting to fetch, nested results are delimited with forward slashes (eg vendor/name => settings['vendor']['name'])
mixed $default - if no setting found or settings not init, return this value.
array $settings Pass an array to fetch value for instead of using the default settings array
Returns
string|array
Definition at line 318 of file Config.php.
References Config\$settings, Config\get_default_settings(), and Config\get_multi_array_value().
Referenced by Logging\__construct(), Config\get_display_name(), Config\get_expiration_timestamp(), Config\meets_ssl_requirement(), Config\ns(), and Config\validate().
is_not_null()
is_not_null ($input)
Filter out null input values.
Definition at line 270 of file Config.php.
meets_ssl_requirement()
meets_ssl_requirement ()
Checks whether SSL requirements are met.
Since
1.0.0
Returns
bool Whether the vendor-defined SSL requirements are met.
Definition at line 393 of file Config.php.
References Config\get_setting(), and Config\ns().
ns()
ns ()
Returns
string Vendor namespace, sanitized with dashes
Definition at line 294 of file Config.php.
References Config\get_setting().
Referenced by Logging\__construct(), Endpoint\__construct(), SupportUser\__construct(), Config\meets_ssl_requirement(), and Client\should_init().
parse_settings()
parse_settings ($config) protected
Validate and initialize settings array passed to the Client contructor.
Parameters
array | string $config Configuration array or JSON-encoded configuration array
Returns
bool|WP_Error[] true: Initialization succeeded; array of WP_Error objects if there are any issues.
Definition at line 244 of file Config.php.
References Config\get_default_settings().
validate()
validate ()
Returns
true|[]
Exceptions
Definition at line 114 of file Config.php.
References SupportRole\$prevented_caps, $url, $value, and Config\get_setting().
Referenced by Client\__construct().
Field Documentation
$default_settings
$default_settings private
Definition at line 36 of file Config.php.
Referenced by Config\get_default_settings().
$reserved_namespaces
$reserved_namespaces = array('trustedlogin', 'client', 'vendor', 'admin', 'wordpress') static private
Definition at line 29 of file Config.php.
$settings
$settings = array() private
Definition at line 90 of file Config.php.
Referenced by Config\__construct(), and Config\get_setting().
The documentation for this class was generated from the following file:
Config.php