GravityView: IXR_ClientMulticall Class Reference
IXR_ClientMulticall Class Reference
Public Member Functions
__construct ($server, $path=false, $port=80)
PHP5 constructor.
addCall ()
IXR_ClientMulticall ($server, $path=false, $port=80)
PHP4 constructor.
query ()
Public Member Functions inherited from IXR_Client
__construct ($server, $path=false, $port=80, $timeout=15)
PHP5 constructor.
getErrorCode ()
getErrorMessage ()
getResponse ()
isError ()
IXR_Client ($server, $path=false, $port=80, $timeout=15)
PHP4 constructor.
query ()
Data Fields
$calls = array()
Data Fields inherited from IXR_Client
$debug = false
$error = false
$headers = array()
$message = false
$path
$port
$response
$server
$timeout
$useragent
Detailed Description
Definition at line 1151 of file class-IXR.php.
Constructor & Destructor Documentation
__construct ($server, $path = false, $port = 80)
PHP5 constructor.
Definition at line 1158 of file class-IXR.php.
Referenced by query().
Member Function Documentation
addCall ()
Definition at line 1171 of file class-IXR.php.
Referenced by query().
IXR_ClientMulticall ($server, $path = false, $port = 80)
PHP4 constructor.
Definition at line 1167 of file class-IXR.php.
Referenced by query().
query ()
Definition at line 1182 of file class-IXR.php.
References $calls, __construct(), addCall(), and IXR_ClientMulticall().
Field Documentation
$calls = array()
Definition at line 1153 of file class-IXR.php.
Referenced by query().
The documentation for this class was generated from the following file:
class-IXR.php