GravityView: SupportUser Class Reference
SupportUser Class Reference
The TrustedLogin all-in-one drop-in class.
Public Member Functions
__construct (Config $config, Logging $logging)
SupportUser constructor.
__get ($name)
Allow accessing limited private properties with a magic method.
create ()
Create the Support User with custom role.
delete ($user_identifier='', $delete_role=true, $delete_endpoint=true)
Deletes support user(s) with options to delete the TrustedLogin-created user role and endpoint as well.
exists ()
Checks if a Support User for this vendor has already been created.
extend ($user_id, $site_identifier_hash, $expiration_timestamp=null, $cron=null)
Updates the scheduled cron job to auto-revoke and updates the Support User's meta.
get ($user_identifier_or_hash='')
Helper Function: Get the generated support user(s).
get_all ()
Get all users with the support role.
get_expiration (WP_User $user, $human_readable=false, $gmt=false)
Returns the expiration for user access as either a human-readable string or timestamp.
get_first ()
Returns the first support user active on the site, if any.
get_revoke_url ($user)
Returns admin URL to revoke support user.
get_secret_id ($user_identifier)
Returns the site secret ID connected to the support user.
get_site_hash ($user_id_or_object)
get_user_identifier ($user_id_or_object)
is_active ($passed_user=null)
Returns whether the support user exists and has an expiration time in the future.
maybe_login ($user_identifier)
Logs in a support user, if any exist at $user_identifier and haven't expired yet.
setup ($user_id, $site_identifier_hash, $expiration_timestamp=null, Cron $cron=null)
Schedules cron job to auto-revoke, adds user meta with unique ids.
Data Fields
$role
const ID_QUERY_PARAM = 'tlid'
Private Member Functions
generate_unique_username ()
Always return a unique username.
get_reassign_user_id ()
Get the ID of the best-guess appropriate admin user.
login (WP_User $support_user)
Processes login (with extra logging) and triggers the 'trustedlogin/{ns}/login' hook.
Private Attributes
$config
$created_by_meta_key
$expires_meta_key
$logging
$site_hash_meta_key
$user_identifier_meta_key
Detailed Description
The TrustedLogin all-in-one drop-in class.
Definition at line 28 of file SupportUser.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Logging $logging)
SupportUser constructor.
Definition at line 80 of file SupportUser.php.
References SupportUser\$config, SupportUser\$logging, and Config\ns().
Member Function Documentation
__get()
__get ($name)
Allow accessing limited private properties with a magic method.
Parameters
string $name Name of property
Returns
string|null Value of property, if defined. Otherwise, null.
Definition at line 98 of file SupportUser.php.
References $name.
create()
create ()
Create the Support User with custom role.
Since
1.0.0
wp_insert_user()
Returns
int|WP_Error - Array with login response information if created, or WP_Error object if there was an issue.
Definition at line 172 of file SupportUser.php.
References SupportUser\exists(), SupportUser\generate_unique_username(), and Encryption\get_random_hash().
delete()
delete ($user_identifier = '', $delete_role = true, $delete_endpoint = true)
Deletes support user(s) with options to delete the TrustedLogin-created user role and endpoint as well.
-by SupportUser::maybe_login() Called when user access has expired, but the cron didn't run... -by Client::revoke_access()
Parameters
string $user_identifier Unique identifier of the user to delete.
bool $delete_role Should the TrustedLogin-created user role be deleted also? Default: true.
bool $delete_endpoint Should the TrustedLogin endpoint for the site be deleted also? Default: true.
Returns
bool|WP_Error True: Successfully removed user and role; false: There are no support users matching $user_identifier; WP_Error: something went wrong.
Definition at line 458 of file SupportUser.php.
References $user, and SupportUser\get_reassign_user_id().
exists()
exists ()
Checks if a Support User for this vendor has already been created.
Since
1.0.0
Returns
int|false - WP User ID if support user exists, otherwise false.
Definition at line 119 of file SupportUser.php.
References $args, and SupportUser\$user_identifier_meta_key.
Referenced by SupportUser\create().
extend()
extend ($user_id, $site_identifier_hash, $expiration_timestamp = null, $cron = null)
Updates the scheduled cron job to auto-revoke and updates the Support User's meta.
Parameters
int $user_id ID of generated support user.
string $site_identifier_hash The unique identifier for the WP_User created {
See also
Encryption::get_random_hash()}
Parameters
int $expiration_timestamp Timestamp when user will be removed. Throws error if null/empty.
Cron | null $cron Optional. The Cron object for handling scheduling. Defaults to null.
Returns
string|WP_Error Value of $identifier_meta_key if worked; empty string or WP_Error if not.
Definition at line 578 of file SupportUser.php.
generate_unique_username()
generate_unique_username () private
Always return a unique username.
Returns
string Username, with possible number trailing, if clashes exist.
Definition at line 239 of file SupportUser.php.
References GV\$i.
Referenced by SupportUser\create().
get()
get ($user_identifier_or_hash = '')
Helper Function: Get the generated support user(s).
Since
1.0.0
Parameters
string $user_identifier_or_hash
Returns
WP_User|null WP_User if found; null if not
Definition at line 360 of file SupportUser.php.
References $args, $user, SupportUser\$user_identifier_meta_key, and Encryption\hash().
get_all()
get_all ()
Get all users with the support role.
Since
1.0.0
Returns
WP_User[]
Definition at line 412 of file SupportUser.php.
References $args.
Referenced by SupportUser\get_first().
get_expiration()
get_expiration (WP_User $user, $human_readable = false, $gmt = false)
Returns the expiration for user access as either a human-readable string or timestamp.
Parameters
WP_User $user
bool $human_readable Whether to show expiration as a human_time_diff()-formatted string. Default: false.
bool $gmt Whether to use GMT timestamp in the human-readable result. Not used if $human_readable is false. Default: false.
Returns
int|string|false False if no expiration is set. Expiration timestamp if $human_readable is false. Time diff if $human_readable is true.
Definition at line 394 of file SupportUser.php.
Referenced by SupportUser\is_active(), and SupportUser\maybe_login().
get_first()
get_first ()
Returns the first support user active on the site, if any.
Since
1.0.0
Returns
WP_User|null
Definition at line 436 of file SupportUser.php.
References SupportUser\get_all().
get_reassign_user_id()
get_reassign_user_id () private
Get the ID of the best-guess appropriate admin user.
Since
1.0.0
Returns
int|null User ID if there are admins, null if not
Definition at line 513 of file SupportUser.php.
Referenced by SupportUser\delete().
get_revoke_url()
get_revoke_url ($user)
Returns admin URL to revoke support user.
SupportUser::get_user_identifier()
Since
1.1 Removed second parameter $current_url.
Parameters
WP_User | int | string $user User object, user ID, or "all". If "all", will revoke all users.
Returns
string|false Unsanitized nonce URL to revoke support user. If not able to retrieve user identifier, returns false.
Definition at line 666 of file SupportUser.php.
References $user, SupportUser\get_user_identifier(), and Endpoint\REVOKE_SUPPORT_QUERY_PARAM.
get_secret_id()
get_secret_id ($user_identifier)
Returns the site secret ID connected to the support user.
Parameters
string $user_identifier
Returns
string|WP_Error|null Returns the secret ID. WP_Error if there was a problem generating any hashes. Null: No users were found using that user identifier.
Definition at line 263 of file SupportUser.php.
References $user, and SupportUser\get_site_hash().
get_site_hash()
get_site_hash ($user_id_or_object)
Parameters
WP_User | int $user_id_or_object User ID or User object
Returns
string|WP_Error User unique identifier if success; WP_Error if $user is not int or WP_User.
Definition at line 633 of file SupportUser.php.
Referenced by SupportUser\get_secret_id().
get_user_identifier()
get_user_identifier ($user_id_or_object)
Parameters
WP_User | int $user_id_or_object User ID or User object
Returns
string|WP_Error User unique identifier if success; WP_Error if $user is not int or WP_User.
Definition at line 606 of file SupportUser.php.
Referenced by SupportUser\get_revoke_url().
is_active()
is_active ($passed_user = null)
Returns whether the support user exists and has an expiration time in the future.
Since
1.0.2
Returns
bool True: Support user exists and has an expiration time in the future. False: Any of those things aren't true.
Definition at line 142 of file SupportUser.php.
References SupportUser\get_expiration().
Referenced by SupportUser\maybe_login().
login()
login (WP_User $support_user) private
Processes login (with extra logging) and triggers the 'trustedlogin/{ns}/login' hook.
Parameters
WP_User $support_user
Action run when TrustedLogin has logged-in
Definition at line 326 of file SupportUser.php.
Referenced by SupportUser\maybe_login().
maybe_login()
maybe_login ($user_identifier)
Logs in a support user, if any exist at $user_identifier and haven't expired yet.
If the user access has expired, deletes the user with {
See also
SupportUser::delete()}
Parameters
string $user_identifier Unique identifier for support user before being hashed.
Returns
true|WP_Error
Definition at line 291 of file SupportUser.php.
References SupportUser\get_expiration(), SupportUser\is_active(), and SupportUser\login().
setup()
setup ($user_id, $site_identifier_hash, $expiration_timestamp = null, Cron $cron = null)
Schedules cron job to auto-revoke, adds user meta with unique ids.
Parameters
int $user_id ID of generated support user
string $site_identifier_hash
int $decay_timestamp Timestamp when user will be removed
Returns
string|WP_Error Value of $identifier_meta_key if worked; empty string or WP_Error if not.
Definition at line 543 of file SupportUser.php.
References Encryption\hash().
Field Documentation
$config
Config $config private
Definition at line 38 of file SupportUser.php.
Referenced by SupportUser\__construct().
$created_by_meta_key
$created_by_meta_key private
Definition at line 75 of file SupportUser.php.
$expires_meta_key
$expires_meta_key private
Definition at line 69 of file SupportUser.php.
$logging
Logging $logging private
Definition at line 43 of file SupportUser.php.
Referenced by SupportUser\__construct().
$role
SupportRole $role
Definition at line 48 of file SupportUser.php.
$site_hash_meta_key
$site_hash_meta_key private
Definition at line 62 of file SupportUser.php.
$user_identifier_meta_key
$user_identifier_meta_key private
Definition at line 55 of file SupportUser.php.
Referenced by SupportUser\exists(), and SupportUser\get().
ID_QUERY_PARAM
const ID_QUERY_PARAM = 'tlid'
Definition at line 33 of file SupportUser.php.
Referenced by Endpoint\maybe_revoke_support().
The documentation for this class was generated from the following file:
SupportUser.php