GravityView: Core_Upgrader Class Reference
Core_Upgrader Class Reference
Core class used for updating core.
Public Member Functions
check_files ()
Compare the disk file checksums against the expected checksums.
upgrade ($current, $args=array())
Upgrade WordPress core.
upgrade_strings ()
Initialize the upgrade strings.
Public Member Functions inherited from WP_Upgrader
__construct ($skin=null)
Construct the upgrader with a skin.
clear_destination ($remote_destination)
Clears the directory where this item is going to be installed into.
download_package ($package)
Download a package.
fs_connect ($directories=array(), $allow_relaxed_file_ownership=false)
Connect to the filesystem.
generic_strings ()
Add the generic strings to WP_Upgrader::$strings.
init ()
Initialize the upgrader.
install_package ($args=array())
Install a package.
maintenance_mode ($enable=false)
Toggle maintenance mode for the site.
run ($options)
Run an upgrade/install.
unpack_package ($package, $delete_package=true)
Unpack a compressed package file.
Static Public Member Functions
static should_update_to_version ($offered_ver)
Determines if this WordPress Core version should update to an offered version or not.
Additional Inherited Members
Data Fields inherited from WP_Upgrader
$result = array()
$skin = null
The upgrader skin being used.
$strings = array()
The error/notification strings used to update the user on the progress.
$update_count = 0
The total number of updates being performed.
$update_current = 0
Detailed Description
Core class used for updating core.
It allows for WordPress to upgrade itself in combination with the wp-admin/includes/update-core.php file.
Since
2.8.0
See also
WP_Upgrader
Definition at line 2161 of file class-wp-upgrader.php.
Member Function Documentation
check_files ()
Compare the disk file checksums against the expected checksums.
Since
3.7.0 public
string $wp_version string $wp_local_package
Returns
bool True if the checksums match, otherwise false.
Definition at line 2471 of file class-wp-upgrader.php.
References $file, $wp_version, ABSPATH, and get_core_checksums().
Referenced by upgrade().
static should_update_to_version ($offered_ver) static
Determines if this WordPress Core version should update to an offered version or not.
Since
3.7.0 public
Parameters
string $offered_ver The offered version, of the format x.y.z.
Returns
bool True if we should update to the offered version, otherwise false.
Filter whether to enable automatic core updates for development versions.
Since
3.7.0
Parameters
bool $upgrade_dev Whether to enable automatic updates for development versions.
Filter whether to enable minor automatic core updates.
Since
3.7.0
Parameters
bool $upgrade_minor Whether to enable minor automatic core updates.
Filter whether to enable major automatic core updates.
Since
3.7.0
Parameters
bool $upgrade_major Whether to enable major automatic core updates.
Definition at line 2362 of file class-wp-upgrader.php.
References $wp_version, ABSPATH, apply_filters(), elseif, get_site_option(), and WPINC.
Referenced by WP_Automatic_Updater\should_update().
upgrade ($current, $args = array())
Upgrade WordPress core.
Since
2.8.0 public
WP_Filesystem_Base $wp_filesystem Subclass callable $_wp_filesystem_direct_method
Parameters
object $current Response object for whether WordPress is current.
array $args { Optional. Arguments for upgrading WordPress core. Default empty array.
bool $pre_check_md5 Whether to check the file checksums before attempting the upgrade. Default true. bool $attempt_rollback Whether to attempt to rollback the chances if there is a problem. Default false. bool $do_rollback Whether to perform this "upgrade" as a rollback. Default false. }
Returns
null|false|WP_Error False or WP_Error on failure, null on success.
This filter is documented in wp-admin/includes/update-core.php
This filter is documented in wp-admin/includes/update-core.php
This action is documented in wp-admin/includes/class-wp-upgrader.php
Definition at line 2202 of file class-wp-upgrader.php.
References $GLOBALS, WP_Upgrader\$result, $wp_version, __, ABSPATH, apply_filters(), check_files(), delete_site_transient(), do_action(), WP_Upgrader\download_package(), elseif, WP_Upgrader\fs_connect(), has_filter(), WP_Upgrader\init(), is_wp_error(), trailingslashit(), WP_Upgrader\unpack_package(), update_core(), upgrade_strings(), WP_CONTENT_DIR, wp_parse_args(), wp_version_check(), and WPINC.
upgrade_strings ()
Initialize the upgrade strings.
Since
2.8.0 public
Definition at line 2169 of file class-wp-upgrader.php.
References __.
Referenced by upgrade().
The documentation for this class was generated from the following file:
class-wp-upgrader.php