GravityView: GruntMakePOT Class Reference
GruntMakePOT Class Reference
POT generation methods for grunt-wp-i18n.
Public Member Functions
wp_plugin ($dir, $output, $slug=null, $excludes= '', $includes= '')
Generate a POT file for a plugin.
wp_theme ($dir, $output, $slug=null, $excludes= '', $includes= '')
Generate a POT file for a theme.
Public Member Functions inherited from MakePOT
__construct ($deprecated=true)
__destruct ()
bb ($dir, $output)
bp ($dir, $output)
generic ($dir, $output)
glotpress ($dir, $output)
guess_plugin_slug ($dir)
is_ms_file ($file_name)
is_not_ms_file ($file_name)
mu ($dir, $output)
realpath_missing ($path)
rosetta ($dir, $output)
tempnam ($file)
wp_admin ($dir, $output)
wp_core ($dir, $output)
wp_frontend ($dir, $output)
wp_generic ($dir, $args)
wp_ms ($dir, $output)
wp_network_admin ($dir, $output)
wp_plugin ($dir, $output, $slug=null)
wp_theme ($dir, $output, $slug=null)
wp_tz ($dir, $output)
wp_version ($dir)
wporg_bb_forums ($dir, $output)
xgettext ($project, $dir, $output_file, $placeholders=array(), $excludes=array(), $includes=array())
Data Fields
$projects
Valid project types.
Data Fields inherited from MakePOT
$max_header_lines = 30
$meta
$ms_files
$projects
$rules
$temp_files = array()
Protected Member Functions
normalize_patterns ($patterns)
Convert a string or array of exclusion/inclusion patterns into an array.
Additional Inherited Members
Static Public Member Functions inherited from MakePOT
static get_addon_header ($header, $source)
static get_first_lines ($filename, $lines=30)
Detailed Description
POT generation methods for grunt-wp-i18n.
Definition at line 7 of file grunt-makepot.php.
Member Function Documentation
normalize_patterns ($patterns) protected
Convert a string or array of exclusion/inclusion patterns into an array.
Parameters
string | array $patterns Comma-separated string or array of exclusion/inclusion patterns.
Returns
array
Definition at line 146 of file grunt-makepot.php.
Referenced by wp_plugin(), and wp_theme().
wp_plugin ($dir, $output, $slug = null, $excludes = '', $includes = '')
Generate a POT file for a plugin.
Parameters
string $dir Directory to search for gettext calls.
string $output POT file name.
string $slug Optional. Plugin slug.
string $excludes Optional. Comma-separated list of exclusion patterns.
string $includes Optional. Comma-separated list of inclusion patterns.
Returns
bool
Definition at line 28 of file grunt-makepot.php.
References $output, PotExtMeta\append(), MakePOT\get_addon_header(), MakePOT\get_first_lines(), MakePOT\guess_plugin_slug(), normalize_patterns(), and MakePOT\xgettext().
wp_theme ($dir, $output, $slug = null, $excludes = '', $includes = '')
Generate a POT file for a theme.
Parameters
string $dir Directory to search for gettext calls.
string $output POT file name.
string $slug Optional. Theme slug.
string $excludes Optional. Comma-separated list of exclusion patterns.
string $includes Optional. Comma-separated list of inclusion patterns.
Returns
bool
Definition at line 73 of file grunt-makepot.php.
References $output, PotExtMeta\append(), MakePOT\get_addon_header(), MakePOT\get_first_lines(), MakePOT\guess_plugin_slug(), normalize_patterns(), and MakePOT\xgettext().
Field Documentation
$projects
Initial value:
= array(
        'wp-plugin',
        'wp-theme',
    )
Valid project types.
array
Definition at line 13 of file grunt-makepot.php.
The documentation for this class was generated from the following file:
grunt-makepot.php