GravityView: WP_Http_Encoding Class Reference
WP_Http_Encoding Class Reference
Core class used to implement deflate and gzip transfer encoding support for HTTP requests.
Static Public Member Functions
static accept_encoding ($url, $args)
What encoding types to accept and their priority values.
static compatible_gzinflate ($gzData)
Decompression of deflated string while staying compatible with the majority of servers.
static compress ($raw, $level=9, $supports=null)
Compress raw string using the deflate format.
static content_encoding ()
What encoding the content used when it was compressed to send in the headers.
static decompress ($compressed, $length=null)
Decompression of deflated string.
static is_available ()
Whether decompression and compression are supported by the PHP version.
static should_decode ($headers)
Whether the content be decoded based on the headers.
Detailed Description
Core class used to implement deflate and gzip transfer encoding support for HTTP requests.
Includes RFC 1950, RFC 1951, and RFC 1952.
Since
2.8.0
Definition at line 17 of file class-wp-http-encoding.php.
Member Function Documentation
static accept_encoding ($url, $args) static
What encoding types to accept and their priority values.
Since
2.8.0
Parameters
string $url
array $args
Returns
string Types of encoding to accept.
Filter the allowed encoding types.
Since
3.6.0
Parameters
array $type Encoding types allowed. Accepts 'gzinflate', 'gzuncompress', 'gzdecode'.
string $url URL of the HTTP request.
array $args HTTP request arguments.
Definition at line 141 of file class-wp-http-encoding.php.
References $url, apply_filters(), and elseif.
Referenced by WP_Http\request().
static compatible_gzinflate ($gzData) static
Decompression of deflated string while staying compatible with the majority of servers.
Certain Servers will return deflated data with headers which PHP's gzinflate() function cannot handle out of the box. The following function has been created from various snippets on the gzinflate() PHP documentation.
Warning: Magic numbers within. Due to the potential different formats that the compressed data may be returned in, some "magic offsets" are needed to ensure proper decompression takes place. For a simple progmatic way to determine the magic offset in use, see: https://core.trac.wordpress.org/ticket/18273
Since
2.8.1 http://au2.php.net/manual/en/function.gzinflate.php#70875 http://au2.php.net/manual/en/function.gzinflate.php#77336 string $gzData String to decompress. string|bool False on failure.
Definition at line 99 of file class-wp-http-encoding.php.
References $i.
static compress ($raw, $level = 9, $supports = null) static
Compress raw string using the deflate format.
Supports the RFC 1951 standard.
Since
2.8.0
Parameters
string $raw String to compress.
int $level Optional, default is 9. Compression level, 9 is highest.
string $supports Optional, not used. When implemented it will choose the right compression based on what the server supports.
Returns
string|false False on failure.
Definition at line 33 of file class-wp-http-encoding.php.
static content_encoding () static
What encoding the content used when it was compressed to send in the headers.
Since
2.8.0
Returns
string Content-Encoding string to send in the header.
Definition at line 187 of file class-wp-http-encoding.php.
static decompress ($compressed, $length = null) static
Decompression of deflated string.
Will attempt to decompress using the RFC 1950 standard, and if that fails then the RFC 1951 standard deflate will be attempted. Finally, the RFC 1952 standard gzip decode will be attempted. If all fail, then the original compressed string will be returned.
Since
2.8.0
Parameters
string $compressed String to decompress.
int $length The optional length of the compressed data.
Returns
string|bool False on failure.
Definition at line 53 of file class-wp-http-encoding.php.
Referenced by WP_Http_Streams\request(), and WP_Http_Curl\request().
static is_available () static
Whether decompression and compression are supported by the PHP version.
Each function is tested instead of checking for the zlib extension, to ensure that the functions all exist in the PHP version and aren't disabled.
Since
2.8.0
Returns
bool
Definition at line 225 of file class-wp-http-encoding.php.
static should_decode ($headers) static
Whether the content be decoded based on the headers.
Since
2.8.0
Parameters
array | string $headers All of the available headers.
Returns
bool
Definition at line 201 of file class-wp-http-encoding.php.
References elseif.
Referenced by WP_Http_Streams\request(), and WP_Http_Curl\request().
The documentation for this class was generated from the following file:
class-wp-http-encoding.php