GravityView: SimplePie Class Reference
SimplePie Class Reference
Public Member Functions
__call ($method, $args)
Magic method handler.
__construct ()
The SimplePie class contains feed level data and options.
__destruct ()
Remove items that link back to this before destroying this object.
__toString ()
Used for converting object to a string.
enable_cache ($enable=true)
Enable/disable caching in SimplePie.
enable_order_by_date ($enable=true)
Set whether feed items should be sorted into reverse chronological order.
encode_instead_of_strip ($enable=true)
error ()
Get the error message for the occurred error.
force_feed ($enable=false)
Force the given data/URL to be treated as a feed.
force_fsockopen ($enable=false)
Force SimplePie to use fsockopen() instead of cURL.
get_all_discovered_feeds ()
get_author ($key=0)
Get an author for the feed.
get_authors ()
Get all authors for the feed.
get_base ($element=array())
Get the base URL value from the feed.
get_categories ()
Get all categories for the feed.
get_category ($key=0)
Get a category for the feed.
get_channel_tags ($namespace, $tag)
Get data for an channel-level element.
get_contributor ($key=0)
Get a contributor for the feed.
get_contributors ()
Get all contributors for the feed.
get_copyright ()
Get the copyright info for the feed.
get_description ()
Get the content for the item.
get_encoding ()
Get the character encoding used for output.
get_favicon ()
Get the favicon for the current feed.
get_feed_tags ($namespace, $tag)
Get data for an feed-level element.
get_image_height ()
Get the feed logo's height.
get_image_link ()
Get the feed logo's link.
get_image_tags ($namespace, $tag)
Get data for an channel-level element.
get_image_title ()
Get the feed logo's title.
get_image_url ()
Get the feed logo's URL.
get_image_width ()
Get the feed logo's link.
get_item ($key=0)
Get a single item from the feed.
get_item_quantity ($max=0)
Get the number of items in the feed.
get_items ($start=0, $end=0)
Get all items from the feed.
get_language ()
Get the language for the feed.
get_latitude ()
Get the latitude coordinates for the item.
get_link ($key=0, $rel= 'alternate')
Get a single link for the feed.
get_links ($rel= 'alternate')
Get all links for the feed.
get_longitude ()
Get the longitude coordinates for the feed.
get_permalink ()
Get the permalink for the item.
get_raw_data ()
Get the raw XML.
& get_registry ()
Get the class registry.
get_title ()
Get the title of the feed.
get_type ()
Get the type of the feed.
handle_content_type ($mime= 'text/html')
Send the content-type header with correct encoding.
init ()
Initialize the feed object.
remove_div ($enable=true)
sanitize ($data, $type, $base= '')
Sanitize feed data.
set_author_class ($class= 'SimplePie_Author')
Set which class SimplePie uses for handling author data.
set_autodiscovery_cache_duration ($seconds=604800)
Set the length of time (in seconds) that the autodiscovered feed URL will be cached.
set_autodiscovery_level ($level=SIMPLEPIE_LOCATOR_ALL)
Set how much feed autodiscovery to do.
set_cache_class ($class= 'SimplePie_Cache')
#@+ Useful when you are overloading or extending SimplePie's default classes.
set_cache_duration ($seconds=3600)
Set the length of time (in seconds) that the contents of a feed will be cached.
set_cache_location ($location= './cache')
Set the file system location where the cached files should be stored.
set_cache_name_function ($function= 'md5')
Set callback function to create cache filename with.
set_caption_class ($class= 'SimplePie_Caption')
Set which class SimplePie uses for <media:text> captions.
set_category_class ($class= 'SimplePie_Category')
Set which class SimplePie uses for handling category data.
set_content_type_sniffer_class ($class= 'SimplePie_Content_Type_Sniffer')
Set which class SimplePie uses for content-type sniffing.
set_copyright_class ($class= 'SimplePie_Copyright')
Set which class SimplePie uses for <media:copyright>
set_credit_class ($class= 'SimplePie_Credit')
Set which class SimplePie uses for <media:credit>
set_enclosure_class ($class= 'SimplePie_Enclosure')
Set which class SimplePie uses for feed enclosures.
set_favicon_handler ($page=false, $qs= 'i')
Set the favicon handler.
set_feed_url ($url)
Set the URL of the feed you want to parse.
set_file (&$file)
Set an instance of {.
set_file_class ($class= 'SimplePie_File')
Set which class SimplePie uses for remote file fetching.
set_image_handler ($page=false, $qs= 'i')
Set the handler to enable the display of cached images.
set_input_encoding ($encoding=false)
Set the character encoding used to parse the feed.
set_item_class ($class= 'SimplePie_Item')
Set which class SimplePie uses for handling feed items.
set_item_limit ($limit=0)
Set the limit for items returned per-feed with multifeeds.
set_locator_class ($class= 'SimplePie_Locator')
Set which class SimplePie uses for auto-discovery.
set_max_checked_feeds ($max=10)
Set maximum number of feeds to check with autodiscovery.
set_output_encoding ($encoding= 'UTF-8')
Set the output encoding.
set_parser_class ($class= 'SimplePie_Parser')
Set which class SimplePie uses for XML parsing.
set_rating_class ($class= 'SimplePie_Rating')
Set which class SimplePie uses for <media:rating>
set_raw_data ($data)
Set the raw XML data to parse.
set_restriction_class ($class= 'SimplePie_Restriction')
Set which class SimplePie uses for <media:restriction>
set_sanitize_class ($class= 'SimplePie_Sanitize')
Set which class SimplePie uses for data sanitization.
set_source_class ($class= 'SimplePie_Source')
Set which class SimplePie uses item sources.
set_stupidly_fast ($set=false)
Set options to make SP as fast as possible.
set_timeout ($timeout=10)
Set the the default timeout for fetching remote feeds.
set_url_replacements ($element_attribute=null)
Set element/attribute key/value pairs of HTML attributes containing URLs that need to be resolved relative to the feed.
set_useragent ($ua=SIMPLEPIE_USERAGENT)
#@-
strip_attributes ($attribs= '')
strip_comments ($strip=false)
strip_htmltags ($tags= '', $encode=null)
subscribe_url ()
Get the URL for the feed.
Static Public Member Functions
static merge_items ($urls, $start=0, $end=0, $limit=0)
Merge items from several feeds into one.
static sort_items ($a, $b)
Sorting callback for items.
Data Fields
$all_discovered_feeds = array()
$autodiscovery = SIMPLEPIE_LOCATOR_ALL
$autodiscovery_cache_duration = 604800
$cache = true
$cache_duration = 3600
$cache_location = './cache'
$cache_name_function = 'md5'
$config_settings = null
$data = array()
$error
$feed_url
$file
$force_feed = false
$force_fsockopen = false
$image_handler = ''
$input_encoding = false
$item_limit = 0
$max_checked_feeds = 10
$multifeed_objects = array()
$multifeed_url = array()
$order_by_date = true
$raw_data
$registry
$sanitize
$strip_attributes = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc')
$strip_htmltags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style')
$timeout = 10
$useragent = SIMPLEPIE_USERAGENT
Protected Member Functions
fetch_data (&$cache)
Fetch the data via SimplePie_File.
Detailed Description
Definition at line 473 of file class-simplepie.php.
Constructor & Destructor Documentation
__construct ()
The SimplePie class contains feed level data and options.
To use SimplePie, create the SimplePie object with no parameters. You can then set configuration options using the provided methods. After setting them, you must initialise the feed using $feed->init(). At that point the object's methods and properties will be available to you.
Previously, it was possible to pass in the feed URL along with cache options directly into the constructor. This has been removed as of 1.3 as it caused a lot of confusion.
Since
1.0 Preview Release
Definition at line 685 of file class-simplepie.php.
References init(), sanitize(), set_cache_duration(), set_cache_location(), and set_feed_url().
__destruct ()
Remove items that link back to this before destroying this object.
Definition at line 726 of file class-simplepie.php.
Member Function Documentation
__call ($method, $args)
Magic method handler.
Parameters
string $method Method name
array $args Arguments to the method
Returns
mixed
Definition at line 3023 of file class-simplepie.php.
References $class, and $file.
__toString ()
Used for converting object to a string.
Definition at line 718 of file class-simplepie.php.
enable_cache ($enable = true)
Enable/disable caching in SimplePie.
This option allows you to disable caching all-together in SimplePie. However, disabling the cache can lead to longer load times.
Since
1.0 Preview Release
Parameters
bool $enable Enable caching
Definition at line 863 of file class-simplepie.php.
enable_order_by_date ($enable = true)
Set whether feed items should be sorted into reverse chronological order.
Parameters
bool $enable Sort as reverse chronological order.
Definition at line 905 of file class-simplepie.php.
Referenced by set_stupidly_fast().
encode_instead_of_strip ($enable = true)
Definition at line 1168 of file class-simplepie.php.
References sanitize().
error ()
Get the error message for the occurred error.
Returns
string|array Error message, or array of messages for multifeeds
Definition at line 1619 of file class-simplepie.php.
References $error.
Referenced by fetch_data(), and init().
fetch_data (& $cache) protected
Fetch the data via SimplePie_File.
If the data is already cached, attempt to fetch it from there instead
Parameters
SimplePie_Cache | false $cache Cache handler, or false to not load from the cache
Returns
array|true Returns true if the data was loaded from the cache, or an array of HTTP headers and sniffed type
Definition at line 1458 of file class-simplepie.php.
References $cache, $file, elseif, error(), force_feed(), force_fsockopen(), init(), null, set_feed_url(), SIMPLEPIE_BUILD, SIMPLEPIE_FILE_SOURCE_REMOTE, and SIMPLEPIE_NAME.
Referenced by init().
force_feed ($enable = false)
Force the given data/URL to be treated as a feed.
This tells SimplePie to ignore the content-type provided by the server. Be careful when using this option, as it will also disable autodiscovery.
Since
1.1
Parameters
bool $enable Force the given data/URL to be treated as a feed
Definition at line 758 of file class-simplepie.php.
Referenced by fetch_data().
force_fsockopen ($enable = false)
Force SimplePie to use fsockopen() instead of cURL.
Since
1.0 Beta 3
Parameters
bool $enable Force fsockopen() to be used
Definition at line 849 of file class-simplepie.php.
Referenced by fetch_data().
get_all_discovered_feeds ()
Definition at line 2462 of file class-simplepie.php.
References $all_discovered_feeds.
get_author ($key = 0)
Get an author for the feed.
Since
1.1
Parameters
int $key The author that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Author|null
Definition at line 2165 of file class-simplepie.php.
References $authors, get_authors(), and null.
get_authors ()
Get all authors for the feed.
Uses <atom:author>, <author>, <dc:creator> or <itunes:author>
Since
1.1
Returns
array|null List of {
See also
SimplePie_Author} objects
Definition at line 2186 of file class-simplepie.php.
References $authors, $name, $url, get_base(), get_channel_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_ITUNES.
Referenced by get_author().
get_base ($element = array())
Get the base URL value from the feed.
Uses <xml:base> if available, otherwise uses the first link in the feed, or failing that, the URL of the feed itself.
See also
get_link
subscribe_url
Parameters
array $element
Returns
string
Definition at line 1998 of file class-simplepie.php.
References elseif, get_link(), get_type(), null, SIMPLEPIE_TYPE_RSS_SYNDICATION, and subscribe_url().
Referenced by get_authors(), get_contributors(), get_copyright(), get_description(), get_image_link(), get_image_url(), get_links(), and get_title().
get_categories ()
Get all categories for the feed.
Uses <atom:category>, <category> or <dc:subject>
Since
Unknown
Returns
array|null List of {
See also
SimplePie_Category} objects
Definition at line 2101 of file class-simplepie.php.
References $label, get_channel_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_category().
get_category ($key = 0)
Get a category for the feed.
Since
Unknown
Parameters
int $key The category that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Category|null
Definition at line 2080 of file class-simplepie.php.
References get_categories(), and null.
get_channel_tags ($namespace, $tag)
Get data for an channel-level element.
This method allows you to get access to ANY element/attribute in the channel/header section of the feed.
See {
See also
SimplePie::get_feed_tags()} for a description of the return value
Since
1.0
See also
http://simplepie.org/wiki/faq/supported_xml_namespaces
Parameters
string $namespace The URL of the XML namespace of the elements you're trying to access
string $tag Tag name
Returns
array
Definition at line 1893 of file class-simplepie.php.
References get_feed_tags(), get_type(), null, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_TYPE_ATOM_ALL, SIMPLEPIE_TYPE_RSS_090, SIMPLEPIE_TYPE_RSS_10, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
Referenced by get_authors(), get_categories(), get_contributors(), get_copyright(), get_description(), get_image_tags(), get_image_url(), get_items(), get_language(), get_latitude(), get_links(), get_longitude(), and get_title().
get_contributor ($key = 0)
Get a contributor for the feed.
Since
1.1
Parameters
int $key The contrbutor that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Author|null
Definition at line 2263 of file class-simplepie.php.
References get_contributors(), and null.
get_contributors ()
Get all contributors for the feed.
Uses <atom:contributor>
Since
1.1
Returns
array|null List of {
See also
SimplePie_Author} objects
Definition at line 2284 of file class-simplepie.php.
References $name, $url, get_base(), get_channel_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, and SIMPLEPIE_NAMESPACE_ATOM_10.
Referenced by get_contributor().
get_copyright ()
Get the copyright info for the feed.
Uses <atom:rights>, <atom:copyright> or <dc:rights>
Since
1.0 (previously called get_feed_copyright() since 0.8)
Returns
string|null
Definition at line 2528 of file class-simplepie.php.
References elseif, get_base(), get_channel_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
get_description ()
Get the content for the item.
Uses <atom:subtitle>, <atom:tagline>, <description>, <dc:description>, <itunes:summary> or <itunes:subtitle>
Since
1.0 (previously called get_feed_description() since 0.8)
Returns
string|null
Definition at line 2476 of file class-simplepie.php.
References elseif, get_base(), get_channel_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
get_encoding ()
Get the character encoding used for output.
Since
Preview Release
Returns
string
Definition at line 1643 of file class-simplepie.php.
References sanitize().
Referenced by handle_content_type().
get_favicon ()
Get the favicon for the current feed.
Definition at line 3003 of file class-simplepie.php.
References $url, get_link(), and null.
get_feed_tags ($namespace, $tag)
Get data for an feed-level element.
This method allows you to get access to ANY element/attribute that is a sub-element of the opening feed tag.
The return value is an indexed array of elements matching the given namespace and tag name. Each element has attribs, data and child subkeys. For attribs and child, these contain namespace subkeys. attribs then has one level of associative name => value data (where value is a string) after the namespace. child has tag-indexed keys after the namespace, each member of which is an indexed array matching this same format.
For example:
// This is probably a bad example because we already support
// <media:content> natively, but it shows you how to parse through
// the nodes.
$group = $item->get_item_tags(SIMPLEPIE_NAMESPACE_MEDIARSS, 'group');
$content = $group[0]['child'][SIMPLEPIE_NAMESPACE_MEDIARSS]['content'];
$file = $content[0]['attribs']['']['url'];
echo $file;
Since
1.0
See also
http://simplepie.org/wiki/faq/supported_xml_namespaces
Parameters
string $namespace The URL of the XML namespace of the elements you're trying to access
string $tag Tag name
Returns
array
Definition at line 1845 of file class-simplepie.php.
References get_type(), null, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RDF, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_TYPE_ATOM_03, SIMPLEPIE_TYPE_ATOM_10, SIMPLEPIE_TYPE_RSS_RDF, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
Referenced by get_channel_tags(), get_image_tags(), and get_items().
get_image_height ()
Get the feed logo's height.
RSS 2.0 feeds are allowed to have a "feed logo" height.
Uses <image><height> or defaults to 31.0 if no height is specified and the feed is an RSS 2.0 feed.
Returns
int|float|null
Definition at line 2809 of file class-simplepie.php.
References elseif, get_image_tags(), get_type(), null, SIMPLEPIE_NAMESPACE_RSS_20, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
get_image_link ()
Get the feed logo's link.
RSS 0.9.0, 1.0 and 2.0 feeds are allowed to have a "feed logo" link. This points to a human-readable page that the image should link to.
Uses <itunes:image>, <atom:logo>, <atom:icon>, <image><title> or <image><dc:title>
Returns
string|null
Definition at line 2753 of file class-simplepie.php.
References elseif, get_base(), get_image_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
get_image_tags ($namespace, $tag)
Get data for an channel-level element.
This method allows you to get access to ANY element/attribute in the image/logo section of the feed.
See {
See also
SimplePie::get_feed_tags()} for a description of the return value
Since
1.0
See also
http://simplepie.org/wiki/faq/supported_xml_namespaces
Parameters
string $namespace The URL of the XML namespace of the elements you're trying to access
string $tag Tag name
Returns
array
Definition at line 1950 of file class-simplepie.php.
References $image, get_channel_tags(), get_feed_tags(), get_type(), null, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_TYPE_RSS_090, SIMPLEPIE_TYPE_RSS_10, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
Referenced by get_image_height(), get_image_link(), get_image_title(), get_image_url(), and get_image_width().
get_image_title ()
Get the feed logo's title.
RSS 0.9.0, 1.0 and 2.0 feeds are allowed to have a "feed logo" title.
Uses <image><title> or <image><dc:title>
Returns
string|null
Definition at line 2670 of file class-simplepie.php.
References elseif, get_image_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
get_image_url ()
Get the feed logo's URL.
RSS 0.9.0, 2.0, Atom 1.0, and feeds with iTunes RSS tags are allowed to have a "feed logo" URL. This points directly to the image itself.
Uses <itunes:image>, <atom:logo>, <atom:icon>, <image><title> or <image><dc:title>
Returns
string|null
Definition at line 2709 of file class-simplepie.php.
References elseif, get_base(), get_channel_tags(), get_image_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
get_image_width ()
Get the feed logo's link.
RSS 2.0 feeds are allowed to have a "feed logo" width.
Uses <image><width> or defaults to 88.0 if no width is specified and the feed is an RSS 2.0 feed.
Returns
int|float|null
Definition at line 2783 of file class-simplepie.php.
References elseif, get_image_tags(), get_type(), null, SIMPLEPIE_NAMESPACE_RSS_20, and SIMPLEPIE_TYPE_RSS_SYNDICATION.
get_item ($key = 0)
Get a single item from the feed.
This is better suited for for() loops, whereas {
See also
get_items()} is better suited for foreach() loops.
get_item_quantity()
Since
Beta 2
Parameters
int $key The item that you want to return. Remember that arrays begin with 0, not 1
Returns
SimplePie_Item|null
Definition at line 2860 of file class-simplepie.php.
References get_items(), and null.
get_item_quantity ($max = 0)
Get the number of items in the feed.
This is well-suited for for() loops with {
See also
get_item()}
Parameters
int $max Maximum value to return. 0 for no limit
Returns
int Number of items in the feed
Definition at line 2834 of file class-simplepie.php.
References get_items().
get_items ($start = 0, $end = 0)
Get all items from the feed.
This is better suited for for() loops, whereas {
See also
get_items()} is better suited for foreach() loops.
get_item_quantity
Since
Beta 2
Parameters
int $start Index to start at
int $end Number of items to return. 0 for all items after $start
Returns
array|null List of {
See also
SimplePie_Item} objects
Definition at line 2886 of file class-simplepie.php.
References $keys, get_channel_tags(), get_feed_tags(), merge_items(), null, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_item(), and get_item_quantity().
get_language ()
Get the language for the feed.
Uses <language>, <dc:language>, or
Since
1.0 (previously called get_feed_language() since 0.8)
Returns
string|null
Definition at line 2564 of file class-simplepie.php.
References elseif, get_channel_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RDF, and SIMPLEPIE_NAMESPACE_RSS_20.
get_latitude ()
Get the latitude coordinates for the item.
Compatible with the W3C WGS84 Basic Geo and GeoRSS specifications
Uses <geo:lat> or <georss:point>
Since
1.0 W3C WGS84 Basic Geo http://www.georss.org/ GeoRSS string|null
Definition at line 2612 of file class-simplepie.php.
References elseif, get_channel_tags(), null, SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
get_link ($key = 0, $rel = 'alternate')
Get a single link for the feed.
Since
1.0 (previously called get_feed_link since Preview Release, get_feed_permalink() since 0.8)
Parameters
int $key The link that you want to return. Remember that arrays begin with 0, not 1
string $rel The relationship of the link to return
Returns
string|null Link URL
Definition at line 2350 of file class-simplepie.php.
References get_links(), and null.
Referenced by get_base(), get_favicon(), and get_permalink().
get_links ($rel = 'alternate')
Get all links for the feed.
Uses <atom:link> or <link>
Since
Beta 2
Parameters
string $rel The relationship of links to return
Returns
array|null Links found for the feed (strings)
Definition at line 2388 of file class-simplepie.php.
References $keys, $link, elseif, get_base(), get_channel_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_IANA_LINK_RELATIONS_REGISTRY, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_link().
get_longitude ()
Get the longitude coordinates for the feed.
Compatible with the W3C WGS84 Basic Geo and GeoRSS specifications
Uses <geo:long>, <geo:lon> or <georss:point>
Since
1.0 W3C WGS84 Basic Geo http://www.georss.org/ GeoRSS string|null
Definition at line 2641 of file class-simplepie.php.
References elseif, get_channel_tags(), null, SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
get_permalink ()
Get the permalink for the item.
Returns the first link available with a relationship of "alternate". Identical to {
See also
get_link()} with key 0
get_link
Since
1.0 (previously called get_feed_link since Preview Release, get_feed_permalink() since 0.8)
Definition at line 2374 of file class-simplepie.php.
References get_link().
get_raw_data ()
Get the raw XML.
This is the same as the old $feed->enable_xml_dump(true), but returns the data instead of printing it.
Returns
string|boolean Raw XML data, false if the cache is used
Definition at line 1632 of file class-simplepie.php.
References $raw_data.
& get_registry ()
Get the class registry.
Use this to override SimplePie's default classes
See also
SimplePie_Registry
Returns
SimplePie_Registry
Definition at line 954 of file class-simplepie.php.
References $registry.
get_title ()
Get the title of the feed.
Uses <atom:title>, <title> or <dc:title>
Since
1.0 (previously called get_feed_title since 0.8)
Returns
string|null
Definition at line 2037 of file class-simplepie.php.
References elseif, get_base(), get_channel_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
get_type ()
Get the type of the feed.
This returns a SIMPLEPIE_TYPE_* constant, which can be tested against using bitwise operators
Since
0.8 (usage changed to using constants in 1.0)
See also
SIMPLEPIE_TYPE_NONE Unknown.
SIMPLEPIE_TYPE_RSS_090 RSS 0.90.
SIMPLEPIE_TYPE_RSS_091_NETSCAPE RSS 0.91 (Netscape).
SIMPLEPIE_TYPE_RSS_091_USERLAND RSS 0.91 (Userland).
SIMPLEPIE_TYPE_RSS_091 RSS 0.91.
SIMPLEPIE_TYPE_RSS_092 RSS 0.92.
SIMPLEPIE_TYPE_RSS_093 RSS 0.93.
SIMPLEPIE_TYPE_RSS_094 RSS 0.94.
SIMPLEPIE_TYPE_RSS_10 RSS 1.0.
SIMPLEPIE_TYPE_RSS_20 RSS 2.0.x.
SIMPLEPIE_TYPE_RSS_RDF RDF-based RSS.
SIMPLEPIE_TYPE_RSS_SYNDICATION Non-RDF-based RSS (truly intended as syndication format).
SIMPLEPIE_TYPE_RSS_ALL Any version of RSS.
SIMPLEPIE_TYPE_ATOM_03 Atom 0.3.
SIMPLEPIE_TYPE_ATOM_10 Atom 1.0.
SIMPLEPIE_TYPE_ATOM_ALL Any version of Atom.
SIMPLEPIE_TYPE_ALL Any known/supported feed type.
Returns
int SIMPLEPIE_TYPE_* constant
Definition at line 1710 of file class-simplepie.php.
References elseif, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RDF, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_TYPE_ALL, SIMPLEPIE_TYPE_ATOM_03, SIMPLEPIE_TYPE_ATOM_10, SIMPLEPIE_TYPE_NONE, SIMPLEPIE_TYPE_RSS_090, SIMPLEPIE_TYPE_RSS_091, SIMPLEPIE_TYPE_RSS_091_NETSCAPE, SIMPLEPIE_TYPE_RSS_091_USERLAND, SIMPLEPIE_TYPE_RSS_092, SIMPLEPIE_TYPE_RSS_093, SIMPLEPIE_TYPE_RSS_094, SIMPLEPIE_TYPE_RSS_10, SIMPLEPIE_TYPE_RSS_20, and SIMPLEPIE_TYPE_RSS_ALL.
Referenced by get_base(), get_channel_tags(), get_feed_tags(), get_image_height(), get_image_tags(), get_image_width(), and init().
handle_content_type ($mime = 'text/html')
Send the content-type header with correct encoding.
This method ensures that the SimplePie-enabled page is being served with the correct mime-type and character encoding HTTP headers (character encoding determined by the {
See also
set_output_encoding} config option).
This won't work properly if any content or whitespace has already been sent to the browser, because it relies on PHP's header() function, and these are the circumstances under which the function works.
Because it's setting these settings for the entire page (as is the nature of HTTP headers), this should only be used once per page (again, at the top).
Parameters
string $mime MIME type to serve the page as
Definition at line 1667 of file class-simplepie.php.
References get_encoding().
init ()
Initialize the feed object.
This is what makes everything happen. Period. This is where all of the configuration options get processed, feeds are fetched, cached, and parsed, and all of that other good stuff.
Returns
boolean True if successful, false otherwise
Definition at line 1267 of file class-simplepie.php.
References $cache, $charset, $force_fsockopen, $i, $input_encoding, $timeout, $url, $useragent, elseif, error(), fetch_data(), get_type(), null, sanitize(), SIMPLEPIE_BUILD, and SIMPLEPIE_TYPE_NONE.
Referenced by __construct(), and fetch_data().
static merge_items ($urls, $start = 0, $end = 0, $limit = 0) static
Merge items from several feeds into one.
If you're merging multiple feeds together, they need to all have dates for the items or else SimplePie will refuse to sort them.
array $urls List of SimplePie feed objects to merge int $start Starting item int $end Number of items to return int $limit Maximum number of items per feed array
Definition at line 3071 of file class-simplepie.php.
References null.
Referenced by get_items().
remove_div ($enable = true)
Definition at line 1150 of file class-simplepie.php.
References sanitize().
Referenced by set_stupidly_fast().
sanitize ($data, $type, $base = '')
Sanitize feed data.
private
See also
SimplePie_Sanitize::sanitize()
Parameters
string $data Data to sanitize
int $type One of the SIMPLEPIE_CONSTRUCT_* constants
string $base Base URL to resolve URLs against
Returns
string Sanitized data
Definition at line 2024 of file class-simplepie.php.
References $data.
Referenced by __construct(), encode_instead_of_strip(), get_authors(), get_categories(), get_contributors(), get_copyright(), get_description(), get_encoding(), get_image_link(), get_image_title(), get_image_url(), get_language(), get_links(), get_title(), init(), remove_div(), set_image_handler(), set_output_encoding(), set_url_replacements(), strip_attributes(), strip_comments(), strip_htmltags(), and subscribe_url().
set_author_class ($class = 'SimplePie_Author')
Set which class SimplePie uses for handling author data.
Definition at line 1018 of file class-simplepie.php.
References $class.
set_autodiscovery_cache_duration ($seconds = 604800)
Set the length of time (in seconds) that the autodiscovered feed URL will be cached.
Parameters
int $seconds The autodiscovered feed URL cache duration.
Definition at line 885 of file class-simplepie.php.
set_autodiscovery_level ($level = SIMPLEPIE_LOCATOR_ALL)
Set how much feed autodiscovery to do.
See also
SIMPLEPIE_LOCATOR_NONE
SIMPLEPIE_LOCATOR_AUTODISCOVERY
SIMPLEPIE_LOCATOR_LOCAL_EXTENSION
SIMPLEPIE_LOCATOR_LOCAL_BODY
SIMPLEPIE_LOCATOR_REMOTE_EXTENSION
SIMPLEPIE_LOCATOR_REMOTE_BODY
SIMPLEPIE_LOCATOR_ALL
Parameters
int $level Feed Autodiscovery Level (level can be a combination of the above constants, see bitwise OR operator)
Definition at line 942 of file class-simplepie.php.
set_cache_class ($class = 'SimplePie_Cache')
#@+ Useful when you are overloading or extending SimplePie's default classes.
Set which class SimplePie uses for caching
Definition at line 970 of file class-simplepie.php.
References $class.
set_cache_duration ($seconds = 3600)
Set the length of time (in seconds) that the contents of a feed will be cached.
Parameters
int $seconds The feed content cache duration
Definition at line 874 of file class-simplepie.php.
Referenced by __construct().
set_cache_location ($location = './cache')
Set the file system location where the cached files should be stored.
Parameters
string $location The file system location.
Definition at line 895 of file class-simplepie.php.
References $location.
Referenced by __construct().
set_cache_name_function ($function = 'md5')
Set callback function to create cache filename with.
Parameters
mixed $function Callback function
Definition at line 1111 of file class-simplepie.php.
set_caption_class ($class = 'SimplePie_Caption')
Set which class SimplePie uses for <media:text> captions.
Definition at line 1042 of file class-simplepie.php.
References $class.
set_category_class ($class = 'SimplePie_Category')
Set which class SimplePie uses for handling category data.
Definition at line 1026 of file class-simplepie.php.
References $class.
set_content_type_sniffer_class ($class = 'SimplePie_Content_Type_Sniffer')
Set which class SimplePie uses for content-type sniffing.
Definition at line 1082 of file class-simplepie.php.
References $class.
set_copyright_class ($class = 'SimplePie_Copyright')
Set which class SimplePie uses for <media:copyright>
Definition at line 1050 of file class-simplepie.php.
References $class.
set_credit_class ($class = 'SimplePie_Credit')
Set which class SimplePie uses for <media:credit>
Definition at line 1058 of file class-simplepie.php.
References $class.
set_enclosure_class ($class = 'SimplePie_Enclosure')
Set which class SimplePie uses for feed enclosures.
Definition at line 1034 of file class-simplepie.php.
References $class.
set_favicon_handler ($page = false, $qs = 'i')
Set the favicon handler.
Definition at line 2991 of file class-simplepie.php.
set_feed_url ($url)
Set the URL of the feed you want to parse.
This allows you to enter the URL of the feed you want to parse, or the website you want to try to use auto-discovery on. This takes priority over any set raw data.
You can set multiple feeds to mash together by passing an array instead of a string for the $url. Remember that with each additional feed comes additional processing and resources.
Since
1.0 Preview Release
See also
set_raw_data()
Parameters
string | array $url This is the URL (or array of URLs) that you want to parse.
Definition at line 778 of file class-simplepie.php.
References $url, and $value.
Referenced by __construct(), and fetch_data().
set_file (& $file)
Set an instance of {.
See also
SimplePie_File} to use as a feed
Parameters
SimplePie_File &$file
Returns
bool True on success, false on failure
Definition at line 800 of file class-simplepie.php.
References $file.
set_file_class ($class = 'SimplePie_File')
Set which class SimplePie uses for remote file fetching.
Definition at line 994 of file class-simplepie.php.
References $class.
set_image_handler ($page = false, $qs = 'i')
Set the handler to enable the display of cached images.
Parameters
str $page Web-accessible path to the handler_image.php file.
str $qs The query string that the value should be passed to.
Definition at line 1236 of file class-simplepie.php.
References $page, and sanitize().
Referenced by set_stupidly_fast().
set_input_encoding ($encoding = false)
Set the character encoding used to parse the feed.
This overrides the encoding reported by the feed, however it will fall back to the normal encoding detection if the override fails
Parameters
string $encoding Character encoding
Definition at line 918 of file class-simplepie.php.
set_item_class ($class = 'SimplePie_Item')
Set which class SimplePie uses for handling feed items.
Definition at line 1010 of file class-simplepie.php.
References $class.
set_item_limit ($limit = 0)
Set the limit for items returned per-feed with multifeeds.
Parameters
integer $limit The maximum number of items to return.
Definition at line 1253 of file class-simplepie.php.
set_locator_class ($class = 'SimplePie_Locator')
Set which class SimplePie uses for auto-discovery.
Definition at line 978 of file class-simplepie.php.
References $class.
set_max_checked_feeds ($max = 10)
Set maximum number of feeds to check with autodiscovery.
Parameters
int $max Maximum number of feeds to check
Definition at line 1145 of file class-simplepie.php.
set_output_encoding ($encoding = 'UTF-8')
Set the output encoding.
Allows you to override SimplePie's output to match that of your webpage. This is useful for times when your webpages are not being served as UTF-8. This setting will be obeyed by {
See also
handle_content_type()}, and is similar to {
set_input_encoding()}.
It should be noted, however, that not all character encodings can support all characters. If your page is being served as ISO-8859-1 and you try to display a Japanese feed, you'll likely see garbled characters. Because of this, it is highly recommended to ensure that your webpages are served as UTF-8.
The number of supported character encodings depends on whether your web host supports mbstring, iconv, or both. See http://simplepie.org/wiki/faq/Supported_Character_Encodings for more information.
Parameters
string $encoding
Definition at line 1204 of file class-simplepie.php.
References sanitize().
set_parser_class ($class = 'SimplePie_Parser')
Set which class SimplePie uses for XML parsing.
Definition at line 986 of file class-simplepie.php.
References $class.
set_rating_class ($class = 'SimplePie_Rating')
Set which class SimplePie uses for <media:rating>
Definition at line 1066 of file class-simplepie.php.
References $class.
set_raw_data ($data)
Set the raw XML data to parse.
Allows you to use a string of RSS/Atom data instead of a remote feed.
If you have a feed available as a string in PHP, you can tell SimplePie to parse that data string instead of a remote feed. Any set feed URL takes precedence.
Since
1.0 Beta 3
Parameters
string $data RSS or Atom data as a string.
See also
set_feed_url()
Definition at line 824 of file class-simplepie.php.
References $data.
set_restriction_class ($class = 'SimplePie_Restriction')
Set which class SimplePie uses for <media:restriction>
Definition at line 1074 of file class-simplepie.php.
References $class.
set_sanitize_class ($class = 'SimplePie_Sanitize')
Set which class SimplePie uses for data sanitization.
Definition at line 1002 of file class-simplepie.php.
References $class.
set_source_class ($class = 'SimplePie_Source')
Set which class SimplePie uses item sources.
Definition at line 1090 of file class-simplepie.php.
References $class.
set_stupidly_fast ($set = false)
Set options to make SP as fast as possible.
Forgoes a substantial amount of data sanitization in favor of speed. This turns SimplePie into a dumb parser of feeds.
Parameters
bool $set Whether to set them or not
Definition at line 1127 of file class-simplepie.php.
References enable_order_by_date(), remove_div(), set_image_handler(), strip_attributes(), strip_comments(), and strip_htmltags().
set_timeout ($timeout = 10)
Set the the default timeout for fetching remote feeds.
This allows you to change the maximum time the feed's server to respond and send the feed back.
Since
1.0 Beta 3
Parameters
int $timeout The maximum number of seconds to spend waiting to retrieve a feed.
Definition at line 838 of file class-simplepie.php.
References $timeout.
set_url_replacements ($element_attribute = null)
Set element/attribute key/value pairs of HTML attributes containing URLs that need to be resolved relative to the feed.
Defaults to |a|, |area|, |blockquote|
Definition at line 1225 of file class-simplepie.php.
References sanitize().
set_useragent ($ua = SIMPLEPIE_USERAGENT)
#@-
Set the user agent string
Parameters
string $ua New user agent string.
Definition at line 1101 of file class-simplepie.php.
static sort_items ($a, $b) static
Sorting callback for items.
private
Parameters
SimplePie $a
SimplePie $b
Returns
boolean
Definition at line 3053 of file class-simplepie.php.
array Stores the default attributes to be stripped by strip_attributes ($attribs = '')
See also
SimplePie::strip_attributes() private
Definition at line 1173 of file class-simplepie.php.
References $strip_attributes, and sanitize().
Referenced by set_stupidly_fast().
strip_comments ($strip = false)
Definition at line 1209 of file class-simplepie.php.
References sanitize().
Referenced by set_stupidly_fast().
array Stores the default tags to be stripped by strip_htmltags ($tags = '', $encode = null)
See also
SimplePie::strip_htmltags() private
Definition at line 1155 of file class-simplepie.php.
References $strip_htmltags, $tags, null, and sanitize().
Referenced by set_stupidly_fast().
subscribe_url ()
Get the URL for the feed.
May or may not be different from the URL passed to {
See also
set_feed_url()}, depending on whether auto-discovery was used.
Since
Preview Release (previously called get_feed_url() since SimplePie 0.8.)
Definition at line 1802 of file class-simplepie.php.
References null, sanitize(), and SIMPLEPIE_CONSTRUCT_IRI.
Referenced by get_base().
Field Documentation
$all_discovered_feeds = array()
Definition at line 621 of file class-simplepie.php.
Referenced by get_all_discovered_feeds().
$autodiscovery = SIMPLEPIE_LOCATOR_ALL
Definition at line 600 of file class-simplepie.php.
$autodiscovery_cache_duration = 604800
Definition at line 564 of file class-simplepie.php.
$cache = true
Definition at line 550 of file class-simplepie.php.
Referenced by fetch_data(), and init().
$cache_duration = 3600
Definition at line 557 of file class-simplepie.php.
$cache_location = './cache'
Definition at line 571 of file class-simplepie.php.
$cache_name_function = 'md5'
Definition at line 578 of file class-simplepie.php.
$config_settings = null
Definition at line 648 of file class-simplepie.php.
$data = array()
Definition at line 479 of file class-simplepie.php.
Referenced by sanitize(), and set_raw_data().
$error
Definition at line 485 of file class-simplepie.php.
Referenced by error().
$feed_url
Definition at line 506 of file class-simplepie.php.
$file
Definition at line 513 of file class-simplepie.php.
Referenced by __call(), fetch_data(), and set_file().
$force_feed = false
Definition at line 543 of file class-simplepie.php.
$force_fsockopen = false
Definition at line 535 of file class-simplepie.php.
Referenced by init().
$image_handler = ''
Definition at line 628 of file class-simplepie.php.
$input_encoding = false
Definition at line 593 of file class-simplepie.php.
Referenced by init().
$item_limit = 0
Definition at line 655 of file class-simplepie.php.
$max_checked_feeds = 10
Definition at line 614 of file class-simplepie.php.
$multifeed_objects = array()
Definition at line 641 of file class-simplepie.php.
$multifeed_url = array()
Definition at line 635 of file class-simplepie.php.
$order_by_date = true
Definition at line 585 of file class-simplepie.php.
$raw_data
Definition at line 520 of file class-simplepie.php.
Referenced by get_raw_data().
$registry
Definition at line 607 of file class-simplepie.php.
Referenced by get_registry().
$sanitize
Definition at line 492 of file class-simplepie.php.
$strip_attributes = array('bgsound', 'class', 'expr', 'id', 'style', 'onclick', 'onerror', 'onfinish', 'onmouseover', 'onmouseout', 'onfocus', 'onblur', 'lowsrc', 'dynsrc')
Definition at line 662 of file class-simplepie.php.
Referenced by strip_attributes().
$strip_htmltags = array('base', 'blink', 'body', 'doctype', 'embed', 'font', 'form', 'frame', 'frameset', 'html', 'iframe', 'input', 'marquee', 'meta', 'noscript', 'object', 'param', 'script', 'style')
Definition at line 669 of file class-simplepie.php.
Referenced by strip_htmltags().
$timeout = 10
Definition at line 527 of file class-simplepie.php.
Referenced by init(), and set_timeout().
$useragent = SIMPLEPIE_USERAGENT
Definition at line 499 of file class-simplepie.php.
Referenced by init().
The documentation for this class was generated from the following file:
class-simplepie.php