GravityView: getid3_apetag Class Reference
getid3_apetag Class Reference
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Public Member Functions
Analyze ()
APEcontentTypeFlagLookup ($contenttypeid)
APEtagItemIsUTF8Lookup ($itemkey)
parseAPEheaderFooter ($APEheaderFooterData)
parseAPEtagFlags ($rawflagint)
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Data Fields
$inline_attachments = true
$overrideendoffset = 0
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Definition at line 17 of file module.tag.apetag.php.
Member Function Documentation
Analyze ()
Definition at line 22 of file module.tag.apetag.php.
References $comment, $i, $overrideendoffset, $value, elseif, getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\ftell(), getid3_lib\GetDataImageSize(), getid3_lib\intValueSupported(), getid3_lib\LittleEndian2Int(), parseAPEheaderFooter(), parseAPEtagFlags(), and str_replace.
APEcontentTypeFlagLookup ($contenttypeid)
Definition at line 373 of file module.tag.apetag.php.
Referenced by parseAPEtagFlags().
APEtagItemIsUTF8Lookup ($itemkey)
Definition at line 383 of file module.tag.apetag.php.
parseAPEheaderFooter ($APEheaderFooterData)
Definition at line 334 of file module.tag.apetag.php.
References getid3_lib\LittleEndian2Int(), and parseAPEtagFlags().
Referenced by Analyze().
parseAPEtagFlags ($rawflagint)
Definition at line 358 of file module.tag.apetag.php.
References APEcontentTypeFlagLookup().
Referenced by Analyze(), and parseAPEheaderFooter().
Field Documentation
$inline_attachments = true
Definition at line 19 of file module.tag.apetag.php.
$overrideendoffset = 0
Definition at line 20 of file module.tag.apetag.php.
Referenced by Analyze().
The documentation for this class was generated from the following file:
module.tag.apetag.php