GravityView: Addon_Settings Class Reference
Addon_Settings Class Reference
If this file is called directly, abort.
Public Member Functions
__construct ()
add_network_menu ()
Add global Settings page for Multisite.
current_user_can_any ($caps)
Prevent uninstall tab from being shown by returning false for the uninstall capability check.
init_admin ()
Run actions when initializing admin.
init_ajax ()
Load license handler in admin-ajax.php.
modify_app_settings_menu_title ($setting_tabs)
Change the settings page header title to "GravityView".
uninstall ()
Uninstall all traces of GravityView.
uninstall_form ()
Display a feedback form when the plugin is uninstalled.
uninstall_warning_message ()
Data Fields
$app_hook_suffix = 'gravityview'
padding __pad0__: .5em .75em
margin __pad1__: .1em
number scale label
font size: 1.2em
Protected Attributes
$_capabilities_app_menu = 'gravityview_view_settings'
$_capabilities_app_settings = 'gravityview_view_settings'
$_capabilities_uninstall = 'gravityview_uninstall'
$_short_title = 'GravityView'
$_slug = 'gravityview'
$_title = 'GravityView'
Private Member Functions
_load_license_handler ()
Make sure the license handler is available.
get_uninstall_reasons ()
Get an array of reasons why the plugin might be uninstalled.
Private Attributes
$License_Handler
Static Private Attributes
static $initialized = false
Detailed Description
If this file is called directly, abort.
The Addon Settings class.
Uses internal GFAddOn APIs.
Definition at line 18 of file class-gv-settings-addon.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Hook everywhere, but only once.
Definition at line 64 of file class-gv-settings-addon.php.
Member Function Documentation
_load_license_handler()
_load_license_handler () private
Make sure the license handler is available.
Returns
void
Definition at line 123 of file class-gv-settings-addon.php.
References GV\get().
add_network_menu()
add_network_menu ()
Add global Settings page for Multisite.
Since
1.7.6
Returns
void
Definition at line 135 of file class-gv-settings-addon.php.
References gravityview().
current_user_can_any()
current_user_can_any ($caps)
Prevent uninstall tab from being shown by returning false for the uninstall capability check.
Otherwise:
Parameters
array | string $caps
Returns
bool
Definition at line 174 of file class-gv-settings-addon.php.
get_uninstall_reasons()
get_uninstall_reasons () private
Get an array of reasons why the plugin might be uninstalled.
Since
1.17.5
Returns
array Array of reasons with the label and followup questions for each uninstall reason
Definition at line 194 of file class-gv-settings-addon.php.
References GV\$reasons.
init_admin()
init_admin ()
Run actions when initializing admin.
Triggers the license key notice, et.c
Returns
void
Since
1.7.6
Definition at line 84 of file class-gv-settings-addon.php.
init_ajax()
init_ajax ()
Load license handler in admin-ajax.php.
Returns
void
Definition at line 114 of file class-gv-settings-addon.php.
modify_app_settings_menu_title()
modify_app_settings_menu_title ($setting_tabs)
Change the settings page header title to "GravityView".
Parameters
$setting_tabs
Returns
array
Definition at line 104 of file class-gv-settings-addon.php.
uninstall()
uninstall ()
Uninstall all traces of GravityView.
Note: method is public because parent method is public
Returns
bool
Set the path so that Gravity Forms can de-activate GravityView
See also
GFAddOn::uninstall_addon deactivate_plugins()
Definition at line 151 of file class-gv-settings-addon.php.
References gravityview(), and GRAVITYVIEW_FILE.
uninstall_form()
uninstall_form ()
Display a feedback form when the plugin is uninstalled.
Since
1.17.5
Returns
string HTML of the uninstallation form
Definition at line 226 of file class-gv-settings-addon.php.
References $user.
uninstall_warning_message()
uninstall_warning_message ()
Definition at line 181 of file class-gv-settings-addon.php.
Field Documentation
$_capabilities_app_menu
$_capabilities_app_menu = 'gravityview_view_settings' protected
Definition at line 47 of file class-gv-settings-addon.php.
$_capabilities_app_settings
$_capabilities_app_settings = 'gravityview_view_settings' protected
Definition at line 42 of file class-gv-settings-addon.php.
$_capabilities_uninstall
$_capabilities_uninstall = 'gravityview_uninstall' protected
Definition at line 37 of file class-gv-settings-addon.php.
$_short_title
$_short_title = 'GravityView' protected
Definition at line 27 of file class-gv-settings-addon.php.
$_slug
$_slug = 'gravityview' protected
Definition at line 32 of file class-gv-settings-addon.php.
$_title
$_title = 'GravityView' protected
Definition at line 22 of file class-gv-settings-addon.php.
$app_hook_suffix
$app_hook_suffix = 'gravityview'
Definition at line 52 of file class-gv-settings-addon.php.
$initialized
$initialized = false static private
Definition at line 62 of file class-gv-settings-addon.php.
$License_Handler
$License_Handler private
Definition at line 57 of file class-gv-settings-addon.php.
__pad0__
padding __pad0__
Definition at line 237 of file class-gv-settings-addon.php.
__pad1__
margin __pad1__
Definition at line 238 of file class-gv-settings-addon.php.
label
number scale label
Initial value:
{
            border: 1px solid #cccccc
Definition at line 235 of file class-gv-settings-addon.php.
size
font size
Definition at line 241 of file class-gv-settings-addon.php.
The documentation for this class was generated from the following file:
class-gv-settings-addon.php