GravityView: SimplePie_Enclosure Class Reference
SimplePie_Enclosure Class Reference
Public Member Functions
__construct ($link=null, $type=null, $length=null, $javascript=null, $bitrate=null, $captions=null, $categories=null, $channels=null, $copyright=null, $credits=null, $description=null, $duration=null, $expression=null, $framerate=null, $hashes=null, $height=null, $keywords=null, $lang=null, $medium=null, $player=null, $ratings=null, $restrictions=null, $samplingrate=null, $thumbnails=null, $title=null, $width=null)
Constructor, used to input the data.
__toString ()
String-ified version.
embed ($options= '', $native=false)
Embed the enclosure using Javascript.
get_bitrate ()
Get the bitrate.
get_caption ($key=0)
Get a single caption.
get_captions ()
Get all captions.
get_categories ()
Get all categories.
get_category ($key=0)
Get a single category.
get_channels ()
Get the number of audio channels.
get_copyright ()
Get the copyright information.
get_credit ($key=0)
Get a single credit.
get_credits ()
Get all credits.
get_description ()
Get the description of the enclosure.
get_duration ($convert=false)
Get the duration of the enclosure.
get_expression ()
Get the expression.
get_extension ()
Get the file extension.
get_framerate ()
Get the framerate (in frames-per-second)
get_handler ()
Get the preferred handler.
get_hash ($key=0)
Get a single hash.
get_hashes ()
Get all credits.
get_height ()
Get the height.
get_keyword ($key=0)
Get a single keyword.
get_keywords ()
Get all keywords.
get_language ()
Get the language.
get_length ()
Get length.
get_link ()
Get the URL.
get_medium ()
Get the medium.
get_player ()
Get the player URL.
get_rating ($key=0)
Get a single rating.
get_ratings ()
Get all ratings.
get_real_type ($find_handler=false)
Get the real media type.
get_restriction ($key=0)
Get a single restriction.
get_restrictions ()
Get all restrictions.
get_sampling_rate ()
Get the sampling rate (in kHz)
get_size ()
Get the file size (in MiB)
get_thumbnail ($key=0)
Get a single thumbnail.
get_thumbnails ()
Get all thumbnails.
get_title ()
Get the title.
get_type ()
Get mimetype of the enclosure.
get_width ()
Get the width.
native_embed ($options='')
Embed the enclosure using <embed>
Data Fields
$bitrate
$captions
$categories
$channels
$copyright
$credits
$description
$duration
$expression
$framerate
$handler
$hashes
$height
$javascript
$keywords
$lang
$length
$link
$medium
$player
$ratings
$restrictions
$samplingrate
$thumbnails
$title
$type
$width
Detailed Description
Definition at line 55 of file Enclosure.php.
Constructor & Destructor Documentation
__construct ($link = null, $type = null, $length = null, $javascript = null, $bitrate = null, $captions = null, $categories = null, $channels = null, $copyright = null, $credits = null, $description = null, $duration = null, $expression = null, $framerate = null, $hashes = null, $height = null, $keywords = null, $lang = null, $medium = null, $player = null, $ratings = null, $restrictions = null, $samplingrate = null, $thumbnails = null, $title = null, $width = null)
Constructor, used to input the data.
For documentation on all the parameters, see the corresponding properties and their accessors
idna_convert If available, this will convert an IDN
Definition at line 227 of file Enclosure.php.
References $bitrate, $captions, $categories, $channels, $copyright, $credits, $description, $duration, $expression, $framerate, $hashes, $height, $keywords, $lang, $length, $link, $medium, $player, $ratings, $restrictions, $samplingrate, $thumbnails, $title, $type, $width, categories, SimplePie_Misc\compress_parse_url(), get_handler(), height, SimplePie_Misc\parse_url(), and width.
Member Function Documentation
__toString ()
String-ified version.
Returns
string
Definition at line 269 of file Enclosure.php.
embed ($options = '', $native = false)
Embed the enclosure using Javascript.
$options is an array or comma-separated key:value string, with the following properties:
alt (string): Alternate content for when an end-user does not have the appropriate handler installed or when a file type is unsupported. Can be any text or HTML. Defaults to blank.
altclass (string): If a file type is unsupported, the end-user will see the alt text (above) linked directly to the content. That link will have this value as its class name. Defaults to blank.
audio (string): This is an image that should be used as a placeholder for audio files before they're loaded (QuickTime-only). Can be any relative or absolute URL. Defaults to blank.
bgcolor (string): The background color for the media, if not already transparent. Defaults to #ffffff.
height (integer): The height of the embedded media. Accepts any numeric pixel value (such as 360) or auto. Defaults to auto, and it is recommended that you use this default.
loop (boolean): Do you want the media to loop when its done? Defaults to false.
mediaplayer (string): The location of the included mediaplayer.swf file. This allows for the playback of Flash Video (.flv) files, and is the default handler for non-Odeo MP3's. Defaults to blank.
video (string): This is an image that should be used as a placeholder for video files before they're loaded (QuickTime-only). Can be any relative or absolute URL. Defaults to blank.
width (integer): The width of the embedded media. Accepts any numeric pixel value (such as 480) or auto. Defaults to auto, and it is recommended that you use this default.
widescreen (boolean): Is the enclosure widescreen or standard? This applies only to video enclosures, and will automatically resize the content appropriately. Defaults to false, implying 4:3 mode.
Note: Non-widescreen (4:3) mode with width and height set to auto will default to 480x360 video resolution. Widescreen (16:9) mode with width and height set to auto will default to 480x270 video resolution.
Definition at line 970 of file Enclosure.php.
References $alt, $mime, $option, $options, elseif, get_extension(), get_handler(), get_link(), and get_real_type().
Referenced by native_embed().
get_bitrate ()
Get the bitrate.
Returns
string|null
Definition at line 280 of file Enclosure.php.
References $bitrate, and null.
get_caption ($key = 0)
Get a single caption.
Parameters
int $key
Returns
SimplePie_Caption|null
Definition at line 298 of file Enclosure.php.
References get_captions(), and null.
get_captions ()
Get all captions.
Returns
array|null Array of {
See also
SimplePie_Caption} objects
Definition at line 316 of file Enclosure.php.
References $captions, and null.
Referenced by get_caption().
get_categories ()
Get all categories.
Returns
array|null Array of {
See also
SimplePie_Category} objects
Definition at line 352 of file Enclosure.php.
References $categories, categories, and null.
Referenced by get_category().
get_category ($key = 0)
Get a single category.
Parameters
int $key
Returns
SimplePie_Category|null
Definition at line 334 of file Enclosure.php.
References get_categories(), and null.
get_channels ()
Get the number of audio channels.
Returns
int|null
Definition at line 369 of file Enclosure.php.
References $channels, and null.
get_copyright ()
Get the copyright information.
Returns
SimplePie_Copyright|null
Definition at line 386 of file Enclosure.php.
References $copyright, and null.
get_credit ($key = 0)
Get a single credit.
Parameters
int $key
Returns
SimplePie_Credit|null
Definition at line 404 of file Enclosure.php.
References get_credits(), and null.
get_credits ()
Get all credits.
Returns
array|null Array of {
See also
SimplePie_Credit} objects
Definition at line 422 of file Enclosure.php.
References $credits, and null.
Referenced by get_credit().
get_description ()
Get the description of the enclosure.
Returns
string|null
Definition at line 439 of file Enclosure.php.
References $description, and null.
get_duration ($convert = false)
Get the duration of the enclosure.
Parameters
string $convert Convert seconds into hh:mm:ss
Returns
string|int|null 'hh:mm:ss' string if $convert was specified, otherwise integer (or null if none found)
Definition at line 457 of file Enclosure.php.
References $duration, null, and SimplePie_Misc\time_hms().
get_expression ()
Get the expression.
Returns
string Probably one of 'sample', 'full', 'nonstop', 'clip'. Defaults to 'full'
Definition at line 482 of file Enclosure.php.
References $expression, and null.
get_extension ()
Get the file extension.
Returns
string|null
Definition at line 499 of file Enclosure.php.
References $url, null, and SimplePie_Misc\parse_url().
Referenced by embed(), and get_real_type().
get_framerate ()
Get the framerate (in frames-per-second)
Returns
string|null
Definition at line 517 of file Enclosure.php.
References $framerate, and null.
get_handler ()
Get the preferred handler.
Returns
string|null One of 'flash', 'fmedia', 'quicktime', 'wmedia', 'mp3'
Definition at line 534 of file Enclosure.php.
References get_real_type().
Referenced by __construct(), and embed().
get_hash ($key = 0)
Get a single hash.
int $key string|null Hash as per media:hash, prefixed with "$algo:"
Definition at line 546 of file Enclosure.php.
References get_hashes(), and null.
get_hashes ()
Get all credits.
Returns
array|null Array of strings, see {
See also
get_hash()}
Definition at line 564 of file Enclosure.php.
References $hashes, and null.
Referenced by get_hash().
get_height ()
Get the height.
Returns
string|null
Definition at line 581 of file Enclosure.php.
References $height, height, and null.
get_keyword ($key = 0)
Get a single keyword.
Parameters
int $key
Returns
string|null
Definition at line 617 of file Enclosure.php.
References get_keywords(), and null.
get_keywords ()
Get all keywords.
Returns
array|null Array of strings
Definition at line 635 of file Enclosure.php.
References $keywords, and null.
Referenced by get_keyword().
get_language ()
Get the language.
string|null Language code as per RFC 3066
Definition at line 599 of file Enclosure.php.
References $lang, and null.
get_length ()
Get length.
Returns
float Length in bytes
Definition at line 652 of file Enclosure.php.
References $length, and null.
Referenced by get_size().
get_link ()
Get the URL.
Returns
string|null
Definition at line 669 of file Enclosure.php.
References null.
Referenced by embed().
get_medium ()
Get the medium.
string|null Should be one of 'image', 'audio', 'video', 'document', 'executable'
Definition at line 687 of file Enclosure.php.
References $medium, and null.
get_player ()
Get the player URL.
Typically the same as {
See also
get_permalink()}
Returns
string|null Player URL
Definition at line 705 of file Enclosure.php.
References $player, and null.
get_rating ($key = 0)
Get a single rating.
Parameters
int $key
Returns
SimplePie_Rating|null
Definition at line 723 of file Enclosure.php.
References get_ratings(), and null.
get_ratings ()
Get all ratings.
Returns
array|null Array of {
See also
SimplePie_Rating} objects
Definition at line 741 of file Enclosure.php.
References $ratings, and null.
Referenced by get_rating().
get_real_type ($find_handler = false)
Get the real media type.
Often, feeds lie to us, necessitating a bit of deeper inspection. This converts types to their canonical representations based on the file extension
See also
get_type()
Parameters
bool $find_handler Internal use only, use {
See also
get_handler()} instead
Returns
string MIME type
Definition at line 1205 of file Enclosure.php.
References $type, elseif, get_extension(), get_type(), and null.
Referenced by embed(), and get_handler().
get_restriction ($key = 0)
Get a single restriction.
Parameters
int $key
Returns
SimplePie_Restriction|null
Definition at line 759 of file Enclosure.php.
References get_restrictions(), and null.
get_restrictions ()
Get all restrictions.
Returns
array|null Array of {
See also
SimplePie_Restriction} objects
Definition at line 777 of file Enclosure.php.
References $restrictions, and null.
Referenced by get_restriction().
get_sampling_rate ()
Get the sampling rate (in kHz)
Returns
string|null
Definition at line 794 of file Enclosure.php.
References $samplingrate, and null.
get_size ()
Get the file size (in MiB)
Returns
float|null File size in mebibytes (1048 bytes)
Definition at line 811 of file Enclosure.php.
References get_length(), and null.
get_thumbnail ($key = 0)
Get a single thumbnail.
Parameters
int $key
Returns
string|null Thumbnail URL
Definition at line 830 of file Enclosure.php.
References get_thumbnails(), and null.
get_thumbnails ()
Get all thumbnails.
Returns
array|null Array of thumbnail URLs
Definition at line 848 of file Enclosure.php.
References $thumbnails, and null.
Referenced by get_thumbnail().
get_title ()
Get the title.
Returns
string|null
Definition at line 865 of file Enclosure.php.
References $title, and null.
get_type ()
Get mimetype of the enclosure.
See also
get_real_type()
Returns
string|null MIME type
Definition at line 883 of file Enclosure.php.
References $type, and null.
Referenced by get_real_type().
get_width ()
Get the width.
Returns
string|null
Definition at line 900 of file Enclosure.php.
References $width, null, and width.
native_embed ($options = '')
Embed the enclosure using <embed>
Parameters
array | string $options See first paramter to {
See also
embed}
Returns
string HTML string to output
Definition at line 920 of file Enclosure.php.
References $options, and embed().
Field Documentation
$bitrate
Definition at line 61 of file Enclosure.php.
Referenced by __construct(), and get_bitrate().
$captions
Definition at line 67 of file Enclosure.php.
Referenced by __construct(), and get_captions().
$categories
Definition at line 73 of file Enclosure.php.
Referenced by __construct(), and get_categories().
$channels
Definition at line 79 of file Enclosure.php.
Referenced by __construct(), and get_channels().
$copyright
Definition at line 85 of file Enclosure.php.
Referenced by __construct(), and get_copyright().
$credits
Definition at line 91 of file Enclosure.php.
Referenced by __construct(), and get_credits().
$description
Definition at line 97 of file Enclosure.php.
Referenced by __construct(), and get_description().
$duration
Definition at line 103 of file Enclosure.php.
Referenced by __construct(), and get_duration().
$expression
Definition at line 109 of file Enclosure.php.
Referenced by __construct(), and get_expression().
$framerate
Definition at line 115 of file Enclosure.php.
Referenced by __construct(), and get_framerate().
$handler
Definition at line 121 of file Enclosure.php.
$hashes
Definition at line 127 of file Enclosure.php.
Referenced by __construct(), and get_hashes().
$height
Definition at line 133 of file Enclosure.php.
Referenced by __construct(), and get_height().
$javascript
Definition at line 139 of file Enclosure.php.
$keywords
Definition at line 145 of file Enclosure.php.
Referenced by __construct(), and get_keywords().
$lang
Definition at line 151 of file Enclosure.php.
Referenced by __construct(), and get_language().
$length
Definition at line 157 of file Enclosure.php.
Referenced by __construct(), and get_length().
$link
Definition at line 163 of file Enclosure.php.
Referenced by __construct().
$medium
Definition at line 169 of file Enclosure.php.
Referenced by __construct(), and get_medium().
$player
Definition at line 175 of file Enclosure.php.
Referenced by __construct(), and get_player().
$ratings
Definition at line 181 of file Enclosure.php.
Referenced by __construct(), and get_ratings().
$restrictions
Definition at line 187 of file Enclosure.php.
Referenced by __construct(), and get_restrictions().
$samplingrate
Definition at line 193 of file Enclosure.php.
Referenced by __construct(), and get_sampling_rate().
$thumbnails
Definition at line 199 of file Enclosure.php.
Referenced by __construct(), and get_thumbnails().
$title
Definition at line 205 of file Enclosure.php.
Referenced by __construct(), and get_title().
$type
Definition at line 211 of file Enclosure.php.
Referenced by __construct(), get_real_type(), and get_type().
$width
Definition at line 217 of file Enclosure.php.
Referenced by __construct(), and get_width().
The documentation for this class was generated from the following file:
Enclosure.php