GravityView: WP_UnitTestCase Class Reference
WP_UnitTestCase Class Reference
Public Member Functions
__get ($name)
__isset ($name)
_create_temporary_tables ($query)
_drop_temporary_tables ($query)
_make_attachment ($upload, $parent_post_id=0)
assertDiscardWhitespace ($expected, $actual)
assertEqualFields ($object, $fields)
assertEqualSets ($expected, $actual)
assertEqualSetsWithIndex ($expected, $actual)
assertNotWPError ($actual, $message= '')
assertQueryTrue ()
Check each of the WP_Query is_* functions/properties against expected boolean value.
assertWPError ($actual, $message= '')
clean_up_global_scope ()
delete_folders ($path)
deprecated_function_run ($function)
doing_it_wrong_run ($function)
expectDeprecated ()
expectedDeprecated ()
files_in_dir ($dir)
flush_cache ()
get_wp_die_handler ($handler)
go_to ($url)
knownPluginBug ($ticket_id)
Skips the current test if there is an open plugin ticket with id $ticket_id.
knownUTBug ($ticket_id)
Skips the current test if there is an open unit tests ticket with id $ticket_id.
knownWPBug ($ticket_id)
Skips the current test if there is an open WordPress ticket with id $ticket_id.
prepareTemplate (Text_Template $template)
Define constants after including files.
remove_added_uploads ()
rmdir ($path)
scan_user_uploads ()
scandir ($dir)
set_permalink_structure ($structure= '')
Utility method that resets permalinks and flushes rewrites.
setExpectedDeprecated ($deprecated)
Declare an expected _deprecated_function() or _deprecated_argument() call from within a test.
setExpectedIncorrectUsage ($doing_it_wrong)
Declare an expected _doing_it_wrong() call from within a test.
setUp ()
start_transaction ()
tearDown ()
temp_filename ()
Returns the name of a temporary file.
unlink ($file)
wp_die_handler ($message)
Static Public Member Functions
static commit_transaction ()
Commit the queries in a transaction.
static delete_user ($user_id)
Multisite-agnostic way to delete a user from the database.
static forceTicket ($ticket)
static get_called_class ()
static setUpBeforeClass ()
static tearDownAfterClass ()
Protected Member Functions
_backup_hooks ()
Saves the action and filter-related globals so they can be restored later.
_microtime_to_float ($microtime)
Helper to Convert a microtime string into a float.
_restore_hooks ()
Restores the hook-related globals to their state at setUp() so that future tests aren't affected by hooks set during this last test.
assertPostConditions ()
Detect post-test failure conditions.
checkRequirements ()
reset_post_statuses ()
Unregister non-built-in post statuses.
reset_post_types ()
Unregister existing post types and register defaults.
reset_taxonomies ()
Unregister existing taxonomies and register defaults.
Static Protected Member Functions
static factory ()
Protected Attributes
$caught_deprecated = array()
$caught_doing_it_wrong = array()
$expected_deprecated = array()
$expected_doing_it_wrong = array()
Static Protected Attributes
static $forced_tickets = array()
static $hooks_saved = array()
static $ignore_files
Detailed Description
Definition at line 6 of file testcase.php.
Member Function Documentation
__get ($name)
Definition at line 21 of file testcase.php.
References $name.
__isset ($name)
Definition at line 17 of file testcase.php.
References $name.
_backup_hooks () protected
Saves the action and filter-related globals so they can be restored later.
Stores $merged_filters, $wp_actions, $wp_current_filter, and $wp_filter on a class variable so they can be restored on tearDown() using _restore_hooks().
array $merged_filters array $wp_actions array $wp_current_filter array $wp_filter
Returns
void
Definition at line 200 of file testcase.php.
References $GLOBALS.
Referenced by setUp().
_create_temporary_tables ($query)
Definition at line 258 of file testcase.php.
_drop_temporary_tables ($query)
Definition at line 264 of file testcase.php.
_make_attachment ($upload, $parent_post_id = 0)
Definition at line 698 of file testcase.php.
References $id, $mime, wp_check_filetype(), wp_generate_attachment_metadata(), wp_insert_attachment(), and wp_update_attachment_metadata().
_microtime_to_float ($microtime) protected
Helper to Convert a microtime string into a float.
Definition at line 663 of file testcase.php.
_restore_hooks () protected
Restores the hook-related globals to their state at setUp() so that future tests aren't affected by hooks set during this last test.
array $merged_filters array $wp_actions array $wp_current_filter array $wp_filter
Returns
void
Definition at line 217 of file testcase.php.
References $GLOBALS.
Referenced by tearDown().
assertDiscardWhitespace ($expected, $actual)
Definition at line 375 of file testcase.php.
assertEqualFields ($object, $fields)
Definition at line 367 of file testcase.php.
assertEqualSets ($expected, $actual)
Definition at line 379 of file testcase.php.
assertEqualSetsWithIndex ($expected, $actual)
Definition at line 385 of file testcase.php.
assertNotWPError ($actual, $message = '')
Definition at line 360 of file testcase.php.
References $message, and is_wp_error().
assertPostConditions () protected
Detect post-test failure conditions.
We use this method to detect expectedDeprecated and expectedIncorrectUsage annotations.
Since
4.2.0
Definition at line 122 of file testcase.php.
References expectedDeprecated().
assertQueryTrue ()
Check each of the WP_Query is_* functions/properties against expected boolean value.
Any properties that are listed by name as parameters will be expected to be true; any others are expected to be false. For example, assertQueryTrue('is_single', 'is_feed') means is_single() and is_feed() must be true and everything else must be false to pass.
Parameters
string $prop,... Any number of WP_Query properties that are expected to be true for the current request.
Definition at line 530 of file testcase.php.
References $message.
assertWPError ($actual, $message = '')
Definition at line 356 of file testcase.php.
References $message.
Referenced by Tests_REST_Request\test_has_multiple_invalid_params_validate_callback(), Tests_REST_Request\test_has_valid_params_required_flag(), Tests_REST_Request\test_has_valid_params_required_flag_multiple(), and Tests_REST_Request\test_has_valid_params_validate_callback().
checkRequirements () protected
Definition at line 434 of file testcase.php.
References elseif, knownPluginBug(), knownUTBug(), and knownWPBug().
clean_up_global_scope ()
Definition at line 145 of file testcase.php.
References flush_cache().
Referenced by setUp().
static commit_transaction () static
Commit the queries in a transaction.
Since
4.1.0
Definition at line 253 of file testcase.php.
References $wpdb.
delete_folders ($path)
Definition at line 638 of file testcase.php.
References $dir, $path, rmdir(), and scandir().
static delete_user ($user_id) static
Multisite-agnostic way to delete a user from the database.
Since
4.3.0
Definition at line 673 of file testcase.php.
References $user_id, is_multisite(), wp_delete_user(), and wpmu_delete_user().
deprecated_function_run ($function)
Definition at line 346 of file testcase.php.
doing_it_wrong_run ($function)
Definition at line 351 of file testcase.php.
expectDeprecated ()
Definition at line 278 of file testcase.php.
References add_action().
Referenced by setUp().
expectedDeprecated ()
Definition at line 294 of file testcase.php.
References $errors.
Referenced by assertPostConditions().
static factory () static protected
Definition at line 27 of file testcase.php.
References null.
Referenced by GravityView_Edit_Entry_Test\_add_and_remove_caps_test(), GravityView_Entry_Link_Shortcode_Test\_test_delete(), GravityView_Entry_Link_Shortcode_Test\_test_edit(), GV_UnitTestCase\setUp(), GravityView_Roles_Capabilities_Test\test_authorless_view(), GravityView_View_Test\test_BackLinkLabel(), GravityView_Uninstall_Test\test_fire_everything(), GVCommon_Test\test_format_date(), GVCommon_Test\test_get_connected_views(), GravityView_Edit_Entry_Test\test_get_edit_link(), GVCommon_Test\test_get_forms(), GVCommon_Test\test_get_meta_form_id(), GVCommon_Test\test_get_meta_template_id(), GravityView_Merge_Tags_Test\test_gf_merge_tags(), GravityView_API_Test\test_gravityview_field_output(), GravityView_Roles_Capabilities_Test\test_has_cap_cap_parameter(), GravityView_Roles_Capabilities_Test\test_has_cap_gravityview_full_access(), GravityView_Roles_Capabilities_Test\test_has_cap_single_post_cap(), GravityView_Roles_Capabilities_Test\test_has_cap_user_id_parameter(), GravityView_Connector_Functions_Test\test_has_gravityview_shortcode(), GVCommon_Test\test_has_gravityview_shortcode(), GravityView_Merge_Tags_Test\test_replace_date_created(), GravityView_Merge_Tags_Test\test_replace_field_custom_merge_tags(), GravityView_Merge_Tags_Test\test_replace_user_variables_created_by(), GravityView_Shortcode_Test\test_shortcode(), and GravityView_Entry_Link_Shortcode_Test\test_shortcode().
files_in_dir ($dir)
Definition at line 613 of file testcase.php.
References $dir, and $name.
Referenced by rmdir(), and scan_user_uploads().
flush_cache ()
Definition at line 226 of file testcase.php.
References wp_cache_add_global_groups(), wp_cache_add_non_persistent_groups(), and wp_cache_flush().
Referenced by clean_up_global_scope(), and go_to().
static forceTicket ($ticket) static
Definition at line 490 of file testcase.php.
Referenced by WP_PHPUnit_Util_Getopt\__construct().
static get_called_class () static
Definition at line 35 of file testcase.php.
get_wp_die_handler ($handler)
Definition at line 270 of file testcase.php.
go_to ($url)
Definition at line 391 of file testcase.php.
References $_SERVER, $GLOBALS, $url, _cleanup_query_vars(), and flush_cache().
Referenced by WP_Canonical_UnitTestCase\assertCanonical().
knownPluginBug ($ticket_id)
Skips the current test if there is an open plugin ticket with id $ticket_id.
Definition at line 483 of file testcase.php.
References TracTickets\isTracTicketClosed().
Referenced by checkRequirements().
knownUTBug ($ticket_id)
Skips the current test if there is an open unit tests ticket with id $ticket_id.
Definition at line 473 of file testcase.php.
References TracTickets\isTracTicketClosed().
Referenced by checkRequirements().
knownWPBug ($ticket_id)
Skips the current test if there is an open WordPress ticket with id $ticket_id.
Definition at line 463 of file testcase.php.
References TracTickets\isTracTicketClosed().
Referenced by WP_Canonical_UnitTestCase\assertCanonical(), and checkRequirements().
prepareTemplate (Text_Template $template)
Define constants after including files.
Definition at line 497 of file testcase.php.
remove_added_uploads ()
Definition at line 607 of file testcase.php.
References rmdir(), and wp_upload_dir().
Referenced by WP_XMLRPC_UnitTestCase\tearDown().
reset_post_statuses () protected
Unregister non-built-in post statuses.
Definition at line 182 of file testcase.php.
References _unregister_post_status(), and get_post_stati().
Referenced by setUp().
reset_post_types () protected
Unregister existing post types and register defaults.
Run before each test in order to clean up the global scope, in case a test forgets to unregister a post type on its own, or fails before it has a chance to do so.
Definition at line 158 of file testcase.php.
References _unregister_post_type(), create_initial_post_types(), and get_post_types().
Referenced by setUp().
reset_taxonomies () protected
Unregister existing taxonomies and register defaults.
Run before each test in order to clean up the global scope, in case a test forgets to unregister a taxonomy on its own, or fails before it has a chance to do so.
Definition at line 172 of file testcase.php.
References $tax, _unregister_taxonomy(), create_initial_taxonomies(), and get_taxonomies().
Referenced by setUp().
rmdir ($path)
Definition at line 598 of file testcase.php.
References $file, $path, files_in_dir(), and unlink().
Referenced by delete_folders(), and remove_added_uploads().
scan_user_uploads ()
Definition at line 627 of file testcase.php.
References files_in_dir(), and wp_upload_dir().
Referenced by setUp().
scandir ($dir)
Definition at line 651 of file testcase.php.
References $dir, and $path.
Referenced by delete_folders().
set_permalink_structure ($structure = '')
Utility method that resets permalinks and flushes rewrites.
Since
4.4.0
WP_Rewrite $wp_rewrite
Parameters
string $structure Optional. Permalink structure to set. Default empty.
Definition at line 690 of file testcase.php.
References $wp_rewrite.
Referenced by setUp().
setExpectedDeprecated ($deprecated)
Declare an expected _deprecated_function() or _deprecated_argument() call from within a test.
Since
4.2.0
Parameters
string $deprecated Name of the function, method, class, or argument that is deprecated. Must match first parameter of the _deprecated_function() or _deprecated_argument() call.
Definition at line 330 of file testcase.php.
References $deprecated.
setExpectedIncorrectUsage ($doing_it_wrong)
Declare an expected _doing_it_wrong() call from within a test.
Since
4.2.0
Parameters
string $deprecated Name of the function, method, or class that appears in the first argument of the source _doing_it_wrong() call.
Definition at line 342 of file testcase.php.
setUp ()
Definition at line 76 of file testcase.php.
References $wp_rewrite, $wpdb, _backup_hooks(), add_filter(), clean_up_global_scope(), expectDeprecated(), reset_post_statuses(), reset_post_types(), reset_taxonomies(), scan_user_uploads(), set_permalink_structure(), and start_transaction().
static setUpBeforeClass () static
Definition at line 50 of file testcase.php.
start_transaction ()
Definition at line 240 of file testcase.php.
References $wpdb, and add_filter().
Referenced by setUp().
tearDown ()
Definition at line 126 of file testcase.php.
References $post, $wp, $wpdb, _restore_hooks(), is_multisite(), ms_is_switched(), null, remove_filter(), remove_theme_support(), and restore_current_blog().
static tearDownAfterClass () static
Definition at line 63 of file testcase.php.
temp_filename ()
Returns the name of a temporary file.
Definition at line 506 of file testcase.php.
References $dir.
unlink ($file)
Definition at line 588 of file testcase.php.
References $file, and elseif.
Referenced by rmdir().
wp_die_handler ($message)
Definition at line 274 of file testcase.php.
References $message.
Field Documentation
$caught_deprecated = array() protected
Definition at line 10 of file testcase.php.
$caught_doing_it_wrong = array() protected
Definition at line 12 of file testcase.php.
$expected_deprecated = array() protected
Definition at line 9 of file testcase.php.
$expected_doing_it_wrong = array() protected
Definition at line 11 of file testcase.php.
Referenced by WP_Canonical_UnitTestCase\assertCanonical().
$forced_tickets = array() static protected
Definition at line 8 of file testcase.php.
$hooks_saved = array() static protected
Definition at line 14 of file testcase.php.
$ignore_files static protected
Definition at line 15 of file testcase.php.
The documentation for this class was generated from the following file:
testcase.php