GravityView: WP_Screen Class Reference
WP_Screen Class Reference
Core class used to implement an admin screen API.
Public Member Functions
add_help_tab ($args)
Add a help tab to the contextual help for the screen.
add_option ($option, $args=array())
Adds an option for the screen.
get_columns ()
Gets the number of layout columns the user has selected.
get_help_sidebar ()
Gets the content from a contextual help sidebar.
get_help_tab ($id)
Gets the arguments for a help tab.
get_help_tabs ()
Gets the help tabs registered for the screen.
get_option ($option, $key=false)
Gets the arguments for an option for the screen.
get_options ()
Get the options registered for the screen.
get_screen_reader_content ()
Get the accessible hidden headings and text used in the screen.
get_screen_reader_text ($key)
Get a screen reader text string.
in_admin ($admin=null)
Indicates whether the screen is in a particular admin.
remove_help_tab ($id)
Removes a help tab from the contextual help for the screen.
remove_help_tabs ()
Removes all help tabs from the contextual help for the screen.
remove_option ($option)
Remove an option from the screen.
remove_options ()
Remove all options from the screen.
remove_screen_reader_content ()
Remove all the accessible hidden headings and text for the screen.
render_list_table_columns_preferences ()
Render the list table columns preferences.
render_meta_boxes_preferences ()
Render the meta boxes preferences.
render_per_page_options ()
Render the items per page option.
render_screen_layout ()
Render the option for number of columns on the page.
render_screen_meta ()
Render the screen's help section.
render_screen_options ($options=array())
Render the screen options tab.
render_screen_reader_content ($key= '', $tag= 'h2')
Render screen reader text.
render_view_mode ()
Render the list table view mode preferences.
set_current_screen ()
Makes the screen object the current screen.
set_help_sidebar ($content)
Add a sidebar to the contextual help for the screen.
set_parentage ($parent_file)
Set the parent information for the screen.
set_screen_reader_content ($content=array())
Add accessible hidden headings and text for the screen.
show_screen_options ()
array $wp_meta_boxes
Static Public Member Functions
static add_old_compat_help ($screen, $help)
Sets the old string-based contextual help for the screen.
static get ($hook_name= '')
Fetches a screen object.
Data Fields
$action
$base
$id
$is_network
$is_user
$parent_base
$parent_file
$post_type
$taxonomy
Protected Attributes
$in_admin
Private Member Functions
__construct ()
Constructor.
Private Attributes
$_help_sidebar = ''
$_help_tabs = array()
$_options = array()
$_screen_reader_content = array()
$_screen_settings
$_show_screen_options
$columns = 0
Static Private Attributes
static $_old_compat_help = array()
static $_registry = array()
Detailed Description
Core class used to implement an admin screen API.
Since
3.3.0
Definition at line 15 of file class-wp-screen.php.
Constructor & Destructor Documentation
__construct () private
Constructor.
Since
3.3.0 private
Definition at line 400 of file class-wp-screen.php.
Member Function Documentation
add_help_tab ($args)
Add a help tab to the contextual help for the screen.
Call this on the load-$pagenow hook for the relevant screen.
Since
3.3.0
4.4.0 The $priority argument was added.
Parameters
array $args { Array of arguments used to display the help tab.
string $title Title for the tab. Default false. string $id Tab ID. Must be HTML-safe. Default false. string $content Optional. Help tab content in plain text or HTML. Default empty string. string $callback Optional. A callback to generate the tab content. Default false. int $priority Optional. The priority of the tab, used for ordering. Default 10. }
Definition at line 576 of file class-wp-screen.php.
References sanitize_html_class(), and wp_parse_args().
Referenced by render_screen_meta().
static add_old_compat_help ($screen, $help) static
Sets the old string-based contextual help for the screen.
For backwards compatibility.
Since
3.3.0
Parameters
WP_Screen $screen A screen object.
string $help Help text.
Definition at line 430 of file class-wp-screen.php.
References $help, and $screen.
Referenced by add_contextual_help().
add_option ($option, $args = array())
Adds an option for the screen.
Call this in template files after admin.php is loaded and before admin-header.php is loaded to add screen options.
Since
3.3.0
Parameters
string $option Option ID
mixed $args Option-dependent arguments.
Definition at line 457 of file class-wp-screen.php.
References $option.
Referenced by render_screen_meta().
static get ($hook_name = '') static
Fetches a screen object.
Since
3.3.0 public
string $hook_suffix
Parameters
string | WP_Screen $hook_name Optional. The hook name (also known as the hook suffix) used to determine the screen. Defaults to the current $hook_suffix global.
Returns
WP_Screen Screen object.
Definition at line 217 of file class-wp-screen.php.
References $action, $base, $GLOBALS, $id, $in_admin, $post, $post_id, $post_type, $screen, $taxonomy, elseif, get_current_screen(), get_post(), is_object_in_taxonomy(), null, post_type_exists(), sanitize_key(), taxonomy_exists(), WP_NETWORK_ADMIN, and WP_USER_ADMIN.
Referenced by convert_to_screen(), WP_Customize_Nav_Menus_Panel\render_screen_options(), and set_current_screen().
get_columns ()
Gets the number of layout columns the user has selected.
The layout_columns option controls the max number and default number of columns. This method returns the number of columns within that range selected by the user via Screen Options. If no selection has been made, the default provisioned in layout_columns is returned. If the screen does not support selecting the number of layout columns, 0 is returned.
Since
3.4.0
Returns
int Number of columns to display.
Definition at line 652 of file class-wp-screen.php.
References $columns.
Referenced by render_screen_layout().
get_help_sidebar ()
Gets the content from a contextual help sidebar.
Since
3.4.0
Returns
string Contents of the help sidebar.
Definition at line 623 of file class-wp-screen.php.
References $_help_sidebar.
Referenced by render_screen_meta().
get_help_tab ($id)
Gets the arguments for a help tab.
Since
3.4.0
Parameters
string $id Help Tab ID.
Returns
array Help tab arguments.
Definition at line 553 of file class-wp-screen.php.
References $id, and null.
get_help_tabs ()
Gets the help tabs registered for the screen.
Since
3.4.0
4.4.0 Help tabs are ordered by their priority.
Returns
array Help tabs with arguments.
Definition at line 521 of file class-wp-screen.php.
References $_help_tabs, and $list.
Referenced by render_screen_meta().
get_option ($option, $key = false)
Gets the arguments for an option for the screen.
Since
3.3.0
Parameters
string $option Option name.
string $key Optional. Specific array key for when the option is an array. Default false.
Returns
string The option value if set, null otherwise.
Definition at line 502 of file class-wp-screen.php.
References $option, and null.
Referenced by render_meta_boxes_preferences(), render_per_page_options(), render_screen_layout(), render_screen_meta(), and show_screen_options().
get_options ()
Get the options registered for the screen.
Since
3.8.0
Returns
array Options with arguments.
Definition at line 488 of file class-wp-screen.php.
References $_options.
get_screen_reader_content ()
Get the accessible hidden headings and text used in the screen.
Since
4.4.0
See also
set_screen_reader_content() For more information on the array format.
Returns
array An associative array of screen reader text strings.
Definition at line 665 of file class-wp-screen.php.
References $_screen_reader_content.
get_screen_reader_text ($key)
Get a screen reader text string.
Since
4.4.0
Parameters
string $key Screen reader text array named key.
Returns
string Screen reader text string.
Definition at line 677 of file class-wp-screen.php.
References null.
in_admin ($admin = null)
Indicates whether the screen is in a particular admin.
Since
3.5.0
Parameters
string $admin The admin to check against (network | user | site). If empty any of the three admins will result in true.
Returns
bool True if the screen is in the indicated admin, false otherwise.
Definition at line 411 of file class-wp-screen.php.
References $in_admin.
remove_help_tab ($id)
Removes a help tab from the contextual help for the screen.
Since
3.3.0
Parameters
string $id The help tab ID.
Definition at line 603 of file class-wp-screen.php.
References $id.
remove_help_tabs ()
Removes all help tabs from the contextual help for the screen.
Since
3.3.0
Definition at line 612 of file class-wp-screen.php.
remove_option ($option)
Remove an option from the screen.
Since
3.8.0
Parameters
string $option Option ID.
Definition at line 468 of file class-wp-screen.php.
References $option.
remove_options ()
Remove all options from the screen.
Since
3.8.0
Definition at line 477 of file class-wp-screen.php.
remove_screen_reader_content ()
Remove all the accessible hidden headings and text for the screen.
Since
4.4.0
Definition at line 716 of file class-wp-screen.php.
render_list_table_columns_preferences ()
Render the list table columns preferences.
Since
4.4.0
Definition at line 1058 of file class-wp-screen.php.
References $columns, $id, $title, __, checked(), get_column_headers(), and get_hidden_columns().
Referenced by render_screen_options().
render_meta_boxes_preferences ()
Render the meta boxes preferences.
Since
4.4.0
array $wp_meta_boxes
Definition at line 1022 of file class-wp-screen.php.
References _e, _x, checked(), current_user_can(), get_current_user_id(), get_option(), get_user_meta(), has_action(), meta_box_prefs(), and update_user_meta().
Referenced by render_screen_options().
render_per_page_options ()
Render the items per page option.
Since
3.3.0
This filter is documented in wp-admin/includes/class-wp-comments-list-table.php
This filter is documented in wp-admin/includes/class-wp-terms-list-table.php
This filter is documented in wp-admin/includes/class-wp-list-table.php
This filter is documented in wp-admin/includes/post.php
Definition at line 1132 of file class-wp-screen.php.
References $option, __, _e, add_filter(), apply_filters(), elseif, endif, get_option(), get_user_option(), input, label, name, null, post_type, and str_replace.
Referenced by render_screen_options().
render_screen_layout ()
Render the option for number of columns on the page.
Since
3.3.0
Definition at line 1103 of file class-wp-screen.php.
References $i, _e, _n(), checked(), get_columns(), get_option(), input, label, name, and number_format_i18n().
Referenced by render_screen_options().
render_screen_meta ()
Render the screen's help section.
This will trigger the deprecated filters for backwards compatibility.
Since
3.3.0
string $screen_layout_columns
Filter the legacy contextual help list.
Since
2.7.0
Parameters
array $old_compat_help Old contextual help.
WP_Screen $this Current WP_Screen instance.
Filter the legacy contextual help text.
Since
2.7.0
Parameters
string $old_help Help text that appears on the screen.
string $screen_id Screen ID.
WP_Screen $this Current WP_Screen instance.
Filter the default legacy contextual help text.
Since
2.8.0
Parameters
string $old_help_default Default contextual help text.
Filter the array of screen layout columns.
This hook provides back-compat for plugins using the back-compat filter instead of add_screen_option().
Since
2.8.0
Parameters
array $empty_columns Empty array.
string $screen_id Screen ID.
WP_Screen $this Current WP_Screen instance.
Definition at line 729 of file class-wp-screen.php.
References $class, $columns, $GLOBALS, $id, __, _e, add_help_tab(), add_option(), apply_filters(), endforeach, endif, esc_html, get_help_sidebar(), get_help_tabs(), get_option(), get_user_option(), label, li, render_screen_options(), and show_screen_options().
render_screen_options ($options = array())
Render the screen options tab.
Since
3.3.0
Parameters
array $options { bool $wrap Whether the screen-options-wrap div will be included. Defaults to true. }
Filter whether to show the Screen Options submit button.
Since
4.4.0
Parameters
bool $show_button Whether to show Screen Options submit button. Default false.
WP_Screen $this Current WP_Screen instance.
Definition at line 969 of file class-wp-screen.php.
References $_screen_settings, $options, __, apply_filters(), esc_attr__(), render_list_table_columns_preferences(), render_meta_boxes_preferences(), render_per_page_options(), render_screen_layout(), render_view_mode(), submit_button(), wp_nonce_field(), and wp_parse_args().
Referenced by render_screen_meta().
render_screen_reader_content ($key = '', $tag = 'h2')
Render screen reader text.
Since
4.4.0
Parameters
string $key The screen reader text array named key.
string $tag Optional. The HTML tag to wrap the screen reader text. Default h2.
Definition at line 1247 of file class-wp-screen.php.
render_view_mode ()
Render the list table view mode preferences.
Since
4.4.0
Filter the post types that have different view mode options.
Since
4.4.0
Parameters
array $view_mode_post_types Array of post types that can change view modes. Default hierarchical post types with show_ui on.
Definition at line 1196 of file class-wp-screen.php.
References $mode, $screen, _e, add_filter(), apply_filters(), checked(), get_current_screen(), get_post_types(), input, label, name, and post_type.
Referenced by render_screen_options().
set_current_screen ()
Makes the screen object the current screen.
See also
set_current_screen()
Since
3.3.0
WP_Screen $current_screen string $taxnow string $typenow
Fires after the current screen has been set.
Since
3.0.0
Parameters
WP_Screen $current_screen Current WP_Screen object.
Definition at line 378 of file class-wp-screen.php.
References $current_screen, $post_type, $taxnow, $taxonomy, $typenow, and do_action().
set_help_sidebar ($content)
Add a sidebar to the contextual help for the screen.
Call this in template files after admin.php is loaded and before admin-header.php is loaded to add a sidebar to the contextual help.
Since
3.3.0
Parameters
string $content Sidebar content in plain text or HTML.
Definition at line 635 of file class-wp-screen.php.
References $content.
set_parentage ($parent_file)
Set the parent information for the screen.
This is called in admin-header.php after the menu parent for the screen has been determined.
Since
3.3.0
Parameters
string $parent_file The parent file of the screen. Typically the $parent_file global.
Definition at line 442 of file class-wp-screen.php.
References $parent_file, and str_replace.
set_screen_reader_content ($content = array())
Add accessible hidden headings and text for the screen.
Since
4.4.0
Parameters
array $content { An associative array of screen reader text strings.
string $heading_views Screen reader text for the filter links heading. Default 'Filter items list'. string $heading_pagination Screen reader text for the pagination heading. Default 'Items list navigation'. string $heading_list Screen reader text for the items list heading. Default 'Items list'. }
Definition at line 700 of file class-wp-screen.php.
References $content, __, and wp_parse_args().
show_screen_options ()
array $wp_meta_boxes
Returns
bool
Filter the screen settings text displayed in the Screen Options tab.
This filter is currently only used on the Widgets screen to enable accessibility mode.
Since
3.0.0
Parameters
string $screen_settings Screen settings.
WP_Screen $this WP_Screen object.
Filter whether to show the Screen Options tab.
Since
3.2.0
Parameters
bool $show_screen Whether to show Screen Options tab. Default true.
WP_Screen $this Current WP_Screen instance.
Definition at line 906 of file class-wp-screen.php.
References $_show_screen_options, $columns, __, apply_filters(), checked(), get_column_headers(), get_option(), and get_user_setting().
Referenced by render_screen_meta().
Field Documentation
$_help_sidebar = '' private
Definition at line 143 of file class-wp-screen.php.
Referenced by get_help_sidebar().
$_help_tabs = array() private
Definition at line 134 of file class-wp-screen.php.
Referenced by get_help_tabs().
$_old_compat_help = array() static private
Definition at line 162 of file class-wp-screen.php.
$_options = array() private
Definition at line 171 of file class-wp-screen.php.
Referenced by get_options().
$_registry = array() static private
Definition at line 183 of file class-wp-screen.php.
$_screen_reader_content = array() private
Definition at line 152 of file class-wp-screen.php.
Referenced by get_screen_reader_content().
$_screen_settings private
Definition at line 201 of file class-wp-screen.php.
Referenced by render_screen_options().
$_show_screen_options private
Definition at line 192 of file class-wp-screen.php.
Referenced by show_screen_options().
$action
Definition at line 23 of file class-wp-screen.php.
Referenced by get().
$base
Definition at line 33 of file class-wp-screen.php.
Referenced by get().
$columns = 0 private
Definition at line 42 of file class-wp-screen.php.
Referenced by get_columns(), render_list_table_columns_preferences(), render_screen_meta(), and show_screen_options().
$id
Definition at line 51 of file class-wp-screen.php.
Referenced by get(), get_help_tab(), remove_help_tab(), render_list_table_columns_preferences(), and render_screen_meta().
$in_admin protected
Definition at line 60 of file class-wp-screen.php.
Referenced by get(), and in_admin().
$is_network
Definition at line 72 of file class-wp-screen.php.
$is_user
Definition at line 84 of file class-wp-screen.php.
$parent_base
Definition at line 95 of file class-wp-screen.php.
$parent_file
Definition at line 105 of file class-wp-screen.php.
Referenced by set_parentage().
$post_type
Definition at line 116 of file class-wp-screen.php.
Referenced by get(), and set_current_screen().
$taxonomy
Definition at line 125 of file class-wp-screen.php.
Referenced by get(), and set_current_screen().
The documentation for this class was generated from the following file:
class-wp-screen.php