GravityView: AddTextdomain Class Reference
AddTextdomain Class Reference
Public Member Functions
__construct ()
process_file ($domain, $source_filename, $inplace)
Add textdomain to a single file.
process_string ($domain, $string)
Add textdomain to a string of PHP.
process_tokens ($domain, $tokens)
Add textdomain to a set of PHP tokens.
usage ()
Data Fields
$funcs
$modified_contents = ''
Detailed Description
Definition at line 11 of file add-textdomain.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 16 of file add-textdomain.php.
Member Function Documentation
process_file ($domain, $source_filename, $inplace)
Add textdomain to a single file.
See also
AddTextdomain::process_string()
Parameters
string $domain Text domain.
string $source_filename Filename with optional path.
bool $inplace True to modifies the PHP file in place. False to print to standard output.
Definition at line 36 of file add-textdomain.php.
References process_string().
process_string ($domain, $string)
Add textdomain to a string of PHP.
Functions calls should be wrapped in opening and closing PHP delimiters as usual.
See also
AddTextdomain::process_tokens()
Parameters
string $domain Text domain.
string $string PHP code to parse.
Returns
string Modified source.
Definition at line 60 of file add-textdomain.php.
References process_tokens().
Referenced by process_file().
process_tokens ($domain, $tokens)
Add textdomain to a set of PHP tokens.
Parameters
string $domain Text domain.
array $tokens PHP tokens. An array of token identifiers. Each individual token identifier is either a single character (i.e.: ;, ., >, !, etc.), or a three element array containing the token index in element 0, the string content of the original token in element 1 and the line number in element 2.
Returns
string Modified source.
Definition at line 76 of file add-textdomain.php.
References $modified_contents.
Referenced by process_string().
usage ()
Definition at line 21 of file add-textdomain.php.
Field Documentation
$funcs
Definition at line 14 of file add-textdomain.php.
$modified_contents = ''
Definition at line 13 of file add-textdomain.php.
Referenced by GruntAddTextdomain\process_tokens(), and process_tokens().
The documentation for this class was generated from the following file:
add-textdomain.php