GravityView: WP Class Reference
WP Class Reference
Public Member Functions
add_query_var ($qv)
Add name to list of public query variables.
build_query_string ()
Sets the query string property based off of the query variable property.
handle_404 ()
Set the Headers for 404, if nothing is found for requested URL.
init ()
Set up the current user.
main ($query_args= '')
Sets up all of the variables required by the WordPress environment.
parse_request ($extra_query_vars= '')
Parse request to find correct WordPress query.
query_posts ()
Set up the Loop based on the query variables.
register_globals ()
Set up the WordPress Globals.
remove_query_var ($name)
Remove name from list of public query variables.
send_headers ()
Sends additional HTTP headers for caching, content type, etc.
set_query_var ($key, $value)
Set the value of a query variable.
Data Fields
$did_permalink = false
$extra_query_vars = array()
$matched_query
$matched_rule
$private_query_vars = array('offset', 'posts_per_page', 'posts_per_archive_page', 'showposts', 'nopaging', 'post_type', 'post_status', 'category__in', 'category__not_in', 'category__and', 'tag__in', 'tag__not_in', 'tag__and', 'tag_slug__in', 'tag_slug__and', 'tag_id', 'post_mime_type', 'perm', 'comments_per_page', 'post__in', 'post__not_in', 'post_parent', 'post_parent__in', 'post_parent__not_in', 'title')
$public_query_vars = array('m', 'p', 'posts', 'w', 'cat', 'withcomments', 'withoutcomments', 's', 'search', 'exact', 'sentence', 'calendar', 'page', 'paged', 'more', 'tb', 'pb', 'author', 'order', 'orderby', 'year', 'monthnum', 'day', 'hour', 'minute', 'second', 'name', 'category_name', 'tag', 'feed', 'author_name', 'static', 'pagename', 'page_id', 'error', 'attachment', 'attachment_id', 'subpost', 'subpost_id', 'preview', 'robots', 'taxonomy', 'term', 'cpage', 'post_type', 'embed')
$query_string
$query_vars
$request
Detailed Description
Definition at line 8 of file class-wp.php.
Member Function Documentation
add_query_var ($qv)
Add name to list of public query variables.
Since
2.1.0
Parameters
string $qv Query variable name.
Definition at line 93 of file class-wp.php.
build_query_string ()
Sets the query string property based off of the query variable property.
The 'query_string' filter is deprecated, but still works. Plugins should use the 'request' filter instead.
Since
2.0.0
Filter the query string before parsing.
Since
1.5.0
Parameters
string $query_string The query string to modify.
Definition at line 507 of file class-wp.php.
References apply_filters(), and has_filter().
Referenced by query_posts().
handle_404 ()
Set the Headers for 404, if nothing is found for requested URL.
Issue a 404 if a request doesn't match any posts and doesn't match any object (e.g. an existing-but-empty category, tag, author) and a 404 was not already issued, and if the request was not a search or the homepage.
Otherwise, issue a 200.
This sets headers after posts have been queried. handle_404() really means "handle status." By inspecting the result of querying posts, seemingly successful requests can be switched to a 404 so that canonical redirection logic can kick in.
Since
2.0.0
WP_Query $wp_query
Definition at line 611 of file class-wp.php.
References $page, get_bloginfo(), get_queried_object(), get_query_var(), is_404, is_admin(), is_author(), is_category(), is_feed(), is_home(), is_paged(), is_post_type_archive(), is_robots(), is_search(), is_singular(), is_tag(), is_tax(), is_user_member_of_blog(), nocache_headers(), pings_open(), and status_header().
Referenced by main().
init ()
Set up the current user.
Since
2.0.0
Definition at line 577 of file class-wp.php.
Referenced by main().
main ($query_args = '')
Sets up all of the variables required by the WordPress environment.
The action 'wp' has one parameter that references the WP object. It allows for accessing the properties and methods to further manipulate the object.
Since
2.0.0
Parameters
string | array $query_args Passed to parse_request()
Fires once the WordPress environment has been set up.
Since
2.1.0
Parameters
WP &$this Current WordPress environment instance (passed by reference).
Definition at line 688 of file class-wp.php.
References do_action_ref_array(), handle_404(), init(), parse_request(), query_posts(), register_globals(), and send_headers().
parse_request ($extra_query_vars = '')
Parse request to find correct WordPress query.
Sets up the query variables based on the request. There are also many filters and actions that can be used to further manipulate the result.
Since
2.0.0
WP_Rewrite $wp_rewrite
Parameters
array | string $extra_query_vars Set the extra query variables.
Filter whether to parse the request.
Since
3.5.0
Parameters
bool $bool Whether or not to parse the request. Default true.
WP $this Current WordPress environment instance.
array | string $extra_query_vars Extra passed query variables.
Filter the query variables whitelist before processing.
Allows (publicly allowed) query vars to be added, removed, or changed prior to executing the query. Needed to allow custom rewrite rules using your own arguments to work, or any other custom query variables you want to be publicly available.
Since
1.5.0
Parameters
array $public_query_vars The array of whitelisted query variables.
Filter the array of parsed query variables.
Since
2.1.0
Parameters
array $query_vars The array of requested query variables.
Fires once all query variables for the current request have been parsed.
Since
2.1.0
Parameters
WP &$this Current WordPress environment instance (passed by reference).
Definition at line 133 of file class-wp.php.
References $_SERVER, $extra_query_vars, $home_path, $page, $post_type, $request, $self, $wp_rewrite, WP_MatchesMapRegex\apply(), apply_filters(), do_action_ref_array(), elseif, get_page_by_path(), get_post_status_object(), get_post_types(), get_taxonomies(), home_url(), is_admin(), is_post_type_viewable(), str_replace, and wp_resolve_numeric_slug_conflicts().
Referenced by main().
query_posts ()
Set up the Loop based on the query variables.
Since
2.0.0
WP_Query $wp_the_query
Definition at line 588 of file class-wp.php.
References build_query_string().
Referenced by main().
register_globals ()
Set up the WordPress Globals.
The query_vars property will be extracted to the GLOBALS. So care should be taken when naming global variables that might interfere with the WordPress environment.
WP_Query $wp_query string $query_string Query string for the loop. array $posts The found posts. WP_Post|null $post The current post, if available. string $request The SQL statement for the request. int $more Only set, if single page or post. int $single If single page or post. Only set, if single page or post. WP_User $authordata Only set, if author archive.
Since
2.0.0
Definition at line 550 of file class-wp.php.
References $GLOBALS, $query_string, $value, and null.
Referenced by main().
remove_query_var ($name)
Remove name from list of public query variables.
Since
4.5.0
Parameters
string $name Query variable name.
Definition at line 105 of file class-wp.php.
References $name.
send_headers ()
Sends additional HTTP headers for caching, content type, etc.
Sets the Content-Type header. Sets the 'error' status (if passed) and optionally exits. If showing a feed, it will also send Last-Modified, ETag, and 304 status if needed.
Since
2.0.0
4.4.0 X-Pingback header is added conditionally after posts have been queried in handle_404().
Filter the HTTP headers before they're sent to the browser.
Since
2.8.0
Parameters
array $headers The list of headers to be sent.
WP $this Current WordPress environment instance.
Fires once the requested HTTP headers for caching, content type, etc. have been sent.
Since
2.1.0
Parameters
WP &$this Current WordPress environment instance (passed by reference).
Definition at line 385 of file class-wp.php.
References $_SERVER, $client_etag, $client_last_modified, $client_modified_timestamp, $name, apply_filters(), do_action_ref_array(), elseif, exit, feed_content_type(), get_default_feed(), get_lastcommentmodified(), get_lastpostmodified(), get_option(), mysql2date(), null, status_header(), wp_get_nocache_headers(), and wp_unslash().
Referenced by main().
set_query_var ($key, $value)
Set the value of a query variable.
Since
2.3.0
Parameters
string $key Query variable name.
mixed $value Query variable value.
Definition at line 117 of file class-wp.php.
References $value.
Field Documentation
$did_permalink = false
Definition at line 84 of file class-wp.php.
$extra_query_vars = array()
Definition at line 36 of file class-wp.php.
Referenced by parse_request().
$matched_query
Definition at line 76 of file class-wp.php.
$matched_rule
Definition at line 68 of file class-wp.php.
$private_query_vars = array('offset', 'posts_per_page', 'posts_per_archive_page', 'showposts', 'nopaging', 'post_type', 'post_status', 'category__in', 'category__not_in', 'category__and', 'tag__in', 'tag__not_in', 'tag__and', 'tag_slug__in', 'tag_slug__and', 'tag_id', 'post_mime_type', 'perm', 'comments_per_page', 'post__in', 'post__not_in', 'post_parent', 'post_parent__in', 'post_parent__not_in', 'title')
Definition at line 28 of file class-wp.php.
$public_query_vars = array('m', 'p', 'posts', 'w', 'cat', 'withcomments', 'withoutcomments', 's', 'search', 'exact', 'sentence', 'calendar', 'page', 'paged', 'more', 'tb', 'pb', 'author', 'order', 'orderby', 'year', 'monthnum', 'day', 'hour', 'minute', 'second', 'name', 'category_name', 'tag', 'feed', 'author_name', 'static', 'pagename', 'page_id', 'error', 'attachment', 'attachment_id', 'subpost', 'subpost_id', 'preview', 'robots', 'taxonomy', 'term', 'cpage', 'post_type', 'embed')
Definition at line 18 of file class-wp.php.
$query_string
Definition at line 52 of file class-wp.php.
Referenced by register_globals().
$query_vars
Definition at line 44 of file class-wp.php.
$request
Definition at line 60 of file class-wp.php.
Referenced by parse_request().
The documentation for this class was generated from the following file:
class-wp.php