GravityView: WP_Role Class Reference
WP_Role Class Reference
Core class used to extend the user roles API.
Public Member Functions
__construct ($role, $capabilities)
Constructor - Set up object properties.
add_cap ($cap, $grant=true)
Assign role a capability.
has_cap ($cap)
Determines whether the role has the given capability.
remove_cap ($cap)
Remove capability from role.
Data Fields
$capabilities
$name
Detailed Description
Core class used to extend the user roles API.
Since
2.0.0
Definition at line 15 of file class-wp-role.php.
Constructor & Destructor Documentation
__construct ($role, $capabilities)
Constructor - Set up object properties.
The list of capabilities, must have the key as the name of the capability and the value a boolean of whether it is granted to the role.
Since
2.0.0 public
Parameters
string $role Role name.
array $capabilities List of capabilities.
Definition at line 46 of file class-wp-role.php.
References $capabilities, and name.
Member Function Documentation
add_cap ($cap, $grant = true)
Assign role a capability.
Since
2.0.0 public
Parameters
string $cap Capability name.
bool $grant Whether role has capability privilege.
Definition at line 60 of file class-wp-role.php.
References name, and wp_roles().
has_cap ($cap)
Determines whether the role has the given capability.
The capabilities is passed through the {
See also
'role_has_cap'} filter. The first parameter for the hook is the list of capabilities the class has assigned. The second parameter is the capability name to look for. The third and final parameter for the hook is the role name.
Since
2.0.0 public
Parameters
string $cap Capability name.
Returns
bool True if the role has the given capability. False otherwise.
Filter which capabilities a role has.
Since
2.0.0
Parameters
array $capabilities Array of role capabilities.
string $cap Capability name.
string $name Role name.
Definition at line 97 of file class-wp-role.php.
References $capabilities, apply_filters(), and name.
remove_cap ($cap)
Remove capability from role.
This is a container for WP_Roles::remove_cap() to remove the capability from the role. That is to say, that WP_Roles::remove_cap() implements the functionality, but it also makes sense to use this class, because you don't need to enter the role name.
Since
2.0.0 public
Parameters
string $cap Capability name.
Definition at line 78 of file class-wp-role.php.
References name, and wp_roles().
Field Documentation
$capabilities
Definition at line 32 of file class-wp-role.php.
Referenced by __construct(), and has_cap().
$name
Definition at line 23 of file class-wp-role.php.
The documentation for this class was generated from the following file:
class-wp-role.php