GravityView: GravityView_Uninstall Class Reference
GravityView_Uninstall Class Reference
Delete GravityView content when GravityView is uninstalled, if the setting is set to "Delete on Uninstall".
Public Member Functions
fire_everything ()
Delete GravityView Views, settings, roles, caps, etc.
Private Member Functions
delete_capabilities ()
Delete capabilities added by GravityView.
delete_entry_meta ()
Delete GravityView "approved entry" meta.
delete_entry_notes ()
Delete all GravityView-generated entry notes.
delete_options ()
Delete GravityView options.
delete_posts ()
Delete all the GravityView custom post type posts.
Detailed Description
Delete GravityView content when GravityView is uninstalled, if the setting is set to "Delete on Uninstall".
Since
1.15
Definition at line 16 of file class-gravityview-uninstall.php.
Member Function Documentation
delete_capabilities()
delete_capabilities () private
Delete capabilities added by GravityView.
Since
1.15
Returns
void
Definition at line 101 of file class-gravityview-uninstall.php.
References GravityView_Roles_Capabilities\get_instance().
Referenced by fire_everything().
delete_entry_meta()
delete_entry_meta () private
Delete GravityView "approved entry" meta.
Since
1.15
Returns
void
Definition at line 39 of file class-gravityview-uninstall.php.
References GravityView_GFFormsModel\get_database_version().
Referenced by fire_everything().
delete_entry_notes()
delete_entry_notes () private
Delete all GravityView-generated entry notes.
Since
1.15
Returns
void
Definition at line 67 of file class-gravityview-uninstall.php.
References GravityView_GFFormsModel\get_database_version().
Referenced by fire_everything().
delete_options()
delete_options () private
Delete GravityView options.
Since
1.15
Returns
void
Definition at line 131 of file class-gravityview-uninstall.php.
Referenced by fire_everything().
delete_posts()
delete_posts () private
Delete all the GravityView custom post type posts.
Since
1.15
Returns
void
Definition at line 110 of file class-gravityview-uninstall.php.
Referenced by fire_everything().
fire_everything()
fire_everything ()
Delete GravityView Views, settings, roles, caps, etc.
See also
https://youtu.be/FXy_DO6IZOA?t=35s
Since
1.15
Returns
void
Definition at line 24 of file class-gravityview-uninstall.php.
References delete_capabilities(), delete_entry_meta(), delete_entry_notes(), delete_options(), and delete_posts().
The documentation for this class was generated from the following file:
class-gravityview-uninstall.php