GravityView: GravityView_Helper_Functions_Test Class Reference
GravityView_Helper_Functions_Test Class Reference
helperfunctions
Public Member Functions
test_gravityview_format_link_DEFAULT ()
gravityview_format_link() _gravityview_strip_subdomain()
test_gravityview_format_link_WHEN_FILTER_NOQUERYSTRING_FALSE ()
gravityview_format_link()
test_gravityview_format_link_WHEN_FILTER_NOSUBDOMAIN_FALSE ()
gravityview_format_link()
test_gravityview_format_link_WHEN_FILTER_ROOTONLY_FALSE ()
gravityview_format_link()
test_gravityview_get_input_id_from_id ()
test_gravityview_is_not_empty_string ()
gravityview_is_not_empty_string
test_gravityview_is_valid_datetime ()
::gravityview_is_valid_datetime
test_gravityview_number_format ()
We only test gravityview_number_format() without a decimal defined; otherwise it's an alias for number_format_i18n()
test_gravityview_sanitize_html_class ()
::gravityview_sanitize_html_class()
test_gravityview_strip_whitespace ()
gravityview_strip_whitespace()
test_gv_empty ()
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
helperfunctions
Definition at line 8 of file helper-functions_Test.php.
Member Function Documentation
test_gravityview_format_link_DEFAULT ()
gravityview_format_link() _gravityview_strip_subdomain()
Definition at line 230 of file helper-functions_Test.php.
References gravityview_format_link().
test_gravityview_format_link_WHEN_FILTER_NOQUERYSTRING_FALSE ()
gravityview_format_link()
Definition at line 401 of file helper-functions_Test.php.
References gravityview_format_link().
test_gravityview_format_link_WHEN_FILTER_NOSUBDOMAIN_FALSE ()
gravityview_format_link()
Definition at line 354 of file helper-functions_Test.php.
References gravityview_format_link().
test_gravityview_format_link_WHEN_FILTER_ROOTONLY_FALSE ()
gravityview_format_link()
Definition at line 324 of file helper-functions_Test.php.
References gravityview_format_link().
test_gravityview_get_input_id_from_id ()
Since
1.16.4 gravityview_get_input_id_from_id()
Definition at line 164 of file helper-functions_Test.php.
References $field_id, and gravityview_get_input_id_from_id().
test_gravityview_is_not_empty_string ()
gravityview_is_not_empty_string
Definition at line 117 of file helper-functions_Test.php.
References gravityview_is_not_empty_string().
test_gravityview_is_valid_datetime ()
::gravityview_is_valid_datetime
Since
1.15.2 datetime
Definition at line 49 of file helper-functions_Test.php.
test_gravityview_number_format ()
We only test gravityview_number_format() without a decimal defined; otherwise it's an alias for number_format_i18n()
See also
number_format_i18n() gravityview_number_format()
Definition at line 144 of file helper-functions_Test.php.
References gravityview_number_format().
test_gravityview_sanitize_html_class ()
::gravityview_sanitize_html_class()
Definition at line 188 of file helper-functions_Test.php.
test_gravityview_strip_whitespace ()
gravityview_strip_whitespace()
Definition at line 94 of file helper-functions_Test.php.
References gravityview_strip_whitespace().
test_gv_empty ()
Since
1.15.1 gv_empty()
Definition at line 14 of file helper-functions_Test.php.
References gv_empty().
The documentation for this class was generated from the following file:
helper-functions_Test.php