GravityView: AMFStream Class Reference
AMFStream Class Reference
Public Member Functions
__construct (&$bytes)
peekByte ()
peekDouble ()
peekInt ()
peekLong ()
peekLongUTF ()
peekUTF ()
read ($length)
readByte ()
readDouble ()
readInt ()
readLong ()
readLongUTF ()
readUTF ()
Data Fields
$bytes
$pos
Detailed Description
Definition at line 389 of file module.audio-video.flv.php.
Constructor & Destructor Documentation
__construct (& $bytes)
Definition at line 393 of file module.audio-video.flv.php.
References $bytes.
Member Function Documentation
peekByte ()
Definition at line 430 of file module.audio-video.flv.php.
References $pos, and readByte().
peekDouble ()
Definition at line 451 of file module.audio-video.flv.php.
References $pos, and readDouble().
peekInt ()
Definition at line 437 of file module.audio-video.flv.php.
References $pos, and readInt().
peekLong ()
Definition at line 444 of file module.audio-video.flv.php.
References $pos, and readLong().
peekLongUTF ()
Definition at line 465 of file module.audio-video.flv.php.
References $pos, and readLongUTF().
peekUTF ()
Definition at line 458 of file module.audio-video.flv.php.
References $pos, and readUTF().
read ($length)
Definition at line 424 of file module.audio-video.flv.php.
Referenced by readDouble(), readLongUTF(), and readUTF().
readByte ()
Definition at line 398 of file module.audio-video.flv.php.
References getid3_lib\BigEndian2Int().
Referenced by peekByte(), readInt(), and readLong().
readDouble ()
Definition at line 410 of file module.audio-video.flv.php.
References getid3_lib\BigEndian2Float(), and read().
Referenced by peekDouble().
readInt ()
Definition at line 402 of file module.audio-video.flv.php.
References readByte().
Referenced by peekInt(), and readUTF().
readLong ()
Definition at line 406 of file module.audio-video.flv.php.
References readByte().
Referenced by peekLong(), and readLongUTF().
readLongUTF ()
Definition at line 419 of file module.audio-video.flv.php.
References read(), and readLong().
Referenced by peekLongUTF().
readUTF ()
Definition at line 414 of file module.audio-video.flv.php.
References read(), and readInt().
Referenced by peekUTF().
Field Documentation
$bytes
Definition at line 390 of file module.audio-video.flv.php.
Referenced by __construct().
$pos
Definition at line 391 of file module.audio-video.flv.php.
Referenced by peekByte(), peekDouble(), peekInt(), peekLong(), peekLongUTF(), and peekUTF().
The documentation for this class was generated from the following file:
module.audio-video.flv.php