GravityView: WP_Links_List_Table Class Reference
WP_Links_List_Table Class Reference
Core class used to implement displaying links in a list table.
Public Member Functions
__construct ($args=array())
Constructor.
ajax_user_can ()
column_categories ($link)
Handles the link categories column output.
column_cb ($link)
Handles the checkbox column output.
column_default ($link, $column_name)
Handles the default column output.
column_name ($link)
Handles the link name column output.
column_rating ($link)
Handles the link rating column output.
column_rel ($link)
Handles the link relation column output.
column_url ($link)
Handles the link URL column output.
column_visible ($link)
Handles the link visibility column output.
display_rows ()
get_columns ()
no_items ()
public
prepare_items ()
int $cat_id string $s string $orderby string $order
Public Member Functions inherited from WP_List_Table
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($args=array())
Constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
_js_vars ()
Send required variables to JavaScript land.
ajax_response ()
Handle an incoming ajax request (called from admin-ajax.php)
ajax_user_can ()
Checks the current user's permissions.
current_action ()
Get the current action selected from the bulk actions dropdown.
display ()
Display the table.
display_rows ()
Generate the table rows.
display_rows_or_placeholder ()
Generate the tbody element for the list table.
get_column_count ()
Return number of visible columns.
get_columns ()
Get a list of columns.
get_pagenum ()
Get the current page number.
get_pagination_arg ($key)
Access the pagination args.
get_primary_column ()
Public wrapper for WP_List_Table::get_default_primary_column_name().
has_items ()
Whether the table has items to display or not.
no_items ()
Message to be displayed when there are no items.
prepare_items ()
Prepares the list of items for displaying.
print_column_headers ($with_id=true)
Print column headers, accounting for hidden and sortable columns.
search_box ($text, $input_id)
Display the search box.
single_row ($item)
Generates content for a single row of the table.
views ()
Display the list of views available on this table.
Protected Member Functions
extra_tablenav ($which)
int $cat_id
get_bulk_actions ()
get_default_primary_column_name ()
Get the name of the default primary column.
get_sortable_columns ()
handle_row_actions ($link, $column_name, $primary)
Generates and displays row action links.
Protected Member Functions inherited from WP_List_Table
bulk_actions ($which= '')
Display the bulk actions dropdown.
column_cb ($item)
column_default ($item, $column_name)
comments_bubble ($post_id, $pending_comments)
Display a comment count bubble.
display_tablenav ($which)
Generate the table navigation above or below the table.
extra_tablenav ($which)
Extra controls to be displayed between bulk actions and pagination.
get_bulk_actions ()
Get an associative array (option_name => option_title) with the list of bulk actions available on this table.
get_column_info ()
Get a list of all, hidden and sortable columns, with filter applied.
get_default_primary_column_name ()
Gets the name of the default primary column.
get_items_per_page ($option, $default=20)
Get number of items to display on a single page.
get_primary_column_name ()
Gets the name of the primary column.
get_sortable_columns ()
Get a list of sortable columns.
get_table_classes ()
Get a list of CSS classes for the WP_List_Table table tag.
get_views ()
Get an associative array (id => link) with the list of views available on this table.
handle_row_actions ($item, $column_name, $primary)
Generates and display row actions links for the list table.
months_dropdown ($post_type)
Display a monthly dropdown for filtering items.
pagination ($which)
Display the pagination.
row_actions ($actions, $always_visible=false)
Generate row actions div.
set_pagination_args ($args)
An internal method that sets all the necessary pagination arguments.
single_row_columns ($item)
Generates the columns for a single row of the table.
view_switcher ($current_mode)
Display a view switcher.
Additional Inherited Members
Data Fields inherited from WP_List_Table
$items
Protected Attributes inherited from WP_List_Table
$_args
$_column_headers
$_pagination_args = array()
$compat_fields = array('_args', '_pagination_args', 'screen', '_actions', '_pagination')
{
$compat_methods
{
$modes = array()
$screen
Detailed Description
Core class used to implement displaying links in a list table.
Since
3.1.0 private
See also
WP_List_Tsble
Definition at line 18 of file class-wp-links-list-table.php.
Constructor & Destructor Documentation
__construct ($args = array())
Constructor.
Since
3.1.0 public
See also
WP_List_Table::__construct() for more information on default arguments.
Parameters
array $args An associative array of arguments.
Definition at line 30 of file class-wp-links-list-table.php.
References null.
Member Function Documentation
ajax_user_can ()
Returns
bool
Definition at line 41 of file class-wp-links-list-table.php.
References current_user_can().
column_categories ($link)
Handles the link categories column output.
Since
4.3.0 public
$cat_id
Parameters
object $link The current link object.
Definition at line 217 of file class-wp-links-list-table.php.
References $link, get_term(), is_wp_error(), and OBJECT.
column_cb ($link)
Handles the checkbox column output.
Since
4.3.0 public
Parameters
object $link The current link object.
Definition at line 170 of file class-wp-links-list-table.php.
References $link, __, input, label, and name.
column_default ($link, $column_name)
Handles the default column output.
Since
4.3.0 public
Parameters
object $link Link object.
string $column_name Current column name.
Fires for each registered custom link column.
Since
2.1.0
Parameters
string $column_name Name of the custom column.
int $link_id Link ID.
Definition at line 284 of file class-wp-links-list-table.php.
References $link, and do_action().
column_name ($link)
Handles the link name column output.
Since
4.3.0 public
Parameters
object $link The current link object.
Definition at line 185 of file class-wp-links-list-table.php.
References $link, get_edit_bookmark_link(), and label.
column_rating ($link)
Handles the link rating column output.
Since
4.3.0 public
Parameters
object $link The current link object.
Definition at line 271 of file class-wp-links-list-table.php.
References $link.
column_rel ($link)
Handles the link relation column output.
Since
4.3.0 public
Parameters
object $link The current link object.
Definition at line 243 of file class-wp-links-list-table.php.
References $link.
column_url ($link)
Handles the link URL column output.
Since
4.3.0 public
Parameters
object $link The current link object.
Definition at line 202 of file class-wp-links-list-table.php.
References $link, and url_shorten().
column_visible ($link)
Handles the link visibility column output.
Since
4.3.0 public
Parameters
object $link The current link object.
Definition at line 255 of file class-wp-links-list-table.php.
References $link, and _e.
display_rows ()
Definition at line 296 of file class-wp-links-list-table.php.
References $link, esc_attr(), sanitize_bookmark(), WP_List_Table\single_row_columns(), and wp_get_link_cats().
extra_tablenav ($which) protected
int $cat_id
Parameters
string $which
Definition at line 94 of file class-wp-links-list-table.php.
References __, submit_button(), and wp_dropdown_categories().
get_bulk_actions () protected
Returns
array
Definition at line 82 of file class-wp-links-list-table.php.
References __.
get_columns ()
Returns
array
Definition at line 125 of file class-wp-links-list-table.php.
References __, and _x.
get_default_primary_column_name () protected
Get the name of the default primary column.
Since
4.3.0 protected
Returns
string Name of the default primary column, in this case, 'name'.
Definition at line 158 of file class-wp-links-list-table.php.
get_sortable_columns () protected
Returns
array
Definition at line 141 of file class-wp-links-list-table.php.
handle_row_actions ($link, $column_name, $primary) protected
Generates and displays row action links.
Since
4.3.0 protected
Parameters
object $link Link being acted upon.
string $column_name Current column name.
string $primary Primary column name.
Returns
string Row action output for links.
Definition at line 320 of file class-wp-links-list-table.php.
References $link, __, esc_js(), get_edit_bookmark_link(), WP_List_Table\row_actions(), and wp_nonce_url().
no_items ()
public
Definition at line 74 of file class-wp-links-list-table.php.
References _e.
prepare_items ()
int $cat_id string $s string $orderby string $order
Definition at line 52 of file class-wp-links-list-table.php.
References $s, get_bookmarks(), and wp_reset_vars().
The documentation for this class was generated from the following file:
class-wp-links-list-table.php