GravityView: getid3_quicktime Class Reference
getid3_quicktime Class Reference
Public Member Functions
Analyze ()
CopyToAppropriateCommentsSection ($keyname, $data, $boxname='')
NoNullString ($nullterminatedstring)
Pascal2String ($pascalstring)
quicktime_read_mp4_descr_length ($data, &$offset)
QuicktimeAudioCodecLookup ($codecid)
QuicktimeColorNameLookup ($colordepthid)
QuicktimeContentRatingLookup ($rtng)
QuicktimeDCOMLookup ($compressionid)
QuicktimeIODSaudioProfileName ($audio_profile_id)
QuicktimeIODSvideoProfileName ($video_profile_id)
QuicktimeLanguageLookup ($languageid)
QuicktimeParseAtom ($atomname, $atomsize, $atom_data, $baseoffset, &$atomHierarchy, $ParseAllPossibleAtoms)
QuicktimeParseContainerAtom ($atom_data, $baseoffset, &$atomHierarchy, $ParseAllPossibleAtoms)
QuicktimeParseNikonNCTG ($atom_data)
QuicktimeSTIKLookup ($stik)
QuicktimeStoreAccountTypeLookup ($akid)
QuicktimeStoreFrontCodeLookup ($sfid)
QuicktimeVideoCodecLookup ($codecid)
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Data Fields
$ParseAllPossibleAtoms = false
$ReturnAtomData = true
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
Definition at line 21 of file module.audio-video.quicktime.php.
Member Function Documentation
Analyze ()
Definition at line 27 of file module.audio-video.quicktime.php.
References getid3_lib\BigEndian2Int(), getid3_handler\fread(), getid3_handler\fseek(), getid3_lib\intValueSupported(), and QuicktimeParseAtom().
CopyToAppropriateCommentsSection ($keyname, $data, $boxname = '')
Definition at line 2111 of file module.audio-video.quicktime.php.
References elseif.
Referenced by QuicktimeParseAtom().
NoNullString ($nullterminatedstring)
Definition at line 2233 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
Pascal2String ($pascalstring)
Definition at line 2241 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
quicktime_read_mp4_descr_length ($data, & $offset)
Definition at line 1455 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeAudioCodecLookup ($codecid)
Definition at line 1663 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeColorNameLookup ($colordepthid)
Definition at line 1717 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeContentRatingLookup ($rtng)
Definition at line 1884 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeDCOMLookup ($compressionid)
Definition at line 1708 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeIODSaudioProfileName ($audio_profile_id)
Definition at line 1752 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeIODSvideoProfileName ($video_profile_id)
Definition at line 1812 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeLanguageLookup ($languageid)
Definition at line 1467 of file module.audio-video.quicktime.php.
References getid3_id3v2\LanguageLookup().
Referenced by QuicktimeParseAtom().
QuicktimeParseAtom ($atomname, $atomsize, $atom_data, $baseoffset, & $atomHierarchy, $ParseAllPossibleAtoms)
Definition at line 121 of file module.audio-video.quicktime.php.
References $i, $ParseAllPossibleAtoms, $value, getid3_lib\BigEndian2Int(), CopyToAppropriateCommentsSection(), getid3_lib\DateMac2Unix(), elseif, getid3_lib\FixedPoint16_16(), getid3_lib\FixedPoint2_30(), getid3_lib\FixedPoint8_8(), getid3_id3v1\LookupGenreName(), NoNullString(), null, Pascal2String(), getid3_lib\PrintHexBytes(), quicktime_read_mp4_descr_length(), QuicktimeAudioCodecLookup(), QuicktimeColorNameLookup(), QuicktimeContentRatingLookup(), QuicktimeDCOMLookup(), QuicktimeIODSaudioProfileName(), QuicktimeIODSvideoProfileName(), QuicktimeLanguageLookup(), QuicktimeParseContainerAtom(), QuicktimeParseNikonNCTG(), QuicktimeSTIKLookup(), QuicktimeStoreFrontCodeLookup(), and QuicktimeVideoCodecLookup().
Referenced by Analyze(), and QuicktimeParseContainerAtom().
QuicktimeParseContainerAtom ($atom_data, $baseoffset, & $atomHierarchy, $ParseAllPossibleAtoms)
Definition at line 1427 of file module.audio-video.quicktime.php.
References $ParseAllPossibleAtoms, getid3_lib\BigEndian2Int(), and QuicktimeParseAtom().
Referenced by QuicktimeParseAtom().
QuicktimeParseNikonNCTG ($atom_data)
Definition at line 1932 of file module.audio-video.quicktime.php.
References $i, and getid3_lib\BigEndian2Int().
Referenced by QuicktimeParseAtom().
QuicktimeSTIKLookup ($stik)
Definition at line 1735 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeStoreAccountTypeLookup ($akid)
Definition at line 1894 of file module.audio-video.quicktime.php.
QuicktimeStoreFrontCodeLookup ($sfid)
Definition at line 1903 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
QuicktimeVideoCodecLookup ($codecid)
Definition at line 1604 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom().
Field Documentation
$ParseAllPossibleAtoms = false
Definition at line 25 of file module.audio-video.quicktime.php.
Referenced by QuicktimeParseAtom(), and QuicktimeParseContainerAtom().
$ReturnAtomData = true
Definition at line 24 of file module.audio-video.quicktime.php.
The documentation for this class was generated from the following file:
module.audio-video.quicktime.php