GravityView: WP_Filesystem_Base Class Reference
WP_Filesystem_Base Class Reference
Base WordPress Filesystem class for which Filesystem implementations extend.
Public Member Functions
abspath ()
Return the path on the remote filesystem of ABSPATH.
atime ($file)
Gets the file's last access time.
chdir ($dir)
Change current directory.
chgrp ($file, $group, $recursive=false)
Change the file group.
chmod ($file, $mode=false, $recursive=false)
Change filesystem permissions.
chown ($file, $owner, $recursive=false)
Change the ownership of a file / folder.
connect ()
Connect filesystem.
copy ($source, $destination, $overwrite=false, $mode=false)
Copy a file.
cwd ()
Get the current working directory.
delete ($file, $recursive=false, $type=false)
Delete a file or directory.
dirlist ($path, $include_hidden=true, $recursive=false)
Get details for files in a directory or a specific file.
exists ($file)
Check if a file or directory exists.
find_base_dir ($base= '.', $echo=false)
Locate a folder on the remote filesystem.
find_folder ($folder)
Locate a folder on the remote filesystem.
get_base_dir ($base= '.', $echo=false)
Locate a folder on the remote filesystem.
get_contents ($file)
Read entire file into a string.
get_contents_array ($file)
Read entire file into an array.
getchmod ($file)
Gets the permissions of the specified file or filepath in their octal format.
gethchmod ($file)
Return the *nix-style file permissions for a file.
getnumchmodfromh ($mode)
Convert *nix-style file permissions to a octal number.
group ($file)
Get the file's group.
is_binary ($text)
Determine if the string provided contains binary characters.
is_dir ($path)
Check if resource is a directory.
is_file ($file)
Check if resource is a file.
is_readable ($file)
Check if a file is readable.
is_writable ($file)
Check if a file or directory is writable.
mkdir ($path, $chmod=false, $chown=false, $chgrp=false)
Create a directory.
move ($source, $destination, $overwrite=false)
Move a file.
mtime ($file)
Gets the file modification time.
owner ($file)
Get the file owner.
put_contents ($file, $contents, $mode=false)
Write a string to a file.
rmdir ($path, $recursive=false)
Delete a directory.
search_for_folder ($folder, $base= '.', $loop=false)
Locate a folder on the remote filesystem.
size ($file)
Gets the file size (in bytes).
touch ($file, $time=0, $atime=0)
Set the access and modification times of a file.
wp_content_dir ()
Return the path on the remote filesystem of WP_CONTENT_DIR.
wp_lang_dir ()
Return the path on the remote filesystem of WP_LANG_DIR.
wp_plugins_dir ()
Return the path on the remote filesystem of WP_PLUGIN_DIR.
wp_themes_dir ($theme=false)
Return the path on the remote filesystem of the Themes Directory.
Data Fields
$cache = array()
$errors = null
public
$method = ''
$options = array()
public
$verbose = false
Detailed Description
Base WordPress Filesystem class for which Filesystem implementations extend.
Since
2.5.0
Definition at line 14 of file class-wp-filesystem-base.php.
Member Function Documentation
abspath ()
Return the path on the remote filesystem of ABSPATH.
public
Since
2.7.0
Returns
string The location of the remote path.
Definition at line 60 of file class-wp-filesystem-base.php.
References ABSPATH, find_folder(), is_dir(), and WPINC.
Referenced by find_base_dir(), and get_base_dir().
atime ($file)
Gets the file's last access time.
public
Since
2.5.0
Parameters
string $file Path to file.
Returns
int|bool Unix timestamp representing last access time.
Definition at line 725 of file class-wp-filesystem-base.php.
chdir ($dir)
Change current directory.
public
Since
2.5.0
Parameters
string $dir The new current directory.
Returns
bool|string
Definition at line 527 of file class-wp-filesystem-base.php.
chgrp ($file, $group, $recursive = false)
Change the file group.
public
Since
2.5.0
Parameters
string $file Path to the file.
mixed $group A group name or number.
bool $recursive Optional. If set True changes file group recursively. Defaults to False.
Returns
bool|string
Definition at line 543 of file class-wp-filesystem-base.php.
chmod ($file, $mode = false, $recursive = false)
Change filesystem permissions.
public
Since
2.5.0
Parameters
string $file Path to the file.
int $mode Optional. The permissions as octal number, usually 0644 for files, 0755 for dirs.
bool $recursive Optional. If set True changes file group recursively. Defaults to False.
Returns
bool|string
Definition at line 559 of file class-wp-filesystem-base.php.
chown ($file, $owner, $recursive = false)
Change the ownership of a file / folder.
Default behavior is to do nothing, override this in your subclass, if desired.
public
Since
2.5.0
Parameters
string $file Path to the file.
mixed $owner A user name or number.
bool $recursive Optional. If set True changes file owner recursivly. Defaults to False.
Returns
bool Returns true on success or false on failure.
Definition at line 443 of file class-wp-filesystem-base.php.
connect ()
Connect filesystem.
public
Since
2.5.0
Returns
bool True on success or false on failure (always true for WP_Filesystem_Direct).
Definition at line 456 of file class-wp-filesystem-base.php.
copy ($source, $destination, $overwrite = false, $mode = false)
Copy a file.
public
Since
2.5.0
Parameters
string $source Path to the source file.
string $destination Path to the destination file.
bool $overwrite Optional. Whether to overwrite the destination file if it exists. Default false.
int $mode Optional. The permissions as octal number, usually 0644 for files, 0755 for dirs. Default false.
Returns
bool True if file copied successfully, False otherwise.
Definition at line 606 of file class-wp-filesystem-base.php.
cwd ()
Get the current working directory.
public
Since
2.5.0
Returns
string|bool The current working directory on success, or false on failure.
Definition at line 513 of file class-wp-filesystem-base.php.
Referenced by search_for_folder().
delete ($file, $recursive = false, $type = false)
Delete a file or directory.
public
Since
2.5.0
Parameters
string $file Path to the file.
bool $recursive Optional. If set True changes file group recursively. Defaults to False. Default false.
bool $type Type of resource. 'f' for file, 'd' for directory. Default false.
Returns
bool True if the file or directory was deleted, false on failure.
Definition at line 641 of file class-wp-filesystem-base.php.
dirlist ($path, $include_hidden = true, $recursive = false)
Get details for files in a directory or a specific file.
public
Since
2.5.0
Parameters
string $path Path to directory or file.
bool $include_hidden Optional. Whether to include details of hidden ("." prefixed) files. Default true.
bool $recursive Optional. Whether to recursively include file details in nested directories. Default false.
Returns
array|bool { Array of files. False if unable to list directory contents.
string $name Name of the file/directory. string $perms *nix representation of permissions. int $permsn Octal representation of permissions. string $owner Owner name or ID. int $size Size of file in bytes. int $lastmodunix Last modified unix timestamp. mixed $lastmod Last modified month (3 letter) and day (without leading 0). int $time Last modified time. string $type Type of resource. 'f' for file, 'd' for directory. mixed $files If a directory and $recursive is true, contains another array of files. }
Definition at line 840 of file class-wp-filesystem-base.php.
Referenced by search_for_folder().
exists ($file)
Check if a file or directory exists.
public
Since
2.5.0
Parameters
string $file Path to file/directory.
Returns
bool Whether $file exists or not.
Definition at line 655 of file class-wp-filesystem-base.php.
Referenced by find_folder().
find_base_dir ($base = '.', $echo = false)
Locate a folder on the remote filesystem.
public
Since
2.5.0
Parameters
string $base The folder to start searching from.
bool $echo True to display debug information. Default false.
Returns
string The location of the remote path.
Definition at line 140 of file class-wp-filesystem-base.php.
References _deprecated_function(), and abspath().
find_folder ($folder)
Locate a folder on the remote filesystem.
Assumes that on Windows systems, Stripping off the Drive letter is OK Sanitizes \ to / in windows filepaths.
public
Since
2.7.0
Parameters
string $folder the folder to locate.
Returns
string|false The location of the remote path, false on failure.
Definition at line 180 of file class-wp-filesystem-base.php.
References $dir, ABSPATH, elseif, exists(), is_dir(), search_for_folder(), str_replace, trailingslashit(), and WP_CONTENT_DIR.
Referenced by WP_Filesystem_MockFS\abspath(), abspath(), wp_content_dir(), wp_lang_dir(), wp_plugins_dir(), and wp_themes_dir().
get_base_dir ($base = '.', $echo = false)
Locate a folder on the remote filesystem.
public
Since
2.5.0
Parameters
string $base The folder to start searching from.
bool $echo True to display debug information.
Returns
string The location of the remote path.
Definition at line 162 of file class-wp-filesystem-base.php.
References _deprecated_function(), and abspath().
get_contents ($file)
Read entire file into a string.
public
Since
2.5.0
Parameters
string $file Name of the file to read.
Returns
mixed|bool Returns the read data or false on failure.
Definition at line 470 of file class-wp-filesystem-base.php.
get_contents_array ($file)
Read entire file into an array.
public
Since
2.5.0
Parameters
string $file Path to the file.
Returns
array|bool the file contents in an array or false on failure.
Definition at line 484 of file class-wp-filesystem-base.php.
getchmod ($file)
Gets the permissions of the specified file or filepath in their octal format.
public
Since
2.5.0
Parameters
string $file
Returns
string the last 3 characters of the octal number
Definition at line 377 of file class-wp-filesystem-base.php.
Referenced by gethchmod().
gethchmod ($file)
Return the *nix-style file permissions for a file.
From the PHP documentation page for fileperms().
public 2.5.0 string $file String filename. string The *nix-style representation of permissions.
Definition at line 327 of file class-wp-filesystem-base.php.
References $file, elseif, and getchmod().
Referenced by WP_Filesystem_Direct\dirlist(), and WP_Filesystem_SSH2\dirlist().
getnumchmodfromh ($mode)
Convert *nix-style file permissions to a octal number.
Converts '-rw-r–r–' to 0644 From "info at rvgate dot nl"'s comment on the PHP documentation for chmod()
public 2.5.0 string $mode string The *nix-style file permission. int octal representation
Definition at line 395 of file class-wp-filesystem-base.php.
References $i, and $mode.
Referenced by WP_Filesystem_Direct\dirlist(), WP_Filesystem_ftpsockets\dirlist(), WP_Filesystem_SSH2\dirlist(), and WP_Filesystem_FTPext\parselisting().
group ($file)
Get the file's group.
public
Since
2.5.0
Parameters
string $file Path to the file.
Returns
string|bool The group or false on error.
Definition at line 587 of file class-wp-filesystem-base.php.
is_binary ($text)
Determine if the string provided contains binary characters.
public
Since
2.7.0
Parameters
string $text String to test against.
Returns
bool true if string is binary, false otherwise.
Definition at line 426 of file class-wp-filesystem-base.php.
References $text.
is_dir ($path)
Check if resource is a directory.
public
Since
2.5.0
Parameters
string $path Directory path.
Returns
bool Whether $path is a directory.
Definition at line 683 of file class-wp-filesystem-base.php.
Referenced by abspath(), find_folder(), and wp_themes_dir().
is_file ($file)
Check if resource is a file.
public
Since
2.5.0
Parameters
string $file File path.
Returns
bool Whether $file is a file.
Definition at line 669 of file class-wp-filesystem-base.php.
is_readable ($file)
Check if a file is readable.
public
Since
2.5.0
Parameters
string $file Path to file.
Returns
bool Whether $file is readable.
Definition at line 697 of file class-wp-filesystem-base.php.
is_writable ($file)
Check if a file or directory is writable.
public
Since
2.5.0
Parameters
string $file Path to file.
Returns
bool Whether $file is writable.
Definition at line 711 of file class-wp-filesystem-base.php.
mkdir ($path, $chmod = false, $chown = false, $chgrp = false)
Create a directory.
public
Since
2.5.0
Parameters
string $path Path for new directory.
mixed $chmod Optional. The permissions as octal number, (or False to skip chmod) Default false.
mixed $chown Optional. A user name or number (or False to skip chown) Default false.
mixed $chgrp Optional. A group name or number (or False to skip chgrp). Default false.
Returns
bool False if directory cannot be created, true otherwise.
Definition at line 793 of file class-wp-filesystem-base.php.
move ($source, $destination, $overwrite = false)
Move a file.
public
Since
2.5.0
Parameters
string $source Path to the source file.
string $destination Path to the destination file.
bool $overwrite Optional. Whether to overwrite the destination file if it exists. Default false.
Returns
bool True if file copied successfully, False otherwise.
Definition at line 623 of file class-wp-filesystem-base.php.
mtime ($file)
Gets the file modification time.
public
Since
2.5.0
Parameters
string $file Path to file.
Returns
int|bool Unix timestamp representing modification time.
Definition at line 739 of file class-wp-filesystem-base.php.
owner ($file)
Get the file owner.
public
Since
2.5.0
Parameters
string $file Path to the file.
Returns
string|bool Username of the user or false on error.
Definition at line 573 of file class-wp-filesystem-base.php.
put_contents ($file, $contents, $mode = false)
Write a string to a file.
public
Since
2.5.0
Parameters
string $file Remote path to the file where to write the data.
string $contents The data to write.
int $mode Optional. The file permissions as octal number, usually 0644.
Returns
bool False on failure.
Definition at line 500 of file class-wp-filesystem-base.php.
rmdir ($path, $recursive = false)
Delete a directory.
public
Since
2.5.0
Parameters
string $path Path to directory.
bool $recursive Optional. Whether to recursively remove files/directories. Default false.
Returns
bool Whether directory is deleted successfully or not.
Definition at line 809 of file class-wp-filesystem-base.php.
search_for_folder ($folder, $base = '.', $loop = false)
Locate a folder on the remote filesystem.
Expects Windows sanitized path.
public
Since
2.7.0
Parameters
string $folder The folder to locate.
string $base The folder to start searching from.
bool $loop If the function has recursed, Internal use only.
Returns
string|false The location of the remote path, false to cease looping.
Definition at line 248 of file class-wp-filesystem-base.php.
References __, cwd(), dirlist(), path_join(), trailingslashit(), and untrailingslashit().
Referenced by find_folder().
size ($file)
Gets the file size (in bytes).
public
Since
2.5.0
Parameters
string $file Path to file.
Returns
int|bool Size of the file in bytes.
Definition at line 753 of file class-wp-filesystem-base.php.
touch ($file, $time = 0, $atime = 0)
Set the access and modification times of a file.
Note: If $file doesn't exist, it will be created.
public
Since
2.5.0
Parameters
string $file Path to file.
int $time Optional. Modified time to set for file. Default 0.
int $atime Optional. Access time to set for file. Default 0.
Returns
bool Whether operation was successful or not.
Definition at line 773 of file class-wp-filesystem-base.php.
wp_content_dir ()
Return the path on the remote filesystem of WP_CONTENT_DIR.
public
Since
2.7.0
Returns
string The location of the remote path.
Definition at line 76 of file class-wp-filesystem-base.php.
References find_folder(), and WP_CONTENT_DIR.
wp_lang_dir ()
Return the path on the remote filesystem of WP_LANG_DIR.
public
Since
3.2.0
Returns
string The location of the remote path.
Definition at line 119 of file class-wp-filesystem-base.php.
References find_folder().
wp_plugins_dir ()
Return the path on the remote filesystem of WP_PLUGIN_DIR.
public
Since
2.7.0
Returns
string The location of the remote path.
Definition at line 88 of file class-wp-filesystem-base.php.
References find_folder().
wp_themes_dir ($theme = false)
Return the path on the remote filesystem of the Themes Directory.
public
Since
2.7.0
Parameters
string $theme The Theme stylesheet or template for the directory.
Returns
string The location of the remote path.
Definition at line 101 of file class-wp-filesystem-base.php.
References $theme, find_folder(), get_theme_root(), is_dir(), and WP_CONTENT_DIR.
Field Documentation
$cache = array()
Definition at line 31 of file class-wp-filesystem-base.php.
$errors = null
public
Definition at line 45 of file class-wp-filesystem-base.php.
$method = ''
Definition at line 40 of file class-wp-filesystem-base.php.
$options = array()
public
Definition at line 50 of file class-wp-filesystem-base.php.
$verbose = false
Definition at line 22 of file class-wp-filesystem-base.php.
The documentation for this class was generated from the following file:
class-wp-filesystem-base.php