GravityView: GVCommon Class Reference
GVCommon Class Reference
If this file is called directly, abort.
Static Public Member Functions
static array_merge_recursive_distinct (array &$array1, array &$array2)
array_merge_recursive does indeed merge arrays, but it converts values with duplicate keys to arrays rather than overwriting the value in the first array with the duplicate value in the second array, as array_merge does.
static calculate_get_entries_criteria ($passed_criteria=array(), $form_ids=array())
Calculates the Search Criteria used on the self::get_entries / self::get_entry methods.
static decode_shortcodes ($string)
Inspired on ::encode_shortcodes, reverse the encoding by replacing the ascii characters by the shortcode brackets.
static entry_has_transaction_data ($entry=array())
Check if an entry has transaction data.
static format_date ($date_string='', $args=array())
Allow formatting date and time based on GravityView standards.
static generate_notice ($notice, $class='', $cap='', $object_id=null)
Display updated/error notice.
static get_all_views ($args=array())
Get all existing Views.
static get_connected_views ($form_id, $args=array())
Get the views for a particular form.
static get_directory_fields ($post_id, $apply_filter=true)
Get the field configuration for the View.
static get_directory_widgets ($view_id, $json_decode=false)
Get the widget configuration for a View.
static get_entries ($form_ids=null, $passed_criteria=null, &$total=null)
Retrieve entries given search, sort, paging criteria.
static get_entry ($entry_slug, $force_allow_ids=false, $check_entry_display=true)
Return a single entry object.
static get_entry_id ($entry_id_or_slug='', $force_allow_ids=false)
Get the entry ID from a string that may be the Entry ID or the Entry Slug.
static get_entry_id_from_slug ($slug)
Get the entry ID from the entry slug, which may or may not be the entry ID.
static get_entry_ids ($form_id, $search_criteria=array())
Wrapper for the Gravity Forms GFFormsModel::search_lead_ids() method.
static get_entry_meta ($form_id, $only_default_column=true)
get extra fields from entry meta
static get_field ($form, $field_id)
Returns the field details array of a specific form given the field id.
static get_field_array ($field)
Return a Gravity Forms field array, whether using GF 1.9 or not.
static get_field_label ($form=array(), $field_id='', $field_value='')
Retrieve the label of a given field id (for a specific form)
static get_field_type ($form=null, $field_id='')
Returns the GF Form field type for a certain field(id) of a form.
static get_form ($form_id)
Returns the form object for a given Form ID.
static get_form_fields ($form='', $add_default_properties=false, $include_parent_field=true)
Return array of fields' id and label, for a given Form ID.
static get_form_from_entry_id ($entry_slug)
Get the form array for an entry based only on the entry ID.
static get_forms ($active=true, $trash=false)
Alias of GFAPI::get_forms()
static get_link_html ($href='', $anchor_text='', $atts=array())
Generate an HTML anchor tag with a list of supported attributes.
static get_meta_form_id ($view_id)
Get the Gravity Forms form ID connected to a View.
static get_meta_template_id ($view_id)
Get the template ID (list, table, datatables, map) for a View.
static get_product_field_types ()
Return array of product field types.
static get_sortable_fields ($formid, $current='')
Render dropdown (select) with the list of sortable fields from a form ID.
static get_sortable_fields_array ($formid, $blacklist=array('list', 'textarea'))
static get_template_setting ($post_id, $key)
Get the setting for a View.
static get_template_settings ($post_id)
Get all the settings for a View.
static get_users ($context='change_entry_creator', $args=array())
Get WordPress users with reasonable limits set.
static gv_parse_str ($string, &$result)
Do the same than parse_str without max_input_vars limitation: Parses $string as if it were the query string passed via a URL and sets variables in the current scope.
static has_cap ($caps='', $object_id=null, $user_id=null)
Alias of GravityView_Roles_Capabilities::has_cap()
static has_gravityview_shortcode ($post=null)
Check whether the post is GravityView.
static has_product_field ($form=array())
Check whether a form has product fields.
static has_shortcode_r ($content, $tag='gravityview')
Placeholder until the recursive has_shortcode() patch is merged.
static is_field_numeric ($form=null, $field='')
Checks if the field type is a 'numeric' field type (e.g.
static js_encrypt ($content, $message='')
Encrypt content using Javascript so that it's hidden when JS is disabled.
static matches_operation ($val1, $val2, $operation)
Wrapper for the GFFormsModel::matches_operation() method that adds additional comparisons, including: 'equals', 'greater_than_or_is', 'greater_than_or_equals', 'less_than_or_is', 'less_than_or_equals', 'not_contains', 'in', and 'not_in'.
static send_email ($from, $to, $bcc, $reply_to, $subject, $message, $from_name='', $message_format='html', $attachments='', $entry=false, $notification=false)
Send email using GFCommon::send_email()
Detailed Description
If this file is called directly, abort.
Definition at line 19 of file class-common.php.
Member Function Documentation
array_merge_recursive_distinct()
static array_merge_recursive_distinct (array & $array1, array & $array2) static
array_merge_recursive does indeed merge arrays, but it converts values with duplicate keys to arrays rather than overwriting the value in the first array with the duplicate value in the second array, as array_merge does.
See also
http://php.net/manual/en/function.array-merge-recursive.php
Since
1.5.3
Parameters
array $array1
array $array2
Returns
array
Author
Daniel <daniel (at) danielsmedegaardbuus (dot) dk>
Gabriel Sobrinho <gabriel (dot) sobrinho (at) gmail (dot) com>
Definition at line 1772 of file class-common.php.
References $value.
calculate_get_entries_criteria()
static calculate_get_entries_criteria ($passed_criteria = array(), $form_ids = array()) static
Calculates the Search Criteria used on the self::get_entries / self::get_entry methods.
Since
1.7.4
Parameters
array $passed_criteria array Input Criteria (search_criteria, sorting, paging)
array $form_ids array Gravity Forms form IDs
Returns
array
Runs Filter:
gravityview_search_operator Modify the search operator for the field (contains, is, isnot, etc)
Parameters
string $operator Existing search operator
array $filter array with key, value, operator, type keys
Prepare date formats to be in Gravity Forms DB format; $passed_criteria may include date formats incompatible with Gravity Forms.
Runs Filter:
gravityview_search_criteria Apply final criteria filter (Used by the Advanced Filter extension)
Parameters
array $criteria Search criteria used by GravityView
array $form_ids Forms to search
int $view_id ID of the view being used to search
Definition at line 430 of file class-common.php.
References $criteria, GV\get(), GravityView_frontend\getInstance(), GravityView_View_Data\getInstance(), and gravityview().
Referenced by View\as_data(), and GV\Mocks\GravityView_frontend_get_view_entries().
decode_shortcodes()
static decode_shortcodes ($string) static
Inspired on ::encode_shortcodes, reverse the encoding by replacing the ascii characters by the shortcode brackets.
Since
1.16.5
Parameters
string $string Input string to decode
Returns
string $string Output string
Definition at line 1844 of file class-common.php.
entry_has_transaction_data()
static entry_has_transaction_data ($entry = array()) static
Check if an entry has transaction data.
Checks the following keys to see if they are set: 'payment_status', 'payment_date', 'transaction_id', 'payment_amount', 'payment_method'
Since
1.20
Parameters
array $entry Gravity Forms entry array
Returns
bool True: Entry has metadata suggesting it has communicated with a payment gateway; False: it does not have that data.
Definition at line 181 of file class-common.php.
References $entry, and Utils\get().
Referenced by GravityView_Plugin_Hooks_Gravity_Forms_Coupon\should_hide_coupon_fields(), and GravityView_Field_Product\should_hide_product_fields().
format_date()
static format_date ($date_string = '', $args = array()) static
Allow formatting date and time based on GravityView standards.
Since
1.16
See also
GVCommon_Test::test_format_date for examples
Parameters
string $date_string The date as stored by Gravity Forms (Y-m-d h:i:s GMT)
string | array $args Array or string of settings for output parsed by wp_parse_args(); Can use raw=1 or `array('raw' => true)\n -rawUn-formatted date string in originalY-m-d h:i:sformat -timestampInteger timestamp returned by GFCommon::get_local_timestamp() -diff"%s ago" format, unless otherformatis defined -humanSet $is_human parameter to true forGFCommon::format_date(). Showsdiffwithin 24 hours or date after. Format based on blog setting, unlessformatis defined. -timeInclude time in theGFCommon::format_date()output -formatDefine your own date format, ordiff` format
Returns
int|null|string Formatted date based on the original date
Gravity Forms code to adjust date to locally-configured Time Zone
See also
GFCommon::format_date() for original code
Definition at line 1057 of file class-common.php.
References $format, and Utils\get().
Referenced by GravityView_Merge_Tags\format_date(), GravityView_Field_Date_Created\get_content(), and GravityView_Field_Workflow_Current_Status_Timestamp\modify_entry_value_workflow_current_status_timestamp().
generate_notice()
static generate_notice ($notice, $class = '', $cap = '', $object_id = null) static
Display updated/error notice.
Since
1.19.2 Added $cap and $object_id parameters
Parameters
string $notice text/HTML of notice
string $class CSS class for notice (updated or error)
string $cap [Optional] Define a capability required to show a notice. If not set, displays to all caps.
Returns
string
Definition at line 1828 of file class-common.php.
References $class, and has_cap().
Referenced by GravityView_frontend\context_not_configured_warning(), GravityView_Edit_Entry_Render\maybe_print_message(), GravityView_Edit_Entry_Render\user_can_edit_entry(), and GravityView_Edit_Entry_Render\user_can_edit_field().
get_all_views()
static get_all_views ($args = array()) static
Get all existing Views.
Since
1.5.4 Added $args array
Parameters
array $args Pass custom array of args, formatted as if for get_posts()
Returns
WP_Post[] Array of Views as WP_Post. Empty array if none found.
Runs Filter:
gravityview/get_all_views/params Modify the parameters sent to get all views.
Parameters
[in,out] array $params Array of parameters to pass to get_posts()
Definition at line 95 of file class-common.php.
Referenced by GravityView_Search_WP_Widget\form(), and Views_Route\get_items().
get_connected_views()
static get_connected_views ($form_id, $args = array()) static
Get the views for a particular form.
Since
1.15.2 Add $args array and limit posts_per_page to 500
get_posts()
Parameters
int $form_id Gravity Forms form ID
array $args Pass args sent to get_posts()
Returns
array Array with view details, as returned by get_posts()
Definition at line 1238 of file class-common.php.
References $form_id.
Referenced by gravityview_get_connected_views().
get_directory_fields()
static get_directory_fields ($post_id, $apply_filter = true) static
Get the field configuration for the View.
array(
[other zones]
'directory_list-title' => array(
[other fields]
'5372653f25d44' => array(
    'id' => string '9' (length=1)
    'label' => string 'Screenshots' (length=11)
    'show_label' => string '1' (length=1)
    'custom_label' => string '' (length=0)
    'custom_class' => string 'gv-gallery' (length=10)
        'only_loggedin' => string '0' (length=1)
    'only_loggedin_cap' => string 'read' (length=4)
)
    [other fields]
)
[other zones])
Since
1.17.4 Added $apply_filter parameter
Parameters
int $post_id View ID
bool $apply_filter Whether to apply the gravityview/configuration/fields filter [Default: true]
Returns
array Multi-array of fields with first level being the field zones. See code comment.
Runs Filter:
gravityview/configuration/fields Filter the View fields' configuration array
Since
1.6.5
Parameters
$fields array Multi-array of fields with first level being the field zones
$post_id int Post ID
Runs Filter:
gravityview/view/configuration/fields Filter the View fields' configuration array.
Since
2.0
Parameters
array $fields Multi-array of fields with first level being the field zones.
\GV\View $view The View the fields are being pulled for.
Definition at line 1380 of file class-common.php.
Referenced by gravityview_get_directory_fields().
get_directory_widgets()
static get_directory_widgets ($view_id, $json_decode = false) static
Get the widget configuration for a View.
Parameters
int $view_id View ID
bool $json_decode Whether to JSON-decode the widget values. Default: false
Returns
array Multi-array of widgets, with the slug of each widget "zone" being the key ("header_top"), and each widget having their own "id"
Definition at line 1414 of file class-common.php.
References $view_id, and gv_map_deep().
get_entries()
static get_entries ($form_ids = null, $passed_criteria = null, & $total = null) static
Retrieve entries given search, sort, paging criteria.
See also
GFAPI::get_entries()
GFFormsModel::get_field_filters_where() public
Parameters
int | array $form_ids The ID of the form or an array IDs of the Forms. Zero for all forms.
mixed $passed_criteria (default: null)
mixed &$total Optional. An output parameter containing the total number of entries. Pass a non-null value to generate the total count. (default: null)
Returns
mixed False: Error fetching entries. Array: Multi-dimensional array of Gravity Forms entry arrays
Reduce # of database calls
Runs Filter:
gravityview_pre_get_entries Define entries to be used before GFAPI::get_entries() is called
Since
1.14
Parameters
null $return If you want to override GFAPI::get_entries() and define entries yourself, tap in here.
array $criteria The final search criteria used to generate the request to GFAPI::get_entries()
array $passed_criteria The original search criteria passed to GVCommon::get_entries()
int | null $total Optional. An output parameter containing the total number of entries. Pass a non-null value to generate
Since
2.1 The $total parameter can now be overriden by reference.
Remove filter added above
Remove filter added above
Runs Filter:
gravityview_entries Modify the array of entries returned to GravityView after it has been fetched from the cache or from GFAPI::get_entries().
Parameters
array | null $entries Array of entries as returned by the cache or by GFAPI::get_entries()
array $criteria The final search criteria used to generate the request to GFAPI::get_entries()
array $passed_criteria The original search criteria passed to GVCommon::get_entries()
int | null $total Optional. An output parameter containing the total number of entries. Pass a non-null value to generate
Since
2.1 The $total parameter can now be overriden by reference.
Definition at line 529 of file class-common.php.
References $criteria, $entries, gravityview(), and GravityView_Cache.
Referenced by GravityView_Recent_Entries_Widget\get_entries(), and gravityview_get_entries().
get_entry()
static get_entry ($entry_slug, $force_allow_ids = false, $check_entry_display = true) static
Return a single entry object.
Since 1.4, supports custom entry slugs. The way that GravityView fetches an entry based on the custom slug is by searching gravityview_unique_id meta. The $entry_slug is fetched by getting the current query var set by is_single_entry()
public
Parameters
string | int $entry_slug Either entry ID or entry slug string
boolean $force_allow_ids Force the get_entry() method to allow passed entry IDs, even if the gravityview_custom_entry_slug_allow_id filter returns false.
boolean $check_entry_display Check whether the entry is visible for the current View configuration. Default: true. {
Since
1.14}
Returns
array|boolean
Runs Filter:
gravityview/common/get_entry/check_entry_display Override whether to check entry display rules against filters
Since
1.16.2
Parameters
bool $check_entry_display Check whether the entry is visible for the current View configuration. Default: true.
array $entry Gravity Forms entry array
Definition at line 673 of file class-common.php.
References $entry, $entry_slug, and gravityview().
Referenced by GravityView_API\entry_link(), GravityView_Entry_Link_Shortcode\get_entry(), gravityview_get_entry(), and GravityView_frontend\setEntry().
get_entry_id()
static get_entry_id ($entry_id_or_slug = '', $force_allow_ids = false) static
Get the entry ID from a string that may be the Entry ID or the Entry Slug.
Since
1.18
Parameters
string $entry_id_or_slug The ID or slug of an entry.
bool $force_allow_ids Whether to force allowing getting the ID of an entry, even if custom slugs are enabled
Returns
false|int|null Returns the ID of the entry found, if custom slugs is enabled. Returns original value if custom slugs is disabled. Returns false if not allowed to convert slug to ID. Returns NULL if entry not found for the passed slug.
Runs Filter:
gravityview_custom_entry_slug Whether to enable and use custom entry slugs.
Parameters
boolean True: Allow for slugs based on entry values. False: always use entry IDs (default)
Runs Filter:
gravityview_custom_entry_slug_allow_id When using a custom slug, allow access to the entry using the original slug (the Entry ID).
If disabled (default), only allow access to an entry using the custom slug value. (example: /entry/custom-slug/ NOT /entry/123/)
If enabled, you could access using the custom slug OR the entry id (example: /entry/custom-slug/ OR /entry/123/)
Parameters
boolean $custom_slug_id_access True: allow accessing the slug by ID; False: only use the slug passed to the method.
If we're using custom entry slugs, we do a meta value search instead of doing a straightup ID search.
Definition at line 625 of file class-common.php.
Referenced by GravityView_Entry_Approval\ajax_update_approved(), and GravityView_Entry_Approval\get_entry_status().
get_entry_id_from_slug()
static get_entry_id_from_slug ($slug) static
Get the entry ID from the entry slug, which may or may not be the entry ID.
Since
1.5.2
Parameters
string $slug The entry slug, as returned by GravityView_API::get_entry_slug()
Returns
int|null The entry ID, if exists; NULL if not
Runs Filter:
gravityview/common/get_entry_id_from_slug/form_id The form ID used to get the custom entry ID. Change this to avoid collisions with data from other forms with the same values and the same field ID.
Since
1.17.2
Parameters
int $form_id ID of the form to search. Default: 0 (searches all forms)
Definition at line 215 of file class-common.php.
References $form_id.
get_entry_ids()
static get_entry_ids ($form_id, $search_criteria = array()) static
Wrapper for the Gravity Forms GFFormsModel::search_lead_ids() method.
See also
GFEntryList::leads_page()
Parameters
int $form_id ID of the Gravity Forms form
Since
1.1.6
Returns
array|void Array of entry IDs. Void if Gravity Forms isn't active.
Definition at line 412 of file class-common.php.
References $form_id.
Referenced by gravityview_get_entry_ids().
get_entry_meta()
static get_entry_meta ($form_id, $only_default_column = true) static
get extra fields from entry meta
Parameters
string $form_id (default: '')
Returns
array
Definition at line 388 of file class-common.php.
References $field, and $form_id.
Referenced by gravityview_get_entry_meta().
get_field()
static get_field ($form, $field_id) static
Returns the field details array of a specific form given the field id.
Alias of GFFormsModel::get_field
Since
1.19 Allow passing form ID as well as form array
GFFormsModel::get_field
See also
GFFormsModel::get_field public
Parameters
array | int $form Form array or ID
string | int $field_id
Returns
GF_Field|null Gravity Forms field object, or NULL: Gravity Forms GFFormsModel does not exist or field at $field_id doesn't exist.
Definition at line 1149 of file class-common.php.
References $field_id, and GV\$form.
Referenced by gravityview_get_field().
get_field_array()
static get_field_array ($field) static
Return a Gravity Forms field array, whether using GF 1.9 or not.
Since
1.7
Parameters
array | GF_Fields $field Gravity Forms field or array
Returns
array Array version of $field
Definition at line 70 of file class-common.php.
References $field.
get_field_label()
static get_field_label ($form = array(), $field_id = '', $field_value = '') static
Retrieve the label of a given field id (for a specific form)
public
Since
1.17 Added $field_value parameter
Parameters
array $form Gravity Forms form array
string $field_id ID of the field. If an input, full input ID (like 1.3)
string | array $field_value Raw value of the field.
Returns
string
Definition at line 1117 of file class-common.php.
References $field, $field_id, $field_value, GV\$form, $label, and Utils\get().
Referenced by gravityview_get_field_label().
get_field_type()
static get_field_type ($form = null, $field_id = '') static
Returns the GF Form field type for a certain field(id) of a form.
Parameters
object $form Gravity Forms form
mixed $field_id Field ID or Field array
Returns
string field type
Definition at line 1536 of file class-common.php.
References $field, $field_id, and GV\$form.
Referenced by gravityview_get_field_type().
get_form()
static get_form ($form_id) static
Returns the form object for a given Form ID.
public
Parameters
mixed $form_id
Returns
array|false Array: Form object returned from Gravity Forms; False: no form ID specified or Gravity Forms isn't active.
Definition at line 28 of file class-common.php.
References $form_id.
Referenced by GravityView_Field\_filter_gform_custom_merge_tags(), gravityview_get_form(), GravityView_Entry_Approval\update_approved_meta(), and GravityView_Search_WP_Widget\widget().
get_form_fields()
static get_form_fields ($form = '', $add_default_properties = false, $include_parent_field = true) static
Return array of fields' id and label, for a given Form ID.
public
Parameters
string | array $form_id (default: '') or $form object
bool $add_default_properties
bool $include_parent_field
Returns
array
In case of email/email confirmation, the input for email has the same id as the parent field
Since
1.7
Runs Filter:
gravityview/common/get_form_fields Modify the form fields shown in the Add Field field picker.
Since
1.17
Parameters
array $fields Associative array of fields, with keys as field type, values an array with the following keys: (string) label (required), (string) type (required), desc, (string) customLabel, (GF_Field) parent, (string) adminLabel, (bool)adminOnly
array $form GF Form array
bool $include_parent_field Whether to include the parent field when getting a field with inputs
Definition at line 283 of file class-common.php.
References $field, GV\$form, GV\get(), and GravityView_Fields\get_all().
Referenced by gravityview_get_form_fields().
get_form_from_entry_id()
static get_form_from_entry_id ($entry_slug) static
Get the form array for an entry based only on the entry ID.
Parameters
int | string $entry_slug Entry slug
Returns
array|false Array: Form object returned from Gravity Forms; False: form doesn't exist, or $entry didn't exist or $entry didn't specify form ID
Definition at line 122 of file class-common.php.
References $entry, $entry_slug, and GV\$form.
Referenced by gravityview_get_form_from_entry_id().
get_forms()
static get_forms ($active = true, $trash = false) static
Alias of GFAPI::get_forms()
See also
GFAPI::get_forms()
Since
1.19 Allow "any" $active status option
Parameters
bool | string $active Status of forms. Use any to get array of forms with any status. Default: true
bool $trash Include forms in trash? Default: false
Returns
array Empty array if GFAPI class isn't available or no forms. Otherwise, the array of Forms
Definition at line 260 of file class-common.php.
References $forms.
Referenced by gravityview_get_forms().
get_link_html()
static get_link_html ($href = '', $anchor_text = '', $atts = array()) static
Generate an HTML anchor tag with a list of supported attributes.
See also
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a Supported attributes defined here esc_url_raw() to sanitize $href esc_attr() to sanitize $atts
Since
1.6
Parameters
string $href URL of the link. Sanitized using esc_url_raw()
string $anchor_text The text or HTML inside the anchor. This is not sanitized in the function.
array | string $atts Attributes to be added to the anchor tag. Parsed by wp_parse_args(), sanitized using esc_attr()
Returns
string HTML output of anchor link. If empty $href, returns NULL
Runs Filter:
gravityview/get_link/allowed_atts Modify the attributes that are allowed to be used in generating links
Parameters
array $allowed_atts Array of attributes allowed
Fix potential security issue with target=_blank
See also
https://dev.to/ben/the-targetblank-vulnerability-by-example
Definition at line 1680 of file class-common.php.
References $href, $output, $value, and GV\get().
Referenced by gravityview_get_link().
get_meta_form_id()
static get_meta_form_id ($view_id) static
Get the Gravity Forms form ID connected to a View.
Parameters
int $view_id The ID of the View to get the connected form of
Returns
false|string ID of the connected Form, if exists. Empty string if not. False if not the View ID isn't valid.
Definition at line 1288 of file class-common.php.
References $view_id.
Referenced by gravityview_get_form_id(), and GravityView_Search_WP_Widget\widget().
get_meta_template_id()
static get_meta_template_id ($view_id) static
Get the template ID (list, table, datatables, map) for a View.
See also
GravityView_Template::template_id
Parameters
int $view_id The ID of the View to get the layout of
Returns
string GravityView_Template::template_id value. Empty string if not.
Definition at line 1301 of file class-common.php.
References $view_id.
Referenced by gravityview_get_template_id().
get_product_field_types()
static get_product_field_types () static
Return array of product field types.
Modify the value using the gform_product_field_types filter
Since
1.20
Returns
array
Definition at line 163 of file class-common.php.
Referenced by GravityView_Field_Product\edit_entry_field_blacklist().
get_sortable_fields()
static get_sortable_fields ($formid, $current = '') static
Render dropdown (select) with the list of sortable fields from a form ID.
public
Parameters
int $formid Form ID
Returns
string html
Definition at line 1443 of file class-common.php.
References $field, and $output.
Referenced by gravityview_get_sortable_fields().
get_sortable_fields_array()
static get_sortable_fields_array ($formid, $blacklist = array('list', 'textarea')) static
Parameters
int $formid Gravity Forms form ID
array $blacklist Field types to exclude
Since
1.8
Returns
array
Merge date and time subfields.
Runs Filter:
gravityview/common/sortable_fields Filter the sortable fields
Since
1.12
Parameters
array $fields Sub-set of GF form fields that are sortable
int $formid The Gravity Forms form ID that the fields are from
Definition at line 1479 of file class-common.php.
References $field, and GV\get().
Referenced by GravityView_HTML_Elements\field_dropdown().
get_template_setting()
static get_template_setting ($post_id, $key) static
Get the setting for a View.
If the setting isn't set by the View, it returns the plugin default.
Parameters
int $post_id View ID
string $key Key for the setting
Returns
mixed|null Setting value, or NULL if not set.
Definition at line 1336 of file class-common.php.
Referenced by GravityView_Edit_Entry\check_user_cap_edit_entry(), and gravityview_get_template_setting().
get_template_settings()
static get_template_settings ($post_id) static
Get all the settings for a View.
defaults() Parses the settings with the plugin defaults as backups.
Parameters
int $post_id View ID
Returns
array Associative array of settings with plugin defaults used if not set by the View
Definition at line 1313 of file class-common.php.
References GV\defaults().
Referenced by gventry\callback(), and gravityview_get_template_settings().
get_users()
static get_users ($context = 'change_entry_creator', $args = array()) static
Get WordPress users with reasonable limits set.
Parameters
string $context Where are we using this information (e.g. change_entry_creator, search_widget ..)
array $args Arguments to modify the user query. See get_users() {
Since
1.14}
Returns
array Array of WP_User objects.
Runs Filter:
gravityview/get_users/{$context} There are issues with too many users using get_users() where it breaks the select. We try to keep it at a reasonable number.
$context is where are we using this information (e.g. change_entry_creator, search_widget ..)
Parameters
array $settings Settings array, with number key defining the # of users to display
Definition at line 1794 of file class-common.php.
Referenced by GravityView_Change_Entry_Creator\add_select(), and GravityView_Widget_Search\get_created_by_choices().
gv_parse_str()
static gv_parse_str ($string, & $result) static
Do the same than parse_str without max_input_vars limitation: Parses $string as if it were the query string passed via a URL and sets variables in the current scope.
Parameters
$string string string to parse (not altered like in the original parse_str(), use the second parameter!)
$result array If the second parameter is present, variables are stored in this variable as array elements
Returns
bool true or false if $string is an empty string
Since
1.5.3
Author
rubo77 at https://gist.github.com/rubo77/6821632
Definition at line 1640 of file class-common.php.
Referenced by _gravityview_process_posted_fields().
has_cap()
static has_cap ($caps = '', $object_id = null, $user_id = null) static
Alias of GravityView_Roles_Capabilities::has_cap()
Since
1.15
See also
GravityView_Roles_Capabilities::has_cap()
Parameters
string | array $caps Single capability or array of capabilities
int $object_id (optional) Parameter can be used to check for capabilities against a specific object, such as a post or user
int | null $user_id (optional) Check the capabilities for a user who is not necessarily the currently logged-in user
Returns
bool True: user has at least one passed capability; False: user does not have any defined capabilities
Definition at line 58 of file class-common.php.
References GravityView_Roles_Capabilities\has_cap().
Referenced by GravityView_Support_Port\_localize_script(), GravityView_Compatibility\_shortcode_gf_notice(), GravityView_Admin_ApproveEntries\add_entry_approved_hidden_input(), GravityView_Admin_Bar\add_floaty_icon(), GravityView_Admin_Bar\add_hooks(), GravityView_Admin_Views\add_post_type_columns(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GravityView_Admin_Add_Shortcode\add_shortcode_button(), GravityView_Admin_Notices\admin_notice(), GravityView_Entry_Approval\ajax_update_approved(), GV\app_settings_fields(), View\as_data(), GravityView_Entry_Approval\autounapprove(), gventry\callback(), gvfield\callback(), gravityview\callback(), View\can_render(), GravityView_Delete_Entry\check_user_cap_delete_entry(), GravityView_Duplicate_Entry\check_user_cap_duplicate_entry(), GravityView_Edit_Entry\check_user_cap_edit_entry(), GravityView_Edit_Entry_Render\check_user_cap_edit_field(), View\content(), GravityView_Admin_Duplicate_View\current_user_can_copy(), GravityView_Field_Notes\display_note(), GravityView_Edit_Entry_Render\filter_admin_only_fields(), generate_notice(), GravityView_Field_Notes\get_add_note_part(), GravityView_Admin_Views\get_connected_form_links(), GravityView_Field_Notes\get_note_email_fields(), Views_Route\get_sub_item_permissions_check(), GravityView_Admin_Views\gform_toolbar_menu(), GravityView_frontend\is_entry_approved(), Field\is_visible(), License_Handler\license_call(), GravityView_Change_Entry_Creator\load(), GravityView_Field_Notes\maybe_add_note(), GravityView_Field_Notes\maybe_delete_notes(), GravityView_Field_Entry_Approval\maybe_not_visible(), GravityView_Field_Entry_Approval\maybe_prevent_field_render(), GV\maybe_save_app_settings(), GravityView_Field_Notes\maybe_send_entry_notes(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), GravityView_Field_Unsubscribe\modify_entry_value_unsubscribe(), GravityView_Admin\no_views_text(), GravityView_Admin\plugin_action_links(), Views_Route\prepare_view_for_response(), GravityView_Field_Notes\process_add_note(), GravityView_Field_Notes\process_delete_notes(), GravityView_frontend\process_search_only_approved(), oEmbed\render_frontend(), GravityView_frontend\render_view(), GravityView_Admin_Views\save_postdata(), License_Handler\settings_edd_license_activation(), GravityView_Admin_ApproveEntries\show_approve_entry_column(), GravityView_Support_Port\show_for_user(), GravityView_Entry_Approval\update_bulk(), GravityView_Cache\use_cache(), and GravityView_Support_Port\user_field().
has_gravityview_shortcode()
static has_gravityview_shortcode ($post = null) static
Check whether the post is GravityView.
Check post type. Is it gravityview?
Check shortcode
Parameters
WP_Post $post WordPress post object
Returns
boolean True: yep, GravityView; No: not!
Definition at line 1172 of file class-common.php.
References $post.
Referenced by has_gravityview_shortcode().
has_product_field()
static has_product_field ($form = array()) static
Check whether a form has product fields.
Since
1.16
1.20 Refactored the field types to get_product_field_types() method
Parameters
array $form Gravity Forms form array
Returns
bool|GF_Field[]
Definition at line 145 of file class-common.php.
References GV\$form.
Referenced by GravityView_Field_Product\clear_product_info_cache().
has_shortcode_r()
static has_shortcode_r ($content, $tag = 'gravityview') static
Placeholder until the recursive has_shortcode() patch is merged.
See also
https://core.trac.wordpress.org/ticket/26343#comment:10
Parameters
string $content Content to check whether there's a shortcode
string $tag Current shortcode tag
Definition at line 1192 of file class-common.php.
References $content.
Referenced by gravityview_has_shortcode_r().
is_field_numeric()
static is_field_numeric ($form = null, $field = '') static
Checks if the field type is a 'numeric' field type (e.g.
to be used when sorting)
Parameters
int | array $form form ID or form array
int | array $field field key or field array
Returns
boolean
Runs Filter:
gravityview/common/numeric_types What types of fields are numeric?
Since
1.5.2
Parameters
array $numeric_types Fields that are numeric. Default: [ number, time ]
Definition at line 1555 of file class-common.php.
References $field, GV\$form, $gv_field, and GravityView_Fields\get().
Referenced by View\as_data(), and GravityView_frontend\get_search_criteria_paging().
js_encrypt()
static js_encrypt ($content, $message = '') static
Encrypt content using Javascript so that it's hidden when JS is disabled.
This is mostly used to hide email addresses from scraper bots.
Parameters
string $content Content to encrypt
string $message Message shown if Javascript is disabled
See also
https://github.com/katzwebservices/standalone-phpenkoder StandalonePHPEnkoder on Github
Since
1.7
Returns
string Content, encrypted
Runs Filter:
gravityview/phpenkoder/msg Modify the message shown when Javascript is disabled and an encrypted email field is displayed
Since
1.7
Parameters
string $message Existing message
string $content Content to encrypt
Definition at line 1601 of file class-common.php.
References $content, $output, and GRAVITYVIEW_DIR.
matches_operation()
static matches_operation ($val1, $val2, $operation) static
Wrapper for the GFFormsModel::matches_operation() method that adds additional comparisons, including: 'equals', 'greater_than_or_is', 'greater_than_or_equals', 'less_than_or_is', 'less_than_or_equals', 'not_contains', 'in', and 'not_in'.
Since
1.13 You can define context, which displays/hides based on what's being displayed (single, multiple, edit)
1.22.1 Added 'in' and 'not_in' for JSON-encoded array values, serialized non-strings
See also
https://docs.gravityview.co/article/252-gvlogic-shortcode GFFormsModel::matches_operation
Since
1.7.5
Parameters
mixed $val1 Left side of comparison
mixed $val2 Right side of comparison
string $operation Type of comparison
Returns
bool True: matches, false: not matches
Since
1.22.1 Handle JSON-encoded comparisons
Definition at line 727 of file class-common.php.
References $criteria, $entries, $entry, $field, $field_value, GV\$form, $value, GV\get(), gravityview(), gravityview_get_context(), gravityview_get_form_id(), and GravityView_GFFormsModel\is_value_match().
Referenced by gvlogic\callback(), and GravityView_GFFormsModel\is_value_match().
send_email()
static send_email ($from, $to, $bcc, $reply_to, $subject, $message, $from_name = '', $message_format = 'html', $attachments = '', $entry = false, $notification = false) static
Send email using GFCommon::send_email()
Since
1.17
See also
GFCommon::send_email This just makes the method public
Parameters
string $from Sender address (required)
string $to Recipient address (required)
string $bcc BCC recipients (required)
string $reply_to Reply-to address (required)
string $subject Subject line (required)
string $message Message body (required)
string $from_name Displayed name of the sender
string $message_format If "html", sent text as text/html. Otherwise, text/plain. Default: "html".
string | array $attachments Optional. Files to attach. {
See also
wp_mail()} for usage. Default: "".
Parameters
array | false $entry Gravity Forms entry array, related to the email. Default: false.
array | false $notification Gravity Forms notification that triggered the email. {
See also
GFCommon::send_notification}. Default:false.
Definition at line 1872 of file class-common.php.
References $entry.
Referenced by GravityView_Field_Notes\maybe_send_entry_notes().
The documentation for this class was generated from the following file:
class-common.php