GravityView: GravityView_Recent_Entries_Widget Class Reference
GravityView_Recent_Entries_Widget Class Reference
Class GravityView_Recent_Entries_Widget.
Public Member Functions
__construct ()
admin_enqueue_scripts ()
Enable the merge tags functionality.
ajax_get_view_merge_tag_data ()
When the widget View is changed, update the Merge Tag data.
form ($instance)
update ($new_instance, $old_instance)
widget ($args, $instance)
Private Member Functions
get_entries ($instance, $form_id)
Get the entries that will be shown in the current widget.
initialize ()
Detailed Description
Class GravityView_Recent_Entries_Widget.
Since
1.6
Definition at line 10 of file class-gravityview-recent-entries-widget.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 13 of file class-gravityview-recent-entries-widget.php.
References $name, and initialize().
Member Function Documentation
admin_enqueue_scripts()
admin_enqueue_scripts ()
Enable the merge tags functionality.
Since
1.6
Definition at line 68 of file class-gravityview-recent-entries-widget.php.
References GRAVITYVIEW_FILE, and GravityView_Plugin\version.
ajax_get_view_merge_tag_data()
ajax_get_view_merge_tag_data ()
When the widget View is changed, update the Merge Tag data.
Since
1.6
Definition at line 39 of file class-gravityview-recent-entries-widget.php.
References GV\$form, $form_id, $output, and gravityview_get_form_id().
form()
form ($instance)
Since
1.6
See also
WP_Widget::form()
Display errors generated for invalid embed IDs
See also
GravityView_View_Data::is_valid_embed_id
Display errors generated for invalid embed IDs
See also
GravityView_View_Data::is_valid_embed_id
Runs Actions:
gravityview_recent_entries_widget_form Displayed at the bottom of the Recent Entries widget admin form
Parameters
GravityView_Recent_Entries_Widget $this WP_Widget object
array $instance Current widget instance
Definition at line 242 of file class-gravityview-recent-entries-widget.php.
References $title, and GravityView_Admin\no_views_text().
get_entries()
get_entries ($instance, $form_id) private
Get the entries that will be shown in the current widget.
Parameters
array $instance Settings for the current widget
string $form_id Form ID int, as string
Returns
array|GV[] $entries Multidimensional array of Gravity Forms entries or GravityView Entry objects
Definition at line 181 of file class-gravityview-recent-entries-widget.php.
References $entries, and View\by_id().
Referenced by widget().
initialize()
initialize () private
Definition at line 26 of file class-gravityview-recent-entries-widget.php.
Referenced by __construct().
update()
update ($new_instance, $old_instance)
Since
1.6
See also
WP_Widget::update()
Parameters
array $new_instance Widget form settings after update
array $old_instance Widget form settings before update
Returns
array Calculated widget settings after processing
Modify the updated instance. This will allow for validating any added instance settings externally.
Parameters
array $instance Calculated widget settings after processing
array $new_instance Widget form settings after update
array $old_instance Widget form settings before update
Definition at line 203 of file class-gravityview-recent-entries-widget.php.
References GravityView_View_Data\is_valid_embed_id().
widget()
widget ($args, $instance)
Since
1.6
See also
WP_Widget::widget()
Parameters
array $args Display arguments including before_title, after_title, before_widget, and after_widget.
array $instance The settings for the particular instance of the widget.
Runs Actions:
gravityview/widget/recent-entries/before_widget Before recent entries are displayed in the WordPress widget
Parameters
array $args Display arguments including before_title, after_title, before_widget, and after_widget.
array $instance The settings for the particular instance of the widget.
Runs Actions:
gravityview/widget/recent-entries/after_widget After recent entries are displayed in the WordPress widget
Parameters
array $args Display arguments including before_title, after_title, before_widget, and after_widget.
array $instance The settings for the particular instance of the widget.
Definition at line 93 of file class-gravityview-recent-entries-widget.php.
References $entries, GV\$form, $form_id, $output, $title, get_entries(), gravityview_get_form(), and gravityview_get_form_id().
The documentation for this class was generated from the following file:
class-gravityview-recent-entries-widget.php