GravityView: GFLocking Class Reference
GFLocking Class Reference
Public Member Functions
__construct ($object_type, $redirect_url, $edit_url= '', $capabilities=array())
ajax_lock_request ()
ajax_reject_lock_request ()
enqueue_list_scripts ()
enqueue_scripts ()
enqueue_view_page_scripts ()
get_lock_ui ($user_id)
get_string ($string_key)
heartbeat_check_locked_objects ($response, $data, $screen_id)
heartbeat_refresh_lock ($response, $data, $screen_id)
heartbeat_refresh_nonces ($response, $data, $screen_id)
heartbeat_request_lock ($response, $data, $screen_id)
init_ajax ()
init_edit_lock ()
init_list_page ()
init_view_page ()
is_locked ($object_id)
list_row_class ($object_id, $echo=true)
lock_indicator ($echo=true)
lock_info ($object_id, $echo=true)
maybe_lock_object ($is_edit_page)
register_noconflict_scripts ($scripts)
register_noconflict_styles ($styles)
register_scripts ()
Data Fields
const PREFIX_EDIT_LOCK = 'lock_'
const PREFIX_EDIT_LOCK_REQUEST = 'lock_request_'
Protected Member Functions
check_lock ($object_id)
check_lock_request ($object_id)
delete_lock_meta ($object_id)
delete_lock_request_meta ($object_id)
get_lock_meta ($object_id)
get_lock_request_meta ($object_id)
get_object_id ()
Override this method to provide the class with the correct object id.
get_strings ()
has_lock ()
is_edit_page ()
Override this method to check the condition for the edit page.
is_list_page ()
Override this method to check the condition for the list page.
is_page ($page_name)
is_view_page ()
Override this method to check the condition for the view page.
request_lock ($object_id)
set_lock ($object_id)
update_lock_meta ($object_id, $lock_value)
update_lock_request_meta ($object_id, $lock_request_value)
Private Attributes
$_capabilities
$_edit_url
$_object_id
$_object_type
$_redirect_url
Detailed Description
Definition at line 16 of file class-gf-locking.php.
Constructor & Destructor Documentation
__construct ($object_type, $redirect_url, $edit_url = '', $capabilities = array())
Definition at line 26 of file class-gf-locking.php.
References DOING_AJAX, get_object_id(), init_ajax(), init_edit_lock(), init_list_page(), init_view_page(), is_edit_page(), is_list_page(), is_view_page(), maybe_lock_object(), and register_scripts().
Member Function Documentation
ajax_lock_request ()
Definition at line 216 of file class-gf-locking.php.
References request_lock().
ajax_reject_lock_request ()
Definition at line 223 of file class-gf-locking.php.
References delete_lock_request_meta().
check_lock ($object_id) protected
Definition at line 235 of file class-gf-locking.php.
References $user_id, get_current_user_id(), and get_lock_meta().
Referenced by enqueue_scripts(), enqueue_view_page_scripts(), has_lock(), heartbeat_check_locked_objects(), heartbeat_refresh_lock(), heartbeat_request_lock(), lock_info(), maybe_lock_object(), and request_lock().
check_lock_request ($object_id) protected
Definition at line 248 of file class-gf-locking.php.
References $user_id, get_current_user_id(), and get_lock_request_meta().
Referenced by heartbeat_refresh_lock().
delete_lock_meta ($object_id) protected
Definition at line 319 of file class-gf-locking.php.
Referenced by maybe_lock_object().
delete_lock_request_meta ($object_id) protected
Definition at line 313 of file class-gf-locking.php.
Referenced by ajax_reject_lock_request().
enqueue_list_scripts ()
Definition at line 168 of file class-gf-locking.php.
References wp_enqueue_script(), wp_enqueue_style(), and wp_localize_script().
enqueue_scripts ()
Definition at line 140 of file class-gf-locking.php.
References check_lock(), get_lock_ui(), get_object_id(), get_string(), wp_enqueue_script(), wp_enqueue_style(), and wp_localize_script().
enqueue_view_page_scripts ()
Definition at line 181 of file class-gf-locking.php.
References check_lock(), get_object_id(), wp_enqueue_script(), wp_enqueue_style(), and wp_localize_script().
get_lock_meta ($object_id) protected
Definition at line 301 of file class-gf-locking.php.
Referenced by check_lock().
get_lock_request_meta ($object_id) protected
Definition at line 297 of file class-gf-locking.php.
Referenced by check_lock_request(), and heartbeat_request_lock().
get_lock_ui ($user_id)
Definition at line 474 of file class-gf-locking.php.
References $_edit_url, $message, $user, $user_id, __, add_query_arg(), esc_url, and get_string().
Referenced by enqueue_scripts().
get_object_id () protected
Override this method to provide the class with the correct object id.
Returns
bool
Definition at line 87 of file class-gf-locking.php.
References $id, and absint().
Referenced by __construct(), enqueue_scripts(), enqueue_view_page_scripts(), and has_lock().
get_string ($string_key)
Definition at line 524 of file class-gf-locking.php.
References get_strings().
Referenced by enqueue_scripts(), get_lock_ui(), heartbeat_check_locked_objects(), heartbeat_refresh_lock(), and lock_info().
get_strings () protected
Definition at line 197 of file class-gf-locking.php.
References __.
Referenced by get_string().
has_lock () protected
Definition at line 230 of file class-gf-locking.php.
References check_lock(), and get_object_id().
heartbeat_check_locked_objects ($response, $data, $screen_id)
Definition at line 342 of file class-gf-locking.php.
References $_object_type, $user, $user_id, __, check_lock(), and get_string().
heartbeat_refresh_lock ($response, $data, $screen_id)
Definition at line 366 of file class-gf-locking.php.
References $_object_type, $user, $user_id, __, check_lock(), check_lock_request(), get_string(), and set_lock().
heartbeat_refresh_nonces ($response, $data, $screen_id)
Definition at line 446 of file class-gf-locking.php.
heartbeat_request_lock ($response, $data, $screen_id)
Definition at line 415 of file class-gf-locking.php.
References $_object_type, $user, $user_id, check_lock(), get_lock_request_meta(), and set_lock().
init_ajax ()
Definition at line 97 of file class-gf-locking.php.
References add_filter().
Referenced by __construct().
init_edit_lock ()
Definition at line 93 of file class-gf-locking.php.
References add_action().
Referenced by __construct().
init_list_page ()
Definition at line 106 of file class-gf-locking.php.
References add_action().
Referenced by __construct().
init_view_page ()
Definition at line 110 of file class-gf-locking.php.
References add_action().
Referenced by __construct().
is_edit_page () protected
Override this method to check the condition for the edit page.
Returns
bool
Definition at line 60 of file class-gf-locking.php.
Referenced by __construct().
is_list_page () protected
Override this method to check the condition for the list page.
Returns
bool
Definition at line 69 of file class-gf-locking.php.
Referenced by __construct().
is_locked ($object_id)
Definition at line 542 of file class-gf-locking.php.
References $user_id, and get_current_user_id().
Referenced by list_row_class().
is_page ($page_name) protected
Definition at line 588 of file class-gf-locking.php.
References GFForms\get_page().
Referenced by GFFormLocking\is_edit_page(), GFEntryLocking\is_edit_page(), GFPluginSettingsLocking\is_edit_page(), GFFormLocking\is_list_page(), GFEntryLocking\is_list_page(), and GFEntryLocking\is_view_page().
is_view_page () protected
Override this method to check the condition for the view page.
Returns
bool
Definition at line 78 of file class-gf-locking.php.
Referenced by __construct().
list_row_class ($object_id, $echo = true)
Definition at line 532 of file class-gf-locking.php.
References is_locked().
lock_indicator ($echo = true)
Definition at line 554 of file class-gf-locking.php.
lock_info ($object_id, $echo = true)
Definition at line 565 of file class-gf-locking.php.
References $user, $user_id, check_lock(), esc_html, and get_string().
maybe_lock_object ($is_edit_page)
Definition at line 325 of file class-gf-locking.php.
References $user_id, check_lock(), delete_lock_meta(), exit, and set_lock().
Referenced by __construct().
register_noconflict_scripts ($scripts)
Definition at line 128 of file class-gf-locking.php.
register_noconflict_styles ($styles)
Definition at line 134 of file class-gf-locking.php.
References $styles.
register_scripts ()
Definition at line 114 of file class-gf-locking.php.
References $min, add_filter(), wp_register_script(), and wp_register_style().
Referenced by __construct().
request_lock ($object_id) protected
Definition at line 275 of file class-gf-locking.php.
References $user, $user_id, __, check_lock(), get_current_user_id(), set_lock(), and update_lock_request_meta().
Referenced by ajax_lock_request().
set_lock ($object_id) protected
Definition at line 261 of file class-gf-locking.php.
References $user_id, get_current_user_id(), and update_lock_meta().
Referenced by heartbeat_refresh_lock(), heartbeat_request_lock(), maybe_lock_object(), and request_lock().
update_lock_meta ($object_id, $lock_value) protected
Definition at line 305 of file class-gf-locking.php.
Referenced by set_lock().
update_lock_request_meta ($object_id, $lock_request_value) protected
Definition at line 309 of file class-gf-locking.php.
Referenced by request_lock().
Field Documentation
$_capabilities private
Definition at line 21 of file class-gf-locking.php.
$_edit_url private
Definition at line 19 of file class-gf-locking.php.
Referenced by get_lock_ui().
$_object_id private
Definition at line 18 of file class-gf-locking.php.
$_object_type private
Definition at line 17 of file class-gf-locking.php.
Referenced by heartbeat_check_locked_objects(), heartbeat_refresh_lock(), and heartbeat_request_lock().
$_redirect_url private
Definition at line 20 of file class-gf-locking.php.
const PREFIX_EDIT_LOCK = 'lock_'
Definition at line 22 of file class-gf-locking.php.
const PREFIX_EDIT_LOCK_REQUEST = 'lock_request_'
Definition at line 23 of file class-gf-locking.php.
The documentation for this class was generated from the following file:
class-gf-locking.php