GravityView: GravityView_Lightbox Class Reference
GravityView_Lightbox Class Reference
Manage lightbox scripts for GravityView.
Public Member Functions
__construct ()
GravityView_Lightbox_Provider constructor.
set_provider ($provider=null)
Activate the lightbox provider chosen in settings.
Static Public Member Functions
static register ($provider)
Register lightbox providers.
Static Private Attributes
static $active_provider = null
static $providers = array()
Detailed Description
Manage lightbox scripts for GravityView.
TODO: Add a global setting for lightbox providers TODO: Add per-field settings
Definition at line 11 of file class-gravityview-lightbox.php.
Constructor & Destructor Documentation
__construct()
__construct ()
GravityView_Lightbox_Provider constructor.
Definition at line 20 of file class-gravityview-lightbox.php.
References gravityview().
Member Function Documentation
register()
static register ($provider) static
Register lightbox providers.
Parameters
$provider
Definition at line 74 of file class-gravityview-lightbox.php.
Referenced by GravityView_Lightbox_Provider_FancyBox\fileupload_link_atts().
set_provider()
set_provider ($provider = null)
Activate the lightbox provider chosen in settings.
Parameters
string | null $provider GravityView_Lightbox_Provider::$slug of provider
Definition at line 39 of file class-gravityview-lightbox.php.
References gravityview().
Field Documentation
$active_provider
$active_provider = null static private
Definition at line 15 of file class-gravityview-lightbox.php.
$providers
$providers = array() static private
Definition at line 13 of file class-gravityview-lightbox.php.
The documentation for this class was generated from the following file:
class-gravityview-lightbox.php