GravityView: GFAutoUpgrade Class Reference
GFAutoUpgrade Class Reference
Public Member Functions
__construct ($slug, $version, $min_gravityforms_version, $title, $full_path, $path, $url, $is_gravityforms_supported)
check_update ($option)
display_changelog ()
display_updates ()
flush_version_info ()
init ()
premium_update ($premium_update)
premium_update_push ($premium_update)
rg_plugin_row ()
Protected Attributes
$_full_path
$_is_gravityforms_supported
$_min_gravityforms_version
$_path
$_slug
$_title
$_url
$_version
Private Member Functions
get_changelog ()
get_key ()
get_remote_request_params ($offering, $key, $version)
get_version_info ($offering, $use_cache=true)
set_version_info ($plugin_slug, $version_info)
Detailed Description
Definition at line 7 of file class-gf-auto-upgrade.php.
Constructor & Destructor Documentation
__construct ($slug, $version, $min_gravityforms_version, $title, $full_path, $path, $url, $is_gravityforms_supported)
Definition at line 18 of file class-gf-auto-upgrade.php.
References $path, $title, $url, and add_action().
Member Function Documentation
check_update ($option)
Definition at line 122 of file class-gf-auto-upgrade.php.
References $_path, $_slug, $_url, $option, get_key(), get_version_info(), and str_replace.
display_changelog ()
Definition at line 155 of file class-gf-auto-upgrade.php.
References exit, and get_changelog().
display_updates ()
Definition at line 214 of file class-gf-auto-upgrade.php.
References $_path, $message, elseif, esc_attr(), esc_html__(), esc_html_e, esc_url, get_version_info(), self_admin_url(), and wp_nonce_url().
flush_version_info ()
Definition at line 110 of file class-gf-auto-upgrade.php.
References set_version_info().
get_changelog () private
Definition at line 165 of file class-gf-auto-upgrade.php.
References $options, $text, esc_html__(), get_bloginfo(), get_key(), get_option(), get_remote_request_params(), and is_wp_error().
Referenced by display_changelog().
get_key () private
Definition at line 206 of file class-gf-auto-upgrade.php.
Referenced by check_update(), and get_changelog().
get_remote_request_params ($offering, $key, $version) private
Definition at line 200 of file class-gf-auto-upgrade.php.
References $wpdb, and get_bloginfo().
Referenced by get_changelog().
get_version_info ($offering, $use_cache = true) private
Definition at line 190 of file class-gf-auto-upgrade.php.
Referenced by check_update(), display_updates(), premium_update(), premium_update_push(), and rg_plugin_row().
init ()
Definition at line 30 of file class-gf-auto-upgrade.php.
References add_action(), add_filter(), is_admin(), and load_plugin_textdomain().
premium_update ($premium_update)
Definition at line 91 of file class-gf-auto-upgrade.php.
References $_path, $update, ABSPATH, get_plugin_data(), and get_version_info().
premium_update_push ($premium_update)
Definition at line 72 of file class-gf-auto-upgrade.php.
References $_path, $update, ABSPATH, get_plugin_data(), and get_version_info().
rg_plugin_row ()
Definition at line 50 of file class-gf-auto-upgrade.php.
References $_title, $message, $title, GFAddOn\display_plugin_message(), esc_html__(), and get_version_info().
set_version_info ($plugin_slug, $version_info) private
Definition at line 114 of file class-gf-auto-upgrade.php.
References set_site_transient(), and set_transient().
Referenced by flush_version_info().
Field Documentation
$_full_path protected
Definition at line 12 of file class-gf-auto-upgrade.php.
$_is_gravityforms_supported protected
Definition at line 15 of file class-gf-auto-upgrade.php.
$_min_gravityforms_version protected
Definition at line 9 of file class-gf-auto-upgrade.php.
$_path protected
Definition at line 13 of file class-gf-auto-upgrade.php.
Referenced by check_update(), display_updates(), premium_update(), and premium_update_push().
$_slug protected
Definition at line 10 of file class-gf-auto-upgrade.php.
Referenced by check_update().
$_title protected
Definition at line 11 of file class-gf-auto-upgrade.php.
Referenced by rg_plugin_row().
$_url protected
Definition at line 14 of file class-gf-auto-upgrade.php.
Referenced by check_update().
$_version protected
Definition at line 8 of file class-gf-auto-upgrade.php.
The documentation for this class was generated from the following file:
class-gf-auto-upgrade.php