GravityView: View_Renderer Class Reference
View_Renderer Class Reference
If this file is called directly, abort.
Public Member Functions
render (View $view, Request $request=null)
Renders a instance.
Public Member Functions inherited from Renderer
__construct ()
Initialization.
legacy_template_warning ($view, $path)
Warn about legacy template being used.
Additional Inherited Members
Static Public Member Functions inherited from Renderer
static maybe_print_notices ($gravityview=null)
Print unconfigured notices to admins.
Detailed Description
If this file is called directly, abort.
The class.
Houses some preliminary rendering functionality.
Definition at line 14 of file class-gv-renderer-view.php.
Member Function Documentation
render()
render (View $view, Request $request = null)
Renders a instance.
Parameters
\GV\View $view The View instance to render.
\GV\Request $request The request context we're currently in. Default: gravityview()->request
Since
2.0
Returns
string The rendered View.
Runs Filter:
gravityview_template_slug_{$template_id} Modify the template slug about to be loaded in directory views.
Since
1.6
Parameters
deprecated
See also
The gravityview_get_template_id filter
Parameters
string $slug Default: 'table'
string $view The current view context: directory.
Figure out whether to get the entries or not.
Some contexts don't need initial entries, like the DataTables directory type.
Runs Filter:
gravityview_get_view_entries_{$template_slug} Whether to get the entries or not.
Parameters
boolean $get_entries Get entries or not, default: true.
Hide View data until search is performed.
Fetch entries for this View.
Load a legacy override template if exists.
We have to bail and call the legacy renderer. Crap!
Show a warning at the top, if View is editable by the user.
Runs Filter:
gravityview/template/view/class Filter the template class that is about to be used to render the view.
Since
2.0
Parameters
string $class The chosen class - Default: .
\GV\View $view The view about to be rendered.
\GV\Request $request The associated request.
Remove multiple sorting before calling legacy filters. This allows us to fake it till we make it.
Mock the legacy state for the widgets and whatnot
Definition at line 27 of file class-gv-renderer-view.php.
References $class, $entries, $post, $template, View\get_entries(), gravityview(), Legacy_Context\pop(), and Legacy_Context\push().
The documentation for this class was generated from the following file:
class-gv-renderer-view.php