GravityView: View_List_Template Class Reference
View_List_Template Class Reference
If this file is called directly, abort.
Public Member Functions
extract_zone_vars ($zones)
Return an array of variables ready to be extracted.
the_field (\GV\Field $field, \GV\Entry $entry, $extras=null)
Output the field in the list view.
Public Member Functions inherited from View_Template
__construct (View $view, Entry_Collection $entries, Request $request)
Initializer.
__destruct ()
add_id_specific_templates ($templates, $slug, $name)
Enable granular template overrides based on current post, view, form, etc.
render ()
Output some HTML.
Public Member Functions inherited from Template
__construct ()
General template initialization.
__destruct ()
Disallow any cleanup for fear of loss of global data.
pop_template_data ($var_name='data')
Restore the template data from the stack.
push_template_data ($data, $var_name='data')
Push the current template data down the stack and set.
Static Public Member Functions
static body_after ($context)
gravityview_list_body_after and gravityview/template/list/body/after actions.
static body_before ($context)
gravityview_list_body_before and gravityview/template/list/body/before actions.
static entry_after ($entry, $context, $zone='')
gravityview_list_entry_after and gravityview/template/list/entry/after actions.
static entry_before ($entry, $context, $zone='')
gravityview_list_entry_before and gravityview/template/list/entry/before actions.
static entry_class ($class, $entry, $context)
gravityview_entry_class and gravityview/template/list/entry/class filters.
Static Public Member Functions inherited from Template
static split_slug ($slug, $name=null)
Get a directory part and a full slug+name (file) components.
Static Public Attributes
static $slug = 'list'
Static Public Attributes inherited from View_Template
static $slug
Additional Inherited Members
Data Fields inherited from View_Template
$entries
$request
$view
Data Fields inherited from Template
$located_template = ''
Protected Attributes inherited from View_Template
$filter_prefix = 'gravityview/template/views'
$plugin_template_directory = 'templates/views/'
$theme_template_directory = 'gravityview/views/'
Detailed Description
If this file is called directly, abort.
The View List Template class .
Renders a and a via a .
Definition at line 14 of file class-gv-template-view-list.php.
Member Function Documentation
body_after()
static body_after ($context) static
gravityview_list_body_after and gravityview/template/list/body/after actions.
Output inside the tbody of the list.
Parameters
$context The 2.0 context.
Returns
void
Runs Actions:
gravityview/template/list/body/after Output inside the tbody of the list at the end.
Since
2.0
Parameters
\GV\Template_Context $context The template context.
Runs Actions:
gravityview_list_body_after Inside the tbody, after any rows are rendered. Can be used to insert additional rows.
Since
1.0.7
Parameters
\GravityView_View $gravityview_view Current GravityView_View object.
ugh!
Definition at line 185 of file class-gv-template-view-list.php.
References GravityView_View\getInstance().
body_before()
static body_before ($context) static
gravityview_list_body_before and gravityview/template/list/body/before actions.
Output inside the tbody of the list.
Parameters
$context The 2.0 context.
Returns
void
Runs Actions:
gravityview/template/list/body/before Output inside the tbody of the list.
Since
2.0
Parameters
\GV\Template_Context $context The template context.
Runs Actions:
gravityview_list_body_before Inside the tbody, before any rows are rendered. Can be used to insert additional rows.
Since
1.0.7
Parameters
\GravityView_View $gravityview_view Current GravityView_View object.
ugh!
Definition at line 159 of file class-gv-template-view-list.php.
References GravityView_View\getInstance().
entry_after()
static entry_after ($entry, $context, $zone = '') static
gravityview_list_entry_after and gravityview/template/list/entry/after actions.
gravityview_list_entry_title_after and gravityview/template/list/entry/title/after actions. gravityview_list_entry_content_after and gravityview/template/list/entry/content/after actions. gravityview_list_entry_footer_after and gravityview/template/list/entry/footer/after actions.
Output inside the entry of the list.
Parameters
\GV\Entry $entry The entry.
\GV\Template_Context $context The 2.0 context.
string $zone The list zone (footer, image, title, etc.).
Returns
void
Runs Actions:
gravityview/template/list/entry/$zone/after Output inside the entry of the list at the end.
Since
2.0
Parameters
\GV\Template_Context $context The template context.
Runs Actions:
gravityview_list_entry_$zone_after Inside the entry, after any rows are rendered. Can be used to insert additional rows.
Since
1.0.7
Parameters
\GravityView_View $gravityview_view Current GravityView_View object.
ugh!
Definition at line 251 of file class-gv-template-view-list.php.
References $entry, and GravityView_View\getInstance().
entry_before()
static entry_before ($entry, $context, $zone = '') static
gravityview_list_entry_before and gravityview/template/list/entry/before actions.
gravityview_list_entry_title_before and gravityview/template/list/entry/title/before actions. gravityview_list_entry_content_before and gravityview/template/list/entry/content/before actions. gravityview_list_entry_footer_before and gravityview/template/list/entry/footer/before actions.
Output inside the entry of the list.
Parameters
\GV\Entry $entry The entry.
\GV\Template_Context $context The 2.0 context.
string $zone The list zone (footer, image, title, etc.).
Returns
void
Runs Actions:
gravityview/template/list/entry/$zone/before Output inside the entry of the list at the end.
Since
2.0
Parameters
\GV\Template_Context $context The template context.
Runs Actions:
gravityview_list_entry_$zone_before Inside the entry, before any rows are rendered. Can be used to insert additional rows.
Since
1.0.7
Parameters
\GravityView_View $gravityview_view Current GravityView_View object.
ugh!
Definition at line 216 of file class-gv-template-view-list.php.
References $entry, and GravityView_View\getInstance().
entry_class()
static entry_class ($class, $entry, $context) static
gravityview_entry_class and gravityview/template/list/entry/class filters.
Modify of the class of a row.
Parameters
string $class The class.
\GV\Entry $entry The entry.
Runs Filter:
gravityview_entry_class Modify the class applied to the entry row.
Parameters
string $class Existing class.
array $entry Current entry being displayed
\GravityView_View $this Current GravityView_View object
Returns
string The modified class.
Runs Filter:
gravityview/template/list/entry/class Modify the class aplied to the entry row.
Parameters
string $class The existing class.
Definition at line 130 of file class-gv-template-view-list.php.
References $class, $entry, and GravityView_View\getInstance().
extract_zone_vars()
extract_zone_vars ($zones)
Return an array of variables ready to be extracted.
Parameters
string | array $zones The field zones to grab.
Returns
array An array ready to be extract()ed in the form of $zone => has_$zone => int
Definition at line 104 of file class-gv-template-view-list.php.
the_field()
the_field (\GV\Field $field, \GV\Entry $entry, $extras = null)
Output the field in the list view.
Parameters
\GV\Field $field The field to output.
\GV\Entry $entry The entry.
array $extras Extra stuff, like wpautop, etc.
Returns
string
Push legacy entry context.
Runs Filter:
gravityview/template/field/label Override the field label.
Since
2.0
Parameters
string $label The label to override.
\GV\Template_Context $context The context.
Runs Filter:
gravityview/template/table/entry/hide_empty
Parameters
boolean Should the row be hidden if the value is empty? Default: don't hide.
\GV\Template_Context $context The context ;) Love it, cherish it. And don't you dare modify it!
Definition at line 29 of file class-gv-template-view-list.php.
References GV\$form, $label, $value, GV\get(), gravityview_field_output(), and Legacy_Context\load().
Field Documentation
$slug
$slug = 'list' static
Definition at line 18 of file class-gv-template-view-list.php.
The documentation for this class was generated from the following file:
class-gv-template-view-list.php