GravityView: WP_Media_List_Table Class Reference
WP_Media_List_Table Class Reference
Core class used to implement displaying media items in a list table.
Public Member Functions
__construct ($args=array())
Constructor.
ajax_user_can ()
column_author ($post)
Handles the author column output.
column_cb ($post)
Handles the checkbox column output.
column_comments ($post)
Handles the comments column output.
column_date ($post)
Handles the date column output.
column_default ($post, $column_name)
Handles output for the default column.
column_desc ($post)
Handles the description column output.
column_parent ($post)
Handles the parent column output.
column_title ($post)
Handles the title column output.
current_action ()
display_rows ()
WP_Post $post
get_columns ()
has_items ()
no_items ()
public
prepare_items ()
WP_Query $wp_query array $post_mime_types array $avail_post_mime_types string $mode
views ()
Override parent views so we can use the filter bar display.
Public Member Functions inherited from WP_List_Table
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($args=array())
Constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
_js_vars ()
Send required variables to JavaScript land.
ajax_response ()
Handle an incoming ajax request (called from admin-ajax.php)
ajax_user_can ()
Checks the current user's permissions.
current_action ()
Get the current action selected from the bulk actions dropdown.
display ()
Display the table.
display_rows ()
Generate the table rows.
display_rows_or_placeholder ()
Generate the tbody element for the list table.
get_column_count ()
Return number of visible columns.
get_columns ()
Get a list of columns.
get_pagenum ()
Get the current page number.
get_pagination_arg ($key)
Access the pagination args.
get_primary_column ()
Public wrapper for WP_List_Table::get_default_primary_column_name().
has_items ()
Whether the table has items to display or not.
no_items ()
Message to be displayed when there are no items.
prepare_items ()
Prepares the list of items for displaying.
print_column_headers ($with_id=true)
Print column headers, accounting for hidden and sortable columns.
search_box ($text, $input_id)
Display the search box.
single_row ($item)
Generates content for a single row of the table.
views ()
Display the list of views available on this table.
Protected Member Functions
extra_tablenav ($which)
get_bulk_actions ()
get_default_primary_column_name ()
Gets the name of the default primary column.
get_sortable_columns ()
get_views ()
array $post_mime_types array $avail_post_mime_types
handle_row_actions ($post, $column_name, $primary)
Generates and displays row action links.
Protected Member Functions inherited from WP_List_Table
bulk_actions ($which= '')
Display the bulk actions dropdown.
column_cb ($item)
column_default ($item, $column_name)
comments_bubble ($post_id, $pending_comments)
Display a comment count bubble.
display_tablenav ($which)
Generate the table navigation above or below the table.
extra_tablenav ($which)
Extra controls to be displayed between bulk actions and pagination.
get_bulk_actions ()
Get an associative array (option_name => option_title) with the list of bulk actions available on this table.
get_column_info ()
Get a list of all, hidden and sortable columns, with filter applied.
get_default_primary_column_name ()
Gets the name of the default primary column.
get_items_per_page ($option, $default=20)
Get number of items to display on a single page.
get_primary_column_name ()
Gets the name of the primary column.
get_sortable_columns ()
Get a list of sortable columns.
get_table_classes ()
Get a list of CSS classes for the WP_List_Table table tag.
get_views ()
Get an associative array (id => link) with the list of views available on this table.
handle_row_actions ($item, $column_name, $primary)
Generates and display row actions links for the list table.
months_dropdown ($post_type)
Display a monthly dropdown for filtering items.
pagination ($which)
Display the pagination.
row_actions ($actions, $always_visible=false)
Generate row actions div.
set_pagination_args ($args)
An internal method that sets all the necessary pagination arguments.
single_row_columns ($item)
Generates the columns for a single row of the table.
view_switcher ($current_mode)
Display a view switcher.
Protected Attributes
$comment_pending_count = array()
Protected Attributes inherited from WP_List_Table
$_args
$_column_headers
$_pagination_args = array()
$compat_fields = array('_args', '_pagination_args', 'screen', '_actions', '_pagination')
{
$compat_methods
{
$modes = array()
$screen
Private Member Functions
_get_row_actions ($post, $att_title)
Private Attributes
$detached
$is_trash
Additional Inherited Members
Data Fields inherited from WP_List_Table
$items
Detailed Description
Core class used to implement displaying media items in a list table.
Since
3.1.0 private
See also
WP_List_Table
Definition at line 18 of file class-wp-media-list-table.php.
Constructor & Destructor Documentation
__construct ($args = array())
Constructor.
Since
3.1.0 public
See also
WP_List_Table::__construct() for more information on default arguments.
Parameters
array $args An associative array of arguments.
Definition at line 42 of file class-wp-media-list-table.php.
References __, and null.
Member Function Documentation
_get_row_actions ($post, $att_title) private
Parameters
WP_Post $post
string $att_title
Returns
array
Filter the action links for each attachment in the Media list table.
Since
2.8.0
Parameters
array $actions An array of action links for each attachment. Default 'Edit', 'Delete Permanently', 'View'.
WP_Post $post WP_Post object for the current attachment.
bool $detached Whether the list table contains media not attached to any posts. Default true.
Definition at line 631 of file class-wp-media-list-table.php.
References $post, __, _x, current_user_can(), esc_attr(), get_edit_post_link(), get_permalink(), permalink, and wp_nonce_url().
ajax_user_can ()
Returns
bool
Definition at line 60 of file class-wp-media-list-table.php.
References current_user_can().
column_author ($post)
Handles the author column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 409 of file class-wp-media-list-table.php.
References add_query_arg(), esc_url, get_the_author(), and get_the_author_meta().
column_cb ($post)
Handles the checkbox column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 348 of file class-wp-media-list-table.php.
References $post, __, _draft_or_post_title(), current_user_can(), input, label, and name.
column_comments ($post)
Handles the comments column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 513 of file class-wp-media-list-table.php.
References $post, WP_List_Table\comments_bubble(), and get_pending_comments_num().
column_date ($post)
Handles the date column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 436 of file class-wp-media-list-table.php.
References $post, __, get_post_time(), human_time_diff(), and mysql2date().
column_default ($post, $column_name)
Handles output for the default column.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
string $column_name Current column name.
Fires for each custom column in the Media list table.
Custom columns are registered using the {
See also
'manage_media_columns'} filter.
Since
2.5.0
Parameters
string $column_name Name of the custom column.
int $post_id Attachment ID.
Definition at line 536 of file class-wp-media-list-table.php.
References $out, $post, __, add_query_arg(), do_action(), elseif, esc_html, esc_url, get_taxonomy(), get_the_terms(), and sanitize_term_field().
column_desc ($post)
Handles the description column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 424 of file class-wp-media-list-table.php.
References $post, and has_excerpt().
column_parent ($post)
Handles the parent column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 464 of file class-wp-media-list-table.php.
References $post, $title, $user_can_edit, _draft_or_post_title(), _e, add_query_arg(), current_user_can(), endif, get_post(), and get_post_type_object().
column_title ($post)
Handles the title column output.
Since
4.3.0 public
Parameters
WP_Post $post The current WP_Post object.
Definition at line 365 of file class-wp-media-list-table.php.
References $class, $file, $mime, $post, $title, __, _draft_or_post_title(), _e, _media_states(), current_user_can(), endif, get_attached_file(), get_edit_post_link(), wp_basename(), and wp_get_attachment_image().
current_action ()
Returns
string
Definition at line 191 of file class-wp-media-list-table.php.
References current_action().
display_rows ()
WP_Post $post
Definition at line 587 of file class-wp-media-list-table.php.
References $post, add_filter(), endwhile, get_current_user_id(), get_pending_comments_num(), have_posts(), WP_List_Table\single_row_columns(), the_post(), and wp_list_pluck().
extra_tablenav ($which) protected
Parameters
string $which
This action is documented in wp-admin/includes/class-wp-posts-list-table.php
Definition at line 162 of file class-wp-media-list-table.php.
References __, current_user_can(), do_action(), is_singular(), WP_List_Table\months_dropdown(), and submit_button().
Referenced by views().
get_bulk_actions () protected
Returns
array
Definition at line 140 of file class-wp-media-list-table.php.
References __, and _x.
get_columns ()
Returns
array
Filter the taxonomy columns for attachments in the Media list table.
Since
3.5.0
Parameters
array $taxonomies An array of registered taxonomies to show for attachments.
string $post_type The post type. Default 'attachment'.
Filter the Media list table columns.
Since
2.5.0
Parameters
array $posts_columns An array of columns displayed in the Media list table.
bool $detached Whether the list table contains media not attached to any posts. Default true.
Definition at line 274 of file class-wp-media-list-table.php.
References __, _x, apply_filters(), elseif, esc_attr__(), get_taxonomies_for_attachments(), get_taxonomy(), post_type_supports(), and wp_filter_object_list().
get_default_primary_column_name () protected
Gets the name of the default primary column.
Since
4.3.0 protected
Returns
string Name of the default primary column, in this case, 'title'.
Definition at line 621 of file class-wp-media-list-table.php.
get_sortable_columns () protected
Returns
array
Definition at line 330 of file class-wp-media-list-table.php.
get_views () protected
array $post_mime_types array $avail_post_mime_types
Returns
array
Definition at line 92 of file class-wp-media-list-table.php.
References $label, __, _x, esc_attr(), selected(), str_replace, and wp_match_mime_types().
Referenced by views().
handle_row_actions ($post, $column_name, $primary) protected
Generates and displays row action links.
Since
4.3.0 protected
Parameters
object $post Attachment being acted upon.
string $column_name Current column name.
string $primary Primary column name.
Returns
string Row actions output for media attachments.
Definition at line 692 of file class-wp-media-list-table.php.
has_items ()
Returns
bool
Definition at line 208 of file class-wp-media-list-table.php.
References have_posts().
no_items ()
public
Definition at line 215 of file class-wp-media-list-table.php.
References _e.
prepare_items ()
WP_Query $wp_query array $post_mime_types array $avail_post_mime_types string $mode
Definition at line 71 of file class-wp-media-list-table.php.
References $mode, WP_List_Table\set_pagination_args(), and wp_edit_attachments_query().
views ()
Override parent views so we can use the filter bar display.
string $mode
This filter is documented in wp-admin/inclues/class-wp-list-table.php
Definition at line 224 of file class-wp-media-list-table.php.
References $class, $mode, _e, apply_filters(), esc_html_e, extra_tablenav(), get_views(), input, label, name, placeholder, and WP_List_Table\view_switcher().
Field Documentation
$comment_pending_count = array() protected
Definition at line 26 of file class-wp-media-list-table.php.
$detached private
Definition at line 28 of file class-wp-media-list-table.php.
$is_trash private
Definition at line 30 of file class-wp-media-list-table.php.
The documentation for this class was generated from the following file:
class-wp-media-list-table.php