GravityView: WPProfiler Class Reference
WPProfiler Class Reference
Public Member Functions
__construct ()
PHP5 constructor.
_current_action ()
_dirty_objects_count ($dirty_objects)
_query_count ($queries)
_query_summary ($queries, &$out)
array_add ($a, $b)
array_sub ($a, $b)
log_action ($tag)
log_filter ($tag)
microtime ($since=0.0)
print_summary ()
results ()
start ($name)
stop ()
Data Fields
$profile
$stack
Detailed Description
Definition at line 20 of file wp-profiler.php.
Constructor & Destructor Documentation
__construct ()
PHP5 constructor.
Definition at line 27 of file wp-profiler.php.
Member Function Documentation
_current_action ()
Definition at line 131 of file wp-profiler.php.
References $wp_actions.
_dirty_objects_count ($dirty_objects)
Definition at line 164 of file wp-profiler.php.
References $out.
Referenced by stop().
_query_count ($queries)
Definition at line 152 of file wp-profiler.php.
References $out.
_query_summary ($queries, & $out)
Definition at line 140 of file wp-profiler.php.
References $out.
Referenced by stop().
array_add ($a, $b)
Definition at line 171 of file wp-profiler.php.
References $out.
Referenced by stop().
array_sub ($a, $b)
Definition at line 181 of file wp-profiler.php.
References $out.
Referenced by stop().
log_action ($tag)
Definition at line 126 of file wp-profiler.php.
log_filter ($tag)
Definition at line 115 of file wp-profiler.php.
References $wp_actions.
microtime ($since = 0.0)
Definition at line 110 of file wp-profiler.php.
Referenced by start(), and stop().
print_summary ()
Definition at line 189 of file wp-profiler.php.
References $name, and results().
results ()
Definition at line 136 of file wp-profiler.php.
References $profile.
Referenced by print_summary().
start ($name)
Definition at line 32 of file wp-profiler.php.
References $name, $wpdb, add_filter(), and microtime().
stop ()
Definition at line 63 of file wp-profiler.php.
References $name, $wpdb, _dirty_objects_count(), _query_summary(), array_add(), array_sub(), microtime(), and remove_filter().
Field Documentation
$profile
Definition at line 22 of file wp-profiler.php.
Referenced by results().
$stack
Definition at line 21 of file wp-profiler.php.
The documentation for this class was generated from the following file:
wp-profiler.php