GravityView: GravityView_Welcome Class Reference
GravityView_Welcome Class Reference
GravityView_Welcome Class.
Public Member Functions
__construct ()
Get things started.
admin_head ()
Hide Individual Dashboard Pages.
admin_menus ()
Register the Dashboard Pages which are later hidden but these pages are used to render the Welcome pages.
credits_screen ()
Render Credits Screen.
getting_started_screen ()
Render About Screen.
is_dashboard_page ($is_page=false, $hook=NULL)
Is this page a GV dashboard page?
tabs ()
Navigation tabs.
Data Fields
$minimum_capability = 'gravityview_getting_started'
Detailed Description
GravityView_Welcome Class.
A general class for About page.
Since
1.0
Definition at line 23 of file class-admin-welcome.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Get things started.
Since
1.0
Definition at line 35 of file class-admin-welcome.php.
Member Function Documentation
admin_head()
admin_head ()
Hide Individual Dashboard Pages.
public
Since
1.0
Returns
void
Definition at line 104 of file class-admin-welcome.php.
References is_dashboard_page().
admin_menus()
admin_menus ()
Register the Dashboard Pages which are later hidden but these pages are used to render the Welcome pages.
public
Since
1.0
Returns
void
Definition at line 50 of file class-admin-welcome.php.
credits_screen()
credits_screen ()
Render Credits Screen.
public
Since
1.0
Returns
void
Definition at line 670 of file class-admin-welcome.php.
References gravityview(), tabs(), GV\top, and GravityView_Plugin\version.
getting_started_screen()
getting_started_screen ()
Render About Screen.
public
Since
1.0
Returns
void
Definition at line 163 of file class-admin-welcome.php.
References GV\all(), GV\bottom, gravityview(), GV\styles(), tabs(), GV\ul, GravityView_Entry_Approval_Status\UNAPPROVED, and GV\update().
is_dashboard_page()
is_dashboard_page ($is_page = false, $hook = NULL)
Is this page a GV dashboard page?
Returns
boolean $is_page True: yep; false: nope
Definition at line 89 of file class-admin-welcome.php.
Referenced by admin_head().
tabs()
tabs ()
Navigation tabs.
public
Since
1.0
Returns
void
Definition at line 128 of file class-admin-welcome.php.
References gravityview_get_floaty(), and GravityView_Plugin\version.
Referenced by credits_screen(), and getting_started_screen().
Field Documentation
$minimum_capability
$minimum_capability = 'gravityview_getting_started'
Definition at line 28 of file class-admin-welcome.php.
The documentation for this class was generated from the following file:
class-admin-welcome.php