GravityView: Tests_REST_API Class Reference
Tests_REST_API Class Reference
restapi
Public Member Functions
setUp ()
test_init_action_added ()
The rest_api_init hook should have been registered with init, and should have a default priority of 10.
test_options_request ()
test_options_request_not_options ()
Ensure that the OPTIONS handler doesn't kick in for non-OPTIONS requests.
test_rest_api_activated ()
The plugin should be installed and activated.
test_rest_route_query_var ()
The rest_route query variable should be registered.
test_rest_url_generation ()
The get_rest_url function should return a URL consistently terminated with a "/", whether the blog is configured with pretty permalink support or not.
test_rest_url_scheme ()
34299
test_route_canonicalized ()
Check that a single route is canonicalized.
test_route_canonicalized_multiple ()
Check that a single route is canonicalized.
test_route_merge ()
Check that routes are merged by default.
test_route_method ()
test_route_method_array ()
The 'methods' arg should accept a single value as well as array.
test_route_method_comma_seperated ()
The 'methods' arg should a comma seperated string.
test_route_method_string ()
The 'methods' arg should accept a single value as well as array.
test_route_override ()
Check that we can override routes.
test_route_reject_empty_namespace ()
Test that we reject routes without namespaces.
test_route_reject_empty_route ()
Test that we reject empty routes.
Public Member Functions inherited from WP_UnitTestCase
__get ($name)
__isset ($name)
_create_temporary_tables ($query)
_drop_temporary_tables ($query)
_make_attachment ($upload, $parent_post_id=0)
assertDiscardWhitespace ($expected, $actual)
assertEqualFields ($object, $fields)
assertEqualSets ($expected, $actual)
assertEqualSetsWithIndex ($expected, $actual)
assertNotWPError ($actual, $message= '')
assertQueryTrue ()
Check each of the WP_Query is_* functions/properties against expected boolean value.
assertWPError ($actual, $message= '')
clean_up_global_scope ()
delete_folders ($path)
deprecated_function_run ($function)
doing_it_wrong_run ($function)
expectDeprecated ()
expectedDeprecated ()
files_in_dir ($dir)
flush_cache ()
get_wp_die_handler ($handler)
go_to ($url)
knownPluginBug ($ticket_id)
Skips the current test if there is an open plugin ticket with id $ticket_id.
knownUTBug ($ticket_id)
Skips the current test if there is an open unit tests ticket with id $ticket_id.
knownWPBug ($ticket_id)
Skips the current test if there is an open WordPress ticket with id $ticket_id.
prepareTemplate (Text_Template $template)
Define constants after including files.
remove_added_uploads ()
rmdir ($path)
scan_user_uploads ()
scandir ($dir)
set_permalink_structure ($structure= '')
Utility method that resets permalinks and flushes rewrites.
setExpectedDeprecated ($deprecated)
Declare an expected _deprecated_function() or _deprecated_argument() call from within a test.
setExpectedIncorrectUsage ($doing_it_wrong)
Declare an expected _doing_it_wrong() call from within a test.
setUp ()
start_transaction ()
tearDown ()
temp_filename ()
Returns the name of a temporary file.
unlink ($file)
wp_die_handler ($message)
Additional Inherited Members
Static Public Member Functions inherited from WP_UnitTestCase
static commit_transaction ()
Commit the queries in a transaction.
static delete_user ($user_id)
Multisite-agnostic way to delete a user from the database.
static forceTicket ($ticket)
static get_called_class ()
static setUpBeforeClass ()
static tearDownAfterClass ()
Protected Member Functions inherited from WP_UnitTestCase
_backup_hooks ()
Saves the action and filter-related globals so they can be restored later.
_microtime_to_float ($microtime)
Helper to Convert a microtime string into a float.
_restore_hooks ()
Restores the hook-related globals to their state at setUp() so that future tests aren't affected by hooks set during this last test.
assertPostConditions ()
Detect post-test failure conditions.
checkRequirements ()
reset_post_statuses ()
Unregister non-built-in post statuses.
reset_post_types ()
Unregister existing post types and register defaults.
reset_taxonomies ()
Unregister existing taxonomies and register defaults.
Static Protected Member Functions inherited from WP_UnitTestCase
static factory ()
Protected Attributes inherited from WP_UnitTestCase
$caught_deprecated = array()
$caught_doing_it_wrong = array()
$expected_deprecated = array()
$expected_doing_it_wrong = array()
Static Protected Attributes inherited from WP_UnitTestCase
static $forced_tickets = array()
static $hooks_saved = array()
static $ignore_files
Detailed Description
restapi
Definition at line 15 of file api-core/phpunit/tests/rest-api.php.
Member Function Documentation
setUp ()
Definition at line 16 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_init_action_added ()
The rest_api_init hook should have been registered with init, and should have a default priority of 10.
Definition at line 33 of file api-core/phpunit/tests/rest-api.php.
References has_action().
test_options_request ()
Definition at line 240 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS, null, and rest_handle_options_request().
test_options_request_not_options ()
Ensure that the OPTIONS handler doesn't kick in for non-OPTIONS requests.
Definition at line 258 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS, null, and rest_handle_options_request().
test_rest_api_activated ()
The plugin should be installed and activated.
Definition at line 25 of file api-core/phpunit/tests/rest-api.php.
test_rest_route_query_var ()
The rest_route query variable should be registered.
Definition at line 182 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS, and rest_api_init().
test_rest_url_generation ()
The get_rest_url function should return a URL consistently terminated with a "/", whether the blog is configured with pretty permalink support or not.
Definition at line 274 of file api-core/phpunit/tests/rest-api.php.
References get_rest_url(), update_option(), and WP_TESTS_DOMAIN.
test_rest_url_scheme ()
34299
Definition at line 287 of file api-core/phpunit/tests/rest-api.php.
References $_SERVER, $url, get_option(), get_rest_url(), home_url(), is_admin(), set_current_screen(), and update_option().
test_route_canonicalized ()
Check that a single route is canonicalized.
Ensures that single and multiple routes are handled correctly.
Definition at line 42 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_canonicalized_multiple ()
Check that a single route is canonicalized.
Ensures that single and multiple routes are handled correctly.
Definition at line 73 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_merge ()
Check that routes are merged by default.
Definition at line 110 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_method ()
Definition at line 187 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_method_array ()
The 'methods' arg should accept a single value as well as array.
Definition at line 215 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_method_comma_seperated ()
The 'methods' arg should a comma seperated string.
Definition at line 229 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_method_string ()
The 'methods' arg should accept a single value as well as array.
Definition at line 201 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_override ()
Check that we can override routes.
Definition at line 129 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_reject_empty_namespace ()
Test that we reject routes without namespaces.
register_rest_route
Definition at line 156 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
test_route_reject_empty_route ()
Test that we reject empty routes.
register_rest_route
Definition at line 170 of file api-core/phpunit/tests/rest-api.php.
References $GLOBALS.
The documentation for this class was generated from the following file:
api-core/phpunit/tests/rest-api.php