GravityView: Twenty_Fourteen_Ephemera_Widget Class Reference
Twenty_Fourteen_Ephemera_Widget Class Reference
Public Member Functions
__construct ()
Constructor.
form ($instance)
Display the form for this widget on the Widgets page of the Admin area.
update ($new_instance, $instance)
Deal with the settings when they are saved by the admin.
widget ($args, $instance)
Output the HTML for this widget.
Public Member Functions inherited from WP_Widget
__construct ($id_base, $name, $widget_options=array(), $control_options=array())
PHP5 constructor.
_get_display_callback ()
Retrieves the widget display callback.
_get_form_callback ()
Retrieves the form callback.
_get_update_callback ()
Retrieves the widget update callback.
_register ()
Register all widget instances of this widget class.
_register_one ($number=-1)
Register an instance of the widget class.
_set ($number)
Set the internal order number for the widget instance.
display_callback ($args, $widget_args=1)
Generate the actual widget content (Do NOT override).
form ($instance)
Outputs the settings update form.
form_callback ($widget_args=1)
Generate the widget control form (Do NOT override).
get_field_id ($field_name)
Constructs id attributes for use in {.
get_field_name ($field_name)
Constructs name attributes for use in form() fields.
get_settings ()
Get the settings for all instances of the widget class.
is_preview ()
Determine whether the current request is inside the Customizer preview.
save_settings ($settings)
Save the settings for all instances of the widget class.
update ($new_instance, $old_instance)
Updates a particular instance of a widget.
update_callback ($deprecated=1)
Deal with changed settings (Do NOT override).
widget ($args, $instance)
Echoes the widget content.
WP_Widget ($id_base, $name, $widget_options=array(), $control_options=array())
PHP4 constructor.
Private Attributes
$formats = array('aside', 'image', 'video', 'audio', 'quote', 'link', 'gallery')
Additional Inherited Members
Data Fields inherited from WP_Widget
$control_options
$id = false
$id_base
$name
$number = false
$updated = false
$widget_options
Detailed Description
Definition at line 14 of file wp-content/themes/twentyfourteen/inc/widgets.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Since
Twenty Fourteen 1.0
Returns
Twenty_Fourteen_Ephemera_Widget
Definition at line 33 of file wp-content/themes/twentyfourteen/inc/widgets.php.
References __.
Member Function Documentation
form ($instance)
Display the form for this widget on the Widgets page of the Admin area.
Since
Twenty Fourteen 1.0
Parameters
array $instance
Definition at line 250 of file wp-content/themes/twentyfourteen/inc/widgets.php.
References $format, WP_Widget\$number, $title, _e, absint(), endforeach, esc_attr(), esc_html, formats, get_post_format_string(), input, label, name, selected(), and size.
update ($new_instance, $instance)
Deal with the settings when they are saved by the admin.
Here is where any validation should happen.
Since
Twenty Fourteen 1.0
Parameters
array $new_instance New widget instance.
array $instance Original widget instance.
Returns
array Updated widget instance.
Definition at line 233 of file wp-content/themes/twentyfourteen/inc/widgets.php.
References absint(), and formats.
widget ($args, $instance)
Output the HTML for this widget.
public
Since
Twenty Fourteen 1.0
Parameters
array $args An array of standard parameters for widgets in this theme.
array $instance An array of settings for this widget instance.
Definition at line 49 of file wp-content/themes/twentyfourteen/inc/widgets.php.
References $format, $GLOBALS, $image, WP_Widget\$number, $title, __, _n(), absint(), apply_filters(), comments_open(), comments_popup_link(), elseif, endif, endwhile, esc_attr(), esc_html, esc_url, formats, get_author_posts_url(), get_comments_number(), get_option(), get_permalink(), get_post_galleries(), get_posts(), get_the_author(), get_the_author_meta(), get_the_date(), get_the_ID(), get_the_post_thumbnail(), has_post_format(), has_post_thumbnail(), li, number_format_i18n(), post_password_required(), the_content(), the_title(), wp_get_attachment_image(), and wp_reset_postdata().
Field Documentation
$formats = array('aside', 'image', 'video', 'audio', 'quote', 'link', 'gallery') private
Definition at line 24 of file wp-content/themes/twentyfourteen/inc/widgets.php.
The documentation for this class was generated from the following file:
wp-content/themes/twentyfourteen/inc/widgets.php