GravityView: SimplePie_Misc Class Reference
SimplePie_Misc Class Reference
Static Public Member Functions
static absolutize_url ($relative, $base)
static atom_03_construct_type ($attribs)
static atom_10_construct_type ($attribs)
static atom_10_content_construct_type ($attribs)
static change_encoding ($data, $input, $output)
Change a string from one encoding to another.
static codepoint_to_utf8 ($codepoint)
Converts a unicode codepoint to a UTF-8 character.
static compress_parse_url ($scheme= '', $authority= '', $path= '', $query= '', $fragment= '')
static debug (&$sp)
Format debugging information.
static element_implode ($element)
static encoding ($charset)
Normalize an encoding name.
static entities_decode ($data)
Decode HTML entities.
static error ($message, $level, $file, $line)
static fix_protocol ($url, $http=1)
static get_build ()
Get the SimplePie build timestamp.
static get_curl_version ()
static get_element ($realname, $string)
Get a HTML/XML element from a HTML string.
static is_isegment_nz_nc ($string)
static normalize_url ($url)
static output_javascript ()
static parse_date ($dt)
static parse_mime ($mime)
static parse_str ($str)
Similar to parse_str()
static parse_url ($url)
static percent_encoding_normalization ($match)
static silence_errors ($num, $str)
static space_seperated_tokens ($string)
static strip_comments ($data)
Strip HTML comments.
static time_hms ($seconds)
static uncomment_rfc822 ($string)
Remove RFC822 comments.
static windows_1252_to_utf8 ($string)
Converts a Windows-1252 encoded string to a UTF-8 encoded string.
static xml_encoding ($data, $registry)
Detect XML encoding, as per XML 1.0 Appendix F.1.
Static Protected Member Functions
static change_encoding_iconv ($data, $input, $output)
static change_encoding_mbstring ($data, $input, $output)
Detailed Description
Definition at line 50 of file wp-includes/SimplePie/misc.php.
Member Function Documentation
static absolutize_url ($relative, $base) static
Definition at line 80 of file wp-includes/SimplePie/misc.php.
References SimplePie_IRI\absolutize().
Referenced by SimplePie_File\__construct().
static atom_03_construct_type ($attribs) static
Definition at line 1835 of file wp-includes/SimplePie/misc.php.
References $mode, SIMPLEPIE_CONSTRUCT_BASE64, SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_NONE, SIMPLEPIE_CONSTRUCT_TEXT, and SIMPLEPIE_CONSTRUCT_XHTML.
static atom_10_construct_type ($attribs) static
Definition at line 1871 of file wp-includes/SimplePie/misc.php.
References SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_NONE, SIMPLEPIE_CONSTRUCT_TEXT, and SIMPLEPIE_CONSTRUCT_XHTML.
static atom_10_content_construct_type ($attribs) static
Definition at line 1893 of file wp-includes/SimplePie/misc.php.
References SIMPLEPIE_CONSTRUCT_BASE64, SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_NONE, SIMPLEPIE_CONSTRUCT_TEXT, and SIMPLEPIE_CONSTRUCT_XHTML.
static change_encoding ($data, $input, $output) static
Change a string from one encoding to another.
Parameters
string $data Raw data in $input encoding
string $input Encoding of $data
string $output Encoding you want
Returns
string|boolean False if we can't convert it
Definition at line 291 of file wp-includes/SimplePie/misc.php.
References $i, $output, change_encoding_iconv(), change_encoding_mbstring(), elseif, encoding(), and windows_1252_to_utf8().
Referenced by xml_encoding().
static change_encoding_iconv ($data, $input, $output) static protected
Definition at line 370 of file wp-includes/SimplePie/misc.php.
References $output.
Referenced by change_encoding().
static change_encoding_mbstring ($data, $input, $output) static protected
Definition at line 332 of file wp-includes/SimplePie/misc.php.
References $output.
Referenced by change_encoding().
static codepoint_to_utf8 ($codepoint) static
Converts a unicode codepoint to a UTF-8 character.
Parameters
int $codepoint Unicode codepoint
Returns
string UTF-8 character
Definition at line 1955 of file wp-includes/SimplePie/misc.php.
Referenced by SimplePie_Decode_HTML_Entities\entity().
static compress_parse_url ($scheme = '', $authority = '', $path = '', $query = '', $fragment = '') static
Definition at line 239 of file wp-includes/SimplePie/misc.php.
References $path.
Referenced by SimplePie_File\__construct(), SimplePie_Enclosure\__construct(), and fix_protocol().
static debug (& $sp) static
Format debugging information.
Definition at line 2195 of file wp-includes/SimplePie/misc.php.
References null, SIMPLEPIE_BUILD, and SIMPLEPIE_VERSION.
static element_implode ($element) static
Definition at line 135 of file wp-includes/SimplePie/misc.php.
References $value.
static encoding ($charset) static
Normalize an encoding name.
This is automatically generated by create.php
To generate it, run php create.php on the command line, and copy the output to replace this function.
Parameters
string $charset Character set to standardise
Returns
string Standardised name
Definition at line 386 of file wp-includes/SimplePie/misc.php.
References $charset.
Referenced by change_encoding().
static entities_decode ($data) static
Decode HTML entities.
Definition at line 1757 of file wp-includes/SimplePie/misc.php.
Referenced by get_element().
static error ($message, $level, $file, $line) static
Definition at line 154 of file wp-includes/SimplePie/misc.php.
References $message.
static fix_protocol ($url, $http = 1) static
Definition at line 195 of file wp-includes/SimplePie/misc.php.
References $url, compress_parse_url(), elseif, normalize_url(), and parse_url().
static get_build () static
Get the SimplePie build timestamp.
Uses the git index if it exists, otherwise uses the modification time of the newest file.
Definition at line 2163 of file wp-includes/SimplePie/misc.php.
References $file, and elseif.
static get_curl_version () static
Definition at line 1699 of file wp-includes/SimplePie/misc.php.
References elseif.
Referenced by SimplePie_File\__construct().
static get_element ($realname, $string) static
Get a HTML/XML element from a HTML string.
Definition at line 98 of file wp-includes/SimplePie/misc.php.
References $i, $name, entities_decode(), and SIMPLEPIE_PCRE_HTML_ATTRIBUTE.
static is_isegment_nz_nc ($string) static
Definition at line 1924 of file wp-includes/SimplePie/misc.php.
static normalize_url ($url) static
Definition at line 250 of file wp-includes/SimplePie/misc.php.
References $url.
Referenced by fix_protocol().
static output_javascript () static
Definition at line 2124 of file wp-includes/SimplePie/misc.php.
References height, placeholder, and width.
static parse_date ($dt) static
Definition at line 1744 of file wp-includes/SimplePie/misc.php.
References SimplePie_Parse_Date\get().
static parse_mime ($mime) static
Definition at line 1823 of file wp-includes/SimplePie/misc.php.
References $mime.
static parse_str ($str) static
Similar to parse_str()
Returns an associative array of name/value pairs, where the value is an array of values that have used the same name
Parameters
string $str The input string.
Returns
array
Definition at line 1995 of file wp-includes/SimplePie/misc.php.
References $name, $value, and null.
static parse_url ($url) static
Definition at line 227 of file wp-includes/SimplePie/misc.php.
References $url.
Referenced by SimplePie_File\__construct(), SimplePie_Enclosure\__construct(), fix_protocol(), and SimplePie_Enclosure\get_extension().
static percent_encoding_normalization ($match) static
Definition at line 256 of file wp-includes/SimplePie/misc.php.
static silence_errors ($num, $str) static
Definition at line 2242 of file wp-includes/SimplePie/misc.php.
static space_seperated_tokens ($string) static
Definition at line 1929 of file wp-includes/SimplePie/misc.php.
static strip_comments ($data) static
Strip HTML comments.
Parameters
string $data Data to strip comments from
Returns
string Comment stripped string
Definition at line 1726 of file wp-includes/SimplePie/misc.php.
References $output.
static time_hms ($seconds) static
Definition at line 52 of file wp-includes/SimplePie/misc.php.
Referenced by SimplePie_Enclosure\get_duration().
static uncomment_rfc822 ($string) static
Remove RFC822 comments.
Parameters
string $data Data to strip comments from
Returns
string Comment stripped string
Definition at line 1769 of file wp-includes/SimplePie/misc.php.
References $output, and elseif.
static windows_1252_to_utf8 ($string) static
Converts a Windows-1252 encoded string to a UTF-8 encoded string.
Parameters
string $string Windows-1252 encoded string
Returns
string UTF-8 encoded string
Definition at line 276 of file wp-includes/SimplePie/misc.php.
Referenced by change_encoding().
static xml_encoding ($data, $registry) static
Detect XML encoding, as per XML 1.0 Appendix F.1.
Definition at line 2024 of file wp-includes/SimplePie/misc.php.
References change_encoding(), and elseif.
The documentation for this class was generated from the following file:
wp-includes/SimplePie/misc.php