GravityView: POP3 Class Reference
POP3 Class Reference
Public Member Functions
__construct ($server= '', $timeout= '')
PHP5 constructor.
apop ($login, $pass)
connect ($server, $port=110)
delete ($msgNum="")
get ($msgNum)
is_ok ($cmd="")
last ($type="count")
login ($login="", $pass="")
parse_banner ($server_text)
pass ($pass="")
POP3 ($server= '', $timeout= '')
PHP4 constructor.
pop_list ($msgNum="")
popstat ()
quit ()
reset ()
send_cmd ($cmd="")
strip_clf ($text="")
top ($msgNum, $numLines="0")
uidl ($msgNum="")
update_timer ()
user ($user="")
Data Fields
$ALLOWAPOP = FALSE
$BANNER = ''
$BUFFER = 512
$COUNT = -1
$DEBUG = FALSE
$ERROR = ''
$FP = ''
$MAILSERVER = ''
$TIMEOUT = 60
Detailed Description
Definition at line 19 of file class-pop3.php.
Constructor & Destructor Documentation
__construct ($server = '', $timeout = '')
PHP5 constructor.
Definition at line 50 of file class-pop3.php.
Member Function Documentation
apop ($login, $pass)
Definition at line 165 of file class-pop3.php.
References $BANNER, $count, elseif, is_ok(), last(), login(), and send_cmd().
connect ($server, $port = 110)
Definition at line 81 of file class-pop3.php.
References $MAILSERVER, is_ok(), parse_banner(), strip_clf(), and update_timer().
delete ($msgNum = "")
Definition at line 582 of file class-pop3.php.
References is_ok(), and send_cmd().
get ($msgNum)
Definition at line 350 of file class-pop3.php.
References $BUFFER, $count, $FP, is_ok(), send_cmd(), and update_timer().
is_ok ($cmd = "")
Definition at line 609 of file class-pop3.php.
Referenced by apop(), connect(), delete(), get(), last(), pass(), pop_list(), reset(), top(), uidl(), and user().
last ($type = "count")
Definition at line 388 of file class-pop3.php.
References $count, $size, is_ok(), and send_cmd().
Referenced by apop(), pass(), and popstat().
login ($login = "", $pass = "")
Definition at line 209 of file class-pop3.php.
References $count, $FP, pass(), and user().
Referenced by apop().
parse_banner ($server_text)
Definition at line 629 of file class-pop3.php.
References $count, and strip_clf().
Referenced by connect().
pass ($pass = "")
Definition at line 140 of file class-pop3.php.
References $count, elseif, is_ok(), last(), quit(), and send_cmd().
Referenced by login().
POP3 ($server = '', $timeout = '')
PHP4 constructor.
Definition at line 71 of file class-pop3.php.
pop_list ($msgNum = "")
Definition at line 275 of file class-pop3.php.
References $COUNT, $FP, $size, is_ok(), send_cmd(), strip_clf(), and update_timer().
popstat ()
Definition at line 500 of file class-pop3.php.
References last().
quit ()
Definition at line 480 of file class-pop3.php.
References $FP, and strip_clf().
Referenced by pass(), and reset().
reset ()
Definition at line 419 of file class-pop3.php.
References is_ok(), quit(), and send_cmd().
send_cmd ($cmd = "")
Definition at line 443 of file class-pop3.php.
References $BUFFER, $FP, strip_clf(), and update_timer().
Referenced by apop(), delete(), get(), last(), pass(), pop_list(), reset(), uidl(), and user().
strip_clf ($text = "")
Definition at line 618 of file class-pop3.php.
References $text, and str_replace.
Referenced by connect(), parse_banner(), pop_list(), quit(), send_cmd(), top(), and uidl().
top ($msgNum, $numLines = "0")
Definition at line 233 of file class-pop3.php.
References $BUFFER, $count, $FP, is_ok(), strip_clf(), and update_timer().
uidl ($msgNum = "")
Definition at line 515 of file class-pop3.php.
References $BUFFER, $COUNT, $count, $FP, $msg, is_ok(), send_cmd(), strip_clf(), and update_timer().
update_timer ()
Definition at line 75 of file class-pop3.php.
Referenced by connect(), get(), pop_list(), send_cmd(), top(), and uidl().
user ($user = "")
Definition at line 121 of file class-pop3.php.
References $user, elseif, is_ok(), and send_cmd().
Referenced by login().
Field Documentation
$ALLOWAPOP = FALSE
Definition at line 43 of file class-pop3.php.
$BANNER = ''
Definition at line 40 of file class-pop3.php.
Referenced by apop().
$BUFFER = 512
Definition at line 27 of file class-pop3.php.
Referenced by get(), send_cmd(), top(), and uidl().
$COUNT = -1
Definition at line 25 of file class-pop3.php.
Referenced by pop_list(), and uidl().
$DEBUG = FALSE
Definition at line 36 of file class-pop3.php.
$ERROR = ''
Definition at line 20 of file class-pop3.php.
$FP = ''
Definition at line 31 of file class-pop3.php.
Referenced by get(), login(), pop_list(), quit(), send_cmd(), top(), and uidl().
$MAILSERVER = ''
Definition at line 34 of file class-pop3.php.
Referenced by connect().
$TIMEOUT = 60
Definition at line 22 of file class-pop3.php.
The documentation for this class was generated from the following file:
class-pop3.php