GravityView: WP_Customize_Manager Class Reference
WP_Customize_Manager Class Reference
Customize Manager class.
Public Member Functions
__construct ()
Constructor.
_sanitize_header_textcolor ($color)
Callback for validating the header_textcolor value.
add_control ($id, $args=array())
Add a customize control.
add_dynamic_settings ($setting_ids)
Register any dynamically-created settings, such as those from $_POST['customized'] that have no corresponding setting created.
add_panel ($id, $args=array())
Add a customize panel.
add_section ($id, $args=array())
Add a customize section.
add_setting ($id, $args=array())
Add a customize setting.
after_setup_theme ()
Callback to validate a theme once it is loaded.
containers ()
Get the registered containers.
controls ()
Get the registered controls.
current_theme ($current_theme)
Filter the current theme and return the name of the previewed theme.
customize_pane_settings ()
Print JavaScript settings for parent window.
customize_preview_base ()
Print base element for preview frame.
customize_preview_html5 ()
Print a workaround to handle HTML5 tags in IE < 9.
customize_preview_init ()
Print JavaScript settings.
customize_preview_loading_style ()
Print CSS for loading indicators for the Customizer preview.
customize_preview_override_404_status ()
Prevent sending a 404 status when returning the response for the customize preview, since it causes the jQuery AJAX to fail.
customize_preview_settings ()
Print JavaScript settings for preview frame.
customize_preview_signature ()
Prints a signature so we can ensure the Customizer was properly executed.
doing_ajax ($action=null)
Return true if it's an AJAX request.
enqueue_control_scripts ()
Enqueue scripts for customize controls.
get_autofocus ()
Get the autofocused constructs.
get_control ($id)
Retrieve a customize control.
get_document_title_template ()
Get the template string for the Customizer pane document title.
get_panel ($id)
Retrieve a customize panel.
get_preview_url ()
Get the initial URL to be previewed.
get_return_url ()
Get URL to link the user to when closing the Customizer.
get_section ($id)
Retrieve a customize section.
get_setting ($id)
Retrieve a customize setting.
get_stylesheet ()
Retrieve the stylesheet name of the previewed theme.
get_stylesheet_root ()
Retrieve the stylesheet root of the previewed theme.
get_template ()
Retrieve the template name of the previewed theme.
get_template_root ()
Retrieve the template root of the previewed theme.
is_ios ()
Determine whether the user agent is iOS.
is_preview ()
Is it a theme preview?
is_theme_active ()
Checks if the current theme is active.
panels ()
Get the registered panels.
post_value ($setting, $default=null)
Return the sanitized value for a given setting from the request's POST data.
prepare_controls ()
Prepare panels, sections, and controls.
refresh_nonces ()
Refresh nonces for the current preview.
register_control_type ($control)
Register a customize control type.
register_controls ()
Register some default controls.
register_dynamic_settings ()
Add settings from the POST data that were not added with code, e.g.
register_panel_type ($panel)
Register a customize panel type.
register_section_type ($section)
Register a customize section type.
remove_control ($id)
Remove a customize control.
remove_panel ($id)
Remove a customize panel.
remove_preview_signature ($return=null)
Removes the signature in case we experience a case where the Customizer was not properly executed.
remove_section ($id)
Remove a customize section.
remove_setting ($id)
Remove a customize setting.
render_control_templates ()
Render JS templates for all registered control types.
render_panel_templates ()
Render JS templates for all registered panel types.
render_section_templates ()
Render JS templates for all registered section types.
save ()
Switch the theme and trigger the save() method on each setting.
sections ()
Get the registered sections.
set_autofocus ($autofocus)
Set the autofocused constructs.
set_post_value ($setting_id, $value)
Override a setting's (unsanitized) value as found in any incoming $_POST['customized'].
set_preview_url ($preview_url)
Set the initial URL to be previewed.
set_return_url ($return_url)
Set URL to link the user to when closing the Customizer.
settings ()
Get the registered settings.
setup_theme ()
Start preview and customize theme.
start_previewing_theme ()
If the theme to be previewed isn't the active theme, add filter callbacks to swap it out at runtime.
stop_previewing_theme ()
Stop previewing the selected theme.
theme ()
Get the theme being customized.
unsanitized_post_values ()
Parse the incoming $_POST['customized'] JSON data and store the unsanitized settings for subsequent post_value() lookups.
wp_die_handler ()
Return the AJAX wp_die() handler if it's a customized request.
wp_loaded ()
Register styles/scripts and initialize the preview of each setting.
wp_redirect_status ($status)
Prevents AJAX requests from following redirects when previewing a theme by issuing a 200 response instead of a 30x.
Data Fields
$nav_menus
$widgets
Protected Member Functions
_cmp_priority ($a, $b)
Helper function to compare two objects by priority, ensuring sort stability via instance_number.
wp_die ($ajax_message, $message=null)
Custom wp_die wrapper.
Protected Attributes
$autofocus = array()
$components = array('widgets', 'nav_menus')
$containers = array()
$controls = array()
$nonce_tick
$original_stylesheet
$panels = array()
$preview_url
$previewing = false
$registered_control_types = array()
$registered_panel_types = array()
$registered_section_types = array()
$return_url
$sections = array()
$settings = array()
$theme
Private Attributes
$_post_values
Detailed Description
Customize Manager class.
Bootstraps the Customize experience on the server-side.
Sets up the theme-switching process if a theme other than the active one is being previewed and customized.
Serves as a factory for Customize Controls and Settings, and instantiates default Customize Controls and Settings.
Since
3.4.0
Definition at line 23 of file class-wp-customize-manager.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Since
3.4.0
Filter the core Customizer components to load.
This allows Core components to be excluded from being instantiated by filtering them out of the array. Note that this filter generally runs during the plugins_loaded action, so it cannot be added in a theme.
Since
4.4.0
See also
WP_Customize_Manager::__construct()
Parameters
array $components List of core components to load.
WP_Customize_Manager $this WP_Customize_Manager instance.
Definition at line 198 of file class-wp-customize-manager.php.
References $components, ABSPATH, add_action(), add_filter(), apply_filters(), remove_action(), and WPINC.
Member Function Documentation
_cmp_priority ($a, $b) protected
Helper function to compare two objects by priority, ensuring sort stability via instance_number.
Since
3.4.0
Parameters
WP_Customize_Panel | WP_Customize_Section | WP_Customize_Control $a Object A.
WP_Customize_Panel | WP_Customize_Section | WP_Customize_Control $b Object B.
Returns
int
Definition at line 1413 of file class-wp-customize-manager.php.
_sanitize_header_textcolor ($color)
Callback for validating the header_textcolor value.
Accepts 'blank', and otherwise uses sanitize_hex_color_no_hash(). Returns default text color if hex color is empty.
Since
3.4.0
Parameters
string $color
Returns
mixed
Definition at line 2110 of file class-wp-customize-manager.php.
References get_theme_support(), and sanitize_hex_color_no_hash().
add_control ($id, $args = array())
Add a customize control.
Since
3.4.0
4.5.0 Return added WP_Customize_Control instance. public
Parameters
WP_Customize_Control | string $id Customize Control object, or ID.
array $args Control arguments; passed to WP_Customize_Control constructor.
Returns
WP_Customize_Control The instance of the control that was added.
Definition at line 1341 of file class-wp-customize-manager.php.
References $id, and controls().
Referenced by register_controls().
add_dynamic_settings ($setting_ids)
Register any dynamically-created settings, such as those from $_POST['customized'] that have no corresponding setting created.
This is a mechanism to "wake up" settings that have been dynamically created on the frontend and have been sent to WordPress in `$_POST['customized']`. When WP loads, the dynamically-created settings then will get created and previewed even though they are not directly created statically with code.
Since
4.2.0 public
Parameters
array $setting_ids The setting IDs to add.
Returns
array The WP_Customize_Setting objects added.
Filter a dynamic setting's constructor args.
For a dynamic setting to be registered, this filter must be employed to override the default false value with an array of args to pass to the WP_Customize_Setting constructor.
Since
4.2.0
Parameters
false | array $setting_args The arguments to the WP_Customize_Setting constructor.
string $setting_id ID for dynamic setting, usually coming from `$_POST['customized']`.
Allow non-statically created settings to be constructed with custom WP_Customize_Setting subclass.
Since
4.2.0
Parameters
string $setting_class WP_Customize_Setting or a subclass.
string $setting_id ID for dynamic setting, usually coming from `$_POST['customized']`.
array $setting_args WP_Customize_Setting or a subclass.
Definition at line 1091 of file class-wp-customize-manager.php.
References add_setting(), apply_filters(), and get_setting().
Referenced by register_dynamic_settings().
add_panel ($id, $args = array())
Add a customize panel.
Since
4.0.0
4.5.0 Return added WP_Customize_Panel instance. public
Parameters
WP_Customize_Panel | string $id Customize Panel object, or Panel ID.
array $args Optional. Panel arguments. Default empty array.
Returns
WP_Customize_Panel The instance of the panel that was added.
Definition at line 1175 of file class-wp-customize-manager.php.
References $id, and panels().
add_section ($id, $args = array())
Add a customize section.
Since
3.4.0
4.5.0 Return added WP_Customize_Section instance. public
Parameters
WP_Customize_Section | string $id Customize Section object, or Section ID.
array $args Section arguments.
Returns
WP_Customize_Section The instance of the section that was added.
Definition at line 1265 of file class-wp-customize-manager.php.
References $id, and sections().
Referenced by register_controls().
add_setting ($id, $args = array())
Add a customize setting.
Since
3.4.0
4.5.0 Return added WP_Customize_Setting instance. public
Parameters
WP_Customize_Setting | string $id Customize Setting object, or ID.
array $args Setting arguments; passed to WP_Customize_Setting constructor.
Returns
WP_Customize_Setting The instance of the setting that was added.
This filter is documented in wp-includes/class-wp-customize-manager.php
This filter is documented in wp-includes/class-wp-customize-manager.php
Definition at line 1057 of file class-wp-customize-manager.php.
References $class, $id, and apply_filters().
Referenced by add_dynamic_settings(), and register_controls().
after_setup_theme ()
Callback to validate a theme once it is loaded.
Since
3.4.0
Definition at line 413 of file class-wp-customize-manager.php.
References $_SERVER, doing_ajax(), exit, and validate_current_theme().
containers ()
Get the registered containers.
Since
4.0.0
Returns
array
Definition at line 540 of file class-wp-customize-manager.php.
References $containers.
Referenced by prepare_controls().
controls ()
Get the registered controls.
Since
3.4.0
Returns
array
Definition at line 529 of file class-wp-customize-manager.php.
References $controls.
Referenced by add_control(), customize_pane_settings(), customize_preview_settings(), enqueue_control_scripts(), get_control(), prepare_controls(), and remove_control().
current_theme ($current_theme)
Filter the current theme and return the name of the previewed theme.
Since
3.4.0
Parameters
$current_theme {
Definition at line 950 of file class-wp-customize-manager.php.
References theme().
customize_pane_settings ()
Print JavaScript settings for parent window.
Since
4.4.0
Filter the list of URLs allowed to be clicked and followed in the Customizer preview.
Since
3.4.0
Parameters
array $allowed_urls An array of allowed URLs.
Definition at line 1642 of file class-wp-customize-manager.php.
References $id, $settings, add_query_arg(), admin_url(), apply_filters(), controls(), esc_url_raw(), get_autofocus(), get_control(), get_document_title_template(), get_preview_url(), get_stylesheet(), home_url(), is_ios(), is_ssl(), is_theme_active(), panels(), sections(), settings(), wp_is_mobile(), wp_json_encode(), and wp_login_url().
customize_preview_base ()
Print base element for preview frame.
Since
3.4.0
Definition at line 755 of file class-wp-customize-manager.php.
customize_preview_html5 ()
Print a workaround to handle HTML5 tags in IE < 9.
Since
3.4.0
Definition at line 764 of file class-wp-customize-manager.php.
References endif.
customize_preview_init ()
Print JavaScript settings.
Since
3.4.0
Fires once the Customizer preview has initialized and JavaScript settings have been printed.
Since
3.4.0
Parameters
WP_Customize_Manager $this WP_Customize_Manager instance.
Definition at line 708 of file class-wp-customize-manager.php.
References add_action(), add_filter(), do_action(), get_stylesheet(), prepare_controls(), and wp_enqueue_script().
Referenced by wp_loaded().
customize_preview_loading_style ()
Print CSS for loading indicators for the Customizer preview.
Since
4.2.0 public
Definition at line 783 of file class-wp-customize-manager.php.
customize_preview_override_404_status ()
Prevent sending a 404 status when returning the response for the customize preview, since it causes the jQuery AJAX to fail.
Send 200 instead.
Since
4.0.0 public
Definition at line 744 of file class-wp-customize-manager.php.
References is_404, and status_header().
customize_preview_settings ()
Print JavaScript settings for preview frame.
Since
3.4.0
Definition at line 802 of file class-wp-customize-manager.php.
References $id, $settings, controls(), get_stylesheet(), panels(), sections(), wp_json_encode(), and wp_unslash().
customize_preview_signature ()
Prints a signature so we can ensure the Customizer was properly executed.
Since
3.4.0
Definition at line 869 of file class-wp-customize-manager.php.
doing_ajax ($action = null)
Return true if it's an AJAX request.
Since
3.4.0
4.2.0 Added $action param. public
Parameters
string | null $action Whether the supplied AJAX action is being run.
Returns
bool True if it's an AJAX request, false otherwise.
Definition at line 304 of file class-wp-customize-manager.php.
References $action, DOING_AJAX, and wp_unslash().
Referenced by after_setup_theme(), setup_theme(), wp_die(), and wp_die_handler().
enqueue_control_scripts ()
Enqueue scripts for customize controls.
Since
3.4.0
Definition at line 1492 of file class-wp-customize-manager.php.
References controls().
get_autofocus ()
Get the autofocused constructs.
Since
4.4.0 public
Returns
array { Mapping of 'panel', 'section', 'control' to the ID which should be autofocused.
string [$control] ID for control to be autofocused. string [$section] ID for section to be autofocused. string [$panel] ID for panel to be autofocused. }
Definition at line 1633 of file class-wp-customize-manager.php.
References $autofocus.
Referenced by customize_pane_settings().
get_control ($id)
Retrieve a customize control.
Since
3.4.0
Parameters
string $id ID of the control.
Returns
WP_Customize_Control|void The control object, if set.
Definition at line 1360 of file class-wp-customize-manager.php.
References $id, and controls().
Referenced by customize_pane_settings().
get_document_title_template ()
Get the template string for the Customizer pane document title.
Since
4.4.0 public
Returns
string The template string for the document title.
Definition at line 1518 of file class-wp-customize-manager.php.
References __, and is_theme_active().
Referenced by customize_pane_settings().
get_panel ($id)
Retrieve a customize panel.
Since
4.0.0 public
Parameters
string $id Panel ID to get.
Returns
WP_Customize_Panel|void Requested panel instance, if set.
Definition at line 1195 of file class-wp-customize-manager.php.
References $id, and panels().
get_preview_url ()
Get the initial URL to be previewed.
Since
4.4.0 public
Returns
string URL being previewed.
Definition at line 1552 of file class-wp-customize-manager.php.
References $preview_url, and home_url().
Referenced by customize_pane_settings().
get_return_url ()
Get URL to link the user to when closing the Customizer.
Since
4.4.0 public
Returns
string URL for link to close Customizer.
Definition at line 1585 of file class-wp-customize-manager.php.
References $preview_url, $referer, $return_url, home_url(), and wp_get_referer().
get_section ($id)
Retrieve a customize section.
Since
3.4.0
Parameters
string $id Section ID.
Returns
WP_Customize_Section|void The section, if set.
Definition at line 1284 of file class-wp-customize-manager.php.
References $id, and sections().
get_setting ($id)
Retrieve a customize setting.
Since
3.4.0
Parameters
string $id Customize Setting ID.
Returns
WP_Customize_Setting|void The setting, if set.
Definition at line 1146 of file class-wp-customize-manager.php.
References $id.
Referenced by add_dynamic_settings(), and register_controls().
get_stylesheet ()
Retrieve the stylesheet name of the previewed theme.
Since
3.4.0
Returns
string Stylesheet name.
Definition at line 916 of file class-wp-customize-manager.php.
References theme().
Referenced by customize_pane_settings(), customize_preview_init(), customize_preview_settings(), get_stylesheet_root(), is_theme_active(), refresh_nonces(), save(), and setup_theme().
get_stylesheet_root ()
Retrieve the stylesheet root of the previewed theme.
Since
3.4.0
Returns
string Theme root.
Definition at line 938 of file class-wp-customize-manager.php.
References get_raw_theme_root(), and get_stylesheet().
get_template ()
Retrieve the template name of the previewed theme.
Since
3.4.0
Returns
string Template name.
Definition at line 905 of file class-wp-customize-manager.php.
References theme().
Referenced by get_template_root().
get_template_root ()
Retrieve the template root of the previewed theme.
Since
3.4.0
Returns
string Theme root.
Definition at line 927 of file class-wp-customize-manager.php.
References get_raw_theme_root(), and get_template().
is_ios ()
Determine whether the user agent is iOS.
Since
4.4.0 public
Returns
bool Whether the user agent is iOS.
Definition at line 1506 of file class-wp-customize-manager.php.
References $_SERVER, and wp_is_mobile().
Referenced by customize_pane_settings().
is_preview ()
Is it a theme preview?
Since
3.4.0
Returns
bool True if it's a preview, false if not.
Definition at line 894 of file class-wp-customize-manager.php.
References $previewing.
Referenced by refresh_nonces(), save(), start_previewing_theme(), stop_previewing_theme(), wp_loaded(), and wp_redirect_status().
is_theme_active ()
Checks if the current theme is active.
Since
3.4.0
Returns
bool
Definition at line 574 of file class-wp-customize-manager.php.
References $original_stylesheet, and get_stylesheet().
Referenced by customize_pane_settings(), get_document_title_template(), register_controls(), save(), setup_theme(), start_previewing_theme(), and stop_previewing_theme().
panels ()
Get the registered panels.
Since
4.0.0 public
Returns
array Panels.
Definition at line 563 of file class-wp-customize-manager.php.
References $panels.
Referenced by add_panel(), customize_pane_settings(), customize_preview_settings(), get_panel(), prepare_controls(), and remove_panel().
post_value ($setting, $default = null)
Return the sanitized value for a given setting from the request's POST data.
Since
3.4.0
4.1.1 Introduced 'default' parameter.
Parameters
WP_Customize_Setting $setting A WP_Customize_Setting derived object
mixed $default value returned $setting has no post value (added in 4.2.0).
Returns
string|mixed $post_value Sanitized value or the $default provided
Definition at line 650 of file class-wp-customize-manager.php.
References $default, and unsanitized_post_values().
prepare_controls ()
Prepare panels, sections, and controls.
For each, check if required related components exist, whether the user has the necessary capabilities, and sort by priority.
Since
3.4.0
Definition at line 1430 of file class-wp-customize-manager.php.
References $controls, $id, $panels, $sections, containers(), controls(), panels(), and sections().
Referenced by customize_preview_init().
refresh_nonces ()
Refresh nonces for the current preview.
Since
4.2.0
Filter nonces for a customize_refresh_nonces AJAX request.
Since
4.2.0
Parameters
array $nonces Array of refreshed nonces for save and preview actions.
WP_Customize_Manager $this WP_Customize_Manager instance.
Definition at line 1022 of file class-wp-customize-manager.php.
References apply_filters(), get_stylesheet(), is_preview(), wp_send_json_error(), and wp_send_json_success().
register_control_type ($control)
Register a customize control type.
Registered types are eligible to be rendered via JS and created dynamically.
Since
4.1.0 public
Parameters
string $control Name of a custom control which is a subclass of {
See also
WP_Customize_Control}.
Definition at line 1387 of file class-wp-customize-manager.php.
Referenced by register_controls().
register_controls ()
Register some default controls.
Since
3.4.0
Definition at line 1784 of file class-wp-customize-manager.php.
References $theme, __, ABSPATH, add_control(), add_section(), add_setting(), get_option(), get_pages(), get_setting(), get_theme_support(), is_theme_active(), register_control_type(), register_panel_type(), register_section_type(), theme(), wp_get_theme(), and wp_prepare_themes_for_js().
register_dynamic_settings ()
Add settings from the POST data that were not added with code, e.g.
dynamically-created settings for Widgets
Since
4.2.0 public
See also
add_dynamic_settings()
Definition at line 2095 of file class-wp-customize-manager.php.
References add_dynamic_settings(), and unsanitized_post_values().
register_panel_type ($panel)
Register a customize panel type.
Registered types are eligible to be rendered via JS and created dynamically.
Since
4.3.0 public
See also
WP_Customize_Panel
Parameters
string $panel Name of a custom panel which is a subclass of WP_Customize_Panel.
Definition at line 1236 of file class-wp-customize-manager.php.
Referenced by register_controls().
register_section_type ($section)
Register a customize section type.
Registered types are eligible to be rendered via JS and created dynamically.
Since
4.3.0 public
See also
WP_Customize_Section
Parameters
string $section Name of a custom section which is a subclass of WP_Customize_Section.
Definition at line 1312 of file class-wp-customize-manager.php.
Referenced by register_controls().
remove_control ($id)
Remove a customize control.
Since
3.4.0
Parameters
string $id ID of the control.
Definition at line 1372 of file class-wp-customize-manager.php.
References $id, and controls().
remove_panel ($id)
Remove a customize panel.
Since
4.0.0 public
Parameters
string $id Panel ID to remove.
Definition at line 1209 of file class-wp-customize-manager.php.
References $id, $message, __, _doing_it_wrong(), esc_url, and panels().
remove_preview_signature ($return = null)
Removes the signature in case we experience a case where the Customizer was not properly executed.
Since
3.4.0
Parameters
mixed $return Value passed through for wp_die_handler filter.
Returns
mixed Value passed through for wp_die_handler filter.
Definition at line 881 of file class-wp-customize-manager.php.
References remove_action().
remove_section ($id)
Remove a customize section.
Since
3.4.0
Parameters
string $id Section ID.
Definition at line 1296 of file class-wp-customize-manager.php.
References $id, and sections().
remove_setting ($id)
Remove a customize setting.
Since
3.4.0
Parameters
string $id Customize Setting ID.
Definition at line 1159 of file class-wp-customize-manager.php.
References $id.
render_control_templates ()
Render JS templates for all registered control types.
Since
4.1.0 public
Definition at line 1397 of file class-wp-customize-manager.php.
render_panel_templates ()
Render JS templates for all registered panel types.
Since
4.3.0 public
Definition at line 1246 of file class-wp-customize-manager.php.
render_section_templates ()
Render JS templates for all registered section types.
Since
4.3.0 public
Definition at line 1322 of file class-wp-customize-manager.php.
save ()
Switch the theme and trigger the save() method on each setting.
Since
3.4.0
Fires once the theme has switched in the Customizer, but before settings have been saved.
Since
3.4.0
Parameters
WP_Customize_Manager $this WP_Customize_Manager instance.
Fires after Customize settings have been saved.
Since
3.6.0
Parameters
WP_Customize_Manager $this WP_Customize_Manager instance.
Filter response data for a successful customize_save AJAX request.
This filter does not apply if there was a nonce or authentication failure.
Since
4.2.0
Parameters
array $data Additional information passed back to the 'saved' event on wp.customize.
WP_Customize_Manager $this WP_Customize_Manager instance.
Definition at line 959 of file class-wp-customize-manager.php.
References $action, apply_filters(), do_action(), get_stylesheet(), is_preview(), is_theme_active(), start_previewing_theme(), stop_previewing_theme(), switch_theme(), update_option(), wp_send_json_error(), and wp_send_json_success().
sections ()
Get the registered sections.
Since
3.4.0
Returns
array
Definition at line 551 of file class-wp-customize-manager.php.
References $sections.
Referenced by add_section(), customize_pane_settings(), customize_preview_settings(), get_section(), prepare_controls(), and remove_section().
set_autofocus ($autofocus)
Set the autofocused constructs.
Since
4.4.0 public
Parameters
array $autofocus { Mapping of 'panel', 'section', 'control' to the ID which should be autofocused.
string [$control] ID for control to be autofocused. string [$section] ID for section to be autofocused. string [$panel] ID for panel to be autofocused. }
Definition at line 1615 of file class-wp-customize-manager.php.
References $autofocus, and wp_array_slice_assoc().
set_post_value ($setting_id, $value)
Override a setting's (unsanitized) value as found in any incoming $_POST['customized'].
Since
4.2.0 public
Parameters
string $setting_id ID for the WP_Customize_Setting instance.
mixed $value Post value.
Announce when a specific setting's unsanitized post value has been set.
Fires when the {
See also
WP_Customize_Manager::set_post_value()} method is called.
The dynamic portion of the hook name, $setting_id, refers to the setting ID.
Since
4.4.0
Parameters
mixed $value Unsanitized setting post value.
WP_Customize_Manager $this WP_Customize_Manager instance.
Announce when any setting's unsanitized post value has been set.
Fires when the {
See also
WP_Customize_Manager::set_post_value()} method is called.
This is useful for WP_Customize_Setting instances to watch in order to update a cached previewed value.
Since
4.4.0
Parameters
string $setting_id Setting ID.
mixed $value Unsanitized setting post value.
WP_Customize_Manager $this WP_Customize_Manager instance.
Definition at line 668 of file class-wp-customize-manager.php.
References $value, do_action(), and unsanitized_post_values().
set_preview_url ($preview_url)
Set the initial URL to be previewed.
URL is validated.
Since
4.4.0 public
Parameters
string $preview_url URL to be previewed.
Definition at line 1540 of file class-wp-customize-manager.php.
References $preview_url, and home_url().
set_return_url ($return_url)
Set URL to link the user to when closing the Customizer.
URL is validated.
Since
4.4.0 public
Parameters
string $return_url URL for return link.
Definition at line 1571 of file class-wp-customize-manager.php.
References $return_url, remove_query_arg(), and wp_removable_query_args().
settings ()
Get the registered settings.
Since
3.4.0
Returns
array
Definition at line 518 of file class-wp-customize-manager.php.
References $settings.
Referenced by customize_pane_settings().
setup_theme ()
Start preview and customize theme.
Check if customize query variable exist. Init filters to filter the current theme.
Since
3.4.0
Definition at line 364 of file class-wp-customize-manager.php.
References __, add_action(), current_user_can(), doing_ajax(), elseif, get_stylesheet(), is_admin(), is_theme_active(), null, send_origin_headers(), show_admin_bar(), start_previewing_theme(), theme(), wp_die(), and wp_get_theme().
start_previewing_theme ()
If the theme to be previewed isn't the active theme, add filter callbacks to swap it out at runtime.
Since
3.4.0
Fires once the Customizer theme preview has started.
Since
3.4.0
Parameters
WP_Customize_Manager $this WP_Customize_Manager instance.
Definition at line 427 of file class-wp-customize-manager.php.
References add_filter(), do_action(), is_preview(), and is_theme_active().
Referenced by save(), and setup_theme().
stop_previewing_theme ()
Stop previewing the selected theme.
Removes filters to change the current theme.
Since
3.4.0
Fires once the Customizer theme preview has stopped.
Since
3.4.0
Parameters
WP_Customize_Manager $this WP_Customize_Manager instance.
Definition at line 466 of file class-wp-customize-manager.php.
References do_action(), is_preview(), is_theme_active(), and remove_filter().
Referenced by save().
theme ()
Get the theme being customized.
Since
3.4.0
Returns
WP_Theme
Definition at line 504 of file class-wp-customize-manager.php.
References $theme, and wp_get_theme().
Referenced by current_theme(), get_stylesheet(), get_template(), register_controls(), and setup_theme().
unsanitized_post_values ()
Parse the incoming $_POST['customized'] JSON data and store the unsanitized settings for subsequent post_value() lookups.
Since
4.1.1
Returns
array
Definition at line 624 of file class-wp-customize-manager.php.
References $_post_values, and wp_unslash().
Referenced by post_value(), register_dynamic_settings(), and set_post_value().
wp_die ($ajax_message, $message = null) protected
Custom wp_die wrapper.
Returns either the standard message for UI or the AJAX message.
Since
3.4.0
Parameters
mixed $ajax_message AJAX return
mixed $message UI message
Definition at line 330 of file class-wp-customize-manager.php.
References $message, __, and doing_ajax().
Referenced by setup_theme().
wp_die_handler ()
Return the AJAX wp_die() handler if it's a customized request.
Since
3.4.0
Returns
string
Definition at line 349 of file class-wp-customize-manager.php.
References doing_ajax().
wp_loaded ()
Register styles/scripts and initialize the preview of each setting.
Since
3.4.0
Fires once WordPress has loaded, allowing scripts and styles to be initialized.
Since
3.4.0
Parameters
WP_Customize_Manager $this WP_Customize_Manager instance.
Definition at line 583 of file class-wp-customize-manager.php.
References customize_preview_init(), do_action(), is_admin(), and is_preview().
wp_redirect_status ($status)
Prevents AJAX requests from following redirects when previewing a theme by issuing a 200 response instead of a 30x.
Instead, the JS will sniff out the location header.
Since
3.4.0
Parameters
$status
Returns
int
Definition at line 609 of file class-wp-customize-manager.php.
References is_admin(), and is_preview().
Field Documentation
$_post_values private
Definition at line 191 of file class-wp-customize-manager.php.
Referenced by unsanitized_post_values().
$autofocus = array() protected
Definition at line 184 of file class-wp-customize-manager.php.
Referenced by get_autofocus(), and set_autofocus().
$components = array('widgets', 'nav_menus') protected
Definition at line 103 of file class-wp-customize-manager.php.
Referenced by __construct().
$containers = array() protected
Definition at line 85 of file class-wp-customize-manager.php.
Referenced by containers().
$controls = array() protected
Definition at line 121 of file class-wp-customize-manager.php.
Referenced by controls(), and prepare_controls().
$nav_menus
Definition at line 67 of file class-wp-customize-manager.php.
$nonce_tick protected
Definition at line 130 of file class-wp-customize-manager.php.
$original_stylesheet protected
Definition at line 40 of file class-wp-customize-manager.php.
Referenced by is_theme_active().
$panels = array() protected
Definition at line 94 of file class-wp-customize-manager.php.
Referenced by panels(), and prepare_controls().
$preview_url protected
Definition at line 166 of file class-wp-customize-manager.php.
Referenced by get_preview_url(), get_return_url(), and set_preview_url().
$previewing = false protected
Definition at line 49 of file class-wp-customize-manager.php.
Referenced by is_preview().
$registered_control_types = array() protected
Definition at line 157 of file class-wp-customize-manager.php.
$registered_panel_types = array() protected
Definition at line 139 of file class-wp-customize-manager.php.
$registered_section_types = array() protected
Definition at line 148 of file class-wp-customize-manager.php.
$return_url protected
Definition at line 175 of file class-wp-customize-manager.php.
Referenced by get_return_url(), and set_return_url().
$sections = array() protected
Definition at line 112 of file class-wp-customize-manager.php.
Referenced by prepare_controls(), and sections().
$settings = array() protected
Definition at line 76 of file class-wp-customize-manager.php.
Referenced by customize_pane_settings(), customize_preview_settings(), and settings().
$theme protected
Definition at line 31 of file class-wp-customize-manager.php.
Referenced by register_controls(), and theme().
$widgets
Definition at line 58 of file class-wp-customize-manager.php.
The documentation for this class was generated from the following file:
class-wp-customize-manager.php