GravityView: View_Legacy_Template Class Reference
View_Legacy_Template Class Reference
If this file is called directly, abort.
Public Member Functions
render ()
Render an old template.
Public Member Functions inherited from View_Template
__construct (View $view, Entry_Collection $entries, Request $request)
Initializer.
__destruct ()
add_id_specific_templates ($templates, $slug, $name)
Enable granular template overrides based on current post, view, form, etc.
render ()
Output some HTML.
Public Member Functions inherited from Template
__construct ()
General template initialization.
__destruct ()
Disallow any cleanup for fear of loss of global data.
pop_template_data ($var_name='data')
Restore the template data from the stack.
push_template_data ($data, $var_name='data')
Push the current template data down the stack and set.
Additional Inherited Members
Static Public Member Functions inherited from Template
static split_slug ($slug, $name=null)
Get a directory part and a full slug+name (file) components.
Data Fields inherited from View_Template
$entries
$request
$view
Data Fields inherited from Template
$located_template = ''
Static Public Attributes inherited from View_Template
static $slug
Protected Attributes inherited from View_Template
$filter_prefix = 'gravityview/template/views'
$plugin_template_directory = 'templates/views/'
$theme_template_directory = 'gravityview/views/'
Detailed Description
If this file is called directly, abort.
A legacy fallback View template.
Can be used to render old templates as needed.
Definition at line 14 of file class-gv-template-view-legacy.php.
Member Function Documentation
render()
render ()
Render an old template.
Definition at line 18 of file class-gv-template-view-legacy.php.
References $entries, $post, $template, GravityView_View\getInstance(), Legacy_Context\pop(), and Legacy_Context\push().
The documentation for this class was generated from the following file:
class-gv-template-view-legacy.php