GravityView: WP_Upgrader Class Reference
WP_Upgrader Class Reference
Core class used for upgrading/installing a local set of files via the Filesystem Abstraction classes from a Zip file.
Public Member Functions
__construct ($skin=null)
Construct the upgrader with a skin.
clear_destination ($remote_destination)
Clears the directory where this item is going to be installed into.
download_package ($package)
Download a package.
fs_connect ($directories=array(), $allow_relaxed_file_ownership=false)
Connect to the filesystem.
generic_strings ()
Add the generic strings to WP_Upgrader::$strings.
init ()
Initialize the upgrader.
install_package ($args=array())
Install a package.
maintenance_mode ($enable=false)
Toggle maintenance mode for the site.
run ($options)
Run an upgrade/install.
unpack_package ($package, $delete_package=true)
Unpack a compressed package file.
Data Fields
$result = array()
$skin = null
The upgrader skin being used.
$strings = array()
The error/notification strings used to update the user on the progress.
$update_count = 0
The total number of updates being performed.
$update_current = 0
Detailed Description
Core class used for upgrading/installing a local set of files via the Filesystem Abstraction classes from a Zip file.
Since
2.8.0
Definition at line 22 of file class-wp-upgrader.php.
Constructor & Destructor Documentation
__construct ($skin = null)
Construct the upgrader with a skin.
Since
2.8.0 public
Parameters
WP_Upgrader_Skin $skin The upgrader skin to use. Default is a {
See also
WP_Upgrader_Skin} instance.
Definition at line 99 of file class-wp-upgrader.php.
References $skin, and null.
Member Function Documentation
clear_destination ($remote_destination)
Clears the directory where this item is going to be installed into.
Since
4.3.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $remote_destination The location on the remote filesystem to be cleared
Returns
bool|WP_Error True upon success, WP_Error on failure.
Definition at line 319 of file class-wp-upgrader.php.
References $details, $file, and $name.
Referenced by install_package().
download_package ($package)
Download a package.
Since
2.8.0 public
Parameters
string $package The URI of the package. If this is the full path to an existing local file, it will be returned untouched.
Returns
string|WP_Error The full path to the downloaded package file, or a {
See also
WP_Error} object.
Filter whether to return the package.
Since
3.7.0 public
Parameters
bool $reply Whether to bail without returning the package. Default false.
string $package The package file name.
WP_Upgrader $this The WP_Upgrader instance.
Definition at line 223 of file class-wp-upgrader.php.
References apply_filters(), download_url(), and is_wp_error().
Referenced by run(), and Core_Upgrader\upgrade().
fs_connect ($directories = array(), $allow_relaxed_file_ownership = false)
Connect to the filesystem.
Since
2.8.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
array $directories Optional. A list of directories. If any of these do not exist, a {
See also
WP_Error} object will be returned. Default empty array.
Parameters
bool $allow_relaxed_file_ownership Whether to allow relaxed file ownership. Default false.
Returns
bool|WP_Error True if able to connect, false or a {
See also
WP_Error} otherwise.
Definition at line 164 of file class-wp-upgrader.php.
References $dir, ABSPATH, esc_html, get_theme_root(), is_wp_error(), WP_CONTENT_DIR, and WP_Filesystem().
Referenced by Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), Language_Pack_Upgrader\bulk_upgrade(), run(), and Core_Upgrader\upgrade().
generic_strings ()
Add the generic strings to WP_Upgrader::$strings.
Since
2.8.0 public
Definition at line 126 of file class-wp-upgrader.php.
References __.
Referenced by init().
init ()
Initialize the upgrader.
This will set the relationship between the skin being used and this upgrader, and also add the generic strings to WP_Upgrader::$strings.
Since
2.8.0 public
Definition at line 115 of file class-wp-upgrader.php.
References generic_strings().
Referenced by Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), Language_Pack_Upgrader\bulk_upgrade(), Plugin_Upgrader\install(), Theme_Upgrader\install(), Plugin_Upgrader\upgrade(), Theme_Upgrader\upgrade(), and Core_Upgrader\upgrade().
install_package ($args = array())
Install a package.
Copies the contents of a package form a source directory, and installs them in a destination directory. Optionally removes the source. It can also optionally clear out the destination folder if it already exists.
Since
2.8.0 public
WP_Filesystem_Base $wp_filesystem Subclass array $wp_theme_directories
Parameters
array | string $args { Optional. Array or string of arguments for installing a package. Default empty array.
string $source Required path to the package source. Default empty. string $destination Required path to a folder to install the package in. Default empty. bool $clear_destination Whether to delete any files already in the destination folder. Default false. bool $clear_working Whether to delete the files form the working directory after copying to the destination. Default false. bool $abort_if_destination_exists Whether to abort the installation if the destination folder already exists. Default true. array $hook_extra Extra arguments to pass to the filter hooks called by {
See also
WP_Upgrader::install_package()}. Default empty array. }
Returns
array|WP_Error The result (also stored in WP_Upgrader:$result), or a {
See also
WP_Error} on failure.
Filter the install response before the installation has started.
Returning a truthy value, or one that could be evaluated as a WP_Error will effectively short-circuit the installation, returning that value instead.
Since
2.8.0
Parameters
bool | WP_Error $response Response.
array $hook_extra Extra arguments passed to hooked filters.
Filter the source file location for the upgrade package.
Since
2.8.0
4.4.0 The $hook_extra parameter became available.
Parameters
string $source File source location.
string $remote_source Remote file source location.
WP_Upgrader $this WP_Upgrader instance.
array $hook_extra Extra arguments passed to hooked filters.
Filter whether the upgrader cleared the destination.
Since
2.8.0
Parameters
mixed $removed Whether the destination was cleared. true on success, WP_Error on failure
string $local_destination The local package destination.
string $remote_destination The remote package destination.
array $hook_extra Extra arguments passed to hooked filters.
Filter the install response after the installation has finished.
Since
2.8.0
Parameters
bool $response Install response.
array $hook_extra Extra arguments passed to hooked filters.
array $result Installation result data.
Definition at line 399 of file class-wp-upgrader.php.
References $result, ABSPATH, apply_filters(), clear_destination(), copy_dir(), elseif, is_wp_error(), str_replace, trailingslashit(), WP_CONTENT_DIR, and wp_parse_args().
Referenced by run().
maintenance_mode ($enable = false)
Toggle maintenance mode for the site.
Creates/deletes the maintenance file to enable/disable maintenance mode.
Since
2.8.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
bool $enable True to enable maintenance mode, false to disable.
Definition at line 739 of file class-wp-upgrader.php.
References $file, and elseif.
Referenced by Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), Theme_Upgrader\current_after(), and Theme_Upgrader\current_before().
run ($options)
Run an upgrade/install.
Attempts to download the package (if it is not a local file), unpack it, and install it in the destination folder.
Since
2.8.0 public
Parameters
array $options { Array or string of arguments for upgrading/installing a package.
string $package The full path or URI of the package to install. Default empty. string $destination The full path to the destination folder. Default empty. bool $clear_destination Whether to delete any files already in the destination folder. Default false. bool $clear_working Whether to delete the files form the working directory after copying to the destination. Default false. bool $abort_if_destination_exists Whether to abort the installation if the destination folder already exists. When true, $clear_destination should be false. Default true. bool $is_multi Whether this run is one of multiple upgrade/install actions being performed in bulk. When true, the skin {
See also
WP_Upgrader::header()} and {
WP_Upgrader::footer()} aren't called. Default false. array $hook_extra Extra arguments to pass to the filter hooks called by {
WP_Upgrader::run()}. }
Returns
array|false|WP_error The result from self::install_package() on success, otherwise a WP_Error, or false if unable to connect to the filesystem.
Filter the package options before running an update.
Since
4.3.0
Parameters
array $options { Options used by the upgrader.
string $package Package for update. string $destination Update location. bool $clear_destination Clear the destination resource. bool $clear_working Clear the working resource. bool $abort_if_destination_exists Abort if the Destination directory exists. bool $is_multi Whether the upgrader is running multiple times. array $hook_extra Extra hook arguments. }
This action is documented in wp-admin/includes/class-wp-upgrader.php
Definition at line 611 of file class-wp-upgrader.php.
References $options, $result, apply_filters(), do_action(), download_package(), fs_connect(), install_package(), is_wp_error(), unpack_package(), WP_CONTENT_DIR, and wp_parse_args().
Referenced by Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), Language_Pack_Upgrader\bulk_upgrade(), Theme_Upgrader\check_parent_theme_filter(), Plugin_Upgrader\install(), Theme_Upgrader\install(), Plugin_Upgrader\upgrade(), and Theme_Upgrader\upgrade().
unpack_package ($package, $delete_package = true)
Unpack a compressed package file.
Since
2.8.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $package Full path to the package file.
bool $delete_package Optional. Whether to delete the package file after attempting to unpack it. Default true.
Returns
string|WP_Error The path to the unpacked contents, or a {
See also
WP_Error} on failure.
Definition at line 269 of file class-wp-upgrader.php.
References $file, $result, is_wp_error(), and unzip_file().
Referenced by run(), and Core_Upgrader\upgrade().
Field Documentation
$result = array()
Definition at line 66 of file class-wp-upgrader.php.
Referenced by install_package(), run(), unpack_package(), and Core_Upgrader\upgrade().
WP_Upgrader_Skin $skin = null
The upgrader skin being used.
Since
2.8.0 public
Definition at line 40 of file class-wp-upgrader.php.
Referenced by __construct(), and Language_Pack_Upgrader\async_upgrade().
string $strings = array()
The error/notification strings used to update the user on the progress.
Since
2.8.0 public
Definition at line 31 of file class-wp-upgrader.php.
int $update_count = 0
The total number of updates being performed.
Set by the bulk update methods.
Since
3.0.0 public
Definition at line 77 of file class-wp-upgrader.php.
$update_current = 0
Definition at line 88 of file class-wp-upgrader.php.
The documentation for this class was generated from the following file:
class-wp-upgrader.php