GravityView: SimplePie_XML_Declaration_Parser Class Reference
SimplePie_XML_Declaration_Parser Class Reference
Public Member Functions
__construct ($data)
Create an instance of the class with the input data.
before_version_name ()
encoding_equals ()
encoding_name ()
encoding_value ()
get_value ()
Read value.
has_data ()
Check whether there is data beyond the pointer.
parse ()
Parse the input data.
skip_whitespace ()
Advance past any whitespace.
standalone_equals ()
standalone_name ()
standalone_value ()
version_equals ()
version_name ()
version_value ()
Data Fields
$data = ''
$data_length = 0
$encoding = 'UTF-8'
$position = 0
$standalone = false
$state = 'before_version_name'
$version = '1.0'
Detailed Description
Definition at line 52 of file XML/Declaration/Parser.php.
Constructor & Destructor Documentation
__construct ($data)
Create an instance of the class with the input data.
public
Parameters
string $data Input data
Definition at line 116 of file XML/Declaration/Parser.php.
References $data.
Member Function Documentation
before_version_name ()
Definition at line 192 of file XML/Declaration/Parser.php.
References skip_whitespace().
encoding_equals ()
Definition at line 266 of file XML/Declaration/Parser.php.
References skip_whitespace().
encoding_name ()
Definition at line 252 of file XML/Declaration/Parser.php.
References skip_whitespace().
encoding_value ()
Definition at line 280 of file XML/Declaration/Parser.php.
References get_value(), has_data(), and skip_whitespace().
get_value ()
Read value.
Definition at line 175 of file XML/Declaration/Parser.php.
References $value, and has_data().
Referenced by encoding_value(), standalone_value(), and version_value().
has_data ()
Check whether there is data beyond the pointer.
private
Returns
bool true if there is further data, false if not
Definition at line 155 of file XML/Declaration/Parser.php.
References $data_length.
Referenced by encoding_value(), get_value(), parse(), standalone_value(), and version_value().
parse ()
Parse the input data.
public
Returns
bool true on success, false on failure
Definition at line 128 of file XML/Declaration/Parser.php.
References $state, and has_data().
skip_whitespace ()
Advance past any whitespace.
Returns
int Number of whitespace characters passed
Definition at line 165 of file XML/Declaration/Parser.php.
Referenced by before_version_name(), encoding_equals(), encoding_name(), encoding_value(), standalone_equals(), standalone_name(), standalone_value(), version_equals(), version_name(), and version_value().
standalone_equals ()
Definition at line 314 of file XML/Declaration/Parser.php.
References skip_whitespace().
standalone_name ()
Definition at line 300 of file XML/Declaration/Parser.php.
References skip_whitespace().
standalone_value ()
Definition at line 328 of file XML/Declaration/Parser.php.
References get_value(), has_data(), and skip_whitespace().
version_equals ()
Definition at line 218 of file XML/Declaration/Parser.php.
References skip_whitespace().
version_name ()
Definition at line 204 of file XML/Declaration/Parser.php.
References skip_whitespace().
version_value ()
Definition at line 232 of file XML/Declaration/Parser.php.
References get_value(), has_data(), and skip_whitespace().
Field Documentation
$data = ''
Definition at line 92 of file XML/Declaration/Parser.php.
Referenced by __construct().
$data_length = 0
Definition at line 100 of file XML/Declaration/Parser.php.
Referenced by has_data().
$encoding = 'UTF-8'
Definition at line 68 of file XML/Declaration/Parser.php.
$position = 0
Definition at line 108 of file XML/Declaration/Parser.php.
$standalone = false
Definition at line 76 of file XML/Declaration/Parser.php.
$state = 'before_version_name'
Definition at line 84 of file XML/Declaration/Parser.php.
Referenced by parse().
$version = '1.0'
Definition at line 60 of file XML/Declaration/Parser.php.
The documentation for this class was generated from the following file:
XML/Declaration/Parser.php