GravityView: Walker_Comment Class Reference
Walker_Comment Class Reference
HTML comment list class.
Public Member Functions
display_element ($element, &$children_elements, $max_depth, $depth, $args, &$output)
Traverse elements to create list from elements.
end_el (&$output, $comment, $depth=0, $args=array())
Ends the element output, if needed.
end_lvl (&$output, $depth=0, $args=array())
End the list of items after the elements are added.
start_el (&$output, $comment, $depth=0, $args=array(), $id=0)
Start the element output.
start_lvl (&$output, $depth=0, $args=array())
Start the list before the elements are added.
Public Member Functions inherited from Walker
display_element ($element, &$children_elements, $max_depth, $depth, $args, &$output)
Traverse elements to create list from elements.
end_el (&$output, $object, $depth=0, $args=array())
Ends the element output, if needed.
end_lvl (&$output, $depth=0, $args=array())
Ends the list of after the elements are added.
get_number_of_root_elements ($elements)
Calculates the total number of root elements.
paged_walk ($elements, $max_depth, $page_num, $per_page)
paged_walk() - produce a page of nested elements
start_el (&$output, $object, $depth=0, $args=array(), $current_object_id=0)
Start the element output.
start_lvl (&$output, $depth=0, $args=array())
Starts the list before the elements are added.
unset_children ($e, &$children_elements)
Unset all the children for a given top level element.
walk ($elements, $max_depth)
Display array of elements hierarchically.
Data Fields
$db_fields = array ('parent' => 'comment_parent', 'id' => 'comment_ID')
$tree_type = 'comment'
Data Fields inherited from Walker
$db_fields
$has_children
$max_pages = 1
$tree_type
Protected Member Functions
comment ($comment, $depth, $args)
Output a single comment.
html5_comment ($comment, $depth, $args)
Output a comment in the HTML5 format.
ping ($comment, $depth, $args)
Output a pingback comment.
Detailed Description
HTML comment list class.
Walker
Since
2.7.0
Definition at line 16 of file class-walker-comment.php.
Member Function Documentation
comment ($comment, $depth, $args) protected
Output a single comment.
protected
Since
3.6.0
See also
wp_list_comments()
Parameters
object $comment Comment to display.
int $depth Depth of comment.
array $args An array of arguments.
Definition at line 253 of file class-walker-comment.php.
References $comment, __, _e, comment_class(), comment_reply_link(), comment_text(), edit_comment_link(), endif, get_comment_author_link(), get_comment_date(), and get_comment_time().
Referenced by start_el().
display_element ($element, & $children_elements, $max_depth, $depth, $args, & $output)
Traverse elements to create list from elements.
This function is designed to enhance Walker::display_element() to display children of higher nesting levels than selected inline on the highest depth level displayed. This prevents them being orphaned at the end of the comment list.
Example: max_depth = 2, with 5 levels of nested content. 1 1.1 1.1.1 1.1.1.1 1.1.1.1.1 1.1.2 1.1.2.1 2 2.2
See also
Walker::display_element()
wp_list_comments()
Since
2.7.0
Parameters
object $element Data object.
array $children_elements List of elements to continue traversing.
int $max_depth Max depth to traverse.
int $depth Depth of current element.
array $args An array of arguments.
string $output Passed by reference. Used to append additional content.
Definition at line 126 of file class-walker-comment.php.
References $id, and $output.
end_el (& $output, $comment, $depth = 0, $args = array())
Ends the element output, if needed.
Since
2.7.0
See also
Walker::end_el()
wp_list_comments()
Parameters
string $output Passed by reference. Used to append additional content.
WP_Comment $comment The comment object. Default current comment.
int $depth Depth of comment.
array $args An array of arguments.
Definition at line 206 of file class-walker-comment.php.
References $comment, and $output.
end_lvl (& $output, $depth = 0, $args = array())
End the list of items after the elements are added.
See also
Walker::end_lvl()
Since
2.7.0
int $comment_depth
Parameters
string $output Passed by reference. Used to append additional content.
int $depth Depth of comment.
array $args Will only append content if style argument value is 'ol' or 'ul'.
Definition at line 79 of file class-walker-comment.php.
References $GLOBALS, and $output.
html5_comment ($comment, $depth, $args) protected
Output a comment in the HTML5 format.
protected
Since
3.6.0
See also
wp_list_comments()
Parameters
object $comment Comment to display.
int $depth Depth of comment.
array $args An array of arguments.
Definition at line 312 of file class-walker-comment.php.
References $comment, __, _e, author, comment_class(), comment_reply_link(), comment_text(), edit_comment_link(), endif, get_comment_author_link(), get_comment_date(), and get_comment_time().
Referenced by start_el().
ping ($comment, $depth, $args) protected
Output a pingback comment.
protected
Since
3.6.0
See also
wp_list_comments()
Parameters
WP_Comment $comment The comment object.
int $depth Depth of comment.
array $args An array of arguments.
Definition at line 231 of file class-walker-comment.php.
References $comment, __, _e, comment_author_link(), comment_class(), and edit_comment_link().
Referenced by start_el().
start_el (& $output, $comment, $depth = 0, $args = array(), $id = 0)
Start the element output.
Since
2.7.0
See also
Walker::start_el()
wp_list_comments()
int $comment_depth WP_Comment $comment
Parameters
string $output Passed by reference. Used to append additional content.
object $comment Comment data object.
int $depth Depth of comment in reference to parents.
array $args An array of arguments.
int $id Optional. ID of the current comment. Default 0 (unused).
Definition at line 166 of file class-walker-comment.php.
References $comment, $GLOBALS, $output, comment(), elseif, html5_comment(), and ping().
start_lvl (& $output, $depth = 0, $args = array())
Start the list before the elements are added.
See also
Walker::start_lvl()
Since
2.7.0
int $comment_depth
Parameters
string $output Passed by reference. Used to append additional content.
int $depth Depth of comment.
array $args Uses 'style' argument for type of HTML list.
Definition at line 50 of file class-walker-comment.php.
References $GLOBALS, and $output.
Field Documentation
$db_fields = array ('parent' => 'comment_parent', 'id' => 'comment_ID')
Definition at line 35 of file class-walker-comment.php.
$tree_type = 'comment'
Definition at line 25 of file class-walker-comment.php.
The documentation for this class was generated from the following file:
class-walker-comment.php