GravityView: WP_UnitTest_Factory_For_Blog Class Reference
WP_UnitTest_Factory_For_Blog Class Reference
Public Member Functions
__construct ($factory=null)
create_object ($args)
get_object_by_id ($blog_id)
update_object ($blog_id, $fields)
Public Member Functions inherited from WP_UnitTest_Factory_For_Thing
__construct ($factory, $default_generation_definitions=array())
Creates a new factory, which will create objects of a specific Thing.
addslashes_deep ($value)
apply_callbacks ($callbacks, $created)
callback ($function)
create ($args=array(), $generation_definitions=null)
create_and_get ($args=array(), $generation_definitions=null)
create_many ($count, $args=array(), $generation_definitions=null)
create_object ($args)
generate_args ($args=array(), $generation_definitions=null, &$callbacks=null)
get_object_by_id ($object_id)
update_object ($object, $fields)
Additional Inherited Members
Data Fields inherited from WP_UnitTest_Factory_For_Thing
$default_generation_definitions
$factory
Detailed Description
Definition at line 184 of file tmp/wordpress-tests-lib/includes/factory.php.
Constructor & Destructor Documentation
__construct ($factory = null)
Definition at line 186 of file tmp/wordpress-tests-lib/includes/factory.php.
References $current_site, and WP_UnitTest_Factory_For_Thing\$factory.
Member Function Documentation
create_object ($args)
Definition at line 197 of file tmp/wordpress-tests-lib/includes/factory.php.
References $blog, $user_id, $wpdb, get_current_user_id(), wp_installing(), and wpmu_create_blog().
get_object_by_id ($blog_id)
Definition at line 214 of file tmp/wordpress-tests-lib/includes/factory.php.
References $blog_id, and get_blog_details().
update_object ($blog_id, $fields)
Definition at line 212 of file tmp/wordpress-tests-lib/includes/factory.php.
The documentation for this class was generated from the following file:
tmp/wordpress-tests-lib/includes/factory.php