GravityView: GravityView_Entry_Approval_Status Class Reference
GravityView_Entry_Approval_Status Class Reference
If this file is called directly, abort.
Static Public Member Functions
static get_all ()
Return array of status options.
static get_key ($value)
Get the status key for a value.
static get_label ($value_or_key)
Get the label for a specific approval value.
static get_labels ()
Get the labels for the status choices.
static get_string ($value_or_key, $string_key='')
Get the label for a specific approval value.
static get_title_attr ($value_or_key)
Get the label for a specific approval value.
static get_values ()
Get the status values as an array.
static is_approved ($status)
static is_disapproved ($status)
static is_unapproved ($status)
static is_valid ($value=NULL)
Check whether the passed value is one of the defined values for entry approval.
static maybe_convert_status ($old_value='')
Convert previously-used values to the current values, for backward compatibility.
Data Fields
const APPROVED = 1
const DISAPPROVED = 2
const UNAPPROVED = 3
Private Member Functions
__construct ()
GravityView_Entry_Approval_Status constructor.
Static Private Member Functions
static choice_pluck ($status, $attr_key='')
Pluck a certain field value from a status array.
static get_choices ()
Match values to the labels.
Detailed Description
If this file is called directly, abort.
There are specific values of entry approval that are valid. This class holds them and manages access to them.
Since
1.18
Definition at line 23 of file class-gravityview-entry-approval-status.php.
Constructor & Destructor Documentation
__construct()
__construct () private
GravityView_Entry_Approval_Status constructor.
Definition at line 43 of file class-gravityview-entry-approval-status.php.
Member Function Documentation
choice_pluck()
static choice_pluck ($status, $attr_key = '') static private
Pluck a certain field value from a status array.
Examples:
self::choice_pluck('disapproved', 'value'); // Returns 2 self::choice_pluck('approved', 'label'); // Returns Approved
Since
1.18
Parameters
int | string $status Valid status value or key (1 or "approved")
string $attr_key Key name for the "value", "label", "action", "title". If "key", returns the matched key instead of value.
Returns
false|string False if match isn't not found
Definition at line 245 of file class-gravityview-entry-approval-status.php.
References GV\get().
get_all()
static get_all () static
Return array of status options.
See also
GravityView_Entry_Approval_Status::get_choices
Returns
array Associative array of available statuses
Definition at line 82 of file class-gravityview-entry-approval-status.php.
Referenced by GravityView_Field_Entry_Approval\enqueue_and_localize_script().
get_choices()
static get_choices () static private
Match values to the labels.
Since
1.18
Returns
array
Definition at line 52 of file class-gravityview-entry-approval-status.php.
get_key()
static get_key ($value) static
Get the status key for a value.
Parameters
int $value Status value (1, 2, 3)
Returns
string|false The status key at status $value, if exists. If not exists, false.
Definition at line 310 of file class-gravityview-entry-approval-status.php.
References $value.
Referenced by GravityView_Field_Is_Approved\filter_field_value(), GravityView_Field_Entry_Approval\get_css_class(), and GravityView_Entry_Approval\update_approved_meta().
get_label()
static get_label ($value_or_key) static
Get the label for a specific approval value.
Since
1.18
Parameters
int | string $value_or_key Valid status value or key (1 or "approved")
Returns
string|false Label of value ("Approved"). If invalid value, return false.
Definition at line 273 of file class-gravityview-entry-approval-status.php.
Referenced by GravityView_Field_Is_Approved\field_options(), GravityView_Field_Is_Approved\filter_field_value(), GravityView_Admin_ApproveEntries\filter_links_entry_list(), and GravityView_Entry_Approval\get_entry_status().
get_labels()
static get_labels () static
Get the labels for the status choices.
Since
1.18
Returns
array Array of labels for the status choices ("Approved", "Disapproved")
Definition at line 218 of file class-gravityview-entry-approval-status.php.
References $labels.
get_string()
static get_string ($value_or_key, $string_key = '') static
Get the label for a specific approval value.
Since
1.18
Parameters
int | string $value_or_key Valid status value or key (1 or "approved")
Returns
string|false Label of value ("Approved"). If invalid value, return false.
Definition at line 286 of file class-gravityview-entry-approval-status.php.
Referenced by GravityView_Field_Entry_Approval\get_anchor_text(), GravityView_Admin_ApproveEntries\get_bulk_actions(), and GravityView_Field_Entry_Approval\get_title_attr().
get_title_attr()
static get_title_attr ($value_or_key) static
Get the label for a specific approval value.
Since
1.18
Parameters
int | string $value_or_key Valid status value or key (1 or "approved")
Returns
string|false Label of value ("Approved"). If invalid value, return false.
Definition at line 299 of file class-gravityview-entry-approval-status.php.
Referenced by GravityView_Admin_ApproveEntries\add_scripts_and_styles().
get_values()
static get_values () static
Get the status values as an array.
Since
1.18
Returns
array Array of values for approval status choices
Definition at line 93 of file class-gravityview-entry-approval-status.php.
is_approved()
static is_approved ($status) static
Parameters
mixed $status Value to check approval of
Since
1.18
Returns
bool True: passed $status matches approved value
Definition at line 176 of file class-gravityview-entry-approval-status.php.
Referenced by gventry\callback(), gvfield\callback(), gravityview\callback(), View\content(), Views_Route\get_sub_item_permissions_check(), GravityView_frontend\is_entry_approved(), and oEmbed\render_frontend().
is_disapproved()
static is_disapproved ($status) static
Parameters
mixed $status Value to check approval of
Since
1.18
Returns
bool True: passed $status matches disapproved value
Definition at line 190 of file class-gravityview-entry-approval-status.php.
is_unapproved()
static is_unapproved ($status) static
Parameters
mixed $status Value to check approval of
Since
1.18
Returns
bool True: passed $status matches unapproved value
Definition at line 204 of file class-gravityview-entry-approval-status.php.
is_valid()
static is_valid ($value = NULL) static
Check whether the passed value is one of the defined values for entry approval.
Since
1.18
Parameters
mixed $value
Returns
bool True: value is valid; false: value is not valid
Definition at line 158 of file class-gravityview-entry-approval-status.php.
References $value.
Referenced by GravityView_Entry_Approval\add_approval_status_updated_note(), GravityView_Entry_Approval\after_submission(), GravityView_Entry_Approval\ajax_update_approved(), GravityView_Entry_Approval\update_approved(), GravityView_Entry_Approval\update_approved_meta(), and GravityView_Entry_Approval\update_bulk().
maybe_convert_status()
static maybe_convert_status ($old_value = '') static
Convert previously-used values to the current values, for backward compatibility.
Since
1.18
Parameters
string $old_value The status
Returns
int|string Current value, possibly converted from old value
Definition at line 111 of file class-gravityview-entry-approval-status.php.
Referenced by GravityView_Entry_Approval\add_approval_status_updated_note(), GravityView_Field_Is_Approved\filter_field_value(), GravityView_Entry_Approval\get_entry_status(), GravityView_Entry_Approval\update_approved(), and GravityView_Entry_Approval\update_approved_meta().
Field Documentation
APPROVED
const APPROVED = 1
Definition at line 28 of file class-gravityview-entry-approval-status.php.
Referenced by GravityView_Entry_Approval\add_approval_status_updated_note(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Entry_Approval\after_update_entry_update_approved_meta(), GravityView_Admin_ApproveEntries\filter_links_entry_list(), GravityView_Admin_ApproveEntries\process_bulk_action(), GravityView_frontend\process_search_only_approved(), and GravityView_Migrate\update_approved_meta().
DISAPPROVED
const DISAPPROVED = 2
Definition at line 33 of file class-gravityview-entry-approval-status.php.
Referenced by GravityView_Entry_Approval\add_approval_status_updated_note(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Entry_Approval\after_update_entry_update_approved_meta(), GravityView_Admin_ApproveEntries\filter_links_entry_list(), GravityView_Admin_ApproveEntries\process_bulk_action(), and GravityView_Migrate\update_approved_meta().
UNAPPROVED
const UNAPPROVED = 3
Definition at line 38 of file class-gravityview-entry-approval-status.php.
Referenced by GravityView_Entry_Approval\add_approval_status_updated_note(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Entry_Approval\after_submission(), GravityView_Entry_Approval\autounapprove(), GravityView_Admin_ApproveEntries\filter_links_entry_list(), and GravityView_Admin_ApproveEntries\process_bulk_action().
The documentation for this class was generated from the following file:
class-gravityview-entry-approval-status.php