GravityView: WP_Comment_Query Class Reference
WP_Comment_Query Class Reference
Core class used for querying comments.
Public Member Functions
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($query= '')
Constructor.
get_comments ()
Get a list of comments matching the query vars.
parse_query ($query= '')
Parse arguments passed to the comment query with default query parameters.
query ($query)
Sets up the WordPress query for retrieving comments.
Data Fields
$comments
$date_query = false
$found_comments = 0
$max_num_pages = 0
$meta_query = false
$query_var_defaults
$query_vars
$request
Protected Member Functions
fill_descendants ($comments)
Fetch descendants for located comments.
get_comment_ids ()
Used internally to get a list of comment IDs matching the query vars.
get_search_sql ($string, $cols)
Used internally to generate an SQL string for searching across multiple columns.
parse_order ($order)
Parse an 'order' query variable and cast it to ASC or DESC as necessary.
parse_orderby ($orderby)
Parse and sanitize 'orderby' keys passed to the comment query.
Protected Attributes
$filtered_where_clause
$meta_query_clauses
$sql_clauses
Detailed Description
Core class used for querying comments.
Since
3.1.0
See also
WP_Comment_Query::__construct() for accepted arguments.
Definition at line 17 of file class-wp-comment-query.php.
Constructor & Destructor Documentation
__construct ($query = '')
Constructor.
Sets up the comment query, based on the query vars passed.
Since
4.2.0
4.4.0 $parent__in and $parent__not_in were added.
4.4.0 Order by comment__in was added. $update_comment_meta_cache, $no_found_rows, $hierarchical, and $update_comment_post_cache were added.
4.5.0 $author_url was added. public
Parameters
string | array $query { Optional. Array or query string of comment query parameters. Default empty.
string $author_email Comment author email address. Default empty. string $author_url Comment author URL. Default empty. array $author__in Array of author IDs to include comments for. Default empty. array $author__not_in Array of author IDs to exclude comments for. Default empty. array $comment__in Array of comment IDs to include. Default empty. array $comment__not_in Array of comment IDs to exclude. Default empty. bool $count Whether to return a comment count (true) or array of comment objects (false). Default false. array $date_query Date query clauses to limit comments by. See WP_Date_Query. Default null. string $fields Comment fields to return. Accepts 'ids' for comment IDs only or empty for all fields. Default empty. int $ID Currently unused. array $include_unapproved Array of IDs or email addresses of users whose unapproved comments will be returned by the query regardless of $status. Default empty. int $karma Karma score to retrieve matching comments for. Default empty. string $meta_key Include comments with a matching comment meta key. Default empty. string $meta_value Include comments with a matching comment meta value. Requires $meta_key to be set. Default empty. array $meta_query Meta query clauses to limit retrieved comments by. See WP_Meta_Query. Default empty. int $number Maximum number of comments to retrieve. Default null (no limit). int $offset Number of comments to offset the query. Used to build LIMIT clause. Default 0. bool $no_found_rows Whether to disable the SQL_CALC_FOUND_ROWS query. Default: true. string|array $orderby Comment status or array of statuses. To use 'meta_value' or 'meta_value_num', $meta_key must also be defined. To sort by a specific $meta_query clause, use that clause's array key. Accepts 'comment_agent', 'comment_approved', 'comment_author', 'comment_author_email', 'comment_author_IP', 'comment_author_url', 'comment_content', 'comment_date', 'comment_date_gmt', 'comment_ID', 'comment_karma', 'comment_parent', 'comment_post_ID', 'comment_type', 'user_id', 'comment__in', 'meta_value', 'meta_value_num', the value of $meta_key, and the array keys of $meta_query. Also accepts false, an empty array, or 'none' to disable ORDER BY clause. Default: 'comment_date_gmt'. string $order How to order retrieved comments. Accepts 'ASC', 'DESC'. Default: 'DESC'. int $parent Parent ID of comment to retrieve children of. Default empty. array $parent__in Array of parent IDs of comments to retrieve children for. Default empty. array $parent__not_in Array of parent IDs of comments not to retrieve children for. Default empty. array $post_author__in Array of author IDs to retrieve comments for. Default empty. array $post_author__not_in Array of author IDs not to retrieve comments for. Default empty. int $post_ID Currently unused. int $post_id Limit results to those affiliated with a given post ID. Default 0. array $post__in Array of post IDs to include affiliated comments for. Default empty. array $post__not_in Array of post IDs to exclude affiliated comments for. Default empty. int $post_author Comment author ID to limit results by. Default empty. string $post_status Post status to retrieve affiliated comments for. Default empty. string $post_type Post type to retrieve affiliated comments for. Default empty. string $post_name Post name to retrieve affiliated comments for. Default empty. int $post_parent Post parent ID to retrieve affiliated comments for. Default empty. string $search Search term(s) to retrieve matching comments for. Default empty. string $status Comment status to limit results by. Accepts 'hold' (comment_status=0), 'approve' (comment_status=1), 'all', or a custom comment status. Default 'all'. string|array $type Include comments of a given type, or array of types. Accepts 'comment', 'pings' (includes 'pingback' and 'trackback'), or anycustom type string. Default empty. array $type__in Include comments from a given array of comment types. Default empty. array $type__not_in Exclude comments from a given array of comment types. Default empty. int $user_id Include comments for a specific user ID. Default empty. bool|string $hierarchical Whether to include comment descendants in the results. 'threaded' returns a tree, with each comment's children stored in a children property on the WP_Comment object. 'flat' returns a flat array of found comments plus their children. Pass false to leave out descendants. The parameter is ignored (forced to false) when $fields is 'ids' or 'counts'. Accepts 'threaded', 'flat', or false. Default: false. bool $update_comment_meta_cache Whether to prime the metadata cache for found comments. Default true. bool $update_comment_post_cache Whether to prime the cache for comment posts. Default false. }
Definition at line 258 of file class-wp-comment-query.php.
References null, and query().
Member Function Documentation
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
Since
4.0.0 public
Parameters
callable $name Method to call.
array $arguments Arguments to pass when calling.
Returns
mixed|false Return value of the callback, false otherwise.
Definition at line 137 of file class-wp-comment-query.php.
References $name.
fill_descendants ($comments) protected
Fetch descendants for located comments.
Instead of calling get_children() separately on each child comment, we do a single set of queries to fetch the descendant trees for all matched top-level comments.
Since
4.4.0
Parameters
array $comments Array of top-level comments whose descendants should be filled in.
Returns
array
Definition at line 883 of file class-wp-comment-query.php.
References $comments, $filtered_where_clause, $i, $wpdb, _prime_comment_caches(), get_comment(), and wp_list_pluck().
Referenced by get_comments().
get_comment_ids () protected
Used internally to get a list of comment IDs matching the query vars.
Since
4.4.0 protected
wpdb $wpdb WordPress database abstraction object.
Filter the comment query clauses.
Since
3.1.0
Parameters
array $pieces A compacted array of comment query clauses.
WP_Comment_Query &$this Current instance of WP_Comment_Query, passed by reference.
Definition at line 473 of file class-wp-comment-query.php.
References $date_query, $post_id, $wpdb, absint(), apply_filters_ref_array(), elseif, get_search_sql(), parse_order(), parse_orderby(), str_replace, wp_array_slice_assoc(), and wp_parse_id_list().
Referenced by get_comments().
get_comments ()
Get a list of comments matching the query vars.
Since
4.2.0 public
wpdb $wpdb WordPress database abstraction object.
Returns
int|array The list of comments.
Fires before comments are retrieved.
Since
3.1.0
Parameters
WP_Comment_Query &$this Current instance of WP_Comment_Query, passed by reference.
Filter the query used to retrieve found comment count.
Since
4.4.0
Parameters
string $found_comments_query SQL query. Default 'SELECT FOUND_ROWS()'.
WP_Comment_Query $comment_query The WP_Comment_Query instance.
Filter the comment query results.
Since
3.1.0
Parameters
array $results An array of comments.
WP_Comment_Query &$this Current instance of WP_Comment_Query, passed by reference.
Definition at line 355 of file class-wp-comment-query.php.
References $comments, $wpdb, _prime_comment_caches(), _prime_post_caches(), apply_filters(), apply_filters_ref_array(), comments, do_action_ref_array(), fill_descendants(), get_comment(), get_comment_ids(), parse_query(), wp_array_slice_assoc(), wp_cache_add(), wp_cache_get(), and wp_cache_set().
Referenced by query().
get_search_sql ($string, $cols) protected
Used internally to generate an SQL string for searching across multiple columns.
Since
3.1.0 protected
wpdb $wpdb WordPress database abstraction object.
Parameters
string $string
array $cols
Returns
string
Definition at line 985 of file class-wp-comment-query.php.
References $wpdb.
Referenced by get_comment_ids().
parse_order ($order) protected
Parse an 'order' query variable and cast it to ASC or DESC as necessary.
Since
4.2.0 protected
Parameters
string $order The 'order' query variable.
Returns
string The sanitized 'order' query variable.
Definition at line 1071 of file class-wp-comment-query.php.
Referenced by get_comment_ids().
parse_orderby ($orderby) protected
Parse and sanitize 'orderby' keys passed to the comment query.
Since
4.2.0 protected
wpdb $wpdb WordPress database abstraction object.
Parameters
string $orderby Alias for the field to order by.
Returns
string|false Value to used in the ORDER clause. False otherwise.
Definition at line 1009 of file class-wp-comment-query.php.
References $meta_query_clauses, $wpdb, elseif, and esc_sql().
Referenced by get_comment_ids().
parse_query ($query = '')
Parse arguments passed to the comment query with default query parameters.
Since
4.2.0 Extracted from WP_Comment_Query::query().
public
Parameters
string | array $query WP_Comment_Query arguments. See WP_Comment_Query::__construct()
Definition at line 317 of file class-wp-comment-query.php.
References $query_vars, do_action_ref_array(), and wp_parse_args().
Referenced by get_comments().
query ($query)
Sets up the WordPress query for retrieving comments.
Since
3.1.0
4.1.0 Introduced 'comment__in', 'comment__not_in', 'post_author__in', 'post_author__not_in', 'author__in', 'author__not_in', 'post__in', 'post__not_in', 'include_unapproved', 'type__in', and 'type__not_in' arguments to $query_vars.
4.2.0 Moved parsing to WP_Comment_Query::parse_query(). public
Parameters
string | array $query Array or URL query string of parameters.
Returns
array|int List of comments, or number of comments when 'count' is passed as a query var.
Definition at line 340 of file class-wp-comment-query.php.
References get_comments(), and wp_parse_args().
Referenced by __construct(), get_approved_comments(), and get_comments().
Field Documentation
$comments
Definition at line 107 of file class-wp-comment-query.php.
Referenced by fill_descendants(), and get_comments().
$date_query = false
Definition at line 80 of file class-wp-comment-query.php.
Referenced by get_comment_ids().
$filtered_where_clause protected
Definition at line 71 of file class-wp-comment-query.php.
Referenced by fill_descendants().
$found_comments = 0
Definition at line 116 of file class-wp-comment-query.php.
$max_num_pages = 0
Definition at line 125 of file class-wp-comment-query.php.
$meta_query = false
Definition at line 35 of file class-wp-comment-query.php.
$meta_query_clauses protected
Definition at line 44 of file class-wp-comment-query.php.
Referenced by parse_orderby().
$query_var_defaults
Definition at line 98 of file class-wp-comment-query.php.
$query_vars
Definition at line 89 of file class-wp-comment-query.php.
Referenced by parse_query().
$request
Definition at line 26 of file class-wp-comment-query.php.
$sql_clauses protected
Initial value:
= array(
        'select'  => '',
        'from'    => '',
        'where'   => array(),
        'groupby' => '',
        'orderby' => '',
        'limits'  => '',
    )
Definition at line 53 of file class-wp-comment-query.php.
The documentation for this class was generated from the following file:
class-wp-comment-query.php