GravityView: ftp Class Reference
ftp Class Reference
Public Member Functions
__construct ($verb=FALSE, $le=FALSE)
__construct ($verb=FALSE, $le=FALSE)
_connect ($host, $port)
_connect ($host, $port)
_data_close ()
_data_close ()
_data_prepare ($mode=FTP_ASCII)
_data_prepare ($mode=FTP_ASCII)
_data_read ($mode=FTP_ASCII, $fp=NULL)
_data_read ($mode=FTP_ASCII, $fp=NULL)
_data_write ($mode=FTP_ASCII, $fp=NULL)
_data_write ($mode=FTP_ASCII, $fp=NULL)
_data_write_block ($mode, $block)
_data_write_block ($mode, $block)
_exec ($cmd, $fnction="_exec")
_exec ($cmd, $fnction="_exec")
_quit ($force=FALSE)
_quit ()
_readmsg ($fnction="_readmsg")
_readmsg ($fnction="_readmsg")
_settimeout ($sock)
_settimeout ($sock)
ftp ($verb=FALSE, $le=FALSE)
ftp ($verb=FALSE, $le=FALSE)
Public Member Functions inherited from ftp_base
__construct ($port_mode=FALSE, $verb=FALSE, $le=FALSE)
_checkCode ()
_list ($arg="", $cmd="LIST", $fnction="_list")
_settype ($mode=FTP_ASCII)
abort ()
cdup ()
chdir ($pathname)
chmod ($pathname, $mode)
connect ($server=NULL)
delete ($pathname)
dirlist ($remote)
features ()
fget ($fp, $remotefile, $rest=0)
file_exists ($pathname)
filesize ($pathname)
fput ($remotefile, $fp)
ftp_base ($port_mode=FALSE)
get ($remotefile, $localfile=NULL, $rest=0)
glob ($pattern, $handle=NULL)
glob_pattern_match ($pattern, $string)
glob_regexp ($pattern, $probe)
is_exists ($pathname)
login ($user=NULL, $pass=NULL)
mdel ($remote, $continious=false)
mdtm ($pathname)
mget ($remote, $local=".", $continious=false)
mkdir ($pathname)
mmkdir ($dir, $mode=0777)
mput ($local=".", $remote=NULL, $continious=false)
nlist ($pathname="", $arg="")
parselisting ($line)
Passive ($pasv=NULL)
PopError ()
PushError ($fctname, $msg, $desc=false)
put ($localfile, $remotefile=NULL, $rest=0)
pwd ()
quit ($force=false)
rawlist ($pathname="", $arg="")
rename ($from, $to)
restore ($from)
rmdir ($pathname)
SendMSG ($message="", $crlf=true)
SetServer ($host, $port=21, $reconnect=true)
SetTimeout ($timeout=30)
SetType ($mode=FTP_AUTOASCII)
SetUmask ($umask=0022)
site ($command, $fnction="site")
systype ()
Additional Inherited Members
Data Fields inherited from ftp_base
$_can_restore
$_code
$_connected
$_curtype
$_datahost
$_dataport
$_eol_code
$_error_array
$_errors
$_features
$_ftp_buff_size
$_ftp_control_sock
$_ftp_data_sock
$_ftp_temp_sock
$_fullhost
$_host
$_lastaction
$_login
$_message
$_passive
$_password
$_port
$_port_available
$_ready
$_timeout
$_type
$_umask
$AuthorizedTransferMode
$AutoAsciiExt
$LocalEcho
$OS_FullName
$OS_local
$OS_remote
$Verbose
Detailed Description
Definition at line 28 of file class-ftp-pure.php.
Constructor & Destructor Documentation
__construct ($verb = FALSE, $le = FALSE)
Definition at line 30 of file class-ftp-pure.php.
Referenced by ftp().
__construct ($verb = FALSE, $le = FALSE)
Definition at line 30 of file class-ftp-sockets.php.
Member Function Documentation
_connect ($host, $port)
Definition at line 51 of file class-ftp-pure.php.
References ftp_base\PushError(), and ftp_base\SendMSG().
_connect ($host, $port)
Definition at line 56 of file class-ftp-sockets.php.
References _settimeout(), ftp_base\PushError(), and ftp_base\SendMSG().
_data_close ()
Definition at line 175 of file class-ftp-pure.php.
References ftp_base\SendMSG().
Referenced by _data_prepare(), _data_read(), _data_write(), and _data_write_block().
_data_close ()
Definition at line 235 of file class-ftp-sockets.php.
References ftp_base\SendMSG().
_data_prepare ($mode = FTP_ASCII)
Definition at line 102 of file class-ftp-pure.php.
References ftp_base\$_ftp_data_sock, $mode, ftp_base\_checkCode(), _data_close(), _exec(), ftp_base\_settype(), ftp_base\PushError(), and ftp_base\SendMSG().
_data_prepare ($mode = FTP_ASCII)
Definition at line 113 of file class-ftp-sockets.php.
References ftp_base\$_ftp_data_sock, $mode, ftp_base\_checkCode(), _data_close(), _exec(), _settimeout(), ftp_base\_settype(), ftp_base\PushError(), ftp_base\SendMSG(), and str_replace.
_data_read ($mode = FTP_ASCII, $fp = NULL)
Definition at line 131 of file class-ftp-pure.php.
References $mode, $out, and ftp_base\SendMSG().
_data_read ($mode = FTP_ASCII, $fp = NULL)
Definition at line 177 of file class-ftp-sockets.php.
References $mode, ftp_base\$OS_local, $out, _data_close(), ftp_base\PushError(), and ftp_base\SendMSG().
_data_write ($mode = FTP_ASCII, $fp = NULL)
Definition at line 147 of file class-ftp-pure.php.
References $mode, $out, _data_write_block(), elseif, and ftp_base\SendMSG().
_data_write ($mode = FTP_ASCII, $fp = NULL)
Definition at line 200 of file class-ftp-sockets.php.
References $mode, ftp_base\$OS_local, $out, _data_close(), _data_write_block(), elseif, ftp_base\PushError(), and ftp_base\SendMSG().
_data_write_block ($mode, $block)
Definition at line 163 of file class-ftp-pure.php.
References $mode, and ftp_base\PushError().
Referenced by _data_write().
_data_write_block ($mode, $block)
Definition at line 222 of file class-ftp-sockets.php.
References $mode, _data_close(), and ftp_base\PushError().
_exec ($cmd, $fnction = "_exec")
Definition at line 86 of file class-ftp-pure.php.
References _readmsg(), and ftp_base\PushError().
Referenced by _data_prepare().
_exec ($cmd, $fnction = "_exec")
Definition at line 97 of file class-ftp-sockets.php.
References _readmsg(), and ftp_base\PushError().
_quit ($force = FALSE)
Definition at line 181 of file class-ftp-pure.php.
References ftp_base\SendMSG().
_quit ()
Definition at line 242 of file class-ftp-sockets.php.
References ftp_base\SendMSG().
Referenced by _settimeout().
_readmsg ($fnction = "_readmsg")
Definition at line 62 of file class-ftp-pure.php.
References ftp_base\PushError().
Referenced by _exec().
_readmsg ($fnction = "_readmsg")
Definition at line 73 of file class-ftp-sockets.php.
References ftp_base\PushError().
_settimeout ($sock)
Definition at line 42 of file class-ftp-sockets.php.
References ftp_base\PushError().
_settimeout ($sock)
Definition at line 42 of file class-ftp-pure.php.
References _quit(), and ftp_base\PushError().
Referenced by _connect(), and _data_prepare().
ftp ($verb = FALSE, $le = FALSE)
Definition at line 34 of file class-ftp-pure.php.
References __construct().
ftp ($verb = FALSE, $le = FALSE)
Definition at line 34 of file class-ftp-sockets.php.
References __construct().
The documentation for this class was generated from the following files:
class-ftp-pure.php
class-ftp-sockets.php