GravityView: GF_Fields Class Reference
GF_Fields Class Reference
Static Public Member Functions
static create ($properties)
static exists ($field_type)
static get ($field_type)
Alias for get_instance()
static get_all ()
static get_instance ($field_type)
static register ($field)
Static Public Attributes
static $deprecation_notice_fired = false
Static Private Attributes
static $_fields = array()
Detailed Description
Definition at line 9 of file class-gf-fields.php.
Member Function Documentation
static create ($properties) static
Parameters
$properties
Returns
GF_Field | bool
Definition at line 65 of file class-gf-fields.php.
References $class, and $field.
Referenced by GFForms\captcha_image(), GFFormsModel\convert_field_objects(), GVCommon\get_field_array(), GFFormsModel\get_field_value(), GFFormDisplay\get_honeypot_field(), GFFormsModel\get_label(), and GravityView_Edit_Entry_Render\maybe_update_post_fields().
static exists ($field_type) static
Definition at line 29 of file class-gf-fields.php.
static get ($field_type) static
Alias for get_instance()
Parameters
$field_type
Returns
GF_Field
Definition at line 49 of file class-gf-fields.php.
Referenced by GFAddOn\get_full_address(), and GFAddOn\get_full_name().
static get_all () static
Returns
GF_Field[]
Definition at line 56 of file class-gf-fields.php.
Referenced by output_field_scripts().
static get_instance ($field_type) static
Parameters
$field_type
Returns
GF_Field
Definition at line 38 of file class-gf-fields.php.
static register ($field) static
Definition at line 16 of file class-gf-fields.php.
References $field.
Field Documentation
$_fields = array() static private
Definition at line 14 of file class-gf-fields.php.
$deprecation_notice_fired = false static
Definition at line 11 of file class-gf-fields.php.
The documentation for this class was generated from the following file:
class-gf-fields.php