GravityView: ftp_base Class Reference
ftp_base Class Reference
PemFTP base class.
Public Member Functions
__construct ($port_mode=FALSE, $verb=FALSE, $le=FALSE)
_checkCode ()
_list ($arg="", $cmd="LIST", $fnction="_list")
_settype ($mode=FTP_ASCII)
abort ()
cdup ()
chdir ($pathname)
chmod ($pathname, $mode)
connect ($server=NULL)
delete ($pathname)
dirlist ($remote)
features ()
fget ($fp, $remotefile, $rest=0)
file_exists ($pathname)
filesize ($pathname)
fput ($remotefile, $fp)
ftp_base ($port_mode=FALSE)
get ($remotefile, $localfile=NULL, $rest=0)
glob ($pattern, $handle=NULL)
glob_pattern_match ($pattern, $string)
glob_regexp ($pattern, $probe)
is_exists ($pathname)
login ($user=NULL, $pass=NULL)
mdel ($remote, $continious=false)
mdtm ($pathname)
mget ($remote, $local=".", $continious=false)
mkdir ($pathname)
mmkdir ($dir, $mode=0777)
mput ($local=".", $remote=NULL, $continious=false)
nlist ($pathname="", $arg="")
parselisting ($line)
Passive ($pasv=NULL)
PopError ()
PushError ($fctname, $msg, $desc=false)
put ($localfile, $remotefile=NULL, $rest=0)
pwd ()
quit ($force=false)
rawlist ($pathname="", $arg="")
rename ($from, $to)
restore ($from)
rmdir ($pathname)
SendMSG ($message="", $crlf=true)
SetServer ($host, $port=21, $reconnect=true)
SetTimeout ($timeout=30)
SetType ($mode=FTP_AUTOASCII)
SetUmask ($umask=0022)
site ($command, $fnction="site")
systype ()
Data Fields
$_can_restore
$_code
$_connected
$_curtype
$_datahost
$_dataport
$_eol_code
$_error_array
$_errors
$_features
$_ftp_buff_size
$_ftp_control_sock
$_ftp_data_sock
$_ftp_temp_sock
$_fullhost
$_host
$_lastaction
$_login
$_message
$_passive
$_password
$_port
$_port_available
$_ready
$_timeout
$_type
$_umask
$AuthorizedTransferMode
$AutoAsciiExt
$LocalEcho
$OS_FullName
$OS_local
$OS_remote
$Verbose
Detailed Description
PemFTP base class.
Definition at line 83 of file class-ftp.php.
Constructor & Destructor Documentation
__construct ($port_mode = FALSE, $verb = FALSE, $le = FALSE)
Definition at line 124 of file class-ftp.php.
References elseif, features(), FTP_OS_Mac, FTP_OS_Unix, FTP_OS_Windows, Passive(), SendMSG(), SetTimeout(), SetType(), and SetUmask().
Referenced by ftp_base().
Member Function Documentation
_checkCode ()
Definition at line 850 of file class-ftp.php.
Referenced by ftp\_data_prepare(), _list(), abort(), cdup(), chdir(), connect(), delete(), features(), fget(), file_exists(), filesize(), fput(), get(), login(), mdtm(), mkdir(), put(), pwd(), quit(), rename(), restore(), rmdir(), site(), and systype().
_list ($arg = "", $cmd = "LIST", $fnction = "_list")
Definition at line 854 of file class-ftp.php.
References $out, and _checkCode().
Referenced by nlist(), and rawlist().
_settype ($mode = FTP_ASCII)
Definition at line 244 of file class-ftp.php.
References $mode, and elseif.
Referenced by ftp\_data_prepare().
abort ()
Definition at line 430 of file class-ftp.php.
References _checkCode().
Referenced by file_exists().
cdup ()
Definition at line 386 of file class-ftp.php.
References _checkCode().
chdir ($pathname)
Definition at line 392 of file class-ftp.php.
References _checkCode().
Referenced by WP_Filesystem_ftpsockets\chdir().
chmod ($pathname, $mode)
Definition at line 472 of file class-ftp.php.
References $mode, and site().
Referenced by WP_Filesystem_ftpsockets\chmod(), mget(), and mmkdir().
connect ($server = NULL)
Definition at line 319 of file class-ftp.php.
References _checkCode(), elseif, features(), FTP_OS_Mac, FTP_OS_Unix, FTP_OS_Windows, SendMSG(), SetServer(), and systype().
Referenced by WP_Filesystem_ftpsockets\connect(), and SetServer().
delete ($pathname)
Definition at line 460 of file class-ftp.php.
References _checkCode().
Referenced by WP_Filesystem_ftpsockets\delete().
dirlist ($remote)
Definition at line 826 of file class-ftp.php.
References $list, parselisting(), PushError(), and rawlist().
Referenced by WP_Filesystem_ftpsockets\dirlist().
features ()
Definition at line 491 of file class-ftp.php.
References _checkCode().
Referenced by __construct(), connect(), and login().
fget ($fp, $remotefile, $rest = 0)
Definition at line 527 of file class-ftp.php.
References $mode, $out, _checkCode(), and restore().
Referenced by WP_Filesystem_ftpsockets\get_contents().
file_exists ($pathname)
Definition at line 515 of file class-ftp.php.
References _checkCode(), abort(), and SendMSG().
Referenced by get(), is_exists(), mget(), mput(), and put().
filesize ($pathname)
Definition at line 420 of file class-ftp.php.
References _checkCode(), and PushError().
Referenced by WP_Filesystem_ftpsockets\size().
fput ($remotefile, $fp)
Definition at line 586 of file class-ftp.php.
References $mode, _checkCode(), and restore().
Referenced by WP_Filesystem_ftpsockets\put_contents().
ftp_base ($port_mode = FALSE)
Definition at line 156 of file class-ftp.php.
References __construct().
get ($remotefile, $localfile = NULL, $rest = 0)
Definition at line 551 of file class-ftp.php.
References $mode, $out, _checkCode(), file_exists(), PushError(), restore(), and SendMSG().
glob ($pattern, $handle = NULL)
Definition at line 768 of file class-ftp.php.
References $dir, $output, $path, glob_pattern_match(), and null.
glob_pattern_match ($pattern, $string)
Definition at line 795 of file class-ftp.php.
References $out, glob_regexp(), null, and str_replace.
Referenced by glob().
glob_regexp ($pattern, $probe)
Definition at line 818 of file class-ftp.php.
Referenced by glob_pattern_match().
is_exists ($pathname)
Definition at line 511 of file class-ftp.php.
References file_exists().
Referenced by mmkdir().
login ($user = NULL, $pass = NULL)
Definition at line 361 of file class-ftp.php.
References $user, _checkCode(), features(), and SendMSG().
Referenced by WP_Filesystem_ftpsockets\connect().
mdel ($remote, $continious = false)
Definition at line 721 of file class-ftp.php.
References $list, parselisting(), PushError(), rawlist(), and rmdir().
Referenced by WP_Filesystem_ftpsockets\delete().
mdtm ($pathname)
Definition at line 440 of file class-ftp.php.
References _checkCode(), and PushError().
Referenced by WP_Filesystem_ftpsockets\mtime().
mget ($remote, $local = ".", $continious = false)
Definition at line 682 of file class-ftp.php.
References $list, chmod(), file_exists(), mkdir(), parselisting(), PushError(), and rawlist().
mkdir ($pathname)
Definition at line 404 of file class-ftp.php.
References _checkCode().
Referenced by mget(), WP_Filesystem_ftpsockets\mkdir(), mmkdir(), and mput().
mmkdir ($dir, $mode = 0777)
Definition at line 759 of file class-ftp.php.
References $dir, $mode, chmod(), is_exists(), and mkdir().
mput ($local = ".", $remote = NULL, $continious = false)
Definition at line 649 of file class-ftp.php.
References $file, $list, elseif, file_exists(), mkdir(), PushError(), and put().
nlist ($pathname = "", $arg = "")
Definition at line 507 of file class-ftp.php.
References _list().
Referenced by WP_Filesystem_ftpsockets\exists().
parselisting ($line)
Definition at line 164 of file class-ftp.php.
References date, elseif, and FTP_OS_Windows.
Referenced by dirlist(), mdel(), and mget().
Passive ($pasv = NULL)
Definition at line 259 of file class-ftp.php.
References $_passive, and SendMSG().
Referenced by __construct(), and WP_Filesystem_ftpsockets\connect().
PopError ()
Definition at line 893 of file class-ftp.php.
PushError ($fctname, $msg, $desc = false)
Definition at line 881 of file class-ftp.php.
References $msg, and SendMSG().
Referenced by ftp\_connect(), ftp\_data_prepare(), ftp\_data_read(), ftp\_data_write(), ftp\_data_write_block(), ftp\_exec(), ftp\_readmsg(), ftp\_settimeout(), dirlist(), filesize(), get(), mdel(), mdtm(), mget(), mput(), put(), and restore().
put ($localfile, $remotefile = NULL, $rest = 0)
Definition at line 610 of file class-ftp.php.
References $mode, _checkCode(), file_exists(), PushError(), and restore().
Referenced by mput().
pwd ()
Definition at line 380 of file class-ftp.php.
References _checkCode().
Referenced by WP_Filesystem_ftpsockets\cwd().
quit ($force = false)
Definition at line 350 of file class-ftp.php.
References _checkCode(), and SendMSG().
Referenced by WP_Filesystem_ftpsockets\__destruct(), and SetServer().
rawlist ($pathname = "", $arg = "")
Definition at line 503 of file class-ftp.php.
References _list().
Referenced by dirlist(), mdel(), and mget().
rename ($from, $to)
Definition at line 410 of file class-ftp.php.
References $from, and _checkCode().
Referenced by WP_Filesystem_ftpsockets\move().
restore ($from)
Definition at line 477 of file class-ftp.php.
References $from, _checkCode(), and PushError().
Referenced by fget(), fput(), get(), and put().
rmdir ($pathname)
Definition at line 398 of file class-ftp.php.
References _checkCode().
Referenced by WP_Filesystem_ftpsockets\delete(), and mdel().
SendMSG ($message = "", $crlf = true)
Definition at line 226 of file class-ftp.php.
References $message.
Referenced by __construct(), ftp\_connect(), ftp\_data_close(), ftp\_data_prepare(), ftp\_data_read(), ftp\_data_write(), ftp\_quit(), connect(), file_exists(), get(), login(), Passive(), PushError(), quit(), SetServer(), SetTimeout(), SetType(), and SetUmask().
SetServer ($host, $port = 21, $reconnect = true)
Definition at line 271 of file class-ftp.php.
References connect(), quit(), and SendMSG().
Referenced by WP_Filesystem_ftpsockets\connect(), and connect().
SetTimeout ($timeout = 30)
Definition at line 311 of file class-ftp.php.
References SendMSG().
Referenced by __construct().
SetType ($mode = FTP_AUTOASCII)
Definition at line 234 of file class-ftp.php.
References $mode, and SendMSG().
Referenced by __construct(), and WP_Filesystem_ftpsockets\connect().
SetUmask ($umask = 0022)
Definition at line 304 of file class-ftp.php.
References SendMSG().
Referenced by __construct().
site ($command, $fnction = "site")
Definition at line 466 of file class-ftp.php.
References _checkCode().
Referenced by chmod().
systype ()
Definition at line 453 of file class-ftp.php.
References _checkCode().
Referenced by connect().
Field Documentation
$_can_restore
Definition at line 112 of file class-ftp.php.
$_code
Definition at line 110 of file class-ftp.php.
$_connected
Definition at line 108 of file class-ftp.php.
$_curtype
Definition at line 114 of file class-ftp.php.
$_datahost
Definition at line 100 of file class-ftp.php.
$_dataport
Definition at line 101 of file class-ftp.php.
$_eol_code
Definition at line 120 of file class-ftp.php.
$_error_array
Definition at line 117 of file class-ftp.php.
$_errors
Definition at line 92 of file class-ftp.php.
$_features
Definition at line 115 of file class-ftp.php.
$_ftp_buff_size
Definition at line 105 of file class-ftp.php.
$_ftp_control_sock
Definition at line 102 of file class-ftp.php.
$_ftp_data_sock
Definition at line 103 of file class-ftp.php.
Referenced by ftp\_data_prepare().
$_ftp_temp_sock
Definition at line 104 of file class-ftp.php.
$_fullhost
Definition at line 98 of file class-ftp.php.
$_host
Definition at line 97 of file class-ftp.php.
$_lastaction
Definition at line 91 of file class-ftp.php.
$_login
Definition at line 106 of file class-ftp.php.
$_message
Definition at line 111 of file class-ftp.php.
$_passive
Definition at line 96 of file class-ftp.php.
Referenced by Passive().
$_password
Definition at line 107 of file class-ftp.php.
$_port
Definition at line 99 of file class-ftp.php.
$_port_available
Definition at line 113 of file class-ftp.php.
$_ready
Definition at line 109 of file class-ftp.php.
$_timeout
Definition at line 95 of file class-ftp.php.
$_type
Definition at line 93 of file class-ftp.php.
$_umask
Definition at line 94 of file class-ftp.php.
$AuthorizedTransferMode
Definition at line 118 of file class-ftp.php.
$AutoAsciiExt
Definition at line 121 of file class-ftp.php.
$LocalEcho
Definition at line 85 of file class-ftp.php.
$OS_FullName
Definition at line 119 of file class-ftp.php.
$OS_local
Definition at line 87 of file class-ftp.php.
Referenced by ftp\_data_read(), and ftp\_data_write().
$OS_remote
Definition at line 88 of file class-ftp.php.
$Verbose
Definition at line 86 of file class-ftp.php.
The documentation for this class was generated from the following file:
class-ftp.php