GravityView: GravityView_Plugin_Hooks_Gravity_Forms_Coupon Class Reference
GravityView_Plugin_Hooks_Gravity_Forms_Coupon Class Reference
Public Member Functions
edit_entry_field_blacklist ($blacklist=array(), $entry=array())
Adds Coupon fields to Edit Entry field blacklist.
edit_entry_field_value ($value, $field, $Edit_Entry_Render)
Set the coupon values for entries that have coupons applied.
should_hide_coupon_fields ($entry=array())
Should Coupon fields be hidden in Edit Entry?
Public Member Functions inherited from GravityView_Plugin_and_Theme_Hooks
__construct ()
GravityView_Theme_Support constructor.
_wp_loaded ()
Fired when all themes and plugins have been loaded.
merge_content_meta_keys ($meta_keys=array(), $post=null, & $views=null)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_meta_keys ($meta_keys=array(), $post_id=0)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_noconflict_scripts ($handles)
Merge plugin or theme scripts with existing no-conflict scripts.
merge_noconflict_styles ($handles)
Merge plugin or theme styles with existing no-conflict styles.
merge_post_type_support ($supports=array(), $is_hierarchical=false)
Merge plugin or theme post type support definitions with existing support values.
Protected Member Functions
add_hooks ()
Protected Member Functions inherited from GravityView_Plugin_and_Theme_Hooks
add_hooks ()
Add filters for meta key and script/style handles, if defined.
Protected Attributes
$function_name = 'gf_coupons'
Protected Attributes inherited from GravityView_Plugin_and_Theme_Hooks
$class_name = false
string Optional.
$constant_name = false
string Optional.
$content_meta_keys = array()
Define the keys to be parsed by the gravityview/view_collection/from_post/meta_keys hook.
$function_name = false
string Optional.
$meta_keys = array()
Define the keys to be parsed by the gravityview/data/parse/meta_keys hook.
$post_type_support = array()
Define features in the admin editor used by the theme or plugin to be used when registering the GravityView post type.
$script_handles = array()
Define script handles used by the theme or plugin to be added to allowed no-conflict scripts.
$style_handles = array()
Define style handles used by the theme or plugin to be added to allowed no-conflict styles.
Detailed Description
Since
1.20
Definition at line 18 of file class-gravityview-plugin-hooks-gravity-forms-coupon.php.
Member Function Documentation
add_hooks()
add_hooks () protected
Since
1.20
Definition at line 29 of file class-gravityview-plugin-hooks-gravity-forms-coupon.php.
edit_entry_field_blacklist()
edit_entry_field_blacklist ($blacklist = array(), $entry = array())
Adds Coupon fields to Edit Entry field blacklist.
Since
1.20
Parameters
array $blacklist Array of field types
array $entry Entry array of entry being edited in Edit Entry
Returns
array Blacklist array, with coupon possibly added
Definition at line 69 of file class-gravityview-plugin-hooks-gravity-forms-coupon.php.
References $entry, and should_hide_coupon_fields().
edit_entry_field_value()
edit_entry_field_value ($value, $field, $Edit_Entry_Render)
Set the coupon values for entries that have coupons applied.
Uses $_POST hacks
Since
1.20
Parameters
string $value
GF_Field_Coupon $field
GravityView_Edit_Entry_Render $Edit_Entry_Render
Returns
string $value is returned unmodified. Only $_POST is modified.
Fake POST data so that the data gets pre-filled. Both are needed.
See also
GF_Field_Coupon::get_field_input
Definition at line 91 of file class-gravityview-plugin-hooks-gravity-forms-coupon.php.
References $entry, $field, GV\$form, $value, and should_hide_coupon_fields().
should_hide_coupon_fields()
should_hide_coupon_fields ($entry = array())
Should Coupon fields be hidden in Edit Entry?
Since
1.20
Parameters
array $entry Entry being edited in Edit Entry, if set
Returns
bool True: Yes, show coupon fields in Edit Entry; False: no, don't show Coupon fields
Runs Filter:
gravityview/edit_entry/hide-coupon-fields Should Coupon fields be hidden in Edit Entry?
Since
1.20
Parameters
bool $has_transaction_data If true (the Entry has transaction data), hide the fields. Otherwise (false), show the Coupon field
Definition at line 45 of file class-gravityview-plugin-hooks-gravity-forms-coupon.php.
References $entry, and GVCommon\entry_has_transaction_data().
Referenced by edit_entry_field_blacklist(), and edit_entry_field_value().
Field Documentation
$function_name
$function_name = 'gf_coupons' protected
Definition at line 24 of file class-gravityview-plugin-hooks-gravity-forms-coupon.php.
The documentation for this class was generated from the following file:
class-gravityview-plugin-hooks-gravity-forms-coupon.php