GravityView: PasswordHash Class Reference
PasswordHash Class Reference
Public Member Functions
__construct ($iteration_count_log2, $portable_hashes)
PHP5 constructor.
CheckPassword ($password, $stored_hash)
crypt_private ($password, $setting)
encode64 ($input, $count)
gensalt_blowfish ($input)
gensalt_extended ($input)
gensalt_private ($input)
get_random_bytes ($count)
HashPassword ($password)
PasswordHash ($iteration_count_log2, $portable_hashes)
PHP4 constructor.
Data Fields
$iteration_count_log2
$itoa64
$portable_hashes
$random_state
Detailed Description
Definition at line 36 of file class-phpass.php.
Constructor & Destructor Documentation
__construct ($iteration_count_log2, $portable_hashes)
PHP5 constructor.
Definition at line 45 of file class-phpass.php.
References $iteration_count_log2, and $portable_hashes.
Member Function Documentation
CheckPassword ($password, $stored_hash)
Definition at line 264 of file class-phpass.php.
References crypt_private().
crypt_private ($password, $setting)
Definition at line 121 of file class-phpass.php.
References $count, $id, $output, and encode64().
Referenced by CheckPassword(), and HashPassword().
encode64 ($input, $count)
Definition at line 88 of file class-phpass.php.
References $count, $i, $output, and $value.
Referenced by crypt_private(), gensalt_extended(), and gensalt_private().
gensalt_blowfish ($input)
Definition at line 184 of file class-phpass.php.
References $i, and $output.
Referenced by HashPassword().
gensalt_extended ($input)
Definition at line 166 of file class-phpass.php.
References $count, $output, and encode64().
Referenced by HashPassword().
gensalt_private ($input)
Definition at line 111 of file class-phpass.php.
References $output, and encode64().
Referenced by HashPassword().
get_random_bytes ($count)
Definition at line 65 of file class-phpass.php.
References $count, $i, and $output.
Referenced by HashPassword().
HashPassword ($password)
Definition at line 225 of file class-phpass.php.
References crypt_private(), gensalt_blowfish(), gensalt_extended(), gensalt_private(), and get_random_bytes().
PasswordHash ($iteration_count_log2, $portable_hashes)
PHP4 constructor.
Definition at line 61 of file class-phpass.php.
Field Documentation
$iteration_count_log2
Definition at line 38 of file class-phpass.php.
Referenced by __construct().
$itoa64
Definition at line 37 of file class-phpass.php.
$portable_hashes
Definition at line 39 of file class-phpass.php.
Referenced by __construct().
$random_state
Definition at line 40 of file class-phpass.php.
The documentation for this class was generated from the following file:
class-phpass.php