GravityView: GFEntryDetail Class Reference
GFEntryDetail Class Reference
Static Public Member Functions
static entry_detail_pagination_link ($pos, $label= '', $class= '', $icon= '')
static lead_detail_edit ($form, $lead)
static lead_detail_grid ($form, $lead, $allow_display_empty_fields=false)
static lead_detail_page ()
static notes_grid ($notes, $is_editable, $emails=null, $subject= '')
static payment_details_box ($lead, $form)
Detailed Description
Definition at line 7 of file entry_detail.php.
Member Function Documentation
static entry_detail_pagination_link ($pos, $label = '', $class = '', $icon = '') static
Definition at line 1092 of file entry_detail.php.
References $class, $href, $label, $url, add_query_arg(), esc_attr(), esc_url, and remove_query_arg().
Referenced by lead_detail_page().
static lead_detail_edit ($form, $lead) static
Definition at line 704 of file entry_detail.php.
References $content, $field, $field_id, $form, $form_id, $value, absint(), apply_filters(), esc_attr(), esc_html, esc_html_e, GFFormsModel\get_lead_field_value(), input, label, and name.
static lead_detail_grid ($form, $lead, $allow_display_empty_fields = false) static
A filter to set if empty fields shown be shown in the entry details
Parameters
bool $display_empty_fields True or false to show the fields
array $form The Form object to filter
array $lead The Lead object to filter
Definition at line 890 of file entry_detail.php.
References $_COOKIE, $class, $content, $count, $field, $form, $form_id, $option, $title, $value, __, absint(), apply_filters(), esc_html, esc_html__(), esc_html_e, GFFormsModel\get_lead_field_value(), input, label, li, and width.
Referenced by gform_default_entry_content().
static lead_detail_page () static
Allow the entry list search criteria to be overridden.
Since
1.9.14.30
Parameters
array $search_criteria An array containing the search criteria.
int $form_id The ID of the current form.
Fires after the Entry is updated from the entry detail page.
Parameters
array $form The form object for the entry.
integer $lead,['id'] The entry ID.
array $original_entry The entry object before being updated.
Fires after a note is attached to an entry and sent as an email
Parameters
string $result The Error message or success message when the entry note is sent
string $email_to The email address to send the entry note to
string $email_from The email address from which the email is sent from
string $email_subject The subject of the email that is sent
mixed $body The Full body of the email containing the message after the note is sent
array $form The current form object
array $lead The Current lead object
Filters through a form payment status and allows modification
Parameters
string $lead,['payment_status] A payment status to filter though
array $form The Form Object to filter through
array $lead The Lead Object to filter through
A filter to allow the modification of the button to update an entry detail
Parameters
string $update_button The HTML Rendered for the Entry Detail update button
A filter to enable or disable the extra payment details box in an entry
Parameters
bool To enable (true) or disable (false)
array $lead The Lead object to filter
Definition at line 9 of file entry_detail.php.
References $current_user, $form, $form_id, $leads, $min, $mode, $post, GFFormsModel\$uploaded_files, $visiblePreviewFields, __, absint(), GFFormsModel\add_note(), apply_filters(), checked(), GFFormsModel\delete_lead(), GFFormsModel\delete_notes(), do_action(), entry_detail_pagination_link(), esc_attr(), esc_attr__(), esc_html, esc_html__(), esc_html_e, GFAPI\get_entries(), GFAPI\get_entry(), GFFormsModel\get_field(), GFEntryList\get_filter_links(), GFFormsModel\get_form_meta(), GFFormsModel\get_lead(), GFFormsModel\get_lead_notes(), get_post(), gform_tooltip(), has_filter(), input, is_wp_error(), label, li, name, page, GFForms\post(), rr, GFFormsModel\save_lead(), selected(), GFFormsModel\set_entry_meta(), GFForms\top_toolbar(), GFFormsModel\update_lead_property(), and wp_nonce_field().
Referenced by GFForms\all_leads_page(), and GFForms\forms().
static notes_grid ($notes, $is_editable, $emails = null, $subject = '') static
A filter to allow you to modify the note apply button
Parameters
string $apply_button The Apply Button HTML
Allows filtering of the notes avatar
Parameters
array $note The Note object that is being filtered when modifying the avatar
Allows for modification of the "Add Note" button for Entry Notes
Parameters
string $note_button The HTML for the "Add Note" Button
Definition at line 768 of file entry_detail.php.
References $class, $count, apply_filters(), esc_attr__(), esc_html, esc_html_e, input, label, name, and textarea.
Referenced by gform_default_entry_content().
static payment_details_box ($lead, $form) static
Allows for modification on the form payment date format
Parameters
array $form The Form object to filter through
array $lead The Lead object to filter through
Allows filtering through a payment transaction ID
Parameters
int $lead,['transaction_id'] The transaction ID that can be modified
array $form The Form object to be filtered when modifying the transaction ID
array $lead The Lead object to be filtered when modifying the transaction ID
Filter through the way the Payment Amount is rendered
Parameters
string $lead,['payment_amount'] The payment amount taken from the lead object
string $lead,['currency'] The payment currency taken from the lead object
array $form The Form onject to filter through
array $lead The lead object to filter through
Fires after the Form Payment Details (The type of payment, the cost, the ID, etc)
Parameters
int $form,['id'] The current Form ID
array $lead The current Lead object
Definition at line 1102 of file entry_detail.php.
References $form, apply_filters(), do_action(), esc_html__(), and esc_html_e.
The documentation for this class was generated from the following file:
entry_detail.php