GravityView: GVCommon_Test Class Reference
GVCommon_Test Class Reference
gvcommon
Public Member Functions
_filter_test_get_link_html ($allowed_atts)
test_format_date ()
test_get_connected_views ()
GVCommon::get_connected_views gravityview_get_connected_views()
test_get_forms ()
get_forms GVCommon::get_forms() gravityview_get_forms()
test_get_link_html ()
link_html gravityview_get_link() GVCommon::get_link_html
test_get_meta_form_id ()
GVCommon::get_meta_form_id gravityview_get_form_id()
test_get_meta_template_id ()
GVCommon::get_meta_template_id gravityview_get_template_id()
test_has_gravityview_shortcode ()
GVCommon::has_gravityview_shortcode()
test_has_shortcode_r ()
GVCommon::has_shortcode_r has_shortcode
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
gvcommon
Definition at line 8 of file GVCommon_Common_Test.php.
Member Function Documentation
_filter_test_get_link_html ($allowed_atts)
Definition at line 189 of file GVCommon_Common_Test.php.
test_format_date ()
Since
1.16 GravityView_Field_Date_Created::replace_merge_tag GVCommon::format_date date_created
adjusting date to local configured Time Zone
See also
GFCommon::format_date()
Definition at line 31 of file GVCommon_Common_Test.php.
References $entry, $form, and GVCommon\format_date().
test_get_connected_views ()
GVCommon::get_connected_views gravityview_get_connected_views()
Definition at line 127 of file GVCommon_Common_Test.php.
References $form_id, and GVCommon\get_connected_views().
test_get_forms ()
get_forms GVCommon::get_forms() gravityview_get_forms()
Definition at line 105 of file GVCommon_Common_Test.php.
References $forms, and GVCommon\get_forms().
test_get_link_html ()
link_html gravityview_get_link() GVCommon::get_link_html
Definition at line 171 of file GVCommon_Common_Test.php.
References $href, and GVCommon\get_link_html().
test_get_meta_form_id ()
GVCommon::get_meta_form_id gravityview_get_form_id()
Definition at line 142 of file GVCommon_Common_Test.php.
References $form_id, $view_id, and GVCommon\get_meta_form_id().
test_get_meta_template_id ()
GVCommon::get_meta_template_id gravityview_get_template_id()
Definition at line 154 of file GVCommon_Common_Test.php.
References $form_id, $view_id, and GVCommon\get_meta_template_id().
test_has_gravityview_shortcode ()
GVCommon::has_gravityview_shortcode()
Definition at line 14 of file GVCommon_Common_Test.php.
References GVCommon\has_gravityview_shortcode().
test_has_shortcode_r ()
GVCommon::has_shortcode_r has_shortcode
Definition at line 198 of file GVCommon_Common_Test.php.
References GVCommon\has_shortcode_r().
The documentation for this class was generated from the following file:
GVCommon_Common_Test.php