GravityView: WP_Tax_Query Class Reference
WP_Tax_Query Class Reference
Core class used to implement taxonomy queries for the Taxonomy API.
Public Member Functions
__construct ($tax_query)
Constructor.
get_sql_for_clause (&$clause, $parent_query)
Generate SQL JOIN and WHERE clauses for a "first-order" query clause.
sanitize_query ($queries)
Ensure the 'tax_query' argument passed to the class constructor is well-formed.
sanitize_relation ($relation)
Sanitize a 'relation' operator.
transform_query (&$query, $resulting_field)
Transforms a single query, from one field to another.
Static Public Member Functions
get_sql ($primary_table, $primary_id_column)
Generates SQL clauses to be appended to a main query.
Data Fields
$primary_id_column
$primary_table
$queried_terms = array()
$queries = array()
$relation
Protected Member Functions
find_compatible_table_alias ($clause, $parent_query)
Identify an existing table alias that is compatible with the current query clause.
get_sql_clauses ()
Generate SQL clauses to be appended to a main query.
get_sql_for_query (&$query, $depth=0)
Generate SQL clauses for a single query array.
Static Protected Member Functions
static is_first_order_clause ($query)
Determine whether a clause is first-order.
Protected Attributes
$table_aliases = array()
Private Member Functions
clean_query (&$query)
Validates a single query.
Static Private Attributes
static $no_results = array('join' => array(''), 'where' => array('0 = 1'))
Detailed Description
Core class used to implement taxonomy queries for the Taxonomy API.
Used for generating SQL clauses that filter a primary query according to object taxonomy terms.
WP_Tax_Query is a helper that allows primary query classes, such as WP_Query, to filter their results by object metadata, by generating JOIN and WHERE subclauses to be attached to the primary SQL query string.
Since
3.1.0
Definition at line 22 of file class-wp-tax-query.php.
Constructor & Destructor Documentation
__construct ($tax_query)
Constructor.
Since
3.1.0
4.1.0 Added support for $operator 'NOT EXISTS' and 'EXISTS' values. public
Parameters
array $tax_query { Array of taxonomy query clauses.
string $relation Optional. The MySQL keyword used to join the clauses of the query. Accepts 'AND', or 'OR'. Default 'AND'. array { Optional. An array of first-order clause parameters, or another fully-formed tax query.
string $taxonomy Taxonomy being queried. Optional when field=term_taxonomy_id. string|int|array $terms Term or terms to filter by. string $field Field to match $terms against. Accepts 'term_id', 'slug', 'name', or 'term_taxonomy_id'. Default: 'term_id'. string $operator MySQL operator to be used with $terms in the WHERE clause. Accepts 'AND', 'IN', 'NOT IN', 'EXISTS', 'NOT EXISTS'. Default: 'IN'. bool $include_children Optional. Whether to include child terms. Requires a $taxonomy. Default: true. } }
Definition at line 121 of file class-wp-tax-query.php.
References sanitize_query(), and sanitize_relation().
Member Function Documentation
clean_query (& $query) private
Validates a single query.
Since
3.2.0 private
Parameters
array $query The single query. Passed by reference.
Definition at line 562 of file class-wp-tax-query.php.
References elseif, get_term_children(), is_taxonomy_hierarchical(), is_wp_error(), taxonomy_exists(), and transform_query().
Referenced by get_sql_for_clause().
find_compatible_table_alias ($clause, $parent_query) protected
Identify an existing table alias that is compatible with the current query clause.
We avoid unnecessary table joins by allowing each clause to look for an existing table alias that is compatible with the query that it needs to perform.
An existing alias is compatible if (a) it is a sibling of $clause (ie, it's under the scope of the same relation), and (b) the combination of operator and relation between the clauses allows for a shared table join. In the case of WP_Tax_Query, this only applies to 'IN' clauses that are connected by the relation 'OR'.
Since
4.1.0 protected
Parameters
array $clause Query clause.
array $parent_query Parent query of $clause.
Returns
string|false Table alias if found, otherwise false.
Definition at line 520 of file class-wp-tax-query.php.
References is_first_order_clause().
Referenced by get_sql_for_clause().
get_sql ($primary_table, $primary_id_column) static
Generates SQL clauses to be appended to a main query.
Since
3.1.0
public
Parameters
string $primary_table Database table where the object being filtered is stored (eg wp_users).
string $primary_id_column ID column for the filtered object in $primary_table.
Returns
array { Array containing JOIN and WHERE SQL clauses to append to the main query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 261 of file class-wp-tax-query.php.
References $primary_id_column, $primary_table, and get_sql_clauses().
get_sql_clauses () protected
Generate SQL clauses to be appended to a main query.
Called by the public WP_Tax_Query::get_sql(), this method is abstracted out to maintain parity with the other Query classes.
Since
4.1.0 protected
Returns
array { Array containing JOIN and WHERE SQL clauses to append to the main query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 284 of file class-wp-tax-query.php.
References $queries, and get_sql_for_query().
Referenced by get_sql().
get_sql_for_clause (& $clause, $parent_query)
Generate SQL JOIN and WHERE clauses for a "first-order" query clause.
Since
4.1.0 public
wpdb $wpdb The WordPress database abstraction object.
Parameters
array $clause Query clause, passed by reference.
array $parent_query Parent query array.
Returns
array { Array containing JOIN and WHERE SQL clauses to append to a first-order query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 401 of file class-wp-tax-query.php.
References $i, $wpdb, clean_query(), elseif, find_compatible_table_alias(), and is_wp_error().
Referenced by get_sql_for_query().
get_sql_for_query (& $query, $depth = 0) protected
Generate SQL clauses for a single query array.
If nested subqueries are found, this method recurses the tree to produce the properly nested SQL.
Since
4.1.0 protected
Parameters
array $query Query to parse, passed by reference.
int $depth Optional. Number of tree levels deep we currently are. Used to calculate indentation. Default 0.
Returns
array { Array containing JOIN and WHERE SQL clauses to append to a single query array.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 318 of file class-wp-tax-query.php.
References $i, $relation, elseif, get_sql_for_clause(), and is_first_order_clause().
Referenced by get_sql_clauses().
static is_first_order_clause ($query) static protected
Determine whether a clause is first-order.
A "first-order" clause is one that contains any of the first-order clause keys ('terms', 'taxonomy', 'include_children', 'field', 'operator'). An empty clause also counts as a first-order clause, for backward compatibility. Any clause that doesn't meet this is determined, by process of elimination, to be a higher-order query.
Since
4.1.0
protected
Parameters
array $query Tax query arguments.
Returns
bool Whether the query clause is a first-order clause.
Definition at line 240 of file class-wp-tax-query.php.
Referenced by find_compatible_table_alias(), and get_sql_for_query().
sanitize_query ($queries)
Ensure the 'tax_query' argument passed to the class constructor is well-formed.
Ensures that each query-level clause has a 'relation' key, and that each first-order clause contains all the necessary keys from $defaults.
Since
4.1.0 public
Parameters
array $queries Array of queries clauses.
Returns
array Sanitized array of query clauses.
Definition at line 143 of file class-wp-tax-query.php.
References $queries, elseif, and sanitize_relation().
Referenced by __construct().
sanitize_relation ($relation)
Sanitize a 'relation' operator.
Since
4.1.0 public
Parameters
string $relation Raw relation key from the query argument.
Returns
string Sanitized relation ('AND' or 'OR').
Definition at line 215 of file class-wp-tax-query.php.
References $relation.
Referenced by __construct(), and sanitize_query().
transform_query (& $query, $resulting_field)
Transforms a single query, from one field to another.
Since
3.2.0
wpdb $wpdb The WordPress database abstraction object.
Parameters
array $query The single query. Passed by reference.
string $resulting_field The resulting field. Accepts 'slug', 'name', 'term_taxonomy_id', or 'term_id'. Default 'term_id'.
Definition at line 606 of file class-wp-tax-query.php.
References $wpdb, esc_sql(), sanitize_key(), and sanitize_term_field().
Referenced by clean_query().
Field Documentation
$no_results = array('join' => array(''), 'where' => array('0 = 1')) static private
Definition at line 53 of file class-wp-tax-query.php.
$primary_id_column
Definition at line 92 of file class-wp-tax-query.php.
Referenced by get_sql().
$primary_table
Definition at line 83 of file class-wp-tax-query.php.
Referenced by get_sql().
$queried_terms = array()
Definition at line 74 of file class-wp-tax-query.php.
$queries = array()
Definition at line 33 of file class-wp-tax-query.php.
Referenced by get_sql_clauses(), and sanitize_query().
$relation
Definition at line 42 of file class-wp-tax-query.php.
Referenced by get_sql_for_query(), and sanitize_relation().
$table_aliases = array() protected
Definition at line 62 of file class-wp-tax-query.php.
The documentation for this class was generated from the following file:
class-wp-tax-query.php