GravityView: PluginActivationHandler Class Reference
PluginActivationHandler Class Reference
This class is responsible for handling plugin activation and deactivation hooks.
Public Member Functions
fire_activation_hook ()
Runs on plugin activation.
get_plugin_activations ()
Returns activated plugins.
register_activation_hook ($plugin_file)
Registers activation hook for the plugin.
register_deactivation_hook ($plugin_file)
Registers deactivation hook for the plugin.
register_hooks ($plugin_file)
Registers activation and deactivation hooks for the plugin.
save_plugin_activations ($plugin_activations)
Saves activated plugins.
Data Fields
const DB_OPTION_NAME = '_gk_foundation_plugin_activations'
Detailed Description
This class is responsible for handling plugin activation and deactivation hooks.
Definition at line 14 of file PluginActivationHandler.php.
Member Function Documentation
fire_activation_hook()
fire_activation_hook ()
Runs on plugin activation.
This method can be called inside init and other WP hooks.
Since
1.0.0
Returns
void
Definition at line 128 of file PluginActivationHandler.php.
References GV\$i, PluginActivationHandler\get_plugin_activations(), and PluginActivationHandler\save_plugin_activations().
get_plugin_activations()
get_plugin_activations ()
Returns activated plugins.
Since
1.0.0
Returns
array
Definition at line 115 of file PluginActivationHandler.php.
Referenced by PluginActivationHandler\fire_activation_hook(), and PluginActivationHandler\register_activation_hook().
register_activation_hook()
register_activation_hook ($plugin_file)
Registers activation hook for the plugin.
Note: this method should not be called inside a hook such as init, plugins_loaded, etc.
See also
https://developer.wordpress.org/reference/functions/register_activation_hook/#more-information
Since
1.0.0
Parameters
string $plugin_file The filename of the plugin including the path.
Returns
void
Definition at line 48 of file PluginActivationHandler.php.
References PluginActivationHandler\get_plugin_activations(), and PluginActivationHandler\save_plugin_activations().
Referenced by PluginActivationHandler\register_hooks().
register_deactivation_hook()
register_deactivation_hook ($plugin_file)
Registers deactivation hook for the plugin.
Note: this method should not be called inside a hook such as init, plugins_loaded, etc.
See also
https://developer.wordpress.org/reference/functions/register_activation_hook/#more-information
Since
1.0.0
Parameters
string $plugin_file The filename of the plugin including the path.
Returns
void
Definition at line 79 of file PluginActivationHandler.php.
Referenced by PluginActivationHandler\register_hooks().
register_hooks()
register_hooks ($plugin_file)
Registers activation and deactivation hooks for the plugin.
Note: this method should not be called inside a hook such as init, plugins_loaded, etc.
See also
https://developer.wordpress.org/reference/functions/register_activation_hook/#more-information
Since
1.0.0
Parameters
string $plugin_file The filename of the plugin including the path.
Returns
void
Definition at line 30 of file PluginActivationHandler.php.
References PluginActivationHandler\register_activation_hook(), and PluginActivationHandler\register_deactivation_hook().
save_plugin_activations()
save_plugin_activations ($plugin_activations)
Saves activated plugins.
Since
1.0.0
Parameters
array $plugin_activations Activated plugins.
Returns
void
Definition at line 100 of file PluginActivationHandler.php.
Referenced by PluginActivationHandler\fire_activation_hook(), and PluginActivationHandler\register_activation_hook().
Field Documentation
DB_OPTION_NAME
const DB_OPTION_NAME = '_gk_foundation_plugin_activations'
Definition at line 15 of file PluginActivationHandler.php.
The documentation for this class was generated from the following file:
PluginActivationHandler.php