GravityView: LoggerInterfaceTest Class Reference
LoggerInterfaceTest Class Reference
Provides a base test class for ensuring compliance with the LoggerInterface.
Public Member Functions
getLogger ()
getLogs ()
This must return the log messages in order.
provideLevelsAndMessages ()
testContextCanContainAnything ()
testContextExceptionKeyCanBeExceptionOrOtherValues ()
testContextReplacement ()
testImplements ()
testLogsAtAllLevels ($level, $message)
provideLevelsAndMessages
testObjectCastToString ()
testThrowsOnInvalidLevel ()
Detailed Description
Provides a base test class for ensuring compliance with the LoggerInterface.
Implementors can extend the class and implement abstract methods to run this as part of their test suite.
Definition at line 21 of file LoggerInterfaceTest.php.
Member Function Documentation
getLogger()
getLogger () abstract
Returns
LoggerInterface
Referenced by LoggerInterfaceTest\testContextCanContainAnything(), LoggerInterfaceTest\testContextExceptionKeyCanBeExceptionOrOtherValues(), LoggerInterfaceTest\testContextReplacement(), LoggerInterfaceTest\testImplements(), LoggerInterfaceTest\testLogsAtAllLevels(), LoggerInterfaceTest\testObjectCastToString(), and LoggerInterfaceTest\testThrowsOnInvalidLevel().
getLogs()
getLogs () abstract
This must return the log messages in order.
The simple formatting of the messages is: "<LOG LEVEL> <MESSAGE>".
Example ->error('Foo') would yield "error Foo".
Returns
string[]
Referenced by LoggerInterfaceTest\testContextCanContainAnything(), LoggerInterfaceTest\testContextExceptionKeyCanBeExceptionOrOtherValues(), LoggerInterfaceTest\testContextReplacement(), LoggerInterfaceTest\testLogsAtAllLevels(), and LoggerInterfaceTest\testObjectCastToString().
provideLevelsAndMessages()
provideLevelsAndMessages ()
Definition at line 60 of file LoggerInterfaceTest.php.
References LogLevel\ALERT, LogLevel\CRITICAL, LogLevel\DEBUG, LogLevel\EMERGENCY, LogLevel\ERROR, LogLevel\INFO, LogLevel\NOTICE, and LogLevel\WARNING.
testContextCanContainAnything()
testContextCanContainAnything ()
Definition at line 109 of file LoggerInterfaceTest.php.
References LoggerInterfaceTest\getLogger(), and LoggerInterfaceTest\getLogs().
testContextExceptionKeyCanBeExceptionOrOtherValues()
testContextExceptionKeyCanBeExceptionOrOtherValues ()
Definition at line 132 of file LoggerInterfaceTest.php.
References LoggerInterfaceTest\getLogger(), and LoggerInterfaceTest\getLogs().
testContextReplacement()
testContextReplacement ()
Definition at line 83 of file LoggerInterfaceTest.php.
References LoggerInterfaceTest\getLogger(), and LoggerInterfaceTest\getLogs().
testImplements()
testImplements ()
Definition at line 39 of file LoggerInterfaceTest.php.
References LoggerInterfaceTest\getLogger().
testLogsAtAllLevels()
testLogsAtAllLevels ($level, $message)
provideLevelsAndMessages
Definition at line 47 of file LoggerInterfaceTest.php.
References LoggerInterfaceTest\getLogger(), and LoggerInterfaceTest\getLogs().
testObjectCastToString()
testObjectCastToString ()
Definition at line 92 of file LoggerInterfaceTest.php.
References LoggerInterfaceTest\getLogger(), and LoggerInterfaceTest\getLogs().
testThrowsOnInvalidLevel()
testThrowsOnInvalidLevel ()
Definition at line 77 of file LoggerInterfaceTest.php.
References LoggerInterfaceTest\getLogger().
The documentation for this class was generated from the following file:
LoggerInterfaceTest.php