GravityView: MakePOT Class Reference
MakePOT Class Reference
Public Member Functions
__construct ($deprecated=true)
__destruct ()
bb ($dir, $output)
bp ($dir, $output)
generic ($dir, $output)
glotpress ($dir, $output)
guess_plugin_slug ($dir)
is_ms_file ($file_name)
is_not_ms_file ($file_name)
mu ($dir, $output)
realpath_missing ($path)
rosetta ($dir, $output)
tempnam ($file)
wp_admin ($dir, $output)
wp_core ($dir, $output)
wp_frontend ($dir, $output)
wp_generic ($dir, $args)
wp_ms ($dir, $output)
wp_network_admin ($dir, $output)
wp_plugin ($dir, $output, $slug=null)
wp_theme ($dir, $output, $slug=null)
wp_tz ($dir, $output)
wp_version ($dir)
wporg_bb_forums ($dir, $output)
xgettext ($project, $dir, $output_file, $placeholders=array(), $excludes=array(), $includes=array())
Static Public Member Functions
static get_addon_header ($header, $source)
static get_first_lines ($filename, $lines=30)
Data Fields
$max_header_lines = 30
$meta
$ms_files
$projects
$rules
$temp_files = array()
Detailed Description
Definition at line 10 of file makepot.php.
Constructor & Destructor Documentation
__construct ($deprecated = true)
Definition at line 156 of file makepot.php.
__destruct ()
Definition at line 160 of file makepot.php.
Member Function Documentation
bb ($dir, $output)
Definition at line 461 of file makepot.php.
References $output, and xgettext().
bp ($dir, $output)
Definition at line 635 of file makepot.php.
References $output, and xgettext().
generic ($dir, $output)
Definition at line 495 of file makepot.php.
References $output, and xgettext().
static get_addon_header ($header, $source) static
Definition at line 487 of file makepot.php.
Referenced by PotExtMeta\load_from_file(), GruntMakePOT\wp_plugin(), wp_plugin(), GruntMakePOT\wp_theme(), and wp_theme().
static get_first_lines ($filename, $lines = 30) static
Definition at line 468 of file makepot.php.
Referenced by PotExtMeta\load_from_file(), GruntMakePOT\wp_plugin(), wp_plugin(), GruntMakePOT\wp_theme(), and wp_theme().
glotpress ($dir, $output)
Definition at line 640 of file makepot.php.
References $output, and xgettext().
guess_plugin_slug ($dir)
Definition at line 500 of file makepot.php.
Referenced by GruntMakePOT\wp_plugin(), wp_plugin(), GruntMakePOT\wp_theme(), and wp_theme().
is_ms_file ($file_name)
Definition at line 663 of file makepot.php.
Referenced by is_not_ms_file().
is_not_ms_file ($file_name)
Definition at line 675 of file makepot.php.
References is_ms_file().
mu ($dir, $output)
Definition at line 452 of file makepot.php.
References $output, and xgettext().
realpath_missing ($path)
Definition at line 172 of file makepot.php.
Referenced by xgettext().
rosetta ($dir, $output)
Definition at line 653 of file makepot.php.
References $output, and xgettext().
tempnam ($file)
Definition at line 166 of file makepot.php.
Referenced by wp_admin(), wp_ms(), and wp_network_admin().
wp_admin ($dir, $output)
Definition at line 281 of file makepot.php.
References $output, PotExtMeta\append(), tempnam(), wp_frontend(), and wp_generic().
Referenced by wp_network_admin().
wp_core ($dir, $output)
Definition at line 248 of file makepot.php.
References $output, and wp_generic().
Referenced by wp_ms().
wp_frontend ($dir, $output)
Definition at line 264 of file makepot.php.
References $output, and wp_generic().
Referenced by wp_admin(), and wp_network_admin().
wp_generic ($dir, $args)
Definition at line 205 of file makepot.php.
References $output, NotGettexted\command_extract(), NotGettexted\list_php_files(), wp_version(), and xgettext().
Referenced by wp_admin(), wp_core(), wp_frontend(), wp_ms(), wp_network_admin(), and wp_tz().
wp_ms ($dir, $output)
Definition at line 387 of file makepot.php.
References $output, tempnam(), wp_core(), and wp_generic().
wp_network_admin ($dir, $output)
Definition at line 336 of file makepot.php.
References $output, tempnam(), wp_admin(), wp_frontend(), and wp_generic().
wp_plugin ($dir, $output, $slug = null)
Definition at line 511 of file makepot.php.
References $output, PotExtMeta\append(), get_addon_header(), get_first_lines(), guess_plugin_slug(), and xgettext().
wp_theme ($dir, $output, $slug = null)
Definition at line 574 of file makepot.php.
References $output, PotExtMeta\append(), get_addon_header(), get_first_lines(), guess_plugin_slug(), and xgettext().
wp_tz ($dir, $output)
Definition at line 427 of file makepot.php.
References $output, and wp_generic().
wp_version ($dir)
Definition at line 444 of file makepot.php.
Referenced by wp_generic().
wporg_bb_forums ($dir, $output)
Definition at line 645 of file makepot.php.
References $output, and xgettext().
xgettext ($project, $dir, $output_file, $placeholders = array(), $excludes = array(), $includes = array())
Definition at line 176 of file makepot.php.
References $meta, $value, and realpath_missing().
Referenced by bb(), bp(), generic(), glotpress(), mu(), rosetta(), wp_generic(), GruntMakePOT\wp_plugin(), wp_plugin(), GruntMakePOT\wp_theme(), wp_theme(), and wporg_bb_forums().
Field Documentation
$max_header_lines = 30
Definition at line 11 of file makepot.php.
$meta
Definition at line 69 of file makepot.php.
Referenced by xgettext().
$ms_files
Initial value:
= array(
        'ms-.*',
        '.*/ms-.*',
        '.*/my-.*',
        'wp-activate\.php',
        'wp-signup\.php',
        'wp-admin/network\.php',
        'wp-admin/includes/ms\.php',
        'wp-admin/network/.*\.php',
        'wp-admin/includes/class-wp-ms.*',
    )
Definition at line 55 of file makepot.php.
$projects
Initial value:
= array(
        'generic',
        'wp-frontend',
        'wp-admin',
        'wp-network-admin',
        'wp-core',
        'wp-ms',
        'wp-tz',
        'wp-plugin',
        'wp-theme',
        'bb',
        'mu',
        'bp',
        'rosetta',
        'wporg-bb-forums',
    )
Definition at line 13 of file makepot.php.
$rules
Initial value:
= array(
        '_'                    => array( 'string' ),
        '__'                   => array( 'string' ),
        '_e'                   => array( 'string' ),
        '_c'                   => array( 'string' ),
        '_n'                   => array( 'singular', 'plural' ),
        '_n_noop'              => array( 'singular', 'plural' ),
        '_nc'                  => array( 'singular', 'plural' ),
        '__ngettext'           => array( 'singular', 'plural' ),
        '__ngettext_noop'      => array( 'singular', 'plural' ),
        '_x'                   => array( 'string', 'context' ),
        '_ex'                  => array( 'string', 'context' ),
        '_nx'                  => array( 'singular', 'plural', null, 'context' ),
        '_nx_noop'             => array( 'singular', 'plural', 'context' ),
        '_n_js'                => array( 'singular', 'plural' ),
        '_nx_js'               => array( 'singular', 'plural', 'context' ),
        'esc_attr__'           => array( 'string' ),
        'esc_html__'           => array( 'string' ),
        'esc_attr_e'           => array( 'string' ),
        'esc_html_e'           => array( 'string' ),
        'esc_attr_x'           => array( 'string', 'context' ),
        'esc_html_x'           => array( 'string', 'context' ),
        'comments_number_link' => array( 'string', 'singular', 'plural' ),
    )
Definition at line 30 of file makepot.php.
$temp_files = array()
Definition at line 67 of file makepot.php.
The documentation for this class was generated from the following file:
makepot.php