GravityView: GravityView_API_Test Class Reference
GravityView_API_Test Class Reference
gvapi
Public Member Functions
_filter_test_gravityview_field_output_args ($args=array(), $passed_args=array())
Prevent wpautop() from being applied to View Zones.
_get_new_view_id ()
_override_no_entries_text_output ($previous, $is_search=false)
setUp ()
test_directory_link ()
gv_directory_link() GravityView_API::directory_link()
test_field_class ()
GravityView_API::field_class()
test_field_width ()
field_width GravityView_API::field_width()
test_gravityview_field_output ()
fieldoutput
test_gravityview_get_current_views ()
test_gv_container_class ()
gv_container_class()
test_gv_value ()
test_no_results ()
GravityView_API_Test::_override_no_entries_text_output() GravityView_API::no_results()
test_replace_variables ()
GravityView_API::replace_variables() GravityView_Merge_Tags::replace_variables()
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Data Fields
$entry = array()
$entry_id = 0
$form = array()
$form_id = 0
$is_set_up = false
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
gvapi
Definition at line 8 of file GravityView_API_Test.php.
Member Function Documentation
_filter_test_gravityview_field_output_args ($args = array(), $passed_args = array())
Prevent wpautop() from being applied to View Zones.
Parameters
array $args Associative array; field and form is required.
array $passed_args Original associative array with field data. field and form are required.
Definition at line 416 of file GravityView_API_Test.php.
_get_new_view_id ()
Definition at line 238 of file GravityView_API_Test.php.
References GravityView_View_Data\get_default_args().
Referenced by test_directory_link(), and test_gravityview_get_current_views().
_override_no_entries_text_output ($previous, $is_search = false)
Definition at line 228 of file GravityView_API_Test.php.
setUp ()
Definition at line 32 of file GravityView_API_Test.php.
References GV_Unit_Tests_Bootstrap\instance().
test_directory_link ()
gv_directory_link() GravityView_API::directory_link()
Definition at line 427 of file GravityView_API_Test.php.
References $gravityview_view, $post, _get_new_view_id(), GravityView_API\directory_link(), and GravityView_frontend\getInstance().
test_field_class ()
GravityView_API::field_class()
Definition at line 164 of file GravityView_API_Test.php.
References $entry, $field, $field_id, $form, and GravityView_API\field_class().
test_field_width ()
field_width GravityView_API::field_width()
Definition at line 309 of file GravityView_API_Test.php.
References $field, $format, and GravityView_API\field_width().
test_gravityview_field_output ()
fieldoutput
See also
gravityview_field_output gravityview_field_output()
'entry' => null, 'field' => null, 'form' => null, 'hide_empty' => true, 'markup' => '
{{label}}{{value}}
', 'label_markup' => '', 'wpautop' => false, 'zone_id' => null,
Definition at line 348 of file GravityView_API_Test.php.
References $field, $field_id, $output, $value, gravityview_field_output(), gravityview_get_field(), and gv_value().
test_gravityview_get_current_views ()
Definition at line 265 of file GravityView_API_Test.php.
References $post, _get_new_view_id(), GravityView_frontend\getInstance(), and gravityview_get_current_views().
test_gv_container_class ()
gv_container_class()
Definition at line 47 of file GravityView_API_Test.php.
References $output, GravityView_View\getInstance(), and gv_container_class().
test_gv_value ()
Definition at line 339 of file GravityView_API_Test.php.
test_no_results ()
GravityView_API_Test::_override_no_entries_text_output() GravityView_API::no_results()
Definition at line 192 of file GravityView_API_Test.php.
References $gravityview_view, GravityView_View\getInstance(), and GravityView_API\no_results().
test_replace_variables ()
GravityView_API::replace_variables() GravityView_Merge_Tags::replace_variables()
Definition at line 115 of file GravityView_API_Test.php.
References GV_Unit_Tests_Bootstrap\instance(), and GravityView_API\replace_variables().
Field Documentation
$entry = array()
Definition at line 28 of file GravityView_API_Test.php.
Referenced by test_field_class().
$entry_id = 0
Definition at line 23 of file GravityView_API_Test.php.
$form = array()
Definition at line 18 of file GravityView_API_Test.php.
Referenced by test_field_class().
$form_id = 0
Definition at line 13 of file GravityView_API_Test.php.
$is_set_up = false
Definition at line 30 of file GravityView_API_Test.php.
The documentation for this class was generated from the following file:
GravityView_API_Test.php