GravityView: Multi_Entry Class Reference
Multi_Entry Class Reference
If this file is called directly, abort.
Public Member Functions
as_entry ()
Fake legacy template support.
get_permalink (\GV\View $view=null, \GV\Request $request=null, $track_directory=true)
Return the link to this multi entry in the supplied context.
offsetExists ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
offsetGet ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
offsetSet ($offset, $value)
ArrayAccess compatibility layer with a Gravity Forms entry array.
offsetUnset ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Public Member Functions inherited from Entry
as_entry ()
Return the backing entry object.
from_field ($field, $fallback=null)
If this is a Multi_Entry filter it by Field.
get_permalink (\GV\View $view=null, \GV\Request $request=null, $track_directory=true)
Return the link to this entry in the supplied context.
get_slug ($apply_filter=false, \GV\View $view=null, \GV\Request $request=null, $track_directory=true)
Get the entry slug.
is_multi ()
Is this a multi-entry (joined entry).
Static Public Member Functions
static from_entries ($entries)
Construct a multientry from an array of entries.
Static Public Member Functions inherited from Entry
static add_rewrite_endpoint ()
Adds the necessary rewrites for single Entries.
static by_id ($entry_id)
Construct a instance by ID.
static get_endpoint_name ()
Return the endpoint name for a single Entry.
Data Fields
$entries = array()
The entries in this form.
Data Fields inherited from Entry
$ID = null
Static Public Attributes
static $backend = 'multi'
Static Public Attributes inherited from Entry
static $backend = null
Private Member Functions
__construct ()
Initialization.
Additional Inherited Members
Protected Attributes inherited from Entry
$entry
Detailed Description
If this file is called directly, abort.
The multi-entry Entry implementation.
An entry that is really a join of 2+ entries. Used for JOINS in the component.
Definition at line 15 of file class-gv-entry-multi.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Initialization.
Definition at line 31 of file class-gv-entry-multi.php.
Member Function Documentation
as_entry()
as_entry ()
Fake legacy template support.
Take the first entry and set it as the current entry. But support nesting.
Returns
array See ::as_entry()
Definition at line 60 of file class-gv-entry-multi.php.
References $entry.
from_entries()
static from_entries ($entries) static
Construct a multientry from an array of entries.
Parameters
Definition at line 41 of file class-gv-entry-multi.php.
References $entries, and $entry.
Referenced by GV\Mocks\GravityView_API_field_value().
get_permalink()
get_permalink (\GV\View $view = null, \GV\Request $request = null, $track_directory = true)
Return the link to this multi entry in the supplied context.
Since
2.2
Parameters
\GV\View | null $view The View context.
\GV\Request $request The Request (current if null).
boolean $track_directory Keep the housing directory arguments intact (used for breadcrumbs, for example). Default: true.
Returns
string The permalink to this entry.
Definition at line 87 of file class-gv-entry-multi.php.
References $entry.
offsetExists()
offsetExists ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Definition at line 111 of file class-gv-entry-multi.php.
offsetGet()
offsetGet ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Maps the old keys to the new data;
Definition at line 126 of file class-gv-entry-multi.php.
offsetSet()
offsetSet ($offset, $value)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Definition at line 142 of file class-gv-entry-multi.php.
References gravityview().
offsetUnset()
offsetUnset ($offset)
ArrayAccess compatibility layer with a Gravity Forms entry array.
Definition at line 154 of file class-gv-entry-multi.php.
References gravityview().
Field Documentation
$backend
$backend = 'multi' static
Definition at line 26 of file class-gv-entry-multi.php.
$entries
$entries = array()
The entries in this form.
Definition at line 19 of file class-gv-entry-multi.php.
The documentation for this class was generated from the following file:
class-gv-entry-multi.php