GravityView: GravityView_Search_WP_Widget Class Reference
GravityView_Search_WP_Widget Class Reference
Search widget class.
Public Member Functions
__construct ()
form ($instance)
update ($new_instance, $old_instance)
widget ($args, $instance)
Private Member Functions
load_required_files ()
Static Private Member Functions
static get_defaults ()
Detailed Description
Search widget class.
Since
1.6
Definition at line 8 of file class-gravityview-search-wp-widget.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 10 of file class-gravityview-search-wp-widget.php.
References GravityView_Widget_Search\getInstance(), and load_required_files().
Member Function Documentation
form()
form ($instance)
Display errors generated for invalid embed IDs
See also
GravityView_View_Data::is_valid_embed_id
Display errors generated for invalid embed IDs
See also
GravityView_View_Data::is_valid_embed_id
Definition at line 138 of file class-gravityview-search-wp-widget.php.
References $title, $view_id, GVCommon\get_all_views(), GravityView_Admin\get_floaty(), and GravityView_Admin\no_views_text().
get_defaults()
static get_defaults () static private
Definition at line 42 of file class-gravityview-search-wp-widget.php.
load_required_files()
load_required_files () private
Definition at line 36 of file class-gravityview-search-wp-widget.php.
References gravityview_register_gravityview_widgets().
Referenced by __construct().
update()
update ($new_instance, $old_instance)
Definition at line 106 of file class-gravityview-search-wp-widget.php.
References GravityView_View_Data\is_valid_embed_id().
widget()
widget ($args, $instance)
This filter is documented in wp-includes/default-widgets.php
Restore previous View context
Definition at line 53 of file class-gravityview-search-wp-widget.php.
References $title, GVCommon\get_form(), GVCommon\get_meta_form_id(), GravityView_Widget_Search\getInstance(), GravityView_View\getInstance(), and gravityview().
The documentation for this class was generated from the following file:
class-gravityview-search-wp-widget.php