GravityView: Walker_Page Class Reference
Walker_Page Class Reference
Core walker class used to create an HTML list of pages.
Public Member Functions
end_el (&$output, $page, $depth=0, $args=array())
Outputs the end of the current element in the tree.
end_lvl (&$output, $depth=0, $args=array())
Outputs the end of the current level in the tree after elements are output.
start_el (&$output, $page, $depth=0, $args=array(), $current_page=0)
Outputs the beginning of the current element in the tree.
start_lvl (&$output, $depth=0, $args=array())
Outputs the beginning of the current level in the tree before elements are output.
Public Member Functions inherited from Walker
display_element ($element, &$children_elements, $max_depth, $depth, $args, &$output)
Traverse elements to create list from elements.
end_el (&$output, $object, $depth=0, $args=array())
Ends the element output, if needed.
end_lvl (&$output, $depth=0, $args=array())
Ends the list of after the elements are added.
get_number_of_root_elements ($elements)
Calculates the total number of root elements.
paged_walk ($elements, $max_depth, $page_num, $per_page)
paged_walk() - produce a page of nested elements
start_el (&$output, $object, $depth=0, $args=array(), $current_object_id=0)
Start the element output.
start_lvl (&$output, $depth=0, $args=array())
Starts the list before the elements are added.
unset_children ($e, &$children_elements)
Unset all the children for a given top level element.
walk ($elements, $max_depth)
Display array of elements hierarchically.
Data Fields
$db_fields = array ('parent' => 'post_parent', 'id' => 'ID')
$tree_type = 'page'
Data Fields inherited from Walker
$db_fields
$has_children
$max_pages = 1
$tree_type
Detailed Description
Core walker class used to create an HTML list of pages.
Since
2.1.0
See also
Walker
Definition at line 17 of file class-walker-page.php.
Member Function Documentation
end_el (& $output, $page, $depth = 0, $args = array())
Outputs the end of the current element in the tree.
Since
2.1.0
See also
Walker::end_el()
Parameters
string $output Passed by reference. Used to append additional content.
object $page Page data object. Not used.
int $depth Depth of page. Not Used.
array $args
Definition at line 168 of file class-walker-page.php.
References $output.
end_lvl (& $output, $depth = 0, $args = array())
Outputs the end of the current level in the tree after elements are output.
Since
2.1.0
See also
Walker::end_lvl()
Parameters
string $output Passed by reference. Used to append additional content.
int $depth Optional. Depth of page. Used for padding. Default 0.
array $args Optional. Arguments for outputting the end of the current level. Default empty array.
Definition at line 66 of file class-walker-page.php.
References $output.
start_el (& $output, $page, $depth = 0, $args = array(), $current_page = 0)
Outputs the beginning of the current element in the tree.
See also
Walker::start_el()
Since
2.1.0
Parameters
string $output Passed by reference. Used to append additional content.
object $page Page data object.
int $depth Depth of page. Used for padding.
array $args Optional arguments.
int $current_page Page ID.
Filter the list of CSS classes to include with each page item in the list.
Since
2.8.0
See also
wp_list_pages()
Parameters
array $css_class An array of CSS classes to be applied to each list item.
WP_Post $page Page data object.
int $depth Depth of page, used for padding.
array $args An array of arguments.
int $current_page ID of the current page.
This filter is documented in wp-includes/post-template.php
Definition at line 83 of file class-walker-page.php.
References $date_format, $output, $page, __, apply_filters(), elseif, get_option(), get_permalink(), get_post(), and mysql2date().
start_lvl (& $output, $depth = 0, $args = array())
Outputs the beginning of the current level in the tree before elements are output.
Since
2.1.0
See also
Walker::start_lvl()
Parameters
string $output Passed by reference. Used to append additional content.
int $depth Optional. Depth of page. Used for padding. Default 0.
array $args Optional. Arguments for outputing the next level. Default empty array.
Definition at line 49 of file class-walker-page.php.
References $output.
Field Documentation
$db_fields = array ('parent' => 'post_parent', 'id' => 'ID')
Definition at line 35 of file class-walker-page.php.
$tree_type = 'page'
Definition at line 25 of file class-walker-page.php.
The documentation for this class was generated from the following file:
class-walker-page.php