GravityView: Entry_List_Template Class Reference
Entry_List_Template Class Reference
If this file is called directly, abort.
Public Member Functions
extract_zone_vars ($zones)
Return an array of variables ready to be extracted.
the_field (\GV\Field $field, $extras=null)
Output the field in the list view.
Public Member Functions inherited from Entry_Template
__construct (Entry $entry, View $view, Request $request)
Initializer.
__destruct ()
add_id_specific_templates ($templates, $slug, $name)
Enable granular template overrides based on current post, view, form, etc.
get_back_label ($do_replace=true)
Fetch the back link label for an entry context.
render ()
Output some HTML.
Public Member Functions inherited from Template
__construct ()
General template initialization.
__destruct ()
Disallow any cleanup for fear of loss of global data.
pop_template_data ($var_name='data')
Restore the template data from the stack.
push_template_data ($data, $var_name='data')
Push the current template data down the stack and set.
Static Public Attributes
static $slug = 'list'
Static Public Attributes inherited from Entry_Template
static $slug
Additional Inherited Members
Static Public Member Functions inherited from Template
static split_slug ($slug, $name=null)
Get a directory part and a full slug+name (file) components.
Data Fields inherited from Entry_Template
$entry
$request
$view
Data Fields inherited from Template
$located_template = ''
Protected Attributes inherited from Entry_Template
$filter_prefix = 'gravityview/template/entries'
$plugin_template_directory = 'templates/entries/'
$theme_template_directory = 'gravityview/entries/'
Detailed Description
If this file is called directly, abort.
The Entry List Template class .
Renders a using a .
Definition at line 14 of file class-gv-template-entry-list.php.
Member Function Documentation
extract_zone_vars()
extract_zone_vars ($zones)
Return an array of variables ready to be extracted.
Parameters
string | array $zones The field zones to grab.
Returns
array An array ready to be extract()ed in the form of $zone => has_$zone => int
Definition at line 85 of file class-gv-template-entry-list.php.
the_field()
the_field (\GV\Field $field, $extras = null)
Output the field in the list view.
Parameters
\GV\Field $field The field to output.
array $extras Extra stuff, like wpautop, etc.
Returns
string
Runs Filter:
gravityview/template/field/label Override the field label.
Since
2.0
Parameters
[in,out] string $label The label to override.
\GV\Template_Context $context The context.
Runs Filter:
gravityview/template/table/entry/hide_empty
Parameters
boolean $hide_empty Should the row be hidden if the value is empty? Default: don't hide.
\GV\Template_Context $context The context ;) Love it, cherish it. And don't you dare modify it!
Definition at line 28 of file class-gv-template-entry-list.php.
References $entry, GV\$form, $label, $value, GF_Form\by_id(), GV\get(), and gravityview_field_output().
Field Documentation
$slug
$slug = 'list' static
Definition at line 18 of file class-gv-template-entry-list.php.
The documentation for this class was generated from the following file:
class-gv-template-entry-list.php