GravityView: GF_Field_Post_Image Class Reference
GF_Field_Post_Image Class Reference
Public Member Functions
get_field_input ($form, $value= '', $entry=null)
get_form_editor_field_settings ()
get_form_editor_field_title ()
get_value_entry_detail ($value, $currency= '', $use_text=false, $format= 'html', $media= 'screen')
get_value_entry_list ($value, $entry, $field_id, $columns, $form)
get_value_merge_tag ($value, $input_id, $entry, $form, $modifier, $raw_value, $url_encode, $esc_html, $format, $nl2br)
get_value_save_entry ($value, $form, $input_name, $lead_id, $lead)
get_value_submission ($field_values, $get_from_post_global_var=true)
Data Fields
$type = 'post_image'
Detailed Description
Definition at line 8 of file class-gf-field-post-image.php.
Member Function Documentation
get_field_input ($form, $value = '', $entry = null)
Definition at line 31 of file class-gf-field-post-image.php.
References $caption, $class, $description, $field_id, $form, $form_id, $id, $size, $title, $value, __, esc_attr(), esc_html, and GFFormsModel\get_temp_filename().
get_form_editor_field_settings ()
Definition at line 16 of file class-gf-field-post-image.php.
get_form_editor_field_title ()
Definition at line 12 of file class-gf-field-post-image.php.
References esc_attr__().
get_value_entry_detail ($value, $currency = '', $use_text = false, $format = 'html', $media = 'screen')
Definition at line 111 of file class-gf-field-post-image.php.
References $ary, $caption, $description, $format, $title, $url, $value, __, label, and str_replace.
get_value_entry_list ($value, $entry, $field_id, $columns, $form)
Definition at line 101 of file class-gf-field-post-image.php.
References $caption, $description, $title, $url, $value, __, esc_attr(), and GFEntryList\get_icon_url().
get_value_merge_tag ($value, $input_id, $entry, $form, $modifier, $raw_value, $url_encode, $esc_html, $format, $nl2br)
Definition at line 151 of file class-gf-field-post-image.php.
References $caption, $description, $title, $url, $value, and str_replace.
get_value_save_entry ($value, $form, $input_name, $lead_id, $lead)
Definition at line 89 of file class-gf-field-post-image.php.
References $form, $form_id, $url, and $value.
get_value_submission ($field_values, $get_from_post_global_var = true)
Definition at line 142 of file class-gf-field-post-image.php.
References $value.
Field Documentation
$type = 'post_image'
Definition at line 10 of file class-gf-field-post-image.php.
The documentation for this class was generated from the following file:
class-gf-field-post-image.php