GravityView: WP_Post Class Reference
WP_Post Class Reference
Public Member Functions
__construct ($post)
Constructor.
__get ($key)
Getter.
__isset ($key)
Isset-er.
filter ($filter)
{ Summary}
to_array ()
Convert object to array.
Static Public Member Functions
static get_instance ($post_id)
Retrieve WP_Post instance.
Data Fields
$comment_count = 0
$comment_status = 'open'
$filter
$guid = ''
$ID
$menu_order = 0
$ping_status = 'open'
$pinged = ''
$post_author = 0
$post_content = ''
$post_content_filtered = ''
$post_date = '0000-00-00 00:00:00'
$post_date_gmt = '0000-00-00 00:00:00'
$post_excerpt = ''
$post_mime_type = ''
$post_modified = '0000-00-00 00:00:00'
$post_modified_gmt = '0000-00-00 00:00:00'
$post_name = ''
$post_parent = 0
$post_password = ''
$post_status = 'publish'
$post_title = ''
$post_type = 'post'
$to_ping = ''
Detailed Description
Definition at line 22 of file class-wp-post.php.
Constructor & Destructor Documentation
__construct ($post)
Constructor.
Parameters
WP_Post | object $post Post object.
Definition at line 239 of file class-wp-post.php.
References $post, and $value.
Member Function Documentation
__get ($key)
Getter.
Parameters
string $key Key to get.
Returns
mixed
Definition at line 272 of file class-wp-post.php.
References $value, __isset(), filter(), get_post_ancestors(), get_post_meta(), get_the_terms(), is_object_in_taxonomy(), post_type, sanitize_post_field(), and wp_list_pluck().
Referenced by to_array().
__isset ($key)
Isset-er.
Parameters
string $key Property to check if set.
Returns
bool
Definition at line 250 of file class-wp-post.php.
References metadata_exists(), and post_type.
Referenced by __get(), and to_array().
filter ($filter)
{ Summary}
Parameters
string $filter Filter.
Returns
self|array|bool|object|WP_Post
Definition at line 315 of file class-wp-post.php.
References $filter, and sanitize_post().
Referenced by __get().
static get_instance ($post_id) static
Retrieve WP_Post instance.
public
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Post ID.
Returns
WP_Post|false Post object, false otherwise.
Definition at line 210 of file class-wp-post.php.
References $post_id, $wpdb, elseif, sanitize_post(), wp_cache_add(), and wp_cache_get().
Referenced by get_post().
to_array ()
Convert object to array.
Returns
array Object as array.
Definition at line 330 of file class-wp-post.php.
References $post, __get(), and __isset().
Field Documentation
$comment_count = 0
Definition at line 188 of file class-wp-post.php.
$comment_status = 'open'
Definition at line 87 of file class-wp-post.php.
$filter
Definition at line 197 of file class-wp-post.php.
Referenced by filter().
$guid = ''
Definition at line 158 of file class-wp-post.php.
$ID
Definition at line 29 of file class-wp-post.php.
$menu_order = 0
Definition at line 165 of file class-wp-post.php.
$ping_status = 'open'
Definition at line 94 of file class-wp-post.php.
$pinged = ''
Definition at line 122 of file class-wp-post.php.
$post_author = 0
Definition at line 38 of file class-wp-post.php.
$post_content = ''
Definition at line 59 of file class-wp-post.php.
$post_content_filtered = ''
Definition at line 144 of file class-wp-post.php.
$post_date = '0000-00-00 00:00:00'
Definition at line 45 of file class-wp-post.php.
$post_date_gmt = '0000-00-00 00:00:00'
Definition at line 52 of file class-wp-post.php.
$post_excerpt = ''
Definition at line 73 of file class-wp-post.php.
$post_mime_type = ''
Definition at line 179 of file class-wp-post.php.
$post_modified = '0000-00-00 00:00:00'
Definition at line 129 of file class-wp-post.php.
$post_modified_gmt = '0000-00-00 00:00:00'
Definition at line 136 of file class-wp-post.php.
$post_name = ''
Definition at line 108 of file class-wp-post.php.
$post_parent = 0
Definition at line 151 of file class-wp-post.php.
$post_password = ''
Definition at line 101 of file class-wp-post.php.
$post_status = 'publish'
Definition at line 80 of file class-wp-post.php.
$post_title = ''
Definition at line 66 of file class-wp-post.php.
$post_type = 'post'
Definition at line 172 of file class-wp-post.php.
$to_ping = ''
Definition at line 115 of file class-wp-post.php.
The documentation for this class was generated from the following file:
class-wp-post.php