GravityView: SimplePie_Source Class Reference
SimplePie_Source Class Reference
Public Member Functions
__construct ($item, $data)
__toString ()
get_author ($key=0)
get_authors ()
get_base ($element=array())
get_categories ()
get_category ($key=0)
get_contributor ($key=0)
get_contributors ()
get_copyright ()
get_description ()
get_image_url ()
get_item ()
get_language ()
get_latitude ()
get_link ($key=0, $rel= 'alternate')
get_links ($rel= 'alternate')
get_longitude ()
get_permalink ()
Added for parity between the parent-level and the item/entry-level.
get_source_tags ($namespace, $tag)
get_title ()
sanitize ($data, $type, $base= '')
set_registry (SimplePie_Registry $registry)
Data Fields
$data = array()
$item
Protected Attributes
$registry
Detailed Description
Definition at line 55 of file Source.php.
Constructor & Destructor Documentation
__construct ($item, $data)
Definition at line 61 of file Source.php.
References $data, and $item.
Member Function Documentation
__toString ()
Definition at line 72 of file Source.php.
get_author ($key = 0)
Definition at line 210 of file Source.php.
References $authors, get_authors(), and null.
get_authors ()
Definition at line 223 of file Source.php.
References $authors, $name, $url, get_base(), get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_ITUNES.
Referenced by get_author().
get_base ($element = array())
Definition at line 89 of file Source.php.
Referenced by get_authors(), get_contributors(), get_copyright(), get_description(), get_image_url(), get_links(), and get_title().
get_categories ()
Definition at line 153 of file Source.php.
References $label, get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_category().
get_category ($key = 0)
Definition at line 140 of file Source.php.
References get_categories(), and null.
get_contributor ($key = 0)
Definition at line 293 of file Source.php.
References get_contributors(), and null.
get_contributors ()
Definition at line 306 of file Source.php.
References $name, $url, get_base(), get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, and SIMPLEPIE_NAMESPACE_ATOM_10.
Referenced by get_contributor().
get_copyright ()
Definition at line 503 of file Source.php.
References elseif, get_base(), get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
get_description ()
Definition at line 459 of file Source.php.
References elseif, get_base(), get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_HTML, SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
get_image_url ()
Definition at line 591 of file Source.php.
References elseif, get_base(), get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_NAMESPACE_ATOM_10, and SIMPLEPIE_NAMESPACE_ITUNES.
get_item ()
Definition at line 99 of file Source.php.
References $item.
get_language ()
Definition at line 531 of file Source.php.
References elseif, get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, and SIMPLEPIE_NAMESPACE_RSS_20.
get_latitude ()
Definition at line 555 of file Source.php.
References elseif, get_source_tags(), null, SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
get_link ($key = 0, $rel = 'alternate')
Definition at line 364 of file Source.php.
References get_links(), and null.
Referenced by get_permalink().
get_links ($rel = 'alternate')
Definition at line 385 of file Source.php.
References $keys, $link, elseif, get_base(), get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_IRI, SIMPLEPIE_IANA_LINK_RELATIONS_REGISTRY, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
Referenced by get_link().
get_longitude ()
Definition at line 571 of file Source.php.
References elseif, get_source_tags(), null, SIMPLEPIE_NAMESPACE_GEORSS, and SIMPLEPIE_NAMESPACE_W3C_BASIC_GEO.
get_permalink ()
Added for parity between the parent-level and the item/entry-level.
Definition at line 380 of file Source.php.
References get_link().
get_source_tags ($namespace, $tag)
Definition at line 77 of file Source.php.
References null.
Referenced by get_authors(), get_categories(), get_contributors(), get_copyright(), get_description(), get_image_url(), get_language(), get_latitude(), get_links(), get_longitude(), and get_title().
get_title ()
Definition at line 104 of file Source.php.
References elseif, get_base(), get_source_tags(), null, sanitize(), SIMPLEPIE_CONSTRUCT_MAYBE_HTML, SIMPLEPIE_CONSTRUCT_TEXT, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_DC_10, SIMPLEPIE_NAMESPACE_DC_11, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, and SIMPLEPIE_NAMESPACE_RSS_20.
sanitize ($data, $type, $base = '')
Definition at line 94 of file Source.php.
Referenced by get_authors(), get_categories(), get_contributors(), get_copyright(), get_description(), get_image_url(), get_language(), get_links(), and get_title().
set_registry (SimplePie_Registry $registry)
Definition at line 67 of file Source.php.
References $registry.
Field Documentation
$data = array()
Definition at line 58 of file Source.php.
Referenced by __construct().
$item
Definition at line 57 of file Source.php.
Referenced by __construct(), and get_item().
$registry protected
Definition at line 59 of file Source.php.
Referenced by set_registry().
The documentation for this class was generated from the following file:
Source.php