GravityView: Shortcode Class Reference
Shortcode Class Reference
If this file is called directly, abort.
Public Member Functions
callback ($atts, $content=null)
The WordPress Shortcode API callback for this shortcode.
Static Public Member Functions
static add ()
Register this shortcode class with the WordPress Shortcode API.
static parse ($content)
Parse a string of content and figure out which ones there are.
static remove ()
Unregister this shortcode.
Data Fields
$atts
$content
$name
Static Private Attributes
static $shortcodes
Detailed Description
If this file is called directly, abort.
The base class.
Contains some unitility methods, base class for all GV Shortcodes.
Definition at line 14 of file class-gv-shortcode.php.
Member Function Documentation
add()
static add () static
Register this shortcode class with the WordPress Shortcode API.
Definition at line 55 of file class-gv-shortcode.php.
References gravityview().
callback()
callback ($atts, $content = null)
The WordPress Shortcode API callback for this shortcode.
Parameters
array $atts The callback shortcode attributes.
string | null $content The wrapped content. Default: null.
Returns
string The result of the shortcode logic.
Definition at line 43 of file class-gv-shortcode.php.
References gravityview().
parse()
static parse ($content) static
Parse a string of content and figure out which ones there are.
Only registered shortcodes (via add_shortcode) will show up. Returned order is not guaranteed.
Parameters
string $content Some post content to search through.
The matches contains:
1 - An extra [ to allow for escaping shortcodes with double [[]] 2 - The shortcode name 3 - The shortcode argument list 4 - The self closing / 5 - The content of a shortcode when it wraps some content. 6 - An extra ] to allow for escaping shortcodes with double [[]]
This is a registered GravityView shortcode.
This is some generic shortcode.
Merge inner shortcodes.
Definition at line 95 of file class-gv-shortcode.php.
References $content.
Referenced by Legacy_Context\load(), and GravityView_View_Data\maybe_get_view_id().
remove()
static remove () static
Unregister this shortcode.
Definition at line 77 of file class-gv-shortcode.php.
Field Documentation
$atts
$atts
Definition at line 23 of file class-gv-shortcode.php.
Referenced by gventry\callback(), gvfield\callback(), gravityview\callback(), gravityview\detail(), and gravityview\parse_and_sanitize_atts().
$content
$content
Definition at line 33 of file class-gv-shortcode.php.
$name
$name
Definition at line 28 of file class-gv-shortcode.php.
$shortcodes
$shortcodes static private
Definition at line 18 of file class-gv-shortcode.php.
The documentation for this class was generated from the following file:
class-gv-shortcode.php