GravityView: getID3 Class Reference
getID3 Class Reference
Public Member Functions
__construct ()
analyze ($filename)
CalculateCompressionRatioAudio ()
CalculateCompressionRatioVideo ()
CalculateReplayGain ()
ChannelsBitratePlaytimeCalculations ()
CharConvert (&$array, $encoding)
error ($message)
fread_buffer_size ()
GetFileFormat (&$filedata, $filename='')
GetFileFormatArray ()
getHashdata ($algorithm)
getid3_tempnam ()
HandleAllTags ()
include_module ($name)
openfile ($filename)
ProcessAudioStreams ()
setOption ($optArray)
version ()
warning ($message)
Data Fields
$encoding = 'UTF-8'
$encoding_id3v1 = 'ISO-8859-1'
$filename
$fp
$info
$memory_limit = 0
$option_extra_info = true
$option_fread_buffer_size = 32768
$option_max_2gb_check = null
$option_md5_data = false
$option_md5_data_source = false
$option_save_attachments = true
$option_sha1_data = false
$option_tag_apetag = true
$option_tag_id3v1 = true
$option_tag_id3v2 = true
$option_tag_lyrics3 = true
$option_tags_html = true
$option_tags_process = true
$tempdir = GETID3_TEMP_DIR
const ATTACHMENTS_INLINE = true
const ATTACHMENTS_NONE = false
const FREAD_BUFFER_SIZE = 32768
const VERSION = '1.9.9-20141121'
Protected Attributes
$startup_error = ''
$startup_warning = ''
Private Member Functions
CleanUp ()
Detailed Description
Definition at line 72 of file getid3.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 119 of file getid3.php.
References $filename, $value, elseif, null, and warning().
Member Function Documentation
analyze ($filename)
Definition at line 338 of file getid3.php.
References $class, $filename, $info, getid3_lib\BigEndian2Int(), CalculateCompressionRatioAudio(), CalculateCompressionRatioVideo(), CalculateReplayGain(), ChannelsBitratePlaytimeCalculations(), CleanUp(), elseif, error(), GetFileFormat(), getHashdata(), HandleAllTags(), include_module(), openfile(), ProcessAudioStreams(), and warning().
CalculateCompressionRatioAudio ()
Definition at line 1520 of file getid3.php.
Referenced by analyze().
CalculateCompressionRatioVideo ()
Definition at line 1472 of file getid3.php.
Referenced by analyze().
CalculateReplayGain ()
Definition at line 1537 of file getid3.php.
References getid3_lib\RGADamplitude2dB().
Referenced by analyze().
ChannelsBitratePlaytimeCalculations ()
Definition at line 1407 of file getid3.php.
References elseif, and getid3_lib\PlaytimeString().
Referenced by analyze().
CharConvert (& $array, $encoding)
Definition at line 1139 of file getid3.php.
References $encoding, $value, elseif, and getid3_lib\iconv_fallback().
Referenced by HandleAllTags().
CleanUp () private
Definition at line 507 of file getid3.php.
References $value.
Referenced by analyze(), and error().
error ($message)
Definition at line 489 of file getid3.php.
References $info, $message, and CleanUp().
Referenced by analyze(), getHashdata(), and openfile().
fread_buffer_size ()
Definition at line 219 of file getid3.php.
References $option_fread_buffer_size.
GetFileFormat (& $filedata, $filename = '')
Definition at line 1100 of file getid3.php.
References $filename, $info, elseif, and GetFileFormatArray().
Referenced by analyze().
GetFileFormatArray ()
Definition at line 555 of file getid3.php.
Referenced by GetFileFormat().
getHashdata ($algorithm)
Definition at line 1283 of file getid3.php.
References $file, error(), getid3_lib\hash_data(), and warning().
Referenced by analyze().
getid3_tempnam ()
Definition at line 1572 of file getid3.php.
HandleAllTags ()
Definition at line 1162 of file getid3.php.
References $encoding, $tags, $value, CharConvert(), and getid3_lib\recursiveMultiByteCharString2HTML().
Referenced by analyze().
include_module ($name)
Definition at line 1576 of file getid3.php.
References $name.
Referenced by analyze().
openfile ($filename)
Definition at line 239 of file getid3.php.
References $encoding, $filename, elseif, error(), getid3_lib\getFileSizeSyscall(), getid3_lib\intValueSupported(), getid3_lib\mb_basename(), str_replace, version(), and warning().
Referenced by analyze().
ProcessAudioStreams ()
Definition at line 1559 of file getid3.php.
References $value.
Referenced by analyze().
setOption ($optArray)
Definition at line 225 of file getid3.php.
version ()
Definition at line 215 of file getid3.php.
Referenced by openfile().
warning ($message)
Definition at line 500 of file getid3.php.
References $message.
Referenced by __construct(), analyze(), getHashdata(), and openfile().
Field Documentation
$encoding = 'UTF-8'
Definition at line 75 of file getid3.php.
Referenced by CharConvert(), HandleAllTags(), and openfile().
$encoding_id3v1 = 'ISO-8859-1'
Definition at line 76 of file getid3.php.
$filename
Definition at line 102 of file getid3.php.
Referenced by __construct(), analyze(), GetFileFormat(), and openfile().
$fp
Definition at line 103 of file getid3.php.
$info
Definition at line 104 of file getid3.php.
Referenced by analyze(), error(), and GetFileFormat().
$memory_limit = 0
Definition at line 106 of file getid3.php.
$option_extra_info = true
Definition at line 87 of file getid3.php.
$option_fread_buffer_size = 32768
Definition at line 99 of file getid3.php.
Referenced by fread_buffer_size().
$option_max_2gb_check = null
Definition at line 96 of file getid3.php.
$option_md5_data = false
Definition at line 93 of file getid3.php.
$option_md5_data_source = false
Definition at line 94 of file getid3.php.
$option_save_attachments = true
Definition at line 90 of file getid3.php.
$option_sha1_data = false
Definition at line 95 of file getid3.php.
$option_tag_apetag = true
Definition at line 82 of file getid3.php.
$option_tag_id3v1 = true
Definition at line 79 of file getid3.php.
$option_tag_id3v2 = true
Definition at line 80 of file getid3.php.
$option_tag_lyrics3 = true
Definition at line 81 of file getid3.php.
$option_tags_html = true
Definition at line 84 of file getid3.php.
$option_tags_process = true
Definition at line 83 of file getid3.php.
$startup_error = '' protected
Definition at line 109 of file getid3.php.
$startup_warning = '' protected
Definition at line 110 of file getid3.php.
$tempdir = GETID3_TEMP_DIR
Definition at line 105 of file getid3.php.
const ATTACHMENTS_INLINE = true
Definition at line 116 of file getid3.php.
Referenced by getid3_handler\saveAttachment().
const ATTACHMENTS_NONE = false
Definition at line 115 of file getid3.php.
Referenced by getid3_matroska\Analyze(), getid3_flac\parseMETAdata(), and getid3_handler\saveAttachment().
const FREAD_BUFFER_SIZE = 32768
Definition at line 113 of file getid3.php.
Referenced by getid3_lib\CopyFileParts().
const VERSION = '1.9.9-20141121'
Definition at line 112 of file getid3.php.
The documentation for this class was generated from the following file:
getid3.php