GravityView: Route Class Reference
Route Class Reference
If this file is called directly, abort.
Public Member Functions
__call ($method, $args)
Fallback if subclass doesn't define routes.
create_item ($request)
Create one item from the collection.
create_item_permissions_check ($request)
Check if a given request has access to create items.
create_sub_item ($request)
Create one item from the collection.
delete_item ($request)
Delete one item from the collection.
delete_item_permissions_check ($request)
Check if a given request has access to delete a specific item.
delete_sub_item ($request)
Delete one item from the collection for sub items.
get_item ($request)
Get one item from the collection.
get_item_permissions_check ($request)
Check if a given request has access to get a specific item.
get_items ($request)
Get a collection of items.
get_items_permissions_check ($request)
Check if a given request has access to get items.
get_sub_item ($request)
Get one item from the collection.
get_sub_items ($request)
Get a collection of items.
prepare_item_for_response ($item, $request)
Prepare the item for the REST response.
register_routes ()
Register the routes for the objects of the controller.
update_item ($request)
Update one item from the collection.
update_item_permissions_check ($request)
Check if a given request has access to update a specific item.
update_sub_item ($request)
Update one item from the collection for sub items.
Protected Member Functions
get_route_name ()
Get route name.
get_sub_type ()
Get sub_type.
not_implemented ()
Generic response for routes not yet implemented.
prepare_item_for_database ($request)
Prepare the item for create or update operation.
Protected Attributes
$route_name
$sub_type
Detailed Description
If this file is called directly, abort.
Definition at line 18 of file class-gv-rest-route.php.
Member Function Documentation
__call()
__call ($method, $args)
Fallback if subclass doesn't define routes.
Returns empty array for args instead of making an error.
Since
2.0
Parameters
$method
Returns
array
Definition at line 398 of file class-gv-rest-route.php.
create_item()
create_item ($request)
Create one item from the collection.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 227 of file class-gv-rest-route.php.
References Route\not_implemented().
create_item_permissions_check()
create_item_permissions_check ($request)
Check if a given request has access to create items.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 329 of file class-gv-rest-route.php.
References Route\not_implemented().
create_sub_item()
create_sub_item ($request)
Create one item from the collection.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 279 of file class-gv-rest-route.php.
References Route\not_implemented().
delete_item()
delete_item ($request)
Delete one item from the collection.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 247 of file class-gv-rest-route.php.
References Route\not_implemented().
delete_item_permissions_check()
delete_item_permissions_check ($request)
Check if a given request has access to delete a specific item.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 349 of file class-gv-rest-route.php.
References Route\not_implemented().
delete_sub_item()
delete_sub_item ($request)
Delete one item from the collection for sub items.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 299 of file class-gv-rest-route.php.
References Route\not_implemented().
get_item()
get_item ($request)
Get one item from the collection.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
|
Definition at line 217 of file class-gv-rest-route.php.
References Route\not_implemented().
get_item_permissions_check()
get_item_permissions_check ($request)
Check if a given request has access to get a specific item.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 319 of file class-gv-rest-route.php.
References Route\not_implemented().
get_items()
get_items ($request)
Get a collection of items.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
|
Definition at line 207 of file class-gv-rest-route.php.
References Route\not_implemented().
get_items_permissions_check()
get_items_permissions_check ($request)
Check if a given request has access to get items.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 309 of file class-gv-rest-route.php.
References Route\not_implemented().
get_route_name()
get_route_name () protected
Get route name.
MUST SET route_name property in subclass!
Since
2.0 protected
Returns
string
Definition at line 174 of file class-gv-rest-route.php.
References Route\$route_name.
Referenced by Route\register_routes().
get_sub_item()
get_sub_item ($request)
Get one item from the collection.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
|
Definition at line 269 of file class-gv-rest-route.php.
References Route\not_implemented().
get_sub_items()
get_sub_items ($request)
Get a collection of items.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
|
Definition at line 258 of file class-gv-rest-route.php.
References Route\not_implemented().
Referenced by Views_Route\prepare_entry_for_response().
get_sub_type()
get_sub_type () protected
Get sub_type.
MUST SET sub_type property in subclass!
Since
2.0 protected
Returns
string
Definition at line 192 of file class-gv-rest-route.php.
References Route\$sub_type.
Referenced by Route\register_routes().
not_implemented()
not_implemented () protected
Generic response for routes not yet implemented.
Since
2.0
Returns
Definition at line 384 of file class-gv-rest-route.php.
Referenced by Route\create_item(), Route\create_item_permissions_check(), Route\create_sub_item(), Route\delete_item(), Route\delete_item_permissions_check(), Route\delete_sub_item(), Route\get_item(), Route\get_item_permissions_check(), Route\get_items(), Route\get_items_permissions_check(), Route\get_sub_item(), Route\get_sub_items(), Route\prepare_item_for_database(), Route\prepare_item_for_response(), Route\update_item(), Route\update_item_permissions_check(), and Route\update_sub_item().
prepare_item_for_database()
prepare_item_for_database ($request) protected
Prepare the item for create or update operation.
Parameters
\WP_REST_Request $request Request object
Returns
Definition at line 360 of file class-gv-rest-route.php.
References Route\not_implemented().
prepare_item_for_response()
prepare_item_for_response ($item, $request)
Prepare the item for the REST response.
Since
2.0
Parameters
mixed $item WordPress representation of the item.
\WP_REST_Request $request Request object.
Returns
Definition at line 374 of file class-gv-rest-route.php.
References Route\not_implemented().
register_routes()
register_routes ()
Register the routes for the objects of the controller.
Definition at line 40 of file class-gv-rest-route.php.
References $format, Route\$sub_type, Core\get_namespace(), Route\get_route_name(), and Route\get_sub_type().
update_item()
update_item ($request)
Update one item from the collection.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 237 of file class-gv-rest-route.php.
References Route\not_implemented().
update_item_permissions_check()
update_item_permissions_check ($request)
Check if a given request has access to update a specific item.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 339 of file class-gv-rest-route.php.
References Route\not_implemented().
update_sub_item()
update_sub_item ($request)
Update one item from the collection for sub items.
Parameters
\WP_REST_Request $request Full data about the request.
Returns
Definition at line 289 of file class-gv-rest-route.php.
References Route\not_implemented().
Field Documentation
$route_name
$route_name protected
Definition at line 26 of file class-gv-rest-route.php.
Referenced by Route\get_route_name().
$sub_type
$sub_type protected
Definition at line 35 of file class-gv-rest-route.php.
Referenced by Route\get_sub_type(), and Route\register_routes().
The documentation for this class was generated from the following file:
class-gv-rest-route.php