GravityView: GF_Installation_Wizard Class Reference
GF_Installation_Wizard Class Reference
Public Member Functions
__construct ()
complete_installation ()
display ()
get_next_step ($current_step)
get_previous_step ($current_step)
get_sorted_step_names ()
get_step ($name=false)
get_step_index ($step)
get_steps ()
progress ($current_step, $echo=true)
summary ()
Private Attributes
$_step_class_names = array()
Detailed Description
Definition at line 7 of file class-gf-installation-wizard.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 10 of file class-gf-installation-wizard.php.
References $path, $step, get_sorted_step_names(), and str_replace.
Member Function Documentation
complete_installation ()
Definition at line 214 of file class-gf-installation-wizard.php.
References $step, delete_option(), and get_step().
Referenced by display().
display ()
Definition at line 39 of file class-gf-installation-wizard.php.
References $min, $name, admin_url(), complete_installation(), elseif, esc_attr(), esc_html_e, esc_url, get_next_step(), get_previous_step(), get_step(), get_step_index(), input, name, progress(), wp_nonce_field(), wp_print_styles(), and wp_register_style().
Referenced by GFForms\maybe_display_installation_wizard().
get_next_step ($current_step)
Parameters
GF_Installation_Wizard_Step $current_step
Returns
bool|GF_Installation_Wizard_Step
Definition at line 199 of file class-gf-installation-wizard.php.
References $i, and get_step().
Referenced by display().
get_previous_step ($current_step)
Parameters
$current_step
Returns
bool|GF_Installation_Wizard_Step
Definition at line 179 of file class-gf-installation-wizard.php.
References $i, and get_step().
Referenced by display().
get_sorted_step_names ()
Definition at line 30 of file class-gf-installation-wizard.php.
Referenced by __construct().
get_step ($name = false)
Parameters
bool $name
Returns
GF_Installation_Wizard_Step
Definition at line 160 of file class-gf-installation-wizard.php.
References $name, $step, and get_option().
Referenced by complete_installation(), display(), get_next_step(), get_previous_step(), get_steps(), and progress().
get_step_index ($step)
Definition at line 256 of file class-gf-installation-wizard.php.
References $i, and $step.
Referenced by display().
get_steps ()
Returns
GF_Installation_Wizard_Step[]
Definition at line 281 of file class-gf-installation-wizard.php.
References get_step().
Referenced by summary().
progress ($current_step, $echo = true)
Parameters
GF_Installation_Wizard_Step $current_step
bool $echo
Returns
string
Definition at line 231 of file class-gf-installation-wizard.php.
References $class, $step, esc_attr(), esc_html, and get_step().
Referenced by display().
summary ()
Definition at line 261 of file class-gf-installation-wizard.php.
References $step, esc_html, and get_steps().
Field Documentation
$_step_class_names = array() private
Definition at line 8 of file class-gf-installation-wizard.php.
The documentation for this class was generated from the following file:
class-gf-installation-wizard.php