GravityView: GFSelectColumns Class Reference
GFSelectColumns Class Reference
Static Public Member Functions
static select_columns_page ()
Data Fields
margin __pad0__: 0 2px 2px 2px
padding __pad1__: 2px
width __pad2__: 96%
border __pad3__: 1px solid white
cursor __pad4__: pointer
font size: 13px
Detailed Description
Definition at line 19 of file select_columns.php.
Member Function Documentation
static select_columns_page () static
Definition at line 20 of file select_columns.php.
References $form, $form_id, __, Arial, color, exit, family, GFFormsModel\get_form_meta(), height, margin, radius, serif, wp_is_mobile(), wp_print_scripts(), and wp_print_styles().
Field Documentation
margin __pad0__
Definition at line 63 of file select_columns.php.
padding __pad1__
Definition at line 64 of file select_columns.php.
width __pad2__
Definition at line 65 of file select_columns.php.
border __pad3__
Definition at line 66 of file select_columns.php.
cursor __pad4__
Definition at line 67 of file select_columns.php.
font size
Definition at line 68 of file select_columns.php.
The documentation for this class was generated from the following file:
select_columns.php