GravityView: Text_Diff Class Reference
Text_Diff Class Reference
Public Member Functions
__construct ($engine, $params)
Computes diffs between sequences of strings.
_check ($from_lines, $to_lines)
Checks a diff for validity.
countAddedLines ()
returns the number of new (added) lines in a given diff.
countDeletedLines ()
Returns the number of deleted (removed) lines in a given diff.
getDiff ()
Returns the array of differences.
getFinal ()
Gets the final set of lines.
getOriginal ()
Gets the original set of lines.
isEmpty ()
Checks for an empty diff.
lcs ()
Computes the length of the Longest Common Subsequence (LCS).
reverse ()
Computes a reversed diff.
Text_Diff ($engine, $params)
PHP4 constructor.
Static Public Member Functions
_getTempDir ()
Determines the location of the system temporary directory.
static trimNewlines (&$line, $key)
Removes trailing newlines from a line of text.
Data Fields
$_edits
Detailed Description
Definition at line 18 of file Diff.php.
Constructor & Destructor Documentation
__construct ($engine, $params)
Computes diffs between sequences of strings.
Parameters
string $engine Name of the diffing engine to use. 'auto' will automatically select the best.
array $params Parameters to pass to the diffing engine. Normally an array of two arrays, each containing the lines from a file.
Definition at line 36 of file Diff.php.
References $class.
Member Function Documentation
_check ($from_lines, $to_lines)
Checks a diff for validity.
This is here only for debugging purposes.
Definition at line 262 of file Diff.php.
References getFinal(), getOriginal(), null, and reverse().
_getTempDir () static
Determines the location of the system temporary directory.
protected
Returns
string A directory name which can be used for temp files. Returns false if one could not be found.
Definition at line 230 of file Diff.php.
Referenced by Text_Diff_Engine_shell\diff().
countAddedLines ()
returns the number of new (added) lines in a given diff.
Since
Text_Diff 1.1.0
Returns
integer The number of new lines
Definition at line 80 of file Diff.php.
References $count.
countDeletedLines ()
Returns the number of deleted (removed) lines in a given diff.
Since
Text_Diff 1.1.0
Returns
integer The number of deleted lines
Definition at line 99 of file Diff.php.
References $count.
getDiff ()
Returns the array of differences.
Definition at line 68 of file Diff.php.
References $_edits.
getFinal ()
Gets the final set of lines.
This reconstructs the $to_lines parameter passed to the constructor.
Returns
array The sequence of strings.
Definition at line 197 of file Diff.php.
Referenced by _check().
getOriginal ()
Gets the original set of lines.
This reconstructs the $from_lines parameter passed to the constructor.
Returns
array The original sequence of strings.
Definition at line 179 of file Diff.php.
Referenced by _check().
isEmpty ()
Checks for an empty diff.
Returns
boolean True if two sequences were identical.
Definition at line 144 of file Diff.php.
lcs ()
Computes the length of the Longest Common Subsequence (LCS).
This is mostly for diagnostic purposes.
Returns
integer The length of the LCS.
Definition at line 161 of file Diff.php.
reverse ()
Computes a reversed diff.
Example: $diff = new Text_Diff($lines1, $lines2); $rev = $diff->reverse();
Returns
Text_Diff A Diff object representing the inverse of the original diff. Note that we purposely don't return a reference here, since this essentially is a clone() method.
Definition at line 125 of file Diff.php.
Referenced by _check().
Text_Diff ($engine, $params)
PHP4 constructor.
Definition at line 61 of file Diff.php.
static trimNewlines (& $line, $key) static
Removes trailing newlines from a line of text.
This is meant to be used with array_walk().
Parameters
string $line The line to trim.
integer $key The index of the line in the array. Not used.
Definition at line 215 of file Diff.php.
References str_replace.
Field Documentation
$_edits
Definition at line 25 of file Diff.php.
Referenced by getDiff().
The documentation for this class was generated from the following file:
Diff.php