GravityView: WP_User Class Reference
WP_User Class Reference
Public Member Functions
__call ($name, $arguments)
Makes private/protected methods readable for backwards compatibility.
__construct ($id=0, $name= '', $blog_id= '')
Constructor.
__get ($key)
Magic method for accessing custom fields.
__isset ($key)
Magic method for checking the existence of a certain custom field.
__set ($key, $value)
Magic method for setting custom user fields.
__unset ($key)
Magic method for unsetting a certain custom field.
add_cap ($cap, $grant=true)
Add capability and grant or deny access to capability.
add_role ($role)
Add role to user.
exists ()
Determine whether the user exists in the database.
for_blog ($blog_id= '')
Set the blog to operate on.
get ($key)
Retrieve the value of a property or meta key.
get_role_caps ()
Retrieve all of the role capabilities and merge with individual capabilities.
has_cap ($cap)
Whether user has capability or role name.
has_prop ($key)
Determine whether a property or meta key is set.
init ($data, $blog_id= '')
Sets up object properties, including capabilities.
level_reduction ($max, $item)
Choose the maximum level the user has.
remove_all_caps ()
Remove all of the capabilities of the user.
remove_cap ($cap)
Remove capability from user.
remove_role ($role)
Remove role from user.
set_role ($role)
Set the role of the user.
to_array ()
Return an array representation.
translate_level_to_cap ($level)
Convert numeric level to level capability name.
update_user_level_from_caps ()
Update the maximum user level for the user.
Static Public Member Functions
static get_data_by ($field, $value)
Return only the main user fields.
Data Fields
$allcaps = array()
$cap_key
$caps = array()
$data
$filter = null
$ID = 0
$roles = array()
Protected Member Functions
_init_caps ($cap_key= '')
Set up capability object properties.
Static Private Attributes
static $back_compat_keys
Detailed Description
Definition at line 34 of file class-wp-user.php.
Constructor & Destructor Documentation
__construct ($id = 0, $name = '', $blog_id = '')
Constructor.
Retrieves the userdata and passes it to WP_User::init().
Since
2.0.0 public
wpdb $wpdb WordPress database abstraction object.
Parameters
int | string | stdClass | WP_User $id User's ID, a WP_User object, or a user object from the DB.
string $name Optional. User's username
int $blog_id Optional Blog ID, defaults to current blog.
Definition at line 118 of file class-wp-user.php.
References $blog_id, $data, $GLOBALS, $id, $name, $prefix, elseif, and init().
Member Function Documentation
__call ($name, $arguments)
Makes private/protected methods readable for backwards compatibility.
Since
4.3.0 public
Parameters
callable $name Method to call.
array $arguments Arguments to pass when calling.
Returns
mixed|false Return value of the callback, false otherwise.
Definition at line 254 of file class-wp-user.php.
References $name.
__get ($key)
Magic method for accessing custom fields.
Since
3.3.0 public
Parameters
string $key User meta key to retrieve.
Returns
mixed Value of the given user meta key (if set). If $key is 'id', the user ID.
Definition at line 300 of file class-wp-user.php.
References $ID, $value, __, _deprecated_argument(), get_user_meta(), and sanitize_user_field().
Referenced by get().
__isset ($key)
Magic method for checking the existence of a certain custom field.
Since
3.3.0 public
Parameters
string $key User meta key to check if set.
Returns
bool Whether the given user meta key is set.
Definition at line 270 of file class-wp-user.php.
References __, _deprecated_argument(), and metadata_exists().
Referenced by has_prop().
__set ($key, $value)
Magic method for setting custom user fields.
This method does not update custom fields in the database. It only stores the value on the WP_User instance.
Since
3.3.0 public
Parameters
string $key User meta key.
mixed $value User meta value.
Definition at line 339 of file class-wp-user.php.
References $value, __, and _deprecated_argument().
__unset ($key)
Magic method for unsetting a certain custom field.
Since
4.4.0 public
Parameters
string $key User meta key to unset.
Definition at line 363 of file class-wp-user.php.
References __, and _deprecated_argument().
_init_caps ($cap_key = '') protected
Set up capability object properties.
Will set the value for the 'cap_key' property to current database table prefix, followed by 'capabilities'. Will then check to see if the property matching the 'cap_key' exists and is an array. If so, it will be used.
protected
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $cap_key Optional capability key
Definition at line 449 of file class-wp-user.php.
References $cap_key, $wpdb, get_role_caps(), and get_user_meta().
Referenced by for_blog().
add_cap ($cap, $grant = true)
Add capability and grant or deny access to capability.
Since
2.0.0 public
Parameters
string $cap Capability name.
bool $grant Whether to grant capability to user.
Definition at line 652 of file class-wp-user.php.
References get_role_caps(), update_user_level_from_caps(), and update_user_meta().
Referenced by GV_UnitTest_Factory_For_User\_add_gravityview_caps().
add_role ($role)
Add role to user.
Updates the user's meta data option with capabilities and roles.
Since
2.0.0 public
Parameters
string $role Role name.
Fires immediately after the user has been given a new role.
Since
4.3.0
Parameters
int $user_id The user ID.
string $role The new role.
Definition at line 506 of file class-wp-user.php.
References do_action(), get_role_caps(), update_user_level_from_caps(), and update_user_meta().
exists ()
Determine whether the user exists in the database.
Since
3.4.0 public
Returns
bool True if user exists in the database, false if not.
Definition at line 391 of file class-wp-user.php.
for_blog ($blog_id = '')
Set the blog to operate on.
Defaults to the current blog.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $blog_id Optional Blog ID, defaults to current blog.
Definition at line 779 of file class-wp-user.php.
References $blog_id, $cap_key, $wpdb, and _init_caps().
get ($key)
Retrieve the value of a property or meta key.
Retrieves from the users and usermeta table.
Since
3.3.0
Parameters
string $key Property
Returns
mixed
Definition at line 405 of file class-wp-user.php.
References __get().
static get_data_by ($field, $value) static
Return only the main user fields.
Since
3.3.0
4.4.0 Added 'ID' as an alias of 'id' for the $field parameter.
wpdb $wpdb WordPress database abstraction object.
Parameters
string $field The field to query against: 'id', 'ID', 'slug', 'email' or 'login'.
string | int $value The field value
Returns
object|false Raw user object
Definition at line 184 of file class-wp-user.php.
References $field, $user, $user_id, $value, $wpdb, sanitize_user(), update_user_caches(), and wp_cache_get().
get_role_caps ()
Retrieve all of the role capabilities and merge with individual capabilities.
All of the capabilities of the roles the user belongs to are merged with the users individual roles. This also means that the user can be denied specific roles that their role might have, but the specific user isn't granted permission to.
Since
2.0.0 public
Returns
array List of all capabilities for the user.
Definition at line 478 of file class-wp-user.php.
References $allcaps, and wp_roles().
Referenced by _init_caps(), add_cap(), add_role(), remove_all_caps(), remove_cap(), remove_role(), and set_role().
has_cap ($cap)
Whether user has capability or role name.
While checking against particular roles in place of a capability is supported in part, this practice is discouraged as it may produce unreliable results.
Since
2.0.0 public
See also
map_meta_cap()
Parameters
string $cap Capability name.
int $object_id,... Optional. ID of the specific object to check against if $cap is a "meta" cap. "Meta" capabilities, e.g. 'edit_post', 'edit_user', etc., are capabilities used by map_meta_cap() to map to other "primitive" capabilities, e.g. 'edit_posts', 'edit_others_posts', etc. The parameter is accessed via func_get_args() and passed to map_meta_cap().
Returns
bool Whether the current user has the given capability. If $cap is a meta cap and $object_id is passed, whether the current user has the given meta capability for the given object.
Dynamically filter a user's capabilities.
Since
2.0.0
3.7.0 Added the user object.
Parameters
array $allcaps An array of all the user's capabilities.
array $caps Actual capabilities for meta capability.
array $args Optional parameters passed to has_cap(), typically object ID.
WP_User $user The user object.
Definition at line 713 of file class-wp-user.php.
References $caps, __, _deprecated_argument(), apply_filters(), is_multisite(), is_super_admin(), and translate_level_to_cap().
has_prop ($key)
Determine whether a property or meta key is set.
Consults the users and usermeta tables.
Since
3.3.0
Parameters
string $key Property
Returns
bool
Definition at line 419 of file class-wp-user.php.
References __isset().
init ($data, $blog_id = '')
Sets up object properties, including capabilities.
Parameters
object $data User DB row object
int $blog_id Optional. The blog id to initialize for
Definition at line 163 of file class-wp-user.php.
References $blog_id, and $data.
Referenced by __construct().
level_reduction ($max, $item)
Choose the maximum level the user has.
Will compare the level from the $item parameter against the $max parameter. If the item is incorrect, then just the $max parameter value will be returned.
Used to get the max level based on the capabilities the user has. This is also based on roles, so if the user is assigned the Administrator role then the capability 'level_10' will exist and the user will get that value.
Since
2.0.0 public
Parameters
int $max Max level of user.
string $item Level capability name.
Returns
int Max Level.
Definition at line 616 of file class-wp-user.php.
remove_all_caps ()
Remove all of the capabilities of the user.
Since
2.1.0 public
wpdb $wpdb WordPress database abstraction object.
Definition at line 685 of file class-wp-user.php.
References $wpdb, delete_user_meta(), and get_role_caps().
remove_cap ($cap)
Remove capability from user.
Since
2.0.0 public
Parameters
string $cap Capability name.
Definition at line 667 of file class-wp-user.php.
References get_role_caps(), update_user_level_from_caps(), and update_user_meta().
remove_role ($role)
Remove role from user.
Since
2.0.0 public
Parameters
string $role Role name.
Fires immediately after a role as been removed from a user.
Since
4.3.0
Parameters
int $user_id The user ID.
string $role The removed role.
Definition at line 535 of file class-wp-user.php.
References do_action(), get_role_caps(), update_user_level_from_caps(), and update_user_meta().
set_role ($role)
Set the role of the user.
This will remove the previous roles of the user and assign the user the new one. You can set the role to an empty string and it will remove all of the roles from the user.
Since
2.0.0 public
Parameters
string $role Role name.
Fires after the user's role has changed.
Since
2.9.0
3.6.0 Added $old_roles to include an array of the user's previous roles.
Parameters
int $user_id The user ID.
string $role The new role.
array $old_roles An array of the user's previous roles.
Definition at line 566 of file class-wp-user.php.
References $roles, do_action(), get_role_caps(), update_user_level_from_caps(), and update_user_meta().
to_array ()
Return an array representation.
Since
3.5.0
Returns
array Array representation.
Definition at line 430 of file class-wp-user.php.
translate_level_to_cap ($level)
Convert numeric level to level capability name.
Prepends 'level_' to level number.
Since
2.0.0 public
Parameters
int $level Level number, 1 to 10.
Returns
string
Definition at line 766 of file class-wp-user.php.
Referenced by has_cap().
update_user_level_from_caps ()
Update the maximum user level for the user.
Updates the 'user_level' user metadata (includes prefix that is the database table prefix) with the maximum user level. Gets the value from the all of the capabilities that the user has.
Since
2.0.0 public
wpdb $wpdb WordPress database abstraction object.
Definition at line 637 of file class-wp-user.php.
References $wpdb, and update_user_meta().
Referenced by add_cap(), add_role(), remove_cap(), remove_role(), and set_role().
Field Documentation
$allcaps = array()
Definition at line 86 of file class-wp-user.php.
Referenced by get_role_caps().
$back_compat_keys static private
Definition at line 102 of file class-wp-user.php.
$cap_key
Definition at line 68 of file class-wp-user.php.
Referenced by _init_caps(), and for_blog().
$caps = array()
Definition at line 59 of file class-wp-user.php.
Referenced by has_cap().
$data
Definition at line 41 of file class-wp-user.php.
Referenced by __construct(), and init().
$filter = null
Definition at line 95 of file class-wp-user.php.
$ID = 0
Definition at line 50 of file class-wp-user.php.
Referenced by __get().
$roles = array()
Definition at line 77 of file class-wp-user.php.
Referenced by set_role().
The documentation for this class was generated from the following file:
class-wp-user.php