GravityView: WP_oEmbed Class Reference
WP_oEmbed Class Reference
Public Member Functions
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ()
Constructor.
_strip_newlines ($html, $data, $url)
Strip any new lines from the HTML.
data2html ($data, $url)
Converts a data object from WP_oEmbed::fetch() and returns the HTML.
discover ($url)
Attempts to discover link tags at the given URL for an oEmbed provider.
fetch ($provider, $url, $args= '')
Connects to a oEmbed provider and returns the result.
get_html ($url, $args= '')
The do-it-all function that takes a URL and attempts to return the HTML.
get_provider ($url, $args= '')
Takes a URL and returns the corresponding oEmbed provider's URL, if there is one.
Static Public Member Functions
static _add_provider_early ($format, $provider, $regex=false)
Add an oEmbed provider just-in-time when wp_oembed_add_provider() is called before the 'plugins_loaded' hook.
static _remove_provider_early ($format)
Remove an oEmbed provider just-in-time when wp_oembed_remove_provider() is called before the 'plugins_loaded' hook.
Data Fields
$providers = array()
Static Public Attributes
static $early_providers = array()
Private Member Functions
_fetch_with_format ($provider_url_with_args, $format)
Fetches result from an oEmbed provider for a specific format and complete provider URL.
_parse_json ($response_body)
Parses a json response body.
_parse_xml ($response_body)
Parses an XML response body.
_parse_xml_body ($response_body)
Helper function for parsing an XML response body.
Private Attributes
$compat_methods = array('_fetch_with_format', '_parse_json', '_parse_xml', '_parse_body')
Detailed Description
Definition at line 20 of file tmp/wordpress/wp-includes/class-oembed.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Since
2.9.0
Filter the list of whitelisted oEmbed providers.
Since WordPress 4.4, oEmbed discovery is enabled for all users and allows embedding of sanitized iframes. The providers in this list are whitelisted, meaning they are trusted and allowed to embed any content, such as iframes, videos, JavaScript, and arbitrary HTML.
Supported providers:
Provider Flavor HTTPS Since
Dailymotion dailymotion.com Yes 2.9.0
Flickr flickr.com Yes 2.9.0
Hulu hulu.com Yes 2.9.0
Photobucket photobucket.com No 2.9.0
Scribd scribd.com Yes 2.9.0
Vimeo vimeo.com Yes 2.9.0
WordPress.tv wordpress.tv Yes 2.9.0
YouTube youtube.com/watch Yes 2.9.0
Funny or Die funnyordie.com Yes 3.0.0
Polldaddy polldaddy.com Yes 3.0.0
SmugMug smugmug.com Yes 3.0.0
YouTube youtu.be Yes 3.0.0
Twitter twitter.com Yes 3.4.0
Instagram instagram.com Yes 3.5.0
Instagram instagr.am Yes 3.5.0
Slideshare slideshare.net Yes 3.5.0
SoundCloud soundcloud.com Yes 3.5.0
Dailymotion dai.ly No 3.6.0
Flickr flic.kr Yes 3.6.0
Spotify spotify.com Yes 3.6.0
Imgur imgur.com Yes 3.9.0
Meetup.com meetup.com Yes 3.9.0
Meetup.com meetu.ps Yes 3.9.0
Animoto animoto.com Yes 4.0.0
Animoto video214.com Yes 4.0.0
CollegeHumor collegehumor.com Yes 4.0.0
Issuu issuu.com Yes 4.0.0
Mixcloud mixcloud.com Yes 4.0.0
Polldaddy poll.fm Yes 4.0.0
TED ted.com Yes 4.0.0
YouTube youtube.com/playlist Yes 4.0.0
Vine vine.co Yes 4.1.0
Tumblr tumblr.com Yes 4.2.0
Kickstarter kickstarter.com Yes 4.2.0
Kickstarter kck.st Yes 4.2.0
Cloudup cloudup.com Yes 4.4.0
ReverbNation reverbnation.com Yes 4.4.0
VideoPress videopress.com Yes 4.4.0
Reddit reddit.com Yes 4.4.0
Speaker Deck speakerdeck.com Yes 4.4.0
No longer supported providers:
Provider Flavor HTTPS Since Removed
Qik qik.com Yes 2.9.0 3.9.0
Viddler viddler.com Yes 2.9.0 4.0.0
Revision3 revision3.com No 2.9.0 4.2.0
Blip blip.tv No 2.9.0 4.4.0
Rdio rdio.com Yes 3.6.0 4.4.1
Rdio rd.io Yes 3.6.0 4.4.1
See also
wp_oembed_add_provider()
Since
2.9.0
Parameters
array $providers An array of popular oEmbed providers.
Definition at line 35 of file tmp/wordpress/wp-includes/class-oembed.php.
References $format, $providers, add_filter(), apply_filters(), and home_url().
Member Function Documentation
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
Since
4.0.0 public
Parameters
callable $name Method to call.
array $arguments Arguments to pass when calling.
Returns
mixed|bool Return value of the callback, false otherwise.
Definition at line 180 of file tmp/wordpress/wp-includes/class-oembed.php.
References $name.
static _add_provider_early ($format, $provider, $regex = false) static
Add an oEmbed provider just-in-time when wp_oembed_add_provider() is called before the 'plugins_loaded' hook.
The just-in-time addition is for the benefit of the 'oembed_providers' filter.
Since
4.0.0 public
See also
wp_oembed_add_provider()
Parameters
string $format Format of URL that this provider can handle. You can use asterisks as wildcards.
string $provider The URL to the oEmbed provider..
bool $regex Optional. Whether the $format parameter is in a regex format. Default false.
Definition at line 245 of file tmp/wordpress/wp-includes/class-oembed.php.
References $format.
Referenced by wp_oembed_add_provider().
_fetch_with_format ($provider_url_with_args, $format) private
Fetches result from an oEmbed provider for a specific format and complete provider URL.
Since
3.0.0 private
Parameters
string $provider_url_with_args URL to the provider with full arguments list (url, maxheight, etc.)
string $format Format to use
Returns
false|object|WP_Error False on failure, otherwise the result in the form of an object.
This filter is documented in wp-includes/class-oembed.php
Definition at line 424 of file tmp/wordpress/wp-includes/class-oembed.php.
References $format, add_query_arg(), apply_filters(), wp_remote_retrieve_body(), wp_remote_retrieve_response_code(), and wp_safe_remote_get().
Referenced by fetch().
_parse_json ($response_body) private
Parses a json response body.
Since
3.0.0 private
Parameters
string $response_body
Returns
object|false
Definition at line 448 of file tmp/wordpress/wp-includes/class-oembed.php.
_parse_xml ($response_body) private
Parses an XML response body.
Since
3.0.0 private
Parameters
string $response_body
Returns
object|false
Definition at line 462 of file tmp/wordpress/wp-includes/class-oembed.php.
References $errors, and _parse_xml_body().
_parse_xml_body ($response_body) private
Helper function for parsing an XML response body.
Since
3.6.0 private
Parameters
string $response_body
Returns
object|false
Definition at line 486 of file tmp/wordpress/wp-includes/class-oembed.php.
References $value.
Referenced by _parse_xml().
static _remove_provider_early ($format) static
Remove an oEmbed provider just-in-time when wp_oembed_remove_provider() is called before the 'plugins_loaded' hook.
The just-in-time removal is for the benefit of the 'oembed_providers' filter.
Since
4.0.0 public
See also
wp_oembed_remove_provider()
Parameters
string $format The format of URL that this provider can handle. You can use asterisks as wildcards.
Definition at line 268 of file tmp/wordpress/wp-includes/class-oembed.php.
References $format.
Referenced by wp_oembed_remove_provider().
_strip_newlines ($html, $data, $url)
Strip any new lines from the HTML.
public
Parameters
string $html Existing HTML.
object $data Data object from WP_oEmbed::data2html()
string $url The original URL passed to oEmbed.
Returns
string Possibly modified $html
Definition at line 577 of file tmp/wordpress/wp-includes/class-oembed.php.
References $count, $i, and str_replace.
data2html ($data, $url)
Converts a data object from WP_oEmbed::fetch() and returns the HTML.
Parameters
object $data A data object result from an oEmbed provider.
string $url The URL to the content that is desired to be embedded.
Returns
false|string False on error, otherwise the HTML needed to embed.
Filter the returned oEmbed HTML.
Use this filter to add support for custom data types, or to filter the result.
Since
2.9.0
Parameters
string $return The returned oEmbed HTML.
object $data A data object result from an oEmbed provider.
string $url The URL of the content to be embedded.
Definition at line 522 of file tmp/wordpress/wp-includes/class-oembed.php.
References $title, $url, apply_filters(), esc_attr(), esc_html, and esc_url.
Referenced by get_html().
discover ($url)
Attempts to discover link tags at the given URL for an oEmbed provider.
Parameters
string $url The URL that should be inspected for discovery <link> tags.
Returns
false|string False on failure, otherwise the oEmbed provider URL.
Filter oEmbed remote get arguments.
Since
4.0.0
See also
WP_Http::request()
Parameters
array $args oEmbed remote get arguments.
string $url URL to be inspected.
Filter the link types that contain oEmbed provider URLs.
Since
2.9.0
Parameters
array $format Array of oEmbed link types. Accepts 'application/json+oembed', 'text/xml+oembed', and 'application/xml+oembed' (incorrect, used by at least Vimeo).
Definition at line 310 of file tmp/wordpress/wp-includes/class-oembed.php.
References $format, $link, $providers, $url, apply_filters(), elseif, shortcode_parse_atts(), wp_remote_retrieve_body(), and wp_safe_remote_get().
Referenced by get_provider().
fetch ($provider, $url, $args = '')
Connects to a oEmbed provider and returns the result.
Parameters
string $provider The URL to the oEmbed provider.
string $url The URL to the content that is desired to be embedded.
array $args Optional arguments. Usually passed from a shortcode.
Returns
false|object False on failure, otherwise the result in the form of an object.
Filter the oEmbed URL to be fetched.
Since
2.9.0
Parameters
string $provider URL of the oEmbed provider.
string $url URL of the content to be embedded.
array $args Optional arguments, usually passed from a shortcode.
Definition at line 388 of file tmp/wordpress/wp-includes/class-oembed.php.
References $format, $url, _fetch_with_format(), add_query_arg(), apply_filters(), is_wp_error(), wp_embed_defaults(), and wp_parse_args().
Referenced by get_html().
get_html ($url, $args = '')
The do-it-all function that takes a URL and attempts to return the HTML.
See also
WP_oEmbed::fetch()
WP_oEmbed::data2html()
Parameters
string $url The URL to the content that should be attempted to be embedded.
array $args Optional arguments. Usually passed from a shortcode.
Returns
false|string False on failure, otherwise the UNSANITIZED (and potentially unsafe) HTML that should be used to embed.
Filter the HTML returned by the oEmbed provider.
Since
2.9.0
Parameters
string $data The returned oEmbed HTML.
string $url URL of the content to be embedded.
array $args Optional arguments, usually passed from a shortcode.
Definition at line 286 of file tmp/wordpress/wp-includes/class-oembed.php.
References $url, apply_filters(), data2html(), fetch(), and get_provider().
get_provider ($url, $args = '')
Takes a URL and returns the corresponding oEmbed provider's URL, if there is one.
Since
4.0.0 public
See also
WP_oEmbed::discover()
Parameters
string $url The URL to the content.
string | array $args Optional provider arguments.
Returns
false|string False on failure, otherwise the oEmbed provider URL.
Definition at line 199 of file tmp/wordpress/wp-includes/class-oembed.php.
References $url, discover(), and str_replace.
Referenced by get_html().
Field Documentation
$compat_methods = array('_fetch_with_format', '_parse_json', '_parse_xml', '_parse_body') private
Definition at line 28 of file tmp/wordpress/wp-includes/class-oembed.php.
$early_providers = array() static
Definition at line 26 of file tmp/wordpress/wp-includes/class-oembed.php.
$providers = array()
Definition at line 21 of file tmp/wordpress/wp-includes/class-oembed.php.
Referenced by __construct(), and discover().
The documentation for this class was generated from the following file:
tmp/wordpress/wp-includes/class-oembed.php