GravityView: WP_SimplePie_File Class Reference
WP_SimplePie_File Class Reference
Public Member Functions
__construct ($url, $timeout=10, $redirects=5, $headers=null, $useragent=null, $force_fsockopen=false)
Public Member Functions inherited from SimplePie_File
__construct ($url, $timeout=10, $redirects=5, $headers=null, $useragent=null, $force_fsockopen=false)
Additional Inherited Members
Data Fields inherited from SimplePie_File
$body
$error
$headers = array()
$method = SIMPLEPIE_FILE_SOURCE_NONE
$redirects = 0
$status_code
$success = true
$url
$useragent
Detailed Description
Definition at line 95 of file class-feed.php.
Constructor & Destructor Documentation
__construct ($url, $timeout = 10, $redirects = 5, $headers = null, $useragent = null, $force_fsockopen = false)
Definition at line 97 of file class-feed.php.
References SimplePie_File\$headers, SimplePie_File\$redirects, SimplePie_File\$url, SimplePie_File\$useragent, is_wp_error(), SIMPLEPIE_FILE_SOURCE_REMOTE, SIMPLEPIE_USERAGENT, wp_remote_retrieve_body(), wp_remote_retrieve_headers(), wp_remote_retrieve_response_code(), and wp_safe_remote_request().
The documentation for this class was generated from the following file:
class-feed.php