GravityView: GravityView_Entry_Approval_Status_Test Class Reference
GravityView_Entry_Approval_Status_Test Class Reference
Public Member Functions
test_get_values ()
test_is_status ()
test_is_valid ()
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
Since
1.18 approval approval_status
Definition at line 10 of file GravityView_Entry_Approval_Status_Test.php.
Member Function Documentation
test_get_values ()
Since
1.18 GravityView_Entry_Approval_Status::get_label() GravityView_Entry_Approval_Status::get_string() GravityView_Entry_Approval_Status::get_key() GravityView_Entry_Approval_Status::get_title_attr()
Definition at line 19 of file GravityView_Entry_Approval_Status_Test.php.
References GravityView_Entry_Approval_Status\get_all(), GravityView_Entry_Approval_Status\get_key(), GravityView_Entry_Approval_Status\get_label(), GravityView_Entry_Approval_Status\get_string(), and GravityView_Entry_Approval_Status\get_title_attr().
test_is_status ()
Since
1.18 GravityView_Entry_Approval_Status::maybe_convert_status() GravityView_Entry_Approval_Status::is_approved() GravityView_Entry_Approval_Status::is_disapproved() GravityView_Entry_Approval_Status::is_unapproved()
Definition at line 76 of file GravityView_Entry_Approval_Status_Test.php.
References GravityView_Entry_Approval_Status\APPROVED, GravityView_Entry_Approval_Status\DISAPPROVED, GravityView_Entry_Approval_Status\is_approved(), GravityView_Entry_Approval_Status\is_disapproved(), GravityView_Entry_Approval_Status\is_unapproved(), and GravityView_Entry_Approval_Status\UNAPPROVED.
test_is_valid ()
Since
1.18 GravityView_Entry_Approval_Status::is_valid()
Definition at line 50 of file GravityView_Entry_Approval_Status_Test.php.
References GravityView_Entry_Approval_Status\APPROVED, GravityView_Entry_Approval_Status\DISAPPROVED, GravityView_Entry_Approval_Status\is_valid(), and GravityView_Entry_Approval_Status\UNAPPROVED.
The documentation for this class was generated from the following file:
GravityView_Entry_Approval_Status_Test.php