GravityView: StringExtractor Class Reference
StringExtractor Class Reference
Responsible for extracting translatable strings from PHP source files in the form of Translations instances.
Public Member Functions
__construct ($rules=array())
does_file_name_match ($path, $excludes, $includes)
entry_from_call ($call, $file_name)
extract_from_code ($code, $file_name)
extract_from_directory ($dir, $excludes=array(), $includes=array(), $prefix= '')
extract_from_file ($file_name, $prefix)
find_function_calls ($function_names, $code)
Finds all function calls in $code and returns an array with an associative array for each function:
is_directory_excluded ($directory, $excludes)
Data Fields
$comment_prefix = 'translators:'
$rules
Detailed Description
Responsible for extracting translatable strings from PHP source files in the form of Translations instances.
Definition at line 10 of file extract.php.
Constructor & Destructor Documentation
__construct ($rules = array())
Definition at line 20 of file extract.php.
References $rules.
Member Function Documentation
does_file_name_match ($path, $excludes, $includes)
Definition at line 51 of file extract.php.
Referenced by extract_from_directory().
entry_from_call ($call, $file_name)
Definition at line 88 of file extract.php.
References $entry, and $i.
Referenced by extract_from_code().
extract_from_code ($code, $file_name)
Definition at line 154 of file extract.php.
References $entry, entry_from_call(), and find_function_calls().
Referenced by extract_from_file().
extract_from_directory ($dir, $excludes = array(), $includes = array(), $prefix = '')
Definition at line 24 of file extract.php.
References does_file_name_match(), extract_from_file(), and is_directory_excluded().
extract_from_file ($file_name, $prefix)
Definition at line 46 of file extract.php.
References extract_from_code().
Referenced by extract_from_directory().
find_function_calls ($function_names, $code)
Finds all function calls in $code and returns an array with an associative array for each function:
name - name of the function
args - array for the function arguments. Each string literal is represented by itself, other arguments are represented by null.
line - line number
Definition at line 176 of file extract.php.
Referenced by extract_from_code().
is_directory_excluded ($directory, $excludes)
Definition at line 74 of file extract.php.
Referenced by extract_from_directory().
Field Documentation
$comment_prefix = 'translators:'
Definition at line 18 of file extract.php.
$rules
Initial value:
= array(
        '__' => array( 'string' ),
        '_e' => array( 'string' ),
        '_n' => array( 'singular', 'plural' ),
    )
Definition at line 12 of file extract.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
extract.php