GravityView: WP_Text_Diff_Renderer_Table Class Reference
WP_Text_Diff_Renderer_Table Class Reference
Table renderer to display the diff lines.
Public Member Functions
__construct ($params=array())
Constructor - Call parent constructor with params array.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
_added ($lines, $encode=true)
public
_changed ($orig, $final)
Process changed lines to do word-by-word diffs for extra highlighting.
_context ($lines, $encode=true)
public
_deleted ($lines, $encode=true)
public
_lines ($lines, $prefix=' ')
_startBlock ($header)
addedLine ($line)
compute_string_distance ($string1, $string2)
Computes a number that is intended to reflect the "distance" between two strings.
contextLine ($line)
deletedLine ($line)
difference ($a, $b)
emptyLine ()
interleave_changed_lines ($orig, $final)
Takes changed blocks and matches which rows in orig turned into which rows in final.
Public Member Functions inherited from Text_Diff_Renderer
__construct ($params=array())
Constructor.
_added ($lines)
_block ($xbeg, $xlen, $ybeg, $ylen, &$edits)
_blockHeader ($xbeg, $xlen, $ybeg, $ylen)
_changed ($orig, $final)
_context ($lines)
_deleted ($lines)
_endBlock ()
_endDiff ()
_lines ($lines, $prefix= ' ')
_startBlock ($header)
_startDiff ()
getParams ()
Get any renderer parameters.
render ($diff)
Renders a diff.
Text_Diff_Renderer ($params=array())
PHP4 constructor.
Data Fields
$_leading_context_lines = 10000
$_trailing_context_lines = 10000
Data Fields inherited from Text_Diff_Renderer
$_leading_context_lines = 0
Number of leading context "lines" to preserve.
$_trailing_context_lines = 0
Number of trailing context "lines" to preserve.
Protected Attributes
$_diff_threshold = 0.6
$_show_split_view = true
$compat_fields = array('_show_split_view', 'inline_diff_renderer', '_diff_threshold')
$inline_diff_renderer = 'WP_Text_Diff_Renderer_inline'
Detailed Description
Table renderer to display the diff lines.
Since
2.6.0 Text_Diff_Renderer Extends
Definition at line 26 of file wp-diff.php.
Constructor & Destructor Documentation
__construct ($params = array())
Constructor - Call parent constructor with params array.
This will set class properties based on the key value pairs in the array.
Since
2.6.0
Parameters
array $params
Definition at line 82 of file wp-diff.php.
Member Function Documentation
__get ($name)
Make private properties readable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to get.
Returns
mixed Property.
Definition at line 469 of file wp-diff.php.
References $name.
__isset ($name)
Make private properties checkable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to check if set.
Returns
bool Whether the property is set.
Definition at line 500 of file wp-diff.php.
References $name.
__set ($name, $value)
Make private properties settable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to check if set.
mixed $value Property value.
Returns
mixed Newly-set property.
Definition at line 485 of file wp-diff.php.
References $name, and $value.
__unset ($name)
Make private properties un-settable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to unset.
Definition at line 514 of file wp-diff.php.
References $name.
_added ($lines, $encode = true)
public
Parameters
array $lines
bool $encode
Returns
string
Contextually filter a diffed line.
Filters TextDiff processing of diffed line. By default, diffs are processed with htmlspecialchars. Use this filter to remove or change the processing. Passes a context indicating if the line is added, deleted or unchanged.
Since
4.1.0
Parameters
String $processed_line The processed diffed line.
String $line The unprocessed diffed line.
string null The line context. Values are 'added', 'deleted' or 'unchanged'.
Definition at line 155 of file wp-diff.php.
References addedLine(), apply_filters(), and emptyLine().
Referenced by _changed().
_changed ($orig, $final)
Process changed lines to do word-by-word diffs for extra highlighting.
(TRAC style) sometimes these lines can actually be deleted or added rows. We do additional processing to figure that out
public
Since
2.6.0
Parameters
array $orig
array $final
Returns
string
Definition at line 252 of file wp-diff.php.
References $inline_diff_renderer, _added(), _deleted(), addedLine(), deletedLine(), elseif, emptyLine(), and interleave_changed_lines().
_context ($lines, $encode = true)
public
Parameters
array $lines
bool $encode
Returns
string
This filter is documented in wp-includes/wp-diff.php
Definition at line 221 of file wp-diff.php.
References apply_filters(), contextLine(), and emptyLine().
_deleted ($lines, $encode = true)
public
Parameters
array $lines
bool $encode
Returns
string
This filter is documented in wp-includes/wp-diff.php
Definition at line 194 of file wp-diff.php.
References apply_filters(), deletedLine(), and emptyLine().
Referenced by _changed().
_lines ($lines, $prefix = ' ')
Parameters
array $lines
string $prefix
Definition at line 104 of file wp-diff.php.
_startBlock ($header)
Parameters
string $header
Returns
string
Definition at line 94 of file wp-diff.php.
addedLine ($line)
Parameters
string $line HTML-escape the value.
Returns
string
Definition at line 113 of file wp-diff.php.
Referenced by _added(), and _changed().
compute_string_distance ($string1, $string2)
Computes a number that is intended to reflect the "distance" between two strings.
Since
2.6.0
Parameters
string $string1
string $string2
Returns
int
Definition at line 432 of file wp-diff.php.
Referenced by interleave_changed_lines().
contextLine ($line)
Parameters
string $line HTML-escape the value.
Returns
string
Definition at line 134 of file wp-diff.php.
Referenced by _context().
deletedLine ($line)
Parameters
string $line HTML-escape the value.
Returns
string
Definition at line 124 of file wp-diff.php.
Referenced by _changed(), and _deleted().
difference ($a, $b)
Since
2.6.0
Parameters
int $a
int $b
Returns
int
Definition at line 456 of file wp-diff.php.
emptyLine ()
Returns
string
Definition at line 143 of file wp-diff.php.
Referenced by _added(), _changed(), _context(), and _deleted().
interleave_changed_lines ($orig, $final)
Takes changed blocks and matches which rows in orig turned into which rows in final.
Returns *_matches (which rows match with which) *_rows (order of rows in each column interleaved with blank rows as necessary)
Since
2.6.0
Parameters
array $orig
array $final
Returns
array
Definition at line 343 of file wp-diff.php.
References $keys, compute_string_distance(), and elseif.
Referenced by _changed().
Field Documentation
$_diff_threshold = 0.6 protected
Definition at line 51 of file wp-diff.php.
$_leading_context_lines = 10000
Definition at line 34 of file wp-diff.php.
$_show_split_view = true protected
Definition at line 69 of file wp-diff.php.
$_trailing_context_lines = 10000
Definition at line 42 of file wp-diff.php.
$compat_fields = array('_show_split_view', 'inline_diff_renderer', '_diff_threshold') protected
Definition at line 71 of file wp-diff.php.
$inline_diff_renderer = 'WP_Text_Diff_Renderer_inline' protected
Definition at line 60 of file wp-diff.php.
Referenced by _changed().
The documentation for this class was generated from the following file:
wp-diff.php