GravityView: GFExport Class Reference
GFExport Class Reference
Static Public Member Functions
static add_default_export_fields ($form)
static export_form_page ()
static export_lead_page ()
static export_page ()
static get_gmt_date ($local_date)
static get_gmt_timestamp ($local_timestamp)
static get_tabs ()
static import_file ($filepath, &$forms=null)
static import_form_page ()
static import_json ($forms_json, &$forms=null)
static import_xml ($xmlstr, &$forms=null)
static maybe_export ()
static page_footer ()
static page_header ($title= '')
static set_property_as_key ($array, $property)
static start_export ($form)
Static Private Member Functions
static cleanup (&$forms)
static get_entry_meta ($form)
static get_field_row_count ($form, $exported_field_ids, $entry_count)
Static Private Attributes
static $min_import_version = '1.3.12.3'
Detailed Description
Definition at line 7 of file gravityforms/export.php.
Member Function Documentation
static add_default_export_fields ($form) static
Definition at line 792 of file gravityforms/export.php.
References $form, __, apply_filters(), and GFFormsModel\convert_field_objects().
Referenced by GFForms\select_export_form().
static cleanup (& $forms) static private
Definition at line 251 of file gravityforms/export.php.
References $count, $field, $form, $forms, $i, $id, GFFormsModel\convert_field_objects(), and GFFormsModel\get_input_type().
static export_form_page () static
Definition at line 360 of file gravityforms/export.php.
References $form, $forms, __, esc_html, esc_html_e, GFFormsModel\get_forms(), gform_tooltip(), input, label, li, name, null, page_footer(), page_header(), wp_die(), and wp_nonce_field().
static export_lead_page () static
Definition at line 407 of file gravityforms/export.php.
References $form, $forms, __, esc_html, esc_html__(), esc_html_e, GFFormsModel\get_forms(), gform_tooltip(), height, input, label, li, name, null, page_footer(), page_header(), placeholder, width, wp_die(), and wp_nonce_field().
static export_page () static
Definition at line 105 of file gravityforms/export.php.
References do_action().
Referenced by GFForms\export_page().
static get_entry_meta ($form) static private
Definition at line 815 of file gravityforms/export.php.
References $form, $keys, and GFFormsModel\get_entry_meta().
static get_field_row_count ($form, $exported_field_ids, $entry_count) static private
Definition at line 565 of file gravityforms/export.php.
References $field, $field_ids, $form, $list, $wpdb, ARRAY_A, and GFAPI\get_fields_by_type().
static get_gmt_date ($local_date) static
Definition at line 620 of file gravityforms/export.php.
static get_gmt_timestamp ($local_timestamp) static
Definition at line 616 of file gravityforms/export.php.
References get_option().
static get_tabs () static
Definition at line 893 of file gravityforms/export.php.
References __, and apply_filters().
static import_file ($filepath, & $forms = null) static
Definition at line 137 of file gravityforms/export.php.
References $forms.
Referenced by GravityView_Ajax\import_form(), GFForms\maybe_import_forms(), and GFForms\maybe_import_theme_forms().
static import_form_page () static
Definition at line 304 of file gravityforms/export.php.
References $count, $forms, __, esc_html_e, gform_tooltip(), input, label, name, page_footer(), page_header(), wp_die(), and wp_nonce_field().
static import_json ($forms_json, & $forms = null) static
Fires after forms have been imported.
Parameters
array $forms An array imported form objects.
Definition at line 147 of file gravityforms/export.php.
References $form_id, $forms, GFAPI\add_forms(), do_action(), and is_wp_error().
static import_xml ($xmlstr, & $forms = null) static
Definition at line 181 of file gravityforms/export.php.
References $count, $form, $form_id, $forms, $options, $title, apply_filters(), GFFormsModel\insert_form(), GFFormsModel\is_unique_title(), GFFormsModel\trim_conditional_logic_values(), GFFormsModel\trim_form_meta_values(), and GFFormsModel\update_form_meta().
static maybe_export () static
Allows you to filter and modify the Export Form
Parameters
array $form Assign which Gravity Form to change the export form for
Definition at line 11 of file gravityforms/export.php.
References $charset, $field, $form, $form_id, $forms, GFForms\$version, __, date, GFFormsModel\get_form_meta(), GFFormsModel\get_form_meta_by_id(), GFFormsModel\get_input_type(), get_option(), sanitize_title_with_dashes(), and start_export().
Referenced by GFForms\init().
static page_footer () static
Definition at line 881 of file gravityforms/export.php.
static page_header ($title = '') static
Definition at line 826 of file gravityforms/export.php.
References $min, $title, $url, add_query_arg(), esc_html, get_tabs(), li, wp_print_styles(), and wp_register_style().
static set_property_as_key ($array, $property) static
Definition at line 295 of file gravityforms/export.php.
static start_export ($form) static
Fires after exporting all the entries in form
Parameters
array $form The Form object to get the entries from
string $start_date The start date for when the export of entries should take place
string $end_date The end date for when the export of entries should stop
array $fields The specified fields where the entries should be exported from
Definition at line 629 of file gravityforms/export.php.
References $field, $field_id, $form, $form_id, $i, $label, $leads, $list, $value, apply_filters(), GFAPI\count_entries(), date_i18n(), do_action(), GFAPI\get_entries(), GFFormsModel\get_field(), maybe_unserialize(), mysql2date(), seems_utf8(), and str_replace.
Referenced by maybe_export(), and GFForms\start_export().
Field Documentation
$min_import_version = '1.3.12.3' static private
Definition at line 9 of file gravityforms/export.php.
The documentation for this class was generated from the following file:
gravityforms/export.php