GravityView: WP_User_Query Class Reference
WP_User_Query Class Reference
Core class used for querying users.
Public Member Functions
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
__construct ($query=null)
PHP5 constructor.
__get ($name)
Make private properties readable for backwards compatibility.
__isset ($name)
Make private properties checkable for backwards compatibility.
__set ($name, $value)
Make private properties settable for backwards compatibility.
__unset ($name)
Make private properties un-settable for backwards compatibility.
get ($query_var)
Retrieve query variable.
get_results ()
Return the list of users.
get_total ()
Return the total number of users for the current query.
prepare_query ($query=array())
Prepare the query variables.
query ()
Execute the query, with the current variables.
set ($query_var, $value)
Set query variable.
Static Public Member Functions
static fill_query_vars ($args)
Fills in missing query variables with default values.
Data Fields
$meta_query = false
$query_fields
$query_from
$query_limit
$query_orderby
$query_vars = array()
$query_where
$request
Protected Member Functions
get_search_sql ($string, $cols, $wild=false)
Used internally to generate an SQL string for searching across multiple columns.
parse_order ($order)
Parse an 'order' query variable and cast it to ASC or DESC as necessary.
parse_orderby ($orderby)
Parse and sanitize 'orderby' keys passed to the user query.
Private Attributes
$compat_fields = array('results', 'total_users')
$results
$total_users = 0
Detailed Description
Core class used for querying users.
Since
3.1.0
See also
WP_User_Query::prepare_query() for information on accepted arguments.
Definition at line 17 of file class-wp-user-query.php.
Constructor & Destructor Documentation
__construct ($query = null)
PHP5 constructor.
Since
3.1.0
Parameters
null | string | array $query Optional. The query variables.
Definition at line 80 of file class-wp-user-query.php.
References prepare_query(), and query().
Member Function Documentation
__call ($name, $arguments)
Make private/protected methods readable for backwards compatibility.
Since
4.0.0 public
Parameters
callable $name Method to call.
array $arguments Arguments to pass when calling.
Returns
mixed Return value of the callback, false otherwise.
Definition at line 792 of file class-wp-user-query.php.
References $name.
__get ($name)
Make private properties readable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to get.
Returns
mixed Property.
Definition at line 731 of file class-wp-user-query.php.
References $name.
__isset ($name)
Make private properties checkable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to check if set.
Returns
bool Whether the property is set.
Definition at line 762 of file class-wp-user-query.php.
References $name.
__set ($name, $value)
Make private properties settable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to check if set.
mixed $value Property value.
Returns
mixed Newly-set property.
Definition at line 747 of file class-wp-user-query.php.
References $name, and $value.
__unset ($name)
Make private properties un-settable for backwards compatibility.
Since
4.0.0 public
Parameters
string $name Property to unset.
Definition at line 776 of file class-wp-user-query.php.
References $name.
static fill_query_vars ($args) static
Fills in missing query variables with default values.
Since
4.4.0 public
Parameters
array $args Query vars, as passed to WP_User_Query.
Returns
array Complete query variables with undefined ones filled in with defaults.
Definition at line 96 of file class-wp-user-query.php.
References $GLOBALS, null, and wp_parse_args().
Referenced by prepare_query().
get ($query_var)
Retrieve query variable.
Since
3.5.0 public
Parameters
string $query_var Query variable key.
Returns
mixed
Definition at line 572 of file class-wp-user-query.php.
References null.
get_results ()
Return the list of users.
Since
3.1.0 public
Returns
array Array of results.
Definition at line 633 of file class-wp-user-query.php.
References $results.
get_search_sql ($string, $cols, $wild = false) protected
Used internally to generate an SQL string for searching across multiple columns.
protected
Since
3.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $string
array $cols
bool $wild Whether to allow wildcard searches. Default is false for Network Admin, true for single site. Single site allows leading and trailing wildcards, Network Admin only trailing.
Returns
string
Definition at line 606 of file class-wp-user-query.php.
References $wpdb.
Referenced by prepare_query().
get_total ()
Return the total number of users for the current query.
Since
3.1.0 public
Returns
int Number of total users.
Definition at line 645 of file class-wp-user-query.php.
References $total_users.
parse_order ($order) protected
Parse an 'order' query variable and cast it to ASC or DESC as necessary.
Since
4.2.0 protected
Parameters
string $order The 'order' query variable.
Returns
string The sanitized 'order' query variable.
Definition at line 710 of file class-wp-user-query.php.
Referenced by prepare_query().
parse_orderby ($orderby) protected
Parse and sanitize 'orderby' keys passed to the user query.
Since
4.2.0 protected
wpdb $wpdb WordPress database abstraction object.
Parameters
string $orderby Alias for the field to order by.
Returns
string Value to used in the ORDER clause, if $orderby is valid.
Definition at line 660 of file class-wp-user-query.php.
References $wpdb, elseif, esc_sql(), get_posts_by_author_sql(), and wp_parse_id_list().
Referenced by prepare_query().
prepare_query ($query = array())
Prepare the query variables.
Since
3.1.0
4.1.0 Added the ability to order by the include value.
4.2.0 Added 'meta_value_num' support for $orderby parameter. Added multi-dimensional array syntax for $orderby parameter.
4.3.0 Added 'has_published_posts' parameter.
4.4.0 Added 'paged', 'role__in', and 'role__not_in' parameters. The 'role' parameter was updated to permit an array or comma-separated list of values. The 'number' parameter was updated to support querying for all users with using -1.
public
wpdb $wpdb WordPress database abstraction object. int $blog_id
Parameters
string | array $query { Optional. Array or string of Query parameters.
int $blog_id The site ID. Default is the global blog id. string|array $role An array or a comma-separated list of role names that users must match to be included in results. Note that this is an inclusive list: users must match each role. Default empty. array $role__in An array of role names. Matched users must have at least one of these roles. Default empty array. array $role__not_in An array of role names to exclude. Users matching one or more of these roles will not be included in results. Default empty array. string $meta_key User meta key. Default empty. string $meta_value User meta value. Default empty. string $meta_compare Comparison operator to test the $meta_value. Accepts '=', '!=', '>', '>=', '<', '<=', 'LIKE', 'NOT LIKE', 'IN', 'NOT IN', 'BETWEEN', 'NOT BETWEEN', 'EXISTS', 'NOT EXISTS', 'REGEXP', 'NOT REGEXP', or 'RLIKE'. Default '='. array $include An array of user IDs to include. Default empty array. array $exclude An array of user IDs to exclude. Default empty array. string $search Search keyword. Searches for possible string matches on columns. When $search_columns is left empty, it tries to determine which column to search in based on search string. Default empty. array $search_columns Array of column names to be searched. Accepts 'ID', 'login', 'nicename', 'email', 'url'. Default empty array. string|array $orderby Field(s) to sort the retrieved users by. May be a single value, an array of values, or a multi-dimensional array with fields as keys and orders ('ASC' or 'DESC') as values. Accepted values are 'ID', 'display_name' (or 'name'), 'include', 'user_login' (or 'login'), 'user_nicename' (or 'nicename'), 'user_email' (or 'email'), 'user_url' (or 'url'), 'user_registered' or 'registered'), 'post_count', 'meta_value', 'meta_value_num', the value of $meta_key, or an array key of $meta_query. To use 'meta_value' or 'meta_value_num', $meta_key must be also be defined. Default 'user_login'. string $order Designates ascending or descending order of users. Order values passed as part of an $orderby array take precedence over this parameter. Accepts 'ASC', 'DESC'. Default 'ASC'. int $offset Number of users to offset in retrieved results. Can be used in conjunction with pagination. Default 0. int $number Number of users to limit the query for. Can be used in conjunction with pagination. Value -1 (all) is supported, but should be used with caution on larger sites. Default empty (all users). int $paged When used with number, defines the page of results to return. Default 1. bool $count_total Whether to count the total number of users found. If pagination is not needed, setting this to false can improve performance. Default true. string|array $fields Which fields to return. Single or all fields (string), or array of fields. Accepts 'ID', 'display_name', 'user_login', 'user_nicename', 'user_email', 'user_url', 'user_registered'. Use 'all' for all fields and 'all_with_meta' to include meta fields. Default 'all'. string $who Type of users to query. Accepts 'authors'. Default empty (all users). bool|array $has_published_posts Pass an array of post types to filter results to users who have published posts in those post types. true is an alias for all public post types. }
Fires before the WP_User_Query has been parsed.
The passed WP_User_Query object contains the query variables, not yet passed into SQL.
Since
4.0.0
Parameters
WP_User_Query $this The current WP_User_Query instance, passed by reference.
Filter the columns to search in a WP_User_Query search.
The default columns depend on the search term, and include 'user_email', 'user_login', 'ID', 'user_url', 'display_name', and 'user_nicename'.
Since
3.6.0
Parameters
array $search_columns Array of column names to be searched.
string $search Text being searched.
WP_User_Query $this The current WP_User_Query instance.
Fires after the WP_User_Query has been parsed, and before the query is executed.
The passed WP_User_Query object contains SQL parts formed from parsing the given query.
Since
3.1.0
Parameters
WP_User_Query $this The current WP_User_Query instance, passed by reference.
Definition at line 200 of file class-wp-user-query.php.
References $blog_id, $field, $post_type, $query_fields, $query_vars, $wpdb, absint(), apply_filters(), do_action(), do_action_ref_array(), elseif, fill_query_vars(), get_post_types(), get_search_sql(), is_multisite(), null, parse_order(), parse_orderby(), sanitize_key(), wp_is_large_network(), and wp_parse_id_list().
Referenced by __construct().
query ()
Execute the query, with the current variables.
Since
3.1.0
wpdb $wpdb WordPress database abstraction object.
Filter SELECT FOUND_ROWS() query for the current WP_User_Query instance.
Since
3.2.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $sql The SELECT FOUND_ROWS() query for the current WP_User_Query.
Definition at line 520 of file class-wp-user-query.php.
References $query_vars, $user, $wpdb, apply_filters(), and elseif.
Referenced by __construct().
set ($query_var, $value)
Set query variable.
Since
3.5.0 public
Parameters
string $query_var Query variable key.
mixed $value Query variable value.
Definition at line 588 of file class-wp-user-query.php.
References $value.
Field Documentation
$compat_fields = array('results', 'total_users') private
Definition at line 64 of file class-wp-user-query.php.
$meta_query = false
Definition at line 53 of file class-wp-user-query.php.
$query_fields
Definition at line 67 of file class-wp-user-query.php.
Referenced by prepare_query().
$query_from
Definition at line 68 of file class-wp-user-query.php.
$query_limit
Definition at line 71 of file class-wp-user-query.php.
$query_orderby
Definition at line 70 of file class-wp-user-query.php.
$query_vars = array()
Definition at line 26 of file class-wp-user-query.php.
Referenced by prepare_query(), and query().
$query_where
Definition at line 69 of file class-wp-user-query.php.
$request
Definition at line 62 of file class-wp-user-query.php.
$results private
Definition at line 35 of file class-wp-user-query.php.
Referenced by get_results().
$total_users = 0 private
Definition at line 44 of file class-wp-user-query.php.
Referenced by get_total().
The documentation for this class was generated from the following file:
class-wp-user-query.php