GravityView: TracTickets Class Reference
TracTickets Class Reference
Static Public Member Functions
static forcingKnownBugs ()
static isTracTicketClosed ($trac_url, $ticket_id)
Checks if track ticket #$ticket_id is resolved.
static usingLocalCache ()
Static Protected Attributes
static $trac_ticket_cache = array()
Detailed Description
Definition at line 3 of file trac.php.
Member Function Documentation
static forcingKnownBugs () static
Definition at line 53 of file trac.php.
static isTracTicketClosed ($trac_url, $ticket_id) static
Checks if track ticket #$ticket_id is resolved.
Returns
bool|null true if the ticket is resolved, false if not resolved, null on error
Definition at line 16 of file trac.php.
References $file, DIR_TESTDATA, and str_replace.
Referenced by WP_UnitTestCase\knownPluginBug(), WP_UnitTestCase\knownUTBug(), and WP_UnitTestCase\knownWPBug().
static usingLocalCache () static
Definition at line 47 of file trac.php.
Field Documentation
$trac_ticket_cache = array() static protected
Definition at line 9 of file trac.php.
The documentation for this class was generated from the following file:
trac.php