GravityView: GravityView_Ajax_Test Class Reference
GravityView_Ajax_Test Class Reference
Public Member Functions
create_test_nonce ()
Set a valid "gravityview_ajaxviews" $_POST['nonce'] value.
get_available_fields_html_DEFAULT ($form, $context)
get_available_fields_html_EDIT_CONTEXT ($form, $context)
get_available_fields_html_SINGLE_CONTEXT ($form, $context)
setUp ()
test_get_available_fields_html ()
GravityView_Ajax::pre_get_form_fields() gvajax
test_import_form ()
GravityView_Ajax::import_form() gvajax
test_pre_get_form_fields ()
GravityView_Ajax::pre_get_form_fields() gvajax
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Data Fields
$AJAX
$GravityView_Preset_Business_Data
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
Definition at line 5 of file GravityView_AJAX_Test.php.
Member Function Documentation
create_test_nonce ()
Set a valid "gravityview_ajaxviews" $_POST['nonce'] value.
See also
GravityView_Ajax::check_ajax_nonce()
Definition at line 32 of file GravityView_AJAX_Test.php.
Referenced by setUp().
get_available_fields_html_DEFAULT ($form, $context)
Parameters
array $form
string $context
Definition at line 69 of file GravityView_AJAX_Test.php.
References GravityView_Ajax\pre_get_form_fields().
get_available_fields_html_EDIT_CONTEXT ($form, $context)
Parameters
array $form
string $context
Definition at line 91 of file GravityView_AJAX_Test.php.
get_available_fields_html_SINGLE_CONTEXT ($form, $context)
Parameters
array $form
string $context
Definition at line 81 of file GravityView_AJAX_Test.php.
setUp ()
Definition at line 17 of file GravityView_AJAX_Test.php.
References create_test_nonce(), GravityView_Ajax, and GravityView_Preset_Business_Data.
test_get_available_fields_html ()
GravityView_Ajax::pre_get_form_fields() gvajax
Definition at line 40 of file GravityView_AJAX_Test.php.
test_import_form ()
GravityView_Ajax::import_form() gvajax
"GRAVITYVIEW_DIR" "../../"
Definition at line 117 of file GravityView_AJAX_Test.php.
References $forms, and GravityView_Preset_Business_Listings.
test_pre_get_form_fields ()
GravityView_Ajax::pre_get_form_fields() gvajax
Definition at line 101 of file GravityView_AJAX_Test.php.
References GravityView_Ajax\pre_get_form_fields().
Field Documentation
$AJAX
Definition at line 10 of file GravityView_AJAX_Test.php.
$GravityView_Preset_Business_Data
Definition at line 15 of file GravityView_AJAX_Test.php.
The documentation for this class was generated from the following file:
GravityView_AJAX_Test.php