GravityView: gventry Class Reference
gventry Class Reference
If this file is called directly, abort.
Public Member Functions
callback ($atts, $content='', $tag='')
Process and output the [gventry] shortcode.
Public Member Functions inherited from Shortcode
callback ($atts, $content='', $tag='')
The WordPress Shortcode API callback for this shortcode.
Data Fields
$name = 'gventry'
Data Fields inherited from Shortcode
$atts
$content
$name
Additional Inherited Members
Static Public Member Functions inherited from Shortcode
static add ($name=null)
Register this shortcode class with the WordPress Shortcode API.
static parse ($content)
Parse a string of content and figure out which ones there are.
static remove ()
Unregister this shortcode.
Detailed Description
If this file is called directly, abort.
The [gventry] shortcode.
Definition at line 12 of file class-gv-shortcode-gventry.php.
Member Function Documentation
callback()
callback ($atts, $content = '', $tag = '')
Process and output the [gventry] shortcode.
Parameters
array $passed_atts The attributes passed.
string $content The content inside the shortcode.
string $tag The shortcode tag.
Returns
string|null The output.
Runs Filter:
gravityview/shortcodes/gventry/atts Filter the [gventry] shortcode attributes.
Parameters
array $atts The initial attributes.
Since
2.0
Since we're using shorthand initialization we have to reverse the order parameters here.
Reverse existing sorts.
Otherwise, sort by date_created.
If a sort already exists, reverse it.
Otherwise, sort by date_created
This View has no data source. There's nothing to show really. ...apart from a nice message if the user can do anything about it.
Private, pending, draft, etc.
Unapproved entries.
Based on code in our unit-tests. Mocks old context, etc.
Runs Filter:
gravityview/shortcodes/gventry/edit/success Modify the edit entry success message in [gventry].
Since
develop
Parameters
string $message The message.
\GV\View $view The View.
\GV\Entry $entry The entry.
array $atts The attributes.
string $back_link URL to return to the original entry.
Since
2.14.6
Parameters
string | null $redirect_url URL to return to after the update.
Since
2.14.6
Remove the back link.
Runs Filter:
gravityview/shortcodes/gventry/output Filter the [gventry] output.
Parameters
string $output The output.
\GV\View | null $view The View detected or null.
\GV\Entry | null $entry The Entry or null.
Since
2.0
Definition at line 27 of file class-gv-shortcode-gventry.php.
References $args, Shortcode\$atts, $back_link, $entries, $entry, GV\$form, $form_id, $output, $template, Entry_Sort\ASC, GF_Entry\by_id(), Internal_Field\by_id(), View\by_id(), Entry_Sort\DESC, endswitch, Utils\get(), GravityView_Edit_Entry\get_nonce_key(), GVCommon\get_template_settings(), GravityView_Edit_Entry\getInstance(), GravityView_View_Data\getInstance(), GravityView_View\getInstance(), gravityview(), gv_map_deep(), GVCommon\has_cap(), GravityView_Entry_Approval_Status\is_approved(), GravityView_Entry_Approval\meta_key, Entry_Sort\NUMERIC, and Entry_Sort\RAND.
Field Documentation
$name
$name = 'gventry'
Definition at line 16 of file class-gv-shortcode-gventry.php.
The documentation for this class was generated from the following file:
class-gv-shortcode-gventry.php