GravityView: IXR_Value Class Reference
IXR_Value Class Reference
Public Member Functions
__construct ($data, $type=false)
PHP5 constructor.
calculateType ()
getXml ()
isStruct ($array)
Checks whether or not the supplied array is a struct or not.
IXR_Value ($data, $type=false)
PHP4 constructor.
Data Fields
$data
$type
Detailed Description
Definition at line 48 of file class-IXR.php.
Constructor & Destructor Documentation
__construct ($data, $type = false)
PHP5 constructor.
Definition at line 55 of file class-IXR.php.
References $data, $i, $type, $value, calculateType(), and IXR_Value().
Member Function Documentation
calculateType ()
Definition at line 82 of file class-IXR.php.
References isStruct().
Referenced by __construct().
getXml ()
Definition at line 119 of file class-IXR.php.
References $name, and $value.
isStruct ($array)
Checks whether or not the supplied array is a struct or not.
Parameters
array $array
Returns
bool
Definition at line 167 of file class-IXR.php.
References $value.
Referenced by calculateType().
IXR_Value ($data, $type = false)
PHP4 constructor.
Definition at line 78 of file class-IXR.php.
Referenced by __construct().
Field Documentation
$data
Definition at line 49 of file class-IXR.php.
Referenced by __construct().
$type
Definition at line 50 of file class-IXR.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
class-IXR.php