GravityView: GF_Field Class Reference
GF_Field Class Reference
Class GF_Field.
Public Member Functions
__construct ($data=array())
& __get ($key)
__isset ($key)
__set ($key, $value)
__unset ($key)
add_button ($field_groups)
Adds the field button to the specified group.
allow_html ()
Override this if the field should allow html tags to be saved with the entry value.
get_admin_buttons ()
Returns the field admin buttons for display in the form editor.
get_conditional_logic_event ($event)
Maybe return the input attribute which will trigger evaluation of conditional logic rules which depend on this field.
get_description ($description, $css_class)
Returns the markup for the field description.
get_entry_inputs ()
Override and return null if a multi-input field value is to be stored under the field ID instead of the individual input IDs.
get_field_content ($value, $force_frontend_label, $form)
Returns the field markup; including field label, description, validation, and the form editor admin buttons.
get_field_input ($form, $value= '', $entry=null)
Returns the field inner markup.
get_field_label ($force_frontend_label, $value)
Retrieve the field label.
get_field_placeholder_attribute ()
If the field placeholder property has a value return the input placeholder attribute.
get_first_input_id ($form)
Returns the input ID to be assigned to the field label for attribute.
get_form_editor_button ()
Returns the field button properties for the form editor.
get_form_editor_field_settings ()
Returns the class names of the settings which should be available on the field in the form editor.
get_form_editor_field_title ()
Returns the field title.
get_form_editor_inline_script_on_page_render ()
Returns the scripts to be included for this field type in the form editor.
get_form_inline_script_on_page_render ($form)
Returns the scripts to be included with the form init scripts on the front-end.
get_input_placeholder_attribute ($input)
If the input placeholder property has a value return the input placeholder attribute.
get_input_placeholder_value ($input)
If configured retrieve the input placeholder value.
get_input_type ()
Retrieves the field input type.
get_input_value_submission ($standard_name, $custom_name= '', $field_values=array(), $get_from_post_global_var=true)
Retrieve the input value on submission.
get_tabindex ()
Maybe return the tabindex attribute.
get_value_default ()
Retrieve the field default value.
get_value_default_if_empty ($value)
Returns the field default value if the field does not already have a value.
get_value_entry_detail ($value, $currency= '', $use_text=false, $format= 'html', $media= 'screen')
Format the entry value for display on the entry detail page and for the {all_fields} merge tag.
get_value_entry_list ($value, $entry, $field_id, $columns, $form)
Format the entry value for display on the entries list page.
get_value_export ($entry, $input_id= '', $use_text=false, $is_csv=false)
Format the entry value before it is used in entry exports and by framework add-ons using GFAddOn::get_field_value().
get_value_merge_tag ($value, $input_id, $entry, $form, $modifier, $raw_value, $url_encode, $esc_html, $format, $nl2br)
Format the entry value for when the field/input merge tag is processed.
get_value_save_entry ($value, $form, $input_name, $lead_id, $lead)
Format the value before it is saved to the Entry Object.
get_value_submission ($field_values, $get_from_post_global_var=true)
Retrieve the field value on submission.
has_calculation ()
Is this a calculated product field or a number field with a calculation enabled and formula configured.
is_conditional_logic_supported ()
Override to indicate if this field type can be used when configuring conditional logic rules.
is_description_above ($form)
Determines if the field description should be positioned above or below the input.
is_entry_detail ()
Determine if the current location is the entry detail page.
is_entry_detail_edit ()
Determine if the current location is the edit entry page.
is_form_editor ()
Determine if the current location is the form editor.
is_value_submission_empty ($form_id)
Used to determine the required validation result.
offsetExists ($offset)
Handles array notation.
offsetGet ($offset)
offsetSet ($offset, $data)
offsetUnset ($offset)
register_form_init_scripts ($form)
Registers the script returned by get_form_inline_script_on_page_render() for display on the front-end.
sanitize_entry_value ($value, $form_id)
Sanitize the entry value before it is saved.
sanitize_settings ()
Forces settings into expected values while saving the form object.
sanitize_settings_choices ($choices=null)
Sanitize the field choices property.
sanitize_settings_conditional_logic ($logic=null)
Sanitize the field conditional logic object.
strip_script_tag ($string)
Strip unsafe tags from the field value.
validate ($value, $form)
Override this method to perform custom validation logic.
Data Fields
const SUPPRESS_DEPRECATION_NOTICE = true
Private Member Functions
maybe_fire_array_access_deprecation_notice ($offset)
Private Attributes
$_is_entry_detail = null
Static Private Attributes
static $deprecation_notice_fired = false
Detailed Description
Class GF_Field.
Note to third party developers: GF_Field is still in a state of flux at the moment so we don’t recommend that you start using it just yet as a base for new fields in production environments. Once it’s stable we’ll provide documentation and instructions on how to use it for your own projects.
Definition at line 15 of file class-gf-field.php.
Constructor & Destructor Documentation
__construct ($data = array())
Definition at line 24 of file class-gf-field.php.
References $value.
Member Function Documentation
& __get ($key)
Definition at line 91 of file class-gf-field.php.
__isset ($key)
Definition at line 83 of file class-gf-field.php.
__set ($key, $value)
Definition at line 87 of file class-gf-field.php.
References $value.
__unset ($key)
Definition at line 99 of file class-gf-field.php.
add_button ($field_groups)
Adds the field button to the specified group.
Parameters
array $field_groups
Returns
array
Definition at line 624 of file class-gf-field.php.
References get_form_editor_button().
allow_html ()
Override this if the field should allow html tags to be saved with the entry value.
Default is false.
Returns
bool
Definition at line 825 of file class-gf-field.php.
Referenced by sanitize_entry_value().
get_admin_buttons ()
Returns the field admin buttons for display in the form editor.
Returns
string
This filter allows for modification of the form field duplicate link. This will change the link for all fields
Parameters
string $duplicate_field_link The Duplicate Field Link (in HTML)
This filter allows for modification of a form field delete link. This will change the link for all fields
Parameters
string $delete_field_link The Delete Field Link (in HTML)
Definition at line 659 of file class-gf-field.php.
References apply_filters(), esc_attr__(), esc_html, esc_html__(), is_entry_detail(), and is_form_editor().
Referenced by GF_Field_Page\get_field_content(), GF_Field_Section\get_field_content(), GF_Field_HTML\get_field_content(), GF_Field_Hidden\get_field_content(), and get_field_content().
get_conditional_logic_event ($event)
Maybe return the input attribute which will trigger evaluation of conditional logic rules which depend on this field.
Parameters
string $event The event attribute which should be returned. Possible values: keyup, click, or change.
Returns
string
Definition at line 469 of file class-gf-field.php.
References is_entry_detail(), and is_form_editor().
Referenced by GF_Field_Checkbox\get_checkbox_choices(), GF_Field_Post_Tags\get_field_input(), GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_Select\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_Post_Title\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_MultiSelect\get_field_input(), GF_Field_Number\get_field_input(), and GF_Field_Radio\get_radio_choices().
get_description ($description, $css_class)
Returns the markup for the field description.
Parameters
string $description The field description.
string $css_class The css class to be assigned to the description container.
Returns
string
Definition at line 750 of file class-gf-field.php.
References $description, is_entry_detail(), and is_form_editor().
Referenced by GF_Field_Section\get_field_content(), and get_field_content().
get_entry_inputs ()
Override and return null if a multi-input field value is to be stored under the field ID instead of the individual input IDs.
Returns
array|null
Definition at line 358 of file class-gf-field.php.
Referenced by get_value_submission().
get_field_content ($value, $force_frontend_label, $form)
Returns the field markup; including field label, description, validation, and the form editor admin buttons.
The {FIELD} placeholder will be replaced in GFFormDisplay::get_field_content with the markup returned by GF_Field::get_field_input().
Parameters
string | array $value The field value. From default/dynamic population, $_POST, or a resumed incomplete submission.
bool $force_frontend_label Should the frontend label be displayed in the admin even if an admin label is configured.
array $form The Form Object currently being processed.
Returns
string
Definition at line 193 of file class-gf-field.php.
References $description, $form, $value, esc_html, get_admin_buttons(), get_description(), get_field_label(), get_first_input_id(), is_description_above(), is_entry_detail(), and is_form_editor().
get_field_input ($form, $value = '', $entry = null)
Returns the field inner markup.
Parameters
array $form The Form Object currently being processed.
string | array $value The field value. From default/dynamic population, $_POST, or a resumed incomplete submission.
null | array $entry Null or the Entry Object currently being edited.
Returns
string
Definition at line 178 of file class-gf-field.php.
get_field_label ($force_frontend_label, $value)
Retrieve the field label.
Parameters
bool $force_frontend_label Should the frontend label be displayed in the admin even if an admin label is configured.
string $value The field value. From default/dynamic population, $_POST, or a resumed incomplete submission.
Returns
string
Definition at line 705 of file class-gf-field.php.
References $value, and label.
Referenced by GF_Field_Section\get_field_content(), GF_Field_HTML\get_field_content(), GF_Field_Hidden\get_field_content(), and get_field_content().
get_field_placeholder_attribute ()
If the field placeholder property has a value return the input placeholder attribute.
Returns
string
Definition at line 503 of file class-gf-field.php.
References esc_attr(), and placeholder.
Referenced by GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Post_Tags\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_Post_Title\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Donation\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_Date\get_field_input(), and GF_Field_Number\get_field_input().
get_first_input_id ($form)
Returns the input ID to be assigned to the field label for attribute.
Parameters
array $form The Form Object currently being processed.
Returns
string
Definition at line 721 of file class-gf-field.php.
References $field_id, $form, $form_id, $id, is_entry_detail(), is_form_editor(), and str_replace.
Referenced by get_field_content().
get_form_editor_button ()
Returns the field button properties for the form editor.
The array contains two elements: 'group' => 'standard_fields' // or 'advanced_fields', 'post_fields', 'pricing_fields' 'text' => 'Button text'
Built-in fields don't need to implement this because the buttons are added in sequence in GFFormDetail
Returns
array
Definition at line 124 of file class-gf-field.php.
References get_form_editor_field_title().
Referenced by add_button().
get_form_editor_field_settings ()
Returns the class names of the settings which should be available on the field in the form editor.
Returns
array
Definition at line 136 of file class-gf-field.php.
get_form_editor_field_title ()
Returns the field title.
Returns
string
Definition at line 111 of file class-gf-field.php.
Referenced by get_form_editor_button().
get_form_editor_inline_script_on_page_render ()
Returns the scripts to be included for this field type in the form editor.
Returns
string
Definition at line 154 of file class-gf-field.php.
get_form_inline_script_on_page_render ($form)
Returns the scripts to be included with the form init scripts on the front-end.
Parameters
array $form The Form Object currently being processed.
Returns
string
Definition at line 165 of file class-gf-field.php.
Referenced by register_form_init_scripts().
get_input_placeholder_attribute ($input)
If the input placeholder property has a value return the input placeholder attribute.
Parameters
array $input The input currently being processed.
Returns
string
Definition at line 517 of file class-gf-field.php.
References esc_attr(), and get_input_placeholder_value().
Referenced by GF_Field_Email\get_field_input(), GF_Field_Time\get_field_input(), and GF_Field_CreditCard\get_field_input().
get_input_placeholder_value ($input)
If configured retrieve the input placeholder value.
Parameters
array $input The input currently being processed.
Returns
string
Definition at line 531 of file class-gf-field.php.
Referenced by GF_Field_CreditCard\get_field_input(), and get_input_placeholder_attribute().
get_input_type ()
Retrieves the field input type.
Returns
string
Definition at line 612 of file class-gf-field.php.
Referenced by has_calculation().
get_input_value_submission ($standard_name, $custom_name = '', $field_values = array(), $get_from_post_global_var = true)
Retrieve the input value on submission.
Parameters
string $standard_name The input name used when accessing the $_POST.
string $custom_name The dynamic population parameter name.
array $field_values The dynamic population parameter names with their corresponding values to be populated.
bool | true $get_from_post_global_var Whether to get the value from the $_POST array as opposed to $field_values.
Returns
array|string
Definition at line 336 of file class-gf-field.php.
References $form_id, $value, elseif, GFFormsModel\get_parameter_value(), and GFFormsModel\maybe_trim_input().
Referenced by GF_Field_Number\get_value_submission(), GF_Field_CreditCard\get_value_submission(), GF_Field_Radio\get_value_submission(), GF_Field_Email\get_value_submission(), GF_Field_List\get_value_submission(), and get_value_submission().
get_tabindex ()
Maybe return the tabindex attribute.
Returns
string
Definition at line 494 of file class-gf-field.php.
Referenced by GF_Field_Checkbox\get_checkbox_choices(), GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Post_Tags\get_field_input(), GF_Field_Calculation\get_field_input(), GF_Field_List\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_Select\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_SingleProduct\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Post_Title\get_field_input(), GF_Field_Donation\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Password\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_MultiSelect\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GF_Field_Number\get_field_input(), GF_Field_List\get_list_input(), GF_Field_Radio\get_radio_choices(), and GF_Field_Address\get_state_field().
get_value_default ()
Retrieve the field default value.
Returns
array|string
Definition at line 779 of file class-gf-field.php.
References $value, and is_form_editor().
Referenced by get_value_default_if_empty().
get_value_default_if_empty ($value)
Returns the field default value if the field does not already have a value.
Parameters
array | string $value The field value.
Returns
array|string
Definition at line 765 of file class-gf-field.php.
References $value, and get_value_default().
get_value_entry_detail ($value, $currency = '', $use_text = false, $format = 'html', $media = 'screen')
Format the entry value for display on the entry detail page and for the {all_fields} merge tag.
Parameters
string | array $value The field value.
string $currency The entry currency code.
bool | false $use_text When processing choice based fields should the choice text be returned instead of the value.
string $format The format requested for the location the merge is being used. Possible values: html, text or url.
string $media The location where the value will be displayed. Possible values: screen or email.
Returns
string
Definition at line 431 of file class-gf-field.php.
References $format, $value, and esc_html.
get_value_entry_list ($value, $entry, $field_id, $columns, $form)
Format the entry value for display on the entries list page.
Parameters
string | array $value The field value.
array $entry The Entry Object currently being processed.
string $field_id The field or input ID currently being processed.
array $columns The properties for the columns being displayed on the entry list page.
array $form The Form Object currently being processed.
Returns
string
Definition at line 416 of file class-gf-field.php.
References $value, and esc_html.
get_value_export ($entry, $input_id = '', $use_text = false, $is_csv = false)
Format the entry value before it is used in entry exports and by framework add-ons using GFAddOn::get_field_value().
Parameters
array $entry The entry currently being processed.
string $input_id The field or input ID.
bool | false $use_text When processing choice based fields should the choice text be returned instead of the value.
bool | false $is_csv Is the value going to be used in the .csv entries export?
Returns
string
Definition at line 451 of file class-gf-field.php.
References $id.
get_value_merge_tag ($value, $input_id, $entry, $form, $modifier, $raw_value, $url_encode, $esc_html, $format, $nl2br)
Format the entry value for when the field/input merge tag is processed.
Not called for the {all_fields} merge tag.
Parameters
string | array $value The field value. Depending on the location the merge tag is being used the following functions may have already been applied to the value: esc_html, nl2br, and urlencode.
string $input_id The field or input ID from the merge tag currently being processed.
array $entry The Entry Object currently being processed.
array $form The Form Object currently being processed.
string $modifier The merge tag modifier. e.g. value
string | array $raw_value The raw field value from before any formatting was applied to $value.
bool $url_encode Indicates if the urlencode function may have been applied to the $value.
bool $esc_html Indicates if the esc_html function may have been applied to the $value.
string $format The format requested for the location the merge is being used. Possible values: html, text or url.
bool $nl2br Indicates if the nl2br function may have been applied to the $value.
Returns
string
Definition at line 401 of file class-gf-field.php.
References $value.
get_value_save_entry ($value, $form, $input_name, $lead_id, $lead)
Format the value before it is saved to the Entry Object.
Parameters
array | string $value The value to be saved.
array $form The Form Object currently being processed.
string $input_name The input name used when accessing the $_POST.
int $lead_id The ID of the Entry currently being processed.
array $lead The Entry Object currently being processed.
Returns
array|string
Definition at line 373 of file class-gf-field.php.
References $form, $value, and sanitize_entry_value().
get_value_submission ($field_values, $get_from_post_global_var = true)
Retrieve the field value on submission.
Parameters
array $field_values The dynamic population parameter names with their corresponding values to be populated.
bool | true $get_from_post_global_var Whether to get the value from the $_POST array as opposed to $field_values.
Returns
array|string
Definition at line 310 of file class-gf-field.php.
References $value, GFForms\get(), get_entry_inputs(), get_input_value_submission(), and str_replace.
has_calculation ()
Is this a calculated product field or a number field with a calculation enabled and formula configured.
Returns
bool
Definition at line 573 of file class-gf-field.php.
References get_input_type().
Referenced by GF_Field_Number\get_field_input(), GF_Field_Number\get_value_save_entry(), and GF_Field_Number\validate().
is_conditional_logic_supported ()
Override to indicate if this field type can be used when configuring conditional logic rules.
Returns
bool
Definition at line 145 of file class-gf-field.php.
is_description_above ($form)
Determines if the field description should be positioned above or below the input.
Parameters
array $form The Form Object currently being processed.
Returns
bool
Definition at line 591 of file class-gf-field.php.
References $form.
Referenced by get_field_content().
is_entry_detail ()
Determine if the current location is the entry detail page.
Returns
bool
Definition at line 555 of file class-gf-field.php.
Referenced by get_admin_buttons(), GF_Field_Checkbox\get_checkbox_choices(), get_conditional_logic_event(), get_description(), GF_Field_HTML\get_field_content(), GF_Field_Hidden\get_field_content(), get_field_content(), GF_Field_SingleShipping\get_field_input(), GF_Field_HTML\get_field_input(), GF_Field_Total\get_field_input(), GF_Field_Hidden\get_field_input(), GF_Field_HiddenProduct\get_field_input(), GF_Field_Checkbox\get_field_input(), GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Post_Tags\get_field_input(), GF_Field_Calculation\get_field_input(), GF_Field_List\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Select\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_SingleProduct\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Post_Title\get_field_input(), GF_Field_Name\get_field_input(), GF_Field_Donation\get_field_input(), GF_Field_Radio\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Password\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_MultiSelect\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GF_Field_Number\get_field_input(), get_first_input_id(), GF_Field_Radio\get_radio_choices(), GF_Field_Address\get_state_field(), and GF_Field_Email\get_value_submission().
is_entry_detail_edit ()
Determine if the current location is the edit entry page.
Returns
bool
Definition at line 564 of file class-gf-field.php.
is_form_editor ()
Determine if the current location is the form editor.
Returns
bool
Definition at line 546 of file class-gf-field.php.
Referenced by get_admin_buttons(), GF_Field_Checkbox\get_checkbox_choices(), get_conditional_logic_event(), get_description(), GF_Field_HTML\get_field_content(), GF_Field_Hidden\get_field_content(), get_field_content(), GF_Field_SingleShipping\get_field_input(), GF_Field_HTML\get_field_input(), GF_Field_Total\get_field_input(), GF_Field_Hidden\get_field_input(), GF_Field_HiddenProduct\get_field_input(), GF_Field_Checkbox\get_field_input(), GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Post_Tags\get_field_input(), GF_Field_Calculation\get_field_input(), GF_Field_List\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Select\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_SingleProduct\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Post_Title\get_field_input(), GF_Field_Name\get_field_input(), GF_Field_Donation\get_field_input(), GF_Field_Radio\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Password\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_MultiSelect\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GF_Field_Number\get_field_input(), GF_Field_List\get_first_input_id(), get_first_input_id(), GF_Field_List\get_list_input(), GF_Field_Radio\get_radio_choices(), GF_Field_Address\get_state_field(), GF_Field_Checkbox\get_value_default(), GF_Field_Radio\get_value_default(), and get_value_default().
is_value_submission_empty ($form_id)
Used to determine the required validation result.
Parameters
int $form_id The ID of the form currently being processed.
Returns
bool
Definition at line 232 of file class-gf-field.php.
References $label, $value, elseif, and str_replace.
maybe_fire_array_access_deprecation_notice ($offset) private
Definition at line 36 of file class-gf-field.php.
References _deprecated_function().
Referenced by offsetExists(), offsetGet(), offsetSet(), and offsetUnset().
offsetExists ($offset)
Handles array notation.
Parameters
mixed $offset
Returns
bool
Definition at line 54 of file class-gf-field.php.
References maybe_fire_array_access_deprecation_notice().
offsetGet ($offset)
Definition at line 60 of file class-gf-field.php.
References maybe_fire_array_access_deprecation_notice().
offsetSet ($offset, $data)
Definition at line 69 of file class-gf-field.php.
References maybe_fire_array_access_deprecation_notice(), and null.
offsetUnset ($offset)
Definition at line 78 of file class-gf-field.php.
References maybe_fire_array_access_deprecation_notice().
register_form_init_scripts ($form)
Registers the script returned by get_form_inline_script_on_page_render() for display on the front-end.
Parameters
array $form The Form Object currently being processed.
Definition at line 798 of file class-gf-field.php.
References $form, GFFormDisplay\add_init_script(), get_form_inline_script_on_page_render(), and GFFormDisplay\ON_PAGE_RENDER.
sanitize_entry_value ($value, $form_id)
Sanitize the entry value before it is saved.
Parameters
string $value The field value to be processed.
int $form_id The ID of the form currently being processed.
Returns
string
Definition at line 838 of file class-gf-field.php.
References $form_id, $value, allow_html(), and wp_kses_post().
Referenced by GF_Field_MultiSelect\get_value_save_entry(), GF_Field_Checkbox\get_value_save_entry(), GF_Field_Radio\get_value_save_entry(), and get_value_save_entry().
sanitize_settings ()
Forces settings into expected values while saving the form object.
No escaping should be done at this stage to prevent double escaping on output.
Currently called only for forms created after version 1.9.6.10.
Definition at line 868 of file class-gf-field.php.
References absint(), label, placeholder, sanitize_settings_choices(), sanitize_settings_conditional_logic(), sanitize_text_field(), size, wp_kses(), wp_kses_allowed_html(), and wp_strip_all_tags().
sanitize_settings_choices ($choices = null)
Sanitize the field choices property.
Parameters
array | null $choices The field choices property.
Returns
array|null
Definition at line 966 of file class-gf-field.php.
References wp_kses(), and wp_kses_allowed_html().
Referenced by GF_Field_Name\sanitize_settings(), and sanitize_settings().
sanitize_settings_conditional_logic ($logic = null)
Sanitize the field conditional logic object.
Parameters
array | null $logic The field conditional logic object.
Returns
array|null
Definition at line 1006 of file class-gf-field.php.
References GFFormsModel\sanitize_conditional_logic().
Referenced by GF_Field_Page\sanitize_settings(), and sanitize_settings().
strip_script_tag ($string)
Strip unsafe tags from the field value.
Parameters
string $string The field value to be processed.
Returns
string
Definition at line 812 of file class-gf-field.php.
validate ($value, $form)
Override this method to perform custom validation logic.
Return the result (bool) by setting $this->failed_validation. Return the validation message (string) by setting $this->validation_message.
Parameters
string | array $value The field value from get_value_submission().
array $form The Form Object currently being processed.
Definition at line 298 of file class-gf-field.php.
Field Documentation
$_is_entry_detail = null private
Definition at line 22 of file class-gf-field.php.
$deprecation_notice_fired = false static private
Definition at line 20 of file class-gf-field.php.
const SUPPRESS_DEPRECATION_NOTICE = true
Definition at line 18 of file class-gf-field.php.
The documentation for this class was generated from the following file:
class-gf-field.php