GravityView: WP_Ajax_UnitTestCase Class Reference
WP_Ajax_UnitTestCase Class Reference
Public Member Functions
dieHandler ($message)
Handler for wp_die() Save the output for analysis, stop execution by throwing an exception.
getDieHandler ()
Return our callback handler.
logout ()
Clear login cookies, unset the current user.
setUp ()
Set up the test fixture.
tearDown ()
Tear down the test fixture.
Public Member Functions inherited from WP_UnitTestCase
__get ($name)
__isset ($name)
_create_temporary_tables ($query)
_drop_temporary_tables ($query)
_make_attachment ($upload, $parent_post_id=0)
assertDiscardWhitespace ($expected, $actual)
assertEqualFields ($object, $fields)
assertEqualSets ($expected, $actual)
assertEqualSetsWithIndex ($expected, $actual)
assertNotWPError ($actual, $message= '')
assertQueryTrue ()
Check each of the WP_Query is_* functions/properties against expected boolean value.
assertWPError ($actual, $message= '')
clean_up_global_scope ()
delete_folders ($path)
deprecated_function_run ($function)
doing_it_wrong_run ($function)
expectDeprecated ()
expectedDeprecated ()
files_in_dir ($dir)
flush_cache ()
get_wp_die_handler ($handler)
go_to ($url)
knownPluginBug ($ticket_id)
Skips the current test if there is an open plugin ticket with id $ticket_id.
knownUTBug ($ticket_id)
Skips the current test if there is an open unit tests ticket with id $ticket_id.
knownWPBug ($ticket_id)
Skips the current test if there is an open WordPress ticket with id $ticket_id.
prepareTemplate (Text_Template $template)
Define constants after including files.
remove_added_uploads ()
rmdir ($path)
scan_user_uploads ()
scandir ($dir)
set_permalink_structure ($structure= '')
Utility method that resets permalinks and flushes rewrites.
setExpectedDeprecated ($deprecated)
Declare an expected _deprecated_function() or _deprecated_argument() call from within a test.
setExpectedIncorrectUsage ($doing_it_wrong)
Declare an expected _doing_it_wrong() call from within a test.
setUp ()
start_transaction ()
tearDown ()
temp_filename ()
Returns the name of a temporary file.
unlink ($file)
wp_die_handler ($message)
Static Public Member Functions
static setUpBeforeClass ()
Static Public Member Functions inherited from WP_UnitTestCase
static commit_transaction ()
Commit the queries in a transaction.
static delete_user ($user_id)
Multisite-agnostic way to delete a user from the database.
static forceTicket ($ticket)
static get_called_class ()
static setUpBeforeClass ()
static tearDownAfterClass ()
Protected Member Functions
_handleAjax ($action)
Mimic the ajax handling of admin-ajax.php Capture the output via output buffering, and if there is any, store it in $this->_last_message.
_setRole ($role)
Switch between user roles E.g.
Protected Member Functions inherited from WP_UnitTestCase
_backup_hooks ()
Saves the action and filter-related globals so they can be restored later.
_microtime_to_float ($microtime)
Helper to Convert a microtime string into a float.
_restore_hooks ()
Restores the hook-related globals to their state at setUp() so that future tests aren't affected by hooks set during this last test.
assertPostConditions ()
Detect post-test failure conditions.
checkRequirements ()
reset_post_statuses ()
Unregister non-built-in post statuses.
reset_post_types ()
Unregister existing post types and register defaults.
reset_taxonomies ()
Unregister existing taxonomies and register defaults.
Protected Attributes
$_error_level = 0
$_last_response = ''
Protected Attributes inherited from WP_UnitTestCase
$caught_deprecated = array()
$caught_doing_it_wrong = array()
$expected_deprecated = array()
$expected_doing_it_wrong = array()
Static Protected Attributes
static $_core_actions_get
static $_core_actions_post
Static Protected Attributes inherited from WP_UnitTestCase
static $forced_tickets = array()
static $hooks_saved = array()
static $ignore_files
Additional Inherited Members
Static Protected Member Functions inherited from WP_UnitTestCase
static factory ()
Detailed Description
Definition at line 17 of file testcase-ajax.php.
Member Function Documentation
_handleAjax ($action) protected
Mimic the ajax handling of admin-ajax.php Capture the output via output buffering, and if there is any, store it in $this->_last_message.
Parameters
string $action
Definition at line 181 of file testcase-ajax.php.
References $action, do_action(), and null.
_setRole ($role) protected
Switch between user roles E.g.
administrator, editor, author, contributor, subscriber
Parameters
string $role
Definition at line 168 of file testcase-ajax.php.
References $post, and $user_id.
dieHandler ($message)
Handler for wp_die() Save the output for analysis, stop execution by throwing an exception.
Error conditions (no output, just die) will throw WPAjaxDieStopException($message) You can test for this with: $this->setExpectedException('WPAjaxDieStopException', 'something contained in $message'); Normal program termination (wp_die called at then end of output) will throw WPAjaxDieContinueException($message) You can test for this with: $this->setExpectedException('WPAjaxDieContinueException', 'something contained in $message');
Parameters
string $message
Definition at line 149 of file testcase-ajax.php.
References $message.
getDieHandler ()
Return our callback handler.
Returns
callback
Definition at line 130 of file testcase-ajax.php.
logout ()
Clear login cookies, unset the current user.
Definition at line 119 of file testcase-ajax.php.
References $_COOKIE, and $GLOBALS.
setUp ()
Set up the test fixture.
Override wp_die(), pretend to be ajax, and suppres E_WARNINGs
Definition at line 82 of file testcase-ajax.php.
References add_action(), add_filter(), and set_current_screen().
static setUpBeforeClass () static
Definition at line 59 of file testcase-ajax.php.
References $action, add_action(), remove_action(), and str_replace.
tearDown ()
Tear down the test fixture.
Reset $_POST, remove the wp_die() override, restore error reporting
Definition at line 104 of file testcase-ajax.php.
References $GLOBALS, remove_action(), remove_filter(), and set_current_screen().
Field Documentation
$_core_actions_get static protected
Initial value:
= array(
        'fetch-list', 'ajax-tag-search', 'wp-compression-test', 'imgedit-preview', 'oembed-cache',
        'autocomplete-user', 'dashboard-widgets', 'logged-in',
    )
Definition at line 29 of file testcase-ajax.php.
$_core_actions_post static protected
Initial value:
= array(
        'oembed_cache', 'image-editor', 'delete-comment', 'delete-tag', 'delete-link',
        'delete-meta', 'delete-post', 'trash-post', 'untrash-post', 'delete-page', 'dim-comment',
        'add-link-category', 'add-tag', 'get-tagcloud', 'get-comments', 'replyto-comment',
        'edit-comment', 'add-menu-item', 'add-meta', 'add-user', 'closed-postboxes',
        'hidden-columns', 'update-welcome-panel', 'menu-get-metabox', 'wp-link-ajax',
        'menu-locations-save', 'menu-quick-search', 'meta-box-order', 'get-permalink',
        'sample-permalink', 'inline-save', 'inline-save-tax', 'find_posts', 'widgets-order',
        'save-widget', 'set-post-thumbnail', 'date_format', 'time_format', 'wp-fullscreen-save-post',
        'wp-remove-post-lock', 'dismiss-wp-pointer', 'heartbeat', 'nopriv_heartbeat', 'get-revision-diffs',
        'save-user-color-scheme', 'update-widget', 'query-themes', 'parse-embed', 'set-attachment-thumbnail',
        'parse-media-shortcode', 'destroy-sessions', 'install-plugin', 'update-plugin', 'press-this-save-post',
        'press-this-add-category', 'crop-image', 'generate-password',
    )
Definition at line 44 of file testcase-ajax.php.
$_error_level = 0 protected
Definition at line 38 of file testcase-ajax.php.
$_last_response = '' protected
Definition at line 23 of file testcase-ajax.php.
The documentation for this class was generated from the following file:
testcase-ajax.php