GravityView: WP_Importer Class Reference
WP_Importer Class Reference
WP_Importer base class.
Public Member Functions
__construct ()
Class Constructor.
bump_request_timeout ($val)
Bump up the request timeout for http requests.
cmpr_strlen ($a, $b)
Sort by strlen, longest string first.
count_imported_posts ($importer_name, $bid)
Return count of imported permalinks from WordPress database.
get_imported_comments ($bid)
Set array with imported comments from WordPress database.
get_imported_posts ($importer_name, $bid)
Returns array with imported permalinks from WordPress database.
get_page ($url, $username= '', $password= '', $head=false)
GET URL.
is_user_over_quota ()
Check if user has exceeded disk quota.
min_whitespace ($string)
Replace newlines, tabs, and multiple spaces with a single space.
set_blog ($blog_id)
set_user ($user_id)
stop_the_insanity ()
Reset global variables that grow out of control during imports.
Detailed Description
WP_Importer base class.
Definition at line 5 of file class-wp-importer.php.
Constructor & Destructor Documentation
__construct ()
Class Constructor.
Definition at line 10 of file class-wp-importer.php.
Member Function Documentation
bump_request_timeout ($val)
Bump up the request timeout for http requests.
Parameters
int $val
Returns
int
Definition at line 219 of file class-wp-importer.php.
cmpr_strlen ($a, $b)
Sort by strlen, longest string first.
Parameters
string $a
string $b
Returns
int
Definition at line 184 of file class-wp-importer.php.
count_imported_posts ($importer_name, $bid)
Return count of imported permalinks from WordPress database.
wpdb $wpdb WordPress database abstraction object.
Parameters
string $importer_name
string $bid
Returns
int
Definition at line 61 of file class-wp-importer.php.
References $count, and $wpdb.
get_imported_comments ($bid)
Set array with imported comments from WordPress database.
wpdb $wpdb WordPress database abstraction object.
Parameters
string $bid
Returns
array
Definition at line 89 of file class-wp-importer.php.
References $wpdb.
get_imported_posts ($importer_name, $bid)
Returns array with imported permalinks from WordPress database.
wpdb $wpdb WordPress database abstraction object.
Parameters
string $importer_name
string $bid
Returns
array
Definition at line 21 of file class-wp-importer.php.
References $wpdb.
get_page ($url, $username = '', $password = '', $head = false)
GET URL.
Parameters
string $url
string $username
string $password
bool $head
Returns
array
Definition at line 197 of file class-wp-importer.php.
References $url, add_filter(), and wp_safe_remote_request().
is_user_over_quota ()
Check if user has exceeded disk quota.
Returns
bool
Definition at line 228 of file class-wp-importer.php.
References upload_is_user_over_quota().
min_whitespace ($string)
Replace newlines, tabs, and multiple spaces with a single space.
Parameters
string $string
Returns
string
Definition at line 244 of file class-wp-importer.php.
set_blog ($blog_id)
Parameters
int $blog_id
Returns
int|void
Definition at line 130 of file class-wp-importer.php.
References $blog, $blog_id, exit, get_blog_details(), is_multisite(), and switch_to_blog().
set_user ($user_id)
Parameters
int $user_id
Returns
int|void
Definition at line 162 of file class-wp-importer.php.
References $user_id, exit, and username_exists().
stop_the_insanity ()
Reset global variables that grow out of control during imports.
wpdb $wpdb array $wp_actions
Definition at line 254 of file class-wp-importer.php.
References $wp_actions, and $wpdb.
The documentation for this class was generated from the following file:
class-wp-importer.php