GravityView: GF_Installation_Wizard_Step_Background_Updates Class Reference
GF_Installation_Wizard_Step_Background_Updates Class Reference
Public Member Functions
display ()
get_title ()
install ()
summary ($echo=true)
validate ()
Public Member Functions inherited from GF_Installation_Wizard_Step
__construct ($values=array())
& __get ($key)
__isset ($key)
__set ($key, $value)
__unset ($key)
display ()
flush_values ()
get_field_validation_result ($key)
get_name ()
get_next_button_text ()
get_posted_values ()
get_previous_button_text ()
get_title ()
get_validation_summary ()
get_values ()
install ()
is ($key)
is_complete ()
set_field_validation_result ($key, $text)
set_validation_summary ($text)
summary ($echo=true)
update ($posted_values=array())
validate ()
validation_message ($key, $echo=true)
Data Fields
$defaults
Data Fields inherited from GF_Installation_Wizard_Step
$defaults = array()
Protected Attributes
$_name = 'background_updates'
Protected Attributes inherited from GF_Installation_Wizard_Step
$_field_validation_results = array()
$_name = ''
$_validation_summary = ''
Detailed Description
Definition at line 3 of file class-gf-installation-wizard-step-background-updates.php.
Member Function Documentation
display ()
Definition at line 13 of file class-gf-installation-wizard-step-background-updates.php.
References _e, checked(), endif, esc_html_e, get_option(), input, GF_Installation_Wizard_Step\is(), label, name, and GF_Installation_Wizard_Step\validation_message().
get_title ()
Definition at line 93 of file class-gf-installation-wizard-step-background-updates.php.
References esc_html__().
install ()
Definition at line 117 of file class-gf-installation-wizard-step-background-updates.php.
References update_option().
summary ($echo = true)
Definition at line 109 of file class-gf-installation-wizard-step-background-updates.php.
References esc_html__().
validate ()
Definition at line 97 of file class-gf-installation-wizard-step-background-updates.php.
References elseif, esc_html__(), and GF_Installation_Wizard_Step\set_field_validation_result().
Field Documentation
$_name = 'background_updates' protected
Definition at line 5 of file class-gf-installation-wizard-step-background-updates.php.
$defaults
Initial value:
= array(
        'background_updates' => 'enabled',
        'accept_terms' => false,
    )
Definition at line 8 of file class-gf-installation-wizard-step-background-updates.php.
The documentation for this class was generated from the following file:
class-gf-installation-wizard-step-background-updates.php