GravityView: getid3_mp3 Class Reference
getid3_mp3 Class Reference
Public Member Functions
Analyze ()
decodeMPEGaudioHeader ($offset, &$info, $recursivesearch=true, $ScanAsCBR=false, $FastMPEGheaderScan=false)
FreeFormatFrameLength ($offset, $deepscan=false)
getOnlyMPEGaudioInfo ($avdataoffset, $BitrateHistogram=false)
getOnlyMPEGaudioInfoBruteForce ()
GuessEncoderOptions ()
RecursiveFrameScanning (&$offset, &$nextframetestoffset, $ScanAsCBR)
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Static Public Member Functions
static ClosestStandardMP3Bitrate ($bit_rate)
static LAMEmiscSourceSampleFrequencyLookup ($SourceSampleFrequencyID)
static LAMEmiscStereoModeLookup ($StereoModeID)
static LAMEpresetUsedLookup ($LAMEtag)
static LAMEsurroundInfoLookup ($SurroundInfoID)
static LAMEvbrMethodLookup ($VBRmethodID)
static MPEGaudioBitrateArray ()
static MPEGaudioChannelModeArray ()
static MPEGaudioEmphasisArray ()
static MPEGaudioFrameLength (&$bitrate, &$version, &$layer, $padding, &$samplerate)
static MPEGaudioFrequencyArray ()
static MPEGaudioHeaderBytesValid ($head4, $allowBitrate15=false)
static MPEGaudioHeaderDecode ($Header4Bytes)
static MPEGaudioHeaderValid ($rawarray, $echoerrors=false, $allowBitrate15=false)
static MPEGaudioLayerArray ()
static MPEGaudioModeExtensionArray ()
static MPEGaudioVersionArray ()
static XingVBRidOffset ($version, $channelmode)
Data Fields
$allow_bruteforce = false
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
Definition at line 25 of file module.audio.mp3.php.
Member Function Documentation
Analyze ()
Definition at line 30 of file module.audio.mp3.php.
References elseif, getid3_handler\fread(), getid3_handler\fseek(), getOnlyMPEGaudioInfo(), getOnlyMPEGaudioInfoBruteForce(), and GuessEncoderOptions().
static ClosestStandardMP3Bitrate ($bit_rate) static
Definition at line 1863 of file module.audio.mp3.php.
decodeMPEGaudioHeader ($offset, & $info, $recursivesearch = true, $ScanAsCBR = false, $FastMPEGheaderScan = false)
Definition at line 408 of file module.audio.mp3.php.
References $i, getid3_lib\BigEndian2Int(), elseif, getid3_handler\fread(), FreeFormatFrameLength(), getid3_handler\fseek(), getid3_handler\isDependencyFor(), getid3_lib\LittleEndian2Float(), RecursiveFrameScanning(), getid3_lib\RGADadjustmentLookup(), getid3_lib\RGADamplitude2dB(), getid3_lib\RGADnameLookup(), getid3_lib\RGADoriginatorLookup(), and getid3_handler\warning().
Referenced by getOnlyMPEGaudioInfo(), and RecursiveFrameScanning().
FreeFormatFrameLength ($offset, $deepscan = false)
Definition at line 1121 of file module.audio.mp3.php.
References elseif, getid3_handler\fread(), getid3_handler\fseek(), and getid3_lib\PrintHexBytes().
Referenced by decodeMPEGaudioHeader().
getOnlyMPEGaudioInfo ($avdataoffset, $BitrateHistogram = false)
Definition at line 1346 of file module.audio.mp3.php.
References getid3_lib\CastAsInt(), decodeMPEGaudioHeader(), elseif, getid3_handler\feof(), getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\ftell(), and getid3_lib\safe_inc().
Referenced by Analyze().
getOnlyMPEGaudioInfoBruteForce ()
Definition at line 1198 of file module.audio.mp3.php.
References $i, $value, getid3_lib\array_max(), getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\ftell(), and getid3_lib\safe_inc().
Referenced by Analyze().
GuessEncoderOptions ()
Definition at line 164 of file module.audio.mp3.php.
References elseif.
Referenced by Analyze().
static LAMEmiscSourceSampleFrequencyLookup ($SourceSampleFrequencyID) static
Definition at line 1939 of file module.audio.mp3.php.
static LAMEmiscStereoModeLookup ($StereoModeID) static
Definition at line 1925 of file module.audio.mp3.php.
static LAMEpresetUsedLookup ($LAMEtag) static
Definition at line 1959 of file module.audio.mp3.php.
References $i.
static LAMEsurroundInfoLookup ($SurroundInfoID) static
Definition at line 1949 of file module.audio.mp3.php.
static LAMEvbrMethodLookup ($VBRmethodID) static
Definition at line 1909 of file module.audio.mp3.php.
static MPEGaudioBitrateArray () static
Definition at line 1636 of file module.audio.mp3.php.
static MPEGaudioChannelModeArray () static
Definition at line 1667 of file module.audio.mp3.php.
static MPEGaudioEmphasisArray () static
Definition at line 1684 of file module.audio.mp3.php.
static MPEGaudioFrameLength (& $bitrate, & $version, & $layer, $padding, & $samplerate) static
Definition at line 1802 of file module.audio.mp3.php.
References elseif.
static MPEGaudioFrequencyArray () static
Definition at line 1655 of file module.audio.mp3.php.
static MPEGaudioHeaderBytesValid ($head4, $allowBitrate15 = false) static
Definition at line 1689 of file module.audio.mp3.php.
Referenced by getid3_riff\ParseRIFF().
static MPEGaudioHeaderDecode ($Header4Bytes) static
Definition at line 1765 of file module.audio.mp3.php.
References getid3_lib\BigEndian2Int().
static MPEGaudioHeaderValid ($rawarray, $echoerrors = false, $allowBitrate15 = false) static
Definition at line 1693 of file module.audio.mp3.php.
static MPEGaudioLayerArray () static
Definition at line 1631 of file module.audio.mp3.php.
static MPEGaudioModeExtensionArray () static
Definition at line 1672 of file module.audio.mp3.php.
static MPEGaudioVersionArray () static
Definition at line 1626 of file module.audio.mp3.php.
RecursiveFrameScanning (& $offset, & $nextframetestoffset, $ScanAsCBR)
Definition at line 1075 of file module.audio.mp3.php.
References $i, decodeMPEGaudioHeader(), elseif, and GETID3_MP3_VALID_CHECK_FRAMES.
Referenced by decodeMPEGaudioHeader().
static XingVBRidOffset ($version, $channelmode) static
Definition at line 1883 of file module.audio.mp3.php.
Field Documentation
$allow_bruteforce = false
Definition at line 28 of file module.audio.mp3.php.
The documentation for this class was generated from the following file:
module.audio.mp3.php