GravityView: Logging Class Reference
Logging Class Reference
Public Member Functions
__construct (Config $config)
Logger constructor.
is_enabled ()
Returns whether logging is enabled.
log ($message='', $method='', $level='debug', $data=array())
Data Fields
const DIRECTORY_PATH = 'trustedlogin-logs/'
Path to logging directory (inside the WP Uploads base dir)
Private Member Functions
check_directory ($dirpath)
Checks whether a path exists and is writable.
maybe_make_logging_directory ()
Returns the directory to use for logging if not defined by Config.
prevent_directory_browsing ($dirpath)
Prevent browsing a directory by adding an index.html file to it.
setup_klogger ($config)
Attempts to initialize KLogger logging.
Private Attributes
$klogger = null
$logging_enabled = false
$ns
Detailed Description
Definition at line 17 of file Logging.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config)
Logger constructor.
Definition at line 42 of file Logging.php.
References Config\get_setting(), Config\ns(), and Logging\setup_klogger().
Member Function Documentation
check_directory()
check_directory ($dirpath) private
Checks whether a path exists and is writable.
Parameters
string $dirpath Path to directory
Returns
bool|string If exists and writable, returns original string. Otherwise, returns false.
Definition at line 143 of file Logging.php.
References Logging\log().
Referenced by Logging\setup_klogger().
is_enabled()
is_enabled ()
Returns whether logging is enabled.
Returns
bool
Filter: Whether debug logging is enabled in TrustedLogin Client
Since
1.0.0
Parameters
bool $debug_mode Default: false
Definition at line 239 of file Logging.php.
Referenced by Logging\log().
log()
log ($message = '', $method = '', $level = 'debug', $data = array())
See also
https://github.com/php-fig/log/blob/master/Psr/Log/LogLevel.php for log levels
Parameters
string | \WP_Error $message Message or error to log. If a WP_Error is passed, $data is ignored.
string $method Method where the log was called
string $level PSR-3 log level
\WP_Error | \Exception | mixed $data Optional. Error data. Ignored if $message is WP_Error.
Definition at line 264 of file Logging.php.
References Logging\is_enabled().
Referenced by Logging\check_directory(), Logging\maybe_make_logging_directory(), Logging\prevent_directory_browsing(), and Logging\setup_klogger().
maybe_make_logging_directory()
maybe_make_logging_directory () private
Returns the directory to use for logging if not defined by Config.
Creates one if it doesn't exist.
Note: Created directories are protected by an index.html file to prevent browsing.
Returns
false|string Directory path, if exists; False if failure.
Definition at line 173 of file Logging.php.
References Logging\log(), and Logging\prevent_directory_browsing().
Referenced by Logging\setup_klogger().
prevent_directory_browsing()
prevent_directory_browsing ($dirpath) private
Prevent browsing a directory by adding an index.html file to it.
Code inspired by
See also
wp_privacy_generate_personal_data_export_file()
Parameters
string $dirpath Path to directory to protect (in this case, logging)
Returns
bool True: File exists or was created; False: file could not be created.
Definition at line 212 of file Logging.php.
References Logging\log().
Referenced by Logging\maybe_make_logging_directory().
setup_klogger()
setup_klogger ($config) private
Attempts to initialize KLogger logging.
Parameters
Config $config
Returns
false|Logger
Definition at line 58 of file Logging.php.
References Logging\$klogger, Logging\check_directory(), Logging\log(), and Logging\maybe_make_logging_directory().
Referenced by Logging\__construct().
Field Documentation
$klogger
$klogger = null private
Definition at line 37 of file Logging.php.
Referenced by Logging\setup_klogger().
$logging_enabled
bool $logging_enabled = false private
Definition at line 32 of file Logging.php.
$ns
$ns private
Definition at line 27 of file Logging.php.
DIRECTORY_PATH
const DIRECTORY_PATH = 'trustedlogin-logs/'
Path to logging directory (inside the WP Uploads base dir)
Definition at line 22 of file Logging.php.
The documentation for this class was generated from the following file:
Logging.php