GravityView: GravityView_Field_Is_Fulfilled Class Reference
GravityView_Field_Is_Fulfilled Class Reference
Public Member Functions
__construct ()
GravityView_Field_Is_Fulfilled constructor.
get_content ($output, $entry=array(), $field_settings=array(), $field=array())
Filter the value of the field.
replace_merge_tag ($matches=array(), $text= '', $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Add {is_fulfilled} merge tag.
Public Member Functions inherited from GravityView_Field
__construct ()
GravityView_Field constructor.
_filter_gform_custom_merge_tags ($custom_merge_tags=array(), $form_id, $fields=array(), $element_id= '')
Add custom merge tags to merge tag options.
_filter_gform_replace_merge_tags ($text, $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Match the merge tag in replacement text for the field.
_filter_sortable_fields ($not_sortable)
Use field settings to modify whether a field is sortable.
add_field_support ($key= '', &$field_options)
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Tap in here to modify field options.
replace_merge_tag ($matches=array(), $text= '', $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Run GravityView filters when using GFCommon::replace_variables()
Data Fields
$_custom_merge_tag = 'is_fulfilled'
$group = 'pricing'
$is_numeric = false
$is_searchable = true
$name = 'is_fulfilled'
$search_operators = array('is', 'isnot')
const FULFILLED = 1
const NOT_FULFILLED = 0
Data Fields inherited from GravityView_Field
$_gf_field_class_name
$contexts = array('single', 'multiple', 'edit', 'export')
$description
$group
standard, advanced, post, pricing, meta, gravityview
$is_numeric
boolean Is field content number-based?
$is_searchable
$is_sortable = true
boolean Can the field be sorted in search?
$label
$name
$search_operators
Private Member Functions
get_string_from_value ($value)
Get the string output based on the numeric value used by Gravity Forms.
Additional Inherited Members
Protected Member Functions inherited from GravityView_Field
custom_merge_tags ($form=array(), $fields=array())
Add custom Merge Tags to Merge Tag options, if custom Merge Tags exist.
is_choice_value_enabled ()
Check whether the enableChoiceValue flag is set for a GF field.
Protected Attributes inherited from GravityView_Field
$_custom_merge_tag = false
$_field_id = ''
$_field_options = array()
Detailed Description
Definition at line 9 of file class-gravityview-field-is-fulfilled.php.
Constructor & Destructor Documentation
__construct ()
GravityView_Field_Is_Fulfilled constructor.
Definition at line 36 of file class-gravityview-field-is-fulfilled.php.
Member Function Documentation
get_content ($output, $entry = array(), $field_settings = array(), $field = array())
Filter the value of the field.
Since
1.16
Parameters
string $output HTML value output
array $entry The GF entry array
array $field_settings Settings for the particular GV field
array $field Current field being displayed
Returns
String values for this field based on the numeric values used by Gravity Forms
Overridden by a template.
Definition at line 58 of file class-gravityview-field-is-fulfilled.php.
References $field, $output, and get_string_from_value().
get_string_from_value ($value) private
Get the string output based on the numeric value used by Gravity Forms.
Since
1.16
Parameters
int | string $value Number value for the field
Returns
string
Definition at line 75 of file class-gravityview-field-is-fulfilled.php.
References $value.
Referenced by get_content(), and replace_merge_tag().
replace_merge_tag ($matches = array(), $text = '', $form = array(), $entry = array(), $url_encode = false, $esc_html = false)
Add {is_fulfilled} merge tag.
Since
1.16
Parameters
array $matches Array of Merge Tag matches found in text by preg_match_all
string $text Text to replace
array $form Gravity Forms form array
array $entry Entry array
bool $url_encode Whether to URL-encode output
Returns
string Original text if {is_fulfilled} isn't found. Otherwise, "Not Fulfilled" or "Fulfilled"
Definition at line 104 of file class-gravityview-field-is-fulfilled.php.
References $entry, $value, and get_string_from_value().
Field Documentation
$_custom_merge_tag = 'is_fulfilled'
Definition at line 21 of file class-gravityview-field-is-fulfilled.php.
$group = 'pricing'
Definition at line 19 of file class-gravityview-field-is-fulfilled.php.
$is_numeric = false
Definition at line 15 of file class-gravityview-field-is-fulfilled.php.
$is_searchable = true
Definition at line 13 of file class-gravityview-field-is-fulfilled.php.
$name = 'is_fulfilled'
Definition at line 11 of file class-gravityview-field-is-fulfilled.php.
$search_operators = array('is', 'isnot')
Definition at line 17 of file class-gravityview-field-is-fulfilled.php.
const FULFILLED = 1
Definition at line 31 of file class-gravityview-field-is-fulfilled.php.
const NOT_FULFILLED = 0
Definition at line 26 of file class-gravityview-field-is-fulfilled.php.
The documentation for this class was generated from the following file:
class-gravityview-field-is-fulfilled.php