GravityView: WP_Http Class Reference
WP_Http Class Reference
Core class used for managing HTTP transports and making HTTP requests.
Public Member Functions
_get_first_available_transport ($args, $url=null)
Tests which transports are capable of supporting the request.
block_request ($uri)
Block requests through the proxy.
get ($url, $args=array())
Uses the GET HTTP method.
head ($url, $args=array())
Uses the HEAD HTTP method.
post ($url, $args=array())
Uses the POST HTTP method.
request ($url, $args=array())
Send an HTTP request to a URI.
Static Public Member Functions
static buildCookieHeader (&$r)
Takes the arguments for a ::request() and checks for the cookie array.
static chunkTransferDecode ($body)
Decodes chunk transfer-encoding, based off the HTTP 1.1 specification.
static handle_redirects ($url, $args, $response)
Handles HTTP Redirects and follows them if appropriate.
static is_ip_address ($maybe_ip)
Determines if a specified string represents an IP address or not.
static make_absolute_url ($maybe_relative_path, $url)
Converts a relative URL to an absolute URL relative to a given URL.
static processHeaders ($headers, $url= '')
Transform header string into an array.
static processResponse ($strResponse)
Parses the responses and splits the parts into headers and body.
Static Protected Member Functions
static parse_url ($url)
Used as a wrapper for PHP's parse_url() function that handles edgecases in < PHP 5.4.7.
Static Private Member Functions
_dispatch_request ($url, $args)
Dispatches a HTTP request to a supporting transport.
Detailed Description
Core class used for managing HTTP transports and making HTTP requests.
This class is used to consistently make outgoing HTTP requests easy for developers while still being compatible with the many PHP configurations under which WordPress runs.
Debugging includes several actions, which pass different variables for debugging the HTTP API.
Since
2.7.0
Definition at line 21 of file class-http.php.
Member Function Documentation
_dispatch_request ($url, $args) static private
Dispatches a HTTP request to a supporting transport.
Tests each transport in order to find a transport which matches the request arguments. Also caches the transport instance to be used later.
The order for requests is cURL, and then PHP Streams.
Since
3.2.0
private
Parameters
string $url URL to Request
array $args Request arguments
Returns
array|WP_Error Array containing 'headers', 'body', 'response', 'cookies', 'filename'. A WP_Error instance upon error
Fires after an HTTP API response is received and before the response is returned.
Since
2.8.0
Parameters
array | WP_Error $response HTTP response or WP_Error object.
string $context Context under which the hook is fired.
string $class HTTP transport used.
array $args HTTP request arguments.
string $url The request URL.
Filter the HTTP API response immediately before the response is returned.
Since
2.9.0
Parameters
array $response HTTP response.
array $args HTTP request arguments.
string $url The request URL.
Definition at line 356 of file class-http.php.
References $class, $url, __, _get_first_available_transport(), apply_filters(), do_action(), and is_wp_error().
Referenced by request().
_get_first_available_transport ($args, $url = null)
Tests which transports are capable of supporting the request.
Since
3.2.0 private
Parameters
array $args Request arguments
string $url URL to Request
Returns
string|false Class name for the first transport that claims to support the request. False if no transport claims to support the request.
Filter which HTTP transports are available and in what order.
Since
3.7.0
Parameters
array $transports Array of HTTP transports to check. Default array contains 'curl', and 'streams', in that order.
array $args HTTP request arguments.
string $url The URL to request.
Definition at line 308 of file class-http.php.
References $class, $url, and apply_filters().
Referenced by _dispatch_request().
block_request ($uri)
Block requests through the proxy.
Those who are behind a proxy and want to prevent access to certain hosts may do so. This will prevent plugins from working and core functionality, if you don't include api.wordpress.org.
You block external URL requests by defining WP_HTTP_BLOCK_EXTERNAL as true in your wp-config.php file and this will only allow localhost and your blog to make requests. The constant WP_ACCESSIBLE_HOSTS will allow additional hosts to go through for requests. The format of the WP_ACCESSIBLE_HOSTS constant is a comma separated list of hostnames to allow, wildcard domains are supported, eg *.wordpress.org will allow for all subdomains of wordpress.org to be contacted.
Since
2.8.0 Allow preventing external requests. https://core.trac.wordpress.org/ticket/14636 Allow wildcard domains in WP_ACCESSIBLE_HOSTS array|null $accessible_hosts array $wildcard_regex string $uri URI of url. bool True to block, false to allow.
Filter whether to block local requests through the proxy.
Since
2.8.0
Parameters
bool $block Whether to block local requests through proxy. Default false.
Definition at line 641 of file class-http.php.
References apply_filters(), get_option(), null, parse_url(), and str_replace.
Referenced by request().
static buildCookieHeader (& $r) static
Takes the arguments for a ::request() and checks for the cookie array.
If it's found, then it upgrades any basic name => value pairs to WP_Http_Cookie instances, which are each parsed into strings and added to the Cookie: header (within the arguments array). Edits the array by reference.
public
Version
2.8.0
Parameters
array $r Full array of args passed into ::request()
Definition at line 557 of file class-http.php.
References $name, and $value.
Referenced by WP_Http_Streams\request(), and WP_Http_Curl\request().
static chunkTransferDecode ($body) static
Decodes chunk transfer-encoding, based off the HTTP 1.1 specification.
Based off the HTTP http_encoding_dechunk function.
Process for chunked decoding. public 2.7.0 string $body Body content string Chunked decoded body on success or raw body on failure.
Definition at line 589 of file class-http.php.
Referenced by WP_Http_Streams\request().
get ($url, $args = array())
Uses the GET HTTP method.
Used for sending data that is expected to be in the body.
public
Since
2.7.0
Parameters
string $url The request URL.
string | array $args Optional. Override the defaults.
Returns
array|WP_Error Array containing 'headers', 'body', 'response', 'cookies', 'filename'. A WP_Error instance upon error
Definition at line 427 of file class-http.php.
References $url, request(), and wp_parse_args().
static handle_redirects ($url, $args, $response) static
Handles HTTP Redirects and follows them if appropriate.
Since
3.7.0
Parameters
string $url The URL which was requested.
array $args The Arguments which were used to make the request.
array $response The Response of the HTTP request.
Returns
false|object False if no redirect is present, a WP_HTTP or WP_Error result otherwise.
Definition at line 791 of file class-http.php.
References $url, __, make_absolute_url(), and wp_remote_request().
Referenced by WP_Http_Streams\request().
head ($url, $args = array())
Uses the HEAD HTTP method.
Used for sending data that is expected to be in the body.
public
Since
2.7.0
Parameters
string $url The request URL.
string | array $args Optional. Override the defaults.
Returns
array|WP_Error Array containing 'headers', 'body', 'response', 'cookies', 'filename'. A WP_Error instance upon error
Definition at line 445 of file class-http.php.
References $url, request(), and wp_parse_args().
static is_ip_address ($maybe_ip) static
Determines if a specified string represents an IP address or not.
This function also detects the type of the IP address, returning either '4' or '6' to represent a IPv4 and IPv6 address respectively. This does not verify if the IP is a valid IP, only that it appears to be an IP address.
for IPv6 regex 3.7.0 string $maybe_ip A suspected IP address integer|bool Upon success, '4' or '6' to represent a IPv4 or IPv6 address, false upon failure
Definition at line 845 of file class-http.php.
Referenced by WP_Http_Streams\verify_ssl_certificate().
static make_absolute_url ($maybe_relative_path, $url) static
Converts a relative URL to an absolute URL relative to a given URL.
If an Absolute URL is provided, no processing of that URL is done.
Since
3.4.0
public
Parameters
string $maybe_relative_path The URL which might be relative
string $url The URL which $maybe_relative_path is relative to
Returns
string An Absolute URL, in a failure condition where the URL cannot be parsed, the relative URL will be returned.
Definition at line 718 of file class-http.php.
References $path, $url, elseif, and wp_parse_url().
Referenced by _links_add_base(), and handle_redirects().
static parse_url ($url) static protected
Used as a wrapper for PHP's parse_url() function that handles edgecases in < PHP 5.4.7.
protected
Parameters
string $url The URL to parse.
Returns
bool|array False on failure; Array of URL components on success; See parse_url()'s return values.
Definition at line 699 of file class-http.php.
References $url, _deprecated_function(), and wp_parse_url().
Referenced by block_request(), and request().
post ($url, $args = array())
Uses the POST HTTP method.
Used for sending data that is expected to be in the body.
public
Since
2.7.0
Parameters
string $url The request URL.
string | array $args Optional. Override the defaults.
Returns
array|WP_Error Array containing 'headers', 'body', 'response', 'cookies', 'filename'. A WP_Error instance upon error
Definition at line 409 of file class-http.php.
References $url, request(), and wp_parse_args().
static processHeaders ($headers, $url = '') static
Transform header string into an array.
If an array is given then it is assumed to be raw header data with numeric keys with the headers as the values. No headers must be passed that were already processed.
public
Since
2.7.0
Parameters
string | array $headers
string $url The URL that was requested
Returns
array Processed string headers. If duplicate headers are encountered, Then a numbered array is returned as the value of that header-key.
Definition at line 482 of file class-http.php.
References $i, $url, $value, and str_replace.
Referenced by WP_Http_Streams\request(), and WP_Http_Curl\request().
static processResponse ($strResponse) static
Parses the responses and splits the parts into headers and body.
public
Since
2.7.0
Parameters
string $strResponse The full response string
Returns
array Array with 'headers' and 'body' keys.
Definition at line 461 of file class-http.php.
Referenced by WP_Http_Streams\request().
request ($url, $args = array())
Send an HTTP request to a URI.
Please note: The only URI that are supported in the HTTP Transport implementation are the HTTP and HTTPS protocols.
public
Since
2.7.0
string $wp_version
Parameters
string $url The request URL.
string | array $args { Optional. Array or string of HTTP request arguments.
string $method Request method. Accepts 'GET', 'POST', 'HEAD', or 'PUT'. Some transports technically allow others, but should not be assumed. Default 'GET'. int $timeout How long the connection should stay open in seconds. Default 5. int $redirection Number of allowed redirects. Not supported by all transports Default 5. string $httpversion Version of the HTTP protocol to use. Accepts '1.0' and '1.1'. Default '1.0'. string $user-agent User-agent value sent. Default WordPress/' . $wp_version . '; ' . get_bloginfo('url'). bool $reject_unsafe_urls Whether to pass URLs through {
See also
wp_http_validate_url()}. Default false. bool $blocking Whether the calling code requires the result of the request. If set to false, the request will be sent to the remote server, and processing returned to the calling code immediately, the caller will know if the request succeeded or failed, but will not receive any response from the remote server. Default true. string|array $headers Array or string of headers to send with the request. Default empty array. array $cookies List of cookies to send with the request. Default empty array. string|array $body Body to send with the request. Default null. bool $compress Whether to compress the $body when sending the request. Default false. bool $decompress Whether to decompress a compressed response. If set to false and compressed content is returned in the response anyway, it will need to be separately decompressed. Default true. bool $sslverify Whether to verify SSL for the request. Default true. string sslcertificates Absolute path to an SSL certificate .crt file. Default ABSPATH . WPINC . '/certificates/ca-bundle.crt'. bool $stream Whether to stream to a file. If set to true and no filename was given, it will be droped it in the WP temp dir and its name will be set using the basename of the URL. Default false. string $filename Filename of the file to write to when streaming. $stream must be set to true. Default null. int $limit_response_size Size in bytes to limit the response to. Default null.
}
Returns
array|WP_Error Array containing 'headers', 'body', 'response', 'cookies', 'filename'. A WP_Error instance upon error.
Filter the timeout value for an HTTP request.
Since
2.7.0
Parameters
int $timeout_value Time in seconds until a request times out. Default 5.
Filter the number of redirects allowed during an HTTP request.
Since
2.7.0
Parameters
int $redirect_count Number of redirects allowed. Default 5.
Filter the version of the HTTP protocol used in a request.
Since
2.7.0
Parameters
string $version Version of HTTP used. Accepts '1.0' and '1.1'. Default '1.0'.
Filter the user agent value sent with an HTTP request.
Since
2.7.0
Parameters
string $user_agent WordPress user agent string.
Filter whether to pass URLs through wp_http_validate_url() in an HTTP request.
Since
3.6.0
Parameters
bool $pass_url Whether to pass URLs through wp_http_validate_url(). Default false.
Filter the arguments used in an HTTP request.
Since
2.7.0
Parameters
array $r An array of HTTP request arguments.
string $url The request URL.
Filter whether to preempt an HTTP request's return value.
Returning a non-false value from the filter will short-circuit the HTTP request and return early with that value. A filter should return either:
An array containing 'headers', 'body', 'response', 'cookies', and 'filename' elements
A WP_Error instance
boolean false (to avoid short-circuiting the response)
Returning any other value may result in unexpected behaviour.
Since
2.9.0
Parameters
false | array | WP_Error $preempt Whether to preempt an HTTP request's return value. Default false.
array $r HTTP request arguments.
string $url The request URL.
Definition at line 78 of file class-http.php.
References $url, $wp_version, __, _dispatch_request(), ABSPATH, WP_Http_Encoding\accept_encoding(), apply_filters(), block_request(), get_bloginfo(), get_option(), get_temp_dir(), is_wp_error(), mbstring_binary_safe_encoding(), null, parse_url(), reset_mbstring_encoding(), wp_http_validate_url(), wp_is_writable(), wp_kses_bad_protocol(), wp_list_pluck(), wp_parse_args(), wp_unique_filename(), and WPINC.
Referenced by get(), head(), and post().
The documentation for this class was generated from the following file:
class-http.php