GravityView: getid3_handler Class Reference
getid3_handler Class Reference
Public Member Functions
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Protected Member Functions
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Private Attributes
$dependency_to = null
Detailed Description
Definition at line 1588 of file getid3.php.
Constructor & Destructor Documentation
__construct (getID3 $getid3, $call_module = null)
Definition at line 1603 of file getid3.php.
References $getid3, and str_replace.
Member Function Documentation
Analyze () abstract
Referenced by AnalyzeString().
AnalyzeString ($string)
Definition at line 1617 of file getid3.php.
References $data_string_length, Analyze(), null, and setStringMode().
error ($text) protected
Definition at line 1708 of file getid3.php.
References $text.
Referenced by getid3_ac3\Analyze(), getid3_flac\Analyze(), getid3_asf\Analyze(), getid3_riff\Analyze(), getid3_dts\Analyze(), getid3_matroska\EnsureBufferHasEnoughData(), getid3_flac\parseMETAdata(), getid3_riff\ParseRIFF(), and getid3_flac\parseSTREAMINFO().
feof () protected
Definition at line 1697 of file getid3.php.
References $data_string_length.
Referenced by getid3_matroska\EnsureBufferHasEnoughData(), getid3_mp3\getOnlyMPEGaudioInfo(), and getid3_ogg\ParseOggPageHeader().
fread ($bytes) protected
Definition at line 1655 of file getid3.php.
References ftell(), and getid3_lib\intValueSupported().
Referenced by getid3_id3v1\Analyze(), getid3_lyrics3\Analyze(), getid3_ogg\Analyze(), getid3_apetag\Analyze(), getid3_id3v2\Analyze(), getid3_ac3\Analyze(), getid3_quicktime\Analyze(), getid3_flac\Analyze(), getid3_mp3\Analyze(), getid3_asf\Analyze(), getid3_riff\Analyze(), getid3_dts\Analyze(), getid3_flv\Analyze(), getid3_mp3\decodeMPEGaudioHeader(), getid3_matroska\EnsureBufferHasEnoughData(), getid3_mp3\FreeFormatFrameLength(), getid3_lyrics3\getLyrics3Data(), getid3_mp3\getOnlyMPEGaudioInfo(), getid3_mp3\getOnlyMPEGaudioInfoBruteForce(), getid3_flac\parseMETAdata(), getid3_ogg\ParseOggPageHeader(), getid3_flac\parsePICTURE(), getid3_riff\ParseRIFF(), getid3_riff\ParseRIFFAMV(), getid3_ogg\ParseVorbisComments(), and saveAttachment().
fseek ($bytes, $whence = SEEK_SET) protected
Definition at line 1667 of file getid3.php.
References elseif, ftell(), and getid3_lib\intValueSupported().
Referenced by getid3_id3v1\Analyze(), getid3_lyrics3\Analyze(), getid3_ogg\Analyze(), getid3_apetag\Analyze(), getid3_id3v2\Analyze(), getid3_ac3\Analyze(), getid3_quicktime\Analyze(), getid3_flac\Analyze(), getid3_mp3\Analyze(), getid3_asf\Analyze(), getid3_riff\Analyze(), getid3_dts\Analyze(), getid3_flv\Analyze(), getid3_mp3\decodeMPEGaudioHeader(), getid3_matroska\EnsureBufferHasEnoughData(), getid3_mp3\FreeFormatFrameLength(), getid3_lyrics3\getLyrics3Data(), getid3_mp3\getOnlyMPEGaudioInfo(), getid3_mp3\getOnlyMPEGaudioInfoBruteForce(), getid3_ogg\ParseOggPageHeader(), getid3_riff\ParseRIFF(), getid3_riff\ParseRIFFAMV(), getid3_ogg\ParseVorbisComments(), and saveAttachment().
ftell () protected
Definition at line 1648 of file getid3.php.
References $data_string_position.
Referenced by getid3_ogg\Analyze(), getid3_apetag\Analyze(), getid3_asf\Analyze(), getid3_riff\Analyze(), getid3_flv\Analyze(), fread(), fseek(), getid3_mp3\getOnlyMPEGaudioInfo(), getid3_mp3\getOnlyMPEGaudioInfoBruteForce(), getid3_flac\parseMETAdata(), getid3_ogg\ParseOggPageHeader(), getid3_flac\parsePICTURE(), getid3_riff\ParseRIFF(), and getid3_ogg\ParseVorbisComments().
isDependencyFor ($module) final protected
Definition at line 1704 of file getid3.php.
Referenced by getid3_ac3\Analyze(), getid3_dts\Analyze(), getid3_mp3\decodeMPEGaudioHeader(), getid3_flac\parseMETAdata(), getid3_flac\parseSTREAMINFO(), and getid3_flac\parseVORBIS_COMMENT().
notice ($text) protected
Definition at line 1718 of file getid3.php.
Referenced by getid3_ogg\ParseVorbisComments().
saveAttachment ($name, $offset, $length, $image_mime = null)
Definition at line 1722 of file getid3.php.
References $dir, $name, getID3\ATTACHMENTS_INLINE, getID3\ATTACHMENTS_NONE, elseif, fread(), fseek(), null, str_replace, and warning().
Referenced by getid3_matroska\parseEBML(), and getid3_flac\parsePICTURE().
setStringMode ($string)
Definition at line 1642 of file getid3.php.
Referenced by AnalyzeString().
warning ($text) protected
Definition at line 1714 of file getid3.php.
References $text.
Referenced by getid3_riff\Analyze(), getid3_matroska\Analyze(), getid3_mp3\decodeMPEGaudioHeader(), getid3_matroska\EnsureBufferHasEnoughData(), getid3_flac\parseMETAdata(), getid3_riff\ParseRIFF(), getid3_riff\ParseRIFFAMV(), getid3_flac\parseSTREAMINFO(), getid3_ogg\ParseVorbisComments(), saveAttachment(), and getid3_matroska\unhandledElement().
Field Documentation
$data_string = '' protected
Definition at line 1596 of file getid3.php.
$data_string_flag = false protected
Definition at line 1595 of file getid3.php.
$data_string_length = 0 protected
Definition at line 1598 of file getid3.php.
Referenced by AnalyzeString(), and feof().
$data_string_position = 0 protected
Definition at line 1597 of file getid3.php.
Referenced by ftell().
$dependency_to = null private
Definition at line 1600 of file getid3.php.
$getid3 protected
Definition at line 1593 of file getid3.php.
Referenced by __construct(), and getid3_ogg\ParseVorbisComments().
The documentation for this class was generated from the following file:
getid3.php