GravityView: testXMLParser Class Reference
testXMLParser Class Reference
Public Member Functions
__construct ($in)
PHP5 constructor.
dataHandler ($parser, $data)
endHandler ($parser, $name)
parse ($in)
startHandler ($parser, $name, $attributes)
Data Fields
$data = array()
$xml
Detailed Description
Definition at line 143 of file utils.php.
Constructor & Destructor Documentation
__construct ($in)
PHP5 constructor.
Definition at line 150 of file utils.php.
References parse().
Member Function Documentation
dataHandler ($parser, $data)
Definition at line 176 of file utils.php.
References $data.
endHandler ($parser, $name)
Definition at line 181 of file utils.php.
References $data.
parse ($in)
Definition at line 159 of file utils.php.
Referenced by __construct().
startHandler ($parser, $name, $attributes)
Definition at line 170 of file utils.php.
References $attributes, $data, and $name.
Field Documentation
$data = array()
Definition at line 145 of file utils.php.
Referenced by dataHandler(), endHandler(), and startHandler().
$xml
Definition at line 144 of file utils.php.
The documentation for this class was generated from the following file:
utils.php