GravityView: GravityView_Admin_No_Conflict Class Reference
GravityView_Admin_No_Conflict Class Reference
Public Member Functions
__construct ()
no_conflict_scripts ()
Callback to eliminate any non-registered script.
no_conflict_styles ()
Callback to eliminate any non-registered style.
Private Member Functions
add_hooks ()
Add the hooks to fix script and style conflicts.
add_script_dependencies ($registered, $scripts)
Add dependencies.
remove_conflicts (&$wp_objects, $required_objects, $type='scripts')
Remove any style or script non-registered in the no conflict mode.
Detailed Description
Since
1.17
Definition at line 14 of file class-gravityview-admin-no-conflict.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Since
1.17
Definition at line 19 of file class-gravityview-admin-no-conflict.php.
References add_hooks().
Member Function Documentation
add_hooks()
add_hooks () private
Add the hooks to fix script and style conflicts.
Since
1.17
Returns
void
Definition at line 33 of file class-gravityview-admin-no-conflict.php.
Referenced by __construct().
add_script_dependencies()
add_script_dependencies ($registered, $scripts) private
Add dependencies.
Since
1.17 Moved to GravityView_Admin_No_Conflict class
Parameters
array $registered [description]
array $scripts [description]
Definition at line 208 of file class-gravityview-admin-no-conflict.php.
Referenced by remove_conflicts().
no_conflict_scripts()
no_conflict_scripts ()
Callback to eliminate any non-registered script.
Since
1.17 Moved to GravityView_Admin_No_Conflict class
Returns
void
Definition at line 51 of file class-gravityview-admin-no-conflict.php.
References gravityview(), and remove_conflicts().
no_conflict_styles()
no_conflict_styles ()
Callback to eliminate any non-registered style.
Since
1.17 Moved to GravityView_Admin_No_Conflict class
Returns
void
Runs Actions:
gravityview_remove_conflicts_after Runs after no-conflict styles are removed. You can re-add styles here.
Definition at line 110 of file class-gravityview-admin-no-conflict.php.
References gravityview(), and remove_conflicts().
remove_conflicts()
remove_conflicts (& $wp_objects, $required_objects, $type = 'scripts') private
Remove any style or script non-registered in the no conflict mode.
Since
1.17 Moved to GravityView_Admin_No_Conflict class
Parameters
WP_Dependencies $wp_objects Object of WP_Styles or WP_Scripts
string[] $required_objects List of registered script/style handles
string $type Either 'styles' or 'scripts'
Returns
void
Runs Filter:
gravityview_noconflict_{$type} Modify the list of no conflict scripts or styles
Filter is gravityview_noconflict_scripts or gravityview_noconflict_styles
Parameters
array $required_objects
Definition at line 170 of file class-gravityview-admin-no-conflict.php.
References add_script_dependencies().
Referenced by no_conflict_scripts(), and no_conflict_styles().
The documentation for this class was generated from the following file:
class-gravityview-admin-no-conflict.php