GravityView: GravityView_Field_Workflow_Step Class Reference
GravityView_Field_Workflow_Step Class Reference
Public Member Functions
__construct ()
add_hooks ()
get_workflow_step ($workflow_step_id=0)
Get a Gravity_Flow_Step object from the step ID.
modify_entry_value_workflow_step ($output, $entry, $field_settings, $field)
Get the value of the Workflow Step based on the workflow_step entry meta int value.
modify_frontend_search_fields ($search_fields=array(), GravityView_Widget_Search $widget, $widget_args=array())
Set the search field choices to the Steps available for the current form.
modify_gravityview_search_field_step_label ($label='', $gf_field=null, $field=array())
Public Member Functions inherited from GravityView_Field
__construct ()
GravityView_Field constructor.
_filter_gform_custom_merge_tags ($custom_merge_tags=array(), $form_id, $fields=array(), $element_id='')
Add custom merge tags to merge tag options.
_filter_gform_replace_merge_tags ($text, $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Match the merge tag in replacement text for the field.
_filter_sortable_fields ($not_sortable)
Use field settings to modify whether a field is sortable.
add_entry_meta ($entry_meta)
Add the custom entry meta key to make it searchable and sortable.
add_field_support ($key='', &$field_options)
add_sortable_field ($fields)
Add the field to the Filter & Sort available fields.
field_options ($field_options, $template_id, $field_id, $context, $input_type, $form_id)
Tap in here to modify field options.
replace_merge_tag ($matches=array(), $text='', $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Run GravityView filters when using GFCommon::replace_variables()
set_default_search_label ($label='', $gf_field=null, $field=array())
Allow setting a default search label for search fields based on the field type.
Data Fields
$group = 'meta'
$name = 'workflow_step'
Data Fields inherited from GravityView_Field
$_gf_field_class_name
$contexts = array('single', 'multiple', 'edit', 'export')
$default_search_label
$description
$entry_meta_is_default_column = false
$entry_meta_key = null
$entry_meta_update_callback = null
$group
standard, advanced, post, pricing, meta, gravityview
$is_numeric
$is_searchable = true
$is_sortable = true
$label
$name
$search_operators
Private Member Functions
get_step_id_from_key ($key)
Get the Workflow Step ID from a search field key.
Additional Inherited Members
Protected Member Functions inherited from GravityView_Field
custom_merge_tags ($form=array(), $fields=array())
Add custom Merge Tags to Merge Tag options, if custom Merge Tags exist.
is_choice_value_enabled ()
Check whether the enableChoiceValue flag is set for a GF field.
Protected Attributes inherited from GravityView_Field
$_custom_merge_tag = false
$_field_id = ''
$_field_options = array()
Detailed Description
Definition at line 9 of file class-gravityview-field-workflow_step.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 15 of file class-gravityview-field-workflow_step.php.
References GravityView_Field\$label, and add_hooks().
Member Function Documentation
add_hooks()
add_hooks ()
Definition at line 24 of file class-gravityview-field-workflow_step.php.
Referenced by __construct().
get_step_id_from_key()
get_step_id_from_key ($key) private
Get the Workflow Step ID from a search field key.
Parameters
string $key Search field key, in the following format: workflow_step_status_[number]
Returns
bool|int The ID of the workflow step. False if not a workflow step field key.
Definition at line 75 of file class-gravityview-field-workflow_step.php.
Referenced by modify_frontend_search_fields(), and modify_gravityview_search_field_step_label().
get_workflow_step()
get_workflow_step ($workflow_step_id = 0)
Get a Gravity_Flow_Step object from the step ID.
Since
1.17.3
GravityView_View::getFormId() to get the current form being searched Gravity_Flow_API::get_step()
Parameters
int $workflow_step_id ID of the step
Returns
bool|Gravity_Flow_Step
Definition at line 123 of file class-gravityview-field-workflow_step.php.
References $form_id, and GravityView_View\getInstance().
Referenced by modify_gravityview_search_field_step_label().
modify_entry_value_workflow_step()
modify_entry_value_workflow_step ($output, $entry, $field_settings, $field)
Get the value of the Workflow Step based on the workflow_step entry meta int value.
Gravity_Flow_API::get_current_step
Parameters
string $output HTML value output
array $entry The GF entry array
array $field_settings Settings for the particular GV field
array $field Current field being displayed
Since
1.17
Returns
string If Gravity Flow not found, or entry not processed yet, returns initial value. Otherwise, returns name of workflow step.
Definition at line 47 of file class-gravityview-field-workflow_step.php.
References $entry, and $output.
modify_frontend_search_fields()
modify_frontend_search_fields ($search_fields = array(), GravityView_Widget_Search $widget, $widget_args = array())
Set the search field choices to the Steps available for the current form.
Since
1.17.3
Parameters
array $search_fields
GravityView_Widget_Search $widget
array $widget_args
Returns
array
Definition at line 149 of file class-gravityview-field-workflow_step.php.
References $form_id, $search_field, GravityView_Plugin_Hooks_Gravity_Flow\get_status_options(), get_step_id_from_key(), and GravityView_View\getInstance().
modify_gravityview_search_field_step_label()
modify_gravityview_search_field_step_label ($label = '', $gf_field = null, $field = array())
Since
1.17.3
Parameters
string $label Existing label text, sanitized.
null | GF_Field $gf_field If search field is connected to a Gravity Forms field, the field object.
array $field Array with the following keys: field ID of the meta key or field ID to be searched, input the type of search input to be shown, label the existing label. Same as $label parameter.
Returns
string If showing a search field for a Step, show the step label.
Definition at line 97 of file class-gravityview-field-workflow_step.php.
References $field, GravityView_Field\$label, get_step_id_from_key(), and get_workflow_step().
Field Documentation
$group
$group = 'meta'
Definition at line 13 of file class-gravityview-field-workflow_step.php.
$name
$name = 'workflow_step'
Definition at line 11 of file class-gravityview-field-workflow_step.php.
The documentation for this class was generated from the following file:
class-gravityview-field-workflow_step.php