GravityView: WP_Http_Curl Class Reference
WP_Http_Curl Class Reference
Core class used to integrate Curl as an HTTP transport.
Public Member Functions
request ($url, $args=array())
Send a HTTP request to a URI using cURL extension.
Static Public Member Functions
static test ($args=array())
Determines whether this class can be used for retrieving an URL.
Private Member Functions
stream_body ($handle, $data)
Grabs the body of the cURL request.
stream_headers ($handle, $headers)
Grabs the headers of the cURL request.
Private Attributes
$body = ''
$bytes_written_total = 0
$headers = ''
$max_body_length = false
$stream_handle = false
Detailed Description
Core class used to integrate Curl as an HTTP transport.
HTTP request method uses Curl extension to retrieve the url.
Requires the Curl extension to be installed.
Since
2.7.0
Definition at line 19 of file class-wp-http-curl.php.
Member Function Documentation
request ($url, $args = array())
Send a HTTP request to a URI using cURL extension.
public
Since
2.7.0
Parameters
string $url The request URL.
string | array $args Optional. Override the defaults.
Returns
array|WP_Error Array containing 'headers', 'body', 'response', 'cookies', 'filename'. A WP_Error instance upon error
This filter is documented in wp-includes/class-wp-http-streams.php
This filter is documented in wp-includes/class-wp-http-streams.php
Fires before the cURL request is executed.
Cookies are not currently handled by the HTTP API. This action allows plugins to handle cookies themselves.
Since
2.8.0
Parameters
resource &$handle The cURL handle returned by curl_init().
array $r The HTTP request arguments.
string $url The request URL.
Definition at line 76 of file class-wp-http-curl.php.
References $body, $bytes_written_total, $headers, $name, $url, $value, __, apply_filters(), WP_Http\buildCookieHeader(), WP_Http_Encoding\decompress(), do_action_ref_array(), elseif, null, WP_Http\processHeaders(), WP_Http_Encoding\should_decode(), WP_DEBUG, and wp_parse_args().
stream_body ($handle, $data) private
Grabs the body of the cURL request.
The contents of the document are passed in chunks, so we append to the $body property for temporary storage. Returning a length shorter than the length of $data passed in will cause cURL to abort the request with CURLE_WRITE_ERROR.
Since
3.6.0 private
Parameters
resource $handle cURL handle.
string $data cURL request body.
Returns
int Total bytes of data written.
Definition at line 332 of file class-wp-http-curl.php.
References $bytes_written_total.
stream_headers ($handle, $headers) private
Grabs the headers of the cURL request.
Each header is sent individually to this callback, so we append to the $header property for temporary storage
Since
3.2.0 private
Parameters
resource $handle cURL handle.
string $headers cURL request headers.
Returns
int Length of the request headers.
Definition at line 313 of file class-wp-http-curl.php.
References $headers.
static test ($args = array()) static
Determines whether this class can be used for retrieving an URL.
Since
2.7.0
Parameters
array $args Optional. Array of request arguments. Default empty array.
Returns
bool False means this class can not be used, true means it can.
Filter whether cURL can be used as a transport for retrieving a URL.
Since
2.7.0
Parameters
bool $use_class Whether the class can be used. Default true.
array $args An array of request arguments.
Definition at line 362 of file class-wp-http-curl.php.
References apply_filters().
Field Documentation
$body = '' private
Definition at line 37 of file class-wp-http-curl.php.
Referenced by request().
$bytes_written_total = 0 private
Definition at line 64 of file class-wp-http-curl.php.
Referenced by request(), and stream_body().
$headers = '' private
Definition at line 28 of file class-wp-http-curl.php.
Referenced by request(), and stream_headers().
$max_body_length = false private
Definition at line 46 of file class-wp-http-curl.php.
$stream_handle = false private
Definition at line 55 of file class-wp-http-curl.php.
The documentation for this class was generated from the following file:
class-wp-http-curl.php