GravityView: WP_UnitTest_Factory_For_Term Class Reference
WP_UnitTest_Factory_For_Term Class Reference
Public Member Functions
__construct ($factory=null, $taxonomy=null)
add_post_terms ($post_id, $terms, $taxonomy, $append=true)
create_and_get ($args=array(), $generation_definitions=null)
create_object ($args)
get_object_by_id ($term_id)
update_object ($term, $fields)
Public Member Functions inherited from WP_UnitTest_Factory_For_Thing
__construct ($factory, $default_generation_definitions=array())
Creates a new factory, which will create objects of a specific Thing.
addslashes_deep ($value)
apply_callbacks ($callbacks, $created)
callback ($function)
create ($args=array(), $generation_definitions=null)
create_and_get ($args=array(), $generation_definitions=null)
create_many ($count, $args=array(), $generation_definitions=null)
create_object ($args)
generate_args ($args=array(), $generation_definitions=null, &$callbacks=null)
get_object_by_id ($object_id)
update_object ($object, $fields)
Data Fields
const DEFAULT_TAXONOMY = 'post_tag'
Data Fields inherited from WP_UnitTest_Factory_For_Thing
$default_generation_definitions
$factory
Private Attributes
$taxonomy
Detailed Description
Definition at line 253 of file tmp/wordpress-tests-lib/includes/factory.php.
Constructor & Destructor Documentation
__construct ($factory = null, $taxonomy = null)
Definition at line 258 of file tmp/wordpress-tests-lib/includes/factory.php.
References WP_UnitTest_Factory_For_Thing\$factory, and $taxonomy.
Member Function Documentation
add_post_terms ($post_id, $terms, $taxonomy, $append = true)
Definition at line 284 of file tmp/wordpress-tests-lib/includes/factory.php.
References $post_id, $taxonomy, and wp_set_post_terms().
create_and_get ($args = array(), $generation_definitions = null)
Definition at line 288 of file tmp/wordpress-tests-lib/includes/factory.php.
References $taxonomy, WP_UnitTest_Factory_For_Thing\create(), and get_term().
create_object ($args)
Definition at line 268 of file tmp/wordpress-tests-lib/includes/factory.php.
References is_wp_error(), and wp_insert_term().
get_object_by_id ($term_id)
Definition at line 294 of file tmp/wordpress-tests-lib/includes/factory.php.
References get_term().
update_object ($term, $fields)
Definition at line 276 of file tmp/wordpress-tests-lib/includes/factory.php.
References $taxonomy, and wp_update_term().
Field Documentation
$taxonomy private
Definition at line 255 of file tmp/wordpress-tests-lib/includes/factory.php.
Referenced by __construct(), add_post_terms(), create_and_get(), and update_object().
const DEFAULT_TAXONOMY = 'post_tag'
Definition at line 256 of file tmp/wordpress-tests-lib/includes/factory.php.
The documentation for this class was generated from the following file:
tmp/wordpress-tests-lib/includes/factory.php