GravityView: WP_Network Class Reference
WP_Network Class Reference
Core class used for interacting with a multisite network.
Public Member Functions
__construct ($network)
Create a new WP_Network object.
Static Public Member Functions
static get_by_path ($domain= '', $path= '', $segments=null)
Retrieve the closest matching network for a domain and path.
static get_instance ($network_id)
Retrieve a network from the database by its ID.
Data Fields
$blog_id = 0
$cookie_domain = ''
$domain = ''
$id
$path = ''
$site_name = ''
Private Member Functions
_set_cookie_domain ()
Set the cookie domain based on the network domain if one has not been populated.
_set_site_name ()
Set the site name assigned to the network if one has not been populated.
Detailed Description
Core class used for interacting with a multisite network.
This class is used during load to populate the $current_site global and setup the current network.
This class is most useful in WordPress multi-network installations where the ability to interact with any network of sites is required.
Since
4.4.0
Definition at line 21 of file class-wp-network.php.
Constructor & Destructor Documentation
__construct ($network)
Create a new WP_Network object.
Will populate object properties from the object provided and assign other default properties based on that information.
Since
4.4.0 public
Parameters
WP_Network | object $network A network object.
Definition at line 127 of file class-wp-network.php.
References $value, _set_cookie_domain(), and _set_site_name().
Member Function Documentation
_set_cookie_domain () private
Set the cookie domain based on the network domain if one has not been populated.
Since
4.4.0 private
Definition at line 160 of file class-wp-network.php.
References $domain.
Referenced by __construct().
_set_site_name () private
Set the site name assigned to the network if one has not been populated.
Since
4.4.0 private
Definition at line 142 of file class-wp-network.php.
References $default, and get_network_option().
Referenced by __construct().
static get_by_path ($domain = '', $path = '', $segments = null) static
Retrieve the closest matching network for a domain and path.
This will not necessarily return an exact match for a domain and path. Instead, it breaks the domain and path into pieces that are then used to match the closest possibility from a query.
The intent of this method is to match a network during bootstrap for a requested site address.
Since
4.4.0 public
Parameters
string $domain Domain to check.
string $path Path to check.
int | null $segments Path segments to use. Defaults to null, or the full path.
Returns
WP_Network|bool Network object if successful. False when no network is found.
Filter the number of path segments to consider when searching for a site.
Since
3.9.0
Parameters
int | null $segments The number of path segments to consider. WordPress by default looks at one path segment. The function default of null only makes sense when you know the requested path should match a network.
string $domain The requested domain.
string $path The requested path, in full.
Determine a network by its domain and path.
This allows one to short-circuit the default logic, perhaps by replacing it with a routine that is more optimal for your setup.
Return null to avoid the short-circuit. Return false if no network can be found at the requested domain and path. Otherwise, return an object from wp_get_network().
Since
3.9.0
Parameters
null | bool | object $network Network value to return by path.
string $domain The requested domain.
string $path The requested path, in full.
int | null $segments The suggested number of paths to consult. Default null, meaning the entire path was to be consulted.
array $paths The paths to search for, based on $path and $segments.
Definition at line 190 of file class-wp-network.php.
References $domain, $path, $wpdb, apply_filters(), is_wp_error(), null, wp_cache_add(), wp_cache_get(), and wp_using_ext_object_cache().
Referenced by get_network_by_path().
static get_instance ($network_id) static
Retrieve a network from the database by its ID.
Since
4.4.0 public
wpdb $wpdb WordPress database abstraction object.
Parameters
int $network_id The ID of the network to retrieve.
Returns
WP_Network|bool The network's object if found. False if not.
Definition at line 93 of file class-wp-network.php.
References $wpdb, is_wp_error(), wp_cache_add(), and wp_cache_get().
Referenced by wp_get_network().
Field Documentation
$blog_id = 0
Definition at line 60 of file class-wp-network.php.
$cookie_domain = ''
Definition at line 69 of file class-wp-network.php.
$domain = ''
Definition at line 39 of file class-wp-network.php.
Referenced by _set_cookie_domain(), and get_by_path().
$id
Definition at line 30 of file class-wp-network.php.
$path = ''
Definition at line 48 of file class-wp-network.php.
Referenced by get_by_path().
$site_name = ''
Definition at line 80 of file class-wp-network.php.
The documentation for this class was generated from the following file:
class-wp-network.php