GravityView: getid3_lyrics3 Class Reference
getid3_lyrics3 Class Reference
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
Public Member Functions
Analyze ()
getLyrics3Data ($endoffset, $version, $length)
IntString2Bool ($char)
Lyrics3LyricsTimestampParse (&$Lyrics3data)
Lyrics3Timestamp2Seconds ($rawtimestamp)
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
getID3() by James Heinrich info@.nosp@m.geti.nosp@m.d3.or.nosp@m.g //
//
Definition at line 18 of file module.tag.lyrics3.php.
Member Function Documentation
Analyze ()
Definition at line 21 of file module.tag.lyrics3.php.
References elseif, getid3_handler\fread(), getid3_handler\fseek(), getLyrics3Data(), getid3_lib\IncludeDependency(), and getid3_lib\intValueSupported().
getLyrics3Data ($endoffset, $version, $length)
Definition at line 129 of file module.tag.lyrics3.php.
References $i, $value, getid3_handler\fread(), getid3_handler\fseek(), IntString2Bool(), getid3_lib\intValueSupported(), Lyrics3LyricsTimestampParse(), and Lyrics3Timestamp2Seconds().
Referenced by Analyze().
IntString2Bool ($char)
Definition at line 290 of file module.tag.lyrics3.php.
References elseif, and null.
Referenced by getLyrics3Data().
Lyrics3LyricsTimestampParse (& $Lyrics3data)
Definition at line 260 of file module.tag.lyrics3.php.
References Lyrics3Timestamp2Seconds(), and str_replace.
Referenced by getLyrics3Data().
Lyrics3Timestamp2Seconds ($rawtimestamp)
Definition at line 253 of file module.tag.lyrics3.php.
Referenced by getLyrics3Data(), and Lyrics3LyricsTimestampParse().
The documentation for this class was generated from the following file:
module.tag.lyrics3.php