GravityView: GravityView_Entry_Approval_Test Class Reference
GravityView_Entry_Approval_Test Class Reference
Public Member Functions
setUp ()
test_add_approval_status_updated_note ()
GravityView_Entry_Approval::add_approval_status_updated_note
test_update_approved ()
test_update_bulk ()
GravityView_Entry_Approval::update_bulk
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Private Attributes
$entries = array()
$form = array()
$form_id = 0
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
Since
1.18 approval
Definition at line 9 of file GravityView_Entry_Approval_Test.php.
Member Function Documentation
setUp ()
Definition at line 17 of file GravityView_Entry_Approval_Test.php.
test_add_approval_status_updated_note ()
GravityView_Entry_Approval::add_approval_status_updated_note
Definition at line 62 of file GravityView_Entry_Approval_Test.php.
References GravityView_Entry_Approval_Status\APPROVED.
test_update_approved ()
Since
1.18 GravityView_Entry_Approval::update_approved GravityView_Cache::in_blacklist()
Definition at line 32 of file GravityView_Entry_Approval_Test.php.
References GravityView_Entry_Approval_Status\APPROVED, GravityView_Entry_Approval_Status\get_all(), GravityView_Entry_Approval\get_entry_status(), GravityView_Cache, GravityView_Entry_Approval_Status\UNAPPROVED, and GravityView_Entry_Approval\update_approved().
test_update_bulk ()
GravityView_Entry_Approval::update_bulk
Definition at line 89 of file GravityView_Entry_Approval_Test.php.
References $entry, GravityView_Entry_Approval_Status\APPROVED, GravityView_Entry_Approval_Status\get_all(), GravityView_Entry_Approval\get_entry_status(), and GravityView_Entry_Approval\update_bulk().
Field Documentation
$entries = array() private
Definition at line 11 of file GravityView_Entry_Approval_Test.php.
$form = array() private
Definition at line 13 of file GravityView_Entry_Approval_Test.php.
$form_id = 0 private
Definition at line 15 of file GravityView_Entry_Approval_Test.php.
The documentation for this class was generated from the following file:
GravityView_Entry_Approval_Test.php