GravityView: GravityView_Merge_Tags_Test Class Reference
GravityView_Merge_Tags_Test Class Reference
merge_tags
Public Member Functions
test_gf_merge_tags ()
We want to make sure that GravityView doesn't mess with Texas.
test_replace_date_created ()
GravityView_Field_Date_Created::replace_merge_tag date_created
test_replace_field_custom_merge_tags ()
GravityView_Field::replace_merge_tag GravityView_Field_Payment_Amount::replace_merge_tag GravityView_Field_Payment_Status::replace_merge_tag GravityView_Field_Payment_Method::replace_merge_tag
test_replace_get_variables ()
test_replace_user_variables_created_by ()
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
merge_tags
Since
1.15
Definition at line 9 of file GravityView_Merge_Tags_Test.php.
Member Function Documentation
test_gf_merge_tags ()
We want to make sure that GravityView doesn't mess with Texas.
Since
1.15.1
Definition at line 188 of file GravityView_Merge_Tags_Test.php.
References $merge_tag, $post, and GravityView_Merge_Tags\replace_variables().
test_replace_date_created ()
GravityView_Field_Date_Created::replace_merge_tag date_created
adjusting date to local configured Time Zone
See also
GFCommon::format_date()
Definition at line 41 of file GravityView_Merge_Tags_Test.php.
References $merge_tag, and GravityView_Merge_Tags\replace_variables().
test_replace_field_custom_merge_tags ()
GravityView_Field::replace_merge_tag GravityView_Field_Payment_Amount::replace_merge_tag GravityView_Field_Payment_Status::replace_merge_tag GravityView_Field_Payment_Method::replace_merge_tag
Since
1.16
Definition at line 112 of file GravityView_Merge_Tags_Test.php.
References $merge_tag, GravityView_Fields\get(), and GravityView_Merge_Tags\replace_variables().
test_replace_get_variables ()
Since
1.15 GravityView_Merge_Tags::replace_get_variables() GravityView_Merge_Tags::replace_variables() GravityView_Merge_Tags::replace_gv_merge_tags()
Definition at line 151 of file GravityView_Merge_Tags_Test.php.
References GravityView_Merge_Tags\replace_variables().
test_replace_user_variables_created_by ()
Since
1.15.1 GravityView_Merge_Tags::replace_user_variables_created_by() GravityView_Merge_Tags::replace_variables() GravityView_Merge_Tags::replace_gv_merge_tags()
Definition at line 17 of file GravityView_Merge_Tags_Test.php.
References $merge_tag, and GravityView_Merge_Tags\replace_variables().
The documentation for this class was generated from the following file:
GravityView_Merge_Tags_Test.php