GravityView: SimplePie_IRI Class Reference
SimplePie_IRI Class Reference
Public Member Functions
__construct ($iri=null)
Create a new IRI object, from a specified string.
__get ($name)
Overload __get() to provide access via properties.
__isset ($name)
Overload __isset() to provide access via properties.
__set ($name, $value)
Overload __set() to provide access via properties.
__toString ()
Return the entire IRI when you try and read the object as a string.
__unset ($name)
Overload __unset() to provide access via properties.
get_iri ()
Get the complete IRI.
get_uri ()
Get the complete URI.
is_valid ()
Check if the object represents a valid IRI.
set_authority ($authority)
Set the authority.
set_fragment ($ifragment)
Set the ifragment.
set_host ($ihost)
Set the ihost.
set_iri ($iri)
Set the entire IRI.
set_path ($ipath)
Set the ipath.
set_port ($port)
Set the port.
set_query ($iquery)
Set the iquery.
set_scheme ($scheme)
Set the scheme.
set_userinfo ($iuserinfo)
Set the iuserinfo.
to_uri ($string)
Convert an IRI to a URI (or parts thereof)
Static Public Member Functions
static absolutize ($base, $relative)
Create a new IRI object by resolving a relative IRI.
Protected Member Functions
get_authority ()
Get the complete authority.
get_iauthority ()
Get the complete iauthority.
parse_iri ($iri)
Parse an IRI into scheme/authority/path/query/fragment segments.
remove_dot_segments ($input)
Remove dot segments from a path.
remove_iunreserved_percent_encoded ($match)
Callback function for preg_replace_callback.
replace_invalid_with_pct_encoding ($string, $extra_chars, $iprivate=false)
Replace invalid character with percent encoding.
scheme_normalization ()
Protected Attributes
$ifragment = null
$ihost = null
$ipath = ''
$iquery = null
$iuserinfo = null
$normalization
Normalization database.
$port = null
$scheme = null
Detailed Description
Definition at line 56 of file IRI.php.
Constructor & Destructor Documentation
__construct ($iri = null)
Create a new IRI object, from a specified string.
Parameters
string $iri
Definition at line 257 of file IRI.php.
References set_iri().
Member Function Documentation
__get ($name)
Overload __get() to provide access via properties.
Parameters
string $name Property name
Returns
mixed
Definition at line 174 of file IRI.php.
References $name, $scheme, elseif, and null.
__isset ($name)
Overload __isset() to provide access via properties.
Parameters
string $name Property name
Returns
bool
Definition at line 227 of file IRI.php.
References $name.
__set ($name, $value)
Overload __set() to provide access via properties.
Parameters
string $name Property name
mixed $value Property value
Definition at line 149 of file IRI.php.
References $name, $value, and elseif.
__toString ()
Return the entire IRI when you try and read the object as a string.
Returns
string
Definition at line 138 of file IRI.php.
References get_iri().
__unset ($name)
Overload __unset() to provide access via properties.
Parameters
string $name Property name
Definition at line 244 of file IRI.php.
References $name.
static absolutize ($base, $relative) static
Create a new IRI object by resolving a relative IRI.
Returns false if $base is not absolute, otherwise an IRI.
Parameters
IRI | string $base (Absolute) Base IRI
IRI | string $relative Relative IRI
Returns
IRI|false
Definition at line 271 of file IRI.php.
References elseif, and null.
Referenced by SimplePie_Misc\absolutize_url().
get_authority () protected
Get the complete authority.
Returns
string
Definition at line 1230 of file IRI.php.
References get_iauthority(), and to_uri().
get_iauthority () protected
Get the complete iauthority.
Returns
string
Definition at line 1200 of file IRI.php.
References $ihost, $port, and null.
Referenced by get_authority(), and get_iri().
get_iri ()
Get the complete IRI.
Returns
string
Definition at line 1149 of file IRI.php.
References $ifragment, $ipath, $iquery, $scheme, elseif, get_iauthority(), is_valid(), and null.
Referenced by __toString(), and get_uri().
get_uri ()
Get the complete URI.
Returns
string
Definition at line 1190 of file IRI.php.
References get_iri(), and to_uri().
is_valid ()
Check if the object represents a valid IRI.
This needs to be done on each call as some things change depending on another part of the IRI.
Returns
bool
Definition at line 769 of file IRI.php.
References null.
Referenced by get_iri().
parse_iri ($iri) protected
Parse an IRI into scheme/authority/path/query/fragment segments.
Parameters
string $iri
Returns
array
Definition at line 364 of file IRI.php.
References null.
Referenced by set_iri().
remove_dot_segments ($input) protected
Remove dot segments from a path.
Parameters
string $input
Returns
string
Definition at line 404 of file IRI.php.
References $output, and elseif.
Referenced by set_path().
remove_iunreserved_percent_encoded ($match) protected
Callback function for preg_replace_callback.
Removes sequences of percent encoded bytes that represent UTF-8 encoded characters in iunreserved
Parameters
array $match PCRE match
Returns
string Replacement
Definition at line 603 of file IRI.php.
References $i, $value, and elseif.
replace_invalid_with_pct_encoding ($string, $extra_chars, $iprivate = false) protected
Replace invalid character with percent encoding.
Parameters
string $string Input string
string $extra_chars Valid characters not in iunreserved or iprivate (this is ASCII-only)
bool $iprivate Allow iprivate
Returns
string
Definition at line 467 of file IRI.php.
References $value, and elseif.
Referenced by set_fragment(), set_host(), set_path(), set_query(), and set_userinfo().
scheme_normalization () protected
Definition at line 735 of file IRI.php.
References null.
Referenced by set_fragment(), set_host(), set_path(), set_port(), set_query(), and set_userinfo().
set_authority ($authority)
Set the authority.
Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $authority
Returns
bool
Definition at line 882 of file IRI.php.
References $iuserinfo, $port, elseif, null, set_host(), set_port(), and set_userinfo().
Referenced by set_iri().
set_fragment ($ifragment)
Set the ifragment.
Parameters
string $ifragment
Returns
bool
Definition at line 1105 of file IRI.php.
References $ifragment, null, replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_iri().
set_host ($ihost)
Set the ihost.
Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $ihost
Returns
bool
Definition at line 970 of file IRI.php.
References $ihost, SimplePie_Net_IPv6\check_ipv6(), SimplePie_Net_IPv6\compress(), elseif, null, replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_authority().
set_iri ($iri)
Set the entire IRI.
Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $iri
Returns
bool
Definition at line 800 of file IRI.php.
References elseif, null, parse_iri(), set_authority(), set_fragment(), set_path(), set_query(), and set_scheme().
Referenced by __construct().
set_path ($ipath)
Set the ipath.
Parameters
string $ipath
Returns
bool
Definition at line 1052 of file IRI.php.
References $ipath, null, remove_dot_segments(), replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_iri().
set_port ($port)
Set the port.
Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $port
Returns
bool
Definition at line 1026 of file IRI.php.
References $port, elseif, null, and scheme_normalization().
Referenced by set_authority().
set_query ($iquery)
Set the iquery.
Parameters
string $iquery
Returns
bool
Definition at line 1085 of file IRI.php.
References $iquery, null, replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_iri().
set_scheme ($scheme)
Set the scheme.
Returns true on success, false on failure (if there are any invalid characters).
Parameters
string $scheme
Returns
bool
Definition at line 857 of file IRI.php.
References $scheme, elseif, and null.
Referenced by set_iri().
set_userinfo ($iuserinfo)
Set the iuserinfo.
Parameters
string $iuserinfo
Returns
bool
Definition at line 948 of file IRI.php.
References $iuserinfo, null, replace_invalid_with_pct_encoding(), and scheme_normalization().
Referenced by set_authority().
to_uri ($string)
Convert an IRI to a URI (or parts thereof)
Returns
string
Definition at line 1124 of file IRI.php.
Referenced by get_authority(), and get_uri().
Field Documentation
$ifragment = null protected
Definition at line 105 of file IRI.php.
Referenced by get_iri(), and set_fragment().
$ihost = null protected
Definition at line 77 of file IRI.php.
Referenced by get_iauthority(), and set_host().
$ipath = '' protected
Definition at line 91 of file IRI.php.
Referenced by get_iri(), and set_path().
$iquery = null protected
Definition at line 98 of file IRI.php.
Referenced by get_iri(), and set_query().
$iuserinfo = null protected
Definition at line 70 of file IRI.php.
Referenced by set_authority(), and set_userinfo().
$normalization protected
Initial value:
= array(
        'acap' => array(
            'port' => 674
        ),
        'dict' => array(
            'port' => 2628
        ),
        'file' => array(
            'ihost' => 'localhost'
        ),
        'http' => array(
            'port' => 80,
            'ipath' => '/'
        ),
        'https' => array(
            'port' => 443,
            'ipath' => '/'
        ),
    )
Normalization database.
Each key is the scheme, each value is an array with each key as the IRI part and value as the default value for that part.
Definition at line 113 of file IRI.php.
$port = null protected
Definition at line 84 of file IRI.php.
Referenced by get_iauthority(), set_authority(), and set_port().
$scheme = null protected
Definition at line 63 of file IRI.php.
Referenced by __get(), get_iri(), and set_scheme().
The documentation for this class was generated from the following file:
IRI.php