GravityView: WP_HTTP_Proxy Class Reference
WP_HTTP_Proxy Class Reference
Core class used to implement HTTP API proxy support.
Public Member Functions
authentication ()
Retrieve authentication string for proxy authentication.
authentication_header ()
Retrieve header string for proxy authentication.
host ()
Retrieve the host for the proxy server.
is_enabled ()
Whether proxy connection should be used.
password ()
Retrieve the password for proxy authentication.
port ()
Retrieve the port for the proxy server.
send_through_proxy ($uri)
Whether URL should be sent through the proxy server.
use_authentication ()
Whether authentication should be used.
username ()
Retrieve the username for proxy authentication.
Detailed Description
Core class used to implement HTTP API proxy support.
There are caveats to proxy support. It requires that defines be made in the wp-config.php file to enable proxy support. There are also a few filters that plugins can hook into for some of the constants.
Please note that only BASIC authentication is supported by most transports. cURL MAY support more methods (such as NTLM authentication) depending on your environment.
The constants are as follows:
WP_PROXY_HOST - Enable proxy support and host for connecting.
WP_PROXY_PORT - Proxy port for connection. No default, must be defined.
WP_PROXY_USERNAME - Proxy username, if it requires authentication.
WP_PROXY_PASSWORD - Proxy password, if it requires authentication.
WP_PROXY_BYPASS_HOSTS - Will prevent the hosts in this list from going through the proxy. You do not need to have localhost and the blog host in this list, because they will not be passed through the proxy. The list should be presented in a comma separated list, wildcards using * are supported, eg. *.wordpress.org
An example can be as seen below.
define('WP_PROXY_HOST', '192.168.84.101');
define('WP_PROXY_PORT', '8080');
define('WP_PROXY_BYPASS_HOSTS', 'localhost, www.example.com, *.wordpress.org');
Proxy support ticket in WordPress. https://core.trac.wordpress.org/ticket/14636 Allow wildcard domains in WP_PROXY_BYPASS_HOSTS 2.8.0
Definition at line 42 of file class-wp-http-proxy.php.
Member Function Documentation
authentication ()
Retrieve authentication string for proxy authentication.
Since
2.8.0
Returns
string
Definition at line 135 of file class-wp-http-proxy.php.
References password(), and username().
Referenced by authentication_header().
authentication_header ()
Retrieve header string for proxy authentication.
Since
2.8.0
Returns
string
Definition at line 146 of file class-wp-http-proxy.php.
References authentication().
host ()
Retrieve the host for the proxy server.
Since
2.8.0
Returns
string
Definition at line 79 of file class-wp-http-proxy.php.
is_enabled ()
Whether proxy connection should be used.
Since
2.8.0
WP_PROXY_HOST WP_PROXY_PORT
Returns
bool
Definition at line 54 of file class-wp-http-proxy.php.
password ()
Retrieve the password for proxy authentication.
Since
2.8.0
Returns
string
Definition at line 121 of file class-wp-http-proxy.php.
Referenced by authentication().
port ()
Retrieve the port for the proxy server.
Since
2.8.0
Returns
string
Definition at line 93 of file class-wp-http-proxy.php.
send_through_proxy ($uri)
Whether URL should be sent through the proxy server.
We want to keep localhost and the blog URL from being sent through the proxy server, because some proxies can not handle this. We also have the constant available for defining other hosts that won't be sent through the proxy.
Since
2.8.0
array|null $bypass_hosts array $wildcard_regex
Parameters
string $uri URI to check.
Returns
bool True, to send through the proxy and false if, the proxy should not be used.
Filter whether to preempt sending the request through the proxy server.
Returning false will bypass the proxy; returning true will send the request through the proxy. Returning null bypasses the filter.
Since
3.5.0
Parameters
null $override Whether to override the request result. Default null.
string $uri URL to check.
array $check Associative array result of parsing the URI.
array $home Associative array result of parsing the site URL.
Definition at line 165 of file class-wp-http-proxy.php.
References apply_filters(), get_option(), null, and str_replace.
use_authentication ()
Whether authentication should be used.
Since
2.8.0
WP_PROXY_USERNAME WP_PROXY_PASSWORD
Returns
bool
Definition at line 68 of file class-wp-http-proxy.php.
username ()
Retrieve the username for proxy authentication.
Since
2.8.0
Returns
string
Definition at line 107 of file class-wp-http-proxy.php.
Referenced by authentication().
The documentation for this class was generated from the following file:
class-wp-http-proxy.php