GravityView: WP_Internal_Pointers Class Reference
WP_Internal_Pointers Class Reference
Core class used to implement an internal admin pointers API.
Static Public Member Functions
static dismiss_pointers_for_new_users ($user_id)
Prevents new users from seeing existing 'new feature' pointers.
static enqueue_scripts ($hook_suffix)
Initializes the new feature pointers.
static pointer_wp330_media_uploader ()
static pointer_wp330_saving_widgets ()
static pointer_wp330_toolbar ()
static pointer_wp340_choose_image_from_library ()
static pointer_wp340_customize_current_theme_link ()
static pointer_wp350_media ()
static pointer_wp360_locks ()
static pointer_wp360_revisions ()
static pointer_wp390_widgets ()
static pointer_wp410_dfw ()
Static Private Member Functions
static print_js ($pointer_id, $selector, $args)
Print the pointer JavaScript data.
Detailed Description
Core class used to implement an internal admin pointers API.
Since
3.3.0
Definition at line 15 of file class-wp-internal-pointers.php.
Member Function Documentation
static dismiss_pointers_for_new_users ($user_id) static
Prevents new users from seeing existing 'new feature' pointers.
Since
3.3.0
Parameters
int $user_id User ID.
Definition at line 163 of file class-wp-internal-pointers.php.
References $user_id, and add_user_meta().
static enqueue_scripts ($hook_suffix) static
Initializes the new feature pointers.
Since
3.3.0
All pointers can be disabled using the following: remove_action('admin_enqueue_scripts', array('WP_Internal_Pointers', 'enqueue_scripts'));
Individual pointers (e.g. wp390_widgets) can be disabled using the following: remove_action('admin_print_footer_scripts', array('WP_Internal_Pointers', 'pointer_wp390_widgets'));
Parameters
string $hook_suffix The current admin page.
Definition at line 31 of file class-wp-internal-pointers.php.
References $hook_suffix, add_action(), current_user_can(), get_current_user_id(), get_user_meta(), wp_enqueue_script(), and wp_enqueue_style().
static pointer_wp330_media_uploader () static
Definition at line 144 of file class-wp-internal-pointers.php.
static pointer_wp330_saving_widgets () static
Definition at line 145 of file class-wp-internal-pointers.php.
static pointer_wp330_toolbar () static
Definition at line 143 of file class-wp-internal-pointers.php.
static pointer_wp340_choose_image_from_library () static
Definition at line 147 of file class-wp-internal-pointers.php.
static pointer_wp340_customize_current_theme_link () static
Definition at line 146 of file class-wp-internal-pointers.php.
static pointer_wp350_media () static
Definition at line 148 of file class-wp-internal-pointers.php.
static pointer_wp360_locks () static
Definition at line 150 of file class-wp-internal-pointers.php.
static pointer_wp360_revisions () static
Definition at line 149 of file class-wp-internal-pointers.php.
static pointer_wp390_widgets () static
Definition at line 151 of file class-wp-internal-pointers.php.
static pointer_wp410_dfw () static
Definition at line 152 of file class-wp-internal-pointers.php.
static print_js ($pointer_id, $selector, $args) static private
Print the pointer JavaScript data.
Since
3.3.0
Parameters
string $pointer_id The pointer ID.
string $selector The HTML elements, on which the pointer should be attached.
array $args Arguments to be passed to the pointer JS (see wp-pointer.js).
Definition at line 108 of file class-wp-internal-pointers.php.
References wp_json_encode().
The documentation for this class was generated from the following file:
class-wp-internal-pointers.php