GravityView: getid3_asf Class Reference
getid3_asf Class Reference
Public Member Functions
__construct (getID3 $getid3)
Analyze ()
ASF_WMpicture (&$data)
HeaderExtensionObjectDataParse (&$asf_header_extension_object_data, &$unhandled_sections)
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Static Public Member Functions
static ASFIndexObjectIndexTypeLookup ($id)
static BytestringToGUID ($Bytestring)
static codecListObjectTypeLookup ($CodecListType)
static FILETIMEtoUNIXtime ($FILETIME, $round=true)
static GUIDname ($GUIDstring)
static GUIDtoBytestring ($GUIDstring)
static KnownGUIDs ()
static metadataLibraryObjectDataTypeLookup ($id)
static TrimConvert ($string)
static TrimTerm ($string)
static WMpictureTypeLookup ($WMpictureType)
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
Definition at line 19 of file module.audio-video.asf.php.
Constructor & Destructor Documentation
__construct (getID3 $getid3)
Definition at line 21 of file module.audio-video.asf.php.
References GUIDtoBytestring(), and KnownGUIDs().
Member Function Documentation
Analyze ()
Definition at line 33 of file module.audio-video.asf.php.
References $value, getid3_lib\array_merge_noclobber(), ASF_WMpicture(), ASFIndexObjectIndexTypeLookup(), BytestringToGUID(), elseif, getid3_handler\error(), FILETIMEtoUNIXtime(), getid3_riff\fourccLookup(), getid3_handler\fread(), getid3_handler\fseek(), getid3_handler\ftell(), GUIDname(), GUIDtoBytestring(), HeaderExtensionObjectDataParse(), getid3_lib\LittleEndian2Int(), getid3_riff\parseWAVEFORMATex(), str_replace, TrimConvert(), and TrimTerm().
ASF_WMpicture (& $data)
Definition at line 1947 of file module.audio-video.asf.php.
References getid3_lib\GetDataImageSize(), and getid3_lib\LittleEndian2Int().
Referenced by Analyze(), and HeaderExtensionObjectDataParse().
static ASFIndexObjectIndexTypeLookup ($id) static
Definition at line 1575 of file module.audio-video.asf.php.
References $id.
Referenced by Analyze().
static BytestringToGUID ($Bytestring) static
Definition at line 1620 of file module.audio-video.asf.php.
Referenced by Analyze(), and HeaderExtensionObjectDataParse().
static codecListObjectTypeLookup ($CodecListType) static
Definition at line 1443 of file module.audio-video.asf.php.
static FILETIMEtoUNIXtime ($FILETIME, $round = true) static
Definition at line 1645 of file module.audio-video.asf.php.
Referenced by Analyze(), and HeaderExtensionObjectDataParse().
static GUIDname ($GUIDstring) static
Definition at line 1567 of file module.audio-video.asf.php.
Referenced by Analyze(), and HeaderExtensionObjectDataParse().
static GUIDtoBytestring ($GUIDstring) static
Definition at line 1585 of file module.audio-video.asf.php.
Referenced by __construct(), and Analyze().
HeaderExtensionObjectDataParse (& $asf_header_extension_object_data, & $unhandled_sections)
Definition at line 1687 of file module.audio-video.asf.php.
References $i, $value, ASF_WMpicture(), BytestringToGUID(), FILETIMEtoUNIXtime(), GUIDname(), getid3_lib\LittleEndian2Int(), and str_replace.
Referenced by Analyze().
static KnownGUIDs () static
Definition at line 1453 of file module.audio-video.asf.php.
Referenced by __construct().
static metadataLibraryObjectDataTypeLookup ($id) static
Definition at line 1934 of file module.audio-video.asf.php.
References $id.
static TrimConvert ($string) static
Definition at line 1999 of file module.audio-video.asf.php.
References getid3_lib\iconv_fallback().
Referenced by Analyze().
static TrimTerm ($string) static
Definition at line 2005 of file module.audio-video.asf.php.
Referenced by Analyze().
static WMpictureTypeLookup ($WMpictureType) static
Definition at line 1656 of file module.audio-video.asf.php.
References getid3_lib\iconv_fallback(), and null.
The documentation for this class was generated from the following file:
module.audio-video.asf.php