GravityView: GravityView_Edit_Entry_Test Class Reference
GravityView_Edit_Entry_Test Class Reference
editentry
Public Member Functions
_add_and_remove_caps_test ($entry, $view_user_edit_enabled)
Test Caps & Permissions always being able to edit.
test_add_template_path ()
GravityView_Edit_Entry::add_template_path
test_get_edit_link ()
GravityView_Edit_Entry::get_edit_link()
test_get_nonce_key ()
GravityView_Edit_Entry::get_nonce_key()
test_getInstance ()
GravityView_Edit_Entry::getInstance()
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Data Fields
$entry = array()
$entry_id = 0
$form = array()
$form_id = 0
$is_set_up = false
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
editentry
Definition at line 8 of file GravityView_Edit_Entry_Test.php.
Member Function Documentation
_add_and_remove_caps_test ($entry, $view_user_edit_enabled)
Test Caps & Permissions always being able to edit.
Parameters
$entry
$view_user_edit_enabled
Definition at line 280 of file GravityView_Edit_Entry_Test.php.
References GravityView_Edit_Entry\check_user_cap_edit_entry().
test_add_template_path ()
GravityView_Edit_Entry::add_template_path
Definition at line 106 of file GravityView_Edit_Entry_Test.php.
References GravityView_Edit_Entry\$file, and GravityView_Edit_Entry\getInstance().
test_get_edit_link ()
GravityView_Edit_Entry::get_edit_link()
Definition at line 42 of file GravityView_Edit_Entry_Test.php.
References GravityView_Edit_Entry\get_edit_link(), GravityView_Edit_Entry\get_nonce_key(), and GravityView_View\getInstance().
test_get_nonce_key ()
GravityView_Edit_Entry::get_nonce_key()
Definition at line 313 of file GravityView_Edit_Entry_Test.php.
References $view_id, and GravityView_Edit_Entry\get_nonce_key().
test_getInstance ()
GravityView_Edit_Entry::getInstance()
Definition at line 35 of file GravityView_Edit_Entry_Test.php.
References GravityView_Edit_Entry\getInstance().
Field Documentation
$entry = array()
Definition at line 28 of file GravityView_Edit_Entry_Test.php.
$entry_id = 0
Definition at line 23 of file GravityView_Edit_Entry_Test.php.
$form = array()
Definition at line 18 of file GravityView_Edit_Entry_Test.php.
$form_id = 0
Definition at line 13 of file GravityView_Edit_Entry_Test.php.
$is_set_up = false
Definition at line 30 of file GravityView_Edit_Entry_Test.php.
The documentation for this class was generated from the following file:
GravityView_Edit_Entry_Test.php