GravityView: Tests_REST_Server Class Reference
Tests_REST_Server Class Reference
restapi
Public Member Functions
embedded_response_callback ($request)
permission_denied ()
test_allow_header_send_only_permitted_methods ()
The "Allow" HTTP header should NOT include other methods which the user does not have access to.
test_allow_header_sent ()
An "Allow" HTTP header should be sent with a request for all available methods on that route.
test_allow_header_sent_with_multiple_methods ()
The "Allow" HTTP header should include all available methods that can be sent to a route.
test_default_param ()
test_default_param_is_overridden ()
test_envelope ()
test_error_to_response ()
test_error_to_response_to_error ()
test_error_to_response_with_status ()
test_get_index ()
test_get_namespace_index ()
test_get_namespaces ()
test_head_request_handled_by_get ()
test_json_error_with_status ()
test_link_embedding ()
test_link_embedding_error ()
test_link_embedding_params
test_link_embedding_params ()
test_link_embedding
test_link_embedding_self ()
test_link_embedding
test_link_embedding_without_links ()
Ensure embedding is a no-op without links in the data.
test_no_nocache_headers_on_unauthenticated_requests ()
test_no_zero_param ()
test_nocache_headers_on_authenticated_requests ()
test_optional_param ()
test_removing_links ()
test_removing_links_for_href ()
test_response_to_data_links ()
test_rest_error ()
test_rest_route_capability_authorization ()
An editor should be able to get access to an route with the edit_posts capability.
test_rest_route_capability_authorization_fails ()
Pass a capability which the user does not have, this should result in a 403 error.
Public Member Functions inherited from WP_UnitTestCase
__get ($name)
__isset ($name)
_create_temporary_tables ($query)
_drop_temporary_tables ($query)
_make_attachment ($upload, $parent_post_id=0)
assertDiscardWhitespace ($expected, $actual)
assertEqualFields ($object, $fields)
assertEqualSets ($expected, $actual)
assertEqualSetsWithIndex ($expected, $actual)
assertNotWPError ($actual, $message= '')
assertQueryTrue ()
Check each of the WP_Query is_* functions/properties against expected boolean value.
assertWPError ($actual, $message= '')
clean_up_global_scope ()
delete_folders ($path)
deprecated_function_run ($function)
doing_it_wrong_run ($function)
expectDeprecated ()
expectedDeprecated ()
files_in_dir ($dir)
flush_cache ()
get_wp_die_handler ($handler)
go_to ($url)
knownPluginBug ($ticket_id)
Skips the current test if there is an open plugin ticket with id $ticket_id.
knownUTBug ($ticket_id)
Skips the current test if there is an open unit tests ticket with id $ticket_id.
knownWPBug ($ticket_id)
Skips the current test if there is an open WordPress ticket with id $ticket_id.
prepareTemplate (Text_Template $template)
Define constants after including files.
remove_added_uploads ()
rmdir ($path)
scan_user_uploads ()
scandir ($dir)
set_permalink_structure ($structure= '')
Utility method that resets permalinks and flushes rewrites.
setExpectedDeprecated ($deprecated)
Declare an expected _deprecated_function() or _deprecated_argument() call from within a test.
setExpectedIncorrectUsage ($doing_it_wrong)
Declare an expected _doing_it_wrong() call from within a test.
setUp ()
start_transaction ()
tearDown ()
temp_filename ()
Returns the name of a temporary file.
unlink ($file)
wp_die_handler ($message)
Additional Inherited Members
Static Public Member Functions inherited from WP_UnitTestCase
static commit_transaction ()
Commit the queries in a transaction.
static delete_user ($user_id)
Multisite-agnostic way to delete a user from the database.
static forceTicket ($ticket)
static get_called_class ()
static setUpBeforeClass ()
static tearDownAfterClass ()
Protected Member Functions inherited from WP_Test_REST_TestCase
assertErrorResponse ($code, $response, $status=null)
assertErrorResponse ($code, $response, $status=null)
Protected Member Functions inherited from WP_UnitTestCase
_backup_hooks ()
Saves the action and filter-related globals so they can be restored later.
_microtime_to_float ($microtime)
Helper to Convert a microtime string into a float.
_restore_hooks ()
Restores the hook-related globals to their state at setUp() so that future tests aren't affected by hooks set during this last test.
assertPostConditions ()
Detect post-test failure conditions.
checkRequirements ()
reset_post_statuses ()
Unregister non-built-in post statuses.
reset_post_types ()
Unregister existing post types and register defaults.
reset_taxonomies ()
Unregister existing taxonomies and register defaults.
Static Protected Member Functions inherited from WP_UnitTestCase
static factory ()
Protected Attributes inherited from WP_UnitTestCase
$caught_deprecated = array()
$caught_doing_it_wrong = array()
$expected_deprecated = array()
$expected_doing_it_wrong = array()
Static Protected Attributes inherited from WP_UnitTestCase
static $forced_tickets = array()
static $hooks_saved = array()
static $ignore_files
Detailed Description
restapi
Definition at line 12 of file rest-server.php.
Member Function Documentation
embedded_response_callback ($request)
Definition at line 479 of file rest-server.php.
permission_denied ()
Definition at line 258 of file rest-server.php.
test_allow_header_send_only_permitted_methods ()
The "Allow" HTTP header should NOT include other methods which the user does not have access to.
Definition at line 232 of file rest-server.php.
References apply_filters().
test_allow_header_sent ()
An "Allow" HTTP header should be sent with a request for all available methods on that route.
Definition at line 179 of file rest-server.php.
References apply_filters().
test_allow_header_sent_with_multiple_methods ()
The "Allow" HTTP header should include all available methods that can be sent to a route.
Definition at line 202 of file rest-server.php.
References apply_filters().
test_default_param ()
Definition at line 55 of file rest-server.php.
test_default_param_is_overridden ()
Definition at line 73 of file rest-server.php.
test_envelope ()
Definition at line 23 of file rest-server.php.
test_error_to_response ()
Definition at line 262 of file rest-server.php.
References $message.
test_error_to_response_to_error ()
Definition at line 295 of file rest-server.php.
References $message.
test_error_to_response_with_status ()
Definition at line 279 of file rest-server.php.
References $message.
test_get_index ()
Definition at line 531 of file rest-server.php.
References WP_REST_Server\DELETABLE, and WP_REST_Server\READABLE.
test_get_namespace_index ()
Definition at line 568 of file rest-server.php.
References WP_REST_Server\DELETABLE, WP_REST_Server\READABLE, and rest_ensure_response().
test_get_namespaces ()
Definition at line 603 of file rest-server.php.
References WP_REST_Server\READABLE.
test_head_request_handled_by_get ()
Definition at line 124 of file rest-server.php.
test_json_error_with_status ()
Definition at line 327 of file rest-server.php.
References wp_json_encode().
test_link_embedding ()
Definition at line 367 of file rest-server.php.
References rest_url().
test_link_embedding_error ()
test_link_embedding_params
Definition at line 440 of file rest-server.php.
References rest_url().
test_link_embedding_params ()
test_link_embedding
Definition at line 418 of file rest-server.php.
References rest_url().
test_link_embedding_self ()
test_link_embedding
Definition at line 399 of file rest-server.php.
References rest_url().
test_link_embedding_without_links ()
Ensure embedding is a no-op without links in the data.
Definition at line 468 of file rest-server.php.
test_no_nocache_headers_on_unauthenticated_requests ()
Definition at line 637 of file rest-server.php.
References $value, and wp_get_nocache_headers().
test_no_zero_param ()
Definition at line 109 of file rest-server.php.
test_nocache_headers_on_authenticated_requests ()
Definition at line 623 of file rest-server.php.
References $value, and wp_get_nocache_headers().
test_optional_param ()
Definition at line 92 of file rest-server.php.
test_removing_links ()
Definition at line 494 of file rest-server.php.
test_removing_links_for_href ()
Definition at line 513 of file rest-server.php.
test_response_to_data_links ()
Definition at line 347 of file rest-server.php.
References $self.
test_rest_error ()
Definition at line 316 of file rest-server.php.
References wp_json_encode().
test_rest_route_capability_authorization ()
An editor should be able to get access to an route with the edit_posts capability.
Definition at line 156 of file rest-server.php.
test_rest_route_capability_authorization_fails ()
Pass a capability which the user does not have, this should result in a 403 error.
Definition at line 138 of file rest-server.php.
The documentation for this class was generated from the following file:
rest-server.php