GravityView: Framework Class Reference
Framework Class Reference
Public Member Functions
add_gk_submenu_item ()
Adds Licenses submenu to the GravityKit top-level admin menu.
ajax_get_app_data (array $payload)
AJAX request to get products and/or licenses data.
configure_ajax_routes (array $routes)
Configures AJAX routes handled by this class.
current_user_can ($permission)
Checks if the current user has a certain permission.
enqueue_assets ($page)
Enqueues UI assets.
get_framework_title ()
Returns framework title used in admin menu and the UI.
get_link_to_product_search ($product_id)
Returns link to product search in the licensing page.
init ()
Initializes the License framework.
license_manager ()
Returns License Manager class instance.
product_manager ()
Returns Product Manager class instance.
Static Public Member Functions
static get_instance ()
Returns class instance.
Data Fields
const AJAX_ROUTER = 'licenses'
const ID = 'gk_licenses'
Private Member Functions
__construct ()
Private Attributes
$_license_manager
$_permissions
$_product_manager
Static Private Attributes
static $_instance
Detailed Description
Definition at line 18 of file Licenses/Framework.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Runs Filter:
gk/foundation/licenses/permissions Modifies permissions to access Licenses functionality.
Since
1.0.0
Parameters
array $permissions Permissions.
Definition at line 51 of file Licenses/Framework.php.
References Framework\current_user_can().
Member Function Documentation
add_gk_submenu_item()
add_gk_submenu_item ()
Adds Licenses submenu to the GravityKit top-level admin menu.
Since
1.0.0
Returns
void
Definition at line 229 of file Licenses/Framework.php.
References AdminMenu\add_submenu_item(), and Framework\get_framework_title().
Referenced by Framework\init().
ajax_get_app_data()
ajax_get_app_data (array $payload)
AJAX request to get products and/or licenses data.
Since
1.0.0
Parameters
array $payload
Exceptions
Exception
Returns
array
Definition at line 174 of file Licenses/Framework.php.
References Framework\current_user_can(), ProductManager\get_instance(), and LicenseManager\get_instance().
configure_ajax_routes()
configure_ajax_routes (array $routes)
Configures AJAX routes handled by this class.
Since
1.0.0
See also
FoundationCore::process_ajax_request()
Parameters
array $routes AJAX route to class method map.
Returns
array
Definition at line 157 of file Licenses/Framework.php.
current_user_can()
current_user_can ($permission)
Checks if the current user has a certain permission.
Since
1.0.0
Returns
bool
Definition at line 317 of file Licenses/Framework.php.
Referenced by Framework\__construct(), Framework\ajax_get_app_data(), Framework\get_framework_title(), and Framework\init().
enqueue_assets()
enqueue_assets ($page)
Enqueues UI assets.
Since
1.0.0
Parameters
string $page Current page.
Exceptions
Exception
Returns
void
Definition at line 251 of file Licenses/Framework.php.
References Framework\get_framework_title(), and LicenseManager\get_instance().
get_framework_title()
get_framework_title ()
Returns framework title used in admin menu and the UI.
Since
1.0.0
Returns
string
Definition at line 208 of file Licenses/Framework.php.
References Framework\current_user_can().
Referenced by Framework\add_gk_submenu_item(), and Framework\enqueue_assets().
get_instance()
static get_instance () static
Returns class instance.
Since
1.0.0
Returns
Framework
Definition at line 98 of file Licenses/Framework.php.
Referenced by LicenseManager\activate_license(), LicenseManager\ajax_activate_license(), ProductManager\ajax_activate_product(), ProductManager\ajax_deactivate_product(), LicenseManager\ajax_get_licenses_data(), ProductManager\ajax_get_products_data(), ProductManager\ajax_install_product(), ProductManager\ajax_update_product(), LicenseManager\display_license_info_on_plugins_page(), ProductManager\update_submenu_badge_count(), and LicenseManager\update_submenu_badge_count().
get_link_to_product_search()
get_link_to_product_search ($product_id)
Returns link to product search in the licensing page.
Since
1.0.5
Parameters
string $product_id Product ID (EDD download ID).
Returns
string
Definition at line 352 of file Licenses/Framework.php.
init()
init ()
Initializes the License framework.
Since
1.0.0
Returns
void
Runs Actions:
gk/foundation/licenses/initialized Fires when the class has finished initializing.
Since
1.0.0
Parameters
$this
Definition at line 113 of file Licenses/Framework.php.
References Framework\add_gk_submenu_item(), Framework\current_user_can(), EDD\get_instance(), ProductManager\get_instance(), and LicenseManager\get_instance().
license_manager()
license_manager ()
Returns License Manager class instance.
Since
1.0.3
Returns
LicenseManager
Definition at line 339 of file Licenses/Framework.php.
References Framework\$_license_manager.
product_manager()
product_manager ()
Returns Product Manager class instance.
Since
1.0.3
Returns
ProductManager
Definition at line 328 of file Licenses/Framework.php.
References Framework\$_product_manager.
Field Documentation
$_instance
$_instance static private
Definition at line 28 of file Licenses/Framework.php.
$_license_manager
$_license_manager private
Definition at line 35 of file Licenses/Framework.php.
Referenced by Framework\license_manager().
$_permissions
$_permissions private
Definition at line 49 of file Licenses/Framework.php.
$_product_manager
$_product_manager private
Definition at line 42 of file Licenses/Framework.php.
Referenced by Framework\product_manager().
AJAX_ROUTER
const AJAX_ROUTER = 'licenses'
Definition at line 21 of file Licenses/Framework.php.
Referenced by ProductManager\init(), and LicenseManager\init().
ID
const ID = 'gk_licenses'
Definition at line 19 of file Licenses/Framework.php.
Referenced by LicenseManager\get_licenses_data(), ProductManager\get_products_data(), LicenseManager\migrate_legacy_licenses(), LicenseManager\recheck_all_licenses(), LicenseManager\save_licenses_data(), ProductManager\update_submenu_badge_count(), and LicenseManager\update_submenu_badge_count().
The documentation for this class was generated from the following file:
Licenses/Framework.php