GravityView: GravityView_Migrate Class Reference
GravityView_Migrate Class Reference
Public Member Functions
__construct ()
get_redux_license_status ($redux_settings=array())
If the settings transient wasn't set, we need to set the default status for the license.
get_redux_settings ()
Get Redux settings, if they exist.
get_search_fields ($view_id)
update_search_on_views ()
-— Migrate from old search widget to new search widget -—
update_settings ()
Private Member Functions
maybe_migrate_approved_meta ()
Convert approval meta values to enumerated values.
maybe_migrate_search_widget ()
migrate_redux_settings ()
Set app settings from prior Redux settings, if exists.
update_approved_meta ()
Convert "Approved" approval status to "1".
Detailed Description
Definition at line 15 of file class-gravityview-migrate.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 17 of file class-gravityview-migrate.php.
Member Function Documentation
get_redux_license_status()
get_redux_license_status ($redux_settings = array())
If the settings transient wasn't set, we need to set the default status for the license.
Since
1.7.4
Parameters
array $redux_settings
Returns
array
Definition at line 139 of file class-gravityview-migrate.php.
References License_Handler\get(), and GV\get().
Referenced by migrate_redux_settings().
get_redux_settings()
get_redux_settings ()
Get Redux settings, if they exist.
Since
1.7.4
Returns
array|bool
Definition at line 163 of file class-gravityview-migrate.php.
References Utils\get(), and GV\get().
Referenced by migrate_redux_settings().
get_search_fields()
get_search_fields ($view_id)
Definition at line 274 of file class-gravityview-migrate.php.
References $field, GV\$form, $form_id, $view_id, GravityView_Widget_Search\get_search_input_types(), gravityview_get_directory_fields(), gravityview_get_field(), gravityview_get_form(), and gravityview_get_form_id().
Referenced by update_search_on_views().
maybe_migrate_approved_meta()
maybe_migrate_approved_meta () private
Convert approval meta values to enumerated values.
Since
1.18
Definition at line 36 of file class-gravityview-migrate.php.
References update_approved_meta().
Referenced by update_settings().
maybe_migrate_search_widget()
maybe_migrate_search_widget () private
Since
1.7.4
Definition at line 86 of file class-gravityview-migrate.php.
References update_search_on_views().
Referenced by update_settings().
migrate_redux_settings()
migrate_redux_settings () private
Set app settings from prior Redux settings, if exists.
Since
1.7.4
Returns
mixed|void
Definition at line 103 of file class-gravityview-migrate.php.
References get_redux_license_status(), get_redux_settings(), and gravityview().
Referenced by update_settings().
update_approved_meta()
update_approved_meta () private
Convert "Approved" approval status to "1".
Since
1.18
Returns
void
Definition at line 55 of file class-gravityview-migrate.php.
References GravityView_Entry_Approval_Status\APPROVED, GravityView_Entry_Approval_Status\DISAPPROVED, and gravityview().
Referenced by maybe_migrate_approved_meta().
update_search_on_views()
update_search_on_views ()
-— Migrate from old search widget to new search widget -—
Definition at line 203 of file class-gravityview-migrate.php.
References get_search_fields(), gravityview(), GRAVITYVIEW_DIR, gravityview_get_directory_widgets(), and gravityview_set_directory_widgets().
Referenced by maybe_migrate_search_widget().
update_settings()
update_settings ()
Definition at line 21 of file class-gravityview-migrate.php.
References maybe_migrate_approved_meta(), maybe_migrate_search_widget(), and migrate_redux_settings().
The documentation for this class was generated from the following file:
class-gravityview-migrate.php