GravityView: class-gravity-api.php File Reference
class-gravity-api.php File Reference
Data Structures
class Gravity_Api
Namespaces
Gravity
API for standard Gravity Forms functionality.
Functions
gapi ()
Function Documentation
gapi ()
Definition at line 277 of file class-gravity-api.php.
References Gravity_Api\get_instance().
Referenced by GFSettings\action_delete_option_rg_gforms_key(), GFSettings\filter_pre_update_option_rg_gforms_key(), and GFSettings\settings_uninstall_page().