GravityView: EDD Class Reference
EDD Class Reference
Public Member Functions
check_for_product_updates ($transient_data, $skip_cache=false)
Checks for product updates and modifies the 'update_plugins' transient.
disable_legacy_edd_updater ()
Disables EDD updater that's included with GravityKit products.
display_product_information ($result, $action, $args)
Returns product information for display on the Plugins page.
format_product_data ($product)
Returns a product object formatted according to what WP expects in order to display changelog/store plugin update data.
init ()
Initializes the class.
Static Public Member Functions
static get_instance ()
Returns class instance.
Static Private Attributes
static $_instance
Detailed Description
Definition at line 15 of file EDD.php.
Member Function Documentation
check_for_product_updates()
check_for_product_updates ($transient_data, $skip_cache = false)
Checks for product updates and modifies the 'update_plugins' transient.
Since
1.0.0
Parameters
object $transient_data
bool $skip_cache (optional) Whether to skip cache when getting products data. Default: false.
Returns
object
Definition at line 110 of file EDD.php.
References EDD\format_product_data(), Arr\get(), and ProductManager\get_instance().
disable_legacy_edd_updater()
disable_legacy_edd_updater ()
Disables EDD updater that's included with GravityKit products.
Since
1.0.0
Returns
void
Definition at line 58 of file EDD.php.
display_product_information()
display_product_information ($result, $action, $args)
Returns product information for display on the Plugins page.
This short-circuits the WordPress.org API request by returning product information from the EDD API that we store in the database.
Since
1.0.0
Parameters
false | object | array $result Product information.
string $action Plugin Installation API action.
object $args Request arguments.
Returns
false|object|array
Definition at line 218 of file EDD.php.
References $args, EDD\format_product_data(), Arr\get(), and ProductManager\get_instance().
format_product_data()
format_product_data ($product)
Returns a product object formatted according to what WP expects in order to display changelog/store plugin update data.
Since
1.0.0
See also
ProductManager::get_products_data()
plugins_api()
Parameters
array $product Product data.
Returns
object
Definition at line 164 of file EDD.php.
References Arr\get(), and LicenseManager\get_instance().
Referenced by EDD\check_for_product_updates(), and EDD\display_product_information().
get_instance()
static get_instance () static
Returns class instance.
Since
1.0.0
Returns
EDD
Definition at line 30 of file EDD.php.
Referenced by Framework\init(), and ProductManager\update_product().
init()
init ()
Initializes the class.
Since
1.0.0
Returns
void
Definition at line 45 of file EDD.php.
Field Documentation
$_instance
$_instance static private
Definition at line 21 of file EDD.php.
The documentation for this class was generated from the following file:
EDD.php