GravityView: GravityView_FieldType Class Reference
GravityView_FieldType Class Reference
Modify option field type by extending this class.
Public Member Functions
__construct ($name='', $field=array(), $curr_value=NULL)
get_field_desc ()
Retrieve field description.
get_field_id ()
Build input id based on the name.
get_field_label ()
Retrieve field label.
get_field_left_label ()
Retrieve field left label.
get_label_class ()
Retrieve field label class.
get_tooltip ()
render_input ($override_input)
important! Override this class outputs the input html part
render_option ()
important! Override this class outputs the field option html
render_setting ($override_input=NULL)
important! Override this class if needed outputs the field setting html
show_merge_tags ()
Verify if field should have merge tags.
tooltip ($name, $css_class='', $return=false, $article=array())
Displays the tooltip.
Static Public Member Functions
static get_field_defaults ()
Returns the default details for a field option.
Protected Attributes
$field
$name
$value
Detailed Description
Modify option field type by extending this class.
Definition at line 6 of file class.field.type.php.
Constructor & Destructor Documentation
__construct()
__construct ($name = '', $field = array(), $curr_value = NULL)
Definition at line 29 of file class.field.type.php.
References $field, and $name.
Member Function Documentation
get_field_defaults()
static get_field_defaults () static
Returns the default details for a field option.
default // default option value, in case nothing is defined (
Returns
array
Definition at line 64 of file class.field.type.php.
get_field_desc()
get_field_desc ()
Retrieve field description.
Returns
string
Definition at line 209 of file class.field.type.php.
Referenced by GravityView_FieldType_checkbox\render_option(), GravityView_FieldType_radio\render_option(), GravityView_FieldType_text\render_option(), GravityView_FieldType_textarea\render_option(), GravityView_FieldType_select\render_option(), GravityView_FieldType_checkboxes\render_option(), GravityView_FieldType_multiselect\render_option(), and GravityView_FieldType_checkbox\render_setting().
get_field_id()
get_field_id ()
Build input id based on the name.
Returns
string
Definition at line 170 of file class.field.type.php.
get_field_label()
get_field_label ()
Retrieve field label.
Returns
string
Definition at line 181 of file class.field.type.php.
Referenced by GravityView_FieldType_checkbox\render_option(), GravityView_FieldType_radio\render_option(), GravityView_FieldType_checkboxes\render_option(), GravityView_FieldType_checkbox\render_setting(), and render_setting().
get_field_left_label()
get_field_left_label ()
Retrieve field left label.
Since
1.7
Returns
string
Definition at line 192 of file class.field.type.php.
Referenced by GravityView_FieldType_checkbox\render_setting().
get_label_class()
get_label_class ()
Retrieve field label class.
Returns
string
Definition at line 200 of file class.field.type.php.
get_tooltip()
get_tooltip ()
Definition at line 81 of file class.field.type.php.
References GV\get(), and tooltip().
Referenced by GravityView_FieldType_checkbox\render_option(), GravityView_FieldType_text\render_option(), GravityView_FieldType_textarea\render_option(), GravityView_FieldType_select\render_option(), GravityView_FieldType_radio\render_option(), GravityView_FieldType_checkboxes\render_option(), GravityView_FieldType_multiselect\render_option(), GravityView_FieldType_checkbox\render_setting(), and render_setting().
render_input()
render_input ($override_input)
important! Override this class outputs the input html part
Definition at line 269 of file class.field.type.php.
Referenced by render_setting().
render_option()
render_option ()
important! Override this class outputs the field option html
Definition at line 233 of file class.field.type.php.
render_setting()
render_setting ($override_input = NULL)
important! Override this class if needed outputs the field setting html
Definition at line 241 of file class.field.type.php.
References get_field_label(), get_tooltip(), and render_input().
show_merge_tags()
show_merge_tags ()
Verify if field should have merge tags.
Returns
boolean
Definition at line 218 of file class.field.type.php.
Referenced by GravityView_FieldType_number\render_input(), GravityView_FieldType_text\render_input(), and GravityView_FieldType_textarea\render_input().
tooltip()
tooltip ($name, $css_class = '', $return = false, $article = array())
Displays the tooltip.
Since
2.8.1
$__gf_tooltips
Parameters
string $name The name of the tooltip to be displayed
string $css_class Optional. The CSS class to apply toi the element. Defaults to empty string.
bool $return Optional. If the tooltip should be returned instead of output. Defaults to false (output)
array $article Optional. Details about support doc article connected to the tooltip. {
string $id Unique ID of article for Beacon API
string $url URL of support doc article
string $type Type of Beacon element to open. {
See also
https://developer.helpscout.com/beacon-2/web/javascript-api/#beaconarticle} }
Returns
string
Filters the tooltips available
Parameters
array $__gf_tooltips Array containing the available tooltips
Below this line has been modified by GravityView.
Modify the tooltip HTML before outputting
Definition at line 113 of file class.field.type.php.
References $name, and $url.
Referenced by get_tooltip().
Field Documentation
$field
$field protected
Definition at line 20 of file class.field.type.php.
Referenced by __construct().
$name
$name protected
Definition at line 13 of file class.field.type.php.
Referenced by __construct(), and tooltip().
$value
$value protected
Definition at line 27 of file class.field.type.php.
Referenced by GravityView_FieldType_radio\render_input(), GravityView_FieldType_select\render_input(), GravityView_FieldType_checkboxes\render_input(), and GravityView_FieldType_multiselect\render_input().
The documentation for this class was generated from the following file:
class.field.type.php