GravityView: Services_JSON Class Reference
Services_JSON Class Reference
Converts to and from JSON format.
Public Member Functions
__construct ($use=0)
constructs a new JSON instance
_encode ($var)
PRIVATE CODE that does the work of encodes an arbitrary variable into JSON format.
decode ($str)
decodes a JSON string into appropriate variable
encode ($var)
encodes an arbitrary variable into JSON format (and sends JSON Header)
encodeUnsafe ($var)
encodes an arbitrary variable into JSON format without JSON Header - warning - may allow XSS!!!!)
isError ($data, $code=null)
name_value ($name, $value)
array-walking function for use in generating JSON-formatted name-value pairs
reduce_string ($str)
reduce a string by removing leading and trailing comments and whitespace
Services_JSON ($use=0)
PHP4 constructor.
strlen8 ($str)
Calculates length of string in bytes.
substr8 ($string, $start, $length=false)
Returns part of a string, interpreting $start and $length as number of bytes.
utf162utf8 ($utf16)
convert a string from one UTF-16 char to one UTF-8 char
utf82utf16 ($utf8)
convert a string from one UTF-8 char to one UTF-16 char
Data Fields
$_mb_convert_encoding = false
$_mb_strlen = false
$_mb_substr = false
Detailed Description
Converts to and from JSON format.
Brief example of use:
// create a new instance of Services_JSON $json = new Services_JSON();
// convert a complexe value to JSON notation, and send it to the browser $value = array('foo', 'bar', array(1, 2, 'baz'), array(3, array(4))); $output = $json->encode($value);
print($output); // prints: ["foo","bar",[1,2,"baz"],[3,[4]]]
// accept incoming POST data, assumed to be in JSON notation $input = file_get_contents('php://input', 1000000); $value = $json->decode($input);
Definition at line 120 of file class-json.php.
Constructor & Destructor Documentation
__construct ($use = 0)
constructs a new JSON instance
Parameters
int $use object behavior flags; combine with boolean-OR
                      possible values:
                      - SERVICES_JSON_LOOSE_TYPE:  loose typing.
                              "{...}" syntax creates associative arrays
                              instead of objects in decode().
                      - SERVICES_JSON_SUPPRESS_ERRORS:  error suppression.
                              Values which can't be encoded (e.g. resources)
                              appear as NULL instead of throwing errors.
                              By default, a deeply-nested resource will
                              bubble up with an error, so all return values
                              from encode() should be checked with isError()
                      - SERVICES_JSON_USE_TO_JSON:  call toJSON when serializing objects
                              It serializes the return value from the toJSON call rather
                              than the object itself, toJSON can return associative arrays,
                              strings or numbers, if you return an object, make sure it does
                              not have a toJSON method, otherwise an error will occur.
Definition at line 143 of file class-json.php.
References _mb_strlen(), and _mb_substr().
Member Function Documentation
_encode ($var)
PRIVATE CODE that does the work of encodes an arbitrary variable into JSON format.
Parameters
mixed $var any number, boolean, string, array, or object to be encoded. see argument 1 to Services_JSON() above for array-parsing behavior. if var is a strng, note that encode() always expects it to be in ASCII or UTF-8 format!
Returns
mixed JSON string representation of input var or an error if a problem occurs public
Definition at line 298 of file class-json.php.
References isError(), SERVICES_JSON_SUPPRESS_ERRORS, SERVICES_JSON_USE_TO_JSON, strlen8(), and utf82utf16().
Referenced by encodeUnsafe(), and name_value().
decode ($str)
decodes a JSON string into appropriate variable
Parameters
string $str JSON-formatted string
Returns
mixed number, boolean, string, array, or object corresponding to given JSON input string. See argument 1 to Services_JSON() above for object-output behavior. Note that decode() always returns strings in ASCII or UTF-8 format! public
Definition at line 590 of file class-json.php.
References $i, elseif, null, reduce_string(), SERVICES_JSON_IN_ARR, SERVICES_JSON_IN_CMT, SERVICES_JSON_IN_OBJ, SERVICES_JSON_IN_STR, SERVICES_JSON_LOOSE_TYPE, strlen8(), substr8(), and utf162utf8().
encode ($var)
encodes an arbitrary variable into JSON format (and sends JSON Header)
Parameters
mixed $var any number, boolean, string, array, or object to be encoded. see argument 1 to Services_JSON() above for array-parsing behavior. if var is a strng, note that encode() always expects it to be in ASCII or UTF-8 format!
Returns
mixed JSON string representation of input var or an error if a problem occurs public
Definition at line 261 of file class-json.php.
References encodeUnsafe().
encodeUnsafe ($var)
encodes an arbitrary variable into JSON format without JSON Header - warning - may allow XSS!!!!)
Parameters
mixed $var any number, boolean, string, array, or object to be encoded. see argument 1 to Services_JSON() above for array-parsing behavior. if var is a strng, note that encode() always expects it to be in ASCII or UTF-8 format!
Returns
mixed JSON string representation of input var or an error if a problem occurs public
Definition at line 277 of file class-json.php.
References _encode().
Referenced by encode().
isError ($data, $code = null)
Definition at line 871 of file class-json.php.
References elseif.
Referenced by _encode(), and name_value().
name_value ($name, $value)
array-walking function for use in generating JSON-formatted name-value pairs
Parameters
string $name name of key to use
mixed $value reference to an array element to be encoded
Returns
string JSON-formatted name-value pair, like '"name":value' private
Definition at line 540 of file class-json.php.
References $name, $value, _encode(), and isError().
reduce_string ($str)
reduce a string by removing leading and trailing comments and whitespace
Parameters
$str string string value to strip of comments and whitespace
Returns
string string value stripped of comments and whitespace private
Definition at line 559 of file class-json.php.
Referenced by decode().
Services_JSON ($use = 0)
PHP4 constructor.
Definition at line 154 of file class-json.php.
strlen8 ($str)
Calculates length of string in bytes.
Parameters
string
Returns
integer length
Definition at line 888 of file class-json.php.
References _mb_strlen().
Referenced by _encode(), decode(), substr8(), and utf82utf16().
substr8 ($string, $start, $length = false)
Returns part of a string, interpreting $start and $length as number of bytes.
Parameters
string
integer start
integer length
Returns
integer length
Definition at line 903 of file class-json.php.
References _mb_substr(), and strlen8().
Referenced by decode().
utf162utf8 ($utf16)
convert a string from one UTF-16 char to one UTF-8 char
Normally should be handled by mb_convert_encoding, but provides a slower PHP-only method for installations that lack the multibye string extension.
Parameters
string $utf16 UTF-16 character
Returns
string UTF-8 character private
Definition at line 173 of file class-json.php.
Referenced by decode().
utf82utf16 ($utf8)
convert a string from one UTF-8 char to one UTF-16 char
Normally should be handled by mb_convert_encoding, but provides a slower PHP-only method for installations that lack the multibye string extension.
Parameters
string $utf8 UTF-8 character
Returns
string UTF-16 character private
Definition at line 217 of file class-json.php.
References strlen8().
Referenced by _encode().
Field Documentation
$_mb_convert_encoding = false
Definition at line 160 of file class-json.php.
$_mb_strlen = false
Definition at line 158 of file class-json.php.
$_mb_substr = false
Definition at line 159 of file class-json.php.
The documentation for this class was generated from the following file:
class-json.php