GravityView: Arr Class Reference
Arr Class Reference
We use Laravel's Arr class for all array helper methods.
Static Public Member Functions
static accessible ($value)
{}
static add ($array, $key, $value)
{}
static collapse ($array)
{}
static crossJoin (... $arrays)
{}
static divide ($array)
{}
static dot ($array, $prepend='')
{}
static except ($array, $keys)
{}
static exists ($array, $key)
{}
static first ($array, callable $callback=null, $default=null)
{}
static flatten ($array, $depth=INF)
{}
static forget (&$array, $keys)
{}
static get ($array, $key, $default=null)
{}
static has ($array, $keys)
{}
static isAssoc (array $array)
{}
static last ($array, callable $callback=null, $default=null)
{}
static only ($array, $keys)
{}
static pluck ($array, $value, $key=null)
{}
static prepend ($array, $value, $key=null)
{}
static pull (&$array, $key, $default=null)
{}
static random ($array, $number=null)
{}
static set (&$array, $key, $value)
{}
static shuffle ($array)
{}
static sort ($array, $callback)
{}
static sortRecursive ($array)
{}
static undot ($array)
Convert a flattened "dot" notation array into an expanded array.
static where ($array, callable $callback)
{}
static wrap ($value)
{}
Detailed Description
We use Laravel's Arr class for all array helper methods.
This is a wrapper as we may swap out the underlying class in the future, add or modify methods, etc.
Since
1.0.0
See also
https://github.com/illuminate/support/blob/5.4/Arr.php
Definition at line 20 of file Arr.php.
Member Function Documentation
accessible()
static accessible ($value) static
{}
Since
1.0.0
Definition at line 26 of file Arr.php.
References $value.
add()
static add ($array, $key, $value) static
{}
Since
1.0.0
Definition at line 35 of file Arr.php.
References $value.
collapse()
static collapse ($array) static
{}
Since
1.0.0
Definition at line 44 of file Arr.php.
crossJoin()
static crossJoin ($arrays) static
{}
Since
1.0.0
Definition at line 53 of file Arr.php.
divide()
static divide ($array) static
{}
Since
1.0.0
Definition at line 62 of file Arr.php.
dot()
static dot ($array, $prepend = '') static
{}
Since
1.0.0
Definition at line 71 of file Arr.php.
except()
static except ($array, $keys) static
{}
Since
1.0.0
Definition at line 108 of file Arr.php.
exists()
static exists ($array, $key) static
{}
Since
1.0.0
Definition at line 117 of file Arr.php.
first()
static first ($array, callable $callback = null, $default = null) static
{}
Since
1.0.0
Definition at line 126 of file Arr.php.
flatten()
static flatten ($array, $depth = INF) static
{}
Since
1.0.0
Definition at line 135 of file Arr.php.
forget()
static forget (& $array, $keys) static
{}
Since
1.0.0
Definition at line 144 of file Arr.php.
get()
static get ($array, $key, $default = null) static
{}
Since
1.0.0
Definition at line 99 of file Arr.php.
Referenced by Core\__construct(), EDD\check_for_product_updates(), Core\configure_settings(), LicenseManager\deactivate_license(), Core\display_foundation_information(), EDD\display_product_information(), EDD\format_product_data(), HelpScout\get_beacon_configuration(), TrustedLogin\get_config(), Framework\get_default_settings(), ProductManager\get_remote_products(), Framework\get_settings(), TranslationsPress_Updater\get_slug_from_locale(), LicenseManager\migrate_legacy_licenses(), GravityForms\modify_system_report(), Core\process_ajax_request(), Blocks\register_blocks(), EntryField\render(), Entry\render(), EntryLink\render(), ViewDetails\render(), View\render(), and HelpScout\should_display_beacon().
has()
static has ($array, $keys) static
{}
Since
1.0.0
Definition at line 153 of file Arr.php.
isAssoc()
static isAssoc (array $array) static
{}
Since
1.0.0
Definition at line 162 of file Arr.php.
last()
static last ($array, callable $callback = null, $default = null) static
{}
Since
1.0.0
Definition at line 171 of file Arr.php.
only()
static only ($array, $keys) static
{}
Since
1.0.0
Definition at line 180 of file Arr.php.
Referenced by LicenseManager\get_site_data().
pluck()
static pluck ($array, $value, $key = null) static
{}
Since
1.0.0
Definition at line 189 of file Arr.php.
References $value.
Referenced by Framework\enqueue_assets().
prepend()
static prepend ($array, $value, $key = null) static
{}
Since
1.0.0
Definition at line 198 of file Arr.php.
References $value.
pull()
static pull (& $array, $key, $default = null) static
{}
Since
1.0.0
Definition at line 207 of file Arr.php.
random()
static random ($array, $number = null) static
{}
Since
1.0.0
Definition at line 216 of file Arr.php.
set()
static set (& $array, $key, $value) static
{}
Since
1.0.0
Definition at line 225 of file Arr.php.
References $value.
Referenced by TrustedLogin\add_tl_key_to_helpscout_beacon(), TrustedLogin\get_config(), and Framework\get_settings().
shuffle()
static shuffle ($array) static
{}
Since
1.0.0
Definition at line 234 of file Arr.php.
sort()
static sort ($array, $callback) static
{}
Since
1.0.0
Definition at line 243 of file Arr.php.
sortRecursive()
static sortRecursive ($array) static
{}
Since
1.0.0
Definition at line 252 of file Arr.php.
undot()
static undot ($array) static
Convert a flattened "dot" notation array into an expanded array.
Since
1.0.3
Parameters
iterable $array
Returns
array
Definition at line 84 of file Arr.php.
References $value.
where()
static where ($array, callable $callback) static
{}
Since
1.0.0
Definition at line 261 of file Arr.php.
wrap()
static wrap ($value) static
{}
Since
1.0.0
Definition at line 270 of file Arr.php.
References $value.
The documentation for this class was generated from the following file:
Arr.php