GravityView: GravityView_Widget_Custom_Content Class Reference
GravityView_Widget_Custom_Content Class Reference
Widget to add custom content.
Public Member Functions
__construct ()
render_frontend ($widget_args, $content='', $context='')
Public Member Functions inherited from Widget
add_shortcode ()
Add $this->shortcode_name shortcode to output self::render_frontend()
as_configuration ()
Return an array of the old format.
assign_widget_options ($options=array(), $template='', $widget='')
Assign template specific widget options.
get_setting ($key)
Get a setting by the setting key.
get_settings ()
Get the widget settings.
get_widget_id ()
Get the Widget ID.
is_registered ()
Whether this Widget's been registered already or not.
maybe_do_shortcode ($text, $widget=null)
Do shortcode if the Widget's shortcode exists.
pre_render_frontend ()
General validations when rendering the widget.
register_widget ($widgets)
Register widget to become available in admin.
render_frontend ($widget_args, $content='', $context='')
Frontend logic.
render_shortcode ($atts, $content='', $context='')
Shortcode.
Protected Attributes
$show_on_single = false
Protected Attributes inherited from Widget
$defaults = array()
$settings = array()
$shortcode_name
$widget_description = ''
$widget_id = ''
$widget_label = ''
$widget_subtitle = ''
Additional Inherited Members
Static Public Member Functions inherited from Widget
static from_configuration ($configuration)
Create the needed widget from a configuration array.
static get_default_widget_areas ()
Default widget areas.
static registered ()
Return all registered widgets.
Data Fields inherited from Widget
$configuration
$position = ''
$UID = ''
Protected Member Functions inherited from Widget
get_default_settings ()
Define general widget settings.
Detailed Description
Widget to add custom content.
Since
1.5.4
Definition at line 10 of file class-gravityview-widget-custom-content.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 18 of file class-gravityview-widget-custom-content.php.
References Widget\$settings.
Member Function Documentation
render_frontend()
render_frontend ($widget_args, $content = '', $context = '')
Definition at line 48 of file class-gravityview-widget-custom-content.php.
References $class, $content, gravityview(), Widget\pre_render_frontend(), and GravityView_Merge_Tags\replace_variables().
Field Documentation
$show_on_single
$show_on_single = false protected
Definition at line 16 of file class-gravityview-widget-custom-content.php.
The documentation for this class was generated from the following file:
class-gravityview-widget-custom-content.php