GravityView: PHPMailer Class Reference
PHPMailer Class Reference
Public Member Functions
__construct ($exceptions=false)
Constructor.
__destruct ()
Destructor.
addAddress ($address, $name= '')
Add a "To" address.
addAttachment ($path, $name= '', $encoding= 'base64', $type= '', $disposition= 'attachment')
Add an attachment from a path on the filesystem.
addBCC ($address, $name= '')
Add a "BCC" address.
addCC ($address, $name= '')
Add a "CC" address.
addCustomHeader ($name, $value=null)
Add a custom header.
addEmbeddedImage ($path, $cid, $name= '', $encoding= 'base64', $type= '', $disposition= 'inline')
Add an embedded (inline) attachment from a file.
addrAppend ($type, $addr)
Create recipient headers.
addReplyTo ($address, $name= '')
Add a "Reply-To" address.
addrFormat ($addr)
Format an address for use in a message header.
addStringAttachment ($string, $filename, $encoding= 'base64', $type= '', $disposition= 'attachment')
Add a string or binary attachment (non-filesystem).
addStringEmbeddedImage ($string, $cid, $name= '', $encoding= 'base64', $type= '', $disposition= 'inline')
Add an embedded stringified attachment.
alternativeExists ()
Check if this message has an alternative body set.
attachmentExists ()
Check if an attachment (non-inline) is present.
base64EncodeWrapMB ($str, $linebreak=null)
Encode and wrap long multibyte strings for mail headers without breaking lines within a character.
clearAddresses ()
Clear all To recipients.
clearAllRecipients ()
Clear all recipient types.
clearAttachments ()
Clear all filesystem, string, and binary attachments.
clearBCCs ()
Clear all BCC recipients.
clearCCs ()
Clear all CC recipients.
clearCustomHeaders ()
Clear all custom headers.
clearQueuedAddresses ($kind)
Clear queued addresses of given kind.
clearReplyTos ()
Clear all ReplyTo recipients.
createBody ()
Assemble the message body.
createHeader ()
Assemble message headers.
DKIM_Add ($headers_line, $subject, $body)
Create the DKIM header and body in a new message header.
DKIM_BodyC ($body)
Generate a DKIM canonicalization body.
DKIM_HeaderC ($signHeader)
Generate a DKIM canonicalization header.
DKIM_QP ($txt)
Quoted-Printable-encode a DKIM header.
DKIM_Sign ($signHeader)
Generate a DKIM signature.
encodeHeader ($str, $position= 'text')
Encode a header string optimally.
encodeQ ($str, $position= 'text')
Encode a string using Q encoding.
encodeQP ($string, $line_max=76)
Encode a string in quoted-printable format.
encodeQPphp ($string, $line_max=76, $space_conv=false)
Backward compatibility wrapper for an old QP encoding function that was removed.
encodeString ($str, $encoding= 'base64')
Encode a string in requested format.
fixEOL ($str)
Ensure consistent line endings in a string.
getAllRecipientAddresses ()
Allows for public read access to 'all_recipients' property.
getAttachments ()
Return the array of attachments.
getBccAddresses ()
Allows for public read access to 'bcc' property.
getCcAddresses ()
Allows for public read access to 'cc' property.
getCustomHeaders ()
Returns all custom headers.
getLastMessageID ()
Return the Message-ID header of the last email.
getMailMIME ()
Get the message MIME type headers.
getReplyToAddresses ()
Allows for public read access to 'ReplyTo' property.
getSentMIMEMessage ()
Returns the whole MIME message.
getSMTPInstance ()
Get an instance to use for SMTP operations.
getToAddresses ()
Allows for public read access to 'to' property.
getTranslations ()
Get the array of strings for the current language.
has8bitChars ($text)
Does a string contain any 8-bit chars (in any charset)?
hasMultiBytes ($str)
Check if a string contains multi-byte characters.
headerLine ($name, $value)
Format a header line.
html2text ($html, $advanced=false)
Convert an HTML string into plain text.
idnSupported ()
Tells whether IDNs (Internationalized Domain Names) are supported or not.
inlineImageExists ()
Check if an inline attachment is present.
isError ()
Check if an error occurred.
isHTML ($isHtml=true)
Sets message type to HTML or plain.
isMail ()
Send messages using PHP's mail() function.
isQmail ()
Send messages using qmail.
isSendmail ()
Send messages using $Sendmail.
isSMTP ()
Send messages using SMTP.
msgHTML ($message, $basedir= '', $advanced=false)
Create a message from an HTML string.
postSend ()
Actually send a message.
preSend ()
Prepare a message for sending.
punyencodeAddress ($address)
Converts IDN in given email address to its ASCII form, also known as punycode, if possible.
secureHeader ($str)
Strip newlines to prevent header injection.
send ()
Create a message and send it.
set ($name, $value= '')
Set or reset instance properties.
setFrom ($address, $name= '', $auto=true)
Set the From and FromName properties.
setLanguage ($langcode= 'en', $lang_path= '')
Set the language for error messages.
setWordWrap ()
Apply word wrapping to the message body.
sign ($cert_filename, $key_filename, $key_pass, $extracerts_filename= '')
Set the public and private key files and password for S/MIME signing.
smtpClose ()
Close the active SMTP session if one exists.
smtpConnect ($options=array())
Initiate a connection to an SMTP server.
textLine ($value)
Return a formatted mail line.
utf8CharBoundary ($encodedText, $maxLength)
Find the last character boundary prior to $maxLength in a utf-8 quoted-printable encoded string.
wrapText ($message, $length, $qp_mode=false)
Word-wrap message.
Static Public Member Functions
static _mime_types ($ext= '')
Get the MIME type for a file extension.
static filenameToType ($filename)
Map a file name to a MIME type.
static hasLineLongerThanMax ($str)
Detect if a string contains a line longer than the maximum line length allowed.
static mb_pathinfo ($path, $options=null)
Multi-byte-safe pathinfo replacement.
static normalizeBreaks ($text, $breaktype="\r\n")
Normalize line breaks in a string.
static rfcDate ()
Return an RFC 822 formatted date.
static validateAddress ($address, $patternselect= 'auto')
Check that a string looks like an email address.
Data Fields
$action_function = ''
$AllowEmpty = false
$AltBody = ''
$AuthType = ''
$Body = ''
$CharSet = 'iso-8859-1'
$ConfirmReadingTo = ''
$ContentType = 'text/plain'
$Debugoutput = 'echo'
$DKIM_domain = ''
$DKIM_identity = ''
$DKIM_passphrase = ''
$DKIM_private = ''
$DKIM_selector = ''
$do_verp = false
$Encoding = '8bit'
$ErrorInfo = ''
$From = 'root@localhost'
$FromName = 'Root User'
$Helo = ''
$Host = 'localhost'
$Hostname = ''
$Ical = ''
$LE = "\n"
$Mailer = 'mail'
$MessageDate = ''
$MessageID = ''
$Password = ''
$PluginDir = ''
$Port = 25
$Priority = null
$Realm = ''
$ReturnPath = ''
$Sender = ''
$Sendmail = '/usr/sbin/sendmail'
$SingleTo = false
$SingleToArray = array()
$SMTPAuth = false
$SMTPAutoTLS = true
$SMTPDebug = 0
$SMTPKeepAlive = false
$SMTPOptions = array()
$SMTPSecure = ''
$Subject = ''
$Timeout = 300
$Username = ''
$UseSendmailOptions = true
$Version = '5.2.14'
$WordWrap = 0
$Workstation = ''
$XMailer = ''
const CRLF = "\r\n"
SMTP RFC standard line ending.
const MAX_LINE_LENGTH = 998
const STOP_CONTINUE = 1
Error severity: message, likely ok to continue processing.
const STOP_CRITICAL = 2
Error severity: message, plus full stop, critical error reached.
const STOP_MESSAGE = 0
Error severity: message only, continue processing.
Protected Member Functions
addAnAddress ($kind, $address, $name= '')
Add an address to one of the recipient arrays or to the ReplyTo array.
addOrEnqueueAnAddress ($kind, $address, $name)
Add an address to one of the recipient arrays or to the ReplyTo array.
attachAll ($disposition_type, $boundary)
Attach all file, string, and binary attachments to the message.
doCallback ($isSent, $to, $cc, $bcc, $subject, $body, $from)
Perform a callback.
edebug ($str)
Output debugging info via user-defined method.
encodeFile ($path, $encoding= 'base64')
Encode a file attachment in requested format.
endBoundary ($boundary)
Return the end of a message boundary.
getBoundary ($boundary, $charSet, $contentType, $encoding)
Return the start of a message boundary.
lang ($key)
Get an error message in the current language.
mailSend ($header, $body)
Send mail using the PHP mail() function.
sendmailSend ($header, $body)
Send mail using the $Sendmail program.
serverHostname ()
Get the server hostname.
setError ($msg)
Add an error message to the error container.
setMessageType ()
Set the message type.
smtpSend ($header, $body)
Send mail via SMTP.
Protected Attributes
$all_recipients = array()
$attachment = array()
$bcc = array()
$boundary = array()
$cc = array()
$CustomHeader = array()
$error_count = 0
$exceptions = false
$language = array()
$lastMessageID = ''
$mailHeader = ''
$message_type = ''
$MIMEBody = ''
$MIMEHeader = ''
$RecipientsQueue = array()
$ReplyTo = array()
$ReplyToQueue = array()
$sign_cert_file = ''
$sign_extracerts_file = ''
$sign_key_file = ''
$sign_key_pass = ''
$smtp = null
$to = array()
$uniqueid = ''
Private Member Functions
mailPassthru ($to, $subject, $body, $header, $params)
Call mail() in a safe_mode-aware fashion.
Detailed Description
Definition at line 28 of file class-phpmailer.php.
Constructor & Destructor Documentation
__construct ($exceptions = false)
Constructor.
Parameters
boolean $exceptions Should we throw external exceptions?
Definition at line 637 of file class-phpmailer.php.
References $exceptions.
__destruct ()
Destructor.
Definition at line 645 of file class-phpmailer.php.
References smtpClose().
Member Function Documentation
static _mime_types ($ext = '') static
Get the MIME type for a file extension.
Parameters
string $ext File extension public
Returns
string MIME type of file.
Definition at line 3326 of file class-phpmailer.php.
addAddress ($address, $name = '')
Add a "To" address.
Parameters
string $address The email address to send to
string $name
Returns
boolean true on success, false if address already used or invalid in some way
Definition at line 795 of file class-phpmailer.php.
References $name, and addOrEnqueueAnAddress().
addAnAddress ($kind, $address, $name = '') protected
Add an address to one of the recipient arrays or to the ReplyTo array.
Addresses that have been added already return false, but do not throw exceptions.
Parameters
string $kind One of 'to', 'cc', 'bcc', or 'ReplyTo'
string $address The email address to send, resp. to reply to
string $name
Exceptions
phpmailerException
Returns
boolean true on success, false if address already used or invalid in some way protected
Definition at line 891 of file class-phpmailer.php.
References $name, edebug(), lang(), setError(), and validateAddress().
addAttachment ($path, $name = '', $encoding = 'base64', $type = '', $disposition = 'attachment')
Add an attachment from a path on the filesystem.
Returns false if the file could not be found or read.
Parameters
string $path Path to the attachment.
string $name Overrides the attachment name.
string $encoding File encoding (see $Encoding).
string $type File extension (MIME) type.
string $disposition Disposition to use
Exceptions
phpmailerException
Returns
boolean
Definition at line 2336 of file class-phpmailer.php.
References $name, $path, edebug(), lang(), and setError().
addBCC ($address, $name = '')
Add a "BCC" address.
Note
: This function works with the SMTP mailer on win32, not with the "mail" mailer.
Parameters
string $address The email address to send to
string $name
Returns
boolean true on success, false if address already used or invalid in some way
Definition at line 819 of file class-phpmailer.php.
References $name, and addOrEnqueueAnAddress().
addCC ($address, $name = '')
Add a "CC" address.
Note
: This function works with the SMTP mailer on win32, not with the "mail" mailer.
Parameters
string $address The email address to send to
string $name
Returns
boolean true on success, false if address already used or invalid in some way
Definition at line 807 of file class-phpmailer.php.
References $name, and addOrEnqueueAnAddress().
addCustomHeader ($name, $value = null)
Add a custom header.
$name value can be overloaded to contain both header name and value (name:value) public
Parameters
string $name Custom header name
string $value Header value
Returns
void
Definition at line 3192 of file class-phpmailer.php.
References $name, $value, and null.
addEmbeddedImage ($path, $cid, $name = '', $encoding = 'base64', $type = '', $disposition = 'inline')
Add an embedded (inline) attachment from a file.
This can include images, sounds, and just about any other document type. These differ from 'regular' attachments in that they are intended to be displayed inline with the message, not just attached for download. This is used in HTML messages that embed the images the HTML refers to using the $cid value.
Parameters
string $path Path to the attachment.
string $cid Content ID of the attachment; Use this to reference the content when using an embedded image in HTML.
string $name Overrides the attachment name.
string $encoding File encoding (see $Encoding).
string $type File MIME type.
string $disposition Disposition to use
Returns
boolean True on successfully adding an attachment
Definition at line 2861 of file class-phpmailer.php.
References $name, $path, lang(), and setError().
Referenced by msgHTML().
addOrEnqueueAnAddress ($kind, $address, $name) protected
Add an address to one of the recipient arrays or to the ReplyTo array.
Because PHPMailer can't validate addresses with an IDN without knowing the PHPMailer::$CharSet (that can still be modified after calling this function), addition of such addresses is delayed until send(). Addresses that have been added already return false, but do not throw exceptions.
Parameters
string $kind One of 'to', 'cc', 'bcc', or 'ReplyTo'
string $address The email address to send, resp. to reply to
string $name
Exceptions
phpmailerException
Returns
boolean true on success, false if address already used or invalid in some way protected
Definition at line 847 of file class-phpmailer.php.
References $name, edebug(), has8bitChars(), idnSupported(), lang(), and setError().
Referenced by addAddress(), addBCC(), addCC(), and addReplyTo().
addrAppend ($type, $addr)
Create recipient headers.
public
Parameters
string $type
array $addr An array of recipient, where each recipient is a 2-element indexed array with element 0 containing an address and element 1 containing a name, like: array(array('joe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Joe User'), array('zoe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Zoe User'))
Returns
string
Definition at line 1664 of file class-phpmailer.php.
References $LE, and addrFormat().
Referenced by createHeader(), and preSend().
addReplyTo ($address, $name = '')
Add a "Reply-To" address.
Parameters
string $address The email address to reply to
string $name
Returns
boolean true on success, false if address already used or invalid in some way
Definition at line 830 of file class-phpmailer.php.
References $name, and addOrEnqueueAnAddress().
addrFormat ($addr)
Format an address for use in a message header.
public
Parameters
array $addr A 2-element indexed array, element 0 containing an address, element 1 containing a name like array('joe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Joe User')
Returns
string
Definition at line 1680 of file class-phpmailer.php.
References encodeHeader(), and secureHeader().
Referenced by addrAppend(), createHeader(), and mailSend().
addStringAttachment ($string, $filename, $encoding = 'base64', $type = '', $disposition = 'attachment')
Add a string or binary attachment (non-filesystem).
This method can be used to attach ascii or binary data, such as a BLOB record from a database.
Parameters
string $string String attachment data.
string $filename Name of the attachment.
string $encoding File encoding (see $Encoding).
string $type File extension (MIME) type.
string $disposition Disposition to use
Returns
void
Definition at line 2821 of file class-phpmailer.php.
addStringEmbeddedImage ($string, $cid, $name = '', $encoding = 'base64', $type = '', $disposition = 'inline')
Add an embedded stringified attachment.
This can include images, sounds, and just about any other document type. Be sure to set the $type to an image type for images: JPEG images use 'image/jpeg', GIF uses 'image/gif', PNG uses 'image/png'.
Parameters
string $string The attachment binary data.
string $cid Content ID of the attachment; Use this to reference the content when using an embedded image in HTML.
string $name
string $encoding File encoding (see $Encoding).
string $type MIME type.
string $disposition Disposition to use
Returns
boolean True on successfully adding an attachment
Definition at line 2906 of file class-phpmailer.php.
References $name.
Referenced by msgHTML().
alternativeExists ()
Check if this message has an alternative body set.
Returns
boolean
Definition at line 2966 of file class-phpmailer.php.
Referenced by setMessageType().
attachAll ($disposition_type, $boundary) protected
Attach all file, string, and binary attachments to the message.
Returns an empty string on failure. protected
Parameters
string $disposition_type
string $boundary
Returns
string
Definition at line 2392 of file class-phpmailer.php.
References $attachment, $boundary, $LE, $mime, $name, $path, encodeFile(), encodeHeader(), encodeString(), isError(), and secureHeader().
Referenced by createBody().
attachmentExists ()
Check if an attachment (non-inline) is present.
Returns
boolean
Definition at line 2952 of file class-phpmailer.php.
References $attachment.
Referenced by setMessageType().
base64EncodeWrapMB ($str, $linebreak = null)
Encode and wrap long multibyte strings for mail headers without breaking lines within a character.
Adapted from a function by paravoid public string $str multi-byte text to wrap encode string $linebreak string to use as linefeed/end-of-line string
Definition at line 2687 of file class-phpmailer.php.
References $i, $LE, and null.
Referenced by encodeHeader().
clearAddresses ()
Clear all To recipients.
Returns
void
Definition at line 2991 of file class-phpmailer.php.
References $to, and clearQueuedAddresses().
clearAllRecipients ()
Clear all recipient types.
Returns
void
Definition at line 3040 of file class-phpmailer.php.
clearAttachments ()
Clear all filesystem, string, and binary attachments.
Returns
void
Definition at line 3053 of file class-phpmailer.php.
clearBCCs ()
Clear all BCC recipients.
Returns
void
Definition at line 3017 of file class-phpmailer.php.
References $bcc, and clearQueuedAddresses().
clearCCs ()
Clear all CC recipients.
Returns
void
Definition at line 3004 of file class-phpmailer.php.
References $cc, and clearQueuedAddresses().
clearCustomHeaders ()
Clear all custom headers.
Returns
void
Definition at line 3062 of file class-phpmailer.php.
clearQueuedAddresses ($kind)
Clear queued addresses of given kind.
protected
Parameters
string $kind 'to', 'cc', or 'bcc'
Returns
void
Definition at line 2977 of file class-phpmailer.php.
References $RecipientsQueue.
Referenced by clearAddresses(), clearBCCs(), and clearCCs().
clearReplyTos ()
Clear all ReplyTo recipients.
Returns
void
Definition at line 3030 of file class-phpmailer.php.
createBody ()
Assemble the message body.
Returns an empty string on failure. public
Exceptions
phpmailerException
Returns
string The assembled message body
Definition at line 2033 of file class-phpmailer.php.
References $CharSet, $Encoding, $file, $LE, $uniqueid, attachAll(), elseif, encodeString(), endBoundary(), getBoundary(), getMailMIME(), has8bitChars(), headerLine(), isError(), lang(), null, setWordWrap(), and textLine().
Referenced by preSend().
createHeader ()
Assemble message headers.
public
Returns
string The assembled headers
Definition at line 1870 of file class-phpmailer.php.
References $MessageID, addrAppend(), addrFormat(), elseif, encodeHeader(), getMailMIME(), headerLine(), secureHeader(), and serverHostname().
Referenced by preSend().
DKIM_Add ($headers_line, $subject, $body)
Create the DKIM header and body in a new message header.
public
Parameters
string $headers_line Header lines
string $subject Subject
string $body Body
Returns
string
Definition at line 3662 of file class-phpmailer.php.
References $from, $to, DKIM_BodyC(), DKIM_HeaderC(), DKIM_QP(), DKIM_Sign(), elseif, and str_replace.
Referenced by preSend().
DKIM_BodyC ($body)
Generate a DKIM canonicalization body.
public
Parameters
string $body Message Body
Returns
string
Definition at line 3639 of file class-phpmailer.php.
References str_replace.
Referenced by DKIM_Add().
DKIM_HeaderC ($signHeader)
Generate a DKIM canonicalization header.
public
Parameters
string $signHeader Header
Returns
string
Definition at line 3619 of file class-phpmailer.php.
References $value.
Referenced by DKIM_Add().
DKIM_QP ($txt)
Quoted-Printable-encode a DKIM header.
public
Parameters
string $txt
Returns
string
Definition at line 3572 of file class-phpmailer.php.
References $i.
Referenced by DKIM_Add().
DKIM_Sign ($signHeader)
Generate a DKIM signature.
public
Parameters
string $signHeader
Exceptions
phpmailerException
Returns
string
Definition at line 3593 of file class-phpmailer.php.
References lang().
Referenced by DKIM_Add().
doCallback ($isSent, $to, $cc, $bcc, $subject, $body, $from) protected
Perform a callback.
Parameters
boolean $isSent
array $to
array $cc
array $bcc
string $subject
string $body
string $from
Definition at line 3804 of file class-phpmailer.php.
References $bcc, $cc, $from, and $to.
Referenced by mailSend(), sendmailSend(), and smtpSend().
edebug ($str) protected
Output debugging info via user-defined method.
Only generates output if SMTP debug output is enabled (
See also
SMTP::$do_debug).
PHPMailer::$Debugoutput
PHPMailer::$SMTPDebug
Parameters
string $str
Definition at line 689 of file class-phpmailer.php.
References str_replace.
Referenced by addAnAddress(), addAttachment(), addOrEnqueueAnAddress(), postSend(), preSend(), setFrom(), and smtpConnect().
encodeFile ($path, $encoding = 'base64') protected
Encode a file attachment in requested format.
Returns an empty string on failure.
Parameters
string $path The full path to the file
string $encoding The encoding to use; one of 'base64', '7bit', '8bit', 'binary', 'quoted-printable'
Exceptions
phpmailerException protected
Returns
string
Definition at line 2517 of file class-phpmailer.php.
References $path, encodeString(), lang(), and setError().
Referenced by attachAll().
encodeHeader ($str, $position = 'text')
Encode a header string optimally.
Picks shortest of Q, B, quoted-printable or none. public
Parameters
string $str
string $position
Returns
string
PhpMissingBreakStatementInspection
Definition at line 2594 of file class-phpmailer.php.
References base64EncodeWrapMB(), encodeQ(), hasMultiBytes(), str_replace, and wrapText().
Referenced by addrFormat(), attachAll(), createHeader(), mailPassthru(), and preSend().
encodeQ ($str, $position = 'text')
Encode a string using Q encoding.
string $str the text to encode string $position Where the text is going to be used, see the RFC for what that means public string
PhpMissingBreakStatementInspection
Definition at line 2770 of file class-phpmailer.php.
References str_replace.
Referenced by encodeHeader().
encodeQP ($string, $line_max = 76)
Encode a string in quoted-printable format.
According to RFC2045 section 6.7. public
Parameters
string $string The text to encode
integer $line_max Number of chars allowed on a line before wrapping
Returns
string Adapted from this comment
Definition at line 2729 of file class-phpmailer.php.
References str_replace.
Referenced by encodeQPphp(), and encodeString().
encodeQPphp ($string, $line_max = 76, $space_conv = false)
Backward compatibility wrapper for an old QP encoding function that was removed.
See also
PHPMailer::encodeQP() public
Parameters
string $string
integer $line_max
boolean $space_conv
Returns
string
Parameters
$space_conv PhpUnusedParameterInspection
Definition at line 2754 of file class-phpmailer.php.
References encodeQP().
encodeString ($str, $encoding = 'base64')
Encode a string in requested format.
Returns an empty string on failure.
Parameters
string $str The text to encode
string $encoding The encoding to use; one of 'base64', '7bit', '8bit', 'binary', 'quoted-printable' public
Returns
string
Definition at line 2558 of file class-phpmailer.php.
References $LE, encodeQP(), fixEOL(), lang(), and setError().
Referenced by attachAll(), createBody(), and encodeFile().
endBoundary ($boundary) protected
Return the end of a message boundary.
protected
Parameters
string $boundary
Returns
string
Definition at line 2272 of file class-phpmailer.php.
References $boundary, and $LE.
Referenced by createBody().
static filenameToType ($filename) static
Map a file name to a MIME type.
Defaults to 'application/octet-stream', i.e.. arbitrary binary data.
Parameters
string $filename A file name or full path, does not need to exist as a file
Returns
string
Definition at line 3441 of file class-phpmailer.php.
fixEOL ($str)
Ensure consistent line endings in a string.
Changes every end of line from CRLF, CR or LF to $this->LE. public
Parameters
string $str String to fixEOL
Returns
string
Definition at line 3172 of file class-phpmailer.php.
References str_replace.
Referenced by encodeString(), and wrapText().
getAllRecipientAddresses ()
Allows for public read access to 'all_recipients' property.
Note
: Before the send() call, queued addresses (i.e. with IDN) are not yet included. public
Returns
array
Definition at line 3789 of file class-phpmailer.php.
References $all_recipients.
getAttachments ()
Return the array of attachments.
Returns
array
Definition at line 2379 of file class-phpmailer.php.
References $attachment.
getBccAddresses ()
Allows for public read access to 'bcc' property.
Note
: Before the send() call, queued addresses (i.e. with IDN) are not yet included. public
Returns
array
Definition at line 3767 of file class-phpmailer.php.
References $bcc.
getBoundary ($boundary, $charSet, $contentType, $encoding) protected
Return the start of a message boundary.
protected
Parameters
string $boundary
string $charSet
string $contentType
string $encoding
Returns
string
Definition at line 2242 of file class-phpmailer.php.
References $boundary, $CharSet, $ContentType, $Encoding, $LE, headerLine(), and textLine().
Referenced by createBody().
getCcAddresses ()
Allows for public read access to 'cc' property.
Note
: Before the send() call, queued addresses (i.e. with IDN) are not yet included. public
Returns
array
Definition at line 3756 of file class-phpmailer.php.
References $cc.
getCustomHeaders ()
Returns all custom headers.
Returns
array
Definition at line 3206 of file class-phpmailer.php.
References $CustomHeader.
getLastMessageID ()
Return the Message-ID header of the last email.
Technically this is the value from the last time the headers were created, but it's also the message ID of the last sent message except in pathological cases.
Returns
string
Definition at line 967 of file class-phpmailer.php.
References $lastMessageID.
getMailMIME ()
Get the message MIME type headers.
public
Returns
string
Definition at line 1966 of file class-phpmailer.php.
References $LE, headerLine(), and textLine().
Referenced by createBody(), and createHeader().
getReplyToAddresses ()
Allows for public read access to 'ReplyTo' property.
Note
: Before the send() call, queued addresses (i.e. with IDN) are not yet included. public
Returns
array
Definition at line 3778 of file class-phpmailer.php.
References $ReplyTo.
getSentMIMEMessage ()
Returns the whole MIME message.
Includes complete headers and body. Only valid post preSend().
See also
PHPMailer::preSend() public
Returns
string
Definition at line 2021 of file class-phpmailer.php.
References $MIMEBody.
getSMTPInstance ()
Get an instance to use for SMTP operations.
Override this function to load your own SMTP implementation
Returns
SMTP
Definition at line 1385 of file class-phpmailer.php.
References $smtp.
Referenced by smtpConnect().
getToAddresses ()
Allows for public read access to 'to' property.
Note
: Before the send() call, queued addresses (i.e. with IDN) are not yet included. public
Returns
array
Definition at line 3745 of file class-phpmailer.php.
References $to.
getTranslations ()
Get the array of strings for the current language.
Returns
array
Definition at line 1649 of file class-phpmailer.php.
References $language.
has8bitChars ($text)
Does a string contain any 8-bit chars (in any charset)?
Parameters
string $text
Returns
boolean
Definition at line 2672 of file class-phpmailer.php.
References $text.
Referenced by addOrEnqueueAnAddress(), createBody(), punyencodeAddress(), and setFrom().
static hasLineLongerThanMax ($str) static
Detect if a string contains a line longer than the maximum line length allowed.
Parameters
string $str
Returns
boolean
Definition at line 3733 of file class-phpmailer.php.
hasMultiBytes ($str)
Check if a string contains multi-byte characters.
public
Parameters
string $str multi-byte text to wrap encode
Returns
boolean
Definition at line 2658 of file class-phpmailer.php.
Referenced by encodeHeader().
headerLine ($name, $value)
Format a header line.
public
Parameters
string $name
string $value
Returns
string
Definition at line 2309 of file class-phpmailer.php.
References $LE, $name, and $value.
Referenced by createBody(), createHeader(), getBoundary(), getMailMIME(), and preSend().
html2text ($html, $advanced = false)
Convert an HTML string into plain text.
This is used by msgHTML(). Note - older versions of this function used a bundled advanced converter which was been removed for license reasons in #232 Example usage: // Use default conversion $plain = $mail->html2text($html); // Use your own custom converter $plain = $mail->html2text($html, function($html) { $converter = new MyHtml2text($html); return $converter->get_text(); });
Parameters
string $html The HTML text to convert
boolean | callable $advanced Any boolean value to use the internal converter, or provide your own callable for custom conversion.
Returns
string
Definition at line 3307 of file class-phpmailer.php.
Referenced by msgHTML().
idnSupported ()
Tells whether IDNs (Internationalized Domain Names) are supported or not.
This requires the "intl" and "mbstring" PHP extensions.
Returns
bool "true" if required functions for IDN support are present
Definition at line 1076 of file class-phpmailer.php.
Referenced by addOrEnqueueAnAddress(), punyencodeAddress(), and setFrom().
inlineImageExists ()
Check if an inline attachment is present.
public
Returns
boolean
Definition at line 2938 of file class-phpmailer.php.
References $attachment.
Referenced by setMessageType().
isError ()
Check if an error occurred.
public
Returns
boolean True if an error did occur.
Definition at line 3160 of file class-phpmailer.php.
Referenced by attachAll(), and createBody().
isHTML ($isHtml = true)
Sets message type to HTML or plain.
Parameters
boolean $isHtml True for HTML mode.
Returns
void
Definition at line 730 of file class-phpmailer.php.
Referenced by msgHTML().
isMail ()
Send messages using PHP's mail() function.
Returns
void
Definition at line 752 of file class-phpmailer.php.
isQmail ()
Send messages using qmail.
Returns
void
Definition at line 777 of file class-phpmailer.php.
isSendmail ()
Send messages using $Sendmail.
Returns
void
Definition at line 761 of file class-phpmailer.php.
isSMTP ()
Send messages using SMTP.
Returns
void
Definition at line 743 of file class-phpmailer.php.
lang ($key) protected
Get an error message in the current language.
protected
Parameters
string $key
Returns
string
Definition at line 3135 of file class-phpmailer.php.
References setLanguage().
Referenced by addAnAddress(), addAttachment(), addEmbeddedImage(), addOrEnqueueAnAddress(), createBody(), DKIM_Sign(), encodeFile(), encodeString(), mailSend(), preSend(), sendmailSend(), set(), setError(), setFrom(), smtpConnect(), and smtpSend().
mailPassthru ($to, $subject, $body, $header, $params) private
Call mail() in a safe_mode-aware fashion.
Also, unless sendmail_path points to sendmail (or something that claims to be sendmail), don't pass params (not a perfect fix, but it will do)
Parameters
string $to To
string $subject Subject
string $body Message Body
string $header Additional Header(s)
string $params Params private
Returns
boolean
Definition at line 666 of file class-phpmailer.php.
References $to, encodeHeader(), and secureHeader().
Referenced by mailSend().
mailSend ($header, $body) protected
Send mail using the PHP mail() function.
Parameters
string $header The message headers
string $body The message body phpmailerException protected boolean
Definition at line 1344 of file class-phpmailer.php.
References $to, addrFormat(), doCallback(), lang(), and mailPassthru().
Referenced by postSend().
static mb_pathinfo ($path, $options = null) static
Multi-byte-safe pathinfo replacement.
Drop-in replacement for pathinfo(), but multibyte-safe, cross-platform-safe, old-version-safe. Works similarly to the one in PHP >= 5.2.0 string $path A filename or path, does not need to exist as a file integer|string $options Either a PATHINFO_* constant, or a string name to return only the specified piece, allows 'filename' to work on PHP < 5.2 string|array
Definition at line 3463 of file class-phpmailer.php.
References $options, and $path.
msgHTML ($message, $basedir = '', $advanced = false)
Create a message from an HTML string.
Automatically makes modifications for inline images and backgrounds and creates a plain-text version by converting the HTML. Overwrites any existing values in $this->Body and $this->AltBody public
Parameters
string $message HTML message string
string $basedir baseline directory for path
boolean | callable $advanced Whether to use the internal HTML to text converter or your own custom converter
See also
PHPMailer::html2text()
Returns
string $message
Definition at line 3223 of file class-phpmailer.php.
References $Body, $message, $url, addEmbeddedImage(), addStringEmbeddedImage(), elseif, html2text(), isHTML(), normalizeBreaks(), and str_replace.
static normalizeBreaks ($text, $breaktype = "\r\n") static
Normalize line breaks in a string.
Converts UNIX LF, Mac CR and Windows CRLF line breaks into a single line break format. Defaults to CRLF (for message bodies) and preserves consecutive breaks.
Parameters
string $text
string $breaktype What kind of line break to use, defaults to CRLF
Returns
string public
Definition at line 3545 of file class-phpmailer.php.
References $text.
Referenced by msgHTML().
postSend ()
Actually send a message.
Send the email via the selected mechanism
Exceptions
phpmailerException
Returns
boolean
Definition at line 1236 of file class-phpmailer.php.
References edebug(), mailSend(), sendmailSend(), setError(), and smtpSend().
Referenced by send().
preSend ()
Prepare a message for sending.
Exceptions
phpmailerException
Returns
boolean
Definition at line 1141 of file class-phpmailer.php.
References $MIMEHeader, addrAppend(), createBody(), createHeader(), DKIM_Add(), edebug(), encodeHeader(), headerLine(), lang(), punyencodeAddress(), secureHeader(), setError(), setMessageType(), str_replace, and validateAddress().
Referenced by send().
punyencodeAddress ($address)
Converts IDN in given email address to its ASCII form, also known as punycode, if possible.
Important: Address must be passed in same encoding as currently set in PHPMailer::$CharSet. This function silently returns unmodified address if:
No conversion is necessary (i.e. domain name is not an IDN, or is already in ASCII form)
Conversion to punycode is impossible (e.g. required PHP functions are not available) or fails for any reason (e.g. domain has characters not allowed in an IDN)
See also
PHPMailer::$CharSet
Parameters
string $address The email address to convert
Returns
string The encoded address in ASCII form
Definition at line 1093 of file class-phpmailer.php.
References has8bitChars(), and idnSupported().
Referenced by preSend().
static rfcDate () static
Return an RFC 822 formatted date.
public
Returns
string
Definition at line 3100 of file class-phpmailer.php.
References date.
secureHeader ($str)
Strip newlines to prevent header injection.
public
Parameters
string $str
Returns
string
Definition at line 3530 of file class-phpmailer.php.
References str_replace.
Referenced by addrFormat(), attachAll(), createHeader(), mailPassthru(), and preSend().
send ()
Create a message and send it.
Uses the sending method specified by $Mailer.
Exceptions
phpmailerException
Returns
boolean false on error - See the ErrorInfo property for details of the error.
Definition at line 1119 of file class-phpmailer.php.
References postSend(), preSend(), and setError().
sendmailSend ($header, $body) protected
Send mail using the $Sendmail program.
Parameters
string $header The message headers
string $body The message body
See also
PHPMailer::$Sendmail
Exceptions
phpmailerException protected
Returns
boolean
Definition at line 1275 of file class-phpmailer.php.
References doCallback(), and lang().
Referenced by postSend().
serverHostname () protected
Get the server hostname.
Returns 'localhost.localdomain' if unknown. protected
Returns
string
Definition at line 3114 of file class-phpmailer.php.
References $_SERVER, $Hostname, and elseif.
Referenced by createHeader(), and smtpConnect().
set ($name, $value = '')
Set or reset instance properties.
You should avoid this function - it's more verbose, less efficient, more error-prone and harder to debug than setting properties directly. Usage Example: `$mail->set('SMTPSecure', 'tls');` is the same as: `$mail->SMTPSecure = 'tls';` public
Parameters
string $name The property name to set
mixed $value The value to set the property to
Returns
boolean Should this not be using the __set() magic function?
Definition at line 3513 of file class-phpmailer.php.
References $name, $value, lang(), and setError().
setError ($msg) protected
Add an error message to the error container.
protected
Parameters
string $msg
Returns
void
Definition at line 3073 of file class-phpmailer.php.
References $msg, and lang().
Referenced by addAnAddress(), addAttachment(), addEmbeddedImage(), addOrEnqueueAnAddress(), encodeFile(), encodeString(), postSend(), preSend(), send(), set(), setFrom(), and smtpSend().
setFrom ($address, $name = '', $auto = true)
Set the From and FromName properties.
Parameters
string $address
string $name
boolean $auto Whether to also set the Sender address, defaults to true
Exceptions
phpmailerException
Returns
boolean
Definition at line 934 of file class-phpmailer.php.
References $name, edebug(), has8bitChars(), idnSupported(), lang(), setError(), and validateAddress().
setLanguage ($langcode = 'en', $lang_path = '')
Set the language for error messages.
Returns false if it cannot load the language file. The default language is English.
Parameters
string $langcode ISO 639-1 2-character language code (e.g. French is "fr")
string $lang_path Path to the language file directory, with trailing separator (slash)
Returns
boolean public
Definition at line 1600 of file class-phpmailer.php.
Referenced by lang().
setMessageType () protected
Set the message type.
PHPMailer only supports some preset message types, not arbitrary MIME structures. protected
Returns
void
Definition at line 2284 of file class-phpmailer.php.
References alternativeExists(), attachmentExists(), and inlineImageExists().
Referenced by preSend().
setWordWrap ()
Apply word wrapping to the message body.
Wraps the message body to the number of chars set in the WordWrap property. You should only do this to plain-text bodies as wrapping HTML tags may break them. This is called automatically by createBody(), so you don't need to call it yourself. public
Returns
void
Definition at line 1846 of file class-phpmailer.php.
References wrapText().
Referenced by createBody().
sign ($cert_filename, $key_filename, $key_pass, $extracerts_filename = '')
Set the public and private key files and password for S/MIME signing.
public
Parameters
string $cert_filename
string $key_filename
string $key_pass Password for private key
string $extracerts_filename Optional path to chain certificate
Definition at line 3558 of file class-phpmailer.php.
smtpClose ()
Close the active SMTP session if one exists.
Returns
void
Definition at line 1581 of file class-phpmailer.php.
References null.
Referenced by __destruct().
smtpConnect ($options = array())
Initiate a connection to an SMTP server.
Returns false if the operation failed.
Parameters
array $options An array of options compatible with stream_context_create() SMTP public
Exceptions
phpmailerException
Returns
boolean
Definition at line 1469 of file class-phpmailer.php.
References $Helo, $options, $Port, $prefix, $secure, $SMTPSecure, edebug(), elseif, getSMTPInstance(), lang(), null, and serverHostname().
Referenced by smtpSend().
smtpSend ($header, $body) protected
Send mail via SMTP.
Returns false if there is a bad MAIL FROM, RCPT, or DATA input. Uses the PHPMailerSMTP class by default.
See also
PHPMailer::getSMTPInstance() to use a different class.
Parameters
string $header The message headers
string $body The message body
Exceptions
phpmailerException SMTP protected
Returns
boolean
Definition at line 1406 of file class-phpmailer.php.
References $From, $Sender, $to, doCallback(), lang(), setError(), and smtpConnect().
Referenced by postSend().
textLine ($value)
Return a formatted mail line.
public
Parameters
string $value
Returns
string
Definition at line 2320 of file class-phpmailer.php.
References $LE, and $value.
Referenced by createBody(), getBoundary(), and getMailMIME().
utf8CharBoundary ($encodedText, $maxLength)
Find the last character boundary prior to $maxLength in a utf-8 quoted-printable encoded string.
Original written by Colin Brown. public
Parameters
string $encodedText utf-8 QP text
integer $maxLength Find the last character boundary prior to this length
Returns
integer
Definition at line 1801 of file class-phpmailer.php.
References elseif.
Referenced by wrapText().
static validateAddress ($address, $patternselect = 'auto') static
Check that a string looks like an email address.
Parameters
string $address The email address to check
string $patternselect A selector for the validation pattern to use :
auto Pick best pattern automatically;
pcre8 Use the squiloople.com pattern, requires PCRE > 8.0, PHP >= 5.3.2, 5.2.14;
pcre Use old PCRE implementation;
php Use PHP built-in FILTER_VALIDATE_EMAIL;
html5 Use the pattern given by the HTML5 spec for 'email' type form input elements.
noregex Don't use a regex: super fast, really dumb.
Returns
boolean public
Uses the same RFC5322 regex on which FILTER_VALIDATE_EMAIL is based, but allows dotless domains. 2009-2010 Michael Rushton Feel free to use and redistribute this code. But please keep this copyright notice. This is the pattern used in the HTML5 spec for validation of 'email' type form input elements. http://www.whatwg.org/specs/web-apps/current-work/#e-mail-state-(type=email)
Definition at line 986 of file class-phpmailer.php.
References elseif.
Referenced by addAnAddress(), preSend(), and setFrom().
wrapText ($message, $length, $qp_mode = false)
Word-wrap message.
For use with mailers that do not automatically perform wrapping and for quoted-printable encoded messages. Original written by philippe.
Parameters
string $message The message to wrap
integer $length The line length to wrap to
boolean $qp_mode Whether to run in Quoted-Printable mode public
Returns
string
Definition at line 1702 of file class-phpmailer.php.
References $LE, $message, elseif, fixEOL(), and utf8CharBoundary().
Referenced by encodeHeader(), and setWordWrap().
Field Documentation
$action_function = ''
Definition at line 440 of file class-phpmailer.php.
$all_recipients = array() protected
Definition at line 491 of file class-phpmailer.php.
Referenced by getAllRecipientAddresses().
$AllowEmpty = false
Definition at line 379 of file class-phpmailer.php.
$AltBody = ''
Definition at line 118 of file class-phpmailer.php.
$attachment = array() protected
Definition at line 520 of file class-phpmailer.php.
Referenced by attachAll(), attachmentExists(), getAttachments(), and inlineImageExists().
$AuthType = ''
Definition at line 291 of file class-phpmailer.php.
$bcc = array() protected
Definition at line 475 of file class-phpmailer.php.
Referenced by clearBCCs(), doCallback(), and getBccAddresses().
$Body = ''
Definition at line 109 of file class-phpmailer.php.
Referenced by msgHTML().
$boundary = array() protected
Definition at line 548 of file class-phpmailer.php.
Referenced by attachAll(), endBoundary(), and getBoundary().
$cc = array() protected
Definition at line 468 of file class-phpmailer.php.
Referenced by clearCCs(), doCallback(), and getCcAddresses().
$CharSet = 'iso-8859-1'
Definition at line 48 of file class-phpmailer.php.
Referenced by createBody(), and getBoundary().
$ConfirmReadingTo = ''
Definition at line 190 of file class-phpmailer.php.
$ContentType = 'text/plain'
Definition at line 54 of file class-phpmailer.php.
Referenced by getBoundary().
$CustomHeader = array() protected
Definition at line 527 of file class-phpmailer.php.
Referenced by getCustomHeaders().
$Debugoutput = 'echo'
Definition at line 342 of file class-phpmailer.php.
$DKIM_domain = ''
Definition at line 414 of file class-phpmailer.php.
$DKIM_identity = ''
Definition at line 400 of file class-phpmailer.php.
$DKIM_passphrase = ''
Definition at line 407 of file class-phpmailer.php.
$DKIM_private = ''
Definition at line 420 of file class-phpmailer.php.
$DKIM_selector = ''
Definition at line 393 of file class-phpmailer.php.
$do_verp = false
Definition at line 373 of file class-phpmailer.php.
$Encoding = '8bit'
Definition at line 61 of file class-phpmailer.php.
Referenced by createBody(), and getBoundary().
$error_count = 0 protected
Definition at line 562 of file class-phpmailer.php.
$ErrorInfo = ''
Definition at line 67 of file class-phpmailer.php.
$exceptions = false protected
Definition at line 598 of file class-phpmailer.php.
Referenced by __construct().
$From = 'root@localhost'
Definition at line 73 of file class-phpmailer.php.
Referenced by smtpSend().
$FromName = 'Root User'
Definition at line 79 of file class-phpmailer.php.
$Helo = ''
Definition at line 242 of file class-phpmailer.php.
Referenced by smtpConnect().
$Host = 'localhost'
Definition at line 226 of file class-phpmailer.php.
$Hostname = ''
Definition at line 199 of file class-phpmailer.php.
Referenced by serverHostname().
$Ical = ''
Definition at line 128 of file class-phpmailer.php.
$language = array() protected
Definition at line 555 of file class-phpmailer.php.
Referenced by getTranslations().
$lastMessageID = '' protected
Definition at line 534 of file class-phpmailer.php.
Referenced by getLastMessageID().
$LE = "\n"
Definition at line 387 of file class-phpmailer.php.
Referenced by addrAppend(), attachAll(), base64EncodeWrapMB(), createBody(), encodeString(), endBoundary(), getBoundary(), getMailMIME(), headerLine(), textLine(), and wrapText().
$Mailer = 'mail'
Definition at line 163 of file class-phpmailer.php.
$mailHeader = '' protected
Definition at line 149 of file class-phpmailer.php.
$message_type = '' protected
Definition at line 541 of file class-phpmailer.php.
$MessageDate = ''
Definition at line 213 of file class-phpmailer.php.
$MessageID = ''
Definition at line 206 of file class-phpmailer.php.
Referenced by createHeader().
$MIMEBody = '' protected
Definition at line 135 of file class-phpmailer.php.
Referenced by getSentMIMEMessage().
$MIMEHeader = '' protected
Definition at line 142 of file class-phpmailer.php.
Referenced by preSend().
$Password = ''
Definition at line 284 of file class-phpmailer.php.
$PluginDir = ''
Definition at line 184 of file class-phpmailer.php.
$Port = 25
Definition at line 233 of file class-phpmailer.php.
Referenced by smtpConnect().
$Priority = null
Definition at line 42 of file class-phpmailer.php.
$Realm = ''
Definition at line 298 of file class-phpmailer.php.
$RecipientsQueue = array() protected
Definition at line 503 of file class-phpmailer.php.
Referenced by clearQueuedAddresses().
$ReplyTo = array() protected
Definition at line 482 of file class-phpmailer.php.
Referenced by getReplyToAddresses().
$ReplyToQueue = array() protected
Definition at line 513 of file class-phpmailer.php.
$ReturnPath = ''
Definition at line 96 of file class-phpmailer.php.
$Sender = ''
Definition at line 86 of file class-phpmailer.php.
Referenced by smtpSend().
$Sendmail = '/usr/sbin/sendmail'
Definition at line 169 of file class-phpmailer.php.
$sign_cert_file = '' protected
Definition at line 569 of file class-phpmailer.php.
$sign_extracerts_file = '' protected
Definition at line 583 of file class-phpmailer.php.
$sign_key_file = '' protected
Definition at line 576 of file class-phpmailer.php.
$sign_key_pass = '' protected
Definition at line 591 of file class-phpmailer.php.
$SingleTo = false
Definition at line 357 of file class-phpmailer.php.
$SingleToArray = array()
Definition at line 364 of file class-phpmailer.php.
$smtp = null protected
Definition at line 454 of file class-phpmailer.php.
Referenced by getSMTPInstance().
$SMTPAuth = false
Definition at line 266 of file class-phpmailer.php.
$SMTPAutoTLS = true
Definition at line 257 of file class-phpmailer.php.
$SMTPDebug = 0
Definition at line 326 of file class-phpmailer.php.
$SMTPKeepAlive = false
Definition at line 350 of file class-phpmailer.php.
$SMTPOptions = array()
Definition at line 272 of file class-phpmailer.php.
$SMTPSecure = ''
Definition at line 249 of file class-phpmailer.php.
Referenced by smtpConnect().
$Subject = ''
Definition at line 102 of file class-phpmailer.php.
$Timeout = 300
Definition at line 312 of file class-phpmailer.php.
$to = array() protected
Definition at line 461 of file class-phpmailer.php.
Referenced by clearAddresses(), DKIM_Add(), doCallback(), getToAddresses(), mailPassthru(), mailSend(), and smtpSend().
$uniqueid = '' protected
Definition at line 605 of file class-phpmailer.php.
Referenced by createBody().
$Username = ''
Definition at line 278 of file class-phpmailer.php.
$UseSendmailOptions = true
Definition at line 176 of file class-phpmailer.php.
$Version = '5.2.14'
Definition at line 34 of file class-phpmailer.php.
$WordWrap = 0
Definition at line 156 of file class-phpmailer.php.
$Workstation = ''
Definition at line 305 of file class-phpmailer.php.
$XMailer = ''
Definition at line 447 of file class-phpmailer.php.
const CRLF = "\r\n"
SMTP RFC standard line ending.
Definition at line 625 of file class-phpmailer.php.
const MAX_LINE_LENGTH = 998
Definition at line 631 of file class-phpmailer.php.
const STOP_CONTINUE = 1
Error severity: message, likely ok to continue processing.
Definition at line 615 of file class-phpmailer.php.
const STOP_CRITICAL = 2
Error severity: message, plus full stop, critical error reached.
Definition at line 620 of file class-phpmailer.php.
const STOP_MESSAGE = 0
Error severity: message only, continue processing.
Definition at line 610 of file class-phpmailer.php.
The documentation for this class was generated from the following file:
class-phpmailer.php