GravityView: AdminMenu Class Reference
AdminMenu Class Reference
This class is responsible for adding a GravityKit menu and submenu items to the WP admin panel.
Public Member Functions
add_admin_menu ()
Configures GravityKit top-level menu and submenu items in WP admin.
get_badge_counter_markup ($menu_id, $badge_count)
Returns the markup for the badge counter.
init ()
Initializes the class.
Static Public Member Functions
static add_submenu_item ($submenu, $position='top')
Adds a submenu to the GravityKit top-level menu in WP admin.
static static get_instance ()
Returns class instance.
static get_submenus ()
Returns submenus optionally modified by a filter.
static remove_admin_menu ()
Removes the GravityKit top-level menu from WP admin.
static remove_submenu_item ($id)
Removes a submenu from the GravityKit top-level menu in WP admin and if the top-level menu is empty, removes it as well.
Data Fields
const WP_ADMIN_MENU_SLUG = '_gk_admin_menu'
Static Private Attributes
static $_instance
static $_submenus
Detailed Description
This class is responsible for adding a GravityKit menu and submenu items to the WP admin panel.
Definition at line 14 of file AdminMenu.php.
Member Function Documentation
add_admin_menu()
add_admin_menu ()
Configures GravityKit top-level menu and submenu items in WP admin.
Since
1.0.0
array $menu array $submenu
void
Runs Filter:
gk/foundation/admin-menu/submenu/{$submenu_id}/counter Displays counter next to the submenu title.
Since
1.0.0
Parameters
int $badge_count
Controls the position of the top-level GravityKit admin menu.
Runs Filter:
gk/foundation/admin-menu/position
Since
1.0.0
Parameters
float $menu_position Default: value of gform_menu_position filter + 0.001.
Runs Filter:
gk/foundation/admin-menu/counter Displays counter next to the top-menu title.
Since
1.0.0
Parameters
int $total_badge_count
Definition at line 80 of file AdminMenu.php.
References AdminMenu\get_badge_counter_markup().
add_submenu_item()
static add_submenu_item ($submenu, $position = 'top') static
Adds a submenu to the GravityKit top-level menu in WP admin.
Since
1.0.0
Parameters
array $submenu The submenu data.
string $position The position of the submenu. Default: 'top'.
void
Definition at line 233 of file AdminMenu.php.
References AdminMenu\$_submenus.
Referenced by TrustedLogin\add_gk_submenu_item(), and Framework\add_gk_submenu_item().
get_badge_counter_markup()
get_badge_counter_markup ($menu_id, $badge_count)
Returns the markup for the badge counter.
Since
1.0.0
Parameters
string $menu_id
int | string $badge_count
Returns
string
Definition at line 335 of file AdminMenu.php.
Referenced by AdminMenu\add_admin_menu().
get_instance()
static static get_instance () static
Returns class instance.
Since
1.0.0
Returns
AdminMenu
Definition at line 42 of file AdminMenu.php.
Referenced by Core\init().
get_submenus()
static get_submenus () static
Returns submenus optionally modified by a filter.
Since
1.0.0
Returns
array
Runs Filter:
gk/foundation/admin-menu/submenus Modifies the submenus object.
Since
1.0.0
Parameters
array $submenus Submenus.
Definition at line 266 of file AdminMenu.php.
init()
init ()
Initializes the class.
Since
1.0.0
Returns
void
Definition at line 57 of file AdminMenu.php.
remove_admin_menu()
static remove_admin_menu () static
Removes the GravityKit top-level menu from WP admin.
Since
1.0.0
array $menu
void
Definition at line 315 of file AdminMenu.php.
remove_submenu_item()
static remove_submenu_item ($id) static
Removes a submenu from the GravityKit top-level menu in WP admin and if the top-level menu is empty, removes it as well.
Since
1.0.0
array $submenu
void
Definition at line 286 of file AdminMenu.php.
Referenced by Framework\enqueue_assets().
Field Documentation
$_instance
$_instance static private
Definition at line 22 of file AdminMenu.php.
$_submenus
$_submenus static private
Initial value:
= [
        'top'    => []
Definition at line 29 of file AdminMenu.php.
Referenced by AdminMenu\add_submenu_item().
WP_ADMIN_MENU_SLUG
const WP_ADMIN_MENU_SLUG = '_gk_admin_menu'
Definition at line 15 of file AdminMenu.php.
The documentation for this class was generated from the following file:
AdminMenu.php