GravityView: SimplePie_Parser Class Reference
SimplePie_Parser Class Reference
Public Member Functions
cdata ($parser, $cdata)
get_current_byte ()
get_current_column ()
get_current_line ()
get_data ()
get_error_code ()
get_error_string ()
parse (&$data, $encoding)
set_registry (SimplePie_Registry $registry)
split_ns ($string)
tag_close ($parser, $tag)
tag_open ($parser, $tag, $attributes)
Data Fields
$current_byte
$current_column
$current_line
$current_xhtml_construct = -1
$data = array()
$datas = array(array())
$element = array('')
$encoding
$error_code
$error_string
$namespace = array('')
$separator = ' '
$xml_base = array('')
$xml_base_explicit = array(false)
$xml_lang = array('')
Protected Attributes
$registry
Detailed Description
Definition at line 54 of file Parser.php.
Member Function Documentation
cdata ($parser, $cdata)
Definition at line 335 of file Parser.php.
Referenced by parse().
get_current_byte ()
Definition at line 258 of file Parser.php.
References $current_byte.
get_current_column ()
Definition at line 253 of file Parser.php.
References $current_column.
get_current_line ()
Definition at line 248 of file Parser.php.
References $current_line.
get_data ()
Definition at line 263 of file Parser.php.
References $data.
get_error_code ()
Definition at line 238 of file Parser.php.
References $error_code.
get_error_string ()
Definition at line 243 of file Parser.php.
References $error_string.
parse (& $data, $encoding)
Definition at line 78 of file Parser.php.
References $attributes, $data, $encoding, cdata(), elseif, null, tag_close(), and tag_open().
set_registry (SimplePie_Registry $registry)
Definition at line 73 of file Parser.php.
References $registry.
split_ns ($string)
Definition at line 370 of file Parser.php.
References SIMPLEPIE_NAMESPACE_ITUNES, SIMPLEPIE_NAMESPACE_MEDIARSS, SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG, SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG2, SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG3, SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG4, and SIMPLEPIE_NAMESPACE_MEDIARSS_WRONG5.
Referenced by tag_open().
tag_close ($parser, $tag)
Definition at line 347 of file Parser.php.
References SIMPLEPIE_NAMESPACE_XHTML.
Referenced by parse().
tag_open ($parser, $tag, $attributes)
Definition at line 268 of file Parser.php.
References $attributes, $data, $name, $value, SIMPLEPIE_NAMESPACE_ATOM_03, SIMPLEPIE_NAMESPACE_ATOM_10, SIMPLEPIE_NAMESPACE_RSS_090, SIMPLEPIE_NAMESPACE_RSS_10, SIMPLEPIE_NAMESPACE_RSS_20, SIMPLEPIE_NAMESPACE_XHTML, SIMPLEPIE_NAMESPACE_XML, and split_ns().
Referenced by parse().
Field Documentation
$current_byte
Definition at line 60 of file Parser.php.
Referenced by get_current_byte().
$current_column
Definition at line 59 of file Parser.php.
Referenced by get_current_column().
$current_line
Definition at line 58 of file Parser.php.
Referenced by get_current_line().
$current_xhtml_construct = -1
Definition at line 69 of file Parser.php.
$data = array()
Definition at line 67 of file Parser.php.
Referenced by get_data(), parse(), and tag_open().
$datas = array(array())
Definition at line 68 of file Parser.php.
$element = array('')
Definition at line 63 of file Parser.php.
$encoding
Definition at line 70 of file Parser.php.
Referenced by parse().
$error_code
Definition at line 56 of file Parser.php.
Referenced by get_error_code().
$error_string
Definition at line 57 of file Parser.php.
Referenced by get_error_string().
$namespace = array('')
Definition at line 62 of file Parser.php.
$registry protected
Definition at line 71 of file Parser.php.
Referenced by set_registry().
$separator = ' '
Definition at line 61 of file Parser.php.
$xml_base = array('')
Definition at line 64 of file Parser.php.
$xml_base_explicit = array(false)
Definition at line 65 of file Parser.php.
$xml_lang = array('')
Definition at line 66 of file Parser.php.
The documentation for this class was generated from the following file:
Parser.php