GravityView: WP_Dependencies Class Reference
WP_Dependencies Class Reference
Public Member Functions
add ($handle, $src, $deps=array(), $ver=false, $args=null)
Register an item.
add_data ($handle, $key, $value)
Add extra item data.
all_deps ($handles, $recursion=false, $group=false)
Determine dependencies.
dequeue ($handles)
Dequeue an item or items.
do_item ($handle)
Process a dependency.
do_items ($handles=false, $group=false)
Process the items and dependencies.
enqueue ($handles)
Queue an item or items.
get_data ($handle, $key)
Get extra item data.
query ($handle, $list= 'registered')
Query list for an item.
remove ($handles)
Un-register an item or items.
set_group ($handle, $recursion, $group)
Set item group, unless already in a lower group.
Data Fields
$args = array()
$done = array()
$group = 0
$groups = array()
$queue = array()
$registered = array()
$to_do = array()
Protected Member Functions
recurse_deps ($queue, $handle)
Recursively search the passed dependency tree for $handle.
Detailed Description
Definition at line 13 of file class.wp-dependencies.php.
Member Function Documentation
add ($handle, $src, $deps = array(), $ver = false, $args = null)
Register an item.
Registers the item if no item of that name already exists.
public
Since
2.1.0
Parameters
string $handle Unique item name.
string $src The item url.
array $deps Optional. An array of item handle strings on which this item depends.
string $ver Optional. Version (used for cache busting).
mixed $args Optional. Custom property of the item. NOT the class property $args. Examples: $media, $in_footer.
Returns
bool Whether the item has been registered. True on success, false on failure.
Definition at line 218 of file class.wp-dependencies.php.
References $args, and registered.
add_data ($handle, $key, $value)
Add extra item data.
Adds data to a registered item.
public
Since
2.6.0
Parameters
string $handle Name of the item. Should be unique.
string $key The data key.
mixed $value The data value.
Returns
bool True on success, false on failure.
Definition at line 238 of file class.wp-dependencies.php.
References $value, and registered.
Referenced by WP_Styles\add_inline_style(), and WP_Scripts\localize().
all_deps ($handles, $recursion = false, $group = false)
Determine dependencies.
Recursively builds an array of items to process taking dependencies into account. Does NOT catch infinite loops.
public
Since
2.1.0
Parameters
mixed $handles Item handle and argument (string) or item handles and arguments (array of strings).
bool $recursion Internal flag that function is calling itself.
mixed $group Group level: (int) level, (false) no groups.
Returns
bool True on success, false on failure.
Definition at line 159 of file class.wp-dependencies.php.
References $group, elseif, registered, and set_group().
Referenced by do_items().
dequeue ($handles)
Dequeue an item or items.
Decodes handles and arguments, then dequeues handles and removes arguments from the class property $args.
public
Since
2.1.0
Parameters
mixed $handles Item handle and argument (string) or item handles and arguments (array of strings).
Definition at line 316 of file class.wp-dependencies.php.
do_item ($handle)
Process a dependency.
public
Since
2.6.0
Parameters
string $handle Name of the item. Should be unique.
Returns
bool True on success, false if not set.
Definition at line 141 of file class.wp-dependencies.php.
References registered.
Referenced by do_items().
do_items ($handles = false, $group = false)
Process the items and dependencies.
Processes the items passed to it or the queue, and their dependencies.
public
Since
2.1.0
Parameters
mixed $handles Optional. Items to be processed: Process queue (false), process item (string), process items (array of strings).
mixed $group Group level: level (int), no groups (false).
Returns
array Handles of items that have been processed.
Definition at line 91 of file class.wp-dependencies.php.
References $done, $group, all_deps(), do_item(), and registered.
Referenced by WP_Styles\do_footer_items(), WP_Scripts\do_footer_items(), WP_Scripts\do_head_items(), and WP_Scripts\print_scripts().
enqueue ($handles)
Queue an item or items.
Decodes handles and arguments, then queues handles and stores arguments in the class property $args. For example in extending classes, $args is appended to the item url as a query string. Note $args is NOT the $args property of items in the $registered array.
public
Since
2.1.0
Parameters
mixed $handles Item handle and argument (string) or item handles and arguments (array of strings).
Definition at line 294 of file class.wp-dependencies.php.
References registered.
get_data ($handle, $key)
Get extra item data.
Gets data associated with a registered item.
public
Since
3.3.0
Parameters
string $handle Name of the item. Should be unique.
string $key The data key.
Returns
mixed Extra item data (string), false otherwise.
Definition at line 257 of file class.wp-dependencies.php.
References registered.
Referenced by WP_Styles\add_inline_style(), WP_Scripts\do_item(), WP_Scripts\localize(), WP_Scripts\print_extra_script(), WP_Styles\print_inline_style(), and WP_Scripts\set_group().
query ($handle, $list = 'registered')
Query list for an item.
public
Since
2.1.0
Parameters
string $handle Name of the item. Should be unique.
string $list Property name of list array.
Returns
bool Found, or object Item data.
Definition at line 362 of file class.wp-dependencies.php.
References $list, recurse_deps(), and registered.
recurse_deps ($queue, $handle) protected
Recursively search the passed dependency tree for $handle.
Since
4.0.0
Parameters
array $queue An array of queued _WP_Dependency handle objects.
string $handle Name of the item. Should be unique.
Returns
bool Whether the handle is found after recursively searching the dependency tree.
Definition at line 336 of file class.wp-dependencies.php.
References $queue, elseif, and registered.
Referenced by query().
remove ($handles)
Un-register an item or items.
public
Since
2.1.0
Parameters
mixed $handles Item handle and argument (string) or item handles and arguments (array of strings).
Returns
void
Definition at line 276 of file class.wp-dependencies.php.
References registered.
set_group ($handle, $recursion, $group)
Set item group, unless already in a lower group.
public
Since
2.8.0
Parameters
string $handle Name of the item. Should be unique.
bool $recursion Internal flag that calling function was called recursively.
mixed $group Group level.
Returns
bool Not already in the group or a lower group
Definition at line 399 of file class.wp-dependencies.php.
References $group.
Referenced by all_deps().
Field Documentation
$args = array()
Definition at line 59 of file class.wp-dependencies.php.
Referenced by add().
$done = array()
Definition at line 48 of file class.wp-dependencies.php.
Referenced by WP_Styles\do_footer_items(), WP_Scripts\do_footer_items(), WP_Scripts\do_head_items(), and do_items().
$group = 0
Definition at line 77 of file class.wp-dependencies.php.
Referenced by all_deps(), WP_Scripts\do_item(), do_items(), WP_Scripts\print_scripts(), WP_Scripts\set_group(), and set_group().
$groups = array()
Definition at line 68 of file class.wp-dependencies.php.
$queue = array()
Definition at line 30 of file class.wp-dependencies.php.
Referenced by recurse_deps().
$registered = array()
Definition at line 21 of file class.wp-dependencies.php.
$to_do = array()
Definition at line 39 of file class.wp-dependencies.php.
The documentation for this class was generated from the following file:
class.wp-dependencies.php