GravityView: View Class Reference
View Class Reference
If this file is called directly, abort.
Public Member Functions
__construct ()
The constructor.
__get ($key)
as_data ()
Be compatible with the old data object.
can_render ($context=null, $request=null)
Checks whether this view can be accessed or not.
get_entries ($request=null)
Retrieve the entries for the current view and request.
get_query_class ()
Return the query class for this View.
offsetExists ($offset)
ArrayAccess compatibility layer with GravityView_View_Data::$views.
offsetGet ($offset)
ArrayAccess compatibility layer with GravityView_View_Data::$views.
offsetSet ($offset, $value)
ArrayAccess compatibility layer with GravityView_View_Data::$views.
offsetUnset ($offset)
ArrayAccess compatibility layer with GravityView_View_Data::$views.
Static Public Member Functions
static _flush_cache ($view_id=null)
Flush the view cache.
static add_rewrite_endpoint ()
Add extra rewrite endpoints.
static by_id ($post_id)
Construct a instance from a post ID.
static content ($content)
A renderer filter for the View post type content.
static exists ($view)
Determines if a view exists to begin with.
static from_post ($post)
Construct a instance from a .
static get_joined_forms ($post_id)
Get joined forms associated with a view In no particular order.
static get_joins ($post)
Get joins associated with a view.
static get_unions ($post)
Get unions associated with a view.
static register_post_type ()
Register the gravityview WordPress Custom Post Type.
static restrict ($caps, $cap, $user_id, $args)
Restrict View access to specific capabilities.
static template_redirect ()
Last chance to configure the output.
Data Fields
$fields
$form
$joins = array()
$settings
$unions = array()
$widgets
Private Attributes
$post
Static Private Attributes
static $cache = array()
Detailed Description
If this file is called directly, abort.
The default GravityView View class.
Houses all base View functionality.
Can be accessed as an array for old compatibility's sake in line with the elements inside the ::$views array.
Definition at line 17 of file class-gv-view.php.
Constructor & Destructor Documentation
__construct()
__construct ()
The constructor.
Definition at line 98 of file class-gv-view.php.
Member Function Documentation
__get()
__get ($key)
Definition at line 1577 of file class-gv-view.php.
_flush_cache()
static _flush_cache ($view_id = null) static
Flush the view cache.
Parameters
int $view_id The View to reset cache for. Optional. Default: resets everything.
Definition at line 786 of file class-gv-view.php.
References $view_id.
add_rewrite_endpoint()
static add_rewrite_endpoint () static
Add extra rewrite endpoints.
Returns
void
CSV.
Definition at line 220 of file class-gv-view.php.
as_data()
as_data ()
Be compatible with the old data object.
Some external code expects an array (doing things like foreach on this, or array_keys) so let's return an array in the old format for such cases. Do not use unless using for back-compatibility.
Definition at line 911 of file class-gv-view.php.
References gravityview_get_form().
by_id()
static by_id ($post_id) static
Construct a instance from a post ID.
Parameters
int | string $post_id The post ID.
Since
2.0
Returns
|null An instance around this or null if not found.
Definition at line 803 of file class-gv-view.php.
References $post.
Referenced by GravityView_Admin_Bar\add_floaty_icon(), GravityView_frontend\add_scripts_and_styles(), GravityView_Entry_Approval\autounapprove(), gventry\callback(), gvfield\callback(), gravityview\callback(), GravityView_Delete_Entry\check_user_cap_delete_entry(), GravityView_Edit_Entry_Render\edit_entry_form(), GravityView_Widget_Search\filter_entries(), GravityView_Edit_Entry_Render\get_configured_edit_fields(), GravityView_Recent_Entries_Widget\get_entries(), GVCommon\get_entry(), GravityView_View_Data\get_fields(), Views_Route\get_item_permissions_check(), Views_Route\get_sub_item(), Views_Route\get_sub_item_permissions_check(), GravityView_View_Data\get_view(), GV\Mocks\GravityView_frontend_get_view_entries(), GV\Mocks\GravityView_View_Data_add_view(), GravityView_Edit_Entry_Render\maybe_print_message(), oEmbed\parse_matches(), Views_Route\prepare_entry_for_response(), GravityView_Delete_Entry\process_delete(), GravityView_Widget_Search\render_frontend(), GravityView_View\render_widget_hooks(), GravityView_Field_Sequence\replace_merge_tag(), and GravityView_frontend\single_entry_title().
can_render()
can_render ($context = null, $request = null)
Checks whether this view can be accessed or not.
Parameters
string[] $context The context we're asking for access from. Can any and as many of one of: edit An edit context. single A single context. cpt The custom post type single page accessed. shortcode Embedded as a shortcode. oembed Embedded as an oEmbed. rest A REST call.
\GV\Request $request The request
Returns
bool| An error if this View shouldn't be rendered here.
Runs Filter:
gravityview/view/can_render Whether the view can be rendered or not.
Parameters
bool | \WP_Error $result The result. Default: null.
\GV\View $view The view.
string[] $context See ::can_render
\GV\Request $request The request.
This View is password protected. Nothing to do here.
Is this View directly accessible via a post URL?
See also
https://codex.wordpress.org/Function_Reference/register_post_type#public
Runs Filter:
gravityview_direct_access Should Views be directly accessible, or only visible using the shortcode?
Parameters
[in,out] boolean true: allow Views to be accessible directly. false: Only allow Views to be embedded. Default: true
int $view_id The ID of the View currently being requested. 0 for general setting
Runs Filter:
gravityview/request/output/direct Should this View be directly accessbile?
Since
2.0
Parameters
[in,out] boolean Accessible or not. Default: accessbile.
\GV\View $view The View we're trying to directly render here.
\GV\Request $request The current request.
Is this View an embed-only View? If so, don't allow rendering here, as this is a direct request.
Private, pending, draft, etc.
Definition at line 415 of file class-gv-view.php.
References gravityview(), and GVCommon\has_cap().
content()
static content ($content) static
A renderer filter for the View post type content.
Parameters
string $content Should be empty, as we don't store anything there.
Returns
string $content The view content as output by the renderers.
This is not a View. Bail.
Shortcodes and oEmbeds and whatnot will be handled elsewhere.
Check permissions.
This View has no data source. There's nothing to show really. ...apart from a nice message if the user can do anything about it.
Editing a single entry.
Viewing a single entry.
Plain old View.
Definition at line 250 of file class-gv-view.php.
References $content, $entry, $image, $title, GVCommon\check_entry_display(), gravityview(), GRAVITYVIEW_FILE, GVCommon\has_cap(), GravityView_Entry_Approval_Status\is_approved(), and GravityView_Entry_Approval\meta_key.
exists()
static exists ($view) static
Determines if a view exists to begin with.
Parameters
int | \WP_Post | null $view The WordPress post ID, a object or null for global $post;
Since
2.0
Returns
bool Whether the post exists or not.
Definition at line 819 of file class-gv-view.php.
Referenced by GravityView_View_Data\maybe_get_view_id().
from_post()
static from_post ($post) static
Construct a instance from a .
Parameters
\WP_Post $post The instance to wrap.
Since
2.0
Returns
|null An instance around this if valid, null otherwise.
Runs Filter:
gravityview/view/get Override View.
Parameters
\GV\View $view The View instance pointer.
Since
2.1
Get connected form.
Runs Filter:
gravityview/configuration/fields Filter the View fields' configuration array.
Since
1.6.5
Parameters
$fields array Multi-array of fields with first level being the field zones.
$view_id int The View the fields are being pulled for.
Runs Filter:
gravityview/view/configuration/fields Filter the View fields' configuration array.
Since
2.0
Parameters
array $fields Multi-array of fields with first level being the field zones.
\GV\View $view The View the fields are being pulled for.
Runs Filter:
gravityview/view/fields Filter the Field Collection for this View.
Since
2.0
Parameters
\GV\Field_Collection $fields A collection of fields.
\GV\View $view The View the fields are being pulled for.
Runs Filter:
gravityview/view/configuration/widgets Filter the View widgets' configuration array.
Since
2.0
Parameters
array $fields Multi-array of widgets with first level being the field zones.
\GV\View $view The View the widgets are being pulled for.
Runs Filter:
gravityview/view/widgets Filter the Widget Collection for this View.
Since
2.0
Parameters
\GV\Widget_Collection $widgets A collection of widgets.
\GV\View $view The View the widgets are being pulled for.
View configuration.
Add the template name into the settings.
View basics.
Runs Filter:
gravityview/view/get Override View.
Parameters
\GV\View $view The View instance pointer.
Since
2.1
Definition at line 675 of file class-gv-view.php.
References $post, GV\get(), gravityview(), gravityview_get_template_id(), and gravityview_get_template_settings().
Referenced by oEmbed\parse_matches(), Views_Route\prepare_view_for_response(), GravityView_Admin_Views\render_active_areas(), and GravityView_Admin_Metaboxes\render_view_configuration_metabox().
get_entries()
get_entries ($request = null)
Retrieve the entries for the current view and request.
Parameters
Remove multiple sorting before calling legacy filters. This allows us to fake it till we make it.
Cleanup duplicate field_filter parameters to simplify the query.
Parameters
\GF_Query $query
Apply multisort.
Merge time subfield sorts.
ORDER again.
Any joins?
This is a temporary stub filter, until GF_Query supports NULL conditions. Do not use! This filter will be removed.
Unions?
Parameters
\GF_Query_Condition $condition
array $fields
$recurse
Returns
Parameters
\GF_Query | \GF_Patched_Query $q
Runs Actions:
gravityview/view/query Override the before the get() call.
Parameters
\GF_Query $query The current query object reference
\GV\View $this The current view object
\GV\Request $request The request object
Map from Gravity Forms entries arrays to an Entry_Collection.
Add total count callback.
Runs Filter:
gravityview/view/entries Modify the entry fetching filters, sorts, offsets, limits.
Parameters
\GV\Entry_Collection $entries The entries for this view.
\GV\View $view The view.
\GV\Request $request The request.
Definition at line 931 of file class-gv-view.php.
References $entries, $entry, $field, $form_id, GravityView_frontend\_override_sorting_id_by_field_type(), GravityView_Entry_Approval_Status\APPROVED, Entry_Sort\ASC, GVCommon\calculate_get_entries_criteria(), Entry_Sort\DESC, Utils\get(), GV\get(), gravityview(), GVCommon\has_cap(), GVCommon\is_field_numeric(), and GravityView_Entry_Approval\meta_key.
Referenced by View_Renderer\render().
get_joined_forms()
static get_joined_forms ($post_id) static
Get joined forms associated with a view In no particular order.
Since
2.0.11
2.0
Parameters
int $post_id ID of the View
Returns
[] Array of instances
Definition at line 568 of file class-gv-view.php.
References GV\$form, $forms, and gravityview().
Referenced by GravityView_Admin_Views\render_field_pickers().
get_joins()
static get_joins ($post) static
Get joins associated with a view.
Parameters
\WP_Post $post GravityView CPT to get joins for
Since
2.0.11
Returns
[] Array of instances
Definition at line 518 of file class-gv-view.php.
References $post, and gravityview().
get_query_class()
get_query_class ()
Return the query class for this View.
Returns
string The class name.
Runs Filter:
gravityview/query/class
Parameters
[in,out] string The query class. Default: GF_Query.
\GV\View $this The View.
Definition at line 1517 of file class-gv-view.php.
get_unions()
static get_unions ($post) static
Get unions associated with a view.
Parameters
\WP_Post $post GravityView CPT to get unions for
Since
2.2.2
Returns
[][] Array of unions (see self::$unions)
Definition at line 620 of file class-gv-view.php.
References $field, $field_id, $form_id, $post, Internal_Field\by_id(), GF_Field\by_id(), and gravityview().
offsetExists()
offsetExists ($offset)
ArrayAccess compatibility layer with GravityView_View_Data::$views.
Definition at line 831 of file class-gv-view.php.
offsetGet()
offsetGet ($offset)
ArrayAccess compatibility layer with GravityView_View_Data::$views.
Maps the old keys to the new data;
Definition at line 847 of file class-gv-view.php.
References GV\$form, and gravityview().
offsetSet()
offsetSet ($offset, $value)
ArrayAccess compatibility layer with GravityView_View_Data::$views.
Definition at line 883 of file class-gv-view.php.
References gravityview().
offsetUnset()
offsetUnset ($offset)
ArrayAccess compatibility layer with GravityView_View_Data::$views.
Definition at line 895 of file class-gv-view.php.
References gravityview().
register_post_type()
static register_post_type () static
Register the gravityview WordPress Custom Post Type.
Register only once
Runs Filter:
gravityview_is_hierarchical Make GravityView Views hierarchical by returning TRUE This will allow for Views to be nested with Parents and also allows for menu order to be set in the Page Attributes metabox
Since
1.13
Parameters
boolean $is_hierarchical Default: false
Runs Filter:
gravityview_post_type_supports Modify post type support values for gravityview post type
See also
add_post_type_support()
Since
1.15.2
Parameters
array $supports Array of features associated with a functional area of the edit screen. Default: 'title', 'revisions'. If $is_hierarchical, also 'page-attributes'
[in] boolean $is_hierarchical Do Views support parent/child relationships? See gravityview_is_hierarchical filter.
Register Custom Post Type - gravityview
Runs Filter:
gravityview_direct_access Should Views be directly accessible, or only visible using the shortcode?
See also
https://codex.wordpress.org/Function_Reference/register_post_type#public
Since
1.15.2
Parameters
[in,out] boolean true: allow Views to be accessible directly. false: Only allow Views to be embedded via shortcode. Default: true
int $view_id The ID of the View currently being requested. 0 for general setting
Runs Filter:
gravityview_has_archive Enable Custom Post Type archive?
Since
1.7.3
Parameters
boolean False: don't have frontend archive; True: yes, have archive. Default: false
Runs Filter:
gravityview_slug Modify the url part for a View.
See also
https://docs.gravityview.co/article/62-changing-the-view-slug
Parameters
string $slug The slug shown in the URL
Runs Filter:
gravityview/post_type/with_front Should the permalink structure be prepended with the front base. (example: if your permalink structure is /blog/, then your links will be: false->/view/, true->/blog/view/). Defaults to true.
See also
https://codex.wordpress.org/Function_Reference/register_post_type
Since
2.0
Parameters
bool $with_front
Definition at line 110 of file class-gv-view.php.
References $args, $labels, gravityview(), and GravityView_Admin\no_views_text().
restrict()
static restrict ($caps, $cap, $user_id, $args) static
Restrict View access to specific capabilities.
Hooked into map_meta_cap WordPress filter.
Since
develop
Parameters
$caps array The output capabilities.
$cap string The cap that is being checked.
$user_id int The User ID.
$args array Additional arguments to the capability.
Returns
array The resulting capabilities.
Runs Filter:
gravityview/security/require_unfiltered_html Bypass restrictions on Views that require unfiltered_html.
Parameters
[in,out] boolean
Since
develop
Parameters
string $cap The capability requested.
int $user_id The user ID.
array $args Any additional args to map_meta_cap
Definition at line 1541 of file class-gv-view.php.
References $args, and endswitch.
template_redirect()
static template_redirect () static
Last chance to configure the output.
Used for CSV output, for example.
Returns
void
CSV output.
Runs Filter:
gravityview/output/{csv|tsv}/filename Modify the name of the generated CSV or TSV file. Name will be sanitized using sanitize_file_name() before output.
See also
sanitize_file_name()
Since
2.1
Parameters
string $filename File name used when downloading a CSV or TSV. Default is "{View title}.csv" or "{View title}.tsv"
\GV\View $view Current View being rendered
Add da' BOM if GF uses it
See also
GFExport::start_export()
Runs Filter:
gravityview/csv/entry/fields Whitelist more entry fields by ID that are output in CSV requests.
Parameters
[in,out] array $allowed The allowed ones, default by_visible, by_position("context_*"), i.e. as set in the View.
\GV\View $view The view.
\GV\Entry $entry WordPress representation of the item.
Definition at line 1394 of file class-gv-view.php.
References $entries, $entry, $field, $field_id, $label, Internal_Field\by_id(), GF_Field\by_id(), and gravityview().
Field Documentation
$cache
$cache = array() static private
Definition at line 68 of file class-gv-view.php.
$fields
$fields
Definition at line 58 of file class-gv-view.php.
$form
$form
Definition at line 48 of file class-gv-view.php.
$joins
$joins = array()
Definition at line 76 of file class-gv-view.php.
$post
$post private
Definition at line 22 of file class-gv-view.php.
$settings
$settings
Definition at line 30 of file class-gv-view.php.
$unions
$unions = array()
Definition at line 93 of file class-gv-view.php.
$widgets
$widgets
Definition at line 38 of file class-gv-view.php.
The documentation for this class was generated from the following file:
class-gv-view.php