GravityView: Remote Class Reference
Remote Class Reference
The TrustedLogin all-in-one drop-in class.
Public Member Functions
__construct (Config $config, Logging $logging)
SupportUser constructor.
handle_response ($api_response, $required_keys=array())
API Response Handler.
init ()
maybe_send_webhook ($data)
POSTs to webhook_url, if defined in the configuration array.
send ($path, $data, $method='POST', $additional_headers=array())
API Function: send the API request.
Static Public Member Functions
static check_response_code ($api_response)
Translates response codes to more nuanced error descriptions specific to TrustedLogin.
Data Fields
const API_URL = 'https://app.trustedlogin.com/api/v1/'
Private Member Functions
build_api_url ($endpoint='')
Builds URL to API endpoints.
Private Attributes
$config
$logging
Detailed Description
The TrustedLogin all-in-one drop-in class.
Definition at line 28 of file Remote.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Logging $logging)
SupportUser constructor.
Definition at line 49 of file Remote.php.
References Remote\$config, and Remote\$logging.
Member Function Documentation
build_api_url()
build_api_url ($endpoint = '') private
Builds URL to API endpoints.
Since
1.0.0
Parameters
string $endpoint Endpoint to hit on the API; example "sites" or "sites/{$site_identifier}"
Returns
string
Modifies the endpoint URL for the TrustedLogin service.
Parameters
string $url URL to TrustedLogin API
Definition at line 187 of file Remote.php.
References $base_url, and $url.
Referenced by Remote\send().
check_response_code()
static check_response_code ($api_response) static
Translates response codes to more nuanced error descriptions specific to TrustedLogin.
Parameters
array | WP_Error $api_response Response from HTTP API
Returns
int|WP_Error|null If valid response, the response code ID or null. If error, a WP_Error with a message description.
Definition at line 214 of file Remote.php.
handle_response()
handle_response ($api_response, $required_keys = array())
API Response Handler.
Since
1.0.0
Parameters
array | WP_Error $api_response - the response from HTTP API
array $required_keys If the response JSON must have specific keys in it, pass them here
Returns
array|WP_Error|null If successful response, returns array of JSON data. If failed, returns WP_Error. If
Definition at line 280 of file Remote.php.
Referenced by SiteAccess\revoke().
init()
init ()
Definition at line 54 of file Remote.php.
maybe_send_webhook()
maybe_send_webhook ($data)
POSTs to webhook_url, if defined in the configuration array.
Since
1.0.0
Parameters
array $data {
string $url The site URL as returned by get_site_url()
string $ns Namespace of the plugin
string $action "created", "extended", "logged_in", or "revoked"
string $ref (Optional) Support ticket Reference ID }
Returns
bool|WP_Error False: webhook setting not defined; True: success; WP_Error: error!
Definition at line 76 of file Remote.php.
send()
send ($path, $data, $method = 'POST', $additional_headers = array())
API Function: send the API request.
Since
1.0.0
Parameters
string $path - the path for the REST API request (no initial or trailing slash needed)
array $data Data passed as JSON-encoded body for
string $method
array $additional_headers - any additional headers required for auth/etc
Returns
array|WP_Error wp_remote_request() response or WP_Error if something went wrong
Definition at line 126 of file Remote.php.
References Remote\build_api_url().
Referenced by SiteAccess\revoke().
Field Documentation
$config
Config $config private
Definition at line 39 of file Remote.php.
Referenced by Remote\__construct().
$logging
Logging $logging private
Definition at line 44 of file Remote.php.
Referenced by Remote\__construct().
API_URL
const API_URL = 'https://app.trustedlogin.com/api/v1/'
Definition at line 34 of file Remote.php.
The documentation for this class was generated from the following file:
Remote.php