GravityView: SpeedTrapListener Class Reference
SpeedTrapListener Class Reference
A PHPUnit TestListener that exposes your slowest running tests by outputting results directly to the console.
Public Member Functions
__construct (array $options=array())
Construct a new instance.
addError (PHPUnit_Framework_Test $test, Exception $e, $time)
An error occurred.
addFailure (PHPUnit_Framework_Test $test, PHPUnit_Framework_AssertionFailedError $e, $time)
A failure occurred.
addIncompleteTest (PHPUnit_Framework_Test $test, Exception $e, $time)
Incomplete test.
addRiskyTest (PHPUnit_Framework_Test $test, Exception $e, $time)
Risky test.
addSkippedTest (PHPUnit_Framework_Test $test, Exception $e, $time)
Skipped test.
addWarning (PHPUnit_Framework_Test $test, PHPUnit_Framework_Warning $e, $time)
A warning occurred.
endTest (PHPUnit_Framework_Test $test, $time)
A test ended.
endTestSuite (PHPUnit_Framework_TestSuite $suite)
A test suite ended.
startTest (PHPUnit_Framework_Test $test)
A test started.
startTestSuite (PHPUnit_Framework_TestSuite $suite)
A test suite started.
Protected Member Functions
addSlowTest (PHPUnit_Framework_TestCase $test, $time)
Stores a test as slow.
getHiddenCount ()
Find how many slow tests occurred that won't be shown due to list length.
getReportLength ()
Calculate number of slow tests to report about.
getSlowThreshold (PHPUnit_Framework_TestCase $test)
Get slow test threshold for given test.
hasSlowTests ()
Whether at least one test has been considered slow.
isSlow ($time, $slowThreshold)
Whether the given test execution time is considered slow.
loadOptions (array $options)
Populate options into class internals.
makeLabel (PHPUnit_Framework_TestCase $test)
Label for describing a test.
renderBody ()
Renders slow test report body.
renderFooter ()
Renders slow test report footer.
renderHeader ()
Renders slow test report header.
toMilliseconds ($time)
Convert PHPUnit's reported test time (microseconds) to milliseconds.
Protected Attributes
$reportLength
$slow = array()
$slowThreshold
$suites = 0
Detailed Description
A PHPUnit TestListener that exposes your slowest running tests by outputting results directly to the console.
Definition at line 7 of file speed-trap-listener.php.
Constructor & Destructor Documentation
__construct (array $options = array())
Construct a new instance.
Parameters
array $options
Definition at line 46 of file speed-trap-listener.php.
References $options, and loadOptions().
Member Function Documentation
addError (PHPUnit_Framework_Test $test, Exception $e, $time)
An error occurred.
Parameters
PHPUnit_Framework_Test $test
Exception $e
float $time
Definition at line 58 of file speed-trap-listener.php.
addFailure (PHPUnit_Framework_Test $test, PHPUnit_Framework_AssertionFailedError $e, $time)
A failure occurred.
Parameters
PHPUnit_Framework_Test $test
PHPUnit_Framework_AssertionFailedError $e
float $time
Definition at line 81 of file speed-trap-listener.php.
addIncompleteTest (PHPUnit_Framework_Test $test, Exception $e, $time)
Incomplete test.
Parameters
PHPUnit_Framework_Test $test
Exception $e
float $time
Definition at line 92 of file speed-trap-listener.php.
addRiskyTest (PHPUnit_Framework_Test $test, Exception $e, $time)
Risky test.
Parameters
PHPUnit_Framework_Test $test
Exception $e
float $time
Since
Method available since Release 4.0.0
Definition at line 104 of file speed-trap-listener.php.
addSkippedTest (PHPUnit_Framework_Test $test, Exception $e, $time)
Skipped test.
Parameters
PHPUnit_Framework_Test $test
Exception $e
float $time
Definition at line 115 of file speed-trap-listener.php.
addSlowTest (PHPUnit_Framework_TestCase $test, $time) protected
Stores a test as slow.
Parameters
PHPUnit_Framework_TestCase $test
int $time Test execution time in milliseconds
Definition at line 192 of file speed-trap-listener.php.
References $label, and makeLabel().
Referenced by endTest().
addWarning (PHPUnit_Framework_Test $test, PHPUnit_Framework_Warning $e, $time)
A warning occurred.
Parameters
PHPUnit_Framework_Test $test
PHPUnit_Framework_Warning $e
float $time
Since
Method available since Release 5.1.0
Definition at line 70 of file speed-trap-listener.php.
endTest (PHPUnit_Framework_Test $test, $time)
A test ended.
Parameters
PHPUnit_Framework_Test $test
float $time
Definition at line 134 of file speed-trap-listener.php.
References addSlowTest(), getSlowThreshold(), isSlow(), and toMilliseconds().
endTestSuite (PHPUnit_Framework_TestSuite $suite)
A test suite ended.
Parameters
PHPUnit_Framework_TestSuite $suite
Definition at line 161 of file speed-trap-listener.php.
References hasSlowTests(), renderBody(), renderFooter(), and renderHeader().
getHiddenCount () protected
Find how many slow tests occurred that won't be shown due to list length.
Returns
int Number of hidden slow tests
Definition at line 246 of file speed-trap-listener.php.
References getReportLength().
Referenced by renderFooter().
getReportLength () protected
Calculate number of slow tests to report about.
Returns
int
Definition at line 236 of file speed-trap-listener.php.
Referenced by getHiddenCount(), and renderBody().
getSlowThreshold (PHPUnit_Framework_TestCase $test) protected
Get slow test threshold for given test.
A TestCase can override the suite-wide slow threshold by using the annotation with the threshold value in milliseconds.
The following test will only be considered slow when its execution time reaches 5000ms (5 seconds):
5000 public function testLongRunningProcess() {}
Parameters
PHPUnit_Framework_TestCase $test
Returns
int
Definition at line 320 of file speed-trap-listener.php.
References $slowThreshold.
Referenced by endTest().
hasSlowTests () protected
Whether at least one test has been considered slow.
Returns
bool
Definition at line 204 of file speed-trap-listener.php.
Referenced by endTestSuite().
isSlow ($time, $slowThreshold) protected
Whether the given test execution time is considered slow.
Parameters
int $time Test execution time in milliseconds
int $slowThreshold Test execution time at which a test should be considered slow (milliseconds)
Returns
bool
Definition at line 181 of file speed-trap-listener.php.
References $slowThreshold.
Referenced by endTest().
loadOptions (array $options) protected
Populate options into class internals.
Parameters
array $options
Definition at line 298 of file speed-trap-listener.php.
Referenced by __construct().
makeLabel (PHPUnit_Framework_TestCase $test) protected
Label for describing a test.
Parameters
PHPUnit_Framework_TestCase $test
Returns
string
Definition at line 226 of file speed-trap-listener.php.
Referenced by addSlowTest().
renderBody () protected
Renders slow test report body.
Definition at line 270 of file speed-trap-listener.php.
References $i, $label, $slow, and getReportLength().
Referenced by endTestSuite().
renderFooter () protected
Renders slow test report footer.
Definition at line 286 of file speed-trap-listener.php.
References getHiddenCount().
Referenced by endTestSuite().
renderHeader () protected
Renders slow test report header.
Definition at line 262 of file speed-trap-listener.php.
Referenced by endTestSuite().
startTest (PHPUnit_Framework_Test $test)
A test started.
Parameters
PHPUnit_Framework_Test $test
Definition at line 124 of file speed-trap-listener.php.
startTestSuite (PHPUnit_Framework_TestSuite $suite)
A test suite started.
Parameters
PHPUnit_Framework_TestSuite $suite
Definition at line 151 of file speed-trap-listener.php.
toMilliseconds ($time) protected
Convert PHPUnit's reported test time (microseconds) to milliseconds.
Parameters
float $time
Returns
int
Definition at line 215 of file speed-trap-listener.php.
Referenced by endTest().
Field Documentation
$reportLength protected
Definition at line 32 of file speed-trap-listener.php.
$slow = array() protected
Definition at line 39 of file speed-trap-listener.php.
Referenced by renderBody().
$slowThreshold protected
Definition at line 25 of file speed-trap-listener.php.
Referenced by getSlowThreshold(), and isSlow().
$suites = 0 protected
Definition at line 17 of file speed-trap-listener.php.
The documentation for this class was generated from the following file:
speed-trap-listener.php