GravityView: GravityView_Uninstall_Test Class Reference
GravityView_Uninstall_Test Class Reference
Public Member Functions
_check_deleted_entry_meta ($entry_ids)
Make sure that the GV approval entry meta has been deleted, but not other meta.
_check_deleted_entry_notes ($entry_ids)
There should only be ONE NOTE not deleted.
_check_deleted_options ($should_be_empty=true)
Make sure the settings and transients have been deleted.
_check_entries ($form, $create_count)
No entries should be deleted.
_check_posts ()
_set_up_entry_meta ($entry_ids, $form)
_set_up_expected_options ()
_set_up_gravityview_settings ()
Set delete to true.
_set_up_notes ($entry_ids)
setUp ()
test_fire_everything ()
Public Member Functions inherited from GV_UnitTestCase
setUp ()
tearDown ()
Additional Inherited Members
Data Fields inherited from GV_UnitTestCase
$factory
Detailed Description
Since
1.15 uninstall Class GravityView_Uninstall_Test
Definition at line 10 of file GravityView_Uninstall_Test.php.
Member Function Documentation
_check_deleted_entry_meta ($entry_ids)
Make sure that the GV approval entry meta has been deleted, but not other meta.
Since
1.15
Parameters
$entry_ids
Definition at line 82 of file GravityView_Uninstall_Test.php.
References $value.
Referenced by test_fire_everything().
_check_deleted_entry_notes ($entry_ids)
There should only be ONE NOTE not deleted.
Since
1.15
Parameters
$entry_ids
Definition at line 119 of file GravityView_Uninstall_Test.php.
References $notes, and GravityView_Entry_Notes\get_notes().
Referenced by test_fire_everything().
_check_deleted_options ($should_be_empty = true)
Make sure the settings and transients have been deleted.
Since
1.15
Definition at line 134 of file GravityView_Uninstall_Test.php.
Referenced by test_fire_everything().
_check_entries ($form, $create_count)
No entries should be deleted.
Since
1.15
Parameters
$form
$create_count
Definition at line 109 of file GravityView_Uninstall_Test.php.
References $entries, and $form.
Referenced by test_fire_everything().
_check_posts ()
Since
1.15
Definition at line 95 of file GravityView_Uninstall_Test.php.
Referenced by test_fire_everything().
_set_up_entry_meta ($entry_ids, $form)
Since
1.15
Parameters
$entry_ids
$form
Definition at line 176 of file GravityView_Uninstall_Test.php.
References $form, GravityView_Entry_Approval_Status\APPROVED, and GravityView_Entry_Approval\update_bulk().
Referenced by test_fire_everything().
_set_up_expected_options ()
Since
1.15
Definition at line 237 of file GravityView_Uninstall_Test.php.
Referenced by test_fire_everything().
_set_up_gravityview_settings ()
Set delete to true.
Since
1.15
Definition at line 227 of file GravityView_Uninstall_Test.php.
References GravityView_Settings\get_instance().
Referenced by test_fire_everything().
_set_up_notes ($entry_ids)
Since
1.15
Parameters
$entry_ids
Definition at line 189 of file GravityView_Uninstall_Test.php.
References $notes, GravityView_Entry_Notes\add_note(), and GravityView_Entry_Notes\get_notes().
Referenced by test_fire_everything().
setUp ()
Definition at line 12 of file GravityView_Uninstall_Test.php.
References GV_Unit_Tests_Bootstrap\instance().
test_fire_everything ()
Since
1.15 GravityView_Uninstall::fire_everything() GravityView_Settings::uninstall() GravityView_Settings::uninstall_addon()
Definition at line 25 of file GravityView_Uninstall_Test.php.
References $form, _check_deleted_entry_meta(), _check_deleted_entry_notes(), _check_deleted_options(), _check_entries(), _check_posts(), _set_up_entry_meta(), _set_up_expected_options(), _set_up_gravityview_settings(), _set_up_notes(), GravityView_Settings\get_instance(), gravityview_get_connected_views(), and GVCommon\has_cap().
The documentation for this class was generated from the following file:
GravityView_Uninstall_Test.php