GravityView: License_Handler Class Reference
License_Handler Class Reference
If this file is called directly, abort.
Public Member Functions
check_license ()
Check the GravityView license information.
flush_related_plugins_transient ()
When a plugin is activated or deactivated, delete the cached extensions/plugins used by get_related_plugins_and_extensions()
get_site_data ()
Retrieves site data (plugin versions, integrations, etc) to be sent along with the license check.
license_call ($array=array(), $cap_check=true)
Perform the call to EDD based on the AJAX call or passed data.
license_details ($response=array())
Allow pure HTML in settings fields.
refresh_license_status ()
When the status transient expires (or is deleted on activation), re-check the status.
settings_edd_license_activation ($field, $echo)
setup_edd ()
Include the EDD plugin updater class, if not exists.
strings ($status=NULL, $license_data=null)
Override the text used in the GravityView EDD license Javascript.
Static Public Member Functions
static get ($settings=null)
static get_related_plugins_and_extensions ($implode='< br/>')
Get active GravityView Extensions and Gravity Forms Add-ons to help debug issues.
Data Fields
const author = 'Katz Web Services, Inc.'
const item_id = 17
Post ID on gravityview.co.
const name = 'GravityView'
const related_plugins_key = 'gravityview_related_plugins'
const status_transient_key = 'gravityview_edd-activate_valid'
Name of the transient used to store license status for GV.
const url = 'https://gravityview.co'
Private Member Functions
__construct ($settings)
_get_edd_settings ($action='', $license='')
Generate the array of settings passed to the EDD license call.
_license_get_remote_response ($data, $license='')
Perform the call.
generate_license_box ($message, $class='')
Generate the status message box HTML based on the current status.
get_license_message ($license_data)
Generate the status message displayed in the license field.
get_license_renewal_url ($license_data)
URL to direct license renewal, or if license key is not set, then just the account page.
get_upgrade_html ($upgrades)
Display possible upgrades for a license.
license_call_update_settings ($license_data, $data)
Update the license after fetching it.
Private Attributes
$EDD_SL_Plugin_Updater
$settings
Static Private Attributes
static $__instance
Detailed Description
If this file is called directly, abort.
The class.
Handles everything licensing. Ka-ching!
Definition at line 14 of file future/includes/class-gv-license-handler.php.
Constructor & Destructor Documentation
__construct()
__construct ($settings) private
Definition at line 50 of file future/includes/class-gv-license-handler.php.
References gravityview().
Member Function Documentation
_get_edd_settings()
_get_edd_settings ($action = '', $license = '') private
Generate the array of settings passed to the EDD license call.
Since
1.7.4
Parameters
string $action The action to send to edd, such as check_license
string $license The license key to have passed to EDD
Returns
array
Definition at line 86 of file future/includes/class-gv-license-handler.php.
_license_get_remote_response()
_license_get_remote_response ($data, $license = '') private
Perform the call.
Returns
array|
Definition at line 436 of file future/includes/class-gv-license-handler.php.
References $url, and gravityview().
check_license()
check_license ()
Check the GravityView license information.
Since
1.19.3
Parameters
bool $force Whether to force checking license, even if AJAX
Returns
void
Definition at line 587 of file future/includes/class-gv-license-handler.php.
flush_related_plugins_transient()
flush_related_plugins_transient ()
When a plugin is activated or deactivated, delete the cached extensions/plugins used by get_related_plugins_and_extensions()
See also
get_related_plugins_and_extensions()
Since
1.15
Definition at line 751 of file future/includes/class-gv-license-handler.php.
generate_license_box()
generate_license_box ($message, $class = '') private
Generate the status message box HTML based on the current status.
Since
1.7.4
Parameters
$message
string $class
Returns
string
Definition at line 362 of file future/includes/class-gv-license-handler.php.
References $class, $output, and $template.
get()
static get ($settings = null) static
Returns
The global instance.
Definition at line 69 of file future/includes/class-gv-license-handler.php.
Referenced by GravityView_Migrate\get_redux_license_status().
get_license_message()
get_license_message ($license_data) private
Generate the status message displayed in the license field.
Since
1.7.4
Parameters
$license_data
Returns
string
Definition at line 227 of file future/includes/class-gv-license-handler.php.
References $class.
get_license_renewal_url()
get_license_renewal_url ($license_data) private
URL to direct license renewal, or if license key is not set, then just the account page.
Since
1.13.1
Parameters
object | null $license_data Object with license data
Returns
string Renewal or account URL
Definition at line 415 of file future/includes/class-gv-license-handler.php.
get_related_plugins_and_extensions()
static get_related_plugins_and_extensions ($implode = '<br />') static
Get active GravityView Extensions and Gravity Forms Add-ons to help debug issues.
Since
1.15
Returns
string List of active extensions related to GravityView or Gravity Forms, separated by HTML line breaks
Definition at line 713 of file future/includes/class-gv-license-handler.php.
Referenced by GravityView_Support_Port\_localize_script().
get_site_data()
get_site_data ()
Retrieves site data (plugin versions, integrations, etc) to be sent along with the license check.
Since
1.9 public
Returns
array
Definition at line 644 of file future/includes/class-gv-license-handler.php.
References GV\get().
get_upgrade_html()
get_upgrade_html ($upgrades) private
Display possible upgrades for a license.
Since
1.17
Parameters
array $upgrades Array of upgrade paths, returned from the GV website
Returns
string HTML list of upgrades available for the current license
Definition at line 312 of file future/includes/class-gv-license-handler.php.
References $output.
license_call()
license_call ($array = array(), $cap_check = true)
Perform the call to EDD based on the AJAX call or passed data.
Since
1.7.4
Parameters
array $array { string $license The license key string $edd_action The EDD action to perform, like check_license string $field_id The ID of the field to check boolean $update Whether to update plugin settings. Prevent updating the data by setting an update key to false string $format If object, return the object of the license data. Else, return the JSON-encoded object }
boolean $cap_check Require gravityview_edit_settings capability from current user.
Returns
mixed|string|void
Definition at line 146 of file future/includes/class-gv-license-handler.php.
References GV\get(), and GVCommon\has_cap().
license_call_update_settings()
license_call_update_settings ($license_data, $data) private
Update the license after fetching it.
Parameters
object $license_data
Returns
void
Definition at line 474 of file future/includes/class-gv-license-handler.php.
license_details()
license_details ($response = array())
Allow pure HTML in settings fields.
Since
1.17
Parameters
array $response License response
Returns
string html key of the $field
Definition at line 255 of file future/includes/class-gv-license-handler.php.
References GV\get().
refresh_license_status()
refresh_license_status ()
When the status transient expires (or is deleted on activation), re-check the status.
Since
1.17
Returns
void
Definition at line 556 of file future/includes/class-gv-license-handler.php.
References gravityview().
settings_edd_license_activation()
settings_edd_license_activation ($field, $echo)
Definition at line 484 of file future/includes/class-gv-license-handler.php.
References $class, $field, GRAVITYVIEW_URL, and GVCommon\has_cap().
Referenced by GV\settings_edd_license().
setup_edd()
setup_edd ()
Include the EDD plugin updater class, if not exists.
Since
1.7.4
1.21.5.3 Changed visibility of method to public
Returns
void
Definition at line 117 of file future/includes/class-gv-license-handler.php.
References gravityview(), and GRAVITYVIEW_FILE.
strings()
strings ($status = NULL, $license_data = null)
Override the text used in the GravityView EDD license Javascript.
Parameters
string $status Status to get. If empty, get all strings.
object | array | null $license_data Object with license data, used to generate link to license renewal URL
Returns
string Modified array of content
Definition at line 377 of file future/includes/class-gv-license-handler.php.
References $strings, and GV\get().
Field Documentation
$__instance
$__instance static private
Definition at line 48 of file future/includes/class-gv-license-handler.php.
$EDD_SL_Plugin_Updater
$EDD_SL_Plugin_Updater private
Definition at line 43 of file future/includes/class-gv-license-handler.php.
$settings
$settings private
Definition at line 18 of file future/includes/class-gv-license-handler.php.
Referenced by GV_License_Handler\get_instance().
author
const author = 'Katz Web Services, Inc.'
Definition at line 21 of file future/includes/class-gv-license-handler.php.
item_id
const item_id = 17
Post ID on gravityview.co.
Since
1.15
Definition at line 28 of file future/includes/class-gv-license-handler.php.
name
const name = 'GravityView'
Definition at line 20 of file future/includes/class-gv-license-handler.php.
related_plugins_key
const related_plugins_key = 'gravityview_related_plugins'
Definition at line 40 of file future/includes/class-gv-license-handler.php.
status_transient_key
const status_transient_key = 'gravityview_edd-activate_valid'
Name of the transient used to store license status for GV.
Since
1.17
Definition at line 34 of file future/includes/class-gv-license-handler.php.
url
const url = 'https://gravityview.co'
Definition at line 22 of file future/includes/class-gv-license-handler.php.
The documentation for this class was generated from the following file:
future/includes/class-gv-license-handler.php