GravityView: WP_Customize_Control Class Reference
WP_Customize_Control Class Reference
Customize Control class.
Public Member Functions
__construct ($manager, $id, $args=array())
Constructor.
active ()
Check whether control is active to current Customizer preview.
active_callback ()
Default callback used when invoking WP_Customize_Control::active().
check_capabilities ()
Check if the theme supports the control and check user capabilities.
enqueue ()
Enqueue control related scripts/styles.
get_content ()
Get the control's content for insertion into the Customizer pane.
get_link ($setting_key= 'default')
Get the data link attribute for a setting.
input_attrs ()
Render the custom attributes for the control's input element.
json ()
Get the data to export to the client via JSON.
link ($setting_key= 'default')
Render the data link attribute for the control's input element.
maybe_render ()
Check capabilities and render the control.
print_template ()
Render the control's JS template.
to_json ()
Refresh the parameters passed to the JavaScript via JSON.
value ($setting_key= 'default')
Fetch a setting's value.
Data Fields
$active_callback = ''
$choices = array()
$description = ''
$id
$input_attrs = array()
$instance_number
$json = array()
$label = ''
$manager
$priority = 10
$section = ''
$setting = 'default'
$settings
$type = 'text'
Protected Member Functions
content_template ()
An Underscore (JS) template for this control's content (but not its container).
render ()
Renders the control wrapper and calls $this->render_content() for the internals.
render_content ()
Render the control's content.
Static Protected Attributes
static $instance_count = 0
Detailed Description
Customize Control class.
Since
3.4.0
Definition at line 15 of file class-wp-customize-control.php.
Constructor & Destructor Documentation
__construct ($manager, $id, $args = array())
Constructor.
Supplied $args override class property defaults.
If `$args['settings']` is not defined, use the $id as the setting ID.
Since
3.4.0
Parameters
WP_Customize_Manager $manager Customizer bootstrap instance.
string $id Control ID.
array $args { Optional. Arguments to override class property defaults.
int $instance_number Order in which this instance was created in relation to other instances. WP_Customize_Manager $manager Customizer bootstrap instance. string $id Control ID. array $settings All settings tied to the control. If undefined, $id will be used. string $setting The primary setting for the control (if there is one). Default 'default'. int $priority Order priority to load the control. Default 10. string $section Section the control belongs to. Default empty. string $label Label for the control. Default empty. string $description Description for the control. Default empty. array $choices List of choices for 'radio' or 'select' type controls, where values are the keys, and labels are the values. Default empty array. array $input_attrs List of custom input attributes for control output, where attribute names are the keys and values are the values. Not used for 'checkbox', 'radio', 'select', 'textarea', or 'dropdown-pages' control types. Default empty array. array $json Deprecated. Use {
See also
WP_Customize_Control->json()} instead. string $type Control type. Core controls include 'text', 'checkbox', 'textarea', 'radio', 'select', and 'dropdown-pages'. Additional input types such as 'email', 'url', 'number', 'hidden', and 'date' are supported implicitly. Default 'text'. }
Definition at line 173 of file class-wp-customize-control.php.
References $id, $keys, $manager, $setting, $settings, and active_callback().
Member Function Documentation
active () final
Check whether control is active to current Customizer preview.
Since
4.0.0 public
Returns
bool Whether the control is active to the current preview.
Filter response of WP_Customize_Control::active().
Since
4.0.0
Parameters
bool $active Whether the Customizer control is active.
WP_Customize_Control $control WP_Customize_Control instance.
Definition at line 221 of file class-wp-customize-control.php.
References active_callback(), and apply_filters().
Referenced by to_json().
active_callback ()
Default callback used when invoking WP_Customize_Control::active().
Subclasses can override this with their specific logic, or they may provide an 'active_callback' argument to the constructor.
Since
4.0.0 public
Returns
true Always true.
Definition at line 249 of file class-wp-customize-control.php.
Referenced by __construct(), and active().
check_capabilities () final
Check if the theme supports the control and check user capabilities.
Since
3.4.0
Returns
bool False if theme doesn't support the control or user doesn't have the required permissions, otherwise true.
Definition at line 308 of file class-wp-customize-control.php.
References $section, and $setting.
Referenced by maybe_render().
content_template () protected
An Underscore (JS) template for this control's content (but not its container).
Class variables for this control class are available in the data JS object; export custom variables by overriding {
See also
WP_Customize_Control::to_json()}.
WP_Customize_Control::print_template()
Since
4.1.0
Definition at line 575 of file class-wp-customize-control.php.
Referenced by print_template().
enqueue ()
Enqueue control related scripts/styles.
Since
3.4.0
Definition at line 211 of file class-wp-customize-control.php.
get_content () final
Get the control's content for insertion into the Customizer pane.
Since
4.1.0
Returns
string Contents of the control.
Definition at line 328 of file class-wp-customize-control.php.
References maybe_render().
Referenced by to_json().
get_link ($setting_key = 'default')
Get the data link attribute for a setting.
Since
3.4.0
Parameters
string $setting_key
Returns
string Data link parameter, if $setting_key is a valid setting, empty string otherwise.
Definition at line 390 of file class-wp-customize-control.php.
References esc_attr().
Referenced by link(), and render_content().
input_attrs ()
Render the custom attributes for the control's input element.
Since
4.0.0 public
Definition at line 415 of file class-wp-customize-control.php.
References $value, and esc_attr().
Referenced by render_content().
json ()
Get the data to export to the client via JSON.
Since
4.1.0
Returns
array Array of parameters passed to the JavaScript.
Definition at line 296 of file class-wp-customize-control.php.
References $json, and to_json().
Referenced by WP_Customize_Upload_Control\to_json(), WP_Widget_Form_Customize_Control\to_json(), WP_Widget_Area_Customize_Control\to_json(), WP_Customize_Theme_Control\to_json(), WP_Customize_Nav_Menu_Location_Control\to_json(), WP_Customize_Color_Control\to_json(), WP_Customize_Cropped_Image_Control\to_json(), WP_Customize_Media_Control\to_json(), and to_json().
link ($setting_key = 'default')
Render the data link attribute for the control's input element.
Since
3.4.0 WP_Customize_Control::get_link()
Parameters
string $setting_key
Definition at line 405 of file class-wp-customize-control.php.
References get_link().
Referenced by WP_Customize_Nav_Menu_Location_Control\render_content(), and render_content().
maybe_render () final
Check capabilities and render the control.
Since
3.4.0 WP_Customize_Control::render()
Fires just before the current Customizer control is rendered.
Since
3.4.0
Parameters
WP_Customize_Control $this WP_Customize_Control instance.
Fires just before a specific Customizer control is rendered.
The dynamic portion of the hook name, $this->id, refers to the control ID.
Since
3.4.0
Parameters
WP_Customize_Control $this {
See also
WP_Customize_Control} instance.
Definition at line 340 of file class-wp-customize-control.php.
References check_capabilities(), do_action(), and render().
Referenced by get_content().
print_template () final
Render the control's JS template.
This function is only run for control types that have been registered with {
See also
WP_Customize_Manager::register_control_type()}.
In the future, this will also print the template for the control's container element and be override-able.
Since
4.1.0
Definition at line 557 of file class-wp-customize-control.php.
References content_template().
render () protected
Renders the control wrapper and calls $this->render_content() for the internals.
Since
3.4.0
Definition at line 373 of file class-wp-customize-control.php.
References $class, $id, $type, li, render_content(), and str_replace.
Referenced by maybe_render().
render_content () protected
Render the control's content.
Allows the content to be overriden without having to rewrite the wrapper in $this->render().
Supports basic input types text, checkbox, textarea, radio, select and dropdown-pages. Additional input types such as email, url, number, hidden and date are supported implicitly.
Control content can alternately be rendered in JS. See {
See also
WP_Customize_Control::print_template()}.
Since
3.4.0
Definition at line 433 of file class-wp-customize-control.php.
References $description, $id, $label, $name, $value, __, checked(), endforeach, endif, esc_attr(), esc_html, esc_textarea(), get_link(), input, input_attrs(), label, link(), name, selected(), str_replace, textarea, value(), and wp_dropdown_pages().
Referenced by render().
to_json ()
Refresh the parameters passed to the JavaScript via JSON.
Since
3.4.0
Definition at line 273 of file class-wp-customize-control.php.
References $description, $instance_number, $label, $priority, $section, $setting, $type, active(), get_content(), and json().
Referenced by json().
value ($setting_key = 'default') final
Fetch a setting's value.
Grabs the main setting by default.
Since
3.4.0
Parameters
string $setting_key
Returns
mixed The requested setting's value, if the setting exists.
Definition at line 262 of file class-wp-customize-control.php.
Referenced by WP_Customize_Nav_Menu_Item_Control\content_template(), WP_Customize_Header_Image_Control\get_current_image_src(), WP_Customize_Header_Image_Control\print_header_image_template(), WP_Customize_Nav_Menu_Location_Control\render_content(), render_content(), WP_Customize_Upload_Control\to_json(), and WP_Customize_Media_Control\to_json().
Field Documentation
$active_callback = ''
Definition at line 131 of file class-wp-customize-control.php.
$choices = array()
Definition at line 97 of file class-wp-customize-control.php.
$description = ''
Definition at line 89 of file class-wp-customize-control.php.
Referenced by WP_Customize_Nav_Menu_Control\content_template(), WP_Customize_Nav_Menu_Location_Control\render_content(), render_content(), and to_json().
$id
Definition at line 49 of file class-wp-customize-control.php.
Referenced by WP_Customize_Image_Control\__construct(), WP_Customize_Color_Control\__construct(), WP_Customize_Site_Icon_Control\__construct(), WP_Customize_Nav_Menu_Item_Control\__construct(), WP_Customize_Media_Control\__construct(), __construct(), render(), WP_Widget_Area_Customize_Control\render_content(), and render_content().
$input_attrs = array()
Definition at line 103 of file class-wp-customize-control.php.
$instance_count = 0 static protected
Definition at line 28 of file class-wp-customize-control.php.
$instance_number
Definition at line 37 of file class-wp-customize-control.php.
Referenced by to_json().
$json = array()
Definition at line 110 of file class-wp-customize-control.php.
Referenced by json().
$label = ''
Definition at line 83 of file class-wp-customize-control.php.
Referenced by WP_Customize_Nav_Menu_Location_Control\render_content(), render_content(), and to_json().
$manager
Definition at line 43 of file class-wp-customize-control.php.
Referenced by WP_Customize_Background_Image_Control\__construct(), WP_Customize_Header_Image_Control\__construct(), WP_Customize_Image_Control\__construct(), WP_Customize_Color_Control\__construct(), WP_Customize_Site_Icon_Control\__construct(), WP_Customize_Nav_Menu_Item_Control\__construct(), WP_Customize_Media_Control\__construct(), and __construct().
$priority = 10
Definition at line 71 of file class-wp-customize-control.php.
Referenced by to_json().
$section = ''
Definition at line 77 of file class-wp-customize-control.php.
Referenced by check_capabilities(), and to_json().
$setting = 'default'
Definition at line 65 of file class-wp-customize-control.php.
Referenced by __construct(), check_capabilities(), and to_json().
$settings
Definition at line 57 of file class-wp-customize-control.php.
Referenced by __construct().
$type = 'text'
Definition at line 116 of file class-wp-customize-control.php.
Referenced by render(), and to_json().
The documentation for this class was generated from the following file:
class-wp-customize-control.php