GravityView: WP_Widget_Recent_Posts Class Reference
WP_Widget_Recent_Posts Class Reference
Core class used to implement a Recent Posts widget.
Public Member Functions
__construct ()
Sets up a new Recent Posts widget instance.
form ($instance)
Outputs the settings form for the Recent Posts widget.
update ($new_instance, $old_instance)
Handles updating the settings for the current Recent Posts widget instance.
widget ($args, $instance)
Outputs the content for the current Recent Posts widget instance.
Public Member Functions inherited from WP_Widget
__construct ($id_base, $name, $widget_options=array(), $control_options=array())
PHP5 constructor.
_get_display_callback ()
Retrieves the widget display callback.
_get_form_callback ()
Retrieves the form callback.
_get_update_callback ()
Retrieves the widget update callback.
_register ()
Register all widget instances of this widget class.
_register_one ($number=-1)
Register an instance of the widget class.
_set ($number)
Set the internal order number for the widget instance.
display_callback ($args, $widget_args=1)
Generate the actual widget content (Do NOT override).
form ($instance)
Outputs the settings update form.
form_callback ($widget_args=1)
Generate the widget control form (Do NOT override).
get_field_id ($field_name)
Constructs id attributes for use in {.
get_field_name ($field_name)
Constructs name attributes for use in form() fields.
get_settings ()
Get the settings for all instances of the widget class.
is_preview ()
Determine whether the current request is inside the Customizer preview.
save_settings ($settings)
Save the settings for all instances of the widget class.
update ($new_instance, $old_instance)
Updates a particular instance of a widget.
update_callback ($deprecated=1)
Deal with changed settings (Do NOT override).
widget ($args, $instance)
Echoes the widget content.
WP_Widget ($id_base, $name, $widget_options=array(), $control_options=array())
PHP4 constructor.
Additional Inherited Members
Data Fields inherited from WP_Widget
$control_options
$id = false
$id_base
$name
$number = false
$updated = false
$widget_options
Detailed Description
Core class used to implement a Recent Posts widget.
Since
2.8.0
See also
WP_Widget
Definition at line 17 of file class-wp-widget-recent-posts.php.
Constructor & Destructor Documentation
__construct ()
Sets up a new Recent Posts widget instance.
Since
2.8.0 public
Definition at line 25 of file class-wp-widget-recent-posts.php.
References __.
Member Function Documentation
form ($instance)
Outputs the settings form for the Recent Posts widget.
Since
2.8.0 public
Parameters
array $instance Current settings.
Definition at line 123 of file class-wp-widget-recent-posts.php.
References WP_Widget\$number, $title, _e, absint(), checked(), esc_attr(), input, label, name, and size.
update ($new_instance, $old_instance)
Handles updating the settings for the current Recent Posts widget instance.
Since
2.8.0 public
Parameters
array $new_instance New settings for this instance as input by the user via WP_Widget::form().
array $old_instance Old settings for this instance.
Returns
array Updated settings to save.
Definition at line 107 of file class-wp-widget-recent-posts.php.
References sanitize_text_field().
widget ($args, $instance)
Outputs the content for the current Recent Posts widget instance.
Since
2.8.0 public
Parameters
array $args Display arguments including 'before_title', 'after_title', 'before_widget', and 'after_widget'.
array $instance Settings for the current Recent Posts widget instance.
This filter is documented in wp-includes/widgets/class-wp-widget-pages.php
Filter the arguments for the Recent Posts widget.
Since
3.4.0
See also
WP_Query::get_posts()
Parameters
array $args An array of arguments used to retrieve the recent posts.
Definition at line 41 of file class-wp-widget-recent-posts.php.
References WP_Widget\$id, WP_Widget\$number, $title, __, absint(), apply_filters(), endif, endwhile, get_the_date(), get_the_title(), li, the_ID(), the_title(), and wp_reset_postdata().
The documentation for this class was generated from the following file:
class-wp-widget-recent-posts.php