GravityView: HelpScout Class Reference
HelpScout Class Reference
Public Member Functions
enqueue_beacon_script ($scripts)
Outputs inline JS code that initializes the HS beacon.
get_beacon_configuration ()
Returns HS beacon configuration options.
get_beacon_label_translations ()
Returns translated labels.
should_display_beacon ()
Determines if the HS beacon should be displayed.
Static Public Member Functions
static get_instance ()
Returns class instance.
Data Fields
const HASH_KEY = 't4MTtLRuIH74gBuQ/2OVpj0NscYAjdg9nY1rw67PiT8='
const HS_BEACON_KEY = 'e899c3af-bfb9-479a-9579-38e758664fb7'
Private Member Functions
__construct ()
Static Private Attributes
static $_instance
Detailed Description
Definition at line 17 of file HelpScout.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Definition at line 29 of file HelpScout.php.
Member Function Documentation
enqueue_beacon_script()
enqueue_beacon_script ($scripts)
Outputs inline JS code that initializes the HS beacon.
Since
1.0.0
Parameters
array $scripts
Returns
array
Definition at line 57 of file HelpScout.php.
References HelpScout\get_beacon_configuration(), and HelpScout\should_display_beacon().
get_beacon_configuration()
get_beacon_configuration ()
Returns HS beacon configuration options.
Since
1.0.0
Returns
array
Runs Filter:
gk/foundation/integrations/helpscout/configuration Modified HS beacon configuration.
Since
1.0.0
Parameters
array $beacon_configuration Beacon configuration.
Definition at line 127 of file HelpScout.php.
References Arr\get(), and HelpScout\get_beacon_label_translations().
Referenced by HelpScout\enqueue_beacon_script().
get_beacon_label_translations()
get_beacon_label_translations ()
Returns translated labels.
These combines default HS translations with custom GravityView translations.
Since
1.0.0
See also
https://github.com/gravityview/GravityView/blob/3a999a0ce8d96cd63386c575fd3199730ded6491/includes/admin/class-gravityview-support-port.php#L137-L156
https://developer.helpscout.com/beacon-2/web/javascript-api/#translate-options
Returns
array
Definition at line 194 of file HelpScout.php.
Referenced by HelpScout\get_beacon_configuration().
get_instance()
static get_instance () static
Returns class instance.
Since
1.0.0
Returns
TrustedLogin
Definition at line 40 of file HelpScout.php.
Referenced by Core\init().
should_display_beacon()
should_display_beacon ()
Determines if the HS beacon should be displayed.
Since
1.0.0
Returns
bool
: Possibly implement additional checks as it's done in GravityView:
If the user doesn't have the gravityview_support_port capability, returns false; then If global setting is "hide", returns false; then If user preference is not set, return global setting; then If user preference is set, return that setting.
Runs Filter:
gk/foundation/integrations/helpscout/display Toggles whether HS beacon should be displayed. Return "true" to short-circuit all other checks.
Since
1.0.0
Parameters
bool $display_beacon Whether to display the beacon.
string | null $page Current page ($_REQUEST['page']).
string | null $post_type Current post type ($_REQUEST['post_type']).
Definition at line 83 of file HelpScout.php.
References Arr\get().
Referenced by HelpScout\enqueue_beacon_script().
Field Documentation
$_instance
$_instance static private
Definition at line 27 of file HelpScout.php.
HASH_KEY
const HASH_KEY = 't4MTtLRuIH74gBuQ/2OVpj0NscYAjdg9nY1rw67PiT8='
Definition at line 20 of file HelpScout.php.
HS_BEACON_KEY
const HS_BEACON_KEY = 'e899c3af-bfb9-479a-9579-38e758664fb7'
Definition at line 18 of file HelpScout.php.
The documentation for this class was generated from the following file:
HelpScout.php