GravityView: WP_Session_Tokens Class Reference
WP_Session_Tokens Class Reference
Abstract class for managing user session tokens.
Public Member Functions
create ($expiration)
Generate a session token and attach session information to it.
destroy ($token)
Destroy a session token.
destroy_all ()
Destroy all session tokens for a user.
destroy_others ($token_to_keep)
Destroy all session tokens for this user, except a single token, presumably the one in use.
get ($token)
Get a user's session.
get_all ()
Retrieve all sessions of a user.
update ($token, $session)
Update a session token.
verify ($token)
Validate a user's session token as authentic.
Static Public Member Functions
static destroy_all_for_all_users ()
Destroy all session tokens for all users.
static drop_sessions ()
This static method should destroy all session tokens for all users.
static get_instance ($user_id)
Get a session token manager instance for a user.
Protected Member Functions
__construct ($user_id)
Protected constructor.
destroy_all_sessions ()
This method should destroy all sessions for a user.
destroy_other_sessions ($verifier)
This method should destroy all session tokens for this user, except a single session passed.
get_session ($verifier)
This method should look up a session by its verifier (token hash).
get_sessions ()
This method should retrieve all sessions of a user, keyed by verifier.
is_still_valid ($session)
Determine whether a session token is still valid, based on expiration.
update_session ($verifier, $session=null)
This method should update a session by its verifier.
Protected Attributes
$user_id
Private Member Functions
hash_token ($token)
Hashes a session token for storage.
Detailed Description
Abstract class for managing user session tokens.
Since
4.0.0
Definition at line 7 of file session.php.
Constructor & Destructor Documentation
__construct ($user_id) protected
Protected constructor.
Since
4.0.0
Parameters
int $user_id User whose session to manage.
Definition at line 25 of file session.php.
References $user_id.
Member Function Documentation
create ($expiration) final
Generate a session token and attach session information to it.
A session token is a long, random string. It is used in a cookie link that cookie to an expiration time and to ensure the cookie becomes invalidated upon logout.
This function generates a token and stores it with the associated expiration time (and potentially other session information via the attach_session_information filter).
Since
4.0.0 public
Parameters
int $expiration Session expiration timestamp.
Returns
string Session token.
Filter the information attached to the newly created session.
Could be used in the future to attach information such as IP address or user agent to a session.
Since
4.0.0
Parameters
array $session Array of extra data.
int $user_id User ID.
Definition at line 119 of file session.php.
References $_SERVER, apply_filters(), update(), and wp_unslash().
destroy ($token) final
Destroy a session token.
Since
4.0.0 public
Parameters
string $token Session token to destroy.
Definition at line 176 of file session.php.
References hash_token(), null, and update_session().
destroy_all () final
Destroy all session tokens for a user.
Since
4.0.0 public
Definition at line 220 of file session.php.
References destroy_all_sessions().
static destroy_all_for_all_users () static final
Destroy all session tokens for all users.
Since
4.0.0 public
Definition at line 231 of file session.php.
References apply_filters().
destroy_all_sessions () abstract protected
This method should destroy all sessions for a user.
Since
4.0.0 protected
Referenced by destroy_all(), and destroy_others().
destroy_other_sessions ($verifier) abstract protected
This method should destroy all session tokens for this user, except a single session passed.
Since
4.0.0 protected
Parameters
string $verifier Verifier of the session to keep.
Referenced by destroy_others().
destroy_others ($token_to_keep) final
Destroy all session tokens for this user, except a single token, presumably the one in use.
Since
4.0.0 public
Parameters
string $token_to_keep Session token to keep.
Definition at line 190 of file session.php.
References destroy_all_sessions(), destroy_other_sessions(), get_session(), and hash_token().
static drop_sessions () static
This static method should destroy all session tokens for all users.
Since
4.0.0 public
Definition at line 308 of file session.php.
get ($token) final
Get a user's session.
Since
4.0.0 public
Parameters
string $token Session token
Returns
array User session
Definition at line 81 of file session.php.
References get_session(), and hash_token().
get_all () final
Retrieve all sessions of a user.
Since
4.0.0 public
Returns
array Sessions of a user.
Definition at line 244 of file session.php.
References get_sessions().
static get_instance ($user_id) static final
Get a session token manager instance for a user.
This method contains a filter that allows a plugin to swap out the session manager for a subclass of WP_Session_Tokens.
Since
4.0.0 public
Parameters
int $user_id User whose session to manage.
Filter the session token manager used.
Since
4.0.0
Parameters
string $session Name of class to use as the manager. Default 'WP_User_Meta_Session_Tokens'.
Definition at line 41 of file session.php.
References $user_id, and apply_filters().
Referenced by wp_ajax_destroy_sessions(), wp_destroy_all_sessions(), wp_destroy_current_session(), wp_destroy_other_sessions(), and wp_get_all_sessions().
get_session ($verifier) abstract protected
This method should look up a session by its verifier (token hash).
Since
4.0.0 protected
Parameters
string $verifier Verifier of the session to retrieve.
Returns
array|null The session, or null if it does not exist.
Referenced by destroy_others(), get(), and verify().
get_sessions () abstract protected
This method should retrieve all sessions of a user, keyed by verifier.
Since
4.0.0 protected
Returns
array Sessions of a user, keyed by verifier.
Referenced by get_all().
hash_token ($token) final private
Hashes a session token for storage.
Since
4.0.0 private
Parameters
string $token Session token to hash.
Returns
string A hash of the session token (a verifier).
Definition at line 63 of file session.php.
Referenced by destroy(), destroy_others(), get(), update(), and verify().
is_still_valid ($session) final protected
Determine whether a session token is still valid, based on expiration.
Since
4.0.0 protected
Parameters
array $session Session to check.
Returns
bool Whether session is valid.
Definition at line 210 of file session.php.
update ($token, $session) final
Update a session token.
Since
4.0.0 public
Parameters
string $token Session token to update.
array $session Session information.
Definition at line 163 of file session.php.
References hash_token(), and update_session().
Referenced by create().
update_session ($verifier, $session = null) abstract protected
This method should update a session by its verifier.
Omitting the second argument should destroy the session.
Since
4.0.0 protected
Parameters
string $verifier Verifier of the session to update.
array $session Optional. Session. Omitting this argument destroys the session.
Referenced by destroy(), and update().
verify ($token) final
Validate a user's session token as authentic.
Checks that the given token is present and hasn't expired.
Since
4.0.0 public
Parameters
string $token Token to verify.
Returns
bool Whether the token is valid for the user.
Definition at line 97 of file session.php.
References get_session(), and hash_token().
Field Documentation
$user_id protected
Definition at line 16 of file session.php.
Referenced by __construct(), and get_instance().
The documentation for this class was generated from the following file:
session.php