GravityView: GravityView_Plugin_and_Theme_Hooks Class Reference
GravityView_Plugin_and_Theme_Hooks Class Reference
Abstract class that makes it easy for plugins and themes to register no-conflict scripts and styles, as well as add post meta keys for GravityView to parse when checking for the existence of shortcodes in content.
Public Member Functions
__construct ()
GravityView_Theme_Support constructor.
__construct ()
GravityView_Theme_Support constructor.
merge_content_meta_keys ($meta_keys=array(), $post_id=0)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_content_meta_keys ($meta_keys=array(), $post_id=0)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_noconflict_scripts ($handles)
Merge plugin or theme scripts with existing no-conflict scripts.
merge_noconflict_scripts ($handles)
Merge plugin or theme scripts with existing no-conflict scripts.
merge_noconflict_styles ($handles)
Merge plugin or theme styles with existing no-conflict styles.
merge_noconflict_styles ($handles)
Merge plugin or theme styles with existing no-conflict styles.
merge_post_type_support ($supports=array(), $is_hierarchical=false)
Merge plugin or theme post type support definitions with existing support values.
merge_post_type_support ($supports=array(), $is_hierarchical=false)
Merge plugin or theme post type support definitions with existing support values.
Protected Member Functions
add_hooks ()
Add filters for meta key and script/style handles, if defined.
add_hooks ()
Add filters for meta key and script/style handles, if defined.
Protected Attributes
$class_name = false
string Optional.
$constant_name = false
string Optional.
$content_meta_keys = array()
Define the keys to be parsed by the gravityview/data/parse/meta_keys hook.
$function_name = false
string Optional.
$post_type_support = array()
Define features in the admin editor used by the theme or plugin to be used when registering the GravityView post type.
$script_handles = array()
Define script handles used by the theme or plugin to be parsed by the gravityview/data/parse/meta_keys hook.
$style_handles = array()
Define style handles used by the theme or plugin to be parsed by the gravityview/data/parse/meta_keys hook.
Private Member Functions
maybe_add_hooks ()
Check whether plugin or theme exists.
maybe_add_hooks ()
Check whether plugin or theme exists.
Detailed Description
Abstract class that makes it easy for plugins and themes to register no-conflict scripts and styles, as well as add post meta keys for GravityView to parse when checking for the existence of shortcodes in content.
Since
1.15.2
Definition at line 22 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
Constructor & Destructor Documentation
__construct ()
GravityView_Theme_Support constructor.
Returns
void
Definition at line 78 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
References maybe_add_hooks().
__construct ()
GravityView_Theme_Support constructor.
Returns
void
Definition at line 78 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
References maybe_add_hooks().
Member Function Documentation
add_hooks () protected
Add filters for meta key and script/style handles, if defined.
Since
1.15.2
Returns
void
Definition at line 106 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
Referenced by maybe_add_hooks().
add_hooks () protected
Add filters for meta key and script/style handles, if defined.
Since
1.15.2
Returns
void
Definition at line 106 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
maybe_add_hooks () private
Check whether plugin or theme exists.
If so, add hooks. This is to reduce load time, since apply_filters() isn't free. If the class name or function name or constant exists for a plugin or theme, add hooks If the class/function/definition aren't speicifed add the hooks
Since
1.15.2
Returns
void
Definition at line 91 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
References add_hooks().
Referenced by __construct().
maybe_add_hooks () private
Check whether plugin or theme exists.
If so, add hooks. This is to reduce load time, since apply_filters() isn't free. If the class name or function name or constant exists for a plugin or theme, add hooks If the class/function/definition aren't speicifed add the hooks
Since
1.15.2
Returns
void
Definition at line 91 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
References add_hooks().
merge_content_meta_keys ($meta_keys = array(), $post_id = 0)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
Since
1.15.2
Parameters
array $handles Array of meta keys to check for existence of shortcodes
int $post_id The ID being checked by GravityView
Returns
array Meta key array, merged with existing meta keys
Definition at line 177 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
merge_content_meta_keys ($meta_keys = array(), $post_id = 0)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
Since
1.15.2
Parameters
array $handles Array of meta keys to check for existence of shortcodes
int $post_id The ID being checked by GravityView
Returns
array Meta key array, merged with existing meta keys
Definition at line 177 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
merge_noconflict_scripts ($handles)
Merge plugin or theme scripts with existing no-conflict scripts.
Since
1.15.2
Parameters
array $handles Array of script handles, as registered with WordPress
Returns
array Handles, merged with existing scripts
Definition at line 162 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
merge_noconflict_scripts ($handles)
Merge plugin or theme scripts with existing no-conflict scripts.
Since
1.15.2
Parameters
array $handles Array of script handles, as registered with WordPress
Returns
array Handles, merged with existing scripts
Definition at line 162 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
merge_noconflict_styles ($handles)
Merge plugin or theme styles with existing no-conflict styles.
Since
1.15.2
Parameters
array $handles Array of style handles, as registered with WordPress
Returns
array Handles, merged with existing styles
Definition at line 148 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
merge_noconflict_styles ($handles)
Merge plugin or theme styles with existing no-conflict styles.
Since
1.15.2
Parameters
array $handles Array of style handles, as registered with WordPress
Returns
array Handles, merged with existing styles
Definition at line 148 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
merge_post_type_support ($supports = array(), $is_hierarchical = false)
Merge plugin or theme post type support definitions with existing support values.
Since
1.15.2
Parameters
array $supports Array of features associated with a functional area of the edit screen.
boolean $is_hierarchical Do Views support parent/child relationships? See gravityview_is_hierarchical filter.
Returns
array Array of features associated with a functional area of the edit screen, merged with existing values
Definition at line 134 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
merge_post_type_support ($supports = array(), $is_hierarchical = false)
Merge plugin or theme post type support definitions with existing support values.
Since
1.15.2
Parameters
array $supports Array of features associated with a functional area of the edit screen.
boolean $is_hierarchical Do Views support parent/child relationships? See gravityview_is_hierarchical filter.
Returns
array Array of features associated with a functional area of the edit screen, merged with existing values
Definition at line 134 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
Field Documentation
$class_name = false protected
string Optional.
Class that should be exist in a plugin or theme. Used to check whether plugin is active.
Since
1.15.2
Definition at line 28 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
$constant_name = false protected
string Optional.
Constant that should be defined by plugin or theme. Used to check whether plugin is active.
Since
1.15.2
Definition at line 40 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
$content_meta_keys = array() protected
Define the keys to be parsed by the gravityview/data/parse/meta_keys hook.
See also
GravityView_View_Data::parse_post_meta
Since
1.15.2 array
Definition at line 48 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
$function_name = false protected
string Optional.
Function that should be exist in a plugin or theme. Used to check whether plugin is active.
Since
1.15.2
Definition at line 34 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
$post_type_support = array() protected
Define features in the admin editor used by the theme or plugin to be used when registering the GravityView post type.
See also
GravityView_Post_Types::init_post_types
Since
1.15.2 array
Definition at line 72 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
$script_handles = array() protected
Define script handles used by the theme or plugin to be parsed by the gravityview/data/parse/meta_keys hook.
See also
GravityView_Admin::remove_conflicts
Since
1.15.2 array
Definition at line 56 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
$style_handles = array() protected
Define style handles used by the theme or plugin to be parsed by the gravityview/data/parse/meta_keys hook.
See also
GravityView_Admin::remove_conflicts
Since
1.15.2 array
Definition at line 64 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php.
The documentation for this class was generated from the following file:
Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/abstract-gravityview-plugin-and-theme-hooks.php