GravityView: GFFeedAddOn Class Reference
GFFeedAddOn Class Reference
Public Member Functions
add_default_feed_settings_fields_props ($fields)
add_paypal_settings ($feed, $form)
ajax_toggle_is_active ()
can_create_feed ()
Override this function to prevent the feed creation UI from being rendered.
can_duplicate_feed ($id)
Override this function to allow the feed to being duplicated.
configure_addon_message ()
delay_feed ($feed, $entry, $form)
delete_feed ($id)
delete_feeds ($form_id=null)
duplicate_feed ($id, $new_form_id=false)
Duplicates the feed.
feed_list_message ()
Override this function to force a message to be displayed in the feed list (instead of data).
feed_list_no_item_message ()
Override this function to change the message that is displayed when the feed list is empty.
feed_list_page ($form=null)
feed_list_title ()
feed_settings_fields ()
feed_settings_title ()
form_settings ($form)
form_settings_header ()
form_settings_init ()
form_settings_sections ()
form_settings_title ()
get_active_feeds ($form_id=null)
get_column_value ($item, $column)
get_current_feed ()
get_current_feed_id ()
get_default_feed_name ()
get_feed ($id)
get_feed_settings_fields ()
get_feed_table ($form)
get_feeds ($form_id=null)
get_feeds_by_entry ($entry_id)
get_feeds_by_slug ($slug, $form_id=null)
get_paypal_feed ($form_id, $entry)
get_single_submission_feed ($entry=false, $form=false)
has_feed ($form_id, $meets_conditional_logic=null)
has_paypal_payment ($feed, $form, $entry)
init ()
init_admin ()
init_ajax ()
insert_feed ($form_id, $is_active, $meta)
is_delayed ($paypal_feed)
is_delayed_payment ($entry, $form, $is_delayed)
is_detail_page ()
is_feed_condition_met ($feed, $form, $entry)
is_feed_list_page ()
is_unique_feed_name ($name, $form_id)
maybe_process_feed ($entry, $form)
notification_events ($events, $form)
Add notifications events supported by Add-On to notification events list.
paypal_fulfillment ($entry, $paypal_config, $transaction_id, $amount)
post_form_duplicated ($form_id, $new_id)
Maybe duplicate feeds when a form is duplicated.
process_feed ($feed, $entry, $form)
save_paypal_settings ($feed)
scripts ()
settings ($sections)
supported_notification_events ($form)
Retrieves notification events supported by Add-On.
update_feed_active ($id, $is_active)
update_feed_meta ($id, $meta)
Public Member Functions inherited from GFAddOn
__construct ()
Class constructor which hooks the instance into the WordPress init action.
add_form_settings_menu ($tabs, $form_id)
Add the form settings tab.
add_note ($entry_id, $note, $note_type=null)
app_settings_fields ()
Override this function to specify the settings fields to be rendered on the plugin settings page.
app_settings_tab ()
app_tab_page ()
Handles the rendering of app menu items that implement the tabs UI.
build_choices ($key_value_pairs)
create_app_menu ()
Creates a top level app menu.
create_plugin_page_menu ($menus)
Creates plugin page menu item Target of gform_addon_navigation filter.
enqueue_preview_styles ($preview_styles, $form)
Target of gform_preview_styles.
enqueue_print_styles ($print_styles, $form)
Target of gform_print_styles.
enqueue_scripts ($form= '', $is_ajax=false)
Target of admin_enqueue_scripts and gform_enqueue_scripts hooks.
field_map_table_header ()
filter_settings ($fields, $settings)
Filter settings fields.
form_settings_page ()
Renders the form settings page.
get_app_settings_tabs ()
Returns the tabs for the settings app menu item.
get_base_path ($full_path= '')
Returns the physical path of the plugins root folder.
get_base_url ($full_path= '')
Returns the url of the root folder of the current Add-On.
get_field_value ($form, $entry, $field_id)
Returns the value of the selected field.
get_first_field_by_type ($field_type, $subfield_id=null, $form_id=null, $return_first_only=true)
Returns the field ID of the first field of the desired type.
get_form_fields_as_choices ($form, $args=array())
Retrieve an array of form fields formatted for select, radio and checkbox settings fields.
get_locking_config ()
Returns the configuration for locking.
get_locking_object_id ()
Returns the ID of the object to be locked.
get_mapped_field_name ($parent_field, $field_name)
get_plugin_setting ($setting_name)
Get plugin setting Returns the plugin setting specified by the $setting_name parameter.
get_plugin_settings ()
Returns the currently saved plugin settings.
get_results_page_config ()
Returns the configuration for the results page.
get_select_options ($choices, $selected_value)
Prepares an HTML string of options for a drop down field.
has_app_menu ()
Checks whether the current Add-On has a top level app menu.
has_app_settings ()
Checks whether the current Add-On has a settings page.
has_deprecated_elements ()
has_plugin_settings_page ()
Checks whether the current Add-On has a settings page.
init ()
Plugin starting point.
is_gravityforms_installed ()
Checks whether the Gravity Forms is installed.
is_gravityforms_supported ($min_gravityforms_version= '')
Checks whether the current version of Gravity Forms is supported.
is_locking_edit_page ()
Returns TRUE if the current page is the edit page.
is_locking_list_page ()
Returns TRUE if the current page is the list page.
is_locking_view_page ()
Returns TRUE if the current page is the view page.
is_object_locked ($object_id)
Checked whether an object is locked.
list_row_class ($object_id, $echo=true)
Outputs class for the row for the specified Object ID on the list page.
load_screen_options ()
Override this function to load custom screen options.
lock_info ($object_id, $echo=true)
Outputs information about the user currently editing the specified object.
log_debug ($message)
Writes an error message to the Gravity Forms log.
log_error ($message)
Writes an error message to the Gravity Forms log.
maybe_override_field_value ($field_value, $form, $entry, $field_id)
Enables use of the gform_SLUG_field_value filter to override the field value.
maybe_save_form_settings ($form)
maybe_uninstall ()
Not intended to be overridden or called directly by Add-Ons.
members_get_capabilities ($caps)
Not intended to be overridden or called directly by Add-Ons.
note_avatar ()
Override this function to specify a custom avatar (i.e.
notes_avatar ($avatar, $note)
plugin_message ()
Returns the message that will be displayed if the current version of Gravity Forms is not supported.
plugin_page_container ()
Plugin page container Target of the plugin menu left nav icon.
plugin_row ()
Target for the after_plugin_row action hook.
plugin_settings_fields ()
Override this function to specify the settings fields to be rendered on the plugin settings page.
plugin_settings_link ($links, $file)
plugin_settings_page ()
Plugin settings page.
plugin_settings_title ()
pre_init ()
Gets executed before all init functions.
register_noconflict_scripts ($scripts)
Target for the gform_noconflict_scripts filter.
register_noconflict_styles ($styles)
Target for the gform_noconflict_styles filter.
render_uninstall ()
Override this function to customize the markup for the uninstall section on the plugin settings page.
save_form_settings ($form, $settings)
set_logging_supported ($plugins)
settings_checkbox_and_select ($field, $echo=true)
Renders and initializes a checkbox field that displays a select field when checked based on the $field array.
settings_dynamic_field_map ($field, $echo=true)
settings_field_map ($field, $echo=true)
settings_field_map_select ($field, $form_id)
settings_field_select ($field, $echo=true)
Renders and initializes a drop down field based on the $field array whose choices are populated by the form's fields.
table_exists ($table_name)
uninstall_addon ()
Removes all settings and deactivates the Add-On.
Static Public Member Functions
static add_entry_meta ($form)
static get_paypal_payment_amount ($form, $entry, $paypal_config)
Static Public Member Functions inherited from GFAddOn
static display_plugin_message ($message, $is_error=false)
Formats and outs a message for the plugin row.
static get_all_deprecated_protected_methods ($add_on_class_name= '')
static get_deprecated_protected_methods_for_base_class ($base_class_name, $add_on_class_name= '')
static get_dynamic_field_map_fields ($feed, $field_name)
static get_field_map_choices ($form_id, $field_type=null, $exclude_field_types=null)
static get_field_map_fields ($feed, $field_name)
static get_gfaddon_base_path ()
Returns the physical path of the Add-On Framework root folder.
static get_gfaddon_base_url ()
Returns the url of the Add-On Framework root folder.
static get_registered_addons ()
Gets all active, registered Add-Ons.
static init_addons ()
Initializes all addons.
static register ($class, $overrides=null)
Registers an addon so that it gets initialized appropriately.
Protected Member Functions
add_delayed_payment_support ($options)
add_feed_error ($error_message, $feed, $entry, $form)
feed_edit_page ($form, $feed_id)
feed_list_columns ()
get_action_links ()
get_bulk_actions ()
get_default_feed_id ($form_id)
get_save_error_message ($sections)
get_save_success_message ($sections)
has_feed_condition_field ()
maybe_save_feed_settings ($feed_id, $form_id)
process_bulk_action ($action)
process_single_action ($action)
save_feed_settings ($feed_id, $form_id, $settings)
settings_feed_condition ($field, $echo=true)
setup ()
trim_conditional_logic_vales ($settings, $form_id)
uninstall ()
update_form_settings ($form, $new_form_settings)
Protected Member Functions inherited from GFAddOn
add_default_save_button ($sections)
add_field ($name, $fields, $settings, $pos)
add_field_after ($name, $fields, $settings)
add_field_before ($name, $fields, $settings)
app_settings ()
Override this function to add a custom app settings page.
app_settings_icon ()
Override this function to specific a custom app settings icon.
app_settings_title ()
Override this function to specific a custom app settings title.
app_settings_uninstall_tab ()
Renders the app settings uninstall tab.
app_tab_page_footer ()
Renders the footer for the tabs UI.
app_tab_page_header ($tabs, $current_tab, $title, $message= '')
Renders the header for the tabs UI.
checkbox_input ($choice, $attributes, $value, $tooltip)
Returns the markup for an individual checkbox input and its associated label.
checkbox_item ($choice, $horizontal_class, $attributes, $value, $tooltip, $error_icon='')
Returns the markup for an individual checkbox item give the parameters.
current_user_can_any ($caps)
Checks whether the current user is assigned to a capability or role.
field_failed_validation ($field)
Checks if the specified field failed validation.
field_map_title ()
form_settings ($form)
Custom form settings page Override this function to implement a complete custom form settings page.
form_settings_fields ($form)
Override this function to specify the settings fields to be rendered on the form settings page.
form_settings_icon ()
Override this function to customize the form settings icon.
form_settings_init ()
Initializes form settings page Hooks up the required scripts and actions for the Form Settings page.
form_settings_page_title ()
Custom form settings title Override this function to display a custom title on the Form Settings Page.
get_app_menu_icon ()
Override this function to specify a custom icon for the top level app menu.
get_app_menu_items ()
Override this function to create a top level app menu.
get_app_setting ($setting_name)
Get app setting Returns the app setting specified by the $setting_name parameter.
get_app_settings ()
Returns the currently saved plugin settings.
get_choice_attributes ($choice, $field_attributes, $default_choice_attributes=array())
Parses the properties of the $choice meta array and returns a set of HTML attributes to be added to the HTML element.
get_current_form ()
Returns the current form object based on the id query var.
get_current_settings ()
get_entry_meta ($entry_meta, $form_id)
Override this method to activate and configure entry meta.
get_error_icon ($field)
Gets the invalid field icon Returns the markup for an alert icon to indicate and highlight invalid fields.
get_field ($name, $settings)
get_field_attributes ($field, $default=array())
Parses the properties of the $field meta array and returns a set of HTML attributes to be added to the HTML element.
get_field_errors ($field=false)
Gets the validation errors for a field.
get_form_settings ($form)
Returns the form settings for the Add-On.
get_full_address ($entry, $field_id)
Returns the combined value of the specified Address field.
get_full_name ($entry, $field_id)
Returns the combined value of the specified Name field.
get_list_field_value ($entry, $field_id, $field)
Returns the value of the specified List field.
get_mapped_field_value ($setting_name, $form, $entry, $settings=false)
Returns the value of the mapped field.
get_plugin_settings_url ()
Returns the unescaped URL for the plugin settings tab associated with this plugin.
get_posted_settings ()
get_previous_settings ()
get_required_indicator ($field)
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
get_save_button ($sections)
get_save_error_message ($sections)
get_save_success_message ($sections)
get_select_option ($choice, $selected_value)
Prepares an HTML string for a single drop down field option.
get_setting ($setting_name, $default_value= '', $settings=false)
get_short_title ()
Returns this plugin's short title.
has_members_plugin ()
Checks whether the Members plugin is installed and activated.
has_setting_field_type ($type, $fields)
init_admin ()
Override this function to add initialization code (i.e.
init_ajax ()
Override this function to add AJAX hooks or to add initialization code when an AJAX request is being performed.
init_frontend ()
Override this function to add initialization code (i.e.
is_app_settings ($tab= '')
Returns TRUE if the current page is the app settings main page, or a specific apps settings tab (specified by the $tab parameter).
is_entry_edit ()
Returns TRUE if the current page is the entry edit page.
is_entry_list ()
is_entry_view ()
Returns TRUE if the current page is the entry view page.
is_form_editor ()
Returns TRUE if the current page is the form editor page.
is_form_settings ($tab=null)
Returns TRUE if the current page is the form settings page, or a specific form settings tab (specified by the $tab parameter).
is_plugin_page ()
Returns TRUE if the current page is the plugin page.
is_plugin_settings ($tab= '')
Returns TRUE if the current page is the plugin settings main page, or a specific plugin settings tab (specified by the $tab parameter).
is_postback ()
Returns TRUE if the current request is a postback, otherwise returns FALSE.
is_preview ()
Returns TRUE if the current page is the preview page.
is_print ()
Returns TRUE if the current page is the print page.
is_results ()
Returns TRUE if the current page is the results page.
is_save_postback ()
Returns TRUE if the settings "Save" button was pressed.
maybe_save_app_settings ()
Saves the plugin settings if the submit button was pressed.
maybe_save_plugin_settings ()
Saves the plugin settings if the submit button was pressed.
method_is_overridden ($method_name, $base_class= 'GFAddOn')
plugin_page ()
Override this function to create a custom plugin page.
plugin_page_icon ()
Override this function to customize the plugin page icon.
plugin_page_init ()
Initializes plugin settings page Hooks up the required scripts and actions for the Plugin Settings page.
plugin_page_title ()
Override this function to customize the plugin page title.
plugin_settings ()
Override this function to add a custom settings page.
plugin_settings_icon ()
plugin_settings_init ()
prepend_attribute ($name, $attribute, $current_attribute)
remove_field ($name, $settings)
render_settings ($sections)
replace_field ($name, $fields, $settings)
results_page_init ($results_page_config)
Initializes the result page functionality.
scripts ()
Override this function to provide a list of scripts to be enqueued.
set_field_error ($field, $error_message= '')
Sets the validation error message Sets the error message to be displayed when a field fails validation.
set_previous_settings ($settings)
set_settings ($settings)
setting_dependency_met ($dependency)
settings ($sections)
settings_checkbox ($field, $echo=true)
settings_fields_only ($settings_type= 'plugin')
Returns an flattened array of field settings for the specified settings type ignoring sections.
settings_hidden ($field, $echo=true)
settings_radio ($field, $echo=true)
settings_save ($field, $echo=true)
settings_select ($field, $echo=true)
settings_select_custom ($field, $echo=true)
Renders and initializes a drop down field with a input field for custom input based on the $field array.
settings_text ($field, $echo=true)
settings_textarea ($field, $echo=true)
setup ()
Performs upgrade tasks when the version of the Add-On changes.
simple_condition ($setting_name_root)
Helper to create a simple conditional logic set of fields.
single_section ($section, $is_first=false)
single_setting ($field)
single_setting_label ($field)
Displays the label for a field, including the tooltip and requirement indicator.
single_setting_row ($field)
single_setting_row_save ($field)
styles ()
Override this function to provide a list of styles to be enqueued.
uninstall ()
Called when the user chooses to uninstall the Add-On - after permissions have been checked and before removing all Add-On settings and Form settings.
uninstall_confirm_message ()
uninstall_warning_message ()
update_app_settings ($settings)
Updates app settings with the provided settings.
update_plugin_settings ($settings)
Updates plugin settings with the provided settings.
upgrade ($previous_version)
Override this function to add to add database update scripts or any other code to be executed when the Add-On version changes.
validate_checkbox_settings ($field, $settings)
validate_field_map_settings ($field, $settings)
validate_select_custom_settings ($field, $settings)
validate_settings ($fields, $settings)
Validates settings fields.
Protected Attributes
$_multiple_feeds = true
$_single_feed_submission = false
$_single_submission_feed = false
Protected Attributes inherited from GFAddOn
$_capabilities = array()
$_capabilities_app_menu = array()
$_capabilities_app_settings = array()
$_capabilities_form_settings = array()
$_capabilities_plugin_page = array()
$_capabilities_settings_page = array()
$_capabilities_uninstall = array()
$_enable_rg_autoupgrade = false
$_full_path
$_min_gravityforms_version
$_path
$_short_title
$_slug
$_title
$_url
$_version
Private Member Functions
get_bulk_action ()
upgrade_base ($previous_version)
Private Attributes
$_current_feed_id = false
$_feed_settings_fields = array()
$_feed_version = '0.11'
Additional Inherited Members
Data Fields inherited from GFAddOn
$app_hook_suffix
Static Protected Member Functions inherited from GFAddOn
static is_json ($value)
static maybe_decode_json ($value)
Detailed Description
Definition at line 16 of file class-gf-feed-addon.php.
Member Function Documentation
add_default_feed_settings_fields_props ($fields)
Definition at line 888 of file class-gf-feed-addon.php.
References $field, and get_default_feed_name().
Referenced by get_feed_settings_fields().
add_delayed_payment_support ($options) protected
Definition at line 1129 of file class-gf-feed-addon.php.
static add_entry_meta ($form) static
Definition at line 1106 of file class-gf-feed-addon.php.
add_feed_error ($error_message, $feed, $entry, $form) protected
Definition at line 1340 of file class-gf-feed-addon.php.
add_paypal_settings ($feed, $form)
Definition at line 1143 of file class-gf-feed-addon.php.
ajax_toggle_is_active ()
Definition at line 638 of file class-gf-feed-addon.php.
References update_feed_active().
can_create_feed ()
Override this function to prevent the feed creation UI from being rendered.
Returns
boolean|true
Definition at line 1014 of file class-gf-feed-addon.php.
Referenced by feed_edit_page(), and feed_list_title().
can_duplicate_feed ($id)
Override this function to allow the feed to being duplicated.
public
Parameters
int | array $id The ID of the feed to be duplicated or the feed object when duplicating a form.
Returns
boolean|true
Definition at line 1025 of file class-gf-feed-addon.php.
Referenced by duplicate_feed().
configure_addon_message ()
Definition at line 1001 of file class-gf-feed-addon.php.
Referenced by feed_edit_page().
delay_feed ($feed, $entry, $form)
Definition at line 263 of file class-gf-feed-addon.php.
Referenced by maybe_process_feed().
delete_feed ($id)
Definition at line 557 of file class-gf-feed-addon.php.
References $id, and $wpdb.
Referenced by process_bulk_action(), and process_single_action().
delete_feeds ($form_id = null)
Definition at line 563 of file class-gf-feed-addon.php.
References $form_id, $format, and $wpdb.
duplicate_feed ($id, $new_form_id = false)
Duplicates the feed.
Parameters
int | array $id The ID of the feed to be duplicated or the feed object when duplicating a form.
mixed $new_form_id False when using feed actions or the ID of the new form when duplicating a form.
Definition at line 578 of file class-gf-feed-addon.php.
References $count, $id, can_duplicate_feed(), esc_html__(), get_feed(), insert_feed(), and is_unique_feed_name().
Referenced by post_form_duplicated(), process_bulk_action(), and process_single_action().
feed_edit_page ($form, $feed_id) protected
Definition at line 683 of file class-gf-feed-addon.php.
References $form, $title, can_create_feed(), configure_addon_message(), feed_settings_title(), get_feed(), get_feed_settings_fields(), maybe_save_feed_settings(), output_field_scripts(), GFAddOn\render_settings(), and GFAddOn\set_settings().
Referenced by form_settings().
feed_list_columns () protected
Definition at line 976 of file class-gf-feed-addon.php.
Referenced by get_feed_table().
feed_list_message ()
Override this function to force a message to be displayed in the feed list (instead of data).
Useful to alert users when main plugin settings haven't been completed.
Returns
string|false
Definition at line 993 of file class-gf-feed-addon.php.
feed_list_no_item_message ()
Override this function to change the message that is displayed when the feed list is empty.
Returns
string The message
Definition at line 984 of file class-gf-feed-addon.php.
feed_list_page ($form = null)
Definition at line 729 of file class-gf-feed-addon.php.
References $action, $form, feed_list_title(), get_bulk_action(), get_feed_table(), input, name, process_bulk_action(), process_single_action(), and wp_nonce_field().
Referenced by form_settings().
feed_list_title ()
Definition at line 782 of file class-gf-feed-addon.php.
References $url, __, add_query_arg(), can_create_feed(), esc_html__(), esc_url, and GFAddOn\get_short_title().
Referenced by feed_list_page().
feed_settings_fields ()
Definition at line 884 of file class-gf-feed-addon.php.
Referenced by get_feed_settings_fields().
feed_settings_title ()
Definition at line 725 of file class-gf-feed-addon.php.
References esc_html__().
Referenced by feed_edit_page().
form_settings ($form)
Definition at line 650 of file class-gf-feed-addon.php.
References $form, feed_edit_page(), feed_list_page(), get_current_feed_id(), get_default_feed_id(), and is_detail_page().
form_settings_header ()
Definition at line 671 of file class-gf-feed-addon.php.
References $title, $url, add_query_arg(), esc_html, esc_html__(), form_settings_title(), and is_feed_list_page().
form_settings_init ()
Definition at line 634 of file class-gf-feed-addon.php.
form_settings_sections ()
Definition at line 646 of file class-gf-feed-addon.php.
form_settings_title ()
Definition at line 679 of file class-gf-feed-addon.php.
References esc_html__().
Referenced by form_settings_header().
get_action_links () protected
Definition at line 964 of file class-gf-feed-addon.php.
References __, add_query_arg(), esc_attr__(), esc_html__(), esc_js(), and esc_url.
Referenced by get_feed_table().
get_active_feeds ($form_id = null)
Definition at line 415 of file class-gf-feed-addon.php.
References $form_id, $wpdb, absint(), and ARRAY_A.
get_bulk_action () private
Definition at line 908 of file class-gf-feed-addon.php.
References $action.
Referenced by feed_list_page().
get_bulk_actions () protected
Definition at line 920 of file class-gf-feed-addon.php.
References esc_html__().
Referenced by get_feed_table().
get_column_value ($item, $column)
Definition at line 1029 of file class-gf-feed-addon.php.
get_current_feed ()
Definition at line 449 of file class-gf-feed-addon.php.
References get_current_feed_id(), and get_feed().
get_current_feed_id ()
Definition at line 455 of file class-gf-feed-addon.php.
References $_current_feed_id, and elseif.
Referenced by form_settings(), and get_current_feed().
get_default_feed_id ($form_id) protected
Definition at line 1049 of file class-gf-feed-addon.php.
References $wpdb.
Referenced by form_settings().
get_default_feed_name ()
Definition at line 489 of file class-gf-feed-addon.php.
References $name, $value, and get_feeds_by_slug().
Referenced by add_default_feed_settings_fields_props().
get_feed ($id)
Definition at line 465 of file class-gf-feed-addon.php.
References $id, $wpdb, and ARRAY_A.
Referenced by duplicate_feed(), feed_edit_page(), get_current_feed(), GFPaymentAddOn\get_payment_feed(), and maybe_save_feed_settings().
get_feed_settings_fields ()
Definition at line 873 of file class-gf-feed-addon.php.
References $_feed_settings_fields, add_default_feed_settings_fields_props(), and feed_settings_fields().
Referenced by feed_edit_page(), and maybe_save_feed_settings().
get_feed_table ($form)
Definition at line 769 of file class-gf-feed-addon.php.
References $columns, $form, feed_list_columns(), get_action_links(), get_bulk_actions(), and get_feeds().
Referenced by feed_list_page().
get_feeds ($form_id = null)
Definition at line 397 of file class-gf-feed-addon.php.
References $form_id, $wpdb, absint(), and ARRAY_A.
Referenced by GFPaymentAddOn\before_delete_field(), get_feed_table(), GFPaymentAddOn\get_payment_feed(), is_unique_feed_name(), maybe_process_feed(), and post_form_duplicated().
get_feeds_by_entry ($entry_id)
Definition at line 480 of file class-gf-feed-addon.php.
References gform_get_meta().
Referenced by GFPaymentAddOn\get_payment_feed().
get_feeds_by_slug ($slug, $form_id = null)
Definition at line 433 of file class-gf-feed-addon.php.
References $form_id, $wpdb, absint(), and ARRAY_A.
Referenced by get_default_feed_name(), and maybe_process_feed().
get_paypal_feed ($form_id, $entry)
Definition at line 281 of file class-gf-feed-addon.php.
References $form_id, and elseif.
static get_paypal_payment_amount ($form, $entry, $paypal_config) static
Definition at line 1230 of file class-gf-feed-addon.php.
get_save_error_message ($sections) protected
Definition at line 852 of file class-gf-feed-addon.php.
References esc_html__(), GFAddOn\get_save_button(), and is_detail_page().
Referenced by maybe_save_feed_settings().
get_save_success_message ($sections) protected
Definition at line 843 of file class-gf-feed-addon.php.
References esc_html__(), GFAddOn\get_save_button(), and is_detail_page().
Referenced by maybe_save_feed_settings().
get_single_submission_feed ($entry = false, $form = false)
Definition at line 1299 of file class-gf-feed-addon.php.
Referenced by maybe_process_feed().
has_feed ($form_id, $meets_conditional_logic = null)
Definition at line 1257 of file class-gf-feed-addon.php.
Referenced by GFPaymentAddOn\add_creditcard_token_input(), and GFPaymentAddOn\results_fields().
has_feed_condition_field () protected
Definition at line 1116 of file class-gf-feed-addon.php.
has_paypal_payment ($feed, $form, $entry)
Definition at line 298 of file class-gf-feed-addon.php.
References $field_id, $form, $option, $options, and elseif.
Referenced by maybe_process_feed().
init ()
Definition at line 43 of file class-gf-feed-addon.php.
References add_filter(), and init().
init_admin ()
Definition at line 59 of file class-gf-feed-addon.php.
References add_action(), and add_filter().
init_ajax ()
Definition at line 51 of file class-gf-feed-addon.php.
References add_action().
insert_feed ($form_id, $is_active, $meta)
Definition at line 548 of file class-gf-feed-addon.php.
References $form_id, and $wpdb.
Referenced by duplicate_feed(), and save_feed_settings().
is_delayed ($paypal_feed)
Definition at line 252 of file class-gf-feed-addon.php.
Referenced by maybe_process_feed().
is_delayed_payment ($entry, $form, $is_delayed)
Definition at line 1284 of file class-gf-feed-addon.php.
is_detail_page ()
Definition at line 667 of file class-gf-feed-addon.php.
References is_feed_list_page().
Referenced by form_settings(), get_save_error_message(), and get_save_success_message().
is_feed_condition_met ($feed, $form, $entry)
Definition at line 268 of file class-gf-feed-addon.php.
References $form.
Referenced by GFPaymentAddOn\get_payment_feed(), and maybe_process_feed().
is_feed_list_page ()
Definition at line 663 of file class-gf-feed-addon.php.
Referenced by form_settings_header(), and is_detail_page().
is_unique_feed_name ($name, $form_id)
Definition at line 518 of file class-gf-feed-addon.php.
References $form_id, $name, and get_feeds().
Referenced by duplicate_feed().
maybe_process_feed ($entry, $form)
Allow feed processing to be delayed.
bool $is_delayed Is feed processing delayed? array $form The Form Object currently being processed. array $entry The Entry Object currently being processed. string $_slug The Add-On slug e.g. gravityformsmailchimp
Definition at line 154 of file class-gf-feed-addon.php.
References GFAddOn\$_slug, $form, delay_feed(), get_feeds(), get_feeds_by_slug(), get_single_submission_feed(), gform_get_meta(), gform_update_meta(), has_paypal_payment(), is_delayed(), is_feed_condition_met(), GFAddOn\log_debug(), and process_feed().
maybe_save_feed_settings ($feed_id, $form_id) protected
Definition at line 792 of file class-gf-feed-addon.php.
References $form_id, GFAddOn\current_user_can_any(), esc_html__(), GFAddOn\filter_settings(), get_feed(), get_feed_settings_fields(), GFAddOn\get_posted_settings(), get_save_error_message(), get_save_success_message(), save_feed_settings(), GFAddOn\set_previous_settings(), trim_conditional_logic_vales(), and GFAddOn\validate_settings().
Referenced by feed_edit_page().
notification_events ($events, $form)
Add notifications events supported by Add-On to notification events list.
public
Parameters
array $events
array $form
Returns
array $events
Definition at line 381 of file class-gf-feed-addon.php.
References $form, and supported_notification_events().
paypal_fulfillment ($entry, $paypal_config, $transaction_id, $amount)
Definition at line 1200 of file class-gf-feed-addon.php.
post_form_duplicated ($form_id, $new_id)
Maybe duplicate feeds when a form is duplicated.
Parameters
int $form_id The ID of the original form.
int $new_id The ID of the duplicate form.
Definition at line 618 of file class-gf-feed-addon.php.
References $form_id, duplicate_feed(), and get_feeds().
process_bulk_action ($action) protected
Definition at line 934 of file class-gf-feed-addon.php.
References $action, delete_feed(), and duplicate_feed().
Referenced by feed_list_page().
process_feed ($feed, $entry, $form)
Definition at line 258 of file class-gf-feed-addon.php.
Referenced by maybe_process_feed().
process_single_action ($action) protected
Definition at line 953 of file class-gf-feed-addon.php.
References $action, absint(), delete_feed(), and duplicate_feed().
Referenced by feed_list_page().
save_feed_settings ($feed_id, $form_id, $settings) protected
Definition at line 861 of file class-gf-feed-addon.php.
References $form_id, insert_feed(), and update_feed_meta().
Referenced by maybe_save_feed_settings().
save_paypal_settings ($feed)
Definition at line 1194 of file class-gf-feed-addon.php.
scripts ()
Definition at line 112 of file class-gf-feed-addon.php.
settings ($sections)
Definition at line 715 of file class-gf-feed-addon.php.
References input, and name.
settings_feed_condition ($field, $echo = true) protected
Definition at line 1062 of file class-gf-feed-addon.php.
setup () protected
Definition at line 69 of file class-gf-feed-addon.php.
References $wpdb, get_option(), GFAddOn\table_exists(), update_option(), and upgrade_base().
supported_notification_events ($form)
Retrieves notification events supported by Add-On.
public
Parameters
array $form
Returns
array
Definition at line 367 of file class-gf-feed-addon.php.
Referenced by notification_events(), and GFPaymentAddOn\post_payment_action().
trim_conditional_logic_vales ($settings, $form_id) protected
Definition at line 831 of file class-gf-feed-addon.php.
References $form, $form_id, GFFormsModel\get_form_meta(), and GFFormsModel\trim_conditional_logic_values_from_element().
Referenced by maybe_save_feed_settings().
uninstall () protected
Definition at line 145 of file class-gf-feed-addon.php.
References $wpdb.
update_feed_active ($id, $is_active)
Definition at line 539 of file class-gf-feed-addon.php.
References $id, and $wpdb.
Referenced by ajax_toggle_is_active(), and GFPaymentAddOn\before_delete_field().
update_feed_meta ($id, $meta)
Definition at line 530 of file class-gf-feed-addon.php.
References $id, and $wpdb.
Referenced by save_feed_settings().
update_form_settings ($form, $new_form_settings) protected
Definition at line 1040 of file class-gf-feed-addon.php.
upgrade_base ($previous_version) private
Definition at line 83 of file class-gf-feed-addon.php.
References $charset_collate, $wpdb, ABSPATH, add_filter(), dbDelta(), and remove_filter().
Referenced by setup().
Field Documentation
$_current_feed_id = false private
Definition at line 41 of file class-gf-feed-addon.php.
Referenced by get_current_feed_id().
$_feed_settings_fields = array() private
Definition at line 40 of file class-gf-feed-addon.php.
Referenced by get_feed_settings_fields().
$_feed_version = '0.11' private
Definition at line 39 of file class-gf-feed-addon.php.
$_multiple_feeds = true protected
Definition at line 22 of file class-gf-feed-addon.php.
$_single_feed_submission = false protected
Definition at line 28 of file class-gf-feed-addon.php.
$_single_submission_feed = false protected
Definition at line 34 of file class-gf-feed-addon.php.
The documentation for this class was generated from the following file:
class-gf-feed-addon.php