GravityView: GravityView_Plugin_Hooks_TrustedLogin Class Reference
GravityView_Plugin_Hooks_TrustedLogin Class Reference
Public Member Functions
add_localization_data ($localization_data=array())
Adds the TrustedLogin Access Key to shared Support Port data.
filter_code_snippets_cap ($default_cap)
Modifies the capability required to access snippets created by the Code Snippets plugin.
filter_is_admin_page ($is_admin=false)
Adds TrustedLogin "Grant Access" to the list of GravityView admin pages (for loading scripts, etc.)
log ($message, $method='', $level='debug', $data=array())
Override TrustedLogin logging with GravityView's logging system.
Public Member Functions inherited from GravityView_Plugin_and_Theme_Hooks
__construct ()
GravityView_Theme_Support constructor.
_wp_loaded ()
Fired when all themes and plugins have been loaded.
merge_content_meta_keys ($meta_keys=array(), $post=null, & $views=null)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_meta_keys ($meta_keys=array(), $post_id=0)
Merge plugin or theme meta keys that store shortcode data with existing keys to check.
merge_noconflict_scripts ($handles)
Merge plugin or theme scripts with existing no-conflict scripts.
merge_noconflict_styles ($handles)
Merge plugin or theme styles with existing no-conflict styles.
merge_post_type_support ($supports=array(), $is_hierarchical=false)
Merge plugin or theme post type support definitions with existing support values.
Data Fields
$function_name = 'gravityview'
const TRUSTEDLOGIN_API_KEY = '3b3dc46c0714cc8e'
const TRUSTEDLOGIN_CLASS_NAME = '\GravityView\TrustedLogin\Client'
The full namespaced class name for the TL Client class.
const TRUSTEDLOGIN_NAMESPACE = 'gravityview'
Protected Member Functions
add_hooks ()
Protected Member Functions inherited from GravityView_Plugin_and_Theme_Hooks
add_hooks ()
Add filters for meta key and script/style handles, if defined.
Protected Attributes
$script_handles
$style_handles
Protected Attributes inherited from GravityView_Plugin_and_Theme_Hooks
$class_name = false
$constant_name = false
$content_meta_keys = array()
Define the keys to be parsed by the gravityview/view_collection/from_post/meta_keys hook.
$function_name = false
$meta_keys = array()
Define the keys to be parsed by the gravityview/data/parse/meta_keys hook.
$post_type_support = array()
Define features in the admin editor used by the theme or plugin to be used when registering the GravityView post type.
$script_handles = array()
Define script handles used by the theme or plugin to be added to allowed no-conflict scripts.
$style_handles = array()
Define style handles used by the theme or plugin to be added to allowed no-conflict styles.
Private Member Functions
get_trustedlogin_config ()
Returns the configuration array passed to TrustedLogin.
Static Private Attributes
static $TL_Client
Detailed Description
Since
2.13
Definition at line 22 of file class-gravityview-plugin-hooks-trustedlogin.php.
Member Function Documentation
add_hooks()
add_hooks () protected
Definition at line 118 of file class-gravityview-plugin-hooks-trustedlogin.php.
References gravityview(), and GRAVITYVIEW_DIR.
add_localization_data()
add_localization_data ($localization_data = array())
Adds the TrustedLogin Access Key to shared Support Port data.
Parameters
array $localization_data Array of data passed to the Support Port.
Returns
array the support port data array with tl_access_key key set to the site access key.
Definition at line 217 of file class-gravityview-plugin-hooks-trustedlogin.php.
filter_code_snippets_cap()
filter_code_snippets_cap ($default_cap)
Modifies the capability required to access snippets created by the Code Snippets plugin.
See also
https://wordpress.org/plugins/code-snippets/
Parameters
$default_cap
Returns
string If current user is a TrustedLogin support user, returns name of their role. Otherwise, returns original capability.
Definition at line 155 of file class-gravityview-plugin-hooks-trustedlogin.php.
filter_is_admin_page()
filter_is_admin_page ($is_admin = false)
Adds TrustedLogin "Grant Access" to the list of GravityView admin pages (for loading scripts, etc.)
Parameters
string | bool $is_page If false, no. If string, the name of the page (single, settings, or views).
string $hook The name of the page to check against. Is passed to the method.
Returns
string|bool
Definition at line 200 of file class-gravityview-plugin-hooks-trustedlogin.php.
get_trustedlogin_config()
get_trustedlogin_config () private
Returns the configuration array passed to TrustedLogin.
See also
TrustedLogin
Returns
array The configuration array for GravityView
Definition at line 71 of file class-gravityview-plugin-hooks-trustedlogin.php.
References gravityview(), and GRAVITYVIEW_FILE.
log()
log ($message, $method = '', $level = 'debug', $data = array())
Override TrustedLogin logging with GravityView's logging system.
Definition at line 185 of file class-gravityview-plugin-hooks-trustedlogin.php.
References gravityview().
Field Documentation
$function_name
$function_name = 'gravityview'
Definition at line 48 of file class-gravityview-plugin-hooks-trustedlogin.php.
$script_handles
$script_handles protected
Initial value:
= array(
        'trustedlogin-' . GravityView_Plugin_Hooks_TrustedLogin::TRUSTEDLOGIN_NAMESPACE,
    )
Definition at line 60 of file class-gravityview-plugin-hooks-trustedlogin.php.
$style_handles
$style_handles protected
Initial value:
= array(
        'trustedlogin-' . GravityView_Plugin_Hooks_TrustedLogin::TRUSTEDLOGIN_NAMESPACE,
    )
Definition at line 53 of file class-gravityview-plugin-hooks-trustedlogin.php.
$TL_Client
$TL_Client static private
Definition at line 42 of file class-gravityview-plugin-hooks-trustedlogin.php.
TRUSTEDLOGIN_API_KEY
const TRUSTEDLOGIN_API_KEY = '3b3dc46c0714cc8e'
Definition at line 32 of file class-gravityview-plugin-hooks-trustedlogin.php.
TRUSTEDLOGIN_CLASS_NAME
const TRUSTEDLOGIN_CLASS_NAME = '\GravityView\TrustedLogin\Client'
The full namespaced class name for the TL Client class.
Definition at line 37 of file class-gravityview-plugin-hooks-trustedlogin.php.
TRUSTEDLOGIN_NAMESPACE
const TRUSTEDLOGIN_NAMESPACE = 'gravityview'
Definition at line 27 of file class-gravityview-plugin-hooks-trustedlogin.php.
The documentation for this class was generated from the following file:
class-gravityview-plugin-hooks-trustedlogin.php