GravityView: GFAsyncUpload Class Reference
GFAsyncUpload Class Reference
Static Public Member Functions
static die_error ($status_code, $message)
static upload ()
Detailed Description
Definition at line 7 of file gravityforms/includes/upload.php.
Member Function Documentation
static die_error ($status_code, $message) static
Definition at line 248 of file gravityforms/includes/upload.php.
References $message.
static upload () static
Definition at line 9 of file gravityforms/includes/upload.php.
References $_SERVER, $dir, $field, $field_id, $file, $form, $form_id, $out, $output, __, absint(), GFForms\add_security_files(), apply_filters(), current_time(), GFFormsModel\get_field(), GFAPI\get_form(), GFFormsModel\get_input_type(), get_option(), GFFormsModel\get_upload_path(), GFFormsModel\get_upload_root(), is_wp_error(), nocache_headers(), sanitize_file_name(), send_nosniff_header(), GFFormsModel\set_permissions(), status_header(), str_replace, wp_max_upload_size(), and wp_mkdir_p().
The documentation for this class was generated from the following file:
gravityforms/includes/upload.php