GravityView: WP_Customize_Panel Class Reference
WP_Customize_Panel Class Reference
Customize Panel class.
Public Member Functions
__construct ($manager, $id, $args=array())
Constructor.
active ()
Check whether panel is active to current Customizer preview.
active_callback ()
Default callback used when invoking {.
check_capabilities ()
Checks required user capabilities and whether the theme has the feature support required by the panel.
get_content ()
Get the panel's content template for insertion into the Customizer pane.
json ()
Gather the parameters passed to client JavaScript via JSON.
maybe_render ()
Check capabilities and render the panel.
print_template ()
Render the panel's JS templates.
Data Fields
$active_callback = ''
$capability = 'edit_theme_options'
$description = ''
$id
$instance_number
$manager
$priority = 160
$sections
$theme_supports = ''
$title = ''
$type = 'default'
Protected Member Functions
content_template ()
An Underscore (JS) template for this panel's content (but not its container).
render ()
Render the panel container, and then its contents (via this->render_content()) in a subclass.
render_content ()
Render the panel UI in a subclass.
render_template ()
An Underscore (JS) template for rendering this panel's container.
Static Protected Attributes
static $instance_count = 0
Detailed Description
Customize Panel class.
A UI container for sections, managed by the WP_Customize_Manager.
Since
4.0.0
See also
WP_Customize_Manager
Definition at line 19 of file class-wp-customize-panel.php.
Constructor & Destructor Documentation
__construct ($manager, $id, $args = array())
Constructor.
Any supplied $args override class property defaults.
Since
4.0.0
Parameters
WP_Customize_Manager $manager Customizer bootstrap instance.
string $id An specific ID for the panel.
array $args Panel arguments.
Definition at line 151 of file class-wp-customize-panel.php.
References $id, $keys, $manager, and active_callback().
Member Function Documentation
active () final
Check whether panel is active to current Customizer preview.
Since
4.1.0 public
Returns
bool Whether the panel is active to the current preview.
Filter response of WP_Customize_Panel::active().
Since
4.1.0
Parameters
bool $active Whether the Customizer panel is active.
WP_Customize_Panel $panel {
See also
WP_Customize_Panel} instance.
Definition at line 178 of file class-wp-customize-panel.php.
References active_callback(), and apply_filters().
Referenced by json().
active_callback ()
Default callback used when invoking {.
See also
WP_Customize_Panel::active()}.
Subclasses can override this with their specific logic, or they may provide an 'active_callback' argument to the constructor.
Since
4.1.0 public
Returns
bool Always true.
Definition at line 206 of file class-wp-customize-panel.php.
Referenced by __construct(), and active().
check_capabilities () final
Checks required user capabilities and whether the theme has the feature support required by the panel.
Since
4.0.0
Returns
bool False if theme doesn't support the panel or the user doesn't have the capability.
Definition at line 234 of file class-wp-customize-panel.php.
Referenced by maybe_render().
content_template () protected
An Underscore (JS) template for this panel's content (but not its container).
Class variables for this panel class are available in the data JS object; export custom variables by overriding WP_Customize_Panel::json().
See also
WP_Customize_Panel::print_template()
Since
4.3.0 protected
Definition at line 366 of file class-wp-customize-panel.php.
References __, _e, and li.
Referenced by print_template().
get_content () final
Get the panel's content template for insertion into the Customizer pane.
Since
4.1.0
Returns
string Content for the panel.
Definition at line 253 of file class-wp-customize-panel.php.
References maybe_render().
Referenced by json().
json ()
Gather the parameters passed to client JavaScript via JSON.
Since
4.1.0
Returns
array The array to be exported to the client as JSON.
Definition at line 217 of file class-wp-customize-panel.php.
References $instance_number, active(), get_bloginfo(), get_content(), and wp_array_slice_assoc().
maybe_render () final
Check capabilities and render the panel.
Since
4.0.0
Fires before rendering a Customizer panel.
Since
4.0.0
Parameters
WP_Customize_Panel $this WP_Customize_Panel instance.
Fires before rendering a specific Customizer panel.
The dynamic portion of the hook name, $this->id, refers to the ID of the specific Customizer panel to be rendered.
Since
4.0.0
Definition at line 264 of file class-wp-customize-panel.php.
References check_capabilities(), do_action(), and render().
Referenced by get_content().
print_template ()
Render the panel's JS templates.
This function is only run for panel types that have been registered with WP_Customize_Manager::register_panel_type().
Since
4.3.0
See also
WP_Customize_Manager::register_panel_type()
Definition at line 321 of file class-wp-customize-panel.php.
References content_template(), and render_template().
render () protected
Render the panel container, and then its contents (via this->render_content()) in a subclass.
Panel containers are now rendered in JS by default, see {
See also
WP_Customize_Panel::print_template()}.
Since
4.0.0 protected
Definition at line 299 of file class-wp-customize-panel.php.
Referenced by maybe_render().
render_content () protected
Render the panel UI in a subclass.
Panel contents are now rendered in JS by default, see {
See also
WP_Customize_Panel::print_template()}.
Since
4.1.0 protected
Definition at line 309 of file class-wp-customize-panel.php.
render_template () protected
An Underscore (JS) template for rendering this panel's container.
Class variables for this panel class are available in the data JS object; export custom variables by overriding WP_Customize_Panel::json().
See also
WP_Customize_Panel::print_template()
Since
4.3.0 protected
Definition at line 343 of file class-wp-customize-panel.php.
References _e, and li.
Referenced by print_template().
Field Documentation
$active_callback = ''
Definition at line 138 of file class-wp-customize-panel.php.
$capability = 'edit_theme_options'
Definition at line 78 of file class-wp-customize-panel.php.
$description = ''
Definition at line 105 of file class-wp-customize-panel.php.
$id
Definition at line 60 of file class-wp-customize-panel.php.
Referenced by __construct().
$instance_count = 0 static protected
Definition at line 33 of file class-wp-customize-panel.php.
$instance_number
Definition at line 42 of file class-wp-customize-panel.php.
Referenced by json().
$manager
Definition at line 51 of file class-wp-customize-panel.php.
Referenced by __construct().
$priority = 160
Definition at line 69 of file class-wp-customize-panel.php.
$sections
Definition at line 114 of file class-wp-customize-panel.php.
$theme_supports = ''
Definition at line 87 of file class-wp-customize-panel.php.
$title = ''
Definition at line 96 of file class-wp-customize-panel.php.
$type = 'default'
Definition at line 123 of file class-wp-customize-panel.php.
The documentation for this class was generated from the following file:
class-wp-customize-panel.php