GravityView: SiteAccess Class Reference
SiteAccess Class Reference
Public Member Functions
__construct (Config $config, Logging $logging)
get_access_key ()
Gets the shareable access key.
get_license_key ($hashed=false)
Get the license key for the current user.
revoke ($secret_id, Remote $remote)
Revoke a site in TrustedLogin.
sync_secret ($secret_id, $site_identifier_hash, $action='create')
Handles the syncing of newly generated support access to the TrustedLogin servers.
Private Member Functions
generate_access_key ()
Generates an accessKey that can be copy-pasted to support to give them access via TrustedLogin.
Private Attributes
$config
$logging
Static Private Attributes
static $sync_actions
Detailed Description
Definition at line 18 of file SiteAccess.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Logging $logging)
Definition at line 41 of file SiteAccess.php.
References SiteAccess\$config, and SiteAccess\$logging.
Member Function Documentation
generate_access_key()
generate_access_key () private
Generates an accessKey that can be copy-pasted to support to give them access via TrustedLogin.
Access Keys can only be used by authenticated support agents to request logged access to a site via their TrustedLogin plugin.
Since
1.0.0
Returns
string|WP_Error Access Key prepended with TL, or something went wrong.
Definition at line 184 of file SiteAccess.php.
References Encryption\hash().
Referenced by SiteAccess\get_access_key().
get_access_key()
get_access_key ()
Gets the shareable access key.
For licensed plugins or themes, a hashed customer's license key is the access key.
For plugins or themes without license keys, the accessKey is generated for the site.
SiteAccess::get_license_key() SiteAccess::generate_access_key()
Since
1.0.0
Returns
string|null $access_key, if exists. Either a hashed license key or a generated hash. If error occurs, returns null.
Definition at line 117 of file SiteAccess.php.
References SiteAccess\generate_access_key(), and SiteAccess\get_license_key().
Referenced by SiteAccess\sync_secret().
get_license_key()
get_license_key ($hashed = false)
Get the license key for the current user.
Since
1.0.0
Parameters
bool $hashed Should the value be hashed using SHA256?
Returns
string|null|WP_Error License key (hashed if $hashed is true) or null if not found. Returns WP_Error if error occurs.
Filter: Allow for over-riding the 'accessKey' sent to SaaS platform
Since
1.0.0
Parameters
string | null $license_key
Definition at line 144 of file SiteAccess.php.
Referenced by SiteAccess\get_access_key().
revoke()
revoke ($secret_id, Remote $remote)
Revoke a site in TrustedLogin.
Parameters
string $secret_id ID of site secret identifier to be removed from TrustedLogin
Remote $remote
Returns
true| Was the sync to TrustedLogin successful
Definition at line 203 of file SiteAccess.php.
References Remote\handle_response(), and Remote\send().
sync_secret()
sync_secret ($secret_id, $site_identifier_hash, $action = 'create')
Handles the syncing of newly generated support access to the TrustedLogin servers.
Parameters
string $secret_id The unique identifier for this TrustedLogin authorization. {
See also
Endpoint::generate_secret_id}
Parameters
string $site_identifier_hash The unique identifier for the WP_User created {
See also
Encryption::get_random_hash()}
Parameters
string $action The type of sync this is. Options can be 'create', 'extend'.
Returns
true|WP_Error True if successfully created secret on TrustedLogin servers; WP_Error if failed.
Definition at line 55 of file SiteAccess.php.
References SiteAccess\$logging, and SiteAccess\get_access_key().
Field Documentation
$config
Config $config private
Definition at line 23 of file SiteAccess.php.
Referenced by SiteAccess\__construct().
$logging
Logging $logging private
Definition at line 28 of file SiteAccess.php.
Referenced by SiteAccess\__construct(), and SiteAccess\sync_secret().
$sync_actions
$sync_actions static private
Initial value:
= array(
        'create',
        'extend'
    )
Definition at line 33 of file SiteAccess.php.
The documentation for this class was generated from the following file:
SiteAccess.php