GravityView: wpdb Class Reference
wpdb Class Reference
Public Member Functions
__construct ($dbuser, $dbpassword, $dbname, $dbhost)
Connects to the database server and selects a database.
__destruct ()
PHP5 style destructor and will run when database object is destroyed.
__get ($name)
PHP5 style magic getter, used to lazy-load expensive data.
__isset ($name)
Magic function, for backwards compatibility.
__set ($name, $value)
Magic function, for backwards compatibility.
__unset ($name)
Magic function, for backwards compatibility.
_escape ($data)
Escape data.
_insert_replace_helper ($table, $data, $format=null, $type= 'INSERT')
Helper function for insert and replace.
_real_escape ($string)
Real escape, using mysqli_real_escape_string() or mysql_real_escape_string()
_weak_escape ($string)
Do not use, deprecated.
bail ($message, $error_code= '500')
Wraps errors in a nice header and footer and dies.
check_connection ($allow_bail=true)
Check that the connection to the database is still up.
check_database_version ()
Whether MySQL database is at least the required minimum version.
db_connect ($allow_bail=true)
Connect to and select database.
db_version ()
The database version number.
delete ($table, $where, $where_format=null)
Delete a row in the table.
esc_like ($text)
First half of escaping for LIKE special characters % and _ before preparing for MySQL.
escape ($data)
Do not use, deprecated.
escape_by_ref (&$string)
Escapes content by reference for insertion into the database, for security.
flush ()
Kill cached query results.
get_blog_prefix ($blog_id=null)
Gets blog prefix.
get_caller ()
Retrieve the name of the function that called wpdb.
get_charset_collate ()
The database character collate.
get_col ($query=null, $x=0)
Retrieve one column from the database.
get_col_charset ($table, $column)
Retrieves the character set for the given column.
get_col_info ($info_type= 'name', $col_offset=-1)
Retrieve column metadata from the last query.
get_col_length ($table, $column)
Retrieve the maximum string length allowed in a given column.
get_results ($query=null, $output=OBJECT)
Retrieve an entire SQL result set from the database (i.e., many rows)
get_row ($query=null, $output=OBJECT, $y=0)
Retrieve one row from the database.
get_var ($query=null, $x=0, $y=0)
Retrieve one variable from the database.
has_cap ($db_cap)
Determine if a database supports a particular feature.
hide_errors ()
Disables showing of database errors.
init_charset ()
Set $this->charset and $this->collate.
insert ($table, $data, $format=null)
Insert a row into a table.
prepare ($query, $args)
Prepares a SQL query for safe execution.
print_error ($str= '')
Print SQL/DB error.
query ($query)
Perform a MySQL database query, using current database connection.
replace ($table, $data, $format=null)
Replace a row into a table.
select ($db, $dbh=null)
Selects a database using the current database connection.
set_blog_id ($blog_id, $site_id=0)
Sets blog id.
set_charset ($dbh, $charset=null, $collate=null)
Sets the connection's character set.
set_prefix ($prefix, $set_table_names=true)
Sets the table prefix for the WordPress tables.
set_sql_mode ($modes=array())
Change the current SQL mode, and ensure its WordPress compatibility.
show_errors ($show=true)
Enables showing of database errors.
strip_invalid_text_for_column ($table, $column, $value)
Strips any invalid characters from the string for a given table and column.
supports_collation ()
Whether the database supports collation.
suppress_errors ($suppress=true)
Whether to suppress database errors.
tables ($scope= 'all', $prefix=true, $blog_id=0)
Returns an array of WordPress tables.
timer_start ()
Starts the timer, for debugging purposes.
timer_stop ()
Stops the debugging timer.
update ($table, $data, $where, $format=null, $where_format=null)
Update a row in the table.
Data Fields
$base_prefix
$blog_versions
$blogid = 0
$blogs
$charset
$collate
$commentmeta
$comments
$field_types = array()
$func_call
$global_tables = array('users', 'usermeta')
$insert_id = 0
$is_mysql = null
$last_error = ''
$last_query
$last_result
$links
$ms_global_tables
$num_queries = 0
$num_rows = 0
$old_tables = array('categories', 'post2cat', 'link2cat')
$options
$postmeta
$posts
$prefix = ''
$queries
$ready = false
$registration_log
$rows_affected = 0
$show_errors = false
$signups
$site
$sitecategories
$siteid = 0
$sitemeta
$suppress_errors = false
$tables
$term_relationships
$term_taxonomy
$termmeta
$terms
$usermeta
$users
Protected Member Functions
check_ascii ($string)
Check if a string is ASCII.
check_safe_collation ($query)
Check if the query is accessing a collation considered safe on the current version of MySQL.
get_table_charset ($table)
Retrieves the character set for the given table.
get_table_from_query ($query)
Find the first table name referenced in a query.
load_col_info ()
Load the column metadata from the last query.
process_field_charsets ($data, $table)
Adds field charsets to field/value/format arrays generated by the wpdb::process_field_formats() method.
process_field_formats ($data, $format)
Prepares arrays of value/format pairs as passed to wpdb CRUD methods.
process_field_lengths ($data, $table)
For string fields, record the maximum string length that field can safely save.
process_fields ($table, $data, $format)
Processes arrays of field/value pairs and field formats.
strip_invalid_text ($data)
Strips any invalid characters based on value/charset pairs.
strip_invalid_text_from_query ($query)
Strips any invalid characters from the query.
Protected Attributes
$check_current_query = true
$col_info
$col_meta = array()
$dbh
$dbhost
$dbname
$dbpassword
$dbuser
$incompatible_modes
$reconnect_retries = 5
$result
$table_charset = array()
Private Member Functions
_do_query ($query)
Internal function to perform the mysql_query() call.
Private Attributes
$checking_collation = false
$has_connected = false
$use_mysqli = false
Detailed Description
Definition at line 52 of file wp-db.php.
Constructor & Destructor Documentation
__construct ($dbuser, $dbpassword, $dbname, $dbhost)
Connects to the database server and selects a database.
PHP5 style constructor for compatibility with PHP5. Does the actual setting up of the class properties and connection to the database.
2.0.8 string $wp_version string $dbuser MySQL database user string $dbpassword MySQL database password string $dbname MySQL database name string $dbhost MySQL database host
Definition at line 626 of file wp-db.php.
References $dbhost, $dbname, $dbpassword, $dbuser, $GLOBALS, db_connect(), elseif, show_errors(), and WP_DEBUG.
__destruct ()
PHP5 style destructor and will run when database object is destroyed.
See also
wpdb::__construct()
Since
2.0.8
Returns
true
Definition at line 668 of file wp-db.php.
Member Function Documentation
__get ($name)
PHP5 style magic getter, used to lazy-load expensive data.
Since
3.5.0
Parameters
string $name The private member to get, and optionally process
Returns
mixed The private member
Definition at line 680 of file wp-db.php.
References $name, and load_col_info().
__isset ($name)
Magic function, for backwards compatibility.
Since
3.5.0
Parameters
string $name The private member to check
Returns
bool If the member is set or not
Definition at line 716 of file wp-db.php.
References $name.
__set ($name, $value)
Magic function, for backwards compatibility.
Since
3.5.0
Parameters
string $name The private member to set
mixed $value The value to set
Definition at line 695 of file wp-db.php.
References $name, and $value.
__unset ($name)
Magic function, for backwards compatibility.
Since
3.5.0
Parameters
string $name The private member to unset
Definition at line 727 of file wp-db.php.
References $name.
_do_query ($query) private
Internal function to perform the mysql_query() call.
Since
3.9.0
private
See also
wpdb::query()
Parameters
string $query The query to run.
Definition at line 1795 of file wp-db.php.
References elseif, get_caller(), timer_start(), and timer_stop().
Referenced by query().
_escape ($data)
Escape data.
Works on arrays.
wpdb::_real_escape()
Since
2.8.0 private
Parameters
string | array $data
Returns
string|array escaped
Definition at line 1153 of file wp-db.php.
References _real_escape().
_insert_replace_helper ($table, $data, $format = null, $type = 'INSERT')
Helper function for insert and replace.
Runs an insert or replace query based on $type argument.
private
Since
3.0.0
See also
wpdb::prepare()
wpdb::$field_types
wp_set_wpdb_vars()
Parameters
string $table Table name
array $data Data to insert (in column => value pairs). Both $data columns and $data values should be "raw" (neither should be SQL escaped). Sending a null value will cause the column to be set to NULL - the corresponding format is ignored in this case.
array | string $format Optional. An array of formats to be mapped to each of the value in $data. If string, that format will be used for all of the values in $data. A format is one of 'd', 'f', 's' (integer, float, string). If omitted, all values in $data will be treated as strings unless otherwise specified in wpdb::$field_types.
string $type Optional. What type of operation is this? INSERT or REPLACE. Defaults to INSERT.
Returns
int|false The number of rows affected, or false on error.
Definition at line 1884 of file wp-db.php.
References $format, $value, prepare(), process_fields(), and query().
Referenced by insert(), and replace().
_real_escape ($string)
Real escape, using mysqli_real_escape_string() or mysql_real_escape_string()
See also
mysqli_real_escape_string()
mysql_real_escape_string()
Since
2.8.0 private
Parameters
string $string to escape
Returns
string escaped
Definition at line 1124 of file wp-db.php.
References $class, __, and _doing_it_wrong().
Referenced by _escape(), and escape_by_ref().
_weak_escape ($string)
Do not use, deprecated.
Use esc_sql() or wpdb::prepare() instead.
Since
2.8.0
Parameters
string $string
Returns
string
Definition at line 1107 of file wp-db.php.
References _deprecated_function().
Referenced by escape().
bail ($message, $error_code = '500')
Wraps errors in a nice header and footer and dies.
Will not die if wpdb::$show_errors is false.
Since
1.5.0
Parameters
string $message The Error message
string $error_code Optional. A Computer readable string to identify the error.
Returns
false|void
Definition at line 3084 of file wp-db.php.
References $message, and wp_die().
Referenced by check_connection(), db_connect(), and select().
check_ascii ($string) protected
Check if a string is ASCII.
The negative regex is faster for non-ASCII strings, as it allows the search to finish as soon as it encounters a non-ASCII character.
Since
4.2.0 protected
Parameters
string $string String to check.
Returns
bool True if ASCII, false if not.
Definition at line 2622 of file wp-db.php.
References elseif.
Referenced by check_safe_collation(), query(), and strip_invalid_text().
check_connection ($allow_bail = true)
Check that the connection to the database is still up.
If not, try to reconnect.
If this function is unable to reconnect, it will forcibly die, or if after the the template_redirect hook has been fired, return false instead.
If $allow_bail is false, the lack of database connection will need to be handled manually.
Since
3.9.0
Parameters
bool $allow_bail Optional. Allows the function to bail. Default true.
Returns
bool|void True if the connection is up.
Definition at line 1582 of file wp-db.php.
References $message, $reconnect_retries, __, bail(), db_connect(), dead_db(), did_action(), WP_DEBUG, and wp_load_translations_early().
Referenced by query().
check_database_version ()
Whether MySQL database is at least the required minimum version.
Since
2.5.0
string $wp_version string $required_mysql_version
Returns
WP_Error|void
Definition at line 3106 of file wp-db.php.
References $required_mysql_version, $wp_version, and __.
check_safe_collation ($query) protected
Check if the query is accessing a collation considered safe on the current version of MySQL.
Since
4.2.0 protected
Parameters
string $query The query to check.
Returns
bool True if the collation is safe, false if it isn't.
Definition at line 2643 of file wp-db.php.
References check_ascii(), get_table_charset(), and get_table_from_query().
Referenced by get_col(), get_results(), get_row(), and get_var().
db_connect ($allow_bail = true)
Connect to and select database.
If $allow_bail is false, the lack of database connection will need to be handled manually.
Since
3.0.0
3.9.0 $allow_bail parameter added.
Parameters
bool $allow_bail Optional. Allows the function to bail. Default true.
Returns
bool True with a successful connection, false on failure.
Definition at line 1454 of file wp-db.php.
References $dbhost, $message, __, bail(), elseif, init_charset(), null, select(), set_charset(), set_sql_mode(), WP_CONTENT_DIR, and wp_load_translations_early().
Referenced by __construct(), and check_connection().
db_version ()
The database version number.
Since
2.7.0
Returns
null|string Null on failure, version number on success.
Definition at line 3217 of file wp-db.php.
delete ($table, $where, $where_format = null)
Delete a row in the table.
wpdb::delete('table', array('ID' => 1)) wpdb::delete('table', array('ID' => 1), array('d'))
Since
3.4.0
See also
wpdb::prepare()
wpdb::$field_types
wp_set_wpdb_vars()
Parameters
string $table Table name
array $where A named array of WHERE clauses (in column => value pairs). Multiple clauses will be joined with ANDs. Both $where columns and $where values should be "raw". Sending a null value will create an IS NULL comparison - the corresponding format will be ignored in this case.
array | string $where_format Optional. An array of formats to be mapped to each of the values in $where. If string, that format will be used for all of the items in $where. A format is one of 'd', 'f', 's' (integer, float, string). If omitted, all values in $where will be treated as strings unless otherwise specified in wpdb::$field_types.
Returns
int|false The number of rows updated, or false on error.
Definition at line 2011 of file wp-db.php.
References $field, $value, prepare(), process_fields(), and query().
esc_like ($text)
First half of escaping for LIKE special characters % and _ before preparing for MySQL.
Use this only before wpdb::prepare() or esc_sql(). Reversing the order is very bad for security.
Example Prepared Statement: $wild = ''; $find = 'only 43% of planets'; $like = $wild . $wpdb->esc_like($find) . $wild; $sql = $wpdb->prepare("SELECT * FROM $wpdb->posts WHERE post_content LIKE %s", $like);
Example Escape Chain: $sql = esc_sql($wpdb->esc_like($input));
Since
4.0.0 public
Parameters
string $text The raw text to be escaped. The input typed by the user should have no extra or deleted slashes.
Returns
string Text in the form of a LIKE phrase. The output is not SQL safe. Call $wpdb::prepare() or real_escape next.
Definition at line 1290 of file wp-db.php.
References $text.
escape ($data)
Do not use, deprecated.
Use esc_sql() or wpdb::prepare() instead.
Since
0.71
Parameters
mixed $data
Returns
mixed
Definition at line 1181 of file wp-db.php.
References _deprecated_function(), and _weak_escape().
escape_by_ref (& $string)
Escapes content by reference for insertion into the database, for security.
wpdb::_real_escape()
Since
2.3.0
Parameters
string $string to escape
Definition at line 1207 of file wp-db.php.
References _real_escape().
flush ()
Kill cached query results.
Since
0.71
Definition at line 1417 of file wp-db.php.
References elseif, and null.
Referenced by query().
get_blog_prefix ($blog_id = null)
Gets blog prefix.
Since
3.0.0
Parameters
int $blog_id Optional.
Returns
string Blog prefix.
Definition at line 941 of file wp-db.php.
References $base_prefix, $blog_id, $blogid, is_multisite(), and null.
Referenced by set_blog_id(), set_prefix(), and tables().
get_caller ()
Retrieve the name of the function that called wpdb.
Searches up the list of functions until it reaches the one that would most logically had called this method.
Since
2.5.0
Returns
string|array The name of the calling function
Definition at line 3206 of file wp-db.php.
References wp_debug_backtrace_summary().
Referenced by _do_query(), and print_error().
get_charset_collate ()
The database character collate.
Since
3.5.0
Returns
string The database character collate.
Definition at line 3137 of file wp-db.php.
References $charset_collate.
get_col ($query = null, $x = 0)
Retrieve one column from the database.
Executes a SQL query and returns the column from the SQL result. If the SQL result contains more than one column, this function returns the column specified. If $query is null, this function returns the specified column from the previous SQL result.
Since
0.71
Parameters
string | null $query Optional. SQL query. Defaults to previous query.
int $x Optional. Column to return. Indexed from 0.
Returns
array Database query result. Array indexed from 0 by SQL result row number.
Definition at line 2274 of file wp-db.php.
References $i, check_safe_collation(), get_var(), null, and query().
get_col_charset ($table, $column)
Retrieves the character set for the given column.
Since
4.2.0 public
Parameters
string $table Table name.
string $column Column name.
Returns
string|false|WP_Error Column character set as a string. False if the column has no character set. WP_Error object if there was an error.
Filter the column charset value before the DB is checked.
Passing a non-null value to the filter will short-circuit checking the DB for the charset, returning that value instead.
Since
4.2.0
Parameters
string $charset The character set to use. Default null.
string $table The name of the table being checked.
string $column The name of the column being checked.
Definition at line 2466 of file wp-db.php.
References $charset, $table_charset, apply_filters(), get_table_charset(), is_wp_error(), and null.
Referenced by process_field_charsets(), and strip_invalid_text_for_column().
get_col_info ($info_type = 'name', $col_offset = -1)
Retrieve column metadata from the last query.
Since
0.71
Parameters
string $info_type Optional. Type one of name, table, def, max_length, not_null, primary_key, multiple_key, unique_key, numeric, blob, type, unsigned, zerofill
int $col_offset Optional. 0: col name. 1: which table the col's in. 2: col's max length. 3: if the col is numeric. 4: col's type
Returns
mixed Column Results
Definition at line 3032 of file wp-db.php.
References $i, and load_col_info().
get_col_length ($table, $column)
Retrieve the maximum string length allowed in a given column.
The length may either be specified as a byte length or a character length.
Since
4.2.1 public
Parameters
string $table Table name.
string $column Column name.
Returns
array|false|WP_Error array('length' => (int), 'type' => 'byte' | 'char') false if the column has no length (for example, numeric column) WP_Error object if there was an error.
Definition at line 2532 of file wp-db.php.
References $table_charset, get_table_charset(), and is_wp_error().
Referenced by process_field_lengths(), and strip_invalid_text_for_column().
get_results ($query = null, $output = OBJECT)
Retrieve an entire SQL result set from the database (i.e., many rows)
Executes a SQL query and returns the entire SQL result.
Since
0.71
Parameters
string $query SQL query.
string $output Optional. Any of ARRAY_A | ARRAY_N | OBJECT | OBJECT_K constants. With one of the first three, return an array of rows indexed from 0 by SQL result row number. Each row is an associative array (column => value, ...), a numerically indexed array (0 => value, ...), or an object. (->column = value), respectively. With OBJECT_K, return an associative array of row objects keyed by the value of each row's first column's value. Duplicate keys are discarded.
Returns
array|object|null Database query results
Definition at line 2306 of file wp-db.php.
References $last_result, $output, ARRAY_A, ARRAY_N, check_safe_collation(), elseif, null, OBJECT, OBJECT_K, and query().
Referenced by get_table_charset().
get_row ($query = null, $output = OBJECT, $y = 0)
Retrieve one row from the database.
Executes a SQL query and returns the row from the SQL result.
Since
0.71
Parameters
string | null $query SQL query.
string $output Optional. one of ARRAY_A | ARRAY_N | OBJECT constants. Return an associative array (column => value, ...), a numerically indexed array (0 => value, ...) or an object (->column = value), respectively.
int $y Optional. Row to return. Indexed from 0.
Returns
array|object|null|void Database query result in format specified by $output or null on failure
Definition at line 2231 of file wp-db.php.
References $output, ARRAY_A, ARRAY_N, check_safe_collation(), elseif, null, OBJECT, print_error(), and query().
Referenced by strip_invalid_text().
get_table_charset ($table) protected
Retrieves the character set for the given table.
Since
4.2.0 protected
Parameters
string $table Table name.
Returns
string|WP_Error Table character set, WP_Error object if it couldn't be found.
Filter the table charset value before the DB is checked.
Passing a non-null value to the filter will effectively short-circuit checking the DB for the charset, returning that value instead.
Since
4.2.0
Parameters
string $charset The character set to use. Default null.
string $table The name of the table being checked.
Definition at line 2363 of file wp-db.php.
References $charset, $columns, $count, apply_filters(), elseif, get_results(), has_cap(), and null.
Referenced by check_safe_collation(), get_col_charset(), get_col_length(), and strip_invalid_text_from_query().
get_table_from_query ($query) protected
Find the first table name referenced in a query.
Since
4.2.0 protected
Parameters
string $query The query to search.
Returns
string|false $table The table name found, or false if a table couldn't be found.
Definition at line 2948 of file wp-db.php.
References str_replace.
Referenced by check_safe_collation(), and strip_invalid_text_from_query().
get_var ($query = null, $x = 0, $y = 0)
Retrieve one variable from the database.
Executes a SQL query and returns the value from the SQL result. If the SQL result contains more than one column and/or more than one row, this function returns the value in the column and row specified. If $query is null, this function returns the value in the specified column and row from the previous SQL result.
Since
0.71
Parameters
string | null $query Optional. SQL query. Defaults to null, use the result from the previous query.
int $x Optional. Column of value to return. Indexed from 0.
int $y Optional. Row of value to return. Indexed from 0.
Returns
string|null Database query result (as string), or null on failure
Definition at line 2196 of file wp-db.php.
References check_safe_collation(), null, and query().
Referenced by get_col().
has_cap ($db_cap)
Determine if a database supports a particular feature.
Since
2.7.0
4.1.0 Support was added for the 'utf8mb4' feature.
See also
wpdb::db_version()
Parameters
string $db_cap The feature to check for. Accepts 'collation', 'group_concat', 'subqueries', 'set_charset', or 'utf8mb4'.
Returns
int|false Whether the database feature is supported, false otherwise.
Definition at line 3161 of file wp-db.php.
Referenced by get_table_charset(), init_charset(), and set_charset().
hide_errors ()
Disables showing of database errors.
By default database errors are not shown.
Since
0.71
See also
wpdb::show_errors()
Returns
bool Whether showing of errors was active
Definition at line 1389 of file wp-db.php.
References $show_errors, and show_errors().
init_charset ()
Set $this->charset and $this->collate.
Since
3.1.0
Definition at line 736 of file wp-db.php.
References DB_CHARSET, DB_COLLATE, elseif, has_cap(), and is_multisite().
Referenced by db_connect().
insert ($table, $data, $format = null)
Insert a row into a table.
wpdb::insert('table', array('column' => 'foo', 'field' => 'bar')) wpdb::insert('table', array('column' => 'foo', 'field' => 1337), array('s', 'd'))
Since
2.5.0
See also
wpdb::prepare()
wpdb::$field_types
wp_set_wpdb_vars()
Parameters
string $table Table name
array $data Data to insert (in column => value pairs). Both $data columns and $data values should be "raw" (neither should be SQL escaped). Sending a null value will cause the column to be set to NULL - the corresponding format is ignored in this case.
array | string $format Optional. An array of formats to be mapped to each of the value in $data. If string, that format will be used for all of the values in $data. A format is one of 'd', 'f', 's' (integer, float, string). If omitted, all values in $data will be treated as strings unless otherwise specified in wpdb::$field_types.
Returns
int|false The number of rows inserted, or false on error.
Definition at line 1833 of file wp-db.php.
References $format, and _insert_replace_helper().
load_col_info () protected
Load the column metadata from the last query.
Since
3.5.0
protected
Definition at line 3006 of file wp-db.php.
References $i.
Referenced by __get(), and get_col_info().
prepare ($query, $args)
Prepares a SQL query for safe execution.
Uses sprintf()-like syntax.
The following directives can be used in the query format string: d (integer) f (float) s (string) %% (literal percentage sign - no argument needed)
All of d, f, and s are to be left unquoted in the query string and they need an argument passed for them. Literals (%) as parts of the query must be properly written as %%.
This function only supports a small subset of the sprintf syntax; it only supports d (integer), f (float), and s (string). Does not support sign, padding, alignment, width or precision specifiers. Does not support argument numbering/swapping.
May be called like sprintf() or like vsprintf().
Both d and s should be left unquoted in the query string.
wpdb::prepare("SELECT * FROM `table` WHERE `column` = %s AND `field` = %d", 'foo', 1337)
wpdb::prepare("SELECT DATE_FORMAT(`field`, '%%c') FROM `table` WHERE `column` = %s", 'foo');
Description of syntax. 2.3.0 string $query Query statement with sprintf()-like placeholders array|mixed $args The array of variables to substitute into the query's placeholders if being called like http://php.net/vsprintf vsprintf()}, or the first variable to substitute into the query's placeholders if being called like http://php.net/sprintf sprintf()}. mixed $args,... further variables to substitute into the query's placeholders if being called like http://php.net/sprintf sprintf()}. string|void Sanitized query string, if there is a query to prepare.
Definition at line 1246 of file wp-db.php.
References __, _doing_it_wrong(), and str_replace.
Referenced by _insert_replace_helper(), delete(), set_charset(), strip_invalid_text(), and update().
print_error ($str = '')
Print SQL/DB error.
Since
0.71 array $EZSQL_ERROR Stores error information of query and error string
Parameters
string $str The error to display
Returns
false|void False if the showing of errors is disabled.
Definition at line 1303 of file wp-db.php.
References $msg, __, get_caller(), is_multisite(), show_errors(), suppress_errors(), wp_die(), and wp_load_translations_early().
Referenced by get_row(), and query().
process_field_charsets ($data, $table) protected
Adds field charsets to field/value/format arrays generated by the wpdb::process_field_formats() method.
Since
4.2.0 protected
Parameters
array $data As it comes from the wpdb::process_field_formats() method.
string $table Table name.
Returns
array|false The same array as $data with additional 'charset' keys.
Definition at line 2129 of file wp-db.php.
References $field, $value, get_col_charset(), and is_wp_error().
Referenced by process_fields().
process_field_formats ($data, $format) protected
Prepares arrays of value/format pairs as passed to wpdb CRUD methods.
Since
4.2.0 protected
Parameters
array $data Array of fields to values.
mixed $format Formats to be mapped to the values in $data.
Returns
array Array, keyed by field names with values being an array of 'value' and 'format' keys.
Definition at line 2094 of file wp-db.php.
References $field, $format, $value, and elseif.
Referenced by process_fields().
process_field_lengths ($data, $table) protected
For string fields, record the maximum string length that field can safely save.
Since
4.2.1 protected
Parameters
array $data As it comes from the wpdb::process_field_charsets() method.
string $table Table name.
Returns
array|false The same array as $data with additional 'length' keys, or false if any of the values were too long for their corresponding field.
Definition at line 2161 of file wp-db.php.
References $field, $value, get_col_length(), and is_wp_error().
Referenced by process_fields().
process_fields ($table, $data, $format) protected
Processes arrays of field/value pairs and field formats.
This is a helper method for wpdb's CRUD methods, which take field/value pairs for inserts, updates, and where clauses. This method first pairs each value with a format. Then it determines the charset of that field, using that to determine if any invalid text would be stripped. If text is stripped, then field processing is rejected and the query fails.
Since
4.2.0 protected
Parameters
string $table Table name.
array $data Field/value pair.
mixed $format Format for each field.
Returns
array|false Returns an array of fields that contain paired values and formats. Returns false for invalid values.
Definition at line 2058 of file wp-db.php.
References $format, process_field_charsets(), process_field_formats(), process_field_lengths(), and strip_invalid_text().
Referenced by _insert_replace_helper(), delete(), and update().
query ($query)
Perform a MySQL database query, using current database connection.
More information can be found on the codex page.
Since
0.71
Parameters
string $query Database query
Returns
int|false Number of rows affected/selected or false on error
Filter the database query.
Some queries are made before the plugins have been loaded, and thus cannot be filtered with this method.
Since
2.1.0
Parameters
string $query Database query.
Definition at line 1667 of file wp-db.php.
References $num_rows, $result, $rows_affected, _do_query(), apply_filters(), check_ascii(), check_connection(), elseif, flush(), print_error(), and strip_invalid_text_from_query().
Referenced by _insert_replace_helper(), delete(), get_col(), get_results(), get_row(), get_var(), and update().
replace ($table, $data, $format = null)
Replace a row into a table.
wpdb::replace('table', array('column' => 'foo', 'field' => 'bar')) wpdb::replace('table', array('column' => 'foo', 'field' => 1337), array('s', 'd'))
Since
3.0.0
See also
wpdb::prepare()
wpdb::$field_types
wp_set_wpdb_vars()
Parameters
string $table Table name
array $data Data to insert (in column => value pairs). Both $data columns and $data values should be "raw" (neither should be SQL escaped). Sending a null value will cause the column to be set to NULL - the corresponding format is ignored in this case.
array | string $format Optional. An array of formats to be mapped to each of the value in $data. If string, that format will be used for all of the values in $data. A format is one of 'd', 'f', 's' (integer, float, string). If omitted, all values in $data will be treated as strings unless otherwise specified in wpdb::$field_types.
Returns
int|false The number of rows affected, or false on error.
Definition at line 1858 of file wp-db.php.
References $format, and _insert_replace_helper().
select ($db, $dbh = null)
Selects a database using the current database connection.
The database name will be changed based on the current database connection. On failure, the execution will bail and display an DB error.
Since
0.71
Parameters
string $db MySQL database name
resource | null $dbh Optional link identifier.
Definition at line 1042 of file wp-db.php.
References $dbh, $message, __, bail(), did_action(), and wp_load_translations_early().
Referenced by db_connect().
set_blog_id ($blog_id, $site_id = 0)
Sets blog id.
Since
3.0.0 public
Parameters
int $blog_id
int $site_id Optional.
Returns
int previous blog id
Definition at line 916 of file wp-db.php.
References $blog_id, $blogid, get_blog_prefix(), and tables().
set_charset ($dbh, $charset = null, $collate = null)
Sets the connection's character set.
Since
3.1.0
Parameters
resource $dbh The resource given by mysql_connect
string $charset Optional. The character set. Default null.
string $collate Optional. The collation. Default null.
Definition at line 774 of file wp-db.php.
References $charset, $collate, $dbh, has_cap(), and prepare().
Referenced by db_connect().
set_prefix ($prefix, $set_table_names = true)
Sets the table prefix for the WordPress tables.
Since
2.5.0
Parameters
string $prefix Alphanumeric name for the new prefix.
bool $set_table_names Optional. Whether the table names, e.g. wpdb::$posts, should be updated or not.
Returns
string|WP_Error Old prefix or WP_Error on error
Definition at line 876 of file wp-db.php.
References $base_prefix, $prefix, get_blog_prefix(), is_multisite(), and tables().
set_sql_mode ($modes = array())
Change the current SQL mode, and ensure its WordPress compatibility.
If no modes are passed, it will ensure the current MySQL server modes are compatible.
Since
3.9.0
Parameters
array $modes Optional. A list of SQL modes to set.
Filter the list of incompatible SQL modes to exclude.
Since
3.9.0
Parameters
array $incompatible_modes An array of incompatible modes.
Definition at line 812 of file wp-db.php.
References $i, $incompatible_modes, $mode, $modes, and apply_filters().
Referenced by db_connect().
show_errors ($show = true)
Enables showing of database errors.
This function should be used only to enable showing of errors. wpdb::hide_errors() should be used instead for hiding of errors. However, this function can be used to enable and disable showing of database errors.
Since
0.71
See also
wpdb::hide_errors()
Parameters
bool $show Whether to show or hide errors
Returns
bool Old value for showing errors.
Definition at line 1373 of file wp-db.php.
References $errors, and $show_errors.
Referenced by __construct(), hide_errors(), and print_error().
strip_invalid_text ($data) protected
Strips any invalid characters based on value/charset pairs.
Since
4.2.0 protected
Parameters
array $data Array of value arrays. Each value array has the keys 'value' and 'charset'. An optional 'ascii' key can be set to false to avoid redundant ASCII checks.
Returns
array|WP_Error The $data parameter, with invalid characters removed from each value. This works as a passthrough: any additional keys such as 'field' are retained in each value array. If we cannot remove invalid characters, a WP_Error object is returned.
Definition at line 2706 of file wp-db.php.
References $charset, $value, ARRAY_A, check_ascii(), get_row(), mbstring_binary_safe_encoding(), prepare(), and reset_mbstring_encoding().
Referenced by process_fields(), strip_invalid_text_for_column(), and strip_invalid_text_from_query().
strip_invalid_text_for_column ($table, $column, $value)
Strips any invalid characters from the string for a given table and column.
Since
4.2.0 public
Parameters
string $table Table name.
string $column Column name.
string $value The text to check.
Returns
string|WP_Error The converted string, or a WP_Error object if the conversion fails.
Definition at line 2909 of file wp-db.php.
References $charset, $value, elseif, get_col_charset(), get_col_length(), is_wp_error(), and strip_invalid_text().
strip_invalid_text_from_query ($query) protected
Strips any invalid characters from the query.
Since
4.2.0 protected
Parameters
string $query Query to convert.
Returns
string|WP_Error The converted query, or a WP_Error object if the conversion fails.
Definition at line 2861 of file wp-db.php.
References $charset, get_table_charset(), get_table_from_query(), is_wp_error(), and strip_invalid_text().
Referenced by query().
supports_collation ()
Whether the database supports collation.
Called when WordPress is generating the table scheme.
Use `wpdb::has_cap('collation')`.
Since
2.5.0
Returns
bool True if collation is supported, false if version does not
Definition at line 3125 of file wp-db.php.
References _deprecated_function().
suppress_errors ($suppress = true)
Whether to suppress database errors.
By default database errors are suppressed, with a simple call to this function they can be enabled.
Since
2.5.0
See also
wpdb::hide_errors()
Parameters
bool $suppress Optional. New value. Defaults to true.
Returns
bool Old value
Definition at line 1406 of file wp-db.php.
References $errors, and $suppress_errors.
Referenced by print_error().
tables ($scope = 'all', $prefix = true, $blog_id = 0)
Returns an array of WordPress tables.
Also allows for the CUSTOM_USER_TABLE and CUSTOM_USER_META_TABLE to override the WordPress users and usermeta tables that would otherwise be determined by the prefix.
The scope argument can take one of the following:
'all' - returns 'all' and 'global' tables. No old tables are returned. 'blog' - returns the blog-level tables for the queried blog. 'global' - returns the global tables for the installation, returning multisite tables only if running multisite. 'ms_global' - returns the multisite global tables, regardless if current installation is multisite. 'old' - returns tables which are deprecated.
Since
3.0.0 wpdb::$tables wpdb::$old_tables wpdb::$global_tables wpdb::$ms_global_tables
Parameters
string $scope Optional. Can be all, global, ms_global, blog, or old tables. Defaults to all.
bool $prefix Optional. Whether to include table prefixes. Default true. If blog prefix is requested, then the custom users and usermeta tables will be mapped.
int $blog_id Optional. The blog_id to prefix. Defaults to wpdb::$blogid. Used only when prefix is requested.
Returns
array Table names. When a prefix is requested, the key is the unprefixed table name.
Definition at line 982 of file wp-db.php.
References $base_prefix, $blog_id, $blogid, $global_tables, $ms_global_tables, $old_tables, $prefix, $tables, get_blog_prefix(), and is_multisite().
Referenced by set_blog_id(), and set_prefix().
timer_start ()
Starts the timer, for debugging purposes.
Since
1.5.0
Returns
true
Definition at line 3057 of file wp-db.php.
Referenced by _do_query().
timer_stop ()
Stops the debugging timer.
Since
1.5.0
Returns
float Total time spent on the query, in seconds
Definition at line 3069 of file wp-db.php.
Referenced by _do_query().
update ($table, $data, $where, $format = null, $where_format = null)
Update a row in the table.
wpdb::update('table', array('column' => 'foo', 'field' => 'bar'), array('ID' => 1)) wpdb::update('table', array('column' => 'foo', 'field' => 1337), array('ID' => 1), array('s', 'd'), array('d'))
Since
2.5.0
See also
wpdb::prepare()
wpdb::$field_types
wp_set_wpdb_vars()
Parameters
string $table Table name
array $data Data to update (in column => value pairs). Both $data columns and $data values should be "raw" (neither should be SQL escaped). Sending a null value will cause the column to be set to NULL - the corresponding format is ignored in this case.
array $where A named array of WHERE clauses (in column => value pairs). Multiple clauses will be joined with ANDs. Both $where columns and $where values should be "raw". Sending a null value will create an IS NULL comparison - the corresponding format will be ignored in this case.
array | string $format Optional. An array of formats to be mapped to each of the values in $data. If string, that format will be used for all of the values in $data. A format is one of 'd', 'f', 's' (integer, float, string). If omitted, all values in $data will be treated as strings unless otherwise specified in wpdb::$field_types.
array | string $where_format Optional. An array of formats to be mapped to each of the values in $where. If string, that format will be used for all of the items in $where. A format is one of 'd', 'f', 's' (integer, float, string). If omitted, all values in $where will be treated as strings.
Returns
int|false The number of rows updated, or false on error.
Definition at line 1946 of file wp-db.php.
References $field, $format, $value, prepare(), process_fields(), and query().
Field Documentation
$base_prefix
Definition at line 231 of file wp-db.php.
Referenced by get_blog_prefix(), set_prefix(), and tables().
$blog_versions
Definition at line 432 of file wp-db.php.
$blogid = 0
Definition at line 249 of file wp-db.php.
Referenced by get_blog_prefix(), set_blog_id(), and tables().
$blogs
Definition at line 423 of file wp-db.php.
$charset
Definition at line 502 of file wp-db.php.
Referenced by get_col_charset(), get_table_charset(), set_charset(), strip_invalid_text(), strip_invalid_text_for_column(), and strip_invalid_text_from_query().
$check_current_query = true protected
Definition at line 171 of file wp-db.php.
$checking_collation = false private
Definition at line 181 of file wp-db.php.
$col_info protected
Definition at line 190 of file wp-db.php.
$col_meta = array() protected
Definition at line 153 of file wp-db.php.
$collate
Definition at line 511 of file wp-db.php.
Referenced by set_charset().
$commentmeta
Definition at line 320 of file wp-db.php.
$comments
Definition at line 311 of file wp-db.php.
$dbh protected
Definition at line 556 of file wp-db.php.
Referenced by select(), and set_charset().
$dbhost protected
Definition at line 547 of file wp-db.php.
Referenced by __construct(), and db_connect().
$dbname protected
Definition at line 538 of file wp-db.php.
Referenced by __construct().
$dbpassword protected
Definition at line 529 of file wp-db.php.
Referenced by __construct().
$dbuser protected
Definition at line 520 of file wp-db.php.
Referenced by __construct().
$field_types = array()
Definition at line 493 of file wp-db.php.
$func_call
Definition at line 565 of file wp-db.php.
$global_tables = array('users', 'usermeta')
Definition at line 291 of file wp-db.php.
Referenced by tables().
$has_connected = false private
Definition at line 607 of file wp-db.php.
$incompatible_modes protected
Initial value:
= array('NO_ZERO_DATE', 'ONLY_FULL_GROUP_BY',
        'STRICT_TRANS_TABLES', 'STRICT_ALL_TABLES', 'TRADITIONAL' )
Definition at line 588 of file wp-db.php.
Referenced by set_sql_mode().
$insert_id = 0
Definition at line 117 of file wp-db.php.
$is_mysql = null
Definition at line 579 of file wp-db.php.
$last_error = ''
Definition at line 81 of file wp-db.php.
$last_query
Definition at line 126 of file wp-db.php.
$last_result
Definition at line 135 of file wp-db.php.
Referenced by get_results().
$links
Definition at line 329 of file wp-db.php.
$ms_global_tables
Initial value:
= array('blogs', 'signups', 'site', 'sitemeta',
        'sitecategories', 'registration_log', 'blog_versions' )
Definition at line 301 of file wp-db.php.
Referenced by tables().
$num_queries = 0
Definition at line 90 of file wp-db.php.
$num_rows = 0
Definition at line 99 of file wp-db.php.
Referenced by query().
$old_tables = array('categories', 'post2cat', 'link2cat')
Definition at line 281 of file wp-db.php.
Referenced by tables().
$options
Definition at line 338 of file wp-db.php.
$postmeta
Definition at line 347 of file wp-db.php.
$posts
Definition at line 356 of file wp-db.php.
$prefix = ''
Definition at line 222 of file wp-db.php.
Referenced by set_prefix(), and tables().
$queries
Definition at line 199 of file wp-db.php.
$ready = false
Definition at line 240 of file wp-db.php.
$reconnect_retries = 5 protected
Definition at line 209 of file wp-db.php.
Referenced by check_connection().
$registration_log
Definition at line 441 of file wp-db.php.
$result protected
Definition at line 144 of file wp-db.php.
Referenced by query().
$rows_affected = 0
Definition at line 108 of file wp-db.php.
Referenced by query().
$show_errors = false
Definition at line 64 of file wp-db.php.
Referenced by hide_errors(), and show_errors().
$signups
Definition at line 450 of file wp-db.php.
$site
Definition at line 459 of file wp-db.php.
$sitecategories
Definition at line 468 of file wp-db.php.
$siteid = 0
Definition at line 258 of file wp-db.php.
$sitemeta
Definition at line 477 of file wp-db.php.
$suppress_errors = false
Definition at line 73 of file wp-db.php.
Referenced by suppress_errors().
$table_charset = array() protected
Definition at line 162 of file wp-db.php.
Referenced by get_col_charset(), and get_col_length().
$tables
Initial value:
= array('posts', 'comments', 'links', 'options', 'postmeta',
        'terms', 'term_taxonomy', 'term_relationships', 'termmeta', 'commentmeta' )
Definition at line 268 of file wp-db.php.
Referenced by tables().
$term_relationships
Definition at line 374 of file wp-db.php.
$term_taxonomy
Definition at line 383 of file wp-db.php.
$termmeta
Definition at line 392 of file wp-db.php.
$terms
Definition at line 365 of file wp-db.php.
$use_mysqli = false private
Definition at line 598 of file wp-db.php.
$usermeta
Definition at line 405 of file wp-db.php.
$users
Definition at line 414 of file wp-db.php.
The documentation for this class was generated from the following file:
wp-db.php