GravityView: WP_Error Class Reference
WP_Error Class Reference
Public Member Functions
__construct ($code= '', $message= '', $data= '')
Initialize the error.
add ($code, $message, $data= '')
Add an error or append additional message to an existing error.
add_data ($data, $code= '')
Add data for error code.
get_error_code ()
Retrieve first error code available.
get_error_codes ()
Retrieve all error codes.
get_error_data ($code= '')
Retrieve error data for error code.
get_error_message ($code= '')
Get single error message.
get_error_messages ($code= '')
Retrieve all error messages or error messages matching code.
remove ($code)
Removes the specified error.
Data Fields
$error_data = array()
$errors = array()
Detailed Description
Definition at line 21 of file class-wp-error.php.
Constructor & Destructor Documentation
__construct ($code = '', $message = '', $data = '')
Initialize the error.
If $code is empty, the other parameters will be ignored. When $code is not empty, $message will be used even if it is empty. The $data parameter will be used only if it is not empty.
Though the class is constructed with a single error code and message, multiple codes can be added using the add() method.
Since
2.1.0
Parameters
string | int $code Error code
string $message Error message
mixed $data Optional. Error data.
Definition at line 55 of file class-wp-error.php.
References $message.
Member Function Documentation
add ($code, $message, $data = '')
Add an error or append additional message to an existing error.
Since
2.1.0 public
Parameters
string | int $code Error code.
string $message Error message.
mixed $data Optional. Error data.
Definition at line 167 of file class-wp-error.php.
References $message.
Referenced by update_core().
add_data ($data, $code = '')
Add data for error code.
The error code can only contain one error data.
Since
2.1.0
Parameters
mixed $data Error data.
string | int $code Error code.
Definition at line 183 of file class-wp-error.php.
References get_error_code().
get_error_code ()
Retrieve first error code available.
Since
2.1.0 public
Returns
string|int Empty string, if no error codes.
Definition at line 88 of file class-wp-error.php.
References get_error_codes().
Referenced by add_data(), get_error_data(), and get_error_message().
get_error_codes ()
Retrieve all error codes.
Since
2.1.0 public
Returns
array List of error codes, if available.
Definition at line 73 of file class-wp-error.php.
Referenced by get_error_code().
get_error_data ($code = '')
Retrieve error data for error code.
Since
2.1.0
Parameters
string | int $code Optional. Error code.
Returns
mixed Error data, if it exists.
Definition at line 149 of file class-wp-error.php.
References get_error_code().
get_error_message ($code = '')
Get single error message.
This will get the first message available for the code. If no code is given then the first code available will be used.
Since
2.1.0
Parameters
string | int $code Optional. Error code to retrieve message.
Returns
string
Definition at line 132 of file class-wp-error.php.
References $messages, get_error_code(), and get_error_messages().
get_error_messages ($code = '')
Retrieve all error messages or error messages matching code.
Since
2.1.0
Parameters
string | int $code Optional. Retrieve messages matching code, if exists.
Returns
array Error strings on success, or empty array on failure (if using code parameter).
Definition at line 105 of file class-wp-error.php.
References $messages.
Referenced by get_error_message().
remove ($code)
Removes the specified error.
This function removes all error messages associated with the specified error code, along with any error data for that code.
Since
4.1.0
Parameters
string | int $code Error code.
Definition at line 200 of file class-wp-error.php.
Field Documentation
$error_data = array()
Definition at line 36 of file class-wp-error.php.
$errors = array()
Definition at line 28 of file class-wp-error.php.
The documentation for this class was generated from the following file:
class-wp-error.php