GravityView: SimplePie_Decode_HTML_Entities Class Reference
SimplePie_Decode_HTML_Entities Class Reference
Public Member Functions
__construct ($data)
Create an instance of the class with the input data.
consume ()
Consume the next byte.
consume_range ($chars)
Consume a range of characters.
entity ()
Decode an entity.
parse ()
Parse the input data.
unconsume ()
Unconsume one byte.
Data Fields
$consumed = ''
$data = ''
$position = 0
Detailed Description
Definition at line 54 of file Entities.php.
Constructor & Destructor Documentation
__construct ($data)
Create an instance of the class with the input data.
public
Parameters
string $data Input data
Definition at line 86 of file Entities.php.
References $data.
Member Function Documentation
consume ()
Consume the next byte.
private
Returns
mixed The next byte, or false, if there is no more data
Definition at line 114 of file Entities.php.
References $position.
Referenced by entity(), and parse().
consume_range ($chars)
Consume a range of characters.
private
Parameters
string $chars Characters to consume
Returns
mixed A series of characters that match the range, or false
Definition at line 134 of file Entities.php.
References $data.
Referenced by entity().
entity ()
Decode an entity.
private
Definition at line 165 of file Entities.php.
References $consumed, $i, SimplePie_Misc\codepoint_to_utf8(), consume(), consume_range(), null, and unconsume().
Referenced by parse().
parse ()
Parse the input data.
public
Returns
string Output data
Definition at line 97 of file Entities.php.
References $data, consume(), and entity().
unconsume ()
Unconsume one byte.
private
Definition at line 154 of file Entities.php.
Referenced by entity().
Field Documentation
$consumed = ''
Definition at line 70 of file Entities.php.
Referenced by entity().
$data = ''
Definition at line 62 of file Entities.php.
Referenced by __construct(), consume_range(), and parse().
$position = 0
Definition at line 78 of file Entities.php.
Referenced by consume().
The documentation for this class was generated from the following file:
Entities.php