GravityView: WP_Customize_Nav_Menus Class Reference
WP_Customize_Nav_Menus Class Reference
Customize Nav Menus class.
Public Member Functions
__construct ($manager)
Constructor.
ajax_load_available_items ()
Ajax handler for loading available menu items.
ajax_search_available_items ()
Ajax handler for searching available menu items.
available_item_types ()
Return an array of all the available item types.
available_items_template ()
Print the html template used to render the add-menu-item frame.
customize_preview_enqueue_deps ()
Enqueue scripts for the Customizer preview.
customize_preview_init ()
Add hooks for the Customizer preview.
customize_register ()
Add the customizer settings and controls.
enqueue_scripts ()
Enqueue scripts and styles for Customizer pane.
export_preview_data ()
Export data from PHP to JS.
filter_dynamic_setting_args ($setting_args, $setting_id)
Filter a dynamic setting's constructor args.
filter_dynamic_setting_class ($setting_class, $setting_id, $setting_args)
Allow non-statically created settings to be constructed with custom WP_Customize_Setting subclass.
filter_wp_nav_menu ($nav_menu_content, $args)
Prepare wp_nav_menu() calls for partial refresh.
filter_wp_nav_menu_args ($args)
Keep track of the arguments that are being passed to wp_nav_menu().
hash_nav_menu_args ($args)
Hash (hmac) the arguments with the nonce and secret auth key to ensure they are not tampered with when submitted in the Ajax request.
intval_base10 ($value)
Get the base10 intval.
load_available_items_query ($type= 'post_type', $object= 'page', $page=0)
Performs the post_type and taxonomy queries for loading available menu items.
print_templates ()
Print the JavaScript templates used to render Menu Customizer components.
render_menu ()
Render a specific menu via wp_nav_menu() using the supplied arguments.
search_available_items_query ($args=array())
Performs post queries for available-item searching.
Data Fields
$manager
$preview_nav_menu_instance_args = array()
$preview_nav_menu_instance_number = 0
$previewed_menus
const RENDER_AJAX_ACTION = 'customize_render_menu_partial'
const RENDER_NONCE_POST_KEY = 'render-menu-nonce'
const RENDER_QUERY_VAR = 'wp_customize_menu_render'
Detailed Description
Customize Nav Menus class.
Implements menu management in the Customizer.
Since
4.3.0
See also
WP_Customize_Manager
Definition at line 19 of file class-wp-customize-nav-menus.php.
Constructor & Destructor Documentation
__construct ($manager)
Constructor.
Since
4.3.0 public
Parameters
object $manager An instance of the WP_Customize_Manager class.
Definition at line 47 of file class-wp-customize-nav-menus.php.
References $manager, add_action(), and add_filter().
Member Function Documentation
ajax_load_available_items ()
Ajax handler for loading available menu items.
Since
4.3.0 public
Definition at line 71 of file class-wp-customize-nav-menus.php.
References $page, absint(), current_user_can(), is_wp_error(), load_available_items_query(), sanitize_key(), wp_die(), wp_send_json_error(), and wp_send_json_success().
ajax_search_available_items ()
Ajax handler for searching available menu items.
Since
4.3.0 public
Definition at line 211 of file class-wp-customize-nav-menus.php.
References $s, __, absint(), current_user_can(), sanitize_text_field(), search_available_items_query(), wp_die(), wp_send_json_error(), wp_send_json_success(), and wp_unslash().
available_item_types ()
Return an array of all the available item types.
Since
4.3.0 public
Returns
array The available menu item types.
Filter the available menu item types.
Since
4.3.0
Parameters
array $item_types Custom menu item types.
Definition at line 620 of file class-wp-customize-nav-menus.php.
References $post_type, apply_filters(), current_theme_supports(), get_post_types(), and get_taxonomies().
Referenced by available_items_template(), and enqueue_scripts().
available_items_template ()
Print the html template used to render the add-menu-item frame.
Since
4.3.0 public
Definition at line 711 of file class-wp-customize-nav-menus.php.
References $id, __, _e, available_item_types(), esc_html, input, label, name, placeholder, and role.
customize_preview_enqueue_deps ()
Enqueue scripts for the Customizer preview.
Since
4.3.0 public
Definition at line 926 of file class-wp-customize-nav-menus.php.
References add_action(), wp_enqueue_script(), and wp_enqueue_style().
customize_preview_init ()
Add hooks for the Customizer preview.
Since
4.3.0 public
Definition at line 823 of file class-wp-customize-nav-menus.php.
References add_action(), and add_filter().
customize_register ()
Add the customizer settings and controls.
Since
4.3.0 public
Definition at line 452 of file class-wp-customize-nav-menus.php.
References $description, $i, $location, $locations, $menu, $menu_items, $num_locations, $value, __, _n(), add_filter(), current_theme_supports(), get_bloginfo(), get_registered_nav_menus(), number_format_i18n(), remove_filter(), wp_get_nav_menu_items(), wp_get_nav_menus(), and wp_html_excerpt().
enqueue_scripts ()
Enqueue scripts and styles for Customizer pane.
Since
4.3.0 public
Definition at line 323 of file class-wp-customize-nav-menus.php.
References $nav_menus_l10n, __, _x, available_item_types(), esc_attr__(), esc_html, null, wp_enqueue_script(), wp_enqueue_style(), wp_get_nav_menus(), wp_json_encode(), wp_localize_script(), and wp_scripts().
export_preview_data ()
Export data from PHP to JS.
Since
4.3.0 public
Definition at line 939 of file class-wp-customize-nav-menus.php.
References $_SERVER, esc_url_raw(), home_url(), wp_json_encode(), and wp_unslash().
filter_dynamic_setting_args ($setting_args, $setting_id)
Filter a dynamic setting's constructor args.
For a dynamic setting to be registered, this filter must be employed to override the default false value with an array of args to pass to the WP_Customize_Setting constructor.
Since
4.3.0 public
Parameters
false | array $setting_args The arguments to the WP_Customize_Setting constructor.
string $setting_id ID for dynamic setting, usually coming from `$_POST['customized']`.
Returns
array|false
Definition at line 411 of file class-wp-customize-nav-menus.php.
References elseif, WP_Customize_Nav_Menu_Item_Setting\ID_PATTERN, WP_Customize_Nav_Menu_Setting\ID_PATTERN, WP_Customize_Nav_Menu_Item_Setting\TYPE, and WP_Customize_Nav_Menu_Setting\TYPE.
filter_dynamic_setting_class ($setting_class, $setting_id, $setting_args)
Allow non-statically created settings to be constructed with custom WP_Customize_Setting subclass.
Since
4.3.0 public
Parameters
string $setting_class WP_Customize_Setting or a subclass.
string $setting_id ID for dynamic setting, usually coming from `$_POST['customized']`.
array $setting_args WP_Customize_Setting or a subclass.
Returns
string
Definition at line 435 of file class-wp-customize-nav-menus.php.
References elseif, WP_Customize_Nav_Menu_Item_Setting\TYPE, and WP_Customize_Nav_Menu_Setting\TYPE.
filter_wp_nav_menu ($nav_menu_content, $args)
Prepare wp_nav_menu() calls for partial refresh.
Wraps output in container for refreshing.
Since
4.3.0 public
See also
wp_nav_menu()
Parameters
string $nav_menu_content The HTML content for the navigation menu.
object $args An object containing wp_nav_menu() arguments.
Returns
null
Definition at line 894 of file class-wp-customize-nav-menus.php.
filter_wp_nav_menu_args ($args)
Keep track of the arguments that are being passed to wp_nav_menu().
Since
4.3.0 public
See also
wp_nav_menu()
Parameters
array $args An array containing wp_nav_menu() arguments.
Returns
array Arguments.
Definition at line 844 of file class-wp-customize-nav-menus.php.
References $preview_nav_menu_instance_number, and hash_nav_menu_args().
hash_nav_menu_args ($args)
Hash (hmac) the arguments with the nonce and secret auth key to ensure they are not tampered with when submitted in the Ajax request.
Since
4.3.0 public
Parameters
array $args The arguments to hash.
Returns
string
Definition at line 916 of file class-wp-customize-nav-menus.php.
Referenced by filter_wp_nav_menu_args(), and render_menu().
intval_base10 ($value)
Get the base10 intval.
This is used as a setting's sanitize_callback; we can't use just plain intval because the second argument is not what intval() expects.
Since
4.3.0 public
Parameters
mixed $value Number to convert.
Returns
int Integer.
Definition at line 608 of file class-wp-customize-nav-menus.php.
References $value.
load_available_items_query ($type = 'post_type', $object = 'page', $page = 0)
Performs the post_type and taxonomy queries for loading available menu items.
Since
4.3.0 public
Parameters
string $type Optional. Accepts any custom object type and has built-in support for 'post_type' and 'taxonomy'. Default is 'post_type'.
string $object Optional. Accepts any registered taxonomy or post type name. Default is 'page'.
int $page Optional. The page number used to generate the query offset. Default is '0'.
Returns
WP_Error|array Returns either a WP_Error object or an array of menu items.
Filter the available menu items.
Since
4.3.0
Parameters
array $items The array of menu items.
string $type The object type.
string $object The object name.
int $page The current page number.
Definition at line 106 of file class-wp-customize-nav-menus.php.
References $page, $post, $post_title, $post_type, __, _x, apply_filters(), elseif, get_bloginfo(), get_permalink(), get_post_type_archive_link(), get_post_type_object(), get_posts(), get_taxonomy(), get_term_link(), get_terms(), home_url(), and is_wp_error().
Referenced by ajax_load_available_items().
print_templates ()
Print the JavaScript templates used to render Menu Customizer components.
Templates are imported into the JS use wp.template.
Since
4.3.0 public
Definition at line 668 of file class-wp-customize-nav-menus.php.
References __, and li.
render_menu ()
Render a specific menu via wp_nav_menu() using the supplied arguments.
Since
4.3.0 public
See also
wp_nav_menu()
Definition at line 966 of file class-wp-customize-nav-menus.php.
References current_user_can(), hash_nav_menu_args(), is_customize_preview(), sanitize_text_field(), wp_nav_menu(), wp_send_json_error(), wp_send_json_success(), and wp_unslash().
search_available_items_query ($args = array())
Performs post queries for available-item searching.
Based on WP_Editor::wp_link_query().
Since
4.3.0 public
Parameters
array $args Optional. Accepts 'pagenum' and 's' (search) arguments.
Returns
array Menu items.
Definition at line 248 of file class-wp-customize-nav-menus.php.
References $post, $post_title, __, absint(), get_bloginfo(), get_permalink(), get_post_types(), get_taxonomies(), get_taxonomy(), get_term_link(), and get_terms().
Referenced by ajax_search_available_items().
Field Documentation
$manager
Definition at line 28 of file class-wp-customize-nav-menus.php.
Referenced by __construct().
$preview_nav_menu_instance_args = array()
Definition at line 815 of file class-wp-customize-nav-menus.php.
$preview_nav_menu_instance_number = 0
Definition at line 806 of file class-wp-customize-nav-menus.php.
Referenced by filter_wp_nav_menu_args().
$previewed_menus
Definition at line 37 of file class-wp-customize-nav-menus.php.
const RENDER_AJAX_ACTION = 'customize_render_menu_partial'
Definition at line 795 of file class-wp-customize-nav-menus.php.
const RENDER_NONCE_POST_KEY = 'render-menu-nonce'
Definition at line 796 of file class-wp-customize-nav-menus.php.
const RENDER_QUERY_VAR = 'wp_customize_menu_render'
Definition at line 797 of file class-wp-customize-nav-menus.php.
The documentation for this class was generated from the following file:
class-wp-customize-nav-menus.php