GravityView: Encryption Class Reference
Encryption Class Reference
Public Member Functions
__construct (Config $config, Remote $remote, Logging $logging)
Encryption constructor.
encrypt ($data, $nonce, $alice_secret_key)
Encrypts a string using the Public Key provided by the plugin/theme developers' server.
generate_keys ()
Generate unique Client encryption keys.
get_nonce ()
Gets and returns a random nonce.
get_vendor_public_key ()
Fetches the Public Key from local or db.
Static Public Member Functions
static get_random_hash ($logging)
Generates a random hash 64 characters long.
static hash ($string, $length=16)
Private Member Functions
get_remote_encryption_key ()
Fetches the Public Key from the TrustedLogin-vendor plugin on support website.
Private Attributes
$config
$logging
$remote
$vendor_public_key_endpoint = 'wp-json/trustedlogin/v1/public_key'
$vendor_public_key_option
Detailed Description
Definition at line 24 of file Encryption.php.
Constructor & Destructor Documentation
__construct()
__construct (Config $config, Remote $remote, Logging $logging)
Encryption constructor.
Parameters
Config $config
Remote $remote
Logging $logging
Filter: Sets the site option name for the Public Key for encryption functions
Since
1.0.0
Parameters
string $vendor_public_key_option
Config $config
Definition at line 59 of file Encryption.php.
References Encryption\$config, Encryption\$logging, and Encryption\$remote.
Member Function Documentation
encrypt()
encrypt ($data, $nonce, $alice_secret_key)
Encrypts a string using the Public Key provided by the plugin/theme developers' server.
Since
1.0.0 () to generate key. () to encrypt.
Parameters
string $data Data to encrypt.
string $nonce The nonce generated for this encryption.
string $alice_secret_key The key to use when generating the encryption key.
Returns
string|WP_Error Encrypted envelope or WP_Error on failure.
Definition at line 277 of file Encryption.php.
References Encryption\get_vendor_public_key().
generate_keys()
generate_keys ()
Generate unique Client encryption keys.
Since
1.0.0
sodium_crypto_box_keypair() sodium_crypto_box_publickey() sodium_crypto_box_secretkey()
Returns
object|WP_Error $alice_keys or WP_Error if there's any issues. $alice_keys = [ 'publicKey' => (string) The public key. 'privateKey' => (string) The private key. ]
Definition at line 355 of file Encryption.php.
get_nonce()
get_nonce ()
Gets and returns a random nonce.
Since
1.0.0
Returns
string|WP_Error Nonce if created, otherwise WP_Error
Definition at line 325 of file Encryption.php.
get_random_hash()
static get_random_hash ($logging) static
Generates a random hash 64 characters long.
If random_bytes() and openssl_random_pseudo_bytes() don't exist, returns WP_Error with code generate_hash_failed.
If random_bytes() does not exist and openssl_random_pseudo_bytes() is unable to return a strong result, returns a WP_Error with code openssl_not_strong_crypto.
random_bytes openssl_random_pseudo_bytes Only used if random_bytes() does not exist.
Parameters
Logging The logging object to use
Returns
string|WP_Error 64-character random hash or a WP_Error object explaining what went wrong. See docblock.
Definition at line 95 of file Encryption.php.
References Encryption\$logging.
Referenced by SupportUser\create(), and Client\grant_access().
get_remote_encryption_key()
get_remote_encryption_key () private
Fetches the Public Key from the TrustedLogin-vendor plugin on support website.
Since
1.0.0
Returns
string|WP_Error If successful, will return the Public Key string. Otherwise WP_Error on failure.
Parameters
string $key_endpoint Endpoint path on vendor (software vendor's) site
Definition at line 225 of file Encryption.php.
References $url, and Encryption\$vendor_public_key_endpoint.
Referenced by Encryption\get_vendor_public_key().
get_vendor_public_key()
get_vendor_public_key ()
Fetches the Public Key from local or db.
Since
1.0.0
Returns
string|WP_Error If found, it returns the publicKey, if not a WP_Error
Filter: Override the public key functions.
Since
1.0.0
Parameters
string $vendor_public_key
Config $config
Definition at line 180 of file Encryption.php.
References Encryption\$config, and Encryption\get_remote_encryption_key().
Referenced by Encryption\encrypt().
hash()
static hash ($string, $length = 16) static
Parameters
$string
Returns
string|WP_Error
Definition at line 139 of file Encryption.php.
Referenced by SiteAccess\generate_access_key(), Endpoint\generate_secret_id(), SupportUser\get(), Endpoint\get_hash(), Cron\schedule(), SupportUser\setup(), and SecurityChecks\verify().
Field Documentation
$config
Config $config private
Definition at line 29 of file Encryption.php.
Referenced by Encryption\__construct(), and Encryption\get_vendor_public_key().
$logging
$logging private
Definition at line 39 of file Encryption.php.
Referenced by Encryption\__construct(), and Encryption\get_random_hash().
$remote
Remote $remote private
Definition at line 34 of file Encryption.php.
Referenced by Encryption\__construct().
$vendor_public_key_endpoint
$vendor_public_key_endpoint = 'wp-json/trustedlogin/v1/public_key' private
Definition at line 50 of file Encryption.php.
Referenced by Encryption\get_remote_encryption_key().
$vendor_public_key_option
$vendor_public_key_option private
Definition at line 45 of file Encryption.php.
The documentation for this class was generated from the following file:
Encryption.php