GravityView: Plugin_Upgrader Class Reference
Plugin_Upgrader Class Reference
Core class used for upgrading/installing plugins.
Public Member Functions
bulk_upgrade ($plugins, $args=array())
Bulk upgrade several plugins at once.
check_package ($source)
Check a source package to be sure it contains a plugin.
deactivate_plugin_before_upgrade ($return, $plugin)
Deactivates a plugin before it is upgraded.
delete_old_plugin ($removed, $local_destination, $remote_destination, $plugin)
Delete the old plugin during an upgrade.
install ($package, $args=array())
Install a plugin package.
install_strings ()
Initialize the install strings.
plugin_info ()
Retrieve the path to the file that contains the plugin info.
upgrade ($plugin, $args=array())
Upgrade a plugin.
upgrade_strings ()
Initialize the upgrade strings.
Public Member Functions inherited from WP_Upgrader
__construct ($skin=null)
Construct the upgrader with a skin.
clear_destination ($remote_destination)
Clears the directory where this item is going to be installed into.
download_package ($package)
Download a package.
fs_connect ($directories=array(), $allow_relaxed_file_ownership=false)
Connect to the filesystem.
generic_strings ()
Add the generic strings to WP_Upgrader::$strings.
init ()
Initialize the upgrader.
install_package ($args=array())
Install a package.
maintenance_mode ($enable=false)
Toggle maintenance mode for the site.
run ($options)
Run an upgrade/install.
unpack_package ($package, $delete_package=true)
Unpack a compressed package file.
Data Fields
$bulk = false
Whether a bulk upgrade/install is being performed.
$result
Plugin upgrade result.
Data Fields inherited from WP_Upgrader
$result = array()
$skin = null
The upgrader skin being used.
$strings = array()
The error/notification strings used to update the user on the progress.
$update_count = 0
The total number of updates being performed.
$update_current = 0
Detailed Description
Core class used for upgrading/installing plugins.
It is designed to upgrade/install plugins from a local zip, remote zip URL, or uploaded zip file.
Since
2.8.0
See also
WP_Upgrader
Definition at line 766 of file class-wp-upgrader.php.
Member Function Documentation
bulk_upgrade ($plugins, $args = array())
Bulk upgrade several plugins at once.
Since
2.8.0
3.7.0 The $args parameter was added, making clearing the plugin update cache optional. public
Parameters
array $plugins Array of the basename paths of the plugins' main files.
array $args { Optional. Other arguments for upgrading several plugins at once. Default empty array.
bool $clear_update_cache Whether to clear the plugin updates cache if successful. Default true. }
Returns
array|false An array of results indexed by plugin file, or false if unable to connect to the filesystem.
Fires when the bulk upgrader process is complete.
Since
3.6.0
Parameters
Plugin_Upgrader $this Plugin_Upgrader instance. In other contexts, $this, might be a Theme_Upgrader or Core_Upgrade instance.
array $data { Array of bulk item update data.
string $action Type of action. Default 'update'. string $type Type of update process. Accepts 'plugin', 'theme', or 'core'. bool $bulk Whether the update process is a bulk update. Default true. array $packages Array of plugin, theme, or core packages to update. }
Definition at line 958 of file class-wp-upgrader.php.
References $plugin, $plugins, $result, add_filter(), do_action(), WP_Upgrader\fs_connect(), get_plugin_data(), get_site_transient(), WP_Upgrader\init(), is_multisite(), is_plugin_active(), WP_Upgrader\maintenance_mode(), remove_filter(), WP_Upgrader\run(), upgrade_strings(), wp_clean_plugins_cache(), WP_CONTENT_DIR, and wp_parse_args().
check_package ($source)
Check a source package to be sure it contains a plugin.
This function is added to the {
See also
'upgrader_source_selection'} filter by {
Plugin_Upgrader::install()}.
Since
3.3.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $source The path to the downloaded package source.
Returns
string|WP_Error The source as passed, or a {
See also
WP_Error} object if no plugins were found.
Definition at line 1089 of file class-wp-upgrader.php.
References $file, __, get_plugin_data(), is_wp_error(), str_replace, trailingslashit(), and WP_CONTENT_DIR.
deactivate_plugin_before_upgrade ($return, $plugin)
Deactivates a plugin before it is upgraded.
Hooked to the {
See also
'upgrader_pre_install'} filter by {
Plugin_Upgrader::upgrade()}.
Since
2.8.0
4.1.0 Added a return value. public
Parameters
bool | WP_Error $return Upgrade offer return.
array $plugin Plugin package arguments.
Returns
bool|WP_Error The passed in $return param or {
See also
WP_Error}.
Definition at line 1156 of file class-wp-upgrader.php.
References $plugin, deactivate_plugins(), DOING_CRON, is_plugin_active(), and is_wp_error().
delete_old_plugin ($removed, $local_destination, $remote_destination, $plugin)
Delete the old plugin during an upgrade.
Hooked to the {
See also
'upgrader_clear_destination'} filter by {
Plugin_Upgrader::upgrade()} and {
Plugin_Upgrader::bulk_upgrade()}.
Since
2.8.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
bool | WP_Error $removed
string $local_destination
string $remote_destination
array $plugin
Returns
WP_Error|bool
Definition at line 1194 of file class-wp-upgrader.php.
References $plugin, is_wp_error(), and trailingslashit().
install ($package, $args = array())
Install a plugin package.
Since
2.8.0
3.7.0 The $args parameter was added, making clearing the plugin update cache optional. public
Parameters
string $package The full local path or URI of the package.
array $args { Optional. Other arguments for installing a plugin package. Default empty array.
bool $clear_update_cache Whether to clear the plugin updates cache if successful. Default true. }
Returns
bool|WP_Error True if the install was successful, false or a WP_Error otherwise.
Definition at line 838 of file class-wp-upgrader.php.
References $result, add_action(), add_filter(), WP_Upgrader\init(), install_strings(), is_wp_error(), remove_action(), remove_filter(), WP_Upgrader\run(), wp_clean_plugins_cache(), and wp_parse_args().
install_strings ()
Initialize the install strings.
Since
2.8.0 public
Definition at line 812 of file class-wp-upgrader.php.
References __.
Referenced by install().
plugin_info ()
Retrieve the path to the file that contains the plugin info.
This isn't used internally in the class, but is called by the skins.
Since
2.8.0 public
Returns
string|false The full path to the main plugin file, or false.
Definition at line 1128 of file class-wp-upgrader.php.
References $plugin, and get_plugins().
upgrade ($plugin, $args = array())
Upgrade a plugin.
Since
2.8.0
3.7.0 The $args parameter was added, making clearing the plugin update cache optional. public
Parameters
string $plugin The basename path to the main plugin file.
array $args { Optional. Other arguments for upgrading a plugin package. Default empty array.
bool $clear_update_cache Whether to clear the plugin updates cache if successful. Default true. }
Returns
bool|WP_Error True if the upgrade was successful, false or a {
See also
WP_Error} object otherwise.
Definition at line 891 of file class-wp-upgrader.php.
References $plugin, $result, add_filter(), get_site_transient(), WP_Upgrader\init(), is_wp_error(), remove_filter(), WP_Upgrader\run(), upgrade_strings(), wp_clean_plugins_cache(), and wp_parse_args().
upgrade_strings ()
Initialize the upgrade strings.
Since
2.8.0 public
Definition at line 794 of file class-wp-upgrader.php.
References __.
Referenced by bulk_upgrade(), and upgrade().
Field Documentation
bool $bulk = false
Whether a bulk upgrade/install is being performed.
Since
2.9.0 public
Definition at line 786 of file class-wp-upgrader.php.
array WP_Error $result
Plugin upgrade result.
Since
2.8.0 public
See also
WP_Upgrader::$result
Definition at line 777 of file class-wp-upgrader.php.
Referenced by bulk_upgrade(), install(), and upgrade().
The documentation for this class was generated from the following file:
class-wp-upgrader.php