GravityView: File_Upload_Upgrader Class Reference
File_Upload_Upgrader Class Reference
Core class used for handling file uploads.
Public Member Functions
__construct ($form, $urlholder)
Construct the upgrader for a form.
cleanup ()
Delete the attachment/uploaded file.
Data Fields
$filename
The name of the file.
$id = 0
The ID of the attachment post for this file.
$package
The full path to the file package.
Detailed Description
Core class used for handling file uploads.
This class handles the upload process and passes it as if it's a local file to the Upgrade/Installer functions.
Since
2.8.0
Definition at line 2499 of file class-wp-upgrader.php.
Constructor & Destructor Documentation
__construct ($form, $urlholder)
Construct the upgrader for a form.
Since
2.8.0 public
Parameters
string $form The name of the form the file was uploaded from.
string $urlholder The name of the GET parameter that holds the filename.
Definition at line 2537 of file class-wp-upgrader.php.
References $file, $form, __, elseif, get_post(), wp_die(), wp_handle_upload(), wp_insert_attachment(), wp_schedule_single_event(), and wp_upload_dir().
Member Function Documentation
cleanup ()
Delete the attachment/uploaded file.
Since
3.2.2 public
Returns
bool Whether the cleanup was successful.
Definition at line 2596 of file class-wp-upgrader.php.
References elseif, package, and wp_delete_attachment().
Field Documentation
string $filename
The name of the file.
Since
2.8.0 public
Definition at line 2517 of file class-wp-upgrader.php.
int $id = 0
The ID of the attachment post for this file.
Since
3.3.0 public
Definition at line 2526 of file class-wp-upgrader.php.
string $package
The full path to the file package.
Since
2.8.0 public
Definition at line 2508 of file class-wp-upgrader.php.
The documentation for this class was generated from the following file:
class-wp-upgrader.php