GravityView: WP_Customize_Nav_Menus_Panel Class Reference
WP_Customize_Nav_Menus_Panel Class Reference
Customize Nav Menus Panel Class.
Public Member Functions
render_screen_options ()
Render screen options for Menus.
wp_nav_menu_manage_columns ()
Returns the advanced options for the nav menus page.
Public Member Functions inherited from WP_Customize_Panel
__construct ($manager, $id, $args=array())
Constructor.
active ()
Check whether panel is active to current Customizer preview.
active_callback ()
Default callback used when invoking {.
check_capabilities ()
Checks required user capabilities and whether the theme has the feature support required by the panel.
get_content ()
Get the panel's content template for insertion into the Customizer pane.
json ()
Gather the parameters passed to client JavaScript via JSON.
maybe_render ()
Check capabilities and render the panel.
print_template ()
Render the panel's JS templates.
Data Fields
$type = 'nav_menus'
Data Fields inherited from WP_Customize_Panel
$active_callback = ''
$capability = 'edit_theme_options'
$description = ''
$id
$instance_number
$manager
$priority = 160
$sections
$theme_supports = ''
$title = ''
$type = 'default'
Protected Member Functions
content_template ()
An Underscore (JS) template for this panel's content (but not its container).
Protected Member Functions inherited from WP_Customize_Panel
content_template ()
An Underscore (JS) template for this panel's content (but not its container).
render ()
Render the panel container, and then its contents (via this->render_content()) in a subclass.
render_content ()
Render the panel UI in a subclass.
render_template ()
An Underscore (JS) template for rendering this panel's container.
Additional Inherited Members
Static Protected Attributes inherited from WP_Customize_Panel
static $instance_count = 0
Detailed Description
Customize Nav Menus Panel Class.
Needed to add screen options.
Since
4.3.0
See also
WP_Customize_Panel
Definition at line 19 of file class-wp-customize-nav-menus-panel.php.
Member Function Documentation
content_template () protected
An Underscore (JS) template for this panel's content (but not its container).
Class variables for this panel class are available in the data JS object; export custom variables by overriding WP_Customize_Panel::json().
Since
4.3.0 protected
See also
WP_Customize_Panel::print_template()
Definition at line 78 of file class-wp-customize-nav-menus-panel.php.
References __, _e, li, and render_screen_options().
render_screen_options ()
Render screen options for Menus.
Since
4.3.0 public
Definition at line 36 of file class-wp-customize-nav-menus-panel.php.
References $screen, add_filter(), and WP_Screen\get().
Referenced by content_template().
wp_nav_menu_manage_columns ()
Returns the advanced options for the nav menus page.
Link title attribute added as it's a relatively advanced concept for new users.
Since
4.3.0 public
Returns
array The advanced menu properties.
Definition at line 55 of file class-wp-customize-nav-menus-panel.php.
References __.
Field Documentation
$type = 'nav_menus'
Definition at line 28 of file class-wp-customize-nav-menus-panel.php.
The documentation for this class was generated from the following file:
class-wp-customize-nav-menus-panel.php