GravityView: GravityView_Admin_Add_Shortcode Class Reference
GravityView_Admin_Add_Shortcode Class Reference
If this file is called directly, abort.
Public Member Functions
__construct ()
add_scripts_and_styles ()
Enqueue scripts and styles.
add_shortcode_button ()
Add shortcode button to the Add Media right.
add_shortcode_popup ()
Add shortcode popup div.
get_sortable_fields ()
Ajax Given a View id, calculates the assigned form, and returns the form fields (only the sortable ones)
is_post_editor_screen ()
check if screen post editor and is not related with post type 'gravityview'
Detailed Description
If this file is called directly, abort.
Definition at line 19 of file class-admin-add-shortcode.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 21 of file class-admin-add-shortcode.php.
Member Function Documentation
add_scripts_and_styles()
add_scripts_and_styles ()
Enqueue scripts and styles.
Returns
void
Definition at line 153 of file class-admin-add-shortcode.php.
References GRAVITYVIEW_FILE, is_post_editor_screen(), and GravityView_Plugin\version.
add_shortcode_button()
add_shortcode_button ()
Add shortcode button to the Add Media right.
Returns
void
Since
1.15.3
Definition at line 51 of file class-admin-add-shortcode.php.
References GVCommon\has_cap(), and is_post_editor_screen().
add_shortcode_popup()
add_shortcode_popup ()
Add shortcode popup div.
Returns
void
Definition at line 76 of file class-admin-add-shortcode.php.
References $post, $settings, $title, View_Settings\defaults(), is_post_editor_screen(), GravityView_Admin\no_views_text(), and GravityView_Render_Settings\render_setting_row().
get_sortable_fields()
get_sortable_fields ()
Ajax Given a View id, calculates the assigned form, and returns the form fields (only the sortable ones)
Returns
void
Definition at line 193 of file class-admin-add-shortcode.php.
References gravityview_get_form_id(), gravityview_get_sortable_fields(), and gravityview_get_template_setting().
is_post_editor_screen()
is_post_editor_screen ()
check if screen post editor and is not related with post type 'gravityview'
Returns
bool
Definition at line 40 of file class-admin-add-shortcode.php.
Referenced by add_scripts_and_styles(), add_shortcode_button(), and add_shortcode_popup().
The documentation for this class was generated from the following file:
class-admin-add-shortcode.php