GravityView: GF_UnitTest_Generator Class Reference
GF_UnitTest_Generator Class Reference
Public Member Functions
__toString ()
next ()
Static Public Member Functions
static get ()
static get_instance ()
Static Private Attributes
static $instances = array()
Detailed Description
Definition at line 228 of file factory.php.
Member Function Documentation
__toString ()
Definition at line 251 of file factory.php.
References next().
static get () static
PhpUndefinedMethodInspection
Definition at line 244 of file factory.php.
Referenced by GF_UnitTest_Factory_For_Entry\__construct().
static get_instance () static
Definition at line 232 of file factory.php.
next () abstract
Referenced by __toString().
Field Documentation
$instances = array() static private
Definition at line 230 of file factory.php.
The documentation for this class was generated from the following file:
factory.php