GravityView: Framework Class Reference
Framework Class Reference
Logging framework for GravityKit.
Public Member Functions
__call ($name, array $arguments=[])
Magic method to access Monolog's logger class methods.
get_log_file ()
Returns log file name with path.
get_logger_handler ()
Returns handler that will process log messages.
get_settings ($gk_settings)
Returns UI settings for the logger.
save_settings ($new_settings)
Deletes log files when UI savings are saved and the logger type is no longer "file".
Static Public Member Functions
static get_instance ($logger_id='', $logger_title='')
Returns class instance.
Data Fields
const DEFAULT_LOGGER_ID = 'gravitykit'
const DEFAULT_LOGGER_TITLE = 'GravityKit'
Private Member Functions
__construct ($logger_id, $logger_title)
Class constructor.
Private Attributes
$_log_path = 'logs'
$_logger
$_logger_id
$_logger_title
$_settings
Static Private Attributes
static $_instances = []
Detailed Description
Logging framework for GravityKit.
Definition at line 24 of file Logger/Framework.php.
Constructor & Destructor Documentation
__construct()
__construct ($logger_id, $logger_title) private
Class constructor.
Since
1.0.0
Parameters
string $logger_id Unique name that's prefixed to each log entry.
string $logger_title Logger title (used in the admin UI).
Returns
void
Runs Filter:
gk/foundation/logger/log-path Changes path where logs are stored.
Since
1.0.0
Parameters
string $log_path Location where logs are stored relative to WP_CONTENT_DIR. Default: WP_CONTENT_DIR . '/logs'.
Definition at line 85 of file Logger/Framework.php.
References Framework\get_logger_handler().
Member Function Documentation
__call()
__call ($name, array $arguments = [])
Magic method to access Monolog's logger class methods.
Since
1.0.0
Parameters
string $name Package/class name.
array $arguments Optional and not used.
Returns
mixed|void
Runs Filter:
gk/foundation/logger/allow-heartbeat-requests Allows logging of WP heartbeat requests.
Since
1.0.0
Parameters
bool $log_heartbeat Default: false.
Definition at line 487 of file Logger/Framework.php.
References $name.
get_instance()
static get_instance ($logger_id = '', $logger_title = '') static
Returns class instance.
Since
1.0.0
Parameters
string $logger_id (optional) Unique logger identifier that's prefixed to each log entry or used with some handlers.. Default: gravitykit.
string $logger_title (optional) Logger title (used in the admin UI). Default: GravityKit.
Returns
Framework
Definition at line 128 of file Logger/Framework.php.
get_log_file()
get_log_file ()
Returns log file name with path.
Returns
string
Definition at line 471 of file Logger/Framework.php.
References Encryption\get_instance().
Referenced by Framework\get_logger_handler(), Framework\get_settings(), and Framework\save_settings().
get_logger_handler()
get_logger_handler ()
Returns handler that will process log messages.
Since
1.0.0
Returns
void|ChromePHPHandler|GravityFormsHandler|StreamHandler|QueryMonitorHandler
Definition at line 146 of file Logger/Framework.php.
References $settings, and Framework\get_log_file().
Referenced by Framework\__construct().
get_settings()
get_settings ($gk_settings)
Returns UI settings for the logger.
Since
1.0.0
1.0.3 Added $gk_settings parameter.
Parameters
array $gk_settings GravityKit general settings object.
Returns
array[]
Definition at line 183 of file Logger/Framework.php.
References Arr\get(), Framework\get_log_file(), and Arr\set().
save_settings()
save_settings ($new_settings)
Deletes log files when UI savings are saved and the logger type is no longer "file".
Since
1.0.0
Returns
void
Definition at line 448 of file Logger/Framework.php.
References $current_settings, and Framework\get_log_file().
Field Documentation
$_instances
$_instances = [] static private
Definition at line 34 of file Logger/Framework.php.
$_log_path
$_log_path = 'logs' private
Definition at line 73 of file Logger/Framework.php.
$_logger
$_logger private
Definition at line 52 of file Logger/Framework.php.
$_logger_id
$_logger_id private
Definition at line 59 of file Logger/Framework.php.
$_logger_title
$_logger_title private
Definition at line 66 of file Logger/Framework.php.
$_settings
$_settings private
Definition at line 43 of file Logger/Framework.php.
DEFAULT_LOGGER_ID
const DEFAULT_LOGGER_ID = 'gravitykit'
Definition at line 25 of file Logger/Framework.php.
DEFAULT_LOGGER_TITLE
const DEFAULT_LOGGER_TITLE = 'GravityKit'
Definition at line 27 of file Logger/Framework.php.
The documentation for this class was generated from the following file:
Logger/Framework.php