GravityView: GravityView_Change_Entry_Creator Class Reference
GravityView_Change_Entry_Creator Class Reference
Public Member Functions
__construct ()
add_select ($form_id, $entry)
Output select element used to change the entry creator.
assign_new_user_to_lead ($user_id, $config, $entry=array(), $password='')
When an user is created using the User Registration add-on, assign the entry to them.
enqueue_selectwoo_assets ()
Enqueue selectWoo script and style.
entry_creator_get_users ()
Get users list for entry creator.
load ()
prevent_conflicts ()
Disable previous functionality; use this one as the canonical.
register_gform_noconflict ($assets)
Allow UI assets.
set_screen_mode ()
Allows for edit links to work with a link instead of a form (GET instead of POST)
update_entry_creator ($form, $entry_id)
When the entry creator is changed, add a note to the entry.
Data Fields
const DEFAULT_NUMBER_OF_USERS = 100
Detailed Description
Since
1.2
Definition at line 6 of file class-gravityview-change-entry-creator.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Since
1.5.1
Runs Filter:
gravityview_disable_change_entry_creator Disable the Change Entry Creator functionality
Since
1.7.4
Parameters
boolean $disable Disable the Change Entry Creator functionality. Default: false.
Use init to fix bbPress warning
See also
https://bbpress.trac.wordpress.org/ticket/2309
Definition at line 13 of file class-gravityview-change-entry-creator.php.
Member Function Documentation
add_select()
add_select ($form_id, $entry)
Output select element used to change the entry creator.
Parameters
int $form_id GF Form ID
array $entry GF entry array
Returns
void
Definition at line 311 of file class-gravityview-change-entry-creator.php.
References $entry, $output, $user, Utils\get(), and GVCommon\get_users().
assign_new_user_to_lead()
assign_new_user_to_lead ($user_id, $config, $entry = array(), $password = '')
When an user is created using the User Registration add-on, assign the entry to them.
Since
1.5.1
Parameters
int $user_id WordPress User ID
array $config User registration feed configuration
array $entry GF Entry array
string $password User password
Returns
void RGFormsModel::update_lead_property() Modify the entry created_by field
Disable assigning the new user to the entry by returning false.
Parameters
int $user_id WordPress User ID
array $config User registration feed configuration
array $entry GF Entry array
Runs Filter:
gravityview_disable_change_entry_creator_note Disable adding a note when changing the entry creator
Since
1.21.5
Parameters
boolean $disable Disable the Change Entry Creator note. Default: false.
Definition at line 144 of file class-gravityview-change-entry-creator.php.
References $entry, GravityView_Entry_Notes\add_note(), and gravityview().
enqueue_selectwoo_assets()
enqueue_selectwoo_assets ()
Enqueue selectWoo script and style.
Since
2.9.1
Definition at line 57 of file class-gravityview-change-entry-creator.php.
References Plugin\$version, gravityview(), and GRAVITYVIEW_FILE.
entry_creator_get_users()
entry_creator_get_users ()
Get users list for entry creator.
Since
2.9.1
Definition at line 100 of file class-gravityview-change-entry-creator.php.
References GVCommon\get_users().
load()
load ()
Since
3.6.3
Returns
void
Definition at line 205 of file class-gravityview-change-entry-creator.php.
References GVCommon\has_cap().
prevent_conflicts()
prevent_conflicts ()
Disable previous functionality; use this one as the canonical.
Returns
void
Definition at line 192 of file class-gravityview-change-entry-creator.php.
register_gform_noconflict()
register_gform_noconflict ($assets)
Allow UI assets.
Parameters
array $assets
Returns
array
Definition at line 368 of file class-gravityview-change-entry-creator.php.
set_screen_mode()
set_screen_mode ()
Allows for edit links to work with a link instead of a form (GET instead of POST)
Returns
void
Definition at line 236 of file class-gravityview-change-entry-creator.php.
update_entry_creator()
update_entry_creator ($form, $entry_id)
When the entry creator is changed, add a note to the entry.
Parameters
array $form GF entry array
int $entry_id Entry ID
Returns
void
Definition at line 256 of file class-gravityview-change-entry-creator.php.
References $created_by, Utils\_POST(), and GravityView_Entry_Notes\add_note().
Field Documentation
DEFAULT_NUMBER_OF_USERS
const DEFAULT_NUMBER_OF_USERS = 100
Definition at line 11 of file class-gravityview-change-entry-creator.php.
The documentation for this class was generated from the following file:
class-gravityview-change-entry-creator.php