GravityView: GravityView_Field_Is_Approved Class Reference
GravityView_Field_Is_Approved Class Reference
Public Member Functions
__construct ()
add_default_field ($entry_default_fields, $form, $zone)
field_options ($field_options, $template_id, $field_id, $context, $input_type)
filter_field_value ($output= '', $entry=array(), $field_settings=array(), $gv_field_output=array())
Convert entry approval status value to label in the field output.
Public Member Functions inherited from GravityView_Field
__construct ()
GravityView_Field constructor.
_filter_gform_custom_merge_tags ($custom_merge_tags=array(), $form_id, $fields=array(), $element_id= '')
Add custom merge tags to merge tag options.
_filter_gform_replace_merge_tags ($text, $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Match the merge tag in replacement text for the field.
_filter_sortable_fields ($not_sortable)
Use field settings to modify whether a field is sortable.
add_entry_meta ($entry_meta)
Add the custom entry meta key to make it searchable and sortable.
add_field_support ($key= '', &$field_options)
add_sortable_field ($fields)
Add the field to the Filter & Sort available fields.
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Tap in here to modify field options.
replace_merge_tag ($matches=array(), $text= '', $form=array(), $entry=array(), $url_encode=false, $esc_html=false)
Run GravityView filters when using GFCommon::replace_variables()
set_default_search_label ($label= '', $gf_field=null, $field=array())
Allow setting a default search label for search fields based on the field type.
Data Fields
$_custom_merge_tag = 'approval_status'
$contexts = array('single', 'multiple')
$entry_meta_is_default_column = false
$entry_meta_key = 'is_approved'
$group = 'meta'
$is_numeric = true
$is_searchable = true
$is_sortable = true
$name = 'is_approved'
$search_operators = array('is', 'isnot')
Data Fields inherited from GravityView_Field
$_gf_field_class_name
$contexts = array('single', 'multiple', 'edit', 'export')
$default_search_label
$description
$entry_meta_is_default_column = false
$entry_meta_key = null
$entry_meta_update_callback = null
$group
standard, advanced, post, pricing, meta, gravityview
$is_numeric
boolean Is field content number-based?
$is_searchable = true
$is_sortable = true
boolean Can the field be sorted in search?
$label
$name
$search_operators
Protected Member Functions
custom_merge_tags ($form=array(), $fields=array())
Add custom merge tags to merge tag options.
Protected Member Functions inherited from GravityView_Field
custom_merge_tags ($form=array(), $fields=array())
Add custom Merge Tags to Merge Tag options, if custom Merge Tags exist.
is_choice_value_enabled ()
Check whether the enableChoiceValue flag is set for a GF field.
Private Member Functions
add_hooks ()
Additional Inherited Members
Protected Attributes inherited from GravityView_Field
$_custom_merge_tag = false
$_field_id = ''
$_field_options = array()
Detailed Description
Definition at line 8 of file class-gravityview-field-is-approved.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 38 of file class-gravityview-field-is-approved.php.
References add_hooks(), and description.
Member Function Documentation
add_default_field ($entry_default_fields, $form, $zone)
Runs Filter:
gravityview_entry_default_fields
Parameters
array $entry_default_fields Array of fields shown by default
string | array $form form_ID or form object
string $zone Either 'single', 'directory', 'header', 'footer'
Returns
array
Definition at line 93 of file class-gravityview-field-is-approved.php.
References $name, and description.
add_hooks () private
Definition at line 49 of file class-gravityview-field-is-approved.php.
Referenced by __construct().
custom_merge_tags ($form = array(), $fields = array()) protected
Add custom merge tags to merge tag options.
Since
1.16
Parameters
array $form GF Form array
GF_Field[] $fields Array of fields in the form
Returns
array Modified merge tags
Definition at line 116 of file class-gravityview-field-is-approved.php.
References $entry, $form, GravityView_Entry_Approval\get_entry_status(), and GravityView_Field\replace_merge_tag().
field_options ($field_options, $template_id, $field_id, $context, $input_type)
Definition at line 169 of file class-gravityview-field-is-approved.php.
References GravityView_Entry_Approval_Status\get_label().
filter_field_value ($output = '', $entry = array(), $field_settings = array(), $gv_field_output = array())
Convert entry approval status value to label in the field output.
Uses labels from the field setting.
Since
1.18
Parameters
string $output HTML value output
array $entry The GF entry array
array $field_settings Settings for the particular GV field
array $field Field array, as fetched from GravityView_View::getCurrentField()
Returns
string The field setting label for the current status. Uses defaults, if not configured.
Definition at line 67 of file class-gravityview-field-is-approved.php.
References $field_settings, $output, $value, GravityView_Entry_Approval_Status\get_key(), GravityView_Entry_Approval_Status\get_label(), and GravityView_Entry_Approval_Status\maybe_convert_status().
Field Documentation
$_custom_merge_tag = 'approval_status'
Definition at line 36 of file class-gravityview-field-is-approved.php.
$contexts = array('single', 'multiple')
Definition at line 14 of file class-gravityview-field-is-approved.php.
$entry_meta_is_default_column = false
Definition at line 34 of file class-gravityview-field-is-approved.php.
$entry_meta_key = 'is_approved'
Definition at line 28 of file class-gravityview-field-is-approved.php.
$group = 'meta'
Definition at line 16 of file class-gravityview-field-is-approved.php.
$is_numeric = true
Definition at line 20 of file class-gravityview-field-is-approved.php.
$is_searchable = true
Definition at line 22 of file class-gravityview-field-is-approved.php.
$is_sortable = true
Definition at line 18 of file class-gravityview-field-is-approved.php.
$name = 'is_approved'
Definition at line 10 of file class-gravityview-field-is-approved.php.
Referenced by add_default_field().
$search_operators = array('is', 'isnot')
Definition at line 12 of file class-gravityview-field-is-approved.php.
The documentation for this class was generated from the following file:
class-gravityview-field-is-approved.php