GravityView: WP_Date_Query Class Reference
WP_Date_Query Class Reference
Class for generating SQL clauses that filter a primary query according to date.
Public Member Functions
__construct ($date_query, $default_column= 'post_date')
Constructor.
build_mysql_datetime ($datetime, $default_to_max=false)
Builds a MySQL format date/time based on some query parameters.
build_time_query ($column, $compare, $hour=null, $minute=null, $second=null)
Builds a query string for comparing time values (hour, minute, second).
build_value ($compare, $value)
Builds and validates a value string based on the comparison operator.
get_compare ($query)
Determines and validates what comparison operator to use.
get_sql ()
Generate WHERE clause to be appended to a main query.
sanitize_query ($queries, $parent_query=null)
Recursive-friendly query sanitizer.
validate_column ($column)
Validates a column name parameter.
validate_date_values ($date_query=array())
Validates the given date_query values and triggers errors if something is not valid.
Data Fields
$column = 'post_date'
$compare = '='
$queries = array()
$relation = 'AND'
$time_keys = array('after', 'before', 'year', 'month', 'monthnum', 'week', 'w', 'dayofyear', 'day', 'dayofweek', 'dayofweek_iso', 'hour', 'minute', 'second')
Protected Member Functions
get_sql_clauses ()
Generate SQL clauses to be appended to a main query.
get_sql_for_clause ($query, $parent_query)
Turns a first-order date query into SQL for a WHERE clause.
get_sql_for_query ($query, $depth=0)
Generate SQL clauses for a single query array.
get_sql_for_subquery ($query)
Turns a single date clause into pieces for a WHERE clause.
is_first_order_clause ($query)
Determine whether this is a first-order clause.
Detailed Description
Class for generating SQL clauses that filter a primary query according to date.
WP_Date_Query is a helper that allows primary query classes, such as {
See also
WP_Query}, to filter their results by date columns, by generating WHERE subclauses to be attached to the primary SQL query string.
Attempting to filter by an invalid date value (eg month=13) will generate SQL that will return no results. In these cases, a _doing_it_wrong() error notice is also thrown. See WP_Date_Query::validate_date_values().
Codex page. 3.7.0
Definition at line 17 of file tmp/wordpress/wp-includes/date.php.
Constructor & Destructor Documentation
__construct ($date_query, $default_column = 'post_date')
Constructor.
Time-related parameters that normally require integer values ('year', 'month', 'week', 'dayofyear', 'day', 'dayofweek', 'dayofweek_iso', 'hour', 'minute', 'second') accept arrays of integers for some values of 'compare'. When 'compare' is 'IN' or 'NOT IN', arrays are accepted; when 'compare' is 'BETWEEN' or 'NOT BETWEEN', arrays of two valid values are required. See individual argument descriptions for accepted values.
Since
3.7.0
4.0.0 The $inclusive logic was updated to include all times within the date range.
4.1.0 Introduced 'dayofweek_iso' time type parameter. public
Parameters
array $date_query { Array of date query clauses.
array { string $column Optional. The column to query against. If undefined, inherits the value of the $default_column parameter. Accepts 'post_date', 'post_date_gmt', 'post_modified','post_modified_gmt', 'comment_date', 'comment_date_gmt'. Default 'post_date'. string $compare Optional. The comparison operator. Accepts '=', '!=', '>', '>=', '<', '<=', 'IN', 'NOT IN', 'BETWEEN', 'NOT BETWEEN'. Default '='. string $relation Optional. The boolean relationship between the date queries. Accepts 'OR' or 'AND'. Default 'OR'. array { Optional. An array of first-order clause parameters, or another fully-formed date query.
string|array $before { Optional. Date to retrieve posts before. Accepts strtotime()-compatible string, or array of 'year', 'month', 'day' values.
string $year The four-digit year. Default empty. Accepts any four-digit year. string $month Optional when passing array.The month of the year. Default (string:empty)|(array:1). Accepts numbers 1-12. string $day Optional when passing array.The day of the month. Default (string:empty)|(array:1). Accepts numbers 1-31. } string|array $after { Optional. Date to retrieve posts after. Accepts strtotime()-compatible string, or array of 'year', 'month', 'day' values.
string $year The four-digit year. Accepts any four-digit year. Default empty. string $month Optional when passing array. The month of the year. Accepts numbers 1-12. Default (string:empty)|(array:12). string $day Optional when passing array.The day of the month. Accepts numbers 1-31. Default (string:empty)|(array:last day of month). } string $column Optional. Used to add a clause comparing a column other than the column specified in the top-level $column parameter. Accepts 'post_date', 'post_date_gmt', 'post_modified', 'post_modified_gmt', 'comment_date', 'comment_date_gmt'. Default is the value of top-level $column. string $compare Optional. The comparison operator. Accepts '=', '!=', '>', '>=', '<', '<=', 'IN', 'NOT IN', 'BETWEEN', 'NOT BETWEEN'. 'IN', 'NOT IN', 'BETWEEN', and 'NOT BETWEEN'. Comparisons support arrays in some time-related parameters. Default '='. bool $inclusive Optional. Include results from dates specified in 'before' or 'after'. Default false. int|array $year Optional. The four-digit year number. Accepts any four-digit year or an array of years if $compare supports it. Default empty. int|array $month Optional. The two-digit month number. Accepts numbers 1-12 or an array of valid numbers if $compare supports it. Default empty. int|array $week Optional. The week number of the year. Accepts numbers 0-53 or an array of valid numbers if $compare supports it. Default empty. int|array $dayofyear Optional. The day number of the year. Accepts numbers 1-366 or an array of valid numbers if $compare supports it. int|array $day Optional. The day of the month. Accepts numbers 1-31 or an array of valid numbers if $compare supports it. Default empty. int|array $dayofweek Optional. The day number of the week. Accepts numbers 1-7 (1 is Sunday) or an array of valid numbers if $compare supports it. Default empty. int|array $dayofweek_iso Optional. The day number of the week (ISO). Accepts numbers 1-7 (1 is Monday) or an array of valid numbers if $compare supports it. Default empty. int|array $hour Optional. The hour of the day. Accepts numbers 0-23 or an array of valid numbers if $compare supports it. Default empty. int|array $minute Optional. The minute of the hour. Accepts numbers 0-60 or an array of valid numbers if $compare supports it. Default empty. int|array $second Optional. The second of the minute. Accepts numbers 0-60 or an array of valid numbers if $compare supports it. Default empty. } } }
Parameters
array $default_column Optional. Default column to query against. Default 'post_date'. Accepts 'post_date', 'post_date_gmt', 'post_modified', 'post_modified_gmt', 'comment_date', 'comment_date_gmt'.
Definition at line 153 of file tmp/wordpress/wp-includes/date.php.
References column, esc_sql(), get_compare(), sanitize_query(), and validate_column().
Member Function Documentation
build_mysql_datetime ($datetime, $default_to_max = false)
Builds a MySQL format date/time based on some query parameters.
You can pass an array of values (year, month, etc.) with missing parameter values being defaulted to either the maximum or minimum values (controlled by the $default_to parameter). Alternatively you can pass a string that will be run through strtotime().
Since
3.7.0 public
Parameters
string | array $datetime An array of parameters or a strotime() string
bool $default_to_max Whether to round up incomplete dates. Supported by values of $datetime that are arrays, or string values that are a subset of MySQL date format ('Y', 'Y-m', 'Y-m-d', 'Y-m-d H:i'). Default: false.
Returns
string|false A MySQL format date/time or false on failure
Definition at line 868 of file tmp/wordpress/wp-includes/date.php.
References $now, current_time(), date, and elseif.
Referenced by get_sql_for_clause().
build_time_query ($column, $compare, $hour = null, $minute = null, $second = null)
Builds a query string for comparing time values (hour, minute, second).
If just hour, minute, or second is set than a normal comparison will be done. However if multiple values are passed, a pseudo-decimal time will be created in order to be able to accurately compare against.
Since
3.7.0 public
Parameters
string $column The column to query against. Needs to be pre-validated!
string $compare The comparison operator. Needs to be pre-validated!
int | null $hour Optional. An hour value (0-23).
int | null $minute Optional. A minute value (0-59).
int | null $second Optional. A second value (0-59).
Returns
string|false A query part or false on failure.
Definition at line 956 of file tmp/wordpress/wp-includes/date.php.
References $compare, $format, $value, $wpdb, build_value(), elseif, and null.
Referenced by get_sql_for_clause().
build_value ($compare, $value)
Builds and validates a value string based on the comparison operator.
Since
3.7.0 public
Parameters
string $compare The compare operator to use
string | array $value The value
Returns
string|false|int The value to be used in SQL or false on error.
Definition at line 805 of file tmp/wordpress/wp-includes/date.php.
References $compare, and $value.
Referenced by build_time_query(), and get_sql_for_clause().
get_compare ($query)
Determines and validates what comparison operator to use.
Since
3.7.0 public
Parameters
array $query A date query or a date subquery.
Returns
string The comparison operator.
Definition at line 272 of file tmp/wordpress/wp-includes/date.php.
References $compare.
Referenced by __construct(), and get_sql_for_clause().
get_sql ()
Generate WHERE clause to be appended to a main query.
Since
3.7.0 public
Returns
string MySQL WHERE clause.
Filter the date query WHERE clause.
Since
3.7.0
Parameters
string $where WHERE clause of the date query.
WP_Date_Query $this The WP_Date_Query instance.
Definition at line 552 of file tmp/wordpress/wp-includes/date.php.
References apply_filters(), and get_sql_clauses().
get_sql_clauses () protected
Generate SQL clauses to be appended to a main query.
Called by the public {
See also
WP_Date_Query::get_sql()}, this method is abstracted out to maintain parity with the other Query classes.
Since
4.1.0 protected
Returns
array { Array containing JOIN and WHERE SQL clauses to append to the main query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 584 of file tmp/wordpress/wp-includes/date.php.
References get_sql_for_query().
Referenced by get_sql().
get_sql_for_clause ($query, $parent_query) protected
Turns a first-order date query into SQL for a WHERE clause.
Since
4.1.0 protected
Parameters
array $query Date query clause.
array $parent_query Parent query of the current date query.
Returns
array { Array containing JOIN and WHERE SQL clauses to append to the main query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 715 of file tmp/wordpress/wp-includes/date.php.
References $column, $compare, $value, $wpdb, _wp_mysql_week(), build_mysql_datetime(), build_time_query(), build_value(), elseif, esc_sql(), get_compare(), null, and validate_column().
Referenced by get_sql_for_query(), and get_sql_for_subquery().
get_sql_for_query ($query, $depth = 0) protected
Generate SQL clauses for a single query array.
If nested subqueries are found, this method recurses the tree to produce the properly nested SQL.
Since
4.1.0 protected
Parameters
array $query Query to parse.
int $depth Optional. Number of tree levels deep we currently are. Used to calculate indentation. Default 0.
Returns
array { Array containing JOIN and WHERE SQL clauses to append to a single query array.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 613 of file tmp/wordpress/wp-includes/date.php.
References $i, $relation, elseif, get_sql_for_clause(), and is_first_order_clause().
Referenced by get_sql_clauses().
get_sql_for_subquery ($query) protected
Turns a single date clause into pieces for a WHERE clause.
A wrapper for get_sql_for_clause(), included here for backward compatibility while retaining the naming convention across Query classes.
Since
3.7.0 protected
Parameters
array $query Date query arguments.
Returns
array { Array containing JOIN and WHERE SQL clauses to append to the main query.
string $join SQL fragment to append to the main JOIN clause. string $where SQL fragment to append to the main WHERE clause. }
Definition at line 696 of file tmp/wordpress/wp-includes/date.php.
References get_sql_for_clause().
is_first_order_clause ($query) protected
Determine whether this is a first-order clause.
Checks to see if the current clause has any time-related keys. If so, it's first-order.
Parameters
array $query Query clause.
Returns
bool True if this is a first-order clause.
Definition at line 258 of file tmp/wordpress/wp-includes/date.php.
References $time_keys.
Referenced by get_sql_for_query(), and sanitize_query().
sanitize_query ($queries, $parent_query = null)
Recursive-friendly query sanitizer.
Ensures that each query-level clause has a 'relation' key, and that each first-order clause contains all the necessary keys from $defaults.
Since
4.1.0 public
Parameters
array $queries
array $parent_query
Returns
array Sanitized queries.
Definition at line 202 of file tmp/wordpress/wp-includes/date.php.
References $queries, is_first_order_clause(), and validate_date_values().
Referenced by __construct().
validate_column ($column)
Validates a column name parameter.
Column names without a table prefix (like 'post_date') are checked against a whitelist of known tables, and then, if found, have a table prefix (such as 'wp_posts.') prepended. Prefixed column names (such as 'wp_posts.post_date') bypass this whitelist check, and are only sanitized to remove illegal characters.
Since
3.7.0 public
Parameters
string $column The user-supplied column name.
Returns
string A validated column name value.
Filter the list of valid date query columns.
Since
3.7.0
4.1.0 Added 'user_registered' to the default recognized columns.
Parameters
array $valid_columns An array of valid date query columns. Defaults are 'post_date', 'post_date_gmt', 'post_modified', 'post_modified_gmt', 'comment_date', 'comment_date_gmt', 'user_registered'
Definition at line 488 of file tmp/wordpress/wp-includes/date.php.
References $column, $wpdb, and apply_filters().
Referenced by __construct(), and get_sql_for_clause().
validate_date_values ($date_query = array())
Validates the given date_query values and triggers errors if something is not valid.
Note that date queries with invalid date ranges are allowed to continue (though of course no items will be found for impossible dates). This method only generates debug notices for these cases.
Since
4.1.0 public
Parameters
array $date_query The date_query array.
Returns
bool True if all values in the query are valid, false if one or more fail.
Definition at line 292 of file tmp/wordpress/wp-includes/date.php.
References __, _doing_it_wrong(), date, elseif, esc_html, and wp_checkdate().
Referenced by sanitize_query().
Field Documentation
$column = 'post_date'
Definition at line 45 of file tmp/wordpress/wp-includes/date.php.
Referenced by get_sql_for_clause(), and validate_column().
$compare = '='
Definition at line 54 of file tmp/wordpress/wp-includes/date.php.
Referenced by build_time_query(), build_value(), get_compare(), and get_sql_for_clause().
$queries = array()
Definition at line 27 of file tmp/wordpress/wp-includes/date.php.
Referenced by sanitize_query().
$relation = 'AND'
Definition at line 36 of file tmp/wordpress/wp-includes/date.php.
Referenced by get_sql_for_query().
$time_keys = array('after', 'before', 'year', 'month', 'monthnum', 'week', 'w', 'dayofyear', 'day', 'dayofweek', 'dayofweek_iso', 'hour', 'minute', 'second')
Definition at line 63 of file tmp/wordpress/wp-includes/date.php.
Referenced by is_first_order_clause().
The documentation for this class was generated from the following file:
tmp/wordpress/wp-includes/date.php