GravityView: gvlogic Class Reference
gvlogic Class Reference
If this file is called directly, abort.
Public Member Functions
callback ($atts, $content='', $tag='')
Process and output the [gvfield] shortcode.
Public Member Functions inherited from Shortcode
callback ($atts, $content='', $tag='')
The WordPress Shortcode API callback for this shortcode.
Static Public Member Functions
static add ($name=null)
Static Public Member Functions inherited from Shortcode
static add ($name=null)
Register this shortcode class with the WordPress Shortcode API.
static parse ($content)
Parse a string of content and figure out which ones there are.
static remove ()
Unregister this shortcode.
Data Fields
$name = 'gvlogic'
Data Fields inherited from Shortcode
$atts
$content
$name
Private Member Functions
authorized ($atts)
Are we authorized to follow the if path?
get_operator ($atts)
Fetch the operator.
get_operators ($with_values=false)
Get array of supported operators.
get_output ($match, $atts, $content)
Get the ouput content.
get_value ($atts)
Fetch the value.
parse_atts ($atts, $content, $tag)
Process the attributes passed to the shortcode.
Detailed Description
If this file is called directly, abort.
The [gvlogic] shortcode.
Definition at line 12 of file class-gv-shortcode-gvlogic.php.
Member Function Documentation
add()
static add ($name = null) static
...some aliases.
Definition at line 21 of file class-gv-shortcode-gvlogic.php.
authorized()
authorized ($atts) private
Are we authorized to follow the if path?
Parameters
array $atts The attributes.
Returns
bool Yes, or no.
Definition at line 83 of file class-gv-shortcode-gvlogic.php.
References Shortcode\$atts, and Utils\get().
Referenced by gvlogic\callback().
callback()
callback ($atts, $content = '', $tag = '')
Process and output the [gvfield] shortcode.
Parameters
array $atts The attributes passed.
string $content The content inside the shortcode.
string $tag The tag.
Returns
string The output.
Definition at line 40 of file class-gv-shortcode-gvlogic.php.
References Shortcode\$atts, Shortcode\$content, $output, $value, gvlogic\authorized(), Utils\get(), gvlogic\get_operator(), gvlogic\get_output(), gvlogic\get_value(), gravityview(), GVCommon\matches_operation(), and gvlogic\parse_atts().
get_operator()
get_operator ($atts) private
Fetch the operator.
Parameters
array $atts The attributes.
Returns
bool|string The operator.
Definition at line 97 of file class-gv-shortcode-gvlogic.php.
References Shortcode\$atts, $value, and gvlogic\get_operators().
Referenced by gvlogic\callback().
get_operators()
get_operators ($with_values = false) private
Get array of supported operators.
Parameters
bool $with_values
Returns
array
Definition at line 230 of file class-gv-shortcode-gvlogic.php.
Referenced by gvlogic\get_operator(), gvlogic\get_value(), and gvlogic\parse_atts().
get_output()
get_output ($match, $atts, $content) private
Get the ouput content.
Parameters
bool $match if or else?
array $atts The attributes.
string $content The content.
Returns
string The output.
Definition at line 145 of file class-gv-shortcode-gvlogic.php.
References Shortcode\$atts, Shortcode\$content, and gravityview().
Referenced by gvlogic\callback().
get_value()
get_value ($atts) private
Fetch the value.
Parameters
array $atts The attributes.
Returns
null|string The value.
Definition at line 120 of file class-gv-shortcode-gvlogic.php.
References Shortcode\$atts, $value, and gvlogic\get_operators().
Referenced by gvlogic\callback().
parse_atts()
parse_atts ($atts, $content, $tag) private
Process the attributes passed to the shortcode.
Make sure they're valid
Returns
void
Runs Filter:
gravityview/gvlogic/atts The logic attributes.
Since
develop
Parameters
[in,out] array $atts The logic attributes.
Definition at line 253 of file class-gv-shortcode-gvlogic.php.
References Shortcode\$atts, and gvlogic\get_operators().
Referenced by gvlogic\callback().
Field Documentation
$name
$name = 'gvlogic'
Definition at line 16 of file class-gv-shortcode-gvlogic.php.
The documentation for this class was generated from the following file:
class-gv-shortcode-gvlogic.php