GravityView: GF_Installation_Wizard_Step Class Reference
GF_Installation_Wizard_Step Class Reference
Public Member Functions
__construct ($values=array())
& __get ($key)
__isset ($key)
__set ($key, $value)
__unset ($key)
display ()
flush_values ()
get_field_validation_result ($key)
get_name ()
get_next_button_text ()
get_posted_values ()
get_previous_button_text ()
get_title ()
get_validation_summary ()
get_values ()
install ()
is ($key)
is_complete ()
set_field_validation_result ($key, $text)
set_validation_summary ($text)
summary ($echo=true)
update ($posted_values=array())
validate ()
validation_message ($key, $echo=true)
Data Fields
$defaults = array()
Protected Attributes
$_field_validation_results = array()
$_name = ''
$_validation_summary = ''
Private Attributes
$_step_values
Detailed Description
Definition at line 3 of file class-gf-installation-wizard-step.php.
Constructor & Destructor Documentation
__construct ($values = array())
Definition at line 13 of file class-gf-installation-wizard-step.php.
Member Function Documentation
& __get ($key)
Definition at line 44 of file class-gf-installation-wizard-step.php.
__isset ($key)
Definition at line 36 of file class-gf-installation-wizard-step.php.
__set ($key, $value)
Definition at line 32 of file class-gf-installation-wizard-step.php.
References $value.
__unset ($key)
Definition at line 40 of file class-gf-installation-wizard-step.php.
display ()
Definition at line 57 of file class-gf-installation-wizard-step.php.
flush_values ()
Definition at line 127 of file class-gf-installation-wizard-step.php.
References delete_option(), and get_name().
get_field_validation_result ($key)
Definition at line 65 of file class-gf-installation-wizard-step.php.
Referenced by validation_message().
get_name ()
Definition at line 20 of file class-gf-installation-wizard-step.php.
References $_name.
Referenced by flush_values(), is(), and update().
get_next_button_text ()
Definition at line 101 of file class-gf-installation-wizard-step.php.
References __.
get_posted_values ()
Definition at line 131 of file class-gf-installation-wizard-step.php.
References $value, and stripslashes_deep().
get_previous_button_text ()
Definition at line 105 of file class-gf-installation-wizard-step.php.
References __.
get_title ()
Definition at line 28 of file class-gf-installation-wizard-step.php.
get_validation_summary ()
Definition at line 80 of file class-gf-installation-wizard-step.php.
References $_validation_summary.
get_values ()
Definition at line 51 of file class-gf-installation-wizard-step.php.
Referenced by update().
install ()
Definition at line 123 of file class-gf-installation-wizard-step.php.
is ($key)
Definition at line 24 of file class-gf-installation-wizard-step.php.
References get_name().
Referenced by GF_Installation_Wizard_Step_Background_Updates\display().
is_complete ()
Definition at line 98 of file class-gf-installation-wizard-step.php.
set_field_validation_result ($key, $text)
Definition at line 72 of file class-gf-installation-wizard-step.php.
References $text.
Referenced by GF_Installation_Wizard_Step_License_Key\validate(), and GF_Installation_Wizard_Step_Background_Updates\validate().
set_validation_summary ($text)
Definition at line 76 of file class-gf-installation-wizard-step.php.
References $text.
summary ($echo = true)
Definition at line 119 of file class-gf-installation-wizard-step.php.
update ($posted_values = array())
Definition at line 109 of file class-gf-installation-wizard-step.php.
References get_name(), get_values(), and update_option().
validate ()
Definition at line 60 of file class-gf-installation-wizard-step.php.
validation_message ($key, $echo = true)
Definition at line 84 of file class-gf-installation-wizard-step.php.
References $message, and get_field_validation_result().
Referenced by GF_Installation_Wizard_Step_Background_Updates\display(), and GF_Installation_Wizard_Step_License_Key\display().
Field Documentation
$_field_validation_results = array() protected
Definition at line 7 of file class-gf-installation-wizard-step.php.
$_name = '' protected
Definition at line 5 of file class-gf-installation-wizard-step.php.
Referenced by get_name().
$_step_values private
Definition at line 11 of file class-gf-installation-wizard-step.php.
$_validation_summary = '' protected
Definition at line 8 of file class-gf-installation-wizard-step.php.
Referenced by get_validation_summary().
$defaults = array()
Definition at line 10 of file class-gf-installation-wizard-step.php.
The documentation for this class was generated from the following file:
class-gf-installation-wizard-step.php