GravityView: GravityView_Edit_Entry Class Reference
GravityView_Edit_Entry Class Reference
Public Member Functions
__construct ()
add_template_path ($file_paths)
Include this extension templates path.
get_field_blacklist ($entry=array())
Returns array of field types that should not be displayed in Edit Entry.
maybe_not_visible ($visible, $field, $view)
Hide the field or not.
modify_field_blacklist ($fields=array(), $context=NULL)
Edit mode doesn't allow certain field types.
Static Public Member Functions
static check_user_cap_edit_entry ($entry, $view=0)
checks if user has permissions to edit a specific entry
static get_edit_link ($entry, $view_id, $post_id=null, $field_values='')
The edit entry link creates a secure link with a nonce.
static get_nonce_key ($view_id, $form_id, $entry_id)
Return a well formatted nonce key according to GravityView Edit Entry protocol.
static getInstance ()
Data Fields
$instances = array()
Static Public Attributes
static $file
static $instance
Private Member Functions
add_hooks ()
addon_specific_hooks ()
Trigger hooks that are normally run in the admin for Addons, but need to be triggered manually because we're not in the admin.
load_components ($component)
Detailed Description
Definition at line 19 of file class-edit-entry.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Definition at line 35 of file class-edit-entry.php.
References add_hooks(), addon_specific_hooks(), and load_components().
Member Function Documentation
add_hooks()
add_hooks () private
Definition at line 82 of file class-edit-entry.php.
Referenced by __construct().
add_template_path()
add_template_path ($file_paths)
Include this extension templates path.
Parameters
array $file_paths List of template paths ordered
Definition at line 156 of file class-edit-entry.php.
addon_specific_hooks()
addon_specific_hooks () private
Trigger hooks that are normally run in the admin for Addons, but need to be triggered manually because we're not in the admin.
Returns
void
Definition at line 103 of file class-edit-entry.php.
Referenced by __construct().
check_user_cap_edit_entry()
static check_user_cap_edit_entry ($entry, $view = 0) static
checks if user has permissions to edit a specific entry
Needs to be used combined with GravityView_Edit_Entry::user_can_edit_entry for maximum security!!
Parameters
array $entry Gravity Forms entry array
\GV\View | int $view ID of the view you want to check visibility against {
Since
1.9.2}. Required since 2.0
Returns
bool
Runs Filter:
gravityview/edit_entry/user_can_edit_entry Modify whether user can edit an entry.
Since
1.15 Added $entry and $view_id parameters
Parameters
[in,out] boolean $user_can_edit Can the current user edit the current entry? (Default: false)
[in] array $entry Gravity Forms entry array {
Since
1.15}
Parameters
[in] int $view_id ID of the view you want to check visibility against {
Since
1.15}
Definition at line 292 of file class-edit-entry.php.
References $entry, $view_id, GVCommon\get_template_setting(), getInstance(), GravityView_View\getInstance(), gravityview(), and GVCommon\has_cap().
Referenced by GravityView_Entry_Link_Shortcode\has_cap(), GravityView_Edit_Entry_Locking\set_lock(), and GravityView_Edit_Entry_Render\user_can_edit_entry().
get_edit_link()
static get_edit_link ($entry, $view_id, $post_id = null, $field_values = '') static
The edit entry link creates a secure link with a nonce.
It also mimics the URL structure Gravity Forms expects to have so that it formats the display of the edit form like it does in the backend, like "You can edit this post from the post page" fields, for example.
Parameters
$entry array Gravity Forms entry object
$view_id int GravityView view id
$post_id int GravityView Post ID where View may be embedded {
Since
1.9.2}
Parameters
string | array $field_values Parameters to pass in to the Edit Entry form to prefill data. Uses the same format as Gravity Forms "Allow field to be populated dynamically" {
Since
1.9.2} {
See also
https://www.gravityhelp.com/documentation/article/allow-field-to-be-populated-dynamically/ }
Returns
string
Allow passing params to dynamically populate entry with values
Since
1.9.2
Runs Filter:
gravityview/edit/link Filter the edit URL link.
Parameters
[in,out] string $url The url.
array $entry The entry.
\GV\View $view The View.
Definition at line 191 of file class-edit-entry.php.
References $entry, $url, $view_id, and gv_entry_link().
Referenced by GravityView_Entry_Link_Shortcode\get_url().
get_field_blacklist()
get_field_blacklist ($entry = array())
Returns array of field types that should not be displayed in Edit Entry.
Since
1.20
Parameters
array $entry Gravity Forms entry array
Returns
array Blacklist of field types
Runs Filter:
gravityview/edit_entry/field_blacklist Array of fields that should not be displayed in Edit Entry
Since
1.20
Parameters
array $fields Blacklist field type array
array $entry Gravity Forms entry array
Definition at line 256 of file class-edit-entry.php.
References $entry.
Referenced by modify_field_blacklist().
get_nonce_key()
static get_nonce_key ($view_id, $form_id, $entry_id) static
Return a well formatted nonce key according to GravityView Edit Entry protocol.
Parameters
$view_id int GravityView view id
$form_id int Gravity Forms form id
$entry_id int Gravity Forms entry id
Returns
string
Definition at line 173 of file class-edit-entry.php.
References $form_id, and $view_id.
Referenced by gventry\callback(), and GravityView_Edit_Entry_Render\setup_vars().
getInstance()
static getInstance () static
Definition at line 57 of file class-edit-entry.php.
Referenced by gventry\callback(), check_user_cap_edit_entry(), GravityView_Field_Post_Category\edit_entry_post_category_choices(), GravityView_Plugin_Hooks_Gravity_Forms_Survey\fix_survey_field_value(), and oEmbed\render_frontend().
load_components()
load_components ($component) private
Definition at line 67 of file class-edit-entry.php.
Referenced by __construct().
maybe_not_visible()
maybe_not_visible ($visible, $field, $view)
Hide the field or not.
For non-logged in users. For users that have no edit rights on any of the current entries.
Parameters
bool $visible Visible or not.
\GV\Field $field The field.
\GV\View $view The View context.
Returns
bool
Definition at line 123 of file class-edit-entry.php.
References $entry, $field, and GV\get().
modify_field_blacklist()
modify_field_blacklist ($fields = array(), $context = NULL)
Edit mode doesn't allow certain field types.
Parameters
array $fields Existing blacklist fields
string | null $context Context
Returns
array If not edit context, original field blacklist. Otherwise, blacklist including post fields.
Definition at line 236 of file class-edit-entry.php.
References get_field_blacklist().
Field Documentation
$file
$file static
Definition at line 24 of file class-edit-entry.php.
Referenced by GravityView_Edit_Entry_Render\edit_entry_form(), and GravityView_Edit_Entry_Render\render_form_buttons().
$instance
$instance static
Definition at line 26 of file class-edit-entry.php.
$instances
$instances = array()
Definition at line 32 of file class-edit-entry.php.
The documentation for this class was generated from the following file:
class-edit-entry.php