GravityView: WP_Customize_Widgets Class Reference
WP_Customize_Widgets Class Reference
Customize Widgets class.
Public Member Functions
__construct ($manager)
Initial loader.
call_widget_update ($widget_id)
Find and invoke the widget update and control callbacks.
capture_filter_pre_get_option ($value)
Pre-filter captured option values before retrieving.
capture_filter_pre_update_option ($new_value, $option_name, $old_value)
Pre-filter captured option values before updating.
customize_controls_init ()
Make sure all widgets get loaded into the Customizer.
customize_preview_enqueue ()
Enqueue scripts for the Customizer preview.
customize_preview_init ()
Add hooks for the Customizer preview.
customize_register ()
Register Customizer settings and controls for all sidebars and widgets.
enqueue_scripts ()
Enqueue scripts and styles for Customizer panel and export data to JavaScript.
export_preview_data ()
At the very end of the page, at the very end of the wp_footer, communicate the sidebars that appeared on the page.
filter_customize_dynamic_setting_args ($args, $setting_id)
Determine the arguments for a dynamically-created setting.
filter_customize_value_old_sidebars_widgets_data ($old_sidebars_widgets)
Filter old_sidebars_widgets_data Customizer setting.
filter_option_sidebars_widgets_for_theme_switch ($sidebars_widgets)
Filter sidebars_widgets option for theme switch.
get_available_widgets ()
Build up an index of all available widgets for use in Backbone models.
get_setting_args ($id, $overrides=array())
Get common arguments to supply when constructing a Customizer setting.
get_setting_id ($widget_id)
Covert a widget_id into its corresponding Customizer setting ID (option name).
get_widget_control ($args)
Get the widget control markup.
get_widget_control_parts ($args)
Get the widget control markup parts.
is_panel_active ()
Return whether the widgets panel is active, based on whether there are sidebars registered.
is_sidebar_rendered ($sidebar_id)
Determine if a sidebar is rendered on the page.
is_wide_widget ($widget_id)
Determine whether the widget is considered "wide".
is_widget_rendered ($widget_id)
Determine if a widget is rendered on the page.
output_widget_control_templates ()
Render the widget form control templates into the DOM.
override_sidebars_widgets_for_theme_switch ()
Override sidebars_widgets for theme switch.
parse_widget_id ($widget_id)
Covert a widget ID into its id_base and number components.
parse_widget_setting_id ($setting_id)
Convert a widget setting ID (option path) to its id_base and number components.
prepreview_added_sidebars_widgets ()
prepreview_added_widget_instance ()
preview_sidebars_widgets ($sidebars_widgets)
When previewing, make sure the proper previewing widgets are used.
print_footer_scripts ()
Call admin_print_footer_scripts and admin_print_scripts hooks to allow custom scripts from plugins.
print_preview_css ()
Insert default style for highlighted widget at early point so theme stylesheet can override.
print_scripts ()
Call admin_print_scripts-widgets.php and admin_print_scripts hooks to allow custom scripts from plugins.
print_styles ()
Call admin_print_styles-widgets.php and admin_print_styles hooks to allow custom styles from plugins.
refresh_nonces ($nonces)
Refresh nonce for widget updates.
register_settings ()
Inspect the incoming customized data for any widget settings, and dynamically add them up-front so widgets will be initialized properly.
remove_prepreview_filters ()
sanitize_sidebar_widgets ($widget_ids)
Make sure that sidebar widget arrays only ever contain widget IDS.
sanitize_sidebar_widgets_js_instance ($widget_ids)
Strip out widget IDs for widgets which are no longer registered.
sanitize_widget_instance ($value)
Sanitize a widget instance.
sanitize_widget_js_instance ($value)
Convert widget instance into JSON-representable format.
schedule_customize_register ()
Ensure widgets are available for all types of previews.
setup_widget_addition_previews ()
tally_rendered_widgets ($widget)
Keep track of the widgets that were rendered.
tally_sidebars_via_dynamic_sidebar_calls ($has_widgets, $sidebar_id)
Tally the sidebars rendered via dynamic_sidebar().
tally_sidebars_via_is_active_sidebar_calls ($is_active, $sidebar_id)
Tally the sidebars rendered via is_active_sidebar().
wp_ajax_update_widget ()
Update widget settings asynchronously.
Data Fields
$manager
Protected Member Functions
_sort_name_callback ($widget_a, $widget_b)
Naturally order available widgets by name.
count_captured_options ()
Get the number of captured widget option updates.
get_captured_option ($option_name, $default=false)
Get the option that was captured from being saved.
get_captured_options ()
Retrieve captured widget option updates.
get_instance_hash_key ($serialized_instance)
Get MAC for a serialized widget instance string.
get_post_value ($name, $default=null)
Get an unslashed post value or return a default.
get_setting_type ($setting_id)
Get the widget setting type given a setting ID.
is_option_capture_ignored ($option_name)
Determine whether the captured option update should be ignored.
start_capturing_option_updates ()
Start keeping track of changes to widget options, caching new values.
stop_capturing_option_updates ()
Undo any changes to the options since options capture began.
Protected Attributes
$_captured_options = array()
$_is_capturing_option_updates = false
$core_widget_id_bases
$old_sidebars_widgets = array()
$rendered_sidebars = array()
$rendered_widgets = array()
$setting_id_patterns
Detailed Description
Customize Widgets class.
Implements widget management in the Customizer.
Since
3.9.0
See also
WP_Customize_Manager
Definition at line 19 of file class-wp-customize-widgets.php.
Constructor & Destructor Documentation
__construct ($manager)
Initial loader.
Since
3.9.0 public
Parameters
WP_Customize_Manager $manager Customize manager bootstrap instance.
Definition at line 84 of file class-wp-customize-widgets.php.
References $manager, add_action(), and add_filter().
Member Function Documentation
_sort_name_callback ($widget_a, $widget_b) protected
Naturally order available widgets by name.
Since
3.9.0 protected
Parameters
array $widget_a The first widget to compare.
array $widget_b The second widget to compare.
Returns
int Reorder position for the current widget comparison.
Definition at line 910 of file class-wp-customize-widgets.php.
call_widget_update ($widget_id)
Find and invoke the widget update and control callbacks.
Requires that $_POST be populated with the instance data.
Since
3.9.0 public
array $wp_registered_widget_updates array $wp_registered_widget_controls
Parameters
string $widget_id Widget ID.
Returns
WP_Error|array Array containing the updated widget information. A WP_Error object, otherwise.
Definition at line 1286 of file class-wp-customize-widgets.php.
References $form, $name, $option, $value, $wp_registered_widget_controls, $wp_registered_widget_updates, count_captured_options(), did_action(), get_captured_option(), get_captured_options(), get_post_value(), get_setting_id(), null, parse_widget_id(), sanitize_widget_instance(), sanitize_widget_js_instance(), start_capturing_option_updates(), stop_capturing_option_updates(), and wp_slash().
Referenced by wp_ajax_update_widget().
capture_filter_pre_get_option ($value)
Pre-filter captured option values before retrieving.
Since
3.9.0 public
Parameters
mixed $value Value to return instead of the option value.
Returns
mixed Filtered option value.
This filter is documented in wp-includes/option.php
Definition at line 1591 of file class-wp-customize-widgets.php.
References $value, apply_filters(), and current_filter().
capture_filter_pre_update_option ($new_value, $option_name, $old_value)
Pre-filter captured option values before updating.
Since
3.9.0 public
Parameters
mixed $new_value The new option value.
string $option_name Name of the option.
mixed $old_value The old option value.
Returns
mixed Filtered option value.
Definition at line 1568 of file class-wp-customize-widgets.php.
References add_filter(), and is_option_capture_ignored().
count_captured_options () protected
Get the number of captured widget option updates.
Since
3.9.0 protected
Returns
int Number of updated options.
Definition at line 1537 of file class-wp-customize-widgets.php.
Referenced by call_widget_update().
customize_controls_init ()
Make sure all widgets get loaded into the Customizer.
Note: these actions are also fired in wp_ajax_update_widget().
Since
3.9.0 public
This action is documented in wp-admin/includes/ajax-actions.php
This action is documented in wp-admin/includes/ajax-actions.php
This action is documented in wp-admin/widgets.php
Definition at line 280 of file class-wp-customize-widgets.php.
References do_action().
customize_preview_enqueue ()
Enqueue scripts for the Customizer preview.
Since
3.9.0 public
Definition at line 1019 of file class-wp-customize-widgets.php.
References wp_enqueue_script().
customize_preview_init ()
Add hooks for the Customizer preview.
Since
3.9.0 public
Definition at line 971 of file class-wp-customize-widgets.php.
References add_action().
customize_register ()
Register Customizer settings and controls for all sidebars and widgets.
Since
3.9.0 public
array $wp_registered_widgets array $wp_registered_widget_controls array $wp_registered_sidebars
Filter Customizer widget section arguments for a given sidebar.
Since
3.9.0
Parameters
array $section_args Array of Customizer widget section arguments.
string $section_id Customizer section ID.
int | string $sidebar_id Sidebar ID.
Definition at line 319 of file class-wp-customize-widgets.php.
References $i, $sidebars_widgets, $wp_registered_sidebars, $wp_registered_widget_controls, $wp_registered_widgets, __, add_filter(), apply_filters(), get_setting_args(), get_setting_id(), is_registered_sidebar(), is_wide_widget(), and wp_get_sidebars_widgets().
Referenced by schedule_customize_register().
enqueue_scripts ()
Enqueue scripts and styles for Customizer panel and export data to JavaScript.
Since
3.9.0 public
WP_Scripts $wp_scripts array $wp_registered_sidebars array $wp_registered_widgets
This action is documented in wp-admin/admin-header.php
Definition at line 617 of file class-wp-customize-widgets.php.
References $wp_registered_sidebars, $wp_registered_widgets, $wp_scripts, __, _x, do_action(), esc_attr__(), get_available_widgets(), str_replace, wp_enqueue_script(), wp_enqueue_style(), and wp_json_encode().
export_preview_data ()
At the very end of the page, at the very end of the wp_footer, communicate the sidebars that appeared on the page.
Since
3.9.0 public
array $wp_registered_sidebars array $wp_registered_widgets
Definition at line 1056 of file class-wp-customize-widgets.php.
References $wp_registered_sidebars, $wp_registered_widgets, __, and wp_json_encode().
filter_customize_dynamic_setting_args ($args, $setting_id)
Determine the arguments for a dynamically-created setting.
Since
4.2.0 public
Parameters
false | array $args The arguments to the WP_Customize_Setting constructor.
string $setting_id ID for dynamic setting, usually coming from `$_POST['customized']`.
Returns
false|array Setting arguments, false otherwise.
Definition at line 171 of file class-wp-customize-widgets.php.
References get_setting_args(), and get_setting_type().
filter_customize_value_old_sidebars_widgets_data ($old_sidebars_widgets)
Filter old_sidebars_widgets_data Customizer setting.
When switching themes, filter the Customizer setting old_sidebars_widgets_data to supply initial $sidebars_widgets before they were overridden by retrieve_widgets(). The value for old_sidebars_widgets_data gets set in the old theme's sidebars_widgets theme_mod.
See also
WP_Customize_Widgets::handle_theme_switch()
Since
3.9.0 public
Parameters
array $old_sidebars_widgets
Returns
array
Definition at line 246 of file class-wp-customize-widgets.php.
References $old_sidebars_widgets.
filter_option_sidebars_widgets_for_theme_switch ($sidebars_widgets)
Filter sidebars_widgets option for theme switch.
When switching themes, the retrieve_widgets() function is run when the Customizer initializes, and then the new sidebars_widgets here get supplied as the default value for the sidebars_widgets option.
See also
WP_Customize_Widgets::handle_theme_switch()
Since
3.9.0 public
array $sidebars_widgets
Parameters
array $sidebars_widgets
Returns
array
Definition at line 266 of file class-wp-customize-widgets.php.
References $GLOBALS, and $sidebars_widgets.
get_available_widgets ()
Build up an index of all available widgets for use in Backbone models.
Since
3.9.0 public
array $wp_registered_widgets array $wp_registered_widget_controls array $available_widgets
See also
wp_list_widgets()
Returns
array List of available widgets.
Definition at line 827 of file class-wp-customize-widgets.php.
References $wp_registered_widget_controls, $wp_registered_widgets, ABSPATH, get_widget_control(), is_active_widget(), is_wide_widget(), next_widget_id_number(), null, and wp_list_widget_controls_dynamic_sidebar().
Referenced by enqueue_scripts(), and output_widget_control_templates().
get_captured_option ($option_name, $default = false) protected
Get the option that was captured from being saved.
Since
4.2.0 protected
Parameters
string $option_name Option name.
mixed $default Optional. Default value to return if the option does not exist.
Returns
mixed Value set for the option.
Definition at line 1520 of file class-wp-customize-widgets.php.
References $default, and $value.
Referenced by call_widget_update().
get_captured_options () protected
Retrieve captured widget option updates.
Since
3.9.0 protected
Returns
array Array of captured options.
Definition at line 1506 of file class-wp-customize-widgets.php.
References $_captured_options.
Referenced by call_widget_update().
get_instance_hash_key ($serialized_instance) protected
Get MAC for a serialized widget instance string.
Allows values posted back from JS to be rejected if any tampering of the data has occurred.
Since
3.9.0 protected
Parameters
string $serialized_instance Widget instance.
Returns
string MAC for serialized widget instance.
Definition at line 1183 of file class-wp-customize-widgets.php.
Referenced by sanitize_widget_instance(), and sanitize_widget_js_instance().
get_post_value ($name, $default = null) protected
Get an unslashed post value or return a default.
Since
3.9.0
protected
Parameters
string $name Post value.
mixed $default Default post value.
Returns
mixed Unslashed post value or default value.
Definition at line 189 of file class-wp-customize-widgets.php.
References $default, $name, and wp_unslash().
Referenced by call_widget_update(), and wp_ajax_update_widget().
get_setting_args ($id, $overrides = array())
Get common arguments to supply when constructing a Customizer setting.
Since
3.9.0 public
Parameters
string $id Widget setting ID.
array $overrides Array of setting overrides.
Returns
array Possibly modified setting arguments.
Filter the common arguments supplied when constructing a Customizer setting.
Since
3.9.0
See also
WP_Customize_Setting
Parameters
array $args Array of Customizer setting arguments.
string $id Widget setting ID.
Definition at line 762 of file class-wp-customize-widgets.php.
References $id, apply_filters(), and elseif.
Referenced by customize_register(), and filter_customize_dynamic_setting_args().
get_setting_id ($widget_id)
Covert a widget_id into its corresponding Customizer setting ID (option name).
Since
3.9.0 public
Parameters
string $widget_id Widget ID.
Returns
string Maybe-parsed widget ID.
Definition at line 484 of file class-wp-customize-widgets.php.
References parse_widget_id().
Referenced by call_widget_update(), customize_register(), and register_settings().
get_setting_type ($setting_id) protected
Get the widget setting type given a setting ID.
Since
4.2.0 protected
array $cache
Parameters
$setting_id Setting ID.
Returns
string|void Setting type.
Definition at line 116 of file class-wp-customize-widgets.php.
Referenced by filter_customize_dynamic_setting_args(), and register_settings().
get_widget_control ($args)
Get the widget control markup.
Since
3.9.0 public
Parameters
array $args Widget control arguments.
Returns
string Widget control form HTML markup.
Definition at line 923 of file class-wp-customize-widgets.php.
Referenced by get_available_widgets(), and get_widget_control_parts().
get_widget_control_parts ($args)
Get the widget control markup parts.
Since
4.4.0 public
Parameters
array $args Widget control arguments.
Returns
array { string $control Markup for widget control wrapping form. string $content The contents of the widget form itself. }
Definition at line 946 of file class-wp-customize-widgets.php.
References $content, and get_widget_control().
is_option_capture_ignored ($option_name) protected
Determine whether the captured option update should be ignored.
Since
3.9.0 protected
Parameters
string $option_name Option name.
Returns
bool Whether the option capture is ignored.
Definition at line 1494 of file class-wp-customize-widgets.php.
Referenced by capture_filter_pre_update_option().
is_panel_active ()
Return whether the widgets panel is active, based on whether there are sidebars registered.
Since
4.4.0 public
See also
WP_Customize_Panel::$active_callback
array $wp_registered_sidebars
Returns
bool Active.
Definition at line 470 of file class-wp-customize-widgets.php.
References $wp_registered_sidebars.
is_sidebar_rendered ($sidebar_id)
Determine if a sidebar is rendered on the page.
Since
4.0.0 public
Parameters
string $sidebar_id Sidebar ID to check.
Returns
bool Whether the sidebar is rendered.
Definition at line 1113 of file class-wp-customize-widgets.php.
is_wide_widget ($widget_id)
Determine whether the widget is considered "wide".
Core widgets which may have controls wider than 250, but can still be shown in the narrow Customizer panel. The RSS and Text widgets in Core, for example, have widths of 400 and yet they still render fine in the Customizer panel. This method will return all Core widgets as being not wide, but this can be overridden with the is_wide_widget_in_customizer filter.
Since
3.9.0 public
$wp_registered_widget_controls
Parameters
string $widget_id Widget ID.
Returns
bool Whether or not the widget is a "wide" widget.
Filter whether the given widget is considered "wide".
Since
3.9.0
Parameters
bool $is_wide Whether the widget is wide, Default false.
string $widget_id Widget ID.
Definition at line 512 of file class-wp-customize-widgets.php.
References $wp_registered_widget_controls, apply_filters(), and parse_widget_id().
Referenced by customize_register(), and get_available_widgets().
is_widget_rendered ($widget_id)
Determine if a widget is rendered on the page.
Since
4.0.0 public
Parameters
string $widget_id Widget ID to check.
Returns
bool Whether the widget is rendered.
Definition at line 1100 of file class-wp-customize-widgets.php.
output_widget_control_templates ()
Render the widget form control templates into the DOM.
Since
3.9.0 public
Definition at line 705 of file class-wp-customize-widgets.php.
References __, _e, endforeach, esc_html, get_available_widgets(), here, input, label, and placeholder.
override_sidebars_widgets_for_theme_switch ()
Override sidebars_widgets for theme switch.
When switching a theme via the Customizer, supply any previously-configured sidebars_widgets from the target theme as the initial sidebars_widgets setting. Also store the old theme's existing settings so that they can be passed along for storing in the sidebars_widgets theme_mod when the theme gets switched.
Since
3.9.0 public
array $sidebars_widgets array $_wp_sidebars_widgets
Definition at line 212 of file class-wp-customize-widgets.php.
References $GLOBALS, $old_sidebars_widgets, $sidebars_widgets, add_filter(), retrieve_widgets(), and wp_get_sidebars_widgets().
parse_widget_id ($widget_id)
Covert a widget ID into its id_base and number components.
Since
3.9.0 public
Parameters
string $widget_id Widget ID.
Returns
array Array containing a widget's id_base and number components.
Definition at line 540 of file class-wp-customize-widgets.php.
References null.
Referenced by call_widget_update(), get_setting_id(), is_wide_widget(), and wp_ajax_update_widget().
parse_widget_setting_id ($setting_id)
Convert a widget setting ID (option path) to its id_base and number components.
Since
3.9.0 public
Parameters
string $setting_id Widget setting ID.
Returns
WP_Error|array Array containing a widget's id_base and number components, or a WP_Error object.
Definition at line 566 of file class-wp-customize-widgets.php.
References null.
prepreview_added_sidebars_widgets ()
Since
3.9.0
Definition at line 1637 of file class-wp-customize-widgets.php.
References _deprecated_function().
prepreview_added_widget_instance ()
Since
3.9.0
Definition at line 1645 of file class-wp-customize-widgets.php.
References _deprecated_function().
preview_sidebars_widgets ($sidebars_widgets)
When previewing, make sure the proper previewing widgets are used.
Because wp_get_sidebars_widgets() gets called early at init (via wp_convert_widget_settings()) and can set global variable $_wp_sidebars_widgets to the value of get_option('sidebars_widgets') before the Customizer preview filter is added, we have to reset it after the filter has been added.
Since
3.9.0 public
Parameters
array $sidebars_widgets List of widgets for the current sidebar.
Returns
array
Definition at line 1006 of file class-wp-customize-widgets.php.
References $sidebars_widgets, and get_option().
print_footer_scripts ()
Call admin_print_footer_scripts and admin_print_scripts hooks to allow custom scripts from plugins.
Since
3.9.0 public
This action is documented in wp-admin/admin-footer.php
This action is documented in wp-admin/admin-footer.php
Definition at line 744 of file class-wp-customize-widgets.php.
References do_action().
print_preview_css ()
Insert default style for highlighted widget at early point so theme stylesheet can override.
Since
3.9.0 public
Runs Actions:
wp_print_styles
Definition at line 1032 of file class-wp-customize-widgets.php.
References outline, and shadow.
print_scripts ()
Call admin_print_scripts-widgets.php and admin_print_scripts hooks to allow custom scripts from plugins.
Since
3.9.0 public
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
Definition at line 599 of file class-wp-customize-widgets.php.
References do_action().
print_styles ()
Call admin_print_styles-widgets.php and admin_print_styles hooks to allow custom styles from plugins.
Since
3.9.0 public
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
Definition at line 584 of file class-wp-customize-widgets.php.
References do_action().
refresh_nonces ($nonces)
Refresh nonce for widget updates.
Since
4.2.0 public
Parameters
array $nonces Array of nonces.
Returns
array $nonces Array of nonces.
Definition at line 986 of file class-wp-customize-widgets.php.
register_settings ()
Inspect the incoming customized data for any widget settings, and dynamically add them up-front so widgets will be initialized properly.
Since
4.2.0 public
Definition at line 135 of file class-wp-customize-widgets.php.
References get_setting_id(), get_setting_type(), and wp_unslash().
remove_prepreview_filters ()
Since
3.9.0
Definition at line 1653 of file class-wp-customize-widgets.php.
References _deprecated_function().
sanitize_sidebar_widgets ($widget_ids)
Make sure that sidebar widget arrays only ever contain widget IDS.
Used as the 'sanitize_callback' for each $sidebars_widgets setting.
Since
3.9.0 public
Parameters
array $widget_ids Array of widget IDs.
Returns
array Array of sanitized widget IDs.
Definition at line 804 of file class-wp-customize-widgets.php.
sanitize_sidebar_widgets_js_instance ($widget_ids)
Strip out widget IDs for widgets which are no longer registered.
One example where this might happen is when a plugin orphans a widget in a sidebar upon deactivation.
Since
3.9.0 public
array $wp_registered_widgets
Parameters
array $widget_ids List of widget IDs.
Returns
array Parsed list of widget IDs.
Definition at line 1265 of file class-wp-customize-widgets.php.
References $wp_registered_widgets.
sanitize_widget_instance ($value)
Sanitize a widget instance.
Unserialize the JS-instance for storing in the options. It's important that this filter only get applied to an instance once.
Since
3.9.0 public
Parameters
array $value Widget instance to sanitize.
Returns
array|void Sanitized widget instance.
Definition at line 1199 of file class-wp-customize-widgets.php.
References $value, and get_instance_hash_key().
Referenced by call_widget_update().
sanitize_widget_js_instance ($value)
Convert widget instance into JSON-representable format.
Since
3.9.0 public
Parameters
array $value Widget instance to convert to JSON.
Returns
array JSON-converted widget instance.
Definition at line 1237 of file class-wp-customize-widgets.php.
References $value, and get_instance_hash_key().
Referenced by call_widget_update(), and wp_ajax_update_widget().
schedule_customize_register ()
Ensure widgets are available for all types of previews.
When in preview, hook to 'customize_register' for settings after WordPress is loaded so that all filters have been initialized (e.g. Widget Visibility).
Since
3.9.0 public
Definition at line 301 of file class-wp-customize-widgets.php.
References add_action(), customize_register(), and is_admin().
setup_widget_addition_previews ()
Since
3.9.0
Definition at line 1629 of file class-wp-customize-widgets.php.
References _deprecated_function().
start_capturing_option_updates () protected
Start keeping track of changes to widget options, caching new values.
Since
3.9.0 protected
Definition at line 1547 of file class-wp-customize-widgets.php.
References add_filter().
Referenced by call_widget_update().
stop_capturing_option_updates () protected
Undo any changes to the options since options capture began.
Since
3.9.0 protected
Definition at line 1610 of file class-wp-customize-widgets.php.
References remove_filter().
Referenced by call_widget_update().
tally_rendered_widgets ($widget)
Keep track of the widgets that were rendered.
Since
3.9.0 public
Parameters
array $widget Rendered widget to tally.
Definition at line 1087 of file class-wp-customize-widgets.php.
tally_sidebars_via_dynamic_sidebar_calls ($has_widgets, $sidebar_id)
Tally the sidebars rendered via dynamic_sidebar().
Keep track of the times that dynamic_sidebar() is called in the template, and assume this means the sidebar would be rendered on the template if there were widgets populating it.
Since
3.9.0 public
Parameters
bool $has_widgets Whether the current sidebar has widgets.
string $sidebar_id Sidebar ID.
Returns
bool
Definition at line 1158 of file class-wp-customize-widgets.php.
References is_registered_sidebar().
tally_sidebars_via_is_active_sidebar_calls ($is_active, $sidebar_id)
Tally the sidebars rendered via is_active_sidebar().
Keep track of the times that is_active_sidebar() is called in the template, and assume that this means that the sidebar would be rendered on the template if there were widgets populating it.
Since
3.9.0 public
Parameters
bool $is_active Whether the sidebar is active.
string $sidebar_id Sidebar ID.
Returns
bool
Definition at line 1132 of file class-wp-customize-widgets.php.
References is_registered_sidebar().
wp_ajax_update_widget ()
Update widget settings asynchronously.
Allows the Customizer to update a widget using its form, but return the new instance info via Ajax instead of saving it to the options table.
Most code here copied from wp_ajax_save_widget()
Since
3.9.0 public
See also
wp_ajax_save_widget()
This action is documented in wp-admin/includes/ajax-actions.php
This action is documented in wp-admin/includes/ajax-actions.php
This action is documented in wp-admin/widgets.php
Definition at line 1412 of file class-wp-customize-widgets.php.
References $form, call_widget_update(), current_user_can(), do_action(), get_post_value(), is_wp_error(), parse_widget_id(), sanitize_widget_js_instance(), wp_die(), wp_send_json_error(), and wp_send_json_success().
Field Documentation
$_captured_options = array() protected
Definition at line 1474 of file class-wp-customize-widgets.php.
Referenced by get_captured_options().
$_is_capturing_option_updates = false protected
Definition at line 1483 of file class-wp-customize-widgets.php.
$core_widget_id_bases protected
Initial value:
= array(
        'archives', 'calendar', 'categories', 'links', 'meta',
        'nav_menu', 'pages', 'recent-comments', 'recent-posts',
        'rss', 'search', 'tag_cloud', 'text',
    )
Definition at line 37 of file class-wp-customize-widgets.php.
$manager
Definition at line 28 of file class-wp-customize-widgets.php.
Referenced by __construct().
$old_sidebars_widgets = array() protected
Definition at line 62 of file class-wp-customize-widgets.php.
Referenced by filter_customize_value_old_sidebars_widgets_data(), and override_sidebars_widgets_for_theme_switch().
$rendered_sidebars = array() protected
Definition at line 48 of file class-wp-customize-widgets.php.
$rendered_widgets = array() protected
Definition at line 55 of file class-wp-customize-widgets.php.
$setting_id_patterns protected
Initial value:
= array(
        'widget_instance' => '/^(widget_.+?)(?:\[(\d+)\])?$/',
        'sidebar_widgets' => '/^sidebars_widgets\[(.+?)\]$/',
    )
Definition at line 71 of file class-wp-customize-widgets.php.
The documentation for this class was generated from the following file:
class-wp-customize-widgets.php