GravityView: GravityView_Fields Class Reference
GravityView_Fields Class Reference
Wanted to extend GF_Fields, but couldn't because static variables are inherited, so $_fields would always be GF results.
Static Public Member Functions
static create ($properties)
static create ($properties)
static exists ($field_name)
Does the field exist (has it been registered)?
static exists ($field_name)
Does the field exist (has it been registered)?
static get ($field_name)
Alias for get_instance()
static get ($field_name)
Alias for get_instance()
static get_all ($group= '')
Get all fields.
static get_all ($group= '')
Get all fields.
static get_associated_field ($gf_field)
Alias for get_instance()
static get_associated_field ($gf_field)
Alias for get_instance()
static get_instance ($field_name)
static get_instance ($field_name)
static register ($field)
static register ($field)
Static Protected Attributes
static $_fields = array()
Detailed Description
Wanted to extend GF_Fields, but couldn't because static variables are inherited, so $_fields would always be GF results.
See also
GF_Fields
Definition at line 14 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
Member Function Documentation
static create ($properties) static
Parameters
array $properties
Returns
GravityView_Field | bool
Definition at line 44 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
References $class, and $field.
static create ($properties) static
Parameters
array $properties
Returns
GravityView_Field | bool
Definition at line 44 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
References $class, and $field.
static exists ($field_name) static
Does the field exist (has it been registered)?
Parameters
string $field_name
Returns
bool True: yes, it exists; False: nope
Definition at line 64 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
static exists ($field_name) static
Does the field exist (has it been registered)?
Parameters
string $field_name
Returns
bool True: yes, it exists; False: nope
Definition at line 64 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
static get ($field_name) static
Alias for get_instance()
Parameters
$field_name
Returns
GravityView_Field|false
Definition at line 84 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
Referenced by GVCommon\is_field_numeric().
static get ($field_name) static
Alias for get_instance()
Parameters
$field_name
Returns
GravityView_Field|false
Definition at line 84 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
static get_all ($group = '') static
Get all fields.
Since
1.16 Added $group parameter
Parameters
string $group Optional. If defined, fetch all fields in a group
Returns
GravityView_Field[]
Definition at line 117 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
References $field.
static get_all ($group = '') static
Get all fields.
Since
1.16 Added $group parameter
Parameters
string $group Optional. If defined, fetch all fields in a group
Returns
GravityView_Field[]
Definition at line 117 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
References $field.
Referenced by GVCommon\get_form_fields().
static get_associated_field ($gf_field) static
Alias for get_instance()
Parameters
string | GF_Field $field_name Gravity Forms field class or the class name type
Returns
GravityView_Field
Definition at line 95 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
References $field.
static get_associated_field ($gf_field) static
Alias for get_instance()
Parameters
string | GF_Field $field_name Gravity Forms field class or the class name type
Returns
GravityView_Field
Definition at line 95 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
References $field.
Referenced by GravityView_API\field_value().
static get_instance ($field_name) static
Parameters
string $field_name
Returns
GravityView_Field|false
Definition at line 73 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
static get_instance ($field_name) static
Parameters
string $field_name
Returns
GravityView_Field|false
Definition at line 73 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
static register ($field) static
Parameters
GravityView_Field $field Field to register
Exceptions
Exception If requirements aren't met
Returns
void
Definition at line 26 of file Sites/vagrant-local/www/wordpress-default/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
References $field.
static register ($field) static
Parameters
GravityView_Field $field Field to register
Exceptions
Exception If requirements aren't met
Returns
void
Definition at line 26 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
References $field.
Referenced by GravityView_Field\__construct().
Field Documentation
static $_fields = array() static protected
Definition at line 17 of file Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php.
The documentation for this class was generated from the following file:
Pressmatic Sites/gravityview-core-dev/app/public/wp-content/plugins/gravityview/includes/fields/class-gravityview-fields.php