GravityView: GF_Field_Post_Custom_Field Class Reference
GF_Field_Post_Custom_Field Class Reference
Public Member Functions
allow_html ()
get_field_input ($form, $value= '', $entry=null)
get_form_editor_field_settings ()
get_form_editor_field_title ()
is_conditional_logic_supported ()
Public Member Functions inherited from GF_Field
__construct ($data=array())
& __get ($key)
__isset ($key)
__set ($key, $value)
__unset ($key)
add_button ($field_groups)
Adds the field button to the specified group.
allow_html ()
Override this if the field should allow html tags to be saved with the entry value.
get_admin_buttons ()
Returns the field admin buttons for display in the form editor.
get_conditional_logic_event ($event)
Maybe return the input attribute which will trigger evaluation of conditional logic rules which depend on this field.
get_description ($description, $css_class)
Returns the markup for the field description.
get_entry_inputs ()
Override and return null if a multi-input field value is to be stored under the field ID instead of the individual input IDs.
get_field_content ($value, $force_frontend_label, $form)
Returns the field markup; including field label, description, validation, and the form editor admin buttons.
get_field_input ($form, $value= '', $entry=null)
Returns the field inner markup.
get_field_label ($force_frontend_label, $value)
Retrieve the field label.
get_field_placeholder_attribute ()
If the field placeholder property has a value return the input placeholder attribute.
get_first_input_id ($form)
Returns the input ID to be assigned to the field label for attribute.
get_form_editor_button ()
Returns the field button properties for the form editor.
get_form_editor_field_settings ()
Returns the class names of the settings which should be available on the field in the form editor.
get_form_editor_field_title ()
Returns the field title.
get_form_editor_inline_script_on_page_render ()
Returns the scripts to be included for this field type in the form editor.
get_form_inline_script_on_page_render ($form)
Returns the scripts to be included with the form init scripts on the front-end.
get_input_placeholder_attribute ($input)
If the input placeholder property has a value return the input placeholder attribute.
get_input_placeholder_value ($input)
If configured retrieve the input placeholder value.
get_input_type ()
Retrieves the field input type.
get_input_value_submission ($standard_name, $custom_name= '', $field_values=array(), $get_from_post_global_var=true)
Retrieve the input value on submission.
get_tabindex ()
Maybe return the tabindex attribute.
get_value_default ()
Retrieve the field default value.
get_value_default_if_empty ($value)
Returns the field default value if the field does not already have a value.
get_value_entry_detail ($value, $currency= '', $use_text=false, $format= 'html', $media= 'screen')
Format the entry value for display on the entry detail page and for the {all_fields} merge tag.
get_value_entry_list ($value, $entry, $field_id, $columns, $form)
Format the entry value for display on the entries list page.
get_value_export ($entry, $input_id= '', $use_text=false, $is_csv=false)
Format the entry value before it is used in entry exports and by framework add-ons using GFAddOn::get_field_value().
get_value_merge_tag ($value, $input_id, $entry, $form, $modifier, $raw_value, $url_encode, $esc_html, $format, $nl2br)
Format the entry value for when the field/input merge tag is processed.
get_value_save_entry ($value, $form, $input_name, $lead_id, $lead)
Format the value before it is saved to the Entry Object.
get_value_submission ($field_values, $get_from_post_global_var=true)
Retrieve the field value on submission.
has_calculation ()
Is this a calculated product field or a number field with a calculation enabled and formula configured.
is_conditional_logic_supported ()
Override to indicate if this field type can be used when configuring conditional logic rules.
is_description_above ($form)
Determines if the field description should be positioned above or below the input.
is_entry_detail ()
Determine if the current location is the entry detail page.
is_entry_detail_edit ()
Determine if the current location is the edit entry page.
is_form_editor ()
Determine if the current location is the form editor.
is_value_submission_empty ($form_id)
Used to determine the required validation result.
offsetExists ($offset)
Handles array notation.
offsetGet ($offset)
offsetSet ($offset, $data)
offsetUnset ($offset)
register_form_init_scripts ($form)
Registers the script returned by get_form_inline_script_on_page_render() for display on the front-end.
sanitize_entry_value ($value, $form_id)
Sanitize the entry value before it is saved.
sanitize_settings ()
Forces settings into expected values while saving the form object.
sanitize_settings_choices ($choices=null)
Sanitize the field choices property.
sanitize_settings_conditional_logic ($logic=null)
Sanitize the field conditional logic object.
strip_script_tag ($string)
Strip unsafe tags from the field value.
validate ($value, $form)
Override this method to perform custom validation logic.
Data Fields
$type = 'post_custom_field'
Data Fields inherited from GF_Field
const SUPPRESS_DEPRECATION_NOTICE = true
Detailed Description
Definition at line 7 of file class-gf-field-post-custom-field.php.
Member Function Documentation
allow_html ()
Definition at line 63 of file class-gf-field-post-custom-field.php.
get_field_input ($form, $value = '', $entry = null)
Definition at line 38 of file class-gf-field-post-custom-field.php.
References $class, $field_id, $form, $form_id, $id, $size, $value, absint(), esc_attr(), GF_Field\get_conditional_logic_event(), GF_Field\get_field_placeholder_attribute(), GF_Field\get_tabindex(), GF_Field\is_entry_detail(), and GF_Field\is_form_editor().
get_form_editor_field_settings ()
Definition at line 15 of file class-gf-field-post-custom-field.php.
get_form_editor_field_title ()
Definition at line 11 of file class-gf-field-post-custom-field.php.
References esc_attr__().
is_conditional_logic_supported ()
Definition at line 34 of file class-gf-field-post-custom-field.php.
Field Documentation
$type = 'post_custom_field'
Definition at line 9 of file class-gf-field-post-custom-field.php.
The documentation for this class was generated from the following file:
class-gf-field-post-custom-field.php