GravityView: Template_Context Class Reference
Template_Context Class Reference
If this file is called directly, abort.
Static Public Member Functions
static from_template ($template, $data=array())
Create a context from a Template.
Data Fields
$display_value
$entries
$entry
$field
$fields
$request
$source
$template
$value
$view
Detailed Description
If this file is called directly, abort.
A template Context class.
This is provided to most template files as a global.
Definition at line 14 of file class-gv-context-template.php.
Member Function Documentation
from_template()
static from_template ($template, $data = array()) static
Create a context from a Template.
Parameters
\GV\Template | array $template The template or array with values expected in a template
array $data Additional data not tied to the template object.
Returns
The context holder.
Data.
Shortcuts.
Definition at line 73 of file class-gv-context-template.php.
References $template, and GV\get().
Referenced by Page_Size\override_view_page_size(), and GravityView_View\render_widget_hooks().
Field Documentation
$display_value
$display_value
Definition at line 53 of file class-gv-context-template.php.
$entries
$entries
Definition at line 33 of file class-gv-context-template.php.
$entry
$entry
Definition at line 28 of file class-gv-context-template.php.
$field
$field
Definition at line 43 of file class-gv-context-template.php.
$fields
$fields
Definition at line 38 of file class-gv-context-template.php.
$request
$request
Definition at line 63 of file class-gv-context-template.php.
$source
$source
Definition at line 48 of file class-gv-context-template.php.
$template
$template
Definition at line 18 of file class-gv-context-template.php.
$value
$value
Definition at line 58 of file class-gv-context-template.php.
$view
$view
Definition at line 23 of file class-gv-context-template.php.
The documentation for this class was generated from the following file:
class-gv-context-template.php