GravityView: GravityView_HTML_Elements Class Reference
GravityView_HTML_Elements Class Reference
Public Member Functions
field_dropdown ($args=array())
Renders an HTML Dropdown of all the fields in a form.
form_dropdown ($args=array())
Renders an HTML Dropdown of all the Products (Downloads)
select ($args=array())
Renders an HTML Dropdown.
Detailed Description
Definition at line 16 of file class-gravityview-html-elements.php.
Member Function Documentation
field_dropdown()
field_dropdown ($args = array())
Renders an HTML Dropdown of all the fields in a form.
Parameters
array $args Arguments for the dropdown
Returns
string $output Product dropdown
Definition at line 68 of file class-gravityview-html-elements.php.
References $args, $field, $field_id, $output, GVCommon\get_sortable_fields_array(), and select().
form_dropdown()
form_dropdown ($args = array())
Renders an HTML Dropdown of all the Products (Downloads)
Since
1.22.1
Parameters
array $args Arguments for the dropdown
Returns
string $output Dropdown of forms
Definition at line 26 of file class-gravityview-html-elements.php.
References $args, GV\$form, $forms, $output, gravityview_get_forms(), and select().
select()
select ($args = array())
Renders an HTML Dropdown.
Since
1.22.1
Parameters
array $args
Returns
string
Definition at line 110 of file class-gravityview-html-elements.php.
References $args, $class, $output, and $value.
Referenced by field_dropdown(), and form_dropdown().
The documentation for this class was generated from the following file:
class-gravityview-html-elements.php