GravityView: AtomParser Class Reference
AtomParser Class Reference
Public Member Functions
__construct ()
PHP5 constructor.
_default ($parser, $data)
_p ($msg)
AtomParser ()
PHP4 constructor.
cdata ($parser, $data)
end_element ($parser, $name)
end_ns ($parser, $prefix)
error_handler ($log_level, $log_text, $error_file, $error_line)
is_declared_content_ns ($new_mapping)
ns_to_prefix ($qname, $attr=false)
parse ()
start_element ($parser, $name, $attrs)
start_ns ($parser, $prefix, $uri)
xml_escape ($string)
Data Fields
$ATOM_CONTENT_ELEMENTS = array('content','summary','title','subtitle','rights')
$ATOM_SIMPLE_ELEMENTS = array('id','updated','published','draft')
$content_ns_contexts = array()
$content_ns_decls = array()
$current
$debug = false
$depth = 0
$feed
$FILE = "php://input"
$in_content
$indent = 2
$is_html = false
$is_text = true
$is_xhtml = false
$NS = 'http://www.w3.org/2005/Atom'
$ns_contexts = array()
$ns_decls = array()
$skipped_div = false
Detailed Description
Definition at line 65 of file atomlib.php.
Constructor & Destructor Documentation
__construct ()
PHP5 constructor.
Definition at line 93 of file atomlib.php.
References null.
Member Function Documentation
_default ($parser, $data)
Definition at line 309 of file atomlib.php.
_p ($msg)
Definition at line 108 of file atomlib.php.
References $msg.
Referenced by cdata(), end_element(), end_ns(), start_element(), and start_ns().
AtomParser ()
PHP4 constructor.
Definition at line 104 of file atomlib.php.
cdata ($parser, $data)
Definition at line 302 of file atomlib.php.
References _p(), and str_replace.
end_element ($parser, $name)
Definition at line 239 of file atomlib.php.
References $name, _p(), ns_to_prefix(), null, and xml_escape().
end_ns ($parser, $prefix)
Definition at line 298 of file atomlib.php.
References $prefix, and _p().
error_handler ($log_level, $log_text, $error_file, $error_line)
Definition at line 114 of file atomlib.php.
is_declared_content_ns ($new_mapping)
Definition at line 346 of file atomlib.php.
Referenced by start_element().
ns_to_prefix ($qname, $attr = false)
Definition at line 314 of file atomlib.php.
References $name, and null.
Referenced by end_element(), and start_element().
parse ()
Definition at line 118 of file atomlib.php.
References __.
start_element ($parser, $name, $attrs)
Definition at line 160 of file atomlib.php.
References $feed, $name, $value, _p(), is_declared_content_ns(), ns_to_prefix(), and xml_escape().
start_ns ($parser, $prefix, $uri)
Definition at line 293 of file atomlib.php.
References $prefix, and _p().
xml_escape ($string)
Definition at line 357 of file atomlib.php.
References str_replace.
Referenced by end_element(), and start_element().
Field Documentation
$ATOM_CONTENT_ELEMENTS = array('content','summary','title','subtitle','rights')
Definition at line 68 of file atomlib.php.
$ATOM_SIMPLE_ELEMENTS = array('id','updated','published','draft')
Definition at line 69 of file atomlib.php.
$content_ns_contexts = array()
Definition at line 79 of file atomlib.php.
$content_ns_decls = array()
Definition at line 78 of file atomlib.php.
$current
Definition at line 88 of file atomlib.php.
$debug = false
Definition at line 71 of file atomlib.php.
$depth = 0
Definition at line 73 of file atomlib.php.
$feed
Definition at line 87 of file atomlib.php.
Referenced by start_element().
$FILE = "php://input"
Definition at line 85 of file atomlib.php.
$in_content
Definition at line 75 of file atomlib.php.
$indent = 2
Definition at line 74 of file atomlib.php.
$is_html = false
Definition at line 81 of file atomlib.php.
$is_text = true
Definition at line 82 of file atomlib.php.
$is_xhtml = false
Definition at line 80 of file atomlib.php.
$NS = 'http://www.w3.org/2005/Atom'
Definition at line 67 of file atomlib.php.
$ns_contexts = array()
Definition at line 76 of file atomlib.php.
$ns_decls = array()
Definition at line 77 of file atomlib.php.
$skipped_div = false
Definition at line 83 of file atomlib.php.
The documentation for this class was generated from the following file:
atomlib.php