GravityView: WP_Widget Class Reference
WP_Widget Class Reference
Core base class extended to register widgets.
Public Member Functions
__construct ($id_base, $name, $widget_options=array(), $control_options=array())
PHP5 constructor.
_get_display_callback ()
Retrieves the widget display callback.
_get_form_callback ()
Retrieves the form callback.
_get_update_callback ()
Retrieves the widget update callback.
_register ()
Register all widget instances of this widget class.
_register_one ($number=-1)
Register an instance of the widget class.
_set ($number)
Set the internal order number for the widget instance.
display_callback ($args, $widget_args=1)
Generate the actual widget content (Do NOT override).
form ($instance)
Outputs the settings update form.
form_callback ($widget_args=1)
Generate the widget control form (Do NOT override).
get_field_id ($field_name)
Constructs id attributes for use in {.
get_field_name ($field_name)
Constructs name attributes for use in form() fields.
get_settings ()
Get the settings for all instances of the widget class.
is_preview ()
Determine whether the current request is inside the Customizer preview.
save_settings ($settings)
Save the settings for all instances of the widget class.
update ($new_instance, $old_instance)
Updates a particular instance of a widget.
update_callback ($deprecated=1)
Deal with changed settings (Do NOT override).
widget ($args, $instance)
Echoes the widget content.
WP_Widget ($id_base, $name, $widget_options=array(), $control_options=array())
PHP4 constructor.
Data Fields
$control_options
$id = false
$id_base
$name
$number = false
$updated = false
$widget_options
Detailed Description
Core base class extended to register widgets.
This class must be extended for each widget and WP_Widget::widget(), WP_Widget::update() and WP_Widget::form() need to be overridden.
Since
2.8.0
4.4.0 Moved to its own file from wp-includes/widgets.php
Definition at line 19 of file class-wp-widget.php.
Constructor & Destructor Documentation
__construct ($id_base, $name, $widget_options = array(), $control_options = array())
PHP5 constructor.
Since
2.8.0 public
Parameters
string $id_base Optional Base ID for the widget, lowercase and unique. If left empty, a portion of the widget's class name will be used Has to be unique.
string $name Name for the widget displayed on the configuration page.
array $widget_options Optional. Widget options. See wp_register_sidebar_widget() for information on accepted arguments. Default empty array.
array $control_options Optional. Widget control options. See wp_register_widget_control() for information on accepted arguments. Default empty array.
Definition at line 154 of file class-wp-widget.php.
References $control_options, $id_base, $name, $widget_options, name, and wp_parse_args().
Referenced by WP_Widget().
Member Function Documentation
_get_display_callback ()
Retrieves the widget display callback.
Since
2.8.0
Returns
callable Display callback.
Definition at line 264 of file class-wp-widget.php.
Referenced by _register_one().
_get_form_callback ()
Retrieves the form callback.
Since
2.8.0
Returns
callable Form callback.
Definition at line 286 of file class-wp-widget.php.
Referenced by _register_one().
_get_update_callback ()
Retrieves the widget update callback.
Since
2.8.0
Returns
callable Update callback.
Definition at line 275 of file class-wp-widget.php.
Referenced by _register_one().
_register ()
Register all widget instances of this widget class.
Since
2.8.0 private
Definition at line 217 of file class-wp-widget.php.
References $number, _register_one(), _set(), and get_settings().
_register_one ($number = -1)
Register an instance of the widget class.
Since
2.8.0 private
Parameters
integer $number Optional. The unique order number of this widget instance compared to other instances of the same class. Default -1.
Definition at line 525 of file class-wp-widget.php.
References $number, _get_display_callback(), _get_form_callback(), _get_update_callback(), _register_widget_form_callback(), _register_widget_update_callback(), name, and wp_register_sidebar_widget().
Referenced by _register().
_set ($number)
Set the internal order number for the widget instance.
Since
2.8.0 private
Parameters
int $number The unique order number of this widget instance compared to other instances of the same class.
Definition at line 252 of file class-wp-widget.php.
References $number.
Referenced by _register(), display_callback(), form_callback(), and update_callback().
display_callback ($args, $widget_args = 1)
Generate the actual widget content (Do NOT override).
Finds the instance and calls {
See also
WP_Widget::widget()}.
Since
2.8.0 public
Parameters
array $args Display arguments. See {
See also
WP_Widget::widget()} for information on accepted arguments.
Parameters
int | array $widget_args { Optional. Internal order number of the widget instance, or array of multi-widget arguments. Default 1.
int $number Number increment used for multiples of the same widget. }
Filter the settings for a particular widget instance.
Returning false will effectively short-circuit display of the widget.
Since
2.8.0
Parameters
array $instance The current widget instance's settings.
WP_Widget $this The current widget instance.
array $args An array of default widget arguments.
Definition at line 327 of file class-wp-widget.php.
References $number, _set(), apply_filters(), get_settings(), is_preview(), widget(), wp_parse_args(), and wp_suspend_cache_addition().
form ($instance)
Outputs the settings update form.
Since
2.8.0 public
Parameters
array $instance Current settings.
Returns
string Default return is 'noform'.
Definition at line 133 of file class-wp-widget.php.
References __.
Referenced by form_callback().
form_callback ($widget_args = 1)
Generate the widget control form (Do NOT override).
Since
2.8.0 public
Parameters
int | array $widget_args Widget instance number or array of widget arguments.
Returns
string|null
Filter the widget instance's settings before displaying the control form.
Returning false effectively short-circuits display of the control form.
Since
2.8.0
Parameters
array $instance The current widget instance's settings.
WP_Widget $this The current widget instance.
Fires at the end of the widget control form.
Use this hook to add extra fields to the widget form. The hook is only fired if the value passed to the 'widget_form_callback' hook is not false.
Note: If the widget has no form, the text echoed from the default form method can be hidden using CSS.
Since
2.8.0
Parameters
WP_Widget $this The widget instance, passed by reference.
null $return Return null if new fields are added.
array $instance An array of the widget's settings.
Definition at line 463 of file class-wp-widget.php.
References _set(), apply_filters(), do_action_ref_array(), form(), get_settings(), null, and wp_parse_args().
get_field_id ($field_name)
Constructs id attributes for use in {.
See also
WP_Widget::form()} fields.
This function should be used in form() methods to create id attributes for fields to be saved by {
See also
WP_Widget::update()}.
Since
2.8.0
4.4.0 Array format field IDs are now accepted. public
Parameters
string $field_name Field name.
Returns
string ID attribute for $field_name.
Definition at line 207 of file class-wp-widget.php.
References str_replace.
Referenced by WP_Widget_Tag_Cloud\form().
get_field_name ($field_name)
Constructs name attributes for use in form() fields.
This function should be used in form() methods to create name attributes for fields to be saved by update()
Since
2.8.0
4.4.0 Array format field names are now accepted.
Parameters
string $field_name Field name
Returns
string Name attribute for $field_name
Definition at line 186 of file class-wp-widget.php.
Referenced by WP_Widget_Tag_Cloud\form().
get_settings ()
Get the settings for all instances of the widget class.
Since
2.8.0 public
Returns
array Multi-dimensional array of widget instance settings.
Definition at line 552 of file class-wp-widget.php.
References get_option(), save_settings(), and wp_convert_widget_settings().
Referenced by _register(), display_callback(), form_callback(), and update_callback().
is_preview ()
Determine whether the current request is inside the Customizer preview.
If true – the current request is inside the Customizer preview, then the object cache gets suspended and widgets should check this to decide whether they should store anything persistently to the object cache, to transients, or anywhere else.
Since
3.9.0 public
WP_Customize_Manager $wp_customize
Returns
bool True if within the Customizer preview, false if not.
Definition at line 305 of file class-wp-widget.php.
References $wp_customize.
Referenced by display_callback(), GravityView_Search_WP_Widget\form(), GravityView_Search_WP_Widget\update(), and update_callback().
save_settings ($settings)
Save the settings for all instances of the widget class.
Since
2.8.0 public
Parameters
array $settings Multi-dimensional array of widget instance settings.
Definition at line 539 of file class-wp-widget.php.
References update_option().
Referenced by get_settings(), and update_callback().
update ($new_instance, $old_instance)
Updates a particular instance of a widget.
This function should check that $new_instance is set correctly. The newly-calculated value of $instance should be returned. If false is returned, the instance won't be saved/updated.
Since
2.8.0 public
Parameters
array $new_instance New settings for this instance as input by the user via WP_Widget::form().
array $old_instance Old settings for this instance.
Returns
array Settings to save or bool false to cancel saving.
Definition at line 120 of file class-wp-widget.php.
Referenced by update_callback().
update_callback ($deprecated = 1)
Deal with changed settings (Do NOT override).
Since
2.8.0 public
array $wp_registered_widgets
Parameters
int $deprecated Not used.
Filter a widget's settings before saving.
Returning false will effectively short-circuit the widget's ability to update settings.
Since
2.8.0
Parameters
array $instance The current widget instance's settings.
array $new_instance Array of new widget settings.
array $old_instance Array of old widget settings.
WP_Widget $this The current widget instance.
Definition at line 379 of file class-wp-widget.php.
References $id_base, $number, $wp_registered_widgets, _set(), apply_filters(), elseif, get_settings(), is_preview(), save_settings(), stripslashes_deep(), update(), and wp_suspend_cache_addition().
widget ($args, $instance)
Echoes the widget content.
Sub-classes should over-ride this function to generate their widget code.
Since
2.8.0 public
Parameters
array $args Display arguments including 'before_title', 'after_title', 'before_widget', and 'after_widget'.
array $instance The settings for the particular instance of the widget.
Definition at line 101 of file class-wp-widget.php.
Referenced by display_callback().
WP_Widget ($id_base, $name, $widget_options = array(), $control_options = array())
PHP4 constructor.
Parameters
string $id_base
string $name
array $widget_options
array $control_options
Definition at line 170 of file class-wp-widget.php.
References $control_options, $id_base, $name, $widget_options, __construct(), and _deprecated_constructor().
Field Documentation
$control_options
Definition at line 55 of file class-wp-widget.php.
Referenced by __construct(), and WP_Widget().
$id = false
Definition at line 73 of file class-wp-widget.php.
Referenced by WP_Widget_Tag_Cloud\form(), WP_Widget_Recent_Posts\widget(), and WP_Widget_Recent_Comments\widget().
$id_base
Definition at line 28 of file class-wp-widget.php.
Referenced by __construct(), update_callback(), and WP_Widget().
$name
Definition at line 37 of file class-wp-widget.php.
Referenced by GravityView_Recent_Entries_Widget\__construct(), __construct(), WP_Widget_Tag_Cloud\form(), and WP_Widget().
$number = false
Definition at line 64 of file class-wp-widget.php.
Referenced by _register(), _register_one(), _set(), display_callback(), WP_Widget_RSS\form(), WP_Widget_Recent_Posts\form(), WP_Widget_Recent_Comments\form(), Twenty_Eleven_Ephemera_Widget\form(), Twenty_Fourteen_Ephemera_Widget\form(), update_callback(), WP_Widget_Recent_Posts\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), and WP_Widget_Recent_Comments\widget().
$updated = false
Definition at line 85 of file class-wp-widget.php.
$widget_options
Definition at line 46 of file class-wp-widget.php.
Referenced by GravityView_Recent_Entries_Widget\__construct(), __construct(), and WP_Widget().
The documentation for this class was generated from the following file:
class-wp-widget.php