GravityView: WP_User_Meta_Session_Tokens Class Reference
WP_User_Meta_Session_Tokens Class Reference
Meta-based user sessions token manager.
Static Public Member Functions
static drop_sessions ()
Destroy all session tokens for all users.
Static Public Member Functions inherited from WP_Session_Tokens
static destroy_all_for_all_users ()
Destroy all session tokens for all users.
static drop_sessions ()
This static method should destroy all session tokens for all users.
static get_instance ($user_id)
Get a session token manager instance for a user.
Protected Member Functions
destroy_all_sessions ()
Destroy all session tokens for a user.
destroy_other_sessions ($verifier)
Destroy all session tokens for a user, except a single session passed.
get_session ($verifier)
Retrieve a session by its verifier (token hash).
get_sessions ()
Get all sessions of a user.
prepare_session ($session)
Converts an expiration to an array of session information.
update_session ($verifier, $session=null)
Update a session by its verifier.
update_sessions ($sessions)
Update a user's sessions in the usermeta table.
Protected Member Functions inherited from WP_Session_Tokens
__construct ($user_id)
Protected constructor.
destroy_all_sessions ()
This method should destroy all sessions for a user.
destroy_other_sessions ($verifier)
This method should destroy all session tokens for this user, except a single session passed.
get_session ($verifier)
This method should look up a session by its verifier (token hash).
get_sessions ()
This method should retrieve all sessions of a user, keyed by verifier.
is_still_valid ($session)
Determine whether a session token is still valid, based on expiration.
update_session ($verifier, $session=null)
This method should update a session by its verifier.
Additional Inherited Members
Public Member Functions inherited from WP_Session_Tokens
create ($expiration)
Generate a session token and attach session information to it.
destroy ($token)
Destroy a session token.
destroy_all ()
Destroy all session tokens for a user.
destroy_others ($token_to_keep)
Destroy all session tokens for this user, except a single token, presumably the one in use.
get ($token)
Get a user's session.
get_all ()
Retrieve all sessions of a user.
update ($token, $session)
Update a session token.
verify ($token)
Validate a user's session token as authentic.
Protected Attributes inherited from WP_Session_Tokens
$user_id
Detailed Description
Meta-based user sessions token manager.
Since
4.0.0
Definition at line 316 of file session.php.
Member Function Documentation
destroy_all_sessions () protected
Destroy all session tokens for a user.
Since
4.0.0 protected
Definition at line 426 of file session.php.
References update_sessions().
destroy_other_sessions ($verifier) protected
Destroy all session tokens for a user, except a single session passed.
Since
4.0.0 protected
Parameters
string $verifier Verifier of the session to keep.
Definition at line 415 of file session.php.
References get_session(), and update_sessions().
static drop_sessions () static
Destroy all session tokens for all users.
Since
4.0.0 public
Definition at line 437 of file session.php.
References delete_metadata().
get_session ($verifier) protected
Retrieve a session by its verifier (token hash).
Since
4.0.0 protected
Parameters
string $verifier Verifier of the session to retrieve.
Returns
array|null The session, or null if it does not exist
Definition at line 360 of file session.php.
References get_sessions(), and null.
Referenced by destroy_other_sessions().
get_sessions () protected
Get all sessions of a user.
Since
4.0.0 protected
Returns
array Sessions of a user.
Definition at line 326 of file session.php.
References get_user_meta().
Referenced by get_session(), and update_session().
prepare_session ($session) protected
Converts an expiration to an array of session information.
Parameters
mixed $session Session or expiration.
Returns
array Session.
Definition at line 343 of file session.php.
update_session ($verifier, $session = null) protected
Update a session by its verifier.
Since
4.0.0 protected
Parameters
string $verifier Verifier of the session to update.
array $session Optional. Session. Omitting this argument destroys the session.
Definition at line 379 of file session.php.
References get_sessions(), and update_sessions().
update_sessions ($sessions) protected
Update a user's sessions in the usermeta table.
Since
4.0.0 protected
Parameters
array $sessions Sessions.
Definition at line 399 of file session.php.
References delete_user_meta(), and update_user_meta().
Referenced by destroy_all_sessions(), destroy_other_sessions(), and update_session().
The documentation for this class was generated from the following file:
session.php