GravityView: WP_Ajax_Response Class Reference
WP_Ajax_Response Class Reference
Public Member Functions
__construct ($args= '')
Constructor - Passes args to WP_Ajax_Response::add().
add ($args= '')
Append to XML response based on given arguments.
send ()
Display XML formatted responses.
Data Fields
$responses = array()
Detailed Description
Definition at line 8 of file class-wp-ajax-response.php.
Constructor & Destructor Documentation
__construct ($args = '')
Constructor - Passes args to WP_Ajax_Response::add().
Since
2.1.0
See also
WP_Ajax_Response::add()
Parameters
string | array $args Optional. Will be passed to add() method.
Definition at line 25 of file class-wp-ajax-response.php.
References add().
Member Function Documentation
add ($args = '')
Append to XML response based on given arguments.
The arguments that can be passed in the $args parameter are below. It is also possible to pass a WP_Error object in either the 'id' or 'data' argument. The parameter isn't actually optional, content should be given in order to send the correct response.
'what' argument is a string that is the XMLRPC response type. 'action' argument is a boolean or string that acts like a nonce. 'id' argument can be WP_Error or an integer. 'old_id' argument is false by default or an integer of the previous ID. 'position' argument is an integer or a string with -1 = top, 1 = bottom, html ID = after, -html ID = before. 'data' argument is a string with the content or message. 'supplemental' argument is an array of strings that will be children of the supplemental element.
Since
2.1.0
Parameters
string | array $args Override defaults.
Returns
string XML response.
Definition at line 53 of file class-wp-ajax-response.php.
References $action, $class, $id, $s, elseif, is_wp_error(), and wp_parse_args().
Referenced by __construct().
send ()
Display XML formatted responses.
Sets the content type header to text/xml.
Since
2.1.0
Definition at line 134 of file class-wp-ajax-response.php.
References DOING_AJAX, get_option(), and wp_die().
Field Documentation
$responses = array()
Definition at line 15 of file class-wp-ajax-response.php.
The documentation for this class was generated from the following file:
class-wp-ajax-response.php