GravityView: getid3_flac Class Reference
getid3_flac Class Reference
http://flac.sourceforge.net/format.html
Public Member Functions
Analyze ()
parseMETAdata ()
parsePICTURE ()
Parse METADATA_BLOCK_PICTURE flac structure and extract attachment External usage: audio.ogg.
Public Member Functions inherited from getid3_handler
__construct (getID3 $getid3, $call_module=null)
Analyze ()
AnalyzeString ($string)
saveAttachment ($name, $offset, $length, $image_mime=null)
setStringMode ($string)
Static Public Member Functions
static applicationIDLookup ($applicationid)
static metaBlockTypeLookup ($blocktype)
static pictureTypeLookup ($type_id)
Data Fields
const syncword = 'fLaC'
Private Member Functions
parseAPPLICATION ($BlockData)
parseCUESHEET ($BlockData)
parseSEEKTABLE ($BlockData)
parseSTREAMINFO ($BlockData)
parseVORBIS_COMMENT ($BlockData)
Additional Inherited Members
Protected Member Functions inherited from getid3_handler
error ($text)
feof ()
fread ($bytes)
fseek ($bytes, $whence=SEEK_SET)
ftell ()
isDependencyFor ($module)
notice ($text)
warning ($text)
Protected Attributes inherited from getid3_handler
$data_string = ''
$data_string_flag = false
$data_string_length = 0
$data_string_position = 0
$getid3
Detailed Description
http://flac.sourceforge.net/format.html
Definition at line 23 of file module.audio.flac.php.
Member Function Documentation
Analyze ()
Definition at line 27 of file module.audio.flac.php.
References getid3_handler\error(), getid3_handler\fread(), getid3_handler\fseek(), parseMETAdata(), and getid3_lib\PrintHexBytes().
static applicationIDLookup ($applicationid) static
Definition at line 396 of file module.audio.flac.php.
static metaBlockTypeLookup ($blocktype) static
Definition at line 383 of file module.audio.flac.php.
parseAPPLICATION ($BlockData) private
Definition at line 239 of file module.audio.flac.php.
References getid3_lib\BigEndian2Int().
Referenced by parseMETAdata().
parseCUESHEET ($BlockData) private
Definition at line 297 of file module.audio.flac.php.
References getid3_lib\BigEndian2Int().
Referenced by parseMETAdata().
parseMETAdata ()
Definition at line 44 of file module.audio.flac.php.
References $i, getID3\ATTACHMENTS_NONE, getid3_lib\BigEndian2Int(), getid3_handler\error(), getid3_handler\fread(), getid3_handler\ftell(), getid3_handler\isDependencyFor(), parseAPPLICATION(), parseCUESHEET(), parsePICTURE(), parseSEEKTABLE(), parseSTREAMINFO(), parseVORBIS_COMMENT(), str_replace, and getid3_handler\warning().
Referenced by Analyze().
parsePICTURE ()
Parse METADATA_BLOCK_PICTURE flac structure and extract attachment External usage: audio.ogg.
Definition at line 352 of file module.audio.flac.php.
References getid3_lib\BigEndian2Int(), getid3_handler\fread(), getid3_handler\ftell(), getid3_handler\saveAttachment(), and str_replace.
Referenced by parseMETAdata().
parseSEEKTABLE ($BlockData) private
Definition at line 249 of file module.audio.flac.php.
References getid3_lib\BigEndian2Int(), and getid3_lib\safe_inc().
Referenced by parseMETAdata().
parseSTREAMINFO ($BlockData) private
Definition at line 197 of file module.audio.flac.php.
References getid3_lib\BigEndian2Bin(), getid3_lib\BigEndian2Int(), getid3_lib\Bin2Dec(), getid3_handler\error(), getid3_handler\isDependencyFor(), and getid3_handler\warning().
Referenced by parseMETAdata().
parseVORBIS_COMMENT ($BlockData) private
Definition at line 278 of file module.audio.flac.php.
References getid3_handler\isDependencyFor().
Referenced by parseMETAdata().
static pictureTypeLookup ($type_id) static
Definition at line 426 of file module.audio.flac.php.
Field Documentation
const syncword = 'fLaC'
Definition at line 25 of file module.audio.flac.php.
The documentation for this class was generated from the following file:
module.audio.flac.php