GravityView: WP_Press_This Class Reference
WP_Press_This Class Reference
Press This class.
Public Member Functions
__construct ()
Constructor.
add_category ()
AJAX handler for adding a new category.
add_editor_style ($styles)
Adds another stylesheet inside TinyMCE.
categories_html ($post)
Outputs the categories HTML.
fetch_source_html ($url)
Downloads the source's HTML via server-side call for the given URL.
get_canonical_link ($data)
Gets the source page's canonical link, based on passed location and meta data.
get_embeds ($data)
Get a list of embeds with no duplicates.
get_images ($data)
Get a list of images with no duplicates.
get_source_site_name ($data)
Gets the source page's site name, based on passed meta data.
get_suggested_content ($data)
Gets the source page's suggested content, based on passed data (description, selection, etc).
get_suggested_title ($data)
Gets the source page's title, based on passed title and meta data.
html ()
Serves the app's base HTML, which in turns calls the load script.
merge_or_fetch_data ()
Handles backward-compat with the legacy version of Press This by supporting its query string params.
post_formats_html ($post)
Outputs the post format selection HTML.
save_post ()
AJAX handler for saving the post as draft or published.
side_load_images ($post_id, $content= '')
Get the source's images and save them locally, for posterity, unless we can't.
site_settings ()
App and site settings data, including i18n strings for the client-side.
source_data_fetch_fallback ($url, $data=array())
Fetches and parses _meta, _images, and _links data from the source.
tags_html ($post)
Outputs the tags HTML.
Data Fields
$version = 8
Private Member Functions
_limit_array ($value)
Utility method to limit an array to 50 values.
_limit_embed ($src)
Limit embed source URLs to specific providers.
_limit_img ($src)
Utility method to limit image source URLs.
_limit_string ($value)
Utility method to limit the length of a given string to 5,000 characters.
_limit_url ($url)
Utility method to limit a given URL to 2,048 characters.
_process_meta_entry ($meta_name, $meta_value, $data)
Process a meta data entry from the source.
Private Attributes
$domain = ''
$embeds = array()
$images = array()
Detailed Description
Press This class.
Since
4.2.0
Definition at line 15 of file class-wp-press-this.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Since
4.2.0 public
Definition at line 32 of file class-wp-press-this.php.
Member Function Documentation
_limit_array ($value) private
Utility method to limit an array to 50 values.
Since
4.2.0
Parameters
array $value Array to limit.
Returns
array Original array if fewer than 50 values, limited array, empty array otherwise.
Definition at line 311 of file class-wp-press-this.php.
References $value.
Referenced by merge_or_fetch_data(), and source_data_fetch_fallback().
_limit_embed ($src) private
Limit embed source URLs to specific providers.
Not all core oEmbed providers are supported. Supported providers include YouTube, Vimeo, Vine, Daily Motion, SoundCloud, and Twitter.
Since
4.2.0
Parameters
string $src Embed source URL.
Returns
string If not from a supported provider, an empty string. Otherwise, a reformattd embed URL.
Definition at line 449 of file class-wp-press-this.php.
References _limit_url(), _wp_oembed_get_object(), ABSPATH, and WPINC.
Referenced by _process_meta_entry(), get_embeds(), get_suggested_content(), merge_or_fetch_data(), and source_data_fetch_fallback().
_limit_img ($src) private
Utility method to limit image source URLs.
Excluded URLs include share-this type buttons, loaders, spinners, spacers, WordPress interface images, tiny buttons or thumbs, mathtag.com or quantserve.com images, or the WordPress.com stats gif.
Since
4.2.0
Parameters
string $src Image source URL.
Returns
string If not matched an excluded URL type, the original URL, empty string otherwise.
Definition at line 402 of file class-wp-press-this.php.
References _limit_url().
Referenced by _process_meta_entry(), merge_or_fetch_data(), and source_data_fetch_fallback().
_limit_string ($value) private
Utility method to limit the length of a given string to 5,000 characters.
Since
4.2.0
Parameters
string $value String to limit.
Returns
bool|int|string If boolean or integer, that value. If a string, the original value if fewer than 5,000 characters, a truncated version, otherwise an empty string.
Definition at line 334 of file class-wp-press-this.php.
References $value, and sanitize_text_field().
Referenced by merge_or_fetch_data(), and source_data_fetch_fallback().
_limit_url ($url) private
Utility method to limit a given URL to 2,048 characters.
Since
4.2.0
Parameters
string $url URL to check for length and validity.
Returns
string Escaped URL if of valid length (< 2048) and makeup. Empty string otherwise.
Definition at line 362 of file class-wp-press-this.php.
References $url, and esc_url_raw().
Referenced by _limit_embed(), _limit_img(), merge_or_fetch_data(), and source_data_fetch_fallback().
_process_meta_entry ($meta_name, $meta_value, $data) private
Process a meta data entry from the source.
Since
4.2.0
Parameters
string $meta_name Meta key name.
mixed $meta_value Meta value.
array $data Associative array of source data.
Returns
array Processed data array.
Definition at line 493 of file class-wp-press-this.php.
References _limit_embed(), and _limit_img().
Referenced by merge_or_fetch_data(), and source_data_fetch_fallback().
add_category ()
AJAX handler for adding a new category.
Since
4.2.0 public
Definition at line 186 of file class-wp-press-this.php.
References __, current_user_can(), elseif, get_category(), get_taxonomy(), is_wp_error(), sanitize_title(), term_exists(), wp_insert_term(), wp_send_json_error(), and wp_send_json_success().
add_editor_style ($styles)
Adds another stylesheet inside TinyMCE.
Since
4.2.0 public
Parameters
string $styles URL to editor stylesheet.
Returns
string Possibly modified stylesheets list.
Definition at line 776 of file class-wp-press-this.php.
References $styles, _x, add_query_arg(), admin_url(), elseif, is_rtl(), and str_replace.
categories_html ($post)
Outputs the categories HTML.
Since
4.2.0 public
Parameters
WP_Post $post Post object.
Definition at line 874 of file class-wp-press-this.php.
References $post, _e, current_user_can(), get_taxonomy(), input, label, placeholder, wp_dropdown_categories(), and wp_terms_checklist().
Referenced by html().
fetch_source_html ($url)
Downloads the source's HTML via server-side call for the given URL.
Since
4.2.0 public
Parameters
string $url URL to scan.
Returns
string Source's HTML sanitized markup
Definition at line 258 of file class-wp-press-this.php.
References $url, $wp_version, __, get_bloginfo(), is_wp_error(), wp_kses(), wp_remote_retrieve_body(), and wp_safe_remote_get().
Referenced by source_data_fetch_fallback().
get_canonical_link ($data)
Gets the source page's canonical link, based on passed location and meta data.
Since
4.2.0 public
Parameters
array $data The site's data.
Returns
string Discovered canonical URL, or empty
Definition at line 1045 of file class-wp-press-this.php.
References $link, and elseif.
Referenced by get_suggested_content().
get_embeds ($data)
Get a list of embeds with no duplicates.
Since
4.2.0 public
Parameters
array $data The site's data.
Returns
array Embeds selected to be available.
Definition at line 978 of file class-wp-press-this.php.
References _limit_embed().
Referenced by html().
get_images ($data)
Get a list of images with no duplicates.
Since
4.2.0 public
Parameters
array $data The site's data.
Returns
array
Definition at line 1011 of file class-wp-press-this.php.
Referenced by html().
get_source_site_name ($data)
Gets the source page's site name, based on passed meta data.
Since
4.2.0 public
Parameters
array $data The site's data.
Returns
string Discovered site name, or empty
Definition at line 1076 of file class-wp-press-this.php.
References $name.
Referenced by get_suggested_content().
get_suggested_content ($data)
Gets the source page's suggested content, based on passed data (description, selection, etc).
Features a blockquoted excerpt, as well as content attribution, if any.
Since
4.2.0 public
Parameters
array $data The site's data.
Returns
string Discovered content, or empty
Filter the default HTML for the Press This editor.
Since
4.2.0
Parameters
array $default_html Associative array with two keys: 'quote' where %1$s is replaced with the site description or the selected content, and 'link' there %1$s is link href, %2$s is link text.
Definition at line 1128 of file class-wp-press-this.php.
References $content, $text, $title, $url, _limit_embed(), _x, apply_filters(), get_canonical_link(), get_source_site_name(), and get_suggested_title().
Referenced by html().
get_suggested_title ($data)
Gets the source page's title, based on passed title and meta data.
Since
4.2.0 public
Parameters
array $data The site's data.
Returns
string Discovered page title, or empty
Definition at line 1099 of file class-wp-press-this.php.
References $title, and elseif.
Referenced by get_suggested_content(), and html().
html ()
Serves the app's base HTML, which in turns calls the load script.
Since
4.2.0 public
WP_Locale $wp_locale string $wp_version bool $is_IE
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This filter is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-footer.php
This action is documented in wp-admin/admin-footer.php
This action is documented in wp-admin/admin-footer.php
Definition at line 1209 of file class-wp-press-this.php.
References $admin_body_class, $admin_body_classes, $embeds, $GLOBALS, $images, $post, $post_ID, $post_title, $wp_locale, $wp_version, __, _e, _ex(), add_filter(), admin_url(), apply_filters(), bloginfo(), categories_html(), current_theme_supports(), current_user_can(), do_action(), endif, esc_html, esc_html_e, get_default_post_to_edit(), get_embeds(), get_images(), get_locale(), get_option(), get_post_format(), get_post_format_string(), get_suggested_content(), get_suggested_title(), get_user_option(), input, is_rtl(), label, language_attributes(), li, merge_or_fetch_data(), name, placeholder, post_formats_html(), post_type_supports(), remove_editor_styles(), role, sanitize_html_class(), site_settings(), str_replace, tags_html(), wp_editor(), wp_enqueue_media(), wp_enqueue_script(), wp_enqueue_style(), wp_json_encode(), and wp_nonce_field().
merge_or_fetch_data ()
Handles backward-compat with the legacy version of Press This by supporting its query string params.
Since
4.2.0 public
Returns
array
Filter whether to enable in-source media discovery in Press This.
Since
4.2.0
Parameters
bool $enable Whether to enable media discovery.
Filter the Press This data array.
Since
4.2.0
Parameters
array $data Press This Data array.
Definition at line 653 of file class-wp-press-this.php.
References $value, _limit_array(), _limit_embed(), _limit_img(), _limit_string(), _limit_url(), _process_meta_entry(), apply_filters(), elseif, source_data_fetch_fallback(), and wp_unslash().
Referenced by html().
post_formats_html ($post)
Outputs the post format selection HTML.
Since
4.2.0 public
Parameters
WP_Post $post Post object.
Definition at line 826 of file class-wp-press-this.php.
References $format, $post, $post_formats, _e, checked(), current_theme_supports(), esc_attr(), esc_html, get_post_format(), get_post_format_string(), get_theme_support(), input, label, name, and post_type_supports().
Referenced by html().
save_post ()
AJAX handler for saving the post as draft or published.
Since
4.2.0 public
Filter the URL to redirect to when Press This saves.
Since
4.2.0
Parameters
string $url Redirect URL. If $status is 'publish', this will be the post permalink. Otherwise, the default is false resulting in no redirect.
int $post_id Post ID.
string $status Post status.
Definition at line 104 of file class-wp-press-this.php.
References $post, $post_id, $redirect, $updated, __, apply_filters(), current_theme_supports(), current_user_can(), elseif, get_edit_post_link(), get_post_permalink(), get_post_status(), is_wp_error(), sanitize_text_field(), set_post_format(), side_load_images(), wp_send_json_error(), wp_send_json_success(), and wp_update_post().
side_load_images ($post_id, $content = '')
Get the source's images and save them locally, for posterity, unless we can't.
Since
4.2.0 public
Parameters
int $post_id Post ID.
string $content Optional. Current expected markup for Press This. Expects slashed. Default empty.
Returns
string New markup with old image URLs replaced with the local attachment ones if swapped.
Definition at line 65 of file class-wp-press-this.php.
References $content, $image, $post_id, current_user_can(), is_wp_error(), media_sideload_image(), null, str_replace, wp_slash(), and wp_unslash().
Referenced by save_post().
site_settings ()
App and site settings data, including i18n strings for the client-side.
Since
4.2.0 public
Returns
array Site settings.
Filter whether or not Press This should redirect the user in the parent window upon save.
Since
4.2.0
Parameters
bool $redirect Whether to redirect in parent window or not. Default false.
Definition at line 42 of file class-wp-press-this.php.
References apply_filters().
Referenced by html().
source_data_fetch_fallback ($url, $data = array())
Fetches and parses _meta, _images, and _links data from the source.
Since
4.2.0 public
Parameters
string $url URL to scan.
array $data Optional. Existing data array if you have one. Default empty array.
Returns
array New data array.
Definition at line 545 of file class-wp-press-this.php.
References $url, $value, _limit_array(), _limit_embed(), _limit_img(), _limit_string(), _limit_url(), _process_meta_entry(), fetch_source_html(), and is_wp_error().
Referenced by merge_or_fetch_data().
tags_html ($post)
Outputs the tags HTML.
Since
4.2.0 public
Parameters
WP_Post $post Post object.
Definition at line 926 of file class-wp-press-this.php.
References $post, _e, current_user_can(), get_taxonomy(), get_terms_to_edit(), input, is_wp_error(), label, name, and size.
Referenced by html().
Field Documentation
$domain = '' private
Definition at line 24 of file class-wp-press-this.php.
$embeds = array() private
Definition at line 22 of file class-wp-press-this.php.
Referenced by html().
$images = array() private
Definition at line 20 of file class-wp-press-this.php.
Referenced by html().
$version = 8
Definition at line 18 of file class-wp-press-this.php.
The documentation for this class was generated from the following file:
class-wp-press-this.php