GravityView: WP_Term Class Reference
WP_Term Class Reference
Core class used to implement the WP_Term object.
Public Member Functions
__construct ($term)
Constructor.
__get ($key)
Getter.
filter ($filter)
Sanitizes term fields, according to the filter type provided.
to_array ()
Converts an object to array.
Static Public Member Functions
static get_instance ($term_id, $taxonomy=null)
Retrieve WP_Term instance.
Data Fields
$count = 0
$description = ''
$filter = 'raw'
$name = ''
$parent = 0
$slug = ''
$taxonomy = ''
$term_group = ''
$term_id
$term_taxonomy_id = 0
Detailed Description
Core class used to implement the WP_Term object.
Since
4.4.0
Definition at line 15 of file class-wp-term.php.
Constructor & Destructor Documentation
__construct ($term)
Constructor.
Since
4.4.0 public
Parameters
WP_Term | object $term Term object.
Definition at line 204 of file class-wp-term.php.
References $value.
Member Function Documentation
__get ($key)
Getter.
Since
4.4.0 public
Parameters
string $key Property to get.
Returns
mixed Property value.
Definition at line 243 of file class-wp-term.php.
References $columns, null, and sanitize_term().
filter ($filter)
Sanitizes term fields, according to the filter type provided.
Since
4.4.0 public
Parameters
string $filter Filter context. Accepts 'edit', 'db', 'display', 'attribute', 'js', 'raw'.
Definition at line 218 of file class-wp-term.php.
References $filter, and sanitize_term().
static get_instance ($term_id, $taxonomy = null) static
Retrieve WP_Term instance.
Since
4.4.0 public
wpdb $wpdb WordPress database abstraction object.
Parameters
int $term_id Term ID.
string $taxonomy Optional. Limit matched terms to those matching $taxonomy. Only used for disambiguating potentially shared terms.
Returns
WP_Term|WP_Error|false Term object, if found. WP_Error if $term_id is shared between taxonomies and there's insufficient data to distinguish which term is intended. False for other failures.
Definition at line 125 of file class-wp-term.php.
References $taxonomy, $term_id, $wpdb, __, elseif, sanitize_term(), taxonomy_exists(), wp_cache_add(), and wp_cache_get().
Referenced by get_term().
to_array ()
Converts an object to array.
Since
4.4.0 public
Returns
array Object as array.
Definition at line 230 of file class-wp-term.php.
Field Documentation
$count = 0
Definition at line 96 of file class-wp-term.php.
$description = ''
Definition at line 78 of file class-wp-term.php.
$filter = 'raw'
Definition at line 107 of file class-wp-term.php.
Referenced by filter().
$name = ''
Definition at line 33 of file class-wp-term.php.
$parent = 0
Definition at line 87 of file class-wp-term.php.
$slug = ''
Definition at line 42 of file class-wp-term.php.
$taxonomy = ''
Definition at line 69 of file class-wp-term.php.
Referenced by get_instance().
$term_group = ''
Definition at line 51 of file class-wp-term.php.
$term_id
Definition at line 24 of file class-wp-term.php.
Referenced by get_instance().
$term_taxonomy_id = 0
Definition at line 60 of file class-wp-term.php.
The documentation for this class was generated from the following file:
class-wp-term.php