GravityView: Theme_Upgrader Class Reference
Theme_Upgrader Class Reference
Core class used for upgrading/installing themes.
Public Member Functions
bulk_upgrade ($themes, $args=array())
Upgrade several themes at once.
check_package ($source)
Check that the package source contains a valid theme.
check_parent_theme_filter ($install_result, $hook_extra, $child_result)
Check if a child theme is being installed and we need to install its parent.
current_after ($return, $theme)
Turn off maintenance mode after upgrading the current theme.
current_before ($return, $theme)
Turn on maintenance mode before attempting to upgrade the current theme.
delete_old_theme ($removed, $local_destination, $remote_destination, $theme)
Delete the old theme during an upgrade.
hide_activate_preview_actions ($actions)
Don't display the activate and preview actions to the user.
install ($package, $args=array())
Install a theme package.
install_strings ()
Initialize the install strings.
theme_info ($theme=null)
Get the WP_Theme object for a theme.
upgrade ($theme, $args=array())
Upgrade a theme.
upgrade_strings ()
Initialize the upgrade strings.
Public Member Functions inherited from WP_Upgrader
__construct ($skin=null)
Construct the upgrader with a skin.
clear_destination ($remote_destination)
Clears the directory where this item is going to be installed into.
download_package ($package)
Download a package.
fs_connect ($directories=array(), $allow_relaxed_file_ownership=false)
Connect to the filesystem.
generic_strings ()
Add the generic strings to WP_Upgrader::$strings.
init ()
Initialize the upgrader.
install_package ($args=array())
Install a package.
maintenance_mode ($enable=false)
Toggle maintenance mode for the site.
run ($options)
Run an upgrade/install.
unpack_package ($package, $delete_package=true)
Unpack a compressed package file.
Data Fields
$bulk = false
Whether multiple themes are being upgraded/installed in bulk.
$result
Result of the theme upgrade offer.
Data Fields inherited from WP_Upgrader
$result = array()
$skin = null
The upgrader skin being used.
$strings = array()
The error/notification strings used to update the user on the progress.
$update_count = 0
The total number of updates being performed.
$update_current = 0
Detailed Description
Core class used for upgrading/installing themes.
It is designed to upgrade/install themes from a local zip, remote zip URL, or uploaded zip file.
Since
2.8.0
See also
WP_Upgrader
Definition at line 1233 of file class-wp-upgrader.php.
Member Function Documentation
bulk_upgrade ($themes, $args = array())
Upgrade several themes at once.
Since
3.0.0
3.7.0 The $args parameter was added, making clearing the update cache optional. public
Parameters
array $themes The theme slugs.
array $args { Optional. Other arguments for upgrading several themes at once. Default empty array.
bool $clear_update_cache Whether to clear the update cache if successful. Default true. }
Returns
array[]|false An array of results, or false if unable to connect to the filesystem.
This action is documented in wp-admin/includes/class-wp-upgrader.php
Definition at line 1525 of file class-wp-upgrader.php.
References $result, $theme, add_filter(), do_action(), WP_Upgrader\fs_connect(), get_site_transient(), get_stylesheet(), get_template(), get_theme_root(), WP_Upgrader\init(), is_multisite(), WP_Upgrader\maintenance_mode(), remove_filter(), WP_Upgrader\run(), theme_info(), upgrade_strings(), wp_clean_themes_cache(), WP_CONTENT_DIR, and wp_parse_args().
check_package ($source)
Check that the package source contains a valid theme.
Hooked to the {
See also
'upgrader_source_selection'} filter by {
Theme_Upgrader::install()}. It will return an error if the theme doesn't have style.css or index.php files.
Since
3.3.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $source The full path to the package source.
Returns
string|WP_Error The source or a WP_Error.
Definition at line 1642 of file class-wp-upgrader.php.
References __, get_file_data(), is_wp_error(), str_replace, trailingslashit(), and WP_CONTENT_DIR.
check_parent_theme_filter ($install_result, $hook_extra, $child_result)
Check if a child theme is being installed and we need to install its parent.
Hooked to the {
See also
'upgrader_post_install'} filter by {
Theme_Upgrader::install()}.
Since
3.4.0 public
Parameters
bool $install_result
array $hook_extra
array $child_result
Returns
type
Definition at line 1310 of file class-wp-upgrader.php.
References add_filter(), get_theme_root(), is_wp_error(), remove_filter(), WP_Upgrader\run(), theme_info(), and themes_api().
current_after ($return, $theme)
Turn off maintenance mode after upgrading the current theme.
Hooked to the {
See also
'upgrader_post_install'} filter by {
Theme_Upgrader::upgrade()} and {
Theme_Upgrader::bulk_upgrade()}.
Since
2.8.0 public
Parameters
bool | WP_Error $return
array $theme
Returns
bool|WP_Error
Definition at line 1728 of file class-wp-upgrader.php.
References $theme, get_stylesheet(), is_wp_error(), WP_Upgrader\maintenance_mode(), switch_theme(), and wp_clean_themes_cache().
current_before ($return, $theme)
Turn on maintenance mode before attempting to upgrade the current theme.
Hooked to the {
See also
'upgrader_pre_install'} filter by {
Theme_Upgrader::upgrade()} and {
Theme_Upgrader::bulk_upgrade()}.
Since
2.8.0 public
Parameters
bool | WP_Error $return
array $theme
Returns
bool|WP_Error
Definition at line 1700 of file class-wp-upgrader.php.
References $theme, get_stylesheet(), is_wp_error(), and WP_Upgrader\maintenance_mode().
delete_old_theme ($removed, $local_destination, $remote_destination, $theme)
Delete the old theme during an upgrade.
Hooked to the {
See also
'upgrader_clear_destination'} filter by {
Theme_Upgrader::upgrade()} and {
Theme_Upgrader::bulk_upgrade()}.
Since
2.8.0 public
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
bool $removed
string $local_destination
string $remote_destination
array $theme
Returns
bool
Definition at line 1767 of file class-wp-upgrader.php.
References $theme, is_wp_error(), and trailingslashit().
hide_activate_preview_actions ($actions)
Don't display the activate and preview actions to the user.
Hooked to the {
See also
'install_theme_complete_actions'} filter by {
Theme_Upgrader::check_parent_theme_filter()} when installing a child theme and installing the parent theme fails.
Since
3.4.0 public
Parameters
array $actions Preview actions.
Returns
array
Definition at line 1382 of file class-wp-upgrader.php.
install ($package, $args = array())
Install a theme package.
Since
2.8.0
3.7.0 The $args parameter was added, making clearing the update cache optional. public
Parameters
string $package The full local path or URI of the package.
array $args { Optional. Other arguments for installing a theme package. Default empty array.
bool $clear_update_cache Whether to clear the updates cache if successful. Default true. }
Returns
bool|WP_Error True if the install was successful, false or a {
See also
WP_Error} object otherwise.
Definition at line 1404 of file class-wp-upgrader.php.
References $result, add_action(), add_filter(), get_theme_root(), WP_Upgrader\init(), install_strings(), is_wp_error(), remove_action(), remove_filter(), WP_Upgrader\run(), wp_clean_themes_cache(), and wp_parse_args().
install_strings ()
Initialize the install strings.
Since
2.8.0 public
Definition at line 1277 of file class-wp-upgrader.php.
References __.
Referenced by install().
theme_info ($theme = null)
Get the WP_Theme object for a theme.
Since
2.8.0
3.0.0 The $theme argument was added. public
Parameters
string $theme The directory name of the theme. This is optional, and if not supplied, the directory name from the last result will be used.
Returns
WP_Theme|false The theme's info object, or false $theme is not supplied and the last result isn't set.
Definition at line 1798 of file class-wp-upgrader.php.
References $theme, and wp_get_theme().
Referenced by bulk_upgrade(), and check_parent_theme_filter().
upgrade ($theme, $args = array())
Upgrade a theme.
Since
2.8.0
3.7.0 The $args parameter was added, making clearing the update cache optional. public
Parameters
string $theme The theme slug.
array $args { Optional. Other arguments for upgrading a theme. Default empty array.
bool $clear_update_cache Whether to clear the update cache if successful. Default true. }
Returns
bool|WP_Error True if the upgrade was successful, false or a {
See also
WP_Error} object otherwise.
Definition at line 1459 of file class-wp-upgrader.php.
References $result, $theme, add_filter(), get_site_transient(), get_theme_root(), WP_Upgrader\init(), is_wp_error(), remove_filter(), WP_Upgrader\run(), upgrade_strings(), wp_clean_themes_cache(), and wp_parse_args().
upgrade_strings ()
Initialize the upgrade strings.
Since
2.8.0 public
Definition at line 1260 of file class-wp-upgrader.php.
References __.
Referenced by bulk_upgrade(), and upgrade().
Field Documentation
bool $bulk = false
Whether multiple themes are being upgraded/installed in bulk.
Since
2.9.0 public
Definition at line 1252 of file class-wp-upgrader.php.
array WP_Error $result
Result of the theme upgrade offer.
Since
2.8.0 public
See also
WP_Upgrader::$result
Definition at line 1243 of file class-wp-upgrader.php.
Referenced by bulk_upgrade(), install(), and upgrade().
The documentation for this class was generated from the following file:
class-wp-upgrader.php