GravityView: WP_Filesystem_SSH2 Class Reference
WP_Filesystem_SSH2 Class Reference
Public Member Functions
__construct ($opt= '')
public
atime ($file)
public
chdir ($dir)
public
chgrp ($file, $group, $recursive=false)
public
chmod ($file, $mode=false, $recursive=false)
public
chown ($file, $owner, $recursive=false)
Change the ownership of a file / folder.
connect ()
public
copy ($source, $destination, $overwrite=false, $mode=false)
public
cwd ()
public
delete ($file, $recursive=false, $type=false)
public
dirlist ($path, $include_hidden=true, $recursive=false)
public
exists ($file)
public
get_contents ($file)
public
get_contents_array ($file)
public
getchmod ($file)
public
group ($file)
public
is_dir ($path)
public
is_file ($file)
public
is_readable ($file)
public
is_writable ($file)
public
mkdir ($path, $chmod=false, $chown=false, $chgrp=false)
public
move ($source, $destination, $overwrite=false)
public
mtime ($file)
public
owner ($file)
public
put_contents ($file, $contents, $mode=false)
public
rmdir ($path, $recursive=false)
public
run_command ($command, $returnbool=false)
public
sftp_path ($path)
Gets the ssh2.sftp PHP stream wrapper path to open for the given file.
size ($file)
public
touch ($file, $time=0, $atime=0)
public
Public Member Functions inherited from WP_Filesystem_Base
abspath ()
Return the path on the remote filesystem of ABSPATH.
atime ($file)
Gets the file's last access time.
chdir ($dir)
Change current directory.
chgrp ($file, $group, $recursive=false)
Change the file group.
chmod ($file, $mode=false, $recursive=false)
Change filesystem permissions.
chown ($file, $owner, $recursive=false)
Change the ownership of a file / folder.
connect ()
Connect filesystem.
copy ($source, $destination, $overwrite=false, $mode=false)
Copy a file.
cwd ()
Get the current working directory.
delete ($file, $recursive=false, $type=false)
Delete a file or directory.
dirlist ($path, $include_hidden=true, $recursive=false)
Get details for files in a directory or a specific file.
exists ($file)
Check if a file or directory exists.
find_base_dir ($base= '.', $echo=false)
Locate a folder on the remote filesystem.
find_folder ($folder)
Locate a folder on the remote filesystem.
get_base_dir ($base= '.', $echo=false)
Locate a folder on the remote filesystem.
get_contents ($file)
Read entire file into a string.
get_contents_array ($file)
Read entire file into an array.
getchmod ($file)
Gets the permissions of the specified file or filepath in their octal format.
gethchmod ($file)
Return the *nix-style file permissions for a file.
getnumchmodfromh ($mode)
Convert *nix-style file permissions to a octal number.
group ($file)
Get the file's group.
is_binary ($text)
Determine if the string provided contains binary characters.
is_dir ($path)
Check if resource is a directory.
is_file ($file)
Check if resource is a file.
is_readable ($file)
Check if a file is readable.
is_writable ($file)
Check if a file or directory is writable.
mkdir ($path, $chmod=false, $chown=false, $chgrp=false)
Create a directory.
move ($source, $destination, $overwrite=false)
Move a file.
mtime ($file)
Gets the file modification time.
owner ($file)
Get the file owner.
put_contents ($file, $contents, $mode=false)
Write a string to a file.
rmdir ($path, $recursive=false)
Delete a directory.
search_for_folder ($folder, $base= '.', $loop=false)
Locate a folder on the remote filesystem.
size ($file)
Gets the file size (in bytes).
touch ($file, $time=0, $atime=0)
Set the access and modification times of a file.
wp_content_dir ()
Return the path on the remote filesystem of WP_CONTENT_DIR.
wp_lang_dir ()
Return the path on the remote filesystem of WP_LANG_DIR.
wp_plugins_dir ()
Return the path on the remote filesystem of WP_PLUGIN_DIR.
wp_themes_dir ($theme=false)
Return the path on the remote filesystem of the Themes Directory.
Data Fields
$keys = false
$link = false
public
$sftp_link
Data Fields inherited from WP_Filesystem_Base
$cache = array()
$errors = null
public
$method = ''
$options = array()
public
$verbose = false
Detailed Description
Definition at line 36 of file class-wp-filesystem-ssh2.php.
Constructor & Destructor Documentation
__construct ($opt = '')
public
Parameters
array $opt
Definition at line 55 of file class-wp-filesystem-ssh2.php.
References __, and elseif.
Member Function Documentation
atime ($file)
public
Parameters
string $file
Returns
int
Definition at line 490 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
chdir ($dir)
public
Parameters
string $dir
Returns
bool|string
Definition at line 274 of file class-wp-filesystem-ssh2.php.
References $dir, and run_command().
chgrp ($file, $group, $recursive = false)
public
Parameters
string $file
string $group
bool $recursive
Returns
bool
Definition at line 287 of file class-wp-filesystem-ssh2.php.
References $file, exists(), is_dir(), and run_command().
Referenced by mkdir().
chmod ($file, $mode = false, $recursive = false)
public
Parameters
string $file
int $mode
bool $recursive
Returns
bool|string
Definition at line 303 of file class-wp-filesystem-ssh2.php.
References $file, $mode, elseif, exists(), is_dir(), is_file(), and run_command().
Referenced by put_contents().
chown ($file, $owner, $recursive = false)
Change the ownership of a file / folder.
public
Parameters
string $file Path to the file.
string | int $owner A user name or number.
bool $recursive Optional. If set True changes file owner recursivly. Defaults to False.
Returns
bool|string Returns true on success or false on failure.
Definition at line 331 of file class-wp-filesystem-ssh2.php.
References $file, exists(), is_dir(), and run_command().
Referenced by mkdir().
connect ()
public
Returns
bool
Definition at line 109 of file class-wp-filesystem-ssh2.php.
References __.
copy ($source, $destination, $overwrite = false, $mode = false)
public
Parameters
string $source
string $destination
bool $overwrite
int | bool $mode
Returns
bool
Definition at line 390 of file class-wp-filesystem-ssh2.php.
References $content, $mode, exists(), get_contents(), and put_contents().
cwd ()
public
Returns
bool
Definition at line 260 of file class-wp-filesystem-ssh2.php.
References trailingslashit().
delete ($file, $recursive = false, $type = false)
public
Parameters
string $file
bool $recursive
string | bool $type
Returns
bool
Definition at line 419 of file class-wp-filesystem-ssh2.php.
References $file, dirlist(), and is_file().
dirlist ($path, $include_hidden = true, $recursive = false)
public
Parameters
string $path
bool $include_hidden
bool $recursive
Returns
bool|array
Definition at line 569 of file class-wp-filesystem-ssh2.php.
References $dir, $path, date, WP_Filesystem_Base\gethchmod(), WP_Filesystem_Base\getnumchmodfromh(), group(), is_dir(), is_file(), mtime(), owner(), sftp_path(), and size().
Referenced by delete().
exists ($file)
public
Parameters
string $file
Returns
bool
Definition at line 439 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
Referenced by chgrp(), chmod(), chown(), and copy().
get_contents ($file)
public
Parameters
string $file
Returns
string|false
Definition at line 222 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
Referenced by copy().
get_contents_array ($file)
public
Parameters
string $file
Returns
array
Definition at line 232 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
getchmod ($file)
public
Parameters
string $file
Returns
string
Definition at line 361 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
group ($file)
public
Parameters
string $file
Returns
string|false
Definition at line 371 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
Referenced by dirlist().
is_dir ($path)
public
Parameters
string $path
Returns
bool
Definition at line 459 of file class-wp-filesystem-ssh2.php.
References $path, and sftp_path().
Referenced by chgrp(), chmod(), chown(), and dirlist().
is_file ($file)
public
Parameters
string $file
Returns
bool
Definition at line 449 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
Referenced by chmod(), delete(), and dirlist().
is_readable ($file)
public
Parameters
string $file
Returns
bool
Definition at line 469 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
is_writable ($file)
public
Parameters
string $file
Returns
bool
Definition at line 479 of file class-wp-filesystem-ssh2.php.
mkdir ($path, $chmod = false, $chown = false, $chgrp = false)
public
Parameters
string $path
mixed $chmod
mixed $chown
mixed $chgrp
Returns
bool
Definition at line 534 of file class-wp-filesystem-ssh2.php.
References $path, chgrp(), chown(), and untrailingslashit().
move ($source, $destination, $overwrite = false)
public
Parameters
string $source
string $destination
bool $overwrite
Returns
bool
Definition at line 407 of file class-wp-filesystem-ssh2.php.
mtime ($file)
public
Parameters
string $file
Returns
int
Definition at line 500 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
Referenced by dirlist().
owner ($file)
public
Parameters
string $file
Returns
string|false
Definition at line 345 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
Referenced by dirlist().
put_contents ($file, $contents, $mode = false)
public
Parameters
string $file
string $contents
bool | int $mode
Returns
bool
Definition at line 244 of file class-wp-filesystem-ssh2.php.
References $file, $mode, chmod(), and sftp_path().
Referenced by copy().
rmdir ($path, $recursive = false)
public
Parameters
string $path
bool $recursive
Returns
bool
Definition at line 557 of file class-wp-filesystem-ssh2.php.
References $path.
run_command ($command, $returnbool = false)
public
Parameters
string $command
bool $returnbool
Returns
bool|string
Definition at line 191 of file class-wp-filesystem-ssh2.php.
References __.
Referenced by chdir(), chgrp(), chmod(), and chown().
sftp_path ($path)
Gets the ssh2.sftp PHP stream wrapper path to open for the given file.
This method also works around a PHP bug where the root directory (/) cannot be opened by PHP functions, causing a false failure. In order to work around this, the path is converted to /./ which is semantically the same as / See https://bugs.php.net/bug.php?id=64169 for more details.
public
Since
4.4.0
Parameters
string $path The File/Directory path on the remote server to return
Returns
string The ssh2.sftp:// wrapped path to use.
Definition at line 177 of file class-wp-filesystem-ssh2.php.
References $path.
Referenced by atime(), dirlist(), exists(), get_contents(), get_contents_array(), getchmod(), group(), is_dir(), is_file(), is_readable(), mtime(), owner(), put_contents(), and size().
size ($file)
public
Parameters
string $file
Returns
int
Definition at line 510 of file class-wp-filesystem-ssh2.php.
References $file, and sftp_path().
Referenced by dirlist().
touch ($file, $time = 0, $atime = 0)
public
Parameters
string $file
int $time
int $atime
Definition at line 521 of file class-wp-filesystem-ssh2.php.
Field Documentation
$keys = false
Definition at line 48 of file class-wp-filesystem-ssh2.php.
$link = false
public
Definition at line 41 of file class-wp-filesystem-ssh2.php.
$sftp_link
Definition at line 47 of file class-wp-filesystem-ssh2.php.
The documentation for this class was generated from the following file:
class-wp-filesystem-ssh2.php