GravityView: comment-template.php File Reference
comment-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
cancel_comment_reply_link ($text= '')
Display HTML content for cancel comment reply link.
comment_author ($comment_ID=0)
Displays the author of the current comment.
comment_author_email ($comment_ID=0)
Display the email of the author of the current global $comment.
comment_author_email_link ($linktext= '', $before= '', $after= '')
Display the html email link to the author of the current comment.
comment_author_IP ($comment_ID=0)
Display the IP address of the author of the current comment.
comment_author_link ($comment_ID=0)
Display the html link to the url of the author of the current comment.
comment_author_url ($comment_ID=0)
Display the url of the author of the current comment.
comment_author_url_link ($linktext= '', $before= '', $after= '')
Displays the HTML link of the url of the author of the current comment.
comment_class ($class= '', $comment=null, $post_id=null, $echo=true)
Generates semantic classes for each comment element.
comment_date ($d= '', $comment_ID=0)
Display the comment date of the current comment.
comment_excerpt ($comment_ID=0)
Display the excerpt of the current comment.
comment_form ($args=array(), $post_id=null)
Output a complete commenting form for use within a template.
comment_form_title ($noreplytext=false, $replytext=false, $linktoparent=true)
Display text based on comment reply status.
comment_ID ()
Display the comment id of the current comment.
comment_id_fields ($id=0)
Output hidden input HTML for replying to comments.
comment_reply_link ($args=array(), $comment=null, $post=null)
Displays the HTML content for reply to comment link.
comment_text ($comment_ID=0, $args=array())
Display the text of the current comment.
comment_time ($d= '')
Display the comment time of the current comment.
comment_type ($commenttxt=false, $trackbacktxt=false, $pingbacktxt=false)
Display the comment type of the current comment.
comments_link ($deprecated= '', $deprecated_2= '')
Display the link to the current post comments.
comments_number ($zero=false, $one=false, $more=false, $deprecated= '')
Display the language string for the number of comments the current post has.
comments_open ($post_id=null)
Whether the current post is open for comments.
comments_popup_link ($zero=false, $one=false, $more=false, $css_class= '', $none=false)
Displays the link to the comments for the current post ID.
comments_template ($file= '/comments.php', $separate_comments=false)
Load the comment template specified in $file.
get_cancel_comment_reply_link ($text= '')
Retrieve HTML content for cancel comment reply link.
get_comment_author ($comment_ID=0)
Retrieve the author of the current comment.
get_comment_author_email ($comment_ID=0)
Retrieve the email of the author of the current comment.
get_comment_author_email_link ($linktext= '', $before= '', $after= '')
Return the html email link to the author of the current comment.
get_comment_author_IP ($comment_ID=0)
Retrieve the IP address of the author of the current comment.
get_comment_author_link ($comment_ID=0)
Retrieve the HTML link to the URL of the author of the current comment.
get_comment_author_url ($comment_ID=0)
Retrieve the url of the author of the current comment.
get_comment_author_url_link ($linktext= '', $before= '', $after= '')
Retrieves the HTML link of the url of the author of the current comment.
get_comment_class ($class= '', $comment_id=null, $post_id=null)
Returns the classes for the comment div as an array.
get_comment_date ($d= '', $comment_ID=0)
Retrieve the comment date of the current comment.
get_comment_excerpt ($comment_ID=0)
Retrieve the excerpt of the current comment.
get_comment_ID ()
Retrieve the comment id of the current comment.
get_comment_id_fields ($id=0)
Retrieve hidden input HTML for replying to comments.
get_comment_link ($comment=null, $args=array())
Retrieve the link to a given comment.
get_comment_reply_link ($args=array(), $comment=null, $post=null)
Retrieve HTML content for reply to comment link.
get_comment_text ($comment_ID=0, $args=array())
Retrieve the text of the current comment.
get_comment_time ($d= '', $gmt=false, $translate=true)
Retrieve the comment time of the current comment.
get_comment_type ($comment_ID=0)
Retrieve the comment type of the current comment.
get_comments_link ($post_id=0)
Retrieves the link to the current post comments.
get_comments_number ($post_id=0)
Retrieve the amount of comments a post has.
get_comments_number_text ($zero=false, $one=false, $more=false)
Display the language string for the number of comments the current post has.
get_post_reply_link ($args=array(), $post=null)
Retrieve HTML content for reply to post link.
get_trackback_url ()
Retrieve The current post's trackback URL.
pings_open ($post_id=null)
Whether the current post is open for pings.
post_reply_link ($args=array(), $post=null)
Displays the HTML content for reply to post link.
trackback_rdf ($deprecated= '')
Generate and display the RDF for the trackback information of current post.
trackback_url ($deprecated_echo=true)
Display the current post's trackback URL.
wp_comment_form_unfiltered_html_nonce ()
Display form token for unfiltered comments.
wp_list_comments ($args=array(), $comments=null)
List comments.
Function Documentation
cancel_comment_reply_link ($text = '')
Display HTML content for cancel comment reply link.
Since
2.7.0
Parameters
string $text Optional. Text to display for cancel reply link. Default empty.
Definition at line 1762 of file comment-template.php.
References $text, and get_cancel_comment_reply_link().
Referenced by comment_form().
comment_author ($comment_ID = 0)
Displays the author of the current comment.
Since
0.71
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to print the author. Default current comment.
Filter the comment author's name for display.
Since
1.2.0
4.1.0 The $comment_ID parameter was added.
Parameters
string $author The comment author's username.
int $comment_ID The comment ID.
Definition at line 58 of file comment-template.php.
References $comment, apply_filters(), get_comment(), and get_comment_author().
Referenced by WP_Comments_List_Table\column_author().
comment_author_email ($comment_ID = 0)
Display the email of the author of the current global $comment.
Care should be taken to protect the email address and assure that email harvesters do not capture your commentors' email address. Most assume that their email address will not appear in raw form on the blog. Doing so will enable anyone, including those that people don't want to get the email address and use it for their own means good and bad.
Since
0.71
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to print the author's email. Default current comment.
Filter the comment author's email for display.
Since
1.2.0
4.1.0 The $comment_ID parameter was added.
Parameters
string $author_email The comment author's email address.
int $comment_ID The comment ID.
Definition at line 115 of file comment-template.php.
References $comment, apply_filters(), get_comment(), and get_comment_author_email().
comment_author_email_link ($linktext = '', $before = '', $after = '')
Display the html email link to the author of the current comment.
Care should be taken to protect the email address and assure that email harvesters do not capture your commentors' email address. Most assume that their email address will not appear in raw form on the blog. Doing so will enable anyone, including those that people don't want to get the email address and use it for their own means good and bad.
Since
0.71
Parameters
string $linktext Optional. Text to display instead of the comment author's email address. Default empty.
string $before Optional. Text or HTML to display before the email link. Default empty.
string $after Optional. Text or HTML to display after the email link. Default empty.
Definition at line 147 of file comment-template.php.
References $link, and get_comment_author_email_link().
comment_author_IP ($comment_ID = 0)
Display the IP address of the author of the current comment.
Since
0.71
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to print the author's IP address. Default current comment.
Definition at line 280 of file comment-template.php.
References esc_html, and get_comment_author_IP().
comment_author_link ($comment_ID = 0)
Display the html link to the url of the author of the current comment.
Since
0.71
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to print the author's link. Default current comment.
Definition at line 241 of file comment-template.php.
References get_comment_author_link().
Referenced by Walker_Comment\ping().
comment_author_url ($comment_ID = 0)
Display the url of the author of the current comment.
Since
0.71
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to print the author's URL. Default current comment.
Filter the comment author's URL for display.
Since
1.2.0
4.1.0 The $comment_ID parameter was added.
Parameters
string $author_url The comment author's URL.
int $comment_ID The comment ID.
Definition at line 321 of file comment-template.php.
References $comment, apply_filters(), get_comment(), and get_comment_author_url().
comment_author_url_link ($linktext = '', $before = '', $after = '')
Displays the HTML link of the url of the author of the current comment.
Since
0.71
Parameters
string $linktext Optional. Text to display instead of the comment author's email address. Default empty.
string $before Optional. Text or HTML to display before the email link. Default empty.
string $after Optional. Text or HTML to display after the email link. Default empty.
Definition at line 391 of file comment-template.php.
References get_comment_author_url_link().
comment_class ($class = '', $comment = null, $post_id = null, $echo = true)
Generates semantic classes for each comment element.
Since
2.7.0
4.4.0 Added the ability for $comment to also accept a WP_Comment object.
Parameters
string | array $class Optional. One or more classes to add to the class list. Default empty.
int | WP_Comment $comment Comment ID or WP_Comment object. Default current comment.
int | WP_Post $post_id Post ID or WP_Post object. Default current post.
bool $echo Optional. Whether to cho or return the output. Default true.
Returns
string If $echo is false, the class will be returned. Void otherwise.
Definition at line 409 of file comment-template.php.
References $class, $comment, $post_id, and get_comment_class().
Referenced by Walker_Comment\comment(), Walker_Comment\html5_comment(), and Walker_Comment\ping().
comment_date ($d = '', $comment_ID = 0)
Display the comment date of the current comment.
Since
0.71
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
string $d Optional. The format of the date. Default user's settings.
int | WP_Comment $comment_ID WP_Comment or ID of the comment for which to print the date. Default current comment.
Definition at line 548 of file comment-template.php.
References get_comment_date().
comment_excerpt ($comment_ID = 0)
Display the excerpt of the current comment.
Since
1.2.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID WP_Comment or ID of the comment for which to print the excerpt. Default current comment.
Filter the comment excerpt for display.
Since
1.2.0
4.1.0 The $comment_ID parameter was added.
Parameters
string $comment_excerpt The comment excerpt text.
int $comment_ID The comment ID.
Definition at line 611 of file comment-template.php.
References $comment, apply_filters(), get_comment(), and get_comment_excerpt().
comment_form ($args = array(), $post_id = null)
Output a complete commenting form for use within a template.
Most strings and form fields may be controlled through the $args array passed into the function, while you may also choose to use the comment_form_default_fields filter to modify the array of default fields if you'd just like to add a new one or remove a single field. All fields are also individually passed through a filter of the form comment_form_field_$name where $name is the key used in the array of fields.
Since
3.0.0
4.1.0 Introduced the 'class_submit' argument.
4.2.0 Introduced the 'submit_button' and 'submit_fields' arguments.
4.4.0 Introduced the 'class_form', 'title_reply_before', 'title_reply_after', 'cancel_reply_before', and 'cancel_reply_after' arguments.
Parameters
array $args { Optional. Default arguments and form fields to override.
array $fields { Default comment fields, filterable by default via the 'comment_form_default_fields' hook.
string $author Comment author field HTML. string $email Comment author email field HTML. string $url Comment author URL field HTML. } string $comment_field The comment textarea field HTML. string $must_log_in HTML element for a 'must be logged in to comment' message. string $logged_in_as HTML element for a 'logged in as [user]' message. string $comment_notes_before HTML element for a message displayed before the comment fields if the user is not logged in. Default 'Your email address will not be published.'. string $comment_notes_after HTML element for a message displayed after the textarea field. string $id_form The comment form element id attribute. Default 'commentform'. string $id_submit The comment submit element id attribute. Default 'submit'. string $class_form The comment form element class attribute. Default 'comment-form'. string $class_submit The comment submit element class attribute. Default 'submit'. string $name_submit The comment submit element name attribute. Default 'submit'. string $title_reply The translatable 'reply' button label. Default 'Leave a Reply'. string $title_reply_to The translatable 'reply-to' button label. Default 'Leave a Reply to s', where s is the author of the comment being replied to. string $title_reply_before HTML displayed before the comment form title. Default: '
'. string $title_reply_after HTML displayed after the comment form title. Default: '
'. string $cancel_reply_before HTML displayed before the cancel reply link. string $cancel_reply_after HTML displayed after the cancel reply link. string $cancel_reply_link The translatable 'cancel reply' button label. Default 'Cancel reply'. string $label_submit The translatable 'submit' button label. Default 'Post a comment'. string $submit_button HTML format for the Submit button. Default: '<input name="%1$s" type="submit" id="%2$s" class="%3$s" value="%4$s">'. string $submit_field HTML format for the markup surrounding the Submit button and comment hidden fields. Default: '
%1$s %2$s', where %1$s is the submit button markup and %2$s is the comment hidden fields. string $format The comment form format. Default 'xhtml'. Accepts 'xhtml', 'html5'. }
Parameters
int | WP_Post $post_id Post ID or WP_Post object to generate the form for. Default current post.
Filter the default comment form fields.
Since
3.0.0
Parameters
array $fields The default comment fields.
This filter is documented in wp-includes/link-template.php
This filter is documented in wp-includes/link-template.php
Filter the comment form default arguments.
Use 'comment_form_default_fields' to filter the comment fields.
Since
3.0.0
Parameters
array $defaults The default comment form arguments.
Fires before the comment form.
Since
3.0.0
Fires after the HTML-formatted 'must log in after' message in the comment form.
Since
3.0.0
Fires at the top of the comment form, inside the form tag.
Since
3.0.0
Filter the 'logged in' message for the comment form for display.
Since
3.0.0
Parameters
string $args_logged_in The logged-in-as HTML-formatted message.
array $commenter An array containing the comment author's username, email, and URL.
string $user_identity If the commenter is a registered user, the display name, blank otherwise.
Fires after the is_user_logged_in() check in the comment form.
Since
3.0.0
Parameters
array $commenter An array containing the comment author's username, email, and URL.
string $user_identity If the commenter is a registered user, the display name, blank otherwise.
Filter the comment form fields, including the textarea.
Since
4.4.0
Parameters
array $comment_fields The comment fields.
Filter the content of the comment textarea field for display.
Since
3.0.0
Parameters
string $args_comment_field The content of the comment textarea field.
Fires before the comment fields in the comment form, excluding the textarea.
Since
3.0.0
Filter a comment form field for display.
The dynamic portion of the filter hook, $name, refers to the name of the comment form field. Such as 'author', 'email', or 'url'.
Since
3.0.0
Parameters
string $field The HTML-formatted output of the comment form field.
Fires after the comment fields in the comment form, excluding the textarea.
Since
3.0.0
Filter the submit button for the comment form to display.
Since
4.2.0
Parameters
string $submit_button HTML markup for the submit button.
array $args Arguments passed to comment_form().
Filter the submit field for the comment form to display.
The submit field includes the submit button, hidden fields for the comment form, and any wrapper markup.
Since
4.2.0
Parameters
string $submit_field HTML markup for the submit field.
array $args Arguments passed to comment_form().
Fires at the bottom of the comment form, inside the closing </form> tag.
Since
1.5.0
Parameters
int $post_id The post ID.
Fires after the comment form.
Since
3.0.0
Fires after the comment form if comments are closed.
Since
3.0.0
Definition at line 2102 of file comment-template.php.
References $field, $name, $post_id, $user, __, _x, apply_filters(), cancel_comment_reply_link(), comment_form_title(), comments_open(), current_theme_supports(), do_action(), elseif, endif, esc_attr(), get_comment_id_fields(), get_edit_user_link(), get_option(), get_permalink(), get_the_ID(), null, wp_get_current_commenter(), wp_login_url(), wp_logout_url(), and wp_parse_args().
comment_form_title ($noreplytext = false, $replytext = false, $linktoparent = true)
Display text based on comment reply status.
Only affects users with JavaScript disabled.
Since
2.7.0
Parameters
string $noreplytext Optional. Text to display when not replying to a comment. Default false.
string $replytext Optional. Text to display when replying to a comment. Default false. Accepts "%s" for the author of the comment being replied to.
string $linktoparent Optional. Boolean to control making the author's name a link to their comment. Default true.
Definition at line 1820 of file comment-template.php.
References $comment, __, get_comment(), get_comment_author(), and get_comment_ID().
Referenced by comment_form().
comment_ID ()
Display the comment id of the current comment.
Since
0.71
Definition at line 654 of file comment-template.php.
References get_comment_ID().
comment_id_fields ($id = 0)
Output hidden input HTML for replying to comments.
Since
2.7.0
Parameters
int $id Optional. Post ID. Default current post ID.
Definition at line 1801 of file comment-template.php.
References $id, and get_comment_id_fields().
comment_reply_link ($args = array(), $comment = null, $post = null)
Displays the HTML content for reply to comment link.
Since
2.7.0
See also
get_comment_reply_link()
Parameters
array $args Optional. Override default options.
int $comment Comment being replied to. Default current comment.
int | WP_Post $post Post ID or WP_Post object the comment is going to be displayed on. Default current post.
Returns
mixed Link to show comment form, if successful. False, if comments are closed.
Definition at line 1636 of file comment-template.php.
References $comment, $post, and get_comment_reply_link().
Referenced by Walker_Comment\comment(), and Walker_Comment\html5_comment().
comment_text ($comment_ID = 0, $args = array())
Display the text of the current comment.
Since
0.71
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
See also
Walker_Comment::comment()
Parameters
int | WP_Comment $comment_ID WP_Comment or ID of the comment for which to print the text. Default current comment.
array $args Optional. An array of arguments. Default empty array. Default empty.
Filter the text of a comment to be displayed.
Since
1.2.0
See also
Walker_Comment::comment()
Parameters
string $comment_text Text of the current comment.
WP_Comment $comment The comment object.
array $args An array of arguments.
Definition at line 940 of file comment-template.php.
References $comment, apply_filters(), get_comment(), and get_comment_text().
Referenced by WP_Comments_List_Table\column_comment(), Walker_Comment\comment(), and Walker_Comment\html5_comment().
comment_time ($d = '')
Display the comment time of the current comment.
Since
0.71
Parameters
string $d Optional. The format of the time. Default user's settings.
Definition at line 999 of file comment-template.php.
References get_comment_time().
comment_type ($commenttxt = false, $trackbacktxt = false, $pingbacktxt = false)
Display the comment type of the current comment.
Since
0.71
Parameters
string $commenttxt Optional. String to display for comment type. Default false.
string $trackbacktxt Optional. String to display for trackback type. Default false.
string $pingbacktxt Optional. String to display for pingback type. Default false.
Definition at line 1040 of file comment-template.php.
References __, _x, and get_comment_type().
comments_link ($deprecated = '', $deprecated_2 = '')
Display the link to the current post comments.
Since
0.71
Parameters
string $deprecated Not Used.
string $deprecated_2 Not Used.
Definition at line 805 of file comment-template.php.
References $deprecated, _deprecated_argument(), esc_url, and get_comments_link().
Referenced by comments_popup_link().
comments_number ($zero = false, $one = false, $more = false, $deprecated = '')
Display the language string for the number of comments the current post has.
Since
0.71
Parameters
string $zero Optional. Text for no comments. Default false.
string $one Optional. Text for one comment. Default false.
string $more Optional. Text for more than one comment. Default false.
string $deprecated Not used.
Definition at line 852 of file comment-template.php.
References $deprecated, $more, _deprecated_argument(), and get_comments_number_text().
Referenced by comments_popup_link().
comments_open ($post_id = null)
Whether the current post is open for comments.
Since
1.5.0
Parameters
int | WP_Post $post_id Post ID or WP_Post object. Default current post.
Returns
bool True if the comments are open.
Filter whether the current post is open for comments.
Since
2.5.0
Parameters
bool $open Whether the current post is open for comments.
int | WP_Post $post_id The post ID or WP_Post object.
Definition at line 1150 of file comment-template.php.
References $post_id, apply_filters(), and get_post().
Referenced by wp_xmlrpc_server\_prepare_page(), comment_form(), comments_popup_link(), feed_links_extra(), get_comment_reply_link(), get_post_reply_link(), twentyfifteen_scripts(), twentyfourteen_scripts(), twentythirteen_scripts_styles(), twentytwelve_scripts_styles(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_handle_comment_submission(), and wp_xmlrpc_server\wp_newComment().
comments_popup_link ($zero = false, $one = false, $more = false, $css_class = '', $none = false)
Displays the link to the comments for the current post ID.
Since
0.71
Parameters
string $zero Optional. String to display when no comments. Default false.
string $one Optional. String to display when only one comment is available. Default false.
string $more Optional. String to display when there are more than one comment. Default false.
string $css_class Optional. CSS class to use for comments. Default empty.
string $none Optional. String to display when comments have been turned off. Default false.
Filter the respond link when a post has no comments.
Since
4.4.0
Parameters
string $respond_link The default response link.
integer $id The post ID.
Filter the comments link attributes for display.
Since
2.5.0
Parameters
string $attributes The comments link attributes. Default empty.
Definition at line 1451 of file comment-template.php.
References $attributes, $id, $more, $title, __, _e, _n(), apply_filters(), comments_link(), comments_number(), comments_open(), esc_attr(), get_comments_number(), get_permalink(), get_the_ID(), get_the_title(), number_format_i18n(), pings_open(), and post_password_required().
Referenced by Twenty_Eleven_Ephemera_Widget\widget(), and Twenty_Fourteen_Ephemera_Widget\widget().
comments_template ($file = '/comments.php', $separate_comments = false)
Load the comment template specified in $file.
Will not display the comments template if not on single post or page, or if the post does not have comments.
Uses the WordPress database object to query for the comments. The comments are passed through the 'comments_array' filter hook with the list of comments and the post ID respectively.
The $file path is passed through a filter hook called, 'comments_template' which includes the TEMPLATEPATH and $file combined. Tries the $filtered path first and if it fails it will require the default comment template from the default theme. If either does not exist, then the WordPress process will be halted. It is advised for that reason, that the default theme is not deleted.
Will not try to get the comments if the post has none.
Since
1.5.0
WP_Query $wp_query WP_Post $post wpdb $wpdb int $id WP_Comment $comment string $user_login int $user_ID string $user_identity bool $overridden_cpage bool $withcomments
Parameters
string $file Optional. The file to load. Default '/comments.php'.
bool $separate_comments Optional. Whether to separate the comments by comment type. Default false.
Filters the arguments used to query comments in comments_template().
Since
4.5.0
Parameters
array $comment_args { Array of arguments. See WP_Comment_Query::__construct() for detailed descriptions.
string|array $orderby Field(s) to order by. string $order Order of results. Accepts 'ASC' or 'DESC'. string $status Comment status. array $include_unapproved Array of IDs or email addresses whose unapproved comments will be included in results. int $post_id ID of the post. bool $no_found_rows Whether to refrain from querying for found rows. bool $update_comment_meta_cache Whether to prime cache for comment meta. bool|string $hierarchical Whether to query for comments hierarchically. int $offset Comment offset. int $number Number of comments to fetch. }
Filter the comments array.
Since
2.1.0
Parameters
array $comments Array of comments supplied to the comments template.
int $post_ID Post ID.
Filter the path to the theme template file used for the comments template.
Since
1.5.1
Parameters
string $theme_template The path to the theme template file.
Definition at line 1251 of file comment-template.php.
References $comment, $file, $id, $page, $post, $user_ID, $wpdb, ABSPATH, add_action(), apply_filters(), elseif, esc_url, get_comment_pages_count(), get_option(), get_query_var(), is_page(), is_single(), separate_comments(), set_query_var(), wp_get_current_commenter(), and WPINC.
get_cancel_comment_reply_link ($text = '')
Retrieve HTML content for cancel comment reply link.
Since
2.7.0
Parameters
string $text Optional. Text to display for cancel reply link. Default empty.
Returns
string
Filter the cancel comment reply link HTML.
Since
2.7.0
Parameters
string $formatted_link The HTML-formatted cancel comment reply link.
string $link Cancel comment reply link URL.
string $text Cancel comment reply link text.
Definition at line 1734 of file comment-template.php.
References $link, $text, __, apply_filters(), esc_html, and remove_query_arg().
Referenced by cancel_comment_reply_link().
get_comment_author ($comment_ID = 0)
Retrieve the author of the current comment.
If the comment has an empty comment_author field, then 'Anonymous' person is assumed.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to retrieve the author. Default current comment.
Returns
string The comment author
Filter the returned comment author name.
Since
1.5.0
4.1.0 The $comment_ID and $comment parameters were added.
Parameters
string $author The comment author's username.
int $comment_ID The comment ID.
WP_Comment $comment The comment object.
Definition at line 24 of file comment-template.php.
References $comment, $user, __, apply_filters(), and get_comment().
Referenced by WP_Comments_List_Table\column_comment(), comment_author(), comment_form_title(), get_comment_author_link(), and get_comment_author_rss().
get_comment_author_email ($comment_ID = 0)
Retrieve the email of the author of the current comment.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to get the author's email. Default current comment.
Returns
string The current comment author's email
Filter the comment author's returned email address.
Since
1.5.0
4.1.0 The $comment_ID and $comment parameters were added.
Parameters
string $comment_author_email The comment author's email address.
int $comment_ID The comment ID.
WP_Comment $comment The comment object.
Definition at line 84 of file comment-template.php.
References $comment, apply_filters(), and get_comment().
Referenced by comment_author_email().
get_comment_author_email_link ($linktext = '', $before = '', $after = '')
Return the html email link to the author of the current comment.
Care should be taken to protect the email address and assure that email harvesters do not capture your commentors' email address. Most assume that their email address will not appear in raw form on the blog. Doing so will enable anyone, including those that people don't want to get the email address and use it for their own means good and bad.
Since
2.7.0
Parameters
string $linktext Optional. Text to display instead of the comment author's email address. Default empty.
string $before Optional. Text or HTML to display before the email link. Default empty.
string $after Optional. Text or HTML to display after the email link. Default empty.
Returns
string
Filter the comment author's email for display.
Care should be taken to protect the email address and assure that email harvesters do not capture your commenter's email address.
Since
1.2.0
4.1.0 The $comment parameter was added.
Parameters
string $comment_author_email The comment author's email address.
WP_Comment $comment The comment object.
Definition at line 169 of file comment-template.php.
References $comment, apply_filters(), esc_html, esc_url, and get_comment().
Referenced by comment_author_email_link().
get_comment_author_IP ($comment_ID = 0)
Retrieve the IP address of the author of the current comment.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to get the author's IP address. Default current comment.
Returns
string Comment author's IP address.
Filter the comment author's returned IP address.
Since
1.5.0
4.1.0 The $comment_ID and $comment parameters were added.
Parameters
string $comment_author_IP The comment author's IP address.
int $comment_ID The comment ID.
WP_Comment $comment The comment object.
Definition at line 255 of file comment-template.php.
References $comment, apply_filters(), and get_comment().
Referenced by WP_Comments_List_Table\column_author(), and comment_author_IP().
get_comment_author_link ($comment_ID = 0)
Retrieve the HTML link to the URL of the author of the current comment.
Both get_comment_author_url() and get_comment_author() rely on get_comment(), which falls back to the global comment variable if the $comment_ID argument is empty.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to get the author's link. Default current comment.
Returns
string The comment author name or HTML link for author's URL.
Filter the comment author's link for display.
Since
1.5.0
4.1.0 The $author and $comment_ID parameters were added.
Parameters
string $return The HTML-formatted comment author link. Empty for an invalid URL.
string $author The comment author's username.
int $comment_ID The comment ID.
Definition at line 208 of file comment-template.php.
References $comment, $url, apply_filters(), get_comment(), get_comment_author(), and get_comment_author_url().
Referenced by Walker_Comment\comment(), comment_author_link(), Walker_Comment\html5_comment(), and WP_Widget_Recent_Comments\widget().
get_comment_author_url ($comment_ID = 0)
Retrieve the url of the author of the current comment.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or the ID of the comment for which to get the author's URL. Default current comment.
Returns
string Comment author URL.
Filter the comment author's URL.
Since
1.5.0
4.1.0 The $comment_ID and $comment parameters were added.
Parameters
string $url The comment author's URL.
int $comment_ID The comment ID.
WP_Comment $comment The comment object.
Definition at line 294 of file comment-template.php.
References $comment, $url, apply_filters(), esc_url, and get_comment().
Referenced by WP_Comments_List_Table\column_author(), comment_author_url(), get_comment_author_link(), and get_comment_author_url_link().
get_comment_author_url_link ($linktext = '', $before = '', $after = '')
Retrieves the HTML link of the url of the author of the current comment.
$linktext parameter is only used if the URL does not exist for the comment author. If the URL does exist then the URL will be used and the $linktext will be ignored.
Encapsulate the HTML link between the $before and $after. So it will appear in the order of $before, link, and finally $after.
Since
1.5.0
Parameters
string $linktext Optional. The text to display instead of the comment author's email address. Default empty.
string $before Optional. The text or HTML to display before the email link. Default empty.
string $after Optional. The text or HTML to display after the email link. Default empty.
Returns
string The HTML link between the $before and $after parameters.
Filter the comment author's returned URL link.
Since
1.5.0
Parameters
string $return The HTML-formatted comment author URL link.
Definition at line 357 of file comment-template.php.
References $url, apply_filters(), get_comment_author_url(), and str_replace.
Referenced by comment_author_url_link().
get_comment_class ($class = '', $comment_id = null, $post_id = null)
Returns the classes for the comment div as an array.
Since
2.7.0
4.4.0 Added the ability for $comment_id to also accept a WP_Comment object.
int $comment_alt int $comment_depth int $comment_thread_alt
Parameters
string | array $class Optional. One or more classes to add to the class list. Default empty.
int | WP_Comment $comment_id Comment ID or WP_Comment object. Default current comment.
int | WP_Post $post_id Post ID or WP_Post object. Default current post.
Returns
array An array of classes.
Filter the returned CSS classes for the current comment.
Since
2.7.0
Parameters
array $classes An array of comment classes.
string $class A comma-separated list of additional classes added to the list.
int $comment_id The comment id.
WP_Comment $comment The comment object.
int | WP_Post $post_id The post ID or WP_Post object.
Definition at line 433 of file comment-template.php.
References $class, $comment, $post, $post_id, $user, apply_filters(), get_comment(), get_post(), if, and sanitize_html_class().
Referenced by comment_class(), and WP_Comments_List_Table\single_row().
get_comment_date ($d = '', $comment_ID = 0)
Retrieve the comment date of the current comment.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
string $d Optional. The format of the date. Default user's setting.
int | WP_Comment $comment_ID WP_Comment or ID of the comment for which to get the date. Default current comment.
Returns
string The comment's date.
Filter the returned comment date.
Since
1.5.0
Parameters
string | int $date Formatted date string or Unix timestamp.
string $d The format of the date.
WP_Comment $comment The comment object.
Definition at line 520 of file comment-template.php.
References $comment, apply_filters(), get_comment(), get_option(), and mysql2date().
Referenced by WP_Comments_List_Table\column_date(), Walker_Comment\comment(), comment_date(), and Walker_Comment\html5_comment().
get_comment_excerpt ($comment_ID = 0)
Retrieve the excerpt of the current comment.
Will cut each word and only output the first 20 words with '…' at the end. If the word count is less than 20, then no truncating is done and no '…' will appear.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID WP_Comment or ID of the comment for which to get the excerpt. Default current comment.
Returns
string The maybe truncated comment with 20 words or less.
Filter the amount of words used in the comment excerpt.
Since
4.4.0
Parameters
int $comment_excerpt_length The amount of words you want to display in the comment excerpt.
Filter the retrieved comment excerpt.
Since
1.5.0
4.1.0 The $comment_ID and $comment parameters were added.
Parameters
string $excerpt The comment excerpt text.
int $comment_ID The comment ID.
WP_Comment $comment The comment object.
Definition at line 566 of file comment-template.php.
References $comment, $excerpt, apply_filters(), get_comment(), and str_replace.
Referenced by comment_excerpt().
get_comment_ID ()
Retrieve the comment id of the current comment.
Since
1.5.0
Returns
int The comment ID.
Filter the returned comment ID.
Since
1.5.0
4.1.0 The $comment_ID parameter was added.
Parameters
int $comment_ID The current comment ID.
WP_Comment $comment The comment object.
Definition at line 634 of file comment-template.php.
References $comment, apply_filters(), and get_comment().
Referenced by comment_form_title(), and comment_ID().
get_comment_id_fields ($id = 0)
Retrieve hidden input HTML for replying to comments.
Since
3.0.0
Parameters
int $id Optional. Post ID. Default current post ID.
Returns
string Hidden input HTML for replying to comments
Filter the returned comment id fields.
Since
3.0.0
Parameters
string $result The HTML-formatted hidden id field comment elements.
int $id The post ID.
int $replytoid The id of the comment being replied to.
Definition at line 1774 of file comment-template.php.
References $id, apply_filters(), and get_the_ID().
Referenced by comment_form(), and comment_id_fields().
get_comment_link ($comment = null, $args = array())
Retrieve the link to a given comment.
Since
1.5.0
4.4.0 Added the ability for $comment to also accept a WP_Comment object. Added $cpage argument.
See also
get_page_of_comment()
WP_Rewrite $wp_rewrite bool $in_comment_loop
Parameters
WP_Comment | int | null $comment Comment to retrieve. Default current comment.
array $args { An array of optional arguments to override the defaults.
string $type Passed to {
See also
get_page_of_comment()}. int $page Current page of comments, for calculating comment pagination. int $per_page Per-page value for comment pagination. int $max_depth Passed to {
get_page_of_comment()}. int|string $cpage Value to use for the comment's "comment-page" or "cpage" value. If provided, this value overrides any value calculated from $page and $per_page. }
Returns
string The permalink to the given comment.
Filter the returned single comment permalink.
Since
2.8.0
4.4.0 Added the $cpage parameter.
See also
get_page_of_comment()
Parameters
string $link The comment permalink with 'comment-$id' appended.
WP_Comment $comment The current comment object.
array $args An array of arguments to override the defaults.
int $cpage The calculated 'cpage' value.
Definition at line 682 of file comment-template.php.
References $comment, $default_comments_page, $link, $wp_rewrite, add_query_arg(), apply_filters(), elseif, get_comment(), get_option(), get_page_of_comment(), get_permalink(), get_query_var(), null, trailingslashit(), user_trailingslashit(), and wp_parse_args().
Referenced by wp_xmlrpc_server\_prepare_comment(), WP_Comments_List_Table\column_comment(), WP_Comments_List_Table\column_date(), comment_link(), and WP_Widget_Recent_Comments\widget().
get_comment_reply_link ($args = array(), $comment = null, $post = null)
Retrieve HTML content for reply to comment link.
Since
2.7.0
4.4.0 Added the ability for $comment to also accept a WP_Comment object.
Parameters
array $args { Optional. Override default arguments.
string $add_below The first part of the selector used to identify the comment to respond below. The resulting value is passed as the first parameter to addComment.moveForm(), concatenated as $add_below-$comment->comment_ID. Default 'comment'. string $respond_id The selector identifying the responding comment. Passed as the third parameter to addComment.moveForm(), and appended to the link URL as a hash value. Default 'respond'. string $reply_text The text of the Reply link. Default 'Reply'. string $login_text The text of the link to reply if logged out. Default 'Log in to Reply'. int $depth' The depth of the new comment. Must be greater than 0 and less than the value of the 'thread_comments_depth' option set in Settings > Discussion. Default 0. string $before The text or HTML to add before the reply link. Default empty. string $after The text or HTML to add after the reply link. Default empty. }
Parameters
int | WP_Comment $comment Comment being replied to. Default current comment.
int | WP_Post $post Post ID or WP_Post object the comment is going to be displayed on. Default current post.
Returns
void|false|string Link to show comment form, if successful. False, if comments are closed.
Filter the comment reply link arguments.
Since
4.1.0
Parameters
array $args Comment reply link arguments. See get_comment_reply_link() for more information on accepted arguments.
WP_Comment $comment The object of the comment being replied to.
WP_Post $post The WP_Post object.
Filter the comment reply link.
Since
2.7.0
Parameters
string $link The HTML markup for the comment reply link.
array $args An array of arguments overriding the defaults.
object $comment The object of the comment being replied.
WP_Post $post The WP_Post object.
Definition at line 1550 of file comment-template.php.
References $comment, $link, $post, __, add_query_arg(), apply_filters(), comments_open(), esc_attr(), esc_url, get_comment(), get_option(), get_permalink(), get_post(), wp_login_url(), and wp_parse_args().
Referenced by comment_reply_link().
get_comment_text ($comment_ID = 0, $args = array())
Retrieve the text of the current comment.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
See also
Walker_Comment::comment()
Parameters
int | WP_Comment $comment_ID WP_Comment or ID of the comment for which to get the text. Default current comment.
array $args Optional. An array of arguments. Default empty.
Returns
string The comment content.
Filter the text of a comment.
Since
1.5.0
See also
Walker_Comment::comment()
Parameters
string $comment_content Text of the comment.
WP_Comment $comment The comment object.
array $args An array of arguments.
Definition at line 911 of file comment-template.php.
References $comment, apply_filters(), and get_comment().
Referenced by comment_text(), and comment_text_rss().
get_comment_time ($d = '', $gmt = false, $translate = true)
Retrieve the comment time of the current comment.
Since
1.5.0
Parameters
string $d Optional. The format of the time. Default user's settings.
bool $gmt Optional. Whether to use the GMT date. Default false.
bool $translate Optional. Whether to translate the time (for use in feeds). Default true.
Returns
string The formatted time.
Filter the returned comment time.
Since
1.5.0
Parameters
string | int $date The comment time, formatted as a date string or Unix timestamp.
string $d Date format.
bool $gmt Whether the GMT date is in use.
bool $translate Whether the time is translated.
WP_Comment $comment The comment object.
Definition at line 969 of file comment-template.php.
References $comment, apply_filters(), get_comment(), get_option(), and mysql2date().
Referenced by Walker_Comment\comment(), comment_time(), and Walker_Comment\html5_comment().
get_comment_type ($comment_ID = 0)
Retrieve the comment type of the current comment.
Since
1.5.0
4.4.0 Added the ability for $comment_ID to also accept a WP_Comment object.
Parameters
int | WP_Comment $comment_ID Optional. WP_Comment or ID of the comment for which to get the type. Default current comment.
Returns
string The comment type.
Filter the returned comment type.
Since
1.5.0
4.1.0 The $comment_ID and $comment parameters were added.
Parameters
string $comment_type The type of comment, such as 'comment', 'pingback', or 'trackback'.
int $comment_ID The comment ID.
WP_Comment $comment The comment object.
Definition at line 1013 of file comment-template.php.
References $comment, apply_filters(), and get_comment().
Referenced by comment_type().
get_comments_link ($post_id = 0)
Retrieves the link to the current post comments.
Since
1.5.0
Parameters
int | WP_Post $post_id Optional. Post ID or WP_Post object. Default is global $post.
Returns
string The link to the comments.
Filter the returned post comments permalink.
Since
3.6.0
Parameters
string $comments_link Post comments permalink with 'comments' appended.
int | WP_Post $post_id Post ID or WP_Post object.
Definition at line 782 of file comment-template.php.
References $post_id, apply_filters(), get_comments_number(), and get_permalink().
Referenced by comments_link(), and comments_link_feed().
get_comments_number ($post_id = 0)
Retrieve the amount of comments a post has.
Since
1.5.0
Parameters
int | WP_Post $post_id Optional. Post ID or WP_Post object. Default is global $post.
Returns
int The number of comments a post has.
Filter the returned comment count for a post.
Since
1.5.0
Parameters
int $count Number of comments a post has.
int $post_id Post ID.
Definition at line 821 of file comment-template.php.
References $count, $post, $post_id, apply_filters(), and get_post().
Referenced by WP_List_Table\comments_bubble(), comments_popup_link(), get_comments_link(), get_comments_number_text(), and Twenty_Fourteen_Ephemera_Widget\widget().
get_comments_number_text ($zero = false, $one = false, $more = false)
Display the language string for the number of comments the current post has.
Since
4.0.0
Parameters
string $zero Optional. Text for no comments. Default false.
string $one Optional. Text for one comment. Default false.
string $more Optional. Text for more than one comment. Default false.
Filter the comments count for display.
Since
1.5.0
See also
_n()
Parameters
string $output A translatable string formatted based on whether the count is equal to 0, 1, or 1+.
int $number The number of post comments.
Definition at line 868 of file comment-template.php.
References $more, $output, __, _n(), apply_filters(), elseif, get_comments_number(), number_format_i18n(), and str_replace.
Referenced by comments_number().
get_post_reply_link ($args = array(), $post = null)
Retrieve HTML content for reply to post link.
Since
2.7.0
Parameters
array $args { Optional. Override default arguments.
string $add_below The first part of the selector used to identify the comment to respond below. The resulting value is passed as the first parameter to addComment.moveForm(), concatenated as $add_below-$comment->comment_ID. Default is 'post'. string $respond_id The selector identifying the responding comment. Passed as the third parameter to addComment.moveForm(), and appended to the link URL as a hash value. Default 'respond'. string $reply_text Text of the Reply link. Default is 'Leave a Comment'. string $login_text Text of the link to reply if logged out. Default is 'Log in to leave a Comment'. string $before Text or HTML to add before the reply link. Default empty. string $after Text or HTML to add after the reply link. Default empty. }
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object the comment is going to be displayed on. Default current post.
Returns
false|null|string Link to show comment form, if successful. False, if comments are closed.
Filter the formatted post comments link HTML.
Since
2.7.0
Parameters
string $formatted The HTML-formatted post comments link.
int | WP_Post $post The post ID or WP_Post object.
Definition at line 1663 of file comment-template.php.
References $link, $post, __, apply_filters(), comments_open(), get_option(), get_permalink(), get_post(), wp_login_url(), and wp_parse_args().
Referenced by post_reply_link().
get_trackback_url ()
Retrieve The current post's trackback URL.
There is a check to see if permalink's have been enabled and if so, will retrieve the pretty path. If permalinks weren't enabled, the ID of the current post is used and appended to the correct page to go to.
Since
1.5.0
Returns
string The trackback URL after being filtered.
Filter the returned trackback URL.
Since
2.2.0
Parameters
string $tb_url The trackback URL.
Definition at line 1068 of file comment-template.php.
References $tb_url, apply_filters(), get_option(), get_permalink(), get_the_ID(), trailingslashit(), and user_trailingslashit().
Referenced by trackback_url().
pings_open ($post_id = null)
Whether the current post is open for pings.
Since
1.5.0
Parameters
int | WP_Post $post_id Post ID or WP_Post object. Default current post.
Returns
bool True if pings are accepted
Filter whether the current post is open for pings.
Since
2.5.0
Parameters
bool $open Whether the current post is open for pings.
int | WP_Post $post_id The post ID or WP_Post object.
Definition at line 1175 of file comment-template.php.
References $post_id, apply_filters(), and get_post().
Referenced by wp_xmlrpc_server\_prepare_page(), comments_popup_link(), feed_links_extra(), WP\handle_404(), and wp_xmlrpc_server\pingback_ping().
post_reply_link ($args = array(), $post = null)
Displays the HTML content for reply to post link.
Since
2.7.0
See also
get_post_reply_link()
Parameters
array $args Optional. Override default options,
int | WP_Post $post Post ID or WP_Post object the comment is going to be displayed on. Default current post.
Returns
string|bool|null Link to show comment form, if successful. False, if comments are closed.
Definition at line 1722 of file comment-template.php.
References $post, and get_post_reply_link().
trackback_rdf ($deprecated = '')
Generate and display the RDF for the trackback information of current post.
Deprecated in 3.0.0, and restored in 3.0.1.
Since
0.71
Parameters
int $deprecated Not used (Was $timezone = 0).
Definition at line 1119 of file comment-template.php.
References $_SERVER, $deprecated, _deprecated_argument(), get_the_title(), the_permalink(), and wptexturize().
trackback_url ($deprecated_echo = true)
Display the current post's trackback URL.
Since
0.71
Parameters
bool $deprecated_echo Not used.
Returns
void|string Should only be used to echo the trackback URL, use get_trackback_url() for the result instead.
Definition at line 1093 of file comment-template.php.
References __, _deprecated_argument(), and get_trackback_url().
wp_comment_form_unfiltered_html_nonce ()
Display form token for unfiltered comments.
Will only display nonce token if the current user has permissions for unfiltered html. Won't display the token for other users.
The function was backported to 2.0.10 and was added to versions 2.1.3 and above. Does not exist in versions prior to 2.0.10 in the 2.0 branch and in the 2.1 branch, prior to 2.1.3. Technically added in 2.2.0.
Backported to 2.0.10.
Since
2.1.3
Definition at line 1206 of file comment-template.php.
References $post, $post_id, current_user_can(), get_post(), and wp_nonce_field().
wp_list_comments ($args = array(), $comments = null)
List comments.
Used in the comments.php template to list comments for a particular post.
Since
2.7.0
See also
WP_Query->comments
WP_Query $wp_query int $comment_alt int $comment_depth int $comment_thread_alt bool $overridden_cpage bool $in_comment_loop
Parameters
string | array $args { Optional. Formatting options.
object $walker Instance of a Walker class to list comments. Default null. int $max_depth The maximum comments depth. Default empty. string $style The style of list ordering. Default 'ul'. Accepts 'ul', 'ol'. string $callback Callback function to use. Default null. string $end-callback Callback function to use at the end. Default null. string $type Type of comments to list. Default 'all'. Accepts 'all', 'comment', 'pingback', 'trackback', 'pings'. int $page Page ID to list comments for. Default empty. int $per_page Number of comments to list per page. Default empty. int $avatar_size Height and width dimensions of the avatar size. Default 32. string $reverse_top_level Ordering of the listed comments. Default null. Accepts 'desc', 'asc'. bool $reverse_children Whether to reverse child comments in the list. Default null. string $format How to format the comments list. Default 'html5' if the theme supports it. Accepts 'html5', 'xhtml'. bool $short_ping Whether to output short pings. Default false. bool $echo Whether to echo the output or return it. Default true. }
Parameters
array $comments Optional. Array of WP_Comment objects.
Filter the arguments used in retrieving the comment list.
Since
4.0.0
See also
wp_list_comments()
Parameters
array $r An array of arguments for displaying comments.
Definition at line 1875 of file comment-template.php.
References $default_comments_page, $output, apply_filters(), current_theme_supports(), elseif, get_comment_pages_count(), get_comments(), get_option(), get_queried_object_id(), get_query_var(), is_singular(), null, separate_comments(), set_query_var(), and wp_parse_args().