GravityView: cron.php File Reference
cron.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_cron_array ()
Retrieve cron info array option.
_set_cron_array ($cron)
Updates the CRON option with the new CRON array.
_upgrade_cron_array ($cron)
Upgrade a Cron info array.
spawn_cron ($gmt_time=0)
Sends a request to run cron through HTTP request that doesn't halt page loading.
wp_clear_scheduled_hook ($hook, $args=array())
Unschedule all cron jobs attached to a specific hook.
wp_cron ()
Run scheduled callbacks or spawn cron for all scheduled events.
wp_get_schedule ($hook, $args=array())
Retrieve Cron schedule for hook with arguments.
wp_get_schedules ()
Retrieve supported and filtered Cron recurrences.
wp_next_scheduled ($hook, $args=array())
Retrieve the next timestamp for a cron event.
wp_reschedule_event ($timestamp, $recurrence, $hook, $args=array())
Reschedule a recurring event.
wp_schedule_event ($timestamp, $recurrence, $hook, $args=array())
Schedule a periodic event.
wp_schedule_single_event ($timestamp, $hook, $args=array())
Schedules a hook to run only once.
wp_unschedule_event ($timestamp, $hook, $args=array())
Unschedule a previously scheduled cron job.
Function Documentation
_get_cron_array ()
Retrieve cron info array option.
Since
2.1.0 private
Returns
false|array CRON info array.
Definition at line 441 of file cron.php.
References _upgrade_cron_array(), and get_option().
Referenced by spawn_cron(), upgrade_431(), wp_clear_scheduled_hook(), wp_cron(), wp_get_schedule(), wp_next_scheduled(), wp_reschedule_event(), wp_schedule_event(), wp_schedule_single_event(), and wp_unschedule_event().
_set_cron_array ($cron)
Updates the CRON option with the new CRON array.
Since
2.1.0 private
Parameters
array $cron Cron info array from _get_cron_array().
Definition at line 462 of file cron.php.
References update_option().
Referenced by upgrade_431(), wp_schedule_event(), wp_schedule_single_event(), and wp_unschedule_event().
_upgrade_cron_array ($cron)
Upgrade a Cron info array.
This function upgrades the Cron info array to version 2.
Since
2.1.0 private
Parameters
array $cron Cron info array from _get_cron_array().
Returns
array An upgraded Cron info array.
Definition at line 478 of file cron.php.
References update_option().
Referenced by _get_cron_array().
spawn_cron ($gmt_time = 0)
Sends a request to run cron through HTTP request that doesn't halt page loading.
Since
2.1.0
Parameters
int $gmt_time Optional. Unix timestamp. Default 0 (current time is used).
Filter the cron request arguments.
Since
3.5.0
4.5.0 $doing_wp_cron was added to the filter arguments.
Parameters
array $cron_request_array { An array of cron request URL arguments.
string $url The cron request URL. int $key The 22 digit GMT microtime. array $args { An array of cron request arguments.
int $timeout The request timeout in seconds. Default .01 seconds. bool $blocking Whether to set blocking for the request. Default false. bool $sslverify Whether SSL should be verified for the request. Default false. } }
Parameters
string $doing_wp_cron The unix timestamp of the cron lock.
This filter is documented in wp-includes/class-wp-http-streams.php
Definition at line 241 of file cron.php.
References $_SERVER, $gmt_time, $keys, _get_cron_array(), ABSPATH, add_query_arg(), apply_filters(), get_transient(), set_transient(), site_url(), WP_DEBUG, wp_remote_post(), and wp_unslash().
Referenced by wp_cron().
wp_clear_scheduled_hook ($hook, $args = array())
Unschedule all cron jobs attached to a specific hook.
Since
2.1.0
Parameters
string $hook Action hook, the execution of which will be unscheduled.
array $args Optional. Arguments that were to be pass to the hook's callback function.
Definition at line 190 of file cron.php.
References __, _deprecated_argument(), _get_cron_array(), and wp_unschedule_event().
Referenced by _future_post_hook(), _transition_post_status(), check_and_publish_future_post(), GFPaymentAddOn\uninstall(), upgrade_370(), upgrade_372(), upgrade_450(), and wp_delete_post().
wp_cron ()
Run scheduled callbacks or spawn cron for all scheduled events.
Since
2.1.0
Definition at line 337 of file cron.php.
References $_SERVER, $gmt_time, $keys, _get_cron_array(), DISABLE_WP_CRON, spawn_cron(), and wp_get_schedules().
wp_get_schedule ($hook, $args = array())
Retrieve Cron schedule for hook with arguments.
Since
2.1.0
Parameters
string $hook Action hook to execute when cron is run.
array $args Optional. Arguments to pass to the hook's callback function.
Returns
string|false False, if no schedule. Schedule on success.
Definition at line 417 of file cron.php.
References _get_cron_array().
wp_get_schedules ()
Retrieve supported and filtered Cron recurrences.
The supported recurrences are 'hourly' and 'daily'. A plugin may add more by hooking into the 'cron_schedules' filter. The filter accepts an array of arrays. The outer array has a key that is the name of the schedule or for example 'weekly'. The value is an array with two keys, one is 'interval' and the other is 'display'.
The 'interval' is a number in seconds of when the cron job should run. So for 'hourly', the time is 3600 or 60*60. For weekly, the value would be 60*60*24*7 or 604800. The value of 'interval' would then be 604800.
The 'display' is the description. For the 'weekly' key, the 'display' would be `__('Once Weekly')`.
For your plugin, you will be passed an array. you can easily add your schedule by doing the following.
// Filter parameter variable name is 'array'.
$array['weekly'] = array(
    'interval' => 604800,
       'display'  => __( 'Once Weekly' )
);
Since
2.1.0
Returns
array
Filter the non-default cron schedules.
Since
2.1.0
Parameters
array $new_schedules An array of non-default cron schedules. Default empty.
Definition at line 392 of file cron.php.
References __, and apply_filters().
Referenced by wp_cron(), wp_reschedule_event(), and wp_schedule_event().
wp_next_scheduled ($hook, $args = array())
Retrieve the next timestamp for a cron event.
Since
2.1.0
Parameters
string $hook Action hook to execute when cron is run.
array $args Optional. Arguments to pass to the hook's callback function.
Returns
false|int The UNIX timestamp of the next time the scheduled event will occur.
Definition at line 222 of file cron.php.
References _get_cron_array().
Referenced by _wp_check_for_scheduled_split_terms(), GravityView_Cache\schedule_transient_cleanup(), GFPaymentAddOn\setup_cron(), wp_schedule_single_event(), wp_schedule_update_checks(), wp_schedule_update_network_counts(), and wp_version_check().
wp_reschedule_event ($timestamp, $recurrence, $hook, $args = array())
Reschedule a recurring event.
Since
2.1.0
Parameters
int $timestamp Timestamp for when to run the event.
string $recurrence How often the event should recur.
string $hook Action hook to execute when cron is run.
array $args Optional. Arguments to pass to the hook's callback function.
Returns
false|void False when an event is not scheduled.
Definition at line 115 of file cron.php.
References $now, _get_cron_array(), wp_get_schedules(), and wp_schedule_event().
wp_schedule_event ($timestamp, $recurrence, $hook, $args = array())
Schedule a periodic event.
Schedules a hook which will be executed by the WordPress actions core on a specific interval, specified by you. The action will trigger when someone visits your WordPress site, if the scheduled time has passed.
Valid values for the recurrence are hourly, daily and twicedaily. These can be extended using the cron_schedules filter in wp_get_schedules().
Use wp_next_scheduled() to prevent duplicates
Since
2.1.0
Parameters
int $timestamp Timestamp for when to run the event.
string $recurrence How often the event should recur.
string $hook Action hook to execute when cron is run.
array $args Optional. Arguments to pass to the hook's callback function.
Returns
false|void False when an event is not scheduled.
This filter is documented in wp-includes/cron.php
Definition at line 77 of file cron.php.
References _get_cron_array(), _set_cron_array(), apply_filters(), object, and wp_get_schedules().
Referenced by GravityView_Cache\schedule_transient_cleanup(), GFPaymentAddOn\setup_cron(), wp_reschedule_event(), wp_schedule_update_checks(), and wp_schedule_update_network_counts().
wp_schedule_single_event ($timestamp, $hook, $args = array())
Schedules a hook to run only once.
Schedules a hook which will be executed once by the WordPress actions core at a time which you specify. The action will fire off when someone visits your WordPress site, if the schedule time has passed.
Since
2.1.0 int $timestamp Timestamp for when to run the event. string $hook Action hook to execute when cron is run. array $args Optional. Arguments to pass to the hook's callback function. false|void False when an event is not scheduled.
Filter a single event before it is scheduled.
Since
3.1.0
Parameters
object $event An object containing an event's data.
Definition at line 23 of file cron.php.
References _get_cron_array(), _set_cron_array(), apply_filters(), object, and wp_next_scheduled().
Referenced by File_Upload_Upgrader\__construct(), _future_post_hook(), _publish_post_hook(), _wp_batch_split_terms(), _wp_check_for_scheduled_split_terms(), WP_Automatic_Updater\after_core_update(), check_and_publish_future_post(), upgrade_210(), upgrade_430(), wp_import_handle_upload(), and wp_version_check().
wp_unschedule_event ($timestamp, $hook, $args = array())
Unschedule a previously scheduled cron job.
The $timestamp and $hook parameters are required, so that the event can be identified.
Since
2.1.0
Parameters
int $timestamp Timestamp for when to run the event.
string $hook Action hook, the execution of which will be unscheduled.
array $args Arguments to pass to the hook's callback function. Although not passed to a callback function, these arguments are used to uniquely identify the scheduled event, so they should be the same as those used when originally scheduling the event.
Returns
false|void False when an event is not unscheduled.
Definition at line 166 of file cron.php.
References _get_cron_array(), and _set_cron_array().
Referenced by wp_clear_scheduled_hook().