GravityView: custom.php File Reference
custom.php File Reference
Namespaces
GravityView
GPL2+
Variables
if(empty($field_settings['content'])) $content = GravityView_API::replace_variables($field_settings['content'], $form, $entry, false, true, false)
$field_settings ['content'] = apply_filters('gravityview/fields/custom/content_before', $field_settings['content'])
$field_settings ['content'] = trim(rtrim($field_settings['content']))
$gravityview_view = GravityView_View::getInstance()
Variable Documentation
$content
if (apply_filters('gravityview/fields/custom/decode_shortcodes', false, $content)) if (!empty($field_settings[ 'wpautop'])) $content = GravityView_API::replace_variables($field_settings['content'], $form, $entry, false, true, false)
Runs Filter:
gravityview/fields/custom/decode_shortcodes Decode brackets in shortcodes
Since
1.16.5
Parameters
boolean $decode Enable/Disable decoding of brackets in the content (default: false)
string $content HTML content of field
Runs Filter:
gravityview/fields/custom/content_after Modify Custom Content field output after Merge Tag variables get replaced, before shortcodes get processed
Since
1.6.2
Parameters
string $content HTML content of field
Definition at line 37 of file custom.php.
Referenced by View\content(), GravityView_Entry_Link_Shortcode\delete_shortcode(), GravityView_Entry_Link_Shortcode\edit_shortcode(), GravityView_Plugin_Hooks_Gravity_PDF\fix_entry_id_for_custom_content_shortcode(), View_Collection\from_content(), GravityView_Entry_Link_Shortcode\get_anchor_text(), GravityView_Field_Notes\get_email_footer(), GravityView_Field_FileUpload\get_field_input(), gravityview_has_shortcode_r(), GravityView_Widget_Search\has_date_field(), GVCommon\has_shortcode_r(), GravityView_frontend\insert_view_in_content(), GVCommon\js_encrypt(), GravityView_Theme_Hooks_SiteOrigin\merge_content_meta_keys(), Shortcode\parse(), GravityView_View_Data\parse_post_content(), GravityView_Entry_Link_Shortcode\read_shortcode(), GravityView_Widget_Custom_Content\render_frontend(), Widget\render_shortcode(), GravityView_Cache\set(), GVLogic_Shortcode\shortcode(), and GravityView_Entry_Link_Shortcode\shortcode().
$field_settings [1/2]
array $field_settings = apply_filters('gravityview/fields/custom/content_before', $field_settings['content'])
Runs Filter:
gravityview/fields/custom/content_before Modify Custom Content field output before Merge Tag processing
Since
1.6.2
Parameters
string $content HTML content of field
Definition at line 27 of file custom.php.
Referenced by GravityView_API\entry_link_html(), GravityView_API\field_value(), GravityView_Field_Is_Approved\filter_field_value(), GravityView_Field_Date_Created\get_content(), GravityView_Field_Date_Updated\get_content(), GravityView_Field_Gravatar\get_email(), GravityView_Field_FileUpload\get_field_input(), GV\Mocks\GravityView_API_field_label(), GV\Mocks\GravityView_API_field_value(), GravityView_Field_Unsubscribe\modify_entry_value_unsubscribe(), and GravityView_Field_Workflow_Current_Status_Timestamp\modify_entry_value_workflow_current_status_timestamp().
$field_settings [2/2]
$field_settings[ 'content'] = trim(rtrim($field_settings['content']))
Definition at line 29 of file custom.php.
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Definition at line 10 of file custom.php.