GravityView: dashboard.php File Reference
dashboard.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_dashboard_control_callback ($dashboard, $meta_box)
_wp_dashboard_recent_comments_row (&$comment, $show_date=true)
WP_Comment $comment
dashboard_browser_nag_class ($classes)
wp_add_dashboard_widget ($widget_id, $widget_name, $callback, $control_callback=null, $callback_args=null)
array $wp_dashboard_control_callbacks
wp_check_browser_version ()
Check if the user needs a browser update.
wp_dashboard ()
Displays the dashboard.
wp_dashboard_browser_nag ()
wp_dashboard_cached_rss_widget ($widget_id, $callback, $check_urls=array())
Checks to see if all of the feed url in $check_urls are cached.
wp_dashboard_empty ()
Empty function usable by plugins to output empty dashboard widget (to be populated later by JS).
wp_dashboard_plugins_output ($rss, $args=array())
Display plugins text for the WordPress news widget.
wp_dashboard_primary ()
WordPress News dashboard widget.
wp_dashboard_primary_output ($widget_id, $feeds)
Display the WordPress news feeds.
wp_dashboard_quick_press ($error_msg=false)
The Quick Draft widget display and creation of drafts.
wp_dashboard_quota ()
Display file upload quota on dashboard.
wp_dashboard_recent_comments ($total_items=5)
Show Comments section.
wp_dashboard_recent_drafts ($drafts=false)
Show recent drafts of the user on the dashboard.
wp_dashboard_recent_posts ($args)
Generates Publishing Soon and Recently Published sections.
wp_dashboard_right_now ()
Dashboard widget that displays some basic stats about the site.
wp_dashboard_rss_control ($widget_id, $form_inputs=array())
The RSS dashboard widget control.
wp_dashboard_rss_output ($widget_id)
Display generic dashboard RSS widget feed.
wp_dashboard_setup ()
Registers dashboard widgets.
wp_dashboard_site_activity ()
Callback function for Activity widget.
wp_dashboard_trigger_widget_control ($widget_control_id=false)
Calls widget control callback.
wp_network_dashboard_right_now ()
wp_welcome_panel ()
Displays a welcome panel to introduce users to WordPress.
Function Documentation
_wp_dashboard_control_callback ($dashboard, $meta_box)
Parameters
type $dashboard
type $meta_box
Definition at line 176 of file dashboard.php.
References __, esc_attr(), submit_button(), wp_dashboard_trigger_widget_control(), and wp_nonce_field().
_wp_dashboard_recent_comments_row (& $comment, $show_date = true)
WP_Comment $comment
Parameters
WP_Comment $comment
bool $show_date
Filter the action links displayed for each comment in the 'Recent Comments' dashboard widget.
Since
2.6.0
Parameters
array $actions An array of comment actions. Default actions include: 'Approve', 'Unapprove', 'Edit', 'Reply', 'Spam', 'Delete', and 'Trash'.
WP_Comment $comment The comment object.
Definition at line 574 of file dashboard.php.
References $comment, $GLOBALS, $link, __, _draft_or_post_title(), author, comment, current_user_can(), dashboard, esc_attr__(), esc_html, esc_url, get_edit_post_link(), label, and spam.
Referenced by wp_ajax_replyto_comment().
dashboard_browser_nag_class ($classes)
Since
3.2.0
Parameters
array $classes
Returns
array
Definition at line 1335 of file dashboard.php.
wp_add_dashboard_widget ($widget_id, $widget_name, $callback, $control_callback = null, $callback_args = null)
array $wp_dashboard_control_callbacks
Parameters
string $widget_id
string $widget_name
callable $callback
callable $control_callback
array $callback_args
Definition at line 142 of file dashboard.php.
References $location, $screen, $url, __, add_meta_box(), add_query_arg(), current_user_can(), esc_url, and get_current_screen().
Referenced by GFForms\dashboard_setup(), and wp_dashboard_setup().
wp_check_browser_version ()
Check if the user needs a browser update.
Since
3.2.0
string $wp_version
Returns
array|bool False on failure, array of browser data on success.
Response should be an array with: 'name' - string - A user friendly browser name 'version' - string - The version of the browser the user is using 'current_version' - string - The most recent version of the browser 'upgrade' - boolean - Whether the browser needs an upgrade 'insecure' - boolean - Whether the browser is deemed insecure 'upgrade_url' - string - The url to visit to upgrade 'img_src' - string - An image representing the browser 'img_src_ssl' - string - An image (over SSL) representing the browser
Definition at line 1353 of file dashboard.php.
Referenced by wp_dashboard_setup().
wp_dashboard ()
Displays the dashboard.
Since
2.5.0
Definition at line 190 of file dashboard.php.
References $columns, $screen, absint(), do_meta_boxes(), get_current_screen(), and wp_nonce_field().
wp_dashboard_browser_nag ()
Filter the notice output for the 'Browse Happy' nag meta box.
Since
3.2.0
Parameters
string $notice The notice content.
array $response An array containing web browser information.
Definition at line 1282 of file dashboard.php.
References $msg.
wp_dashboard_cached_rss_widget ($widget_id, $callback, $check_urls = array())
Checks to see if all of the feed url in $check_urls are cached.
If $check_urls is empty, look for the rss feed url found in the dashboard widget options of $widget_id. If cached, call $callback, a function that echoes out output for this widget. If not cache, echo a "Loading..." stub which is later replaced by AJAX call (see top of /wp-admin/index.php)
Since
2.5.0
Parameters
string $widget_id
callable $callback
array $check_urls RSS feeds
Returns
bool False on failure. True on success.
Definition at line 920 of file dashboard.php.
wp_dashboard_empty ()
Empty function usable by plugins to output empty dashboard widget (to be populated later by JS).
Definition at line 1397 of file dashboard.php.
wp_dashboard_plugins_output ($rss, $args = array())
Display plugins text for the WordPress news widget.
Since
2.5.0
Parameters
string $rss The RSS feed URL.
array $args Array of arguments for this RSS feed.
Definition at line 1151 of file dashboard.php.
wp_dashboard_primary ()
WordPress News dashboard widget.
Since
2.7.0
Filter the primary link URL for the 'WordPress News' dashboard widget.
Since
2.5.0
Parameters
string $link The widget's primary link URL.
Filter the primary feed URL for the 'WordPress News' dashboard widget.
Since
2.3.0
Parameters
string $url The widget's primary feed URL.
Filter the primary link title for the 'WordPress News' dashboard widget.
Since
2.3.0
Parameters
string $title Title attribute for the widget's primary link.
Filter the secondary link URL for the 'WordPress News' dashboard widget.
Since
2.3.0
Parameters
string $link The widget's secondary link URL.
Filter the secondary feed URL for the 'WordPress News' dashboard widget.
Since
2.3.0
Parameters
string $url The widget's secondary feed URL.
Filter the secondary link title for the 'WordPress News' dashboard widget.
Since
2.3.0
Parameters
string $title Title attribute for the widget's secondary link.
Filter the number of secondary link items for the 'WordPress News' dashboard widget.
Since
4.4.0
Parameters
string $items How many items to show in the secondary feed.
Definition at line 1027 of file dashboard.php.
Referenced by wp_ajax_dashboard_widgets().
wp_dashboard_primary_output ($widget_id, $feeds)
Display the WordPress news feeds.
Since
3.8.0
Parameters
string $widget_id Widget ID.
array $feeds Array of RSS feeds.
Definition at line 1130 of file dashboard.php.
wp_dashboard_quick_press ($error_msg = false)
The Quick Draft widget display and creation of drafts.
Since
3.8.0
int $post_ID
Parameters
string $error_msg Optional. Error message. Default false.
This filter is documented in wp-admin/edit-form-advanced.php
Definition at line 449 of file dashboard.php.
References $post, $post_ID, $user_id, __, _e, apply_filters(), current_user_can(), endif, get_blogs_of_user(), get_current_blog_id(), get_current_user_id(), get_default_post_to_edit(), get_post(), get_user_option(), if, input, is_super_admin(), label, name, submit_button(), textarea, update_user_option(), wp_dashboard_recent_drafts(), and wp_nonce_field().
Referenced by wp_dashboard_quick_press_output().
wp_dashboard_quota ()
Display file upload quota on dashboard.
Runs on the activity_box_end hook in wp_dashboard_right_now().
Since
3.0.0
Returns
bool|null True if not multisite, user can't upload files, or the space check option is disabled.
Definition at line 1231 of file dashboard.php.
wp_dashboard_recent_comments ($total_items = 5)
Show Comments section.
Since
3.8.0
Parameters
int $total_items Optional. Number of comments to query. Default 5.
Returns
bool False if no comments were found. True otherwise.
Definition at line 843 of file dashboard.php.
wp_dashboard_recent_drafts ($drafts = false)
Show recent drafts of the user on the dashboard.
Since
2.7.0
Parameters
array $drafts
Filter the post query arguments for the 'Recent Drafts' dashboard widget.
Since
4.4.0
Parameters
array $query_args The query arguments for the 'Recent Drafts' dashboard widget.
Definition at line 520 of file dashboard.php.
References $title, $url, __, _draft_or_post_title(), _x, admin_url(), apply_filters(), esc_attr(), esc_html, esc_url, get_current_user_id(), get_edit_post_link(), get_posts(), get_the_time(), and wp_trim_words().
Referenced by wp_dashboard_quick_press().
wp_dashboard_recent_posts ($args)
Generates Publishing Soon and Recently Published sections.
Since
3.8.0
Parameters
array $args { An array of query and display arguments.
int $max Number of posts to display. string $status Post status. string $order Designates ascending ('ASC') or descending ('DESC') order. string $title Section title. string $id The container id. }
Returns
bool False if no posts were found. True otherwise.
Filter the query arguments used for the Recent Posts widget.
Since
4.2.0
Parameters
array $query_args The arguments passed to WP_Query to produce the list of posts.
Definition at line 758 of file dashboard.php.
wp_dashboard_right_now ()
Dashboard widget that displays some basic stats about the site.
Formerly 'Right Now'. A streamlined 'At a Glance' as of 3.8.
Since
2.7.0
Filter the array of extra elements to list in the 'At a Glance' dashboard widget.
Prior to 3.8.0, the widget was named 'Right Now'. Each element is wrapped in list-item tags on output.
Since
3.8.0
Parameters
array $items Array of extra 'At a Glance' widget items.
Filter the link title attribute for the 'Search Engines Discouraged' message displayed in the 'At a Glance' dashboard widget.
Prior to 3.8.0, the widget was named 'Right Now'.
Since
3.0.0
4.5.0 No title attribute output by default.
Parameters
string $title Default attribute text.
Filter the link label for the 'Search Engines Discouraged' message displayed in the 'At a Glance' dashboard widget.
Prior to 3.8.0, the widget was named 'Right Now'.
Since
3.0.0
Parameters
string $content Default text.
Fires at the end of the 'At a Glance' dashboard widget.
Prior to 3.8.0, the widget was named 'Right Now'.
Since
2.5.0
Fires at the end of the 'At a Glance' dashboard widget.
Prior to 3.8.0, the widget was named 'Right Now'.
Since
2.0.0
Definition at line 231 of file dashboard.php.
References $content, $post_type, $post_type_object, $text, $title, __, _n(), _nx(), apply_filters(), current_user_can(), do_action(), endif, get_option(), get_post_type_object(), is_network_admin(), is_user_admin(), label, li, number_format_i18n(), update_right_now_message(), wp_count_comments(), and wp_count_posts().
wp_dashboard_rss_control ($widget_id, $form_inputs = array())
The RSS dashboard widget control.
Sets up $args to be used as input to wp_widget_rss_form(). Handles POST data from RSS-type widgets.
Since
2.5.0
Parameters
string $widget_id
array $form_inputs
Definition at line 988 of file dashboard.php.
wp_dashboard_rss_output ($widget_id)
Display generic dashboard RSS widget feed.
Since
2.5.0
Parameters
string $widget_id
Definition at line 898 of file dashboard.php.
wp_dashboard_setup ()
Registers dashboard widgets.
Handles POST data, sets up filters.
Since
2.5.0
array $wp_registered_widgets array $wp_registered_widget_controls array $wp_dashboard_control_callbacks
Fires after core widgets for the Network Admin dashboard have been registered.
Since
3.1.0
Filter the list of widgets to load for the Network Admin dashboard.
Since
3.1.0
Parameters
array $dashboard_widgets An array of dashboard widgets.
Fires after core widgets for the User Admin dashboard have been registered.
Since
3.1.0
Filter the list of widgets to load for the User Admin dashboard.
Since
3.1.0
Parameters
array $dashboard_widgets An array of dashboard widgets.
Fires after core widgets for the admin dashboard have been registered.
Since
2.5.0
Filter the list of widgets to load for the admin dashboard.
Since
2.5.0
Parameters
array $dashboard_widgets An array of dashboard widgets.
This action is documented in wp-admin/edit-form-advanced.php
This action is documented in wp-admin/edit-form-advanced.php
Definition at line 20 of file dashboard.php.
References $_SERVER, $name, $screen, $wp_registered_widget_controls, $wp_registered_widgets, __, add_filter(), apply_filters(), current_user_can(), do_action(), elseif, exit, get_current_screen(), get_post_type_object(), is_blog_admin(), is_network_admin(), is_user_admin(), remove_query_arg(), wp_add_dashboard_widget(), wp_check_browser_version(), and wp_dashboard_trigger_widget_control().
wp_dashboard_site_activity ()
Callback function for Activity widget.
Since
3.8.0
Definition at line 711 of file dashboard.php.
wp_dashboard_trigger_widget_control ($widget_control_id = false)
Calls widget control callback.
Since
2.5.0
array $wp_dashboard_control_callbacks
Parameters
int $widget_control_id Registered Widget ID.
Definition at line 969 of file dashboard.php.
Referenced by _wp_dashboard_control_callback(), and wp_dashboard_setup().
wp_network_dashboard_right_now ()
Since
3.1.0
Fires in the Network Admin 'Right Now' dashboard widget just before the user and site search form fields.
Since
MU
Parameters
null $unused
Fires at the end of the 'Right Now' widget in the Network Admin dashboard.
Since
MU
Fires at the end of the 'Right Now' widget in the Network Admin dashboard.
Since
MU
Definition at line 368 of file dashboard.php.
References $action, $class, __, _e, _n(), current_user_can(), do_action(), get_blog_count(), get_user_count(), input, label, name, network_admin_url(), number_format_i18n(), size, and submit_button().
wp_welcome_panel ()
Displays a welcome panel to introduce users to WordPress.
Since
3.3.0
Definition at line 1404 of file dashboard.php.