GravityView: data-source.php File Reference
data-source.php File Reference
Namespaces
GravityView
GPL2+
Variables
$current_form = (int) \GV\Utils::_GET('form_id', gravityview_get_form_id($post->ID))
$forms = gravityview_get_forms('any', false, 'title')
Variable Documentation
$current_form
$current_form = (int) \GV\Utils::_GET('form_id', gravityview_get_form_id($post->ID))
Definition at line 13 of file data-source.php.
Referenced by GravityView_Field_Time\_get_time_format(), GravityView_Admin_Views\add_view_dropdown(), and GravityView_Admin_Metaboxes\get_data_source_header().
$forms
$forms = gravityview_get_forms('any', false, 'title')
Definition at line 19 of file data-source.php.
Referenced by GravityView_Widget_Gravity_Forms\_get_form_choices(), GravityView_Admin_Views\add_view_dropdown(), GravityView_API\entry_link(), GravityView_HTML_Elements\form_dropdown(), GravityView_Cache\get_cache_key_prefix(), GravityView_Admin_ApproveEntries\get_first_form_id(), GVCommon\get_forms(), View\get_joined_forms(), GravityView_Ajax\import_form(), Request\is_entry(), GravityView_Ajax\pre_get_form_fields(), and GravityView_Widget_Search\prepare_field_filter().