GravityView: default-constants.php File Reference
default-constants.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
wp_cookie_constants ()
Defines cookie related WordPress constants.
wp_functionality_constants ()
Defines functionality related WordPress constants.
wp_initial_constants ()
Defines initial WordPress constants.
wp_plugin_directory_constants ()
Defines plugin directory WordPress constants.
wp_ssl_constants ()
Defines cookie related WordPress constants.
wp_templating_constants ()
Defines templating related WordPress constants.
Function Documentation
wp_cookie_constants ()
Defines cookie related WordPress constants.
Defines constants after multisite is loaded.
Since
3.0.0
Used to guarantee unique hash cookies
Since
1.5.0
2.0.0
2.0.0
2.5.0
2.6.0
2.6.0
2.3.0
1.2.0
1.5.0
2.6.0
2.6.0
2.0.0
Definition at line 194 of file default-constants.php.
References get_option(), get_site_option(), and SITECOOKIEPATH.
Referenced by GravityView_Compatibility\check_gravityforms().
wp_functionality_constants ()
Defines functionality related WordPress constants.
Since
3.0.0
Since
2.5.0
2.9.0
3.3.0
Definition at line 307 of file default-constants.php.
wp_initial_constants ()
Defines initial WordPress constants.
See also
wp_debug_mode()
Since
3.0.0
int $blog_id
Private
#@+ Constants for expressing human-readable intervals in their respective number of seconds.
Please note that these values are approximate and are provided for convenience. For example, MONTH_IN_SECONDS wrongly assumes every month has 30 days and YEAR_IN_SECONDS does not take leap years into account.
If you need more accuracy please consider using the DateTime class (http://php.net/manual/class.datetime.php).
Since
3.5.0
4.4.0 Introduced MONTH_IN_SECONDS.
#@-
#@+ Constants for expressing human-readable data sizes in their respective number of bytes.
Since
4.4.0
#@-
Definition at line 17 of file default-constants.php.
References $blog_id, $GLOBALS, ABSPATH, is_multisite(), and WP_MEMORY_LIMIT.
wp_plugin_directory_constants ()
Defines plugin directory WordPress constants.
Defines must-use plugin directory constants, which may be overridden in the sunrise.php drop-in
Since
3.0.0
Allows for the plugins directory to be moved from the default location.
Since
2.6.0
Allows for the plugins directory to be moved from the default location.
Since
2.6.0
Allows for the plugins directory to be moved from the default location.
Since
2.1.0
Allows for the mu-plugins directory to be moved from the default location.
Since
2.8.0
Allows for the mu-plugins directory to be moved from the default location.
Since
2.8.0
Allows for the mu-plugins directory to be moved from the default location.
Since
2.8.0
Definition at line 133 of file default-constants.php.
References get_option(), and WP_CONTENT_DIR.
wp_ssl_constants ()
Defines cookie related WordPress constants.
Since
3.0.0
Since
2.6.0
2.6.0
Definition at line 280 of file default-constants.php.
References force_ssl_admin(), and get_option().
wp_templating_constants ()
Defines templating related WordPress constants.
Since
3.0.0
Filesystem path to the current active template directory
Since
1.5.0
Filesystem path to the current active template stylesheet directory
Since
2.1.0
Slug of the default theme for this install. Used as the default theme when installing new sites. It will be used as the fallback if the current theme doesn't exist.
Since
3.0.0
See also
WP_Theme::get_core_default_theme()
Definition at line 335 of file default-constants.php.
References get_stylesheet_directory(), and get_template_directory().