GravityView: delete_link.php File Reference
delete_link.php File Reference
Variables
$attributes
$gravityview_view = GravityView_View::getInstance()
array $entry array $form array $field_settings
$href = GravityView_Delete_Entry::get_delete_link($entry, $view_id)
if(!GravityView_Delete_Entry::check_user_cap_delete_entry($entry, $field_settings)) $link_text = empty($field_settings['delete_link']) ? __('Delete Entry', 'gravityview') : $field_settings['delete_link']
$view_id = $gravityview_view->getViewId()
Variable Documentation
$attributes
$attributes
Initial value:
= array(
    'onclick' => GravityView_Delete_Entry::get_confirm_dialog()
)
Definition at line 25 of file delete_link.php.
Referenced by GravityView_Delete_Entry\add_delete_button(), GV\as_html(), and View_Table_Template\the_entry().
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
array $entry array $form array $field_settings
Definition at line 8 of file delete_link.php.
Referenced by GravityView_API\directory_link(), GravityView_Widget_Search\enqueue_datepicker(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_API\field_label(), GravityView_Field_Notes\get_add_note_part(), GravityView_Field_FileUpload\get_files_array(), GravityView_Field_Notes\get_note_emails_array(), GravityView_Widget_Search\get_search_class(), GravityView_Widget_Search\get_search_filter_details(), GravityView_Widget_Search\get_search_form_action(), GravityView_Shortcode\get_view_detail(), gravityview_back_link(), Legacy_Context\load(), GravityView_API\no_results(), GravityView_Edit_Entry_Render\print_scripts(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Pagination_Info\render_frontend(), GravityView_Widget_Poll\render_frontend(), GravityView_Widget_Search\render_frontend(), GravityView_Edit_Entry_Render\setup_vars(), and GravityView_Widget_Search\the_clear_search_button().
$href
$href = GravityView_Delete_Entry::get_delete_link($entry, $view_id)
Definition at line 23 of file delete_link.php.
Referenced by GravityView_API\entry_link_html(), Admin\get_button(), GravityView_Admin_Installer\get_download_display_details(), GVCommon\get_link_html(), gravityview_back_link(), gravityview_get_link(), and Addon_Settings\modify_gform_settings_save_button().
$link_text
$link_text = empty($field_settings['delete_link']) ? __('Delete Entry', 'gravityview') : $field_settings['delete_link']
Definition at line 19 of file delete_link.php.
Referenced by gravityview_get_map_link(), GravityView_Support_Port\maybe_add_article_to_tooltip(), and GravityView_Entry_Link_Shortcode\shortcode().
$view_id
$view_id = $gravityview_view->getViewId()
Definition at line 10 of file delete_link.php.
Referenced by GravityView_View_Data\__construct(), View\_flush_cache(), GravityView_Admin_Bar\add_floaty_icon(), Field_Template\add_id_specific_templates(), GravityView_frontend\add_scripts_and_styles(), GravityView_View_Data\add_view(), gravityview\callback(), GravityView_Edit_Entry\check_user_cap_edit_entry(), View_Collection\contains(), GravityView_frontend\context_not_configured_warning(), GravityView_API\entry_link(), GravityView_Widget_Search\filter_entries(), GravityView_Search_WP_Widget\form(), View_Collection\get(), GVCommon\get_directory_widgets(), GravityView_Edit_Entry\get_edit_link(), GravityView_View_Data\get_fields(), get_gravityview(), GravityView_View_Data\get_id_from_atts(), Views_Route\get_item(), Views_Route\get_item_permissions_check(), GVCommon\get_meta_form_id(), GVCommon\get_meta_template_id(), GravityView_Edit_Entry\get_nonce_key(), Entry\get_permalink(), GravityView_Migrate\get_search_fields(), Views_Route\get_sub_item(), Views_Route\get_sub_item_permissions_check(), GravityView_View_Data\get_view(), gravityview_back_link(), gravityview_get_current_view_data(), gravityview_get_form_id(), gravityview_get_joined_forms(), GV\Mocks\GravityView_View_Data_add_view(), gv_container_class(), GravityView_View_Data\is_valid_embed_id(), oEmbed\parse_matches(), Views_Route\prepare_entry_for_response(), GravityView_frontend\set_context_view_id(), the_gravityview(), and GravityView_View_Data\view_exists().