GravityView: edit-form-comment.php File Reference
edit-form-comment.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$datef = __('M j, Y @ H:i')
$name = get_comment_author($parent)
$post_id = $comment->comment_post_ID
$quicktags_settings = array('buttons' => 'strong,em,link,block,del,ins,img,ul,ol,li,code,close')
$referer = wp_get_referer()
if(current_user_can('edit_post', $post_id)) else
endif
Variable Documentation
$datef = __('M j, Y @ H:i')
Definition at line 93 of file edit-form-comment.php.
Referenced by attachment_submit_meta_box(), post_submit_meta_box(), wp_post_revision_title(), and wp_post_revision_title_expanded().
$name = get_comment_author($parent)
Definition at line 132 of file edit-form-comment.php.
$post_id = $comment->comment_post_ID
Definition at line 110 of file edit-form-comment.php.
$quicktags_settings = array('buttons' => 'strong,em,link,block,del,ins,img,ul,ol,li,code,close')
Definition at line 68 of file edit-form-comment.php.
Referenced by edit_form_image_editor(), and wp_comment_reply().
$referer = wp_get_referer()
Definition at line 190 of file edit-form-comment.php.
Referenced by WP_Customize_Manager\get_return_url(), wp_media_attach_action(), and wp_nonce_field().
if (current_user_can('edit_post', $post_id)) else
Initial value:
{
    $post_link = esc_html( get_the_title( $post_id ) )
Definition at line 114 of file edit-form-comment.php.
if (!wp_is_mobile()) catch (e) endif
Definition at line 32 of file edit-form-comment.php.