GravityView: edit-tags.php File Reference
edit-tags.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$_SERVER ['REQUEST_URI'] = remove_query_arg(array('message', 'error'), $_SERVER['REQUEST_URI'])
$class = (isset($_REQUEST['error'])) ? 'error' : 'updated'
$location = false
$pagenum = $wp_list_table->get_pagenum()
if(!in_array($tax->name, get_taxonomies(array('show_ui'=> true)))) if(!current_user_can($tax->cap->manage_terms)) global $post_type
$post_type is set when the WP_Terms_List_Table instance is created
$referer = wp_get_referer()
$submenu_file = "edit-tags.php?taxonomy=$taxonomy"
$tax = get_taxonomy($taxnow)
$title = $tax->labels->name
$total_pages = $wp_list_table->get_pagination_arg('total_pages')
$wp_list_table = _get_list_table('WP_Terms_List_Table')
if('post'!=$post_type) elseif('link_category'==$tax->name) else
endif
if ('category'==$taxonomy|| 'link_category'==$taxonomy|| 'post_tag'==$taxonomy)
Also used by the Edit Tag form.
Variable Documentation
$_SERVER['REQUEST_URI'] = remove_query_arg(array('message', 'error'), $_SERVER['REQUEST_URI'])
Definition at line 320 of file edit-tags.php.
Referenced by WP_Plugins_List_Table\__construct(), GV_Unit_Tests_Bootstrap\__construct(), _device_can_upload(), wp_xmlrpc_server\_multisite_getUsersBlogs(), WP_Admin_Bar\_render(), _wp_customize_include(), _wp_customize_loader_settings(), _wp_menu_item_classes_by_context(), add_query_arg(), WP_Customize_Manager\after_setup_theme(), WP_Terms_List_Table\column_name(), WP_MS_Users_List_Table\column_username(), WP_Customize_Theme_Control\content_template(), WP_Session_Tokens\create(), GFFormsModel\create_lead(), _WP_Editors\editor_js(), WP_Customize_Nav_Menus\export_preview_data(), get_blogaddress_by_domain(), get_cli_args(), GFFormsModel\get_current_page_url(), GFFormDisplay\get_form(), get_home_path(), get_http_origin(), GFFormsModel\get_ip(), get_rest_url(), get_shortcut_link(), WP_UnitTestCase\go_to(), WP_Terms_List_Table\handle_row_actions(), WP_MS_Users_List_Table\handle_row_actions(), iis7_supports_permalinks(), WP_Customize_Manager\is_ios(), is_lighttpd_before_150(), is_ssl(), maybe_add_existing_user_to_blog(), media_upload_form(), network_step2(), new_user_email_admin_notice(), newblog_notify_siteadmin(), newuser_notify_siteadmin(), WP_List_Table\pagination(), WP\parse_request(), wp_xmlrpc_server\pingback_ping(), WP_List_Table\print_column_headers(), GFForms\process_exterior_pages(), redirect_canonical(), rest_cookie_check_errors(), SimplePie_Sanitize\sanitize(), GFFormsModel\save_lead(), self_link(), WP\send_headers(), send_origin_headers(), IXR_Server\serve(), WP_REST_Server\serve_request(), PHPMailer\serverHostname(), signup_nonce_check(), WP_Users_List_Table\single_row(), spawn_cron(), Tests_REST_API\test_rest_url_scheme(), trackback_rdf(), GFAsyncUpload\upload(), user_can_richedit(), GF_Field_CAPTCHA\validate(), wp_admin_bar_customize_menu(), wp_admin_canonical_url(), wp_ajax_wp_compression_test(), wp_auth_check_html(), wp_cron(), wp_dashboard_setup(), wp_favicon_request(), wp_fix_server_vars(), wp_get_raw_referer(), wp_get_referer(), wp_get_server_protocol(), wp_guess_url(), wp_is_mobile(), wp_login_form(), wp_magic_quotes(), wp_new_comment(), wp_original_referer_field(), wp_plupload_default_settings(), wp_prepare_themes_for_js(), wp_print_media_templates(), wp_redirect_admin_locations(), wp_referer_field(), wp_unregister_GLOBALS(), wpmu_admin_do_redirect(), wpmu_log_new_registrations(), wpmu_signup_blog_notification(), wpmu_signup_user_notification(), wpmu_welcome_notification(), and wpmu_welcome_user_notification().
$class = (isset($_REQUEST['error'])) ? 'error' : 'updated'
Definition at line 302 of file edit-tags.php.
$location = false
Definition at line 62 of file edit-tags.php.
Referenced by SimplePie_File\__construct(), SimplePie_Cache_MySQL\__construct(), SimplePie_Cache_Memcache\__construct(), _wp_check_split_nav_menu_terms(), GFFormDisplay\add_init_script(), WP_Customize_Nav_Menu_Control\content_template(), WP_Feed_Cache\create(), SimplePie_Cache\create(), WP_Customize_Nav_Menus\customize_register(), get_edit_bookmark_link(), get_edit_comment_link(), get_edit_term_link(), SimplePie_Cache\get_handler(), GravityView_Compatibility\get_plugin_status(), GravityView_Admin\get_plugin_status(), has_nav_menu(), register_nav_menu(), SimplePie\set_cache_location(), unregister_nav_menu(), wp_add_dashboard_widget(), wp_delete_nav_menu(), wp_load_translations_early(), and wp_media_attach_action().
$pagenum = $wp_list_table->get_pagenum()
Definition at line 40 of file edit-tags.php.
if (!in_array($tax->name, get_taxonomies(array('show_ui'=> true)))) if (!current_user_can($tax->cap->manage_terms)) global $post_type
$post_type is set when the WP_Terms_List_Table instance is created
string $post_type
Definition at line 24 of file edit-tags.php.
$referer = wp_get_referer()
Definition at line 63 of file edit-tags.php.
$submenu_file = "edit-tags.php?taxonomy=$taxonomy"
Definition at line 52 of file edit-tags.php.
$tax = get_taxonomy($taxnow)
Definition at line 15 of file edit-tags.php.
Referenced by WP_Terms_List_Table\__construct(), _post_format_request(), _wp_batch_split_terms(), WP_Terms_List_Table\column_posts(), WP_Canonical_UnitTestCase\delete_shared_fixtures(), edit_term_link(), WP_Widget_Tag_Cloud\form(), get_edit_term_link(), get_taxonomy_labels(), get_the_archive_title(), WP_Terms_List_Table\handle_row_actions(), WP_Terms_List_Table\inline_edit(), WP_UnitTestCase\reset_taxonomies(), WP_Widget_Tag_Cloud\widget(), wp_admin_bar_edit_menu(), wp_ajax_add_tag(), wp_ajax_ajax_tag_search(), wp_ajax_delete_tag(), wp_ajax_get_tagcloud(), wp_ajax_inline_save_tax(), wp_nav_menu_taxonomy_meta_boxes(), wp_popular_terms_checklist(), wp_terms_checklist(), wp_title(), and wp_update_term_count().
$title = $tax->labels->name
Definition at line 42 of file edit-tags.php.
$total_pages = $wp_list_table->get_pagination_arg('total_pages')
Definition at line 216 of file edit-tags.php.
Referenced by WP_List_Table\pagination(), and GFPaymentStatsTable\pagination().
$wp_list_table = _get_list_table('WP_Terms_List_Table')
Definition at line 39 of file edit-tags.php.
if (is_plugin_active('wpcat2tag-importer/wpcat2tag-importer.php')) else
Initial value:
{
    $parent_file = 'edit.php'
Definition at line 50 of file edit-tags.php.
if (!is_null($tax->labels->popular_items)) if (current_user_can($tax->cap->edit_terms)) if (!wp_is_mobile()) catch (e) endif
Definition at line 321 of file edit-tags.php.
s&</h1> if($message) ('category' = =$taxonomy|| 'link_category'==$taxonomy|| 'post_tag'==$taxonomy)
Also used by the Edit Tag form.
Definition at line 227 of file edit-tags.php.