GravityView: edit_link.php File Reference
edit_link.php File Reference
Variables
$gravityview_view = GravityView_View::getInstance()
$href = GravityView_Edit_Entry::get_edit_link($entry, $view_id)
$link_atts = empty($field_settings['new_window']) ? '' : 'target="_blank"'
if(!GravityView_Edit_Entry::check_user_cap_edit_entry($entry)) $link_text = empty($field_settings['edit_link']) ? __('Edit Entry', 'gk-gravityview') : $field_settings['edit_link']
$output = apply_filters('gravityview_entry_link', GravityView_API::replace_variables($link_text, $form, $entry))
$view_id = $gravityview_view->getViewId()
Variable Documentation
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Definition at line 3 of file edit_link.php.
$href
$href = GravityView_Edit_Entry::get_edit_link($entry, $view_id)
Definition at line 20 of file edit_link.php.
$link_atts
$link_atts = empty($field_settings['new_window']) ? '' : 'target="_blank"'
Definition at line 16 of file edit_link.php.
Referenced by GravityView_Lightbox_Provider_FancyBox\fileupload_link_atts(), GravityView_Lightbox_Provider\fileupload_link_atts(), GravityView_Field_FileUpload\get_files_array(), GravityView_Entry_Link_Shortcode\get_link_atts(), Field_Template\render(), and GravityView_Entry_Link_Shortcode\shortcode().
$link_text
if (!GravityView_Edit_Entry::check_user_cap_edit_entry($entry)) $link_text = empty($field_settings['edit_link']) ? __('Edit Entry', 'gk-gravityview') : $field_settings['edit_link']
Definition at line 14 of file edit_link.php.
$output
$output = apply_filters('gravityview_entry_link', GravityView_API::replace_variables($link_text, $form, $entry))
Definition at line 18 of file edit_link.php.
Referenced by GravityView_Field_Consent\__construct(), GravityView_Admin_Views\add_custom_column_content(), GravityView_Change_Entry_Creator\add_select(), GravityView_Admin_Notices\admin_notice(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), gvfield\callback(), gvlogic\callback(), GravityView_frontend\context_not_configured_warning(), gravityview\detail(), GravityView_Field_Notes\display_note(), GravityView_API\entry_link_html(), WPUpgraderSkin\error(), GravityView_HTML_Elements\field_dropdown(), GravityView_Edit_Entry_Render\fill_post_template(), GravityView_frontend\filter_no_entries_output(), GravityView_HTML_Elements\form_dropdown(), GravityView_Admin_Views\get_connected_form_links(), GravityView_Field_Payment_Amount\get_content(), GravityView_Field_Is_Fulfilled\get_content(), GravityView_Field_Transaction_Type\get_content(), GravityView_Field_Date_Created\get_content(), GravityView_Field_Date_Updated\get_content(), GravityView_Field_Is_Starred\get_content(), GravityView_Admin_Metaboxes\get_data_source_header(), GravityView_Field_Notes\get_email_footer(), GravityView_Admin_View_Item\get_item_info(), GVCommon\get_link_html(), GravityView_Entry_List\get_output(), GVCommon\get_sortable_fields(), gravityview_convert_value_to_term_list(), gravityview_get_the_term_list(), gv_selected(), GVCommon\js_encrypt(), Renderer\maybe_print_configuration_notice(), Renderer\maybe_print_reserved_slugs_notice(), GravityView_Field_Unsubscribe\modify_entry_value_unsubscribe(), GravityView_Field_Workflow_Final_Status\modify_entry_value_workflow_final_status(), GravityView_Field_Workflow_Step\modify_entry_value_workflow_step(), GravityView_API\no_results(), GravityView_Admin\no_views_text(), GravityView_Entry_List\output(), GravityView_Plugin_Hooks_Pageviews\pageviews(), Views_Route\prepare_entry_for_response(), GravityView_Field_Section\prevent_empty_field(), Field_Template\render(), GravityView_Admin_Views\render_available_fields(), GravityView_Render_Settings\render_checkbox_option(), GravityView_Admin_Views\render_directory_active_areas(), GravityView_Render_Settings\render_field_option(), GravityView_Render_Settings\render_field_options(), GravityView_Widget_Pagination_Info\render_frontend(), oEmbed\render_frontend(), GravityView_Admin_Metaboxes\render_merge_tags_scripts(), GravityView_Widget_Search\render_searchable_fields(), GravityView_Render_Settings\render_select_option(), GravityView_Render_Settings\render_setting_row(), GravityView_Admin_Views\render_widgets_active_areas(), GravityView_View\renderZone(), GravityView_HTML_Elements\select(), and GravityView_Recent_Entries_Widget\widget().
$view_id
$view_id = $gravityview_view->getViewId()
Definition at line 5 of file edit_link.php.