GravityView: embed.php File Reference
embed.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_oembed_create_xml ($data, $node=null)
Creates an XML string from a given array.
_oembed_rest_pre_serve_request ($served, $result, $request, $server)
Hooks into the REST API output to print XML instead of JSON.
enqueue_embed_scripts ()
Enqueue embed iframe default CSS and JS & fire do_action('enqueue_embed_scripts')
get_oembed_endpoint_url ($permalink= '', $format= 'json')
Retrieves the oEmbed endpoint URL for a given permalink.
get_oembed_response_data ($post, $width)
Retrieves the oEmbed response data for a given post.
get_oembed_response_data_rich ($data, $post, $width, $height)
Filters the oEmbed response data to return an iframe embed code.
get_post_embed_html ($width, $height, $post=null)
Retrieves the embed code for a specific post.
get_post_embed_url ($post=null)
Retrieves the URL to embed a specific post in an iframe.
print_embed_styles ()
Prints the CSS in the embed iframe header.
the_excerpt_embed ()
Displays the post excerpt for the embed template.
wp_embed_defaults ($url= '')
Creates default array of embed parameters.
wp_embed_excerpt_attachment ($content)
Filters the post excerpt for the embed template.
wp_embed_excerpt_more ($more_string)
Filters the string in the 'more' link displayed after a trimmed excerpt.
wp_embed_handler_audio ($matches, $attr, $url, $rawattr)
Audio embed handler callback.
wp_embed_handler_googlevideo ($matches, $attr, $url, $rawattr)
The Google Video embed handler callback.
wp_embed_handler_video ($matches, $attr, $url, $rawattr)
Video embed handler callback.
wp_embed_handler_youtube ($matches, $attr, $url, $rawattr)
YouTube iframe embed handler callback.
wp_embed_register_handler ($id, $regex, $callback, $priority=10)
Registers an embed handler.
wp_embed_unregister_handler ($id, $priority=10)
Unregisters a previously-registered embed handler.
wp_filter_oembed_result ($result, $data, $url)
Filters the given oEmbed HTML.
wp_maybe_load_embeds ()
Determines if default embed handlers should be loaded.
wp_oembed_add_discovery_links ()
Adds oEmbed discovery links in the website <head>.
wp_oembed_add_host_js ()
Adds the necessary JavaScript to communicate with the embedded iframes.
wp_oembed_add_provider ($format, $provider, $regex=false)
Adds a URL format and oEmbed provider URL pair.
wp_oembed_ensure_format ($format)
Ensures that the specified format is either 'json' or 'xml'.
wp_oembed_get ($url, $args= '')
Attempts to fetch the embed HTML for a provided URL using oEmbed.
wp_oembed_register_route ()
Registers the oEmbed REST API route.
wp_oembed_remove_provider ($format)
Removes an oEmbed provider.
Function Documentation
_oembed_create_xml ($data, $node = null)
Creates an XML string from a given array.
Since
4.4.0 private
Parameters
array $data The original oEmbed response data.
SimpleXMLElement $node Optional. XML node to append the result to recursively.
Returns
string|false XML string on success, false on error.
Definition at line 698 of file embed.php.
References $value, esc_html, and null.
Referenced by _oembed_rest_pre_serve_request().
_oembed_rest_pre_serve_request ($served, $result, $request, $server)
Hooks into the REST API output to print XML instead of JSON.
This is only done for the oEmbed API endpoint, which supports both formats.
private
Since
4.4.0
Parameters
bool $served Whether the request has already been served.
WP_HTTP_ResponseInterface $result Result to send to the client. Usually a WP_REST_Response.
WP_REST_Request $request Request used to generate the response.
WP_REST_Server $server Server instance.
Returns
true
Definition at line 652 of file embed.php.
References _oembed_create_xml(), get_option(), get_status_header_desc(), and status_header().
enqueue_embed_scripts ()
Enqueue embed iframe default CSS and JS & fire do_action('enqueue_embed_scripts')
Enqueue PNG fallback CSS for embed iframe for legacy versions of IE.
Allows plugins to queue scripts for the embed iframe end using wp_enqueue_script(). Runs first in oembed_head().
Since
4.4.0
Fires when scripts and styles are enqueued for the embed iframe.
Since
4.4.0
Definition at line 871 of file embed.php.
References do_action(), and wp_enqueue_style().
get_oembed_endpoint_url ($permalink = '', $format = 'json')
Retrieves the oEmbed endpoint URL for a given permalink.
Pass an empty string as the first argument to get the endpoint base URL.
Since
4.4.0
Parameters
string $permalink Optional. The permalink used for the url query arg. Default empty.
string $format Optional. The requested response format. Default 'json'.
Returns
string The oEmbed endpoint URL.
Filter the oEmbed endpoint URL.
Since
4.4.0
Parameters
string $url The URL to the oEmbed endpoint.
string $permalink The permalink used for the url query arg.
string $format The requested response format.
Definition at line 418 of file embed.php.
References $format, $permalink, $url, add_query_arg(), apply_filters(), and rest_url().
Referenced by wp_oembed_add_discovery_links().
get_oembed_response_data ($post, $width)
Retrieves the oEmbed response data for a given post.
Since
4.4.0
Parameters
WP_Post | int $post Post object or ID.
int $width The requested width.
Returns
array|false Response data on success, false if post doesn't exist.
Filter the allowed minimum and maximum widths for the oEmbed response.
Since
4.4.0
Parameters
array $min_max_width { Minimum and maximum widths for the oEmbed response.
int $min Minimum width. Default 200. int $max Maximum width. Default 600. }
Filter the oEmbed response data.
Since
4.4.0
Parameters
array $data The response data.
WP_Post $post The post object.
int $width The requested width.
int $height The calculated height.
Definition at line 517 of file embed.php.
References $post, apply_filters(), get_author_posts_url(), get_bloginfo(), get_home_url(), get_post(), and get_post_status().
Referenced by WP_oEmbed_Controller\get_item().
get_oembed_response_data_rich ($data, $post, $width, $height)
Filters the oEmbed response data to return an iframe embed code.
Since
4.4.0
Parameters
array $data The response data.
WP_Post $post The post object.
int $width The requested width.
int $height The calculated height.
Returns
array The modified response data.
Definition at line 589 of file embed.php.
References $post, $thumbnail_id, absint(), get_post_embed_html(), get_post_thumbnail_id(), get_post_type(), has_post_thumbnail(), wp_attachment_is(), wp_attachment_is_image(), and wp_get_attachment_image_src().
get_post_embed_html ($width, $height, $post = null)
Retrieves the embed code for a specific post.
Since
4.4.0
Parameters
int $width The width for the response.
int $height The height for the response.
int | WP_Post $post Optional. Post ID or object. Default is global $post.
Returns
string|false Embed code on success, false if post doesn't exist.
Filter the embed HTML output for a given post.
Since
4.4.0
Parameters
string $output The default HTML.
WP_Post $post Current post object.
int $width Width of the response.
int $height Height of the response.
Definition at line 454 of file embed.php.
References $output, $post, a, ABSPATH, esc_url, get_permalink(), get_post(), get_post_embed_url(), get_the_title(), and WPINC.
Referenced by get_oembed_response_data_rich().
get_post_embed_url ($post = null)
Retrieves the URL to embed a specific post in an iframe.
Since
4.4.0
Parameters
int | WP_Post $post Optional. Post ID or object. Defaults to the current post.
Returns
string|false The post embed URL on success, false if the post doesn't exist.
Filter the URL to embed a specific post.
Since
4.4.0
Parameters
string $embed_url The post embed URL.
WP_Post $post The corresponding post object.
Definition at line 383 of file embed.php.
References $post, add_query_arg(), apply_filters(), esc_url_raw(), get_option(), get_permalink(), get_post(), trailingslashit(), and user_trailingslashit().
Referenced by get_post_embed_html().
print_embed_styles ()
Prints the CSS in the embed iframe header.
Since
4.4.0
Prints the JavaScript in the embed iframe header.
Since
4.4.0
Prepare the oembed HTML to be displayed in an RSS feed.
Since
4.4.0 private
Parameters
string $content The content to filter.
Returns
string The filtered content.
Prints the necessary markup for the embed comments button.
Since
4.4.0
Prints the necessary markup for the embed sharing button.
Since
4.4.0
Prints the necessary markup for the embed sharing dialog.
Since
4.4.0
Definition at line 888 of file embed.php.
References a, ABSPATH, align, clip, color, comments, decoration, family, height, image, input, margin, outline, radius, selected(), serif, shadow, site, size, sizing, space, textarea, transform, width, and WPINC.
the_excerpt_embed ()
Displays the post excerpt for the embed template.
Intended to be used in 'The Loop'.
Since
4.4.0
Filter the post excerpt for the embed template.
Since
4.4.0
Parameters
string $output The current post excerpt.
Definition at line 830 of file embed.php.
References $output, apply_filters(), and get_the_excerpt().
wp_embed_defaults ($url = '')
Creates default array of embed parameters.
The width defaults to the content width as specified by the theme. If the theme does not specify a content width, then 500px is used.
The default height is 1.5 times the width, or 1000px, whichever is smaller.
The 'embed_defaults' filter can be used to adjust either of these values.
Since
2.9.0
int $content_width
Parameters
string $url Optional. The URL that should be embedded. Default empty.
Returns
array Default embed parameters.
Filter the default array of embed dimensions.
Since
2.9.0
Parameters
array $size An array of embed width and height values in pixels (in that order).
string $url The URL that should be embedded.
Definition at line 63 of file embed.php.
References $GLOBALS, $url, and apply_filters().
Referenced by WP_oEmbed\fetch(), and WP_Embed\shortcode().
wp_embed_excerpt_attachment ($content)
Filters the post excerpt for the embed template.
Shows players for video and audio attachments.
Since
4.4.0
Parameters
string $content The current post excerpt.
Returns
string The modified post excerpt.
Definition at line 853 of file embed.php.
References $content, is_attachment(), and prepend_attachment().
wp_embed_excerpt_more ($more_string)
Filters the string in the 'more' link displayed after a trimmed excerpt.
Replaces '[...]' (appended to automatically generated excerpts) with an ellipsis and a "Continue reading" link in the embed template.
Since
4.4.0
Parameters
string $more_string Default 'more' string.
Returns
string 'Continue reading' link prepended with an ellipsis.
Definition at line 810 of file embed.php.
References $link, __, esc_url, get_permalink(), get_the_title(), and is_embed().
wp_embed_handler_audio ($matches, $attr, $url, $rawattr)
Audio embed handler callback.
Since
3.6.0
Parameters
array $matches The RegEx matches from the provided regex when calling wp_embed_register_handler().
array $attr Embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Returns
string The embed HTML.
Filter the audio embed output.
Since
3.6.0
Parameters
string $audio Audio embed output.
array $attr An array of embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Definition at line 282 of file embed.php.
References $url, apply_filters(), and esc_url.
wp_embed_handler_googlevideo ($matches, $attr, $url, $rawattr)
The Google Video embed handler callback.
Google Video does not support oEmbed.
See also
WP_Embed::register_handler()
WP_Embed::shortcode()
Parameters
array $matches The RegEx matches from the provided regex when calling wp_embed_register_handler().
array $attr Embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Returns
string The embed HTML.
Filter the Google Video embed output.
Since
2.9.0
Parameters
string $html Google Video HTML embed markup.
array $matches The RegEx matches from the provided regex.
array $attr An array of embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Definition at line 213 of file embed.php.
References $url, apply_filters(), esc_attr(), and wp_expand_dimensions().
wp_embed_handler_video ($matches, $attr, $url, $rawattr)
Video embed handler callback.
Since
3.6.0
Parameters
array $matches The RegEx matches from the provided regex when calling wp_embed_register_handler().
array $attr Embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Returns
string The embed HTML.
Filter the video embed output.
Since
3.6.0
Parameters
string $video Video embed output.
array $attr An array of embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Definition at line 309 of file embed.php.
References $url, apply_filters(), and esc_url.
wp_embed_handler_youtube ($matches, $attr, $url, $rawattr)
YouTube iframe embed handler callback.
Catches YouTube iframe embed URLs that are not parsable by oEmbed but can be translated into a URL that is.
Since
4.0.0
WP_Embed $wp_embed
Parameters
array $matches The RegEx matches from the provided regex when calling wp_embed_register_handler().
array $attr Embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Returns
string The embed HTML.
Filter the YoutTube embed output.
Since
4.0.0
See also
wp_embed_handler_youtube()
Parameters
string $embed YouTube embed output.
array $attr An array of embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Definition at line 252 of file embed.php.
References $url, and apply_filters().
wp_embed_register_handler ($id, $regex, $callback, $priority = 10)
Registers an embed handler.
Should probably only be used for sites that do not support oEmbed.
Since
2.9.0
WP_Embed $wp_embed
Parameters
string $id An internal ID/name for the handler. Needs to be unique.
string $regex The regex that will be used to see if this handler should be used for a URL.
callable $callback The callback function that will be called if the regex is matched.
int $priority Optional. Used to specify the order in which the registered handlers will be tested. Default 10.
Definition at line 25 of file embed.php.
References $id.
Referenced by GravityView_oEmbed\register_handler(), and wp_maybe_load_embeds().
wp_embed_unregister_handler ($id, $priority = 10)
Unregisters a previously-registered embed handler.
Since
2.9.0
WP_Embed $wp_embed
Parameters
string $id The handler ID that should be removed.
int $priority Optional. The priority of the handler to be removed. Default 10.
Definition at line 40 of file embed.php.
References $id.
wp_filter_oembed_result ($result, $data, $url)
Filters the given oEmbed HTML.
If the $url isn't on the trusted providers list, we need to filter the HTML heavily for security.
Only filters 'rich' and 'html' response types.
Since
4.4.0
Parameters
string $result The oEmbed HTML result.
object $data A data object result from an oEmbed provider.
string $url The URL of the content to be embedded.
Returns
string The filtered and sanitized oEmbed result.
Definition at line 738 of file embed.php.
References $content, $url, _wp_oembed_get_object(), ABSPATH, esc_url, str_replace, wp_kses(), and WPINC.
wp_maybe_load_embeds ()
Determines if default embed handlers should be loaded.
Checks to make sure that the embeds library hasn't already been loaded. If it hasn't, then it will load the embeds library.
Since
2.9.0
See also
wp_embed_register_handler()
Filter whether to load the default embed handlers.
Returning a falsey value will prevent loading the default embed handlers.
Since
2.9.0
Parameters
bool $maybe_load_embeds Whether to load the embeds library. Default true.
Filter the audio embed handler callback.
Since
3.6.0
Parameters
callable $handler Audio embed handler callback function.
Filter the video embed handler callback.
Since
3.6.0
Parameters
callable $handler Video embed handler callback function.
Definition at line 162 of file embed.php.
References apply_filters(), wp_embed_register_handler(), wp_get_audio_extensions(), and wp_get_video_extensions().
wp_oembed_add_discovery_links ()
Adds oEmbed discovery links in the website <head>.
Since
4.4.0
Filter the oEmbed discovery links HTML.
Since
4.4.0
Parameters
string $output HTML of the discovery links.
Definition at line 345 of file embed.php.
References $output, apply_filters(), esc_url, get_oembed_endpoint_url(), get_permalink(), is_front_page(), and is_singular().
wp_oembed_add_host_js ()
Adds the necessary JavaScript to communicate with the embedded iframes.
Since
4.4.0
Definition at line 371 of file embed.php.
References wp_enqueue_script().
wp_oembed_add_provider ($format, $provider, $regex = false)
Adds a URL format and oEmbed provider URL pair.
Since
2.9.0
See also
WP_oEmbed
Parameters
string $format The format of URL that this provider can handle. You can use asterisks as wildcards.
string $provider The URL to the oEmbed provider.
boolean $regex Optional. Whether the $format parameter is in a RegEx format. Default false.
Definition at line 114 of file embed.php.
References $format, WP_oEmbed\_add_provider_early(), _wp_oembed_get_object(), ABSPATH, did_action(), and WPINC.
wp_oembed_ensure_format ($format)
Ensures that the specified format is either 'json' or 'xml'.
Since
4.4.0
Parameters
string $format The oEmbed response format. Accepts 'json' or 'xml'.
Returns
string The format, either 'xml' or 'json'. Default 'json'.
Definition at line 629 of file embed.php.
References $format.
wp_oembed_get ($url, $args = '')
Attempts to fetch the embed HTML for a provided URL using oEmbed.
Since
2.9.0
See also
WP_oEmbed
Parameters
string $url The URL that should be embedded.
array $args Optional. Additional arguments and parameters for retrieving embed HTML. Default empty.
Returns
false|string False on failure or the embed HTML on success.
Definition at line 96 of file embed.php.
References $url, _wp_oembed_get_object(), ABSPATH, and WPINC.
Referenced by WP_Embed\shortcode().
wp_oembed_register_route ()
Registers the oEmbed REST API route.
Since
4.4.0
Definition at line 335 of file embed.php.
wp_oembed_remove_provider ($format)
Removes an oEmbed provider.
Since
3.5.0
See also
WP_oEmbed
Parameters
string $format The URL format for the oEmbed provider to remove.
Returns
bool Was the provider removed successfully?
Definition at line 135 of file embed.php.
References $format, WP_oEmbed\_remove_provider_early(), _wp_oembed_get_object(), ABSPATH, did_action(), and WPINC.