GravityView: feed.php File Reference
feed.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
atom_enclosure ()
Display the atom enclosure for the current post.
atom_site_icon ()
Displays Site Icon in atom feeds.
bloginfo_rss ($show= '')
Display RSS container for the bloginfo function.
comment_author_rss ()
Display the current comment author in the feed.
comment_guid ($comment_id=null)
Display the feed GUID for the current comment.
comment_link ($comment=null)
Display the link to the comments.
comment_text_rss ()
Display the current comment content for use in the feeds.
comments_link_feed ()
Outputs the link to the comments for the current post in an xml safe way.
feed_content_type ($type= '')
Return the content type for specified feed type.
fetch_feed ($url)
Build SimplePie object based on RSS or Atom feed from URL.
get_bloginfo_rss ($show= '')
RSS container for the bloginfo function.
get_comment_author_rss ()
Retrieve the current comment author for use in the feeds.
get_comment_guid ($comment_id=null)
Retrieve the feed GUID for the current comment.
get_default_feed ()
Retrieve the default feed.
get_the_category_rss ($type=null)
Retrieve all of the post categories, formatted for use in feeds.
get_the_content_feed ($feed_type=null)
Retrieve the post content for feeds.
get_the_title_rss ()
Retrieve the current post title for the feed.
get_wp_title_rss ($deprecated= '&#8211;')
Retrieve the blog title for the feed title.
html_type_rss ()
Display the HTML type based on the blog setting.
prep_atom_text_construct ($data)
Determine the type of a string of data with the data formatted.
rss2_site_icon ()
Displays Site Icon in RSS2.
rss_enclosure ()
Display the rss enclosure for the current post.
self_link ()
Display the link for the currently displayed feed in a XSS safe way.
the_category_rss ($type=null)
Display the post categories in the feed.
the_content_feed ($feed_type=null)
Display the post content for feeds.
the_excerpt_rss ()
Display the post excerpt for the feed.
the_permalink_rss ()
Display the permalink to the post for use in feeds.
the_title_rss ()
Display the post title in the feed.
wp_title_rss ($deprecated= '&#8211;')
Display the blog title for display of the feed title.
Function Documentation
atom_enclosure ()
Display the atom enclosure for the current post.
Uses the global $post to check whether the post requires a password and if the user has the password for the post. If not then it will return before displaying.
Also uses the function get_post_custom() to get the post's 'enclosure' metadata field and parses the value to display the enclosure(s). The enclosure(s) consist of link HTML tag(s) with a URI and other attributes.
Since
2.2.0
Filter the atom enclosure HTML link tag for the current post.
Since
2.2.0
Parameters
string $html_link_tag The HTML link tag with a URI and other attributes.
Definition at line 497 of file feed.php.
References apply_filters(), get_post_custom(), and post_password_required().
atom_site_icon ()
Displays Site Icon in atom feeds.
Since
4.3.0
See also
get_site_icon_url()
Definition at line 568 of file feed.php.
References $url, and get_site_icon_url().
bloginfo_rss ($show = '')
Display RSS container for the bloginfo function.
You can retrieve anything that you can using the get_bloginfo() function. Everything will be stripped of tags and characters converted, when the values are retrieved for use in the feeds.
Since
0.71
See also
get_bloginfo() For the list of possible values to display.
Parameters
string $show See get_bloginfo() for possible values.
Filter the bloginfo for display in RSS feeds.
Since
2.1.0
See also
get_bloginfo()
Parameters
string $rss_container RSS container for the blog information.
string $show The type of blog information to retrieve.
Definition at line 53 of file feed.php.
References apply_filters(), and get_bloginfo_rss().
comment_author_rss ()
Display the current comment author in the feed.
Since
1.0.0
Definition at line 339 of file feed.php.
References get_comment_author_rss().
comment_guid ($comment_id = null)
Display the feed GUID for the current comment.
Since
2.5.0
Parameters
int | WP_Comment $comment_id Optional comment object or id. Defaults to global comment object.
Definition at line 272 of file feed.php.
References esc_url, and get_comment_guid().
comment_link ($comment = null)
Display the link to the comments.
Since
1.5.0
4.4.0 Introduced the $comment argument.
Parameters
int | WP_Comment $comment Optional. Comment object or id. Defaults to global comment object.
Filter the current comment's permalink.
Since
3.6.0
See also
get_comment_link()
Parameters
string $comment_permalink The current comment permalink.
Definition at line 301 of file feed.php.
References $comment, apply_filters(), esc_url, and get_comment_link().
comment_text_rss ()
Display the current comment content for use in the feeds.
Since
1.0.0
Filter the current comment content for use in a feed.
Since
1.5.0
Parameters
string $comment_text The content of the current comment.
Definition at line 348 of file feed.php.
References apply_filters(), and get_comment_text().
comments_link_feed ()
Outputs the link to the comments for the current post in an xml safe way.
Since
3.0.0
Returns
none
Filter the comments permalink for the current post.
Since
3.6.0
Parameters
string $comment_permalink The current comment permalink with 'comments' appended.
Definition at line 253 of file feed.php.
References apply_filters(), esc_url, and get_comments_link().
feed_content_type ($type = '')
Return the content type for specified feed type.
Since
2.8.0
Parameters
string $type Type of feed. Possible values include 'rss', rss2', 'atom', and 'rdf'.
Filter the content type for a specific feed type.
Since
2.8.0
Parameters
string $content_type Content type indicating the type of data that a feed contains.
string $type Type of feed. Possible values include 'rss', rss2', 'atom', and 'rdf'.
Definition at line 628 of file feed.php.
References $types, apply_filters(), and get_default_feed().
Referenced by feed_links(), feed_links_extra(), and WP\send_headers().
fetch_feed ($url)
Build SimplePie object based on RSS or Atom feed from URL.
Since
2.8.0
Parameters
mixed $url URL of feed to retrieve. If an array of URLs, the feeds are merged using SimplePie's multifeed feature. See also ​http://simplepie.org/wiki/faq/typical_multifeed_gotchas
Returns
WP_Error|SimplePie WP_Error object on failure or SimplePie object on success
This filter is documented in wp-includes/class-feed.php
Fires just before processing the SimplePie feed object.
Since
3.0.0
Parameters
object &$feed SimplePie feed object, passed by reference.
mixed $url URL of feed to retrieve. If an array of URLs, the feeds are merged.
Definition at line 663 of file feed.php.
References $url, ABSPATH, apply_filters(), do_action_ref_array(), get_option(), and WPINC.
Referenced by WP_Widget_RSS\widget(), wp_widget_rss_output(), and wp_widget_rss_process().
get_bloginfo_rss ($show = '')
RSS container for the bloginfo function.
You can retrieve anything that you can using the get_bloginfo() function. Everything will be stripped of tags and characters converted, when the values are retrieved for use in the feeds.
Since
1.5.1
See also
get_bloginfo() For the list of possible values to display.
Parameters
string $show See get_bloginfo() for possible values.
Returns
string
Filter the bloginfo for use in RSS feeds.
Since
2.2.0
See also
convert_chars()
get_bloginfo()
Parameters
string $info Converted string value of the blog information.
string $show The type of blog information to retrieve.
Definition at line 25 of file feed.php.
References apply_filters(), convert_chars(), and get_bloginfo().
Referenced by bloginfo_rss(), export_wp(), get_the_category_rss(), get_the_generator(), and rss2_site_icon().
get_comment_author_rss ()
Retrieve the current comment author for use in the feeds.
Since
2.0.0
Returns
string Comment Author
Filter the current comment author for use in a feed.
Since
1.5.0
See also
get_comment_author()
Parameters
string $comment_author The current comment author.
Definition at line 321 of file feed.php.
References apply_filters(), and get_comment_author().
Referenced by comment_author_rss().
get_comment_guid ($comment_id = null)
Retrieve the feed GUID for the current comment.
Since
2.5.0
Parameters
int | WP_Comment $comment_id Optional comment object or id. Defaults to global comment object.
Returns
false|string false on failure or guid for comment on success.
Definition at line 284 of file feed.php.
References $comment, get_comment(), and get_the_guid().
Referenced by comment_guid().
get_default_feed ()
Retrieve the default feed.
The default feed is 'rss2', unless a plugin changes it through the 'default_feed' filter.
Since
2.5.0
Returns
string Default feed, or for example 'rss2', 'atom', etc.
Filter the default feed type.
Since
2.5.0
Parameters
string $feed_type Type of default feed. Possible values include 'rss2', 'atom'. Default 'rss2'.
Definition at line 77 of file feed.php.
References apply_filters().
Referenced by do_feed(), feed_content_type(), feed_links(), get_author_feed_link(), get_feed_link(), get_post_comments_feed_link(), get_post_type_archive_feed_link(), get_search_comments_feed_link(), get_search_feed_link(), get_term_feed_link(), get_the_category_rss(), get_the_content_feed(), WP_Query\is_feed(), redirect_canonical(), and WP\send_headers().
get_the_category_rss ($type = null)
Retrieve all of the post categories, formatted for use in feeds.
All of the categories for the current post in the feed loop, will be retrieved and have feed markup added, so that they can easily be added to the RSS2, Atom, or RSS1 and RSS0.91 RDF feeds.
Since
2.1.0
Parameters
string $type Optional, default is the type returned by get_default_feed().
Returns
string All of the post categories for displaying in the feed.
Filter all of the post categories for display in a feed.
Since
1.2.0
Parameters
string $the_list All of the RSS post categories.
string $type Type of feed. Possible values include 'rss2', 'atom'. Default 'rss2'.
Definition at line 373 of file feed.php.
References $tags, apply_filters(), elseif, esc_attr(), get_bloginfo_rss(), get_default_feed(), get_option(), get_the_category(), get_the_tags(), and sanitize_term_field().
Referenced by the_category_rss().
get_the_content_feed ($feed_type = null)
Retrieve the post content for feeds.
Since
2.9.0
See also
get_the_content()
Parameters
string $feed_type The type of feed. rss2 | atom | rss | rdf
Returns
string The filtered content.
This filter is documented in wp-includes/post-template.php
Filter the post content for use in feeds.
Since
2.9.0
Parameters
string $content The current post content.
string $feed_type Type of feed. Possible values include 'rss2', 'atom'. Default 'rss2'.
Definition at line 184 of file feed.php.
References $content, apply_filters(), get_default_feed(), get_the_content(), and str_replace.
Referenced by the_content_feed().
get_the_title_rss ()
Retrieve the current post title for the feed.
Since
2.0.0
Returns
string Current post title.
Filter the post title for use in a feed.
Since
1.2.0
Parameters
string $title The current post title.
Definition at line 152 of file feed.php.
References $title, apply_filters(), and get_the_title().
Referenced by the_title_rss().
get_wp_title_rss ($deprecated = '&#8211;')
Retrieve the blog title for the feed title.
Since
2.2.0
4.4.0 The optional $sep parameter was deprecated and renamed to $deprecated.
Parameters
string $deprecated Unused..
Returns
string The document title.
Filter the blog title for use as the feed title.
Since
2.2.0
4.4.0 The $sep parameter was deprecated and renamed to $deprecated.
Parameters
string $title The current blog title.
string $deprecated Unused.
Definition at line 99 of file feed.php.
References $deprecated, __, _deprecated_argument(), apply_filters(), and wp_get_document_title().
Referenced by rss2_site_icon(), and wp_title_rss().
html_type_rss ()
Display the HTML type based on the blog setting.
The two possible values are either 'xhtml' or 'html'.
Since
2.2.0
Definition at line 435 of file feed.php.
References get_bloginfo().
prep_atom_text_construct ($data)
Determine the type of a string of data with the data formatted.
Tell whether the type is text, html, or xhtml, per RFC 4287 section 3.1.
In the case of WordPress, text is defined as containing no markup, xhtml is defined as "well formed", and html as tag soup (i.e., the rest).
Container div tags are added to xhtml values, per section 3.1.1.3.
2.5.0 string $data Input string array array(type, value)
Definition at line 535 of file feed.php.
rss2_site_icon ()
Displays Site Icon in RSS2.
Since
4.3.0
Definition at line 580 of file feed.php.
References $url, convert_chars(), get_bloginfo_rss(), get_site_icon_url(), and get_wp_title_rss().
rss_enclosure ()
Display the rss enclosure for the current post.
Uses the global $post to check whether the post requires a password and if the user has the password for the post. If not then it will return before displaying.
Also uses the function get_post_custom() to get the post's 'enclosure' metadata field and parses the value to display the enclosure(s). The enclosure(s) consist of enclosure HTML tag(s) with a URI and other attributes.
Since
1.5.0
Filter the RSS enclosure HTML link tag for the current post.
Since
2.2.0
Parameters
string $html_link_tag The HTML link tag with a URI and other attributes.
Definition at line 458 of file feed.php.
References apply_filters(), get_post_custom(), and post_password_required().
self_link ()
Display the link for the currently displayed feed in a XSS safe way.
Generate a correct link for the atom:self element.
Since
2.5.0
Filter the current feed URL.
Since
3.6.0
See also
set_url_scheme()
wp_unslash()
Parameters
string $feed_link The link for the feed with set URL scheme.
Definition at line 606 of file feed.php.
References $_SERVER, apply_filters(), esc_url, home_url(), set_url_scheme(), and wp_unslash().
the_category_rss ($type = null)
Display the post categories in the feed.
Since
0.71
See also
get_the_category_rss() For better explanation.
Parameters
string $type Optional, default is the type returned by get_default_feed().
Definition at line 424 of file feed.php.
References get_the_category_rss().
the_content_feed ($feed_type = null)
Display the post content for feeds.
Since
2.9.0
Parameters
string $feed_type The type of feed. rss2 | atom | rss | rdf
Definition at line 210 of file feed.php.
References get_the_content_feed().
the_excerpt_rss ()
Display the post excerpt for the feed.
Since
0.71
Filter the post excerpt for a feed.
Since
1.2.0
Parameters
string $output The current post excerpt.
Definition at line 219 of file feed.php.
References $output, apply_filters(), and get_the_excerpt().
the_permalink_rss ()
Display the permalink to the post for use in feeds.
Since
2.3.0
Filter the permalink to the post for use in feeds.
Since
2.3.0
Parameters
string $post_permalink The current post permalink.
Definition at line 236 of file feed.php.
References apply_filters(), esc_url, and get_permalink().
Referenced by permalink_single_rss().
the_title_rss ()
Display the post title in the feed.
Since
0.71
Definition at line 171 of file feed.php.
References get_the_title_rss().
Referenced by export_wp().
wp_title_rss ($deprecated = '&#8211;')
Display the blog title for display of the feed title.
Since
2.2.0
4.4.0 The optional $sep parameter was deprecated and renamed to $deprecated.
Parameters
string $deprecated Unused.
Filter the blog title for display of the feed title.
Since
2.2.0
4.4.0 The $sep parameter was deprecated and renamed to $deprecated.
See also
get_wp_title_rss()
Parameters
string $wp_title_rss The current blog title.
string $deprecated Unused.
Definition at line 125 of file feed.php.
References $deprecated, __, _deprecated_argument(), apply_filters(), and get_wp_title_rss().