GravityView: field-created_by-html.php File Reference
field-created_by-html.php File Reference
Variables
$field_settings = $gravityview->field->as_configuration()
if(! $user) $name_display = empty($field_settings['name_display']) ? 'display_name' : $field_settings['name_display']
if(empty($value)) $user = get_userdata($value)
if(! isset($gravityview)||empty($gravityview->template)) $value = $gravityview->value
The default created by field output template.
case __pad0__
case __pad1__
break
endswitch
Variable Documentation
$field_settings
$field_settings = $gravityview->field->as_configuration()
Definition at line 15 of file field-created_by-html.php.
$name_display
if (! $user) $name_display = empty($field_settings['name_display']) ? 'display_name' : $field_settings['name_display']
Definition at line 30 of file field-created_by-html.php.
$user
if (empty($value)) $user = get_userdata($value)
Definition at line 23 of file field-created_by-html.php.
Referenced by GravityView_Change_Entry_Creator\add_select(), SupportUser\delete(), SupportUser\get(), GravityView_Widget_Search\get_created_by_choices(), GravityView_Field_Gravatar\get_email(), GravityView_Edit_Entry_Locking\get_lock_ui(), SupportUser\get_revoke_url(), SupportUser\get_secret_id(), GravityView_Edit_Entry_User_Registration\match_current_display_name(), GravityView_Edit_Entry_Locking\request_lock(), Client\revoke_access(), GravityView_Support_Port\show_for_user(), Addon_Settings\uninstall_form(), and GravityView_Support_Port\user_field().
$value
if (! isset($gravityview)||empty($gravityview->template)) $value = $gravityview->value
The default created by field output template.
$gravityview
Since
2.0
Definition at line 14 of file field-created_by-html.php.
__pad0__
case __pad0__
Definition at line 43 of file field-created_by-html.php.
__pad1__
case __pad1__
Definition at line 46 of file field-created_by-html.php.
break
break
Definition at line 36 of file field-created_by-html.php.
endswitch
endswitch
Definition at line 48 of file field-created_by-html.php.
Referenced by Form\__get(), gventry\callback(), gvfield\callback(), gravityview\detail(), GV\Mocks\GravityView_API_field_label(), GV\Mocks\GravityView_API_field_value(), Legacy_Context\load(), WP_Action_Logger\log(), GF_Entry_Filter\merge_search_criteria(), Views_Route\prepare_entry_for_response(), View\restrict(), GravityView_Widget_Search\sieve_filter_choices(), Plugin\supports(), and Legacy_Context\thaw().