GravityView: field-survey-html.php File Reference
field-survey-html.php File Reference
Variables
$choice_display = \GV\Utils::get($field, 'choice_display', $default_display)
$default_display = $field->score ? 'score' : 'default'
$display_value = $gravityview->display_value
$field = $gravityview->field
$input_id = gravityview_get_input_id_from_id($field->ID)
Variable Documentation
$choice_display
$choice_display = \GV\Utils::get($field, 'choice_display', $default_display)
Definition at line 22 of file field-survey-html.php.
$default_display
$default_display = $field->score ? 'score' : 'default'
Definition at line 20 of file field-survey-html.php.
$display_value
$display_value = $gravityview->display_value
Definition at line 16 of file field-survey-html.php.
$field
$field = $gravityview->field
Definition at line 15 of file field-survey-html.php.
$input_id
$input_id = gravityview_get_input_id_from_id($field->ID)
Definition at line 17 of file field-survey-html.php.
Referenced by GravityView_Field_List\add_form_fields(), GravityView_Field_Survey\field_options(), GravityView_Field_Survey\get_choice_score(), GravityView_Edit_Entry_Render\get_field_value(), GravityView_Field_Address\get_input_type_from_input_id(), GravityView_Widget_Search\prepare_field_filter(), GravityView_Edit_Entry_Render\save_field_value(), GravityView_Field_Address\search_bar_input_type(), GravityView_Field_Address\search_field_filter(), GravityView_Edit_Entry_Render\unselect_default_values(), GravityView_Edit_Entry_Render\unset_hidden_field_values(), and GravityView_Edit_Entry_Render\update_calculation_fields().