GravityView: field-entry_link-html.php File Reference
field-entry_link-html.php File Reference
Variables
$add_query_args = apply_filters('gravityview/entry_link/add_query_args', true)
$field_settings = $gravityview->field->as_configuration()
$href = $gravityview->entry->get_permalink($gravityview->view, $gravityview->request, $tag_atts)
if($add_query_args) $link = gravityview_get_link($href, $output, $tag_atts)
$link_text = empty($field_settings['entry_link_text']) ? esc_html__('View Details', 'gravityview') : $field_settings['entry_link_text']
$output = apply_filters('gravityview_entry_link', GravityView_API::replace_variables($link_text, $form, $entry), $gravityview)
if(! empty($field_settings['new_window'])) global $post
$tag_atts = array()
if(! isset($gravityview)||empty($gravityview->template)) if(! $gravityview->field->form_id||!($form=GFAPI::get_form($gravityview->field->form_id))) if($gravityview->entry->is_multi()) else
The default entry link field output template.
Variable Documentation
$add_query_args
$add_query_args = apply_filters('gravityview/entry_link/add_query_args', true)
Runs Filter:
gravityview/entry_link/add_query_args Modify whether to include passed $_GET parameters to the end of the url
Since
2.10
Parameters
bool $add_query_params Whether to include passed $_GET parameters to the end of the Entry Link URL. Default: true.
Definition at line 46 of file field-entry_link-html.php.
Referenced by GravityView_API\directory_link(), GravityView_API\entry_link(), and GravityView_Delete_Entry\get_delete_link().
$field_settings
$field_settings = $gravityview->field->as_configuration()
Definition at line 25 of file field-entry_link-html.php.
$href
$href = $gravityview->entry->get_permalink($gravityview->view, $gravityview->request, $tag_atts)
Definition at line 39 of file field-entry_link-html.php.
$link
if ($add_query_args) $link = gravityview_get_link($href, $output, $tag_atts)
Definition at line 52 of file field-entry_link-html.php.
Referenced by GravityView_API\directory_link(), GravityView_API\entry_link_html(), GravityView_Theme_Hooks_WPML\filter_gravityview_back_link(), Admin\get_footer_html(), GravityView_Entry_List\get_item_output(), gravityview_back_link(), gravityview_get_map_link(), gravityview_get_the_term_list(), and GravityView_Field_Unsubscribe\modify_entry_value_unsubscribe().
$link_text
$link_text = empty($field_settings['entry_link_text']) ? esc_html__('View Details', 'gravityview') : $field_settings['entry_link_text']
Definition at line 27 of file field-entry_link-html.php.
$output
$output = apply_filters('gravityview_entry_link', GravityView_API::replace_variables($link_text, $form, $entry), $gravityview)
Runs Filter:
gravityview_field_entry_link Modify the link HTML (here for backward compatibility)
Parameters
string $link HTML output of the link
string $href URL of the link
array $entry The GF entry array
array $field_settings Settings for the particular GV field
Definition at line 29 of file field-entry_link-html.php.
$post
if (! empty($field_settings[ 'new_window'])) global $post
Definition at line 33 of file field-entry_link-html.php.
$tag_atts
$tag_atts = array()
Definition at line 31 of file field-entry_link-html.php.
else
if (! isset($gravityview)||empty($gravityview->template)) if (! $gravityview->field->form_id||!($form=GFAPI::get_form($gravityview->field->form_id))) if ($gravityview->entry->is_multi()) else
Initial value:
{
    $entry = $gravityview->entry->as_entry()
The default entry link field output template.
$gravityview
Since
2.0
Definition at line 21 of file field-entry_link-html.php.