GravityView: formatting.php File Reference
formatting.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_autop_newline_preservation_helper ($matches)
Newline preservation help function for wpautop.
_deep_replace ($search, $subject)
Perform a deep string replace operation to ensure the values in $search are no longer present.
_get_wptexturize_shortcode_regex ($tagnames)
Retrieve the regular expression for shortcodes.
_get_wptexturize_split_regex ($shortcode_regex= '')
Retrieve the combined regular expression for HTML and shortcodes.
_links_add_base ($m)
Callback to add a base url to relative links in passed content.
_links_add_target ($m)
Callback to add a target attribute to all links in passed content.
_make_email_clickable_cb ($matches)
Callback to convert email address match to HTML A element.
_make_url_clickable_cb ($matches)
Callback to convert URI match to HTML A element.
_make_web_ftp_clickable_cb ($matches)
Callback to convert URL match to HTML A element.
_split_str_by_whitespace ($string, $goal)
Breaks a string into chunks by splitting at whitespace characters.
_wp_iso_convert ($match)
Helper function to convert hex encoded chars to ASCII.
_wp_specialchars ($string, $quote_style=ENT_NOQUOTES, $charset=false, $double_encode=false)
Converts a number of special characters into their HTML entities.
_wptexturize_pushpop_element ($text, &$stack, $disabled_elements)
Search for disabled element tags.
addslashes_gpc ($gpc)
Adds slashes to escape strings.
antispambot ($email_address, $hex_encoding=0)
Converts email addresses characters to HTML entities to block spam bots.
backslashit ($string)
Adds backslashes before letters and before a number at the start of a string.
balanceTags ($text, $force=false)
Balances tags if forced to, or if the 'use_balanceTags' option is set to true.
capital_P_dangit ($text)
Forever eliminate "Wordpress" from the planet (or at least the little bit we can influence).
convert_chars ($content, $deprecated= '')
Converts lone & characters into &#038; (a.k.a.
convert_invalid_entities ($content)
Converts invalid Unicode references range to valid range.
convert_smilies ($text)
Convert text equivalent of smilies to images.
ent2ncr ($text)
Converts named entities into numbered entities.
esc_attr ($text)
Escaping for HTML attributes.
esc_html ($text)
Escaping for HTML blocks.
esc_js ($text)
Escape single quotes, htmlspecialchar " < > &, and fix line endings.
esc_sql ($data)
Escapes data for use in a MySQL query.
esc_textarea ($text)
Escaping for textarea values.
esc_url ($url, $protocols=null, $_context= 'display')
Checks and cleans a URL.
esc_url_raw ($url, $protocols=null)
Performs esc_url() for database usage.
force_balance_tags ($text)
Balances tags of string using a modified stack.
format_for_editor ($text, $default_editor=null)
Formats text for the editor.
format_to_edit ($content, $rich_text=false)
Acts on text which is about to be edited.
get_date_from_gmt ($string, $format= 'Y-m-d H:i:s')
Converts a GMT date into the correct format for the blog.
get_gmt_from_date ($string, $format= 'Y-m-d H:i:s')
Returns a date in the GMT equivalent.
get_html_split_regex ()
Retrieve the regular expression for an HTML element.
get_url_in_content ($content)
Extract and return the first URL from passed content.
htmlentities2 ($myHTML)
Convert entities, while preserving already-encoded entities.
human_time_diff ($from, $to= '')
Determines the difference between two timestamps.
is_email ($email, $deprecated=false)
Verifies that an email is valid.
iso8601_timezone_to_offset ($timezone)
Computes an offset in seconds from an iso8601 timezone.
iso8601_to_datetime ($date_string, $timezone= 'user')
Converts an iso8601 date to MySQL DateTime format used by post_date[_gmt].
links_add_base_url ($content, $base, $attrs=array('src', 'href'))
Add a Base url to relative links in passed content.
links_add_target ($content, $target= '_blank', $tags=array('a'))
Adds a Target attribute to all links in passed content.
make_clickable ($text)
Convert plaintext URI to HTML links.
map_deep ($value, $callback)
Maps a function to all non-iterable elements of an array or an object.
normalize_whitespace ($str)
Normalize EOL characters and strip duplicate whitespace.
print_emoji_detection_script ()
string $wp_version bool $printed
print_emoji_styles ()
Print the important emoji-related styles.
rawurlencode_deep ($value)
Navigates through an array, object, or scalar, and raw-encodes the values to be used in a URL.
remove_accents ($string)
Converts all accent characters to ASCII characters.
sanitize_email ($email)
Strips out all characters that are not allowable in an email.
sanitize_file_name ($filename)
Sanitizes a filename, replacing whitespace with dashes.
sanitize_html_class ($class, $fallback= '')
Sanitizes an HTML classname to ensure it only contains valid characters.
sanitize_key ($key)
Sanitizes a string key.
sanitize_mime_type ($mime_type)
Sanitize a mime type.
sanitize_option ($option, $value)
Sanitises various option values based on the nature of the option.
sanitize_sql_orderby ($orderby)
Ensures a string is a valid SQL 'order by' clause.
sanitize_text_field ($str)
Sanitize a string from user input or from the db.
sanitize_title ($title, $fallback_title= '', $context= 'save')
Sanitizes a title, or returns a fallback title.
sanitize_title_for_query ($title)
Sanitizes a title with the 'query' context.
sanitize_title_with_dashes ($title, $raw_title= '', $context= 'display')
Sanitizes a title, replacing whitespace and a few other characters with dashes.
sanitize_trackback_urls ($to_ping)
Sanitize space or carriage return separated URLs that are used to send trackbacks.
sanitize_user ($username, $strict=false)
Sanitizes a username, stripping out unsafe characters.
seems_utf8 ($str)
Checks to see if a string is utf8 encoded.
shortcode_unautop ($pee)
Don't auto-p wrap shortcodes that stand alone.
stripslashes_deep ($value)
Navigates through an array, object, or scalar, and removes slashes from the values.
stripslashes_from_strings_only ($value)
Callback function for stripslashes_deep() which strips slashes from strings.
tag_escape ($tag_name)
Escape an HTML tag name.
trailingslashit ($string)
Appends a trailing slash.
translate_smiley ($matches)
Convert one smiley code to the icon graphic file equivalent.
untrailingslashit ($string)
Removes trailing forward slashes and backslashes if they exist.
url_shorten ($url, $length=35)
Shorten an URL, to be used as link text.
urldecode_deep ($value)
Navigates through an array, object, or scalar, and decodes URL-encoded values.
urlencode_deep ($value)
Navigates through an array, object, or scalar, and encodes the values to be used in a URL.
utf8_uri_encode ($utf8_string, $length=0)
Encode the Unicode values to be used in the URI.
wp_basename ($path, $suffix= '')
i18n friendly version of basename()
wp_check_invalid_utf8 ($string, $strip=false)
Checks for invalid UTF8 in a string.
wp_encode_emoji ($content)
Convert any 4 byte emoji in a string to their equivalent HTML entity.
wp_html_excerpt ($str, $count, $more=null)
Safely extracts not more than the first $count characters from html string.
wp_html_split ($input)
Separate HTML elements and comments from the text.
wp_iso_descrambler ($string)
Convert to ASCII from email subjects.
wp_make_link_relative ($link)
Convert full URL paths to absolute paths.
wp_parse_str ($string, &$array)
Parses a string into variables to be stored in an array.
wp_pre_kses_less_than ($text)
Convert lone less than signs.
wp_pre_kses_less_than_callback ($matches)
Callback function used by preg_replace.
wp_rel_nofollow ($text)
Adds rel nofollow string to all HTML A elements in content.
wp_rel_nofollow_callback ($matches)
Callback to add rel=nofollow string to HTML A element.
wp_replace_in_html_tags ($haystack, $replace_pairs)
Replace characters or phrases within HTML elements only.
wp_slash ($value)
Add slashes to a string or array of strings.
wp_spaces_regexp ()
Returns the regexp for common whitespace characters.
wp_specialchars_decode ($string, $quote_style=ENT_NOQUOTES)
Converts a number of HTML entities into their special characters.
wp_sprintf ($pattern)
WordPress implementation of PHP sprintf() with filters.
wp_sprintf_l ($pattern, $args)
Localize list items before the rest of the content.
wp_staticize_emoji ($text)
Convert emoji to a static img element.
wp_staticize_emoji_for_email ($mail)
Convert emoji in emails into static images.
wp_strip_all_tags ($string, $remove_breaks=false)
Properly strip all HTML tags including script and style.
wp_trim_excerpt ($text= '')
Generates an excerpt from the content, if needed.
wp_trim_words ($text, $num_words=55, $more=null)
Trims text to a certain number of words.
wp_unslash ($value)
Remove slashes from a string or array of strings.
wpautop ($pee, $br=true)
Replaces double line-breaks with paragraph elements.
wptexturize ($text, $reset=false)
Replaces common plain text characters into formatted entities.
wptexturize_primes ($haystack, $needle, $prime, $open_quote, $close_quote)
Implements a logic tree to determine whether or not "7'." represents seven feet, then converts the special char into either a prime char or a closing quote char.
zeroise ($number, $threshold)
Add leading zeros when necessary.
Function Documentation
_autop_newline_preservation_helper ($matches)
Newline preservation help function for wpautop.
Since
3.1.0 private
Parameters
array $matches preg_replace_callback matches array
Returns
string
Definition at line 774 of file formatting.php.
References str_replace.
_deep_replace ($search, $subject)
Perform a deep string replace operation to ensure the values in $search are no longer present.
Repeats the replacement operation until it no longer replaces anything so as to remove "nested" values e.g. $subject = '%0%0%0DDD', $search ='%0D', $result ='' rather than the '%0%0DD' that str_replace would return
Since
2.8.1 private
Parameters
string | array $search The value being searched for, otherwise known as the needle. An array may be used to designate multiple needles.
string $subject The string being searched and replaced on, otherwise known as the haystack.
Returns
string The string with the replaced svalues.
Definition at line 3321 of file formatting.php.
References $count, and str_replace.
Referenced by esc_url().
_get_wptexturize_shortcode_regex ($tagnames)
Retrieve the regular expression for shortcodes.
private
Definition at line 697 of file formatting.php.
Referenced by wptexturize().
_get_wptexturize_split_regex ($shortcode_regex = '')
Retrieve the combined regular expression for HTML and shortcodes.
private
Definition at line 656 of file formatting.php.
Referenced by wptexturize().
_links_add_base ($m)
Callback to add a base url to relative links in passed content.
Since
2.7.0 private
string $_links_add_base
Parameters
string $m The matched link.
Returns
string The processed link.
Definition at line 4152 of file formatting.php.
References WP_Http\make_absolute_url(), and wp_allowed_protocols().
_links_add_target ($m)
Callback to add a target attribute to all links in passed content.
Since
2.7.0 private
string $_links_add_target
Parameters
string $m The matched link.
Returns
string The processed link.
Definition at line 4198 of file formatting.php.
References $link, and esc_attr().
_make_email_clickable_cb ($matches)
Callback to convert email address match to HTML A element.
This function was backported from 2.5.0 to 2.3.2. Regex callback for make_clickable().
Since
2.3.2 private
Parameters
array $matches Single Regex Match.
Returns
string HTML A element with email address.
Definition at line 2180 of file formatting.php.
_make_url_clickable_cb ($matches)
Callback to convert URI match to HTML A element.
This function was backported from 2.5.0 to 2.3.2. Regex callback for make_clickable().
Since
2.3.2 private
Parameters
array $matches Single Regex Match.
Returns
string HTML A element with URI address.
Definition at line 2113 of file formatting.php.
References $url, and esc_url().
_make_web_ftp_clickable_cb ($matches)
Callback to convert URL match to HTML A element.
This function was backported from 2.5.0 to 2.3.2. Regex callback for make_clickable().
Since
2.3.2 private
Parameters
array $matches Single Regex Match.
Returns
string HTML A element with URL address.
Definition at line 2150 of file formatting.php.
References esc_url().
_split_str_by_whitespace ($string, $goal)
Breaks a string into chunks by splitting at whitespace characters.
The length of each returned chunk is as close to the specified length goal as possible, with the caveat that each chunk includes its trailing delimiter. Chunks longer than the goal are guaranteed to not have any inner whitespace.
Joining the returned chunks with empty delimiters reconstructs the input string losslessly.
Input string must have no null characters (or eventual transformations on output chunks must not care about null characters)
_split_str_by_whitespace("1234 67890 1234 67890a cd 1234   890 123456789 1234567890a    45678   1 3 5 7 90 ", 10) ==
array (
    0 => '1234 67890 ',  // 11 characters: Perfect split
    1 => '1234 ',        //  5 characters: '1234 67890a' was too long
    2 => '67890a cd ',   // 10 characters: '67890a cd 1234' was too long
    3 => '1234   890 ',  // 11 characters: Perfect split
    4 => '123456789 ',   // 10 characters: '123456789 1234567890a' was too long
    5 => '1234567890a ', // 12 characters: Too long, but no inner whitespace on which to split
    6 => '   45678   ',  // 11 characters: Perfect split
    7 => '1 3 5 7 90 ',  // 11 characters: End of $string
);
Since
3.4.0 private
Parameters
string $string The string to split.
int $goal The desired chunk length.
Returns
array Numeric array of chunks.
Definition at line 2283 of file formatting.php.
Referenced by make_clickable().
_wp_iso_convert ($match)
Helper function to convert hex encoded chars to ASCII.
Since
3.1.0 private
Parameters
array $match The preg_replace_callback matches array
Returns
string Converted chars
Definition at line 2580 of file formatting.php.
_wp_specialchars ($string, $quote_style = ENT_NOQUOTES, $charset = false, $double_encode = false)
Converts a number of special characters into their HTML entities.
Specifically deals with: &, <, >, ", and '.
$quote_style can be set to ENT_COMPAT to encode " to ", or ENT_QUOTES to do both. Default is ENT_NOQUOTES where no quotes are encoded.
Since
1.2.2 private
string $_charset
Parameters
string $string The text which is to be encoded.
int | string $quote_style Optional. Converts double quotes if set to ENT_COMPAT, both single and double if set to ENT_QUOTES or none if set to ENT_NOQUOTES. Also compatible with old values; converting single quotes if set to 'single', double if set to 'double' or both if otherwise set. Default is ENT_NOQUOTES.
string $charset Optional. The character encoding of the string. Default is false.
bool $double_encode Optional. Whether to encode existing html entities. Default is false.
Returns
string The encoded text with HTML entities.
Definition at line 891 of file formatting.php.
References $charset, elseif, null, str_replace, wp_kses_normalize_entities(), and wp_load_alloptions().
Referenced by esc_attr(), esc_html(), and esc_js().
_wptexturize_pushpop_element ($text, & $stack, $disabled_elements)
Search for disabled element tags.
Push element to stack on tag open and pop on tag close.
Assumes first char of $text is tag opening and last char is tag closing. Assumes second char of $text is optionally '/' to indicate closing as in </html>.
Since
2.9.0 private
Parameters
string $text Text to check. Must be a tag like <html> or [shortcode].
array $stack List of open tag elements.
array $disabled_elements The tag names to match against. Spaces are not allowed in tag names.
Definition at line 375 of file formatting.php.
References $text, and elseif.
Referenced by wptexturize().
addslashes_gpc ($gpc)
Adds slashes to escape strings.
Slashes will first be removed if magic_quotes_gpc is set, see http://www.php.net/magic_quotes for more details.
Since
0.71
Parameters
string $gpc The string returned from HTTP request data.
Returns
string Returns a string escaped with slashes.
Definition at line 2009 of file formatting.php.
References wp_slash().
Referenced by WP_Query\get_posts().
antispambot ($email_address, $hex_encoding = 0)
Converts email addresses characters to HTML entities to block spam bots.
Since
0.71
Parameters
string $email_address Email address.
int $hex_encoding Optional. Set to 1 to enable hex encoding.
Returns
string Converted email address.
Definition at line 2085 of file formatting.php.
References $i, elseif, str_replace, and zeroise().
backslashit ($string)
Adds backslashes before letters and before a number at the start of a string.
Since
0.71
Parameters
string $string Value to which backslashes will be added.
Returns
string String with backslashes inserted.
Definition at line 1959 of file formatting.php.
Referenced by date_i18n().
balanceTags ($text, $force = false)
Balances tags if forced to, or if the 'use_balanceTags' option is set to true.
Since
0.71
Parameters
string $text Text to be balanced
bool $force If true, forces balancing, ignoring the value of the option. Default false.
Returns
string Balanced text
Definition at line 1761 of file formatting.php.
References $text, force_balance_tags(), and get_option().
capital_P_dangit ($text)
Forever eliminate "Wordpress" from the planet (or at least the little bit we can influence).
Violating our coding standards for a good function name.
Since
3.0.0
string|false $dblq
Parameters
string $text The text to be modified.
Returns
string The modified text.
Definition at line 4315 of file formatting.php.
References $text, _x, current_filter(), and str_replace.
Referenced by wp_get_document_title().
convert_chars ($content, $deprecated = '')
Converts lone & characters into &#038; (a.k.a.
&)
Since
0.71
Parameters
string $content String of characters to be converted.
string $deprecated Not used.
Returns
string Converted string.
Definition at line 1689 of file formatting.php.
References $content, $deprecated, and _deprecated_argument().
Referenced by get_bloginfo_rss(), rss2_site_icon(), wp_get_document_title(), and wp_richedit_pre().
convert_invalid_entities ($content)
Converts invalid Unicode references range to valid range.
Since
4.3.0
Parameters
string $content String with entities that need converting.
Returns
string Converted string.
Definition at line 1709 of file formatting.php.
References $content.
convert_smilies ($text)
Convert text equivalent of smilies to images.
Will only convert smilies if the option 'use_smilies' is true and the global used in the function isn't empty.
Since
0.71
string|array $wp_smiliessearch
Parameters
string $text Content to convert smilies from text.
Returns
string Converted content with text smilies replaced with images.
Definition at line 2423 of file formatting.php.
References $content, $i, $output, $text, and get_option().
ent2ncr ($text)
Converts named entities into numbered entities.
Since
1.5.1
Parameters
string $text The text within which entities will be converted.
Returns
string Text with converted entities.
Filter text before named entities are converted into numbered entities.
A non-null string must be returned for the filter to be evaluated.
Since
3.3.0
Parameters
null $converted_text The text to be converted. Default null.
string $text The text prior to entity conversion.
Definition at line 2993 of file formatting.php.
References $text, apply_filters(), null, and str_replace.
esc_attr ($text)
Escaping for HTML attributes.
Since
2.8.0
Parameters
string $text
Returns
string
Filter a string cleaned and escaped for output in an HTML attribute.
Text passed to esc_attr() is stripped of invalid or special characters before output.
Since
2.0.6
Parameters
string $safe_text The text after it has been escaped.
string $text The text prior to being escaped.
Definition at line 3553 of file formatting.php.
References $text, _wp_specialchars(), apply_filters(), and wp_check_invalid_utf8().
Referenced by _links_add_target(), and translate_smiley().
esc_html ($text)
Escaping for HTML blocks.
Since
2.8.0
Parameters
string $text
Returns
string
Filter a string cleaned and escaped for output in HTML.
Text passed to esc_html() is stripped of invalid or special characters before output.
Since
2.8.0
Parameters
string $safe_text The text after it has been escaped.
string $text The text prior to being escaped.
Definition at line 3528 of file formatting.php.
References $text, _wp_specialchars(), apply_filters(), and wp_check_invalid_utf8().
Referenced by sanitize_option(), and wp_pre_kses_less_than_callback().
esc_js ($text)
Escape single quotes, htmlspecialchar " < > &, and fix line endings.
Escapes text strings for echoing in JS. It is intended to be used for inline JS (in a tag attribute, for example onclick="..."). Note that the strings have to be in single quotes. The filter 'js_escape' is also applied here.
Since
2.8.0
Parameters
string $text The text to be escaped.
Returns
string Escaped text.
Filter a string cleaned and escaped for output in JavaScript.
Text passed to esc_js() is stripped of invalid or special characters, and properly slashed for output.
Since
2.0.6
Parameters
string $safe_text The text after it has been escaped.
string $text The text prior to being escaped.
Definition at line 3500 of file formatting.php.
References $text, _wp_specialchars(), apply_filters(), str_replace, and wp_check_invalid_utf8().
Referenced by GFConfirmationTable\column_name(), dismissed_updates(), WP_Themes_List_Table\display_rows(), Bulk_Upgrader_Skin\error(), GFForms\format_toolbar_menu_items(), GFFeedAddOn\get_action_links(), GravityView_Delete_Entry\get_confirm_dialog(), GFFormDisplay\get_counter_init_script(), GF_Field_CreditCard\get_form_inline_script_on_page_render(), GFFormDisplay\get_input_mask_init_script(), GFFormDisplay\get_password_strength_init_script(), WP_Links_List_Table\handle_row_actions(), js_escape(), sanitize_bookmark_field(), sanitize_post_field(), sanitize_term_field(), sanitize_user_field(), GFSettings\settings_uninstall_page(), and wp_save_image().
esc_sql ($data)
Escapes data for use in a MySQL query.
Usually you should prepare queries using wpdb::prepare(). Sometimes, spot-escaping is required or useful. One example is preparing an array for use in an IN clause.
Since
2.8.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string | array $data Unescaped data
Returns
string|array Escaped data
Definition at line 3346 of file formatting.php.
References $wpdb.
Referenced by WP_Date_Query\__construct(), _pad_term_counts(), _update_post_term_count(), GFAPI\add_entry(), get_page_by_path(), get_page_by_title(), WP_Date_Query\get_sql_for_clause(), WP_User_Query\parse_orderby(), WP_Comment_Query\parse_orderby(), WP_Tax_Query\transform_query(), GFAPI\update_entry(), and GFAPI\update_forms_property().
esc_textarea ($text)
Escaping for textarea values.
Since
3.1.0
Parameters
string $text
Returns
string
Filter a string cleaned and escaped for output in a textarea element.
Since
3.1.0
Parameters
string $safe_text The text after it has been escaped.
string $text The text prior to being escaped.
Definition at line 3578 of file formatting.php.
References $text, apply_filters(), and get_option().
Referenced by _list_meta_row(), WP_Comments_List_Table\column_comment(), WP_Widget_Text\form(), GravityView_Recent_Entries_Widget\form(), format_to_edit(), GF_Field_Textarea\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Post_Content\get_field_input(), get_inline_data(), network_step2(), WP_Customize_Control\render_content(), GravityView_FieldType_textarea\render_input(), and GravityView_Render_Settings\render_textarea_option().
esc_url ($url, $protocols = null, $_context = 'display')
Checks and cleans a URL.
A number of characters are removed from the URL. If the URL is for displaying (the default behaviour) ampersands are also replaced. The 'clean_url' filter is applied to the returned cleaned URL.
Since
2.8.0
Parameters
string $url The URL to be cleaned.
array $protocols Optional. An array of acceptable protocols. Defaults to return value of wp_allowed_protocols()
string $_context Private. Use esc_url_raw() for database usage.
Returns
string The cleaned $url after the 'clean_url' filter is applied.
Filter a string cleaned and escaped for output as a URL.
Since
2.3.0
Parameters
string $good_protocol_url The cleaned URL to be returned.
string $original_url The URL prior to cleaning.
string $_context If 'display', replace ampersands and single quotes only.
Definition at line 3366 of file formatting.php.
References $url, _deep_replace(), apply_filters(), elseif, str_replace, wp_allowed_protocols(), wp_kses_bad_protocol(), wp_kses_normalize_entities(), and wp_parse_url().
Referenced by _make_url_clickable_cb(), _make_web_ftp_clickable_cb(), esc_url_raw(), and translate_smiley().
esc_url_raw ($url, $protocols = null)
Performs esc_url() for database usage.
Since
2.8.0
Parameters
string $url The URL to be cleaned.
array $protocols An array of acceptable protocols.
Returns
string The cleaned URL.
Definition at line 3468 of file formatting.php.
References $url, and esc_url().
Referenced by WP_Press_This\_limit_url(), GravityView_Entry_Link_Shortcode_Test\_test_delete(), _wp_ajax_delete_comment_response(), GravityView_frontend\add_columns_sort_links(), GFAPI\add_entry(), GravityView_Settings\app_settings_fields(), GFFormsModel\create_lead(), WP_Customize_Manager\customize_pane_settings(), edit_post(), edit_user(), WP_Customize_Nav_Menus\export_preview_data(), GravityView_Entry_Notes\filter_avatar(), get_blogaddress_by_domain(), get_editor_stylesheets(), get_header_image(), GVCommon\get_link_html(), get_pagenum_link(), get_post_embed_url(), get_uploaded_header_images(), get_url_in_content(), GravityView_Image\html(), GravityView_Delete_Entry\process_delete(), GFFormDisplay\process_form(), rest_output_link_header(), rest_send_cors_headers(), WP_Customize_Nav_Menu_Item_Setting\sanitize(), WP_Theme\sanitize_header(), sanitize_option(), sanitize_url(), Custom_Image_Header\set_header_image(), GVCommon_Test\test_get_link_html(), twentyeleven_url_grabber(), twentytwelve_custom_header_fonts(), twentytwelve_mce_css(), twentytwelve_scripts_styles(), wp_ajax_send_link_to_editor(), wp_media_upload_handler(), wp_prepare_themes_for_js(), wp_update_nav_menu_item(), and wp_widget_rss_process().
force_balance_tags ($text)
Balances tags of string using a modified stack.
Since
2.0.4
Author
Leonard Lin leona.nosp@m.rd@a.nosp@m.cm.or.nosp@m.g GPL
Copyright
November 4, 2001
Version
1.1
Definition at line 1787 of file formatting.php.
References $attributes, $i, $text, elseif, and str_replace.
Referenced by balanceTags(), and get_the_content().
format_for_editor ($text, $default_editor = null)
Formats text for the editor.
Generally the browsers treat everything inside a textarea as text, but it is still a good idea to HTML entity encode <, > and & in the content.
The filter {
See also
'format_for_editor'} is applied here. If $text is empty the filter will be applied to an empty string.
Since
4.3.0
See also
_WP_Editors::editor()
Parameters
string $text The text to be formatted.
string $default_editor The default editor for the current user. It is usually either 'html' or 'tinymce'.
Returns
string The formatted text after filter is applied.
Filter the text after it is formatted for the editor.
Since
4.3.0
Parameters
string $text The formatted text.
string $default_editor The default editor for the current user. It is usually either 'html' or 'tinymce'.
Definition at line 3289 of file formatting.php.
References $text, apply_filters(), and get_option().
format_to_edit ($content, $rich_text = false)
Acts on text which is about to be edited.
The $content is run through esc_textarea(), which uses htmlspecialchars() to convert special characters to HTML entities. If $richedit is set to true, it is simply a holder for the 'format_to_edit' filter.
Since
0.71
4.4.0 The $richedit parameter was renamed to $rich_text for clarity.
Parameters
string $content The text about to be edited.
bool $rich_text Optional. Whether $content should be considered rich text, in which case it would not be passed through esc_textarea(). Default false.
Returns
string The text after the filter (and possibly htmlspecialchars()) has been run.
Filter the text to be formatted for editing.
Since
1.2.0
Parameters
string $content The text, prior to formatting for editing.
Definition at line 1916 of file formatting.php.
References $content, apply_filters(), and esc_textarea().
Referenced by get_comment_to_edit(), and sanitize_post_field().
get_date_from_gmt ($string, $format = 'Y-m-d H:i:s')
Converts a GMT date into the correct format for the blog.
Requires and returns a date in the Y-m-d H:i:s format. If there is a timezone_string available, the returned date is in that timezone, otherwise it simply adds the value of gmt_offset. Return format can be overridden using the $format parameter
Since
1.2.0
Parameters
string $string The date to be converted.
string $format The format string for the returned date (default is Y-m-d H:i:s)
Returns
string Formatted date relative to the timezone / GMT offset.
Definition at line 2635 of file formatting.php.
References $format, date, and get_option().
Referenced by wp_xmlrpc_server\_insert_post(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), rest_get_date_with_gmt(), wp_xmlrpc_server\wp_editComment(), and wp_insert_post().
get_gmt_from_date ($string, $format = 'Y-m-d H:i:s')
Returns a date in the GMT equivalent.
Requires and returns a date in the Y-m-d H:i:s format. If there is a timezone_string available, the date is assumed to be in that timezone, otherwise it simply subtracts the value of the 'gmt_offset' option. Return format can be overridden using the $format parameter.
Since
1.2.0
Parameters
string $string The date to be converted.
string $format The format string for the returned date (default is Y-m-d H:i:s)
Returns
string GMT version of the date provided.
Definition at line 2598 of file formatting.php.
References $format, and get_option().
Referenced by wp_xmlrpc_server\_convert_date_gmt(), _future_post_hook(), _wp_translate_postdata(), GravityView_Admin_Duplicate_View\create_duplicate(), GravityView_Widget_Search\filter_entries(), wp_insert_comment(), wp_insert_post(), and wp_update_comment().
get_html_split_regex ()
Retrieve the regular expression for an HTML element.
Since
4.4.0
Returns
string The regular expression
Definition at line 598 of file formatting.php.
Referenced by wp_html_split().
get_url_in_content ($content)
Extract and return the first URL from passed content.
Since
3.6.0
Parameters
string $content A string which might contain a URL.
Returns
string|false The found URL.
Definition at line 4432 of file formatting.php.
References $content, and esc_url_raw().
Referenced by twentyeleven_get_first_url(), and twentythirteen_get_link_url().
htmlentities2 ($myHTML)
Convert entities, while preserving already-encoded entities.
Borrowed from the PHP Manual user notes. 1.2.2 string $myHTML The text to be converted. string Converted text.
Definition at line 3482 of file formatting.php.
human_time_diff ($from, $to = '')
Determines the difference between two timestamps.
The difference is returned in a human readable format such as "1 hour", "5 mins", "2 days".
Since
1.5.0
Parameters
int $from Unix timestamp from which the difference begins.
int $to Optional. Unix timestamp to end the time difference. Default becomes time() if not set.
Returns
string Human readable time difference.
Filter the human readable difference between two timestamps.
Since
4.0.0
Parameters
string $since The difference in human readable text.
int $diff The difference in seconds.
int $from Unix timestamp from which the difference begins.
int $to Unix timestamp to end the time difference.
Definition at line 2819 of file formatting.php.
References $from, _n(), apply_filters(), and elseif.
Referenced by WP_Media_List_Table\column_date(), WP_Posts_List_Table\column_date(), WP_Plugin_Install_List_Table\display_rows(), GVCommon\format_date(), GVCommon_Test\test_format_date(), GravityView_Merge_Tags_Test\test_replace_date_created(), wp_post_revision_title_expanded(), and wp_prepare_revisions_for_js().
is_email ($email, $deprecated = false)
Verifies that an email is valid.
Does not grok i18n domains. Not RFC compliant.
Since
0.71
Parameters
string $email Email address to verify.
bool $deprecated Deprecated.
Returns
string|bool Either false or the valid email address.
Filter whether an email address is valid.
This filter is evaluated under several different contexts, such as 'email_too_short', 'email_no_at', 'local_invalid_chars', 'domain_period_sequence', 'domain_period_limits', 'domain_no_periods', 'sub_hyphen_limits', 'sub_invalid_chars', or no specific context.
Since
2.8.0
Parameters
bool $is_email Whether the email address has passed the is_email() checks. Default false.
string $email The email address being checked.
string $context Context under which the email was tested.
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
Definition at line 2473 of file formatting.php.
References $deprecated, _deprecated_argument(), apply_filters(), and null.
Referenced by edit_user(), get_user_id_from_string(), newblog_notify_siteadmin(), newuser_notify_siteadmin(), populate_network(), register_new_user(), sanitize_option(), send_confirmation_on_profile_email(), update_option_new_admin_email(), validate_email(), wp_handle_comment_submission(), wp_xmlrpc_server\wp_newComment(), and wpmu_validate_user_signup().
iso8601_timezone_to_offset ($timezone)
Computes an offset in seconds from an iso8601 timezone.
Since
1.5.0
Parameters
string $timezone Either 'Z' for 0 offset or 'hhmm'.
Returns
int|float The offset in seconds.
Definition at line 2660 of file formatting.php.
Referenced by iso8601_to_datetime().
iso8601_to_datetime ($date_string, $timezone = 'user')
Converts an iso8601 date to MySQL DateTime format used by post_date[_gmt].
Since
1.5.0
Parameters
string $date_string Date and time in ISO 8601 format http://en.wikipedia.org/wiki/ISO_8601.
string $timezone Optional. If set to GMT returns the time minus gmt_offset. Default is 'user'.
Returns
string The date and time in MySQL DateTime format - Y-m-d H:i:s.
Definition at line 2682 of file formatting.php.
References elseif, get_option(), and iso8601_timezone_to_offset().
Referenced by wp_xmlrpc_server\_insert_post(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), and wp_xmlrpc_server\wp_editComment().
links_add_base_url ($content, $base, $attrs = array('src', 'href'))
Add a Base url to relative links in passed content.
By default it supports the 'src' and 'href' attributes. However this can be changed via the 3rd param.
Since
2.7.0
string $_links_add_base
Parameters
string $content String to search for links in.
string $base The base URL to prefix to links.
array $attrs The attributes which should be processed.
Returns
string The processed content.
Definition at line 4134 of file formatting.php.
References $content.
links_add_target ($content, $target = '_blank', $tags = array('a'))
Adds a Target attribute to all links in passed content.
This function by default only applies to <a> tags, however this can be modified by the 3rd param.
NOTE: Any current target attributed will be stripped and replaced.
Since
2.7.0
string $_links_add_target
Parameters
string $content String to search for links in.
string $target The Target to add to the links.
array $tags An array of tags to apply to.
Returns
string The processed content.
Definition at line 4180 of file formatting.php.
References $content, and $tags.
make_clickable ($text)
Convert plaintext URI to HTML links.
Converts URI, www and ftp, and email addresses. Finishes by fixing links within links.
Since
0.71
Parameters
string $text Content to convert URIs.
Returns
string Content with converted URIs.
Definition at line 2196 of file formatting.php.
References $text, _split_str_by_whitespace(), and elseif.
map_deep ($value, $callback)
Maps a function to all non-iterable elements of an array or an object.
This is similar to array_walk_recursive() but acts upon objects too.
Since
4.4.0
Parameters
mixed $value The array, object, or scalar.
callable $callback The function to map onto $value.
Returns
The value with the callback applied to all non-arrays and non-objects inside it.
Definition at line 3893 of file formatting.php.
References $value, and elseif.
Referenced by rawurlencode_deep(), stripslashes_deep(), urldecode_deep(), and urlencode_deep().
normalize_whitespace ($str)
Normalize EOL characters and strip duplicate whitespace.
Since
2.7.0
Parameters
string $str The string to normalize.
Returns
string The normalized string.
Definition at line 4213 of file formatting.php.
References str_replace.
Referenced by gravityview_strip_whitespace(), and wp_save_post_revision().
print_emoji_detection_script ()
string $wp_version bool $printed
Filter the URL where emoji images are hosted.
Since
4.2.0
Parameters
string The emoji base URL.
Filter the extension of the emoji files.
Since
4.2.0
Parameters
string The emoji extension. Default .png.
This filter is documented in wp-includes/class.wp-scripts.php
This filter is documented in wp-includes/class.wp-scripts.php
This filter is documented in wp-includes/class.wp-scripts.php
Definition at line 4517 of file formatting.php.
References $wp_version, a, ABSPATH, apply_filters(), includes_url(), wp_json_encode(), and WPINC.
print_emoji_styles ()
Print the important emoji-related styles.
Since
4.2.0
bool $printed
Definition at line 4486 of file formatting.php.
References align, height, margin, shadow, and width.
rawurlencode_deep ($value)
Navigates through an array, object, or scalar, and raw-encodes the values to be used in a URL.
Since
3.4.0
Parameters
mixed $value The array or string to be encoded.
Returns
mixed $value The encoded value.
Definition at line 2060 of file formatting.php.
References $value, and map_deep().
Referenced by get_avatar_data(), and redirect_canonical().
remove_accents ($string)
Converts all accent characters to ASCII characters.
If there are no accent characters, then the string given is just returned.
Since
1.2.1
Parameters
string $string Text that might have accent characters
Returns
string Filtered string with replaced "nice" characters.
Definition at line 1132 of file formatting.php.
References $locale, elseif, get_locale(), seems_utf8(), and str_replace.
Referenced by sanitize_title(), and sanitize_user().
sanitize_email ($email)
Strips out all characters that are not allowable in an email.
Since
1.5.0
Parameters
string $email Email address to filter.
Returns
string Filtered email address.
Filter a sanitized email address.
This filter is evaluated under several contexts, including 'email_too_short', 'email_no_at', 'local_invalid_chars', 'domain_period_sequence', 'domain_period_limits', 'domain_no_periods', 'domain_no_valid_subs', or no context.
Since
2.8.0
Parameters
string $email The sanitized email address.
string $email The email address, as provided to sanitize_email().
string $message A message to pass to the user.
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
Definition at line 2713 of file formatting.php.
References apply_filters(), and null.
Referenced by sanitize_option(), wpmu_signup_user(), and wpmu_validate_user_signup().
sanitize_file_name ($filename)
Sanitizes a filename, replacing whitespace with dashes.
Removes special characters that are illegal in filenames on certain operating systems and special characters requiring special escaping to manipulate at the command line. Replaces spaces and consecutive dashes with a single dash. Trims period, dash and underscore from beginning and end of filename.
Since
2.1.0
Parameters
string $filename The filename to be sanitized
Returns
string The sanitized filename
Filter the list of characters to remove from a filename.
Since
2.8.0
Parameters
array $special_chars Characters to remove.
string $filename_raw Filename as it was passed into sanitize_file_name().
Filter a sanitized filename string.
Since
2.8.0
Parameters
string $filename Sanitized filename.
string $filename_raw The filename prior to sanitization.
This filter is documented in wp-includes/formatting.php
Definition at line 1374 of file formatting.php.
References apply_filters(), get_allowed_mime_types(), and str_replace.
Referenced by GFFormsModel\get_file_upload_path(), wp_xmlrpc_server\mw_newMediaObject(), GFAsyncUpload\upload(), and wp_unique_filename().
sanitize_html_class ($class, $fallback = '')
Sanitizes an HTML classname to ensure it only contains valid characters.
Strips the string down to A-Z,a-z,0-9,_,-. If this results in an empty string then it will return the alternative value supplied.
Since
2.8.0
Parameters
string $class The classname to be sanitized
string $fallback Optional. The value to return if the sanitization ends up as an empty string. Defaults to an empty string.
Returns
string The sanitized value
Filter a sanitized HTML class string.
Since
2.8.0
Parameters
string $sanitized The sanitized HTML class.
string $class HTML class before sanitization.
string $fallback The fallback string.
Definition at line 1658 of file formatting.php.
References $class, and apply_filters().
Referenced by _navigation_markup(), WP_Screen\add_help_tab(), _WP_Editors\editor_settings(), gallery_shortcode(), get_body_class(), get_comment_class(), GravityView_FieldType\get_field_id(), GravityView_Admin_View_Item\get_item_info(), GravityView_FieldType\get_label_class(), get_post_class(), WP_Press_This\html(), iframe_header(), img_caption_shortcode(), login_header(), and WP_MS_Themes_List_Table\single_row().
sanitize_key ($key)
Sanitizes a string key.
Keys are used as internal identifiers. Lowercase alphanumeric characters, dashes and underscores are allowed.
Since
3.0.0
Parameters
string $key String key
Returns
string Sanitized key
Filter a sanitized key string.
Since
3.0.0
Parameters
string $key Sanitized key.
string $raw_key The key prior to sanitization.
Definition at line 1490 of file formatting.php.
References apply_filters().
Referenced by WP_List_Table\__construct(), _get_last_post_time(), _wp_preview_terms_filter(), _wp_translate_postdata(), add_metadata(), WP_Customize_Nav_Menus\ajax_load_available_items(), bulk_edit_posts(), delete_metadata(), delete_metadata_by_mid(), edit_post(), export_wp(), WP_Screen\get(), GFFormDisplay\get_form(), WP_Meta_Query\get_sql(), GFFormDisplay\gform_footer(), has_post_format(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), WP_Query\parse_orderby(), WP_Query\parse_query(), WP_Comments_List_Table\prepare_items(), WP_User_Query\prepare_query(), GFFormDisplay\process_form(), GFFormDisplay\process_send_resume_link(), register_post_status(), register_post_type(), GFFormDisplay\replace_save_variables(), WP_Customize_Nav_Menu_Item_Setting\sanitize(), set_post_format(), set_screen_options(), WP_Tax_Query\transform_query(), update_meta_cache(), update_metadata(), update_metadata_by_mid(), update_user_status(), wp_ajax_ajax_tag_search(), wp_ajax_closed_postboxes(), wp_ajax_dismiss_wp_pointer(), wp_ajax_get_tagcloud(), wp_ajax_heartbeat(), wp_ajax_hidden_columns(), wp_ajax_inline_save_tax(), wp_ajax_meta_box_order(), wp_ajax_nopriv_heartbeat(), wp_ajax_save_user_color_scheme(), wp_ajax_update_plugin(), and wp_update_nav_menu_item().
sanitize_mime_type ($mime_type)
Sanitize a mime type.
Since
3.1.3
Parameters
string $mime_type Mime type
Returns
string Sanitized mime type
Filter a mime type following sanitization.
Since
3.1.3
Parameters
string $sani_mime_type The sanitized mime type.
string $mime_type The mime type prior to sanitization.
Definition at line 4339 of file formatting.php.
References apply_filters().
sanitize_option ($option, $value)
Sanitises various option values based on the nature of the option.
This is basically a switch statement which will pass $value through a number of functions depending on the $option.
Since
2.0.5
wpdb $wpdb WordPress database abstraction object.
Parameters
string $option The name of the option.
string $value The unsanitised value.
Returns
string Sanitized value.
Filter an option value following sanitization.
Since
2.3.0
4.3.0 Added the $original_value parameter.
Parameters
string $value The sanitized option value.
string $option The option name.
string $original_value The original value passed to the function.
Definition at line 3642 of file formatting.php.
References $allowed_zones, $option, $value, $wpdb, __, absint(), add_settings_error(), apply_filters(), esc_html(), esc_url_raw(), get_available_languages(), get_option(), get_role(), is_email(), is_multisite(), is_wp_error(), null, sanitize_email(), str_replace, wp_kses_data(), and WPLANG.
Referenced by add_network_option(), add_option(), get_settings_errors(), update_network_option(), update_option(), wp_ajax_date_format(), and wp_ajax_time_format().
sanitize_sql_orderby ($orderby)
Ensures a string is a valid SQL 'order by' clause.
Accepts one or more columns, with or without a sort order (ASC / DESC). e.g. 'column_1', 'column_1, column_2', 'column_1 ASC, column_2 DESC' etc.
Also accepts 'RAND()'.
Since
2.5.1
Parameters
string $orderby Order by clause to be validated.
Returns
string|false Returns $orderby if valid, false otherwise.
Definition at line 1636 of file formatting.php.
sanitize_text_field ($str)
Sanitize a string from user input or from the db.
check for invalid UTF-8, Convert single < characters to entity, strip all tags, remove line breaks, tabs and extra white space, strip octets.
Since
2.9.0
Parameters
string $str
Returns
string
Filter a sanitized text field string.
Since
2.9.0
Parameters
string $filtered The sanitized string.
string $str The string prior to being sanitized.
Definition at line 4257 of file formatting.php.
References apply_filters(), str_replace, wp_check_invalid_utf8(), wp_pre_kses_less_than(), and wp_strip_all_tags().
Referenced by WP_Press_This\_limit_string(), WP_Customize_Nav_Menus\ajax_search_available_items(), GFFormsModel\create_lead(), edit_post(), edit_user(), WP_Widget_Calendar\form(), WP_Widget_Text\form(), WP_Widget_Meta\form(), WP_Widget_Categories\form(), WP_Widget_Archives\form(), GFForms\handle_ajax_do_shortcode(), handle_confirmation_edit_submission(), notification_edit_page(), WP_Customize_Nav_Menus\render_menu(), WP_Customize_Nav_Menu_Setting\sanitize(), WP_Customize_Nav_Menu_Item_Setting\sanitize(), GF_Field_Phone\sanitize_entry_value(), GF_Field_FileUpload\sanitize_settings(), GF_Field\sanitize_settings(), GFFormsModel\sanitize_settings(), GFFormsModel\save_lead(), WP_Press_This\save_post(), WP_Widget_Text\update(), WP_Widget_Calendar\update(), WP_Widget_Search\update(), WP_Widget_Meta\update(), WP_Nav_Menu_Widget\update(), WP_Widget_Tag_Cloud\update(), WP_Widget_Pages\update(), WP_Widget_Recent_Posts\update(), WP_Widget_Categories\update(), WP_Widget_Archives\update(), WP_Widget_Recent_Comments\update(), wp_ajax_save_attachment(), and wp_page_menu().
sanitize_title ($title, $fallback_title = '', $context = 'save')
Sanitizes a title, or returns a fallback title.
Specifically, HTML and PHP tags are stripped. Further actions can be added via the plugin API. If $title is empty and $fallback_title is set, the latter will be used.
Since
1.0.0
Parameters
string $title The string to be sanitized.
string $fallback_title Optional. A title to use if $title is empty.
string $context Optional. The operation for which the string is sanitized
Returns
string The sanitized string.
Filter a sanitized title string.
Since
1.2.0
Parameters
string $title Sanitized title.
string $raw_title The title prior to sanitization.
string $context The context for which the title is being sanitized.
Definition at line 1520 of file formatting.php.
References $title, apply_filters(), and remove_accents().
Referenced by _wp_ajax_add_hierarchical_term(), WP_Press_This\add_category(), add_menu_page(), WP_Admin_Bar\add_node(), dynamic_sidebar(), WP_Customize_Nav_Menu_Setting\filter_wp_get_nav_menu_object(), WP_Customize_Nav_Menu_Setting\filter_wp_get_nav_menus(), get_category_by_path(), GravityView_API\get_custom_entry_slug(), GravityView_API\get_entry_slug(), GravityView_Post_Types\get_entry_var_name(), get_sample_permalink(), get_term_by(), get_terms(), is_active_sidebar(), make_site_theme(), media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), permalink_anchor(), register_sidebar_widget(), register_widget_control(), sanitize_title_for_query(), WP_Plugins_List_Table\single_row(), sync_category_tag_slugs(), term_exists(), upgrade_100(), upgrade_110(), upgrade_230(), upgrade_330(), wp_ajax_add_link_category(), wp_insert_post(), wp_insert_term(), wp_insert_user(), and wp_update_term().
sanitize_title_for_query ($title)
Sanitizes a title with the 'query' context.
Used for querying the database for a value from URL.
Since
3.1.0
Parameters
string $title The string to be sanitized.
Returns
string The sanitized string.
Definition at line 1553 of file formatting.php.
References $title, and sanitize_title().
Referenced by WP_Query\get_posts().
sanitize_title_with_dashes ($title, $raw_title = '', $context = 'display')
Sanitizes a title, replacing whitespace and a few other characters with dashes.
Limits the output to alphanumeric characters, underscore (_) and dash (-). Whitespace becomes a dash.
Since
1.2.0
Parameters
string $title The title to be sanitized.
string $raw_title Optional. Not used.
string $context Optional. The operation for which the string is sanitized.
Returns
string The sanitized title.
Definition at line 1570 of file formatting.php.
References $title, seems_utf8(), str_replace, and utf8_uri_encode().
Referenced by install_dashboard(), GFExport\maybe_export(), WP_Plugin_Install_List_Table\prepare_items(), register_post_type(), and register_taxonomy().
sanitize_trackback_urls ($to_ping)
Sanitize space or carriage return separated URLs that are used to send trackbacks.
Since
3.4.0
Parameters
string $to_ping Space or carriage return separated URLs
Returns
string URLs starting with the http or https protocol, separated by a carriage return.
Filter a list of trackback URLs following sanitization.
The string returned here consists of a space or carriage return-delimited list of trackback URLs.
Since
3.4.0
Parameters
string $urls_to_ping Sanitized space or carriage return separated URLs.
string $to_ping Space or carriage return separated URLs before sanitization.
Definition at line 4360 of file formatting.php.
References $url, and apply_filters().
Referenced by get_to_ping(), and wp_insert_post().
sanitize_user ($username, $strict = false)
Sanitizes a username, stripping out unsafe characters.
Removes tags, octets, entities, and if strict is enabled, will only keep alphanumeric, _, space, ., -, After sanitizing, it passes the username, raw username (the username in the parameter), and the value of $strict as parameters for the 'sanitize_user' filter.
Since
2.0.0
Parameters
string $username The username to be sanitized.
bool $strict If set limits $username to specific characters. Default false.
Returns
string The sanitized username, after passing through filters.
Filter a sanitized username string.
Since
2.0.1
Parameters
string $username Sanitized username.
string $raw_username The username prior to sanitization.
bool $strict Whether to limit the sanitization to specific characters. Default false.
Definition at line 1452 of file formatting.php.
References apply_filters(), remove_accents(), and wp_strip_all_tags().
Referenced by edit_user(), WP_User\get_data_by(), register_new_user(), validate_username(), wp_insert_user(), wpmu_create_blog(), wpmu_create_user(), wpmu_signup_user(), and wpmu_validate_user_signup().
seems_utf8 ($str)
Checks to see if a string is utf8 encoded.
NOTE: This function checks for 5-Byte sequences, UTF8 has Bytes Sequences with a maximum length of 4.
Author
bmorel at ssi dot fr (modified)
Since
1.2.1
Parameters
string $str The string to be checked
Returns
bool True if $str fits a UTF-8 model, false otherwise.
Definition at line 847 of file formatting.php.
References $i, elseif, mbstring_binary_safe_encoding(), and reset_mbstring_encoding().
Referenced by export_wp(), remove_accents(), sanitize_title_with_dashes(), GFExport\start_export(), and wp_read_image_metadata().
shortcode_unautop ($pee)
Don't auto-p wrap shortcodes that stand alone.
Ensures that shortcodes are not wrapped in <p>...</p>.
Since
2.9.0
array $shortcode_tags
Parameters
string $pee The content.
Returns
string The filtered content.
Definition at line 790 of file formatting.php.
References $shortcode_tags, and wp_spaces_regexp().
stripslashes_deep ($value)
Navigates through an array, object, or scalar, and removes slashes from the values.
Since
2.0.0
Parameters
mixed $value The value to be stripped.
Returns
mixed Stripped value.
Definition at line 2024 of file formatting.php.
References $value, and map_deep().
Referenced by GravityView_Delete_Entry\display_message(), WP_REST_Server\embed_links(), GravityView_Widget_Search\filter_entries(), GFAddOn\get_posted_settings(), GF_Installation_Wizard_Step\get_posted_values(), WP_REST_Request\parse_body_params(), GFForms\parse_shortcode(), GFForms\post(), GravityView_Merge_Tags\replace_get_variables(), WP_Widget\update_callback(), GFFormsModel\update_grid_column_meta(), wp_ajax_send_attachment_to_editor(), wp_magic_quotes(), wp_parse_str(), and wp_unslash().
stripslashes_from_strings_only ($value)
Callback function for stripslashes_deep() which strips slashes from strings.
Since
4.4.0
Parameters
mixed $value The array or string to be stripped.
Returns
mixed $value The stripped value.
Definition at line 2036 of file formatting.php.
References $value.
tag_escape ($tag_name)
Escape an HTML tag name.
Since
2.5.0
Parameters
string $tag_name
Returns
string
Filter a string cleaned and escaped for output as an HTML tag.
Since
2.8.0
Parameters
string $safe_tag The tag name after it has been escaped.
string $tag_name The text before it was escaped.
Definition at line 3599 of file formatting.php.
References apply_filters().
Referenced by gallery_shortcode(), and get_tag_regex().
trailingslashit ($string)
Appends a trailing slash.
Will remove trailing forward and backslashes if it exists already before adding a trailing forward slash. This prevents double slashing a string or path.
The primary use of this is for paths and thus should be used for paths. It is not restricted to paths and offers no specific path support.
Since
1.2.0
Parameters
string $string What to add the trailing slash to.
Returns
string String with trailing slash added.
Definition at line 1979 of file formatting.php.
References untrailingslashit().
Referenced by _copy_dir(), _upgrade_422_find_genericons_files_in_folder(), _upgrade_422_remove_genericons(), _wp_link_page(), Plugin_Upgrader\check_package(), Theme_Upgrader\check_package(), WP_Filesystem_Direct\chgrp(), WP_Filesystem_Direct\chmod(), copy_dir(), WP_Filesystem_FTPext\cwd(), WP_Filesystem_ftpsockets\cwd(), WP_Filesystem_SSH2\cwd(), WP_Filesystem_Direct\delete(), WP_Filesystem_FTPext\delete(), Plugin_Upgrader\delete_old_plugin(), Theme_Upgrader\delete_old_theme(), delete_plugins(), delete_theme(), WP_Filesystem_MockFS\dirlist(), domain_exists(), _WP_Editors\editor_settings(), GravityView_API\entry_link(), WP_Filesystem_MockFS\exists(), WP_Filesystem_Base\find_folder(), WP_Image_Editor\generate_filename(), get_attachment_link(), get_author_feed_link(), get_comment_link(), get_comments_pagenum_link(), GF_Field_FileUpload\get_field_input(), get_filesystem_method(), Gravity_Api\get_gravity_api_url(), GravityView_oEmbed\get_handler_regex(), get_home_path(), WP_Image_Editor\get_output_format(), get_pagenum_link(), GravityView_Compatibility\get_plugin_status(), get_post_comments_feed_link(), get_post_embed_url(), get_post_type_archive_feed_link(), get_rest_url(), get_search_feed_link(), get_temp_dir(), get_term_feed_link(), GFForms\get_toolbar_menu_items(), get_trackback_url(), WP_Admin_Bar\initialize(), insert_blog(), WP_Upgrader\install_package(), WP_Filesystem_MockFS\is_dir(), WP_Filesystem_FTPext\is_dir(), GravityView_Edit_Entry\load_components(), load_muplugin_textdomain(), WP_Filesystem_MockFS\locate_parent_node(), WP_Filesystem_MockFS\mkdir(), WP_Rewrite\mod_rewrite_rules(), network_step2(), paginate_comments_links(), paginate_links(), plugin_dir_path(), plugin_dir_url(), GravityView_Ajax\pre_get_form_fields(), redirect_canonical(), redirect_guess_404_permalink(), rel_canonical(), WP_Theme\scandir(), WP_Filesystem_Base\search_for_folder(), unzip_file(), update_blog_details(), update_core(), Core_Upgrader\upgrade(), url_to_postid(), user_trailingslashit(), weblog_ping(), wp_calculate_image_srcset(), wp_get_attachment_url(), wp_old_slug_redirect(), and wp_upload_dir().
translate_smiley ($matches)
Convert one smiley code to the icon graphic file equivalent.
Callback handler for convert_smilies(). Looks up one smiley code in the $wpsmiliestrans global array and returns an <img> string for that smiley.
Since
2.8.0
array $wpsmiliestrans
Parameters
array $matches Single match. Smiley code to convert to image.
Returns
string Image string for smiley.
Filter the Smiley image URL before it's used in the image element.
Since
2.9.0
Parameters
string $smiley_url URL for the smiley image.
string $img Filename for the smiley image.
string $site_url Site URL, as returned by site_url().
Definition at line 2378 of file formatting.php.
References apply_filters(), esc_attr(), esc_url(), includes_url(), and site_url().
untrailingslashit ($string)
Removes trailing forward slashes and backslashes if they exist.
The primary use of this is for paths and thus should be used for paths. It is not restricted to paths and offers no specific path support.
Since
2.2.0
Parameters
string $string What to remove the trailing slashes from.
Returns
string String without the trailing slashes.
Definition at line 1994 of file formatting.php.
Referenced by __get_option(), _config_wp_home(), _config_wp_siteurl(), _unzip_file_pclzip(), _unzip_file_ziparchive(), _wp_menu_item_classes_by_context(), WP_Comments_List_Table\column_author(), WP_MS_Sites_List_Table\column_blogname(), WP_MS_Sites_List_Table\column_cb(), WP_REST_Server\embed_links(), get_alloptions_110(), get_option(), get_sample_permalink(), WP_MS_Sites_List_Table\handle_row_actions(), install_blog(), WP_Automatic_Updater\is_vcs_checkout(), load_theme_textdomain(), WP_Filesystem_Direct\mkdir(), WP_Filesystem_FTPext\mkdir(), WP_Filesystem_ftpsockets\mkdir(), WP_Filesystem_SSH2\mkdir(), recurse_dirsize(), register_theme_directory(), WP_Filesystem_Base\search_for_folder(), trailingslashit(), unzip_file(), url_shorten(), user_trailingslashit(), WP_Widget_RSS\widget(), wp_redirect_admin_locations(), and wp_upload_dir().
url_shorten ($url, $length = 35)
Shorten an URL, to be used as link text.
Since
1.2.0
4.4.0 Moved to wp-includes/formatting.php from wp-admin/includes/misc.php and added $length param.
Parameters
string $url URL to shorten.
int $length Optional. Maximum length of the shortened URL. Default 35 characters.
Returns
string Shortened URL.
Definition at line 4794 of file formatting.php.
References $url, str_replace, and untrailingslashit().
Referenced by WP_Links_List_Table\column_url().
urldecode_deep ($value)
Navigates through an array, object, or scalar, and decodes URL-encoded values.
Since
4.4.0
Parameters
mixed $value The array or string to be decoded.
Returns
mixed $value The decoded value.
Definition at line 2072 of file formatting.php.
References $value, and map_deep().
urlencode_deep ($value)
Navigates through an array, object, or scalar, and encodes the values to be used in a URL.
Since
2.2.0
Parameters
mixed $value The array or string to be encoded.
Returns
mixed $value The encoded value.
Definition at line 2048 of file formatting.php.
References $value, and map_deep().
Referenced by add_query_arg(), and paginate_links().
utf8_uri_encode ($utf8_string, $length = 0)
Encode the Unicode values to be used in the URI.
Since
1.5.0
Parameters
string $utf8_string
int $length Max length of the string
Returns
string String with Unicode encoded for URI.
Definition at line 1072 of file formatting.php.
References $i, $value, elseif, mbstring_binary_safe_encoding(), and reset_mbstring_encoding().
Referenced by _truncate_post_slug(), and sanitize_title_with_dashes().
wp_basename ($path, $suffix = '')
i18n friendly version of basename()
Since
3.1.0
Parameters
string $path A path.
string $suffix If the filename ends in suffix this will also be cut off.
Returns
string
Definition at line 4299 of file formatting.php.
References $path, and str_replace.
Referenced by WP_Image_Editor_GD\_save(), WP_Image_Editor_Imagick\_save(), attachment_submitbox_metadata(), WP_Media_List_Table\column_title(), WP_Image_Editor\generate_filename(), get_media_item(), WP_Image_Editor\get_output_format(), WP_Query\get_posts(), image_attachment_fields_to_save(), image_downsize(), WP_Query\parse_tax_query(), wp_ajax_send_link_to_editor(), wp_calculate_image_srcset(), wp_get_attachment_image_src(), wp_image_add_srcset_and_sizes(), and wp_prepare_attachment_for_js().
wp_check_invalid_utf8 ($string, $strip = false)
Checks for invalid UTF8 in a string.
Since
2.8.0
bool $is_utf8 bool $utf8_pcre
Parameters
string $string The text which is to be checked.
bool $strip Optional. Whether to attempt to strip out invalid UTF8. Default is false.
Returns
string The checked text.
Definition at line 1024 of file formatting.php.
References get_option(), and null.
Referenced by _wp_json_convert_string(), esc_attr(), esc_html(), esc_js(), and sanitize_text_field().
wp_encode_emoji ($content)
Convert any 4 byte emoji in a string to their equivalent HTML entity.
Currently, only Unicode 7 emoji are supported. Skin tone modifiers are allowed, all other Unicode 8 emoji will be added when the spec is finalised.
This allows us to store emoji in a DB using the utf8 character set.
Since
4.2.0
Parameters
string $content The content to encode.
Returns
string The encoded content.
Definition at line 4601 of file formatting.php.
References $content, and str_replace.
Referenced by wp_insert_post(), and wp_staticize_emoji().
wp_html_excerpt ($str, $count, $more = null)
Safely extracts not more than the first $count characters from html string.
UTF-8, tags and entities safe prefix extraction. Entities inside will NOT be counted as one character. For example & will be counted as 4, < as 3, etc.
Since
2.5.0
Parameters
string $str String to get the excerpt from.
int $count Maximum number of characters to take.
string $more Optional. What to append if $str needs to be trimmed. Defaults to empty string.
Returns
string The excerpt.
Definition at line 4107 of file formatting.php.
References $count, $excerpt, $more, null, and wp_strip_all_tags().
Referenced by WP_Comments_List_Table\column_author(), WP_Customize_Nav_Menus\customize_register(), do_trackbacks(), get_media_item(), and wp_admin_bar_site_menu().
wp_html_split ($input)
Separate HTML elements and comments from the text.
Since
4.2.4
Parameters
string $input The text which has to be formatted.
Returns
array The formatted text.
Definition at line 587 of file formatting.php.
References get_html_split_regex().
Referenced by do_shortcodes_in_html_tags(), and wp_replace_in_html_tags().
wp_iso_descrambler ($string)
Convert to ASCII from email subjects.
Since
1.2.0
Parameters
string $string Subject line
Returns
string Converted string to ASCII
Definition at line 2561 of file formatting.php.
References str_replace.
wp_make_link_relative ($link)
Convert full URL paths to absolute paths.
Removes the http or https protocols and the domain. Keeps the path '/' at the beginning, so it isn't a true relative link, but from the web root base.
Since
2.1.0
4.1.0 Support was added for relative URLs.
Parameters
string $link Full URL path.
Returns
string Absolute path.
Definition at line 3624 of file formatting.php.
References $link.
wp_parse_str ($string, & $array)
Parses a string into variables to be stored in an array.
Uses parse_str() and stripslashes if magic_quotes_gpc is on.
Since
2.2.1
Parameters
string $string The string to be parsed.
array $array Variables will be stored in this array.
Filter the array of variables derived from a parsed string.
Since
2.3.0
Parameters
array $array The array populated with variables.
Definition at line 3921 of file formatting.php.
References apply_filters(), and stripslashes_deep().
Referenced by add_query_arg(), GravityView_Entry_Link_Shortcode\get_link_atts(), GravityView_Entry_Link_Shortcode\maybe_add_field_values_query_args(), paginate_links(), wp_parse_args(), and wp_style_loader_src().
wp_pre_kses_less_than ($text)
Convert lone less than signs.
KSES already converts lone greater than signs.
Since
2.3.0
Parameters
string $text Text to be converted.
Returns
string Converted text.
Definition at line 3945 of file formatting.php.
References $text.
Referenced by sanitize_text_field().
wp_pre_kses_less_than_callback ($matches)
Callback function used by preg_replace.
Since
2.3.0
Parameters
array $matches Populated by matches to preg_replace.
Returns
string The text returned after esc_html if needed.
Definition at line 3957 of file formatting.php.
References esc_html().
wp_rel_nofollow ($text)
Adds rel nofollow string to all HTML A elements in content.
Since
1.5.0
Parameters
string $text Content that may contain HTML A elements.
Returns
string Converted content.
Definition at line 2318 of file formatting.php.
References $text, and wp_slash().
wp_rel_nofollow_callback ($matches)
Callback to add rel=nofollow string to HTML A element.
Will remove already existing rel="nofollow" and rel='nofollow' from the string to prevent from invalidating (X)HTML.
Since
2.3.0
Parameters
array $matches Single Match
Returns
string HTML A Element with rel nofollow.
Definition at line 2336 of file formatting.php.
References $name, $text, $value, home_url(), set_url_scheme(), and shortcode_parse_atts().
wp_replace_in_html_tags ($haystack, $replace_pairs)
Replace characters or phrases within HTML elements only.
Since
4.2.3
Parameters
string $haystack The text which has to be formatted.
array $replace_pairs In the form array('from' => 'to', ...).
Returns
string The formatted text.
Definition at line 724 of file formatting.php.
References $i, str_replace, and wp_html_split().
Referenced by WP_Embed\autoembed(), and wpautop().
wp_slash ($value)
Add slashes to a string or array of strings.
This should be used when preparing data for core API that expects slashed data. This should not be used to escape data going directly into an SQL query.
Since
3.6.0
Parameters
string | array $value String or array of strings to slash.
Returns
string|array Slashed $value
Definition at line 4393 of file formatting.php.
References $value.
Referenced by _wp_put_post_revision(), add_meta(), addslashes_gpc(), WP_Customize_Widgets\call_widget_update(), edit_post(), edit_user(), wp_xmlrpc_server\escape(), media_upload_form_handler(), WP_Press_This\side_load_images(), upgrade_160(), upgrade_230(), wp_ajax_inline_save(), wp_ajax_replyto_comment(), wp_ajax_save_attachment(), wp_create_user(), wp_handle_comment_submission(), wp_rel_nofollow(), wp_restore_post_revision(), wp_trash_post(), wp_untrash_post(), wp_update_category(), wp_update_comment(), wp_update_link(), wp_update_post(), and wp_update_term().
wp_spaces_regexp ()
Returns the regexp for common whitespace characters.
By default, spaces include new lines, tabs, nbsp entities, and the UTF-8 nbsp. This is designed to replace the PCRE sequence. In ticket #22692, that sequence was found to be unreliable due to random inclusion of the A0 byte.
Since
4.0.0
string $spaces
Returns
string The spaces regexp.
Filter the regexp for common whitespace characters.
This string is substituted for the sequence as needed in regular expressions. For websites not written in English, different characters may represent whitespace. For websites not encoded in UTF-8, the 0xC2 0xA0 sequence may not be in use.
Since
4.0.0
Parameters
string $spaces Regexp pattern for matching common whitespace characters.
Definition at line 4457 of file formatting.php.
References apply_filters().
Referenced by shortcode_unautop(), smilies_init(), wptexturize(), and wptexturize_primes().
wp_specialchars_decode ($string, $quote_style = ENT_NOQUOTES)
Converts a number of HTML entities into their special characters.
Specifically deals with: &, <, >, ", and '.
$quote_style can be set to ENT_COMPAT to decode " entities, or ENT_QUOTES to do both " and '. Default is ENT_NOQUOTES where no quotes are decoded.
Since
2.8.0
Parameters
string $string The text which is to be decoded.
string | int $quote_style Optional. Converts double quotes if set to ENT_COMPAT, both single and double if set to ENT_QUOTES or none if set to ENT_NOQUOTES. Also compatible with old _wp_specialchars() values; converting single quotes if set to 'single', double if set to 'double' or both if otherwise set. Default is ENT_NOQUOTES.
Returns
string The decoded text without HTML entities.
Definition at line 964 of file formatting.php.
References elseif, and false.
Referenced by admin_created_user_email(), retrieve_password(), send_confirmation_on_profile_email(), WP_Automatic_Updater\send_debug_email(), WP_Automatic_Updater\send_email(), update_option_new_admin_email(), wp_update_user(), wpmu_signup_blog_notification(), wpmu_signup_user_notification(), wpmu_welcome_notification(), and wpmu_welcome_user_notification().
wp_sprintf ($pattern)
WordPress implementation of PHP sprintf() with filters.
Since
2.5.0 string $pattern The string which formatted args are inserted. mixed $args ,... Arguments to be formatted into the $pattern string. string The formatted string.
Filter a fragment from the pattern passed to wp_sprintf().
If the fragment is unchanged, then sprintf() will be run on the fragment.
Since
2.5.0
Parameters
string $fragment A fragment from the pattern.
string $arg The argument.
Definition at line 3973 of file formatting.php.
References apply_filters(), and str_replace.
Referenced by get_the_taxonomies().
wp_sprintf_l ($pattern, $args)
Localize list items before the rest of the content.
The 'l' must be at the first characters can then contain the rest of the content. The list items will have ', ', ', and', and ' and ' added depending on the amount of list items in the $args parameter.
Since
2.5.0
Parameters
string $pattern Content containing 'l' at the beginning.
array $args List items to prepend to the content and replace 'l'.
Returns
string Localized list items and rest of the content.
Filter the translated delimiters used by wp_sprintf_l(). Placeholders (s) are included to assist translators and then removed before the array of strings reaches the filter.
Please note: Ampersands and entities should be avoided here.
Since
2.5.0
Parameters
array $delimiters An array of translated delimiters.
Definition at line 4047 of file formatting.php.
References $i, __, and apply_filters().
wp_staticize_emoji ($text)
Convert emoji to a static img element.
Since
4.2.0
Parameters
string $text The content to encode.
Returns
string The encoded content.
This filter is documented in wp-includes/formatting.php
This filter is documented in wp-includes/formatting.php
Definition at line 4643 of file formatting.php.
References $content, $i, $output, $text, apply_filters(), str_replace, and wp_encode_emoji().
Referenced by wp_staticize_emoji_for_email().
wp_staticize_emoji_for_email ($mail)
Convert emoji in emails into static images.
Since
4.2.0
Parameters
array $mail The email data array.
Returns
array The email data array, with emoji in the message staticized.
This filter is documented in wp-includes/pluggable.php
Definition at line 4725 of file formatting.php.
References $charset, $content, $name, apply_filters(), str_replace, and wp_staticize_emoji().
wp_strip_all_tags ($string, $remove_breaks = false)
Properly strip all HTML tags including script and style.
This differs from strip_tags() because it removes the contents of the <script> and <style> tags. E.g. `strip_tags('<script>something</script>')` will return 'something'. wp_strip_all_tags will return ''
Since
2.9.0
Parameters
string $string String containing HTML tags
bool $remove_breaks Optional. Whether to remove left over line breaks and white space chars
Returns
string The processed string.
Definition at line 4233 of file formatting.php.
Referenced by edit_post(), handle_confirmation_edit_submission(), media_upload_form_handler(), GFFormsModel\sanitize_conditional_logic(), GF_Field_Page\sanitize_settings(), GF_Field_Date\sanitize_settings(), GF_Field\sanitize_settings(), GF_Field_Address\sanitize_settings(), sanitize_text_field(), sanitize_user(), WP_Users_List_Table\single_row(), WP_List_Table\single_row_columns(), wp_ajax_save_attachment(), wp_html_excerpt(), and wp_trim_words().
wp_trim_excerpt ($text = '')
Generates an excerpt from the content, if needed.
The excerpt word amount will be 55 words and if the amount is greater than that, then the string ' […]' will be appended to the excerpt. If the string is less than 55 words, then the content will be returned as is.
The 55 word limit can be modified by plugins/themes using the excerpt_length filter The ' […]' string can be modified by plugins/themes using the excerpt_more filter
Since
1.5.0
Parameters
string $text Optional. The excerpt. If set to empty, an excerpt is generated.
Returns
string The excerpt.
This filter is documented in wp-includes/post-template.php
Filter the number of words in an excerpt.
Since
2.7.0
Parameters
int $number The number of words. Default 55.
Filter the string in the "more" link displayed after a trimmed excerpt.
Since
2.9.0
Parameters
string $more_string The string shown within the more link.
Filter the trimmed excerpt string.
Since
2.8.0
Parameters
string $text The trimmed text.
string $raw_excerpt The text prior to trimming.
Definition at line 2887 of file formatting.php.
References $text, apply_filters(), get_the_content(), str_replace, strip_shortcodes(), and wp_trim_words().
wp_trim_words ($text, $num_words = 55, $more = null)
Trims text to a certain number of words.
This function is localized. For languages that count 'words' by the individual character (such as East Asian languages), the $num_words argument will apply to the number of individual characters.
Since
3.3.0
Parameters
string $text Text to trim.
int $num_words Number of words. Default 55.
string $more Optional. What to append if $text needs to be trimmed. Default '…'.
Returns
string Trimmed text.
Filter the text content after words have been trimmed.
Since
3.3.0
Parameters
string $text The trimmed text.
int $num_words The number of words to trim the text to. Default 5.
string $more An optional string to append to the end of the trimmed text, e.g. ….
string $original_text The text before it was trimmed.
Definition at line 2941 of file formatting.php.
References $more, $text, __, _x, apply_filters(), get_option(), null, and wp_strip_all_tags().
Referenced by WP_Customize_Nav_Menu_Item_Setting\value_as_wp_post_nav_menu_item(), wp_dashboard_recent_drafts(), wp_setup_nav_menu_item(), wp_trim_excerpt(), and wp_widget_rss_output().
wp_unslash ($value)
Remove slashes from a string or array of strings.
This should be used to remove slashes from data passed to core API that expects data to be unslashed.
Since
3.6.0
Parameters
string | array $value String or array of strings to unslash.
Returns
string|array Unslashed $value
Definition at line 4420 of file formatting.php.
References $value, and stripslashes_deep().
Referenced by WP_Plugins_List_Table\__construct(), _admin_search_query(), WP_Themes_List_Table\_js_vars(), WP_MS_Themes_List_Table\_search_callback(), WP_Plugins_List_Table\_search_callback(), _wp_link_page(), add_meta(), add_metadata(), add_ping(), WP_Customize_Nav_Menus\ajax_search_available_items(), wp_xmlrpc_server\blogger_getPost(), wp_xmlrpc_server\blogger_getRecentPosts(), WP_Terms_List_Table\column_name(), WP_MS_Users_List_Table\column_username(), WP_Session_Tokens\create(), WP_Customize_Manager\customize_preview_settings(), delete_metadata(), display_setup_form(), WP_Customize_Manager\doing_ajax(), edit_post(), edit_user(), WP_Customize_Nav_Menus\export_preview_data(), get_default_link_to_edit(), get_default_post_to_edit(), get_pages(), WP_Customize_Widgets\get_post_value(), get_term_by(), WP_Terms_List_Table\handle_row_actions(), WP_MS_Users_List_Table\handle_row_actions(), install_blog(), install_plugin_information(), install_plugin_install_status(), install_plugins_favorites_form(), install_search_form(), install_theme_information(), install_theme_search_form(), media_upload_form_handler(), WP_Press_This\merge_or_fetch_data(), newblog_notify_siteadmin(), newuser_notify_siteadmin(), post_exists(), post_password_required(), WP_MS_Users_List_Table\prepare_items(), WP_Theme_Install_List_Table\prepare_items(), WP_Themes_List_Table\prepare_items(), WP_MS_Sites_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), WP_Terms_List_Table\prepare_items(), WP_Users_List_Table\prepare_items(), WP_Customize_Widgets\register_settings(), WP_Customize_Nav_Menus\render_menu(), request_filesystem_credentials(), WP_Customize_Setting\sanitize(), sanitize_comment_cookies(), self_link(), WP\send_headers(), WP_REST_Server\serve_request(), wp_xmlrpc_server\set_custom_fields(), WP_Press_This\side_load_images(), WP_Users_List_Table\single_row(), spawn_cron(), stream_preview_image(), term_exists(), trackback_url_list(), WP_Customize_Manager\unsanitized_post_values(), update_meta(), update_metadata(), wp_ajax_add_link_category(), wp_ajax_add_meta(), wp_ajax_ajax_tag_search(), wp_ajax_date_format(), wp_ajax_find_posts(), wp_ajax_heartbeat(), wp_ajax_nopriv_heartbeat(), wp_ajax_parse_embed(), wp_ajax_parse_media_shortcode(), wp_ajax_query_themes(), wp_ajax_save_attachment(), wp_ajax_save_wporg_username(), wp_ajax_send_attachment_to_editor(), wp_ajax_send_link_to_editor(), wp_ajax_time_format(), wp_ajax_wp_link_ajax(), wp_allow_comment(), wp_get_original_referer(), wp_get_raw_referer(), wp_get_referer(), wp_insert_comment(), wp_insert_link(), wp_insert_post(), wp_insert_term(), wp_insert_user(), wp_media_upload_handler(), wp_original_referer_field(), wp_prepare_themes_for_js(), wp_referer_field(), wp_save_image(), wp_xmlrpc_server\wp_setOptions(), wp_update_comment(), wp_update_term(), wpmu_log_new_registrations(), wpmu_validate_blog_signup(), and wpmu_welcome_notification().
wpautop ($pee, $br = true)
Replaces double line-breaks with paragraph elements.
A group of regex replaces used to identify text formatted with newlines and replace double line-breaks with HTML paragraph tags. The remaining line-breaks after conversion become <
> tags, unless $br is set to '0' or 'false'.
Since
0.71
Parameters
string $pee The text which has to be formatted.
bool $br Optional. If set, this will convert all remaining line-breaks after paragraphing. Default true.
Returns
string Text which has been converted into correct paragraph tags.
Definition at line 429 of file formatting.php.
References $i, $name, str_replace, and wp_replace_in_html_tags().
Referenced by GravityView_Compatibility\_shortcode_gf_notice(), GravityView_Admin_Notices\admin_notice(), GravityView_Extension\admin_notice(), GravityView_Search_WP_Widget\form(), gravityview_field_output(), GravityView_API\no_results(), GravityView_Post_Types\no_views_text(), GravityView_Widget_Custom_Content\render_frontend(), GravityView_Admin_Views\tooltips(), GravityView_Edit_Entry_Render\user_can_edit_entry(), GravityView_Edit_Entry_Render\user_can_edit_field(), WP_Widget_Text\widget(), and wp_richedit_pre().
wptexturize ($text, $reset = false)
Replaces common plain text characters into formatted entities.
As an example,
'cause today's effort makes it worth tomorrow's "holiday" ...
Becomes:
&#8217;cause today&#8217;s effort makes it worth tomorrow&#8217;s &#8220;holiday&#8221; &#8230;
Code within certain html blocks are skipped.
Do not use this function before the 'init' action hook; everything will break.
Since
0.71
array $wp_cockneyreplace Array of formatted entities for certain common phrases array $shortcode_tags array $static_characters array $static_replacements array $dynamic_characters array $dynamic_replacements array $default_no_texturize_tags array $default_no_texturize_shortcodes bool $run_texturize
Parameters
string $text The text to be formatted
bool $reset Set to true for unit testing. Translated patterns will reset.
Returns
string The string replaced with html entities
Filter whether to skip running wptexturize().
Passing false to the filter will effectively short-circuit wptexturize(). returning the original text passed to the function instead.
The filter runs only once, the first time wptexturize() is called.
Since
4.0.0
See also
wptexturize()
Parameters
bool $run_texturize Whether to short-circuit wptexturize().
Filter the list of HTML elements not to texturize.
Since
2.8.0
Parameters
array $default_no_texturize_tags An array of HTML element names.
Filter the list of shortcodes not to texturize.
Since
2.8.0
Parameters
array $default_no_texturize_shortcodes An array of shortcode names.
Definition at line 41 of file formatting.php.
References $shortcode_tags, $text, _get_wptexturize_shortcode_regex(), _get_wptexturize_split_regex(), _wptexturize_pushpop_element(), _x, apply_filters(), elseif, null, str_replace, wp_spaces_regexp(), and wptexturize_primes().
Referenced by _get_plugin_data_markup_translate(), gallery_shortcode(), get_archives_link(), hello_dolly_get_lyric(), WP_Theme\markup_header(), trackback_rdf(), and wp_get_document_title().
wptexturize_primes ($haystack, $needle, $prime, $open_quote, $close_quote)
Implements a logic tree to determine whether or not "7'." represents seven feet, then converts the special char into either a prime char or a closing quote char.
Since
4.3.0
Parameters
string $haystack The plain text to be searched.
string $needle The character to search for such as ' or ".
string $prime The prime char to use for replacement.
string $open_quote The opening quote char. Opening quote replacement must be accomplished already.
string $close_quote The closing quote char to use for replacement.
Returns
string The $haystack value after primes and quotes replacements.
Definition at line 306 of file formatting.php.
References $count, elseif, str_replace, and wp_spaces_regexp().
Referenced by wptexturize().
zeroise ($number, $threshold)
Add leading zeros when necessary.
If you set the threshold to '4' and the number is '10', then you will get back '0010'. If you set the threshold to '4' and the number is '5000', then you will get back '5000'.
Uses sprintf to append the amount of zeros based on the $threshold parameter and the size of the number. If the number is large enough, then no zeros will be appended.
Since
0.71
Parameters
int $number Number to append zeros to if not greater than threshold.
int $threshold Digit places number needs to be to not have zeros added.
Returns
string Adds leading zeros to number if needed.
Definition at line 1947 of file formatting.php.
Referenced by antispambot(), export_date_options(), get_calendar(), get_day_link(), WP_Locale\get_month(), get_month_link(), media_upload_library_form(), WP_List_Table\months_dropdown(), touch_time(), and wp_title().