GravityView: form_settings.php File Reference
form_settings.php File Reference
Data Structures
class GFConfirmationTable
class GFFormSettings
Functions
static activate_save ($form)
static deactivate_save ($form)
static delete_confirmation ($confirmation_id, $form_id)
Delete a form confirmation by ID.
static get_confirmation_ui_settings ($confirmation)
static get_tabs ($form_id)
static handle_confirmation_edit_submission ($confirmation, $form)
static is_unique_name ($name, $confirmations)
static maybe_process_confirmation_list_action ()
static notification_page ()
static output ($a)
static output_field_scripts ($echo=true)
static page_footer ()
static page_header ($title= '')
Function Documentation
static activate_save ($form) static
Definition at line 1620 of file form_settings.php.
References $form, $form_id, __, GFFormsModel\save_form_confirmations(), and GFFormsModel\save_form_notifications().
Referenced by GFFormSettings\form_settings_ui().
static deactivate_save ($form) static
Definition at line 1685 of file form_settings.php.
References $form, $form_id, GFFormsModel\save_form_confirmations(), and GFFormsModel\save_form_notifications().
Referenced by GFFormSettings\form_settings_ui().
static delete_confirmation ($confirmation_id, $form_id) static
Delete a form confirmation by ID.
Parameters
mixed $confirmation_id
mixed $form_id Can pass a form ID or a form object
Returns
mixed The result of the database operation
Fires right before the confirmation that a form is deleted
Parameters
int $form,['confirmations'][ $confirmation_id ] The delete confirmation object ID array $form The Form object to filter through
Definition at line 1563 of file form_settings.php.
References $form, $form_id, do_action(), GFFormsModel\flush_current_forms(), GFFormsModel\get_form_meta(), and GFFormsModel\save_form_confirmations().
Referenced by GFForms\delete_confirmation(), and maybe_process_confirmation_list_action().
static get_confirmation_ui_settings ($confirmation) static
These variables are used to convenient "wrap" child form settings in the appropriate HTML.
Definition at line 1179 of file form_settings.php.
References $class, $errors, $form, $form_id, __, _e, checked(), esc_html, GFFormsModel\get_form_meta(), gform_tooltip(), input, label, name, page, textarea, wp_dropdown_pages(), and wp_editor().
Referenced by GFFormSettings\confirmations_edit_page().
static get_tabs ($form_id) static
Definition at line 1442 of file form_settings.php.
References $form_id, __, apply_filters(), and null.
Referenced by GFForms\get_form_settings_sub_menu_items(), GFForms\modify_admin_title(), GFExport\page_header(), and page_header().
static handle_confirmation_edit_submission ($confirmation, $form) static
Definition at line 1456 of file form_settings.php.
References $form, $name, $url, __, absint(), ARRAY_A, esc_url, remove_query_arg(), GFFormsModel\sanitize_conditional_logic(), sanitize_text_field(), GFFormsModel\save_form_confirmations(), GFFormsModel\trim_conditional_logic_values_from_element(), and wp_strip_all_tags().
Referenced by GFFormSettings\confirmations_edit_page().
static is_unique_name ($name, $confirmations) static
Definition at line 1590 of file form_settings.php.
References $name.
Referenced by GFFormSettings\confirmations_edit_page().
static maybe_process_confirmation_list_action () static
Definition at line 1534 of file form_settings.php.
References $action, __, and delete_confirmation().
Referenced by GFFormSettings\confirmations_list_page().
static notification_page () static
Definition at line 1358 of file form_settings.php.
Referenced by GFFormSettings\form_settings_page().
static output ($a) static
Definition at line 1586 of file form_settings.php.
Referenced by WP_MatchesMapRegex\__construct(), and GravityView_Welcome\getting_started_screen().
static output_field_scripts ($echo = true) static
Definition at line 1600 of file form_settings.php.
References GF_Fields\get_all().
Referenced by GFFormSettings\confirmations_edit_page(), GFFeedAddOn\feed_edit_page(), and GFFormSettings\form_settings_ui().
static page_footer () static
Definition at line 1420 of file form_settings.php.
References height.
Referenced by GFFormSettings\confirmations_list_page(), GFExport\export_form_page(), GFExport\export_lead_page(), GFFormSettings\form_settings_ui(), GFExport\import_form_page(), and GFSettings\settings_page().
static page_header ($title = '') static
Definition at line 1366 of file form_settings.php.
References $form, $title, $url, _e, add_query_arg(), esc_html, GFFormsModel\get_form_meta(), get_tabs(), li, GFForms\top_toolbar(), wp_print_styles(), and wp_register_style().
Referenced by GFFormSettings\confirmations_edit_page(), GFFormSettings\confirmations_list_page(), GFExport\export_form_page(), GFExport\export_lead_page(), GFFormSettings\form_settings_ui(), GFExport\import_form_page(), notification_edit_page(), GFSettings\settings_page(), and GFSettings\settings_uninstall_page().