GravityView: forms_model.php File Reference
forms_model.php File Reference
Data Structures
class GFFormsModel
class RGFormsModel
Functions
gform_add_meta ($entry_id, $meta_key, $meta_value, $form_id=null)
Add metadata associated with an entry.
gform_delete_meta ($entry_id, $meta_key= '')
gform_get_meta ($entry_id, $meta_key)
gform_get_meta_values_for_entries ($entry_ids, $meta_keys)
gform_update_meta ($entry_id, $meta_key, $meta_value, $form_id=null)
Add or update metadata associated with an entry.
Variables
global $_gform_lead_meta = array()
const GFORMS_MAX_FIELD_LENGTH get_option('gform_longtext_ready') ? 4294967295 : 200
if (!class_exists('GFForms'))
Function Documentation
gform_add_meta ($entry_id, $meta_key, $meta_value, $form_id = null)
Add metadata associated with an entry.
Data will be serialized; Don't forget to sanitize user input.
Parameters
int $entry_id The ID of the entry where metadata is to be added
string $meta_key The key for the meta data to be stored
mixed $meta_value The data to be stored for the entry
int | null $form_id The form ID of the entry (optional, saves extra query if passed when creating the metadata)
Definition at line 5373 of file forms_model.php.
References $_gform_lead_meta, $form_id, $wpdb, GFFormsModel\get_lead_meta_table_name(), GFFormsModel\get_lead_table_name(), and maybe_serialize().
Referenced by GravityView_Uninstall_Test\_set_up_entry_meta().
gform_delete_meta ($entry_id, $meta_key = '')
Definition at line 5392 of file forms_model.php.
References $_gform_lead_meta, $wpdb, and GFFormsModel\get_lead_meta_table_name().
Referenced by GFFormsModel\delete_lead(), GFFormsModel\refresh_product_cache(), and GFAPI\update_entry().
gform_get_meta ($entry_id, $meta_key)
Definition at line 5268 of file forms_model.php.
References $_gform_lead_meta, $value, $wpdb, GFFormsModel\get_lead_meta_table_name(), maybe_unserialize(), and null.
Referenced by GravityView_Uninstall_Test\_set_up_entry_meta(), GravityView_Admin_ApproveEntries\add_entry_approved_hidden_input(), GFFormsModel\get_encrypted_fields(), GravityView_API\get_entry_slug(), GFFeedAddOn\get_feeds_by_entry(), gform_update_meta(), GravityView_frontend\is_entry_approved(), GFPaymentAddOn\is_payment_gateway(), GFFeedAddOn\maybe_process_feed(), and GFFormsModel\refresh_product_cache().
gform_get_meta_values_for_entries ($entry_ids, $meta_keys)
Definition at line 5286 of file forms_model.php.
References $wpdb, GFFormsModel\get_lead_meta_table_name(), maybe_unserialize(), and null.
Referenced by GravityView_Uninstall_Test\_check_deleted_entry_meta(), and GFFormsModel\build_lead_array().
gform_update_meta ($entry_id, $meta_key, $meta_value, $form_id = null)
Add or update metadata associated with an entry.
Data will be serialized. Don't forget to sanitize user input.
Parameters
int $entry_id The ID of the entry to be updated
string $meta_key The key for the meta data to be stored
mixed $meta_value The data to be stored for the entry
int | null $form_id The form ID of the entry (optional, saves extra query if passed when creating the metadata)
Definition at line 5334 of file forms_model.php.
References $_gform_lead_meta, $form_id, $wpdb, GFFormsModel\get_lead_meta_table_name(), GFFormsModel\get_lead_table_name(), gform_get_meta(), and maybe_serialize().
Referenced by GFAPI\add_entry(), GravityView_API\entry_create_custom_slug(), GFPaymentAddOn\entry_post_save(), GravityView_API\get_entry_slug(), GFFeedAddOn\maybe_process_feed(), GFFormsModel\set_encrypted_fields(), GFFormsModel\set_entry_meta(), GravityView_Admin_ApproveEntries\update_approved_meta(), and GFAPI\update_entry().
Variable Documentation
$_gform_lead_meta = array()
Definition at line 5264 of file forms_model.php.
Referenced by gform_add_meta(), gform_delete_meta(), gform_get_meta(), and gform_update_meta().
const GFORMS_MAX_FIELD_LENGTH get_option('gform_longtext_ready') ? 4294967295 : 200
Definition at line 10 of file forms_model.php.
Referenced by GFFormsModel\build_lead_array(), GFFormsModel\get_lead_field_value(), GFFormsModel\is_duplicate(), GFForms\setup_database(), and GFFormsModel\update_lead_field_value().
if(!class_exists('GFForms'))
Definition at line 3 of file forms_model.php.
Referenced by GFFormsModel\build_lead_array().