GravityView: functions.wp-styles.php File Reference
functions.wp-styles.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
wp_add_inline_style ($handle, $data)
Add extra CSS styles to a registered stylesheet.
wp_dequeue_style ($handle)
Remove a previously enqueued CSS stylesheet.
wp_deregister_style ($handle)
Remove a registered stylesheet.
wp_enqueue_style ($handle, $src=false, $deps=array(), $ver=false, $media= 'all')
Enqueue a CSS stylesheet.
wp_print_styles ($handles=false)
Display styles that are in the $handles queue.
wp_register_style ($handle, $src, $deps=array(), $ver=false, $media= 'all')
Register a CSS stylesheet.
wp_style_add_data ($handle, $key, $value)
Add metadata to a CSS stylesheet.
wp_style_is ($handle, $list= 'enqueued')
Check whether a CSS stylesheet has been added to the queue.
wp_styles ()
Initialize $wp_styles if it has not been set.
Function Documentation
wp_add_inline_style ($handle, $data)
Add extra CSS styles to a registered stylesheet.
Styles will only be added if the stylesheet in already in the queue. Accepts a string $data containing the CSS. If two or more CSS code blocks are added to the same stylesheet $handle, they will be printed in the order they were added, i.e. the latter added styles can redeclare the previous.
See also
WP_Styles::add_inline_style()
Since
3.3.0
Parameters
string $handle Name of the stylesheet to add the extra styles to. Must be lowercase.
string $data String containing the CSS styles to be added.
Returns
bool True on success, false on failure.
Definition at line 83 of file functions.wp-styles.php.
References __, _doing_it_wrong(), _wp_scripts_maybe_doing_it_wrong(), and wp_styles().
Referenced by twentyfifteen_color_scheme_css(), twentyfifteen_header_background_color_css(), twentyfifteen_post_nav_background(), and twentyfifteen_sidebar_text_color_css().
wp_dequeue_style ($handle)
Remove a previously enqueued CSS stylesheet.
See also
WP_Dependencies::dequeue()
Since
3.1.0
Parameters
string $handle Name of the stylesheet to be removed.
Definition at line 176 of file functions.wp-styles.php.
References _wp_scripts_maybe_doing_it_wrong(), and wp_styles().
Referenced by GravityView_Admin\no_conflict_styles().
wp_deregister_style ($handle)
Remove a registered stylesheet.
See also
WP_Dependencies::remove()
Since
2.1.0
Parameters
string $handle Name of the stylesheet to be removed.
Definition at line 128 of file functions.wp-styles.php.
References _wp_scripts_maybe_doing_it_wrong(), and wp_styles().
wp_enqueue_style ($handle, $src = false, $deps = array(), $ver = false, $media = 'all')
Enqueue a CSS stylesheet.
Registers the style if source provided (does NOT overwrite) and enqueues.
See also
WP_Dependencies::add()
WP_Dependencies::enqueue() List of CSS media types. 2.6.0 string $handle Name of the stylesheet. string|bool $src Path to the stylesheet from the root directory of WordPress. Example: '/css/mystyle.css'. array $deps An array of registered style handles this stylesheet depends on. Default empty array. string|bool $ver String specifying the stylesheet version number, if it has one. This parameter is used to ensure that the correct version is sent to the client regardless of caching, and so should be included if a version number is available and makes sense for the stylesheet. string $media Optional. The media for which this stylesheet has been defined. Default 'all'. Accepts 'all', 'aural', 'braille', 'handheld', 'projection', 'print', 'screen', 'tty', or 'tv'.
Definition at line 155 of file functions.wp-styles.php.
References $wp_styles, _wp_scripts_maybe_doing_it_wrong(), and wp_styles().
Referenced by GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GravityView_frontend\add_style(), add_thickbox(), GravityView_Recent_Entries_Widget\admin_enqueue_scripts(), Custom_Background\admin_load(), Custom_Image_Header\css_includes(), WP_Customize_Nav_Menus\customize_preview_enqueue_deps(), WP_Customize_Color_Control\enqueue(), GFForms\enqueue_admin_scripts(), GravityView_Widget_Search\enqueue_datepicker(), enqueue_embed_scripts(), GFFormDisplay\enqueue_form_scripts(), GFLocking\enqueue_list_scripts(), WP_Internal_Pointers\enqueue_scripts(), GFLocking\enqueue_scripts(), WP_Customize_Nav_Menus\enqueue_scripts(), GFAddOn\enqueue_scripts(), WP_Customize_Widgets\enqueue_scripts(), _WP_Editors\enqueue_scripts(), GravityView_Widget_Poll\enqueue_scripts_and_styles(), GFLocking\enqueue_view_page_scripts(), WP_Press_This\html(), iframe_header(), WP_Admin_Bar\initialize(), GFFormDisplay\print_form_scripts(), print_tooltip_scripts(), GravityView_View\render_widget_hooks(), twentyeleven_admin_enqueue_scripts(), twentyeleven_enqueue_color_scheme(), twentyfifteen_scripts(), twentyfourteen_admin_fonts(), twentyfourteen_scripts(), twentythirteen_custom_header_fonts(), twentythirteen_scripts_styles(), twentytwelve_custom_header_fonts(), twentytwelve_scripts_styles(), wp_admin_css(), wp_audio_shortcode(), wp_auth_check_load(), wp_enqueue_media(), wp_iframe(), wp_playlist_scripts(), and wp_video_shortcode().
wp_print_styles ($handles = false)
Display styles that are in the $handles queue.
Passing an empty array to $handles prints the queue, passing an array with one string prints that style, and passing an array of strings prints those styles.
WP_Styles $wp_styles The WP_Styles object for printing styles.
Since
2.6.0
Parameters
string | bool | array $handles Styles to be printed. Default 'false'.
Returns
array On success, a processed array of WP_Dependencies items; otherwise, an empty array.
Fires before styles in the $handles queue are printed.
Since
2.6.0
Definition at line 42 of file functions.wp-styles.php.
References $wp_styles, _wp_scripts_maybe_doing_it_wrong(), do_action(), and wp_styles().
Referenced by GFForms\addons_page(), GF_Installation_Wizard\display(), _WP_Editors\editor(), GFFormList\form_list_page(), GFForms\handle_ajax_do_shortcode(), GFEntryList\leads_page(), GFSettings\page_header(), GFExport\page_header(), page_header(), GFFormDisplay\print_form_scripts(), print_tooltip_scripts(), GFSelectColumns\select_columns_page(), GFUpdate\update_page(), and wp_admin_css().
wp_register_style ($handle, $src, $deps = array(), $ver = false, $media = 'all')
Register a CSS stylesheet.
See also
WP_Dependencies::add() List of CSS media types. 2.6.0 4.3.0 A return value was added. string $handle Name of the stylesheet. string|bool $src Path to the stylesheet from the WordPress root directory. Example: '/css/mystyle.css'. array $deps An array of registered style handles this stylesheet depends on. Default empty array. string|bool $ver String specifying the stylesheet version number. Used to ensure that the correct version is sent to the client regardless of caching. Default 'false'. Accepts 'false', 'null', or 'string'. string $media Optional. The media for which this stylesheet has been defined. Default 'all'. Accepts 'all', 'aural', 'braille', 'handheld', 'projection', 'print', 'screen', 'tty', or 'tv'. bool Whether the style has been registered. True on success, false on failure.
Definition at line 113 of file functions.wp-styles.php.
References _wp_scripts_maybe_doing_it_wrong(), and wp_styles().
Referenced by GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GF_Installation_Wizard\display(), GFAddOn\enqueue_print_styles(), GFAddOn\enqueue_scripts(), GFSettings\page_header(), GFExport\page_header(), page_header(), GFLocking\register_scripts(), GFForms\register_scripts(), and GravityView_Template\register_styles().
wp_style_add_data ($handle, $key, $value)
Add metadata to a CSS stylesheet.
Works only if the stylesheet has already been added.
Possible values for $key and $value: 'conditional' string Comments for IE 6, lte IE 7 etc. 'rtl' bool|string To declare an RTL stylesheet. 'suffix' string Optional suffix, used in combination with RTL. 'alt' bool For rel="alternate stylesheet". 'title' string For preferred/alternate stylesheets.
See also
WP_Dependency::add_data()
Since
3.6.0
Parameters
string $handle Name of the stylesheet.
string $key Name of data point for which we're storing a value. Accepts 'conditional', 'rtl' and 'suffix', 'alt' and 'title'.
mixed $value String containing the CSS data to be added.
Returns
bool True on success, false on failure.
Definition at line 220 of file functions.wp-styles.php.
References $value, and wp_styles().
Referenced by twentyfifteen_scripts(), twentyfourteen_scripts(), and twentythirteen_scripts_styles().
wp_style_is ($handle, $list = 'enqueued')
Check whether a CSS stylesheet has been added to the queue.
Since
2.8.0
Parameters
string $handle Name of the stylesheet.
string $list Optional. Status of the stylesheet to check. Default 'enqueued'. Accepts 'enqueued', 'registered', 'queue', 'to_do', and 'done'.
Returns
bool Whether style is queued.
Definition at line 192 of file functions.wp-styles.php.
References $list, _wp_scripts_maybe_doing_it_wrong(), and wp_styles().
Referenced by GravityView_frontend\add_style(), GFFormDisplay\print_form_scripts(), and twentytwelve_body_class().
wp_styles ()
Initialize $wp_styles if it has not been set.
WP_Styles $wp_styles
Since
4.2.0
Returns
WP_Styles WP_Styles instance.
Definition at line 20 of file functions.wp-styles.php.
References $wp_styles.
Referenced by _print_styles(), print_admin_styles(), wp_add_inline_style(), wp_admin_css(), wp_dequeue_style(), wp_deregister_style(), wp_enqueue_style(), wp_print_styles(), wp_register_style(), wp_style_add_data(), and wp_style_is().