GravityView: functions.wp-scripts.php File Reference
functions.wp-scripts.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_scripts_maybe_doing_it_wrong ($function)
Helper function to output a _doing_it_wrong message when applicable.
wp_dequeue_script ($handle)
Remove a previously enqueued script.
wp_deregister_script ($handle)
Remove a registered script.
wp_enqueue_script ($handle, $src=false, $deps=array(), $ver=false, $in_footer=false)
Enqueue a script.
wp_localize_script ($handle, $object_name, $l10n)
Localize a script.
wp_print_scripts ($handles=false)
Print scripts in document head that are in the $handles queue.
wp_register_script ($handle, $src, $deps=array(), $ver=false, $in_footer=false)
Register a new script.
wp_script_add_data ($handle, $key, $value)
Add metadata to a script.
wp_script_is ($handle, $list= 'enqueued')
Check whether a script has been added to the queue.
wp_scripts ()
Initialize $wp_scripts if it has not been set.
Function Documentation
_wp_scripts_maybe_doing_it_wrong ($function)
Helper function to output a _doing_it_wrong message when applicable.
Since
4.2.0
Parameters
string $function Function name.
Definition at line 36 of file functions.wp-scripts.php.
References __, _doing_it_wrong(), and did_action().
Referenced by wp_add_inline_style(), wp_dequeue_script(), wp_dequeue_style(), wp_deregister_script(), wp_deregister_style(), wp_enqueue_script(), wp_enqueue_style(), wp_localize_script(), wp_print_scripts(), wp_print_styles(), wp_register_script(), wp_register_style(), wp_script_is(), and wp_style_is().
wp_dequeue_script ($handle)
Remove a previously enqueued script.
See also
WP_Dependencies::dequeue()
Since
3.1.0
Parameters
string $handle Name of the script to be removed.
Definition at line 254 of file functions.wp-scripts.php.
References _wp_scripts_maybe_doing_it_wrong(), and wp_scripts().
wp_deregister_script ($handle)
Remove a registered script.
Note: there are intentional safeguards in place to prevent critical admin scripts, such as jQuery core, from being unregistered.
See also
WP_Dependencies::remove()
Since
2.6.0
Parameters
string $handle Name of the script to be removed.
Do not allow accidental or negligent de-registering of critical scripts in the admin. Show minimal remorse if the correct hook is used.
Definition at line 173 of file functions.wp-scripts.php.
References $GLOBALS, $message, __, _doing_it_wrong(), _wp_scripts_maybe_doing_it_wrong(), current_filter(), is_admin(), and wp_scripts().
wp_enqueue_script ($handle, $src = false, $deps = array(), $ver = false, $in_footer = false)
Enqueue a script.
Registers the script if $src provided (does NOT overwrite), and enqueues it.
See also
WP_Dependencies::add()
WP_Dependencies::add_data()
WP_Dependencies::enqueue()
Since
2.6.0
Parameters
string $handle Name of the script.
string | bool $src Path to the script from the root directory of WordPress. Example: '/js/myscript.js'.
array $deps An array of registered handles this script depends on. Default empty array.
string | bool $ver Optional. String specifying the script version number, if it has one. This parameter is used to ensure that the correct version is sent to the client regardless of caching, and so should be included if a version number is available and makes sense for the script.
bool $in_footer Optional. Whether to enqueue the script before </head> or before </body>. Default 'false'. Accepts 'false' or 'true'.
Definition at line 224 of file functions.wp-scripts.php.
References $wp_scripts, _wp_scripts_maybe_doing_it_wrong(), and wp_scripts().
Referenced by GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), add_thickbox(), GravityView_Recent_Entries_Widget\admin_enqueue_scripts(), Custom_Background\admin_load(), WP_Customize_Widgets\customize_preview_enqueue(), WP_Customize_Nav_Menus\customize_preview_enqueue_deps(), WP_Customize_Manager\customize_preview_init(), do_accordion_sections(), WP_Customize_Header_Image_Control\enqueue(), WP_Customize_Color_Control\enqueue(), WP_Customize_Cropped_Image_Control\enqueue(), GFForms\enqueue_admin_scripts(), enqueue_comment_hotkeys_js(), GravityView_Widget_Search\enqueue_datepicker(), GFFormDisplay\enqueue_form_scripts(), GravityView_Admin_Views\enqueue_gravity_forms_scripts(), GFLocking\enqueue_list_scripts(), WP_Internal_Pointers\enqueue_scripts(), GFLocking\enqueue_scripts(), WP_Customize_Nav_Menus\enqueue_scripts(), Featured_Content\enqueue_scripts(), GFAddOn\enqueue_scripts(), WP_Customize_Widgets\enqueue_scripts(), _WP_Editors\enqueue_scripts(), GravityView_Widget_Poll\enqueue_scripts_and_styles(), GFLocking\enqueue_view_page_scripts(), WP_Press_This\html(), WP_Admin_Bar\initialize(), Custom_Image_Header\js_includes(), GravityView_Support_Port\maybe_enqueue_script(), media_upload_gallery(), GFFormDisplay\print_form_scripts(), GV_License_Handler\settings_edd_license_activation(), twentyeleven_admin_enqueue_scripts(), twentyeleven_customize_preview_js(), twentyfifteen_customize_control_js(), twentyfifteen_customize_preview_js(), twentyfifteen_scripts(), twentyfourteen_customize_preview_js(), twentyfourteen_scripts(), twentythirteen_customize_preview_js(), twentythirteen_scripts_styles(), twentytwelve_customize_preview_js(), twentytwelve_scripts_styles(), wp_audio_shortcode(), wp_auth_check_load(), wp_enqueue_media(), wp_media_upload_handler(), wp_oembed_add_host_js(), wp_playlist_scripts(), and wp_video_shortcode().
wp_localize_script ($handle, $object_name, $l10n)
Localize a script.
Works only if the script has already been added.
Accepts an associative array $l10n and creates a JavaScript object:
"$object_name" = {
    key: value,
    key: value,
    ...
}
See also
WP_Dependencies::localize() WP_Scripts $wp_scripts The WP_Scripts object for printing scripts. 2.6.0 todo 55. string $handle Script handle the data will be attached to. string $object_name Name for the JavaScript object. Passed directly, so it should be qualified JS variable. Example: '/[a-zA-Z0-9_]+/'. array $l10n The data itself. The data can be either a single or multi-dimensional array. bool True if the script was successfully localized, false otherwise.
Definition at line 151 of file functions.wp-scripts.php.
References $wp_scripts, and _wp_scripts_maybe_doing_it_wrong().
Referenced by GravityView_Support_Port\_localize_script(), GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GravityView_Recent_Entries_Widget\admin_enqueue_scripts(), WP_Customize_Background_Image_Control\enqueue(), WP_Customize_Header_Image_Control\enqueue(), GFForms\enqueue_admin_scripts(), GFLocking\enqueue_list_scripts(), GFLocking\enqueue_scripts(), WP_Customize_Nav_Menus\enqueue_scripts(), GFAddOn\enqueue_scripts(), GFLocking\enqueue_view_page_scripts(), GFForms\register_scripts(), GV_License_Handler\settings_edd_license_activation(), twentyfifteen_customize_control_js(), twentyfifteen_scripts(), twentyfourteen_scripts(), wp_enqueue_media(), and wp_just_in_time_script_localization().
wp_print_scripts ($handles = false)
Print scripts in document head that are in the $handles queue.
Called by admin-header.php and wp_head hook. Since it is called by wp_head on every page load, the function does not instantiate the WP_Scripts object unless script names are explicitly passed. Makes use of already-instantiated $wp_scripts global if present. Use provided wp_print_scripts hook to register/enqueue new scripts.
See also
WP_Scripts::do_items() WP_Scripts $wp_scripts The WP_Scripts object for printing scripts.
Since
2.6.0
Parameters
string | bool | array $handles Optional. Scripts to be printed. Default 'false'.
Returns
array On success, a processed array of WP_Dependencies items; otherwise, an empty array.
Fires before scripts in the $handles queue are printed.
Since
2.1.0
Definition at line 65 of file functions.wp-scripts.php.
References $wp_scripts, _wp_scripts_maybe_doing_it_wrong(), do_action(), and wp_scripts().
Referenced by CreatePlaceholdersUI(), GFForms\handle_ajax_do_shortcode(), GFFormDisplay\print_form_scripts(), GravityView_Edit_Entry_Render\print_scripts(), print_tooltip_scripts(), GFSelectColumns\select_columns_page(), wp_ajax_parse_embed(), and wp_ajax_parse_media_shortcode().
wp_register_script ($handle, $src, $deps = array(), $ver = false, $in_footer = false)
Register a new script.
Registers a script to be linked later using the wp_enqueue_script() function.
See also
WP_Dependencies::add()
WP_Dependencies::add_data()
Since
2.6.0
4.3.0 A return value was added.
Parameters
string $handle Name of the script. Should be unique.
string $src Path to the script from the WordPress root directory. Example: '/js/myscript.js'.
array $deps Optional. An array of registered script handles this script depends on. Set to false if there are no dependencies. Default empty array.
string | bool $ver Optional. String specifying script version number, if it has one, which is concatenated to end of path as a query string. If no version is specified or set to false, a version number is automatically added equal to current installed WordPress version. If set to null, no version is added. Default 'false'. Accepts 'false', 'null', or 'string'.
bool $in_footer Optional. Whether to enqueue the script before </head> or before </body>. Default 'false'. Accepts 'false' or 'true'.
Returns
bool Whether the script has been registered. True on success, false on failure.
Definition at line 111 of file functions.wp-scripts.php.
References $registered, $wp_scripts, _wp_scripts_maybe_doing_it_wrong(), and wp_scripts().
Referenced by GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GFAddOn\enqueue_scripts(), GravityView_Edit_Entry_Render\print_scripts(), GFLocking\register_scripts(), and GFForms\register_scripts().
wp_script_add_data ($handle, $key, $value)
Add metadata to a script.
Works only if the script has already been added.
Possible values for $key and $value: 'conditional' string Comments for IE 6, lte IE 7, etc.
Since
4.2.0
See also
WP_Dependency::add_data()
Parameters
string $handle Name of the script.
string $key Name of data point for which we're storing a value.
mixed $value String containing the data to be added.
Returns
bool True on success, false on failure.
Definition at line 294 of file functions.wp-scripts.php.
References $value, and wp_scripts().
wp_script_is ($handle, $list = 'enqueued')
Check whether a script has been added to the queue.
Since
2.8.0
3.5.0 'enqueued' added as an alias of the 'queue' list.
Parameters
string $handle Name of the script.
string $list Optional. Status of the script to check. Default 'enqueued'. Accepts 'enqueued', 'registered', 'queue', 'to_do', and 'done'.
Returns
bool Whether the script is queued.
Definition at line 271 of file functions.wp-scripts.php.
References $list, _wp_scripts_maybe_doing_it_wrong(), and wp_scripts().
Referenced by GFFormDisplay\enqueue_form_scripts(), GFFormDisplay\get_form_init_scripts(), and GFFormDisplay\print_form_scripts().
wp_scripts ()
Initialize $wp_scripts if it has not been set.
WP_Scripts $wp_scripts
Since
4.2.0
Returns
WP_Scripts WP_Scripts instance.
Definition at line 20 of file functions.wp-scripts.php.
References $wp_scripts.
Referenced by _wp_customize_loader_settings(), WP_Customize_Nav_Menus\enqueue_scripts(), print_head_scripts(), wp_dequeue_script(), wp_deregister_script(), wp_enqueue_script(), wp_plupload_default_settings(), wp_print_scripts(), wp_register_script(), wp_script_add_data(), and wp_script_is().