GravityView: gravityview.php File Reference
future/gravityview.php File Reference
Functions
gravityview ()
The main GravityView wrapper function.
Variables
if (! defined('GRAVITYVIEW_DIR')) = apply_filters('gravityview/fields/custom/content_after', $content)
If this file is called directly, abort.
Function Documentation
gravityview()
gravityview ()
The main GravityView wrapper function.
Exposes classes and functionality via the instance.
Since
2.0
Returns
A global Core instance.
Definition at line 26 of file future/gravityview.php.
Referenced by GravityView_Admin\__construct(), GravityView_Widget_Gravity_Forms\__construct(), GravityView_Extension\__construct(), GravityView_Lightbox\__construct(), GF_Entry\__construct(), GF_Form\__construct(), Template\__construct(), Legacy_Override_Template\__construct(), GravityView_Field\__construct(), GravityView_Entry_Approval_Merge_Tags\_filter_gform_form_settings_fields(), GravityView_Entry_Approval_Merge_Tags\_filter_gform_replace_merge_tags(), GravityView_Widget_Gravity_Forms\_get_form_choices(), _gravityview_process_posted_fields(), Request\_has_field_key(), GravityView_Entry_Approval\_send_notifications(), Plugin\activate(), Form_Collection\add(), Widget_Collection\add(), View_Collection\add(), Field_Collection\add(), Shortcode\add(), Entry_Collection\add(), GravityView_Admin_Views\add_custom_column_content(), GravityView_Field\add_entry_meta(), GravityView_Admin_Bar\add_floaty_icon(), GravityView_Plugin_Hooks_Yoast_SEO\add_hooks(), GravityView_Theme_Hooks_Elegant_Themes\add_hooks_admin_init(), GravityView_View\add_id_specific_templates(), GravityView_Admin_Notices\add_notice(), Extension\add_notice(), GravityView_oEmbed\add_provider(), GravityView_Widget_Search\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), Widget\add_shortcode(), GravityView_frontend\add_style(), GravityView_Theme_Hooks_WPML\add_url_hooks(), GravityView_Admin_Notices\admin_notice(), GravityView_Entry_Approval\after_submission(), GravityView_Entry_Approval\ajax_update_approved(), GravityView_Field\as_array(), Join\as_query_join(), GravityView_Change_Entry_Creator\assign_new_user_to_lead(), GravityView_Cache\blocklist_add(), GravityView_Cache\blocklist_remove(), GF_Field\by_id(), GVCommon\calculate_get_entries_criteria(), gvfield\callback(), gravityview\callback(), gvlogic\callback(), Shortcode\callback(), View\can_render(), GVCommon\check_entry_display(), GravityView_Compatibility\check_gravityforms(), GravityView_Compatibility\check_php(), GravityView_Admin_Notices\check_show_multisite_notices(), GravityView_Delete_Entry\check_user_cap_delete_entry(), GravityView_Duplicate_Entry\check_user_cap_duplicate_entry(), GravityView_Edit_Entry\check_user_cap_edit_entry(), GravityView_Compatibility\check_wordpress(), GravityView_Field_List\column_value(), View\content(), GravityView_Ajax\create_preset_form(), GravityView_Field_Is_Approved\custom_merge_tags(), GravityView_Edit_Entry_Render\custom_validation(), View_Settings\defaults(), GravityView_Cache\delete(), GravityView_Cache\delete_expired_transients(), GravityView_Entry_Notes\delete_notes(), GravityView_Delete_Entry\delete_or_trash_entry(), GravityView_API\directory_link(), Renderer\disable_show_only_approved_entries(), GravityView_Duplicate_Entry\duplicate_entry(), GravityView_Field_Post_Custom_Field\edit_entry_field_value(), GravityView_Field_Total\edit_entry_recalculate_totals(), GravityView_Change_Entry_Creator\enqueue_selectwoo_assets(), GravityView_Cache\entry_added(), GravityView_API\entry_create_custom_slug(), GravityView_Cache\entry_created(), GravityView_API\entry_link_html(), GravityView_Cache\entry_property_changed(), GravityView_Cache\entry_status_changed(), GravityView_Cache\entry_updated(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_API\field_value(), GravityView_Edit_Entry_Render\filter_conditional_logic(), GravityView_Widget_Search\filter_entries(), GravityView_Uninstall\fire_everything(), GF_Field\from_configuration(), Internal_Field\from_configuration(), Field\from_configuration(), View\from_post(), views\get(), Field\get(), GravityView_Cache\get(), GravityView_Field_Notes\get_add_note_part(), GravityView_Admin_Views\get_available_fields(), Entry_Template\get_back_label(), GravityView_Admin_Duplicate_View\get_clone_view_link(), GravityView_Field_Date_Updated\get_content(), GravityView_Delete_Entry\get_delete_link(), GravityView_Duplicate_Entry\get_duplicate_link(), GVCommon\get_entries(), View\get_entries(), GravityView_Entry_Link_Shortcode\get_entry(), GVCommon\get_entry(), GravityView_oEmbed\get_entry_id(), GravityView_API\get_entry_slug(), Internal_Source\get_field(), Source\get_field(), GF_Form\get_field(), GravityView_Ajax\get_field_options(), GravityView_Field_FileUpload\get_files_array(), GravityView_Admin_ApproveEntries\get_first_form_id(), GravityView_Widget_Search\get_formatted_date(), Plugin\get_gravityforms_version(), GravityView_Settings\get_instance(), View\get_joined_forms(), View\get_joins(), GF_Field\get_label(), GravityView_Field_Notes\get_note_email_fields(), gvlogic\get_output(), Entry\get_permalink(), GravityView_Ajax\get_preset_fields_config(), GravityView_Widget_Search\get_search_class(), GravityView_frontend\get_search_criteria(), GravityView_frontend\get_search_criteria_paging(), View\get_unions(), GravityView_Powered_By\get_url(), Internal_Field\get_value(), GF_Field\get_value(), GravityView_oEmbed\getInstance(), GravityView_View\getPaginationCounts(), Plugin_Settings\getSetting(), GravityView_Welcome\getting_started_screen(), GV\Mocks\GravityView_API_field_label(), GV\Mocks\GravityView_API_field_value(), gravityview_css_url(), gravityview_field_output(), GV\Mocks\GravityView_frontend_get_view_entries(), gravityview_get_context(), gravityview_get_current_views(), gravityview_get_input_id_from_id(), gravityview_is_admin_page(), gravityview_ob_include(), GravityView_Ajax\import_fields(), GravityView_Ajax\import_form(), GravityView_Cache\in_blocklist(), Plugin\include_legacy_core(), Plugin\include_legacy_frontend(), GravityView_Plugin_Hooks_Pageviews\increment_callback(), Core\init(), GravityView_Edit_Entry_Render\init(), GravityView_oEmbed\initialize(), GravityView_frontend\insert_view_in_content(), Logger\interpolate(), GravityView_Lightbox_Provider\is_active(), GravityView_Admin\is_admin_page(), GravityView_Field\is_choice_value_enabled(), GravityView_Edit_Entry_Render\is_edit_entry(), Request\is_entry(), GravityView_frontend\is_entry_approved(), Extension\is_extension_supported(), Widget\is_registered(), GravityView_Entry_Approval_Merge_Tags\is_request_valid(), GravityView_Compatibility\is_valid(), GravityView_Compatibility\is_valid_gravity_forms(), GravityView_Compatibility\is_valid_php(), GravityView_Compatibility\is_valid_wordpress(), Legacy_Context\load(), Extension\load_plugin_textdomain(), Blocks\localize_block_assets(), GravityView_Powered_By\maybe_add_link(), GravityView_Field_Notes\maybe_add_note(), GravityView_Support_Port\maybe_display_helpscout_beacon(), GravityView_Duplicate_Entry\maybe_duplicate_list(), GravityView_Edit_Entry_Locking\maybe_enqueue_scripts(), Renderer\maybe_print_reserved_slugs_notice(), GravityView_Plugin_Hooks_Gravity_Forms_Partial_Entries\maybe_save_partial_entry(), GravityView_Field_Notes\maybe_send_entry_notes(), GravityView_Entry_Approval_Merge_Tags\maybe_update_approved(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), Plugin_Settings\migrate_legacy_settings(), GravityView_Migrate\migrate_redux_settings(), GravityView_Admin_No_Conflict\no_conflict_scripts(), GravityView_Admin_No_Conflict\no_conflict_styles(), View\offsetGet(), Multi_Entry\offsetSet(), GF_Entry\offsetSet(), GF_Form\offsetSet(), View\offsetSet(), Multi_Entry\offsetUnset(), GF_Entry\offsetUnset(), GF_Form\offsetUnset(), View\offsetUnset(), Page_Size\override_view_page_size(), GravityView_frontend\parse_content(), oEmbed\parse_matches(), GravityView_Ajax\pre_get_form_fields(), GravityView_Widget_Poll\pre_render_frontend(), Widget\pre_render_frontend(), GravityView_Edit_Entry_Render\prevent_maybe_process_form(), GravityView_Plugin_Hooks_Gravity_Forms_Chained_Selects\print_scripts(), GravityView_Field_Notes\process_add_note(), GravityView_Bulk_Actions\process_bulk_action(), GravityView_Delete_Entry\process_connected_posts(), GravityView_Delete_Entry\process_delete(), GravityView_Duplicate_Entry\process_duplicate(), GravityView_Edit_Entry_Render\process_save(), GravityView_frontend\process_search_dates(), GravityView_frontend\process_search_only_approved(), GravityView_oEmbed\register_handler(), View\register_post_type(), GravityView_Plugin_Hooks_Pageviews\remove_autocontent(), GravityView_Theme_Hooks_WooThemes\remove_meta_box(), GravityView_Theme_Hooks_WPML\remove_url_hooks(), Entry_Renderer\render(), oEmbed\render(), View_Template\render(), GravityView_Metabox_Tab\render(), Field_Template\render(), GravityView_View\render(), GravityView_Admin_Views\render_active_areas(), GravityView_Admin_Views\render_available_fields(), GravityView_Admin_Views\render_directory_active_areas(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Custom_Content\render_frontend(), oEmbed\render_frontend(), GravityView_Widget_Search\render_frontend(), GravityView_oEmbed\render_handler(), GravityView_oEmbed\render_provider_request(), GravityView_Widget_Search\render_searchable_fields(), GravityView_Admin_Metaboxes\render_shortcode_hint(), GravityView_frontend\render_view(), GravityView_View\render_widget_hooks(), GravityView_View\renderZone(), GravityView_Merge_Tags\replace_entry_link(), GravityView_Field_Sequence\replace_merge_tag(), GravityView_Merge_Tags\replace_variables(), Legacy_Context\reset(), GravityView_Edit_Entry_User_Registration\restore_display_name(), GravityView_Admin_Views\save_postdata(), GravityView_Cache\set(), GravityView_Lightbox\set_provider(), GravityView_oEmbed\set_single_entry_id(), GravityView_Shortcode\shortcode(), GravityView_Entry_Link_Shortcode\shortcode(), GravityView_Field_Custom\show_field_in_edit_entry(), GravityView_frontend\single_entry_title(), GravityView_Admin_Views\suggest_support_articles(), View\template_redirect(), GravityView_Entry_Approval\update_approved(), GravityView_Migrate\update_approved_meta(), GravityView_Entry_Approval\update_approved_meta(), GravityView_Entry_Approval\update_bulk(), Field\update_configuration(), GravityView_Migrate\update_search_on_views(), GravityView_Edit_Entry_User_Registration\update_user(), GravityView_Cache\use_cache(), GravityView_Delete_Entry\user_can_delete_entry(), GravityView_Duplicate_Entry\user_can_duplicate_entry(), GravityView_Edit_Entry_Render\user_can_edit_entry(), GravityView_Edit_Entry_Render\user_can_edit_field(), GravityView_Edit_Entry_Render\verify_user_can_edit_post(), GravityView_Search_WP_Widget\widget(), and GravityView_Theme_Hooks_WPML\wpml_ls_filter().
Variable Documentation
if
if = apply_filters('gravityview/fields/custom/content_after', $content)
If this file is called directly, abort.
The default survey field output template.
The default entry link field output template.
The default edit link field output template.
The default duplicate link field output template.
The default delete link field output template.
The default custom content field output template.
Require core and mocks "GRAVITYVIEW_DIR" "../"
Runs Filter:
gravityview/fields/custom/decode_shortcodes Decode brackets in shortcodes
Since
1.16.5
Parameters
boolean $decode Enable/Disable decoding of brackets in the content (default: false)
string $content HTML content of field
Runs Filter:
gravityview/fields/custom/content_after Modify Custom Content field output after Merge Tag variables get replaced, before shortcodes get processed
Since
1.6.2
Parameters
string $content HTML content of field
$gravityview
Since
2.0
Runs Filter:
gravityview/fields/custom/decode_shortcodes Decode brackets in shortcodes, rendering them inert (escape brackets).
Since
1.16.5
Parameters
boolean $decode Enable/Disable decoding of brackets in the content (default: false)
string $content HTML content of field
Since
2.0
Parameters
Filter is defined in /templates/fields/field-checkbox-html.php
Runs Filter:
gravityview/template/field/survey/glue The value used to separate multiple values in the Survey field output
Since
2.10.4
Parameters
string The glue. Default: "; " (semicolon with a trailing space)
Definition at line 3 of file future/gravityview.php.