GravityView: general-template.php File Reference
general-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
__checked_selected_helper ($helper, $current, $echo, $type)
Private helper function for checked, selected, and disabled.
_wp_render_title_tag ()
Displays title tag with content.
add_thickbox ()
Enqueues the default ThickBox js and css.
allowed_tags ()
Display all of the allowed tags in HTML format with attributes.
bloginfo ($show='')
Display information about the blog.
calendar_week_mod ($num)
Get number of days since the start of the week.
checked ($checked, $current=true, $echo=true)
Outputs the html checked attribute.
delete_get_calendar_cache ()
Purge the cached results of get_calendar.
disabled ($disabled, $current=true, $echo=true)
Outputs the html disabled attribute.
feed_links ($args=array())
Display the links to the general feeds.
feed_links_extra ($args=array())
Display the links to the extra feeds such as category feeds.
get_archives_link ($url, $text, $format= 'html', $before= '', $after= '')
Retrieve archive link content based on predefined or custom code.
get_bloginfo ($show= '', $filter= 'raw')
Retrieve information about the blog.
get_calendar ($initial=true, $echo=true)
Display calendar with days that have posts as links.
get_footer ($name=null)
Load footer template.
get_header ($name=null)
Load header template.
get_language_attributes ($doctype= 'html')
Gets the language attributes for the html tag.
get_post_modified_time ($d= 'U', $gmt=false, $post=null, $translate=false)
Retrieve the time at which the post was last modified.
get_post_time ($d= 'U', $gmt=false, $post=null, $translate=false)
Retrieve the time at which the post was written.
get_search_form ($echo=true)
Display search form.
get_search_query ($escaped=true)
Retrieve the contents of the search WordPress query variable.
get_sidebar ($name=null)
Load sidebar template.
get_site_icon_url ($size=512, $url= '', $blog_id=0)
Returns the Site Icon URL.
get_template_part ($slug, $name=null)
Load a template part into a template.
get_the_archive_description ()
Retrieve category, tag, or term description.
get_the_archive_title ()
Retrieve the archive title based on the queried object.
get_the_date ($d= '', $post=null)
Retrieve the date on which the post was written.
get_the_generator ($type= '')
Creates the generator XML or Comment for RSS, ATOM, etc.
get_the_modified_date ($d= '')
Retrieve the date on which the post was last modified.
get_the_modified_time ($d= '')
Retrieve the time at which the post was last modified.
get_the_time ($d= '', $post=null)
Retrieve the time at which the post was written.
has_site_icon ($blog_id=0)
Whether the site has a Site Icon.
language_attributes ($doctype= 'html')
Displays the language attributes for the html tag.
noindex ()
Display a noindex meta tag if required by the blog configuration.
paginate_links ($args= '')
Retrieve paginated link for archive post pages.
post_type_archive_title ($prefix= '', $display=true)
Display or retrieve title for a post type archive.
register_admin_color_schemes ()
Registers the default Admin color schemes.
rsd_link ()
Display the link to the Really Simple Discovery service endpoint.
selected ($selected, $current=true, $echo=true)
Outputs the html selected attribute.
single_cat_title ($prefix= '', $display=true)
Display or retrieve page title for category archive.
single_month_title ($prefix= '', $display=true)
Display or retrieve page title for post archive based on date.
single_post_title ($prefix= '', $display=true)
Display or retrieve page title for post.
single_tag_title ($prefix= '', $display=true)
Display or retrieve page title for tag post archive.
single_term_title ($prefix= '', $display=true)
Display or retrieve page title for taxonomy term archive.
site_icon_url ($size=512, $url= '', $blog_id=0)
Displays the Site Icon URL.
the_archive_description ($before= '', $after= '')
Display category, tag, or term description.
the_archive_title ($before= '', $after= '')
Display the archive title based on the queried object.
the_date ($d= '', $before= '', $after= '', $echo=true)
Display or Retrieve the date the current post was written (once per date)
the_date_xml ()
Outputs the date in iso8601 format for xml files.
the_generator ($type)
Display the generator XML or Comment for RSS, ATOM, etc.
the_modified_date ($d= '', $before= '', $after= '', $echo=true)
Display the date on which the post was last modified.
the_modified_time ($d= '')
Display the time at which the post was last modified.
the_search_query ()
Display the contents of the search query variable.
the_time ($d= '')
Display the time at which the post was written.
the_weekday ()
Display the weekday on which the post was written.
the_weekday_date ($before='', $after='')
Display the weekday on which the post was written.
user_can_richedit ()
Whether the user should have a WYSIWIG editor.
wlwmanifest_link ()
Display the link to the Windows Live Writer manifest file.
wp_admin_css ($file= 'wp-admin', $force_echo=false)
Enqueues or directly prints a stylesheet link to the specified CSS file.
wp_admin_css_color ($key, $name, $url, $colors=array(), $icons=array())
Registers an admin colour scheme css file.
wp_admin_css_uri ($file= 'wp-admin')
Display the URL of a WordPress admin CSS file.
wp_default_editor ()
Find out which editor should be displayed by default.
wp_editor ($content, $editor_id, $settings=array())
Renders an editor.
wp_footer ()
Fire the wp_footer action.
wp_generator ()
Display the XHTML generator that is generated on the wp_head hook.
wp_get_archives ($args= '')
Display archive links based on type and format.
wp_get_document_title ()
Returns document title for the current page.
wp_head ()
Fire the wp_head action.
wp_heartbeat_settings ($settings)
Default settings for heartbeat.
wp_login_form ($args=array())
Provides a simple login form for use anywhere within WordPress.
wp_login_url ($redirect= '', $force_reauth=false)
Returns the URL that allows the user to log in to the site.
wp_loginout ($redirect= '', $echo=true)
Display the Log In/Out link.
wp_logout_url ($redirect= '')
Returns the Log Out URL.
wp_lostpassword_url ($redirect= '')
Returns the URL that allows the user to retrieve the lost password.
wp_meta ()
Theme container function for the 'wp_meta' action.
wp_no_robots ()
Display a noindex meta tag.
wp_register ($before= '< li >', $after= '</li >', $echo=true)
Display the Registration or Admin link.
wp_registration_url ()
Returns the URL that allows the user to register on the site.
wp_site_icon ()
Display site icon meta tags.
wp_title ($sep= '&raquo;', $display=true, $seplocation= '')
Display or retrieve page title for all areas of blog.
Function Documentation
__checked_selected_helper ($helper, $current, $echo, $type)
Private helper function for checked, selected, and disabled.
Compares the first two arguments and if identical marks as $type
Since
2.8.0 private
Parameters
mixed $helper One of the values to compare
mixed $current (true) The other value to compare if not just true
bool $echo Whether to echo or just return the string
string $type The type of checked|selected|disabled we are doing
Returns
string html attribute or empty string
Definition at line 3446 of file general-template.php.
Referenced by checked(), disabled(), gv_selected(), and selected().
_wp_render_title_tag ()
Displays title tag with content.
Since
4.1.0
4.4.0 Improved title output replaced wp_title(). private
Definition at line 951 of file general-template.php.
References current_theme_supports(), and wp_get_document_title().
add_thickbox ()
Enqueues the default ThickBox js and css.
If any of the settings need to be changed, this can be done with another js file similar to media-upload.js. That file should require array('thickbox') to ensure it is loaded after.
Since
2.5.0
Definition at line 3260 of file general-template.php.
References add_action(), is_network_admin(), wp_enqueue_script(), and wp_enqueue_style().
Referenced by _WP_Editors\enqueue_scripts().
allowed_tags ()
Display all of the allowed tags in HTML format with attributes.
This is useful for displaying in the comment area, which elements and attributes are supported. As well as any plugins which want to display it.
Since
1.0.1
array $allowedtags
Returns
string HTML allowed tags entity encoded.
Definition at line 2007 of file general-template.php.
References $allowedtags, and $attributes.
bloginfo ($show = '')
Display information about the blog.
See also
get_bloginfo() For possible values for the parameter.
Since
0.71
Parameters
string $show What to display.
Definition at line 597 of file general-template.php.
References get_bloginfo().
Referenced by WP_Press_This\html(), iframe_header(), login_header(), Custom_Image_Header\step_1(), twentythirteen_admin_header_image(), twentytwelve_admin_header_image(), wp_iframe(), and wp_print_media_templates().
calendar_week_mod ($num)
Get number of days since the start of the week.
Since
1.5.0
Parameters
int $num Number of day.
Returns
int Days since the start of the week.
Definition at line 1748 of file general-template.php.
Referenced by get_calendar().
checked ($checked, $current = true, $echo = true)
Outputs the html checked attribute.
Compares the first two arguments and if identical marks as checked
Since
1.0.0
Parameters
mixed $checked One of the values to compare
mixed $current (true) The other value to compare if not just true
bool $echo Whether to echo or just return the string
Returns
string html attribute or empty string
Definition at line 3396 of file general-template.php.
References __checked_selected_helper().
Referenced by admin_color_scheme_picker(), confirm_delete_users(), CreatePlaceholdersUI(), GF_Installation_Wizard_Step_Settings\display(), GF_Installation_Wizard_Step_Background_Updates\display(), GF_Installation_Wizard_Step_License_Key\display(), display_setup_form(), WP_Widget_Text\form(), WP_Widget_Links\form(), WP_Widget_Recent_Posts\form(), GravityView_Search_WP_Widget\form(), WP_Widget_Categories\form(), WP_Widget_Archives\form(), get_confirmation_ui_settings(), GF_Field_Address\get_field_input(), Custom_Image_Header\js_1(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), link_submit_meta_box(), network_step1(), notification_edit_page(), options_discussion_add_js(), post_comment_status_meta_box(), post_format_meta_box(), WP_Press_This\post_formats_html(), post_submit_meta_box(), GravityView_Render_Settings\render_checkbox_option(), WP_Customize_Control\render_content(), GravityView_FieldType_radio\render_input(), GravityView_FieldType_checkbox\render_input(), WP_Screen\render_list_table_columns_preferences(), WP_Screen\render_meta_boxes_preferences(), WP_Screen\render_screen_layout(), WP_Screen\render_view_mode(), request_filesystem_credentials(), Custom_Image_Header\show_header_selector(), WP_Screen\show_screen_options(), Walker_Nav_Menu_Edit\start_el(), Walker_Category_Checklist\start_el(), Custom_Image_Header\step_1(), twentyeleven_settings_field_color_scheme(), twentyeleven_settings_field_layout(), use_ssl_preference(), GravityView_Support_Port\user_field(), wp_image_editor(), wp_media_insert_url_form(), wp_print_media_templates(), and wp_widget_rss_form().
delete_get_calendar_cache ()
Purge the cached results of get_calendar.
See also
get_calendar
Since
2.1.0
Definition at line 1991 of file general-template.php.
References wp_cache_delete().
disabled ($disabled, $current = true, $echo = true)
Outputs the html disabled attribute.
Compares the first two arguments and if identical marks as disabled
Since
3.0.0
Parameters
mixed $disabled One of the values to compare
mixed $current (true) The other value to compare if not just true
bool $echo Whether to echo or just return the string
Returns
string html attribute or empty string
Definition at line 3428 of file general-template.php.
References __checked_selected_helper().
Referenced by image_size_input_fields(), post_tags_meta_box(), request_filesystem_credentials(), Walker_Category_Checklist\start_el(), wp_image_editor(), wp_nav_menu_disabled_check(), wp_popular_terms_checklist(), wp_print_media_templates(), and wp_print_revision_templates().
feed_links ($args = array())
Display the links to the general feeds.
Since
2.8.0
Parameters
array $args Optional arguments.
Filter whether to display the posts feed link.
Since
4.4.0
Parameters
bool $show Whether to display the posts feed link. Default true.
Filter whether to display the comments feed link.
Since
4.4.0
Parameters
bool $show Whether to display the comments feed link. Default true.
Definition at line 2456 of file general-template.php.
References __, _x, apply_filters(), current_theme_supports(), esc_attr(), esc_url, feed_content_type(), get_bloginfo(), get_default_feed(), get_feed_link(), and wp_parse_args().
feed_links_extra ($args = array())
Display the links to the extra feeds such as category feeds.
Since
2.8.0
Parameters
array $args Optional arguments.
Definition at line 2501 of file general-template.php.
References $href, $id, $post, $post_type, $title, __, _x, comments_open(), elseif, esc_attr(), esc_url, feed_content_type(), get_author_feed_link(), get_bloginfo(), get_category_feed_link(), get_post(), get_post_comments_feed_link(), get_post_type_archive_feed_link(), get_post_type_object(), get_queried_object(), get_query_var(), get_search_feed_link(), get_search_query(), get_tag_feed_link(), get_the_author_meta(), is_author(), is_category(), is_post_type_archive(), is_search(), is_singular(), is_tag(), pings_open(), post_type_archive_title(), the_title_attribute(), and wp_parse_args().
get_archives_link ($url, $text, $format = 'html', $before = '', $after = '')
Retrieve archive link content based on predefined or custom code.
The format can be one of four styles. The 'link' for head element, 'option' for use in the select element, 'html' for use in list (either ol or ul HTML elements). Custom content is also supported using the before and after parameters.
The 'link' format uses the <link> HTML element with the archives relationship. The before and after parameters are not used. The text parameter is used to describe the link.
The 'option' format uses the option HTML element for use in select element. The value is the url parameter and the before and after parameters are used between the text description.
The 'html' format, which is the default, uses the li HTML element for use in the list HTML elements. The before parameter is before the link and the after parameter is after the closing link.
The custom format uses the before parameter before the link ('a' HTML element) and the after parameter after the closing link tag. If the above three values for the format are not used, then custom format is assumed.
Since
1.0.0
Parameters
string $url URL to archive.
string $text Archive text description.
string $format Optional, default is 'html'. Can be 'link', 'option', 'html', or custom.
string $before Optional. Content to prepend to the description. Default empty.
string $after Optional. Content to append to the description. Default empty.
Returns
string HTML link content for archive.
Filter the archive link content.
Since
2.6.0
Parameters
string $link_html The archive HTML link content.
Definition at line 1468 of file general-template.php.
References $format, $text, $url, apply_filters(), elseif, esc_attr(), esc_url, and wptexturize().
Referenced by wp_get_archives().
get_bloginfo ($show = '', $filter = 'raw')
Retrieve information about the blog.
Some show parameter values are deprecated and will be removed in future versions. These options will trigger the {
See also
_deprecated_argument()} function. The deprecated blog info options are listed in the function contents.
The possible values for the 'show' parameter are listed below.
url - Blog URI to homepage.
wpurl - Blog URI path to WordPress.
description - Secondary title
The feed URL options can be retrieved from 'rdf_url' (RSS 0.91), 'rss_url' (RSS 1.0), 'rss2_url' (RSS 2.0), or 'atom_url' (Atom feed). The comment feeds can be retrieved from the 'comments_atom_url' (Atom comment feed) or 'comments_rss2_url' (RSS 2.0 comment feed).
Since
0.71
string $wp_version
Parameters
string $show Blog info to retrieve.
string $filter How to filter what is retrieved.
Returns
string Mostly string values, might be empty.
Filter the URL returned by get_bloginfo().
Since
2.0.5
Parameters
mixed $output The URL returned by bloginfo().
mixed $show Type of information requested.
Filter the site information returned by get_bloginfo().
Since
0.71
Parameters
mixed $output The requested non-URL site information.
mixed $show Type of information requested.
Definition at line 628 of file general-template.php.
References $output, $url, $wp_version, __, _deprecated_argument(), apply_filters(), get_feed_link(), get_locale(), get_option(), get_stylesheet_directory_uri(), get_stylesheet_uri(), get_template_directory_uri(), home_url(), is_rtl(), site_url(), and str_replace.
Referenced by bloginfo(), feed_links(), feed_links_extra(), get_language_attributes(), get_the_generator(), wp_admin_css_uri(), and wp_get_document_title().
get_calendar ($initial = true, $echo = true)
Display calendar with days that have posts as links.
The calendar is cached, which will be retrieved, if it exists. If there are no posts for the month, then it will not be displayed.
Since
1.0.0
wpdb $wpdb int $m int $monthnum int $year WP_Locale $wp_locale array $posts
Parameters
bool $initial Optional, default is true. Use initial calendar names.
bool $echo Optional, default is true. Set to false for return.
Returns
string|void String when retrieving.
This filter is documented in wp-includes/general-template.php
Filter the HTML calendar output.
Since
3.0.0
Parameters
string $calendar_output HTML output of the calendar.
This filter is documented in wp-includes/general-template.php
Definition at line 1772 of file general-template.php.
References $date_format, $label, $output, $wp_locale, $wpdb, __, _x, apply_filters(), ARRAY_N, calendar_week_mod(), current_time(), date, elseif, esc_attr(), get_day_link(), get_month_link(), get_option(), wp_cache_get(), wp_cache_set(), and zeroise().
Referenced by WP_Widget_Calendar\widget().
get_footer ($name = null)
Load footer template.
Includes the footer template for a theme or if a name is specified then a specialised footer will be included.
For the parameter, if the file is called "footer-special.php" then specify "special".
Since
1.5.0
Parameters
string $name The name of the specialised footer.
Fires before the footer template file is loaded.
The hook allows a specific footer template file to be used in place of the default footer template file. If your file is called footer-new.php, you would specify the filename in the hook as get_footer('new').
Since
2.1.0
2.8.0 $name parameter added.
Parameters
string $name Name of the specific footer file to use.
Definition at line 62 of file general-template.php.
References $name, $templates, ABSPATH, do_action(), load_template(), locate_template(), and WPINC.
get_header ($name = null)
Load header template.
Includes the header template for a theme or if a name is specified then a specialised header will be included.
For the parameter, if the file is called "header-special.php" then specify "special".
Since
1.5.0
Parameters
string $name The name of the specialised header.
Fires before the header template file is loaded.
The hook allows a specific header template file to be used in place of the default header template file. If your file is called header-new.php, you would specify the filename in the hook as get_header('new').
Since
2.1.0
2.8.0 $name parameter added.
Parameters
string $name Name of the specific header file to use.
Definition at line 22 of file general-template.php.
References $name, $templates, ABSPATH, do_action(), load_template(), locate_template(), and WPINC.
Referenced by Gettext_Translations\gettext_select_plural_form(), and Gettext_Translations\set_header().
get_language_attributes ($doctype = 'html')
Gets the language attributes for the html tag.
Builds up a set of html attributes containing the text direction and language information for the page.
Since
4.3.0
Parameters
string $doctype Optional. The type of html document. Accepts 'xhtml' or 'html'. Default 'html'.
Filter the language attributes for display in the html tag.
Since
2.5.0
4.3.0 Added the $doctype parameter.
Parameters
string $output A space-separated list of language attributes.
string $doctype The type of html document (xhtml|html).
Definition at line 2805 of file general-template.php.
References $attributes, $lang, $output, apply_filters(), get_bloginfo(), get_option(), and is_rtl().
Referenced by language_attributes().
get_post_modified_time ($d = 'U', $gmt = false, $post = null, $translate = false)
Retrieve the time at which the post was last modified.
Since
2.0.0
Parameters
string $d Optional. Format to use for retrieving the time the post was modified. Either 'G', 'U', or php date format. Default 'U'.
bool $gmt Optional. Whether to retrieve the GMT time. Default false.
int | WP_Post $post WP_Post object or ID. Default is global $post object.
bool $translate Whether to translate the time string. Default false.
Returns
false|string Formatted date string or Unix timestamp. False on failure.
Filter the localized time a post was last modified.
Since
2.8.0
Parameters
string $time The formatted time.
string $d The date format. Accepts 'G', 'U', or php date format. Default 'U'.
bool $gmt Whether to return the GMT time. Default false.
Definition at line 2337 of file general-template.php.
References $post, apply_filters(), get_post(), and mysql2date().
Referenced by get_the_modified_date(), and get_the_modified_time().
get_post_time ($d = 'U', $gmt = false, $post = null, $translate = false)
Retrieve the time at which the post was written.
Since
2.0.0
Parameters
string $d Optional. Format to use for retrieving the time the post was written. Either 'G', 'U', or php date format. Default 'U'.
bool $gmt Optional. Whether to retrieve the GMT time. Default false.
int | WP_Post $post WP_Post object or ID. Default is global $post object.
bool $translate Whether to translate the time string. Default false.
Returns
false|string|int Formatted date string or Unix timestamp. False on failure.
Filter the localized time a post was written.
Since
2.6.0
Parameters
string $time The formatted time.
string $d Format to use for retrieving the time the post was written. Accepts 'G', 'U', or php date format. Default 'U'.
bool $gmt Whether to retrieve the GMT time. Default false.
Definition at line 2250 of file general-template.php.
References $post, apply_filters(), get_post(), and mysql2date().
Referenced by WP_Media_List_Table\column_date(), WP_Posts_List_Table\column_date(), and get_the_time().
get_search_form ($echo = true)
Display search form.
Will first attempt to locate the searchform.php file in either the child or the parent, then load it. If it doesn't exist, then the default search form will be displayed. The default search form is HTML, which will be displayed. There is a filter applied to the search form HTML in order to edit or replace it. The filter is 'get_search_form'.
This function is primarily used by themes which want to hardcode the search form into the sidebar and also by the search widget in WordPress.
There is also an action that is called whenever the function is run called, 'pre_get_search_form'. This can be useful for outputting JavaScript that the search relies on or various formatting that applies to the beginning of the search. To give a few examples of what it can be used for.
Since
2.7.0
Parameters
bool $echo Default to echo and not return the form.
Returns
string|void String when $echo is false.
Fires before the search form is retrieved, at the start of get_search_form().
Since
2.7.0 as 'get_search_form' action.
3.6.0
Filter the HTML format of the search form. 3.6.0 string $format The type of markup to use in the search form. Accepts 'html5', 'xhtml'. Filter the HTML output of the search form. 2.7.0 string $form The search form HTML output.
Definition at line 196 of file general-template.php.
References $form, $format, _x, apply_filters(), current_theme_supports(), do_action(), esc_attr_x(), esc_url, get_search_query(), home_url(), locate_template(), and null.
Referenced by WP_Widget_Search\widget().
get_search_query ($escaped = true)
Retrieve the contents of the search WordPress query variable.
The search query string is passed through esc_attr() to ensure that it is safe for placing in an html attribute.
Since
2.3.0
Parameters
bool $escaped Whether the result is escaped. Default true. Only use when you are later escaping it. Do not use unescaped.
Returns
string
Filter the contents of the search query variable.
Since
2.3.0
Parameters
mixed $search Contents of the search query variable.
Definition at line 2761 of file general-template.php.
References apply_filters(), esc_attr(), and get_query_var().
Referenced by feed_links_extra(), get_search_form(), get_search_link(), the_search_query(), and wp_get_document_title().
get_sidebar ($name = null)
Load sidebar template.
Includes the sidebar template for a theme or if a name is specified then a specialised sidebar will be included.
For the parameter, if the file is called "sidebar-special.php" then specify "special".
Since
1.5.0
Parameters
string $name The name of the specialised sidebar.
Fires before the sidebar template file is loaded.
The hook allows a specific sidebar template file to be used in place of the default sidebar template file. If your file is called sidebar-new.php, you would specify the filename in the hook as get_sidebar('new').
Since
2.2.0
2.8.0 $name parameter added.
Parameters
string $name Name of the specific sidebar file to use.
Definition at line 102 of file general-template.php.
References $name, $templates, ABSPATH, do_action(), load_template(), locate_template(), and WPINC.
get_site_icon_url ($size = 512, $url = '', $blog_id = 0)
Returns the Site Icon URL.
Since
4.3.0
Parameters
int $size Optional. Size of the site icon. Default 512 (pixels).
string $url Optional. Fallback url if no site icon is found. Default empty.
int $blog_id Optional. ID of the blog to get the site icon for. Default current blog.
Returns
string Site Icon URL.
Filter the site icon URL.
4.4.0
Parameters
string $url Site icon URL.
int $size Size of the site icon.
int $blog_id ID of the blog to get the site icon for.
Definition at line 760 of file general-template.php.
References $blog_id, $size, $url, apply_filters(), get_current_blog_id(), get_option(), is_multisite(), ms_is_switched(), restore_current_blog(), switch_to_blog(), and wp_get_attachment_image_url().
Referenced by atom_site_icon(), has_site_icon(), rss2_site_icon(), site_icon_url(), and wp_site_icon().
get_template_part ($slug, $name = null)
Load a template part into a template.
Makes it easy for a theme to reuse sections of code in a easy to overload way for child themes.
Includes the named template part for a theme or if a name is specified then a specialised part will be included. If the theme contains no {slug}.php file then no template will be included.
The template is included using require, not require_once, so you may include the same template part multiple times.
For the $name parameter, if the file is called "{slug}-special.php" then specify "special".
Since
3.0.0
Parameters
string $slug The slug name for the generic template.
string $name The name of the specialised template.
Fires before the specified template part file is loaded.
The dynamic portion of the hook name, $slug, refers to the slug name for the generic template part.
Since
3.0.0
Parameters
string $slug The slug name for the generic template.
string $name The name of the specialized template.
Definition at line 150 of file general-template.php.
References $name, $templates, do_action(), and locate_template().
Referenced by GravityView_View\render().
get_the_archive_description ()
Retrieve category, tag, or term description.
Since
4.1.0
Returns
string Archive description.
Filter the archive description.
Since
4.1.0
See also
term_description()
Parameters
string $description Archive description to be displayed.
Definition at line 1422 of file general-template.php.
References apply_filters(), and term_description().
Referenced by the_archive_description().
get_the_archive_title ()
Retrieve the archive title based on the queried object.
Since
4.1.0
Returns
string Archive title.
Filter the archive title.
Since
4.1.0
Parameters
string $title Archive title to be displayed.
Definition at line 1345 of file general-template.php.
References $tax, $title, __, _x, apply_filters(), elseif, get_queried_object(), get_taxonomy(), get_the_author(), get_the_date(), is_author(), is_category(), is_day(), is_month(), is_post_type_archive(), is_tag(), is_tax(), is_year(), post_type_archive_title(), single_cat_title(), single_tag_title(), and single_term_title().
Referenced by the_archive_title().
get_the_date ($d = '', $post = null)
Retrieve the date on which the post was written.
Unlike the_date() this function will always return the date. Modify output with 'get_the_date' filter.
Since
3.0.0
Parameters
string $d Optional. PHP date format defaults to the date_format option if not specified.
int | WP_Post $post Optional. Post ID or WP_Post object. Default current post.
Returns
false|string Date the current post was written. False on failure.
Filter the date a post was published.
Since
3.0.0
Parameters
string $the_date The formatted date.
string $d PHP date format. Defaults to 'date_format' option if not specified.
int | WP_Post $post The post object or ID.
Definition at line 2095 of file general-template.php.
References $post, apply_filters(), get_option(), get_post(), and mysql2date().
Referenced by get_the_archive_title(), the_date(), WP_Widget_Recent_Posts\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), and wp_get_document_title().
get_the_generator ($type = '')
Creates the generator XML or Comment for RSS, ATOM, etc.
Returns the correct generator type for the requested output format. Allows for a plugin to filter generators on an individual basis using the 'get_the_generator_{$type}' filter.
Since
2.5.0
Parameters
string $type The type of generator to return - (html|xhtml|atom|rss2|rdf|comment|export).
Returns
string|void The HTML content for the generator.
Filter the HTML for the retrieved generator type.
The dynamic portion of the hook name, $type, refers to the generator type.
Since
2.5.0
Parameters
string $gen The HTML markup output to {
See also
wp_head()}.
Parameters
string $type The type of generator. Accepts 'html', 'xhtml', 'atom', 'rss2', 'rdf', 'comment', 'export'.
Definition at line 3319 of file general-template.php.
References apply_filters(), current_filter(), date, get_bloginfo(), and get_bloginfo_rss().
Referenced by the_generator().
get_the_modified_date ($d = '')
Retrieve the date on which the post was last modified.
Since
2.1.0
Parameters
string $d Optional. PHP date format. Defaults to the "date_format" option
Returns
string
Filter the date a post was last modified.
Since
2.1.0
Parameters
string $the_time The formatted date.
string $d PHP date format. Defaults to value specified in 'date_format' option.
Definition at line 2163 of file general-template.php.
References apply_filters(), get_option(), get_post_modified_time(), and null.
Referenced by the_modified_date().
get_the_modified_time ($d = '')
Retrieve the time at which the post was last modified.
Since
2.0.0
Parameters
string $d Optional Either 'G', 'U', or php date format defaults to the value specified in the time_format option.
Returns
string
Filter the localized time a post was last modified.
Since
2.0.0
Parameters
string $the_time The formatted time.
string $d Format to use for retrieving the time the post was written. Accepts 'G', 'U', or php date format. Defaults to value specified in 'time_format' option.
Definition at line 2306 of file general-template.php.
References apply_filters(), get_option(), get_post_modified_time(), and null.
Referenced by the_modified_time().
get_the_time ($d = '', $post = null)
Retrieve the time at which the post was written.
Since
1.5.0
Parameters
string $d Optional. Format to use for retrieving the time the post was written. Either 'G', 'U', or php date format defaults to the value specified in the time_format option. Default empty.
int | WP_Post $post WP_Post object or ID. Default is global $post object.
Returns
false|string Formatted date string or Unix timestamp. False on failure.
Filter the time a post was written.
Since
1.5.0
Parameters
string $the_time The formatted time.
string $d Format to use for retrieving the time the post was written. Accepts 'G', 'U', or php date format value specified in 'time_format' option. Default empty.
int | WP_Post $post WP_Post object or ID.
Definition at line 2212 of file general-template.php.
References $post, apply_filters(), get_option(), get_post(), and get_post_time().
Referenced by WP_Posts_List_Table\column_date(), the_time(), and wp_dashboard_recent_drafts().
has_site_icon ($blog_id = 0)
Whether the site has a Site Icon.
Since
4.3.0
Parameters
int $blog_id Optional. ID of the blog in question. Default current blog.
Returns
bool Whether the site has a site icon or not.
Definition at line 813 of file general-template.php.
References $blog_id, and get_site_icon_url().
Referenced by wp_site_icon().
language_attributes ($doctype = 'html')
Displays the language attributes for the html tag.
Builds up a set of html attributes containing the text direction and language information for the page.
Since
2.1.0
4.3.0 Converted into a wrapper for get_language_attributes().
Parameters
string $doctype Optional. The type of html document. Accepts 'xhtml' or 'html'. Default 'html'.
Definition at line 2844 of file general-template.php.
References get_language_attributes().
Referenced by _default_wp_die_handler(), _wp_admin_html_begin(), display_header(), WP_Press_This\html(), and login_header().
noindex ()
Display a noindex meta tag if required by the blog configuration.
If a blog is marked as not being public then the noindex meta tag will be output to tell web robots not to index the page content. Add this to the wp_head action. Typical usage is as a wp_head callback. add_action('wp_head', 'noindex');
See also
wp_no_robots
Since
2.1.0
Definition at line 2602 of file general-template.php.
References get_option(), and wp_no_robots().
paginate_links ($args = '')
Retrieve paginated link for archive post pages.
Technically, the function can be used to create paginated link list for any area. The 'base' argument is used to reference the url, which will be used to create the paginated links. The 'format' argument is then used for replacing the page number. It is however, most likely and by default, to be used on the archive post pages.
The 'type' argument controls format of the returned value. The default is 'plain', which is just a string with the links separated by a newline character. The other possible values are either 'array' or 'list'. The 'array' value will return an array of the paginated link list to offer full control of display. The 'list' value will place all of the paginated links in an unordered HTML list.
The 'total' argument is the total amount of pages and is an integer. The 'current' argument is the current page number and is also an integer.
An example of the 'base' argument is "http://example.com/all_posts.php%_%" and the '_' is required. The '_' will be replaced by the contents of in the 'format' argument. An example for the 'format' argument is "?page=%#%" and the '%#' is also required. The '%#' will be replaced with the page number.
You can include the previous and next links in the list by setting the 'prev_next' argument to true, which it is by default. You can set the previous text, by using the 'prev_text' argument. You can set the next text by setting the 'next_text' argument.
If the 'show_all' argument is set to true, then it will show all of the pages instead of a short list of the pages near the current page. By default, the 'show_all' is set to false and controlled by the 'end_size' and 'mid_size' arguments. The 'end_size' argument is how many numbers on either the start and the end list edges, by default is 1. The 'mid_size' argument is how many numbers to either side of current page, but not including current page.
It is possible to add query vars to the link by using the 'add_args' argument and see add_query_arg() for more information.
The 'before_page_number' and 'after_page_number' arguments allow users to augment the links themselves. Typically this might be to add context to the numbered links so that screen reader users understand what the links are for. The text strings are added before and after the page number - within the anchor tag.
Since
2.1.0
WP_Query $wp_query WP_Rewrite $wp_rewrite
Parameters
string | array $args { Optional. Array or string of arguments for generating paginated links for archives.
string $base Base of the paginated url. Default empty. string $format Format for the pagination structure. Default empty. int $total The total amount of pages. Default is the value WP_Query's max_num_pages or 1. int $current The current page number. Default is 'paged' query var or 1. bool $show_all Whether to show all pages. Default false. int $end_size How many numbers on either the start and the end list edges. Default 1. int $mid_size How many numbers to either side of the current pages. Default 2. bool $prev_next Whether to include the previous and next links in the list. Default true. bool $prev_text The previous page text. Default ' Previous'. bool $next_text The next page text. Default ' Previous'. string $type Controls format of the returned value. Possible values are 'plain', 'array' and 'list'. Default is 'plain'. array $add_args An array of query args to add. Default false. string $add_fragment A string to append to each link. Default empty. string $before_page_number A string to appear before the page number. Default empty. string $after_page_number A string to append after the page number. Default empty. }
Returns
array|string|void String of page links or array of page links.
Filter the paginated links for the given archive pages.
Since
3.0.0
Parameters
string $link The paginated link URL.
This filter is documented in wp-includes/general-template.php
This filter is documented in wp-includes/general-template.php
Definition at line 2923 of file general-template.php.
References $format, $link, $wp_rewrite, __, add_query_arg(), apply_filters(), elseif, endif, esc_url, get_pagenum_link(), get_query_var(), number_format_i18n(), str_replace, trailingslashit(), urlencode_deep(), user_trailingslashit(), wp_parse_args(), and wp_parse_str().
Referenced by get_the_posts_pagination(), GFEntryList\leads_page(), media_upload_library_form(), paginate_comments_links(), GravityView_Widget_Page_Links\render_frontend(), wp_nav_menu_item_post_type_meta_box(), and wp_nav_menu_item_taxonomy_meta_box().
post_type_archive_title ($prefix = '', $display = true)
Display or retrieve title for a post type archive.
This is optimized for archive.php and archive-{$post_type}.php template files for displaying the title of the post type.
Since
3.1.0
Parameters
string $prefix Optional. What to display before the title.
bool $display Optional, default is true. Whether to display or retrieve title.
Returns
string|void Title when retrieving, null when displaying or failure.
Filter the post type archive title.
Since
3.1.0
Parameters
string $post_type_name Post type 'name' label.
string $post_type Post type.
Definition at line 1160 of file general-template.php.
References $post_type, $prefix, $title, apply_filters(), get_post_type_object(), get_query_var(), and is_post_type_archive().
Referenced by feed_links_extra(), get_the_archive_title(), wp_get_document_title(), and wp_title().
register_admin_color_schemes ()
Registers the default Admin color schemes.
Since
3.0.0
string $wp_version
Definition at line 3113 of file general-template.php.
References $GLOBALS, _x, admin_url(), is_rtl(), and wp_admin_css_color().
rsd_link ()
Display the link to the Really Simple Discovery service endpoint.
2.0.0
Definition at line 2576 of file general-template.php.
References esc_url, and site_url().
selected ($selected, $current = true, $echo = true)
Outputs the html selected attribute.
Compares the first two arguments and if identical marks as selected
Since
1.0.0
Parameters
mixed $selected One of the values to compare
mixed $current (true) The other value to compare if not just true
bool $echo Whether to echo or just return the string
Returns
string html attribute or empty string
Definition at line 3412 of file general-template.php.
References __checked_selected_helper().
Referenced by GravityView_Change_Entry_Creator\add_select(), GravityView_Admin_Views\add_view_dropdown(), choose_primary_blog(), CreatePlaceholdersUI(), WP_Comments_List_Table\extra_tablenav(), WP_Nav_Menu_Widget\form(), WP_Widget_Tag_Cloud\form(), WP_Widget_Links\form(), WP_Widget_Pages\form(), GravityView_Search_WP_Widget\form(), Twenty_Fourteen_Ephemera_Widget\form(), GravityView_Recent_Entries_Widget\form(), GVCommon\get_sortable_fields(), WP_Media_List_Table\get_views(), GFHelp\help_page(), install_search_form(), install_theme_search_form(), GFEntryDetail\lead_detail_page(), WP_List_Table\months_dropdown(), mu_dropdown_languages(), notification_edit_page(), page_template_dropdown(), parent_dropdown(), post_submit_meta_box(), print_embed_styles(), WP_Customize_Nav_Menu_Location_Control\render_content(), WP_Customize_Control\render_content(), GravityView_FieldType_select\render_input(), GravityView_Widget_Search\render_searchable_fields(), GravityView_Render_Settings\render_select_option(), GFPaymentAddOn\results_filter_ui(), touch_time(), wp_dropdown_categories(), wp_dropdown_languages(), wp_dropdown_users(), wp_print_media_templates(), and wp_widget_rss_form().
single_cat_title ($prefix = '', $display = true)
Display or retrieve page title for category archive.
Useful for category template files for displaying the category page title. The prefix does not automatically place a space between the prefix, so if there should be a space, the parameter value will need to have it at the end.
Since
0.71
Parameters
string $prefix Optional. What to display before the title.
bool $display Optional, default is true. Whether to display or retrieve title.
Returns
string|void Title when retrieving.
Definition at line 1199 of file general-template.php.
References $prefix, and single_term_title().
Referenced by get_the_archive_title().
single_month_title ($prefix = '', $display = true)
Display or retrieve page title for post archive based on date.
Useful for when the template only needs to display the month and year, if either are available. The prefix does not automatically place a space between the prefix, so if there should be a space, the parameter value will need to have it at the end.
Since
0.71
WP_Locale $wp_locale
Parameters
string $prefix Optional. What to display before the title.
bool $display Optional, default is true. Whether to display or retrieve title.
Returns
string|void Title when retrieving.
Definition at line 1295 of file general-template.php.
References $prefix, $wp_locale, elseif, and get_query_var().
single_post_title ($prefix = '', $display = true)
Display or retrieve page title for post.
This is optimized for single.php template file for displaying the post title.
It does not support placing the separator after the title, but by leaving the prefix parameter empty, you can set the title separator manually. The prefix does not automatically place a space between the prefix, so if there should be a space, the parameter value will need to have it at the end.
Since
0.71
Parameters
string $prefix Optional. What to display before the title.
bool $display Optional, default is true. Whether to display or retrieve title.
Returns
string|void Title when retrieving.
Filter the page title for a single post.
Since
0.71
Parameters
string $_post_title The single post page title.
object $_post The current queried object as returned by get_queried_object().
Definition at line 1127 of file general-template.php.
References $prefix, $title, apply_filters(), and get_queried_object().
Referenced by wp_get_document_title(), and wp_title().
single_tag_title ($prefix = '', $display = true)
Display or retrieve page title for tag post archive.
Useful for tag template files for displaying the tag page title. The prefix does not automatically place a space between the prefix, so if there should be a space, the parameter value will need to have it at the end.
Since
2.3.0
Parameters
string $prefix Optional. What to display before the title.
bool $display Optional, default is true. Whether to display or retrieve title.
Returns
string|void Title when retrieving.
Definition at line 1216 of file general-template.php.
References $prefix, and single_term_title().
Referenced by get_the_archive_title().
single_term_title ($prefix = '', $display = true)
Display or retrieve page title for taxonomy term archive.
Useful for taxonomy term template files for displaying the taxonomy term page title. The prefix does not automatically place a space between the prefix, so if there should be a space, the parameter value will need to have it at the end.
Since
3.1.0
Parameters
string $prefix Optional. What to display before the title.
bool $display Optional, default is true. Whether to display or retrieve title.
Returns
string|void Title when retrieving.
Filter the category archive page title.
Since
2.0.10
Parameters
string $term_name Category name for archive being displayed.
Filter the tag archive page title.
Since
2.3.0
Parameters
string $term_name Tag name for archive being displayed.
Filter the custom taxonomy archive page title.
Since
3.1.0
Parameters
string $term_name Term name for archive being displayed.
Definition at line 1233 of file general-template.php.
References $prefix, apply_filters(), elseif, get_queried_object(), is_category(), is_tag(), and is_tax().
Referenced by get_the_archive_title(), single_cat_title(), single_tag_title(), wp_get_document_title(), and wp_title().
site_icon_url ($size = 512, $url = '', $blog_id = 0)
Displays the Site Icon URL.
Since
4.3.0
Parameters
int $size Optional. Size of the site icon. Default 512 (pixels).
string $url Optional. Fallback url if no site icon is found. Default empty.
int $blog_id Optional. ID of the blog to get the site icon for. Default current blog.
Definition at line 801 of file general-template.php.
References $blog_id, $size, $url, esc_url, and get_site_icon_url().
the_archive_description ($before = '', $after = '')
Display category, tag, or term description.
Since
4.1.0
See also
get_the_archive_description()
Parameters
string $before Optional. Content to prepend to the description. Default empty.
string $after Optional. Content to append to the description. Default empty.
Definition at line 1408 of file general-template.php.
References $description, and get_the_archive_description().
the_archive_title ($before = '', $after = '')
Display the archive title based on the queried object.
Since
4.1.0
See also
get_the_archive_title()
Parameters
string $before Optional. Content to prepend to the title. Default empty.
string $after Optional. Content to append to the title. Default empty.
Definition at line 1330 of file general-template.php.
References $title, and get_the_archive_title().
the_date ($d = '', $before = '', $after = '', $echo = true)
Display or Retrieve the date the current post was written (once per date)
Will only output the date if the current post's date is different from the previous one output.
i.e. Only one date listing will show per day worth of posts shown in the loop, even if the function is called several times for each post.
HTML output can be filtered with 'the_date'. Date string output can be filtered with 'get_the_date'.
Since
0.71
string|int|bool $currentday string|int|bool $previousday
Parameters
string $d Optional. PHP date format defaults to the date_format option if not specified.
string $before Optional. Output before the date.
string $after Optional. Output after the date.
bool $echo Optional, default is display. Whether to echo the date or return it.
Returns
string|void String if retrieving.
Filter the date a post was published for display.
Since
0.71
Parameters
string $the_date The formatted date string.
string $d PHP date format. Defaults to 'date_format' option if not specified.
string $before HTML output before the date.
string $after HTML output after the date.
Definition at line 2056 of file general-template.php.
References apply_filters(), get_the_date(), and is_new_day().
the_date_xml ()
Outputs the date in iso8601 format for xml files.
Since
1.0.0
Definition at line 2029 of file general-template.php.
References get_post(), and mysql2date().
the_generator ($type)
Display the generator XML or Comment for RSS, ATOM, etc.
Returns the correct generator type for the requested output format. Allows for a plugin to filter generators overall the the_generator filter.
Since
2.5.0
Parameters
string $type The type of generator to output - (html|xhtml|atom|rss2|rdf|comment|export).
Filter the output of the XHTML generator tag for display.
Since
2.5.0
Parameters
string $generator_type The generator output.
string $type The type of generator to output. Accepts 'html', 'xhtml', 'atom', 'rss2', 'rdf', 'comment', 'export'.
Definition at line 3294 of file general-template.php.
References apply_filters(), and get_the_generator().
Referenced by wp_generator().
the_modified_date ($d = '', $before = '', $after = '', $echo = true)
Display the date on which the post was last modified.
Since
2.1.0
Parameters
string $d Optional. PHP date format defaults to the date_format option if not specified.
string $before Optional. Output before the date.
string $after Optional. Output after the date.
bool $echo Optional, default is display. Whether to echo the date or return it.
Returns
string|void String if retrieving.
Filter the date a post was last modified for display.
Since
2.1.0
Parameters
string $the_modified_date The last modified date.
string $d PHP date format. Defaults to 'date_format' option if not specified.
string $before HTML output before the date.
string $after HTML output after the date.
Definition at line 2132 of file general-template.php.
References apply_filters(), and get_the_modified_date().
the_modified_time ($d = '')
Display the time at which the post was last modified.
Since
2.0.0
Parameters
string $d Optional Either 'G', 'U', or php date format defaults to the value specified in the time_format option.
Filter the localized time a post was last modified, for display.
Since
2.0.0
Parameters
string $get_the_modified_time The formatted time.
string $d The time format. Accepts 'G', 'U', or php date format. Defaults to value specified in 'time_format' option.
Definition at line 2284 of file general-template.php.
References apply_filters(), and get_the_modified_time().
the_search_query ()
Display the contents of the search query variable.
The search query string is passed through esc_attr() to ensure that it is safe for placing in an html attribute.
Since
2.1.0
Filter the contents of the search query variable for display.
Since
2.3.0
Parameters
mixed $search Contents of the search query variable.
Definition at line 2784 of file general-template.php.
References apply_filters(), esc_attr(), and get_search_query().
the_time ($d = '')
Display the time at which the post was written.
Since
0.71
Parameters
string $d Either 'G', 'U', or php date format.
Filter the time a post was written for display.
Since
0.71
Parameters
string $get_the_time The formatted time.
string $d The time format. Accepts 'G', 'U', or php date format.
Definition at line 2188 of file general-template.php.
References apply_filters(), and get_the_time().
the_weekday ()
Display the weekday on which the post was written.
Since
0.71
WP_Locale $wp_locale
Filter the weekday on which the post was written, for display.
Since
0.71
Parameters
string $the_weekday
Definition at line 2369 of file general-template.php.
References $wp_locale, apply_filters(), get_post(), and mysql2date().
the_weekday_date ($before = '', $after = '')
Display the weekday on which the post was written.
Will only output the weekday if the current post's weekday is different from the previous one output.
Since
0.71
WP_Locale $wp_locale string|int|bool $currentday string|int|bool $previousweekday
Parameters
string $before Optional Output before the date.
string $after Optional Output after the date.
Filter the localized date on which the post was written, for display.
Since
0.71
Parameters
string $the_weekday_date
string $before The HTML to output before the date.
string $after The HTML to output after the date.
Definition at line 2398 of file general-template.php.
References $wp_locale, apply_filters(), get_post(), and mysql2date().
user_can_richedit ()
Whether the user should have a WYSIWIG editor.
Checks that the user requires a WYSIWIG editor and that the editor is supported in the users browser.
Since
2.0.0
bool $wp_rich_edit bool $is_gecko bool $is_opera bool $is_safari bool $is_chrome bool $is_IE
Returns
bool
Filter whether the user can access the rich (Visual) editor.
Since
2.1.0
Parameters
bool $wp_rich_edit Whether the user can access to the rich (Visual) editor.
Definition at line 2671 of file general-template.php.
References $_SERVER, $is_chrome, $is_edge, $is_gecko, $is_IE, $is_opera, $is_safari, apply_filters(), elseif, get_user_option(), and wp_is_mobile().
Referenced by get_compat_media_markup(), get_media_item(), _WP_Editors\parse_settings(), sanitize_post_field(), and wp_default_editor().
wlwmanifest_link ()
Display the link to the Windows Live Writer manifest file.
2.3.1
Definition at line 2586 of file general-template.php.
References includes_url().
wp_admin_css ($file = 'wp-admin', $force_echo = false)
Enqueues or directly prints a stylesheet link to the specified CSS file.
"Intelligently" decides to enqueue or to print the CSS file. If the 'wp_print_styles' action has not yet been called, the CSS file will be enqueued. If the wp_print_styles action has been called, the CSS link will be printed. Printing may be forced by passing true as the $force_echo (second) parameter.
For backward compatibility with WordPress 2.3 calling method: If the $file (first) parameter does not correspond to a registered CSS file, we assume $file is a file relative to wp-admin/ without its ".css" extension. A stylesheet link to that generated URL is printed.
Since
2.3.0
Parameters
string $file Optional. Style handle name or file name (without ".css" extension) relative to wp-admin/. Defaults to 'wp-admin'.
bool $force_echo Optional. Force the stylesheet link to be printed rather than enqueued.
Filter the stylesheet link to the specified CSS file.
If the site is set to display right-to-left, the RTL stylesheet link will be used instead.
Since
2.3.0
Parameters
string $file Style handle name or filename (without ".css" extension) relative to wp-admin/. Defaults to 'wp-admin'.
This filter is documented in wp-includes/general-template.php
Definition at line 3220 of file general-template.php.
References $file, apply_filters(), did_action(), esc_url, is_rtl(), wp_admin_css_uri(), wp_enqueue_style(), wp_print_styles(), and wp_styles().
Referenced by display_header(), login_header(), and setup_config_display_header().
wp_admin_css_color ($key, $name, $url, $colors = array(), $icons = array())
Registers an admin colour scheme css file.
Allows a plugin to register a new admin colour scheme. For example:
wp_admin_css_color('classic', __('Classic'), admin_url("css/colors-classic.css"), array(
    '#07273E', '#14568A', '#D54E21', '#2683AE'
));
Since
2.5.0
array $_wp_admin_css_colors
Parameters
string $key The unique key for this theme.
string $name The name of the theme.
string $url The URL of the CSS file containing the color scheme.
array $colors Optional. An array of CSS color definition strings which are used to give the user a feel for the theme.
array $icons { Optional. CSS color definitions used to color any SVG icons.
string $base SVG icon base color. string $focus SVG icon color on focus. string $current SVG icon color of current admin menu link. }
Definition at line 3092 of file general-template.php.
References $name, $url, and object.
Referenced by register_admin_color_schemes().
wp_admin_css_uri ($file = 'wp-admin')
Display the URL of a WordPress admin CSS file.
See also
WP_Styles::_css_href and its style_loader_src filter.
Since
2.3.0
Parameters
string $file file relative to wp-admin/ without its ".css" extension.
Returns
string
Filter the URI of a WordPress admin CSS file.
Since
2.3.0
Parameters
string $_file Relative path to the file with query arguments attached.
string $file Relative path to the file, minus its ".css" extension.
Definition at line 3181 of file general-template.php.
References $file, add_query_arg(), admin_url(), apply_filters(), and get_bloginfo().
Referenced by wp_admin_css().
wp_default_editor ()
Find out which editor should be displayed by default.
Works out which of the two editors to display as the current editor for a user. The 'html' setting is for the "Text" editor tab.
Since
2.5.0
Returns
string Either 'tinymce', or 'html', or 'test'
Filter which editor should be displayed by default.
Since
2.5.0
Parameters
array $r An array of editors. Accepts 'tinymce', 'html', 'test'.
Definition at line 2706 of file general-template.php.
References apply_filters(), get_user_setting(), and user_can_richedit().
Referenced by _WP_Editors\editor().
wp_editor ($content, $editor_id, $settings = array())
Renders an editor.
Using this function is the proper way to output all needed components for both TinyMCE and Quicktags. _WP_Editors should not be used directly. See https://core.trac.wordpress.org/ticket/17144.
NOTE: Once initialized the TinyMCE editor cannot be safely moved in the DOM. For that reason running wp_editor() inside of a metabox is not a good idea unless only Quicktags is used. On the post edit screen several actions can be used to include additional editors containing TinyMCE: 'edit_page_form', 'edit_form_advanced' and 'dbx_post_sidebar'. See https://core.trac.wordpress.org/ticket/19173 for more information.
See also
_WP_Editors::editor()
Since
3.3.0
Parameters
string $content Initial content for the editor.
string $editor_id HTML ID attribute value for the textarea and TinyMCE. Can only be /[a-z]+/.
array $settings See _WP_Editors::editor().
Definition at line 2742 of file general-template.php.
References $content, ABSPATH, _WP_Editors\editor(), and WPINC.
Referenced by edit_form_image_editor(), get_confirmation_ui_settings(), WP_Press_This\html(), GFAddOn\settings_textarea(), the_editor(), and wp_comment_reply().
wp_footer ()
Fire the wp_footer action.
Since
1.5.1
Print scripts or data before the closing body tag on the front end.
Since
1.5.1
Definition at line 2440 of file general-template.php.
References do_action().
wp_generator ()
Display the XHTML generator that is generated on the wp_head hook.
Since
2.5.0
Filter the output of the XHTML generator tag.
Since
2.5.0
Parameters
string $generator_type The XHTML generator.
Definition at line 3273 of file general-template.php.
References apply_filters(), and the_generator().
wp_get_archives ($args = '')
Display archive links based on type and format.
Since
1.2.0
4.4.0 $post_type arg was added.
See also
get_archives_link()
wpdb $wpdb WP_Locale $wp_locale
Parameters
string | array $args { Default archive links arguments. Optional.
string $type Type of archive to retrieve. Accepts 'daily', 'weekly', 'monthly', 'yearly', 'postbypost', or 'alpha'. Both 'postbypost' and 'alpha' display the same archive link list as well as post titles instead of displaying dates. The difference between the two is that 'alpha' will order by post title and 'postbypost' will order by post date. Default 'monthly'. string|int $limit Number of links to limit the query to. Default empty (no limit). string $format Format each link should take using the $before and $after args. Accepts 'link' (<link> tag), 'option' (<option> tag), 'html' (<li> tag), or a custom format, which generates a link anchor with $before preceding and $after succeeding. Default 'html'. string $before Markup to prepend to the beginning of each link. Default empty. string $after Markup to append to the end of each link. Default empty. bool $show_post_count Whether to display the post count alongside the link. Default false. bool|int $echo Whether to echo or return the links list. Default 1|true to echo. string $order Whether to use ascending or descending order. Accepts 'ASC', or 'DESC'. Default 'DESC'. string $post_type Post type. Default 'post'. }
Returns
string|void String when retrieving.
Filter the SQL WHERE clause for retrieving archives.
Since
2.2.0
Parameters
string $sql_where Portion of SQL query containing the WHERE clause.
array $r An array of default arguments.
Filter the SQL JOIN clause for retrieving archives.
Since
2.2.0
Parameters
string $sql_join Portion of SQL query containing JOIN clause.
array $r An array of default arguments.
This filter is documented in wp-includes/post-template.php
Definition at line 1526 of file general-template.php.
References $output, $post_type_object, $text, $url, $wp_locale, $wpdb, __, _wp_mysql_week(), absint(), add_query_arg(), apply_filters(), date_i18n(), elseif, get_archives_link(), get_day_link(), get_month_link(), get_option(), get_permalink(), get_post_type_object(), get_weekstartend(), get_year_link(), home_url(), is_post_type_viewable(), mysql2date(), wp_cache_get(), wp_cache_set(), and wp_parse_args().
Referenced by get_archives(), and WP_Widget_Archives\widget().
wp_get_document_title ()
Returns document title for the current page.
Since
4.4.0
int $page Page number of a single post. int $paged Page number of a list of posts.
Returns
string Tag with the document title.
Filter the document title before it is generated.
Passing a non-empty value will short-circuit wp_get_document_title(), returning that value instead.
Since
4.4.0
Parameters
string $title The document title. Default empty string.
Filter the separator for the document title.
Since
4.4.0
Parameters
string $sep Document title separator. Default '-'.
Filter the parts of the document title.
Since
4.4.0
Parameters
array $title { The document title parts.
string $title Title of the viewed page. string $page Optional. Page number if paginated. string $tagline Optional. Site description when on home page. string $site Optional. Site title when not on home page. }
Definition at line 827 of file general-template.php.
References $page, $paged, $title, __, _x, apply_filters(), capital_P_dangit(), convert_chars(), elseif, esc_html, get_bloginfo(), get_queried_object(), get_search_query(), get_the_date(), is_404, is_author(), is_category(), is_day(), is_front_page(), is_home(), is_month(), is_post_type_archive(), is_search(), is_singular(), is_tag(), is_tax(), is_year(), post_type_archive_title(), single_post_title(), single_term_title(), and wptexturize().
Referenced by _wp_render_title_tag(), and get_wp_title_rss().
wp_head ()
Fire the wp_head action.
Since
1.2.0
Print scripts or data in the head tag on the front end.
Since
1.5.0
Definition at line 2426 of file general-template.php.
References do_action().
wp_heartbeat_settings ($settings)
Default settings for heartbeat.
Outputs the nonce used in the heartbeat XHR
Since
3.6.0
Parameters
array $settings
Returns
array $settings
Definition at line 3468 of file general-template.php.
References admin_url(), and is_admin().
wp_login_form ($args = array())
Provides a simple login form for use anywhere within WordPress.
The login format HTML is echoed by default. Pass a false value for $echo to return it instead.
Since
3.0.0
Parameters
array $args { Optional. Array of options to control the form output. Default empty array.
bool $echo Whether to display the login form or return the form HTML code. Default true (echo). string $redirect URL to redirect to. Must be absolute, as in "https://example.com/mypage/". Default is to redirect back to the request URI. string $form_id ID attribute value for the form. Default 'loginform'. string $label_username Label for the username field. Default 'Username'. string $label_password Label for the password field. Default 'Password'. string $label_remember Label for the remember field. Default 'Remember Me'. string $label_log_in Label for the submit button. Default 'Log In'. string $id_username ID attribute value for the username field. Default 'user_login'. string $id_password ID attribute value for the password field. Default 'user_pass'. string $id_remember ID attribute value for the remember field. Default 'rememberme'. string $id_submit ID attribute value for the submit button. Default 'wp-submit'. bool $remember Whether to display the "rememberme" checkbox in the form. string $value_username Default value for the username field. Default empty. bool $value_remember Whether the "Remember Me" checkbox should be checked by default. Default false (unchecked).
}
Returns
string|void String when retrieving.
Filter the default login form output arguments.
Since
3.0.0
See also
wp_login_form()
Parameters
array $defaults An array of default login form arguments.
Filter content to display at the top of the login form.
The filter evaluates just following the opening form tag element.
Since
3.0.0
Parameters
string $content Content to display. Default empty.
array $args Array of login form arguments.
Filter content to display in the middle of the login form.
The filter evaluates just following the location where the 'login-password' field is displayed.
Since
3.0.0
Parameters
string $content Content to display. Default empty.
array $args Array of login form arguments.
Filter content to display at the bottom of the login form.
The filter evaluates just preceding the closing form tag element.
Since
3.0.0
Parameters
string $content Content to display. Default empty.
array $args Array of login form arguments.
Definition at line 405 of file general-template.php.
References $_SERVER, $form, __, apply_filters(), esc_attr(), esc_html, esc_url, is_ssl(), site_url(), and wp_parse_args().
wp_login_url ($redirect = '', $force_reauth = false)
Returns the URL that allows the user to log in to the site.
Since
2.7.0
Parameters
string $redirect Path to redirect to on login.
bool $force_reauth Whether to force reauthorization, even if a cookie is present. Default is false.
Returns
string A log in URL.
Filter the login URL.
Since
2.8.0
4.2.0 The $force_reauth parameter was added.
Parameters
string $login_url The login URL.
string $redirect The path to redirect to on login, if supplied.
bool $force_reauth Whether to force reauthorization, even if a cookie is present.
Definition at line 334 of file general-template.php.
References $redirect, add_query_arg(), apply_filters(), and site_url().
Referenced by comment_form(), WP_Customize_Manager\customize_pane_settings(), get_comment_reply_link(), get_post_reply_link(), wp_xmlrpc_server\initialise_blog_option_info(), wp_auth_check_html(), wp_loginout(), wp_redirect_admin_locations(), and wpmu_welcome_user_notification().
wp_loginout ($redirect = '', $echo = true)
Display the Log In/Out link.
Displays a link, which allows users to navigate to the Log In page to log in or log out depending on whether they are currently logged in.
Since
1.5.0
Parameters
string $redirect Optional path to redirect to on login/logout.
bool $echo Default to echo and not return the link.
Returns
string|void String when retrieving.
Filter the HTML output for the Log In/Log Out link.
Since
1.5.0
Parameters
string $link The HTML link content.
This filter is documented in wp-includes/general-template.php
Definition at line 274 of file general-template.php.
References $link, $redirect, __, apply_filters(), esc_url, wp_login_url(), and wp_logout_url().
Referenced by WP_Widget_Meta\widget().
wp_logout_url ($redirect = '')
Returns the Log Out URL.
Returns the URL that allows the user to log out of the site.
Since
2.7.0
Parameters
string $redirect Path to redirect to on logout.
Returns
string A log out URL.
Filter the logout URL.
Since
2.8.0
Parameters
string $logout_url The Log Out URL.
string $redirect Path to redirect to on logout.
Definition at line 305 of file general-template.php.
References $redirect, add_query_arg(), apply_filters(), site_url(), and wp_nonce_url().
Referenced by comment_form(), wp_admin_bar_my_account_menu(), wp_loginout(), and wp_nonce_ays().
wp_lostpassword_url ($redirect = '')
Returns the URL that allows the user to retrieve the lost password.
Since
2.8.0
Parameters
string $redirect Path to redirect to on login.
Returns
string Lost password URL.
Filter the Lost Password URL.
Since
2.8.0
Parameters
string $lostpassword_url The lost password page URL.
string $redirect The path to redirect to on login.
Definition at line 507 of file general-template.php.
References $redirect, add_query_arg(), apply_filters(), and network_site_url().
Referenced by wp_authenticate_username_password().
wp_meta ()
Theme container function for the 'wp_meta' action.
The 'wp_meta' action can have several purposes, depending on how you use it, but one purpose might have been to allow for theme switching.
Since
1.5.0
Explanation of 'wp_meta' action.
Fires before displaying echoed content in the sidebar.
Since
1.5.0
Definition at line 580 of file general-template.php.
References do_action().
Referenced by WP_Widget_Meta\widget().
wp_no_robots ()
Display a noindex meta tag.
Outputs a noindex meta tag that tells web robots not to index the page content. Typical usage is as a wp_head callback. add_action('wp_head', 'wp_no_robots');
Since
3.3.0
Definition at line 2616 of file general-template.php.
Referenced by noindex().
wp_register ($before = '<li>', $after = '</li>', $echo = true)
Display the Registration or Admin link.
Display a link which allows the user to navigate to the registration page if not logged in and registration is enabled or to the dashboard if logged in.
Since
1.5.0
Parameters
string $before Text to output before the link. Default <li>.
string $after Text to output after the link. Default </li>.
bool $echo Default to echo and not return the link.
Returns
string|void String when retrieving.
Filter the HTML link to the Registration or Admin page.
Users are sent to the admin page if logged-in, or the registration page if enabled and logged-out.
Since
1.5.0
Parameters
string $link The HTML code for the link to the Registration or Admin page.
Definition at line 539 of file general-template.php.
References $link, __, admin_url(), apply_filters(), current_user_can(), elseif, esc_url, get_option(), and wp_registration_url().
Referenced by WP_Widget_Meta\widget().
wp_registration_url ()
Returns the URL that allows the user to register on the site.
Since
3.6.0
Returns
string User registration URL.
Filter the user registration URL.
Since
3.6.0
Parameters
string $register The user registration URL.
Definition at line 363 of file general-template.php.
References apply_filters(), and site_url().
Referenced by redirect_canonical(), and wp_register().
wp_site_icon ()
Display site icon meta tags.
Since
4.3.0
HTML5 specification link icon.
Filter the site icon meta tags, so Plugins can add their own.
Since
4.3.0
Parameters
array $meta_tags Site Icon meta elements.
Definition at line 2627 of file general-template.php.
References apply_filters(), esc_url, get_site_icon_url(), has_site_icon(), and is_customize_preview().
wp_title ($sep = '&raquo;', $display = true, $seplocation = '')
Display or retrieve page title for all areas of blog.
By default, the page title will display the separator before the page title, so that the blog title will be before the page title. This is not good for title display, since the blog title shows up on most tabs and not what is important, which is the page that the user is looking at.
There are also SEO benefits to having the blog title after or to the 'right' or the page title. However, it is mostly common sense to have the blog title to the right with most browsers supporting tabs. You can achieve this by using the seplocation parameter and setting the value to 'right'. This change was introduced around 2.5.0, in case backwards compatibility of themes is important.
Since
1.0.0
WP_Locale $wp_locale
Parameters
string $sep Optional, default is '»'. How to separate the various items within the page title.
bool $display Optional, default is true. Whether to display or retrieve title.
string $seplocation Optional. Direction to display title, 'right'.
Returns
string|null String on retrieve, null when displaying.
Filter the parts of the page title.
Since
4.0.0
Parameters
array $title_array Parts of the page title.
Filter the text of the page title.
Since
2.0.0
Parameters
string $title Page title.
string $sep Title separator.
string $seplocation Location of the separator (left or right).
Definition at line 984 of file general-template.php.
References $post_type, $post_type_object, $prefix, $tax, $title, $wp_locale, __, apply_filters(), get_post_type_object(), get_queried_object(), get_query_var(), get_taxonomy(), is_404, is_archive(), is_author(), is_category(), is_front_page(), is_home(), is_page(), is_post_type_archive(), is_search(), is_single(), is_tag(), is_tax(), post_type_archive_title(), single_post_title(), single_term_title(), and zeroise().