GravityView: gquiz_percent.php File Reference
gquiz_percent.php File Reference
Namespaces
GravityView
GPL2+
Variables
$field = GravityView_View::getInstance()->getCurrentField()
if(gv_empty($field['value'], false, false)) $format = apply_filters('gravityview/field/quiz_percent/format', '%d%%')
Variable Documentation
$field
$field = GravityView_View::getInstance()->getCurrentField()
Definition at line 9 of file gquiz_percent.php.
$format
if (gv_empty($field[ 'value'], false, false)) $format = apply_filters('gravityview/field/quiz_percent/format', '%d%%')
Runs Filter:
gravityview/field/quiz_percent/format Modify the format of the display of Quiz Score (Percent) field.
See also
http://php.net/manual/en/function.sprintf.php For formatting guide
Parameters
string $format Format passed to printf() function. Default d%%, which prints as "{number}%". Notice the double %%, this prints a literal '' character.
Definition at line 21 of file gquiz_percent.php.
Referenced by GravityView_Field_List\column_value(), GravityView_API\field_value(), GravityView_API\field_width(), GVCommon\format_date(), GravityView_Widget_Search\get_date_field_format(), GravityView_Widget_Search\get_datepicker_format(), GravityView_Widget_Search\get_formatted_date(), Views_Route\get_sub_item(), GravityView_Edit_Entry_User_Registration\match_current_display_name(), Views_Route\prepare_entry_for_response(), Route\register_routes(), GravityView_API\replace_variables(), and GravityView_Merge_Tags\replace_variables().