GravityView: gravityforms.php File Reference
gravityforms.php File Reference
Data Structures
class GFForms
class RGForms
Functions
gravity_form ($id, $display_title=true, $display_description=true, $display_inactive=false, $field_values=null, $ajax=false, $tabindex=1, $echo=true)
gravity_form_enqueue_scripts ($form_id, $is_ajax=false)
Variables
$gf_license_key = ''
$gf_recaptcha_private_key = ''
$gf_recaptcha_public_key = ''
const GF_MIN_WP_VERSION '3.7'
const GF_SUPPORTED_WP_VERSION version_compare(get_bloginfo('version'), GF_MIN_WP_VERSION, '>=')
if(!defined('GRAVITY_MANAGER_URL')) if (!defined('GRAVITY_MANAGER_PROXY_URL'))
const RG_CURRENT_VIEW (!defined('IS_ADMIN')) RGForms::get('view')
Function Documentation
gravity_form ($id, $display_title = true, $display_description = true, $display_inactive = false, $field_values = null, $ajax = false, $tabindex = 1, $echo = true)
Definition at line 3194 of file gravityforms.php.
References $id, and GFForms\get_form().
gravity_form_enqueue_scripts ($form_id, $is_ajax = false)
Get a specific property of an array without needing to check if that property exists. Provide a default value if you want to return a specific value if the property is not set.
Parameters
$array array Array from which the property's value should be retrieved.
$prop string Name of the property to be retreived.
null $default mixed Value that should be returned if the property is not set or empty.
Returns
null|string|mixed
Definition at line 3203 of file gravityforms.php.
References $form_id, and GFForms\enqueue_form_scripts().
Variable Documentation
$gf_license_key = ''
Definition at line 33 of file gravityforms.php.
Referenced by GFForms\maybe_populate_keys().
$gf_recaptcha_private_key = ''
Definition at line 46 of file gravityforms.php.
Referenced by GFForms\maybe_populate_keys().
$gf_recaptcha_public_key = ''
Definition at line 47 of file gravityforms.php.
Referenced by GFForms\maybe_populate_keys().
const GF_MIN_WP_VERSION '3.7'
Definition at line 70 of file gravityforms.php.
const GF_SUPPORTED_WP_VERSION version_compare(get_bloginfo('version'), GF_MIN_WP_VERSION, '>=')
Definition at line 71 of file gravityforms.php.
Referenced by GFForms\init().
if (!defined('GRAVITY_MANAGER_URL')) if(!defined('GRAVITY_MANAGER_PROXY_URL'))
Definition at line 77 of file gravityforms.php.
const RG_CURRENT_VIEW(!defined('IS_ADMIN')) RGForms::get('view')
Definition at line 69 of file gravityforms.php.
Referenced by GF_Field_Checkbox\get_checkbox_choices(), GF_Field_Name\get_field_input(), GF_Field_Number\get_field_input(), GF_Field_Radio\get_radio_choices(), GF_Field_Address\get_state_field(), GFFormsModel\save_input(), GFFormsModel\save_lead(), and GFForms\top_toolbar().