GravityView: gravityview.php File Reference
gravityview.php File Reference
Variables
const GRAVITYVIEW_DIR plugin_dir_path(__FILE__)
"GRAVITYVIEW_DIR" "./" The absolute path to the plugin directory, with trailing slash
const GRAVITYVIEW_FILE __FILE__
Full path to the GravityView file "GRAVITYVIEW_FILE" "./gravityview.php".
const GRAVITYVIEW_URL plugin_dir_url(__FILE__)
The URL to this file, with trailing slash.
const GV_FUTURE_MIN_GF_VERSION '2.5.0'
GravityView will soon require at least this version of Gravity Forms to function properly.
const GV_FUTURE_MIN_PHP_VERSION '7.4.0'
const GV_FUTURE_MIN_WP_VERSION '5.3'
GravityView will soon require at least this version of WordPress to function properly.
const GV_MIN_GF_VERSION '2.3.3.9'
GravityView requires at least this version of Gravity Forms to function properly.
const GV_MIN_PHP_VERSION '5.6.4'
GravityView requires at least this version of PHP to function properly.
const GV_MIN_WP_VERSION '4.7.0'
GravityView requires at least this version of WordPress to function properly.
const GV_PLUGIN_VERSION (! GravityKit\GravityView\Foundation\meets_min_php_version_requirement(__FILE__, '7.2.0')) '2.17'
Constants.
if (! defined('ABSPATH'))
Plugin Name: GravityView Plugin URI: https://www.gravitykit.com Description: The best, easiest way to display Gravity Forms entries on your website.
Variable Documentation
GRAVITYVIEW_DIR
const GRAVITYVIEW_DIR plugin_dir_path(__FILE__)
"GRAVITYVIEW_DIR" "./" The absolute path to the plugin directory, with trailing slash
Definition at line 49 of file gravityview.php.
Referenced by GravityView_Default_Template_List\__construct(), Blocks\__construct(), GravityView_Preset_Event_Listings\__construct(), GravityView_Preset_Issue_Tracker\__construct(), GravityView_Preset_Job_Board\__construct(), GravityView_Preset_Profiles\__construct(), GravityView_Admin_Metaboxes\__construct(), GravityView_Preset_Staff_Profiles\__construct(), GravityView_Preset_Resume_Board\__construct(), GravityView_Preset_Website_Showcase\__construct(), GravityView_Preset_Business_Data\__construct(), GravityView_Preset_Business_Listings\__construct(), GravityView_Admin\backend_actions(), Plugin\dir(), GravityView_Edit_Entry_Render\fill_post_template(), gravityview_css_url(), gravityview_get_files_array(), gravityview_register_default_templates(), gravityview_register_gravityview_widgets(), gravityview_register_placeholder_templates(), gravityview_register_widgets(), GravityView_Ajax\import_fields(), GravityView_Admin\include_required_files(), GVCommon\js_encrypt(), GravityView_Edit_Entry_Render\load(), GravityView_Render_Settings\load_type_class(), Blocks\register_blocks(), GravityView_Field_Entry_Approval\register_scripts_and_styles(), GravityView_Metabox_Tab\render(), GravityView_Edit_Entry_Render\update_post_image(), and GravityView_Migrate\update_search_on_views().
GRAVITYVIEW_FILE
const GRAVITYVIEW_FILE __FILE__
Full path to the GravityView file "GRAVITYVIEW_FILE" "./gravityview.php".
Definition at line 40 of file gravityview.php.
Referenced by GravityView_Default_Template_List\__construct(), GravityView_Preset_Business_Data\__construct(), GravityView_Preset_Profiles\__construct(), GravityView_Preset_Resume_Board\__construct(), GravityView_Preset_Staff_Profiles\__construct(), GravityView_Preset_Website_Showcase\__construct(), GravityView_Preset_Business_Listings\__construct(), GravityView_Preset_Event_Listings\__construct(), GravityView_Preset_Issue_Tracker\__construct(), GravityView_Preset_Job_Board\__construct(), GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GravityView_Recent_Entries_Widget\admin_enqueue_scripts(), View\content(), GravityView_frontend\context_not_configured_warning(), GravityView_Lightbox_Provider_FancyBox\enqueue_scripts(), GravityView_Change_Entry_Creator\enqueue_selectwoo_assets(), GravityView_Lightbox_Provider_FancyBox\enqueue_styles(), GravityView_Entry_Notes\filter_avatar(), gravityview_get_floaty(), gravityview_register_placeholder_templates(), Plugin\is_network_activated(), Renderer\maybe_print_configuration_notice(), Renderer\maybe_print_entry_approval_notice(), Blocks\register_blocks(), GravityView_Widget_Search\register_scripts(), and Plugin\relpath().
GRAVITYVIEW_URL
const GRAVITYVIEW_URL plugin_dir_url(__FILE__)
The URL to this file, with trailing slash.
Definition at line 45 of file gravityview.php.
Referenced by GravityView_Field_Entry_Approval\register_scripts_and_styles().
GV_FUTURE_MIN_GF_VERSION
const GV_FUTURE_MIN_GF_VERSION '2.5.0'
GravityView will soon require at least this version of Gravity Forms to function properly.
Since
1.19.4
Definition at line 60 of file gravityview.php.
Referenced by GravityView_Compatibility\check_gravityforms().
GV_FUTURE_MIN_PHP_VERSION
const GV_FUTURE_MIN_PHP_VERSION '7.4.0'
Definition at line 85 of file gravityview.php.
Referenced by GravityView_Compatibility\check_php().
GV_FUTURE_MIN_WP_VERSION
const GV_FUTURE_MIN_WP_VERSION '5.3'
GravityView will soon require at least this version of WordPress to function properly.
Since
2.9.3
Definition at line 72 of file gravityview.php.
Referenced by GravityView_Compatibility\check_wordpress().
GV_MIN_GF_VERSION
const GV_MIN_GF_VERSION '2.3.3.9'
GravityView requires at least this version of Gravity Forms to function properly.
Definition at line 54 of file gravityview.php.
Referenced by GravityView_Compatibility\check_gravityforms().
GV_MIN_PHP_VERSION
const GV_MIN_PHP_VERSION '5.6.4'
GravityView requires at least this version of PHP to function properly.
Since
1.12
Definition at line 78 of file gravityview.php.
Referenced by GravityView_Compatibility\check_php().
GV_MIN_WP_VERSION
const GV_MIN_WP_VERSION '4.7.0'
GravityView requires at least this version of WordPress to function properly.
Since
1.12
Definition at line 66 of file gravityview.php.
Referenced by GravityView_Compatibility\check_wordpress().
GV_PLUGIN_VERSION
const GV_PLUGIN_VERSION(! GravityKit\GravityView\Foundation\meets_min_php_version_requirement(__FILE__, '7.2.0')) '2.17'
Constants.
The plugin version.
Definition at line 34 of file gravityview.php.
Referenced by GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GravityView_Recent_Entries_Widget\admin_enqueue_scripts(), GravityView_Compatibility\check_php(), GravityView_Compatibility\check_wordpress(), Core\configure_settings(), GravityView_frontend\enqueue_default_style(), GravityView_Lightbox_Provider_FancyBox\enqueue_scripts(), GravityView_Lightbox_Provider_FancyBox\enqueue_styles(), LicenseManager\get_site_data(), GravityView_Field_Notes\register_scripts(), GravityView_Field_Entry_Approval\register_scripts_and_styles(), GravityView_Template\register_styles(), GravityView_Welcome\tabs(), and GravityView_Welcome\welcome().
if
if(! defined('ABSPATH'))
Plugin Name: GravityView Plugin URI: https://www.gravitykit.com Description: The best, easiest way to display Gravity Forms entries on your website.
Version: 2.17 Author: GravityKit Author URI: https://www.gravitykit.com Text Domain: gk-gravityview License: GPLv2 or later License URI: http://www.gnu.org/licenses/gpl-2.0.htmlIf this file is called directly, abort.
Definition at line 15 of file gravityview.php.