GravityView: hello.php File Reference
hello.php File Reference
Namespaces
Hello_Dolly
Functions
dolly_css ()
hello_dolly ()
hello_dolly_get_lyric ()
Function Documentation
dolly_css ()
Definition at line 63 of file hello.php.
References is_rtl().
hello_dolly ()
Definition at line 54 of file hello.php.
References hello_dolly_get_lyric().
hello_dolly_get_lyric ()
These are the lyrics to Hello Dolly
Definition at line 15 of file hello.php.
References wptexturize().
Referenced by hello_dolly().