GravityView: image-edit.php File Reference
image-edit.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_crop_image_resource ($img, $x, $y, $w, $h)
Crops an image resource.
_flip_image_resource ($img, $horz, $vert)
Flips an image resource.
_image_get_preview_ratio ($w, $h)
Image preview ratio.
_rotate_image_resource ($img, $angle)
Returns an image resource.
image_edit_apply_changes ($image, $changes)
Performs group of changes on Editor specified.
stream_preview_image ($post_id)
Streams image in post to browser, along with enqueued changes in $_REQUEST['history'].
wp_image_editor ($post_id, $msg=false)
Loads the WP image-editing interface.
wp_restore_image ($post_id)
Restores the metadata for a given attachment.
wp_save_image ($post_id)
Saves image to post along with enqueued changes in $_REQUEST['history'].
wp_save_image_file ($filename, $image, $mime_type, $post_id)
Saves Image to File.
wp_stream_image ($image, $mime_type, $post_id)
Streams image in WP_Image_Editor to browser.
Function Documentation
_crop_image_resource ($img, $x, $y, $w, $h)
Crops an image resource.
Internal use only.
Since
2.9.0
Parameters
resource $img Image resource.
float $x Source point x-coordinate.
float $y Source point y-cooredinate.
float $w Source width.
float $h Source height.
Returns
resource (maybe) cropped image resource.
Definition at line 445 of file image-edit.php.
References wp_imagecreatetruecolor().
Referenced by image_edit_apply_changes().
_flip_image_resource ($img, $horz, $vert)
Flips an image resource.
Internal use only.
Since
2.9.0
Parameters
resource $img Image resource.
bool $horz Whether to flip horizontally.
bool $vert Whether to flip vertically.
Returns
resource (maybe) flipped image resource.
Definition at line 413 of file image-edit.php.
References __, _deprecated_function(), and wp_imagecreatetruecolor().
Referenced by image_edit_apply_changes().
_image_get_preview_ratio ($w, $h)
Image preview ratio.
Internal use only.
Since
2.9.0
Parameters
int $w Image width in pixels.
int $h Image height in pixels.
Returns
float|int Image preview ratio.
Definition at line 375 of file image-edit.php.
Referenced by image_edit_apply_changes(), and stream_preview_image().
_rotate_image_resource ($img, $angle)
Returns an image resource.
Internal use only.
Since
2.9.0
Parameters
resource $img Image resource.
float | int $angle Image rotation angle, in degrees.
Returns
resource|false GD image resource, false otherwise.
Definition at line 390 of file image-edit.php.
References __, and _deprecated_function().
Referenced by image_edit_apply_changes().
image_edit_apply_changes ($image, $changes)
Performs group of changes on Editor specified.
Since
2.9.0
Parameters
WP_Image_Editor $image {
See also
WP_Image_Editor} instance.
Parameters
array $changes Array of change operations.
Returns
WP_Image_Editor {
See also
WP_Image_Editor} instance with changes applied.
Filter the WP_Image_Editor instance before applying changes to the image.
Since
3.5.0
Parameters
WP_Image_Editor $image WP_Image_Editor instance.
array $changes Array of change operations.
Filter the GD image resource before applying changes to the image.
Since
2.9.0
Parameters
resource $image GD image resource.
array $changes Array of change operations.
Definition at line 465 of file image-edit.php.
References $i, $image, $size, __, _crop_image_resource(), _deprecated_argument(), _flip_image_resource(), _image_get_preview_ratio(), _rotate_image_resource(), apply_filters(), and elseif.
Referenced by stream_preview_image(), and wp_save_image().
stream_preview_image ($post_id)
Streams image in post to browser, along with enqueued changes in $_REQUEST['history'].
Parameters
int $post_id
Returns
bool
This filter is documented in wp-admin/admin.php
Definition at line 586 of file image-edit.php.
References $post, $post_id, $size, _image_get_preview_ratio(), _load_image_to_edit_path(), apply_filters(), get_post(), image_edit_apply_changes(), is_wp_error(), null, wp_get_image_editor(), WP_MAX_MEMORY_LIMIT, wp_stream_image(), and wp_unslash().
Referenced by wp_ajax_imgedit_preview().
wp_image_editor ($post_id, $msg = false)
Loads the WP image-editing interface.
Parameters
int $post_id Post ID.
bool | object $msg Optional. Message to display for image editor updates or errors. Default false.
Definition at line 16 of file image-edit.php.
References $msg, $post_id, __, _e, checked(), disabled(), elseif, endif, esc_html_e, get_post_meta(), get_post_mime_type(), height, image_get_intermediate_size(), input, label, name, width, wp_constrain_dimensions(), wp_get_attachment_metadata(), and wp_image_editor_supports().
Referenced by edit_form_image_editor(), and wp_ajax_image_editor().
wp_restore_image ($post_id)
Restores the metadata for a given attachment.
Since
2.9.0
Parameters
int $post_id Attachment post ID.
Returns
stdClass Image restoration message object.
Definition at line 625 of file image-edit.php.
References $file, $msg, $post_id, __, _wp_relative_upload_path(), elseif, get_attached_file(), get_intermediate_image_sizes(), get_post_meta(), path_join(), update_attached_file(), update_post_meta(), wp_delete_file(), wp_get_attachment_metadata(), and wp_update_attachment_metadata().
Referenced by wp_ajax_image_editor().
wp_save_image ($post_id)
Saves image to post along with enqueued changes in $_REQUEST['history'].
array $_wp_additional_image_sizes
Parameters
int $post_id
Returns
Definition at line 710 of file image-edit.php.
References $path, $post, $post_id, $size, __, _load_image_to_edit_path(), _wp_relative_upload_path(), elseif, esc_js(), get_attached_file(), get_intermediate_image_sizes(), get_option(), get_post(), get_post_meta(), image_edit_apply_changes(), is_wp_error(), path_join(), update_attached_file(), update_post_meta(), wp_delete_file(), wp_get_attachment_image_src(), wp_get_attachment_metadata(), wp_get_attachment_url(), wp_get_image_editor(), wp_save_image_file(), wp_unslash(), and wp_update_attachment_metadata().
Referenced by wp_ajax_image_editor().
wp_save_image_file ($filename, $image, $mime_type, $post_id)
Saves Image to File.
Parameters
string $filename
WP_Image_Editor $image
string $mime_type
int $post_id
Returns
bool
This filter is documented in wp-admin/includes/image-edit.php
Filter whether to skip saving the image file.
Returning a non-null value will short-circuit the save method, returning that value instead.
Since
3.5.0
Parameters
mixed $override Value to return instead of saving. Default null.
string $filename Name of the file to be saved.
WP_Image_Editor $image WP_Image_Editor instance.
string $mime_type Image mime type.
int $post_id Post ID.
This filter is documented in wp-admin/includes/image-edit.php
Filter whether to skip saving the image file.
Returning a non-null value will short-circuit the save method, returning that value instead.
Since
2.9.0
Parameters
mixed $override Value to return instead of saving. Default null.
string $filename Name of the file to be saved.
WP_Image_Editor $image WP_Image_Editor instance.
string $mime_type Image mime type.
int $post_id Post ID.
This filter is documented in wp-includes/class-wp-image-editor.php
Definition at line 298 of file image-edit.php.
References $image, $post_id, __, _deprecated_argument(), apply_filters(), and null.
Referenced by wp_save_image().
wp_stream_image ($image, $mime_type, $post_id)
Streams image in WP_Image_Editor to browser.
Provided for backcompat reasons
Parameters
WP_Image_Editor $image
string $mime_type
int $post_id
Returns
bool
Filter the WP_Image_Editor instance for the image to be streamed to the browser.
Since
3.5.0
Parameters
WP_Image_Editor $image WP_Image_Editor instance.
int $post_id Post ID.
Filter the GD image resource to be streamed to the browser.
Since
2.9.0
Parameters
resource $image Image resource to be streamed.
int $post_id Post ID.
Definition at line 242 of file image-edit.php.
References $image, $post_id, __, _deprecated_argument(), apply_filters(), is_wp_error(), and null.
Referenced by GFForms\captcha_image(), and stream_preview_image().