GravityView: upgrade.php File Reference
includes/upgrade.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
__get_option ($setting)
Utility version of get_option that is private to install/upgrade.
add_clean_index ($table, $index)
Adds an index to a specified table.
dbDelta ($queries= '', $execute=true)
Modifies the database based on specified SQL statements.
deslash ($content)
Filters for content to remove unnecessary slashes.
drop_index ($table, $index)
Drops a specified index from a table.
get_alloptions_110 ()
Retrieve all options as it was for 1.2.
make_db_current ($tables= 'all')
Updates the database tables to a new schema.
make_db_current_silent ($tables= 'all')
Updates the database tables to a new schema, but without displaying results.
make_site_theme ()
Creates a site theme.
make_site_theme_from_default ($theme_name, $template)
Creates a site theme from the default theme.
make_site_theme_from_oldschool ($theme_name, $template)
Creates a site theme from an existing theme.
maybe_add_column ($table_name, $column_name, $create_ddl)
Adds column to a database table if it doesn't already exist.
maybe_convert_table_to_utf8mb4 ($table)
If a table only contains utf8 or utf8mb4 columns, convert it to utf8mb4.
maybe_create_table ($table_name, $create_ddl)
Creates a table in the database if it doesn't already exist.
maybe_disable_automattic_widgets ()
Disables the Automattic widgets plugin, which was merged into core.
maybe_disable_link_manager ()
Disables the Link Manager on upgrade if, at the time of upgrade, no links exist in the DB.
pre_schema_upgrade ()
Runs before the schema is upgraded.
translate_level_to_role ($level)
Translate user level to user role name.
upgrade_100 ()
Execute changes made in WordPress 1.0.
upgrade_101 ()
Execute changes made in WordPress 1.0.1.
upgrade_110 ()
Execute changes made in WordPress 1.2.
upgrade_130 ()
Execute changes made in WordPress 1.5.
upgrade_160 ()
Execute changes made in WordPress 2.0.
upgrade_210 ()
Execute changes made in WordPress 2.1.
upgrade_230 ()
Execute changes made in WordPress 2.3.
upgrade_230_old_tables ()
Remove old categories, link2cat, and post2cat database tables.
upgrade_230_options_table ()
Remove old options from the database.
upgrade_250 ()
Execute changes made in WordPress 2.5.0.
upgrade_252 ()
Execute changes made in WordPress 2.5.2.
upgrade_260 ()
Execute changes made in WordPress 2.6.
upgrade_270 ()
Execute changes made in WordPress 2.7.
upgrade_280 ()
Execute changes made in WordPress 2.8.
upgrade_290 ()
Execute changes made in WordPress 2.9.
upgrade_300 ()
Execute changes made in WordPress 3.0.
upgrade_330 ()
Execute changes made in WordPress 3.3.
upgrade_340 ()
Execute changes made in WordPress 3.4.
upgrade_350 ()
Execute changes made in WordPress 3.5.
upgrade_370 ()
Execute changes made in WordPress 3.7.
upgrade_372 ()
Execute changes made in WordPress 3.7.2.
upgrade_380 ()
Execute changes made in WordPress 3.8.0.
upgrade_400 ()
Execute changes made in WordPress 4.0.0.
upgrade_420 ()
Execute changes made in WordPress 4.2.0.
upgrade_430 ()
Executes changes made in WordPress 4.3.0.
upgrade_430_fix_comments ()
Executes comments changes made in WordPress 4.3.0.
upgrade_431 ()
Executes changes made in WordPress 4.3.1.
upgrade_440 ()
Executes changes made in WordPress 4.4.0.
upgrade_450 ()
Execute changes made in WordPress 4.5.0.
upgrade_all ()
Functions to be called in install and upgrade scripts.
upgrade_network ()
Executes network-level upgrade routines.
upgrade_old_slugs ()
Upgrade old slugs made in version 2.2.
wp_check_mysql_version ()
Checks the version of the installed MySQL binary.
wp_install_maybe_enable_pretty_permalinks ()
Maybe enable pretty permalinks on install.
wp_should_upgrade_global_tables ()
Determine if global tables should be upgraded.
Variables
if(!function_exists('wp_install'))($blog_title, $user_name, $user_email, $public, $deprecated= '', $user_password= '', $language= '') endif
WordPress Administration API.
Function Documentation
__get_option ($setting)
Utility version of get_option that is private to install/upgrade.
Since
1.5.1 private
wpdb $wpdb
Parameters
string $setting Option name.
Returns
mixed
Definition at line 2018 of file includes/upgrade.php.
References $option, $wpdb, maybe_unserialize(), and untrailingslashit().
Referenced by make_site_theme(), make_site_theme_from_default(), make_site_theme_from_oldschool(), maybe_disable_automattic_widgets(), populate_options(), upgrade_130(), and upgrade_all().
add_clean_index ($table, $index)
Adds an index to a specified table.
Since
1.0.1
wpdb $wpdb
Parameters
string $table Database table name.
string $index Database table index column.
Returns
true True, when done with execution.
Definition at line 1902 of file includes/upgrade.php.
References $wpdb, and drop_index().
Referenced by upgrade_101().
dbDelta ($queries = '', $execute = true)
Modifies the database based on specified SQL statements.
Useful for creating new tables and updating existing tables to a new structure.
Since
1.5.0
wpdb $wpdb
Parameters
string | array $queries Optional. The query to run. Can be multiple queries in an array, or a string of queries separated by semicolons. Default empty.
bool $execute Optional. Whether or not to execute the query right away. Default true.
Returns
array Strings containing the results of the various update queries.
Filter the dbDelta SQL queries.
Since
3.3.0
Parameters
array $queries An array of dbDelta SQL queries.
Filter the dbDelta SQL queries for creating tables and/or databases.
Queries filterable via this hook contain "CREATE TABLE" or "CREATE DATABASE".
Since
3.3.0
Parameters
array $cqueries An array of dbDelta create SQL queries.
Filter the dbDelta SQL queries for inserting or updating.
Queries filterable via this hook contain "INSERT INTO" or "UPDATE".
Since
3.3.0
Parameters
array $iqueries An array of dbDelta insert or update SQL queries.
Definition at line 2083 of file includes/upgrade.php.
References $wpdb, apply_filters(), elseif, wp_get_db_schema(), and wp_should_upgrade_global_tables().
Referenced by make_db_current(), make_db_current_silent(), GFForms\setup_database(), and GFFeedAddOn\upgrade_base().
deslash ($content)
Filters for content to remove unnecessary slashes.
Since
1.5.0
Parameters
string $content The content to modify.
Returns
string The de-slashed content.
Definition at line 2046 of file includes/upgrade.php.
References $content.
Referenced by upgrade_130().
drop_index ($table, $index)
Drops a specified index from a table.
Since
1.0.1
wpdb $wpdb
Parameters
string $table Database table name.
string $index Index name to drop.
Returns
true True, when finished.
Definition at line 1879 of file includes/upgrade.php.
References $i, and $wpdb.
Referenced by add_clean_index(), and GFForms\setup_database().
get_alloptions_110 ()
Retrieve all options as it was for 1.2.
Since
1.2.0
wpdb $wpdb
Returns
stdClass List of options.
Definition at line 1993 of file includes/upgrade.php.
References $option, $options, $wpdb, and untrailingslashit().
Referenced by upgrade_110().
make_db_current ($tables = 'all')
Updates the database tables to a new schema.
By default, updates all the tables to use the latest defined schema, but can also be used to update a specific set of tables in wp_get_db_schema().
Since
1.5.0
dbDelta
Parameters
string $tables Optional. Which set of tables to update. Default is 'all'.
Definition at line 2350 of file includes/upgrade.php.
References dbDelta().
make_db_current_silent ($tables = 'all')
Updates the database tables to a new schema, but without displaying results.
By default, updates all the tables to use the latest defined schema, but can also be used to update a specific set of tables in wp_get_db_schema().
Since
1.5.0
See also
make_db_current()
Parameters
string $tables Optional. Which set of tables to update. Default is 'all'.
Definition at line 2369 of file includes/upgrade.php.
References dbDelta().
Referenced by install_blog().
make_site_theme ()
Creates a site theme.
{
Definition at line 2530 of file includes/upgrade.php.
References $current_template, $template, __get_option(), ABSPATH, make_site_theme_from_default(), make_site_theme_from_oldschool(), sanitize_title(), update_option(), and WP_CONTENT_DIR.
Referenced by upgrade_130().
make_site_theme_from_default ($theme_name, $template)
Creates a site theme from the default theme.
{
Definition at line 2467 of file includes/upgrade.php.
References $image, __get_option(), elseif, and WP_CONTENT_DIR.
Referenced by make_site_theme().
make_site_theme_from_oldschool ($theme_name, $template)
Creates a site theme from an existing theme.
{
Definition at line 2384 of file includes/upgrade.php.
References $home_path, __get_option(), ABSPATH, get_home_path(), str_replace, and WP_CONTENT_DIR.
Referenced by make_site_theme().
maybe_add_column ($table_name, $column_name, $create_ddl)
Adds column to a database table if it doesn't already exist.
Since
1.3.0
wpdb $wpdb
Parameters
string $table_name The table name to modify.
string $column_name The column name to add to the table.
string $create_ddl The SQL statement used to add the column.
Returns
bool True if already exists or on successful completion, false on error.
Definition at line 1921 of file includes/upgrade.php.
References $wpdb.
maybe_convert_table_to_utf8mb4 ($table)
If a table only contains utf8 or utf8mb4 columns, convert it to utf8mb4.
Since
4.2.0
wpdb $wpdb
Parameters
string $table The table to convert.
Returns
bool true if the table was converted, false if it wasn't.
Definition at line 1951 of file includes/upgrade.php.
References $charset, and $wpdb.
Referenced by pre_schema_upgrade(), upgrade_430(), and upgrade_network().
maybe_create_table ($table_name, $create_ddl)
Creates a table in the database if it doesn't already exist.
This method checks for an existing database and creates a new one if it's not already present. It doesn't rely on MySQL's "IF NOT EXISTS" statement, but chooses to query all tables first and then run the SQL statement creating the table.
Since
1.0.0
wpdb $wpdb
Parameters
string $table_name Database table name to create.
string $create_ddl SQL statement to create table.
Returns
bool If table already exists or was created by function.
Definition at line 1849 of file includes/upgrade.php.
References $wpdb.
maybe_disable_automattic_widgets ()
Disables the Automattic widgets plugin, which was merged into core.
Since
2.2.0
Definition at line 2619 of file includes/upgrade.php.
References $plugin, $plugins, __get_option(), and update_option().
Referenced by upgrade_all().
maybe_disable_link_manager ()
Disables the Link Manager on upgrade if, at the time of upgrade, no links exist in the DB.
Since
3.5.0
int $wp_current_db_version wpdb $wpdb WordPress database abstraction object.
Definition at line 2639 of file includes/upgrade.php.
References $wpdb, get_option(), and update_option().
Referenced by upgrade_all().
pre_schema_upgrade ()
Runs before the schema is upgraded.
Since
2.9.0
int $wp_current_db_version wpdb $wpdb WordPress database abstraction object.
Definition at line 2654 of file includes/upgrade.php.
References $wpdb, is_multisite(), maybe_convert_table_to_utf8mb4(), and wp_should_upgrade_global_tables().
translate_level_to_role ($level)
Translate user level to user role name.
Since
2.0.0
Parameters
int $level User level.
Returns
string User role name.
Definition at line 2579 of file includes/upgrade.php.
Referenced by upgrade_160().
upgrade_100 ()
Execute changes made in WordPress 1.0.
Since
1.0.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 571 of file includes/upgrade.php.
References $post, $wpdb, endforeach, endif, and sanitize_title().
Referenced by upgrade_all().
upgrade_101 ()
Execute changes made in WordPress 1.0.1.
Since
1.0.1
wpdb $wpdb WordPress database abstraction object.
Definition at line 630 of file includes/upgrade.php.
References $wpdb, and add_clean_index().
Referenced by upgrade_all().
upgrade_110 ()
Execute changes made in WordPress 1.2.
Since
1.2.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 651 of file includes/upgrade.php.
References $gmt_time, $user, $wpdb, add_option(), date, get_alloptions_110(), and sanitize_title().
Referenced by upgrade_all().
upgrade_130 ()
Execute changes made in WordPress 1.5.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 714 of file includes/upgrade.php.
References $comment, $link, $option, $options, $post, $post_title, $wpdb, __get_option(), deslash(), get_permalink(), make_site_theme(), and update_option().
Referenced by upgrade_all().
upgrade_160 ()
Execute changes made in WordPress 2.0.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object. int $wp_current_db_version
Definition at line 802 of file includes/upgrade.php.
References $comment, $id, $user, $wpdb, endforeach, endif, get_post_meta(), get_user_meta(), populate_roles_160(), translate_level_to_role(), update_attached_file(), update_user_meta(), and wp_slash().
Referenced by upgrade_all().
upgrade_210 ()
Execute changes made in WordPress 2.1.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object. int $wp_current_db_version
Definition at line 889 of file includes/upgrade.php.
References $now, $post, $wpdb, elseif, mysql2date(), populate_roles_210(), and wp_schedule_single_event().
Referenced by upgrade_all().
upgrade_230 ()
Execute changes made in WordPress 2.3.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object. int $wp_current_db_version
Definition at line 937 of file includes/upgrade.php.
References $count, $description, $id, $link, $name, $post, $post_id, $wpdb, if, populate_roles_230(), sanitize_title(), update_option(), and wp_slash().
Referenced by upgrade_all().
upgrade_230_old_tables ()
Remove old categories, link2cat, and post2cat database tables.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 1133 of file includes/upgrade.php.
References $wpdb.
Referenced by upgrade_all().
upgrade_230_options_table ()
Remove old options from the database.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 1116 of file includes/upgrade.php.
References $wpdb.
Referenced by upgrade_all().
upgrade_250 ()
Execute changes made in WordPress 2.5.0.
Since
2.5.0
int $wp_current_db_version
Definition at line 1162 of file includes/upgrade.php.
References populate_roles_250().
Referenced by upgrade_all().
upgrade_252 ()
Execute changes made in WordPress 2.5.2.
Since
2.5.2
wpdb $wpdb WordPress database abstraction object.
Definition at line 1179 of file includes/upgrade.php.
References $wpdb.
Referenced by upgrade_all().
upgrade_260 ()
Execute changes made in WordPress 2.6.
Since
2.6.0
int $wp_current_db_version
Definition at line 1193 of file includes/upgrade.php.
References populate_roles_260().
Referenced by upgrade_all().
upgrade_270 ()
Execute changes made in WordPress 2.7.
Since
2.7.0
wpdb $wpdb WordPress database abstraction object. int $wp_current_db_version
Definition at line 1209 of file includes/upgrade.php.
References $wpdb, and populate_roles_270().
Referenced by upgrade_all().
upgrade_280 ()
Execute changes made in WordPress 2.8.
Since
2.8.0
int $wp_current_db_version wpdb $wpdb WordPress database abstraction object.
Definition at line 1229 of file includes/upgrade.php.
References $value, $wpdb, is_multisite(), populate_roles_280(), refresh_blog_details(), and update_option().
Referenced by upgrade_all().
upgrade_290 ()
Execute changes made in WordPress 2.9.
Since
2.9.0
int $wp_current_db_version
Definition at line 1259 of file includes/upgrade.php.
References get_option(), and update_option().
Referenced by upgrade_all().
upgrade_300 ()
Execute changes made in WordPress 3.0.
Since
3.0.0
int $wp_current_db_version wpdb $wpdb WordPress database abstraction object.
Definition at line 1280 of file includes/upgrade.php.
References $prefix, $wpdb, add_site_option(), get_site_option(), is_main_site(), is_multisite(), populate_roles_300(), and wp_should_upgrade_global_tables().
Referenced by upgrade_all().
upgrade_330 ()
Execute changes made in WordPress 3.3.
Since
3.3.0
int $wp_current_db_version wpdb $wpdb array $wp_registered_widgets array $sidebars_widgets
Definition at line 1328 of file includes/upgrade.php.
References $i, $id, $name, $sidebars_widgets, $wp_registered_widgets, $wpdb, elseif, get_option(), retrieve_widgets(), sanitize_title(), update_option(), and wp_should_upgrade_global_tables().
Referenced by upgrade_all().
upgrade_340 ()
Execute changes made in WordPress 3.4.
Since
3.4.0
int $wp_current_db_version wpdb $wpdb
Definition at line 1401 of file includes/upgrade.php.
References $wpdb, add_option(), delete_option(), get_option(), null, and wp_should_upgrade_global_tables().
Referenced by upgrade_all().
upgrade_350 ()
Execute changes made in WordPress 3.5.
Since
3.5.0
int $wp_current_db_version wpdb $wpdb
Definition at line 1438 of file includes/upgrade.php.
References $name, $wpdb, get_post_types(), get_taxonomies(), get_term_by(), str_replace, update_option(), wp_delete_term(), and wp_should_upgrade_global_tables().
Referenced by upgrade_all().
upgrade_370 ()
Execute changes made in WordPress 3.7.
Since
3.7.0
int $wp_current_db_version
Definition at line 1468 of file includes/upgrade.php.
References wp_clear_scheduled_hook().
Referenced by upgrade_all().
upgrade_372 ()
Execute changes made in WordPress 3.7.2.
Since
3.7.2
3.8.0
int $wp_current_db_version
Definition at line 1483 of file includes/upgrade.php.
References wp_clear_scheduled_hook().
Referenced by upgrade_all().
upgrade_380 ()
Execute changes made in WordPress 3.8.0.
Since
3.8.0
int $wp_current_db_version
Definition at line 1497 of file includes/upgrade.php.
References deactivate_plugins().
Referenced by upgrade_all().
upgrade_400 ()
Execute changes made in WordPress 4.0.0.
Since
4.0.0
int $wp_current_db_version
Definition at line 1512 of file includes/upgrade.php.
References get_available_languages(), get_option(), is_multisite(), update_option(), and WPLANG.
Referenced by upgrade_all().
upgrade_420 ()
Execute changes made in WordPress 4.2.0.
Since
4.2.0
int $wp_current_db_version wpdb $wpdb
Definition at line 1534 of file includes/upgrade.php.
upgrade_430 ()
Executes changes made in WordPress 4.3.0.
Since
4.3.0
int $wp_current_db_version Current version. wpdb $wpdb WordPress database abstraction object.
Definition at line 1545 of file includes/upgrade.php.
References $wpdb, is_multisite(), maybe_convert_table_to_utf8mb4(), update_option(), upgrade_430_fix_comments(), wp_schedule_single_event(), and wp_should_upgrade_global_tables().
Referenced by upgrade_all().
upgrade_430_fix_comments ()
Executes comments changes made in WordPress 4.3.0.
Since
4.3.0
int $wp_current_db_version Current version. wpdb $wpdb WordPress database abstraction object.
Definition at line 1584 of file includes/upgrade.php.
References $comment, $wpdb, elseif, is_wp_error(), and wp_delete_comment().
Referenced by upgrade_430().
upgrade_431 ()
Executes changes made in WordPress 4.3.1.
Since
4.3.1
Definition at line 1631 of file includes/upgrade.php.
References _get_cron_array(), and _set_cron_array().
Referenced by upgrade_all().
upgrade_440 ()
Executes changes made in WordPress 4.4.0.
Since
4.4.0
int $wp_current_db_version Current version. wpdb $wpdb WordPress database abstraction object.
Definition at line 1649 of file includes/upgrade.php.
References $wpdb, and wp_roles().
Referenced by upgrade_all().
upgrade_450 ()
Execute changes made in WordPress 4.5.0.
Since
4.5.0
int $wp_current_db_version
Definition at line 1673 of file includes/upgrade.php.
References wp_clear_scheduled_hook().
Referenced by upgrade_all().
upgrade_all ()
Functions to be called in install and upgrade scripts.
Contains conditional checks to determine which upgrade scripts to run, based on database version and WP version being updated-to.
Since
1.0.1
int $wp_current_db_version int $wp_db_version
Definition at line 456 of file includes/upgrade.php.
References $template, $wp_db_version, __get_option(), maybe_disable_automattic_widgets(), maybe_disable_link_manager(), populate_options(), update_option(), upgrade_100(), upgrade_101(), upgrade_110(), upgrade_130(), upgrade_160(), upgrade_210(), upgrade_230(), upgrade_230_old_tables(), upgrade_230_options_table(), upgrade_250(), upgrade_252(), upgrade_260(), upgrade_270(), upgrade_280(), upgrade_290(), upgrade_300(), upgrade_330(), upgrade_340(), upgrade_350(), upgrade_370(), upgrade_372(), upgrade_380(), upgrade_400(), upgrade_430(), upgrade_431(), upgrade_440(), upgrade_450(), and upgrade_old_slugs().
upgrade_network ()
Executes network-level upgrade routines.
Since
3.0.0
int $wp_current_db_version wpdb $wpdb
Definition at line 1687 of file includes/upgrade.php.
References $value, $wpdb, delete_site_option(), get_site_option(), is_main_network(), maybe_convert_table_to_utf8mb4(), update_site_option(), wp_get_themes(), and wp_should_upgrade_global_tables().
upgrade_old_slugs ()
Upgrade old slugs made in version 2.2.
Since
2.2.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 1148 of file includes/upgrade.php.
References $wpdb.
Referenced by upgrade_all().
wp_check_mysql_version ()
Checks the version of the installed MySQL binary.
Since
2.1.0
wpdb $wpdb
Definition at line 2607 of file includes/upgrade.php.
References $wpdb, and is_wp_error().
wp_install_maybe_enable_pretty_permalinks ()
Maybe enable pretty permalinks on install.
If after enabling pretty permalinks don't work, fallback to query-string permalinks.
Since
4.2.0
WP_Rewrite $wp_rewrite WordPress rewrite component.
Returns
bool Whether pretty permalinks are enabled. False otherwise.
Fires after a site is fully upgraded.
Since
3.9.0
Parameters
int $wp_db_version The new $wp_db_version.
int $wp_current_db_version The old (current) $wp_db_version.
Definition at line 290 of file includes/upgrade.php.
References $permalink_structure, $wp_rewrite, get_bloginfo(), get_option(), get_permalink(), home_url(), wp_remote_get(), and wp_remote_retrieve_header().
wp_should_upgrade_global_tables ()
Determine if global tables should be upgraded.
This function performs a series of checks to ensure the environment allows for the safe upgrading of global WordPress database tables. It is necessary because global tables will commonly grow to millions of rows on large installations, and the ability to control their upgrade routines can be critical to the operation of large networks.
In a future iteration, this function may use wp_is_large_network() to more- intelligently prevent global table upgrades. Until then, we make sure WordPress is on the main site of the main network, to avoid running queries more than once in multi-site or multi-network environments.
Since
4.3.0
Returns
bool Whether to run the upgrade routines on global tables.
Filter if upgrade routines should be run on global tables.
Parameters
bool $should_upgrade Whether to run the upgrade routines on global tables.
Definition at line 2753 of file includes/upgrade.php.
References apply_filters(), is_main_network(), and is_main_site().
Referenced by dbDelta(), pre_schema_upgrade(), upgrade_300(), upgrade_330(), upgrade_340(), upgrade_350(), upgrade_430(), and upgrade_network().
Variable Documentation
if (!function_exists('install_global_terms')) () endif
WordPress Administration API.
Install global terms.
WordPress Schema API
Since
3.0.0
wpdb $wpdb string $charset_collate
Definition at line 21 of file includes/upgrade.php.
Referenced by upgrade_100(), and upgrade_160().