GravityView: options.php File Reference
includes/options.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
options_discussion_add_js ()
Output JavaScript to toggle display of additional settings if avatars are disabled.
options_general_add_js ()
Display JavaScript on the page.
options_permalink_add_js ()
Display JavaScript on the page.
options_reading_add_js ()
Display JavaScript on the page.
options_reading_blog_charset ()
Render the blog charset setting.
Function Documentation
options_discussion_add_js ()
Output JavaScript to toggle display of additional settings if avatars are disabled.
Since
4.2.0
Definition at line 15 of file includes/options.php.
References checked().
options_general_add_js ()
Display JavaScript on the page.
Since
3.5.0
Definition at line 34 of file includes/options.php.
References get_home_url(), and wp_json_encode().
options_permalink_add_js ()
Display JavaScript on the page.
Since
3.5.0
Definition at line 94 of file includes/options.php.
options_reading_add_js ()
Display JavaScript on the page.
Since
3.5.0
Definition at line 116 of file includes/options.php.
options_reading_blog_charset ()
Render the blog charset setting.
Since
3.5.0
Definition at line 138 of file includes/options.php.
References __, esc_attr(), and get_option().