GravityView: plugin-install.php File Reference
includes/plugin-install.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
display_plugins_table ()
Display plugin content based on plugin list.
install_dashboard ()
install_plugin_information ()
Display plugin information in dialog box form.
install_plugin_install_status ($api, $loop=false)
Determine the status we can perform on a plugin.
install_plugins_favorites_form ()
Show a username form for the favorites page.
install_plugins_upload ()
Upload from zip.
install_popular_tags ($args=array())
Retrieve popular WordPress plugin tags.
install_search_form ($type_selector=true)
Display search form for searching plugins.
plugins_api ($action, $args=array())
Retrieves plugin installer pages from the WordPress.org Plugins API.
Variables
$date_format = __('M j, Y @ H:i')
exit
</style > foreach ((array) $api->sections as $section_name=> $content)
if (!empty($api->last_updated))
Function Documentation
display_plugins_table ()
Display plugin content based on plugin list.
Since
2.7.0
WP_List_Table $wp_list_table
Definition at line 324 of file includes/plugin-install.php.
References $wp_list_table, __, current_filter(), and get_user_option().
Referenced by install_dashboard().
install_dashboard ()
Since
2.7.0
Definition at line 211 of file includes/plugin-install.php.
References $tags, $url, __, _e, display_plugins_table(), esc_url, install_popular_tags(), is_wp_error(), object, sanitize_title_with_dashes(), self_admin_url(), and wp_generate_tag_cloud().
install_plugin_information ()
Display plugin information in dialog box form.
Since
2.7.0
string $tab string $wp_version
Definition at line 427 of file includes/plugin-install.php.
References $content, __, _x, esc_attr(), esc_url, iframe_header(), image, is_ssl(), is_wp_error(), plugins_api(), wp_die(), wp_kses(), and wp_unslash().
install_plugin_install_status ($api, $loop = false)
Determine the status we can perform on a plugin.
Since
3.0.0
Parameters
array | object $api
bool $loop
Returns
type
Definition at line 354 of file includes/plugin-install.php.
References $file, $plugin, $url, current_user_can(), delete_site_transient(), elseif, get_plugins(), get_site_transient(), object, self_admin_url(), wp_nonce_url(), wp_unslash(), and wp_update_plugins().
Referenced by WP_Plugin_Install_List_Table\display_rows().
install_plugins_favorites_form ()
Show a username form for the favorites page.
Since
3.5.0
Definition at line 302 of file includes/plugin-install.php.
References $user, _e, get_user_option(), input, label, name, and wp_unslash().
install_plugins_upload ()
Upload from zip.
Since
2.8.0
Definition at line 283 of file includes/plugin-install.php.
References __, _e, input, label, name, submit_button(), and wp_nonce_field().
install_popular_tags ($args = array())
Retrieve popular WordPress plugin tags.
Since
2.7.0
Parameters
array $args
Returns
array
Definition at line 193 of file includes/plugin-install.php.
References $tags, get_site_transient(), is_wp_error(), plugins_api(), and set_site_transient().
Referenced by install_dashboard().
install_search_form ($type_selector = true)
Display search form for searching plugins.
Since
2.7.0
Parameters
bool $type_selector
Definition at line 252 of file includes/plugin-install.php.
References __, _e, _ex(), endif, esc_attr__(), input, label, name, selected(), submit_button(), and wp_unslash().
Referenced by WP_Plugin_Install_List_Table\views().
plugins_api ($action, $args = array())
Retrieves plugin installer pages from the WordPress.org Plugins API.
It is possible for a plugin to override the Plugin API result with three filters. Assume this is for plugins, which can extend on the Plugin Info to offer more choices. This is very powerful and must be used with care when overriding the filters.
The first filter, {
See also
'plugins_api_args'}, is for the args and gives the action as the second parameter. The hook for {
'plugins_api_args'} must ensure that an object is returned.
The second filter, {
See also
'plugins_api'}, allows a plugin to override the WordPress.org Plugin Install API entirely. If $action is 'query_plugins' or 'plugin_information', an object MUST be passed. If $action is 'hot_tags` or 'hot_categories', an array MUST be passed.
Finally, the third filter, {
See also
'plugins_api_result'}, makes it possible to filter the response object or array, depending on the $action type.
Supported arguments per action:
Argument Name query_plugins plugin_information hot_tags hot_categories
$slug No Yes No No
$per_page Yes No No No
$page Yes No No No
$number No No Yes Yes
$search Yes No No No
$tag Yes No No No
$author Yes No No No
$user Yes No No No
$browse Yes No No No
$locale Yes Yes No No
$installed_plugins Yes No No No
$is_ssl Yes Yes No No
$fields Yes Yes No No
Since
2.7.0
Parameters
string $action API action to perform: 'query_plugins', 'plugin_information', 'hot_tags' or 'hot_categories'.
array | object $args { Optional. Array or object of arguments to serialize for the Plugin Info API.
string $slug The plugin slug. Default empty. int $per_page Number of plugins per page. Default 24. int $page Number of current page. Default 1. int $number Number of tags or categories to be queried. string $search A search term. Default empty. string $tag Tag to filter plugins. Default empty. string $author Username of an plugin author to filter plugins. Default empty. string $user Username to query for their favorites. Default empty. string $browse Browse view: 'popular', 'new', 'beta', 'recommended'. string $locale Locale to provide context-sensitive results. Default is the value of get_locale(). string $installed_plugins Installed plugins to provide context-sensitive results. bool $is_ssl Whether links should be returned with https or not. Default false. array $fields { Array of fields which should or should not be returned.
bool $short_description Whether to return the plugin short description. Default true. bool $description Whether to return the plugin full description. Default false. bool $sections Whether to return the plugin readme sections: description, installation, FAQ, screenshots, other notes, and changelog. Default false. bool $tested Whether to return the 'Compatible up to' value. Default true. bool $requires Whether to return the required WordPress version. Default true. bool $rating Whether to return the rating in percent and total number of ratings. Default true. bool $ratings Whether to return the number of rating for each star (1-5). Default true. bool $downloaded Whether to return the download count. Default true. bool $downloadlink Whether to return the download link for the package. Default true. bool $last_updated Whether to return the date of the last update. Default true. bool $added Whether to return the date when the plugin was added to the wordpress.org repository. Default true. bool $tags Whether to return the assigned tags. Default true. bool $compatibility Whether to return the WordPress compatibility list. Default true. bool $homepage Whether to return the plugin homepage link. Default true. bool $versions Whether to return the list of all available versions. Default false. bool $donate_link Whether to return the donation link. Default true. bool $reviews Whether to return the plugin reviews. Default false. bool $banners Whether to return the banner images links. Default false. bool $icons Whether to return the icon links. Default false. bool $active_installs Whether to return the number of active installs. Default false. bool $group Whether to return the assigned group. Default false. bool $contributors Whether to return the list of contributors. Default false. } }
Returns
object|array|WP_Error Response object or array on success, WP_Error on failure. See the function reference article for more information on the make-up of possible return values depending on the value of $action.
Filter the WordPress.org Plugin Install API arguments.
Important: An object MUST be returned to this filter.
Since
2.7.0
Parameters
object $args Plugin API arguments.
string $action The type of information being requested from the Plugin Install API.
Filter the response for the current WordPress.org Plugin Install API request.
Passing a non-false value will effectively short-circuit the WordPress.org API request.
If $action is 'query_plugins' or 'plugin_information', an object MUST be passed. If $action is 'hot_tags` or 'hot_categories', an array should be passed.
Since
2.7.0
Parameters
false | object | array $result The result object or array. Default false.
string $action The type of information being requested from the Plugin Install API.
object $args Plugin API arguments.
Filter the Plugin Install API response results.
Since
2.7.0
Parameters
object | WP_Error $res Response object or WP_Error.
string $action The type of information being requested from the Plugin Install API.
object $args Plugin API arguments.
Definition at line 101 of file includes/plugin-install.php.
References $action, $url, __, apply_filters(), elseif, get_locale(), is_wp_error(), maybe_unserialize(), object, set_url_scheme(), WP_DEBUG, wp_http_supports(), wp_remote_post(), and wp_remote_retrieve_body().
Referenced by install_plugin_information(), install_popular_tags(), and WP_Plugin_Install_List_Table\prepare_items().
Variable Documentation
$date_format = __('M j, Y @ H:i')
Definition at line 534 of file includes/plugin-install.php.
exit
Definition at line 668 of file includes/plugin-install.php.
Referenced by GravityView_Ajax\_exit(), _redirect_to_about_wordpress(), WP_Customize_Manager\after_setup_theme(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), delete_plugins(), delete_theme(), GFAutoUpgrade\display_changelog(), GFForms\display_changelog(), do_dismiss_core_update(), do_undismiss_core_update(), get_cli_args(), GravityView_Widget_Search\get_searchable_fields(), GravityView_Admin_Add_Shortcode\get_sortable_fields(), GravityView_Welcome\getting_started_screen(), GFForms\handle_ajax_do_shortcode(), install_theme_information(), GV_License_Handler\license_call(), GFLocking\maybe_lock_object(), maybe_redirect_404(), media_send_to_editor(), media_upload_form_handler(), media_upload_type_form(), IXR_Server\output(), GravityView_Delete_Entry\process_delete(), GFForms\process_exterior_pages(), GFFormDisplay\process_form(), redirect_canonical(), GravityView_Admin_Duplicate_View\save_as_new_view(), GFSelectColumns\select_columns_page(), WP\send_headers(), send_origin_headers(), WP_Importer\set_blog(), WP_List_Table\set_pagination_args(), set_screen_options(), WP_Importer\set_user(), wp_dashboard_setup(), wp_favicon_request(), wp_media_attach_action(), wp_old_slug_redirect(), wp_redirect_admin_locations(), and wpmu_admin_do_redirect().
if (!empty($api->version)) if (!empty($api->author)) if (!empty($api->last_updated)) if (!empty($api->requires)) if (!empty($api->tested)) if (!empty($api->active_installs)) if (!empty($api->slug)&&empty($api->external)) if (!empty($api->homepage)) if (!empty($api->donate_link)&&empty($api->contributors)) if (!empty($api->rating)) if (!empty($api->ratings)&&array_sum((array) $api->ratings) > 0) if (!empty($api->contributors)) if (!empty($api->tested)&&version_compare(substr($GLOBALS['wp_version'], 0, strlen($api->tested)), $api->tested, '>')) elseif (!empty($api->requires)&&version_compare(substr($GLOBALS['wp_version'], 0, strlen($api->requires)), $api->requires, '<')) foreach((array) $api->sections as $section_name=> $content)
Definition at line 514 of file includes/plugin-install.php.
if(!empty($api->download_link)&&(current_user_can('install_plugins')||current_user_can('update_plugins')))
Definition at line 536 of file includes/plugin-install.php.