GravityView: update-core.php File Reference
includes/update-core.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$_old_files
global $_old_files
$_new_bundled_files
global $_new_bundled_files
if(!defined('CORE_UPGRADE_SKIP_NEW_BUNDLED')||CORE_UPGRADE_SKIP_NEW_BUNDLED) update_core ($from, $to)
Upgrade the core of WordPress.
_copy_dir ($from, $to, $skip_list=array())
Copies a directory from one location to another via the WordPress Filesystem Abstraction.
_redirect_to_about_wordpress ($new_version)
Redirect to the About WordPress page after a successful upgrade.
_upgrade_422_remove_genericons ()
Cleans up Genericons example files.
_upgrade_422_find_genericons_files_in_folder ($directory)
Recursively find Genericons example files in a given folder.
_upgrade_440_force_deactivate_incompatible_plugins ()
Function Documentation
_copy_dir ($from, $to, $skip_list = array())
Copies a directory from one location to another via the WordPress Filesystem Abstraction.
Assumes that WP_Filesystem() has already been called and setup.
This is a temporary function for the 3.1 -> 3.2 upgrade, as well as for those upgrading to 3.7+
Since
3.2.0
3.7.0 Updated not to use a regular expression for the skip list
See also
copy_dir()
WP_Filesystem_Base $wp_filesystem
Parameters
string $from source directory
string $to destination directory
array $skip_list a list of files/folders to skip copying
Returns
mixed WP_Error on failure, True on success.
Definition at line 1145 of file includes/update-core.php.
References $from, __, elseif, is_wp_error(), and trailingslashit().
Referenced by update_core().
_redirect_to_about_wordpress ($new_version)
Redirect to the About WordPress page after a successful upgrade.
This function is only needed when the existing install is older than 3.4.0.
Since
3.3.0
string $wp_version string $pagenow string $action
Parameters
string $new_version
Definition at line 1201 of file includes/update-core.php.
References $action, $pagenow, $wp_version, __, ABSPATH, exit, load_default_textdomain(), and show_message().
_upgrade_422_find_genericons_files_in_folder ($directory)
Recursively find Genericons example files in a given folder.
Since
4.2.2
Parameters
string $directory Directory path. Expects trailingslashed.
Returns
array
Definition at line 1287 of file includes/update-core.php.
References $dir, and trailingslashit().
Referenced by _upgrade_422_remove_genericons().
_upgrade_422_remove_genericons ()
Cleans up Genericons example files.
Since
4.2.2
array $wp_theme_directories WP_Filesystem_Base $wp_filesystem
Definition at line 1243 of file includes/update-core.php.
References $file, _upgrade_422_find_genericons_files_in_folder(), and trailingslashit().
Referenced by update_core().
_upgrade_440_force_deactivate_incompatible_plugins ()
Since
4.4.0
Definition at line 1309 of file includes/update-core.php.
References deactivate_plugins(), and REST_API_VERSION.
Referenced by update_core().
if (!defined('CORE_UPGRADE_SKIP_NEW_BUNDLED')||CORE_UPGRADE_SKIP_NEW_BUNDLED) update_core ($from, $to)
Upgrade the core of WordPress.
This will create a .maintenance file at the base of the WordPress directory to ensure that people can not access the web site, when the files are being copied to their locations.
The files in the $_old_files list will be removed and the new files copied from the zip file after the database is upgraded.
The files in the $_new_bundled_files list will be added to the installation if the version is greater than or equal to the old version being upgraded.
The steps for the upgrader for after the new release is downloaded and unzipped is:
Test unzipped location for select files to ensure that unzipped worked.
Create the .maintenance file in current WordPress base.
Copy new WordPress directory over old WordPress files.
Upgrade WordPress to new version. 4.1. Copy all files/folders other than wp-content 4.2. Copy any language files to WP_LANG_DIR (which may differ from WP_CONTENT_DIR 4.3. Copy any new bundled themes/plugins to their respective locations
Delete new WordPress directory path.
Delete .maintenance file.
Remove old files.
Delete 'update_core' option.
There are several areas of failure. For instance if PHP times out before step 6, then you will not be able to access any portion of your site. Also, since the upgrade will not continue where it left off, you will not be able to automatically remove old files and remove the 'update_core' option. This isn't that bad.
If the copy of the new WordPress over the old fails, then the worse is that the new WordPress directory will remain.
If it is assumed that every file will be copied over, including plugins and themes, then if you edit the default theme, you should rename it, so that your changes remain.
Since
2.7.0
WP_Filesystem_Base $wp_filesystem array $_old_files array $_new_bundled_files wpdb $wpdb string $wp_version string $required_php_version string $required_mysql_version
Parameters
string $from New release unzipped path.
string $to Path to old WordPress installation.
Returns
WP_Error|null WP_Error on failure, null on success.
Filter feedback messages displayed during the core update process.
The filter is first evaluated after the zip file for the latest version has been downloaded and unzipped. It is evaluated five more times during the process:
Before WordPress begins the core upgrade process.
Before Maintenance Mode is enabled.
Before WordPress begins copying over the necessary files.
Before Maintenance Mode is disabled.
Before the database is upgraded.
Since
2.5.0
Parameters
string $feedback The core update feedback messages.
Import $wp_version, $required_php_version, and $required_mysql_version from the new version $wp_filesystem->wp_content_dir() returned unslashed pre-2.8
string $wp_version string $required_php_version string $required_mysql_version
This filter is documented in wp-admin/includes/update-core.php
This filter is documented in wp-admin/includes/update-core.php
This filter is documented in wp-admin/includes/update-core.php
This filter is documented in wp-admin/includes/update-core.php
This filter is documented in wp-admin/includes/update-core.php
Fires after WordPress core has been successfully updated.
Since
3.3.0
Parameters
string $wp_version The current WordPress version.
Definition at line 799 of file includes/update-core.php.
References $_new_bundled_files, $_old_files, $file, $from, $mysql_compat, $mysql_version, $php_compat, $php_version, $required_mysql_version, $required_php_version, $wp_version, $wpdb, __, _copy_dir(), _upgrade_422_remove_genericons(), _upgrade_440_force_deactivate_incompatible_plugins(), ABSPATH, WP_Error\add(), admin_url(), apply_filters(), copy_dir(), delete_option(), delete_site_option(), delete_site_transient(), do_action(), elseif, get_core_checksums(), is_wp_error(), str_replace, trailingslashit(), wp_cache_delete(), wp_cache_flush(), WP_CONTENT_DIR, wp_remote_post(), and WPINC.
Referenced by Core_Upgrader\upgrade().
Variable Documentation
$_new_bundled_files
Initial value:
= array(
    'plugins/akismet/'       => '2.0',
    'themes/twentyten/'      => '3.0',
    'themes/twentyeleven/'   => '3.2',
    'themes/twentytwelve/'   => '3.5',
    'themes/twentythirteen/' => '3.6',
    'themes/twentyfourteen/' => '3.8',
    'themes/twentyfifteen/'  => '4.1',
    'themes/twentysixteen/'  => '4.4',
)
Definition at line 727 of file includes/update-core.php.
Referenced by update_core().
$_old_files
Definition at line 18 of file includes/update-core.php.
Referenced by update_core().