GravityView: import.php File Reference
includes/import.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_usort_by_first_member ($a, $b)
Sorts a multidimensional array by first member of each top level member.
get_importers ()
Retrieve list of importers.
register_importer ($id, $name, $description, $callback)
Register importer for WordPress.
wp_get_popular_importers ()
Returns a list from WordPress.org of popular importer plugins.
wp_import_cleanup ($id)
Cleanup importer.
wp_import_handle_upload ()
Handle importer uploading and add attachment.
Function Documentation
_usort_by_first_member ($a, $b)
Sorts a multidimensional array by first member of each top level member.
Used by uasort() as a callback, should not be used directly.
Since
2.9.0 private
Parameters
array $a
array $b
Returns
int
Definition at line 37 of file includes/import.php.
get_importers ()
Retrieve list of importers.
Since
2.0.0
array $wp_importers
Returns
array
Definition at line 17 of file includes/import.php.
References $wp_importers.
register_importer ($id, $name, $description, $callback)
Register importer for WordPress.
Since
2.0.0
array $wp_importers
Parameters
string $id Importer tag. Used to uniquely identify importer.
string $name Importer name and title.
string $description Importer description.
callable $callback Callback to run.
Returns
WP_Error Returns WP_Error when $callback is WP_Error.
Definition at line 54 of file includes/import.php.
References $description, $id, $name, $wp_importers, and is_wp_error().
wp_get_popular_importers ()
Returns a list from WordPress.org of popular importer plugins.
Since
3.5.0
Returns
array Importers with metadata for each.
Definition at line 125 of file includes/import.php.
References $locale, $options, $popular_importers, $url, $wp_version, __, ABSPATH, add_query_arg(), get_locale(), get_site_transient(), home_url(), set_site_transient(), translate(), wp_remote_get(), wp_remote_retrieve_body(), and WPINC.
wp_import_cleanup ($id)
Cleanup importer.
Removes attachment based on ID.
Since
2.0.0
Parameters
string $id Importer ID.
Definition at line 70 of file includes/import.php.
References $id, and wp_delete_attachment().
wp_import_handle_upload ()
Handle importer uploading and add attachment.
Since
2.0.0
Returns
array Uploaded file's details on success, error message on failure
Definition at line 81 of file includes/import.php.
References $id, __, wp_handle_upload(), wp_insert_attachment(), and wp_schedule_single_event().