GravityView: network.php File Reference
includes/network.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
allow_subdirectory_install ()
Allow subdirectory install.
allow_subdomain_install ()
Allow subdomain install.
get_clean_basedomain ()
Get base domain of network.
network_domain_check ()
Check for an existing network.
network_step1 ($errors=false)
Prints step 1 for Network installation process.
network_step2 ($errors=false)
Prints step 2 for Network installation process.
Function Documentation
allow_subdirectory_install ()
Allow subdirectory install.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Returns
bool Whether subdirectory install is allowed
Filter whether to enable the subdirectory install feature in Multisite.
Since
3.0.0
Parameters
bool $allow Whether to enable the subdirectory install feature in Multisite. Default is false.
Definition at line 52 of file includes/network.php.
References $post, $wpdb, and apply_filters().
Referenced by network_step1(), and network_step2().
allow_subdomain_install ()
Allow subdomain install.
Since
3.0.0
Returns
bool Whether subdomain install is allowed
Definition at line 35 of file includes/network.php.
References get_option().
Referenced by network_step1(), and network_step2().
get_clean_basedomain ()
Get base domain of network.
Since
3.0.0
Returns
string Base domain.
Definition at line 80 of file includes/network.php.
References get_option(), and network_domain_check().
Referenced by network_step1(), and network_step2().
network_domain_check ()
Check for an existing network.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Returns
Whether a network exists.
Definition at line 19 of file includes/network.php.
References $wpdb.
Referenced by get_clean_basedomain().
network_step1 ($errors = false)
Prints step 1 for Network installation process.
Since
3.0.0
bool $is_apache
Parameters
WP_Error $errors
Definition at line 101 of file includes/network.php.
References $errors, $is_apache, __, _e, _x, ABSPATH, admin_url(), allow_subdirectory_install(), allow_subdomain_install(), apache_mod_loaded(), checked(), elseif, endif, esc_html_e, esc_url, get_clean_basedomain(), get_option(), got_mod_rewrite(), input, is_wp_error(), label, name, size, submit_button(), WP_CONTENT_DIR, and wp_nonce_field().
network_step2 ($errors = false)
Prints step 2 for Network installation process.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
WP_Error $errors
Definition at line 326 of file includes/network.php.
References $_SERVER, $errors, $home_path, $wpdb, __, _e, ABSPATH, allow_subdirectory_install(), allow_subdomain_install(), elseif, endif, esc_html_e, esc_textarea(), get_clean_basedomain(), get_home_path(), get_option(), get_site_option(), iis7_supports_permalinks(), is_multisite(), is_subdomain_install(), is_wp_error(), L, li, n, str_replace, textarea, trailingslashit(), WP_CONTENT_DIR, wp_remote_get(), wp_remote_retrieve_body(), and WPINC.