GravityView: theme-install.php File Reference
includes/theme-install.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
display_theme ($theme)
Prints a theme on the Install Themes pages.
display_themes ()
Display theme content based on theme list.
install_theme_information ()
Display theme information in dialog box form.
install_theme_search_form ($type_selector=true)
Display search form for searching themes.
install_themes_dashboard ()
Display tags filter for themes.
install_themes_feature_list ()
Retrieve list of WordPress theme features (aka theme tags)
install_themes_upload ()
Variables
$theme_field_defaults
$themes_allowedtags
Function Documentation
display_theme ($theme)
Prints a theme on the Install Themes pages.
WP_Theme_Install_List_Table $wp_list_table
Parameters
object $theme
Definition at line 162 of file includes/theme-install.php.
References $theme, $wp_list_table, _deprecated_function(), and _get_list_table().
display_themes ()
Display theme content based on theme list.
Since
2.8.0
WP_Theme_Install_List_Table $wp_list_table
Definition at line 179 of file includes/theme-install.php.
References $wp_list_table, and _get_list_table().
install_theme_information ()
Display theme information in dialog box form.
Since
2.8.0
WP_Theme_Install_List_Table $wp_list_table
Definition at line 197 of file includes/theme-install.php.
References $theme, $wp_list_table, __, _get_list_table(), exit, iframe_footer(), iframe_header(), is_wp_error(), themes_api(), wp_die(), and wp_unslash().
install_theme_search_form ($type_selector = true)
Display search form for searching themes.
Since
2.8.0
Parameters
bool $type_selector
Definition at line 56 of file includes/theme-install.php.
References __, _e, _ex(), endif, input, label, name, selected(), size, submit_button(), and wp_unslash().
Referenced by install_themes_dashboard().
install_themes_dashboard ()
Display tags filter for themes.
Since
2.8.0
Definition at line 98 of file includes/theme-install.php.
References $feature_list, __, _e, esc_attr(), esc_html, get_theme_feature_list(), input, install_theme_search_form(), label, li, name, and submit_button().
install_themes_feature_list ()
Retrieve list of WordPress theme features (aka theme tags)
Since
2.8.0
Returns
array
Definition at line 31 of file includes/theme-install.php.
References $feature_list, _deprecated_function(), get_transient(), is_wp_error(), set_transient(), and themes_api().
install_themes_upload ()
Since
2.8.0
Definition at line 141 of file includes/theme-install.php.
References __, _e, input, label, name, submit_button(), and wp_nonce_field().
Variable Documentation
$theme_field_defaults
Initial value:
= array('description' => true, 'sections' => false, 'tested' => true, 'requires' => true,
    'rating' => true, 'downloaded' => true, 'downloadlink' => true, 'last_updated' => true, 'homepage' => true,
    'tags' => true, 'num_ratings' => true
)
Definition at line 17 of file includes/theme-install.php.
Referenced by WP_Theme_Install_List_Table\prepare_items(), and wp_ajax_query_themes().
$themes_allowedtags
Initial value:
= array('a' => array('href' => array(), 'title' => array(), 'target' => array()),
    'abbr' => array('title' => array()), 'acronym' => array('title' => array()),
    'code' => array(), 'pre' => array(), 'em' => array(), 'strong' => array(),
    'div' => array(), 'p' => array(), 'ul' => array(), 'ol' => array(), 'li' => array(),
    'h1' => array(), 'h2' => array(), 'h3' => array(), 'h4' => array(), 'h5' => array(), 'h6' => array(),
    'img' => array('src' => array(), 'class' => array(), 'alt' => array())
)
Definition at line 9 of file includes/theme-install.php.
Referenced by WP_Theme_Install_List_Table\install_theme_info(), WP_Theme_Install_List_Table\single_row(), and wp_ajax_query_themes().