GravityView: credits.php File Reference
includes/credits.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_credits_add_profile_link (&$display_name, $username, $profiles)
Retrieve the link to a contributor's WordPress.org profile page.
_wp_credits_build_object_link (&$data)
Retrieve the link to an external library used in WordPress.
wp_credits ()
Retrieve the contributor credits.
Function Documentation
_wp_credits_add_profile_link (& $display_name, $username, $profiles)
Retrieve the link to a contributor's WordPress.org profile page.
private
Since
3.2.0
Parameters
string $display_name The contributor's display name, passed by reference.
string $username The contributor's username.
string $profiles URL to the contributor's WordPress.org profile page.
Definition at line 55 of file includes/credits.php.
References esc_html, and esc_url.
_wp_credits_build_object_link (& $data)
Retrieve the link to an external library used in WordPress.
private
Since
3.2.0
Parameters
string $data External library data, passed by reference.
Definition at line 67 of file includes/credits.php.
References esc_html, and esc_url.
wp_credits ()
Retrieve the contributor credits.
string $wp_version The current WordPress version.
Since
3.2.0
Returns
array|false A list of all of the contributors, or false on error.
Definition at line 19 of file includes/credits.php.
References $locale, $wp_version, get_locale(), get_site_transient(), is_wp_error(), set_site_transient(), wp_remote_get(), wp_remote_retrieve_body(), and wp_remote_retrieve_response_code().