GravityView: menu.php File Reference
includes/menu.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
add_cssclass ($add, $class)
add_menu_classes ($menu)
Variables
$_wp_menu_nopriv = array()
$_wp_submenu_nopriv = array()
$last_menu_key = array_keys($menu)
if(!user_can_access_admin_page()) $menu = add_menu_classes($menu)
if(apply_filters('custom_menu_order', false)) $prev_menu_was_separator = false
Filter whether to enable custom ordering of the administration menu.
if(is_network_admin()) elseif(is_user_admin()) else
Function Documentation
add_cssclass ($add, $class)
Parameters
string $add
string $class
Returns
string
Definition at line 187 of file includes/menu.php.
References $class.
Referenced by add_menu_classes().
add_menu_classes ($menu)
Parameters
array $menu
Returns
array
Filter administration menus array with classes added for top-level items.
Since
2.7.0
Parameters
array $menu Associative array of administration menu items.
Filter the order of administration menu items.
A truthy value must first be passed to the {
See also
'custom_menu_order'} filter for this filter to work. Use the following to enable custom menu ordering:
add_filter('custom_menu_order', '__return_true');
Since
2.8.0
Parameters
array $menu_order An ordered array of menu items.
array $menu_order array $default_menu_order
Parameters
array $a
array $b
Returns
int
Fires when access to an admin page is denied.
Since
2.5.0
Definition at line 197 of file includes/menu.php.
References $i, $menu, add_cssclass(), and apply_filters().
Variable Documentation
$_wp_menu_nopriv = array()
Definition at line 72 of file includes/menu.php.
Referenced by get_admin_page_parent(), and user_can_access_admin_page().
$_wp_submenu_nopriv = array()
Definition at line 71 of file includes/menu.php.
Referenced by add_submenu_page(), get_admin_page_parent(), and user_can_access_admin_page().
$last_menu_key = array_keys($menu)
Definition at line 327 of file includes/menu.php.
if (!user_can_access_admin_page()) $menu = add_menu_classes($menu)
Definition at line 345 of file includes/menu.php.
Referenced by add_menu_classes(), add_menu_page(), add_submenu_page(), WP_Customize_Nav_Menus\customize_register(), export_wp(), WP_Customize_Nav_Menu_Setting\filter_nav_menu_options(), WP_Customize_Nav_Menu_Item_Setting\filter_wp_get_nav_menu_items(), WP_Customize_Nav_Menu_Setting\filter_wp_get_nav_menus(), WP_Nav_Menu_Widget\form(), get_admin_page_parent(), get_admin_page_title(), is_nav_menu(), remove_menu_page(), user_can_access_admin_page(), wp_delete_nav_menu(), wp_get_nav_menu_items(), wp_get_nav_menu_object(), wp_get_nav_menu_to_edit(), wp_nav_menu(), wp_page_menu(), and wp_update_nav_menu_item().
if (apply_filters('custom_menu_order', false)) $prev_menu_was_separator = false
Filter whether to enable custom ordering of the administration menu.
See the {
See also
'menu_order'} filter for reordering menu items.
Since
2.8.0
Parameters
bool $custom Whether custom ordering is enabled. Default false.
Definition at line 307 of file includes/menu.php.
if (is_network_admin()) elseif (is_user_admin()) else
Initial value:
{
    do_action( '_admin_menu' )
Definition at line 31 of file includes/menu.php.