GravityView: js.php File Reference
js.php File Reference
Functions
CreateDefaultValuesUI (field)
CreateInputNames (field)
CreatePlaceholdersUI (field)
HideSettings (element_id)
InitializeFormConditionalLogic ()
InitPaginationOptions (isInit)
SaveCustomChoices ()
ShowSettings (element_id)
TogglePostCategoryInitialItem (isInit)
Variables
if (!class_exists('GFForms'))
Function Documentation
CreateDefaultValuesUI (field)
Definition at line 192 of file js.php.
References esc_html__().
CreateInputNames (field)
Definition at line 162 of file js.php.
References esc_html__(), and null.
CreatePlaceholdersUI (field)
Allows for modification for the middle name input for the Name Field in a form
Parameters
int The ID for the field string The Label for the input
Definition at line 216 of file js.php.
References __, _x, checked(), do_action(), esc_html__(), fields, get_option(), input, label, li, margin, month, null, page, pages, password, placeholder, selected(), size, type, and wp_print_scripts().
HideSettings (element_id)
Definition at line 140 of file js.php.
InitializeFormConditionalLogic ()
Definition at line 59 of file js.php.
References esc_html__().
InitPaginationOptions (isInit)
Definition at line 71 of file js.php.
References esc_html__(), and pages.
SaveCustomChoices ()
Definition at line 29 of file js.php.
References esc_html__(), and name.
ShowSettings (element_id)
Definition at line 135 of file js.php.
TogglePostCategoryInitialItem (isInit)
Definition at line 145 of file js.php.
References esc_html__().
Variable Documentation
if(!class_exists('GFForms'))
Definition at line 2 of file js.php.