GravityView: kses.php File Reference
kses.php File Reference
Namespaces
External
kses 0.2.2 - HTML/XHTML filter that only allows some elements and attributes Copyright (C) 2002, 2003, 2005 Ulf Harnhammar
Functions
_wp_add_global_attributes ($value)
Helper function to add global attributes to a tag in the allowed html list.
_wp_kses_decode_entities_chr ($match)
Regex callback for wp_kses_decode_entities()
_wp_kses_decode_entities_chr_hexdec ($match)
Regex callback for wp_kses_decode_entities()
_wp_kses_split_callback ($match)
Callback for wp_kses_split.
kses_init ()
Sets up most of the Kses filters for input form content.
kses_init_filters ()
Adds all Kses input form content filters.
kses_remove_filters ()
Removes all Kses input form content filters.
safecss_filter_attr ($css, $deprecated= '')
Inline CSS filter.
valid_unicode ($i)
Helper function to determine if a Unicode value is valid.
wp_filter_kses ($data)
Sanitize content with allowed HTML Kses rules.
wp_filter_nohtml_kses ($data)
Strips all of the HTML in the content.
wp_filter_post_kses ($data)
Sanitize content for allowed HTML tags for post content.
wp_kses ($string, $allowed_html, $allowed_protocols=array())
Filters content and keeps only allowable HTML elements.
wp_kses_allowed_html ($context= '')
Return a list of allowed tags and attributes for a given context.
wp_kses_array_lc ($inarray)
Goes through an array and changes the keys to all lower case.
wp_kses_attr ($element, $attr, $allowed_html, $allowed_protocols)
Removes all attributes, if none are allowed for this element.
wp_kses_attr_check (&$name, &$value, &$whole, $vless, $element, $allowed_html)
Determine whether an attribute is allowed.
wp_kses_attr_parse ($element)
Finds all attributes of an HTML element.
wp_kses_bad_protocol ($string, $allowed_protocols)
Sanitize string from bad protocols.
wp_kses_bad_protocol_once ($string, $allowed_protocols, $count=1)
Sanitizes content from bad protocols and other characters.
wp_kses_bad_protocol_once2 ($string, $allowed_protocols)
Callback for wp_kses_bad_protocol_once() regular expression.
wp_kses_check_attr_val ($value, $vless, $checkname, $checkvalue)
Performs different checks for attribute values.
wp_kses_data ($data)
Sanitize content with allowed HTML Kses rules.
wp_kses_decode_entities ($string)
Convert all entities to their character counterparts.
wp_kses_hair ($attr, $allowed_protocols)
Builds an attribute list from string containing attributes.
wp_kses_hair_parse ($attr)
Builds an attribute list from string containing attributes.
wp_kses_hook ($string, $allowed_html, $allowed_protocols)
You add any kses hooks here.
wp_kses_html_error ($string)
Handles parsing errors in wp_kses_hair().
wp_kses_js_entities ($string)
Removes the HTML JavaScript entities found in early versions of Netscape 4.
wp_kses_named_entities ($matches)
Callback for wp_kses_normalize_entities() regular expression.
wp_kses_no_null ($string, $options=null)
Removes any invalid control characters in $string.
wp_kses_normalize_entities ($string)
Converts and fixes HTML entities.
wp_kses_normalize_entities2 ($matches)
Callback for wp_kses_normalize_entities() regular expression.
wp_kses_normalize_entities3 ($matches)
Callback for wp_kses_normalize_entities() for regular expression.
wp_kses_one_attr ($string, $element)
Filters one attribute only and ensures its value is allowed.
wp_kses_post ($data)
Sanitize content for allowed HTML tags for post content.
wp_kses_split ($string, $allowed_html, $allowed_protocols)
Searches for HTML tags, no matter how malformed.
wp_kses_split2 ($string, $allowed_html, $allowed_protocols)
Callback for wp_kses_split for fixing malformed HTML tags.
wp_kses_stripslashes ($string)
Strips slashes from in front of quotes.
wp_kses_version ()
This function returns kses' version number.
Variables
global $allowedentitynames
global $allowedposttags = wp_kses_array_lc($allowedposttags)
global $allowedtags
if(!CUSTOM_TAGS) else
if(!defined('CUSTOM_TAGS')) define('CUSTOM_TAGS' false
You can override this in a plugin.
Function Documentation
_wp_add_global_attributes ($value)
Helper function to add global attributes to a tag in the allowed html list.
Since
3.5.0 private
Parameters
array $value An array of attributes.
Returns
array The array of attributes with global attributes added.
Definition at line 1745 of file kses.php.
References $value.
_wp_kses_decode_entities_chr ($match)
Regex callback for wp_kses_decode_entities()
Parameters
array $match preg match
Returns
string
Definition at line 1516 of file kses.php.
_wp_kses_decode_entities_chr_hexdec ($match)
Regex callback for wp_kses_decode_entities()
Parameters
array $match preg match
Returns
string
Definition at line 1526 of file kses.php.
_wp_kses_split_callback ($match)
Callback for wp_kses_split.
Since
3.1.0 private
array $pass_allowed_html array $pass_allowed_protocols
Returns
string
Definition at line 737 of file kses.php.
References wp_kses_split2().
kses_init ()
Sets up most of the Kses filters for input form content.
If you remove the kses_init() function from 'init' hook and 'set_current_user' (priority is default), then none of the Kses filter hooks will be added.
First removes all of the Kses filters in case the current user does not need to have Kses filter the content. If the user does not have unfiltered_html capability, then Kses filters are added.
Since
2.0.0
Definition at line 1662 of file kses.php.
References current_user_can(), kses_init_filters(), and kses_remove_filters().
kses_init_filters ()
Adds all Kses input form content filters.
All hooks have default priority. The wp_filter_kses() function is added to the 'pre_comment_content' and 'title_save_pre' hooks.
The wp_filter_post_kses() function is added to the 'content_save_pre', 'excerpt_save_pre', and 'content_filtered_save_pre' hooks.
Since
2.0.0
Definition at line 1607 of file kses.php.
References add_filter(), and current_user_can().
Referenced by kses_init(), wp_ajax_replyto_comment(), and wp_handle_comment_submission().
kses_remove_filters ()
Removes all Kses input form content filters.
A quick procedural method to removing all of the filters that kses uses for content in WordPress Loop.
Does not remove the kses_init() function from 'init' hook (priority is default). Also does not remove kses_init() function from 'set_current_user' hook (priority is also default).
Since
2.0.6
Definition at line 1635 of file kses.php.
References remove_filter().
Referenced by kses_init(), wp_ajax_replyto_comment(), and wp_handle_comment_submission().
safecss_filter_attr ($css, $deprecated = '')
Inline CSS filter.
Since
2.8.1
Parameters
string $css A string of CSS rules.
string $deprecated Not used.
Returns
string Filtered string of CSS rules.
Filter list of allowed CSS attributes.
Since
2.8.1
Parameters
array $attr List of allowed CSS attributes.
Definition at line 1679 of file kses.php.
References $deprecated, _deprecated_argument(), apply_filters(), str_replace, and wp_kses_no_null().
Referenced by wp_kses_attr_check().
valid_unicode ($i)
Helper function to determine if a Unicode value is valid.
Parameters
int $i Unicode value
Returns
bool True if the value was a valid Unicode number
Definition at line 1484 of file kses.php.
References $i.
Referenced by wp_kses_normalize_entities2(), and wp_kses_normalize_entities3().
wp_filter_kses ($data)
Sanitize content with allowed HTML Kses rules.
Since
1.0.0
Parameters
string $data Content to filter, expected to be escaped with slashes
Returns
string Filtered content
Definition at line 1538 of file kses.php.
References current_filter(), and wp_kses().
wp_filter_nohtml_kses ($data)
Strips all of the HTML in the content.
Since
2.1.0
Parameters
string $data Content to strip all HTML from
Returns
string Filtered content without any HTML
Definition at line 1592 of file kses.php.
References wp_kses().
wp_filter_post_kses ($data)
Sanitize content for allowed HTML tags for post content.
Post content refers to the page contents of the 'post' type and not $_POST data from forms.
Since
2.0.0
Parameters
string $data Post content to filter, expected to be escaped with slashes
Returns
string Filtered post content with allowed HTML tags and attributes intact.
Definition at line 1565 of file kses.php.
References wp_kses().
Referenced by edit_post().
wp_kses ($string, $allowed_html, $allowed_protocols = array())
Filters content and keeps only allowable HTML elements.
This function makes sure that only the allowed HTML element names, attribute names and attribute values plus only sane HTML entities will occur in $string. You have to remove any slashes from PHP's magic quotes before you call this function.
The default allowed protocols are 'http', 'https', 'ftp', 'mailto', 'news', 'irc', 'gopher', 'nntp', 'feed', 'telnet, 'mms', 'rtsp' and 'svn'. This covers all common link protocols, except for 'javascript' which should not be allowed for untrusted users.
Since
1.0.0
Parameters
string $string Content to filter through kses
array $allowed_html List of allowed HTML elements
array $allowed_protocols Optional. Allowed protocol in links.
Returns
string Filtered content with only allowed HTML elements
Definition at line 525 of file kses.php.
References wp_allowed_protocols(), wp_kses_hook(), wp_kses_js_entities(), wp_kses_no_null(), wp_kses_normalize_entities(), and wp_kses_split().
Referenced by _get_plugin_data_markup_translate(), GFFormsModel\choice_value_match(), WP_Plugin_Install_List_Table\display_rows(), GFFormDisplay\failed_state_validation(), Automatic_Upgrader_Skin\feedback(), WP_Press_This\fetch_source_html(), img_caption_shortcode(), install_plugin_information(), WP_Theme_Install_List_Table\install_theme_info(), GF_Field_Checkbox\is_checkbox_checked(), WP_Theme\sanitize_header(), GF_Field_Page\sanitize_settings(), GF_Field_HTML\sanitize_settings(), GF_Field\sanitize_settings(), GFFormsModel\sanitize_settings(), GF_Field\sanitize_settings_choices(), WP_Theme_Install_List_Table\single_row(), wp_ajax_query_themes(), wp_filter_kses(), wp_filter_nohtml_kses(), wp_filter_oembed_result(), wp_filter_post_kses(), wp_kses_data(), wp_kses_post(), wp_kses_split2(), and wp_plugin_update_row().
wp_kses_allowed_html ($context = '')
Return a list of allowed tags and attributes for a given context.
Since
3.5.0
array $allowedposttags array $allowedtags array $allowedentitynames
Parameters
string $context The context for which to retrieve tags. Allowed values are post, strip, data,entities, or the name of a field filter such as pre_user_description.
Returns
array List of allowed tags and their allowed attributes.
Filter HTML elements allowed for a given context.
Since
3.5.0
Parameters
string $tags Allowed tags, attributes, and/or entities.
string $context Context to judge allowed tags by. Allowed values are 'post', 'data', 'strip', 'entities', 'explicit', or the name of a filter.
This filter is documented in wp-includes/kses.php
This filter is documented in wp-includes/kses.php
This filter is documented in wp-includes/kses.php
This filter is documented in wp-includes/kses.php
This filter is documented in wp-includes/kses.php
Definition at line 624 of file kses.php.
References $allowedentitynames, $allowedposttags, $allowedtags, $tags, and apply_filters().
Referenced by GFFormsModel\choice_value_match(), GFFormDisplay\failed_state_validation(), gallery_shortcode(), GF_Field_Checkbox\is_checkbox_checked(), GF_Field_Page\sanitize_settings(), GF_Field_HTML\sanitize_settings(), GF_Field\sanitize_settings(), GFFormsModel\sanitize_settings(), GF_Field\sanitize_settings_choices(), wp_kses_attr(), wp_kses_one_attr(), and wp_kses_split2().
wp_kses_array_lc ($inarray)
Goes through an array and changes the keys to all lower case.
Since
1.0.0
Parameters
array $inarray Unfiltered array
Returns
array Fixed array with all lowercase keys
Definition at line 1281 of file kses.php.
wp_kses_attr ($element, $attr, $allowed_html, $allowed_protocols)
Removes all attributes, if none are allowed for this element.
If some are allowed it calls wp_kses_hair() to split them further, and then it builds up new HTML code from the data that kses_hair() returns. It also removes "<" and ">" characters, if there are any left. One more thing it does is to check if the tag has a closing XHTML slash, and if it does, it puts one in the returned code as well.
Since
1.0.0
Parameters
string $element HTML element/tag
string $attr HTML attributes from HTML element to closing HTML element tag
array $allowed_html Allowed HTML elements
array $allowed_protocols Allowed protocols to keep
Returns
string Sanitized HTML element
Definition at line 822 of file kses.php.
References wp_kses_allowed_html(), wp_kses_attr_check(), and wp_kses_hair().
Referenced by wp_kses_split2().
wp_kses_attr_check (& $name, & $value, & $whole, $vless, $element, $allowed_html)
Determine whether an attribute is allowed.
Since
4.2.3
Parameters
string $name The attribute name. Returns empty string when not allowed.
string $value The attribute value. Returns a filtered value.
string $whole The name=value input. Returns filtered input.
string $vless 'y' when attribute like "enabled", otherwise 'n'.
string $element The name of the element to which this attribute belongs.
array $allowed_html The full list of allowed elements and attributes.
Returns
bool Is the attribute allowed?
Definition at line 866 of file kses.php.
References $name, $value, safecss_filter_attr(), str_replace, and wp_kses_check_attr_val().
Referenced by wp_kses_attr(), and wp_kses_one_attr().
wp_kses_attr_parse ($element)
Finds all attributes of an HTML element.
Does not modify input. May return "evil" output.
Based on wp_kses_split2() and wp_kses_attr()
Since
4.2.3
Parameters
string $element HTML element/tag
Returns
array|bool List of attributes found in $element. Returns false on failure.
Definition at line 1041 of file kses.php.
References wp_kses_hair_parse().
Referenced by do_shortcodes_in_html_tags().
wp_kses_bad_protocol ($string, $allowed_protocols)
Sanitize string from bad protocols.
This function removes all non-allowed protocols from the beginning of $string. It ignores whitespace and the case of the letters, and it does understand HTML entities. It does its work in a while loop, so it won't be fooled by a string like "javascript:javascript:alert(57)".
Since
1.0.0
Parameters
string $string Content to filter bad protocols from
array $allowed_protocols Allowed protocols to keep
Returns
string Filtered content
Definition at line 1218 of file kses.php.
References wp_kses_bad_protocol_once(), and wp_kses_no_null().
Referenced by esc_url(), WP_Http\request(), wp_http_validate_url(), wp_kses_hair(), and wp_kses_one_attr().
wp_kses_bad_protocol_once ($string, $allowed_protocols, $count = 1)
Sanitizes content from bad protocols and other characters.
This function searches for URL protocols at the beginning of $string, while handling whitespace and HTML entities.
Since
1.0.0
Parameters
string $string Content to check for bad protocols
string $allowed_protocols Allowed protocols
Returns
string Sanitized content
Definition at line 1336 of file kses.php.
References $count, and wp_kses_bad_protocol_once2().
Referenced by wp_kses_bad_protocol().
wp_kses_bad_protocol_once2 ($string, $allowed_protocols)
Callback for wp_kses_bad_protocol_once() regular expression.
This function processes URL protocols, checks to see if they're in the whitelist or not, and returns different data depending on the answer.
private
Since
1.0.0
Parameters
string $string URI scheme to check against the whitelist
string $allowed_protocols Allowed protocols
Returns
string Sanitized content
Definition at line 1367 of file kses.php.
References wp_kses_decode_entities(), and wp_kses_no_null().
Referenced by wp_kses_bad_protocol_once().
wp_kses_check_attr_val ($value, $vless, $checkname, $checkvalue)
Performs different checks for attribute values.
The currently implemented checks are "maxlen", "minlen", "maxval", "minval" and "valueless".
Since
1.0.0
Parameters
string $value Attribute value
string $vless Whether the value is valueless. Use 'y' or 'n'
string $checkname What $checkvalue is checking for.
mixed $checkvalue What constraint the value should pass
Returns
bool Whether check passes
Definition at line 1146 of file kses.php.
References $value.
Referenced by wp_kses_attr_check().
wp_kses_data ($data)
Sanitize content with allowed HTML Kses rules.
Since
2.9.0
Parameters
string $data Content to filter, expected to not be escaped
Returns
string Filtered content
Definition at line 1550 of file kses.php.
References current_filter(), and wp_kses().
Referenced by sanitize_option().
wp_kses_decode_entities ($string)
Convert all entities to their character counterparts.
This function decodes numeric HTML entities (&#65; and &#x41;). It doesn't do anything with other entities like ä, but we don't need them in the URL protocol whitelisting system anyway.
Since
1.0.0
Parameters
string $string Content to change entities
Returns
string Content after decoded entities
Definition at line 1503 of file kses.php.
Referenced by wp_kses_bad_protocol_once2().
wp_kses_hair ($attr, $allowed_protocols)
Builds an attribute list from string containing attributes.
This function does a lot of work. It parses an attribute list into an array with attribute data, and tries to do the right thing even if it gets weird input. It will add quotes around attribute values that don't have any quotes or apostrophes around them, to make it easier to produce HTML code that will conform to W3C's HTML specification. It will also remove bad URL protocols from attribute values. It also reduces duplicate attributes by using the attribute defined first (foo='bar' foo='baz' will result in foo='bar').
Since
1.0.0
Parameters
string $attr Attribute list from HTML element to closing HTML element tag
array $allowed_protocols Allowed protocols to keep
Returns
array List of attributes after parsing
Definition at line 917 of file kses.php.
References $mode, wp_kses_bad_protocol(), and wp_kses_html_error().
Referenced by wp_kses_attr().
wp_kses_hair_parse ($attr)
Builds an attribute list from string containing attributes.
Does not modify input. May return "evil" output. In case of unexpected input, returns false instead of stripping things.
Based on wp_kses_hair() but does not return a multi-dimensional array.
Since
4.2.3
Parameters
string $attr Attribute list from HTML element to closing HTML element tag
Returns
array|bool List of attributes found in $attr. Returns false on failure.
Definition at line 1092 of file kses.php.
Referenced by wp_kses_attr_parse().
wp_kses_hook ($string, $allowed_html, $allowed_protocols)
You add any kses hooks here.
There is currently only one kses WordPress hook and it is called here. All parameters are passed to the hooks and expected to receive a string.
Since
1.0.0
Parameters
string $string Content to filter through kses
array $allowed_html List of allowed HTML elements
array $allowed_protocols Allowed protocol in links
Returns
string Filtered content through 'pre_kses' hook
Filter content to be run through kses.
Since
2.3.0
Parameters
string $string Content to run through kses.
array $allowed_html Allowed HTML elements.
array $allowed_protocols Allowed protocol in links.
Definition at line 680 of file kses.php.
References apply_filters().
Referenced by wp_kses().
wp_kses_html_error ($string)
Handles parsing errors in wp_kses_hair().
The general plan is to remove everything to and including some whitespace, but it deals with quotes and apostrophes as well.
Since
1.0.0
Parameters
string $string
Returns
string
Definition at line 1320 of file kses.php.
Referenced by wp_kses_hair().
wp_kses_js_entities ($string)
Removes the HTML JavaScript entities found in early versions of Netscape 4.
Since
1.0.0
Parameters
string $string
Returns
string
Definition at line 1305 of file kses.php.
Referenced by wp_kses(), and wp_kses_one_attr().
wp_kses_named_entities ($matches)
Callback for wp_kses_normalize_entities() regular expression.
This function only accepts valid named entity references, which are finite, case-sensitive, and highly scrutinized by HTML and XML validators.
Since
3.0.0
array $allowedentitynames
Parameters
array $matches preg_replace_callback() matches array
Returns
string Correctly encoded entity
Definition at line 1422 of file kses.php.
References $allowedentitynames, and $i.
wp_kses_no_null ($string, $options = null)
Removes any invalid control characters in $string.
Also removes any instance of the '\0' string.
Since
1.0.0
Parameters
string $string
array $options Set 'slash_zero' => 'keep' when '\0' is allowed. Default is 'remove'.
Returns
string
Definition at line 1244 of file kses.php.
References $options.
Referenced by get_the_content(), safecss_filter_attr(), wp_kses(), wp_kses_bad_protocol(), wp_kses_bad_protocol_once2(), and wp_kses_one_attr().
wp_kses_normalize_entities ($string)
Converts and fixes HTML entities.
This function normalizes HTML entities. It will convert AT&T to the correct AT&T, &#00058; to &#58;, &#XYZZY; to &#XYZZY; and so on.
Since
1.0.0
Parameters
string $string Content to normalize entities
Returns
string Content with normalized entities
Definition at line 1397 of file kses.php.
References str_replace.
Referenced by _wp_specialchars(), esc_url(), and wp_kses().
wp_kses_normalize_entities2 ($matches)
Callback for wp_kses_normalize_entities() regular expression.
This function helps {
See also
wp_kses_normalize_entities()} to only accept 16-bit values and nothing more for &#number; entities.
private
Since
1.0.0
Parameters
array $matches preg_replace_callback() matches array
Returns
string Correctly encoded entity
Definition at line 1444 of file kses.php.
References $i, and valid_unicode().
wp_kses_normalize_entities3 ($matches)
Callback for wp_kses_normalize_entities() for regular expression.
This function helps wp_kses_normalize_entities() to only accept valid Unicode numeric entities in hex form.
private
Parameters
array $matches preg_replace_callback() matches array
Returns
string Correctly encoded entity
Definition at line 1470 of file kses.php.
References valid_unicode().
wp_kses_one_attr ($string, $element)
Filters one attribute only and ensures its value is allowed.
This function has the advantage of being more secure than esc_attr() and can escape data in some situations where wp_kses() must strip the whole attribute.
Since
4.2.3
Parameters
string $string The 'whole' attribute, including name and value.
string $element The element name to which the attribute belongs.
Returns
string Filtered attribute.
Definition at line 547 of file kses.php.
References $name, $value, esc_attr(), wp_allowed_protocols(), wp_kses_allowed_html(), wp_kses_attr_check(), wp_kses_bad_protocol(), wp_kses_js_entities(), and wp_kses_no_null().
Referenced by do_shortcodes_in_html_tags().
wp_kses_post ($data)
Sanitize content for allowed HTML tags for post content.
Post content refers to the page contents of the 'post' type and not $_POST data from forms.
Since
2.9.0
Parameters
string $data Post content to filter
Returns
string Filtered post content with allowed HTML tags and attributes intact.
Definition at line 1580 of file kses.php.
References wp_kses().
Referenced by GF_Field_List\get_value_entry_detail(), WP_SimplePie_Sanitize_KSES\sanitize(), GF_Field\sanitize_entry_value(), WP_Widget_Text\update(), and wp_read_image_metadata().
wp_kses_split ($string, $allowed_html, $allowed_protocols)
Searches for HTML tags, no matter how malformed.
It also matches stray ">" characters.
Since
1.0.0
array $pass_allowed_html array $pass_allowed_protocols
Parameters
string $string Content to filter
array $allowed_html Allowed HTML elements
array $allowed_protocols Allowed protocols to keep
Returns
string Content with fixed HTML tags
Definition at line 719 of file kses.php.
Referenced by wp_kses().
wp_kses_split2 ($string, $allowed_html, $allowed_protocols)
Callback for wp_kses_split for fixing malformed HTML tags.
This function does a lot of work. It rejects some very malformed things like <:::>. It returns an empty string, if the element isn't allowed (look ma, no strip_tags()!). Otherwise it splits the tag into an element and an attribute list.
After the tag is split into an element and an attribute list, it is run through another filter which will remove illegal attributes and once that is completed, will be returned.
private
Since
1.0.0
Parameters
string $string Content to filter
array $allowed_html Allowed HTML elements
array $allowed_protocols Allowed protocols to keep
Returns
string Fixed HTML element
Definition at line 762 of file kses.php.
References str_replace, wp_kses(), wp_kses_allowed_html(), wp_kses_attr(), and wp_kses_stripslashes().
Referenced by _wp_kses_split_callback().
wp_kses_stripslashes ($string)
Strips slashes from in front of quotes.
This function changes the character sequence " to just ". It leaves all other slashes alone. It's really weird, but the quoting from preg_replace(//e) seems to require this.
Since
1.0.0
Parameters
string $string String to strip slashes
Returns
string Fixed string with quoted slashes
Definition at line 1269 of file kses.php.
Referenced by wp_kses_split2().
wp_kses_version ()
This function returns kses' version number.
Since
1.0.0
Returns
string KSES Version Number
Definition at line 700 of file kses.php.
Variable Documentation
global $allowedentitynames
Definition at line 49 of file kses.php.
Referenced by wp_kses_allowed_html(), and wp_kses_named_entities().
$allowedposttags = wp_kses_array_lc($allowedposttags)
Definition at line 49 of file kses.php.
Referenced by wp_kses_allowed_html().
global $allowedtags
Definition at line 49 of file kses.php.
Referenced by allowed_tags(), and wp_kses_allowed_html().
if (!CUSTOM_TAGS) else
Initial value:
{
    $allowedtags = wp_kses_array_lc( $allowedtags )
Definition at line 500 of file kses.php.
if (!defined('CUSTOM_TAGS')) define('CUSTOM_TAGS' false
You can override this in a plugin.
The wp_kses_allowed_html filter is more powerful and supplies context. CUSTOM_TAGS is not recommended and should be considered deprecated.
See also
wp_kses_allowed_html()
Since
1.2.0
Definition at line 44 of file kses.php.