GravityView: l10n.php File Reference
l10n.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
__ ($text, $domain= 'default')
Retrieve the translation of $text.
_e ($text, $domain= 'default')
Display translated text.
_ex ($text, $context, $domain= 'default')
Display translated string with gettext context.
_n ($single, $plural, $number, $domain= 'default')
Translates and retrieves the singular or plural form based on the supplied number.
_n_noop ($singular, $plural, $domain=null)
Registers plural strings in POT file, but don't translate them.
_nx ($single, $plural, $number, $context, $domain= 'default')
Translates and retrieves the singular or plural form based on the supplied number, with gettext context.
_nx_noop ($singular, $plural, $context, $domain=null)
Register plural strings with gettext context in the POT file, but don't translate them.
_x ($text, $context, $domain= 'default')
Retrieve translated string with gettext context.
before_last_bar ($string)
Remove last item on a pipe-delimited string.
esc_attr__ ($text, $domain= 'default')
Retrieve the translation of $text and escapes it for safe use in an attribute.
esc_attr_e ($text, $domain= 'default')
Display translated text that has been escaped for safe use in an attribute.
esc_attr_x ($text, $context, $domain= 'default')
Translate string with gettext context, and escapes it for safe use in an attribute.
esc_html__ ($text, $domain= 'default')
Retrieve the translation of $text and escapes it for safe use in HTML output.
esc_html_e ($text, $domain= 'default')
Display translated text that has been escaped for safe use in HTML output.
esc_html_x ($text, $context, $domain= 'default')
Translate string with gettext context, and escapes it for safe use in HTML output.
get_available_languages ($dir=null)
Get all available languages based on the presence of *.mo files in a given directory.
get_locale ()
Retrieves the current locale.
get_translations_for_domain ($domain)
Return the Translations instance for a text domain.
is_textdomain_loaded ($domain)
Whether there are translations for the text domain.
load_child_theme_textdomain ($domain, $path=false)
Load the child themes translated strings.
load_default_textdomain ($locale=null)
Load default translated strings based on locale.
load_muplugin_textdomain ($domain, $mu_plugin_rel_path= '')
Load the translated strings for a plugin residing in the mu-plugins directory.
load_plugin_textdomain ($domain, $deprecated=false, $plugin_rel_path=false)
Load a plugin's translated strings.
load_textdomain ($domain, $mofile)
Load a .mo file into the text domain $domain.
load_theme_textdomain ($domain, $path=false)
Load the theme's translated strings.
translate ($text, $domain= 'default')
Retrieve the translation of $text.
translate_nooped_plural ($nooped_plural, $count, $domain= 'default')
Translates and retrieves the singular or plural form of a string that's been registered with _n_noop() or _nx_noop().
translate_user_role ($name)
Translates role name.
translate_with_gettext_context ($text, $context, $domain= 'default')
Retrieve the translation of $text in the context defined in $context.
unload_textdomain ($domain)
Unload translations for a text domain.
wp_dropdown_languages ($args=array())
Language selector.
wp_get_installed_translations ($type)
Get installed translations.
wp_get_pomo_file_data ($po_file)
Extract headers from a PO file.
Function Documentation
__ ($text, $domain = 'default')
Retrieve the translation of $text.
If there is no translation, or the text domain isn't loaded, the original text is returned.
Since
2.1.0
Parameters
string $text Text to translate.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated text.
Definition at line 172 of file l10n.php.
References $text, and translate().
_e ($text, $domain = 'default')
Display translated text.
Since
1.2.0
Parameters
string $text Text to translate.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Definition at line 217 of file l10n.php.
References $text, and translate().
_ex ($text, $context, $domain = 'default')
Display translated string with gettext context.
Since
3.0.0
Parameters
string $text Text to translate.
string $context Context information for the translators.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated context string without pipe.
Definition at line 279 of file l10n.php.
References $text, and _x().
Referenced by WP_Customize_Nav_Menu_Control\content_template(), display_setup_form(), WP_Widget_Links\form(), WP_Press_This\html(), WP_Terms_List_Table\inline_edit(), WP_Posts_List_Table\inline_edit(), install_search_form(), install_theme_search_form(), list_meta(), media_upload_form(), meta_form(), post_submit_meta_box(), WP_Customize_Themes_Section\render(), WP_Widget_Area_Customize_Control\render_content(), WP_Customize_Header_Image_Control\render_content(), wp_print_media_templates(), wp_print_revision_templates(), and wp_widget_control().
_n ($single, $plural, $number, $domain = 'default')
Translates and retrieves the singular or plural form based on the supplied number.
Used when you want to use the appropriate form of a string based on whether a number is singular or plural.
Example:
$people = sprintf(_n('%s person', '%s people', $count, 'text-domain'), number_format_i18n($count));
Since
2.8.0
Parameters
string $single The text to be used if the number is singular.
string $plural The text to be used if the number is plural.
int $number The number to compare against to use either the singular or plural form.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string The translated singular or plural form.
Filter the singular or plural form of a string.
Since
2.2.0
Parameters
string $translation Translated text.
string $single The text to be used if the number is singular.
string $plural The text to be used if the number is plural.
string $number The number to compare against to use either the singular or plural form.
string $domain Text domain. Unique identifier for retrieving translated strings.
Definition at line 332 of file l10n.php.
References $translations, apply_filters(), and get_translations_for_domain().
Referenced by _nc(), _wp_ajax_delete_comment_response(), WP_List_Table\ajax_response(), WP_List_Table\comments_bubble(), comments_popup_link(), WP_Customize_Nav_Menus\customize_register(), GFFormList\form_list_page(), get_comments_number_text(), WP_MS_Users_List_Table\get_views(), WP_MS_Themes_List_Table\get_views(), WP_Plugins_List_Table\get_views(), human_time_diff(), WP_List_Table\pagination(), GFPaymentStatsTable\pagination(), WP_Screen\render_screen_layout(), WP_Users_List_Table\single_row(), translate_nooped_plural(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_admin_bar_comments_menu(), wp_ajax_replyto_comment(), wp_dashboard_right_now(), wp_get_update_data(), wp_network_dashboard_right_now(), and wp_star_rating().
_n_noop ($singular, $plural, $domain = null)
Registers plural strings in POT file, but don't translate them.
Used when you want to keep structures with translatable plural strings and use them later when the number is known.
Example:
$messages = array(
    'post' => _n_noop( '%s post', '%s posts', 'text-domain' ),
    'page' => _n_noop( '%s pages', '%s pages', 'text-domain' ),
);
...
$message = $messages[ $type ];
$usable_text = sprintf(translate_nooped_plural($message, $count, 'text-domain'), number_format_i18n($count));
Since
2.5.0
Parameters
string $singular Singular form to be localized.
string $plural Plural form to be localized.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default null.
Returns
array { Array of translation information for the strings.
string $0 Singular form to be localized. No longer used. string $1 Plural form to be localized. No longer used. string $singular Singular form to be localized. string $plural Plural form to be localized. null $context Context information for the translators. string $domain Text domain. }
Definition at line 424 of file l10n.php.
References null.
Referenced by create_initial_post_types(), get_post_mime_types(), and wp_generate_tag_cloud().
_nx ($single, $plural, $number, $context, $domain = 'default')
Translates and retrieves the singular or plural form based on the supplied number, with gettext context.
This is a hybrid of _n() and _x(). It supports context and plurals.
Used when you want to use the appropriate form of a string with context based on whether a number is singular or plural.
Example:
$people = sprintf(_n('%s person', '%s people', $count, 'context', 'text-domain'), number_format_i18n($count));
Since
2.8.0
Parameters
string $single The text to be used if the number is singular.
string $plural The text to be used if the number is plural.
int $number The number to compare against to use either the singular or plural form.
string $context Context information for the translators.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string The translated singular or plural form.
Filter the singular or plural form of a string with gettext context.
Since
2.8.0
Parameters
string $translation Translated text.
string $single The text to be used if the number is singular.
string $plural The text to be used if the number is plural.
string $number The number to compare against to use either the singular or plural form.
string $context Context information for the translators.
string $domain Text domain. Unique identifier for retrieving translated strings.
Definition at line 372 of file l10n.php.
References $translations, apply_filters(), and get_translations_for_domain().
Referenced by _wp_ajax_delete_comment_response(), WP_MS_Users_List_Table\get_views(), WP_Users_List_Table\get_views(), WP_Posts_List_Table\get_views(), WP_MS_Themes_List_Table\get_views(), WP_Plugins_List_Table\get_views(), translate_nooped_plural(), wp_ajax_replyto_comment(), and wp_dashboard_right_now().
_nx_noop ($singular, $plural, $context, $domain = null)
Register plural strings with gettext context in the POT file, but don't translate them.
Used when you want to keep structures with translatable plural strings and use them later when the number is known.
Example:
$messages = array(
    'post' => _n_noop( '%s post', '%s posts', 'context', 'text-domain' ),
    'page' => _n_noop( '%s pages', '%s pages', 'context', 'text-domain' ),
);
...
$message = $messages[ $type ];
$usable_text = sprintf(translate_nooped_plural($message, $count, 'text-domain'), number_format_i18n($count));
Since
2.8.0
Parameters
string $singular Singular form to be localized.
string $plural Plural form to be localized.
string $context Context information for the translators.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default null.
Returns
array { Array of translation information for the strings.
string $0 Singular form to be localized. No longer used. string $1 Plural form to be localized. No longer used. string $2 Context information for the translators. No longer used. string $singular Singular form to be localized. string $plural Plural form to be localized. string $context Context information for the translators. string $domain Text domain. }
Definition at line 463 of file l10n.php.
Referenced by WP_Comments_List_Table\get_views().
_x ($text, $context, $domain = 'default')
Retrieve translated string with gettext context.
Quite a few times, there will be collisions with similar translatable text found in more than two places, but with different translated context.
By including the context in the pot file, translators can translate the two strings differently.
Since
2.8.0
Parameters
string $text Text to translate.
string $context Context information for the translators.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated context string without pipe.
Definition at line 264 of file l10n.php.
References $text, and translate_with_gettext_context().
Referenced by _ex().
before_last_bar ($string)
Remove last item on a pipe-delimited string.
Meant for removing the last item in a string, such as 'Role name|User role'. The original string will be returned if no pipe '|' characters are found in the string.
Since
2.8.0
Parameters
string $string A pipe-delimited string.
Returns
string Either $string or everything before the last pipe.
Definition at line 119 of file l10n.php.
Referenced by _c(), _nc(), translate_user_role(), and translate_with_context().
esc_attr__ ($text, $domain = 'default')
Retrieve the translation of $text and escapes it for safe use in an attribute.
If there is no translation, or the text domain isn't loaded, the original text is returned.
Since
2.8.0
Parameters
string $text Text to translate.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated text on success, original text on failure.
Definition at line 188 of file l10n.php.
References $text, esc_attr(), and translate().
Referenced by _wp_dashboard_recent_comments_row(), GravityView_Delete_Entry\add_delete_button(), GFForms\add_form_button(), GFForms\admin_bar(), Plugin_Upgrader_Skin\after(), GravityView_Settings\app_settings_fields(), GravityView_Edit_Entry_Render\edit_entry_form(), edit_form_image_editor(), WP_Customize_Nav_Menus\enqueue_scripts(), WP_Customize_Widgets\enqueue_scripts(), WP_Comments_List_Table\extra_tablenav(), GFFeedAddOn\get_action_links(), GF_Field\get_admin_buttons(), WP_Media_List_Table\get_columns(), WP_Posts_List_Table\get_columns(), GF_Field_List\get_field_input(), GF_Field_Name\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_Post_Excerpt\get_form_editor_field_title(), GF_Field_HTML\get_form_editor_field_title(), GF_Field_Post_Tags\get_form_editor_field_title(), GF_Field_Section\get_form_editor_field_title(), GF_Field_Name\get_form_editor_field_title(), GF_Field_Page\get_form_editor_field_title(), GF_Field_Post_Category\get_form_editor_field_title(), GF_Field_Post_Content\get_form_editor_field_title(), GF_Field_Post_Custom_Field\get_form_editor_field_title(), GF_Field_Post_Image\get_form_editor_field_title(), GF_Field_Hidden\get_form_editor_field_title(), GF_Field_Post_Title\get_form_editor_field_title(), GF_Field_Product\get_form_editor_field_title(), GF_Field_List\get_form_editor_field_title(), GF_Field_CreditCard\get_form_editor_field_title(), GF_Field_Radio\get_form_editor_field_title(), GF_Field_Date\get_form_editor_field_title(), GF_Field_Time\get_form_editor_field_title(), GF_Field_Select\get_form_editor_field_title(), GF_Field_Text\get_form_editor_field_title(), GF_Field_Email\get_form_editor_field_title(), GF_Field_Textarea\get_form_editor_field_title(), GF_Field_Website\get_form_editor_field_title(), GF_Field_FileUpload\get_form_editor_field_title(), GF_Field_Number\get_form_editor_field_title(), GF_Field_CAPTCHA\get_form_editor_field_title(), GF_Field_Checkbox\get_form_editor_field_title(), GF_Field_Phone\get_form_editor_field_title(), GF_Field_Password\get_form_editor_field_title(), GF_Field_MultiSelect\get_form_editor_field_title(), GF_Field_Total\get_form_editor_field_title(), GF_Field_Shipping\get_form_editor_field_title(), GF_Field_Quantity\get_form_editor_field_title(), GF_Field_Option\get_form_editor_field_title(), GF_Field_Address\get_form_editor_field_title(), get_media_item(), GF_Field_Name\get_name_prefix_field(), GF_Field_Radio\get_radio_choices(), GravityView_Settings\get_required_indicator(), get_the_password_form(), GF_Field_FileUpload\get_value_entry_detail(), GF_Field_FileUpload\get_value_entry_list(), WP_Comments_List_Table\handle_row_actions(), WP_Posts_List_Table\handle_row_actions(), install_search_form(), WP_Theme_Install_List_Table\install_theme_info(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GravityView_Post_Types\no_views_text(), GFEntryDetail\notes_grid(), GFPaymentStatsTable\pagination(), GravityView_Admin_Views\render_active_areas(), WP_Screen\render_screen_options(), GravityView_Admin_Duplicate_View\save_as_new_view(), GFSettings\settings_uninstall_page(), WP_Theme_Install_List_Table\single_row(), ToggleActive(), WP_Widget_Meta\widget(), wp_default_scripts(), wp_media_insert_url_form(), and wp_timezone_choice().
esc_attr_e ($text, $domain = 'default')
Display translated text that has been escaped for safe use in an attribute.
Since
2.8.0
Parameters
string $text Text to translate.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Definition at line 230 of file l10n.php.
References $text, esc_attr(), and translate().
Referenced by _wp_menu_output(), GFEntryList\leads_page(), wp_print_media_templates(), and wp_print_revision_templates().
esc_attr_x ($text, $context, $domain = 'default')
Translate string with gettext context, and escapes it for safe use in an attribute.
Since
2.8.0
Parameters
string $text Text to translate.
string $context Context information for the translators.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated text
Definition at line 294 of file l10n.php.
References $text, esc_attr(), and translate_with_gettext_context().
Referenced by GravityView_Widget_Search\add_datepicker_localization(), get_search_form(), GravityView_Change_Entry_Creator\update_entry_creator(), and wp_dropdown_languages().
esc_html__ ($text, $domain = 'default')
Retrieve the translation of $text and escapes it for safe use in HTML output.
If there is no translation, or the text domain isn't loaded, the original text is returned.
Since
2.8.0
Parameters
string $text Text to translate.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated text
Definition at line 204 of file l10n.php.
References $text, esc_html, and translate().
Referenced by GravityView_Field_Quiz_Score\__construct(), GravityView_Field_FileUpload\__construct(), GravityView_Field_Name\__construct(), GravityView_Field_Captcha\__construct(), GravityView_Field_Hidden\__construct(), GravityView_Field_MultiSelect\__construct(), GravityView_Field_Page\__construct(), GravityView_Field_Password\__construct(), GravityView_Field_Phone\__construct(), GravityView_Field_Post_Category\__construct(), GravityView_Field_Post_Content\__construct(), GravityView_Field_Post_Custom_Field\__construct(), GravityView_Post_Excerpt\__construct(), GravityView_Field_Radio\__construct(), GravityView_Field_Select\__construct(), GravityView_Field_Text\__construct(), GravityView_Field_Checkbox\__construct(), GravityView_Field_Created_By\__construct(), GravityView_Field_CreditCard\__construct(), GravityView_Field_Date\__construct(), GravityView_Field_Post_Image\__construct(), GravityView_Field_Source_URL\__construct(), GravityView_Field_Address\__construct(), GravityView_Field_Email\__construct(), GravityView_Field_Post_Tags\__construct(), GravityView_Field_Post_Title\__construct(), GravityView_Field_Section\__construct(), GravityView_Field_Textarea\__construct(), GravityView_Field_Website\__construct(), GravityView_Field_Calculation\__construct(), GravityView_Field_HTML\__construct(), GravityView_Widget_Search\__construct(), GravityView_Field_Date_Created\__construct(), GravityView_Field_Number\__construct(), GravityView_Field_Other_Entries\__construct(), GravityView_Field_Payment_Status\__construct(), GravityView_Field_Payment_Date\__construct(), GravityView_Field_Post_ID\__construct(), GravityView_Field_Payment_Amount\__construct(), GravityView_Field_Payment_Method\__construct(), GravityView_Field_Transaction_ID\__construct(), GravityView_Field_Currency\__construct(), GravityView_Field_Entry_Link\__construct(), GravityView_Field_Custom\__construct(), GravityView_Field_Is_Fulfilled\__construct(), GravityView_Field_List\__construct(), GravityView_Field_Transaction_Type\__construct(), GravityView_Field_Time\__construct(), GFPaymentStatsTable\__construct(), GravityView_Compatibility\_shortcode_gf_notice(), GFPaymentAddOn\add_pending_payment(), GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_Change_Entry_Creator\add_select(), GFPaymentAddOn\add_subscription_payment(), GFForms\addons_page(), GFEntryList\all_leads_page(), GravityView_Settings\app_settings_fields(), GFPaymentAddOn\billing_info_fields(), GFPaymentAddOn\cancel_subscription(), GFPaymentAddOn\complete_payment(), ConfirmDeleteForm(), GFFormsModel\convert_confirmation(), CreateDefaultValuesUI(), CreateInputNames(), CreatePlaceholdersUI(), GFForms\dashboard(), GFForms\dashboard_update_message(), GF_Installation_Wizard_Step_License_Key\display(), GFEntryList\display_paging_links(), GFAutoUpgrade\display_updates(), GFFeedAddOn\duplicate_feed(), GFFormsModel\duplicate_form(), GFForms\enqueue_admin_scripts(), GFPaymentAddOn\expire_subscription(), GFExport\export_lead_page(), GFPaymentAddOn\fail_payment(), GFPaymentAddOn\fail_subscription_payment(), GFPaymentAddOn\feed_list_columns(), GFFeedAddOn\feed_list_title(), GFPaymentAddOn\feed_settings_fields(), GFFeedAddOn\feed_settings_title(), GravityView_Search_WP_Widget\form(), GFFeedAddOn\form_settings_header(), GFFeedAddOn\form_settings_title(), GFPaymentAddOn\format_chart_h_axis(), GVCommon\format_date(), GravityView_oEmbed\generate_preview_notice(), GFFeedAddOn\get_action_links(), GF_Field_Address\get_address_types(), GF_Field\get_admin_buttons(), GFFeedAddOn\get_bulk_actions(), GF_Field_Address\get_canadian_provinces(), GFAutoUpgrade\get_changelog(), GFForms\get_changelog(), GF_Field_Checkbox\get_checkbox_choices(), GFPaymentAddOn\get_column_value_amount(), GFPaymentAddOn\get_column_value_transactionType(), GF_Field_Address\get_countries(), GF_Field_Address\get_country_codes(), GF_Field_Date\get_day_dropdown(), GF_Field_CreditCard\get_expiration_months(), GF_Field_CreditCard\get_expiration_years(), GF_Field_Page\get_field_content(), GFFormDisplay\get_field_content(), GF_Field_HTML\get_field_input(), GF_Field_Calculation\get_field_input(), GF_Field_SingleProduct\get_field_input(), GF_Field_Name\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Password\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GFEntryList\get_filter_links(), GFFormDisplay\get_form(), GFFormsModel\get_grid_columns(), GF_Field_Date\get_month_dropdown(), GF_Installation_Wizard_Step_Complete\get_next_button_text(), GFPaymentAddOn\get_order_data(), GFPaymentAddOn\get_payment_choices(), GFFormDisplay\get_progress_bar(), GF_Field_Radio\get_radio_choices(), GF_Field_Number\get_range_message(), GFPaymentAddOn\get_sales_data(), GFFeedAddOn\get_save_error_message(), GFAddOn\get_save_error_message(), GFFeedAddOn\get_save_success_message(), GFAddOn\get_save_success_message(), GVCommon\get_sortable_fields(), GF_Installation_Wizard_Step_Complete\get_title(), GF_Installation_Wizard_Step_License_Key\get_title(), GF_Installation_Wizard_Step_Settings\get_title(), GF_Installation_Wizard_Step_Background_Updates\get_title(), GF_Field_Address\get_us_state_code(), GF_Field_Address\get_us_states(), GF_Field_Calculation\get_value_entry_detail(), GF_Field_SingleProduct\get_value_entry_detail(), GF_Field_FileUpload\get_value_entry_list(), GF_Field_Date\get_year_dropdown(), gravityview_get_map_link(), GFForms\handle_ajax_do_shortcode(), GFHelp\help_page(), InitializeFormConditionalLogic(), InitPaginationOptions(), GravityView_View_Data\is_valid_embed_id(), GFEntryDetail\lead_detail_grid(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GravityView_Settings\license_key_notice(), GFFormsModel\load_notifications_from_legacy(), GFFeedAddOn\maybe_save_feed_settings(), notification_edit_page(), GFPaymentAddOn\option_choices(), GFPaymentAddOn\other_settings_fields(), output_form_list_script_block(), GFEntryDetail\payment_details_box(), GravityView_Admin\plugin_action_links(), GFForms\plugin_row(), GFForms\plugin_settings_link(), GFPaymentAddOn\process_callback_action(), GFPaymentAddOn\process_capture(), GFPaymentAddOn\process_subscription(), GFPaymentAddOn\product_amount_choices(), GFPaymentAddOn\recurring_amount_choices(), GFPaymentAddOn\refund_payment(), GFForms\register_scripts(), GravityView_oEmbed\render_admin(), GravityView_Admin_Views\render_directory_active_areas(), GravityView_Widget_Search\render_searchable_fields(), GFFormDisplay\replace_save_variables(), GFPaymentAddOn\requires_credit_card_message(), GFForms\resend_notifications(), GFPaymentAddOn\results_filter_ui(), GFPaymentAddOn\results_markup(), GFAutoUpgrade\rg_plugin_row(), GFFormsModel\save_lead(), SaveCustomChoices(), GFPaymentAddOn\settings_setup_fee(), GFPaymentAddOn\settings_trial(), GFSettings\settings_uninstall_page(), GFAddOn\single_setting(), GFPaymentAddOn\start_subscription(), GV_License_Handler\strings(), GF_Installation_Wizard_Step_Settings\summary(), GF_Installation_Wizard_Step_Background_Updates\summary(), GFPaymentAddOn\supported_billing_intervals(), GravityView_Welcome\tabs(), GravityView_Widget_Search\the_clear_search_button(), TogglePostCategoryInitialItem(), GFUpdate\update_page(), GF_Field_Name\validate(), GF_Field_HiddenProduct\validate(), GF_Field_Calculation\validate(), GF_Field_SingleProduct\validate(), GF_Field_FileUpload\validate(), GF_Field_CAPTCHA\validate(), GF_Field_Address\validate(), GF_Field_Date\validate(), GF_Field_Time\validate(), GF_Field_Donation\validate(), GF_Field_Radio\validate(), GF_Field_Website\validate(), GF_Field_CreditCard\validate(), GF_Field_Password\validate(), GF_Field_Email\validate(), GF_Installation_Wizard_Step_License_Key\validate(), GF_Field_Number\validate(), GF_Installation_Wizard_Step_Background_Updates\validate(), GFFormDisplay\validate(), GFFormDisplay\validate_entry_limit(), GFFormDisplay\validate_form_schedule(), and GFPaymentAddOn\void_authorization().
esc_html_e ($text, $domain = 'default')
Display translated text that has been escaped for safe use in HTML output.
Since
2.8.0
Parameters
string $text Text to translate.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Definition at line 243 of file l10n.php.
References $text, esc_html, and translate().
esc_html_x ($text, $context, $domain = 'default')
Translate string with gettext context, and escapes it for safe use in HTML output.
Since
2.9.0
Parameters
string $text Text to translate.
string $context Context information for the translators.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated text.
Definition at line 309 of file l10n.php.
References $text, esc_html, and translate_with_gettext_context().
Referenced by GFEntryList\get_filter_links(), and GFPaymentStatsTable\pagination().
get_available_languages ($dir = null)
Get all available languages based on the presence of *.mo files in a given directory.
The default directory is WP_LANG_DIR.
Since
3.0.0
Parameters
string $dir A directory to search for language files. Default WP_LANG_DIR.
Returns
array An array of language codes or an empty array if no languages are present. Language codes are formed by stripping the .mo extension from the language file names.
Definition at line 849 of file l10n.php.
References $dir.
Referenced by sanitize_option(), upgrade_400(), wp_download_language_pack(), and wp_install_language_form().
get_locale ()
Retrieves the current locale.
If the locale is set, then it will filter the locale in the {
See also
'locale'} filter hook and return the value.
If the locale is not set already, then the WPLANG constant is used if it is defined. Then it is filtered through the {
See also
'locale'} filter hook and the value for the locale global set and the locale is returned.
The process to get the locale should only be done once, but the locale will always be filtered using the {
See also
'locale'} hook.
Since
1.5.0
string $locale string $wp_local_package
Returns
string The locale of the blog or from the {
See also
'locale'} hook.
Filter WordPress install's locale ID.
Since
1.5.0
Parameters
string $locale The locale ID.
This filter is documented in wp-includes/l10n.php
Definition at line 30 of file l10n.php.
References $locale, apply_filters(), get_option(), get_site_option(), is_multisite(), wp_installing(), and WPLANG.
Referenced by _WP_Editors\editor_settings(), get_bloginfo(), get_locale_stylesheet_uri(), WP_Press_This\html(), iframe_header(), GFAddOn\init(), list_core_update(), list_translation_updates(), load_default_textdomain(), load_muplugin_textdomain(), GravityView_Extension\load_plugin_textdomain(), GravityView_Plugin\load_plugin_textdomain(), load_plugin_textdomain(), load_theme_textdomain(), login_header(), plugins_api(), populate_network(), WP_Plugin_Install_List_Table\prepare_items(), remove_accents(), WP_Theme\sort_by_name(), themes_api(), translations_api(), wp_credits(), wp_get_popular_importers(), wp_maybe_decline_date(), wp_timezone_choice(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
get_translations_for_domain ($domain)
Return the Translations instance for a text domain.
If there isn't one, returns empty Translations instance.
Since
2.8.0
array $l10n
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
Returns
NOOP_Translations A Translations instance.
Definition at line 794 of file l10n.php.
Referenced by _n(), _nx(), translate(), and translate_with_gettext_context().
is_textdomain_loaded ($domain)
Whether there are translations for the text domain.
Since
3.0.0
array $l10n
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
Returns
bool Whether there are translations.
Definition at line 812 of file l10n.php.
Referenced by _get_plugin_data_markup_translate(), and WP_Theme\load_textdomain().
load_child_theme_textdomain ($domain, $path = false)
Load the child themes translated strings.
If the current locale exists as a .mo file in the child themes root directory, it will be included in the translated strings by the $domain.
The .mo files must be named based on the locale exactly.
Since
2.9.0
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
string $path Optional. Path to the directory containing the .mo file. Default false.
Returns
bool True when the theme textdomain is successfully loaded, false otherwise.
Definition at line 776 of file l10n.php.
References $path, get_stylesheet_directory(), and load_theme_textdomain().
load_default_textdomain ($locale = null)
Load default translated strings based on locale.
Loads the .mo file in WP_LANG_DIR constant path from WordPress root. The translated (.mo) file is named based on the locale.
See also
load_textdomain()
Since
1.5.0
Parameters
string $locale Optional. Locale to load. Default is the value of {
See also
get_locale()}.
Returns
bool Whether the textdomain was loaded.
Definition at line 625 of file l10n.php.
References $locale, get_locale(), is_admin(), is_multisite(), is_network_admin(), load_textdomain(), null, unload_textdomain(), wp_installing(), WP_INSTALLING_NETWORK, and WP_REPAIRING.
Referenced by _redirect_to_about_wordpress().
load_muplugin_textdomain ($domain, $mu_plugin_rel_path = '')
Load the translated strings for a plugin residing in the mu-plugins directory.
Since
3.0.0
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
string $mu_plugin_rel_path Relative to WPMU_PLUGIN_DIR directory in which the .mo file resides. Default empty string.
Returns
bool True when textdomain is successfully loaded, false otherwise.
This filter is documented in wp-includes/l10n.php
Definition at line 706 of file l10n.php.
References $locale, $path, apply_filters(), get_locale(), load_textdomain(), and trailingslashit().
Referenced by GravityView_Plugin\load_plugin_textdomain().
load_plugin_textdomain ($domain, $deprecated = false, $plugin_rel_path = false)
Load a plugin's translated strings.
If the path is not given then it will be the root of the plugin directory.
The .mo file should be named based on the text domain with a dash, and then the locale exactly.
Since
1.5.0
Parameters
string $domain Unique identifier for retrieving translated strings
string $deprecated Use the $plugin_rel_path parameter instead.
string $plugin_rel_path Optional. Relative path to WP_PLUGIN_DIR where the .mo file resides. Default false.
Returns
bool True when textdomain is successfully loaded, false otherwise.
Filter a plugin's locale.
Since
3.0.0
Parameters
string $locale The plugin's current locale.
string $domain Text domain. Unique identifier for retrieving translated strings.
Definition at line 665 of file l10n.php.
References $deprecated, $locale, $path, _deprecated_argument(), ABSPATH, apply_filters(), elseif, get_locale(), and load_textdomain().
Referenced by _get_plugin_data_markup_translate(), GFAutoUpgrade\init(), and GFAddOn\init().
load_textdomain ($domain, $mofile)
Load a .mo file into the text domain $domain.
If the text domain already exists, the translations will be merged. If both sets have the same string, the translation from the original value will be taken.
On success, the .mo file will be placed in the $l10n global by $domain and will be a MO object.
Since
1.5.0
array $l10n
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
string $mofile Path to the .mo file.
Returns
bool True on success, false on failure.
Filter text domain and/or MO file path for loading translations.
Since
2.9.0
Parameters
bool $override Whether to override the text domain. Default false.
string $domain Text domain. Unique identifier for retrieving translated strings.
string $mofile Path to the MO file.
Fires before the MO translation file is loaded.
Since
2.9.0
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
string $mofile Path to the .mo file.
Filter MO file path for loading translations for a specific text domain.
Since
2.9.0
Parameters
string $mofile Path to the MO file.
string $domain Text domain. Unique identifier for retrieving translated strings.
Definition at line 518 of file l10n.php.
References apply_filters(), and do_action().
Referenced by GFAddOn\init(), load_default_textdomain(), load_muplugin_textdomain(), GravityView_Extension\load_plugin_textdomain(), GravityView_Plugin\load_plugin_textdomain(), load_plugin_textdomain(), load_theme_textdomain(), wp_load_translations_early(), and wp_timezone_choice().
load_theme_textdomain ($domain, $path = false)
Load the theme's translated strings.
If the current locale exists as a .mo file in the theme's root directory, it will be included in the translated strings by the $domain.
The .mo files must be named based on the locale exactly.
Since
1.5.0
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
string $path Optional. Path to the directory containing the .mo file. Default false.
Returns
bool True when textdomain is successfully loaded, false otherwise.
Filter a theme's locale.
Since
3.0.0
Parameters
string $locale The theme's current locale.
string $domain Text domain. Unique identifier for retrieving translated strings.
Definition at line 736 of file l10n.php.
References $locale, $path, apply_filters(), get_locale(), get_template_directory(), load_textdomain(), and untrailingslashit().
Referenced by load_child_theme_textdomain(), GravityView_Plugin\load_plugin_textdomain(), WP_Theme\load_textdomain(), twentythirteen_setup(), and twentytwelve_setup().
translate ($text, $domain = 'default')
Retrieve the translation of $text.
If there is no translation, or the text domain isn't loaded, the original text is returned.
Note: Don't use translate() directly, use __() or related functions.
Since
2.2.0
Parameters
string $text Text to translate.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated text
Filter text with its translation.
Since
2.0.11
Parameters
string $translations Translated text.
string $text Text to translate.
string $domain Text domain. Unique identifier for retrieving translated strings.
Definition at line 92 of file l10n.php.
References $text, $translations, apply_filters(), and get_translations_for_domain().
Referenced by __(), _c(), _e(), _get_plugin_data_markup_translate(), esc_attr__(), esc_attr_e(), esc_html__(), esc_html_e(), WP_Theme\translate_header(), translate_with_context(), wp_get_popular_importers(), and wp_timezone_choice().
translate_nooped_plural ($nooped_plural, $count, $domain = 'default')
Translates and retrieves the singular or plural form of a string that's been registered with _n_noop() or _nx_noop().
Used when you want to use a translatable plural string once the number is known.
Example:
$messages = array(
    'post' => _n_noop( '%s post', '%s posts', 'text-domain' ),
    'page' => _n_noop( '%s pages', '%s pages', 'text-domain' ),
);
...
$message = $messages[ $type ];
$usable_text = sprintf(translate_nooped_plural($message, $count, 'text-domain'), number_format_i18n($count));
Since
3.1.0
Parameters
array $nooped_plural Array with singular, plural, and context keys, usually the result of _n_noop() or _nx_noop().
int $count Number of objects.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. If $nooped_plural contains a text domain passed to _n_noop() or _nx_noop(), it will override this value. Default 'default'.
Returns
string Either $single or $plural translated text.
Definition at line 491 of file l10n.php.
References $count, _n(), and _nx().
Referenced by WP_Comments_List_Table\get_views(), WP_Posts_List_Table\get_views(), media_upload_library_form(), and wp_generate_tag_cloud().
translate_user_role ($name)
Translates role name.
Since the role names are in the database and not in the source there are dummy gettext calls to get them into the POT file and this function properly translates them back.
The before_last_bar() call is needed, because older installs keep the roles using the old context format: 'Role name|User role' and just skipping the content after the last bar is easier than fixing them in the DB. New installs won't suffer from that problem.
Since
2.8.0
Parameters
string $name The role name.
Returns
string Translated role name on success, original name on failure.
Definition at line 834 of file l10n.php.
References $name, before_last_bar(), and translate_with_gettext_context().
Referenced by admin_created_user_email(), WP_Users_List_Table\get_role_list(), WP_Users_List_Table\get_views(), and wp_dropdown_roles().
translate_with_gettext_context ($text, $context, $domain = 'default')
Retrieve the translation of $text in the context defined in $context.
If there is no translation, or the text domain isn't loaded the original text is returned.
Note: Don't use translate_with_gettext_context() directly, use _x() or related functions.
Since
2.8.0
Parameters
string $text Text to translate.
string $context Context information for the translators.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string Translated text on success, original text on failure.
Filter text with its translation based on context information.
Since
2.8.0
Parameters
string $translations Translated text.
string $text Text to translate.
string $context Context information for the translators.
string $domain Text domain. Unique identifier for retrieving translated strings.
Definition at line 144 of file l10n.php.
References $text, $translations, apply_filters(), and get_translations_for_domain().
Referenced by _x(), esc_attr_x(), esc_html_x(), and translate_user_role().
unload_textdomain ($domain)
Unload translations for a text domain.
Since
3.0.0
array $l10n
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
Returns
bool Whether textdomain was unloaded.
Filter the text domain for loading translation.
Since
3.0.0
Parameters
bool $override Whether to override unloading the text domain. Default false.
string $domain Text domain. Unique identifier for retrieving translated strings.
Fires before the text domain is unloaded.
Since
3.0.0
Parameters
string $domain Text domain. Unique identifier for retrieving translated strings.
Definition at line 579 of file l10n.php.
References apply_filters(), and do_action().
Referenced by load_default_textdomain().
wp_dropdown_languages ($args = array())
Language selector.
Since
4.0.0
4.3.0 Introduced the echo argument.
See also
get_available_languages()
wp_get_available_translations()
Parameters
string | array $args { Optional. Array or string of arguments for outputting the language selector.
string $id ID attribute of the select element. Default empty. string $name Name attribute of the select element. Default empty. array $languages List of installed languages, contain only the locales. Default empty array. array $translations List of available translations. Default result of wp_get_available_translations(). string $selected Language which should be selected. Default empty. bool|int $echo Whether to echo the generated markup. Accepts 0, 1, or their boolean equivalents. Default 1. bool $show_available_translations Whether to show available translations. Default true. }
Returns
string HTML content
Definition at line 965 of file l10n.php.
References $language, $locale, $output, $translations, ABSPATH, esc_attr(), esc_attr_x(), esc_html, selected(), wp_get_available_translations(), and wp_parse_args().
wp_get_installed_translations ($type)
Get installed translations.
Looks in the wp-content/languages directory for translations of plugins or themes.
Since
3.7.0
Parameters
string $type What to search for. Accepts 'plugins', 'themes', 'core'.
Returns
array Array of language data.
Definition at line 877 of file l10n.php.
References $dir, $file, $language, and wp_get_pomo_file_data().
Referenced by delete_plugins(), delete_theme(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
wp_get_pomo_file_data ($po_file)
Extract headers from a PO file.
Since
3.7.0
Parameters
string $po_file Path to PO file.
Returns
array PO file headers.
Definition at line 926 of file l10n.php.
References $value, and get_file_data().
Referenced by wp_get_installed_translations().