GravityView: link-template.php File Reference
link-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_page_link ($post=false, $leavename=false, $sample=false)
Retrieve the page permalink.
_navigation_markup ($links, $class= 'posts-navigation', $screen_reader_text= '')
Wraps passed links in navigational markup.
adjacent_post_link ($format, $link, $in_same_term=false, $excluded_terms= '', $previous=true, $taxonomy= 'category')
Display adjacent post link.
adjacent_posts_rel_link ($title= '%title', $in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Display relational links for the posts adjacent to the current post.
adjacent_posts_rel_link_wp_head ()
Display relational links for the posts adjacent to the current post for single post pages.
admin_url ($path= '', $scheme= 'admin')
Retrieve the url to the admin area for the current site.
content_url ($path= '')
Retrieve the url to the content directory.
edit_bookmark_link ($link= '', $before= '', $after= '', $bookmark=null)
Display edit bookmark (literally a URL external to blog) link anchor content.
edit_comment_link ($text=null, $before= '', $after= '')
Display edit comment link with formatting.
edit_post_link ($text=null, $before= '', $after= '', $id=0, $class= 'post-edit-link')
Display edit post link for post.
edit_tag_link ($link= '', $before= '', $after= '', $tag=null)
Display or retrieve edit tag link with formatting.
edit_term_link ($link= '', $before= '', $after= '', $term=null, $echo=true)
Display or retrieve edit term link with formatting.
get_adjacent_post ($in_same_term=false, $excluded_terms= '', $previous=true, $taxonomy= 'category')
Retrieve adjacent post.
get_adjacent_post_link ($format, $link, $in_same_term=false, $excluded_terms= '', $previous=true, $taxonomy= 'category')
Get adjacent post link.
get_adjacent_post_rel_link ($title= '%title', $in_same_term=false, $excluded_terms= '', $previous=true, $taxonomy= 'category')
Get adjacent post relational link.
get_admin_url ($blog_id=null, $path= '', $scheme= 'admin')
Retrieves the url to the admin area for a given site.
get_attachment_link ($post=null, $leavename=false)
Retrieve permalink for attachment.
get_author_feed_link ($author_id, $feed= '')
Retrieve the feed link for a given author.
get_avatar_data ($id_or_email, $args=null)
Retrieve default data about the avatar.
get_avatar_url ($id_or_email, $args=null)
Retrieve the avatar URL.
get_boundary_post ($in_same_term=false, $excluded_terms= '', $start=true, $taxonomy= 'category')
Retrieve boundary post.
get_category_feed_link ($cat_id, $feed= '')
Retrieve the feed link for a category.
get_comments_pagenum_link ($pagenum=1, $max_page=0)
Retrieve comments page number link.
get_dashboard_url ($user_id=0, $path= '', $scheme= 'admin')
Get the URL to the user's dashboard.
get_day_link ($year, $month, $day)
Retrieve the permalink for the day archives with year and month.
get_delete_post_link ($id=0, $deprecated= '', $force_delete=false)
Retrieve delete posts link for post.
get_edit_bookmark_link ($link=0)
Display edit bookmark (literally a URL external to blog) link.
get_edit_comment_link ($comment_id=0)
Retrieve edit comment link.
get_edit_post_link ($id=0, $context= 'display')
Retrieve edit posts link for post.
get_edit_profile_url ($user_id=0, $scheme= 'admin')
Get the URL to the user's profile editor.
get_edit_tag_link ($tag_id, $taxonomy= 'post_tag')
Retrieve edit tag link.
get_edit_term_link ($term_id, $taxonomy, $object_type= '')
Retrieve edit term url.
get_edit_user_link ($user_id=null)
Retrieve edit user link.
get_feed_link ($feed= '')
Retrieve the permalink for the feed type.
get_home_url ($blog_id=null, $path= '', $scheme=null)
Retrieve the home url for a given site.
get_month_link ($year, $month)
Retrieve the permalink for the month archives with year.
get_next_comments_link ($label= '', $max_page=0)
Return the link to next comments page.
get_next_post ($in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Retrieve next post that is adjacent to current post.
get_next_post_link ($format= '%link &raquo;', $link= '%title', $in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Get next post link that is adjacent to the current post.
get_next_posts_link ($label=null, $max_page=0)
Return the next posts page link.
get_next_posts_page_link ($max_page=0)
Retrieve next posts page link.
get_page_link ($post=false, $leavename=false, $sample=false)
Retrieve the permalink for current page or page ID.
get_pagenum_link ($pagenum=1, $escape=true)
Retrieve links for page numbers.
get_permalink ($post=0, $leavename=false)
Retrieve full permalink for current post or post ID.
get_post_comments_feed_link ($post_id=0, $feed= '')
Retrieve the permalink for the post comments feed.
get_post_permalink ($id=0, $leavename=false, $sample=false)
Retrieve the permalink for a post with a custom post type.
get_post_type_archive_feed_link ($post_type, $feed= '')
Retrieve the permalink for a post type archive feed.
get_post_type_archive_link ($post_type)
Retrieve the permalink for a post type archive.
get_posts_nav_link ($args=array())
Return post pages link navigation for previous and next pages.
get_preview_post_link ($post=null, $query_args=array(), $preview_link= '')
Retrieve URL used for the post preview.
get_previous_comments_link ($label= '')
Return the previous comments page link.
get_previous_post ($in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Retrieve previous post that is adjacent to current post.
get_previous_post_link ($format= '&laquo;%link', $link= '%title', $in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Get previous post link that is adjacent to the current post.
get_previous_posts_link ($label=null)
Return the previous posts page link.
get_previous_posts_page_link ()
Retrieve previous posts page link.
get_search_comments_feed_link ($search_query= '', $feed= '')
Retrieve the permalink for the comments feed of the search results.
get_search_feed_link ($search_query= '', $feed= '')
Retrieve the permalink for the feed of the search results.
get_search_link ($query= '')
Retrieve permalink for search.
get_shortcut_link ()
Retrieve the Press This bookmarklet link.
get_site_url ($blog_id=null, $path= '', $scheme=null)
Retrieve the site url for a given site.
get_tag_feed_link ($tag_id, $feed= '')
Retrieve permalink for feed of tag.
get_term_feed_link ($term_id, $taxonomy= 'category', $feed= '')
Retrieve the feed link for a term.
get_the_comments_navigation ($args=array())
Returns navigation to next/previous set of comments when applicable.
get_the_comments_pagination ($args=array())
Returns a paginated navigation to next/previous set of comments, when applicable.
get_the_permalink ($post=0, $leavename=false)
Retrieve full permalink for current post or post ID.
get_the_post_navigation ($args=array())
Return navigation to next/previous post when applicable.
get_the_posts_navigation ($args=array())
Return navigation to next/previous set of posts when applicable.
get_the_posts_pagination ($args=array())
Return a paginated navigation to next/previous set of posts, when applicable.
get_year_link ($year)
Retrieve the permalink for the year archives.
home_url ($path= '', $scheme=null)
Retrieve the home url for the current site.
includes_url ($path= '', $scheme=null)
Retrieve the url to the includes directory.
network_admin_url ($path= '', $scheme= 'admin')
Retrieve the url to the admin area for the network.
network_home_url ($path= '', $scheme=null)
Retrieves the home url for the current network.
network_site_url ($path= '', $scheme=null)
Retrieve the site url for the current network.
next_comments_link ($label= '', $max_page=0)
Display the link to next comments page.
next_post_link ($format= '%link &raquo;', $link= '%title', $in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Display next post link that is adjacent to the current post.
next_post_rel_link ($title= '%title', $in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Display relational link for the next post adjacent to the current post.
next_posts ($max_page=0, $echo=true)
Display or return the next posts page link.
next_posts_link ($label=null, $max_page=0)
Display the next posts page link.
paginate_comments_links ($args=array())
Create pagination links for the comments on the current post.
permalink_anchor ($mode= 'id')
Display permalink anchor for current post.
plugins_url ($path= '', $plugin= '')
Retrieve a URL within the plugins or mu-plugins directory.
post_comments_feed_link ($link_text= '', $post_id= '', $feed= '')
Display the comment feed link for a post.
posts_nav_link ($sep= '', $prelabel= '', $nxtlabel= '')
Display post pages link navigation for previous and next pages.
prev_post_rel_link ($title= '%title', $in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Display relational link for the previous post adjacent to the current post.
previous_comments_link ($label= '')
Display the previous comments page link.
previous_post_link ($format= '&laquo;%link', $link= '%title', $in_same_term=false, $excluded_terms= '', $taxonomy= 'category')
Display previous post link that is adjacent to the current post.
previous_posts ($echo=true)
Display or return the previous posts page link.
previous_posts_link ($label=null)
Display the previous posts page link.
rel_canonical ()
Output rel=canonical for singular queries.
self_admin_url ($path= '', $scheme= 'admin')
Retrieve the url to the admin area for either the current blog or the network depending on context.
set_url_scheme ($url, $scheme=null)
Sets the scheme for a URL.
site_url ($path= '', $scheme=null)
Retrieve the site url for the current site.
the_comments_navigation ($args=array())
Displays navigation to next/previous set of comments when applicable.
the_comments_pagination ($args=array())
Displays a paginated navigation to next/previous set of comments, when applicable.
the_feed_link ($anchor, $feed= '')
Display the permalink for the feed type.
the_permalink ($post=0)
Display the permalink for the current post.
the_post_navigation ($args=array())
Display navigation to next/previous post when applicable.
the_posts_navigation ($args=array())
Display navigation to next/previous set of posts when applicable.
the_posts_pagination ($args=array())
Display a paginated navigation to next/previous set of posts, when applicable.
the_shortlink ($text= '', $title= '', $before= '', $after= '')
Display the Short Link for a Post.
user_admin_url ($path= '', $scheme= 'admin')
Retrieve the url to the admin area for the current user.
user_trailingslashit ($string, $type_of_url= '')
Retrieve trailing slash string, if blog set for adding trailing slashes.
wp_get_shortlink ($id=0, $context= 'post', $allow_slugs=true)
Return a shortlink for a post, page, attachment, or blog.
wp_shortlink_header ()
Send a Link: rel=shortlink header if a shortlink is defined for the current page.
wp_shortlink_wp_head ()
Inject rel=shortlink into head if a shortlink is defined for the current page.
Function Documentation
_get_page_link ($post = false, $leavename = false, $sample = false)
Retrieve the page permalink.
Ignores page_on_front. Internal use only.
Since
2.1.0 private
WP_Rewrite $wp_rewrite
Parameters
int | object $post Optional. Post ID or object.
bool $leavename Optional. Leave name.
bool $sample Optional. Sample permalink.
Returns
string The page permalink.
Filter the permalink for a non-page_on_front page.
Since
2.1.0
Parameters
string $link The page's permalink.
int $post_id The ID of the page.
Definition at line 343 of file link-template.php.
References $link, $post, $wp_rewrite, apply_filters(), get_page_uri(), get_post(), home_url(), str_replace, and user_trailingslashit().
Referenced by get_attachment_link(), get_page_link(), and get_post_comments_feed_link().
_navigation_markup ($links, $class = 'posts-navigation', $screen_reader_text = '')
Wraps passed links in navigational markup.
Since
4.1.0 private
Parameters
string $links Navigational links.
string $class Optional. Custom class for nav element. Default: 'posts-navigation'.
string $screen_reader_text Optional. Screen reader text for nav element. Default: 'Posts navigation'.
Returns
string Navigation template tag.
Filter the navigation markup template.
Note: The filtered template HTML must contain specifiers for the navigation class (%1$s), the screen-reader-text value (%2$s), and placement of the navigation links (%3$s):
<nav class="navigation %1$s" role="navigation">
    <h2 class="screen-reader-text">%2$s</h2>
    <div class="nav-links">%3$s</div>
</nav>
Since
4.4.0
Parameters
string $template The default template.
string $class The class passed by the calling function.
Returns
string Navigation template.
Definition at line 2545 of file link-template.php.
References $class, $template, __, apply_filters(), esc_html, and sanitize_html_class().
Referenced by get_the_comments_navigation(), get_the_comments_pagination(), get_the_post_navigation(), get_the_posts_navigation(), and get_the_posts_pagination().
adjacent_post_link ($format, $link, $in_same_term = false, $excluded_terms = '', $previous = true, $taxonomy = 'category')
Display adjacent post link.
Can be either next post link or previous.
Since
2.5.0
Parameters
string $format Link anchor format.
string $link Link permalink format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded category IDs.
bool $previous Optional. Whether to display link to previous or next post. Default true.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Definition at line 2044 of file link-template.php.
References $format, $link, and get_adjacent_post_link().
adjacent_posts_rel_link ($title = '%title', $in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Display relational links for the posts adjacent to the current post.
Since
2.8.0
Parameters
string $title Optional. Link title format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Definition at line 1798 of file link-template.php.
References $title, and get_adjacent_post_rel_link().
Referenced by adjacent_posts_rel_link_wp_head().
adjacent_posts_rel_link_wp_head ()
Display relational links for the posts adjacent to the current post for single post pages.
This is meant to be attached to actions like 'wp_head'. Do not call this directly in plugins or theme templates.
Since
3.0.0
Definition at line 1810 of file link-template.php.
References adjacent_posts_rel_link(), is_attachment(), and is_single().
admin_url ($path = '', $scheme = 'admin')
Retrieve the url to the admin area for the current site.
Since
2.6.0
Parameters
string $path Optional path relative to the admin url.
string $scheme The scheme to use. Default is 'admin', which obeys force_ssl_admin() and is_ssl(). 'http' or 'https' can be passed to force those schemes.
Returns
string Admin url link with optional path appended.
Definition at line 3072 of file link-template.php.
References $path, get_admin_url(), and null.
Referenced by get_dashboard_url(), get_delete_post_link(), get_edit_bookmark_link(), get_edit_comment_link(), get_edit_post_link(), get_edit_term_link(), get_shortcut_link(), network_admin_url(), and self_admin_url().
content_url ($path = '')
Retrieve the url to the content directory.
Since
2.6.0
Parameters
string $path Optional. Path relative to the content url.
Returns
string Content url link with optional path appended.
Filter the URL to the content directory.
Since
2.8.0
Parameters
string $url The complete URL to the content directory including scheme and path.
string $path Path relative to the URL to the content directory. Blank string if no path is specified.
Definition at line 3141 of file link-template.php.
References $path, $url, apply_filters(), and set_url_scheme().
Referenced by WP_Styles\_css_href(), WP_Scripts\do_item(), _WP_Editors\editor_settings(), and get_theme_root_uri().
edit_bookmark_link ($link = '', $before = '', $after = '', $bookmark = null)
Display edit bookmark (literally a URL external to blog) link anchor content.
Since
2.7.0
Parameters
string $link Optional. Anchor text.
string $before Optional. Display before edit link.
string $after Optional. Display after edit link.
int $bookmark Optional. Bookmark ID.
Filter the bookmark edit link anchor tag.
Since
2.7.0
Parameters
string $link Anchor tag for the edit link.
int $link_id Bookmark ID.
Definition at line 1471 of file link-template.php.
References $link, __, apply_filters(), current_user_can(), esc_url, get_bookmark(), and get_edit_bookmark_link().
edit_comment_link ($text = null, $before = '', $after = '')
Display edit comment link with formatting.
Since
1.0.0
Parameters
string $text Optional. Anchor text.
string $before Optional. Display before edit link.
string $after Optional. Display after edit link.
Filter the comment edit link anchor tag.
Since
2.3.0
Parameters
string $link Anchor tag for the edit link.
int $comment_id Comment ID.
string $text Anchor text.
Definition at line 1409 of file link-template.php.
References $comment, $link, $text, __, apply_filters(), current_user_can(), esc_url, get_comment(), get_edit_comment_link(), and null.
Referenced by Walker_Comment\comment(), Walker_Comment\html5_comment(), and Walker_Comment\ping().
edit_post_link ($text = null, $before = '', $after = '', $id = 0, $class = 'post-edit-link')
Display edit post link for post.
Since
1.0.0
4.4.0 The $class argument was added.
Parameters
string $text Optional. Anchor text.
string $before Optional. Display before edit link.
string $after Optional. Display after edit link.
int $id Optional. Post ID.
string $class Optional. Add custom class to link.
Filter the post edit link anchor tag.
Since
2.3.0
Parameters
string $link Anchor tag for the edit link.
int $post_id Post ID.
string $text Anchor text.
Definition at line 1305 of file link-template.php.
References $class, $id, $link, $post, $text, $url, __, apply_filters(), esc_attr(), esc_url, get_edit_post_link(), get_post(), and null.
edit_tag_link ($link = '', $before = '', $after = '', $tag = null)
Display or retrieve edit tag link with formatting.
Since
2.7.0
Parameters
string $link Optional. Anchor text.
string $before Optional. Display before edit link.
string $after Optional. Display after edit link.
object $tag Tag object.
Filter the anchor tag for the edit link for a tag (or term in another taxonomy).
Since
2.7.0
Parameters
string $link The anchor tag for the edit link.
Definition at line 893 of file link-template.php.
References $link, apply_filters(), and edit_term_link().
edit_term_link ($link = '', $before = '', $after = '', $term = null, $echo = true)
Display or retrieve edit term link with formatting.
Since
3.1.0
Parameters
string $link Optional. Anchor text. Default empty.
string $before Optional. Display before edit link. Default empty.
string $after Optional. Display after edit link. Default empty.
object $term Optional. Term object. If null, the queried object will be inspected. Default null.
bool $echo Optional. Whether or not to echo the return. Default true.
Returns
string|void HTML content.
Filter the anchor tag for the edit link of a term.
Since
3.1.0
Parameters
string $link The anchor tag for the edit link.
int $term_id Term ID.
Definition at line 971 of file link-template.php.
References $link, $tax, __, apply_filters(), current_user_can(), get_edit_term_link(), get_queried_object(), and get_taxonomy().
Referenced by edit_tag_link().
get_adjacent_post ($in_same_term = false, $excluded_terms = '', $previous = true, $taxonomy = 'category')
Retrieve adjacent post.
Can either be next or previous post.
Since
2.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
bool $in_same_term Optional. Whether post should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
bool $previous Optional. Whether to retrieve previous post.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Returns
null|string|WP_Post Post object if successful. Null if global $post is not set. Empty string if no corresponding post exists.
Filter the IDs of terms excluded from adjacent post queries.
The dynamic portion of the hook name, $adjacent, refers to the type of adjacency, 'next' or 'previous'.
Since
4.4.0
Parameters
string $excluded_terms Array of excluded term IDs.
Filter the JOIN clause in the SQL for an adjacent post query.
The dynamic portion of the hook name, $adjacent, refers to the type of adjacency, 'next' or 'previous'.
Since
2.5.0
4.4.0 Added the $taxonomy and $post parameters.
Parameters
string $join The JOIN clause in the SQL.
bool $in_same_term Whether post should be in a same taxonomy term.
array $excluded_terms Array of excluded term IDs.
string $taxonomy Taxonomy. Used to identify the term used when $in_same_term is true.
WP_Post $post WP_Post object.
Filter the WHERE clause in the SQL for an adjacent post query.
The dynamic portion of the hook name, $adjacent, refers to the type of adjacency, 'next' or 'previous'.
Since
2.5.0
4.4.0 Added the $taxonomy and $post parameters.
Parameters
string $where The WHERE clause in the SQL.
bool $in_same_term Whether post should be in a same taxonomy term.
array $excluded_terms Array of excluded term IDs.
string $taxonomy Taxonomy. Used to identify the term used when $in_same_term is true.
WP_Post $post WP_Post object.
Filter the ORDER BY clause in the SQL for an adjacent post query.
The dynamic portion of the hook name, $adjacent, refers to the type of adjacency, 'next' or 'previous'.
Since
2.5.0
4.4.0 Added the $post parameter.
Parameters
string $order_by The ORDER BY clause in the SQL.
WP_Post $post WP_Post object.
Definition at line 1574 of file link-template.php.
References $post, $post_type_object, $user_id, $wpdb, __, _deprecated_argument(), apply_filters(), current_user_can(), get_current_user_id(), get_post(), get_post_stati(), get_post_type_object(), is_object_in_taxonomy(), is_wp_error(), null, taxonomy_exists(), wp_cache_get(), wp_cache_set(), and wp_get_object_terms().
Referenced by get_adjacent_post_link(), get_adjacent_post_rel_link(), get_next_post(), get_previous_post(), and twentyfifteen_post_nav_background().
get_adjacent_post_link ($format, $link, $in_same_term = false, $excluded_terms = '', $previous = true, $taxonomy = 'category')
Get adjacent post link.
Can be either next post link or previous.
Since
3.7.0
Parameters
string $format Link anchor format.
string $link Link permalink format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded terms IDs.
bool $previous Optional. Whether to display link to previous or next post. Default true.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Returns
string The link URL of the previous or next post in relation to the current post.
This filter is documented in wp-includes/post-template.php
Filter the adjacent post link.
The dynamic portion of the hook name, $adjacent, refers to the type of adjacency, 'next' or 'previous'.
Since
2.6.0
4.2.0 Added the $adjacent parameter.
Parameters
string $output The adjacent post link.
string $format Link anchor format.
string $link Link permalink format.
WP_Post $post The adjacent post.
string $adjacent Whether the post is previous or next.
Definition at line 1982 of file link-template.php.
References $format, $link, $output, $post, $title, __, apply_filters(), get_adjacent_post(), get_option(), get_permalink(), get_post(), is_attachment(), mysql2date(), and str_replace.
Referenced by adjacent_post_link(), get_next_post_link(), and get_previous_post_link().
get_adjacent_post_rel_link ($title = '%title', $in_same_term = false, $excluded_terms = '', $previous = true, $taxonomy = 'category')
Get adjacent post relational link.
Can either be next or previous post relational link.
Since
2.8.0
Parameters
string $title Optional. Link title format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
bool $previous Optional. Whether to display link to previous or next post. Default true.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Returns
string|void The adjacent post relational link URL.
Filter the adjacent post relational link.
The dynamic portion of the hook name, $adjacent, refers to the type of adjacency, 'next' or 'previous'.
Since
2.8.0
Parameters
string $link The relational link.
Definition at line 1750 of file link-template.php.
References $link, $post, $post_title, $title, __, apply_filters(), esc_attr(), get_adjacent_post(), get_option(), get_permalink(), get_post(), is_attachment(), mysql2date(), str_replace, and the_title_attribute().
Referenced by adjacent_posts_rel_link(), next_post_rel_link(), and prev_post_rel_link().
get_admin_url ($blog_id = null, $path = '', $scheme = 'admin')
Retrieves the url to the admin area for a given site.
Since
3.0.0
Parameters
int $blog_id Optional. Blog ID. Default null (current site).
string $path Optional. Path relative to the admin url. Default empty.
string $scheme Optional. The scheme to use. Accepts 'http' or 'https', to force those schemes. Default 'admin', which obeys {
See also
force_ssl_admin()} and {
is_ssl()}.
Returns
string Admin url link with optional path appended.
Filter the admin area URL.
Since
2.8.0
Parameters
string $url The complete admin area URL including scheme and path.
string $path Path relative to the admin area URL. Blank string if no path is specified.
int | null $blog_id Blog ID, or null for the current blog.
Definition at line 3088 of file link-template.php.
References $blog_id, $path, $url, apply_filters(), and get_site_url().
Referenced by _access_denied_splash(), admin_url(), get_dashboard_url(), WP_MS_Sites_List_Table\handle_row_actions(), wp_xmlrpc_server\initialise_blog_option_info(), and wp_admin_bar_my_sites_menu().
get_attachment_link ($post = null, $leavename = false)
Retrieve permalink for attachment.
This can be used in the WordPress Loop or outside of it.
Since
2.0.0
WP_Rewrite $wp_rewrite
Parameters
int | object $post Optional. Post ID or object.
bool $leavename Optional. Leave name.
Returns
string The attachment permalink.
Filter the permalink for an attachment.
Since
2.0.0
Parameters
string $link The attachment's permalink.
int $post_id Attachment ID.
Definition at line 387 of file link-template.php.
References $link, $name, $post, $wp_rewrite, _get_page_link(), apply_filters(), elseif, get_option(), get_permalink(), get_post(), get_post_types(), home_url(), str_replace, trailingslashit(), and user_trailingslashit().
Referenced by _fix_attachment_links(), get_permalink(), get_the_attachment_link(), image_link_input_fields(), image_media_send_to_editor(), media_upload_form_handler(), redirect_canonical(), wp_ajax_send_attachment_to_editor(), wp_get_attachment_link(), and wp_prepare_attachment_for_js().
get_author_feed_link ($author_id, $feed = '')
Retrieve the feed link for a given author.
Returns a link to the feed for all posts by a given author. A specific feed can be requested or left blank to get the default feed.
Since
2.5.0
Parameters
int $author_id ID of an author.
string $feed Optional. Feed type.
Returns
string Link to the feed for the author specified by $author_id.
Filter the feed link for a given author.
Since
1.5.1
Parameters
string $link The author feed link.
string $feed Feed type.
Definition at line 720 of file link-template.php.
References $link, $permalink_structure, apply_filters(), get_author_posts_url(), get_default_feed(), get_option(), home_url(), trailingslashit(), and user_trailingslashit().
Referenced by feed_links_extra(), get_author_rss_link(), and wp_list_authors().
get_avatar_data ($id_or_email, $args = null)
Retrieve default data about the avatar.
Since
4.2.0
Parameters
mixed $id_or_email The Gravatar to retrieve. Accepts a user_id, gravatar md5 hash, user email, WP_User object, WP_Post object, or WP_Comment object.
array $args { Optional. Arguments to return instead of the default arguments.
int $size Height and width of the avatar image file in pixels. Default 96. int $height Display height of the avatar in pixels. Defaults to $size. int $width Display width of the avatar in pixels. Defaults to $size. string $default URL for the default image or a default type. Accepts '404' (return a 404 instead of a default image), 'retro' (8bit), 'monsterid' (monster), 'wavatar' (cartoon face), 'indenticon' (the "quilt"), 'mystery', 'mm', or 'mysteryman' (The Oyster Man), 'blank' (transparent GIF), or 'gravatar_default' (the Gravatar logo). Default is the value of the 'avatar_default' option, with a fallback of 'mystery'. bool $force_default Whether to always show the default image, never the Gravatar. Default false. string $rating What rating to display avatars up to. Accepts 'G', 'PG', 'R', 'X', and are judged in that order. Default is the value of the 'avatar_rating' option. string $scheme URL scheme to use. See set_url_scheme() for accepted values. Default null. array $processed_args When the function returns, the value will be the processed/sanitized $args plus a "found_avatar" guess. Pass as a reference. Default null. string $extra_attr HTML attributes to insert in the IMG element. Is not sanitized. Default empty. }
Returns
array $processed_args { Along with the arguments passed in $args, this will contain a couple of extra arguments.
bool $found_avatar True if we were able to find an avatar for this user, false or not set if we couldn't. string $url The URL of the avatar we found. }
Filter whether to retrieve the avatar URL early.
Passing a non-null value in the 'url' member of the return array will effectively short circuit get_avatar_data(), passing the value through the {
See also
'get_avatar_data'} filter and returning early.
Since
4.2.0
Parameters
array $args Arguments passed to get_avatar_data(), after processing.
mixed $id_or_email The Gravatar to retrieve. Accepts a user_id, gravatar md5 hash, user email, WP_User object, WP_Post object, or WP_Comment object.
This filter is documented in wp-includes/link-template.php
Filter the list of allowed comment types for retrieving avatars.
Since
3.0.0
Parameters
array $types An array of content types. Default only contains 'comment'.
This filter is documented in wp-includes/link-template.php
Filter the avatar URL.
Since
4.2.0
Parameters
string $url The URL of the avatar.
mixed $id_or_email The Gravatar to retrieve. Accepts a user_id, gravatar md5 hash, user email, WP_User object, WP_Post object, or WP_Comment object.
array $args Arguments passed to get_avatar_data(), after processing.
Filter the avatar data.
Since
4.2.0
Parameters
array $args Arguments passed to get_avatar_data(), after processing.
mixed $id_or_email The Gravatar to retrieve. Accepts a user_id, gravatar md5 hash, user email, WP_User object, WP_Post object, or WP_Comment object.
Definition at line 3754 of file link-template.php.
References $url, $user, absint(), add_query_arg(), apply_filters(), elseif, get_comment(), get_option(), is_ssl(), is_wp_error(), null, rawurlencode_deep(), set_url_scheme(), and wp_parse_args().
Referenced by get_avatar_url().
get_avatar_url ($id_or_email, $args = null)
Retrieve the avatar URL.
Since
4.2.0
Parameters
mixed $id_or_email The Gravatar to retrieve a URL for. Accepts a user_id, gravatar md5 hash, user email, WP_User object, WP_Post object, or WP_Comment object.
array $args { Optional. Arguments to return instead of the default arguments.
int $size Height and width of the avatar in pixels. Default 96. string $default URL for the default image or a default type. Accepts '404' (return a 404 instead of a default image), 'retro' (8bit), 'monsterid' (monster), 'wavatar' (cartoon face), 'indenticon' (the "quilt"), 'mystery', 'mm', or 'mysteryman' (The Oyster Man), 'blank' (transparent GIF), or 'gravatar_default' (the Gravatar logo). Default is the value of the 'avatar_default' option, with a fallback of 'mystery'. bool $force_default Whether to always show the default image, never the Gravatar. Default false. string $rating What rating to display avatars up to. Accepts 'G', 'PG', 'R', 'X', and are judged in that order. Default is the value of the 'avatar_rating' option. string $scheme URL scheme to use. See set_url_scheme() for accepted values. Default null. array $processed_args When the function returns, the value will be the processed/sanitized $args plus a "found_avatar" guess. Pass as a reference. Default null. }
Returns
false|string The URL of the avatar we found, or false if we couldn't find an avatar.
Definition at line 3713 of file link-template.php.
References get_avatar_data().
get_boundary_post ($in_same_term = false, $excluded_terms = '', $start = true, $taxonomy = 'category')
Retrieve boundary post.
Boundary being either the first or last post by publish date within the constraints specified by $in_same_term or $excluded_terms.
Since
2.8.0
Parameters
bool $in_same_term Optional. Whether returned post should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
bool $start Optional. Whether to retrieve first or last post.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Returns
null|array Array containing the boundary post object if successful, null otherwise.
Definition at line 1859 of file link-template.php.
References $post, get_post(), get_posts(), is_attachment(), is_single(), null, taxonomy_exists(), and wp_get_object_terms().
Referenced by get_boundary_post_rel_link().
get_category_feed_link ($cat_id, $feed = '')
Retrieve the feed link for a category.
Returns a link to the feed for all posts in a given category. A specific feed can be requested or left blank to get the default feed.
Since
2.5.0
Parameters
int $cat_id ID of a category.
string $feed Optional. Feed type.
Returns
string Link to the feed for the category specified by $cat_id.
Definition at line 764 of file link-template.php.
References get_term_feed_link().
Referenced by feed_links_extra(), get_category_rss_link(), and wp_xmlrpc_server\mw_getCategories().
get_comments_pagenum_link ($pagenum = 1, $max_page = 0)
Retrieve comments page number link.
Since
2.7.0
WP_Rewrite $wp_rewrite
Parameters
int $pagenum Optional. Page number.
int $max_page Optional. The maximum number of comment pages.
Returns
string The comments page number link URL.
Filter the comments page number link for the current request.
Since
2.7.0
Parameters
string $result The comments page number link.
Definition at line 2590 of file link-template.php.
References $pagenum, $wp_rewrite, add_query_arg(), apply_filters(), elseif, get_option(), get_permalink(), trailingslashit(), and user_trailingslashit().
Referenced by get_next_comments_link(), get_previous_comments_link(), and rel_canonical().
get_dashboard_url ($user_id = 0, $path = '', $scheme = 'admin')
Get the URL to the user's dashboard.
If a user does not belong to any site, the global user dashboard is used. If the user belongs to the current site, the dashboard for the current site is returned. If the user cannot edit the current site, the dashboard to the user's primary blog is returned.
Since
3.1.0
Parameters
int $user_id Optional. User ID. Defaults to current user.
string $path Optional path relative to the dashboard. Use only paths known to both blog and user admins.
string $scheme The scheme to use. Default is 'admin', which obeys force_ssl_admin() and is_ssl(). 'http' or 'https' can be passed to force those schemes.
Returns
string Dashboard url link with optional path appended.
Filter the dashboard URL for a user.
Since
3.1.0
Parameters
string $url The complete URL including scheme and path.
int $user_id The user ID.
string $path Path relative to the URL. Blank string if no path is specified.
string $scheme Scheme to give the URL context. Accepts 'http', 'https', 'login', 'login_post', 'admin', 'relative' or null.
Definition at line 3433 of file link-template.php.
References $blogs, $current_blog, $path, $url, $user_id, admin_url(), apply_filters(), elseif, get_active_blog_for_user(), get_admin_url(), get_blogs_of_user(), get_current_blog_id(), get_current_user_id(), is_multisite(), is_super_admin(), and user_admin_url().
Referenced by get_edit_profile_url(), wp_admin_bar_dashboard_view_site_menu(), wp_admin_bar_my_account_item(), and wp_admin_bar_my_account_menu().
get_day_link ($year, $month, $day)
Retrieve the permalink for the day archives with year and month.
Since
1.0.0
WP_Rewrite $wp_rewrite
Parameters
bool | int $year False for current year. Integer of year.
bool | int $month False for current month. Integer of month.
bool | int $day False for current day. Integer of day.
Returns
string The permalink for the specified day, month, and year archive.
Filter the day archive permalink.
Since
1.5.0
Parameters
string $daylink Permalink for the day archive.
int $year Year for the archive.
int $month Month for the archive.
int $day The day for the archive.
Definition at line 515 of file link-template.php.
References $wp_rewrite, apply_filters(), current_time(), home_url(), str_replace, user_trailingslashit(), and zeroise().
Referenced by get_calendar(), redirect_canonical(), and wp_get_archives().
get_delete_post_link ($id = 0, $deprecated = '', $force_delete = false)
Retrieve delete posts link for post.
Can be used within the WordPress loop or outside of it, with any post type.
Since
2.9.0
Parameters
int $id Optional. Post ID.
string $deprecated Not used.
bool $force_delete Whether to bypass trash and force deletion. Default is false.
Returns
string|void The delete post link URL for the given post.
Filter the post delete link.
Since
2.9.0
Parameters
string $link The delete link.
int $post_id Post ID.
bool $force_delete Whether to bypass the trash and force deletion. Default false.
Definition at line 1344 of file link-template.php.
References $action, $deprecated, $id, $post, $post_type_object, _deprecated_argument(), add_query_arg(), admin_url(), apply_filters(), current_user_can(), get_post(), get_post_type_object(), and wp_nonce_url().
Referenced by attachment_submit_meta_box(), and WP_Posts_List_Table\handle_row_actions().
get_edit_bookmark_link ($link = 0)
Display edit bookmark (literally a URL external to blog) link.
Since
2.7.0
Parameters
int | stdClass $link Optional. Bookmark ID.
Returns
string|void The edit bookmark link URL.
Filter the bookmark (link) edit link.
Since
2.7.0
Parameters
string $location The edit link.
int $link_id Bookmark ID.
Definition at line 1442 of file link-template.php.
References $link, $location, admin_url(), apply_filters(), current_user_can(), and get_bookmark().
Referenced by WP_Links_List_Table\column_name(), edit_bookmark_link(), and WP_Links_List_Table\handle_row_actions().
get_edit_comment_link ($comment_id = 0)
Retrieve edit comment link.
Since
2.3.0
Parameters
int | WP_Comment $comment_id Optional. Comment ID or WP_Comment object.
Returns
string|void The edit comment link URL for the given comment.
Filter the comment edit link.
Since
2.3.0
Parameters
string $location The edit link.
Definition at line 1382 of file link-template.php.
References $comment, $location, admin_url(), apply_filters(), current_user_can(), and get_comment().
Referenced by edit_comment_link().
get_edit_post_link ($id = 0, $context = 'display')
Retrieve edit posts link for post.
Can be used within the WordPress loop or outside of it. Can be used with pages, posts, attachments, and revisions.
Since
2.3.0
Parameters
int $id Optional. Post ID.
string $context Optional, defaults to display. How to write the '&', defaults to '&'.
Returns
string|null The edit post link for the given post. null if the post type is invalid or does not allow an editing UI.
Filter the post edit link.
Since
2.3.0
Parameters
string $link The edit link.
int $post_id Post ID.
string $context The link context. If set to 'display' then ampersands are encoded.
Definition at line 1256 of file link-template.php.
References $action, $id, $link, $post, $post_type_object, admin_url(), apply_filters(), current_user_can(), elseif, get_post(), and get_post_type_object().
Referenced by WP_Media_List_Table\_get_row_actions(), _wp_dashboard_recent_comments_row(), WP_Comments_List_Table\column_response(), WP_Media_List_Table\column_title(), WP_Posts_List_Table\column_title(), edit_post_link(), WP_Posts_List_Table\handle_row_actions(), WP_Press_This\save_post(), wp_admin_bar_edit_menu(), wp_dashboard_recent_drafts(), wp_post_revision_title(), wp_post_revision_title_expanded(), and wp_prepare_attachment_for_js().
get_edit_profile_url ($user_id = 0, $scheme = 'admin')
Get the URL to the user's profile editor.
Since
3.1.0
Parameters
int $user_id Optional. User ID. Defaults to current user.
string $scheme The scheme to use. Default is 'admin', which obeys force_ssl_admin() and is_ssl(). 'http' or 'https' can be passed to force those schemes.
Returns
string Dashboard url link with optional path appended.
Filter the URL for a user's profile editor.
Since
3.1.0
Parameters
string $url The complete URL including scheme and path.
int $user_id The user ID.
string $scheme Scheme to give the URL context. Accepts 'http', 'https', 'login', 'login_post', 'admin', 'relative' or null.
Definition at line 3478 of file link-template.php.
References $url, $user_id, apply_filters(), elseif, get_current_user_id(), get_dashboard_url(), is_network_admin(), is_user_admin(), network_admin_url(), and user_admin_url().
Referenced by default_password_nag(), get_edit_user_link(), wp_admin_bar_my_account_item(), and wp_admin_bar_my_account_menu().
get_edit_tag_link ($tag_id, $taxonomy = 'post_tag')
Retrieve edit tag link.
Since
2.7.0
Parameters
int $tag_id Tag ID
string $taxonomy Taxonomy
Returns
string The edit tag link URL for the given tag.
Filter the edit link for a tag (or term in another taxonomy).
Since
2.7.0
Parameters
string $link The term edit link.
Definition at line 872 of file link-template.php.
References apply_filters(), and get_edit_term_link().
get_edit_term_link ($term_id, $taxonomy, $object_type = '')
Retrieve edit term url.
Since
3.1.0
Parameters
int $term_id Term ID.
string $taxonomy Taxonomy.
string $object_type The object type. Used to highlight the proper post type menu on the linked page. Defaults to the first object_type associated with the taxonomy.
Returns
string|null The edit term link URL for the given term, or null on failure.
Filter the edit link for a term.
Since
3.1.0
Parameters
string $location The edit link.
int $term_id Term ID.
string $taxonomy Taxonomy name.
string $object_type The object type (eg. the post type).
Definition at line 917 of file link-template.php.
References $location, $tax, add_query_arg(), admin_url(), apply_filters(), current_user_can(), elseif, get_taxonomy(), get_term(), and is_wp_error().
Referenced by WP_Terms_List_Table\column_name(), edit_term_link(), get_edit_tag_link(), WP_Terms_List_Table\handle_row_actions(), wp_admin_bar_edit_menu(), and wp_tag_cloud().
get_edit_user_link ($user_id = null)
Retrieve edit user link.
Since
3.5.0
Parameters
int $user_id Optional. User ID. Defaults to the current user.
Returns
string URL to edit user page or empty string.
Filter the user edit link.
Since
3.5.0
Parameters
string $link The edit link.
int $user_id User ID.
Definition at line 1501 of file link-template.php.
References $link, $user, $user_id, add_query_arg(), apply_filters(), current_user_can(), get_current_user_id(), get_edit_profile_url(), and self_admin_url().
Referenced by WP_MS_Users_List_Table\column_username(), comment_form(), WP_MS_Users_List_Table\handle_row_actions(), and WP_Users_List_Table\single_row().
get_feed_link ($feed = '')
Retrieve the permalink for the feed type.
Since
1.5.0
WP_Rewrite $wp_rewrite
Parameters
string $feed Optional, defaults to default feed. Feed type.
Returns
string The feed permalink.
Filter the feed type permalink.
Since
1.5.0
Parameters
string $output The feed permalink.
string $feed Feed type.
Definition at line 580 of file link-template.php.
References $output, $permalink, $wp_rewrite, apply_filters(), get_default_feed(), home_url(), str_replace, and user_trailingslashit().
Referenced by feed_links(), get_bloginfo(), redirect_canonical(), and the_feed_link().
get_home_url ($blog_id = null, $path = '', $scheme = null)
Retrieve the home url for a given site.
Returns the 'home' option with the appropriate protocol, 'https' if {
See also
is_ssl()} and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is overridden.
Since
3.0.0
string $pagenow
Parameters
int $blog_id Optional. Blog ID. Default null (current blog).
string $path Optional. Path relative to the home URL. Default empty.
string | null $scheme Optional. Scheme to give the home URL context. Accepts 'http', 'https', 'relative', 'rest', or null. Default null.
Returns
string Home URL link with optional path appended.
Filter the home URL.
Since
3.0.0
Parameters
string $url The complete home URL including scheme and path.
string $path Path relative to the home URL. Blank string if no path is specified.
string | null $orig_scheme Scheme to give the home URL context. Accepts 'http', 'https', 'relative', 'rest', or null.
int | null $blog_id Blog ID, or null for the current blog.
Definition at line 2963 of file link-template.php.
References $blog_id, $pagenow, $path, $url, apply_filters(), get_option(), is_admin(), is_multisite(), is_ssl(), restore_current_blog(), set_url_scheme(), and switch_to_blog().
Referenced by _access_denied_splash(), choose_primary_blog(), WP_MS_Users_List_Table\column_blogs(), confirm_delete_users(), get_oembed_response_data(), get_post_type_archive_link(), get_rest_url(), WP_MS_Sites_List_Table\handle_row_actions(), home_url(), WP_Admin_Bar\initialize(), install_blog(), options_general_add_js(), wp_admin_bar_my_sites_menu(), and wp_admin_bar_site_menu().
get_month_link ($year, $month)
Retrieve the permalink for the month archives with year.
Since
1.0.0
WP_Rewrite $wp_rewrite
Parameters
bool | int $year False for current year. Integer of year.
bool | int $month False for current month. Integer of month.
Returns
string The permalink for the specified month and year archive.
Filter the month archive permalink.
Since
1.5.0
Parameters
string $monthlink Permalink for the month archive.
int $year Year for the archive.
int $month The month for the archive.
Definition at line 476 of file link-template.php.
References $wp_rewrite, apply_filters(), current_time(), home_url(), str_replace, user_trailingslashit(), and zeroise().
Referenced by get_calendar(), redirect_canonical(), and wp_get_archives().
get_next_comments_link ($label = '', $max_page = 0)
Return the link to next comments page.
Since
2.7.1
WP_Query $wp_query
Parameters
string $label Optional. Label for link text.
int $max_page Optional. Max page.
Returns
string|void HTML-formatted link for the next page of comments.
Filter the anchor tag attributes for the next comments page link.
Since
2.7.0
Parameters
string $attributes Attributes for the anchor tag.
Definition at line 2634 of file link-template.php.
References $label, $page, __, apply_filters(), esc_url, get_comment_pages_count(), get_comments_pagenum_link(), get_query_var(), and is_singular().
Referenced by get_the_comments_navigation(), and next_comments_link().
get_next_post ($in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Retrieve next post that is adjacent to current post.
Since
1.5.0
Parameters
bool $in_same_term Optional. Whether post should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Returns
null|string|WP_Post Post object if successful. Null if global $post is not set. Empty string if no corresponding post exists.
Definition at line 1555 of file link-template.php.
References get_adjacent_post().
Referenced by next_post().
get_next_post_link ($format = '%link &raquo;', $link = '%title', $in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Get next post link that is adjacent to the current post.
Since
3.7.0
Parameters
string $format Optional. Link anchor format.
string $link Optional. Link permalink format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Returns
string The link URL of the next post in relation to the current post.
Definition at line 1947 of file link-template.php.
References $format, $link, and get_adjacent_post_link().
Referenced by get_the_post_navigation(), and next_post_link().
get_next_posts_link ($label = null, $max_page = 0)
Return the next posts page link.
Since
2.7.0
int $paged WP_Query $wp_query
Parameters
string $label Content for link text.
int $max_page Optional. Max pages.
Returns
string|void HTML-formatted next posts page link.
Filter the anchor tag attributes for the next posts page link.
Since
2.7.0
Parameters
string $attributes Attributes for the anchor tag.
Definition at line 2178 of file link-template.php.
References $label, $paged, __, apply_filters(), is_single(), next_posts(), and null.
Referenced by get_posts_nav_link(), get_the_posts_navigation(), and next_posts_link().
get_next_posts_page_link ($max_page = 0)
Retrieve next posts page link.
Backported from 2.1.3 to 2.0.10.
Since
2.0.10
int $paged
Parameters
int $max_page Optional. Max pages.
Returns
string|void The link URL for next posts page.
Definition at line 2136 of file link-template.php.
References $paged, get_pagenum_link(), and is_single().
Referenced by next_posts().
get_page_link ($post = false, $leavename = false, $sample = false)
Retrieve the permalink for current page or page ID.
Respects page_on_front. Use this one.
Since
1.5.0
Parameters
int | object $post Optional. Post ID or object.
bool $leavename Optional, defaults to false. Whether to keep page name.
bool $sample Optional, defaults to false. Is it a sample permalink.
Returns
string The page permalink.
Filter the permalink for a page.
Since
1.5.0
Parameters
string $link The page's permalink.
int $post_id The ID of the page.
bool $sample Is it a sample permalink.
Definition at line 308 of file link-template.php.
References $link, $post, _get_page_link(), apply_filters(), get_option(), get_post(), and home_url().
Referenced by get_permalink().
get_pagenum_link ($pagenum = 1, $escape = true)
Retrieve links for page numbers.
Since
1.5.0
WP_Rewrite $wp_rewrite
Parameters
int $pagenum Optional. Page ID.
bool $escape Optional. Whether to escape the URL for display, with esc_url(). Defaults to true. Otherwise, prepares the URL with esc_url_raw().
Returns
string The link URL for the given page number.
Filter the page number link for the current request.
Since
2.5.0
Parameters
string $result The page number link.
Definition at line 2060 of file link-template.php.
References $pagenum, $wp_rewrite, add_query_arg(), apply_filters(), esc_url, esc_url_raw(), get_bloginfo(), home_url(), is_admin(), remove_query_arg(), trailingslashit(), and user_trailingslashit().
Referenced by get_next_posts_page_link(), get_previous_posts_page_link(), and paginate_links().
get_permalink ($post = 0, $leavename = false)
Retrieve full permalink for current post or post ID.
Since
1.0.0
Parameters
int | WP_Post $post Optional. Post ID or post object. Default is the global $post.
bool $leavename Optional. Whether to keep post name or page name. Default false.
Returns
string|false The permalink URL or false if post does not exist.
Filter the permalink structure for a post before token replacement occurs.
Only applies to posts with post_type of 'post'.
Since
3.0.0
Parameters
string $permalink The site's permalink structure.
WP_Post $post The post in question.
bool $leavename Whether to keep the post name.
Filter the category that gets used in the category% permalink token.
Since
3.5.0
Parameters
stdClass $cat The category to use in the permalink.
array $cats Array of all categories associated with the post.
WP_Post $post The post in question.
Filter the permalink for a post.
Only applies to posts with post_type of 'post'.
Since
1.5.0
Parameters
string $permalink The post's permalink.
WP_Post $post The post in question.
bool $leavename Whether to keep the post name.
Definition at line 117 of file link-template.php.
References $cats, $permalink, $post, apply_filters(), date, elseif, get_attachment_link(), get_category_parents(), get_option(), get_page_link(), get_post(), get_post_permalink(), get_post_types(), get_term(), get_the_category(), home_url(), is_wp_error(), str_replace, and user_trailingslashit().
Referenced by WP_Media_List_Table\_get_row_actions(), wp_xmlrpc_server\_prepare_page(), wp_xmlrpc_server\_prepare_post(), _transition_post_status(), _wp_link_page(), WP_Comments_List_Table\column_response(), comment_form(), comments_popup_link(), GravityView_API\directory_link(), get_adjacent_post_link(), get_adjacent_post_rel_link(), get_attachment_link(), get_blog_permalink(), get_boundary_post_rel_link(), get_comment_link(), get_comment_reply_link(), get_comments_link(), get_comments_pagenum_link(), get_media_item(), get_parent_post_rel_link(), get_post_comments_feed_link(), get_post_embed_html(), get_post_embed_url(), get_post_reply_link(), get_post_type_archive_link(), get_preview_post_link(), get_sample_permalink(), get_sample_permalink_html(), GravityView_Widget_Search\get_search_form_action(), get_the_content(), get_the_permalink(), get_trackback_url(), gravityview_get_permalink_query_args(), GFFormDisplay\handle_confirmation(), WP_Posts_List_Table\handle_row_actions(), WP_Customize_Nav_Menus\load_available_items_query(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), paginate_comments_links(), pingback(), post_permalink(), redirect_canonical(), redirect_guess_404_permalink(), rel_canonical(), WP_Customize_Nav_Menus\search_available_items_query(), Walker_Page\start_el(), the_permalink(), the_permalink_rss(), trackback(), twentyeleven_get_first_url(), twentythirteen_get_link_url(), upgrade_130(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_admin_bar_edit_menu(), wp_embed_excerpt_more(), wp_get_archives(), wp_insert_post(), wp_install_maybe_enable_pretty_permalinks(), _WP_Editors\wp_link_query(), wp_list_categories(), wp_oembed_add_discovery_links(), wp_old_slug_redirect(), and wp_setup_nav_menu_item().
get_post_comments_feed_link ($post_id = 0, $feed = '')
Retrieve the permalink for the post comments feed.
Since
2.2.0
Parameters
int $post_id Optional. Post ID.
string $feed Optional. Feed type.
Returns
string The permalink for the comments feed for the given post.
Filter the post comments feed permalink.
Since
1.5.1
Parameters
string $url Post comments feed permalink.
Definition at line 626 of file link-template.php.
References $post, $post_id, $url, _get_page_link(), absint(), add_query_arg(), apply_filters(), elseif, get_default_feed(), get_option(), get_permalink(), get_post(), get_the_ID(), home_url(), if, trailingslashit(), and user_trailingslashit().
Referenced by comments_rss(), feed_links_extra(), post_comments_feed_link(), redirect_canonical(), and redirect_guess_404_permalink().
get_post_permalink ($id = 0, $leavename = false, $sample = false)
Retrieve the permalink for a post with a custom post type.
Since
3.0.0
WP_Rewrite $wp_rewrite
Parameters
int $id Optional. Post ID.
bool $leavename Optional, defaults to false. Whether to keep post name.
bool $sample Optional, defaults to false. Is it a sample permalink.
Returns
string|WP_Error The post permalink.
Filter the permalink for a post with a custom post type.
Since
3.0.0
Parameters
string $post_link The post's permalink.
WP_Post $post The post in question.
bool $leavename Whether to keep the post name.
bool $sample Is it a sample permalink.
Definition at line 250 of file link-template.php.
References $id, $post, $post_type, $wp_rewrite, add_query_arg(), apply_filters(), get_page_uri(), get_post(), get_post_status(), get_post_type_object(), home_url(), is_wp_error(), str_replace, and user_trailingslashit().
Referenced by get_permalink(), and WP_Press_This\save_post().
get_post_type_archive_feed_link ($post_type, $feed = '')
Retrieve the permalink for a post type archive feed.
Since
3.1.0
Parameters
string $post_type Post type
string $feed Optional. Feed type
Returns
string|false The post type feed permalink.
Filter the post type archive feed link.
Since
3.1.0
Parameters
string $link The post type archive feed link.
string $feed Feed type.
Definition at line 1174 of file link-template.php.
References $link, $post_type, add_query_arg(), apply_filters(), get_default_feed(), get_option(), get_post_type_archive_link(), get_post_type_object(), and trailingslashit().
Referenced by feed_links_extra().
get_post_type_archive_link ($post_type)
Retrieve the permalink for a post type archive.
Since
3.1.0
WP_Rewrite $wp_rewrite
Parameters
string $post_type Post type
Returns
string|false The post type archive permalink.
This filter is documented in wp-includes/link-template.php
Filter the post type archive permalink.
Since
3.1.0
Parameters
string $link The post type archive permalink.
string $post_type Post type name.
Definition at line 1122 of file link-template.php.
References $link, $post_type, $wp_rewrite, apply_filters(), get_home_url(), get_option(), get_permalink(), get_post_type_object(), home_url(), if, and user_trailingslashit().
Referenced by get_post_type_archive_feed_link(), WP_Customize_Nav_Menus\load_available_items_query(), wp_list_categories(), wp_nav_menu_item_post_type_meta_box(), and wp_setup_nav_menu_item().
get_posts_nav_link ($args = array())
Return post pages link navigation for previous and next pages.
Since
2.8.0
WP_Query $wp_query
Parameters
string | array $args Optional args.
Returns
string The posts link navigation.
Definition at line 2309 of file link-template.php.
References $paged, __, get_next_posts_link(), get_previous_posts_link(), get_query_var(), is_singular(), and wp_parse_args().
Referenced by posts_nav_link().
get_preview_post_link ($post = null, $query_args = array(), $preview_link = '')
Retrieve URL used for the post preview.
Get the preview post URL. Allows additional query args to be appended.
Since
4.4.0
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Defaults to global post.
array $query_args Optional. Array of additional query args to be appended to the link.
string $preview_link Optional. Base preview link to be used if it should differ from the post permalink.
Returns
string URL used for the post preview.
Filter the URL used for a post preview.
Since
2.0.5
4.0.0 Added the $post parameter.
Parameters
string $preview_link URL used for the post preview.
WP_Post $post Post object.
Definition at line 1215 of file link-template.php.
References $post, $post_type_object, add_query_arg(), apply_filters(), get_permalink(), get_post(), get_post_type_object(), and is_post_type_viewable().
Referenced by _wp_link_page(), get_sample_permalink_html(), WP_Posts_List_Table\handle_row_actions(), post_submit_meta_box(), wp_admin_bar_edit_menu(), and wp_ajax_get_permalink().
get_previous_comments_link ($label = '')
Return the previous comments page link.
Since
2.7.1
Parameters
string $label Optional. Label for comments link text.
Returns
string|void HTML-formatted link for the previous page of comments.
Filter the anchor tag attributes for the previous comments page link.
Since
2.7.0
Parameters
string $attributes Attributes for the anchor tag.
Definition at line 2690 of file link-template.php.
References $label, $page, __, apply_filters(), esc_url, get_comments_pagenum_link(), get_query_var(), and is_singular().
Referenced by get_the_comments_navigation(), and previous_comments_link().
get_previous_post ($in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Retrieve previous post that is adjacent to current post.
Since
1.5.0
Parameters
bool $in_same_term Optional. Whether post should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Returns
null|string|WP_Post Post object if successful. Null if global $post is not set. Empty string if no corresponding post exists.
Definition at line 1541 of file link-template.php.
References get_adjacent_post().
Referenced by previous_post().
get_previous_post_link ($format = '&laquo; %link', $link = '%title', $in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Get previous post link that is adjacent to the current post.
Since
3.7.0
Parameters
string $format Optional. Link anchor format.
string $link Optional. Link permalink format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Returns
string The link URL of the previous post in relation to the current post.
Definition at line 1915 of file link-template.php.
References $format, $link, and get_adjacent_post_link().
Referenced by get_the_post_navigation(), and previous_post_link().
get_previous_posts_link ($label = null)
Return the previous posts page link.
Since
2.7.0
int $paged
Parameters
string $label Optional. Previous page link text.
Returns
string|void HTML-formatted previous page link.
Filter the anchor tag attributes for the previous posts page link.
Since
2.7.0
Parameters
string $attributes Attributes for the anchor tag.
Definition at line 2269 of file link-template.php.
References $label, $paged, __, apply_filters(), is_single(), null, and previous_posts().
Referenced by get_posts_nav_link(), get_the_posts_navigation(), and previous_posts_link().
get_previous_posts_page_link ()
Retrieve previous posts page link.
Will only return string, if not on a single page or post.
Backported to 2.0.10 from 2.1.3.
Since
2.0.10
int $paged
Returns
string|void The link for the previous posts page.
Definition at line 2231 of file link-template.php.
References $paged, get_pagenum_link(), and is_single().
Referenced by previous_posts().
get_search_comments_feed_link ($search_query = '', $feed = '')
Retrieve the permalink for the comments feed of the search results.
Since
2.5.0
WP_Rewrite $wp_rewrite
Parameters
string $search_query Optional. Search query.
string $feed Optional. Feed type.
Returns
string The comments feed search results permalink.
This filter is documented in wp-includes/link-template.php
Definition at line 1093 of file link-template.php.
References $link, $wp_rewrite, add_query_arg(), apply_filters(), get_default_feed(), and get_search_feed_link().
get_search_feed_link ($search_query = '', $feed = '')
Retrieve the permalink for the feed of the search results.
Since
2.5.0
WP_Rewrite $wp_rewrite
Parameters
string $search_query Optional. Search query.
string $feed Optional. Feed type.
Returns
string The search results feed permalink.
Filter the search feed link.
Since
2.5.0
Parameters
string $link Search feed link.
string $feed Feed type.
string $type The search type. One of 'posts' or 'comments'.
Definition at line 1054 of file link-template.php.
References $link, $wp_rewrite, add_query_arg(), apply_filters(), get_default_feed(), get_search_link(), and trailingslashit().
Referenced by feed_links_extra(), and get_search_comments_feed_link().
get_search_link ($query = '')
Retrieve permalink for search.
Since
3.0.0
WP_Rewrite $wp_rewrite
Parameters
string $query Optional. The query string to use. If empty the current query is used.
Returns
string The search permalink.
Filter the search permalink.
Since
3.0.0
Parameters
string $link Search permalink.
string $search The URL-encoded search term.
Definition at line 1013 of file link-template.php.
References $link, $wp_rewrite, apply_filters(), get_search_query(), home_url(), str_replace, and user_trailingslashit().
Referenced by get_search_feed_link().
get_shortcut_link ()
Retrieve the Press This bookmarklet link.
Use this in 'a' element 'href' attribute.
Since
2.6.0
bool $is_IE string $wp_version WP_Press_This $wp_press_this
Returns
string The Press This bookmarklet link URL.
Return the old/shorter bookmarklet code for MSIE 8 and lower, since they only support a max length of ~2000 characters for bookmark[let] URLs, which is way to small for our smarter one. Do update the version number so users do not get the "upgrade your bookmarklet" notice when using PT in those browsers.
Filter the Press This bookmarklet link.
Since
2.6.0
Parameters
string $link The Press This bookmarklet link.
Definition at line 2878 of file link-template.php.
References $_SERVER, $GLOBALS, $is_IE, $link, $url, $wp_version, ABSPATH, admin_url(), apply_filters(), str_replace, and wp_json_encode().
get_site_url ($blog_id = null, $path = '', $scheme = null)
Retrieve the site url for a given site.
Returns the 'site_url' option with the appropriate protocol, 'https' if {
See also
is_ssl()} and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is overridden.
Since
3.0.0
Parameters
int $blog_id Optional. Blog ID. Default null (current site).
string $path Optional. Path relative to the site url. Default empty.
string $scheme Optional. Scheme to give the site url context. Accepts 'http', 'https', 'login', 'login_post', 'admin', or 'relative'. Default null.
Returns
string Site url link with optional path appended.
Filter the site URL.
Since
2.7.0
Parameters
string $url The complete site URL including scheme and path.
string $path Path relative to the site URL. Blank string if no path is specified.
string | null $scheme Scheme to give the site URL context. Accepts 'http', 'https', 'login', 'login_post', 'admin', 'relative' or null.
int | null $blog_id Blog ID, or null for the current blog.
Definition at line 3035 of file link-template.php.
References $blog_id, $path, $url, apply_filters(), get_option(), is_multisite(), restore_current_blog(), set_url_scheme(), and switch_to_blog().
Referenced by get_admin_url(), and site_url().
get_tag_feed_link ($tag_id, $feed = '')
Retrieve permalink for feed of tag.
Since
2.3.0
Parameters
int $tag_id Tag ID.
string $feed Optional. Feed type.
Returns
string The feed permalink for the given tag.
Definition at line 859 of file link-template.php.
References get_term_feed_link().
Referenced by feed_links_extra(), and wp_xmlrpc_server\wp_getTags().
get_term_feed_link ($term_id, $taxonomy = 'category', $feed = '')
Retrieve the feed link for a term.
Returns a link to the feed for all posts in a given term. A specific feed can be requested or left blank to get the default feed.
Since
3.0.0
Parameters
int $term_id ID of a category.
string $taxonomy Optional. Taxonomy of $term_id
string $feed Optional. Feed type.
Returns
string|false Link to the feed for the term specified by $term_id and $taxonomy.
Filter the category feed link.
Since
1.5.1
Parameters
string $link The category feed link.
string $feed Feed type.
Filter the post tag feed link.
Since
2.3.0
Parameters
string $link The tag feed link.
string $feed Feed type.
Filter the feed link for a taxonomy other than 'category' or 'post_tag'.
Since
3.0.0
Parameters
string $link The taxonomy feed link.
string $feed Feed type.
string $feed The taxonomy name.
Definition at line 781 of file link-template.php.
References $link, $permalink_structure, apply_filters(), elseif, get_default_feed(), get_option(), get_taxonomy(), get_term(), get_term_link(), home_url(), is_wp_error(), trailingslashit(), and user_trailingslashit().
Referenced by get_category_feed_link(), get_tag_feed_link(), and Walker_Category\start_el().
get_the_comments_navigation ($args = array())
Returns navigation to next/previous set of comments when applicable.
Since
4.4.0
Parameters
array $args { Optional. Default comments navigation arguments.
string $prev_text Anchor text to display in the previous comments link. Default 'Older comments'. string $next_text Anchor text to display in the next comments link. Default 'Newer comments'. string $screen_reader_text Screen reader text for nav element. Default 'Comments navigation'. }
Returns
string Markup for comments links.
Definition at line 2780 of file link-template.php.
References __, _navigation_markup(), get_comment_pages_count(), get_next_comments_link(), get_previous_comments_link(), and wp_parse_args().
Referenced by the_comments_navigation().
get_the_comments_pagination ($args = array())
Returns a paginated navigation to next/previous set of comments, when applicable.
Since
4.4.0
See also
paginate_comments_links()
Parameters
array $args { Optional. Default pagination arguments.
string $screen_reader_text Screen reader text for nav element. Default 'Comments navigation'. }
Returns
string Markup for pagination links.
Definition at line 2834 of file link-template.php.
References __, _navigation_markup(), paginate_comments_links(), and wp_parse_args().
Referenced by the_comments_pagination().
get_the_permalink ($post = 0, $leavename = false)
Retrieve full permalink for current post or post ID.
This function is an alias for get_permalink().
Since
3.9.0
See also
get_permalink()
Parameters
int | WP_Post $post Optional. Post ID or post object. Default is the global $post.
bool $leavename Optional. Whether to keep post name or page name. Default false.
Returns
string|false The permalink URL or false if post does not exist.
Definition at line 104 of file link-template.php.
References $post, and get_permalink().
get_the_post_navigation ($args = array())
Return navigation to next/previous post when applicable.
Since
4.1.0
4.4.0 Introduced the in_same_term, excluded_terms, and taxonomy arguments.
Parameters
array $args { Optional. Default post navigation arguments. Default empty array.
string $prev_text Anchor text to display in the previous post link. Default 'title'. string $next_text Anchor text to display in the next post link. Default 'title'. bool $in_same_term Whether link should be in a same taxonomy term. Default false. array|string $excluded_terms Array or comma-separated list of excluded term IDs. Default empty. string $taxonomy Taxonomy, if $in_same_term is true. Default 'category'. string $screen_reader_text Screen reader text for nav element. Default 'Post navigation'. }
Returns
string Markup for post links.
Definition at line 2372 of file link-template.php.
References __, _navigation_markup(), get_next_post_link(), get_previous_post_link(), and wp_parse_args().
Referenced by the_post_navigation().
get_the_posts_navigation ($args = array())
Return navigation to next/previous set of posts when applicable.
Since
4.1.0
WP_Query $wp_query WordPress Query object.
Parameters
array $args { Optional. Default posts navigation arguments. Default empty array.
string $prev_text Anchor text to display in the previous posts link. Default 'Older posts'. string $next_text Anchor text to display in the next posts link. Default 'Newer posts'. string $screen_reader_text Screen reader text for nav element. Default 'Posts navigation'. }
Returns
string Markup for posts links.
Definition at line 2439 of file link-template.php.
References $GLOBALS, __, _navigation_markup(), get_next_posts_link(), get_previous_posts_link(), and wp_parse_args().
Referenced by the_posts_navigation().
get_the_posts_pagination ($args = array())
Return a paginated navigation to next/previous set of posts, when applicable.
Since
4.1.0
Parameters
array $args { Optional. Default pagination arguments, {
See also
paginate_links()}.
string $screen_reader_text Screen reader text for navigation element. Default 'Posts navigation'. }
Returns
string Markup for pagination links.
Definition at line 2493 of file link-template.php.
References $GLOBALS, __, _navigation_markup(), _x, paginate_links(), and wp_parse_args().
Referenced by the_posts_pagination().
get_year_link ($year)
Retrieve the permalink for the year archives.
Since
1.5.0
WP_Rewrite $wp_rewrite
Parameters
int | bool $year False for current year or year for permalink.
Returns
string The permalink for the specified year archive.
Filter the year archive permalink.
Since
1.5.0
Parameters
string $yearlink Permalink for the year archive.
int $year Year for the archive.
Definition at line 442 of file link-template.php.
References $wp_rewrite, apply_filters(), current_time(), home_url(), str_replace, and user_trailingslashit().
Referenced by redirect_canonical(), and wp_get_archives().
home_url ($path = '', $scheme = null)
Retrieve the home url for the current site.
Returns the 'home' option with the appropriate protocol, 'https' if {
See also
is_ssl()} and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is overridden.
Since
3.0.0
Parameters
string $path Optional. Path relative to the home url. Default empty.
string | null $scheme Optional. Scheme to give the home url context. Accepts 'http', 'https', 'relative', 'rest', or null. Default null.
Returns
string Home url link with optional path appended.
Definition at line 2941 of file link-template.php.
References $path, get_home_url(), and null.
Referenced by _get_page_link(), get_attachment_link(), get_author_feed_link(), get_day_link(), get_feed_link(), get_month_link(), get_page_link(), get_pagenum_link(), get_permalink(), get_post_comments_feed_link(), get_post_permalink(), get_post_type_archive_link(), get_search_link(), get_term_feed_link(), get_year_link(), network_home_url(), and wp_get_shortlink().
includes_url ($path = '', $scheme = null)
Retrieve the url to the includes directory.
Since
2.6.0
Parameters
string $path Optional. Path relative to the includes url.
string $scheme Optional. Scheme to give the includes url context.
Returns
string Includes url link with optional path appended.
Filter the URL to the includes directory.
Since
2.8.0
Parameters
string $url The complete URL to the includes directory including scheme and path.
string $path Path relative to the URL to the wp-includes directory. Blank string if no path is specified.
Definition at line 3115 of file link-template.php.
References $path, $url, apply_filters(), site_url(), and WPINC.
network_admin_url ($path = '', $scheme = 'admin')
Retrieve the url to the admin area for the network.
Since
3.0.0
Parameters
string $path Optional path relative to the admin url.
string $scheme The scheme to use. Default is 'admin', which obeys force_ssl_admin() and is_ssl(). 'http' or 'https' can be passed to force those schemes.
Returns
string Admin url link with optional path appended.
Filter the network admin URL.
Since
3.0.0
Parameters
string $url The complete network admin URL including scheme and path.
string $path Path relative to the network admin URL. Blank string if no path is specified.
Definition at line 3306 of file link-template.php.
References $path, $url, admin_url(), apply_filters(), is_multisite(), and network_site_url().
Referenced by WP_MS_Users_List_Table\column_blogs(), WP_MS_Sites_List_Table\column_users(), core_update_footer(), get_edit_profile_url(), WP_MS_Users_List_Table\get_views(), WP_MS_Users_List_Table\handle_row_actions(), WP_MS_Sites_List_Table\handle_row_actions(), newblog_notify_siteadmin(), newuser_notify_siteadmin(), WP_Themes_List_Table\no_items(), self_admin_url(), WP_Automatic_Updater\send_email(), WP_Plugins_List_Table\single_row(), site_admin_notice(), update_nag(), update_right_now_message(), wp_admin_bar_my_sites_menu(), wp_admin_bar_site_menu(), wp_admin_bar_updates_menu(), wp_ajax_query_themes(), wp_link_manager_disabled_message(), and wp_network_dashboard_right_now().
network_home_url ($path = '', $scheme = null)
Retrieves the home url for the current network.
Returns the home url with the appropriate protocol, 'https' {
See also
is_ssl()} and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is overridden.
Since
3.0.0
Parameters
string $path Optional. Path relative to the home url. Default empty.
string $scheme Optional. Scheme to give the home url context. Accepts 'http', 'https', or 'relative'. Default null.
Returns
string Home url link with optional path appended.
Filter the network home URL.
Since
3.0.0
Parameters
string $url The complete network home URL including scheme and path.
string $path Path relative to the network home URL. Blank string if no path is specified.
string | null $orig_scheme Scheme to give the URL context. Accepts 'http', 'https', 'relative' or null.
Definition at line 3265 of file link-template.php.
References $current_site, $path, $url, apply_filters(), get_current_site(), home_url(), is_admin(), is_multisite(), is_ssl(), and set_url_scheme().
Referenced by export_wp(), get_blogaddress_by_name(), login_header(), maybe_redirect_404(), retrieve_password(), send_confirmation_on_profile_email(), WP_Automatic_Updater\send_debug_email(), and update_option_new_admin_email().
network_site_url ($path = '', $scheme = null)
Retrieve the site url for the current network.
Returns the site url with the appropriate protocol, 'https' if is_ssl() and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is overridden.
Since
3.0.0
Parameters
string $path Optional. Path relative to the site url.
string $scheme Optional. Scheme to give the site url context. See set_url_scheme().
Returns
string Site url link with optional path appended.
Filter the network site URL.
Since
3.0.0
Parameters
string $url The complete network site URL including scheme and path.
string $path Path relative to the network site URL. Blank string if no path is specified.
string | null $scheme Scheme to give the URL context. Accepts 'http', 'https', 'relative' or null.
Definition at line 3223 of file link-template.php.
References $current_site, $path, $url, apply_filters(), get_current_site(), is_multisite(), set_url_scheme(), and site_url().
Referenced by network_admin_url(), redirect_canonical(), retrieve_password(), user_admin_url(), wp_lostpassword_url(), wp_version_check(), and wpmu_signup_blog_notification().
next_comments_link ($label = '', $max_page = 0)
Display the link to next comments page.
Since
2.7.0
Parameters
string $label Optional. Label for link text.
int $max_page Optional. Max page.
Definition at line 2678 of file link-template.php.
References $label, and get_next_comments_link().
next_post_link ($format = '%link &raquo;', $link = '%title', $in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Display next post link that is adjacent to the current post.
Since
1.5.0
See also
get_next_post_link()
Parameters
string $format Optional. Link anchor format.
string $link Optional. Link permalink format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Definition at line 1963 of file link-template.php.
References $format, $link, and get_next_post_link().
next_post_rel_link ($title = '%title', $in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Display relational link for the next post adjacent to the current post.
Since
2.8.0
Parameters
string $title Optional. Link title format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Definition at line 1827 of file link-template.php.
References $title, and get_adjacent_post_rel_link().
next_posts ($max_page = 0, $echo = true)
Display or return the next posts page link.
Since
0.71
Parameters
int $max_page Optional. Max pages.
bool $echo Optional. Echo or return;
Returns
string|void The link URL for next posts page if $echo = false.
Definition at line 2157 of file link-template.php.
References $output, esc_url, and get_next_posts_page_link().
Referenced by get_next_posts_link().
next_posts_link ($label = null, $max_page = 0)
Display the next posts page link.
Since
0.71
Parameters
string $label Content for link text.
int $max_page Optional. Max pages.
Definition at line 2214 of file link-template.php.
References $label, and get_next_posts_link().
paginate_comments_links ($args = array())
Create pagination links for the comments on the current post.
See also
paginate_links()
Since
2.7.0
WP_Rewrite $wp_rewrite
Parameters
string | array $args Optional args. See paginate_links().
Returns
string|void Markup for pagination links.
Definition at line 2736 of file link-template.php.
References $page, $wp_rewrite, add_query_arg(), get_comment_pages_count(), get_permalink(), get_query_var(), is_singular(), paginate_links(), trailingslashit(), user_trailingslashit(), and wp_parse_args().
Referenced by get_the_comments_pagination().
permalink_anchor ($mode = 'id')
Display permalink anchor for current post.
The permalink mode title will use the post title for the 'a' element 'id' attribute. The id mode uses 'post-' with the post ID for the 'id' attribute.
Since
0.71
Parameters
string $mode Permalink mode can be either 'title', 'id', or default, which is 'id'.
Definition at line 76 of file link-template.php.
References $mode, $post, $title, get_post(), and sanitize_title().
plugins_url ($path = '', $plugin = '')
Retrieve a URL within the plugins or mu-plugins directory.
Defaults to the plugins directory URL if no arguments are supplied.
Since
2.6.0
Parameters
string $path Optional. Extra path appended to the end of the URL, including the relative directory if $plugin is supplied. Default empty.
string $plugin Optional. A full path to a file inside a plugin or mu-plugin. The URL will be relative to its directory. Default empty. Typically this is done by passing __FILE__ as the argument.
Returns
string Plugins URL link with optional paths appended.
Filter the URL to the plugins directory.
Since
2.8.0
Parameters
string $url The complete URL to the plugins directory including scheme and path.
string $path Path relative to the URL to the plugins directory. Blank string if no path is specified.
string $plugin The plugin file path to be relative to. Blank string if no plugin is specified.
Definition at line 3173 of file link-template.php.
References $path, $plugin, $url, apply_filters(), plugin_basename(), set_url_scheme(), and wp_normalize_path().
Referenced by GravityView_Default_Template_List\__construct(), GravityView_Preset_Business_Data\__construct(), GravityView_Preset_Staff_Profiles\__construct(), GravityView_Preset_Website_Showcase\__construct(), GravityView_Preset_Business_Listings\__construct(), GravityView_Preset_Event_Listings\__construct(), GravityView_Preset_Issue_Tracker\__construct(), GravityView_Preset_Job_Board\__construct(), GravityView_Preset_Profiles\__construct(), GravityView_Preset_Resume_Board\__construct(), GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Views\add_scripts_and_styles(), GravityView_frontend\add_scripts_and_styles(), GravityView_Recent_Entries_Widget\admin_enqueue_scripts(), GravityView_Settings\app_settings_fields(), GravityView_Entry_Notes\filter_avatar(), GFAddOn\get_base_url(), GFAddOn\get_gfaddon_base_url(), get_theme_root_uri(), GravityView_Support_Port\maybe_enqueue_script(), plugin_dir_url(), and GravityView_Settings\styles().
post_comments_feed_link ($link_text = '', $post_id = '', $feed = '')
Display the comment feed link for a post.
Prints out the comment feed link for a post. Link text is placed in the anchor. If no link text is specified, default text is used. If no post ID is specified, the current post is used.
Since
2.5.0
Parameters
string $link_text Descriptive text.
int $post_id Optional post ID. Default to current post.
string $feed Optional. Feed format.
Filter the post comment feed link anchor tag.
Since
2.8.0
Parameters
string $link The complete anchor tag for the comment feed link.
int $post_id Post ID.
string $feed The feed type, or an empty string for the default feed type.
Definition at line 689 of file link-template.php.
References $link, $link_text, $post_id, $url, __, apply_filters(), esc_url, and get_post_comments_feed_link().
Referenced by comments_rss_link().
posts_nav_link ($sep = '', $prelabel = '', $nxtlabel = '')
Display post pages link navigation for previous and next pages.
Since
0.71
Parameters
string $sep Optional. Separator for posts navigation links.
string $prelabel Optional. Label for previous pages.
string $nxtlabel Optional Label for next pages.
Definition at line 2349 of file link-template.php.
References get_posts_nav_link().
prev_post_rel_link ($title = '%title', $in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Display relational link for the previous post adjacent to the current post.
Since
2.8.0
Parameters
string $title Optional. Link title format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs. Default true.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Definition at line 1841 of file link-template.php.
References $title, and get_adjacent_post_rel_link().
previous_comments_link ($label = '')
Display the previous comments page link.
Since
2.7.0
Parameters
string $label Optional. Label for comments link text.
Definition at line 2721 of file link-template.php.
References $label, and get_previous_comments_link().
previous_post_link ($format = '&laquo; %link', $link = '%title', $in_same_term = false, $excluded_terms = '', $taxonomy = 'category')
Display previous post link that is adjacent to the current post.
Since
1.5.0
See also
get_previous_post_link()
Parameters
string $format Optional. Link anchor format.
string $link Optional. Link permalink format.
bool $in_same_term Optional. Whether link should be in a same taxonomy term.
array | string $excluded_terms Optional. Array or comma-separated list of excluded term IDs.
string $taxonomy Optional. Taxonomy, if $in_same_term is true. Default 'category'.
Definition at line 1931 of file link-template.php.
References $format, $link, and get_previous_post_link().
previous_posts ($echo = true)
Display or return the previous posts page link.
Since
0.71
Parameters
bool $echo Optional. Echo or return;
Returns
string|void The previous posts page link if $echo = false.
Definition at line 2250 of file link-template.php.
References $output, esc_url, and get_previous_posts_page_link().
Referenced by get_previous_posts_link().
previous_posts_link ($label = null)
Display the previous posts page link.
Since
0.71
Parameters
string $label Optional. Previous page link text.
Definition at line 2295 of file link-template.php.
References $label, and get_previous_posts_link().
rel_canonical ()
Output rel=canonical for singular queries.
Since
2.9.0
Definition at line 3506 of file link-template.php.
References $id, $page, $url, add_query_arg(), esc_url, get_comments_pagenum_link(), get_option(), get_permalink(), get_queried_object_id(), get_query_var(), is_singular(), trailingslashit(), and user_trailingslashit().
self_admin_url ($path = '', $scheme = 'admin')
Retrieve the url to the admin area for either the current blog or the network depending on context.
Since
3.1.0
Parameters
string $path Optional path relative to the admin url.
string $scheme The scheme to use. Default is 'admin', which obeys force_ssl_admin() and is_ssl(). 'http' or 'https' can be passed to force those schemes.
Returns
string Admin url link with optional path appended.
Definition at line 3363 of file link-template.php.
References $path, admin_url(), elseif, is_network_admin(), is_user_admin(), network_admin_url(), and user_admin_url().
Referenced by Plugin_Upgrader_Skin\after(), core_upgrade_preamble(), WP_Plugin_Install_List_Table\display_rows(), GFAutoUpgrade\display_updates(), do_core_upgrade(), get_edit_user_link(), WP_Theme_Install_List_Table\get_views(), WP_Plugin_Install_List_Table\get_views(), install_dashboard(), install_plugin_install_status(), WP_Theme_Install_List_Table\install_theme_info(), WP_Theme_Install_List_Table\single_row(), wp_admin_bar_wp_menu(), wp_plugin_update_row(), wp_print_request_filesystem_credentials_modal(), and wp_theme_update_row().
set_url_scheme ($url, $scheme = null)
Sets the scheme for a URL.
Since
3.4.0
4.4.0 The 'rest' scheme was added.
Parameters
string $url Absolute url that includes a scheme
string | null $scheme Optional. Scheme to give $url. Currently 'http', 'https', 'login', 'login_post', 'admin', 'relative', 'rest', 'rpc', or null. Default null.
Returns
string $url URL with chosen scheme.
Filter the resulting URL after setting the scheme.
Since
3.4.0
Parameters
string $url The complete URL including scheme and path.
string $scheme Scheme applied to the URL. One of 'http', 'https', or 'relative'.
string | null $orig_scheme Scheme requested for the URL. One of 'http', 'https', 'login', 'login_post', 'admin', 'relative', 'rest', 'rpc', or null.
Definition at line 3383 of file link-template.php.
References $url, apply_filters(), elseif, force_ssl_admin(), and is_ssl().
Referenced by _custom_background_cb(), wp_xmlrpc_server\_multisite_getUsersBlogs(), _wp_menu_item_classes_by_context(), add_menu_page(), Custom_Background\admin_page(), WP_Customize_Theme_Control\content_template(), content_url(), _WP_Editors\editor_settings(), filter_SSL(), get_avatar_data(), get_core_checksums(), GravityView_Field_FileUpload\get_files_array(), get_header_image(), get_home_path(), get_home_url(), get_rest_url(), get_sample_permalink_html(), get_site_url(), WP_Posts_List_Table\handle_row_actions(), install_blog(), network_home_url(), network_site_url(), WP_List_Table\pagination(), plugins_api(), plugins_url(), WP_List_Table\print_column_headers(), self_link(), Custom_Image_Header\show_header_selector(), themes_api(), translations_api(), url_is_accessable_via_ssl(), url_to_postid(), wp_admin_bar_edit_menu(), wp_admin_canonical_url(), wp_ajax_query_themes(), wp_get_attachment_url(), wp_rel_nofollow_callback(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
site_url ($path = '', $scheme = null)
Retrieve the site url for the current site.
Returns the 'site_url' option with the appropriate protocol, 'https' if is_ssl() and 'http' otherwise. If $scheme is 'http' or 'https', is_ssl() is overridden.
Since
3.0.0
Parameters
string $path Optional. Path relative to the site url.
string $scheme Optional. Scheme to give the site url context. See set_url_scheme().
Returns
string Site url link with optional path appended.
Definition at line 3015 of file link-template.php.
References $path, get_site_url(), and null.
Referenced by includes_url(), and network_site_url().
the_comments_navigation ($args = array())
Displays navigation to next/previous set of comments when applicable.
Since
4.4.0
Parameters
array $args See {
See also
get_the_comments_navigation()} for available arguments.
Definition at line 2815 of file link-template.php.
References get_the_comments_navigation().
the_comments_pagination ($args = array())
Displays a paginated navigation to next/previous set of comments, when applicable.
Since
4.4.0
Parameters
array $args See {
See also
get_the_comments_pagination()} for available arguments.
Definition at line 2861 of file link-template.php.
References get_the_comments_pagination().
the_feed_link ($anchor, $feed = '')
Display the permalink for the feed type.
Since
3.0.0
Parameters
string $anchor The link's anchor text.
string $feed Optional, defaults to default feed. Feed type.
Filter the feed link anchor tag.
Since
3.0.0
Parameters
string $link The complete anchor tag for a feed link.
string $feed The feed type, or an empty string for the default feed type.
Definition at line 555 of file link-template.php.
References $link, apply_filters(), esc_url, and get_feed_link().
the_permalink ($post = 0)
Display the permalink for the current post.
Since
1.2.0
4.4.0 Added the $post parameter.
Parameters
int | WP_Post $post Optional. Post ID or post object. Default is the global $post.
Filter the display of the permalink for the current post.
Since
1.5.0
4.4.0 Added the $post parameter.
Parameters
string $permalink The permalink for the current post.
int | WP_Post $post Post ID, WP_Post object, or 0. Default 0.
Definition at line 17 of file link-template.php.
References $post, apply_filters(), esc_url, and get_permalink().
Referenced by permalink_link(), and trackback_rdf().
the_post_navigation ($args = array())
Display navigation to next/previous post when applicable.
Since
4.1.0
Parameters
array $args Optional. See {
See also
get_the_post_navigation()} for available arguments. Default empty array.
Definition at line 2416 of file link-template.php.
References get_the_post_navigation().
the_posts_navigation ($args = array())
Display navigation to next/previous set of posts when applicable.
Since
4.1.0
Parameters
array $args Optional. See {
See also
get_the_posts_navigation()} for available arguments. Default empty array.
Definition at line 2475 of file link-template.php.
References get_the_posts_navigation().
the_posts_pagination ($args = array())
Display a paginated navigation to next/previous set of posts, when applicable.
Since
4.1.0
Parameters
array $args Optional. See {
See also
get_the_posts_pagination()} for available arguments. Default empty array.
Definition at line 2530 of file link-template.php.
References get_the_posts_pagination().
the_shortlink ($text = '', $title = '', $before = '', $after = '')
Display the Short Link for a Post.
Must be called from inside "The Loop"
Call like the_shortlink(__('Shortlinkage FTW'))
Since
3.0.0
Parameters
string $text Optional The link text or HTML to be displayed. Defaults to 'This is the short link.'
string $title Optional The tooltip for the link. Must be sanitized. Defaults to the sanitized post title.
string $before Optional HTML to display before the link.
string $after Optional HTML to display after the link.
Filter the shortlink anchor tag for a post.
Since
3.0.0
Parameters
string $link Shortlink anchor tag.
string $shortlink Shortlink URL.
string $text Shortlink's text.
string $title Shortlink's title attribute.
Definition at line 3656 of file link-template.php.
References $link, $post, $text, $title, __, apply_filters(), esc_url, get_post(), the_title_attribute(), and wp_get_shortlink().
user_admin_url ($path = '', $scheme = 'admin')
Retrieve the url to the admin area for the current user.
Since
3.0.0
Parameters
string $path Optional path relative to the admin url.
string $scheme The scheme to use. Default is 'admin', which obeys force_ssl_admin() and is_ssl(). 'http' or 'https' can be passed to force those schemes.
Returns
string Admin url link with optional path appended.
Filter the user admin URL for the current user.
Since
3.1.0
Parameters
string $url The complete URL including scheme and path.
string $path Path relative to the URL. Blank string if no path is specified.
Definition at line 3336 of file link-template.php.
References $path, $url, apply_filters(), and network_site_url().
Referenced by get_dashboard_url(), get_edit_profile_url(), WP_Admin_Bar\initialize(), and self_admin_url().
user_trailingslashit ($string, $type_of_url = '')
Retrieve trailing slash string, if blog set for adding trailing slashes.
Conditionally adds a trailing slash if the permalink structure has a trailing slash, strips the trailing slash if not. The string is passed through the 'user_trailingslashit' filter. Will remove trailing slash from string, if blog is not set to have them.
Since
2.2.0 WP_Rewrite $wp_rewrite
Parameters
string $string URL with or without a trailing slash.
string $type_of_url The type of URL being considered (e.g. single, category, etc) for use in the filter.
Returns
string The URL with the trailing slash appended or stripped.
Filter the trailing slashed string, depending on whether the site is set to use training slashes.
Since
2.2.0
Parameters
string $string URL with or without a trailing slash.
string $type_of_url The type of URL being considered. Accepts 'single', 'single_trackback', 'single_feed', 'single_paged', 'feed', 'category', 'page', 'year', 'month', 'day', 'paged', 'post_type_archive'.
Definition at line 45 of file link-template.php.
References $wp_rewrite, apply_filters(), trailingslashit(), and untrailingslashit().
Referenced by _get_page_link(), _wp_link_page(), get_attachment_link(), get_author_feed_link(), get_author_posts_url(), get_comment_link(), get_comments_pagenum_link(), get_day_link(), get_feed_link(), get_index_rel_link(), get_month_link(), get_pagenum_link(), get_permalink(), get_post_comments_feed_link(), get_post_embed_url(), get_post_permalink(), get_post_type_archive_link(), get_search_link(), get_term_feed_link(), get_term_link(), get_trackback_url(), get_year_link(), paginate_comments_links(), paginate_links(), redirect_canonical(), redirect_guess_404_permalink(), rel_canonical(), and wp_old_slug_redirect().
wp_get_shortlink ($id = 0, $context = 'post', $allow_slugs = true)
Return a shortlink for a post, page, attachment, or blog.
This function exists to provide a shortlink tag that all themes and plugins can target. A plugin must hook in to provide the actual shortlinks. Default shortlink support is limited to providing ?p= style links for posts. Plugins can short-circuit this function via the pre_get_shortlink filter or filter the output via the get_shortlink filter.
Since
3.0.0.
Parameters
int $id A post or blog id. Default is 0, which means the current post or blog.
string $context Whether the id is a 'blog' id, 'post' id, or 'media' id. If 'post', the post_type of the post is consulted. If 'query', the current query is consulted to determine the id and context. Default is 'post'.
bool $allow_slugs Whether to allow post slugs in the shortlink. It is up to the plugin how and whether to honor this.
Returns
string A shortlink or an empty string if no shortlink exists for the requested resource or if shortlinks are not enabled.
Filter whether to preempt generating a shortlink for the given post.
Passing a truthy value to the filter will effectively short-circuit the shortlink-generation process, returning that value instead.
Since
3.0.0
Parameters
bool | string $return Short-circuit return value. Either false or a URL string.
int $id Post ID, or 0 for the current post.
string $context The context for the link. One of 'post' or 'query',
bool $allow_slugs Whether to allow post slugs in the shortlink.
Filter the shortlink for a post.
Since
3.0.0
Parameters
string $shortlink Shortlink URL.
int $id Post ID, or 0 for the current post.
string $context The context for the link. One of 'post' or 'query',
bool $allow_slugs Whether to allow post slugs in the shortlink. Not used by default.
Definition at line 3551 of file link-template.php.
References $id, $post, $post_id, $post_type, apply_filters(), elseif, get_option(), get_post(), get_post_type_object(), get_queried_object_id(), home_url(), and is_singular().
Referenced by the_shortlink(), wp_admin_bar_shortlink_menu(), wp_shortlink_header(), and wp_shortlink_wp_head().
wp_shortlink_header ()
Send a Link: rel=shortlink header if a shortlink is defined for the current page.
Attached to the wp action.
Since
3.0.0
Definition at line 3630 of file link-template.php.
References wp_get_shortlink().
wp_shortlink_wp_head ()
Inject rel=shortlink into head if a shortlink is defined for the current page.
Attached to the wp_head action.
Since
3.0.0
Definition at line 3614 of file link-template.php.
References esc_url, and wp_get_shortlink().