GravityView: link-add.php File Reference
link-add.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$link = get_default_link_to_edit()
$parent_file = 'link-manager.php'
$title = __('Add New Link')
Variable Documentation
$link = get_default_link_to_edit()
Definition at line 26 of file link-add.php.
Referenced by _fix_attachment_links(), _get_page_link(), _links_add_target(), _post_format_link(), wp_xmlrpc_server\_prepare_page(), GravityView_Entry_Link_Shortcode_Test\_test_read(), _wp_dashboard_recent_comments_row(), adjacent_post_link(), WP_MS_Users_List_Table\column_blogs(), WP_Links_List_Table\column_categories(), WP_Links_List_Table\column_cb(), WP_Links_List_Table\column_default(), WP_Links_List_Table\column_name(), WP_Links_List_Table\column_rating(), WP_Links_List_Table\column_rel(), WP_Links_List_Table\column_url(), WP_Links_List_Table\column_visible(), comment_author_email_link(), GravityView_API\directory_link(), WP_oEmbed\discover(), WP_Links_List_Table\display_rows(), edit_bookmark_link(), edit_comment_link(), edit_post_link(), edit_tag_link(), edit_term_link(), GravityView_API\entry_link_html(), GFForms\format_toolbar_menu_items(), get_adjacent_post_link(), get_adjacent_post_rel_link(), get_attachment_link(), get_author_feed_link(), get_author_link(), get_author_posts_url(), get_author_rss_link(), get_blog_permalink(), get_boundary_post_rel_link(), get_cancel_comment_reply_link(), WP_Press_This\get_canonical_link(), get_category_parents(), get_category_rss_link(), get_comment_link(), get_comment_reply_link(), get_default_link_to_edit(), get_edit_bookmark_link(), get_edit_post_link(), get_edit_user_link(), SimplePie_Item\get_enclosures(), GravityView_Field_FileUpload\get_files_array(), get_index_rel_link(), GravityView_Entry_List\get_item_output(), get_linkobjects(), get_linkrating(), SimplePie_Locator\get_links(), SimplePie_Source\get_links(), SimplePie_Item\get_links(), SimplePie\get_links(), get_next_post_link(), get_page_link(), get_parent_post_rel_link(), SimplePie_Item\get_permalink(), get_post_reply_link(), get_post_type_archive_feed_link(), get_post_type_archive_link(), get_previous_post_link(), get_search_comments_feed_link(), get_search_feed_link(), get_search_link(), get_shortcut_link(), get_term_feed_link(), get_the_author_posts_link(), get_the_term_list(), WP_Comments_List_Table\get_views(), gravityview_back_link(), gravityview_get_map_link(), gravityview_get_the_term_list(), WP_Links_List_Table\handle_row_actions(), WP_Comments_List_Table\handle_row_actions(), image_link_input_fields(), link_advanced_meta_box(), link_categories_meta_box(), WP_REST_Response\link_header(), link_submit_meta_box(), link_target_meta_box(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), next_post_link(), paginate_links(), post_comments_feed_link(), previous_post_link(), WP_List_Table\row_actions(), SimplePie_Locator\search_elements_by_tag(), Walker_Category\start_el(), the_feed_link(), the_media_upload_tabs(), the_shortlink(), upgrade_130(), upgrade_230(), WP_Widget_RSS\widget(), wp_admin_bar_new_content_menu(), wp_ajax_delete_link(), wp_embed_excerpt_more(), wp_link_manager_disabled_message(), wp_link_pages(), wp_list_authors(), wp_loginout(), wp_make_link_relative(), wp_not_installed(), wp_old_slug_redirect(), wp_post_revision_title(), wp_post_revision_title_expanded(), wp_register(), wp_tag_cloud(), wp_update_link(), wp_widget_rss_output(), wp_widget_rss_process(), and xfn_check().
$parent_file = 'link-manager.php'
Definition at line 16 of file link-add.php.
$title = __('Add New Link')
Definition at line 15 of file link-add.php.