GravityView: list-table.php File Reference
list-table.php File Reference
Data Structures
class _WP_List_Table_Compat
Helper class to be used only by back compat functions.
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_list_table ($class, $args=array())
Fetch an instance of a WP_List_Table class.
print_column_headers ($screen, $with_id=true)
Prints column headers for a particular screen.
register_column_headers ($screen, $columns)
Register column headers for a particular screen.
Function Documentation
_get_list_table ($class, $args = array())
Fetch an instance of a WP_List_Table class.
private
Since
3.1.0
string $hook_suffix
Parameters
string $class The type of the list table, which is the class name.
array $args Optional. Arguments to pass to the class. Accepts 'screen'.
Returns
object|bool Object on success, false if the class does not exist.
Definition at line 22 of file list-table.php.
References $class, $GLOBALS, ABSPATH, convert_to_screen(), elseif, get_current_screen(), and null.
Referenced by display_theme(), display_themes(), install_theme_information(), post_comment_meta_box(), wp_ajax_add_tag(), wp_ajax_add_user(), wp_ajax_edit_comment(), wp_ajax_fetch_list(), wp_ajax_get_comments(), wp_ajax_inline_save(), wp_ajax_inline_save_tax(), wp_ajax_replyto_comment(), wp_comment_reply(), wp_plugin_update_row(), and wp_theme_update_row().
print_column_headers ($screen, $with_id = true)
Prints column headers for a particular screen.
Since
2.7.0
Parameters
string | WP_Screen $screen The screen hook name or screen object.
bool $with_id Whether to set the id attribute or not.
Definition at line 80 of file list-table.php.
References $screen, and $wp_list_table.
register_column_headers ($screen, $columns)
Register column headers for a particular screen.
Since
2.7.0
Parameters
string $screen The handle for the screen to add help to. This is usually the hook name returned by the add_*_page() functions.
array $columns An array of columns with column IDs as the keys and translated column names as the values
See also
get_column_headers(), print_column_headers(), get_hidden_columns()
Definition at line 68 of file list-table.php.
References $columns, $screen, and $wp_list_table.