GravityView: load-styles.php File Reference
load-styles.php File Reference
Variables
$compress = (isset($_GET['c']) && $_GET['c'])
$expires_offset = 31536000
$force_gzip = ($compress && 'gzip' == $_GET['c'])
$load = preg_replace('/[^a-z0-9,_-]+/i', '', $_GET['load'])
$out = ''
$rtl = (isset($_GET['dir']) && 'rtl' == $_GET['dir'])
$wp_styles = new WP_Styles()
const ABSPATH dirname(dirname(__FILE__)) . '/'
Set ABSPATH for execution.
exit
if ($compress &&!ini_get('zlib.output_compression')&& 'ob_gzhandler'!=ini_get('output_handler')&&isset($_SERVER['HTTP_ACCEPT_ENCODING']))
const WPINC 'wp-includes'
Variable Documentation
$compress = (isset($_GET['c']) && $_GET['c'])
Definition at line 24 of file load-styles.php.
$expires_offset = 31536000
Definition at line 27 of file load-styles.php.
$force_gzip = ($compress && 'gzip' == $_GET['c'])
Definition at line 25 of file load-styles.php.
$load = preg_replace('/[^a-z0-9,_-]+/i', '', $_GET['load'])
Definition at line 18 of file load-styles.php.
$out = ''
Definition at line 28 of file load-styles.php.
$rtl = (isset($_GET['dir']) && 'rtl' == $_GET['dir'])
Definition at line 26 of file load-styles.php.
$wp_styles = new WP_Styles()
Definition at line 30 of file load-styles.php.
Referenced by _print_styles(), GFForms\no_conflict_mode_style(), GravityView_Admin\no_conflict_styles(), print_admin_styles(), print_late_styles(), twentytwelve_scripts_styles(), wp_enqueue_style(), wp_print_styles(), and wp_styles().
const ABSPATH dirname(dirname(__FILE__)) . '/'
Set ABSPATH for execution.
Definition at line 11 of file load-styles.php.
exit
Definition at line 73 of file load-styles.php.
if($compress &&!ini_get('zlib.output_compression')&& 'ob_gzhandler'!=ini_get('output_handler')&&isset($_SERVER['HTTP_ACCEPT_ENCODING']))
Definition at line 61 of file load-styles.php.
const WPINC 'wp-includes'
Definition at line 12 of file load-styles.php.