GravityView: load-scripts.php File Reference
load-scripts.php File Reference
Variables
$compress = (isset($_GET['c']) && $_GET['c'])
$expires_offset = 31536000
$force_gzip = ($compress && 'gzip' == $_GET['c'])
$load = $_GET['load']
$out = ''
$wp_scripts = new WP_Scripts()
const ABSPATH dirname(dirname(__FILE__)) . '/'
Set ABSPATH for execution.
exit
if ($compress &&!ini_get('zlib.output_compression')&& 'ob_gzhandler'!=ini_get('output_handler')&&isset($_SERVER['HTTP_ACCEPT_ENCODING']))
const WPINC 'wp-includes'
Variable Documentation
$compress = (isset($_GET['c']) && $_GET['c'])
Definition at line 28 of file load-scripts.php.
$expires_offset = 31536000
Definition at line 30 of file load-scripts.php.
$force_gzip = ($compress && 'gzip' == $_GET['c'])
Definition at line 29 of file load-scripts.php.
Referenced by wp_ajax_wp_compression_test().
$load = $_GET['load']
Definition at line 14 of file load-scripts.php.
Referenced by locate_template(), and GravityView_View\locate_template().
$out = ''
Definition at line 31 of file load-scripts.php.
Referenced by SimplePie_File\__construct(), ftp\_data_read(), ftp\_data_write(), WPProfiler\_dirty_objects_count(), ftp_base\_list(), WPProfiler\_query_count(), WPProfiler\_query_summary(), WPProfiler\array_add(), WPProfiler\array_sub(), check_comment(), WP_Media_List_Table\column_default(), WP_Posts_List_Table\column_default(), WP_Terms_List_Table\column_name(), ftp_base\fget(), gen_tests_array(), ftp_base\get(), MockAction\get_args(), get_cli_args(), MockAction\get_tags(), ftp_base\glob_pattern_match(), WP_Comments_List_Table\handle_row_actions(), image_align_input_fields(), image_downsize(), image_hwstring(), image_size_input_fields(), WP_List_Table\row_actions(), shortcode_atts(), GFAsyncUpload\upload(), WP_Widget_Pages\widget(), wp_ajax_wp_compression_test(), wp_doc_link_parse(), xml_array_dumbdown(), and xml_find().
$wp_scripts = new WP_Scripts()
Definition at line 33 of file load-scripts.php.
const ABSPATH dirname(dirname(__FILE__)) . '/'
Set ABSPATH for execution.
Definition at line 11 of file load-scripts.php.
Referenced by WP_Filesystem_ftpsockets\__construct(), WP_Customize_Manager\__construct(), _custom_header_background_just_in_time(), _get_list_table(), WP_Press_This\_limit_embed(), _maybe_update_core(), _redirect_to_about_wordpress(), _unzip_file_pclzip(), _wp_admin_bar_init(), _wp_customize_include(), _wp_handle_upload(), _wp_image_editor_choose(), WP_Filesystem_MockFS\abspath(), WP_Filesystem_Base\abspath(), GFForms\captcha_image(), Core_Upgrader\check_files(), GravityView_Compatibility\check_gravityforms(), check_password_reset_key(), comment_footer_die(), comments_template(), core_upgrade_preamble(), WP_UnitTest_Factory_For_Network\create_object(), GFFormsModel\dbDelta(), delete_plugins(), delete_theme(), do_core_upgrade(), do_enclose(), do_feed_atom(), do_feed_rdf(), do_feed_rss(), do_feed_rss2(), edit_form_image_editor(), _WP_Editors\editor(), WP_Plugins_List_Table\extra_tablenav(), fetch_feed(), find_core_auto_update(), WP_Filesystem_Base\find_folder(), WP_Upgrader\fs_connect(), WP_Customize_Widgets\get_available_widgets(), get_footer(), get_header(), get_home_path(), get_password_reset_key(), GravityView_Compatibility\get_plugin_status(), get_post_embed_html(), get_shortcut_link(), get_sidebar(), get_theme_root_uri(), install_blog(), install_blog_defaults(), WP_Upgrader\install_package(), WP_Automatic_Updater\is_vcs_checkout(), list_plugin_updates(), load_plugin_textdomain(), maintenance_nag(), make_site_theme(), make_site_theme_from_oldschool(), GFFormsModel\media_handle_upload(), network_step1(), network_step2(), pingback(), post_password_required(), GFAutoUpgrade\premium_update(), GFForms\premium_update(), GFAutoUpgrade\premium_update_push(), GFForms\premium_update_push(), WP_Theme_Install_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), print_embed_styles(), print_emoji_detection_script(), WP_Customize_Manager\register_controls(), WP_Http\request(), require_wp_db(), rich_edit_exists(), GFForms\setup_database(), Core_Upgrader\should_update_to_version(), spawn_cron(), WP_Widget_Form_Customize_Control\to_json(), translations_api(), WP_Automatic_Updater\update(), update_core(), Core_Upgrader\upgrade(), GFFeedAddOn\upgrade_base(), weblog_ping(), wp_ajax_add_menu_item(), wp_ajax_crop_image(), wp_ajax_dashboard_widgets(), wp_ajax_get_revision_diffs(), wp_ajax_image_editor(), wp_ajax_imgedit_preview(), wp_ajax_menu_get_metabox(), wp_ajax_menu_quick_search(), wp_ajax_press_this_add_category(), wp_ajax_press_this_save_post(), wp_ajax_replyto_comment(), wp_ajax_update_plugin(), wp_ajax_wp_link_ajax(), wp_can_install_language_pack(), wp_debug_backtrace_summary(), wp_default_scripts(), wp_default_styles(), wp_download_language_pack(), wp_dropdown_languages(), wp_editor(), wp_enqueue_media(), WP_Filesystem(), wp_filter_oembed_result(), wp_get_active_and_valid_plugins(), wp_get_attachment_image_src(), wp_get_available_translations(), wp_get_popular_importers(), wp_guess_url(), wp_initial_constants(), wp_load_translations_early(), wp_maintenance(), wp_maybe_auto_update(), wp_maybe_load_widgets(), wp_mime_type_icon(), wp_not_installed(), wp_oembed_add_provider(), wp_oembed_get(), wp_oembed_remove_provider(), wp_read_audio_metadata(), wp_read_video_metadata(), wp_set_lang_dir(), wp_simplepie_autoload(), wp_start_object_cache(), wp_tiny_mce(), wp_update_core(), wp_update_plugin(), wp_update_plugins(), wp_update_theme(), wp_update_themes(), wp_upload_bits(), wp_upload_dir(), and wp_version_check().
exit
Definition at line 60 of file load-scripts.php.
if($compress &&!ini_get('zlib.output_compression')&& 'ob_gzhandler'!=ini_get('output_handler')&&isset($_SERVER['HTTP_ACCEPT_ENCODING']))
Definition at line 48 of file load-scripts.php.
const WPINC 'wp-includes'
Definition at line 12 of file load-scripts.php.
Referenced by WP_Customize_Manager\__construct(), WP_Press_This\_limit_embed(), _maybe_update_core(), _wp_admin_bar_init(), _wp_customize_include(), _wp_image_editor_choose(), WP_Filesystem_Base\abspath(), GravityView_Compatibility\check_gravityforms(), check_password_reset_key(), comments_template(), do_enclose(), do_feed_atom(), do_feed_rdf(), do_feed_rss(), do_feed_rss2(), fetch_feed(), get_footer(), get_header(), get_password_reset_key(), get_post_embed_html(), get_sidebar(), WP_Scripts\in_default_dir(), includes_url(), maintenance_nag(), network_step2(), pingback(), post_password_required(), print_embed_styles(), print_emoji_detection_script(), WP_Http\request(), require_wp_db(), rich_edit_exists(), Core_Upgrader\should_update_to_version(), translations_api(), update_core(), Core_Upgrader\upgrade(), weblog_ping(), wp_ajax_wp_link_ajax(), wp_default_scripts(), wp_default_styles(), wp_editor(), wp_enqueue_media(), wp_filter_oembed_result(), wp_get_attachment_image_src(), wp_get_available_translations(), wp_get_popular_importers(), wp_load_translations_early(), wp_maybe_load_widgets(), wp_mime_type_icon(), wp_not_installed(), wp_oembed_add_provider(), wp_oembed_get(), wp_oembed_remove_provider(), wp_read_audio_metadata(), wp_read_video_metadata(), wp_set_lang_dir(), wp_simplepie_autoload(), wp_start_object_cache(), wp_tiny_mce(), wp_update_plugins(), wp_update_themes(), and wp_version_check().