GravityView: load.php File Reference
load.php File Reference
Functions
get_current_blog_id ()
Retrieve the current blog ID.
is_admin ()
Whether the current request is for an administrative interface page.
is_blog_admin ()
Whether the current request is for a site's admininstrative interface.
is_multisite ()
If Multisite is enabled.
is_network_admin ()
Whether the current request is for the network administrative interface.
is_user_admin ()
Whether the current request is for a user admin screen.
require_wp_db ()
Load the database class file and instantiate the $wpdb global.
shutdown_action_hook ()
Runs just before PHP shuts down execution.
timer_start ()
Start the WordPress micro-timer.
timer_stop ($display=0, $precision=3)
Retrieve or display the time from the page start to when function is called.
wp_check_php_mysql_versions ()
Check for the required PHP version, and the MySQL extension or a database drop-in.
wp_clone ($object)
Copy an object.
wp_debug_mode ()
Set PHP error reporting based on WordPress debug settings.
wp_favicon_request ()
Don't load all of WordPress when handling a favicon.ico request.
wp_fix_server_vars ()
Fix $_SERVER variables for various setups.
wp_get_active_and_valid_plugins ()
Retrieve an array of active and valid plugin files.
wp_get_mu_plugins ()
Retrieve an array of must-use plugin files.
wp_get_server_protocol ()
These functions are needed to load WordPress.
wp_installing ($is_installing=null)
Check or set whether WordPress is in "installation" mode.
wp_load_translations_early ()
Attempt an early load of translations.
wp_magic_quotes ()
Add magic quotes to $_GET, $_POST, $_COOKIE, and $_SERVER.
wp_maintenance ()
Die with a maintenance message when conditions are met.
wp_not_installed ()
Redirect to the installer if WordPress is not installed.
wp_set_internal_encoding ()
Set internal encoding.
wp_set_lang_dir ()
Set the location of the language directory.
wp_set_wpdb_vars ()
Set the database table prefix and the format specifiers for database table columns.
wp_start_object_cache ()
Start the WordPress object cache.
wp_unregister_GLOBALS ()
Turn register globals off.
wp_using_ext_object_cache ($using=null)
Toggle $_wp_using_ext_object_cache on and off without directly touching global.
Function Documentation
get_current_blog_id ()
Retrieve the current blog ID.
Since
3.1.0
int $blog_id
Returns
int Blog id
Definition at line 772 of file load.php.
References $blog_id, and absint().
Referenced by _access_denied_splash(), _wp_upload_dir_baseurl(), add_blog_option(), count_users(), delete_blog_option(), GravityView_Cache\delete_expired_transients(), GFFormsModel\ensure_tables_exist(), WP_Customize_Nav_Menu_Setting\filter_nav_menu_options(), WP_Customize_Nav_Menu_Setting\filter_wp_get_nav_menu_object(), WP_Customize_Nav_Menu_Setting\filter_wp_get_nav_menus(), WP_Theme\get_allowed_on_site(), get_blog_details(), get_blog_option(), get_blogs_of_user(), get_dashboard_url(), GFFormsModel\get_form_meta(), get_site_icon_url(), WP_Admin_Bar\initialize(), WP_Customize_Setting\is_current_blog_previewed(), is_main_site(), is_user_member_of_blog(), WP_Customize_Nav_Menu_Setting\preview(), WP_Customize_Setting\preview(), WP_Customize_Nav_Menu_Item_Setting\preview(), refresh_blog_details(), GFFormsModel\restore_form(), GFForms\setup(), GFFormsModel\trash_form(), update_blog_option(), update_blog_public(), GFFormsModel\update_form_meta(), WP_Customize_Nav_Menu_Setting\value(), WP_Customize_Nav_Menu_Item_Setting\value(), wp_admin_bar_site_menu(), wp_ajax_autocomplete_user(), wp_dashboard_quick_press(), wp_delete_user(), wp_just_in_time_script_localization(), wp_upload_dir(), and wpmu_delete_blog().
is_admin ()
Whether the current request is for an administrative interface page.
Does not check if the user is an administrator; {
See also
current_user_can()} for checking roles and capabilities.
Since
1.5.1
WP_Screen $current_screen
Returns
bool True if inside WordPress administration interface, false otherwise.
Definition at line 667 of file load.php.
References $GLOBALS, and elseif.
is_blog_admin ()
Whether the current request is for a site's admininstrative interface.
e.g. /wp-admin/
Does not check if the user is an administrator; {
See also
current_user_can()} for checking roles and capabilities.
Since
3.1.0
WP_Screen $current_screen
Returns
bool True if inside WordPress blog administration pages.
Definition at line 690 of file load.php.
References $GLOBALS, and elseif.
Referenced by wp_admin_bar_site_menu(), wp_dashboard_setup(), and wp_validate_logged_in_cookie().
is_multisite ()
If Multisite is enabled.
Since
3.0.0
Returns
bool True if Multisite is enabled, false otherwise.
Definition at line 753 of file load.php.
Referenced by WP_UnitTest_Factory\__construct(), WP_Object_Cache\__construct(), _get_dropins(), _wp_handle_upload(), activate_plugin(), add_network_option(), wp_xmlrpc_server\blogger_getUsersBlogs(), Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), GravityView_Compatibility\check_gravityforms(), GravityView_Admin_Notices\check_show_multisite_notices(), GFFormsModel\copy_post_image(), count_users(), GravityView_Settings\create_app_menu(), current_user_can_for_blog(), GFForms\dashboard(), deactivate_plugins(), delete_network_option(), GFFormsModel\delete_physical_file(), WP_UnitTestCase\delete_user(), WP_Themes_List_Table\display_rows(), WP_Users_List_Table\display_rows(), WP_Plugins_List_Table\display_rows(), edit_user(), export_wp(), get_active_blog_for_user(), WP_Theme\get_allowed_on_site(), get_author_user_ids(), wpdb\get_blog_prefix(), get_blogs_of_user(), WP_Users_List_Table\get_bulk_actions(), WP_Plugins_List_Table\get_bulk_actions(), GravityView_Render_Settings\get_cap_choices(), get_dashboard_url(), get_editable_user_ids(), get_home_url(), get_locale(), get_main_network_id(), get_network_option(), get_rest_url(), get_site_icon_url(), get_site_url(), get_theme_update_available(), global_terms_enabled(), WP_User\has_cap(), iis7_save_url_rewrite_rules(), GFForms\init(), wpdb\init_charset(), WP_Admin_Bar\initialize(), WP_Theme\is_allowed(), is_main_network(), is_main_site(), GravityView_Plugin\is_network_activated(), is_plugin_active_for_network(), is_super_admin(), is_user_member_of_blog(), load_default_textdomain(), GV_Unit_Tests_Bootstrap\load_rest_api(), login_header(), map_meta_cap(), GFForms\maybe_display_installation_wizard(), media_upload_form(), wp_xmlrpc_server\mw_newMediaObject(), network_admin_url(), network_home_url(), network_site_url(), network_step2(), WP_Themes_List_Table\no_items(), WP_Plugins_List_Table\no_items(), populate_network(), populate_options(), pre_schema_upgrade(), WP_Plugins_List_Table\prepare_items(), WP_User_Query\prepare_query(), wpdb\print_error(), redirect_canonical(), rest_api_activation(), rest_api_deactivation(), retrieve_password(), WP_Rewrite\rewrite_rules(), sanitize_option(), GF_Field_HTML\sanitize_settings(), save_mod_rewrite_rules(), WP_Importer\set_blog(), wpdb\set_prefix(), GFSettings\settings_uninstall_page(), WP_Users_List_Table\single_row(), WP_Plugins_List_Table\single_row(), wpdb\tables(), WP_UnitTestCase\tearDown(), update_home_siteurl(), update_nag(), update_network_option(), upgrade_280(), upgrade_300(), upgrade_400(), upgrade_430(), validate_active_plugins(), wp_admin_bar_dashboard_view_site_menu(), wp_admin_bar_my_account_item(), wp_admin_bar_my_account_menu(), wp_admin_bar_my_sites_menu(), wp_admin_bar_site_menu(), wp_ajax_autocomplete_user(), wp_authenticate_spam_check(), wp_delete_attachment(), wp_delete_user(), wp_get_active_and_valid_plugins(), wp_get_db_schema(), wp_get_themes(), wp_get_users_with_no_role(), wp_xmlrpc_server\wp_getUsersBlogs(), wp_initial_constants(), wp_load_alloptions(), wp_load_core_site_options(), wp_not_installed(), wp_plugin_update_row(), wp_plupload_default_settings(), wp_print_media_templates(), wp_upload_dir(), and wp_version_check().
is_network_admin ()
Whether the current request is for the network administrative interface.
e.g. /wp-admin/network/
Does not check if the user is an administrator; {
See also
current_user_can()} for checking roles and capabilities.
Since
3.1.0
WP_Screen $current_screen
Returns
bool True if inside WordPress network administration pages.
Definition at line 713 of file load.php.
References $GLOBALS, elseif, and WP_NETWORK_ADMIN.
Referenced by _access_denied_splash(), WP_Admin_Bar\add_menus(), add_thickbox(), GravityView_Compatibility\check_gravityforms(), GravityView_Settings\create_app_menu(), get_edit_profile_url(), GravityView_Compatibility\get_plugin_status(), GravityView_Welcome\getting_started_screen(), load_default_textdomain(), self_admin_url(), wp_admin_bar_site_menu(), wp_dashboard_right_now(), wp_dashboard_setup(), wp_plugin_update_row(), and wp_validate_logged_in_cookie().
is_user_admin ()
Whether the current request is for a user admin screen.
e.g. /wp-admin/user/
Does not inform on whether the user is an admin! Use capability checks to tell if the user should be accessing a section or not {
See also
current_user_can()}.
Since
3.1.0
WP_Screen $current_screen
Returns
bool True if inside WordPress user administration pages.
Definition at line 737 of file load.php.
References $GLOBALS, elseif, and WP_USER_ADMIN.
Referenced by WP_Admin_Bar\add_menus(), get_edit_profile_url(), self_admin_url(), wp_admin_bar_site_menu(), wp_dashboard_right_now(), and wp_dashboard_setup().
require_wp_db ()
Load the database class file and instantiate the $wpdb global.
Since
2.5.0
wpdb $wpdb The WordPress database class.
Definition at line 359 of file load.php.
References $wpdb, ABSPATH, DB_HOST, DB_NAME, DB_PASSWORD, DB_USER, WP_CONTENT_DIR, and WPINC.
shutdown_action_hook ()
Runs just before PHP shuts down execution.
Since
1.2.0 private
Fires just before PHP shuts down execution.
Since
1.2.0
Definition at line 630 of file load.php.
References do_action(), and wp_cache_close().
timer_start ()
Start the WordPress micro-timer.
Since
0.71 private
float $timestart Unix timestamp set at the beginning of the page load.
See also
timer_stop()
Returns
bool Always returns true.
Definition at line 225 of file load.php.
timer_stop ($display = 0, $precision = 3)
Retrieve or display the time from the page start to when function is called.
Since
0.71
float $timestart Seconds from when timer_start() is called. float $timeend Seconds from when function is called.
Parameters
int | bool $display Whether to echo or return the results. Accepts 0|false for return, 1|true for echo. Default 0|false.
int $precision The number of digits from the right of the decimal to display. Default 3.
Returns
string The "second.microsecond" finished time calculation. The number is formatted for human consumption, both localized and rounded.
Definition at line 246 of file load.php.
References number_format_i18n().
wp_check_php_mysql_versions ()
Check for the required PHP version, and the MySQL extension or a database drop-in.
Dies if requirements are not met.
Since
3.0.0 private
string $required_php_version The required PHP version string. string $wp_version The WordPress version string.
Definition at line 123 of file load.php.
References $php_version, $required_php_version, $wp_version, __, WP_CONTENT_DIR, wp_get_server_protocol(), and wp_load_translations_early().
wp_clone ($object)
Copy an object.
Since
2.7.0
Parameters
object $object The object to clone.
Returns
object The cloned object.
Definition at line 650 of file load.php.
wp_debug_mode ()
Set PHP error reporting based on WordPress debug settings.
Uses three constants: WP_DEBUG, WP_DEBUG_DISPLAY, and WP_DEBUG_LOG. All three can be defined in wp-config.php. By default, WP_DEBUG and WP_DEBUG_LOG are set to false, and WP_DEBUG_DISPLAY is set to true.
When WP_DEBUG is true, all PHP notices are reported. WordPress will also display internal notices: when a deprecated WordPress function, function argument, or file is used. Deprecated code may be removed from a later version.
It is strongly recommended that plugin and theme developers use WP_DEBUG in their development environments.
WP_DEBUG_DISPLAY and WP_DEBUG_LOG perform no function unless WP_DEBUG is true.
When WP_DEBUG_DISPLAY is true, WordPress will force errors to be displayed. WP_DEBUG_DISPLAY defaults to true. Defining it as null prevents WordPress from changing the global configuration setting. Defining WP_DEBUG_DISPLAY as false will force errors to be hidden.
When WP_DEBUG_LOG is true, errors will be logged to debug.log in the content directory.
Errors are never displayed for XML-RPC requests.
Since
3.0.0 private
Definition at line 287 of file load.php.
References elseif, null, WP_CONTENT_DIR, and WP_DEBUG.
wp_favicon_request ()
Don't load all of WordPress when handling a favicon.ico request.
Instead, send the headers for a zero-length favicon and bail.
Since
3.0.0
Definition at line 153 of file load.php.
References $_SERVER, and exit.
wp_fix_server_vars ()
Fix $_SERVER variables for various setups.
Since
3.0.0 private
string $PHP_SELF The filename of the currently executing script, relative to the document root.
Definition at line 57 of file load.php.
References $_SERVER, $PHP_SELF, and elseif.
wp_get_active_and_valid_plugins ()
Retrieve an array of active and valid plugin files.
While upgrading or installing WordPress, no plugins are returned.
The default directory is wp-content/plugins. To change the default directory manually, define WP_PLUGIN_DIR and WP_PLUGIN_URL in wp-config.php.
Since
3.0.0 private
Returns
array Files.
Definition at line 553 of file load.php.
References $plugin, $plugins, _deprecated_file(), ABSPATH, get_option(), is_multisite(), validate_file(), wp_get_active_network_plugins(), and wp_installing().
Referenced by GravityView_Support_Port\get_related_plugins_and_extensions().
wp_get_mu_plugins ()
Retrieve an array of must-use plugin files.
The default directory is wp-content/mu-plugins. To change the default directory manually, define WPMU_PLUGIN_DIR and WPMU_PLUGIN_URL in wp-config.php.
Since
3.0.0 private
Returns
array Files to include.
Definition at line 523 of file load.php.
References $plugin.
wp_get_server_protocol ()
These functions are needed to load WordPress.
Return the HTTP protocol sent by the server.
Since
4.4.0
Returns
string The HTTP protocol. Default: HTTP/1.0.
Definition at line 17 of file load.php.
References $_SERVER.
Referenced by status_header(), wp_check_php_mysql_versions(), and wp_maintenance().
wp_installing ($is_installing = null)
Check or set whether WordPress is in "installation" mode.
If the WP_INSTALLING constant is defined during the bootstrap, wp_installing() will default to true.
Since
4.4.0
bool $installing
Parameters
bool $is_installing Optional. True to set WP into Installing mode, false to turn Installing mode off. Omit this parameter if you only want to fetch the current status.
Returns
bool True if WP is installing, otherwise false. When a $is_installing is passed, the function will report whether WP was in installing mode prior to the change to $is_installing.
Definition at line 880 of file load.php.
References null, and WP_INSTALLING.
Referenced by add_option(), WP_UnitTest_Factory_For_Blog\create_object(), dead_db(), delete_option(), get_locale(), get_option(), get_transient(), is_blog_installed(), WP_Automatic_Updater\is_disabled(), load_default_textdomain(), request_filesystem_credentials(), update_home_siteurl(), update_option(), validate_current_theme(), wp_get_active_and_valid_plugins(), wp_get_available_translations(), wp_load_alloptions(), wp_load_core_site_options(), wp_maintenance(), wp_not_installed(), wp_schedule_update_checks(), wp_schedule_update_network_counts(), wp_style_loader_src(), wp_update_plugins(), wp_update_themes(), wp_version_check(), and wpmu_create_blog().
wp_load_translations_early ()
Attempt an early load of translations.
Used for errors encountered during the initial loading process, before the locale has been properly detected and loaded.
Designed for unusual load sequences (like setup-config.php) or for when the script will then terminate with an error, otherwise there is a risk that a file can be double-included.
Since
3.4.0 private
string $text_direction WP_Locale $wp_locale The WordPress date and time locale object.
bool $loaded
Definition at line 795 of file load.php.
References $locale, $location, $locations, $wp_locale, ABSPATH, did_action(), load_textdomain(), WP_CONTENT_DIR, WPINC, and WPLANG.
Referenced by wpdb\check_connection(), wpdb\db_connect(), dead_db(), is_blog_installed(), ms_not_installed(), wpdb\print_error(), wpdb\select(), wp_check_php_mysql_versions(), wp_maintenance(), and wp_set_wpdb_vars().
wp_magic_quotes ()
Add magic quotes to $_GET, $_POST, $_COOKIE, and $_SERVER.
Also forces $_REQUEST to be $_GET + $_POST. If $_SERVER, $_COOKIE, or $_ENV are needed, use those superglobals directly.
Since
3.0.0 private
Definition at line 606 of file load.php.
References $_COOKIE, $_SERVER, add_magic_quotes(), and stripslashes_deep().
wp_maintenance ()
Die with a maintenance message when conditions are met.
Checks for a file in the WordPress root directory named ".maintenance". This file will contain the variable $upgrading, set to the time the file was created. If the file was created less than 10 minutes ago, WordPress enters maintenance mode and displays a message.
The default message can be replaced by using a drop-in (maintenance.php in the wp-content directory).
Since
3.0.0 private
int $upgrading the unix timestamp marking when upgrading WordPress began.
Definition at line 176 of file load.php.
References _e, ABSPATH, is_rtl(), WP_CONTENT_DIR, wp_get_server_protocol(), wp_installing(), and wp_load_translations_early().
wp_not_installed ()
Redirect to the installer if WordPress is not installed.
Dies with an error message when Multisite is enabled.
Since
3.0.0 private
Definition at line 490 of file load.php.
References $link, __, ABSPATH, elseif, is_blog_installed(), is_multisite(), nocache_headers(), wp_die(), wp_guess_url(), wp_installing(), and WPINC.
wp_set_internal_encoding ()
Set internal encoding.
In most cases the default internal encoding is latin1, which is of no use, since we want to use the mb_ functions for utf-8 strings.
Since
3.0.0 private
Definition at line 589 of file load.php.
References $charset, and get_option().
wp_set_lang_dir ()
Set the location of the language directory.
To set directory manually, define the WP_LANG_DIR constant in wp-config.php.
If the language directory exists within WP_CONTENT_DIR, it is used. Otherwise the language directory is assumed to live in WPINC.
Since
3.0.0 private
Server path of the language directory.
No leading slash, no trailing slash, full path, not relative to ABSPATH
Since
2.1.0
Server path of the language directory.
No leading slash, no trailing slash, full path, not relative to ABSPATH.
Since
2.1.0
Definition at line 320 of file load.php.
References ABSPATH, WP_CONTENT_DIR, and WPINC.
wp_set_wpdb_vars ()
Set the database table prefix and the format specifiers for database table columns.
Columns not listed here default to s.
Since
3.0.0 private
wpdb $wpdb The WordPress database class. string $table_prefix The database table prefix.
Definition at line 384 of file load.php.
References $prefix, $table_prefix, $wpdb, __, dead_db(), is_wp_error(), wp_die(), and wp_load_translations_early().
wp_start_object_cache ()
Start the WordPress object cache.
If an object-cache.php file exists in the wp-content directory, it uses that drop-in as an external object cache.
Since
3.0.0 private
int $blog_id Blog ID.
Definition at line 441 of file load.php.
References $blog_id, ABSPATH, elseif, wp_cache_add_global_groups(), wp_cache_add_non_persistent_groups(), wp_cache_init(), wp_cache_switch_to_blog(), WP_CONTENT_DIR, wp_using_ext_object_cache(), and WPINC.
wp_unregister_GLOBALS ()
Turn register globals off.
Since
2.1.0 private
Definition at line 31 of file load.php.
References $_COOKIE, $_SERVER, and $GLOBALS.
wp_using_ext_object_cache ($using = null)
Toggle $_wp_using_ext_object_cache on and off without directly touching global.
Since
3.7.0
bool $_wp_using_ext_object_cache
Parameters
bool $using Whether external object cache is being used.
Returns
bool The current 'using' setting.
Definition at line 422 of file load.php.
References null.
Referenced by _get_cron_lock(), delete_site_transient(), delete_transient(), WP_Network\get_by_path(), WP_Query\get_posts(), get_site_transient(), get_transient(), set_site_transient(), set_transient(), wp_get_nav_menu_items(), wp_load_core_site_options(), and wp_start_object_cache().