GravityView: locale.php File Reference
locale.php File Reference
Data Structures
class WP_Locale
Class that loads the calendar locale.
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
is_rtl ()
Checks if current locale is RTL.
Function Documentation
is_rtl ()
Checks if current locale is RTL.
Since
3.0.0
WP_Locale $wp_locale
Returns
bool Whether locale is RTL.
Definition at line 404 of file locale.php.
References $wp_locale.
Referenced by _default_wp_die_handler(), _mce_set_direction(), GravityView_Widget_Search\add_datepicker_localization(), WP_Press_This\add_editor_style(), add_editor_style(), GravityView_Admin_Notices\admin_notice(), dead_db(), display_header(), dolly_css(), GFFormDisplay\enqueue_form_scripts(), gallery_shortcode(), get_bloginfo(), get_body_class(), GF_Field_List\get_field_input(), get_language_attributes(), gravityview_get_floaty(), WP_Press_This\html(), iframe_header(), login_header(), GFFormDisplay\print_form_scripts(), register_admin_color_schemes(), setup_config_display_header(), twentyeleven_get_default_theme_options(), wp_admin_css(), wp_default_styles(), wp_iframe(), wp_maintenance(), and _WP_Editors\wp_mce_translation().