GravityView: media-upload.php File Reference
media-upload.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$body_id = 'media-upload'
$ID = isset($ID) ? (int) $ID : 0
$post_id = isset($post_id)? (int) $post_id : 0
if(isset($action)&&$action== 'edit'&&!$ID) if(!empty($_REQUEST['post_id'])&&!current_user_can('edit_post', $_REQUEST['post_id'])) if(isset($_GET['type'])) else
if(!isset($_GET['inline'])) define('IFRAME_REQUEST' true
Variable Documentation
$body_id = 'media-upload'
Definition at line 80 of file media-upload.php.
$ID = isset($ID) ? (int) $ID : 0
Definition at line 31 of file media-upload.php.
Referenced by get_post_mime_type(), get_post_status(), wp_xmlrpc_server\mw_editPost(), trackback(), wp_insert_user(), and wp_update_user().
$post_id = isset($post_id)? (int) $post_id : 0
Definition at line 32 of file media-upload.php.
if ($tab== 'type'||$tab== 'type_url'||!array_key_exists($tab, media_upload_tabs())) else
Initial value:
{
    $type = apply_filters( 'media_upload_default_type', 'file' )
Definition at line 54 of file media-upload.php.
if (!isset($_GET['inline'])) define('IFRAME_REQUEST' true
Definition at line 12 of file media-upload.php.