GravityView: media-template.php File Reference
media-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
wp_print_media_templates ()
Prints the templates used in the media manager.
wp_underscore_audio_template ()
Output the markup for a audio tag to be used in an Underscore template when data.model is passed.
wp_underscore_video_template ()
Output the markup for a video tag to be used in an Underscore template when data.model is passed.
Function Documentation
wp_print_media_templates ()
Prints the templates used in the media manager.
Since
3.5.0
bool $is_IE
This action is documented in wp-admin/includes/media.php
This action is documented in wp-admin/includes/media.php
This action is documented in wp-admin/includes/media.php
This action is documented in wp-admin/includes/media.php
This action is documented in wp-admin/includes/media.php
This action is documented in wp-admin/includes/media.php
This filter is documented in wp-admin/includes/media.php
This filter is documented in wp-admin/includes/media.php
This filter is documented in wp-admin/includes/media.php
This filter is documented in wp-admin/includes/media.php
Fires when the custom Backbone media templates are printed.
Since
3.5.0
Definition at line 139 of file media-template.php.
References $_SERVER, $class, $i, $is_IE, $label, $name, $size, $value, __, _device_can_upload(), _e, _ex(), add_action(), apply_filters(), bloginfo(), checked(), disabled(), do_action(), elseif, endforeach, endif, esc_attr_e(), esc_html, esc_html_e, height, if, input, is_multisite(), is_upload_space_available(), label, name, outline, placeholder, post_type_supports(), remove_action(), selected(), size, size_format(), textarea, width, wp_get_audio_extensions(), wp_get_video_extensions(), wp_max_upload_size(), wp_underscore_audio_template(), and wp_underscore_video_template().
wp_underscore_audio_template ()
Output the markup for a audio tag to be used in an Underscore template when data.model is passed.
Since
3.9.0
Definition at line 16 of file media-template.php.
References endforeach, width, and wp_get_audio_extensions().
Referenced by wp_print_media_templates().
wp_underscore_video_template ()
Output the markup for a video tag to be used in an Underscore template when data.model is passed.
Since
3.9.0
Definition at line 50 of file media-template.php.
References $value, endforeach, height, width, and wp_get_video_extensions().
Referenced by wp_print_media_templates().