GravityView: menu-header.php File Reference
menu-header.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_menu_output ($menu, $submenu, $submenu_as_parent=true)
Display menu.
Variables
global $menu
For when admin-header is included from within a function.
global $parent_file = apply_filters('parent_file', $parent_file)
Filter the parent file of an admin menu sub-menu item.
$self = preg_replace('|^.*/wp-admin/network/|i', '', $_SERVER['PHP_SELF'])
The current page.
global $submenu
global $submenu_file = apply_filters('submenu_file', $submenu_file, $parent_file)
Filter the file of an admin menu sub-menu item.
Function Documentation
_wp_menu_output ($menu, $submenu, $submenu_as_parent = true)
Display menu.
private
Since
2.7.0
string $self string $parent_file string $submenu_file string $plugin_page string $typenow
Parameters
array $menu
array $submenu
bool $submenu_as_parent
Definition at line 68 of file menu-header.php.
References $class, $id, $menu, $parent_file, $plugin_page, $self, $submenu, $submenu_file, $title, $typenow, elseif, esc_attr(), esc_attr_e(), li, and n.
Variable Documentation
global $menu
For when admin-header is included from within a function.
array $menu array $submenu string $parent_file string $submenu_file
Definition at line 27 of file menu-header.php.
Referenced by _wp_menu_output().
$parent_file = apply_filters('parent_file', $parent_file)
Filter the parent file of an admin menu sub-menu item.
Allows plugins to move sub-menu items around.
Since
MU
Parameters
string $parent_file The parent file.
Definition at line 27 of file menu-header.php.
Referenced by _wp_menu_output().
$self = preg_replace('|^.*/wp-admin/network/|i', '', $_SERVER['PHP_SELF'])
The current page.
string $self
Definition at line 14 of file menu-header.php.
Referenced by _wp_menu_output(), WP\parse_request(), Tests_REST_Server\test_response_to_data_links(), and wp_terms_checklist().
global $submenu
Definition at line 27 of file menu-header.php.
Referenced by _wp_menu_output(), add_submenu_page(), get_admin_page_parent(), get_admin_page_title(), remove_submenu_page(), user_can_access_admin_page(), and wp_widgets_add_menu().
$submenu_file = apply_filters('submenu_file', $submenu_file, $parent_file)
Filter the file of an admin menu sub-menu item.
Since
4.4.0
Parameters
string $submenu_file The submenu file.
string $parent_file The submenu item's parent file.
Definition at line 27 of file menu-header.php.
Referenced by _wp_menu_output().