GravityView: meta-boxes.php File Reference
meta-boxes.php File Reference
Functions
attachment_id3_data_meta_box ($post)
Display fields for ID3 data.
attachment_submit_meta_box ($post)
Display attachment submit form fields.
link_advanced_meta_box ($link)
Display advanced link options form fields.
link_categories_meta_box ($link)
Display link categories form fields.
link_submit_meta_box ($link)
Display link create form fields.
link_target_meta_box ($link)
Display form fields for changing link target.
link_xfn_meta_box ($link)
Display xfn form fields.
page_attributes_meta_box ($post)
Display page attributes form fields.
post_author_meta_box ($post)
Display form field with list of authors.
post_categories_meta_box ($post, $box)
Display post categories form fields.
post_comment_meta_box ($post)
Display comments for post.
post_comment_meta_box_thead ($result)
Display comments for post table header.
post_comment_status_meta_box ($post)
Display comments status form fields.
post_custom_meta_box ($post)
Display custom fields form fields.
post_excerpt_meta_box ($post)
Display post excerpt form fields.
post_format_meta_box ($post, $box)
Display post format form elements.
post_revisions_meta_box ($post)
Display list of revisions.
post_slug_meta_box ($post)
Display slug form fields.
post_submit_meta_box ($post, $args=array())
Displays post submit form fields.
post_tags_meta_box ($post, $box)
Display post tags form fields.
post_thumbnail_meta_box ($post)
Display post thumbnail meta box.
post_trackback_meta_box ($post)
Display trackback links form fields.
xfn_check ($class, $value= '', $deprecated= '')
Display checked checkboxes attribute for xfn microformat options.
Function Documentation
attachment_id3_data_meta_box ($post)
Display fields for ID3 data.
Since
3.9.0
Parameters
WP_Post $post A post object.
Definition at line 1191 of file meta-boxes.php.
References $label, $post, endforeach, input, label, name, wp_get_attachment_id3_keys(), and wp_get_attachment_metadata().
attachment_submit_meta_box ($post)
Display attachment submit form fields.
Since
3.5.0
Parameters
object $post
Fires after the 'Uploaded on' section of the Save meta box in the attachment editing screen.
Since
3.5.0
Definition at line 290 of file meta-boxes.php.
References $datef, $post, __, _x, current_user_can(), date_i18n(), do_action(), get_delete_post_link(), input, name, null, and submit_button().
link_advanced_meta_box ($link)
Display advanced link options form fields.
Since
2.6.0
Parameters
object $link
Definition at line 1140 of file meta-boxes.php.
References $link, _e, input, label, name, size, and textarea.
link_categories_meta_box ($link)
Display link categories form fields.
Since
2.6.0
Parameters
object $link
Definition at line 921 of file meta-boxes.php.
References $link, _e, input, label, li, name, wp_link_category_checklist(), wp_nonce_field(), and wp_popular_terms_checklist().
link_submit_meta_box ($link)
Display link create form fields.
Since
2.7.0
Parameters
object $link
This action is documented in wp-admin/includes/meta-boxes.php
Fires at the end of the Publish box in the Link editing screen.
Since
2.5.0
Definition at line 852 of file meta-boxes.php.
References $link, __, _e, checked(), current_user_can(), do_action(), input, label, n, name, and submit_button().
link_target_meta_box ($link)
Display form fields for changing link target.
Since
2.6.0
Parameters
object $link
Definition at line 967 of file meta-boxes.php.
References $link, _e, input, label, and name.
link_xfn_meta_box ($link)
Display xfn form fields.
Since
2.6.0
Parameters
object $link
Definition at line 1022 of file meta-boxes.php.
References _e, input, label, name, and xfn_check().
page_attributes_meta_box ($post)
Display page attributes form fields.
Since
2.7.0
Parameters
object $post
Filter the arguments used to generate a Pages drop-down element.
Since
3.3.0
See also
wp_dropdown_pages()
Parameters
array $dropdown_args Array of arguments used to generate the pages drop-down.
WP_Post $post The current WP_Post object.
Fires immediately after the heading inside the 'Template' section of the 'Page Attributes' meta box.
Since
4.4.0
Parameters
string $template The template used for the current post.
WP_Post $post The current post.
Filter the title of the default page template displayed in the drop-down.
Since
4.1.0
Parameters
string $label The display value for the default page template title.
string $context Where the option label is displayed. Possible values include 'meta-box' or 'quick-edit'.
Definition at line 769 of file meta-boxes.php.
References $dropdown_args, $post, $post_type_object, $template, __, _e, apply_filters(), do_action(), esc_html, get_current_screen(), get_option(), get_page_templates(), get_post_type_object(), input, label, name, page_template_dropdown(), size, and wp_dropdown_pages().
post_author_meta_box ($post)
Display form field with list of authors.
Since
2.6.0
int $user_ID
Parameters
object $post
Definition at line 735 of file meta-boxes.php.
References $post, $user_ID, _e, label, and wp_dropdown_users().
post_categories_meta_box ($post, $box)
Display post categories form fields.
Since
2.6.0
Parameters
WP_Post $post Post object.
array $box { Categories meta box arguments.
string $id Meta box ID. string $title Meta box title. callable $callback Meta box display callback. array $args { Extra meta box arguments.
string $taxonomy Taxonomy. Default 'category'. } }
Filter the arguments for the taxonomy parent dropdown on the Post Edit page.
Since
4.4.0
Parameters
array $parent_dropdown_args { Optional. Array of arguments to generate parent dropdown.
string $taxonomy Name of the taxonomy to retrieve. bool $hide_if_empty True to skip generating markup if no categories are found. Default 0. string $name Value for the 'name' attribute of the select element. Default "new{$tax_name}_parent". string $orderby Which column to use for ordering terms. Default 'name'. bool|int $hierarchical Whether to traverse the taxonomy hierarchy. Default 1. string $show_option_none Text to display for the "none" option. Default "&mdash; {$parent} &mdash;", where $parent is 'parent_item' taxonomy label. }
Definition at line 473 of file meta-boxes.php.
References $name, $post, __, _e, apply_filters(), current_user_can(), endif, esc_attr(), get_taxonomy(), input, label, li, name, wp_dropdown_categories(), wp_nonce_field(), wp_parse_args(), wp_popular_terms_checklist(), and wp_terms_checklist().
post_comment_meta_box ($post)
Display comments for post.
Since
2.8.0
Parameters
object $post
Definition at line 683 of file meta-boxes.php.
References $post, $wp_list_table, __, _e, _get_list_table(), get_comments(), get_current_screen(), get_hidden_meta_boxes(), wp_comment_trashnotice(), and wp_nonce_field().
post_comment_meta_box_thead ($result)
Display comments for post table header.
Since
3.0.0
Parameters
array $result table header rows
Returns
array
Definition at line 671 of file meta-boxes.php.
post_comment_status_meta_box ($post)
Display comments status form fields.
Since
2.6.0
Parameters
object $post
Fires at the end of the Discussion meta box on the post editing screen.
Since
3.1.0
Parameters
WP_Post $post WP_Post object of the current post.
Definition at line 643 of file meta-boxes.php.
References $post, __, _e, checked(), do_action(), input, label, and name.
post_custom_meta_box ($post)
Display custom fields form fields.
Since
2.6.0
Parameters
object $post
Definition at line 619 of file meta-boxes.php.
References $metadata, $post, $value, _e, current_user_can(), has_meta(), is_protected_meta(), list_meta(), and meta_form().
post_excerpt_meta_box ($post)
Display post excerpt form fields.
Since
2.6.0
Parameters
object $post
Definition at line 574 of file meta-boxes.php.
References $post, _e, label, name, and textarea.
post_format_meta_box ($post, $box)
Display post format form elements.
Since
3.1.0
Parameters
WP_Post $post Post object.
array $box { Post formats meta box arguments.
string $id Meta box ID. string $title Meta box title. callable $callback Meta box display callback. array $args Extra meta box arguments. }
Definition at line 367 of file meta-boxes.php.
References $format, $post, $post_formats, _e, checked(), current_theme_supports(), endforeach, endif, esc_html, get_post_format(), get_post_format_string(), get_theme_support(), input, label, name, and post_type_supports().
post_revisions_meta_box ($post)
Display list of revisions.
Since
2.6.0
Parameters
object $post
Definition at line 756 of file meta-boxes.php.
References $post, and wp_list_post_revisions().
post_slug_meta_box ($post)
Display slug form fields.
Since
2.6.0
Parameters
object $post
This filter is documented in wp-admin/edit-tag-form.php
Definition at line 718 of file meta-boxes.php.
References $post, _e, apply_filters(), input, label, name, and size.
post_submit_meta_box ($post, $args = array())
Displays post submit form fields.
Since
2.7.0
string $action
Parameters
WP_Post $post Current post object.
array $args { Array of arguments for building the post submit meta box.
string $id Meta box ID. string $title Meta box title. callable $callback Meta box display callback. array $args Extra meta box arguments. }
Fires before the post time/date setting in the Publish meta box.
Since
4.4.0
Parameters
WP_Post $post WP_Post object for the current post.
Fires after the post time/date setting in the Publish meta box.
Since
2.9.0
4.4.0 Added the $post parameter.
Parameters
WP_Post $post WP_Post object for the current post.
Fires at the beginning of the publishing actions section of the Publish meta box.
Since
2.7.0
Definition at line 22 of file meta-boxes.php.
References $action, $datef, $post, $post_type, $post_type_object, __, _e, _ex(), checked(), current_time(), current_user_can(), date_i18n(), do_action(), elseif, endif, esc_html, esc_url, get_post_type_object(), get_preview_post_link(), input, is_post_type_viewable(), is_sticky(), label, name, number_format_i18n(), selected(), submit_button(), touch_time(), and wp_revisions_to_keep().
post_tags_meta_box ($post, $box)
Display post tags form fields.
Since
2.6.0
Parameters
WP_Post $post Post object.
array $box { Tags meta box arguments.
string $id Meta box ID. string $title Meta box title. callable $callback Meta box display callback. array $args { Extra meta box arguments.
string $taxonomy Taxonomy. Default 'post_tag'. } }
Definition at line 412 of file meta-boxes.php.
References $post, _x, current_user_can(), disabled(), endif, esc_attr(), get_taxonomy(), get_terms_to_edit(), input, label, name, size, str_replace, textarea, and wp_parse_args().
post_thumbnail_meta_box ($post)
Display post thumbnail meta box.
Since
2.9.0
Parameters
WP_Post $post A post object.
Definition at line 1179 of file meta-boxes.php.
References $post, $thumbnail_id, _wp_post_thumbnail_html(), and get_post_meta().
post_trackback_meta_box ($post)
Display trackback links form fields.
Since
2.6.0
Parameters
object $post
Definition at line 588 of file meta-boxes.php.
References $post, __, _e, esc_attr(), esc_html, label, and str_replace.
xfn_check ($class, $value = '', $deprecated = '')
Display checked checkboxes attribute for xfn microformat options.
Since
1.0.1
object $link
Parameters
string $class
string $value
mixed $deprecated Never used.
Definition at line 994 of file meta-boxes.php.
References $class, $deprecated, $link, $value, and _deprecated_argument().
Referenced by link_xfn_meta_box().