GravityView: meta.php File Reference
meta.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_meta_table ($type)
Retrieve the name of the metadata table for the specified object type.
add_metadata ($meta_type, $object_id, $meta_key, $meta_value, $unique=false)
Add metadata for the specified object.
delete_metadata ($meta_type, $object_id, $meta_key, $meta_value= '', $delete_all=false)
Delete metadata for the specified object.
delete_metadata_by_mid ($meta_type, $meta_id)
Delete meta data by meta ID.
get_meta_sql ($meta_query, $type, $primary_table, $primary_id_column, $context=null)
Given a meta query, generates SQL clauses to be appended to a main query.
get_metadata ($meta_type, $object_id, $meta_key= '', $single=false)
Retrieve metadata for the specified object.
get_metadata_by_mid ($meta_type, $meta_id)
Get meta data by meta ID.
is_protected_meta ($meta_key, $meta_type=null)
Determine whether a meta key is protected.
metadata_exists ($meta_type, $object_id, $meta_key)
Determine if a meta key is set for a given object.
register_meta ($meta_type, $meta_key, $sanitize_callback, $auth_callback=null)
Register meta key.
sanitize_meta ($meta_key, $meta_value, $meta_type)
Sanitize meta value.
update_meta_cache ($meta_type, $object_ids)
Update the metadata cache for the specified objects.
update_metadata ($meta_type, $object_id, $meta_key, $meta_value, $prev_value= '')
Update metadata for the specified object.
update_metadata_by_mid ($meta_type, $meta_id, $meta_value, $meta_key=false)
Update meta data by meta ID.
Function Documentation
_get_meta_table ($type)
Retrieve the name of the metadata table for the specified object type.
Since
2.9.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $type Type of object to get metadata table for (e.g., comment, post, or user)
Returns
string|false Metadata table name, or false if no metadata table exists
Definition at line 880 of file meta.php.
References $wpdb.
Referenced by add_metadata(), delete_metadata(), delete_metadata_by_mid(), get_metadata_by_mid(), WP_Meta_Query\get_sql(), update_meta_cache(), update_metadata(), and update_metadata_by_mid().
add_metadata ($meta_type, $object_id, $meta_key, $meta_value, $unique = false)
Add metadata for the specified object.
Since
2.9.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, or user)
int $object_id ID of the object metadata is for
string $meta_key Metadata key
mixed $meta_value Metadata value. Must be serializable if non-scalar.
bool $unique Optional, default is false. Whether the specified metadata key should be unique for the object. If true, and the object already has a value for the specified metadata key, no change will be made.
Returns
int|false The meta ID on success, false on failure.
Filter whether to add metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user). Returning a non-null value will effectively short-circuit the function.
Since
3.1.0
Parameters
null | bool $check Whether to allow adding metadata for the given type.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value. Must be serializable if non-scalar.
bool $unique Whether the specified meta key should be unique for the object. Optional. Default false.
Fires immediately before meta of a specific type is added.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user).
Since
3.1.0
Parameters
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value.
Fires immediately after meta of a specific type is added.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user).
Since
2.9.0
Parameters
int $mid The meta ID after successful update.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value.
Definition at line 30 of file meta.php.
References $wpdb, _get_meta_table(), absint(), apply_filters(), do_action(), maybe_serialize(), null, sanitize_key(), sanitize_meta(), wp_cache_delete(), and wp_unslash().
Referenced by add_comment_meta(), add_post_meta(), add_term_meta(), add_user_meta(), and update_metadata().
delete_metadata ($meta_type, $object_id, $meta_key, $meta_value = '', $delete_all = false)
Delete metadata for the specified object.
Since
2.9.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, or user)
int $object_id ID of the object metadata is for
string $meta_key Metadata key
mixed $meta_value Optional. Metadata value. Must be serializable if non-scalar. If specified, only delete metadata entries with this value. Otherwise, delete all entries with the specified meta_key. Pass null,false`, or an empty string to skip this check. (For backward compatibility, it is not possible to pass an empty string to delete those entries with an empty string for a value.)
bool $delete_all Optional, default is false. If true, delete matching metadata entries for all objects, ignoring the specified object_id. Otherwise, only delete matching metadata entries for the specified object_id.
Returns
bool True on successful delete, false on failure.
Filter whether to delete metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user). Returning a non-null value will effectively short-circuit the function.
Since
3.1.0
Parameters
null | bool $delete Whether to allow metadata deletion of the given type.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value. Must be serializable if non-scalar.
bool $delete_all Whether to delete the matching metadata entries for all objects, ignoring the specified $object_id. Default false.
Fires immediately before deleting metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user).
Since
3.1.0
Parameters
array $meta_ids An array of metadata entry IDs to delete.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value.
Fires immediately before deleting metadata for a post.
Since
2.9.0
Parameters
array $meta_ids An array of post metadata entry IDs to delete.
Fires immediately after deleting metadata of a specific type.
The dynamic portion of the hook name, $meta_type, refers to the meta object type (comment, post, or user).
Since
2.9.0
Parameters
array $meta_ids An array of deleted metadata entry IDs.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value.
Fires immediately after deleting metadata for a post.
Since
2.9.0
Parameters
array $meta_ids An array of deleted post metadata entry IDs.
Definition at line 310 of file meta.php.
References $count, $wpdb, _get_meta_table(), absint(), apply_filters(), do_action(), maybe_serialize(), null, sanitize_key(), wp_cache_delete(), and wp_unslash().
Referenced by delete_comment_meta(), delete_post_meta(), delete_post_meta_by_key(), delete_term_meta(), delete_user_meta(), WP_User_Meta_Session_Tokens\drop_sessions(), install_blog(), and wp_delete_attachment().
delete_metadata_by_mid ($meta_type, $meta_id)
Delete meta data by meta ID.
Since
3.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, term, or user).
int $meta_id ID for a specific meta row
Returns
bool True on successful delete, false on failure.
This action is documented in wp-includes/meta.php
Fires immediately before deleting post or comment metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (post or comment).
Since
3.4.0
Parameters
int $meta_id ID of the metadata entry to delete.
This action is documented in wp-includes/meta.php
Fires immediately after deleting post or comment metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (post or comment).
Since
3.4.0
Parameters
int $meta_ids Deleted metadata entry ID.
Definition at line 698 of file meta.php.
References $wpdb, _get_meta_table(), absint(), do_action(), get_metadata_by_mid(), sanitize_key(), and wp_cache_delete().
Referenced by delete_meta(), do_all_pings(), do_enclose(), wp_xmlrpc_server\set_custom_fields(), wp_delete_attachment(), wp_delete_comment(), wp_delete_post(), wp_delete_term(), wp_delete_user(), and wpmu_delete_user().
get_meta_sql ($meta_query, $type, $primary_table, $primary_id_column, $context = null)
Given a meta query, generates SQL clauses to be appended to a main query.
Since
3.2.0
See also
WP_Meta_Query
Parameters
array $meta_query A meta query.
string $type Type of meta.
string $primary_table Primary database table name.
string $primary_id_column Primary ID column name.
object $context Optional. The main query object
Returns
array Associative array of JOIN and WHERE SQL.
Definition at line 865 of file meta.php.
get_metadata ($meta_type, $object_id, $meta_key = '', $single = false)
Retrieve metadata for the specified object.
Since
2.9.0
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, or user)
int $object_id ID of the object metadata is for
string $meta_key Optional. Metadata key. If not specified, retrieve all metadata for the specified object.
bool $single Optional, default is false. If true, return only the first value of the specified meta_key. This parameter has no effect if meta_key is not specified.
Returns
mixed Single metadata value, or array of values
Filter whether to retrieve metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user). Returning a non-null value will effectively short-circuit the function.
Since
3.1.0
Parameters
null | array | string $value The value get_metadata() should return - a single metadata value, or an array of values.
int $object_id Object ID.
string $meta_key Meta key.
bool $single Whether to return only the first value of the specified $meta_key.
Definition at line 458 of file meta.php.
References absint(), apply_filters(), maybe_unserialize(), null, update_meta_cache(), and wp_cache_get().
Referenced by get_comment_meta(), get_post_meta(), get_term_meta(), get_user_meta(), and update_metadata().
get_metadata_by_mid ($meta_type, $meta_id)
Get meta data by meta ID.
Since
3.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, term, or user).
int $meta_id ID for a specific meta row
Returns
object|false Meta object or false.
Definition at line 564 of file meta.php.
References $wpdb, _get_meta_table(), absint(), and maybe_unserialize().
Referenced by delete_metadata_by_mid(), get_post_meta_by_id(), wp_xmlrpc_server\set_custom_fields(), update_metadata_by_mid(), wp_ajax_add_meta(), and wp_ajax_delete_meta().
is_protected_meta ($meta_key, $meta_type = null)
Determine whether a meta key is protected.
Since
3.1.3
Parameters
string $meta_key Meta key
string | null $meta_type
Returns
bool True if the key is protected, false otherwise.
Filter whether a meta key is protected.
Since
3.2.0
Parameters
bool $protected Whether the key is protected. Default false.
string $meta_key Meta key.
string $meta_type Meta type.
Definition at line 900 of file meta.php.
References apply_filters().
Referenced by _list_meta_row(), add_meta(), edit_post(), map_meta_cap(), meta_form(), post_custom_meta_box(), register_meta(), the_meta(), wp_ajax_add_meta(), and wp_ajax_delete_meta().
metadata_exists ($meta_type, $object_id, $meta_key)
Determine if a meta key is set for a given object.
Since
3.3.0
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, or user)
int $object_id ID of the object metadata is for
string $meta_key Metadata key.
Returns
bool True of the key is set, false if not.
This filter is documented in wp-includes/meta.php
Definition at line 525 of file meta.php.
References absint(), apply_filters(), null, update_meta_cache(), and wp_cache_get().
Referenced by WP_Post\__isset(), and WP_User\__isset().
register_meta ($meta_type, $meta_key, $sanitize_callback, $auth_callback = null)
Register meta key.
Since
3.3.0
Parameters
string $meta_type Type of meta
string $meta_key Meta key
string | array $sanitize_callback A function or method to call when sanitizing the value of $meta_key.
string | array $auth_callback Optional. A function or method to call when performing edit_post_meta, add_post_meta, and delete_post_meta capability checks.
Definition at line 954 of file meta.php.
References add_filter(), and is_protected_meta().
sanitize_meta ($meta_key, $meta_value, $meta_type)
Sanitize meta value.
Since
3.1.3
Parameters
string $meta_key Meta key
mixed $meta_value Meta value to sanitize
string $meta_type Type of meta
Returns
mixed Sanitized $meta_value
Filter the sanitization of a specific meta key of a specific meta type.
The dynamic portions of the hook name, $meta_type, and $meta_key, refer to the metadata object type (comment, post, or user) and the meta key value, respectively.
Since
3.3.0
Parameters
mixed $meta_value Meta value to sanitize.
string $meta_key Meta key.
string $meta_type Meta type.
Definition at line 925 of file meta.php.
References apply_filters().
Referenced by add_metadata(), update_metadata(), and update_metadata_by_mid().
update_meta_cache ($meta_type, $object_ids)
Update the metadata cache for the specified objects.
Since
2.9.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, or user)
int | array $object_ids Array or comma delimited list of object IDs to update cache for
Returns
array|false Metadata cache for the specified objects, or false on failure.
Definition at line 785 of file meta.php.
References $id, $wpdb, _get_meta_table(), ARRAY_A, sanitize_key(), wp_cache_add(), and wp_cache_get().
Referenced by get_metadata(), get_user_metavalues(), WP_Query\lazyload_comment_meta(), metadata_exists(), update_comment_cache(), update_postmeta_cache(), update_termmeta_cache(), and wp_make_content_images_responsive().
update_metadata ($meta_type, $object_id, $meta_key, $meta_value, $prev_value = '')
Update metadata for the specified object.
If no value already exists for the specified object ID and metadata key, the metadata will be added.
Since
2.9.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, or user)
int $object_id ID of the object metadata is for
string $meta_key Metadata key
mixed $meta_value Metadata value. Must be serializable if non-scalar.
mixed $prev_value Optional. If specified, only update existing metadata entries with the specified value. Otherwise, update all entries.
Returns
int|bool Meta ID if the key didn't exist, true on successful update, false on failure.
Filter whether to update metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user). Returning a non-null value will effectively short-circuit the function.
Since
3.1.0
Parameters
null | bool $check Whether to allow updating metadata for the given type.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value. Must be serializable if non-scalar.
mixed $prev_value Optional. If specified, only update existing metadata entries with the specified value. Otherwise, update all entries.
Fires immediately before updating metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user).
Since
2.9.0
Parameters
int $meta_id ID of the metadata entry to update.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value.
Fires immediately before updating a post's metadata.
Since
2.9.0
Parameters
int $meta_id ID of metadata entry to update.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value.
Fires immediately after updating metadata of a specific type.
The dynamic portion of the hook, $meta_type, refers to the meta object type (comment, post, or user).
Since
2.9.0
Parameters
int $meta_id ID of updated metadata entry.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value.
Fires immediately after updating a post's metadata.
Since
2.9.0
Parameters
int $meta_id ID of updated metadata entry.
int $object_id Object ID.
string $meta_key Meta key.
mixed $meta_value Meta value.
Definition at line 143 of file meta.php.
References $wpdb, _get_meta_table(), absint(), add_metadata(), apply_filters(), do_action(), get_metadata(), maybe_serialize(), null, sanitize_key(), sanitize_meta(), wp_cache_delete(), and wp_unslash().
Referenced by update_comment_meta(), update_post_meta(), update_term_meta(), and update_user_meta().
update_metadata_by_mid ($meta_type, $meta_id, $meta_value, $meta_key = false)
Update meta data by meta ID.
Since
3.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $meta_type Type of object metadata is for (e.g., comment, post, or user)
int $meta_id ID for a specific meta row
string $meta_value Metadata value
string $meta_key Optional, you can provide a meta key to update it
Returns
bool True on successful update, false on failure.
This action is documented in wp-includes/meta.php
This action is documented in wp-includes/meta.php
This action is documented in wp-includes/meta.php
This action is documented in wp-includes/meta.php
Definition at line 607 of file meta.php.
References $wpdb, _get_meta_table(), absint(), do_action(), elseif, get_metadata_by_mid(), maybe_serialize(), sanitize_key(), sanitize_meta(), and wp_cache_delete().
Referenced by wp_xmlrpc_server\set_custom_fields(), update_meta(), and wp_ajax_add_meta().