GravityView: ms-blogs.php File Reference
ms-blogs.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_update_blog_date_on_post_delete ($post_id)
Handler for updating the blog date when a published post is deleted.
_update_blog_date_on_post_publish ($new_status, $old_status, $post)
Handler for updating the blog date when a post is published or an already published post is changed.
_update_posts_count_on_delete ($post_id)
Handler for updating the blog posts count date when a post is deleted.
_update_posts_count_on_transition_post_status ($new_status, $old_status)
Handler for updating the blog posts count date when a post status changes.
add_blog_option ($id, $option, $value)
Add a new option for a given blog id.
clean_blog_cache ($blog)
Clean the blog cache.
delete_blog_option ($id, $option)
Removes option by name for a given blog id.
get_blog_details ($fields=null, $get_all=true)
Retrieve the details for a blog from the blogs table and blog options.
get_blog_option ($id, $option, $default=false)
Retrieve option value for a given blog id based on name of option.
get_blog_status ($id, $pref)
Get a blog details field.
get_blogaddress_by_id ($blog_id)
Get a full blog URL, given a blog id.
get_blogaddress_by_name ($blogname)
Get a full blog URL, given a blog name.
get_id_from_blogname ($slug)
Given a blog's (subdomain or directory) slug, retrieve its id.
get_last_updated ($deprecated= '', $start=0, $quantity=40)
Get a list of most recently updated blogs.
is_archived ($id)
Check if a particular blog is archived.
ms_is_switched ()
Determines if switch_to_blog() is in effect.
refresh_blog_details ($blog_id=0)
Clear the blog details cache.
restore_current_blog ()
Restore the current blog, after calling switch_to_blog()
switch_to_blog ($new_blog, $deprecated=null)
Switch the current blog.
update_archived ($id, $archived)
Update the 'archived' status of a particular blog.
update_blog_details ($blog_id, $details=array())
Update the details for a blog.
update_blog_option ($id, $option, $value, $deprecated=null)
Update an option for a particular blog.
update_blog_status ($blog_id, $pref, $value, $deprecated=null)
Update a blog details field.
wpmu_update_blogs_date ()
Update the last_updated field for the current blog.
Function Documentation
_update_blog_date_on_post_delete ($post_id)
Handler for updating the blog date when a published post is deleted.
Since
3.4.0
Parameters
int $post_id Post ID
Definition at line 938 of file ms-blogs.php.
References $post, $post_id, get_post(), get_post_type_object(), and wpmu_update_blogs_date().
_update_blog_date_on_post_publish ($new_status, $old_status, $post)
Handler for updating the blog date when a post is published or an already published post is changed.
Since
3.3.0
Parameters
string $new_status The new post status
string $old_status The old post status
object $post Post object
Definition at line 916 of file ms-blogs.php.
References $post, get_post_type_object(), and wpmu_update_blogs_date().
_update_posts_count_on_delete ($post_id)
Handler for updating the blog posts count date when a post is deleted.
Since
4.0.0
Parameters
int $post_id Post ID.
Definition at line 960 of file ms-blogs.php.
References $post, $post_id, get_post(), and update_posts_count().
_update_posts_count_on_transition_post_status ($new_status, $old_status)
Handler for updating the blog posts count date when a post status changes.
Since
4.0.0
Parameters
string $new_status The status the post is changing to.
string $old_status The status the post is changing from.
Definition at line 978 of file ms-blogs.php.
References update_posts_count().
add_blog_option ($id, $option, $value)
Add a new option for a given blog id.
You do not need to serialize values. If the value needs to be serialized, then it will be serialized before it is inserted into the database. Remember, resources can not be serialized or added as an option.
You can create options without values and then update the values later. Existing options will not be updated and checks are performed to ensure that you aren't adding a protected WordPress option. Care should be taken to not name options the same as the ones which are protected.
Since
MU
Parameters
int $id A blog ID. Can be null to refer to the current blog.
string $option Name of option to add. Expected to not be SQL-escaped.
mixed $value Optional. Option value, can be anything. Expected to not be SQL-escaped.
Returns
bool False if option was not added and true if option was added.
Definition at line 516 of file ms-blogs.php.
References $id, $option, $value, add_option(), get_current_blog_id(), restore_current_blog(), and switch_to_blog().
clean_blog_cache ($blog)
Clean the blog cache.
Since
3.5.0
Parameters
stdClass $blog The blog details as returned from get_blog_details()
Definition at line 441 of file ms-blogs.php.
References $blog, $blog_id, and wp_cache_delete().
Referenced by refresh_blog_details(), and wpmu_delete_blog().
delete_blog_option ($id, $option)
Removes option by name for a given blog id.
Prevents removal of protected WordPress options.
Since
MU
Parameters
int $id A blog ID. Can be null to refer to the current blog.
string $option Name of option to remove. Expected to not be SQL-escaped.
Returns
bool True, if option is successfully deleted. False on failure.
Definition at line 541 of file ms-blogs.php.
References $id, $option, delete_option(), get_current_blog_id(), restore_current_blog(), and switch_to_blog().
get_blog_details ($fields = null, $get_all = true)
Retrieve the details for a blog from the blogs table and blog options.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
int | string | array $fields Optional. A blog ID, a blog slug, or an array of fields to query against. If not specified the current blog ID is used.
bool $get_all Whether to retrieve all details or only the details in the blogs table. Default is true.
Returns
object|false Blog details on success. False on failure.
Filter a blog's details.
Since
MU
Parameters
object $details The blog details.
Definition at line 120 of file ms-blogs.php.
References $blog, $blog_id, $details, $wpdb, apply_filters(), elseif, get_current_blog_id(), get_id_from_blogname(), get_option(), is_subdomain_install(), restore_current_blog(), switch_to_blog(), wp_cache_delete(), wp_cache_get(), and wp_cache_set().
Referenced by wp_xmlrpc_server\_multisite_getUsersBlogs(), add_user_to_blog(), get_active_blog_for_user(), get_blog_status(), get_blogaddress_by_id(), get_blogs_of_user(), get_dashboard_blog(), WP_UnitTest_Factory_For_Blog\get_object_by_id(), is_user_member_of_blog(), ms_site_check(), refresh_blog_details(), WP_Importer\set_blog(), update_blog_details(), and wpmu_delete_blog().
get_blog_option ($id, $option, $default = false)
Retrieve option value for a given blog id based on name of option.
If the option does not exist or does not have a value, then the return value will be false. This is useful to check whether you need to install an option and is commonly used during installation of plugin options and to test whether upgrading is required.
If the option was serialized then it will be unserialized when it is returned.
Since
MU
Parameters
int $id A blog ID. Can be null to refer to the current blog.
string $option Name of option to retrieve. Expected to not be SQL-escaped.
mixed $default Optional. Default value to return if the option does not exist.
Returns
mixed Value set for the option.
Filter a blog option value.
The dynamic portion of the hook name, $option, refers to the blog option name.
Since
3.5.0
Parameters
string $value The option value.
int $id Blog ID.
Definition at line 471 of file ms-blogs.php.
References $default, $id, $option, $value, apply_filters(), get_current_blog_id(), get_option(), restore_current_blog(), and switch_to_blog().
Referenced by get_rest_url(), and install_blog().
get_blog_status ($id, $pref)
Get a blog details field.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
int $id The blog id
string $pref A field name
Returns
bool|string|null $value
Definition at line 876 of file ms-blogs.php.
References $details, $id, $wpdb, and get_blog_details().
Referenced by is_archived().
get_blogaddress_by_id ($blog_id)
Get a full blog URL, given a blog id.
Since
MU
Parameters
int $blog_id Blog ID
Returns
string Full URL of the blog if found. Empty string if not.
Definition at line 40 of file ms-blogs.php.
References $blog_id, esc_url, and get_blog_details().
Referenced by install_blog(), and wpmu_welcome_notification().
get_blogaddress_by_name ($blogname)
Get a full blog URL, given a blog name.
Since
MU
Parameters
string $blogname The (subdomain or directory) name
Returns
string
Definition at line 61 of file ms-blogs.php.
References $url, esc_url, is_subdomain_install(), and network_home_url().
get_id_from_blogname ($slug)
Given a blog's (subdomain or directory) slug, retrieve its id.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $slug
Returns
int A blog id
Definition at line 84 of file ms-blogs.php.
References $blog_id, $current_site, $path, $wpdb, get_current_site(), is_subdomain_install(), wp_cache_get(), and wp_cache_set().
Referenced by avoid_blog_page_permalink_collision(), and get_blog_details().
get_last_updated ($deprecated = '', $start = 0, $quantity = 40)
Get a list of most recently updated blogs.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
mixed $deprecated Not used
int $start The offset
int $quantity The maximum number of blogs to retrieve. Default is 40.
Returns
array The list of blogs
Definition at line 898 of file ms-blogs.php.
References $deprecated, $wpdb, _deprecated_argument(), and ARRAY_A.
is_archived ($id)
Check if a particular blog is archived.
Since
MU
Parameters
int $id The blog id
Returns
string Whether the blog is archived or not
Definition at line 771 of file ms-blogs.php.
References $id, and get_blog_status().
ms_is_switched ()
Determines if switch_to_blog() is in effect.
Since
3.5.0
array $_wp_switched_stack
Returns
bool True if switched, false otherwise.
Definition at line 759 of file ms-blogs.php.
References $GLOBALS.
Referenced by get_site_icon_url(), WP_UnitTestCase\tearDown(), update_home_siteurl(), and wp_upload_dir().
refresh_blog_details ($blog_id = 0)
Clear the blog details cache.
Since
MU
Parameters
int $blog_id Optional. Blog ID. Defaults to current blog.
Fires after the blog details cache is cleared.
Since
3.4.0
Parameters
int $blog_id Blog ID.
Definition at line 257 of file ms-blogs.php.
References $blog_id, $details, clean_blog_cache(), do_action(), get_blog_details(), get_current_blog_id(), null, and object.
Referenced by insert_blog(), update_blog_details(), update_blog_option(), update_blog_status(), and upgrade_280().
restore_current_blog ()
Restore the current blog, after calling switch_to_blog()
See also
switch_to_blog()
Since
MU
wpdb $wpdb array $_wp_switched_stack int $blog_id bool $switched string $table_prefix WP_Object_Cache $wp_object_cache
Returns
bool True on success, false if we're already on the current blog
This filter is documented in wp-includes/ms-blogs.php
This filter is documented in wp-includes/ms-blogs.php
Definition at line 692 of file ms-blogs.php.
References $blog, $current_user, $GLOBALS, $wpdb, did_action(), do_action(), wp_cache_add_global_groups(), wp_cache_add_non_persistent_groups(), wp_cache_init(), wp_cache_switch_to_blog(), and wp_roles().
Referenced by add_blog_option(), add_user_to_blog(), WP_MS_Sites_List_Table\column_blogname(), create_empty_blog(), current_user_can_for_blog(), delete_blog_option(), WP_Theme\get_allowed_on_site(), get_blog_details(), get_blog_option(), get_blog_permalink(), get_blog_post(), get_home_url(), get_site_icon_url(), get_site_url(), WP_Users_List_Table\get_views(), GV_Unit_Tests_Bootstrap\load_rest_api(), newblog_notify_siteadmin(), remove_user_from_blog(), rest_api_activation(), rest_api_deactivation(), WP_UnitTestCase\tearDown(), update_blog_details(), update_blog_option(), upload_space_setting(), wp_admin_bar_my_sites_menu(), wp_xmlrpc_server\wp_getUsersBlogs(), wpmu_create_blog(), wpmu_delete_blog(), and wpmu_delete_user().
switch_to_blog ($new_blog, $deprecated = null)
Switch the current blog.
This function is useful if you need to pull posts, or other information, from other blogs. You can switch back afterwards using restore_current_blog().
Things that aren't switched:
autoloaded options. See #14992
plugins. See #14941
See also
restore_current_blog()
Since
MU
wpdb $wpdb int $blog_id array $_wp_switched_stack bool $switched string $table_prefix WP_Object_Cache $wp_object_cache
Parameters
int $new_blog The id of the blog you want to switch to. Default: current blog
bool $deprecated Deprecated argument
Returns
true Always returns True.
Fires when the blog is switched.
Since
MU
Parameters
int $new_blog New blog ID.
int $new_blog Blog ID.
This filter is documented in wp-includes/ms-blogs.php
Definition at line 610 of file ms-blogs.php.
References $current_user, $GLOBALS, $wpdb, did_action(), do_action(), wp_cache_add_global_groups(), wp_cache_add_non_persistent_groups(), wp_cache_init(), wp_cache_switch_to_blog(), and wp_roles().
Referenced by add_blog_option(), add_user_to_blog(), WP_MS_Sites_List_Table\column_blogname(), create_empty_blog(), current_user_can_for_blog(), delete_blog_option(), WP_Theme\get_allowed_on_site(), get_blog_details(), get_blog_option(), get_blog_permalink(), get_blog_post(), get_home_url(), get_site_icon_url(), get_site_url(), WP_Users_List_Table\get_views(), GV_Unit_Tests_Bootstrap\load_rest_api(), newblog_notify_siteadmin(), remove_user_from_blog(), rest_api_activation(), rest_api_deactivation(), WP_Importer\set_blog(), update_blog_details(), update_blog_option(), upload_space_setting(), wp_admin_bar_my_sites_menu(), wp_xmlrpc_server\wp_getUsersBlogs(), wpmu_create_blog(), wpmu_delete_blog(), and wpmu_delete_user().
update_archived ($id, $archived)
Update the 'archived' status of a particular blog.
Since
MU
Parameters
int $id The blog id
string $archived The new status
Returns
string $archived
Definition at line 784 of file ms-blogs.php.
References $id, and update_blog_status().
update_blog_details ($blog_id, $details = array())
Update the details for a blog.
Updates the blogs table for a given blog id.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
int $blog_id Blog ID
array $details Array of details keyed by blogs table field names.
Returns
bool True if update succeeds, false otherwise.
Fires when the blog status is changed to 'spam'.
Since
MU
Parameters
int $blog_id Blog ID.
Fires when the blog status is changed to 'ham'.
Since
MU
Parameters
int $blog_id Blog ID.
Fires when the blog status is changed to 'mature'.
Since
3.1.0
Parameters
int $blog_id Blog ID.
Fires when the blog status is changed to 'unmature'.
Since
3.1.0
Parameters
int $blog_id Blog ID.
Fires when the blog status is changed to 'archived'.
Since
MU
Parameters
int $blog_id Blog ID.
Fires when the blog status is changed to 'unarchived'.
Since
MU
Parameters
int $blog_id Blog ID.
Fires when the blog status is changed to 'deleted'.
Since
3.5.0
Parameters
int $blog_id Blog ID.
Fires when the blog status is changed to 'undeleted'.
Since
3.5.0
Parameters
int $blog_id Blog ID.
Definition at line 298 of file ms-blogs.php.
References $blog_id, $details, $field, $wpdb, current_time(), do_action(), get_blog_details(), refresh_blog_details(), restore_current_blog(), switch_to_blog(), trailingslashit(), and update_option().
Referenced by wpmu_update_blogs_date().
update_blog_option ($id, $option, $value, $deprecated = null)
Update an option for a particular blog.
Since
MU
Parameters
int $id The blog id.
string $option The option key.
mixed $value The option value.
mixed $deprecated Not used.
Returns
bool True on success, false on failure.
Definition at line 568 of file ms-blogs.php.
References $deprecated, $id, $option, $value, _deprecated_argument(), get_current_blog_id(), null, refresh_blog_details(), restore_current_blog(), switch_to_blog(), and update_option().
update_blog_status ($blog_id, $pref, $value, $deprecated = null)
Update a blog details field.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
int $blog_id BLog ID
string $pref A field name
string $value Value for $pref
null $deprecated
Returns
string|false $value
This filter is documented in wp-includes/ms-blogs.php
This filter is documented in wp-includes/ms-blogs.php
This filter is documented in wp-includes/ms-blogs.php
This filter is documented in wp-includes/ms-blogs.php
This filter is documented in wp-includes/ms-blogs.php
This filter is documented in wp-includes/ms-blogs.php
This filter is documented in wp-includes/ms-blogs.php
This filter is documented in wp-includes/ms-blogs.php
Fires after the current blog's 'public' setting is updated.
Since
MU
Parameters
int $blog_id Blog ID.
string $value The value of blog status.
Definition at line 802 of file ms-blogs.php.
References $blog_id, $deprecated, $value, $wpdb, _deprecated_argument(), current_time(), do_action(), elseif, null, and refresh_blog_details().
Referenced by update_archived(), update_blog_public(), wpmu_create_blog(), and wpmu_delete_blog().
wpmu_update_blogs_date ()
Update the last_updated field for the current blog.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Fires after the blog details are updated.
Since
MU
Parameters
int $blog_id Blog ID.
Definition at line 18 of file ms-blogs.php.
References $wpdb, current_time(), do_action(), and update_blog_details().
Referenced by _update_blog_date_on_post_delete(), and _update_blog_date_on_post_publish().