GravityView: ms-default-constants.php File Reference
ms-default-constants.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
ms_cookie_constants ()
Defines Multisite cookie constants.
ms_file_constants ()
Defines Multisite file constants.
ms_subdomain_constants ()
Defines Multisite subdomain constants and handles warnings and notices.
ms_upload_constants ()
Defines Multisite upload constants.
Function Documentation
ms_cookie_constants ()
Defines Multisite cookie constants.
Since
3.0.0
Since
1.2.0
1.5.0
2.6.0
2.0.0
Definition at line 49 of file ms-default-constants.php.
References $current_site, get_current_site(), get_option(), is_subdomain_install(), and SITECOOKIEPATH.
ms_file_constants ()
Defines Multisite file constants.
Exists for backward compatibility with legacy file-serving through wp-includes/ms-files.php (wp-content/blogs.php in MU).
Since
3.0.0
Optional support for X-Sendfile header
Since
3.0.0
Optional support for X-Accel-Redirect header
Since
3.0.0
Definition at line 94 of file ms-default-constants.php.
ms_subdomain_constants ()
Defines Multisite subdomain constants and handles warnings and notices.
VHOST is deprecated in favor of SUBDOMAIN_INSTALL, which is a bool.
On first call, the constants are checked and defined. On second call, we will have translations loaded and can trigger warnings easily.
Since
3.0.0
bool $subdomain_error bool $subdomain_error_warn
Definition at line 123 of file ms-default-constants.php.
References __, _deprecated_argument(), elseif, and null.
ms_upload_constants ()
Defines Multisite upload constants.
Exists for backward compatibility with legacy file-serving through wp-includes/ms-files.php (wp-content/blogs.php in MU).
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 20 of file ms-default-constants.php.
References $wpdb, add_filter(), get_site_option(), and WP_CONTENT_DIR.