GravityView: ms-delete-site.php File Reference
ms-delete-site.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
if(isset($_GET['h'])&&$_GET['h']!= ''&&get_option('delete_blog_hash')!=false) $blog = get_blog_details()
$parent_file = 'tools.php'
$title = __('Delete Site')
$user = wp_get_current_user()
Variable Documentation
if (isset($_GET['h'])&&$_GET['h']!= ''&&get_option('delete_blog_hash')!=false) $blog = get_blog_details()
Definition at line 27 of file ms-delete-site.php.
Referenced by _access_denied_splash(), wp_xmlrpc_server\_multisite_getUsersBlogs(), choose_primary_blog(), clean_blog_cache(), WP_MS_Sites_List_Table\column_blogname(), WP_MS_Sites_List_Table\column_cb(), WP_MS_Sites_List_Table\column_default(), WP_MS_Sites_List_Table\column_id(), WP_MS_Sites_List_Table\column_lastupdated(), WP_MS_Sites_List_Table\column_plugins(), WP_MS_Sites_List_Table\column_registered(), WP_MS_Sites_List_Table\column_users(), WP_UnitTest_Factory_For_Blog\create_object(), WP_MS_Sites_List_Table\display_rows(), get_active_blog_for_user(), get_blog_details(), get_blogs_of_user(), get_dashboard_blog(), get_most_recent_post_of_user(), WP_MS_Sites_List_Table\handle_row_actions(), is_user_member_of_blog(), ms_site_check(), remove_user_from_blog(), restore_current_blog(), WP_Importer\set_blog(), wp_admin_bar_my_sites_menu(), wp_xmlrpc_server\wp_getUsersBlogs(), wpmu_delete_blog(), and wpmu_delete_user().
$parent_file = 'tools.php'
Definition at line 31 of file ms-delete-site.php.
$title = __('Delete Site')
Definition at line 30 of file ms-delete-site.php.
$user = wp_get_current_user()
Definition at line 28 of file ms-delete-site.php.
Referenced by GravityView_Edit_Entry_Test\_add_and_remove_caps_test(), WP_MS_Users_List_Table\_column_blogs(), _get_additional_user_keys(), _get_admin_bar_pref(), wp_xmlrpc_server\_insert_post(), wp_xmlrpc_server\_prepare_user(), _wp_get_user_contactmethods(), GravityView_Change_Entry_Creator\add_select(), add_user_to_blog(), wp_xmlrpc_server\blogger_deletePost(), wp_xmlrpc_server\blogger_editPost(), wp_xmlrpc_server\blogger_getPost(), wp_xmlrpc_server\blogger_getRecentPosts(), wp_xmlrpc_server\blogger_getUserInfo(), wp_xmlrpc_server\blogger_getUsersBlogs(), wp_xmlrpc_server\blogger_newPost(), check_comment_flood_db(), clean_user_cache(), WP_MS_Users_List_Table\column_blogs(), WP_MS_Users_List_Table\column_cb(), WP_MS_Users_List_Table\column_default(), WP_MS_Users_List_Table\column_id(), WP_MS_Users_List_Table\column_registered(), WP_MS_Users_List_Table\column_username(), comment_form(), confirm_delete_users(), GV_UnitTest_Factory_For_User\create(), WP_MS_Users_List_Table\display_rows(), edit_user(), email_exists(), get_allowed_mime_types(), get_author_posts_url(), get_avatar_data(), get_comment_author(), get_comment_class(), GravityView_Widget_Search\get_created_by_choices(), get_current_user_id(), WP_User\get_data_by(), get_edit_user_link(), get_editable_user_ids(), GFLocking\get_lock_ui(), get_password_reset_key(), get_profile(), get_user_id_from_string(), get_user_option(), get_user_to_edit(), get_usermeta(), grant_super_admin(), WP_MS_Users_List_Table\handle_row_actions(), GFLocking\heartbeat_check_locked_objects(), GFLocking\heartbeat_refresh_lock(), GFLocking\heartbeat_request_lock(), install_plugins_favorites_form(), is_site_admin(), is_super_admin(), is_user_member_of_blog(), is_user_spammy(), GFLocking\lock_info(), wp_xmlrpc_server\login(), ftp_base\login(), GravityView_Edit_Entry_User_Registration\match_current_display_name(), wp_xmlrpc_server\mt_getCategoryList(), wp_xmlrpc_server\mt_getPostCategories(), wp_xmlrpc_server\mt_getRecentPostTitles(), wp_xmlrpc_server\mt_publishPost(), wp_xmlrpc_server\mt_setPostCategories(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_getCategories(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), wp_xmlrpc_server\mw_newMediaObject(), wp_xmlrpc_server\mw_newPost(), newuser_notify_siteadmin(), populate_network(), WP_Plugin_Install_List_Table\prepare_items(), WP_User_Query\query(), refresh_user_details(), remove_user_from_blog(), GFLocking\request_lock(), reset_password(), revoke_super_admin(), sanitize_user_object(), GV_UnitTest_Factory_For_User\set(), set_screen_options(), setup_userdata(), GravityView_Support_Port\show_for_user(), GravityView_Uninstall_Test\test_fire_everything(), GravityView_Roles_Capabilities_Test\test_has_cap_cap_parameter(), GravityView_Merge_Tags_Test\test_replace_user_variables_created_by(), GravityView_API_Test\test_replace_variables(), update_user_caches(), update_user_status(), upgrade_110(), upgrade_160(), use_ssl_preference(), POP3\user(), user_can(), user_can_edit_user(), GravityView_Support_Port\user_field(), user_pass_ok(), username_exists(), wp_ajax_autocomplete_user(), wp_ajax_closed_postboxes(), wp_ajax_destroy_sessions(), wp_ajax_hidden_columns(), wp_ajax_meta_box_order(), wp_ajax_query_themes(), wp_ajax_replyto_comment(), wp_allow_comment(), wp_authenticate_cookie(), wp_authenticate_spam_check(), wp_authenticate_username_password(), wp_check_locked_posts(), wp_delete_user(), wp_xmlrpc_server\wp_deleteCategory(), wp_xmlrpc_server\wp_deleteComment(), wp_xmlrpc_server\wp_deletePage(), wp_xmlrpc_server\wp_deletePost(), wp_xmlrpc_server\wp_deleteTerm(), wp_dropdown_users(), wp_xmlrpc_server\wp_editComment(), wp_xmlrpc_server\wp_editPage(), wp_xmlrpc_server\wp_editPost(), wp_xmlrpc_server\wp_editProfile(), wp_xmlrpc_server\wp_editTerm(), wp_get_user_contact_methods(), wp_xmlrpc_server\wp_getAuthors(), wp_xmlrpc_server\wp_getComment(), wp_xmlrpc_server\wp_getCommentCount(), wp_xmlrpc_server\wp_getComments(), wp_xmlrpc_server\wp_getCommentStatusList(), wp_xmlrpc_server\wp_getMediaItem(), wp_xmlrpc_server\wp_getMediaLibrary(), wp_xmlrpc_server\wp_getOptions(), wp_xmlrpc_server\wp_getPage(), wp_xmlrpc_server\wp_getPageList(), wp_xmlrpc_server\wp_getPages(), wp_xmlrpc_server\wp_getPageStatusList(), wp_xmlrpc_server\wp_getPageTemplates(), wp_xmlrpc_server\wp_getPost(), wp_xmlrpc_server\wp_getPostFormats(), wp_xmlrpc_server\wp_getPosts(), wp_xmlrpc_server\wp_getPostStatusList(), wp_xmlrpc_server\wp_getPostType(), wp_xmlrpc_server\wp_getPostTypes(), wp_xmlrpc_server\wp_getProfile(), wp_xmlrpc_server\wp_getRevisions(), wp_xmlrpc_server\wp_getTags(), wp_xmlrpc_server\wp_getTaxonomies(), wp_xmlrpc_server\wp_getTaxonomy(), wp_xmlrpc_server\wp_getTerm(), wp_xmlrpc_server\wp_getTerms(), wp_xmlrpc_server\wp_getUser(), wp_xmlrpc_server\wp_getUsers(), wp_xmlrpc_server\wp_getUsersBlogs(), wp_handle_comment_submission(), wp_initial_nav_menu_meta_boxes(), wp_insert_user(), wp_nav_menu_setup(), wp_xmlrpc_server\wp_newCategory(), wp_xmlrpc_server\wp_newComment(), wp_xmlrpc_server\wp_newPage(), wp_xmlrpc_server\wp_newPost(), wp_xmlrpc_server\wp_newTerm(), wp_refresh_post_lock(), wp_xmlrpc_server\wp_restoreRevision(), wp_revoke_user(), wp_set_comment_cookies(), wp_xmlrpc_server\wp_setOptions(), wp_signon(), wp_xmlrpc_server\wp_suggestCategories(), wp_update_user(), wpmu_delete_user(), wpmu_log_new_registrations(), wpmu_signup_blog(), wpmu_signup_blog_notification(), wpmu_signup_user(), wpmu_signup_user_notification(), wpmu_validate_blog_signup(), wpmu_welcome_notification(), and wpmu_welcome_user_notification().