GravityView: ms-files.php File Reference
ms-files.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$client_etag = isset($_SERVER['HTTP_IF_NONE_MATCH']) ? stripslashes($_SERVER['HTTP_IF_NONE_MATCH']) : false
$client_last_modified = trim($_SERVER['HTTP_IF_MODIFIED_SINCE'])
$client_modified_timestamp = $client_last_modified ? strtotime($client_last_modified) : 0
$etag = '"' . md5($last_modified) . '"'
if($current_blog->archived== '1'||$current_blog->spam== '1'||$current_blog->deleted== '1') $file = rtrim(BLOGUPLOADDIR, '/') . '/' . str_replace('..', '', $_GET[ 'file' ])
if(!is_file($file)) $mime = wp_check_filetype($file)
else $mimetype = 'image/' . substr($file, strrpos($file, '.') + 1)
$modified_timestamp = strtotime($last_modified)
if(false===strpos($_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS')) header('Content-Length d M Y H
const SHORTINIT true
Variable Documentation
$client_etag = isset($_SERVER['HTTP_IF_NONE_MATCH']) ? stripslashes($_SERVER['HTTP_IF_NONE_MATCH']) : false
Definition at line 61 of file ms-files.php.
Referenced by WP\send_headers().
$client_last_modified = trim($_SERVER['HTTP_IF_MODIFIED_SINCE'])
Definition at line 66 of file ms-files.php.
Referenced by WP\send_headers().
$client_modified_timestamp = $client_last_modified ? strtotime($client_last_modified) : 0
Definition at line 68 of file ms-files.php.
Referenced by WP\send_headers().
$etag = '"' . md5($last_modified) . '"'
Definition at line 55 of file ms-files.php.
if ($current_blog->archived== '1'||$current_blog->spam== '1'||$current_blog->deleted== '1') $file = rtrim(BLOGUPLOADDIR, '/') . '/' . str_replace('..', '', $_GET[ 'file' ])
Definition at line 26 of file ms-files.php.
if (!is_file($file)) $mime = wp_check_filetype($file)
Definition at line 32 of file ms-files.php.
Referenced by WP_UnitTestCase\_make_attachment(), PHPMailer\attachAll(), check_upload_mimes(), WP_Media_List_Table\column_title(), WP_UnitTest_Factory_For_Attachment\create_upload_object(), do_enclose(), SimplePie_Enclosure\embed(), SimplePie_Misc\parse_mime(), wp_match_mime_types(), and wp_mime_type_icon().
else $mimetype = 'image/' . substr($file, strrpos($file, '.') + 1)
Definition at line 39 of file ms-files.php.
$modified_timestamp = strtotime($last_modified)
Definition at line 71 of file ms-files.php.
if (false===strpos($_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS')) header('Content-Length d M Y H
Definition at line 42 of file ms-files.php.
const SHORTINIT true
Definition at line 11 of file ms-files.php.