GravityView: ms-functions.php File Reference
ms-functions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
add_existing_user_to_blog ($details=false)
Add a user to a blog based on details from maybe_add_existing_user_to_blog().
add_new_user_to_blog ($user_id, $password, $meta)
Add a newly created user to the appropriate blog.
add_user_to_blog ($blog_id, $user_id, $role)
Add a user to a blog.
check_upload_mimes ($mimes)
Check an array of MIME types against a whitelist.
domain_exists ($domain, $path, $site_id=1)
Check whether a blogname is already taken.
filter_SSL ($url)
Formats a URL to use https.
fix_phpmailer_messageid ($phpmailer)
Correct From host on outgoing mail to match the site domain.
force_ssl_content ($force= '')
Whether to force SSL on content.
get_active_blog_for_user ($user_id)
Get one of a user's active blogs.
get_blog_count ($network_id=0)
The number of active sites on your installation.
get_blog_id_from_url ($domain, $path= '/')
Get a blog's numeric ID from its URL.
get_blog_permalink ($blog_id, $post_id)
Get the permalink for a post on another blog.
get_blog_post ($blog_id, $post_id)
Get a blog post from any site on the network.
get_current_site ()
Get the current network.
get_dirsize ($directory)
Get the size of a directory.
get_most_recent_post_of_user ($user_id)
Get a user's most recent post.
get_sitestats ()
Gets the network's site and user counts.
get_space_allowed ()
Returns the upload quota for the current blog.
get_space_used ()
Returns the space used by the current blog.
get_subdirectory_reserved_names ()
Retrieves a list of reserved site on a sub-directory Multisite install.
get_upload_space_available ()
Determines if there is any upload space left in the current blog's quota.
get_user_count ()
The number of active users in your installation.
global_terms ($term_id, $deprecated= '')
Maintains a canonical list of terms by syncing terms created for each blog with the global terms table.
insert_blog ($domain, $path, $site_id)
Store basic site info in the blogs table.
install_blog ($blog_id, $blog_title= '')
Install an empty blog.
install_blog_defaults ($blog_id, $user_id)
Set blog defaults.
is_email_address_unsafe ($user_email)
Checks an email address against a list of banned domains.
is_upload_space_available ()
Determines if there is any upload space left in the current blog's quota.
is_user_option_local ($key, $user_id=0, $blog_id=0)
Check whether a usermeta key has to do with the current blog.
is_user_spammy ($user=null)
Check to see whether a user is marked as a spammer, based on user login.
maybe_add_existing_user_to_blog ()
Add a new user to a blog by visiting /newbloguser/username/.
maybe_redirect_404 ()
Correct 404 redirects when NOBLOGREDIRECT is defined.
newblog_notify_siteadmin ($blog_id, $deprecated= '')
Notifies the network admin that a new site has been activated.
newuser_notify_siteadmin ($user_id)
Notifies the network admin that a new user has been activated.
recurse_dirsize ($directory, $exclude=null)
Get the size of a directory recursively.
redirect_this_site ($deprecated= '')
Ensure that the current site's domain is listed in the allowed redirect host list.
remove_user_from_blog ($user_id, $blog_id= '', $reassign= '')
Remove a user from a blog.
signup_nonce_check ($result)
Process the signup nonce created in signup_nonce_fields().
signup_nonce_fields ()
Add a nonce field to the signup page.
update_blog_public ($old_value, $value)
Update this blog's 'public' setting in the global blogs table.
update_posts_count ($deprecated= '')
Update a blog's post count.
upload_is_file_too_big ($upload)
Check whether an upload is too big.
upload_size_limit_filter ($size)
Filters the maximum upload file size allowed, in bytes.
users_can_register_signup_filter ()
Check whether users can self-register, based on Network settings.
welcome_user_msg_filter ($text)
Ensure that the welcome message is not empty.
wp_get_sites ($args=array())
Return an array of sites for a network or networks.
wp_is_large_network ($using= 'sites')
Whether or not we have a large network.
wp_maybe_update_network_site_counts ()
Update the count of sites for the current network.
wp_maybe_update_network_user_counts ()
Update the network-wide users count.
wp_schedule_update_network_counts ()
Schedule update of the network-wide counts for the current network.
wp_update_network_counts ()
Update the network-wide counts for the current network.
wp_update_network_site_counts ()
Update the network-wide site count.
wp_update_network_user_counts ()
Update the network-wide user count.
wpmu_activate_signup ($key)
Activate a signup.
wpmu_create_blog ($domain, $path, $title, $user_id, $meta=array(), $site_id=1)
Create a site.
wpmu_create_user ($user_name, $password, $email)
Create a user.
wpmu_log_new_registrations ($blog_id, $user_id)
Logs user registrations.
wpmu_signup_blog ($domain, $path, $title, $user, $user_email, $meta=array())
Record site signup information for future activation.
wpmu_signup_blog_notification ($domain, $path, $title, $user, $user_email, $key, $meta=array())
Notify user of signup success.
wpmu_signup_user ($user, $user_email, $meta=array())
Record user signup information for future activation.
wpmu_signup_user_notification ($user, $user_email, $key, $meta=array())
Notify user of signup success.
wpmu_validate_blog_signup ($blogname, $blog_title, $user= '')
Processes new site registrations.
wpmu_validate_user_signup ($user_name, $user_email)
Sanitize and validate data required for a user sign-up.
wpmu_welcome_notification ($blog_id, $user_id, $password, $title, $meta=array())
Notify a user that their blog activation has been successful.
wpmu_welcome_user_notification ($user_id, $password, $meta=array())
Notify a user that their account activation has been successful.
Function Documentation
add_existing_user_to_blog ($details = false)
Add a user to a blog based on details from maybe_add_existing_user_to_blog().
Since
MU
int $blog_id
Parameters
array $details
Returns
true|WP_Error|void
Fires immediately after an existing user is added to a site.
Since
MU
Parameters
int $user_id User ID.
mixed $result True on success or a WP_Error object if the user doesn't exist.
Definition at line 1982 of file ms-functions.php.
References $blog_id, $details, add_user_to_blog(), and do_action().
Referenced by maybe_add_existing_user_to_blog().
add_new_user_to_blog ($user_id, $password, $meta)
Add a newly created user to the appropriate blog.
To add a user in general, use add_user_to_blog(). This function is specifically hooked into the wpmu_activate_user action.
Since
MU
See also
add_user_to_blog()
Parameters
int $user_id
mixed $password Ignored.
array $meta
Definition at line 2013 of file ms-functions.php.
References $blog_id, $user_id, add_user_to_blog(), get_current_site(), remove_user_from_blog(), and update_user_meta().
add_user_to_blog ($blog_id, $user_id, $role)
Add a user to a blog.
Use the 'add_user_to_blog' action to fire an event when users are added to a blog.
Since
MU 1.0
Parameters
int $blog_id ID of the blog you're adding the user to.
int $user_id ID of the user you're adding.
string $role The role you want the user to have
Returns
true|WP_Error
Fires immediately after a user is added to a site.
Since
MU
Parameters
int $user_id User ID.
string $role User role.
int $blog_id Blog ID.
Definition at line 153 of file ms-functions.php.
References $blog_id, $details, $user, $user_id, __, do_action(), get_blog_details(), get_user_meta(), restore_current_blog(), switch_to_blog(), update_user_meta(), and wp_cache_delete().
Referenced by add_existing_user_to_blog(), add_new_user_to_blog(), get_active_blog_for_user(), and wpmu_create_blog().
check_upload_mimes ($mimes)
Check an array of MIME types against a whitelist.
WordPress ships with a set of allowed upload filetypes, which is defined in wp-includes/functions.php in get_allowed_mime_types(). This function is used to filter that list against the filetype whitelist provided by Multisite Super Admins at wp-admin/network/settings.php.
Since
MU
Parameters
array $mimes
Returns
array
Definition at line 1735 of file ms-functions.php.
References $mime, and get_site_option().
domain_exists ($domain, $path, $site_id = 1)
Check whether a blogname is already taken.
Used during the new site registration process to ensure that each blogname is unique.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $domain The domain to be checked.
string $path The path to be checked.
int $site_id Optional. Relevant only on multi-network installs.
Returns
int
Filter whether a blogname is taken.
Since
3.5.0
Parameters
int | null $result The blog_id if the blogname exists, null otherwise.
string $domain Domain to be checked.
string $path Path to be checked.
int $site_id Site ID. Relevant only on multi-network installs.
Definition at line 1257 of file ms-functions.php.
References $path, $wpdb, apply_filters(), and trailingslashit().
Referenced by create_empty_blog(), wpmu_create_blog(), and wpmu_validate_blog_signup().
filter_SSL ($url)
Formats a URL to use https.
Useful as a filter.
Since
2.8.5
Parameters
string $url URL
Returns
string URL with https as the scheme
Definition at line 2167 of file ms-functions.php.
References $url, force_ssl_content(), get_bloginfo(), is_ssl(), and set_url_scheme().
fix_phpmailer_messageid ($phpmailer)
Correct From host on outgoing mail to match the site domain.
Since
MU
Parameters
PHPMailer $phpmailer The PHPMailer instance, passed by reference.
Definition at line 2030 of file ms-functions.php.
References $phpmailer, and get_current_site().
force_ssl_content ($force = '')
Whether to force SSL on content.
Since
2.8.5
bool $forced_content
Parameters
bool $force
Returns
bool True if forced, false if not forced.
Definition at line 2145 of file ms-functions.php.
Referenced by filter_SSL().
get_active_blog_for_user ($user_id)
Get one of a user's active blogs.
Returns the user's primary blog, if they have one and it is active. If it's inactive, function returns another active blog of the user. If none are found, the user is added as a Subscriber to the Dashboard Blog and that blog is returned.
Since
MU 1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $user_id The unique ID of the user
Returns
object|void The blog object
Definition at line 42 of file ms-functions.php.
References $blog, $blog_id, $blogs, $details, $user_id, $wpdb, add_user_to_blog(), get_blog_details(), get_blogs_of_user(), get_user_meta(), is_multisite(), and update_user_meta().
Referenced by get_dashboard_url(), WP_Admin_Bar\initialize(), and wp_xmlrpc_server\wp_getUsersBlogs().
get_blog_count ($network_id = 0)
The number of active sites on your installation.
The count is cached and updated twice daily. This is not a live count.
Since
MU 1.0
Parameters
int $network_id Deprecated, not supported.
Returns
int
Definition at line 116 of file ms-functions.php.
References _deprecated_argument(), and get_site_option().
Referenced by get_sitestats(), wp_is_large_network(), wp_network_dashboard_right_now(), and wp_version_check().
get_blog_id_from_url ($domain, $path = '/')
Get a blog's numeric ID from its URL.
On a subdirectory installation like example.com/blog1/, $domain will be the root 'example.com' and $path the subdirectory '/blog1/'. With subdomains like blog1.example.com, $domain is 'blog1.example.com' and $path is '/'.
Since
MU 2.6.5
wpdb $wpdb WordPress database abstraction object.
Parameters
string $domain
string $path Optional. Not required for subdomain installations.
Returns
int 0 if no blog found, otherwise the ID of the matching blog
Definition at line 307 of file ms-functions.php.
References $id, $path, $wpdb, elseif, wp_cache_get(), and wp_cache_set().
get_blog_permalink ($blog_id, $post_id)
Get the permalink for a post on another blog.
Since
MU 1.0
Parameters
int $blog_id ID of the source blog.
int $post_id ID of the desired post.
Returns
string The post's permalink
Definition at line 283 of file ms-functions.php.
References $blog_id, $link, $post_id, get_permalink(), restore_current_blog(), and switch_to_blog().
get_blog_post ($blog_id, $post_id)
Get a blog post from any site on the network.
Since
MU 1.0
Parameters
int $blog_id ID of the blog.
int $post_id ID of the post you're looking for.
Returns
WP_Post|null WP_Post on success or null on failure
Definition at line 132 of file ms-functions.php.
References $blog_id, $post, $post_id, get_post(), restore_current_blog(), and switch_to_blog().
get_current_site ()
Get the current network.
Returns an object containing the 'id', 'domain', 'path', and 'site_name' properties of the network being viewed.
See also
wpmu_current_site()
Since
MU
object $current_site
Returns
object
Definition at line 1597 of file ms-functions.php.
References $current_site.
Referenced by add_new_user_to_blog(), WP_MS_Users_List_Table\column_blogs(), fix_phpmailer_messageid(), get_id_from_blogname(), get_main_network_id(), WP_MS_Sites_List_Table\handle_row_actions(), install_blog(), is_main_network(), login_header(), ms_allowed_http_request_hosts(), ms_cookie_constants(), ms_site_check(), network_home_url(), network_site_url(), populate_options(), WP_MS_Sites_List_Table\prepare_items(), redirect_this_site(), wp_admin_bar_site_menu(), wp_xmlrpc_server\wp_getUsersBlogs(), wpmu_delete_blog(), wpmu_signup_blog_notification(), wpmu_validate_blog_signup(), wpmu_welcome_notification(), and wpmu_welcome_user_notification().
get_dirsize ($directory)
Get the size of a directory.
A helper function that is used primarily to check whether a blog has exceeded its allowed upload space.
Since
MU
Parameters
string $directory Full path of a directory.
Returns
int Size of the directory in MB.
Definition at line 1661 of file ms-functions.php.
References get_transient(), is_main_site(), recurse_dirsize(), and set_transient().
Referenced by get_space_used().
get_most_recent_post_of_user ($user_id)
Get a user's most recent post.
Walks through each of a user's blogs to find the post with the most recent post_date_gmt.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
int $user_id
Returns
array Contains the blog_id, post_id, post_date_gmt, and post_gmt_ts
Definition at line 1615 of file ms-functions.php.
References $blog, $prefix, $user_id, $wpdb, ARRAY_A, and get_blogs_of_user().
get_sitestats ()
Gets the network's site and user counts.
Since
MU 1.0
Returns
array Site and user count for the network.
Definition at line 17 of file ms-functions.php.
References get_blog_count(), and get_user_count().
get_space_allowed ()
Returns the upload quota for the current blog.
Since
MU
Returns
int Quota in megabytes
Filter the upload quota for the current site.
Since
3.7.0
Parameters
int $space_allowed Upload quota in megabytes for the current blog.
Definition at line 2304 of file ms-functions.php.
References apply_filters(), get_option(), and get_site_option().
Referenced by display_space_usage(), get_upload_space_available(), multisite_over_quota_message(), and upload_is_user_over_quota().
get_space_used ()
Returns the space used by the current blog.
Since
3.5.0
Returns
int Used space in megabytes
Filter the amount of storage space used by the current site.
Since
3.5.0
Parameters
int | bool $space_used The amount of used space, in megabytes. Default false.
Definition at line 2280 of file ms-functions.php.
References apply_filters(), get_dirsize(), and wp_upload_dir().
Referenced by display_space_usage(), get_upload_space_available(), and upload_is_user_over_quota().
get_subdirectory_reserved_names ()
Retrieves a list of reserved site on a sub-directory Multisite install.
Since
4.4.0
Returns
array $names Array of reserved subdirectory names.
Filter reserved site names on a sub-directory Multisite install.
Since
3.0.0
4.4.0 'wp-admin', 'wp-content', 'wp-includes', 'wp-json', and 'embed' were added to the reserved names list.
Parameters
array $subdirectory_reserved_names Array of reserved names.
Definition at line 2492 of file ms-functions.php.
References apply_filters().
Referenced by wpmu_validate_blog_signup().
get_upload_space_available ()
Determines if there is any upload space left in the current blog's quota.
Since
3.0.0
Returns
int of upload space available in bytes
Definition at line 2330 of file ms-functions.php.
References get_site_option(), get_space_allowed(), and get_space_used().
Referenced by check_upload_size(), fix_import_form_size(), is_upload_space_available(), and upload_size_limit_filter().
get_user_count ()
The number of active users in your installation.
The count is cached and updated twice daily. This is not a live count.
Since
MU 2.7
Returns
int
Definition at line 102 of file ms-functions.php.
References get_site_option().
Referenced by get_sitestats(), WP_MS_Users_List_Table\get_views(), wp_is_large_network(), wp_network_dashboard_right_now(), and wp_version_check().
global_terms ($term_id, $deprecated = '')
Maintains a canonical list of terms by syncing terms created for each blog with the global terms table.
Since
3.0.0
See also
term_id_filter
wpdb $wpdb WordPress database abstraction object. int $global_terms_recurse
Parameters
int $term_id An ID for a term on the current blog.
string $deprecated Not used.
Returns
int An ID from the global terms table mapped from $term_id.
Definition at line 1797 of file ms-functions.php.
References $wpdb, clean_term_cache(), elseif, get_option(), global_terms_enabled(), null, and update_option().
insert_blog ($domain, $path, $site_id)
Store basic site info in the blogs table.
This function creates a row in the wp_blogs table and returns the new blog's ID. It is the first step in creating a new blog.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $domain The domain of the new site.
string $path The path of the new site.
int $site_id Unless you're running a multi-network install, be sure to set this value to 1.
Returns
int|false The ID of the new row
Definition at line 1290 of file ms-functions.php.
References $blog_id, $path, $wpdb, current_time(), refresh_blog_details(), trailingslashit(), and wp_maybe_update_network_site_counts().
Referenced by create_empty_blog(), and wpmu_create_blog().
install_blog ($blog_id, $blog_title = '')
Install an empty blog.
Creates the new blog tables and options. If calling this function directly, be sure to use switch_to_blog() first, so that $wpdb points to the new blog.
Since
MU
wpdb $wpdb WP_Roles $wp_roles
Parameters
int $blog_id The value returned by insert_blog().
string $blog_title The title of the new site.
Definition at line 1323 of file ms-functions.php.
References $blog_id, $current_site, $table_prefix, $url, $wpdb, __, ABSPATH, delete_metadata(), get_blog_option(), get_blogaddress_by_id(), get_current_site(), get_home_url(), get_site_option(), is_subdomain_install(), make_db_current_silent(), null, populate_options(), populate_roles(), set_url_scheme(), untrailingslashit(), update_option(), and wp_unslash().
Referenced by create_empty_blog(), and wpmu_create_blog().
install_blog_defaults ($blog_id, $user_id)
Set blog defaults.
This function creates a row in the wp_blogs table.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
int $blog_id Ignored in this function.
int $user_id
Definition at line 1390 of file ms-functions.php.
References $user_id, $wpdb, and ABSPATH.
is_email_address_unsafe ($user_email)
Checks an email address against a list of banned domains.
This function checks against the Banned Email Domains list at wp-admin/network/settings.php. The check is only run on self-registrations; user creation at wp-admin/network/users.php bypasses this check.
Since
MU
Parameters
string $user_email The email provided by the user at registration.
Returns
bool Returns true when the email address is banned.
Filter whether an email address is unsafe.
Since
3.5.0
Parameters
bool $is_email_address_unsafe Whether the email address is "unsafe". Default false.
string $user_email User email address.
Definition at line 346 of file ms-functions.php.
References apply_filters(), and get_site_option().
Referenced by wpmu_validate_user_signup().
is_upload_space_available ()
Determines if there is any upload space left in the current blog's quota.
Since
3.0.0
Returns
bool True if space is available, false otherwise.
Definition at line 2353 of file ms-functions.php.
References get_site_option(), and get_upload_space_available().
Referenced by media_upload_form(), wp_plupload_default_settings(), wp_print_media_templates(), and wpmu_checkAvailableSpace().
is_user_option_local ($key, $user_id = 0, $blog_id = 0)
Check whether a usermeta key has to do with the current blog.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $key
int $user_id Optional. Defaults to current user.
int $blog_id Optional. Defaults to current blog.
Returns
bool
Definition at line 2081 of file ms-functions.php.
References $blog_id, $current_user, and $wpdb.
is_user_spammy ($user = null)
Check to see whether a user is marked as a spammer, based on user login.
Since
MU
Parameters
string | WP_User $user Optional. Defaults to current user. WP_User object, or user login name as a string.
Returns
bool
Definition at line 2043 of file ms-functions.php.
References $user.
Referenced by wp_authenticate_spam_check().
maybe_add_existing_user_to_blog ()
Add a new user to a blog by visiting /newbloguser/username/.
This will only work when the user's details are saved as an option keyed as 'new_user_x', where 'x' is the username of the user to be added, as when a user is invited through the regular WP Add User interface.
Since
MU
Definition at line 1952 of file ms-functions.php.
References $_SERVER, $details, __, add_existing_user_to_blog(), admin_url(), delete_option(), get_option(), home_url(), is_wp_error(), and wp_die().
maybe_redirect_404 ()
Correct 404 redirects when NOBLOGREDIRECT is defined.
Since
MU
Filter the redirect URL for 404s on the main site.
The filter is only evaluated if the NOBLOGREDIRECT constant is defined.
Since
3.0.0
Parameters
string $no_blog_redirect The redirect URL defined in NOBLOGREDIRECT.
Definition at line 1925 of file ms-functions.php.
References apply_filters(), exit, is_404, is_main_site(), and network_home_url().
newblog_notify_siteadmin ($blog_id, $deprecated = '')
Notifies the network admin that a new site has been activated.
Filter 'newblog_notify_siteadmin' to change the content of the notification email.
Since
MU
Parameters
int $blog_id The new site's ID.
string $deprecated Not used.
Returns
bool
Filter the message body of the new site activation email sent to the network administrator.
Since
MU
Parameters
string $msg Email body.
Definition at line 1166 of file ms-functions.php.
References $_SERVER, $blog_id, $msg, __, apply_filters(), esc_url, get_option(), get_site_option(), is_email(), network_admin_url(), restore_current_blog(), site_url(), switch_to_blog(), and wp_unslash().
newuser_notify_siteadmin ($user_id)
Notifies the network admin that a new user has been activated.
Filter 'newuser_notify_siteadmin' to change the content of the notification email.
Since
MU
Parameters
int $user_id The new user's ID.
Returns
bool
Filter the message body of the new user activation email sent to the network administrator.
Since
MU
Parameters
string $msg Email body.
WP_User $user WP_User instance of the new user.
Definition at line 1211 of file ms-functions.php.
References $_SERVER, $msg, $user, $user_id, __, apply_filters(), esc_url, get_site_option(), is_email(), network_admin_url(), and wp_unslash().
recurse_dirsize ($directory, $exclude = null)
Get the size of a directory recursively.
Used by get_dirsize() to get a directory's size when it contains other directories.
Since
MU
4.3.0 $exclude parameter added.
Parameters
string $directory Full path of a directory.
string $exclude Optional. Full path of a subdirectory to exclude from the total.
Returns
int|false Size in MB if a valid directory. False if not.
Definition at line 1694 of file ms-functions.php.
References $file, $path, $size, elseif, and untrailingslashit().
Referenced by get_dirsize().
redirect_this_site ($deprecated = '')
Ensure that the current site's domain is listed in the allowed redirect host list.
See also
wp_validate_redirect()
Since
MU
Parameters
array | string $deprecated Not used.
Returns
array The current site's domain
Definition at line 1866 of file ms-functions.php.
References get_current_site().
remove_user_from_blog ($user_id, $blog_id = '', $reassign = '')
Remove a user from a blog.
Use the 'remove_user_from_blog' action to fire an event when users are removed from a blog.
Accepts an optional $reassign parameter, if you want to reassign the user's blog posts to another user upon removal.
Since
MU 1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $user_id ID of the user you're removing.
int $blog_id ID of the blog you're removing the user from.
string $reassign Optional. A user to whom to reassign posts.
Returns
true|WP_Error
Fires before a user is removed from a site.
Since
MU
Parameters
int $user_id User ID.
int $blog_id Blog ID.
Definition at line 205 of file ms-functions.php.
References $blog, $blog_id, $blogs, $user, $user_id, $wpdb, __, do_action(), get_blogs_of_user(), get_user_meta(), restore_current_blog(), switch_to_blog(), and update_user_meta().
Referenced by add_new_user_to_blog(), wp_delete_user(), wpmu_delete_blog(), and wpmu_delete_user().
signup_nonce_check ($result)
Process the signup nonce created in signup_nonce_fields().
Since
MU
Parameters
array $result
Returns
array
Definition at line 1910 of file ms-functions.php.
References $_SERVER, __, and wp_die().
signup_nonce_fields ()
Add a nonce field to the signup page.
Since
MU
Definition at line 1896 of file ms-functions.php.
References $id, and wp_nonce_field().
update_blog_public ($old_value, $value)
Update this blog's 'public' setting in the global blogs table.
Public blogs have a setting of 1, private blogs are 0.
Since
MU
Parameters
int $old_value
int $value The new public value
Definition at line 2065 of file ms-functions.php.
References $value, get_current_blog_id(), and update_blog_status().
update_posts_count ($deprecated = '')
Update a blog's post count.
WordPress MS stores a blog's post count as an option so as to avoid extraneous COUNTs when a blog's details are fetched with get_blog_details(). This function is called when posts are published or unpublished to make sure the count stays current.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $deprecated Not used.
Definition at line 1761 of file ms-functions.php.
References $wpdb, and update_option().
Referenced by _update_posts_count_on_delete(), and _update_posts_count_on_transition_post_status().
upload_is_file_too_big ($upload)
Check whether an upload is too big.
Since
MU
Parameters
array $upload
Returns
string|array If the upload is under the size limit, $upload is returned. Otherwise returns an error message.
Definition at line 1880 of file ms-functions.php.
References __, and get_site_option().
upload_size_limit_filter ($size)
Filters the maximum upload file size allowed, in bytes.
Since
3.0.0
Parameters
int $size Upload size limit in bytes.
Returns
int Upload size limit in bytes.
Definition at line 2368 of file ms-functions.php.
References $size, get_site_option(), and get_upload_space_available().
users_can_register_signup_filter ()
Check whether users can self-register, based on Network settings.
Since
MU
Returns
bool
Definition at line 2100 of file ms-functions.php.
References get_site_option().
welcome_user_msg_filter ($text)
Ensure that the welcome message is not empty.
Currently unused.
Since
MU
Parameters
string $text
Returns
string
Definition at line 2113 of file ms-functions.php.
References $text, __, remove_filter(), and update_site_option().
wp_get_sites ($args = array())
Return an array of sites for a network or networks.
Since
3.7.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $args { Array of default arguments. Optional.
int|array $network_id A network ID or array of network IDs. Set to null to retrieve sites from all networks. Defaults to current network ID. int $public Retrieve public or non-public sites. Default null, for any. int $archived Retrieve archived or non-archived sites. Default null, for any. int $mature Retrieve mature or non-mature sites. Default null, for any. int $spam Retrieve spam or non-spam sites. Default null, for any. int $deleted Retrieve deleted or non-deleted sites. Default null, for any. int $limit Number of sites to limit the query to. Default 100. int $offset Exclude the first x sites. Used in combination with the $limit parameter. Default 0. }
Returns
array An empty array if the install is considered "large" via wp_is_large_network(). Otherwise, an associative array of site data arrays, each containing the site (network) ID, blog ID, site domain and path, dates registered and modified, and the language ID. Also, boolean values for whether the site is public, archived, mature, spam, and/or deleted.
Definition at line 2432 of file ms-functions.php.
References $wpdb, ARRAY_A, null, wp_is_large_network(), wp_parse_args(), and wp_parse_id_list().
Referenced by GV_Unit_Tests_Bootstrap\load_rest_api(), rest_api_activation(), and rest_api_deactivation().
wp_is_large_network ($using = 'sites')
Whether or not we have a large network.
The default criteria for a large network is either more than 10,000 users or more than 10,000 sites. Plugins can alter this criteria using the 'wp_is_large_network' filter.
Since
3.3.0
Parameters
string $using 'sites or 'users'. Default is 'sites'.
Returns
bool True if the network meets the criteria for large. False otherwise.
Filter whether the network is considered large.
Since
3.3.0
Parameters
bool $is_large_network Whether the network has more than 10000 users or sites.
string $component The component to count. Accepts 'users', or 'sites'.
int $count The count of items for the component.
This filter is documented in wp-includes/ms-functions.php
Definition at line 2386 of file ms-functions.php.
References $count, apply_filters(), get_blog_count(), and get_user_count().
Referenced by WP_MS_Users_List_Table\prepare_items(), WP_MS_Sites_List_Table\prepare_items(), WP_User_Query\prepare_query(), wp_ajax_autocomplete_user(), wp_get_sites(), wp_maybe_update_network_site_counts(), and wp_maybe_update_network_user_counts().
wp_maybe_update_network_site_counts ()
Update the count of sites for the current network.
If enabled through the 'enable_live_network_counts' filter, update the sites count on a network when a site is created or its status is updated.
Since
3.7.0
Filter whether to update network site or user counts when a new site is created.
Since
3.7.0
See also
wp_is_large_network()
Parameters
bool $small_network Whether the network is considered small.
string $context Context. Either 'users' or 'sites'.
Definition at line 2208 of file ms-functions.php.
References apply_filters(), wp_is_large_network(), and wp_update_network_site_counts().
Referenced by insert_blog().
wp_maybe_update_network_user_counts ()
Update the network-wide users count.
If enabled through the 'enable_live_network_counts' filter, update the users count on a network when a user is created or its status is updated.
Since
3.7.0
This filter is documented in wp-includes/ms-functions.php
Definition at line 2235 of file ms-functions.php.
References apply_filters(), wp_is_large_network(), and wp_update_network_user_counts().
wp_schedule_update_network_counts ()
Schedule update of the network-wide counts for the current network.
Since
3.1.0
Definition at line 2182 of file ms-functions.php.
References is_main_site(), wp_installing(), wp_next_scheduled(), and wp_schedule_event().
wp_update_network_counts ()
Update the network-wide counts for the current network.
Since
3.1.0
Definition at line 2195 of file ms-functions.php.
References wp_update_network_site_counts(), and wp_update_network_user_counts().
wp_update_network_site_counts ()
Update the network-wide site count.
Since
3.7.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 2252 of file ms-functions.php.
References $count, $wpdb, and update_site_option().
Referenced by wp_maybe_update_network_site_counts(), and wp_update_network_counts().
wp_update_network_user_counts ()
Update the network-wide user count.
Since
3.7.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 2266 of file ms-functions.php.
References $count, $wpdb, and update_site_option().
Referenced by wp_maybe_update_network_user_counts(), and wp_update_network_counts().
wpmu_activate_signup ($key)
Activate a signup.
Hook to 'wpmu_activate_user' or 'wpmu_activate_blog' for events that should happen only when users or sites are self-created (since those actions are not called when users and sites are created by a Super Admin).
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $key The activation key provided to the user.
Returns
array|WP_Error An array containing information about the activated user and/or blog
Fires immediately after a new user is activated.
Since
MU
Parameters
int $user_id User ID.
int $password User password.
array $meta Signup meta data.
Fires immediately after a site is activated.
Since
MU
Parameters
int $blog_id Blog ID.
int $user_id User ID.
int $password User password.
string $signup_title Site title.
array $meta Signup meta data.
Definition at line 952 of file ms-functions.php.
References $blog_id, $now, $user_id, $wpdb, __, current_time(), do_action(), is_wp_error(), maybe_unserialize(), username_exists(), wpmu_create_blog(), and wpmu_create_user().
wpmu_create_blog ($domain, $path, $title, $user_id, $meta = array(), $site_id = 1)
Create a site.
This function runs when a user self-registers a new site as well as when a Super Admin creates a new site. Hook to 'wpmu_new_blog' for events that should affect all new sites.
On subdirectory installs, $domain is the same as the main site's domain, and the path is the subdirectory name (eg 'example.com' and '/blog1/'). On subdomain installs, $domain is the new subdomain + root domain (eg 'blog1.example.com'), and $path is '/'.
Since
MU
Parameters
string $domain The new site's domain.
string $path The new site's path.
string $title The new site's title.
int $user_id The user ID of the new site's admin.
array $meta Optional. Used to set initial site options.
int $site_id Optional. Only relevant on multi-network installs.
Returns
int|WP_Error Returns WP_Error object on failure, int $blog_id on success
Fires immediately after a new site is created.
Since
MU
Parameters
int $blog_id Blog ID.
int $user_id User ID.
string $domain Site domain.
string $path Site path.
int $site_id Site ID. Only relevant on multi-network installs.
array $meta Meta data. Used to set initial site options.
Definition at line 1091 of file ms-functions.php.
References $blog_id, $path, $title, $user_id, $value, __, add_option(), add_user_to_blog(), do_action(), domain_exists(), get_site_option(), get_user_meta(), insert_blog(), install_blog(), is_subdomain_install(), is_super_admin(), restore_current_blog(), sanitize_user(), str_replace, switch_to_blog(), update_blog_status(), update_option(), update_user_meta(), wp_installing(), and wp_parse_args().
Referenced by WP_UnitTest_Factory_For_Blog\create_object(), and wpmu_activate_signup().
wpmu_create_user ($user_name, $password, $email)
Create a user.
This function runs when a user self-registers as well as when a Super Admin creates a new user. Hook to 'wpmu_new_user' for events that should affect all new users, but only on Multisite (otherwise use 'user_register').
Since
MU
Parameters
string $user_name The new user's login name.
string $password The new user's password.
string $email The new user's email address.
Returns
int|false Returns false on failure, or int $user_id on success
Fires immediately after a new user is created.
Since
MU
Parameters
int $user_id User ID.
Definition at line 1046 of file ms-functions.php.
References $user_id, delete_user_option(), do_action(), is_wp_error(), sanitize_user(), and wp_create_user().
Referenced by wpmu_activate_signup().
wpmu_log_new_registrations ($blog_id, $user_id)
Logs user registrations.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
int $blog_id
int $user_id
Definition at line 1776 of file ms-functions.php.
References $_SERVER, $blog_id, $user, $user_id, $wpdb, current_time(), and wp_unslash().
wpmu_signup_blog ($domain, $path, $title, $user, $user_email, $meta = array())
Record site signup information for future activation.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $domain The requested domain.
string $path The requested path.
string $title The requested site title.
string $user The user's requested login name.
string $user_email The user's email address.
array $meta By default, contains the requested privacy setting and lang_id.
Fires after site signup information has been written to the database.
Since
4.4.0
Parameters
string $domain The requested domain.
string $path The requested path.
string $title The requested site title.
string $user The user's requested login name.
string $user_email The user's email address.
string $key The user's activation key
array $meta By default, contains the requested privacy setting and lang_id.
Definition at line 666 of file ms-functions.php.
References $path, $title, $user, $wpdb, current_time(), and do_action().
wpmu_signup_blog_notification ($domain, $path, $title, $user, $user_email, $key, $meta = array())
Notify user of signup success.
This is the notification function used when site registration is enabled.
Filter 'wpmu_signup_blog_notification' to bypass this function or replace it with your own notification behavior.
Filter 'wpmu_signup_blog_notification_email' and 'wpmu_signup_blog_notification_subject' to change the content and subject line of the email sent to newly registered users.
Since
MU
Parameters
string $domain The new blog domain.
string $path The new blog path.
string $title The site title.
string $user The user's login name.
string $user_email The user's email address.
string $key The activation key created in wpmu_signup_blog()
array $meta By default, contains the requested privacy setting and lang_id.
Returns
bool
Filter whether to bypass the new site email notification.
Since
MU
Parameters
string | bool $domain Site domain.
string $path Site path.
string $title Site title.
string $user User login name.
string $user_email User email address.
string $key Activation key created in wpmu_signup_blog().
array $meta By default, contains the requested privacy setting and lang_id.
Filter the message content of the new blog notification email.
Content should be formatted for transmission via wp_mail().
Since
MU
Parameters
string $content Content of the notification email.
string $domain Site domain.
string $path Site path.
string $title Site title.
string $user User login name.
string $user_email User email address.
string $key Activation key created in wpmu_signup_blog().
array $meta By default, contains the requested privacy setting and lang_id.
Filter the subject of the new blog notification email.
Since
MU
Parameters
string $subject Subject of the notification email.
string $domain Site domain.
string $path Site path.
string $title Site title.
string $user User login name.
string $user_email User email address.
string $key Activation key created in wpmu_signup_blog().
array $meta By default, contains the requested privacy setting and lang_id.
Definition at line 770 of file ms-functions.php.
References $_SERVER, $message, $path, $title, $user, __, apply_filters(), esc_html, esc_url, get_current_site(), get_option(), get_site_option(), is_subdomain_install(), network_site_url(), and wp_specialchars_decode().
wpmu_signup_user ($user, $user_email, $meta = array())
Record user signup information for future activation.
This function is used when user registration is open but new site registration is not.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $user The user's requested login name.
string $user_email The user's email address.
array $meta By default, this is an empty array.
Fires after a user's signup information has been written to the database.
Since
4.4.0
Parameters
string $user The user's requested login name.
string $user_email The user's email address.
string $key The user's activation key
array $meta Additional signup meta. By default, this is an empty array.
Definition at line 713 of file ms-functions.php.
References $user, $wpdb, current_time(), do_action(), sanitize_email(), and sanitize_user().
wpmu_signup_user_notification ($user, $user_email, $key, $meta = array())
Notify user of signup success.
This is the notification function used when no new site has been requested.
Filter 'wpmu_signup_user_notification' to bypass this function or replace it with your own notification behavior.
Filter 'wpmu_signup_user_notification_email' and 'wpmu_signup_user_notification_subject' to change the content and subject line of the email sent to newly registered users.
Since
MU
Parameters
string $user The user's login name.
string $user_email The user's email address.
string $key The activation key created in wpmu_signup_user()
array $meta By default, an empty array.
Returns
bool
Filter whether to bypass the email notification for new user sign-up.
Since
MU
Parameters
string $user User login name.
string $user_email User email address.
string $key Activation key created in wpmu_signup_user().
array $meta Signup meta data.
Filter the content of the notification email for new user sign-up.
Content should be formatted for transmission via wp_mail().
Since
MU
Parameters
string $content Content of the notification email.
string $user User login name.
string $user_email User email address.
string $key Activation key created in wpmu_signup_user().
array $meta Signup meta data.
Filter the subject of the notification email of new user signup.
Since
MU
Parameters
string $subject Subject of the notification email.
string $user User login name.
string $user_email User email address.
string $key Activation key created in wpmu_signup_user().
array $meta Signup meta data.
Definition at line 873 of file ms-functions.php.
References $_SERVER, $message, $user, __, apply_filters(), esc_html, get_option(), get_site_option(), site_url(), and wp_specialchars_decode().
wpmu_validate_blog_signup ($blogname, $blog_title, $user = '')
Processes new site registrations.
Checks the data provided by the user during blog signup. Verifies the validity and uniqueness of blog paths and domains.
This function prevents the current user from registering a new site with a blogname equivalent to another user's login name. Passing the $user parameter to the function, where $user is the other user, is effectively an override of this limitation.
Filter 'wpmu_validate_blog_signup' if you want to modify the way that WordPress validates new site signups.
Since
MU
wpdb $wpdb string $domain
Parameters
string $blogname The blog name provided by the user. Must be unique.
string $blog_title The blog title provided by the user.
WP_User | string $user Optional. The user object to check against the new site name.
Returns
array Contains the new site data and error messages.
Filter the new site name during registration.
The name is the site's subdomain or the site's subdirectory path depending on the network settings.
Since
MU
Parameters
string $blogname Site name.
Filter site details and error messages following registration.
Since
MU
Parameters
array $result { Array of domain, path, blog name, blog title, user and error messages.
string $domain Domain for the site. string $path Path for the site. Used in subdirectory installs. string $blogname The unique site name (slug). string $blog_title Blog title. string|WP_User $user By default, an empty string. A user object if provided. WP_Error $errors WP_Error containing any errors found. }
Definition at line 543 of file ms-functions.php.
References $current_site, $errors, $path, $user, $wpdb, __, add_site_option(), apply_filters(), current_time(), domain_exists(), get_current_site(), get_site_option(), get_subdirectory_reserved_names(), is_subdomain_install(), is_super_admin(), mysql2date(), username_exists(), and wp_unslash().
wpmu_validate_user_signup ($user_name, $user_email)
Sanitize and validate data required for a user sign-up.
Verifies the validity and uniqueness of user names and user email addresses, and checks email addresses against admin-provided domain whitelists and blacklists.
The {
See also
'wpmu_validate_user_signup'} hook provides an easy way to modify the sign-up process. The value $result, which is passed to the hook, contains both the user-provided info and the error messages created by the function. {
'wpmu_validate_user_signup'} allows you to process the data in any way you'd like, and unset the relevant errors if necessary.
Since
MU
wpdb $wpdb WordPress database abstraction object.
Parameters
string $user_name The login name provided by the user.
string $user_email The email provided by the user.
Returns
array Contains username, email, and error messages.
This filter is documented in wp-includes/user.php
Filter the validated user registration details.
This does not allow you to override the username or email of the user during registration. The values are solely used for validation and error handling.
Since
MU
Parameters
array $result { The array of user name, email and the error messages.
string $user_name Sanitized and unique username. string $orig_username Original username. string $user_email User email address. WP_Error $errors WP_Error object containing any errors found. }
Definition at line 407 of file ms-functions.php.
References $errors, $now, $wpdb, __, add_site_option(), apply_filters(), current_time(), email_exists(), get_site_option(), is_email(), is_email_address_unsafe(), mysql2date(), null, sanitize_email(), sanitize_user(), and username_exists().
wpmu_welcome_notification ($blog_id, $user_id, $password, $title, $meta = array())
Notify a user that their blog activation has been successful.
Filter 'wpmu_welcome_notification' to disable or bypass.
Filter 'update_welcome_email' and 'update_welcome_subject' to modify the content and subject line of the notification email.
Since
MU
Parameters
int $blog_id
int $user_id
string $password
string $title The new blog's title
array $meta Optional. Not used in the default function, but is passed along to hooks for customization.
Returns
bool
Filter whether to bypass the welcome email after site activation.
Returning false disables the welcome email.
Since
MU
Parameters
int | bool $blog_id Blog ID.
int $user_id User ID.
string $password User password.
string $title Site title.
array $meta Signup meta data.
Filter the content of the welcome email after site activation.
Content should be formatted for transmission via wp_mail().
Since
MU
Parameters
string $welcome_email Message body of the email.
int $blog_id Blog ID.
int $user_id User ID.
string $password User password.
string $title Site title.
array $meta Signup meta data.
Filter the subject of the welcome email after site activation.
Since
MU
Parameters
string $subject Subject of the email.
Definition at line 1419 of file ms-functions.php.
References $_SERVER, $blog_id, $current_site, $message, $title, $url, $user, $user_id, __, apply_filters(), esc_html, get_blogaddress_by_id(), get_current_site(), get_option(), get_site_option(), str_replace, wp_specialchars_decode(), and wp_unslash().
wpmu_welcome_user_notification ($user_id, $password, $meta = array())
Notify a user that their account activation has been successful.
Filter 'wpmu_welcome_user_notification' to disable or bypass.
Filter 'update_welcome_user_email' and 'update_welcome_user_subject' to modify the content and subject line of the notification email.
Since
MU
Parameters
int $user_id
string $password
array $meta Optional. Not used in the default function, but is passed along to hooks for customization.
Returns
bool
Filter whether to bypass the welcome email after user activation.
Returning false disables the welcome email.
Since
MU
Parameters
int $user_id User ID.
string $password User password.
array $meta Signup meta data.
Filter the content of the welcome email after user activation.
Content should be formatted for transmission via wp_mail().
Since
MU
Parameters
type $welcome_email The message body of the account activation success email.
int $user_id User ID.
string $password User password.
array $meta Signup meta data.
Filter the subject of the welcome email after user activation.
Since
MU
Parameters
string $subject Subject of the email.
Definition at line 1520 of file ms-functions.php.
References $_SERVER, $current_site, $message, $user, $user_id, __, apply_filters(), esc_html, get_current_site(), get_option(), get_site_option(), str_replace, wp_login_url(), and wp_specialchars_decode().