GravityView: ms-load.php File Reference
ms-load.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
get_current_site_name ($current_site)
This deprecated function formerly set the site_name property of the $current_site object.
get_network_by_path ($domain, $path, $segments=null)
Retrieve the closest matching network for a domain and path.
get_site_by_path ($domain, $path, $segments=null)
Retrieve a site object by its domain and path.
is_subdomain_install ()
Whether a subdomain configuration is enabled.
ms_not_installed ($domain, $path)
Displays a failure message.
ms_site_check ()
Checks status of current blog.
wp_get_active_network_plugins ()
Returns array of network plugin files to be included in global scope.
wp_get_network ($network)
Retrieve an object containing information about the requested network.
wpmu_current_site ()
This deprecated function managed much of the site and network loading in multisite.
Function Documentation
get_current_site_name ($current_site)
This deprecated function formerly set the site_name property of the $current_site object.
This function simply returns the object, as before. The bootstrap takes care of setting site_name.
private
Since
3.0.0
Parameters
object $current_site
Returns
object
Definition at line 336 of file ms-load.php.
References $current_site, and _deprecated_function().
get_network_by_path ($domain, $path, $segments = null)
Retrieve the closest matching network for a domain and path.
Since
3.9.0
4.4.0 Converted to a wrapper for WP_Network::get_by_path()
Parameters
string $domain Domain to check.
string $path Path to check.
int | null $segments Path segments to use. Defaults to null, or the full path.
Returns
WP_Network|false Network object if successful. False when no network is found.
Definition at line 130 of file ms-load.php.
References $path, and WP_Network\get_by_path().
get_site_by_path ($domain, $path, $segments = null)
Retrieve a site object by its domain and path.
Since
3.9.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $domain Domain to check.
string $path Path to check.
int | null $segments Path segments to use. Defaults to null, or the full path.
Returns
object|false Site object if successful. False when no site is found.
Filter the number of path segments to consider when searching for a site.
Since
3.9.0
Parameters
int | null $segments The number of path segments to consider. WordPress by default looks at one path segment following the network path. The function default of null only makes sense when you know the requested path should match a site.
string $domain The requested domain.
string $path The requested path, in full.
Determine a site by its domain and path.
This allows one to short-circuit the default logic, perhaps by replacing it with a routine that is more optimal for your setup.
Return null to avoid the short-circuit. Return false if no site can be found at the requested domain and path. Otherwise, return a site object.
Since
3.9.0
Parameters
null | bool | object $site Site value to return by path.
string $domain The requested domain.
string $path The requested path, in full.
int | null $segments The suggested number of paths to consult. Default null, meaning the entire path was to be consulted.
array $paths The paths to search for, based on $path and $segments.
Definition at line 165 of file ms-load.php.
References $path, $wpdb, apply_filters(), elseif, and null.
is_subdomain_install ()
Whether a subdomain configuration is enabled.
Since
3.0.0
Returns
bool True if subdomain configuration is enabled, false otherwise.
Definition at line 18 of file ms-load.php.
Referenced by avoid_blog_page_permalink_collision(), get_blog_details(), get_blogaddress_by_domain(), get_blogaddress_by_name(), get_id_from_blogname(), install_blog(), ms_cookie_constants(), network_step2(), WP_MS_Sites_List_Table\prepare_items(), wpmu_create_blog(), wpmu_signup_blog_notification(), and wpmu_validate_blog_signup().
ms_not_installed ($domain, $path)
Displays a failure message.
Used when a blog's tables do not exist. Checks for a missing $wpdb->site table as well.
private
Since
3.0.0
4.4.0 The $domain and $path parameters were added.
wpdb $wpdb WordPress database abstraction object.
Parameters
string $domain The requested domain for the error to reference.
string $path The requested path for the error to reference.
Definition at line 277 of file ms-load.php.
References $msg, $path, $title, $wpdb, __, DB_NAME, dead_db(), is_admin(), wp_die(), and wp_load_translations_early().
ms_site_check ()
Checks status of current blog.
Checks if the blog is deleted, inactive, archived, or spammed.
Dies with a default message if the blog does not pass the check.
To change the default message when a blog does not pass the check, use the wp-content/blog-deleted.php, blog-inactive.php and blog-suspended.php drop-ins.
Since
3.0.0
Returns
true|string Returns true on success, or drop-in file to include.
Filter checking the status of the current blog.
Since
3.0.0
Parameters
bool null Whether to skip the blog status check. Default null.
Definition at line 70 of file ms-load.php.
References $blog, __, apply_filters(), get_blog_details(), get_current_site(), get_site_option(), is_super_admin(), null, str_replace, WP_CONTENT_DIR, and wp_die().
wp_get_active_network_plugins ()
Returns array of network plugin files to be included in global scope.
The default directory is wp-content/plugins. To change the default directory manually, define WP_PLUGIN_DIR and WP_PLUGIN_URL in wp-config.php.
private
Since
3.1.0
Returns
array Files to include.
Definition at line 36 of file ms-load.php.
References $plugin, $plugins, get_site_option(), and validate_file().
Referenced by wp_get_active_and_valid_plugins().
wp_get_network ($network)
Retrieve an object containing information about the requested network.
Since
3.9.0
4.4.0 Converted to leverage WP_Network
Parameters
object | int $network The network's database row or ID.
Returns
WP_Network|false Object containing network information if found, false if not.
Definition at line 143 of file ms-load.php.
References WP_Network\get_instance().
Referenced by WP_UnitTest_Factory_For_Network\get_object_by_id().
wpmu_current_site ()
This deprecated function managed much of the site and network loading in multisite.
The current bootstrap code is now responsible for parsing the site and network load as well as setting the global $current_site object.
private
Since
3.0.0
object $current_site
Returns
object
Definition at line 355 of file ms-load.php.
References $current_site, and _deprecated_function().