GravityView: ms.php File Reference
ms.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_access_denied_splash ()
Displays an access denied message when a user tries to view a site's dashboard they do not have access to.
_thickbox_path_admin_subfolder ()
Thickbox image paths for Network Admin.
avoid_blog_page_permalink_collision ($data, $postarr)
Avoids a collision between a site slug and a permalink slug.
can_edit_network ($site_id)
Whether or not we can edit this network from this page.
check_import_new_users ($permission)
Checks if the current user has permissions to import new users.
check_upload_size ($file)
Determine if uploaded file exceeds space quota.
choose_primary_blog ()
Handles the display of choosing a user's primary site.
confirm_delete_users ($users)
display_space_usage ()
Displays the amount of disk space used by the current blog.
fix_import_form_size ($size)
Get the remaining upload space for this blog.
format_code_lang ($code= '')
Returns the language for a language code.
grant_super_admin ($user_id)
Grants Super Admin privileges.
mu_dropdown_languages ($lang_files=array(), $current= '')
Generates and displays a drop-down of available languages.
network_settings_add_js ()
Print JavaScript in the header on the Network Settings screen.
new_user_email_admin_notice ()
Adds an admin notice alerting the user to check for confirmation email after email address change.
refresh_user_details ($id)
Cleans the user cache for a specific user.
revoke_super_admin ($user_id)
Revokes Super Admin privileges.
send_confirmation_on_profile_email ()
Sends an email when an email address change is requested.
site_admin_notice ()
Displays an admin notice to upgrade all sites after a core upgrade.
sync_category_tag_slugs ($term, $taxonomy)
Synchronize category and post tag slugs when global terms are enabled.
update_option_new_admin_email ($old_value, $value)
Sends an email when a site administrator email address is changed.
update_user_status ($id, $pref, $value, $deprecated=null)
Update the status of a user in the database.
upload_is_user_over_quota ($echo=true)
Check whether a blog has used its allotted upload space.
upload_space_setting ($id)
Displays the edit blog upload space setting form on the Edit Blog screen.
wpmu_delete_blog ($blog_id, $drop=false)
Delete a blog.
wpmu_delete_user ($id)
Delete a user from the network and remove from all sites.
Function Documentation
_access_denied_splash ()
Displays an access denied message when a user tries to view a site's dashboard they do not have access to.
Since
3.2.0 private
Definition at line 643 of file ms.php.
References $blog, $blog_name, $blogs, $output, __, esc_url, get_admin_url(), get_bloginfo(), get_blogs_of_user(), get_current_blog_id(), get_current_user_id(), get_home_url(), is_network_admin(), wp_die(), and wp_list_filter().
_thickbox_path_admin_subfolder ()
Thickbox image paths for Network Admin.
Since
3.1.0
private
Definition at line 975 of file ms.php.
avoid_blog_page_permalink_collision ($data, $postarr)
Avoids a collision between a site slug and a permalink slug.
In a subdirectory install this will make sure that a site and a post do not use the same subdirectory by checking for a site with the same name as a new post.
Since
3.0.0
Parameters
array $data An array of post data.
array $postarr An array of posts. Not currently used.
Returns
array The new array of post data after checking for collisions.
Definition at line 770 of file ms.php.
References get_id_from_blogname(), is_main_site(), and is_subdomain_install().
can_edit_network ($site_id)
Whether or not we can edit this network from this page.
By default editing of network is restricted to the Network Admin for that $site_id this allows for this to be overridden.
Since
3.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $site_id The network/site ID to check.
Returns
bool True if network can be edited, otherwise false.
Filter whether this network can be edited from this page.
Since
3.1.0
Parameters
bool $result Whether the network can be edited from this page.
int $site_id The network/site ID to check.
Definition at line 949 of file ms.php.
References $wpdb, and apply_filters().
Referenced by WP_MS_Users_List_Table\column_blogs().
check_import_new_users ($permission)
Checks if the current user has permissions to import new users.
Since
3.0.0
Parameters
string $permission A permission to be checked. Currently not used.
Returns
bool True if the user has proper permissions, false if they do not.
Definition at line 684 of file ms.php.
References is_super_admin().
check_upload_size ($file)
Determine if uploaded file exceeds space quota.
Since
3.0.0
Parameters
array $file $_FILES array for a given file.
Returns
array $_FILES array with 'error' key set if file exceeds quota. 'error' is empty otherwise.
Definition at line 18 of file ms.php.
References $file, __, DOING_AJAX, get_site_option(), get_upload_space_available(), upload_is_user_over_quota(), and wp_die().
choose_primary_blog ()
Handles the display of choosing a user's primary site.
This displays the user's primary site and allows the user to choose which site is primary.
Since
3.0.0
Definition at line 800 of file ms.php.
References $blog, _e, elseif, esc_url, get_blogs_of_user(), get_current_user_id(), get_home_url(), get_user_meta(), label, name, selected(), and update_user_meta().
confirm_delete_users ($users)
Parameters
array $users
This action is documented in wp-admin/users.php
Definition at line 987 of file ms.php.
References $blogs, $current_user, $details, $user, $user_id, __, _e, checked(), current_user_can(), do_action(), endif, esc_attr(), esc_html_e, esc_url, get_blogs_of_user(), get_home_url(), get_super_admins(), get_users(), input, label, li, name, submit_button(), wp_die(), and wp_nonce_field().
display_space_usage ()
Displays the amount of disk space used by the current blog.
Not used in core.
Since
MU
Definition at line 444 of file ms.php.
References __, get_space_allowed(), and get_space_used().
fix_import_form_size ($size)
Get the remaining upload space for this blog.
Since
MU
Parameters
int $size Current max size in bytes
Returns
int Max size in bytes
Definition at line 472 of file ms.php.
References $size, get_upload_space_available(), and upload_is_user_over_quota().
format_code_lang ($code = '')
Returns the language for a language code.
Since
3.0.0
Parameters
string $code Optional. The two-letter language code. Default empty.
Returns
string The language corresponding to $code if it exists. If it does not exist, then the first two letters of $code is returned.
Filter the language codes.
Since
MU
Parameters
array $lang_codes Key/value pair of language codes where key is the short version.
string $code A two-letter designation of the language.
Definition at line 586 of file ms.php.
References apply_filters().
Referenced by mu_dropdown_languages().
grant_super_admin ($user_id)
Grants Super Admin privileges.
Since
3.0.0
array $super_admins
Parameters
int $user_id ID of the user to be granted Super Admin privileges.
Returns
bool True on success, false on failure. This can fail when the user is already a super admin or when the $super_admins global is defined.
Fires before the user is granted Super Admin privileges.
Since
3.0.0
Parameters
int $user_id ID of the user that is about to be granted Super Admin privileges.
Fires after the user is granted Super Admin privileges.
Since
3.0.0
Parameters
int $user_id ID of the user that was granted Super Admin privileges.
Definition at line 851 of file ms.php.
References $GLOBALS, $user, $user_id, do_action(), get_site_option(), and update_site_option().
mu_dropdown_languages ($lang_files = array(), $current = '')
Generates and displays a drop-down of available languages.
Since
3.0.0
Parameters
array $lang_files Optional. An array of the language files. Default empty array.
string $current Optional. The current language code. Default empty.
Filter the languages available in the dropdown.
Since
MU
Parameters
array $output HTML output of the dropdown.
array $lang_files Available language files.
string $current The current language code.
Definition at line 699 of file ms.php.
References $output, __, apply_filters(), elseif, esc_attr(), esc_html, format_code_lang(), and selected().
network_settings_add_js ()
Print JavaScript in the header on the Network Settings screen.
Since
4.1.0
Definition at line 1097 of file ms.php.
new_user_email_admin_notice ()
Adds an admin notice alerting the user to check for confirmation email after email address change.
Since
3.0.0
Definition at line 407 of file ms.php.
References $_SERVER, __, get_current_user_id(), and get_option().
refresh_user_details ($id)
Cleans the user cache for a specific user.
Since
3.0.0
Parameters
int $id The user ID.
Returns
bool|int The ID of the refreshed user or false if the user does not exist.
Definition at line 566 of file ms.php.
References $id, $user, and clean_user_cache().
revoke_super_admin ($user_id)
Revokes Super Admin privileges.
Since
3.0.0
array $super_admins
Parameters
int $user_id ID of the user Super Admin privileges to be revoked from.
Returns
bool True on success, false on failure. This can fail when the user's email is the network admin email or when the $super_admins global is defined.
Fires before the user's Super Admin privileges are revoked.
Since
3.0.0
Parameters
int $user_id ID of the user Super Admin privileges are being revoked from.
Fires after the user's Super Admin privileges are revoked.
Since
3.0.0
Parameters
int $user_id ID of the user Super Admin privileges were revoked from.
Definition at line 898 of file ms.php.
References $GLOBALS, $user, $user_id, do_action(), get_site_option(), and update_site_option().
send_confirmation_on_profile_email ()
Sends an email when an email address change is requested.
Since
3.0.0
WP_Error $errors WP_Error object. wpdb $wpdb WordPress database object.
Filter the email text sent when a user changes emails.
The following strings have a special meaning and will get replaced dynamically:
USERNAME### The current user's username.
ADMIN_URL### The link to click on to confirm the email change.
EMAIL### The new email.
SITENAME### The name of the site.
SITEURL### The URL to the site.
Since
MU
Parameters
string $email_text Text in the email.
string $new_user_email New user email that the current user has changed to.
Definition at line 328 of file ms.php.
References $content, $current_user, $errors, $wpdb, __, admin_url(), apply_filters(), delete_option(), esc_url, get_option(), get_site_option(), is_email(), network_home_url(), str_replace, update_option(), and wp_specialchars_decode().
site_admin_notice ()
Displays an admin notice to upgrade all sites after a core upgrade.
Since
3.0.0
int $wp_db_version The version number of the database.
Returns
false False if the current user is not a super admin.
Definition at line 750 of file ms.php.
References $wp_db_version, __, esc_url, get_site_option(), is_super_admin(), and network_admin_url().
sync_category_tag_slugs ($term, $taxonomy)
Synchronize category and post tag slugs when global terms are enabled.
Since
3.0.0
Parameters
object $term The term.
string $taxonomy The taxonomy for $term. Should be 'category' or 'post_tag', as these are the only taxonomies which are processed by this function; anything else will be returned untouched.
Returns
object|array Returns $term, after filtering the 'slug' field with {
See also
sanitize_title()} if $taxonomy is 'category' or 'post_tag'.
Definition at line 625 of file ms.php.
References global_terms_enabled(), and sanitize_title().
update_option_new_admin_email ($old_value, $value)
Sends an email when a site administrator email address is changed.
Since
3.0.0
Parameters
string $old_value The old email address. Not currently used.
string $value The new email address.
Filter the email text sent when the site admin email is changed.
The following strings have a special meaning and will get replaced dynamically:
USERNAME### The current user's username.
ADMIN_URL### The link to click on to confirm the email change.
EMAIL### The new email.
SITENAME### The name of the site.
SITEURL### The URL to the site.
Since
MU
Parameters
string $email_text Text in the email.
string $new_admin_email New admin email that the current administration email was changed to.
Definition at line 264 of file ms.php.
References $content, $current_user, $new_admin_email, $value, __, admin_url(), apply_filters(), esc_url, get_option(), get_site_option(), is_email(), network_home_url(), str_replace, update_option(), and wp_specialchars_decode().
update_user_status ($id, $pref, $value, $deprecated = null)
Update the status of a user in the database.
Used in core to mark a user as spam or "ham" (not spam) in Multisite.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $id The user ID.
string $pref The column in the wp_users table to update the user's status in (presumably user_status, spam, or deleted).
int $value The new status for the user.
null $deprecated Deprecated as of 3.0.2 and should not be used.
Returns
int The initially passed $value.
Fires after the user is marked as a SPAM user.
Since
3.0.0
Parameters
int $id ID of the user marked as SPAM.
Fires after the user is marked as a HAM user. Opposite of SPAM.
Since
3.0.0
Parameters
int $id ID of the user marked as HAM.
Definition at line 522 of file ms.php.
References $deprecated, $id, $user, $value, $wpdb, _deprecated_argument(), clean_user_cache(), do_action(), null, and sanitize_key().
upload_is_user_over_quota ($echo = true)
Check whether a blog has used its allotted upload space.
Since
MU
Parameters
bool $echo Optional. If $echo is set and the quota is exceeded, a warning message is echoed. Default is true.
Returns
bool True if user is over upload space quota, otherwise false.
Definition at line 420 of file ms.php.
References _e, get_site_option(), get_space_allowed(), and get_space_used().
Referenced by check_upload_size(), fix_import_form_size(), WP_Importer\is_user_over_quota(), and wp_xmlrpc_server\mw_newMediaObject().
upload_space_setting ($id)
Displays the edit blog upload space setting form on the Edit Blog screen.
Since
3.0.0
Parameters
int $id The ID of the blog to display the setting for.
Definition at line 487 of file ms.php.
References $id, _e, get_option(), input, label, name, restore_current_blog(), and switch_to_blog().
wpmu_delete_blog ($blog_id, $drop = false)
Delete a blog.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $blog_id Blog ID.
bool $drop True if blog's table should be dropped. Default is false.
Fires before a blog is deleted.
Since
MU
Parameters
int $blog_id The blog ID.
bool $drop True if blog's table should be dropped. Default is false.
Filter the tables to drop when the blog is deleted.
Since
MU
Parameters
array $tables The blog tables to be dropped.
int $blog_id The ID of the blog to drop tables for.
Filter the upload base directory to delete when the blog is deleted.
Since
MU
Parameters
string $uploads,['basedir'] Uploads path without subdirectory.
See also
wp_upload_dir()
Parameters
int $blog_id The blog ID.
Definition at line 60 of file ms.php.
References $blog, $blog_id, $current_site, $dir, $file, $user_id, $wpdb, apply_filters(), clean_blog_cache(), do_action(), elseif, get_blog_details(), get_current_blog_id(), get_current_site(), get_option(), get_site_option(), get_users(), is_main_site(), remove_user_from_blog(), restore_current_blog(), switch_to_blog(), update_blog_status(), and wp_upload_dir().
wpmu_delete_user ($id)
Delete a user from the network and remove from all sites.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $id The user ID.
Returns
bool True if the user was deleted, otherwise false.
Fires before a user is deleted from the network.
Since
MU
Parameters
int $id ID of the user about to be deleted from the network.
This action is documented in wp-admin/includes/user.php
Definition at line 190 of file ms.php.
References $blog, $blogs, $id, $post_id, $user, $wpdb, clean_user_cache(), delete_metadata_by_mid(), do_action(), get_blogs_of_user(), get_super_admins(), remove_user_from_blog(), restore_current_blog(), switch_to_blog(), wp_delete_link(), and wp_delete_post().
Referenced by WP_UnitTestCase\delete_user().