GravityView: my-sites.php File Reference
my-sites.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$action = isset($_POST['action']) ? $_POST['action'] : 'splash'
$blogs = get_blogs_of_user($current_user->ID)
$parent_file = 'index.php'
$settings_html = apply_filters('myblogs_options', '', 'global')
Enable the Global Settings section on the My Sites screen.
if('updateblogsettings'==$action &&isset($_POST['primary_blog'])) $title = __('My Sites')
$updated = false
else __pad0__
foreach($blogs as $user_blog) if(count($blogs) > 1||has_action('myblogs_allblogs_options')||has_filter('myblogs_options')) endif
if ($updated)
Variable Documentation
$action = isset($_POST['action']) ? $_POST['action'] : 'splash'
Definition at line 18 of file my-sites.php.
$blogs = get_blogs_of_user($current_user->ID)
Definition at line 20 of file my-sites.php.
Referenced by _access_denied_splash(), wp_xmlrpc_server\_multisite_getUsersBlogs(), WP_MS_Users_List_Table\column_blogs(), confirm_delete_users(), get_active_blog_for_user(), get_blog_list(), get_blogs_of_user(), get_dashboard_url(), get_most_active_blogs(), remove_user_from_blog(), wp_xmlrpc_server\wp_getUsersBlogs(), and wpmu_delete_user().
$parent_file = 'index.php'
Definition at line 36 of file my-sites.php.
$settings_html = apply_filters('myblogs_options', '', 'global')
Enable the Global Settings section on the My Sites screen.
By default, the Global Settings section is hidden. Passing a non-empty string to this filter will enable the section, and allow new settings to be added, either globally or for specific sites.
Since
MU
Parameters
string $settings_html The settings HTML markup. Default empty.
object $context Context of the setting (global or site-specific). Default 'global'.
Definition at line 101 of file my-sites.php.
if ('updateblogsettings'==$action &&isset($_POST['primary_blog'])) $title = __('My Sites')
Definition at line 35 of file my-sites.php.
$updated = false
Definition at line 22 of file my-sites.php.
Referenced by bulk_edit_posts(), GravityView_Edit_Entry_User_Registration\restore_display_name(), WP_Press_This\save_post(), GFFormsModel\trim_conditional_logic_values(), GFFormsModel\trim_conditional_logic_values_from_element(), update_term_meta(), and wp_ajax_inline_save_tax().
else __pad0__
Definition at line 73 of file my-sites.php.
foreach ($blogs as $user_blog) if (count($blogs) > 1||has_action('myblogs_allblogs_options')||has_filter('myblogs_options')) endif
Definition at line 126 of file my-sites.php.
if($updated)
Definition at line 54 of file my-sites.php.