GravityView: GravityKit\GravityView\Foundation Namespace Reference
GravityKit\GravityView\Foundation Namespace Reference
GPL-2.0-or-later
Namespaces
Encryption
GPL-2.0-or-later
Helpers
GPL-2.0-or-later
Integrations
GPL-2.0-or-later
Licenses
GPL-2.0-or-later
Logger
GPL-2.0-or-later
Settings
GPL-2.0-or-later
Translations
GPL-2.0-or-later
WP
GPL-2.0-or-later
Data Structures
class Core
Functions
is_disabled_via_url ($plugin_file)
Checks if loading is disabled via a URL parameter.
meets_min_php_version_requirement ($plugin_file, $min_php_version='5.6.4', $show_notice=true)
Checks if the minimum PHP version requirement is met.
should_load ($plugin_file)
Determines if a plugin should load.
Detailed Description
GPL-2.0-or-later
Modified by gravityview on 13-January-2023 using Strauss.
See also
https://github.com/BrianHenryIE/strauss
Function Documentation
is_disabled_via_url()
GravityKit\GravityView\Foundation\is_disabled_via_url ($plugin_file)
Checks if loading is disabled via a URL parameter.
Adding ?gk_disable_loading to the URL will prevent the loading of all plugins that include Foundation. Adding ?gk_disable_loading=plugin-text-domain to the URL will prevent the loading of specific plugin(s) that includes Foundation (multiple text domains can be comma-separated).
Since
1.0.4
Parameters
string $plugin_file Absolute path to the main plugin file.
Returns
bool
Definition at line 38 of file preflight_check.php.
References Core\get_plugin_data().
Referenced by GravityKit\GravityView\Foundation\should_load().
meets_min_php_version_requirement()
GravityKit\GravityView\Foundation\meets_min_php_version_requirement ($plugin_file, $min_php_version = '5.6.4', $show_notice = true)
Checks if the minimum PHP version requirement is met.
Parameters
string $plugin_file Absolute path to the main plugin file.
string $min_php_version (optional) Minimum PHP version. Default: 5.6.4.
bool $show_notice (optional) Display error notice. Default: true.
Returns
bool
Definition at line 93 of file preflight_check.php.
References Core\get_plugin_data().
Referenced by GravityKit\GravityView\Foundation\should_load().
should_load()
GravityKit\GravityView\Foundation\should_load ($plugin_file)
Determines if a plugin should load.
Since
1.0.3
1.0.4 Repurposed as a catch-all method that performs multiple checks
Parameters
string $plugin_file Absolute path to the main plugin file.
Returns
bool
Definition at line 23 of file preflight_check.php.
References GravityKit\GravityView\Foundation\is_disabled_via_url(), and GravityKit\GravityView\Foundation\meets_min_php_version_requirement().