GravityView: GV\Mocks Namespace Reference
GV\Mocks Namespace Reference
Data Structures
class GF_Query_Call_TIMESORT
Time merge calls.
class GF_Query_Condition_IS_NULL
Gravity Forms GF_Query does not support NULL condition clauses.
class Legacy_Context
A manager of legacy global states and contexts.
Functions
GravityView_API_field_label ($form, $field_settings, $entry, $force_show_label=false)
Mock out the ::field_label method.
GravityView_API_field_value ($entry, $field_settings, $format)
The old function does a bit too much, not only does it retrieve the value for a field, but it also renders some output.
GravityView_frontend_get_view_entries ($args, $form_id, $parameters, $count)
GravityView_View_Data_add_view ($view_id, $atts, $_this)
This file contains mock code for deprecated functions.
Function Documentation
GravityView_API_field_label()
GV\Mocks\GravityView_API_field_label ($form, $field_settings, $entry, $force_show_label = false)
Mock out the ::field_label method.
Uses the new ::get_label methods
See also
::field_label
A bail condition.
Runs Filter:
gravityview_render_after_label Append content to a field label
Parameters
string $appended_content Content you can add after a label. Empty by default.
array $field GravityView field array
Runs Filter:
gravityview/template/field_label Modify field label output
Since
1.7
Parameters
string $label Field label HTML
array $field GravityView field array
array $form Gravity Forms form array
array $entry Gravity Forms entry array
Determine the source backend.
Fields with a numeric ID are Gravity Forms ones.
Initialize the future field.
The Gravity Forms backend.
The label never wins...
Our internal backend.
An unidentified backend.
Add the field settings.
Runs Filter:
gravityview_render_after_label Append content to a field label
Parameters
string $appended_content Content you can add after a label. Empty by default.
array $field GravityView field array
Runs Filter:
gravityview/template/field_label Modify field label output
Since
1.7
Parameters
string $label Field label HTML
array $field GravityView field array
array $form Gravity Forms form array
array $entry Gravity Forms entry array
Definition at line 214 of file _mocks.php.
References $entry, $field, $field_settings, GV\$form, $label, Source\BACKEND_GRAVITYFORMS, Source\BACKEND_INTERNAL, GF_Form\by_id(), GF_Entry\by_id(), endswitch, Internal_Source\get_field(), gravityview(), and GravityView_API\replace_variables().
Referenced by GravityView_API\field_label().
GravityView_API_field_value()
GV\Mocks\GravityView_API_field_value ($entry, $field_settings, $format)
The old function does a bit too much, not only does it retrieve the value for a field, but it also renders some output.
We are stubbing the plain value part of it, the rendering will follow once our field renderers are ready.
See also
::field_value
Determine the source backend.
Fields with a numeric ID are Gravity Forms ones.
Initialize the future field.
The Gravity Forms backend.
Our internal backend.
An unidentified backend.
Add the field settings.
Definition at line 144 of file _mocks.php.
References $entry, $field, $field_settings, GV\$form, Source\BACKEND_GRAVITYFORMS, Source\BACKEND_INTERNAL, GF_Form\by_id(), GF_Entry\by_id(), endswitch, Multi_Entry\from_entries(), Internal_Source\get_field(), and gravityview().
Referenced by GravityView_API\field_value().
GravityView_frontend_get_view_entries()
GV\Mocks\GravityView_frontend_get_view_entries ($args, $form_id, $parameters, $count)
See also
::get_view_entries
Kick off all advanced filters.
Parameters and criteria are pretty much the same thing here, just different naming, where $parameters are the initial parameters calculated for hte view, and $criteria are the filtered ones retrieved via ::calculate_get_entries_criteria()
...and all the (now deprecated) filters that usually follow gravityview_get_entries
We've been given an entries result that we can return, just set the paging and we're good to go.
Set paging, count and unwrap the entries.
GF_Query does not subtract the offset, we have to subtract it ourselves.
Just one more filter, for compatibility's sake!
Definition at line 69 of file _mocks.php.
References $args, $criteria, $entries, GV\$form, $form_id, GF_Form\by_id(), View\by_id(), GVCommon\calculate_get_entries_criteria(), Plugin\FEATURE_GFQUERY, Utils\get(), and gravityview().
Referenced by GravityView_frontend\get_search_criteria().
GravityView_View_Data_add_view()
GV\Mocks\GravityView_View_Data_add_view ($view_id, $atts, $_this)
This file contains mock code for deprecated functions.
See also
::add_view
Handle array of IDs.
View has been set already.
Doesn't have a connected form.
Update the settings
Definition at line 15 of file _mocks.php.
References $view_id, and View\by_id().
Referenced by GravityView_View_Data\add_view().