GravityView: GV Namespace Reference
GV Namespace Reference
Namespaces
Mocks
REST
Shortcodes
Widgets
Wrappers
Data Structures
class Addon_Settings
If this file is called directly, abort.
class Admin_Request
If this file is called directly, abort.
class Collection
If this file is called directly, abort.
class Context
If this file is called directly, abort.
class Core
If this file is called directly, abort.
class EDD_SL_Plugin_Updater
Allows plugins to use their own update API.
class Edit_Entry_Renderer
If this file is called directly, abort.
class Entry
If this file is called directly, abort.
class Entry_Collection
If this file is called directly, abort.
class Entry_Filter
If this file is called directly, abort.
class Entry_Legacy_Template
If this file is called directly, abort.
class Entry_List_Template
If this file is called directly, abort.
class Entry_Offset
If this file is called directly, abort.
class Entry_Renderer
If this file is called directly, abort.
class Entry_Sort
If this file is called directly, abort.
class Entry_Table_Template
If this file is called directly, abort.
class Entry_Template
If this file is called directly, abort.
class Extension
If this file is called directly, abort.
class Field
If this file is called directly, abort.
class Field_Collection
If this file is called directly, abort.
class Field_CSV_Template
If this file is called directly, abort.
class Field_HTML_Template
If this file is called directly, abort.
class Field_Renderer
If this file is called directly, abort.
class Field_Template
If this file is called directly, abort.
class Form
If this file is called directly, abort.
class Form_Collection
If this file is called directly, abort.
class Frontend_Request
If this file is called directly, abort.
class GF_Entry
If this file is called directly, abort.
class GF_Entry_Filter
If this file is called directly, abort.
class GF_Field
If this file is called directly, abort.
class GF_Form
If this file is called directly, abort.
class Internal_Field
If this file is called directly, abort.
class Internal_Source
If this file is called directly, abort.
class Join
If this file is called directly, abort.
class Legacy_Override_Template
If this file is called directly, abort.
class License_Handler
If this file is called directly, abort.
class Logger
The abstract class.
class LogLevel
If this file is called directly, abort.
class Mock_Request
If this file is called directly, abort.
class Multi_Entry
If this file is called directly, abort.
class oEmbed
If this file is called directly, abort.
class Plugin
If this file is called directly, abort.
class Renderer
If this file is called directly, abort.
class Request
If this file is called directly, abort.
class Settings
If this file is called directly, abort.
class Shortcode
If this file is called directly, abort.
class Source
If this file is called directly, abort.
class Template
If this file is called directly, abort.
class Template_Context
If this file is called directly, abort.
class Utils
If this file is called directly, abort.
class View
If this file is called directly, abort.
class View_Collection
If this file is called directly, abort.
class View_Legacy_Template
If this file is called directly, abort.
class View_List_Template
If this file is called directly, abort.
class View_Renderer
If this file is called directly, abort.
class View_Settings
If this file is called directly, abort.
class View_Table_Template
If this file is called directly, abort.
class View_Template
If this file is called directly, abort.
class Widget
If this file is called directly, abort.
class Widget_Collection
If this file is called directly, abort.
class WP_Action_Logger
If this file is called directly, abort.
Functions
all ()
Get all the settings.
app_settings_fields ()
Specify the settings fields to be rendered on the plugin settings page.
app_settings_icon ()
Prevent displaying of any icon.
app_settings_tab ()
app_settings_title ()
The Settings title.
as_html ($field, $echo=true)
create_app_menu ()
Add Settings link to GravityView menu.
defaults ()
Default settings.
get ($key, $default=null)
Retrieve a setting.
get_app_setting ($setting_name)
Retrieve a setting.
get_app_settings ()
Get all settings.
get_default_settings ()
Default settings.
get_license_handler ()
Allow public access to the GV class.
get_posted_settings ()
When the settings are saved, make sure the license key matches the previously activated key.
get_required_indicator ($field)
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
static getSetting ($key)
Get the setting for GravityView by name.
has_site_settings ()
Does the current site have its own settings?
is_save_postback ()
Check whether GravityView is being saved.
license_key_notice ()
Display a notice if the plugin is inactive.
maybe_save_app_settings ()
Check for the gravityview_edit_settings capability before saving plugin settings.
scripts ()
Add tooltip script to app settings page.
set ($settings, $value=null)
Sets a subset of settings.
settings_edd_license ($field, $echo=true)
Register the settings field for the EDD License field type.
settings_html ($field, $echo=true)
Allow pure HTML settings row.
settings_submit ($field, $echo=true)
single_setting_label ($field)
The same as the parent, except added support for field descriptions.
single_setting_row ($field)
Keep GravityView styling for `$field['description']`, even though Gravity Forms added support for it.
single_setting_row_html ($field)
No needed for pure HTML settings row.
styles ()
Register styles in the app admin page.
update ($settings)
Updates settings.
update_app_settings ($settings)
Updates app settings with the provided settings.
Variables
if(gravityview() ->plugin->is_GF_25()) $form = ob_get_clean()
$i = 0
$reasons = $this->get_uninstall_reasons()
padding bottom
scale description p description
</style > if(gravityview() ->plugin->is_GF_25()) else
padding top
scale description ul
gv form field wrapper
Function Documentation
all()
GV\all ()
Get all the settings.
Returns
array The settings.
Definition at line 631 of file class-gv-settings-addon.php.
References defaults(), and has_site_settings().
Referenced by View_Collection\all(), Field_Collection\all(), Entry_Collection\all(), Widget_Collection\by_id(), Widget_Collection\by_position(), Field_Collection\by_position(), Field_Collection\by_visible(), Widget_Collection\from_configuration(), Field_Collection\from_configuration(), Widget_Collection\get(), Form_Collection\get(), View_Collection\get(), Field_Collection\get(), Entry_Collection\get(), get(), get_app_settings(), GravityView_Widget_Search\get_view_searchable_fields(), GravityView_Welcome\getting_started_screen(), Entry_Collection\pluck(), and set().
app_settings_fields()
GV\app_settings_fields ()
Specify the settings fields to be rendered on the plugin settings page.
Returns
array
Since
1.15 Added Support Port support
2.0 Added REST API
Runs Filter:
gravityview_settings_fields Filter the settings fields.
Parameters
array $fields The fields to filter.
Runs Filter:
gravityview/settings/fields Filter the settings fields.
Parameters
array $fields The fields to filter.
Redux backward compatibility
Since
1.7.4
Runs Filter:
gravityview/settings/extension/sections Modify the GravityView settings page Extensions can tap in here to insert their own section and settings. $sections[] = array('title' => __('GravityView My Extension Settings', 'gravityview'), 'fields' => $settings,);
Parameters
array $extension_settings Empty array, ready for extension settings!
Definition at line 965 of file class-gv-settings-addon.php.
References $field, defaults(), get(), gravityview(), GRAVITYVIEW_FILE, and GVCommon\has_cap().
app_settings_icon()
GV\app_settings_icon ()
Prevent displaying of any icon.
Returns
string
Definition at line 553 of file class-gv-settings-addon.php.
app_settings_tab()
GV\app_settings_tab ()
Definition at line 529 of file class-gv-settings-addon.php.
app_settings_title()
GV\app_settings_title ()
The Settings title.
Returns
string
Definition at line 543 of file class-gv-settings-addon.php.
as_html()
GV\as_html ($field, $echo = true)
Definition at line 695 of file class-gv-settings-addon.php.
References $attributes, $field, $name, $value, and get().
Referenced by Addon_Settings\settings_save(), and settings_submit().
create_app_menu()
GV\create_app_menu ()
Add Settings link to GravityView menu.
Returns
void
Override whether to show the Settings menu on a per-blog basis.
Since
1.7.6
Parameters
bool $hide_if_network_activated Default: true
Definition at line 930 of file class-gv-settings-addon.php.
References has_site_settings().
defaults()
GV\defaults () private
Default settings.
Returns
array The defaults.
Runs Filter:
gravityview/settings/default Filter default global settings.
Parameters
[in,out] array The defaults.
Definition at line 663 of file class-gv-settings-addon.php.
Referenced by all(), app_settings_fields(), View_Settings\as_atts(), GravityView_View_Data\get_default_args(), get_default_settings(), get_gravityview(), GVCommon\get_template_settings(), and View_Settings\with_defaults().
get()
GV\get ($key, $default = null)
Retrieve a setting.
Parameters
string $key The setting key.
string $default A default if not found.
Returns
mixed The setting value.
Backward compatibility with Redux
Definition at line 579 of file class-gv-settings-addon.php.
References all().
Referenced by Mock_Request\__call(), GravityView_Field_Consent\__construct(), GravityView_Admin_View_Item\__construct(), GravityView_Field\__construct(), Utils\_GET(), Addon_Settings\_load_license_handler(), Utils\_POST(), Utils\_REQUEST(), Utils\_SERVER(), View_Table_Template\add_columns_sort_links(), GravityView_Field_List\add_form_fields(), GravityView_Edit_Entry_Render\after_update(), GravityView_Entry_Approval\after_update_entry_update_approved_meta(), app_settings_fields(), as_html(), Core\bootstrap(), GVCommon\calculate_get_entries_criteria(), GravityView_Entry_Approval_Status\choice_pluck(), GravityView_Edit_Entry_Render\custom_validation(), GravityView_Duplicate_Entry\duplicate_entry(), GravityView_API\entry_create_custom_slug(), GravityView_Field_Post_Image\explode_value(), GravityView_Widget_Search\filter_entries(), GravityView_Field_Unsubscribe\filter_gravityview_entry_default_field(), GravityView_Plugin_Hooks_Gravity_Forms_Survey\fix_survey_field_value(), Widget\from_configuration(), Entry\from_field(), View\from_post(), Template_Context\from_template(), Utils\get(), Settings\get(), GravityView_Admin_Views\get_available_fields(), Entry_Template\get_back_label(), GravityView_Field_Payment_Amount\get_content(), GravityView_Field_Date_Created\get_content(), GravityView_Field_Date_Updated\get_content(), GravityView_Widget_Search\get_datepicker_format(), GravityView_Admin_Installer\get_download_display_details(), View\get_entries(), GravityView_API\get_entry_slug(), GravityView_Widget_Search\get_field_label(), GVCommon\get_form_fields(), GravityView_Admin_ApproveEntries\get_form_id(), GV_License_Handler\get_instance(), GravityView_Admin_View_Item\get_item_info(), GVCommon\get_link_html(), GravityView_Edit_Entry_Locking\get_lock_meta(), GravityView_GFFormsModel\get_post_field_images(), get_posted_settings(), GravityView_Migrate\get_redux_license_status(), GravityView_Migrate\get_redux_settings(), GravityView_frontend\get_search_criteria(), GravityView_Widget_Search\get_search_filter_details(), GravityView_Widget_Search\get_search_input_label(), GravityView_Field_Sequence\get_sequence(), Widget\get_setting(), License_Handler\get_site_data(), GVCommon\get_sortable_fields_array(), GravityView_Edit_Entry_Locking\get_string(), GravityView_FieldType\get_tooltip(), Internal_Field\get_value(), GravityView_Shortcode\get_view_detail(), GravityView_Admin_View_Item\getOutput(), GravityView_Edit_Entry_Render\gform_pre_validation(), gravityview(), gravityview_register_placeholder_templates(), Core\init(), Extension\is_compatible(), License_Handler\license_call(), License_Handler\license_details(), GravityView_Default_Template_Table\maybe_modify_button_label(), GravityView_Duplicate_Entry\maybe_not_visible(), GravityView_Edit_Entry\maybe_not_visible(), GravityView_Delete_Entry\maybe_not_visible(), GravityView_Field_Entry_Approval\maybe_prevent_field_render(), Renderer\maybe_print_reserved_slugs_notice(), GravityView_Field_Unsubscribe\maybe_unsubscribe(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), GravityView_Theme_Hooks_SiteOrigin\merge_content_meta_keys(), GravityView_Field_Unsubscribe\modify_entry_value_unsubscribe(), GravityView_Field_Workflow_Current_Status_Timestamp\modify_entry_value_workflow_current_status_timestamp(), GravityView_Field_Workflow_Final_Status\modify_search_filters(), GravityView_Field_Entry_Approval\modify_search_parameters(), Entry_Collection\pluck(), GravityView_Admin_Installer\render_download(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Custom_Content\render_frontend(), GravityView_Admin_Installer\render_section(), GravityView_Merge_Tags\replace_entry_link(), GravityView_Field_Payment_Amount\replace_merge_tag(), GravityView_Edit_Entry_Render\save_field_value(), GravityView_Field_Address\search_field_filter(), Extension\settings(), settings_edd_license(), Addon_Settings\settings_save(), GravityView_Field_Custom\show_field_in_edit_entry(), GravityView_Widget_Search\sieve_filter_choices(), single_setting_label(), single_setting_row(), License_Handler\strings(), Entry_List_Template\the_field(), View_List_Template\the_field(), GravityView_Edit_Entry_Render\unselect_default_values(), and GravityView_Edit_Entry_User_Registration\update_user().
get_app_setting()
GV\get_app_setting ($setting_name)
Retrieve a setting.
Parameters
string $setting_name The setting key.
Returns
mixed The setting or null
Definition at line 566 of file class-gv-settings-addon.php.
get_app_settings()
GV\get_app_settings ()
Get all settings.
Returns
array The settings.
Definition at line 621 of file class-gv-settings-addon.php.
References all().
get_default_settings()
GV\get_default_settings ()
Default settings.
Returns
array The defaults.
Definition at line 653 of file class-gv-settings-addon.php.
References defaults().
get_license_handler()
GV\get_license_handler ()
Allow public access to the GV class.
Since
1.7.4
Returns
Definition at line 841 of file class-gv-settings-addon.php.
Referenced by license_key_notice(), and settings_edd_license().
get_posted_settings()
GV\get_posted_settings ()
When the settings are saved, make sure the license key matches the previously activated key.
Returns
array settings from parent::get_posted_settings(), with license_key_response and license_key_status potentially unset
Definition at line 1389 of file class-gv-settings-addon.php.
References get().
Referenced by license_key_notice().
get_required_indicator()
GV\get_required_indicator ($field)
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
Parameters
$field - The field meta.
Returns
string - Returns markup of the required indicator symbol
Definition at line 955 of file class-gv-settings-addon.php.
getSetting()
static GV\getSetting ($key) static
Get the setting for GravityView by name.
Parameters
string $key Option key to fetch
Returns
mixed
Definition at line 607 of file class-gv-settings-addon.php.
References gravityview().
has_site_settings()
GV\has_site_settings () private
Does the current site have its own settings?
If not multisite, returns true.
If multisite and the plugin is network activated, returns true; we need to register the submenu page for the Network Admin settings to work.
If multisite and not network admin, return false.
Since
2.8.2
Returns
bool
Definition at line 920 of file class-gv-settings-addon.php.
References gravityview().
Referenced by all(), and create_app_menu().
is_save_postback()
GV\is_save_postback ()
Check whether GravityView is being saved.
The generic is_save_postback() is true for all addons
Since
2.0.8
Returns
bool
Definition at line 745 of file class-gv-settings-addon.php.
Referenced by license_key_notice(), and maybe_save_app_settings().
license_key_notice()
GV\license_key_notice ()
Display a notice if the plugin is inactive.
Returns
void
I wanted to remove the period from after the buttons in the string, but didn't want to mess up the translation strings for the translators.
Since
1.17
PhpMissingBreakStatementInspection
Definition at line 755 of file class-gv-settings-addon.php.
References $settings, $title, $url, GravityView_Admin_Notices\add_notice(), Utils\get(), get_license_handler(), get_posted_settings(), gravityview(), and is_save_postback().
maybe_save_app_settings()
GV\maybe_save_app_settings ()
Check for the gravityview_edit_settings capability before saving plugin settings.
Gravity Forms says you're able to edit if you're able to view settings. GravityView allows two different permissions.
Since
1.15
Returns
void
Definition at line 1371 of file class-gv-settings-addon.php.
References GVCommon\has_cap(), and is_save_postback().
scripts()
GV\scripts ()
Add tooltip script to app settings page.
Not enqueued by Gravity Forms for some reason.
Since
1.21.5
See also
GFAddOn::scripts()
Returns
array Array of scripts
Definition at line 855 of file class-gv-settings-addon.php.
Referenced by GravityView_Welcome\getting_started_screen().
set()
GV\set ($settings, $value = null)
Sets a subset of settings.
Parameters
array|string An array of settings to update, or string (key) and $value to update one setting.
mixed $value A value if $settings is string (key). Default: null.
Definition at line 1234 of file class-gv-settings-addon.php.
References $settings, and all().
Referenced by GravityView_Edit_Entry_Locking\update_lock_meta(), and GravityView_Edit_Entry_Locking\update_lock_request_meta().
settings_edd_license()
GV\settings_edd_license ($field, $echo = true)
Register the settings field for the EDD License field type.
Parameters
array $field
bool $echo Whether to echo the
Returns
string
Definition at line 1264 of file class-gv-settings-addon.php.
References $field, get(), get_license_handler(), and License_Handler\settings_edd_license_activation().
settings_html()
GV\settings_html ($field, $echo = true) protected
Allow pure HTML settings row.
Since
2.0.6
Parameters
array $field
bool $echo Whether to echo the
Returns
string
Definition at line 1295 of file class-gv-settings-addon.php.
References $field, and Utils\get().
settings_submit()
GV\settings_submit ($field, $echo = true)
Definition at line 729 of file class-gv-settings-addon.php.
References $field, as_html(), and gravityview().
single_setting_label()
GV\single_setting_label ($field)
The same as the parent, except added support for field descriptions.
Parameters
$field array
Definition at line 1356 of file class-gv-settings-addon.php.
References $description, $field, and get().
single_setting_row()
GV\single_setting_row ($field)
Keep GravityView styling for `$field['description']`, even though Gravity Forms added support for it.
Converts `$field['description']to$field['gv_description'] Converts$field['subtitle']to$field['description']`
Since
1.21.5.2
See also
http://share.gravityview.co/P28uGp/2OIRKxog for image that shows subtitle vs description
single_setting_label Converts gv_description back to description
Parameters
array $field
Returns
void
Definition at line 1343 of file class-gv-settings-addon.php.
References $field, and get().
single_setting_row_html()
GV\single_setting_row_html ($field)
No needed for pure HTML settings row.
Since
2.0.6
Parameters
array $field
Returns
void
Definition at line 1315 of file class-gv-settings-addon.php.
References $field.
styles()
GV\styles ()
Register styles in the app admin page.
Returns
array
Definition at line 876 of file class-gv-settings-addon.php.
References gravityview(), and GRAVITYVIEW_FILE.
update()
GV\update ($settings)
Updates settings.
Parameters
array $settings The settings array.
Returns
boolean False if value was not updated and true if value was updated.
Definition at line 1251 of file class-gv-settings-addon.php.
References $settings.
Referenced by Settings\__construct(), GravityView_Field_Is_Starred\print_script(), and update_app_settings().
update_app_settings()
GV\update_app_settings ($settings)
Updates app settings with the provided settings.
Same as the GFAddon, except it returns the value from update_option()
Parameters
array $settings - App settings to be saved
Returns
boolean False if value was not updated and true if value was updated.
Definition at line 1223 of file class-gv-settings-addon.php.
References $settings, and update().
Variable Documentation
$form
return $form = ob_get_clean()
Definition at line 524 of file class-gv-settings-addon.php.
Referenced by GravityView_Field_List\_filter_field_label(), GravityView_Field\_filter_gform_custom_merge_tags(), GravityView_Field\_filter_gform_replace_merge_tags(), GravityView_Field_Gravatar\_get_email_field_choices(), GravityView_Widget_Gravity_Forms\_get_form_choices(), GravityView_frontend\_get_single_entry_title(), GravityView_Field_Time\_get_time_format_for_field(), GravityView_frontend\_override_sorting_id_by_field_type(), GravityView_Entry_Approval\_send_notifications(), Form_Collection\add(), GravityView_frontend\add_columns_sort_links(), GravityView_Admin_Views\add_custom_column_content(), GravityView_Plugin_Hooks_Gravity_Forms_Quiz\add_form_fields(), GravityView_Field_List\add_form_fields(), GravityView_Admin_Views\add_view_dropdown(), GravityView_Plugin_Hooks_Gravity_Forms_Signature\after_edit_entry(), GravityView_Entry_Approval\after_submission(), GravityView_Entry_Approval\after_update_entry_update_approved_meta(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), GravityView_Entry_Approval\autounapprove(), GF_Form\by_id(), GF_Field\by_id(), gventry\callback(), GravityView_Plugin_Hooks_Gravity_Flow\clear_cache_after_workflow(), GravityView_Field_Product\clear_product_info_cache(), GravityView_Ajax\create_preset_form(), GravityView_Field_Is_Approved\custom_merge_tags(), GravityView_Duplicate_Entry\duplicate_entry(), GravityView_Plugin_Hooks_Gravity_Forms_Coupon\edit_entry_field_value(), GravityView_Field_Total\edit_entry_recalculate_totals(), GravityView_Cache\entry_added(), GravityView_Cache\entry_created(), GravityView_Cache\entry_updated(), GravityView_Field_Post_Image\explode_value(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_API\field_label(), GravityView_Field_Password\field_label(), GravityView_Field_Unsubscribe\filter_gravityview_entry_default_field(), GravityView_Admin_ApproveEntries\filter_links_entry_list(), GravityView_HTML_Elements\form_dropdown(), GF_Field\from_configuration(), GF_Form\from_form(), Form_Collection\get(), GravityView_Admin_ApproveEntries\get_approved_column(), GravityView_Entry_Approval\get_approved_column_input_label(), GravityView_Admin_Views\get_available_fields(), GravityView_Field_Address\get_choices_state(), GravityView_Admin_Views\get_connected_form_links(), GF_Form\get_entries(), GravityView_Admin_Views\get_entry_default_fields(), GravityView_Edit_Entry_User_Registration\get_feed_configuration(), GF_Form\get_field(), GVCommon\get_field(), View_Table_Template\get_field_column_label(), GravityView_Field_FileUpload\get_field_input(), GVCommon\get_field_label(), GVCommon\get_field_type(), GravityView_Admin\get_floaty(), GVCommon\get_form_fields(), GVCommon\get_form_from_entry_id(), View\get_joined_forms(), GravityView_GFFormsModel\get_post_field_images(), GravityView_GFFormsModel\get_post_fields(), GravityView_frontend\get_search_criteria_paging(), GravityView_Migrate\get_search_fields(), GravityView_Widget_Search\get_search_filter_details(), GravityView_Widget_Search\get_searchable_fields(), GravityView_Ajax\get_sortable_fields(), GravityView_Admin_View_Item\getOutput(), GV\Mocks\GravityView_API_field_label(), GV\Mocks\GravityView_API_field_value(), gravityview_field_output(), GV\Mocks\GravityView_frontend_get_view_entries(), gravityview_get_field(), gravityview_get_field_label(), gravityview_get_field_type(), gravityview_get_form_fields(), gravityview_is_single_entry(), gv_class(), GVCommon\has_product_field(), GravityView_Field\is_choice_value_enabled(), GVCommon\is_field_numeric(), GravityView_frontend\is_field_sortable(), GravityView_GFFormsModel\is_value_match(), Renderer\maybe_print_entry_approval_notice(), GravityView_Plugin_Hooks_Gravity_Forms_Partial_Entries\maybe_save_partial_entry(), GravityView_Field_Notes\maybe_send_entry_notes(), View\offsetGet(), GravityView_Ajax\pre_get_form_fields(), GravityView_Widget_Search\prepare_field_filter(), GravityView_Admin_Views\render_active_areas(), GravityView_Admin_Views\render_additional_fields(), GravityView_Admin_Views\render_available_fields(), GravityView_Render_Settings\render_field_options(), oEmbed\render_frontend(), GravityView_Admin_Metaboxes\render_merge_tags_scripts(), GravityView_Merge_Tags\replace_get_variables(), GravityView_Merge_Tags\replace_gv_merge_tags(), GravityView_API\replace_variables(), GravityView_Merge_Tags\replace_variables(), GravityView_Field_Address\search_field_filter(), GravityView_Field_Post_Category\set_post_categories(), GravityView_Field_Custom\show_field_in_edit_entry(), Entry_Table_Template\the_entry(), Entry_List_Template\the_field(), View_List_Template\the_field(), View_Table_Template\the_field(), GravityView_Entry_Approval\update_approved_meta(), GravityView_Edit_Entry_User_Registration\update_user(), and GravityView_Recent_Entries_Widget\widget().
$i
$i = 0
Definition at line 489 of file class-gv-settings-addon.php.
Referenced by View_Table_Template\add_columns_sort_links(), Entry_Collection\fetch(), GravityView_Edit_Entry_Render\filter_conditional_logic(), GravityView_Admin_ApproveEntries\get_bulk_actions(), Request\is_entry(), and GravityView_Field_Custom\show_field_in_edit_entry().
$reasons
$reasons = $this->get_uninstall_reasons()
Definition at line 475 of file class-gv-settings-addon.php.
Referenced by Addon_Settings\get_uninstall_reasons().
bottom
padding bottom
Definition at line 400 of file class-gv-settings-addon.php.
description
scale description p description
Initial value:
{
                margin-top: 0 !important
Definition at line 403 of file class-gv-settings-addon.php.
Referenced by GravityView_Field_Unsubscribe\__construct(), GravityView_Field_Created_By\__construct(), GravityView_Field_Gravatar\__construct(), GravityView_Field_ID\__construct(), GravityView_Field_Source_URL\__construct(), GravityView_Field_IP\__construct(), GravityView_Field_Entry_Approval\__construct(), GravityView_Field_Payment_Date\__construct(), GravityView_Field_Payment_Status\__construct(), GravityView_Field_Is_Starred\__construct(), GravityView_Field_Date_Created\__construct(), GravityView_Field_Date_Updated\__construct(), GravityView_Field_Other_Entries\__construct(), GravityView_Field_Payment_Method\__construct(), GravityView_Field_Entry_Link\__construct(), GravityView_Field_Custom\__construct(), GravityView_Field_Is_Fulfilled\__construct(), GravityView_Field_Transaction_Type\__construct(), GravityView_Field_Sequence\__construct(), GravityView_Field_Is_Approved\__construct(), GravityView_Field_Gravatar\add_default_field(), GravityView_Field_Entry_Link\add_default_field(), GravityView_Field_Is_Starred\add_default_field(), GravityView_Field_Custom\add_default_field(), GravityView_Field_Sequence\add_default_field(), GravityView_Field_Is_Approved\add_default_field(), GravityView_Field\as_array(), GravityView_Field_Unsubscribe\filter_gravityview_entry_default_field(), and GravityView_Field_Entry_Approval\filter_gravityview_entry_default_field().
else
</style> if (gravityview() ->plugin->is_GF_25()) else
Initial value:
{
            echo '<div class="gv-uninstall-form-wrapper" style="font-size: 110%; padding: 15px 0;">'
Definition at line 425 of file class-gv-settings-addon.php.
top
padding top
Definition at line 405 of file class-gv-settings-addon.php.
Referenced by GravityView_Admin_Bar\add_floaty_icon(), and GravityView_Lightbox_Provider_FancyBox\print_scripts().
ul
scale description ul
Initial value:
{
                margin-bottom: 0
Definition at line 398 of file class-gv-settings-addon.php.
Referenced by GravityView_Welcome\getting_started_screen(), and GravityView_FieldType_checkboxes\render_input().
wrapper
gv form field wrapper
Initial value:
{
                margin-top: 30px
Definition at line 408 of file class-gv-settings-addon.php.