GravityView: nav-menu-template.php File Reference
nav-menu-template.php File Reference
Data Structures
class Walker_Nav_Menu
Create HTML list of nav menu items.
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_nav_menu_item_id_use_once ($id, $item)
Prevents a menu item ID from being used more than once.
_wp_menu_item_classes_by_context (&$menu_items)
Add the class property classes for the current context, if applicable.
walk_nav_menu_tree ($items, $depth, $r)
Retrieve the HTML list content for nav menu items.
wp_nav_menu ($args=array())
Displays a navigation menu.
Function Documentation
_nav_menu_item_id_use_once ($id, $item)
Prevents a menu item ID from being used more than once.
Since
3.0.1 private
array $used_ids
Parameters
string $id
object $item
Returns
string
Definition at line 720 of file nav-menu-template.php.
References $id.
_wp_menu_item_classes_by_context (& $menu_items)
Add the class property classes for the current context, if applicable.
private
Since
3.0.0
WP_Query $wp_query WP_Rewrite $wp_rewrite
Parameters
array $menu_items The current menu item objects to which to add the class property information.
Definition at line 470 of file nav-menu-template.php.
References $_SERVER, $menu_items, $wp_rewrite, _get_term_hierarchy(), elseif, get_object_taxonomies(), get_option(), get_post_meta(), home_url(), if, is_front_page(), is_post_type_archive(), is_post_type_hierarchical(), is_taxonomy_hierarchical(), set_url_scheme(), untrailingslashit(), and wp_get_object_terms().
Referenced by wp_nav_menu().
walk_nav_menu_tree ($items, $depth, $r)
Retrieve the HTML list content for nav menu items.
Walker_Nav_Menu to create HTML list content.
Since
3.0.0
Parameters
array $items
int $depth
object $r
Returns
string
Definition at line 702 of file nav-menu-template.php.
Referenced by _wp_ajax_menu_quick_search(), wp_ajax_add_menu_item(), wp_get_nav_menu_to_edit(), wp_nav_menu(), wp_nav_menu_item_post_type_meta_box(), and wp_nav_menu_item_taxonomy_meta_box().
wp_nav_menu ($args = array())
Displays a navigation menu.
Since
3.0.0
array $menu_id_slugs
Parameters
array $args { Optional. Array of nav menu arguments.
string $menu Desired menu. Accepts (matching in order) id, slug, name. Default empty. string $menu_class CSS class to use for the ul element which forms the menu. Default 'menu'. string $menu_id The ID that is applied to the ul element which forms the menu. Default is the menu slug, incremented. string $container Whether to wrap the ul, and what to wrap it with. Default 'div'. string $container_class Class that is applied to the container. Default 'menu-{menu slug}-container'. string $container_id The ID that is applied to the container. Default empty. callable|bool $fallback_cb If the menu doesn't exists, a callback function will fire. Default is 'wp_page_menu'. Set to false for no fallback. string $before Text before the link text. Default empty. string $after Text after the link text. Default empty. string $link_before Text before the link. Default empty. string $link_after Text after the link. Default empty. bool $echo Whether to echo the menu or return it. Default true. int $depth How many levels of the hierarchy are to be included. 0 means all. Default 0. object $walker Instance of a custom walker class. Default empty. string $theme_location Theme location to be used. Must be registered with register_nav_menu() in order to be selectable by the user. string $items_wrap How the list items should be wrapped. Default is a ul with an id and class. Uses printf() format with numbered placeholders. }
Returns
object|false|void Menu output if $echo is false, false if there are no items or no menu was found.
Filter the arguments used to display a navigation menu.
Since
3.0.0
See also
wp_nav_menu()
Parameters
array $args Array of wp_nav_menu() arguments.
Filter whether to short-circuit the wp_nav_menu() output.
Returning a non-null value to the filter will short-circuit wp_nav_menu(), echoing that value if $args->echo is true, returning that value otherwise.
Since
3.9.0
See also
wp_nav_menu()
Parameters
string | null $output Nav menu output to short-circuit with. Default null.
object $args An object containing wp_nav_menu() arguments.
Filter the list of HTML tags that are valid for use as menu containers.
Since
3.0.0
Parameters
array $tags The acceptable HTML tags for use as menu containers. Default is array containing 'div' and 'nav'.
Filter the sorted list of menu item objects before generating the menu's HTML.
Since
3.1.0
Parameters
array $sorted_menu_items The menu items, sorted by each menu item's menu order.
object $args An object containing wp_nav_menu() arguments.
Filter the HTML list content for navigation menus.
Since
3.0.0
See also
wp_nav_menu()
Parameters
string $items The HTML list content for the menu items.
object $args An object containing wp_nav_menu() arguments.
Filter the HTML list content for a specific navigation menu.
Since
3.0.0
See also
wp_nav_menu()
Parameters
string $items The HTML list content for the menu items.
object $args An object containing wp_nav_menu() arguments.
Filter the HTML content for navigation menus.
Since
3.0.0
See also
wp_nav_menu()
Parameters
string $nav_menu The HTML content for the navigation menu.
object $args An object containing wp_nav_menu() arguments.
Definition at line 252 of file nav-menu-template.php.
References $class, $id, $locations, $menu, $menu_items, _wp_menu_item_classes_by_context(), apply_filters(), esc_attr(), get_nav_menu_locations(), is_wp_error(), null, object, walk_nav_menu_tree(), wp_get_nav_menu_items(), wp_get_nav_menu_object(), wp_get_nav_menus(), and wp_parse_args().
Referenced by WP_Customize_Nav_Menus\render_menu(), and WP_Nav_Menu_Widget\widget().