GravityView: nav-menus.php File Reference
nav-menus.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
if(is_nav_menu($nav_menu_selected_id)) wp_nav_menu_max_depth ($classes)
int $_wp_nav_menu_max_depth
Variables
if(!$nav_menu_selected_title &&is_nav_menu($nav_menu_selected_id)) foreach((array) $nav_menus as $key=> $_nav_menu) if(current_theme_supports('menus')) global $_wp_nav_menu_max_depth = 0
$action = isset($_REQUEST['action']) ? $_REQUEST['action'] : 'edit'
$add_new_screen = (isset($_GET['menu']) && 0 == $_GET['menu']) ? true : false
$editing_menus = '<p>' . __('Each custom menu may contain a mix of links to pages, categories, custom URLs or other content types. Menu links are added by selecting items from the expanding boxes in the left-hand column below.') . '</p>'
$locations = get_registered_nav_menus()
$locations_overview = '<ul><li>' . __('To assign menus to one or more theme locations, <strong>select a menu from each location&#8217;s drop down.</strong> When you&#8217;re finished, <strong>click Save Changes</strong>') . '</li>'
$locations_screen = (isset($_GET['action']) && 'locations' == $_GET['action']) ? true : false
$menu_count = count($nav_menus)
$menu_locations = get_nav_menu_locations()
$menu_management = '<p>' . __('The menu management box at the top of the screen is used to control which menu is opened in the editor below.') . '</p>'
$messages = array()
$nav_menu_selected_id = isset($_REQUEST['menu']) ? (int) $_REQUEST['menu'] : 0
$nav_menu_selected_title = ''
switch($action) $nav_menus = wp_get_nav_menus()
$nav_menus_l10n
$num_locations = count(array_keys($locations))
$one_theme_location_no_menus = (1 == count(get_registered_nav_menus()) && ! $add_new_screen && empty($nav_menus) && ! empty($page_count->publish)) ? true : false
$overview = '<p>' . sprintf(__('Menus can be displayed in locations defined by your theme, even used in sidebars by adding a &#8220;Custom Menu&#8221; widget on the <a href="%1$s">Widgets</a> screen. If your theme does not support the custom menus feature (the default themes, %2$s and %3$s, do), you can learn about adding this support by following the Documentation link to the side.'), admin_url('widgets.php'), 'Twenty Fifteen', 'Twenty Fourteen') . '</p>'
$page_count = wp_count_posts('page')
$starter_copy = ($one_theme_location_no_menus) ? __('Edit your default menu by adding or removing items. Drag each item into the order you prefer. Click Create Menu to save your changes.') : __('Drag each item into the order you prefer. Click the arrow on the right of the item to reveal additional configuration options.')
else __pad1__
else __pad2__
else or< a href="%s"> create a new menu</a > action edit menu nav menus php nav menus php Select a menu to edit
if($locations_screen)(1==$num_locations) else
foreach($messages as $message) endforeach
endif {
if (isset($_GET['menu'])&& '0'==$_GET['menu'])
Function Documentation
if (is_nav_menu($nav_menu_selected_id)) wp_nav_menu_max_depth ($classes)
int $_wp_nav_menu_max_depth
Parameters
string $classes
Returns
string
Filter the number of locations listed per menu in the drop-down select.
Since
3.6.0
Parameters
int $locations Number of menu locations to list. Default 3.
Definition at line 500 of file nav-menus.php.
References $_wp_nav_menu_max_depth.
Variable Documentation
$_wp_nav_menu_max_depth = 0
Definition at line 473 of file nav-menus.php.
Referenced by Walker_Nav_Menu_Edit\start_el(), and wp_nav_menu_max_depth().
$action = isset($_REQUEST['action']) ? $_REQUEST['action'] : 'edit'
Definition at line 50 of file nav-menus.php.
$add_new_screen = (isset($_GET['menu']) && 0 == $_GET['menu']) ? true : false
Definition at line 398 of file nav-menus.php.
$editing_menus = '<p>' . __('Each custom menu may contain a mix of links to pages, categories, custom URLs or other content types. Menu links are added by selecting items from the expanding boxes in the left-hand column below.') . '</p>'
Definition at line 537 of file nav-menus.php.
$locations = get_registered_nav_menus()
Definition at line 45 of file nav-menus.php.
Referenced by _wp_check_split_nav_menu_terms(), WP_Customize_Nav_Menus\customize_register(), get_nav_menu_locations(), has_nav_menu(), register_nav_menus(), wp_delete_nav_menu(), wp_load_translations_early(), and wp_nav_menu().
$locations_overview = '<ul><li>' . __('To assign menus to one or more theme locations, <strong>select a menu from each location&#8217;s drop down.</strong> When you&#8217;re finished, <strong>click Save Changes</strong>') . '</li>'
Definition at line 551 of file nav-menus.php.
$locations_screen = (isset($_GET['action']) && 'locations' == $_GET['action']) ? true : false
Definition at line 400 of file nav-menus.php.
$menu_count = count($nav_menus)
Definition at line 395 of file nav-menus.php.
$menu_locations = get_nav_menu_locations()
Definition at line 46 of file nav-menus.php.
$menu_management = '<p>' . __('The menu management box at the top of the screen is used to control which menu is opened in the editor below.') . '</p>'
Definition at line 526 of file nav-menus.php.
$messages = array()
Definition at line 36 of file nav-menus.php.
$nav_menu_selected_id = isset($_REQUEST['menu']) ? (int) $_REQUEST['menu'] : 0
Definition at line 42 of file nav-menus.php.
Referenced by wp_nav_menu_disabled_check(), wp_nav_menu_item_link_meta_box(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_item_taxonomy_meta_box(), and wp_nav_menu_update_menu_items().
$nav_menu_selected_title = ''
Definition at line 39 of file nav-menus.php.
Referenced by wp_nav_menu_update_menu_items().
switch ($action) $nav_menus = wp_get_nav_menus()
Definition at line 394 of file nav-menus.php.
Referenced by export_wp().
$nav_menus_l10n
Initial value:
= array(
    'oneThemeLocationNoMenus' => $one_theme_location_no_menus,
    'moveUp'       => __( 'Move up one' ),
    'moveDown'     => __( 'Move down one' ),
    'moveToTop'    => __( 'Move to the top' ),
    'moveUnder'    => __( 'Move under %s' ),
    'moveOutFrom'  => __( 'Move out from under %s' ),
    'under'        => __( 'Under %s' ),
    'outFrom'      => __( 'Out from under %s' ),
    'menuFocus'    => __( '%1$s. Menu item %2$d of %3$d.' ),
    'subMenuFocus' => __( '%1$s. Sub item number %2$d under %3$s.' ),
)
Definition at line 409 of file nav-menus.php.
Referenced by WP_Customize_Nav_Menus\enqueue_scripts().
$num_locations = count(array_keys($locations))
Definition at line 47 of file nav-menus.php.
Referenced by WP_Customize_Nav_Menus\customize_register().
$one_theme_location_no_menus = (1 == count(get_registered_nav_menus()) && ! $add_new_screen && empty($nav_menus) && ! empty($page_count->publish)) ? true : false
Definition at line 407 of file nav-menus.php.
Referenced by wp_nav_menu_disabled_check().
$overview = '<p>' . sprintf(__('Menus can be displayed in locations defined by your theme, even used in sidebars by adding a &#8220;Custom Menu&#8221; widget on the <a href="%1$s">Widgets</a> screen. If your theme does not support the custom menus feature (the default themes, %2$s and %3$s, do), you can learn about adding this support by following the Documentation link to the side.'), admin_url('widgets.php'), 'Twenty Fifteen', 'Twenty Fourteen') . '</p>'
Definition at line 515 of file nav-menus.php.
$page_count = wp_count_posts('page')
Definition at line 406 of file nav-menus.php.
Referenced by GFFormDisplay\get_progress_bar().
$starter_copy = ($one_theme_location_no_menus) ? __('Edit your default menu by adding or removing items. Drag each item into the order you prefer. Click Create Menu to save your changes.') : __('Drag each item into the order you prefer. Click the arrow on the right of the item to reveal additional configuration options.')
Definition at line 759 of file nav-menus.php.
else __pad1__
Definition at line 550 of file nav-menus.php.
else __pad2__
Definition at line 666 of file nav-menus.php.
else or<a href="%s"> create a new menu</a> action edit menu nav menus php nav menus php Select a menu to edit
Definition at line 666 of file nav-menus.php.
else
Initial value:
{
            echo '<p>' .  sprintf( _n( 'Your theme supports %s menu. Select which menu appears in each location.', 'Your theme supports %s menus. Select which menu appears in each location.', $num_locations ), number_format_i18n( $num_locations ) ) . '</p>'
Definition at line 604 of file nav-menus.php.
endforeach
Definition at line 596 of file nav-menus.php.
endif {
Definition at line 560 of file nav-menus.php.
if(isset($menu_items)&&0==count($menu_items))
Definition at line 718 of file nav-menus.php.