GravityView: noop.php File Reference
noop.php File Reference
Functions
__ ()
_x ()
add_action ()
add_filter ()
admin_url ()
apply_filters ()
did_action ()
do_action_ref_array ()
esc_attr ()
get_bloginfo ()
get_file ($path)
get_option ()
home_url ()
includes_url ()
is_admin ()
is_lighttpd_before_150 ()
site_url ()
wp_guess_url ()
Variables
if(!function_exists('json_encode'))() endif
Function Documentation
__ ()
Definition at line 6 of file noop.php.
_x ()
Definition at line 11 of file noop.php.
add_action ()
Definition at line 41 of file noop.php.
Referenced by GravityView_Ajax\__construct(), GravityView_Change_Entry_Creator\__construct(), GravityView_Logging\__construct(), GravityView_GF_Entries_List\__construct(), GravityView_Post_Types\__construct(), GravityView_Migrate\__construct(), GFAutoUpgrade\__construct(), Twenty_Eleven_Ephemera_Widget\__construct(), GravityView_Admin_Add_Shortcode\__construct(), WP_Widget_Factory\__construct(), GravityView_Admin_Views\__construct(), GravityView_Widget_Search\__construct(), WP_Widget_Recent_Comments\__construct(), WP_Embed\__construct(), GravityView_Welcome\__construct(), WP_Scripts\__construct(), WP_Customize_Site_Icon_Control\__construct(), WP_Customize_Nav_Menus\__construct(), Custom_Background\__construct(), Custom_Image_Header\__construct(), GravityView_Extension\__construct(), WP_Site_Icon\__construct(), WP_Customize_Widgets\__construct(), GFAddOn\__construct(), WP_List_Table\__construct(), GravityView_View\__construct(), WP_Customize_Nav_Menu_Item_Setting\__construct(), WP_Customize_Manager\__construct(), _custom_header_background_just_in_time(), add_feed(), GravityView_Admin_Bar\add_hooks(), GravityView_Admin_ApproveEntries\add_hooks(), GravityView_Support_Port\add_hooks(), GravityView_Admin_Duplicate_View\add_hooks(), GravityView_Admin_Notices\add_hooks(), GravityView_Delete_Entry\add_hooks(), GravityView_Admin\add_hooks(), GV_License_Handler\add_hooks(), GravityView_Roles_Capabilities\add_hooks(), GravityView_Cache\add_hooks(), GravityView_Template\add_hooks(), GravityView_Theme_Hooks_WooThemes\add_hooks(), GravityView_Edit_Entry\add_hooks(), GravityView_Plugin\add_hooks(), add_menu_page(), WP_Admin_Bar\add_menus(), GFSettings\add_settings_page(), add_submenu_page(), add_thickbox(), WP_Customize_Setting\aggregate_multidimensional(), comments_template(), WP_Customize_Nav_Menus\customize_preview_enqueue_deps(), WP_Customize_Manager\customize_preview_init(), WP_Customize_Nav_Menus\customize_preview_init(), WP_Customize_Widgets\customize_preview_init(), _WP_Editors\editor_settings(), WP_Internal_Pointers\enqueue_scripts(), WP_UnitTestCase\expectDeprecated(), WP_Rewrite\flush_rules(), GFFormList\form_list_page(), GravityView_Plugin\frontend_actions(), GFFormDisplay\get_form(), GFAutoUpgrade\init(), Featured_Content\init(), Custom_Background\init(), Custom_Image_Header\init(), WP_Locale\init(), GFForms\init(), GFFeedAddOn\init_admin(), GFPaymentAddOn\init_admin(), GravityView_Settings\init_admin(), GFAddOn\init_admin(), GFFeedAddOn\init_ajax(), GFPaymentAddOn\init_ajax(), GFAddOn\init_ajax(), GFLocking\init_edit_lock(), GFAddOn\init_frontend(), GFLocking\init_list_page(), GFLocking\init_view_page(), GravityView_Recent_Entries_Widget\initialize(), GravityView_oEmbed\initialize(), GravityView_Admin_Metaboxes\initialize(), WP_Admin_Bar\initialize(), GravityView_frontend\initialize(), Plugin_Upgrader\install(), Theme_Upgrader\install(), GravityView_Edit_Entry_User_Registration\load(), GravityView_Edit_Entry_Render\load(), GravityView_Change_Entry_Creator\load(), GV_Unit_Tests_Bootstrap\load_rest_api(), login_header(), GFPaymentAddOn\pre_init(), WP_Theme_Install_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), WP_Customize_Setting\preview(), register_post_type(), rest_api_default_filters(), WP_Customize_Widgets\schedule_customize_register(), Featured_Content\setup(), WP_Ajax_UnitTestCase\setUp(), GFPaymentAddOn\setup_cron(), WP_Customize_Manager\setup_theme(), WP_Ajax_UnitTestCase\setUpBeforeClass(), GravityView_Ajax_Test\test_get_available_fields_html(), twentyeleven_theme_options_add_page(), twentyfifteen_switch_theme(), twentyfourteen_switch_theme(), twentythirteen_switch_theme(), uninstall_plugin(), wp_admin_bar_customize_menu(), wp_auth_check_load(), wp_enqueue_media(), wp_maybe_load_widgets(), wp_playlist_scripts(), wp_plugin_update_rows(), wp_print_media_templates(), wp_set_comment_status(), and wp_theme_update_rows().
add_filter ()
Definition at line 16 of file noop.php.
Referenced by GravityView_Logging\__construct(), GravityView_Search_WP_Widget\__construct(), GravityView_Field_Section\__construct(), GravityView_Field_Calculation\__construct(), GravityView_Widget_Poll\__construct(), GravityView_Admin_Views\__construct(), GravityView_Field_Date_Created\__construct(), GravityView_Widget_Search\__construct(), WP_Embed\__construct(), GravityView_Field_Payment_Amount\__construct(), WP_oEmbed\__construct(), GravityView_Field_Is_Fulfilled\__construct(), GravityView_Field_List\__construct(), GravityView_Field_Transaction_Type\__construct(), GravityView_Welcome\__construct(), WP_Comments_List_Table\__construct(), WP_Customize_Nav_Menus\__construct(), GravityView_Field_Time\__construct(), GravityView_Extension\__construct(), WP_Site_Icon\__construct(), WP_Customize_Widgets\__construct(), _WP_List_Table_Compat\__construct(), GravityView_Field\__construct(), WP_Customize_Setting\__construct(), WP_List_Table\__construct(), GravityView_View\__construct(), WP_Customize_Manager\__construct(), GravityView_Field_Time\_maybe_filter_gravity_forms_query(), _set_preview(), _show_post_preview(), _wp_post_thumbnail_class_filter_add(), GravityView_Entry_Notes\add_hooks(), GravityView_Merge_Tags\add_hooks(), GravityView_Admin_ApproveEntries\add_hooks(), GravityView_Admin_Duplicate_View\add_hooks(), GravityView_Delete_Entry\add_hooks(), GravityView_Admin\add_hooks(), GravityView_Plugin_Hooks_Yoast_SEO\add_hooks(), GravityView_Roles_Capabilities\add_hooks(), GravityView_Compatibility\add_hooks(), GravityView_Template\add_hooks(), GravityView_Edit_Entry\add_hooks(), GravityView_Plugin_and_Theme_Hooks\add_hooks(), GravityView_Edit_Entry\addon_specific_hooks(), Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), Language_Pack_Upgrader\bulk_upgrade(), WP_Customize_Widgets\capture_filter_pre_update_option(), Theme_Upgrader\check_parent_theme_filter(), WP_Customize_Manager\customize_preview_init(), WP_Customize_Nav_Menus\customize_preview_init(), WP_Customize_Widgets\customize_register(), WP_Customize_Nav_Menus\customize_register(), GFFormsModel\dbDelta(), WP_Media_List_Table\display_rows(), WP_Posts_List_Table\display_rows(), do_core_upgrade(), _WP_Editors\editor(), GravityView_Widget_Search\enqueue_datepicker(), export_wp(), GravityView_API\field_class(), GravityView_Field_Time\field_options(), GravityView_oEmbed\generate_entry_output(), GVCommon\get_entries(), WP_Importer\get_page(), WP_Site_Icon\get_post_metadata(), WP_Query\get_posts(), WP_Press_This\html(), GFAutoUpgrade\init(), GFFeedAddOn\init(), Featured_Content\init(), GFPaymentAddOn\init(), GFForms\init(), GFAddOn\init(), GFFeedAddOn\init_admin(), GFPaymentAddOn\init_admin(), GravityView_Settings\init_admin(), GFAddOn\init_admin(), GFLocking\init_ajax(), GFPaymentAddOn\init_frontend(), GFAddOn\init_frontend(), GravityView_frontend\initialize(), GravityView_frontend\insert_view_in_content(), Plugin_Upgrader\install(), Theme_Upgrader\install(), kses_init_filters(), GravityView_Edit_Entry_Admin\load(), GravityView_Edit_Entry_Render\load(), media_upload_library_form(), media_upload_type_form(), ms_upload_constants(), WP_Customize_Widgets\override_sidebars_widgets_for_theme_switch(), GFAddOn\pre_init(), GravityView_Edit_Entry_Render\prevent_render_form(), WP_Customize_Nav_Menu_Setting\preview(), WP_Customize_Setting\preview(), WP_Customize_Nav_Menu_Item_Setting\preview(), register_meta(), GFLocking\register_scripts(), register_setting(), register_taxonomy(), GravityView_Edit_Entry_Render\render_edit_form(), WP_Screen\render_per_page_options(), WP_Customize_Nav_Menus_Panel\render_screen_options(), GravityView_frontend\render_view(), WP_Screen\render_view_mode(), rest_api_default_filters(), GFAddOn\results_page_init(), WP_XMLRPC_UnitTestCase\setUp(), WP_UnitTestCase\setUp(), WP_Ajax_UnitTestCase\setUp(), GFForms\setup_database(), WPProfiler\start(), WP_Customize_Widgets\start_capturing_option_updates(), WP_Customize_Manager\start_previewing_theme(), WP_UnitTestCase\start_transaction(), GVCommon_Test\test_get_link_html(), GravityView_Merge_Tags_Test\test_gf_merge_tags(), GravityView_API_Test\test_gravityview_field_output(), GravityView_Helper_Functions_Test\test_gravityview_format_link_WHEN_FILTER_NOQUERYSTRING_FALSE(), GravityView_Helper_Functions_Test\test_gravityview_format_link_WHEN_FILTER_NOSUBDOMAIN_FALSE(), GravityView_Helper_Functions_Test\test_gravityview_format_link_WHEN_FILTER_ROOTONLY_FALSE(), GravityView_API_Test\test_no_results(), GravityView_Merge_Tags_Test\test_replace_get_variables(), GravityView_Shortcode_Test\test_shortcode_get_view_detail_PAGING(), GravityView_Shortcode_Test\test_shortcode_get_view_detail_TOTAL_ENTRIES(), twentyten_remove_recent_comments_style(), twentythirteen_setup(), WP_Customize_Nav_Menu_Setting\update(), WP_Customize_Nav_Menu_Item_Setting\update(), WP_Automatic_Updater\update(), GravityView_Edit_Entry_User_Registration\update_user(), Plugin_Upgrader\upgrade(), Theme_Upgrader\upgrade(), GFFeedAddOn\upgrade_base(), GravityView_Edit_Entry_Render\validate(), wp_ajax_crop_image(), wp_dashboard_setup(), wp_link_manager_disabled_message(), wp_list_widget_controls(), Featured_Content\wp_loaded(), wp_nav_menu_setup(), wp_signon(), wp_update_core(), wp_update_plugin(), and wp_update_theme().
admin_url ()
Definition at line 71 of file noop.php.
Referenced by GFFormLocking\__construct(), GFEntryLocking\__construct(), GFFormSettingsLocking\__construct(), GFPluginSettingsLocking\__construct(), _wp_customize_loader_settings(), WP_Press_This\add_editor_style(), GFForms\admin_bar(), Custom_Background\admin_page(), GravityView_Compatibility\check_gravityforms(), WP_Comments_List_Table\column_author(), WP_List_Table\comments_bubble(), WP_Customize_Manager\customize_pane_settings(), Featured_Content\customize_register(), GF_Installation_Wizard\display(), _WP_Editors\editor_js(), WP_Nav_Menu_Widget\form(), GravityView_Search_WP_Widget\form(), get_allowed_http_origins(), GravityView_Admin_Duplicate_View\get_clone_view_link(), GravityView_Admin_Views\get_connected_form_links(), GFForms\get_form_settings_sub_menu_items(), GFAddOn\get_plugin_settings_url(), get_theme_update_available(), get_upload_iframe_src(), WP_Comments_List_Table\get_views(), GravityView_Welcome\getting_started_screen(), GravityView_Admin_Views\gform_toolbar_menu(), WP_Posts_List_Table\handle_row_actions(), Custom_Image_Header\help(), WP_Press_This\html(), GFEntryList\leads_page(), GravityView_Settings\license_key_notice(), maybe_add_existing_user_to_blog(), media_upload_flash_bypass(), media_upload_form(), media_upload_library_form(), media_upload_max_image_resize(), media_upload_type_form(), media_upload_type_url_form(), menu_page_url(), network_step1(), WP_Themes_List_Table\no_items(), WP_Plugins_List_Table\no_items(), GravityView_Post_Types\no_views_text(), notification_edit_page(), GravityView_Admin\plugin_action_links(), GFForms\plugin_row(), GFForms\plugin_settings_link(), register_admin_color_schemes(), GravityView_Admin_Duplicate_View\save_as_new_view(), save_new_form(), send_confirmation_on_profile_email(), WP_Automatic_Updater\send_email(), Custom_Image_Header\step_1(), ToggleActive(), twentyfourteen_contextual_help(), twentyfourteen_customize_register(), update_core(), update_option_new_admin_email(), wp_admin_bar_appearance_menu(), wp_admin_bar_comments_menu(), wp_admin_bar_dashboard_view_site_menu(), wp_admin_bar_my_sites_menu(), wp_admin_bar_new_content_menu(), wp_admin_bar_site_menu(), wp_admin_css_uri(), wp_customize_support_script(), wp_customize_url(), wp_dashboard_recent_drafts(), wp_default_scripts(), wp_enqueue_media(), wp_heartbeat_settings(), wp_plupload_default_settings(), wp_prepare_revisions_for_js(), wp_prepare_themes_for_js(), wp_redirect_admin_locations(), wp_register(), and wp_user_settings().
apply_filters ()
Definition at line 26 of file noop.php.
Referenced by GravityView_Change_Entry_Creator\__construct(), WP_Feed_Cache_Transient\__construct(), WP_oEmbed\__construct(), wp_xmlrpc_server\__construct(), WP_Customize_Manager\__construct(), WP_Theme\__construct(), WP_Text_Diff_Renderer_Table\_added(), _close_comments_for_old_post(), _close_comments_for_old_posts(), WP_Text_Diff_Renderer_Table\_context(), WP_Styles\_css_href(), WP_Text_Diff_Renderer_Table\_deleted(), _deprecated_argument(), _deprecated_constructor(), _deprecated_file(), _deprecated_function(), WP_Http\_dispatch_request(), _doing_it_wrong(), WP_oEmbed\_fetch_with_format(), WP_Http\_get_first_available_transport(), _get_page_link(), wp_xmlrpc_server\_insert_post(), _load_image_to_edit_path(), _media_states(), _n(), _navigation_markup(), _nx(), GravityView_frontend\_override_sorting_id_by_field_type(), _post_states(), wp_xmlrpc_server\_prepare_comment(), wp_xmlrpc_server\_prepare_media_item(), wp_xmlrpc_server\_prepare_page(), wp_xmlrpc_server\_prepare_post(), wp_xmlrpc_server\_prepare_post_type(), wp_xmlrpc_server\_prepare_taxonomy(), wp_xmlrpc_server\_prepare_term(), wp_xmlrpc_server\_prepare_user(), WP_Image_Editor_GD\_save(), WP_Image_Editor_Imagick\_save(), _wp_admin_bar_init(), _wp_handle_upload(), _wp_image_editor_choose(), _wp_post_revision_fields(), _wp_post_thumbnail_html(), _wp_relative_upload_path(), WP_Http_Encoding\accept_encoding(), WP_Customize_Panel\active(), WP_Customize_Section\active(), WP_Customize_Control\active(), GravityView_Widget_Search\add_datepicker_localization(), GFExport\add_default_export_fields(), GravityView_Delete_Entry\add_delete_button(), WP_Customize_Manager\add_dynamic_settings(), add_menu_classes(), add_metadata(), add_network_option(), GravityView_Entry_Notes\add_note(), add_option(), add_ping(), GravityView_frontend\add_scripts_and_styles(), WP_Customize_Manager\add_setting(), GravityView_Admin_Metaboxes\add_settings_metabox_tabs(), WP_Site_Icon\additional_sizes(), adjacent_image_link(), GravityView_Admin_Notices\admin_notice(), Plugin_Upgrader_Skin\after(), Custom_Image_Header\ajax_header_crop(), WP_Styles\all_deps(), WP_Scripts\all_deps(), allow_subdirectory_install(), GravityView_Settings\app_settings_fields(), GravityView_Change_Entry_Creator\assign_new_user_to_lead(), Language_Pack_Upgrader\async_upgrade(), atom_enclosure(), attachment_submitbox_metadata(), attachment_url_to_postid(), WP_Customize_Nav_Menus\available_item_types(), WP_Http\block_request(), bloginfo_rss(), WP\build_query_string(), WP_List_Table\bulk_actions(), WP_Embed\cache_oembed(), GVCommon\calculate_get_entries_criteria(), can_edit_network(), WP_Customize_Widgets\capture_filter_pre_get_option(), WP_REST_Server\check_authentication(), check_comment(), check_comment_flood_db(), check_password_reset_key(), GravityView_Edit_Entry\check_user_cap_edit_entry(), GFFormDisplay\clean_up_files(), WP_Comments_List_Table\column_author(), WP_MS_Users_List_Table\column_blogs(), WP_Comments_List_Table\column_comment(), WP_Posts_List_Table\column_date(), WP_MS_Users_List_Table\column_default(), WP_Terms_List_Table\column_default(), WP_MS_Themes_List_Table\column_description(), WP_Terms_List_Table\column_name(), WP_MS_Themes_List_Table\column_name(), GFConfirmationTable\column_name(), WP_Terms_List_Table\column_slug(), WP_Posts_List_Table\column_title(), comment_author(), comment_author_email(), comment_author_url(), comment_excerpt(), comment_form(), comment_link(), comment_text(), comment_text_rss(), comments_link_feed(), GravityView_frontend\comments_open(), comments_open(), comments_popup_link(), comments_template(), GFFormSettings\confirmations_edit_page(), content_url(), count_user_posts(), WP_Session_Tokens\create(), GravityView_Settings\create_app_menu(), GravityView_Admin_Duplicate_View\create_duplicate(), create_initial_taxonomies(), GFForms\create_menu(), GravityView_Ajax\create_preset_form(), current_theme_supports(), WP_Customize_Manager\customize_pane_settings(), WP_Customize_Widgets\customize_register(), GFForms\dashboard_setup(), WP_oEmbed\data2html(), date_i18n(), dbDelta(), delete_metadata(), WP_Session_Tokens\destroy_all_for_all_users(), WP_oEmbed\discover(), WP_REST_Server\dispatch(), GF_Installation_Wizard_Step_Settings\display(), WP_Widget\display_callback(), GravityView_Delete_Entry\display_message(), WP_Themes_List_Table\display_rows(), WP_Plugin_Install_List_Table\display_rows(), do_enclose(), WP_Styles\do_item(), WP_Scripts\do_item(), do_robots(), do_trackbacks(), domain_exists(), WP_Upgrader\download_package(), dynamic_sidebar(), edit_bookmark_link(), edit_comment_link(), GravityView_Edit_Entry_Render\edit_entry_form(), edit_post(), edit_post_link(), edit_tag_link(), edit_term_link(), edit_user(), _WP_Editors\editor(), _WP_Editors\editor_settings(), GFForms\enqueue_admin_scripts(), GravityView_Widget_Search\enqueue_datepicker(), ent2ncr(), GravityView_API\entry_create_custom_slug(), GravityView_API\entry_link_html(), WP_REST_Server\envelope_response(), esc_attr(), esc_html(), esc_js(), esc_textarea(), esc_url(), export_wp(), WP_Comments_List_Table\extra_tablenav(), feed_content_type(), feed_links(), WP_oEmbed\fetch(), fetch_feed(), GravityView_API\field_label(), GravityView_Field\field_support_options(), GravityView_API\field_value(), file_is_displayable_image(), GravityView_Edit_Entry_Render\filter_admin_only_fields(), GravityView_Edit_Entry_Render\filter_conditional_logic(), GravityView_Widget_Search\filter_entries(), WP_Meta_Query\find_compatible_table_alias(), WP_Rewrite\flush_rules(), GFFormDisplay\footer_init_scripts(), WP_Widget\form_callback(), GFFormSettings\form_settings_ui(), format_code_lang(), format_for_editor(), format_to_edit(), GFForms\format_toolbar_menu_items(), gallery_shortcode(), get_adjacent_post(), get_adjacent_post_link(), get_adjacent_post_rel_link(), GF_Field\get_admin_buttons(), get_admin_url(), GVCommon\get_all_views(), WP_Theme\get_allowed(), get_allowed_http_origins(), get_allowed_mime_types(), get_ancestors(), get_archives_link(), get_attached_file(), get_attached_media(), get_attachment_fields_to_edit(), get_attachment_icon(), get_attachment_icon_src(), get_attachment_innerHTML(), get_attachment_link(), get_author_feed_link(), get_author_posts_url(), get_avatar_data(), get_blog_details(), get_blog_option(), get_bloginfo(), get_bloginfo_rss(), get_blogs_of_user(), get_body_class(), get_bookmarks(), get_boundary_post_rel_link(), WP_Network\get_by_path(), get_calendar(), get_cancel_comment_reply_link(), GravityView_Render_Settings\get_cap_choices(), get_categories(), GravityView_Admin_Duplicate_View\get_clone_view_link(), wpdb\get_col_charset(), get_column_headers(), WP_List_Table\get_column_info(), WP_MS_Users_List_Table\get_columns(), WP_MS_Sites_List_Table\get_columns(), WP_Media_List_Table\get_columns(), WP_Posts_List_Table\get_columns(), get_comment(), get_comment_author(), get_comment_author_email(), get_comment_author_email_link(), get_comment_author_IP(), get_comment_author_link(), get_comment_author_rss(), get_comment_author_url(), get_comment_author_url_link(), get_comment_class(), get_comment_date(), get_comment_excerpt(), get_comment_ID(), get_comment_id_fields(), get_comment_link(), get_comment_reply_link(), get_comment_text(), get_comment_time(), get_comment_to_edit(), get_comment_type(), WP_Comment_Query\get_comments(), get_comments_link(), get_comments_number(), get_comments_number_text(), get_comments_pagenum_link(), get_compat_media_markup(), GravityView_Delete_Entry\get_confirm_dialog(), GravityView_Admin_Views\get_connected_form_links(), GF_Field_Address\get_countries(), GravityView_API\get_custom_entry_slug(), get_dashboard_url(), WP_REST_Server\get_data_for_routes(), get_day_link(), GravityView_View_Data\get_default_args(), get_default_comment_status(), get_default_feed(), GravityView_Render_Settings\get_default_field_options(), get_default_post_to_edit(), GravityView_Widget\get_default_settings(), GravityView_Plugin\get_default_widget_areas(), GravityView_Delete_Entry\get_delete_mode(), get_delete_post_link(), get_edit_bookmark_link(), get_edit_comment_link(), get_edit_post_link(), get_edit_profile_url(), get_edit_tag_link(), get_edit_term_link(), get_edit_user_link(), get_editable_authors(), get_editable_roles(), get_editor_stylesheets(), get_enclosed(), GravityView_Recent_Entries_Widget\get_entries(), GVCommon\get_entries(), GVCommon\get_entry(), GravityView_Admin_Views\get_entry_default_fields(), GFFormsModel\get_entry_meta(), GravityView_API\get_entry_slug(), GravityView_Post_Types\get_entry_var_name(), get_feed_link(), GFFormDisplay\get_field_content(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GF_Field_Number\get_field_input(), GravityView_Widget_Search\get_field_label(), get_file_data(), GravityView_Field_FileUpload\get_files_array(), get_filesystem_method(), GFEntryList\get_filter_links(), GFFormDisplay\get_form(), GFFormDisplay\get_form_init_scripts(), GravityView_Widget_Poll\get_frontend_settings(), GFFormsModel\get_grid_columns(), GravityView_oEmbed\get_handler_regex(), get_header_image_tag(), get_hidden_columns(), get_hidden_meta_boxes(), get_home_url(), WP_oEmbed\get_html(), get_http_origin(), get_image_send_to_editor(), get_image_tag(), WP_REST_Server\get_index(), get_index_rel_link(), get_inline_data(), GFFormsModel\get_input_masks(), WP_Session_Tokens\get_instance(), get_intermediate_image_sizes(), WP_oEmbed_Controller\get_item(), GravityView_Admin_View_Item\get_item_info(), GravityView_Entry_List\get_item_output(), WP_List_Table\get_items_per_page(), GFFormDisplay\get_js_redirect_confirmation(), get_language_attributes(), get_lastpostdate(), get_lastpostmodified(), GFFormsModel\get_lead_field_value(), GVCommon\get_link_html(), get_links_list(), get_locale(), get_locale_stylesheet_uri(), get_main_network_id(), get_media_embedded_in_content(), get_media_item(), get_metadata(), get_month_link(), WP_REST_Server\get_namespace_index(), get_network_option(), get_next_comments_link(), get_next_posts_link(), GravityView_Entry_Notes\get_notes(), get_oembed_endpoint_url(), get_oembed_response_data(), get_option(), get_others_unpublished_posts(), GravityView_Entry_List\get_output(), GVLogic_Shortcode\get_output(), WP_Image_Editor\get_output_format(), get_page_link(), get_page_of_comment(), WP_Theme\get_page_templates(), get_page_uri(), get_pagenum_link(), get_pages(), WP_REST_Request\get_parameter_order(), get_parent_post_rel_link(), get_password_reset_key(), WP_Comments_List_Table\get_per_page(), get_permalink(), get_post_class(), get_post_comments_feed_link(), get_post_embed_url(), get_post_galleries(), get_post_gallery(), get_post_mime_types(), get_post_modified_time(), get_post_permalink(), get_post_reply_link(), get_post_status(), get_post_time(), get_post_type_archive_feed_link(), get_post_type_archive_link(), get_post_type_labels(), WP_Query\get_posts(), get_posts_by_author_sql(), GravityView_Ajax\get_preset_fields_config(), get_preview_post_link(), get_previous_comments_link(), get_previous_posts_link(), WP_List_Table\get_primary_column_name(), GFFormDisplay\get_progress_bar(), get_pung(), get_query_template(), GravityView_Admin_Views\get_registered_widgets(), get_rest_url(), WP_Users_List_Table\get_role_list(), WP_REST_Server\get_routes(), get_sample_permalink(), get_sample_permalink_html(), GravityView_Widget_Search\get_search_class(), get_search_comments_feed_link(), GravityView_frontend\get_search_criteria(), get_search_feed_link(), get_search_form(), GravityView_Widget_Search\get_search_input_types(), get_search_link(), get_search_query(), WP_Query\get_search_stopwords(), WP_Customize_Widgets\get_setting_args(), GFForms\get_shortcodes(), get_shortcut_link(), get_site_by_path(), get_site_icon_url(), get_site_transient(), get_site_url(), GVCommon\get_sortable_fields(), GVCommon\get_sortable_fields_array(), get_space_allowed(), get_space_used(), WP_Date_Query\get_sql(), get_stylesheet(), get_stylesheet_directory(), get_stylesheet_directory_uri(), get_stylesheet_uri(), get_subdirectory_reserved_names(), WP_Press_This\get_suggested_content(), wpdb\get_table_charset(), GFExport\get_tabs(), get_tabs(), get_tags(), get_taxonomy_labels(), get_template(), get_template_directory(), get_template_directory_uri(), get_term(), get_term_feed_link(), get_term_link(), get_terms(), get_terms_to_edit(), get_the_archive_description(), get_the_archive_title(), get_the_author(), get_the_author_meta(), get_the_author_posts_link(), get_the_category(), get_the_category_list(), get_the_category_rss(), get_the_content(), get_the_content_feed(), get_the_date(), get_the_excerpt(), get_the_generator(), get_the_guid(), get_the_modified_author(), get_the_modified_date(), get_the_modified_time(), get_the_password_form(), get_the_post_thumbnail(), get_the_tag_list(), get_the_tags(), get_the_term_list(), get_the_terms(), get_the_time(), get_the_title(), get_the_title_rss(), get_theme_data(), get_theme_mod(), get_theme_root(), get_theme_root_uri(), get_to_ping(), get_trackback_url(), get_transient(), get_upload_iframe_src(), GF_Field_Address\get_us_states(), get_user_option(), GVCommon\get_users(), get_users_drafts(), GF_Field_Number\get_value_entry_detail(), GF_Field_Address\get_value_entry_detail(), GF_Field_Number\get_value_entry_list(), GF_Field_Number\get_value_merge_tag(), GF_Field_Password\get_value_save_entry(), GravityView_Shortcode\get_view_detail(), WP_Comments_List_Table\get_views(), get_wp_title_rss(), GF_Field_Date\get_year_dropdown(), get_year_link(), WP_Http_Cookie\getHeaderValue(), GravityView_View\getPaginationCounts(), gform_tooltip(), global_terms_enabled(), got_mod_rewrite(), got_url_rewrite(), gravityview_back_link(), gravityview_field_output(), gravityview_format_link(), gravityview_get_context(), gravityview_get_map_link(), gravityview_get_registered_templates(), gravityview_get_terms_choices(), gv_container_class(), gv_value(), WP_Terms_List_Table\handle_row_actions(), WP_MS_Users_List_Table\handle_row_actions(), WP_MS_Sites_List_Table\handle_row_actions(), WP_Comments_List_Table\handle_row_actions(), WP_Posts_List_Table\handle_row_actions(), WP_Role\has_cap(), WP_User\has_cap(), GFFormDisplay\has_conditional_logic(), has_nav_menu(), GVCommon\has_product_field(), GravityView_Image\html(), WP_Press_This\html(), human_time_diff(), iframe_header(), iis7_supports_permalinks(), WP_Rewrite\iis7_url_rewrite_rules(), image_add_caption(), image_constrain_size_for_editor(), image_downsize(), image_edit_apply_changes(), image_get_intermediate_size(), image_resize_dimensions(), image_size_input_fields(), img_caption_shortcode(), GFExport\import_xml(), includes_url(), GFAddOn\init(), GravityView_Post_Types\init_post_types(), wp_xmlrpc_server\initialise_blog_option_info(), WP_Posts_List_Table\inline_edit(), WP_Site_Icon\insert_attachment(), Custom_Image_Header\insert_attachment(), WP_Upgrader\install_package(), WP_Site_Icon\intermediate_image_sizes(), is_active_sidebar(), is_admin_bar_showing(), GravityView_Admin\is_admin_page(), is_allowed_http_origin(), GFForms\is_auto_update_disabled(), WP_Automatic_Updater\is_disabled(), is_email(), is_email_address_unsafe(), GFFormsModel\is_encrypted_field(), GVCommon\is_field_numeric(), GravityView_frontend\is_field_sortable(), is_multi_author(), is_protected_meta(), GravityView_frontend\is_single_entry(), GFFormsModel\is_value_match(), WP_Automatic_Updater\is_vcs_checkout(), WP_Customize_Widgets\is_wide_widget(), GVCommon\js_encrypt(), WP_Customize_Setting\js_value(), GFEntryDetail\lead_detail_edit(), GFEntryDetail\lead_detail_grid(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GravityView_Edit_Entry_User_Registration\load(), WP_Image_Editor_GD\load(), WP_Image_Editor_Imagick\load(), WP_Customize_Nav_Menus\load_available_items_query(), load_image_to_edit(), load_muplugin_textdomain(), GravityView_Extension\load_plugin_textdomain(), GravityView_Plugin\load_plugin_textdomain(), load_plugin_textdomain(), load_textdomain(), load_theme_textdomain(), GravityView_Render_Settings\load_type_class(), wp_xmlrpc_server\login(), login_header(), GravityView_Edit_Entry_Render\manage_conditional_logic(), map_meta_cap(), GravityView_Support_Port\maybe_enqueue_script(), WP_Embed\maybe_make_link(), maybe_redirect_404(), GFFormsModel\maybe_trim_input(), media_buttons(), media_upload_form(), media_upload_form_handler(), media_upload_library_form(), media_upload_tabs(), media_upload_type_form(), media_upload_type_url_form(), WP_Press_This\merge_or_fetch_data(), meta_form(), metadata_exists(), WP_Rewrite\mod_rewrite_rules(), GravityView_Edit_Entry_Render\modify_edit_field_input(), WP_List_Table\months_dropdown(), ms_site_check(), wp_xmlrpc_server\mt_supportedTextFilters(), mu_dropdown_languages(), wp_xmlrpc_server\mw_newMediaObject(), network_admin_url(), network_home_url(), network_site_url(), newblog_notify_siteadmin(), newuser_notify_siteadmin(), next_post(), GFForms\no_conflict_mode(), GravityView_API\no_results(), GFEntryDetail\notes_grid(), notification_edit_page(), number_format_i18n(), page_attributes_meta_box(), GFSettings\page_header(), GFForms\page_supports_add_form_button(), paginate_links(), IXR_Message\parse(), GravityView_View_Data\parse_post_meta(), WP\parse_request(), _WP_Editors\parse_settings(), GFForms\parse_shortcode(), GFEntryDetail\payment_details_box(), pingback(), wp_xmlrpc_server\pingback_error(), wp_xmlrpc_server\pingback_ping(), pings_open(), plugins_api(), plugins_url(), populate_network(), post_categories_meta_box(), post_comments_feed_link(), post_slug_meta_box(), post_type_archive_title(), postbox_classes(), GravityView_Ajax\pre_get_form_fields(), GravityView_Widget\pre_render_frontend(), WP_MS_Users_List_Table\prepare_items(), WP_Theme_Install_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), WP_Plugins_List_Table\prepare_items(), WP_Terms_List_Table\prepare_items(), WP_Users_List_Table\prepare_items(), WP_MS_Themes_List_Table\prepare_items(), WP_Posts_List_Table\prepare_items(), WP_User_Query\prepare_query(), prepend_attachment(), previous_post(), print_admin_styles(), print_emoji_detection_script(), print_footer_scripts(), print_head_scripts(), print_late_styles(), GFFormsModel\purge_expired_incomplete_submissions(), WP_HTTP_IXR_Client\query(), WP_User_Query\query(), wpdb\query(), WP_Widget_Recent_Comments\recent_comments_style(), redirect_canonical(), WP_Customize_Manager\refresh_nonces(), register_new_user(), register_post_type(), WP_oEmbed_Controller\register_routes(), register_taxonomy(), GravityView_Admin\remove_conflicts(), GravityView_Admin_Views\render_additional_fields(), GravityView_Admin_Views\render_available_fields(), GravityView_Admin_Views\render_directory_active_areas(), GravityView_Render_Settings\render_field_option(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Pagination_Info\render_frontend(), WP_Screen\render_per_page_options(), WP_Screen\render_screen_meta(), WP_Screen\render_screen_options(), GravityView_Widget_Search\render_searchable_fields(), GravityView_frontend\render_view(), WP_Screen\render_view_mode(), GravityView_Merge_Tags\replace_get_variables(), GFFormDisplay\replace_save_variables(), GravityView_Merge_Tags\replace_variables(), WP_Http_Streams\request(), WP_Http_Curl\request(), WP_Http\request(), request_filesystem_credentials(), rest_get_url_prefix(), GravityView_Edit_Entry_User_Registration\restore_display_name(), retrieve_password(), WP_Rewrite\rewrite_rules(), rss_enclosure(), WP_Upgrader\run(), WP_Automatic_Updater\run(), safecss_filter_attr(), WP_Customize_Nav_Menu_Setting\sanitize(), WP_Customize_Setting\sanitize(), WP_Customize_Nav_Menu_Item_Setting\sanitize(), sanitize_bookmark_field(), sanitize_comment_cookies(), GFFormsModel\sanitize_conditional_logic(), sanitize_email(), sanitize_file_name(), sanitize_html_class(), sanitize_key(), sanitize_meta(), sanitize_mime_type(), sanitize_option(), sanitize_post_field(), GFFormsModel\sanitize_settings(), sanitize_term_field(), sanitize_text_field(), sanitize_title(), sanitize_trackback_urls(), sanitize_user(), sanitize_user_field(), WP_Customize_Manager\save(), GFFormsModel\save_incomplete_submission(), WP_Press_This\save_post(), GravityView_Cache\schedule_transient_cleanup(), search_theme_directories(), self_link(), send_confirmation_on_profile_email(), WP_Automatic_Updater\send_core_update_notification_email(), WP_Automatic_Updater\send_debug_email(), WP_Automatic_Updater\send_email(), WP\send_headers(), WP_HTTP_Proxy\send_through_proxy(), WP_REST_Server\serve_request(), GravityView_Cache\set(), GravityView_Image\set_image_size(), GFFormsModel\set_permissions(), WP_Image_Editor\set_quality(), set_screen_options(), set_site_transient(), wpdb\set_sql_mode(), set_theme_mod(), set_transient(), set_url_scheme(), WP_Query\setup_postdata(), WP_Embed\shortcode(), shortcode_atts(), WP_Automatic_Updater\should_update(), Core_Upgrader\should_update_to_version(), GravityView_Admin_ApproveEntries\show_approve_entry_column(), WP_Screen\show_screen_options(), GravityView_frontend\single_entry_title(), single_post_title(), WP_Theme_Install_List_Table\single_row(), WP_Users_List_Table\single_row(), WP_Plugins_List_Table\single_row(), single_term_title(), WP_Press_This\site_settings(), spawn_cron(), Walker_CategoryDropdown\start_el(), Walker_Category_Checklist\start_el(), Walker_Nav_Menu_Checklist\start_el(), Walker_Nav_Menu\start_el(), Walker_Page\start_el(), Walker_Category\start_el(), GFExport\start_export(), status_header(), Custom_Image_Header\step_2(), Custom_Image_Header\step_3(), stream_preview_image(), tag_escape(), WP_Http_Curl\test(), WP_Http_Streams\test(), Tests_REST_Server\test_allow_header_send_only_permitted_methods(), Tests_REST_Server\test_allow_header_sent(), Tests_REST_Server\test_allow_header_sent_with_multiple_methods(), the_author_meta(), the_content(), the_content_rss(), the_date(), the_excerpt(), the_excerpt_embed(), the_excerpt_rss(), the_feed_link(), the_generator(), the_guid(), the_media_upload_tabs(), the_meta(), the_modified_date(), the_modified_time(), the_permalink(), the_permalink_rss(), the_search_query(), the_shortlink(), the_terms(), the_time(), the_weekday(), the_weekday_date(), themes_api(), GravityView_Admin_Views\tooltips(), GFForms\top_toolbar(), translate(), translate_smiley(), translate_with_gettext_context(), translations_api(), GFFormsModel\trim_conditional_logic_values_from_element(), GFFormsModel\trim_form_meta_values(), twentyeleven_color_schemes(), twentyeleven_get_default_theme_options(), twentyeleven_get_first_url(), twentyeleven_layout_classes(), twentyeleven_layouts(), twentyeleven_theme_options_validate(), twentyfifteen_custom_header_setup(), twentyfifteen_get_color_schemes(), twentyfourteen_custom_header_setup(), twentyfourteen_get_featured_posts(), twentythirteen_get_link_url(), unload_textdomain(), unzip_file(), GravityView_Recent_Entries_Widget\update(), update_attached_file(), WP_Widget\update_callback(), update_core(), GFAPI\update_entry(), update_metadata(), update_network_option(), update_option(), update_option_new_admin_email(), update_right_now_message(), GravityView_Edit_Entry_User_Registration\update_user(), Core_Upgrader\upgrade(), GFAsyncUpload\upload(), url_to_postid(), GravityView_Cache\use_cache(), user_admin_url(), user_can_richedit(), GravityView_Support_Port\user_field(), user_trailingslashit(), GF_Field_FileUpload\validate(), WP_Date_Query\validate_column(), validate_current_theme(), GravityView_Image\validate_image_src(), validate_username(), WP_Customize_Setting\value(), WP_Customize_Nav_Menu_Item_Setting\value_as_wp_post_nav_menu_item(), GravityView_Delete_Entry\verify_nonce(), GravityView_Edit_Entry_Render\verify_nonce(), WP_Media_List_Table\views(), WP_Plugin_Install_List_Table\views(), WP_List_Table\views(), WP_Widget_Links\widget(), WP_Widget_Search\widget(), WP_Nav_Menu_Widget\widget(), WP_Widget_Tag_Cloud\widget(), WP_Widget_Archives\widget(), WP_Widget_Pages\widget(), WP_Widget_Categories\widget(), WP_Widget_Recent_Posts\widget(), WP_Widget_Text\widget(), WP_Widget_RSS\widget(), GravityView_Search_WP_Widget\widget(), WP_Widget_Meta\widget(), Twenty_Eleven_Ephemera_Widget\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), WP_Widget_Calendar\widget(), WP_Widget_Recent_Comments\widget(), GravityView_Recent_Entries_Widget\widget(), wp_admin_css(), wp_admin_css_uri(), wp_ajax_add_menu_item(), wp_ajax_ajax_tag_search(), wp_ajax_autocomplete_user(), wp_ajax_crop_image(), wp_ajax_heartbeat(), wp_ajax_inline_save(), wp_ajax_menu_get_metabox(), wp_ajax_nopriv_heartbeat(), wp_ajax_query_attachments(), wp_ajax_query_themes(), wp_ajax_save_attachment_compat(), wp_ajax_send_attachment_to_editor(), wp_ajax_send_link_to_editor(), wp_ajax_wp_remove_post_lock(), wp_allow_comment(), wp_allowed_protocols(), wp_audio_shortcode(), wp_auth_check_html(), wp_auth_check_load(), wp_authenticate_spam_check(), wp_authenticate_username_password(), wp_calculate_image_sizes(), wp_calculate_image_srcset(), wp_check_filetype_and_ext(), wp_checkdate(), wp_comment_reply(), wp_constrain_dimensions(), wp_count_attachments(), wp_count_comments(), wp_count_posts(), wp_create_thumbnail(), wp_dashboard_quick_press(), wp_dashboard_recent_drafts(), wp_dashboard_right_now(), wp_dashboard_setup(), wp_default_editor(), wp_default_scripts(), wp_delete_attachment(), wp_delete_file(), wp_delete_post(), wp_delete_user(), wp_die(), wp_doc_link_parse(), wp_dropdown_categories(), wp_dropdown_pages(), wp_dropdown_users(), wp_edit_attachments_query_vars(), wp_edit_posts_query(), wp_embed_defaults(), wp_embed_handler_audio(), wp_embed_handler_googlevideo(), wp_embed_handler_video(), wp_embed_handler_youtube(), wp_enqueue_media(), wp_ext2type(), WP_Filesystem(), wp_filter_comment(), wp_generate_attachment_metadata(), wp_generate_tag_cloud(), wp_generator(), wp_get_archives(), wp_get_attachment_id3_keys(), wp_get_attachment_image(), wp_get_attachment_image_src(), wp_get_attachment_link(), wp_get_attachment_metadata(), wp_get_attachment_thumb_file(), wp_get_attachment_thumb_url(), wp_get_attachment_url(), wp_get_audio_extensions(), wp_get_comment_column_max_length(), wp_get_current_commenter(), wp_get_document_title(), wp_get_mime_types(), wp_get_nav_menu_object(), wp_get_nav_menu_to_edit(), wp_get_nav_menus(), wp_get_nocache_headers(), wp_get_object_terms(), wp_get_password_hint(), wp_get_revision_ui_diff(), wp_get_schedules(), wp_get_shortlink(), wp_get_sidebars_widgets(), wp_get_update_data(), wp_get_user_contact_methods(), wp_get_video_extensions(), wp_xmlrpc_server\wp_getPost(), wp_xmlrpc_server\wp_getPosts(), wp_xmlrpc_server\wp_getPostType(), wp_xmlrpc_server\wp_getPostTypes(), wp_xmlrpc_server\wp_getProfile(), wp_xmlrpc_server\wp_getRevisions(), wp_xmlrpc_server\wp_getTaxonomies(), wp_xmlrpc_server\wp_getTaxonomy(), wp_xmlrpc_server\wp_getUser(), wp_xmlrpc_server\wp_getUsers(), wp_htmledit_pre(), wp_http_validate_url(), wp_import_upload_form(), wp_insert_post(), wp_insert_term(), wp_insert_user(), wp_is_large_network(), wp_kses_allowed_html(), wp_kses_hook(), wp_link_category_checklist(), wp_link_pages(), _WP_Editors\wp_link_query(), wp_list_bookmarks(), wp_list_categories(), wp_list_comments(), wp_list_pages(), wp_load_image(), wp_login_form(), wp_login_url(), wp_loginout(), wp_logout_url(), wp_lostpassword_url(), wp_max_upload_size(), wp_maybe_load_embeds(), wp_maybe_load_widgets(), wp_maybe_update_network_site_counts(), wp_maybe_update_network_user_counts(), _WP_Editors\wp_mce_translation(), wp_media_insert_url_form(), wp_media_upload_handler(), wp_mediaelement_fallback(), wp_mime_type_icon(), wp_nav_menu(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_post_type_meta_boxes(), wp_nav_menu_taxonomy_meta_boxes(), wp_new_comment(), wp_new_comment_notify_moderator(), wp_new_comment_notify_postauthor(), wp_xmlrpc_server\wp_newComment(), wp_oembed_add_discovery_links(), wp_old_slug_redirect(), wp_page_menu(), wp_parse_str(), wp_playlist_shortcode(), wp_plupload_default_settings(), wp_popular_terms_checklist(), wp_post_revision_title_expanded(), wp_prepare_attachment_for_js(), wp_prepare_revisions_for_js(), wp_prepare_themes_for_js(), wp_print_media_templates(), wp_read_image_metadata(), wp_register(), wp_registration_url(), wp_removable_query_args(), wp_revisions_to_keep(), wp_richedit_pre(), wp_save_image_file(), wp_save_post_revision(), wp_schedule_event(), wp_schedule_single_event(), wp_set_comment_cookies(), wp_setup_nav_menu_item(), wp_should_upgrade_global_tables(), wp_signon(), wp_site_icon(), wp_spaces_regexp(), wp_sprintf(), wp_sprintf_l(), wp_staticize_emoji(), wp_staticize_emoji_for_email(), wp_stream_image(), wp_tag_cloud(), wp_terms_checklist(), wp_title(), wp_title_rss(), wp_trim_excerpt(), wp_trim_words(), wp_unique_post_slug(), wp_unique_term_slug(), wp_update_attachment_metadata(), wp_update_comment(), wp_update_plugins(), wp_update_term(), wp_update_themes(), wp_update_user(), wp_upload_bits(), wp_upload_dir(), wp_version_check(), wp_video_shortcode(), wpmu_delete_blog(), wpmu_signup_blog_notification(), wpmu_signup_user_notification(), wpmu_validate_blog_signup(), wpmu_validate_user_signup(), wpmu_welcome_notification(), wpmu_welcome_user_notification(), and wptexturize().
did_action ()
Definition at line 46 of file noop.php.
Referenced by _default_wp_die_handler(), _register_widget_form_callback(), _remove_theme_support(), _wp_scripts_maybe_doing_it_wrong(), add_theme_support(), WP_Customize_Widgets\call_widget_update(), wpdb\check_connection(), create_initial_taxonomies(), WP_Rewrite\flush_rules(), GravityView_frontend\insert_view_in_content(), print_head_scripts(), GravityView_View\render_widget_hooks(), restore_current_blog(), wpdb\select(), switch_to_blog(), wp_admin_css(), wp_audio_shortcode(), wp_default_scripts(), wp_enqueue_media(), wp_load_translations_early(), wp_oembed_add_provider(), wp_oembed_remove_provider(), wp_print_head_scripts(), wp_register_sidebar_widget(), wp_register_widget_control(), and wp_video_shortcode().
do_action_ref_array ()
Definition at line 51 of file noop.php.
Referenced by WP_Styles\__construct(), edit_user(), fetch_feed(), WP_Widget\form_callback(), WP_Comment_Query\get_comments(), WP_Query\get_posts(), WP_Query\have_posts(), WP_Scripts\init(), WP\main(), WP_Comment_Query\parse_query(), WP_Query\parse_query(), WP\parse_request(), pingback(), WP_User_Query\prepare_query(), WP_Http_Curl\request(), WP_Rewrite\rewrite_rules(), WP\send_headers(), WP_Query\setup_postdata(), WP_Query\the_post(), wp_admin_bar_render(), and wp_signon().
esc_attr ()
Definition at line 21 of file noop.php.
Referenced by _admin_search_query(), GV_License_Handler\_get_edd_settings(), WP_Media_List_Table\_get_row_actions(), WP_Themes_List_Table\_js_vars(), GV_License_Handler\_license_get_remote_response(), _list_meta_row(), _print_scripts(), _print_styles(), WP_Admin_Bar\_render_group(), WP_Admin_Bar\_render_item(), GravityView_Entry_Link_Shortcode_Test\_test_edit(), GravityView_Entry_Link_Shortcode_Test\_test_read(), _walk_bookmarks(), _wp_dashboard_control_callback(), _wp_menu_output(), WP_Admin_Bar\add_node(), GravityView_Entry_Notes\add_note(), GravityView_Change_Entry_Creator\add_select(), GravityView_Admin_Add_Shortcode\add_shortcode_popup(), GravityView_Admin_Notices\admin_notice(), GravityView_Extension\admin_notice(), attribute_escape(), WP_List_Table\bulk_actions(), WP_Comments_List_Table\column_comment(), WP_MS_Themes_List_Table\column_description(), WP_Terms_List_Table\column_name(), WP_MS_Themes_List_Table\column_name(), WP_Posts_List_Table\column_title(), comment_form(), comments_popup_link(), confirm_delete_users(), WP_Customize_Nav_Menu_Control\content_template(), GFForms\create_menu(), GravityView_Ajax\create_preset_form(), WP_oEmbed\data2html(), GravityView_Admin_Notices\dismiss_notice(), GF_Installation_Wizard\display(), GravityView_Delete_Entry\display_message(), WP_Themes_List_Table\display_rows(), WP_Links_List_Table\display_rows(), WP_Plugin_Install_List_Table\display_rows(), GFAutoUpgrade\display_updates(), WP_Styles\do_item(), do_settings_fields(), GravityView_Edit_Entry_Render\edit_entry_form(), edit_post_link(), _WP_Editors\editor(), GFEntryDetail\entry_detail_pagination_link(), esc_attr__(), esc_attr_e(), esc_attr_x(), WP_Comments_List_Table\extra_tablenav(), feed_links(), feed_links_extra(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_Widget_Search\filter_entries(), WP_Nav_Menu_Widget\form(), WP_Widget_Tag_Cloud\form(), WP_Widget_Recent_Posts\form(), GravityView_Search_WP_Widget\form(), Twenty_Eleven_Ephemera_Widget\form(), Twenty_Fourteen_Ephemera_Widget\form(), form_option(), GFFormSettings\form_settings_ui(), GFForms\format_toolbar_menu_items(), GV_License_Handler\generate_license_box(), get_adjacent_post_rel_link(), get_archives_link(), get_attachment_fields_to_edit(), get_attachment_icon(), get_attachment_innerHTML(), GravityView_Ajax\get_available_fields_html(), get_boundary_post_rel_link(), get_calendar(), GF_Field_Address\get_canadian_provinces_dropdown(), GF_Field_Checkbox\get_checkbox_choices(), GFFormDisplay\get_chosen_init_script(), get_comment_reply_link(), get_compat_media_markup(), GFFormDisplay\get_conditional_logic(), GF_Field_Address\get_country_dropdown(), GF_Field_Date\get_date_array_by_format(), get_default_link_to_edit(), WP_Posts_List_Table\get_edit_link(), GravityView_FieldType\get_field_id(), GF_Field_SingleShipping\get_field_input(), GF_Field_Hidden\get_field_input(), GF_Field_Post_Image\get_field_input(), GF_Field_HiddenProduct\get_field_input(), GF_Field_Checkbox\get_field_input(), GF_Field_Post_Tags\get_field_input(), GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Calculation\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_Select\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_SingleProduct\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_Post_Title\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Name\get_field_input(), GF_Field_Donation\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Password\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_MultiSelect\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GF_Field_Number\get_field_input(), GravityView_Widget_Search\get_field_label(), GravityView_Ajax\get_field_options(), GF_Field\get_field_placeholder_attribute(), GravityView_Field_FileUpload\get_files_array(), GFFormDisplay\get_form_button(), get_image_send_to_editor(), get_image_tag(), get_index_rel_link(), GF_Field\get_input_placeholder_attribute(), WP_Customize_Control\get_link(), GVCommon\get_link_html(), get_links(), GF_Field_List\get_list_input(), get_media_item(), get_parent_post_rel_link(), GravityView_Ajax\get_preset_fields_config(), GF_Field_Radio\get_radio_choices(), GravityView_frontend\get_search_criteria(), get_search_query(), GVCommon\get_sortable_fields(), GF_Field_Address\get_state_dropdown(), get_submit_button(), get_terms_to_edit(), get_the_attachment_link(), get_the_author_link(), get_the_author_posts_link(), get_the_category_rss(), get_the_taxonomies(), GF_Field_Address\get_us_state_dropdown(), GF_Field_FileUpload\get_value_entry_detail(), GF_Field_Post_Image\get_value_entry_list(), GF_Field_FileUpload\get_value_entry_list(), WP_Media_List_Table\get_views(), GravityView_Admin_View_Item\getOutput(), GFFormDisplay\gform_footer(), GravityView_Admin_Views\gform_toolbar_menu(), gform_tooltip(), WP_Terms_List_Table\handle_row_actions(), WP_Posts_List_Table\handle_row_actions(), GravityView_Image\html(), image_align_input_fields(), image_link_input_fields(), img_caption_shortcode(), GravityView_Cache\in_blacklist(), WP_Customize_Control\input_attrs(), install_plugin_information(), WP_Theme_Install_List_Table\install_theme_info(), install_themes_dashboard(), GFEntryDetail\lead_detail_edit(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GV_License_Handler\license_call(), list_core_update(), load_template(), media_buttons(), media_sideload_image(), media_upload_form_handler(), media_upload_library_form(), meta_form(), WP_List_Table\months_dropdown(), mu_dropdown_languages(), notification_edit_page(), options_reading_blog_charset(), GravityView_Metabox_Tab\parse_icon_class_name(), post_categories_meta_box(), WP_Press_This\post_formats_html(), post_tags_meta_box(), post_trackback_meta_box(), GravityView_Widget_Search\prepare_field_filter(), WP_Styles\print_inline_style(), GravityView_Delete_Entry\process_delete(), GF_Installation_Wizard\progress(), GravityView_Render_Settings\render_checkbox_option(), WP_Customize_Nav_Menu_Location_Control\render_content(), WP_Customize_Control\render_content(), GravityView_Render_Settings\render_field_options(), GravityView_Widget_Search\render_searchable_fields(), GravityView_Render_Settings\render_select_option(), GravityView_Render_Settings\render_text_option(), GravityView_Render_Settings\render_textarea_option(), GravityView_frontend\render_view(), GFFormDisplay\replace_save_variables(), request_filesystem_credentials(), GFPaymentAddOn\results_filter_ui(), sanitize_bookmark_field(), sanitize_comment_cookies(), sanitize_post_field(), sanitize_term_field(), sanitize_user_field(), WP_List_Table\search_box(), GravityView_Entry_List\set_item_tag(), GravityView_Entry_List\set_wrapper_tag(), GFPaymentAddOn\settings_billing_cycle(), settings_fields(), GFAddOn\settings_hidden(), GravityView_Settings\settings_submit(), GFAddOn\settings_text(), GFAddOn\settings_textarea(), GravityView_Entry_Link_Shortcode\shortcode(), Custom_Image_Header\show_header_selector(), WP_Theme_Install_List_Table\single_row(), WP_Users_List_Table\single_row(), WP_Plugins_List_Table\single_row(), Walker_Nav_Menu_Edit\start_el(), Walker_Nav_Menu_Checklist\start_el(), Walker_Nav_Menu\start_el(), Walker_Category\start_el(), Custom_Image_Header\step_1(), the_media_upload_tabs(), the_post_password(), the_search_query(), the_title_attribute(), GFForms\toolbar_sub_menu_items(), twentyeleven_footer_sidebar_class(), twentythirteen_header_style(), WP_Widget_Archives\widget(), WP_Widget_Categories\widget(), WP_Widget_RSS\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_admin_bar_shortlink_menu(), wp_ajax_add_link_category(), wp_ajax_find_posts(), wp_ajax_send_attachment_to_editor(), wp_audio_shortcode(), wp_dashboard_recent_drafts(), wp_dropdown_categories(), wp_dropdown_languages(), wp_dropdown_pages(), wp_dropdown_roles(), wp_dropdown_users(), wp_embed_handler_googlevideo(), wp_generate_tag_cloud(), wp_get_update_data(), wp_image_add_srcset_and_sizes(), wp_install_language_form(), wp_kses_one_attr(), wp_list_authors(), wp_list_categories(), wp_list_widget_controls(), wp_login_form(), wp_media_upload_handler(), wp_nav_menu(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_item_taxonomy_meta_box(), wp_nonce_field(), wp_original_referer_field(), wp_page_menu(), wp_playlist_shortcode(), wp_plugin_update_row(), wp_referer_field(), wp_theme_update_row(), wp_timezone_choice(), wp_video_shortcode(), wp_widget_control(), wp_widget_rss_form(), wp_widget_rss_output(), and RGXML\xml_attribute().
get_bloginfo ()
Definition at line 56 of file noop.php.
Referenced by _access_denied_splash(), _fix_attachment_links(), GravityView_Support_Port\_localize_script(), GFForms\add_form_button(), Gravity_Api\add_site(), GFForms\addons_page(), admin_created_user_email(), cache_javascript_headers(), core_update_footer(), WP_Customize_Nav_Menus\customize_register(), _WP_Editors\editor_settings(), export_wp(), WP_Press_This\fetch_source_html(), filter_SSL(), get_bloginfo_rss(), GFAutoUpgrade\get_changelog(), GFForms\get_changelog(), GravityView_Settings\get_default_settings(), GF_Field_FileUpload\get_field_input(), get_header_image_tag(), get_index_rel_link(), get_oembed_response_data(), get_pagenum_link(), GFAutoUpgrade\get_remote_request_params(), WP\handle_404(), html_type_rss(), WP_Customize_Panel\json(), WP_Customize_Section\json(), WP_Customize_Nav_Menus\load_available_items_query(), login_footer(), wp_xmlrpc_server\pingback_ping(), WP_Customize_Nav_Menu_Item_Setting\populate_value(), WP_Http\request(), Gravity_Api\request(), WP_Customize_Nav_Menus\search_available_items_query(), WP_Automatic_Updater\send_debug_email(), GravityView_Merge_Tags_Test\test_gf_merge_tags(), WP_Customize_Media_Control\to_json(), twentyfourteen_wp_title(), twentythirteen_wp_title(), twentytwelve_wp_title(), update_right_now_message(), Gravity_Api\update_site(), weblog_ping(), wp_admin_bar_site_menu(), wp_default_scripts(), wp_default_styles(), wp_install_maybe_enable_pretty_permalinks(), wp_nonce_ays(), wp_update_plugins(), and wp_update_themes().
get_file ($path)
Definition at line 95 of file noop.php.
References $path.
get_option ()
Definition at line 31 of file noop.php.
Referenced by WP_Comments_List_Table\__construct(), WP_Posts_List_Table\__construct(), GravityView_Uninstall_Test\_check_deleted_options(), _close_comments_for_old_post(), _close_comments_for_old_posts(), _fix_attachment_links(), _get_cron_array(), _get_term_hierarchy(), wp_xmlrpc_server\_getOptions(), WP_Roles\_init(), _mb_strlen(), _mb_substr(), _media_states(), _oembed_rest_pre_serve_request(), _post_states(), _publish_post_hook(), _reset_front_page_settings_for_post(), _split_shared_term(), _walk_bookmarks(), _wp_auto_add_pages_to_menu(), _wp_batch_split_terms(), _wp_check_for_scheduled_split_terms(), _wp_check_split_default_terms(), _wp_link_page(), _wp_menu_item_classes_by_context(), _wp_mysql_week(), _wp_upgrade_revisions_of_post(), activate_plugin(), GravityView_Widget_Search\add_datepicker_localization(), add_term_meta(), allow_subdomain_install(), balanceTags(), GravityView_Cache\blacklist_add(), GravityView_Cache\blacklist_remove(), WP_Http\block_request(), wp_xmlrpc_server\blogger_getUsersBlogs(), check_comment(), check_theme_switched(), WP_MS_Sites_List_Table\column_blogname(), WP_Terms_List_Table\column_cb(), WP_MS_Themes_List_Table\column_name(), comment_form(), comments_template(), convert_smilies(), create_initial_taxonomies(), CreatePlaceholdersUI(), current_time(), GFForms\dashboard_dismiss_upgrade(), GFForms\dashboard_update_message(), date_i18n(), deactivate_plugins(), WP_Site_Icon\delete_attachment_data(), delete_term_meta(), GF_Installation_Wizard_Step_Background_Updates\display(), do_robots(), GFFormDisplay\enqueue_form_scripts(), GravityView_API\entry_link(), esc_textarea(), export_wp(), fetch_feed(), GVCommon\format_date(), format_for_editor(), WP_Rewrite\generate_rewrite_rules(), generic_ping(), get_adjacent_post_link(), get_adjacent_post_rel_link(), WP_Theme\get_allowed_on_site(), GravityView_Settings\get_app_settings(), get_attachment_fields_to_edit(), get_attachment_link(), get_author_feed_link(), get_avatar_data(), get_blog_details(), get_blog_option(), get_bloginfo(), get_blogs_of_user(), get_boundary_post_rel_link(), get_calendar(), GFAutoUpgrade\get_changelog(), GFForms\get_changelog(), get_clean_basedomain(), get_comment_date(), get_comment_link(), get_comment_pages_count(), get_comment_reply_link(), get_comment_time(), get_comments_pagenum_link(), get_current_theme(), GFFormsModel\get_custom_choices(), get_date_from_gmt(), get_default_comment_status(), get_default_post_to_edit(), GravityView_Uninstall\get_delete_setting(), GF_Field_CAPTCHA\get_field_input(), get_gmt_from_date(), GFExport\get_gmt_timestamp(), get_home_path(), get_home_url(), WP_REST_Server\get_index(), get_language_attributes(), get_links(), get_locale(), GFPaymentAddOn\get_mysql_tz_offset(), get_page_link(), get_page_of_comment(), get_parent_post_rel_link(), get_permalink(), get_post_comments_feed_link(), get_post_embed_url(), WP_Site_Icon\get_post_metadata(), get_post_reply_link(), get_post_type_archive_feed_link(), get_post_type_archive_link(), WP_Query\get_posts(), WP_Query\get_queried_object(), get_raw_theme_root(), GravityView_Migrate\get_redux_settings(), get_rest_url(), WP_Customize_Setting\get_root_value(), get_sample_permalink_html(), Featured_Content\get_setting(), WP_Widget\get_settings(), get_settings(), get_settings_errors(), get_site_icon_url(), Gravity_Api\get_site_key(), Gravity_Api\get_site_secret(), get_site_url(), get_space_allowed(), GF_Installation_Wizard\get_step(), Featured_Content\get_sticky_posts(), get_stylesheet(), get_template(), get_term_feed_link(), get_term_meta(), get_the_category_rss(), get_the_date(), get_the_modified_date(), get_the_modified_time(), get_the_time(), get_theme_mods(), get_theme_root_uri(), get_trackback_url(), get_uploaded_header_images(), get_weekstartend(), GravityView_Welcome\getting_started_screen(), global_terms(), WP_Terms_List_Table\handle_row_actions(), WP_Press_This\html(), iframe_header(), image_constrain_size_for_editor(), GravityView_Cache\in_blacklist(), WP_Rewrite\init(), GFForms\is_auto_update_disabled(), is_dynamic_sidebar(), WP_Query\is_front_page(), GFFormsModel\is_html5_enabled(), is_plugin_active(), is_sticky(), is_uninstallable_plugin(), iso8601_to_datetime(), GFForms\load_first(), GV_Unit_Tests_Bootstrap\load_rest_api(), make_url_footnote(), map_meta_cap(), maybe_add_existing_user_to_blog(), maybe_disable_link_manager(), GFForms\maybe_display_installation_wizard(), GFExport\maybe_export(), GFForms\maybe_import_forms(), GFForms\maybe_import_theme_forms(), GravityView_Migrate\maybe_migrate_search_widget(), media_upload_form(), media_upload_max_image_resize(), ms_cookie_constants(), network_step1(), network_step2(), new_user_email_admin_notice(), newblog_notify_siteadmin(), GFForms\no_conflict_mode_script(), GFForms\no_conflict_mode_style(), noindex(), options_reading_blog_charset(), IXR_Server\output(), page_attributes_meta_box(), WP_Query\parse_query(), wp_xmlrpc_server\pingback_ping(), populate_network(), Featured_Content\pre_get_posts(), WP_Themes_List_Table\prepare_items(), WP_Plugins_List_Table\prepare_items(), WP_Customize_Widgets\preview_sidebars_widgets(), GFFormDisplay\print_form_scripts(), privacy_ping_filter(), redirect_canonical(), WP_Customize_Manager\register_controls(), register_new_user(), register_post_type(), register_taxonomy(), register_uninstall_hook(), WP_Roles\reinit(), rel_canonical(), WP_Roles\remove_role(), remove_theme_mod(), remove_theme_mods(), WP_Http\request(), Gravity_Api\request(), request_filesystem_credentials(), rest_api_maybe_flush_rewrites(), retrieve_password(), WP_Automatic_Updater\run(), sanitize_option(), GFFormsModel\save_key(), WP_Ajax_Response\send(), send_confirmation_on_profile_email(), WP_Automatic_Updater\send_email(), WP\send_headers(), WP_HTTP_Proxy\send_through_proxy(), WP_REST_Server\serve_request(), WP_Rewrite\set_category_base(), WP_Rewrite\set_tag_base(), set_theme_mod(), GFSettings\settings_uninstall_page(), GFFeedAddOn\setup(), GFPaymentAddOn\setup(), GFAddOn\setup(), GFForms\setup(), GFForms\setup_database(), smilies_init(), Walker_Page\start_el(), stick_post(), switch_theme(), GravityView_API_Test\test_replace_variables(), Tests_REST_API\test_rest_url_scheme(), trackback(), trackback_response(), twentyeleven_get_theme_options(), twentyfifteen_scripts(), twentyfourteen_scripts(), twentythirteen_body_class(), twentythirteen_scripts_styles(), twentytwelve_scripts_styles(), uninstall_plugin(), unstick_post(), WP_Customize_Nav_Menu_Setting\update(), GFFormsModel\update_lead_field_value(), update_option_new_admin_email(), update_recently_edited(), update_term_meta(), update_termmeta_cache(), upgrade_290(), upgrade_330(), upgrade_340(), upgrade_400(), GFAsyncUpload\upload(), upload_space_setting(), GF_Field_CAPTCHA\validate(), validate_active_plugins(), WP_Customize_Nav_Menu_Setting\value(), weblog_ping(), WP_Widget_RSS\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), Twenty_Eleven_Ephemera_Widget\widget(), WP_Widget_Recent_Comments\widget(), wp_ajax_delete_inactive_widgets(), wp_blacklist_check(), wp_check_invalid_utf8(), wp_convert_widget_settings(), wp_cookie_constants(), wp_dashboard_right_now(), wp_delete_term(), wp_edit_posts_query(), wp_enqueue_media(), wp_generate_attachment_metadata(), wp_get_active_and_valid_plugins(), wp_get_archives(), wp_get_shortlink(), wp_get_sidebars_widgets(), wp_get_split_terms(), wp_xmlrpc_server\wp_getUsersBlogs(), wp_handle_comment_submission(), wp_htmledit_pre(), wp_http_validate_url(), wp_insert_link(), wp_insert_post(), wp_insert_user(), wp_install_maybe_enable_pretty_permalinks(), wp_list_categories(), wp_list_comments(), wp_list_pages(), wp_media_insert_url_form(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_update_menu_items(), wp_new_comment_notify_postauthor(), wp_xmlrpc_server\wp_newComment(), wp_page_menu(), wp_plugin_directory_constants(), wp_prepare_revisions_for_js(), wp_register(), wp_resolve_numeric_slug_conflicts(), WP_Rewrite\wp_rewrite_rules(), wp_richedit_pre(), wp_save_image(), wp_send_json(), wp_set_internal_encoding(), wp_set_link_cats(), wp_set_post_categories(), wp_ssl_constants(), wp_term_is_shared(), wp_timezone_override_offset(), wp_trim_words(), wp_unique_post_slug(), wp_unique_term_slug(), wp_update_plugins(), wp_update_themes(), wp_update_user(), wp_upload_dir(), wp_widget_rss_output(), wp_widgets_init(), wpmu_delete_blog(), wpmu_signup_blog_notification(), wpmu_signup_user_notification(), wpmu_welcome_notification(), and wpmu_welcome_user_notification().
home_url ()
Definition at line 76 of file noop.php.
Referenced by WP_oEmbed\__construct(), GV_License_Handler\_get_edd_settings(), _wp_customize_loader_settings(), _wp_menu_item_classes_by_context(), admin_created_user_email(), Custom_Background\admin_page(), WP_Canonical_UnitTestCase\assertCanonical(), WP_Customize_Manager\customize_pane_settings(), WP_Customize_Nav_Menus\export_preview_data(), get_allowed_http_origins(), get_author_posts_url(), get_bloginfo(), WP_Canonical_UnitTestCase\get_canonical(), GravityView_oEmbed\get_handler_regex(), WP_Customize_Manager\get_preview_url(), WP_Customize_Manager\get_return_url(), get_search_form(), get_term_link(), WP_Admin_Bar\initialize(), is_local_attachment(), WP_Customize_Nav_Menus\load_available_items_query(), maybe_add_existing_user_to_blog(), WP_Rewrite\mod_rewrite_rules(), WP\parse_request(), redirect_canonical(), WP_Rewrite\rewrite_rules(), self_link(), WP_Automatic_Updater\send_email(), WP_Customize_Manager\set_preview_url(), Custom_Image_Header\step_1(), Tests_REST_API\test_rest_url_scheme(), url_to_postid(), weblog_ping(), WP_Widget_RSS\widget(), wp_admin_bar_dashboard_view_site_menu(), wp_admin_bar_my_sites_menu(), wp_admin_bar_search_menu(), wp_admin_bar_site_menu(), wp_customize_support_script(), wp_get_archives(), wp_get_popular_importers(), wp_get_referer(), wp_xmlrpc_server\wp_getUsersBlogs(), wp_install_maybe_enable_pretty_permalinks(), wp_list_categories(), wp_nav_menu_item_post_type_meta_box(), wp_page_menu(), wp_redirect_admin_locations(), wp_rel_nofollow_callback(), wp_set_comment_cookies(), wp_update_user(), and wp_version_check().
includes_url ()
Definition at line 81 of file noop.php.
Referenced by _WP_Editors\editor_settings(), GF_Field_FileUpload\get_field_input(), media_upload_form(), print_emoji_detection_script(), GFForms\register_scripts(), translate_smiley(), WP_Widget_RSS\widget(), wlwmanifest_link(), wp_default_scripts(), _WP_Editors\wp_mce_translation(), wp_mime_type_icon(), wp_plupload_default_settings(), and wpview_media_sandbox_styles().
is_admin ()
Definition at line 61 of file noop.php.
Referenced by GravityView_Admin\__construct(), GravityView_Change_Entry_Creator\__construct(), GravityView_Admin_Duplicate_View\__construct(), GravityView_Edit_Entry\__construct(), _custom_header_background_just_in_time(), _post_format_request(), WP_Admin_Bar\_render(), _wp_customize_include(), add_editor_style(), _WP_Editors\editor_js(), _WP_Editors\editor_settings(), GravityView_Admin_Views\filter_pre_get_posts_by_gravityview_form_id(), GravityView_Plugin\frontend_actions(), WP_Theme\get_allowed_on_site(), GF_Field_CreditCard\get_field_input(), get_home_url(), get_pagenum_link(), get_post_class(), WP_Query\get_posts(), get_the_title(), get_theme_mods(), WP\handle_404(), Featured_Content\hide_featured_term(), Featured_Content\hide_the_featured_term(), image_constrain_size_for_editor(), GravityView_Debug_Bar\init(), GFAutoUpgrade\init(), GFAddOn\init(), WP_Query\init_query_flags(), GravityView_frontend\insert_view_in_content(), is_admin_bar_showing(), GravityView_Admin\is_admin_page(), GravityView_Edit_Entry_Admin\load(), load_default_textdomain(), ms_not_installed(), network_home_url(), WP_Query\parse_query(), WP\parse_request(), redirect_canonical(), register_post_type(), register_taxonomy(), remove_editor_styles(), GravityView_Admin_Bar\remove_links(), GravityView_oEmbed\render_handler(), WP_Customize_Widgets\schedule_customize_register(), script_concat_settings(), GravityView_Extension\settings(), WP_Customize_Manager\setup_theme(), GravityView_Shortcode\shortcode(), WP_Customize_Nav_Menu_Item_Setting\sort_wp_get_nav_menu_items(), switch_theme(), Tests_REST_API\test_rest_url_scheme(), twentyeleven_auto_excerpt_more(), twentyeleven_custom_excerpt_more(), twentyten_auto_excerpt_more(), twentyten_custom_excerpt_more(), wp_admin_bar_customize_menu(), wp_admin_bar_dashboard_view_site_menu(), wp_admin_bar_edit_menu(), wp_admin_bar_search_menu(), wp_admin_bar_sidebar_toggle(), wp_admin_bar_site_menu(), wp_auth_check_load(), wp_convert_widget_settings(), wp_default_scripts(), wp_deregister_script(), wp_enqueue_media(), wp_get_attachment_url(), wp_get_nav_menu_items(), wp_get_sidebars_widgets(), wp_heartbeat_settings(), WP_Customize_Manager\wp_loaded(), WP_Customize_Manager\wp_redirect_status(), wp_user_settings(), wp_video_shortcode(), and wp_widget_rss_output().
is_lighttpd_before_150 ()
Definition at line 36 of file noop.php.
site_url ()
Definition at line 66 of file noop.php.
Referenced by wp_xmlrpc_server\blogger_getUsersBlogs(), do_robots(), get_bloginfo(), GravityView_Admin_Views\get_connected_form_links(), GF_Field_FileUpload\get_field_input(), get_the_password_form(), get_theme_root_uri(), GFForms\get_toolbar_menu_items(), WP_Rewrite\mod_rewrite_rules(), newblog_notify_siteadmin(), rsd_link(), spawn_cron(), GravityView_API_Test\test_directory_link(), translate_smiley(), WP_Widget_RSS\widget(), wp_default_scripts(), wp_default_styles(), wp_xmlrpc_server\wp_getUsersBlogs(), wp_login_form(), wp_login_url(), wp_logout_url(), wp_print_request_filesystem_credentials_modal(), wp_redirect_admin_locations(), wp_registration_url(), and wpmu_signup_user_notification().
wp_guess_url ()
Definition at line 86 of file noop.php.
Referenced by populate_options(), wp_default_scripts(), wp_default_styles(), and wp_not_installed().
Variable Documentation
if (! function_exists('json_encode')) () endif
Definition at line 88 of file noop.php.