GravityView: notes.php File Reference
notes.php File Reference
Namespaces
GravityView
GPL2+
Variables
$container_class = (sizeof($notes) > 0 ? 'gv-has-notes' : 'gv-no-notes')
$entry = $gravityview_view->getCurrentEntry()
$entry_slug = GravityView_API::get_entry_slug($entry['id'], $entry)
$gravityview_view = GravityView_View::getInstance()
$notes = GravityView_Entry_Notes::get_notes($entry['id'])
$show_add = ! empty($visibility_settings['add'])
$show_delete = (! empty($visibility_settings['delete']) && GVCommon::has_cap('gravityview_delete_entry_notes'))
$show_notes = $show_notes_logged_out || (! empty($visibility_settings['view']) && GVCommon::has_cap('gravityview_view_entry_notes'))
$show_notes_logged_out = (! empty($visibility_settings['view']) && ! empty($visibility_settings['view_loggedout']))
$strings = GravityView_Field_Notes::strings()
$visibility_settings = $gravityview_view->getCurrentFieldSetting('notes')
if (! GVCommon::has_cap(array('gravityview_view_entry_notes', 'gravityview_add_entry_notes', 'gravityview_delete_entry_notes')) &&! $show_notes_logged_out)
Variable Documentation
$container_class
$container_class = (sizeof($notes) > 0 ? 'gv-has-notes' : 'gv-no-notes')
Definition at line 36 of file notes.php.
Referenced by GravityView_Admin_View_Item\getOutput().
$entry
array $entry = $gravityview_view->getCurrentEntry()
Runs Filter:
gravityview_excerpt_more Modify the "Read more" link used when "Maximum Words" setting is enabled and the output is truncated
Since
1.16.1
Parameters
string $excerpt_more Default: ...
Definition at line 27 of file notes.php.
Referenced by Legacy_Override_Template\__construct(), Entry_Template\__construct(), Field_Template\__construct(), GravityView_Field\_filter_gform_replace_merge_tags(), GravityView_Entry_Approval\_send_notifications(), Entry_Collection\add(), GravityView_Entry_Approval\add_approval_status_updated_note(), GravityView_Admin_ApproveEntries\add_entry_approved_hidden_input(), GravityView_Admin_Bar\add_floaty_icon(), GravityView_Edit_Entry_User_Registration\add_hooks(), GravityView_Cache\add_hooks(), GravityView_Field_Notes\add_note(), GravityView_Change_Entry_Creator\add_select(), GravityView_Field_Total\add_to_blacklist(), GravityView_Entry_Approval\after_submission(), GravityView_Entry_Approval\after_update_entry_update_approved_meta(), View\as_data(), Multi_Entry\as_entry(), Entry\as_entry(), GravityView_Change_Entry_Creator\assign_new_user_to_lead(), GF_Entry\by_id(), gvfield\callback(), gventry\callback(), gravityview\callback(), GravityView_Edit_Entry\check_user_cap_edit_entry(), View\content(), GravityView_Field_Is_Approved\custom_merge_tags(), GravityView_Plugin_Hooks_Gravity_Forms_Coupon\edit_entry_field_blacklist(), GravityView_Field_Product\edit_entry_field_blacklist(), GravityView_Plugin_Hooks_Gravity_Forms_Signature\edit_entry_field_input(), GravityView_Plugin_Hooks_Gravity_Forms_Coupon\edit_entry_field_value(), GravityView_Field_Post_Category\edit_entry_post_category_choices(), GravityView_Cache\entry_added(), View_List_Template\entry_after(), View_List_Template\entry_before(), View_List_Template\entry_class(), View_Table_Template\entry_class(), GravityView_API\entry_create_custom_slug(), GravityView_Cache\entry_created(), GVCommon\entry_has_transaction_data(), GravityView_API\entry_link(), GravityView_API\entry_link_html(), GravityView_Field_Post_Image\explode_value(), GravityView_API\field_class(), GravityView_API\field_label(), GravityView_API\field_value(), GravityView_Plugin_Hooks_Gravity_Forms_Survey\fix_survey_field_value(), Multi_Entry\from_entries(), GF_Entry\from_entry(), GF_Form\from_form(), Entry_Collection\get(), GravityView_Field_Notes\get_add_note_part(), GravityView_Field_Payment_Amount\get_content(), GravityView_Field_Is_Starred\get_content(), GravityView_API\get_custom_entry_slug(), GravityView_Edit_Entry\get_edit_link(), GVCommon\get_entry(), GravityView_API\get_entry_slug(), GravityView_Entry_Approval\get_entry_status(), GravityView_Edit_Entry\get_field_blacklist(), GravityView_Field_FileUpload\get_field_input(), GVCommon\get_form_from_entry_id(), GravityView_Entry_List\get_item_output(), Internal_Field\get_label(), GF_Field\get_label(), Field\get_label(), GravityView_Field_Notes\get_note_emails_array(), GravityView_Entry_List\get_output(), Multi_Entry\get_permalink(), GravityView_GFFormsModel\get_post_field_images(), GravityView_GFFormsModel\get_post_fields(), GravityView_Field_Sequence\get_sequence(), Views_Route\get_sub_item(), Views_Route\get_sub_item_permissions_check(), GravityView_Field_Payment_Date\get_value(), GravityView_Field_Payment_Amount\get_value(), Internal_Field\get_value(), GF_Field\get_value(), Field\get_value(), Field\get_value_filters(), GravityView_View\getCurrentEntry(), GV\Mocks\GravityView_API_field_label(), GV\Mocks\GravityView_API_field_value(), gravityview_field_output(), gravityview_get_field_value(), gv_class(), gv_entry_link(), gv_label(), gv_value(), GravityView_Plugin_Hooks_Pageviews\increment_callback(), Request\is_edit_entry(), Request\is_entry(), GVCommon\matches_operation(), GravityView_Field_Notes\maybe_send_entry_notes(), GravityView_Field_Unsubscribe\maybe_unsubscribe(), GravityView_Field_Unsubscribe\modify_entry_value_unsubscribe(), GravityView_Field_Workflow_Current_Status_Timestamp\modify_entry_value_workflow_current_status_timestamp(), GravityView_Field_Workflow_Step\modify_entry_value_workflow_step(), oEmbed\parse_matches(), Entry_Collection\pluck(), oEmbed\pre_oembed_result(), Views_Route\prepare_entry_for_response(), GravityView_Field_Notes\process_add_note(), Entry_Legacy_Template\render(), oEmbed\render(), Legacy_Override_Template\render(), Field_Template\render(), oEmbed\render_admin(), oEmbed\render_frontend(), oEmbed\render_provider_request(), GravityView_Merge_Tags\replace_entry_link(), GravityView_Merge_Tags\replace_get_variables(), GravityView_Merge_Tags\replace_gv_merge_tags(), GravityView_Field_Created_By\replace_merge_tag(), GravityView_Field_Date_Created\replace_merge_tag(), GravityView_Field_Payment_Amount\replace_merge_tag(), GravityView_Field_Sequence\replace_merge_tag(), GravityView_Field_Is_Fulfilled\replace_merge_tag(), GravityView_Field\replace_merge_tag(), GravityView_API\replace_variables(), GravityView_Merge_Tags\replace_variables(), GravityView_Edit_Entry_User_Registration\restore_display_name(), GVCommon\send_email(), GravityView_Field_Post_Category\set_post_categories(), GravityView_Plugin_Hooks_Gravity_Forms_Coupon\should_hide_coupon_fields(), GravityView_Field_Product\should_hide_product_fields(), GravityView_Field_Custom\show_field_in_edit_entry(), GravityView_Entry_List\skip_entry(), View\template_redirect(), Entry_Table_Template\the_field(), Entry_List_Template\the_field(), View_Table_Template\the_field(), and GravityView_Entry_Approval\update_approved().
$entry_slug
$entry_slug = GravityView_API::get_entry_slug($entry['id'], $entry)
Definition at line 30 of file notes.php.
Referenced by GF_Entry\by_slug(), GravityView_API\entry_link(), GravityView_Field_Notes\get_add_note_part(), GravityView_Delete_Entry\get_delete_link(), GVCommon\get_entry(), GravityView_Field_FileUpload\get_field_input(), GVCommon\get_form_from_entry_id(), GravityView_Field_Notes\get_note_email_fields(), Entry\get_permalink(), gravityview_get_entry(), gravityview_get_form_from_entry_id(), GravityView_Delete_Entry\process_delete(), GravityView_Duplicate_Entry\process_duplicate(), and GravityView_Theme_Hooks_WPML\wpml_ls_filter().
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Definition at line 9 of file notes.php.
$notes
$notes = GravityView_Entry_Notes::get_notes($entry['id'])
Definition at line 28 of file notes.php.
Referenced by GravityView_Entry_Notes\get_notes().
$show_add
$show_add = ! empty($visibility_settings['add'])
Definition at line 32 of file notes.php.
$show_delete
$show_delete = (! empty($visibility_settings['delete']) && GVCommon::has_cap('gravityview_delete_entry_notes'))
Definition at line 33 of file notes.php.
Referenced by GravityView_Field_Notes\display_note().
$show_notes
$show_notes = $show_notes_logged_out || (! empty($visibility_settings['view']) && GVCommon::has_cap('gravityview_view_entry_notes'))
Definition at line 34 of file notes.php.
$show_notes_logged_out
$show_notes_logged_out = (! empty($visibility_settings['view']) && ! empty($visibility_settings['view_loggedout']))
Definition at line 12 of file notes.php.
$strings
$strings = GravityView_Field_Notes::strings()
Definition at line 29 of file notes.php.
Referenced by GravityView_Field_Notes\enqueue_scripts(), GravityView_Field_Notes\get_note_email_fields(), License_Handler\strings(), and GravityView_Field_Notes\strings().
$visibility_settings
$visibility_settings = $gravityview_view->getCurrentFieldSetting('notes')
Definition at line 11 of file notes.php.
Referenced by GravityView_Field_Notes\get_add_note_part().
if
if(! GVCommon::has_cap(array('gravityview_view_entry_notes', 'gravityview_add_entry_notes', 'gravityview_delete_entry_notes')) &&! $show_notes_logged_out)
Definition at line 14 of file notes.php.