GravityView: notification.php File Reference
notification.php File Reference
Data Structures
class GFNotificationTable
Functions
static get_notification ($form, $notification_id)
static notification_edit_page ($form_id, $notification_id)
static notification_page ()
Variables
if(!class_exists('GFForms')) Class GFNotification
Function Documentation
static get_notification ($form, $notification_id) static private
Definition at line 14 of file notification.php.
References $form, and $id.
Referenced by notification_edit_page().
static notification_edit_page ($form_id, $notification_id) static
These variables are used to convenient "wrap" child form settings in the appropriate HTML.
Delete a form notification by ID.
Parameters
mixed $notification_id
mixed $form_id Can pass a form ID or a form object
Returns
mixed
Definition at line 34 of file notification.php.
References $class, $count, $field, $form, $form_id, $i, $min, $url, admin_url(), apply_filters(), checked(), esc_attr(), esc_html__(), esc_url, GFFormsModel\get_entry_meta(), GFFormsModel\get_form_meta(), get_notification(), input, label, null, page_header(), placeholder, remove_query_arg(), GFFormsModel\sanitize_conditional_logic(), sanitize_text_field(), GFFormsModel\save_form_notifications(), selected(), textarea, and GFFormsModel\trim_conditional_logic_values_from_element().
Referenced by notification_page().
static notification_page () static
Definition at line 24 of file notification.php.
References $form_id, and notification_edit_page().
Variable Documentation
if (!class_exists('GFForms')) Class GFNotification
Initial value:
{
    private static $supported_fields = array(
        'checkbox', 'radio', 'select', 'text', 'website', 'textarea', 'email', 'hidden', 'number', 'phone', 'multiselect', 'post_title',
        'post_tags', 'post_custom_field', 'post_content', 'post_excerpt',
    )
Definition at line 7 of file notification.php.