GravityView: options-general.php File Reference
options-general.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$allowed_zones = timezone_identifiers_list()
$check_zone_info = true
$current_offset = get_option('gmt_offset')
$custom = true
_e('Date Format')?></th >< td >< fieldset >< legend class $date_formats = array_unique(apply_filters('date_formats', array(__('F j, Y'), 'Y-m-d', 'm/d/Y', 'd/m/Y')))
Filter the default date formats.
_e('In a few words, explain what this site is about.')?></p ></td ></tr ><?php if(!is_multisite()) else _e('Email Address')?></label ></th >< td >< input name $new_admin_email = get_option('new_admin_email')
$now = localtime(time(), true)
$options_help
$parent_file = 'options-general.php'
_e('Time Format')?></th >< td >< fieldset >< legend class $time_formats = array_unique(apply_filters('time_formats', array(__('g:i a'), 'g:i A', 'H:i')))
Filter the default time formats.
$timezone_format = _x('Y-m-d H:i:s', 'timezone date format')
$title = __('General Settings')
$tzstring = get_option('timezone_string')
endif
foreach ($date_formats as $format)
Variable Documentation
$allowed_zones = timezone_identifiers_list()
Definition at line 182 of file options-general.php.
Referenced by sanitize_option().
$check_zone_info = true
Definition at line 124 of file options-general.php.
$current_offset = get_option('gmt_offset')
Definition at line 121 of file options-general.php.
$custom = true
Definition at line 238 of file options-general.php.
Referenced by _post_type_meta_capabilities(), GravityView_API\entry_create_custom_slug(), GravityView_API\get_entry_slug(), get_post_custom_keys(), get_post_custom_values(), and post_custom().
_e ('Date Format') ?></th> <td> <fieldset><legend class $date_formats = array_unique(apply_filters('date_formats', array(__('F j, Y'), 'Y-m-d', 'm/d/Y', 'd/m/Y')))
Filter the default date formats.
Since
2.7.0
4.0.0 Added ISO date standard YYYY-MM-DD format.
Parameters
array $default_date_formats Array of default date formats.
Definition at line 236 of file options-general.php.
_e ('In a few words, explain what this site is about.')?></p ></td ></tr ><?php if(!is_multisite()) else _e ('Email Address') ?> </label></th> <td><input name $new_admin_email = get_option('new_admin_email')
Definition at line 104 of file options-general.php.
Referenced by update_option_new_admin_email().
$now = localtime(time(), true)
Definition at line 174 of file options-general.php.
Referenced by _wp_upgrade_revisions_of_post(), WP_Date_Query\build_mysql_datetime(), upgrade_210(), GFFormDisplay\validate_form_schedule(), wp_ajax_add_meta(), wp_insert_post(), wp_reschedule_event(), wpmu_activate_signup(), and wpmu_validate_user_signup().
if (!is_multisite()) $options_help
Initial value:
= '<p>' . __('The fields on this screen determine some of the basics of your site setup.') . '</p>' .
    '<p>' . __('Most themes display the site title at the top of every page, in the title bar of the browser, and as the identifying name for syndicated feeds. The tagline is also displayed by many themes.') . '</p>'
Definition at line 25 of file options-general.php.
$parent_file = 'options-general.php'
Definition at line 19 of file options-general.php.
_e ('Time Format') ?></th> <td> <fieldset><legend class $time_formats = array_unique(apply_filters('time_formats', array(__('g:i a'), 'g:i A', 'H:i')))
Filter the default time formats.
Since
2.7.0
Parameters
array $default_time_formats Array of default time formats.
Definition at line 272 of file options-general.php.
$timezone_format = _x('Y-m-d H:i:s', 'timezone date format')
Definition at line 21 of file options-general.php.
Referenced by date_i18n().
$title = __('General Settings')
Definition at line 18 of file options-general.php.
$tzstring = get_option('timezone_string')
Definition at line 122 of file options-general.php.
endif
Definition at line 115 of file options-general.php.
foreach($time_formats as $format)
Definition at line 240 of file options-general.php.