GravityView: options-reading.php File Reference
options-reading.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$parent_file = 'options-general.php'
$title = __('Reading Settings')
s displayed on the front page of your site It can be posts in reverse chronological order(classic blog) or a static fixed page To set static a home you first need to create two< a href="%s"> Pages</a > One will become the front and the other will be where your posts are displayed post new php including the maximum numbers of posts to display and whether to show full text or a summary</p >< p > You must click the Save Changes button at the bottom of the screen for new settings to take effect</p > id site visibility title blog_privacy_selector Site Visibility Search Engine Visibility content< p > You can choose whether or not your site will be crawled by ping and spiders If you want those services to ignore your click the checkbox next to & __ ('When this setting is in effect, a reminder is shown in the At a Glance box of the Dashboard that says,&#8220;Search Engines Discouraged,&#8221;to remind you that your site is not being crawled.'). '</p >'
else __pad3__
else __pad4__
endif
s displayed on the front page of your site It can be posts in reverse chronological order(classic blog) or a static fixed page To set static a home page
s displayed on the front page of your site It can be posts in reverse chronological order(classic blog) or a static fixed page To set static a home you first need to create two< a href="%s"> Pages</a > One will become the front and the other will be where your posts are displayed post new php post_type
s displayed on the front page of your site It can be posts in reverse chronological order(classic blog) or a static fixed page To set static a home you first need to create two< a href="%s"> Pages</a > One will become the front and the other will be where your posts are displayed post new php including the maximum numbers of posts to display and whether to show full text or a summary</p >< p > You must click the Save Changes button at the bottom of the screen for new settings to take effect</p > id site visibility title blog_privacy_selector Site Visibility Search Engine Visibility content< p > You can choose whether or not your site will be crawled by robots
s displayed on the front page of your site It can be posts in reverse chronological order(classic blog) or a static fixed page To set static a home you first need to create two< a href="%s"> Pages</a > One will become the front and the other will be where your posts are displayed post new php including the maximum numbers of posts to display and whether to show full text or a summary</p >< p > You must click the Save Changes button at the bottom of the screen for new settings to take effect</p > id site visibility title blog_privacy_selector Site Visibility Search Engine Visibility content< p > You can choose whether or not your site will be crawled by ping services
s displayed on the front page of your site It can be posts in reverse chronological order(classic blog) or a static fixed page To set static a home you first need to create two< a href="%s"> Pages</a > One will become the front and the other will be where your posts are displayed post new php including the maximum numbers of posts to display and whether to show full text or a summary</p >< p > You must click the Save Changes button at the bottom of the screen for new settings to take effect</p > id site visibility title blog_privacy_selector Site Visibility Search Engine Visibility content< p > You can choose whether or not your site will be crawled by ping and spiders If you want those services to ignore your site
Variable Documentation
$parent_file = 'options-general.php'
Definition at line 16 of file options-reading.php.
$title = __('Reading Settings')
Definition at line 15 of file options-reading.php.
if (!in_array(get_option('blog_charset'), array('utf8', 'utf-8', 'UTF8', 'UTF-8'))) add_settings_field('blog_charset' __('Encoding for pages and feeds')
Definition at line 33 of file options-reading.php.
else __pad3__
Definition at line 66 of file options-reading.php.
else __pad4__
Definition at line 136 of file options-reading.php.
endif
Definition at line 62 of file options-reading.php.
string array A string or an array of capabilities or roles that have access to the app settings page static
Definition at line 24 of file options-reading.php.
Referenced by _default_wp_die_handler(), CreatePlaceholdersUI(), get_confirmation_ui_settings(), GravityView_Welcome\getting_started_screen(), GFEntryDetail\lead_detail_page(), and GFEntryList\leads_page().
s displayed on the front page of your site It can be posts in reverse chronological order (classic blog) or a static fixed page To set static a home you first need to create two<a href="%s"> Pages</a> One will become the front and the other will be where your posts are displayed post new php post_type static
Initial value:
=page') . '</p>' .
        '<p>' . __('You can also control the display of your content in RSS feeds
Definition at line 24 of file options-reading.php.
Referenced by WP_Post\__get(), WP_Post\__isset(), _close_comments_for_old_posts(), WP_Query\get_posts(), WP_Screen\render_per_page_options(), and WP_Screen\render_view_mode().
s displayed on the front page of your site It can be posts in reverse chronological order (classic blog) or a static fixed page To set static a home you first need to create two<a href="%s"> Pages</a> One will become the front and the other will be where your posts are displayed post new php including the maximum numbers of posts to display and whether to show full text or a summary</p><p> You must click the Save Changes button at the bottom of the screen for new settings to take effect</p> id site visibility title blog_privacy_selector Site Visibility Search Engine Visibility content<p> You can choose whether or not your site will be crawled by robots static
Definition at line 24 of file options-reading.php.
s displayed on the front page of your site It can be posts in reverse chronological order (classic blog) or a static fixed page To set static a home you first need to create two<a href="%s"> Pages</a> One will become the front and the other will be where your posts are displayed post new php including the maximum numbers of posts to display and whether to show full text or a summary</p><p> You must click the Save Changes button at the bottom of the screen for new settings to take effect</p> id site visibility title blog_privacy_selector Site Visibility Search Engine Visibility content<p> You can choose whether or not your site will be crawled by ping services static
Definition at line 24 of file options-reading.php.
s displayed on the front page of your site It can be posts in reverse chronological order (classic blog) or a static fixed page To set static a home you first need to create two<a href="%s"> Pages</a> One will become the front and the other will be where your posts are displayed post new php including the maximum numbers of posts to display and whether to show full text or a summary</p><p> You must click the Save Changes button at the bottom of the screen for new settings to take effect</p> id site visibility title blog_privacy_selector Site Visibility Search Engine Visibility content<p> You can choose whether or not your site will be crawled by ping and spiders If you want those services to ignore your site static
Definition at line 24 of file options-reading.php.
Referenced by export_wp(), GravityView_Welcome\getting_started_screen(), print_embed_styles(), and wpmu_signup_stylesheet().