GravityView: option.php File Reference
option.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
add_network_option ($network_id, $option, $value)
Add a new network option.
add_option ($option, $value= '', $deprecated= '', $autoload= 'yes')
Add a new option.
add_site_option ($option, $value)
Add a new option for the current network.
delete_all_user_settings ()
Delete the user settings of the current user.
delete_network_option ($network_id, $option)
Removes a network option by name.
delete_option ($option)
Removes option by name.
delete_site_option ($option)
Removes a option by name for the current network.
delete_site_transient ($transient)
Delete a site transient.
delete_transient ($transient)
Delete a transient.
delete_user_setting ($names)
Delete user interface settings.
form_option ($option)
Print option value after sanitizing for forms.
get_all_user_settings ()
Retrieve all user interface settings.
get_network_option ($network_id, $option, $default=false)
Retrieve a network's option value based on the option name.
get_option ($option, $default=false)
Retrieve option value based on name of option.
get_site_option ($option, $default=false, $deprecated=true)
Retrieve an option value for the current network based on name of option.
get_site_transient ($transient)
Get the value of a site transient.
get_transient ($transient)
Get the value of a transient.
get_user_setting ($name, $default=false)
Retrieve user interface setting value based on setting name.
set_site_transient ($transient, $value, $expiration=0)
Set/update the value of a site transient.
set_transient ($transient, $value, $expiration=0)
Set/update the value of a transient.
set_user_setting ($name, $value)
Add or update user interface setting.
update_network_option ($network_id, $option, $value)
Update the value of a network option that was already added.
update_option ($option, $value, $autoload=null)
Update the value of an option that was already added.
update_site_option ($option, $value)
Update the value of an option that was already added for the current network.
wp_load_alloptions ()
Loads and caches all autoloaded options, if available or all options.
wp_load_core_site_options ($site_id=null)
Loads and caches certain often requested site options if is_multisite() and a persistent cache is not being used.
wp_protect_special_option ($option)
Protect WordPress special option from being modified.
wp_set_all_user_settings ($user_settings)
Private.
wp_user_settings ()
Saves and restores user interface settings stored in a cookie.
Function Documentation
add_network_option ($network_id, $option, $value)
Add a new network option.
Existing options will not be updated.
Since
4.4.0
See also
add_option()
wpdb $wpdb object $current_site
Parameters
int $network_id ID of the network. Can be null to default to the current network ID.
string $option Name of option to add. Expected to not be SQL-escaped.
mixed $value Option value, can be anything. Expected to not be SQL-escaped.
Returns
bool False if option was not added and true if option was added.
Filter the value of a specific network option before it is added.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.9.0 As 'pre_add_site_option_' . $key
3.0.0
4.4.0 The $option parameter was added
Parameters
mixed $value Value of network option.
string $option Option name.
Fires after a specific network option has been successfully added.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.9.0 As "add_site_option_{$key}"
3.0.0
Parameters
string $option Name of the network option.
mixed $value Value of the network option.
Fires after a network option has been successfully added.
Since
3.0.0
Parameters
string $option Name of the network option.
mixed $value Value of the network option.
Definition at line 1193 of file option.php.
References $current_site, $option, $value, $wpdb, add_option(), apply_filters(), do_action(), get_network_option(), is_multisite(), maybe_serialize(), sanitize_option(), wp_cache_get(), wp_cache_set(), and wp_protect_special_option().
Referenced by add_site_option(), and update_network_option().
add_option ($option, $value = '', $deprecated = '', $autoload = 'yes')
Add a new option.
You do not need to serialize values. If the value needs to be serialized, then it will be serialized before it is inserted into the database. Remember, resources can not be serialized or added as an option.
You can create options without values and then update the values later. Existing options will not be updated and checks are performed to ensure that you aren't adding a protected WordPress option. Care should be taken to not name options the same as the ones which are protected.
Since
1.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $option Name of option to add. Expected to not be SQL-escaped.
mixed $value Optional. Option value. Must be serializable if non-scalar. Expected to not be SQL-escaped.
string $deprecated Optional. Description. Not used anymore.
string | bool $autoload Optional. Whether to load the option when WordPress starts up. Default is enabled. Accepts 'no' to disable for legacy reasons.
Returns
bool False if option was not added and true if option was added.
This filter is documented in wp-includes/option.php
Fires before an option is added.
Since
2.9.0
Parameters
string $option Name of the option to add.
mixed $value Value of the option.
Fires after a specific option has been added.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.5.0 As "add_option_{$name}"
3.0.0
Parameters
string $option Name of the option to add.
mixed $value Value of the option.
Fires after an option has been added.
Since
2.9.0
Parameters
string $option Name of the added option.
mixed $value Value of the option.
Definition at line 398 of file option.php.
References $deprecated, $option, $value, $wpdb, _deprecated_argument(), apply_filters(), do_action(), get_option(), maybe_serialize(), sanitize_option(), wp_cache_get(), wp_cache_set(), wp_installing(), wp_load_alloptions(), and wp_protect_special_option().
Referenced by add_blog_option(), add_network_option(), set_transient(), switch_theme(), update_option(), upgrade_110(), upgrade_340(), and wpmu_create_blog().
add_site_option ($option, $value)
Add a new option for the current network.
Existing options will not be updated. Note that prior to 3.3 this wasn't the case.
Since
2.8.0
4.4.0 Modified into wrapper for add_network_option()
See also
add_network_option()
Parameters
string $option Name of option to add. Expected to not be SQL-escaped.
mixed $value Option value, can be anything. Expected to not be SQL-escaped.
Returns
bool False if the option was not added. True if the option was added.
Definition at line 1026 of file option.php.
References $option, $value, add_network_option(), and null.
Referenced by set_site_transient(), upgrade_300(), wpmu_validate_blog_signup(), and wpmu_validate_user_signup().
delete_all_user_settings ()
Delete the user settings of the current user.
Since
2.7.0
Definition at line 985 of file option.php.
References $user_id, get_current_user_id(), SITECOOKIEPATH, and update_user_option().
delete_network_option ($network_id, $option)
Removes a network option by name.
Since
4.4.0
See also
delete_option()
wpdb $wpdb object $current_site
Parameters
int $network_id ID of the network. Can be null to default to the current network ID.
string $option Name of option to remove. Expected to not be SQL-escaped.
Returns
bool True, if succeed. False, if failure.
Fires immediately before a specific network option is deleted.
The dynamic portion of the hook name, $option, refers to the option name.
Since
3.0.0
4.4.0 The $option parameter was added
Parameters
string $option Option name.
Fires after a specific network option has been deleted.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.9.0 As "delete_site_option_{$key}"
3.0.0
Parameters
string $option Name of the network option.
Fires after a network option has been deleted.
Since
3.0.0
Parameters
string $option Name of the network option.
Definition at line 1302 of file option.php.
References $current_site, $option, $wpdb, delete_option(), do_action(), is_multisite(), and wp_cache_delete().
Referenced by delete_site_option().
delete_option ($option)
Removes option by name.
Prevents removal of protected WordPress options.
Since
1.2.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $option Name of option to remove. Expected to not be SQL-escaped.
Returns
bool True, if option is successfully deleted. False on failure.
Fires immediately before an option is deleted.
Since
2.9.0
Parameters
string $option Name of the option to delete.
Fires after a specific option has been deleted.
The dynamic portion of the hook name, $option, refers to the option name.
Since
3.0.0
Parameters
string $option Name of the deleted option.
Fires after an option has been deleted.
Since
2.9.0
Parameters
string $option Name of the deleted option.
Definition at line 491 of file option.php.
References $option, $wpdb, do_action(), wp_cache_delete(), wp_cache_set(), wp_installing(), wp_load_alloptions(), and wp_protect_special_option().
Referenced by _reset_front_page_settings_for_post(), _wp_batch_split_terms(), _wp_upgrade_revisions_of_post(), clean_term_cache(), GF_Installation_Wizard\complete_installation(), WP_Site_Icon\delete_attachment_data(), delete_blog_option(), delete_network_option(), GravityView_Uninstall\delete_options(), delete_transient(), GF_Installation_Wizard_Step\flush_values(), WP_Theme\get_allowed_on_site(), get_theme_mods(), get_transient(), GV_Unit_Tests_Bootstrap\load_rest_api(), maybe_add_existing_user_to_blog(), GravityView_Migrate\migrate_redux_settings(), populate_options(), Gravity_Api\purge_site_credentials(), remove_theme_mods(), rest_api_deactivation(), WP_Automatic_Updater\run(), GFFormsModel\save_key(), send_confirmation_on_profile_email(), set_transient(), GFSettings\settings_uninstall_page(), switch_theme(), Twenty_Eleven_Ephemera_Widget\update(), update_core(), update_home_siteurl(), and upgrade_340().
delete_site_option ($option)
Removes a option by name for the current network.
Since
2.8.0
4.4.0 Modified into wrapper for delete_network_option()
See also
delete_network_option()
Parameters
string $option Name of option to remove. Expected to not be SQL-escaped.
Returns
bool True, if succeed. False, if failure.
Definition at line 1041 of file option.php.
References $option, delete_network_option(), and null.
Referenced by delete_site_transient(), get_site_transient(), update_core(), and upgrade_network().
delete_site_transient ($transient)
Delete a site transient.
Since
2.9.0
Parameters
string $transient Transient name. Expected to not be SQL-escaped.
Returns
bool True if successful, false otherwise
Fires immediately before a specific site transient is deleted.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
3.0.0
Parameters
string $transient Transient name.
Fires after a transient is deleted.
Since
3.0.0
Parameters
string $transient Deleted transient name.
Definition at line 1488 of file option.php.
References $option, delete_site_option(), do_action(), wp_cache_delete(), and wp_using_ext_object_cache().
Referenced by GravityView_Uninstall\delete_options(), delete_theme(), GravityView_Support_Port\flush_related_plugins_transient(), install_plugin_install_status(), update_core(), Core_Upgrader\upgrade(), wp_clean_plugins_cache(), wp_clean_themes_cache(), and wp_clean_update_cache().
delete_transient ($transient)
Delete a transient.
Since
2.8.0
Parameters
string $transient Transient name. Expected to not be SQL-escaped.
Returns
bool true if successful, false otherwise
Fires immediately before a specific transient is deleted.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
3.0.0
Parameters
string $transient Transient name.
Fires after a transient is deleted.
Since
3.0.0
Parameters
string $transient Deleted transient name.
Definition at line 560 of file option.php.
References $option, delete_option(), do_action(), wp_cache_delete(), and wp_using_ext_object_cache().
Referenced by __clear_multi_author_cache(), GV_License_Handler\_license_get_remote_response(), _wp_handle_upload(), GravityView_Plugin\activate(), GFFormsModel\copy_post_image(), GravityView_Uninstall\delete_options(), GravityView_Admin_Notices\flush_dismissed_notices(), get_settings_errors(), GravityView_Welcome\getting_started_screen(), GFForms\setup(), twentyfifteen_category_transient_flusher(), twentyfourteen_category_transient_flusher(), WP_Feed_Cache_Transient\unlink(), Featured_Content\validate_settings(), wp_delete_attachment(), and wp_maybe_generate_attachment_metadata().
delete_user_setting ($names)
Delete user interface settings.
Deleting settings would reset them to the defaults. This function has to be used before any output has started as it calls setcookie().
Since
2.7.0
Parameters
string $names The name or array of names of the setting to be deleted.
Returns
bool|void true if deleted successfully/false if not.
Definition at line 877 of file option.php.
References $name, get_all_user_settings(), and wp_set_all_user_settings().
Referenced by default_password_nag_edit_user(), and default_password_nag_handler().
form_option ($option)
Print option value after sanitizing for forms.
Since
1.5.0
Parameters
string $option Option name.
Definition at line 161 of file option.php.
References $option, esc_attr(), and get_option().
get_all_user_settings ()
Retrieve all user interface settings.
Since
2.7.0
array $_updated_user_settings
Returns
array the last saved user settings or empty array.
Definition at line 909 of file option.php.
References $_COOKIE, $option, $user_id, get_current_user_id(), and get_user_option().
Referenced by delete_user_setting(), get_user_setting(), and set_user_setting().
get_network_option ($network_id, $option, $default = false)
Retrieve a network's option value based on the option name.
Since
4.4.0
See also
get_option()
wpdb $wpdb object $current_site
Parameters
int $network_id ID of the network. Can be null to default to the current network ID.
string $option Name of option to retrieve. Expected to not be SQL-escaped.
mixed $default Optional. Value to return if the option doesn't exist. Default false.
Returns
mixed Value set for the option.
Filter an existing network option before it is retrieved.
The dynamic portion of the hook name, $option, refers to the option name.
Passing a truthy value to the filter will effectively short-circuit retrieval, returning the passed value instead.
Since
2.9.0 As 'pre_site_option_' . $key
3.0.0
4.4.0 The $option parameter was added
Parameters
mixed $pre_option The default value to return if the option does not exist.
string $option Option name.
Filter a specific default network option.
The dynamic portion of the hook name, $option, refers to the option name.
Since
3.4.0
4.4.0 The $option parameter was added.
Parameters
mixed $default The value to return if the site option does not exist in the database.
string $option Option name.
This filter is documented in wp-includes/option.php
This filter is documented in wp-includes/option.php
Filter the value of an existing network option.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.9.0 As 'site_option_' . $key
3.0.0
4.4.0 The $option parameter was added
Parameters
mixed $value Value of network option.
string $option Option name.
Definition at line 1076 of file option.php.
References $current_site, $default, $option, $value, $wpdb, apply_filters(), get_option(), is_multisite(), maybe_unserialize(), wp_cache_get(), and wp_cache_set().
Referenced by WP_Network\_set_site_name(), add_network_option(), get_site_option(), and update_network_option().
get_option ($option, $default = false)
Retrieve option value based on name of option.
If the option does not exist or does not have a value, then the return value will be false. This is useful to check whether you need to install an option and is commonly used during installation of plugin options and to test whether upgrading is required.
If the option was serialized then it will be unserialized when it is returned.
Any scalar values will be returned as strings. You may coerce the return type of a given option by registering a 'option_{$option}' filter callback.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $option Name of option to retrieve. Expected to not be SQL-escaped.
mixed $default Optional. Default value to return if the option does not exist.
Returns
mixed Value set for the option.
Filter the value of an existing option before it is retrieved.
The dynamic portion of the hook name, $option, refers to the option name.
Passing a truthy value to the filter will short-circuit retrieving the option value, returning the passed value instead.
Since
1.5.0
4.4.0 The $option parameter was added.
Parameters
bool | mixed $pre_option Value to return instead of the option value. Default false to skip it.
string $option Option name.
Filter the default value for an option.
The dynamic portion of the hook name, $option, refers to the option name.
Since
3.4.0
4.4.0 The $option parameter was added.
Parameters
mixed $default The default value to return if the option does not exist in the database.
string $option Option name.
This filter is documented in wp-includes/option.php
This filter is documented in wp-includes/option.php
Filter the value of an existing option.
The dynamic portion of the hook name, $option, refers to the option name.
Since
1.5.0 As 'option_' . $setting
3.0.0
4.4.0 The $option parameter was added.
Parameters
mixed $value Value of the option. If stored serialized, it will be unserialized prior to being returned.
string $option Option name.
Definition at line 30 of file option.php.
References $default, $option, $value, $wpdb, apply_filters(), maybe_unserialize(), untrailingslashit(), wp_cache_add(), wp_cache_get(), wp_cache_set(), wp_installing(), and wp_load_alloptions().
Referenced by add_option(), form_option(), get_network_option(), get_transient(), set_transient(), and update_option().
get_site_option ($option, $default = false, $deprecated = true)
Retrieve an option value for the current network based on name of option.
Since
2.8.0
4.4.0 The $use_cache parameter was deprecated.
4.4.0 Modified into wrapper for get_network_option()
See also
get_network_option()
Parameters
string $option Name of option to retrieve. Expected to not be SQL-escaped.
mixed $default Optional value to return if option doesn't exist. Default false.
bool $deprecated Whether to use cache. Multisite only. Always set to true.
Returns
mixed Value set for the option.
Definition at line 1008 of file option.php.
References $default, $option, get_network_option(), and null.
Referenced by activate_plugin(), WP_Automatic_Updater\after_core_update(), check_upload_mimes(), check_upload_size(), deactivate_plugins(), GFFormsModel\delete_physical_file(), dismiss_core_update(), WP_Theme\get_allowed_on_network(), get_blog_count(), get_core_updates(), get_dashboard_blog(), get_locale(), get_site_transient(), get_space_allowed(), get_super_admins(), get_upload_space_available(), get_user_count(), global_terms_enabled(), grant_super_admin(), install_blog(), is_email_address_unsafe(), is_plugin_active_for_network(), is_upload_space_available(), maintenance_nag(), map_meta_cap(), ms_site_check(), ms_upload_constants(), network_step2(), newblog_notify_siteadmin(), newuser_notify_siteadmin(), WP_Themes_List_Table\no_items(), populate_network(), WP_Plugins_List_Table\prepare_items(), revoke_super_admin(), script_concat_settings(), send_confirmation_on_profile_email(), WP_Automatic_Updater\send_core_update_notification_email(), WP_Automatic_Updater\send_debug_email(), WP_Automatic_Updater\send_email(), set_site_transient(), Core_Upgrader\should_update_to_version(), site_admin_notice(), undismiss_core_update(), update_option_new_admin_email(), upgrade_300(), upgrade_network(), upload_is_file_too_big(), upload_is_user_over_quota(), upload_size_limit_filter(), users_can_register_signup_filter(), validate_active_plugins(), wp_cookie_constants(), wp_get_active_network_plugins(), wp_get_user_contact_methods(), wp_upload_dir(), wp_version_check(), wpmu_create_blog(), wpmu_delete_blog(), wpmu_signup_blog_notification(), wpmu_signup_user_notification(), wpmu_validate_blog_signup(), wpmu_validate_user_signup(), wpmu_welcome_notification(), and wpmu_welcome_user_notification().
get_site_transient ($transient)
Get the value of a site transient.
If the transient does not exist, does not have a value, or has expired, then the return value will be false.
Since
2.9.0
See also
get_transient()
Parameters
string $transient Transient name. Expected to not be SQL-escaped.
Returns
mixed Value of transient.
Filter the value of an existing site transient.
The dynamic portion of the hook name, $transient, refers to the transient name.
Passing a truthy value to the filter will effectively short-circuit retrieval, returning the passed value instead.
Since
2.9.0
4.4.0 The $transient parameter was added.
Parameters
mixed $pre_site_transient The default value to return if the site transient does not exist. Any value other than false will short-circuit the retrieval of the transient, and return the returned value.
string $transient Transient name.
Filter the value of an existing site transient.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
2.9.0
4.4.0 The $transient parameter was added.
Parameters
mixed $value Value of site transient.
string $transient Transient name.
Definition at line 1538 of file option.php.
References $value, apply_filters(), delete_site_option(), get_site_option(), wp_cache_get(), and wp_using_ext_object_cache().
Referenced by GravityView_Uninstall_Test\_check_deleted_options(), _maybe_update_core(), _maybe_update_plugins(), _maybe_update_themes(), Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), delete_plugins(), find_core_auto_update(), find_core_update(), get_core_updates(), WP_Plugin_Install_List_Table\get_installed_plugin_slugs(), get_plugin_updates(), GravityView_Support_Port\get_related_plugins_and_extensions(), get_theme_feature_list(), get_theme_roots(), get_theme_update_available(), get_theme_updates(), install_plugin_install_status(), install_popular_tags(), WP_Plugins_List_Table\prepare_items(), WP_MS_Themes_List_Table\prepare_items(), WP_Automatic_Updater\run(), search_theme_directories(), Plugin_Upgrader\upgrade(), Theme_Upgrader\upgrade(), wp_credits(), wp_get_available_translations(), wp_get_popular_importers(), wp_get_translation_updates(), wp_get_update_data(), wp_plugin_update_row(), wp_plugin_update_rows(), wp_prepare_themes_for_js(), wp_theme_update_row(), wp_theme_update_rows(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
get_transient ($transient)
Get the value of a transient.
If the transient does not exist, does not have a value, or has expired, then the return value will be false.
Since
2.8.0
Parameters
string $transient Transient name. Expected to not be SQL-escaped.
Returns
mixed Value of transient.
Filter the value of an existing transient.
The dynamic portion of the hook name, $transient, refers to the transient name.
Passing a truthy value to the filter will effectively short-circuit retrieval of the transient, returning the passed value instead.
Since
2.8.0
4.4.0 The $transient parameter was added
Parameters
mixed $pre_transient The default value to return if the transient does not exist. Any value other than false will short-circuit the retrieval of the transient, and return the returned value.
string $transient Transient name.
Filter an existing transient's value.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
2.8.0
4.4.0 The $transient parameter was added
Parameters
mixed $value Value of transient.
string $transient Transient name.
Definition at line 609 of file option.php.
References $value, apply_filters(), delete_option(), get_option(), wp_cache_get(), wp_installing(), wp_load_alloptions(), and wp_using_ext_object_cache().
Referenced by GravityView_Uninstall_Test\_check_deleted_options(), GravityView_Admin_Notices\admin_notice(), RSSCache\check_cache(), GravityView_Admin_Notices\dismiss_notice(), GravityView_Cache\get(), RSSCache\get(), get_dirsize(), Featured_Content\get_featured_post_ids(), get_settings_errors(), GravityView_Welcome\getting_started_screen(), install_themes_feature_list(), is_multi_author(), WP_Feed_Cache_Transient\load(), WP_Feed_Cache_Transient\mtime(), spawn_cron(), twentyfifteen_categorized_blog(), twentyfourteen_categorized_blog(), and wp_maybe_generate_attachment_metadata().
get_user_setting ($name, $default = false)
Retrieve user interface setting value based on setting name.
Since
2.7.0
Parameters
string $name The name of the setting.
string $default Optional default value to return when $name is not set.
Returns
mixed the last saved user setting or the default value/false if it doesn't exist.
Definition at line 837 of file option.php.
References $default, $name, and get_all_user_settings().
Referenced by default_password_nag_handler(), image_align_input_fields(), image_link_input_fields(), image_size_input_fields(), media_upload_library_form(), media_upload_max_image_resize(), media_upload_type_form(), media_upload_type_url_form(), _WP_Editors\parse_settings(), WP_Posts_List_Table\prepare_items(), WP_Screen\show_screen_options(), wp_default_editor(), and _WP_Editors\wp_link_dialog().
set_site_transient ($transient, $value, $expiration = 0)
Set/update the value of a site transient.
You do not need to serialize values, if the value needs to be serialize, then it will be serialized before it is set.
Since
2.9.0
See also
set_transient()
Parameters
string $transient Transient name. Expected to not be SQL-escaped. Must be 40 characters or fewer in length.
mixed $value Transient value. Expected to not be SQL-escaped.
int $expiration Optional. Time until expiration in seconds. Default 0 (no expiration).
Returns
bool False if value was not set and true if value was set.
Filter the value of a specific site transient before it is set.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
3.0.0
4.4.0 The $transient parameter was added.
Parameters
mixed $value New value of site transient.
string $transient Transient name.
Filter the expiration for a site transient before its value is set.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
4.4.0
Parameters
int $expiration Time until expiration in seconds. Use 0 for no expiration.
mixed $value New value of site transient.
string $transient Transient name.
Fires after the value for a specific site transient has been set.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
3.0.0
4.4.0 The $transient parameter was added
Parameters
mixed $value Site transient value.
int $expiration Time until expiration in seconds.
string $transient Transient name.
Fires after the value for a site transient has been set.
Since
3.0.0
Parameters
string $transient The name of the site transient.
mixed $value Site transient value.
int $expiration Time until expiration in seconds.
Definition at line 1611 of file option.php.
References $option, $value, add_site_option(), apply_filters(), do_action(), get_site_option(), update_site_option(), wp_cache_set(), and wp_using_ext_object_cache().
Referenced by GravityView_Uninstall_Test\_set_up_expected_options(), delete_plugins(), GravityView_Support_Port\get_related_plugins_and_extensions(), get_theme_feature_list(), install_popular_tags(), search_theme_directories(), GFAutoUpgrade\set_version_info(), wp_credits(), wp_get_available_translations(), wp_get_popular_importers(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
set_transient ($transient, $value, $expiration = 0)
Set/update the value of a transient.
You do not need to serialize values. If the value needs to be serialized, then it will be serialized before it is set.
Since
2.8.0
Parameters
string $transient Transient name. Expected to not be SQL-escaped. Must be 172 characters or fewer in length.
mixed $value Transient value. Must be serializable if non-scalar. Expected to not be SQL-escaped.
int $expiration Optional. Time until expiration in seconds. Default 0 (no expiration).
Returns
bool False if value was not set and true if value was set.
Filter a specific transient before its value is set.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
3.0.0
4.2.0 The $expiration parameter was added.
4.4.0 The $transient parameter was added.
Parameters
mixed $value New value of transient.
int $expiration Time until expiration in seconds.
string $transient Transient name.
Filter the expiration for a transient before its value is set.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
4.4.0
Parameters
int $expiration Time until expiration in seconds. Use 0 for no expiration.
mixed $value New value of transient.
string $transient Transient name.
Fires after the value for a specific transient has been set.
The dynamic portion of the hook name, $transient, refers to the transient name.
Since
3.0.0
3.6.0 The $value and $expiration parameters were added.
4.4.0 The $transient parameter was added.
Parameters
mixed $value Transient value.
int $expiration Time until expiration in seconds.
string $transient The name of the transient.
Fires after the value for a transient has been set.
Since
3.0.0
3.6.0 The $value and $expiration parameters were added.
Parameters
string $transient The name of the transient.
mixed $value Transient value.
int $expiration Time until expiration in seconds.
Definition at line 682 of file option.php.
References $update, $value, add_option(), apply_filters(), delete_option(), do_action(), get_option(), update_option(), wp_cache_set(), and wp_using_ext_object_cache().
Referenced by GravityView_Uninstall_Test\_set_up_expected_options(), GravityView_Plugin\activate(), GravityView_Admin_Notices\dismiss_notice(), get_dirsize(), Featured_Content\get_featured_post_ids(), install_themes_feature_list(), is_multi_author(), GV_License_Handler\license_call(), WP_Plugins_List_Table\prepare_items(), WP_Feed_Cache_Transient\save(), GravityView_Cache\set(), RSSCache\set(), GFAutoUpgrade\set_version_info(), spawn_cron(), WP_Feed_Cache_Transient\touch(), twentyfifteen_categorized_blog(), twentyfourteen_categorized_blog(), and wp_maybe_generate_attachment_metadata().
set_user_setting ($name, $value)
Add or update user interface setting.
Both $name and $value can contain only ASCII letters, numbers and underscores. This function has to be used before any output has started as it calls setcookie().
Since
2.8.0
Parameters
string $name The name of the setting.
string $value The value for the setting.
Returns
bool|void true if set successfully/false if not.
Definition at line 855 of file option.php.
References $name, $value, get_all_user_settings(), and wp_set_all_user_settings().
Referenced by WP_Posts_List_Table\prepare_items().
update_network_option ($network_id, $option, $value)
Update the value of a network option that was already added.
Since
4.4.0
See also
update_option()
wpdb $wpdb object $current_site
Parameters
int $network_id ID of the network. Can be null to default to the current network ID.
string $option Name of option. Expected to not be SQL-escaped.
mixed $value Option value. Expected to not be SQL-escaped.
Returns
bool False if value was not updated and true if value was updated.
Filter a specific network option before its value is updated.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.9.0 As 'pre_update_site_option_' . $key
3.0.0
4.4.0 The $option parameter was added
Parameters
mixed $value New value of the network option.
mixed $old_value Old value of the network option.
string $option Option name.
Fires after the value of a specific network option has been successfully updated.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.9.0 As "update_site_option_{$key}"
3.0.0
Parameters
string $option Name of the network option.
mixed $value Current value of the network option.
mixed $old_value Old value of the network option.
Fires after the value of a network option has been successfully updated.
Since
3.0.0
Parameters
string $option Name of the network option.
mixed $value Current value of the network option.
mixed $old_value Old value of the network option.
Definition at line 1385 of file option.php.
References $current_site, $option, $value, $wpdb, add_network_option(), apply_filters(), do_action(), get_network_option(), is_multisite(), maybe_serialize(), sanitize_option(), update_option(), wp_cache_get(), wp_cache_set(), and wp_protect_special_option().
Referenced by update_site_option().
update_option ($option, $value, $autoload = null)
Update the value of an option that was already added.
You do not need to serialize values. If the value needs to be serialized, then it will be serialized before it is inserted into the database. Remember, resources can not be serialized or added as an option.
If the option does not exist, then the option will be added with the option value, with an $autoload value of 'yes'.
Since
1.0.0
4.2.0 The $autoload parameter was added.
wpdb $wpdb WordPress database abstraction object.
Parameters
string $option Option name. Expected to not be SQL-escaped.
mixed $value Option value. Must be serializable if non-scalar. Expected to not be SQL-escaped.
string | bool $autoload Optional. Whether to load the option when WordPress starts up. For existing options, $autoload can only be updated using update_option() if $value is also changed. Accepts 'yes'|true to enable or 'no'|false to disable. For non-existent options, the default value is 'yes'. Default null.
Returns
bool False if value was not updated and true if value was updated.
Filter a specific option before its value is (maybe) serialized and updated.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.6.0
4.4.0 The $option parameter was added.
Parameters
mixed $value The new, unserialized option value.
mixed $old_value The old option value.
string $option Option name.
Filter an option before its value is (maybe) serialized and updated.
Since
3.9.0
Parameters
mixed $value The new, unserialized option value.
string $option Name of the option.
mixed $old_value The old option value.
This filter is documented in wp-includes/option.php
Fires immediately before an option value is updated.
Since
2.9.0
Parameters
string $option Name of the option to update.
mixed $old_value The old option value.
mixed $value The new option value.
Fires after the value of a specific option has been successfully updated.
The dynamic portion of the hook name, $option, refers to the option name.
Since
2.0.1
4.4.0 The $option parameter was added.
Parameters
mixed $old_value The old option value.
mixed $value The new option value.
string $option Option name.
Fires after the value of an option has been successfully updated.
Since
2.9.0
Parameters
string $option Name of the updated option.
mixed $old_value The old option value.
mixed $value The new option value.
Definition at line 253 of file option.php.
References $option, $value, $wpdb, add_option(), apply_filters(), do_action(), get_option(), maybe_serialize(), null, sanitize_option(), wp_cache_get(), wp_cache_set(), wp_installing(), wp_load_alloptions(), and wp_protect_special_option().
Referenced by _get_term_hierarchy(), _reset_front_page_settings_for_post(), _set_cron_array(), _set_default_permalink_structure_for_tests(), GravityView_Uninstall_Test\_set_up_expected_options(), GravityView_Uninstall_Test\_set_up_gravityview_settings(), _split_shared_term(), _upgrade_cron_array(), _wp_batch_split_terms(), _wp_check_split_default_terms(), _wp_upgrade_revisions_of_post(), GravityView_Plugin\activate(), activate_plugin(), WP_Roles\add_cap(), GravityView_Roles_Capabilities\add_caps(), WP_Roles\add_role(), Gravity_Api\add_site(), GravityView_Cache\blacklist_add(), GravityView_Cache\blacklist_remove(), check_theme_switched(), GFForms\dashboard_dismiss_upgrade(), deactivate_plugins(), GFFormsModel\delete_custom_choice(), Featured_Content\delete_post_tag(), GFForms\do_self_healing(), WP_Rewrite\flush_rules(), WP_Theme\get_allowed_on_site(), get_theme_mods(), GravityView_Welcome\getting_started_screen(), global_terms(), GF_Installation_Wizard_Step_License_Key\install(), GF_Installation_Wizard_Step_Settings\install(), GF_Installation_Wizard_Step_Background_Updates\install(), install_blog(), GFForms\load_first(), GV_Unit_Tests_Bootstrap\load_rest_api(), make_site_theme(), maybe_disable_automattic_widgets(), maybe_disable_link_manager(), GFForms\maybe_import_forms(), GFForms\maybe_import_theme_forms(), GFForms\maybe_populate_keys(), populate_options(), WP_Plugins_List_Table\prepare_items(), register_uninstall_hook(), WP_Roles\remove_cap(), WP_Roles\remove_role(), remove_theme_mod(), request_filesystem_credentials(), rest_api_activation(), rest_api_maybe_flush_rewrites(), WP_Automatic_Updater\run(), WP_Customize_Manager\save(), GFFormsModel\save_custom_choice(), GFFormsModel\save_key(), WP_Widget\save_settings(), send_confirmation_on_profile_email(), WP_Rewrite\set_category_base(), WP_Rewrite\set_permalink_structure(), WP_Customize_Setting\set_root_value(), WP_Rewrite\set_tag_base(), set_theme_mod(), set_transient(), GFSettings\settings_uninstall_page(), WP_Canonical_UnitTestCase\setUp(), GFFeedAddOn\setup(), GFPaymentAddOn\setup(), GFAddOn\setup(), GFForms\setup(), stick_post(), switch_theme(), Tests_REST_API\test_rest_url_generation(), Tests_REST_API\test_rest_url_scheme(), uninstall_plugin(), unstick_post(), GF_Installation_Wizard_Step\update(), WP_Customize_Nav_Menu_Setting\update(), GravityView_Settings\update_app_settings(), update_blog_details(), update_blog_option(), update_network_option(), update_option_new_admin_email(), update_posts_count(), update_recently_edited(), GravityView_Migrate\update_search_on_views(), upgrade_130(), upgrade_230(), upgrade_280(), upgrade_290(), upgrade_330(), upgrade_350(), upgrade_400(), upgrade_430(), upgrade_all(), validate_active_plugins(), wp_ajax_delete_inactive_widgets(), wp_convert_widget_settings(), wp_nav_menu_update_menu_items(), WP_Rewrite\wp_rewrite_rules(), wp_set_sidebars_widgets(), wp_xmlrpc_server\wp_setOptions(), and wpmu_create_blog().
update_site_option ($option, $value)
Update the value of an option that was already added for the current network.
Since
2.8.0
4.4.0 Modified into wrapper for update_network_option()
See also
update_network_option()
Parameters
string $option Name of option. Expected to not be SQL-escaped.
mixed $value Option value. Expected to not be SQL-escaped.
Returns
bool False if value was not updated. True if value was updated.
Definition at line 1057 of file option.php.
References $option, $value, null, and update_network_option().
Referenced by activate_plugin(), WP_Automatic_Updater\after_core_update(), deactivate_plugins(), dismiss_core_update(), grant_super_admin(), WP_Plugins_List_Table\prepare_items(), revoke_super_admin(), WP_Automatic_Updater\send_email(), set_site_transient(), undismiss_core_update(), upgrade_network(), welcome_user_msg_filter(), wp_ajax_wp_compression_test(), wp_update_network_site_counts(), and wp_update_network_user_counts().
wp_load_alloptions ()
Loads and caches all autoloaded options, if available or all options.
Since
2.2.0
wpdb $wpdb WordPress database abstraction object.
Returns
array List of all options.
Definition at line 174 of file option.php.
References $wpdb, is_multisite(), wp_cache_add(), wp_cache_get(), and wp_installing().
Referenced by _wp_specialchars(), add_option(), delete_option(), get_alloptions(), get_option(), get_transient(), is_blog_installed(), and update_option().
wp_load_core_site_options ($site_id = null)
Loads and caches certain often requested site options if is_multisite() and a persistent cache is not being used.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $site_id Optional site ID for which to query the options. Defaults to the current site.
Definition at line 207 of file option.php.
References $option, $options, $wpdb, is_multisite(), maybe_unserialize(), wp_cache_set(), wp_installing(), and wp_using_ext_object_cache().
wp_protect_special_option ($option)
Protect WordPress special option from being modified.
Will die if $option is in protected list. Protected options are 'alloptions' and 'notoptions' options.
Since
2.2.0
Parameters
string $option Option name.
Definition at line 149 of file option.php.
References $option, __, esc_html, and wp_die().
Referenced by add_network_option(), add_option(), delete_option(), update_network_option(), and update_option().
wp_set_all_user_settings ($user_settings)
Private.
Set all user interface settings.
Since
2.8.0
array $_updated_user_settings
Parameters
array $user_settings
Returns
bool|void
Definition at line 950 of file option.php.
References $name, $user_id, $value, get_current_user_id(), is_super_admin(), is_user_member_of_blog(), and update_user_option().
Referenced by delete_user_setting(), and set_user_setting().
wp_user_settings ()
Saves and restores user interface settings stored in a cookie.
Checks if the current user-settings cookie is updated and stores it. When no cookie exists (different browser used), adds the last saved cookie restoring the settings.
Since
2.7.0
Definition at line 787 of file option.php.
References $_COOKIE, $secure, $user_id, admin_url(), get_current_user_id(), get_user_option(), is_admin(), is_super_admin(), is_user_member_of_blog(), null, SITECOOKIEPATH, and update_user_option().