GravityView: other_entries.php File Reference
other_entries.php File Reference
Namespaces
GravityView
GPL2+
Variables
$created_by = \GV\Utils::get($field, 'entry/created_by')
$criteria ['paging']
Modify the search parameters before the entries are fetched.
$criteria ['search_criteria']
$criteria ['search_criteria'] = GravityView_frontend::process_search_only_approved($view_settings, $criteria['search_criteria'])
$criteria ['search_criteria']['status'] = apply_filters('gravityview_status', 'active', $view_settings)
$deprecated = apply_filters('gravityview/field/other_entries/args', array(), $field)
$entries = GVCommon::get_entries($form_id, $criteria)
$field = $gravityview_view->getCurrentField()
if(empty($created_by)) $form_id = $gravityview_view->getFormId()
$gravityview_view = GravityView_View::getInstance()
if(empty($entries) && $gravityview_view->getCurrentFieldSetting('no_entries_hide')) $list
$view_settings = gravityview_get_template_settings($gravityview_view->getViewId())
$view_settings ['page_size'] = $gravityview_view->getCurrentFieldSetting('page_size')
Variable Documentation
$created_by
$created_by = \GV\Utils::get($field, 'entry/created_by')
Definition at line 13 of file other_entries.php.
Referenced by GravityView_Field_Other_Entries\filter_entries(), GravityView_Field_Gravatar\get_email(), and GravityView_Change_Entry_Creator\update_entry_creator().
$criteria [1/4]
$criteria
Initial value:
= array(
    'offset' => 0,
    'page_size' => $view_settings['page_size']
)
Modify the search parameters before the entries are fetched.
Since
1.11
Parameters
array $criteria Gravity Forms search criteria array, as used by GVCommon::get_entries()
array $view_settings Associative array of settings with plugin defaults used if not set by the View
int $form_id The Gravity Forms ID
Definition at line 28 of file other_entries.php.
Referenced by GravityView_Field_Time\_maybe_filter_gravity_forms_query(), GVCommon\calculate_get_entries_criteria(), GVCommon\check_entry_display(), GravityView_Field_Other_Entries\filter_entries(), GVCommon\get_entries(), GravityView_frontend\get_search_criteria(), and GV\Mocks\GravityView_frontend_get_view_entries().
$criteria [2/4]
$criteria[ 'search_criteria']
Initial value:
= array(
    'field_filters' => array(
        array(
            'key' => 'created_by',
            'value' => $created_by,
            'operator' => 'is'
        )
    )
)
Definition at line 34 of file other_entries.php.
$criteria [3/4]
$criteria[ 'search_criteria'] = GravityView_frontend::process_search_only_approved($view_settings, $criteria['search_criteria'])
Definition at line 43 of file other_entries.php.
$criteria [4/4]
$criteria[ 'search_criteria'][ 'status'] = apply_filters('gravityview_status', 'active', $view_settings)
Definition at line 44 of file other_entries.php.
$deprecated
$deprecated = apply_filters('gravityview/field/other_entries/args', array(), $field)
Since
1.7.6
Definition at line 81 of file other_entries.php.
$entries
$entries = GVCommon::get_entries($form_id, $criteria)
Definition at line 57 of file other_entries.php.
Referenced by View_Template\__construct(), gvfield\callback(), gravityview\callback(), GVCommon\check_entry_display(), gravityview\detail(), Multi_Entry\from_entries(), GF_Form\get_entries(), GravityView_Field_Other_Entries\get_entries(), GravityView_Recent_Entries_Widget\get_entries(), GVCommon\get_entries(), View\get_entries(), GravityView_Entry_Link_Shortcode\get_entry(), GravityView_frontend\get_search_criteria(), GV\Mocks\GravityView_frontend_get_view_entries(), Request\is_entry(), Views_Route\prepare_entry_for_response(), GravityView_Bulk_Actions\process_bulk_action(), Entry_Legacy_Template\render(), View_Legacy_Template\render(), Entry_Renderer\render(), Edit_Entry_Renderer\render(), Legacy_Override_Template\render(), GravityView_Edit_Entry_Render\setup_vars(), View\template_redirect(), GravityView_Entry_Approval\update_bulk(), and GravityView_Recent_Entries_Widget\widget().
$field
$field = $gravityview_view->getCurrentField()
Definition at line 11 of file other_entries.php.
$form_id
if (empty($created_by)) $form_id = $gravityview_view->getFormId()
Definition at line 20 of file other_entries.php.
Referenced by GravityView_Field\_filter_gform_custom_merge_tags(), GravityView_Field_Gravatar\_get_email_field_choices(), GravityView_Field_Time\_get_time_format_for_field(), GravityView_frontend\_override_sorting_id_by_field_type(), GravityView_Entry_Approval\add_approval_status_updated_note(), GravityView_Admin_Views\add_custom_column_content(), GravityView_GF_Entries_List\add_edit_link(), GravityView_Admin_Bar\add_floaty_icon(), Field_Template\add_id_specific_templates(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), GravityView_Entry_Approval\ajax_update_approved(), GF_Form\by_id(), GF_Entry\by_id(), GF_Entry\by_slug(), gvfield\callback(), GravityView_Admin\connected_form_warning(), GravityView_Cache\delete(), GravityView_Field_Post_Image\explode_value(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_Field_FileUpload\field_options(), GravityView_Field_Radio\field_options(), GravityView_Field_Checkbox\field_options(), GravityView_Field_Select\field_options(), GravityView_Field_MultiSelect\field_options(), GravityView_Field_Survey\field_options(), GravityView_Field_Consent\field_options(), GravityView_Field_Gravatar\field_options(), GravityView_Field_Time\field_options(), GravityView_Widget_Search\filter_entries(), GravityView_frontend\filter_no_entries_output(), GravityView_Admin_Views\filter_pre_get_posts(), GravityView_Plugin_Hooks_Gravity_PDF\fix_entry_id_for_custom_content_shortcode(), Form_Collection\get(), GravityView_Bulk_Actions\get_bulk_actions(), GravityView_Admin_Views\get_connected_form_links(), GVCommon\get_connected_views(), GravityView_Render_Settings\get_default_field_options(), GVCommon\get_directory_fields(), View\get_entries(), GVCommon\get_entry_id_from_slug(), GVCommon\get_entry_ids(), GVCommon\get_entry_meta(), GravityView_Ajax\get_field_options(), GravityView_Admin_ApproveEntries\get_first_form_id(), GVCommon\get_form(), GravityView_Admin_ApproveEntries\get_form_id(), GVCommon\get_form_or_form_template(), GravityView_Edit_Entry\get_nonce_key(), GravityView_frontend\get_search_criteria(), GravityView_frontend\get_search_criteria_paging(), GravityView_Migrate\get_search_fields(), GravityView_Plugin_Hooks_Gravity_Flow\get_status_options(), View\get_unions(), GravityView_Field_Workflow_Step\get_workflow_step(), GravityView_Welcome\getting_started_screen(), GV\Mocks\GravityView_frontend_get_view_entries(), gravityview_get_connected_views(), gravityview_get_directory_fields(), gravityview_get_entry_ids(), gravityview_get_entry_meta(), gravityview_get_form(), GravityView_Cache\in_blocklist(), Request\is_edit_entry(), Request\is_entry(), GravityView_Duplicate_Entry\make_duplicate_link_row(), GravityView_Entry_Approval_Merge_Tags\maybe_update_approved(), GravityView_Field_Workflow_Step\modify_frontend_search_fields(), GravityView_Plugin_Hooks_Gravity_Flow\modify_search_bar_fields_dropdown(), GravityView_Field_Time\modify_sort_id(), GravityView_Widget_Search\prepare_field_filter(), GravityView_Bulk_Actions\process_bulk_action(), GravityView_Admin_Views\render_active_areas(), GravityView_Admin_Views\render_additional_fields(), GravityView_Admin_Views\render_available_fields(), GravityView_Admin_Views\render_directory_active_areas(), GravityView_Render_Settings\render_field_options(), GravityView_Admin_Views\render_field_pickers(), GravityView_Widget_Gravity_Forms\render_frontend(), GravityView_Widget_Search\render_searchable_fields(), GravityView_Admin_Views\save_postdata(), GravityView_Admin_Views\set_default_view_fields(), GravityView_Admin_ApproveEntries\show_approve_entry_column(), GravityView_Widget_Search\sieve_filter_choices(), GravityView_Admin_ApproveEntries\update_approved(), GravityView_Entry_Approval\update_approved(), GravityView_Entry_Approval_Merge_Tags\update_approved(), GravityView_Entry_Approval\update_approved_meta(), GravityView_Entry_Approval\update_bulk(), and GravityView_Recent_Entries_Widget\widget().
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Definition at line 9 of file other_entries.php.
$list
if (empty($entries) &&$gravityview_view->getCurrentFieldSetting('no_entries_hide')) $list
Initial value:
= new GravityView_Entry_List(
    $entries,
    $gravityview_view->getPostId(),
    $field['form'],
    $gravityview_view->getCurrentFieldSetting('link_format'),
    $gravityview_view->getCurrentFieldSetting('after_link'),
    'other_entries'
)
Definition at line 65 of file other_entries.php.
$view_settings [1/2]
$view_settings = gravityview_get_template_settings($gravityview_view->getViewId())
Definition at line 23 of file other_entries.php.
$view_settings [2/2]
$view_settings[ 'page_size'] = $gravityview_view->getCurrentFieldSetting('page_size')
Definition at line 25 of file other_entries.php.