GravityView: plugins.php File Reference
plugins.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$_SERVER ['REQUEST_URI'] = remove_query_arg(array('error', 'deleted', 'activate', 'activate-multi', 'deactivate', 'deactivate-multi', '_error_nonce'), $_SERVER['REQUEST_URI'])
$action = $wp_list_table->current_action()
else $errmsg = __('Plugin could not be activated because it triggered a <strong>fatal error</strong>.')
$invalid = validate_active_plugins()
$pagenum = $wp_list_table->get_pagenum()
$parent_file = 'plugins.php'
$plugin = isset($_REQUEST['plugin']) ? $_REQUEST['plugin'] : ''
$s = isset($_REQUEST['s']) ? urlencode($_REQUEST['s']) : ''
$title = __('Plugins')
$wp_list_table = _get_list_table('WP_Plugins_List_Table')
else __pad5__
else
endif
s code will get in the way of another plugin
s code will get in the way of another causing compatibility issues If your site starts doing strange things
Variable Documentation
$_SERVER['REQUEST_URI'] = remove_query_arg(array('error', 'deleted', 'activate', 'activate-multi', 'deactivate', 'deactivate-multi', '_error_nonce'), $_SERVER['REQUEST_URI'])
Definition at line 24 of file plugins.php.
$action = $wp_list_table->current_action()
Definition at line 18 of file plugins.php.
else $errmsg = __('Plugin could not be activated because it triggered a <strong>fatal error</strong>.')
Definition at line 432 of file plugins.php.
$invalid = validate_active_plugins()
Definition at line 411 of file plugins.php.
Referenced by validate_active_plugins().
$pagenum = $wp_list_table->get_pagenum()
Definition at line 16 of file plugins.php.
$parent_file = 'plugins.php'
Definition at line 407 of file plugins.php.
$plugin = isset($_REQUEST['plugin']) ? $_REQUEST['plugin'] : ''
Definition at line 20 of file plugins.php.
Referenced by WP_Plugins_List_Table\_search_callback(), activate_plugin(), activate_plugins(), GFForms\addons_page(), Plugin_Upgrader\bulk_upgrade(), Plugin_Upgrader\deactivate_plugin_before_upgrade(), deactivate_plugins(), Plugin_Upgrader\delete_old_plugin(), delete_plugins(), WP_Plugin_Install_List_Table\display_rows(), GFForms\get_addon_info(), WP_Plugin_Install_List_Table\get_installed_plugin_slugs(), get_plugin_files(), install_plugin_install_status(), is_network_only_plugin(), is_plugin_active(), is_plugin_active_for_network(), is_plugin_inactive(), is_uninstallable_plugin(), maybe_disable_automattic_widgets(), Plugin_Upgrader\plugin_info(), plugin_sandbox_scrape(), plugins_url(), WP_Automatic_Updater\run(), GFSettings\settings_uninstall_page(), uninstall_plugin(), Plugin_Upgrader\upgrade(), validate_active_plugins(), validate_plugin(), wp_ajax_update_plugin(), wp_get_active_and_valid_plugins(), wp_get_active_network_plugins(), wp_get_mu_plugins(), wp_update_plugin(), and wp_update_plugins().
$s = isset($_REQUEST['s']) ? urlencode($_REQUEST['s']) : ''
Definition at line 21 of file plugins.php.
$title = __('Plugins')
Definition at line 406 of file plugins.php.
$wp_list_table = _get_list_table('WP_Plugins_List_Table')
Definition at line 15 of file plugins.php.
else __pad5__
Definition at line 460 of file plugins.php.
else
Initial value:
{
                    _e( 'The selected plugins have been <strong>deleted</strong>.' )
Definition at line 461 of file plugins.php.
endif
Definition at line 467 of file plugins.php.
string array A string or an array of capabilities or roles that can uninstall the plugin
Definition at line 386 of file plugins.php.
Referenced by Plugin_Upgrader_Skin\__construct(), Plugin_Upgrader_Skin\after(), and GravityView_Welcome\getting_started_screen().
s code will get in the way of another causing compatibility issues If your site starts doing strange things
Definition at line 386 of file plugins.php.