GravityView: plugin-editor.php File Reference
plugin-editor.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$file = validate_file_to_edit($file, $plugin_files)
$parent_file = 'plugins.php'
if(empty($plugins)) if($file) elseif(empty($plugin)) $plugin_files = get_plugin_files($plugin)
$plugins = get_plugins()
$real_file = WP_PLUGIN_DIR . '/' . $file
$scrollto = isset($_REQUEST['scrollto']) ? (int) $_REQUEST['scrollto'] : 0
$title = __("Edit Plugins")
switch ($action)
Variable Documentation
$file = validate_file_to_edit($file, $plugin_files)
Definition at line 51 of file plugin-editor.php.
Referenced by GravityView_Widget_Search\__construct(), GravityView_Delete_Entry\__construct(), GravityView_Edit_Entry\__construct(), GravityView_Metabox_Tab\__construct(), File_Upload_Upgrader\__construct(), _deprecated_file(), _unzip_file_pclzip(), _unzip_file_ziparchive(), _upgrade_422_remove_genericons(), _wp_get_attachment_relative_path(), _wp_handle_upload(), GravityView_Delete_Entry\add_template_path(), GravityView_Edit_Entry\add_template_path(), GravityView_Widget_Search\add_template_path(), WP_Filesystem_Direct\atime(), WP_Filesystem_SSH2\atime(), wp_xmlrpc_server\attach_uploads(), attachment_submitbox_metadata(), WP_Filesystem_ftpsockets\chdir(), Core_Upgrader\check_files(), Plugin_Upgrader\check_package(), Language_Pack_Upgrader\check_package(), check_upload_size(), WP_Filesystem_Direct\chgrp(), WP_Filesystem_SSH2\chgrp(), WP_Filesystem_Direct\chmod(), WP_Filesystem_FTPext\chmod(), WP_Filesystem_ftpsockets\chmod(), WP_Filesystem_SSH2\chmod(), WP_Filesystem_Direct\chown(), WP_Filesystem_SSH2\chown(), GFFormDisplay\clean_up_files(), WP_Upgrader\clear_destination(), WP_Media_List_Table\column_title(), comments_template(), WP_UnitTest_Factory_For_Attachment\create_object(), WP_UnitTest_Factory_For_Attachment\create_upload_object(), PHPMailer\createBody(), WP_Filesystem_Direct\delete(), WP_Filesystem_FTPext\delete(), WP_Filesystem_ftpsockets\delete(), WP_Filesystem_SSH2\delete(), GFFormsModel\delete_files(), getid3_lib\EmbeddedLookup(), WP_Filesystem_Direct\exists(), WP_Filesystem_FTPext\exists(), WP_Filesystem_ftpsockets\exists(), WP_Filesystem_SSH2\exists(), get_attached_file(), get_attachment_icon_src(), get_attachment_taxonomies(), get_author_posts_url(), SimplePie_Misc\get_build(), WP_Filesystem_Direct\get_contents(), WP_Filesystem_FTPext\get_contents(), WP_Filesystem_ftpsockets\get_contents(), WP_Filesystem_MockFS\get_contents(), WP_Filesystem_SSH2\get_contents(), WP_Filesystem_Direct\get_contents_array(), WP_Filesystem_FTPext\get_contents_array(), WP_Filesystem_ftpsockets\get_contents_array(), WP_Filesystem_SSH2\get_contents_array(), get_dropins(), get_editor_stylesheets(), get_file_data(), get_file_description(), get_media_item(), get_mu_plugins(), WP_Theme\get_page_templates(), get_plugin_files(), get_plugins(), get_real_file_to_edit(), GF_Field_FileUpload\get_value_merge_tag(), WP_Filesystem_Direct\getchmod(), WP_Filesystem_FTPext\getchmod(), WP_Filesystem_ftpsockets\getchmod(), WP_Filesystem_SSH2\getchmod(), getid3_lib\getFileSizeSyscall(), getID3\getHashdata(), WP_Filesystem_Base\gethchmod(), WP_Filesystem_Direct\group(), WP_Filesystem_FTPext\group(), WP_Filesystem_ftpsockets\group(), WP_Filesystem_SSH2\group(), getid3_lib\hash_data(), image_link_input_fields(), image_make_intermediate_size(), image_resize(), GravityView_Ajax\import_fields(), WP_Site_Icon\insert_attachment(), install_plugin_install_status(), WP_Filesystem_MockFS\is_file(), WP_Filesystem_Direct\is_file(), WP_Filesystem_FTPext\is_file(), WP_Filesystem_ftpsockets\is_file(), WP_Filesystem_SSH2\is_file(), WP_Filesystem_Direct\is_readable(), WP_Filesystem_SSH2\is_readable(), is_uninstallable_plugin(), is_wpmu_sitewide_plugin(), WP_Filesystem_Direct\is_writable(), TracTickets\isTracTicketClosed(), list_files(), GravityView_Edit_Entry\load_components(), WP_Upgrader\maintenance_mode(), media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), media_sideload_image(), ftp_base\mput(), WP_Filesystem_Direct\mtime(), WP_Filesystem_FTPext\mtime(), WP_Filesystem_ftpsockets\mtime(), WP_Filesystem_SSH2\mtime(), WP_Filesystem_Direct\owner(), WP_Filesystem_FTPext\owner(), WP_Filesystem_ftpsockets\owner(), WP_Filesystem_SSH2\owner(), plugin_basename(), plugin_dir_path(), plugin_dir_url(), GFForms\plugin_settings_link(), WP_Filesystem_Direct\put_contents(), WP_Filesystem_FTPext\put_contents(), WP_Filesystem_ftpsockets\put_contents(), WP_Filesystem_SSH2\put_contents(), recurse_dirsize(), register_activation_hook(), register_deactivation_hook(), register_uninstall_hook(), GFForms\rename_suspicious_files_recursive(), GravityView_Metabox_Tab\render(), WP_UnitTestCase\rmdir(), SimplePie_Sanitize\sanitize(), WP_Filesystem_Direct\size(), WP_Filesystem_FTPext\size(), WP_Filesystem_ftpsockets\size(), WP_Filesystem_SSH2\size(), Custom_Image_Header\step_2(), Custom_Image_Header\step_2_manage_upload(), WP_Filesystem_Direct\touch(), uninstall_plugin(), WP_UnitTestCase\unlink(), WP_Upgrader\unpack_package(), unzip_file(), update_attached_file(), update_core(), update_recently_edited(), GFAsyncUpload\upload(), GF_Field_FileUpload\upload_file(), GFFormsModel\upload_file(), validate_file(), validate_file_to_edit(), wp_admin_css(), wp_admin_css_uri(), wp_attachment_is(), wp_check_filetype_and_ext(), wp_create_thumbnail(), wp_delete_attachment(), wp_delete_file(), wp_generate_attachment_metadata(), wp_get_attachment_thumb_file(), wp_get_attachment_url(), wp_get_installed_translations(), wp_handle_sideload(), wp_handle_upload(), wp_insert_attachment(), wp_load_image(), wp_maybe_generate_attachment_metadata(), wp_mime_type_icon(), wp_plugin_update_row(), wp_read_audio_metadata(), wp_read_image_metadata(), wp_read_video_metadata(), wp_register_plugin_realpath(), wp_restore_image(), wp_simplepie_autoload(), wp_update_plugins(), and wpmu_delete_blog().
$parent_file = 'plugins.php'
Definition at line 21 of file plugin-editor.php.
if (empty($plugins)) if ($file) elseif (empty($plugin)) $plugin_files = get_plugin_files($plugin)
Definition at line 46 of file plugin-editor.php.
Referenced by get_dropins(), get_mu_plugins(), get_plugin_files(), and get_plugins().
$plugins = get_plugins()
Definition at line 25 of file plugin-editor.php.
Referenced by activate_plugins(), GFForms\addons_page(), Plugin_Upgrader\bulk_upgrade(), deactivate_plugins(), delete_plugins(), _WP_Editors\editor_js(), _WP_Editors\editor_settings(), _WP_Editors\enqueue_scripts(), is_plugin_active_for_network(), list_plugin_updates(), maybe_disable_automattic_widgets(), WP_Plugins_List_Table\no_items(), WP_Plugins_List_Table\prepare_items(), GFForms\set_logging_supported(), GFAddOn\set_logging_supported(), validate_active_plugins(), wp_get_active_and_valid_plugins(), wp_get_active_network_plugins(), wp_get_update_data(), wp_plugin_update_rows(), and wp_update_plugins().
$real_file = WP_PLUGIN_DIR . '/' . $file
Definition at line 52 of file plugin-editor.php.
$scrollto = isset($_REQUEST['scrollto']) ? (int) $_REQUEST['scrollto'] : 0
Definition at line 53 of file plugin-editor.php.
$title = __("Edit Plugins")
Definition at line 20 of file plugin-editor.php.
switch($action)
Definition at line 55 of file plugin-editor.php.