GravityView: post-template.php File Reference
post-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_convert_urlencoded_to_entities ($match)
Preview fix for JavaScript bug with foreign languages.
_wp_link_page ($i)
Helper function for wp_link_pages().
body_class ($class= '')
Display the classes for the body element.
get_body_class ($class= '')
Retrieve the classes for the body element as an array.
get_page_template_slug ($post_id=null)
Get the specific template name for a page.
get_post_class ($class= '', $post_id=null)
Retrieve the classes for the post div as an array.
get_the_content ($more_link_text=null, $strip_teaser=false)
Retrieve the post content.
get_the_excerpt ($deprecated= '')
Retrieve the post excerpt.
get_the_guid ($post=0)
Retrieve the Post Global Unique Identifier (guid).
get_the_ID ()
Retrieve the ID of the current item in the WordPress Loop.
get_the_password_form ($post=0)
Retrieve protected post password form content.
get_the_title ($post=0)
Retrieve post title.
has_excerpt ($id=0)
Whether post has excerpt.
is_page_template ($template= '')
Whether currently in a page template.
post_class ($class= '', $post_id=null)
Display the classes for the post div.
post_custom ($key= '')
Retrieve post custom meta data field.
post_password_required ($post=null)
Whether post requires password and correct password has been provided.
prepend_attachment ($content)
Wrap attachment in paragraph tag before content.
the_attachment_link ($id=0, $fullsize=false, $deprecated=false, $permalink=false)
Display an attachment page link using an image or icon.
the_content ($more_link_text=null, $strip_teaser=false)
Display the post content.
the_excerpt ()
Display the post excerpt.
the_guid ($post=0)
Display the Post Global Unique Identifier (guid).
the_ID ()
Display the ID of the current item in the WordPress Loop.
the_meta ()
Display list of post custom fields.
the_title ($before= '', $after= '', $echo=true)
Display or retrieve the current post title with optional content.
the_title_attribute ($args= '')
Sanitize the current title when retrieving or displaying.
walk_page_dropdown_tree ()
Retrieve HTML dropdown (select) content for page list.
walk_page_tree ($pages, $depth, $current_page, $r)
Retrieve HTML list content for page list.
wp_dropdown_pages ($args= '')
Retrieve or display list of pages as a dropdown (select list).
wp_get_attachment_link ($id=0, $size= 'thumbnail', $permalink=false, $icon=false, $text=false, $attr= '')
Retrieve an attachment page link using an image or icon, if possible.
wp_link_pages ($args= '')
The formatted output of a list of pages.
wp_list_pages ($args= '')
Retrieve or display list of pages in list (li) format.
wp_list_post_revisions ($post_id=0, $type= 'all')
Display list of a post's revisions.
wp_page_menu ($args=array())
Display or retrieve list of pages with optional home link.
wp_post_revision_title ($revision, $link=true)
Retrieve formatted date timestamp of a revision (linked to that revisions's page).
wp_post_revision_title_expanded ($revision, $link=true)
Retrieve formatted date timestamp of a revision (linked to that revisions's page).
Function Documentation
_convert_urlencoded_to_entities ($match)
Preview fix for JavaScript bug with foreign languages.
Since
3.1.0 private
Parameters
array $match Match array from preg_replace_callback.
Returns
string
Definition at line 333 of file post-template.php.
_wp_link_page ($i)
Helper function for wp_link_pages().
Since
3.1.0 private
WP_Rewrite $wp_rewrite
Parameters
int $i Page number.
Returns
string Link.
Definition at line 921 of file post-template.php.
References $i, $post, $url, $wp_rewrite, add_query_arg(), elseif, esc_url, get_option(), get_permalink(), get_post(), get_preview_post_link(), is_preview(), trailingslashit(), user_trailingslashit(), and wp_unslash().
Referenced by wp_link_pages().
body_class ($class = '')
Display the classes for the body element.
Since
2.8.0
Parameters
string | array $class One or more classes to add to the class list.
Definition at line 540 of file post-template.php.
References $class, and get_body_class().
get_body_class ($class = '')
Retrieve the classes for the body element as an array.
Since
2.8.0
WP_Query $wp_query
Parameters
string | array $class One or more classes to add to the class list.
Returns
array Array of classes.
Filter the list of CSS body classes for the current post or page.
Since
2.8.0
Parameters
array $classes An array of body classes.
array $class An array of additional classes added to the body.
Definition at line 555 of file post-template.php.
References $class, $page, $post, $post_id, $post_type, apply_filters(), elseif, get_background_color(), get_background_image(), get_page_template_slug(), get_pages(), get_post(), get_post_format(), get_post_mime_type(), get_query_var(), get_theme_support(), is_404, is_admin_bar_showing(), is_archive(), is_attachment(), is_author(), is_category(), is_date(), is_front_page(), is_home(), is_page(), is_page_template(), is_paged(), is_post_type_archive(), is_rtl(), is_search(), is_single(), is_singular(), is_tag(), is_tax(), is_wp_error(), post_type_supports(), sanitize_html_class(), and str_replace.
Referenced by body_class().
get_page_template_slug ($post_id = null)
Get the specific template name for a page.
Since
3.4.0
Parameters
int $post_id Optional. The page ID to check. Defaults to the current post, when used in the loop.
Returns
string|false Page template filename. Returns an empty string when the default page template is in use. Returns false if the post is not a page.
Definition at line 1593 of file post-template.php.
References $post, $post_id, $template, get_post(), and get_post_meta().
Referenced by wp_xmlrpc_server\_prepare_page(), get_body_class(), get_page_template(), and is_page_template().
get_post_class ($class = '', $post_id = null)
Retrieve the classes for the post div as an array.
The class names are many. If the post is a sticky, then the 'sticky' class name. The class 'hentry' is always added to each post. If the post has a post thumbnail, 'has-post-thumbnail' is added as a class. For each taxonomy that the post belongs to, a class will be added of the format '{$taxonomy}-{$slug}' - eg 'category-foo' or 'my_custom_taxonomy-bar'. The 'post_tag' taxonomy is a special case; the class has the 'tag-' prefix instead of 'post_tag-'. All classes are passed through the filter, 'post_class' with the list of classes, followed by $class parameter value, with the post ID as the last parameter.
Since
2.7.0
4.2.0 Custom taxonomy classes were added.
Parameters
string | array $class One or more classes to add to the class list.
int | WP_Post $post_id Optional. Post ID or post object.
Returns
array Array of classes.
Filter the list of CSS classes for the current post.
Since
2.7.0
Parameters
array $classes An array of post classes.
array $class An array of additional classes added to the post.
int $post_id The post ID.
Definition at line 432 of file post-template.php.
References $class, $post, $post_id, apply_filters(), current_theme_supports(), elseif, get_post(), get_post_format(), get_taxonomies(), get_the_terms(), has_post_thumbnail(), is_admin(), is_attachment(), is_home(), is_object_in_taxonomy(), is_paged(), is_sticky(), is_wp_error(), post_password_required(), post_type_supports(), and sanitize_html_class().
Referenced by post_class().
get_the_content ($more_link_text = null, $strip_teaser = false)
Retrieve the post content.
Since
0.71
int $page int $more bool $preview array $pages int $multipage
Parameters
string $more_link_text Optional. Content for when there is more text.
bool $strip_teaser Optional. Strip teaser content before the more text. Default is false.
Returns
string
Filter the Read More link text.
Since
2.8.0
Parameters
string $more_link_element Read More link element.
string $more_link_text Read More text.
Definition at line 260 of file post-template.php.
References $content, $more, $output, $page, $post, __, apply_filters(), force_balance_tags(), get_permalink(), get_post(), get_the_password_form(), null, post_password_required(), and wp_kses_no_null().
Referenced by get_the_content_feed(), the_content(), the_content_rss(), twentyeleven_get_first_url(), twentyeleven_get_gallery_images(), twentyeleven_url_grabber(), twentyten_get_gallery_images(), twentythirteen_get_link_url(), and wp_trim_excerpt().
get_the_excerpt ($deprecated = '')
Retrieve the post excerpt.
Since
0.71
Parameters
mixed $deprecated Not used.
Returns
string
Filter the retrieved post excerpt.
Since
1.2.0
Parameters
string $post_excerpt The post excerpt.
Definition at line 364 of file post-template.php.
References $deprecated, $post, __, _deprecated_argument(), apply_filters(), get_post(), and post_password_required().
Referenced by the_excerpt(), the_excerpt_embed(), and the_excerpt_rss().
get_the_guid ($post = 0)
Retrieve the Post Global Unique Identifier (guid).
The guid will appear to be a link, but should not be used as an link to the post. The reason you should not use it as a link, is because of moving the blog across domains.
Since
1.5.0
Parameters
int | WP_Post $post Optional. Post ID or post object. Default is global $post.
Returns
string
Filter the Global Unique Identifier (guid) of the post.
Since
1.5.0
Parameters
string $guid Global Unique Identifier (guid) of the post.
int $id The post ID.
Definition at line 205 of file post-template.php.
References $id, $post, apply_filters(), and get_post().
Referenced by _transition_post_status(), get_comment_guid(), the_guid(), and wp_get_attachment_url().
get_the_ID ()
Retrieve the ID of the current item in the WordPress Loop.
Since
2.1.0
Returns
int|false The ID of the current item in the WordPress Loop. False if $post is not set.
Definition at line 27 of file post-template.php.
References $post, and get_post().
Referenced by _wp_ajax_menu_quick_search(), comment_form(), comments_popup_link(), get_comment_id_fields(), get_post_comments_feed_link(), get_post_custom(), get_trackback_url(), is_sticky(), prepend_attachment(), GravityView_frontend\render_view(), the_ID(), twentyeleven_get_gallery_images(), twentyten_get_gallery_images(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_audio_shortcode(), and wp_video_shortcode().
get_the_password_form ($post = 0)
Retrieve protected post password form content.
Since
1.0.0
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
string HTML content for password form for password protected post.
Filter the HTML output for the protected post password form.
If modifying the password field, please note that the core database schema limits the password field to 20 characters regardless of the value of the size attribute in the form input.
Since
2.7.0
Parameters
string $output The password form HTML output.
Definition at line 1526 of file post-template.php.
References $label, $output, $post, __, apply_filters(), esc_attr__(), esc_url, get_post(), and site_url().
Referenced by get_the_content(), and GravityView_frontend\render_view().
get_the_title ($post = 0)
Retrieve post title.
If the post is protected and the visitor is not an admin, then "Protected" will be displayed before the post title. If the post is private, then "Private" will be located before the post title.
Since
0.71
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
string
Filter the text prepended to the post title for protected posts.
The filter is only applied on the front end.
Since
2.8.0
Parameters
string $prepend Text displayed before the post title. Default 'Protected: s'.
WP_Post $post Current post object.
Filter the text prepended to the post title of private posts.
The filter is only applied on the front end.
Since
2.8.0
Parameters
string $prepend Text displayed before the post title. Default 'Private: s'.
WP_Post $post Current post object.
Filter the post title.
Since
0.71
Parameters
string $title The post title.
int $id The post ID.
Definition at line 110 of file post-template.php.
References $id, $post, $title, __, apply_filters(), elseif, get_post(), and is_admin().
Referenced by _draft_or_post_title(), wp_xmlrpc_server\_prepare_comment(), _wp_ajax_menu_quick_search(), WP_Comments_List_Table\column_response(), comments_popup_link(), get_post_embed_html(), get_the_title_rss(), WP_Customize_Nav_Menu_Item_Setting\populate_value(), Walker_Nav_Menu_Edit\start_el(), the_title(), the_title_attribute(), trackback_rdf(), WP_Widget_Recent_Posts\widget(), WP_Widget_Recent_Comments\widget(), wp_embed_excerpt_more(), _WP_Editors\wp_link_query(), and wp_prepare_revisions_for_js().
has_excerpt ($id = 0)
Whether post has excerpt.
Since
2.3.0
Parameters
int | WP_Post $id Optional. Post ID or post object.
Returns
bool
Definition at line 395 of file post-template.php.
References $id, $post, and get_post().
Referenced by WP_Media_List_Table\column_desc(), twentyeleven_custom_excerpt_more(), and twentyten_custom_excerpt_more().
is_page_template ($template = '')
Whether currently in a page template.
This template tag allows you to determine if you are in a page template. You can optionally provide a template name or array of template names and then the check will be specific to that template.
Since
2.5.0
4.2.0 The $template parameter was changed to also accept an array of page templates.
Parameters
string | array $template The specific template name or array of templates to match.
Returns
bool True on success, false on failure.
Definition at line 1561 of file post-template.php.
References $template, get_page_template_slug(), get_queried_object_id(), and is_page().
Referenced by get_body_class(), twentyeleven_body_classes(), twentyfourteen_body_classes(), twentytwelve_body_class(), and twentytwelve_content_width().
post_class ($class = '', $post_id = null)
Display the classes for the post div.
Since
2.7.0
Parameters
string | array $class One or more classes to add to the class list.
int | WP_Post $post_id Optional. Post ID or post object. Defaults to the global $post.
Definition at line 408 of file post-template.php.
References $class, $post_id, and get_post_class().
post_custom ($key = '')
Retrieve post custom meta data field.
Since
1.5.0
Parameters
string $key Meta data key name.
Returns
false|string|array Array of values or single value, if only one element exists. False will be returned if key does not exist.
Definition at line 962 of file post-template.php.
References $custom, elseif, and get_post_custom().
post_password_required ($post = null)
Whether post requires password and correct password has been provided.
Since
2.7.0
Parameters
int | WP_Post | null $post An optional post. Global $post used if not provided.
Returns
bool false if a password is not required or the correct password cookie is present, true otherwise.
Definition at line 763 of file post-template.php.
References $_COOKIE, $post, ABSPATH, get_post(), wp_unslash(), and WPINC.
Referenced by atom_enclosure(), comments_popup_link(), get_post_class(), get_the_content(), get_the_excerpt(), GravityView_frontend\render_view(), rss_enclosure(), twentyfourteen_post_classes(), Twenty_Fourteen_Ephemera_Widget\widget(), and wp_handle_comment_submission().
prepend_attachment ($content)
Wrap attachment in paragraph tag before content.
Since
2.0.0
Parameters
string $content
Returns
string
Filter the attachment markup to be prepended to the post content.
Since
2.0.0
See also
prepend_attachment()
Parameters
string $p The attachment HTML output.
Definition at line 1474 of file post-template.php.
References $content, $post, apply_filters(), elseif, get_post(), get_post_thumbnail_id(), get_the_ID(), has_post_thumbnail(), wp_attachment_is(), wp_audio_shortcode(), wp_get_attachment_link(), wp_get_attachment_metadata(), wp_get_attachment_url(), and wp_video_shortcode().
Referenced by wp_embed_excerpt_attachment().
the_attachment_link ($id = 0, $fullsize = false, $deprecated = false, $permalink = false)
Display an attachment page link using an image or icon.
Since
2.0.0
Parameters
int | WP_Post $id Optional. Post ID or post object.
bool $fullsize Optional, default is false. Whether to use full size.
bool $deprecated Deprecated. Not used.
bool $permalink Optional, default is false. Whether to include permalink.
Definition at line 1403 of file post-template.php.
References $deprecated, $id, $permalink, _deprecated_argument(), and wp_get_attachment_link().
the_content ($more_link_text = null, $strip_teaser = false)
Display the post content.
Since
0.71
Parameters
string $more_link_text Optional. Content for when there is more text.
bool $strip_teaser Optional. Strip teaser content before the more text. Default is false.
Filter the post content.
Since
0.71
Parameters
string $content Content of the current post.
Definition at line 230 of file post-template.php.
References $content, apply_filters(), get_the_content(), and str_replace.
Referenced by Twenty_Fourteen_Ephemera_Widget\widget().
the_excerpt ()
Display the post excerpt.
Since
0.71
Filter the displayed post excerpt.
Since
0.71
See also
get_the_excerpt()
Parameters
string $post_excerpt The post excerpt.
Definition at line 342 of file post-template.php.
References apply_filters(), and get_the_excerpt().
Referenced by WP_Posts_List_Table\column_title().
the_guid ($post = 0)
Display the Post Global Unique Identifier (guid).
The guid will appear to be a link, but should not be used as a link to the post. The reason you should not use it as a link, is because of moving the blog across domains.
URL is escaped to make it XML-safe.
Since
1.5.0
Parameters
int | WP_Post $post Optional. Post ID or post object. Default is global $post.
Filter the escaped Global Unique Identifier (guid) of the post.
Since
4.2.0
See also
get_the_guid()
Parameters
string $guid Escaped Global Unique Identifier (guid) of the post.
int $id The post ID.
Definition at line 174 of file post-template.php.
References $id, $post, apply_filters(), get_post(), and get_the_guid().
the_ID ()
Display the ID of the current item in the WordPress Loop.
Since
0.71
Definition at line 16 of file post-template.php.
References get_the_ID().
Referenced by WP_Widget_Recent_Posts\widget().
the_meta ()
Display list of post custom fields.
Since
1.2.0
Filter the HTML output of the li element in the post custom fields list.
Since
2.2.0
Parameters
string $html The HTML output for the li element.
string $key Meta key.
string $value Meta value.
Definition at line 981 of file post-template.php.
References $keys, $value, apply_filters(), get_post_custom_keys(), get_post_custom_values(), and is_protected_meta().
the_title ($before = '', $after = '', $echo = true)
Display or retrieve the current post title with optional content.
Since
0.71
Parameters
string $before Optional. Content to prepend to the title.
string $after Optional. Content to append to the title.
bool $echo Optional, default to true.Whether to display or return.
Returns
string|void String if $echo parameter is false.
Definition at line 42 of file post-template.php.
References $title, and get_the_title().
Referenced by WP_Widget_Recent_Posts\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), and Twenty_Eleven_Ephemera_Widget\widget().
the_title_attribute ($args = '')
Sanitize the current title when retrieving or displaying.
Works like the_title(), except the parameters can be in a string or an array. See the function for what can be override in the $args parameter.
The title before it is displayed will have the tags stripped and esc_attr() before it is passed to the user or displayed. The default as with the_title(), is to display the title.
Since
2.3.0
Parameters
string | array $args { Title attribute arguments. Optional.
string $before Markup to prepend to the title. Default empty. string $after Markup to append to the title. Default empty. bool $echo Whether to echo or return the title. Default true for echo. WP_Post $post Current post object to retrieve the title for. }
Returns
string|void String when echo is false.
Definition at line 78 of file post-template.php.
References $title, esc_attr(), get_post(), get_the_title(), and wp_parse_args().
Referenced by feed_links_extra(), get_adjacent_post_rel_link(), and the_shortlink().
walk_page_dropdown_tree ()
Retrieve HTML dropdown (select) content for page list.
Walker_PageDropdown to create HTML dropdown content.
Since
2.1.0
See also
Walker_PageDropdown::walk() for parameters and return description.
Returns
string
Definition at line 1379 of file post-template.php.
Referenced by wp_dropdown_pages().
walk_page_tree ($pages, $depth, $current_page, $r)
Retrieve HTML list content for page list.
Walker_Page to create HTML list content.
Since
2.1.0
Parameters
array $pages
int $depth
int $current_page
array $r
Returns
string
Definition at line 1355 of file post-template.php.
References $page.
Referenced by wp_list_pages().
wp_dropdown_pages ($args = '')
Retrieve or display list of pages as a dropdown (select list).
Since
2.1.0
4.2.0 The $value_field argument was added.
4.3.0 The $class argument was added.
Parameters
array | string $args { Optional. Array or string of arguments to generate a pages drop-down element.
int $depth Maximum depth. Default 0. int $child_of Page ID to retrieve child pages of. Default 0. int|string $selected Value of the option that should be selected. Default 0. bool|int $echo Whether to echo or return the generated markup. Accepts 0, 1, or their bool equivalents. Default 1. string $name Value for the 'name' attribute of the select element. Default 'page_id'. string $id Value for the 'id' attribute of the select element. string $class Value for the 'class' attribute of the select element. Default: none. Defaults to the value of $name. string $show_option_none Text to display for showing no pages. Default empty (does not display). string $show_option_no_change Text to display for "no change" option. Default empty (does not display). string $option_none_value Value to use when no page is selected. Default empty. string $value_field Post field used to populate the 'value' attribute of the option elements. Accepts any valid post field. Default 'ID'. }
Returns
string HTML content, if not displaying.
Filter the HTML output of a list of pages as a drop down.
Since
2.1.0
4.4.0 $r and $pages added as arguments.
Parameters
string $output HTML output for drop down list of pages.
array $r The parsed arguments array.
array $pages List of WP_Post objects returned by get_pages()
Definition at line 1038 of file post-template.php.
References $class, $output, apply_filters(), esc_attr(), get_pages(), walk_page_dropdown_tree(), and wp_parse_args().
Referenced by get_confirmation_ui_settings(), WP_Posts_List_Table\inline_edit(), page_attributes_meta_box(), and WP_Customize_Control\render_content().
wp_get_attachment_link ($id = 0, $size = 'thumbnail', $permalink = false, $icon = false, $text = false, $attr = '')
Retrieve an attachment page link using an image or icon, if possible.
Since
2.5.0
4.4.0 The $id parameter can now accept either a post ID or WP_Post object.
Parameters
int | WP_Post $id Optional. Post ID or post object.
string | array $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'thumbnail'.
bool $permalink Optional, Whether to add permalink to image. Default false.
bool $icon Optional. Whether the attachment is an icon. Default false.
string | false $text Optional. Link text to use. Activated by passing a string, false otherwise. Default false.
array | string $attr Optional. Array or string of attributes. Default empty.
Returns
string HTML content.
Filter a retrieved attachment page link.
Since
2.7.0
Parameters
string $link_html The page link HTML output.
int $id Post ID.
string | array $size Size of the image. Image size or array of width and height values (in that order). Default 'thumbnail'.
bool $permalink Whether to add permalink to image. Default false.
bool $icon Whether to include an icon. Default false.
string | bool $text If string, will be link text. Default false.
Definition at line 1430 of file post-template.php.
References $id, $link_text, $permalink, $size, $text, $url, __, apply_filters(), elseif, get_attachment_link(), get_post(), wp_get_attachment_image(), and wp_get_attachment_url().
Referenced by adjacent_image_link(), gallery_shortcode(), prepend_attachment(), the_attachment_link(), and wp_playlist_shortcode().
wp_link_pages ($args = '')
The formatted output of a list of pages.
Displays page links for paginated posts (i.e. includes the . Quicktag one or more times). This tag must be within The Loop.
Since
1.2.0
int $page int $numpages int $multipage int $more
Parameters
string | array $args { Optional. Array or string of default arguments.
string $before HTML or text to prepend to each link. Default is <p> Pages:. string $after HTML or text to append to each link. Default is </p>. string $link_before HTML or text to prepend to each link, inside the <a> tag. Also prepended to the current item, which is not linked. Default empty. string $link_after HTML or text to append to each Pages link inside the <a> tag. Also appended to the current item, which is not linked. Default empty. string $next_or_number Indicates whether page numbers should be used. Valid values are number and next. Default is 'number'. string $separator Text between pagination links. Default is ' '. string $nextpagelink Link text for the next page link, if available. Default is 'Next Page'. string $previouspagelink Link text for the previous page link, if available. Default is 'Previous Page'. string $pagelink Format string for page numbers. The % in the parameter string will be replaced with the page number, so 'Page ' generates "Page 1", "Page 2", etc. Defaults to '', just the page number. int|bool $echo Whether to echo or not. Accepts 1|true or 0|false. Default 1|true. }
Returns
string Formatted output in HTML.
Filter the arguments used in retrieving page links for paginated posts.
Since
3.0.0
Parameters
array $params An array of arguments for page links for paginated posts.
Filter the HTML output of individual page number links.
Since
3.6.0
Parameters
string $link The page number HTML output.
int $i Page number for paginated posts' page links.
This filter is documented in wp-includes/post-template.php
This filter is documented in wp-includes/post-template.php
Filter the HTML output of page links for paginated posts.
Since
3.6.0
Parameters
string $output HTML output of paginated posts' page links.
array $args An array of arguments.
Definition at line 820 of file post-template.php.
References $i, $link, $more, $output, $page, __, _wp_link_page(), apply_filters(), elseif, str_replace, and wp_parse_args().
Referenced by link_pages().
wp_list_pages ($args = '')
Retrieve or display list of pages in list (li) format.
Since
1.5.0
See also
get_pages()
WP_Query $wp_query
Parameters
array | string $args { Array or string of arguments. Optional.
int $child_of Display only the sub-pages of a single page by ID. Default 0 (all pages). string $authors Comma-separated list of author IDs. Default empty (all authors). string $date_format PHP date format to use for the listed pages. Relies on the 'show_date' parameter. Default is the value of 'date_format' option. int $depth Number of levels in the hierarchy of pages to include in the generated list. Accepts -1 (any depth), 0 (all pages), 1 (top-level pages only), and n (pages to the given n depth). Default 0. bool $echo Whether or not to echo the list of pages. Default true. string $exclude Comma-separated list of page IDs to exclude. Default empty. array $include Comma-separated list of page IDs to include. Default empty. string $link_after Text or HTML to follow the page link label. Default null. string $link_before Text or HTML to precede the page link label. Default null. string $post_type Post type to query for. Default 'page'. string $post_status Comma-separated list of post statuses to include. Default 'publish'. string $show_date Whether to display the page publish or modified date for each page. Accepts 'modified' or any other value. An empty value hides the date. Default empty. string $sort_column Comma-separated list of column names to sort the pages by. Accepts 'post_author', 'post_date', 'post_title', 'post_name', 'post_modified', 'post_modified_gmt', 'menu_order', 'post_parent', 'ID', 'rand', or 'comment_count'. Default 'post_title'. string $title_li List heading. Passing a null or empty value will result in no heading, and the list will not be wrapped with unordered list <ul> tags. Default 'Pages'. Walker $walker Walker instance to use for listing pages. Default empty (Walker_Page). }
Returns
string|void HTML list of pages.
Filter the array of pages to exclude from the pages list.
Since
2.1.0
Parameters
array $exclude_array An array of page IDs to exclude.
Filter the HTML output of the pages to list.
Since
1.5.1
4.4.0 $pages added as arguments.
See also
wp_list_pages()
Parameters
string $output HTML output of the pages list.
array $r An array of page-listing arguments.
array $pages List of WP_Post objects returned by get_pages()
Definition at line 1130 of file post-template.php.
References $output, __, apply_filters(), elseif, get_option(), get_pages(), get_queried_object(), get_queried_object_id(), is_attachment(), is_page(), is_post_type_hierarchical(), is_singular(), walk_page_tree(), and wp_parse_args().
Referenced by WP_Widget_Pages\widget(), and wp_page_menu().
wp_list_post_revisions ($post_id = 0, $type = 'all')
Display list of a post's revisions.
Can output either a UL with edit links or a TABLE with diff interface, and restore action links.
Since
2.6.0
Parameters
int | WP_Post $post_id Optional. Post ID or WP_Post object. Default is global $post.
string $type 'all' (default), 'revision' or 'autosave'
Definition at line 1705 of file post-template.php.
References $post, $post_id, __, _deprecated_argument(), current_user_can(), get_post(), wp_get_post_revisions(), wp_is_post_autosave(), and wp_post_revision_title_expanded().
Referenced by post_revisions_meta_box().
wp_page_menu ($args = array())
Display or retrieve list of pages with optional home link.
The arguments are listed below and part of the arguments are for wp_list_pages() function. Check that function for more info on those arguments.
Since
2.7.0
4.4.0 Added menu_id, container, before, after, and walker arguments.
Parameters
array | string $args { Optional. Arguments to generate a page menu. See wp_list_pages() for additional arguments.
string $sort_column How to short the list of pages. Accepts post column names. Default 'menu_order, post_title'. string $menu_id ID for the div containing the page list. Default is empty string. string $menu_class Class to use for the element containing the page list. Default 'menu'. string $container Element to use for the element containing the page list. Default 'div'. bool $echo Whether to echo the list or return it. Accepts true (echo) or false (return). Default true. int|bool|string $show_home Whether to display the link to the home page. Can just enter the text you'd like shown for the home link. 1|true defaults to 'Home'. string $link_before The HTML or text to prepend to $show_home text. Default empty. string $link_after The HTML or text to append to $show_home text. Default empty. string $before The HTML or text to prepend to the menu. Default is '
. string $after The HTML or text to append to the menu. Default is ''. Walker $walker Walker instance to use for listing pages. Default empty (Walker_Page). }
Returns
string|void HTML menu
Filter the arguments used to generate a page-based menu.
Since
2.7.0
See also
wp_page_menu()
Parameters
array $args An array of page menu arguments.
Filter the HTML output of a page-based menu.
Since
2.7.0
See also
wp_page_menu()
Parameters
string $menu The HTML output.
array $args An array of arguments.
Definition at line 1236 of file post-template.php.
References $class, $menu, $text, __, apply_filters(), esc_attr(), get_option(), home_url(), is_front_page(), is_paged(), sanitize_text_field(), str_replace, wp_list_pages(), and wp_parse_args().
wp_post_revision_title ($revision, $link = true)
Retrieve formatted date timestamp of a revision (linked to that revisions's page).
Since
2.6.0
Parameters
int | object $revision Revision ID or revision object.
bool $link Optional, default is true. Link to revisions's page?
Returns
string|false i18n formatted datetimestamp or localized 'Current Revision'.
Definition at line 1612 of file post-template.php.
References $datef, $link, _x, current_user_can(), date_i18n(), elseif, get_edit_post_link(), get_post(), wp_is_post_autosave(), and wp_is_post_revision().
wp_post_revision_title_expanded ($revision, $link = true)
Retrieve formatted date timestamp of a revision (linked to that revisions's page).
Since
3.6.0
Parameters
int | object $revision Revision ID or revision object.
bool $link Optional, default is true. Link to revisions's page?
Returns
string|false gravatar, user, i18n formatted datetimestamp or localized 'Current Revision'.
Filter the formatted author and date for a revision.
Since
4.4.0
Parameters
string $revision_date_author The formatted string.
WP_Post $revision The revision object.
bool $link Whether to link to the revisions page, as passed into wp_post_revision_title_expanded().
Definition at line 1647 of file post-template.php.
References $datef, $link, __, _x, apply_filters(), current_time(), current_user_can(), date_i18n(), elseif, get_edit_post_link(), get_post(), get_the_author_meta(), human_time_diff(), wp_is_post_autosave(), and wp_is_post_revision().
Referenced by wp_list_post_revisions().