GravityView: post-thumbnail-template.php File Reference
post-thumbnail-template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
get_post_thumbnail_id ($post=null)
Retrieve post thumbnail ID.
get_the_post_thumbnail ($post=null, $size= 'post-thumbnail', $attr= '')
Retrieve the post thumbnail.
get_the_post_thumbnail_url ($post=null, $size= 'post-thumbnail')
Return the post thumbnail URL.
has_post_thumbnail ($post=null)
Check if post has an image attached.
the_post_thumbnail ($size= 'post-thumbnail', $attr= '')
Display the post thumbnail.
the_post_thumbnail_url ($size= 'post-thumbnail')
Display the post thumbnail URL.
update_post_thumbnail_cache ($wp_query=null)
Update cache for thumbnails in the current loop.
Function Documentation
get_post_thumbnail_id ($post = null)
Retrieve post thumbnail ID.
Since
2.9.0
4.4.0 $post can be a post ID or WP_Post object.
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
string|int Post thumbnail ID or empty string.
Definition at line 34 of file post-thumbnail-template.php.
References $post, get_post(), and get_post_meta().
Referenced by wp_xmlrpc_server\_prepare_post(), edit_form_image_editor(), get_media_item(), get_oembed_response_data_rich(), get_the_post_thumbnail(), get_the_post_thumbnail_url(), has_post_thumbnail(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), prepend_attachment(), twentyfifteen_post_nav_background(), update_post_thumbnail_cache(), wp_playlist_shortcode(), and wp_prepare_attachment_for_js().
get_the_post_thumbnail ($post = null, $size = 'post-thumbnail', $attr = '')
Retrieve the post thumbnail.
When a theme adds 'post-thumbnail' support, a special 'post-thumbnail' image size is registered, which differs from the 'thumbnail' image size managed via the Settings > Media screen.
When using the_post_thumbnail() or related functions, the 'post-thumbnail' image size is used by default, though a different size can be specified instead as needed.
Since
2.9.0
4.4.0 $post can be a post ID or WP_Post object.
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
string | array $size Optional. Image size to use. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'post-thumbnail'.
string | array $attr Optional. Query string or array of attributes. Default empty.
Returns
string The post thumbnail image tag.
Filter the post thumbnail size.
Since
2.9.0
Parameters
string | array $size The post thumbnail size. Image size or array of width and height values (in that order). Default 'post-thumbnail'.
Fires before fetching the post thumbnail HTML.
Provides "just in time" filtering of all filters in wp_get_attachment_image().
Since
2.9.0
Parameters
int $post_id The post ID.
string $post_thumbnail_id The post thumbnail ID.
string | array $size The post thumbnail size. Image size or array of width and height values (in that order). Default 'post-thumbnail'.
Fires after fetching the post thumbnail HTML.
Since
2.9.0
Parameters
int $post_id The post ID.
string $post_thumbnail_id The post thumbnail ID.
string | array $size The post thumbnail size. Image size or array of width and height values (in that order). Default 'post-thumbnail'.
Filter the post thumbnail HTML.
Since
2.9.0
Parameters
string $html The post thumbnail HTML.
int $post_id The post ID.
string $post_thumbnail_id The post thumbnail ID.
string | array $size The post thumbnail size. Image size or array of width and height values (in that order). Default 'post-thumbnail'.
string $attr Query string of attributes.
Definition at line 114 of file post-thumbnail-template.php.
References $post, $size, apply_filters(), do_action(), get_post(), get_post_thumbnail_id(), in_the_loop(), update_post_thumbnail_cache(), and wp_get_attachment_image().
Referenced by the_post_thumbnail(), and Twenty_Fourteen_Ephemera_Widget\widget().
get_the_post_thumbnail_url ($post = null, $size = 'post-thumbnail')
Return the post thumbnail URL.
Since
4.4.0
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
string | array $size Optional. Registered image size to retrieve the source for or a flat array of height and width dimensions. Default 'post-thumbnail'.
Returns
string|false Post thumbnail URL or false if no URL is available.
Definition at line 190 of file post-thumbnail-template.php.
References $post, $size, get_post_thumbnail_id(), and wp_get_attachment_image_url().
Referenced by the_post_thumbnail_url().
has_post_thumbnail ($post = null)
Check if post has an image attached.
Since
2.9.0
4.4.0 $post can be a post ID or WP_Post object.
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
bool Whether the post has an image attached.
Definition at line 21 of file post-thumbnail-template.php.
References $post, and get_post_thumbnail_id().
Referenced by get_oembed_response_data_rich(), get_post_class(), prepend_attachment(), twentyfifteen_post_nav_background(), twentyfourteen_post_classes(), twentytwelve_body_class(), and Twenty_Fourteen_Ephemera_Widget\widget().
the_post_thumbnail ($size = 'post-thumbnail', $attr = '')
Display the post thumbnail.
When a theme adds 'post-thumbnail' support, a special 'post-thumbnail' image size is registered, which differs from the 'thumbnail' image size managed via the Settings > Media screen.
When using the_post_thumbnail() or related functions, the 'post-thumbnail' image size is used by default, though a different size can be specified instead as needed.
Since
2.9.0
See also
get_the_post_thumbnail()
Parameters
string | array $size Optional. Image size to use. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'post-thumbnail'.
string | array $attr Optional. Query string or array of attributes. Default empty.
Definition at line 61 of file post-thumbnail-template.php.
References $size, get_the_post_thumbnail(), and null.
the_post_thumbnail_url ($size = 'post-thumbnail')
Display the post thumbnail URL.
Since
4.4.0
Parameters
string | array $size Optional. Image size to use. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'post-thumbnail'.
Definition at line 207 of file post-thumbnail-template.php.
References $size, $url, esc_url, get_the_post_thumbnail_url(), and null.
update_post_thumbnail_cache ($wp_query = null)
Update cache for thumbnails in the current loop.
Since
3.2.0
WP_Query $wp_query
Parameters
WP_Query $wp_query Optional. A WP_Query instance. Defaults to the $wp_query global.
Definition at line 74 of file post-thumbnail-template.php.
References $GLOBALS, $id, $post, _prime_post_caches(), and get_post_thumbnail_id().
Referenced by get_the_post_thumbnail().