GravityView: post-formats.php File Reference
post-formats.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_post_format_get_term ($term)
Remove the post format prefix from the name property of the term object created by get_term().
_post_format_get_terms ($terms, $taxonomies, $args)
Remove the post format prefix from the name property of the term objects created by get_terms().
_post_format_link ($link, $term, $taxonomy)
Filters the post format term link to remove the format prefix.
_post_format_request ($qvs)
Filters the request to allow for the format prefix.
_post_format_wp_get_object_terms ($terms)
Remove the post format prefix from the name property of the term objects created by wp_get_object_terms().
get_post_format ($post=null)
Retrieve the format slug for a post.
get_post_format_link ($format)
Returns a link to a post format index.
get_post_format_slugs ()
Retrieves an array of post format slugs.
get_post_format_string ($slug)
Returns a pretty, translated version of a post format slug.
get_post_format_strings ()
Returns an array of post format slugs to their translated and pretty display versions.
has_post_format ($format=array(), $post=null)
Check if a post has any of the given formats, or any format.
set_post_format ($post, $format)
Assign a format to a post.
Function Documentation
_post_format_get_term ($term)
Remove the post format prefix from the name property of the term object created by get_term().
private
Since
3.1.0
Parameters
object $term
Returns
object
Definition at line 203 of file post-formats.php.
References get_post_format_string(), and str_replace.
_post_format_get_terms ($terms, $taxonomies, $args)
Remove the post format prefix from the name property of the term objects created by get_terms().
private
Since
3.1.0
Parameters
array $terms
string | array $taxonomies
array $args
Returns
array
Definition at line 221 of file post-formats.php.
References $name, get_post_format_string(), and str_replace.
_post_format_link ($link, $term, $taxonomy)
Filters the post format term link to remove the format prefix.
private
Since
3.1.0
WP_Rewrite $wp_rewrite
Parameters
string $link
object $term
string $taxonomy
Returns
string
Definition at line 181 of file post-formats.php.
References $link, $wp_rewrite, add_query_arg(), remove_query_arg(), and str_replace.
_post_format_request ($qvs)
Filters the request to allow for the format prefix.
private
Since
3.1.0
Parameters
array $qvs
Returns
array
Definition at line 156 of file post-formats.php.
References $tax, get_post_format_slugs(), get_taxonomy(), and is_admin().
_post_format_wp_get_object_terms ($terms)
Remove the post format prefix from the name property of the term objects created by wp_get_object_terms().
private
Since
3.1.0
Parameters
array $terms
Returns
array
Definition at line 247 of file post-formats.php.
References get_post_format_string(), and str_replace.
get_post_format ($post = null)
Retrieve the format slug for a post.
Since
3.1.0
Parameters
int | object | null $post Post ID or post object. Optional, default is the current post from the loop.
Returns
string|false The format if successful. False otherwise.
Definition at line 17 of file post-formats.php.
References $format, $post, get_post(), get_the_terms(), post_type_supports(), and str_replace.
Referenced by wp_xmlrpc_server\_prepare_post(), WP_Posts_List_Table\column_title(), _WP_Editors\editor_settings(), get_body_class(), get_inline_data(), get_post_class(), WP_Press_This\html(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), post_format_meta_box(), WP_Press_This\post_formats_html(), and Twenty_Eleven_Ephemera_Widget\widget().
get_post_format_link ($format)
Returns a link to a post format index.
Since
3.1.0
Parameters
string $format The post format slug.
Returns
string|WP_Error|false The post format term link.
Definition at line 140 of file post-formats.php.
References $format, get_term_by(), get_term_link(), and is_wp_error().
get_post_format_slugs ()
Retrieves an array of post format slugs.
Since
3.1.0
Returns
array The array of post format slugs.
Definition at line 111 of file post-formats.php.
References get_post_format_strings().
Referenced by _post_format_request(), add_theme_support(), and set_post_format().
get_post_format_string ($slug)
Returns a pretty, translated version of a post format slug.
Since
3.1.0
Parameters
string $slug A post format slug.
Returns
string The translated post format name.
Definition at line 124 of file post-formats.php.
References get_post_format_strings().
Referenced by _post_format_get_term(), _post_format_get_terms(), _post_format_wp_get_object_terms(), WP_Posts_List_Table\column_title(), Twenty_Fourteen_Ephemera_Widget\form(), WP_Press_This\html(), WP_Posts_List_Table\inline_edit(), post_format_meta_box(), and WP_Press_This\post_formats_html().
get_post_format_strings ()
Returns an array of post format slugs to their translated and pretty display versions.
Since
3.1.0
Returns
array The array of translated post format names.
Definition at line 88 of file post-formats.php.
References _x.
Referenced by get_post_format_slugs(), get_post_format_string(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), and wp_xmlrpc_server\wp_getPostFormats().
has_post_format ($format = array(), $post = null)
Check if a post has any of the given formats, or any format.
Since
3.1.0
Parameters
string | array $format Optional. The format or formats to check.
object | int | null $post Optional. The post to check. If not supplied, defaults to the current post if used in the loop.
Returns
bool True if the post has any of the given formats (or any format, if no format specified), false otherwise.
Definition at line 43 of file post-formats.php.
References $format, $post, has_term(), and sanitize_key().
Referenced by twentythirteen_content_width(), and Twenty_Fourteen_Ephemera_Widget\widget().
set_post_format ($post, $format)
Assign a format to a post.
Since
3.1.0
Parameters
int | object $post The post for which to assign a format.
string $format A format to assign. Use an empty string or array to remove all formats from the post.
Returns
array|WP_Error|false WP_Error on error. Array of affected term IDs on success.
Definition at line 64 of file post-formats.php.
References $format, $post, __, get_post(), get_post_format_slugs(), sanitize_key(), and wp_set_post_terms().
Referenced by wp_xmlrpc_server\_insert_post(), bulk_edit_posts(), GFFormsModel\create_post(), edit_post(), get_default_post_to_edit(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), and WP_Press_This\save_post().