GravityView: preview.php File Reference
preview.php File Reference
Variables
$form = RGFormsModel::get_form_meta($_GET['id'])
if(!class_exists('RGForms')) if(!GFCommon::current_user_can_any(array('gravityforms_edit_forms', 'gravityforms_create_form', 'gravityforms_preview_forms'))) $min = defined('SCRIPT_DEBUG') && SCRIPT_DEBUG || isset($_GET['gform_debug']) ? '' : '.min'
$styles = apply_filters('gform_preview_styles', array(), $form)
esc_html_e ('Form Preview', 'gravityforms')?></title >< link rel
Variable Documentation
$form = RGFormsModel::get_form_meta($_GET['id'])
Definition at line 52 of file preview.php.
Referenced by GV_UnitTest_Factory_For_View\__construct(), File_Upload_Upgrader\__construct(), GFAddOn\_can_enqueue_script(), GravityView_Uninstall_Test\_check_entries(), GFAddOn\_field_condition_matches(), GravityView_Field_List\_filter_field_label(), GravityView_Field\_filter_gform_custom_merge_tags(), GravityView_Field\_filter_gform_replace_merge_tags(), GravityView_Field_Time\_get_time_format_for_field(), GravityView_frontend\_override_sorting_id_by_field_type(), GravityView_Uninstall_Test\_set_up_entry_meta(), activate_save(), GravityView_frontend\add_columns_sort_links(), GFPaymentAddOn\add_creditcard_token_input(), GravityView_Admin_Views\add_custom_column_content(), GFExport\add_default_export_fields(), GFFormsModel\add_default_properties(), GFAPI\add_entry(), GFAPI\add_forms(), GravityView_Admin_Views\add_view_dropdown(), GravityView_Admin_ApproveEntries\after_update_entry_update_approved_meta(), GFPaymentAddOn\ajax_cancel_subscription(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), GFPaymentAddOn\before_delete_field(), GFFormsModel\build_lead_array(), WP_Customize_Widgets\call_widget_update(), GVCommon\check_entry_display(), GFFormDisplay\clean_up_files(), GFExport\cleanup(), GFFormSettings\confirmations_edit_page(), GFFormSettings\confirmations_list_page(), GFFormsModel\convert_confirmation(), GFFormsModel\convert_field_objects(), GFFormsModel\convert_property_to_merge_tag(), GFFormsModel\create_lead(), GFFormsModel\create_post(), GravityView_Ajax\create_preset_form(), GFForms\dashboard(), deactivate_save(), delete_confirmation(), GFFormsModel\delete_field(), GFFormsModel\delete_file(), GFFormsModel\delete_files(), GFFormsModel\delete_files_by_form(), GFAPI\delete_form(), GFFormsModel\delete_password(), GF_Field_Password\delete_passwords(), GFFormsModel\duplicate_form(), GFFormDisplay\enqueue_form_scripts(), GFForms\enqueue_form_scripts(), GFAddOn\enqueue_print_styles(), GFAddOn\enqueue_scripts(), GFFormDisplay\enqueue_scripts(), GravityView_Cache\entry_created(), GFPaymentAddOn\entry_post_save(), GravityView_Cache\entry_updated(), GFExport\export_form_page(), GFExport\export_lead_page(), GFFeedAddOn\feed_edit_page(), GFFeedAddOn\feed_list_page(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_API\field_label(), GravityView_API\field_value(), GravityView_Edit_Entry_Render\filter_conditional_logic(), GravityView_Edit_Entry_Render\filter_modify_form_fields(), GFForms\fix_checkbox_value(), GFForms\fix_leading_and_trailing_spaces(), GFFormDisplay\footer_init_scripts(), GFFeedAddOn\form_settings(), GFFormSettings\form_settings_ui(), GravityView_Admin_ApproveEntries\get_approved_column(), GravityView_Admin_Views\get_available_fields(), GravityView_Ajax\get_available_fields_html(), GravityView_Ajax_Test\get_available_fields_html_DEFAULT(), GFFormDisplay\get_calculations_init_script(), GFFormDisplay\get_chosen_init_script(), GFPaymentAddOn\get_column_value_amount(), GFFormDisplay\get_conditional_logic(), GFFormDisplay\get_conditional_logic_fields(), get_confirmation_ui_settings(), GravityView_Admin_Views\get_connected_form_links(), GFFormDisplay\get_counter_init_script(), GFPaymentAddOn\get_credit_card_field(), GFFormDisplay\get_currency_format_init_script(), GFFormsModel\get_current_lead(), GFFormsModel\get_custom_field(), GravityView_Admin_Views\get_entry_default_fields(), GFExport\get_entry_meta(), GFFeedAddOn\get_feed_table(), GVCommon\get_field(), GFFormDisplay\get_field(), GFFormsModel\get_field(), GF_Field_HTML\get_field_content(), GF_Field_Hidden\get_field_content(), GF_Field\get_field_content(), GFFormDisplay\get_field_content(), GFFormsModel\get_field_display(), GFFormsModel\get_field_filters_where(), GF_Field_SingleShipping\get_field_input(), GF_Field_Total\get_field_input(), GF_Field_Hidden\get_field_input(), GF_Field_Post_Image\get_field_input(), GF_Field_HiddenProduct\get_field_input(), GF_Field_Checkbox\get_field_input(), GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Post_Tags\get_field_input(), GF_Field_Calculation\get_field_input(), GF_Field_List\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_Select\get_field_input(), GF_Field_SingleProduct\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Post_Title\get_field_input(), GF_Field_Name\get_field_input(), GF_Field_Donation\get_field_input(), GF_Field_Radio\get_field_input(), GF_Field_Website\get_field_input(), GF_Field_Password\get_field_input(), GF_Field_Phone\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_MultiSelect\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_CreditCard\get_field_input(), GF_Field_Date\get_field_input(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GF_Field_Number\get_field_input(), GVCommon\get_field_label(), GFFormsModel\get_field_merge_tag(), GFExport\get_field_row_count(), GVCommon\get_field_type(), GFAddOn\get_field_value(), GFFormsModel\get_field_value_long(), GFAPI\get_fields_by_type(), GFFormsModel\get_fields_by_type(), GFEntryList\get_filter_links(), GFAddOn\get_first_field_by_type(), GF_Field_List\get_first_input_id(), GF_Field_FileUpload\get_first_input_id(), GF_Field_Time\get_first_input_id(), GF_Field\get_first_input_id(), GFAPI\get_form(), GFFormDisplay\get_form(), GVCommon\get_form_fields(), GVCommon\get_form_from_entry_id(), GFFormsModel\get_form_id(), GFFormDisplay\get_form_init_scripts(), GFFormsModel\get_form_meta(), GFFormsModel\get_form_meta_by_id(), GFFormsModel\get_forms(), GVCommon\get_forms(), GFFormsModel\get_grid_columns(), GFFormDisplay\get_honeypot_field(), GFFormDisplay\get_input_mask_init_script(), GFFormsModel\get_lead_field_value(), GFAddOn\get_mapped_field_value(), GFFormDisplay\get_max_field_id(), GFFormDisplay\get_max_page_number(), get_notification(), GFFormDisplay\get_number_formats_script(), GFPaymentAddOn\get_order_data(), GFFormsModel\get_page_by_number(), GFFormDisplay\get_password_strength_init_script(), GFPaymentAddOn\get_payment_choices(), GFPaymentAddOn\get_payment_feed(), GFFormsModel\get_post_fields(), GFFormsModel\get_prepared_input_value(), GFFormDisplay\get_progress_bar(), GravityView_Migrate\get_search_fields(), GravityView_Widget_Search\get_search_filter_details(), get_search_form(), GravityView_Widget_Search\get_searchable_fields(), GFFormsModel\get_section(), GFForms\get_shortcodes(), GravityView_Ajax\get_sortable_fields(), GFFormDisplay\get_state(), GFPaymentAddOn\get_submission_data(), GFFormDisplay\get_target_page(), GF_Field_Select\get_value_merge_tag(), GF_Field_Checkbox\get_value_merge_tag(), GF_Field_Radio\get_value_merge_tag(), GF_Field_Total\get_value_save_entry(), GF_Field_Post_Image\get_value_save_entry(), GF_Field_Phone\get_value_save_entry(), GF_Field_Calculation\get_value_save_entry(), GF_Field_Password\get_value_save_entry(), GF_Field_MultiSelect\get_value_save_entry(), GF_Field_Checkbox\get_value_save_entry(), GF_Field_Number\get_value_save_entry(), GF_Field_Radio\get_value_save_entry(), GF_Field_FileUpload\get_value_save_entry(), GF_Field\get_value_save_entry(), GF_Field_Date\get_year_dropdown(), GFFormDisplay\gform_footer(), GravityView_Edit_Entry_Render\gform_pre_validation(), gravityview_get_field(), gravityview_get_field_label(), gravityview_get_field_type(), gravityview_get_form_fields(), gv_class(), GFFormDisplay\handle_confirmation(), handle_confirmation_edit_submission(), GFFormDisplay\handle_save_confirmation(), GFFormDisplay\handle_save_email_confirmation(), GFFormDisplay\handle_submission(), GFFormDisplay\has_calculation_field(), GFFormDisplay\has_character_counter(), GFFormDisplay\has_conditional_logic(), GFFormDisplay\has_conditional_logic_legwork(), GFPaymentAddOn\has_credit_card_field(), GFFormDisplay\has_currency_copy_values_option(), GFFormDisplay\has_currency_format_number_field(), GFFormDisplay\has_datepicker_field(), GFFormDisplay\has_enhanced_dropdown(), GFFormDisplay\has_fileupload_field(), GFFormDisplay\has_input_mask(), GFFormDisplay\has_other_choice(), GFFormDisplay\has_pages(), GFFormDisplay\has_password_strength(), GFFeedAddOn\has_paypal_payment(), GFFormDisplay\has_placeholder(), GFFormDisplay\has_price_field(), GVCommon\has_product_field(), GFFormDisplay\has_recaptcha_field(), GFExport\import_xml(), GFFormDisplay\insert_review_page(), GFFormsModel\is_checkbox_checked(), GF_Field\is_description_above(), GFFeedAddOn\is_feed_condition_met(), GFFormsModel\is_field_hidden(), GVCommon\is_field_numeric(), GravityView_frontend\is_field_sortable(), GFFormDisplay\is_form_empty(), GFFormDisplay\is_last_page(), GFFormsModel\is_page_hidden(), GFFormsModel\is_unique_title(), GFEntryDetail\lead_detail_edit(), GFEntryDetail\lead_detail_grid(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GFFormsModel\load_confirmations(), GFFormsModel\load_notifications_from_legacy(), GFFormsModel\load_notifications_to_legacy(), GFFormDisplay\maybe_add_review_page(), GFExport\maybe_export(), GFAddOn\maybe_override_field_value(), GFFeedAddOn\maybe_process_feed(), GFFormsModel\maybe_sanitize_form_settings(), GFPaymentAddOn\maybe_validate(), notification_edit_page(), GFFeedAddOn\notification_events(), page_header(), GFEntryDetail\payment_details_box(), GFPaymentAddOn\post_payment_action(), GravityView_Ajax\pre_get_form_fields(), GravityView_Widget_Search\prepare_field_filter(), GFFormsModel\prepare_value(), GFFormDisplay\prev_field_has_description(), GFFormDisplay\print_form_scripts(), GFForms\print_form_scripts(), GFFormDisplay\process_form(), GFFormDisplay\process_send_resume_link(), GFPaymentAddOn\product_amount_choices(), GFPaymentAddOn\recurring_amount_choices(), GFFormsModel\refresh_product_cache(), GF_Field\register_form_init_scripts(), GFFormDisplay\register_form_init_scripts(), GravityView_Admin_Views\render_active_areas(), GravityView_Admin_Views\render_available_fields(), GravityView_Admin_Metaboxes\render_merge_tags_scripts(), GravityView_Merge_Tags\replace_get_variables(), GravityView_Merge_Tags\replace_gv_merge_tags(), GFFormDisplay\replace_save_variables(), GravityView_Merge_Tags\replace_variables(), GravityView_API\replace_variables(), GFForms\resend_notifications(), GFPaymentAddOn\results_data(), GFPaymentAddOn\results_fields(), GFFormsModel\sanitize_settings(), GFFormsModel\save_incomplete_submission(), GFFormsModel\save_input(), GFFormsModel\save_lead(), GFForms\select_export_form(), GFFormDisplay\send_emails(), GFAPI\send_notifications(), GFFormsModel\set_entry_meta(), GFPaymentAddOn\settings_setup_fee(), GFPaymentAddOn\settings_trial(), GFExport\start_export(), GFAPI\submit_form(), GravityView_View_Test\test_BackLinkLabel(), GravityView_Uninstall_Test\test_fire_everything(), GVCommon_Test\test_format_date(), GravityView_Merge_Tags_Test\test_gf_merge_tags(), GravityView_Merge_Tags_Test\test_replace_date_created(), GravityView_Merge_Tags_Test\test_replace_field_custom_merge_tags(), GravityView_Merge_Tags_Test\test_replace_user_variables_created_by(), GravityView_Entry_Link_Shortcode_Test\test_shortcode(), GFFeedAddOn\trim_conditional_logic_vales(), GFFormsModel\trim_conditional_logic_values(), GFFormsModel\trim_conditional_logic_values_from_element(), GFFormsModel\trim_form_meta_values(), GFFormDisplay\update_confirmation(), GFFormsModel\update_confirmation_active(), GFAPI\update_entry(), GFAPI\update_entry_field(), GFAPI\update_form(), GFAPI\update_forms(), GFFormsModel\update_lead_field_value(), GFFormsModel\update_lead_property(), GFForms\update_lead_status(), GFFormsModel\update_notification_active(), GravityView_Edit_Entry_User_Registration\update_user(), GFAsyncUpload\upload(), GFFormDisplay\upload_files(), GF_Field_FileUpload\validate(), GFFormDisplay\validate(), GFFormDisplay\validate_entry_limit(), GFFormDisplay\validate_form_schedule(), GFFormDisplay\validate_honeypot(), GFPaymentAddOn\validation(), wp_admin_bar_search_menu(), wp_ajax_save_widget(), WP_Customize_Widgets\wp_ajax_update_widget(), and wp_login_form().
if (!class_exists('RGForms')) if (!GFCommon::current_user_can_any(array('gravityforms_edit_forms', 'gravityforms_create_form', 'gravityforms_preview_forms'))) $min = defined('SCRIPT_DEBUG') && SCRIPT_DEBUG || isset($_GET['gform_debug']) ? '' : '.min'
Definition at line 24 of file preview.php.
Referenced by SimplePie_Parse_Date\date_asctime(), GF_Installation_Wizard\display(), GFFormDisplay\enqueue_form_scripts(), GFFormList\form_list_page(), GF_Field_Number\get_field_input(), GFPaymentAddOn\get_numeric_choices(), GF_Field_Number\get_range_message(), GFHelp\help_page(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GFForms\modify_tiny_mce_4(), notification_edit_page(), GFSettings\page_header(), GFExport\page_header(), GFFormDisplay\print_form_scripts(), print_tooltip_scripts(), random_int(), GFLocking\register_scripts(), GFForms\register_scripts(), GFAddOn\scripts(), GFPaymentAddOn\scripts(), GFAddOn\styles(), and GFUpdate\update_page().
$styles = apply_filters('gform_preview_styles', array(), $form)
Definition at line 56 of file preview.php.
Referenced by WP_Press_This\add_editor_style(), GFAddOn\add_no_conflict_styles(), GFAddOn\enqueue_print_styles(), GFAddOn\enqueue_scripts(), GravityView_Admin_ApproveEntries\register_gform_noconflict_style(), GFLocking\register_noconflict_styles(), GFAddOn\register_noconflict_styles(), GravityView_Settings\styles(), wp_ajax_parse_embed(), wp_ajax_parse_media_shortcode(), and wp_default_styles().
esc_html_e('Form Preview', 'gravityforms')?></title >< link rel
Initial value:
='stylesheet' href='<?php echo GFCommon::get_base_url() ?>/css/reset<?php echo $min; ?>.css' type='text/css' />
    <link rel='stylesheet' href='<?php echo GFCommon::get_base_url() ?>/css/formreset<?php echo $min; ?>.css' type='text/css' />
    <link rel='stylesheet' href='<?php echo GFCommon::get_base_url() ?>/css/datepicker<?php echo $min; ?>.css' type='text/css' />
    <link rel='stylesheet' href='<?php echo GFCommon::get_base_url() ?>/css/formsmain<?php echo $min; ?>.css' type='text/css' />
    <link rel='stylesheet' href='<?php echo GFCommon::get_base_url() ?>/css/readyclass<?php echo $min; ?>.css' type='text/css' />
    <link rel='stylesheet' href='<?php echo GFCommon::get_base_url() ?>/css/browsers<?php echo $min; ?>.css' type='text/css' />
<?php
if (is_rtl()) {
    ?>
    <link rel='stylesheet' href='<?php echo GFCommon::get_base_url() ?>/css/rtl<?php echo $min; ?>.css' type='text/css' />
    <?php
}
Definition at line 33 of file preview.php.
Referenced by GravityView_GF_Entries_List\add_edit_link(), GravityView_Admin_Add_Shortcode\add_shortcode_button(), GravityView_Admin_Add_Shortcode\add_shortcode_popup(), GravityView_Admin_Views\add_view_dropdown(), confirm_delete_users(), GFForms\dashboard(), GFForms\dashboard_update_message(), GF_Installation_Wizard_Step_Settings\display(), GF_Installation_Wizard_Step_Complete\display(), GF_Installation_Wizard_Step_License_Key\display(), GF_Installation_Wizard_Step_Background_Updates\display(), GF_Installation_Wizard\display(), GFAutoUpgrade\display_updates(), GFExport\export_form_page(), GFExport\export_lead_page(), GravityView_Search_WP_Widget\form(), GravityView_Recent_Entries_Widget\form(), GFHelp\help_page(), WP_Press_This\html(), GFExport\import_form_page(), GFEntryDetail\lead_detail_edit(), GFEntryDetail\lead_detail_grid(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), network_step1(), network_step2(), GFPaymentStatsTable\no_items(), GFEntryDetail\notes_grid(), GFEntryDetail\payment_details_box(), GFSettings\settings_uninstall_page(), GravityView_Welcome\tabs(), GFForms\top_toolbar(), GFUpdate\update_page(), GravityView_Support_Port\user_field(), WP_Media_List_Table\views(), wp_image_editor(), and wp_print_media_templates().