GravityView: print-entry.php File Reference
print-entry.php File Reference
Functions
gform_default_entry_content ($form, $entry, $entry_ids)
Variables
if(!empty($styles)) $auto_print = gf_apply_filters(array('gform_print_entry_disable_auto_print', $form['id']), false, $form) ? '' : 'onload="window.print();"'
Disable auto-print when the Print Entry view has fully loaded.
if(empty($form_id)||empty($lead_ids)) $form = RGFormsModel::get_form_meta($form_id)
$form_id = absint(rgget('fid'))
$leads = rgget('lid')
$min = defined('SCRIPT_DEBUG') && SCRIPT_DEBUG || isset($_GET['gform_debug']) ? '' : '.min'
$styles = apply_filters('gform_print_styles', false, $form)
if(0==$leads) else
esc_html_e ('close window', 'gravityforms')?></a ></span ><?php esc_html_e('Print Preview'
Function Documentation
gform_default_entry_content ($form, $entry, $entry_ids)
Allow the entry list search criteria to be overridden.
Since
1.9.14.30
Parameters
array $search_criteria An array containing the search criteria.
int $form_id The ID of the current form.
Output content for the current entry when looping through entries on the Print Entry view.
Since
1.9.14.16
Parameters
array $form Current Form object.
array $entry Current Entry object.
array $entry_ids Array of entry IDs to be printed.
See also
https://gist.github.com/spivurno/d617ce30b47d8a8bc8a8
Definition at line 25 of file print-entry.php.
References $form, GFFormsModel\get_lead_notes(), GFEntryDetail\lead_detail_grid(), and GFEntryDetail\notes_grid().
Variable Documentation
if (!empty($styles)) $auto_print = gf_apply_filters(array('gform_print_entry_disable_auto_print', $form['id']), false, $form) ? '' : 'onload="window.print();"'
Disable auto-print when the Print Entry view has fully loaded.
Since
1.9.14.16
Parameters
bool false Auto print is enabled by default. Set to true to disable.
array $form Current Form object.
See also
https://gist.github.com/spivurno/e7d1e4563986b3bc5ac4
Definition at line 146 of file print-entry.php.
if (empty($form_id)||empty($lead_ids)) $form = RGFormsModel::get_form_meta($form_id)
Definition at line 108 of file print-entry.php.
Referenced by gform_default_entry_content().
$form_id = absint(rgget('fid'))
Definition at line 50 of file print-entry.php.
$leads = rgget('lid')
Definition at line 51 of file print-entry.php.
Referenced by GFFormsModel\build_lead_array(), GFFormsModel\delete_leads(), GFFormsModel\get_lead(), GFFormsModel\get_leads(), GFFormsModel\get_leads_by_meta(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GFForms\resend_notifications(), GFFormsModel\search_leads(), GFExport\start_export(), and GFFormsModel\update_leads_property().
$min = defined('SCRIPT_DEBUG') && SCRIPT_DEBUG || isset($_GET['gform_debug']) ? '' : '.min'
Definition at line 110 of file print-entry.php.
$styles = apply_filters('gform_print_styles', false, $form)
Definition at line 131 of file print-entry.php.
if (0==$leads) else
Initial value:
{
    $lead_ids = explode( ',', $leads )
Definition at line 97 of file print-entry.php.
esc_html_e('close window', 'gravityforms')?></a ></span ><?php esc_html_e('Print Preview'
Definition at line 154 of file print-entry.php.