GravityView: query.php File Reference
query.php File Reference
Data Structures
class WP_Query
The WordPress Query class.
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
get_queried_object ()
Retrieve the currently-queried object.
get_queried_object_id ()
Retrieve ID of the current queried object.
get_query_var ($var, $default= '')
Retrieve variable in the WP_Query class.
have_comments ()
Whether there are comments to loop over.
have_posts ()
Whether current WordPress query has results to loop over.
in_the_loop ()
Whether the caller is in the Loop.
is_404 ()
Is the query a 404 (returns no results)?
is_archive ()
Is the query for an existing archive page?
is_attachment ($attachment= '')
Is the query for an existing attachment page?
is_author ($author= '')
Is the query for an existing author archive page?
is_category ($category= '')
Is the query for an existing category archive page?
is_comment_feed ()
Is the query for a comments feed?
is_date ()
Is the query for an existing date archive?
is_day ()
Is the query for an existing day archive?
is_embed ()
Is the query for an embedded post?
is_feed ($feeds= '')
Is the query for a feed?
is_front_page ()
Is the query for the front page of the site?
is_home ()
Is the query for the blog homepage?
is_main_query ()
Is the query the main query?
is_month ()
Is the query for an existing month archive?
is_page ($page= '')
Is the query for an existing single page?
is_paged ()
Is the query for paged result and not for the first page?
is_post_type_archive ($post_types= '')
Is the query for an existing post type archive page?
is_preview ()
Is the query for a post or page preview?
is_robots ()
Is the query for the robots file?
is_search ()
Is the query for a search?
is_single ($post= '')
Is the query for an existing single post?
is_singular ($post_types= '')
Is the query for an existing single post of any post type (post, attachment, page, ...
is_tag ($tag= '')
Is the query for an existing tag archive page?
is_tax ($taxonomy= '', $term= '')
Is the query for an existing taxonomy archive page?
is_time ()
Is the query for a specific time?
is_trackback ()
Is the query for a trackback endpoint call?
is_year ()
Is the query for an existing year archive?
query_posts ($query)
Set up The Loop with query parameters.
rewind_posts ()
Rewind the loop posts.
set_query_var ($var, $value)
Set query variable.
setup_postdata ($post)
Set up global post data.
the_comment ()
Iterate comment index in the comment loop.
the_post ()
Iterate the post index in the loop.
wp_old_slug_redirect ()
Redirect old slugs to the correct permalink.
wp_reset_postdata ()
After looping through a separate query, this function restores the $post global to the current post in the main query.
wp_reset_query ()
Destroy the previous query and set up a new query.
Function Documentation
get_queried_object ()
Retrieve the currently-queried object.
Wrapper for WP_Query::get_queried_object().
Since
3.1.0 public
WP_Query $wp_query Global WP_Query instance.
Returns
object Queried object.
Definition at line 43 of file query.php.
Referenced by edit_term_link(), feed_links_extra(), get_attachment_template(), get_author_template(), get_category_template(), get_page_template(), get_single_template(), get_tag_template(), get_taxonomy_template(), get_the_archive_title(), WP\handle_404(), single_post_title(), single_term_title(), term_description(), wp_get_document_title(), wp_list_categories(), wp_list_pages(), wp_old_slug_redirect(), and wp_title().
get_queried_object_id ()
Retrieve ID of the current queried object.
Wrapper for WP_Query::get_queried_object_id().
Since
3.1.0
WP_Query $wp_query Global WP_Query instance.
Returns
int ID of the queried object.
Definition at line 59 of file query.php.
Referenced by get_page_template(), is_page_template(), redirect_canonical(), rel_canonical(), wp_get_shortlink(), wp_list_categories(), wp_list_comments(), and wp_list_pages().
get_query_var ($var, $default = '')
Retrieve variable in the WP_Query class.
Since
1.5.0
3.9.0 The $default argument was introduced.
WP_Query $wp_query Global WP_Query instance.
Parameters
string $var The variable key to retrieve.
mixed $default Optional. Value to return if the query variable is not set. Default empty.
Returns
mixed Contents of the query variable.
Definition at line 26 of file query.php.
References $default.
Referenced by comments_template(), do_feed(), feed_links_extra(), get_archive_template(), get_body_class(), get_comment_link(), get_comment_pages_count(), get_next_comments_link(), get_page_of_comment(), get_page_template(), get_post_type_archive_template(), get_posts_nav_link(), get_previous_comments_link(), get_search_query(), WP\handle_404(), GravityView_frontend\is_single_entry(), paginate_comments_links(), paginate_links(), post_type_archive_title(), redirect_canonical(), redirect_guess_404_permalink(), rel_canonical(), single_month_title(), wp_dropdown_categories(), wp_dropdown_users(), wp_list_comments(), wp_old_slug_redirect(), and wp_title().
have_comments ()
Whether there are comments to loop over.
Since
2.2.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 816 of file query.php.
have_posts ()
Whether current WordPress query has results to loop over.
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 760 of file query.php.
Referenced by _wp_ajax_menu_quick_search(), WP_Media_List_Table\display_rows(), WP_Posts_List_Table\has_items(), and WP_Media_List_Table\has_items().
in_the_loop ()
Whether the caller is in the Loop.
Since
2.0.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool True if caller is within loop, false if loop hasn't started or ended.
Definition at line 774 of file query.php.
Referenced by get_the_post_thumbnail(), WP_Query\have_posts(), WP_Query\init(), GravityView_frontend\single_entry_title(), and WP_Query\the_post().
is_404 ()
Is the query a 404 (returns no results)?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 690 of file query.php.
References __, and _doing_it_wrong().
Referenced by wp_old_slug_redirect().
is_archive ()
Is the query for an existing archive page?
Month, Year, Category, Author, Post Type archive...
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 145 of file query.php.
References __, and _doing_it_wrong().
Referenced by get_body_class(), twentyfourteen_body_classes(), and wp_title().
is_attachment ($attachment = '')
Is the query for an existing attachment page?
Since
2.0.0
WP_Query $wp_query Global WP_Query instance.
Parameters
int | string | array | object $attachment Attachment ID, title, slug, or array of such.
Returns
bool
Definition at line 187 of file query.php.
References __, and _doing_it_wrong().
Referenced by adjacent_posts_rel_link_wp_head(), get_adjacent_post_link(), get_adjacent_post_rel_link(), get_body_class(), get_boundary_post(), get_post_class(), redirect_canonical(), twentyeleven_custom_excerpt_more(), twentyfifteen_post_nav_background(), twentyfourteen_body_classes(), twentyfourteen_content_width(), twentyfourteen_post_classes(), twentyten_custom_excerpt_more(), twentythirteen_body_class(), twentythirteen_content_width(), twentytwelve_content_width(), wp_embed_excerpt_attachment(), and wp_list_pages().
is_author ($author = '')
Is the query for an existing author archive page?
If the $author parameter is specified, this function will additionally check if the query is for one of the authors specified.
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Parameters
mixed $author Optional. User ID, nickname, nicename, or array of User IDs, nicknames, and nicenames
Returns
bool
Definition at line 211 of file query.php.
References __, and _doing_it_wrong().
Referenced by feed_links_extra(), get_body_class(), get_the_archive_title(), WP\handle_404(), redirect_canonical(), wp_dropdown_users(), wp_get_document_title(), and wp_title().
is_category ($category = '')
Is the query for an existing category archive page?
If the $category parameter is specified, this function will additionally check if the query is for one of the categories specified.
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Parameters
mixed $category Optional. Category ID, name, slug, or array of Category IDs, names, and slugs.
Returns
bool
Definition at line 235 of file query.php.
References __, and _doing_it_wrong().
Referenced by feed_links_extra(), get_body_class(), get_the_archive_title(), WP\handle_404(), redirect_canonical(), single_term_title(), term_description(), wp_dropdown_categories(), wp_get_document_title(), wp_list_categories(), and wp_title().
is_comment_feed ()
Is the query for a comments feed?
Since
3.0.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 369 of file query.php.
References __, and _doing_it_wrong().
is_date ()
Is the query for an existing date archive?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 308 of file query.php.
References __, and _doing_it_wrong().
Referenced by get_body_class().
is_day ()
Is the query for an existing day archive?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 328 of file query.php.
References __, and _doing_it_wrong().
Referenced by get_the_archive_title(), redirect_canonical(), and wp_get_document_title().
is_embed ()
Is the query for an embedded post?
Since
4.4.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool Whether we're in an embedded post or not.
Definition at line 710 of file query.php.
References __, and _doing_it_wrong().
Referenced by is_admin_bar_showing(), wp_embed_excerpt_more(), and wp_old_slug_redirect().
is_feed ($feeds = '')
Is the query for a feed?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Parameters
string | array $feeds Optional feed types to check.
Returns
bool
Definition at line 349 of file query.php.
References __, and _doing_it_wrong().
Referenced by gallery_shortcode(), WP\handle_404(), redirect_canonical(), twentyfourteen_wp_title(), twentythirteen_wp_title(), twentytwelve_wp_title(), wp_old_slug_redirect(), and wp_playlist_shortcode().
is_front_page ()
Is the query for the front page of the site?
This is for what is displayed at your site's main URL.
Depends on the site's "Front page displays" Reading Settings 'show_on_front' and 'page_on_front'.
If you set a static page for the front page of your site, this function will return true when viewing that page.
Otherwise the same as
See also
is_home()
Since
2.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool True, if front of site.
Definition at line 398 of file query.php.
References __, and _doing_it_wrong().
Referenced by _wp_menu_item_classes_by_context(), get_body_class(), redirect_canonical(), twentyfourteen_body_classes(), twentyfourteen_scripts(), twentyfourteen_wp_title(), twentythirteen_wp_title(), twentytwelve_wp_title(), wp_get_document_title(), wp_oembed_add_discovery_links(), wp_page_menu(), and wp_title().
is_home ()
Is the query for the blog homepage?
This is the page which shows the time based blog content of your site.
Depends on the site's "Front page displays" Reading Settings 'show_on_front' and 'page_for_posts'.
If you set a static page for the front page of your site, this function will return true only on the page you set as the "Posts page".
See also
is_front_page()
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool True if blog view homepage.
Definition at line 427 of file query.php.
References __, and _doing_it_wrong().
Referenced by get_body_class(), get_post_class(), WP\handle_404(), redirect_canonical(), twentyeleven_body_classes(), twentyfourteen_body_classes(), twentyfourteen_wp_title(), twentythirteen_wp_title(), twentytwelve_wp_title(), wp_get_document_title(), and wp_title().
is_main_query ()
Is the query the main query?
Since
3.3.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 730 of file query.php.
References $message, __, _doing_it_wrong(), and current_filter().
is_month ()
Is the query for an existing month archive?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 447 of file query.php.
References __, and _doing_it_wrong().
Referenced by get_the_archive_title(), redirect_canonical(), and wp_get_document_title().
is_page ($page = '')
Is the query for an existing single page?
If the $page parameter is specified, this function will additionally check if the query is for one of the pages specified.
See also
is_single()
is_singular()
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Parameters
int | string | array $page Optional. Page ID, title, slug, or array of such. Default empty.
Returns
bool Whether the query is for an existing single page.
Definition at line 474 of file query.php.
References $page, __, and _doing_it_wrong().
Referenced by comments_template(), get_body_class(), is_page_template(), redirect_canonical(), wp_list_pages(), and wp_title().
is_paged ()
Is the query for paged result and not for the first page?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 494 of file query.php.
References __, and _doing_it_wrong().
Referenced by get_body_class(), get_post_class(), WP\handle_404(), twentyfourteen_has_featured_posts(), and wp_page_menu().
is_post_type_archive ($post_types = '')
Is the query for an existing post type archive page?
Since
3.1.0
WP_Query $wp_query Global WP_Query instance.
Parameters
string | array $post_types Optional. Post type or array of posts types to check against.
Returns
bool
Definition at line 166 of file query.php.
References __, and _doing_it_wrong().
Referenced by _wp_menu_item_classes_by_context(), feed_links_extra(), get_body_class(), get_the_archive_title(), WP\handle_404(), post_type_archive_title(), wp_get_document_title(), and wp_title().
is_preview ()
Is the query for a post or page preview?
Since
2.0.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 514 of file query.php.
References __, and _doing_it_wrong().
Referenced by _wp_link_page(), GravityView_API\entry_link(), GF_Field_CreditCard\get_form_inline_script_on_page_render(), GravityView_frontend\insert_view_in_content(), redirect_canonical(), and wp_post_preview_js().
is_robots ()
Is the query for the robots file?
Since
2.1.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 534 of file query.php.
References __, and _doing_it_wrong().
Referenced by WP\handle_404(), and redirect_canonical().
is_search ()
Is the query for a search?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 554 of file query.php.
References __, and _doing_it_wrong().
Referenced by feed_links_extra(), get_body_class(), WP\handle_404(), redirect_canonical(), GravityView_frontend\setIsSearch(), twentyfourteen_body_classes(), wp_get_document_title(), and wp_title().
is_single ($post = '')
Is the query for an existing single post?
Works for any post type, except attachments and pages
If the $post parameter is specified, this function will additionally check if the query is for one of the Posts specified.
See also
is_page()
is_singular()
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Parameters
int | string | array $post Optional. Post ID, title, slug, or array of such. Default empty.
Returns
bool Whether the query is for an existing single post.
Definition at line 583 of file query.php.
References $post, __, and _doing_it_wrong().
Referenced by adjacent_posts_rel_link_wp_head(), comments_template(), get_body_class(), get_boundary_post(), get_next_posts_link(), get_next_posts_page_link(), get_previous_posts_link(), get_previous_posts_page_link(), redirect_canonical(), twentyfifteen_post_nav_background(), and wp_title().
is_singular ($post_types = '')
Is the query for an existing single post of any post type (post, attachment, page, ...
)?
If the $post_types parameter is specified, this function will additionally check if the query is for one of the Posts Types specified.
See also
is_page()
is_single()
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Parameters
string | array $post_types Optional. Post type or array of post types. Default empty.
Returns
bool Whether the query is for an existing single post of any of the given post types.
Definition at line 610 of file query.php.
References __, and _doing_it_wrong().
Referenced by WP_Media_List_Table\extra_tablenav(), WP_Posts_List_Table\extra_tablenav(), feed_links_extra(), get_body_class(), get_next_comments_link(), get_posts_nav_link(), get_previous_comments_link(), WP\handle_404(), paginate_comments_links(), redirect_canonical(), rel_canonical(), twentyeleven_body_classes(), twentyfifteen_scripts(), twentyfourteen_body_classes(), twentyfourteen_scripts(), twentythirteen_scripts_styles(), twentytwelve_scripts_styles(), wp_get_document_title(), wp_get_shortlink(), wp_list_comments(), wp_list_pages(), and wp_oembed_add_discovery_links().
is_tag ($tag = '')
Is the query for an existing tag archive page?
If the $tag parameter is specified, this function will additionally check if the query is for one of the tags specified.
Since
2.3.0
WP_Query $wp_query Global WP_Query instance.
Parameters
mixed $tag Optional. Tag ID, name, slug, or array of Tag IDs, names, and slugs.
Returns
bool
Definition at line 259 of file query.php.
References __, and _doing_it_wrong().
Referenced by feed_links_extra(), get_body_class(), get_the_archive_title(), WP\handle_404(), redirect_canonical(), single_term_title(), term_description(), wp_get_document_title(), wp_list_categories(), and wp_title().
is_tax ($taxonomy = '', $term = '')
Is the query for an existing taxonomy archive page?
If the $taxonomy parameter is specified, this function will additionally check if the query is for that specific $taxonomy.
If the $term parameter is specified in addition to the $taxonomy parameter, this function will additionally check if the query is for one of the terms specified.
Since
2.5.0
WP_Query $wp_query Global WP_Query instance.
Parameters
string | array $taxonomy Optional. Taxonomy slug or slugs.
int | string | array $term Optional. Term ID, name, slug or array of Term IDs, names, and slugs.
Returns
bool
Definition at line 288 of file query.php.
References __, and _doing_it_wrong().
Referenced by get_body_class(), get_the_archive_title(), WP\handle_404(), redirect_canonical(), single_term_title(), term_description(), wp_get_document_title(), wp_list_categories(), and wp_title().
is_time ()
Is the query for a specific time?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 630 of file query.php.
References __, and _doing_it_wrong().
is_trackback ()
Is the query for a trackback endpoint call?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 650 of file query.php.
References __, and _doing_it_wrong().
Referenced by redirect_canonical().
is_year ()
Is the query for an existing year archive?
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Returns
bool
Definition at line 670 of file query.php.
References __, and _doing_it_wrong().
Referenced by get_the_archive_title(), redirect_canonical(), and wp_get_document_title().
query_posts ($query)
Set up The Loop with query parameters.
This will override the current WordPress Loop and shouldn't be used more than once. This must not be used within the WordPress Loop.
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Parameters
string $query
Returns
array List of posts
Definition at line 92 of file query.php.
References $GLOBALS.
Referenced by _wp_ajax_menu_quick_search().
rewind_posts ()
Rewind the loop posts.
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Definition at line 786 of file query.php.
set_query_var ($var, $value)
Set query variable.
Since
2.2.0
WP_Query $wp_query Global WP_Query instance.
Parameters
string $var Query variable key.
mixed $value Query variable value.
Definition at line 74 of file query.php.
References $value.
Referenced by comments_template(), and wp_list_comments().
setup_postdata ($post)
Set up global post data.
Since
1.5.0
4.4.0 Added the ability to pass a post ID to $post.
WP_Query $wp_query Global WP_Query instance.
Parameters
WP_Post | object | int $post WP_Post instance or Post ID/object.
Returns
bool True when finished.
Definition at line 5052 of file query.php.
References $post.
Referenced by GFForms\handle_ajax_do_shortcode(), WP_Posts_List_Table\single_row(), start_wp(), wp_ajax_parse_embed(), and wp_ajax_parse_media_shortcode().
the_comment ()
Iterate comment index in the comment loop.
Since
2.2.0
WP_Query $wp_query Global WP_Query instance.
Returns
object
Definition at line 830 of file query.php.
the_post ()
Iterate the post index in the loop.
Since
1.5.0
WP_Query $wp_query Global WP_Query instance.
Definition at line 798 of file query.php.
Referenced by _wp_ajax_menu_quick_search(), and WP_Media_List_Table\display_rows().
wp_old_slug_redirect ()
Redirect old slugs to the correct permalink.
Attempts to find the current slug from the past slugs.
Since
2.1.0
WP_Query $wp_query Global WP_Query instance. wpdb $wpdb WordPress database abstraction object. WP_Rewrite $wp_rewrite WordPress rewrite component.
Filter the old slug redirect URL.
Since
4.4.0
Parameters
string $link The redirect URL.
Definition at line 4959 of file query.php.
References $GLOBALS, $id, $link, $post_type, $wp_rewrite, $wpdb, apply_filters(), elseif, endif, exit, get_permalink(), get_queried_object(), get_query_var(), is_404(), is_embed(), is_feed(), is_post_type_hierarchical(), trailingslashit(), and user_trailingslashit().
wp_reset_postdata ()
After looping through a separate query, this function restores the $post global to the current post in the main query.
Since
3.0.0
WP_Query $wp_query Global WP_Query instance.
Definition at line 122 of file query.php.
Referenced by GravityView_Merge_Tags_Test\test_gf_merge_tags(), WP_Widget_Recent_Posts\widget(), Twenty_Eleven_Ephemera_Widget\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), and wp_reset_query().
wp_reset_query ()
Destroy the previous query and set up a new query.
This should be used after query_posts() and before another query_posts(). This will remove obscure bugs that occur when the previous wp_query object is not destroyed properly before another is set up.
Since
2.3.0
WP_Query $wp_query Global WP_Query instance. WP_Query $wp_the_query Copy of the global WP_Query instance created during wp_reset_query().
Definition at line 109 of file query.php.
References $GLOBALS, and wp_reset_postdata().