GravityView: recaptchalib.php File Reference
recaptchalib.php File Reference
Functions
_recaptcha_aes_encrypt ($val, $ky)
_recaptcha_aes_pad ($val)
_recaptcha_http_post ($host, $path, $data, $port=80)
Submits an HTTP POST to a reCAPTCHA server.
_recaptcha_mailhide_email_parts ($email)
_recaptcha_mailhide_urlbase64 ($x)
_recaptcha_qsencode ($data)
Encodes the given data into a query string format.
if(!class_exists('ReCaptchaResponse')) recaptcha_check_answer ($privkey, $remoteip, $challenge, $response, $extra_params=array())
A ReCaptchaResponse is returned from recaptcha_check_answer()
recaptcha_get_html ($pubkey, $error=null, $use_ssl=false, $lang='en')
Gets the challenge HTML (javascript and non-javascript version).
recaptcha_get_signup_url ($domain=null, $appname=null)
gets a URL where the user can sign up for reCAPTCHA.
recaptcha_mailhide_html ($pubkey, $privkey, $email)
Gets html to display an email address given a public an private key.
recaptcha_mailhide_url ($pubkey, $privkey, $email)
Variables
const RECAPTCHA_API_SECURE_SERVER "https://www.google.com/recaptcha/api"
const RECAPTCHA_API_SERVER "http://www.google.com/recaptcha/api"
The reCAPTCHA server URL's.
const RECAPTCHA_VERIFY_SERVER "www.google.com"
Function Documentation
_recaptcha_aes_encrypt ($val, $ky)
Definition at line 217 of file recaptchalib.php.
References $mode, and _recaptcha_aes_pad().
Referenced by recaptcha_mailhide_url().
_recaptcha_aes_pad ($val)
Definition at line 209 of file recaptchalib.php.
Referenced by _recaptcha_aes_encrypt().
_recaptcha_http_post ($host, $path, $data, $port = 80)
Submits an HTTP POST to a reCAPTCHA server.
Parameters
string $host
string $path
array $data
int port
Returns
array response
Definition at line 67 of file recaptchalib.php.
References _recaptcha_qsencode().
Referenced by recaptcha_check_answer().
_recaptcha_mailhide_email_parts ($email)
Definition at line 251 of file recaptchalib.php.
Referenced by recaptcha_mailhide_html().
_recaptcha_mailhide_urlbase64 ($x)
Definition at line 228 of file recaptchalib.php.
Referenced by recaptcha_mailhide_url().
_recaptcha_qsencode ($data)
Encodes the given data into a query string format.
Parameters
$data - array of string elements to be encoded
Returns
string - encoded request
Definition at line 47 of file recaptchalib.php.
References $value.
Referenced by _recaptcha_http_post(), and recaptcha_get_signup_url().
if (!class_exists('ReCaptchaResponse')) recaptcha_check_answer ($privkey, $remoteip, $challenge, $response, $extra_params = array())
A ReCaptchaResponse is returned from recaptcha_check_answer()
Calls an HTTP POST function to verify if the user's guess was correct
Parameters
string $privkey
string $remoteip
string $challenge
string $response
array $extra_params an array of extra variables to post to the server
Returns
ReCaptchaResponse
Definition at line 155 of file recaptchalib.php.
References _recaptcha_http_post(), null, and RECAPTCHA_VERIFY_SERVER.
Referenced by GF_Field_CAPTCHA\validate().
recaptcha_get_html ($pubkey, $error = null, $use_ssl = false, $lang = 'en')
Gets the challenge HTML (javascript and non-javascript version).
This is called from the browser, and the resulting reCAPTCHA HTML widget is embedded within the HTML form it was called from.
Parameters
string $pubkey A public key for reCAPTCHA
string $error The error given by reCAPTCHA (optional, default is null)
boolean $use_ssl Should the request be made over ssl? (optional, default is false)
Returns
string - The HTML to be embedded in the user's form.
Definition at line 106 of file recaptchalib.php.
References $lang, null, RECAPTCHA_API_SECURE_SERVER, and RECAPTCHA_API_SERVER.
Referenced by GF_Field_CAPTCHA\get_field_input().
recaptcha_get_signup_url ($domain = null, $appname = null)
gets a URL where the user can sign up for reCAPTCHA.
If your application has a configuration page where you enter a key, you should provide a link using this function.
Parameters
string $domain The domain where the page is hosted
string $appname The name of your application
Definition at line 205 of file recaptchalib.php.
References _recaptcha_qsencode().
recaptcha_mailhide_html ($pubkey, $privkey, $email)
Gets html to display an email address given a public an private key.
to get a key, go to:
http://www.google.com/recaptcha/mailhide/apikey
Definition at line 270 of file recaptchalib.php.
References $url, _recaptcha_mailhide_email_parts(), and recaptcha_mailhide_url().
recaptcha_mailhide_url ($pubkey, $privkey, $email)
Definition at line 233 of file recaptchalib.php.
References _recaptcha_aes_encrypt(), _recaptcha_mailhide_urlbase64(), and null.
Referenced by recaptcha_mailhide_html().
Variable Documentation
const RECAPTCHA_API_SECURE_SERVER "https://www.google.com/recaptcha/api"
Definition at line 39 of file recaptchalib.php.
Referenced by recaptcha_get_html().
const RECAPTCHA_API_SERVER "http://www.google.com/recaptcha/api"
The reCAPTCHA server URL's.
Definition at line 38 of file recaptchalib.php.
Referenced by recaptcha_get_html().
const RECAPTCHA_VERIFY_SERVER "www.google.com"
Definition at line 40 of file recaptchalib.php.
Referenced by recaptcha_check_answer().