GravityView: rewrite.php File Reference
rewrite.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_filter_taxonomy_base ($base)
Filter the URL base for taxonomies.
add_feed ($feedname, $function)
Add a new feed type like /atom1/.
add_permastruct ($name, $struct, $args=array())
Add permalink structure.
add_rewrite_endpoint ($name, $places, $query_var=true)
Add an endpoint, like /trackback/.
add_rewrite_rule ($regex, $query, $after= 'bottom')
Adds a rewrite rule that transforms a URL structure to a set of query vars.
add_rewrite_tag ($tag, $regex, $query= '')
Add a new rewrite tag (like postname%).
flush_rewrite_rules ($hard=true)
Remove rewrite rules and then recreate rewrite rules.
remove_permastruct ($name)
Remove permalink structure.
remove_rewrite_tag ($tag)
Removes an existing rewrite tag (like postname%).
url_to_postid ($url)
Examine a url and try to determine the post ID it represents.
wp_resolve_numeric_slug_conflicts ($query_vars=array())
Resolve numeric slugs that collide with date permalinks.
Variables
const EP_ALL EP_PERMALINK | EP_ATTACHMENT | EP_ROOT | EP_COMMENTS | EP_SEARCH | EP_PAGES | EP_ALL_ARCHIVES
Endpoint Mask for everything.
const EP_ALL_ARCHIVES EP_DATE | EP_YEAR | EP_MONTH | EP_DAY | EP_CATEGORIES | EP_TAGS | EP_AUTHORS
Endpoint Mask for all archive views.
const EP_ATTACHMENT 2
Endpoint Mask for Attachment.
const EP_AUTHORS 2048
Endpoint Mask for authors.
const EP_CATEGORIES 512
Endpoint Mask for categories.
const EP_COMMENTS 128
Endpoint Mask for comments.
const EP_DATE 4
Endpoint Mask for date.
const EP_DAY 32
Endpoint Mask for day.
const EP_MONTH 16
Endpoint Mask for month.
const EP_NONE 0
Endpoint Mask for default, which is nothing.
const EP_PAGES 4096
Endpoint Mask for pages.
const EP_PERMALINK 1
Endpoint Mask for Permalink.
const EP_ROOT 64
Endpoint Mask for root.
const EP_SEARCH 256
Endpoint Mask for searches.
const EP_TAGS 1024
Endpoint Mask for tags.
const EP_YEAR 8
Endpoint Mask for year.
Function Documentation
_wp_filter_taxonomy_base ($base)
Filter the URL base for taxonomies.
To remove any manually prepended /index.php/.
private
Since
2.6.0
Parameters
string $base The taxonomy base that we're going to filter
Returns
string
Definition at line 324 of file rewrite.php.
add_feed ($feedname, $function)
Add a new feed type like /atom1/.
Since
2.1.0
WP_Rewrite $wp_rewrite
Parameters
string $feedname Feed name.
callable $function Callback to run on feed display.
Returns
string Feed action name.
Definition at line 244 of file rewrite.php.
References $wp_rewrite, add_action(), and remove_action().
add_permastruct ($name, $struct, $args = array())
Add permalink structure.
Since
3.0.0
See also
WP_Rewrite::add_permastruct() WP_Rewrite $wp_rewrite WordPress rewrite component.
Parameters
string $name Name for permalink structure.
string $struct Permalink structure.
array $args Optional. Arguments for building the rules from the permalink structure, see WP_Rewrite::add_permastruct() for full details. Default empty array.
Definition at line 202 of file rewrite.php.
References $name, and $wp_rewrite.
Referenced by register_post_type(), and register_taxonomy().
add_rewrite_endpoint ($name, $places, $query_var = true)
Add an endpoint, like /trackback/.
Adding an endpoint creates extra rewrite rules for each of the matching places specified by the provided bitmask. For example:
add_rewrite_endpoint('json', EP_PERMALINK | EP_PAGES);
will add a new rewrite rule ending with "json(/(.*))?/?$" for every permastruct that describes a permalink (post) or page. This is rewritten to "json=$match" where $match is the part of the URL matched by the endpoint regex (e.g. "foo" in "[permalink]/json/foo/").
A new query var with the same name as the endpoint will also be created.
When specifying $places ensure that you are using the EP_* constants (or a combination of them using the bitwise OR operator) as their values are not guaranteed to remain static (especially EP_ALL).
Be sure to flush the rewrite rules - see flush_rewrite_rules() - when your plugin gets activated and deactivated.
Since
2.1.0
4.3.0 Added support for skipping query var registration by passing false to $query_var.
WP_Rewrite $wp_rewrite
Parameters
string $name Name of the endpoint.
int $places Endpoint mask describing the places the endpoint should be added.
string | bool $query_var Name of the corresponding query variable. Pass false to skip registering a query_var for this endpoint. Defaults to the value of $name.
Definition at line 308 of file rewrite.php.
References $name, and $wp_rewrite.
Referenced by GravityView_Post_Types\init_rewrite().
add_rewrite_rule ($regex, $query, $after = 'bottom')
Adds a rewrite rule that transforms a URL structure to a set of query vars.
Any value in the $after parameter that isn't 'bottom' will result in the rule being placed at the top of the rewrite rules.
Since
2.1.0
4.4.0 Array support was added to the $query parameter.
WP_Rewrite $wp_rewrite WordPress Rewrite Component.
Parameters
string $regex Regular expression to match request against.
string | array $query The corresponding query vars for this rewrite rule.
string $after Optional. Priority of the new rule. Accepts 'top' or 'bottom'. Default 'bottom'.
Definition at line 137 of file rewrite.php.
References $wp_rewrite.
Referenced by register_post_type(), and rest_api_register_rewrites().
add_rewrite_tag ($tag, $regex, $query = '')
Add a new rewrite tag (like postname%).
The $query parameter is optional. If it is omitted you must ensure that you call this on, or before, the 'init' hook. This is because $query defaults to "$tag=", and for this to work a new query var has to be added.
Since
2.1.0
WP_Rewrite $wp_rewrite WP $wp
Parameters
string $tag Name of the new rewrite tag.
string $regex Regular expression to substitute the tag for in rewrite rules.
string $query Optional. String to append to the rewritten query. Must end in '='. Default empty.
Definition at line 159 of file rewrite.php.
References $wp, and $wp_rewrite.
Referenced by register_post_type(), and register_taxonomy().
flush_rewrite_rules ($hard = true)
Remove rewrite rules and then recreate rewrite rules.
Since
3.0.0
WP_Rewrite $wp_rewrite
Parameters
bool $hard Whether to update .htaccess (hard flush) or just update rewrite_rules transient (soft flush). Default is true (hard).
Definition at line 271 of file rewrite.php.
References $wp_rewrite.
Referenced by GravityView_Plugin\activate(), check_theme_switched(), GravityView_Plugin\deactivate(), GV_Unit_Tests_Bootstrap\load_rest_api(), populate_network(), rest_api_maybe_flush_rewrites(), and update_home_siteurl().
remove_permastruct ($name)
Remove permalink structure.
Can only be used to remove permastructs that were added using add_permastruct(). Built-in permastructs cannot be removed.
Since
4.5.0
See also
WP_Rewrite::remove_permastruct() WP_Rewrite $wp_rewrite WordPress rewrite component.
Parameters
string $name Name for permalink structure.
Definition at line 227 of file rewrite.php.
References $name, and $wp_rewrite.
Referenced by unregister_taxonomy().
remove_rewrite_tag ($tag)
Removes an existing rewrite tag (like postname%).
Since
4.5.0
WP_Rewrite $wp_rewrite WordPress rewrite component.
Parameters
string $tag Name of the rewrite tag.
Definition at line 184 of file rewrite.php.
References $wp_rewrite.
Referenced by unregister_taxonomy().
url_to_postid ($url)
Examine a url and try to determine the post ID it represents.
Checks are supposedly from the hosted site blog.
Since
1.0.0
WP_Rewrite $wp_rewrite WP $wp
Parameters
string $url Permalink to check.
Returns
int Post ID, or 0 on failure.
Filter the URL to derive the post ID from.
Since
2.2.0
Parameters
string $url The URL to derive the post ID from.
Definition at line 462 of file rewrite.php.
References $home_path, $id, $page, $post_type, $url, $value, $wp, $wp_rewrite, absint(), WP_MatchesMapRegex\apply(), apply_filters(), get_page_by_path(), get_post_status_object(), get_post_types(), home_url(), set_url_scheme(), str_replace, trailingslashit(), and wp_resolve_numeric_slug_conflicts().
Referenced by WP_oEmbed_Controller\get_item(), GravityView_oEmbed\get_postid_from_url_and_slug(), is_local_attachment(), pingback(), wp_xmlrpc_server\pingback_extensions_getPingbacks(), wp_xmlrpc_server\pingback_ping(), and wp_xmlrpc_server\wp_newComment().
wp_resolve_numeric_slug_conflicts ($query_vars = array())
Resolve numeric slugs that collide with date permalinks.
Permalinks of posts with numeric slugs can sometimes look to WP_Query::parse_query() like a date archive, as when your permalink structure is /year%/postname%/ and a post with post_name '05' has the URL /2015/05/.
This function detects conflicts of this type and resolves them in favor of the post permalink.
Note that, since 4.3.0, wp_unique_post_slug() prevents the creation of post slugs that would result in a date archive conflict. The resolution performed in this function is primarily for legacy content, as well as cases when the admin has changed the site's permalink structure in a way that introduces URL conflicts.
Since
4.3.0
Parameters
array $query_vars Optional. Query variables for setting up the loop, as determined in WP::parse_request(). Default empty array.
Returns
array Returns the original array of query vars, with date/post conflicts resolved.
Definition at line 354 of file rewrite.php.
References $post, $value, elseif, get_option(), get_page_by_path(), and OBJECT.
Referenced by WP\parse_request(), and url_to_postid().
Variable Documentation
const EP_ALL EP_PERMALINK | EP_ATTACHMENT | EP_ROOT | EP_COMMENTS | EP_SEARCH | EP_PAGES | EP_ALL_ARCHIVES
Endpoint Mask for everything.
Since
2.1.0
Definition at line 119 of file rewrite.php.
Referenced by GravityView_Post_Types\init_rewrite().
const EP_ALL_ARCHIVES EP_DATE | EP_YEAR | EP_MONTH | EP_DAY | EP_CATEGORIES | EP_TAGS | EP_AUTHORS
Endpoint Mask for all archive views.
Since
3.7.0
Definition at line 112 of file rewrite.php.
const EP_ATTACHMENT 2
Endpoint Mask for Attachment.
Since
2.1.0
Definition at line 28 of file rewrite.php.
Referenced by WP_Rewrite\generate_rewrite_rules().
const EP_AUTHORS 2048
Endpoint Mask for authors.
Since
2.1.0
Definition at line 98 of file rewrite.php.
Referenced by WP_Rewrite\rewrite_rules().
const EP_CATEGORIES 512
Endpoint Mask for categories.
Since
2.1.0
Definition at line 84 of file rewrite.php.
Referenced by create_initial_taxonomies().
const EP_COMMENTS 128
Endpoint Mask for comments.
Since
2.1.0
Definition at line 70 of file rewrite.php.
Referenced by WP_Rewrite\rewrite_rules().
const EP_DATE 4
Endpoint Mask for date.
Since
2.1.0
Definition at line 35 of file rewrite.php.
Referenced by WP_Rewrite\rewrite_rules().
const EP_DAY 32
Endpoint Mask for day.
Since
2.1.0
Definition at line 56 of file rewrite.php.
Referenced by WP_Rewrite\generate_rewrite_rules().
const EP_MONTH 16
Endpoint Mask for month.
Since
2.1.0
Definition at line 49 of file rewrite.php.
Referenced by WP_Rewrite\generate_rewrite_rules().
const EP_NONE 0
Endpoint Mask for default, which is nothing.
Since
2.1.0
Definition at line 14 of file rewrite.php.
Referenced by WP_Rewrite\add_permastruct(), WP_Rewrite\generate_rewrite_rule(), WP_Rewrite\generate_rewrite_rules(), and register_taxonomy().
const EP_PAGES 4096
Endpoint Mask for pages.
Since
2.1.0
Definition at line 105 of file rewrite.php.
Referenced by WP_Rewrite\generate_rewrite_rules(), and WP_Rewrite\page_rewrite_rules().
const EP_PERMALINK 1
Endpoint Mask for Permalink.
Since
2.1.0
Definition at line 21 of file rewrite.php.
Referenced by WP_Rewrite\generate_rewrite_rules(), register_post_type(), and WP_Rewrite\rewrite_rules().
const EP_ROOT 64
Endpoint Mask for root.
Since
2.1.0
Definition at line 63 of file rewrite.php.
Referenced by WP_Rewrite\generate_rewrite_rules(), and WP_Rewrite\rewrite_rules().
const EP_SEARCH 256
Endpoint Mask for searches.
Since
2.1.0
Definition at line 77 of file rewrite.php.
Referenced by WP_Rewrite\rewrite_rules().
const EP_TAGS 1024
Endpoint Mask for tags.
Since
2.3.0
Definition at line 91 of file rewrite.php.
Referenced by create_initial_taxonomies().
const EP_YEAR 8
Endpoint Mask for year.
Since
2.1.0
Definition at line 42 of file rewrite.php.
Referenced by WP_Rewrite\generate_rewrite_rules().