GravityView: rss.php File Reference
rss.php File Reference
Data Structures
class MagpieRSS
class RSSCache
Namespaces
External
kses 0.2.2 - HTML/XHTML filter that only allows some elements and attributes Copyright (C) 2002, 2003, 2005 Ulf Harnhammar
Functions
_fetch_remote_file ($url, $headers="")
_response_to_rss ($resp)
init ()
is_client_error ($sc)
is_error ($sc)
is_info ($sc)
is_redirect ($sc)
is_server_error ($sc)
is_success ($sc)
Variables
const ATOM 'Atom'
if(!function_exists('fetch_rss'))($url) endif
const MAGPIE_USER_AGENT 'WordPress/' . $GLOBALS['wp_version']
const RSS 'RSS'
RSS feed constant.
Function Documentation
_fetch_remote_file ($url, $headers = "")
Definition at line 552 of file rss.php.
References $url, $value, is_wp_error(), wp_remote_retrieve_body(), wp_remote_retrieve_headers(), wp_remote_retrieve_response_code(), and wp_safe_remote_request().
_response_to_rss ($resp)
Definition at line 595 of file rss.php.
References $field.
init ()
Definition at line 642 of file rss.php.
References $GLOBALS.
Referenced by _WP_Editors\editor_js(), GFFeedAddOn\init(), and GFPaymentAddOn\init().
is_client_error ($sc)
Definition at line 709 of file rss.php.
is_error ($sc)
Definition at line 705 of file rss.php.
is_info ($sc)
Definition at line 693 of file rss.php.
is_redirect ($sc)
Definition at line 701 of file rss.php.
is_server_error ($sc)
Definition at line 713 of file rss.php.
is_success ($sc)
Definition at line 697 of file rss.php.
Variable Documentation
const ATOM 'Atom'
Definition at line 31 of file rss.php.
Referenced by MagpieRSS\feed_cdata(), MagpieRSS\feed_end_element(), MagpieRSS\feed_start_element(), and MagpieRSS\is_atom().
if (!function_exists('get_rss')) ($url, $num_items=5) endif
Definition at line 403 of file rss.php.
const MAGPIE_USER_AGENT 'WordPress/' . $GLOBALS['wp_version']
Definition at line 32 of file rss.php.
const RSS 'RSS'
RSS feed constant.
Definition at line 30 of file rss.php.
Referenced by export_wp(), MagpieRSS\feed_end_element(), MagpieRSS\feed_start_element(), and MagpieRSS\is_rss().