GravityView: screen.php File Reference
screen.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
add_screen_option ($option, $args=array())
Register and configure an admin screen option.
get_column_headers ($screen)
Get the column headers for a screen.
get_current_screen ()
Get the current screen object.
get_hidden_columns ($screen)
Get a list of hidden columns.
get_hidden_meta_boxes ($screen)
Get Hidden Meta Boxes.
meta_box_prefs ($screen)
Prints the meta box preferences for screen meta.
set_current_screen ($hook_name= '')
Set the current screen object.
Function Documentation
add_screen_option ($option, $args = array())
Register and configure an admin screen option.
Since
3.1.0
Parameters
string $option An option name.
mixed $args Option-dependent arguments.
Definition at line 187 of file screen.php.
References $current_screen, $option, and get_current_screen().
get_column_headers ($screen)
Get the column headers for a screen.
Since
2.7.0
array $column_headers
Parameters
string | WP_Screen $screen The screen you want the headers for
Returns
array Containing the headers in the format id => UI String
Filter the column headers for a list table on a specific screen.
The dynamic portion of the hook name, $screen->id, refers to the ID of a specific screen. For example, the screen ID for the Posts list table is edit-post, so the filter for that screen would be manage_edit-post_columns.
Since
3.0.0
Parameters
array $columns An array of column headers. Default empty.
Definition at line 19 of file screen.php.
References $screen, apply_filters(), and convert_to_screen().
Referenced by _WP_List_Table_Compat\get_column_info(), WP_List_Table\get_column_info(), WP_List_Table\get_primary_column_name(), WP_Screen\render_list_table_columns_preferences(), and WP_Screen\show_screen_options().
get_current_screen ()
Get the current screen object.
Since
3.1.0
WP_Screen $current_screen
Returns
WP_Screen Current screen object
Definition at line 205 of file screen.php.
References $current_screen, and null.
Referenced by _get_list_table(), add_meta_box(), add_screen_option(), GravityView_Admin_Views\add_view_dropdown(), Custom_Background\admin_load(), do_accordion_sections(), do_meta_boxes(), WP_Screen\get(), Custom_Image_Header\help(), iframe_header(), page_attributes_meta_box(), post_comment_meta_box(), remove_meta_box(), WP_Screen\render_view_mode(), screen_layout(), screen_meta(), screen_options(), twentyeleven_theme_options_help(), twentyfourteen_contextual_help(), wp_add_dashboard_widget(), wp_admin_bar_edit_menu(), wp_auth_check_load(), wp_dashboard(), and wp_dashboard_setup().
get_hidden_columns ($screen)
Get a list of hidden columns.
Since
2.7.0
Parameters
string | WP_Screen $screen The screen you want the hidden columns for
Returns
array
Filter the default list of hidden columns.
Since
4.4.0
Parameters
array $hidden An array of columns hidden by default.
WP_Screen $screen WP_Screen object of the current screen.
Filter the list of hidden columns.
Since
4.4.0
4.4.1 Added the use_defaults parameter.
Parameters
array $hidden An array of hidden columns.
WP_Screen $screen WP_Screen object of the current screen.
bool $use_defaults Whether to show the default columns.
Definition at line 53 of file screen.php.
References $screen, apply_filters(), convert_to_screen(), and get_user_option().
Referenced by _WP_List_Table_Compat\get_column_info(), WP_List_Table\get_column_info(), and WP_Screen\render_list_table_columns_preferences().
get_hidden_meta_boxes ($screen)
Get Hidden Meta Boxes.
Since
2.7.0
Parameters
string | WP_Screen $screen Screen identifier
Returns
array Hidden Meta Boxes
Filter the default list of hidden meta boxes.
Since
3.1.0
Parameters
array $hidden An array of meta boxes hidden by default.
WP_Screen $screen WP_Screen object of the current screen.
Filter the list of hidden meta boxes.
Since
3.3.0
Parameters
array $hidden An array of hidden meta boxes.
WP_Screen $screen WP_Screen object of the current screen.
bool $use_defaults Whether to show the default meta boxes. Default true.
Definition at line 137 of file screen.php.
References $screen, apply_filters(), convert_to_screen(), and get_user_option().
Referenced by do_accordion_sections(), do_meta_boxes(), meta_box_prefs(), and post_comment_meta_box().
meta_box_prefs ($screen)
Prints the meta box preferences for screen meta.
Since
2.7.0
array $wp_meta_boxes
Parameters
WP_Screen $screen
Definition at line 98 of file screen.php.
References $screen, convert_to_screen(), and get_hidden_meta_boxes().
Referenced by WP_Screen\render_meta_boxes_preferences().
set_current_screen ($hook_name = '')
Set the current screen object.
Since
3.0.0
Parameters
mixed $hook_name Optional. The hook name (also known as the hook suffix) used to determine the screen, or an existing screen object.
Definition at line 222 of file screen.php.
References WP_Screen\get().
Referenced by WP_Ajax_UnitTestCase\setUp(), WP_Ajax_UnitTestCase\tearDown(), Tests_REST_API\test_rest_url_scheme(), and wp_ajax_dashboard_widgets().