GravityView: script-loader.php File Reference
script-loader.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_print_scripts ()
Print scripts (internal use only)
_print_styles ()
Print styles (internal use only)
_wp_footer_scripts ()
Private, for use in *_footer_scripts hooks.
print_admin_styles ()
Prints the styles queue in the HTML head on admin pages.
print_footer_scripts ()
Prints the scripts that were queued for the footer or too late for the HTML head.
print_head_scripts ()
Prints the script queue in the HTML head on admin pages.
print_late_styles ()
Prints the styles that were queued too late for the HTML head.
script_concat_settings ()
Determine the concatenation and compression settings for scripts and styles.
wp_default_scripts (&$scripts)
BackPress: WordPress Dependencies Class.
wp_default_styles (&$styles)
Assign default styles to $styles object.
wp_enqueue_scripts ()
Wrapper for do_action('wp_enqueue_scripts')
wp_just_in_time_script_localization ()
Load localized data on print rather than initialization.
wp_print_footer_scripts ()
Hooks to print the scripts and styles in the footer.
wp_print_head_scripts ()
Prints the script queue in the HTML head on the front end.
wp_prototype_before_jquery ($js_array)
Reorder JavaScript scripts array to place prototype before jQuery.
wp_style_loader_src ($src, $handle)
Administration Screen CSS for changing the styles.
Function Documentation
_print_scripts ()
Print scripts (internal use only)
WP_Scripts $wp_scripts bool $compress_scripts
Definition at line 954 of file script-loader.php.
References $wp_scripts, and esc_attr().
Referenced by print_footer_scripts(), and print_head_scripts().
_print_styles ()
Print styles (internal use only)
bool $compress_css
Definition at line 1124 of file script-loader.php.
References $dir, $href, $wp_styles, esc_attr(), and wp_styles().
Referenced by GFAddOn\enqueue_print_styles(), GFAddOn\enqueue_scripts(), print_admin_styles(), and print_late_styles().
_wp_footer_scripts ()
Private, for use in *_footer_scripts hooks.
Since
3.3.0
Definition at line 1013 of file script-loader.php.
References print_footer_scripts(), and print_late_styles().
print_admin_styles ()
Prints the styles queue in the HTML head on admin pages.
Since
2.8.0
bool $concatenate_scripts
Returns
array
Filter whether to print the admin styles.
Since
2.8.0
Parameters
bool $print Whether to print the admin styles. Default true.
Definition at line 1058 of file script-loader.php.
References $wp_styles, _print_styles(), apply_filters(), script_concat_settings(), and wp_styles().
print_footer_scripts ()
Prints the scripts that were queued for the footer or too late for the HTML head.
Since
2.8.0
WP_Scripts $wp_scripts bool $concatenate_scripts
Returns
array
Filter whether to print the footer scripts.
Since
2.8.0
Parameters
bool $print Whether to print the footer scripts. Default true.
Definition at line 921 of file script-loader.php.
References $wp_scripts, _print_scripts(), apply_filters(), and script_concat_settings().
Referenced by _wp_footer_scripts().
print_head_scripts ()
Prints the script queue in the HTML head on admin pages.
Postpones the scripts that were queued for the footer. print_footer_scripts() is called in the footer to print these scripts.
Since
2.8.0
See also
wp_print_scripts()
bool $concatenate_scripts
Returns
array
This action is documented in wp-includes/functions.wp-scripts.php
Filter whether to print the head scripts.
Since
2.8.0
Parameters
bool $print Whether to print the head scripts. Default true.
Definition at line 882 of file script-loader.php.
References $wp_scripts, _print_scripts(), apply_filters(), did_action(), do_action(), script_concat_settings(), and wp_scripts().
Referenced by wp_print_head_scripts().
print_late_styles ()
Prints the styles that were queued too late for the HTML head.
Since
3.3.0
WP_Styles $wp_styles bool $concatenate_scripts
Returns
array|void
Filter whether to print the styles queued too late for the HTML head.
Since
3.3.0
Parameters
bool $print Whether to print the 'late' styles. Default true.
Definition at line 1092 of file script-loader.php.
References $wp_styles, _print_styles(), and apply_filters().
Referenced by _wp_footer_scripts().
script_concat_settings ()
Determine the concatenation and compression settings for scripts and styles.
Since
2.8.0
bool $concatenate_scripts bool $compress_scripts bool $compress_css
Definition at line 1159 of file script-loader.php.
References get_site_option(), and is_admin().
Referenced by _WP_Editors\editor_js(), print_admin_styles(), print_footer_scripts(), and print_head_scripts().
wp_default_scripts (& $scripts)
BackPress: WordPress Dependencies Class.
BackPress: WordPress Scripts Class BackPress: WordPress Scripts Functions BackPress: WordPress Styles Class BackPress: WordPress Styles Functions Register all WordPress scripts.
Localizes some of them. args order: $scripts->add('handle', 'url', 'dependencies', 'query-string', 1); when last arg === 1 queues the script for the footer
Since
2.6.0
Parameters
WP_Scripts $scripts WP_Scripts object.
Filter the Heartbeat settings.
Since
3.6.0
Parameters
array $settings Heartbeat settings array.
Filter the authentication check interval.
Since
3.6.0
Parameters
int $interval The interval in which to check a user's authentication. Default 3 minutes in seconds, or 180.
Filter the MediaElement configuration settings.
Since
4.4.0
Parameters
array $mejs_settings MediaElement settings array.
Definition at line 50 of file script-loader.php.
References $GLOBALS, $wp_version, __, _x, ABSPATH, admin_url(), apply_filters(), did_action(), esc_attr__(), get_bloginfo(), get_current_user_id(), includes_url(), is_admin(), site_url(), SITECOOKIEPATH, wp_guess_url(), and WPINC.
wp_default_styles (& $styles)
Assign default styles to $styles object.
Nothing is returned, because the $styles parameter is passed by reference. Meaning that whatever object is passed will be updated without having to reassign the variable that was passed back to the same value. This saves memory.
Adding default styles is not the only task, it also assigns the base_url property, the default version, and text direction for the object.
Since
2.6.0
Parameters
WP_Styles $styles
Definition at line 671 of file script-loader.php.
References $styles, $wp_version, _x, ABSPATH, elseif, get_bloginfo(), is_rtl(), site_url(), wp_guess_url(), and WPINC.
wp_enqueue_scripts ()
Wrapper for do_action('wp_enqueue_scripts')
Allows plugins to queue scripts for the front end using wp_enqueue_script(). Runs first in wp_head() where all is_home(), is_page(), etc. functions are available.
Since
2.8.0
Fires when scripts and styles are enqueued.
Since
2.8.0
Definition at line 1040 of file script-loader.php.
References do_action().
wp_just_in_time_script_localization ()
Load localized data on print rather than initialization.
These localizations require information that may not be loaded even by init.
Since
2.5.0
Definition at line 808 of file script-loader.php.
References get_current_blog_id(), and wp_localize_script().
wp_print_footer_scripts ()
Hooks to print the scripts and styles in the footer.
Since
2.8.0
Fires when footer scripts are printed.
Since
2.8.0
Definition at line 1023 of file script-loader.php.
References do_action().
wp_print_head_scripts ()
Prints the script queue in the HTML head on the front end.
Postpones the scripts that were queued for the footer. wp_print_footer_scripts() is called in the footer to print these scripts.
Since
2.8.0
WP_Scripts $wp_scripts
Returns
array
This action is documented in wp-includes/functions.wp-scripts.php
Definition at line 994 of file script-loader.php.
References $wp_scripts, did_action(), do_action(), and print_head_scripts().
wp_prototype_before_jquery ($js_array)
Reorder JavaScript scripts array to place prototype before jQuery.
Since
2.3.1
Parameters
array $js_array JavaScript scripts array
Returns
array Reordered array, if needed.
Definition at line 784 of file script-loader.php.
wp_style_loader_src ($src, $handle)
Administration Screen CSS for changing the styles.
If installing the 'wp-admin/' directory will be replaced with './'.
The $_wp_admin_css_colors global manages the Administration Screens CSS stylesheet that is loaded. The option that is set is 'admin_color' and is the color and key for the array. The value for the color key is an object with a 'url' parameter that has the URL path to the CSS file.
The query from $src parameter will be appended to the URL that is given from the $_wp_admin_css_colors array value URL.
Since
2.6.0 array $_wp_admin_css_colors
Parameters
string $src Source URL.
string $handle Either 'colors' or 'colors-rtl'.
Returns
string|false URL path to CSS stylesheet for Administration Screens.
Definition at line 837 of file script-loader.php.
References $url, add_query_arg(), get_user_option(), wp_installing(), and wp_parse_str().