GravityView: search-field-chainedselect.php File Reference
search-field-chainedselect.php File Reference
Variables
$alignment = apply_filters('gravityview/search/chained_selects/alignment', $gravityview_view->search_layout, $search_field)
Prevent Chained Select Search Bar input fields from outputting styles.
$field = \GV\GF_Field::by_id($form, $search_field['key'])
if(! class_exists('GF_Chained_Field_Select')) if(empty($search_field['choices'])) $form = \GV\GF_Form::from_form($gravityview_view->getForm())
$gf_field = $field->field
$gravityview_view = GravityView_View::getInstance()
$hide_inactive = apply_filters('gravityview/search/chained_selects/hide_inactive', false, $search_field)
Choose whether to hide inactive dropdowns in the chain.
$search_field = $gravityview_view->search_field
$view_id = $gravityview_view->getViewId()
$gf_field chainedSelectsAlignment = $gravityview_view->search_layout
if (! gv_empty($search_field[ 'label'], false, false))
Variable Documentation
$alignment
$alignment = apply_filters('gravityview/search/chained_selects/alignment', $gravityview_view->search_layout, $search_field)
Prevent Chained Select Search Bar input fields from outputting styles.
Since
TODO
Parameters
GravityView_Widget_Search $this GravityView Widget instance
array{key:string,label:string,value:string,type:string,choices:array} $search_field
Definition at line 40 of file search-field-chainedselect.php.
$field
$field = \GV\GF_Field::by_id($form, $search_field['key'])
Definition at line 29 of file search-field-chainedselect.php.
Referenced by Entry_Sort\__construct(), Field_Template\__construct(), GravityView_Field_List\_filter_field_label(), GravityView_Field_Time\_get_time_format_for_field(), Request\_has_field_key(), Field_Collection\add(), GravityView_frontend\add_columns_sort_links(), GravityView_Field_Password\add_form_fields(), GravityView_Plugin_Hooks_Gravity_Forms_Signature\after_edit_entry(), GravityView_Edit_Entry_Render\after_update(), GV\app_settings_fields(), GravityView_Field_Date\apply_format_date_modifiers(), GV\as_html(), Internal_Field\by_id(), GF_Field\by_id(), Field_Collection\by_position(), Field_Collection\by_visible(), gvfield\callback(), GravityView_Delete_Entry\check_user_cap_delete_entry(), GravityView_Duplicate_Entry\check_user_cap_duplicate_entry(), GravityView_Edit_Entry_Render\check_user_cap_edit_field(), GravityView_Fields\create(), GravityView_Edit_Entry_Render\custom_validation(), GravityView_Plugin_Hooks_Gravity_Forms_Signature\edit_entry_field_input(), GravityView_Field_Post_Custom_Field\edit_entry_field_value(), GravityView_Plugin_Hooks_Gravity_Forms_Coupon\edit_entry_field_value(), GravityView_Field_Hidden\edit_entry_fix_hidden_fields(), GravityView_Plugin_Hooks_Gravity_Perks\edit_entry_fix_uid_fields(), GravityView_Field_Post_Image\explode_value(), GravityView_API\field_class(), GravityView_HTML_Elements\field_dropdown(), GravityView_API\field_html_attr_id(), GravityView_API\field_label(), GravityView_Field_Password\field_label(), GravityView_Field_Survey\field_options(), GravityView_API\field_width(), GravityView_Edit_Entry_Render\filter_admin_only_fields(), GravityView_Edit_Entry_Render\filter_conditional_logic(), GravityView_Widget_Search\filter_entries(), GravityView_Edit_Entry_Render\fix_multiselect_value_serialization(), GravityView_Plugin_Hooks_Gravity_Forms_Survey\fix_survey_field_value(), GravityView_Edit_Entry_Render\form_prepare_for_save(), GF_Field\from_configuration(), Internal_Field\from_configuration(), Field_Collection\from_configuration(), Field\from_configuration(), Entry\from_field(), Field_Collection\get(), GravityView_Fields\get_all(), GravityView_Entry_Approval\get_approved_column_input_label(), GravityView_Fields\get_associated_field(), GravityView_Admin_Views\get_available_fields(), GravityView_Field_Survey\get_choice_score(), GravityView_Edit_Entry_Render\get_configured_edit_fields(), GravityView_Field_Payment_Amount\get_content(), GravityView_Field_Is_Fulfilled\get_content(), GravityView_Field_Transaction_Type\get_content(), GravityView_Field_Date_Created\get_content(), GravityView_Field_Date_Updated\get_content(), View\get_entries(), GVCommon\get_entry_meta(), GVCommon\get_field_array(), View_Table_Template\get_field_column_label(), GravityView_Field_Post_Content\get_field_input(), GravityView_Field_FileUpload\get_field_input(), GVCommon\get_field_label(), GravityView_Widget_Search\get_field_label(), GVCommon\get_field_type(), GravityView_Edit_Entry_Render\get_field_value(), GF_Form\get_fields(), GravityView_Field_FileUpload\get_files_array(), GVCommon\get_form_fields(), GravityView_frontend\get_search_criteria_paging(), GravityView_Migrate\get_search_fields(), GravityView_Widget_Search\get_search_filter_details(), GVCommon\get_sortable_fields(), GVCommon\get_sortable_fields_array(), View\get_unions(), GravityView_Field_Payment_Date\get_value(), GravityView_Field_Payment_Amount\get_value(), GF_Field\get_value(), GravityView_Widget_Search\get_view_searchable_fields(), GravityView_Edit_Entry_Render\gform_pre_validation(), GV\Mocks\GravityView_API_field_label(), GV\Mocks\GravityView_API_field_value(), gravityview_field_output(), gravityview_hide_empty_fields_in_edit_entry(), gravityview_is_single_entry(), gv_class(), gv_label(), gv_value(), GravityView_Widget_Search\has_date_field(), GravityView_Field\is_choice_value_enabled(), GVCommon\is_field_numeric(), GravityView_frontend\is_field_sortable(), GravityView_Render_Settings\load_type_class(), GravityView_Field_Unsubscribe\maybe_not_visible(), GravityView_Field_Entry_Approval\maybe_not_visible(), GravityView_Duplicate_Entry\maybe_not_visible(), GravityView_Edit_Entry\maybe_not_visible(), GravityView_Delete_Entry\maybe_not_visible(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), GravityView_Merge_Tags\maybe_urlencode(), GravityView_Edit_Entry_Render\merge_field_properties(), GravityView_Merge_Tags\modifier_maxwords(), GravityView_Field_Workflow_Step\modify_gravityview_search_field_step_label(), GravityView_Plugin_Hooks_Gravity_Forms_Survey\modify_search_bar_input_type(), GravityView_Plugin_Hooks_Gravity_Forms_Chained_Selects\modify_searchable_fields(), GravityView_Plugin_Hooks_Gravity_Forms_Chained_Selects\modify_searchable_fields_allowlist(), Views_Route\prepare_entry_for_response(), GravityView_Widget_Search\prepare_field_filter(), GravityView_Edit_Entry_Render\preset_approval_fields(), GravityView_Merge_Tags\process_modifiers(), GravityView_Fields\register(), GravityView_Field_List\remove_columns_from_searchable_fields(), Field_Template\render(), GravityView_Admin_Views\render_active_areas(), GravityView_Widget_Search\render_frontend(), GravityView_Widget_Search\render_searchable_fields(), GravityView_View\renderZone(), GravityView_Edit_Entry_Render\save_field_value(), GravityView_Field\set_default_search_label(), GravityView_Field_Post_Category\set_post_categories(), GV\settings_edd_license(), License_Handler\settings_edd_license_activation(), GV\settings_html(), Addon_Settings\settings_save(), GV\settings_submit(), GravityView_Widget_Search\sieve_filter_choices(), GV\single_setting_label(), GV\single_setting_row(), GV\single_setting_row_html(), View\template_redirect(), View_Table_Template\the_columns(), Entry_Table_Template\the_entry(), View_Table_Template\the_entry(), GravityView_Edit_Entry_Render\unselect_default_values(), GravityView_Edit_Entry_Render\unset_hidden_field_values(), GravityView_Entry_Approval\update_approved_meta(), GravityView_Edit_Entry_Render\update_calculation_fields(), GravityView_Edit_Entry_Render\update_post_image(), GravityView_Edit_Entry_Render\user_can_edit_field(), and GravityView_Edit_Entry_Render\verify_user_can_edit_post().
$form
if (! class_exists('GF_Chained_Field_Select')) if (empty($search_field[ 'choices'])) $form = \GV\GF_Form::from_form($gravityview_view->getForm())
Definition at line 27 of file search-field-chainedselect.php.
$gf_field
$gf_field = $field->field
Definition at line 32 of file search-field-chainedselect.php.
Referenced by GravityView_Fields\get_associated_field(), GravityView_Plugin_Hooks_Gravity_Forms_Chained_Selects\get_field_values(), and Field_Template\render().
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Definition at line 12 of file search-field-chainedselect.php.
$hide_inactive
$hide_inactive = apply_filters('gravityview/search/chained_selects/hide_inactive', false, $search_field)
Choose whether to hide inactive dropdowns in the chain.
Since
TODO
Parameters
bool $hide_inactive Whether to hide drop-downs that aren't available yet.
GravityView_Widget_Search $this GravityView Widget instance
array{key:string,label:string,value:string,type:string,choices:array} $search_field
Definition at line 49 of file search-field-chainedselect.php.
$search_field
$search_field = $gravityview_view->search_field
Definition at line 14 of file search-field-chainedselect.php.
Referenced by GravityView_Widget_Search\gf_query_filter(), GravityView_Field_Workflow_Step\modify_frontend_search_fields(), GravityView_Field_Workflow_Final_Status\modify_search_filters(), GravityView_Plugin_Hooks_Gravity_Forms_Chained_Selects\print_scripts(), GravityView_Plugin_Hooks_Gravity_Forms_Chained_Selects\print_styles(), and GravityView_Field_Address\search_field_filter().
$view_id
$view_id = $gravityview_view->getViewId()
Definition at line 13 of file search-field-chainedselect.php.
chainedSelectsAlignment
$gf_field chainedSelectsAlignment = $gravityview_view->search_layout
Definition at line 52 of file search-field-chainedselect.php.
if
if(! gv_empty($search_field['label'], false, false))
Definition at line 55 of file search-field-chainedselect.php.