GravityView: search-field-submit.php File Reference
search-field-submit.php File Reference
Variables
$args = gv_get_query_args()
$gravityview_view = GravityView_View::getInstance()
$view_id = $gravityview_view->getViewId()
foreach ($args as $key=> $value) = array_merge($current_settings, $_directions)
Variable Documentation
$args
$args = gv_get_query_args()
Definition at line 15 of file search-field-submit.php.
Referenced by GravityView_Admin_Installer\add_downloads_data_filters(), GravityView_Widget_Search\add_no_permalink_fields(), GravityView_Duplicate_Entry\add_reserved_arg(), GravityView_Edit_Entry\add_reserved_arg(), GravityView_Delete_Entry\add_reserved_arg(), GravityView_Widget_Search\add_reserved_args(), gventry\callback(), gvfield\callback(), GravityView_API\directory_link(), GravityView_API\entry_link(), GravityView_HTML_Elements\field_dropdown(), GravityView_Widget_Search\filter_entries(), GravityView_Recent_Entries_Widget\form(), GravityView_HTML_Elements\form_dropdown(), GVCommon\format_date(), Field\get(), GVCommon\get_all_views(), GVCommon\get_connected_views(), GravityView_View_Data\get_default_arg(), Internal_Source\get_field(), GF_Form\get_field(), get_gravityview(), Entry\get_permalink(), GravityView_frontend\get_search_criteria(), GravityView_frontend\get_search_criteria_paging(), GravityView_Admin_ApproveEntries\get_sort_link(), GVCommon\get_users(), gravityview_after(), gravityview_before(), gravityview_field_output(), gravityview_footer(), GV\Mocks\GravityView_frontend_get_view_entries(), gravityview_get_connected_views(), gravityview_get_permalink_query_args(), gravityview_get_terms_choices(), gravityview_header(), EDD_SL_Plugin_Updater\http_request_args(), Admin_Request\is_admin(), GravityView_frontend\is_entry_approved(), GravityView_Field_Entry_Approval\maybe_prevent_field_render(), GravityView_Roles_Capabilities\members_register_cap_group(), GravityView_frontend\process_search_dates(), GravityView_frontend\process_search_only_approved(), View\register_post_type(), GravityView_Render_Settings\render_text_option(), GravityView_Render_Settings\render_textarea_option(), View\restrict(), GravityView_HTML_Elements\select(), View_Table_Template\the_columns(), View_Table_Template\the_field(), GravityView_Search_WP_Widget\widget(), and GravityView_Recent_Entries_Widget\widget().
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Since
2.0
Definition at line 6 of file search-field-submit.php.
$view_id
$view_id = $gravityview_view->getViewId()
Definition at line 7 of file search-field-submit.php.
foreach
foreach = array_merge($current_settings, $_directions)
Definition at line 17 of file search-field-submit.php.
Referenced by Legacy_Context\reset().