GravityView: select-template.php File Reference
select-template.php File Reference
Namespaces
GravityView
GPL2+
Variables
$current_template = gravityview_get_template_id($post->ID)
global $post
$templates = gravityview_get_registered_templates()
Variable Documentation
$current_template
$current_template = gravityview_get_template_id($post->ID)
Definition at line 15 of file select-template.php.
$post
global $post
Definition at line 9 of file select-template.php.
$templates
$templates = gravityview_get_registered_templates()
Definition at line 17 of file select-template.php.
Referenced by GravityView_Admin_Views\add_custom_column_content(), Legacy_Override_Template\add_id_specific_templates(), View_Template\add_id_specific_templates(), Field_Template\add_id_specific_templates(), Entry_Template\add_id_specific_templates(), GravityView_View\add_id_specific_templates(), gravityview_get_registered_templates(), and GravityView_Template\register_template().