GravityView: shortcodes.php File Reference
shortcodes.php File Reference
$shortcode_tags
WordPress API for creating bbcode like tags or what WordPress calls "shortcodes." The tag and attribute parsing or regular expression code is based on the Textpattern tag parser.
A few examples are below:
[shortcode /] [shortcode foo="bar" baz="bing" /] [shortcode foo="bar"]content[/shortcode]
Shortcode tags support attributes and enclosed content, but does not entirely support inline shortcodes in other shortcodes. You will have to call the shortcode parser in your function to account for that.
{ Container for storing shortcode tags and their hook to call for the shortcode
Since
2.5.0
$shortcode_tags = array()
add_shortcode ($tag, $func)
Add hook for shortcode tag.
remove_shortcode ($tag)
Removes hook for shortcode.
remove_all_shortcodes ()
Clear all shortcodes.
shortcode_exists ($tag)
Whether a registered shortcode exists named $tag.
has_shortcode ($content, $tag)
Whether the passed content contains the specified shortcode.
do_shortcode ($content, $ignore_html=false)
Search content for shortcodes and filter shortcodes through their hooks.
get_shortcode_regex ($tagnames=null)
Retrieve the shortcode regular expression for searching.
do_shortcode_tag ($m)
Regular Expression callable for do_shortcode() for calling shortcode hook.
do_shortcodes_in_html_tags ($content, $ignore_html, $tagnames)
Search only inside HTML elements for shortcodes and process them.
unescape_invalid_shortcodes ($content)
Remove placeholders added by do_shortcodes_in_html_tags().
get_shortcode_atts_regex ()
Retrieve the shortcode attributes regex.
shortcode_parse_atts ($text)
Retrieve all attributes from the shortcodes tag.
shortcode_atts ($pairs, $atts, $shortcode= '')
Combine user attributes with known attributes and fill in defaults when needed.
strip_shortcodes ($content)
Remove all shortcode tags from the given content.
strip_shortcode_tag ($m)
Strips a shortcode tag based on RegEx matches against post content.
Function Documentation
add_shortcode ($tag, $func)
Add hook for shortcode tag.
There can only be one hook for each shortcode. Which means that if another plugin has a similar shortcode, it will override yours or yours will override theirs depending on which order the plugins are included and/or ran.
Simplest example of a shortcode tag using the API:
// [footag foo="bar"]
function footag_func($atts) {
    return "foo = {
        $atts[foo]
    }";
}
add_shortcode('footag', 'footag_func');
Example with nice attribute defaults:
// [bartag foo="bar"]
function bartag_func($atts) {
    $args = shortcode_atts( array(
        'foo' => 'no foo',
        'baz' => 'default baz',
    ), $atts );
    return "foo = {$args['foo']}";
}
add_shortcode('bartag', 'bartag_func');
Example with enclosed content:
// [baztag]content[/baztag]
function baztag_func($atts, $content = '') {
    return "content = $content";
}
add_shortcode('baztag', 'baztag_func');
Since
2.5.0
array $shortcode_tags
Parameters
string $tag Shortcode tag to be searched in post content.
callable $func Hook to run when shortcode is found.
Definition at line 89 of file shortcodes.php.
References $message, $shortcode_tags, __, and _doing_it_wrong().
Referenced by WP_Embed\__construct(), GravityView_Compatibility\add_fallback_shortcode(), GravityView_Shortcode\add_hooks(), GravityView_Entry_Link_Shortcode\add_hooks(), GVLogic_Shortcode\add_hooks(), GFForms\init(), WP_Embed\run_shortcode(), GravityView_View_Test\test_BackLinkLabel(), and GVCommon_Test\test_has_shortcode_r().
do_shortcode ($content, $ignore_html = false)
Search content for shortcodes and filter shortcodes through their hooks.
If there are no shortcode tags defined, then the content will be returned without any filtering. This might cause issues when plugins are disabled but the shortcode will still show up in the post or content.
Since
2.5.0
array $shortcode_tags List of shortcode tags and their callback hooks.
Parameters
string $content Content to search for shortcodes.
bool $ignore_html When true, shortcodes inside HTML elements will be skipped.
Returns
string Content with shortcodes filtered out.
Definition at line 202 of file shortcodes.php.
References $content, $shortcode_tags, do_shortcodes_in_html_tags(), get_shortcode_regex(), and unescape_invalid_shortcodes().
Referenced by GFFormsModel\create_post(), GF_Field_HTML\get_field_input(), GVLogic_Shortcode\get_output(), GravityView_View\getBackLinkLabel(), GFForms\handle_ajax_do_shortcode(), img_caption_shortcode(), GravityView_Widget\maybe_do_shortcode(), WP_Embed\run_shortcode(), GravityView_frontend\single_entry_title(), GravityView_Shortcode_Test\test_shortcode(), GravityView_Shortcode_Test\test_shortcode_get_view_detail_PAGING(), GravityView_Shortcode_Test\test_shortcode_get_view_detail_TOTAL_ENTRIES(), wp_ajax_parse_embed(), and wp_ajax_parse_media_shortcode().
do_shortcode_tag ($m)
Regular Expression callable for do_shortcode() for calling shortcode hook.
See also
get_shortcode_regex for details of the match array contents.
Since
2.5.0 private
array $shortcode_tags
Parameters
array $m Regular expression match array
Returns
string|false False on failure.
Definition at line 306 of file shortcodes.php.
References $message, $shortcode_tags, __, _doing_it_wrong(), null, and shortcode_parse_atts().
Referenced by get_post_galleries().
do_shortcodes_in_html_tags ($content, $ignore_html, $tagnames)
Search only inside HTML elements for shortcodes and process them.
Any [ or ] characters remaining inside elements will be HTML encoded to prevent interference with shortcodes that are outside the elements. Assumes $content processed by KSES already. Users with unfiltered_html capability may get unexpected output if angle braces are nested in tags.
Since
4.2.3
Parameters
string $content Content to search for shortcodes
bool $ignore_html When true, all square braces inside elements will be encoded.
array $tagnames List of shortcodes to find.
Returns
string Content with shortcodes filtered out.
Definition at line 348 of file shortcodes.php.
References $attributes, $content, $count, get_shortcode_regex(), wp_html_split(), wp_kses_attr_parse(), and wp_kses_one_attr().
Referenced by do_shortcode(), and strip_shortcodes().
get_shortcode_atts_regex ()
Retrieve the shortcode attributes regex.
Since
4.4.0
Returns
string The shortcode attribute regular expression
Definition at line 462 of file shortcodes.php.
Referenced by shortcode_parse_atts().
get_shortcode_regex ($tagnames = null)
Retrieve the shortcode regular expression for searching.
The regular expression combines the shortcode tags in the regular expression in a regex class.
The regular expression contains 6 different sub matches to help with parsing.
1 - An extra [ to allow for escaping shortcodes with double [[]] 2 - The shortcode name 3 - The shortcode argument list 4 - The self closing / 5 - The content of a shortcode when it wraps some content. 6 - An extra ] to allow for escaping shortcodes with double [[]]
Since
2.5.0
array $shortcode_tags
Parameters
array $tagnames List of shortcodes to find. Optional. Defaults to all registered shortcodes.
Returns
string The shortcode search regular expression
Definition at line 253 of file shortcodes.php.
References $shortcode_tags.
Referenced by do_shortcode(), do_shortcodes_in_html_tags(), get_post_galleries(), has_shortcode(), GVCommon\has_shortcode_r(), strip_shortcodes(), twentyeleven_get_gallery_images(), twentyten_get_gallery_images(), and wp_ajax_parse_embed().
has_shortcode ($content, $tag)
Whether the passed content contains the specified shortcode.
Since
3.6.0
array $shortcode_tags
Parameters
string $content Content to search for shortcodes.
string $tag Shortcode tag to check.
Returns
bool Whether the passed content contains the given shortcode.
Definition at line 166 of file shortcodes.php.
References $content, elseif, get_shortcode_regex(), and shortcode_exists().
Referenced by get_post_galleries(), GravityView_Widget\maybe_do_shortcode(), and wp_ajax_parse_embed().
remove_all_shortcodes ()
Clear all shortcodes.
This function is simple, it clears all of the shortcode tags by replacing the shortcodes global by a empty array. This is actually a very efficient method for removing all shortcodes.
Since
2.5.0
array $shortcode_tags
Definition at line 134 of file shortcodes.php.
References $shortcode_tags.
Referenced by WP_Embed\run_shortcode().
remove_shortcode ($tag)
Removes hook for shortcode.
Since
2.5.0
array $shortcode_tags
Parameters
string $tag Shortcode tag to remove hook for.
Definition at line 117 of file shortcodes.php.
References $shortcode_tags.
shortcode_atts ($pairs, $atts, $shortcode = '')
Combine user attributes with known attributes and fill in defaults when needed.
The pairs should be considered to be all of the attributes which are supported by the caller and given as a list. The returned attributes will only contain the attributes in the $pairs list.
If the $atts list has unsupported attributes, then they will be ignored and removed from the final returned list.
Since
2.5.0
Parameters
array $pairs Entire list of supported attributes and their defaults.
array $atts User defined attributes in shortcode tag.
string $shortcode Optional. The name of the shortcode, provided for context to enable filtering
Returns
array Combined and filtered attribute list.
Filter a shortcode's default attributes.
If the third parameter of the shortcode_atts() function is present then this filter is available. The third parameter, $shortcode, is the name of the shortcode.
Since
3.6.0
4.4.0 Added the $shortcode parameter.
Parameters
array $out The output array of shortcode attributes.
array $pairs The supported attributes and their defaults.
array $atts The user defined shortcode attributes.
string $shortcode The shortcode name.
Definition at line 530 of file shortcodes.php.
References $default, $name, $out, and apply_filters().
Referenced by GravityView_View_Data\add_view(), gallery_shortcode(), GVCommon\get_link_html(), img_caption_shortcode(), GravityView_Shortcode\parse_and_sanitize_atts(), GVLogic_Shortcode\parse_atts(), GFForms\parse_shortcode(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Entry_Link_Shortcode\shortcode(), wp_audio_shortcode(), wp_playlist_shortcode(), and wp_video_shortcode().
shortcode_exists ($tag)
Whether a registered shortcode exists named $tag.
Since
3.6.0
array $shortcode_tags List of shortcode tags and their callback hooks.
Parameters
string $tag Shortcode tag to check.
Returns
bool Whether the given shortcode exists.
Definition at line 150 of file shortcodes.php.
References $shortcode_tags.
Referenced by GravityView_Field_FileUpload\get_files_array(), has_shortcode(), GVCommon\has_shortcode_r(), GravityView_View_Data\parse_post_content(), and GravityView_Entry_Link_Shortcode_Test\test_add_hooks().
shortcode_parse_atts ($text)
Retrieve all attributes from the shortcodes tag.
The attributes list has the attribute name as the key and the value of the attribute as the value in the key/value pair. This allows for easier retrieval of the attributes, since all attributes have to be known.
Since
2.5.0
Parameters
string $text
Returns
array|string List of attribute values. Returns empty array if trim($text) == '""'. Returns empty string if trim($text) == ''. All other matches are checked for not empty().
Definition at line 481 of file shortcodes.php.
References $text, $value, elseif, and get_shortcode_atts_regex().
Referenced by WP_oEmbed\discover(), do_shortcode_tag(), GFFormDisplay\get_embedded_forms(), GravityView_View_Data\get_id_from_atts(), get_post_galleries(), GravityView_View_Data\parse_post_content(), GFFormDisplay\replace_save_variables(), twentyeleven_get_gallery_images(), twentyten_get_gallery_images(), wp_ajax_parse_embed(), and wp_rel_nofollow_callback().
strip_shortcode_tag ($m)
Strips a shortcode tag based on RegEx matches against post content.
Since
3.3.0
Parameters
array $m RegEx matches against post content.
Returns
string|false The content stripped of the tag, otherwise false.
Definition at line 607 of file shortcodes.php.
strip_shortcodes ($content)
Remove all shortcode tags from the given content.
Since
2.5.0
array $shortcode_tags
Parameters
string $content Content to remove shortcode tags.
Returns
string Content without shortcode tags.
Definition at line 570 of file shortcodes.php.
References $content, $shortcode_tags, do_shortcodes_in_html_tags(), get_shortcode_regex(), and unescape_invalid_shortcodes().
Referenced by wp_trim_excerpt().
unescape_invalid_shortcodes ($content)
Remove placeholders added by do_shortcodes_in_html_tags().
Since
4.2.3
Parameters
string $content Content to search for placeholders.
Returns
string Content with placeholders removed.
Definition at line 447 of file shortcodes.php.
References $content.
Referenced by do_shortcode(), and strip_shortcodes().
Variable Documentation
$shortcode_tags = array()
Definition at line 42 of file shortcodes.php.
Referenced by add_shortcode(), do_shortcode(), do_shortcode_tag(), get_shortcode_regex(), remove_all_shortcodes(), remove_shortcode(), WP_Embed\run_shortcode(), shortcode_exists(), shortcode_unautop(), strip_shortcodes(), and wptexturize().