GravityView: site-info.php File Reference
site-info.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
if(!$id) $details = get_blog_details($id)
$id = isset($_REQUEST['id']) ? intval($_REQUEST['id']) : 0
$is_main_site = is_main_site($id)
$parent_file = 'sites.php'
if(!$details) if(!can_edit_network($details->site_id)) $parsed_scheme = parse_url($details->siteurl, PHP_URL_SCHEME)
$submenu_file = 'sites.php'
$tabs
if(isset($_REQUEST['action'])&& 'update-site'==$_REQUEST['action']) if(isset($_GET['update'])) $title = sprintf(__('Edit Site: %s'), esc_html($details->blogname))
The site URL is rarely edited as this can cause the site to not work properly The Registered date and Last Updated date are displayed Network admins can mark a site as archived
endforeach
endif
The site URL is rarely edited as this can cause the site to not work properly The Registered date and Last Updated date are displayed Network admins can mark a site as deleted and mature
The site URL is rarely edited as this can cause the site to not work properly The Registered date and Last Updated date are displayed Network admins can mark a site as deleted and to remove from listings or disable</p >< p >< strong > Users</strong > & mdash
This displays the users associated with this site You can also change their reset their password
This displays the users associated with this site You can also change their role
The site URL is rarely edited as this can cause the site to not work properly The Registered date and Last Updated date are displayed Network admins can mark a site as spam
This area shows themes that are not already enabled across the network Enabling a theme in this menu makes it accessible to this site It does not activate the theme
Variable Documentation
if (!$id) $details = get_blog_details($id)
Definition at line 44 of file site-info.php.
Referenced by add_existing_user_to_blog(), add_user_to_blog(), WP_Upgrader\clear_destination(), confirm_delete_users(), get_active_blog_for_user(), get_blog_details(), get_blog_list(), get_blog_status(), get_most_active_blogs(), get_settings_errors(), maybe_add_existing_user_to_blog(), refresh_blog_details(), GravityView_Admin_Views\render_available_fields(), GravityView_Admin_Views\render_available_widgets(), Custom_Image_Header\reset_header_image(), settings_errors(), update_blog_details(), and wp_dropdown_roles().
$id = isset($_REQUEST['id']) ? intval($_REQUEST['id']) : 0
Definition at line 38 of file site-info.php.
$is_main_site = is_main_site($id)
Definition at line 54 of file site-info.php.
$parent_file = 'sites.php'
Definition at line 131 of file site-info.php.
if (!$details) if (!can_edit_network($details->site_id)) $parsed_scheme = parse_url($details->siteurl, PHP_URL_SCHEME)
Definition at line 53 of file site-info.php.
$submenu_file = 'sites.php'
Definition at line 132 of file site-info.php.
$tabs
Initial value:
= array(
    'site-info'     => array( 'label' => __( 'Info' ),     'url' => 'site-info.php'     ),
    'site-users'    => array( 'label' => __( 'Users' ),    'url' => 'site-users.php'    ),
    'site-themes'   => array( 'label' => __( 'Themes' ),   'url' => 'site-themes.php'   ),
    'site-settings' => array( 'label' => __( 'Settings' ), 'url' => 'site-settings.php' ),
)
Definition at line 143 of file site-info.php.
Referenced by GFAddOn\_tab_matches(), Custom_Image_Header\filter_upload_tabs(), GFForms\get_form_settings_sub_menu_items(), WP_Theme_Install_List_Table\get_views(), WP_Plugin_Install_List_Table\get_views(), WP_Theme_Install_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), the_media_upload_tabs(), update_gallery_tab(), and wp_enqueue_media().
if (isset($_REQUEST['action'])&& 'update-site'==$_REQUEST['action']) if (isset($_GET['update'])) $title = sprintf(__('Edit Site: %s'), esc_html($details->blogname))
Definition at line 129 of file site-info.php.
The site URL is rarely edited as this can cause the site to not work properly The Registered date and Last Updated date are displayed Network admins can mark a site as archived
Definition at line 26 of file site-info.php.
endforeach
Definition at line 206 of file site-info.php.
endif
Definition at line 178 of file site-info.php.
The site URL is rarely edited as this can cause the site to not work properly The Registered date and Last Updated date are displayed Network admins can mark a site as deleted and mature
Definition at line 26 of file site-info.php.
This displays the users associated with this site You can also change their reset their or remove them from the site Removing the user from the site does not remove the user from the network</p >< p >< strong > Themes</strong > & mdash
Definition at line 26 of file site-info.php.
Referenced by wp_underscore_playlist_templates().
This displays the users associated with this site You can also change their reset their password
Definition at line 27 of file site-info.php.
Referenced by CreatePlaceholdersUI(), and twentyfifteen_get_color_scheme_css().
This displays the users associated with this site You can also change their role
Definition at line 27 of file site-info.php.
Referenced by SimplePie_Credit\__construct(), WP_Admin_Bar\_render(), WP_Customize_Nav_Menus\available_items_template(), SimplePie_Credit\get_role(), GravityView_Welcome\getting_started_screen(), WP_Press_This\html(), WP_Customize_Themes_Section\render(), and wp_print_request_filesystem_credentials_modal().
The site URL is rarely edited as this can cause the site to not work properly The Registered date and Last Updated date are displayed Network admins can mark a site as spam
Definition at line 26 of file site-info.php.
Referenced by _wp_dashboard_recent_comments_row(), export_wp(), and GFEntryList\leads_page().
This area shows themes that are not already enabled across the network Enabling a theme in this menu makes it accessible to this site It does not activate the theme
Definition at line 28 of file site-info.php.