GravityView: sites.php File Reference
sites.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$id = isset($_REQUEST['id']) ? intval($_REQUEST['id']) : 0
if(isset($_GET['action'])) $msg = ''
$pagenum = $wp_list_table->get_pagenum()
$parent_file = 'sites.php'
$title = __('Sites')
$wp_list_table = _get_list_table('WP_MS_Sites_List_Table')
endif
if (!current_user_can('manage_sites')) wp_die(__('You do not have permission to access this page.')
if (isset($_REQUEST['s'])&&$_REQUEST['s'])
Variable Documentation
$id = isset($_REQUEST['id']) ? intval($_REQUEST['id']) : 0
Definition at line 54 of file sites.php.
if (isset($_GET['action'])) $msg = ''
Definition at line 224 of file sites.php.
Referenced by AtomParser\_p(), logIO(), maintenance_nag(), ms_not_installed(), newblog_notify_siteadmin(), newuser_notify_siteadmin(), populate_network(), wpdb\print_error(), ftp_base\PushError(), PHPMailer\setError(), POP3\uidl(), update_nag(), update_right_now_message(), wp_ajax_image_editor(), wp_dashboard_browser_nag(), wp_image_editor(), and wp_restore_image().
$pagenum = $wp_list_table->get_pagenum()
Definition at line 20 of file sites.php.
$parent_file = 'sites.php'
Definition at line 23 of file sites.php.
$title = __('Sites')
Definition at line 22 of file sites.php.
$wp_list_table = _get_list_table('WP_MS_Sites_List_Table')
Definition at line 19 of file sites.php.
endif
Definition at line 288 of file sites.php.
if(!current_user_can('manage_sites')) wp_die(__('You do not have permission to access this page.')
Definition at line 16 of file sites.php.
if(isset($_REQUEST['s'])&&$_REQUEST['s'])
Definition at line 291 of file sites.php.