GravityView: site-new.php File Reference
site-new.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$lang = get_site_option('WPLANG')
$parent_file = 'sites.php'
if(isset($_REQUEST['action'])&& 'add-site'==$_REQUEST['action']) if(isset($_GET['update'])) $title = __('Add New Site')
$translations = wp_get_available_translations()
< tr class="form-field form-required">< th scope="row">< label for="admin-email"> _e('Admin Email')?></label ></th >< td >< input name _e ('The username and password will be mailed to this email address.')?></td ></tr ></table ><?php submit_button(__('Add Site')
wp_nonce_field('add-blog', '_wpnonce_add-blog')?>< table class if(is_subdomain_install()) else
endif
if (!empty($messages))
Variable Documentation
$lang = get_site_option('WPLANG')
Definition at line 205 of file site-new.php.
Referenced by SimplePie_Item\get_enclosures(), get_language_attributes(), and recaptcha_get_html().
$parent_file = 'sites.php'
Definition at line 161 of file site-new.php.
if (isset($_REQUEST['action'])&& 'add-site'==$_REQUEST['action']) if (isset($_GET['update'])) $title = __('Add New Site')
Definition at line 160 of file site-new.php.
$translations = wp_get_available_translations()
Definition at line 197 of file site-new.php.
Referenced by _n(), _nx(), delete_plugins(), delete_theme(), translate(), translate_with_gettext_context(), wp_download_language_pack(), wp_dropdown_languages(), wp_get_available_translations(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
<tr class="form-field form-required"><th scope="row"><label for="admin-email"> _e ('Admin Email') ?></label></th> <td><input name _e('The username and password will be mailed to this email address.')?></td ></tr ></table ><?php submit_button(__('Add Site')
Initial value:
="blog[email]" type="email" class="regular-text wp-suggest-user" id="admin-email" data-autocomplete-type="search" data-autocomplete-field="user_email" /></td>
        </tr>
        <tr class="form-field">
            <td colspan="2"><?php _e( 'A new user will be created if the above email address is not in the database.' )
Definition at line 229 of file site-new.php.
wp_nonce_field ('add-blog', '_wpnonce_add-blog') ?> <table class if (is_subdomain_install()) else
Initial value:
{
                echo $current_site->domain . $current_site->path
Definition at line 184 of file site-new.php.
endif
Definition at line 223 of file site-new.php.
if(!empty($messages))
Definition at line 172 of file site-new.php.