GravityView: template-loader.php File Reference
template-loader.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
elseif(is_embed()) $template = apply_filters('embed_template', $template)
Filter the template used for embedded posts.
endif
return
Variable Documentation
elseif (is_embed()) $template = apply_filters('embed_template', $template)
Filter the template used for embedded posts.
Since
4.4.0
Parameters
string $template Path to the template file.
Definition at line 52 of file template-loader.php.
Referenced by _navigation_markup(), GravityView_Admin_Views\add_custom_column_content(), GravityView_Template\assign_active_areas(), GravityView_Template\assign_fields_xml(), GravityView_Template\assign_form_xml(), WP_Themes_List_Table\display_rows(), GV_License_Handler\generate_license_box(), get_page_template(), get_page_template_slug(), get_query_template(), get_template_directory(), get_template_directory_uri(), GFForms\get_view(), is_page_template(), make_site_theme(), page_attributes_meta_box(), page_template_dropdown(), populate_network(), populate_options(), switch_theme(), and upgrade_all().
endif
Definition at line 56 of file template-loader.php.
return
Definition at line 35 of file template-loader.php.