GravityView: theme-editor.php File Reference
theme-editor.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
if(!$theme->exists()) if($theme->errors()&& 'theme_no_stylesheet'==$theme->errors() ->get_error_code()) $allowed_files = $style_files = array()
$default_types = array('php', 'css')
$file = $theme->get_stylesheet_directory() . '/' . $relative_file
$file_types = apply_filters('wp_theme_editor_filetypes', $default_types, $theme)
Filter the list of file types allowed for editing in the Theme editor.
$has_templates = false
$parent_file = 'themes.php'
$scrollto = isset($_REQUEST['scrollto']) ? (int) $_REQUEST['scrollto'] : 0
$theme = wp_get_theme($stylesheet)
$title = __("Edit Themes")
if($theme) else
get_current_screen() -> add_help_tab(array('id'=> 'overview', 'title'=> __('Overview'), 'content'=>'< p >'.__('You can use the Theme Editor to edit the individual CSS and PHP files which make up your theme.'). '</p >< p >'.__("Begin by choosing a theme to edit from the dropdown menu and clicking Select. A list then appears of the theme's template files. Clicking once on any file name causes the file to appear in the large Editor box."). '</p >< p >'.__('For PHP files, you can use the Documentation dropdown to select from functions recognized in that file.Look Up takes you to a web page with reference material about that particular function.'). '</p >< p id="newcontent-description">'.__('In the editing area the Tab key enters a tab character.To move below this area by pressing Tab, press the Esc key followed by the Tab key.In some cases the Esc key will need to be pressed twice before the Tab key will allow you to continue.'). '</p >< p >'.__('After typing in your edits, click Update File.'). '</p >< p >'.__('< strong >Advice:</strong > think very carefully about your site crashing if you are live-editing the theme currently in use.'). '</p >< p >'.sprintf(__('Upgrading to a newer version of the same theme will override changes made here.To avoid this consider creating a< a href="%s"target="_blank"> child theme</a > instead https
switch ($action)
Variable Documentation
if (!$theme->exists()) if ($theme->errors()&& 'theme_no_stylesheet'==$theme->errors() ->get_error_code()) $allowed_files = $style_files = array()
Definition at line 64 of file theme-editor.php.
Referenced by get_file_description(), validate_file(), and validate_file_to_edit().
$default_types = array('php', 'css')
Definition at line 66 of file theme-editor.php.
Referenced by wp_audio_shortcode(), and wp_video_shortcode().
$file = $theme->get_stylesheet_directory() . '/' . $relative_file
Definition at line 103 of file theme-editor.php.
$file_types = apply_filters('wp_theme_editor_filetypes', $default_types, $theme)
Filter the list of file types allowed for editing in the Theme editor.
Since
4.4.0
Parameters
array $default_types List of file types. Default types include 'php' and 'css'.
WP_Theme $theme The current Theme object.
Definition at line 76 of file theme-editor.php.
$has_templates = false
Definition at line 65 of file theme-editor.php.
$parent_file = 'themes.php'
Definition at line 21 of file theme-editor.php.
$scrollto = isset($_REQUEST['scrollto']) ? (int) $_REQUEST['scrollto'] : 0
Definition at line 107 of file theme-editor.php.
$theme = wp_get_theme($stylesheet)
Definition at line 54 of file theme-editor.php.
Referenced by WP_Theme_Install_List_Table\_get_theme_status(), WP_MS_Themes_List_Table\_search_callback(), Theme_Upgrader\bulk_upgrade(), WP_MS_Themes_List_Table\column_cb(), WP_MS_Themes_List_Table\column_default(), WP_MS_Themes_List_Table\column_description(), WP_MS_Themes_List_Table\column_name(), Theme_Upgrader\current_after(), Theme_Upgrader\current_before(), Theme_Upgrader\delete_old_theme(), WP_Themes_List_Table\display_rows(), WP_Theme_Install_List_Table\display_rows(), WP_MS_Themes_List_Table\display_rows(), display_theme(), get_allowed_themes(), get_broken_themes(), WP_Theme\get_core_default_theme(), get_current_theme(), GF_Field_CAPTCHA\get_field_input(), Language_Pack_Upgrader\get_name_for_update(), get_theme(), get_theme_data(), get_theme_update_available(), get_themes(), WP_Theme_Install_List_Table\install_theme_info(), install_theme_information(), list_theme_updates(), GFForms\maybe_import_theme_forms(), populate_options(), WP_Themes_List_Table\prepare_items(), WP_MS_Themes_List_Table\prepare_items(), remove_theme_mod(), WP_Automatic_Updater\run(), WP_Themes_List_Table\search_theme(), set_theme_mod(), WP_Theme_Install_List_Table\single_row(), WP_MS_Themes_List_Table\single_row(), Theme_Upgrader\theme_info(), WP_Theme_Install_List_Table\theme_installer_single(), theme_update_available(), WP_Automatic_Updater\update(), Theme_Upgrader\upgrade(), wp_ajax_query_themes(), wp_clean_themes_cache(), wp_get_themes(), wp_prepare_themes_for_js(), wp_theme_update_row(), wp_theme_update_rows(), WP_Filesystem_Base\wp_themes_dir(), wp_update_theme(), and wp_update_themes().
$title = __("Edit Themes")
Definition at line 20 of file theme-editor.php.
foreach ($file_types as $type) if (empty($file)) else
Initial value:
{
    $stylesheet = get_stylesheet()
Definition at line 50 of file theme-editor.php.
get_current_screen () -> add_help_tab(array('id'=> 'overview', 'title'=> __('Overview'), 'content'=>'< p >'.__('You can use the Theme Editor to edit the individual CSS and PHP files which make up your theme.'). '</p >< p >'.__("Begin by choosing a theme to edit from the dropdown menu and clicking Select. A list then appears of the theme's template files. Clicking once on any file name causes the file to appear in the large Editor box."). '</p >< p >'.__('For PHP files, you can use the Documentation dropdown to select from functions recognized in that file.Look Up takes you to a web page with reference material about that particular function.'). '</p >< p id="newcontent-description">'.__('In the editing area the Tab key enters a tab character.To move below this area by pressing Tab, press the Esc key followed by the Tab key.In some cases the Esc key will need to be pressed twice before the Tab key will allow you to continue.'). '</p >< p >'.__('After typing in your edits, click Update File.'). '</p >< p >'.__('< strong >Advice:</strong > think very carefully about your site crashing if you are live-editing the theme currently in use.'). '</p >< p >'.sprintf(__('Upgrading to a newer version of the same theme will override changes made here.To avoid this consider creating a<a href="%s" target="_blank"> child theme</a> instead https override
Definition at line 23 of file theme-editor.php.
switch($action)
Definition at line 109 of file theme-editor.php.