GravityView: theme-options.php File Reference
theme-options.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyeleven_admin_enqueue_scripts ($hook_suffix)
Properly enqueue styles and scripts for our theme options page.
twentyeleven_color_schemes ()
Return an array of color schemes registered for Twenty Eleven.
twentyeleven_customize_preview_js ()
Bind JS handlers to make Customizer preview reload changes asynchronously.
twentyeleven_customize_register ($wp_customize)
Implements Twenty Eleven theme options into Customizer.
twentyeleven_enqueue_color_scheme ()
Enqueue the styles for the current color scheme.
twentyeleven_get_default_link_color ($color_scheme=null)
Return the default link color for Twenty Eleven, based on color scheme.
twentyeleven_get_default_theme_options ()
Return the default options for Twenty Eleven.
twentyeleven_get_theme_options ()
Return the options array for Twenty Eleven.
twentyeleven_layout_classes ($existing_classes)
Add Twenty Eleven layout classes to the array of body classes.
twentyeleven_layouts ()
Return an array of layout options registered for Twenty Eleven.
twentyeleven_option_page_capability ($capability)
Change the capability required to save the 'twentyeleven_options' options group.
twentyeleven_print_link_color_style ()
Add a style block to the theme for the current link color.
twentyeleven_settings_field_color_scheme ()
Render the Color Scheme setting field.
twentyeleven_settings_field_layout ()
Render the Layout setting field.
twentyeleven_settings_field_link_color ()
Render the Link Color setting field.
twentyeleven_theme_options_add_page ()
Add a theme options page to the admin menu, including some help documentation.
twentyeleven_theme_options_help ()
twentyeleven_theme_options_init ()
Register the form setting for our twentyeleven_options array.
twentyeleven_theme_options_render_page ()
Render the theme options page for Twenty Eleven.
twentyeleven_theme_options_validate ($input)
Sanitize and validate form input.
Variables
section recent posts other recent posts comments link a
Function Documentation
twentyeleven_admin_enqueue_scripts ($hook_suffix)
Properly enqueue styles and scripts for our theme options page.
This function is attached to the admin_enqueue_scripts action hook.
Since
Twenty Eleven 1.0
Parameters
string $hook_suffix An admin page's hook suffix.
Definition at line 19 of file theme-options.php.
References get_template_directory_uri(), wp_enqueue_script(), and wp_enqueue_style().
twentyeleven_color_schemes ()
Return an array of color schemes registered for Twenty Eleven.
Since
Twenty Eleven 1.0
Filter the Twenty Eleven color scheme options.
Since
Twenty Eleven 1.0
Parameters
array $color_scheme_options An associative array of color scheme options.
Definition at line 146 of file theme-options.php.
References __, apply_filters(), and get_template_directory_uri().
Referenced by twentyeleven_customize_register(), twentyeleven_get_default_link_color(), twentyeleven_settings_field_color_scheme(), and twentyeleven_theme_options_validate().
twentyeleven_customize_preview_js ()
Bind JS handlers to make Customizer preview reload changes asynchronously.
Used with blogname and blogdescription.
Since
Twenty Eleven 1.3
Definition at line 584 of file theme-options.php.
References get_template_directory_uri(), and wp_enqueue_script().
twentyeleven_customize_register ($wp_customize)
Implements Twenty Eleven theme options into Customizer.
Since
Twenty Eleven 1.3
Parameters
object $wp_customize Customizer object.
Definition at line 508 of file theme-options.php.
References $options, $wp_customize, __, twentyeleven_color_schemes(), twentyeleven_get_default_link_color(), twentyeleven_get_default_theme_options(), twentyeleven_get_theme_options(), and twentyeleven_layouts().
twentyeleven_enqueue_color_scheme ()
Enqueue the styles for the current color scheme.
Since
Twenty Eleven 1.0
Fires after the styles for the Twenty Eleven color scheme are enqueued.
Since
Twenty Eleven 1.0
Parameters
string $color_scheme The color scheme.
Definition at line 398 of file theme-options.php.
References $options, do_action(), get_template_directory_uri(), null, twentyeleven_get_theme_options(), and wp_enqueue_style().
twentyeleven_get_default_link_color ($color_scheme = null)
Return the default link color for Twenty Eleven, based on color scheme.
Since
Twenty Eleven 1.0
Parameters
string $color_scheme Optional. Color scheme. Default null (or the active color scheme).
Returns
string The default link color.
Definition at line 242 of file theme-options.php.
References $options, null, twentyeleven_color_schemes(), and twentyeleven_get_theme_options().
Referenced by twentyeleven_customize_register(), twentyeleven_get_default_theme_options(), twentyeleven_settings_field_link_color(), and twentyeleven_theme_options_validate().
twentyeleven_get_default_theme_options ()
Return the default options for Twenty Eleven.
Since
Twenty Eleven 1.0
Returns
array An array of default theme options.
Filter the Twenty Eleven default options.
Since
Twenty Eleven 1.0
Parameters
array $default_theme_options An array of default theme options.
Definition at line 213 of file theme-options.php.
References apply_filters(), is_rtl(), and twentyeleven_get_default_link_color().
Referenced by twentyeleven_customize_register(), twentyeleven_get_theme_options(), twentyeleven_print_link_color_style(), and twentyeleven_theme_options_validate().
twentyeleven_get_theme_options ()
Return the options array for Twenty Eleven.
Since
Twenty Eleven 1.0
Definition at line 260 of file theme-options.php.
References get_option(), and twentyeleven_get_default_theme_options().
Referenced by twentyeleven_customize_register(), twentyeleven_enqueue_color_scheme(), twentyeleven_get_default_link_color(), twentyeleven_layout_classes(), twentyeleven_print_link_color_style(), twentyeleven_settings_field_color_scheme(), twentyeleven_settings_field_layout(), and twentyeleven_settings_field_link_color().
twentyeleven_layout_classes ($existing_classes)
Add Twenty Eleven layout classes to the array of body classes.
Since
Twenty Eleven 1.0
Parameters
array $existing_classes An array of existing body classes.
Filter the Twenty Eleven layout body classes.
Since
Twenty Eleven 1.0
Parameters
array $classes An array of body classes.
string $current_layout The current theme layout.
Definition at line 471 of file theme-options.php.
References $current_layout, $options, apply_filters(), elseif, and twentyeleven_get_theme_options().
twentyeleven_layouts ()
Return an array of layout options registered for Twenty Eleven.
Since
Twenty Eleven 1.0
Filter the Twenty Eleven layout options.
Since
Twenty Eleven 1.0
Parameters
array $layout_options An associative array of layout options.
Definition at line 177 of file theme-options.php.
References __, apply_filters(), and get_template_directory_uri().
Referenced by twentyeleven_customize_register(), twentyeleven_settings_field_layout(), and twentyeleven_theme_options_validate().
twentyeleven_option_page_capability ($capability)
Change the capability required to save the 'twentyeleven_options' options group.
See also
twentyeleven_theme_options_init() First parameter to register_setting() is the name of the options group.
twentyeleven_theme_options_add_page() The edit_theme_options capability is used for viewing the page.
By default, the options groups for all registered settings require the manage_options capability. This filter is required to change our theme options page to edit_theme_options instead. By default, only administrators have either of these capabilities, but the desire here is to allow for finer-grained control for roles and users.
Parameters
string $capability The capability used for the page, which is manage_options by default.
Returns
string The capability to actually use.
Definition at line 81 of file theme-options.php.
twentyeleven_print_link_color_style ()
Add a style block to the theme for the current link color.
This function is attached to the wp_head action hook.
Since
Twenty Eleven 1.0
Definition at line 423 of file theme-options.php.
References $options, a, color, image, posts, twentyeleven_get_default_theme_options(), and twentyeleven_get_theme_options().
twentyeleven_settings_field_color_scheme ()
Render the Color Scheme setting field.
Since
Twenty Eleven 1.3
Definition at line 269 of file theme-options.php.
References $options, checked(), esc_html, height, input, label, name, twentyeleven_color_schemes(), twentyeleven_get_theme_options(), and width.
twentyeleven_settings_field_layout ()
Render the Layout setting field.
Since
Twenty Eleven 1.3
Definition at line 310 of file theme-options.php.
References $options, checked(), esc_html, height, input, label, name, twentyeleven_get_theme_options(), twentyeleven_layouts(), and width.
twentyeleven_settings_field_link_color ()
Render the Link Color setting field.
Since
Twenty Eleven 1.3
Definition at line 293 of file theme-options.php.
References $options, __, input, name, twentyeleven_get_default_link_color(), and twentyeleven_get_theme_options().
twentyeleven_theme_options_add_page ()
Add a theme options page to the admin menu, including some help documentation.
This function is attached to the admin_menu action hook.
Since
Twenty Eleven 1.0
Definition at line 93 of file theme-options.php.
References __, add_action(), and add_theme_page().
twentyeleven_theme_options_help ()
Definition at line 109 of file theme-options.php.
References $help, $screen, __, add_contextual_help(), and get_current_screen().
twentyeleven_theme_options_init ()
Register the form setting for our twentyeleven_options array.
This function is attached to the admin_init action hook.
This call to register_setting() registers a validation callback, twentyeleven_theme_options_validate(), which is used when the option is saved, to ensure that our option values are complete, properly formatted, and safe.
Since
Twenty Eleven 1.0
Definition at line 37 of file theme-options.php.
References __, add_settings_field(), add_settings_section(), and register_setting().
twentyeleven_theme_options_render_page ()
Render the theme options page for Twenty Eleven.
Since
Twenty Eleven 1.2
Definition at line 332 of file theme-options.php.
References __, do_settings_sections(), get_current_theme(), screen_icon(), settings_errors(), settings_fields(), submit_button(), and wp_get_theme().
twentyeleven_theme_options_validate ($input)
Sanitize and validate form input.
Accepts an array, return a sanitized array.
See also
twentyeleven_theme_options_init()
Since
Twenty Eleven 1.0
Parameters
array $input An array of form input.
Filter the Twenty Eleven sanitized form input array.
Since
Twenty Eleven 1.0
Parameters
array $output An array of sanitized form output.
array $input An array of un-sanitized form input.
array $defaults An array of default theme options.
Definition at line 363 of file theme-options.php.
References $output, apply_filters(), twentyeleven_color_schemes(), twentyeleven_get_default_link_color(), twentyeleven_get_default_theme_options(), and twentyeleven_layouts().
Variable Documentation
a a
Definition at line 450 of file theme-options.php.
Referenced by get_post_embed_html(), GFEntryList\leads_page(), print_embed_styles(), print_emoji_detection_script(), twentyeleven_print_link_color_style(), twentyfifteen_get_color_scheme_css(), and twentytwelve_header_style().