GravityView: theme-install.php File Reference
theme-install.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$feature_list = get_theme_feature_list()
$help_installing
if($tab) $help_overview
if(!is_network_admin()) $installed_themes = search_theme_directories()
$parent_file = 'themes.php'
$tabs = apply_filters('install_themes_tabs', array('upload' => __('Upload Theme')))
Filter the tabs shown on the Add Themes screen.
if(is_multisite()&&!is_network_admin()) $title = __('Add Themes')
$user = isset($_GET['user']) ? wp_unslash($_GET['user']) : get_user_option('wporg_favorites')
Variable Documentation
$feature_list = get_theme_feature_list()
Definition at line 169 of file theme-install.php.
Referenced by get_theme_feature_list(), install_themes_dashboard(), install_themes_feature_list(), and WP_Theme\translate_header().
$help_installing
Initial value:
=
    '<p>' . __('Once you have generated a list of themes, you can preview and install any of them. Click on the thumbnail of the theme you&#8217;re interested in previewing. It will open up in a full-screen Preview page to give you a better idea of how that theme will look.') . '</p>' .
    '<p>' . __('To install the theme so you can preview it with your site&#8217;s content and customize its theme options, click the "Install" button at the top of the left-hand pane. The theme files will be downloaded to your website automatically. When this is complete, the theme is now available for activation, which you can do by clicking the "Activate" link, or by navigating to your Manage Themes screen and clicking the "Live Preview" link under any installed theme&#8217;s thumbnail image.') . '</p>'
Definition at line 87 of file theme-install.php.
if ($tab) $help_overview
Initial value:
=
    '<p>' . sprintf(__('You can find additional themes for your site by using the Theme Browser/Installer on this screen, which will display themes from the <a href="%s" target="_blank">WordPress.org Theme Directory</a>. These themes are designed and developed by third parties, are available free of charge, and are compatible with the license WordPress uses.'), 'https://wordpress.org/themes/') . '</p>' .
    '<p>' . __( 'You can Search for themes by keyword, author, or tag, or can get more specific and search by criteria listed in the feature filter.' ) . ' <span id="live-search-desc">' . __( 'The search results will be updated as you type.' ) . '</span></p>' .
    '<p>' . __( 'Alternately, you can browse the themes that are Featured, Popular, or Latest. When you find a theme you like, you can preview it or install it.' ) . '</p>' .
    '<p>' . __('You can Upload a theme manually if you have already downloaded its ZIP archive onto your computer (make sure it is from a trusted and original source). You can also do it the old-fashioned way and copy a downloaded theme&#8217;s folder via FTP into your <code>/wp-content/themes</code> directory.') . '</p>'
Definition at line 75 of file theme-install.php.
if (!is_network_admin()) $installed_themes = search_theme_directories()
Definition at line 30 of file theme-install.php.
Referenced by wp_update_themes().
$parent_file = 'themes.php'
Definition at line 24 of file theme-install.php.
$tabs = apply_filters('install_themes_tabs', array('upload' => __('Upload Theme')))
Filter the tabs shown on the Add Themes screen.
This filter is for backwards compatibility only, for the suppression of the upload tab.
Since
2.8.0
Parameters
array $tabs The tabs shown on the Add Themes screen. Default is 'upload'.
Definition at line 120 of file theme-install.php.
if (is_multisite()&&!is_network_admin()) $title = __('Add Themes')
Definition at line 23 of file theme-install.php.
$user = isset($_GET['user']) ? wp_unslash($_GET['user']) : get_user_option('wporg_favorites')
Definition at line 151 of file theme-install.php.