GravityView: time.php File Reference
time.php File Reference
Namespaces
GravityView
GPL2+
Variables
$field_id = \GV\Utils::_GET('field_id', \GV\Utils::get($gv_field, 'field_id'))
$gravityview_view = GravityView_View::getInstance()
$gv_field = $gravityview_view->getCurrentField()
$output = ''
$value = \GV\Utils::_GET('value', \GV\Utils::get($gv_field, 'value'))
if ('' !==$value)
Variable Documentation
$field_id
$field_id = \GV\Utils::_GET('field_id', \GV\Utils::get($gv_field, 'field_id'))
Definition at line 17 of file time.php.
Referenced by GravityView_Field_Time\_filter_date_display_date_format(), View_Table_Template\_get_multisort_url(), GravityView_Field_Time\_get_time_format_for_field(), GravityView_Field_Address\add_hooks(), Field_Template\add_id_specific_templates(), Internal_Field\by_id(), GF_Field\by_id(), GravityView_Widget_Search\convert_request_key_to_filter_key(), GravityView_Field_Date\date_display(), GravityView_Field_Time\date_format(), GravityView_Delete_Entry\delete_link_field_options(), GravityView_Duplicate_Entry\duplicate_link_field_options(), GravityView_Field_Post_Image\explode_value(), GravityView_HTML_Elements\field_dropdown(), GravityView_Field_Survey\field_options(), GravityView_Field_Radio\field_options(), GravityView_Field_Checkbox\field_options(), GravityView_Field_Select\field_options(), GravityView_Field_MultiSelect\field_options(), GravityView_Edit_Entry_Admin\field_options(), GravityView_Field_Time\field_options(), GravityView_Field_Address\field_options(), GravityView_Field\field_options(), GravityView_Plugin_Hooks_Gravity_Forms_Survey\fix_survey_field_value(), GravityView_Render_Settings\get_cap_choices(), GravityView_Render_Settings\get_default_field_options(), Internal_Source\get_field(), GF_Form\get_field(), GVCommon\get_field(), GVCommon\get_field_label(), GVCommon\get_field_type(), GravityView_Widget_Search\get_search_input_types(), View\get_unions(), gravityview_get_field(), gravityview_get_field_label(), gravityview_get_field_type(), gravityview_get_field_value(), gravityview_get_input_id_from_id(), gravityview_is_single_entry(), GravityView_frontend\is_field_sortable(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), GravityView_Delete_Entry\modify_visibility_caps(), GravityView_Duplicate_Entry\modify_visibility_caps(), Views_Route\prepare_entry_for_response(), GravityView_Widget_Search\prepare_field_filter(), GravityView_Render_Settings\render_field_options(), GravityView_Field_Address\search_bar_input_type(), View\template_redirect(), GravityView_Edit_Entry_Render\unselect_default_values(), GravityView_Edit_Entry_Render\update_calculation_fields(), and GravityView_Edit_Entry_Render\update_post_image().
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Definition at line 9 of file time.php.
$gv_field
$gv_field = $gravityview_view->getCurrentField()
Definition at line 11 of file time.php.
Referenced by GF_Field\by_id(), GVCommon\is_field_numeric(), GravityView_Field_Sequence\replace_merge_tag(), and GravityView_Edit_Entry_Render\verify_user_can_edit_post().
$output
$output = ''
Definition at line 19 of file time.php.
$value
$value = \GV\Utils::_GET('value', \GV\Utils::get($gv_field, 'value'))
Definition at line 14 of file time.php.
if
if('' !==$value)
Definition at line 21 of file time.php.