GravityView: index.php File Reference
tmp/wordpress/wp-admin/index.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$help = '<p>' . __('Welcome to your WordPress Dashboard! This is the screen you will see when you log in to your site, and gives you access to all the site management features of WordPress. You can get help for any screen by clicking the Help tab in the upper corner.') . '</p>'
$hide = 0 == $option || (2 == $option && wp_get_current_user()->user_email != get_option('admin_email'))
if(has_action('welcome_panel')&&current_user_can('edit_theme_options')) $option = get_user_meta(get_current_user_id(), 'show_welcome_panel', true)
$parent_file = 'index.php'
$screen = get_current_screen()
$title = __('Dashboard')
endif
Variable Documentation
else $help = '<p>' . __('Welcome to your WordPress Dashboard! This is the screen you will see when you log in to your site, and gives you access to all the site management features of WordPress. You can get help for any screen by clicking the Help tab in the upper corner.') . '</p>'
Definition at line 32 of file tmp/wordpress/wp-admin/index.php.
Referenced by add_contextual_help(), WP_Screen\add_old_compat_help(), and twentyeleven_theme_options_help().
$hide = 0 == $option || (2 == $option && wp_get_current_user()->user_email != get_option('admin_email'))
Definition at line 103 of file tmp/wordpress/wp-admin/index.php.
if (has_action('welcome_panel')&&current_user_can('edit_theme_options')) $option = get_user_meta(get_current_user_id(), 'show_welcome_panel', true)
Definition at line 101 of file tmp/wordpress/wp-admin/index.php.
Referenced by WP_PHPUnit_Util_Getopt\__construct(), __get_option(), GravityView_Uninstall_Test\_check_deleted_options(), wp_xmlrpc_server\_getOptions(), _wp_check_split_default_terms(), add_blog_option(), add_network_option(), add_option(), WP_Screen\add_option(), add_screen_option(), add_site_option(), WP_Customize_Widgets\call_widget_update(), GFAutoUpgrade\check_update(), delete_blog_option(), delete_network_option(), delete_option(), delete_site_option(), delete_site_transient(), delete_transient(), SimplePie_Enclosure\embed(), form_option(), get_all_user_settings(), get_alloptions_110(), get_blog_option(), get_default_comment_status(), WP_List_Table\get_items_per_page(), get_network_option(), get_option(), WP_Screen\get_option(), GFPaymentAddOn\get_order_data(), get_settings(), get_site_option(), get_user_option(), GFFeedAddOn\has_paypal_payment(), RGXML\is_attribute(), GFEntryDetail\lead_detail_grid(), populate_options(), WP_Screen\remove_option(), GravityView_Admin_Views\render_field_option(), GravityView_Render_Settings\render_field_option(), GravityView_Render_Settings\render_field_options(), WP_Screen\render_per_page_options(), sanitize_option(), RGXML\serialize(), set_screen_options(), set_site_transient(), update_blog_option(), update_network_option(), update_option(), update_site_option(), upgrade_130(), wp_load_core_site_options(), and wp_protect_special_option().
$parent_file = 'index.php'
Definition at line 30 of file tmp/wordpress/wp-admin/index.php.
$screen = get_current_screen()
Definition at line 35 of file tmp/wordpress/wp-admin/index.php.
Referenced by add_contextual_help(), add_meta_box(), WP_Screen\add_old_compat_help(), do_accordion_sections(), do_meta_boxes(), WP_Screen\get(), get_column_headers(), get_hidden_columns(), get_hidden_meta_boxes(), meta_box_prefs(), print_column_headers(), register_column_headers(), remove_meta_box(), WP_Customize_Nav_Menus_Panel\render_screen_options(), WP_Screen\render_view_mode(), twentyeleven_theme_options_help(), wp_add_dashboard_widget(), wp_auth_check_load(), wp_dashboard(), and wp_dashboard_setup().
$title = __('Dashboard')
Definition at line 29 of file tmp/wordpress/wp-admin/index.php.
endif
Definition at line 123 of file tmp/wordpress/wp-admin/index.php.