GravityView: class-oembed.php File Reference
tmp/wordpress/wp-includes/class-oembed.php File Reference
Data Structures
class WP_oEmbed
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_oembed_get_object ()
Returns the initialized WP_oEmbed object.
Function Documentation
_wp_oembed_get_object ()
Returns the initialized WP_oEmbed object.
Since
2.9.0 private
WP_oEmbed $wp_oembed
Returns
WP_oEmbed object.
Definition at line 617 of file tmp/wordpress/wp-includes/class-oembed.php.
References null.
Referenced by WP_Press_This\_limit_embed(), wp_filter_oembed_result(), wp_oembed_add_provider(), wp_oembed_get(), and wp_oembed_remove_provider().