GravityView: tools.php File Reference
tools.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$tags = get_taxonomy('post_tag')
$title = __('Tools')
WordPress Administration Bootstrap.
_e ('Copy &#8220;Press This &#8221;bookmarklet code')?></span ></button ></p >< div class
endif
ll be on your way to easier content creation Clicking on it while on another website opens a popup window with all these options</p > id converter title Categories and Tags Converter content< p > Categories have hierarchy
Run Importer link will take you to a screen where you can choose to convert tags into categories or vice versa</p >< p >< strong > For more information
Variable Documentation
$tags = get_taxonomy('post_tag')
Definition at line 100 of file tools.php.
Referenced by export_wp(), get_media_embedded_in_content(), GFFormsModel\get_post_fields(), get_tags(), get_the_category_rss(), getID3\HandleAllTags(), install_dashboard(), install_popular_tags(), links_add_target(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), WP_Query\parse_tax_query(), SimplePie_Sanitize\strip_htmltags(), SimplePie\strip_htmltags(), WP_Theme\translate_header(), wp_add_post_tags(), wp_ajax_get_tagcloud(), wp_generate_tag_cloud(), wp_get_post_terms(), wp_xmlrpc_server\wp_getTags(), wp_insert_post(), wp_kses_allowed_html(), wp_set_post_tags(), wp_set_post_terms(), and wp_tag_cloud().
$title = __('Tools')
WordPress Administration Bootstrap.
Definition at line 12 of file tools.php.
_e('Open Press This')?></a ></p >< script > jQuery(document).ready(function($)
Initial value:
="hidden js-pressthis-code-wrap clear" id="pressthis-code-wrap">
            <p id="pressthis-code-desc">
                <?php _e( 'If you can&#8217;t drag the bookmarklet to your bookmarks, copy the following code and create a new bookmark. Paste the code into the new bookmark&#8217;s URL field.' )
Definition at line 54 of file tools.php.
endif
Definition at line 96 of file tools.php.
ll be on your way to easier content creation Clicking on it while on another website opens a popup window with all these options</p> id converter title Categories and Tags Converter content<p> Categories have hierarchy
Definition at line 22 of file tools.php.
Run Importer link will take you to a screen where you can choose to convert tags into categories or vice versa</p><p><strong> For more information
Definition at line 30 of file tools.php.