GravityView: tooltips.php File Reference
tooltips.php File Reference
Functions
gform_tooltip ($name, $css_class= '', $return=false)
print_tooltip_scripts ()
Variables
global $__gf_tooltips
Function Documentation
gform_tooltip ($name, $css_class = '', $return = false)
Definition at line 167 of file tooltips.php.
References $__gf_tooltips, $name, apply_filters(), and esc_attr().
Referenced by GF_Installation_Wizard_Step_Settings\display(), GFExport\export_form_page(), GFExport\export_lead_page(), GFFormSettings\form_settings_ui(), get_confirmation_ui_settings(), GFExport\import_form_page(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GFAddOn\settings_text(), GFAddOn\settings_textarea(), GFAddOn\single_section(), GravityView_Settings\single_setting_label(), and GFAddOn\single_setting_label().
print_tooltip_scripts ()
Definition at line 9 of file tooltips.php.
References $min, null, wp_enqueue_style(), wp_print_scripts(), and wp_print_styles().
Variable Documentation
$__gf_tooltips
Definition at line 21 of file tooltips.php.
Referenced by gform_tooltip().