GravityView: translation-install.php File Reference
translation-install.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
translations_api ($type, $args=null)
Retrieve translations from WordPress Translation API.
wp_can_install_language_pack ()
Check if WordPress has access to the filesystem without asking for credentials.
wp_download_language_pack ($download)
Download a language pack.
wp_get_available_translations ()
Get available translations from the WordPress.org API.
wp_install_language_form ($languages)
Output the select form for the language selection on the installation screen.
Function Documentation
translations_api ($type, $args = null)
Retrieve translations from WordPress Translation API.
Since
4.0.0
Parameters
string $type Type of translations. Accepts 'plugins', 'themes', 'core'.
array | object $args Translation API arguments. Optional.
Returns
object|WP_Error On success an object of translations, WP_Error on failure.
Allows a plugin to override the WordPress.org Translation Install API entirely.
Since
4.0.0
Parameters
bool | array $result The result object. Default false.
string $type The type of translations being requested.
object $args Translation API arguments.
Filter the Translation Install API response results.
Since
4.0.0
Parameters
object | WP_Error $res Response object or WP_Error.
string $type The type of translations being requested.
object $args Translation API arguments.
Definition at line 19 of file translation-install.php.
References $options, $url, $wp_version, __, ABSPATH, apply_filters(), get_locale(), is_wp_error(), set_url_scheme(), WP_DEBUG, wp_http_supports(), wp_remote_post(), wp_remote_retrieve_body(), and WPINC.
Referenced by wp_get_available_translations().
wp_can_install_language_pack ()
Check if WordPress has access to the filesystem without asking for credentials.
Since
4.0.0
Returns
bool Returns true on success, false on failure.
Definition at line 226 of file translation-install.php.
References ABSPATH, is_wp_error(), and WP_CONTENT_DIR.
wp_download_language_pack ($download)
Download a language pack.
Since
4.0.0
See also
wp_get_available_translations()
Parameters
string $download Language code to download.
Returns
string|bool Returns the language code if successfully downloaded (or already installed), or false on failure.
Definition at line 178 of file translation-install.php.
References $translations, ABSPATH, get_available_languages(), is_wp_error(), object, and wp_get_available_translations().
wp_get_available_translations ()
Get available translations from the WordPress.org API.
Since
4.0.0
See also
translations_api()
Returns
array Array of translations, each an array of data. If the API response results in an error, an empty array will be returned.
Definition at line 96 of file translation-install.php.
References $translations, $wp_version, ABSPATH, get_site_transient(), is_wp_error(), set_site_transient(), translations_api(), wp_installing(), and WPINC.
Referenced by wp_download_language_pack(), and wp_dropdown_languages().
wp_install_language_form ($languages)
Output the select form for the language selection on the installation screen.
Since
4.0.0
string $wp_local_package
Parameters
array $languages Array of available languages (populated via the Translation API).
Definition at line 131 of file translation-install.php.
References $language, esc_attr(), esc_html, and get_available_languages().