GravityView: customizer.php File Reference
twentyfourteen/inc/customizer.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyfourteen_contextual_help ()
Add contextual help to the Themes and Post edit screens.
twentyfourteen_customize_preview_js ()
Bind JS handlers to make Customizer preview reload changes asynchronously.
twentyfourteen_customize_register ($wp_customize)
Implement Customizer additions and adjustments.
twentyfourteen_sanitize_layout ($layout)
Sanitize the Featured Content layout value.
Function Documentation
twentyfourteen_contextual_help ()
Add contextual help to the Themes and Post edit screens.
Since
Twenty Fourteen 1.0
Definition at line 98 of file twentyfourteen/inc/customizer.php.
References $GLOBALS, __, _x, add_query_arg(), admin_url(), current_filter(), esc_url, and get_current_screen().
twentyfourteen_customize_preview_js ()
Bind JS handlers to make Customizer preview reload changes asynchronously.
Since
Twenty Fourteen 1.0
Definition at line 88 of file twentyfourteen/inc/customizer.php.
References get_template_directory_uri(), and wp_enqueue_script().
twentyfourteen_customize_register ($wp_customize)
Implement Customizer additions and adjustments.
Since
Twenty Fourteen 1.0
Parameters
WP_Customize_Manager $wp_customize Customizer object.
Definition at line 17 of file twentyfourteen/inc/customizer.php.
References $wp_customize, __, _x, add_query_arg(), admin_url(), and esc_url.
twentyfourteen_sanitize_layout ($layout)
Sanitize the Featured Content layout value.
Since
Twenty Fourteen 1.0
Parameters
string $layout Layout type.
Returns
string Filtered layout type (grid|slider).
Definition at line 75 of file twentyfourteen/inc/customizer.php.