GravityView: customizer.php File Reference
twentyfifteen/inc/customizer.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyfifteen_color_scheme_css ()
Enqueues front-end CSS for color scheme.
twentyfifteen_color_scheme_css_template ()
Output an Underscore template for generating CSS for the color scheme.
twentyfifteen_customize_control_js ()
Binds JS listener to make Customizer color_scheme control.
twentyfifteen_customize_preview_js ()
Binds JS handlers to make the Customizer preview reload changes asynchronously.
twentyfifteen_customize_register ($wp_customize)
Add postMessage support for site title and description for the Customizer.
twentyfifteen_get_color_scheme_css ($colors)
Returns CSS for the color schemes.
twentyfifteen_get_color_schemes ()
Register color schemes for Twenty Fifteen.
Variables
if(!function_exists('twentyfifteen_get_color_scheme'))() endif
Function Documentation
twentyfifteen_color_scheme_css ()
Enqueues front-end CSS for color scheme.
Since
Twenty Fifteen 1.0
See also
wp_add_inline_style()
Definition at line 248 of file twentyfifteen/inc/customizer.php.
References get_theme_mod(), twentyfifteen_get_color_scheme_css(), twentyfifteen_hex2rgb(), and wp_add_inline_style().
twentyfifteen_color_scheme_css_template ()
Output an Underscore template for generating CSS for the color scheme.
The template generates the css dynamically for instant display in the Customizer preview.
Since
Twenty Fifteen 1.0
Definition at line 715 of file twentyfifteen/inc/customizer.php.
References twentyfifteen_get_color_scheme_css().
twentyfifteen_customize_control_js ()
Binds JS listener to make Customizer color_scheme control.
Passes color scheme data as colorScheme global.
Since
Twenty Fifteen 1.0
Definition at line 289 of file twentyfifteen/inc/customizer.php.
References get_template_directory_uri(), twentyfifteen_get_color_schemes(), wp_enqueue_script(), and wp_localize_script().
twentyfifteen_customize_preview_js ()
Binds JS handlers to make the Customizer preview reload changes asynchronously.
Since
Twenty Fifteen 1.0
Definition at line 300 of file twentyfifteen/inc/customizer.php.
References get_template_directory_uri(), and wp_enqueue_script().
twentyfifteen_customize_register ($wp_customize)
Add postMessage support for site title and description for the Customizer.
Since
Twenty Fifteen 1.0
Parameters
WP_Customize_Manager $wp_customize Customizer object.
Definition at line 17 of file twentyfifteen/inc/customizer.php.
References $wp_customize, and __.
twentyfifteen_get_color_scheme_css ($colors)
Returns CSS for the color schemes.
Since
Twenty Fifteen 1.0
Parameters
array $colors Color scheme colors.
Returns
string Color scheme CSS.
Definition at line 313 of file twentyfifteen/inc/customizer.php.
References a, author, button, color, comments, input, label, li, outline, password, textarea, title, width, and wp_parse_args().
Referenced by twentyfifteen_color_scheme_css(), and twentyfifteen_color_scheme_css_template().
twentyfifteen_get_color_schemes ()
Register color schemes for Twenty Fifteen.
Can be filtered with {
See also
'twentyfifteen_color_schemes'}.
The order of colors in a colors array:
Main Background Color.
Sidebar Background Color.
Box Background Color.
Main Text and Link Color.
Sidebar Text and Link Color.
Meta Box Background Color.
Since
Twenty Fifteen 1.0
Returns
array An associative array of color scheme options.
Filter the color schemes registered for use with Twenty Fifteen.
The default schemes include 'default', 'dark', 'yellow', 'pink', 'purple', and 'blue'.
Since
Twenty Fifteen 1.0
Parameters
array $schemes { Associative array of color schemes data.
array $slug { Associative array of information for setting up the color scheme.
string $label Color scheme label. array $colors HEX codes for default colors prepended with a hash symbol ('#'). Colors are defined in the following order: Main background, sidebar background, box background, main text and link, sidebar text and link, meta box background. } }
Definition at line 89 of file twentyfifteen/inc/customizer.php.
References __, and apply_filters().
Referenced by twentyfifteen_customize_control_js().
Variable Documentation
if (! function_exists('twentyfifteen_sanitize_color_scheme')) ($value) endif
Definition at line 181 of file twentyfifteen/inc/customizer.php.