GravityView: back-compat.php File Reference
twentyfourteen/inc/back-compat.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyfourteen_customize ()
Prevent the Customizer from being loaded on WordPress versions prior to 3.6.
twentyfourteen_preview ()
Prevent the Theme Preview from being loaded on WordPress versions prior to 3.4.
twentyfourteen_switch_theme ()
Prevent switching to Twenty Fourteen on old versions of WordPress.
twentyfourteen_upgrade_notice ()
Add message for unsuccessful theme switch.
Function Documentation
twentyfourteen_customize ()
Prevent the Customizer from being loaded on WordPress versions prior to 3.6.
Since
Twenty Fourteen 1.0
Definition at line 46 of file twentyfourteen/inc/back-compat.php.
References $GLOBALS, __, and wp_die().
twentyfourteen_preview ()
Prevent the Theme Preview from being loaded on WordPress versions prior to 3.4.
Since
Twenty Fourteen 1.0
Definition at line 58 of file twentyfourteen/inc/back-compat.php.
References $GLOBALS, __, and wp_die().
twentyfourteen_switch_theme ()
Prevent switching to Twenty Fourteen on old versions of WordPress.
Switches to the default theme.
Since
Twenty Fourteen 1.0
Definition at line 21 of file twentyfourteen/inc/back-compat.php.
References add_action(), and switch_theme().
twentyfourteen_upgrade_notice ()
Add message for unsuccessful theme switch.
Prints an update nag after an unsuccessful attempt to switch to Twenty Fourteen on WordPress versions prior to 3.6.
Since
Twenty Fourteen 1.0
Definition at line 36 of file twentyfourteen/inc/back-compat.php.
References $GLOBALS, $message, and __.