GravityView: back-compat.php File Reference
twentythirteen/inc/back-compat.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentythirteen_customize ()
Prevent the Customizer from being loaded on WordPress versions prior to 3.6.
twentythirteen_preview ()
Prevent the Theme Preview from being loaded on WordPress versions prior to 3.4.
twentythirteen_switch_theme ()
Prevent switching to Twenty Thirteen on old versions of WordPress.
twentythirteen_upgrade_notice ()
Add message for unsuccessful theme switch.
Function Documentation
twentythirteen_customize ()
Prevent the Customizer from being loaded on WordPress versions prior to 3.6.
Since
Twenty Thirteen 1.0
Definition at line 46 of file twentythirteen/inc/back-compat.php.
References $GLOBALS, __, and wp_die().
twentythirteen_preview ()
Prevent the Theme Preview from being loaded on WordPress versions prior to 3.4.
Since
Twenty Thirteen 1.0
Definition at line 58 of file twentythirteen/inc/back-compat.php.
References $GLOBALS, __, and wp_die().
twentythirteen_switch_theme ()
Prevent switching to Twenty Thirteen on old versions of WordPress.
Switches to the default theme.
Since
Twenty Thirteen 1.0
Definition at line 21 of file twentythirteen/inc/back-compat.php.
References add_action(), and switch_theme().
twentythirteen_upgrade_notice ()
Add message for unsuccessful theme switch.
Prints an update nag after an unsuccessful attempt to switch to Twenty Thirteen on WordPress versions prior to 3.6.
Since
Twenty Thirteen 1.0
Definition at line 36 of file twentythirteen/inc/back-compat.php.
References $GLOBALS, $message, and __.