GravityView: content-link.php File Reference
twentyfifteen/content-link.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
else __pad4__
endif
else esc_url (twentyfifteen_get_link_url()))
Variable Documentation
else __pad4__
Definition at line 21 of file twentyfifteen/content-link.php.
endif
Definition at line 22 of file twentyfifteen/content-link.php.
else esc_url(twentyfifteen_get_link_url()))
Definition at line 21 of file twentyfifteen/content-link.php.
Referenced by _access_denied_splash(), WP_Styles\_css_href(), _get_plugin_data_markup_translate(), _walk_bookmarks(), _wp_credits_add_profile_link(), _wp_credits_build_object_link(), _wp_customize_loader_settings(), _wp_dashboard_recent_comments_row(), _wp_link_page(), _wp_post_thumbnail_html(), GFForms\add_form_button(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Notices\admin_notice(), Custom_Background\admin_page(), choose_primary_blog(), clean_url(), WP_Media_List_Table\column_author(), WP_Comments_List_Table\column_author(), WP_MS_Users_List_Table\column_blogs(), WP_Comments_List_Table\column_comment(), WP_Comments_List_Table\column_date(), WP_Media_List_Table\column_default(), WP_MS_Users_List_Table\column_email(), WP_Terms_List_Table\column_name(), WP_MS_Themes_List_Table\column_name(), GFConfirmationTable\column_name(), WP_Terms_List_Table\column_posts(), WP_MS_Users_List_Table\column_username(), WP_MS_Sites_List_Table\column_users(), comment_guid(), comment_link(), WP_List_Table\comments_bubble(), comments_link(), comments_link_feed(), comments_rss(), comments_template(), confirm_delete_users(), WP_Customize_Theme_Control\content_template(), core_upgrade_preamble(), Featured_Content\customize_register(), customize_themes_print_templates(), WP_oEmbed\data2html(), GF_Installation_Wizard\display(), WP_Plugin_Install_List_Table\display_rows(), GFAutoUpgrade\display_updates(), do_core_upgrade(), WP_Scripts\do_item(), edit_bookmark_link(), edit_comment_link(), GravityView_Edit_Entry_Render\edit_entry_form(), edit_link(), edit_post_link(), GFEntryDetail\entry_detail_pagination_link(), feed_links(), feed_links_extra(), GFFeedAddOn\feed_list_title(), GFForms\format_toolbar_menu_items(), GFFeedAddOn\get_action_links(), get_archives_link(), get_blogaddress_by_id(), get_blogaddress_by_name(), get_category_parents(), get_comment_author_email_link(), get_comment_author_url(), get_comment_reply_link(), get_comment_to_edit(), get_default_link_to_edit(), WP_Posts_List_Table\get_edit_link(), GF_Field_Date\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GFFormDisplay\get_form(), get_index_rel_link(), get_links(), GFLocking\get_lock_ui(), get_most_active_blogs(), get_next_comments_link(), get_pagenum_link(), get_post_embed_html(), get_previous_comments_link(), get_sample_permalink_html(), get_search_form(), GravityView_Widget_Search\get_search_form_action(), get_the_author_link(), get_the_author_posts_link(), get_the_category_list(), get_the_password_form(), get_the_term_list(), get_theme_update_available(), WP_Users_List_Table\get_views(), WP_MS_Themes_List_Table\get_views(), handle_confirmation_edit_submission(), WP_Terms_List_Table\handle_row_actions(), WP_MS_Users_List_Table\handle_row_actions(), WP_MS_Sites_List_Table\handle_row_actions(), WP_Comments_List_Table\handle_row_actions(), WP_Posts_List_Table\handle_row_actions(), header_image(), install_dashboard(), install_plugin_information(), WP_Theme_Install_List_Table\install_theme_info(), GravityView_Settings\license_key_notice(), list_core_update(), WP_Theme\markup_header(), WP_Embed\maybe_make_link(), media_upload_library_form(), media_upload_max_image_resize(), media_upload_type_url_form(), menu_page_url(), network_step1(), newblog_notify_siteadmin(), newuser_notify_siteadmin(), next_posts(), WP_Plugins_List_Table\no_items(), notification_edit_page(), paginate_links(), WP_List_Table\pagination(), GFForms\plugin_settings_link(), post_comments_feed_link(), post_submit_meta_box(), previous_posts(), WP_List_Table\print_column_headers(), rel_canonical(), WP_Customize_Manager\remove_panel(), GFFormDisplay\replace_save_variables(), GFPaymentAddOn\requires_credit_card_message(), rest_output_link_wp_head(), rsd_link(), sanitize_user_field(), self_link(), send_confirmation_on_profile_email(), WP_Theme_Install_List_Table\single_row(), WP_Users_List_Table\single_row(), WP_Plugins_List_Table\single_row(), site_admin_notice(), site_icon_url(), Walker_Nav_Menu\start_el(), Walker_Category\start_el(), Custom_Image_Header\step_1(), GV_License_Handler\strings(), the_feed_link(), the_media_upload_tabs(), the_permalink(), the_permalink_rss(), the_post_thumbnail_url(), the_shortlink(), GFForms\toolbar_sub_menu_items(), twentyfifteen_post_nav_background(), twentyfourteen_contextual_help(), twentyfourteen_customize_register(), twentythirteen_admin_header_style(), update_option_new_admin_email(), WP_List_Table\view_switcher(), WP_Widget_RSS\widget(), WP_Widget_Meta\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), WP_Widget_Recent_Comments\widget(), wp_add_dashboard_widget(), wp_admin_bar_edit_menu(), wp_admin_bar_search_menu(), wp_admin_css(), wp_ajax_send_attachment_to_editor(), wp_ajax_send_link_to_editor(), wp_audio_shortcode(), wp_customize_url(), wp_dashboard_recent_drafts(), wp_embed_excerpt_more(), wp_embed_handler_audio(), wp_embed_handler_video(), wp_filter_oembed_result(), wp_generate_tag_cloud(), wp_list_authors(), wp_list_categories(), wp_login_form(), wp_loginout(), wp_media_upload_handler(), wp_mediaelement_fallback(), wp_nonce_ays(), wp_oembed_add_discovery_links(), wp_plugin_update_row(), wp_prepare_themes_for_js(), wp_register(), wp_set_comment_cookies(), wp_shortlink_wp_head(), wp_site_icon(), wp_theme_update_row(), wp_version_check(), wp_video_shortcode(), wp_widget_rss_output(), wp_widget_rss_process(), and wpmu_signup_blog_notification().