GravityView: update-core.php File Reference
update-core.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
core_upgrade_preamble ()
Display upgrade WordPress for downloading latest or upgrading automatically form.
dismissed_updates ()
do_core_upgrade ($reinstall=false)
Upgrade WordPress core display.
do_dismiss_core_update ()
do_undismiss_core_update ()
list_core_update ($update)
string $wp_local_package wpdb $wpdb string $wp_version
list_plugin_updates ()
string $wp_version
list_theme_updates ()
list_translation_updates ()
Variables
$action = isset($_GET['action']) ? $_GET['action'] : 'upgrade-core'
$parent_file = 'index.php'
if(('do-theme-upgrade'==$action||('do-plugin-upgrade'==$action &&!isset($_GET['plugins'])))&&!isset($_POST['checked'])) $title = __('WordPress Updates')
$updates_howto = '<p>' . __('<strong>WordPress</strong> &mdash; Updating your WordPress installation is a simple one-click procedure: just <strong>click on the &#8220;Update Now&#8221; button</strong> when you are notified that a new version is available.') . ' ' . __('In most cases, WordPress will automatically apply maintenance and security updates in the background for you.') . '</p>'
$updates_overview = '<p>' . __('On this screen, you can update to the latest version of WordPress, as well as update your themes, plugins, and translations from the WordPress.org repositories.') . '</p>'
$upgrade_error = false
if('upgrade-core'==$action) elseif('do-core-upgrade'==$action|| 'do-core-reinstall'==$action) elseif('do-plugin-upgrade'==$action) elseif('do-theme-upgrade'==$action) elseif('do-translation-upgrade'==$action) else
Function Documentation
core_upgrade_preamble ()
Display upgrade WordPress for downloading latest or upgrading automatically form.
Since
2.7.0
string $wp_version string $required_php_version string $required_mysql_version
Definition at line 156 of file update-core.php.
References $required_mysql_version, $required_php_version, $update, $wp_version, __, _e, ABSPATH, dismissed_updates(), elseif, esc_url, get_core_updates(), list_core_update(), object, self_admin_url(), WP_Automatic_Updater\should_update(), and wp_http_supports().
dismissed_updates ()
Since
2.7.0
Definition at line 120 of file update-core.php.
References $update, __, esc_js(), get_core_updates(), and list_core_update().
Referenced by core_upgrade_preamble().
do_core_upgrade ($reinstall = false)
Upgrade WordPress core display.
Since
2.7.0
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
bool $reinstall
Definition at line 430 of file update-core.php.
References $locale, $message, $update, $url, __, _e, ABSPATH, add_filter(), esc_url, find_core_update(), is_wp_error(), request_filesystem_credentials(), self_admin_url(), show_message(), WP_Filesystem(), and wp_nonce_url().
do_dismiss_core_update ()
Since
2.7.0
Definition at line 507 of file update-core.php.
References $locale, $update, dismiss_core_update(), exit, find_core_update(), and wp_nonce_url().
do_undismiss_core_update ()
Since
2.7.0
Fires after the core, plugin, and theme update tables.
Since
2.9.0
Definition at line 521 of file update-core.php.
References $locale, $update, exit, find_core_update(), undismiss_core_update(), and wp_nonce_url().
list_core_update ($update)
string $wp_local_package wpdb $wpdb string $wp_version
bool $first_pass
Parameters
object $update
Definition at line 35 of file update-core.php.
References $form_action, $message, $mysql_compat, $mysql_version, $php_compat, $php_version, $update, $wp_version, $wpdb, __, elseif, esc_attr(), esc_url, get_core_updates(), get_locale(), submit_button(), WP_CONTENT_DIR, and wp_nonce_field().
Referenced by core_upgrade_preamble(), and dismissed_updates().
list_plugin_updates ()
string $wp_version
Definition at line 220 of file update-core.php.
References $compat, $form_action, $plugins, $wp_version, __, _e, ABSPATH, elseif, get_core_updates(), get_plugin_updates(), input, label, name, and wp_nonce_field().
list_theme_updates ()
Since
2.9.0
Definition at line 329 of file update-core.php.
References $form_action, $theme, __, _e, get_theme_updates(), height, input, label, name, width, and wp_nonce_field().
list_translation_updates ()
Since
3.7.0
Definition at line 400 of file update-core.php.
References $form_action, __, _e, get_locale(), input, name, wp_get_translation_updates(), and wp_nonce_field().
Variable Documentation
$action = isset($_GET['action']) ? $_GET['action'] : 'upgrade-core'
Definition at line 532 of file update-core.php.
$parent_file = 'index.php'
Definition at line 542 of file update-core.php.
if (('do-theme-upgrade'==$action||('do-plugin-upgrade'==$action &&!isset($_GET['plugins'])))&&!isset($_POST['checked'])) $title = __('WordPress Updates')
Definition at line 541 of file update-core.php.
$updates_howto = '<p>' . __('<strong>WordPress</strong> &mdash; Updating your WordPress installation is a simple one-click procedure: just <strong>click on the &#8220;Update Now&#8221; button</strong> when you are notified that a new version is available.') . ' ' . __('In most cases, WordPress will automatically apply maintenance and security updates in the background for you.') . '</p>'
Definition at line 553 of file update-core.php.
$updates_overview = '<p>' . __('On this screen, you can update to the latest version of WordPress, as well as update your themes, plugins, and translations from the WordPress.org repositories.') . '</p>'
Definition at line 544 of file update-core.php.
$upgrade_error = false
Definition at line 534 of file update-core.php.
if ('upgrade-core'==$action) elseif ('do-core-upgrade'==$action|| 'do-core-reinstall'==$action) elseif ('do-plugin-upgrade'==$action) elseif ('do-theme-upgrade'==$action) elseif ('do-translation-upgrade'==$action) else
Initial value:
{
    do_action( "update-core-custom_{$action}" )
Definition at line 717 of file update-core.php.