GravityView: user-edit.php File Reference
user-edit.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$current_user = wp_get_current_user()
else $parent_file = 'profile.php'
$profile_help
else $submenu_file = 'profile.php'
$title = IS_PROFILE_PAGE ? __('Profile') : __('Edit User')
$user_can_edit = current_user_can('edit_posts') || current_user_can('edit_pages')
$user_id = (int) $user_id
$wp_http_referer = remove_query_arg(array('update', 'delete_count'), $wp_http_referer)
if(is_multisite()&&!current_user_can('manage_network_users')&&$user_id!=$current_user->ID &&!apply_filters('enable_edit_any_user_configuration', true)) if(is_multisite()&&IS_PROFILE_PAGE &&isset($_GET[ 'newuseremail'])&&$current_user->ID) elseif(is_multisite()&&IS_PROFILE_PAGE &&!empty($_GET['dismiss'])&&$current_user->ID. '_new_email'==$_GET['dismiss']) switch ($action)
Filter whether to allow administrators on Multisite to edit every user.
Variable Documentation
$current_user = wp_get_current_user()
Definition at line 15 of file user-edit.php.
Referenced by GravityView_Edit_Entry_Test\_add_and_remove_caps_test(), GFAPI\add_entry(), GravityView_Delete_Entry\check_user_cap_delete_entry(), GravityView_Edit_Entry\check_user_cap_edit_entry(), confirm_delete_users(), GFFormsModel\create_lead(), current_user_can(), current_user_can_for_blog(), GFForms\init(), is_user_option_local(), GFEntryDetail\lead_detail_page(), restore_current_blog(), GFFormsModel\save_lead(), send_confirmation_on_profile_email(), switch_to_blog(), GFAPI\update_entry(), GravityView_Change_Entry_Creator\update_entry_creator(), update_option_new_admin_email(), wp_admin_bar_my_account_item(), wp_admin_bar_my_account_menu(), and wp_update_user().
else $parent_file = 'profile.php'
Definition at line 37 of file user-edit.php.
$profile_help
Initial value:
= '<p>' . __('Your profile contains information about you (your &#8220;account&#8221;) as well as some personal options related to using WordPress.') . '</p>' .
    '<p>' . __('You can change your password, turn on keyboard shortcuts, change the color scheme of your WordPress administration screens, and turn off the WYSIWYG (Visual) editor, among other things. You can hide the Toolbar (formerly called the Admin Bar) from the front end of your site, however it cannot be disabled on the admin screens.') . '</p>' .
    '<p>' . __('Your username cannot be changed, but you can use other fields to enter your real name or a nickname, and change which name to display on your posts.') . '</p>' .
    '<p>' . __( 'You can log out of other devices, such as your phone or a public computer, by clicking the Log Out Everywhere Else button.' ) . '</p>' .
    '<p>' . __('Required fields are indicated; the rest are optional. Profile information will only be displayed if your theme is set up to do so.') . '</p>' .
    '<p>' . __('Remember to click the Update Profile button when you are finished.') . '</p>'
Definition at line 39 of file user-edit.php.
else $submenu_file = 'profile.php'
Definition at line 32 of file user-edit.php.
$title = IS_PROFILE_PAGE ? __('Profile') : __('Edit User')
Definition at line 28 of file user-edit.php.
$user_can_edit = current_user_can('edit_posts') || current_user_can('edit_pages')
Definition at line 60 of file user-edit.php.
Referenced by GravityView_Edit_Entry\check_user_cap_edit_entry(), WP_Media_List_Table\column_parent(), and get_compat_media_markup().
$user_id = (int) $user_id
Definition at line 14 of file user-edit.php.
Referenced by WP_Ajax_UnitTestCase\_setRole(), GFAPI\add_entry(), add_new_user_to_blog(), GFFormsModel\add_note(), GFAddOn\add_note(), add_user_meta(), add_user_to_blog(), admin_color_scheme_picker(), GravityView_Change_Entry_Creator\assign_new_user_to_lead(), GFLocking\check_lock(), GFLocking\check_lock_request(), check_password_reset_key(), confirm_delete_users(), GV_UnitTest_Factory_For_User\create(), GV_UnitTest_Factory_For_User\create_and_set(), WP_UnitTest_Factory_For_Blog\create_object(), delete_all_user_settings(), WP_UnitTestCase\delete_user(), delete_user_meta(), delete_user_option(), delete_usermeta(), WP_Internal_Pointers\dismiss_pointers_for_new_users(), edit_user(), get_active_blog_for_user(), get_adjacent_post(), get_all_user_settings(), get_blogs_of_user(), get_dashboard_url(), WP_User\get_data_by(), get_edit_profile_url(), get_edit_user_link(), get_editable_authors(), get_editable_user_ids(), GFLocking\get_lock_ui(), get_most_recent_post_of_user(), WP_UnitTest_Factory_For_User\get_object_by_id(), get_others_drafts(), get_others_pending(), get_others_unpublished_posts(), WP_Query\get_posts(), get_the_author_meta(), get_user_meta(), get_user_to_edit(), get_usermeta(), get_users_drafts(), grant_super_admin(), GVCommon\has_cap(), GravityView_Roles_Capabilities\has_cap(), GFLocking\heartbeat_check_locked_objects(), GFLocking\heartbeat_refresh_lock(), GFLocking\heartbeat_request_lock(), install_blog_defaults(), GFLocking\is_locked(), is_site_admin(), is_super_admin(), is_user_member_of_blog(), GFLocking\lock_info(), map_meta_cap(), GravityView_Edit_Entry_User_Registration\match_current_display_name(), GFLocking\maybe_lock_object(), newuser_notify_siteadmin(), WP_Comments_List_Table\prepare_items(), register_new_user(), remove_user_from_blog(), GFLocking\request_lock(), GravityView_Edit_Entry_User_Registration\restore_display_name(), revoke_super_admin(), sanitize_user_field(), GFFormsModel\save_lead(), GV_UnitTest_Factory_For_User\set(), GFLocking\set_lock(), WP_Importer\set_user(), GravityView_Roles_Capabilities_Test\test_has_cap_user_id_parameter(), the_author_meta(), GFAPI\update_entry(), WP_UnitTest_Factory_For_User\update_object(), update_user_meta(), GravityView_Support_Port\update_user_meta_value(), update_user_option(), update_usermeta(), user_can_create_draft(), user_can_create_post(), user_can_delete_post(), user_can_delete_post_comments(), user_can_edit_post(), user_can_edit_post_comments(), user_can_edit_post_date(), user_can_edit_user(), user_can_set_post_date(), wp_admin_bar_dashboard_view_site_menu(), wp_admin_bar_my_account_item(), wp_admin_bar_my_account_menu(), wp_ajax_add_user(), wp_authenticate_cookie(), wp_check_locked_posts(), wp_dashboard_quick_press(), wp_get_post_autosave(), wp_xmlrpc_server\wp_getUser(), wp_insert_comment(), wp_insert_post(), wp_insert_user(), wp_refresh_post_lock(), wp_send_new_user_notifications(), wp_set_all_user_settings(), wp_update_user(), wp_user_settings(), wp_validate_logged_in_cookie(), wpmu_activate_signup(), wpmu_create_blog(), wpmu_create_user(), wpmu_delete_blog(), wpmu_log_new_registrations(), wpmu_welcome_notification(), and wpmu_welcome_user_notification().
$wp_http_referer = remove_query_arg(array('update', 'delete_count'), $wp_http_referer)
Definition at line 58 of file user-edit.php.
if (is_multisite()&&!current_user_can('manage_network_users')&&$user_id!=$current_user->ID &&!apply_filters('enable_edit_any_user_configuration', true)) if (is_multisite()&&IS_PROFILE_PAGE &&isset($_GET[ 'newuseremail'])&&$current_user->ID) elseif (is_multisite()&&IS_PROFILE_PAGE &&!empty($_GET['dismiss'])&&$current_user->ID. '_new_email'==$_GET['dismiss']) switch($action)
Filter whether to allow administrators on Multisite to edit every user.
Enabling the user editing form via this filter also hinges on the user holding the 'manage_network_users' cap, and the logged-in user not matching the user profile open for editing.
The filter was introduced to replace the EDIT_ANY_USER constant.
Since
3.0.0
Parameters
bool $allow Whether to allow editing of any user. Default true.
Definition at line 103 of file user-edit.php.