GravityView: utils.php File Reference
utils.php File Reference
Data Structures
class MockAction
class MockClass
Use to create objects by yourself.
class testXMLParser
class wpdb_exposed_methods_for_testing
Special class for exposing protected wpdb methods we need to access.
Functions
_clean_term_filters ()
_cleanup_query_vars ()
_unregister_post_status ($status)
Unregister a post status.
if(!function_exists('str_getcsv')) _unregister_post_type ($cpt_name)
Removes the post type and its taxonomy associations.
_unregister_taxonomy ($taxonomy_name)
benchmark_pcre_backtracking ($pattern, $subject, $strategy)
Determine approximate backtrack count when running PCRE.
dmp ()
dmp_filter ($a)
drop_tables ()
Drops all tables from the WordPress database.
gen_tests_array ($name, $array)
get_echo ($callable, $args=array())
mask_input_value ($in, $name='_wpnonce')
print_backtrace ()
rand_long_str ($length)
rand_str ($len=32)
strip_ws ($txt)
xml_array_dumbdown (&$data)
xml_find ($tree)
xml_join_atts ($atts)
xml_to_array ($in)
Function Documentation
_clean_term_filters ()
Definition at line 382 of file utils.php.
_cleanup_query_vars ()
Definition at line 363 of file utils.php.
Referenced by WP_UnitTestCase\go_to().
_unregister_post_status ($status)
Unregister a post status.
Since
4.2.0
Parameters
string $status
Definition at line 359 of file utils.php.
Referenced by WP_UnitTestCase\reset_post_statuses().
if (!function_exists('str_getcsv')) _unregister_post_type ($cpt_name)
Removes the post type and its taxonomy associations.
Definition at line 337 of file utils.php.
Referenced by WP_UnitTestCase\reset_post_types().
_unregister_taxonomy ($taxonomy_name)
Definition at line 348 of file utils.php.
Referenced by WP_UnitTestCase\reset_taxonomies().
benchmark_pcre_backtracking ($pattern, $subject, $strategy)
Determine approximate backtrack count when running PCRE.
Returns
int The backtrack count.
Definition at line 411 of file utils.php.
dmp ()
Definition at line 248 of file utils.php.
Referenced by MockAction\action(), MockAction\action2(), dmp_filter(), MockAction\filter(), MockAction\filter2(), MockAction\filter_append(), and MockAction\filterall().
dmp_filter ($a)
Definition at line 255 of file utils.php.
References dmp().
drop_tables ()
Drops all tables from the WordPress database.
Definition at line 296 of file utils.php.
gen_tests_array ($name, $array)
Definition at line 267 of file utils.php.
References $out.
get_echo ($callable, $args = array())
Definition at line 260 of file utils.php.
mask_input_value ($in, $name = '_wpnonce')
Definition at line 319 of file utils.php.
print_backtrace ()
Definition at line 303 of file utils.php.
rand_long_str ($length)
Definition at line 9 of file utils.php.
References $i.
rand_str ($len = 32)
Definition at line 5 of file utils.php.
strip_ws ($txt)
Definition at line 22 of file utils.php.
xml_array_dumbdown (& $data)
Definition at line 230 of file utils.php.
References $i, $name, and $out.
xml_find ($tree)
Definition at line 195 of file utils.php.
References $i, and $out.
xml_join_atts ($atts)
Definition at line 223 of file utils.php.
xml_to_array ($in)
Definition at line 190 of file utils.php.