GravityView: vars.php File Reference
vars.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
wp_is_mobile ()
Test if the current browser runs on a mobile device (smart phone, tablet, etc.)
Variables
global $is_apache = (strpos($_SERVER['SERVER_SOFTWARE'], 'Apache') !== false || strpos($_SERVER['SERVER_SOFTWARE'], 'LiteSpeed') !== false)
Whether the server software is Apache or something else bool $is_apache.
global $is_chrome
global $is_edge
global $is_gecko
global $is_IE = ($is_macIE || $is_winIE)
global $is_IIS = !$is_apache && (strpos($_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS') !== false || strpos($_SERVER['SERVER_SOFTWARE'], 'ExpressionDevServer') !== false)
Whether the server software is IIS or something else bool $is_IIS.
global $is_iis7 = $is_IIS && intval(substr($_SERVER['SERVER_SOFTWARE'], strpos($_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS/') + 14)) >= 7
Whether the server software is IIS 7.X or greater bool $is_iis7.
global $is_iphone
global $is_lynx = $is_gecko = $is_winIE = $is_macIE = $is_opera = $is_NS4 = $is_safari = $is_chrome = $is_iphone = $is_edge = false
global $is_macIE
global $is_nginx = (strpos($_SERVER['SERVER_SOFTWARE'], 'nginx') !== false)
Whether the server software is Nginx or something else bool $is_nginx.
global $is_NS4
global $is_opera
global $is_safari
global $is_winIE
global $pagenow = 'index.php'
if(is_admin()) else
Function Documentation
wp_is_mobile ()
Test if the current browser runs on a mobile device (smart phone, tablet, etc.)
bool $is_mobile
Returns
bool
Definition at line 127 of file vars.php.
References $_SERVER, elseif, and null.
Referenced by _device_can_upload(), _ipad_meta(), WP_Admin_Bar\_render(), _wp_customize_loader_settings(), WP_Customize_Manager\customize_pane_settings(), _WP_Editors\editor_settings(), GFForms\enqueue_admin_scripts(), GravityView_Admin_Views\enqueue_gravity_forms_scripts(), WP_Customize_Manager\is_ios(), login_header(), media_upload_form(), GFSelectColumns\select_columns_page(), user_can_richedit(), wp_plupload_default_settings(), and wp_shake_js().
Variable Documentation
$is_apache = (strpos($_SERVER['SERVER_SOFTWARE'], 'Apache') !== false || strpos($_SERVER['SERVER_SOFTWARE'], 'LiteSpeed') !== false)
Whether the server software is Apache or something else bool $is_apache.
Definition at line 18 of file vars.php.
Referenced by apache_mod_loaded(), and network_step1().
global $is_chrome
Definition at line 18 of file vars.php.
Referenced by post_form_autocomplete_off(), and user_can_richedit().
global $is_edge
Definition at line 18 of file vars.php.
Referenced by user_can_richedit().
global $is_gecko
Definition at line 18 of file vars.php.
Referenced by user_can_richedit().
$is_IE = ($is_macIE || $is_winIE)
Definition at line 18 of file vars.php.
Referenced by WP_Admin_Bar\_render(), _wp_admin_html_begin(), get_shortcut_link(), media_upload_form(), user_can_richedit(), and wp_print_media_templates().
$is_IIS = !$is_apache && (strpos($_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS') !== false || strpos($_SERVER['SERVER_SOFTWARE'], 'ExpressionDevServer') !== false)
Whether the server software is IIS or something else bool $is_IIS.
Definition at line 18 of file vars.php.
Referenced by redirect_canonical().
$is_iis7 = $is_IIS && intval(substr($_SERVER['SERVER_SOFTWARE'], strpos($_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS/') + 14)) >= 7
Whether the server software is IIS 7.X or greater bool $is_iis7.
Definition at line 18 of file vars.php.
Referenced by iis7_supports_permalinks().
global $is_iphone
Definition at line 18 of file vars.php.
$is_lynx = $is_gecko = $is_winIE = $is_macIE = $is_opera = $is_NS4 = $is_safari = $is_chrome = $is_iphone = $is_edge = false
Definition at line 18 of file vars.php.
global $is_macIE
Definition at line 18 of file vars.php.
Referenced by funky_javascript_fix().
$is_nginx = (strpos($_SERVER['SERVER_SOFTWARE'], 'nginx') !== false)
Whether the server software is Nginx or something else bool $is_nginx.
Definition at line 18 of file vars.php.
global $is_NS4
Definition at line 18 of file vars.php.
global $is_opera
Definition at line 18 of file vars.php.
Referenced by media_upload_form(), and user_can_richedit().
global $is_safari
Definition at line 18 of file vars.php.
Referenced by post_form_autocomplete_off(), and user_can_richedit().
global $is_winIE
Definition at line 18 of file vars.php.
Referenced by funky_javascript_fix().
else $pagenow = 'index.php'
Definition at line 18 of file vars.php.
if (is_admin()) else
Initial value:
{
    if ( preg_match('#([^/]+\.php)([?/].*?)?$#i', $_SERVER['PHP_SELF'], $self_matches) )
        $pagenow = strtolower($self_matches[1])
Definition at line 42 of file vars.php.