GravityView: update.php File Reference
wordpress/wp-includes/update.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_maybe_update_core ()
Determines whether core should be updated.
_maybe_update_plugins ()
Check the last time plugins were run before checking plugin versions.
_maybe_update_themes ()
Check themes versions only after a duration of time.
wp_clean_update_cache ()
Clear existing update caches for plugins, themes, and core.
wp_get_translation_updates ()
Retrieves a list of all language updates available.
wp_get_update_data ()
Collect counts and UI strings for available updates.
wp_maybe_auto_update ()
Performs WordPress automatic background updates.
wp_schedule_update_checks ()
Schedule core, theme, and plugin update checks.
wp_update_plugins ($extra_stats=array())
Check plugin versions against the latest versions hosted on WordPress.org.
wp_update_themes ($extra_stats=array())
Check theme versions against the latest versions hosted on WordPress.org.
wp_version_check ($extra_stats=array(), $force_check=false)
Check WordPress version against the newest version.
Function Documentation
_maybe_update_core ()
Determines whether core should be updated.
Since
2.8.0
string $wp_version
Definition at line 596 of file wordpress/wp-includes/update.php.
References $wp_version, ABSPATH, get_site_transient(), wp_version_check(), and WPINC.
_maybe_update_plugins ()
Check the last time plugins were run before checking plugin versions.
This might have been backported to WordPress 2.6.1 for performance reasons. This is used for the wp-admin to check only so often instead of every page load.
Since
2.7.0 private
Definition at line 619 of file wordpress/wp-includes/update.php.
References get_site_transient(), and wp_update_plugins().
_maybe_update_themes ()
Check themes versions only after a duration of time.
This is for performance reasons to make sure that on the theme version checker is not run on every page load.
Since
2.7.0 private
Definition at line 635 of file wordpress/wp-includes/update.php.
References get_site_transient(), and wp_update_themes().
wp_clean_update_cache ()
Clear existing update caches for plugins, themes, and core.
Since
4.1.0
Definition at line 663 of file wordpress/wp-includes/update.php.
References delete_site_transient(), wp_clean_plugins_cache(), and wp_clean_themes_cache().
Referenced by Language_Pack_Upgrader\bulk_upgrade(), and WP_Automatic_Updater\run().
wp_get_translation_updates ()
Retrieves a list of all language updates available.
Since
3.7.0
Returns
array
Definition at line 513 of file wordpress/wp-includes/update.php.
References get_site_transient(), and object.
Referenced by Language_Pack_Upgrader\async_upgrade(), Language_Pack_Upgrader\bulk_upgrade(), list_translation_updates(), WP_Automatic_Updater\run(), and wp_get_update_data().
wp_get_update_data ()
Collect counts and UI strings for available updates.
Since
3.3.0
Returns
array
Filter the returned array of update data for plugins, themes, and WordPress core.
Since
3.5.0
Parameters
array $update_data { Fetched update data.
array $counts An array of counts for available plugin, theme, and WordPress updates. string $update_title Titles of available updates. }
Parameters
array $titles An array of update counts and UI strings for available updates.
Definition at line 535 of file wordpress/wp-includes/update.php.
References $plugins, $update_data, $update_title, __, _n(), apply_filters(), current_user_can(), esc_attr(), get_core_updates(), get_site_transient(), and wp_get_translation_updates().
Referenced by wp_admin_bar_updates_menu().
wp_maybe_auto_update ()
Performs WordPress automatic background updates.
Since
3.7.0
Definition at line 498 of file wordpress/wp-includes/update.php.
References ABSPATH, and WP_Automatic_Updater\run().
wp_schedule_update_checks ()
Schedule core, theme, and plugin update checks.
Since
3.1.0
Definition at line 647 of file wordpress/wp-includes/update.php.
References wp_installing(), wp_next_scheduled(), and wp_schedule_event().
wp_update_plugins ($extra_stats = array())
Check plugin versions against the latest versions hosted on WordPress.org.
The WordPress version, PHP version, and Locale is sent along with a list of all plugins installed. Checks against the WordPress server at api.wordpress.org. Will only check if WordPress isn't installing.
Since
2.3.0 string $wp_version Used to notify the WordPress version.
Parameters
array $extra_stats Extra statistics to report to the WordPress.org API.
Filter the locales requested for plugin translations.
Since
3.7.0
Parameters
array $locales Plugin locale. Default is current locale of the site.
Definition at line 190 of file wordpress/wp-includes/update.php.
References $file, $options, $plugin, $plugins, $translations, $url, $wp_version, __, ABSPATH, apply_filters(), current_filter(), DOING_CRON, foreach, get_bloginfo(), get_locale(), get_option(), get_plugins(), get_site_transient(), is_wp_error(), object, set_site_transient(), set_url_scheme(), WP_DEBUG, wp_get_installed_translations(), wp_http_supports(), wp_installing(), wp_json_encode(), wp_remote_post(), wp_remote_retrieve_body(), wp_remote_retrieve_response_code(), and WPINC.
Referenced by _maybe_update_plugins(), install_plugin_install_status(), WP_Automatic_Updater\run(), and wp_ajax_update_plugin().
wp_update_themes ($extra_stats = array())
Check theme versions against the latest versions hosted on WordPress.org.
A list of all themes installed in sent to WP. Checks against the WordPress server at api.wordpress.org. Will only check if WordPress isn't installing.
Since
2.7.0
Parameters
array $extra_stats Extra statistics to report to the WordPress.org API.
Filter the locales requested for theme translations.
Since
3.7.0
Parameters
array $locales Theme locale. Default is current locale of the site.
Definition at line 351 of file wordpress/wp-includes/update.php.
References $installed_themes, $options, $theme, $translations, $url, $wp_version, __, ABSPATH, apply_filters(), current_filter(), DOING_CRON, get_bloginfo(), get_locale(), get_option(), get_site_transient(), is_wp_error(), set_site_transient(), set_url_scheme(), WP_DEBUG, wp_get_installed_translations(), wp_get_themes(), wp_http_supports(), wp_installing(), wp_json_encode(), wp_remote_post(), wp_remote_retrieve_body(), wp_remote_retrieve_response_code(), and WPINC.
Referenced by _maybe_update_themes(), and WP_Automatic_Updater\run().
wp_version_check ($extra_stats = array(), $force_check = false)
Check WordPress version against the newest version.
The WordPress version, PHP version, and Locale is sent. Checks against the WordPress server at api.wordpress.org server. Will only check if WordPress isn't installing.
Since
2.3.0 string $wp_version Used to check against the newest WordPress version. wpdb $wpdb string $wp_local_package
Parameters
array $extra_stats Extra statistics to report to the WordPress.org API.
bool $force_check Whether to bypass the transient cache and force a fresh update check. Defaults to false, true if $extra_stats is set.
Filter the locale requested for WordPress core translations.
Since
2.8.0
Parameters
string $locale Current locale.
Definition at line 24 of file wordpress/wp-includes/update.php.
References $locale, $mysql_version, $options, $php_version, $translations, $url, $value, $wp_version, $wpdb, __, ABSPATH, apply_filters(), count_users(), do_action(), doing_action(), DOING_CRON, elseif, esc_html, esc_url, get_blog_count(), get_locale(), get_site_option(), get_site_transient(), get_user_count(), home_url(), is_multisite(), is_wp_error(), network_site_url(), null, object, set_site_transient(), set_url_scheme(), WP_DEBUG, wp_get_installed_translations(), wp_http_supports(), wp_installing(), wp_json_encode(), wp_next_scheduled(), wp_remote_post(), wp_remote_retrieve_body(), wp_remote_retrieve_response_code(), wp_schedule_single_event(), and WPINC.
Referenced by _maybe_update_core(), WP_Automatic_Updater\run(), and Core_Upgrader\upgrade().