GravityView: functions.php File Reference
wordpress/wp-content/themes/twentyfifteen/functions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyfifteen_javascript_detection ()
JavaScript Detection.
twentyfifteen_nav_description ($item_output, $item, $depth, $args)
Display descriptions in main navigation.
twentyfifteen_post_nav_background ()
Add featured image as background image to post navigation elements.
twentyfifteen_scripts ()
Enqueue scripts and styles.
twentyfifteen_search_form_modify ($html)
Add a screen-reader-text class to the search form's submit button.
twentyfifteen_widgets_init ()
Register widget area.
Variables
if(!isset($content_width)) if(version_compare($GLOBALS['wp_version'], '4.1-alpha', '<')) if(!function_exists('twentyfifteen_setup'))() endif
Set the content width based on the theme's design and stylesheet.
Function Documentation
twentyfifteen_javascript_detection ()
JavaScript Detection.
Adds a js class to the root <html> element when JavaScript is detected.
Since
Twenty Fifteen 1.1
Definition at line 215 of file wordpress/wp-content/themes/twentyfifteen/functions.php.
twentyfifteen_nav_description ($item_output, $item, $depth, $args)
Display descriptions in main navigation.
Since
Twenty Fifteen 1.0
Parameters
string $item_output The menu item output.
WP_Post $item Menu item object.
int $depth Depth of the menu.
array $args wp_nav_menu() arguments.
Returns
string Menu item with possible description.
Definition at line 314 of file wordpress/wp-content/themes/twentyfifteen/functions.php.
References str_replace.
twentyfifteen_post_nav_background ()
Add featured image as background image to post navigation elements.
Since
Twenty Fifteen 1.0
See also
wp_add_inline_style()
Definition at line 268 of file wordpress/wp-content/themes/twentyfifteen/functions.php.
References esc_url, get_adjacent_post(), get_post(), get_post_thumbnail_id(), has_post_thumbnail(), is_attachment(), is_single(), wp_add_inline_style(), and wp_get_attachment_image_src().
twentyfifteen_scripts ()
Enqueue scripts and styles.
Since
Twenty Fifteen 1.0
Definition at line 225 of file wordpress/wp-content/themes/twentyfifteen/functions.php.
References __, comments_open(), get_option(), get_stylesheet_uri(), get_template_directory_uri(), is_singular(), null, wp_attachment_is_image(), wp_enqueue_script(), wp_enqueue_style(), wp_localize_script(), and wp_style_add_data().
twentyfifteen_search_form_modify ($html)
Add a screen-reader-text class to the search form's submit button.
Since
Twenty Fifteen 1.0
Parameters
string $html Search form HTML.
Returns
string Modified search form HTML.
Definition at line 331 of file wordpress/wp-content/themes/twentyfifteen/functions.php.
References str_replace.
twentyfifteen_widgets_init ()
Register widget area.
Since
Twenty Fifteen 1.0
https://codex.wordpress.org/Function_Reference/register_sidebar
Definition at line 131 of file wordpress/wp-content/themes/twentyfifteen/functions.php.
References __, and register_sidebar().
Variable Documentation
if (! function_exists('twentyfifteen_fonts_url')) () endif
Set the content width based on the theme's design and stylesheet.
Since
Twenty Fifteen 1.0 Twenty Fifteen only works in WordPress 4.1 or later.
Definition at line 44 of file wordpress/wp-content/themes/twentyfifteen/functions.php.