GravityView: export.php File Reference
wordpress/wp-admin/includes/export.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
export_wp ($args=array())
Generates the WXR export file for download.
Variables
const WXR_VERSION '1.2'
Version number for the export format.
Function Documentation
export_wp ($args = array())
Generates the WXR export file for download.
Since
2.1.0
wpdb $wpdb WP_Post $post
Parameters
array $args Filters defining what should be included in the export.
Fires at the beginning of an export, before any headers are sent.
Since
2.3.0
Parameters
array $args An array of export arguments.
Filter the export filename.
Since
4.4.0
Parameters
string $wp_filename The name of the file for download.
string $sitename The site name.
string $date Today's date, formatted.
Wrap given string in XML CDATA tag.
Since
2.1.0
Parameters
string $str String to wrap in XML CDATA tag.
Returns
string
Return the URL of the site
Since
2.5.0
Returns
string Site URL.
Output a cat_name XML tag from a given category object
Since
2.1.0
Parameters
object $category Category Object
Output a category_description XML tag from a given category object
Since
2.1.0
Parameters
object $category Category Object
Output a tag_name XML tag from a given tag object
Since
2.3.0
Parameters
object $tag Tag Object
Output a tag_description XML tag from a given tag object
Since
2.3.0
Parameters
object $tag Tag Object
Output a term_name XML tag from a given term object
Since
2.9.0
Parameters
object $term Term Object
Output a term_description XML tag from a given term object
Since
2.9.0
Parameters
object $term Term Object
Output list of authors with posts
Since
3.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $post_ids Array of post IDs to filter the query by. Optional.
Ouput all navigation menu terms
Since
3.1.0
Output list of taxonomy terms, in XML tag format, associated with a post
Since
2.3.0
Parameters
bool $return_me
string $meta_key
Returns
bool
Definition at line 28 of file wordpress/wp-admin/includes/export.php.
References $authors, $cats, $menu, $nav_menus, $post, $tags, $wpdb, add_filter(), apply_filters(), date, do_action(), elseif, generated, get_bloginfo(), get_bloginfo_rss(), get_categories(), get_comment(), get_object_taxonomies(), get_option(), get_post(), get_post_type_object(), get_post_types(), get_tags(), get_taxonomies(), get_term(), get_terms(), H, is_multisite(), name, network_home_url(), null, post_type_exists(), RSS, sanitize_key(), seems_utf8(), site, spam, str_replace, term_exists(), the_title_rss(), wp_get_nav_menus(), wp_get_object_terms(), and wp_parse_args().
Variable Documentation
const WXR_VERSION '1.2'
Version number for the export format.
Bump this when something changes that might affect compatibility.
Since
2.5.0
Definition at line 16 of file wordpress/wp-admin/includes/export.php.