GravityView: functions.php File Reference
wordpress-tests-lib/includes/functions.php File Reference
Data Structures
class Basic_Object
class Basic_Subclass
Functions
_delete_all_posts ()
_disable_wp_die ()
_enable_wp_die ()
_set_default_permalink_structure_for_tests ()
Set a permalink structure.
_test_filter_build_unique_id ($tag, $function, $priority)
_wp_die_handler ($message, $title= '', $args=array())
_wp_die_handler_filter ()
_wp_die_handler_txt ($message, $title, $args)
tests_add_filter ($tag, $function_to_add, $priority=10, $accepted_args=1)
Function Documentation
_delete_all_posts ()
Definition at line 35 of file wordpress-tests-lib/includes/functions.php.
References $id, $wpdb, and wp_delete_post().
_disable_wp_die ()
Definition at line 83 of file wordpress-tests-lib/includes/functions.php.
References $GLOBALS.
_enable_wp_die ()
Definition at line 87 of file wordpress-tests-lib/includes/functions.php.
References $GLOBALS.
_set_default_permalink_structure_for_tests ()
Set a permalink structure.
Hooked as a callback to the 'populate_options' action, we use this function to set a permalink structure during wp_install(), so that WP doesn't attempt to do a time-consuming remote request.
Since
4.2.0
Definition at line 115 of file wordpress-tests-lib/includes/functions.php.
References update_option().
_test_filter_build_unique_id ($tag, $function, $priority)
Definition at line 13 of file wordpress-tests-lib/includes/functions.php.
References $wp_filter.
Referenced by tests_add_filter().
_wp_die_handler ($message, $title = '', $args = array())
Definition at line 75 of file wordpress-tests-lib/includes/functions.php.
References $GLOBALS, $message, $title, and _wp_die_handler_txt().
_wp_die_handler_filter ()
Definition at line 91 of file wordpress-tests-lib/includes/functions.php.
_wp_die_handler_txt ($message, $title, $args)
Definition at line 95 of file wordpress-tests-lib/includes/functions.php.
Referenced by _wp_die_handler().
tests_add_filter ($tag, $function_to_add, $priority = 10, $accepted_args = 1)
Definition at line 4 of file wordpress-tests-lib/includes/functions.php.
References $merged_filters, $wp_filter, and _test_filter_build_unique_id().
Referenced by GV_Unit_Tests_Bootstrap\__construct().