GravityView: functions.php File Reference
wordpress/wp-content/themes/twentyfourteen/functions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyfourteen_admin_fonts ()
Enqueue Google fonts style to admin screen for custom header display.
twentyfourteen_body_classes ($classes)
Extend the default WordPress body classes.
twentyfourteen_content_width ()
Adjust content_width value for image attachment template.
twentyfourteen_font_url ()
Register Lato Google font for Twenty Fourteen.
twentyfourteen_get_featured_posts ()
Getter function for Featured Content Plugin.
twentyfourteen_has_featured_posts ()
A helper conditional function that returns a boolean value.
twentyfourteen_post_classes ($classes)
Extend the default WordPress post classes.
twentyfourteen_scripts ()
Enqueue scripts and styles for the front end.
twentyfourteen_widgets_init ()
Register three Twenty Fourteen widget areas.
twentyfourteen_wp_title ($title, $sep)
Create a nicely formatted and more specific title element text for output in head of document, based on current view.
Variables
if(!isset($content_width)) if(version_compare($GLOBALS['wp_version'], '3.6', '<')) if(!function_exists('twentyfourteen_setup'))() endif
Set up the content width value based on the theme's design.
Function Documentation
twentyfourteen_admin_fonts ()
Enqueue Google fonts style to admin screen for custom header display.
Since
Twenty Fourteen 1.0
Filter the default Twenty Fourteen attachment size.
Since
Twenty Fourteen 1.0
Parameters
array $dimensions { An array of height and width dimensions.
int $height Height of the image in pixels. Default 810. int $width Width of the image in pixels. Default 810. }
Definition at line 272 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References null, twentyfourteen_font_url(), and wp_enqueue_style().
twentyfourteen_body_classes ($classes)
Extend the default WordPress body classes.
Adds body classes to denote:
Single or multiple authors.
Presence of header image except in Multisite signup and activate pages.
Index views.
Full-width content layout.
Presence of footer widgets.
Single views.
Featured content layout.
Since
Twenty Fourteen 1.0
Parameters
array $classes A list of existing body class values.
Returns
array The filtered body class list.
Definition at line 404 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References $GLOBALS, elseif, get_header_image(), get_theme_mod(), is_active_sidebar(), is_archive(), is_attachment(), is_front_page(), is_home(), is_multi_author(), is_page_template(), is_search(), and is_singular().
twentyfourteen_content_width ()
Adjust content_width value for image attachment template.
Since
Twenty Fourteen 1.0
Definition at line 125 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References $GLOBALS, is_attachment(), and wp_attachment_is_image().
twentyfourteen_font_url ()
Register Lato Google font for Twenty Fourteen.
Since
Twenty Fourteen 1.0
Returns
string
Definition at line 207 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References _x, and add_query_arg().
Referenced by twentyfourteen_admin_fonts(), and twentyfourteen_scripts().
twentyfourteen_get_featured_posts ()
Getter function for Featured Content Plugin.
Since
Twenty Fourteen 1.0
Returns
array An array of WP_Post objects.
Filter the featured posts to return in Twenty Fourteen.
Since
Twenty Fourteen 1.0
Parameters
array | bool $posts Array of featured posts, otherwise false.
Definition at line 139 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References apply_filters().
Referenced by twentyfourteen_has_featured_posts().
twentyfourteen_has_featured_posts ()
A helper conditional function that returns a boolean value.
Since
Twenty Fourteen 1.0
Returns
bool Whether there are featured posts.
Definition at line 157 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References is_paged(), and twentyfourteen_get_featured_posts().
twentyfourteen_post_classes ($classes)
Extend the default WordPress post classes.
Adds a post class to denote: Non-password protected page with a post thumbnail.
Since
Twenty Fourteen 1.0
Parameters
array $classes A list of existing post class values.
Returns
array The filtered post class list.
Definition at line 455 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References has_post_thumbnail(), is_attachment(), and post_password_required().
twentyfourteen_scripts ()
Enqueue scripts and styles for the front end.
Since
Twenty Fourteen 1.0
Definition at line 229 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References __, comments_open(), get_option(), get_stylesheet_uri(), get_template_directory_uri(), get_theme_mod(), is_active_sidebar(), is_front_page(), is_singular(), null, twentyfourteen_font_url(), wp_attachment_is_image(), wp_enqueue_script(), wp_enqueue_style(), wp_localize_script(), and wp_style_add_data().
twentyfourteen_widgets_init ()
Register three Twenty Fourteen widget areas.
Since
Twenty Fourteen 1.0
Definition at line 166 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References __, get_template_directory(), register_sidebar(), and register_widget().
twentyfourteen_wp_title ($title, $sep)
Create a nicely formatted and more specific title element text for output in head of document, based on current view.
Since
Twenty Fourteen 1.0
int $paged WordPress archive pagination page count. int $page WordPress paginated post page count.
Parameters
string $title Default title text for current view.
string $sep Optional separator.
Returns
string The filtered title.
Definition at line 477 of file wordpress/wp-content/themes/twentyfourteen/functions.php.
References $page, $paged, $site_description, $title, __, get_bloginfo(), is_404, is_feed(), is_front_page(), and is_home().
Variable Documentation
if (! function_exists('twentyfourteen_list_authors')) () endif
Set up the content width value based on the theme's design.
See also
twentyfourteen_content_width()
Since
Twenty Fourteen 1.0 Twenty Fourteen only works in WordPress 3.6 or later.
Definition at line 46 of file wordpress/wp-content/themes/twentyfourteen/functions.php.