GravityView: functions.php File Reference
wordpress/wp-includes/functions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
__return_empty_array ()
Returns an empty array.
__return_empty_string ()
Returns an empty string.
__return_false ()
Returns false.
__return_null ()
Returns null.
__return_true ()
Returns true.
__return_zero ()
Returns 0.
_ajax_wp_die_handler ($message= '')
Kill WordPress ajax execution.
_canonical_charset ($charset)
Retrieve a canonical form of the provided charset appropriate for passing to PHP functions such as htmlspecialchars() and charset html attributes.
_cleanup_header_comment ($str)
Strip close comment and close php tags from file headers used by WP.
_config_wp_home ($url= '')
Retrieve the WordPress home page URL.
_config_wp_siteurl ($url= '')
Retrieve the WordPress site URL.
_default_wp_die_handler ($message, $title= '', $args=array())
Kill WordPress execution and display HTML message with error message.
_deprecated_argument ($function, $version, $message=null)
Mark a function argument as deprecated and inform when it has been used.
_deprecated_constructor ($class, $version)
Marks a constructor as deprecated and informs when it has been used.
_deprecated_file ($file, $version, $replacement=null, $message= '')
Mark a file as deprecated and inform when it has been used.
_deprecated_function ($function, $version, $replacement=null)
Mark a function as deprecated and inform when it has been used.
_device_can_upload ()
Test if the current device has the capability to upload files.
_doing_it_wrong ($function, $message, $version)
Mark something as being incorrectly called.
_get_non_cached_ids ($object_ids, $cache_key)
Retrieve ids that are not already present in the cache.
_http_build_query ($data, $prefix=null, $sep=null, $key= '', $urlencode=true)
From php.net (modified by Mark Jaquith to behave like the native PHP5 function).
_mce_set_direction ($input)
Set the localized direction for MCE plugin.
_scalar_wp_die_handler ($message= '')
Kill WordPress execution.
_wp_json_convert_string ($string)
Convert a string to UTF-8, so that it can be safely encoded to JSON.
_wp_json_prepare_data ($data)
Prepares response data to be serialized to JSON.
_wp_json_sanity_check ($data, $depth)
Perform sanity checks on data that shall be encoded to JSON.
_wp_mysql_week ($column)
Return a MySQL expression for selecting the week number based on the start_of_week option.
_wp_timezone_choice_usort_callback ($a, $b)
Sort-helper for timezones.
_xmlrpc_wp_die_handler ($message, $title= '', $args=array())
Kill WordPress execution and display XML message with error message.
absint ($maybeint)
Convert a value to non-negative integer.
add_magic_quotes ($array)
Walks the array while sanitizing the contents.
add_query_arg ()
Retrieves a modified URL query string.
apache_mod_loaded ($mod, $default=false)
Does the specified module exist in the Apache config?
bool_from_yn ($yn)
Whether input is yes or no.
build_query ($data)
Build URL query based on an associative and, or indexed array.
cache_javascript_headers ()
Set the headers for caching for 10 days with JavaScript content type.
current_time ($type, $gmt=0)
Retrieve the current time based on specified type.
date_i18n ($dateformatstring, $unixtimestamp=false, $gmt=false)
Retrieve the date in localized format, based on timestamp.
dead_db ()
Load custom DB error or display WordPress DB error.
do_enclose ($content, $post_ID)
Check content for video and audio links to add as enclosures.
do_feed ()
Load the feed template from the use of an action hook.
do_feed_atom ($for_comments)
Load either Atom comment feed or Atom posts feed.
do_feed_rdf ()
Load the RDF RSS 0.91 Feed template.
do_feed_rss ()
Load the RSS 1.0 Feed Template.
do_feed_rss2 ($for_comments)
Load either the RSS2 comment feed or the RSS2 posts feed.
do_robots ()
Display the robots.txt file content.
force_ssl_admin ($force=null)
Whether to force SSL used for the Administration Screens.
get_allowed_mime_types ($user=null)
Retrieve list of allowed mime types and file extensions.
get_file_data ($file, $default_headers, $context= '')
Retrieve metadata from a file.
get_main_network_id ()
Get the main network ID.
get_num_queries ()
Retrieve the number of database queries during the WordPress execution.
get_status_header_desc ($code)
Retrieve the description for the HTTP status.
get_tag_regex ($tag)
Return RegEx body to liberally match an opening HTML tag.
get_temp_dir ()
Determine a writable directory for temporary files.
get_weekstartend ($mysqlstring, $start_of_week= '')
Get the week start and end from the datetime or date string from MySQL.
global_terms_enabled ()
Determine whether global terms are enabled.
iis7_supports_permalinks ()
Check if IIS 7+ supports pretty permalinks.
is_blog_installed ()
Test whether blog is already installed.
is_lighttpd_before_150 ()
Is the server running earlier than 1.5.0 version of lighttpd?
is_main_network ($network_id=null)
Determine whether a network is the main network of the Multisite install.
is_main_site ($site_id=null)
Determine whether a site is the main site of the current network.
is_new_day ()
Whether the publish date of the current post in the loop is different from the publish date of the previous post in the loop.
is_serialized ($data, $strict=true)
Check value to find if it was serialized.
is_serialized_string ($data)
Check whether serialized data is of string type.
is_ssl ()
Determine if SSL is used.
maybe_serialize ($data)
Serialize data, if needed.
maybe_unserialize ($original)
Unserialize value only if it was serialized.
mbstring_binary_safe_encoding ($reset=false)
Set the mbstring internal encoding to a binary safe encoding when func_overload is enabled.
mysql2date ($format, $date, $translate=true)
Convert given date string into a different format.
mysql_to_rfc3339 ($date_string)
Parses and formats a MySQL datetime (Y-m-d H:i:s) for ISO8601/RFC3339.
nocache_headers ()
Set the headers to prevent caching for the different browsers.
number_format_i18n ($number, $decimals=0)
Convert integer number to format based on the locale.
path_is_absolute ($path)
Test if a give filesystem path is absolute.
path_join ($base, $path)
Join two filesystem paths together.
remove_query_arg ($key, $query=false)
Removes an item or items from a query string.
reset_mbstring_encoding ()
Reset the mbstring internal encoding to a users previously set encoding.
send_frame_options_header ()
Send a HTTP header to limit rendering of pages to same origin iframes.
send_nosniff_header ()
Send a HTTP header to disable content type sniffing in browsers which support it.
size_format ($bytes, $decimals=0)
Convert number of bytes largest unit bytes will fit into.
smilies_init ()
Convert smiley code to the icon graphic file equivalent.
status_header ($code, $description= '')
Set HTTP status header.
validate_file ($file, $allowed_files= '')
File validates against allowed set of defined rules.
win_is_writable ($path)
Workaround for Windows bug in is_writable() function.
wp ($query_vars= '')
Set up the WordPress query.
wp_allowed_protocols ()
Retrieve a list of protocols to allow in HTML attributes.
wp_array_slice_assoc ($array, $keys)
Extract a slice of an array, given a list of keys.
wp_auth_check ($response)
Check whether a user is still logged in, for the heartbeat.
wp_auth_check_html ()
Output the HTML that shows the wp-login dialog when the user is no longer logged in.
wp_auth_check_load ()
Load the auth check for monitoring whether the user is still logged in.
wp_check_filetype ($filename, $mimes=null)
Retrieve the file type from the file name.
wp_check_filetype_and_ext ($file, $filename, $mimes=null)
Attempt to determine the real file type of a file.
wp_checkdate ($month, $day, $year, $source_date)
Test if the supplied date is valid for the Gregorian calendar.
wp_debug_backtrace_summary ($ignore_class=null, $skip_frames=0, $pretty=true)
Return a comma-separated string of functions that have been called to get to the current point in code.
wp_delete_file ($file)
Delete a file.
wp_die ($message= '', $title= '', $args=array())
Kill WordPress execution and display HTML message with error message.
wp_ext2type ($ext)
Retrieve the file type based on the extension name.
wp_extract_urls ($content)
Use RegEx to extract URLs from arbitrary content.
wp_filter_object_list ($list, $args=array(), $operator= 'and', $field=false)
Filters a list of objects, based on a set of key => value arguments.
wp_find_hierarchy_loop ($callback, $start, $start_parent, $callback_args=array())
Find hierarchy loops using a callback function that maps object IDs to parent IDs.
wp_find_hierarchy_loop_tortoise_hare ($callback, $start, $override=array(), $callback_args=array(), $_return_loop=false)
Use the "The Tortoise and the Hare" algorithm to detect loops.
wp_get_http_headers ($url, $deprecated=false)
Retrieve HTTP Headers from URL.
wp_get_mime_types ()
Retrieve list of mime types and file extensions.
wp_get_nocache_headers ()
Get the header information to prevent caching.
wp_get_original_referer ()
Retrieve original referer that was posted, if it exists.
wp_get_raw_referer ()
Retrieve unvalidated referer from '_wp_http_referer' or HTTP referer.
wp_get_referer ()
Retrieve referer from '_wp_http_referer' or HTTP referer.
wp_guess_url ()
Guess the URL for the site.
wp_is_numeric_array ($data)
Determines if the variable is a numeric-indexed array.
wp_is_stream ($path)
Test if a given path is a stream URL.
wp_is_writable ($path)
Determine if a directory is writable.
wp_json_encode ($data, $options=0, $depth=512)
Encode a variable into JSON, with some sanity checks.
wp_list_filter ($list, $args=array(), $operator= 'AND')
Filters a list of objects, based on a set of key => value arguments.
wp_list_pluck ($list, $field, $index_key=null)
Pluck a certain field out of each object in a list.
wp_maybe_decline_date ($date)
Determines if the date should be declined.
wp_maybe_load_widgets ()
Determines if Widgets library should be loaded.
wp_mkdir_p ($target)
Recursive directory creation based on full path.
wp_nonce_ays ($action)
Display "Are You Sure" message to confirm the action being taken.
wp_nonce_field ($action=-1, $name="_wpnonce", $referer=true, $echo=true)
Retrieve or display nonce hidden field for forms.
wp_nonce_url ($actionurl, $action=-1, $name= '_wpnonce')
Retrieve URL with nonce added to URL query.
wp_normalize_path ($path)
Normalize a filesystem path.
wp_ob_end_flush_all ()
Flush all output buffers for PHP 5.2.
wp_original_referer_field ($echo=true, $jump_back_to= 'current')
Retrieve or display original referer hidden field for forms.
wp_parse_args ($args, $defaults= '')
Merge user defined arguments into defaults array.
wp_parse_id_list ($list)
Clean up an array, comma- or space-separated list of IDs.
wp_post_preview_js ()
Outputs a small JS snippet on preview tabs/windows to remove window.name on unload.
wp_referer_field ($echo=true)
Retrieve or display referer hidden field for forms.
wp_remote_fopen ($uri)
HTTP request for URI to retrieve content.
wp_removable_query_args ()
Returns an array of single-use query variable names that can be removed from a URL.
wp_scheduled_delete ()
Permanently delete comments or posts of any type that have held a status of 'trash' for the number of days defined in EMPTY_TRASH_DAYS.
wp_send_json ($response)
Send a JSON response back to an Ajax request.
wp_send_json_error ($data=null)
Send a JSON response back to an Ajax request, indicating failure.
wp_send_json_success ($data=null)
Send a JSON response back to an Ajax request, indicating success.
wp_suspend_cache_addition ($suspend=null)
Temporarily suspend cache additions.
wp_suspend_cache_invalidation ($suspend=true)
Suspend cache invalidation.
wp_timezone_choice ($selected_zone)
Gives a nicely-formatted list of timezone strings.
wp_timezone_override_offset ()
gmt_offset modification for smart timezone handling.
wp_unique_filename ($dir, $filename, $unique_filename_callback=null)
Get a filename that is sanitized and unique for the given directory.
wp_upload_bits ($name, $deprecated, $bits, $time=null)
Create a file in the upload folder with given content.
wp_upload_dir ($time=null)
Get an array containing the current upload directory's path and url.
wp_validate_boolean ($var)
Filter/validate a variable as a boolean.
wp_widgets_add_menu ()
Append the Widgets menu to the themes main menu.
xmlrpc_getpostcategory ($content)
Retrieve the post category or categories from XMLRPC XML.
xmlrpc_getposttitle ($content)
Retrieve post title from XMLRPC XML.
xmlrpc_removepostdata ($content)
XMLRPC XML content without title and category elements.
Variables
height __pad10__
margin __pad11__
padding __pad12__
cursor __pad13__
padding __pad14__
button __pad15__
color __pad16__
button __pad17__
button __pad18__
transform __pad19__
margin __pad3__
a __pad4__
a __pad5__
outline __pad6__
border __pad7__
color __pad8__
display __pad9__
a
vertical align
webkit appearance
button
border color
text decoration
if('rtl'==$text_direction) endif
font family
line height
button button large
ul li
font Monaco
font monospace
webkit box box outline
webkit border radius
webkit box shadow
font size
webkit box sizing
white space
webkit box box webkit transform
Function Documentation
__return_empty_array ()
Returns an empty array.
Useful for returning an empty array to filters easily.
Since
3.0.0
Returns
array Empty array.
Definition at line 4576 of file wordpress/wp-includes/functions.php.
__return_empty_string ()
Returns an empty string.
Useful for returning an empty string to filters easily.
Since
3.7.0
See also
__return_null()
Returns
string Empty string.
Definition at line 4604 of file wordpress/wp-includes/functions.php.
__return_false ()
Returns false.
Useful for returning false to filters easily.
Since
3.0.0
See also
__return_true()
Returns
false False.
Definition at line 4550 of file wordpress/wp-includes/functions.php.
__return_null ()
Returns null.
Useful for returning null to filters easily.
Since
3.4.0
Returns
null Null value.
Definition at line 4589 of file wordpress/wp-includes/functions.php.
References null.
__return_true ()
Returns true.
Useful for returning true to filters easily.
Since
3.0.0
See also
__return_false()
Returns
true True.
Definition at line 4535 of file wordpress/wp-includes/functions.php.
__return_zero ()
Returns 0.
Useful for returning 0 to filters easily.
Since
3.0.0
Returns
int 0.
Definition at line 4563 of file wordpress/wp-includes/functions.php.
_ajax_wp_die_handler ($message = '')
Kill WordPress ajax execution.
This is the handler for wp_die when processing Ajax requests.
Since
3.4.0 private
Parameters
string $message Optional. Response to print. Default empty.
Definition at line 2751 of file wordpress/wp-includes/functions.php.
References $message.
_canonical_charset ($charset)
Retrieve a canonical form of the provided charset appropriate for passing to PHP functions such as htmlspecialchars() and charset html attributes.
Since
3.6.0 private
See also
https://core.trac.wordpress.org/ticket/23688
Parameters
string $charset A charset name.
Returns
string The canonical form of the charset.
Definition at line 5032 of file wordpress/wp-includes/functions.php.
References $charset.
_cleanup_header_comment ($str)
Strip close comment and close php tags from file headers used by WP.
Since
2.8.0 private
See also
https://core.trac.wordpress.org/ticket/8497
Parameters
string $str Header comment to clean up.
Returns
string
Definition at line 4410 of file wordpress/wp-includes/functions.php.
Referenced by get_file_data(), get_file_description(), and WP_Theme\get_page_templates().
_config_wp_home ($url = '')
Retrieve the WordPress home page URL.
If the constant named 'WP_HOME' exists, then it will be used and returned by the function. This can be used to counter the redirection on your local development environment.
Since
2.2.0 private
See also
WP_HOME
Parameters
string $url URL for the home location.
Returns
string Homepage location.
Definition at line 3047 of file wordpress/wp-includes/functions.php.
References $url, and untrailingslashit().
_config_wp_siteurl ($url = '')
Retrieve the WordPress site URL.
If the constant named 'WP_SITEURL' is defined, then the value in that constant will always be returned. This can be used for debugging a site on your localhost while not having to change the database to your URL.
Since
2.2.0 private
See also
WP_SITEURL
Parameters
string $url URL to set the WordPress site location.
Returns
string The WordPress Site URL.
Definition at line 3068 of file wordpress/wp-includes/functions.php.
References $url, and untrailingslashit().
_default_wp_die_handler ($message, $title = '', $args = array())
Kill WordPress execution and display HTML message with error message.
This is the default handler for wp_die if you want a custom one for your site then you can overload using the wp_die_handler filter in wp_die
Since
3.0.0 private
Parameters
string $message Error message.
string $title Optional. Error title. Default empty.
string | array $args Optional. Arguments to control behavior. Default empty array.
Definition at line 2531 of file wordpress/wp-includes/functions.php.
References $errors, $message, $title, __, color, did_action(), elseif, family, is_rtl(), is_wp_error(), language_attributes(), margin, name, nocache_headers(), page, serif, shadow, status_header(), width, and wp_parse_args().
_deprecated_argument ($function, $version, $message = null)
Mark a function argument as deprecated and inform when it has been used.
This function is to be used whenever a deprecated function argument is used. Before this function is called, the argument must be checked for whether it was used by comparing it to its default value or evaluating whether it is empty. For example:
if (! empty($deprecated)) {
    _deprecated_argument( __FUNCTION__, '3.0' );
}
There is a hook deprecated_argument_run that will be called that can be used to get the backtrace up to what file and function used the deprecated argument.
The current behavior is to trigger a user error if WP_DEBUG is true.
Since
3.0.0 private
Parameters
string $function The function that was called.
string $version The version of WordPress that deprecated the argument used.
string $message Optional. A message regarding the change. Default null.
Fires when a deprecated argument is called.
Since
3.0.0
Parameters
string $function The function that was called.
string $message A message regarding the change.
string $version The version of WordPress that deprecated the argument used.
Filter whether to trigger an error for deprecated arguments.
Since
3.0.0
Parameters
bool $trigger Whether to trigger the error for deprecated arguments. Default true.
Definition at line 3737 of file wordpress/wp-includes/functions.php.
References $message, __, apply_filters(), do_action(), and WP_DEBUG.
Referenced by WP_Admin_Bar\__get(), WP_User\__get(), WP_User\__isset(), WP_User\__set(), WP_User\__unset(), WP_Admin_Bar\add_node(), add_option(), add_settings_field(), add_settings_section(), comments_link(), comments_number(), convert_chars(), discover_pingback_server_uri(), get_adjacent_post(), get_blog_count(), get_bloginfo(), get_categories(), get_delete_post_link(), get_last_updated(), get_plugin_data(), WP_Query\get_posts(), get_the_author(), get_the_excerpt(), get_user_option(), get_wp_title_rss(), WP_User\has_cap(), image_edit_apply_changes(), is_email(), load_plugin_textdomain(), ms_subdomain_constants(), _WP_Editors\parse_settings(), register_setting(), safecss_filter_attr(), the_attachment_link(), the_author(), the_author_posts_link(), trackback_rdf(), trackback_url(), unregister_setting(), update_blog_option(), update_blog_status(), update_user_status(), wp_clear_scheduled_hook(), wp_dropdown_categories(), wp_get_http_headers(), wp_get_recent_posts(), wp_get_sidebars_widgets(), wp_list_post_revisions(), wp_save_image_file(), wp_stream_image(), wp_title_rss(), wp_upload_bits(), and xfn_check().
_deprecated_constructor ($class, $version)
Marks a constructor as deprecated and informs when it has been used.
Similar to _deprecated_function(), but with different strings. Used to remove PHP4 style constructors.
The current behavior is to trigger a user error if WP_DEBUG is true.
This function is to be used in every PHP4 style constructor method that is deprecated.
Since
4.3.0 private
Parameters
string $class The class containing the deprecated constructor.
string $version The version of WordPress that deprecated the function.
Fires when a deprecated constructor is called.
Since
4.3.0
Parameters
string $class The class containing the deprecated constructor.
string $version The version of WordPress that deprecated the function.
Filter whether to trigger an error for deprecated functions.
WP_DEBUG must be true in addition to the filter evaluating to true.
Since
4.3.0
Parameters
bool $trigger Whether to trigger the error for deprecated functions. Default true.
Definition at line 3624 of file wordpress/wp-includes/functions.php.
References $class, __, apply_filters(), do_action(), and WP_DEBUG.
Referenced by WP_Widget\WP_Widget(), and WP_Widget_Factory\WP_Widget_Factory().
_deprecated_file ($file, $version, $replacement = null, $message = '')
Mark a file as deprecated and inform when it has been used.
There is a hook deprecated_file_included that will be called that can be used to get the backtrace up to what file and function included the deprecated file.
The current behavior is to trigger a user error if WP_DEBUG is true.
This function is to be used in every file that is deprecated.
Since
2.5.0 private
Parameters
string $file The file that was included.
string $version The version of WordPress that deprecated the file.
string $replacement Optional. The file that should have been included based on ABSPATH. Default null.
string $message Optional. A message regarding the change. Default empty.
Fires when a deprecated file is called.
Since
2.5.0
Parameters
string $file The file that was called.
string $replacement The file that should have been included based on ABSPATH.
string $version The version of WordPress that deprecated the file.
string $message A message regarding the change.
Filter whether to trigger an error for deprecated files.
Since
2.5.0
Parameters
bool $trigger Whether to trigger the error for deprecated files. Default true.
Definition at line 3675 of file wordpress/wp-includes/functions.php.
References $file, $message, __, apply_filters(), do_action(), and WP_DEBUG.
Referenced by wp_get_active_and_valid_plugins().
_deprecated_function ($function, $version, $replacement = null)
Mark a function as deprecated and inform when it has been used.
There is a hook deprecated_function_run that will be called that can be used to get the backtrace up to what file and function called the deprecated function.
The current behavior is to trigger a user error if WP_DEBUG is true.
This function is to be used in every function that is deprecated.
Since
2.5.0 private
Parameters
string $function The function that was called.
string $version The version of WordPress that deprecated the function.
string $replacement Optional. The function that should have been called. Default null.
Fires when a deprecated function is called.
Since
2.5.0
Parameters
string $function The function that was called.
string $replacement The function that should have been called.
string $version The version of WordPress that deprecated the function.
Filter whether to trigger an error for deprecated functions.
Since
2.5.0
Parameters
bool $trigger Whether to trigger the error for deprecated functions. Default true.
Definition at line 3573 of file wordpress/wp-includes/functions.php.
References __, apply_filters(), do_action(), and WP_DEBUG.
Referenced by __ngettext(), __ngettext_noop(), _c(), _flip_image_resource(), _get_post_ancestors(), _insert_into_post_button(), _media_button(), _nc(), _preview_theme_stylesheet_filter(), _preview_theme_template_filter(), _relocate_children(), _rotate_image_resource(), _search_terms_tidy(), WP_Customize_Setting\_update_option(), WP_Customize_Setting\_update_theme_mod(), wpdb\_weak_escape(), activate_sitewide_plugin(), add_contextual_help(), add_custom_background(), add_custom_image_header(), GFFormsModel\add_default_properties(), add_object_page(), add_option_update_handler(), add_utility_page(), attribute_escape(), automatic_feed_links(), clean_page_cache(), clean_pre(), clean_url(), clear_global_post_cache(), codepress_footer_js(), codepress_get_lang(), comments_popup_script(), comments_rss(), comments_rss_link(), create_empty_blog(), create_user(), current_theme_info(), deactivate_sitewide_plugin(), debug_fclose(), debug_fopen(), debug_fwrite(), delete_usermeta(), GFForms\deprecate_add_on_methods(), display_theme(), documentation_link(), dropdown_categories(), dropdown_cats(), dropdown_link_categories(), _WP_Editors\editor(), wpdb\escape(), favorite_actions(), WP_Filesystem_Base\find_base_dir(), WP_Widget_Recent_Comments\flush_widget_cache(), force_ssl_login(), format_to_post(), funky_javascript_fix(), gd_edit_image_support(), generate_random_password(), get_admin_users_for_domain(), get_all_category_ids(), get_alloptions(), get_allowed_themes(), get_archives(), get_attachment_icon(), get_attachment_icon_src(), get_attachment_innerHTML(), get_author_link(), get_author_name(), get_author_rss_link(), get_author_user_ids(), get_autotoggle(), WP_Filesystem_Base\get_base_dir(), get_blog_list(), get_blogaddress_by_domain(), get_boundary_post_rel_link(), get_broken_themes(), get_category_children(), get_category_rss_link(), get_catname(), get_commentdata(), get_comments_popup_template(), get_current_site_name(), get_current_theme(), get_dashboard_blog(), get_default_page_to_edit(), get_editable_authors(), get_editable_user_ids(), GFFormsModel\get_fileupload_value(), GFFormsModel\get_forms_by_id(), get_index_rel_link(), get_link(), get_linkcatname(), get_linkobjects(), get_linkobjectsbyname(), get_linkrating(), get_links(), get_links_list(), get_links_withrating(), get_linksbyname(), get_linksbyname_withrating(), get_most_active_blogs(), get_others_drafts(), get_others_pending(), get_others_unpublished_posts(), get_parent_post_rel_link(), get_post_to_edit(), get_postdata(), get_profile(), get_real_file_to_edit(), get_settings(), get_site_allowed_themes(), get_the_attachment_link(), get_the_author_aim(), get_the_author_description(), get_the_author_email(), get_the_author_firstname(), get_the_author_icq(), get_the_author_ID(), get_the_author_lastname(), get_the_author_login(), get_the_author_msn(), get_the_author_nickname(), get_the_author_url(), get_the_author_yim(), get_theme(), get_theme_data(), get_themes(), get_udims(), get_user_details(), get_user_id_from_string(), get_user_metavalues(), get_usermeta(), get_usernumposts(), get_users_of_blog(), gzip_compression(), image_resize(), index_rel_link(), install_themes_feature_list(), is_blog_user(), is_comments_popup(), WP_Query\is_comments_popup(), is_main_blog(), is_plugin_page(), is_site_admin(), is_taxonomy(), is_term(), is_wpmu_sitewide_plugin(), js_escape(), like_escape(), link_pages(), links_popup_script(), list_authors(), list_cats(), logIO(), make_url_footnote(), GF_Field\maybe_fire_array_access_deprecation_notice(), media_upload_audio(), media_upload_file(), media_upload_image(), media_upload_video(), GFFormsModel\move_temp_file(), mu_options(), next_post(), parent_post_rel_link(), WP_Http\parse_url(), permalink_link(), permalink_single_rss(), popuplinks(), post_permalink(), WP_Customize_Widgets\prepreview_added_sidebars_widgets(), WP_Customize_Widgets\prepreview_added_widget_instance(), preview_theme(), preview_theme_ob_filter(), preview_theme_ob_filter_callback(), previous_post(), WP_Scripts\print_scripts_l10n(), WP_Admin_Bar\recursive_render(), register_sidebar_widget(), register_widget_control(), remove_custom_background(), remove_custom_image_header(), remove_option_update_handler(), WP_Customize_Widgets\remove_prepreview_filters(), GravityView_Admin_Views\render_field_option(), GravityView_Render_Settings\render_field_option(), GravityView_Admin_Views\render_label(), GravityView_Admin_Views\render_setting_row(), WP_Object_Cache\reset(), rich_edit_exists(), sanitize_url(), sanitize_user_object(), screen_layout(), screen_options(), GFFormDisplay\send_emails(), WP_Customize_Widgets\setup_widget_addition_previews(), start_post_rel_link(), start_wp(), sticky_class(), wpdb\supports_collation(), the_attachment_links(), the_author_aim(), the_author_description(), the_author_email(), the_author_firstname(), the_author_icq(), the_author_ID(), the_author_lastname(), the_author_login(), the_author_msn(), the_author_nickname(), the_author_url(), the_author_yim(), the_category_head(), the_category_ID(), the_content_rss(), the_editor(), tinymce_include(), translate_with_context(), type_url_form_audio(), type_url_form_file(), type_url_form_image(), type_url_form_video(), unregister_sidebar_widget(), unregister_widget_control(), update_category_cache(), GFFormsModel\update_lead(), update_page_cache(), update_usermeta(), GFFormsModel\upload_file(), url_is_accessable_via_ssl(), use_codepress(), user_can_create_draft(), user_can_create_post(), user_can_delete_post(), user_can_delete_post_comments(), user_can_edit_post(), user_can_edit_post_comments(), user_can_edit_post_date(), user_can_edit_user(), user_can_set_post_date(), user_pass_ok(), validate_email(), wp_admin_bar_dashboard_view_site_menu(), wp_cache_reset(), wp_convert_bytes_to_hr(), wp_create_thumbnail(), wp_dashboard_quick_press_output(), wp_dropdown_cats(), wp_explain_nonce(), _WP_Editors\wp_fullscreen_html(), wp_get_http(), wp_get_links(), wp_get_linksbyname(), wp_get_post_cats(), wp_get_single_post(), wp_htmledit_pre(), wp_list_cats(), wp_load_image(), wp_nav_menu_locations_meta_box(), wp_preload_dialogs(), wp_print_editor_js(), wp_quicktags(), wp_richedit_pre(), wp_set_post_cats(), wp_shrink_dimensions(), wp_specialchars(), wp_timezone_supported(), wp_tiny_mce(), wp_update_core(), wp_update_plugin(), wp_update_theme(), wpmu_admin_do_redirect(), wpmu_admin_redirect_add_updated_param(), wpmu_checkAvailableSpace(), wpmu_current_site(), wpmu_get_blog_allowedthemes(), and wpmu_menu().
_device_can_upload ()
Test if the current device has the capability to upload files.
Since
3.4.0 private
Returns
bool Whether the device is able to upload files.
Definition at line 4841 of file wordpress/wp-includes/functions.php.
References $_SERVER, and wp_is_mobile().
Referenced by media_upload_form(), wp_plupload_default_settings(), and wp_print_media_templates().
_doing_it_wrong ($function, $message, $version)
Mark something as being incorrectly called.
There is a hook doing_it_wrong_run that will be called that can be used to get the backtrace up to what file and function called the deprecated function.
The current behavior is to trigger a user error if WP_DEBUG is true.
Since
3.1.0 private
Parameters
string $function The function that was called.
string $message A message explaining what has been done incorrectly.
string $version The version of WordPress where the message was added.
Fires when the given function is being used incorrectly.
Since
3.1.0
Parameters
string $function The function that was called.
string $message A message explaining what has been done incorrectly.
string $version The version of WordPress where the message was added.
Filter whether to trigger an error for _doing_it_wrong() calls.
Since
3.1.0
Parameters
bool $trigger Whether to trigger the error for _doing_it_wrong() calls. Default true.
Definition at line 3788 of file wordpress/wp-includes/functions.php.
References $message, __, apply_filters(), do_action(), and WP_DEBUG.
Referenced by wpdb\_real_escape(), _wp_scripts_maybe_doing_it_wrong(), WP_Admin_Bar\add_node(), add_shortcode(), add_theme_support(), convert_to_screen(), do_shortcode_tag(), is_404(), is_archive(), is_attachment(), is_author(), is_category(), is_comment_feed(), is_date(), is_day(), is_embed(), is_feed(), is_front_page(), is_home(), is_main_query(), is_month(), is_page(), is_paged(), is_post_type_archive(), is_preview(), is_robots(), is_search(), is_single(), is_singular(), is_tag(), is_tax(), is_time(), is_trackback(), is_year(), map_meta_cap(), wpdb\prepare(), GFForms\process_exterior_pages(), register_post_type(), register_sidebar(), register_taxonomy(), register_uninstall_hook(), WP_Customize_Manager\remove_panel(), WP_Date_Query\validate_date_values(), wp_add_inline_style(), wp_deregister_script(), and wp_insert_post().
_get_non_cached_ids ($object_ids, $cache_key)
Retrieve ids that are not already present in the cache.
Since
3.4.0 private
Parameters
array $object_ids ID list.
string $cache_key The cache bucket to check against.
Returns
array List of ids not present in the cache.
Definition at line 4821 of file wordpress/wp-includes/functions.php.
References $id, and wp_cache_get().
Referenced by _prime_comment_caches(), and _prime_post_caches().
_http_build_query ($data, $prefix = null, $sep = null, $key = '', $urlencode = true)
From php.net (modified by Mark Jaquith to behave like the native PHP5 function).
Since
3.2.0 private
See also
http://us1.php.net/manual/en/function.http-build-query.php
Parameters
array | object $data An array or object of data. Converted to array.
string $prefix Optional. Numeric index. If set, start parameter numbering with it. Default null.
string $sep Optional. Argument separator; defaults to 'arg_separator.output'. Default null.
string $key Optional. Used to prefix key name. Default empty.
bool $urlencode Optional. Whether to use urlencode() in the result. Default true.
Returns
string The query string.
Definition at line 706 of file wordpress/wp-includes/functions.php.
References $prefix, elseif, and null.
Referenced by build_query().
_mce_set_direction ($input)
Set the localized direction for MCE plugin.
Will only set the direction to 'rtl', if the WordPress locale has the text direction set to 'rtl'.
Fills in the 'directionality' setting, enables the 'directionality' plugin, and adds the 'ltr' button to 'toolbar1', formerly 'theme_advanced_buttons1' array keys. These keys are then returned in the $input (TinyMCE settings) array.
Since
2.1.0 private
Parameters
array $input MCE settings array.
Returns
array Direction set for 'rtl', if needed by locale.
Definition at line 3091 of file wordpress/wp-includes/functions.php.
References is_rtl().
_scalar_wp_die_handler ($message = '')
Kill WordPress execution.
This is the handler for wp_die when processing APP requests.
Since
3.4.0 private
Parameters
string $message Optional. Response to print. Default empty.
Definition at line 2767 of file wordpress/wp-includes/functions.php.
References $message.
_wp_json_convert_string ($string)
Convert a string to UTF-8, so that it can be safely encoded to JSON.
Since
4.1.0 private
See also
_wp_json_sanity_check()
bool $use_mb
Parameters
string $string The string which is to be converted.
Returns
string The checked string.
Definition at line 2896 of file wordpress/wp-includes/functions.php.
References null, and wp_check_invalid_utf8().
Referenced by _wp_json_sanity_check().
_wp_json_prepare_data ($data)
Prepares response data to be serialized to JSON.
This supports the JsonSerializable interface for PHP 5.2-5.3 as well.
Since
4.4.0 private
Parameters
mixed $data Native representation.
Returns
bool|int|float|null|string|array Data ready for json_encode().
Definition at line 2926 of file wordpress/wp-includes/functions.php.
References null.
Referenced by wp_json_encode().
_wp_json_sanity_check ($data, $depth)
Perform sanity checks on data that shall be encoded to JSON.
Since
4.1.0 private
See also
wp_json_encode()
Parameters
mixed $data Variable (usually an array or object) to encode as JSON.
int $depth Maximum depth to walk through $data. Must be greater than 0.
Returns
mixed The sanitized data that shall be encoded to JSON.
Definition at line 2832 of file wordpress/wp-includes/functions.php.
References $id, $output, _wp_json_convert_string(), and elseif.
Referenced by wp_json_encode().
_wp_mysql_week ($column)
Return a MySQL expression for selecting the week number based on the start_of_week option.
Since
3.0.0
Parameters
string $column Database column.
Returns
string SQL clause.
Definition at line 4629 of file wordpress/wp-includes/functions.php.
References get_option().
Referenced by WP_Date_Query\get_sql_for_clause(), and wp_get_archives().
_wp_timezone_choice_usort_callback ($a, $b)
Sort-helper for timezones.
Since
2.9.0 private
Parameters
array $a
array $b
Returns
int
Definition at line 4230 of file wordpress/wp-includes/functions.php.
_xmlrpc_wp_die_handler ($message, $title = '', $args = array())
Kill WordPress execution and display XML message with error message.
This is the handler for wp_die when processing XMLRPC requests.
Since
3.2.0 private
wp_xmlrpc_server $wp_xmlrpc_server
Parameters
string $message Error message.
string $title Optional. Error title. Default empty.
string | array $args Optional. Arguments to control behavior. Default empty array.
Definition at line 2728 of file wordpress/wp-includes/functions.php.
References $message, $wp_xmlrpc_server, and wp_parse_args().
absint ($maybeint)
Convert a value to non-negative integer.
Since
2.5.0
Parameters
mixed $maybeint Data you wish to have converted to a non-negative integer.
Returns
int A non-negative integer.
Definition at line 3551 of file wordpress/wp-includes/functions.php.
Referenced by WP_Comments_List_Table\__construct(), wp_xmlrpc_server\_insert_post(), _wp_get_image_size_from_meta(), GFAPI\add_entry(), add_image_size(), add_metadata(), GravityView_Widget_Search\add_no_permalink_fields(), Custom_Image_Header\ajax_header_add(), Custom_Image_Header\ajax_header_crop(), Custom_Image_Header\ajax_header_remove(), WP_Customize_Nav_Menus\ajax_load_available_items(), GFForms\ajax_parse_request(), WP_Customize_Nav_Menus\ajax_search_available_items(), wp_xmlrpc_server\blogger_getRecentPosts(), GFForms\dashboard(), delete_metadata(), delete_metadata_by_mid(), WP_Customize_Header_Image_Control\enqueue(), GravityView_API\field_width(), GravityView_Widget_Search\filter_entries(), WP_Widget_Recent_Posts\form(), WP_Widget_Recent_Comments\form(), Twenty_Eleven_Ephemera_Widget\form(), Twenty_Fourteen_Ephemera_Widget\form(), GravityView_Recent_Entries_Widget\form(), GFFeedAddOn\get_active_feeds(), get_avatar_data(), WP_Comment_Query\get_comment_ids(), get_current_blog_id(), GFFormsModel\get_current_lead(), GFFeedAddOn\get_feeds(), GFFeedAddOn\get_feeds_by_slug(), GF_Field_SingleShipping\get_field_input(), GF_Field_Total\get_field_input(), GF_Field_Checkbox\get_field_input(), GF_Field_Post_Custom_Field\get_field_input(), GF_Field_Post_Tags\get_field_input(), GF_Field_Textarea\get_field_input(), GF_Field_Post_Excerpt\get_field_input(), GF_Field_Price\get_field_input(), GF_Field_Select\get_field_input(), GF_Field_Text\get_field_input(), GF_Field_Post_Content\get_field_input(), GF_Field_Donation\get_field_input(), GF_Field_Email\get_field_input(), GF_Field_MultiSelect\get_field_input(), GF_Field_Time\get_field_input(), GF_Field_Address\get_field_input(), GF_Field_FileUpload\get_field_input(), GFFormsModel\get_file_upload_path(), GFEntryList\get_filter_links(), GFAPI\get_form(), Custom_Image_Header\get_header_dimensions(), get_header_image_tag(), GFFormsModel\get_lead_field_value(), get_media_item(), get_metadata(), get_metadata_by_mid(), GFFormLocking\get_object_id(), GFEntryLocking\get_object_id(), GFLocking\get_object_id(), GFFormSettingsLocking\get_object_id(), get_oembed_response_data_rich(), WP_List_Table\get_pagenum(), get_pending_comments_num(), get_post_comments_feed_link(), get_post_custom(), WP_Query\get_posts(), GFPaymentAddOn\get_sales_data(), GFForms\get_shortcodes(), get_status_header_desc(), get_terms(), GFForms\get_toolbar_menu_items(), GFFormsModel\get_upload_path(), GFFormsModel\get_upload_url(), GravityView_Entry_Link_Shortcode\get_url(), GF_Field_Checkbox\get_value_entry_list(), GF_Field_Checkbox\get_value_export(), GF_Field_Name\get_value_export(), GF_Field_Address\get_value_export(), WP_Comments_List_Table\get_views(), GravityView_View\getViewId(), GFFormDisplay\gform_footer(), handle_confirmation_edit_submission(), GFFormDisplay\handle_save_confirmation(), GFFormDisplay\handle_save_email_confirmation(), Featured_Content\init(), GF_Field_Checkbox\is_checkbox_checked(), GFFormsModel\is_checkbox_checked(), is_sticky(), Custom_Image_Header\js_2(), GFEntryDetail\lead_detail_edit(), GFEntryDetail\lead_detail_grid(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), GFForms\maybe_process_form(), media_upload_form(), metadata_exists(), wp_xmlrpc_server\mt_getRecentPostTitles(), wp_xmlrpc_server\mw_getRecentPosts(), number_format_i18n(), WP_Query\parse_query(), WP_Query\parse_tax_query(), WP_User_Query\prepare_query(), GFFormDisplay\process_send_resume_link(), GFFeedAddOn\process_single_action(), WP_Customize_Header_Image_Control\render_content(), GFForms\resend_notifications(), sanitize_option(), GF_Field_Checkbox\sanitize_settings(), GF_Field_List\sanitize_settings(), GF_Field_FileUpload\sanitize_settings(), GF_Field\sanitize_settings(), GFFormsModel\sanitize_settings(), save_new_form(), WP_Customize_Nav_Menus\search_available_items_query(), set_post_thumbnail(), WP_HTTP_Response\set_status(), GravityView_Entry_Link_Shortcode\shortcode(), Custom_Image_Header\step_2(), Custom_Image_Header\step_3(), GFAPI\submit_form(), WP_Customize_Cropped_Image_Control\to_json(), GravityView_Search_WP_Widget\update(), WP_Widget_Recent_Comments\update(), GravityView_Recent_Entries_Widget\update(), Twenty_Fourteen_Ephemera_Widget\update(), GFAPI\update_entry(), GravityView_Change_Entry_Creator\update_entry_creator(), update_metadata(), update_metadata_by_mid(), GFAsyncUpload\upload(), url_to_postid(), WP_Widget_Recent_Posts\widget(), Twenty_Eleven_Ephemera_Widget\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), WP_Widget_Recent_Comments\widget(), wp_ajax_autocomplete_user(), wp_ajax_crop_image(), wp_ajax_get_attachment(), wp_ajax_get_comments(), wp_ajax_replyto_comment(), wp_ajax_save_attachment(), wp_ajax_save_attachment_compat(), wp_ajax_save_attachment_order(), wp_ajax_wp_link_ajax(), wp_calculate_image_sizes(), wp_check_locked_posts(), wp_dashboard(), wp_get_archives(), wp_get_attachment_image(), wp_get_attachment_image_sizes(), wp_get_attachment_image_srcset(), wp_get_recent_posts(), wp_xmlrpc_server\wp_getComments(), wp_xmlrpc_server\wp_getMediaLibrary(), wp_xmlrpc_server\wp_getPosts(), wp_xmlrpc_server\wp_getTerms(), wp_xmlrpc_server\wp_getUsers(), wp_handle_comment_submission(), _WP_Editors\wp_link_query(), wp_make_content_images_responsive(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_item_taxonomy_meta_box(), wp_new_comment(), wp_xmlrpc_server\wp_newComment(), wp_prepare_revisions_for_js(), wp_refresh_post_lock(), wp_refresh_post_nonces(), and wp_video_shortcode().
add_magic_quotes ($array)
Walks the array while sanitizing the contents.
Since
0.71
Parameters
array $array Array to walk while sanitizing contents.
Returns
array Sanitized $array.
Definition at line 901 of file wordpress/wp-includes/functions.php.
Referenced by _fix_attachment_links(), wp_magic_quotes(), and wp_update_user().
add_query_arg ()
Retrieves a modified URL query string.
You can rebuild the URL and append query variables to the URL query by using this function. There are two ways to use this function; either a single key and value, or an associative array.
Using a single key and value:
add_query_arg('key', 'value', 'http://example.com');
Using an associative array:
add_query_arg(array(
    'key1' => 'value1',
    'key2' => 'value2',
), 'http://example.com');
Omitting the URL from either use results in the current URL being used (the value of `$_SERVER['REQUEST_URI']`).
Values are expected to be encoded appropriately with urlencode() or rawurlencode().
Setting any query variable's value to boolean false removes the key (see remove_query_arg()).
Important: The return value of add_query_arg() is not escaped by default. Output should be late-escaped with esc_url() or similar to help prevent vulnerability to cross-site scripting (XSS) attacks.
Since
1.5.0
Parameters
string | array $key Either a query variable key, or an associative array of query variables.
string $value Optional. Either a query variable value, or a URL to act upon.
string $url Optional. A URL to act upon.
Returns
string New URL query string (unescaped).
Definition at line 770 of file wordpress/wp-includes/functions.php.
References $_SERVER, build_query(), elseif, urlencode_deep(), and wp_parse_str().
Referenced by WP_Plugins_List_Table\__construct(), WP_Styles\_css_href(), WP_oEmbed\_fetch_with_format(), GV_License_Handler\_license_get_remote_response(), _post_format_link(), _wp_link_page(), activate_plugin(), activate_plugins(), GravityView_frontend\add_columns_sort_links(), WP_Press_This\add_editor_style(), WP_Rewrite\add_rule(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Admin_Notices\admin_notice(), WP_Media_List_Table\column_author(), WP_Comments_List_Table\column_author(), WP_Media_List_Table\column_default(), WP_Terms_List_Table\column_name(), WP_MS_Themes_List_Table\column_name(), GFConfirmationTable\column_name(), WP_Media_List_Table\column_parent(), WP_Terms_List_Table\column_posts(), WP_MS_Users_List_Table\column_username(), WP_List_Table\comments_bubble(), GFFormSettings\confirmations_list_page(), WP_Customize_Theme_Control\content_template(), WP_Customize_Manager\customize_pane_settings(), Featured_Content\customize_register(), customize_themes_print_templates(), GravityView_API\directory_link(), WP_Scripts\do_item(), dropdown_cats(), GFEntryDetail\entry_detail_pagination_link(), GravityView_API\entry_link(), GFFeedAddOn\feed_list_title(), WP_oEmbed\fetch(), GFFeedAddOn\form_settings_header(), GFFeedAddOn\get_action_links(), get_avatar_data(), get_comment_link(), get_comment_reply_link(), get_comments_pagenum_link(), GravityView_Delete_Entry\get_delete_link(), get_delete_post_link(), GravityView_Edit_Entry\get_edit_link(), WP_Posts_List_Table\get_edit_link(), get_edit_term_link(), get_edit_user_link(), GravityView_Field_FileUpload\get_files_array(), GFLocking\get_lock_ui(), get_oembed_endpoint_url(), get_pagenum_link(), GFAddOn\get_plugin_settings_url(), get_post_comments_feed_link(), get_post_embed_url(), get_post_permalink(), get_post_type_archive_feed_link(), get_preview_post_link(), get_rest_url(), get_search_comments_feed_link(), get_search_feed_link(), GravityView_Widget_Search\get_search_form_action(), get_theme_update_available(), get_upload_iframe_src(), WP_Users_List_Table\get_views(), WP_Comments_List_Table\get_views(), WP_MS_Themes_List_Table\get_views(), WP_Plugins_List_Table\get_views(), WP_Terms_List_Table\handle_row_actions(), WP_MS_Users_List_Table\handle_row_actions(), WP_Theme_Install_List_Table\install_theme_info(), GravityView_Entry_Link_Shortcode\maybe_add_field_values_query_args(), media_upload_library_form(), menu_page_url(), GFExport\page_header(), page_header(), paginate_comments_links(), paginate_links(), WP_List_Table\pagination(), WP_List_Table\print_column_headers(), GravityView_Delete_Entry\process_delete(), redirect_canonical(), rel_canonical(), remove_query_arg(), GravityView_Widget_Page_Links\render_frontend(), GFFormDisplay\replace_save_variables(), GFPaymentAddOn\requires_credit_card_message(), WP_List_Table\set_pagination_args(), set_screen_options(), WP_Theme_Install_List_Table\single_row(), WP_Users_List_Table\single_row(), spawn_cron(), Custom_Image_Header\step_1(), GravityView_Edit_Entry_Test\test_get_edit_link(), GravityView_Widget_Search\the_clear_search_button(), the_media_upload_tabs(), twentyfourteen_contextual_help(), twentyfourteen_customize_register(), twentyfourteen_font_url(), twentythirteen_fonts_url(), twentytwelve_get_font_url(), WP_List_Table\view_switcher(), wp_add_dashboard_widget(), wp_admin_bar_customize_menu(), wp_admin_css_uri(), wp_ajax_query_themes(), wp_audio_shortcode(), wp_enqueue_media(), wp_get_archives(), wp_get_links(), wp_get_popular_importers(), wp_login_url(), wp_logout_url(), wp_lostpassword_url(), wp_media_attach_action(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_item_taxonomy_meta_box(), wp_nonce_url(), wp_prepare_revisions_for_js(), wp_prepare_themes_for_js(), wp_style_loader_src(), wp_theme_update_row(), and wp_video_shortcode().
apache_mod_loaded ($mod, $default = false)
Does the specified module exist in the Apache config?
Since
2.5.0
bool $is_apache
Parameters
string $mod The module, e.g. mod_rewrite.
bool $default Optional. The default return value if the module is not found. Default false.
Returns
bool Whether the specified module is loaded.
Definition at line 3850 of file wordpress/wp-includes/functions.php.
References $default, $is_apache, and elseif.
Referenced by got_mod_rewrite(), and network_step1().
bool_from_yn ($yn)
Whether input is yes or no.
Must be 'y' to be true.
Since
1.0.0
Parameters
string $yn Character string containing either 'y' (yes) or 'n' (no).
Returns
bool True if yes, false on anything else.
Definition at line 1196 of file wordpress/wp-includes/functions.php.
build_query ($data)
Build URL query based on an associative and, or indexed array.
This is a convenient function for easily building url queries. It sets the separator to '&' and uses _http_build_query() function.
Since
2.3.0
See also
_http_build_query() Used to build the query for more on what http_build_query() does. array $data URL-encode key/value pairs. string URL-encoded string.
Definition at line 684 of file wordpress/wp-includes/functions.php.
References _http_build_query(), and null.
Referenced by add_query_arg().
cache_javascript_headers ()
Set the headers for caching for 10 days with JavaScript content type.
Since
2.1.0
Definition at line 1164 of file wordpress/wp-includes/functions.php.
References get_bloginfo().
current_time ($type, $gmt = 0)
Retrieve the current time based on specified type.
The 'mysql' type will return the time in the format for MySQL DATETIME field. The 'timestamp' type will return the current timestamp. Other strings will be interpreted as PHP date formats (e.g. 'Y-m-d').
If $gmt is set to either '1' or 'true', then both types will use GMT time. if $gmt is false, the output is adjusted with the GMT offset in the WordPress option.
Since
1.0.0
Parameters
string $type Type of time to retrieve. Accepts 'mysql', 'timestamp', or PHP date format string (e.g. 'Y-m-d').
int | bool $gmt Optional. Whether to use GMT timezone. Default false.
Returns
int|string Integer if $type is 'timestamp', string otherwise.
Definition at line 61 of file wordpress/wp-includes/functions.php.
References date, and get_option().
Referenced by wp_xmlrpc_server\blogger_newPost(), WP_Date_Query\build_mysql_datetime(), GFFormsModel\copy_post_image(), date_i18n(), get_calendar(), get_day_link(), GFFormsModel\get_file_upload_path(), get_month_link(), WP_Query\get_posts(), get_year_link(), insert_blog(), media_handle_sideload(), media_handle_upload(), populate_network(), post_submit_meta_box(), GFFormsModel\save_incomplete_submission(), touch_time(), update_blog_details(), update_blog_status(), GFAsyncUpload\upload(), GFFormDisplay\validate_form_schedule(), wp_ajax_add_meta(), wp_insert_comment(), wp_insert_post(), wp_new_comment(), wp_post_revision_title_expanded(), wp_update_post(), wp_upload_dir(), wpmu_activate_signup(), wpmu_log_new_registrations(), wpmu_signup_blog(), wpmu_signup_user(), wpmu_update_blogs_date(), wpmu_validate_blog_signup(), and wpmu_validate_user_signup().
date_i18n ($dateformatstring, $unixtimestamp = false, $gmt = false)
Retrieve the date in localized format, based on timestamp.
If the locale specifies the locale month and weekday, then the locale will take over the format for the date. If it isn't, then the date format string will be used instead.
Since
0.71
WP_Locale $wp_locale
Parameters
string $dateformatstring Format to display the date.
bool | int $unixtimestamp Optional. Unix timestamp. Default false.
bool $gmt Optional. Whether to use GMT timezone. Default false.
Returns
string The date, translated if locale specifies it.
Filter the date formatted based on the locale.
Since
2.8.0
Parameters
string $j Formatted date string.
string $req_format Format to display the date.
int $i Unix timestamp.
bool $gmt Whether to convert to GMT for time. Default false.
Definition at line 89 of file wordpress/wp-includes/functions.php.
References $i, $timezone_format, $wp_locale, apply_filters(), backslashit(), current_time(), get_option(), and null.
Referenced by attachment_submit_meta_box(), heartbeat_autosave(), mysql2date(), post_submit_meta_box(), GravityView_frontend\process_search_dates(), GFExport\start_export(), GVCommon_Test\test_format_date(), GravityView_Merge_Tags_Test\test_replace_date_created(), wp_ajax_date_format(), wp_ajax_time_format(), wp_ajax_wp_fullscreen_save_post(), wp_get_archives(), wp_post_revision_title(), wp_post_revision_title_expanded(), wp_prepare_revisions_for_js(), and wp_widget_rss_output().
dead_db ()
Load custom DB error or display WordPress DB error.
If a file exists in the wp-content directory named db-error.php, then it will be loaded instead of displaying the WordPress DB error. If it is not found, then the WordPress DB error will be displayed instead.
The WordPress DB error sets the HTTP status header to 500 to try to prevent search engines from caching the message. Custom DB messages should do the same.
This function was backported to WordPress 2.3.2, but originally was added in WordPress 2.5.0.
Since
2.3.2
wpdb $wpdb WordPress database abstraction object.
Definition at line 3508 of file wordpress/wp-includes/functions.php.
References $wpdb, _e, is_rtl(), nocache_headers(), status_header(), WP_CONTENT_DIR, wp_die(), wp_installing(), and wp_load_translations_early().
Referenced by wpdb\check_connection(), is_blog_installed(), ms_not_installed(), and wp_set_wpdb_vars().
do_enclose ($content, $post_ID)
Check content for video and audio links to add as enclosures.
Will not add enclosures that have already been added and will remove enclosures that are no longer in the post. This is called as pingbacks and trackbacks.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $content Post Content.
int $post_ID Post ID.
Filter the list of enclosure links before querying the database.
Allows for the addition and/or removal of potential enclosures to save to postmeta before checking the database for existing enclosures.
Since
4.4.0
Parameters
array $post_links An array of enclosure links.
int $post_ID Post ID.
Definition at line 553 of file wordpress/wp-includes/functions.php.
References $content, $mime, $post_ID, $url, $wpdb, ABSPATH, add_post_meta(), apply_filters(), delete_metadata_by_mid(), elseif, get_enclosed(), wp_extract_urls(), wp_get_http_headers(), wp_get_mime_types(), and WPINC.
Referenced by do_all_pings().
do_feed ()
Load the feed template from the use of an action hook.
If the feed action does not have a hook, then the function will die with a message telling the visitor that the feed is not valid.
It is better to only have one hook for each feed.
Since
2.1.0
WP_Query $wp_query Used to tell if the use a comment feed.
Fires once the given feed is loaded.
The dynamic portion of the hook name, $feed, refers to the feed template name. Possible values include: 'rdf', 'rss', 'rss2', and 'atom'.
Since
2.1.0
4.4.0 The $feed parameter was added.
Parameters
bool $is_comment_feed Whether the feed is a comment feed.
string $feed The feed name.
Definition at line 1212 of file wordpress/wp-includes/functions.php.
References __, do_action(), get_default_feed(), get_query_var(), has_action(), and wp_die().
do_feed_atom ($for_comments)
Load either Atom comment feed or Atom posts feed.
Since
2.1.0
See also
load_template()
Parameters
bool $for_comments True for the comment feed, false for normal feed.
Definition at line 1289 of file wordpress/wp-includes/functions.php.
References ABSPATH, load_template(), and WPINC.
do_feed_rdf ()
Load the RDF RSS 0.91 Feed template.
Since
2.1.0
See also
load_template()
Definition at line 1249 of file wordpress/wp-includes/functions.php.
References ABSPATH, load_template(), and WPINC.
do_feed_rss ()
Load the RSS 1.0 Feed Template.
Since
2.1.0
See also
load_template()
Definition at line 1260 of file wordpress/wp-includes/functions.php.
References ABSPATH, load_template(), and WPINC.
do_feed_rss2 ($for_comments)
Load either the RSS2 comment feed or the RSS2 posts feed.
Since
2.1.0
See also
load_template()
Parameters
bool $for_comments True for the comment feed, false for normal feed.
Definition at line 1273 of file wordpress/wp-includes/functions.php.
References ABSPATH, load_template(), and WPINC.
do_robots ()
Display the robots.txt file content.
The echo content should be with usage of the permalinks or for creating the robots.txt file.
Since
2.1.0
Fires when displaying the robots.txt file.
Since
2.1.0
Filter the robots.txt output.
Since
3.0.0
Parameters
string $output Robots.txt output.
bool $public Whether the site is considered "public".
Definition at line 1304 of file wordpress/wp-includes/functions.php.
References $output, $path, apply_filters(), do_action(), get_option(), and site_url().
force_ssl_admin ($force = null)
Whether to force SSL used for the Administration Screens.
Since
2.6.0
bool $forced
Parameters
string | bool $force Optional. Whether to force SSL in admin screens. Default null.
Returns
bool True if forced, false if not forced.
Definition at line 3965 of file wordpress/wp-includes/functions.php.
Referenced by force_ssl_login(), set_url_scheme(), and wp_ssl_constants().
get_allowed_mime_types ($user = null)
Retrieve list of allowed mime types and file extensions.
Since
2.8.6
Parameters
int | WP_User $user Optional. User to check. Defaults to current user.
Returns
array Array of mime types keyed by the file extension regex corresponding to those types.
Filter list of allowed mime types and file extensions.
Since
2.0.0
Parameters
array $t Mime types keyed by the file extension regex corresponding to those types. 'swf' and 'exe' removed from full list. 'htm|html' also removed depending on '$user' capabilities.
int | WP_User | null $user User ID, User object or null if not provided (indicates current user).
Definition at line 2397 of file wordpress/wp-includes/functions.php.
References $user, apply_filters(), current_user_can(), user_can(), and wp_get_mime_types().
Referenced by sanitize_file_name(), wp_check_filetype(), and wp_enqueue_media().
get_file_data ($file, $default_headers, $context = '')
Retrieve metadata from a file.
Searches for metadata in the first 8kiB of a file, such as a plugin or theme. Each piece of metadata must be on its own line. Fields can not span multiple lines, the value will get cut at the end of the first line.
If the file data is not within that first 8kiB, then the author should correct their plugin file and move the data headers to the top.
2.9.0 string $file Path to the file. array $default_headers List of headers, in the format array('HeaderKey' => 'Header Name'). string $context Optional. If specified adds filter hook "extra_{$context}_headers". Default empty. array Array of file headers in HeaderKey => Header Value format.
Filter extra file headers by context.
The dynamic portion of the hook name, $context, refers to the context where extra headers might be loaded.
Since
2.9.0
Parameters
array $extra_context_headers Empty array by default.
Definition at line 4484 of file wordpress/wp-includes/functions.php.
References $field, $file, _cleanup_header_comment(), apply_filters(), and str_replace.
Referenced by WP_Theme\__construct(), Theme_Upgrader\check_package(), get_plugin_data(), and wp_get_pomo_file_data().
get_main_network_id ()
Get the main network ID.
Since
4.3.0
wpdb $wpdb WordPress database abstraction object.
Returns
int The ID of the main network.
Filter the main network ID.
Since
4.3.0
Parameters
int $main_network_id The ID of the main network.
Definition at line 4132 of file wordpress/wp-includes/functions.php.
References $wpdb, apply_filters(), elseif, get_current_site(), is_multisite(), wp_cache_add(), and wp_cache_get().
Referenced by is_main_network().
get_num_queries ()
Retrieve the number of database queries during the WordPress execution.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Returns
int Number of database queries.
Definition at line 1181 of file wordpress/wp-includes/functions.php.
References $wpdb.
get_status_header_desc ($code)
Retrieve the description for the HTTP status.
Since
2.3.0
array $wp_header_to_desc
Parameters
int $code HTTP status code.
Returns
string Empty string if not found, or description if found.
Definition at line 968 of file wordpress/wp-includes/functions.php.
References absint().
Referenced by _oembed_rest_pre_serve_request(), WP_oEmbed_Controller\get_item(), and status_header().
get_tag_regex ($tag)
Return RegEx body to liberally match an opening HTML tag.
Matches an opening HTML tag that:
Is self-closing or
Has no body but has a closing tag of the same name or
Contains a body and a closing tag of the same name
Note: this RegEx does not balance inner tags and does not attempt to produce valid HTML
Since
3.6.0
Parameters
string $tag An HTML tag name. Example: 'video'.
Returns
string Tag RegEx.
Definition at line 5014 of file wordpress/wp-includes/functions.php.
References tag_escape().
get_temp_dir ()
Determine a writable directory for temporary files.
Function's preference is the return value of sys_get_temp_dir(), followed by your PHP temporary upload directory, followed by WP_CONTENT_DIR, before finally defaulting to /tmp/
In the event that this function does not find a writable location, It may be overridden by the WP_TEMP_DIR constant in your wp-config.php file.
Since
2.5.0
string $temp
Returns
string Writable temporary directory.
Definition at line 1723 of file wordpress/wp-includes/functions.php.
References trailingslashit(), WP_CONTENT_DIR, and wp_is_writable().
Referenced by WP_Http\request(), wp_read_audio_metadata(), wp_read_video_metadata(), and wp_tempnam().
get_weekstartend ($mysqlstring, $start_of_week = '')
Get the week start and end from the datetime or date string from MySQL.
Since
0.71
Parameters
string $mysqlstring Date or datetime field type from MySQL.
int | string $start_of_week Optional. Start of the week as an integer. Default empty string.
Returns
array Keys are 'start' and 'end'.
Definition at line 284 of file wordpress/wp-includes/functions.php.
References date, and get_option().
Referenced by wp_get_archives().
global_terms_enabled ()
Determine whether global terms are enabled.
Since
3.0.0
bool $global_terms
Returns
bool True if multisite and global terms enabled.
Filter whether global terms are enabled.
Passing a non-null value to the filter will effectively short-circuit the function, returning the value of the 'global_terms_enabled' site option instead.
Since
3.0.0
Parameters
null $enabled Whether global terms are enabled.
Definition at line 4172 of file wordpress/wp-includes/functions.php.
References apply_filters(), get_site_option(), is_multisite(), and null.
Referenced by global_terms(), WP_Terms_List_Table\inline_edit(), populate_network(), and sync_category_tag_slugs().
iis7_supports_permalinks ()
Check if IIS 7+ supports pretty permalinks.
Since
2.8.0
bool $is_iis7
Returns
bool Whether IIS7 supports permalinks.
Filter whether IIS 7+ supports pretty permalinks.
Since
2.8.0
Parameters
bool $supports_permalinks Whether IIS7 supports permalinks. Default false.
Definition at line 3879 of file wordpress/wp-includes/functions.php.
References $_SERVER, $is_iis7, and apply_filters().
Referenced by got_url_rewrite(), iis7_save_url_rewrite_rules(), network_step2(), and redirect_canonical().
is_blog_installed ()
Test whether blog is already installed.
The cache will be checked first. If you have a cache plugin, which saves the cache values, then this will work. If you use the default WordPress cache, and the database goes away, then you might have problems.
Checks for the 'siteurl' option for whether WordPress is installed.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Returns
bool Whether the blog is already installed.
Definition at line 1351 of file wordpress/wp-includes/functions.php.
References $wpdb, __, dead_db(), wp_cache_get(), wp_cache_set(), wp_installing(), wp_load_alloptions(), and wp_load_translations_early().
Referenced by wp_not_installed(), and wp_widgets_init().
is_lighttpd_before_150 ()
Is the server running earlier than 1.5.0 version of lighttpd?
Since
2.5.0
Returns
bool Whether the server is running lighttpd < 1.5.0.
Definition at line 3833 of file wordpress/wp-includes/functions.php.
References $_SERVER.
is_main_network ($network_id = null)
Determine whether a network is the main network of the Multisite install.
Since
3.7.0
Parameters
int $network_id Optional. Network ID to test. Defaults to current network.
Returns
bool True if $network_id is the main network, or if not running Multisite.
Definition at line 4107 of file wordpress/wp-includes/functions.php.
References get_current_site(), get_main_network_id(), is_multisite(), and null.
Referenced by populate_options(), WP_Automatic_Updater\run(), upgrade_network(), wp_should_upgrade_global_tables(), and wp_upload_dir().
is_main_site ($site_id = null)
Determine whether a site is the main site of the current network.
Since
3.0.0
object $current_site
Parameters
int $site_id Optional. Site ID to test. Defaults to current site. Defaults to current site.
Returns
bool True if $site_id is the main site of the network, or if not running Multisite.
Definition at line 4086 of file wordpress/wp-includes/functions.php.
References $current_site, get_current_blog_id(), and is_multisite().
Referenced by avoid_blog_page_permalink_collision(), GravityView_Admin_Notices\check_show_multisite_notices(), WP_MS_Sites_List_Table\column_cb(), GravityView_Settings\create_app_menu(), get_dirsize(), is_main_blog(), GFForms\maybe_display_installation_wizard(), maybe_redirect_404(), populate_options(), WP_Rewrite\rewrite_rules(), WP_Automatic_Updater\run(), upgrade_300(), wp_schedule_update_network_counts(), wp_should_upgrade_global_tables(), wp_upload_dir(), and wpmu_delete_blog().
is_new_day ()
Whether the publish date of the current post in the loop is different from the publish date of the previous post in the loop.
Since
0.71
string $currentday The day of the current post in the loop. string $previousday The day of the previous post in the loop.
Returns
int 1 when new day, 0 if not a new day.
Definition at line 661 of file wordpress/wp-includes/functions.php.
Referenced by the_date().
is_serialized ($data, $strict = true)
Check value to find if it was serialized.
If $data is not an string, then returned value will always be false. Serialized data is always a string.
Since
2.0.5
Parameters
string $data Value to check to see if was serialized.
bool $strict Optional. Whether to be strict about the end of the string. Default true.
Returns
bool False if not serialized and true if it was.
Definition at line 340 of file wordpress/wp-includes/functions.php.
References elseif.
Referenced by _list_meta_row(), maybe_serialize(), maybe_unserialize(), and GFFormsModel\unserialize().
is_serialized_string ($data)
Check whether serialized data is of string type.
Since
2.0.5
Parameters
string $data Serialized data.
Returns
bool False if not a serialized string, true if it is.
Definition at line 403 of file wordpress/wp-includes/functions.php.
References elseif.
Referenced by _list_meta_row().
is_ssl ()
Determine if SSL is used.
Since
2.6.0
Returns
bool True if SSL, false if not used.
Definition at line 3943 of file wordpress/wp-includes/functions.php.
References $_SERVER, and elseif.
Referenced by WP_Admin_Bar\__get(), GravityView_Support_Port\_localize_script(), GravityView_Admin_Add_Shortcode\add_scripts_and_styles(), WP_Customize_Manager\customize_pane_settings(), GravityView_Widget_Search\enqueue_datepicker(), filter_SSL(), get_avatar_data(), GF_Field_CAPTCHA\get_captcha(), GFFormDisplay\get_field(), GFFormDisplay\get_field_content(), GF_Field_FileUpload\get_field_input(), GF_Field_CAPTCHA\get_field_input(), GF_Field_CreditCard\get_form_inline_script_on_page_render(), get_home_url(), GF_Field_CAPTCHA\get_math_captcha(), get_rest_url(), GF_Field_FileUpload\get_value_entry_detail(), install_plugin_information(), network_home_url(), redirect_canonical(), set_url_scheme(), wp_admin_bar_customize_menu(), wp_ajax_parse_embed(), wp_auth_check_html(), wp_get_attachment_url(), wp_guess_url(), wp_login_form(), and wp_signon().
maybe_serialize ($data)
Serialize data, if needed.
Since
2.0.5
Parameters
string | array | object $data Data that might be serialized.
Returns
mixed A scalar data
Definition at line 432 of file wordpress/wp-includes/functions.php.
References is_serialized().
Referenced by add_metadata(), add_network_option(), add_option(), delete_metadata(), gform_add_meta(), gform_update_meta(), GFFormsModel\update_grid_column_meta(), update_metadata(), update_metadata_by_mid(), update_network_option(), update_option(), and update_usermeta().
maybe_unserialize ($original)
Unserialize value only if it was serialized.
Since
2.0.0
Parameters
string $original Maybe unserialized original, if is needed.
Returns
mixed Unserialized data can be any type.
Definition at line 322 of file wordpress/wp-includes/functions.php.
References is_serialized().
Referenced by __get_option(), _list_meta_row(), GravityView_Field_List\column_value(), GravityView_Admin_Duplicate_View\copy_view_meta_info(), count_users(), GV_UnitTest_Factory_For_View\create_object(), GFFormsModel\create_post(), GF_Field_List\get_field_input(), GFFormsModel\get_grid_column_meta(), get_metadata(), get_metadata_by_mid(), get_network_option(), get_option(), gform_get_meta(), gform_get_meta_values_for_entries(), GravityView_Ajax\import_fields(), plugins_api(), GFExport\start_export(), themes_api(), wp_load_core_site_options(), and wpmu_activate_signup().
mbstring_binary_safe_encoding ($reset = false)
Set the mbstring internal encoding to a binary safe encoding when func_overload is enabled.
When mbstring.func_overload is in use for multi-byte encodings, the results from strlen() and similar functions respect the utf8 characters, causing binary data to return incorrect lengths.
This function overrides the mbstring encoding to a binary-safe encoding, and resets it to the users expected encoding afterwards through the reset_mbstring_encoding function.
It is safe to recursively call this function, however each mbstring_binary_safe_encoding() call must be followed up with an equal number of reset_mbstring_encoding() calls.
Since
3.7.0
See also
reset_mbstring_encoding()
array $encodings bool $overloaded
Parameters
bool $reset Optional. Whether to reset the encoding back to a previously-set encoding. Default false.
Definition at line 5070 of file wordpress/wp-includes/functions.php.
References null.
Referenced by _unzip_file_pclzip(), WP_Filesystem_ftpsockets\dirlist(), WP_Filesystem_ftpsockets\get_contents(), WP_Filesystem_Direct\put_contents(), WP_Filesystem_FTPext\put_contents(), WP_Filesystem_ftpsockets\put_contents(), WP_Http\request(), reset_mbstring_encoding(), seems_utf8(), wpdb\strip_invalid_text(), utf8_uri_encode(), and wp_read_image_metadata().
mysql2date ($format, $date, $translate = true)
Convert given date string into a different format.
$format should be either a PHP date format string, e.g. 'U' for a Unix timestamp, or 'G' for a Unix timestamp assuming that $date is GMT.
If $translate is true then the given date and format string will be passed to date_i18n() for translation.
Since
0.71
Parameters
string $format Format of the date to return.
string $date Date string to convert.
bool $translate Whether the return date should be translated. Default true.
Returns
string|int|bool Formatted date string or Unix timestamp. False if $date is empty.
Definition at line 26 of file wordpress/wp-includes/functions.php.
References $format, $i, date, and date_i18n().
Referenced by wp_xmlrpc_server\_convert_date(), wp_xmlrpc_server\_convert_date_gmt(), check_comment_flood_db(), WP_Media_List_Table\column_date(), WP_Posts_List_Table\column_date(), WP_MS_Sites_List_Table\column_lastupdated(), WP_MS_Users_List_Table\column_registered(), WP_MS_Sites_List_Table\column_registered(), GVCommon\format_date(), get_adjacent_post_link(), get_adjacent_post_rel_link(), get_boundary_post_rel_link(), get_comment_date(), get_comment_time(), get_inline_data(), get_media_item(), get_parent_post_rel_link(), get_post_modified_time(), get_post_time(), get_the_date(), mysql_to_rfc3339(), WP\send_headers(), WP_Query\setup_postdata(), Walker_Page\start_el(), GFExport\start_export(), GVCommon_Test\test_format_date(), GravityView_Merge_Tags_Test\test_replace_date_created(), the_date_xml(), the_weekday(), the_weekday_date(), touch_time(), upgrade_210(), wp_ajax_find_posts(), wp_ajax_wp_fullscreen_save_post(), wp_xmlrpc_server\wp_editPost(), wp_get_archives(), wp_insert_post(), _WP_Editors\wp_link_query(), wp_prepare_attachment_for_js(), wpmu_validate_blog_signup(), and wpmu_validate_user_signup().
mysql_to_rfc3339 ($date_string)
Parses and formats a MySQL datetime (Y-m-d H:i:s) for ISO8601/RFC3339.
Explicitly strips timezones, as datetimes are not saved with any timezone information. Including any information on the offset could be misleading.
Since
4.4.0
Parameters
string $date_string Date string to parse and format.
Returns
string Date formatted for ISO8601/RFC3339.
Definition at line 5191 of file wordpress/wp-includes/functions.php.
References mysql2date().
nocache_headers ()
Set the headers to prevent caching for the different browsers.
Different browsers support different nocache headers, so several headers must be sent so that all of them get the point that no caching should occur.
Since
2.0.0
See also
wp_get_nocache_headers()
Definition at line 1136 of file wordpress/wp-includes/functions.php.
References $name, and wp_get_nocache_headers().
Referenced by _default_wp_die_handler(), dead_db(), WP\handle_404(), GFAsyncUpload\upload(), and wp_not_installed().
number_format_i18n ($number, $decimals = 0)
Convert integer number to format based on the locale.
Since
2.3.0
WP_Locale $wp_locale
Parameters
int $number The number to convert based on locale.
int $decimals Optional. Precision of the number of decimal places. Default 0.
Returns
string Converted number in string format.
Filter the number formatted based on the locale.
Since
2.8.0
Parameters
string $formatted Converted number in string format.
Definition at line 218 of file wordpress/wp-includes/functions.php.
References $wp_locale, absint(), and apply_filters().
Referenced by _wp_ajax_delete_comment_response(), WP_List_Table\ajax_response(), WP_Terms_List_Table\column_links(), WP_Terms_List_Table\column_posts(), WP_MS_Sites_List_Table\column_users(), WP_List_Table\comments_bubble(), comments_popup_link(), WP_Customize_Nav_Menus\customize_register(), WP_Plugin_Install_List_Table\display_rows(), get_comments_number_text(), GravityView_Shortcode\get_view_detail(), WP_MS_Users_List_Table\get_views(), WP_Users_List_Table\get_views(), WP_Comments_List_Table\get_views(), WP_Posts_List_Table\get_views(), WP_MS_Themes_List_Table\get_views(), WP_Plugins_List_Table\get_views(), gravityview_number_format(), media_handle_upload(), media_upload_library_form(), paginate_links(), WP_List_Table\pagination(), GFPaymentStatsTable\pagination(), post_submit_meta_box(), GravityView_Widget_Pagination_Info\render_frontend(), WP_Screen\render_screen_layout(), WP_Users_List_Table\single_row(), size_format(), Walker_Category\start_el(), GravityView_Helper_Functions_Test\test_gravityview_number_format(), timer_stop(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_admin_bar_comments_menu(), wp_admin_bar_updates_menu(), wp_ajax_query_themes(), wp_ajax_replyto_comment(), wp_dashboard_right_now(), wp_generate_tag_cloud(), wp_network_dashboard_right_now(), and wp_star_rating().
path_is_absolute ($path)
Test if a give filesystem path is absolute.
For example, '/foo/bar', or 'c:'.
Since
2.5.0
Parameters
string $path File path.
Returns
bool True if path is absolute, false is not absolute.
Definition at line 1647 of file wordpress/wp-includes/functions.php.
References $path.
Referenced by path_join().
path_join ($base, $path)
Join two filesystem paths together.
For example, 'give me $path relative to $base'. If the $path is absolute, then it the full path is returned.
Since
2.5.0
Parameters
string $base Base path.
string $path Path relative to $base.
Returns
string The path with the base or absolute path.
Definition at line 1678 of file wordpress/wp-includes/functions.php.
References $path, and path_is_absolute().
Referenced by _load_image_to_edit_path(), image_get_intermediate_size(), WP_Filesystem_Base\search_for_folder(), wp_delete_attachment(), wp_restore_image(), wp_save_image(), and wp_upload_dir().
remove_query_arg ($key, $query = false)
Removes an item or items from a query string.
Since
1.5.0
Parameters
string | array $key Query key or keys to remove.
bool | string $query Optional. When false uses the current URL. Default false.
Returns
string New URL query string.
Definition at line 842 of file wordpress/wp-includes/functions.php.
References add_query_arg().
Referenced by _post_format_link(), _remove_qs_args_if_not_in_url(), GravityView_frontend\add_columns_sort_links(), WP_Customize_Theme_Control\content_template(), GravityView_Edit_Entry_Render\edit_entry_form(), GFEntryDetail\entry_detail_pagination_link(), get_cancel_comment_reply_link(), GFFormDisplay\get_form(), get_pagenum_link(), handle_confirmation_edit_submission(), notification_edit_page(), WP_List_Table\pagination(), WP_List_Table\print_column_headers(), GravityView_Delete_Entry\process_delete(), redirect_canonical(), GFFormDisplay\replace_save_variables(), WP_Customize_Manager\set_return_url(), set_screen_options(), wp_admin_canonical_url(), wp_dashboard_setup(), wp_media_attach_action(), and wp_nonce_ays().
reset_mbstring_encoding ()
Reset the mbstring internal encoding to a users previously set encoding.
See also
mbstring_binary_safe_encoding()
Since
3.7.0
Definition at line 5099 of file wordpress/wp-includes/functions.php.
References mbstring_binary_safe_encoding().
Referenced by _unzip_file_pclzip(), WP_Filesystem_ftpsockets\dirlist(), WP_Filesystem_ftpsockets\get_contents(), WP_Filesystem_Direct\put_contents(), WP_Filesystem_FTPext\put_contents(), WP_Filesystem_ftpsockets\put_contents(), WP_Http\request(), seems_utf8(), wpdb\strip_invalid_text(), utf8_uri_encode(), and wp_read_image_metadata().
send_frame_options_header ()
Send a HTTP header to limit rendering of pages to same origin iframes.
Since
3.1.3
See also
https://developer.mozilla.org/en/the_x-frame-options_response_header
Definition at line 4721 of file wordpress/wp-includes/functions.php.
send_nosniff_header ()
Send a HTTP header to disable content type sniffing in browsers which support it.
Since
3.0.0
See also
http://blogs.msdn.com/ie/archive/2008/07/02/ie8-security-part-v-comprehensive-protection.aspx
http://src.chromium.org/viewvc/chrome?view=rev&revision=6985
Definition at line 4616 of file wordpress/wp-includes/functions.php.
Referenced by GFAsyncUpload\upload().
size_format ($bytes, $decimals = 0)
Convert number of bytes largest unit bytes will fit into.
It is easier to read 1 kB than 1024 bytes and 1 MB than 1048576 bytes. Converts number of bytes to human readable number by taking the number of that unit that the bytes will go into it. Supports TB value.
Please note that integers in PHP are limited to 32 bits, unless they are on 64 bit architecture, then they have 64 bit size. If you need to place the larger size then what PHP integer type will hold, then use a string. It will be converted to a double, which should always have 64 bit length.
Technically the correct unit names for powers of 1024 are KiB, MiB etc.
Since
2.3.0
Parameters
int | string $bytes Number of bytes. Note max integer size for integers.
int $decimals Optional. Precision of number of decimal places. Default 0.
Returns
string|false False on failure. Number string on success.
Definition at line 257 of file wordpress/wp-includes/functions.php.
References number_format_i18n().
Referenced by attachment_submitbox_metadata(), media_upload_form(), wp_import_upload_form(), wp_prepare_attachment_for_js(), and wp_print_media_templates().
smilies_init ()
Convert smiley code to the icon graphic file equivalent.
You can turn off smilies, by going to the write setting screen and unchecking the box, or by setting 'use_smilies' option to false or removing the option.
Plugins may override the default smiley list by setting the $wpsmiliestrans to an array, with the key the code the blogger types in and the value the image file.
The $wp_smiliessearch global is for the regular expression and is set each time the function is called.
The full list of smilies can be found in the function and won't be listed in the description. Probably should create a Codex page for it, so that it is available.
array $wpsmiliestrans array $wp_smiliessearch
Since
2.2.0
Definition at line 3130 of file wordpress/wp-includes/functions.php.
References get_option(), and wp_spaces_regexp().
status_header ($code, $description = '')
Set HTTP status header.
Since
2.0.0
4.4.0 Added the $description parameter.
See also
get_status_header_desc()
Parameters
int $code HTTP status code.
string $description Optional. A custom description for the HTTP status.
Filter an HTTP status header.
Since
2.2.0
Parameters
string $status_header HTTP status header.
int $code HTTP status code.
string $description Description for the status code.
string $protocol Server protocol.
Definition at line 1058 of file wordpress/wp-includes/functions.php.
References $description, apply_filters(), get_status_header_desc(), and wp_get_server_protocol().
Referenced by _default_wp_die_handler(), _oembed_rest_pre_serve_request(), WP_Customize_Manager\customize_preview_override_404_status(), dead_db(), GFPaymentAddOn\display_callback_error(), WP\handle_404(), GFPaymentAddOn\maybe_process_callback(), WP\send_headers(), send_origin_headers(), IXR_Server\serve(), WP_REST_Server\set_status(), and GFAsyncUpload\upload().
validate_file ($file, $allowed_files = '')
File validates against allowed set of defined rules.
A return value of '1' means that the $file contains either '..' or './'. A return value of '2' means that the $file contains ':' after the first character. A return value of '3' means that the file is not in the allowed files list.
Since
1.2.0
Parameters
string $file File path.
array $allowed_files List of allowed files.
Returns
int 0 means nothing is wrong, greater than 0 means something was wrong.
Definition at line 3920 of file wordpress/wp-includes/functions.php.
References $allowed_files, and $file.
Referenced by get_page_template(), validate_file_to_edit(), validate_plugin(), wp_get_active_and_valid_plugins(), and wp_get_active_network_plugins().
win_is_writable ($path)
Workaround for Windows bug in is_writable() function.
PHP has issues with Windows ACL's for determine if a directory is writable or not, this works around them by checking the ability to open files rather than relying upon PHP to interprate the OS ACL.
Since
2.8.0
See also
http://bugs.php.net/bug.php?id=27609
http://bugs.php.net/bug.php?id=30931
Parameters
string $path Windows path to check for write-ability.
Returns
bool Whether the path is writable.
Definition at line 1784 of file wordpress/wp-includes/functions.php.
References $path, and elseif.
Referenced by iis7_save_url_rewrite_rules(), and wp_is_writable().
wp ($query_vars = '')
Set up the WordPress query.
Since
2.0.0
WP $wp_locale WP_Query $wp_query WP_Query $wp_the_query
Parameters
string | array $query_vars Default WP_Query arguments.
Definition at line 950 of file wordpress/wp-includes/functions.php.
References $wp.
Referenced by wp_edit_attachments_query(), and wp_edit_posts_query().
wp_allowed_protocols ()
Retrieve a list of protocols to allow in HTML attributes.
Since
3.3.0
4.3.0 Added 'webcal' to the protocols array.
See also
wp_kses()
esc_url()
array $protocols
Returns
array Array of allowed protocols. Defaults to an array containing 'http', 'https', 'ftp', 'ftps', 'mailto', 'news', 'irc', 'gopher', 'nntp', 'feed', 'telnet', 'mms', 'rtsp', 'svn', 'tel', 'fax', 'xmpp', and 'webcal'.
Filter the list of protocols allowed in HTML attributes.
Since
3.0.0
Parameters
array $protocols Array of allowed protocols e.g. 'http', 'ftp', 'tel', and more.
Definition at line 4740 of file wordpress/wp-includes/functions.php.
References apply_filters().
Referenced by _links_add_base(), edit_user(), esc_url(), wp_kses(), and wp_kses_one_attr().
wp_array_slice_assoc ($array, $keys)
Extract a slice of an array, given a list of keys.
Since
3.1.0
Parameters
array $array The original array.
array $keys The list of keys.
Returns
array The array slice.
Definition at line 3275 of file wordpress/wp-includes/functions.php.
References $keys.
Referenced by WP_Comment_Query\get_comment_ids(), WP_Comment_Query\get_comments(), get_pages(), get_terms(), WP_Customize_Panel\json(), WP_Customize_Section\json(), WP_Customize_Nav_Menu_Setting\sanitize(), WP_Customize_Nav_Menu_Item_Setting\sanitize(), WP_Customize_Manager\set_autofocus(), WP_Customize_Nav_Menu_Setting\update(), WP_Customize_Nav_Menu_Setting\value(), wp_dropdown_users(), wp_list_authors(), and wp_update_comment().
wp_auth_check ($response)
Check whether a user is still logged in, for the heartbeat.
Send a result that shows a log-in box if the user is no longer logged in, or if their cookie is within the grace period.
Since
3.6.0
int $login_grace_period
Parameters
array $response The Heartbeat response.
Returns
array $response The Heartbeat response with 'wp-auth-check' value set.
Definition at line 4993 of file wordpress/wp-includes/functions.php.
References $GLOBALS.
wp_auth_check_html ()
Output the HTML that shows the wp-login dialog when the user is no longer logged in.
Since
3.6.0
Filter whether the authentication check originated at the same domain.
Since
3.6.0
Parameters
bool $same_domain Whether the authentication check originated at the same domain.
Definition at line 4941 of file wordpress/wp-includes/functions.php.
References $_SERVER, _e, apply_filters(), is_ssl(), and wp_login_url().
wp_auth_check_load ()
Load the auth check for monitoring whether the user is still logged in.
Can be disabled with remove_action('admin_enqueue_scripts', 'wp_auth_check_load');
This is disabled for certain screens where a login screen could cause an inconvenient interruption. A filter called wp_auth_check_load can be used for fine-grained control.
Since
3.6.0
Filter whether to load the authentication check.
Passing a falsey value to the filter will effectively short-circuit loading the authentication check.
Since
3.6.0
Parameters
bool $show Whether to load the authentication check.
WP_Screen $screen The current screen object.
Definition at line 4905 of file wordpress/wp-includes/functions.php.
References $screen, add_action(), apply_filters(), get_current_screen(), is_admin(), wp_enqueue_script(), and wp_enqueue_style().
wp_check_filetype ($filename, $mimes = null)
Retrieve the file type from the file name.
You can optionally define the mime array, if needed.
Since
2.0.4
Parameters
string $filename File name or path.
array $mimes Optional. Key is the file extension with value as the mime type.
Returns
array Values with extension first and mime type.
Definition at line 2160 of file wordpress/wp-includes/functions.php.
References get_allowed_mime_types().
Referenced by WP_UnitTestCase\_make_attachment(), GFFormsModel\copy_post_image(), WP_UnitTest_Factory_For_Attachment\create_upload_object(), wp_attachment_is(), wp_audio_shortcode(), wp_check_filetype_and_ext(), wp_get_image_editor(), wp_playlist_shortcode(), wp_upload_bits(), and wp_video_shortcode().
wp_check_filetype_and_ext ($file, $filename, $mimes = null)
Attempt to determine the real file type of a file.
If unable to, the file name extension will be used to determine type.
If it's determined that the extension does not match the file's real type, then the "proper_filename" value will be set with a proper filename and extension.
Currently this function only supports validating images known to getimagesize().
Since
3.0.0
Parameters
string $file Full path to the file.
string $filename The name of the file (may differ from $file due to $file being in a tmp directory).
array $mimes Optional. Key is the file extension with value as the mime type.
Returns
array Values for the extension, MIME, and either a corrected filename or false if original $filename is valid.
Filter the list mapping image mime types to their respective extensions.
Since
3.0.0
Parameters
array $mime_to_ext Array of image mime types and their matching extensions.
Filter the "real" file type of the given file.
Since
3.0.0
Parameters
array $wp_check_filetype_and_ext File data array containing 'ext', 'type', and 'proper_filename' keys.
string $file Full path to the file.
string $filename The name of the file (may differ from $file due to $file being in a tmp directory).
array $mimes Key is the file extension with value as the mime type.
Definition at line 2197 of file wordpress/wp-includes/functions.php.
References $file, apply_filters(), and wp_check_filetype().
Referenced by _wp_handle_upload(), Custom_Image_Header\step_2_manage_upload(), and wp_ajax_upload_attachment().
wp_checkdate ($month, $day, $year, $source_date)
Test if the supplied date is valid for the Gregorian calendar.
Since
3.5.0
See also
checkdate()
Parameters
int $month Month number.
int $day Day number.
int $year Year number.
string $source_date The date to filter.
Returns
bool True if valid date, false if not valid date.
Filter whether the given date is valid for the Gregorian calendar.
Since
3.5.0
Parameters
bool $checkdate Whether the given date is valid.
string $source_date Date to check.
Definition at line 4882 of file wordpress/wp-includes/functions.php.
References apply_filters().
Referenced by _wp_translate_postdata(), WP_Query\parse_query(), redirect_canonical(), WP_Date_Query\validate_date_values(), and wp_insert_post().
wp_debug_backtrace_summary ($ignore_class = null, $skip_frames = 0, $pretty = true)
Return a comma-separated string of functions that have been called to get to the current point in code.
Since
3.4.0
See also
https://core.trac.wordpress.org/ticket/19589
Parameters
string $ignore_class Optional. A class to ignore all function calls within - useful when you want to just give info about the callee. Default null.
int $skip_frames Optional. A number of stack frames to skip - useful for unwinding back to the source of the issue. Default 0.
bool $pretty Optional. Whether or not you want a comma separated string or raw array returned. Default true.
Returns
string|array Either a string containing a reversed comma separated trace or an array of individual calls.
Definition at line 4776 of file wordpress/wp-includes/functions.php.
References ABSPATH, elseif, str_replace, and WP_CONTENT_DIR.
Referenced by wpdb\get_caller(), GravityView_Logging\log_debug(), GravityView_Logging\log_error(), and GV_Unit_Tests_Bootstrap\test_print_log().
wp_delete_file ($file)
Delete a file.
Since
4.2.0
Parameters
string $file The path to the file to delete.
Filter the path of the file to delete.
Since
2.1.0
Parameters
string $medium Path to the file to delete.
Definition at line 5132 of file wordpress/wp-includes/functions.php.
References $file, and apply_filters().
Referenced by Custom_Image_Header\step_3(), wp_ajax_crop_image(), wp_delete_attachment(), wp_restore_image(), and wp_save_image().
wp_die ($message = '', $title = '', $args = array())
Kill WordPress execution and display HTML message with error message.
This function complements the die() PHP function. The difference is that HTML will be displayed to the user. It is recommended to use this function only when the execution should not continue any further. It is not recommended to call this function very often, and try to handle as many errors as possible silently or more gracefully.
As a shorthand, the desired HTTP response code may be passed as an integer to the $title parameter (the default title would apply) or the $args parameter.
Since
2.0.4
4.1.0 The $title and $args parameters were changed to optionally accept an integer to be used as the response code.
Parameters
string | WP_Error $message Optional. Error message. If this is a {
See also
WP_Error} object, the error's messages are used. Default empty.
Parameters
string | int $title Optional. Error title. If $message is a WP_Error object, error data with the key 'title' may be used to specify the title. If $title is an integer, then it is treated as the response code. Default empty.
string | array | int $args { Optional. Arguments to control behavior. If $args is an integer, then it is treated as the response code. Default empty array.
int $response The HTTP response code. Default 500. bool $back_link Whether to include a link to go back. Default false. string $text_direction The text direction. This is only useful internally, when WordPress is still loading and the site's locale is not set up yet. Accepts 'rtl'. Default is the value of {
See also
is_rtl()}. }
Filter callback for killing WordPress execution for AJAX requests.
Since
3.4.0
Parameters
callable $function Callback function name.
Filter callback for killing WordPress execution for XML-RPC requests.
Since
3.4.0
Parameters
callable $function Callback function name.
Filter callback for killing WordPress execution for all non-AJAX, non-XML-RPC requests.
Since
3.0.0
Parameters
callable $function Callback function name.
Definition at line 2477 of file wordpress/wp-includes/functions.php.
References $message, $title, apply_filters(), DOING_AJAX, elseif, and XMLRPC_REQUEST.
Referenced by WP_Terms_List_Table\__construct(), File_Upload_Upgrader\__construct(), _access_denied_splash(), _show_post_preview(), _wp_ajax_add_hierarchical_term(), Custom_Image_Header\admin_page(), WP_Customize_Nav_Menus\ajax_load_available_items(), WP_Customize_Nav_Menus\ajax_search_available_items(), wpdb\bail(), bulk_edit_posts(), check_comment_flood_db(), check_upload_size(), confirm_delete_users(), dead_db(), do_feed(), edit_comment(), edit_link(), edit_post(), edit_user(), GFExport\export_form_page(), GFExport\export_lead_page(), GFExport\import_form_page(), install_plugin_information(), install_theme_information(), maybe_add_existing_user_to_blog(), ms_not_installed(), ms_site_check(), WP_Theme_Install_List_Table\prepare_items(), wpdb\print_error(), GFFormDisplay\process_send_resume_link(), retrieve_password(), GravityView_Admin_Duplicate_View\save_as_new_view(), WP_Ajax_Response\send(), signup_nonce_check(), Custom_Image_Header\step_2(), Custom_Image_Header\step_2_manage_upload(), Custom_Image_Header\step_3(), twentyfifteen_customize(), twentyfifteen_preview(), twentyfourteen_customize(), twentyfourteen_preview(), twentythirteen_customize(), twentythirteen_preview(), GFUpdate\update_page(), validate_file_to_edit(), wp_ajax_add_link_category(), wp_ajax_add_menu_item(), wp_ajax_add_meta(), wp_ajax_add_tag(), wp_ajax_add_user(), wp_ajax_ajax_tag_search(), wp_ajax_autocomplete_user(), wp_ajax_closed_postboxes(), wp_ajax_dashboard_widgets(), wp_ajax_date_format(), wp_ajax_delete_comment(), wp_ajax_delete_inactive_widgets(), wp_ajax_delete_link(), wp_ajax_delete_meta(), wp_ajax_delete_page(), wp_ajax_delete_post(), wp_ajax_delete_tag(), wp_ajax_dim_comment(), wp_ajax_dismiss_wp_pointer(), wp_ajax_edit_comment(), wp_ajax_fetch_list(), wp_ajax_get_comments(), wp_ajax_get_permalink(), wp_ajax_get_tagcloud(), wp_ajax_hidden_columns(), wp_ajax_image_editor(), wp_ajax_imgedit_preview(), wp_ajax_inline_save(), wp_ajax_inline_save_tax(), wp_ajax_logged_in(), wp_ajax_menu_get_metabox(), wp_ajax_menu_locations_save(), wp_ajax_menu_quick_search(), wp_ajax_meta_box_order(), wp_ajax_oembed_cache(), wp_ajax_replyto_comment(), wp_ajax_sample_permalink(), wp_ajax_save_widget(), wp_ajax_set_post_thumbnail(), wp_ajax_time_format(), wp_ajax_trash_post(), wp_ajax_update_welcome_panel(), WP_Customize_Widgets\wp_ajax_update_widget(), wp_ajax_upload_attachment(), wp_ajax_widgets_order(), wp_ajax_wp_compression_test(), wp_ajax_wp_link_ajax(), wp_ajax_wp_remove_post_lock(), wp_allow_comment(), wp_link_manager_disabled_message(), wp_media_attach_action(), wp_nonce_ays(), wp_not_installed(), wp_protect_special_option(), wp_send_json(), wp_set_wpdb_vars(), wpmu_checkAvailableSpace(), and write_post().
wp_ext2type ($ext)
Retrieve the file type based on the extension name.
Since
2.5.0
Parameters
string $ext The extension to search.
Returns
string|void The file type, example: audio, video, document, spreadsheet, etc.
Filter file type based on the extension name.
Since
2.5.0
See also
wp_ext2type()
Parameters
array $ext2type Multi-dimensional array with extensions for a default set of file types.
Definition at line 2119 of file wordpress/wp-includes/functions.php.
References apply_filters().
Referenced by wp_ajax_send_link_to_editor(), wp_media_upload_handler(), and wp_mime_type_icon().
wp_extract_urls ($content)
Use RegEx to extract URLs from arbitrary content.
Since
3.7.0
Parameters
string $content Content to extract URLs from.
Returns
array URLs found in passed string.
Definition at line 516 of file wordpress/wp-includes/functions.php.
References $content.
Referenced by do_enclose(), and pingback().
wp_filter_object_list ($list, $args = array(), $operator = 'and', $field = false)
Filters a list of objects, based on a set of key => value arguments.
Since
3.0.0
Parameters
array $list An array of objects to filter
array $args Optional. An array of key => value arguments to match against each object. Default empty array.
string $operator Optional. The logical operation to perform. 'or' means only one element from the array needs to match; 'and' means all elements must match; 'not' means no elements may match. Default 'and'.
bool | string $field A field from the object to place instead of the entire object. Default false.
Returns
array A list of objects or object fields.
Definition at line 3318 of file wordpress/wp-includes/functions.php.
References $field, $list, wp_list_filter(), and wp_list_pluck().
Referenced by WP_Media_List_Table\get_columns(), WP_Posts_List_Table\get_columns(), get_post_stati(), get_post_types(), get_taxonomies(), and GFFormDisplay\update_confirmation().
wp_find_hierarchy_loop ($callback, $start, $start_parent, $callback_args = array())
Find hierarchy loops using a callback function that maps object IDs to parent IDs.
Since
3.1.0 private
Parameters
callable $callback Function that accepts (ID, $callback_args) and outputs parent_ID.
int $start The ID to start the loop check at.
int $start_parent The parent_ID of $start to use instead of calling $callback($start). Use null to always use $callback
array $callback_args Optional. Additional arguments to send to $callback.
Returns
array IDs of all members of loop.
Definition at line 4658 of file wordpress/wp-includes/functions.php.
References wp_find_hierarchy_loop_tortoise_hare().
Referenced by wp_check_post_hierarchy_for_loops(), and wp_check_term_hierarchy_for_loops().
wp_find_hierarchy_loop_tortoise_hare ($callback, $start, $override = array(), $callback_args = array(), $_return_loop = false)
Use the "The Tortoise and the Hare" algorithm to detect loops.
For every step of the algorithm, the hare takes two steps and the tortoise one. If the hare ever laps the tortoise, there must be a loop.
Since
3.1.0 private
Parameters
callable $callback Function that accepts (ID, callback_arg, ...) and outputs parent_ID.
int $start The ID to start the loop check at.
array $override Optional. An array of (ID => parent_ID, ...) to use instead of $callback. Default empty array.
array $callback_args Optional. Additional arguments to send to $callback. Default empty array.
bool $_return_loop Optional. Return loop members or just detect presence of loop? Only set to true if you already know the given $start is part of a loop (otherwise the returned array might include branches). Default false.
Returns
mixed Scalar ID of some arbitrary member of the loop, or array of IDs of all members of loop if $_return_loop
Definition at line 4687 of file wordpress/wp-includes/functions.php.
Referenced by wp_find_hierarchy_loop().
wp_get_http_headers ($url, $deprecated = false)
Retrieve HTTP Headers from URL.
Since
1.5.1
Parameters
string $url URL to retrieve HTTP headers from.
bool $deprecated Not Used.
Returns
bool|string False on failure, headers on success.
Definition at line 638 of file wordpress/wp-includes/functions.php.
References $deprecated, $url, _deprecated_argument(), is_wp_error(), wp_remote_retrieve_headers(), and wp_safe_remote_head().
Referenced by do_enclose().
wp_get_mime_types ()
Retrieve list of mime types and file extensions.
Since
3.5.0
4.2.0 Support was added for GIMP (xcf) files.
Returns
array Array of mime types keyed by the file extension regex corresponding to those types.
Filter the list of mime types and file extensions.
This filter should be used to add, not remove, mime types. To remove mime types, use the 'upload_mimes' filter.
Since
3.5.0
Parameters
array $wp_get_mime_types Mime types keyed by the file extension regex corresponding to those types.
Definition at line 2274 of file wordpress/wp-includes/functions.php.
References apply_filters().
Referenced by do_enclose(), get_allowed_mime_types(), WP_Image_Editor\get_extension(), WP_Image_Editor\get_mime_type(), wp_audio_shortcode(), wp_playlist_shortcode(), and wp_video_shortcode().
wp_get_nocache_headers ()
Get the header information to prevent caching.
The several different headers cover the different ways cache prevention is handled by different browsers
Since
2.8.0
Returns
array The associative array of header names and field values.
Filter the cache-controlling headers.
Since
2.8.0
See also
wp_get_nocache_headers()
Parameters
array $headers { Header names and field values.
string $Expires Expires header. string $Cache-Control Cache-Control header. string $Pragma Pragma header. }
Definition at line 1096 of file wordpress/wp-includes/functions.php.
References apply_filters().
Referenced by nocache_headers(), WP\send_headers(), WP_REST_Server\serve_request(), Tests_REST_Server\test_no_nocache_headers_on_unauthenticated_requests(), and Tests_REST_Server\test_nocache_headers_on_authenticated_requests().
wp_get_original_referer ()
Retrieve original referer that was posted, if it exists.
Since
2.0.4
Returns
string|false False if no original referer or original referer if set.
Definition at line 1562 of file wordpress/wp-includes/functions.php.
References wp_unslash().
Referenced by wp_original_referer_field().
wp_get_raw_referer ()
Retrieve unvalidated referer from '_wp_http_referer' or HTTP referer.
Do not use for redirects, use wp_get_referer() instead.
Since
4.5.0
Returns
string|bool Referer URL on success, false on failure.
Definition at line 1545 of file wordpress/wp-includes/functions.php.
References $_SERVER, and wp_unslash().
Referenced by wp_get_referer().
wp_get_referer ()
Retrieve referer from '_wp_http_referer' or HTTP referer.
If it's the same as the current request URL, will return false.
Since
2.0.4
Returns
false|string False on failure. Referer URL on success.
Definition at line 1522 of file wordpress/wp-includes/functions.php.
References $_SERVER, home_url(), wp_get_raw_referer(), and wp_unslash().
Referenced by WP_Terms_List_Table\column_name(), WP_Customize_Manager\get_return_url(), WP_Terms_List_Table\handle_row_actions(), set_screen_options(), wp_media_attach_action(), wp_nonce_ays(), and wp_original_referer_field().
wp_guess_url ()
Guess the URL for the site.
Will remove wp-admin links to retrieve only return URLs not in the wp-admin directory.
Since
2.6.0
Returns
string The guessed URL.
Definition at line 3987 of file wordpress/wp-includes/functions.php.
References $_SERVER, $path, $url, ABSPATH, elseif, is_ssl(), and str_replace.
wp_is_numeric_array ($data)
Determines if the variable is a numeric-indexed array.
Since
4.4.0
Parameters
mixed $data Variable to check.
Returns
bool Whether the variable is a list.
Definition at line 3292 of file wordpress/wp-includes/functions.php.
References $keys.
Referenced by WP_REST_Server\response_to_data().
wp_is_stream ($path)
Test if a given path is a stream URL.
Parameters
string $path The resource path or URL.
Returns
bool True if the path is a stream URL.
Definition at line 4862 of file wordpress/wp-includes/functions.php.
References $path.
Referenced by WP_Image_Editor\make_image(), WP_Image_Editor_GD\make_image(), and wp_mkdir_p().
wp_is_writable ($path)
Determine if a directory is writable.
This function is used to work around certain ACL issues in PHP primarily affecting Windows Servers.
Since
3.6.0
See also
win_is_writable()
Parameters
string $path Path to check for write-ability.
Returns
bool Whether the path is writable.
Definition at line 1761 of file wordpress/wp-includes/functions.php.
References $path, and win_is_writable().
Referenced by get_temp_dir(), and WP_Http\request().
wp_json_encode ($data, $options = 0, $depth = 512)
Encode a variable into JSON, with some sanity checks.
Since
4.1.0
Parameters
mixed $data Variable (usually an array or object) to encode as JSON.
int $options Optional. Options to be passed to json_encode(). Default 0.
int $depth Optional. Maximum depth to walk through $data. Must be greater than 0. Default 512.
Returns
string|false The JSON encoded string, or false if it cannot be encoded.
Definition at line 2784 of file wordpress/wp-includes/functions.php.
References $options, _wp_json_prepare_data(), _wp_json_sanity_check(), and elseif.
Referenced by WP_Themes_List_Table\_js_vars(), WP_List_Table\_js_vars(), _wp_ajax_menu_quick_search(), _wp_customize_loader_settings(), WP_List_Table\ajax_response(), WP_Customize_Manager\customize_pane_settings(), WP_Customize_Manager\customize_preview_settings(), _WP_Editors\editor_settings(), WP_Customize_Nav_Menus\enqueue_scripts(), WP_Customize_Widgets\enqueue_scripts(), WP_Customize_Nav_Menus\export_preview_data(), WP_Customize_Widgets\export_preview_data(), get_shortcut_link(), WP_Press_This\html(), WP_REST_Server\json_error(), WP_Scripts\localize(), media_send_to_editor(), media_upload_form(), options_general_add_js(), print_emoji_detection_script(), WP_Internal_Pointers\print_js(), Tests_REST_Request\request_with_parameters(), WP_REST_Server\serve_request(), Tests_REST_Server\test_json_error_with_status(), Tests_REST_Request\test_parameters_for_json_post(), Tests_REST_Request\test_parameters_for_json_put(), Tests_REST_Server\test_rest_error(), wp_ajax_autocomplete_user(), wp_ajax_image_editor(), wp_ajax_menu_get_metabox(), wp_ajax_upload_attachment(), wp_ajax_wp_link_ajax(), wp_color_scheme_settings(), _WP_Editors\wp_mce_translation(), wp_playlist_shortcode(), wp_plupload_default_settings(), wp_send_json(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
wp_list_filter ($list, $args = array(), $operator = 'AND')
Filters a list of objects, based on a set of key => value arguments.
Since
3.1.0
Parameters
array $list An array of objects to filter.
array $args Optional. An array of key => value arguments to match against each object. Default empty array.
string $operator Optional. The logical operation to perform. 'AND' means all elements from the array must match. 'OR' means only one element needs to match. 'NOT' means no elements may match. Default 'AND'.
Returns
array Array of found values.
Definition at line 3344 of file wordpress/wp-includes/functions.php.
References $count, and $list.
Referenced by _access_denied_splash(), GravityView_Widget_Search\get_field_label(), WP_Query\get_queried_object(), WP_REST_Response\remove_link(), WP_Automatic_Updater\send_debug_email(), and wp_filter_object_list().
wp_list_pluck ($list, $field, $index_key = null)
Pluck a certain field out of each object in a list.
This has the same functionality and prototype of array_column() (PHP 5.5) but also supports objects.
Since
3.1.0
4.0.0 $index_key parameter added.
Parameters
array $list List of objects or arrays
int | string $field Field from the object to place instead of the entire object
int | string $index_key Optional. Field from the object to use as keys for the new array. Default null.
Returns
array Array of found values. If $index_key is set, an array of found values with keys corresponding to $index_key. If $index_key is null, array keys from the original $list will be preserved in the results.
Definition at line 3391 of file wordpress/wp-includes/functions.php.
References $field, $list, and $value.
Referenced by WP_Post\__get(), WP_Media_List_Table\display_rows(), WP_Comment_Query\fill_descendants(), GravityView_Field_List\get_column_label(), GravityView_Widget_Search\get_field_label(), get_inline_data(), GravityView_Admin_View_Item\get_item_info(), get_post_galleries_images(), get_terms(), WP_Comments_List_Table\prepare_items(), WP_Http\request(), WP_Automatic_Updater\send_debug_email(), WP_Widget_Recent_Comments\widget(), wp_delete_term(), wp_enqueue_media(), wp_filter_object_list(), wp_get_object_terms(), wp_insert_term(), and wp_prepare_revisions_for_js().
wp_maybe_decline_date ($date)
Determines if the date should be declined.
If the locale specifies that month names require a genitive case in certain formats (like 'j F Y'), the month name will be replaced with a correct form.
Since
4.4.0
Parameters
string $date Formatted date string.
Returns
string The date, declined if locale specifies it.
Definition at line 172 of file wordpress/wp-includes/functions.php.
References $locale, $wp_locale, _x, and get_locale().
wp_maybe_load_widgets ()
Determines if Widgets library should be loaded.
Checks to make sure that the widgets library hasn't already been loaded. If it hasn't, then it will load the widgets library and run an action hook.
Since
2.2.0
Filter whether to load the Widgets library.
Passing a falsey value to the filter will effectively short-circuit the Widgets library from loading.
Since
2.8.0
Parameters
bool $wp_maybe_load_widgets Whether to load the Widgets library. Default true.
Definition at line 3439 of file wordpress/wp-includes/functions.php.
References ABSPATH, add_action(), apply_filters(), and WPINC.
wp_mkdir_p ($target)
Recursive directory creation based on full path.
Will attempt to set permissions on folders.
Since
2.0.1
Parameters
string $target Full path to attempt to create.
Returns
bool Whether the path was created. True if path already exists.
Definition at line 1578 of file wordpress/wp-includes/functions.php.
References $i, null, str_replace, and wp_is_stream().
Referenced by _copy_image_file(), GFFormsModel\copy_post_image(), GF_Field_CAPTCHA\get_captcha(), GFFormsModel\get_file_upload_path(), GF_Field_CAPTCHA\get_math_captcha(), WP_Image_Editor\make_image(), GFAsyncUpload\upload(), GFFormDisplay\upload_files(), wp_crop_image(), wp_upload_bits(), and wp_upload_dir().
wp_nonce_ays ($action)
Display "Are You Sure" message to confirm the action being taken.
If the action has the nonce explain message, then it will be displayed along with the "Are you sure?" message.
Since
2.0.4
Parameters
string $action The nonce action.
Definition at line 2430 of file wordpress/wp-includes/functions.php.
References $action, __, esc_url, get_bloginfo(), remove_query_arg(), wp_die(), wp_get_referer(), and wp_logout_url().
wp_nonce_field ($action = -1, $name = "_wpnonce", $referer = true, $echo = true)
Retrieve or display nonce hidden field for forms.
The nonce field is used to validate that the contents of the form came from the location on the current site and not somewhere else. The nonce does not offer absolute protection, but should protect against most cases. It is very important to use nonce field in forms.
The $action and $name are optional, but if you want to have better security, it is strongly suggested to set those two parameters. It is easier to just call the function without any parameters, because validation of the nonce doesn't require any parameters, but since crackers know what the default is it won't be difficult for them to find a way around your nonce and cause damage.
The input name will be whatever $name value you gave. The input value will be the nonce creation value.
Since
2.0.4
Parameters
int | string $action Optional. Action name. Default -1.
string $name Optional. Nonce name. Default '_wpnonce'.
bool $referer Optional. Whether to set the referer field for validation. Default true.
bool $echo Optional. Whether to display or return hidden form field. Default true.
Returns
string Nonce field HTML markup.
Definition at line 1457 of file wordpress/wp-includes/functions.php.
References $action, $name, $referer, esc_attr(), and wp_referer_field().
Referenced by _list_meta_row(), _wp_dashboard_control_callback(), admin_color_scheme_picker(), confirm_delete_users(), GFFormSettings\confirmations_list_page(), GF_Installation_Wizard\display(), WP_Post_Comments_List_Table\display(), WP_Themes_List_Table\display(), WP_Theme_Install_List_Table\display(), WP_Comments_List_Table\display(), WP_List_Table\display_tablenav(), GravityView_Edit_Entry_Render\edit_entry_form(), GFExport\export_form_page(), GFExport\export_lead_page(), WP_Comments_List_Table\extra_tablenav(), GFFeedAddOn\feed_list_page(), find_posts_div(), GFFormSettings\form_settings_ui(), GFFormDisplay\gform_footer(), WP_Press_This\html(), GFExport\import_form_page(), WP_Terms_List_Table\inline_edit(), WP_Posts_List_Table\inline_edit(), install_plugins_upload(), install_themes_upload(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), link_categories_meta_box(), list_core_update(), list_plugin_updates(), list_theme_updates(), list_translation_updates(), media_upload_library_form(), media_upload_type_form(), media_upload_type_url_form(), meta_form(), network_step1(), post_categories_meta_box(), post_comment_meta_box(), WP_Screen\render_screen_options(), GFAddOn\render_settings(), GravityView_Admin_Metaboxes\render_view_configuration_metabox(), GFFormDisplay\replace_save_variables(), settings_fields(), signup_nonce_fields(), Custom_Image_Header\step_1(), Custom_Image_Header\step_2(), wp_comment_form_unfiltered_html_nonce(), wp_comment_reply(), wp_dashboard(), wp_dashboard_quick_press(), and _WP_Editors\wp_link_dialog().
wp_nonce_url ($actionurl, $action = -1, $name = '_wpnonce')
Retrieve URL with nonce added to URL query.
Since
2.0.4
Parameters
string $actionurl URL to add nonce action.
int | string $action Optional. Nonce action name. Default -1.
string $name Optional. Nonce name. Default '_wpnonce'.
Returns
string Escaped URL with nonce action added.
Definition at line 1426 of file wordpress/wp-includes/functions.php.
References $action, $name, add_query_arg(), esc_html, and str_replace.
Referenced by WP_Media_List_Table\_get_row_actions(), GFForms\addons_page(), Plugin_Upgrader_Skin\after(), GravityView_Compatibility\check_gravityforms(), WP_MS_Themes_List_Table\column_name(), delete_plugins(), delete_theme(), WP_Themes_List_Table\display_rows(), GFAutoUpgrade\display_updates(), do_core_upgrade(), do_dismiss_core_update(), do_undismiss_core_update(), GravityView_Delete_Entry\get_delete_link(), get_delete_post_link(), get_media_item(), get_theme_update_available(), WP_Links_List_Table\handle_row_actions(), WP_Terms_List_Table\handle_row_actions(), WP_MS_Users_List_Table\handle_row_actions(), WP_MS_Sites_List_Table\handle_row_actions(), WP_Posts_List_Table\handle_row_actions(), install_plugin_install_status(), WP_Theme_Install_List_Table\install_theme_info(), GFEntryList\leads_page(), WP_Upgrader_Skin\request_filesystem_credentials(), WP_Theme_Install_List_Table\single_row(), WP_Users_List_Table\single_row(), WP_Plugins_List_Table\single_row(), GFUpdate\update_page(), wp_logout_url(), wp_plugin_update_row(), wp_prepare_revisions_for_js(), wp_prepare_themes_for_js(), and wp_theme_update_row().
wp_normalize_path ($path)
Normalize a filesystem path.
On windows systems, replaces backslashes with forward slashes and forces upper-case drive letters. Ensures that no duplicate slashes exist.
Since
3.9.0
4.4.0 Ensures upper-case drive letters on Windows systems.
Parameters
string $path Path to normalize.
Returns
string Normalized path.
Definition at line 1698 of file wordpress/wp-includes/functions.php.
References $path, and str_replace.
Referenced by plugin_basename(), plugins_url(), and wp_register_plugin_realpath().
wp_ob_end_flush_all ()
Flush all output buffers for PHP 5.2.
Make sure all output buffers are flushed before our singletons are destroyed.
Since
2.2.0
Definition at line 3484 of file wordpress/wp-includes/functions.php.
References $i.
Referenced by show_message().
wp_original_referer_field ($echo = true, $jump_back_to = 'current')
Retrieve or display original referer hidden field for forms.
The input name is '_wp_original_http_referer' and will be either the same value of wp_referer_field(), if that was posted already or it will be the current page, if it doesn't exist.
Since
2.0.4
Parameters
bool $echo Optional. Whether to echo the original http referer. Default true.
string $jump_back_to Optional. Can be 'previous' or page you want to jump back to. Default 'current'.
Returns
string Original referer field.
Definition at line 1503 of file wordpress/wp-includes/functions.php.
References $_SERVER, esc_attr(), wp_get_original_referer(), wp_get_referer(), and wp_unslash().
wp_parse_args ($args, $defaults = '')
Merge user defined arguments into defaults array.
This function is used throughout WordPress to allow for both string or array to be merged into another array.
Since
2.2.0
Parameters
string | array $args Value to merge with $defaults
array $defaults Optional. Array that serves as the defaults. Default empty.
Returns
array Merged user defined values with defaults.
Definition at line 3238 of file wordpress/wp-includes/functions.php.
References elseif, and wp_parse_str().
Referenced by GravityView_Default_Template_List\__construct(), WP_Upgrader_Skin\__construct(), GravityView_FieldType\__construct(), GravityView_Image\__construct(), GravityView_Admin_View_Item\__construct(), WP_List_Table\__construct(), GravityView_View\__construct(), WP_Widget\__construct(), Plugin_Upgrader_Skin\__construct(), Bulk_Upgrader_Skin\__construct(), _default_wp_die_handler(), wp_xmlrpc_server\_insert_post(), GravityView_Support_Port\_localize_script(), _register_widget_form_callback(), _walk_bookmarks(), _xmlrpc_wp_die_handler(), WP_Ajax_Response\add(), GFFormsModel\add_default_properties(), WP_Screen\add_help_tab(), GravityView_Extension\add_metabox_tab(), WP_Admin_Bar\add_node(), GravityView_Entry_Notes\add_note(), WP_Rewrite\add_permastruct(), GFSettings\add_settings_page(), add_theme_support(), GravityView_View_Data\add_view(), Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), Language_Pack_Upgrader\bulk_upgrade(), GVCommon\calculate_get_entries_criteria(), comment_form(), GV_UnitTest_Factory_For_View\create_object(), GF_UnitTest_Factory_For_Entry\create_object(), GF_UnitTest_Factory_For_Form\create_object(), WP_Widget\display_callback(), WP_Terms_List_Table\display_rows_or_placeholder(), export_wp(), feed_links(), feed_links_extra(), WP_oEmbed\fetch(), WP_User_Query\fill_query_vars(), WP_Widget_Search\form(), WP_Widget_Calendar\form(), WP_Widget_Text\form(), WP_Widget_Meta\form(), WP_Widget_Links\form(), WP_Widget_Pages\form(), GravityView_Search_WP_Widget\form(), WP_Widget_Categories\form(), WP_Widget_Archives\form(), GravityView_Recent_Entries_Widget\form(), WP_Widget\form_callback(), GVCommon\format_date(), WP_Http\get(), GVCommon\get_all_views(), get_approved_comments(), get_avatar_data(), get_bookmarks(), get_categories(), WP_Comment\get_children(), get_children(), get_comment_link(), get_comment_reply_link(), get_compat_media_markup(), GVCommon\get_connected_views(), get_custom_header(), GravityView_Widget_Poll\get_frontend_settings(), get_gravityview(), get_header_image_tag(), GravityView_View_Data\get_id_from_atts(), GFFormsModel\get_leads_where_sql(), GVCommon\get_link_html(), get_media_item(), get_objects_in_term(), get_page_of_comment(), get_pages(), get_post_reply_link(), get_posts(), get_posts_nav_link(), WP_REST_Server\get_routes(), Featured_Content\get_setting(), GVCommon\get_template_settings(), get_terms(), get_the_comments_navigation(), get_the_comments_pagination(), get_the_post_navigation(), get_the_posts_navigation(), get_the_posts_pagination(), get_the_taxonomies(), get_users(), GVCommon\get_users(), gravityview_field_output(), gravityview_get_terms_choices(), WP_Http\head(), Plugin_Upgrader\install(), Theme_Upgrader\install(), WP_Upgrader\install_package(), GravityView_Template\merge_defaults(), GravityView_Migrate\migrate_redux_settings(), paginate_comments_links(), paginate_links(), WP_Comment_Query\parse_query(), WP_Query\parse_query(), _WP_Editors\parse_settings(), WP_Http\post(), post_categories_meta_box(), post_tags_meta_box(), GFPaymentAddOn\process_callback_action(), WP_Comment_Query\query(), WP_Query\query(), register_post_status(), register_post_type(), register_sidebar(), register_taxonomy(), GravityView_Admin_Views\render_active_areas(), GravityView_Admin_Views\render_additional_fields(), WP_Screen\render_screen_options(), GravityView_frontend\render_view(), WP_Http_Streams\request(), WP_Http_Curl\request(), WP_Http\request(), Gravity_Api\request(), WP_Upgrader\run(), WP_List_Table\set_pagination_args(), WP_Screen\set_screen_reader_content(), GravityView_View\setCurrentField(), WP_Embed\shortcode(), GFAddOn\single_section(), the_taxonomies(), the_title_attribute(), the_widget(), twentyfifteen_get_color_scheme_css(), WP_Widget_Search\update(), GravityView_Search_WP_Widget\update(), WP_Widget_Archives\update(), Plugin_Upgrader\upgrade(), Theme_Upgrader\upgrade(), Core_Upgrader\upgrade(), wp_ajax_query_themes(), wp_count_terms(), wp_delete_term(), wp_dropdown_categories(), wp_dropdown_languages(), wp_dropdown_pages(), wp_dropdown_users(), wp_enqueue_media(), wp_generate_tag_cloud(), wp_get_archives(), wp_get_attachment_image(), wp_get_links(), wp_get_linksbyname(), wp_get_nav_menu_items(), wp_get_nav_menus(), wp_get_object_terms(), wp_get_post_categories(), wp_get_post_revisions(), wp_get_post_terms(), wp_get_recent_posts(), wp_get_sites(), wp_get_themes(), wp_http_supports(), wp_insert_attachment(), wp_insert_category(), wp_insert_link(), wp_insert_post(), wp_insert_term(), wp_link_pages(), wp_list_authors(), wp_list_bookmarks(), wp_list_categories(), wp_list_cats(), wp_list_comments(), wp_list_pages(), wp_login_form(), wp_nav_menu(), wp_page_menu(), wp_register_sidebar_widget(), wp_register_widget_control(), wp_star_rating(), wp_tag_cloud(), wp_terms_checklist(), wp_update_nav_menu_item(), wp_update_term(), wp_widget_rss_form(), wp_widget_rss_output(), and wpmu_create_blog().
wp_parse_id_list ($list)
Clean up an array, comma- or space-separated list of IDs.
Since
3.0.0
Parameters
array | string $list List of ids.
Returns
array Sanitized array of IDs.
Definition at line 3259 of file wordpress/wp-includes/functions.php.
References $list.
Referenced by WP_Comment_Query\get_comment_ids(), get_pages(), get_posts(), get_terms(), WP_User_Query\parse_orderby(), WP_User_Query\prepare_query(), wp_get_sites(), and wp_list_categories().
wp_post_preview_js ()
Outputs a small JS snippet on preview tabs/windows to remove window.name on unload.
This prevents reusing the same tab for a preview when the user has navigated away.
Since
4.3.0
Definition at line 5153 of file wordpress/wp-includes/functions.php.
References $name, $post, false, and is_preview().
wp_referer_field ($echo = true)
Retrieve or display referer hidden field for forms.
The referer link is the current Request URI from the server super global. The input name is '_wp_http_referer', in case you wanted to check manually.
Since
2.0.4
Parameters
bool $echo Optional. Whether to echo or return the referer field. Default true.
Returns
string Referer field HTML markup.
Definition at line 1481 of file wordpress/wp-includes/functions.php.
References $_SERVER, esc_attr(), and wp_unslash().
Referenced by WP_Plugin_Install_List_Table\display_tablenav(), and wp_nonce_field().
wp_remote_fopen ($uri)
HTTP request for URI to retrieve content.
Since
1.5.1
See also
wp_safe_remote_get()
Parameters
string $uri URI/URL of web page to retrieve.
Returns
false|string HTTP content. False on failure.
Definition at line 922 of file wordpress/wp-includes/functions.php.
References $options, is_wp_error(), wp_remote_retrieve_body(), and wp_safe_remote_get().
wp_removable_query_args ()
Returns an array of single-use query variable names that can be removed from a URL.
Since
4.4.0
Returns
array An array of parameters to remove from the URL.
Filter the list of query variables to remove.
Since
4.2.0
Parameters
array $removable_query_args An array of query variables to remove from a URL.
Definition at line 858 of file wordpress/wp-includes/functions.php.
References apply_filters().
Referenced by WP_Customize_Manager\set_return_url(), and wp_admin_canonical_url().
wp_scheduled_delete ()
Permanently delete comments or posts of any type that have held a status of 'trash' for the number of days defined in EMPTY_TRASH_DAYS.
The default value of EMPTY_TRASH_DAYS is 30 (days).
Since
2.9.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 4424 of file wordpress/wp-includes/functions.php.
References $comment, $post, $post_id, $wpdb, ARRAY_A, delete_comment_meta(), delete_post_meta(), get_comment(), get_post(), wp_delete_comment(), and wp_delete_post().
wp_send_json ($response)
Send a JSON response back to an Ajax request.
Since
3.5.0
Parameters
mixed $response Variable (usually an array or object) to encode as JSON, then print and die.
Definition at line 2972 of file wordpress/wp-includes/functions.php.
References DOING_AJAX, get_option(), wp_die(), and wp_json_encode().
Referenced by wp_ajax_heartbeat(), wp_ajax_nopriv_heartbeat(), wp_send_json_error(), and wp_send_json_success().
wp_send_json_error ($data = null)
Send a JSON response back to an Ajax request, indicating failure.
If the $data parameter is a {
See also
WP_Error} object, the errors within the object are processed and output as an array of error codes and corresponding messages. All other types are output without further processing.
Since
3.5.0
4.1.0 The $data parameter is now processed if a {
See also
WP_Error} object is passed in.
Parameters
mixed $data Data to encode as JSON, then print and die.
Definition at line 3011 of file wordpress/wp-includes/functions.php.
References $message, $messages, is_wp_error(), and wp_send_json().
Referenced by WP_Press_This\add_category(), Custom_Image_Header\ajax_header_add(), Custom_Image_Header\ajax_header_crop(), Custom_Image_Header\ajax_header_remove(), WP_Customize_Nav_Menus\ajax_load_available_items(), WP_Customize_Nav_Menus\ajax_search_available_items(), WP_Customize_Manager\refresh_nonces(), WP_Customize_Nav_Menus\render_menu(), WP_Customize_Manager\save(), WP_Press_This\save_post(), wp_ajax_crop_image(), wp_ajax_destroy_sessions(), wp_ajax_find_posts(), wp_ajax_get_attachment(), wp_ajax_get_revision_diffs(), wp_ajax_heartbeat(), wp_ajax_parse_embed(), wp_ajax_parse_media_shortcode(), wp_ajax_query_attachments(), wp_ajax_query_themes(), wp_ajax_save_attachment(), wp_ajax_save_attachment_compat(), wp_ajax_save_attachment_order(), wp_ajax_save_user_color_scheme(), wp_ajax_save_wporg_username(), wp_ajax_send_attachment_to_editor(), wp_ajax_send_link_to_editor(), wp_ajax_set_attachment_thumbnail(), wp_ajax_update_plugin(), WP_Customize_Widgets\wp_ajax_update_widget(), and wp_ajax_wp_fullscreen_save_post().
wp_send_json_success ($data = null)
Send a JSON response back to an Ajax request, indicating success.
Since
3.5.0
Parameters
mixed $data Data to encode as JSON, then print and die.
Definition at line 2988 of file wordpress/wp-includes/functions.php.
References wp_send_json().
Referenced by WP_Press_This\add_category(), Custom_Image_Header\ajax_header_add(), Custom_Image_Header\ajax_header_crop(), Custom_Image_Header\ajax_header_remove(), WP_Customize_Nav_Menus\ajax_load_available_items(), WP_Customize_Nav_Menus\ajax_search_available_items(), WP_Customize_Manager\refresh_nonces(), WP_Customize_Nav_Menus\render_menu(), WP_Customize_Manager\save(), WP_Press_This\save_post(), wp_ajax_crop_image(), wp_ajax_destroy_sessions(), wp_ajax_find_posts(), wp_ajax_generate_password(), wp_ajax_get_attachment(), wp_ajax_get_revision_diffs(), wp_ajax_parse_embed(), wp_ajax_parse_media_shortcode(), wp_ajax_query_attachments(), wp_ajax_query_themes(), wp_ajax_save_attachment(), wp_ajax_save_attachment_compat(), wp_ajax_save_attachment_order(), wp_ajax_save_user_color_scheme(), wp_ajax_save_wporg_username(), wp_ajax_send_attachment_to_editor(), wp_ajax_send_link_to_editor(), wp_ajax_set_attachment_thumbnail(), wp_ajax_set_post_thumbnail(), wp_ajax_update_plugin(), WP_Customize_Widgets\wp_ajax_update_widget(), and wp_ajax_wp_fullscreen_save_post().
wp_suspend_cache_addition ($suspend = null)
Temporarily suspend cache additions.
Stops more data being added to the cache, but still allows cache retrieval. This is useful for actions, such as imports, when a lot of data would otherwise be almost uselessly added to the cache.
Suspension lasts for a single page load at most. Remember to call this function again if you wish to re-enable cache adds earlier.
Since
3.3.0
bool $_suspend
Parameters
bool $suspend Optional. Suspends additions if true, re-enables them if false.
Returns
bool The current suspend setting
Definition at line 4043 of file wordpress/wp-includes/functions.php.
Referenced by WP_Object_Cache\add(), WP_Widget\display_callback(), and WP_Widget\update_callback().
wp_suspend_cache_invalidation ($suspend = true)
Suspend cache invalidation.
Turns cache invalidation on and off. Useful during imports where you don't wont to do invalidations every time a post is inserted. Callers must be sure that what they are doing won't lead to an inconsistent cache when invalidation is suspended.
Since
2.7.0
bool $_wp_suspend_cache_invalidation
Parameters
bool $suspend Optional. Whether to suspend or enable cache invalidation. Default true.
Returns
bool The current suspend setting.
Definition at line 4066 of file wordpress/wp-includes/functions.php.
wp_timezone_choice ($selected_zone)
Gives a nicely-formatted list of timezone strings.
Since
2.9.0
bool $mo_loaded
Parameters
string $selected_zone Selected timezone.
Returns
string
Definition at line 4278 of file wordpress/wp-includes/functions.php.
References $label, $locale, $value, __, esc_attr(), esc_attr__(), esc_html, get_locale(), load_textdomain(), str_replace, and translate().
wp_timezone_override_offset ()
gmt_offset modification for smart timezone handling.
Overrides the gmt_offset option if we have a timezone_string available.
Since
2.8.0
Returns
float|false Timezone GMT offset, false otherwise.
Definition at line 4207 of file wordpress/wp-includes/functions.php.
References get_option().
wp_unique_filename ($dir, $filename, $unique_filename_callback = null)
Get a filename that is sanitized and unique for the given directory.
If the filename is not unique, then a number will be added to the filename before the extension, and will continue adding numbers until the filename is unique.
The callback is passed three parameters, the first one is the directory, the second is the filename, and the third is the extension.
Since
2.5.0
Parameters
string $dir Directory.
string $filename File name.
callable $unique_filename_callback Callback. Default null.
Returns
string New filename, if given wasn't unique.
Definition at line 1972 of file wordpress/wp-includes/functions.php.
References $dir, $name, sanitize_file_name(), and str_replace.
Referenced by _copy_image_file(), _wp_handle_upload(), GFFormsModel\copy_post_image(), WP_Http\request(), wp_crop_image(), wp_tempnam(), and wp_upload_bits().
wp_upload_bits ($name, $deprecated, $bits, $time = null)
Create a file in the upload folder with given content.
If there is an error, then the key 'error' will exist with the error message. If success, then the key 'file' will have the unique file path, the 'url' key will have the link to the new file. and the 'error' key will be set to false.
This function will not move an uploaded file to the upload folder. It will create a new file with the content in $bits parameter. If you move the upload file, read the content of the uploaded file, and then you can give the filename and content to this function, which will add it to the upload folder.
The permissions will be set on the new file automatically by this function.
Since
2.0.0
Parameters
string $name Filename.
null | string $deprecated Never used. Set to null.
mixed $bits File content
string $time Optional. Time formatted in 'yyyy/mm'. Default null.
Returns
array
Filter whether to treat the upload bits as an error.
Passing a non-array to the filter will effectively short-circuit preparing the upload bits, returning that value instead.
Since
3.0.0
Parameters
mixed $upload_bits_error An array of upload bits data, or a non-array error to return.
This filter is documented in wp-admin/includes/file.php
Definition at line 2044 of file wordpress/wp-includes/functions.php.
References $deprecated, $message, $name, $url, __, _deprecated_argument(), ABSPATH, apply_filters(), current_user_can(), str_replace, wp_check_filetype(), wp_mkdir_p(), wp_unique_filename(), and wp_upload_dir().
Referenced by WP_UnitTest_Factory_For_Attachment\create_upload_object(), wp_xmlrpc_server\mw_newMediaObject(), and wp_generate_attachment_metadata().
wp_upload_dir ($time = null)
Get an array containing the current upload directory's path and url.
Checks the 'upload_path' option, which should be from the web root folder, and if it isn't empty it will be used. If it is empty, then the path will be 'WP_CONTENT_DIR/uploads'. If the 'UPLOADS' constant is defined, then it will override the 'upload_path' option and 'WP_CONTENT_DIR/uploads' path.
The upload URL path is set either by the 'upload_url_path' option or by using the 'WP_CONTENT_URL' constant and appending '/uploads' to the path.
If the 'uploads_use_yearmonth_folders' is set to true (checkbox if checked in the administration settings panel), then the time will be used. The format will be year first and then month.
If the path couldn't be created, then an error will be returned with the key 'error' containing the error message. The error suggests that the parent directory is not writable by the server.
On success, the returned array will have many indices: 'path' - base directory and sub directory or full path to upload directory. 'url' - base url and sub directory or absolute URL to upload directory. 'subdir' - sub directory if uploads use year/month folders option is on. 'basedir' - path without subdir. 'baseurl' - URL path without subdir. 'error' - set to false.
Since
2.0.0
Parameters
string $time Optional. Time formatted in 'yyyy/mm'. Default null.
Returns
array See above for description.
Filter the uploads directory data.
Since
2.0.0
Parameters
array $uploads Array of upload directory data with keys of 'path', 'url', 'subdir, 'basedir', and 'error'.
Definition at line 1834 of file wordpress/wp-includes/functions.php.
References $dir, $message, $url, __, ABSPATH, apply_filters(), current_time(), elseif, get_current_blog_id(), get_option(), get_site_option(), is_main_network(), is_main_site(), is_multisite(), ms_is_switched(), path_join(), str_replace, trailingslashit(), untrailingslashit(), WP_CONTENT_DIR, and wp_mkdir_p().
Referenced by File_Upload_Upgrader\__construct(), _wp_handle_upload(), _wp_relative_upload_path(), _wp_upload_dir_baseurl(), attachment_url_to_postid(), GFFormsModel\copy_post_image(), discover_pingback_server_uri(), get_attached_file(), get_space_used(), GFFormsModel\get_upload_root(), GFFormsModel\get_upload_url(), GFFormsModel\get_upload_url_root(), GFForms\heal_wp_upload_dir(), WP_UnitTestCase\remove_added_uploads(), WP_UnitTestCase\scan_user_uploads(), wp_delete_attachment(), wp_get_attachment_url(), wp_import_upload_form(), wp_upload_bits(), and wpmu_delete_blog().
wp_validate_boolean ($var)
Filter/validate a variable as a boolean.
Alternative to filter_var($var, FILTER_VALIDATE_BOOLEAN).
Since
4.0.0
Parameters
mixed $var Boolean value to validate.
Returns
bool Whether the value is validated.
Definition at line 5113 of file wordpress/wp-includes/functions.php.
Referenced by wp_xmlrpc_server\_toggle_sticky(), wp_audio_shortcode(), wp_playlist_shortcode(), and wp_video_shortcode().
wp_widgets_add_menu ()
Append the Widgets menu to the themes main menu.
Since
2.2.0
array $submenu
Definition at line 3467 of file wordpress/wp-includes/functions.php.
References $submenu, __, and current_theme_supports().
xmlrpc_getpostcategory ($content)
Retrieve the post category or categories from XMLRPC XML.
If the category element is not found, then the default post category will be used. The return type then would be what $post_default_category. If the category is found, then it will always be an array.
Since
0.71
string $post_default_category Default XML-RPC post category.
Parameters
string $content XMLRPC XML Request content
Returns
string|array List of categories or category name.
Definition at line 482 of file wordpress/wp-includes/functions.php.
References $content.
Referenced by wp_xmlrpc_server\blogger_editPost(), and wp_xmlrpc_server\blogger_newPost().
xmlrpc_getposttitle ($content)
Retrieve post title from XMLRPC XML.
If the title element is not part of the XML, then the default post title from the $post_default_title will be used instead.
Since
0.71
string $post_default_title Default XML-RPC post title.
Parameters
string $content XMLRPC XML Request content
Returns
string Post title
Definition at line 458 of file wordpress/wp-includes/functions.php.
References $content, $post_default_title, and $post_title.
Referenced by wp_xmlrpc_server\blogger_editPost(), and wp_xmlrpc_server\blogger_newPost().
xmlrpc_removepostdata ($content)
XMLRPC XML content without title and category elements.
Since
0.71
Parameters
string $content XML-RPC XML Request content.
Returns
string XMLRPC XML Request content without title and category elements.
Definition at line 501 of file wordpress/wp-includes/functions.php.
References $content.
Referenced by wp_xmlrpc_server\blogger_editPost(), and wp_xmlrpc_server\blogger_newPost().
Variable Documentation
height __pad10__
Definition at line 2651 of file wordpress/wp-includes/functions.php.
margin __pad11__
Definition at line 2652 of file wordpress/wp-includes/functions.php.
padding __pad12__
Definition at line 2653 of file wordpress/wp-includes/functions.php.
cursor __pad13__
Definition at line 2654 of file wordpress/wp-includes/functions.php.
padding __pad14__
Definition at line 2671 of file wordpress/wp-includes/functions.php.
button __pad15__
Definition at line 2674 of file wordpress/wp-includes/functions.php.
color __pad16__
Definition at line 2678 of file wordpress/wp-includes/functions.php.
button __pad17__
Definition at line 2682 of file wordpress/wp-includes/functions.php.
button __pad18__
Definition at line 2689 of file wordpress/wp-includes/functions.php.
transform __pad19__
Definition at line 2695 of file wordpress/wp-includes/functions.php.
margin __pad3__
Definition at line 2617 of file wordpress/wp-includes/functions.php.
a __pad4__
Definition at line 2629 of file wordpress/wp-includes/functions.php.
a __pad5__
Definition at line 2634 of file wordpress/wp-includes/functions.php.
outline __pad6__
Definition at line 2641 of file wordpress/wp-includes/functions.php.
border __pad7__
Definition at line 2645 of file wordpress/wp-includes/functions.php.
color __pad8__
Definition at line 2646 of file wordpress/wp-includes/functions.php.
display __pad9__
Definition at line 2647 of file wordpress/wp-includes/functions.php.
a a
Initial value:
{
            color: #0073aa
Definition at line 2626 of file wordpress/wp-includes/functions.php.
vertical align
Definition at line 2665 of file wordpress/wp-includes/functions.php.
webkit appearance
Definition at line 2656 of file wordpress/wp-includes/functions.php.
button button
Initial value:
{
            background: #f7f7f7
Definition at line 2643 of file wordpress/wp-includes/functions.php.
Referenced by twentyfifteen_get_color_scheme_css().
border color
Definition at line 2677 of file wordpress/wp-includes/functions.php.
Referenced by _default_wp_die_handler().
text decoration
Definition at line 2648 of file wordpress/wp-includes/functions.php.
if ('rtl'==$text_direction) endif
Definition at line 2699 of file wordpress/wp-includes/functions.php.
font family
Definition at line 2620 of file wordpress/wp-includes/functions.php.
Referenced by _default_wp_die_handler().
line height
Definition at line 2616 of file wordpress/wp-includes/functions.php.
button button large
Initial value:
{
            height: 30px
Definition at line 2668 of file wordpress/wp-includes/functions.php.
ul li
Initial value:
{
            margin-bottom: 10px
Definition at line 2622 of file wordpress/wp-includes/functions.php.
Referenced by WP_Admin_Bar\_render_item(), _wp_menu_output(), confirm_delete_users(), WP_Customize_Nav_Menu_Control\content_template(), WP_Customize_Nav_Menus_Panel\content_template(), WP_Customize_Panel\content_template(), CreatePlaceholdersUI(), WP_Themes_List_Table\display_rows(), do_accordion_sections(), GFExport\export_form_page(), GFExport\export_lead_page(), GravityView_Welcome\getting_started_screen(), GFHelp\help_page(), WP_Press_This\html(), install_themes_dashboard(), GFEntryDetail\lead_detail_grid(), GFEntryDetail\lead_detail_page(), GFEntryList\leads_page(), link_categories_meta_box(), network_step2(), GFSettings\page_header(), GFExport\page_header(), page_header(), post_categories_meta_box(), WP_Customize_Nav_Menus\print_templates(), WP_Customize_New_Menu_Section\render(), WP_Customize_Themes_Section\render(), WP_Customize_Control\render(), WP_Screen\render_screen_meta(), WP_Customize_Panel\render_template(), WP_Customize_Section\render_template(), WP_Theme_Install_List_Table\single_row(), Walker_Nav_Menu_Edit\start_el(), GFForms\top_toolbar(), twentyfifteen_get_color_scheme_css(), WP_Widget_Recent_Posts\widget(), WP_Widget_Meta\widget(), Twenty_Eleven_Ephemera_Widget\widget(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_dashboard_right_now(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_item_taxonomy_meta_box(), and wp_popular_terms_checklist().
font Monaco
Definition at line 2620 of file wordpress/wp-includes/functions.php.
font monospace
Definition at line 2620 of file wordpress/wp-includes/functions.php.
webkit box box outline
Definition at line 2683 of file wordpress/wp-includes/functions.php.
Referenced by print_embed_styles(), WP_Customize_Widgets\print_preview_css(), twentyfifteen_get_color_scheme_css(), and wp_print_media_templates().
border radius
Definition at line 2655 of file wordpress/wp-includes/functions.php.
Referenced by print_embed_styles(), and GFSelectColumns\select_columns_page().
webkit box box shadow
Definition at line 2636 of file wordpress/wp-includes/functions.php.
Referenced by _default_wp_die_handler(), print_embed_styles(), print_emoji_styles(), and WP_Customize_Widgets\print_preview_css().
font size
Definition at line 2615 of file wordpress/wp-includes/functions.php.
box sizing
Definition at line 2659 of file wordpress/wp-includes/functions.php.
white space
Definition at line 2658 of file wordpress/wp-includes/functions.php.
Referenced by GFEntryList\leads_page(), and print_embed_styles().
ms transform
Definition at line 2691 of file wordpress/wp-includes/functions.php.
Referenced by print_embed_styles().