GravityView: compat.php File Reference
wordpress/wp-includes/compat.php File Reference
Namespaces
PHP
WordPress implementation for PHP functions either missing from older PHP versions or not included by default.
Functions
_hash_hmac ($algo, $data, $key, $raw_output=false)
Internal compat function to mimic hash_hmac().
_mb_strlen ($str, $encoding=null)
Internal compat function to mimic mb_strlen().
_mb_substr ($str, $start, $length=null, $encoding=null)
Internal compat function to mimic mb_substr().
if(!function_exists('_')) _wp_can_use_pcre_u ($set=null)
Returns whether PCRE/u (PCRE_UTF8 modifier) is available for use.
Variables
if(!function_exists('mb_substr'))($str, $start, $length=null, $encoding=null) endif
Function Documentation
_hash_hmac ($algo, $data, $key, $raw_output = false)
Internal compat function to mimic hash_hmac().
Since
3.2.0
Parameters
string $algo Hash algorithm. Accepts 'md5' or 'sha1'.
string $data Data to be hashed.
string $key Secret key to use for generating the hash.
bool $raw_output Optional. Whether to output raw binary data (true), or lowercase hexits (false). Default false.
Returns
string|false The hash in output determined by $raw_output. False if $algo is unknown or invalid.
Services_JSON $wp_json
Parameters
string $string
bool $assoc_array
Returns
object|array
Parameters
object $data
Returns
array
JsonSerializable interface.
Compatibility shim for PHP <5.4
4.4.0
Definition at line 255 of file wordpress/wp-includes/compat.php.
_mb_strlen ($str, $encoding = null)
Internal compat function to mimic mb_strlen().
Only understands UTF-8 and 8bit. All other character sets will be treated as 8bit. For $encoding === UTF-8, the $str input is expected to be a valid UTF-8 byte sequence. The behavior of this function for invalid inputs is undefined.
Since
4.2.0
Parameters
string $str The string to retrieve the character length from.
string | null $encoding Optional. Character encoding to use. Default null.
Returns
int String length of $str.
Definition at line 166 of file wordpress/wp-includes/compat.php.
References $count, _wp_can_use_pcre_u(), get_option(), and null.
Referenced by Services_JSON\__construct(), and Services_JSON\strlen8().
_mb_substr ($str, $start, $length = null, $encoding = null)
Internal compat function to mimic mb_substr().
Only understands UTF-8 and 8bit. All other character sets will be treated as 8bit. For $encoding === UTF-8, the $str input is expected to be a valid UTF-8 byte sequence. The behavior of this function for invalid inputs is undefined.
Since
3.2.0
Parameters
string $str The string to extract the substring from.
int $start Position to being extraction from in $str.
int | null $length Optional. Maximum number of characters to extract from $str. Default null.
string | null $encoding Optional. Character encoding to use. Default null.
Returns
string Extracted substring.
Definition at line 82 of file wordpress/wp-includes/compat.php.
References _wp_can_use_pcre_u(), get_option(), and null.
Referenced by Services_JSON\__construct(), and Services_JSON\substr8().
if (!function_exists('_')) _wp_can_use_pcre_u ($set = null)
Returns whether PCRE/u (PCRE_UTF8 modifier) is available for use.
Since
4.2.2 private
string $utf8_pcre
Parameters
bool $set - Used for testing only null : default - get PCRE/u capability false : Used for testing - return false for future calls to this function 'reset': Used for testing - restore default behavior of this function
Definition at line 30 of file wordpress/wp-includes/compat.php.
References null.
Referenced by _mb_strlen(), and _mb_substr().
Variable Documentation
if (!defined('JSON_PRETTY_PRINT'))if (! function_exists('json_last_error_msg')) () endif
Definition at line 44 of file wordpress/wp-includes/compat.php.