GravityView: http.php File Reference
wordpress/wp-includes/http.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_http_get_object ()
Returns the initialized WP_Http Object.
allowed_http_request_hosts ($is_external, $host)
Whitelists allowed redirect hosts for safe HTTP requests as well.
get_allowed_http_origins ()
Retrieve list of allowed HTTP origins.
get_http_origin ()
Get the HTTP Origin of the current request.
is_allowed_http_origin ($origin=null)
Determines if the HTTP origin is an authorized one.
ms_allowed_http_request_hosts ($is_external, $host)
Whitelists any domain in a multisite installation for safe HTTP requests.
send_origin_headers ()
Send Access-Control-Allow-Origin and related headers if the current request is from an allowed origin.
wp_http_supports ($capabilities=array(), $url=null)
Determines if there is an HTTP Transport that can process this request.
wp_http_validate_url ($url)
Validate a URL for safe use in the HTTP API.
wp_parse_url ($url)
A wrapper for PHP's parse_url() function that handles edgecases in < PHP 5.4.7.
wp_remote_get ($url, $args=array())
Retrieve the raw response from the HTTP request using the GET method.
wp_remote_head ($url, $args=array())
Retrieve the raw response from the HTTP request using the HEAD method.
wp_remote_post ($url, $args=array())
Retrieve the raw response from the HTTP request using the POST method.
wp_remote_request ($url, $args=array())
Retrieve the raw response from the HTTP request.
wp_remote_retrieve_body ($response)
Retrieve only the body from the raw response.
wp_remote_retrieve_cookie ($response, $name)
Retrieve a single cookie by name from the raw response.
wp_remote_retrieve_cookie_value ($response, $name)
Retrieve a single cookie's value by name from the raw response.
wp_remote_retrieve_cookies ($response)
Retrieve only the cookies from the raw response.
wp_remote_retrieve_header ($response, $header)
Retrieve a single header by name from the raw response.
wp_remote_retrieve_headers ($response)
Retrieve only the headers from the raw response.
wp_remote_retrieve_response_code ($response)
Retrieve only the response code from the raw response.
wp_remote_retrieve_response_message ($response)
Retrieve only the response message from the raw response.
wp_safe_remote_get ($url, $args=array())
Retrieve the raw response from a safe HTTP request using the GET method.
wp_safe_remote_head ($url, $args=array())
Retrieve the raw response from a safe HTTP request using the HEAD method.
wp_safe_remote_post ($url, $args=array())
Retrieve the raw response from a safe HTTP request using the POST method.
wp_safe_remote_request ($url, $args=array())
Retrieve the raw response from a safe HTTP request.
Function Documentation
_wp_http_get_object ()
Returns the initialized WP_Http Object.
Since
2.7.0 private
WP_Http $http
Returns
WP_Http HTTP Transport object.
Definition at line 22 of file wordpress/wp-includes/http.php.
References null.
Referenced by wp_http_supports(), wp_remote_get(), wp_remote_head(), wp_remote_post(), wp_remote_request(), wp_safe_remote_get(), wp_safe_remote_head(), wp_safe_remote_post(), and wp_safe_remote_request().
allowed_http_request_hosts ($is_external, $host)
Whitelists allowed redirect hosts for safe HTTP requests as well.
Attached to the http_request_host_is_external filter.
Since
3.6.0
Parameters
bool $is_external
string $host
Returns
bool
Definition at line 585 of file wordpress/wp-includes/http.php.
get_allowed_http_origins ()
Retrieve list of allowed HTTP origins.
Since
3.4.0
Returns
array Array of origin URLs.
Change the origin types allowed for HTTP requests.
Since
3.4.0
Parameters
array $allowed_origins { Default allowed HTTP origins. string Non-secure URL for admin origin. string Secure URL for admin origin. string Non-secure URL for home origin. string Secure URL for home origin. }
Definition at line 412 of file wordpress/wp-includes/http.php.
References admin_url(), apply_filters(), and home_url().
Referenced by is_allowed_http_origin().
get_http_origin ()
Get the HTTP Origin of the current request.
Since
3.4.0
Returns
string URL of the origin. Empty string if no origin.
Change the origin of an HTTP request.
Since
3.4.0
Parameters
string $origin The original origin for the request.
Definition at line 390 of file wordpress/wp-includes/http.php.
References $_SERVER, and apply_filters().
Referenced by is_allowed_http_origin(), rest_send_cors_headers(), and send_origin_headers().
is_allowed_http_origin ($origin = null)
Determines if the HTTP origin is an authorized one.
Since
3.4.0
Parameters
null | string $origin Origin URL. If not provided, the value of get_http_origin() is used.
Returns
string True if the origin is allowed. False otherwise.
Change the allowed HTTP origin result.
Since
3.4.0
Parameters
string $origin Result of check for allowed origin.
string $origin_arg Original origin string passed into is_allowed_http_origin function.
Definition at line 448 of file wordpress/wp-includes/http.php.
References apply_filters(), get_allowed_http_origins(), get_http_origin(), and null.
Referenced by send_origin_headers().
ms_allowed_http_request_hosts ($is_external, $host)
Whitelists any domain in a multisite installation for safe HTTP requests.
Attached to the http_request_host_is_external filter.
Since
3.6.0
wpdb $wpdb WordPress database abstraction object. array $queried
Parameters
bool $is_external
string $host
Returns
bool
Definition at line 605 of file wordpress/wp-includes/http.php.
References $wpdb, and get_current_site().
send_origin_headers ()
Send Access-Control-Allow-Origin and related headers if the current request is from an allowed origin.
If the request is an OPTIONS request, the script exits with either access control headers sent, or a 403 response if the origin is not allowed. For other request methods, you will receive a return value.
Since
3.4.0
Returns
string|false Returns the origin URL if headers are sent. Returns false if headers are not sent.
Definition at line 481 of file wordpress/wp-includes/http.php.
References $_SERVER, exit, get_http_origin(), is_allowed_http_origin(), and status_header().
Referenced by WP_Customize_Manager\setup_theme().
wp_http_supports ($capabilities = array(), $url = null)
Determines if there is an HTTP Transport that can process this request.
Since
3.2.0
Parameters
array $capabilities Array of capabilities to test or a wp_remote_request() $args array.
string $url Optional. If given, will check if the URL requires SSL and adds that requirement to the capabilities array.
Returns
bool
Definition at line 361 of file wordpress/wp-includes/http.php.
References $count, $url, _wp_http_get_object(), and wp_parse_args().
Referenced by core_upgrade_preamble(), get_core_checksums(), plugins_api(), themes_api(), translations_api(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
wp_http_validate_url ($url)
Validate a URL for safe use in the HTTP API.
Since
3.5.2
Parameters
string $url
Returns
false|string URL or false on failure.
Check if HTTP request is external or not.
Allows to change and allow external requests for the HTTP request.
Since
3.6.0
Parameters
bool false Whether HTTP request is external or not.
string $host IP of the requested host.
string $url URL of the requested host.
Definition at line 508 of file wordpress/wp-includes/http.php.
References $url, apply_filters(), get_option(), and wp_kses_bad_protocol().
Referenced by pingback_ping_source_uri(), and WP_Http\request().
wp_parse_url ($url)
A wrapper for PHP's parse_url() function that handles edgecases in < PHP 5.4.7.
PHP 5.4.7 expanded parse_url()'s ability to handle non-absolute url's, including schemeless and relative url's with :// in the path, this works around those limitations providing a standard output on PHP 5.2~5.4+.
Error suppression is used as prior to PHP 5.3.3, an E_WARNING would be generated when URL parsing failed.
Since
4.4.0
Parameters
string $url The URL to parse.
Returns
bool|array False on failure; Array of URL components on success; See parse_url()'s return values.
Definition at line 634 of file wordpress/wp-includes/http.php.
References $url.
Referenced by esc_url(), WP_Http\make_absolute_url(), and WP_Http\parse_url().
wp_remote_get ($url, $args = array())
Retrieve the raw response from the HTTP request using the GET method.
Since
2.7.0
See also
wp_remote_request() For more information on the response array format.
WP_Http::request() For default arguments information.
Parameters
string $url Site URL to retrieve.
array $args Optional. Request arguments. Default empty array.
Returns
WP_Error|array The response or WP_Error on failure.
Definition at line 168 of file wordpress/wp-includes/http.php.
References $url, and _wp_http_get_object().
Referenced by GV_License_Handler\_license_get_remote_response(), get_core_checksums(), network_step2(), populate_network(), url_is_accessable_via_ssl(), wp_credits(), wp_get_popular_importers(), and wp_install_maybe_enable_pretty_permalinks().
wp_remote_head ($url, $args = array())
Retrieve the raw response from the HTTP request using the HEAD method.
Since
2.7.0
See also
wp_remote_request() For more information on the response array format.
WP_Http::request() For default arguments information.
Parameters
string $url Site URL to retrieve.
array $args Optional. Request arguments. Default empty array.
Returns
WP_Error|array The response or WP_Error on failure.
Definition at line 202 of file wordpress/wp-includes/http.php.
References $url, and _wp_http_get_object().
wp_remote_post ($url, $args = array())
Retrieve the raw response from the HTTP request using the POST method.
Since
2.7.0
See also
wp_remote_request() For more information on the response array format.
WP_Http::request() For default arguments information.
Parameters
string $url Site URL to retrieve.
array $args Optional. Request arguments. Default empty array.
Returns
WP_Error|array The response or WP_Error on failure.
Definition at line 185 of file wordpress/wp-includes/http.php.
References $url, and _wp_http_get_object().
Referenced by plugins_api(), WP_HTTP_IXR_Client\query(), spawn_cron(), themes_api(), translations_api(), update_core(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
wp_remote_request ($url, $args = array())
Retrieve the raw response from the HTTP request.
The array structure is a little complex:
$res = array(
    'headers'  => array(),
    'response' => array(
        'code'    => int,
        'message' => string
    )
);
All of the headers in $res['headers'] are with the name as the key and the value as the value. So to get the User-Agent, you would do the following.
$user_agent = $res['headers']['user-agent'];
The body is the raw response content and can be retrieved from $res['body'].
This function is called first to make the request and there are other API functions to abstract out the above convoluted setup.
Request method defaults for helper functions:
Default 'GET' for wp_remote_get()
Default 'POST' for wp_remote_post()
Default 'HEAD' for wp_remote_head()
Since
2.7.0
See also
WP_Http::request() For additional information on default arguments.
Parameters
string $url Site URL to retrieve.
array $args Optional. Request arguments. Default empty array.
Returns
WP_Error|array The response or WP_Error on failure.
Definition at line 151 of file wordpress/wp-includes/http.php.
References $url, and _wp_http_get_object().
Referenced by WP_Http\handle_redirects(), and Gravity_Api\request().
wp_remote_retrieve_body ($response)
Retrieve only the body from the raw response.
Since
2.7.0
Parameters
array $response HTTP response.
Returns
string The body of the response. Empty string if no body or incorrect parameter given.
Definition at line 283 of file wordpress/wp-includes/http.php.
References is_wp_error().
Referenced by WP_SimplePie_File\__construct(), _fetch_remote_file(), WP_oEmbed\_fetch_with_format(), GV_License_Handler\_license_get_remote_response(), WP_oEmbed\discover(), discover_pingback_server_uri(), WP_Press_This\fetch_source_html(), get_core_checksums(), network_step2(), wp_xmlrpc_server\pingback_ping(), plugins_api(), WP_HTTP_IXR_Client\query(), themes_api(), translations_api(), wp_credits(), wp_get_http(), wp_get_popular_importers(), wp_remote_fopen(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
wp_remote_retrieve_cookie ($response, $name)
Retrieve a single cookie by name from the raw response.
Since
4.4.0
Parameters
array $response HTTP response.
string $name The name of the cookie to retrieve.
Returns
WP_Http_Cookie|string The WP_Http_Cookie object. Empty string if the cookie isn't present in the response.
Definition at line 315 of file wordpress/wp-includes/http.php.
References $name, and wp_remote_retrieve_cookies().
Referenced by wp_remote_retrieve_cookie_value().
wp_remote_retrieve_cookie_value ($response, $name)
Retrieve a single cookie's value by name from the raw response.
Since
4.4.0
Parameters
array $response HTTP response.
string $name The name of the cookie to retrieve.
Returns
string The value of the cookie. Empty string if the cookie isn't present in the response.
Definition at line 340 of file wordpress/wp-includes/http.php.
References $name, and wp_remote_retrieve_cookie().
wp_remote_retrieve_cookies ($response)
Retrieve only the cookies from the raw response.
Since
4.4.0
Parameters
array $response HTTP response.
Returns
array An array of WP_Http_Cookie objects from the response. Empty array if there are none, or the response is a WP_Error.
Definition at line 298 of file wordpress/wp-includes/http.php.
References is_wp_error().
Referenced by wp_remote_retrieve_cookie().
wp_remote_retrieve_header ($response, $header)
Retrieve a single header by name from the raw response.
Since
2.7.0
Parameters
array $response
string $header Header name to retrieve value from.
Returns
string The header value. Empty string on if incorrect parameter given, or if the header doesn't exist.
Definition at line 231 of file wordpress/wp-includes/http.php.
References is_wp_error().
Referenced by discover_pingback_server_uri(), download_url(), and wp_install_maybe_enable_pretty_permalinks().
wp_remote_retrieve_headers ($response)
Retrieve only the headers from the raw response.
Since
2.7.0
Parameters
array $response HTTP response.
Returns
array The headers of the response. Empty array if incorrect parameter given.
Definition at line 215 of file wordpress/wp-includes/http.php.
References is_wp_error().
Referenced by WP_SimplePie_File\__construct(), _fetch_remote_file(), wp_get_http(), and wp_get_http_headers().
wp_remote_retrieve_response_code ($response)
Retrieve only the response code from the raw response.
Will return an empty array if incorrect parameter value is given.
Since
2.7.0
Parameters
array $response HTTP response.
Returns
int|string The response code as an integer. Empty string on incorrect parameter given.
Definition at line 251 of file wordpress/wp-includes/http.php.
References is_wp_error().
Referenced by WP_SimplePie_File\__construct(), _fetch_remote_file(), WP_oEmbed\_fetch_with_format(), download_url(), get_core_checksums(), populate_network(), WP_HTTP_IXR_Client\query(), url_is_accessable_via_ssl(), wp_credits(), wp_get_http(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
wp_remote_retrieve_response_message ($response)
Retrieve only the response message from the raw response.
Will return an empty array if incorrect parameter value is given.
Since
2.7.0
Parameters
array $response HTTP response.
Returns
string The response message. Empty string on incorrect parameter given.
Definition at line 268 of file wordpress/wp-includes/http.php.
References is_wp_error().
Referenced by download_url().
wp_safe_remote_get ($url, $args = array())
Retrieve the raw response from a safe HTTP request using the GET method.
This function is ideal when the HTTP request is being made to an arbitrary URL. The URL is validated to avoid redirection and request forgery attacks.
Since
3.6.0
See also
wp_remote_request() For more information on the response array format.
WP_Http::request() For default arguments information.
Parameters
string $url Site URL to retrieve.
array $args Optional. Request arguments. Default empty array.
Returns
WP_Error|array The response or WP_Error on failure.
Definition at line 67 of file wordpress/wp-includes/http.php.
References $url, and _wp_http_get_object().
Referenced by WP_oEmbed\_fetch_with_format(), WP_oEmbed\discover(), discover_pingback_server_uri(), download_url(), WP_Press_This\fetch_source_html(), wp_xmlrpc_server\pingback_ping(), and wp_remote_fopen().
wp_safe_remote_head ($url, $args = array())
Retrieve the raw response from a safe HTTP request using the HEAD method.
This function is ideal when the HTTP request is being made to an arbitrary URL. The URL is validated to avoid redirection and request forgery attacks.
Since
3.6.0
See also
wp_remote_request() For more information on the response array format.
WP_Http::request() For default arguments information.
Parameters
string $url Site URL to retrieve.
array $args Optional. Request arguments. Default empty array.
Returns
WP_Error|array The response or WP_Error on failure.
Definition at line 109 of file wordpress/wp-includes/http.php.
References $url, and _wp_http_get_object().
Referenced by discover_pingback_server_uri(), and wp_get_http_headers().
wp_safe_remote_post ($url, $args = array())
Retrieve the raw response from a safe HTTP request using the POST method.
This function is ideal when the HTTP request is being made to an arbitrary URL. The URL is validated to avoid redirection and request forgery attacks.
Since
3.6.0
See also
wp_remote_request() For more information on the response array format.
WP_Http::request() For default arguments information.
Parameters
string $url Site URL to retrieve.
array $args Optional. Request arguments. Default empty array.
Returns
WP_Error|array The response or WP_Error on failure.
Definition at line 88 of file wordpress/wp-includes/http.php.
References $url, and _wp_http_get_object().
Referenced by trackback().
wp_safe_remote_request ($url, $args = array())
Retrieve the raw response from a safe HTTP request.
This function is ideal when the HTTP request is being made to an arbitrary URL. The URL is validated to avoid redirection and request forgery attacks.
Since
3.6.0
See also
wp_remote_request() For more information on the response array format.
WP_Http::request() For default arguments information.
Parameters
string $url Site URL to retrieve.
array $args Optional. Request arguments. Default empty array.
Returns
WP_Error|array The response or WP_Error on failure.
Definition at line 46 of file wordpress/wp-includes/http.php.
References $url, and _wp_http_get_object().
Referenced by WP_SimplePie_File\__construct(), _fetch_remote_file(), WP_Importer\get_page(), and wp_get_http().