GravityView: settings.php File Reference
wordpress/wp-admin/network/settings.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$fieldset_end = ''
Add New page Banned Names illegal_names Users are not allowed to register these sites Separate names by spaces Limited Email Registrations limited_email_domains If you want to limit site registrations to certain domains One domain per line Banned Email Domains banned_email_domains banned_email_domains If you want to ban domains from site registrations One domain per line New Site Settings Welcome Email welcome_email The welcome email sent to new site owners Welcome User Email welcome_user_email The welcome email sent to new users First Post first_post The first post on a new site First Page first_page The first page on a new site First Comment first_comment The first comment on a new site First Comment Author first_comment_author The author of the first comment on a new site First Comment URL first_comment_url The URL for the first comment on a new site Upload Settings Site upload space upload_space_check_disabled Limit total size of files uploaded to s MB</label >< label >< input name="blog_upload_space"type="number"min="0"style="width: 100px"id="blog_upload_space"aria-describedby="blog-upload-space-desc"value="' . esc_attr(get_site_option('blog_upload_space', 100)) . '"/> Size in megabytes Upload file types upload_filetypes jpg jpeg png gif Allowed file types Separate types by spaces Max upload file size s KB File size in kilobytes< input name="fileupload_maxk"type="number"min="0"style="width: 100px"id="fileupload_maxk"aria-describedby="fileupload-maxk-desc"value="' . esc_attr(get_site_option('fileupload_maxk', 300)) . '"/> Size in kilobytes Language Settings Default Language WPLANG name WPLANG id WPLANG selected languages translations show_available_translations Menu Settings Enable administration menus menu_items plugins dashboards **since MU **param array $admin_menus The menu items available * $menu_items = apply_filters('mu_menu_items', array('plugins' => __('Plugins')))
$parent_file = 'settings.php'
$title = __('Network Settings')
_e ('Network Title')?></label ></th >< td >< input name
s options</p >< p > Operational settings has fields for the network &__('Registration settings can disable/enable public signups.If you let others sign up for a site, install spam plugins.Spaces, not commas, should separate names banned as sites for this network.'). '</p >'. '< p >'.__('New site settings are defaults applied when a new site is created in the network.These include welcome email for when a new site or user account is registered and what &__('Upload settings control the size of the uploaded files and the amount of available upload space for each site.You can change the default value for specific sites when you edit a particular site.Allowed file types are also listed(space separated only).'). '</p >'. '< p >'.__('You can set the language and the translation files will be automatically downloaded and installed(available if your filesystem is writable).'). '</p >'. '< p >'.__('Menu setting enables/disables the plugin menus from appearing for non super admins so that only super admins
if(count((array) $menu_items) > 1) foreach ((array) $menu_items as $key=> $val)
if (!current_user_can('manage_network_options')) wp_die(__('You do not have permission to access this page.')
if (isset($_GET['updated']))
s options</p >< p > Operational settings has fields for the network &__('Registration settings can disable/enable public signups.If you let others sign up for a site, install spam plugins.Spaces, not commas, should separate names banned as sites for this network.'). '</p >'. '< p >'.__('New site settings are defaults applied when a new site is created in the network.These include welcome email for when a new site or user account is registered and what &__('Upload settings control the size of the uploaded files and the amount of available upload space for each site.You can change the default value for specific sites when you edit a particular site.Allowed file types are also listed(space separated only).'). '</p >'. '< p >'.__('You can set the language and the translation files will be automatically downloaded and installed(available if your filesystem is writable).'). '</p >'. '< p >'.__('Menu setting enables/disables the plugin menus from appearing for non super admins so that only super not site have access to activate plugins</p >< p > Super admins can no longer be added on the Options screen You must now go to the list of existing users on Network Admin Users and click on Username or the Edit action link below that name This goes to an Edit User page where you can check a box to grant super admin privileges</p >< p >< strong > For more information
Variable Documentation
$fieldset_end = ''
Definition at line 365 of file wordpress/wp-admin/network/settings.php.
Add New page Banned Names illegal_names Users are not allowed to register these sites Separate names by spaces Limited Email Registrations limited_email_domains If you want to limit site registrations to certain domains One domain per line Banned Email Domains banned_email_domains banned_email_domains If you want to ban domains from site registrations One domain per line New Site Settings Welcome Email welcome_email The welcome email sent to new site owners Welcome User Email welcome_user_email The welcome email sent to new users First Post first_post The first post on a new site First Page first_page The first page on a new site First Comment first_comment The first comment on a new site First Comment Author first_comment_author The author of the first comment on a new site First Comment URL first_comment_url The URL for the first comment on a new site Upload Settings Site upload space upload_space_check_disabled Limit total size of files uploaded to s MB</label><label><input name="blog_upload_space" type="number" min="0" style="width: 100px" id="blog_upload_space" aria-describedby="blog-upload-space-desc" value="' . esc_attr(get_site_option('blog_upload_space', 100)) . '" /> Size in megabytes Upload file types upload_filetypes jpg jpeg png gif Allowed file types Separate types by spaces Max upload file size s KB File size in kilobytes<input name="fileupload_maxk" type="number" min="0" style="width: 100px" id="fileupload_maxk" aria-describedby="fileupload-maxk-desc" value="' . esc_attr(get_site_option('fileupload_maxk', 300)) . '" /> Size in kilobytes Language Settings Default Language WPLANG name WPLANG id WPLANG selected languages translations show_available_translations Menu Settings Enable administration menus menu_items plugins dashboards* * since MU* * param array $admin_menus The menu items available* $menu_items = apply_filters('mu_menu_items', array('plugins' => __('Plugins')))
Definition at line 364 of file wordpress/wp-admin/network/settings.php.
Referenced by _wp_menu_item_classes_by_context(), WP_Customize_Nav_Menus\customize_register(), GFForms\format_toolbar_menu_items(), GFForms\get_toolbar_menu_items(), GravityView_Admin_Views\gform_toolbar_menu(), GFForms\toolbar_sub_menu_items(), GFForms\top_toolbar(), wp_ajax_add_menu_item(), wp_get_associated_nav_menu_items(), wp_get_nav_menu_to_edit(), wp_nav_menu(), wp_nav_menu_update_menu_items(), and wp_update_nav_menu_item().
$parent_file = 'settings.php'
Definition at line 23 of file wordpress/wp-admin/network/settings.php.
$title = __('Network Settings')
Definition at line 22 of file wordpress/wp-admin/network/settings.php.
_e('Network Title')?></label ></th >< td >< input name
Initial value:
="site_name" type="text" id="site_name" class="regular-text" value="<?php echo esc_attr($current_site->site_name) ?>" />
                </td>
            </tr>
            <tr>
                <th scope="row"><label for="admin_email"><?php _e( 'Network Admin Email' )
Definition at line 107 of file wordpress/wp-admin/network/settings.php.
Referenced by _local_storage_notice(), WP_Admin_Bar\_render(), admin_color_scheme_picker(), Custom_Background\admin_page(), attachment_submitbox_metadata(), WP_Customize_Nav_Menus\available_items_template(), WP_Press_This\categories_html(), choose_primary_blog(), WP_MS_Themes_List_Table\column_cb(), WP_Comments_List_Table\column_cb(), WP_Posts_List_Table\column_date(), WP_Media_List_Table\column_parent(), WP_Media_List_Table\column_title(), WP_Links_List_Table\column_visible(), Walker_Comment\comment(), comments_popup_link(), confirm_delete_users(), GFFormSettings\confirmations_list_page(), WP_Customize_Nav_Menu_Auto_Add_Control\content_template(), WP_Customize_Nav_Menu_Control\content_template(), WP_Customize_Theme_Control\content_template(), WP_Customize_Nav_Menu_Item_Control\content_template(), WP_Customize_Nav_Menus_Panel\content_template(), WP_Customize_Panel\content_template(), core_upgrade_preamble(), customize_themes_print_templates(), dead_db(), default_password_nag(), GF_Installation_Wizard_Step_Settings\display(), GF_Installation_Wizard_Step_Background_Updates\display(), display_header(), WP_Themes_List_Table\display_rows(), WP_Plugin_Install_List_Table\display_rows(), display_setup_form(), do_accordion_sections(), do_core_upgrade(), edit_form_image_editor(), WP_Users_List_Table\extra_tablenav(), WP_Comments_List_Table\extra_tablenav(), find_posts_div(), WP_Widget_Search\form(), WP_Widget_Calendar\form(), WP_Widget_Text\form(), WP_Widget_Meta\form(), WP_Nav_Menu_Widget\form(), WP_Widget_Links\form(), WP_Widget_Pages\form(), WP_Widget_Recent_Posts\form(), GravityView_Search_WP_Widget\form(), WP_Widget_Categories\form(), WP_Widget_Archives\form(), WP_Widget_Recent_Comments\form(), Twenty_Eleven_Ephemera_Widget\form(), Twenty_Fourteen_Ephemera_Widget\form(), GravityView_Recent_Entries_Widget\form(), GFFormSettings\form_settings_ui(), get_confirmation_ui_settings(), WP_Press_This\html(), Walker_Comment\html5_comment(), iframe_header(), WP_Terms_List_Table\inline_edit(), WP_Posts_List_Table\inline_edit(), install_dashboard(), install_plugins_favorites_form(), install_plugins_upload(), install_search_form(), WP_Theme_Install_List_Table\install_theme_info(), install_theme_search_form(), install_themes_dashboard(), install_themes_upload(), link_advanced_meta_box(), link_categories_meta_box(), link_submit_meta_box(), link_target_meta_box(), link_xfn_meta_box(), list_meta(), list_plugin_updates(), list_theme_updates(), list_translation_updates(), media_upload_form(), media_upload_html_bypass(), media_upload_library_form(), media_upload_type_form(), media_upload_type_url_form(), meta_form(), WP_List_Table\months_dropdown(), network_step1(), network_step2(), WP_Links_List_Table\no_items(), WP_Themes_List_Table\no_items(), WP_MS_Users_List_Table\no_items(), WP_Users_List_Table\no_items(), WP_Theme_Install_List_Table\no_items(), WP_MS_Sites_List_Table\no_items(), WP_Comments_List_Table\no_items(), WP_Media_List_Table\no_items(), WP_MS_Themes_List_Table\no_items(), WP_Plugins_List_Table\no_items(), WP_List_Table\no_items(), WP_Customize_Widgets\output_widget_control_templates(), page_attributes_meta_box(), page_header(), Walker_Comment\ping(), post_author_meta_box(), post_categories_meta_box(), post_comment_meta_box(), post_comment_status_meta_box(), post_custom_meta_box(), post_excerpt_meta_box(), post_format_meta_box(), WP_Press_This\post_formats_html(), post_slug_meta_box(), post_submit_meta_box(), post_trackback_meta_box(), WP_Customize_Header_Image_Control\print_header_image_template(), WP_Customize_Themes_Section\render(), WP_Customize_New_Menu_Control\render_content(), WP_Widget_Area_Customize_Control\render_content(), WP_Customize_Header_Image_Control\render_content(), WP_Screen\render_meta_boxes_preferences(), WP_Screen\render_per_page_options(), WP_Screen\render_screen_layout(), WP_Screen\render_screen_meta(), WP_Customize_Panel\render_template(), WP_Customize_Section\render_template(), WP_Screen\render_view_mode(), request_filesystem_credentials(), GFForms\resend_notifications(), setup_config_display_header(), Custom_Image_Header\show_header_selector(), WP_Theme_Install_List_Table\single_row(), Walker_Nav_Menu_Edit\start_el(), Custom_Image_Header\step_1(), Custom_Image_Header\step_2(), GravityView_Welcome\tabs(), WP_Press_This\tags_html(), WP_Theme_Install_List_Table\theme_installer(), touch_time(), upload_is_user_over_quota(), upload_space_setting(), use_ssl_preference(), GravityView_Support_Port\user_field(), WP_Media_List_Table\views(), WP_Widget_Meta\widget(), wp_auth_check_html(), wp_comment_reply(), wp_comment_trashnotice(), wp_dashboard_quick_press(), wp_iframe(), wp_image_editor(), wp_import_upload_form(), _WP_Editors\wp_link_dialog(), wp_maintenance(), wp_nav_menu_item_link_meta_box(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_item_taxonomy_meta_box(), wp_network_dashboard_right_now(), wp_print_media_templates(), wp_print_revision_templates(), wp_widget_control(), and wp_widget_rss_form().
s options</p><p> Operational settings has fields for the network& __ ('Registration settings can disable/enable public signups.If you let others sign up for a site, install spam plugins.Spaces, not commas, should separate names banned as sites for this network.'). '</p >'. '< p >'.__('New site settings are defaults applied when a new site is created in the network.These include welcome email for when a new site or user account is registered and what& __ ('Upload settings control the size of the uploaded files and the amount of available upload space for each site.You can change the default value for specific sites when you edit a particular site.Allowed file types are also listed(space separated only).'). '</p >'. '< p >'.__('You can set the language and the translation files will be automatically downloaded and installed (available if your filesystem is writable).'). '</p >'. '< p >'.__('Menu setting enables/disables the plugin menus from appearing for non super admins so that only super not site admins new
Definition at line 36 of file wordpress/wp-admin/network/settings.php.
if (count((array) $menu_items) > 1) foreach((array) $menu_items as $key=> $val)
Definition at line 370 of file wordpress/wp-admin/network/settings.php.
if($_POST)
Definition at line 19 of file wordpress/wp-admin/network/settings.php.
if(isset($_GET['updated']))
Definition at line 95 of file wordpress/wp-admin/network/settings.php.
s options</p><p> Operational settings has fields for the network& __ ('Registration settings can disable/enable public signups.If you let others sign up for a site, install spam plugins.Spaces, not commas, should separate names banned as sites for this network.'). '</p >'. '< p >'.__('New site settings are defaults applied when a new site is created in the network.These include welcome email for when a new site or user account is registered and what& __ ('Upload settings control the size of the uploaded files and the amount of available upload space for each site.You can change the default value for specific sites when you edit a particular site.Allowed file types are also listed(space separated only).'). '</p >'. '< p >'.__('You can set the language and the translation files will be automatically downloaded and installed (available if your filesystem is writable).'). '</p >'. '< p >'.__('Menu setting enables/disables the plugin menus from appearing for non super admins so that only super not site have access to activate plugins</p><p> Super admins can no longer be added on the Options screen You must now go to the list of existing users on Network Admin Users and click on Username or the Edit action link below that name This goes to an Edit User page where you can check a box to grant super admin privileges</p><p><strong> For more information new
Definition at line 36 of file wordpress/wp-admin/network/settings.php.