GravityView: functions.php File Reference
wordpress/wp-content/themes/twentyeleven/functions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyeleven_auto_excerpt_more ($more)
Replace "[...]" in the Read More link with an ellipsis.
twentyeleven_body_classes ($classes)
Add two classes to the array of body classes.
twentyeleven_custom_excerpt_more ($output)
Add a pretty "Continue Reading" link to custom post excerpts.
twentyeleven_excerpt_length ($length)
Set the post excerpt length to 40 words.
twentyeleven_footer_sidebar_class ()
Count the number of footer sidebars to enable dynamic classes for the footer.
twentyeleven_get_first_url ()
Return the first link from the post content.
twentyeleven_get_gallery_images ()
Retrieve the IDs for images in a gallery.
twentyeleven_page_menu_args ($args)
Show a home link for the wp_nav_menu() fallback, wp_page_menu().
twentyeleven_url_grabber ()
Return the URL for the first link found in the post content.
twentyeleven_widgets_init ()
Register sidebars and widgetized areas.
Variables
margin __pad17__
padding __pad18__
if(!function_exists('twentyeleven_admin_header_style'))() font Arial
if(!function_exists('twentyeleven_header_style'))() color
text decoration
if(!function_exists('twentyeleven_header_style'))() else
if(!function_exists('twentyeleven_setup'))() endif
if(!function_exists('twentyeleven_admin_header_style'))() font family
line height
if(!function_exists('twentyeleven_admin_header_style'))() font Helvetica
if(!function_exists('twentyeleven_admin_header_style'))() font Nimbus Sans L
if(!function_exists('twentyeleven_admin_header_style'))() font Nimbus Sans sans serif
font size
Function Documentation
twentyeleven_auto_excerpt_more ($more)
Replace "[...]" in the Read More link with an ellipsis.
The "[...]" is appended to automatically generated excerpts.
To override this in a child theme, remove the filter and add your own function tied to the excerpt_more filter hook.
Since
Twenty Eleven 1.0
Parameters
string $more The Read More text.
Returns
The filtered Read More text.
Definition at line 392 of file wordpress/wp-content/themes/twentyeleven/functions.php.
References $more, and is_admin().
twentyeleven_body_classes ($classes)
Add two classes to the array of body classes.
The first is if the site has only had one author with published posts. The second is if a singular post being displayed
Since
Twenty Eleven 1.0
Parameters
array $classes Existing body classes.
Returns
array The filtered array of body classes.
Definition at line 692 of file wordpress/wp-content/themes/twentyeleven/functions.php.
References is_home(), is_multi_author(), is_page_template(), and is_singular().
twentyeleven_custom_excerpt_more ($output)
Add a pretty "Continue Reading" link to custom post excerpts.
To override this link in a child theme, remove the filter and add your own function tied to the get_the_excerpt filter hook.
Since
Twenty Eleven 1.0
Parameters
string $output The "Continue Reading" link.
Returns
string The filtered "Continue Reading" link.
Definition at line 411 of file wordpress/wp-content/themes/twentyeleven/functions.php.
References $output, has_excerpt(), is_admin(), and is_attachment().
twentyeleven_excerpt_length ($length)
Set the post excerpt length to 40 words.
To override this length in a child theme, remove the filter and add your own function tied to the excerpt_length filter hook.
Since
Twenty Eleven 1.0
Parameters
int $length The number of excerpt characters.
Returns
int The filtered number of characters.
Definition at line 361 of file wordpress/wp-content/themes/twentyeleven/functions.php.
twentyeleven_footer_sidebar_class ()
Count the number of footer sidebars to enable dynamic classes for the footer.
Since
Twenty Eleven 1.0
Definition at line 557 of file wordpress/wp-content/themes/twentyeleven/functions.php.
References $class, $count, esc_attr(), and is_active_sidebar().
twentyeleven_get_first_url ()
Return the first link from the post content.
If none found, the post permalink is used as a fallback.
Since
Twenty Eleven 1.0
get_url_in_content() to get the first URL from the post content.
Returns
string The first link.
This filter is documented in wp-includes/link-template.php
Definition at line 527 of file wordpress/wp-content/themes/twentyeleven/functions.php.
References $content, apply_filters(), get_permalink(), get_the_content(), get_url_in_content(), and twentyeleven_url_grabber().
twentyeleven_get_gallery_images ()
Retrieve the IDs for images in a gallery.
get_post_galleries() First, if available. Falls back to shortcode parsing, then as last option uses a get_posts() call.
Since
Twenty Eleven 1.6
Returns
array List of image IDs from the post gallery.
Definition at line 714 of file wordpress/wp-content/themes/twentyeleven/functions.php.
References get_post_galleries(), get_posts(), get_shortcode_regex(), get_the_content(), get_the_ID(), and shortcode_parse_atts().
twentyeleven_page_menu_args ($args)
Show a home link for the wp_nav_menu() fallback, wp_page_menu().
Since
Twenty Eleven 1.0
Parameters
array $args The page menu arguments.
See also
wp_page_menu()
Returns
array The filtered page menu arguments.
Definition at line 427 of file wordpress/wp-content/themes/twentyeleven/functions.php.
twentyeleven_url_grabber ()
Return the URL for the first link found in the post content.
Since
Twenty Eleven 1.0
Returns
string|bool URL or false when no link is present.
Definition at line 545 of file wordpress/wp-content/themes/twentyeleven/functions.php.
References esc_url_raw(), and get_the_content().
Referenced by twentyeleven_get_first_url().
twentyeleven_widgets_init ()
Register sidebars and widgetized areas.
Also register the default Epherma widget.
Since
Twenty Eleven 1.0
Definition at line 441 of file wordpress/wp-content/themes/twentyeleven/functions.php.
References __, register_sidebar(), and register_widget().
Variable Documentation
margin __pad17__
Definition at line 291 of file wordpress/wp-content/themes/twentyeleven/functions.php.
padding __pad18__
Definition at line 301 of file wordpress/wp-content/themes/twentyeleven/functions.php.
if (! function_exists('twentyeleven_admin_header_style')) () font Arial
Definition at line 272 of file wordpress/wp-content/themes/twentyeleven/functions.php.
Referenced by GFSelectColumns\select_columns_page(), and twentytwelve_admin_header_style().
border color
Definition at line 232 of file wordpress/wp-content/themes/twentyeleven/functions.php.
Referenced by Custom_Background\admin_page(), Custom_Image_Header\js_1(), login_header(), print_embed_styles(), GFSelectColumns\select_columns_page(), twentyeleven_print_link_color_style(), twentyfifteen_get_color_scheme_css(), twentythirteen_header_style(), twentytwelve_header_style(), and wpmu_signup_stylesheet().
text decoration
Definition at line 296 of file wordpress/wp-content/themes/twentyeleven/functions.php.
Referenced by print_embed_styles().
if (! function_exists('twentyeleven_header_style')) () else
Definition at line 232 of file wordpress/wp-content/themes/twentyeleven/functions.php.
if (! function_exists('twentyeleven_posted_on')) () endif
Definition at line 50 of file wordpress/wp-content/themes/twentyeleven/functions.php.
if (! function_exists('twentyeleven_admin_header_style')) () font family
Definition at line 272 of file wordpress/wp-content/themes/twentyeleven/functions.php.
Referenced by print_embed_styles(), GFSelectColumns\select_columns_page(), and twentytwelve_admin_header_style().
line height
Definition at line 295 of file wordpress/wp-content/themes/twentyeleven/functions.php.
Referenced by GravityView_Image\__construct(), SimplePie_Enclosure\__construct(), GFExport\export_lead_page(), SimplePie_Enclosure\get_height(), GravityView_Welcome\getting_started_screen(), list_theme_updates(), media_upload_type_url_form(), SimplePie_Misc\output_javascript(), GFSettings\page_footer(), page_footer(), print_embed_styles(), print_emoji_styles(), AVCSequenceParameterSetReader\readData(), GFSelectColumns\select_columns_page(), GravityView_Image\set_image_size(), Custom_Image_Header\step_2(), GravityView_Welcome\tabs(), WP_Customize_Cropped_Image_Control\to_json(), twentyeleven_settings_field_color_scheme(), twentyeleven_settings_field_layout(), twentythirteen_header_style(), wp_image_editor(), wp_print_media_templates(), and wp_underscore_video_template().
if (! function_exists('twentyeleven_admin_header_style')) () font Helvetica
Definition at line 272 of file wordpress/wp-content/themes/twentyeleven/functions.php.
Referenced by twentytwelve_admin_header_style().
if (! function_exists('twentyeleven_admin_header_style')) () font Nimbus Sans L
Definition at line 272 of file wordpress/wp-content/themes/twentyeleven/functions.php.
Referenced by network_step2().
if (! function_exists('twentyeleven_admin_header_style')) () font Nimbus Sans sans serif
Definition at line 272 of file wordpress/wp-content/themes/twentyeleven/functions.php.
Referenced by _default_wp_die_handler(), print_embed_styles(), GFSelectColumns\select_columns_page(), and twentytwelve_admin_header_style().
font size
Definition at line 294 of file wordpress/wp-content/themes/twentyeleven/functions.php.