GravityView: update.php File Reference
wordpress/wp-admin/includes/update.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
core_update_footer ($msg= '')
dismiss_core_update ($update)
find_core_auto_update ()
Gets the best available (and enabled) Auto-Update for WordPress Core.
find_core_update ($version, $locale)
get_core_checksums ($version, $locale)
Gets and caches the checksums for the given version of WordPress.
get_core_updates ($options=array())
Get available core updates.
get_plugin_updates ()
get_preferred_from_update_core ()
Selects the first update version from the update_core option.
get_theme_updates ()
maintenance_nag ()
int $upgrading
undismiss_core_update ($version, $locale)
update_nag ()
string $pagenow
update_right_now_message ()
wp_plugin_update_row ($file, $plugin_data)
wp_plugin_update_rows ()
wp_theme_update_row ($theme_key, $theme)
wp_theme_update_rows ()
Function Documentation
core_update_footer ($msg = '')
Parameters
string $msg
Returns
string
Definition at line 184 of file wordpress/wp-admin/includes/update.php.
References __, current_user_can(), get_bloginfo(), get_preferred_from_update_core(), and network_admin_url().
dismiss_core_update ($update)
Parameters
object $update
Returns
bool
Definition at line 136 of file wordpress/wp-admin/includes/update.php.
References $update, get_site_option(), and update_site_option().
Referenced by do_dismiss_core_update().
find_core_auto_update ()
Gets the best available (and enabled) Auto-Update for WordPress Core.
If there's 1.2.3 and 1.3 on offer, it'll choose 1.3 if the install allows it, else, 1.2.3
Since
3.7.0
Returns
array|false False on failure, otherwise the core update offering.
Definition at line 72 of file wordpress/wp-admin/includes/update.php.
References $update, ABSPATH, and get_site_transient().
Referenced by WP_Automatic_Updater\run().
find_core_update ($version, $locale)
Parameters
string $version
string $locale
Returns
object|false
Definition at line 165 of file wordpress/wp-admin/includes/update.php.
References $locale, $update, and get_site_transient().
Referenced by do_core_upgrade(), do_dismiss_core_update(), and do_undismiss_core_update().
get_core_checksums ($version, $locale)
Gets and caches the checksums for the given version of WordPress.
Since
3.7.0
Parameters
string $version Version string to query.
string $locale Locale to query.
Returns
bool|array False on failure. An array of checksums on success.
Definition at line 103 of file wordpress/wp-admin/includes/update.php.
References $options, $url, __, DOING_CRON, is_wp_error(), null, set_url_scheme(), WP_DEBUG, wp_http_supports(), wp_remote_get(), wp_remote_retrieve_body(), and wp_remote_retrieve_response_code().
Referenced by Core_Upgrader\check_files(), and update_core().
get_core_updates ($options = array())
Get available core updates.
Parameters
array $options Set $options['dismissed'] to true to show dismissed upgrades too, set $options['available'] to false to skip not-dismissed updates.
Returns
array|false Array of the update objects on success, false on failure.
Definition at line 30 of file wordpress/wp-admin/includes/update.php.
References $options, $update, get_site_option(), and get_site_transient().
Referenced by core_upgrade_preamble(), dismissed_updates(), get_preferred_from_update_core(), list_core_update(), list_plugin_updates(), and wp_get_update_data().
get_plugin_updates ()
Since
2.9.0
Returns
array
Definition at line 281 of file wordpress/wp-admin/includes/update.php.
References get_plugins(), get_site_transient(), and object.
Referenced by list_plugin_updates(), and WP_Automatic_Updater\send_email().
get_preferred_from_update_core ()
Selects the first update version from the update_core option.
Returns
object|array|false The response from the API on success, false on failure.
Definition at line 14 of file wordpress/wp-admin/includes/update.php.
References get_core_updates().
Referenced by core_update_footer(), WP_Automatic_Updater\send_email(), update_nag(), and update_right_now_message().
get_theme_updates ()
Returns
array
Definition at line 411 of file wordpress/wp-admin/includes/update.php.
References get_site_transient(), and wp_get_theme().
Referenced by list_theme_updates(), and WP_Automatic_Updater\send_email().
maintenance_nag ()
int $upgrading
Returns
false|void
Definition at line 514 of file wordpress/wp-admin/includes/update.php.
References $msg, $wp_version, __, ABSPATH, current_user_can(), get_site_option(), and WPINC.
undismiss_core_update ($version, $locale)
Parameters
string $version
string $locale
Returns
bool
Definition at line 148 of file wordpress/wp-admin/includes/update.php.
References $locale, get_site_option(), and update_site_option().
Referenced by do_undismiss_core_update().
update_nag ()
string $pagenow
Returns
false|void
Definition at line 219 of file wordpress/wp-admin/includes/update.php.
References $msg, $pagenow, __, current_user_can(), get_preferred_from_update_core(), is_multisite(), and network_admin_url().
update_right_now_message ()
Filter the text displayed in the 'At a Glance' dashboard widget.
Prior to 3.8.0, the widget was named 'Right Now'.
Since
4.4.0
Parameters
string $content Default text.
Definition at line 242 of file wordpress/wp-admin/includes/update.php.
References $content, $msg, __, apply_filters(), current_user_can(), get_bloginfo(), get_preferred_from_update_core(), network_admin_url(), and wp_get_theme().
Referenced by wp_dashboard_right_now().
wp_plugin_update_row ($file, $plugin_data)
Parameters
string $file
array $plugin_data
Returns
false|void
Fires at the end of the update message container in each row of the plugins list table.
The dynamic portion of the hook name, $file, refers to the path of the plugin's primary file relative to the plugins directory.
Since
2.8.0
Parameters
array $plugin_data { An array of plugin metadata.
string $name The human-readable name of the plugin. string $plugin_uri Plugin URI. string $version Plugin version. string $description Plugin description. string $author Plugin author. string $author_uri Plugin author URI. string $text_domain Plugin text domain. string $domain_path Relative path to the plugin's .mo file(s). bool $network Whether the plugin can only be activated network wide. string $title The human-readable title of the plugin. string $author_name Plugin author's name. bool $update Whether there's an available update. Default null. }
Parameters
array $r { An array of metadata about the available plugin update.
int $id Plugin ID. string $slug Plugin slug. string $new_version New plugin version. string $url Plugin URL. string $package Plugin update package URL. }
Definition at line 317 of file wordpress/wp-admin/includes/update.php.
References $file, $wp_list_table, __, _get_list_table(), current_user_can(), do_action(), elseif, esc_attr(), esc_url, get_site_transient(), is_multisite(), is_network_admin(), is_plugin_active(), is_plugin_active_for_network(), self_admin_url(), wp_kses(), and wp_nonce_url().
wp_plugin_update_rows ()
Since
2.9.0
Definition at line 298 of file wordpress/wp-admin/includes/update.php.
References $plugins, add_action(), current_user_can(), and get_site_transient().
wp_theme_update_row ($theme_key, $theme)
Parameters
string $theme_key
WP_Theme $theme
Returns
false|void
Fires at the end of the update message container in each row of the themes list table.
The dynamic portion of the hook name, $theme_key, refers to the theme slug as found in the WordPress.org themes repository.
Since
3.1.0
Parameters
WP_Theme $theme The WP_Theme object.
array $r { An array of metadata about the available theme update.
string $new_version New theme version. string $url Theme URL. string $package Theme update package URL. }
Definition at line 449 of file wordpress/wp-admin/includes/update.php.
References $theme, $wp_list_table, __, _get_list_table(), add_query_arg(), current_user_can(), do_action(), elseif, esc_attr(), esc_url, get_site_transient(), self_admin_url(), and wp_nonce_url().
wp_theme_update_rows ()
Since
3.1.0
Definition at line 429 of file wordpress/wp-admin/includes/update.php.
References $theme, add_action(), current_user_can(), and get_site_transient().