GravityView: upload.php File Reference
wordpress/wp-admin/upload.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$doaction = $wp_list_table->current_action()
s &</h1 > $message = ''
if(!empty($_GET['posted'])) if(!empty($_GET['attached'])&&$attached=absint($_GET['attached'])) if(!empty($_GET['detach'])&&$detached=absint($_GET['detach'])) if(!empty($_GET['deleted'])&&$deleted=absint($_GET['deleted'])) if(!empty($_GET['trashed'])&&$trashed=absint($_GET['trashed'])) if(!empty($_GET['untrashed'])&&$untrashed=absint($_GET['untrashed'])) $messages [1] = __('Media attachment updated.')
$messages [2] = __('Media attachment permanently deleted.')
$messages [3] = __('Error saving media attachment.')
$messages [4] = __('Media attachment moved to the trash.') . ' <a href="' . esc_url(wp_nonce_url('upload.php?doaction=undo&action=untrash&ids='.(isset($_GET['ids']) ? $_GET['ids'] : ''), "bulk-media")) . '">' . __('Undo') . '</a>'
$messages [5] = __('Media attachment restored from the trash.')
$mode = get_user_option('media_library_mode', get_current_user_id()) ? get_user_option('media_library_mode', get_current_user_id()) : 'grid'
$modes = array('grid', 'list')
$pagenum = $wp_list_table->get_pagenum()
$parent_file = 'upload.php'
$title = __('Media Library')
if(isset($_GET['mode'])&&in_array($_GET['mode'], $modes)) if('grid'===$mode) $wp_list_table = _get_list_table('WP_Media_List_Table')
ve uploaded are listed in the Media Library
Variable Documentation
$doaction = $wp_list_table->current_action()
Definition at line 97 of file wordpress/wp-admin/upload.php.
s&</h1> $message = ''
Definition at line 228 of file wordpress/wp-admin/upload.php.
if (!empty($_GET['posted'])) if (!empty($_GET['attached'])&&$attached=absint($_GET['attached'])) if (!empty($_GET['detach'])&&$detached=absint($_GET['detach'])) if (!empty($_GET['deleted'])&&$deleted=absint($_GET['deleted'])) if (!empty($_GET['trashed'])&&$trashed=absint($_GET['trashed'])) if (!empty($_GET['untrashed'])&&$untrashed=absint($_GET['untrashed'])) $messages[1] = __('Media attachment updated.')
Definition at line 275 of file wordpress/wp-admin/upload.php.
$messages[2] = __('Media attachment permanently deleted.')
Definition at line 276 of file wordpress/wp-admin/upload.php.
$messages[3] = __('Error saving media attachment.')
Definition at line 277 of file wordpress/wp-admin/upload.php.
$messages[4] = __('Media attachment moved to the trash.') . ' <a href="' . esc_url(wp_nonce_url('upload.php?doaction=undo&action=untrash&ids='.(isset($_GET['ids']) ? $_GET['ids'] : ''), "bulk-media")) . '">' . __('Undo') . '</a>'
Definition at line 278 of file wordpress/wp-admin/upload.php.
$messages[5] = __('Media attachment restored from the trash.')
Definition at line 279 of file wordpress/wp-admin/upload.php.
$mode = get_user_option('media_library_mode', get_current_user_id()) ? get_user_option('media_library_mode', get_current_user_id()) : 'grid'
Definition at line 15 of file wordpress/wp-admin/upload.php.
Referenced by ftp\_data_prepare(), ftp\_data_read(), ftp\_data_write(), ftp\_data_write_block(), _recaptcha_aes_encrypt(), ftp_base\_settype(), SimplePie_Misc\atom_03_construct_type(), GVCommon\check_entry_display(), WP_Filesystem_Direct\chmod(), WP_Filesystem_FTPext\chmod(), WP_Filesystem_ftpsockets\chmod(), WP_Filesystem_SSH2\chmod(), ftp_base\chmod(), WP_MS_Sites_List_Table\column_blogname(), WP_Posts_List_Table\column_date(), WP_MS_Sites_List_Table\column_lastupdated(), WP_MS_Users_List_Table\column_registered(), WP_MS_Sites_List_Table\column_registered(), WP_Posts_List_Table\column_title(), WP_Filesystem_Direct\copy(), WP_Filesystem_FTPext\copy(), WP_Filesystem_ftpsockets\copy(), WP_Filesystem_SSH2\copy(), GravityView_Delete_Entry\delete_or_trash_entry(), Text_Diff_Engine_string\diff(), ftp_base\fget(), GravityView_Widget_Search\filter_entries(), ftp_base\fput(), ftp_base\get(), WP_Filesystem_Base\getnumchmodfromh(), WP_Posts_List_Table\inline_edit(), GFFormDisplay\is_last_page(), GFEntryDetail\lead_detail_page(), ftp_base\mmkdir(), WP_MS_Users_List_Table\pagination(), WP_MS_Sites_List_Table\pagination(), permalink_anchor(), WP_MS_Users_List_Table\prepare_items(), WP_MS_Sites_List_Table\prepare_items(), WP_Media_List_Table\prepare_items(), WP_Posts_List_Table\prepare_items(), ftp_base\put(), WP_Filesystem_Direct\put_contents(), WP_Filesystem_FTPext\put_contents(), WP_Filesystem_ftpsockets\put_contents(), WP_Filesystem_SSH2\put_contents(), WP_Screen\render_view_mode(), wpdb\set_sql_mode(), ftp_base\SetType(), getid3_ogg\SpeexBandModeLookup(), QRtools\tcpdfBarcodeArray(), WP_List_Table\view_switcher(), WP_Media_List_Table\views(), wp_ajax_inline_save(), wp_comment_reply(), wp_get_single_post(), and wp_kses_hair().
$modes = array('grid', 'list')
Definition at line 16 of file wordpress/wp-admin/upload.php.
Referenced by wpdb\set_sql_mode().
$pagenum = $wp_list_table->get_pagenum()
Definition at line 94 of file wordpress/wp-admin/upload.php.
$parent_file = 'upload.php'
Definition at line 174 of file wordpress/wp-admin/upload.php.
$title = __('Media Library')
Definition at line 173 of file wordpress/wp-admin/upload.php.
if (isset($_GET['mode'])&&in_array($_GET['mode'], $modes)) if ('grid'===$mode) $wp_list_table = _get_list_table('WP_Media_List_Table')
Definition at line 93 of file wordpress/wp-admin/upload.php.
ve uploaded are listed in the Media Library
Definition at line 184 of file wordpress/wp-admin/upload.php.