GravityView: functions.php File Reference
wordpress/wp-content/themes/twentytwelve/functions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentytwelve_body_class ($classes)
Extend the default WordPress body classes.
twentytwelve_content_width ()
Adjust content width in certain contexts.
twentytwelve_customize_preview_js ()
Enqueue Javascript postMessage handlers for the Customizer.
twentytwelve_customize_register ($wp_customize)
Register postMessage support.
twentytwelve_get_font_url ()
Add support for a custom header image.
twentytwelve_mce_css ($mce_css)
Filter TinyMCE CSS path to include Google Fonts.
twentytwelve_page_menu_args ($args)
Filter the page menu arguments.
twentytwelve_scripts_styles ()
Enqueue scripts and styles for front-end.
twentytwelve_setup ()
Twenty Twelve setup.
twentytwelve_widgets_init ()
Register sidebars.
twentytwelve_wp_title ($title, $sep)
Filter the page title.
Variables
if(!function_exists('twentytwelve_content_nav'))($html_id) endif
Function Documentation
twentytwelve_body_class ($classes)
Extend the default WordPress body classes.
Extends the default WordPress body class to denote:
Using a full-width layout, when no active widgets in the sidebar or full-width template.
Front Page template: thumbnail in use and number of sidebars for widget areas.
White or empty background color to change the layout and spacing.
Custom fonts enabled.
Single or multiple authors.
Since
Twenty Twelve 1.0
Parameters
array $classes Existing class values.
Returns
array Filtered class values.
Definition at line 421 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References elseif, get_background_color(), get_background_image(), has_post_thumbnail(), is_active_sidebar(), is_multi_author(), is_page_template(), and wp_style_is().
twentytwelve_content_width ()
Adjust content width in certain contexts.
Adjusts content_width value for full-width and single image attachment templates, and when there are no active widgets in the sidebar.
Since
Twenty Twelve 1.0
Definition at line 462 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References is_active_sidebar(), is_attachment(), and is_page_template().
twentytwelve_customize_preview_js ()
Enqueue Javascript postMessage handlers for the Customizer.
Binds JS handlers to make the Customizer preview reload changes asynchronously.
Since
Twenty Twelve 1.0
Definition at line 493 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References get_template_directory_uri(), and wp_enqueue_script().
twentytwelve_customize_register ($wp_customize)
Register postMessage support.
Add postMessage support for site title and description for the Customizer.
Since
Twenty Twelve 1.0
Parameters
WP_Customize_Manager $wp_customize Customizer object.
Definition at line 479 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References $wp_customize.
twentytwelve_get_font_url ()
Add support for a custom header image.
Return the Google font stylesheet URL if available.
The use of Open Sans by default is localized. For languages that use characters not supported by the font, the font can be disabled.
Since
Twenty Twelve 1.2
Returns
string Font stylesheet or empty string if disabled.
Definition at line 95 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References _x, add_query_arg(), and elseif.
Referenced by twentytwelve_custom_header_fonts(), twentytwelve_mce_css(), and twentytwelve_scripts_styles().
twentytwelve_mce_css ($mce_css)
Filter TinyMCE CSS path to include Google Fonts.
Adds additional stylesheets to the TinyMCE editor if needed.
twentytwelve_get_font_url() To get the Google Font stylesheet URL.
Since
Twenty Twelve 1.2
Parameters
string $mce_css CSS path to load in TinyMCE.
Returns
string Filtered CSS path.
Definition at line 169 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References esc_url_raw(), str_replace, and twentytwelve_get_font_url().
twentytwelve_page_menu_args ($args)
Filter the page menu arguments.
Makes our wp_nav_menu() fallback – wp_page_menu() – show a home link.
Since
Twenty Twelve 1.0
Definition at line 225 of file wordpress/wp-content/themes/twentytwelve/functions.php.
twentytwelve_scripts_styles ()
Enqueue scripts and styles for front-end.
Since
Twenty Twelve 1.0
Definition at line 131 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References $wp_styles, comments_open(), esc_url_raw(), get_option(), get_stylesheet_uri(), get_template_directory_uri(), is_singular(), null, twentytwelve_get_font_url(), wp_enqueue_script(), and wp_enqueue_style().
twentytwelve_setup ()
Twenty Twelve setup.
Sets up theme defaults and registers the various WordPress features that Twenty Twelve supports.
load_theme_textdomain() For translation/localization support. add_editor_style() To add a Visual Editor stylesheet. add_theme_support() To add support for post thumbnails, automatic feed links, custom background, and post formats. register_nav_menu() To add support for navigation menus. set_post_thumbnail_size() To set a custom post thumbnail size.
Since
Twenty Twelve 1.0
Definition at line 44 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References __, add_editor_style(), add_theme_support(), get_template_directory(), load_theme_textdomain(), register_nav_menu(), and set_post_thumbnail_size().
twentytwelve_widgets_init ()
Register sidebars.
Registers our main widget area and the front page widget areas.
Since
Twenty Twelve 1.0
Definition at line 239 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References __, and register_sidebar().
twentytwelve_wp_title ($title, $sep)
Filter the page title.
Creates a nicely formatted and more specific title element text for output in head of document, based on current view.
Since
Twenty Twelve 1.0
Parameters
string $title Default title text for current view.
string $sep Optional separator.
Returns
string Filtered title.
Definition at line 196 of file wordpress/wp-content/themes/twentytwelve/functions.php.
References $page, $paged, $site_description, $title, __, get_bloginfo(), is_404, is_feed(), is_front_page(), and is_home().
Variable Documentation
if (! function_exists('twentytwelve_entry_meta')) () endif
Definition at line 272 of file wordpress/wp-content/themes/twentytwelve/functions.php.