GravityView: functions.php File Reference
wordpress/wp-content/themes/twentyten/functions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyten_auto_excerpt_more ($more)
Replace "[...]" with an ellipsis and twentyten_continue_reading_link().
twentyten_custom_excerpt_more ($output)
Add a pretty "Continue Reading" link to custom post excerpts.
twentyten_excerpt_length ($length)
Set the post excerpt length to 40 characters.
twentyten_get_gallery_images ()
Retrieve the IDs for images in a gallery.
twentyten_page_menu_args ($args)
Show a home link for our wp_nav_menu() fallback, wp_page_menu().
twentyten_remove_gallery_css ($css)
Deprecated way to remove inline styles printed when the gallery shortcode is used.
twentyten_remove_recent_comments_style ()
Remove the default styles that are packaged with the Recent Comments widget.
twentyten_widgets_init ()
Register widgetized areas, including two sidebars and four widget-ready columns in the footer.
Variables
if(!function_exists('twentyten_setup'))() endif
if (version_compare($GLOBALS['wp_version'], '3.1', '<')) add_filter('gallery_style'
Function Documentation
twentyten_auto_excerpt_more ($more)
Replace "[...]" with an ellipsis and twentyten_continue_reading_link().
"[...]" is appended to automatically generated excerpts.
To override this in a child theme, remove the filter and add your own function tied to the excerpt_more filter hook.
Since
Twenty Ten 1.0
Parameters
string $more The Read More text.
Returns
string An ellipsis.
Definition at line 297 of file wordpress/wp-content/themes/twentyten/functions.php.
References $more, and is_admin().
twentyten_custom_excerpt_more ($output)
Add a pretty "Continue Reading" link to custom post excerpts.
To override this link in a child theme, remove the filter and add your own function tied to the get_the_excerpt filter hook.
Since
Twenty Ten 1.0
Parameters
string $output The "Coninue Reading" link.
Returns
string Excerpt with a pretty "Continue Reading" link.
Definition at line 316 of file wordpress/wp-content/themes/twentyten/functions.php.
References $output, has_excerpt(), is_admin(), and is_attachment().
twentyten_excerpt_length ($length)
Set the post excerpt length to 40 characters.
To override this length in a child theme, remove the filter and add your own function tied to the excerpt_length filter hook.
Since
Twenty Ten 1.0
Parameters
int $length The number of excerpt characters.
Returns
int The filtered number of excerpt characters.
Definition at line 266 of file wordpress/wp-content/themes/twentyten/functions.php.
twentyten_get_gallery_images ()
Retrieve the IDs for images in a gallery.
get_post_galleries() First, if available. Falls back to shortcode parsing, then as last option uses a get_posts() call.
Since
Twenty Ten 1.6.
Returns
array List of image IDs from the post gallery.
Definition at line 567 of file wordpress/wp-content/themes/twentyten/functions.php.
References get_post_galleries(), get_posts(), get_shortcode_regex(), get_the_content(), get_the_ID(), and shortcode_parse_atts().
twentyten_page_menu_args ($args)
Show a home link for our wp_nav_menu() fallback, wp_page_menu().
To override this in a child theme, remove the filter and optionally add your own function tied to the wp_page_menu_args filter hook.
Since
Twenty Ten 1.0
Parameters
array $args An optional array of arguments.
See also
wp_page_menu()
Definition at line 248 of file wordpress/wp-content/themes/twentyten/functions.php.
twentyten_remove_gallery_css ($css)
Deprecated way to remove inline styles printed when the gallery shortcode is used.
This function is no longer needed or used. Use the use_default_gallery_style filter instead, as seen above.
Since
Twenty Ten 1.0
Returns
string The gallery style filter, with the styles themselves removed.
Definition at line 345 of file wordpress/wp-content/themes/twentyten/functions.php.
twentyten_remove_recent_comments_style ()
Remove the default styles that are packaged with the Recent Comments widget.
To override this in a child theme, remove the filter and optionally add your own function tied to the widgets_init action hook.
This function uses a filter (show_recent_comments_widget_style) new in WordPress 3.1 to remove the default style. Using Twenty Ten 1.2 in WordPress 3.0 will show the styles, but they won't have any effect on the widget in default Twenty Ten styling.
Since
Twenty Ten 1.0
Definition at line 502 of file wordpress/wp-content/themes/twentyten/functions.php.
References add_filter().
twentyten_widgets_init ()
Register widgetized areas, including two sidebars and four widget-ready columns in the footer.
To override twentyten_widgets_init() in a child theme, remove the action hook and add your own function tied to the init hook.
Since
Twenty Ten 1.0
register_sidebar()
Definition at line 420 of file wordpress/wp-content/themes/twentyten/functions.php.
References __, and register_sidebar().
Variable Documentation
if (! function_exists('twentyten_posted_in')) () endif
Definition at line 53 of file wordpress/wp-content/themes/twentyten/functions.php.
if(version_compare($GLOBALS['wp_version'], '3.1', '<')) add_filter('gallery_style'
Definition at line 349 of file wordpress/wp-content/themes/twentyten/functions.php.