GravityView: export.php File Reference
wordpress/wp-admin/export.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
export_add_js ()
Display JavaScript on the page.
export_date_options ($post_type= 'post')
Create the date options fields for exporting a given post type.
Variables
$authors = $wpdb->get_col("SELECT DISTINCT post_author FROM {$wpdb->posts} WHERE post_type = 'post'")
$post_stati = get_post_stati(array('internal' => false), 'objects')
$title = __('Export')
Load WordPress export API.
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file author
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom categories
s content in order to import it into another installation or platform The export file will be an XML file format called WXR comments
endforeach
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom fields
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file date range by or publishing status</p >< p > Once generated
if (isset($_GET['download']))
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file date range by or publishing status</p >< p > Once your WXR file can be imported by another WordPress site or by another blogging platform able to access this format</p >< p >< strong > For more information
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file date range by month
s content in order to import it into another installation or platform The export file will be an XML file format called WXR pages
s content in order to import it into another installation or platform The export file will be an XML file format called WXR Posts
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file to
Function Documentation
export_add_js ()
Display JavaScript on the page.
Since
3.5.0
Filter the export args.
Since
3.5.0
Parameters
array $args The arguments to send to the exporter.
Definition at line 24 of file wordpress/wp-admin/export.php.
export_date_options ($post_type = 'post')
Create the date options fields for exporting a given post type.
wpdb $wpdb WordPress database abstraction object. WP_Locale $wp_locale Date and Time Locale object.
Since
3.1.0
Parameters
string $post_type The post type. Default 'post'.
Definition at line 130 of file wordpress/wp-admin/export.php.
References $post_type, $wp_locale, $wpdb, month, and zeroise().
Variable Documentation
$authors = $wpdb->get_col("SELECT DISTINCT post_author FROM {$wpdb->posts} WHERE post_type = 'post'")
Definition at line 179 of file wordpress/wp-admin/export.php.
Referenced by export_wp(), SimplePie_Source\get_author(), SimplePie_Item\get_author(), SimplePie\get_author(), SimplePie_Source\get_authors(), SimplePie_Item\get_authors(), SimplePie\get_authors(), get_editable_authors(), WP_Query\get_posts(), WP_Posts_List_Table\inline_edit(), wp_xmlrpc_server\wp_getAuthors(), wp_list_authors(), and wp_prepare_revisions_for_js().
$post_stati = get_post_stati(array('internal' => false), 'objects')
Definition at line 208 of file wordpress/wp-admin/export.php.
Referenced by wp_edit_posts_query().
$title = __('Export')
Load WordPress export API.
Definition at line 17 of file wordpress/wp-admin/export.php.
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file author
Definition at line 48 of file wordpress/wp-admin/export.php.
Referenced by GV_License_Handler\_get_edd_settings(), _wp_dashboard_recent_comments_row(), Walker_Comment\html5_comment(), and twentyfifteen_get_color_scheme_css().
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom categories
Definition at line 48 of file wordpress/wp-admin/export.php.
Referenced by SimplePie_Enclosure\__construct(), and SimplePie_Enclosure\get_categories().
s content in order to import it into another installation or platform The export file will be an XML file format called WXR comments
Definition at line 48 of file wordpress/wp-admin/export.php.
endforeach
Definition at line 210 of file wordpress/wp-admin/export.php.
bool Whether to allow editing product fields
Since
1.9
Definition at line 48 of file wordpress/wp-admin/export.php.
Referenced by CreatePlaceholdersUI(), GravityView_View\getField(), GravityView_View\getFields(), GravityView_Welcome\getting_started_screen(), output_form_list_script_block(), GravityView_View\setField(), and GravityView_View\setFields().
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file date range by or publishing status</p><p> Once generated
Definition at line 48 of file wordpress/wp-admin/export.php.
Referenced by export_wp().
if(isset($_GET['download']))
Definition at line 59 of file wordpress/wp-admin/export.php.
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file date range by or publishing status</p><p> Once your WXR file can be imported by another WordPress site or by another blogging platform able to access this format</p><p><strong> For more information
Definition at line 48 of file wordpress/wp-admin/export.php.
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file date range by month
Definition at line 48 of file wordpress/wp-admin/export.php.
Referenced by SimplePie_Parse_Date\__construct(), CreatePlaceholdersUI(), SimplePie_Parse_Date\date_asctime(), SimplePie_Parse_Date\date_rfc2822(), SimplePie_Parse_Date\date_rfc850(), export_date_options(), WP_Locale\get_month(), WP_Locale\init(), and WP_List_Table\months_dropdown().
s content in order to import it into another installation or platform The export file will be an XML file format called WXR pages
Definition at line 48 of file wordpress/wp-admin/export.php.
Referenced by CreatePlaceholdersUI(), and InitPaginationOptions().
s content in order to import it into another installation or platform The export file will be an XML file format called WXR Posts
Definition at line 48 of file wordpress/wp-admin/export.php.
Referenced by GravityView_Welcome\getting_started_screen().
s content in order to import it into another installation or platform The export file will be an XML file format called WXR custom and tags can be included You can choose for the WXR file to
Definition at line 48 of file wordpress/wp-admin/export.php.