GravityView: functions.php File Reference
wordpress/wp-content/themes/twentythirteen/functions.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentythirteen_body_class ($classes)
Extend the default WordPress body classes.
twentythirteen_content_width ()
Adjust content_width value for video post formats and attachment templates.
twentythirteen_customize_preview_js ()
Enqueue Javascript postMessage handlers for the Customizer.
twentythirteen_customize_register ($wp_customize)
Add postMessage support for site title and description for the Customizer.
twentythirteen_fonts_url ()
Return the Google font stylesheet URL, if available.
twentythirteen_get_link_url ()
Return the post URL.
twentythirteen_scripts_styles ()
Enqueue scripts and styles for the front end.
twentythirteen_setup ()
Twenty Thirteen setup.
twentythirteen_widgets_init ()
Register two widget areas.
twentythirteen_wp_title ($title, $sep)
Filter the page title.
Variables
if(!function_exists('twentythirteen_paging_nav'))() endif
Function Documentation
twentythirteen_body_class ($classes)
Extend the default WordPress body classes.
Adds body classes to denote:
Single or multiple authors.
Active widgets in the sidebar to change the layout and spacing.
When avatars are disabled in discussion settings.
Since
Twenty Thirteen 1.0
Parameters
array $classes A list of existing body class values.
Returns
array The filtered body class list.
Definition at line 498 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References get_option(), is_404, is_active_sidebar(), is_attachment(), and is_multi_author().
twentythirteen_content_width ()
Adjust content_width value for video post formats and attachment templates.
Since
Twenty Thirteen 1.0
Definition at line 517 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References elseif, has_post_format(), and is_attachment().
twentythirteen_customize_preview_js ()
Enqueue Javascript postMessage handlers for the Customizer.
Binds JavaScript handlers to make the Customizer preview reload changes asynchronously.
Since
Twenty Thirteen 1.0
Definition at line 549 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References get_template_directory_uri(), and wp_enqueue_script().
twentythirteen_customize_register ($wp_customize)
Add postMessage support for site title and description for the Customizer.
Since
Twenty Thirteen 1.0
Parameters
WP_Customize_Manager $wp_customize Customizer object.
Definition at line 534 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References $wp_customize.
twentythirteen_fonts_url ()
Return the Google font stylesheet URL, if available.
The use of Source Sans Pro and Bitter by default is localized. For languages that use characters not supported by the font, the font can be disabled.
Since
Twenty Thirteen 1.0
Returns
string Font stylesheet or empty string if disabled.
Definition at line 121 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References _x, and add_query_arg().
Referenced by twentythirteen_custom_header_fonts(), twentythirteen_scripts_styles(), and twentythirteen_setup().
twentythirteen_get_link_url ()
Return the post URL.
get_url_in_content() to get the URL in the post meta (if it exists) or the first link found in the post content.
Falls back to the post permalink if no URL is found in the post.
Since
Twenty Thirteen 1.0
Returns
string The Link format URL.
Definition at line 457 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References $content, apply_filters(), get_permalink(), get_the_content(), and get_url_in_content().
twentythirteen_scripts_styles ()
Enqueue scripts and styles for the front end.
Since
Twenty Thirteen 1.0
Definition at line 160 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References comments_open(), get_option(), get_stylesheet_uri(), get_template_directory_uri(), is_active_sidebar(), is_singular(), null, twentythirteen_fonts_url(), wp_enqueue_script(), wp_enqueue_style(), and wp_style_add_data().
twentythirteen_setup ()
Twenty Thirteen setup.
Sets up theme defaults and registers the various WordPress features that Twenty Thirteen supports.
load_theme_textdomain() For translation/localization support. add_editor_style() To add Visual Editor stylesheets. add_theme_support() To add support for automatic feed links, post formats, and post thumbnails. register_nav_menu() To add support for a navigation menu. set_post_thumbnail_size() To set a custom post thumbnail size.
Since
Twenty Thirteen 1.0
Definition at line 60 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References __, add_editor_style(), add_filter(), add_theme_support(), get_template_directory(), load_theme_textdomain(), register_nav_menu(), set_post_thumbnail_size(), and twentythirteen_fonts_url().
twentythirteen_widgets_init ()
Register two widget areas.
Since
Twenty Thirteen 1.0
Filter the image attachment size to use.
Since
Twenty thirteen 1.0
Parameters
array $size { int The attachment height in pixels. int The attachment width in pixels. }
Definition at line 229 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References __, and register_sidebar().
twentythirteen_wp_title ($title, $sep)
Filter the page title.
Creates a nicely formatted and more specific title element text for output in head of document, based on current view.
Since
Twenty Thirteen 1.0
Parameters
string $title Default title text for current view.
string $sep Optional separator.
Returns
string The filtered title.
Definition at line 202 of file wordpress/wp-content/themes/twentythirteen/functions.php.
References $page, $paged, $site_description, $title, __, get_bloginfo(), is_404, is_feed(), is_front_page(), and is_home().
Variable Documentation
endif
Definition at line 252 of file wordpress/wp-content/themes/twentythirteen/functions.php.