GravityView: file.php File Reference
wp-admin/includes/file.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_unzip_file_pclzip ($file, $to, $needed_dirs=array())
This function should not be called directly, use unzip_file instead.
_unzip_file_ziparchive ($file, $to, $needed_dirs=array())
This function should not be called directly, use unzip_file instead.
_wp_handle_upload (&$file, $overrides, $time, $action)
Handle PHP uploads in WordPress, sanitizing file names, checking extensions for mime type, and moving the file to the appropriate directory within the uploads directory.
copy_dir ($from, $to, $skip_list=array())
Copies a directory from one location to another via the WordPress Filesystem Abstraction.
download_url ($url, $timeout=300)
Downloads a url to a local temporary file using the WordPress HTTP Class.
get_file_description ($file)
Get the description for standard WordPress theme files and other various standard WordPress files.
get_filesystem_method ($args=array(), $context=false, $allow_relaxed_file_ownership=false)
Determines which method to use for reading, writing, modifying, or deleting files on the filesystem.
get_home_path ()
Get the absolute filesystem path to the root of the WordPress installation.
list_files ($folder= '', $levels=100)
Returns a listing of all files in the specified folder and all subdirectories up to 100 levels deep.
request_filesystem_credentials ($form_post, $type= '', $error=false, $context=false, $extra_fields=null, $allow_relaxed_file_ownership=false)
Displays a form to the user to request for their FTP/SSH details in order to connect to the filesystem.
unzip_file ($file, $to)
Unzips a specified ZIP file to a location on the Filesystem via the WordPress Filesystem Abstraction.
validate_file_to_edit ($file, $allowed_files= '')
Make sure that the file that was requested to edit, is allowed to be edited.
verify_file_md5 ($filename, $expected_md5)
Calculates and compares the MD5 of a file to its expected value.
WP_Filesystem ($args=false, $context=false, $allow_relaxed_file_ownership=false)
Initialises and connects the WordPress Filesystem Abstraction classes.
wp_handle_sideload (&$file, $overrides=false, $time=null)
Wrapper for _wp_handle_upload(), passes 'wp_handle_sideload' action.
wp_handle_upload (&$file, $overrides=false, $time=null)
Wrapper for _wp_handle_upload(), passes 'wp_handle_upload' action.
wp_print_request_filesystem_credentials_modal ()
Print the filesystem credentials modal when needed.
wp_tempnam ($filename= '', $dir= '')
Returns a filename of a Temporary unique file.
Variables
$wp_file_descriptions
The descriptions for theme files.
Function Documentation
_unzip_file_pclzip ($file, $to, $needed_dirs = array())
This function should not be called directly, use unzip_file instead.
Attempts to unzip an archive using the PclZip library. Assumes that WP_Filesystem() has already been called and set up.
Since
3.0.0
See also
unzip_file private
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $file Full path and filename of zip archive
string $to Full path on the filesystem to extract archive to
array $needed_dirs A partial list of required folders needed to be created.
Returns
mixed WP_Error on failure, True on success
Definition at line 718 of file wp-admin/includes/file.php.
References $dir, $file, __, ABSPATH, DOING_CRON, mbstring_binary_safe_encoding(), PCLZIP_OPT_EXTRACT_AS_STRING, reset_mbstring_encoding(), untrailingslashit(), and WP_CONTENT_DIR.
Referenced by unzip_file().
_unzip_file_ziparchive ($file, $to, $needed_dirs = array())
This function should not be called directly, use unzip_file instead.
Attempts to unzip an archive using the ZipArchive class. Assumes that WP_Filesystem() has already been called and set up.
Since
3.0.0
See also
unzip_file private
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $file Full path and filename of zip archive
string $to Full path on the filesystem to extract archive to
array $needed_dirs A partial list of required folders needed to be created.
Returns
mixed WP_Error on failure, True on success
Definition at line 618 of file wp-admin/includes/file.php.
References $dir, $file, $i, __, DOING_CRON, untrailingslashit(), and WP_CONTENT_DIR.
Referenced by unzip_file().
_wp_handle_upload (& $file, $overrides, $time, $action)
Handle PHP uploads in WordPress, sanitizing file names, checking extensions for mime type, and moving the file to the appropriate directory within the uploads directory.
Since
4.0.0
See also
wp_handle_upload_error
Parameters
array $file Reference to a single element of $_FILES. Call the function once for each uploaded file.
array | false $overrides An associative array of names => values to override default variables. Default false.
string $time Time formatted in 'yyyy/mm'.
string $action Expected value for $_POST['action'].
Returns
array On success, returns an associative array of file attributes. On failure, returns $overrides['upload_error_handler'](&$file, $message) or array('error'=>$message).
Filter the data for a file before it is uploaded to WordPress.
The dynamic portion of the hook name, $action, refers to the post action.
Since
2.9.0 as 'wp_handle_upload_prefilter'.
4.0.0 Converted to a dynamic hook with $action.
Parameters
array $file An array of data for a single file.
Filter the data array for the uploaded file.
Since
2.1.0
Parameters
array $upload { Array of upload data.
string $file Filename of the newly-uploaded file. string $url URL of the uploaded file. string $type File type. }
Parameters
string $context The type of upload action. Values include 'upload' or 'sideload'.
Definition at line 238 of file wp-admin/includes/file.php.
References $action, $file, $message, $url, __, ABSPATH, apply_filters(), current_user_can(), delete_transient(), is_multisite(), null, str_replace, wp_check_filetype_and_ext(), wp_unique_filename(), and wp_upload_dir().
Referenced by wp_handle_sideload(), and wp_handle_upload().
copy_dir ($from, $to, $skip_list = array())
Copies a directory from one location to another via the WordPress Filesystem Abstraction.
Assumes that WP_Filesystem() has already been called and setup.
Since
2.5.0
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $from source directory
string $to destination directory
array $skip_list a list of files/folders to skip copying
Returns
mixed WP_Error on failure, True on success.
Definition at line 812 of file wp-admin/includes/file.php.
References $from, __, elseif, is_wp_error(), and trailingslashit().
Referenced by WP_Upgrader\install_package(), and update_core().
download_url ($url, $timeout = 300)
Downloads a url to a local temporary file using the WordPress HTTP Class.
Please note, That the calling function must unlink() the file.
Since
2.5.0
Parameters
string $url the URL of the file to download
int $timeout The timeout for the request to download the file default 300 seconds
Returns
mixed WP_Error on failure, string Filename on success.
Definition at line 479 of file wp-admin/includes/file.php.
References $url, __, is_wp_error(), verify_file_md5(), wp_remote_retrieve_header(), wp_remote_retrieve_response_code(), wp_remote_retrieve_response_message(), wp_safe_remote_get(), and wp_tempnam().
Referenced by WP_Upgrader\download_package(), and media_sideload_image().
get_file_description ($file)
Get the description for standard WordPress theme files and other various standard WordPress files.
Since
1.5.0
array $wp_file_descriptions
Parameters
string $file Filesystem path or filename
Returns
string Description of file from $wp_file_descriptions or basename of $file if description doesn't exist. Appends 'Page Template' to basename of $file if the file is a page template
Definition at line 71 of file wp-admin/includes/file.php.
References $allowed_files, $file, $name, $wp_file_descriptions, __, _cleanup_header_comment(), and elseif.
get_filesystem_method ($args = array(), $context = false, $allow_relaxed_file_ownership = false)
Determines which method to use for reading, writing, modifying, or deleting files on the filesystem.
The priority of the transports are: Direct, SSH2, FTP PHP Extension, FTP Sockets (Via Sockets class, or fsockopen()). Valid values for these are: 'direct', 'ssh2', 'ftpext' or 'ftpsockets'.
The return value can be overridden by defining the FS_METHOD constant in wp-config.php, or filtering via {
See also
'filesystem_method'}.
Plugins may define a custom transport handler, See WP_Filesystem(). 2.5.0 callable $_wp_filesystem_direct_method array $args Optional. Connection details. Default empty array. string $context Optional. Full path to the directory that is tested for being writable. Default false. bool $allow_relaxed_file_ownership Optional. Whether to allow Group/World writable. Default false. string The transport to use, see description for valid return values.
Filter the filesystem method to use.
Since
2.6.0
Parameters
string $method Filesystem method to return.
array $args An array of connection details for the method.
string $context Full path to the directory that is tested for being writable.
bool $allow_relaxed_file_ownership Whether to allow Group/World writable.
Definition at line 949 of file wp-admin/includes/file.php.
References $GLOBALS, apply_filters(), elseif, trailingslashit(), and WP_CONTENT_DIR.
Referenced by request_filesystem_credentials(), WP_Filesystem(), and wp_print_request_filesystem_credentials_modal().
get_home_path ()
Get the absolute filesystem path to the root of the WordPress installation.
Since
1.5.0
Returns
string Full filesystem path to the root of the WordPress installation
Definition at line 95 of file wp-admin/includes/file.php.
References $_SERVER, $home_path, ABSPATH, get_option(), set_url_scheme(), str_replace, and trailingslashit().
Referenced by iis7_save_url_rewrite_rules(), make_site_theme_from_oldschool(), network_step2(), and save_mod_rewrite_rules().
list_files ($folder = '', $levels = 100)
Returns a listing of all files in the specified folder and all subdirectories up to 100 levels deep.
The depth of the recursiveness can be controlled by the $levels param.
Since
2.6.0
Parameters
string $folder Optional. Full path to folder. Default empty.
int $levels Optional. Levels of folders to follow, Default 100 (PHP Loop limit).
Returns
bool|array False on failure, Else array of files
Definition at line 120 of file wp-admin/includes/file.php.
References $dir, and $file.
request_filesystem_credentials ($form_post, $type = '', $error = false, $context = false, $extra_fields = null, $allow_relaxed_file_ownership = false)
Displays a form to the user to request for their FTP/SSH details in order to connect to the filesystem.
All chosen/entered details are saved, Excluding the Password.
Hostnames may be in the form of hostname:portnumber (eg: wordpress.org:2467) to specify an alternate FTP/SSH port.
Plugins may override this form by returning true|false via the {
See also
'request_filesystem_credentials'} filter.
Since
2.5.
string $pagenow
Parameters
string $form_post The URL to post the form to.
string $type Optional. Chosen type of filesystem. Default empty.
bool $error Optional. Whether the current request has failed to connect. Default false.
string $context Optional. Full path to the directory that is tested for being writable. Default false.
array $extra_fields Optional. Extra POST fields which should be checked for to be included in the post. Default null.
bool $allow_relaxed_file_ownership Optional. Whether to allow Group/World writable. Default false.
Returns
bool False on failure, true on success.
Filter the filesystem credentials form output.
Returning anything other than an empty string will effectively short-circuit output of the filesystem credentials form, returning that value instead.
Since
2.5.0
Parameters
mixed $output Form output to return instead. Default empty.
string $form_post The URL to post the form to.
string $type Chosen type of filesystem.
bool $error Whether the current request has failed to connect. Default false.
string $context Full path to the directory that is tested for being writable.
bool $allow_relaxed_file_ownership Whether to allow Group/World writable. Default false.
array $extra_fields Extra POST fields.
Filter the connection types to output to the filesystem credentials form.
Since
2.9.0
Parameters
array $types Types of connections.
array $credentials Credentials to connect with.
string $type Chosen filesystem method.
object $error Error object.
string $context Full path to the directory that is tested for being writable.
Definition at line 1039 of file wp-admin/includes/file.php.
References $field, $heading_tag, $name, $pagenow, $text, $types, __, _e, apply_filters(), checked(), disabled(), elseif, endforeach, endif, esc_attr(), esc_html, get_filesystem_method(), get_option(), input, is_wp_error(), label, name, placeholder, submit_button(), update_option(), wp_installing(), and wp_unslash().
Referenced by delete_plugins(), delete_theme(), do_core_upgrade(), and wp_print_request_filesystem_credentials_modal().
unzip_file ($file, $to)
Unzips a specified ZIP file to a location on the Filesystem via the WordPress Filesystem Abstraction.
Assumes that WP_Filesystem() has already been called and set up. Does not extract a root-level __MACOSX directory, if present.
Attempts to increase the PHP Memory limit to 256M before uncompressing, However, The most memory required shouldn't be much larger than the Archive itself.
Since
2.5.0
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $file Full path and filename of zip archive
string $to Full path on the filesystem to extract archive to
Returns
mixed WP_Error on failure, True on success
This filter is documented in wp-admin/admin.php
Filter whether to use ZipArchive to unzip archives.
Since
3.0.0
Parameters
bool $ziparchive Whether to use ZipArchive. Default true.
Definition at line 552 of file wp-admin/includes/file.php.
References $dir, $file, $i, $path, __, _unzip_file_pclzip(), _unzip_file_ziparchive(), apply_filters(), elseif, is_wp_error(), trailingslashit(), untrailingslashit(), and WP_MAX_MEMORY_LIMIT.
Referenced by WP_Upgrader\unpack_package().
validate_file_to_edit ($file, $allowed_files = '')
Make sure that the file that was requested to edit, is allowed to be edited.
Function will die if you are not allowed to edit the file
Since
1.5.0
Parameters
string $file file the users is attempting to edit
array $allowed_files Array of allowed files to edit, $file must match an entry exactly
Returns
string|null
Definition at line 205 of file wp-admin/includes/file.php.
References $allowed_files, $file, __, validate_file(), and wp_die().
verify_file_md5 ($filename, $expected_md5)
Calculates and compares the MD5 of a file to its expected value.
Since
3.7.0
Parameters
string $filename The filename to check the MD5 of.
string $expected_md5 The expected MD5 of the file, either a base64 encoded raw md5, or a hex-encoded md5
Returns
bool|object WP_Error on failure, true on success, false when the MD5 format is unknown/unexpected
Definition at line 521 of file wp-admin/includes/file.php.
References __, and elseif.
Referenced by download_url().
WP_Filesystem ($args = false, $context = false, $allow_relaxed_file_ownership = false)
Initialises and connects the WordPress Filesystem Abstraction classes.
This function will include the chosen transport and attempt connecting.
Plugins may add extra transports, And force WordPress to use them by returning the filename via the {
See also
'filesystem_method_file'} filter.
Since
2.5.0
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
array | false $args Optional. Connection args, These are passed directly to the WP_Filesystem_*() classes. Default false.
string | false $context Optional. Context for get_filesystem_method(). Default false.
bool $allow_relaxed_file_ownership Optional. Whether to allow Group/World writable. Default false.
Returns
null|bool false on failure, true on success.
Filter the path for a specific filesystem method class file.
Since
2.6.0
See also
get_filesystem_method()
Parameters
string $path Path to the specific filesystem method class file.
string $method The filesystem method to use.
Definition at line 869 of file wp-admin/includes/file.php.
References ABSPATH, apply_filters(), get_filesystem_method(), and is_wp_error().
Referenced by delete_plugins(), delete_theme(), do_core_upgrade(), and WP_Upgrader\fs_connect().
wp_handle_sideload (& $file, $overrides = false, $time = null)
Wrapper for _wp_handle_upload(), passes 'wp_handle_sideload' action.
Since
2.6.0
See also
_wp_handle_upload()
Parameters
array $file An array similar to that of a PHP $_FILES POST array
array | bool $overrides Optional. An associative array of names=>values to override default variables. Default false.
string $time Optional. Time formatted in 'yyyy/mm'. Default null.
Returns
array On success, returns an associative array of file attributes. On failure, returns $overrides['upload_error_handler'](&$file, $message) or array('error'=>$message).
Definition at line 456 of file wp-admin/includes/file.php.
References $action, $file, and _wp_handle_upload().
Referenced by media_handle_sideload().
wp_handle_upload (& $file, $overrides = false, $time = null)
Wrapper for _wp_handle_upload(), passes 'wp_handle_upload' action.
Since
2.0.0
See also
_wp_handle_upload()
Parameters
array $file Reference to a single element of $_FILES. Call the function once for each uploaded file.
array | bool $overrides Optional. An associative array of names=>values to override default variables. Default false.
string $time Optional. Time formatted in 'yyyy/mm'. Default null.
Returns
array On success, returns an associative array of file attributes. On failure, returns $overrides['upload_error_handler'](&$file, $message) or array('error'=>$message).
Definition at line 429 of file wp-admin/includes/file.php.
References $action, $file, and _wp_handle_upload().
Referenced by File_Upload_Upgrader\__construct(), media_handle_upload(), Custom_Image_Header\step_2_manage_upload(), and wp_import_handle_upload().
wp_print_request_filesystem_credentials_modal ()
Print the filesystem credentials modal when needed.
Since
4.2.0
Definition at line 1263 of file wp-admin/includes/file.php.
References get_filesystem_method(), request_filesystem_credentials(), role, self_admin_url(), and site_url().
wp_tempnam ($filename = '', $dir = '')
Returns a filename of a Temporary unique file.
Please note that the calling function must unlink() this itself.
The filename is based off the passed parameter or defaults to the current unix timestamp, while the directory can either be passed as well, or by leaving it blank, default to a writable temporary directory.
Since
2.6.0
Parameters
string $filename Optional. Filename to base the Unique file off. Default empty.
string $dir Optional. Directory to store the file in. Default empty.
Returns
string a writable filename
Definition at line 160 of file wp-admin/includes/file.php.
References $dir, get_temp_dir(), and wp_unique_filename().
Referenced by download_url(), WP_Filesystem_FTPext\get_contents(), WP_Filesystem_ftpsockets\get_contents(), WP_Filesystem_FTPext\put_contents(), and WP_Filesystem_ftpsockets\put_contents().
Variable Documentation
$wp_file_descriptions
The descriptions for theme files.
Definition at line 15 of file wp-admin/includes/file.php.
Referenced by get_file_description().