GravityView: theme.php File Reference
wp-admin/includes/theme.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_template_edit_filename ($fullpath, $containingfolder)
Tidies a filename for url display by the theme editor.
customize_themes_print_templates ()
Print JS templates for the theme-browsing UI in the Customizer.
delete_theme ($stylesheet, $redirect= '')
Remove a theme.
get_page_templates ($post=null)
Get the Page Templates available in this theme.
get_theme_feature_list ($api=true)
Retrieve list of WordPress theme features (aka theme tags)
get_theme_update_available ($theme)
Retrieve the update link if there is a theme update available.
theme_update_available ($theme)
Check if there is an update for a theme available.
themes_api ($action, $args=array())
Retrieves theme installer pages from the WordPress.org Themes API.
wp_prepare_themes_for_js ($themes=null)
Prepare themes for JavaScript.
Function Documentation
_get_template_edit_filename ($fullpath, $containingfolder)
Tidies a filename for url display by the theme editor.
Since
2.9.0 private
Parameters
string $fullpath Full path to the theme file
string $containingfolder Path of the theme parent folder
Returns
string
Definition at line 114 of file wp-admin/includes/theme.php.
References str_replace.
customize_themes_print_templates ()
Print JS templates for the theme-browsing UI in the Customizer.
Since
4.2.0
Definition at line 585 of file wp-admin/includes/theme.php.
References $preview_url, __, _e, add_query_arg(), esc_url, and str_replace.
delete_theme ($stylesheet, $redirect = '')
Remove a theme.
Since
2.8.0
WP_Filesystem_Base $wp_filesystem Subclass
Parameters
string $stylesheet Stylesheet of the theme to delete
string $redirect Redirect to page when complete.
Returns
void|bool|WP_Error When void, echoes content.
Definition at line 20 of file wp-admin/includes/theme.php.
References $redirect, $translations, __, ABSPATH, delete_site_transient(), exit, is_wp_error(), request_filesystem_credentials(), trailingslashit(), WP_Filesystem(), wp_get_installed_translations(), and wp_nonce_url().
get_page_templates ($post = null)
Get the Page Templates available in this theme.
Since
1.5.0
Parameters
WP_Post | null $post Optional. The post being edited, provided for context.
Returns
array Key is the template name, value is the filename of the template
Definition at line 100 of file wp-admin/includes/theme.php.
References $post, and wp_get_theme().
Referenced by page_attributes_meta_box(), page_template_dropdown(), and wp_xmlrpc_server\wp_getPageTemplates().
get_theme_feature_list ($api = true)
Retrieve list of WordPress theme features (aka theme tags)
Since
3.1.0
Parameters
bool $api Optional. Whether try to fetch tags from the WordPress.org API. Defaults to true.
Returns
array Array of features keyed by category with translations keyed by slug.
Definition at line 195 of file wp-admin/includes/theme.php.
References $feature_list, __, current_user_can(), get_site_transient(), is_wp_error(), set_site_transient(), and themes_api().
Referenced by install_themes_dashboard(), and WP_Theme\translate_header().
get_theme_update_available ($theme)
Retrieve the update link if there is a theme update available.
Will return a link if there is an update available.
Since
3.8.0
object $themes_update
Parameters
WP_Theme $theme WP_Theme object.
Returns
false|string HTML for the update link, or false if invalid info was passed.
Definition at line 144 of file wp-admin/includes/theme.php.
References $theme, $update, __, add_query_arg(), admin_url(), current_user_can(), elseif, esc_url, get_site_transient(), is_multisite(), null, and wp_nonce_url().
Referenced by theme_update_available(), and wp_prepare_themes_for_js().
theme_update_available ($theme)
Check if there is an update for a theme available.
Will display link, if there is an update available.
Since
2.7.0
See also
get_theme_update_available()
Parameters
WP_Theme $theme Theme data object.
Definition at line 128 of file wp-admin/includes/theme.php.
References $theme, and get_theme_update_available().
Referenced by WP_Themes_List_Table\display_rows().
themes_api ($action, $args = array())
Retrieves theme installer pages from the WordPress.org Themes API.
It is possible for a theme to override the Themes API result with three filters. Assume this is for themes, which can extend on the Theme Info to offer more choices. This is very powerful and must be used with care, when overriding the filters.
The first filter, {
See also
'themes_api_args'}, is for the args and gives the action as the second parameter. The hook for {
'themes_api_args'} must ensure that an object is returned.
The second filter, {
See also
'themes_api'}, allows a plugin to override the WordPress.org Theme API entirely. If $action is 'query_themes', 'theme_information', or 'feature_list', an object MUST be passed. If $action is 'hot_tags`, an array should be passed.
Finally, the third filter, {
See also
'themes_api_result'}, makes it possible to filter the response object or array, depending on the $action type.
Supported arguments per action:
Argument Name 'query_themes' 'theme_information' 'hot_tags' 'feature_list'
$slug No Yes No No
$per_page Yes No No No
$page Yes No No No
$number No No Yes No
$search Yes No No No
$tag Yes No No No
$author Yes No No No
$user Yes No No No
$browse Yes No No No
$locale Yes Yes No No
$fields Yes Yes No No
Since
2.8.0
Parameters
string $action API action to perform: 'query_themes', 'theme_information', 'hot_tags' or 'feature_list'.
array | object $args { Optional. Array or object of arguments to serialize for the Plugin Info API.
string $slug The plugin slug. Default empty. int $per_page Number of themes per page. Default 24. int $page Number of current page. Default 1. int $number Number of tags to be queried. string $search A search term. Default empty. string $tag Tag to filter themes. Default empty. string $author Username of an author to filter themes. Default empty. string $user Username to query for their favorites. Default empty. string $browse Browse view: 'featured', 'popular', 'updated', 'favorites'. string $locale Locale to provide context-sensitive results. Default is the value of get_locale(). array $fields { Array of fields which should or should not be returned.
bool $description Whether to return the theme full description. Default false. bool $sections Whether to return the theme readme sections: description, installation, FAQ, screenshots, other notes, and changelog. Default false. bool $rating Whether to return the rating in percent and total number of ratings. Default false. bool $ratings Whether to return the number of rating for each star (1-5). Default false. bool $downloaded Whether to return the download count. Default false. bool $downloadlink Whether to return the download link for the package. Default false. bool $last_updated Whether to return the date of the last update. Default false. bool $tags Whether to return the assigned tags. Default false. bool $homepage Whether to return the theme homepage link. Default false. bool $screenshots Whether to return the screenshots. Default false. int $screenshot_count Number of screenshots to return. Default 1. bool $screenshot_url Whether to return the URL of the first screenshot. Default false. bool $photon_screenshots Whether to return the screenshots via Photon. Default false. bool $template Whether to return the slug of the parent theme. Default false. bool $parent Whether to return the slug, name and homepage of the parent theme. Default false. bool $versions Whether to return the list of all available versions. Default false. bool $theme_url Whether to return theme's URL. Default false. bool $extended_author Whether to return nicename or nicename and display name. Default false. } }
Returns
object|array|WP_Error Response object or array on success, WP_Error on failure. See the function reference article for more information on the make-up of possible return objects depending on the value of $action.
Filter arguments used to query for installer pages from the WordPress.org Themes API.
Important: An object MUST be returned to this filter.
Since
2.8.0
Parameters
object $args Arguments used to query for installer pages from the WordPress.org Themes API.
string $action Requested action. Likely values are 'theme_information', 'feature_list', or 'query_themes'.
Filter whether to override the WordPress.org Themes API.
Passing a non-false value will effectively short-circuit the WordPress.org API request.
If $action is 'query_themes', 'theme_information', or 'feature_list', an object MUST be passed. If $action is 'hot_tags`, an array should be passed.
Since
2.8.0
Parameters
false | object | array $override Whether to override the WordPress.org Themes API. Default false.
string $action Requested action. Likely values are 'theme_information', 'feature_list', or 'query_themes'.
object $args Arguments used to query for installer pages from the Themes API.
Filter the returned WordPress.org Themes API response.
Since
2.8.0
Parameters
array | object $res WordPress.org Themes API response.
string $action Requested action. Likely values are 'theme_information', 'feature_list', or 'query_themes'.
object $args Arguments used to query for installer pages from the WordPress.org Themes API.
Definition at line 381 of file wp-admin/includes/theme.php.
References $action, $url, __, apply_filters(), DOING_AJAX, get_locale(), is_wp_error(), maybe_unserialize(), object, set_url_scheme(), WP_DEBUG, wp_http_supports(), wp_remote_post(), and wp_remote_retrieve_body().
Referenced by Theme_Upgrader\check_parent_theme_filter(), get_theme_feature_list(), install_theme_information(), install_themes_feature_list(), WP_Theme_Install_List_Table\prepare_items(), and wp_ajax_query_themes().
wp_prepare_themes_for_js ($themes = null)
Prepare themes for JavaScript.
Since
3.8.0
Parameters
array $themes Optional. Array of WP_Theme objects to prepare. Defaults to all allowed themes.
Returns
array An associative array of theme data, sorted by name.
Filter theme data before it is prepared for JavaScript.
Passing a non-empty array will result in wp_prepare_themes_for_js() returning early with that value instead.
Since
4.2.0
Parameters
array $prepared_themes An associative array of theme data. Default empty array.
null | array $themes An array of WP_Theme objects to prepare, if any.
string $current_theme The current theme slug.
Filter the themes prepared for JavaScript, for themes.php.
Could be useful for changing the order, which is by name by default.
Since
3.8.0
Parameters
array $prepared_themes Array of themes.
Definition at line 477 of file wp-admin/includes/theme.php.
References $_SERVER, $theme, add_query_arg(), admin_url(), apply_filters(), current_user_can(), esc_url, esc_url_raw(), get_site_transient(), get_stylesheet(), get_theme_update_available(), null, WP_Theme\sort_by_name(), wp_customize_url(), wp_get_theme(), wp_get_themes(), wp_nonce_url(), and wp_unslash().
Referenced by WP_Customize_Manager\register_controls().