GravityView: widgets.php File Reference
wp-admin/includes/widgets.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_sort_name_callback ($a, $b)
Callback to sort array by a 'name' key.
next_widget_id_number ($id_base)
array $wp_registered_widgets
wp_list_widget_controls ($sidebar, $sidebar_name= '')
Show the widgets and their settings for a sidebar.
wp_list_widget_controls_dynamic_sidebar ($params)
Retrieves the widget control arguments.
wp_list_widgets ()
Display list of the available widgets.
wp_widget_control ($sidebar_args)
Meta widget used to display the control form for a widget.
wp_widgets_access_body_class ($classes)
Function Documentation
_sort_name_callback ($a, $b)
Callback to sort array by a 'name' key.
Since
3.1.0 private
Returns
int
Definition at line 60 of file wp-admin/includes/widgets.php.
next_widget_id_number ($id_base)
array $wp_registered_widgets
Parameters
string $id_base
Returns
int
Definition at line 142 of file wp-admin/includes/widgets.php.
References $wp_registered_widgets.
Referenced by WP_Customize_Widgets\get_available_widgets(), and wp_list_widgets().
wp_list_widget_controls ($sidebar, $sidebar_name = '')
Show the widgets and their settings for a sidebar.
Used in the admin widget config screen.
Since
2.5.0
Parameters
string $sidebar Sidebar ID.
string $sidebar_name Optional. Sidebar name. Default empty.
Definition at line 73 of file wp-admin/includes/widgets.php.
References $description, add_filter(), dynamic_sidebar(), esc_attr(), esc_html, and wp_sidebar_description().
wp_list_widget_controls_dynamic_sidebar ($params)
Retrieves the widget control arguments.
Since
2.5.0
array $wp_registered_widgets
int $i
Parameters
array $params
Returns
array
Definition at line 114 of file wp-admin/includes/widgets.php.
References $i, $id, and $wp_registered_widgets.
Referenced by WP_Customize_Widgets\get_available_widgets(), WP_Widget_Form_Customize_Control\to_json(), and wp_list_widgets().
wp_list_widgets ()
Display list of the available widgets.
Since
2.5.0
array $wp_registered_widgets array $wp_registered_widget_controls
Definition at line 17 of file wp-admin/includes/widgets.php.
References $wp_registered_widget_controls, $wp_registered_widgets, is_active_widget(), next_widget_id_number(), and wp_list_widget_controls_dynamic_sidebar().
wp_widget_control ($sidebar_args)
Meta widget used to display the control form for a widget.
Called from dynamic_sidebar().
Since
2.5.0
array $wp_registered_widgets array $wp_registered_widget_controls array $sidebars_widgets
Parameters
array $sidebar_args
Returns
array
Definition at line 169 of file wp-admin/includes/widgets.php.
References $sidebars_widgets, $wp_registered_widget_controls, $wp_registered_widgets, __, _e, _ex(), esc_attr(), esc_html, input, name, submit_button(), and wp_widget_description().
wp_widgets_access_body_class ($classes)
Parameters
string $classes
Returns
string
Definition at line 279 of file wp-admin/includes/widgets.php.