GravityView: ms-deprecated.php File Reference
wp-admin/includes/ms-deprecated.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
activate_sitewide_plugin ()
Deprecated functionality for activating a network-only plugin.
deactivate_sitewide_plugin ($plugin=false)
Deprecated functionality for deactivating a network-only plugin.
get_site_allowed_themes ()
Deprecated functionality for getting themes network-enabled themes.
is_wpmu_sitewide_plugin ($file)
Deprecated functionality for determining if the current plugin is network-only.
ms_deprecated_blogs_file ()
Deprecated functionality for determining whether a file is deprecated.
mu_options ($options)
WPMU options.
wpmu_checkAvailableSpace ()
Determines if the available space defined by the admin has been exceeded by the user.
wpmu_get_blog_allowedthemes ($blog_id=0)
Deprecated functionality for getting themes allowed on a specific site.
wpmu_menu ()
Outputs the WPMU menu.
Function Documentation
activate_sitewide_plugin ()
Deprecated functionality for activating a network-only plugin.
Definition at line 52 of file wp-admin/includes/ms-deprecated.php.
References _deprecated_function().
deactivate_sitewide_plugin ($plugin = false)
Deprecated functionality for deactivating a network-only plugin.
Definition at line 63 of file wp-admin/includes/ms-deprecated.php.
References _deprecated_function().
get_site_allowed_themes ()
Deprecated functionality for getting themes network-enabled themes.
Definition at line 84 of file wp-admin/includes/ms-deprecated.php.
References _deprecated_function(), and WP_Theme\get_allowed_on_network().
is_wpmu_sitewide_plugin ($file)
Deprecated functionality for determining if the current plugin is network-only.
Definition at line 73 of file wp-admin/includes/ms-deprecated.php.
References $file, _deprecated_function(), and is_network_only_plugin().
ms_deprecated_blogs_file ()
Deprecated functionality for determining whether a file is deprecated.
Definition at line 105 of file wp-admin/includes/ms-deprecated.php.
mu_options ($options)
WPMU options.
Definition at line 41 of file wp-admin/includes/ms-deprecated.php.
References $options, and _deprecated_function().
wpmu_checkAvailableSpace ()
Determines if the available space defined by the admin has been exceeded by the user.
Definition at line 29 of file wp-admin/includes/ms-deprecated.php.
References __, _deprecated_function(), is_upload_space_available(), and wp_die().
wpmu_get_blog_allowedthemes ($blog_id = 0)
Deprecated functionality for getting themes allowed on a specific site.
Definition at line 95 of file wp-admin/includes/ms-deprecated.php.
References $blog_id, _deprecated_function(), and WP_Theme\get_allowed_on_site().
wpmu_menu ()
Outputs the WPMU menu.
Definition at line 18 of file wp-admin/includes/ms-deprecated.php.
References _deprecated_function().