GravityView: install.php File Reference
wp-admin/install.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
display_header ($body_classes= '')
Display install header.
display_setup_form ($error=null)
Display installer setup form.
Variables
if(!$mysql_compat||!$php_compat) if(!is_string($wpdb->base_prefix)|| ''===$wpdb->base_prefix) if(defined('DO_NOT_UPGRADE_GLOBAL_TABLES')) $language = ''
string $wp_local_package WP_Locale $wp_locale
$mysql_compat = version_compare($mysql_version, $required_mysql_version, '>=') || file_exists(WP_CONTENT_DIR . '/db.php')
$mysql_version = $wpdb->db_version()
$php_compat = version_compare($php_version, $required_php_version, '>=')
$php_version = phpversion()
if(is_blog_installed()) global $required_mysql_version
if(is_blog_installed()) global $required_php_version
if(!empty($_REQUEST['language'])) elseif(isset($GLOBALS['wp_local_package'])) $scripts_to_print = array('jquery')
$step = isset($_GET['step']) ? (int) $_GET['step'] : 0
if(is_blog_installed()) global $wp_version
string $wp_version string $required_php_version string $required_mysql_version wpdb $wpdb
const WP_INSTALLING true
Function Documentation
display_header ($body_classes = '')
Display install header.
Since
2.5.0
Parameters
string $body_classes
Definition at line 58 of file wp-admin/install.php.
References _e, is_rtl(), language_attributes(), name, and wp_admin_css().
display_setup_form ($error = null)
Display installer setup form.
Since
2.8.0
Parameters
string | null $error
This action is documented in wp-admin/options-reading.php
Definition at line 92 of file wp-admin/install.php.
References $wpdb, __, _e, _ex(), checked(), do_action(), endif, has_action(), input, label, name, null, size, submit_button(), and wp_unslash().
Variable Documentation
if (!$mysql_compat||!$php_compat) if (!is_string($wpdb->base_prefix)|| ''===$wpdb->base_prefix) if (defined('DO_NOT_UPGRADE_GLOBAL_TABLES')) $language = ''
string $wp_local_package WP_Locale $wp_locale
Definition at line 257 of file wp-admin/install.php.
Referenced by GF_Field_CAPTCHA\get_field_input(), wp_dropdown_languages(), wp_get_installed_translations(), and wp_install_language_form().
$mysql_compat = version_compare($mysql_version, $required_mysql_version, '>=') || file_exists(WP_CONTENT_DIR . '/db.php')
Definition at line 228 of file wp-admin/install.php.
Referenced by list_core_update(), WP_Automatic_Updater\should_update(), and update_core().
$mysql_version = $wpdb->db_version()
Definition at line 226 of file wp-admin/install.php.
Referenced by list_core_update(), update_core(), and wp_version_check().
$php_compat = version_compare($php_version, $required_php_version, '>=')
Definition at line 227 of file wp-admin/install.php.
Referenced by list_core_update(), WP_Automatic_Updater\should_update(), and update_core().
$php_version = phpversion()
Definition at line 225 of file wp-admin/install.php.
Referenced by list_core_update(), update_core(), wp_check_php_mysql_versions(), and wp_version_check().
if (is_blog_installed()) global $required_mysql_version
Definition at line 212 of file wp-admin/install.php.
Referenced by wpdb\check_database_version(), core_upgrade_preamble(), and update_core().
if (is_blog_installed()) global $required_php_version
Definition at line 212 of file wp-admin/install.php.
Referenced by core_upgrade_preamble(), update_core(), and wp_check_php_mysql_versions().
if (!empty($_REQUEST['language'])) elseif (isset($GLOBALS['wp_local_package'])) $scripts_to_print = array('jquery')
Definition at line 264 of file wp-admin/install.php.
$step = isset($_GET['step']) ? (int) $_GET['step'] : 0
Definition at line 49 of file wp-admin/install.php.
Referenced by GF_Installation_Wizard\__construct(), Custom_Image_Header\admin_page(), GF_Installation_Wizard\complete_installation(), Custom_Image_Header\css_includes(), GF_Installation_Wizard\get_step(), GF_Installation_Wizard\get_step_index(), Custom_Image_Header\js(), Custom_Image_Header\js_includes(), GF_Installation_Wizard\progress(), Custom_Image_Header\step(), and GF_Installation_Wizard\summary().
if (is_blog_installed()) global $wp_version
string $wp_version string $required_php_version string $required_mysql_version wpdb $wpdb
Definition at line 212 of file wp-admin/install.php.
const WP_INSTALLING true
Definition at line 33 of file wp-admin/install.php.