GravityView: nav-menu.php File Reference
wp-admin/includes/nav-menu.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_ajax_menu_quick_search ($request=array())
Walker_Nav_Menu_Edit class.
_wp_delete_orphaned_draft_menu_items ()
Deletes orphaned draft menu items.
_wp_nav_menu_meta_box_object ($object=null)
Adds custom arguments to some of the meta box object types.
wp_get_nav_menu_to_edit ($menu_id=0)
Returns the menu formatted to edit.
wp_initial_nav_menu_meta_boxes ()
Limit the amount of meta boxes to pages, posts, links, and categories for first time users.
wp_nav_menu_disabled_check ($nav_menu_selected_id)
Check whether to disable the Menu Locations meta box submit button.
wp_nav_menu_item_link_meta_box ()
Displays a metabox for the custom links menu item.
wp_nav_menu_item_post_type_meta_box ($object, $post_type)
Displays a metabox for a post type menu item.
wp_nav_menu_item_taxonomy_meta_box ($object, $taxonomy)
Displays a metabox for a taxonomy menu item.
wp_nav_menu_manage_columns ()
Returns the columns for the nav menus page.
wp_nav_menu_post_type_meta_boxes ()
Creates metaboxes for any post type menu item.
wp_nav_menu_setup ()
Register nav menu metaboxes and advanced menu items.
wp_nav_menu_taxonomy_meta_boxes ()
Creates metaboxes for any taxonomy menu item.
wp_nav_menu_update_menu_items ($nav_menu_selected_id, $nav_menu_selected_title)
Saves nav menu items.
wp_save_nav_menu_items ($menu_id=0, $menu_data=array())
Save posted nav menu item data.
Function Documentation
_wp_ajax_menu_quick_search ($request = array())
Walker_Nav_Menu_Edit class.
Walker_Nav_Menu_Checklist class Prints the appropriate response to a menu quick search.
Since
3.0.0
Parameters
array $request The unsanitized request values.
Definition at line 23 of file wp-admin/includes/nav-menu.php.
References elseif, get_post(), get_post_type(), get_post_type_object(), get_term(), get_terms(), get_the_ID(), get_the_title(), have_posts(), is_wp_error(), post_type_exists(), query_posts(), taxonomy_exists(), the_post(), walk_nav_menu_tree(), and wp_json_encode().
Referenced by wp_ajax_menu_quick_search().
_wp_delete_orphaned_draft_menu_items ()
Deletes orphaned draft menu items.
private
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 964 of file wp-admin/includes/nav-menu.php.
References $wpdb, and wp_delete_post().
_wp_nav_menu_meta_box_object ($object = null)
Adds custom arguments to some of the meta box object types.
Since
3.0.0
private
Parameters
object $object The post type or taxonomy meta-object.
Returns
object The post type of taxonomy object.
Definition at line 837 of file wp-admin/includes/nav-menu.php.
References elseif.
wp_get_nav_menu_to_edit ($menu_id = 0)
Returns the menu formatted to edit.
Since
3.0.0
Parameters
int $menu_id Optional. The ID of the menu to format. Default 0.
Returns
string|WP_Error $output The menu formatted to edit or error object on failure.
Filter the Walker class used when adding nav menu items.
Since
3.0.0
Parameters
string $class The walker class to use. Default 'Walker_Nav_Menu_Edit'.
int $menu_id ID of the menu being rendered.
Definition at line 878 of file wp-admin/includes/nav-menu.php.
References $menu, $menu_items, __, apply_filters(), elseif, is_nav_menu(), is_wp_error(), walk_nav_menu_tree(), wp_get_nav_menu_items(), and wp_get_nav_menu_object().
wp_initial_nav_menu_meta_boxes ()
Limit the amount of meta boxes to pages, posts, links, and categories for first time users.
Since
3.0.0
array $wp_meta_boxes
Definition at line 151 of file wp-admin/includes/nav-menu.php.
References $user, get_user_option(), and update_user_option().
wp_nav_menu_disabled_check ($nav_menu_selected_id)
Check whether to disable the Menu Locations meta box submit button.
Since
3.6.0
bool $one_theme_location_no_menus to determine if no menus exist
Parameters
int | string $nav_menu_selected_id (id, name or slug) of the currently-selected menu
Returns
string Disabled attribute if at least one menu exists, false if not
Definition at line 241 of file wp-admin/includes/nav-menu.php.
References $nav_menu_selected_id, $one_theme_location_no_menus, and disabled().
Referenced by wp_nav_menu_item_link_meta_box(), wp_nav_menu_item_post_type_meta_box(), and wp_nav_menu_item_taxonomy_meta_box().
wp_nav_menu_item_link_meta_box ()
Displays a metabox for the custom links menu item.
Since
3.0.0
int $_nav_menu_placeholder int|string $nav_menu_selected_id
Definition at line 258 of file wp-admin/includes/nav-menu.php.
References $nav_menu_selected_id, _e, input, label, name, and wp_nav_menu_disabled_check().
wp_nav_menu_item_post_type_meta_box ($object, $post_type)
Displays a metabox for a post type menu item.
Since
3.0.0
int $_nav_menu_placeholder int|string $nav_menu_selected_id
Parameters
string $object Not used.
string $post_type The post type object.
Filter the posts displayed in the 'Most Recent' tab of the current post type's menu items meta box.
The dynamic portion of the hook name, $post_type_name, refers to the post type name.
Since
4.3.0
Parameters
array $most_recent An array of post objects being listed.
array $args An array of WP_Query arguments.
object $post_type The current post type object for this menu item meta box.
Filter the posts displayed in the 'View All' tab of the current post type's menu items meta box.
The dynamic portion of the hook name, $post_type_name, refers to the slug of the current post type.
Since
3.2.0
See also
WP_Query::query()
Parameters
array $posts The posts for the current post type.
array $args An array of WP_Query arguments.
object $post_type The current post type object for this menu item meta box.
Definition at line 302 of file wp-admin/includes/nav-menu.php.
References $nav_menu_selected_id, $pagenum, $post_type, $recent_args, __, _e, _x, absint(), add_query_arg(), apply_filters(), elseif, endif, esc_attr(), get_option(), get_post(), get_post_type_archive_link(), get_post_type_object(), get_posts(), home_url(), input, is_post_type_hierarchical(), is_wp_error(), li, name, paginate_links(), WP_Query\query(), submit_button(), walk_nav_menu_tree(), and wp_nav_menu_disabled_check().
wp_nav_menu_item_taxonomy_meta_box ($object, $taxonomy)
Displays a metabox for a taxonomy menu item.
Since
3.0.0
int|string $nav_menu_selected_id
Parameters
string $object Not used.
string $taxonomy The taxonomy object.
Definition at line 579 of file wp-admin/includes/nav-menu.php.
References $nav_menu_selected_id, $pagenum, __, _e, absint(), add_query_arg(), elseif, endif, esc_attr(), get_terms(), input, is_taxonomy_hierarchical(), is_wp_error(), li, name, paginate_links(), submit_button(), walk_nav_menu_tree(), wp_count_terms(), and wp_nav_menu_disabled_check().
wp_nav_menu_manage_columns ()
Returns the columns for the nav menus page.
Since
3.0.0
Returns
string|WP_Error $output The menu formatted to edit or error object on failure.
Definition at line 944 of file wp-admin/includes/nav-menu.php.
References __.
wp_nav_menu_post_type_meta_boxes ()
Creates metaboxes for any post type menu item.
Since
3.0.0
Filter whether a menu items meta box will be added for the current object type.
If a falsey value is returned instead of an object, the menu items meta box for the current meta box object will not be added.
Since
3.0.0
Parameters
object $meta_box_object The current object to add a menu items meta box for.
Definition at line 181 of file wp-admin/includes/nav-menu.php.
References $id, $post_type, add_meta_box(), apply_filters(), and get_post_types().
Referenced by wp_nav_menu_setup().
wp_nav_menu_setup ()
Register nav menu metaboxes and advanced menu items.
Since
3.0.0
Definition at line 126 of file wp-admin/includes/nav-menu.php.
References $user, __, add_filter(), add_meta_box(), get_user_option(), update_user_option(), wp_nav_menu_post_type_meta_boxes(), and wp_nav_menu_taxonomy_meta_boxes().
wp_nav_menu_taxonomy_meta_boxes ()
Creates metaboxes for any taxonomy menu item.
Since
3.0.0
This filter is documented in wp-admin/includes/nav-menu.php
Definition at line 215 of file wp-admin/includes/nav-menu.php.
References $id, $tax, add_meta_box(), apply_filters(), and get_taxonomies().
Referenced by wp_nav_menu_setup().
wp_nav_menu_update_menu_items ($nav_menu_selected_id, $nav_menu_selected_title)
Saves nav menu items.
Since
3.6.0
Parameters
int | string $nav_menu_selected_id (id, slug, or name) of the currently-selected menu
string $nav_menu_selected_title Title of the currently-selected menu
Returns
array $messages The menu updated message
This action is documented in wp-includes/nav-menu.php
Definition at line 984 of file wp-admin/includes/nav-menu.php.
References $field, $menu_items, $messages, $nav_menu_selected_id, $nav_menu_selected_title, __, ARRAY_A, do_action(), get_option(), is_nav_menu_item(), is_wp_error(), update_option(), wp_defer_term_counting(), wp_delete_post(), wp_get_nav_menu_items(), wp_get_nav_menus(), and wp_update_nav_menu_item().
wp_save_nav_menu_items ($menu_id = 0, $menu_data = array())
Save posted nav menu item data.
Since
3.0.0
Parameters
int $menu_id The menu ID for which to save this item. $menu_id of 0 makes a draft, orphaned menu item.
array $menu_data The unsanitized posted menu item data.
Returns
array The database IDs of the items saved
Definition at line 768 of file wp-admin/includes/nav-menu.php.
References is_nav_menu(), and wp_update_nav_menu_item().
Referenced by wp_ajax_add_menu_item().