GravityView: comment.php File Reference
wp-admin/includes/comment.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
comment_exists ($comment_author, $comment_date, $timezone= 'blog')
Determine if a comment exists based on author and date.
comment_footer_die ($msg)
Display error message at bottom of comments.
edit_comment ()
Update a comment with values provided in $_POST.
enqueue_comment_hotkeys_js ()
floated_admin_avatar ($name)
Add avatars to relevant places in admin, or try to.
get_comment_to_edit ($id)
Returns a WP_Comment object based on comment ID.
get_pending_comments_num ($post_id)
Get the number of pending comments on a post or posts.
Function Documentation
comment_exists ($comment_author, $comment_date, $timezone = 'blog')
Determine if a comment exists based on author and date.
For best performance, use $timezone = 'gmt', which queries a field that is properly indexed. The default value for $timezone is 'blog' for legacy reasons.
Since
2.0.0
4.4.0 Added the $timezone parameter.
wpdb $wpdb WordPress database abstraction object.
Parameters
string $comment_author Author of the comment.
string $comment_date Date of the comment.
string $timezone Timezone. Accepts 'blog' or 'gmt'. Default 'blog'.
Returns
mixed Comment post ID on success.
Definition at line 27 of file wp-admin/includes/comment.php.
References $wpdb.
comment_footer_die ($msg)
Display error message at bottom of comments.
Parameters
string $msg Error Message. Assumed to contain HTML and be sanitized.
Definition at line 192 of file wp-admin/includes/comment.php.
References ABSPATH.
edit_comment ()
Update a comment with values provided in $_POST.
Since
2.0.0
Definition at line 47 of file wp-admin/includes/comment.php.
References __, current_user_can(), wp_die(), and wp_update_comment().
Referenced by wp_ajax_edit_comment().
enqueue_comment_hotkeys_js ()
Since
2.7.0
Definition at line 182 of file wp-admin/includes/comment.php.
References get_user_option(), and wp_enqueue_script().
floated_admin_avatar ($name)
Add avatars to relevant places in admin, or try to.
Since
2.5.0
Parameters
string $name User name.
Returns
string Avatar with Admin name.
Definition at line 174 of file wp-admin/includes/comment.php.
References get_comment().
get_comment_to_edit ($id)
Returns a WP_Comment object based on comment ID.
Since
2.0.0
Parameters
int $id ID of comment to retrieve.
Returns
WP_Comment|false Comment if found. False on failure.
Filter the comment content before editing.
Since
2.0.0
Parameters
string $comment-,>comment_content Comment content.
Definition at line 96 of file wp-admin/includes/comment.php.
References $comment, $id, apply_filters(), esc_url, format_to_edit(), and get_comment().
get_pending_comments_num ($post_id)
Get the number of pending comments on a post or posts.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | array $post_id Either a single Post ID or an array of Post IDs
Returns
int|array Either a single Posts pending comments as an int or an array of ints keyed on the Post IDs
Definition at line 131 of file wp-admin/includes/comment.php.
References $id, $post_id, $wpdb, absint(), and ARRAY_A.
Referenced by WP_Posts_List_Table\_display_rows(), WP_Media_List_Table\column_comments(), WP_Comments_List_Table\column_response(), WP_Media_List_Table\display_rows(), and WP_Comments_List_Table\prepare_items().