GravityView: media.php File Reference
wp-admin/includes/media.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_cleanup_image_add_caption ($matches)
Private preg_replace callback used in image_add_caption()
attachment_submitbox_metadata ()
Displays non-editable attachment metadata in the publish metabox.
edit_form_image_editor ($post)
Displays the image and editor in the post editor.
get_attachment_fields_to_edit ($post, $errors=null)
Retrieves the attachment fields to edit form fields.
get_compat_media_markup ($attachment_id, $args=null)
get_image_send_to_editor ($id, $caption, $title, $align, $url= '', $rel= '', $size= 'medium', $alt= '')
Retrieves the image HTML to send to the editor.
get_media_item ($attachment_id, $args=null)
Retrieve HTML form for modifying the image attachment.
get_media_items ($post_id, $errors)
Retrieve HTML for media items of post gallery.
get_upload_iframe_src ($type=null, $post_id=null, $tab=null)
int $post_ID
image_add_caption ($html, $id, $caption, $title, $align, $url, $size, $alt= '')
Adds image shortcode with caption to editor.
image_align_input_fields ($post, $checked= '')
Retrieve HTML for the image alignment radio buttons with the specified one checked.
image_attachment_fields_to_edit ($form_fields, $post)
Retrieves the image attachment fields to edit form fields.
image_attachment_fields_to_save ($post, $attachment)
Filters input from media_upload_form_handler() and assigns a default post_title from the file name if none supplied.
image_link_input_fields ($post, $url_type= '')
Retrieve HTML for the Link URL buttons with the default link type as specified.
image_media_send_to_editor ($html, $attachment_id, $attachment)
Retrieves the media element HTML to send to the editor.
image_size_input_fields ($post, $check= '')
Retrieve HTML for the size radio buttons with the specified one checked.
media_buttons ($editor_id= 'content')
Adds the media button to the editor.
media_handle_sideload ($file_array, $post_id, $desc=null, $post_data=array())
This handles a sideloaded file in the same way as an uploaded file is handled by media_handle_upload().
media_handle_upload ($file_id, $post_id, $post_data=array(), $overrides=array('test_form'=> false))
Save a file submitted from a POST request and create an attachment post for it.
media_post_single_attachment_fields_to_edit ($form_fields, $post)
Retrieves the post non-image attachment fields to edito form fields.
media_send_to_editor ($html)
Adds image html to editor.
media_sideload_image ($file, $post_id, $desc=null, $return= 'html')
Downloads an image from the specified URL and attaches it to a post.
media_single_attachment_fields_to_edit ($form_fields, $post)
Retrieves the single non-image attachment fields to edit form fields.
media_upload_flash_bypass ()
Displays the multi-file uploader message.
media_upload_form ($errors=null)
Outputs the legacy media upload form.
media_upload_form_handler ()
Handles form submissions for the legacy media uploader.
media_upload_gallery ()
Retrieves the legacy media uploader form in an iframe.
media_upload_gallery_form ($errors)
Adds gallery form to upload iframe.
media_upload_header ()
Outputs the legacy media upload header.
media_upload_html_bypass ()
Displays the browser's built-in uploader message.
media_upload_library ()
Retrieves the legacy media library form in an iframe.
media_upload_library_form ($errors)
Outputs the legacy media upload form for the media library.
media_upload_max_image_resize ()
Displays the checkbox to scale images.
media_upload_tabs ()
Defines the default media upload tabs.
media_upload_text_after ()
Used to display a "After a file has been uploaded..." help message.
media_upload_type_form ($type= 'file', $errors=null, $id=null)
Outputs the legacy media upload form for a given media type.
media_upload_type_url_form ($type=null, $errors=null, $id=null)
Outputs the legacy media upload form for external media.
multisite_over_quota_message ()
Displays the out of storage quota message in Multisite.
the_media_upload_tabs ()
Outputs the legacy media upload tabs UI.
update_gallery_tab ($tabs)
Adds the gallery tab back to the tabs array if post has image attachments.
wp_add_id3_tag_data (&$metadata, $data)
Parse ID3v2, ID3v1, and getID3 comments to extract usable data.
wp_caption_input_textarea ($edit_post)
Output a textarea element for inputting an attachment caption.
wp_iframe ($content_func)
Adds the iframe to display content for the media upload page.
wp_media_attach_action ($parent_id, $action= 'attach')
Encapsulate logic for Attach/Detach actions.
wp_media_insert_url_form ($default_view= 'image')
Creates the form for external url.
wp_media_upload_handler ()
Handles the process of uploading media.
wp_read_audio_metadata ($file)
Retrieve metadata from a audio file's ID3 tags.
wp_read_video_metadata ($file)
Retrieve metadata from a video file's ID3 tags.
Function Documentation
_cleanup_image_add_caption ($matches)
Private preg_replace callback used in image_add_caption()
private
Since
3.4.0
Definition at line 235 of file wp-admin/includes/media.php.
attachment_submitbox_metadata ()
Displays non-editable attachment metadata in the publish metabox.
Since
3.5.0
This filter is documented in wp-admin/includes/media.php
Filter the audio and video metadata fields to be shown in the publish meta box.
The key for each item in the array should correspond to an attachment metadata key, and the value should be the desired label.
Since
3.7.0
Parameters
array $fields An array of the attachment metadata keys and labels.
Filter the audio attachment metadata fields to be shown in the publish meta box.
The key for each item in the array should correspond to an attachment metadata key, and the value should be the desired label.
Since
3.7.0
Parameters
array $fields An array of the attachment metadata keys and labels.
Definition at line 2801 of file wp-admin/includes/media.php.
References $file, $label, $post, __, _e, apply_filters(), elseif, endif, esc_html, get_attached_file(), get_post(), input, label, name, size_format(), str_replace, wp_basename(), wp_get_attachment_metadata(), and wp_get_attachment_url().
edit_form_image_editor ($post)
Displays the image and editor in the post editor.
Since
3.5.0
Parameters
WP_Post $post A post object.
Definition at line 2694 of file wp-admin/includes/media.php.
References $post, $quicktags_settings, __, _e, ABSPATH, elseif, endif, esc_attr__(), get_compat_media_markup(), get_post_meta(), get_post_thumbnail_id(), input, label, name, textarea, wp_attachment_is(), wp_attachment_is_image(), wp_audio_shortcode(), wp_editor(), wp_get_attachment_image_src(), wp_get_attachment_metadata(), wp_get_attachment_url(), wp_image_editor(), wp_image_editor_supports(), wp_maybe_generate_attachment_metadata(), and wp_video_shortcode().
get_attachment_fields_to_edit ($post, $errors = null)
Retrieves the attachment fields to edit form fields.
Since
2.5.0
Parameters
WP_Post $post
array $errors
Returns
array
Filter the attachment fields to edit.
Since
2.5.0
Parameters
array $form_fields An array of attachment form fields.
WP_Post $post The WP_Post attachment object.
Definition at line 1186 of file wp-admin/includes/media.php.
References $alt, $errors, $post, __, apply_filters(), esc_attr(), get_attachment_taxonomies(), get_object_term_cache(), get_option(), get_post(), get_post_meta(), get_taxonomy(), image_align_input_fields(), image_link_input_fields(), image_size_input_fields(), sanitize_post(), wp_caption_input_textarea(), wp_get_attachment_url(), and wp_get_object_terms().
Referenced by get_media_item().
get_compat_media_markup ($attachment_id, $args = null)
Since
3.5.0
Parameters
int $attachment_id
array $args
Returns
array
This filter is documented in wp-admin/includes/media.php
This filter is documented in wp-admin/includes/media.php
This filter is documented in wp-admin/includes/media.php
Definition at line 1602 of file wp-admin/includes/media.php.
References $class, $field, $id, $name, $post, $user_can_edit, $value, apply_filters(), current_user_can(), elseif, esc_attr(), get_attachment_taxonomies(), get_object_term_cache(), get_post(), get_taxonomy(), null, user_can_richedit(), wp_get_object_terms(), and wp_parse_args().
Referenced by edit_form_image_editor(), and wp_prepare_attachment_for_js().
get_image_send_to_editor ($id, $caption, $title, $align, $url = '', $rel = '', $size = 'medium', $alt = '')
Retrieves the image HTML to send to the editor.
Since
2.5.0
Parameters
int $id Image attachment id.
string $caption Image caption.
string $title Image title attribute.
string $align Image CSS alignment property.
string $url Optional. Image src URL. Default empty.
string $rel Optional. Image rel attribute. Default empty.
string | array $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'medium'.
string $alt Optional. Image alt attribute. Default empty.
Returns
string The HTML output to insert into the editor.
Filter the image HTML markup to send to the editor.
Since
2.5.0
Parameters
string $html The image HTML markup to send.
int $id The attachment id.
string $caption The image caption.
string $title The image title.
string $align The image alignment.
string $url The image source URL.
string | array $size Size of image. Image size or array of width and height values (in that order). Default 'medium'.
string $alt The image alternative, or alt, text.
Definition at line 120 of file wp-admin/includes/media.php.
References $alt, $caption, $id, $size, $title, $url, apply_filters(), esc_attr(), and get_image_tag().
Referenced by image_media_send_to_editor(), and wp_ajax_send_attachment_to_editor().
get_media_item ($attachment_id, $args = null)
Retrieve HTML form for modifying the image attachment.
Since
2.5.0
string $redir_tab
Parameters
int $attachment_id Attachment ID for modification.
string | array $args Optional. Override defaults.
Returns
string HTML form for attachment.
Filter the arguments used to retrieve an image for the edit image form.
Since
3.1.0
See also
get_media_item
Parameters
array $args An array of arguments.
Filter the media metadata.
Since
2.5.0
Parameters
string $media_dims The HTML markup containing the media dimensions.
WP_Post $post The WP_Post attachment object.
Definition at line 1347 of file wp-admin/includes/media.php.
References $class, $field, $file, $id, $keys, $name, $post, $title, $value, __, absint(), apply_filters(), current_theme_supports(), current_user_can(), elseif, esc_attr(), esc_attr__(), esc_html, get_attached_file(), get_attachment_fields_to_edit(), get_permalink(), get_post(), get_post_mime_types(), get_post_thumbnail_id(), get_post_type(), get_post_type_object(), get_submit_button(), mysql2date(), null, post_type_supports(), user_can_richedit(), wp_attachment_is_image(), wp_basename(), wp_get_attachment_image_src(), wp_get_attachment_metadata(), wp_html_excerpt(), wp_image_editor_supports(), wp_match_mime_types(), wp_nonce_url(), and wp_parse_args().
Referenced by get_media_items().
get_media_items ($post_id, $errors)
Retrieve HTML for media items of post gallery.
The HTML markup retrieved will be created for the progress of SWF Upload component. Will also create link for showing and hiding the form to modify the image attachment.
Since
2.5.0
WP_Query $wp_the_query
Parameters
int $post_id Optional. Post ID.
array $errors Errors for attachment, if any.
Returns
string
Definition at line 1311 of file wp-admin/includes/media.php.
References $attachments, $errors, $GLOBALS, $id, $output, $post, $post_id, get_children(), get_media_item(), get_post(), null, and posts.
Referenced by media_upload_library_form(), and media_upload_type_form().
get_upload_iframe_src ($type = null, $post_id = null, $tab = null)
int $post_ID
Parameters
string $type
int $post_id
string $tab
Returns
string
Filter the upload iframe source URL for a specific media type.
The dynamic portion of the hook name, $type, refers to the type of media uploaded.
Since
3.0.0
Parameters
string $upload_iframe_src The upload iframe source URL by type.
Definition at line 592 of file wp-admin/includes/media.php.
References $post_ID, $post_id, add_query_arg(), admin_url(), and apply_filters().
Referenced by _wp_post_thumbnail_html().
image_add_caption ($html, $id, $caption, $title, $align, $url, $size, $alt = '')
Adds image shortcode with caption to editor.
Since
2.6.0
Parameters
string $html
integer $id
string $caption image caption
string $title image title attribute
string $align image css alignment property
string $url image src url
string $size image size (thumbnail, medium, large, full or added with add_image_size())
string $alt image alt attribute
Returns
string
Filter the caption text.
Note: If the caption text is empty, the caption shortcode will not be appended to the image HTML when inserted into the editor.
Passing an empty value also prevents the {
See also
'image_add_caption_shortcode'} filter from being evaluated at the end of {
image_add_caption()}.
Since
4.1.0
Parameters
string $caption The original caption text.
int $id The attachment ID.
Filter whether to disable captions.
Prevents image captions from being appended to image HTML when inserted into the editor.
Since
2.6.0
Parameters
bool $bool Whether to disable appending captions. Returning true to the filter will disable captions. Default empty string.
Filter the image HTML markup including the caption shortcode.
Since
2.6.0
Parameters
string $shcode The image HTML markup with caption shortcode.
string $html The image HTML markup.
Definition at line 168 of file wp-admin/includes/media.php.
References $caption, $id, apply_filters(), and str_replace.
image_align_input_fields ($post, $checked = '')
Retrieve HTML for the image alignment radio buttons with the specified one checked.
Since
2.7.0
Parameters
WP_Post $post
string $checked
Returns
string
Definition at line 947 of file wp-admin/includes/media.php.
References $label, $name, $out, __, esc_attr(), and get_user_setting().
Referenced by get_attachment_fields_to_edit().
image_attachment_fields_to_edit ($form_fields, $post)
Retrieves the image attachment fields to edit form fields.
Since
2.5.0
Parameters
array $form_fields
object $post
Returns
array
Definition at line 1095 of file wp-admin/includes/media.php.
image_attachment_fields_to_save ($post, $attachment)
Filters input from media_upload_form_handler() and assigns a default post_title from the file name if none supplied.
Illustrates the use of the attachment_fields_to_save filter which can be used to add default values to any field before saving to DB.
Since
2.5.0
Parameters
array $post The WP_Post attachment object converted to an array.
array $attachment An array of attachment metadata.
Returns
array Filtered attachment post object.
Definition at line 1140 of file wp-admin/includes/media.php.
References $post, __, and wp_basename().
image_link_input_fields ($post, $url_type = '')
Retrieve HTML for the Link URL buttons with the default link type as specified.
Since
2.7.0
Parameters
WP_Post $post
string $url_type
Returns
string
Definition at line 1049 of file wp-admin/includes/media.php.
References $file, $link, $post, $url, __, elseif, esc_attr(), get_attachment_link(), get_user_setting(), and wp_get_attachment_url().
Referenced by get_attachment_fields_to_edit().
image_media_send_to_editor ($html, $attachment_id, $attachment)
Retrieves the media element HTML to send to the editor.
Since
2.5.0
Parameters
string $html
integer $attachment_id
array $attachment
Returns
string
Definition at line 1162 of file wp-admin/includes/media.php.
References $alt, $post, $size, $url, get_attachment_link(), get_image_send_to_editor(), and get_post().
image_size_input_fields ($post, $check = '')
Retrieve HTML for the size radio buttons with the specified one checked.
Since
2.7.0
Parameters
WP_Post $post
bool | string $check
Returns
array
Filter the names and labels of the default image sizes.
Since
3.3.0
Parameters
array $size_names Array of image sizes and their names. Default values include 'Thumbnail', 'Medium', 'Large', 'Full Size'.
Definition at line 975 of file wp-admin/includes/media.php.
References $label, $out, $post, $size, __, apply_filters(), disabled(), elseif, get_user_setting(), and image_downsize().
Referenced by get_attachment_fields_to_edit().
media_buttons ($editor_id = 'content')
Adds the media button to the editor.
Since
2.5.0
int $post_ID
int $instance
Parameters
string $editor_id
Filter the legacy (pre-3.5.0) media buttons.
Since
2.5.0
Parameters
string $string Media buttons context. Default empty.
Definition at line 546 of file wp-admin/includes/media.php.
References $GLOBALS, $post, __, apply_filters(), esc_attr(), get_post(), and wp_enqueue_media().
media_handle_sideload ($file_array, $post_id, $desc = null, $post_data = array())
This handles a sideloaded file in the same way as an uploaded file is handled by media_handle_upload().
Since
2.6.0
Parameters
array $file_array Array similar to a $_FILES upload array
int $post_id The post ID the media is associated with
string $desc Description of the sideloaded file
array $post_data allows you to overwrite some of the attachment
Returns
int|object The ID of the attachment or a WP_Error on failure
Definition at line 389 of file wp-admin/includes/media.php.
References $content, $file, $id, $image_meta, $post, $post_id, $title, $url, current_time(), get_post(), is_wp_error(), sanitize_title(), wp_generate_attachment_metadata(), wp_handle_sideload(), wp_insert_attachment(), wp_read_image_metadata(), and wp_update_attachment_metadata().
Referenced by media_sideload_image().
media_handle_upload ($file_id, $post_id, $post_data = array(), $overrides = array('test_form' => false))
Save a file submitted from a POST request and create an attachment post for it.
Since
2.5.0
Parameters
string $file_id Index of the $_FILES array that the file was sent. Required.
int $post_id The post ID of a post to attach the media item to. Required, but can be set to 0, creating a media item that has no relationship to a post.
array $post_data Overwrite some of the attachment. Optional.
array $overrides Override the wp_handle_upload() behavior. Optional.
Returns
int|WP_Error ID of the attachment or a WP_Error object on failure.
Definition at line 269 of file wp-admin/includes/media.php.
References $content, $excerpt, $file, $id, $image_meta, $name, $post, $post_id, $title, $url, __, current_time(), elseif, get_post(), is_wp_error(), number_format_i18n(), sanitize_title(), wp_generate_attachment_metadata(), wp_handle_upload(), wp_insert_attachment(), wp_read_audio_metadata(), wp_read_image_metadata(), and wp_update_attachment_metadata().
Referenced by GFFormsModel\create_post(), wp_ajax_upload_attachment(), and wp_media_upload_handler().
media_post_single_attachment_fields_to_edit ($form_fields, $post)
Retrieves the post non-image attachment fields to edito form fields.
Since
2.8.0
Parameters
array $form_fields An array of attachment form fields.
WP_Post $post The WP_Post attachment object.
Returns
array Filtered attachment form fields.
Definition at line 1122 of file wp-admin/includes/media.php.
media_send_to_editor ($html)
Adds image html to editor.
Since
2.5.0
Parameters
string $html
Definition at line 247 of file wp-admin/includes/media.php.
References exit, and wp_json_encode().
Referenced by media_upload_form_handler(), and wp_media_upload_handler().
media_sideload_image ($file, $post_id, $desc = null, $return = 'html')
Downloads an image from the specified URL and attaches it to a post.
Since
2.6.0
4.2.0 Introduced the $return parameter.
Parameters
string $file The URL of the image to download.
int $post_id The post ID the media is to be associated with.
string $desc Optional. Description of the image.
string $return Optional. Accepts 'html' (image tag html) or 'src' (URL). Default 'html'.
Returns
string|WP_Error Populated HTML img tag on success, WP_Error object otherwise.
Definition at line 848 of file wp-admin/includes/media.php.
References $alt, $file, $id, $post_id, __, download_url(), esc_attr(), is_wp_error(), media_handle_sideload(), and wp_get_attachment_url().
Referenced by WP_Press_This\side_load_images().
media_single_attachment_fields_to_edit ($form_fields, $post)
Retrieves the single non-image attachment fields to edit form fields.
Since
2.5.0
Parameters
array $form_fields An array of attachment form fields.
WP_Post $post The WP_Post attachment object.
Returns
array Filtered attachment form fields.
Definition at line 1108 of file wp-admin/includes/media.php.
media_upload_flash_bypass ()
Displays the multi-file uploader message.
Since
2.6.0
int $post_ID
Definition at line 2619 of file wp-admin/includes/media.php.
References $GLOBALS, $post, __, admin_url(), elseif, and get_post().
media_upload_form ($errors = null)
Outputs the legacy media upload form.
Since
2.5.0
string $type string $tab bool $is_IE bool $is_opera
Parameters
array $errors
Fires when an upload will exceed the defined upload space quota for a network site.
Since
3.5.0
Fires just before the legacy (pre-3.5.0) upload interface is loaded.
Since
2.6.0
Filter the media upload post parameters.
Since
3.1.0 As 'swfupload_post_params'
3.3.0
Parameters
array $post_params An array of media upload parameters used by Plupload.
Filter the default Plupload settings.
Since
3.3.0
Parameters
array $plupload_init An array of default settings used by Plupload.
Fires before the upload interface loads.
Since
2.6.0 As 'pre-flash-upload-ui'
3.3.0
Fires after the upload interface loads.
Since
2.6.0 As 'post-flash-upload-ui'
3.3.0
Fires before the upload button in the media upload interface.
Since
2.6.0
Fires after the upload button in the media upload interface.
Since
2.6.0
Fires on the post upload UI screen.
Legacy (pre-3.5.0) media workflow hook.
Since
2.6.0
Definition at line 1779 of file wp-admin/includes/media.php.
References $_SERVER, $errors, $is_IE, $is_opera, $post_id, __, _device_can_upload(), _e, _ex(), absint(), admin_url(), apply_filters(), do_action(), esc_html, get_option(), includes_url(), input, is_multisite(), is_upload_space_available(), is_wp_error(), label, name, size_format(), submit_button(), wp_is_mobile(), wp_json_encode(), and wp_max_upload_size().
Referenced by media_upload_type_form().
media_upload_form_handler ()
Handles form submissions for the legacy media uploader.
Since
2.5.0
Returns
mixed void|object WP_Error on failure
Filter the attachment fields to be saved.
Since
2.5.0
See also
wp_get_attachment_metadata()
Parameters
array $post An array of post data.
array $attachment An array of attachment metadata.
Filter the HTML markup for a media item sent to the editor.
Since
2.5.0
See also
wp_get_attachment_metadata()
Parameters
string $html HTML markup for a media item sent to the editor.
int $send_id The first key from the $_POST['send'] data.
array $attachment Array of attachment metadata.
Definition at line 628 of file wp-admin/includes/media.php.
References $errors, $keys, $post, apply_filters(), ARRAY_A, current_user_can(), esc_attr(), exit, get_attachment_link(), get_attachment_taxonomies(), get_post(), get_post_meta(), media_send_to_editor(), null, update_post_meta(), wp_set_object_terms(), wp_slash(), wp_strip_all_tags(), wp_unslash(), and wp_update_post().
Referenced by media_upload_gallery(), media_upload_library(), and wp_media_upload_handler().
media_upload_gallery ()
Retrieves the legacy media uploader form in an iframe.
Since
2.5.0
Returns
string|null
Definition at line 901 of file wp-admin/includes/media.php.
References $errors, media_upload_form_handler(), wp_enqueue_script(), and wp_iframe().
media_upload_gallery_form ($errors)
Adds gallery form to upload iframe.
Since
2.5.0
string $redir_tab string $type string $tab
Parameters
array $errors
This filter is documented in wp-admin/includes/media.php
Definition at line 2182 of file wp-admin/includes/media.php.
media_upload_header ()
Outputs the legacy media upload header.
Since
2.5.0
Definition at line 1756 of file wp-admin/includes/media.php.
References $post_id, and the_media_upload_tabs().
Referenced by media_upload_library_form(), media_upload_type_form(), and media_upload_type_url_form().
media_upload_html_bypass ()
Displays the browser's built-in uploader message.
Since
2.6.0
Definition at line 2639 of file wp-admin/includes/media.php.
References _e.
media_upload_library ()
Retrieves the legacy media library form in an iframe.
Since
2.5.0
Returns
string|null
Definition at line 924 of file wp-admin/includes/media.php.
References $errors, media_upload_form_handler(), and wp_iframe().
media_upload_library_form ($errors)
Outputs the legacy media upload form for the media library.
Since
2.5.0
wpdb $wpdb WP_Query $wp_query WP_Locale $wp_locale string $type string $tab array $post_mime_types
Parameters
array $errors
This filter is documented in wp-admin/includes/media.php
Filter the media upload mime type list items.
Returned values should begin with an <li> tag.
Since
3.1.0
Parameters
array $type_links An array of list items containing mime type link HTML.
Definition at line 2334 of file wp-admin/includes/media.php.
References $class, $default, $label, $wp_locale, $wpdb, __, _e, add_filter(), add_query_arg(), admin_url(), apply_filters(), esc_attr(), esc_html, esc_url, get_media_items(), get_user_setting(), input, label, media_upload_header(), name, null, number_format_i18n(), paginate_links(), submit_button(), translate_nooped_plural(), wp_count_attachments(), wp_edit_attachments_query(), wp_match_mime_types(), wp_nonce_field(), and zeroise().
media_upload_max_image_resize ()
Displays the checkbox to scale images.
Since
3.3.0
Definition at line 2659 of file wp-admin/includes/media.php.
References __, admin_url(), current_user_can(), esc_url, get_option(), get_user_setting(), input, label, and name.
media_upload_tabs ()
Defines the default media upload tabs.
Since
2.5.0
Returns
array default tabs
Filter the available tabs in the legacy (pre-3.5.0) media popup.
Since
2.5.0
Parameters
array $_default_tabs An array of media tabs.
Definition at line 16 of file wp-admin/includes/media.php.
References __, and apply_filters().
Referenced by the_media_upload_tabs().
media_upload_text_after ()
Used to display a "After a file has been uploaded..." help message.
Since
3.3.0
Definition at line 2652 of file wp-admin/includes/media.php.
media_upload_type_form ($type = 'file', $errors = null, $id = null)
Outputs the legacy media upload form for a given media type.
Since
2.5.0
Parameters
string $type
object $errors
integer $id
Filter the media upload form action URL.
Since
2.6.0
Parameters
string $form_action_url The media upload form action URL.
string $type The type of media. Default 'file'.
Definition at line 1968 of file wp-admin/includes/media.php.
References $errors, $form_class, $id, $post_id, __, _e, add_filter(), admin_url(), apply_filters(), exit, get_media_items(), get_user_setting(), input, is_wp_error(), media_upload_form(), media_upload_header(), name, submit_button(), and wp_nonce_field().
media_upload_type_url_form ($type = null, $errors = null, $id = null)
Outputs the legacy media upload form for external media.
Since
2.7.0
Parameters
string $type
object $errors
integer $id
This filter is documented in wp-admin/includes/media.php
This filter is documented in wp-admin/includes/media.php
Filter the insert media from URL form HTML.
Since
3.3.0
Parameters
string $form_html The insert from URL form HTML.
Definition at line 2038 of file wp-admin/includes/media.php.
References $form_class, $post_id, _e, admin_url(), align, apply_filters(), esc_url, get_user_setting(), height, input, media_upload_header(), n, name, null, width, and wp_nonce_field().
multisite_over_quota_message ()
Displays the out of storage quota message in Multisite.
Since
3.5.0
Definition at line 2683 of file wp-admin/includes/media.php.
References __, and get_space_allowed().
the_media_upload_tabs ()
Outputs the legacy media upload tabs UI.
Since
2.5.0
string $redir_tab
This filter is documented in wp-admin/media-upload.php
Definition at line 74 of file wp-admin/includes/media.php.
References $class, $default, $href, $link, $tabs, $text, add_query_arg(), apply_filters(), elseif, esc_attr(), esc_url, and media_upload_tabs().
Referenced by media_upload_header().
update_gallery_tab ($tabs)
Adds the gallery tab back to the tabs array if post has image attachments.
Since
2.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $tabs
Returns
array $tabs with gallery if post has image attachment
Definition at line 44 of file wp-admin/includes/media.php.
References $attachments, $post_id, $tabs, $wpdb, and __.
wp_add_id3_tag_data (& $metadata, $data)
Parse ID3v2, ID3v1, and getID3 comments to extract usable data.
Since
3.6.0
Parameters
array $metadata An existing array with data
array $data Data supplied by ID3 tags
Definition at line 2938 of file wp-admin/includes/media.php.
References $image, $list, $metadata, and elseif.
Referenced by wp_read_audio_metadata(), and wp_read_video_metadata().
wp_caption_input_textarea ($edit_post)
Output a textarea element for inputting an attachment caption.
Since
3.4.0
Parameters
WP_Post $edit_post Attachment WP_Post object.
Returns
string HTML markup for the textarea element.
Definition at line 1079 of file wp-admin/includes/media.php.
References $name.
Referenced by get_attachment_fields_to_edit().
wp_iframe ($content_func)
Adds the iframe to display content for the media upload page.
Since
2.5.0
int $body_id
Parameters
string | callable $content_func
This action is documented in wp-admin/admin-header.php
Fires when admin styles enqueued for the legacy (pre-3.5.0) media upload popup are printed.
Since
2.9.0
This action is documented in wp-admin/admin-header.php
Fires when admin scripts enqueued for the legacy (pre-3.5.0) media upload popup are printed.
Since
2.9.0
This action is documented in wp-admin/admin-header.php
Fires when scripts enqueued for the admin header for the legacy (pre-3.5.0) media upload popup are printed.
Since
2.9.0
This action is documented in wp-admin/admin-header.php
Fires in the admin header for each specific form tab in the legacy (pre-3.5.0) media upload popup.
The dynamic portion of the hook, $content_func, refers to the form callback for the media upload type. Possible values include 'media_upload_type_form', 'media_upload_type_url_form', and 'media_upload_library_form'.
Since
2.5.0
This action is documented in wp-admin/admin-footer.php
Definition at line 448 of file wp-admin/includes/media.php.
References $GLOBALS, _e, _wp_admin_html_begin(), bloginfo(), do_action(), is_rtl(), and wp_enqueue_style().
Referenced by media_upload_gallery(), media_upload_library(), and wp_media_upload_handler().
wp_media_attach_action ($parent_id, $action = 'attach')
Encapsulate logic for Attach/Detach actions.
Since
4.2.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $parent_id Attachment parent ID.
string $action Optional. Attach/detach action. Accepts 'attach' or 'detach'. Default 'attach'.
Definition at line 3092 of file wp-admin/includes/media.php.
References $action, $location, $referer, $wpdb, __, add_query_arg(), clean_attachment_cache(), current_user_can(), exit, remove_query_arg(), wp_die(), and wp_get_referer().
wp_media_insert_url_form ($default_view = 'image')
Creates the form for external url.
Since
2.7.0
Parameters
string $default_view
Returns
string the form html
This filter is documented in wp-admin/includes/media.php
Definition at line 2516 of file wp-admin/includes/media.php.
References $caption, __, apply_filters(), checked(), esc_attr__(), get_option(), and get_submit_button().
Referenced by type_url_form_audio(), type_url_form_file(), type_url_form_image(), and type_url_form_video().
wp_media_upload_handler ()
Handles the process of uploading media.
Since
2.5.0
Returns
null|string
Filter the URL sent to the editor for a specific media type.
The dynamic portion of the hook name, $type, refers to the type of media being sent.
Since
3.3.0
Parameters
string $html HTML markup sent to the editor.
string $src Media source URL.
string $title Media title.
Filter the image URL sent to the editor.
Since
2.8.0
Parameters
string $html HTML markup sent to the editor for an image.
string $src Image source URL.
string $alt Image alternate, or alt, text.
string $align The image alignment. Default 'alignnone'. Possible values include 'alignleft', 'aligncenter', 'alignright', 'alignnone'.
Definition at line 739 of file wp-admin/includes/media.php.
References $alt, $class, $errors, $id, $title, __, apply_filters(), elseif, esc_attr(), esc_html, esc_url, esc_url_raw(), is_wp_error(), media_handle_upload(), media_send_to_editor(), media_upload_form_handler(), wp_enqueue_script(), wp_ext2type(), wp_iframe(), and wp_unslash().
Referenced by media_upload_audio(), media_upload_file(), media_upload_image(), and media_upload_video().
wp_read_audio_metadata ($file)
Retrieve metadata from a audio file's ID3 tags.
Since
3.6.0
Parameters
string $file Path to file.
Returns
array|bool Returns array of metadata, if found.
Definition at line 3044 of file wp-admin/includes/media.php.
References $file, $metadata, ABSPATH, get_temp_dir(), wp_add_id3_tag_data(), and WPINC.
Referenced by media_handle_upload(), and wp_generate_attachment_metadata().
wp_read_video_metadata ($file)
Retrieve metadata from a video file's ID3 tags.
Since
3.6.0
Parameters
string $file Path to file.
Returns
array|bool Returns array of metadata, if found.
Definition at line 2982 of file wp-admin/includes/media.php.
References $file, $metadata, ABSPATH, get_temp_dir(), wp_add_id3_tag_data(), and WPINC.
Referenced by wp_generate_attachment_metadata().