GravityView: bookmark.php File Reference
wp-admin/includes/bookmark.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
add_link ()
Add a link to using values provided in $_POST.
edit_link ($link_id=0)
Updates or inserts a link using values provided in $_POST.
get_default_link_to_edit ()
Retrieves the default link for editing.
get_link_to_edit ($link_id)
Retrieves link data based on its ID.
wp_delete_link ($link_id)
Deletes a specified link from the database.
wp_get_link_cats ($link_id=0)
Retrieves the link categories associated with the link specified.
wp_insert_link ($linkdata, $wp_error=false)
Inserts/updates links into/in the database.
wp_link_manager_disabled_message ()
Outputs the 'disabled' message for the WordPress Link Manager.
wp_set_link_cats ($link_id=0, $link_categories=array())
Update link with the specified link categories.
wp_update_link ($linkdata)
Updates a link in the database.
Function Documentation
add_link ()
Add a link to using values provided in $_POST.
Since
2.0.0
Returns
int|WP_Error Value 0 or WP_Error on failure. The link ID on success.
Definition at line 16 of file wp-admin/includes/bookmark.php.
References edit_link().
edit_link ($link_id = 0)
Updates or inserts a link using values provided in $_POST.
Since
2.0.0
Parameters
int $link_id Optional. ID of the link to edit. Default 0.
Returns
int|WP_Error Value 0 or WP_Error on failure. The link ID on success.
Definition at line 28 of file wp-admin/includes/bookmark.php.
References __, current_user_can(), esc_html, esc_url, wp_die(), wp_insert_link(), and wp_update_link().
Referenced by add_link().
get_default_link_to_edit ()
Retrieves the default link for editing.
Since
2.0.0
Returns
stdClass Default link object.
Definition at line 60 of file wp-admin/includes/bookmark.php.
References $link, esc_attr(), esc_url, and wp_unslash().
get_link_to_edit ($link_id)
Retrieves link data based on its ID.
Since
2.0.0
Parameters
int $link_id ID of link to retrieve.
Returns
object Link object for editing.
Definition at line 137 of file wp-admin/includes/bookmark.php.
References get_bookmark(), and OBJECT.
wp_delete_link ($link_id)
Deletes a specified link from the database.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $link_id ID of the link to delete
Returns
true Always true.
Fires before a link is deleted.
Since
2.0.0
Parameters
int $link_id ID of the link to delete.
Fires after a link has been deleted.
Since
2.2.0
Parameters
int $link_id ID of the deleted link.
Definition at line 87 of file wp-admin/includes/bookmark.php.
References $wpdb, clean_bookmark_cache(), do_action(), and wp_delete_object_term_relationships().
Referenced by wp_ajax_delete_link(), wp_delete_user(), and wpmu_delete_user().
wp_get_link_cats ($link_id = 0)
Retrieves the link categories associated with the link specified.
Since
2.1.0
Parameters
int $link_id Link ID to look up
Returns
array The requested link's categories
Definition at line 124 of file wp-admin/includes/bookmark.php.
References $cats, and wp_get_object_terms().
Referenced by WP_Links_List_Table\display_rows(), get_linkcatname(), and wp_link_category_checklist().
wp_insert_link ($linkdata, $wp_error = false)
Inserts/updates links into/in the database.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $linkdata Elements that make up the link to insert.
bool $wp_error Optional. Whether to return a WP_Error object on failure. Default false.
Returns
int|WP_Error Value 0 or WP_Error on failure. The link ID on success.
Fires after a link was updated in the database.
Since
2.0.0
Parameters
int $link_id ID of the link that was updated.
Fires after a link was added to the database.
Since
2.0.0
Parameters
int $link_id ID of the link that was added.
Definition at line 152 of file wp-admin/includes/bookmark.php.
References $update, $wpdb, __, clean_bookmark_cache(), do_action(), get_current_user_id(), get_option(), sanitize_bookmark(), wp_parse_args(), wp_set_link_cats(), and wp_unslash().
Referenced by edit_link(), and wp_update_link().
wp_link_manager_disabled_message ()
Outputs the 'disabled' message for the WordPress Link Manager.
Since
3.5.0 private
string $pagenow
Definition at line 301 of file wp-admin/includes/bookmark.php.
References $link, $pagenow, __, add_filter(), current_user_can(), network_admin_url(), remove_filter(), and wp_die().
wp_set_link_cats ($link_id = 0, $link_categories = array())
Update link with the specified link categories.
Since
2.1.0
Parameters
int $link_id ID of the link to update.
array $link_categories Array of link categories to add the link to.
Definition at line 250 of file wp-admin/includes/bookmark.php.
References clean_bookmark_cache(), get_option(), and wp_set_object_terms().
Referenced by wp_insert_link().
wp_update_link ($linkdata)
Updates a link in the database.
Since
2.0.0
Parameters
array $linkdata Link data to update.
Returns
int|WP_Error Value 0 or WP_Error on failure. The updated link ID on success.
Definition at line 271 of file wp-admin/includes/bookmark.php.
References $link, ARRAY_A, get_bookmark(), wp_insert_link(), and wp_slash().
Referenced by edit_link().