GravityView: revision.php File Reference
wp-admin/revision.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$from = is_numeric($from) ? absint($from) : null
else $parent_file = $submenu_file = 'edit.php'
$redirect = 'edit.php'
$revision_id = absint($revision)
$revisions_overview = '<p>' . __('This screen is used for managing your content revisions.') . '</p>'
$revisions_sidebar = '<p><strong>' . __('For more information:') . '</strong></p>'
Variable Documentation
$from = is_numeric($from) ? absint($from) : null
Definition at line 27 of file wp-admin/revision.php.
Referenced by _copy_dir(), copy_dir(), PHPMailer\DKIM_Add(), PHPMailer\doCallback(), human_time_diff(), SMTP\mail(), ftp_base\rename(), ftp_base\restore(), update_core(), and wp_prepare_revisions_for_js().
else $parent_file = $submenu_file = 'edit.php'
Definition at line 98 of file wp-admin/revision.php.
$redirect = 'edit.php'
Definition at line 30 of file wp-admin/revision.php.
Referenced by activate_plugin(), activate_plugins(), delete_theme(), redirect_canonical(), WP_Press_This\save_post(), wp_login_url(), wp_loginout(), wp_logout_url(), and wp_lostpassword_url().
$revision_id = absint($revision)
Definition at line 25 of file wp-admin/revision.php.
Referenced by _wp_put_post_revision(), wp_delete_post(), wp_delete_post_revision(), wp_prepare_revisions_for_js(), wp_restore_post_revision(), and wp_xmlrpc_server\wp_restoreRevision().
$revisions_overview = '<p>' . __('This screen is used for managing your content revisions.') . '</p>'
Definition at line 105 of file wp-admin/revision.php.
$revisions_sidebar = '<p><strong>' . __('For more information:') . '</strong></p>'
Definition at line 118 of file wp-admin/revision.php.