GravityView: revision.php File Reference
wp-admin/includes/revision.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
wp_get_revision_ui_diff ($post, $compare_from, $compare_to)
Get the revision UI diff.
wp_prepare_revisions_for_js ($post, $selected_revision_id, $from=null)
Prepare revisions for JavaScript.
wp_print_revision_templates ()
Print JavaScript templates required for the revisions experience.
Function Documentation
wp_get_revision_ui_diff ($post, $compare_from, $compare_to)
Get the revision UI diff.
Since
3.6.0
Parameters
object | int $post The post object. Also accepts a post ID.
int $compare_from The revision ID to compare from.
int $compare_to The revision ID to come to.
Returns
array|bool Associative array of a post's revisioned fields and their diffs. Or, false on failure.
Contextually filter a post revision field.
The dynamic portion of the hook name, $field, corresponds to each of the post fields of the revision object being iterated over in a foreach statement.
Since
3.6.0
Parameters
string $compare_from-,>$field The current revision field to compare to or from.
string $field The current revision field.
WP_Post $compare_from The revision post object to compare to or from.
string null The context of whether the current revision is the old or the new one. Values are 'to' or 'from'.
This filter is documented in wp-admin/includes/revision.php
Filter revisions text diff options.
Filter the options passed to {
See also
wp_text_diff()} when viewing a post revision.
Since
4.1.0
Parameters
array $args { Associative array of options to pass to {
See also
wp_text_diff()}.
bool $show_split_view True for split view (two columns), false for un-split view (single column). Default true. }
Parameters
string $field The current revision field.
WP_Post $compare_from The revision post to compare from.
WP_Post $compare_to The revision post to compare to.
Filter the fields displayed in the post revision diff UI.
Since
4.1.0
Parameters
array $return Revision UI fields. Each item is an array of id, name and diff.
WP_Post $compare_from The revision post to compare from.
WP_Post $compare_to The revision post to compare to.
Definition at line 22 of file wp-admin/includes/revision.php.
References $field, $name, $post, __, _wp_post_revision_fields(), apply_filters(), esc_html, and get_post().
Referenced by wp_ajax_get_revision_diffs(), and wp_prepare_revisions_for_js().
wp_prepare_revisions_for_js ($post, $selected_revision_id, $from = null)
Prepare revisions for JavaScript.
Since
3.6.0
Parameters
object | int $post The post object. Also accepts a post ID.
int $selected_revision_id The selected revision ID.
int $from Optional. The revision ID to compare from.
Returns
array An associative array of revision data and related settings.
Filter the array of revisions used on the revisions screen.
Since
4.4.0
Parameters
array $revisions_data { The bootstrapped data for the revisions screen.
int $id Revision ID. string $title Title for the revision's parent WP_Post object. int $author Revision post author ID. string $date Date the revision was modified. string $dateShort Short-form version of the date the revision was modified. string $timeAgo GMT-aware amount of time ago the revision was modified. bool $autosave Whether the revision is an autosave. bool $current Whether the revision is both not an autosave and the post modified date matches the revision modified date (GMT-aware). bool|false $restoreUrl URL if the revision can be restored, false otherwise. }
Parameters
WP_Post $revision The revision's WP_Post object.
WP_Post $post The revision's parent WP_Post object.
If we only have one revision, the initial revision is missing; This happens when we have an autsosave and the user has clicked 'View the Autosave'
Definition at line 145 of file wp-admin/includes/revision.php.
References $authors, $from, $post, $revision_id, $show_avatars, __, _x, absint(), add_query_arg(), admin_url(), apply_filters(), current_user_can(), date_i18n(), elseif, get_option(), get_post(), get_the_author_meta(), get_the_title(), human_time_diff(), str_replace, wp_get_post_revisions(), wp_get_revision_ui_diff(), wp_is_post_autosave(), wp_list_pluck(), wp_nonce_url(), and wp_revisions_enabled().
wp_print_revision_templates ()
Print JavaScript templates required for the revisions experience.
Since
4.1.0
WP_Post $post The global $post object.
Definition at line 316 of file wp-admin/includes/revision.php.
References $post, __, _e, _ex(), disabled(), esc_attr_e(), input, label, and wp_check_post_lock().