GravityView: misc.php File Reference
wp-admin/includes/misc.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_ipad_meta ()
admin_color_scheme_picker ($user_id)
Display the default admin color scheme picker (Used in user-edit.php)
extract_from_markers ($filename, $marker)
Extracts strings from between the BEGIN and END markers in the .htaccess file.
got_mod_rewrite ()
Returns whether the server is running Apache with the mod_rewrite module loaded.
got_url_rewrite ()
Returns whether the server supports URL rewriting.
heartbeat_autosave ($response, $data)
Autosave with heartbeat.
iis7_add_rewrite_rule ($filename, $rewrite_rule)
Add WordPress rewrite rule to the IIS 7+ configuration file.
iis7_delete_rewrite_rule ($filename)
Delete WordPress rewrite rule from web.config file if it exists there.
iis7_rewrite_rule_exists ($filename)
Check if rewrite rule for WordPress already exists in the IIS 7+ configuration file.
iis7_save_url_rewrite_rules ()
Updates the IIS web.config file with the current rules if it is writable.
insert_with_markers ($filename, $marker, $insertion)
Inserts an array of strings into a file (.htaccess), placing it between BEGIN and END markers.
post_form_autocomplete_off ()
Disables autocomplete on the 'post' form (Add/Edit Post screens) for WebKit browsers, as they disregard the autocomplete setting on the editor textarea.
save_mod_rewrite_rules ()
Updates the htaccess file with the current rules if it is writable.
saveDomDocument ($doc, $filename)
Saves the XML document into a file.
set_screen_options ()
Saves option for number of rows when listing posts, pages, comments, etc.
show_message ($message)
Displays the given administration message.
update_home_siteurl ($old_value, $value)
Flushes rewrite rules if siteurl, home or page_on_front changed.
update_recently_edited ($file)
Update the "recently-edited" file for the plugin or theme editor.
wp_admin_canonical_url ()
Remove single-use URL parameters and create canonical link based on new URL.
wp_check_locked_posts ($response, $data, $screen_id)
Check lock status for posts displayed on the Posts screen.
wp_color_scheme_settings ()
array $_wp_admin_css_colors
wp_doc_link_parse ($content)
wp_heartbeat_set_suspension ($settings)
Disable suspension of Heartbeat on the Add/Edit Post screens.
wp_refresh_post_lock ($response, $data, $screen_id)
Check lock status on the New/Edit Post screen and refresh the lock.
wp_refresh_post_nonces ($response, $data, $screen_id)
Check nonce expiration on the New/Edit Post screen and refresh if needed.
wp_reset_vars ($vars)
Resets global variables based on $_GET and $_POST.
Function Documentation
_ipad_meta ()
Since
3.3.0
Definition at line 722 of file wp-admin/includes/misc.php.
References name, and wp_is_mobile().
admin_color_scheme_picker ($user_id)
Display the default admin color scheme picker (Used in user-edit.php)
Since
3.0.0
array $_wp_admin_css_colors
Parameters
int $user_id User ID.
Definition at line 641 of file wp-admin/includes/misc.php.
References $user_id, _e, checked(), endforeach, esc_html, get_user_option(), input, label, name, and wp_nonce_field().
extract_from_markers ($filename, $marker)
Extracts strings from between the BEGIN and END markers in the .htaccess file.
Since
1.5.0
Parameters
string $filename
string $marker
Returns
array An array of strings from a file (.htaccess) from between BEGIN and END markers.
Definition at line 67 of file wp-admin/includes/misc.php.
got_mod_rewrite ()
Returns whether the server is running Apache with the mod_rewrite module loaded.
Since
2.0.0
Returns
bool
Filter whether Apache and mod_rewrite are present.
This filter was previously used to force URL rewriting for other servers, like nginx. Use the got_url_rewrite filter in got_url_rewrite() instead.
Since
2.5.0
See also
got_url_rewrite()
Parameters
bool $got_rewrite Whether Apache and mod_rewrite are present.
Definition at line 16 of file wp-admin/includes/misc.php.
References apache_mod_loaded(), and apply_filters().
Referenced by got_url_rewrite(), network_step1(), and save_mod_rewrite_rules().
got_url_rewrite ()
Returns whether the server supports URL rewriting.
Detects Apache's mod_rewrite, IIS 7.0+ permalink support, and nginx.
Since
3.7.0
bool $is_nginx
Returns
bool Whether the server supports URL rewriting.
Filter whether URL rewriting is available.
Since
3.7.0
Parameters
bool $got_url_rewrite Whether URL rewriting is available.
Definition at line 45 of file wp-admin/includes/misc.php.
References $GLOBALS, apply_filters(), got_mod_rewrite(), and iis7_supports_permalinks().
heartbeat_autosave ($response, $data)
Autosave with heartbeat.
Since
3.9.0
Parameters
array $response The Heartbeat response.
array $data The $_POST data sent.
Returns
array The Heartbeat response.
Definition at line 875 of file wp-admin/includes/misc.php.
References __, date_i18n(), elseif, is_wp_error(), and wp_autosave().
iis7_add_rewrite_rule ($filename, $rewrite_rule)
Add WordPress rewrite rule to the IIS 7+ configuration file.
Since
2.8.0
Parameters
string $filename The file path to the configuration file
string $rewrite_rule The XML fragment with URL Rewrite rule
Returns
bool
Definition at line 544 of file wp-admin/includes/misc.php.
References false, and saveDomDocument().
Referenced by iis7_save_url_rewrite_rules().
iis7_delete_rewrite_rule ($filename)
Delete WordPress rewrite rule from web.config file if it exists there.
Since
2.8.0
Parameters
string $filename Name of the configuration file
Returns
bool
Definition at line 509 of file wp-admin/includes/misc.php.
References saveDomDocument().
Referenced by iis7_save_url_rewrite_rules().
iis7_rewrite_rule_exists ($filename)
Check if rewrite rule for WordPress already exists in the IIS 7+ configuration file.
Since
2.8.0
Returns
bool
Parameters
string $filename The file path to the configuration file
Definition at line 483 of file wp-admin/includes/misc.php.
References false.
iis7_save_url_rewrite_rules ()
Updates the IIS web.config file with the current rules if it is writable.
If the permalinks do not require rewrite rules then the rules are deleted from the web.config file.
Since
2.8.0
WP_Rewrite $wp_rewrite
Returns
bool True if web.config was updated successfully
Definition at line 229 of file wp-admin/includes/misc.php.
References $home_path, $wp_rewrite, get_home_path(), iis7_add_rewrite_rule(), iis7_delete_rewrite_rule(), iis7_supports_permalinks(), is_multisite(), and win_is_writable().
Referenced by WP_Rewrite\flush_rules().
insert_with_markers ($filename, $marker, $insertion)
Inserts an array of strings into a file (.htaccess), placing it between BEGIN and END markers.
Replaces existing marked info. Retains surrounding data. Creates file if none exists.
Since
1.5.0
Parameters
string $filename Filename to alter.
string $marker The marker to alter.
array | string $insertion The new content to insert.
Returns
bool True on write success, false on failure.
Definition at line 104 of file wp-admin/includes/misc.php.
References elseif.
Referenced by save_mod_rewrite_rules().
post_form_autocomplete_off ()
Disables autocomplete on the 'post' form (Add/Edit Post screens) for WebKit browsers, as they disregard the autocomplete setting on the editor textarea.
That can break the editor when the user navigates to it with the browser's Back button. See #28037
Since
4.0.0
bool $is_safari bool $is_chrome
Definition at line 904 of file wp-admin/includes/misc.php.
References $is_chrome, and $is_safari.
save_mod_rewrite_rules ()
Updates the htaccess file with the current rules if it is writable.
Always writes to the file if it exists and is writable to ensure that we blank out old rules.
Since
1.5.0
WP_Rewrite $wp_rewrite
Definition at line 196 of file wp-admin/includes/misc.php.
References $home_path, $wp_rewrite, get_home_path(), got_mod_rewrite(), insert_with_markers(), and is_multisite().
Referenced by WP_Rewrite\flush_rules().
saveDomDocument ($doc, $filename)
Saves the XML document into a file.
Since
2.8.0
Parameters
DOMDocument $doc
string $filename
Definition at line 624 of file wp-admin/includes/misc.php.
Referenced by iis7_add_rewrite_rule(), and iis7_delete_rewrite_rule().
set_screen_options ()
Saves option for number of rows when listing posts, pages, comments, etc.
Since
2.8.0
Filter a screen option value before it is set.
The filter can also be used to modify non-standard [items]_per_page settings. See the parent function for a full list of standard options.
Returning false to the filter will skip saving the current option.
Since
2.8.0
See also
set_screen_options()
Parameters
bool | int $value Screen option value. Default false to skip.
string $option The option name.
int $value The number of rows to use.
Definition at line 397 of file wp-admin/includes/misc.php.
References $option, $url, $user, $value, add_query_arg(), apply_filters(), elseif, exit, get_post_types(), get_taxonomies(), remove_query_arg(), sanitize_key(), str_replace, update_user_meta(), and wp_get_referer().
show_message ($message)
Displays the given administration message.
Since
2.1.0
Parameters
string | WP_Error $message
Definition at line 324 of file wp-admin/includes/misc.php.
References $message, is_wp_error(), and wp_ob_end_flush_all().
Referenced by _redirect_to_about_wordpress(), do_core_upgrade(), and WP_Upgrader_Skin\feedback().
update_home_siteurl ($old_value, $value)
Flushes rewrite rules if siteurl, home or page_on_front changed.
Since
2.1.0
Parameters
string $old_value
string $value
Definition at line 280 of file wp-admin/includes/misc.php.
References delete_option(), flush_rewrite_rules(), is_multisite(), ms_is_switched(), and wp_installing().
update_recently_edited ($file)
Update the "recently-edited" file for the plugin or theme editor.
Since
1.5.0
Parameters
string $file
Definition at line 257 of file wp-admin/includes/misc.php.
References $file, get_option(), and update_option().
wp_admin_canonical_url ()
Remove single-use URL parameters and create canonical link based on new URL.
Remove specific query string parameters from a URL, create the canonical link, put it in the admin header, and change the current URL to match.
Since
4.2.0
Definition at line 920 of file wp-admin/includes/misc.php.
References $_SERVER, null, remove_query_arg(), set_url_scheme(), and wp_removable_query_args().
wp_check_locked_posts ($response, $data, $screen_id)
Check lock status for posts displayed on the Posts screen.
Since
3.6.0
Parameters
array $response The Heartbeat response.
array $data The $_POST data sent.
string $screen_id The screen id.
Returns
array The Heartbeat response.
Definition at line 740 of file wp-admin/includes/misc.php.
References $post_id, $user, $user_id, __, absint(), current_user_can(), and wp_check_post_lock().
wp_color_scheme_settings ()
array $_wp_admin_css_colors
Definition at line 697 of file wp-admin/includes/misc.php.
References elseif, get_user_option(), and wp_json_encode().
wp_doc_link_parse ($content)
Since
2.8.0
Parameters
string $content
Returns
array
Filter the list of functions and classes to be ignored from the documentation lookup.
Since
2.8.0
Parameters
array $ignore_functions Functions and classes to be ignored.
Definition at line 342 of file wp-admin/includes/misc.php.
References $content, $count, $out, and apply_filters().
wp_heartbeat_set_suspension ($settings)
Disable suspension of Heartbeat on the Add/Edit Post screens.
Since
3.8.0
string $pagenow
Parameters
array $settings An array of Heartbeat settings.
Returns
array Filtered Heartbeat settings.
Definition at line 856 of file wp-admin/includes/misc.php.
References $pagenow.
wp_refresh_post_lock ($response, $data, $screen_id)
Check lock status on the New/Edit Post screen and refresh the lock.
Since
3.6.0
Parameters
array $response The Heartbeat response.
array $data The $_POST data sent.
string $screen_id The screen id.
Returns
array The Heartbeat response.
Definition at line 775 of file wp-admin/includes/misc.php.
References $post_id, $user, $user_id, __, absint(), current_user_can(), wp_check_post_lock(), and wp_set_post_lock().
wp_refresh_post_nonces ($response, $data, $screen_id)
Check nonce expiration on the New/Edit Post screen and refresh if needed.
Since
3.6.0
Parameters
array $response The Heartbeat response.
array $data The $_POST data sent.
string $screen_id The screen id.
Returns
array The Heartbeat response.
Definition at line 818 of file wp-admin/includes/misc.php.
References $post_id, absint(), and current_user_can().
wp_reset_vars ($vars)
Resets global variables based on $_GET and $_POST.
This function resets global variables based on the names passed in the $vars array to the value of $_POST[$var] or $_GET[$var] or '' if neither is defined.
Since
2.0.0
Parameters
array $vars An array of globals to reset.
Definition at line 303 of file wp-admin/includes/misc.php.
References $GLOBALS.
Referenced by WP_Theme_Install_List_Table\prepare_items(), WP_Links_List_Table\prepare_items(), WP_Plugin_Install_List_Table\prepare_items(), WP_Plugins_List_Table\prepare_items(), and WP_MS_Themes_List_Table\prepare_items().