GravityView: image.php File Reference
wp-admin/includes/image.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_copy_image_file ($attachment_id)
Copy an existing image file.
_load_image_to_edit_path ($attachment_id, $size= 'full')
Retrieve the path or url of an attachment's attached file.
file_is_displayable_image ($path)
Validate that file is suitable for displaying within a web page.
file_is_valid_image ($path)
Validate that file is an image.
load_image_to_edit ($attachment_id, $mime_type, $size= 'full')
Load an image resource for editing.
wp_crop_image ($src, $src_x, $src_y, $src_w, $src_h, $dst_w, $dst_h, $src_abs=false, $dst_file=false)
Crop an Image to a given size.
wp_exif_date2ts ($str)
Convert the exif date format to a unix timestamp.
wp_exif_frac2dec ($str)
Convert a fraction string to a decimal.
wp_generate_attachment_metadata ($attachment_id, $file)
Generate post thumbnail attachment meta data.
wp_read_image_metadata ($file)
Get extended image metadata, exif or iptc as available.
Function Documentation
_copy_image_file ($attachment_id)
Copy an existing image file.
Since
3.4.0 private
Parameters
string $attachment_id Attachment ID.
Returns
string|false New file path on success, false on failure.
Definition at line 591 of file wp-admin/includes/image.php.
References _load_image_to_edit_path(), get_attached_file(), str_replace, wp_mkdir_p(), and wp_unique_filename().
Referenced by Custom_Image_Header\step_3().
_load_image_to_edit_path ($attachment_id, $size = 'full')
Retrieve the path or url of an attachment's attached file.
If the attached file is not present on the local filesystem (usually due to replication plugins), then the url of the file is returned if url fopen is supported.
Since
3.4.0 private
Parameters
string $attachment_id Attachment ID.
string $size Optional. Image size, defaults to 'full'.
Returns
string|false File path or url on success, false on failure.
Filter the path to the current image.
The filter is evaluated for all image sizes except 'full'.
Since
3.1.0
Parameters
string $path Path to the current image.
string $attachment_id Attachment ID.
string $size Size of the image.
Filter the image URL if not in the local filesystem.
The filter is only evaluated if fopen is enabled on the server.
Since
3.1.0
Parameters
string $image_url Current image URL.
string $attachment_id Attachment ID.
string $size Size of the image.
Filter the returned path or URL of the current image.
Since
2.9.0
Parameters
string | bool $filepath File path or URL to current image, or false.
string $attachment_id Attachment ID.
string $size Size of the image.
Definition at line 537 of file wp-admin/includes/image.php.
References $size, apply_filters(), elseif, get_attached_file(), image_get_intermediate_size(), path_join(), and wp_get_attachment_url().
Referenced by _copy_image_file(), load_image_to_edit(), stream_preview_image(), wp_crop_image(), and wp_save_image().
file_is_displayable_image ($path)
Validate that file is suitable for displaying within a web page.
Since
2.5.0
Parameters
string $path File path to test.
Returns
bool True if suitable, false if not suitable.
Filter whether the current image is displayable in the browser.
Since
2.5.0
Parameters
bool $result Whether the image can be displayed. Default true.
string $path Path to the image.
Definition at line 453 of file wp-admin/includes/image.php.
References $path, apply_filters(), and elseif.
Referenced by wp_generate_attachment_metadata().
file_is_valid_image ($path)
Validate that file is an image.
Since
2.5.0
Parameters
string $path File path to test if valid image.
Returns
bool True if valid image, false if not valid image.
Definition at line 440 of file wp-admin/includes/image.php.
References $path, and $size.
load_image_to_edit ($attachment_id, $mime_type, $size = 'full')
Load an image resource for editing.
Since
2.9.0
Parameters
string $attachment_id Attachment ID.
string $mime_type Image mime type.
string $size Optional. Image size, defaults to 'full'.
Returns
resource|false The resulting image resource on success, false on failure.
Filter the current image being loaded for editing.
Since
2.9.0
Parameters
resource $image Current image.
string $attachment_id Attachment ID.
string $size Image size.
Definition at line 486 of file wp-admin/includes/image.php.
References $image, $size, _load_image_to_edit_path(), and apply_filters().
wp_crop_image ($src, $src_x, $src_y, $src_w, $src_h, $dst_w, $dst_h, $src_abs = false, $dst_file = false)
Crop an Image to a given size.
Since
2.1.0
Parameters
string | int $src The source file or Attachment ID.
int $src_x The start x position to crop from.
int $src_y The start y position to crop from.
int $src_w The width to crop.
int $src_h The height to crop.
int $dst_w The destination width.
int $dst_h The destination height.
int $src_abs Optional. If the source crop points are absolute.
string $dst_file Optional. The destination file to write to.
Returns
string|WP_Error New filepath on success, WP_Error on failure.
Definition at line 25 of file wp-admin/includes/image.php.
References _load_image_to_edit_path(), get_attached_file(), is_wp_error(), str_replace, wp_get_image_editor(), wp_mkdir_p(), and wp_unique_filename().
Referenced by Custom_Image_Header\ajax_header_crop(), Custom_Image_Header\step_2(), Custom_Image_Header\step_3(), and wp_ajax_crop_image().
wp_exif_date2ts ($str)
Convert the exif date format to a unix timestamp.
Since
2.5.0
Parameters
string $str
Returns
int
Definition at line 235 of file wp-admin/includes/image.php.
Referenced by wp_read_image_metadata().
wp_exif_frac2dec ($str)
Convert a fraction string to a decimal.
Since
2.5.0
Parameters
string $str
Returns
int|float
Definition at line 220 of file wp-admin/includes/image.php.
Referenced by wp_read_image_metadata().
wp_generate_attachment_metadata ($attachment_id, $file)
Generate post thumbnail attachment meta data.
Since
2.1.0
array $_wp_additional_image_sizes
Parameters
int $attachment_id Attachment Id to process.
string $file Filepath of the Attached image.
Returns
mixed Metadata for attachment.
Filter the image sizes automatically generated when uploading an image.
Since
2.9.0
4.4.0 Added the $metadata argument.
Parameters
array $sizes An associative array of image sizes.
array $metadata An associative array of image metadata: width, height, file.
Filter the parameters for the attachment thumbnail creation.
Since
3.9.0
Parameters
array $image_attachment An array of parameters to create the thumbnail.
array $metadata Current attachment metadata.
array $uploaded An array containing the thumbnail path and url.
Filter the generated attachment meta data.
Since
2.1.0
Parameters
array $metadata An array of attachment meta data.
int $attachment_id Current attachment ID.
Definition at line 76 of file wp-admin/includes/image.php.
References $file, $image_meta, $metadata, $s, _wp_relative_upload_path(), add_post_meta(), apply_filters(), current_theme_supports(), elseif, file_is_displayable_image(), get_intermediate_image_sizes(), get_option(), get_post(), get_post_mime_type(), get_posts(), is_wp_error(), post_type_supports(), str_replace, update_post_meta(), wp_attachment_is(), wp_get_image_editor(), wp_insert_attachment(), wp_read_audio_metadata(), wp_read_image_metadata(), wp_read_video_metadata(), wp_update_attachment_metadata(), and wp_upload_bits().
Referenced by WP_UnitTestCase\_make_attachment(), WP_UnitTest_Factory_For_Attachment\create_upload_object(), WP_Site_Icon\insert_attachment(), Custom_Image_Header\insert_attachment(), media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), wp_xmlrpc_server\mw_newMediaObject(), Custom_Image_Header\step_2(), wp_ajax_crop_image(), and wp_maybe_generate_attachment_metadata().
wp_read_image_metadata ($file)
Get extended image metadata, exif or iptc as available.
Retrieves the EXIF metadata aperture, credit, camera, caption, copyright, iso created_timestamp, focal_length, shutter_speed, and title.
The IPTC metadata that is retrieved is APP13, credit, byline, created date and time, caption, copyright, and title. Also includes FNumber, Model, DateTimeDigitized, FocalLength, ISOSpeedRatings, and ExposureTime.
Parameters
string $file
Returns
bool|array False on failure. Image metadata array on success.
Filter the image types to check for exif data.
Since
2.5.0
Parameters
array $image_types Image types to check for exif data.
Filter the array of meta data read from an image's exif data.
Since
2.5.0
4.4.0 The $iptc parameter was added.
Parameters
array $meta Image meta data.
string $file Path to image file.
int $sourceImageType Type of image.
array $iptc IPTC data.
Definition at line 258 of file wp-admin/includes/image.php.
References $caption, $file, $value, apply_filters(), elseif, mbstring_binary_safe_encoding(), reset_mbstring_encoding(), seems_utf8(), wp_exif_date2ts(), wp_exif_frac2dec(), and wp_kses_post().
Referenced by media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), and wp_generate_attachment_metadata().