GravityView: taxonomy.php File Reference
wp-admin/includes/taxonomy.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
category_exists ($cat_name, $parent=null)
Check whether a category exists.
get_category_to_edit ($id)
Get category object for given ID and 'edit' filter context.
get_tags_to_edit ($post_id, $taxonomy= 'post_tag')
Get comma-separated list of tags available to edit.
get_terms_to_edit ($post_id, $taxonomy= 'post_tag')
Get comma-separated list of terms available to edit for the given post ID.
tag_exists ($tag_name)
Check whether a post tag with a given name exists.
wp_create_categories ($categories, $post_id= '')
Create categories for the given post.
wp_create_category ($cat_name, $parent=0)
Add a new category to the database if it does not already exist.
wp_create_tag ($tag_name)
Add a new tag to the database if it does not already exist.
wp_create_term ($tag_name, $taxonomy= 'post_tag')
Add a new term to the database if it does not already exist.
wp_insert_category ($catarr, $wp_error=false)
Updates an existing Category or creates a new Category.
wp_update_category ($catarr)
Aliases wp_insert_category() with minimal args.
Function Documentation
category_exists ($cat_name, $parent = null)
Check whether a category exists.
Since
2.0.0
See also
term_exists()
Parameters
int | string $cat_name Category name.
int $parent Optional. ID of parent term.
Returns
mixed
Definition at line 24 of file wp-admin/includes/taxonomy.php.
References $id, and term_exists().
Referenced by wp_create_categories(), and wp_create_category().
get_category_to_edit ($id)
Get category object for given ID and 'edit' filter context.
Since
2.0.0
Parameters
int $id
Returns
object
Definition at line 39 of file wp-admin/includes/taxonomy.php.
References $id, _make_cat_compat(), get_term(), and OBJECT.
get_tags_to_edit ($post_id, $taxonomy = 'post_tag')
Get comma-separated list of tags available to edit.
Since
2.3.0
Parameters
int $post_id
string $taxonomy Optional. The taxonomy for which to retrieve terms. Default 'post_tag'.
Returns
string|bool|WP_Error
Definition at line 224 of file wp-admin/includes/taxonomy.php.
References $post_id, and get_terms_to_edit().
get_terms_to_edit ($post_id, $taxonomy = 'post_tag')
Get comma-separated list of terms available to edit for the given post ID.
Since
2.8.0
Parameters
int $post_id
string $taxonomy Optional. The taxonomy for which to retrieve terms. Default 'post_tag'.
Returns
string|bool|WP_Error
Filter the comma-separated list of terms available to edit.
Since
2.8.0
See also
get_terms_to_edit()
Parameters
array $terms_to_edit An array of terms.
string $taxonomy The taxonomy for which to retrieve terms. Default 'post_tag'.
Definition at line 237 of file wp-admin/includes/taxonomy.php.
References $post_id, apply_filters(), esc_attr(), get_object_term_cache(), is_wp_error(), wp_cache_add(), and wp_get_object_terms().
Referenced by get_inline_data(), get_tags_to_edit(), post_tags_meta_box(), and WP_Press_This\tags_html().
tag_exists ($tag_name)
Check whether a post tag with a given name exists.
Since
2.3.0
Parameters
int | string $tag_name
Returns
mixed
Definition at line 199 of file wp-admin/includes/taxonomy.php.
References term_exists().
wp_create_categories ($categories, $post_id = '')
Create categories for the given post.
Since
2.0.0
Parameters
array $categories List of categories to create.
int $post_id Optional. The post ID. Default empty.
Returns
array List of categories to create for the given post.
Definition at line 70 of file wp-admin/includes/taxonomy.php.
References $id, $post_id, category_exists(), elseif, wp_create_category(), and wp_set_post_categories().
wp_create_category ($cat_name, $parent = 0)
Add a new category to the database if it does not already exist.
Since
2.0.0
Parameters
int | string $cat_name
int $parent
Returns
int|WP_Error
Definition at line 54 of file wp-admin/includes/taxonomy.php.
References $id, category_exists(), and wp_insert_category().
Referenced by wp_create_categories().
wp_create_tag ($tag_name)
Add a new tag to the database if it does not already exist.
Since
2.3.0
Parameters
int | string $tag_name
Returns
array|WP_Error
Definition at line 211 of file wp-admin/includes/taxonomy.php.
References wp_create_term().
Referenced by Featured_Content\validate_settings().
wp_create_term ($tag_name, $taxonomy = 'post_tag')
Add a new term to the database if it does not already exist.
Since
2.8.0
Parameters
int | string $tag_name
string $taxonomy Optional. The taxonomy for which to retrieve terms. Default 'post_tag'.
Returns
array|WP_Error
Definition at line 285 of file wp-admin/includes/taxonomy.php.
References $id, term_exists(), and wp_insert_term().
Referenced by wp_create_tag().
wp_insert_category ($catarr, $wp_error = false)
Updates an existing Category or creates a new Category.
Since
2.0.0
2.5.0 $wp_error parameter was added.
3.0.0 The 'taxonomy' argument was added.
Parameters
array $catarr { Array of arguments for inserting a new category.
int $cat_ID Category ID. A non-zero value updates an existing category. Default 0. string $taxonomy Taxonomy slug. Default 'category'. string $cat_name Category name. Default empty. string $category_description Category description. Default empty. string $category_nicename Category nice (display) name. Default empty. int|string $category_parent Category parent ID. Default empty. }
Parameters
bool $wp_error Optional. Default false.
Returns
int|object The ID number of the new or updated Category on success. Zero or a WP_Error on failure, depending on param $wp_error.
Definition at line 108 of file wp-admin/includes/taxonomy.php.
References $description, $name, $update, __, is_wp_error(), term_exists(), term_is_ancestor_of(), wp_insert_term(), wp_parse_args(), and wp_update_term().
Referenced by wp_create_category(), wp_xmlrpc_server\wp_newCategory(), and wp_update_category().
wp_update_category ($catarr)
Aliases wp_insert_category() with minimal args.
If you want to update only some fields of an existing category, call this function with only the new values set inside $catarr.
Since
2.0.0
Parameters
array $catarr The 'cat_ID' value is required. All other keys are optional.
Returns
int|bool The ID number of the new or updated Category on success. Zero or FALSE on failure.
Definition at line 168 of file wp-admin/includes/taxonomy.php.
References _make_cat_compat(), ARRAY_A, get_term(), wp_insert_category(), and wp_slash().