GravityView: deprecated.php File Reference
wp-admin/includes/deprecated.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_insert_into_post_button ($type)
This was once used to display an 'Insert into Post' button.
_media_button ($title, $icon, $type, $id)
This was once used to display a media button.
_relocate_children ($old_ID, $new_ID)
This was once used to move child posts to a new parent.
add_contextual_help ($screen, $help)
Add contextual help text for a page.
add_object_page ($page_title, $menu_title, $capability, $menu_slug, $function= '', $icon_url= '')
Add a top-level menu page in the 'objects' section.
add_option_update_handler ($option_group, $option_name, $sanitize_callback= '')
Register a setting and its sanitization callback.
add_utility_page ($page_title, $menu_title, $capability, $menu_slug, $function= '', $icon_url= '')
Add a top-level menu page in the 'utility' section.
codepress_footer_js ()
Adds JavaScript required to make CodePress work on the theme/plugin editors.
codepress_get_lang ($filename)
Determines the language to use for CodePress syntax highlighting.
current_theme_info ()
Retrieves information on the current active theme.
documentation_link ()
Unused Admin function.
dropdown_categories ($default=0, $parent=0, $popular_ids=array())
Legacy function used to generate the categories checklist control.
dropdown_link_categories ($default=0)
Legacy function used to generate a link categories checklist control.
favorite_actions ()
Favorite actions were deprecated in version 3.2.
get_allowed_themes ()
Get the allowed themes for the current blog.
get_author_user_ids ()
Get all user IDs.
get_broken_themes ()
Retrieves a list of broken themes.
get_default_page_to_edit ()
Gets the default page information to use.
get_editable_authors ($user_id)
Gets author users who can edit posts.
get_editable_user_ids ($user_id, $exclude_zeros=true, $post_type= 'post')
Gets the IDs of any users who can edit posts.
get_others_drafts ($user_id)
Retrieve drafts from other users.
get_others_pending ($user_id)
Retrieve pending review posts from other users.
get_others_unpublished_posts ($user_id, $type= 'any')
Retrieves editable posts from other users.
get_post_to_edit ($id)
Gets an existing post and format it for editing.
get_real_file_to_edit ($file)
Get the real filesystem path to a file to edit within the admin.
get_screen_icon ()
Retrieves the screen icon (no longer used in 3.8+).
get_udims ($width, $height)
Calculated the new dimensions for a downsampled image.
media_upload_audio ()
Handles uploading an audio file.
media_upload_file ()
Handles uploading a generic file.
media_upload_image ()
Handles uploading an image.
media_upload_video ()
Handles uploading a video file.
remove_option_update_handler ($option_group, $option_name, $sanitize_callback= '')
Unregister a setting.
screen_icon ()
Displays a screen icon.
screen_layout ($screen)
Returns the screen layout options.
screen_meta ($screen)
Renders the screen's help.
screen_options ($screen)
Returns the screen's per-page options.
the_attachment_links ($id=false)
This was once used to display attachment links.
tinymce_include ()
type_url_form_audio ()
Handles retrieving the insert-from-URL form for an audio file.
type_url_form_file ()
Handles retrieving the insert-from-URL form for a generic file.
type_url_form_image ()
Handles retrieving the insert-from-URL form for an image.
type_url_form_video ()
Handles retrieving the insert-from-URL form for a video file.
use_codepress ()
Determine whether to use CodePress.
wp_create_thumbnail ($file, $max_side, $deprecated= '')
This was once used to create a thumbnail from an Image given a maximum side size.
wp_dashboard_incoming_links ()
Deprecated dashboard widget controls.
wp_dashboard_incoming_links_control ()
Deprecated dashboard incoming links control.
wp_dashboard_incoming_links_output ()
Deprecated dashboard widget controls.
wp_dashboard_plugins ()
Deprecated dashboard plugins control.
wp_dashboard_primary_control ()
Deprecated dashboard primary control.
wp_dashboard_quick_press_output ()
Output the QuickPress dashboard widget.
wp_dashboard_recent_comments_control ()
Deprecated dashboard recent comments control.
wp_dashboard_secondary ()
Deprecated dashboard secondary section.
wp_dashboard_secondary_control ()
Deprecated dashboard secondary control.
wp_dashboard_secondary_output ()
Deprecated dashboard secondary output.
wp_dropdown_cats ($currentcat=0, $currentparent=0, $parent=0, $level=0, $categories=0)
Legacy function used for generating a categories drop-down control.
wp_nav_menu_locations_meta_box ()
This was once used to display a metabox for the nav menu theme locations.
wp_preload_dialogs ()
Preloads TinyMCE dialogs.
wp_print_editor_js ()
Prints TinyMCE editor JS.
wp_quicktags ()
Handles quicktags.
wp_shrink_dimensions ($width, $height, $wmax=128, $hmax=96)
Calculates the new dimensions for a downsampled image.
wp_tiny_mce ($teeny=false, $settings=false)
Outputs the TinyMCE editor.
wp_update_core ($current, $feedback= '')
This was once used to kick-off the Core Updater.
wp_update_plugin ($plugin, $feedback= '')
This was once used to kick-off the Plugin Updater.
wp_update_theme ($theme, $feedback= '')
This was once used to kick-off the Theme Updater.
Variables
endif
Function Documentation
_insert_into_post_button ($type)
This was once used to display an 'Insert into Post' button.
Now it is deprecated and stubbed.
Definition at line 1054 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
_media_button ($title, $icon, $type, $id)
This was once used to display a media button.
Now it is deprecated and stubbed.
Definition at line 1065 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
_relocate_children ($old_ID, $new_ID)
This was once used to move child posts to a new parent.
Since
2.3.0
Parameters
int $old_ID
int $new_ID
Definition at line 1307 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
add_contextual_help ($screen, $help)
Add contextual help text for a page.
Creates an 'Overview' help tab.
Since
2.7.0
Parameters
string $screen The handle for the screen to add help to. This is usually the hook name returned by the add_*_page() functions.
string $help The content of an 'Overview' help tab.
Definition at line 976 of file wp-admin/includes/deprecated.php.
References $help, $screen, _deprecated_function(), WP_Screen\add_old_compat_help(), and convert_to_screen().
Referenced by twentyeleven_theme_options_help().
add_object_page ($page_title, $menu_title, $capability, $menu_slug, $function = '', $icon_url = '')
Add a top-level menu page in the 'objects' section.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Since
2.7.0
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
string $icon_url The url to the icon to be used for this menu.
Returns
string The resulting page's hook_suffix.
Definition at line 1334 of file wp-admin/includes/deprecated.php.
References $_wp_last_object_menu, $capability, _deprecated_function(), and add_menu_page().
add_option_update_handler ($option_group, $option_name, $sanitize_callback = '')
Register a setting and its sanitization callback.
Since
2.7.0
Parameters
string $option_group A settings group name. Should correspond to a whitelisted option key name. Default whitelisted option key names include "general," "discussion," and "reading," among others.
string $option_name The name of an option to sanitize and save.
callable $sanitize_callback A callback function that sanitizes the option's value.
Definition at line 167 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and register_setting().
add_utility_page ($page_title, $menu_title, $capability, $menu_slug, $function = '', $icon_url = '')
Add a top-level menu page in the 'utility' section.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Since
2.7.0
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
string $icon_url The url to the icon to be used for this menu.
Returns
string The resulting page's hook_suffix.
Definition at line 1367 of file wp-admin/includes/deprecated.php.
References $_wp_last_utility_menu, $capability, _deprecated_function(), and add_menu_page().
codepress_footer_js ()
Adds JavaScript required to make CodePress work on the theme/plugin editors.
Since
2.8.0
Definition at line 206 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
codepress_get_lang ($filename)
Determines the language to use for CodePress syntax highlighting.
Since
2.8.0
Parameters
string $filename
Definition at line 196 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
current_theme_info ()
Retrieves information on the current active theme.
Since
2.0.0
Returns
WP_Theme
Definition at line 1041 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_get_theme().
documentation_link ()
Unused Admin function.
Since
2.0.0
Definition at line 33 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
dropdown_categories ($default = 0, $parent = 0, $popular_ids = array())
Legacy function used to generate the categories checklist control.
Since
0.71
Parameters
int $default Unused.
int $parent Unused.
array $popular_ids Unused.
Definition at line 82 of file wp-admin/includes/deprecated.php.
References $post_ID, _deprecated_function(), and wp_category_checklist().
dropdown_link_categories ($default = 0)
Legacy function used to generate a link categories checklist control.
Since
2.1.0
Parameters
int $default Unused.
Definition at line 97 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_link_category_checklist().
favorite_actions ()
Favorite actions were deprecated in version 3.2.
Use the admin bar instead.
Since
2.7.0
Definition at line 856 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
get_allowed_themes ()
Get the allowed themes for the current blog.
Since
3.0.0
Returns
array $themes Array of allowed themes.
Definition at line 994 of file wp-admin/includes/deprecated.php.
References $theme, _deprecated_function(), and wp_get_themes().
get_author_user_ids ()
Get all user IDs.
Returns
array List of user IDs.
Definition at line 227 of file wp-admin/includes/deprecated.php.
References $wpdb, _deprecated_function(), and is_multisite().
get_broken_themes ()
Retrieves a list of broken themes.
Since
1.5.0
Returns
array
Definition at line 1016 of file wp-admin/includes/deprecated.php.
References $name, $theme, _deprecated_function(), and wp_get_themes().
get_default_page_to_edit ()
Gets the default page information to use.
Since
2.5.0
Returns
WP_Post Post object containing all the default post data as attributes
Definition at line 1094 of file wp-admin/includes/deprecated.php.
References $page, _deprecated_function(), and get_default_post_to_edit().
get_editable_authors ($user_id)
Gets author users who can edit posts.
Parameters
int $user_id User ID.
Returns
array|bool List of editable authors. False if no editable users.
Definition at line 247 of file wp-admin/includes/deprecated.php.
References $authors, $user_id, $wpdb, _deprecated_function(), apply_filters(), and get_editable_user_ids().
get_editable_user_ids ($user_id, $exclude_zeros = true, $post_type = 'post')
Gets the IDs of any users who can edit posts.
Parameters
int $user_id User ID.
bool $exclude_zeros Optional. Whether to exclude zeroes. Default true.
Returns
array Array of editable user IDs, empty array otherwise.
Definition at line 273 of file wp-admin/includes/deprecated.php.
References $post_type, $user, $user_id, $wpdb, _deprecated_function(), get_post_type_object(), and is_multisite().
Referenced by get_editable_authors(), and get_others_unpublished_posts().
get_others_drafts ($user_id)
Retrieve drafts from other users.
Parameters
int $user_id User ID.
Returns
array List of drafts from other users.
Definition at line 705 of file wp-admin/includes/deprecated.php.
References $user_id, _deprecated_function(), and get_others_unpublished_posts().
get_others_pending ($user_id)
Retrieve pending review posts from other users.
Parameters
int $user_id User ID.
Returns
array List of posts with pending review post type from other users.
Definition at line 720 of file wp-admin/includes/deprecated.php.
References $user_id, _deprecated_function(), and get_others_unpublished_posts().
get_others_unpublished_posts ($user_id, $type = 'any')
Retrieves editable posts from other users.
Since
2.3.0
Parameters
int $user_id User ID to not retrieve posts from.
string $type Optional. Post type to retrieve. Accepts 'draft', 'pending' or 'any' (all). Default 'any'.
Returns
array List of posts from others.
Definition at line 672 of file wp-admin/includes/deprecated.php.
References $dir, $user_id, $wpdb, _deprecated_function(), apply_filters(), and get_editable_user_ids().
Referenced by get_others_drafts(), and get_others_pending().
get_post_to_edit ($id)
Gets an existing post and format it for editing.
Since
2.0.0
Parameters
int $id
Returns
object
Definition at line 1079 of file wp-admin/includes/deprecated.php.
References $id, _deprecated_function(), get_post(), and OBJECT.
get_real_file_to_edit ($file)
Get the real filesystem path to a file to edit within the admin.
Since
1.5.0
Parameters
string $file Filesystem path relative to the wp-content directory.
Returns
string Full filesystem path to edit.
Definition at line 113 of file wp-admin/includes/deprecated.php.
References $file, _deprecated_function(), and WP_CONTENT_DIR.
get_screen_icon ()
Retrieves the screen icon (no longer used in 3.8+).
Returns
string
Definition at line 1228 of file wp-admin/includes/deprecated.php.
Referenced by screen_icon().
get_udims ($width, $height)
Calculated the new dimensions for a downsampled image.
Since
2.0.0
Parameters
int $width Current width of the image
int $height Current height of the image
Returns
array Shrunk dimensions (width, height).
Definition at line 66 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_constrain_dimensions().
media_upload_audio ()
Handles uploading an audio file.
Returns
null|string
Definition at line 881 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_media_upload_handler().
media_upload_file ()
Handles uploading a generic file.
Returns
null|string
Definition at line 907 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_media_upload_handler().
media_upload_image ()
Handles uploading an image.
Returns
null|string
Definition at line 868 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_media_upload_handler().
media_upload_video ()
Handles uploading a video file.
Returns
null|string
Definition at line 894 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_media_upload_handler().
remove_option_update_handler ($option_group, $option_name, $sanitize_callback = '')
Unregister a setting.
Since
2.7.0
Parameters
string $option_group
string $option_name
callable $sanitize_callback
Definition at line 183 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and unregister_setting().
screen_icon ()
Displays a screen icon.
Since
2.7.0
3.8.0 Screen icons are no longer used in WordPress. This function no longer produces output.
Definition at line 1217 of file wp-admin/includes/deprecated.php.
References get_screen_icon().
Referenced by twentyeleven_theme_options_render_page().
screen_layout ($screen)
Returns the screen layout options.
Since
2.8.0
Definition at line 804 of file wp-admin/includes/deprecated.php.
References $current_screen, _deprecated_function(), and get_current_screen().
screen_meta ($screen)
Renders the screen's help.
Since
2.7.0
Definition at line 844 of file wp-admin/includes/deprecated.php.
References $current_screen, and get_current_screen().
screen_options ($screen)
Returns the screen's per-page options.
Since
2.8.0
Definition at line 824 of file wp-admin/includes/deprecated.php.
References $current_screen, _deprecated_function(), and get_current_screen().
the_attachment_links ($id = false)
This was once used to display attachment links.
Now it is deprecated and stubbed.
Since
2.0.0
Parameters
int | bool $id
Definition at line 1205 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
tinymce_include ()
Since
2.1.0
Definition at line 20 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_tiny_mce().
type_url_form_audio ()
Handles retrieving the insert-from-URL form for an audio file.
Returns
string
Definition at line 933 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_media_insert_url_form().
type_url_form_file ()
Handles retrieving the insert-from-URL form for a generic file.
Returns
string
Definition at line 959 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_media_insert_url_form().
type_url_form_image ()
Handles retrieving the insert-from-URL form for an image.
Returns
string
Definition at line 920 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_media_insert_url_form().
type_url_form_video ()
Handles retrieving the insert-from-URL form for a video file.
Returns
string
Definition at line 946 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_media_insert_url_form().
use_codepress ()
Determine whether to use CodePress.
Since
2.8.0
Definition at line 216 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
wp_create_thumbnail ($file, $max_side, $deprecated = '')
This was once used to create a thumbnail from an Image given a maximum side size.
Since
1.2.0
Parameters
mixed $file Filename of the original image, Or attachment id.
int $max_side Maximum length of a single side for the thumbnail.
mixed $deprecated Never used.
Returns
string Thumbnail path on success, Error string on failure.
Definition at line 1114 of file wp-admin/includes/deprecated.php.
References $file, _deprecated_function(), apply_filters(), and image_resize().
wp_dashboard_incoming_links ()
Deprecated dashboard widget controls.
Since
2.7.0
Definition at line 1253 of file wp-admin/includes/deprecated.php.
wp_dashboard_incoming_links_control ()
Deprecated dashboard incoming links control.
Definition at line 1260 of file wp-admin/includes/deprecated.php.
wp_dashboard_incoming_links_output ()
Deprecated dashboard widget controls.
Since
2.5.0
Definition at line 1238 of file wp-admin/includes/deprecated.php.
wp_dashboard_plugins ()
Deprecated dashboard plugins control.
Definition at line 1267 of file wp-admin/includes/deprecated.php.
wp_dashboard_primary_control ()
Deprecated dashboard primary control.
Definition at line 1274 of file wp-admin/includes/deprecated.php.
wp_dashboard_quick_press_output ()
Output the QuickPress dashboard widget.
Since
3.0.0
Definition at line 733 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_dashboard_quick_press().
wp_dashboard_recent_comments_control ()
Deprecated dashboard recent comments control.
Definition at line 1281 of file wp-admin/includes/deprecated.php.
wp_dashboard_secondary ()
Deprecated dashboard secondary section.
Definition at line 1288 of file wp-admin/includes/deprecated.php.
wp_dashboard_secondary_control ()
Deprecated dashboard secondary control.
Definition at line 1295 of file wp-admin/includes/deprecated.php.
wp_dashboard_secondary_output ()
Deprecated dashboard secondary output.
Definition at line 1245 of file wp-admin/includes/deprecated.php.
wp_dropdown_cats ($currentcat = 0, $currentparent = 0, $parent = 0, $level = 0, $categories = 0)
Legacy function used for generating a categories drop-down control.
Since
1.2.0
Parameters
int $currentcat Optional. ID of the current category. Default 0.
int $currentparent Optional. Current parent category ID. Default 0.
int $parent Optional. Parent ID to retrieve categories for. Default 0.
int $level Optional. Number of levels deep to display. Default 0.
array $categories Optional. Categories to include in the control. Default 0.
Returns
bool|null False if no categories were found.
Definition at line 133 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), esc_html, and get_categories().
wp_nav_menu_locations_meta_box ()
This was once used to display a metabox for the nav menu theme locations.
Deprecated in favor of a 'Manage Locations' tab added to nav menus management screen.
Since
3.0.0
Definition at line 1127 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
wp_preload_dialogs ()
Preloads TinyMCE dialogs.
Definition at line 773 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
wp_print_editor_js ()
Prints TinyMCE editor JS.
Definition at line 783 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
wp_quicktags ()
Handles quicktags.
Definition at line 793 of file wp-admin/includes/deprecated.php.
References _deprecated_function().
wp_shrink_dimensions ($width, $height, $wmax = 128, $hmax = 96)
Calculates the new dimensions for a downsampled image.
Since
2.0.0
Parameters
int $width Current width of the image
int $height Current height of the image
int $wmax Maximum wanted width
int $hmax Maximum wanted height
Returns
array Shrunk dimensions (width, height).
Definition at line 50 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), and wp_constrain_dimensions().
wp_tiny_mce ($teeny = false, $settings = false)
Outputs the TinyMCE editor.
Since
2.7.0
int $num
Definition at line 747 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), ABSPATH, _WP_Editors\editor_settings(), _WP_Editors\parse_settings(), and WPINC.
Referenced by tinymce_include().
wp_update_core ($current, $feedback = '')
This was once used to kick-off the Core Updater.
Deprecated in favor of instantating a Core_Upgrader instance directly, and calling the 'upgrade' method.
Since
2.7.0
Definition at line 1141 of file wp-admin/includes/deprecated.php.
References _deprecated_function(), ABSPATH, and add_filter().
wp_update_plugin ($plugin, $feedback = '')
This was once used to kick-off the Plugin Updater.
Deprecated in favor of instantating a Plugin_Upgrader instance directly, and calling the 'upgrade' method. Unused since 2.8.0.
Since
2.5.0
Definition at line 1164 of file wp-admin/includes/deprecated.php.
References $plugin, _deprecated_function(), ABSPATH, and add_filter().
wp_update_theme ($theme, $feedback = '')
This was once used to kick-off the Theme Updater.
Deprecated in favor of instantating a Theme_Upgrader instance directly, and calling the 'upgrade' method. Unused since 2.8.0.
Since
2.7.0
Definition at line 1186 of file wp-admin/includes/deprecated.php.
References $theme, _deprecated_function(), ABSPATH, and add_filter().
Variable Documentation
endif
Definition at line 658 of file wp-admin/includes/deprecated.php.