GravityView: plugin.php File Reference
wp-admin/includes/plugin.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_dropins ()
Returns drop-ins that WordPress uses.
_get_plugin_data_markup_translate ($plugin_file, $plugin_data, $markup=true, $translate=true)
Sanitizes plugin data, optionally adds markup, optionally translates.
_sort_uname_callback ($a, $b)
Callback to sort array by a 'Name' key.
activate_plugin ($plugin, $redirect= '', $network_wide=false, $silent=false)
Attempts activation of plugin in a "sandbox" and redirects on success.
activate_plugins ($plugins, $redirect= '', $network_wide=false, $silent=false)
Activate multiple plugins.
add_comments_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Comments main menu.
add_dashboard_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Dashboard main menu.
add_links_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Links main menu.
add_management_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Tools main menu.
add_media_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Media main menu.
add_menu_page ($page_title, $menu_title, $capability, $menu_slug, $function= '', $icon_url= '', $position=null)
Add a top-level menu page.
add_option_whitelist ($new_options, $options= '')
Adds an array of options to the options whitelist.
add_options_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Settings main menu.
add_pages_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Pages main menu.
add_plugins_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Plugins main menu.
add_posts_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Posts main menu.
add_submenu_page ($parent_slug, $page_title, $menu_title, $capability, $menu_slug, $function= '')
Add a submenu page.
add_theme_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Appearance main menu.
add_users_page ($page_title, $menu_title, $capability, $menu_slug, $function= '')
Add submenu page to the Users/Profile main menu.
deactivate_plugins ($plugins, $silent=false, $network_wide=null)
Deactivate a single plugin or multiple plugins.
delete_plugins ($plugins, $deprecated= '')
Remove directory and files of a plugin for a list of plugins.
get_admin_page_parent ($parent= '')
string $parent_file array $menu array $submenu string $pagenow string $typenow string $plugin_page array $_wp_real_parent_file array $_wp_menu_nopriv array $_wp_submenu_nopriv
get_admin_page_title ()
string $title array $menu array $submenu string $pagenow string $plugin_page string $typenow
get_dropins ()
Check the wp-content directory and retrieve all drop-ins with any plugin data.
get_mu_plugins ()
Check the mu-plugins directory and retrieve all mu-plugin files with any plugin data.
get_plugin_data ($plugin_file, $markup=true, $translate=true)
Parses the plugin contents to retrieve plugin's metadata.
get_plugin_files ($plugin)
Get a list of a plugin's files.
get_plugin_page_hook ($plugin_page, $parent_page)
get_plugin_page_hookname ($plugin_page, $parent_page)
array $admin_page_hooks
get_plugins ($plugin_folder= '')
Check the plugins directory and retrieve all plugin files with plugin data.
is_network_only_plugin ($plugin)
Checks for "Network: true" in the plugin header to see if this should be activated only as a network wide plugin.
is_plugin_active ($plugin)
Check whether the plugin is active by checking the active_plugins list.
is_plugin_active_for_network ($plugin)
Check whether the plugin is active for the entire network.
is_plugin_inactive ($plugin)
Check whether the plugin is inactive.
is_uninstallable_plugin ($plugin)
Whether the plugin can be uninstalled.
menu_page_url ($menu_slug, $echo=true)
Get the url to access a particular menu page based on the slug it was registered with.
option_update_filter ($options)
Refreshes the value of the options whitelist available via the 'whitelist_options' filter.
plugin_sandbox_scrape ($plugin)
register_setting ($option_group, $option_name, $sanitize_callback= '')
Register a setting and its sanitization callback.
remove_menu_page ($menu_slug)
Remove a top-level admin menu.
remove_option_whitelist ($del_options, $options= '')
Removes a list of options from the options whitelist.
remove_submenu_page ($menu_slug, $submenu_slug)
Remove an admin submenu.
settings_fields ($option_group)
Output nonce, action, and option_page fields for a settings page.
uninstall_plugin ($plugin)
Uninstall a single plugin.
unregister_setting ($option_group, $option_name, $sanitize_callback= '')
Unregister a setting.
user_can_access_admin_page ()
string $pagenow array $menu array $submenu array $_wp_menu_nopriv array $_wp_submenu_nopriv string $plugin_page array $_registered_pages
validate_active_plugins ()
Validate active plugins.
validate_plugin ($plugin)
Validate the plugin path.
wp_clean_plugins_cache ($clear_update_cache=true)
Clears the Plugins cache used by get_plugins() and by default, the Plugin Update cache.
Function Documentation
_get_dropins ()
Returns drop-ins that WordPress uses.
Includes Multisite drop-ins only when is_multisite()
Since
3.0.0
Returns
array Key is file name. The value is an array, with the first value the purpose of the drop-in and the second value the name of the constant that must be true for the drop-in to be used, or true if no constant is required.
Definition at line 409 of file wp-admin/includes/plugin.php.
References __, and is_multisite().
Referenced by get_dropins(), and WP_Plugins_List_Table\single_row().
_get_plugin_data_markup_translate ($plugin_file, $plugin_data, $markup = true, $translate = true)
Sanitizes plugin data, optionally adds markup, optionally translates.
Since
2.7.0 private
See also
get_plugin_data()
Definition at line 112 of file wp-admin/includes/plugin.php.
References $field, __, elseif, esc_url, is_textdomain_loaded(), load_plugin_textdomain(), plugin_basename(), translate(), wp_kses(), and wptexturize().
Referenced by get_plugin_data(), and WP_Plugins_List_Table\prepare_items().
_sort_uname_callback ($a, $b)
Callback to sort array by a 'Name' key.
Since
3.1.0 private
Definition at line 354 of file wp-admin/includes/plugin.php.
activate_plugin ($plugin, $redirect = '', $network_wide = false, $silent = false)
Attempts activation of plugin in a "sandbox" and redirects on success.
A plugin that is already activated will not attempt to be activated again.
The way it works is by setting the redirection to the error before trying to include the plugin file. If the plugin fails, then the redirection will not be overwritten with the success message. Also, the options will not be updated and the activation hook will not be called on plugin error.
It should be noted that in no way the below code will actually prevent errors within the file. The code should not be used elsewhere to replicate the "sandbox", which uses redirection to work. { 13 1}
If any errors are found or text is outputted, then it will be captured to ensure that the success redirection will update the error redirection.
Since
2.5.0
Parameters
string $plugin Plugin path to main plugin file with plugin data.
string $redirect Optional. URL to redirect to.
bool $network_wide Optional. Whether to enable the plugin for all sites in the network or just the current site. Multisite only. Default false.
bool $silent Optional. Whether to prevent calling activation hooks. Default false.
Returns
WP_Error|null WP_Error on invalid file or null on success.
Fires before a plugin is activated.
If a plugin is silently activated (such as during an update), this hook does not fire.
Since
2.9.0
Parameters
string $plugin Plugin path to main plugin file with plugin data.
bool $network_wide Whether to enable the plugin for all sites in the network or just the current site. Multisite only. Default is false.
Fires as a specific plugin is being activated.
This hook is the "activation" hook used internally by {
See also
register_activation_hook()}. The dynamic portion of the hook name, $plugin, refers to the plugin basename.
If a plugin is silently activated (such as during an update), this hook does not fire.
Since
2.0.0
Parameters
bool $network_wide Whether to enable the plugin for all sites in the network or just the current site. Multisite only. Default is false.
Fires after a plugin has been activated.
If a plugin is silently activated (such as during an update), this hook does not fire.
Since
2.9.0
Parameters
string $plugin Plugin path to main plugin file with plugin data.
bool $network_wide Whether to enable the plugin for all sites in the network or just the current site. Multisite only. Default is false.
Definition at line 521 of file wp-admin/includes/plugin.php.
References $output, $plugin, $redirect, __, add_query_arg(), do_action(), get_option(), get_site_option(), is_multisite(), is_network_only_plugin(), is_wp_error(), null, plugin_basename(), update_option(), update_site_option(), validate_plugin(), and wp_register_plugin_realpath().
Referenced by activate_plugins().
activate_plugins ($plugins, $redirect = '', $network_wide = false, $silent = false)
Activate multiple plugins.
When WP_Error is returned, it does not mean that one of the plugins had errors. It means that one or more of the plugins file path was invalid.
The execution will be halted as soon as one of the plugins has an error.
Since
2.6.0
Parameters
string | array $plugins Single plugin or list of plugins to activate.
string $redirect Redirect to page after successful activation.
bool $network_wide Whether to enable the plugin for all sites in the network.
bool $silent Prevent calling activation hooks. Default is false.
Returns
bool|WP_Error True when finished or WP_Error if there were errors during a plugin activation.
Definition at line 730 of file wp-admin/includes/plugin.php.
References $errors, $plugin, $plugins, $redirect, __, activate_plugin(), add_query_arg(), and is_wp_error().
add_comments_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Comments main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1388 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_dashboard_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Dashboard main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1288 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_links_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Links main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1348 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_management_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Tools main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1185 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_media_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Media main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1328 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_menu_page ($page_title, $menu_title, $capability, $menu_slug, $function = '', $icon_url = '', $position = null)
Add a top-level menu page.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
array $menu array $admin_page_hooks array $_registered_pages array $_parent_pages
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
string $icon_url The URL to the icon to be used for this menu.
Pass a base64-encoded SVG using a data URI, which will be colored to match the color scheme. This should begin with 'data:image/svg+xml;base64,'.
Pass the name of a Dashicons helper class to use a font icon, e.g. 'dashicons-chart-pie'.
Pass 'none' to leave div.wp-menu-image empty so an icon can be added via CSS.
int $position The position in the menu order this one should appear.
Returns
string The resulting page's hook_suffix.
Definition at line 1057 of file wp-admin/includes/plugin.php.
References $capability, $menu, add_action(), current_user_can(), elseif, get_plugin_page_hookname(), null, plugin_basename(), sanitize_title(), and set_url_scheme().
Referenced by GravityView_Settings\add_network_menu(), add_object_page(), add_utility_page(), and GFForms\create_menu().
add_option_whitelist ($new_options, $options = '')
Adds an array of options to the options whitelist.
Since
2.7.0
array $whitelist_options
Parameters
array $new_options
string | array $options
Returns
array
Definition at line 1841 of file wp-admin/includes/plugin.php.
References $keys, $options, $page, and $whitelist_options.
Referenced by option_update_filter().
add_options_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Settings main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1205 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_pages_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Pages main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1368 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_plugins_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Plugins main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1245 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_posts_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Posts main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1308 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
add_submenu_page ($parent_slug, $page_title, $menu_title, $capability, $menu_slug, $function = '')
Add a submenu page.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
array $submenu array $menu array $_wp_real_parent_file bool $_wp_submenu_nopriv array $_registered_pages array $_parent_pages
Parameters
string $parent_slug The slug name for the parent menu (or the file name of a standard WordPress admin page).
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1120 of file wp-admin/includes/plugin.php.
References $_wp_real_parent_file, $_wp_submenu_nopriv, $capability, $menu, $submenu, add_action(), current_user_can(), get_plugin_page_hookname(), and plugin_basename().
Referenced by _add_post_type_submenus(), _add_themes_utility_last(), add_comments_page(), add_dashboard_page(), add_links_page(), add_management_page(), add_media_page(), add_options_page(), add_pages_page(), add_plugins_page(), add_posts_page(), add_theme_page(), add_users_page(), GravityView_Welcome\admin_menus(), GravityView_Settings\create_app_menu(), and GFForms\create_menu().
add_theme_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Appearance main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1225 of file wp-admin/includes/plugin.php.
References $capability, and add_submenu_page().
Referenced by Custom_Background\init(), Custom_Image_Header\init(), and twentyeleven_theme_options_add_page().
add_users_page ($page_title, $menu_title, $capability, $menu_slug, $function = '')
Add submenu page to the Users/Profile main menu.
This function takes a capability which will be used to determine whether or not a page is included in the menu.
The function which is hooked in to handle the output of the page must check that the user has the required capability as well.
Parameters
string $page_title The text to be displayed in the title tags of the page when the menu is selected.
string $menu_title The text to be used for the menu.
string $capability The capability required for this menu to be displayed to the user.
string $menu_slug The slug name to refer to this menu by (should be unique for this menu).
callable $function The function to be called to output the content for this page.
Returns
false|string The resulting page's hook_suffix, or false if the user does not have the capability required.
Definition at line 1265 of file wp-admin/includes/plugin.php.
References $capability, add_submenu_page(), and current_user_can().
deactivate_plugins ($plugins, $silent = false, $network_wide = null)
Deactivate a single plugin or multiple plugins.
The deactivation hook is disabled by the plugin upgrader by using the $silent parameter.
Since
2.5.0
Parameters
string | array $plugins Single plugin or list of plugins to deactivate.
bool $silent Prevent calling deactivation hooks. Default is false.
mixed $network_wide Whether to deactivate the plugin for all sites in the network. A value of null (the default) will deactivate plugins for both the site and the network.
Fires before a plugin is deactivated.
If a plugin is silently deactivated (such as during an update), this hook does not fire.
Since
2.9.0
Parameters
string $plugin Plugin path to main plugin file with plugin data.
bool $network_deactivating Whether the plugin is deactivated for all sites in the network or just the current site. Multisite only. Default is false.
Fires as a specific plugin is being deactivated.
This hook is the "deactivation" hook used internally by {
See also
register_deactivation_hook()}. The dynamic portion of the hook name, $plugin, refers to the plugin basename.
If a plugin is silently deactivated (such as during an update), this hook does not fire.
Since
2.0.0
Parameters
bool $network_deactivating Whether the plugin is deactivated for all sites in the network or just the current site. Multisite only. Default is false.
Fires after a plugin is deactivated.
If a plugin is silently deactivated (such as during an update), this hook does not fire.
Since
2.9.0
Parameters
string $plugin Plugin basename.
bool $network_deactivating Whether the plugin is deactivated for all sites in the network or just the current site. Multisite only. Default false.
Definition at line 628 of file wp-admin/includes/plugin.php.
References $plugin, $plugins, do_action(), elseif, get_option(), get_site_option(), is_multisite(), is_plugin_active(), is_plugin_active_for_network(), plugin_basename(), update_option(), and update_site_option().
Referenced by _upgrade_440_force_deactivate_incompatible_plugins(), Plugin_Upgrader\deactivate_plugin_before_upgrade(), GFSettings\settings_uninstall_page(), upgrade_380(), and validate_active_plugins().
delete_plugins ($plugins, $deprecated = '')
Remove directory and files of a plugin for a list of plugins.
Since
2.6.0
WP_Filesystem_Base $wp_filesystem
Parameters
array $plugins List of plugins to delete.
string $deprecated Deprecated.
Returns
bool|null|WP_Error True on success, false is $plugins is empty, WP_Error on failure. Null if filesystem credentials are required to proceed.
Fires immediately before a plugin deletion attempt.
Since
4.4.0
Parameters
string $plugin_file Plugin file name.
Fires immediately after a plugin deletion attempt.
Since
4.4.0
Parameters
string $plugin_file Plugin file name.
bool $deleted Whether the plugin deletion was successful.
Definition at line 761 of file wp-admin/includes/plugin.php.
References $errors, $plugin, $plugins, $translations, $url, __, ABSPATH, do_action(), exit, get_site_transient(), is_uninstallable_plugin(), is_wp_error(), request_filesystem_credentials(), set_site_transient(), trailingslashit(), uninstall_plugin(), WP_Filesystem(), wp_get_installed_translations(), and wp_nonce_url().
get_admin_page_parent ($parent = '')
string $parent_file array $menu array $submenu string $pagenow string $typenow string $plugin_page array $_wp_real_parent_file array $_wp_menu_nopriv array $_wp_submenu_nopriv
Definition at line 1492 of file wp-admin/includes/plugin.php.
References $_wp_menu_nopriv, $_wp_real_parent_file, $_wp_submenu_nopriv, $menu, $pagenow, $parent_file, $plugin_page, $submenu, $typenow, and elseif.
Referenced by get_admin_page_title(), get_plugin_page_hookname(), and user_can_access_admin_page().
get_admin_page_title ()
string $title array $menu array $submenu string $pagenow string $plugin_page string $typenow
Definition at line 1557 of file wp-admin/includes/plugin.php.
References $menu, $pagenow, $plugin_page, $submenu, $title, $typenow, elseif, get_admin_page_parent(), and get_plugin_page_hook().
get_dropins ()
Check the wp-content directory and retrieve all drop-ins with any plugin data.
Since
3.0.0
Returns
array Key is the file path and the value is an array of the plugin data.
Definition at line 364 of file wp-admin/includes/plugin.php.
References $file, $plugin_files, _get_dropins(), get_plugin_data(), and WP_CONTENT_DIR.
Referenced by WP_Plugins_List_Table\prepare_items().
get_mu_plugins ()
Check the mu-plugins directory and retrieve all mu-plugin files with any plugin data.
WordPress only includes mu-plugin files in the base mu-plugins directory (wp-content/mu-plugins).
Since
3.0.0
Returns
array Key is the mu-plugin file path and the value is an array of the mu-plugin data.
Definition at line 307 of file wp-admin/includes/plugin.php.
References $file, $plugin_files, and get_plugin_data().
Referenced by WP_Plugins_List_Table\prepare_items().
get_plugin_data ($plugin_file, $markup = true, $translate = true)
Parses the plugin contents to retrieve plugin's metadata.
The metadata of the plugin's data searches for the following in the plugin's header. All plugin data must be on its own line. For plugin description, it must not have any newlines or only parts of the description will be displayed and the same goes for the plugin data. The below is formatted for printing.
/*
Plugin Name: Name of Plugin
Plugin URI: Link to plugin information
Description: Plugin Description
Author: Plugin author's name
Author URI: Link to the author's web site
Version: Must be set in the plugin for WordPress 2.3+
Text Domain: Optional. Unique identifier, should be same as the one used in
    load_plugin_textdomain()
Domain Path: Optional. Only useful if the translations are located in a
    folder above the plugin's base path. For example, if .mo files are
    located in the locale folder then Domain Path will be "/locale/" and
    must have the first slash. Defaults to the base folder the plugin is
    located in.
Network: Optional. Specify "Network: true" to require that a plugin is activated
    across all sites in an installation. This will prevent a plugin from being
    activated on a single site when Multisite is enabled.
 * / # Remove the space to close comment
Some users have issues with opening large files and manipulating the contents for want is usually the first 1kiB or 2kiB. This function stops pulling in the plugin contents when it has all of the required plugin data.
The first 8kiB of the file will be pulled in and if the plugin data is not within that first 8kiB, then the plugin author should correct their plugin and move the plugin data headers to the top.
The plugin file is assumed to have permissions to allow for scripts to read the file. This is not checked however and the file is only opened for reading.
Since
1.5.0
Parameters
string $plugin_file Path to the plugin file
bool $markup Optional. If the returned data should have HTML markup applied. Default true.
bool $translate Optional. If the returned data should be translated. Default true.
Returns
array { Plugin data. Values will be empty if not supplied by the plugin.
string $Name Name of the plugin. Should be unique. string $Title Title of the plugin and link to the plugin's site (if set). string $Description Plugin description. string $Author Author's name. string $AuthorURI Author's website address (if set). string $Version Plugin version. string $TextDomain Plugin textdomain. string $DomainPath Plugins relative directory path to .mo files. bool $Network Whether the plugin can only be activated network-wide. }
Definition at line 68 of file wp-admin/includes/plugin.php.
References __, _deprecated_argument(), _get_plugin_data_markup_translate(), and get_file_data().
Referenced by Plugin_Upgrader\bulk_upgrade(), Plugin_Upgrader\check_package(), get_dropins(), get_mu_plugins(), get_plugins(), GravityView_Support_Port\get_related_plugins_and_extensions(), is_network_only_plugin(), GFAutoUpgrade\premium_update(), GFForms\premium_update(), GFAutoUpgrade\premium_update_push(), GFForms\premium_update_push(), WP_Automatic_Updater\update(), and wp_ajax_update_plugin().
get_plugin_files ($plugin)
Get a list of a plugin's files.
Since
2.8.0
Parameters
string $plugin Plugin ID
Returns
array List of files relative to the plugin root.
Definition at line 185 of file wp-admin/includes/plugin.php.
References $dir, $file, $plugin, $plugin_files, and plugin_basename().
get_plugin_page_hook ($plugin_page, $parent_page)
Since
2.3.0
Parameters
string $plugin_page
string $parent_page
Returns
string|null
Definition at line 1635 of file wp-admin/includes/plugin.php.
References $plugin_page, get_plugin_page_hookname(), has_action(), and null.
Referenced by get_admin_page_title().
get_plugin_page_hookname ($plugin_page, $parent_page)
array $admin_page_hooks
Parameters
string $plugin_page
string $parent_page
Definition at line 1649 of file wp-admin/includes/plugin.php.
References $plugin_page, elseif, and get_admin_page_parent().
Referenced by add_menu_page(), add_submenu_page(), get_plugin_page_hook(), and user_can_access_admin_page().
get_plugins ($plugin_folder = '')
Check the plugins directory and retrieve all plugin files with plugin data.
WordPress only supports plugin files in the base plugins directory (wp-content/plugins) and in one directory above the plugins directory (wp-content/plugins/my-plugin). The file it looks for has the plugin data and must be found in those two locations. It is recommended to keep your plugin files in their own directories.
The file with the plugin data is the file that will be included and therefore needs to have the main execution for the plugin. This does not mean everything must be contained in the file and it is recommended that the file be split for maintainability. Keep everything in one file for extreme optimization purposes.
Since
1.5.0
Parameters
string $plugin_folder Optional. Relative path to single plugin folder.
Returns
array Key is the plugin file path and the value is an array of the plugin data.
Definition at line 237 of file wp-admin/includes/plugin.php.
References $file, $plugin_files, get_plugin_data(), plugin_basename(), wp_cache_get(), and wp_cache_set().
Referenced by GFForms\addons_page(), Language_Pack_Upgrader\get_name_for_update(), get_plugin_updates(), install_plugin_install_status(), Plugin_Upgrader\plugin_info(), WP_Plugins_List_Table\prepare_items(), validate_plugin(), wp_ajax_update_plugin(), and wp_update_plugins().
is_network_only_plugin ($plugin)
Checks for "Network: true" in the plugin header to see if this should be activated only as a network wide plugin.
The plugin would also work when Multisite is not enabled.
Checks for "Site Wide Only: true" for backwards compatibility.
Since
3.0.0
Parameters
string $plugin Plugin to check
Returns
bool True if plugin is network only, false otherwise.
Definition at line 487 of file wp-admin/includes/plugin.php.
References $plugin, and get_plugin_data().
Referenced by activate_plugin(), is_wpmu_sitewide_plugin(), WP_Plugins_List_Table\prepare_items(), and WP_Plugins_List_Table\single_row().
is_plugin_active ($plugin)
Check whether the plugin is active by checking the active_plugins list.
Since
2.5.0
Parameters
string $plugin Base plugin path from plugins directory.
Returns
bool True, if in the active plugins list. False, not in the list.
Definition at line 437 of file wp-admin/includes/plugin.php.
References $plugin, get_option(), and is_plugin_active_for_network().
Referenced by Plugin_Upgrader_Skin\__construct(), GFForms\addons_page(), Plugin_Upgrader\bulk_upgrade(), Plugin_Upgrader\deactivate_plugin_before_upgrade(), deactivate_plugins(), GravityView_Compatibility\get_plugin_status(), is_plugin_inactive(), WP_Plugins_List_Table\prepare_items(), WP_Plugins_List_Table\single_row(), and wp_plugin_update_row().
is_plugin_active_for_network ($plugin)
Check whether the plugin is active for the entire network.
Since
3.0.0
Parameters
string $plugin Base plugin path from plugins directory.
Returns
bool True, if active for the network, otherwise false.
Definition at line 464 of file wp-admin/includes/plugin.php.
References $plugin, $plugins, get_site_option(), and is_multisite().
Referenced by Plugin_Upgrader_Skin\__construct(), deactivate_plugins(), GravityView_Compatibility\get_plugin_status(), GravityView_Plugin\is_network_activated(), is_plugin_active(), WP_Plugins_List_Table\prepare_items(), WP_Plugins_List_Table\single_row(), and wp_plugin_update_row().
is_plugin_inactive ($plugin)
Check whether the plugin is inactive.
Reverse of is_plugin_active(). Used as a callback.
Since
3.1.0
See also
is_plugin_active()
Parameters
string $plugin Base plugin path from plugins directory.
Returns
bool True if inactive. False if active.
Definition at line 452 of file wp-admin/includes/plugin.php.
References $plugin, and is_plugin_active().
is_uninstallable_plugin ($plugin)
Whether the plugin can be uninstalled.
Since
2.7.0
Parameters
string $plugin Plugin path to check.
Returns
bool Whether plugin can be uninstalled.
Definition at line 953 of file wp-admin/includes/plugin.php.
References $file, $plugin, get_option(), and plugin_basename().
Referenced by delete_plugins().
menu_page_url ($menu_slug, $echo = true)
Get the url to access a particular menu page based on the slug it was registered with.
If the slug hasn't been registered properly no url will be returned
Since
3.0.0
array $_parent_pages
Parameters
string $menu_slug The slug name to refer to this menu by (should be unique for this menu)
bool $echo Whether or not to echo the url - default is true
Returns
string the url
Definition at line 1455 of file wp-admin/includes/plugin.php.
References $url, add_query_arg(), admin_url(), and esc_url.
option_update_filter ($options)
Refreshes the value of the options whitelist available via the 'whitelist_options' filter.
Since
2.7.0
array $new_whitelist_options
Parameters
array $options
Returns
array
Definition at line 1821 of file wp-admin/includes/plugin.php.
References $options, and add_option_whitelist().
plugin_sandbox_scrape ($plugin)
Parameters
string $plugin
Definition at line 1922 of file wp-admin/includes/plugin.php.
References $plugin, and wp_register_plugin_realpath().
register_setting ($option_group, $option_name, $sanitize_callback = '')
Register a setting and its sanitization callback.
Since
2.7.0
array $new_whitelist_options
Parameters
string $option_group A settings group name. Should correspond to a whitelisted option key name. Default whitelisted option key names include "general," "discussion," and "reading," among others.
string $option_name The name of an option to sanitize and save.
callable $sanitize_callback A callback function that sanitizes the option's value.
Definition at line 1762 of file wp-admin/includes/plugin.php.
References __, _deprecated_argument(), and add_filter().
Referenced by add_option_update_handler(), and twentyeleven_theme_options_init().
remove_menu_page ($menu_slug)
Remove a top-level admin menu.
Since
3.1.0
array $menu
Parameters
string $menu_slug The slug of the menu.
Returns
array|bool The removed menu on success, false if not found.
Definition at line 1402 of file wp-admin/includes/plugin.php.
References $i, and $menu.
remove_option_whitelist ($del_options, $options = '')
Removes a list of options from the options whitelist.
Since
2.7.0
array $whitelist_options
Parameters
array $del_options
string | array $options
Returns
array
Definition at line 1874 of file wp-admin/includes/plugin.php.
References $keys, $options, $page, and $whitelist_options.
remove_submenu_page ($menu_slug, $submenu_slug)
Remove an admin submenu.
Since
3.1.0
array $submenu
Parameters
string $menu_slug The slug for the parent menu.
string $submenu_slug The slug of the submenu.
Returns
array|bool The removed submenu on success, false if not found.
Definition at line 1426 of file wp-admin/includes/plugin.php.
References $i, and $submenu.
Referenced by GravityView_Welcome\admin_head().
settings_fields ($option_group)
Output nonce, action, and option_page fields for a settings page.
Since
2.7.0
Parameters
string $option_group A settings group name. This should match the group name used in register_setting().
Definition at line 1900 of file wp-admin/includes/plugin.php.
References esc_attr(), and wp_nonce_field().
Referenced by twentyeleven_theme_options_render_page().
uninstall_plugin ($plugin)
Uninstall a single plugin.
Calls the uninstall hook, if it is available.
Since
2.7.0
Parameters
string $plugin Relative plugin path from Plugin Directory.
Returns
true True if a plugin's uninstall.php file has been found and included.
Fires in uninstall_plugin() before the plugin is uninstalled.
Since
4.5.0
Parameters
string $plugin Relative plugin path from plugin directory.
array $uninstallable_plugins Uninstallable plugins.
Fires in uninstall_plugin() once the plugin has been uninstalled.
The action concatenates the 'uninstall_' prefix with the basename of the plugin passed to {
See also
uninstall_plugin()} to create a dynamically-named action.
Since
2.7.0
Definition at line 973 of file wp-admin/includes/plugin.php.
References $file, $plugin, add_action(), do_action(), get_option(), plugin_basename(), update_option(), and wp_register_plugin_realpath().
Referenced by delete_plugins().
unregister_setting ($option_group, $option_name, $sanitize_callback = '')
Unregister a setting.
Since
2.7.0
array $new_whitelist_options
Parameters
string $option_group
string $option_name
callable $sanitize_callback
Definition at line 1791 of file wp-admin/includes/plugin.php.
References __, _deprecated_argument(), and remove_filter().
Referenced by remove_option_update_handler().
user_can_access_admin_page ()
string $pagenow array $menu array $submenu array $_wp_menu_nopriv array $_wp_submenu_nopriv string $plugin_page array $_registered_pages
Definition at line 1680 of file wp-admin/includes/plugin.php.
References $_wp_menu_nopriv, $_wp_submenu_nopriv, $menu, $pagenow, $plugin_page, $submenu, current_user_can(), elseif, get_admin_page_parent(), and get_plugin_page_hookname().
validate_active_plugins ()
Validate active plugins.
Validate all active plugins, deactivates invalid and returns an array of deactivated ones.
Since
2.5.0
Returns
array invalid plugins, plugin as key, error as value
Definition at line 894 of file wp-admin/includes/plugin.php.
References $invalid, $plugin, $plugins, current_user_can(), deactivate_plugins(), get_option(), get_site_option(), is_multisite(), is_wp_error(), update_option(), and validate_plugin().
validate_plugin ($plugin)
Validate the plugin path.
Checks that the file exists and is valid file.
Since
2.5.0
Parameters
string $plugin Plugin Path
Returns
WP_Error|int 0 on success, WP_Error on failure.
Definition at line 933 of file wp-admin/includes/plugin.php.
References $plugin, __, get_plugins(), and validate_file().
Referenced by activate_plugin(), and validate_active_plugins().
wp_clean_plugins_cache ($clear_update_cache = true)
Clears the Plugins cache used by get_plugins() and by default, the Plugin Update cache.
Since
3.7.0
Parameters
bool $clear_update_cache Whether to clear the Plugin updates cache
Definition at line 1913 of file wp-admin/includes/plugin.php.
References delete_site_transient(), and wp_cache_delete().
Referenced by Plugin_Upgrader\bulk_upgrade(), Plugin_Upgrader\install(), WP_Automatic_Updater\run(), Plugin_Upgrader\upgrade(), and wp_clean_update_cache().