GravityView: widgets.php File Reference
wp-admin/widgets.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$errors
foreach($wp_registered_sidebars as $sidebar=> $registered_sidebar) $i = $split = 0
if(isset($_POST['savewidget'])||isset($_POST['removewidget'])) if(isset($_POST['removeinactivewidgets'])) if(isset($_GET['editwidget'])&&$_GET['editwidget']) $messages
$parent_file = 'themes.php'
$sidebars_count = count($theme_sidebars)
if(!current_theme_supports('widgets')) $sidebars_widgets = wp_get_sidebars_widgets()
$single_sidebar_class = ''
$theme_sidebars = array()
$title = __('Widgets')
if(!current_user_can('edit_theme_options')) $widgets_access = get_user_setting('widgets_access')
WordPress Administration Bootstrap.
if(isset($_GET['widgets-access'])) if('on'==$widgets_access) else
s not required</p >< p > Enabling Accessibility Mode
s not required</p >< p > Enabling Accessibility via Screen Options
Variable Documentation
$errors
Initial value:
= array(
    __('Error while saving.'),
    __('Error in displaying the widget settings form.')
)
Definition at line 339 of file wp-admin/widgets.php.
Referenced by _default_wp_die_handler(), WP_oEmbed\_parse_xml(), activate_plugins(), delete_plugins(), edit_user(), WP_Upgrader_Skin\error(), WP_REST_Server\error_to_response(), WP_UnitTestCase\expectedDeprecated(), GravityView_API\field_value(), get_attachment_fields_to_edit(), get_confirmation_ui_settings(), GravityView_Logging\get_errors(), get_media_items(), GravityView_Logging\log_error(), media_upload_form(), media_upload_form_handler(), media_upload_gallery(), media_upload_library(), media_upload_type_form(), network_step1(), network_step2(), populate_network(), register_new_user(), send_confirmation_on_profile_email(), WP_Automatic_Updater\send_email(), wpdb\show_errors(), wpdb\suppress_errors(), RGXML\unserialize(), wp_ajax_save_attachment_compat(), wp_media_upload_handler(), wpmu_validate_blog_signup(), and wpmu_validate_user_signup().
foreach ($wp_registered_sidebars as $sidebar=> $registered_sidebar) $i = $split = 0
Definition at line 445 of file wp-admin/widgets.php.
if (isset($_POST['savewidget'])||isset($_POST['removewidget'])) if (isset($_POST['removeinactivewidgets'])) if (isset($_GET['editwidget'])&&$_GET['editwidget']) $messages
Initial value:
= array(
    __('Changes saved.')
)
Definition at line 335 of file wp-admin/widgets.php.
$parent_file = 'themes.php'
Definition at line 47 of file wp-admin/widgets.php.
$sidebars_count = count($theme_sidebars)
Definition at line 447 of file wp-admin/widgets.php.
if (!current_theme_supports('widgets')) $sidebars_widgets = wp_get_sidebars_widgets()
Definition at line 83 of file wp-admin/widgets.php.
Referenced by _wp_sidebars_changed(), WP_Customize_Widgets\customize_register(), dynamic_sidebar(), WP_Customize_Widgets\filter_option_sidebars_widgets_for_theme_switch(), is_active_sidebar(), is_active_widget(), is_dynamic_sidebar(), WP_Customize_Widgets\override_sidebars_widgets_for_theme_switch(), WP_Customize_Widgets\preview_sidebars_widgets(), retrieve_widgets(), switch_theme(), upgrade_330(), wp_ajax_delete_inactive_widgets(), wp_convert_widget_settings(), wp_get_sidebars_widgets(), wp_set_sidebars_widgets(), and wp_widget_control().
$single_sidebar_class = ''
Definition at line 446 of file wp-admin/widgets.php.
$theme_sidebars = array()
Definition at line 402 of file wp-admin/widgets.php.
$title = __('Widgets')
Definition at line 46 of file wp-admin/widgets.php.
if (!current_user_can('edit_theme_options')) $widgets_access = get_user_setting('widgets_access')
WordPress Administration Bootstrap.
WordPress Administration Widgets API
Definition at line 23 of file wp-admin/widgets.php.
if ($sidebars_count > 1) else
Initial value:
{
    wp_enqueue_script('admin-widgets')
Definition at line 31 of file wp-admin/widgets.php.
s not required</p><p> Enabling Accessibility Mode
Definition at line 62 of file wp-admin/widgets.php.
s not required</p><p> Enabling Accessibility via Screen Options
Definition at line 62 of file wp-admin/widgets.php.