GravityView: template.php File Reference
wp-admin/includes/template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_admin_search_query ()
Display the search query.
_draft_or_post_title ($post=0)
Get the post title.
_list_meta_row ($entry, &$count)
Outputs a single row of public meta data in the Custom Fields meta box.
_local_storage_notice ()
Output the HTML for restoring the post data from DOM storage.
_media_states ($post)
_post_states ($post)
_wp_admin_html_begin ()
bool $is_IE
_wp_posts_page_notice ()
Output a notice when editing the page for posts (internal use only).
add_meta_box ($id, $title, $callback, $screen=null, $context= 'advanced', $priority= 'default', $callback_args=null)
Adds a meta box to one or more screens.
add_settings_error ($setting, $code, $message, $type= 'error')
Register a settings error to be displayed to the user.
add_settings_field ($id, $title, $callback, $page, $section= 'default', $args=array())
Add a new field to a section of a settings page.
add_settings_section ($id, $title, $callback, $page)
Add a new section to a settings page.
compression_test ()
Test support for compressing JavaScript from PHP.
convert_to_screen ($hook_name)
Convert a screen string to a screen object.
do_accordion_sections ($screen, $context, $object)
Meta Box Accordion Template Function.
do_meta_boxes ($screen, $context, $object)
Meta-Box template function.
do_settings_fields ($page, $section)
Print out the settings fields for a particular settings section.
do_settings_sections ($page)
Prints out all settings sections added to a particular settings page.
find_posts_div ($found_action= '')
Outputs the modal window used for attaching media to posts or pages in the media-listing screen.
get_inline_data ($post)
Adds hidden fields with the data for use in the inline editor for posts and pages.
get_settings_errors ($setting= '', $sanitize=false)
Fetch settings errors registered by add_settings_error()
get_submit_button ($text= '', $type= 'primary large', $name= 'submit', $wrap=true, $other_attributes= '')
Returns a submit button, with provided text and appropriate class.
iframe_footer ()
Generic Iframe footer for use with Thickbox.
iframe_header ($title= '', $deprecated=false)
Generic Iframe header for use with Thickbox.
list_meta ($meta)
Outputs a post's public meta data in the Custom Fields meta box.
meta_form ($post=null)
Prints the form in the Custom Fields meta box.
page_template_dropdown ($default= '')
Print out option HTML elements for the page templates drop-down.
parent_dropdown ($default=0, $parent=0, $level=0, $post=null)
Print out option HTML elements for the page parents drop-down.
remove_meta_box ($id, $screen, $context)
Removes a meta box from one or more screens.
settings_errors ($setting= '', $sanitize=false, $hide_on_update=false)
Display settings errors registered by {.
submit_button ($text=null, $type= 'primary', $name= 'submit', $wrap=true, $other_attributes=null)
Echoes a submit button, with provided text and appropriate class(es).
the_post_password ()
Display the post password.
touch_time ($edit=1, $for_post=1, $tab_index=0, $multi=0)
Print out HTML form date elements for editing post or comment publish date.
wp_category_checklist ($post_id=0, $descendants_and_self=0, $selected_cats=false, $popular_cats=false, $walker=null, $checked_ontop=true)
Walker_Category_Checklist class.
wp_comment_reply ($position=1, $checkbox=false, $mode= 'single', $table_row=true)
Outputs the in-line comment reply-to form in the Comments list table.
wp_comment_trashnotice ()
Output 'undo move to trash' text for comments.
wp_dropdown_roles ($selected= '')
Print out option html elements for role selectors.
wp_import_upload_form ($action)
Outputs the form used by the importers to accept the data to be imported.
wp_link_category_checklist ($link_id=0)
Outputs a link category checklist element.
wp_popular_terms_checklist ($taxonomy, $default=0, $number=10, $echo=true)
Retrieve a list of the most popular terms from the specified taxonomy.
wp_star_rating ($args=array())
Output a HTML element with a star rating for a given rating.
wp_terms_checklist ($post_id=0, $args=array())
Output an unordered list of checkbox input elements labelled with term names.
Function Documentation
_admin_search_query ()
Display the search query.
A simple wrapper to display the "s" parameter in a GET URI. This function should only be used when the_search_query() cannot.
Since
2.7.0
Definition at line 1552 of file wp-admin/includes/template.php.
References esc_attr(), and wp_unslash().
_draft_or_post_title ($post = 0)
Get the post title.
The post title is fetched and if it is blank then a default string is returned.
Since
2.7.0
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
string The post title if set.
Definition at line 1537 of file wp-admin/includes/template.php.
References $post, $title, __, esc_html, and get_the_title().
Referenced by _wp_dashboard_recent_comments_row(), WP_Media_List_Table\column_cb(), WP_Posts_List_Table\column_cb(), WP_Media_List_Table\column_parent(), WP_Media_List_Table\column_title(), WP_Posts_List_Table\column_title(), WP_Posts_List_Table\handle_row_actions(), and wp_dashboard_recent_drafts().
_list_meta_row ($entry, & $count)
Outputs a single row of public meta data in the Custom Fields meta box.
Since
2.5.0
string $update_nonce
Parameters
array $entry
int $count
Returns
string
Definition at line 527 of file wp-admin/includes/template.php.
References $count, __, esc_attr(), esc_textarea(), get_submit_button(), is_protected_meta(), is_serialized(), is_serialized_string(), maybe_unserialize(), and wp_nonce_field().
Referenced by list_meta(), and wp_ajax_add_meta().
_local_storage_notice ()
Output the HTML for restoring the post data from DOM storage.
Since
3.6.0 private
Definition at line 1989 of file wp-admin/includes/template.php.
References _e.
_media_states ($post)
Parameters
WP_Post $post
Filter the default media display states for items in the Media list table.
Since
3.2.0
Parameters
array $media_states An array of media states. Default 'Header Image', 'Background Image', 'Site Icon'.
Definition at line 1731 of file wp-admin/includes/template.php.
References $i, $post, __, apply_filters(), current_theme_supports(), get_option(), and get_post_meta().
Referenced by WP_Media_List_Table\column_title().
_post_states ($post)
Parameters
WP_Post $post
Filter the default post display states used in the posts list table.
Since
2.8.0
Parameters
array $post_states An array of post display states.
WP_Post $post The current post object.
Definition at line 1672 of file wp-admin/includes/template.php.
References $i, $post, __, _x, apply_filters(), get_option(), and is_sticky().
Referenced by WP_Posts_List_Table\column_title().
_wp_admin_html_begin ()
bool $is_IE
Fires inside the HTML tag in the admin header.
Since
2.2.0
This action is documented in wp-admin/includes/template.php
Definition at line 1935 of file wp-admin/includes/template.php.
References $is_IE, do_action(), endif, is_admin_bar_showing(), and language_attributes().
Referenced by iframe_header(), and wp_iframe().
_wp_posts_page_notice ()
Output a notice when editing the page for posts (internal use only).
Since
4.2.0
Definition at line 2077 of file wp-admin/includes/template.php.
References __.
add_meta_box ($id, $title, $callback, $screen = null, $context = 'advanced', $priority = 'default', $callback_args = null)
Adds a meta box to one or more screens.
Since
2.5.0
4.4.0 The $screen parameter now accepts an array of screen IDs.
array $wp_meta_boxes
Parameters
string $id Meta box ID (used in the 'id' attribute for the meta box).
string $title Title of the meta box.
callable $callback Function that fills the box with the desired content. The function should echo its output.
string | array | WP_Screen $screen Optional. The screen or screens on which to show the box (such as a post type, 'link', or 'comment'). Accepts a single screen ID, WP_Screen object, or array of screen IDs. Default is the current screen.
string $context Optional. The context within the screen where the boxes should display. Available contexts vary from screen to screen. Post edit screen contexts include 'normal', 'side', and 'advanced'. Comments screen contexts include 'normal' and 'side'. Menus meta boxes (accordion sections) all use the 'side' context. Global default is 'advanced'.
string $priority Optional. The priority within the context where the boxes should show ('high', 'low'). Default 'default'.
array $callback_args Optional. Data that should be set as the $args property of the box array (which is the second parameter passed to your callback). Default null.
Definition at line 903 of file wp-admin/includes/template.php.
References $id, $page, $screen, $title, convert_to_screen(), elseif, and get_current_screen().
Referenced by GravityView_Extension\add_metabox_tab(), do_meta_boxes(), GravityView_Admin_Metaboxes\register_metaboxes(), wp_add_dashboard_widget(), wp_nav_menu_post_type_meta_boxes(), wp_nav_menu_setup(), and wp_nav_menu_taxonomy_meta_boxes().
add_settings_error ($setting, $code, $message, $type = 'error')
Register a settings error to be displayed to the user.
Part of the Settings API. Use this to show messages to users about settings validation problems, missing settings or anything else.
Settings errors should be added inside the $sanitize_callback function defined in register_setting() for a given setting to give feedback about the submission.
By default messages will show immediately after the submission that generated the error. Additional calls to settings_errors() can be used to show errors even when the settings page is first accessed.
Since
3.0.0
array $wp_settings_errors Storage array of errors registered during this pageload
Parameters
string $setting Slug title of the setting to which this error applies
string $code Slug-name to identify the error. Used as part of 'id' attribute in HTML output.
string $message The formatted message text to display to the user (will be shown inside styled <div> and <p> tags).
string $type Optional. Message type, controls HTML class. Accepts 'error' or 'updated'. Default 'error'.
Definition at line 1361 of file wp-admin/includes/template.php.
References $message.
Referenced by sanitize_option().
add_settings_field ($id, $title, $callback, $page, $section = 'default', $args = array())
Add a new field to a section of a settings page.
Part of the Settings API. Use this to define a settings field that will show as part of a settings section inside a settings page. The fields are shown using do_settings_fields() in do_settings-sections()
The $callback argument should be the name of a function that echoes out the html input tags for this setting field. Use get_option() to retrieve existing values to show.
Since
2.7.0
4.2.0 The $class argument was added.
$wp_settings_fields Storage array of settings fields and info about their pages/sections
Parameters
string $id Slug-name to identify the field. Used in the 'id' attribute of tags.
string $title Formatted title of the field. Shown as the label for the field during output.
string $callback Function that fills the field with the desired form inputs. The function should echo its output.
string $page The slug-name of the settings page on which to show the section (general, reading, writing, ...).
string $section Optional. The slug-name of the section of the settings page in which to show the box. Default 'default'.
array $args { Optional. Extra arguments used when outputting the field.
string $label_for When supplied, the setting title will be wrapped in a <label> element, its for attribute populated with this value. string $class CSS Class to be added to the <tr> element when the field is output. }
Definition at line 1245 of file wp-admin/includes/template.php.
References $id, $page, $title, __, and _deprecated_argument().
Referenced by twentyeleven_theme_options_init().
add_settings_section ($id, $title, $callback, $page)
Add a new section to a settings page.
Part of the Settings API. Use this to define new settings sections for an admin page. Show settings sections in your admin page callback function with do_settings_sections(). Add settings fields to your section with add_settings_field()
The $callback argument should be the name of a function that echoes out any content you want to show at the top of the settings section before the actual fields. It can output nothing if you want.
Since
2.7.0
$wp_settings_sections Storage array of all settings sections added to admin pages
Parameters
string $id Slug-name to identify the section. Used in the 'id' attribute of tags.
string $title Formatted title of the section. Shown as the heading for the section.
string $callback Function that echos out any content at the top of the section (between heading and fields).
string $page The slug-name of the settings page on which to show the section. Built-in pages include 'general', 'reading', 'writing', 'discussion', 'media', etc. Create your own using add_options_page();
Definition at line 1194 of file wp-admin/includes/template.php.
References $id, $page, $title, __, and _deprecated_argument().
Referenced by twentyeleven_theme_options_init().
compression_test ()
Test support for compressing JavaScript from PHP.
Outputs JavaScript that tests if compression from PHP works as expected and sets an option with the result. Has no effect when the current user is not an administrator. To run the test again the option 'can_compress_scripts' has to be deleted.
Since
2.8.0
Definition at line 1783 of file wp-admin/includes/template.php.
convert_to_screen ($hook_name)
Convert a screen string to a screen object.
Since
3.0.0
Parameters
string $hook_name The hook name (also known as the hook suffix) used to determine the screen.
Returns
WP_Screen Screen object.
Definition at line 1974 of file wp-admin/includes/template.php.
References __, _doing_it_wrong(), and WP_Screen\get().
Referenced by _WP_List_Table_Compat\__construct(), WP_List_Table\__construct(), _get_list_table(), add_contextual_help(), add_meta_box(), do_accordion_sections(), do_meta_boxes(), get_column_headers(), get_hidden_columns(), get_hidden_meta_boxes(), meta_box_prefs(), and remove_meta_box().
do_accordion_sections ($screen, $context, $object)
Meta Box Accordion Template Function.
Largely made up of abstracted code from do_meta_boxes(), this function serves to build meta boxes as list items for display as a collapsible accordion.
Since
3.6.0
global $wp_meta_boxes Used to retrieve registered meta boxes.
Parameters
string | object $screen The screen identifier.
string $context The meta box context.
mixed $object gets passed to the section callback function as first parameter.
Returns
int number of meta boxes as accordion sections.
Definition at line 1116 of file wp-admin/includes/template.php.
References $i, $page, $screen, _e, convert_to_screen(), elseif, esc_html, get_current_screen(), get_hidden_meta_boxes(), li, and wp_enqueue_script().
do_meta_boxes ($screen, $context, $object)
Meta-Box template function.
Since
2.5.0
array $wp_meta_boxes
bool $already_sorted
Parameters
string | WP_Screen $screen Screen identifier
string $context box context
mixed $object gets passed to the box callback function as first parameter
Returns
int number of meta_boxes
Definition at line 990 of file wp-admin/includes/template.php.
References $i, $id, $page, $screen, __, add_meta_box(), convert_to_screen(), elseif, get_current_screen(), get_hidden_meta_boxes(), get_user_option(), null, and postbox_classes().
Referenced by wp_dashboard().
do_settings_fields ($page, $section)
Print out the settings fields for a particular settings section.
Part of the Settings API. Use this in a settings page to output a specific section. Should normally be called by do_settings_sections() rather than directly.
$wp_settings_fields Storage array of settings fields and their pages/sections
Since
2.7.0
Parameters
string $page Slug title of the admin page who's settings fields you want to show.
string $section Slug title of the settings section who's fields you want to show.
Definition at line 1309 of file wp-admin/includes/template.php.
References $class, $field, $page, and esc_attr().
Referenced by do_settings_sections().
do_settings_sections ($page)
Prints out all settings sections added to a particular settings page.
Part of the Settings API. Use this in a settings page callback function to output all the sections and fields that were added to that $page with add_settings_section() and add_settings_field()
$wp_settings_sections Storage array of all settings sections added to admin pages $wp_settings_fields Storage array of settings fields and info about their pages/sections
Since
2.7.0
Parameters
string $page The slug name of the page whose settings sections you want to output
Definition at line 1274 of file wp-admin/includes/template.php.
References $page, and do_settings_fields().
Referenced by twentyeleven_theme_options_render_page().
find_posts_div ($found_action = '')
Outputs the modal window used for attaching media to posts or pages in the media-listing screen.
Since
2.7.0
Parameters
string $found_action
Definition at line 1482 of file wp-admin/includes/template.php.
References __, _e, input, label, name, submit_button(), and wp_nonce_field().
get_inline_data ($post)
Adds hidden fields with the data for use in the inline editor for posts and pages.
Since
2.7.0
Parameters
WP_Post $post Post object.
This filter is documented in wp-admin/edit-tag-form.php
This filter is documented in wp-admin/edit-tag-form.php
Definition at line 271 of file wp-admin/includes/template.php.
References $post, $post_type_object, $title, apply_filters(), current_user_can(), elseif, esc_html, esc_textarea(), get_object_taxonomies(), get_object_term_cache(), get_post_format(), get_post_meta(), get_post_type_object(), get_taxonomy(), get_terms_to_edit(), is_sticky(), mysql2date(), post_type_supports(), str_replace, wp_cache_add(), wp_get_object_terms(), and wp_list_pluck().
Referenced by WP_Posts_List_Table\column_title().
get_settings_errors ($setting = '', $sanitize = false)
Fetch settings errors registered by add_settings_error()
Checks the $wp_settings_errors array for any errors declared during the current pageload and returns them.
If changes were just submitted ($_GET['settings-updated']) and settings errors were saved to the 'settings_errors' transient then those errors will be returned instead. This is used to pass errors back across pageloads.
Use the $sanitize argument to manually re-sanitize the option before returning errors. This is useful if you have errors or notices you want to show even when the user hasn't submitted data (i.e. when they first load an options page, or in admin_notices action hook)
Since
3.0.0
array $wp_settings_errors Storage array of errors registered during this pageload
Parameters
string $setting Optional slug title of a specific setting who's errors you want.
boolean $sanitize Whether to re-sanitize the setting value before returning errors.
Returns
array Array of settings errors
Definition at line 1394 of file wp-admin/includes/template.php.
References $details, delete_transient(), get_option(), get_transient(), and sanitize_option().
Referenced by settings_errors().
get_submit_button ($text = '', $type = 'primary large', $name = 'submit', $wrap = true, $other_attributes = '')
Returns a submit button, with provided text and appropriate class.
Since
3.1.0
Parameters
string $text Optional. The text of the button. Default 'Save Changes'.
string $type Optional. The type of button. Accepts 'primary', 'secondary', or 'delete'. Default 'primary large'.
string $name Optional. The HTML name of the submit button. Defaults to "submit". If no id attribute is given in $other_attributes below, $name will be used as the button's id. Default 'submit'.
bool $wrap Optional. True if the output button should be wrapped in a paragraph tag, false otherwise. Default true.
array | string $other_attributes Optional. Other attributes that should be output with the button, mapping attributes to their values, such as `array('tabindex' => '1'). These attributes will be output asattribute="value", such as tabindex="1". Other attributes can also be provided as a string such astabindex="1"`, though the array format is typically cleaner. Default empty.
Returns
string Submit button HTML.
Definition at line 1883 of file wp-admin/includes/template.php.
References $attributes, $class, $id, $name, $text, $value, __, elseif, and esc_attr().
Referenced by _list_meta_row(), get_media_item(), submit_button(), and wp_media_insert_url_form().
iframe_footer ()
Generic Iframe footer for use with Thickbox.
Since
2.7.0
This action is documented in wp-admin/admin-footer.php
This action is documented in wp-admin/admin-footer.php
Definition at line 1646 of file wp-admin/includes/template.php.
References do_action().
Referenced by install_theme_information().
iframe_header ($title = '', $deprecated = false)
Generic Iframe header for use with Thickbox.
Since
2.7.0
string $hook_suffix string $admin_body_class WP_Locale $wp_locale
Parameters
string $title Optional. Title of the Iframe page. Default empty.
bool $deprecated Not used.
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This action is documented in wp-admin/admin-header.php
This filter is documented in wp-admin/admin-header.php
string $body_id
Definition at line 1568 of file wp-admin/includes/template.php.
References $admin_body_class, $admin_body_classes, $current_screen, $GLOBALS, $hook_suffix, $title, $wp_locale, _e, _wp_admin_html_begin(), apply_filters(), bloginfo(), do_action(), get_current_screen(), get_locale(), get_option(), is_rtl(), sanitize_html_class(), show_admin_bar(), str_replace, and wp_enqueue_style().
Referenced by install_plugin_information(), and install_theme_information().
list_meta ($meta)
Outputs a post's public meta data in the Custom Fields meta box.
Since
1.2.0
Parameters
array $meta
Definition at line 480 of file wp-admin/includes/template.php.
References $count, __, _e, _ex(), _list_meta_row(), and _x.
Referenced by post_custom_meta_box().
meta_form ($post = null)
Prints the form in the Custom Fields meta box.
Since
1.2.0
wpdb $wpdb WordPress database abstraction object.
Parameters
WP_Post $post Optional. The post being edited.
Filter values for the meta key dropdown in the Custom Fields meta box.
Returning a non-null value will effectively short-circuit and avoid a potentially expensive query against postmeta.
Since
4.4.0
Parameters
array | null $keys Pre-defined meta keys to be used in place of a postmeta query. Default null.
WP_Post $post The current post object.
Filter the number of custom fields to retrieve for the drop-down in the Custom Fields meta box.
Since
2.1.0
Parameters
int $limit Number of custom fields to retrieve. Default 30.
Definition at line 580 of file wp-admin/includes/template.php.
References $keys, $post, $wpdb, __, _e, _ex(), apply_filters(), current_user_can(), esc_attr(), esc_html, get_post(), input, is_protected_meta(), label, name, null, submit_button(), textarea, and wp_nonce_field().
Referenced by post_custom_meta_box().
page_template_dropdown ($default = '')
Print out option HTML elements for the page templates drop-down.
Since
1.5.0
Parameters
string $default Optional. The template file name. Default empty.
Definition at line 767 of file wp-admin/includes/template.php.
References $default, $template, $templates, get_page_templates(), get_post(), and selected().
Referenced by WP_Posts_List_Table\inline_edit(), and page_attributes_meta_box().
parent_dropdown ($default = 0, $parent = 0, $level = 0, $post = null)
Print out option HTML elements for the page parents drop-down.
Since
1.5.0
4.4.0 $post argument was added.
wpdb $wpdb WordPress database abstraction object.
Parameters
int $default Optional. The default page ID to be pre-selected. Default 0.
int $parent Optional. The parent page ID. Default 0.
int $level Optional. Page depth level. Default 0.
int | WP_Post $post Post ID or WP_Post object.
Returns
null|false Boolean False if page has no children, otherwise print out html elements
Definition at line 791 of file wp-admin/includes/template.php.
References $default, $post, $wpdb, esc_html, get_post(), and selected().
remove_meta_box ($id, $screen, $context)
Removes a meta box from one or more screens.
Since
2.6.0
4.4.0 The $screen parameter now accepts an array of screen IDs.
array $wp_meta_boxes
Parameters
string $id Meta box ID (used in the 'id' attribute for the meta box).
string | array | WP_Screen $screen The screen or screens on which the meta box is shown (such as a post type, 'link', or 'comment'). Accepts a single screen ID, WP_Screen object, or array of screen IDs.
string $context Optional. The context within the screen where the boxes should display. Available contexts vary from screen to screen. Post edit screen contexts include 'normal', 'side', and 'advanced'. Comments screen contexts include 'normal' and 'side'. Menus meta boxes (accordion sections) all use the 'side' context. Global default is 'advanced'.
Definition at line 1070 of file wp-admin/includes/template.php.
References $id, $page, $screen, convert_to_screen(), elseif, and get_current_screen().
settings_errors ($setting = '', $sanitize = false, $hide_on_update = false)
Display settings errors registered by {.
See also
add_settings_error()}.
Part of the Settings API. Outputs a div for each error retrieved by {
See also
get_settings_errors()}.
This is called automatically after a settings page based on the Settings API is submitted. Errors should be added during the validation callback function for a setting defined in {
See also
register_setting()}
The $sanitize option is passed into {
See also
get_settings_errors()} and will re-run the setting sanitization on its current value.
The $hide_on_update option will cause errors to only show when the settings page is first loaded. if the user has already saved new values it will be hidden to avoid repeating messages already shown in the default error reporting after submission. This is useful to show general errors like missing settings when the user arrives at the settings page.
Since
3.0.0
Parameters
string $setting Optional slug title of a specific setting who's errors you want.
bool $sanitize Whether to re-sanitize the setting value before returning errors.
bool $hide_on_update If set to true errors will not be shown if the settings page has already been submitted.
Definition at line 1454 of file wp-admin/includes/template.php.
References $details, $output, and get_settings_errors().
Referenced by twentyeleven_theme_options_render_page().
submit_button ($text = null, $type = 'primary', $name = 'submit', $wrap = true, $other_attributes = null)
Echoes a submit button, with provided text and appropriate class(es).
Since
3.1.0
See also
get_submit_button()
Parameters
string $text The text of the button (defaults to 'Save Changes')
string $type Optional. The type and CSS class(es) of the button. Core values include 'primary', 'secondary', 'delete'. Default 'primary'
string $name The HTML name of the submit button. Defaults to "submit". If no id attribute is given in $other_attributes below, $name will be used as the button's id.
bool $wrap True if the output button should be wrapped in a paragraph tag, false otherwise. Defaults to true
array | string $other_attributes Other attributes that should be output with the button, mapping attributes to their values, such as setting tabindex to 1, etc. These key/value attribute pairs will be output as attribute="value", where attribute is the key. Other attributes can also be provided as a string such as 'tabindex="1"', though the array format is preferred. Default null.
Definition at line 1858 of file wp-admin/includes/template.php.
References $name, $text, and get_submit_button().
Referenced by _wp_dashboard_control_callback(), attachment_submit_meta_box(), WP_List_Table\bulk_actions(), confirm_delete_users(), display_setup_form(), WP_Links_List_Table\extra_tablenav(), WP_Media_List_Table\extra_tablenav(), WP_Users_List_Table\extra_tablenav(), WP_Comments_List_Table\extra_tablenav(), WP_Posts_List_Table\extra_tablenav(), WP_Plugins_List_Table\extra_tablenav(), find_posts_div(), WP_Posts_List_Table\inline_edit(), install_plugins_upload(), install_search_form(), install_theme_search_form(), install_themes_dashboard(), install_themes_upload(), link_submit_meta_box(), list_core_update(), media_upload_form(), media_upload_library_form(), media_upload_type_form(), meta_form(), network_step1(), post_submit_meta_box(), WP_Screen\render_screen_options(), request_filesystem_credentials(), WP_List_Table\search_box(), Custom_Image_Header\step_1(), Custom_Image_Header\step_2(), twentyeleven_theme_options_render_page(), wp_dashboard_quick_press(), wp_import_upload_form(), wp_nav_menu_item_post_type_meta_box(), wp_nav_menu_item_taxonomy_meta_box(), wp_network_dashboard_right_now(), and wp_widget_control().
the_post_password ()
Display the post password.
The password is passed through esc_attr() to ensure that it is safe for placing in an html attribute.
Since
2.7.0
Definition at line 1520 of file wp-admin/includes/template.php.
References $post, esc_attr(), and get_post().
touch_time ($edit = 1, $for_post = 1, $tab_index = 0, $multi = 0)
Print out HTML form date elements for editing post or comment publish date.
Since
0.71
4.4.0 Converted to use get_comment() instead of the global $comment.
WP_Locale $wp_locale
Parameters
int | bool $edit Accepts 1|true for editing the date, 0|false for adding the date.
int | bool $for_post Accepts 1|true for applying the date to a post, 0|false for a comment.
int $tab_index The tabindex attribute to add. Default 0.
int | bool $multi Optional. Whether the additional fields and buttons should be added. Default 0|false.
Definition at line 684 of file wp-admin/includes/template.php.
References $i, $post, $value, $wp_locale, __, _e, current_time(), get_comment(), get_post(), mysql2date(), selected(), and zeroise().
Referenced by WP_Posts_List_Table\inline_edit(), and post_submit_meta_box().
wp_category_checklist ($post_id = 0, $descendants_and_self = 0, $selected_cats = false, $popular_cats = false, $walker = null, $checked_ontop = true)
Walker_Category_Checklist class.
WP_Internal_Pointers class Output an unordered list of checkbox input elements labeled with category names.
Since
2.5.1
See also
wp_terms_checklist()
Parameters
int $post_id Optional. Post to generate a categories checklist for. Default 0. $selected_cats must not be an array. Default 0.
int $descendants_and_self Optional. ID of the category to output along with its descendants. Default 0.
array $selected_cats Optional. List of categories to mark as checked. Default false.
array $popular_cats Optional. List of categories to receive the "popular-category" class. Default false.
object $walker Optional. Walker object to use to build the output. Default is a Walker_Category_Checklist instance.
bool $checked_ontop Optional. Whether to move checked items out of the hierarchy and to the top of the list. Default true.
Definition at line 40 of file wp-admin/includes/template.php.
References $post_id, and wp_terms_checklist().
Referenced by dropdown_categories().
wp_comment_reply ($position = 1, $checkbox = false, $mode = 'single', $table_row = true)
Outputs the in-line comment reply-to form in the Comments list table.
Since
2.7.0
WP_List_Table $wp_list_table
Parameters
int $position
bool $checkbox
string $mode
bool $table_row
Filter the in-line comment reply-to form output in the Comments list table.
Returning a non-empty value here will short-circuit display of the in-line comment-reply form in the Comments list table, echoing the returned value instead.
Since
2.7.0
See also
wp_comment_reply()
Parameters
string $content The reply-to form content.
array $args An array of default args.
Definition at line 354 of file wp-admin/includes/template.php.
References $content, $mode, $quicktags_settings, $wp_list_table, _e, _get_list_table(), apply_filters(), current_user_can(), endif, input, label, name, size, wp_editor(), and wp_nonce_field().
wp_comment_trashnotice ()
Output 'undo move to trash' text for comments.
Since
2.9.0
Definition at line 462 of file wp-admin/includes/template.php.
References __, and _e.
Referenced by post_comment_meta_box().
wp_dropdown_roles ($selected = '')
Print out option html elements for role selectors.
Since
2.1.0
Parameters
string $selected Slug for the role that should be already selected.
Definition at line 820 of file wp-admin/includes/template.php.
References $details, $name, esc_attr(), get_editable_roles(), and translate_user_role().
Referenced by WP_Users_List_Table\extra_tablenav().
wp_import_upload_form ($action)
Outputs the form used by the importers to accept the data to be imported.
Since
2.0.0
Parameters
string $action The action attribute for the form.
Filter the maximum allowed upload size for import files.
Since
2.3.0
See also
wp_max_upload_size()
Parameters
int $max_upload_size Allowed upload size. Default 1 MB.
Definition at line 843 of file wp-admin/includes/template.php.
References $size, __, _e, apply_filters(), endif, input, label, name, size, size_format(), submit_button(), wp_max_upload_size(), and wp_upload_dir().
wp_link_category_checklist ($link_id = 0)
Outputs a link category checklist element.
Since
2.5.1
Parameters
int $link_id
This filter is documented in wp-includes/category-template.php
Definition at line 234 of file wp-admin/includes/template.php.
References $default, $name, apply_filters(), esc_html, get_terms(), and wp_get_link_cats().
Referenced by dropdown_link_categories(), and link_categories_meta_box().
wp_popular_terms_checklist ($taxonomy, $default = 0, $number = 10, $echo = true)
Retrieve a list of the most popular terms from the specified taxonomy.
If the $echo argument is true then the elements for a list of checkbox <input> elements labelled with the names of the selected terms is output. If the $post_ID global isn't empty then the terms associated with that post will be marked as checked.
Since
2.5.0
Parameters
string $taxonomy Taxonomy to retrieve terms from.
int $default Not used.
int $number Number of terms to retrieve. Defaults to 10.
bool $echo Optionally output the list as well. Defaults to true.
Returns
array List of popular term IDs.
This filter is documented in wp-includes/category-template.php
Definition at line 191 of file wp-admin/includes/template.php.
References $id, $post, $tax, apply_filters(), current_user_can(), disabled(), esc_html, get_post(), get_taxonomy(), get_terms(), input, label, li, and wp_get_object_terms().
Referenced by _wp_ajax_add_hierarchical_term(), link_categories_meta_box(), and post_categories_meta_box().
wp_star_rating ($args = array())
Output a HTML element with a star rating for a given rating.
Outputs a HTML element with the star rating exposed on a 0..5 scale in half star increments (ie. 1, 1.5, 2 stars). Optionally, if specified, the number of ratings may also be displayed by passing the $number parameter.
Since
3.8.0
4.4.0 Introduced the echo parameter.
Parameters
array $args { Optional. Array of star ratings arguments.
int $rating The rating to display, expressed in either a 0.5 rating increment, or percentage. Default 0. string $type Format that the $rating is in. Valid values are 'rating' (default), or, 'percent'. Default 'rating'. int $number The number of ratings that makes up this rating. Default 0. bool $echo Whether to echo the generated markup. False to return the markup instead of echoing it. Default true. }
Definition at line 2026 of file wp-admin/includes/template.php.
References $format, $output, $title, __, _n(), number_format_i18n(), str_replace, and wp_parse_args().
Referenced by WP_Plugin_Install_List_Table\display_rows(), WP_Theme_Install_List_Table\install_theme_info(), and wp_ajax_query_themes().
wp_terms_checklist ($post_id = 0, $args = array())
Output an unordered list of checkbox input elements labelled with term names.
Taxonomy-independent version of wp_category_checklist().
Since
3.0.0
4.4.0 Introduced the $echo argument.
Parameters
int $post_id Optional. Post ID. Default 0.
array | string $args { Optional. Array or string of arguments for generating a terms checklist. Default empty array.
int $descendants_and_self ID of the category to output along with its descendants. Default 0. array $selected_cats List of categories to mark as checked. Default false. array $popular_cats List of categories to receive the "popular-category" class. Default false. object $walker Walker object to use to build the output. Default is a Walker_Category_Checklist instance. string $taxonomy Taxonomy to generate the checklist for. Default 'category'. bool $checked_ontop Whether to move checked items out of the hierarchy and to the top of the list. Default true. bool $echo Whether to echo the generated markup. False to return the markup instead of echoing it. Default true. }
Filter the taxonomy terms checklist arguments.
Since
3.4.0
See also
wp_terms_checklist()
Parameters
array $args An array of arguments.
int $post_id The post ID.
Definition at line 77 of file wp-admin/includes/template.php.
References $keys, $output, $post_id, $self, $tax, apply_filters(), current_user_can(), elseif, get_taxonomy(), get_term(), get_terms(), null, wp_get_object_terms(), and wp_parse_args().
Referenced by _wp_ajax_add_hierarchical_term(), WP_Press_This\categories_html(), WP_Posts_List_Table\inline_edit(), post_categories_meta_box(), and wp_category_checklist().