GravityView: user.php File Reference
wp-admin/includes/user.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
add_user ()
Creates a new user from the "Users" form using $_POST information.
admin_created_user_email ($text)
default_password_nag ()
default_password_nag_edit_user ($user_ID, $old_data)
default_password_nag_handler ($errors=false)
delete_users_add_js ()
edit_user ($user_id=0)
Edit user settings based on contents of $_POST.
get_editable_roles ()
Fetch a filtered list of user roles that the current user is allowed to edit.
get_user_to_edit ($user_id)
Retrieve user data and filter it.
get_users_drafts ($user_id)
Retrieve the user's drafts.
use_ssl_preference ($user)
Optional SSL preference that can be turned on by hooking to the 'personal_options' action.
wp_delete_user ($id, $reassign=null)
Remove user and optionally reassign posts and links to another user.
wp_revoke_user ($id)
Remove all capabilities from user.
Function Documentation
add_user ()
Creates a new user from the "Users" form using $_POST information.
Since
2.0.0
Returns
int|WP_Error WP_Error or User ID.
Definition at line 16 of file wp-admin/includes/user.php.
References edit_user().
admin_created_user_email ($text)
Parameters
string $text
Returns
string
Definition at line 505 of file wp-admin/includes/user.php.
References __, get_bloginfo(), get_editable_roles(), home_url(), translate_user_role(), and wp_specialchars_decode().
default_password_nag ()
Since
2.8.0
string $pagenow
Definition at line 449 of file wp-admin/includes/user.php.
References $pagenow, __, _e, get_edit_profile_url(), and get_user_option().
default_password_nag_edit_user ($user_ID, $old_data)
Since
2.8.0
Parameters
int $user_ID
object $old_data
Definition at line 430 of file wp-admin/includes/user.php.
References $user_ID, delete_user_setting(), get_user_option(), and update_user_option().
default_password_nag_handler ($errors = false)
Since
2.8.0
int $user_ID
Parameters
false $errors Deprecated.
Definition at line 411 of file wp-admin/includes/user.php.
References $user_ID, delete_user_setting(), get_user_option(), get_user_setting(), and update_user_option().
delete_users_add_js ()
Since
3.5.0 private
Definition at line 469 of file wp-admin/includes/user.php.
edit_user ($user_id = 0)
Edit user settings based on contents of $_POST.
Used on user-edit.php and profile.php to manage and process user options, passwords etc.
Since
2.0.0
Parameters
int $user_id Optional. User ID.
Returns
int|WP_Error user id of the updated user
Fires before the password and confirm password fields are checked for congruity.
Since
1.5.1
Parameters
string $user_login The username.
string &$pass1 The password, passed by reference.
string &$pass2 The confirmed password, passed by reference.
This filter is documented in wp-includes/user.php
Fires before user profile update errors are returned.
Since
2.8.0
Parameters
WP_Error &$errors WP_Error object, passed by reference.
bool $update Whether this is a user update.
WP_User &$user WP_User object, passed by reference.
Fires after a new user has been created.
Since
4.4.0
Parameters
int $user_id ID of the newly created user.
string $notify Type of notification that should happen. See {
See also
wp_send_new_user_notifications()} for more information on possible values.
Definition at line 30 of file wp-admin/includes/user.php.
References $errors, $name, $update, $user, $user_id, __, apply_filters(), current_user_can(), do_action(), do_action_ref_array(), elseif, email_exists(), esc_url_raw(), get_current_user_id(), get_editable_roles(), is_email(), is_multisite(), sanitize_text_field(), sanitize_user(), username_exists(), validate_username(), wp_allowed_protocols(), wp_die(), wp_get_user_contact_methods(), wp_insert_user(), wp_roles(), wp_slash(), wp_unslash(), and wp_update_user().
Referenced by add_user(), and wp_ajax_add_user().
get_editable_roles ()
Fetch a filtered list of user roles that the current user is allowed to edit.
Simple function who's main purpose is to allow filtering of the list of roles in the $wp_roles object so that plugins can remove inappropriate ones depending on the situation or user making edits. Specifically because without filtering anyone with the edit_users capability can edit others to be administrators, even if they are only editors or authors. This filter allows admins to delegate user management.
Since
2.8.0
Returns
array
Filter the list of editable roles.
Since
2.8.0
Parameters
array $all_roles List of roles.
Definition at line 211 of file wp-admin/includes/user.php.
References apply_filters(), and wp_roles().
Referenced by admin_created_user_email(), edit_user(), and wp_dropdown_roles().
get_user_to_edit ($user_id)
Retrieve user data and filter it.
Since
2.0.5
Parameters
int $user_id User ID.
Returns
WP_User|bool WP_User object on success, false on failure.
Definition at line 234 of file wp-admin/includes/user.php.
References $user, and $user_id.
get_users_drafts ($user_id)
Retrieve the user's drafts.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $user_id User ID.
Returns
array
Filter the user's drafts query string.
Since
2.0.0
Parameters
string $query The user's drafts query string.
Definition at line 253 of file wp-admin/includes/user.php.
References $user_id, $wpdb, and apply_filters().
use_ssl_preference ($user)
Optional SSL preference that can be turned on by hooking to the 'personal_options' action.
Since
2.7.0
Parameters
object $user User data object
Definition at line 491 of file wp-admin/includes/user.php.
References $user, _e, checked(), input, label, and name.
wp_delete_user ($id, $reassign = null)
Remove user and optionally reassign posts and links to another user.
If the $reassign parameter is not assigned to a User ID, then all posts will be deleted of that user. The action 'delete_user' that is passed the User ID being deleted will be run after the posts are either reassigned or deleted. The user meta will also be deleted that are for that User ID.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $id User ID.
int $reassign Optional. Reassign posts and links to new User ID.
Returns
bool True when finished.
Fires immediately before a user is deleted from the database.
Since
2.0.0
Parameters
int $id ID of the user to delete.
int | null $reassign ID of the user to reassign posts and links to. Default null, for no reassignment.
Filter the list of post types to delete with a user.
Since
3.4.0
Parameters
array $post_types_to_delete Post types to delete.
int $id User ID.
Fires immediately after a user is deleted from the database.
Since
2.9.0
Parameters
int $id ID of the deleted user.
int | null $reassign ID of the user to reassign posts and links to. Default null, for no reassignment.
Definition at line 284 of file wp-admin/includes/user.php.
References $id, $post_id, $post_type, $user, $wpdb, apply_filters(), clean_bookmark_cache(), clean_post_cache(), clean_user_cache(), delete_metadata_by_mid(), do_action(), elseif, get_current_blog_id(), get_post_types(), is_multisite(), null, post_type_supports(), remove_user_from_blog(), wp_delete_link(), and wp_delete_post().
Referenced by WP_UnitTestCase\delete_user().
wp_revoke_user ($id)
Remove all capabilities from user.
Since
2.1.0
Parameters
int $id User ID.
Definition at line 397 of file wp-admin/includes/user.php.
References $id, and $user.