GravityView: post.php File Reference
wp-admin/includes/post.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_admin_notice_post_locked ()
Outputs the HTML for the notice to say that someone else is editing or has taken over editing of this post.
_fix_attachment_links ($post)
Replace hrefs of attachment anchors with up-to-date permalinks.
_wp_post_thumbnail_html ($thumbnail_id=null, $post=null)
Output HTML for the post thumbnail meta-box.
_wp_translate_postdata ($update=false, $post_data=null)
add_meta ($post_ID)
Add post meta data defined in $_POST superglobal for post with given ID.
bulk_edit_posts ($post_data=null)
Process the post data for the bulk editing of posts.
delete_meta ($mid)
Delete post meta data by meta ID.
edit_post ($post_data=null)
Update an existing post with values provided in $_POST.
get_available_post_mime_types ($type= 'attachment')
Get all available post MIME types for a given post type.
get_available_post_statuses ($type= 'post')
Get all the possible statuses for a post_type.
get_default_post_to_edit ($post_type= 'post', $create_in_db=false)
Default post information to use when populating the "Write Post" form.
get_meta_keys ()
Get a list of previously defined keys.
get_post_meta_by_id ($mid)
Get post meta data by meta ID.
get_sample_permalink ($id, $title=null, $name=null)
Get a sample permalink based off of the post name.
get_sample_permalink_html ($id, $new_title=null, $new_slug=null)
Returns the HTML of the sample permalink slug editor.
has_meta ($postid)
Get meta data for the given post ID.
post_exists ($title, $content= '', $date= '')
Determine if a post exists based on title, content, and date.
post_preview ()
postbox_classes ($id, $page)
Returns the list of classes to be used by a metabox.
redirect_post ($post_id= '')
Redirect to previous page.
update_meta ($meta_id, $meta_key, $meta_value)
Update post meta data by meta ID.
wp_autosave ($post_data)
Save a post submitted with XHR.
wp_check_post_lock ($post_id)
Check to see if the post is currently being edited by another user.
wp_create_post_autosave ($post_data)
wp_edit_attachments_query ($q=false)
Executes a query for attachments.
wp_edit_attachments_query_vars ($q=false)
Get the query variables for the current attachments request.
wp_edit_posts_query ($q=false)
Run the wp query to fetch the posts for listing on the edit posts page.
wp_set_post_lock ($post_id)
Mark the post as currently being edited by the current user.
wp_write_post ()
Creates a new post from the "Write Post" form using $_POST information.
write_post ()
Calls wp_write_post() and handles the errors.
Function Documentation
_admin_notice_post_locked ()
Outputs the HTML for the notice to say that someone else is editing or has taken over editing of this post.
Since
2.8.5
Returns
none
Filter whether to show the post locked dialog.
Returning a falsey value to the filter will short-circuit displaying the dialog.
Since
3.6.0
Parameters
bool $display Whether to display the dialog. Default true.
WP_User | bool $user WP_User object on success, false otherwise.
Filter whether to allow the post lock to be overridden.
Returning a falsey value to the filter will disable the ability to override the post lock.
Since
3.6.0
Parameters
bool $override Whether to allow overriding post locks. Default true.
WP_Post $post Post object.
WP_User $user User object.
Fires inside the post locked dialog before the buttons are displayed.
Since
3.6.0
Parameters
WP_Post $post Post object.
Fires inside the dialog displayed when a user has lost the post lock.
Since
3.6.0
Parameters
WP_Post $post Post object.
Definition at line 1492 of file wp-admin/includes/post.php.
_fix_attachment_links ($post)
Replace hrefs of attachment anchors with up-to-date permalinks.
Since
2.3.0 private
Parameters
int | object $post Post ID or post object.
Returns
void|int|WP_Error Void if nothing fixed. 0 or WP_Error on update failure. The post ID on update success.
Definition at line 922 of file wp-admin/includes/post.php.
References $content, $link, $post, $url_id, $value, add_magic_quotes(), ARRAY_A, false, get_attachment_link(), get_bloginfo(), get_option(), get_post(), str_replace, and wp_update_post().
Referenced by edit_post(), and wp_write_post().
_wp_post_thumbnail_html ($thumbnail_id = null, $post = null)
Output HTML for the post thumbnail meta-box.
Since
2.9.0
int $content_width array $_wp_additional_image_sizes
Parameters
int $thumbnail_id ID of the attachment used for thumbnail
mixed $post The post ID or object associated with the thumbnail, defaults to global $post.
Returns
string html
Filter the size used to display the post thumbnail image in the 'Featured Image' meta box.
Note: When a theme adds 'post-thumbnail' support, a special 'post-thumbnail' image size is registered, which differs from the 'thumbnail' image size managed via the Settings > Media screen. See the $size parameter description for more information on default values.
Since
4.4.0
Parameters
string | array $size Post thumbnail image size to display in the meta box. Accepts any valid image size, or an array of width and height values in pixels (in that order). If the 'post-thumbnail' size is set, default is 'post-thumbnail'. Otherwise, default is an array with 266 as both the height and width values.
int $thumbnail_id Post thumbnail attachment ID.
WP_Post $post The post object associated with the thumbnail.
Filter the admin post thumbnail HTML markup to return.
Since
2.9.0
Parameters
string $content Admin post thumbnail HTML markup.
int $post_id Post ID.
Definition at line 1378 of file wp-admin/includes/post.php.
References $content, $post, $post_type_object, $size, $thumbnail_id, __, apply_filters(), esc_html, esc_url, get_post(), get_post_type_object(), get_upload_iframe_src(), and wp_get_attachment_image().
Referenced by post_thumbnail_meta_box(), and wp_ajax_set_post_thumbnail().
_wp_translate_postdata ($update = false, $post_data = null)
Definition at line 21 of file wp-admin/includes/post.php.
References $post_id, $update, __, current_user_can(), date, elseif, get_current_user_id(), get_gmt_from_date(), get_post_field(), get_post_status_object(), get_post_type_object(), sanitize_key(), and wp_checkdate().
Referenced by bulk_edit_posts(), edit_post(), and wp_write_post().
add_meta ($post_ID)
Add post meta data defined in $_POST superglobal for post with given ID.
Since
1.2.0
Parameters
int $post_ID
Returns
int|bool
Definition at line 798 of file wp-admin/includes/post.php.
References $post_ID, add_post_meta(), current_user_can(), is_protected_meta(), wp_slash(), and wp_unslash().
Referenced by edit_post(), wp_ajax_add_meta(), and wp_write_post().
bulk_edit_posts ($post_data = null)
Process the post data for the bulk editing of posts.
Updates all bulk edited posts/pages, adding (but not removing) tags and categories. Skips pages when they would be their own parent or child.
Since
2.7.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $post_data Optional, the array of post data to process if not provided will use $_POST superglobal.
Returns
array
Definition at line 411 of file wp-admin/includes/post.php.
References $cats, $field, $i, $page, $post, $post_ID, $post_type_object, $updated, $wpdb, __, _wp_translate_postdata(), _x, current_user_can(), get_object_taxonomies(), get_post(), get_post_type(), get_post_type_object(), get_taxonomy(), is_taxonomy_hierarchical(), is_wp_error(), null, sanitize_key(), set_post_format(), stick_post(), str_replace, unstick_post(), wp_check_post_lock(), wp_die(), wp_get_object_terms(), wp_get_post_categories(), and wp_update_post().
delete_meta ($mid)
Delete post meta data by meta ID.
Since
1.2.0
Parameters
int $mid
Returns
bool
Definition at line 837 of file wp-admin/includes/post.php.
References delete_metadata_by_mid().
Referenced by edit_post(), and wp_ajax_delete_meta().
edit_post ($post_data = null)
Update an existing post with values provided in $_POST.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $post_data Optional.
Returns
int Post ID.
This filter is documented in wp-admin/includes/media.php
Definition at line 181 of file wp-admin/includes/post.php.
References $field, $label, $post, $post_ID, $value, $wpdb, __, _fix_attachment_links(), _wp_get_post_revision_version(), _wp_translate_postdata(), _wp_upgrade_revisions_of_post(), _x, add_meta(), apply_filters(), current_user_can(), delete_meta(), esc_url_raw(), get_current_user_id(), get_post(), get_post_meta(), get_post_meta_by_id(), get_post_type_object(), get_terms(), is_protected_meta(), is_taxonomy_hierarchical(), is_wp_error(), post_type_supports(), sanitize_key(), sanitize_text_field(), set_post_format(), stick_post(), str_replace, unstick_post(), update_meta(), update_post_meta(), wp_die(), wp_filter_post_kses(), wp_get_attachment_id3_keys(), wp_get_attachment_metadata(), wp_get_post_revisions(), wp_set_post_lock(), wp_slash(), wp_strip_all_tags(), wp_unslash(), wp_update_attachment_metadata(), and wp_update_post().
Referenced by wp_ajax_add_meta(), wp_ajax_inline_save(), wp_ajax_wp_fullscreen_save_post(), and wp_write_post().
get_available_post_mime_types ($type = 'attachment')
Get all available post MIME types for a given post type.
Since
2.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $type
Returns
mixed
Definition at line 1078 of file wp-admin/includes/post.php.
References $types, and $wpdb.
Referenced by wp_edit_attachments_query().
get_available_post_statuses ($type = 'post')
Get all the possible statuses for a post_type.
Since
2.5.0
Parameters
string $type The post_type you want the statuses for
Returns
array As array of all the statuses for the supplied post type
Definition at line 974 of file wp-admin/includes/post.php.
References $stati, and wp_count_posts().
Referenced by wp_edit_posts_query().
get_default_post_to_edit ($post_type = 'post', $create_in_db = false)
Default post information to use when populating the "Write Post" form.
Since
2.0.0
Parameters
string $post_type Optional. A post type string. Default 'post'.
bool $create_in_db Optional. Whether to insert the post into database. Default false.
Returns
WP_Post Post object containing all the default post data as attributes
Filter the default post content initially used in the "Write Post" form.
Since
1.5.0
Parameters
string $post_content Default post content.
WP_Post $post Post object.
Filter the default post title initially used in the "Write Post" form.
Since
1.5.0
Parameters
string $post_title Default post title.
WP_Post $post Post object.
Filter the default post excerpt initially used in the "Write Post" form.
Since
1.5.0
Parameters
string $post_excerpt Default post excerpt.
WP_Post $post Post object.
Definition at line 584 of file wp-admin/includes/post.php.
References $post, $post_id, $post_title, $post_type, __, apply_filters(), current_theme_supports(), esc_html, get_default_comment_status(), get_option(), get_post(), post_type_supports(), set_post_format(), wp_insert_post(), and wp_unslash().
Referenced by wp_xmlrpc_server\_insert_post(), get_default_page_to_edit(), WP_Press_This\html(), WP_Posts_List_Table\inline_edit(), wp_xmlrpc_server\mw_newPost(), and wp_dashboard_quick_press().
get_meta_keys ()
Get a list of previously defined keys.
Since
1.2.0
wpdb $wpdb WordPress database abstraction object.
Returns
mixed
Definition at line 850 of file wp-admin/includes/post.php.
References $keys, and $wpdb.
get_post_meta_by_id ($mid)
Get post meta data by meta ID.
Since
2.1.0
Parameters
int $mid
Returns
object|bool
Definition at line 870 of file wp-admin/includes/post.php.
References get_metadata_by_mid().
Referenced by edit_post().
get_sample_permalink ($id, $title = null, $name = null)
Get a sample permalink based off of the post name.
Since
2.5.0
Parameters
int $id Post ID or post object.
string $title Optional. Title. Default null.
string $name Optional. Name. Default null.
Returns
array Array with two entries of type string.
This filter is documented in wp-admin/edit-tag-form.php
This filter is documented in wp-admin/edit-tag-form.php
Filter the sample permalink.
Since
4.4.0
Parameters
string $permalink Sample permalink.
int $post_id Post ID.
string $title Post title.
string $name Post name (slug).
WP_Post $post Post object.
Definition at line 1207 of file wp-admin/includes/post.php.
References $id, $name, $permalink, $post, $title, apply_filters(), get_page_uri(), get_permalink(), get_post(), get_post_type_object(), sanitize_title(), str_replace, untrailingslashit(), and wp_unique_post_slug().
Referenced by get_sample_permalink_html().
get_sample_permalink_html ($id, $new_title = null, $new_slug = null)
Returns the HTML of the sample permalink slug editor.
Since
2.5.0
Parameters
int $id Post ID or post object.
string $new_title Optional. New title. Default null.
string $new_slug Optional. New slug. Default null.
Returns
string The HTML of the sample permalink slug editor.
Filter the sample permalink HTML markup.
Since
2.9.0
4.4.0 Added $post parameter.
Parameters
string $return Sample permalink HTML markup.
int $post_id Post ID.
string $new_title New sample permalink title.
string $new_slug New sample permalink slug.
WP_Post $post Post object.
Definition at line 1285 of file wp-admin/includes/post.php.
References $id, $permalink, $post, __, apply_filters(), current_user_can(), esc_url, get_option(), get_permalink(), get_post(), get_preview_post_link(), get_sample_permalink(), set_url_scheme(), and str_replace.
Referenced by wp_ajax_sample_permalink().
has_meta ($postid)
Get meta data for the given post ID.
Since
1.2.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $postid
Returns
mixed
Definition at line 884 of file wp-admin/includes/post.php.
References $wpdb, and ARRAY_A.
Referenced by wp_xmlrpc_server\get_custom_fields(), and post_custom_meta_box().
post_exists ($title, $content = '', $date = '')
Determine if a post exists based on title, content, and date.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $title Post title
string $content Optional post content
string $date Optional post date
Returns
int Post ID if post exists, 0 otherwise.
Definition at line 669 of file wp-admin/includes/post.php.
References $content, $post_title, $title, $wpdb, sanitize_post_field(), and wp_unslash().
post_preview ()
Definition at line 1709 of file wp-admin/includes/post.php.
postbox_classes ($id, $page)
Returns the list of classes to be used by a metabox.
Since
2.5.0
Parameters
string $id
string $page
Returns
string
Filter the postbox classes for a specific screen and screen ID combo.
The dynamic portions of the hook name, $page and $id, refer to the screen and screen ID, respectively.
Since
3.2.0
Parameters
array $classes An array of postbox classes.
Definition at line 1170 of file wp-admin/includes/post.php.
References $id, $page, apply_filters(), elseif, and get_user_option().
Referenced by do_meta_boxes().
redirect_post ($post_id = '')
Redirect to previous page.
Parameters
int $post_id Optional. Post ID.
Filter the post redirect destination URL.
Since
2.9.0
Parameters
string $location The destination URL.
int $post_id The post ID.
Definition at line 1800 of file wp-admin/includes/post.php.
update_meta ($meta_id, $meta_key, $meta_value)
Update post meta data by meta ID.
Since
1.2.0
Parameters
int $meta_id
string $meta_key Expect Slashed
string $meta_value Expect Slashed
Returns
bool
Definition at line 902 of file wp-admin/includes/post.php.
References update_metadata_by_mid(), and wp_unslash().
Referenced by edit_post().
wp_autosave ($post_data)
Save a post submitted with XHR.
Intended for use with heartbeat and autosave.js
Since
3.9.0
Parameters
array $post_data Associative array of the submitted post data.
Returns
mixed The value 0 or WP_Error on failure. The saved post ID on success. The ID can be the draft post_id or the autosave revision post_id.
Definition at line 1762 of file wp-admin/includes/post.php.
Referenced by heartbeat_autosave().
wp_check_post_lock ($post_id)
Check to see if the post is currently being edited by another user.
Since
2.5.0
Parameters
int $post_id ID of the post to check for editing
Returns
integer False: not locked or locked by current user. Int: user ID of user with lock.
This filter is documented in wp-admin/includes/ajax-actions.php
Definition at line 1445 of file wp-admin/includes/post.php.
Referenced by bulk_edit_posts(), WP_Posts_List_Table\column_title(), WP_Posts_List_Table\single_row(), wp_ajax_inline_save(), wp_check_locked_posts(), wp_print_revision_templates(), and wp_refresh_post_lock().
wp_create_post_autosave ($post_data)
Fires before an autosave is stored.
Since
4.1.0
Parameters
array $new_autosave Post array - the autosave that is about to be saved.
Definition at line 1647 of file wp-admin/includes/post.php.
wp_edit_attachments_query ($q = false)
Executes a query for attachments.
An array of WP_Query arguments can be passed in, which will override the arguments set by this function.
Since
2.5.0
Parameters
array | false $q Array of query variables to use to build the query or false to use $_GET superglobal.
Returns
array
Definition at line 1152 of file wp-admin/includes/post.php.
References get_available_post_mime_types(), get_post_mime_types(), wp(), and wp_edit_attachments_query_vars().
Referenced by media_upload_library_form(), and WP_Media_List_Table\prepare_items().
wp_edit_attachments_query_vars ($q = false)
Get the query variables for the current attachments request.
Since
4.2.0
Parameters
array | false $q Optional. Array of query variables to use to build the query or false to use $_GET superglobal. Default false.
Returns
array The parsed query vars.
Filter the number of items to list per page when listing media items.
Since
2.9.0
Parameters
int $media_per_page Number of media to list. Default 20.
Definition at line 1094 of file wp-admin/includes/post.php.
References $post_type, apply_filters(), current_user_can(), get_post_mime_types(), get_post_type_object(), and get_user_option().
Referenced by wp_edit_attachments_query().
wp_edit_posts_query ($q = false)
Run the wp query to fetch the posts for listing on the edit posts page.
Since
2.5.0
Parameters
array | bool $q Array of query variables to use to build the query or false to use $_GET superglobal.
Returns
array
Filter the number of items per page to show for a specific 'per_page' type.
The dynamic portion of the hook name, $post_type, refers to the post type.
Some examples of filter hooks generated here include: 'edit_attachment_per_page', 'edit_post_per_page', 'edit_page_per_page', etc.
Since
3.0.0
Parameters
int $posts_per_page Number of posts to display per page for the given post type. Default 20.
Filter the number of posts displayed per page when specifically listing "posts".
Since
2.8.0
Parameters
int $posts_per_page Number of posts to be displayed. Default 20.
string $post_type The post type.
Definition at line 988 of file wp-admin/includes/post.php.
References $post_stati, $post_type, apply_filters(), elseif, get_available_post_statuses(), get_option(), get_post_stati(), get_post_types(), get_user_option(), is_post_type_hierarchical(), and wp().
Referenced by WP_Posts_List_Table\prepare_items().
wp_set_post_lock ($post_id)
Mark the post as currently being edited by the current user.
Since
2.5.0
Parameters
int $post_id ID of the post to being edited
Returns
bool|array Returns false if the post doesn't exist of there is no current user, or an array of the lock time and the user ID.
Definition at line 1473 of file wp-admin/includes/post.php.
Referenced by edit_post(), wp_refresh_post_lock(), and wp_write_post().
wp_write_post ()
Creates a new post from the "Write Post" form using $_POST information.
Since
2.1.0
WP_User $current_user
Returns
int|WP_Error
Definition at line 709 of file wp-admin/includes/post.php.
References $GLOBALS, $post_ID, __, _fix_attachment_links(), _wp_translate_postdata(), add_meta(), add_post_meta(), current_user_can(), edit_post(), get_post_type_object(), is_wp_error(), wp_insert_post(), and wp_set_post_lock().
Referenced by write_post().
write_post ()
Calls wp_write_post() and handles the errors.
Since
2.0.0
Returns
int|null
Definition at line 778 of file wp-admin/includes/post.php.
References is_wp_error(), wp_die(), and wp_write_post().