GravityView: image.php File Reference
wp-content/themes/twentyeleven/image.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$attachment_size = apply_filters('twentyeleven_attachment_size', 848)
Filter the Twenty Eleven default attachment size.
$attachments = array_values(get_children(array('post_parent' => $post->post_parent, 'post_status' => 'inherit', 'post_type' => 'attachment', 'post_mime_type' => 'image', 'order' => 'ASC', 'orderby' => 'menu_order ID')))
$metadata = wp_get_attachment_metadata()
foreach($attachments as $k=> $attachment) if(count($attachments) > 1) else
endif
endwhile
Variable Documentation
$attachment_size = apply_filters('twentyeleven_attachment_size', 848)
Filter the Twenty Eleven default attachment size.
Since
Twenty Eleven 1.0
Parameters
int The height and width attachment size dimensions in pixels. Default 848.
Definition at line 83 of file wp-content/themes/twentyeleven/image.php.
$attachments = array_values(get_children(array('post_parent' => $post->post_parent, 'post_status' => 'inherit', 'post_type' => 'attachment', 'post_mime_type' => 'image', 'order' => 'ASC', 'orderby' => 'menu_order ID')))
Definition at line 55 of file wp-content/themes/twentyeleven/image.php.
Referenced by adjacent_image_link(), wp_xmlrpc_server\attach_uploads(), gallery_shortcode(), get_media_items(), WP_Rewrite\page_uri_index(), update_gallery_tab(), wp_ajax_save_attachment_order(), wp_xmlrpc_server\wp_getMediaLibrary(), and wp_playlist_shortcode().
$metadata = wp_get_attachment_metadata()
Definition at line 29 of file wp-content/themes/twentyeleven/image.php.
Referenced by WP_Site_Icon\insert_attachment(), Custom_Image_Header\insert_attachment(), WP_Image_Editor_GD\multi_resize(), WP_Image_Editor_Imagick\multi_resize(), post_custom_meta_box(), wp_add_id3_tag_data(), wp_ajax_crop_image(), wp_generate_attachment_metadata(), wp_read_audio_metadata(), and wp_read_video_metadata().
foreach ($attachments as $k=> $attachment) if (count($attachments) > 1) else
Initial value:
{
        $next_attachment_url = wp_get_attachment_url()
Definition at line 70 of file wp-content/themes/twentyeleven/image.php.
endif
Definition at line 91 of file wp-content/themes/twentyeleven/image.php.
endwhile
Definition at line 107 of file wp-content/themes/twentyeleven/image.php.