GravityView: image.php File Reference
wp-content/themes/twentythirteen/image.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$metadata = wp_get_attachment_metadata()
$post_title = get_the_title($post->post_parent)
$published_text = __('<span class="attachment-meta">Published on <time class="entry-date" datetime="%1$s">%2$s</time> in <a href="%3$s" title="Return to %4$s" rel="gallery">%5$s</a></span>', 'twentythirteen')
endif
endwhile
Variable Documentation
$metadata = wp_get_attachment_metadata()
Definition at line 41 of file wp-content/themes/twentythirteen/image.php.
$post_title = get_the_title($post->post_parent)
Definition at line 29 of file wp-content/themes/twentythirteen/image.php.
Referenced by wp_xmlrpc_server\blogger_newPost(), GFFormsModel\create_post(), do_trackbacks(), get_adjacent_post_rel_link(), get_attachment_icon(), get_default_post_to_edit(), get_the_attachment_link(), WP_Press_This\html(), WP_Customize_Nav_Menus\load_available_items_query(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), post_exists(), WP_Customize_Nav_Menus\search_available_items_query(), GravityView_Edit_Entry_Test\test_get_edit_link(), GravityView_Entry_Link_Shortcode_Test\test_shortcode(), upgrade_130(), wp_insert_post(), and xmlrpc_getposttitle().
$published_text = __('<span class="attachment-meta">Published on <time class="entry-date" datetime="%1$s">%2$s</time> in <a href="%3$s" title="Return to %4$s" rel="gallery">%5$s</a></span>', 'twentythirteen')
Definition at line 28 of file wp-content/themes/twentythirteen/image.php.
endif
Definition at line 69 of file wp-content/themes/twentythirteen/image.php.
endwhile
Definition at line 85 of file wp-content/themes/twentythirteen/image.php.