GravityView: wp-comments-post.php File Reference
wp-comments-post.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$comment = wp_handle_comment_submission(wp_unslash($_POST))
$location = empty($_POST['redirect_to']) ? get_comment_link($comment) : $_POST['redirect_to'] . '#comment-' . $comment->comment_ID
Filter the location URI to send the commenter after posting.
if(is_wp_error($comment)) $user = wp_get_current_user()
exit
if ('POST'!=$_SERVER['REQUEST_METHOD'])
Sets up the WordPress Environment.
Variable Documentation
$comment = wp_handle_comment_submission(wp_unslash($_POST))
Definition at line 20 of file wp-comments-post.php.
Referenced by WP_Comment\__construct(), wp_xmlrpc_server\_prepare_comment(), _wp_ajax_delete_comment_response(), _wp_dashboard_recent_comments_row(), getid3_apetag\Analyze(), check_comment(), WP_Comments_List_Table\column_author(), WP_Comments_List_Table\column_comment(), WP_Comments_List_Table\column_date(), WP_Comments_List_Table\column_default(), Walker_Comment\comment(), comment_author(), comment_author_email(), comment_author_url(), comment_class(), comment_excerpt(), comment_form_title(), comment_link(), comment_reply_link(), comment_text(), comments_template(), edit_comment_link(), Walker_Comment\end_el(), WP_Comments_List_Table\floated_admin_avatar(), getid3_id3v1\GenerateID3v1Tag(), get_comment(), get_comment_author(), get_comment_author_email(), get_comment_author_email_link(), get_comment_author_IP(), get_comment_author_link(), get_comment_author_url(), get_comment_class(), get_comment_date(), get_comment_excerpt(), get_comment_guid(), get_comment_ID(), get_comment_link(), get_comment_reply_link(), get_comment_text(), get_comment_time(), get_comment_to_edit(), get_comment_type(), get_edit_comment_link(), get_page_of_comment(), WP_Comments_List_Table\handle_row_actions(), Walker_Comment\html5_comment(), load_template(), map_meta_cap(), wp_xmlrpc_server\mt_getTrackbackPings(), Walker_Comment\ping(), wp_xmlrpc_server\pingback_extensions_getPingbacks(), SimplePie_Sanitize\sanitize(), WP_Comments_List_Table\single_row(), Walker_Comment\start_el(), update_comment_cache(), upgrade_130(), upgrade_160(), upgrade_430_fix_comments(), WP_Widget_Recent_Comments\widget(), wp_ajax_delete_comment(), wp_ajax_dim_comment(), wp_ajax_edit_comment(), wp_ajax_get_comments(), wp_ajax_replyto_comment(), wp_blacklist_check(), wp_delete_comment(), wp_xmlrpc_server\wp_editComment(), wp_get_comment_status(), wp_xmlrpc_server\wp_getComment(), wp_xmlrpc_server\wp_getComments(), wp_insert_comment(), wp_new_comment_notify_moderator(), wp_new_comment_notify_postauthor(), wp_xmlrpc_server\wp_newComment(), wp_scheduled_delete(), wp_set_comment_cookies(), wp_set_comment_status(), wp_spam_comment(), wp_transition_comment_status(), wp_trash_comment(), wp_trash_post_comments(), wp_unspam_comment(), wp_untrash_comment(), and wp_update_comment().
$location = empty($_POST['redirect_to']) ? get_comment_link($comment) : $_POST['redirect_to'] . '#comment-' . $comment->comment_ID
Filter the location URI to send the commenter after posting.
Since
2.0.5
Parameters
string $location The 'redirect_to' URI sent via $_POST.
WP_Comment $comment Comment object.
Definition at line 42 of file wp-comments-post.php.
if (is_wp_error($comment)) $user = wp_get_current_user()
Definition at line 30 of file wp-comments-post.php.
exit
Definition at line 55 of file wp-comments-post.php.
if('POST'!=$_SERVER['REQUEST_METHOD'])
Sets up the WordPress Environment.
Definition at line 8 of file wp-comments-post.php.