GravityView: custom-header.php File Reference
wp-content/themes/twentyfifteen/inc/custom-header.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentyfifteen_custom_header_setup ()
Set up the WordPress core custom header feature.
twentyfifteen_header_background_color_css ()
Enqueues front-end CSS for the header background color.
twentyfifteen_hex2rgb ($color)
Convert HEX to RGB.
twentyfifteen_sidebar_text_color_css ()
Enqueues front-end CSS for the sidebar text color.
Variables
if(!function_exists('twentyfifteen_header_style'))() endif
Function Documentation
twentyfifteen_custom_header_setup ()
Set up the WordPress core custom header feature.
twentyfifteen_header_style()
Filter Twenty Fifteen custom-header support arguments.
Since
Twenty Fifteen 1.0
Parameters
array $args { An array of custom-header support arguments.
string $default_text_color Default color of the header text. int $width Width in pixels of the custom header image. Default 954. int $height Height in pixels of the custom header image. Default 1300. string $wp-head-callback Callback function used to styles the header image and text displayed on the blog. }
Definition at line 15 of file wp-content/themes/twentyfifteen/inc/custom-header.php.
References add_theme_support(), and apply_filters().
twentyfifteen_header_background_color_css ()
Enqueues front-end CSS for the header background color.
Since
Twenty Fifteen 1.0
See also
wp_add_inline_style()
Definition at line 195 of file wp-content/themes/twentyfifteen/inc/custom-header.php.
References get_theme_mod(), and wp_add_inline_style().
twentyfifteen_hex2rgb ($color)
Convert HEX to RGB.
Since
Twenty Fifteen 1.0
Parameters
string $color The original color, in 3- or 6-digit hexadecimal form.
Returns
array Array containing RGB (red, green, and blue) values for the given HEX code, empty array otherwise.
Definition at line 52 of file wp-content/themes/twentyfifteen/inc/custom-header.php.
Referenced by twentyfifteen_color_scheme_css(), and twentyfifteen_sidebar_text_color_css().
twentyfifteen_sidebar_text_color_css ()
Enqueues front-end CSS for the sidebar text color.
Since
Twenty Fifteen 1.0
Definition at line 239 of file wp-content/themes/twentyfifteen/inc/custom-header.php.
References get_theme_mod(), twentyfifteen_hex2rgb(), and wp_add_inline_style().
Variable Documentation
if (! function_exists('twentyfifteen_header_style')) () endif
Definition at line 70 of file wp-content/themes/twentyfifteen/inc/custom-header.php.