GravityView: wp-cron.php File Reference
wp-cron.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
if(!defined('ABSPATH')) _get_cron_lock ()
Retrieves the cron lock.
Variables
$doing_cron_transient = get_transient('doing_cron')
$gmt_time = microtime(true)
$keys = array_keys($crons)
const DOING_CRON true
Function Documentation
if (!defined('ABSPATH')) _get_cron_lock ()
Retrieves the cron lock.
Returns the uncached doing_cron transient.
Since
3.3.0
Returns
string|false Value of the doing_cron transient, 0|false otherwise.
Fires scheduled events.
Since
2.1.0
Parameters
string $hook Name of the hook that was scheduled to be fired.
array $args The arguments to be passed to the hook.
Definition at line 39 of file wp-cron.php.
References $value, $wpdb, wp_cache_get(), and wp_using_ext_object_cache().
Variable Documentation
$doing_cron_transient = get_transient('doing_cron')
Definition at line 69 of file wp-cron.php.
$gmt_time = microtime(true)
Definition at line 62 of file wp-cron.php.
Referenced by spawn_cron(), upgrade_110(), and wp_cron().
$keys = array_keys($crons)
Definition at line 61 of file wp-cron.php.
Referenced by WP_Customize_Setting\__construct(), WP_Customize_Panel\__construct(), WP_Customize_Section\__construct(), WP_Customize_Control\__construct(), _get_additional_user_keys(), WP_Widget_Factory\_register_widgets(), add_option_whitelist(), WP_Query\fill_query_vars(), WP_Widget_Tag_Cloud\form(), GFForms\format_toolbar_menu_items(), get_blogs_of_user(), get_bookmarks(), GFFormsModel\get_custom_field_names(), GFExport\get_entry_meta(), SimplePie\get_items(), SimplePie_Source\get_links(), SimplePie_Item\get_links(), SimplePie\get_links(), get_media_item(), get_meta_keys(), get_post_custom_keys(), get_selectable_entry_meta(), WP_Text_Diff_Renderer_Table\interleave_changed_lines(), is_user_member_of_blog(), media_upload_form_handler(), meta_form(), WP_Customize_Setting\multidimensional(), WP_Customize_Setting\multidimensional_get(), WP_Customize_Setting\multidimensional_isset(), WP_Customize_Setting\multidimensional_replace(), WP_Theme\offsetExists(), populate_options(), remove_option_whitelist(), GFFormsModel\set_entry_meta(), spawn_cron(), the_meta(), wp_ajax_query_attachments(), wp_array_slice_assoc(), wp_cron(), wp_is_numeric_array(), wp_mime_type_icon(), wp_terms_checklist(), and wp_update_comment().
const DOING_CRON true
Definition at line 22 of file wp-cron.php.
Referenced by _unzip_file_pclzip(), _unzip_file_ziparchive(), Plugin_Upgrader\deactivate_plugin_before_upgrade(), GFForms\deprecate_add_on_methods(), get_core_checksums(), wp_update_plugins(), wp_update_themes(), and wp_version_check().