GravityView: custom-header.php File Reference
wp-content/themes/twentythirteen/inc/custom-header.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
twentythirteen_admin_header_image ()
Output markup to be displayed on the Appearance > Header admin panel.
twentythirteen_admin_header_style ()
Style the header image displayed on the Appearance > Header admin panel.
twentythirteen_custom_header_fonts ()
Load our special font CSS files.
twentythirteen_custom_header_setup ()
Set up the WordPress core custom header arguments and settings.
twentythirteen_header_style ()
Style the header text displayed on the blog.
Variables
margin __pad24__
clip __pad25__
if(!empty($header_image)||display_header_text()) if(!display_header_text()) clip
clip endif
webkit box sizing
max width
Function Documentation
twentythirteen_admin_header_image ()
Output markup to be displayed on the Appearance > Header admin panel.
This callback overrides the default markup displayed there.
Since
Twenty Thirteen 1.0
Definition at line 218 of file wp-content/themes/twentythirteen/inc/custom-header.php.
References bloginfo(), display_header_text(), and get_header_textcolor().
twentythirteen_admin_header_style ()
Style the header image displayed on the Appearance > Header admin panel.
Since
Twenty Thirteen 1.0
Definition at line 152 of file wp-content/themes/twentythirteen/inc/custom-header.php.
References $header_image, esc_url, get_header_image(), and sizing.
twentythirteen_custom_header_fonts ()
Load our special font CSS files.
Since
Twenty Thirteen 1.0
Definition at line 70 of file wp-content/themes/twentythirteen/inc/custom-header.php.
References get_template_directory_uri(), null, twentythirteen_fonts_url(), and wp_enqueue_style().
twentythirteen_custom_header_setup ()
Set up the WordPress core custom header arguments and settings.
add_theme_support() to register support for 3.4 and up. twentythirteen_header_style() to style front-end. twentythirteen_admin_header_style() to style wp-admin form. twentythirteen_admin_header_image() to add custom markup to wp-admin form. register_default_headers() to set up the bundled header images.
Since
Twenty Thirteen 1.0
Definition at line 23 of file wp-content/themes/twentythirteen/inc/custom-header.php.
References _x, add_theme_support(), and register_default_headers().
twentythirteen_header_style ()
Style the header text displayed on the blog.
get_header_textcolor() options: Hide text (returns 'blank'), or any hex value.
Since
Twenty Thirteen 1.0
Definition at line 86 of file wp-content/themes/twentythirteen/inc/custom-header.php.
References $header_image, clip, color, display_header_text(), elseif, endif, esc_attr(), get_header_image(), get_header_textcolor(), get_theme_support(), header_image(), height, size, title, and width.
Variable Documentation
margin __pad24__
Definition at line 171 of file wp-content/themes/twentythirteen/inc/custom-header.php.
clip __pad25__
Definition at line 184 of file wp-content/themes/twentythirteen/inc/custom-header.php.
if (!empty($header_image)||display_header_text()) if (!display_header_text()) clip
Definition at line 179 of file wp-content/themes/twentythirteen/inc/custom-header.php.
Referenced by print_embed_styles(), twentythirteen_header_style(), and twentytwelve_header_style().
clip endif
Definition at line 184 of file wp-content/themes/twentythirteen/inc/custom-header.php.
Referenced by twentythirteen_header_style().
box sizing
Definition at line 168 of file wp-content/themes/twentythirteen/inc/custom-header.php.
Referenced by print_embed_styles(), and twentythirteen_admin_header_style().
max width
Definition at line 172 of file wp-content/themes/twentythirteen/inc/custom-header.php.
Referenced by GravityView_Image\__construct(), SimplePie_Enclosure\__construct(), _admin_bar_bump_cb(), _default_wp_die_handler(), GravityView_Welcome\admin_head(), WP_Customize_Media_Control\content_template(), GFExport\export_lead_page(), GFFormList\form_list_page(), SimplePie_Enclosure\get_width(), GravityView_Welcome\getting_started_screen(), GFEntryDetail\lead_detail_grid(), GFEntryList\leads_page(), list_theme_updates(), media_upload_type_url_form(), SimplePie_Misc\output_javascript(), print_embed_styles(), print_emoji_styles(), AVCSequenceParameterSetReader\readData(), GravityView_Image\set_image_size(), WP_Theme_Install_List_Table\single_row(), Custom_Image_Header\step_2(), GravityView_Welcome\tabs(), WP_Customize_Cropped_Image_Control\to_json(), twentyeleven_settings_field_color_scheme(), twentyeleven_settings_field_layout(), twentyfifteen_get_color_scheme_css(), twentythirteen_header_style(), wp_image_editor(), wp_playlist_shortcode(), wp_print_media_templates(), wp_underscore_audio_template(), wp_underscore_video_template(), and wpmu_signup_stylesheet().