GravityView: sidebar.php File Reference
wp-content/themes/twentyeleven/sidebar.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$current_layout = $options['theme_layout']
$options = twentyeleven_get_theme_options()
endif
Variable Documentation
$current_layout = $options['theme_layout']
Definition at line 11 of file wp-content/themes/twentyeleven/sidebar.php.
Referenced by twentyeleven_layout_classes().
$options = twentyeleven_get_theme_options()
Definition at line 10 of file wp-content/themes/twentyeleven/sidebar.php.
Referenced by SpeedTrapListener\__construct(), WP_PHPUnit_Util_Getopt\__construct(), GravityView_Uninstall_Test\_check_deleted_options(), wp_xmlrpc_server\_getOptions(), _WP_Editors\_parse_init(), _register_widget_form_callback(), _register_widget_update_callback(), GravityView_Field\add_field_support(), add_option_whitelist(), GFForms\addons_page(), GravityView_Widget\assign_widget_options(), Language_Pack_Upgrader\bulk_upgrade(), SMTP\connect(), WP_REST_Server\dispatch(), _WP_Editors\editor_js(), SimplePie_Enclosure\embed(), GravityView_Field\field_support_options(), get_alloptions_110(), GFAutoUpgrade\get_changelog(), GFForms\get_changelog(), get_core_checksums(), get_core_updates(), WP_REST_Server\get_data_for_route(), GF_Field_CAPTCHA\get_field_input(), GF_Field_Name\get_name_prefix_field(), GFPaymentAddOn\get_order_data(), Featured_Content\get_setting(), GFFeedAddOn\has_paypal_payment(), GravityView_Plugin_Hooks_Yoast_SEO\hide_wordpress_seo_metabox(), GFExport\import_xml(), PHPMailer\mb_pathinfo(), mu_options(), SimplePie_Enclosure\native_embed(), option_update_filter(), GravityView_Shortcode\parse_and_sanitize_atts(), populate_options(), GravityView_Ajax\pre_get_form_fields(), register_sidebar_widget(), register_widget_control(), remove_option_whitelist(), GravityView_Render_Settings\render_field_options(), WP_Screen\render_screen_options(), GFFormDisplay\replace_save_variables(), Gravity_Api\request(), WP_Upgrader\run(), PHPMailer\smtpConnect(), trackback(), translations_api(), twentyeleven_customize_register(), twentyeleven_enqueue_color_scheme(), twentyeleven_get_default_link_color(), twentyeleven_layout_classes(), twentyeleven_print_link_color_style(), twentyeleven_settings_field_color_scheme(), twentyeleven_settings_field_layout(), twentyeleven_settings_field_link_color(), upgrade_130(), wp_get_http(), wp_get_popular_importers(), wp_xmlrpc_server\wp_getOptions(), wp_json_encode(), wp_kses_no_null(), wp_load_core_site_options(), wp_register_sidebar_widget(), wp_register_widget_control(), wp_remote_fopen(), wp_xmlrpc_server\wp_setOptions(), wp_update_plugins(), wp_update_themes(), and wp_version_check().
</div><!-- #secondary .widget-area --> endif
Definition at line 34 of file wp-content/themes/twentyeleven/sidebar.php.