GravityView: custom-header.php File Reference
wp-content/themes/twentytwelve/inc/custom-header.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
max twentytwelve_admin_header_image ()
Output markup to be displayed on the Appearance > Header admin panel.
twentytwelve_admin_header_style ()
Style the header image displayed on the Appearance > Header admin panel.
twentytwelve_custom_header_fonts ()
Load our special font CSS file.
twentytwelve_custom_header_setup ()
Set up the WordPress core custom header arguments and settings.
twentytwelve_header_style ()
Style the header text displayed on the blog.
Variables
margin __pad38__
padding __pad39__
color __pad40__
color __pad41__
color __pad42__
margin bottom
text decoration
line height
font size
max width
Function Documentation
max twentytwelve_admin_header_image ()
Output markup to be displayed on the Appearance > Header admin panel.
This callback overrides the default markup displayed there.
Since
Twenty Twelve 1.0
Definition at line 149 of file wp-content/themes/twentytwelve/inc/custom-header.php.
References $header_image, bloginfo(), display_header_text(), endif, get_header_image(), get_header_textcolor(), height, and width.
twentytwelve_admin_header_style ()
Style the header image displayed on the Appearance > Header admin panel.
Since
Twenty Twelve 1.0
Definition at line 107 of file wp-content/themes/twentytwelve/inc/custom-header.php.
References Arial, family, Helvetica, and serif.
twentytwelve_custom_header_fonts ()
Load our special font CSS file.
Since
Twenty Twelve 1.2
Definition at line 55 of file wp-content/themes/twentytwelve/inc/custom-header.php.
References esc_url_raw(), null, twentytwelve_get_font_url(), and wp_enqueue_style().
twentytwelve_custom_header_setup ()
Set up the WordPress core custom header arguments and settings.
add_theme_support() to register support for 3.4 and up. twentytwelve_header_style() to style front-end. twentytwelve_admin_header_style() to style wp-admin form. twentytwelve_admin_header_image() to add custom markup to wp-admin form.
Since
Twenty Twelve 1.0
Definition at line 22 of file wp-content/themes/twentytwelve/inc/custom-header.php.
References add_theme_support().
twentytwelve_header_style ()
Style the header text displayed on the blog.
get_header_textcolor() options: 515151 is default, hide text (returns 'blank'), or any hex value.
Since
Twenty Twelve 1.0
Definition at line 69 of file wp-content/themes/twentytwelve/inc/custom-header.php.
References a, clip, color, display_header_text(), endif, get_header_textcolor(), get_theme_support(), and title.
Variable Documentation
margin __pad38__
Definition at line 117 of file wp-content/themes/twentytwelve/inc/custom-header.php.
padding __pad39__
Definition at line 118 of file wp-content/themes/twentytwelve/inc/custom-header.php.
color __pad40__
Definition at line 124 of file wp-content/themes/twentytwelve/inc/custom-header.php.
color __pad41__
Definition at line 128 of file wp-content/themes/twentytwelve/inc/custom-header.php.
color __pad42__
Definition at line 131 of file wp-content/themes/twentytwelve/inc/custom-header.php.
margin bottom
Definition at line 133 of file wp-content/themes/twentytwelve/inc/custom-header.php.
text decoration
Definition at line 125 of file wp-content/themes/twentytwelve/inc/custom-header.php.
line height
Definition at line 116 of file wp-content/themes/twentytwelve/inc/custom-header.php.
Referenced by twentytwelve_admin_header_image().
font size
Definition at line 121 of file wp-content/themes/twentytwelve/inc/custom-header.php.
max width
Definition at line 136 of file wp-content/themes/twentytwelve/inc/custom-header.php.
Referenced by twentytwelve_admin_header_image().