GravityView: ms-deprecated.php File Reference
wp-includes/ms-deprecated.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
clear_global_post_cache ($post_id)
Deprecated functionality to clear the global post cache.
create_empty_blog ($domain, $path, $weblog_title, $site_id=1)
Create an empty blog.
generate_random_password ($len=8)
Generates a random password.
get_admin_users_for_domain ($sitedomain= '', $path= '')
Get the admin for a domain/path combination.
get_blog_list ($start=0, $num=10, $deprecated= '')
Deprecated functionality to retrieve a list of all sites.
get_blogaddress_by_domain ($domain, $path)
Get a full blog URL, given a domain and a path.
get_dashboard_blog ()
Get the "dashboard blog", the blog where users without a blog edit their profile data.
get_most_active_blogs ($num=10, $display=true)
Deprecated functionality to retrieve a list of the most active sites.
get_user_details ($username)
Deprecated functionality to retrieve user information.
get_user_id_from_string ($string)
Get a numeric user ID from either an email address or a login.
is_main_blog ()
Deprecated functionality to determin if the current site is the main site.
is_site_admin ($user_login= '')
Determine if user is a site admin.
validate_email ($email, $check_domain=true)
Deprecated functionality to validate an email address.
wpmu_admin_do_redirect ($url= '')
Redirect a user based on $_GET or $_POST arguments.
wpmu_admin_redirect_add_updated_param ($url= '')
Adds an 'updated=true' argument to a URL.
Variables
if(!function_exists('graceful_fail'))($message) endif
Function Documentation
clear_global_post_cache ($post_id)
Deprecated functionality to clear the global post cache.
Since
MU
Definition at line 134 of file wp-includes/ms-deprecated.php.
References _deprecated_function().
create_empty_blog ($domain, $path, $weblog_title, $site_id = 1)
Create an empty blog.
Since
MU 1.0
Parameters
string $domain The new blog's domain.
string $path The new blog's path.
string $weblog_title The new blog's title.
int $site_id Optional. Defaults to 1.
Returns
string|int The ID of the newly created blog
Definition at line 376 of file wp-includes/ms-deprecated.php.
References $blog_id, $path, __, _deprecated_function(), domain_exists(), insert_blog(), install_blog(), restore_current_blog(), and switch_to_blog().
generate_random_password ($len = 8)
Generates a random password.
Since
MU
Definition at line 41 of file wp-includes/ms-deprecated.php.
References _deprecated_function().
get_admin_users_for_domain ($sitedomain = '', $path = '')
Get the admin for a domain/path combination.
Since
MU 1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $sitedomain Optional. Site domain.
string $path Optional. Site path.
Returns
array|false The network admins
Definition at line 412 of file wp-includes/ms-deprecated.php.
References $path, $wpdb, _deprecated_function(), and ARRAY_A.
get_blog_list ($start = 0, $num = 10, $deprecated = '')
Deprecated functionality to retrieve a list of all sites.
Since
MU
Definition at line 173 of file wp-includes/ms-deprecated.php.
References $blogs, $details, $wpdb, _deprecated_function(), and ARRAY_A.
Referenced by get_most_active_blogs().
get_blogaddress_by_domain ($domain, $path)
Get a full blog URL, given a domain and a path.
Since
MU
Parameters
string $domain
string $path
Returns
string
Definition at line 345 of file wp-includes/ms-deprecated.php.
References $_SERVER, $path, $url, _deprecated_function(), esc_url_raw(), and is_subdomain_install().
get_dashboard_blog ()
Get the "dashboard blog", the blog where users without a blog edit their profile data.
Dashboard blog functionality was removed in WordPress 3.1, replaced by the user admin.
Since
MU
Returns
int Current site ID.
Definition at line 26 of file wp-includes/ms-deprecated.php.
References $blog, $GLOBALS, _deprecated_function(), get_blog_details(), and get_site_option().
get_most_active_blogs ($num = 10, $display = true)
Deprecated functionality to retrieve a list of the most active sites.
Since
MU
Returns
array List of "most active" sites.
Definition at line 204 of file wp-includes/ms-deprecated.php.
References $blogs, $details, $url, _deprecated_function(), esc_url, and get_blog_list().
get_user_details ($username)
Deprecated functionality to retrieve user information.
Since
MU
Definition at line 122 of file wp-includes/ms-deprecated.php.
References _deprecated_function().
get_user_id_from_string ($string)
Get a numeric user ID from either an email address or a login.
A numeric string is considered to be an existing user ID and is simply returned as such.
Since
MU
Parameters
string $string Either an email address or a login.
Returns
int
Definition at line 320 of file wp-includes/ms-deprecated.php.
References $user, _deprecated_function(), elseif, and is_email().
is_main_blog ()
Deprecated functionality to determin if the current site is the main site.
Since
MU
Definition at line 145 of file wp-includes/ms-deprecated.php.
References _deprecated_function(), and is_main_site().
is_site_admin ($user_login = '')
Determine if user is a site admin.
Plugins should use is_multisite() instead of checking if this function exists to determine if multisite is enabled.
This function must reside in a file included only if is_multisite() due to legacy function_exists() checks to determine if multisite is enabled.
Since
MU
Definition at line 59 of file wp-includes/ms-deprecated.php.
References $user, $user_id, _deprecated_function(), get_current_user_id(), and is_super_admin().
validate_email ($email, $check_domain = true)
Deprecated functionality to validate an email address.
Since
MU
Parameters
string $email Email address to verify.
bool $check_domain Deprecated.
Returns
string|bool Either false or the valid email address.
Definition at line 161 of file wp-includes/ms-deprecated.php.
References _deprecated_function(), and is_email().
wpmu_admin_do_redirect ($url = '')
Redirect a user based on $_GET or $_POST arguments.
The function looks for redirect arguments in the following order: 1) $_GET['ref'] 2) $_POST['ref'] 3) $_SERVER['HTTP_REFERER'] 4) $_GET['redirect'] 5) $_POST['redirect'] 6) $url
Since
MU
Parameters
string $url
Definition at line 255 of file wp-includes/ms-deprecated.php.
References $_SERVER, $url, _deprecated_function(), elseif, esc_html, exit, and wpmu_admin_redirect_add_updated_param().
wpmu_admin_redirect_add_updated_param ($url = '')
Adds an 'updated=true' argument to a URL.
Since
MU
Parameters
string $url
Returns
string
Definition at line 295 of file wp-includes/ms-deprecated.php.
References $url, and _deprecated_function().
Referenced by wpmu_admin_do_redirect().
Variable Documentation
if (!function_exists('graceful_fail')) ($message) endif
Definition at line 76 of file wp-includes/ms-deprecated.php.