GravityView: user.php File Reference
wp-includes/user.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_additional_user_keys ($user)
Returns a list of meta keys to be (maybe) populated in wp_update_user().
_wp_get_user_contactmethods ($user=null)
The old private function for setting up user contact methods.
add_user_meta ($user_id, $meta_key, $meta_value, $unique=false)
Add meta data field to a user.
check_password_reset_key ($key, $login)
Retrieves a user row based on password reset key and login.
clean_user_cache ($user)
Clean all user caches.
count_many_users_posts ($users, $post_type= 'post', $public_only=false)
Number of posts written by a list of users.
count_user_posts ($userid, $post_type= 'post', $public_only=false)
Number of posts user has written.
count_users ($strategy= 'time')
Count number of users who have each of the user roles.
delete_user_meta ($user_id, $meta_key, $meta_value= '')
Remove metadata matching criteria from a user.
delete_user_option ($user_id, $option_name, $global=false)
Delete user option with global blog capability.
email_exists ($email)
Checks whether the given email exists.
get_blogs_of_user ($user_id, $all=false)
Get the blogs a user belongs to.
get_current_user_id ()
Get the current user's ID.
get_password_reset_key ($user)
Creates, stores, then returns a password reset key for user.
get_user_meta ($user_id, $key= '', $single=false)
Retrieve user meta field for a user.
get_user_option ($option, $user=0, $deprecated= '')
Retrieve user option that can be either per Site or per Network.
get_users ($args=array())
Retrieve list of users matching criteria.
is_user_member_of_blog ($user_id=0, $blog_id=0)
Find out whether a user is a member of a given blog.
register_new_user ($user_login, $user_email)
Handles registering a new user.
reset_password ($user, $new_pass)
Handles resetting the user's password.
sanitize_user_field ($field, $value, $user_id, $context)
Sanitize user field based on context.
setup_userdata ($for_user_id= '')
Set up global user vars.
update_user_caches ($user)
Update all user caches.
update_user_meta ($user_id, $meta_key, $meta_value, $prev_value= '')
Update user meta field based on user ID.
update_user_option ($user_id, $option_name, $newvalue, $global=false)
Update user option with global blog capability.
username_exists ($username)
Checks whether the given username exists.
validate_username ($username)
Checks whether a username is valid.
wp_authenticate_cookie ($user, $username, $password)
Authenticate the user using the WordPress auth cookie.
wp_authenticate_spam_check ($user)
For Multisite blogs, check if the authenticated user has been marked as a spammer, or if the user's primary blog has been marked as spam.
wp_authenticate_username_password ($user, $username, $password)
Authenticate a user, confirming the username and password are valid.
wp_create_user ($username, $password, $email= '')
A simpler way of inserting a user into the database.
wp_destroy_all_sessions ()
Remove all session tokens for the current user from the database.
wp_destroy_current_session ()
Remove the current session token from the database.
wp_destroy_other_sessions ()
Remove all but the current session token for the current user for the database.
wp_dropdown_users ($args= '')
Create dropdown HTML content of users.
wp_get_all_sessions ()
Retrieve a list of sessions for the current user.
wp_get_password_hint ()
Gets the text suggesting how to create strong passwords.
wp_get_session_token ()
Retrieve the current session token from the logged_in cookie.
wp_get_user_contact_methods ($user=null)
Set up the user contact methods.
wp_get_users_with_no_role ()
Get the user IDs of all users with no role on this site.
wp_insert_user ($userdata)
Insert a user into the database.
wp_send_new_user_notifications ($user_id, $notify= 'both')
Initiate email notifications related to the creation of new users.
wp_signon ($credentials=array(), $secure_cookie= '')
Authenticate and log in a user with remember capability.
wp_update_user ($userdata)
Update a user in the database.
wp_validate_logged_in_cookie ($user_id)
Validate the logged-in cookie.
Function Documentation
_get_additional_user_keys ($user)
Returns a list of meta keys to be (maybe) populated in wp_update_user().
The list of keys returned via this function are dependent on the presence of those keys in the user meta data to be set.
Since
3.3.0 private
Parameters
WP_User $user WP_User instance.
Returns
array List of user keys to be populated in wp_update_user().
Definition at line 1861 of file wp-includes/user.php.
References $keys, $user, and wp_get_user_contact_methods().
Referenced by wp_update_user().
_wp_get_user_contactmethods ($user = null)
The old private function for setting up user contact methods.
Use wp_get_user_contact_methods() instead.
Since
2.9.0 private
Parameters
WP_User $user Optional. WP_User object. Default null.
Returns
array Array of contact methods and their labels.
Definition at line 1908 of file wp-includes/user.php.
References $user, and wp_get_user_contact_methods().
add_user_meta ($user_id, $meta_key, $meta_value, $unique = false)
Add meta data field to a user.
Post meta data is called "Custom Fields" on the Administration Screens.
Since
3.0.0 int $user_id User ID. string $meta_key Metadata name. mixed $meta_value Metadata value. bool $unique Optional, default is false. Whether the same key should not be added. int|false Meta ID on success, false on failure.
Definition at line 669 of file wp-includes/user.php.
References $user_id, and add_metadata().
Referenced by WP_Internal_Pointers\dismiss_pointers_for_new_users().
check_password_reset_key ($key, $login)
Retrieves a user row based on password reset key and login.
A key is considered 'expired' if it exactly matches the value of the user_activation_key field, rather than being matched after going through the hashing process. This field is now hashed; old values are no longer accepted but have a different WP_Error code so good user feedback can be provided.
Since
3.1.0
wpdb $wpdb WordPress database object for queries. PasswordHash $wp_hasher Portable PHP password hashing framework instance.
Parameters
string $key Hash to validate sending user's password.
string $login The user login.
Returns
WP_User|WP_Error WP_User object on success, WP_Error object for invalid or expired keys.
Filter the expiration time of password reset keys.
Since
4.3.0
Parameters
int $expiration The expiration time in seconds.
Filter the return value of check_password_reset_key() when an old-style key is used.
Since
3.7.0 Previously plain-text keys were stored in the database.
4.3.0 Previously key hashes were stored without an expiration time.
Parameters
WP_Error $return A WP_Error object denoting an expired key. Return a WP_User object to validate the key.
int $user_id The matched user ID.
Definition at line 2026 of file wp-includes/user.php.
References $user_id, $wpdb, __, ABSPATH, apply_filters(), elseif, and WPINC.
clean_user_cache ($user)
Clean all user caches.
Since
3.0.0
4.4.0 'clean_user_cache' action was added.
Parameters
WP_User | int $user User object or ID to be cleaned from the cache
Fires immediately after the given user's cache is cleaned.
Since
4.4.0
Parameters
int $user_id User ID.
WP_User $user User object.
Definition at line 1167 of file wp-includes/user.php.
References $user, do_action(), and wp_cache_delete().
Referenced by delete_usermeta(), refresh_user_details(), update_user_status(), update_usermeta(), wp_delete_user(), and wpmu_delete_user().
count_many_users_posts ($users, $post_type = 'post', $public_only = false)
Number of posts written by a list of users.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $users Array of user IDs.
string | array $post_type Optional. Single post type or array of post types to check. Defaults to 'post'.
bool $public_only Optional. Only return counts for public posts. Defaults to false.
Returns
array Amount of posts each user has written.
Definition at line 317 of file wp-includes/user.php.
References $count, $id, $post_type, $wpdb, ARRAY_N, get_posts_by_author_sql(), and null.
Referenced by WP_Users_List_Table\display_rows().
count_user_posts ($userid, $post_type = 'post', $public_only = false)
Number of posts user has written.
Since
3.0.0
4.1.0 Added $post_type argument.
4.3.0 Added $public_only argument. Added the ability to pass an array of post types to $post_type.
wpdb $wpdb WordPress database abstraction object.
Parameters
int $userid User ID.
array | string $post_type Optional. Single post type or array of post types to count the number of posts for. Default 'post'.
bool $public_only Optional. Whether to only return counts for public posts. Default false.
Returns
string Number of posts the user has written in this post type.
Filter the number of posts a user has written.
Since
2.7.0
4.1.0 Added $post_type argument.
4.3.1 Added $public_only argument.
Parameters
int $count The user's post count.
int $userid User ID.
string | array $post_type Single post type or array of post types to count the number of posts for.
bool $public_only Whether to limit counted posts to public posts.
Definition at line 283 of file wp-includes/user.php.
References $count, $post_type, $wpdb, apply_filters(), and get_posts_by_author_sql().
Referenced by get_the_author_posts(), and get_usernumposts().
count_users ($strategy = 'time')
Count number of users who have each of the user roles.
Assumes there are neither duplicated nor orphaned capabilities meta_values. Assumes role names are unique phrases. Same assumption made by WP_User_Query::prepare_query() Using $strategy = 'time' this is CPU-intensive and should handle around 10^7 users. Using $strategy = 'memory' this is memory-intensive and should handle around 10^5 users, but see WP Bug #12257.
Since
3.0.0
4.4.0 The number of users with no role is now included in the none element.
wpdb $wpdb WordPress database abstraction object.
Parameters
string $strategy 'time' or 'memory'
Returns
array Includes a grand total and an array of counts indexed by role strings.
Definition at line 744 of file wp-includes/user.php.
References $count, $id, $name, $wpdb, ARRAY_N, get_current_blog_id(), is_multisite(), maybe_unserialize(), and wp_roles().
Referenced by WP_Users_List_Table\get_views(), and wp_version_check().
delete_user_meta ($user_id, $meta_key, $meta_value = '')
Remove metadata matching criteria from a user.
You can match based on the key, or key and value. Removing based on key and value, will keep from removing duplicate metadata with the same key. It also allows removing all metadata matching key, if needed.
Since
3.0.0 int $user_id User ID string $meta_key Metadata name. mixed $meta_value Optional. Metadata value. bool True on success, false on failure.
Definition at line 688 of file wp-includes/user.php.
References $user_id, and delete_metadata().
Referenced by delete_user_option(), WP_User\remove_all_caps(), and WP_User_Meta_Session_Tokens\update_sessions().
delete_user_option ($user_id, $option_name, $global = false)
Delete user option with global blog capability.
User options are just like user metadata except that they have support for global blog options. If the 'global' parameter is false, which it is by default it will prepend the WordPress table prefix to the option name.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $user_id User ID
string $option_name User option name.
bool $global Optional. Whether option name is global or blog specific. Default false (blog specific).
Returns
bool True on success, false on failure.
Definition at line 458 of file wp-includes/user.php.
References $user_id, $wpdb, and delete_user_meta().
Referenced by wpmu_create_user().
email_exists ($email)
Checks whether the given email exists.
Since
2.1.0
Parameters
string $email Email.
Returns
int|false The user's ID on success, and false on failure.
Definition at line 1213 of file wp-includes/user.php.
References $user.
Referenced by edit_user(), register_new_user(), wp_insert_user(), and wpmu_validate_user_signup().
get_blogs_of_user ($user_id, $all = false)
Get the blogs a user belongs to.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $user_id User ID
bool $all Whether to retrieve all blogs, or only blogs that are not marked as deleted, archived, or spam.
Returns
array A list of the user's blogs. An empty array if the user doesn't exist or belongs to no blogs.
Filter the list of blogs a user belongs to.
Since
MU
Parameters
array $blogs An array of blog objects belonging to the user.
int $user_id User ID.
bool $all Whether the returned blogs array should contain all blogs, including those marked 'deleted', 'archived', or 'spam'. Default false.
Definition at line 500 of file wp-includes/user.php.
References $blog, $blog_id, $blogs, $keys, $user_id, $wpdb, apply_filters(), get_blog_details(), get_current_blog_id(), get_option(), get_user_meta(), is_multisite(), object, and str_replace.
Referenced by _access_denied_splash(), choose_primary_blog(), WP_MS_Users_List_Table\column_blogs(), confirm_delete_users(), get_active_blog_for_user(), get_dashboard_url(), get_most_recent_post_of_user(), WP_Admin_Bar\initialize(), remove_user_from_blog(), wp_dashboard_quick_press(), wp_xmlrpc_server\wp_getUsersBlogs(), and wpmu_delete_user().
get_current_user_id ()
Get the current user's ID.
Since
MU
Returns
int The current user's ID
Definition at line 351 of file wp-includes/user.php.
References $user.
Referenced by WP_Posts_List_Table\__construct(), _access_denied_splash(), _count_posts_cache_key(), _wp_translate_postdata(), check_comment_flood_db(), GFLocking\check_lock(), GFLocking\check_lock_request(), choose_primary_blog(), WP_UnitTest_Factory_For_Blog\create_object(), delete_all_user_settings(), WP_Media_List_Table\display_rows(), edit_post(), edit_user(), WP_Internal_Pointers\enqueue_scripts(), WP_Canonical_UnitTestCase\generate_shared_fixtures(), get_adjacent_post(), get_all_user_settings(), get_dashboard_url(), get_edit_profile_url(), get_edit_user_link(), WP_Query\get_posts(), get_posts_by_author_sql(), get_user_option(), WP_Posts_List_Table\get_views(), WP_Admin_Bar\initialize(), is_blog_user(), GFLocking\is_locked(), is_site_admin(), is_super_admin(), is_user_member_of_blog(), new_user_email_admin_notice(), WP_Plugin_Install_List_Table\prepare_items(), WP_Posts_List_Table\prepare_items(), WP_Screen\render_meta_boxes_preferences(), GFLocking\request_lock(), GFLocking\set_lock(), setup_userdata(), WP_Users_List_Table\single_row(), WP_Posts_List_Table\single_row(), WP_Customize_Nav_Menu_Item_Setting\value_as_wp_post_nav_menu_item(), wp_admin_bar_dashboard_view_site_menu(), wp_admin_bar_my_account_item(), wp_admin_bar_my_account_menu(), wp_ajax_destroy_sessions(), wp_ajax_dismiss_wp_pointer(), wp_ajax_inline_save(), wp_ajax_save_user_color_scheme(), wp_ajax_save_wporg_username(), wp_ajax_update_welcome_panel(), wp_ajax_wp_remove_post_lock(), wp_count_posts(), wp_dashboard_quick_press(), wp_dashboard_recent_drafts(), wp_default_scripts(), wp_destroy_all_sessions(), wp_destroy_current_session(), wp_destroy_other_sessions(), wp_get_all_sessions(), wp_insert_link(), wp_insert_post(), wp_restore_post_revision(), wp_set_all_user_settings(), and wp_user_settings().
get_password_reset_key ($user)
Creates, stores, then returns a password reset key for user.
Since
4.4.0
wpdb $wpdb WordPress database abstraction object. PasswordHash $wp_hasher Portable PHP password hashing framework.
Parameters
WP_User $user User to retrieve password reset key for.
Returns
string|WP_Error Password reset key on success. WP_Error on error.
Fires before a new password is retrieved.
Since
1.5.0
Parameters
string $user_login The user login name.
Fires before a new password is retrieved.
Since
1.5.1
Parameters
string $user_login The user login name.
Filter whether to allow a password to be reset.
Since
2.7.0
Parameters
bool $allow Whether to allow the password to be reset. Default true.
int $user_data-,>ID The ID of the user attempting to reset a password.
Fires when a password reset key is generated.
Since
2.5.0
Parameters
string $user_login The username for the user.
string $key The generated password reset key.
Definition at line 1944 of file wp-includes/user.php.
References $user, $wpdb, __, ABSPATH, apply_filters(), do_action(), elseif, is_wp_error(), and WPINC.
Referenced by retrieve_password().
get_user_meta ($user_id, $key = '', $single = false)
Retrieve user meta field for a user.
Since
3.0.0 int $user_id User ID. string $key Optional. The meta key to retrieve. By default, returns data for all keys. bool $single Whether to return a single value. mixed Will be an array if $single is false. Will be value of meta data field if $single is true.
Definition at line 703 of file wp-includes/user.php.
References $user_id, and get_metadata().
Referenced by WP_User\__get(), WP_User\_init_caps(), add_user_to_blog(), choose_primary_blog(), WP_Internal_Pointers\enqueue_scripts(), get_active_blog_for_user(), get_blogs_of_user(), WP_User_Meta_Session_Tokens\get_sessions(), is_user_member_of_blog(), remove_user_from_blog(), WP_Screen\render_meta_boxes_preferences(), upgrade_160(), wp_ajax_dismiss_wp_pointer(), wp_ajax_save_user_color_scheme(), wp_update_user(), and wpmu_create_blog().
get_user_option ($option, $user = 0, $deprecated = '')
Retrieve user option that can be either per Site or per Network.
If the user ID is not given, then the current user will be used instead. If the user ID is given, then the user data will be retrieved. The filter for the result, will also pass the original option name and finally the user data object as the third parameter.
The option will first check for the per site name and then the per Network name.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $option User option name.
int $user Optional. User ID.
string $deprecated Use get_option() to check for an option in the options table.
Returns
mixed User option value on success, false on failure.
Filter a specific user option value.
The dynamic portion of the hook name, $option, refers to the user option name.
Since
2.5.0
Parameters
mixed $result Value for the user's option.
string $option Name of the option being retrieved.
WP_User $user WP_User object of the user whose option is being retrieved.
Definition at line 377 of file wp-includes/user.php.
References $deprecated, $option, $prefix, $user, $wpdb, _deprecated_argument(), apply_filters(), elseif, and get_current_user_id().
Referenced by _get_admin_bar_pref(), admin_color_scheme_picker(), default_password_nag(), default_password_nag_edit_user(), default_password_nag_handler(), display_plugins_table(), do_meta_boxes(), enqueue_comment_hotkeys_js(), get_all_user_settings(), get_hidden_columns(), get_hidden_meta_boxes(), WP_List_Table\get_items_per_page(), WP_Press_This\html(), install_plugins_favorites_form(), postbox_classes(), WP_Plugin_Install_List_Table\prepare_items(), WP_Screen\render_per_page_options(), WP_Screen\render_screen_meta(), GravityView_Support_Port\show_for_user(), user_can_richedit(), wp_ajax_query_themes(), wp_color_scheme_settings(), wp_dashboard_quick_press(), wp_edit_attachments_query_vars(), wp_edit_posts_query(), wp_initial_nav_menu_meta_boxes(), wp_nav_menu_setup(), wp_style_loader_src(), and wp_user_settings().
get_users ($args = array())
Retrieve list of users matching criteria.
Since
3.1.0
See also
WP_User_Query
Parameters
array $args Optional. Arguments to retrieve users. See {
See also
WP_User_Query::prepare_query()} for more information on accepted arguments.
Returns
array List of users.
Definition at line 477 of file wp-includes/user.php.
References wp_parse_args().
Referenced by WP_MS_Sites_List_Table\column_users(), confirm_delete_users(), populate_network(), wp_ajax_autocomplete_user(), wp_dropdown_users(), wp_xmlrpc_server\wp_getAuthors(), wp_xmlrpc_server\wp_getUsers(), wp_list_authors(), and wpmu_delete_blog().
is_user_member_of_blog ($user_id = 0, $blog_id = 0)
Find out whether a user is a member of a given blog.
Since
MU 1.1
Parameters
int $user_id Optional. The unique ID of the user. Defaults to the current user.
int $blog_id Optional. ID of the blog to check. Defaults to the current site.
Returns
bool
Definition at line 600 of file wp-includes/user.php.
References $blog, $blog_id, $keys, $user, $user_id, $wpdb, get_blog_details(), get_current_blog_id(), get_current_user_id(), get_user_meta(), and is_multisite().
Referenced by WP\handle_404(), is_blog_user(), wp_admin_bar_site_menu(), wp_set_all_user_settings(), and wp_user_settings().
register_new_user ($user_login, $user_email)
Handles registering a new user.
Since
2.5.0
Parameters
string $user_login User's username for logging in
string $user_email User's email address to send password and add
Returns
int|WP_Error Either user's ID or error on failure.
Filter the email address of a user being registered.
Since
2.1.0
Parameters
string $user_email The email address of the new user.
This filter is documented in wp-includes/user.php
Fires when submitting registration form data, before the user is created.
Since
2.1.0
Parameters
string $sanitized_user_login The submitted username after being sanitized.
string $user_email The submitted email.
WP_Error $errors Contains any errors with submitted username and email, e.g., an empty field, an invalid username or email, or an existing username or email.
Filter the errors encountered when a new user is being registered.
The filtered WP_Error object may, for example, contain errors for an invalid or existing username or email address. A WP_Error object should always returned, but may or may not contain errors.
If any errors are present in $errors, this will abort the user's registration.
Since
2.1.0
Parameters
WP_Error $errors A WP_Error object containing any errors encountered during registration.
string $sanitized_user_login User's username after it has been sanitized.
string $user_email User's email.
Fires after a new user registration has been recorded.
Since
4.4.0
Parameters
int $user_id ID of the newly registered user.
Definition at line 2139 of file wp-includes/user.php.
References $errors, $user_id, __, apply_filters(), do_action(), elseif, email_exists(), get_option(), is_email(), is_wp_error(), sanitize_user(), update_user_option(), username_exists(), validate_username(), and wp_create_user().
reset_password ($user, $new_pass)
Handles resetting the user's password.
Since
2.5.0
Parameters
object $user The user
string $new_pass New password for the user in plaintext
Fires before the user's password is reset.
Since
1.5.0
Parameters
object $user The user.
string $new_pass New user password.
Fires after the user's password is reset.
Since
4.4.0
Parameters
object $user The user.
string $new_pass New user password.
Definition at line 2105 of file wp-includes/user.php.
References $user, do_action(), and update_user_option().
sanitize_user_field ($field, $value, $user_id, $context)
Sanitize user field based on context.
Possible context values are: 'raw', 'edit', 'db', 'display', 'attribute' and 'js'. The 'display' context is used by default. 'attribute' and 'js' contexts are treated like 'display' when calling filters.
Since
2.3.0
Parameters
string $field The user Object field name.
mixed $value The user Object value.
int $user_id User ID.
string $context How to sanitize user fields. Looks for 'raw', 'edit', 'db', 'display', 'attribute' and 'js'.
Returns
mixed Sanitized value.
This filter is documented in wp-includes/post.php
Filter a user field value in the 'edit' context.
The dynamic portion of the hook name, $field, refers to the prefixed user field being filtered, such as 'user_login', 'user_email', 'first_name', etc.
Since
2.9.0
Parameters
mixed $value Value of the prefixed user field.
int $user_id User ID.
This filter is documented in wp-includes/post.php
Filter the value of a user field in the 'db' context.
The dynamic portion of the hook name, $field, refers to the prefixed user field being filtered, such as 'user_login', 'user_email', 'first_name', etc.
Since
2.9.0
Parameters
mixed $value Value of the prefixed user field.
This filter is documented in wp-includes/post.php
Filter the value of a user field in a standard context.
The dynamic portion of the hook name, $field, refers to the prefixed user field being filtered, such as 'user_login', 'user_email', 'first_name', etc.
Since
2.9.0
Parameters
mixed $value The user object value to sanitize.
int $user_id User ID.
string $context The context to filter within.
Definition at line 1045 of file wp-includes/user.php.
References $field, $user_id, $value, apply_filters(), elseif, esc_attr(), esc_html, esc_js(), and esc_url.
Referenced by WP_User\__get(), and sanitize_user_object().
setup_userdata ($for_user_id = '')
Set up global user vars.
Used by wp_set_current_user() for back compat. Might be deprecated in the future.
Since
2.0.4
string $user_login The user username for logging in object $userdata User data. int $user_level The level of the user int $user_ID The ID of the user string $user_email The email address of the user string $user_url The url in the user's profile string $user_identity The display name of the user
Parameters
int $for_user_id Optional. User ID to set up global data.
Definition at line 838 of file wp-includes/user.php.
References $user, $user_ID, get_current_user_id(), and null.
update_user_caches ($user)
Update all user caches.
Since
3.0.0
Parameters
object | WP_User $user User object to be cached
Returns
bool|null Returns false on failure.
Definition at line 1144 of file wp-includes/user.php.
References $user, and wp_cache_add().
Referenced by WP_User\get_data_by().
update_user_meta ($user_id, $meta_key, $meta_value, $prev_value = '')
Update user meta field based on user ID.
Use the $prev_value parameter to differentiate between meta fields with the same key and user ID.
If the meta field for the user does not exist, it will be added.
Since
3.0.0 int $user_id User ID. string $meta_key Metadata key. mixed $meta_value Metadata value. mixed $prev_value Optional. Previous value to check before removing. int|bool Meta ID if the key didn't exist, true on successful update, false on failure.
Definition at line 724 of file wp-includes/user.php.
References $user_id, and update_metadata().
Referenced by WP_User\add_cap(), add_new_user_to_blog(), WP_User\add_role(), add_user_to_blog(), choose_primary_blog(), get_active_blog_for_user(), populate_network(), WP_Plugin_Install_List_Table\prepare_items(), WP_User\remove_cap(), WP_User\remove_role(), remove_user_from_blog(), WP_Screen\render_meta_boxes_preferences(), WP_User\set_role(), set_screen_options(), WP_User_Meta_Session_Tokens\update_sessions(), WP_User\update_user_level_from_caps(), GravityView_Support_Port\update_user_meta_value(), update_user_option(), upgrade_160(), wp_ajax_dismiss_wp_pointer(), wp_ajax_save_user_color_scheme(), wp_ajax_save_wporg_username(), wp_ajax_update_welcome_panel(), wp_insert_user(), and wpmu_create_blog().
update_user_option ($user_id, $option_name, $newvalue, $global = false)
Update user option with global blog capability.
User options are just like user metadata except that they have support for global blog options. If the 'global' parameter is false, which it is by default it will prepend the WordPress table prefix to the option name.
Deletes the user option if $newvalue is empty.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $user_id User ID.
string $option_name User option name.
mixed $newvalue User option value.
bool $global Optional. Whether option name is global or blog specific. Default false (blog specific).
Returns
int|bool User meta ID if the option didn't exist, true on successful update, false on failure.
Definition at line 432 of file wp-includes/user.php.
References $user_id, $wpdb, and update_user_meta().
Referenced by default_password_nag_edit_user(), default_password_nag_handler(), delete_all_user_settings(), register_new_user(), reset_password(), wp_ajax_closed_postboxes(), wp_ajax_hidden_columns(), wp_ajax_meta_box_order(), wp_dashboard_quick_press(), wp_initial_nav_menu_meta_boxes(), wp_nav_menu_setup(), wp_set_all_user_settings(), and wp_user_settings().
username_exists ($username)
Checks whether the given username exists.
Since
2.0.0
Parameters
string $username Username.
Returns
int|false The user's ID on success, and false on failure.
Definition at line 1198 of file wp-includes/user.php.
References $user.
Referenced by edit_user(), register_new_user(), WP_Importer\set_user(), wp_insert_user(), wpmu_activate_signup(), wpmu_validate_blog_signup(), and wpmu_validate_user_signup().
validate_username ($username)
Checks whether a username is valid.
Since
2.0.1
4.4.0 Empty sanitized usernames are now considered invalid
Parameters
string $username Username.
Returns
bool Whether username given is valid
Filter whether the provided username is valid or not.
Since
2.0.1
Parameters
bool $valid Whether given username is valid.
string $username Username to check.
Definition at line 1229 of file wp-includes/user.php.
References apply_filters(), and sanitize_user().
Referenced by edit_user(), and register_new_user().
wp_authenticate_cookie ($user, $username, $password)
Authenticate the user using the WordPress auth cookie.
Since
2.8.0
string $auth_secure_cookie
Parameters
WP_User | WP_Error | null $user WP_User or WP_Error object from a previous callback. Default null.
string $username Username. If not empty, cancels the cookie authentication.
string $password Password. If not empty, cancels the cookie authentication.
Returns
WP_User|WP_Error WP_User on success, WP_Error on failure.
Definition at line 188 of file wp-includes/user.php.
References $_COOKIE, $user, $user_id, and __.
wp_authenticate_spam_check ($user)
For Multisite blogs, check if the authenticated user has been marked as a spammer, or if the user's primary blog has been marked as spam.
Since
3.7.0
Parameters
WP_User | WP_Error | null $user WP_User or WP_Error object from a previous callback. Default null.
Returns
WP_User|WP_Error WP_User on success, WP_Error if the user is considered a spammer.
Filter whether the user has been marked as a spammer.
Since
3.7.0
Parameters
bool $spammed Whether the user is considered a spammer.
WP_User $user User to check against.
Definition at line 223 of file wp-includes/user.php.
References $user, __, apply_filters(), is_multisite(), and is_user_spammy().
wp_authenticate_username_password ($user, $username, $password)
Authenticate a user, confirming the username and password are valid.
Since
2.8.0
Parameters
WP_User | WP_Error | null $user WP_User or WP_Error object from a previous callback. Default null.
string $username Username for authentication.
string $password Password for authentication.
Returns
WP_User|WP_Error WP_User on success, WP_Error on failure.
Filter whether the given user can be authenticated with the provided $password.
Since
2.5.0
Parameters
WP_User | WP_Error $user WP_User or WP_Error object if a previous callback failed authentication.
string $password Password to check against the user.
Definition at line 116 of file wp-includes/user.php.
References $user, __, apply_filters(), is_wp_error(), and wp_lostpassword_url().
wp_create_user ($username, $password, $email = '')
A simpler way of inserting a user into the database.
Creates a new user with just the username, password, and email. For more complex user creation use {
See also
wp_insert_user()} to specify more information.
Since
2.0.0
See also
wp_insert_user() More complete way to create a new user
Parameters
string $username The user's username.
string $password The user's password.
string $email Optional. The user's email. Default empty.
Returns
int|WP_Error The newly created user's ID or a WP_Error object if the user could not be created.
Definition at line 1840 of file wp-includes/user.php.
References wp_insert_user(), and wp_slash().
Referenced by create_user(), register_new_user(), and wpmu_create_user().
wp_destroy_all_sessions ()
Remove all session tokens for the current user from the database.
Since
4.0.0
Definition at line 2303 of file wp-includes/user.php.
References get_current_user_id(), and WP_Session_Tokens\get_instance().
wp_destroy_current_session ()
Remove the current session token from the database.
Since
4.0.0
Definition at line 2277 of file wp-includes/user.php.
References get_current_user_id(), WP_Session_Tokens\get_instance(), and wp_get_session_token().
wp_destroy_other_sessions ()
Remove all but the current session token for the current user for the database.
Since
4.0.0
Definition at line 2290 of file wp-includes/user.php.
References get_current_user_id(), WP_Session_Tokens\get_instance(), and wp_get_session_token().
wp_dropdown_users ($args = '')
Create dropdown HTML content of users.
The content can either be displayed, which it is by default or retrieved by setting the 'echo' argument. The 'include' and 'exclude' arguments do not need to be used; all users will be displayed in that case. Only one can be used, either 'include' or 'exclude', but not both.
The available arguments are as follows:
Since
2.3.0
4.5.0 Added the 'display_name_with_login' value for 'show'.
int $blog_id
Parameters
array | string $args { Optional. Array or string of arguments to generate a drop-down of users. {
See also
WP_User_Query::prepare_query() for additional available arguments.
string $show_option_all Text to show as the drop-down default (all). Default empty. string $show_option_none Text to show as the drop-down default when no users were found. Default empty. int|string $option_none_value Value to use for $show_option_non when no users were found. Default -1. string $hide_if_only_one_author Whether to skip generating the drop-down if only one user was found. Default empty. string $orderby Field to order found users by. Accepts user fields. Default 'display_name'. string $order Whether to order users in ascending or descending order. Accepts 'ASC' (ascending) or 'DESC' (descending). Default 'ASC'. array|string $include Array or comma-separated list of user IDs to include. Default empty. array|string $exclude Array or comma-separated list of user IDs to exclude. Default empty. bool|int $multi Whether to skip the ID attribute on the 'select' element. Accepts 1|true or 0|false. Default 0|false. string $show User data to display. If the selected item is empty then the 'user_login' will be displayed in parentheses. Accepts any user field, or 'display_name_with_login' to show the display name with user_login in parentheses. Default 'display_name'. int|bool $echo Whether to echo or return the drop-down. Accepts 1|true (echo) or 0|false (return). Default 1|true. int $selected Which user ID should be selected. Default 0. bool $include_selected Whether to always include the selected user ID in the drop- down. Default false. string $name Name attribute of select element. Default 'user'. string $id ID attribute of the select element. Default is the value of $name. string $class Class attribute of the select element. Default empty. int $blog_id ID of blog (Multisite only). Default is ID of the current blog. string $who Which type of users to query. Accepts only an empty string or 'authors'. Default empty. }
Returns
string String of HTML content.
Filter the query arguments for the user drop-down.
Since
4.4.0
Parameters
array $query_args The query arguments for wp_dropdown_users().
array $r The default arguments for wp_dropdown_users().
Filter the wp_dropdown_users() HTML output.
Since
2.3.0
Parameters
string $output HTML output generated by wp_dropdown_users().
Definition at line 919 of file wp-includes/user.php.
References $GLOBALS, $id, $name, $output, $user, _x, apply_filters(), elseif, esc_attr(), esc_html, get_query_var(), get_users(), if, is_author(), selected(), wp_array_slice_assoc(), and wp_parse_args().
Referenced by WP_Posts_List_Table\inline_edit(), and post_author_meta_box().
wp_get_all_sessions ()
Retrieve a list of sessions for the current user.
Since
4.0.0
Returns
array Array of sessions.
Definition at line 2267 of file wp-includes/user.php.
References get_current_user_id(), and WP_Session_Tokens\get_instance().
wp_get_password_hint ()
Gets the text suggesting how to create strong passwords.
Since
4.1.0
Returns
string The password hint text.
Filter the text describing the site's password complexity policy.
Since
4.1.0
Parameters
string $hint The password hint text.
Definition at line 1919 of file wp-includes/user.php.
References __, and apply_filters().
wp_get_session_token ()
Retrieve the current session token from the logged_in cookie.
Since
4.0.0
Returns
string Token.
Definition at line 2256 of file wp-includes/user.php.
Referenced by wp_ajax_destroy_sessions(), wp_destroy_current_session(), and wp_destroy_other_sessions().
wp_get_user_contact_methods ($user = null)
Set up the user contact methods.
Default contact methods were removed in 3.6. A filter dictates contact methods.
Since
3.7.0
Parameters
WP_User $user Optional. WP_User object.
Returns
array Array of contact methods and their labels.
Filter the user contact methods.
Since
2.9.0
Parameters
array $methods Array of contact methods and their labels.
WP_User $user WP_User object.
Definition at line 1876 of file wp-includes/user.php.
References $user, __, apply_filters(), and get_site_option().
Referenced by _get_additional_user_keys(), _wp_get_user_contactmethods(), edit_user(), and wp_insert_user().
wp_get_users_with_no_role ()
Get the user IDs of all users with no role on this site.
This function returns an empty array when used on Multisite.
Since
4.4.0
Returns
array Array of user IDs.
Definition at line 2317 of file wp-includes/user.php.
References $prefix, $wpdb, is_multisite(), and wp_roles().
Referenced by WP_Users_List_Table\prepare_items().
wp_insert_user ($userdata)
Insert a user into the database.
Most of the $userdata array fields have filters associated with the values. Exceptions are 'ID', 'rich_editing', 'comment_shortcuts', 'admin_color', 'use_ssl', 'user_registered', and 'role'. The filters have the prefix 'pre_user_' followed by the field name. An example using 'description' would have the filter called, 'pre_user_description' that can be hooked into.
Since
2.0.0
3.6.0 The aim, jabber, and yim fields were removed as default user contact methods for new installs. See wp_get_user_contact_methods().
wpdb $wpdb WordPress database abstraction object.
Parameters
array | object | WP_User $userdata { An array, object, or WP_User object of user data arguments.
int $ID User ID. If supplied, the user will be updated. string $user_pass The plain-text user password. string $user_login The user's login username. string $user_nicename The URL-friendly user name. string $user_url The user URL. string $user_email The user email address. string $display_name The user's display name. Default is the user's username. string $nickname The user's nickname. Default is the user's username. string $first_name The user's first name. For new users, will be used to build the first part of the user's display name if $display_name is not specified. string $last_name The user's last name. For new users, will be used to build the second part of the user's display name if $display_name is not specified. string $description The user's biographical description. string|bool $rich_editing Whether to enable the rich-editor for the user. False if not empty. string|bool $comment_shortcuts Whether to enable comment moderation keyboard shortcuts for the user. Default false. string $admin_color Admin color scheme for the user. Default 'fresh'. bool $use_ssl Whether the user should always access the admin over https. Default false. string $user_registered Date the user registered. Format is 'Y-m-d H:i:s'. string|bool $show_admin_bar_front Whether to display the Admin Bar for the user on the site's frontend. Default true. string $role User's role. }
Returns
int|WP_Error The newly created user's ID or a WP_Error object if the user could not be created.
Filter a username after it has been sanitized.
This filter is called before the user is created or updated.
Since
2.0.3
Parameters
string $sanitized_user_login Username after it has been sanitized.
Filter the list of blacklisted usernames.
Since
4.4.0
Parameters
array $usernames Array of blacklisted usernames.
Filter a user's nicename before the user is created or updated.
Since
2.0.3
Parameters
string $user_nicename The user's nicename.
Filter a user's URL before the user is created or updated.
Since
2.0.3
Parameters
string $raw_user_url The user's URL.
Filter a user's email before the user is created or updated.
Since
2.0.3
Parameters
string $raw_user_email The user's email.
Filter a user's nickname before the user is created or updated.
Since
2.0.3
Parameters
string $nickname The user's nickname.
Filter a user's first name before the user is created or updated.
Since
2.0.3
Parameters
string $first_name The user's first name.
Filter a user's last name before the user is created or updated.
Since
2.0.3
Parameters
string $last_name The user's last name.
Filter a user's display name before the user is created or updated.
Since
2.0.3
Parameters
string $display_name The user's display name.
Filter a user's description before the user is created or updated.
Since
2.0.3
Parameters
string $description The user's description.
Filter a user's meta values and keys before the user is created or updated.
Does not include contact methods. These are added using wp_get_user_contact_methods($user).
Since
4.4.0
Parameters
array $meta { Default meta values and keys for the user.
string $nickname The user's nickname. Default is the user's username. string $first_name The user's first name. string $last_name The user's last name. string $description The user's description. bool $rich_editing Whether to enable the rich-editor for the user. False if not empty. bool $comment_shortcuts Whether to enable keyboard shortcuts for the user. Default false. string $admin_color The color scheme for a user's admin screen. Default 'fresh'. int|bool $use_ssl Whether to force SSL on the user's admin area. 0|false if SSL is not forced. bool $show_admin_bar_front Whether to show the admin bar on the front end for the user. Default true. }
Parameters
WP_User $user User object.
bool $update Whether the user is being updated rather than created.
Fires immediately after an existing user is updated.
Since
2.0.0
Parameters
int $user_id User ID.
object $old_user_data Object containing user's data prior to update.
Fires immediately after a new user is registered.
Since
1.5.0
Parameters
int $user_id User ID.
Definition at line 1294 of file wp-includes/user.php.
References $description, $ID, $update, $user, $user_id, $value, $wpdb, __, _x, apply_filters(), do_action(), elseif, email_exists(), get_option(), sanitize_title(), sanitize_user(), update_user_meta(), username_exists(), wp_cache_delete(), wp_get_user_contact_methods(), and wp_unslash().
Referenced by GV_UnitTest_Factory_For_User\create_object(), WP_UnitTest_Factory_For_User\create_object(), edit_user(), wp_create_user(), and wp_update_user().
wp_send_new_user_notifications ($user_id, $notify = 'both')
Initiate email notifications related to the creation of new users.
Notifications are sent both to the site admin and to the newly created user.
Since
4.4.0
Parameters
int $user_id ID of the newly created user.
string $notify Optional. Type of notification that should happen. Accepts 'admin' or an empty string (admin only), or 'both' (admin and user). Default 'both'.
Definition at line 2245 of file wp-includes/user.php.
References $user_id, and null.
wp_signon ($credentials = array(), $secure_cookie = '')
Authenticate and log in a user with remember capability.
The credentials is an array that has 'user_login', 'user_password', and 'remember' indices. If the credentials is not given, then the log in form will be assumed and used if set.
The various authentication cookies will be set by this function and will be set for a longer period depending on if the 'remember' credential is set to true.
Since
2.5.0
string $auth_secure_cookie
Parameters
array $credentials Optional. User info in order to sign on.
string | bool $secure_cookie Optional. Whether to use secure cookie.
Returns
WP_User|WP_Error WP_User on success, WP_Error on failure.
Fires before the user is authenticated.
The variables passed to the callbacks are passed by reference, and can be modified by callback functions.
Since
1.5.1
Parameters
string $user_login Username, passed by reference.
string $user_password User password, passed by reference.
Filter whether to use a secure sign-on cookie.
Since
3.1.0
Parameters
bool $secure_cookie Whether to use a secure sign-on cookie.
array $credentials { Array of entered sign-on data.
string $user_login Username. string $user_password Password entered. bool $remember Whether to 'remember' the user. Increases the time that the cookie will be kept. Default false. }
Fires after the user has successfully logged in.
Since
1.5.0
Parameters
string $user_login Username.
WP_User $user WP_User object of the logged-in user.
Definition at line 28 of file wp-includes/user.php.
References $user, add_filter(), apply_filters(), do_action(), do_action_ref_array(), is_ssl(), and is_wp_error().
wp_update_user ($userdata)
Update a user in the database.
It is possible to update a user's password by specifying the 'user_pass' value in the $userdata parameter array.
If current user's password is being updated, then the cookies will be cleared.
Since
2.0.0
See also
wp_insert_user() For what fields can be set in $userdata.
Parameters
mixed $userdata An array of user data or a user object of type stdClass or WP_User.
Returns
int|WP_Error The updated user's ID or a WP_Error object if the user could not be updated.
Filter whether to send the password change email.
Since
4.3.0
See also
wp_insert_user() For $user and $userdata fields.
Parameters
bool $send Whether to send the email.
array $user The original user array.
array $userdata The updated user array.
Filter whether to send the email change email.
Since
4.3.0
See also
wp_insert_user() For $user and $userdata fields.
Parameters
bool $send Whether to send the email.
array $user The original user array.
array $userdata The updated user array.
Filter the contents of the email sent when the user's password is changed.
Since
4.3.0
Parameters
array $pass_change_email { Used to build wp_mail(). string $to The intended recipients. Add emails in a comma separated string. string $subject The subject of the email. string $message The content of the email. The following strings have a special meaning and will get replaced dynamically:
###USERNAME### The current user's username.
###ADMIN_EMAIL### The admin email in case this was unexpected.
###EMAIL### The old email.
###SITENAME### The name of the site.
###SITEURL### The URL to the site. string $headers Headers. Add headers in a newline (
) separated string. }
array $user The original user array.
array $userdata The updated user array.
Filter the contents of the email sent when the user's email is changed.
Since
4.3.0
Parameters
array $email_change_email { Used to build wp_mail(). string $to The intended recipients. string $subject The subject of the email. string $message The content of the email. The following strings have a special meaning and will get replaced dynamically:
###USERNAME### The current user's username.
###ADMIN_EMAIL### The admin email in case this was unexpected.
###EMAIL### The old email.
###SITENAME### The name of the site.
###SITEURL### The URL to the site. string $headers Headers. }
array $user The original user array.
array $userdata The updated user array.
This filter is documented in wp-includes/pluggable.php
Definition at line 1620 of file wp-includes/user.php.
References $blog_name, $current_user, $ID, $user, $user_id, __, _get_additional_user_keys(), add_magic_quotes(), apply_filters(), elseif, get_option(), get_user_meta(), home_url(), is_wp_error(), str_replace, wp_cache_delete(), wp_insert_user(), and wp_specialchars_decode().
Referenced by edit_user(), GravityView_Edit_Entry_User_Registration\restore_display_name(), WP_UnitTest_Factory_For_User\update_object(), and wp_xmlrpc_server\wp_editProfile().
wp_validate_logged_in_cookie ($user_id)
Validate the logged-in cookie.
Checks the logged-in cookie if the previous auth cookie could not be validated and parsed.
This is a callback for the determine_current_user filter, rather than API.
Since
3.9.0
Parameters
int | bool $user_id The user ID (or false) as received from the determine_current_user filter.
Returns
int|false User ID if validated, false otherwise. If a user ID from an earlier filter callback is received, that value is returned.
Definition at line 256 of file wp-includes/user.php.
References $_COOKIE, $user_id, is_blog_admin(), and is_network_admin().