GravityView: nav-menu.php File Reference
wp-includes/nav-menu.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_is_valid_nav_menu_item ($item)
Return if a menu item is valid.
_sort_nav_menu_items ($a, $b)
Sort menu items by the desired key.
_wp_auto_add_pages_to_menu ($new_status, $old_status, $post)
Automatically add newly published page objects to menus with that as an option.
_wp_delete_post_menu_item ($object_id=0)
Callback for handling a menu item when its original object is deleted.
_wp_delete_tax_menu_item ($object_id=0, $tt_id, $taxonomy)
Serves as a callback for handling a menu item when its original object is deleted.
get_nav_menu_locations ()
Returns an array with the registered navigation menu locations and the menu assigned to it.
get_registered_nav_menus ()
Returns an array of all registered navigation menus in a theme.
has_nav_menu ($location)
Whether a registered nav menu location has a menu assigned to it.
is_nav_menu ($menu)
Check if the given ID is a navigation menu.
is_nav_menu_item ($menu_item_id=0)
Determine whether the given ID is a nav menu item.
register_nav_menu ($location, $description)
Register a navigation menu for a theme.
register_nav_menus ($locations=array())
Register navigation menus for a theme.
unregister_nav_menu ($location)
Unregisters a navigation menu for a theme.
wp_create_nav_menu ($menu_name)
Create a Navigation Menu.
wp_delete_nav_menu ($menu)
Delete a Navigation Menu.
wp_get_associated_nav_menu_items ($object_id=0, $object_type= 'post_type', $taxonomy= '')
Get the menu items associated with a particular object.
wp_get_nav_menu_items ($menu, $args=array())
Return all menu items of a navigation menu.
wp_get_nav_menu_object ($menu)
Returns a navigation menu object.
wp_get_nav_menus ($args=array())
Returns all navigation menu objects.
wp_setup_nav_menu_item ($menu_item)
Decorates a menu item object with the shared navigation menu item properties.
wp_update_nav_menu_item ($menu_id=0, $menu_item_db_id=0, $menu_item_data=array())
Save the properties of a menu item or create a new one.
wp_update_nav_menu_object ($menu_id=0, $menu_data=array())
Save the properties of a menu or create a new menu with those properties.
Function Documentation
_is_valid_nav_menu_item ($item)
Return if a menu item is valid.
3.2.0 private object $item The menu item to check. bool False if invalid, otherwise true.
Definition at line 592 of file wp-includes/nav-menu.php.
_sort_nav_menu_items ($a, $b)
Sort menu items by the desired key.
Since
3.0.0 private
string $_menu_item_sort_prop
Parameters
object $a The first object to compare
object $b The second object to compare
Returns
int -1, 0, or 1 if $a is considered to be respectively less than, equal to, or greater than $b.
Definition at line 561 of file wp-includes/nav-menu.php.
References elseif.
_wp_auto_add_pages_to_menu ($new_status, $old_status, $post)
Automatically add newly published page objects to menus with that as an option.
Since
3.0.0 private
Parameters
string $new_status The new status of the post object.
string $old_status The old status of the post object.
object $post The post object being transitioned from one status to another.
Definition at line 963 of file wp-includes/nav-menu.php.
References $post, get_option(), wp_get_nav_menu_items(), and wp_update_nav_menu_item().
_wp_delete_post_menu_item ($object_id = 0)
Callback for handling a menu item when its original object is deleted.
Since
3.0.0 private
Parameters
int $object_id The ID of the original object being trashed.
Definition at line 923 of file wp-includes/nav-menu.php.
References wp_delete_post(), and wp_get_associated_nav_menu_items().
_wp_delete_tax_menu_item ($object_id = 0, $tt_id, $taxonomy)
Serves as a callback for handling a menu item when its original object is deleted.
Since
3.0.0 private
Parameters
int $object_id Optional. The ID of the original object being trashed. Default 0.
int $tt_id Term taxonomy ID. Unused.
string $taxonomy Taxonomy slug.
Definition at line 943 of file wp-includes/nav-menu.php.
References wp_delete_post(), and wp_get_associated_nav_menu_items().
get_nav_menu_locations ()
Returns an array with the registered navigation menu locations and the menu assigned to it.
Since
3.0.0
Returns
array
Definition at line 151 of file wp-includes/nav-menu.php.
References $locations, and get_theme_mod().
Referenced by _wp_check_split_nav_menu_terms(), has_nav_menu(), wp_delete_nav_menu(), and wp_nav_menu().
get_registered_nav_menus ()
Returns an array of all registered navigation menus in a theme.
Since
3.0.0
array $_wp_registered_nav_menus
Returns
array
Definition at line 137 of file wp-includes/nav-menu.php.
Referenced by WP_Customize_Nav_Menu_Control\content_template(), WP_Customize_Nav_Menus\customize_register(), and has_nav_menu().
has_nav_menu ($location)
Whether a registered nav menu location has a menu assigned to it.
Since
3.0.0
Parameters
string $location Menu location identifier.
Returns
bool Whether location has a menu.
Filter whether a nav menu is assigned to the specified location.
Since
4.3.0
Parameters
bool $has_nav_menu Whether there is a menu assigned to a location.
string $location Menu location.
Definition at line 164 of file wp-includes/nav-menu.php.
References $location, $locations, apply_filters(), get_nav_menu_locations(), and get_registered_nav_menus().
is_nav_menu ($menu)
Check if the given ID is a navigation menu.
Returns true if it is; false otherwise.
Since
3.0.0
Parameters
int | string $menu The menu to check (ID, slug, or name).
Returns
bool Whether the menu exists.
Definition at line 62 of file wp-includes/nav-menu.php.
References $menu, is_wp_error(), and wp_get_nav_menu_object().
Referenced by wp_get_nav_menu_to_edit(), and wp_save_nav_menu_items().
is_nav_menu_item ($menu_item_id = 0)
Determine whether the given ID is a nav menu item.
Since
3.0.0
Parameters
int $menu_item_id The ID of the potential nav menu item.
Returns
bool Whether the given ID is that of a nav menu item.
Definition at line 192 of file wp-includes/nav-menu.php.
References get_post_type(), and is_wp_error().
Referenced by wp_get_associated_nav_menu_items(), wp_nav_menu_update_menu_items(), and wp_update_nav_menu_item().
register_nav_menu ($location, $description)
Register a navigation menu for a theme.
Since
3.0.0
Parameters
string $location Menu location identifier, like a slug.
string $description Menu location descriptive text.
Definition at line 125 of file wp-includes/nav-menu.php.
References $description, $location, and register_nav_menus().
Referenced by twentythirteen_setup(), and twentytwelve_setup().
register_nav_menus ($locations = array())
Register navigation menus for a theme.
Since
3.0.0
array $_wp_registered_nav_menus
Parameters
array $locations Associative array of menu location identifiers (like a slug) and descriptive text.
Definition at line 88 of file wp-includes/nav-menu.php.
References $locations, and add_theme_support().
Referenced by register_nav_menu().
unregister_nav_menu ($location)
Unregisters a navigation menu for a theme.
array $_wp_registered_nav_menus
Parameters
string $location The menu location identifier.
Returns
bool True on success, false on failure.
Definition at line 104 of file wp-includes/nav-menu.php.
References $location, and _remove_theme_support().
wp_create_nav_menu ($menu_name)
Create a Navigation Menu.
Since
3.0.0
Parameters
string $menu_name Menu name.
Returns
int|WP_Error Menu ID on success, WP_Error object on failure.
Definition at line 204 of file wp-includes/nav-menu.php.
References wp_update_nav_menu_object().
wp_delete_nav_menu ($menu)
Delete a Navigation Menu.
Since
3.0.0
Parameters
string $menu Menu ID, slug, or name.
Returns
bool|WP_Error True on success, false or WP_Error object on failure.
Fires after a navigation menu has been successfully deleted.
Since
3.0.0
Parameters
int $term_id ID of the deleted menu.
Definition at line 216 of file wp-includes/nav-menu.php.
References $location, $locations, $menu, do_action(), get_nav_menu_locations(), get_objects_in_term(), is_wp_error(), set_theme_mod(), wp_delete_post(), wp_delete_term(), and wp_get_nav_menu_object().
Referenced by WP_Customize_Nav_Menu_Setting\update().
wp_get_associated_nav_menu_items ($object_id = 0, $object_type = 'post_type', $taxonomy = '')
Get the menu items associated with a particular object.
Since
3.0.0
Parameters
int $object_id The ID of the original object.
string $object_type The type of object, such as "taxonomy" or "post_type."
string $taxonomy If $object_type is "taxonomy", $taxonomy is the name of the tax that $object_id belongs to
Returns
array The array of menu item IDs; empty array if none;
Definition at line 879 of file wp-includes/nav-menu.php.
References $menu_items, elseif, get_post_meta(), and is_nav_menu_item().
Referenced by _wp_delete_post_menu_item(), and _wp_delete_tax_menu_item().
wp_get_nav_menu_items ($menu, $args = array())
Return all menu items of a navigation menu.
Since
3.0.0
string $_menu_item_sort_prop array $fetched
Parameters
string $menu Menu name, ID, or slug.
array $args Optional. Arguments to pass to {
See also
get_posts()}.
Returns
false|array $items Array of menu items, otherwise false.
Filter the navigation menu items being returned.
Since
3.0.0
Parameters
array $items An array of menu item post objects.
object $menu The menu object.
array $args An array of arguments used to retrieve menu item objects.
Definition at line 608 of file wp-includes/nav-menu.php.
References $GLOBALS, $i, $menu, $post_type, ARRAY_A, elseif, get_objects_in_term(), get_post_meta(), get_posts(), get_terms(), is_admin(), is_wp_error(), wp_get_nav_menu_object(), wp_parse_args(), and wp_using_ext_object_cache().
Referenced by _wp_auto_add_pages_to_menu(), WP_Customize_Nav_Menus\customize_register(), wp_get_nav_menu_to_edit(), wp_nav_menu(), wp_nav_menu_update_menu_items(), and wp_update_nav_menu_item().
wp_get_nav_menu_object ($menu)
Returns a navigation menu object.
Since
3.0.0
Parameters
string $menu Menu ID, slug, or name - or the menu object.
Returns
object|false False if $menu param isn't supplied or term does not exist, menu object if successful.
Filter the nav_menu term retrieved for wp_get_nav_menu_object().
Since
4.3.0
Parameters
object | false $menu_obj Term from nav_menu taxonomy, or false if nothing had been found.
string $menu The menu ID, slug, or name passed to wp_get_nav_menu_object().
Definition at line 18 of file wp-includes/nav-menu.php.
References $menu, apply_filters(), get_term(), get_term_by(), and is_wp_error().
Referenced by is_nav_menu(), WP_Customize_Nav_Menu_Setting\value(), WP_Nav_Menu_Widget\widget(), wp_delete_nav_menu(), wp_get_nav_menu_items(), wp_get_nav_menu_to_edit(), wp_nav_menu(), wp_update_nav_menu_item(), and wp_update_nav_menu_object().
wp_get_nav_menus ($args = array())
Returns all navigation menu objects.
Since
3.0.0
4.1.0 Default value of the 'orderby' argument was changed from 'none' to 'name'.
Parameters
array $args Optional. Array of arguments passed on to {
See also
get_terms()}. Default empty array.
Returns
array Menu objects.
Filter the navigation menu objects being returned.
Since
3.0.0
See also
get_terms()
Parameters
array $menus An array of menu objects.
array $args An array of arguments used to retrieve menu objects.
Definition at line 532 of file wp-includes/nav-menu.php.
References apply_filters(), get_terms(), and wp_parse_args().
Referenced by WP_Customize_Nav_Menus\customize_register(), WP_Customize_Nav_Menus\enqueue_scripts(), export_wp(), WP_Nav_Menu_Widget\form(), wp_nav_menu(), and wp_nav_menu_update_menu_items().
wp_setup_nav_menu_item ($menu_item)
Decorates a menu item object with the shared navigation menu item properties.
Properties:
ID: The term_id if the menu item represents a taxonomy term.
attr_title: The title attribute of the link element for this menu item.
classes: The array of class attribute values for the link element of this menu item.
db_id: The DB ID of this item as a nav_menu_item object, if it exists (0 if it doesn't exist).
description: The description of this menu item.
menu_item_parent: The DB ID of the nav_menu_item that is this item's menu parent, if any. 0 otherwise.
object: The type of object originally represented, such as "category," "post", or "attachment."
object_id: The DB ID of the original object this menu item represents, e.g. ID for posts and term_id for categories.
post_parent: The DB ID of the original object's parent object, if any (0 otherwise).
post_title: A "no title" label if menu item represents a post that lacks a title.
target: The target attribute of the link element for this menu item.
title: The title of this menu item.
type: The family of objects originally represented, such as "post_type" or "taxonomy."
type_label: The singular label used to describe this type of menu item.
url: The URL to which this menu item points.
xfn: The XFN relationship expressed in the link of this menu item.
_invalid: Whether the menu item represents an object that no longer exists.
Since
3.0.0
Parameters
object $menu_item The menu item to modify.
Returns
object $menu_item The menu item with standard menu item properties.
This filter is documented in wp-includes/post-template.php
Filter a navigation menu item's title attribute.
Since
3.0.0
Parameters
string $item_title The menu item title attribute.
Filter a navigation menu item's description.
Since
3.0.0
Parameters
string $description The menu item description.
This filter is documented in wp-includes/nav-menu.php
This filter is documented in wp-includes/nav-menu.php
Filter a navigation menu item object.
Since
3.0.0
Parameters
object $menu_item The menu item object.
Definition at line 721 of file wp-includes/nav-menu.php.
References __, apply_filters(), elseif, get_permalink(), get_post(), get_post_meta(), get_post_type_archive_link(), get_post_type_object(), get_taxonomy(), get_term_field(), get_term_link(), is_wp_error(), and wp_trim_words().
Referenced by WP_Customize_Nav_Menu_Item_Setting\value(), and wp_ajax_add_menu_item().
wp_update_nav_menu_item ($menu_id = 0, $menu_item_db_id = 0, $menu_item_data = array())
Save the properties of a menu item or create a new one.
Since
3.0.0
Parameters
int $menu_id The ID of the menu. Required. If "0", makes the menu item a draft orphan.
int $menu_item_db_id The ID of the menu item. If "0", creates a new menu item.
array $menu_item_data The menu item's data.
Returns
int|WP_Error The menu item's database ID or WP_Error object on failure.
Fires immediately after a new navigation menu item has been added.
Since
4.4.0
See also
wp_update_nav_menu_item()
Parameters
int $menu_id ID of the updated menu.
int $menu_item_db_id ID of the new menu item.
array $args An array of arguments used to update/add the menu item.
Fires after a navigation menu item has been updated.
Since
3.0.0
See also
wp_update_nav_menu_item()
Parameters
int $menu_id ID of the updated menu.
int $menu_item_db_id ID of the updated menu item.
array $args An array of arguments used to update a menu item.
Definition at line 354 of file wp-includes/nav-menu.php.
References $menu, $menu_items, $post, $update, __, delete_post_meta(), do_action(), elseif, esc_url_raw(), get_post(), get_post_field(), get_post_meta(), get_post_type_object(), get_term_field(), is_nav_menu_item(), is_object_in_term(), is_wp_error(), sanitize_key(), update_post_meta(), wp_get_nav_menu_items(), wp_get_nav_menu_object(), wp_insert_post(), wp_parse_args(), wp_set_object_terms(), and wp_update_post().
Referenced by _wp_auto_add_pages_to_menu(), WP_Customize_Nav_Menu_Item_Setting\update(), wp_nav_menu_update_menu_items(), and wp_save_nav_menu_items().
wp_update_nav_menu_object ($menu_id = 0, $menu_data = array())
Save the properties of a menu or create a new menu with those properties.
Since
3.0.0
Parameters
int $menu_id The ID of the menu or "0" to create a new menu.
array $menu_data The array of menu data.
Returns
int|WP_Error Menu ID on success, WP_Error object on failure.
Fires after a navigation menu is successfully created.
Since
3.0.0
Parameters
int $term_id ID of the new menu.
array $menu_data An array of menu data.
Fires after a navigation menu has been successfully updated.
Since
3.0.0
Parameters
int $menu_id ID of the updated menu.
array $menu_data An array of menu data.
Definition at line 261 of file wp-includes/nav-menu.php.
References __, do_action(), esc_html, get_term_by(), is_wp_error(), null, wp_get_nav_menu_object(), wp_insert_term(), and wp_update_term().
Referenced by WP_Customize_Nav_Menu_Setting\update(), and wp_create_nav_menu().