GravityView: category.php File Reference
wp-includes/category.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_make_cat_compat (&$category)
Update category structure to old pre 2.3 from new taxonomy structure.
cat_is_ancestor_of ($cat1, $cat2)
Check if a category is an ancestor of another category.
clean_category_cache ($id)
Remove the category cache data based on ID.
get_cat_ID ($cat_name)
Retrieve the ID of a category from its name.
get_cat_name ($cat_id)
Retrieve the name of a category from its ID.
get_categories ($args= '')
Retrieve list of category objects.
get_category ($category, $output=OBJECT, $filter= 'raw')
Retrieves category data given a category ID or category object.
get_category_by_path ($category_path, $full_match=true, $output=OBJECT)
Retrieve category based on URL containing the category slug.
get_category_by_slug ($slug)
Retrieve category object by category slug.
get_tag ($tag, $output=OBJECT, $filter= 'raw')
Retrieve post tag by tag ID or tag object.
get_tags ($args= '')
Retrieves all post tags.
sanitize_category ($category, $context= 'display')
Sanitizes category data based on context.
sanitize_category_field ($field, $value, $cat_id, $context)
Sanitizes data in single category key field.
Function Documentation
_make_cat_compat (& $category)
Update category structure to old pre 2.3 from new taxonomy structure.
This function was added for the taxonomy support to update the new category structure with the old category one. This will maintain compatibility with plugins and themes which depend on the old key or property names.
The parameter should only be passed a variable and not create the array or object inline to the parameter. The reason for this is that parameter is passed by reference and PHP will fail unless it has the variable.
There is no return value, because everything is updated on the variable you pass to it. This is one of the features with using pass by reference in PHP.
Since
2.3.0
4.4.0 The $category parameter now also accepts a WP_Term object. private
Parameters
array | object | WP_Term $category Category Row object or array
Definition at line 332 of file wp-includes/category.php.
References elseif, and is_wp_error().
Referenced by get_categories(), get_category(), get_category_by_path(), get_category_by_slug(), get_category_to_edit(), WP_Query\get_queried_object(), get_the_category(), and wp_update_category().
cat_is_ancestor_of ($cat1, $cat2)
Check if a category is an ancestor of another category.
You can use either an id or the category object for both parameters. If you use an integer the category will be retrieved.
Since
2.1.0
Parameters
int | object $cat1 ID or object to check if this is the parent category.
int | object $cat2 The child category.
Returns
bool Whether $cat2 is child of $cat1
Definition at line 213 of file wp-includes/category.php.
References term_is_ancestor_of().
clean_category_cache ($id)
Remove the category cache data based on ID.
Since
2.1.0
Parameters
int $id Category ID
Definition at line 308 of file wp-includes/category.php.
References $id, and clean_term_cache().
get_cat_ID ($cat_name)
Retrieve the ID of a category from its name.
Since
1.0.0
Parameters
string $cat_name Category name.
Returns
int 0, if failure and ID of category on success.
Definition at line 178 of file wp-includes/category.php.
References get_term_by().
Referenced by wp_xmlrpc_server\mw_editPost(), and wp_xmlrpc_server\mw_newPost().
get_cat_name ($cat_id)
Retrieve the name of a category from its ID.
Since
1.0.0
Parameters
int $cat_id Category ID
Returns
string Category name, or an empty string if category doesn't exist.
Definition at line 193 of file wp-includes/category.php.
References get_term(), and is_wp_error().
Referenced by wp_xmlrpc_server\_prepare_page(), get_catname(), wp_xmlrpc_server\mt_getPostCategories(), wp_xmlrpc_server\mw_getPost(), and wp_xmlrpc_server\mw_getRecentPosts().
get_categories ($args = '')
Retrieve list of category objects.
If you change the type to 'link' in the arguments, then the link categories will be returned instead. Also all categories will be updated to be backwards compatible with pre-2.3 plugins and themes.
Since
2.1.0
See also
get_terms() Type of arguments that can be changed. string|array $args Optional. Change the defaults retrieving categories. array List of categories.
Filter the taxonomy used to retrieve terms when calling {
See also
get_categories()}.
Since
2.7.0
Parameters
string $taxonomy Taxonomy to retrieve terms from.
array $args An array of arguments. See {
See also
get_terms()}.
Definition at line 23 of file wp-includes/category.php.
References __, _deprecated_argument(), _make_cat_compat(), apply_filters(), get_terms(), and wp_parse_args().
Referenced by export_wp(), get_links_list(), wp_xmlrpc_server\mt_getCategoryList(), wp_xmlrpc_server\mw_getCategories(), twentyfifteen_categorized_blog(), twentyfourteen_categorized_blog(), wp_dropdown_cats(), wp_list_categories(), and wp_xmlrpc_server\wp_suggestCategories().
get_category ($category, $output = OBJECT, $filter = 'raw')
Retrieves category data given a category ID or category object.
If you pass the $category parameter an object, which is assumed to be the category row object retrieved the database. It will cache the category data.
If you pass $category an integer of the category ID, then that category will be retrieved from the database, if it isn't already cached, and pass it back.
If you look at get_term(), then both types will be passed through several filters and finally sanitized based on the $filter parameter value.
The category will converted to maintain backwards compatibility.
Since
1.5.1
Parameters
int | object $category Category ID or Category row object
string $output Optional. Constant OBJECT, ARRAY_A, or ARRAY_N
string $filter Optional. Default is raw or no WordPress defined filter will applied.
Returns
object|array|WP_Error|null Category data in type defined by $output parameter. WP_Error if $category is empty, null if it does not exist.
Definition at line 81 of file wp-includes/category.php.
References $output, _make_cat_compat(), get_term(), and is_wp_error().
Referenced by WP_Press_This\add_category(), get_category_children(), and get_linkcatname().
get_category_by_path ($category_path, $full_match = true, $output = OBJECT)
Retrieve category based on URL containing the category slug.
Breaks the $category_path parameter up to get the category slug.
Tries to find the child path and will return it. If it doesn't find a match, then it will return the first category matching slug, if $full_match, is set to false. If it does not, then it will return null.
It is also possible that it will return a WP_Error object on failure. Check for it when using this function.
Since
2.1.0
Parameters
string $category_path URL containing category slugs.
bool $full_match Optional. Whether full path should be matched.
string $output Optional. Constant OBJECT, ARRAY_A, or ARRAY_N
Returns
object|array|WP_Error|void Type is based on $output value.
Definition at line 111 of file wp-includes/category.php.
References $output, $path, _make_cat_compat(), get_term(), get_terms(), is_wp_error(), sanitize_title(), and str_replace.
Referenced by redirect_canonical().
get_category_by_slug ($slug)
Retrieve category object by category slug.
Since
2.3.0
Parameters
string $slug The category slug.
Returns
object Category data object
Definition at line 162 of file wp-includes/category.php.
References _make_cat_compat(), and get_term_by().
get_tag ($tag, $output = OBJECT, $filter = 'raw')
Retrieve post tag by tag ID or tag object.
If you pass the $tag parameter an object, which is assumed to be the tag row object retrieved the database. It will cache the tag data.
If you pass $tag an integer of the tag ID, then that tag will be retrieved from the database, if it isn't already cached, and pass it back.
If you look at get_term(), then both types will be passed through several filters and finally sanitized based on the $filter parameter value.
Since
2.3.0
Parameters
int | object $tag
string $output Optional. Constant OBJECT, ARRAY_A, or ARRAY_N
string $filter Optional. Default is raw or no WordPress defined filter will applied.
Returns
object|array|WP_Error|null Tag data in type defined by $output parameter. WP_Error if $tag is empty, null if it does not exist.
Definition at line 295 of file wp-includes/category.php.
References $output, and get_term().
get_tags ($args = '')
Retrieves all post tags.
Since
2.3.0
See also
get_terms() For list of arguments to pass.
Parameters
string | array $args Tag arguments to use when retrieving tags.
Returns
array List of tags.
Filter the array of term objects returned for the 'post_tag' taxonomy.
Since
2.3.0
Parameters
array $tags Array of 'post_tag' term objects.
array $args An array of arguments.
See also
get_terms()
Definition at line 256 of file wp-includes/category.php.
References $tags, apply_filters(), and get_terms().
Referenced by export_wp(), and wp_xmlrpc_server\wp_getTags().
sanitize_category ($category, $context = 'display')
Sanitizes category data based on context.
Since
2.3.0
Parameters
object | array $category Category data
string $context Optional. Default is 'display'.
Returns
object|array Same type as $category with sanitized data for safe use.
Definition at line 226 of file wp-includes/category.php.
References sanitize_term().
sanitize_category_field ($field, $value, $cat_id, $context)
Sanitizes data in single category key field.
Since
2.3.0
Parameters
string $field Category key to sanitize
mixed $value Category value to sanitize
int $cat_id Category ID
string $context What filter to use, 'raw', 'display', etc.
Returns
mixed Same type as $value after $value has been sanitized.
Definition at line 241 of file wp-includes/category.php.
References $field, $value, and sanitize_term_field().