GravityView: theme.php File Reference
wp-includes/theme.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_custom_background_cb ()
Default custom background callback.
_custom_header_background_just_in_time ()
Registers the internal custom header and background routines.
_delete_attachment_theme_mod ($id)
Checks an attachment being deleted to see if it's a header or background image.
_get_random_header_data ()
Get random header image data from registered images in theme.
_remove_theme_support ($feature)
Do not use.
_wp_customize_include ()
Includes and instantiates the WP_Customize_Manager class.
_wp_customize_loader_settings ()
Adds settings for the customize-loader script.
add_editor_style ($stylesheet= 'editor-style.css')
Add callback for custom TinyMCE editor stylesheets.
add_theme_support ($feature)
Allows a theme to register its support of a certain feature.
background_color ()
Display background color value.
background_image ()
Display background image path.
check_theme_switched ()
Checks if a theme has been changed and runs 'after_switch_theme' hook on the next WP load.
current_theme_supports ($feature)
Checks a theme's support for a given feature.
display_header_text ()
Whether to display the header text.
get_background_color ()
Retrieve value for custom background color.
get_background_image ()
Retrieve background image for custom background.
get_custom_header ()
Get the header image data.
get_editor_stylesheets ()
Retrieve any registered editor stylesheets.
get_header_image ()
Retrieve header image for custom header.
get_header_image_tag ($attr=array())
Create image tag markup for a custom header image.
get_header_textcolor ()
Retrieve text color for custom header.
get_locale_stylesheet_uri ()
Retrieve localized stylesheet URI.
get_random_header_image ()
Get random header image url from registered images in theme.
get_raw_theme_root ($stylesheet_or_template, $skip_cache=false)
Get the raw theme root relative to the content directory with no filters applied.
get_stylesheet ()
Retrieve name of the current stylesheet.
get_stylesheet_directory ()
Retrieve stylesheet directory path for current theme.
get_stylesheet_directory_uri ()
Retrieve stylesheet directory URI.
get_stylesheet_uri ()
Retrieve URI of current theme stylesheet.
get_template ()
Retrieve name of the current theme.
get_template_directory ()
Retrieve current theme directory.
get_template_directory_uri ()
Retrieve theme directory URI.
get_theme_mod ($name, $default=false)
Retrieve theme modification value for the current theme.
get_theme_mods ()
Retrieve all theme modifications.
get_theme_root ($stylesheet_or_template=false)
Retrieve path to themes directory.
get_theme_root_uri ($stylesheet_or_template=false, $theme_root=false)
Retrieve URI for themes directory.
get_theme_roots ()
Retrieve theme roots.
get_theme_support ($feature)
Gets the theme support arguments passed when registering that support.
get_uploaded_header_images ()
Get the header images uploaded for the current theme.
has_header_image ()
Check whether a header image is set or not.
header_image ()
Display header image URL.
header_textcolor ()
Display text color for custom header.
is_child_theme ()
Whether a child theme is in use.
is_customize_preview ()
Whether the site is being previewed in the Customizer.
is_random_header_image ($type= 'any')
Check if random header image is in use.
locale_stylesheet ()
Display localized stylesheet link element.
register_default_headers ($headers)
Register a selection of default headers to be displayed by the custom header admin UI.
register_theme_directory ($directory)
Register a directory that contains themes.
remove_editor_styles ()
Removes all visual editor stylesheets.
remove_theme_mod ($name)
Remove theme modification name from current theme list.
remove_theme_mods ()
Remove theme modifications option for current theme.
remove_theme_support ($feature)
Allows a theme to de-register its support of a certain feature.
require_if_theme_supports ($feature, $include)
Checks a theme's support for a given feature before loading the functions which implement it.
search_theme_directories ($force=false)
Search all registered theme directories for complete and valid themes.
set_theme_mod ($name, $value)
Update theme modification value for the current theme.
switch_theme ($stylesheet)
Switches the theme.
the_header_image_tag ($attr=array())
Display the image markup for a custom header image.
unregister_default_headers ($header)
Unregister default headers.
validate_current_theme ()
Checks that current theme files 'index.php' and 'style.css' exists.
wp_clean_themes_cache ($clear_update_cache=true)
Clears the cache held by get_theme_roots() and WP_Theme.
wp_customize_support_script ()
Prints a script to check whether or not the Customizer is supported, and apply either the no-customize-support or customize-support class to the body.
wp_customize_url ($stylesheet=null)
Returns a URL to load the Customizer.
wp_get_theme ($stylesheet=null, $theme_root=null)
Gets a WP_Theme object for a theme.
wp_get_themes ($args=array())
Returns an array of WP_Theme objects based on the arguments.
Function Documentation
_custom_background_cb ()
Default custom background callback.
Since
3.0.0 protected
Definition at line 1355 of file wp-includes/theme.php.
References $image, get_background_color(), get_background_image(), get_theme_mod(), get_theme_support(), and set_url_scheme().
_custom_header_background_just_in_time ()
Registers the internal custom header and background routines.
Since
3.4.0 private
Custom_Image_Header $custom_image_header Custom_Background $custom_background
Definition at line 1700 of file wp-includes/theme.php.
References ABSPATH, add_action(), add_theme_support(), current_theme_supports(), get_theme_support(), and is_admin().
_delete_attachment_theme_mod ($id)
Checks an attachment being deleted to see if it's a header or background image.
If true it removes the theme modification which would be pointing at the deleted attachment.
private
Since
3.0.0
4.3.0 Also removes header_image_data.
Parameters
int $id The attachment id.
Definition at line 1930 of file wp-includes/theme.php.
References $header_image, $id, get_background_image(), get_header_image(), remove_theme_mod(), and wp_get_attachment_url().
_get_random_header_data ()
Get random header image data from registered images in theme.
Since
3.4.0
private
array $_wp_default_headers object $_wp_random_header
Returns
object
Definition at line 1104 of file wp-includes/theme.php.
References current_theme_supports(), elseif, get_stylesheet_directory_uri(), get_template_directory_uri(), get_theme_mod(), get_uploaded_header_images(), null, and object.
Referenced by get_custom_header(), and get_random_header_image().
_remove_theme_support ($feature)
Do not use.
Removes theme support internally, ignorant of the blacklist.
private
Since
3.1.0
array $_wp_theme_features Custom_Image_Header $custom_image_header Custom_Background $custom_background
Parameters
string $feature
Definition at line 1793 of file wp-includes/theme.php.
References $GLOBALS, add_theme_support(), did_action(), get_theme_support(), and remove_action().
Referenced by remove_editor_styles(), remove_theme_support(), and unregister_nav_menu().
_wp_customize_include ()
Includes and instantiates the WP_Customize_Manager class.
Loads the Customizer at plugins_loaded when accessing the customize.php admin page or when any request includes a wp_customize=on param, either as a GET query var or as POST data. This param is a signal for whether to bootstrap the Customizer when WordPress is loading, especially in the Customizer preview or when making Customizer Ajax requests for widgets or menus.
Since
3.4.0
WP_Customize_Manager $wp_customize
Definition at line 1998 of file wp-includes/theme.php.
References $_SERVER, $GLOBALS, ABSPATH, is_admin(), and WPINC.
_wp_customize_loader_settings ()
Adds settings for the customize-loader script.
Since
3.4.0
Definition at line 2014 of file wp-includes/theme.php.
References $_SERVER, $wp_scripts, __, admin_url(), esc_url, home_url(), wp_is_mobile(), wp_json_encode(), and wp_scripts().
add_editor_style ($stylesheet = 'editor-style.css')
Add callback for custom TinyMCE editor stylesheets.
The parameter $stylesheet is the name of the stylesheet, relative to the theme root. It also accepts an array of stylesheets. It is optional and defaults to 'editor-style.css'.
This function automatically adds another stylesheet with -rtl prefix, e.g. editor-style-rtl.css. If that file doesn't exist, it is removed before adding the stylesheet(s) to TinyMCE. If an array of stylesheets is passed to add_editor_style(), RTL is only added for the first stylesheet.
Since version 3.4 the TinyMCE body has .rtl CSS class. It is a better option to use that class and add any RTL styles to the main stylesheet.
Since
3.0.0
array $editor_styles
Parameters
array | string $stylesheet Optional. Stylesheet name or array thereof, relative to theme root. Defaults to 'editor-style.css'
Definition at line 1421 of file wp-includes/theme.php.
References add_theme_support(), is_admin(), is_rtl(), and str_replace.
Referenced by twentythirteen_setup(), and twentytwelve_setup().
add_theme_support ($feature)
Allows a theme to register its support of a certain feature.
Must be called in the theme's functions.php file to work. If attached to a hook, it must be after_setup_theme. The init hook may be too late for some features.
Since
2.9.0
array $_wp_theme_features
Parameters
string $feature The feature being added.
Returns
void|bool False on failure, void otherwise.
Definition at line 1526 of file wp-includes/theme.php.
References $post_formats, __, _doing_it_wrong(), did_action(), elseif, get_post_format_slugs(), and wp_parse_args().
Referenced by _custom_header_background_just_in_time(), _remove_theme_support(), add_custom_background(), add_custom_image_header(), add_editor_style(), automatic_feed_links(), register_nav_menus(), register_sidebar(), twentyfifteen_custom_header_setup(), twentyfourteen_custom_header_setup(), twentythirteen_custom_header_setup(), twentythirteen_setup(), twentytwelve_custom_header_setup(), and twentytwelve_setup().
background_color ()
Display background color value.
Since
3.0.0
Definition at line 1345 of file wp-includes/theme.php.
References get_background_color().
background_image ()
Display background image path.
Since
3.0.0
Definition at line 1325 of file wp-includes/theme.php.
References get_background_image().
check_theme_switched ()
Checks if a theme has been changed and runs 'after_switch_theme' hook on the next WP load.
Since
3.3.0
Fires on the first WP load after a theme switch if the old theme still exists.
This action fires multiple times and the parameters differs according to the context, if the old theme exists or not. If the old theme is missing, the parameter will be the slug of the old theme.
Since
3.3.0
Parameters
string $old_name Old theme name.
WP_Theme $old_theme WP_Theme instance of the old theme.
This action is documented in wp-includes/theme.php
Definition at line 1950 of file wp-includes/theme.php.
References do_action(), flush_rewrite_rules(), get_option(), remove_action(), update_option(), and wp_get_theme().
current_theme_supports ($feature)
Checks a theme's support for a given feature.
Since
2.9.0
array $_wp_theme_features
Parameters
string $feature the feature being checked
Returns
bool
Filter whether the current theme supports a specific feature.
The dynamic portion of the hook name, $feature, refers to the specific theme feature. Possible values include 'post-formats', 'post-thumbnails', 'custom-background', 'custom-header', 'menus', 'automatic-feed-links', and 'html5'.
Since
3.4.0
Parameters
bool true Whether the current theme supports the given feature. Default true.
array $args Array of arguments for the feature.
string $feature The theme feature.
Definition at line 1842 of file wp-includes/theme.php.
References apply_filters().
Referenced by _custom_header_background_just_in_time(), _get_random_header_data(), _media_states(), wp_xmlrpc_server\_prepare_post(), _wp_render_title_tag(), Custom_Image_Header\ajax_header_crop(), WP_Customize_Nav_Menus\available_item_types(), comment_form(), WP_Customize_Nav_Menu_Control\content_template(), create_initial_taxonomies(), GFFormsModel\create_post(), Custom_Image_Header\css_includes(), WP_Customize_Nav_Menus\customize_register(), display_header_text(), _WP_Editors\editor_settings(), feed_links(), gallery_shortcode(), get_custom_header(), get_default_post_to_edit(), Custom_Image_Header\get_header_dimensions(), get_media_item(), get_post_class(), get_search_form(), WP_Press_This\html(), img_caption_shortcode(), wp_xmlrpc_server\initialise_blog_option_info(), WP_Admin_Bar\initialize(), WP_Posts_List_Table\inline_edit(), Custom_Image_Header\js(), Custom_Image_Header\js_1(), Custom_Image_Header\js_2(), Custom_Image_Header\js_includes(), post_format_meta_box(), WP_Press_This\post_formats_html(), WP_Widget_Recent_Comments\recent_comments_style(), remove_editor_styles(), require_if_theme_supports(), WP_Press_This\save_post(), Custom_Image_Header\step_1(), Custom_Image_Header\step_2(), Custom_Image_Header\step_3(), wp_admin_bar_appearance_menu(), wp_enqueue_media(), wp_generate_attachment_metadata(), wp_xmlrpc_server\wp_getPostFormats(), wp_list_comments(), and wp_widgets_add_menu().
display_header_text ()
Whether to display the header text.
Since
3.4.0
Returns
bool
Definition at line 975 of file wp-includes/theme.php.
References current_theme_supports(), get_theme_mod(), and get_theme_support().
Referenced by Custom_Image_Header\js_1(), Custom_Image_Header\step_1(), twentythirteen_admin_header_image(), twentythirteen_header_style(), twentytwelve_admin_header_image(), and twentytwelve_header_style().
get_background_color ()
Retrieve value for custom background color.
Since
3.0.0
Returns
string
Definition at line 1336 of file wp-includes/theme.php.
References get_theme_mod(), and get_theme_support().
Referenced by _custom_background_cb(), Custom_Background\admin_page(), background_color(), get_body_class(), and twentytwelve_body_class().
get_background_image ()
Retrieve background image for custom background.
Since
3.0.0
Returns
string
Definition at line 1316 of file wp-includes/theme.php.
References get_theme_mod(), and get_theme_support().
Referenced by _custom_background_cb(), _delete_attachment_theme_mod(), Custom_Background\admin_page(), background_image(), get_body_class(), and twentytwelve_body_class().
get_custom_header ()
Get the header image data.
Since
3.4.0
array $_wp_default_headers
Returns
object
Definition at line 1233 of file wp-includes/theme.php.
References $default, $url, _get_random_header_data(), current_theme_supports(), get_stylesheet_directory_uri(), get_template_directory_uri(), get_theme_mod(), get_theme_support(), is_random_header_image(), and wp_parse_args().
Referenced by get_header_image_tag(), and Custom_Image_Header\step_1().
get_editor_stylesheets ()
Retrieve any registered editor stylesheets.
Since
4.0.0
array $editor_styles Registered editor stylesheets
Returns
array If registered, a list of editor stylesheet URLs.
Filter the array of stylesheets applied to the editor.
Since
4.3.0
Parameters
array $stylesheets Array of stylesheets to be applied to the editor.
Definition at line 1465 of file wp-includes/theme.php.
References $file, $GLOBALS, apply_filters(), esc_url_raw(), get_stylesheet_directory(), get_stylesheet_directory_uri(), get_template_directory(), get_template_directory_uri(), and is_child_theme().
Referenced by _WP_Editors\editor_settings().
get_header_image ()
Retrieve header image for custom header.
Since
2.1.0
Returns
string|false
Definition at line 1003 of file wp-includes/theme.php.
References $url, esc_url_raw(), get_random_header_image(), get_theme_mod(), get_theme_support(), is_random_header_image(), and set_url_scheme().
Referenced by _delete_attachment_theme_mod(), has_header_image(), header_image(), Custom_Image_Header\step_1(), twentyfourteen_body_classes(), twentythirteen_admin_header_style(), twentythirteen_header_style(), and twentytwelve_admin_header_image().
get_header_image_tag ($attr = array())
Create image tag markup for a custom header image.
Since
4.4.0
Parameters
array $attr Optional. Additional attributes for the image tag. Can be used to override the default attributes. Default empty.
Returns
string HTML image element markup or empty string on failure.
Filter the markup of header images.
Since
4.4.0
Parameters
string $html The HTML image tag markup being filtered.
object $header The custom header object returned by 'get_custom_header()'.
array $attr Array of the attributes for the image tag.
Definition at line 1024 of file wp-includes/theme.php.
References $image_meta, $name, $value, absint(), apply_filters(), get_bloginfo(), get_custom_header(), get_post_meta(), wp_calculate_image_sizes(), wp_calculate_image_srcset(), and wp_parse_args().
Referenced by the_header_image_tag().
get_header_textcolor ()
Retrieve text color for custom header.
Since
2.1.0
Returns
string
Definition at line 955 of file wp-includes/theme.php.
References get_theme_mod(), and get_theme_support().
Referenced by header_textcolor(), Custom_Image_Header\step_1(), twentythirteen_admin_header_image(), twentythirteen_header_style(), twentytwelve_admin_header_image(), and twentytwelve_header_style().
get_locale_stylesheet_uri ()
Retrieve localized stylesheet URI.
The stylesheet directory for the localized stylesheet files are located, by default, in the base theme directory. The name of the locale file will be the locale followed by '.css'. If that does not exist, then the text direction stylesheet will be checked for existence, for example 'ltr.css'.
The theme may change the location of the stylesheet directory by either using the 'stylesheet_directory_uri' filter or the 'locale_stylesheet_uri' filter. If you want to change the location of the stylesheet files for the entire WordPress workflow, then change the former. If you just have the locale in a separate folder, then change the latter.
Since
2.1.0
WP_Locale $wp_locale
Returns
string
Filter the localized stylesheet URI.
Since
2.1.0
Parameters
string $stylesheet_uri Localized stylesheet URI.
string $stylesheet_dir_uri Stylesheet directory URI.
Definition at line 255 of file wp-includes/theme.php.
References $dir, $locale, $wp_locale, apply_filters(), elseif, get_locale(), get_stylesheet_directory(), and get_stylesheet_directory_uri().
Referenced by locale_stylesheet().
get_random_header_image ()
Get random header image url from registered images in theme.
Since
3.2.0
Returns
string Path to header image
Definition at line 1141 of file wp-includes/theme.php.
References _get_random_header_data().
Referenced by get_header_image(), and is_random_header_image().
get_raw_theme_root ($stylesheet_or_template, $skip_cache = false)
Get the raw theme root relative to the content directory with no filters applied.
Since
3.1.0
array $wp_theme_directories
Parameters
string $stylesheet_or_template The stylesheet or template name of the theme
bool $skip_cache Optional. Whether to skip the cache. Defaults to false, meaning the cache is used.
Returns
string Theme root
Definition at line 626 of file wp-includes/theme.php.
References elseif, get_option(), and get_theme_roots().
Referenced by WP_Customize_Manager\get_stylesheet_root(), WP_Customize_Manager\get_template_root(), get_theme_root(), get_theme_root_uri(), switch_theme(), wp_get_theme(), and wp_get_themes().
get_stylesheet ()
Retrieve name of the current stylesheet.
The theme name that the administrator has currently set the front end theme as.
For all intents and purposes, the template name and the stylesheet name are going to be the same for most cases.
Since
1.5.0
Returns
string Stylesheet name.
Filter the name of current stylesheet.
Since
1.5.0
Parameters
string $stylesheet Name of the current stylesheet.
Definition at line 152 of file wp-includes/theme.php.
References apply_filters(), and get_option().
Referenced by Custom_Image_Header\ajax_header_add(), Custom_Image_Header\ajax_header_remove(), Theme_Upgrader\bulk_upgrade(), Theme_Upgrader\current_after(), Theme_Upgrader\current_before(), Custom_Image_Header\customize_set_last_used(), get_stylesheet_directory(), get_stylesheet_directory_uri(), Custom_Image_Header\get_uploaded_header_images(), Custom_Image_Header\set_header_image(), validate_current_theme(), wp_get_theme(), wp_get_themes(), and wp_prepare_themes_for_js().
get_stylesheet_directory ()
Retrieve stylesheet directory path for current theme.
Since
1.5.0
Returns
string Path to current theme directory.
Filter the stylesheet directory path for current theme.
Since
1.5.0
Parameters
string $stylesheet_dir Absolute path to the current theme.
string $stylesheet Directory name of the current theme.
string $theme_root Absolute path to themes directory.
Definition at line 170 of file wp-includes/theme.php.
References apply_filters(), get_stylesheet(), and get_theme_root().
Referenced by get_editor_stylesheets(), get_locale_stylesheet_uri(), load_child_theme_textdomain(), GFForms\maybe_import_theme_forms(), validate_current_theme(), and wp_templating_constants().
get_stylesheet_directory_uri ()
Retrieve stylesheet directory URI.
Since
1.5.0
Returns
string
Filter the stylesheet directory URI.
Since
1.5.0
Parameters
string $stylesheet_dir_uri Stylesheet directory URI.
string $stylesheet Name of the activated theme's directory.
string $theme_root_uri Themes root URI.
Definition at line 194 of file wp-includes/theme.php.
References apply_filters(), get_stylesheet(), get_theme_root_uri(), and str_replace.
Referenced by _get_random_header_data(), get_bloginfo(), get_custom_header(), Custom_Image_Header\get_default_header_images(), get_editor_stylesheets(), get_locale_stylesheet_uri(), get_stylesheet_uri(), get_theme_mod(), Custom_Image_Header\process_default_headers(), and Custom_Image_Header\reset_header_image().
get_stylesheet_uri ()
Retrieve URI of current theme stylesheet.
The stylesheet file name is 'style.css' which is appended to stylesheet directory URI path.
Since
1.5.0
Returns
string
Filter the URI of the current theme stylesheet.
Since
1.5.0
Parameters
string $stylesheet_uri Stylesheet URI for the current theme/child theme.
string $stylesheet_dir_uri Stylesheet directory URI for the current theme/child theme.
Definition at line 221 of file wp-includes/theme.php.
References apply_filters(), and get_stylesheet_directory_uri().
Referenced by get_bloginfo(), twentyfifteen_scripts(), twentyfourteen_scripts(), twentythirteen_scripts_styles(), and twentytwelve_scripts_styles().
get_template ()
Retrieve name of the current theme.
Since
1.5.0
Returns
string Template name.
Filter the name of the current theme.
Since
1.5.0
Parameters
string $template Current theme's directory name.
Definition at line 284 of file wp-includes/theme.php.
References apply_filters(), and get_option().
Referenced by Theme_Upgrader\bulk_upgrade(), get_template_directory(), get_template_directory_uri(), and GFForms\maybe_import_theme_forms().
get_template_directory ()
Retrieve current theme directory.
Since
1.5.0
Returns
string Template directory path.
Filter the current theme directory path.
Since
1.5.0
Parameters
string $template_dir The URI of the current theme directory.
string $template Directory name of the current theme.
string $theme_root Absolute path to the themes directory.
Definition at line 302 of file wp-includes/theme.php.
References $template, apply_filters(), get_template(), and get_theme_root().
Referenced by get_attachment_icon_src(), get_editor_stylesheets(), load_theme_textdomain(), twentyfourteen_widgets_init(), twentythirteen_setup(), twentytwelve_setup(), validate_current_theme(), and wp_templating_constants().
get_template_directory_uri ()
Retrieve theme directory URI.
Since
1.5.0
Returns
string Template directory URI.
Filter the current theme directory URI.
Since
1.5.0
Parameters
string $template_dir_uri The URI of the current theme directory.
string $template Directory name of the current theme.
string $theme_root_uri The themes root URI.
Definition at line 326 of file wp-includes/theme.php.
References $template, apply_filters(), get_template(), get_theme_root_uri(), and str_replace.
Referenced by _get_random_header_data(), Featured_Content\enqueue_scripts(), get_bloginfo(), get_custom_header(), Custom_Image_Header\get_default_header_images(), get_editor_stylesheets(), get_theme_mod(), Custom_Image_Header\process_default_headers(), Custom_Image_Header\reset_header_image(), twentyeleven_admin_enqueue_scripts(), twentyeleven_color_schemes(), twentyeleven_customize_preview_js(), twentyeleven_enqueue_color_scheme(), twentyeleven_layouts(), twentyfifteen_customize_control_js(), twentyfifteen_customize_preview_js(), twentyfifteen_scripts(), twentyfourteen_customize_preview_js(), twentyfourteen_scripts(), twentythirteen_custom_header_fonts(), twentythirteen_customize_preview_js(), twentythirteen_scripts_styles(), twentytwelve_customize_preview_js(), and twentytwelve_scripts_styles().
get_theme_mod ($name, $default = false)
Retrieve theme modification value for the current theme.
If the modification name does not exist, then the $default will be passed through sprintf() PHP function with the first string the template directory URI and the second string the stylesheet directory URI.
Since
2.1.0
Parameters
string $name Theme modification name.
bool | string $default
Returns
string
Filter the theme modification, or 'theme_mod', value.
The dynamic portion of the hook name, $name, refers to the key name of the modification array. For example, 'header_textcolor', 'header_image', and so on depending on the theme options.
Since
2.2.0
Parameters
string $current_mod The value of the current theme modification.
This filter is documented in wp-includes/theme.php
Definition at line 851 of file wp-includes/theme.php.
References $default, $name, apply_filters(), get_stylesheet_directory_uri(), get_template_directory_uri(), and get_theme_mods().
Referenced by _custom_background_cb(), _get_random_header_data(), Custom_Background\admin_page(), display_header_text(), get_background_color(), get_background_image(), get_custom_header(), get_header_image(), get_header_textcolor(), get_nav_menu_locations(), WP_Customize_Setting\get_root_value(), is_random_header_image(), retrieve_widgets(), Custom_Image_Header\show_header_selector(), switch_theme(), twentyfifteen_color_scheme_css(), twentyfifteen_header_background_color_css(), twentyfifteen_sidebar_text_color_css(), twentyfourteen_body_classes(), and twentyfourteen_scripts().
get_theme_mods ()
Retrieve all theme modifications.
Since
3.1.0
Returns
array|void Theme modifications.
Definition at line 821 of file wp-includes/theme.php.
References delete_option(), get_option(), is_admin(), update_option(), and wp_get_theme().
Referenced by get_theme_mod(), remove_theme_mod(), and set_theme_mod().
get_theme_root ($stylesheet_or_template = false)
Retrieve path to themes directory.
Does not have trailing slash.
Since
1.5.0
array $wp_theme_directories
Parameters
string $stylesheet_or_template The stylesheet or template name of the theme
Returns
string Theme path.
Filter the absolute path to the themes directory.
Since
1.5.0
Parameters
string $theme_root Absolute path to themes directory.
Definition at line 541 of file wp-includes/theme.php.
References apply_filters(), get_raw_theme_root(), and WP_CONTENT_DIR.
Referenced by Theme_Upgrader\bulk_upgrade(), Theme_Upgrader\check_parent_theme_filter(), WP_Upgrader\fs_connect(), get_stylesheet_directory(), get_template_directory(), Theme_Upgrader\install(), WP_Automatic_Updater\update(), Theme_Upgrader\upgrade(), and WP_Filesystem_Base\wp_themes_dir().
get_theme_root_uri ($stylesheet_or_template = false, $theme_root = false)
Retrieve URI for themes directory.
Does not have trailing slash.
Since
1.5.0
array $wp_theme_directories
Parameters
string $stylesheet_or_template Optional. The stylesheet or template name of the theme. Default is to leverage the main theme root.
string $theme_root Optional. The theme root for which calculations will be based, preventing the need for a get_raw_theme_root() call.
Returns
string Themes URI.
Filter the URI for themes directory.
Since
1.5.0
Parameters
string $theme_root_uri The URI for themes directory.
string $siteurl WordPress web address which is set in General Options.
string $stylesheet_or_template Stylesheet or template name of the theme.
Definition at line 578 of file wp-includes/theme.php.
References ABSPATH, apply_filters(), content_url(), elseif, get_option(), get_raw_theme_root(), plugins_url(), site_url(), str_replace, and WP_CONTENT_DIR.
Referenced by get_stylesheet_directory_uri(), and get_template_directory_uri().
get_theme_roots ()
Retrieve theme roots.
Since
2.9.0
array $wp_theme_directories
Returns
array|string An array of theme roots keyed by template/stylesheet or a single theme root if all themes have the same root.
Definition at line 352 of file wp-includes/theme.php.
References get_site_transient(), and search_theme_directories().
Referenced by get_raw_theme_root().
get_theme_support ($feature)
Gets the theme support arguments passed when registering that support.
Since
3.1.0
array $_wp_theme_features
Parameters
string $feature the feature to check
Returns
mixed The array of extra arguments or the value for the registered feature.
Definition at line 1741 of file wp-includes/theme.php.
Referenced by _custom_background_cb(), _custom_header_background_just_in_time(), _remove_theme_support(), WP_Customize_Manager\_sanitize_header_textcolor(), GFFormsModel\create_post(), display_header_text(), WP_Customize_Header_Image_Control\enqueue(), get_background_color(), get_background_image(), get_body_class(), get_custom_header(), Custom_Image_Header\get_default_header_images(), Custom_Image_Header\get_header_dimensions(), get_header_image(), get_header_textcolor(), Featured_Content\init(), WP_Admin_Bar\initialize(), WP_Posts_List_Table\inline_edit(), is_random_header_image(), Custom_Image_Header\js_1(), Custom_Image_Header\js_2(), post_format_meta_box(), WP_Press_This\post_formats_html(), WP_Customize_Manager\register_controls(), WP_Customize_Header_Image_Control\render_content(), Custom_Image_Header\reset_header_image(), Custom_Image_Header\step_1(), Custom_Image_Header\step_2(), twentythirteen_header_style(), twentytwelve_header_style(), and wp_xmlrpc_server\wp_getPostFormats().
get_uploaded_header_images ()
Get the header images uploaded for the current theme.
Since
3.2.0
Returns
array
Definition at line 1195 of file wp-includes/theme.php.
References $url, esc_url_raw(), get_option(), get_post_meta(), get_posts(), wp_get_attachment_metadata(), and wp_get_attachment_url().
Referenced by _get_random_header_data().
has_header_image ()
Check whether a header image is set or not.
Since
4.2.0
See also
get_header_image()
Returns
bool Whether a header image is set or not.
Definition at line 992 of file wp-includes/theme.php.
References get_header_image().
header_image ()
Display header image URL.
Since
2.1.0
Definition at line 1181 of file wp-includes/theme.php.
References $image, esc_url, and get_header_image().
Referenced by twentythirteen_header_style().
header_textcolor ()
Display text color for custom header.
Since
2.1.0
Definition at line 964 of file wp-includes/theme.php.
References get_header_textcolor().
is_child_theme ()
Whether a child theme is in use.
Since
3.0.0
Returns
bool true if a child theme is in use, false otherwise.
Definition at line 135 of file wp-includes/theme.php.
Referenced by get_editor_stylesheets(), and validate_current_theme().
is_customize_preview ()
Whether the site is being previewed in the Customizer.
Since
4.0.0
WP_Customize_Manager $wp_customize Customizer instance.
Returns
bool True if the site is being previewed in the Customizer, false otherwise.
Definition at line 2107 of file wp-includes/theme.php.
References $wp_customize.
Referenced by WP_Customize_Nav_Menus\render_menu(), and wp_site_icon().
is_random_header_image ($type = 'any')
Check if random header image is in use.
Always true if user expressly chooses the option in Appearance > Header. Also true if theme has multiple header images registered, no specific header image is chosen, and theme turns on random headers with add_theme_support().
Since
3.2.0
Parameters
string $type The random pool to use. any|default|uploaded
Returns
bool
Definition at line 1160 of file wp-includes/theme.php.
References elseif, get_random_header_image(), get_theme_mod(), and get_theme_support().
Referenced by get_custom_header(), get_header_image(), and Custom_Image_Header\show_header_selector().
locale_stylesheet ()
Display localized stylesheet link element.
Since
2.1.0
Definition at line 656 of file wp-includes/theme.php.
References get_locale_stylesheet_uri().
register_default_headers ($headers)
Register a selection of default headers to be displayed by the custom header admin UI.
Since
3.0.0
array $_wp_default_headers
Parameters
array $headers Array of headers keyed by a string id. The ids point to arrays containing 'url', 'thumbnail_url', and 'description' keys.
Definition at line 1276 of file wp-includes/theme.php.
Referenced by twentythirteen_custom_header_setup().
register_theme_directory ($directory)
Register a directory that contains themes.
Since
2.9.0
array $wp_theme_directories
Parameters
string $directory Either the full filesystem path to a theme folder or a folder within WP_CONTENT_DIR
Returns
bool
Definition at line 376 of file wp-includes/theme.php.
References untrailingslashit(), and WP_CONTENT_DIR.
remove_editor_styles ()
Removes all visual editor stylesheets.
Since
3.1.0
array $editor_styles
Returns
bool True on success, false if there were no stylesheets to remove.
Definition at line 1447 of file wp-includes/theme.php.
References $GLOBALS, _remove_theme_support(), current_theme_supports(), and is_admin().
Referenced by WP_Press_This\html().
remove_theme_mod ($name)
Remove theme modification name from current theme list.
If removing the name also removes all elements, then the entire option will be removed.
Since
2.1.0
Parameters
string $name Theme modification name.
Definition at line 917 of file wp-includes/theme.php.
References $name, $theme, get_option(), get_theme_mods(), remove_theme_mods(), and update_option().
Referenced by _delete_attachment_theme_mod(), retrieve_widgets(), Custom_Image_Header\set_header_image(), switch_theme(), Custom_Background\take_action(), and WP_Customize_Background_Image_Setting\update().
remove_theme_mods ()
Remove theme modifications option for current theme.
Since
2.1.0
Definition at line 938 of file wp-includes/theme.php.
References delete_option(), get_option(), and wp_get_theme().
Referenced by remove_theme_mod().
remove_theme_support ($feature)
Allows a theme to de-register its support of a certain feature.
Should be called in the theme's functions.php file. Generally would be used for child themes to override support from the parent theme.
Since
3.0.0
See also
add_theme_support()
Parameters
string $feature the feature being added
Returns
bool|void Whether feature was removed.
Definition at line 1773 of file wp-includes/theme.php.
References _remove_theme_support().
Referenced by remove_custom_background(), remove_custom_image_header(), and WP_UnitTestCase\tearDown().
require_if_theme_supports ($feature, $include)
Checks a theme's support for a given feature before loading the functions which implement it.
Since
2.9.0
Parameters
string $feature The feature being checked.
string $include Path to the file.
Returns
bool True if the current theme supports the supplied feature, false otherwise.
Definition at line 1910 of file wp-includes/theme.php.
References current_theme_supports().
search_theme_directories ($force = false)
Search all registered theme directories for complete and valid themes.
Since
2.9.0
array $wp_theme_directories array $found_themes
Parameters
bool $force Optional. Whether to force a new directory scan. Defaults to false.
Returns
array|false Valid themes found
Filter whether to get the cache of the registered theme directories.
Since
3.4.0
Parameters
bool $cache_expiration Whether to get the cache of the theme directories. Default false.
string $cache_directory Directory to be searched for the cache.
Definition at line 411 of file wp-includes/theme.php.
References $dir, apply_filters(), get_site_transient(), null, set_site_transient(), str_replace, and WP_CONTENT_DIR.
Referenced by WP_Theme\__construct(), get_theme_roots(), wp_clean_themes_cache(), and wp_get_themes().
set_theme_mod ($name, $value)
Update theme modification value for the current theme.
Since
2.1.0
Parameters
string $name Theme modification name.
mixed $value Theme modification value.
Filter the theme mod value on save.
The dynamic portion of the hook name, $name, refers to the key name of the modification array. For example, 'header_textcolor', 'header_image', and so on depending on the theme options.
Since
3.9.0
Parameters
string $value The new value of the theme mod.
string $old_value The current value of the theme mod.
Definition at line 885 of file wp-includes/theme.php.
References $name, $theme, $value, apply_filters(), get_option(), get_theme_mods(), and update_option().
Referenced by _wp_check_split_nav_menu_terms(), Custom_Image_Header\reset_header_image(), Custom_Image_Header\set_header_image(), WP_Customize_Setting\set_root_value(), switch_theme(), Custom_Background\take_action(), Custom_Image_Header\take_action(), wp_ajax_menu_locations_save(), and wp_delete_nav_menu().
switch_theme ($stylesheet)
Switches the theme.
Accepts one argument: $stylesheet of the theme. It also accepts an additional function signature of two arguments: $template then $stylesheet. This is for backwards compatibility.
Since
2.5.0
array $wp_theme_directories WP_Customize_Manager $wp_customize array $sidebars_widgets
Parameters
string $stylesheet Stylesheet name
Fires after the theme is switched.
Since
1.5.0
Parameters
string $new_name Name of the new theme.
WP_Theme $new_theme WP_Theme instance of the new theme.
Definition at line 677 of file wp-includes/theme.php.
References $sidebars_widgets, $template, $wp_customize, add_option(), current_action(), delete_option(), do_action(), elseif, get_option(), get_raw_theme_root(), get_theme_mod(), is_admin(), null, remove_theme_mod(), set_theme_mod(), update_option(), and wp_get_theme().
Referenced by Theme_Upgrader\current_after(), WP_Customize_Manager\save(), twentyfifteen_switch_theme(), twentyfourteen_switch_theme(), twentythirteen_switch_theme(), and validate_current_theme().
the_header_image_tag ($attr = array())
Display the image markup for a custom header image.
Since
4.4.0
Parameters
array $attr Optional. Attributes for the image markup. Default empty.
Definition at line 1088 of file wp-includes/theme.php.
References get_header_image_tag().
unregister_default_headers ($header)
Unregister default headers.
This function must be called after register_default_headers() has already added the header you want to remove.
See also
register_default_headers()
Since
3.0.0
array $_wp_default_headers
Parameters
string | array $header The header string id (key of array) to remove, or an array thereof.
Returns
bool|void A single header returns true on success, false on failure. There is currently no return value for multiple headers.
Definition at line 1297 of file wp-includes/theme.php.
References elseif.
validate_current_theme ()
Checks that current theme files 'index.php' and 'style.css' exists.
Does not initially check the default theme, which is the fallback and should always exist. But if it doesn't exist, it'll fall back to the latest core default theme that does exist. Will switch theme to the fallback theme if current theme does not validate.
You can use the 'validate_current_theme' filter to return false to disable this functionality.
Since
1.5.0
See also
WP_DEFAULT_THEME
Returns
bool
Filter whether to validate the current theme.
Since
2.7.0
Parameters
bool $validate Whether to validate the current theme. Default true.
If we're in an invalid state but WP_DEFAULT_THEME doesn't exist, switch to the latest core default theme that's installed. If it turns out that this latest core default theme is our current theme, then there's nothing we can do about that, so we have to bail, rather than going into an infinite loop. (This is why there are checks against WP_DEFAULT_THEME above, also.) We also can't do anything if it turns out there is no default theme installed. (That's false.)
Definition at line 768 of file wp-includes/theme.php.
References $default, apply_filters(), elseif, WP_Theme\get_core_default_theme(), get_stylesheet(), get_stylesheet_directory(), get_template_directory(), is_child_theme(), switch_theme(), wp_get_theme(), and wp_installing().
Referenced by WP_Customize_Manager\after_setup_theme().
wp_clean_themes_cache ($clear_update_cache = true)
Clears the cache held by get_theme_roots() and WP_Theme.
Since
3.5.0
Parameters
bool $clear_update_cache Whether to clear the Theme updates cache
Definition at line 120 of file wp-includes/theme.php.
References $theme, delete_site_transient(), null, search_theme_directories(), and wp_get_themes().
Referenced by Theme_Upgrader\bulk_upgrade(), Theme_Upgrader\current_after(), Theme_Upgrader\install(), WP_Automatic_Updater\run(), Theme_Upgrader\upgrade(), and wp_clean_update_cache().
wp_customize_support_script ()
Prints a script to check whether or not the Customizer is supported, and apply either the no-customize-support or customize-support class to the body.
This function MUST be called inside the body tag.
Ideally, call this function immediately after the body tag is opened. This prevents a flash of unstyled content.
It is also recommended that you add the "no-customize-support" class to the body tag by default.
Since
3.4.0
Definition at line 2075 of file wp-includes/theme.php.
References admin_url(), endif, and home_url().
wp_customize_url ($stylesheet = null)
Returns a URL to load the Customizer.
Since
3.4.0
Parameters
string $stylesheet Optional. Theme to customize. Defaults to current theme. The theme's stylesheet will be urlencoded if necessary.
Returns
string
Definition at line 2053 of file wp-includes/theme.php.
References $url, admin_url(), and esc_url.
Referenced by WP_Themes_List_Table\display_rows(), wp_admin_bar_customize_menu(), and wp_prepare_themes_for_js().
wp_get_theme ($stylesheet = null, $theme_root = null)
Gets a WP_Theme object for a theme.
Since
3.4.0
array $wp_theme_directories
Parameters
string $stylesheet Directory name for the theme. Optional. Defaults to current theme.
string $theme_root Absolute path of the theme root to look in. Optional. If not specified, get_raw_theme_root() is used to calculate the theme root for the $stylesheet provided (or current theme).
Returns
WP_Theme Theme object. Be sure to check the object's exists() method if you need to confirm the theme's existence.
Definition at line 97 of file wp-includes/theme.php.
References elseif, get_raw_theme_root(), get_stylesheet(), and WP_CONTENT_DIR.
Referenced by WP_Theme_Install_List_Table\_get_theme_status(), check_theme_switched(), current_theme_info(), WP_Theme\get_core_default_theme(), get_current_theme(), Language_Pack_Upgrader\get_name_for_update(), get_page_templates(), get_theme_mods(), get_theme_updates(), populate_network(), populate_options(), WP_Customize_Manager\register_controls(), remove_theme_mods(), WP_Customize_Manager\setup_theme(), switch_theme(), WP_Customize_Manager\theme(), Theme_Upgrader\theme_info(), twentyeleven_theme_options_render_page(), WP_Automatic_Updater\update(), update_right_now_message(), validate_current_theme(), wp_insert_post(), and wp_prepare_themes_for_js().
wp_get_themes ($args = array())
Returns an array of WP_Theme objects based on the arguments.
Despite advances over get_themes(), this function is quite expensive, and grows linearly with additional themes. Stick to wp_get_theme() if possible.
Since
3.4.0
array $wp_theme_directories array $_themes
Parameters
array $args The search arguments. Optional.
errors mixed True to return themes with errors, false to return themes without errors, null to return all themes. Defaults to false.
allowed mixed (Multisite) True to return only allowed themes for a site. False to return only disallowed themes for a site. 'site' to return only site-allowed themes. 'network' to return only network-allowed themes. Null to return all themes. Defaults to null.
blog_id int (Multisite) The blog ID used to calculate which themes are allowed. Defaults to 0, synonymous for the current blog.
Returns
array Array of WP_Theme objects.
Definition at line 30 of file wp-includes/theme.php.
References $theme, elseif, WP_Theme\get_allowed(), WP_Theme\get_allowed_on_network(), WP_Theme\get_allowed_on_site(), get_raw_theme_root(), get_stylesheet(), is_multisite(), null, search_theme_directories(), WP_CONTENT_DIR, and wp_parse_args().
Referenced by WP_Theme\get_allowed_on_site(), get_allowed_themes(), get_broken_themes(), get_themes(), WP_Themes_List_Table\prepare_items(), WP_MS_Themes_List_Table\prepare_items(), upgrade_network(), wp_clean_themes_cache(), wp_prepare_themes_for_js(), and wp_update_themes().