GravityView: widgets.php File Reference
wp-includes/widgets.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_widget_id_base ($id)
Retrieves the widget ID base value.
_register_widget_form_callback ($id, $name, $form_callback, $options=array())
Registers the form callback for a widget.
_register_widget_update_callback ($id_base, $update_callback, $options=array())
Registers the update callback for a widget.
_wp_sidebars_changed ()
Handle sidebars config after theme change.
dynamic_sidebar ($index=1)
Display dynamic sidebar.
is_active_sidebar ($index)
Whether a sidebar is in use.
is_active_widget ($callback=false, $widget_id=false, $id_base=false, $skip_inactive=true)
Whether widget is displayed on the front-end.
is_dynamic_sidebar ()
Whether the dynamic sidebar is enabled and used by theme.
is_registered_sidebar ($sidebar_id)
Checks if a sidebar is registered.
register_sidebar ($args=array())
Builds the definition for a single sidebar and returns the ID.
register_sidebars ($number=1, $args=array())
Creates multiple sidebars.
register_widget ($widget_class)
Register a widget.
retrieve_widgets ($theme_changed=false)
Look for "lost" widgets, this has to run at least on each theme change.
the_widget ($widget, $instance=array(), $args=array())
Output an arbitrary widget as a template tag.
unregister_sidebar ($name)
Removes a sidebar from the list.
unregister_widget ($widget_class)
Unregister a widget.
wp_convert_widget_settings ($base_name, $option_name, $settings)
Convert the widget settings from single to multi-widget format.
wp_get_sidebars_widgets ($deprecated=true)
Retrieve full list of sidebars and their widget instance IDs.
wp_get_widget_defaults ()
Retrieve default registered sidebars list.
wp_register_sidebar_widget ($id, $name, $output_callback, $options=array())
Register an instance of a widget.
wp_register_widget_control ($id, $name, $control_callback, $options=array())
Registers widget control callback for customizing options.
wp_set_sidebars_widgets ($sidebars_widgets)
Set the sidebar widget option to update sidebars.
wp_sidebar_description ($id)
Retrieve description for a sidebar.
wp_unregister_sidebar_widget ($id)
Remove widget from sidebar.
wp_unregister_widget_control ($id)
Remove control callback for widget.
wp_widget_description ($id)
Retrieve description for widget.
wp_widget_rss_form ($args, $inputs=null)
Display RSS widget options form.
wp_widget_rss_output ($rss, $args=array())
Display the RSS entries in a list.
wp_widget_rss_process ($widget_rss, $check_feed=true)
Process RSS feed widget data and optionally retrieve feed items.
wp_widgets_init ()
Register all of the default WordPress widgets on startup.
Variables
$_wp_sidebars_widgets = array()
Private.
$GLOBALS ['_wp_deprecated_widgets_callbacks']
Private.
global $wp_registered_sidebars = array()
global $wp_registered_widget_controls = array()
Stores the registered widget control (options).
global $wp_registered_widget_updates = array()
array $wp_registered_widget_updates
global $wp_registered_widgets = array()
Stores the registered widgets.
Function Documentation
_get_widget_id_base ($id)
Retrieves the widget ID base value.
Since
2.8.0
Parameters
string $id Widget ID.
Returns
string Widget ID base.
Definition at line 1078 of file wp-includes/widgets.php.
References $id.
Referenced by is_active_widget(), wp_register_sidebar_widget(), and wp_register_widget_control().
_register_widget_form_callback ($id, $name, $form_callback, $options = array())
Registers the form callback for a widget.
Since
2.8.0
array $wp_registered_widget_controls
Parameters
int | string $id Widget ID.
string $name Name attribute for the widget.
callable $form_callback Form callback.
array $options Optional. Widget control options. See {
See also
wp_register_widget_control()}. Default empty array.
Definition at line 558 of file wp-includes/widgets.php.
References $id, $name, $options, $wp_registered_widget_controls, did_action(), and wp_parse_args().
Referenced by WP_Widget\_register_one().
_register_widget_update_callback ($id_base, $update_callback, $options = array())
Registers the update callback for a widget.
Since
2.8.0
array $wp_registered_widget_updates
Parameters
string $id_base The base ID of a widget created by extending WP_Widget.
callable $update_callback Update callback method for the widget.
array $options Optional. Widget control options. See {
See also
wp_register_widget_control()}. Default empty array.
Definition at line 527 of file wp-includes/widgets.php.
References $options, and $wp_registered_widget_updates.
Referenced by WP_Widget\_register_one().
_wp_sidebars_changed ()
Handle sidebars config after theme change.
private
Since
3.3.0
array $sidebars_widgets
Definition at line 1090 of file wp-includes/widgets.php.
References $sidebars_widgets, retrieve_widgets(), and wp_get_sidebars_widgets().
dynamic_sidebar ($index = 1)
Display dynamic sidebar.
By default this displays the default sidebar or 'sidebar-1'. If your theme specifies the 'id' or 'name' parameter for its registered sidebars you can pass an id or name as the $index parameter. Otherwise, you can pass in a numerical index to display the sidebar at that index.
Since
2.2.0
array $wp_registered_sidebars array $wp_registered_widgets
Parameters
int | string $index Optional, default is 1. Index, name or ID of dynamic sidebar.
Returns
bool True, if widget sidebar was found and called. False if not found or not called.
This action is documented in wp-includes/widget.php
This action is documented in wp-includes/widget.php
This filter is documented in wp-includes/widget.php
Fires before widgets are rendered in a dynamic sidebar.
Note: The action also fires for empty sidebars, and on both the front-end and back-end, including the Inactive Widgets sidebar on the Widgets screen.
Since
3.9.0
Parameters
int | string $index Index, name, or ID of the dynamic sidebar.
bool $has_widgets Whether the sidebar is populated with widgets. Default true.
Filter the parameters passed to a widget's display callback.
Note: The filter is evaluated on both the front-end and back-end, including for the Inactive Widgets sidebar on the Widgets screen.
Since
2.5.0
See also
register_sidebar()
Parameters
array $params { array $args { An array of widget display arguments.
string $name Name of the sidebar the widget is assigned to. string $id ID of the sidebar the widget is assigned to. string $description The sidebar description. string $class CSS class applied to the sidebar container. string $before_widget HTML markup to prepend to each widget in the sidebar. string $after_widget HTML markup to append to each widget in the sidebar. string $before_title HTML markup to prepend to the widget title when displayed. string $after_title HTML markup to append to the widget title when displayed. string $widget_id ID of the widget. string $widget_name Name of the widget. } array $widget_args { An array of multi-widget arguments.
int $number Number increment used for multiples of the same widget. } }
Fires before a widget's display callback is called.
Note: The action fires on both the front-end and back-end, including for widgets in the Inactive Widgets sidebar on the Widgets screen.
The action is not fired for empty sidebars.
Since
3.0.0
Parameters
array $widget_id { An associative array of widget arguments.
string $name Name of the widget. string $id Widget ID. array|callable $callback When the hook is fired on the front-end, $callback is an array containing the widget object. Fired on the back-end, $callback is 'wp_widget_control', see $_callback. array $params An associative array of multi-widget arguments. string $classname CSS class applied to the widget container. string $description The widget description. array $_callback When the hook is fired on the back-end, $_callback is populated with an array containing the widget object, see $callback. }
Fires after widgets are rendered in a dynamic sidebar.
Note: The action also fires for empty sidebars, and on both the front-end and back-end, including the Inactive Widgets sidebar on the Widgets screen.
Since
3.9.0
Parameters
int | string $index Index, name, or ID of the dynamic sidebar.
bool $has_widgets Whether the sidebar is populated with widgets. Default true.
Filter whether a sidebar has widgets.
Note: The filter is also evaluated for empty sidebars, and on both the front-end and back-end, including the Inactive Widgets sidebar on the Widgets screen.
Since
3.9.0
Parameters
bool $did_one Whether at least one widget was rendered in the sidebar. Default false.
int | string $index Index, name, or ID of the dynamic sidebar.
Definition at line 613 of file wp-includes/widgets.php.
References $id, $sidebars_widgets, $value, $wp_registered_sidebars, $wp_registered_widgets, apply_filters(), do_action(), elseif, sanitize_title(), and wp_get_sidebars_widgets().
Referenced by wp_list_widget_controls().
is_active_sidebar ($index)
Whether a sidebar is in use.
Since
2.8.0
Parameters
string | int $index Sidebar name, id or number to check.
Returns
bool true if the sidebar is in use, false otherwise.
Filter whether a dynamic sidebar is considered "active".
Since
3.9.0
Parameters
bool $is_active_sidebar Whether or not the sidebar should be considered "active". In other words, whether the sidebar contains any widgets.
int | string $index Index, name, or ID of the dynamic sidebar.
Definition at line 850 of file wp-includes/widgets.php.
References $sidebars_widgets, apply_filters(), sanitize_title(), and wp_get_sidebars_widgets().
Referenced by twentyeleven_footer_sidebar_class(), twentyfourteen_body_classes(), twentyfourteen_scripts(), twentythirteen_body_class(), twentythirteen_scripts_styles(), twentytwelve_body_class(), and twentytwelve_content_width().
is_active_widget ($callback = false, $widget_id = false, $id_base = false, $skip_inactive = true)
Whether widget is displayed on the front-end.
Either $callback or $id_base can be used $id_base is the first argument when extending WP_Widget class Without the optional $widget_id parameter, returns the ID of the first sidebar in which the first instance of the widget with the given callback or $id_base is found. With the $widget_id parameter, returns the ID of the sidebar where the widget with that callback/$id_base AND that ID is found.
NOTE: $widget_id and $id_base are the same for single widgets. To be effective this function has to run after widgets have initialized, at action 'init' or later.
Since
2.2.0
array $wp_registered_widgets
Parameters
string | false $callback Optional, Widget callback to check. Default false.
int | false $widget_id Optional. Widget ID. Optional, but needed for checking. Default false.
string | false $id_base Optional. The base ID of a widget created by extending WP_Widget. Default false.
bool $skip_inactive Optional. Whether to check in 'wp_inactive_widgets'. Default true.
Returns
string|false False if widget is not active or id of sidebar in which the widget is active.
Definition at line 795 of file wp-includes/widgets.php.
References $sidebars_widgets, $wp_registered_widgets, _get_widget_id_base(), and wp_get_sidebars_widgets().
Referenced by WP_Widget_Recent_Comments\__construct(), WP_Customize_Widgets\get_available_widgets(), and wp_list_widgets().
is_dynamic_sidebar ()
Whether the dynamic sidebar is enabled and used by theme.
Since
2.2.0
array $wp_registered_widgets array $wp_registered_sidebars
Returns
bool True, if using widgets. False, if not using widgets.
Definition at line 829 of file wp-includes/widgets.php.
References $sidebars_widgets, $wp_registered_sidebars, $wp_registered_widgets, and get_option().
is_registered_sidebar ($sidebar_id)
Checks if a sidebar is registered.
Since
4.4.0
array $wp_registered_sidebars Registered sidebars.
Parameters
string | int $sidebar_id The ID of the sidebar when it was registered.
Returns
bool True if the sidebar is registered, false otherwise.
Definition at line 302 of file wp-includes/widgets.php.
References $wp_registered_sidebars.
Referenced by WP_Customize_Widgets\customize_register(), register_sidebars(), WP_Customize_Widgets\tally_sidebars_via_dynamic_sidebar_calls(), and WP_Customize_Widgets\tally_sidebars_via_is_active_sidebar_calls().
register_sidebar ($args = array())
Builds the definition for a single sidebar and returns the ID.
Accepts either a string or an array and then parses that against a set of default arguments for the new sidebar. WordPress will automatically generate a sidebar ID and name based on the current number of registered sidebars if those arguments are not included.
When allowing for automatic generation of the name and ID parameters, keep in mind that the incrementor for your sidebar can change over time depending on what other plugins and themes are installed.
If theme support for 'widgets' has not yet been added when this function is called, it will be automatically enabled through the use of add_theme_support()
Since
2.2.0
array $wp_registered_sidebars Stores the new sidebar in this array by sidebar ID.
Parameters
array | string $args { Optional. Array or string of arguments for the sidebar being registered.
string $name The name or title of the sidebar displayed in the Widgets interface. Default 'Sidebar $instance'. string $id The unique identifier by which the sidebar will be called. Default 'sidebar-$instance'. string $description Description of the sidebar, displayed in the Widgets interface. Default empty string. string $class Extra CSS class to assign to the sidebar in the Widgets interface. Default empty. string $before_widget HTML content to prepend to each widget's HTML output when assigned to this sidebar. Default is an opening list item element. string $after_widget HTML content to append to each widget's HTML output when assigned to this sidebar. Default is a closing list item element. string $before_title HTML content to prepend to the sidebar title when displayed. Default is an opening h2 element. string $after_title HTML content to append to the sidebar title when displayed. Default is a closing h2 element. }
Returns
string Sidebar ID added to $wp_registered_sidebars global.
Fires once a sidebar has been registered.
Since
3.0.0
Parameters
array $sidebar Parsed arguments for the registered sidebar.
Definition at line 236 of file wp-includes/widgets.php.
References $i, $wp_registered_sidebars, __, _doing_it_wrong(), add_theme_support(), do_action(), and wp_parse_args().
Referenced by register_sidebars(), twentyeleven_widgets_init(), twentyfifteen_widgets_init(), twentyfourteen_widgets_init(), twentyten_widgets_init(), twentythirteen_widgets_init(), and twentytwelve_widgets_init().
register_sidebars ($number = 1, $args = array())
Creates multiple sidebars.
If you wanted to quickly create multiple sidebars for a theme or internally. This function will allow you to do so. If you don't pass the 'name' and/or 'id' in $args, then they will be built for you.
Since
2.2.0
See also
register_sidebar() The second parameter is documented by register_sidebar() and is the same here.
array $wp_registered_sidebars
Parameters
int $number Optional. Number of sidebars to create. Default 1.
array | string $args { Optional. Array or string of arguments for building a sidebar.
string $id The base string of the unique identifier for each sidebar. If provided, and multiple sidebars are being defined, the id will have "-2" appended, and so on. Default 'sidebar-' followed by the number the sidebar creation is currently at. string $name The name or title for the sidebars displayed in the admin dashboard. If registering more than one sidebar, include 'd' in the string as a placeholder for the uniquely assigned number for each sidebar. Default 'Sidebar' for the first sidebar, otherwise 'Sidebar d'. }
Definition at line 162 of file wp-includes/widgets.php.
References $i, $wp_registered_sidebars, __, is_registered_sidebar(), and register_sidebar().
register_widget ($widget_class)
Register a widget.
Registers a WP_Widget widget
Since
2.8.0
See also
WP_Widget
WP_Widget_Factory $wp_widget_factory
Parameters
string $widget_class The name of a class that extends WP_Widget
Definition at line 110 of file wp-includes/widgets.php.
Referenced by gravityview_register_widgets(), twentyeleven_widgets_init(), twentyfourteen_widgets_init(), and wp_widgets_init().
retrieve_widgets ($theme_changed = false)
Look for "lost" widgets, this has to run at least on each theme change.
Since
2.8.0
array $wp_registered_sidebars array $sidebars_widgets array $wp_registered_widgets
Parameters
string | bool $theme_changed Whether the theme was changed as a boolean. A value of 'customize' defers updates for the Customizer.
Returns
array|void
Definition at line 1112 of file wp-includes/widgets.php.
References $id, $sidebars_widgets, $wp_registered_sidebars, $wp_registered_widgets, get_theme_mod(), remove_theme_mod(), and wp_set_sidebars_widgets().
Referenced by _wp_sidebars_changed(), WP_Customize_Widgets\override_sidebars_widgets_for_theme_switch(), and upgrade_330().
the_widget ($widget, $instance = array(), $args = array())
Output an arbitrary widget as a template tag.
Since
2.8.0
WP_Widget_Factory $wp_widget_factory
Parameters
string $widget The widget's PHP class name (see class-wp-widget.php).
array $instance Optional. The widget's instance settings. Default empty array.
array $args { Optional. Array of arguments to configure the display of the widget.
string $before_widget HTML content that will be prepended to the widget's HTML output. Default <div class="widget %s">, where s is the widget's class name. string $after_widget HTML content that will be appended to the widget's HTML output. Default </div>. string $before_title HTML content that will be prepended to the widget's title when displayed. Default <h2 class="widgettitle">. string $after_title HTML content that will be appended to the widget's title when displayed. Default </h2>. }
Fires before rendering the requested widget.
Since
3.0.0
Parameters
string $widget The widget's class name.
array $instance The current widget instance's settings.
array $args An array of the widget's sidebar arguments.
Definition at line 1036 of file wp-includes/widgets.php.
References do_action(), and wp_parse_args().
unregister_sidebar ($name)
Removes a sidebar from the list.
Since
2.2.0
array $wp_registered_sidebars Stores the new sidebar in this array by sidebar ID.
Parameters
string $name The ID of the sidebar when it was added.
Definition at line 286 of file wp-includes/widgets.php.
References $name, and $wp_registered_sidebars.
unregister_widget ($widget_class)
Unregister a widget.
Unregisters a WP_Widget widget. Useful for unregistering default widgets. Run within a function hooked to the widgets_init action.
Since
2.8.0
See also
WP_Widget
WP_Widget_Factory $wp_widget_factory
Parameters
string $widget_class The name of a class that extends WP_Widget
Definition at line 130 of file wp-includes/widgets.php.
wp_convert_widget_settings ($base_name, $option_name, $settings)
Convert the widget settings from single to multi-widget format.
Since
2.8.0
array $_wp_sidebars_widgets
Parameters
string $base_name
string $option_name
array $settings
Returns
array
Definition at line 963 of file wp-includes/widgets.php.
References $GLOBALS, $i, $name, $sidebars_widgets, get_option(), is_admin(), and update_option().
Referenced by WP_Widget\get_settings().
wp_get_sidebars_widgets ($deprecated = true)
Retrieve full list of sidebars and their widget instance IDs.
Will upgrade sidebar widget list, if needed. Will also save updated list, if needed.
Since
2.2.0 private
array $_wp_sidebars_widgets array $sidebars_widgets
Parameters
bool $deprecated Not used (argument deprecated).
Returns
array Upgraded list of widgets to version 3 array format when called from the admin.
Filter the list of sidebars and their widgets.
Since
2.7.0
Parameters
array $sidebars_widgets An associative array of sidebars and their widgets.
Definition at line 886 of file wp-includes/widgets.php.
References $_wp_sidebars_widgets, $deprecated, $sidebars_widgets, _deprecated_argument(), apply_filters(), get_option(), and is_admin().
Referenced by _wp_sidebars_changed(), WP_Customize_Widgets\customize_register(), dynamic_sidebar(), is_active_sidebar(), is_active_widget(), WP_Customize_Widgets\override_sidebars_widgets_for_theme_switch(), wp_ajax_delete_inactive_widgets(), and wp_ajax_save_widget().
wp_get_widget_defaults ()
Retrieve default registered sidebars list.
Since
2.2.0 private
array $wp_registered_sidebars
Returns
array
Definition at line 940 of file wp-includes/widgets.php.
References $wp_registered_sidebars.
wp_register_sidebar_widget ($id, $name, $output_callback, $options = array())
Register an instance of a widget.
The default widget option is 'classname' that can be overridden.
The function can also be used to un-register widgets when $output_callback parameter is an empty string.
Since
2.2.0
array $wp_registered_widgets Uses stored registered widgets. array $wp_register_widget_defaults Retrieves widget defaults. array $wp_registered_widget_updates array $_wp_deprecated_widgets_callbacks
Parameters
int | string $id Widget ID.
string $name Widget display title.
callable $output_callback Run when widget is called.
array $options { Optional. An array of supplementary widget options for the instance.
string $classname Class name for the widget's HTML container. Default is a shortened version of the output callback name. string $description Widget description for display in the widget administration panel and/or theme. }
Fires once for each registered widget.
Since
3.0.0
Parameters
array $widget An array of default widget arguments.
Definition at line 335 of file wp-includes/widgets.php.
References $id, $name, $options, $wp_registered_widget_controls, $wp_registered_widget_updates, $wp_registered_widgets, _get_widget_id_base(), did_action(), do_action(), and wp_parse_args().
Referenced by WP_Widget\_register_one(), and wp_unregister_sidebar_widget().
wp_register_widget_control ($id, $name, $control_callback, $options = array())
Registers widget control callback for customizing options.
Since
2.2.0
array $wp_registered_widget_controls array $wp_registered_widget_updates array $wp_registered_widgets array $_wp_deprecated_widgets_callbacks
Parameters
int | string $id Sidebar ID.
string $name Sidebar display name.
callable $control_callback Run when sidebar is displayed.
array $options { Optional. Array or string of control options. Default empty array.
int $height Never used. Default 200. int $width Width of the fully expanded control form (but try hard to use the default width). Default 250. int|string $id_base Required for multi-widgets, i.e widgets that allow multiple instances such as the text widget. The widget id will end up looking like {$id_base}-{$unique_number}. }
Definition at line 470 of file wp-includes/widgets.php.
References $id, $name, $options, $wp_registered_widget_controls, $wp_registered_widget_updates, $wp_registered_widgets, _get_widget_id_base(), did_action(), and wp_parse_args().
Referenced by wp_unregister_widget_control().
wp_set_sidebars_widgets ($sidebars_widgets)
Set the sidebar widget option to update sidebars.
Since
2.2.0 private
Parameters
array $sidebars_widgets Sidebar widgets and their settings.
Definition at line 924 of file wp-includes/widgets.php.
References $sidebars_widgets, and update_option().
Referenced by retrieve_widgets(), wp_ajax_delete_inactive_widgets(), wp_ajax_save_widget(), and wp_ajax_widgets_order().
wp_sidebar_description ($id)
Retrieve description for a sidebar.
When registering sidebars a 'description' parameter can be included that describes the sidebar for display on the widget administration panel.
Since
2.9.0
array $wp_registered_sidebars
Parameters
string $id sidebar ID.
Returns
string|void Sidebar description, if available.
Definition at line 413 of file wp-includes/widgets.php.
References $id, $wp_registered_sidebars, and esc_html.
Referenced by wp_list_widget_controls().
wp_unregister_sidebar_widget ($id)
Remove widget from sidebar.
Since
2.2.0
Parameters
int | string $id Widget ID.
Fires just before a widget is removed from a sidebar.
Since
3.0.0
Parameters
int $id The widget ID.
Definition at line 430 of file wp-includes/widgets.php.
References $id, do_action(), wp_register_sidebar_widget(), and wp_unregister_widget_control().
Referenced by unregister_sidebar_widget().
wp_unregister_widget_control ($id)
Remove control callback for widget.
Since
2.2.0
Parameters
int | string $id Widget ID.
Definition at line 594 of file wp-includes/widgets.php.
References $id, and wp_register_widget_control().
Referenced by unregister_widget_control(), and wp_unregister_sidebar_widget().
wp_widget_description ($id)
Retrieve description for widget.
When registering widgets, the options can also include 'description' that describes the widget for display on the widget administration panel or in the theme.
Since
2.5.0
array $wp_registered_widgets
Parameters
int | string $id Widget ID.
Returns
string|void Widget description, if available.
Definition at line 390 of file wp-includes/widgets.php.
References $id, $wp_registered_widgets, and esc_html.
Referenced by wp_widget_control().
wp_widget_rss_form ($args, $inputs = null)
Display RSS widget options form.
The options for what fields are displayed for the RSS form are all booleans and are as follows: 'url', 'title', 'items', 'show_summary', 'show_author', 'show_date'.
Since
2.5.0
Parameters
array | string $args Values for input fields.
array $inputs Override default display options.
Definition at line 1328 of file wp-includes/widgets.php.
References $i, $id, __, _e, checked(), endforeach, endif, esc_attr(), input, label, name, selected(), str_replace, and wp_parse_args().
Referenced by WP_Widget_RSS\form().
wp_widget_rss_output ($rss, $args = array())
Display the RSS entries in a list.
Since
2.5.0
Parameters
string | array | object $rss RSS url.
array $args Widget arguments.
Definition at line 1224 of file wp-includes/widgets.php.
References $link, $title, __, current_user_can(), date_i18n(), elseif, esc_attr(), esc_html, esc_url, fetch_feed(), get_option(), is_admin(), is_wp_error(), wp_parse_args(), and wp_trim_words().
Referenced by WP_Widget_RSS\widget().
wp_widget_rss_process ($widget_rss, $check_feed = true)
Process RSS feed widget data and optionally retrieve feed items.
The feed widget can not have more than 20 items or it will reset back to the default, which is 10.
The resulting array has the feed title, feed url, feed link (from channel), feed items, error (if any), and whether to show summary, author, and date. All respectively in the order of the array elements.
Since
2.5.0
Parameters
array $widget_rss RSS widget feed data. Expects unescaped data.
bool $check_feed Optional, default is true. Whether to check feed for errors.
Returns
array
Definition at line 1402 of file wp-includes/widgets.php.
References $link, $title, $url, esc_url, esc_url_raw(), fetch_feed(), and is_wp_error().
Referenced by WP_Widget_RSS\update().
wp_widgets_init ()
Register all of the default WordPress widgets on startup.
Calls 'widgets_init' action after all of the WordPress widgets have been registered.
Since
2.2.0
Fires after all default WordPress widgets have been registered.
Since
2.2.0
Definition at line 1439 of file wp-includes/widgets.php.
References do_action(), get_option(), is_blog_installed(), and register_widget().
Variable Documentation
$_wp_sidebars_widgets = array()
Private.
array $_wp_sidebars_widgets
Definition at line 61 of file wp-includes/widgets.php.
Referenced by wp_get_sidebars_widgets().
$GLOBALS['_wp_deprecated_widgets_callbacks']
Initial value:
= array(
    'wp_widget_pages',
    'wp_widget_pages_control',
    'wp_widget_calendar',
    'wp_widget_calendar_control',
    'wp_widget_archives',
    'wp_widget_archives_control',
    'wp_widget_links',
    'wp_widget_meta',
    'wp_widget_meta_control',
    'wp_widget_search',
    'wp_widget_recent_entries',
    'wp_widget_recent_entries_control',
    'wp_widget_tag_cloud',
    'wp_widget_tag_cloud_control',
    'wp_widget_categories',
    'wp_widget_categories_control',
    'wp_widget_text',
    'wp_widget_text_control',
    'wp_widget_rss',
    'wp_widget_rss_control',
    'wp_widget_recent_comments',
    'wp_widget_recent_comments_control'
)
Private.
array $_wp_deprecated_widgets_callbacks
Definition at line 68 of file wp-includes/widgets.php.
Referenced by wp_convert_widget_settings().
$wp_registered_sidebars = array()
Stores the sidebars, since many themes can have more than one.
array $wp_registered_sidebars
Since
2.2.0
Definition at line 26 of file wp-includes/widgets.php.
Referenced by WP_Customize_Widgets\customize_register(), dynamic_sidebar(), WP_Customize_Widgets\enqueue_scripts(), WP_Customize_Widgets\export_preview_data(), is_dynamic_sidebar(), WP_Customize_Widgets\is_panel_active(), is_registered_sidebar(), register_sidebar(), register_sidebars(), retrieve_widgets(), unregister_sidebar(), wp_get_widget_defaults(), and wp_sidebar_description().
$wp_registered_widget_controls = array()
Stores the registered widget control (options).
array $wp_registered_widget_controls
Since
2.2.0
Definition at line 26 of file wp-includes/widgets.php.
Referenced by _register_widget_form_callback(), WP_Customize_Widgets\call_widget_update(), WP_Customize_Widgets\customize_register(), WP_Customize_Widgets\get_available_widgets(), WP_Customize_Widgets\is_wide_widget(), wp_ajax_save_widget(), wp_dashboard_setup(), wp_list_widgets(), wp_register_sidebar_widget(), wp_register_widget_control(), and wp_widget_control().
$wp_registered_widget_updates = array()
array $wp_registered_widget_updates
Definition at line 26 of file wp-includes/widgets.php.
Referenced by _register_widget_update_callback(), WP_Customize_Widgets\call_widget_update(), wp_ajax_save_widget(), wp_register_sidebar_widget(), and wp_register_widget_control().
$wp_registered_widgets = array()
Stores the registered widgets.
array $wp_registered_widgets
Since
2.2.0
Definition at line 26 of file wp-includes/widgets.php.
Referenced by WP_Widget_Factory\_register_widgets(), WP_Customize_Widgets\customize_register(), dynamic_sidebar(), WP_Customize_Widgets\enqueue_scripts(), WP_Customize_Widgets\export_preview_data(), WP_Customize_Widgets\get_available_widgets(), is_active_widget(), is_dynamic_sidebar(), next_widget_id_number(), retrieve_widgets(), WP_Customize_Widgets\sanitize_sidebar_widgets_js_instance(), WP_Widget_Form_Customize_Control\to_json(), WP_Widget\update_callback(), upgrade_330(), wp_ajax_save_widget(), wp_dashboard_setup(), wp_list_widget_controls_dynamic_sidebar(), wp_list_widgets(), wp_register_sidebar_widget(), wp_register_widget_control(), wp_widget_control(), and wp_widget_description().