GravityView: media.php File Reference
wp-includes/media.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_get_attachment_relative_path ($file)
Get the attachment path relative to the upload directory.
_wp_get_image_size_from_meta ($size_name, $image_meta)
Get the image size as array from its meta data.
_wp_image_editor_choose ($args=array())
Tests which editors are capable of supporting the request.
_wp_post_thumbnail_class_filter ($attr)
Adds a 'wp-post-image' class to post thumbnails.
_wp_post_thumbnail_class_filter_add ($attr)
Adds '_wp_post_thumbnail_class_filter' callback to the 'wp_get_attachment_image_attributes' filter hook.
_wp_post_thumbnail_class_filter_remove ($attr)
Removes the '_wp_post_thumbnail_class_filter' callback from the 'wp_get_attachment_image_attributes' filter hook.
_wp_upload_dir_baseurl ()
Caches and returns the base URL of the uploads directory.
add_image_size ($name, $width=0, $height=0, $crop=false)
Register a new image size.
adjacent_image_link ($prev=true, $size= 'thumbnail', $text=false)
Displays next or previous image link that has the same post parent.
attachment_url_to_postid ($url)
Tries to convert an attachment URL into a post ID.
gallery_shortcode ($attr)
Builds the Gallery shortcode output.
get_attached_media ($type, $post=0)
Retrieves media attached to the passed post.
get_attachment_taxonomies ($attachment)
Retrieves taxonomies attached to given the attachment.
get_image_tag ($id, $alt, $title, $align, $size= 'medium')
Gets an img tag for an image attachment, scaling it down if requested.
get_intermediate_image_sizes ()
Gets the available intermediate image sizes.
get_media_embedded_in_content ($content, $types=null)
Check the content blob for an audio, video, object, embed, or iframe tags.
get_post_galleries ($post, $html=true)
Retrieves galleries from the passed post's content.
get_post_galleries_images ($post=0)
Retrieve the image srcs from galleries from a post's content, if present.
get_post_gallery ($post=0, $html=true)
Check a specified post's content for gallery and, if present, return the first.
get_post_gallery_images ($post=0)
Checks a post's content for galleries and return the image srcs for the first found gallery.
get_taxonomies_for_attachments ($output= 'names')
Retrieves all of the taxonomy names that are registered for attachments.
has_image_size ($name)
Check if an image size exists.
image_constrain_size_for_editor ($width, $height, $size= 'medium', $context=null)
Scale down the default size of an image.
image_downsize ($id, $size= 'medium')
Scale an image to fit a particular size (such as 'thumb' or 'medium').
image_get_intermediate_size ($post_id, $size= 'thumbnail')
Retrieves the image's intermediate size (resized) path, width, and height.
image_hwstring ($width, $height)
Retrieve width and height attributes using given width and height values.
image_make_intermediate_size ($file, $width, $height, $crop=false)
Resizes an image to make a thumbnail or intermediate size.
image_resize_dimensions ($orig_w, $orig_h, $dest_w, $dest_h, $crop=false)
Retrieves calculated resize dimensions for use in WP_Image_Editor.
img_caption_shortcode ($attr, $content=null)
Builds the Caption shortcode output.
next_image_link ($size= 'thumbnail', $text=false)
Displays next image link that has the same post parent.
previous_image_link ($size= 'thumbnail', $text=false)
Displays previous image link that has the same post parent.
remove_image_size ($name)
Remove a new image size.
set_post_thumbnail_size ($width=0, $height=0, $crop=false)
Registers an image size for the post thumbnail.
wp_audio_shortcode ($attr, $content= '')
Builds the Audio shortcode output.
wp_calculate_image_sizes ($size, $image_src=null, $image_meta=null, $attachment_id=0)
Creates a 'sizes' attribute value for an image.
wp_calculate_image_srcset ($size_array, $image_src, $image_meta, $attachment_id=0)
A helper function to calculate the image sources to include in a 'srcset' attribute.
wp_constrain_dimensions ($current_width, $current_height, $max_width=0, $max_height=0)
Calculates the new dimensions for a down-sampled image.
wp_convert_hr_to_bytes ($size)
Converts a shorthand byte value to an integer byte value.
wp_enqueue_media ($args=array())
Enqueues all scripts, styles, settings, and templates necessary to use all media JS APIs.
wp_expand_dimensions ($example_width, $example_height, $max_width, $max_height)
Based on a supplied width/height example, return the biggest possible dimensions based on the max width/height.
wp_get_attachment_id3_keys ($attachment, $context= 'display')
Returns useful keys to use to lookup data from an attachment's stored metadata.
wp_get_attachment_image ($attachment_id, $size= 'thumbnail', $icon=false, $attr= '')
Get an HTML img element representing an image attachment.
wp_get_attachment_image_sizes ($attachment_id, $size= 'medium', $image_meta=null)
Retrieves the value for an image attachment's 'sizes' attribute.
wp_get_attachment_image_src ($attachment_id, $size= 'thumbnail', $icon=false)
Retrieve an image to represent an attachment.
wp_get_attachment_image_srcset ($attachment_id, $size= 'medium', $image_meta=null)
Retrieves the value for an image attachment's 'srcset' attribute.
wp_get_attachment_image_url ($attachment_id, $size= 'thumbnail', $icon=false)
Get the URL of an image attachment.
wp_get_audio_extensions ()
Returns a filtered list of WP-supported audio formats.
wp_get_image_editor ($path, $args=array())
Returns a WP_Image_Editor instance and loads file into it.
wp_get_video_extensions ()
Returns a filtered list of WP-supported video formats.
wp_image_add_srcset_and_sizes ($image, $image_meta, $attachment_id)
Adds 'srcset' and 'sizes' attributes to an existing 'img' element.
wp_image_editor_supports ($args=array())
Tests whether there is an editor that supports a given mime type or methods.
wp_imagecreatetruecolor ($width, $height)
Create new GD image resource with transparency support.
wp_make_content_images_responsive ($content)
Filters 'img' elements in post content to add 'srcset' and 'sizes' attributes.
wp_max_upload_size ()
Determines the maximum upload size allowed in php.ini.
wp_maybe_generate_attachment_metadata ($attachment)
Maybe attempts to generate attachment metadata, if missing.
wp_mediaelement_fallback ($url)
Provides a No-JS Flash fallback as a last resort for audio / video.
wp_playlist_scripts ($type)
Outputs and enqueue default scripts and styles for playlists.
wp_playlist_shortcode ($attr)
Builds the Playlist shortcode output.
wp_plupload_default_settings ()
Prints default plupload arguments.
wp_prepare_attachment_for_js ($attachment)
Prepares an attachment post object for JS, where it is expected to be JSON-encoded and fit into an Attachment model.
wp_underscore_playlist_templates ()
Outputs the templates used by playlists.
wp_video_shortcode ($attr, $content= '')
Builds the Video shortcode output.
wpview_media_sandbox_styles ()
Returns the URLs for CSS files used in an iframe-sandbox'd TinyMCE media view.
Function Documentation
_wp_get_attachment_relative_path ($file)
Get the attachment path relative to the upload directory.
Since
4.4.1 private
Parameters
string $file Attachment file name.
Returns
string Attachment path relative to the upload directory.
Definition at line 889 of file wp-includes/media.php.
References $file.
Referenced by wp_calculate_image_srcset(), and wp_get_attachment_url().
_wp_get_image_size_from_meta ($size_name, $image_meta)
Get the image size as array from its meta data.
Used for responsive images.
Since
4.4.0 private
Parameters
string $size_name Image size. Accepts any valid image size name ('thumbnail', 'medium', etc.).
array $image_meta The image meta data.
Returns
array|bool Array of width and height values in pixels (in that order) or false if the size doesn't exist.
Definition at line 939 of file wp-includes/media.php.
References $image_meta, absint(), and elseif.
Referenced by wp_calculate_image_sizes().
_wp_image_editor_choose ($args = array())
Tests which editors are capable of supporting the request.
Since
3.5.0
Parameters
array $args Optional. Array of arguments for choosing a capable editor. Default empty array.
Returns
string|false Class name for the first editor that claims to support the request. False if no editor claims to support the request.
Filter the list of image editing library classes.
Since
3.5.0
Parameters
array $image_editors List of available image editors. Defaults are 'WP_Image_Editor_Imagick', 'WP_Image_Editor_GD'.
Definition at line 2887 of file wp-includes/media.php.
References ABSPATH, apply_filters(), and WPINC.
Referenced by wp_get_image_editor(), and wp_image_editor_supports().
_wp_post_thumbnail_class_filter ($attr)
Adds a 'wp-post-image' class to post thumbnails.
Internal use only.
Uses the 'begin_fetch_post_thumbnail_html' and 'end_fetch_post_thumbnail_html' action hooks to dynamically add/remove itself so as to only filter post thumbnails.
Since
2.9.0
Parameters
array $attr Thumbnail attributes including src, class, alt, title.
Returns
array Modified array of attributes including the new 'wp-post-image' class.
Definition at line 1401 of file wp-includes/media.php.
_wp_post_thumbnail_class_filter_add ($attr)
Adds '_wp_post_thumbnail_class_filter' callback to the 'wp_get_attachment_image_attributes' filter hook.
Internal use only.
Since
2.9.0
Parameters
array $attr Thumbnail attributes including src, class, alt, title.
Definition at line 1415 of file wp-includes/media.php.
References add_filter().
_wp_post_thumbnail_class_filter_remove ($attr)
Removes the '_wp_post_thumbnail_class_filter' callback from the 'wp_get_attachment_image_attributes' filter hook.
Internal use only.
Since
2.9.0
Parameters
array $attr Thumbnail attributes including src, class, alt, title.
Definition at line 1428 of file wp-includes/media.php.
References remove_filter().
_wp_upload_dir_baseurl ()
Caches and returns the base URL of the uploads directory.
Since
4.4.0 private
Returns
string The base URL, cached.
Definition at line 913 of file wp-includes/media.php.
References $blog_id, get_current_blog_id(), and wp_upload_dir().
Referenced by wp_calculate_image_srcset().
add_image_size ($name, $width = 0, $height = 0, $crop = false)
Register a new image size.
Cropping behavior for the image size is dependent on the value of $crop:
If false (default), images will be scaled, not cropped.
If an array in the form of array(x_crop_position, y_crop_position):
x_crop_position accepts 'left' 'center', or 'right'.
y_crop_position accepts 'top', 'center', or 'bottom'. Images will be cropped to the specified dimensions within the defined crop area.
If true, images will be cropped to the specified dimensions using center positions.
Since
2.9.0
array $_wp_additional_image_sizes Associative array of additional image sizes.
Parameters
string $name Image size identifier.
int $width Image width in pixels.
int $height Image height in pixels.
bool | array $crop Optional. Whether to crop images to specified width and height or resize. An array can specify positioning of the crop area. Default false.
Definition at line 246 of file wp-includes/media.php.
References $name, and absint().
Referenced by set_post_thumbnail_size().
adjacent_image_link ($prev = true, $size = 'thumbnail', $text = false)
Displays next or previous image link that has the same post parent.
Retrieves the current attachment object from the $post global.
Since
2.5.0
Parameters
bool $prev Optional. Whether to display the next (false) or previous (true) link. Default true.
string | array $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'thumbnail'.
bool $text Optional. Link text. Default false.
Filter the adjacent image link.
The dynamic portion of the hook name, $adjacent, refers to the type of adjacency, either 'next', or 'previous'.
Since
3.5.0
Parameters
string $output Adjacent image HTML markup.
int $attachment_id Attachment ID
string $size Image size.
string $text Link text.
Definition at line 2631 of file wp-includes/media.php.
References $attachments, $output, $post, $size, $text, apply_filters(), get_children(), get_post(), and wp_get_attachment_link().
Referenced by next_image_link(), and previous_image_link().
attachment_url_to_postid ($url)
Tries to convert an attachment URL into a post ID.
Since
4.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $url The URL to resolve.
Returns
int The found post ID, or 0 on failure.
Filter an attachment id found by URL.
Since
4.2.0
Parameters
int | null $post_id The post_id (if any) found by the function.
string $url The URL being looked up.
Definition at line 3739 of file wp-includes/media.php.
References $dir, $path, $post_id, $url, $wpdb, apply_filters(), str_replace, and wp_upload_dir().
Referenced by WP_Customize_Upload_Control\to_json(), and wp_ajax_set_attachment_thumbnail().
gallery_shortcode ($attr)
Builds the Gallery shortcode output.
This implements the functionality of the Gallery Shortcode for displaying WordPress images on a post.
Since
2.5.0
int $instance
Parameters
array $attr { Attributes of the gallery shortcode.
string $order Order of the images in the gallery. Default 'ASC'. Accepts 'ASC', 'DESC'. string $orderby The field to use when ordering the images. Default 'menu_order ID'. Accepts any valid SQL ORDERBY statement. int $id Post ID. string $itemtag HTML tag to use for each image in the gallery. Default 'dl', or 'figure' when the theme registers HTML5 gallery support. string $icontag HTML tag to use for each image's icon. Default 'dt', or 'div' when the theme registers HTML5 gallery support. string $captiontag HTML tag to use for each image's caption. Default 'dd', or 'figcaption' when the theme registers HTML5 gallery support. int $columns Number of columns of images to display. Default 3. string|array $size Size of the images to display. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'thumbnail'. string $ids A comma-separated list of IDs of attachments to display. Default empty. string $include A comma-separated list of IDs of attachments to include. Default empty. string $exclude A comma-separated list of IDs of attachments to exclude. Default empty. string $link What to link each image to. Default empty (links to the attachment page). Accepts 'file', 'none'. }
Returns
string HTML content to display gallery.
Filter the default gallery shortcode output.
If the filtered output isn't empty, it will be used instead of generating the default gallery template.
Since
2.5.0
4.2.0 The $instance parameter was added.
See also
gallery_shortcode()
Parameters
string $output The gallery output. Default empty.
array $attr Attributes of the gallery shortcode.
int $instance Unique numeric ID of this gallery shortcode instance.
Filter whether to print default gallery styles.
Since
3.1.0
Parameters
bool $print Whether to print default gallery styles. Defaults to false if the theme supports HTML5 galleries. Otherwise, defaults to true.
Filter the default gallery shortcode CSS styles.
Since
2.5.0
Parameters
string $gallery_style Default CSS styles and opening HTML div container for the gallery shortcode output.
Definition at line 1579 of file wp-includes/media.php.
References $attachments, $columns, $i, $id, $image_meta, $output, $post, apply_filters(), current_theme_supports(), elseif, get_children(), get_post(), get_posts(), is_feed(), is_rtl(), sanitize_html_class(), shortcode_atts(), tag_escape(), wp_get_attachment_image(), wp_get_attachment_link(), wp_get_attachment_metadata(), wp_kses_allowed_html(), and wptexturize().
get_attached_media ($type, $post = 0)
Retrieves media attached to the passed post.
Since
3.6.0
Parameters
string $type Mime type.
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
array Found attachments.
Filter arguments used to retrieve media attached to the given post.
Since
3.6.0
Parameters
array $args Post query arguments.
string $type Mime type of the desired media.
mixed $post Post ID or object.
Filter the list of media attached to the given post.
Since
3.6.0
Parameters
array $children Associative array of media attached to the given post.
string $type Mime type of the media desired.
mixed $post Post ID or object.
Definition at line 3517 of file wp-includes/media.php.
References $post, apply_filters(), get_children(), and get_post().
Referenced by wp_audio_shortcode(), and wp_video_shortcode().
get_attachment_taxonomies ($attachment)
Retrieves taxonomies attached to given the attachment.
Since
2.5.0
Parameters
int | array | object $attachment Attachment ID, data array, or data object.
Returns
array Empty array on failure. List of taxonomies on success.
Definition at line 2679 of file wp-includes/media.php.
References $file, elseif, get_attached_file(), get_object_taxonomies(), get_post(), and object.
Referenced by get_attachment_fields_to_edit(), get_compat_media_markup(), get_object_taxonomies(), media_upload_form_handler(), and wp_ajax_save_attachment_compat().
get_image_tag ($id, $alt, $title, $align, $size = 'medium')
Gets an img tag for an image attachment, scaling it down if requested.
The filter 'get_image_tag_class' allows for changing the class name for the image without having to use regular expressions on the HTML content. The parameters are: what WordPress will use for the class, the Attachment ID, image align value, and the size the image should be.
The second filter 'get_image_tag' has the HTML content, which can then be further manipulated by a plugin to change all attribute values and even HTML content.
Since
2.5.0
Parameters
int $id Attachment ID.
string $alt Image Description for the alt attribute.
string $title Image Description for the title attribute.
string $align Part of the class name for aligning the image.
string | array $size Optional. Registered image size to retrieve a tag for. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'medium'.
Returns
string HTML IMG element for given image attachment
Filter the value of the attachment's image tag class attribute.
Since
2.6.0
Parameters
string $class CSS class name or space-separated list of classes.
int $id Attachment ID.
string $align Part of the class name for aligning the image.
string | array $size Size of image. Image size or array of width and height values (in that order). Default 'medium'.
Filter the HTML content for the image tag.
Since
2.6.0
Parameters
string $html HTML content for the image.
int $id Attachment ID.
string $alt Alternate text.
string $title Attachment title.
string $align Part of the class name for aligning the image.
string | array $size Size of image. Image size or array of width and height values (in that order). Default 'medium'.
Definition at line 332 of file wp-includes/media.php.
References $alt, $class, $id, $size, $title, apply_filters(), esc_attr(), image_downsize(), and image_hwstring().
Referenced by get_image_send_to_editor().
get_intermediate_image_sizes ()
Gets the available intermediate image sizes.
Since
3.0.0
array $_wp_additional_image_sizes
Returns
array Returns a filtered array of image size strings.
Filter the list of intermediate image sizes.
Since
2.5.0
Parameters
array $image_sizes An array of intermediate image sizes. Defaults are 'thumbnail', 'medium', 'medium_large', 'large'.
Definition at line 716 of file wp-includes/media.php.
References apply_filters().
Referenced by wp_generate_attachment_metadata(), wp_restore_image(), and wp_save_image().
get_media_embedded_in_content ($content, $types = null)
Check the content blob for an audio, video, object, embed, or iframe tags.
Since
3.6.0
Parameters
string $content A string which might contain media data.
array $types An array of media types: 'audio', 'video', 'object', 'embed', or 'iframe'.
Returns
array A list of found HTML media embeds.
Filter the embedded media types that are allowed to be returned from the content blob.
Since
4.2.0
Parameters
array $allowed_media_types An array of allowed media types. Default media types are 'audio', 'video', 'object', 'embed', and 'iframe'.
Definition at line 3564 of file wp-includes/media.php.
References $content, $tags, $types, and apply_filters().
get_post_galleries ($post, $html = true)
Retrieves galleries from the passed post's content.
Since
3.6.0
Parameters
int | WP_Post $post Post ID or object.
bool $html Optional. Whether to return HTML or data in the array. Default true.
Returns
array A list of arrays, each containing gallery data and srcs parsed from the expanded shortcode.
Filter the list of all found galleries in the given post.
Since
3.6.0
Parameters
array $galleries Associative array of all found post galleries.
WP_Post $post Post object.
Definition at line 3606 of file wp-includes/media.php.
References $post, $s, apply_filters(), do_shortcode_tag(), get_post(), get_shortcode_regex(), has_shortcode(), and shortcode_parse_atts().
Referenced by get_post_galleries_images(), get_post_gallery(), twentyeleven_get_gallery_images(), twentyten_get_gallery_images(), and Twenty_Fourteen_Ephemera_Widget\widget().
get_post_galleries_images ($post = 0)
Retrieve the image srcs from galleries from a post's content, if present.
Since
3.6.0
See also
get_post_galleries()
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
array A list of lists, each containing image srcs parsed. from an expanded shortcode
Definition at line 3684 of file wp-includes/media.php.
References $post, get_post_galleries(), and wp_list_pluck().
get_post_gallery ($post = 0, $html = true)
Check a specified post's content for gallery and, if present, return the first.
Since
3.6.0
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
bool $html Optional. Whether to return HTML or data. Default is true.
Returns
string|array Gallery data and srcs parsed from the expanded shortcode.
Filter the first-found post gallery.
Since
3.6.0
Parameters
array $gallery The first-found post gallery.
int | WP_Post $post Post ID or object.
array $galleries Associative array of all found post galleries.
Definition at line 3657 of file wp-includes/media.php.
References $post, apply_filters(), and get_post_galleries().
Referenced by get_post_gallery_images().
get_post_gallery_images ($post = 0)
Checks a post's content for galleries and return the image srcs for the first found gallery.
Since
3.6.0
See also
get_post_gallery()
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
array A list of a gallery's image srcs in order.
Definition at line 3699 of file wp-includes/media.php.
References $post, and get_post_gallery().
get_taxonomies_for_attachments ($output = 'names')
Retrieves all of the taxonomy names that are registered for attachments.
Handles mime-type-specific taxonomies such as attachment:image and attachment:video.
Since
3.5.0
See also
get_taxonomies()
Parameters
string $output Optional. The type of taxonomy output to return. Accepts 'names' or 'objects'. Default 'names'.
Returns
array The names of all taxonomy of $object_type.
Definition at line 2724 of file wp-includes/media.php.
References $output, and get_taxonomies().
Referenced by WP_Media_List_Table\get_columns(), WP_Query\get_posts(), and wp_ajax_query_attachments().
has_image_size ($name)
Check if an image size exists.
Since
3.9.0
array $_wp_additional_image_sizes
Parameters
string $name The image size to check.
Returns
bool True if the image size exists, false if not.
Definition at line 266 of file wp-includes/media.php.
References $name.
image_constrain_size_for_editor ($width, $height, $size = 'medium', $context = null)
Scale down the default size of an image.
This is so that the image is a better fit for the editor and theme.
The $size parameter accepts either an array or a string. The supported string values are 'thumb' or 'thumbnail' for the given thumbnail size or defaults at 128 width and 96 height in pixels. Also supported for the string value is 'medium', 'medium_large' and 'full'. The 'full' isn't actually supported, but any value other than the supported will result in the content_width size or 500 if that is not set.
Finally, there is a filter named {
See also
'editor_max_image_size'}, that will be called on the calculated array for width and height, respectively. The second parameter will be the value that was in the $size parameter. The returned type for the hook is an array with the width as the first element and the height as the second element.
Since
2.5.0
int $content_width array $_wp_additional_image_sizes
Parameters
int $width Width of the image in pixels.
int $height Height of the image in pixels.
string | array $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'medium'.
string $context Optional. Could be 'display' (like in a theme) or 'edit' (like inserting into an editor). Default null.
Returns
array Width and height of what the result image should resize to.
Filter the maximum image size dimensions for the editor.
Since
2.5.0
Parameters
array $max_image_size An array with the width as the first element, and the height as the second element.
string | array $size Size of what the result image should be.
string $context The context the image is being resized for. Possible values are 'display' (like in a theme) or 'edit' (like inserting into an editor).
Definition at line 41 of file wp-includes/media.php.
References $size, apply_filters(), elseif, get_option(), is_admin(), and wp_constrain_dimensions().
Referenced by image_downsize(), image_get_intermediate_size(), and wp_prepare_attachment_for_js().
image_downsize ($id, $size = 'medium')
Scale an image to fit a particular size (such as 'thumb' or 'medium').
Array with image url, width, height, and whether is intermediate size, in that order is returned on success is returned. $is_intermediate is true if $url is a resized image, false if it is the original.
The URL might be the original image, or it might be a resized version. This function won't create a new resized copy, it will just return an already resized one if it exists.
A plugin may use the 'image_downsize' filter to hook into and offer image resizing services for images. The hook must return an array with the same elements that are returned in the function. The first element being the URL to the new image that was resized.
Since
2.5.0
Parameters
int $id Attachment ID for image.
array | string $size Optional. Image size to scale to. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'medium'.
Returns
false|array Array containing the image URL, width, height, and boolean for whether the image is an intermediate size. False on failure.
Filter whether to preempt the output of image_downsize().
Passing a truthy value to the filter will effectively short-circuit down-sizing the image, returning that value as output instead.
Since
2.5.0
Parameters
bool $downsize Whether to short-circuit the image downsize. Default false.
int $id Attachment ID for image.
array | string $size Size of image. Image size or array of width and height values (in that order). Default 'medium'.
Definition at line 165 of file wp-includes/media.php.
References $id, $out, $size, apply_filters(), elseif, image_constrain_size_for_editor(), image_get_intermediate_size(), str_replace, wp_attachment_is_image(), wp_basename(), wp_get_attachment_metadata(), wp_get_attachment_thumb_file(), and wp_get_attachment_url().
Referenced by wp_xmlrpc_server\_prepare_media_item(), get_image_tag(), image_size_input_fields(), wp_get_attachment_image_src(), and wp_get_attachment_thumb_url().
image_get_intermediate_size ($post_id, $size = 'thumbnail')
Retrieves the image's intermediate size (resized) path, width, and height.
The $size parameter can be an array with the width and height respectively. If the size matches the 'sizes' metadata array for width and height, then it will be used. If there is no direct match, then the nearest image size larger than the specified size will be used. If nothing is found, then the function will break out and return false.
The metadata 'sizes' is used for compatible sizes that can be used for the parameter $size value.
The url path will be given, when the $size parameter is a string.
If you are passing an array for the $size, you should consider using add_image_size() so that a cropped version is generated. It's much more efficient than having to find the closest-sized image and then having the browser scale down the image.
Since
2.5.0
Parameters
int $post_id Attachment ID.
array | string $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'thumbnail'.
Returns
false|array $data { Array of file relative path, width, and height on success. Additionally includes absolute path and URL if registered size is passed to $size parameter. False on failure.
string $file Image's path relative to uploads directory int $width Width of image int $height Height of image string $path Optional. Image's absolute filesystem path. Only returned if registered size is passed to $size parameter. string $url Optional. Image's URL. Only returned if registered size is passed to $size parameter. }
This filter is documented in wp-includes/media.php
This filter is documented in wp-includes/media.php
Filter the output of image_get_intermediate_size()
Since
4.4.0
See also
image_get_intermediate_size()
Parameters
array $data Array of file relative path, width, and height on success. May also include file absolute path and URL.
int $post_id The post_id of the image attachment
string | array $size Registered image size or flat array of initially-requested height and width dimensions (in that order).
Definition at line 632 of file wp-includes/media.php.
References $post_id, $size, apply_filters(), image_constrain_size_for_editor(), image_resize_dimensions(), path_join(), wp_get_attachment_metadata(), and wp_get_attachment_url().
Referenced by _load_image_to_edit_path(), image_downsize(), and wp_image_editor().
image_hwstring ($width, $height)
Retrieve width and height attributes using given width and height values.
Both attributes are required in the sense that both parameters must have a value, but are optional in that if you set them to false or null, then they will not be added to the returned string.
You can set the value using a string, but it will only take numeric values. If you wish to put 'px' after the numbers, then it will be stripped out of the return.
Since
2.5.0
Parameters
int | string $width Image width in pixels.
int | string $height Image height in pixels.
Returns
string HTML attributes for width and, or height.
Definition at line 131 of file wp-includes/media.php.
References $out.
Referenced by get_image_tag(), and wp_get_attachment_image().
image_make_intermediate_size ($file, $width, $height, $crop = false)
Resizes an image to make a thumbnail or intermediate size.
The returned array has the file size, the image width, and image height. The filter 'image_make_intermediate_size' can be used to hook in and change the values of the returned array. The only parameter is the resized file path.
Since
2.5.0
Parameters
string $file File path.
int $width Image width.
int $height Image height.
bool $crop Optional. Whether to crop image to specified width and height or resize. Default false.
Returns
false|array False, if no image was created. Metadata array on success.
Definition at line 577 of file wp-includes/media.php.
References $file, is_wp_error(), and wp_get_image_editor().
image_resize_dimensions ($orig_w, $orig_h, $dest_w, $dest_h, $crop = false)
Retrieves calculated resize dimensions for use in WP_Image_Editor.
Calculates dimensions and coordinates for a resized image that fits within a specified width and height.
Cropping behavior is dependent on the value of $crop:
If false (default), images will not be cropped.
If an array in the form of array(x_crop_position, y_crop_position):
x_crop_position accepts 'left' 'center', or 'right'.
y_crop_position accepts 'top', 'center', or 'bottom'. Images will be cropped to the specified dimensions within the defined crop area.
If true, images will be cropped to the specified dimensions using center positions.
Since
2.5.0
Parameters
int $orig_w Original width in pixels.
int $orig_h Original height in pixels.
int $dest_w New width in pixels.
int $dest_h New height in pixels.
bool | array $crop Optional. Whether to crop image to specified width and height or resize. An array can specify positioning of the crop area. Default false.
Returns
false|array False on failure. Returned array matches parameters for imagecopyresampled().
Filter whether to preempt calculating the image resize dimensions.
Passing a non-null value to the filter will effectively short-circuit image_resize_dimensions(), returning that value instead.
Since
3.4.0
Parameters
null | mixed $null Whether to preempt output of the resize dimensions.
int $orig_w Original width in pixels.
int $orig_h Original height in pixels.
int $dest_w New width in pixels.
int $dest_h New height in pixels.
bool | array $crop Whether to crop image to specified width and height or resize. An array can specify positioning of the crop area. Default false.
Definition at line 471 of file wp-includes/media.php.
References $output, apply_filters(), elseif, null, and wp_constrain_dimensions().
Referenced by WP_Image_Editor_GD\_resize(), image_get_intermediate_size(), and WP_Image_Editor_Imagick\resize().
img_caption_shortcode ($attr, $content = null)
Builds the Caption shortcode output.
Allows a plugin to replace the content that would otherwise be returned. The filter is 'img_caption_shortcode' and passes an empty string, the attr parameter and the content parameter values.
The supported attributes for the shortcode are 'id', 'align', 'width', and 'caption'.
Since
2.6.0
Parameters
array $attr { Attributes of the caption shortcode.
string $id ID of the div element for the caption. string $align Class name that aligns the caption. Default 'alignnone'. Accepts 'alignleft', 'aligncenter', alignright', 'alignnone'. int $width The width of the caption, in pixels. string $caption The caption text. string $class Additional class name(s) added to the caption container. }
Parameters
string $content Shortcode content.
Returns
string HTML content to display the caption.
Filter the default caption shortcode output.
If the filtered output isn't empty, it will be used instead of generating the default caption template.
Since
2.6.0
See also
img_caption_shortcode()
Parameters
string $output The caption output. Default empty.
array $attr Attributes of the caption shortcode.
string $content The image element, possibly wrapped in a hyperlink.
Filter the width of an image's caption.
By default, the caption is 10 pixels greater than the width of the image, to prevent post content from running up against a floated image.
Since
3.7.0
See also
img_caption_shortcode()
Parameters
int $width Width of the caption in pixels. To remove this inline style, return zero.
array $atts Attributes of the caption shortcode.
string $content The image element, possibly wrapped in a hyperlink.
Definition at line 1460 of file wp-includes/media.php.
References $class, $content, $output, apply_filters(), current_theme_supports(), do_shortcode(), elseif, esc_attr(), sanitize_html_class(), shortcode_atts(), and wp_kses().
next_image_link ($size = 'thumbnail', $text = false)
Displays next image link that has the same post parent.
Since
2.5.0
See also
adjacent_image_link()
Parameters
string | array $size Optional. Image size. Accepts any valid image size, an array of width and height values in pixels (in that order), 0, or 'none'. 0 or 'none' will default to 'post_title' or $text. Default 'thumbnail'.
string $text Optional. Link text. Default false.
Definition at line 2615 of file wp-includes/media.php.
References $size, $text, and adjacent_image_link().
previous_image_link ($size = 'thumbnail', $text = false)
Displays previous image link that has the same post parent.
Since
2.5.0
See also
adjacent_image_link()
Parameters
string | array $size Optional. Image size. Accepts any valid image size, an array of width and height values in pixels (in that order), 0, or 'none'. 0 or 'none' will default to 'post_title' or $text. Default 'thumbnail'.
string $text Optional. Link text. Default false.
Definition at line 2599 of file wp-includes/media.php.
References $size, $text, and adjacent_image_link().
remove_image_size ($name)
Remove a new image size.
Since
3.9.0
array $_wp_additional_image_sizes
Parameters
string $name The image size to remove.
Returns
bool True if the image size was successfully removed, false on failure.
Definition at line 282 of file wp-includes/media.php.
References $name.
set_post_thumbnail_size ($width = 0, $height = 0, $crop = false)
Registers an image size for the post thumbnail.
Since
2.9.0
See also
add_image_size() for details on cropping behavior.
Parameters
int $width Image width in pixels.
int $height Image height in pixels.
bool | array $crop Optional. Whether to crop images to specified width and height or resize. An array can specify positioning of the crop area. Default false.
Definition at line 305 of file wp-includes/media.php.
References add_image_size().
Referenced by twentythirteen_setup(), and twentytwelve_setup().
wp_audio_shortcode ($attr, $content = '')
Builds the Audio shortcode output.
This implements the functionality of the Audio Shortcode for displaying WordPress mp3s in a post.
Since
3.6.0
int $instance
Parameters
array $attr { Attributes of the audio shortcode.
string $src URL to the source of the audio file. Default empty. string $loop The 'loop' attribute for the <audio> element. Default empty. string $autoplay The 'autoplay' attribute for the <audio> element. Default empty. string $preload The 'preload' attribute for the <audio> element. Default 'none'. string $class The 'class' attribute for the <audio> element. Default 'wp-audio-shortcode'. string $style The 'style' attribute for the <audio> element. Default 'width: 100%; visibility: hidden;'. }
Parameters
string $content Shortcode content.
Returns
string|void HTML content to display audio.
Filter the default audio shortcode output.
If the filtered output isn't empty, it will be used instead of generating the default audio template.
Since
3.6.0
Parameters
string $html Empty variable to be replaced with shortcode markup.
array $attr Attributes of the shortcode.
See also
wp_audio_shortcode()
Parameters
string $content Shortcode content.
int $instance Unique numeric ID of this audio shortcode instance.
Filter the media library used for the audio shortcode.
Since
3.6.0
Parameters
string $library Media library used for the audio shortcode.
Filter the class attribute for the audio shortcode output container.
Since
3.6.0
Parameters
string $class CSS class or list of space-separated classes.
Filter the audio shortcode output.
Since
3.6.0
Parameters
string $html Audio shortcode HTML output.
array $atts Array of audio shortcode attributes.
string $audio Audio file.
int $post_id Post ID.
string $library Media library used for the audio shortcode.
Definition at line 2173 of file wp-includes/media.php.
References $content, $default_types, $post_id, $url, add_query_arg(), apply_filters(), did_action(), esc_attr(), esc_html, esc_url, get_attached_media(), get_post(), get_the_ID(), null, shortcode_atts(), wp_check_filetype(), wp_enqueue_script(), wp_enqueue_style(), wp_get_attachment_url(), wp_get_audio_extensions(), wp_get_mime_types(), wp_mediaelement_fallback(), and wp_validate_boolean().
Referenced by edit_form_image_editor(), GravityView_Field_FileUpload\get_files_array(), and prepend_attachment().
wp_calculate_image_sizes ($size, $image_src = null, $image_meta = null, $attachment_id = 0)
Creates a 'sizes' attribute value for an image.
Since
4.4.0
Parameters
array | string $size Image size to retrieve. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'medium'.
string $image_src Optional. The URL to the image file. Default null.
array $image_meta Optional. The image meta data as returned by 'wp_get_attachment_metadata()'. Default null.
int $attachment_id Optional. Image attachment ID. Either $image_meta or $attachment_id is needed when using the image size name as argument for $size. Default 0.
Returns
string|bool A valid source size value for use in a 'sizes' attribute or false.
Filter the output of 'wp_calculate_image_sizes()'.
Since
4.4.0
Parameters
string $sizes A source size value for use in a 'sizes' attribute.
array | string $size Requested size. Image size or array of width and height values in pixels (in that order).
string | null $image_src The URL to the image file or null.
array | null $image_meta The image meta data as returned by wp_get_attachment_metadata() or null.
int $attachment_id Image attachment ID of the original image or 0.
Definition at line 1211 of file wp-includes/media.php.
References $image_meta, $size, _wp_get_image_size_from_meta(), absint(), apply_filters(), elseif, and get_post_meta().
Referenced by get_header_image_tag(), wp_get_attachment_image(), wp_get_attachment_image_sizes(), and wp_image_add_srcset_and_sizes().
wp_calculate_image_srcset ($size_array, $image_src, $image_meta, $attachment_id = 0)
A helper function to calculate the image sources to include in a 'srcset' attribute.
Since
4.4.0
Parameters
array $size_array Array of width and height values in pixels (in that order).
string $image_src The 'src' of the image.
array $image_meta The image meta data as returned by 'wp_get_attachment_metadata()'.
int $attachment_id Optional. The image attachment ID to pass to the filter. Default 0.
Returns
string|bool The 'srcset' attribute value. False on error or when only one source exists.
Let plugins pre-filter the image meta to be able to fix inconsistencies in the stored data.
Parameters
array $image_meta The image meta data as returned by 'wp_get_attachment_metadata()'.
array $size_array Array of width and height values in pixels (in that order).
string $image_src The 'src' of the image.
int $attachment_id The image attachment ID or 0 if not supplied.
Filter the maximum image width to be included in a 'srcset' attribute.
Since
4.4.0
Parameters
int $max_width The maximum image width to be included in the 'srcset'. Default '1600'.
array $size_array Array of width and height values in pixels (in that order).
To make sure the ID matches our image src, we will check to see if any sizes in our attachment meta match our $image_src. If no mathces are found we don't return a srcset to avoid serving an incorrect image. See #35045.
To check for varying crops, we calculate the expected size of the smaller image if the larger were constrained by the width of the smaller and then see if it matches what we're expecting.
Filter an image's 'srcset' sources.
Since
4.4.0
Parameters
array $sources { One or more arrays of source data to include in the 'srcset'.
array $width { string $url The URL of an image source. string $descriptor The descriptor type used in the image candidate string, either 'w' or 'x'. int $value The source width if paired with a 'w' descriptor, or a pixel density value if paired with an 'x' descriptor. } }
Parameters
array $size_array Array of width and height values in pixels (in that order).
string $image_src The 'src' of the image.
array $image_meta The image meta data as returned by 'wp_get_attachment_metadata()'.
int $attachment_id Image attachment ID or 0.
Definition at line 998 of file wp-includes/media.php.
References $image, $image_meta, _wp_get_attachment_relative_path(), _wp_upload_dir_baseurl(), apply_filters(), elseif, trailingslashit(), wp_basename(), and wp_constrain_dimensions().
Referenced by get_header_image_tag(), wp_get_attachment_image(), wp_get_attachment_image_srcset(), and wp_image_add_srcset_and_sizes().
wp_constrain_dimensions ($current_width, $current_height, $max_width = 0, $max_height = 0)
Calculates the new dimensions for a down-sampled image.
If either width or height are empty, no constraint is applied on that dimension.
Since
2.5.0
Parameters
int $current_width Current width of the image.
int $current_height Current height of the image.
int $max_width Optional. Max width in pixels to constrain to. Default 0.
int $max_height Optional. Max height in pixels to constrain to. Default 0.
Returns
array First item is the width, the second item is the height.
Filter dimensions to constrain down-sampled images to.
Since
4.1.0
Parameters
array $dimensions The image width and height.
int $current_width The current width of the image.
int $current_height The current height of the image.
int $max_width The maximum width permitted.
int $max_height The maximum height permitted.
Definition at line 386 of file wp-includes/media.php.
References apply_filters().
Referenced by get_udims(), image_constrain_size_for_editor(), image_resize_dimensions(), wp_calculate_image_srcset(), wp_expand_dimensions(), wp_image_editor(), and wp_shrink_dimensions().
wp_convert_hr_to_bytes ($size)
Converts a shorthand byte value to an integer byte value.
Since
2.3.0
Parameters
string $size A shorthand byte value.
Returns
int An integer byte value.
Definition at line 2791 of file wp-includes/media.php.
References $size, elseif, and false.
Referenced by wp_max_upload_size().
wp_enqueue_media ($args = array())
Enqueues all scripts, styles, settings, and templates necessary to use all media JS APIs.
Since
3.5.0
int $content_width wpdb $wpdb WP_Locale $wp_locale
Parameters
array $args { Arguments for enqueuing media scripts.
int|WP_Post A post object or ID. }
This filter is documented in wp-admin/includes/media.php
This filter is documented in wp-admin/includes/media.php
Filter the media view settings.
Since
3.5.0
Parameters
array $settings List of media view settings.
WP_Post $post Post object.
Filter the media view strings.
Since
3.5.0
Parameters
array $strings List of media view strings.
WP_Post $post Post object.
Fires at the conclusion of wp_enqueue_media().
Since
3.5.0
Definition at line 3216 of file wp-includes/media.php.
References $post, $post_type_object, $tabs, $thumbnail_support, $wp_locale, $wpdb, __, _x, ABSPATH, add_action(), add_query_arg(), admin_url(), apply_filters(), current_theme_supports(), did_action(), do_action(), elseif, get_allowed_mime_types(), get_option(), get_post(), get_post_meta(), get_post_mime_types(), get_post_type_object(), is_admin(), null, post_type_supports(), wp_attachment_is(), wp_enqueue_script(), wp_enqueue_style(), wp_get_audio_extensions(), wp_get_video_extensions(), wp_list_pluck(), wp_localize_script(), wp_parse_args(), wp_plupload_default_settings(), and WPINC.
Referenced by Custom_Background\admin_load(), WP_Customize_Header_Image_Control\enqueue(), WP_Customize_Media_Control\enqueue(), WP_Press_This\html(), Custom_Image_Header\js_includes(), and media_buttons().
wp_expand_dimensions ($example_width, $example_height, $max_width, $max_height)
Based on a supplied width/height example, return the biggest possible dimensions based on the max width/height.
Since
2.9.0
See also
wp_constrain_dimensions()
Parameters
int $example_width The width of an example embed.
int $example_height The height of an example embed.
int $max_width The maximum allowed width.
int $max_height The maximum allowed height.
Returns
array The maximum possible width and height based on the example ratio.
Definition at line 2774 of file wp-includes/media.php.
References wp_constrain_dimensions().
Referenced by wp_embed_handler_googlevideo().
wp_get_attachment_id3_keys ($attachment, $context = 'display')
Returns useful keys to use to lookup data from an attachment's stored metadata.
Since
3.9.0
Parameters
WP_Post $attachment The current attachment, provided for context.
string $context Optional. The context. Accepts 'edit', 'display'. Default 'display'.
Returns
array Key/value pairs of field keys to labels.
Filter the editable list of keys to look up data from an attachment's metadata.
Since
3.9.0
Parameters
array $fields Key/value pairs of field keys to labels.
WP_Post $attachment Attachment object.
string $context The context. Accepts 'edit', 'display'. Default 'display'.
Definition at line 2124 of file wp-includes/media.php.
References __, _x, apply_filters(), and elseif.
Referenced by attachment_id3_data_meta_box(), edit_post(), wp_ajax_save_attachment(), wp_playlist_shortcode(), and wp_prepare_attachment_for_js().
wp_get_attachment_image ($attachment_id, $size = 'thumbnail', $icon = false, $attr = '')
Get an HTML img element representing an image attachment.
While $size will accept an array, it is better to register a size with add_image_size() so that a cropped version is generated. It's much more efficient than having to find the closest-sized image and then having the browser scale down the image.
Since
2.5.0
Parameters
int $attachment_id Image attachment ID.
string | array $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'thumbnail'.
bool $icon Optional. Whether the image should be treated as an icon. Default false.
string | array $attr Optional. Attributes for the image markup. Default empty.
Returns
string HTML img element or empty string on failure.
Filter the list of attachment image attributes.
Since
2.8.0
Parameters
array $attr Attributes for the image markup.
WP_Post $attachment Image attachment post.
string | array $size Requested size. Image size or array of width and height values (in that order). Default 'thumbnail'.
Definition at line 800 of file wp-includes/media.php.
References $image, $image_meta, $name, $size, $value, absint(), apply_filters(), get_post(), get_post_meta(), image_hwstring(), wp_calculate_image_sizes(), wp_calculate_image_srcset(), wp_get_attachment_image_src(), and wp_parse_args().
Referenced by _wp_post_thumbnail_html(), WP_Comments_List_Table\column_response(), WP_Media_List_Table\column_title(), gallery_shortcode(), get_the_post_thumbnail(), set_post_thumbnail(), Twenty_Fourteen_Ephemera_Widget\widget(), and wp_get_attachment_link().
wp_get_attachment_image_sizes ($attachment_id, $size = 'medium', $image_meta = null)
Retrieves the value for an image attachment's 'sizes' attribute.
Since
4.4.0
See also
wp_calculate_image_sizes()
Parameters
int $attachment_id Image attachment ID.
array | string $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'medium'.
array $image_meta Optional. The image meta data as returned by 'wp_get_attachment_metadata()'. Default null.
Returns
string|bool A valid source size value for use in a 'sizes' attribute or false.
Definition at line 1179 of file wp-includes/media.php.
References $image, $image_meta, $size, absint(), get_post_meta(), wp_calculate_image_sizes(), and wp_get_attachment_image_src().
wp_get_attachment_image_src ($attachment_id, $size = 'thumbnail', $icon = false)
Retrieve an image to represent an attachment.
A mime icon for files, thumbnail or intermediate size for images.
The returned array contains four values: the URL of the attachment image src, the width of the image file, the height of the image file, and a boolean representing whether the returned array describes an intermediate (generated) image size or the original, full-sized upload.
Since
2.5.0
Parameters
int $attachment_id Image attachment ID.
string | array $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'thumbnail'.
bool $icon Optional. Whether the image should be treated as an icon. Default false.
Returns
false|array Returns an array (url, width, height, is_intermediate), or false, if no image is available.
This filter is documented in wp-includes/post.php
Filter the image src result.
Since
4.3.0
Parameters
array | false $image Either array with src, width & height, icon src, or false.
int $attachment_id Image attachment ID.
string | array $size Size of image. Image size or array of width and height values (in that order). Default 'thumbnail'.
bool $icon Whether the image should be treated as an icon. Default false.
Definition at line 751 of file wp-includes/media.php.
References $image, $size, ABSPATH, apply_filters(), image_downsize(), wp_basename(), wp_mime_type_icon(), and WPINC.
Referenced by edit_form_image_editor(), get_media_item(), get_oembed_response_data_rich(), Custom_Image_Header\step_2(), twentyfifteen_post_nav_background(), wp_get_attachment_image(), wp_get_attachment_image_sizes(), wp_get_attachment_image_srcset(), wp_get_attachment_image_url(), wp_playlist_shortcode(), wp_prepare_attachment_for_js(), and wp_save_image().
wp_get_attachment_image_srcset ($attachment_id, $size = 'medium', $image_meta = null)
Retrieves the value for an image attachment's 'srcset' attribute.
Since
4.4.0
See also
wp_calculate_image_srcset()
Parameters
int $attachment_id Image attachment ID.
array | string $size Optional. Image size. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'medium'.
array $image_meta Optional. The image meta data as returned by 'wp_get_attachment_metadata()'. Default null.
Returns
string|bool A 'srcset' value string or false.
Definition at line 969 of file wp-includes/media.php.
References $image, $image_meta, $size, absint(), get_post_meta(), wp_calculate_image_srcset(), and wp_get_attachment_image_src().
wp_get_attachment_image_url ($attachment_id, $size = 'thumbnail', $icon = false)
Get the URL of an image attachment.
Since
4.4.0
Parameters
int $attachment_id Image attachment ID.
string | array $size Optional. Image size to retrieve. Accepts any valid image size, or an array of width and height values in pixels (in that order). Default 'thumbnail'.
bool $icon Optional. Whether the image should be treated as an icon. Default false.
Returns
string|false Attachment URL or false if no image is available.
Definition at line 875 of file wp-includes/media.php.
References $image, $size, and wp_get_attachment_image_src().
Referenced by get_site_icon_url(), and get_the_post_thumbnail_url().
wp_get_audio_extensions ()
Returns a filtered list of WP-supported audio formats.
Since
3.6.0
Returns
array Supported audio formats.
Filter the list of supported audio formats.
Since
3.6.0
Parameters
array $extensions An array of support audio formats. Defaults are 'mp3', 'ogg', 'wma', 'm4a', 'wav'.
Definition at line 2103 of file wp-includes/media.php.
References apply_filters().
Referenced by GravityView_Field_FileUpload\get_files_array(), populate_network(), wp_attachment_is(), wp_audio_shortcode(), wp_enqueue_media(), wp_maybe_load_embeds(), wp_print_media_templates(), and wp_underscore_audio_template().
wp_get_image_editor ($path, $args = array())
Returns a WP_Image_Editor instance and loads file into it.
Since
3.5.0
Parameters
string $path Path to the file to load.
array $args Optional. Additional arguments for retrieving the image editor. Default empty array.
Returns
WP_Image_Editor|WP_Error The WP_Image_Editor object if successful, an WP_Error object otherwise.
Definition at line 2837 of file wp-includes/media.php.
References $path, __, _wp_image_editor_choose(), is_wp_error(), and wp_check_filetype().
Referenced by image_make_intermediate_size(), image_resize(), stream_preview_image(), wp_crop_image(), wp_generate_attachment_metadata(), and wp_save_image().
wp_get_video_extensions ()
Returns a filtered list of WP-supported video formats.
Since
3.6.0
Returns
array List of supported video formats.
Filter the list of supported video formats.
Since
3.6.0
Parameters
array $extensions An array of support video formats. Defaults are 'mp4', 'm4v', 'webm', 'ogv', 'wmv', 'flv'.
Definition at line 2336 of file wp-includes/media.php.
References apply_filters().
Referenced by GravityView_Field_FileUpload\get_files_array(), populate_network(), wp_attachment_is(), wp_enqueue_media(), wp_maybe_load_embeds(), wp_print_media_templates(), wp_underscore_video_template(), and wp_video_shortcode().
wp_image_add_srcset_and_sizes ($image, $image_meta, $attachment_id)
Adds 'srcset' and 'sizes' attributes to an existing 'img' element.
Since
4.4.0
See also
wp_calculate_image_srcset()
wp_calculate_image_sizes()
Parameters
string $image An HTML 'img' element to be filtered.
array $image_meta The image meta data as returned by 'wp_get_attachment_metadata()'.
int $attachment_id Image attachment ID.
Returns
string Converted 'img' element with 'srcset' and 'sizes' attributes added.
Definition at line 1313 of file wp-includes/media.php.
References $image, $image_meta, esc_attr(), wp_basename(), wp_calculate_image_sizes(), and wp_calculate_image_srcset().
Referenced by wp_make_content_images_responsive().
wp_image_editor_supports ($args = array())
Tests whether there is an editor that supports a given mime type or methods.
Since
3.5.0
Parameters
string | array $args Optional. Array of arguments to retrieve the image editor supports. Default empty array.
Returns
bool True if an eligible editor is found; false otherwise.
Definition at line 2873 of file wp-includes/media.php.
References _wp_image_editor_choose().
Referenced by edit_form_image_editor(), get_media_item(), and wp_image_editor().
wp_imagecreatetruecolor ($width, $height)
Create new GD image resource with transparency support.
Since
2.9.0
Parameters
int $width Image width in pixels.
int $height Image height in pixels..
Returns
resource The GD image resource.
Definition at line 2752 of file wp-includes/media.php.
Referenced by _crop_image_resource(), _flip_image_resource(), WP_Image_Editor_GD\_resize(), WP_Image_Editor_GD\crop(), and WP_Image_Editor_GD\flip().
wp_make_content_images_responsive ($content)
Filters 'img' elements in post content to add 'srcset' and 'sizes' attributes.
Since
4.4.0
See also
wp_image_add_srcset_and_sizes()
Parameters
string $content The raw post content to be filtered.
Returns
string Converted content with 'srcset' and 'sizes' attributes added to images.
Definition at line 1261 of file wp-includes/media.php.
References $content, $image, $image_meta, absint(), get_post_meta(), str_replace, update_meta_cache(), and wp_image_add_srcset_and_sizes().
wp_max_upload_size ()
Determines the maximum upload size allowed in php.ini.
Since
2.5.0
Returns
int Allowed upload size.
Filter the maximum upload size allowed in php.ini.
Since
2.5.0
Parameters
int $size Max upload size limit in bytes.
int $u_bytes Maximum upload filesize in bytes.
int $p_bytes Maximum size of POST data in bytes.
Definition at line 2810 of file wp-includes/media.php.
References apply_filters(), and wp_convert_hr_to_bytes().
Referenced by GF_Field_FileUpload\get_field_input(), media_upload_form(), GFAsyncUpload\upload(), GF_Field_FileUpload\validate(), wp_import_upload_form(), wp_plupload_default_settings(), and wp_print_media_templates().
wp_maybe_generate_attachment_metadata ($attachment)
Maybe attempts to generate attachment metadata, if missing.
Since
3.9.0
Parameters
WP_Post $attachment Attachment object.
Definition at line 3711 of file wp-includes/media.php.
References $file, delete_transient(), get_attached_file(), get_post_meta(), get_transient(), set_transient(), wp_generate_attachment_metadata(), wp_get_attachment_metadata(), and wp_update_attachment_metadata().
Referenced by edit_form_image_editor().
wp_mediaelement_fallback ($url)
Provides a No-JS Flash fallback as a last resort for audio / video.
Since
3.6.0
Parameters
string $url The media element URL.
Returns
string Fallback HTML.
Filter the Mediaelement fallback output for no-JS.
Since
3.6.0
Parameters
string $output Fallback output for no-JS.
string $url Media file URL.
Definition at line 2084 of file wp-includes/media.php.
References $url, apply_filters(), and esc_url.
Referenced by wp_audio_shortcode(), and wp_video_shortcode().
wp_playlist_scripts ($type)
Outputs and enqueue default scripts and styles for playlists.
Since
3.9.0
Parameters
string $type Type of playlist. Accepts 'audio' or 'video'.
Definition at line 1817 of file wp-includes/media.php.
References add_action(), endif, wp_enqueue_script(), and wp_enqueue_style().
wp_playlist_shortcode ($attr)
Builds the Playlist shortcode output.
This implements the functionality of the playlist shortcode for displaying a collection of WordPress audio or video files in a post.
Since
3.9.0
int $content_width int $instance
Parameters
array $attr { Array of default playlist attributes.
string $type Type of playlist to display. Accepts 'audio' or 'video'. Default 'audio'. string $order Designates ascending or descending order of items in the playlist. Accepts 'ASC', 'DESC'. Default 'ASC'. string $orderby Any column, or columns, to sort the playlist. If $ids are passed, this defaults to the order of the $ids array ('post__in'). Otherwise default is 'menu_order ID'. int $id If an explicit $ids array is not present, this parameter will determine which attachments are used for the playlist. Default is the current post ID. array $ids Create a playlist out of these explicit attachment IDs. If empty, a playlist will be created from all $type attachments of $id. Default empty. array $exclude List of specific attachment IDs to exclude from the playlist. Default empty. string $style Playlist style to use. Accepts 'light' or 'dark'. Default 'light'. bool $tracklist Whether to show or hide the playlist. Default true. bool $tracknumbers Whether to show or hide the numbers next to entries in the playlist. Default true. bool $images Show or hide the video or audio thumbnail (Featured Image/post thumbnail). Default true. bool $artists Whether to show or hide artist name in the playlist. Default true. }
Returns
string Playlist output. Empty string if the passed type is unsupported.
Filter the playlist output.
Passing a non-empty value to the filter will short-circuit generation of the default playlist output, returning the passed value instead.
Since
3.9.0
4.2.0 The $instance parameter was added.
Parameters
string $output Playlist output. Default empty.
array $attr An array of shortcode attributes.
int $instance Unique numeric ID of this playlist shortcode instance.
Print and enqueue playlist scripts, styles, and JavaScript templates.
Since
3.9.0
Parameters
string $type Type of playlist. Possible values are 'audio' or 'video'.
string $style The 'theme' for the playlist. Core provides 'light' and 'dark'.
Definition at line 1864 of file wp-includes/media.php.
References $attachments, $id, $label, $output, $post, $url, apply_filters(), do_action(), elseif, endif, esc_attr(), get_children(), get_post(), get_post_thumbnail_id(), get_posts(), is_feed(), shortcode_atts(), width, wp_check_filetype(), wp_get_attachment_id3_keys(), wp_get_attachment_image_src(), wp_get_attachment_link(), wp_get_attachment_metadata(), wp_get_attachment_url(), wp_get_mime_types(), wp_json_encode(), wp_mime_type_icon(), and wp_validate_boolean().
wp_plupload_default_settings ()
Prints default plupload arguments.
Since
3.4.0
Filter the Plupload default settings.
Since
3.4.0
Parameters
array $defaults Default Plupload settings array.
Filter the Plupload default parameters.
Since
3.4.0
Parameters
array $params Default Plupload parameters array.
Definition at line 2929 of file wp-includes/media.php.
References $_SERVER, $wp_scripts, _device_can_upload(), admin_url(), apply_filters(), includes_url(), is_multisite(), is_upload_space_available(), wp_is_mobile(), wp_json_encode(), wp_max_upload_size(), and wp_scripts().
Referenced by wp_enqueue_media().
wp_prepare_attachment_for_js ($attachment)
Prepares an attachment post object for JS, where it is expected to be JSON-encoded and fit into an Attachment model.
Since
3.5.0
Parameters
mixed $attachment Attachment ID or object.
Returns
array|void Array of attachment details.
This filter is documented in wp-admin/includes/media.php
This filter is documented in wp-includes/media.php
Filter the attachment data prepared for JavaScript.
Since
3.5.0
Parameters
array $response Array of prepared attachment data.
int | object $attachment Attachment ID or object.
array $meta Array of attachment meta data.
Definition at line 3007 of file wp-includes/media.php.
References $base_url, $id, $label, $size, __, apply_filters(), current_user_can(), elseif, get_attached_file(), get_attachment_link(), get_compat_media_markup(), get_edit_post_link(), get_post(), get_post_meta(), get_post_thumbnail_id(), get_post_type_object(), image_constrain_size_for_editor(), mysql2date(), size_format(), str_replace, wp_basename(), wp_get_attachment_id3_keys(), wp_get_attachment_image_src(), wp_get_attachment_metadata(), wp_get_attachment_url(), and wp_mime_type_icon().
Referenced by WP_Customize_Upload_Control\to_json(), WP_Customize_Media_Control\to_json(), wp_ajax_crop_image(), wp_ajax_get_attachment(), wp_ajax_save_attachment_compat(), and wp_ajax_upload_attachment().
wp_underscore_playlist_templates ()
Outputs the templates used by playlists.
Since
3.9.0
Definition at line 1771 of file wp-includes/media.php.
References _x, and mdash.
Referenced by wp_ajax_parse_media_shortcode().
wp_video_shortcode ($attr, $content = '')
Builds the Video shortcode output.
This implements the functionality of the Video Shortcode for displaying WordPress mp4s in a post.
Since
3.6.0
int $content_width int $instance
Parameters
array $attr { Attributes of the shortcode.
string $src URL to the source of the video file. Default empty. int $height Height of the video embed in pixels. Default 360. int $width Width of the video embed in pixels. Default $content_width or 640. string $poster The 'poster' attribute for the <video> element. Default empty. string $loop The 'loop' attribute for the <video> element. Default empty. string $autoplay The 'autoplay' attribute for the <video> element. Default empty. string $preload The 'preload' attribute for the <video> element. Default 'metadata'. string $class The 'class' attribute for the <video> element. Default 'wp-video-shortcode'. }
Parameters
string $content Shortcode content.
Returns
string|void HTML content to display video.
Filter the default video shortcode output.
If the filtered output isn't empty, it will be used instead of generating the default video template.
Since
3.6.0
See also
wp_video_shortcode()
Parameters
string $html Empty variable to be replaced with shortcode markup.
array $attr Attributes of the video shortcode.
string $content Video shortcode content.
int $instance Unique numeric ID of this video shortcode instance.
Filter the media library used for the video shortcode.
Since
3.6.0
Parameters
string $library Media library used for the video shortcode.
Filter the class attribute for the video shortcode output container.
Since
3.6.0
Parameters
string $class CSS class or list of space-separated classes.
Filter the output of the video shortcode.
Since
3.6.0
Parameters
string $output Video shortcode HTML output.
array $atts Array of video shortcode attributes.
string $video Video file.
int $post_id Post ID.
string $library Media library used for the video shortcode.
Definition at line 2376 of file wp-includes/media.php.
References $content, $default_types, $output, $post_id, $url, absint(), add_query_arg(), apply_filters(), did_action(), elseif, esc_attr(), esc_html, esc_url, get_attached_media(), get_post(), get_the_ID(), is_admin(), null, shortcode_atts(), str_replace, wp_check_filetype(), wp_enqueue_script(), wp_enqueue_style(), wp_get_attachment_url(), wp_get_mime_types(), wp_get_video_extensions(), wp_mediaelement_fallback(), and wp_validate_boolean().
Referenced by edit_form_image_editor(), GravityView_Field_FileUpload\get_files_array(), and prepend_attachment().
wpview_media_sandbox_styles ()
Returns the URLs for CSS files used in an iframe-sandbox'd TinyMCE media view.
Since
4.0.0
string $wp_version
Returns
array The relevant CSS file URLs.
Definition at line 3783 of file wp-includes/media.php.
References $GLOBALS, and includes_url().
Referenced by wp_ajax_parse_embed(), and wp_ajax_parse_media_shortcode().