GravityView: revision.php File Reference
wp-includes/revision.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_set_preview ($post)
Sets up the post object for preview based on the post autosave.
_show_post_preview ()
Filters the latest content for preview from the post autosave.
_wp_get_post_revision_version ($revision)
Gets the post revision version.
_wp_post_revision_fields ($post=null, $autosave=false)
Determines which fields of posts are to be saved in revisions.
_wp_preview_terms_filter ($terms, $post_id, $taxonomy)
Filters terms lookup to set the post format.
_wp_put_post_revision ($post=null, $autosave=false)
Inserts post data into the posts table as a post revision.
_wp_upgrade_revisions_of_post ($post, $revisions)
Upgrade the revisions author, add the current post as a revision and set the revisions version to 1.
wp_delete_post_revision ($revision_id)
Deletes a revision.
wp_get_post_autosave ($post_id, $user_id=0)
Retrieve the autosaved data of the specified post.
wp_get_post_revision (&$post, $output=OBJECT, $filter= 'raw')
Gets a post revision.
wp_get_post_revisions ($post_id=0, $args=null)
Returns all revisions of specified post.
wp_is_post_autosave ($post)
Determines if the specified post is an autosave.
wp_is_post_revision ($post)
Determines if the specified post is a revision.
wp_restore_post_revision ($revision_id, $fields=null)
Restores a post to the specified revision.
wp_revisions_enabled ($post)
Determine if revisions are enabled for a given post.
wp_revisions_to_keep ($post)
Determine how many revisions to retain for a given post.
wp_save_post_revision ($post_id)
Creates a revision for the current version of a post.
Function Documentation
_set_preview ($post)
Sets up the post object for preview based on the post autosave.
Since
2.7.0 private
Parameters
WP_Post $post
Returns
WP_Post|false
Definition at line 497 of file wp-includes/revision.php.
References $post, add_filter(), sanitize_post(), and wp_get_post_autosave().
_show_post_preview ()
Filters the latest content for preview from the post autosave.
Since
2.7.0 private
Definition at line 524 of file wp-includes/revision.php.
References $id, __, add_filter(), and wp_die().
_wp_get_post_revision_version ($revision)
Gets the post revision version.
Since
3.6.0 private
Parameters
WP_Post $revision
Returns
int|false
Definition at line 570 of file wp-includes/revision.php.
References elseif.
Referenced by _wp_upgrade_revisions_of_post(), and edit_post().
_wp_post_revision_fields ($post = null, $autosave = false)
Determines which fields of posts are to be saved in revisions.
Does two things. If passed a post array, it will return a post array ready to be inserted into the posts table as a post revision. Otherwise, returns an array whose keys are the post fields to be saved for post revisions.
Since
2.6.0 private
array $fields
Parameters
array | null $post Optional. A post array to be processed for insertion as a post revision. Default null.
bool $autosave Optional. Is the revision an autosave? Default false.
Returns
array Post array ready to be inserted as a post revision or array of fields that can be versioned.
Filter the list of fields saved in post revisions.
Included by default: 'post_title', 'post_content' and 'post_excerpt'.
Disallowed fields: 'ID', 'post_name', 'post_parent', 'post_date', 'post_date_gmt', 'post_status', 'post_type', 'comment_count', and 'post_author'.
Since
2.6.0
Parameters
array $fields List of fields to revision. Contains 'post_title', 'post_content', and 'post_excerpt' by default.
Definition at line 25 of file wp-includes/revision.php.
References $field, $post, __, apply_filters(), and null.
Referenced by _wp_put_post_revision(), wp_get_revision_ui_diff(), wp_restore_post_revision(), and wp_save_post_revision().
_wp_preview_terms_filter ($terms, $post_id, $taxonomy)
Filters terms lookup to set the post format.
Since
3.6.0 private
Parameters
array $terms
int $post_id
string $taxonomy
Returns
array
Definition at line 546 of file wp-includes/revision.php.
References $post, $post_id, elseif, get_post(), get_term_by(), and sanitize_key().
_wp_put_post_revision ($post = null, $autosave = false)
Inserts post data into the posts table as a post revision.
Since
2.6.0 private
Parameters
int | WP_Post | array | null $post Post ID, post object OR post array.
bool $autosave Optional. Is the revision an autosave?
Returns
int|WP_Error WP_Error or 0 if error, new revision ID if success.
Fires once a revision has been saved.
Since
2.6.0
Parameters
int $revision_id Post revision ID.
Definition at line 258 of file wp-includes/revision.php.
References $post, $revision_id, __, _wp_post_revision_fields(), ARRAY_A, do_action(), elseif, get_post(), is_wp_error(), wp_insert_post(), and wp_slash().
Referenced by wp_save_post_revision().
_wp_upgrade_revisions_of_post ($post, $revisions)
Upgrade the revisions author, add the current post as a revision and set the revisions version to 1.
Since
3.6.0 private
wpdb $wpdb WordPress database abstraction object.
Parameters
WP_Post $post Post object
array $revisions Current revisions of the post
Returns
bool true if the revisions were upgraded, false if problems
Definition at line 594 of file wp-includes/revision.php.
References $now, $post, $update, $wpdb, _wp_get_post_revision_version(), delete_option(), get_option(), update_option(), wp_cache_delete(), and wp_save_post_revision().
Referenced by edit_post().
wp_delete_post_revision ($revision_id)
Deletes a revision.
Deletes the row from the posts table corresponding to the specified revision.
Since
2.6.0
Parameters
int | WP_Post $revision_id Revision ID or revision object.
Returns
array|false|WP_Post|WP_Error|null Null or WP_Error if error, deleted post if success.
Fires once a post revision has been deleted.
Since
2.6.0
Parameters
int $revision_id Post revision ID.
object | array $revision Post revision object or array.
Definition at line 388 of file wp-includes/revision.php.
References $revision_id, do_action(), wp_delete_post(), and wp_get_post_revision().
Referenced by wp_delete_post(), and wp_save_post_revision().
wp_get_post_autosave ($post_id, $user_id = 0)
Retrieve the autosaved data of the specified post.
Returns a post object containing the information that was autosaved for the specified post. If the optional $user_id is passed, returns the autosave for that user otherwise returns the latest autosave.
Since
2.6.0
Parameters
int $post_id The post ID.
int $user_id Optional The post author ID.
Returns
WP_Post|false The autosaved data or false on failure or when no autosave exists.
Definition at line 200 of file wp-includes/revision.php.
References $post_id, $user_id, and wp_get_post_revisions().
Referenced by _set_preview().
wp_get_post_revision (& $post, $output = OBJECT, $filter = 'raw')
Gets a post revision.
Since
2.6.0
Parameters
int | WP_Post $post The post ID or object.
string $output Optional. OBJECT, ARRAY_A, or ARRAY_N.
string $filter Optional sanitation filter.
See also
sanitize_post().
Returns
WP_Post|array|null Null if error or post object if success.
Definition at line 301 of file wp-includes/revision.php.
References $output, $post, ARRAY_A, ARRAY_N, elseif, get_post(), null, and OBJECT.
Referenced by wp_delete_post_revision(), wp_is_post_autosave(), wp_is_post_revision(), wp_restore_post_revision(), and wp_xmlrpc_server\wp_restoreRevision().
wp_get_post_revisions ($post_id = 0, $args = null)
Returns all revisions of specified post.
Since
2.6.0
See also
get_children()
Parameters
int | WP_Post $post_id Optional. Post ID or WP_Post object. Default is global $post.
array | null $args Optional. Arguments for retrieving post revisions. Default null.
Returns
array An array of revisions, or an empty array if none.
Definition at line 420 of file wp-includes/revision.php.
References $post, $post_id, get_children(), get_post(), wp_parse_args(), and wp_revisions_enabled().
Referenced by edit_post(), wp_ajax_get_revision_diffs(), wp_get_post_autosave(), wp_xmlrpc_server\wp_getRevisions(), wp_list_post_revisions(), wp_prepare_revisions_for_js(), and wp_save_post_revision().
wp_is_post_autosave ($post)
Determines if the specified post is an autosave.
Since
2.6.0
Parameters
int | WP_Post $post Post ID or post object.
Returns
false|int False if not a revision, ID of autosave's parent otherwise
Definition at line 238 of file wp-includes/revision.php.
References $post, and wp_get_post_revision().
Referenced by wp_xmlrpc_server\wp_getRevisions(), wp_list_post_revisions(), wp_post_revision_title(), wp_post_revision_title_expanded(), wp_prepare_revisions_for_js(), and wp_xmlrpc_server\wp_restoreRevision().
wp_is_post_revision ($post)
Determines if the specified post is a revision.
Since
2.6.0
Parameters
int | WP_Post $post Post ID or post object.
Returns
false|int False if not a revision, ID of revision's parent otherwise.
Definition at line 223 of file wp-includes/revision.php.
References $post, and wp_get_post_revision().
Referenced by add_post_meta(), delete_post_meta(), update_post_meta(), wp_post_revision_title(), and wp_post_revision_title_expanded().
wp_restore_post_revision ($revision_id, $fields = null)
Restores a post to the specified revision.
Can restore a past revision using all fields of the post revision, or only selected fields.
Since
2.6.0
Parameters
int | WP_Post $revision_id Revision ID or revision object.
array $fields Optional. What fields to restore from. Defaults to all.
Returns
int|false|null Null if error, false if no fields to restore, (int) post ID if success.
Fires after a post revision has been restored.
Since
2.6.0
Parameters
int $post_id Post ID.
int $revision_id Post revision ID.
Definition at line 331 of file wp-includes/revision.php.
References $field, $post_id, $revision_id, $update, _wp_post_revision_fields(), ARRAY_A, do_action(), get_current_user_id(), is_wp_error(), update_post_meta(), wp_get_post_revision(), wp_slash(), and wp_update_post().
Referenced by wp_xmlrpc_server\wp_restoreRevision().
wp_revisions_enabled ($post)
Determine if revisions are enabled for a given post.
Since
3.6.0
Parameters
WP_Post $post The post object.
Returns
bool True if number of revisions to keep isn't zero, false otherwise.
Definition at line 447 of file wp-includes/revision.php.
References $post, and wp_revisions_to_keep().
Referenced by wp_get_post_revisions(), wp_xmlrpc_server\wp_getRevisions(), wp_prepare_revisions_for_js(), wp_xmlrpc_server\wp_restoreRevision(), and wp_save_post_revision().
wp_revisions_to_keep ($post)
Determine how many revisions to retain for a given post.
By default, an infinite number of revisions are kept.
The constant WP_POST_REVISIONS can be set in wp-config to specify the limit of revisions to keep.
Since
3.6.0
Parameters
WP_Post $post The post object.
Returns
int The number of revisions to keep.
Filter the number of revisions to save for the given post.
Overrides the value of WP_POST_REVISIONS.
Since
3.6.0
Parameters
int $num Number of revisions to store.
WP_Post $post Post object.
Definition at line 464 of file wp-includes/revision.php.
References $post, apply_filters(), and post_type_supports().
Referenced by post_submit_meta_box(), wp_revisions_enabled(), and wp_save_post_revision().
wp_save_post_revision ($post_id)
Creates a revision for the current version of a post.
Typically used immediately after a post update, as every update is a revision, and the most recent revision always matches the current post.
Since
2.6.0
Parameters
int $post_id The ID of the post to save as a revision.
Returns
int|WP_Error|void Void or 0 if error, new revision ID, if success.
Filter whether the post has changed since the last revision.
By default a revision is saved only if one of the revisioned fields has changed. This filter can override that so a revision is saved even if nothing has changed.
Since
3.6.0
Parameters
bool $check_for_changes Whether to check for changes before saving a new revision. Default true.
WP_Post $last_revision The last revision post object.
WP_Post $post The post object.
Filter whether a post has changed.
By default a revision is saved only if one of the revisioned fields has changed. This filter allows for additional checks to determine if there were changes.
Since
4.1.0
Parameters
bool $post_has_changed Whether the post has changed.
WP_Post $last_revision The last revision post object.
WP_Post $post The post object.
Definition at line 85 of file wp-includes/revision.php.
References $field, $i, $post, $post_id, _wp_post_revision_fields(), _wp_put_post_revision(), apply_filters(), get_post(), normalize_whitespace(), post_type_supports(), wp_delete_post_revision(), wp_get_post_revisions(), wp_revisions_enabled(), and wp_revisions_to_keep().
Referenced by _wp_upgrade_revisions_of_post().