GravityView: deprecated.php File Reference
wp-includes/deprecated.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
__ngettext ()
Retrieve the plural or single form based on the amount.
__ngettext_noop ()
Register plural strings in POT file, but don't translate them.
_c ($text, $domain= 'default')
Retrieve translated string with vertical bar context.
_get_post_ancestors (&$post)
Retrieve post ancestors.
_nc ($single, $plural, $number, $domain= 'default')
Legacy version of _n(), which supports contexts.
_preview_theme_stylesheet_filter ()
Private function to modify the current stylesheet when previewing a theme.
_preview_theme_template_filter ()
Private function to modify the current template when previewing a theme.
_save_post_hook ()
Callback formerly fired on the save_post hook.
_search_terms_tidy ($t)
Formerly used internally to tidy up the search terms.
add_custom_background ($wp_head_callback= '', $admin_head_callback= '', $admin_preview_callback= '')
Add callbacks for background image display.
add_custom_image_header ($wp_head_callback, $admin_head_callback, $admin_preview_callback= '')
Add callbacks for image header display.
attribute_escape ($text)
Escaping for HTML attributes.
automatic_feed_links ($add=true)
Enable/disable automatic general feed link outputting.
clean_page_cache ($id)
Will clean the page in the cache.
clean_pre ($matches)
Accepts matches array from preg_replace_callback in wpautop() or a string.
clean_url ($url, $protocols=null, $context= 'display')
Checks and cleans a URL.
comments_popup_script ()
Display the JS popup script to show a comment.
comments_rss ()
Return link to the post RSS feed.
comments_rss_link ($link_text= 'Comments RSS')
Print RSS comment feed link.
create_user ($username, $password, $email)
An alias of wp_create_user().
debug_fclose ($fp)
Close the debugging file handle.
debug_fopen ($filename, $mode)
Open the file handle for debugging.
debug_fwrite ($fp, $string)
Write contents to the file used for debugging.
default_topic_count_text ($count)
Old callback for tag link tooltips.
delete_usermeta ($user_id, $meta_key, $meta_value= '')
Remove user meta data.
dropdown_cats ($optionall=1, $all= 'All', $orderby= 'ID', $order= 'asc', $show_last_update=0, $show_count=0, $hide_empty=1, $optionnone=false, $selected=0, $exclude=0)
Deprecated method for generating a drop-down of categories.
force_ssl_login ($force=null)
Whether SSL login should be forced.
format_to_post ($content)
Formerly used to escape strings before inserting into the DB.
funky_javascript_callback ($matches)
Callback used to change uXXXX to &#YYY; syntax.
funky_javascript_fix ($text)
Fixes JavaScript bugs in browsers.
gd_edit_image_support ($mime_type)
Check if the installed version of GD supports particular image type.
get_all_category_ids ()
Retrieves all category IDs.
get_alloptions ()
Retrieve all autoload options, or all options if no autoloaded ones exist.
get_archives ($type='', $limit='', $format='html', $before= '', $after= '', $show_post_count=false)
Retrieves a list of archives.
get_attachment_icon ($id=0, $fullsize=false, $max_dims=false)
Retrieve HTML content of icon attachment image element.
get_attachment_icon_src ($id=0, $fullsize=false)
Retrieve icon URL and Path.
get_attachment_innerHTML ($id=0, $fullsize=false, $max_dims=false)
Retrieve HTML content of image element.
get_author_link ($echo, $author_id, $author_nicename= '')
Returns or Prints link to the author's posts.
get_author_name ($auth_id=false)
Retrieve the specified author's preferred display name.
get_author_rss_link ($echo=false, $author_id=1)
Print/Return link to author RSS feed.
get_autotoggle ($id=0)
Gets the auto_toggle setting.
get_boundary_post_rel_link ($title= '%title', $in_same_cat=false, $excluded_categories= '', $start=true)
Get boundary post relational link.
get_category_children ($id, $before= '/', $after= '', $visited=array())
Retrieve category children list separated before and after the term IDs.
get_category_rss_link ($echo=false, $cat_ID=1)
Print/Return link to category RSS2 feed.
get_catname ($cat_ID)
Retrieve the category name by the category ID.
get_commentdata ($comment_ID, $no_cache=0, $include_unapproved=false)
Retrieve an array of comment data about comment $comment_ID.
get_comments_popup_template ()
Retrieve path of comment popup template in current or parent template.
get_current_theme ()
Retrieve current theme name.
get_index_rel_link ()
Get site index relational link.
get_link ($bookmark_id, $output=OBJECT, $filter= 'raw')
Retrieves bookmark data based on ID.
get_linkcatname ($id=0)
Gets the name of category by id.
get_linkobjects ($category=0, $orderby= 'name', $limit=0)
Gets an array of link objects associated with category n.
get_linkobjectsbyname ($cat_name="noname", $orderby= 'name', $limit=-1)
Gets an array of link objects associated with category $cat_name.
get_linkrating ($link)
Legacy function that retrieved the value of a link's link_rating field.
get_links ($category=-1, $before= '', $after= '< br/>', $between= ' ', $show_images=true, $orderby= 'name', $show_description=true, $show_rating=false, $limit=-1, $show_updated=1, $echo=true)
Gets the links associated with category by id.
get_links_list ($order= 'name')
Output entire list of links by category.
get_links_withrating ($category=-1, $before= '', $after= '< br/>', $between=" ", $show_images=true, $orderby= 'id', $show_description=true, $limit=-1, $show_updated=0)
Gets the links associated with category n and display rating stars/chars.
get_linksbyname ($cat_name="noname", $before= '', $after= '< br/>', $between=" ", $show_images=true, $orderby= 'id', $show_description=true, $show_rating=false, $limit=-1, $show_updated=0)
Gets the links associated with category $cat_name.
get_linksbyname_withrating ($cat_name="noname", $before= '', $after= '< br/>', $between=" ", $show_images=true, $orderby= 'id', $show_description=true, $limit=-1, $show_updated=0)
Gets the links associated with category 'cat_name' and display rating stars/chars.
get_parent_post_rel_link ($title= '%title')
Get parent post relational link.
get_postdata ($postid)
Entire Post data.
get_profile ($field, $user=false)
Retrieve user data based on field.
get_settings ($option)
Get value based on option.
get_the_attachment_link ($id=0, $fullsize=false, $max_dims=false, $permalink=false)
Retrieve HTML content of attachment image with link.
get_the_author_aim ()
Retrieve the AIM address of the author of the current post.
get_the_author_description ()
Retrieve the description of the author of the current post.
get_the_author_email ()
Retrieve the email of the author of the current post.
get_the_author_firstname ()
Retrieve the first name of the author of the current post.
get_the_author_icq ()
Retrieve the ICQ number of the author of the current post.
get_the_author_ID ()
Retrieve the ID of the author of the current post.
get_the_author_lastname ()
Retrieve the last name of the author of the current post.
get_the_author_login ()
Retrieve the login name of the author of the current post.
get_the_author_msn ()
Retrieve the MSN address of the author of the current post.
get_the_author_nickname ()
Retrieve the nickname of the author of the current post.
get_the_author_url ()
Retrieve the URL to the home page of the author of the current post.
get_the_author_yim ()
Retrieve the Yahoo! IM name of the author of the current post.
get_theme ($theme)
Retrieve theme data.
get_theme_data ($theme_file)
Retrieve theme data from parsed theme file.
get_themes ()
Retrieve list of themes with theme data in theme directory.
get_user_metavalues ($ids)
Perform the query to get the $metavalues array(s) needed by _fill_user and _fill_many_users.
get_usermeta ($user_id, $meta_key= '')
Retrieve user metadata.
get_usernumposts ($userid)
Retrieves the number of posts a user has written.
get_users_of_blog ($id= '')
Get users for the blog.
gzip_compression ()
Unused function.
image_resize ($file, $max_w, $max_h, $crop=false, $suffix=null, $dest_path=null, $jpeg_quality=90)
Scale down an image to fit a particular size and save a new copy of the image.
index_rel_link ()
Display relational link for the site index.
is_blog_user ($blog_id=0)
Checks if the current user belong to a given blog.
is_comments_popup ()
Whether the current URL is within the comments popup window.
is_plugin_page ()
Is the current admin page generated by a plugin?
is_taxonomy ($taxonomy)
Checks that the taxonomy name exists.
is_term ($term, $taxonomy= '', $parent=0)
Check if Term exists.
js_escape ($text)
Escape single quotes, specialchar double quotes, and fix line endings.
like_escape ($text)
Formerly used to escape strings before searching the DB.
link_pages ($before='< br/>', $after='< br/>', $next_or_number='number', $nextpagelink='next page', $previouspagelink='previous page', $pagelink='%', $more_file='')
Print list of pages based on arguments.
links_popup_script ($text= 'Links', $width=400, $height=400, $file='links.all.php', $count=true)
Show the link to the links popup and the number of links.
list_authors ($optioncount=false, $exclude_admin=true, $show_fullname=false, $hide_empty=true, $feed= '', $feed_image= '')
Lists authors.
list_cats ($optionall=1, $all= 'All', $sort_column= 'ID', $sort_order= 'asc', $file= '', $list=true, $optiondates=0, $optioncount=0, $hide_empty=1, $use_desc_for_title=1, $children=false, $child_of=0, $categories=0, $recurse=0, $feed= '', $feed_image= '', $exclude= '', $hierarchical=false)
Lists categories.
make_url_footnote ($content)
Strip HTML and put links at the bottom of stripped content.
next_post ($format='%', $next='next post: ', $title='yes', $in_same_cat='no', $limitnext=1, $excluded_categories='')
Prints link to the next post.
parent_post_rel_link ($title= '%title')
Display relational link for parent item.
permalink_link ()
Print the permalink of the current post in the loop.
permalink_single_rss ($deprecated= '')
Print the permalink to the RSS feed.
popuplinks ($text)
Adds element attributes to open links in new windows.
post_permalink ($post_id=0)
Retrieve permalink from post ID.
preview_theme ()
Start preview theme output buffer.
preview_theme_ob_filter ($content)
Callback function for ob_start() to capture all links in the theme.
preview_theme_ob_filter_callback ($matches)
Manipulates preview theme links in order to control and maintain location.
previous_post ($format='%', $previous='previous post: ', $title='yes', $in_same_cat='no', $limitprev=1, $excluded_categories='')
Prints link to the previous post.
register_sidebar_widget ($name, $output_callback, $classname= '')
Register widget for sidebar with backwards compatibility.
register_widget_control ($name, $control_callback, $width= '', $height= '')
Registers widget control callback for customizing options.
remove_custom_background ()
Remove custom background support.
remove_custom_image_header ()
Remove image header support.
rich_edit_exists ()
Determine if TinyMCE is available.
sanitize_url ($url, $protocols=null)
Performs esc_url() for database or redirect usage.
sanitize_user_object ($user, $context= 'display')
Sanitize every user field.
start_post_rel_link ($title= '%title', $in_same_cat=false, $excluded_categories= '')
Display relational link for the first post.
start_wp ()
Sets up the WordPress Loop.
sticky_class ($post_id=null)
Display "sticky" CSS class, if a post is sticky.
the_author_aim ()
Display the AIM address of the author of the current post.
the_author_description ()
Display the description of the author of the current post.
the_author_email ()
Display the email of the author of the current post.
the_author_firstname ()
Display the first name of the author of the current post.
the_author_icq ()
Display the ICQ number of the author of the current post.
the_author_ID ()
Display the ID of the author of the current post.
the_author_lastname ()
Display the last name of the author of the current post.
the_author_login ()
Display the login name of the author of the current post.
the_author_msn ()
Display the MSN address of the author of the current post.
the_author_nickname ()
Display the nickname of the author of the current post.
the_author_url ()
Display the URL to the home page of the author of the current post.
the_author_yim ()
Display the Yahoo! IM name of the author of the current post.
the_category_head ($before='', $after='')
Print category with optional text before and after.
the_category_ID ($echo=true)
Return or Print Category ID.
the_content_rss ($more_link_text='(more...)', $stripteaser=0, $more_file='', $cut=0, $encode_html=0)
Display the post content for the feed.
the_editor ($content, $id= 'content', $prev_id= 'title', $media_buttons=true, $tab_index=2, $extended=true)
Displays an editor: TinyMCE, HTML, or both.
translate_with_context ($text, $domain= 'default')
Translates $text like translate(), but assumes that the text contains a context after its last vertical bar.
unregister_sidebar_widget ($id)
Alias of wp_unregister_sidebar_widget().
unregister_widget_control ($id)
Alias of wp_unregister_widget_control().
update_category_cache ()
Update the categories cache.
update_page_cache (&$pages)
Alias of update_post_cache().
update_usermeta ($user_id, $meta_key, $meta_value)
Update metadata of user.
url_is_accessable_via_ssl ($url)
Determines if the URL can be accessed over SSL.
user_can_create_draft ($user_id, $blog_id=1, $category_id= 'None')
Whether user can create a post.
user_can_create_post ($user_id, $blog_id=1, $category_id= 'None')
Whether user can create a post.
user_can_delete_post ($user_id, $post_id, $blog_id=1)
Whether user can delete a post.
user_can_delete_post_comments ($user_id, $post_id, $blog_id=1)
Whether user can delete a post.
user_can_edit_post ($user_id, $post_id, $blog_id=1)
Whether user can edit a post.
user_can_edit_post_comments ($user_id, $post_id, $blog_id=1)
Whether user can delete a post.
user_can_edit_post_date ($user_id, $post_id, $blog_id=1)
Whether user can delete a post.
user_can_edit_user ($user_id, $other_user)
Can user can edit other user.
user_can_set_post_date ($user_id, $blog_id=1, $category_id= 'None')
Whether user can set new posts' dates.
user_pass_ok ($user_login, $user_pass)
Check that the user login name and password is correct.
wp_admin_bar_dashboard_view_site_menu ($wp_admin_bar)
Add the "Dashboard"/"Visit Site" menu.
wp_convert_bytes_to_hr ($bytes)
Converts an integer byte value to a shorthand byte value.
wp_explain_nonce ($action)
Retrieve nonce action "Are you sure" message.
wp_get_http ($url, $file_path=false, $red=1)
Perform a HTTP HEAD or GET request.
wp_get_links ($args= '')
Gets the links associated with category.
wp_get_linksbyname ($category, $args= '')
Gets the links associated with the named category.
wp_get_post_cats ($blogid= '1', $post_ID=0)
Retrieves a list of post categories.
wp_get_single_post ($postid=0, $mode=OBJECT)
Retrieve a single post, based on post ID.
wp_htmledit_pre ($output)
Formats text for the HTML editor.
wp_list_cats ($args= '')
Lists categories.
wp_load_image ($file)
Load an image from a string, if PHP supports it.
wp_richedit_pre ($text)
Formats text for the rich text editor.
wp_set_post_cats ($blogid= '1', $post_ID=0, $post_categories=array())
Sets the categories that the post id belongs to.
wp_specialchars ($string, $quote_style=ENT_NOQUOTES, $charset=false, $double_encode=false)
Legacy escaping for HTML blocks.
wp_timezone_supported ()
Check for PHP timezone support.
Function Documentation
__ngettext ()
Retrieve the plural or single form based on the amount.
Since
1.2.0
Definition at line 1787 of file wp-includes/deprecated.php.
References _deprecated_function().
__ngettext_noop ()
Register plural strings in POT file, but don't translate them.
Since
2.5.0
Definition at line 1800 of file wp-includes/deprecated.php.
References _deprecated_function().
_c ($text, $domain = 'default')
Retrieve translated string with vertical bar context.
Quite a few times, there will be collisions with similar translatable text found in more than two places but with different translated context.
In order to use the separate contexts, the _c() function is used and the translatable string uses a pipe ('|') which has the context the string is in.
When the translated string is returned, it is everything before the pipe, not including the pipe character. If there is no pipe in the translated text then everything is returned.
Since
2.2.0
Parameters
string $text Text to translate
string $domain Optional. Domain to retrieve the translated text
Returns
string Translated context string without pipe
Definition at line 1737 of file wp-includes/deprecated.php.
References $text, _deprecated_function(), before_last_bar(), and translate().
_get_post_ancestors (& $post)
Retrieve post ancestors.
This is no longer needed as WP_Post lazy-loads the ancestors property with get_post_ancestors().
Since
2.3.4
Definition at line 3138 of file wp-includes/deprecated.php.
References _deprecated_function().
_nc ($single, $plural, $number, $domain = 'default')
Legacy version of _n(), which supports contexts.
Strips everything from the translation after the last bar.
Since
2.7.0
Parameters
string $single The text to be used if the number is singular.
string $plural The text to be used if the number is plural.
int $number The number to compare against to use either the singular or plural form.
string $domain Optional. Text domain. Unique identifier for retrieving translated strings. Default 'default'.
Returns
string The translated singular or plural form.
Definition at line 1775 of file wp-includes/deprecated.php.
References _deprecated_function(), _n(), and before_last_bar().
_preview_theme_stylesheet_filter ()
Private function to modify the current stylesheet when previewing a theme.
Since
2.9.0
Returns
string
Definition at line 3467 of file wp-includes/deprecated.php.
References _deprecated_function().
_preview_theme_template_filter ()
Private function to modify the current template when previewing a theme.
Since
2.9.0
Returns
string
Definition at line 3453 of file wp-includes/deprecated.php.
References _deprecated_function().
_save_post_hook ()
Callback formerly fired on the save_post hook.
No longer needed.
Since
2.3.0
Definition at line 3264 of file wp-includes/deprecated.php.
_search_terms_tidy ($t)
Formerly used internally to tidy up the search terms.
Since
2.9.0 private
Definition at line 3336 of file wp-includes/deprecated.php.
References _deprecated_function().
add_custom_background ($wp_head_callback = '', $admin_head_callback = '', $admin_preview_callback = '')
Add callbacks for background image display.
Since
3.0.0
Parameters
callable $wp_head_callback Call on 'wp_head' action.
callable $admin_head_callback Call on custom background administration screen.
callable $admin_preview_callback Output a custom background image div on the custom background administration screen. Optional.
Definition at line 2999 of file wp-includes/deprecated.php.
References _deprecated_function(), and add_theme_support().
add_custom_image_header ($wp_head_callback, $admin_head_callback, $admin_preview_callback = '')
Add callbacks for image header display.
Since
2.1.0
Parameters
callable $wp_head_callback Call on 'wp_head' action.
callable $admin_head_callback Call on custom header administration screen.
callable $admin_preview_callback Output a custom header image div on the custom header administration screen. Optional.
Definition at line 2963 of file wp-includes/deprecated.php.
References _deprecated_function(), and add_theme_support().
attribute_escape ($text)
Escaping for HTML attributes.
Since
2.0.6
Parameters
string $text
Returns
string
Definition at line 2082 of file wp-includes/deprecated.php.
References $text, _deprecated_function(), and esc_attr().
automatic_feed_links ($add = true)
Enable/disable automatic general feed link outputting.
Since
2.8.0
Parameters
bool $add Optional, default is true. Add or remove links. Defaults to true.
Definition at line 2385 of file wp-includes/deprecated.php.
References _deprecated_function(), add_theme_support(), and remove_action().
clean_page_cache ($id)
Will clean the page in the cache.
Clean (read: delete) page from cache that matches $id. Will also clean cache associated with 'all_page_ids' and 'get_pages'.
Since
2.0.0
Parameters
int $id Page ID to clean
Definition at line 3090 of file wp-includes/deprecated.php.
References $id, _deprecated_function(), and clean_post_cache().
clean_pre ($matches)
Accepts matches array from preg_replace_callback in wpautop() or a string.
Ensures that the contents of a <pre>...</pre> HTML block are not converted into paragraphs or line-breaks.
Since
1.2.0
Parameters
array | string $matches The array or string
Returns
string The pre block without paragraph/line-break conversion.
Definition at line 2936 of file wp-includes/deprecated.php.
References $text, _deprecated_function(), and str_replace.
clean_url ($url, $protocols = null, $context = 'display')
Checks and cleans a URL.
A number of characters are removed from the URL. If the URL is for displaying (the default behaviour) ampersands are also replaced. The 'clean_url' filter is applied to the returned cleaned URL.
Since
1.2.0
Parameters
string $url The URL to be cleaned.
array $protocols Optional. An array of acceptable protocols.
string $context Optional. How the URL will be used. Default is 'display'.
Returns
string The cleaned $url after the 'clean_url' filter is applied.
Definition at line 2025 of file wp-includes/deprecated.php.
References $url, _deprecated_function(), and esc_url.
comments_popup_script ()
Display the JS popup script to show a comment.
Since
0.71
Definition at line 3701 of file wp-includes/deprecated.php.
References _deprecated_function().
comments_rss ()
Return link to the post RSS feed.
Since
1.5.0
Returns
string
Definition at line 1174 of file wp-includes/deprecated.php.
References _deprecated_function(), esc_url, and get_post_comments_feed_link().
comments_rss_link ($link_text = 'Comments RSS')
Print RSS comment feed link.
Since
1.0.1
Parameters
string $link_text
Definition at line 1119 of file wp-includes/deprecated.php.
References $link_text, _deprecated_function(), and post_comments_feed_link().
create_user ($username, $password, $email)
An alias of wp_create_user().
Since
2.0.0
Parameters
string $username The user's username.
string $password The user's password.
string $email The user's email.
Returns
int The new user's ID.
Definition at line 1191 of file wp-includes/deprecated.php.
References _deprecated_function(), and wp_create_user().
debug_fclose ($fp)
Close the debugging file handle.
Since
0.71
http://www.php.net/manual/en/function.error-log.php
Definition at line 2849 of file wp-includes/deprecated.php.
References _deprecated_function().
debug_fopen ($filename, $mode)
Open the file handle for debugging.
Since
0.71
http://www.php.net/manual/en/function.error-log.php
Definition at line 2820 of file wp-includes/deprecated.php.
References _deprecated_function().
debug_fwrite ($fp, $string)
Write contents to the file used for debugging.
Since
0.71
http://www.php.net/manual/en/function.error-log.php
Definition at line 2834 of file wp-includes/deprecated.php.
References $GLOBALS, and _deprecated_function().
default_topic_count_text ($count)
Old callback for tag link tooltips.
Since
2.7.0 private
Definition at line 3369 of file wp-includes/deprecated.php.
References $count.
delete_usermeta ($user_id, $meta_key, $meta_value = '')
Remove user meta data.
Since
2.0.0
Parameters
int $user_id User ID.
string $meta_key Metadata key.
mixed $meta_value Metadata value.
Returns
bool True deletion completed and false if user_id is not a number.
Definition at line 2211 of file wp-includes/deprecated.php.
References $user_id, $wpdb, _deprecated_function(), clean_user_cache(), do_action(), and wp_cache_delete().
Referenced by update_usermeta().
dropdown_cats ($optionall = 1, $all = 'All', $orderby = 'ID', $order = 'asc', $show_last_update = 0, $show_count = 0, $hide_empty = 1, $optionnone = false, $selected = 0, $exclude = 0)
Deprecated method for generating a drop-down of categories.
Since
0.71
Parameters
int $optionall
string $all
string $orderby
string $order
int $show_last_update
int $show_count
int $hide_empty
bool $optionnone
int $selected
int $exclude
Returns
string
Definition at line 677 of file wp-includes/deprecated.php.
References __, _deprecated_function(), add_query_arg(), and wp_dropdown_categories().
force_ssl_login ($force = null)
Whether SSL login should be forced.
Since
2.6.0
Parameters
string | bool $force Optional Whether to force SSL login. Default null.
Returns
bool True if forced, false if not forced.
Definition at line 3662 of file wp-includes/deprecated.php.
References _deprecated_function(), and force_ssl_admin().
format_to_post ($content)
Formerly used to escape strings before inserting into the DB.
Has not performed this function for many, many years. Use wpdb::prepare() instead.
Since
0.71
Parameters
string $content The text to format.
Returns
string The very same text.
Definition at line 3384 of file wp-includes/deprecated.php.
References $content, and _deprecated_function().
funky_javascript_callback ($matches)
Callback used to change uXXXX to &#YYY; syntax.
Since
2.8.0 private
Parameters
array $matches Single Match
Returns
string An HTML entity
Definition at line 2439 of file wp-includes/deprecated.php.
funky_javascript_fix ($text)
Fixes JavaScript bugs in browsers.
Converts unicode characters to HTML numbered entities.
Since
1.5.0
$is_macIE $is_winIE
Parameters
string $text Text to be made safe.
Returns
string Fixed text.
Definition at line 2457 of file wp-includes/deprecated.php.
References $is_macIE, $is_winIE, $text, and _deprecated_function().
gd_edit_image_support ($mime_type)
Check if the installed version of GD supports particular image type.
Since
2.9.0
Parameters
string $mime_type
Returns
bool
Definition at line 3276 of file wp-includes/deprecated.php.
References _deprecated_function().
get_all_category_ids ()
Retrieves all category IDs.
Since
2.0.0
object List of all of the category IDs.
Definition at line 1286 of file wp-includes/deprecated.php.
References _deprecated_function(), get_terms(), wp_cache_add(), and wp_cache_get().
Referenced by get_category_children().
get_alloptions ()
Retrieve all autoload options, or all options if no autoloaded ones exist.
Since
1.0.0
Returns
array List of all options.
Definition at line 1816 of file wp-includes/deprecated.php.
References _deprecated_function(), and wp_load_alloptions().
get_archives ($type = '', $limit = '', $format = 'html', $before = '', $after = '', $show_post_count = false)
Retrieves a list of archives.
Since
0.71
Parameters
string $type
string $limit
string $format
string $before
string $after
bool $show_post_count
Returns
string|null
Definition at line 767 of file wp-includes/deprecated.php.
References _deprecated_function(), and wp_get_archives().
get_attachment_icon ($id = 0, $fullsize = false, $max_dims = false)
Retrieve HTML content of icon attachment image element.
Since
2.0.0
Parameters
int $id Optional. Post ID.
bool $fullsize Optional, default to false. Whether to have full size image.
array $max_dims Optional. Dimensions of image.
Returns
false|string HTML content.
Definition at line 1904 of file wp-includes/deprecated.php.
References $id, $post, $post_title, _deprecated_function(), apply_filters(), esc_attr(), get_attachment_icon_src(), and get_post().
Referenced by get_attachment_innerHTML().
get_attachment_icon_src ($id = 0, $fullsize = false)
Retrieve icon URL and Path.
Since
2.1.0
Parameters
int $id Optional. Post ID.
bool $fullsize Optional, default to false. Whether to have full image.
Returns
array Icon URL and full path to file, respectively.
Definition at line 1862 of file wp-includes/deprecated.php.
References $file, $id, $post, _deprecated_function(), apply_filters(), elseif, get_attached_file(), get_post(), get_template_directory(), wp_attachment_is_image(), wp_get_attachment_thumb_url(), wp_get_attachment_url(), and wp_mime_type_icon().
Referenced by get_attachment_icon().
get_attachment_innerHTML ($id = 0, $fullsize = false, $max_dims = false)
Retrieve HTML content of image element.
Since
2.0.0
Parameters
int $id Optional. Post ID.
bool $fullsize Optional, default to false. Whether to have full size image.
array $max_dims Optional. Dimensions of image.
Returns
false|string
Definition at line 1960 of file wp-includes/deprecated.php.
References $id, $post, _deprecated_function(), apply_filters(), esc_attr(), get_attachment_icon(), and get_post().
Referenced by get_the_attachment_link().
get_author_link ($echo, $author_id, $author_nicename = '')
Returns or Prints link to the author's posts.
Since
1.2.0
Parameters
bool $echo
int $author_id
string $author_nicename Optional.
Returns
string|null
Definition at line 785 of file wp-includes/deprecated.php.
References $link, _deprecated_function(), and get_author_posts_url().
get_author_name ($auth_id = false)
Retrieve the specified author's preferred display name.
Since
1.0.0
Parameters
int $auth_id The ID of the author.
Returns
string The author's display name.
Definition at line 1567 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_author_rss_link ($echo = false, $author_id = 1)
Print/Return link to author RSS feed.
Since
1.2.0
Parameters
bool $echo
int $author_id
Returns
string
Definition at line 1156 of file wp-includes/deprecated.php.
References $link, _deprecated_function(), and get_author_feed_link().
get_autotoggle ($id = 0)
Gets the auto_toggle setting.
Since
0.71
Parameters
int $id The category to get. If no category supplied uses 0
Returns
int Only returns 0.
Definition at line 583 of file wp-includes/deprecated.php.
References _deprecated_function().
get_boundary_post_rel_link ($title = '%title', $in_same_cat = false, $excluded_categories = '', $start = true)
Get boundary post relational link.
Can either be start or end post relational link.
Since
2.8.0
Parameters
string $title Optional. Link title format.
bool $in_same_cat Optional. Whether link should be in a same category.
string $excluded_categories Optional. Excluded categories IDs.
bool $start Optional, default is true. Whether to display link to first or last post.
Returns
string
Definition at line 2660 of file wp-includes/deprecated.php.
References $link, $post, $title, __, _deprecated_function(), apply_filters(), esc_attr(), get_boundary_post(), get_option(), get_permalink(), mysql2date(), and str_replace.
Referenced by start_post_rel_link().
get_category_children ($id, $before = '/', $after = '', $visited = array())
Retrieve category children list separated before and after the term IDs.
Since
1.2.0
Parameters
int $id Category ID to retrieve children.
string $before Optional. Prepend before category term ID.
string $after Optional, default is empty string. Append after category term ID.
array $visited Optional. Category Term IDs that have already been added.
Returns
string
TODO: consult hierarchy
Definition at line 1251 of file wp-includes/deprecated.php.
References $id, _deprecated_function(), get_all_category_ids(), get_category(), and is_wp_error().
get_category_rss_link ($echo = false, $cat_ID = 1)
Print/Return link to category RSS2 feed.
Since
1.2.0
Parameters
bool $echo
int $cat_ID
Returns
string
Definition at line 1135 of file wp-includes/deprecated.php.
References $link, _deprecated_function(), and get_category_feed_link().
get_catname ($cat_ID)
Retrieve the category name by the category ID.
Since
0.71
Parameters
int $cat_ID Category ID
Returns
string category name
Definition at line 1233 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_cat_name().
get_commentdata ($comment_ID, $no_cache = 0, $include_unapproved = false)
Retrieve an array of comment data about comment $comment_ID.
Since
0.71
Parameters
int $comment_ID The ID of the comment
int $no_cache Whether to use the cache (cast to bool)
bool $include_unapproved Whether to include unapproved comments
Returns
array The comment data
Definition at line 1218 of file wp-includes/deprecated.php.
References _deprecated_function(), ARRAY_A, and get_comment().
get_comments_popup_template ()
Retrieve path of comment popup template in current or parent template.
Since
1.5.0
Returns
string Full path to comments popup template file.
Definition at line 3675 of file wp-includes/deprecated.php.
References _deprecated_function().
get_current_theme ()
Retrieve current theme name.
Since
1.5.0
Returns
string
Definition at line 2915 of file wp-includes/deprecated.php.
References $theme, _deprecated_function(), get_option(), and wp_get_theme().
Referenced by twentyeleven_theme_options_render_page().
get_index_rel_link ()
Get site index relational link.
Since
2.8.0
Returns
string
Definition at line 2712 of file wp-includes/deprecated.php.
References $link, _deprecated_function(), apply_filters(), esc_attr(), esc_url, get_bloginfo(), and user_trailingslashit().
Referenced by index_rel_link().
get_link ($bookmark_id, $output = OBJECT, $filter = 'raw')
Retrieves bookmark data based on ID.
Since
2.0.0
Parameters
int $bookmark_id ID of link
string $output Optional. Type of output. Accepts OBJECT, ARRAY_N, or ARRAY_A. Default OBJECT.
string $filter Optional. How to filter the link for output. Accepts 'raw', 'edit', 'attribute', 'js', 'db', or 'display'. Default 'raw'.
Returns
object|array Bookmark object or array, depending on the type specified by $output.
Definition at line 1988 of file wp-includes/deprecated.php.
References $output, _deprecated_function(), and get_bookmark().
get_linkcatname ($id = 0)
Gets the name of category by id.
Since
0.71
Parameters
int $id The category to get. If no category supplied uses 0
Returns
string
Definition at line 1091 of file wp-includes/deprecated.php.
References $cats, $id, _deprecated_function(), get_category(), and wp_get_link_cats().
get_linkobjects ($category = 0, $orderby = 'name', $limit = 0)
Gets an array of link objects associated with category n.
Usage:
$links = get_linkobjects(1);
if ($links) {
    foreach ($links as $link) {
        echo '<li>'.$link->link_name.'<br />'.$link->link_description.'</li>';
    }
}
Fields are:
link_id
link_url
link_name
link_image
link_target
link_category
link_description
link_visible
link_owner
link_rating
link_updated
link_rel
link_notes
Since
1.0.1
Parameters
int $category The category to use. If no category supplied uses all
string $orderby the order to output the links. E.g. 'id', 'name', 'url', 'description', or 'rating'. Or maybe owner. If you start the name with an underscore the order will be reversed. You can also specify 'rand' as the order which will return links in a random order.
int $limit Limit to X entries. If not specified, all entries are shown.
Returns
array
Definition at line 508 of file wp-includes/deprecated.php.
References $link, _deprecated_function(), and get_bookmarks().
Referenced by get_linkobjectsbyname().
get_linkobjectsbyname ($cat_name = "noname", $orderby = 'name', $limit = -1)
Gets an array of link objects associated with category $cat_name.
$links = get_linkobjectsbyname('fred'); foreach ($links as $link) { echo '' . $link->link_name . ''; }
Since
1.0.1
Parameters
string $cat_name The category name to use. If no match is found uses all.
string $orderby The order to output the links. E.g. 'id', 'name', 'url', 'description', or 'rating'. Or maybe owner. If you start the name with an underscore the order will be reversed. You can also specify 'rand' as the order which will return links in a random order.
int $limit Limit to X entries. If not specified, all entries are shown.
Returns
array
Definition at line 457 of file wp-includes/deprecated.php.
References _deprecated_function(), get_linkobjects(), and get_term_by().
get_linkrating ($link)
Legacy function that retrieved the value of a link's link_rating field.
Since
1.0.1
Parameters
object $link Link object.
Returns
mixed Value of the 'link_rating' field, false otherwise.
Definition at line 1076 of file wp-includes/deprecated.php.
References $link, _deprecated_function(), and sanitize_bookmark_field().
Referenced by get_links().
get_links ($category = -1, $before = '', $after = '<br />', $between = ' ', $show_images = true, $orderby = 'name', $show_description = true, $show_rating = false, $limit = -1, $show_updated = 1, $echo = true)
Gets the links associated with category by id.
Since
0.71
Parameters
int $category The category to use. If no category supplied uses all
string $before the html to output before the link
string $after the html to output after the link
string $between the html to output between the link/image and its description. Not used if no image or show_images == true
bool $show_images whether to show images (if defined).
string $orderby the order to output the links. E.g. 'id', 'name', 'url', 'description', or 'rating'. Or maybe owner. If you start the name with an underscore the order will be reversed. You can also specify 'rand' as the order which will return links in a random order.
bool $show_description whether to show the description if show_images=false/not defined.
bool $show_rating show rating stars/chars
int $limit Limit to X entries. If not specified, all entries are shown.
int $show_updated whether to show last updated timestamp
bool $echo whether to echo the results, or return them instead
Returns
null|string
Definition at line 924 of file wp-includes/deprecated.php.
References $alt, $name, $output, $title, _deprecated_function(), date, esc_attr(), esc_url, get_bookmarks(), get_linkrating(), get_option(), null, and sanitize_bookmark_field().
Referenced by get_links_list(), get_links_withrating(), and get_linksbyname().
get_links_list ($order = 'name')
Output entire list of links by category.
Output a list of all links, listed by category, using the settings in $wpdb->linkcategories and output it as a nested HTML unordered list.
Since
1.0.1
Parameters
string $order Sort link categories by 'name' or 'id'
Definition at line 1017 of file wp-includes/deprecated.php.
References $cats, _deprecated_function(), apply_filters(), get_categories(), and get_links().
get_links_withrating ($category = -1, $before = '', $after = '<br />', $between = " ", $show_images = true, $orderby = 'id', $show_description = true, $limit = -1, $show_updated = 0)
Gets the links associated with category n and display rating stars/chars.
Since
0.71
Parameters
int $category The category to use. If no category supplied uses all
string $before The html to output before the link
string $after The html to output after the link
string $between The html to output between the link/image and its description. Not used if no image or show_images == true
bool $show_images Whether to show images (if defined).
string $orderby The order to output the links. E.g. 'id', 'name', 'url', 'description', or 'rating'. Or maybe owner. If you start the name with an underscore the order will be reversed. You can also specify 'rand' as the order which will return links in a random order.
bool $show_description Whether to show the description if show_images=false/not defined.
int $limit Limit to X entries. If not specified, all entries are shown.
int $show_updated Whether to show last updated timestamp
Definition at line 567 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_links().
get_linksbyname ($cat_name = "noname", $before = '', $after = '<br />', $between = " ", $show_images = true, $orderby = 'id', $show_description = true, $show_rating = false, $limit = -1, $show_updated = 0)
Gets the links associated with category $cat_name.
Since
0.71
Parameters
string $cat_name Optional. The category name to use. If no match is found uses all.
string $before Optional. The html to output before the link.
string $after Optional. The html to output after the link.
string $between Optional. The html to output between the link/image and its description. Not used if no image or $show_images is true.
bool $show_images Optional. Whether to show images (if defined).
string $orderby Optional. The order to output the links. E.g. 'id', 'name', 'url', 'description' or 'rating'. Or maybe owner. If you start the name with an underscore the order will be reversed. You can also specify 'rand' as the order which will return links in a random order.
bool $show_description Optional. Whether to show the description if show_images=false/not defined.
bool $show_rating Optional. Show rating stars/chars.
int $limit Optional. Limit to X entries. If not specified, all entries are shown.
int $show_updated Optional. Whether to show last updated timestamp
Definition at line 395 of file wp-includes/deprecated.php.
References _deprecated_function(), get_links(), and get_term_by().
Referenced by get_linksbyname_withrating().
get_linksbyname_withrating ($cat_name = "noname", $before = '', $after = '<br />', $between = " ", $show_images = true, $orderby = 'id', $show_description = true, $limit = -1, $show_updated = 0)
Gets the links associated with category 'cat_name' and display rating stars/chars.
Since
0.71
Parameters
string $cat_name The category name to use. If no match is found uses all
string $before The html to output before the link
string $after The html to output after the link
string $between The html to output between the link/image and its description. Not used if no image or show_images is true
bool $show_images Whether to show images (if defined).
string $orderby the order to output the links. E.g. 'id', 'name', 'url', 'description', or 'rating'. Or maybe owner. If you start the name with an underscore the order will be reversed. You can also specify 'rand' as the order which will return links in a random order.
bool $show_description Whether to show the description if show_images=false/not defined
int $limit Limit to X entries. If not specified, all entries are shown.
int $show_updated Whether to show last updated timestamp
Definition at line 540 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_linksbyname().
get_parent_post_rel_link ($title = '%title')
Get parent post relational link.
Since
2.8.0
Parameters
string $title Optional. Link title format.
Returns
string
Definition at line 2740 of file wp-includes/deprecated.php.
References $GLOBALS, $link, $post, $title, _deprecated_function(), apply_filters(), esc_attr(), get_option(), get_permalink(), get_post(), mysql2date(), and str_replace.
Referenced by parent_post_rel_link().
get_postdata ($postid)
Entire Post data.
Since
0.71
Parameters
int $postid
Returns
array
Definition at line 25 of file wp-includes/deprecated.php.
References $post, _deprecated_function(), and get_post().
get_profile ($field, $user = false)
Retrieve user data based on field.
Since
1.5.0
Parameters
string $field User meta field.
false | int $user Optional. User ID to retrieve the field for. Default false (current user).
Returns
string The author's field from the current author's DB object.
Definition at line 2405 of file wp-includes/deprecated.php.
References $field, $user, _deprecated_function(), and get_the_author_meta().
get_settings ($option)
Get value based on option.
Since
0.71
Parameters
string $option
Returns
string
Definition at line 829 of file wp-includes/deprecated.php.
References $option, _deprecated_function(), and get_option().
get_the_attachment_link ($id = 0, $fullsize = false, $max_dims = false, $permalink = false)
Retrieve HTML content of attachment image with link.
Since
2.0.0
Parameters
int $id Optional. Post ID.
bool $fullsize Optional, default is false. Whether to use full size image.
array $max_dims Optional. Max image dimensions.
bool $permalink Optional, default is false. Whether to include permalink to image.
Returns
string
Definition at line 1834 of file wp-includes/deprecated.php.
References $id, $permalink, $post_title, $url, __, _deprecated_function(), esc_attr(), get_attachment_innerHTML(), get_attachment_link(), get_post(), and wp_get_attachment_url().
get_the_author_aim ()
Retrieve the AIM address of the author of the current post.
Since
1.5.0
Returns
string The author's AIM address.
Definition at line 1540 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_description ()
Retrieve the description of the author of the current post.
Since
1.5.0
Returns
string The author's description.
Definition at line 1306 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_email ()
Retrieve the email of the author of the current post.
Since
1.5.0
Returns
string The author's username.
Definition at line 1436 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_firstname ()
Retrieve the first name of the author of the current post.
Since
1.5.0
Returns
string The author's first name.
Definition at line 1358 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_icq ()
Retrieve the ICQ number of the author of the current post.
Since
1.5.0
Returns
string The author's ICQ number.
Definition at line 1462 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_ID ()
Retrieve the ID of the author of the current post.
Since
1.5.0
Returns
string|int The author's ID.
Definition at line 1607 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_lastname ()
Retrieve the last name of the author of the current post.
Since
1.5.0
Returns
string The author's last name.
Definition at line 1384 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_login ()
Retrieve the login name of the author of the current post.
Since
1.5.0
Returns
string The author's login name (username).
Definition at line 1332 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_msn ()
Retrieve the MSN address of the author of the current post.
Since
1.5.0
Returns
string The author's MSN address.
Definition at line 1514 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_nickname ()
Retrieve the nickname of the author of the current post.
Since
1.5.0
Returns
string The author's nickname.
Definition at line 1410 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_url ()
Retrieve the URL to the home page of the author of the current post.
Since
1.5.0
Returns
string The URL to the author's page.
Definition at line 1581 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_the_author_yim ()
Retrieve the Yahoo! IM name of the author of the current post.
Since
1.5.0
Returns
string The author's Yahoo! IM name.
Definition at line 1488 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_author_meta().
get_theme ($theme)
Retrieve theme data.
Since
1.5.0
Parameters
string $theme Theme name.
Returns
array|null Null, if theme name does not exist. Theme data, if exists.
Definition at line 2897 of file wp-includes/deprecated.php.
References $theme, _deprecated_function(), get_themes(), and null.
get_theme_data ($theme_file)
Retrieve theme data from parsed theme file.
Since
1.5.0
Parameters
string $theme_file Theme file path.
Returns
array Theme data.
Definition at line 3035 of file wp-includes/deprecated.php.
References $theme, _deprecated_function(), and apply_filters().
get_themes ()
Retrieve list of themes with theme data in theme directory.
The theme is broken, if it doesn't have a parent theme and is missing either style.css and, or index.php. If the theme has a parent theme then it is broken, if it is missing style.css; index.php is optional.
Since
1.5.0
Returns
array Theme list with theme data.
Definition at line 2866 of file wp-includes/deprecated.php.
References $name, $theme, _deprecated_function(), and wp_get_themes().
Referenced by get_theme().
get_user_metavalues ($ids)
Perform the query to get the $metavalues array(s) needed by _fill_user and _fill_many_users.
Since
3.0.0
Parameters
array $ids User ID numbers list.
Returns
array of arrays. The array is indexed by user_id, containing $metavalues object arrays.
Definition at line 2587 of file wp-includes/deprecated.php.
References $id, $value, _deprecated_function(), object, and update_meta_cache().
get_usermeta ($user_id, $meta_key = '')
Retrieve user metadata.
If $user_id is not a number, then the function will fail over with a 'false' boolean return value. Other returned values depend on whether there is only one item to be returned, which be that single item type. If there is more than one metadata value, then it will be list of metadata values.
Since
2.0.0
Parameters
int $user_id User ID
string $meta_key Optional. Metadata key.
Returns
mixed
Definition at line 2257 of file wp-includes/deprecated.php.
References $user, $user_id, $wpdb, _deprecated_function(), and wp_cache_get().
get_usernumposts ($userid)
Retrieves the number of posts a user has written.
Since
0.71
Parameters
int $userid User to count posts for.
Returns
int Number of posts the given user has written.
Definition at line 2424 of file wp-includes/deprecated.php.
References _deprecated_function(), and count_user_posts().
get_users_of_blog ($id = '')
Get users for the blog.
For setups that use the multi-blog feature. Can be used outside of the multi-blog feature.
Since
2.2.0
wpdb $wpdb WordPress database abstraction object. int $blog_id The Blog id of the blog for those that use more than one blog
Parameters
int $id Blog ID.
Returns
array List of users that are part of that Blog ID
Definition at line 2365 of file wp-includes/deprecated.php.
References $blog_id, $id, $wpdb, and _deprecated_function().
gzip_compression ()
Unused function.
Definition at line 1201 of file wp-includes/deprecated.php.
References _deprecated_function().
image_resize ($file, $max_w, $max_h, $crop = false, $suffix = null, $dest_path = null, $jpeg_quality = 90)
Scale down an image to fit a particular size and save a new copy of the image.
The PNG transparency will be preserved using the function, as well as the image type. If the file going in is PNG, then the resized image is going to be PNG. The only supported image types are PNG, GIF, and JPEG.
Some functionality requires API to exist, so some PHP version may lose out support. This is not the fault of WordPress (where functionality is downgraded, not actual defects), but of your PHP version.
Since
2.5.0
Parameters
string $file Image file path.
int $max_w Maximum width to resize to.
int $max_h Maximum height to resize to.
bool $crop Optional. Whether to crop image or resize.
string $suffix Optional. File suffix.
string $dest_path Optional. New image file path.
int $jpeg_quality Optional, default is 90. Image quality percentage.
Returns
mixed WP_Error on failure. String with new destination path.
Definition at line 3198 of file wp-includes/deprecated.php.
References $file, _deprecated_function(), is_wp_error(), and wp_get_image_editor().
Referenced by wp_create_thumbnail().
index_rel_link ()
Display relational link for the site index.
Since
2.8.0
Definition at line 2725 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_index_rel_link().
is_blog_user ($blog_id = 0)
Checks if the current user belong to a given blog.
Since
MU
Parameters
int $blog_id Blog ID
Returns
bool True if the current users belong to $blog_id, false if not.
Definition at line 2805 of file wp-includes/deprecated.php.
References $blog_id, _deprecated_function(), get_current_user_id(), and is_user_member_of_blog().
is_comments_popup ()
Whether the current URL is within the comments popup window.
Since
1.5.0
Returns
bool
Definition at line 3689 of file wp-includes/deprecated.php.
References _deprecated_function().
is_plugin_page ()
Is the current admin page generated by a plugin?
Use global $plugin_page and/or get_plugin_page_hookname() hooks.
Since
1.5.0
$plugin_page
Returns
bool
Definition at line 2514 of file wp-includes/deprecated.php.
References $plugin_page, and _deprecated_function().
is_taxonomy ($taxonomy)
Checks that the taxonomy name exists.
Since
2.3.0
Parameters
string $taxonomy Name of taxonomy object
Returns
bool Whether the taxonomy exists.
Definition at line 2480 of file wp-includes/deprecated.php.
References _deprecated_function(), and taxonomy_exists().
is_term ($term, $taxonomy = '', $parent = 0)
Check if Term exists.
Since
2.3.0
Parameters
int | string $term The term to check
string $taxonomy The taxonomy name to use
int $parent ID of parent term under which to confine the exists search.
Returns
mixed Get the term id or Term Object, if exists.
Definition at line 2497 of file wp-includes/deprecated.php.
References _deprecated_function(), and term_exists().
js_escape ($text)
Escape single quotes, specialchar double quotes, and fix line endings.
The filter 'js_escape' is also applied by esc_js()
Since
2.0.4
Parameters
string $text The text to be escaped.
Returns
string Escaped text.
Definition at line 2045 of file wp-includes/deprecated.php.
References $text, _deprecated_function(), and esc_js().
like_escape ($text)
Formerly used to escape strings before searching the DB.
It was poorly documented and never worked as described.
Since
2.5.0
Parameters
string $text The text to be escaped.
Returns
string text, safe for inclusion in LIKE query.
Definition at line 3399 of file wp-includes/deprecated.php.
References $text, _deprecated_function(), and str_replace.
Referenced by GravityView_Cache\delete().
link_pages ($before = '<br />', $after = '<br />', $next_or_number = 'number', $nextpagelink = 'next page', $previouspagelink = 'previous page', $pagelink = '%', $more_file = '')
Print list of pages based on arguments.
Since
0.71
Parameters
string $before
string $after
string $next_or_number
string $nextpagelink
string $previouspagelink
string $pagelink
string $more_file
Returns
string
Definition at line 811 of file wp-includes/deprecated.php.
References _deprecated_function(), and wp_link_pages().
links_popup_script ($text = 'Links', $width = 400, $height = 400, $file = 'links.all.php', $count = true)
Show the link to the links popup and the number of links.
Since
0.71
Parameters
string $text the text of the link
int $width the width of the popup window
int $height the height of the popup window
string $file the page to open in the popup window
bool $count the number of links in the db
Definition at line 1062 of file wp-includes/deprecated.php.
References _deprecated_function().
list_authors ($optioncount = false, $exclude_admin = true, $show_fullname = false, $hide_empty = true, $feed = '', $feed_image = '')
Lists authors.
Since
1.2.0
Parameters
bool $optioncount
bool $exclude_admin
bool $show_fullname
bool $hide_empty
string $feed
string $feed_image
Returns
null|string
Definition at line 711 of file wp-includes/deprecated.php.
References _deprecated_function(), and wp_list_authors().
list_cats ($optionall = 1, $all = 'All', $sort_column = 'ID', $sort_order = 'asc', $file = '', $list = true, $optiondates = 0, $optioncount = 0, $hide_empty = 1, $use_desc_for_title = 1, $children = false, $child_of = 0, $categories = 0, $recurse = 0, $feed = '', $feed_image = '', $exclude = '', $hierarchical = false)
Lists categories.
Since
0.71
Parameters
int $optionall
string $all
string $sort_column
string $sort_order
string $file
bool $list
int $optiondates
int $optioncount
int $hide_empty
int $use_desc_for_title
bool $children
int $child_of
int $categories
int $recurse
string $feed
string $feed_image
string $exclude
bool $hierarchical
Returns
false|null
Definition at line 615 of file wp-includes/deprecated.php.
References _deprecated_function(), and wp_list_cats().
make_url_footnote ($content)
Strip HTML and put links at the bottom of stripped content.
Searches for all of the links, strips them out of the content, and places them at the bottom of the content with numbers.
Since
0.71
Parameters
string $content Content to get links
Returns
string HTML stripped out of content with links at the bottom.
Definition at line 1698 of file wp-includes/deprecated.php.
References $content, $i, $link_text, _deprecated_function(), get_option(), and str_replace.
Referenced by the_content_rss().
next_post ($format = '%', $next = 'next post: ', $title = 'yes', $in_same_cat = 'no', $limitnext = 1, $excluded_categories = '')
Prints link to the next post.
Since
0.71
Parameters
string $format
string $next
string $title
string $in_same_cat
int $limitnext
string $excluded_categories
Definition at line 171 of file wp-includes/deprecated.php.
References $format, $post, $title, _deprecated_function(), apply_filters(), get_next_post(), and str_replace.
parent_post_rel_link ($title = '%title')
Display relational link for parent item.
Since
2.8.0
Definition at line 2768 of file wp-includes/deprecated.php.
References $title, _deprecated_function(), and get_parent_post_rel_link().
permalink_link ()
Print the permalink of the current post in the loop.
Since
0.71
Definition at line 842 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_permalink().
permalink_single_rss ($deprecated = '')
Print the permalink to the RSS feed.
Since
0.71
Parameters
string $deprecated
Definition at line 856 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_permalink_rss().
popuplinks ($text)
Adds element attributes to open links in new windows.
Since
0.71
Parameters
string $text Content to replace links to open in a new window.
Returns
string Content that has filtered links.
Definition at line 3714 of file wp-includes/deprecated.php.
References $text, and _deprecated_function().
post_permalink ($post_id = 0)
Retrieve permalink from post ID.
Since
1.0.0
Parameters
int | WP_Post $post_id Optional. Post ID or WP_Post object. Default is global $post.
Returns
string|false
Definition at line 3586 of file wp-includes/deprecated.php.
References $post_id, _deprecated_function(), and get_permalink().
preview_theme ()
Start preview theme output buffer.
Will only perform task if the user has permissions and template and preview query variables exist.
Since
2.6.0
Definition at line 3440 of file wp-includes/deprecated.php.
References _deprecated_function().
preview_theme_ob_filter ($content)
Callback function for ob_start() to capture all links in the theme.
Since
2.6.0
Parameters
string $content
Returns
string
Definition at line 3482 of file wp-includes/deprecated.php.
References $content, and _deprecated_function().
preview_theme_ob_filter_callback ($matches)
Manipulates preview theme links in order to control and maintain location.
Callback function for preg_replace_callback() to accept and filter matches.
Since
2.6.0
Parameters
array $matches
Returns
string
Definition at line 3499 of file wp-includes/deprecated.php.
References _deprecated_function().
previous_post ($format = '%', $previous = 'previous post: ', $title = 'yes', $in_same_cat = 'no', $limitprev = 1, $excluded_categories = '')
Prints link to the previous post.
Since
1.5.0
Parameters
string $format
string $previous
string $title
string $in_same_cat
int $limitprev
string $excluded_categories
Definition at line 135 of file wp-includes/deprecated.php.
References $format, $post, $title, _deprecated_function(), apply_filters(), get_previous_post(), and str_replace.
register_sidebar_widget ($name, $output_callback, $classname = '')
Register widget for sidebar with backwards compatibility.
Allows $name to be an array that accepts either three elements to grab the first element and the third for the name or just uses the first element of the array for the name.
Passes to wp_register_sidebar_widget() after argument list and backwards compatibility is complete.
Since
2.2.0
Parameters
string | int $name Widget ID.
callable $output_callback Run when widget is called.
string $classname Optional. Classname widget option. Default empty.
mixed $params,... Widget parameters.
Definition at line 2106 of file wp-includes/deprecated.php.
References $id, $name, $options, _deprecated_function(), and sanitize_title().
register_widget_control ($name, $control_callback, $width = '', $height = '')
Registers widget control callback for customizing options.
Allows $name to be an array that accepts either three elements to grab the first element and the third for the name or just uses the first element of the array for the name.
Passes to wp_register_widget_control() after the argument list has been compiled.
Since
2.2.0
Parameters
int | string $name Sidebar ID.
callable $control_callback Widget control callback to display and process form.
int $width Widget width.
int $height Widget height.
Definition at line 2161 of file wp-includes/deprecated.php.
References $id, $name, $options, _deprecated_function(), and sanitize_title().
remove_custom_background ()
Remove custom background support.
Since
3.1.0
Returns
null|bool Whether support was removed.
Definition at line 3020 of file wp-includes/deprecated.php.
References _deprecated_function(), and remove_theme_support().
remove_custom_image_header ()
Remove image header support.
Since
3.1.0
Returns
null|bool Whether support was removed.
Definition at line 2983 of file wp-includes/deprecated.php.
References _deprecated_function(), and remove_theme_support().
rich_edit_exists ()
Determine if TinyMCE is available.
Checks to see if the user has deleted the tinymce files to slim down their WordPress install.
Since
2.1.0
Returns
bool Whether TinyMCE exists.
Definition at line 3352 of file wp-includes/deprecated.php.
References _deprecated_function(), ABSPATH, and WPINC.
sanitize_url ($url, $protocols = null)
Performs esc_url() for database or redirect usage.
Since
2.3.1
Parameters
string $url The URL to be cleaned.
array $protocols An array of acceptable protocols.
Returns
string The cleaned URL.
Definition at line 2004 of file wp-includes/deprecated.php.
References $url, _deprecated_function(), and esc_url_raw().
sanitize_user_object ($user, $context = 'display')
Sanitize every user field.
If the context is 'raw', then the user object or array will get minimal santization of the int fields.
Since
2.3.0
Parameters
object | array $user The User Object or Array
string $context Optional, default is 'display'. How to sanitize user fields.
Returns
object|array The now sanitized User Object or Array (will be the same type as $user)
Definition at line 2621 of file wp-includes/deprecated.php.
References $field, $user, _deprecated_function(), and sanitize_user_field().
start_post_rel_link ($title = '%title', $in_same_cat = false, $excluded_categories = '')
Display relational link for the first post.
Since
2.8.0
Parameters
string $title Optional. Link title format.
bool $in_same_cat Optional. Whether link should be in a same category.
string $excluded_categories Optional. Excluded categories IDs.
Definition at line 2698 of file wp-includes/deprecated.php.
References $title, _deprecated_function(), and get_boundary_post_rel_link().
start_wp ()
Sets up the WordPress Loop.
Use The Loop instead.
1.0.1 deprecated 164.
Definition at line 61 of file wp-includes/deprecated.php.
References __, _deprecated_function(), get_post(), and setup_postdata().
sticky_class ($post_id = null)
Display "sticky" CSS class, if a post is sticky.
Since
2.7.0
Parameters
int $post_id An optional post ID.
Definition at line 3122 of file wp-includes/deprecated.php.
References $post_id, _deprecated_function(), and is_sticky().
the_author_aim ()
Display the AIM address of the author of the current post.
Since
0.71
Definition at line 1552 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_description ()
Display the description of the author of the current post.
Since
1.0.0
Definition at line 1318 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_email ()
Display the email of the author of the current post.
Since
0.71
Definition at line 1448 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_firstname ()
Display the first name of the author of the current post.
Since
0.71
Definition at line 1370 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_icq ()
Display the ICQ number of the author of the current post.
Since
0.71
Definition at line 1474 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_ID ()
Display the ID of the author of the current post.
Since
0.71
Definition at line 1619 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_lastname ()
Display the last name of the author of the current post.
Since
0.71
Definition at line 1396 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_login ()
Display the login name of the author of the current post.
Since
0.71
Definition at line 1344 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_msn ()
Display the MSN address of the author of the current post.
Since
0.71
Definition at line 1526 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_nickname ()
Display the nickname of the author of the current post.
Since
0.71
Definition at line 1422 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_url ()
Display the URL to the home page of the author of the current post.
Since
0.71
Definition at line 1593 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_author_yim ()
Display the Yahoo! IM name of the author of the current post.
Since
0.71
Definition at line 1500 of file wp-includes/deprecated.php.
References _deprecated_function(), and the_author_meta().
the_category_head ($before = '', $after = '')
Print category with optional text before and after.
Since
0.71
Parameters
string $before
string $after
Definition at line 105 of file wp-includes/deprecated.php.
References _deprecated_function(), get_the_category(), and get_the_category_by_ID().
the_category_ID ($echo = true)
Return or Print Category ID.
Since
0.71
Parameters
bool $echo
Returns
null|int
Definition at line 82 of file wp-includes/deprecated.php.
References _deprecated_function(), and get_the_category().
the_content_rss ($more_link_text = '(more...)', $stripteaser = 0, $more_file = '', $cut = 0, $encode_html = 0)
Display the post content for the feed.
For encoding the html or the $encode_html parameter, there are three possible values. '0' will make urls footnotes and use make_url_footnote(). '1' will encode special characters and automatically display all of the content. The value of '2' will strip all HTML tags from the content.
Also note that you cannot set the amount of words and not set the html encoding. If that is the case, then the html encoding will default to 2, which will strip all HTML tags.
To restrict the amount of words of the content, you can use the cut parameter. If the content is less than the amount, then there won't be any dots added to the end. If there is content left over, then dots will be added and the rest of the content will be removed.
Since
0.71
Parameters
string $more_link_text Optional. Text to display when more content is available but not displayed.
int $stripteaser Optional. Default is 0.
string $more_file Optional.
int $cut Optional. Amount of words to keep for the content.
int $encode_html Optional. How to encode the content.
Definition at line 1652 of file wp-includes/deprecated.php.
References $content, $excerpt, $i, _deprecated_function(), apply_filters(), elseif, esc_html, get_the_content(), make_url_footnote(), and str_replace.
the_editor ($content, $id = 'content', $prev_id = 'title', $media_buttons = true, $tab_index = 2, $extended = true)
Displays an editor: TinyMCE, HTML, or both.
Since
2.1.0
Parameters
string $content Textarea content.
string $id Optional. HTML ID attribute value. Default 'content'.
string $prev_id Optional. Unused.
bool $media_buttons Optional. Whether to display media buttons. Default true.
int $tab_index Optional. Unused.
bool $extended Optional. Unused.
int $tab_index Optional, not used
Definition at line 2572 of file wp-includes/deprecated.php.
References $content, $id, _deprecated_function(), and wp_editor().
translate_with_context ($text, $domain = 'default')
Translates $text like translate(), but assumes that the text contains a context after its last vertical bar.
Since
2.5.0
Parameters
string $text Text to translate
string $domain Domain to retrieve the translated text
Returns
string Translated text
Definition at line 1754 of file wp-includes/deprecated.php.
References $text, _deprecated_function(), before_last_bar(), and translate().
unregister_sidebar_widget ($id)
Alias of wp_unregister_sidebar_widget().
Since
2.2.0
Parameters
int | string $id Widget ID.
Definition at line 2137 of file wp-includes/deprecated.php.
References $id, _deprecated_function(), and wp_unregister_sidebar_widget().
unregister_widget_control ($id)
Alias of wp_unregister_widget_control().
Since
2.2.0
Parameters
int | string $id Widget ID.
Definition at line 2194 of file wp-includes/deprecated.php.
References $id, _deprecated_function(), and wp_unregister_widget_control().
update_category_cache ()
Update the categories cache.
This function does not appear to be used anymore or does not appear to be needed. It might be a legacy function left over from when there was a need for updating the category cache.
Since
1.5.0
Returns
bool Always return True
Definition at line 2537 of file wp-includes/deprecated.php.
References _deprecated_function().
update_page_cache (& $pages)
Alias of update_post_cache().
See also
update_post_cache() Posts and pages are the same, alias is intentional
Since
1.5.1
Parameters
array $pages list of page objects
Definition at line 3072 of file wp-includes/deprecated.php.
References _deprecated_function(), and update_post_cache().
update_usermeta ($user_id, $meta_key, $meta_value)
Update metadata of user.
There is no need to serialize values, they will be serialized if it is needed. The metadata key can only be a string with underscores. All else will be removed.
Will remove the metadata, if the meta value is empty.
Since
2.0.0
Parameters
int $user_id User ID
string $meta_key Metadata key.
mixed $meta_value Metadata value.
Returns
bool True on successful update, false on failure.
Definition at line 2310 of file wp-includes/deprecated.php.
References $user_id, $wpdb, _deprecated_function(), clean_user_cache(), delete_usermeta(), do_action(), elseif, maybe_serialize(), and wp_cache_delete().
url_is_accessable_via_ssl ($url)
Determines if the URL can be accessed over SSL.
Determines if the URL can be accessed over SSL by using the WordPress HTTP API to access the URL using https as the scheme.
Since
2.5.0
Parameters
string $url The URL to test.
Returns
bool Whether SSL access is available.
Definition at line 3416 of file wp-includes/deprecated.php.
References $url, _deprecated_function(), is_wp_error(), set_url_scheme(), wp_remote_get(), and wp_remote_retrieve_response_code().
user_can_create_draft ($user_id, $blog_id = 1, $category_id = 'None')
Whether user can create a post.
Since
1.5.0
Parameters
int $user_id
int $blog_id Not Used
int $category_id Not Used
Returns
bool
Definition at line 223 of file wp-includes/deprecated.php.
References $user_id, and _deprecated_function().
user_can_create_post ($user_id, $blog_id = 1, $category_id = 'None')
Whether user can create a post.
Since
1.5.0
Parameters
int $user_id
int $blog_id Not Used
int $category_id Not Used
Returns
bool
Definition at line 204 of file wp-includes/deprecated.php.
References $user_id, and _deprecated_function().
Referenced by user_can_set_post_date().
user_can_delete_post ($user_id, $post_id, $blog_id = 1)
Whether user can delete a post.
Since
1.5.0
Parameters
int $user_id
int $post_id
int $blog_id Not Used
Returns
bool
Definition at line 270 of file wp-includes/deprecated.php.
References $blog_id, $post_id, $user_id, _deprecated_function(), and user_can_edit_post().
user_can_delete_post_comments ($user_id, $post_id, $blog_id = 1)
Whether user can delete a post.
Since
1.5.0
Parameters
int $user_id
int $post_id
int $blog_id Not Used
Returns
bool returns true if $user_id can delete $post_id's comments
Definition at line 346 of file wp-includes/deprecated.php.
References $blog_id, $post_id, $user_id, _deprecated_function(), and user_can_edit_post_comments().
user_can_edit_post ($user_id, $post_id, $blog_id = 1)
Whether user can edit a post.
Since
1.5.0
Parameters
int $user_id
int $post_id
int $blog_id Not Used
Returns
bool
Definition at line 242 of file wp-includes/deprecated.php.
References $post, $post_id, $user_id, _deprecated_function(), and get_post().
Referenced by user_can_delete_post(), user_can_edit_post_comments(), and user_can_edit_post_date().
user_can_edit_post_comments ($user_id, $post_id, $blog_id = 1)
Whether user can delete a post.
Since
1.5.0
Parameters
int $user_id
int $post_id
int $blog_id Not Used
Returns
bool returns true if $user_id can edit $post_id's comments
Definition at line 327 of file wp-includes/deprecated.php.
References $blog_id, $post_id, $user_id, _deprecated_function(), and user_can_edit_post().
Referenced by user_can_delete_post_comments().
user_can_edit_post_date ($user_id, $post_id, $blog_id = 1)
Whether user can delete a post.
Since
1.5.0
Parameters
int $user_id
int $post_id
int $blog_id Not Used
Returns
bool returns true if $user_id can edit $post_id's date
Definition at line 308 of file wp-includes/deprecated.php.
References $blog_id, $post_id, $user_id, _deprecated_function(), and user_can_edit_post().
user_can_edit_user ($user_id, $other_user)
Can user can edit other user.
Since
1.5.0
Parameters
int $user_id
int $other_user
Returns
bool
Definition at line 364 of file wp-includes/deprecated.php.
References $user, $user_id, and _deprecated_function().
user_can_set_post_date ($user_id, $blog_id = 1, $category_id = 'None')
Whether user can set new posts' dates.
Since
1.5.0
Parameters
int $user_id
int $blog_id Not Used
int $category_id Not Used
Returns
bool
Definition at line 289 of file wp-includes/deprecated.php.
References $blog_id, $user_id, _deprecated_function(), and user_can_create_post().
user_pass_ok ($user_login, $user_pass)
Check that the user login name and password is correct.
Since
0.71
Parameters
string $user_login User name.
string $user_pass User password.
Returns
bool False if does not authenticate, true if username and password authenticates.
Definition at line 3249 of file wp-includes/deprecated.php.
References $user, _deprecated_function(), and is_wp_error().
wp_admin_bar_dashboard_view_site_menu ($wp_admin_bar)
Add the "Dashboard"/"Visit Site" menu.
Since
3.2.0
Definition at line 2780 of file wp-includes/deprecated.php.
References $user_id, __, _deprecated_function(), admin_url(), elseif, get_current_user_id(), get_dashboard_url(), home_url(), is_admin(), and is_multisite().
wp_convert_bytes_to_hr ($bytes)
Converts an integer byte value to a shorthand byte value.
Since
2.3.0
Parameters
int $bytes An integer byte value.
Returns
string A shorthand byte value.
Definition at line 3311 of file wp-includes/deprecated.php.
References $size, and _deprecated_function().
wp_explain_nonce ($action)
Retrieve nonce action "Are you sure" message.
Deprecated in 3.4.1 and 3.5.0. Backported to 3.3.3.
Since
2.0.4
Parameters
string $action Nonce action.
Returns
string Are you sure message.
Definition at line 3108 of file wp-includes/deprecated.php.
References __, and _deprecated_function().
wp_get_http ($url, $file_path = false, $red = 1)
Perform a HTTP HEAD or GET request.
If $file_path is a writable filename, this will do a GET request and write the file to that path.
Since
2.5.0
Parameters
string $url URL to fetch.
string | bool $file_path Optional. File path to write request to. Default false.
int $red Optional. The number of Redirects followed, Upon 5 being hit, returns false. Default 1.
Returns
bool|string False on failure and string of headers if HEAD request.
Definition at line 3608 of file wp-includes/deprecated.php.
References $options, $url, _deprecated_function(), is_wp_error(), wp_remote_retrieve_body(), wp_remote_retrieve_headers(), wp_remote_retrieve_response_code(), and wp_safe_remote_request().
wp_get_links ($args = '')
Gets the links associated with category.
Since
1.0.1
Parameters
string $args a query string
Returns
null|string
Definition at line 871 of file wp-includes/deprecated.php.
References _deprecated_function(), add_query_arg(), wp_list_bookmarks(), and wp_parse_args().
wp_get_linksbyname ($category, $args = '')
Gets the links associated with the named category.
Since
1.0.1
Parameters
string $category The category to use.
string $args
Returns
string|null
Definition at line 419 of file wp-includes/deprecated.php.
References _deprecated_function(), wp_list_bookmarks(), and wp_parse_args().
wp_get_post_cats ($blogid = '1', $post_ID = 0)
Retrieves a list of post categories.
Since
1.0.1
Parameters
int $blogid Not Used
int $post_ID
Returns
array
Definition at line 729 of file wp-includes/deprecated.php.
References $post_ID, _deprecated_function(), and wp_get_post_categories().
wp_get_single_post ($postid = 0, $mode = OBJECT)
Retrieve a single post, based on post ID.
Has categories in 'post_category' property or key. Has tags in 'tags_input' property or key.
Since
1.0.0
Parameters
int $postid Post ID.
string $mode How to return result, either OBJECT, ARRAY_N, or ARRAY_A.
Returns
WP_Post|null Post object or array holding post contents and information
Definition at line 3233 of file wp-includes/deprecated.php.
References $mode, _deprecated_function(), and get_post().
wp_htmledit_pre ($output)
Formats text for the HTML editor.
Unless $output is empty it will pass through htmlspecialchars before the 'htmledit_pre' filter is applied.
Since
2.5.0
Parameters
string $output The text to be formatted.
Returns
string Formatted text after filter applied.
Filter the text before it is formatted for the HTML editor.
Since
2.5.0
Parameters
string $output The HTML-formatted text.
Definition at line 3559 of file wp-includes/deprecated.php.
References $output, _deprecated_function(), apply_filters(), and get_option().
wp_list_cats ($args = '')
Lists categories.
Since
1.2.0
Parameters
string | array $args
Returns
false|null|string
Definition at line 635 of file wp-includes/deprecated.php.
References _deprecated_function(), wp_list_categories(), and wp_parse_args().
Referenced by list_cats().
wp_load_image ($file)
Load an image from a string, if PHP supports it.
Since
2.1.0
Parameters
string $file Filename of the image to load.
Returns
resource The resulting image resource on success, Error string on failure.
Definition at line 3152 of file wp-includes/deprecated.php.
References $file, $image, __, _deprecated_function(), apply_filters(), get_attached_file(), and WP_MAX_MEMORY_LIMIT.
wp_richedit_pre ($text)
Formats text for the rich text editor.
The filter 'richedit_pre' is applied here. If $text is empty the filter will be applied to an empty string.
Since
2.0.0
Parameters
string $text The text to be formatted.
Returns
string The formatted text after filter is applied.
Filter text returned for the rich text editor.
This filter is first evaluated, and the value returned, if an empty string is passed to wp_richedit_pre(). If an empty string is passed, it results in a break tag and line feed.
If a non-empty string is passed, the filter is evaluated on the wp_richedit_pre() return after being formatted.
Since
2.0.0
Parameters
string $output Text for the rich text editor.
This filter is documented in wp-includes/deprecated.php
Definition at line 3516 of file wp-includes/deprecated.php.
References $output, $text, _deprecated_function(), apply_filters(), convert_chars(), get_option(), and wpautop().
wp_set_post_cats ($blogid = '1', $post_ID = 0, $post_categories = array())
Sets the categories that the post id belongs to.
Since
1.0.1
Parameters
int $blogid Not used
int $post_ID
array $post_categories
Returns
bool|mixed
Definition at line 747 of file wp-includes/deprecated.php.
References $post_ID, _deprecated_function(), and wp_set_post_categories().
wp_specialchars ($string, $quote_style = ENT_NOQUOTES, $charset = false, $double_encode = false)
Legacy escaping for HTML blocks.
Parameters
string $string String to escape.
string $quote_style Unused.
false | string $charset Unused.
false $double_encode Whether to double encode. Unused.
Returns
string Escaped $string.
Definition at line 2062 of file wp-includes/deprecated.php.
References _deprecated_function(), and esc_html.
wp_timezone_supported ()
Check for PHP timezone support.
Since
2.9.0
Returns
bool
Definition at line 2551 of file wp-includes/deprecated.php.
References _deprecated_function().