GravityView: template.php File Reference
wp-includes/template.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
get_404_template ()
Retrieve path of 404 template in current or parent template.
get_archive_template ()
Retrieve path of archive template in current or parent template.
get_attachment_template ()
Retrieve path of attachment template in current or parent template.
get_author_template ()
Retrieve path of author template in current or parent template.
get_category_template ()
Retrieve path of category template in current or parent template.
get_date_template ()
Retrieve path of date template in current or parent template.
get_front_page_template ()
Retrieve path of front-page template in current or parent template.
get_home_template ()
Retrieve path of home template in current or parent template.
get_index_template ()
Retrieve path of index template in current or parent template.
get_page_template ()
Retrieve path of page template in current or parent template.
get_paged_template ()
Retrieve path of paged template in current or parent template.
get_post_type_archive_template ()
Retrieve path of post type archive template in current or parent template.
get_query_template ($type, $templates=array())
Retrieve path to a template.
get_search_template ()
Retrieve path of search template in current or parent template.
get_single_template ()
Retrieve path of single template in current or parent template.
get_singular_template ()
Retrieves the path of the singular template in current or parent template.
get_tag_template ()
Retrieve path of tag template in current or parent template.
get_taxonomy_template ()
Retrieve path of taxonomy template in current or parent template.
load_template ($_template_file, $require_once=true)
Require the template file with WordPress environment.
locate_template ($template_names, $load=false, $require_once=true)
Retrieve the name of the highest priority template file that exists.
Function Documentation
get_404_template ()
Retrieve path of 404 template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. '404_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to 404 template file.
Definition at line 76 of file wp-includes/template.php.
References get_query_template().
get_archive_template ()
Retrieve path of archive template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'archive_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to archive template file.
Definition at line 92 of file wp-includes/template.php.
References $post_type, $templates, get_query_template(), and get_query_var().
Referenced by get_post_type_archive_template().
get_attachment_template ()
Retrieve path of attachment template in current or parent template.
The attachment path first checks if the first part of the mime type exists. The second check is for the second part of the mime type. The last check is for both types separated by an underscore. If neither are found then the file 'attachment.php' is checked and returned.
Some examples for the 'text/plain' mime type are 'text.php', 'plain.php', and finally 'text-plain.php'.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'attachment_template'.
Since
2.0.0
See also
get_query_template()
array $posts
Returns
string Full path to attachment template file.
Definition at line 445 of file wp-includes/template.php.
References $templates, get_queried_object(), and get_query_template().
get_author_template ()
Retrieve path of author template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'author_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to author template file.
Definition at line 142 of file wp-includes/template.php.
References $templates, get_queried_object(), and get_query_template().
get_category_template ()
Retrieve path of category template in current or parent template.
Works by first retrieving the current slug, for example 'category-default.php', and then trying category ID, for example 'category-1.php', and will finally fall back to category.php template, if those files don't exist.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'category_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to category template file.
Definition at line 172 of file wp-includes/template.php.
References $templates, get_queried_object(), and get_query_template().
get_date_template ()
Retrieve path of date template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'date_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to date template file.
Definition at line 264 of file wp-includes/template.php.
References get_query_template().
get_front_page_template ()
Retrieve path of front-page template in current or parent template.
Looks for 'front-page.php'. The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'frontpage_template'.
Since
3.0.0
See also
get_query_template()
Returns
string Full path to front page template file.
Definition at line 301 of file wp-includes/template.php.
References $templates, and get_query_template().
get_home_template ()
Retrieve path of home template in current or parent template.
This is the template used for the page containing the blog posts. Attempts to locate 'home.php' first before falling back to 'index.php'.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'home_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to home template file.
Definition at line 283 of file wp-includes/template.php.
References $templates, and get_query_template().
get_index_template ()
Retrieve path of index template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'index_template'.
Since
3.0.0
See also
get_query_template()
Returns
string Full path to index template file.
Definition at line 60 of file wp-includes/template.php.
References get_query_template().
get_page_template ()
Retrieve path of page template in current or parent template.
Will first look for the specifically assigned page template. Then will search for 'page-{slug}.php', followed by 'page-{id}.php', and finally 'page.php'.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'page_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to page template file.
Definition at line 323 of file wp-includes/template.php.
References $id, $post, $template, $templates, get_page_template_slug(), get_queried_object(), get_queried_object_id(), get_query_template(), get_query_var(), and validate_file().
get_paged_template ()
Retrieve path of paged template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'paged_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to paged template file.
Definition at line 359 of file wp-includes/template.php.
References get_query_template().
get_post_type_archive_template ()
Retrieve path of post type archive template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'archive_template'.
Since
3.7.0
See also
get_archive_template()
Returns
string Full path to archive template file.
Definition at line 118 of file wp-includes/template.php.
References $post_type, get_archive_template(), get_post_type_object(), and get_query_var().
get_query_template ($type, $templates = array())
Retrieve path to a template.
Used to quickly retrieve the path of a template without including the file extension. It will also check the parent theme, if the file exists, with the use of locate_template(). Allows for more generic template location without the use of the other get_*_template() functions.
Since
1.5.0
Parameters
string $type Filename without extension.
array $templates An optional list of template candidates
Returns
string Full path to template file.
Filter the path of the queried template by type.
The dynamic portion of the hook name, $type, refers to the filename – minus the file extension and any non-alphanumeric characters delimiting words – of the file to load. This hook also applies to various types of files loaded as part of the Template Hierarchy.
Possible values for $type include: 'index', '404', 'archive', 'author', 'category', 'tag', 'taxonomy', 'date', 'home', 'front_page', 'page', 'paged', 'search', 'single', 'singular', and 'attachment'.
Since
1.5.0
Parameters
string $template Path to the template. See locate_template().
Definition at line 23 of file wp-includes/template.php.
References $template, $templates, apply_filters(), and locate_template().
Referenced by get_404_template(), get_archive_template(), get_attachment_template(), get_author_template(), get_category_template(), get_date_template(), get_front_page_template(), get_home_template(), get_index_template(), get_page_template(), get_paged_template(), get_search_template(), get_single_template(), get_singular_template(), get_tag_template(), and get_taxonomy_template().
get_search_template ()
Retrieve path of search template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'search_template'.
Since
1.5.0
See also
get_query_template()
Returns
string Full path to search template file.
Definition at line 375 of file wp-includes/template.php.
References get_query_template().
get_single_template ()
Retrieve path of single template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'single_template'.
Since
1.5.0
4.4.0 single-{post_type}-{post_name}.php was added to the top of the template hierarchy.
See also
get_query_template()
Returns
string Full path to single template file.
Definition at line 392 of file wp-includes/template.php.
References $templates, get_queried_object(), and get_query_template().
get_singular_template ()
Retrieves the path of the singular template in current or parent template.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'singular_template'.
Since
4.3.0
See also
get_query_template()
Returns
string Full path to singular template file
Definition at line 419 of file wp-includes/template.php.
References get_query_template().
get_tag_template ()
Retrieve path of tag template in current or parent template.
Works by first retrieving the current tag name, for example 'tag-wordpress.php', and then trying tag ID, for example 'tag-1.php', and will finally fall back to tag.php template, if those files don't exist.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'tag_template'.
Since
2.3.0
See also
get_query_template()
Returns
string Full path to tag template file.
Definition at line 202 of file wp-includes/template.php.
References $templates, get_queried_object(), and get_query_template().
get_taxonomy_template ()
Retrieve path of taxonomy template in current or parent template.
Retrieves the taxonomy and term, if term is available. The template is prepended with 'taxonomy-' and followed by both the taxonomy string and the taxonomy string followed by a dash and then followed by the term.
The taxonomy and term template is checked and used first, if it exists. Second, just the taxonomy template is checked, and then finally, taxonomy.php template is used. If none of the files exist, then it will fall back on to index.php.
The template path is filterable via the dynamic {
See also
'$type_template'} hook, e.g. 'taxonomy_template'.
Since
2.5.0
See also
get_query_template()
Returns
string Full path to taxonomy template file.
Definition at line 237 of file wp-includes/template.php.
References $templates, get_queried_object(), and get_query_template().
load_template ($_template_file, $require_once = true)
Require the template file with WordPress environment.
The globals are set up for the template file to ensure that the WordPress environment is available from within the function. The query variables are also available.
Since
1.5.0
array $posts WP_Post $post bool $wp_did_header WP_Query $wp_query WP_Rewrite $wp_rewrite wpdb $wpdb string $wp_version WP $wp int $id WP_Comment $comment int $user_ID
Parameters
string $_template_file Path to template file.
bool $require_once Whether to require_once or require. Default true.
Definition at line 525 of file wp-includes/template.php.
References $comment, $id, $post, $s, $user_ID, $wp, $wp_rewrite, $wp_version, $wpdb, and esc_attr().
Referenced by do_feed_atom(), do_feed_rdf(), do_feed_rss(), do_feed_rss2(), GravityView_API\field_value(), get_footer(), get_header(), get_sidebar(), locate_template(), and GravityView_View\locate_template().
locate_template ($template_names, $load = false, $require_once = true)
Retrieve the name of the highest priority template file that exists.
Searches in the STYLESHEETPATH before TEMPLATEPATH so that themes which inherit from a parent theme can just overload one file.
Since
2.7.0
Parameters
string | array $template_names Template file(s) to search for, in order.
bool $load If true the template file will be loaded if it is found.
bool $require_once Whether to require_once or require. Default true. Has no effect if $load is false.
Returns
string The template filename if one is located.
Definition at line 481 of file wp-includes/template.php.
References $load, elseif, and load_template().
Referenced by get_footer(), get_header(), get_query_template(), get_search_form(), get_sidebar(), get_template_part(), and GravityView_View\locate_template().