GravityView: plugin.php File Reference
wp-includes/plugin.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_wp_call_all_hook ($args)
Call the 'all' hook, which will process the functions hooked into it.
_wp_filter_build_unique_id ($tag, $function, $priority)
Build Unique ID for storage and retrieval.
add_action ($tag, $function_to_add, $priority=10, $accepted_args=1)
Hooks a function on to a specific action.
add_filter ($tag, $function_to_add, $priority=10, $accepted_args=1)
Hook a function or method to a specific filter action.
apply_filters ($tag, $value)
Call the functions added to a filter hook.
apply_filters_ref_array ($tag, $args)
Execute functions hooked on a specific filter hook, specifying arguments in an array.
current_action ()
Retrieve the name of the current action.
current_filter ()
Retrieve the name of the current filter or action.
did_action ($tag)
Retrieve the number of times an action is fired.
do_action ($tag, $arg= '')
Execute functions hooked on a specific action hook.
do_action_ref_array ($tag, $args)
Execute functions hooked on a specific action hook, specifying arguments in an array.
doing_action ($action=null)
Retrieve the name of an action currently being processed.
doing_filter ($filter=null)
Retrieve the name of a filter currently being processed.
has_action ($tag, $function_to_check=false)
Check if any action has been registered for a hook.
has_filter ($tag, $function_to_check=false)
Check if any filter has been registered for a hook.
plugin_basename ($file)
Gets the basename of a plugin.
plugin_dir_path ($file)
Get the filesystem directory path (with trailing slash) for the plugin FILE passed in.
plugin_dir_url ($file)
Get the URL directory path (with trailing slash) for the plugin FILE passed in.
register_activation_hook ($file, $function)
Set the activation hook for a plugin.
register_deactivation_hook ($file, $function)
Set the deactivation hook for a plugin.
register_uninstall_hook ($file, $callback)
Set the uninstallation hook for a plugin.
remove_action ($tag, $function_to_remove, $priority=10)
Removes a function from a specified action hook.
remove_all_actions ($tag, $priority=false)
Remove all of the hooks from an action.
remove_all_filters ($tag, $priority=false)
Remove all of the hooks from a filter.
remove_filter ($tag, $function_to_remove, $priority=10)
Removes a function from a specified filter hook.
wp_register_plugin_realpath ($file)
Register a plugin's real path.
Variables
global $merged_filters
global $wp_actions
global $wp_current_filter
global $wp_filter
Function Documentation
_wp_call_all_hook ($args)
Call the 'all' hook, which will process the functions hooked into it.
The 'all' hook passes all of the arguments or parameters that were used for the hook, which this function was called for.
This function is used internally for apply_filters(), do_action(), and do_action_ref_array() and is not meant to be used from outside those functions. This function does not check for the existence of the all hook, so it will fail unless the all hook exists prior to this function call.
Since
2.5.0 private
array $wp_filter Stores all of the filters
Parameters
array $args The collected parameters from the hook that was called.
Definition at line 865 of file wp-includes/plugin.php.
References $wp_filter.
Referenced by apply_filters(), apply_filters_ref_array(), do_action(), and do_action_ref_array().
_wp_filter_build_unique_id ($tag, $function, $priority)
Build Unique ID for storage and retrieval.
The old way to serialize the callback caused issues and this function is the solution. It works by checking for objects and creating a new property in the class to keep track of the object and new objects of the same class that need to be added.
It also allows for the removal of actions and filters for objects after they change class properties. It is possible to include the property $wp_filter_id in your class and set it to "null" or a number to bypass the workaround. However this will prevent you from adding new classes and any new classes will overwrite the previous hook by the same class.
Functions and static method callbacks are just returned as strings and shouldn't have any speed penalty.
2.2.3 private array $wp_filter Storage for all of the filters and actions. int $filter_id_count string $tag Used in counting how many hooks were applied callable $function Used for creating unique id int|bool $priority Used in counting how many hooks were applied. If === false and $function is an object reference, we return the unique id only if it already has one, false otherwise. string|false Unique ID for usage as array key or false if $priority === false and $function is an object reference, and it does not already have a unique id.
Definition at line 911 of file wp-includes/plugin.php.
References $wp_filter, and elseif.
Referenced by add_filter(), has_filter(), and remove_filter().
add_action ($tag, $function_to_add, $priority = 10, $accepted_args = 1)
Hooks a function on to a specific action.
Actions are the hooks that the WordPress core launches at specific points during execution, or when specific events occur. Plugins can specify that one or more of its PHP functions are executed at these points, using the Action API.
Since
1.2.0
Parameters
string $tag The name of the action to which the $function_to_add is hooked.
callable $function_to_add The name of the function you wish to be called.
int $priority Optional. Used to specify the order in which the functions associated with a particular action are executed. Default 10. Lower numbers correspond with earlier execution, and functions with the same priority are executed in the order in which they were added to the action.
int $accepted_args Optional. The number of arguments the function accepts. Default 1.
Returns
true Will always return true.
Definition at line 457 of file wp-includes/plugin.php.
References add_filter().
Referenced by register_activation_hook(), and register_deactivation_hook().
add_filter ($tag, $function_to_add, $priority = 10, $accepted_args = 1)
Hook a function or method to a specific filter action.
WordPress offers filter hooks to allow plugins to modify various types of internal data at runtime.
A plugin can modify data by binding a callback to a filter hook. When the filter is later applied, each bound callback is run in order of priority, and given the opportunity to modify a value by returning a new value.
The following example shows how a callback function is bound to a filter hook.
Note that $example is passed to the callback, (maybe) modified, then returned:
function example_callback($example) {
    // Maybe modify $example in some way.
       return $example;
}
add_filter('example_filter', 'example_callback');
Bound callbacks can accept from none to the total number of arguments passed as parameters in the corresponding apply_filters() call.
In other words, if an apply_filters() call passes four total arguments, callbacks bound to it can accept none (the same as 1) of the arguments or up to four. The important part is that the $accepted_args value must reflect the number of arguments the bound callback actually opted to accept. If no arguments were accepted by the callback that is considered to be the same as accepting 1 argument. For example:
// Filter call.
$value = apply_filters('hook', $value, $arg2, $arg3);
// Accepting zero/one arguments.
function example_callback() {
    ...
    return 'some value';
}
add_filter('hook', 'example_callback'); // Where $priority is default 10, $accepted_args is default 1.
// Accepting two arguments (three possible).
function example_callback($value, $arg2) {
    ...
    return $maybe_modified_value;
}
add_filter('hook', 'example_callback', 10, 2); // Where $priority is 10, $accepted_args is 2.
Note: The function will return true whether or not the callback is valid. It is up to you to take care. This is done for optimization purposes, so everything is as quick as possible.
Since
0.71
array $wp_filter A multidimensional array of all hooks and the callbacks hooked to them. array $merged_filters Tracks the tags that need to be merged for later. If the hook is added, it doesn't need to run through that process.
Parameters
string $tag The name of the filter to hook the $function_to_add callback to.
callable $function_to_add The callback to be run when the filter is applied.
int $priority Optional. Used to specify the order in which the functions associated with a particular action are executed. Default 10. Lower numbers correspond with earlier execution, and functions with the same priority are executed in the order in which they were added to the action.
int $accepted_args Optional. The number of arguments the function accepts. Default 1.
Returns
true
Definition at line 103 of file wp-includes/plugin.php.
References $merged_filters, $wp_filter, and _wp_filter_build_unique_id().
Referenced by add_action().
apply_filters ($tag, $value)
Call the functions added to a filter hook.
The callback functions attached to filter hook $tag are invoked by calling this function. This function can be used to create a new filter hook by simply calling this function with the name of the new hook specified using the $tag parameter.
The function allows for additional arguments to be added and passed to hooks.
// Our filter callback function
function example_callback($string, $arg1, $arg2) {
    // (maybe) modify $string
    return $string;
}
add_filter('example_filter', 'example_callback', 10, 3);
/*
 * Apply the filters by calling the 'example_callback' function we
 * "hooked" to 'example_filter' using the add_filter() function above.
 * - 'example_filter' is the filter hook $tag
 * - 'filter me' is the value being filtered
 * - $arg1 and $arg2 are the additional arguments passed to the callback.
$value = apply_filters('example_filter', 'filter me', $arg1, $arg2);
Since
0.71
array $wp_filter Stores all of the filters. array $merged_filters Merges the filter hooks using this function. array $wp_current_filter Stores the list of current filters with the current one last.
Parameters
string $tag The name of the filter hook.
mixed $value The value on which the filters hooked to $tag are applied on.
mixed $var,... Additional variables passed to the functions hooked to $tag.
Returns
mixed The filtered value after all hooked functions are applied to it.
Definition at line 199 of file wp-includes/plugin.php.
References $merged_filters, $value, $wp_current_filter, $wp_filter, and _wp_call_all_hook().
apply_filters_ref_array ($tag, $args)
Execute functions hooked on a specific filter hook, specifying arguments in an array.
Since
3.0.0
See also
apply_filters() This function is identical, but the arguments passed to the functions hooked to $tag are supplied using an array.
array $wp_filter Stores all of the filters array $merged_filters Merges the filter hooks using this function. array $wp_current_filter Stores the list of current filters with the current one last
Parameters
string $tag The name of the filter hook.
array $args The arguments supplied to the functions hooked to $tag.
Returns
mixed The filtered value after all hooked functions are applied to it.
Definition at line 261 of file wp-includes/plugin.php.
References $merged_filters, $wp_current_filter, $wp_filter, and _wp_call_all_hook().
Referenced by WP_Comment_Query\get_comment_ids(), WP_Comment_Query\get_comments(), WP_Query\get_posts(), WP_Meta_Query\get_sql(), and WP_Query\set_found_posts().
current_action ()
Retrieve the name of the current action.
Since
3.9.0
Returns
string Hook name of the current action.
Definition at line 389 of file wp-includes/plugin.php.
References current_filter().
Referenced by WP_Terms_List_Table\current_action(), WP_Media_List_Table\current_action(), WP_Users_List_Table\current_action(), WP_Comments_List_Table\current_action(), WP_Plugins_List_Table\current_action(), WP_Posts_List_Table\current_action(), rest_cookie_collect_status(), and switch_theme().
current_filter ()
Retrieve the name of the current filter or action.
Since
2.5.0
array $wp_current_filter Stores the list of current filters with the current one last
Returns
string Hook name of the current filter or action.
Definition at line 377 of file wp-includes/plugin.php.
References $wp_current_filter.
Referenced by GravityView_frontend\add_scripts_and_styles(), Language_Pack_Upgrader\bulk_upgrade(), capital_P_dangit(), WP_Customize_Widgets\capture_filter_pre_get_option(), current_action(), display_plugins_table(), get_the_generator(), GravityView_frontend\insert_view_in_content(), is_main_query(), GravityView_Edit_Entry_Render\prevent_render_form(), GravityView_Admin_Views\register_no_conflict(), GravityView_View\render_widget_hooks(), twentyfourteen_contextual_help(), wp_deregister_script(), wp_filter_kses(), wp_kses_data(), wp_update_plugins(), and wp_update_themes().
did_action ($tag)
Retrieve the number of times an action is fired.
Since
2.1.0
array $wp_actions Increments the amount of times action was triggered.
Parameters
string $tag The name of the action hook.
Returns
int The number of times action hook $tag is fired.
Definition at line 542 of file wp-includes/plugin.php.
References $wp_actions.
do_action ($tag, $arg = '')
Execute functions hooked on a specific action hook.
This function invokes all functions attached to action hook $tag. It is possible to create new action hooks by simply calling this function, specifying the name of the new hook using the $tag parameter.
You can pass extra arguments to the hooks, much like you can with {
See also
apply_filters()}.
Since
1.2.0
array $wp_filter Stores all of the filters array $wp_actions Increments the amount of times action was triggered. array $merged_filters Merges the filter hooks using this function. array $wp_current_filter Stores the list of current filters with the current one last
Parameters
string $tag The name of the action to be executed.
mixed $arg,... Optional. Additional arguments which are passed on to the functions hooked to the action. Default empty.
Definition at line 482 of file wp-includes/plugin.php.
References $merged_filters, $wp_actions, $wp_current_filter, $wp_filter, and _wp_call_all_hook().
Referenced by _deprecated_argument(), _deprecated_constructor(), _deprecated_file(), _deprecated_function(), WP_Http\_dispatch_request(), _doing_it_wrong(), WP_Ajax_UnitTestCase\_handleAjax(), _publish_post_hook(), _split_shared_term(), _transition_post_status(), _update_generic_term_count(), _update_post_term_count(), _wp_admin_html_begin(), _wp_put_post_revision(), activate_plugin(), GravityView_Admin_Views\add_custom_column_content(), GFAPI\add_entry(), add_existing_user_to_blog(), GravityView_View\add_id_specific_templates(), WP_Admin_Bar\add_menus(), add_metadata(), add_network_option(), GFFormsModel\add_note(), GravityView_Admin_Notices\add_notice(), GravityView_Extension\add_notice(), add_option(), WP_User\add_role(), GravityView_Admin_ApproveEntries\add_scripts_and_styles(), GravityView_Widget\add_shortcode(), GravityView_frontend\add_style(), GFPaymentAddOn\add_subscription_payment(), add_user_to_blog(), GravityView_View_Data\add_view(), GravityView_Admin_Notices\admin_notice(), GravityView_Edit_Entry_Render\after_update(), GFEntryList\all_leads_page(), GFForms\all_leads_page(), GravityView_Change_Entry_Creator\assign_new_user_to_lead(), attachment_submit_meta_box(), GravityView_Admin\backend_actions(), GravityView_Cache\blacklist_add(), GravityView_Cache\blacklist_remove(), wp_xmlrpc_server\blogger_deletePost(), wp_xmlrpc_server\blogger_editPost(), wp_xmlrpc_server\blogger_getPost(), wp_xmlrpc_server\blogger_getRecentPosts(), wp_xmlrpc_server\blogger_getUserInfo(), wp_xmlrpc_server\blogger_getUsersBlogs(), wp_xmlrpc_server\blogger_newPost(), Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), GVCommon\calculate_get_entries_criteria(), GFPaymentAddOn\cancel_subscription(), check_comment_flood_db(), GVCommon\check_entry_display(), check_theme_switched(), GravityView_Delete_Entry\check_user_cap_delete_entry(), GravityView_Edit_Entry\check_user_cap_edit_entry(), clean_attachment_cache(), clean_object_term_cache(), clean_post_cache(), clean_term_cache(), clean_user_cache(), WP_Links_List_Table\column_default(), WP_MS_Sites_List_Table\column_default(), WP_Media_List_Table\column_default(), WP_MS_Themes_List_Table\column_default(), WP_Comments_List_Table\column_default(), WP_Posts_List_Table\column_default(), WP_MS_Sites_List_Table\column_plugins(), GravityView_Field_List\column_value(), comment_form(), GFPaymentAddOn\complete_payment(), confirm_delete_users(), GravityView_Admin_Duplicate_View\create_duplicate(), GravityView_Ajax\create_preset_form(), CreatePlaceholdersUI(), GravityView_Edit_Entry_Render\custom_validation(), WP_Customize_Widgets\customize_controls_init(), WP_Customize_Manager\customize_preview_init(), deactivate_plugins(), GravityView_Cache\delete(), delete_confirmation(), GravityView_Cache\delete_expired_transients(), GFFormsModel\delete_field(), GFFormsModel\delete_form(), GFFormsModel\delete_lead(), GFFormsModel\delete_leads_by_form(), delete_metadata(), delete_metadata_by_mid(), delete_network_option(), GFFormsModel\delete_note(), GravityView_Entry_Notes\delete_notes(), delete_option(), GravityView_Delete_Entry\delete_or_trash_entry(), delete_plugins(), delete_site_transient(), delete_transient(), delete_usermeta(), GFFormsModel\delete_views(), GF_Installation_Wizard_Step_Settings\display(), WP_Theme_Install_List_Table\display(), display_setup_form(), WP_Plugin_Install_List_Table\display_tablenav(), do_activate_header(), do_feed(), do_robots(), do_signup_header(), GFFormsModel\duplicate_form(), dynamic_sidebar(), edit_user(), _WP_Editors\editor(), _WP_Editors\editor_js(), enqueue_embed_scripts(), WP_Customize_Widgets\enqueue_scripts(), _WP_Editors\enqueue_scripts(), GravityView_Cache\entry_created(), GravityView_API\entry_link_html(), GravityView_Cache\entry_updated(), GFExport\export_page(), export_wp(), WP_Media_List_Table\extra_tablenav(), WP_Users_List_Table\extra_tablenav(), WP_Comments_List_Table\extra_tablenav(), WP_Posts_List_Table\extra_tablenav(), GFPaymentAddOn\fail_subscription_payment(), GravityView_API\field_value(), GravityView_Widget_Search\filter_entries(), GravityView_Recent_Entries_Widget\form(), GFFormSettings\form_settings_page(), GFFormSettings\form_settings_ui(), GFForms\forms(), GravityView_Plugin\frontend_actions(), GravityView_Cache\get(), GravityView_Ajax\get_active_areas(), GravityView_Admin_Views\get_available_fields(), GravityView_Ajax\get_available_fields_html(), GravityView_Admin_Duplicate_View\get_clone_view_link(), GravityView_Delete_Entry\get_delete_link(), GVCommon\get_entries(), GravityView_Entry_Link_Shortcode\get_entry(), GravityView_Ajax\get_field_options(), GravityView_View_Data\get_fields(), get_footer(), GravityView_Widget_Search\get_formatted_date(), get_header(), GravityView_View_Data\get_id_from_atts(), GVLogic_Shortcode\get_output(), get_password_reset_key(), WP_Query\get_posts(), GravityView_Ajax\get_preset_fields_config(), GravityView_frontend\get_search_criteria(), get_search_form(), get_sidebar(), get_template_part(), get_the_post_thumbnail(), GravityView_View_Data\get_view(), GravityView_View\getPaginationCounts(), grant_super_admin(), gravityview_after(), gravityview_before(), gravityview_field_output(), gravityview_footer(), gravityview_get_current_views(), gravityview_header(), gravityview_ob_include(), GFFormDisplay\handle_submission(), WP_Press_This\html(), iframe_footer(), iframe_header(), GravityView_Ajax\import_fields(), GravityView_Ajax\import_form(), GFExport\import_json(), GravityView_Cache\in_blacklist(), WP_Admin_Bar\initialize(), WP_Terms_List_Table\inline_edit(), WP_Posts_List_Table\inline_edit(), GFPaymentAddOn\insert_transaction(), GravityView_frontend\insert_view_in_content(), GravityView_Extension\is_extension_supported(), GFEntryDetail\lead_detail_page(), link_submit_meta_box(), GravityView_Extension\load_plugin_textdomain(), load_textdomain(), GFForms\loaded(), GravityView_Plugin\log_debug(), GravityView_Plugin\log_error(), login_footer(), login_header(), GravityView_Support_Port\maybe_enqueue_script(), WP_Customize_Panel\maybe_render(), WP_Customize_Section\maybe_render(), WP_Customize_Control\maybe_render(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), media_upload_form(), GravityView_Edit_Entry_Render\modify_edit_field_input(), wp_xmlrpc_server\mt_getCategoryList(), wp_xmlrpc_server\mt_getPostCategories(), wp_xmlrpc_server\mt_getRecentPostTitles(), wp_xmlrpc_server\mt_getTrackbackPings(), wp_xmlrpc_server\mt_publishPost(), wp_xmlrpc_server\mt_setPostCategories(), wp_xmlrpc_server\mt_supportedMethods(), wp_xmlrpc_server\mt_supportedTextFilters(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_getCategories(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), wp_xmlrpc_server\mw_newMediaObject(), wp_xmlrpc_server\mw_newPost(), GravityView_Admin\no_conflict_styles(), page_attributes_meta_box(), GravityView_View_Data\parse_post_content(), GravityView_View_Data\parse_post_meta(), WP_Query\parse_tax_query(), GFEntryDetail\payment_details_box(), wp_xmlrpc_server\pingback_extensions_getPingbacks(), wp_xmlrpc_server\pingback_ping(), populate_options(), post_comment_status_meta_box(), GFPaymentAddOn\post_payment_action(), post_submit_meta_box(), GravityView_Ajax\pre_get_form_fields(), GravityView_Widget_Poll\pre_render_frontend(), GravityView_Widget\pre_render_frontend(), WP_User_Query\prepare_query(), GravityView_Edit_Entry_Render\prevent_maybe_process_form(), WP_Customize_Setting\preview(), WP_Customize_Widgets\print_footer_scripts(), print_head_scripts(), WP_Customize_Widgets\print_scripts(), WP_Customize_Widgets\print_styles(), GravityView_Admin_ApproveEntries\process_bulk_action(), GFPaymentAddOn\process_callback_action(), GravityView_Delete_Entry\process_delete(), GravityView_Edit_Entry_Render\process_save(), GravityView_frontend\process_search_dates(), GravityView_frontend\process_search_only_approved(), refresh_blog_details(), GFPaymentAddOn\refund_payment(), register_new_user(), register_post_type(), register_sidebar(), register_taxonomy(), WP_User\remove_role(), remove_user_from_blog(), GravityView_Metabox_Tab\render(), GravityView_View\render(), GravityView_Admin_Views\render_active_areas(), GravityView_Admin_Views\render_directory_active_areas(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Custom_Content\render_frontend(), GravityView_oEmbed\render_handler(), GravityView_frontend\render_view(), GravityView_View\render_widget_hooks(), reset_password(), restore_current_blog(), GravityView_Edit_Entry_User_Registration\restore_display_name(), GFFormsModel\restore_form(), retrieve_password(), revoke_super_admin(), WP_Upgrader\run(), WP_Automatic_Updater\run(), WP_Customize_Setting\save(), WP_Customize_Manager\save(), GFFormsModel\save_incomplete_submission(), GravityView_Admin_Views\save_postdata(), GravityView_Cache\set(), WP_Screen\set_current_screen(), GVLogic_Shortcode\set_operation(), WP_Rewrite\set_permalink_structure(), WP_Customize_Manager\set_post_value(), WP_User\set_role(), set_site_transient(), set_transient(), GravityView_oEmbed\set_vars(), GravityView_Admin_Metaboxes\settings_metabox_render(), GFSettings\settings_page(), GravityView_Shortcode\shortcode(), GravityView_Entry_Link_Shortcode\shortcode(), GVLogic_Shortcode\shortcode(), shutdown_action_hook(), WP_Plugins_List_Table\single_row(), WP_MS_Themes_List_Table\single_row(), GFExport\start_export(), WP_Customize_Manager\start_previewing_theme(), GFPaymentAddOn\start_subscription(), Custom_Image_Header\step_1(), Custom_Image_Header\step_2(), WP_Customize_Manager\stop_previewing_theme(), switch_theme(), switch_to_blog(), WP_Query\the_comment(), the_widget(), GFFormsModel\trash_form(), twentyeleven_enqueue_color_scheme(), uninstall_plugin(), unload_textdomain(), unregister_taxonomy(), WP_Customize_Setting\update(), WP_Automatic_Updater\update(), GravityView_Admin_ApproveEntries\update_approved_meta(), update_blog_details(), update_blog_status(), GravityView_Admin_ApproveEntries\update_bulk(), update_core(), GFFormsModel\update_form_active(), GFFormsModel\update_lead_property(), update_metadata(), update_metadata_by_mid(), update_network_option(), GFFormsModel\update_notification_active(), update_option(), GFUpdate\update_page(), GravityView_Migrate\update_search_on_views(), update_user_status(), update_usermeta(), GravityView_frontend\updateViewSorting(), Core_Upgrader\upgrade(), GravityView_Cache\use_cache(), GravityView_Edit_Entry_Render\user_can_edit_entry(), GravityView_Edit_Entry_Render\user_can_edit_field(), GravityView_Search_WP_Widget\widget(), GravityView_Recent_Entries_Widget\widget(), wp_admin_bar_render(), wp_ajax_crop_image(), wp_ajax_delete_inactive_widgets(), wp_ajax_heartbeat(), wp_ajax_nopriv_heartbeat(), wp_ajax_save_widget(), WP_Customize_Widgets\wp_ajax_update_widget(), wp_allow_comment(), wp_blacklist_check(), wp_dashboard_right_now(), wp_dashboard_setup(), wp_delete_attachment(), wp_delete_comment(), wp_delete_link(), wp_delete_nav_menu(), wp_delete_post(), wp_delete_post_revision(), wp_delete_term(), wp_delete_user(), wp_xmlrpc_server\wp_deleteCategory(), wp_xmlrpc_server\wp_deleteComment(), wp_xmlrpc_server\wp_deletePage(), wp_xmlrpc_server\wp_deletePost(), wp_xmlrpc_server\wp_deleteTerm(), wp_xmlrpc_server\wp_editComment(), wp_xmlrpc_server\wp_editPage(), wp_xmlrpc_server\wp_editPost(), wp_xmlrpc_server\wp_editProfile(), wp_xmlrpc_server\wp_editTerm(), wp_enqueue_media(), wp_enqueue_scripts(), wp_footer(), wp_xmlrpc_server\wp_getAuthors(), wp_xmlrpc_server\wp_getComment(), wp_xmlrpc_server\wp_getCommentCount(), wp_xmlrpc_server\wp_getComments(), wp_xmlrpc_server\wp_getCommentStatusList(), wp_xmlrpc_server\wp_getMediaItem(), wp_xmlrpc_server\wp_getMediaLibrary(), wp_xmlrpc_server\wp_getPage(), wp_xmlrpc_server\wp_getPageList(), wp_xmlrpc_server\wp_getPages(), wp_xmlrpc_server\wp_getPageStatusList(), wp_xmlrpc_server\wp_getPost(), wp_xmlrpc_server\wp_getPostFormats(), wp_xmlrpc_server\wp_getPosts(), wp_xmlrpc_server\wp_getPostStatusList(), wp_xmlrpc_server\wp_getPostType(), wp_xmlrpc_server\wp_getPostTypes(), wp_xmlrpc_server\wp_getProfile(), wp_xmlrpc_server\wp_getRevisions(), wp_xmlrpc_server\wp_getTags(), wp_xmlrpc_server\wp_getTaxonomies(), wp_xmlrpc_server\wp_getTaxonomy(), wp_xmlrpc_server\wp_getTerm(), wp_xmlrpc_server\wp_getTerms(), wp_xmlrpc_server\wp_getUser(), wp_xmlrpc_server\wp_getUsers(), wp_xmlrpc_server\wp_getUsersBlogs(), wp_handle_comment_submission(), wp_head(), wp_iframe(), wp_insert_comment(), wp_insert_link(), wp_insert_post(), wp_insert_term(), wp_insert_user(), WP_Customize_Manager\wp_loaded(), wp_meta(), wp_nav_menu_update_menu_items(), wp_network_dashboard_right_now(), wp_new_comment(), wp_xmlrpc_server\wp_newCategory(), wp_xmlrpc_server\wp_newComment(), wp_xmlrpc_server\wp_newPage(), wp_xmlrpc_server\wp_newPost(), wp_xmlrpc_server\wp_newTerm(), wp_playlist_shortcode(), wp_plugin_update_row(), wp_print_footer_scripts(), wp_print_head_scripts(), wp_print_media_templates(), wp_print_scripts(), wp_print_styles(), wp_publish_post(), wp_register_sidebar_widget(), wp_remove_object_terms(), wp_restore_post_revision(), wp_xmlrpc_server\wp_restoreRevision(), wp_set_comment_status(), wp_set_object_terms(), wp_signon(), wp_spam_comment(), wp_xmlrpc_server\wp_suggestCategories(), wp_theme_update_row(), wp_transition_comment_status(), wp_transition_post_status(), wp_trash_comment(), wp_trash_post(), wp_trash_post_comments(), wp_unregister_sidebar_widget(), wp_unspam_comment(), wp_untrash_comment(), wp_untrash_post(), wp_untrash_post_comments(), wp_update_comment(), wp_update_comment_count_now(), wp_update_nav_menu_item(), wp_update_nav_menu_object(), wp_update_term(), wp_version_check(), wp_widgets_init(), wpmu_activate_signup(), wpmu_create_blog(), wpmu_create_user(), wpmu_delete_blog(), wpmu_delete_user(), wpmu_signup_blog(), wpmu_signup_user(), and wpmu_update_blogs_date().
do_action_ref_array ($tag, $args)
Execute functions hooked on a specific action hook, specifying arguments in an array.
Since
2.1.0
See also
do_action() This function is identical, but the arguments passed to the functions hooked to $tag< are supplied using an array. array $wp_filter Stores all of the filters array $wp_actions Increments the amount of times action was triggered. array $merged_filters Merges the filter hooks using this function. array $wp_current_filter Stores the list of current filters with the current one last
Parameters
string $tag The name of the action to be executed.
array $args The arguments supplied to the functions hooked to $tag.
Definition at line 566 of file wp-includes/plugin.php.
References $merged_filters, $wp_actions, $wp_current_filter, $wp_filter, and _wp_call_all_hook().
doing_action ($action = null)
Retrieve the name of an action currently being processed.
Since
3.9.0
Parameters
string | null $action Optional. Action to check. Defaults to null, which checks if any action is currently being run.
Returns
bool Whether the action is currently in the stack.
Definition at line 433 of file wp-includes/plugin.php.
References $action, and doing_filter().
Referenced by wp_version_check().
doing_filter ($filter = null)
Retrieve the name of a filter currently being processed.
The function current_filter() only returns the most recent filter or action being executed. did_action() returns true once the action is initially processed.
This function allows detection for any filter currently being executed (despite not being the most recent filter to fire, in the case of hooks called from hook callbacks) to be verified.
Since
3.9.0
See also
current_filter()
did_action() array $wp_current_filter Current filter.
Parameters
null | string $filter Optional. Filter to check. Defaults to null, which checks if any filter is currently being run.
Returns
bool Whether the filter is currently in the stack.
Definition at line 414 of file wp-includes/plugin.php.
References $wp_current_filter, and null.
Referenced by doing_action().
has_action ($tag, $function_to_check = false)
Check if any action has been registered for a hook.
Since
2.5.0
See also
has_filter() has_action() is an alias of has_filter().
Parameters
string $tag The name of the action hook.
callable | bool $function_to_check Optional. The callback to check for. Default false.
Returns
bool|int If $function_to_check is omitted, returns boolean for whether the hook has anything registered. When checking a specific function, the priority of that hook is returned, or false if the function is not attached. When using the $function_to_check argument, this function may return a non-boolean value that evaluates to false (e.g.) 0, so use the === operator for testing the return value.
Definition at line 624 of file wp-includes/plugin.php.
References has_filter().
Referenced by display_setup_form(), do_feed(), get_plugin_page_hook(), WP_Customize_Setting\preview(), WP_Screen\render_meta_boxes_preferences(), Tests_REST_API\test_init_action_added(), and WP_Customize_Setting\update().
has_filter ($tag, $function_to_check = false)
Check if any filter has been registered for a hook.
Since
2.5.0
array $wp_filter Stores all of the filters.
Parameters
string $tag The name of the filter hook.
callable | bool $function_to_check Optional. The callback to check for. Default false.
Returns
false|int If $function_to_check is omitted, returns boolean for whether the hook has anything registered. When checking a specific function, the priority of that hook is returned, or false if the function is not attached. When using the $function_to_check argument, this function may return a non-boolean value that evaluates to false (e.g.) 0, so use the === operator for testing the return value.
Definition at line 128 of file wp-includes/plugin.php.
References $GLOBALS, $wp_filter, and _wp_filter_build_unique_id().
Referenced by GFPaymentAddOn\add_subscription_payment(), WP\build_query_string(), GFPaymentAddOn\cancel_subscription(), WP_MS_Sites_List_Table\column_plugins(), GFPaymentAddOn\complete_payment(), _WP_Editors\editor(), GFPaymentAddOn\fail_subscription_payment(), WP_MS_Sites_List_Table\get_columns(), has_action(), GFPaymentAddOn\insert_transaction(), GFEntryDetail\lead_detail_page(), map_meta_cap(), GFFormDisplay\maybe_add_review_page(), GFPaymentAddOn\post_payment_action(), WP_Customize_Nav_Menu_Item_Setting\preview(), GFPaymentAddOn\process_callback_action(), GFPaymentAddOn\refund_payment(), GFPaymentAddOn\start_subscription(), and Core_Upgrader\upgrade().
plugin_basename ($file)
Gets the basename of a plugin.
This method extracts the name of a plugin from its filename.
Since
1.5.0
array $wp_plugin_paths
Parameters
string $file The filename of plugin.
Returns
string The name of a plugin.
Definition at line 675 of file wp-includes/plugin.php.
References $dir, $file, and wp_normalize_path().
Referenced by _get_plugin_data_markup_translate(), activate_plugin(), GravityView_Admin\add_hooks(), add_menu_page(), add_submenu_page(), deactivate_plugins(), get_plugin_files(), get_plugins(), is_uninstallable_plugin(), GravityView_Extension\load_plugin_textdomain(), GFForms\plugin_settings_link(), plugins_url(), register_activation_hook(), register_deactivation_hook(), register_uninstall_hook(), and uninstall_plugin().
plugin_dir_path ($file)
Get the filesystem directory path (with trailing slash) for the plugin FILE passed in.
Since
2.8.0
Parameters
string $file The filename of the plugin (FILE).
Returns
string the filesystem path of the directory that contains the plugin.
Definition at line 742 of file wp-includes/plugin.php.
References $file, and trailingslashit().
Referenced by GravityView_Widget_Search\__construct(), GravityView_Uninstall\__construct(), GravityView_Delete_Entry\__construct(), GravityView_Edit_Entry\__construct(), GravityView_Widget_Poll\add_template_path(), and GravityView_Extension\settings().
plugin_dir_url ($file)
Get the URL directory path (with trailing slash) for the plugin FILE passed in.
Since
2.8.0
Parameters
string $file The filename of the plugin (FILE).
Returns
string the URL path of the directory that contains the plugin.
Definition at line 754 of file wp-includes/plugin.php.
References $file, plugins_url(), and trailingslashit().
register_activation_hook ($file, $function)
Set the activation hook for a plugin.
When a plugin is activated, the action 'activate_PLUGINNAME' hook is called. In the name of this hook, PLUGINNAME is replaced with the name of the plugin, including the optional subdirectory. For example, when the plugin is located in wp-content/plugins/sampleplugin/sample.php, then the name of this hook will become 'activate_sampleplugin/sample.php'.
When the plugin consists of only one file and is (as by default) located at wp-content/plugins/sample.php the name of this hook will be 'activate_sample.php'.
Since
2.0.0
Parameters
string $file The filename of the plugin including the path.
callable $function The function hooked to the 'activate_PLUGIN' action.
Definition at line 776 of file wp-includes/plugin.php.
References $file, add_action(), and plugin_basename().
Referenced by GV_Unit_Tests_Bootstrap\load_rest_api().
register_deactivation_hook ($file, $function)
Set the deactivation hook for a plugin.
When a plugin is deactivated, the action 'deactivate_PLUGINNAME' hook is called. In the name of this hook, PLUGINNAME is replaced with the name of the plugin, including the optional subdirectory. For example, when the plugin is located in wp-content/plugins/sampleplugin/sample.php, then the name of this hook will become 'deactivate_sampleplugin/sample.php'.
When the plugin consists of only one file and is (as by default) located at wp-content/plugins/sample.php the name of this hook will be 'deactivate_sample.php'.
Since
2.0.0
Parameters
string $file The filename of the plugin including the path.
callable $function The function hooked to the 'deactivate_PLUGIN' action.
Definition at line 799 of file wp-includes/plugin.php.
References $file, add_action(), and plugin_basename().
Referenced by GV_Unit_Tests_Bootstrap\load_rest_api().
register_uninstall_hook ($file, $callback)
Set the uninstallation hook for a plugin.
Registers the uninstall hook that will be called when the user clicks on the uninstall link that calls for the plugin to uninstall itself. The link won't be active unless the plugin hooks into the action.
The plugin should not run arbitrary code outside of functions, when registering the uninstall hook. In order to run using the hook, the plugin will have to be included, which means that any code laying outside of a function will be run during the uninstall process. The plugin should not hinder the uninstall process.
If the plugin can not be written without running code within the plugin, then the plugin should create a file named 'uninstall.php' in the base plugin folder. This file will be called, if it exists, during the uninstall process bypassing the uninstall hook. The plugin, when using the 'uninstall.php' should always check for the 'WP_UNINSTALL_PLUGIN' constant, before executing.
Since
2.7.0
Parameters
string $file Plugin file.
callable $callback The callback to run when the hook is called. Must be a static method or function.
Definition at line 830 of file wp-includes/plugin.php.
References $file, __, _doing_it_wrong(), get_option(), plugin_basename(), and update_option().
remove_action ($tag, $function_to_remove, $priority = 10)
Removes a function from a specified action hook.
This function removes a function attached to a specified action hook. This method can be used to remove default functions attached to a specific filter hook and possibly replace them with a substitute.
Since
1.2.0
Parameters
string $tag The action hook to which the function to be removed is hooked.
callable $function_to_remove The name of the function which should be removed.
int $priority Optional. The priority of the function. Default 10.
Returns
bool Whether the function is removed.
Definition at line 642 of file wp-includes/plugin.php.
References remove_filter().
Referenced by WP_Customize_Manager\__construct(), _remove_theme_support(), add_feed(), automatic_feed_links(), check_theme_switched(), Plugin_Upgrader\install(), Theme_Upgrader\install(), GravityView_Change_Entry_Creator\prevent_conflicts(), GravityView_Edit_Entry_Render\prevent_maybe_process_form(), GravityView_Admin_Bar\remove_links(), WP_Customize_Manager\remove_preview_signature(), WP_Automatic_Updater\run(), WP_Ajax_UnitTestCase\setUpBeforeClass(), WP_MS_Themes_List_Table\single_row(), WP_Ajax_UnitTestCase\tearDown(), GravityView_Ajax_Test\test_get_available_fields_html(), and wp_print_media_templates().
remove_all_actions ($tag, $priority = false)
Remove all of the hooks from an action.
Since
2.7.0
Parameters
string $tag The action to remove hooks from.
int | bool $priority The priority number to remove them from. Default false.
Returns
true True when finished.
Definition at line 655 of file wp-includes/plugin.php.
References remove_all_filters().
remove_all_filters ($tag, $priority = false)
Remove all of the hooks from a filter.
Since
2.7.0
array $wp_filter Stores all of the filters array $merged_filters Merges the filter hooks using this function.
Parameters
string $tag The filter to remove hooks from.
int | bool $priority Optional. The priority number to remove. Default false.
Returns
true True when finished.
Definition at line 352 of file wp-includes/plugin.php.
References $merged_filters, $wp_filter, and elseif.
Referenced by Language_Pack_Upgrader\bulk_upgrade(), GV_Unit_Tests_Bootstrap\load(), remove_all_actions(), GV_UnitTestCase\setUp(), and GravityView_Merge_Tags_Test\test_gf_merge_tags().
remove_filter ($tag, $function_to_remove, $priority = 10)
Removes a function from a specified filter hook.
This function removes a function attached to a specified filter hook. This method can be used to remove default functions attached to a specific filter hook and possibly replace them with a substitute.
To remove a hook, the $function_to_remove and $priority arguments must match when the hook was added. This goes for both filters and actions. No warning will be given on removal failure.
Since
1.2.0
array $wp_filter Stores all of the filters array $merged_filters Merges the filter hooks using this function.
Parameters
string $tag The filter hook to which the function to be removed is hooked.
callable $function_to_remove The name of the function which should be removed.
int $priority Optional. The priority of the function. Default 10.
Returns
bool Whether the function existed before it was removed.
Definition at line 321 of file wp-includes/plugin.php.
References $GLOBALS, and _wp_filter_build_unique_id().
Referenced by GravityView_Field_Time\_modify_query_sort_by_time_hack(), _wp_post_thumbnail_class_filter_remove(), Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), Language_Pack_Upgrader\bulk_upgrade(), Theme_Upgrader\check_parent_theme_filter(), WP_Customize_Nav_Menus\customize_register(), GFFormsModel\dbDelta(), _WP_Editors\editor(), GravityView_API\field_class(), GravityView_Field_Time\field_options(), GravityView_oEmbed\generate_entry_output(), GVCommon\get_entries(), GravityView_frontend\insert_view_in_content(), Plugin_Upgrader\install(), Theme_Upgrader\install(), kses_remove_filters(), GravityView_Edit_Entry_Render\prevent_render_form(), remove_action(), GravityView_Edit_Entry_Render\render_edit_form(), GFForms\setup_database(), WPProfiler\stop(), WP_Customize_Widgets\stop_capturing_option_updates(), WP_Customize_Manager\stop_previewing_theme(), WP_XMLRPC_UnitTestCase\tearDown(), WP_Ajax_UnitTestCase\tearDown(), WP_UnitTestCase\tearDown(), GVCommon_Test\test_get_link_html(), GravityView_Merge_Tags_Test\test_gf_merge_tags(), GravityView_API_Test\test_gravityview_field_output(), GravityView_API_Test\test_no_results(), GravityView_Merge_Tags_Test\test_replace_get_variables(), GravityView_Shortcode_Test\test_shortcode_get_view_detail_PAGING(), GravityView_Shortcode_Test\test_shortcode_get_view_detail_TOTAL_ENTRIES(), unregister_setting(), unregister_taxonomy(), GravityView_Edit_Entry_User_Registration\update_user(), Plugin_Upgrader\upgrade(), Theme_Upgrader\upgrade(), GFFeedAddOn\upgrade_base(), GravityView_Edit_Entry_Render\validate(), welcome_user_msg_filter(), wp_ajax_crop_image(), wp_ajax_send_attachment_to_editor(), and wp_link_manager_disabled_message().
wp_register_plugin_realpath ($file)
Register a plugin's real path.
This is used in plugin_basename() to resolve symlinked paths.
Since
3.9.0
See also
plugin_basename()
array $wp_plugin_paths
string $wp_plugin_path string $wpmu_plugin_path
Parameters
string $file Known path to the file.
Returns
bool Whether the path was able to be registered.
Definition at line 710 of file wp-includes/plugin.php.
References $file, null, and wp_normalize_path().
Referenced by activate_plugin(), plugin_sandbox_scrape(), and uninstall_plugin().
Variable Documentation
global $merged_filters
Definition at line 23 of file wp-includes/plugin.php.
Referenced by add_filter(), apply_filters(), apply_filters_ref_array(), do_action(), do_action_ref_array(), remove_all_filters(), and tests_add_filter().
global $wp_actions
Definition at line 23 of file wp-includes/plugin.php.
Referenced by WPProfiler\_current_action(), MockAction\current_filter(), did_action(), do_action(), do_action_ref_array(), WPProfiler\log_filter(), and WP_Importer\stop_the_insanity().
global $wp_current_filter
Definition at line 23 of file wp-includes/plugin.php.
Referenced by apply_filters(), apply_filters_ref_array(), current_filter(), do_action(), do_action_ref_array(), and doing_filter().
global $wp_filter
Definition at line 23 of file wp-includes/plugin.php.
Referenced by _test_filter_build_unique_id(), _wp_call_all_hook(), _wp_filter_build_unique_id(), add_filter(), apply_filters(), apply_filters_ref_array(), do_action(), do_action_ref_array(), has_filter(), remove_all_filters(), and tests_add_filter().