GravityView: comment.php File Reference
wp-includes/comment.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_close_comments_for_old_post ($open, $post_id)
Close comments on an old post.
_close_comments_for_old_posts ($posts, $query)
Close comments on old posts on the fly, without any extra DB queries.
_prime_comment_caches ($comment_ids, $update_meta_cache=true)
Adds any comments from the given IDs to the cache that do not already exist in cache.
add_comment_meta ($comment_id, $meta_key, $meta_value, $unique=false)
Add meta data field to a comment.
check_comment ($author, $email, $url, $comment, $user_ip, $user_agent, $comment_type)
Check whether a comment passes internal checks to be allowed to add.
check_comment_flood_db ($ip, $email, $date)
Check whether comment flooding is occurring.
clean_comment_cache ($ids)
Removes comment ID from the comment cache.
delete_comment_meta ($comment_id, $meta_key, $meta_value= '')
Remove metadata matching criteria from a comment.
discover_pingback_server_uri ($url, $deprecated= '')
Finds a pingback server URI based on the given URL.
do_all_pings ()
Perform all pingbacks, enclosures, trackbacks, and send to pingback services.
do_trackbacks ($post_id)
Perform trackbacks.
generic_ping ($post_id=0)
Sends pings to all of the ping site services.
get_approved_comments ($post_id, $args=array())
Retrieve the approved comments for post $post_id.
get_comment (&$comment=null, $output=OBJECT)
Retrieves comment data given a comment ID or comment object.
get_comment_count ($post_id=0)
The amount of comments in a post or total comments.
get_comment_meta ($comment_id, $key= '', $single=false)
Retrieve comment meta field for a comment.
get_comment_pages_count ($comments=null, $per_page=null, $threaded=null)
Calculate the total number of comment pages.
get_comment_statuses ()
Retrieve all of the WordPress supported comment statuses.
get_comments ($args= '')
Retrieve a list of comments.
get_default_comment_status ($post_type= 'post', $comment_type= 'comment')
Gets the default comment status for a post type.
get_lastcommentmodified ($timezone= 'server')
The date the last comment was modified.
get_page_of_comment ($comment_ID, $args=array())
Calculate what page number a comment will appear on for comment paging.
pingback ($content, $post_ID)
Pings back the links found in a post.
pingback_ping_source_uri ($source_uri)
Default filter attached to pingback_ping_source_uri to validate the pingback's Source URI.
privacy_ping_filter ($sites)
Check whether blog is public before returning sites.
sanitize_comment_cookies ()
Sanitizes the cookies sent to the user already.
separate_comments (&$comments)
Separates an array of comments into an array keyed by comment_type.
trackback ($trackback_url, $title, $excerpt, $ID)
Send a Trackback.
update_comment_cache ($comments, $update_meta_cache=true)
Updates the comment cache of given comments.
update_comment_meta ($comment_id, $meta_key, $meta_value, $prev_value= '')
Update comment meta field based on comment ID.
weblog_ping ($server= '', $path= '')
Send a pingback.
wp_allow_comment ($commentdata)
Validates whether this comment is allowed to be made.
wp_blacklist_check ($author, $email, $url, $comment, $user_ip, $user_agent)
Does comment contain blacklisted characters or words.
wp_count_comments ($post_id=0)
Retrieve total comments for blog or single post.
wp_defer_comment_counting ($defer=null)
Whether to defer comment counting.
wp_delete_comment ($comment_id, $force_delete=false)
Trashes or deletes a comment.
wp_filter_comment ($commentdata)
Filters and sanitizes comment data.
wp_get_comment_column_max_length ($column)
Calculate the maximum character length of a column from the comments table.
wp_get_comment_status ($comment_id)
The status of a comment by ID.
wp_get_current_commenter ()
Get current commenter's name, email, and URL.
wp_handle_comment_submission ($comment_data)
Handles the submission of a comment, usually posted to wp-comments-post.php via a comment form.
wp_insert_comment ($commentdata)
Inserts a comment into the database.
wp_new_comment ($commentdata)
Adds a new comment to the database.
wp_new_comment_notify_moderator ($comment_ID)
Send a comment moderation notification to the comment moderator.
wp_new_comment_notify_postauthor ($comment_ID)
Send a notification of a new comment to the post author.
wp_set_comment_cookies ($comment, $user)
Sets the cookies used to store an unauthenticated commentator's identity.
wp_set_comment_status ($comment_id, $comment_status, $wp_error=false)
Sets the status of a comment.
wp_spam_comment ($comment_id)
Marks a comment as Spam.
wp_throttle_comment_flood ($block, $time_lastcomment, $time_newcomment)
Whether a comment should be blocked because of comment flood.
wp_transition_comment_status ($new_status, $old_status, $comment)
Call hooks for when a comment status transition occurs.
wp_trash_comment ($comment_id)
Moves a comment to the Trash.
wp_unspam_comment ($comment_id)
Removes a comment from the Spam.
wp_untrash_comment ($comment_id)
Removes a comment from the Trash.
wp_update_comment ($commentarr)
Updates an existing comment in the database.
wp_update_comment_count ($post_id, $do_deferred=false)
Updates the comment count for post(s).
wp_update_comment_count_now ($post_id)
Updates the comment count for the post.
xmlrpc_pingback_error ($ixr_error)
Default filter attached to xmlrpc_pingback_error.
Function Documentation
_close_comments_for_old_post ($open, $post_id)
Close comments on an old post.
Hooked to comments_open and pings_open.
private
Since
2.7.0
Parameters
bool $open Comments open or closed
int $post_id Post ID
Returns
bool $open
This filter is documented in wp-includes/comment.php
Definition at line 2616 of file wp-includes/comment.php.
References $post, $post_id, apply_filters(), get_option(), and get_post().
_close_comments_for_old_posts ($posts, $query)
Close comments on old posts on the fly, without any extra DB queries.
Hooked to the_posts.
private
Since
2.7.0
Parameters
WP_Post $posts Post data object.
WP_Query $query Query object.
Returns
array
Filter the list of post types to automatically close comments for.
Since
3.2.0
Parameters
array $post_types An array of registered post types. Default array with 'post'.
Definition at line 2579 of file wp-includes/comment.php.
References apply_filters(), get_option(), and post_type.
_prime_comment_caches ($comment_ids, $update_meta_cache = true)
Adds any comments from the given IDs to the cache that do not already exist in cache.
Since
4.4.0 private
See also
update_comment_cache() wpdb $wpdb WordPress database abstraction object.
Parameters
array $comment_ids Array of comment IDs.
bool $update_meta_cache Optional. Whether to update the meta cache. Default true.
Definition at line 2554 of file wp-includes/comment.php.
References $wpdb, _get_non_cached_ids(), and update_comment_cache().
Referenced by WP_Comment_Query\fill_descendants(), and WP_Comment_Query\get_comments().
add_comment_meta ($comment_id, $meta_key, $meta_value, $unique = false)
Add meta data field to a comment.
Since
2.9.0 int $comment_id Comment ID. string $meta_key Metadata name. mixed $meta_value Metadata value. bool $unique Optional, default is false. Whether the same key should not be added. int|bool Meta ID on success, false on failure.
Definition at line 411 of file wp-includes/comment.php.
References add_metadata().
Referenced by wp_insert_comment(), wp_spam_comment(), and wp_trash_comment().
check_comment ($author, $email, $url, $comment, $user_ip, $user_agent, $comment_type)
Check whether a comment passes internal checks to be allowed to add.
If manual comment moderation is set in the administration, then all checks, regardless of their type and whitelist, will fail and the function will return false.
If the number of links exceeds the amount in the administration, then the check fails. If any of the parameter contents match the blacklist of words, then the check fails.
If the comment author was approved before, then the comment is automatically whitelisted.
If all checks pass, the function will return true.
Since
1.2.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $author Comment author name.
string $email Comment author email.
string $url Comment author URL.
string $comment Content of the comment.
string $user_ip Comment author IP address.
string $user_agent Comment author User-Agent.
string $comment_type Comment type, either user-submitted comment, trackback, or pingback.
Returns
bool If all checks pass, true, otherwise false.
This filter is documented in wp-includes/comment-template.php
Filter the maximum number of links allowed in a comment.
Since
3.0.0
Parameters
int $num_links The number of links allowed.
string $url Comment author's URL. Included in allowed links total.
Definition at line 39 of file wp-includes/comment.php.
References $comment, $out, $url, $wpdb, apply_filters(), and get_option().
Referenced by wp_allow_comment().
check_comment_flood_db ($ip, $email, $date)
Check whether comment flooding is occurring.
Won't run, if current user can manage options, so to not block administrators.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $ip Comment IP.
string $email Comment author email address.
string $date MySQL time string.
Filter the comment flood status.
Since
2.1.0
Parameters
bool $bool Whether a comment flood is occurring. Default false.
int $time_lastcomment Timestamp of when the last comment was posted.
int $time_newcomment Timestamp of when the new comment was posted.
Fires before the comment flood message is triggered.
Since
1.5.0
Parameters
int $time_lastcomment Timestamp of when the last comment was posted.
int $time_newcomment Timestamp of when the new comment was posted.
Definition at line 702 of file wp-includes/comment.php.
References $user, $wpdb, __, apply_filters(), current_user_can(), do_action(), get_current_user_id(), mysql2date(), and wp_die().
clean_comment_cache ($ids)
Removes comment ID from the comment cache.
Since
2.3.0
Parameters
int | array $ids Comment ID or array of comment IDs to remove from cache
Definition at line 2507 of file wp-includes/comment.php.
References $id, wp_cache_delete(), and wp_cache_set().
Referenced by wp_delete_comment(), wp_set_comment_status(), wp_trash_post_comments(), wp_untrash_post_comments(), and wp_update_comment().
delete_comment_meta ($comment_id, $meta_key, $meta_value = '')
Remove metadata matching criteria from a comment.
You can match based on the key, or key and value. Removing based on key and value, will keep from removing duplicate metadata with the same key. It also allows removing all metadata matching key, if needed.
Since
2.9.0 int $comment_id comment ID string $meta_key Metadata name. mixed $meta_value Optional. Metadata value. bool True on success, false on failure.
Definition at line 430 of file wp-includes/comment.php.
References delete_metadata().
Referenced by wp_scheduled_delete(), wp_spam_comment(), wp_trash_comment(), wp_unspam_comment(), and wp_untrash_comment().
discover_pingback_server_uri ($url, $deprecated = '')
Finds a pingback server URI based on the given URL.
Checks the HTML for the rel="pingback" link and x-pingback headers. It does a check for the x-pingback headers first and returns that, if available. The check for the rel="pingback" has more overhead than just the header.
Since
1.5.0
Parameters
string $url URL to ping.
int $deprecated Not Used.
Returns
false|string False on failure, string containing URI on success.
Definition at line 2135 of file wp-includes/comment.php.
References $deprecated, $url, _deprecated_argument(), is_wp_error(), wp_remote_retrieve_body(), wp_remote_retrieve_header(), wp_safe_remote_get(), wp_safe_remote_head(), and wp_upload_dir().
Referenced by pingback().
do_all_pings ()
Perform all pingbacks, enclosures, trackbacks, and send to pingback services.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 2200 of file wp-includes/comment.php.
References $wpdb, delete_metadata_by_mid(), do_enclose(), do_trackbacks(), generic_ping(), and pingback().
do_trackbacks ($post_id)
Perform trackbacks.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Post ID to do trackbacks on.
This filter is documented in wp-includes/post-template.php
This filter is documented in wp-includes/post-template.php
This filter is documented in wp-includes/post-template.php
Definition at line 2234 of file wp-includes/comment.php.
References $excerpt, $post, $post_id, $post_title, $wpdb, apply_filters(), get_post(), get_pung(), get_to_ping(), str_replace, trackback(), and wp_html_excerpt().
Referenced by do_all_pings().
generic_ping ($post_id = 0)
Sends pings to all of the ping site services.
Since
1.2.0
Parameters
int $post_id Post ID.
Returns
int Same as Post ID from parameter
Definition at line 2281 of file wp-includes/comment.php.
References $post_id, get_option(), and weblog_ping().
Referenced by do_all_pings().
get_approved_comments ($post_id, $args = array())
Retrieve the approved comments for post $post_id.
Since
2.0.0
4.1.0 Refactored to leverage {
See also
WP_Comment_Query} over a direct query.
Parameters
int $post_id The ID of the post.
array $args Optional. See {
See also
WP_Comment_Query::query()} for information on accepted arguments.
Returns
int|array $comments The approved comments, or number of comments if $count argument is true.
Definition at line 139 of file wp-includes/comment.php.
References $post_id, WP_Comment_Query\query(), and wp_parse_args().
get_comment (& $comment = null, $output = OBJECT)
Retrieves comment data given a comment ID or comment object.
If an object is passed then the comment data will be cached and then returned after being passed through a filter. If the comment is empty, then the global comment variable will be used, if it is set.
Since
2.0.0
WP_Comment $comment
Parameters
WP_Comment | string | int $comment Comment to retrieve.
string $output Optional. OBJECT or ARRAY_A or ARRAY_N constants.
Returns
WP_Comment|array|null Depends on $output value.
Fires after a comment is retrieved.
Since
2.3.0
Parameters
mixed $_comment Comment data.
Definition at line 170 of file wp-includes/comment.php.
References $comment, $GLOBALS, $output, apply_filters(), ARRAY_A, ARRAY_N, elseif, WP_Comment\get_instance(), null, and OBJECT.
Referenced by _wp_ajax_delete_comment_response(), WP_Comments_List_Table\column_comment(), comment_author(), comment_author_email(), comment_author_url(), comment_excerpt(), comment_form_title(), comment_text(), edit_comment_link(), export_wp(), WP_Comment_Query\fill_descendants(), WP_Comments_List_Table\floated_admin_avatar(), floated_admin_avatar(), get_avatar_data(), get_comment_author(), get_comment_author_email(), get_comment_author_email_link(), get_comment_author_IP(), get_comment_author_link(), get_comment_author_url(), get_comment_class(), get_comment_date(), get_comment_excerpt(), get_comment_guid(), get_comment_ID(), get_comment_link(), get_comment_reply_link(), get_comment_text(), get_comment_time(), get_comment_to_edit(), get_comment_type(), get_commentdata(), WP_Comment_Query\get_comments(), get_edit_comment_link(), WP_UnitTest_Factory_For_Comment\get_object_by_id(), get_page_of_comment(), map_meta_cap(), touch_time(), wp_ajax_delete_comment(), wp_ajax_dim_comment(), wp_ajax_edit_comment(), wp_ajax_get_comments(), wp_ajax_replyto_comment(), wp_delete_comment(), wp_xmlrpc_server\wp_deleteComment(), wp_xmlrpc_server\wp_editComment(), wp_get_comment_status(), wp_xmlrpc_server\wp_getComment(), wp_handle_comment_submission(), wp_insert_comment(), wp_new_comment_notify_moderator(), wp_new_comment_notify_postauthor(), wp_scheduled_delete(), wp_set_comment_status(), wp_spam_comment(), wp_trash_comment(), wp_unspam_comment(), wp_untrash_comment(), and wp_update_comment().
get_comment_count ($post_id = 0)
The amount of comments in a post or total comments.
A lot like wp_count_comments(), in that they both return comment stats (albeit with different types). The wp_count_comments() actual caches, but this function does not.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Optional. Comment amount in post if > 0, else total comments blog wide.
Returns
array The amount of spam, approved, awaiting moderation, and total comments.
Definition at line 338 of file wp-includes/comment.php.
References $post_id, $wpdb, and ARRAY_A.
Referenced by wp_count_comments().
get_comment_meta ($comment_id, $key = '', $single = false)
Retrieve comment meta field for a comment.
Since
2.9.0 int $comment_id Comment ID. string $key Optional. The meta key to retrieve. By default, returns data for all keys. bool $single Whether to return a single value. mixed Will be an array if $single is false. Will be value of meta data field if $single is true.
Definition at line 446 of file wp-includes/comment.php.
References get_metadata().
Referenced by WP_Comments_List_Table\handle_row_actions(), wp_unspam_comment(), and wp_untrash_comment().
get_comment_pages_count ($comments = null, $per_page = null, $threaded = null)
Calculate the total number of comment pages.
Since
2.7.0
Walker_Comment
WP_Query $wp_query
Parameters
array $comments Optional array of WP_Comment objects. Defaults to $wp_query->comments
int $per_page Optional comments per page.
bool $threaded Optional control over flat or threaded comments.
Returns
int Number of comment pages.
Definition at line 794 of file wp-includes/comment.php.
References $count, get_option(), get_query_var(), and null.
Referenced by comments_template(), get_next_comments_link(), get_the_comments_navigation(), paginate_comments_links(), and wp_list_comments().
get_comment_statuses ()
Retrieve all of the WordPress supported comment statuses.
Comments have a limited set of valid status values, this provides the comment status values and descriptions.
Since
2.7.0
Returns
array List of comment statuses.
Definition at line 232 of file wp-includes/comment.php.
References __, and _x.
Referenced by wp_xmlrpc_server\wp_editComment(), and wp_xmlrpc_server\wp_getCommentStatusList().
get_comments ($args = '')
Retrieve a list of comments.
The comment list can be for the blog as a whole or for an individual post.
Since
2.7.0
Parameters
string | array $args Optional. Array or string of arguments. See {
See also
WP_Comment_Query::parse_query()} for information on accepted arguments. Default empty.
Returns
int|array List of comments or number of found comments if $count argument is true.
Definition at line 217 of file wp-includes/comment.php.
References WP_Comment_Query\query().
Referenced by WP_Comment\get_children(), post_comment_meta_box(), WP_Comments_List_Table\prepare_items(), WP_Widget_Recent_Comments\widget(), wp_xmlrpc_server\wp_getComments(), and wp_list_comments().
get_default_comment_status ($post_type = 'post', $comment_type = 'comment')
Gets the default comment status for a post type.
Since
4.3.0
Parameters
string $post_type Optional. Post type. Default 'post'.
string $comment_type Optional. Comment type. Default 'comment'.
Returns
string Expected return value is 'open' or 'closed'.
Filter the default comment status for the given post type.
Since
4.3.0
Parameters
string $status Default status for the given post type, either 'open' or 'closed'.
string $post_type Post type. Default is post.
string $comment_type Type of comment. Default is comment.
Definition at line 252 of file wp-includes/comment.php.
References $option, $post_type, apply_filters(), elseif, get_option(), and post_type_supports().
Referenced by get_default_post_to_edit(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), and wp_insert_post().
get_lastcommentmodified ($timezone = 'server')
The date the last comment was modified.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object. array $cache_lastcommentmodified
Parameters
string $timezone Which timezone to use in reference to 'gmt', 'blog', or 'server' locations.
Returns
string Last comment modified date.
Definition at line 298 of file wp-includes/comment.php.
References $wpdb, and date.
Referenced by WP\send_headers().
get_page_of_comment ($comment_ID, $args = array())
Calculate what page number a comment will appear on for comment paging.
Since
2.7.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $comment_ID Comment ID.
array $args { Array of optional arguments. string $type Limit paginated comments to those matching a given type. Accepts 'comment', 'trackback', 'pingback', 'pings' (trackbacks and pingbacks), or 'all'. Default is 'all'. int $per_page Per-page count to use when calculating pagination. Defaults to the value of the 'comments_per_page' option. int|string $max_depth If greater than 1, comment page will be determined for the top-level parent of $comment_ID. Defaults to the value of the 'thread_comments_depth' option. } *
Returns
int|null Comment page number or null on error.
Filters the calculated page on which a comment appears.
Since
4.4.0
Parameters
int $page Comment page.
array $args { Arguments used to calculate pagination. These include arguments auto-detected by the function, based on query vars, system settings, etc. For pristine arguments passed to the function, see $original_args.
string $type Type of comments to count. int $page Calculated current page. int $per_page Calculated number of comments per page. int $max_depth Maximum comment threading depth allowed. }
Parameters
array $original_args { Array of arguments passed to the function. Some or all of these may not be set.
string $type Type of comments to count. int $page Current comment page. int $per_page Number of comments per page. int $max_depth Maximum comment threading depth allowed. }
Definition at line 850 of file wp-includes/comment.php.
References $comment, $page, $wpdb, apply_filters(), get_comment(), get_option(), get_query_var(), null, and wp_parse_args().
Referenced by get_comment_link().
pingback ($content, $post_ID)
Pings back the links found in a post.
Since
0.71
string $wp_version
Parameters
string $content Post content to check for links.
int $post_ID Post ID.
Fires just before pinging back links found in a post.
Since
2.0.0
Parameters
array &$post_links An array of post links to be checked, passed by reference.
array &$pung Whether a link has already been pinged, passed by reference.
int $post_ID The post ID.
Filter the user agent sent when pinging-back a URL.
Since
2.9.0
Parameters
string $concat_useragent The user agent concatenated with ' – WordPress/' and the WordPress version.
string $useragent The useragent.
string $pingback_server_url The server URL being linked to.
string $pagelinkedto URL of page linked to.
string $pagelinkedfrom URL of page linked from.
Definition at line 2304 of file wp-includes/comment.php.
References $content, $post_ID, $wp_version, ABSPATH, add_ping(), apply_filters(), discover_pingback_server_uri(), do_action_ref_array(), elseif, endforeach, endif, get_permalink(), get_pung(), is_local_attachment(), url_to_postid(), wp_extract_urls(), and WPINC.
Referenced by do_all_pings().
pingback_ping_source_uri ($source_uri)
Default filter attached to pingback_ping_source_uri to validate the pingback's Source URI.
Since
3.5.1
See also
wp_http_validate_url()
Parameters
string $source_uri
Returns
string
Definition at line 2474 of file wp-includes/comment.php.
References wp_http_validate_url().
privacy_ping_filter ($sites)
Check whether blog is public before returning sites.
Since
2.1.0
Parameters
mixed $sites Will return if blog is public, will not return if not public.
Returns
mixed Empty string if blog is not public, returns $sites, if site is public.
Definition at line 2392 of file wp-includes/comment.php.
References get_option().
sanitize_comment_cookies ()
Sanitizes the cookies sent to the user already.
Will only do anything if the cookies have already been created for the user. Mostly used after cookies had been sent to use elsewhere.
Since
2.0.4
Filter the comment author's name cookie before it is set.
When this filter hook is evaluated in wp_filter_comment(), the comment author's name string is passed.
Since
1.5.0
Parameters
string $author_cookie The comment author name cookie.
Filter the comment author's email cookie before it is set.
When this filter hook is evaluated in wp_filter_comment(), the comment author's email string is passed.
Since
1.5.0
Parameters
string $author_email_cookie The comment author email cookie.
Filter the comment author's URL cookie before it is set.
When this filter hook is evaluated in wp_filter_comment(), the comment author's URL string is passed.
Since
1.5.0
Parameters
string $author_url_cookie The comment author URL cookie.
Definition at line 506 of file wp-includes/comment.php.
References $_COOKIE, apply_filters(), esc_attr(), and wp_unslash().
separate_comments (& $comments)
Separates an array of comments into an array keyed by comment_type.
Since
2.7.0
Parameters
array $comments Array of comments
Returns
array Array of comments keyed by comment_type.
Definition at line 765 of file wp-includes/comment.php.
References $count, and $i.
Referenced by comments_template(), and wp_list_comments().
trackback ($trackback_url, $title, $excerpt, $ID)
Send a Trackback.
Updates database when sending trackback to prevent duplicates.
Since
0.71
wpdb $wpdb WordPress database abstraction object.
Parameters
string $trackback_url URL to send trackbacks.
string $title Title of post.
string $excerpt Excerpt of post.
int $ID Post ID.
Returns
int|false|void Database query from update.
Definition at line 2414 of file wp-includes/comment.php.
References $excerpt, $ID, $options, $title, $wpdb, get_option(), get_permalink(), is_wp_error(), and wp_safe_remote_post().
Referenced by do_trackbacks(), and trackback_url_list().
update_comment_cache ($comments, $update_meta_cache = true)
Updates the comment cache of given comments.
Will add the comments in $comments to the cache. If comment ID already exists in the comment cache then it will not be updated. The comment is added to the cache using the comment group with the key using the ID of the comments.
Since
2.3.0
4.4.0 Introduced the $update_meta_cache parameter.
Parameters
array $comments Array of comment row objects
bool $update_meta_cache Whether to update commentmeta cache. Default true.
Definition at line 2528 of file wp-includes/comment.php.
References $comment, update_meta_cache(), and wp_cache_add().
Referenced by _prime_comment_caches(), and WP_Comments_List_Table\prepare_items().
update_comment_meta ($comment_id, $meta_key, $meta_value, $prev_value = '')
Update comment meta field based on comment ID.
Use the $prev_value parameter to differentiate between meta fields with the same key and comment ID.
If the meta field for the comment does not exist, it will be added.
Since
2.9.0 int $comment_id Comment ID. string $meta_key Metadata key. mixed $meta_value Metadata value. mixed $prev_value Optional. Previous value to check before removing. int|bool Meta ID if the key didn't exist, true on successful update, false on failure.
Definition at line 467 of file wp-includes/comment.php.
References update_metadata().
weblog_ping ($server = '', $path = '')
Send a pingback.
Since
1.2.0
string $wp_version
Parameters
string $server Host of blog to connect to.
string $path Path to send the ping.
Definition at line 2448 of file wp-includes/comment.php.
References $path, $wp_version, ABSPATH, get_bloginfo(), get_option(), home_url(), trailingslashit(), and WPINC.
Referenced by generic_ping().
wp_allow_comment ($commentdata)
Validates whether this comment is allowed to be made.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $commentdata Contains information on the comment
Returns
int|string Signifies the approval status (0|1|'spam')
Filters the ID, if any, of the duplicate comment found when creating a new comment.
Return an empty value from this filter to allow what WP considers a duplicate comment.
Since
4.4.0
Parameters
int $dupe_id ID of the comment identified as a duplicate.
array $commentdata Data for the comment being created.
Fires immediately after a duplicate comment is detected.
Since
3.0.0
Parameters
array $commentdata Comment data.
Fires immediately before a comment is marked approved.
Allows checking for comment flooding.
Since
2.3.0
Parameters
string $comment_author_IP Comment author's IP address.
string $comment_author_email Comment author's email.
string $comment_date_gmt GMT date the comment was posted.
Filter a comment's approval status before it is set.
Since
2.1.0
Parameters
bool | string $approved The approval status. Accepts 1, 0, or 'spam'.
array $commentdata Comment data.
Definition at line 568 of file wp-includes/comment.php.
References $user, $wpdb, __, apply_filters(), check_comment(), do_action(), wp_blacklist_check(), wp_die(), and wp_unslash().
Referenced by wp_new_comment().
wp_blacklist_check ($author, $email, $url, $comment, $user_ip, $user_agent)
Does comment contain blacklisted characters or words.
Since
1.5.0
Parameters
string $author The author of the comment
string $email The email of the comment
string $url The url used in the comment
string $comment The comment content
string $user_ip The comment author IP address
string $user_agent The author's browser user agent
Returns
bool True if comment contains blacklisted content, false if comment does not
Fires before the comment is tested for blacklisted characters or words.
Since
1.5.0
Parameters
string $author Comment author.
string $email Comment author's email.
string $url Comment author's URL.
string $comment Comment content.
string $user_ip Comment author's IP address.
string $user_agent Comment author's browser user agent.
Definition at line 1000 of file wp-includes/comment.php.
References $comment, $url, do_action(), and get_option().
Referenced by wp_allow_comment().
wp_count_comments ($post_id = 0)
Retrieve total comments for blog or single post.
The properties of the returned object contain the 'moderated', 'approved', and spam comments for either the entire blog or single post. Those properties contain the amount of comments that match the status. The 'total_comments' property contains the integer of total comments.
The comment stats are cached and then retrieved, if they already exist in the cache.
Since
2.5.0
Parameters
int $post_id Optional. Post ID.
Returns
object|array Comment stats.
Filter the comments count for a given post.
Since
2.7.0
Parameters
array $count An empty array.
int $post_id The post ID.
Definition at line 1060 of file wp-includes/comment.php.
References $count, $post_id, apply_filters(), get_comment_count(), object, wp_cache_get(), and wp_cache_set().
Referenced by _wp_ajax_delete_comment_response(), WP_Comments_List_Table\get_views(), wp_admin_bar_comments_menu(), wp_ajax_replyto_comment(), wp_dashboard_right_now(), and wp_xmlrpc_server\wp_getCommentCount().
wp_defer_comment_counting ($defer = null)
Whether to defer comment counting.
When setting $defer to true, all post comment counts will not be updated until $defer is set to false. When $defer is set to false, then all previously deferred updated post comment counts will then be automatically updated without having to call wp_update_comment_count() after.
Since
2.5.0 bool $_defer
Parameters
bool $defer
Returns
bool
Definition at line 2014 of file wp-includes/comment.php.
References null, and wp_update_comment_count().
Referenced by wp_delete_attachment(), wp_delete_post(), and wp_update_comment_count().
wp_delete_comment ($comment_id, $force_delete = false)
Trashes or deletes a comment.
The comment is moved to trash instead of permanently deleted unless trash is disabled, item is already in the trash, or $force_delete is true.
The post comment count will be updated if the comment was approved and has a post ID available.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | WP_Comment $comment_id Comment ID or WP_Comment object.
bool $force_delete Whether to bypass trash and force deletion. Default is false.
Returns
bool True on success, false on failure.
Fires immediately before a comment is deleted from the database.
Since
1.2.0
Parameters
int $comment_id The comment ID.
Fires immediately after a comment is deleted from the database.
Since
2.9.0
Parameters
int $comment_id The comment ID.
This action is documented in wp-includes/comment.php
Definition at line 1108 of file wp-includes/comment.php.
References $comment, $post_id, $wpdb, clean_comment_cache(), delete_metadata_by_mid(), do_action(), get_comment(), wp_get_comment_status(), wp_transition_comment_status(), wp_trash_comment(), and wp_update_comment_count().
Referenced by WP_Canonical_UnitTestCase\delete_shared_fixtures(), upgrade_430_fix_comments(), wp_ajax_delete_comment(), wp_delete_attachment(), wp_delete_post(), wp_xmlrpc_server\wp_deleteComment(), wp_scheduled_delete(), and wp_trash_comment().
wp_filter_comment ($commentdata)
Filters and sanitizes comment data.
Sets the comment data 'filtered' field to true when finished. This can be checked as to whether the comment should be filtered and to keep from filtering the same comment more than once.
Since
2.0.0
Parameters
array $commentdata Contains information on the comment.
Returns
array Parsed comment information.
Filter the comment author's user id before it is set.
The first time this filter is evaluated, 'user_ID' is checked (for back-compat), followed by the standard 'user_id' value.
Since
1.5.0
Parameters
int $user_ID The comment author's user ID.
This filter is documented in wp-includes/comment.php
Filter the comment author's browser user agent before it is set.
Since
1.5.0
Parameters
int $comment_agent The comment author's browser user agent.
This filter is documented in wp-includes/comment.php
Filter the comment content before it is set.
Since
1.5.0
Parameters
int $comment_content The comment content.
Filter the comment author's IP before it is set.
Since
1.5.0
Parameters
int $comment_author_ip The comment author's IP.
This filter is documented in wp-includes/comment.php
This filter is documented in wp-includes/comment.php
Definition at line 1589 of file wp-includes/comment.php.
References apply_filters(), and elseif.
Referenced by wp_new_comment(), and wp_update_comment().
wp_get_comment_column_max_length ($column)
Calculate the maximum character length of a column from the comments table.
Since
4.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $column Name of a column in the comments table.
Returns
int Maximum column character length.
Filters the calculated length for a given column of the comments table.
Since
4.5.0
Parameters
int $max_length Maximum column character length.
string $column Column name.
Definition at line 960 of file wp-includes/comment.php.
References $wpdb, apply_filters(), and elseif.
Referenced by wp_handle_comment_submission().
wp_get_comment_status ($comment_id)
The status of a comment by ID.
Since
1.0.0
Parameters
int | WP_Comment $comment_id Comment ID or WP_Comment object
Returns
false|string Status might be 'trash', 'approved', 'unapproved', 'spam'. False on failure.
Definition at line 1346 of file wp-includes/comment.php.
References $comment, elseif, get_comment(), and null.
Referenced by WP_Comments_List_Table\handle_row_actions(), WP_Comments_List_Table\single_row(), wp_ajax_delete_comment(), wp_ajax_dim_comment(), wp_delete_comment(), and wp_new_comment().
wp_get_current_commenter ()
Get current commenter's name, email, and URL.
Expects cookies content to already be sanitized. User of this function might wish to recheck the returned array for validity.
See also
sanitize_comment_cookies() Use to sanitize cookies
Since
2.0.4
Returns
array Comment author, email, url respectively.
Filter the current commenter's name, email, and URL.
Since
3.1.0
Parameters
array $comment_author_data { An array of current commenter variables.
string $comment_author The name of the author of the comment. Default empty. string $comment_author_email The email address of the $comment_author. Default empty. string $comment_author_url The URL address of the $comment_author. Default empty. }
Definition at line 1455 of file wp-includes/comment.php.
References $_COOKIE, and apply_filters().
Referenced by comment_form(), and comments_template().
wp_handle_comment_submission ($comment_data)
Handles the submission of a comment, usually posted to wp-comments-post.php via a comment form.
This function expects unslashed data, as opposed to functions such as wp_new_comment() which expect slashed data.
Since
4.4.0
Parameters
array $comment_data { Comment data.
string|int $comment_post_ID The ID of the post that relates to the comment. string $author The name of the comment author. string $email The comment author email address. string $url The comment author URL. string $comment The content of the comment. string|int $comment_parent The ID of this comment's parent, if any. Default 0. string $_wp_unfiltered_html_comment The nonce value for allowing unfiltered HTML. }
Returns
WP_Comment|WP_Error A WP_Comment object on success, a WP_Error object on failure.
Fires when a comment is attempted on a post that does not exist.
Since
1.5.0
Parameters
int $comment_post_ID Post ID.
Fires when a comment is attempted on a post that has comments closed.
Since
1.5.0
Parameters
int $comment_post_ID Post ID.
Fires when a comment is attempted on a trashed post.
Since
2.9.0
Parameters
int $comment_post_ID Post ID.
Fires when a comment is attempted on a post in draft mode.
Since
1.5.1
Parameters
int $comment_post_ID Post ID.
Fires when a comment is attempted on a password-protected post.
Since
2.9.0
Parameters
int $comment_post_ID Post ID.
Fires before a comment is posted.
Since
2.8.0
Parameters
int $comment_post_ID Post ID.
Definition at line 2666 of file wp-includes/comment.php.
References $post, $user, $user_ID, __, absint(), comments_open(), current_user_can(), do_action(), elseif, get_comment(), get_option(), get_post(), get_post_status(), get_post_status_object(), is_email(), kses_init_filters(), kses_remove_filters(), null, post_password_required(), wp_get_comment_column_max_length(), wp_new_comment(), and wp_slash().
wp_insert_comment ($commentdata)
Inserts a comment into the database.
Since
2.0.0
4.4.0 Introduced $comment_meta argument.
wpdb $wpdb WordPress database abstraction object.
Parameters
array $commentdata { Array of arguments for inserting a new comment.
string $comment_agent The HTTP user agent of the $comment_author when the comment was submitted. Default empty. int|string $comment_approved Whether the comment has been approved. Default 1. string $comment_author The name of the author of the comment. Default empty. string $comment_author_email The email address of the $comment_author. Default empty. string $comment_author_IP The IP address of the $comment_author. Default empty. string $comment_author_url The URL address of the $comment_author. Default empty. string $comment_content The content of the comment. Default empty. string $comment_date The date the comment was submitted. To set the date manually, $comment_date_gmt must also be specified. Default is the current time. string $comment_date_gmt The date the comment was submitted in the GMT timezone. Default is $comment_date in the site's GMT timezone. int $comment_karma The karma of the comment. Default 0. int $comment_parent ID of this comment's parent, if any. Default 0. int $comment_post_ID ID of the post that relates to the comment, if any. Default 0. string $comment_type Comment type. Default empty. array $comment_meta Optional. Array of key/value pairs to be stored in commentmeta for the new comment. int $user_id ID of the user who submitted the comment. Default 0. }
Returns
int|false The new comment's ID on success, false on failure.
Fires immediately after a comment is inserted into the database.
Since
2.8.0
Parameters
int $id The comment ID.
WP_Comment $comment Comment object.
Definition at line 1521 of file wp-includes/comment.php.
References $comment, $id, $user_id, $wpdb, add_comment_meta(), current_time(), do_action(), get_comment(), get_gmt_from_date(), if, wp_cache_set(), wp_unslash(), and wp_update_comment_count().
Referenced by WP_UnitTest_Factory_For_Comment\create_object(), and wp_new_comment().
wp_new_comment ($commentdata)
Adds a new comment to the database.
Filters new comment to ensure that the fields are sanitized and valid before inserting comment into database. Calls 'comment_post' action with comment ID and whether comment is approved by WordPress. Also has 'preprocess_comment' filter for processing the comment data before the function handles it.
We use REMOTE_ADDR here directly. If you are behind a proxy, you should ensure that it is properly set, such as in wp-config.php, for your environment. See https://core.trac.wordpress.org/ticket/9235
Since
1.5.0
4.3.0 'comment_agent' and 'comment_author_IP' can be set via $commentdata.
See also
wp_insert_comment() wpdb $wpdb WordPress database abstraction object.
Parameters
array $commentdata { Comment data.
string $comment_author The name of the comment author. string $comment_author_email The comment author email address. string $comment_author_url The comment author URL. string $comment_content The content of the comment. string $comment_date The date the comment was submitted. Default is the current time. string $comment_date_gmt The date the comment was submitted in the GMT timezone. Default is $comment_date in the GMT timezone. int $comment_parent The ID of this comment's parent, if any. Default 0. int $comment_post_ID The ID of the post that relates to the comment. int $user_id The ID of the user who submitted the comment. Default 0. int $user_ID Kept for backward-compatibility. Use $user_id instead. string $comment_agent Comment author user agent. Default is the value of 'HTTP_USER_AGENT' in the $_SERVER superglobal sent in the original request. string $comment_author_IP Comment author IP address in IPv4 format. Default is the value of 'REMOTE_ADDR' in the $_SERVER superglobal sent in the original request. }
Returns
int|false The ID of the comment on success, false on failure.
Filter a comment's data before it is sanitized and inserted into the database.
Since
1.5.0
Parameters
array $commentdata Comment data.
Fires immediately after a comment is inserted into the database.
Since
1.2.0
Parameters
int $comment_ID The comment ID.
int | string $comment_approved 1 if the comment is approved, 0 if not, 'spam' if spam.
Definition at line 1698 of file wp-includes/comment.php.
References $_SERVER, $field, $wpdb, absint(), apply_filters(), current_time(), do_action(), elseif, wp_allow_comment(), wp_filter_comment(), wp_get_comment_status(), and wp_insert_comment().
Referenced by wp_xmlrpc_server\pingback_ping(), wp_ajax_replyto_comment(), wp_handle_comment_submission(), and wp_xmlrpc_server\wp_newComment().
wp_new_comment_notify_moderator ($comment_ID)
Send a comment moderation notification to the comment moderator.
Since
4.4.0
Parameters
int $comment_ID ID of the comment.
Returns
bool True on success, false on failure.
This filter is documented in wp-includes/comment.php
Definition at line 1790 of file wp-includes/comment.php.
References $comment, apply_filters(), and get_comment().
wp_new_comment_notify_postauthor ($comment_ID)
Send a notification of a new comment to the post author.
Since
4.4.0
Uses the {
See also
'notify_post_author'} filter to determine whether the post author should be notified when a new comment is added, overriding site setting.
Parameters
int $comment_ID Comment ID.
Returns
bool True on success, false on failure.
Filter whether to send the post author new comment notification emails, overriding the site setting.
Since
4.4.0
Parameters
bool $maybe_notify Whether to notify the post author about the new comment.
int $comment_ID The ID of the comment for the notification.
Definition at line 1817 of file wp-includes/comment.php.
References $comment, apply_filters(), get_comment(), and get_option().
wp_set_comment_cookies ($comment, $user)
Sets the cookies used to store an unauthenticated commentator's identity.
Typically used to recall previous comments by this commentator that are still held in moderation.
Parameters
WP_Comment $comment Comment object.
object $user Comment author's object.
Since
3.4.0
Filter the lifetime of the comment cookie in seconds.
Since
2.8.0
Parameters
int $seconds Comment cookie lifetime. Default 30000000.
Definition at line 480 of file wp-includes/comment.php.
References $comment, $secure, $user, apply_filters(), COOKIE_DOMAIN, esc_url, and home_url().
wp_set_comment_status ($comment_id, $comment_status, $wp_error = false)
Sets the status of a comment.
The 'wp_set_comment_status' action is called after the comment is handled. If the comment status is not in the list, then false is returned.
Since
1.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | WP_Comment $comment_id Comment ID or WP_Comment object.
string $comment_status New comment status, either 'hold', 'approve', 'spam', or 'trash'.
bool $wp_error Whether to return a WP_Error object if there is a failure. Default is false.
Returns
bool|WP_Error True on success, false or WP_Error on failure.
Fires immediately before transitioning a comment's status from one to another in the database.
Since
1.5.0
Parameters
int $comment_id Comment ID.
string | bool $comment_status Current comment status. Possible values include 'hold', 'approve', 'spam', 'trash', or false.
Definition at line 1864 of file wp-includes/comment.php.
References $comment, $wpdb, __, add_action(), clean_comment_cache(), do_action(), get_comment(), wp_transition_comment_status(), and wp_update_comment_count().
Referenced by wp_ajax_dim_comment(), wp_ajax_replyto_comment(), wp_spam_comment(), wp_trash_comment(), wp_unspam_comment(), and wp_untrash_comment().
wp_spam_comment ($comment_id)
Marks a comment as Spam.
Since
2.9.0
Parameters
int | WP_Comment $comment_id Comment ID or WP_Comment object.
Returns
bool True on success, false on failure.
Fires immediately before a comment is marked as Spam.
Since
2.9.0
Parameters
int $comment_id The comment ID.
Fires immediately after a comment is marked as Spam.
Since
2.9.0
Parameters
int $comment_id The comment ID.
Definition at line 1260 of file wp-includes/comment.php.
References $comment, add_comment_meta(), delete_comment_meta(), do_action(), get_comment(), and wp_set_comment_status().
Referenced by wp_ajax_delete_comment().
wp_throttle_comment_flood ($block, $time_lastcomment, $time_newcomment)
Whether a comment should be blocked because of comment flood.
Since
2.1.0
Parameters
bool $block Whether plugin has already blocked comment.
int $time_lastcomment Timestamp for last comment.
int $time_newcomment Timestamp for new comment.
Returns
bool Whether comment should be blocked.
Definition at line 1651 of file wp-includes/comment.php.
wp_transition_comment_status ($new_status, $old_status, $comment)
Call hooks for when a comment status transition occurs.
Calls hooks for comment status transitions. If the new comment status is not the same as the previous comment status, then two hooks will be ran, the first is 'transition_comment_status' with new status, old status, and comment data. The next action called is 'comment_OLDSTATUS_to_NEWSTATUS' the NEWSTATUS is the $new_status parameter and the OLDSTATUS is $old_status parameter; it has the comment data.
The final action will run whether or not the comment statuses are the same. The action is named 'comment_NEWSTATUS_COMMENTTYPE', NEWSTATUS is from the $new_status parameter and COMMENTTYPE is comment_type comment data.
Since
2.7.0
Parameters
string $new_status New comment status.
string $old_status Previous comment status.
object $comment Comment data.
Fires when the comment status is in transition.
Since
2.7.0
Parameters
int | string $new_status The new comment status.
int | string $old_status The old comment status.
object $comment The comment data.
Fires when the comment status is in transition from one specific status to another.
The dynamic portions of the hook name, $old_status, and $new_status, refer to the old and new comment statuses, respectively.
Since
2.7.0
Parameters
WP_Comment $comment Comment object.
Fires when the status of a specific comment type is in transition.
The dynamic portions of the hook name, $new_status, and $comment->comment_type, refer to the new comment status, and the type of comment, respectively.
Typical comment types include an empty string (standard comment), 'pingback', or 'trackback'.
Since
2.7.0
Parameters
int $comment_ID The comment ID.
WP_Comment $comment Comment object.
Definition at line 1387 of file wp-includes/comment.php.
References $comment, and do_action().
Referenced by wp_delete_comment(), wp_set_comment_status(), and wp_update_comment().
wp_trash_comment ($comment_id)
Moves a comment to the Trash.
If trash is disabled, comment is permanently deleted.
Since
2.9.0
Parameters
int | WP_Comment $comment_id Comment ID or WP_Comment object.
Returns
bool True on success, false on failure.
Fires immediately before a comment is sent to the Trash.
Since
2.9.0
Parameters
int $comment_id The comment ID.
Fires immediately after a comment is sent to Trash.
Since
2.9.0
Parameters
int $comment_id The comment ID.
Definition at line 1172 of file wp-includes/comment.php.
References $comment, add_comment_meta(), delete_comment_meta(), do_action(), get_comment(), wp_delete_comment(), and wp_set_comment_status().
Referenced by wp_ajax_delete_comment(), and wp_delete_comment().
wp_unspam_comment ($comment_id)
Removes a comment from the Spam.
Since
2.9.0
Parameters
int | WP_Comment $comment_id Comment ID or WP_Comment object.
Returns
bool True on success, false on failure.
Fires immediately before a comment is unmarked as Spam.
Since
2.9.0
Parameters
int $comment_id The comment ID.
Fires immediately after a comment is unmarked as Spam.
Since
2.9.0
Parameters
int $comment_id The comment ID.
Definition at line 1302 of file wp-includes/comment.php.
References $comment, delete_comment_meta(), do_action(), get_comment(), get_comment_meta(), and wp_set_comment_status().
Referenced by wp_ajax_delete_comment().
wp_untrash_comment ($comment_id)
Removes a comment from the Trash.
Since
2.9.0
Parameters
int | WP_Comment $comment_id Comment ID or WP_Comment object.
Returns
bool True on success, false on failure.
Fires immediately before a comment is restored from the Trash.
Since
2.9.0
Parameters
int $comment_id The comment ID.
Fires immediately after a comment is restored from the Trash.
Since
2.9.0
Parameters
int $comment_id The comment ID.
Definition at line 1216 of file wp-includes/comment.php.
References $comment, delete_comment_meta(), do_action(), get_comment(), get_comment_meta(), and wp_set_comment_status().
Referenced by wp_ajax_delete_comment().
wp_update_comment ($commentarr)
Updates an existing comment in the database.
Filters the comment and makes sure certain fields are valid before updating.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $commentarr Contains information on the comment.
Returns
int Comment was updated if value is 1, or was not updated if value is 0.
Filter the comment content before it is updated in the database.
Since
1.5.0
Parameters
string $comment_content The comment data.
Fires immediately after a comment is updated in the database.
The hook also fires immediately before comment status transition hooks are fired.
Since
1.2.0
Parameters
int $comment_ID The comment ID.
Definition at line 1931 of file wp-includes/comment.php.
References $comment, $keys, $wpdb, apply_filters(), ARRAY_A, clean_comment_cache(), do_action(), elseif, get_comment(), get_gmt_from_date(), get_post(), wp_array_slice_assoc(), wp_filter_comment(), wp_slash(), wp_transition_comment_status(), wp_unslash(), and wp_update_comment_count().
Referenced by edit_comment(), WP_UnitTest_Factory_For_Comment\update_object(), and wp_xmlrpc_server\wp_editComment().
wp_update_comment_count ($post_id, $do_deferred = false)
Updates the comment count for post(s).
When $do_deferred is false (is by default) and the comments have been set to be deferred, the post_id will be added to a queue, which will be updated at a later date and only updated once per post ID.
If the comments have not be set up to be deferred, then the post will be updated. When $do_deferred is set to true, then all previous deferred post IDs will be updated along with the current $post_id.
Since
2.1.0
See also
wp_update_comment_count_now() For what could cause a false return value
array $_deferred
Parameters
int | null $post_id Post ID.
bool $do_deferred Optional. Whether to process previously deferred post comment counts. Default false.
Returns
bool|void True on success, false on failure or if post with ID does not exist.
Definition at line 2049 of file wp-includes/comment.php.
References $i, $post_id, elseif, wp_defer_comment_counting(), and wp_update_comment_count_now().
Referenced by wp_defer_comment_counting(), wp_delete_comment(), wp_insert_comment(), wp_set_comment_status(), and wp_update_comment().
wp_update_comment_count_now ($post_id)
Updates the comment count for the post.
Since
2.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Post ID
Returns
bool True on success, false on '0' $post_id or if post with ID does not exist.
Fires immediately after a post's comment count is updated in the database.
Since
2.3.0
Parameters
int $post_id Post ID.
int $new The new comment count.
int $old The old comment count.
This action is documented in wp-includes/post.php
Definition at line 2084 of file wp-includes/comment.php.
References $post, $post_id, $wpdb, clean_post_cache(), do_action(), get_post(), and wp_cache_delete().
Referenced by wp_update_comment_count().
xmlrpc_pingback_error ($ixr_error)
Default filter attached to xmlrpc_pingback_error.
Returns a generic pingback error code unless the error code is 48, which reports that the pingback is already registered.
Since
3.5.1 IXR_Error $ixr_error IXR_Error
Definition at line 2490 of file wp-includes/comment.php.