GravityView: bookmark.php File Reference
wp-includes/bookmark.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
clean_bookmark_cache ($bookmark_id)
Deletes the bookmark cache.
get_bookmark ($bookmark, $output=OBJECT, $filter= 'raw')
Retrieve Bookmark data.
get_bookmark_field ($field, $bookmark, $context= 'display')
Retrieve single bookmark data item or field.
get_bookmarks ($args= '')
Retrieves the list of bookmarks.
sanitize_bookmark ($bookmark, $context= 'display')
Sanitizes all bookmark fields.
sanitize_bookmark_field ($field, $value, $bookmark_id, $context)
Sanitizes a bookmark field.
Function Documentation
clean_bookmark_cache ($bookmark_id)
Deletes the bookmark cache.
Since
2.7.0
Parameters
int $bookmark_id Bookmark ID.
Definition at line 413 of file wp-includes/bookmark.php.
References clean_object_term_cache(), and wp_cache_delete().
Referenced by wp_delete_link(), wp_delete_user(), wp_insert_link(), and wp_set_link_cats().
get_bookmark ($bookmark, $output = OBJECT, $filter = 'raw')
Retrieve Bookmark data.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | stdClass $bookmark
string $output Optional. Either OBJECT, ARRAY_N, or ARRAY_A constant
string $filter Optional, default is 'raw'.
Returns
array|object|null Type returned depends on $output value.
Definition at line 21 of file wp-includes/bookmark.php.
References $GLOBALS, $output, $wpdb, ARRAY_A, ARRAY_N, elseif, null, OBJECT, sanitize_bookmark(), wp_cache_add(), wp_cache_get(), and wp_get_object_terms().
Referenced by edit_bookmark_link(), get_bookmark_field(), get_edit_bookmark_link(), get_link(), get_link_to_edit(), wp_ajax_delete_link(), and wp_update_link().
get_bookmark_field ($field, $bookmark, $context = 'display')
Retrieve single bookmark data item or field.
Since
2.3.0
Parameters
string $field The name of the data field to return
int $bookmark The bookmark ID to get field
string $context Optional. The context of how the field will be used.
Returns
string|WP_Error
Definition at line 70 of file wp-includes/bookmark.php.
References $field, get_bookmark(), is_wp_error(), and sanitize_bookmark_field().
get_bookmarks ($args = '')
Retrieves the list of bookmarks.
Attempts to retrieve from the cache first based on MD5 hash of arguments. If that fails, then the query will be built from the arguments and executed. The results will be stored to the cache.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string | array $args { Optional. String or array of arguments to retrieve bookmarks.
string $orderby How to order the links by. Accepts post fields. Default 'name'. string $order Whether to order bookmarks in ascending or descending order. Accepts 'ASC' (ascending) or 'DESC' (descending). Default 'ASC'. int $limit Amount of bookmarks to display. Accepts 1+ or -1 for all. Default -1. string $category Comma-separated list of category ids to include links from. Default empty. string $category_name Category to retrieve links for by name. Default empty. int|bool $hide_invisible Whether to show or hide links marked as 'invisible'. Accepts 1|true or 0|false. Default 1|true. int|bool $show_updated Whether to display the time the bookmark was last updated. Accepts 1|true or 0|false. Default 0|false. string $include Comma-separated list of bookmark IDs to include. Default empty. string $exclude Comma-separated list of bookmark IDs to exclude. Default empty. }
Returns
array List of bookmark row objects.
Filter the returned list of bookmarks.
The first time the hook is evaluated in this file, it returns the cached bookmarks list. The second evaluation returns a cached bookmarks list if the link category is passed but does not exist. The third evaluation returns the full cached results.
Since
2.1.0
See also
get_bookmarks()
Parameters
array $bookmarks List of the cached bookmarks.
array $r An array of bookmark query arguments.
This filter is documented in wp-includes/bookmark.php
This filter is documented in wp-includes/bookmark.php
Definition at line 117 of file wp-includes/bookmark.php.
References $bookmarks, $keys, $wpdb, apply_filters(), elseif, get_term_by(), wp_cache_get(), wp_cache_set(), and wp_parse_args().
Referenced by get_linkobjects(), get_links(), WP_Links_List_Table\prepare_items(), and wp_list_bookmarks().
sanitize_bookmark ($bookmark, $context = 'display')
Sanitizes all bookmark fields.
Since
2.3.0
Parameters
object | array $bookmark Bookmark row
string $context Optional, default is 'display'. How to filter the fields
Returns
object|array Same type as $bookmark but with fields sanitized.
Definition at line 305 of file wp-includes/bookmark.php.
References $field, and sanitize_bookmark_field().
Referenced by WP_Links_List_Table\display_rows(), get_bookmark(), and wp_insert_link().
sanitize_bookmark_field ($field, $value, $bookmark_id, $context)
Sanitizes a bookmark field.
Sanitizes the bookmark fields based on what the field name is. If the field has a strict value set, then it will be tested for that, else a more generic filtering is applied. After the more strict filter is applied, if the $context is 'raw' then the value is immediately return.
Hooks exist for the more generic cases. With the 'edit' context, the 'edit_$field' filter will be called and passed the $value and $bookmark_id respectively. With the 'db' context, the 'pre_$field' filter is called and passed the value. The 'display' context is the final context and has the $field has the filter name and is passed the $value, $bookmark_id, and $context respectively.
Since
2.3.0
Parameters
string $field The bookmark field
mixed $value The bookmark field value
int $bookmark_id Bookmark ID
string $context How to filter the field value. Either 'raw', 'edit', 'attribute', 'js', 'db', or 'display'
Returns
mixed The filtered value
This filter is documented in wp-includes/post.php
This filter is documented in wp-includes/post.php
This filter is documented in wp-includes/post.php
Definition at line 355 of file wp-includes/bookmark.php.
References $field, $value, apply_filters(), elseif, esc_attr(), esc_html, and esc_js().
Referenced by _walk_bookmarks(), get_bookmark_field(), get_linkrating(), get_links(), and sanitize_bookmark().