GravityView: taxonomy.php File Reference
wp-includes/taxonomy.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_get_term_children ($term_id, $terms, $taxonomy, &$ancestors=array())
Get the subset of $terms that are descendants of $term_id.
_get_term_hierarchy ($taxonomy)
Retrieves children of taxonomy as Term IDs.
_pad_term_counts (&$terms, $taxonomy)
Add count of children to parent count.
_split_shared_term ($term_id, $term_taxonomy_id, $record=true)
Create a new term for a term_taxonomy item that currently shares its term with another term_taxonomy.
_update_generic_term_count ($terms, $taxonomy)
Will update term count based on number of objects.
_update_post_term_count ($terms, $taxonomy)
Will update term count based on object types of the current taxonomy.
_wp_batch_split_terms ()
Splits a batch of shared taxonomy terms.
_wp_check_for_scheduled_split_terms ()
In order to avoid the _wp_batch_split_terms() job being accidentally removed, check that it's still scheduled while we haven't finished splitting terms.
_wp_check_split_default_terms ($term_id, $new_term_id, $term_taxonomy_id, $taxonomy)
Check default categories when a term gets split to see if any of them need to be updated.
_wp_check_split_nav_menu_terms ($term_id, $new_term_id, $term_taxonomy_id, $taxonomy)
If the term being split is a nav_menu, change associations.
_wp_check_split_terms_in_menus ($term_id, $new_term_id, $term_taxonomy_id, $taxonomy)
Check menu items when a term gets split to see if any of them need to be updated.
add_term_meta ($term_id, $meta_key, $meta_value, $unique=false)
Adds metadata to a term.
clean_object_term_cache ($object_ids, $object_type)
Removes the taxonomy relationship to terms from the cache.
clean_term_cache ($ids, $taxonomy= '', $clean_taxonomy=true)
Will remove all of the term ids from the cache.
create_initial_taxonomies ()
Creates the initial taxonomies.
delete_term_meta ($term_id, $meta_key, $meta_value= '')
Removes metadata matching criteria from a term.
get_ancestors ($object_id=0, $object_type= '', $resource_type= '')
Get an array of ancestor IDs for a given object.
get_object_taxonomies ($object, $output= 'names')
Return all of the taxonomy names that are of $object_type.
get_object_term_cache ($id, $taxonomy)
Retrieves the taxonomy relationship to the term object id.
get_objects_in_term ($term_ids, $taxonomies, $args=array())
Retrieve object_ids of valid taxonomy and term.
get_post_taxonomies ($post=0)
Retrieve all taxonomies of a post with just the names.
get_tax_sql ($tax_query, $primary_table, $primary_id_column)
Given a taxonomy query, generates SQL to be appended to a main query.
get_taxonomies ($args=array(), $output= 'names', $operator= 'and')
Retrieves a list of registered taxonomy names or objects.
get_taxonomy ($taxonomy)
Retrieves the taxonomy object of $taxonomy.
get_taxonomy_labels ($tax)
Builds an object with all taxonomy labels out of a taxonomy object.
get_term ($term, $taxonomy= '', $output=OBJECT, $filter= 'raw')
Get all Term data from database by Term ID.
get_term_by ($field, $value, $taxonomy= '', $output=OBJECT, $filter= 'raw')
Get all Term data from database by Term field and data.
get_term_children ($term_id, $taxonomy)
Merge all term children into a single array of their IDs.
get_term_field ($field, $term, $taxonomy= '', $context= 'display')
Get sanitized Term field.
get_term_link ($term, $taxonomy= '')
Generate a permalink for a taxonomy term archive.
get_term_meta ($term_id, $key= '', $single=false)
Retrieves metadata for a term.
get_term_to_edit ($id, $taxonomy)
Sanitizes Term for editing.
get_terms ($taxonomies, $args= '')
Retrieve the terms in a given taxonomy or list of taxonomies.
get_the_taxonomies ($post=0, $args=array())
Retrieve all taxonomies associated with a post.
is_object_in_taxonomy ($object_type, $taxonomy)
Determine if the given object type is associated with the given taxonomy.
is_object_in_term ($object_id, $taxonomy, $terms=null)
Determine if the given object is associated with any of the given terms.
is_taxonomy_hierarchical ($taxonomy)
Whether the taxonomy object is hierarchical.
register_taxonomy ($taxonomy, $object_type, $args=array())
Creates or modifies a taxonomy object.
register_taxonomy_for_object_type ($taxonomy, $object_type)
Add an already registered taxonomy to an object type.
sanitize_term ($term, $taxonomy, $context= 'display')
Sanitize Term all fields.
sanitize_term_field ($field, $value, $term_id, $taxonomy, $context)
Cleanse the field value in the term based on the context.
taxonomy_exists ($taxonomy)
Checks that the taxonomy name exists.
term_exists ($term, $taxonomy= '', $parent=null)
Check if Term exists.
term_is_ancestor_of ($term1, $term2, $taxonomy)
Check if a term is an ancestor of another term.
the_taxonomies ($args=array())
Display the taxonomies of a post with available options.
unregister_taxonomy ($taxonomy)
Unregister a taxonomy.
unregister_taxonomy_for_object_type ($taxonomy, $object_type)
Remove an already registered taxonomy from an object type.
update_object_term_cache ($object_ids, $object_type)
Updates the cache for the given term object ID(s).
update_term_cache ($terms, $taxonomy= '')
Updates Terms to Taxonomy in cache.
update_term_meta ($term_id, $meta_key, $meta_value, $prev_value= '')
Updates term metadata.
update_termmeta_cache ($term_ids)
Updates metadata cache for list of term IDs.
wp_add_object_terms ($object_id, $terms, $taxonomy)
Add term(s) associated with a given object.
wp_check_term_hierarchy_for_loops ($parent, $term_id, $taxonomy)
Checks the given subset of the term hierarchy for hierarchy loops.
wp_count_terms ($taxonomy, $args=array())
Count how many terms are in Taxonomy.
wp_defer_term_counting ($defer=null)
Enable or disable term counting.
wp_delete_category ($cat_ID)
Deletes one existing category.
wp_delete_object_term_relationships ($object_id, $taxonomies)
Will unlink the object from the taxonomy or taxonomies.
wp_delete_term ($term, $taxonomy, $args=array())
Removes a term from the database.
wp_get_object_terms ($object_ids, $taxonomies, $args=array())
Retrieves the terms associated with the given object(s), in the supplied taxonomies.
wp_get_split_term ($old_term_id, $taxonomy)
Get the new term ID corresponding to a previously split term.
wp_get_split_terms ($old_term_id)
Get data about terms that previously shared a single term_id, but have since been split.
wp_get_term_taxonomy_parent_id ($term_id, $taxonomy)
Returns the term's parent's term_ID.
wp_insert_term ($term, $taxonomy, $args=array())
Add a new term to the database.
wp_remove_object_terms ($object_id, $terms, $taxonomy)
Remove term(s) associated with a given object.
wp_set_object_terms ($object_id, $terms, $taxonomy, $append=false)
Create Term and Taxonomy Relationships.
wp_term_is_shared ($term_id)
Determine whether a term is shared between multiple taxonomies.
wp_unique_term_slug ($slug, $term)
Will make slug unique, if it isn't already.
wp_update_term ($term_id, $taxonomy, $args=array())
Update term based on arguments provided.
wp_update_term_count ($terms, $taxonomy, $do_deferred=false)
Updates the amount of terms in taxonomy.
wp_update_term_count_now ($terms, $taxonomy)
Perform term count update immediately.
Function Documentation
_get_term_children ($term_id, $terms, $taxonomy, & $ancestors = array())
Get the subset of $terms that are descendants of $term_id.
If $terms is an array of objects, then _get_term_children() returns an array of objects. If $terms is an array of IDs, then _get_term_children() returns an array of IDs.
private
Since
2.3.0
Parameters
int $term_id The ancestor term: all returned terms should be descendants of $term_id.
array $terms The set of terms - either an array of term objects or term IDs - from which those that are descendants of $term_id will be chosen.
string $taxonomy The taxonomy which determines the hierarchy of the terms.
array $ancestors Optional. Term ancestors that have already been identified. Passed by reference, to keep track of found terms when recursing the hierarchy. The array of located ancestors is used to prevent infinite recursion loops. For performance, term_ids are used as array keys, with 1 as value. Default empty array.
Returns
array|WP_Error The subset of $terms that are descendants of $term_id.
Definition at line 3783 of file wp-includes/taxonomy.php.
References _get_term_hierarchy(), get_term(), and is_wp_error().
Referenced by get_terms().
_get_term_hierarchy ($taxonomy)
Retrieves children of taxonomy as Term IDs.
Since
2.3.0
Parameters
string $taxonomy Taxonomy name.
Returns
array Empty if $taxonomy isn't hierarchical or returns children as Term IDs.
Definition at line 3746 of file wp-includes/taxonomy.php.
References get_option(), get_terms(), is_taxonomy_hierarchical(), and update_option().
Referenced by _get_term_children(), _pad_term_counts(), _wp_batch_split_terms(), _wp_menu_item_classes_by_context(), clean_term_cache(), WP_Terms_List_Table\display_rows_or_placeholder(), get_term_children(), and get_terms().
_pad_term_counts (& $terms, $taxonomy)
Add count of children to parent count.
Recalculates term counts by including items from child terms. Assumes all relevant children are already in the $terms argument.
private
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $terms List of term objects, passed by reference.
string $taxonomy Term context.
Definition at line 3846 of file wp-includes/taxonomy.php.
References $id, $wpdb, _get_term_hierarchy(), esc_sql(), get_taxonomy(), and is_taxonomy_hierarchical().
Referenced by get_terms().
_split_shared_term ($term_id, $term_taxonomy_id, $record = true)
Create a new term for a term_taxonomy item that currently shares its term with another term_taxonomy.
Since
4.2.0
4.3.0 Introduced $record parameter. Also, $term_id and $term_taxonomy_id can now accept objects.
wpdb $wpdb WordPress database abstraction object.
Parameters
int | object $term_id ID of the shared term, or the shared term object.
int | object $term_taxonomy_id ID of the term_taxonomy item to receive a new term, or the term_taxonomy object (corresponding to a row from the term_taxonomy table).
bool $record Whether to record data about the split term in the options table. The recording process has the potential to be resource-intensive, so during batch operations it can be beneficial to skip inline recording and do it just once, after the batch is processed. Only set this to false if you know what you are doing. Default: true.
Returns
int|WP_Error When the current term does not need to be split (or cannot be split on the current database schema), $term_id is returned. When the term is successfully split, the new term_id is returned. A WP_Error is returned for miscellaneous errors.
Fires after a previously shared taxonomy term is split into two separate terms.
Since
4.2.0
Parameters
int $term_id ID of the formerly shared term.
int $new_term_id ID of the new term created for the $term_taxonomy_id.
int $term_taxonomy_id ID for the term_taxonomy row affected by the split.
string $taxonomy Taxonomy for the split term.
Definition at line 4005 of file wp-includes/taxonomy.php.
References $wpdb, __, clean_term_cache(), do_action(), get_option(), and update_option().
Referenced by _wp_batch_split_terms(), and wp_update_term().
_update_generic_term_count ($terms, $taxonomy)
Will update term count based on number of objects.
Default callback for the 'link_category' taxonomy.
Since
3.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $terms List of term taxonomy IDs.
object $taxonomy Current taxonomy object of terms.
This action is documented in wp-includes/taxonomy.php
This action is documented in wp-includes/taxonomy.php
Definition at line 3967 of file wp-includes/taxonomy.php.
References $count, $wpdb, and do_action().
Referenced by wp_update_term_count_now().
_update_post_term_count ($terms, $taxonomy)
Will update term count based on object types of the current taxonomy.
Private function for the default callback for post_tag and category taxonomies.
private
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
array $terms List of Term taxonomy IDs.
object $taxonomy Current taxonomy object of terms.
This action is documented in wp-includes/taxonomy.php
This action is documented in wp-includes/taxonomy.php
Definition at line 3918 of file wp-includes/taxonomy.php.
References $count, $wpdb, do_action(), esc_sql(), and foreach.
Referenced by wp_update_term_count_now().
_wp_batch_split_terms ()
Splits a batch of shared taxonomy terms.
Since
4.3.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 4129 of file wp-includes/taxonomy.php.
References $tax, $wpdb, _get_term_hierarchy(), _split_shared_term(), delete_option(), get_option(), update_option(), and wp_schedule_single_event().
_wp_check_for_scheduled_split_terms ()
In order to avoid the _wp_batch_split_terms() job being accidentally removed, check that it's still scheduled while we haven't finished splitting terms.
Since
4.3.0
Definition at line 4224 of file wp-includes/taxonomy.php.
References get_option(), wp_next_scheduled(), and wp_schedule_single_event().
_wp_check_split_default_terms ($term_id, $new_term_id, $term_taxonomy_id, $taxonomy)
Check default categories when a term gets split to see if any of them need to be updated.
Since
4.2.0
Parameters
int $term_id ID of the formerly shared term.
int $new_term_id ID of the new term created for the $term_taxonomy_id.
int $term_taxonomy_id ID for the term_taxonomy row affected by the split.
string $taxonomy Taxonomy for the split term.
Definition at line 4241 of file wp-includes/taxonomy.php.
References $option, get_option(), and update_option().
_wp_check_split_nav_menu_terms ($term_id, $new_term_id, $term_taxonomy_id, $taxonomy)
If the term being split is a nav_menu, change associations.
Since
4.3.0
Parameters
int $term_id ID of the formerly shared term.
int $new_term_id ID of the new term created for the $term_taxonomy_id.
int $term_taxonomy_id ID for the term_taxonomy row affected by the split.
string $taxonomy Taxonomy for the split term.
Definition at line 4298 of file wp-includes/taxonomy.php.
References $location, $locations, get_nav_menu_locations(), and set_theme_mod().
_wp_check_split_terms_in_menus ($term_id, $new_term_id, $term_taxonomy_id, $taxonomy)
Check menu items when a term gets split to see if any of them need to be updated.
Since
4.2.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $term_id ID of the formerly shared term.
int $new_term_id ID of the new term created for the $term_taxonomy_id.
int $term_taxonomy_id ID for the term_taxonomy row affected by the split.
string $taxonomy Taxonomy for the split term.
Definition at line 4266 of file wp-includes/taxonomy.php.
References $post_id, $wpdb, and update_post_meta().
add_term_meta ($term_id, $meta_key, $meta_value, $unique = false)
Adds metadata to a term.
Since
4.4.0
Parameters
int $term_id Term ID.
string $meta_key Metadata name.
mixed $meta_value Metadata value.
bool $unique Optional. Whether to bail if an entry with the same key is found for the term. Default false.
Returns
int|WP_Error|bool Meta ID on success. WP_Error when term_id is ambiguous between taxonomies. False on failure.
Definition at line 1633 of file wp-includes/taxonomy.php.
References __, add_metadata(), get_option(), wp_cache_set(), and wp_term_is_shared().
clean_object_term_cache ($object_ids, $object_type)
Removes the taxonomy relationship to terms from the cache.
Will remove the entire taxonomy relationship containing term $object_id. The term IDs have to exist within the taxonomy $object_type for the deletion to take place.
Since
2.3.0
bool $_wp_suspend_cache_invalidation
See also
get_object_taxonomies() for more on $object_type.
Parameters
int | array $object_ids Single or list of term object ID(s).
array | string $object_type The taxonomy object type.
Fires after the object term cache has been cleaned.
Since
2.5.0
Parameters
array $object_ids An array of object IDs.
string $objet_type Object type.
Definition at line 3534 of file wp-includes/taxonomy.php.
References $id, do_action(), get_object_taxonomies(), and wp_cache_delete().
Referenced by clean_attachment_cache(), clean_bookmark_cache(), clean_post_cache(), wp_delete_term(), and wp_update_term().
clean_term_cache ($ids, $taxonomy = '', $clean_taxonomy = true)
Will remove all of the term ids from the cache.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object. bool $_wp_suspend_cache_invalidation
Parameters
int | array $ids Single or list of Term IDs.
string $taxonomy Optional. Can be empty and will assume tt_ids, else will use for context. Default empty.
bool $clean_taxonomy Optional. Whether to clean taxonomy wide caches (true), or just individual term object caches (false). Default true.
Fires once after each taxonomy's term cache has been cleaned.
Since
2.5.0
Parameters
array $ids An array of term IDs.
string $taxonomy Taxonomy slug.
Definition at line 3577 of file wp-includes/taxonomy.php.
References $id, $wpdb, _get_term_hierarchy(), delete_option(), do_action(), wp_cache_delete(), and wp_cache_set().
Referenced by _split_shared_term(), clean_category_cache(), global_terms(), wp_delete_term(), wp_insert_term(), wp_update_term(), and wp_update_term_count_now().
create_initial_taxonomies ()
Creates the initial taxonomies.
This function fires twice: in wp-settings.php before plugins are loaded (for backwards compatibility reasons), and again on the {
See also
'init'} action. We must avoid registering rewrite rules before the {
'init'} action.
Since
2.8.0
WP_Rewrite $wp_rewrite The WordPress rewrite class.
Filter the post formats rewrite base.
Since
3.1.0
Parameters
string $context Context of the rewrite base. Default 'type'.
Definition at line 24 of file wp-includes/taxonomy.php.
References $wp_rewrite, __, _x, apply_filters(), current_theme_supports(), did_action(), EP_CATEGORIES, EP_TAGS, get_option(), null, and register_taxonomy().
Referenced by WP_UnitTestCase\reset_taxonomies(), and WP_Canonical_UnitTestCase\setUp().
delete_term_meta ($term_id, $meta_key, $meta_value = '')
Removes metadata matching criteria from a term.
Since
4.4.0
Parameters
int $term_id Term ID.
string $meta_key Metadata name.
mixed $meta_value Optional. Metadata value. If provided, rows will only be removed that match the value.
Returns
bool True on success, false on failure.
Definition at line 1663 of file wp-includes/taxonomy.php.
References delete_metadata(), get_option(), and wp_cache_set().
get_ancestors ($object_id = 0, $object_type = '', $resource_type = '')
Get an array of ancestor IDs for a given object.
Since
3.1.0
4.1.0 Introduced the $resource_type argument.
Parameters
int $object_id Optional. The ID of the object. Default 0.
string $object_type Optional. The type of object for which we'll be retrieving ancestors. Accepts a post type or a taxonomy name. Default empty.
string $resource_type Optional. Type of resource $object_type is. Accepts 'post_type' or 'taxonomy'. Default empty.
Returns
array An array of ancestors from lowest to highest in the hierarchy.
This filter is documented in wp-includes/taxonomy.php
Filter a given object's ancestors.
Since
3.1.0
4.1.1 Introduced the $resource_type parameter.
Parameters
array $ancestors An array of object ancestors.
int $object_id Object ID.
string $object_type Type of object.
string $resource_type Type of resource $object_type is.
Definition at line 4675 of file wp-includes/taxonomy.php.
References apply_filters(), elseif, get_post_ancestors(), get_term(), is_taxonomy_hierarchical(), is_wp_error(), and post_type_exists().
Referenced by get_term_link(), and wp_ajax_add_tag().
get_object_taxonomies ($object, $output = 'names')
Return all of the taxonomy names that are of $object_type.
It appears that this function can be used to find all of the names inside of $wp_taxonomies global variable.
`<?php $taxonomies = get_object_taxonomies('post'); ?>Should result inArray('category', 'post_tag')`
Since
2.3.0
array $wp_taxonomies The registered taxonomies.
Parameters
array | string | WP_Post $object Name of the type of taxonomy object, or an object (row from posts)
string $output Optional. The type of output to return in the array. Accepts either taxonomy 'names' or 'objects'. Default 'names'.
Returns
array The names of all taxonomy of $object_type.
Definition at line 176 of file wp-includes/taxonomy.php.
References $output, and get_attachment_taxonomies().
Referenced by wp_xmlrpc_server\_insert_post(), wp_xmlrpc_server\_prepare_post(), wp_xmlrpc_server\_prepare_post_type(), _update_term_count_on_transition_post_status(), _wp_menu_item_classes_by_context(), bulk_edit_posts(), clean_object_term_cache(), export_wp(), get_attachment_taxonomies(), WP_Posts_List_Table\get_columns(), get_inline_data(), get_post_taxonomies(), WP_Query\get_posts(), get_the_taxonomies(), WP_Posts_List_Table\inline_edit(), is_object_in_taxonomy(), WP_Query\lazyload_term_meta(), update_object_term_cache(), wp_delete_attachment(), and wp_delete_post().
get_object_term_cache ($id, $taxonomy)
Retrieves the taxonomy relationship to the term object id.
Since
2.3.0
Parameters
int $id Term object ID.
string $taxonomy Taxonomy name.
Returns
bool|mixed Empty array if $terms found, but not $taxonomy. False if nothing is in cache for $taxonomy and $id.
Definition at line 3642 of file wp-includes/taxonomy.php.
References $id, and wp_cache_get().
Referenced by get_attachment_fields_to_edit(), get_compat_media_markup(), get_inline_data(), get_terms_to_edit(), get_the_taxonomies(), get_the_terms(), is_object_in_term(), and WP_Query\lazyload_term_meta().
get_objects_in_term ($term_ids, $taxonomies, $args = array())
Retrieve object_ids of valid taxonomy and term.
The strings of $taxonomies must exist before this function will continue. On failure of finding a valid taxonomy, it will return an WP_Error class, kind of like Exceptions in PHP 5, except you can't catch them. Even so, you can still test for the WP_Error class and get the error message.
The $terms aren't checked the same as $taxonomies, but still need to exist for $object_ids to be returned.
It is possible to change the order that object_ids is returned by either using PHP sort family functions or using the database by using $args with either ASC or DESC array. The value should be in the key named 'order'.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | array $term_ids Term id or array of term ids of terms that will be used.
string | array $taxonomies String of taxonomy name or Array of string values of taxonomy names.
array | string $args Change the order of the object_ids, either ASC or DESC.
Returns
WP_Error|array If the taxonomy does not exist, then WP_Error will be returned. On success. the array can be empty meaning that there are no $object_ids found or it will return the $object_ids found.
Definition at line 713 of file wp-includes/taxonomy.php.
References $wpdb, __, taxonomy_exists(), and wp_parse_args().
Referenced by wp_delete_nav_menu(), and wp_get_nav_menu_items().
get_post_taxonomies ($post = 0)
Retrieve all taxonomies of a post with just the names.
Since
2.5.0
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
Returns
array
Definition at line 4580 of file wp-includes/taxonomy.php.
References $post, get_object_taxonomies(), and get_post().
get_tax_sql ($tax_query, $primary_table, $primary_id_column)
Given a taxonomy query, generates SQL to be appended to a main query.
Since
3.1.0
See also
WP_Tax_Query
Parameters
array $tax_query A compact tax query
string $primary_table
string $primary_id_column
Returns
array
Definition at line 758 of file wp-includes/taxonomy.php.
get_taxonomies ($args = array(), $output = 'names', $operator = 'and')
Retrieves a list of registered taxonomy names or objects.
Since
3.0.0
array $wp_taxonomies The registered taxonomies.
Parameters
array $args Optional. An array of key => value arguments to match against the taxonomy objects. Default empty array.
string $output Optional. The type of output to return in the array. Accepts either taxonomy 'names' or 'objects'. Default 'names'.
string $operator Optional. The logical operation to perform. Accepts 'and' or 'or'. 'or' means only one element from the array needs to match; 'and' means all elements must match. Default 'and'.
Returns
array A list of taxonomy names or objects.
Definition at line 150 of file wp-includes/taxonomy.php.
References $field, $output, and wp_filter_object_list().
Referenced by WP_Customize_Nav_Menus\available_item_types(), export_wp(), WP_Widget_Tag_Cloud\form(), get_post_class(), get_taxonomies_for_attachments(), WP\parse_request(), WP_Query\parse_tax_query(), WP_UnitTestCase\reset_taxonomies(), WP_Customize_Nav_Menus\search_available_items_query(), set_screen_options(), upgrade_350(), wp_ajax_menu_get_metabox(), wp_xmlrpc_server\wp_getTaxonomies(), and wp_nav_menu_taxonomy_meta_boxes().
get_taxonomy ($taxonomy)
Retrieves the taxonomy object of $taxonomy.
The get_taxonomy function will first check that the parameter string given is a taxonomy object and if it is, it will return it.
Since
2.3.0
array $wp_taxonomies The registered taxonomies.
Parameters
string $taxonomy Name of taxonomy object to return.
Returns
object|false The Taxonomy Object or false if $taxonomy doesn't exist.
Definition at line 213 of file wp-includes/taxonomy.php.
References taxonomy_exists().
Referenced by WP_Terms_List_Table\__construct(), _pad_term_counts(), _post_format_request(), _wp_ajax_add_hierarchical_term(), WP_Press_This\add_category(), WP_Terms_List_Table\ajax_user_can(), bulk_edit_posts(), WP_Press_This\categories_html(), WP_Terms_List_Table\column_cb(), WP_Media_List_Table\column_default(), WP_Posts_List_Table\column_default(), WP_Terms_List_Table\column_posts(), edit_term_link(), get_attachment_fields_to_edit(), WP_Media_List_Table\get_columns(), WP_Posts_List_Table\get_columns(), get_compat_media_markup(), get_edit_term_link(), get_inline_data(), get_term_feed_link(), get_term_link(), get_the_archive_title(), get_the_taxonomies(), WP_Terms_List_Table\handle_row_actions(), WP_Terms_List_Table\inline_edit(), WP_Posts_List_Table\inline_edit(), is_taxonomy_hierarchical(), WP_Customize_Nav_Menus\load_available_items_query(), WP_Terms_List_Table\no_items(), post_categories_meta_box(), post_tags_meta_box(), redirect_canonical(), WP_Customize_Nav_Menus\search_available_items_query(), WP_Press_This\tags_html(), unregister_taxonomy(), WP_Customize_Nav_Menu_Item_Setting\value_as_wp_post_nav_menu_item(), WP_Widget_Tag_Cloud\widget(), wp_admin_bar_edit_menu(), wp_ajax_add_tag(), wp_ajax_ajax_tag_search(), wp_ajax_delete_tag(), wp_ajax_get_tagcloud(), wp_ajax_inline_save(), wp_ajax_inline_save_tax(), wp_delete_term(), wp_xmlrpc_server\wp_deleteTerm(), wp_xmlrpc_server\wp_editTerm(), wp_get_object_terms(), wp_xmlrpc_server\wp_getTaxonomy(), wp_xmlrpc_server\wp_getTerm(), wp_xmlrpc_server\wp_getTerms(), wp_insert_post(), wp_list_categories(), wp_xmlrpc_server\wp_newTerm(), wp_popular_terms_checklist(), wp_set_object_terms(), wp_setup_nav_menu_item(), wp_terms_checklist(), wp_title(), wp_update_term(), and wp_update_term_count_now().
get_taxonomy_labels ($tax)
Builds an object with all taxonomy labels out of a taxonomy object.
Accepted keys of the label array in the taxonomy object:
name - general name for the taxonomy, usually plural. The same as and overridden by $tax->label. Default is Tags/Categories
singular_name - name for one object of this taxonomy. Default is Tag/Category
search_items - Default is Search Tags/Search Categories
popular_items - This string isn't used on hierarchical taxonomies. Default is Popular Tags
all_items - Default is All Tags/All Categories
parent_item - This string isn't used on non-hierarchical taxonomies. In hierarchical ones the default is Parent Category
parent_item_colon - The same as parent_item, but with colon : in the end
edit_item - Default is Edit Tag/Edit Category
view_item - Default is View Tag/View Category
update_item - Default is Update Tag/Update Category
add_new_item - Default is Add New Tag/Add New Category
new_item_name - Default is New Tag Name/New Category Name
separate_items_with_commas - This string isn't used on hierarchical taxonomies. Default is "Separate tags with commas", used in the meta box.
add_or_remove_items - This string isn't used on hierarchical taxonomies. Default is "Add or remove tags", used in the meta box when JavaScript is disabled.
choose_from_most_used - This string isn't used on hierarchical taxonomies. Default is "Choose from the most used tags", used in the meta box.
not_found - Default is "No tags found"/"No categories found", used in the meta box and taxonomy list table.
no_terms - Default is "No tags"/"No categories", used in the posts and media list tables.
items_list_navigation - String for the table pagination hidden heading.
items_list - String for the table hidden heading.
Above, the first default value is for non-hierarchical taxonomies (like tags) and the second one is for hierarchical taxonomies (like categories).
Since
3.0.0
4.3.0 Added the no_terms label.
4.4.0 Added the items_list_navigation and items_list labels.
Parameters
object $tax Taxonomy object.
Returns
object object with all the labels as member variables.
Filter the labels of a specific taxonomy.
The dynamic portion of the hook name, $taxonomy, refers to the taxonomy slug.
Since
4.4.0
See also
get_taxonomy_labels() for the full list of taxonomy labels.
Parameters
object $labels Object with labels for the taxonomy as member variables.
Definition at line 570 of file wp-includes/taxonomy.php.
References $tax, __, _get_custom_object_labels(), _x, apply_filters(), if, null, and object.
Referenced by register_taxonomy().
get_term ($term, $taxonomy = '', $output = OBJECT, $filter = 'raw')
Get all Term data from database by Term ID.
The usage of the get_term function is to apply filters to a term object. It is possible to get a term object from the database before applying the filters.
$term ID must be part of $taxonomy, to get from the database. Failure, might be able to be captured by the hooks. Failure would be the same value as $wpdb returns for the get_row method.
There are two hooks, one is specifically for each term, named 'get_term', and the second is for the taxonomy name, 'term_$taxonomy'. Both hooks gets the term object, and the taxonomy name as parameters. Both hooks are expected to return a Term object.
{
See also
'get_term'} hook - Takes two parameters the term Object and the taxonomy name. Must return term object. Used in get_term() as a catch-all filter for every $term.
{
See also
'get_$taxonomy'} hook - Takes two parameters the term Object and the taxonomy name. Must return term object. $taxonomy will be the taxonomy name, so for example, if 'category', it would be 'get_category' as the filter name. Useful for custom taxonomies or plugging into default taxonomies.
Since
2.3.0
4.4.0 Converted to return a WP_Term object if $output is OBJECT. The $taxonomy parameter was made optional.
wpdb $wpdb WordPress database abstraction object.
See also
sanitize_term_field() The $context param lists the available values for get_term_by() $filter param.
Parameters
int | WP_Term | object $term If integer, term data will be fetched from the database, or from the cache if available. If stdClass object (as in the results of a database query), will apply filters and return a WP_Term object corresponding to the $term data. If WP_Term, will return $term.
string $taxonomy Optional. Taxonomy name that $term is part of.
string $output Constant OBJECT, ARRAY_A, or ARRAY_N
string $filter Optional, default is raw or no WordPress defined filter will applied.
Returns
mixed Type corresponding to $output on success or null on failure. When $output is OBJECT, a WP_Term instance is returned. If taxonomy does not exist then WP_Error will be returned.
Filter a term.
Since
2.3.0
4.4.0 $_term can now also be a WP_Term object.
Parameters
int | WP_Term $_term Term object or ID.
string $taxonomy The taxonomy slug.
Filter a taxonomy.
The dynamic portion of the filter name, $taxonomy, refers to the taxonomy slug.
Since
2.3.0
4.4.0 $_term can now also be a WP_Term object.
Parameters
int | WP_Term $_term Term object or ID.
string $taxonomy The taxonomy slug.
Definition at line 807 of file wp-includes/taxonomy.php.
References $output, __, apply_filters(), ARRAY_A, ARRAY_N, elseif, WP_Term\get_instance(), is_wp_error(), null, sanitize_term(), and taxonomy_exists().
Referenced by _get_term_children(), WP_Terms_List_Table\_rows(), _wp_ajax_add_hierarchical_term(), _wp_ajax_menu_quick_search(), WP_Links_List_Table\column_categories(), WP_Terms_List_Table\column_name(), WP_UnitTest_Factory_For_Term\create_and_get(), export_wp(), get_ancestors(), get_cat_name(), get_category(), get_category_by_path(), get_category_parents(), get_category_to_edit(), get_edit_term_link(), WP_UnitTest_Factory_For_Term\get_object_by_id(), get_permalink(), WP_Query\get_queried_object(), get_tag(), get_term_by(), get_term_feed_link(), get_term_field(), get_term_link(), get_term_to_edit(), get_terms(), get_the_category_by_ID(), GravityView_Widget_Search\prepare_field_filter(), GFFormsModel\prepare_value(), Walker_Category\start_el(), term_is_ancestor_of(), wp_ajax_add_menu_item(), wp_ajax_add_tag(), wp_ajax_delete_tag(), wp_ajax_inline_save_tax(), wp_delete_term(), wp_xmlrpc_server\wp_deleteTerm(), wp_xmlrpc_server\wp_editTerm(), wp_get_nav_menu_object(), wp_get_term_taxonomy_parent_id(), wp_xmlrpc_server\wp_getTerm(), wp_xmlrpc_server\wp_newTerm(), wp_terms_checklist(), wp_unique_term_slug(), wp_update_category(), and wp_update_term().
get_term_by ($field, $value, $taxonomy = '', $output = OBJECT, $filter = 'raw')
Get all Term data from database by Term field and data.
Warning: $value is not escaped for 'name' $field. You must do it yourself, if required.
The default $field is 'id', therefore it is possible to also use null for field, but not recommended that you do so.
If $value does not exist, the return value will be false. If $taxonomy exists and $field and $value combinations exist, the Term will be returned.
Since
2.3.0
4.4.0 $taxonomy is optional if $field is 'term_taxonomy_id'. Converted to return a WP_Term object if $output is OBJECT.
wpdb $wpdb WordPress database abstraction object.
See also
sanitize_term_field() The $context param lists the available values for get_term_by() $filter param.
Parameters
string $field Either 'slug', 'name', 'id' (term_id), or 'term_taxonomy_id'
string | int $value Search for this term value
string $taxonomy Taxonomy name. Optional, if $field is 'term_taxonomy_id'.
string $output Constant OBJECT, ARRAY_A, or ARRAY_N
string $filter Optional, default is raw or no WordPress defined filter will applied.
Returns
WP_Term|bool WP_Term instance on success. Will return false if $taxonomy does not exist or $term was not found.
Definition at line 901 of file wp-includes/taxonomy.php.
References $field, $output, $value, $wpdb, elseif, get_term(), is_wp_error(), sanitize_title(), taxonomy_exists(), wp_cache_add(), and wp_unslash().
Referenced by wp_xmlrpc_server\_insert_post(), _wp_preview_terms_filter(), get_bookmarks(), get_cat_ID(), get_category_by_slug(), Featured_Content\get_featured_post_ids(), get_linkobjectsbyname(), get_linksbyname(), get_post_format_link(), WP_Query\get_posts(), WP_Query\get_queried_object(), get_term_link(), gravityview_convert_value_to_term_list(), upgrade_350(), Featured_Content\validate_settings(), wp_get_nav_menu_object(), wp_insert_term(), wp_unique_term_slug(), wp_update_nav_menu_object(), and wp_update_term().
get_term_children ($term_id, $taxonomy)
Merge all term children into a single array of their IDs.
This recursive function will merge all of the children of $term into the same array of term IDs. Only useful for taxonomies which are hierarchical.
Will return an empty array if $term does not exist in $taxonomy.
Since
2.3.0
Parameters
string $term_id ID of Term to get children.
string $taxonomy Taxonomy Name.
Returns
array|WP_Error List of Term IDs. WP_Error returned if $taxonomy does not exist.
Definition at line 962 of file wp-includes/taxonomy.php.
References __, _get_term_hierarchy(), and taxonomy_exists().
Referenced by WP_Tax_Query\clean_query(), and get_terms().
get_term_field ($field, $term, $taxonomy = '', $context = 'display')
Get sanitized Term field.
The function is for contextual reasons and for simplicity of usage.
Since
2.3.0
4.4.0 The $taxonomy parameter was made optional. $term can also now accept a WP_Term object.
See also
sanitize_term_field()
Parameters
string $field Term field to fetch.
int | WP_Term $term Term ID or object.
string $taxonomy Optional. Taxonomy Name. Default empty.
string $context Optional, default is display. Look at sanitize_term_field() for available options.
Returns
string|int|null|WP_Error Will return an empty string if $term is not an object or if $field is not set in $term.
Definition at line 1003 of file wp-includes/taxonomy.php.
References $field, get_term(), is_wp_error(), and sanitize_term_field().
Referenced by WP_Customize_Nav_Menu_Item_Setting\populate_value(), Walker_Nav_Menu_Edit\start_el(), term_description(), wp_setup_nav_menu_item(), and wp_update_nav_menu_item().
get_term_link ($term, $taxonomy = '')
Generate a permalink for a taxonomy term archive.
Since
2.5.0
WP_Rewrite $wp_rewrite
Parameters
object | int | string $term The term object, ID, or slug whose link will be retrieved.
string $taxonomy Optional. Taxonomy. Default empty.
Returns
string|WP_Error HTML link to taxonomy term archive on success, WP_Error if term does not exist.
Filter the tag link.
Since
2.3.0
Parameters
string $termlink Tag link URL.
int $term_id Term ID.
Filter the category link.
Since
1.5.0
Parameters
string $termlink Category link URL.
int $term_id Term ID.
Filter the term link.
Since
2.5.0
Parameters
string $termlink Term link URL.
object $term Term object.
string $taxonomy Taxonomy slug.
Definition at line 4388 of file wp-includes/taxonomy.php.
References $wp_rewrite, __, apply_filters(), elseif, get_ancestors(), get_taxonomy(), get_term(), get_term_by(), home_url(), is_wp_error(), str_replace, and user_trailingslashit().
Referenced by get_category_link(), get_post_format_link(), get_tag_link(), get_term_feed_link(), get_the_taxonomies(), get_the_term_list(), gravityview_convert_value_to_term_list(), WP_Terms_List_Table\handle_row_actions(), WP_Customize_Nav_Menus\load_available_items_query(), redirect_canonical(), WP_Customize_Nav_Menus\search_available_items_query(), Walker_Category\start_el(), wp_admin_bar_edit_menu(), wp_setup_nav_menu_item(), and wp_tag_cloud().
get_term_meta ($term_id, $key = '', $single = false)
Retrieves metadata for a term.
Since
4.4.0
Parameters
int $term_id Term ID.
string $key Optional. The meta key to retrieve. If no key is provided, fetches all metadata for the term.
bool $single Whether to return a single value. If false, an array of all values matching the $term_id/$key pair will be returned. Default: false.
Returns
mixed If $single is false, an array of metadata values. If $single is true, a single metadata value.
Definition at line 1690 of file wp-includes/taxonomy.php.
References get_metadata(), and get_option().
get_term_to_edit ($id, $taxonomy)
Sanitizes Term for editing.
Return value is sanitize_term() and usage is for sanitizing the term for editing. Function is for contextual and simplicity.
Since
2.3.0
Parameters
int | object $id Term ID or object.
string $taxonomy Taxonomy name.
Returns
string|int|null|WP_Error Will return empty string if $term is not an object.
Definition at line 1029 of file wp-includes/taxonomy.php.
References $id, get_term(), is_wp_error(), and sanitize_term().
get_terms ($taxonomies, $args = '')
Retrieve the terms in a given taxonomy or list of taxonomies.
You can fully inject any customizations to the query before it is sent, as well as control the output with a filter.
The {
See also
'get_terms'} filter will be called when the cache has the term and will pass the found term along with the array of $taxonomies and array of $args. This filter is also called before the array of terms is passed and will pass the array of terms, along with the $taxonomies and $args.
The {
See also
'list_terms_exclusions'} filter passes the compiled exclusions along with the $args.
The {
See also
'get_terms_orderby'} filter passes the ORDER BY clause for the query along with the $args array.
Since
2.3.0
4.2.0 Introduced 'name' and 'childless' parameters.
4.4.0 Introduced the ability to pass 'term_id' as an alias of 'id' for the orderby parameter. Introduced the 'meta_query' and 'update_term_meta_cache' parameters. Converted to return a list of WP_Term objects.
wpdb $wpdb WordPress database abstraction object. array $wp_filter
Parameters
string | array $taxonomies Taxonomy name or list of Taxonomy names.
array | string $args { Optional. Array or string of arguments to get terms.
string $orderby Field(s) to order terms by. Accepts term fields ('name', 'slug', 'term_group', 'term_id', 'id', 'description'), 'count' for term taxonomy count, 'include' to match the 'order' of the $include param, or 'none' to skip ORDER BY. Defaults to 'name'. string $order Whether to order terms in ascending or descending order. Accepts 'ASC' (ascending) or 'DESC' (descending). Default 'ASC'. bool|int $hide_empty Whether to hide terms not assigned to any posts. Accepts 1|true or 0|false. Default 1|true. array|string $include Array or comma/space-separated string of term ids to include. Default empty array. array|string $exclude Array or comma/space-separated string of term ids to exclude. If $include is non-empty, $exclude is ignored. Default empty array. array|string $exclude_tree Array or comma/space-separated string of term ids to exclude along with all of their descendant terms. If $include is non-empty, $exclude_tree is ignored. Default empty array. int|string $number Maximum number of terms to return. Accepts ''|0 (all) or any positive number. Default ''|0 (all). int $offset The number by which to offset the terms query. Default empty. string $fields Term fields to query for. Accepts 'all' (returns an array of complete term objects), 'ids' (returns an array of ids), 'id=>parent' (returns an associative array with ids as keys, parent term IDs as values), 'names' (returns an array of term names), 'count' (returns the number of matching terms), 'id=>name' (returns an associative array with ids as keys, term names as values), or 'id=>slug' (returns an associative array with ids as keys, term slugs as values). Default 'all'. string|array $name Optional. Name or array of names to return term(s) for. Default empty. string|array $slug Optional. Slug or array of slugs to return term(s) for. Default empty. bool $hierarchical Whether to include terms that have non-empty descendants (even if $hide_empty is set to true). Default true. string $search Search criteria to match terms. Will be SQL-formatted with wildcards before and after. Default empty. string $name__like Retrieve terms with criteria by which a term is LIKE $name__like. Default empty. string $description__like Retrieve terms where the description is LIKE $description__like. Default empty. bool $pad_counts Whether to pad the quantity of a term's children in the quantity of each term's "count" object variable. Default false. string $get Whether to return terms regardless of ancestry or whether the terms are empty. Accepts 'all' or empty (disabled). Default empty. int $child_of Term ID to retrieve child terms of. If multiple taxonomies are passed, $child_of is ignored. Default 0. int|string $parent Parent term ID to retrieve direct-child terms of. Default empty. bool $childless True to limit results to terms that have no children. This parameter has no effect on non-hierarchical taxonomies. Default false. string $cache_domain Unique cache key to be produced when this query is stored in an object cache. Default is 'core'. bool $update_term_meta_cache Whether to prime meta caches for matched terms. Default true. array $meta_query Meta query clauses to limit retrieved terms by. See WP_Meta_Query. Default empty. }
Returns
array|int|WP_Error List of WP_Term instances and their children. Will return WP_Error, if any of $taxonomies do not exist.
Filter the terms query default arguments.
Use 'get_terms_args' to filter the passed arguments.
Since
4.4.0
Parameters
array $defaults An array of default get_terms() arguments.
array $taxonomies An array of taxonomies.
Filter the terms query arguments.
Since
3.1.0
Parameters
array $args An array of get_terms() arguments.
array $taxonomies An array of taxonomies.
Filter the ORDERBY clause of the terms query.
Since
2.8.0
Parameters
string $orderby ORDERBY clause of the terms query.
array $args An array of terms query arguments.
array $taxonomies An array of taxonomies.
Filter the terms to exclude from the terms query.
Since
2.3.0
Parameters
string $exclusions NOT IN clause of the terms query.
array $args An array of terms query arguments.
array $taxonomies An array of taxonomies.
Filter the fields to select in the terms query.
Field lists modified using this filter will only modify the term fields returned by the function when the $fields parameter set to 'count' or 'all'. In all other cases, the term fields in the results array will be determined by the $fields parameter alone.
Use of this filter can result in unpredictable behavior, and is not recommended.
Since
2.8.0
Parameters
array $selects An array of fields to select for the terms query.
array $args An array of term query arguments.
array $taxonomies An array of taxonomies.
Filter the terms query SQL clauses.
Since
3.1.0
Parameters
array $pieces Terms query SQL clauses.
array $taxonomies An array of taxonomies.
array $args An array of terms query arguments.
Filter the given taxonomy's terms cache.
Since
2.3.0
Parameters
array $cache Cached array of terms for the given taxonomy.
array $taxonomies An array of taxonomies.
array $args An array of get_terms() arguments.
This filter is documented in wp-includes/taxonomy.php
This filter is documented in wp-includes/taxonomy.php
Definition at line 1126 of file wp-includes/taxonomy.php.
References $wpdb, __, _get_term_children(), _get_term_hierarchy(), _pad_term_counts(), absint(), apply_filters(), elseif, get_term(), get_term_children(), is_taxonomy_hierarchical(), sanitize_term_field(), sanitize_title(), taxonomy_exists(), update_term_cache(), update_termmeta_cache(), wp_array_slice_assoc(), wp_cache_add(), wp_cache_get(), wp_cache_set(), wp_list_pluck(), wp_parse_args(), and wp_parse_id_list().
Referenced by _get_term_hierarchy(), wp_xmlrpc_server\_insert_post(), _wp_ajax_menu_quick_search(), WP_Terms_List_Table\display_rows_or_placeholder(), edit_post(), export_wp(), WP_Widget_Links\form(), get_all_category_ids(), get_categories(), get_category_by_path(), get_tags(), gravityview_get_terms_choices(), WP_Customize_Nav_Menus\load_available_items_query(), WP_Customize_Nav_Menus\search_available_items_query(), Walker_Category\start_el(), wp_ajax_ajax_tag_search(), wp_ajax_get_tagcloud(), wp_count_terms(), wp_dropdown_categories(), wp_get_nav_menu_items(), wp_get_nav_menus(), wp_xmlrpc_server\wp_getTerms(), wp_insert_term(), wp_link_category_checklist(), wp_list_bookmarks(), wp_nav_menu_item_taxonomy_meta_box(), wp_popular_terms_checklist(), wp_tag_cloud(), and wp_terms_checklist().
get_the_taxonomies ($post = 0, $args = array())
Retrieve all taxonomies associated with a post.
This function can be used within the loop. It will also return an array of the taxonomies with links to the taxonomy and name.
Since
2.5.0
Parameters
int | WP_Post $post Optional. Post ID or WP_Post object. Default is global $post.
array $args { Optional. Arguments about how to format the list of taxonomies. Default empty array.
string $template Template for displaying a taxonomy label and list of terms. Default is "Label: Terms." string $term_template Template for displaying a single term in the list. Default is the term name linked to its archive. }
Returns
array List of taxonomies.
Definition at line 4526 of file wp-includes/taxonomy.php.
References $post, __, esc_attr(), get_object_taxonomies(), get_object_term_cache(), get_post(), get_taxonomy(), get_term_link(), wp_get_object_terms(), wp_parse_args(), and wp_sprintf().
Referenced by the_taxonomies().
is_object_in_taxonomy ($object_type, $taxonomy)
Determine if the given object type is associated with the given taxonomy.
Since
3.0.0
Parameters
string $object_type Object type string.
string $taxonomy Single taxonomy name.
Returns
bool True if object is associated with the taxonomy, otherwise false.
Definition at line 4654 of file wp-includes/taxonomy.php.
References get_object_taxonomies().
Referenced by WP_Post\__get(), wp_xmlrpc_server\_prepare_page(), WP_Posts_List_Table\extra_tablenav(), WP_Screen\get(), get_adjacent_post(), get_post_class(), get_the_category_list(), and wp_insert_post().
is_object_in_term ($object_id, $taxonomy, $terms = null)
Determine if the given object is associated with any of the given terms.
The given terms are checked against the object's terms' term_ids, names and slugs. Terms given as integers will only be checked against the object's terms' term_ids. If no terms are given, determines if object is associated with any terms in the given taxonomy.
Since
2.7.0
Parameters
int $object_id ID of the object (post ID, link ID, ...).
string $taxonomy Single taxonomy name.
int | string | array $terms Optional. Term term_id, name, slug or array of said. Default null.
Returns
bool|WP_Error WP_Error on input error.
Definition at line 4600 of file wp-includes/taxonomy.php.
References __, get_object_term_cache(), is_wp_error(), wp_cache_set(), and wp_get_object_terms().
Referenced by has_term(), and wp_update_nav_menu_item().
is_taxonomy_hierarchical ($taxonomy)
Whether the taxonomy object is hierarchical.
Checks to make sure that the taxonomy is an object first. Then Gets the object, and finally returns the hierarchical value in the object.
A false return value might also mean that the taxonomy does not exist.
Since
2.3.0
Parameters
string $taxonomy Name of taxonomy object.
Returns
bool Whether the taxonomy is hierarchical.
Definition at line 253 of file wp-includes/taxonomy.php.
References get_taxonomy(), and taxonomy_exists().
Referenced by _get_term_hierarchy(), wp_xmlrpc_server\_insert_post(), _pad_term_counts(), _wp_menu_item_classes_by_context(), bulk_edit_posts(), WP_Tax_Query\clean_query(), WP_Terms_List_Table\display_rows_or_placeholder(), edit_post(), get_ancestors(), get_terms(), wp_ajax_add_tag(), wp_delete_term(), wp_insert_term(), wp_nav_menu_item_taxonomy_meta_box(), wp_set_post_terms(), and wp_unique_term_slug().
register_taxonomy ($taxonomy, $object_type, $args = array())
Creates or modifies a taxonomy object.
Note: Do not use before the {
See also
'init'} hook.
A simple function for creating or modifying a taxonomy object based on the parameters given. The function will accept an array (third optional parameter), along with strings for the taxonomy name and another string for the object type.
Since
2.3.0
4.2.0 Introduced show_in_quick_edit argument.
4.4.0 The show_ui argument is now enforced on the term editing screen.
4.4.0 The public argument now controls whether the taxonomy can be queried on the front-end.
array $wp_taxonomies Registered taxonomies. WP $wp WP instance.
Parameters
string $taxonomy Taxonomy key, must not exceed 32 characters.
array | string $object_type Name of the object type for the taxonomy object.
array | string $args { Optional. Array or query string of arguments for registering a taxonomy.
string $label Name of the taxonomy shown in the menu. Usually plural. If not set, `$labels['name']` will be used. array $labels An array of labels for this taxonomy. By default, Tag labels are used for non-hierarchical taxonmies, and Category labels are used for hierarchical taxonomies. See accepted values in get_taxonomy_labels(). Default empty array. string $description A short descriptive summary of what the taxonomy is for. Default empty. bool $public Whether the taxonomy is publicly queryable. Default true. bool $hierarchical Whether the taxonomy is hierarchical. Default false. bool $show_ui Whether to generate and allow a UI for managing terms in this taxonomy in the admin. If not set, the default is inherited from $public (default true). bool $show_in_menu Whether to show the taxonomy in the admin menu. If true, the taxonomy is shown as a submenu of the object type menu. If false, no menu is shown. $show_ui must be true. If not set, default is inherited from $show_ui (default true). bool $show_in_nav_menus Makes this taxonomy available for selection in navigation menus. If not set, the default is inherited from $public (default true). bool $show_tagcloud Whether to list the taxonomy in the Tag Cloud Widget controls. If not set, the default is inherited from $show_ui (default true). bool $show_in_quick_edit Whether to show the taxonomy in the quick/bulk edit panel. It not set, the default is inherited from $show_ui (default true). bool $show_admin_column Whether to display a column for the taxonomy on its post type listing screens. Default false. bool|callable $meta_box_cb Provide a callback function for the meta box display. If not set, post_categories_meta_box() is used for hierarchical taxonomies, and post_tags_meta_box() is used for non-hierarchical. If false, no meta box is shown. array $capabilities { Array of capabilities for this taxonomy.
string $manage_terms Default 'manage_categories'. string $edit_terms Default 'manage_categories'. string $delete_terms Default 'manage_categories'. string $assign_terms Default 'edit_posts'. } bool|array $rewrite { Triggers the handling of rewrites for this taxonomy. Default true, using $taxonomy as slug. To prevent rewrite, set to false. To specify rewrite rules, an array can be passed with any of these keys:
string $slug Customize the permastruct slug. Default $taxonomy key. bool $with_front Should the permastruct be prepended with WP_Rewrite::$front. Default true. bool $hierarchical Either hierarchical rewrite tag or not. Default false. int $ep_mask Assign an endpoint mask. Default EP_NONE. } string $query_var Sets the query var key for this taxonomy. Default $taxonomy key. If false, a taxonomy cannot be loaded at ?{query_var}={term_slug}. If a string, the query ?{query_var}={term_slug} will be valid. callable $update_count_callback Works much like a hook, in that it will be called when the count is updated. Default _update_post_term_count() for taxonomies attached to post types, which confirms that the objects are published before counting them. Default _update_generic_term_count() for taxonomies attached to other object types, such as users. bool $_builtin This taxonomy is a "built-in" taxonomy. INTERNAL USE ONLY! Default false. }
Returns
WP_Error|void WP_Error, if errors.
Filter the arguments for registering a taxonomy.
Since
4.4.0
Parameters
array $args Array of arguments for registering a taxonomy.
array $object_type Array of names of object types for the taxonomy.
string $taxonomy Taxonomy key.
Fires after a taxonomy is registered.
Since
3.3.0
Parameters
string $taxonomy Taxonomy slug.
array | string $object_type Object type or array of object types.
array $args Array of taxonomy registration arguments.
Definition at line 342 of file wp-includes/taxonomy.php.
References $wp, __, _doing_it_wrong(), add_filter(), add_permastruct(), add_rewrite_tag(), apply_filters(), do_action(), EP_NONE, get_option(), get_taxonomy_labels(), is_admin(), null, object, sanitize_title_with_dashes(), and wp_parse_args().
Referenced by create_initial_taxonomies().
register_taxonomy_for_object_type ($taxonomy, $object_type)
Add an already registered taxonomy to an object type.
Since
3.0.0
array $wp_taxonomies The registered taxonomies.
Parameters
string $taxonomy Name of taxonomy object.
string $object_type Name of the object type.
Returns
bool True if successful, false if not.
Definition at line 638 of file wp-includes/taxonomy.php.
References get_post_type_object().
Referenced by register_post_type().
sanitize_term ($term, $taxonomy, $context = 'display')
Sanitize Term all fields.
Relies on sanitize_term_field() to sanitize the term. The difference is that this function will sanitize all fields. The context is based on sanitize_term_field().
The $term is expected to be either an array or an object.
Since
2.3.0
Parameters
array | object $term The term to check.
string $taxonomy The taxonomy name to use.
string $context Optional. Context in which to sanitize the term. Accepts 'edit', 'db', 'display', 'attribute', or 'js'. Default 'display'.
Returns
array|object Term with all fields sanitized.
Definition at line 1864 of file wp-includes/taxonomy.php.
References $field, and sanitize_term_field().
Referenced by WP_Term\__get(), WP_Term\filter(), WP_Term\get_instance(), get_term(), get_term_to_edit(), sanitize_category(), WP_Terms_List_Table\single_row(), wp_get_object_terms(), wp_insert_term(), and wp_update_term().
sanitize_term_field ($field, $value, $term_id, $taxonomy, $context)
Cleanse the field value in the term based on the context.
Passing a term field value through the function should be assumed to have cleansed the value for whatever context the term field is going to be used.
If no context or an unsupported context is given, then default filters will be applied.
There are enough filters for each context to support a custom filtering without creating your own filter function. Simply create a function that hooks into the filter you need.
Since
2.3.0
Parameters
string $field Term field to sanitize.
string $value Search for this term value.
int $term_id Term ID.
string $taxonomy Taxonomy Name.
string $context Context in which to sanitize the term field. Accepts 'edit', 'db', 'display', 'attribute', or 'js'.
Returns
mixed Sanitized field.
Filter a term field to edit before it is sanitized.
The dynamic portion of the filter name, $field, refers to the term field.
Since
2.3.0
Parameters
mixed $value Value of the term field.
int $term_id Term ID.
string $taxonomy Taxonomy slug.
Filter the taxonomy field to edit before it is sanitized.
The dynamic portions of the filter name, $taxonomy and $field, refer to the taxonomy slug and taxonomy field, respectively.
Since
2.3.0
Parameters
mixed $value Value of the taxonomy field to edit.
int $term_id Term ID.
Filter a term field value before it is sanitized.
The dynamic portion of the filter name, $field, refers to the term field.
Since
2.3.0
Parameters
mixed $value Value of the term field.
string $taxonomy Taxonomy slug.
Filter a taxonomy field before it is sanitized.
The dynamic portions of the filter name, $taxonomy and $field, refer to the taxonomy slug and field name, respectively.
Since
2.3.0
Parameters
mixed $value Value of the taxonomy field.
Filter the category nicename before it is sanitized.
Use the pre_{$taxonomy}_{$field} hook instead.
Since
2.0.3
Parameters
string $value The category nicename.
Filter the term field for use in RSS.
The dynamic portion of the filter name, $field, refers to the term field.
Since
2.3.0
Parameters
mixed $value Value of the term field.
string $taxonomy Taxonomy slug.
Filter the taxonomy field for use in RSS.
The dynamic portions of the hook name, $taxonomy, and $field, refer to the taxonomy slug and field name, respectively.
Since
2.3.0
Parameters
mixed $value Value of the taxonomy field.
Filter the term field sanitized for display.
The dynamic portion of the filter name, $field, refers to the term field name.
Since
2.3.0
Parameters
mixed $value Value of the term field.
int $term_id Term ID.
string $taxonomy Taxonomy slug.
string $context Context to retrieve the term field value.
Filter the taxonomy field sanitized for display.
The dynamic portions of the filter name, $taxonomy, and $field, refer to the taxonomy slug and taxonomy field, respectively.
Since
2.3.0
Parameters
mixed $value Value of the taxonomy field.
int $term_id Term ID.
string $context Context to retrieve the taxonomy field value.
Definition at line 1912 of file wp-includes/taxonomy.php.
References $field, $value, apply_filters(), elseif, esc_attr(), esc_html, and esc_js().
Referenced by WP_Media_List_Table\column_default(), WP_Posts_List_Table\column_default(), get_term_field(), get_terms(), get_the_category_rss(), WP_Query\parse_tax_query(), sanitize_category_field(), sanitize_term(), WP_Tax_Query\transform_query(), and wp_get_object_terms().
taxonomy_exists ($taxonomy)
Checks that the taxonomy name exists.
Formerly is_taxonomy(), introduced in 2.3.0.
Since
3.0.0
array $wp_taxonomies The registered taxonomies.
Parameters
string $taxonomy Name of taxonomy object.
Returns
bool Whether the taxonomy exists.
Definition at line 234 of file wp-includes/taxonomy.php.
Referenced by WP_Terms_List_Table\__construct(), WP_Widget_Tag_Cloud\_get_current_taxonomy(), _wp_ajax_menu_quick_search(), WP_Tax_Query\clean_query(), WP_Screen\get(), get_adjacent_post(), get_boundary_post(), WP_Term\get_instance(), get_objects_in_term(), get_taxonomy(), get_term(), get_term_by(), get_term_children(), get_terms(), is_taxonomy(), is_taxonomy_hierarchical(), WP_Customize_Nav_Menu_Item_Setting\populate_value(), unregister_taxonomy(), wp_xmlrpc_server\wp_deleteTerm(), wp_xmlrpc_server\wp_editTerm(), wp_get_object_terms(), wp_xmlrpc_server\wp_getTaxonomy(), wp_xmlrpc_server\wp_getTerm(), wp_xmlrpc_server\wp_getTerms(), wp_insert_term(), wp_list_categories(), wp_xmlrpc_server\wp_newTerm(), wp_remove_object_terms(), wp_set_object_terms(), and wp_update_term().
term_exists ($term, $taxonomy = '', $parent = null)
Check if Term exists.
Formerly is_term(), introduced in 2.3.0.
Since
3.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | string $term The term to check
string $taxonomy The taxonomy name to use
int $parent Optional. ID of parent term under which to confine the exists search.
Returns
mixed Returns null if the term does not exist. Returns the term ID if no taxonomy is specified and the term ID exists. Returns an array of the term ID and the term taxonomy ID the taxonomy is specified and the pairing exists.
Definition at line 1772 of file wp-includes/taxonomy.php.
References $wpdb, ARRAY_A, sanitize_title(), and wp_unslash().
Referenced by _wp_ajax_add_hierarchical_term(), WP_Press_This\add_category(), category_exists(), export_wp(), is_term(), tag_exists(), wp_ajax_add_link_category(), wp_create_term(), wp_delete_term(), wp_insert_category(), wp_insert_term(), wp_remove_object_terms(), wp_set_object_terms(), wp_unique_term_slug(), and wp_update_term().
term_is_ancestor_of ($term1, $term2, $taxonomy)
Check if a term is an ancestor of another term.
You can use either an id or the term object for both parameters.
Since
3.4.0
Parameters
int | object $term1 ID or object to check if this is the parent term.
int | object $term2 The child term.
string $taxonomy Taxonomy name that $term1 and $term2 belong to.
Returns
bool Whether $term2 is a child of $term1.
Definition at line 1833 of file wp-includes/taxonomy.php.
References get_term().
Referenced by cat_is_ancestor_of(), and wp_insert_category().
the_taxonomies ($args = array())
Display the taxonomies of a post with available options.
This function can be used within the loop to display the taxonomies for a post without specifying the Post ID. You can also use it outside the Loop to display the taxonomies for a specific post.
Since
2.5.0
Parameters
array $args { Arguments about which post to use and how to format the output. Shares all of the arguments supported by get_the_taxonomies(), in addition to the following.
int|WP_Post $post Post ID or object to get taxonomies of. Default current post. string $before Displays before the taxonomies. Default empty string. string $sep Separates each taxonomy. Default is a space. string $after Displays after the taxonomies. Default empty string. }
Definition at line 4494 of file wp-includes/taxonomy.php.
References get_the_taxonomies(), and wp_parse_args().
unregister_taxonomy ($taxonomy)
Unregister a taxonomy.
Can not be used to unregister built-in taxonomies.
Since
4.5.0
WP $wp Current WordPress environment instance. array $wp_taxonomies List of taxonomies.
Parameters
string $taxonomy Taxonomy name.
Returns
bool|WP_Error True on success, WP_Error on failure.
Fires after a taxonomy is unregistered.
Since
4.5.0
Parameters
string $taxonomy Taxonomy name.
Definition at line 491 of file wp-includes/taxonomy.php.
References $wp, __, do_action(), get_taxonomy(), remove_filter(), remove_permastruct(), remove_rewrite_tag(), and taxonomy_exists().
unregister_taxonomy_for_object_type ($taxonomy, $object_type)
Remove an already registered taxonomy from an object type.
Since
3.7.0
array $wp_taxonomies The registered taxonomies.
Parameters
string $taxonomy Name of taxonomy object.
string $object_type Name of the object type.
Returns
bool True if successful, false if not.
Definition at line 667 of file wp-includes/taxonomy.php.
References get_post_type_object().
update_object_term_cache ($object_ids, $object_type)
Updates the cache for the given term object ID(s).
Note: Due to performance concerns, great care should be taken to only update term caches when necessary. Processing time can increase exponentially depending on both the number of passed term IDs and the number of taxonomies those terms belong to.
Caches will only be updated for terms not already cached.
Since
2.3.0
Parameters
string | array $object_ids Comma-separated list or array of term object IDs.
array | string $object_type The taxonomy object type.
Returns
void|false False if all of the terms in $object_ids are already cached.
Definition at line 3662 of file wp-includes/taxonomy.php.
References $id, $value, get_object_taxonomies(), wp_cache_add(), wp_cache_get(), and wp_get_object_terms().
Referenced by update_post_caches().
update_term_cache ($terms, $taxonomy = '')
Updates Terms to Taxonomy in cache.
Since
2.3.0
Parameters
array $terms List of term objects to change.
string $taxonomy Optional. Update Term to this taxonomy in cache. Default empty.
Definition at line 3721 of file wp-includes/taxonomy.php.
References wp_cache_add().
Referenced by get_terms(), and wp_get_object_terms().
update_term_meta ($term_id, $meta_key, $meta_value, $prev_value = '')
Updates term metadata.
Use the $prev_value parameter to differentiate between meta fields with the same key and term ID.
If the meta field for the term does not exist, it will be added.
Since
4.4.0
Parameters
int $term_id Term ID.
string $meta_key Metadata key.
mixed $meta_value Metadata value.
mixed $prev_value Optional. Previous value to check before removing.
Returns
int|WP_Error|bool Meta ID if the key didn't previously exist. True on successful update. WP_Error when term_id is ambiguous between taxonomies. False on failure.
Definition at line 1715 of file wp-includes/taxonomy.php.
References $updated, __, get_option(), update_metadata(), wp_cache_set(), and wp_term_is_shared().
update_termmeta_cache ($term_ids)
Updates metadata cache for list of term IDs.
Performs SQL query to retrieve all metadata for the terms matching $term_ids and stores them in the cache. Subsequent calls to get_term_meta() will not need to query the database.
Since
4.4.0
Parameters
array $term_ids List of term IDs.
Returns
array|false Returns false if there is nothing to update. Returns an array of metadata on success.
Definition at line 1746 of file wp-includes/taxonomy.php.
References get_option(), and update_meta_cache().
Referenced by get_terms(), WP_Query\lazyload_term_meta(), and wp_get_object_terms().
wp_add_object_terms ($object_id, $terms, $taxonomy)
Add term(s) associated with a given object.
Since
3.6.0
Parameters
int $object_id The ID of the object to which the terms will be added.
array | int | string $terms The slug(s) or ID(s) of the term(s) to add.
array | string $taxonomy Taxonomy name.
Returns
array|WP_Error Affected Term IDs
Definition at line 2975 of file wp-includes/taxonomy.php.
References wp_set_object_terms().
wp_check_term_hierarchy_for_loops ($parent, $term_id, $taxonomy)
Checks the given subset of the term hierarchy for hierarchy loops.
Prevents loops from forming and breaks those that it finds.
Attached to the {
See also
'wp_update_term_parent'} filter.
Since
3.1.0
Parameters
int $parent term_id of the parent for the term we're checking.
int $term_id The term we're checking.
string $taxonomy The taxonomy of the term we're checking.
Returns
int The new parent for the term.
Definition at line 4749 of file wp-includes/taxonomy.php.
References wp_find_hierarchy_loop(), and wp_update_term().
wp_count_terms ($taxonomy, $args = array())
Count how many terms are in Taxonomy.
Default $args is 'hide_empty' which can be 'hide_empty=true' or array('hide_empty' => true).
Since
2.3.0
Parameters
string $taxonomy Taxonomy name.
array | string $args Optional. Array of arguments that get passed to {
See also
get_terms()}. Default empty array.
Returns
array|int|WP_Error Number of terms in that taxonomy or WP_Error if the taxonomy does not exist.
Definition at line 2072 of file wp-includes/taxonomy.php.
References get_terms(), and wp_parse_args().
Referenced by WP_Terms_List_Table\prepare_items(), and wp_nav_menu_item_taxonomy_meta_box().
wp_defer_term_counting ($defer = null)
Enable or disable term counting.
Since
2.5.0
bool $_defer
Parameters
bool $defer Optional. Enable if true, disable if false.
Returns
bool Whether term counting is enabled or disabled.
Definition at line 3421 of file wp-includes/taxonomy.php.
References null, and wp_update_term_count().
Referenced by wp_nav_menu_update_menu_items(), and wp_update_term_count().
wp_delete_category ($cat_ID)
Deletes one existing category.
Since
2.0.0
Parameters
int $cat_ID
Returns
bool|int|WP_Error Returns true if completes delete action; false if term doesn't exist; Zero on attempted deletion of default Category; WP_Error object is also a possibility.
Definition at line 2314 of file wp-includes/taxonomy.php.
References wp_delete_term().
wp_delete_object_term_relationships ($object_id, $taxonomies)
Will unlink the object from the taxonomy or taxonomies.
Will remove all relationships between the object and any terms in a particular taxonomy or taxonomies. Does not remove the term or taxonomy itself.
Since
2.3.0
Parameters
int $object_id The term Object Id that refers to the term.
string | array $taxonomies List of Taxonomy Names or single Taxonomy name.
Definition at line 2099 of file wp-includes/taxonomy.php.
References wp_get_object_terms(), and wp_remove_object_terms().
Referenced by wp_delete_attachment(), wp_delete_link(), and wp_delete_post().
wp_delete_term ($term, $taxonomy, $args = array())
Removes a term from the database.
If the term is a parent of other terms, then the children will be updated to that term's parent.
Metadata associated with the term will be deleted.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $term Term ID.
string $taxonomy Taxonomy Name.
array | string $args { Optional. Array of arguments to override the default term ID. Default empty array.
int $default The term ID to make the default term. This will only override the terms found if there is only one term found. Any other and the found terms are used. bool $force_default Optional. Whether to force the supplied term as default to be assigned even if the object was not going to be term-less. Default false. }
Returns
bool|int|WP_Error True on success, false if term does not exist. Zero on attempted deletion of default Category. WP_Error if the taxonomy does not exist.
Fires when deleting a term, before any modifications are made to posts or terms.
Since
4.1.0
Parameters
int $term Term ID.
string $taxonomy Taxonomy Name.
Fires immediately before a term to delete's children are reassigned a parent.
Since
2.9.0
Parameters
array $edit_tt_ids An array of term taxonomy IDs for the given term.
Fires immediately after a term to delete's children are reassigned a parent.
Since
2.9.0
Parameters
array $edit_tt_ids An array of term taxonomy IDs for the given term.
Fires immediately before a term taxonomy ID is deleted.
Since
2.9.0
Parameters
int $tt_id Term taxonomy ID.
Fires immediately after a term taxonomy ID is deleted.
Since
2.9.0
Parameters
int $tt_id Term taxonomy ID.
Fires after a term is deleted from the database and the cache is cleaned.
Since
2.5.0
4.5.0 Introduced $object_ids argument.
Parameters
int $term Term ID.
int $tt_id Term taxonomy ID.
string $taxonomy Taxonomy slug.
mixed $deleted_term Copy of the already-deleted term, in the form specified by the parent function. WP_Error otherwise.
array $object_ids List of term object IDs.
Fires after a term in a specific taxonomy is deleted.
The dynamic portion of the hook name, $taxonomy, refers to the specific taxonomy the term belonged to.
Since
2.3.0
4.5.0 Introduced $object_ids argument.
Parameters
int $term Term ID.
int $tt_id Term taxonomy ID.
mixed $deleted_term Copy of the already-deleted term, in the form specified by the parent function. WP_Error otherwise.
array $object_ids List of term object IDs.
Definition at line 2139 of file wp-includes/taxonomy.php.
References $default, $wpdb, clean_object_term_cache(), clean_term_cache(), delete_metadata_by_mid(), do_action(), get_option(), get_taxonomy(), get_term(), is_taxonomy_hierarchical(), is_wp_error(), term_exists(), wp_get_object_terms(), wp_list_pluck(), wp_parse_args(), and wp_set_object_terms().
Referenced by WP_Canonical_UnitTestCase\delete_shared_fixtures(), upgrade_350(), wp_ajax_delete_tag(), wp_delete_category(), wp_delete_nav_menu(), wp_xmlrpc_server\wp_deleteCategory(), and wp_xmlrpc_server\wp_deleteTerm().
wp_get_object_terms ($object_ids, $taxonomies, $args = array())
Retrieves the terms associated with the given object(s), in the supplied taxonomies.
Since
2.3.0
4.2.0 Added support for 'taxonomy', 'parent', and 'term_taxonomy_id' values of $orderby. Introduced $parent argument.
4.4.0 Introduced $meta_query and $update_term_meta_cache arguments. When $fields is 'all' or 'all_with_object_id', an array of WP_Term objects will be returned.
wpdb $wpdb WordPress database abstraction object.
Parameters
int | array $object_ids The ID(s) of the object(s) to retrieve.
string | array $taxonomies The taxonomies to retrieve terms from.
array | string $args { Array of arguments. string $orderby Field by which results should be sorted. Accepts 'name', 'count', 'slug', 'term_group', 'term_order', 'taxonomy', 'parent', or 'term_taxonomy_id'. Default 'name'. string $order Sort order. Accepts 'ASC' or 'DESC'. Default 'ASC'. string $fields Fields to return for matched terms. Accepts 'all', 'ids', 'names', and 'all_with_object_id'. Note that 'all' or 'all_with_object_id' will result in an array of term objects being returned, 'ids' will return an array of integers, and 'names' an array of strings. int $parent Optional. Limit results to the direct children of a given term ID. bool $update_term_meta_cache Whether to prime termmeta cache for matched terms. Only applies when $fields is 'all', 'all_with_object_id', or 'term_id'. Default true. array $meta_query Meta query clauses to limit retrieved terms by. See WP_Meta_Query. Default empty. }
Returns
array|WP_Error The requested term data or empty array if no terms found. WP_Error if any of the $taxonomies don't exist.
Filter the terms for a given object or objects.
Since
4.2.0
Parameters
array $terms An array of terms for the given object or objects.
array $object_id_array Array of object IDs for which $terms were retrieved.
array $taxonomy_array Array of taxonomies from which $terms were retrieved.
array $args An array of arguments for retrieving terms for the given object(s). See wp_get_object_terms() for details.
Filter the terms for a given object or objects.
The $taxonomies parameter passed to this filter is formatted as a SQL fragment. The {
See also
'get_object_terms'} filter is recommended as an alternative.
Since
2.8.0
Parameters
array $terms An array of terms for the given object or objects.
int | array $object_ids Object ID or array of IDs.
string $taxonomies SQL-formatted (comma-separated and quoted) list of taxonomy names.
array $args An array of arguments for retrieving terms for the given object(s). See {
See also
wp_get_object_terms()} for details.
Definition at line 2350 of file wp-includes/taxonomy.php.
References $wpdb, __, apply_filters(), elseif, get_taxonomy(), sanitize_term(), sanitize_term_field(), taxonomy_exists(), update_term_cache(), update_termmeta_cache(), wp_list_pluck(), and wp_parse_args().
Referenced by wp_xmlrpc_server\_prepare_post(), _update_term_count_on_transition_post_status(), _wp_menu_item_classes_by_context(), bulk_edit_posts(), export_wp(), get_adjacent_post(), get_attachment_fields_to_edit(), get_bookmark(), get_boundary_post(), get_compat_media_markup(), get_inline_data(), get_terms_to_edit(), get_the_taxonomies(), get_the_terms(), is_object_in_term(), redirect_canonical(), update_object_term_cache(), wp_delete_object_term_relationships(), wp_delete_term(), wp_get_link_cats(), wp_get_post_categories(), wp_get_post_terms(), wp_popular_terms_checklist(), wp_set_object_terms(), and wp_terms_checklist().
wp_get_split_term ($old_term_id, $taxonomy)
Get the new term ID corresponding to a previously split term.
Since
4.2.0
Parameters
int $old_term_id Term ID. This is the old, pre-split term ID.
string $taxonomy Taxonomy that the term belongs to.
Returns
int|false If a previously split term is found corresponding to the old term_id and taxonomy, the new term_id will be returned. If no previously split term is found matching the parameters, returns false.
Definition at line 4343 of file wp-includes/taxonomy.php.
References wp_get_split_terms().
wp_get_split_terms ($old_term_id)
Get data about terms that previously shared a single term_id, but have since been split.
Since
4.2.0
Parameters
int $old_term_id Term ID. This is the old, pre-split term ID.
Returns
array Array of new term IDs, keyed by taxonomy.
Definition at line 4321 of file wp-includes/taxonomy.php.
References get_option().
Referenced by wp_get_split_term().
wp_get_term_taxonomy_parent_id ($term_id, $taxonomy)
Returns the term's parent's term_ID.
Since
3.1.0
Parameters
int $term_id Term ID.
string $taxonomy Taxonomy name.
Returns
int|false False on error.
Definition at line 4727 of file wp-includes/taxonomy.php.
References get_term(), and is_wp_error().
wp_insert_term ($term, $taxonomy, $args = array())
Add a new term to the database.
A non-existent term is inserted in the following sequence:
The term is added to the term table, then related to the taxonomy.
If everything is correct, several actions are fired.
The 'term_id_filter' is evaluated.
The term cache is cleaned.
Several more actions are fired.
An array is returned containing the term_id and term_taxonomy_id.
If the 'slug' argument is not empty, then it is checked to see if the term is invalid. If it is not a valid, existing term, it is added and the term_id is given.
If the taxonomy is hierarchical, and the 'parent' argument is not empty, the term is inserted and the term_id will be given.
Error handling: If $taxonomy does not exist or $term is empty, a WP_Error object will be returned.
If the term already exists on the same hierarchical level, or the term slug and name are not unique, a WP_Error object will be returned.
wpdb $wpdb WordPress database abstraction object.
Since
2.3.0
Parameters
string $term The term to add or update.
string $taxonomy The taxonomy to which to add the term.
array | string $args { Optional. Array or string of arguments for inserting a term.
string $alias_of Slug of the term to make this term an alias of. Default empty string. Accepts a term slug. string $description The term description. Default empty string. int $parent The id of the parent term. Default 0. string $slug The term slug to use. Default empty string. }
Returns
array|WP_Error An array containing the term_id and term_taxonomy_id, {
See also
WP_Error} otherwise.
Filter a term before it is sanitized and inserted into the database.
Since
3.0.0
Parameters
string $term The term to add or update.
string $taxonomy Taxonomy slug.
This action is documented in wp-includes/taxonomy.php
This action is documented in wp-includes/taxonomy.php
Fires immediately after a new term is created, before the term cache is cleaned.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Term taxonomy ID.
string $taxonomy Taxonomy slug.
Fires after a new term is created for a specific taxonomy.
The dynamic portion of the hook name, $taxonomy, refers to the slug of the taxonomy the term was created for.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Term taxonomy ID.
Filter the term ID after a new term is created.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Taxonomy term ID.
Fires after a new term is created, and after the term cache has been cleaned.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Term taxonomy ID.
string $taxonomy Taxonomy slug.
Fires after a new term in a specific taxonomy is created, and after the term cache has been cleaned.
The dynamic portion of the hook name, $taxonomy, refers to the taxonomy slug.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Term taxonomy ID.
Definition at line 2608 of file wp-includes/taxonomy.php.
References $description, $name, $wpdb, __, apply_filters(), clean_term_cache(), do_action(), elseif, get_term_by(), get_terms(), if, is_taxonomy_hierarchical(), is_wp_error(), null, sanitize_term(), sanitize_title(), taxonomy_exists(), term_exists(), wp_list_pluck(), wp_parse_args(), wp_unique_term_slug(), wp_unslash(), and wp_update_term().
Referenced by wp_xmlrpc_server\_insert_post(), _wp_ajax_add_hierarchical_term(), WP_Press_This\add_category(), WP_UnitTest_Factory_For_Term\create_object(), wp_ajax_add_link_category(), wp_ajax_add_tag(), wp_create_term(), wp_insert_category(), wp_xmlrpc_server\wp_newTerm(), wp_set_object_terms(), and wp_update_nav_menu_object().
wp_remove_object_terms ($object_id, $terms, $taxonomy)
Remove term(s) associated with a given object.
Since
3.6.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $object_id The ID of the object from which the terms will be removed.
array | int | string $terms The slug(s) or ID(s) of the term(s) to remove.
array | string $taxonomy Taxonomy name.
Returns
bool|WP_Error True on success, false or WP_Error on failure.
Fires immediately before an object-term relationship is deleted.
Since
2.9.0
Parameters
int $object_id Object ID.
array $tt_ids An array of term taxonomy IDs.
Fires immediately after an object-term relationship is deleted.
Since
2.9.0
Parameters
int $object_id Object ID.
array $tt_ids An array of term taxonomy IDs.
Definition at line 2991 of file wp-includes/taxonomy.php.
References $wpdb, __, do_action(), is_wp_error(), taxonomy_exists(), term_exists(), wp_cache_delete(), and wp_update_term_count().
Referenced by wp_delete_object_term_relationships(), and wp_set_object_terms().
wp_set_object_terms ($object_id, $terms, $taxonomy, $append = false)
Create Term and Taxonomy Relationships.
Relates an object (post, link etc) to a term and taxonomy type. Creates the term and taxonomy relationship if it doesn't already exist. Creates a term if it doesn't exist (using the slug).
A relationship means that the term is grouped in or belongs to the taxonomy. A term has no meaning until it is given context by defining which taxonomy it exists under.
Since
2.3.0
wpdb $wpdb The WordPress database abstraction object.
Parameters
int $object_id The object to relate to.
array | int | string $terms A single term slug, single term id, or array of either term slugs or ids. Will replace all existing related terms in this taxonomy.
string $taxonomy The context in which to relate the term to the object.
bool $append Optional. If false will delete difference of terms. Default false.
Returns
array|WP_Error Affected Term IDs.
Fires immediately before an object-term relationship is added.
Since
2.9.0
Parameters
int $object_id Object ID.
int $tt_id Term taxonomy ID.
Fires immediately after an object-term relationship is added.
Since
2.9.0
Parameters
int $object_id Object ID.
int $tt_id Term taxonomy ID.
Fires after an object's terms have been set.
Since
2.8.0
Parameters
int $object_id Object ID.
array $terms An array of object terms.
array $tt_ids An array of term taxonomy IDs.
string $taxonomy Taxonomy slug.
bool $append Whether to append new terms to the old terms.
array $old_tt_ids Old array of term taxonomy IDs.
Definition at line 2854 of file wp-includes/taxonomy.php.
References $wpdb, __, do_action(), get_taxonomy(), is_wp_error(), taxonomy_exists(), term_exists(), wp_cache_delete(), wp_get_object_terms(), wp_insert_term(), wp_remove_object_terms(), and wp_update_term_count().
Referenced by media_upload_form_handler(), wp_add_object_terms(), wp_ajax_save_attachment_compat(), wp_delete_term(), wp_set_link_cats(), wp_set_post_terms(), and wp_update_nav_menu_item().
wp_term_is_shared ($term_id)
Determine whether a term is shared between multiple taxonomies.
Shared taxonomy terms began to be split in 4.3, but failed cron tasks or other delays in upgrade routines may cause shared terms to remain.
Since
4.4.0
Parameters
int $term_id
Returns
bool
Definition at line 4365 of file wp-includes/taxonomy.php.
References $wpdb, and get_option().
Referenced by add_term_meta(), and update_term_meta().
wp_unique_term_slug ($slug, $term)
Will make slug unique, if it isn't already.
The $slug has to be unique global to every taxonomy, meaning that one taxonomy term can't have a matching slug with another taxonomy term. Each slug has to be globally unique for every taxonomy.
The way this works is that if the taxonomy that the term belongs to is hierarchical and has a parent, it will append that parent to the $slug.
If that still doesn't return an unique slug, then it try to append a number until it finds a number that is truly unique.
The only purpose for $term is for appending a parent, if one exists.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $slug The string that will be tried for a unique slug.
object $term The term object that the $slug will belong to.
Returns
string Will return a true unique slug.
Filter whether the proposed unique term slug is bad.
Since
4.3.0
Parameters
bool $needs_suffix Whether the slug needs to be made unique with a suffix.
string $slug The slug.
object $term Term object.
Filter the unique term slug.
Since
4.3.0
Parameters
string $slug Unique term slug.
object $term Term object.
string $original_slug Slug originally passed to the function for testing.
Definition at line 3082 of file wp-includes/taxonomy.php.
References $wpdb, apply_filters(), get_option(), get_term(), get_term_by(), is_taxonomy_hierarchical(), is_wp_error(), and term_exists().
Referenced by wp_insert_term(), and wp_update_term().
wp_update_term ($term_id, $taxonomy, $args = array())
Update term based on arguments provided.
The $args will indiscriminately override all values with the same field name. Care must be taken to not override important information need to update or update will fail (or perhaps create a new term, neither would be acceptable).
Defaults will set 'alias_of', 'description', 'parent', and 'slug' if not defined in $args already.
'alias_of' will create a term group, if it doesn't already exist, and update it for the $term.
If the 'slug' argument in $args is missing, then the 'name' in $args will be used. It should also be noted that if you set 'slug' and it isn't unique then a WP_Error will be passed back. If you don't pass any slug, then a unique one will be created for you.
For what can be overrode in $args, check the term scheme can contain and stay away from the term keys.
Since
2.3.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $term_id The ID of the term
string $taxonomy The context in which to relate the term to the object.
array | string $args Optional. Array of get_terms() arguments. Default empty array.
Returns
array|WP_Error Returns Term ID and Taxonomy Term ID
Filter the term parent.
Hook to this filter to see if it will cause a hierarchy loop.
Since
3.1.0
Parameters
int $parent ID of the parent term.
int $term_id Term ID.
string $taxonomy Taxonomy slug.
array $parsed_args An array of potentially altered update arguments for the given term.
array $args An array of update arguments for the given term.
Fires immediately before the given terms are edited.
Since
2.9.0
Parameters
int $term_id Term ID.
string $taxonomy Taxonomy slug.
Fires immediately after the given terms are edited.
Since
2.9.0
Parameters
int $term_id Term ID
string $taxonomy Taxonomy slug.
Fires immediate before a term-taxonomy relationship is updated.
Since
2.9.0
Parameters
int $tt_id Term taxonomy ID.
string $taxonomy Taxonomy slug.
Fires immediately after a term-taxonomy relationship is updated.
Since
2.9.0
Parameters
int $tt_id Term taxonomy ID.
string $taxonomy Taxonomy slug.
Fires after a term has been updated, but before the term cache has been cleaned.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Term taxonomy ID.
string $taxonomy Taxonomy slug.
Fires after a term in a specific taxonomy has been updated, but before the term cache has been cleaned.
The dynamic portion of the hook name, $taxonomy, refers to the taxonomy slug.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Term taxonomy ID.
This filter is documented in wp-includes/taxonomy.php
Fires after a term has been updated, and the term cache has been cleaned.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Term taxonomy ID.
string $taxonomy Taxonomy slug.
Fires after a term for a specific taxonomy has been updated, and the term cache has been cleaned.
The dynamic portion of the hook name, $taxonomy, refers to the taxonomy slug.
Since
2.3.0
Parameters
int $term_id Term ID.
int $tt_id Term taxonomy ID.
Definition at line 3189 of file wp-includes/taxonomy.php.
References $description, $name, $wpdb, __, _split_shared_term(), apply_filters(), clean_object_term_cache(), clean_term_cache(), do_action(), elseif, get_taxonomy(), get_term(), get_term_by(), is_wp_error(), sanitize_term(), sanitize_title(), taxonomy_exists(), term_exists(), wp_parse_args(), wp_slash(), wp_unique_term_slug(), and wp_unslash().
Referenced by WP_UnitTest_Factory_For_Term\update_object(), wp_ajax_inline_save_tax(), wp_check_term_hierarchy_for_loops(), wp_xmlrpc_server\wp_editTerm(), wp_insert_category(), wp_insert_term(), and wp_update_nav_menu_object().
wp_update_term_count ($terms, $taxonomy, $do_deferred = false)
Updates the amount of terms in taxonomy.
If there is a taxonomy callback applied, then it will be called for updating the count.
The default action is to count what the amount of terms have the relationship of term ID. Once that is done, then update the database.
Since
2.3.0
array $_deferred
Parameters
int | array $terms The term_taxonomy_id of the terms.
string $taxonomy The context of the term.
bool $do_deferred Whether to flush the deferred term counts too. Default false.
Returns
bool If no terms will return false, and if successful will return true.
Definition at line 3452 of file wp-includes/taxonomy.php.
References $tax, wp_defer_term_counting(), and wp_update_term_count_now().
Referenced by _update_term_count_on_transition_post_status(), wp_defer_term_counting(), wp_remove_object_terms(), and wp_set_object_terms().
wp_update_term_count_now ($terms, $taxonomy)
Perform term count update immediately.
Since
2.5.0
Parameters
array $terms The term_taxonomy_id of terms to update.
string $taxonomy The context of the term.
Returns
true Always true when complete.
Definition at line 3487 of file wp-includes/taxonomy.php.
References _update_generic_term_count(), _update_post_term_count(), clean_term_cache(), foreach, and get_taxonomy().
Referenced by wp_update_term_count().