GravityView: post.php File Reference
wp-includes/post.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
_add_post_type_submenus ()
Add submenus for post types.
_count_posts_cache_key ($type= 'post', $perm= '')
Return the cache key for wp_count_posts() based on the passed arguments.
_future_post_hook ($deprecated, $post)
Hook used to schedule publication for a post marked for the future.
_get_custom_object_labels ($object, $nohier_vs_hier_defaults)
Build an object with custom-something object (post type, taxonomy) labels out of a custom-something object.
_get_last_post_time ($timezone, $field, $post_type= 'any')
Get the timestamp of the last time any post was modified or published.
_page_traverse_name ($page_id, &$children, &$result)
Traverse and return all the nested children post names of a root page.
_post_type_meta_capabilities ($capabilities=null)
Store or return a list of post type meta caps for map_meta_cap().
_prime_post_caches ($ids, $update_term_cache=true, $update_meta_cache=true)
Adds any posts from the given ids to the cache that do not already exist in cache.
_publish_post_hook ($post_id)
Hook to schedule pings and enclosures when a post is published.
_reset_front_page_settings_for_post ($post_id)
Reset the page_on_front, show_on_front, and page_for_post settings when a linked page is deleted or trashed.
_transition_post_status ($new_status, $old_status, $post)
Hook for managing future post transitions to published.
_truncate_post_slug ($slug, $length=200)
Truncate a post slug.
_update_term_count_on_transition_post_status ($new_status, $old_status, $post)
Update the custom taxonomies' term counts when a post's status is changed.
_wp_relative_upload_path ($path)
Return relative path to an uploaded file.
add_ping ($post_id, $uri)
Add a URL to those already pinged.
add_post_meta ($post_id, $meta_key, $meta_value, $unique=false)
Add meta data field to a post.
add_post_type_support ($post_type, $feature)
Register support of certain features for a post type.
check_and_publish_future_post ($post_id)
Publish future post and make sure post ID has future post status.
clean_attachment_cache ($id, $clean_terms=false)
Will clean the attachment in the cache.
clean_post_cache ($post)
Will clean the post in the cache.
create_initial_post_types ()
Creates the initial post types when 'init' action is fired.
delete_post_meta ($post_id, $meta_key, $meta_value= '')
Remove metadata matching criteria from a post.
delete_post_meta_by_key ($post_meta_key)
Delete everything from post meta matching meta key.
delete_post_thumbnail ($post)
Remove a post thumbnail.
get_all_page_ids ()
Get a list of page IDs.
get_all_post_type_supports ($post_type)
Get all the post type features.
get_attached_file ($attachment_id, $unfiltered=false)
Retrieve attached file path based on attachment ID.
get_children ($args= '', $output=OBJECT)
Retrieve all children of the post parent ID.
get_enclosed ($post_id)
Retrieve enclosures already enclosed for a post.
get_extended ($post)
Get extended entry info ().
get_lastpostdate ($timezone= 'server', $post_type= 'any')
Retrieve the date that the last post was published.
get_lastpostmodified ($timezone= 'server', $post_type= 'any')
Get the timestamp of the last time any post was modified.
get_page ($page, $output=OBJECT, $filter= 'raw')
Retrieves page data given a page ID or page object.
get_page_by_path ($page_path, $output=OBJECT, $post_type= 'page')
Retrieves a page given its path.
get_page_by_title ($page_title, $output=OBJECT, $post_type= 'page')
Retrieve a page given its title.
get_page_children ($page_id, $pages)
Identify descendants of a given page ID in a list of page objects.
get_page_hierarchy (&$pages, $page_id=0)
Order the pages with children under parents in a flat list.
get_page_statuses ()
Retrieve all of the WordPress support page statuses.
get_page_uri ($page)
Build the URI path for a page.
get_pages ($args=array())
Retrieve a list of pages.
get_post ($post=null, $output=OBJECT, $filter= 'raw')
Retrieves post data given a post ID or post object.
get_post_ancestors ($post)
Retrieve ancestors of a post.
get_post_custom ($post_id=0)
Retrieve post meta fields, based on post ID.
get_post_custom_keys ($post_id=0)
Retrieve meta field names for a post.
get_post_custom_values ($key= '', $post_id=0)
Retrieve values for a custom post field.
get_post_field ($field, $post, $context= 'display')
Retrieve data from a post field based on Post ID.
get_post_meta ($post_id, $key= '', $single=false)
Retrieve post meta field for a post.
get_post_mime_type ($ID= '')
Retrieve the mime type of an attachment based on the ID.
get_post_mime_types ()
Get default post mime types.
get_post_stati ($args=array(), $output= 'names', $operator= 'and')
Get a list of post statuses.
get_post_status ($ID= '')
Retrieve the post status based on the Post ID.
get_post_status_object ($post_status)
Retrieve a post status object by name.
get_post_statuses ()
Retrieve all of the WordPress supported post statuses.
get_post_type ($post=null)
Retrieve the post type of the current post or of a given post.
get_post_type_capabilities ($args)
Build an object with all post type capabilities out of a post type object.
get_post_type_labels ($post_type_object)
Build an object with all post type labels out of a post type object.
get_post_type_object ($post_type)
Retrieve a post type object by name.
get_post_types ($args=array(), $output= 'names', $operator= 'and')
Get a list of all registered post type objects.
get_posts ($args=null)
Retrieve list of latest posts or posts matching criteria.
get_posts_by_author_sql ($post_type, $full=true, $post_author=null, $public_only=false)
Retrieve the post SQL based on capability, author, and type.
get_private_posts_cap_sql ($post_type)
Retrieve the private post SQL based on capability.
get_pung ($post_id)
Retrieve URLs already pinged for a post.
get_to_ping ($post_id)
Retrieve URLs that need to be pinged.
is_local_attachment ($url)
Check if the attachment URI is local one and is really an attachment.
is_post_type_hierarchical ($post_type)
Whether the post type is hierarchical.
is_post_type_viewable ($post_type_object)
Determines whether a post type is considered "viewable".
is_sticky ($post_id=0)
Check if post is sticky.
post_type_exists ($post_type)
Check if a post type is registered.
post_type_supports ($post_type, $feature)
Check a post type's support for a given feature.
register_post_status ($post_status, $args=array())
Register a post status.
register_post_type ($post_type, $args=array())
Register a post type.
remove_post_type_support ($post_type, $feature)
Remove support for a feature from a post type.
sanitize_post ($post, $context= 'display')
Sanitize every post field.
sanitize_post_field ($field, $value, $post_id, $context= 'display')
Sanitize post field based on context.
set_post_thumbnail ($post, $thumbnail_id)
Set a post thumbnail.
set_post_type ($post_id=0, $post_type= 'post')
Update the post type for the post ID.
stick_post ($post_id)
Make a post sticky.
trackback_url_list ($tb_list, $post_id)
Do trackbacks for a list of URLs.
unstick_post ($post_id)
Un-stick a post.
update_attached_file ($attachment_id, $file)
Update attachment file path based on attachment ID.
update_post_cache (&$posts)
Updates posts in cache.
update_post_caches (&$posts, $post_type= 'post', $update_term_cache=true, $update_meta_cache=true)
Call major cache updating functions for list of Post objects.
update_post_meta ($post_id, $meta_key, $meta_value, $prev_value= '')
Update post meta field based on post ID.
update_postmeta_cache ($post_ids)
Updates metadata cache for list of post IDs.
wp_add_post_tags ($post_id=0, $tags= '')
Add tags to a post.
wp_attachment_is ($type, $post_id=0)
Verifies an attachment is of a given type.
wp_attachment_is_image ($post=0)
Checks if the attachment is an image.
wp_check_for_changed_slugs ($post_id, $post, $post_before)
Check for changed slugs for published post objects and save the old slug.
wp_check_post_hierarchy_for_loops ($post_parent, $post_ID)
Check the given subset of the post hierarchy for hierarchy loops.
wp_count_attachments ($mime_type= '')
Count number of attachments for the mime type(s).
wp_count_posts ($type= 'post', $perm= '')
Count number of posts of a post type and if user has permissions to view.
wp_delete_attachment ($post_id, $force_delete=false)
Trash or delete an attachment.
wp_delete_auto_drafts ()
Delete auto-drafts for new posts that are > 7 days old.
wp_delete_post ($postid=0, $force_delete=false)
Trash or delete a post or page.
wp_get_attachment_metadata ($post_id=0, $unfiltered=false)
Retrieve attachment meta field for attachment ID.
wp_get_attachment_thumb_file ($post_id=0)
Retrieve thumbnail for an attachment.
wp_get_attachment_thumb_url ($post_id=0)
Retrieve URL for an attachment thumbnail.
wp_get_attachment_url ($post_id=0)
Retrieve the URL for an attachment.
wp_get_post_categories ($post_id=0, $args=array())
Retrieve the list of categories for a post.
wp_get_post_parent_id ($post_ID)
Return the post's parent's post_ID.
wp_get_post_tags ($post_id=0, $args=array())
Retrieve the tags for a post.
wp_get_post_terms ($post_id=0, $taxonomy= 'post_tag', $args=array())
Retrieve the terms for a post.
wp_get_recent_posts ($args=array(), $output=ARRAY_A)
Retrieve a number of recent posts.
wp_insert_attachment ($args, $file=false, $parent=0)
Insert an attachment.
wp_insert_post ($postarr, $wp_error=false)
Insert or update a post.
wp_match_mime_types ($wildcard_mime_types, $real_mime_types)
Check a MIME-Type against a list.
wp_mime_type_icon ($mime=0)
Retrieve the icon for a MIME type.
wp_post_mime_type_where ($post_mime_types, $table_alias= '')
Convert MIME types into SQL.
wp_publish_post ($post)
Publish a post by transitioning the post status.
wp_set_post_categories ($post_ID=0, $post_categories=array(), $append=false)
Set categories for a post.
wp_set_post_tags ($post_id=0, $tags= '', $append=false)
Set the tags for a post.
wp_set_post_terms ($post_id=0, $tags= '', $taxonomy= 'post_tag', $append=false)
Set the terms for a post.
wp_transition_post_status ($new_status, $old_status, $post)
Fires actions related to the transitioning of a post's status.
wp_trash_post ($post_id=0)
Move a post or page to the Trash.
wp_trash_post_comments ($post=null)
Moves comments for a post to the trash.
wp_unique_post_slug ($slug, $post_ID, $post_status, $post_type, $post_parent)
Computes a unique slug for the post, when given the desired slug and some post details.
wp_untrash_post ($post_id=0)
Restore a post or page from the Trash.
wp_untrash_post_comments ($post=null)
Restore comments for a post from the trash.
wp_update_attachment_metadata ($post_id, $data)
Update metadata for an attachment.
wp_update_post ($postarr=array(), $wp_error=false)
Update a post with new post data.
Function Documentation
_add_post_type_submenus ()
Add submenus for post types.
private
Since
3.1.0
Definition at line 1460 of file wp-includes/post.php.
References add_submenu_page(), get_post_type_object(), and get_post_types().
_count_posts_cache_key ($type = 'post', $perm = '')
Return the cache key for wp_count_posts() based on the passed arguments.
Since
3.9.0
Parameters
string $type Optional. Post type to retrieve count Default 'post'.
string $perm Optional. 'readable' or empty. Default empty.
Returns
string The cache key.
Definition at line 2092 of file wp-includes/post.php.
References $post_type_object, current_user_can(), get_current_user_id(), and get_post_type_object().
Referenced by _transition_post_status(), and wp_count_posts().
_future_post_hook ($deprecated, $post)
Hook used to schedule publication for a post marked for the future.
The $post properties used and must exist are 'ID' and 'post_date_gmt'.
Since
2.3.0 private
Parameters
int $deprecated Not used. Can be set to null. Never implemented. Not marked as deprecated with _deprecated_argument() as it conflicts with wp_transition_post_status() and the default filter for {
See also
_future_post_hook()}.
Parameters
WP_Post $post Post object.
Definition at line 5710 of file wp-includes/post.php.
References $post, get_gmt_from_date(), wp_clear_scheduled_hook(), and wp_schedule_single_event().
_get_custom_object_labels ($object, $nohier_vs_hier_defaults)
Build an object with custom-something object (post type, taxonomy) labels out of a custom-something object.
Since
3.0.0 private
Parameters
object $object A custom-something object.
array $nohier_vs_hier_defaults Hierarchical vs non-hierarchical default labels.
Returns
object Object containing labels for the given custom-something object.
Definition at line 1422 of file wp-includes/post.php.
References $value, if, object, and return.
Referenced by get_post_type_labels(), and get_taxonomy_labels().
_get_last_post_time ($timezone, $field, $post_type = 'any')
Get the timestamp of the last time any post was modified or published.
Since
3.1.0
4.4.0 The $post_type argument was added. private
wpdb $wpdb WordPress database abstraction object.
Parameters
string $timezone The timezone for the timestamp. See get_lastpostdate(). for information on accepted values.
string $field Post field to check. Accepts 'date' or 'modified'.
string $post_type Optional. The post type to check. Default 'any'.
Returns
string|false The timestamp.
Definition at line 5421 of file wp-includes/post.php.
References $field, $post_type, $wpdb, date, get_post_types(), sanitize_key(), wp_cache_get(), and wp_cache_set().
Referenced by get_lastpostdate(), and get_lastpostmodified().
_page_traverse_name ($page_id, & $children, & $result)
Traverse and return all the nested children post names of a root page.
$children contains parent-children relations
Since
2.9.0
See also
_page_traverse_name()
Parameters
int $page_id Page ID.
array $children Parent-children relations, passed by reference.
array $result Result, passed by reference.
Definition at line 4274 of file wp-includes/post.php.
Referenced by get_page_hierarchy().
_post_type_meta_capabilities ($capabilities = null)
Store or return a list of post type meta caps for map_meta_cap().
Since
3.1.0 private
array $meta_caps
Parameters
array | void $capabilities Post type meta capabilities.
Definition at line 1300 of file wp-includes/post.php.
References $custom, and null.
Referenced by get_post_type_capabilities(), and map_meta_cap().
_prime_post_caches ($ids, $update_term_cache = true, $update_meta_cache = true)
Adds any posts from the given ids to the cache that do not already exist in cache.
Since
3.4.0 private
See also
update_post_caches()
wpdb $wpdb WordPress database abstraction object.
Parameters
array $ids ID list.
bool $update_term_cache Optional. Whether to update the term cache. Default true.
bool $update_meta_cache Optional. Whether to update the meta cache. Default true.
Definition at line 5894 of file wp-includes/post.php.
References $wpdb, _get_non_cached_ids(), and update_post_caches().
Referenced by WP_Posts_List_Table\_display_rows_hierarchical(), WP_Comment_Query\get_comments(), WP_Query\get_posts(), update_post_thumbnail_cache(), and WP_Widget_Recent_Comments\widget().
_publish_post_hook ($post_id)
Hook to schedule pings and enclosures when a post is published.
Uses XMLRPC_REQUEST and WP_IMPORTING constants.
Since
2.3.0 private
Parameters
int $post_id The ID in the database table of the post being published.
Fires when _publish_post_hook() is called during an XML-RPC request.
Since
2.1.0
Parameters
int $post_id Post ID.
Definition at line 5725 of file wp-includes/post.php.
References $post_id, add_post_meta(), do_action(), get_option(), and wp_schedule_single_event().
_reset_front_page_settings_for_post ($post_id)
Reset the page_on_front, show_on_front, and page_for_post settings when a linked page is deleted or trashed.
Also ensures the post is no longer sticky.
Since
3.7.0 private
Parameters
int $post_id Post ID.
Definition at line 2491 of file wp-includes/post.php.
References $post, $post_id, delete_option(), get_option(), get_post(), unstick_post(), and update_option().
_transition_post_status ($new_status, $old_status, $post)
Hook for managing future post transitions to published.
Since
2.3.0 private
See also
wp_clear_scheduled_hook() wpdb $wpdb WordPress database abstraction object.
Parameters
string $new_status New post status.
string $old_status Previous post status.
WP_Post $post Post object.
Fires when a post's status is transitioned from private to published.
Since
1.5.0
Parameters
int $post_id Post ID.
Definition at line 5659 of file wp-includes/post.php.
References $post, $wpdb, _count_posts_cache_key(), do_action(), get_permalink(), get_the_guid(), wp_cache_delete(), and wp_clear_scheduled_hook().
_truncate_post_slug ($slug, $length = 200)
Truncate a post slug.
Since
3.6.0 private
See also
utf8_uri_encode()
Parameters
string $slug The slug to truncate.
int $length Optional. Max length of the slug. Default 200 (characters).
Returns
string The truncated slug.
Definition at line 3690 of file wp-includes/post.php.
References utf8_uri_encode().
Referenced by wp_unique_post_slug().
_update_term_count_on_transition_post_status ($new_status, $old_status, $post)
Update the custom taxonomies' term counts when a post's status is changed.
For example, default posts term counts (for custom taxonomies) don't include private / draft posts.
Since
3.3.0 private
Parameters
string $new_status New post status.
string $old_status Old post status.
WP_Post $post Post object.
Definition at line 5872 of file wp-includes/post.php.
References $post, get_object_taxonomies(), wp_get_object_terms(), and wp_update_term_count().
_wp_relative_upload_path ($path)
Return relative path to an uploaded file.
The path is relative to the current upload dir.
Since
2.9.0
Parameters
string $path Full path to the file.
Returns
string Relative path on success, unchanged path on failure.
Filter the relative path to an uploaded file.
Since
2.9.0
Parameters
string $new_path Relative path to the file.
string $path Full path to the file.
Definition at line 248 of file wp-includes/post.php.
References $path, apply_filters(), str_replace, and wp_upload_dir().
Referenced by update_attached_file(), wp_generate_attachment_metadata(), wp_restore_image(), and wp_save_image().
add_ping ($post_id, $uri)
Add a URL to those already pinged.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Post ID.
string $uri Ping URI.
Returns
int|false How many rows were updated.
Filter the new ping URL to add for the given post.
Since
2.0.0
Parameters
string $new New ping URL to add.
Definition at line 3896 of file wp-includes/post.php.
References $post_id, $wpdb, apply_filters(), and wp_unslash().
Referenced by pingback().
add_post_meta ($post_id, $meta_key, $meta_value, $unique = false)
Add meta data field to a post.
Post meta data is called "Custom Fields" on the Administration Screen.
Since
1.5.0
Parameters
int $post_id Post ID.
string $meta_key Metadata name.
mixed $meta_value Metadata value. Must be serializable if non-scalar.
bool $unique Optional. Whether the same key should not be added. Default false.
Returns
int|false Meta ID on success, false on failure.
Definition at line 1668 of file wp-includes/post.php.
References $post_id, add_metadata(), and wp_is_post_revision().
Referenced by _publish_post_hook(), wp_xmlrpc_server\add_enclosure_if_new(), add_meta(), GravityView_Admin_Duplicate_View\copy_view_meta_info(), GravityView_Admin_Duplicate_View\create_duplicate(), GFFormsModel\create_post(), do_enclose(), GravityView_Admin_Views\save_postdata(), wp_xmlrpc_server\set_custom_fields(), wp_check_for_changed_slugs(), wp_generate_attachment_metadata(), wp_insert_post(), wp_trash_post(), wp_trash_post_comments(), and wp_write_post().
add_post_type_support ($post_type, $feature)
Register support of certain features for a post type.
All core features are directly associated with a functional area of the edit screen, such as the editor or a meta box. Features include: 'title', 'editor', 'comments', 'revisions', 'trackbacks', 'author', 'excerpt', 'page-attributes', 'thumbnail', 'custom-fields', and 'post-formats'.
Additionally, the 'revisions' feature dictates whether the post type will store revisions, and the 'comments' feature dictates whether the comments count will show on the edit screen.
Since
3.0.0
array $_wp_post_type_features
Parameters
string $post_type The post type for which to add the feature.
string | array $feature The feature being added, accepts an array of feature strings or a single string.
Definition at line 1490 of file wp-includes/post.php.
References $post_type.
Referenced by create_initial_post_types(), and register_post_type().
check_and_publish_future_post ($post_id)
Publish future post and make sure post ID has future post status.
Invoked by cron 'publish_future_post' event. This safeguard prevents cron from publishing drafts, etc.
Since
2.5.0
Parameters
int | WP_Post $post_id Post ID or post object.
Definition at line 3515 of file wp-includes/post.php.
References $post, $post_id, get_post(), wp_clear_scheduled_hook(), wp_publish_post(), and wp_schedule_single_event().
clean_attachment_cache ($id, $clean_terms = false)
Will clean the attachment in the cache.
Cleaning means delete from the cache. Optionally will clean the term object cache associated with the attachment ID.
This function will not run if $_wp_suspend_cache_invalidation is not empty.
Since
3.0.0
bool $_wp_suspend_cache_invalidation
Parameters
int $id The attachment ID in the cache to clean.
bool $clean_terms Optional. Whether to clean terms cache. Default false.
Fires after the given attachment's cache is cleaned.
Since
3.0.0
Parameters
int $id Attachment ID.
Definition at line 5618 of file wp-includes/post.php.
References $id, clean_object_term_cache(), do_action(), and wp_cache_delete().
Referenced by wp_media_attach_action().
clean_post_cache ($post)
Will clean the post in the cache.
Cleaning means delete from the cache of the post. Will call to clean the term object cache associated with the post ID.
This function not run if $_wp_suspend_cache_invalidation is not empty. See wp_suspend_cache_invalidation().
Since
2.0.0
bool $_wp_suspend_cache_invalidation
Parameters
int | WP_Post $post Post ID or post object to remove from the cache.
Fires immediately after the given post's cache is cleaned.
Since
2.5.0
Parameters
int $post_id Post ID.
WP_Post $post Post object.
Fires immediately after the given page's cache is cleaned.
Since
2.5.0
Parameters
int $post_id Post ID.
Definition at line 5497 of file wp-includes/post.php.
References $post, clean_object_term_cache(), do_action(), get_post(), wp_cache_delete(), and wp_cache_set().
Referenced by WP_Posts_List_Table\_display_rows_hierarchical(), clean_page_cache(), set_post_type(), wp_delete_attachment(), wp_delete_post(), wp_delete_user(), wp_insert_post(), wp_publish_post(), and wp_update_comment_count_now().
create_initial_post_types ()
Creates the initial post types when 'init' action is fired.
Since
2.9.0
Definition at line 18 of file wp-includes/post.php.
References __, _n_noop(), _x, add_post_type_support(), register_post_status(), and register_post_type().
Referenced by WP_UnitTestCase\reset_post_types().
delete_post_meta ($post_id, $meta_key, $meta_value = '')
Remove metadata matching criteria from a post.
You can match based on the key, or key and value. Removing based on key and value, will keep from removing duplicate metadata with the same key. It also allows removing all metadata matching key, if needed.
Since
1.5.0
Parameters
int $post_id Post ID.
string $meta_key Metadata name.
mixed $meta_value Optional. Metadata value. Must be serializable if non-scalar. Default empty.
Returns
bool True on success, false on failure.
Definition at line 1691 of file wp-includes/post.php.
References $post_id, delete_metadata(), and wp_is_post_revision().
Referenced by Custom_Image_Header\ajax_header_remove(), GravityView_Admin_Duplicate_View\create_duplicate(), WP_Embed\delete_oembed_caches(), delete_post_thumbnail(), GravityView_Admin_Views\save_postdata(), set_post_thumbnail(), update_attached_file(), wp_check_for_changed_slugs(), wp_delete_attachment(), wp_delete_post(), wp_scheduled_delete(), wp_untrash_post(), wp_untrash_post_comments(), wp_update_attachment_metadata(), and wp_update_nav_menu_item().
delete_post_meta_by_key ($post_meta_key)
Delete everything from post meta matching meta key.
Since
2.3.0
Parameters
string $post_meta_key Key to search for when deleting.
Returns
bool Whether the post meta key was deleted from the database.
Definition at line 1749 of file wp-includes/post.php.
References delete_metadata(), and null.
delete_post_thumbnail ($post)
Remove a post thumbnail.
Since
3.3.0
Parameters
int | WP_Post $post Post ID or post object where thumbnail should be removed from.
Returns
bool True on success, false on failure.
Definition at line 5834 of file wp-includes/post.php.
References $post, delete_post_meta(), and get_post().
Referenced by wp_xmlrpc_server\_insert_post(), wp_xmlrpc_server\mw_editPost(), and wp_ajax_set_post_thumbnail().
get_all_page_ids ()
Get a list of page IDs.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Returns
array List of page IDs.
Definition at line 4045 of file wp-includes/post.php.
References $wpdb, wp_cache_add(), and wp_cache_get().
get_all_post_type_supports ($post_type)
Get all the post type features.
Since
3.4.0
array $_wp_post_type_features
Parameters
string $post_type The post type.
Returns
array Post type supports list.
Definition at line 1528 of file wp-includes/post.php.
References $post_type.
Referenced by wp_xmlrpc_server\_prepare_post_type().
get_attached_file ($attachment_id, $unfiltered = false)
Retrieve attached file path based on attachment ID.
By default the path will go through the 'get_attached_file' filter, but passing a true to the $unfiltered argument of get_attached_file() will return the file path unfiltered.
The function works by getting the single post meta name, named '_wp_attached_file' and returning it. This is a convenience function to prevent looking up the meta name and provide a mechanism for sending the attached filename through a filter.
Since
2.0.0
Parameters
int $attachment_id Attachment ID.
bool $unfiltered Optional. Whether to apply filters. Default false.
Returns
string|false The file path to where the attached file should be, false otherwise.
Filter the attached file based on the given ID.
Since
2.1.0
Parameters
string $file Path to attached file.
int $attachment_id Attachment ID.
Definition at line 187 of file wp-includes/post.php.
References $file, apply_filters(), get_post_meta(), and wp_upload_dir().
Referenced by _copy_image_file(), _load_image_to_edit_path(), attachment_submitbox_metadata(), WP_Media_List_Table\column_title(), get_attachment_icon_src(), get_attachment_taxonomies(), get_media_item(), Custom_Image_Header\step_2(), Custom_Image_Header\step_3(), wp_attachment_is(), wp_crop_image(), wp_delete_attachment(), wp_get_attachment_thumb_file(), wp_load_image(), wp_maybe_generate_attachment_metadata(), wp_mime_type_icon(), wp_prepare_attachment_for_js(), wp_restore_image(), and wp_save_image().
get_children ($args = '', $output = OBJECT)
Retrieve all children of the post parent ID.
Normally, without any enhancements, the children would apply to pages. In the context of the inner workings of WordPress, pages, posts, and attachments share the same table, so therefore the functionality could apply to any one of them. It is then noted that while this function does not work on posts, it does not mean that it won't work on posts. It is recommended that you know what context you wish to retrieve the children of.
Attachments may also be made the child of a post, so if that is an accurate statement (which needs to be verified), it would then be possible to get all of the attachments for a post. Attachments have since changed since version 2.5, so this is most likely inaccurate, but serves generally as an example of what is possible.
The arguments listed as defaults are for this function and also of the get_posts() function. The arguments are combined with the get_children defaults and are then passed to the get_posts() function, which accepts additional arguments. You can replace the defaults in this function, listed below and the additional arguments listed in the get_posts() function.
The 'post_parent' is the most important argument and important attention needs to be paid to the $args parameter. If you pass either an object or an integer (number), then just the 'post_parent' is grabbed and everything else is lost. If you don't specify any arguments, then it is assumed that you are in The Loop and the post parent will be grabbed for from the current post.
The 'post_parent' argument is the ID to get the children. The 'numberposts' is the amount of posts to retrieve that has a default of '-1', which is used to get all of the posts. Giving a number higher than 0 will only retrieve that amount of posts.
The 'post_type' and 'post_status' arguments can be used to choose what criteria of posts to retrieve. The 'post_type' can be anything, but WordPress post types are 'post', 'pages', and 'attachments'. The 'post_status' argument will accept any post status within the write administration panels.
Since
2.0.0
See also
get_posts()
WP_Post $post
Parameters
mixed $args Optional. User defined arguments for replacing the defaults. Default empty.
string $output Optional. Constant for return type. Accepts OBJECT, ARRAY_A, ARRAY_N. Default OBJECT.
Returns
array Array of children, where the type of each element is determined by $output parameter. Empty array on failure.
Definition at line 320 of file wp-includes/post.php.
References $GLOBALS, $output, ARRAY_A, ARRAY_N, elseif, get_posts(), OBJECT, update_post_cache(), and wp_parse_args().
Referenced by adjacent_image_link(), gallery_shortcode(), get_attached_media(), get_media_items(), wp_get_post_revisions(), and wp_playlist_shortcode().
get_enclosed ($post_id)
Retrieve enclosures already enclosed for a post.
Since
1.5.0
Parameters
int $post_id Post ID.
Returns
array List of enclosures.
Filter the list of enclosures already enclosed for the given post.
Since
2.0.0
Parameters
array $pung Array of enclosures for the given post.
int $post_id Post ID.
Definition at line 3926 of file wp-includes/post.php.
References $post_id, apply_filters(), and get_post_custom().
Referenced by do_enclose().
get_extended ($post)
Get extended entry info ().
There should not be any space after the second dash and before the word 'more'. There can be text or space(s) after the word 'more', but won't be referenced.
The returned array has 'main', 'extended', and 'more_text' keys. Main has the text before the . The 'extended' key has the content after the comment. The 'more_text' key has the custom "Read More" text.
Since
1.0.0
Parameters
string $post Post content.
Returns
array Post before ('main'), after ('extended'), and custom read more ('more_text').
Definition at line 389 of file wp-includes/post.php.
References $post.
Referenced by wp_xmlrpc_server\_prepare_page(), wp_xmlrpc_server\mw_getPost(), and wp_xmlrpc_server\mw_getRecentPosts().
get_lastpostdate ($timezone = 'server', $post_type = 'any')
Retrieve the date that the last post was published.
The server timezone is the default and is the difference between GMT and server time. The 'blog' value is the date when the last post was posted. The 'gmt' is when the last post was posted in GMT formatted date.
Since
0.71
4.4.0 The $post_type argument was added.
Parameters
string $timezone Optional. The timezone for the timestamp. Accepts 'server', 'blog', or 'gmt'. 'server' uses the server's internal timezone. 'blog' uses the post_modified field, which proxies to the timezone set for the site. 'gmt' uses the post_modified_gmt field. Default 'server'.
string $post_type Optional. The post type to check. Default 'any'.
Returns
string The date of the last post.
Filter the date the last post was published.
Since
2.3.0
Parameters
string $date Date the last post was published.
string $timezone Location to use for getting the post published date. See {
See also
get_lastpostdate()} for accepted $timezone values.
Definition at line 5341 of file wp-includes/post.php.
References $post_type, _get_last_post_time(), and apply_filters().
Referenced by get_lastpostmodified().
get_lastpostmodified ($timezone = 'server', $post_type = 'any')
Get the timestamp of the last time any post was modified.
The server timezone is the default and is the difference between GMT and server time. The 'blog' value is just when the last post was modified. The 'gmt' is when the last post was modified in GMT time.
Since
1.2.0
4.4.0 The $post_type argument was added.
Parameters
string $timezone Optional. The timezone for the timestamp. See {
See also
get_lastpostdate()} for information on accepted values. Default 'server'.
Parameters
string $post_type Optional. The post type to check. Default 'any'.
Returns
string The timestamp.
Pre-filter the return value of get_lastpostmodified() before the query is run.
Since
4.4.0
Parameters
string $lastpostmodified Date the last post was modified. Returning anything other than false will short-circuit the function.
string $timezone Location to use for getting the post modified date. See {
See also
get_lastpostdate()} for accepted $timezone values.
Parameters
string $post_type The post type to check.
Filter the date the last post was modified.
Since
2.3.0
Parameters
string $lastpostmodified Date the last post was modified.
string $timezone Location to use for getting the post modified date. See {
See also
get_lastpostdate()} for accepted $timezone values.
Definition at line 5370 of file wp-includes/post.php.
References $post_type, _get_last_post_time(), apply_filters(), and get_lastpostdate().
Referenced by WP\send_headers().
get_page ($page, $output = OBJECT, $filter = 'raw')
Retrieves page data given a page ID or page object.
Use get_post() instead of get_page().
Since
1.5.1
Parameters
mixed $page Page object or page ID. Passed by reference.
string $output Optional. What to output. Accepts OBJECT, ARRAY_A, or ARRAY_N. Default OBJECT.
string $filter Optional. How the return value should be filtered. Accepts 'raw', 'edit', 'db', 'display'. Default 'raw'.
Returns
WP_Post|array|null WP_Post on success or null on failure.
Definition at line 4072 of file wp-includes/post.php.
References $output, $page, and get_post().
Referenced by GFForms\enqueue_admin_scripts().
get_page_by_path ($page_path, $output = OBJECT, $post_type = 'page')
Retrieves a page given its path.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $page_path Page path.
string $output Optional. Output type. Accepts OBJECT, ARRAY_N, or ARRAY_A. Default OBJECT.
string | array $post_type Optional. Post type or array of post types. Default 'page'.
Returns
WP_Post|array|void WP_Post on success.
Definition at line 4089 of file wp-includes/post.php.
References $count, $output, $page, $post_type, $wpdb, esc_sql(), get_post(), OBJECT_K, and str_replace.
Referenced by WP_Query\get_posts(), WP_Query\is_page(), WP_Query\is_single(), WP_Query\parse_query(), WP\parse_request(), url_to_postid(), and wp_resolve_numeric_slug_conflicts().
get_page_by_title ($page_title, $output = OBJECT, $post_type = 'page')
Retrieve a page given its title.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $page_title Page title
string $output Optional. Output type. OBJECT, ARRAY_N, or ARRAY_A. Default OBJECT.
string | array $post_type Optional. Post type or array of post types. Default 'page'.
Returns
WP_Post|array|void WP_Post on success or null on failure
Definition at line 4164 of file wp-includes/post.php.
References $output, $page, $post_type, $wpdb, esc_sql(), and get_post().
get_page_children ($page_id, $pages)
Identify descendants of a given page ID in a list of page objects.
Descendants are identified from the $pages array passed to the function. No database queries are performed.
Since
1.5.1
Parameters
int $page_id Page ID.
array $pages List of page objects from which descendants should be identified.
Returns
array List of page children.
Definition at line 4203 of file wp-includes/post.php.
References $page.
Referenced by get_pages().
get_page_hierarchy (& $pages, $page_id = 0)
Order the pages with children under parents in a flat list.
It uses auxiliary structure to hold parent-children relationships and runs in O(N) complexity
Since
2.0.0
Parameters
array $pages Posts array, passed by reference.
int $page_id Optional. Parent page ID. Default 0.
Returns
array A list arranged by hierarchy. Children immediately follow their parents.
Definition at line 4244 of file wp-includes/post.php.
References _page_traverse_name().
Referenced by WP_Rewrite\page_uri_index().
get_page_statuses ()
Retrieve all of the WordPress support page statuses.
Pages have a limited set of valid status values, this provides the post_status values and descriptions.
Since
2.5.0
Returns
array List of page statuses.
Definition at line 617 of file wp-includes/post.php.
References __.
Referenced by wp_xmlrpc_server\wp_getPageStatusList().
get_page_uri ($page)
Build the URI path for a page.
Sub pages will be in the "directory" under the parent page post name.
Since
1.5.0
Parameters
WP_Post | object | int $page Page object or page ID.
Returns
string|false Page URI, false on error.
Filter the URI for a page.
Since
4.4.0
Parameters
string $uri Page URI.
WP_Post $page Page object.
Definition at line 4293 of file wp-includes/post.php.
References $page, apply_filters(), and get_post().
Referenced by _get_page_link(), get_post_permalink(), get_sample_permalink(), and WP_Rewrite\page_uri_index().
get_pages ($args = array())
Retrieve a list of pages.
wpdb $wpdb WordPress database abstraction object.
Since
1.5.0
Parameters
array | string $args { Optional. Array or string of arguments to retrieve pages.
int $child_of Page ID to return child and grandchild pages of. Note: The value of $hierarchical has no bearing on whether $child_of returns hierarchical results. Default 0, or no restriction. string $sort_order How to sort retrieved pages. Accepts 'ASC', 'DESC'. Default 'ASC'. string $sort_column What columns to sort pages by, comma-separated. Accepts 'post_author', 'post_date', 'post_title', 'post_name', 'post_modified', 'menu_order', 'post_modified_gmt', 'post_parent', 'ID', 'rand', 'comment_count'. 'post_' can be omitted for any values that start with it. Default 'post_title'. bool $hierarchical Whether to return pages hierarchically. If false in conjunction with $child_of also being false, both arguments will be disregarded. Default true. array $exclude Array of page IDs to exclude. Default empty array. array $include Array of page IDs to include. Cannot be used with $child_of, $parent, $exclude, $meta_key, $meta_value, or $hierarchical. Default empty array. string $meta_key Only include pages with this meta key. Default empty. string $meta_value Only include pages with this meta value. Requires $meta_key. Default empty. string $authors A comma-separated list of author IDs. Default empty. int $parent Page ID to return direct children of. Default -1, or no restriction. string|array $exclude_tree Comma-separated string or array of page IDs to exclude. Default empty array. int $number The number of pages to return. Default 0, or all pages. int $offset The number of pages to skip before returning. Requires $number. Default 0. string $post_type The post type to query. Default 'page'. string $post_status A comma-separated list of post status types to include. Default 'publish'. }
Returns
array|false List of pages matching defaults or $args.
This filter is documented in wp-includes/post.php
This filter is documented in wp-includes/post.php
Filter the retrieved list of pages.
Since
2.1.0
Parameters
array $pages List of pages to retrieve.
array $r Array of get_pages() arguments.
Definition at line 4363 of file wp-includes/post.php.
References $i, $id, $page, $wpdb, apply_filters(), elseif, get_page_children(), get_post_stati(), get_post_types(), sanitize_post(), update_post_cache(), wp_array_slice_assoc(), wp_cache_get(), wp_cache_set(), wp_parse_args(), wp_parse_id_list(), and wp_unslash().
Referenced by WP_Posts_List_Table\_display_rows_hierarchical(), get_body_class(), WP_Customize_Manager\register_controls(), wp_dropdown_pages(), and wp_list_pages().
get_post ($post = null, $output = OBJECT, $filter = 'raw')
Retrieves post data given a post ID or post object.
See sanitize_post() for optional $filter values. Also, the parameter $post, must be given as a variable, since it is passed by reference.
Since
1.5.1
WP_Post $post
Parameters
int | WP_Post | null $post Optional. Post ID or post object. Defaults to global $post.
string $output Optional, default is Object. Accepts OBJECT, ARRAY_A, or ARRAY_N. Default OBJECT.
string $filter Optional. Type of filter to apply. Accepts 'raw', 'edit', 'db', or 'display'. Default 'raw'.
Returns
WP_Post|array|null Type corresponding to $output on success or null on failure. When $output is OBJECT, a WP_Post instance is returned.
Definition at line 426 of file wp-includes/post.php.
References $GLOBALS, $output, $post, ARRAY_A, ARRAY_N, elseif, WP_Post\get_instance(), null, and sanitize_post().
Referenced by File_Upload_Upgrader\__construct(), WP_Comment\__get(), WP_Comment\__isset(), _close_comments_for_old_post(), _fix_attachment_links(), _get_page_link(), wp_xmlrpc_server\_insert_post(), WP_Posts_List_Table\_page_rows(), wp_xmlrpc_server\_prepare_page(), wp_xmlrpc_server\_prepare_post(), _reset_front_page_settings_for_post(), _update_blog_date_on_post_delete(), _update_posts_count_on_delete(), _wp_ajax_menu_quick_search(), _wp_link_page(), _wp_post_thumbnail_html(), _wp_preview_terms_filter(), _wp_put_post_revision(), adjacent_image_link(), attachment_submitbox_metadata(), author_can(), wp_xmlrpc_server\blogger_deletePost(), wp_xmlrpc_server\blogger_editPost(), wp_xmlrpc_server\blogger_getPost(), bulk_edit_posts(), WP_Embed\cache_oembed(), check_and_publish_future_post(), clean_post_cache(), WP_Media_List_Table\column_parent(), WP_Comments_List_Table\column_response(), WP_Posts_List_Table\column_title(), comments_open(), GFFormsModel\copy_post_image(), WP_Site_Icon\create_attachment_object(), Custom_Image_Header\create_attachment_object(), GFFormsModel\create_post(), delete_post_thumbnail(), do_trackbacks(), edit_post(), edit_post_link(), _WP_Editors\editor_settings(), export_wp(), feed_links_extra(), gallery_shortcode(), WP_Screen\get(), get_adjacent_post(), get_adjacent_post_link(), get_adjacent_post_rel_link(), get_attached_media(), get_attachment_fields_to_edit(), get_attachment_icon(), get_attachment_icon_src(), get_attachment_innerHTML(), get_attachment_link(), get_attachment_taxonomies(), get_blog_post(), get_body_class(), get_boundary_post(), GravityView_Admin_Duplicate_View\get_clone_view_link(), get_comment_class(), get_comment_reply_link(), get_comments_number(), get_compat_media_markup(), get_default_post_to_edit(), get_delete_post_link(), get_edit_post_link(), get_media_item(), get_media_items(), WP_UnitTest_Factory_For_Post\get_object_by_id(), get_oembed_response_data(), get_page(), get_page_by_path(), get_page_by_title(), get_page_link(), get_page_template_slug(), get_page_uri(), get_parent_post_rel_link(), get_permalink(), get_post_ancestors(), get_post_class(), get_post_comments_feed_link(), get_post_embed_html(), get_post_embed_url(), get_post_field(), get_post_format(), get_post_galleries(), get_post_mime_type(), get_post_modified_time(), get_post_permalink(), get_post_reply_link(), get_post_status(), get_post_taxonomies(), get_post_thumbnail_id(), get_post_time(), get_post_to_edit(), get_post_type(), get_postdata(), WP_Query\get_posts(), get_preview_post_link(), WP_Query\get_queried_object(), get_sample_permalink(), get_sample_permalink_html(), get_the_attachment_link(), get_the_author_posts(), get_the_content(), get_the_date(), get_the_excerpt(), get_the_guid(), get_the_ID(), get_the_modified_author(), get_the_password_form(), get_the_post_thumbnail(), get_the_taxonomies(), get_the_terms(), get_the_time(), get_the_title(), GFForms\handle_ajax_do_shortcode(), has_excerpt(), has_term(), image_media_send_to_editor(), GravityView_Admin\is_admin_page(), is_local_attachment(), GFEntryDetail\lead_detail_page(), map_meta_cap(), GravityView_View_Data\maybe_get_view_id(), WP_Embed\maybe_run_ajax_cache(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), media_buttons(), media_handle_sideload(), media_handle_upload(), media_upload_flash_bypass(), media_upload_form_handler(), meta_form(), wp_xmlrpc_server\mt_getPostCategories(), wp_xmlrpc_server\mt_getTrackbackPings(), wp_xmlrpc_server\mt_publishPost(), wp_xmlrpc_server\mt_setPostCategories(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_newMediaObject(), page_template_dropdown(), parent_dropdown(), permalink_anchor(), wp_xmlrpc_server\pingback_extensions_getPingbacks(), wp_xmlrpc_server\pingback_ping(), pings_open(), post_password_required(), prepend_attachment(), redirect_canonical(), GravityView_Admin_Duplicate_View\save_as_new_view(), set_post_format(), set_post_thumbnail(), WP_Query\setup_postdata(), WP_Embed\shortcode(), WP_Comments_List_Table\single_row(), WP_Posts_List_Table\single_row(), Walker_Nav_Menu_Edit\start_el(), Walker_Page\start_el(), start_wp(), stream_preview_image(), GravityView_API_Test\test_directory_link(), GravityView_API_Test\test_gravityview_get_current_views(), the_date_xml(), the_guid(), the_post_password(), the_shortlink(), the_title_attribute(), the_weekday(), the_weekday_date(), touch_time(), trackback_url_list(), twentyfifteen_post_nav_background(), update_attached_file(), user_can_edit_post(), WP_Customize_Nav_Menu_Item_Setting\value(), wp_admin_bar_edit_menu(), wp_ajax_add_menu_item(), wp_ajax_add_meta(), wp_ajax_delete_page(), wp_ajax_delete_post(), wp_ajax_get_attachment(), wp_ajax_get_revision_diffs(), wp_ajax_inline_save(), wp_ajax_parse_embed(), wp_ajax_parse_media_shortcode(), wp_ajax_replyto_comment(), wp_ajax_save_attachment(), wp_ajax_save_attachment_compat(), wp_ajax_save_attachment_order(), wp_ajax_send_attachment_to_editor(), wp_ajax_send_link_to_editor(), wp_ajax_trash_post(), wp_ajax_wp_fullscreen_save_post(), wp_ajax_wp_remove_post_lock(), wp_attachment_is(), wp_audio_shortcode(), wp_comment_form_unfiltered_html_nonce(), wp_dashboard_quick_press(), wp_xmlrpc_server\wp_deletePage(), wp_xmlrpc_server\wp_deletePost(), wp_xmlrpc_server\wp_editPage(), wp_xmlrpc_server\wp_editPost(), wp_enqueue_media(), wp_generate_attachment_metadata(), wp_get_attachment_image(), wp_get_attachment_link(), wp_get_attachment_metadata(), wp_get_attachment_thumb_file(), wp_get_attachment_thumb_url(), wp_get_attachment_url(), wp_get_post_parent_id(), wp_get_post_revision(), wp_get_post_revisions(), wp_get_revision_ui_diff(), wp_get_shortlink(), wp_get_single_post(), wp_xmlrpc_server\wp_getCommentCount(), wp_xmlrpc_server\wp_getMediaItem(), wp_xmlrpc_server\wp_getPage(), wp_xmlrpc_server\wp_getPost(), wp_xmlrpc_server\wp_getRevisions(), wp_handle_comment_submission(), wp_insert_post(), wp_list_post_revisions(), wp_mime_type_icon(), wp_nav_menu_item_post_type_meta_box(), wp_xmlrpc_server\wp_newComment(), wp_playlist_shortcode(), wp_popular_terms_checklist(), wp_post_revision_title(), wp_post_revision_title_expanded(), wp_prepare_attachment_for_js(), wp_prepare_revisions_for_js(), wp_publish_post(), wp_xmlrpc_server\wp_restoreRevision(), wp_save_image(), wp_save_post_revision(), wp_scheduled_delete(), wp_setup_nav_menu_item(), wp_trash_post(), wp_trash_post_comments(), wp_unique_post_slug(), wp_untrash_post(), wp_untrash_post_comments(), wp_update_attachment_metadata(), wp_update_comment(), wp_update_comment_count_now(), wp_update_nav_menu_item(), wp_update_post(), and wp_video_shortcode().
get_post_ancestors ($post)
Retrieve ancestors of a post.
Since
2.5.0
Parameters
int | WP_Post $post Post ID or post object.
Returns
array Ancestor IDs or empty array if none are found.
Definition at line 466 of file wp-includes/post.php.
References $id, $post, and get_post().
Referenced by WP_Post\__get(), get_ancestors(), and WP_Posts_List_Table\single_row().
get_post_custom ($post_id = 0)
Retrieve post meta fields, based on post ID.
The post meta fields are retrieved from the cache where possible, so the function is optimized to be called more than once.
Since
1.2.0
Parameters
int $post_id Optional. Post ID. Default is ID of the global $post.
Returns
array Post meta for the given post.
Definition at line 1764 of file wp-includes/post.php.
References $post_id, absint(), get_post_meta(), and get_the_ID().
Referenced by atom_enclosure(), get_enclosed(), get_post_custom_keys(), get_post_custom_values(), wp_xmlrpc_server\mw_getPost(), post_custom(), and rss_enclosure().
get_post_custom_keys ($post_id = 0)
Retrieve meta field names for a post.
If there are no meta fields, then nothing (null) will be returned.
Since
1.2.0
Parameters
int $post_id Optional. Post ID. Default is ID of the global $post.
Returns
array|void Array of the keys, if retrieved.
Definition at line 1782 of file wp-includes/post.php.
References $custom, $keys, $post_id, and get_post_custom().
Referenced by GravityView_Admin_Duplicate_View\copy_view_meta_info(), WP_Embed\delete_oembed_caches(), and the_meta().
get_post_custom_values ($key = '', $post_id = 0)
Retrieve values for a custom post field.
The parameters must not be considered optional. All of the post meta fields will be retrieved and only the meta field key values returned.
Since
1.2.0
Parameters
string $key Optional. Meta field key. Default empty.
int $post_id Optional. Post ID. Default is ID of the global $post.
Returns
array|null Meta field values.
Definition at line 1804 of file wp-includes/post.php.
References $custom, $post_id, get_post_custom(), and null.
Referenced by GravityView_Admin_Duplicate_View\copy_view_meta_info(), and the_meta().
get_post_field ($field, $post, $context = 'display')
Retrieve data from a post field based on Post ID.
Examples of the post field will be, 'post_type', 'post_status', 'post_content', etc and based off of the post object property or key names.
The context values are based off of the taxonomy filter functions and supported values are found within those functions.
Since
2.3.0
See also
sanitize_post_field()
Parameters
string $field Post field name.
int | WP_Post $post Post ID or post object.
string $context Optional. How to filter the field. Accepts 'raw', 'edit', 'db', or 'display'. Default 'display'.
Returns
string The value of the post field on success, empty string on failure.
Definition at line 506 of file wp-includes/post.php.
References $field, $post, get_post(), and sanitize_post_field().
Referenced by _wp_translate_postdata(), wp_insert_post(), and wp_update_nav_menu_item().
get_post_meta ($post_id, $key = '', $single = false)
Retrieve post meta field for a post.
Since
1.5.0
Parameters
int $post_id Post ID.
string $key Optional. The meta key to retrieve. By default, returns data for all keys. Default empty.
bool $single Optional. Whether to return a single value. Default false.
Returns
mixed Will be an array if $single is false. Will be value of meta data field if $single is true.
Definition at line 1711 of file wp-includes/post.php.
References $post_id, and get_metadata().
Referenced by WP_Post\__get(), _media_states(), wp_xmlrpc_server\_prepare_post(), _wp_menu_item_classes_by_context(), wp_xmlrpc_server\add_enclosure_if_new(), GravityView_View_Data\add_view(), GFFormsModel\copy_post_image(), edit_form_image_editor(), edit_post(), get_attached_file(), get_attachment_fields_to_edit(), GVCommon\get_directory_fields(), get_header_image_tag(), get_inline_data(), GVCommon\get_meta_form_id(), GVCommon\get_meta_template_id(), get_page_template_slug(), get_post_custom(), get_post_status(), get_post_thumbnail_id(), GravityView_Migrate\get_search_fields(), GVCommon\get_template_settings(), get_the_modified_author(), get_uploaded_header_images(), Custom_Image_Header\get_uploaded_header_images(), map_meta_cap(), media_upload_form_handler(), GravityView_View_Data\parse_post_meta(), post_thumbnail_meta_box(), GravityView_Admin_Views\render_widgets_active_areas(), WP_Embed\shortcode(), GravityView_Migrate\update_search_on_views(), upgrade_160(), wp_ajax_crop_image(), wp_ajax_save_attachment(), wp_ajax_wp_fullscreen_save_post(), wp_calculate_image_sizes(), wp_check_for_changed_slugs(), wp_delete_attachment(), wp_enqueue_media(), wp_get_associated_nav_menu_items(), wp_get_attachment_image(), wp_get_attachment_image_sizes(), wp_get_attachment_image_srcset(), wp_get_attachment_metadata(), wp_get_attachment_url(), wp_get_nav_menu_items(), wp_image_editor(), wp_make_content_images_responsive(), wp_maybe_generate_attachment_metadata(), wp_prepare_attachment_for_js(), wp_restore_image(), wp_save_image(), wp_setup_nav_menu_item(), wp_untrash_post(), wp_untrash_post_comments(), and wp_update_nav_menu_item().
get_post_mime_type ($ID = '')
Retrieve the mime type of an attachment based on the ID.
This function can be used with any post type, but it makes more sense with attachments.
Since
2.0.0
Parameters
int | WP_Post $ID Optional. Post ID or post object. Default empty.
Returns
string|false The mime type on success, false on failure.
Definition at line 529 of file wp-includes/post.php.
References $ID, $post, and get_post().
Referenced by get_body_class(), wp_generate_attachment_metadata(), and wp_image_editor().
get_post_mime_types ()
Get default post mime types.
Since
2.9.0
Returns
array List of post mime types.
Filter the default list of post mime types.
Since
2.5.0
Parameters
array $post_mime_types Default list of post mime types.
Definition at line 2219 of file wp-includes/post.php.
References __, _n_noop(), and apply_filters().
Referenced by get_media_item(), wp_edit_attachments_query(), wp_edit_attachments_query_vars(), and wp_enqueue_media().
get_post_stati ($args = array(), $output = 'names', $operator = 'and')
Get a list of post statuses.
Since
3.0.0
array $wp_post_statuses List of post statuses.
See also
register_post_status()
Parameters
array | string $args Optional. Array or string of post status arguments to compare against properties of the global $wp_post_statuses objects. Default empty array.
string $output Optional. The type of output to return, either 'names' or 'objects'. Default 'names'.
string $operator Optional. The logical operation to perform. 'or' means only one element from the array needs to match; 'and' means all elements must match. Default 'and'.
Returns
array A list of post status names or objects.
Definition at line 773 of file wp-includes/post.php.
References $field, $output, and wp_filter_object_list().
Referenced by WP_Posts_List_Table\__construct(), get_adjacent_post(), get_pages(), WP_Query\get_posts(), WP_Posts_List_Table\get_views(), WP_Posts_List_Table\prepare_items(), WP_UnitTestCase\reset_post_statuses(), wp_count_posts(), and wp_edit_posts_query().
get_post_status ($ID = '')
Retrieve the post status based on the Post ID.
If the post ID is of an attachment, then the parent post status will be given instead.
Since
2.0.0
Parameters
int | WP_Post $ID Optional. Post ID or post object. Default empty.
Returns
string|false Post status on success, false on failure.
Filter the post status.
Since
4.4.0
Parameters
string $post_status The post status.
WP_Post $post The post object.
Definition at line 549 of file wp-includes/post.php.
References $ID, $post, apply_filters(), get_post(), and get_post_meta().
Referenced by get_oembed_response_data(), get_post_permalink(), WP_Query\get_posts(), GravityView_View_Data\is_valid_embed_id(), redirect_canonical(), WP_Press_This\save_post(), GravityView_View_Data\view_exists(), wp_delete_post(), wp_handle_comment_submission(), and wp_set_post_categories().
get_post_status_object ($post_status)
Retrieve a post status object by name.
Since
3.0.0
array $wp_post_statuses List of post statuses.
See also
register_post_status()
Parameters
string $post_status The name of a registered post status.
Returns
object|null A post status object.
Definition at line 747 of file wp-includes/post.php.
References null.
Referenced by wp_xmlrpc_server\_insert_post(), _wp_translate_postdata(), WP_Query\get_posts(), map_meta_cap(), WP\parse_request(), url_to_postid(), and wp_handle_comment_submission().
get_post_statuses ()
Retrieve all of the WordPress supported post statuses.
Posts have a limited set of valid status values, this provides the post_status values and descriptions.
Since
2.5.0
Returns
array List of post statuses.
Definition at line 596 of file wp-includes/post.php.
References __.
Referenced by wp_xmlrpc_server\wp_getPostStatusList().
get_post_type ($post = null)
Retrieve the post type of the current post or of a given post.
Since
2.1.0
Parameters
int | WP_Post | null $post Optional. Post ID or post object. Default is global $post.
Returns
string|false Post type on success, false on failure.
Definition at line 823 of file wp-includes/post.php.
References $post, and get_post().
Referenced by wp_xmlrpc_server\_insert_post(), _wp_ajax_menu_quick_search(), bulk_edit_posts(), get_media_item(), get_oembed_response_data_rich(), get_the_category_list(), GVCommon\has_gravityview_shortcode(), is_nav_menu_item(), GravityView_View_Data\is_valid_embed_id(), GravityView_Admin_Duplicate_View\make_duplicate_link_row(), GravityView_View_Data\maybe_get_view_id(), GravityView_frontend\parse_content(), wp_check_for_changed_slugs(), and wp_set_post_categories().
get_post_type_capabilities ($args)
Build an object with all post type capabilities out of a post type object.
Post type capabilities use the 'capability_type' argument as a base, if the capability is not set in the 'capabilities' argument array or if the 'capabilities' argument is not supplied.
The capability_type argument can optionally be registered as an array, with the first value being singular and the second plural, e.g. array('story, 'stories') Otherwise, an 's' will be added to the value for the plural form. After registration, capability_type will always be a string of the singular value.
By default, seven keys are accepted as part of the capabilities array:
edit_post, read_post, and delete_post are meta capabilities, which are then generally mapped to corresponding primitive capabilities depending on the context, which would be the post being edited/read/deleted and the user or role being checked. Thus these capabilities would generally not be granted directly to users or roles.
edit_posts - Controls whether objects of this post type can be edited.
edit_others_posts - Controls whether objects of this type owned by other users can be edited. If the post type does not support an author, then this will behave like edit_posts.
publish_posts - Controls publishing objects of this post type.
read_private_posts - Controls whether private objects can be read.
These four primitive capabilities are checked in core in various locations. There are also seven other primitive capabilities which are not referenced directly in core, except in map_meta_cap(), which takes the three aforementioned meta capabilities and translates them into one or more primitive capabilities that must then be checked against the user or role, depending on the context.
read - Controls whether objects of this post type can be read.
delete_posts - Controls whether objects of this post type can be deleted.
delete_private_posts - Controls whether private objects can be deleted.
delete_published_posts - Controls whether published objects can be deleted.
delete_others_posts - Controls whether objects owned by other users can be can be deleted. If the post type does not support an author, then this will behave like delete_posts.
edit_private_posts - Controls whether private objects can be edited.
edit_published_posts - Controls whether published objects can be edited.
These additional capabilities are only used in map_meta_cap(). Thus, they are only assigned by default if the post type is registered with the 'map_meta_cap' argument set to true (default is false).
Since
3.0.0
See also
register_post_type()
map_meta_cap()
Parameters
object $args Post type registration arguments.
Returns
object object with all the capabilities as member variables.
Definition at line 1244 of file wp-includes/post.php.
References _post_type_meta_capabilities().
Referenced by register_post_type().
get_post_type_labels ($post_type_object)
Build an object with all post type labels out of a post type object.
Accepted keys of the label array in the post type object:
name - general name for the post type, usually plural. The same and overridden by $post_type_object->label. Default is Posts/Pages
singular_name - name for one object of this post type. Default is Post/Page
add_new - Default is Add New for both hierarchical and non-hierarchical types. When internationalizing this string, please use a gettext context https://codex.wordpress.org/I18n_for_WordPress_Developers#Disambiguation_by_context matching your post type. Example: `_x('Add New', 'product');`.
add_new_item - Default is Add New Post/Add New Page.
edit_item - Default is Edit Post/Edit Page.
new_item - Default is New Post/New Page.
view_item - Default is View Post/View Page.
search_items - Default is Search Posts/Search Pages.
not_found - Default is No posts found/No pages found.
not_found_in_trash - Default is No posts found in Trash/No pages found in Trash.
parent_item_colon - This string isn't used on non-hierarchical types. In hierarchical ones the default is 'Parent Page:'.
all_items - String for the submenu. Default is All Posts/All Pages.
archives - String for use with archives in nav menus. Default is Post Archives/Page Archives.
insert_into_item - String for the media frame button. Default is Insert into post/Insert into page.
uploaded_to_this_item - String for the media frame filter. Default is Uploaded to this post/Uploaded to this page.
featured_image - Default is Featured Image.
set_featured_image - Default is Set featured image.
remove_featured_image - Default is Remove featured image.
use_featured_image - Default is Use as featured image.
menu_name - Default is the same as name.
filter_items_list - String for the table views hidden heading.
items_list_navigation - String for the table pagination hidden heading.
items_list - String for the table hidden heading.
Above, the first default value is for non-hierarchical post types (like posts) and the second one is for hierarchical post types (like pages).
Since
3.0.0
4.3.0 Added the featured_image, set_featured_image, remove_featured_image, and use_featured_image labels.
4.4.0 Added the insert_into_item, uploaded_to_this_item, filter_items_list, items_list_navigation, and items_list labels.
private
Parameters
object $post_type_object Post type object.
Returns
object object with all the labels as member variables.
Filter the labels of a specific post type.
The dynamic portion of the hook name, $post_type, refers to the post type slug.
Since
3.5.0
See also
get_post_type_labels() for the full list of labels.
Parameters
object $labels Object with labels for the post type as member variables.
Definition at line 1358 of file wp-includes/post.php.
References $post_type, $post_type_object, __, _get_custom_object_labels(), _x, apply_filters(), null, and object.
Referenced by register_post_type().
get_post_type_object ($post_type)
Retrieve a post type object by name.
Since
3.0.0
array $wp_post_types List of post types.
See also
register_post_type()
Parameters
string $post_type The name of a registered post type.
Returns
object|null A post type object.
Definition at line 842 of file wp-includes/post.php.
References $post_type, and null.
Referenced by WP_Posts_List_Table\__construct(), _add_post_type_submenus(), _count_posts_cache_key(), wp_xmlrpc_server\_insert_post(), wp_xmlrpc_server\_toggle_sticky(), _update_blog_date_on_post_delete(), _update_blog_date_on_post_publish(), _wp_ajax_menu_quick_search(), _wp_post_thumbnail_html(), _wp_translate_postdata(), GravityView_Admin_Add_Shortcode\add_shortcode_popup(), WP_Posts_List_Table\ajax_user_can(), wp_xmlrpc_server\blogger_newPost(), bulk_edit_posts(), WP_Media_List_Table\column_parent(), WP_Terms_List_Table\column_posts(), WP_Comments_List_Table\column_response(), WP_Posts_List_Table\column_title(), edit_post(), export_wp(), WP_Posts_List_Table\extra_tablenav(), feed_links_extra(), get_adjacent_post(), WP_Posts_List_Table\get_bulk_actions(), GravityView_Admin_Duplicate_View\get_clone_view_link(), get_delete_post_link(), get_edit_post_link(), get_editable_user_ids(), get_inline_data(), get_media_item(), get_post_permalink(), get_post_type_archive_feed_link(), get_post_type_archive_link(), get_post_type_archive_template(), WP_Query\get_posts(), get_posts_by_author_sql(), get_preview_post_link(), WP_Query\get_queried_object(), get_sample_permalink(), WP_Posts_List_Table\handle_row_actions(), WP_Posts_List_Table\inline_edit(), WP_Query\is_post_type_archive(), is_post_type_hierarchical(), WP_Customize_Nav_Menus\load_available_items_query(), map_meta_cap(), wp_xmlrpc_server\mw_newPost(), WP_Posts_List_Table\no_items(), page_attributes_meta_box(), WP_Query\parse_query(), post_submit_meta_box(), post_type_archive_title(), post_type_exists(), redirect_canonical(), register_taxonomy_for_object_type(), Walker_Nav_Menu_Edit\start_el(), unregister_taxonomy_for_object_type(), WP_Customize_Nav_Menu_Item_Setting\value_as_wp_post_nav_menu_item(), wp_admin_bar_edit_menu(), wp_admin_bar_my_sites_menu(), wp_ajax_add_menu_item(), wp_ajax_query_attachments(), wp_count_posts(), wp_dashboard_right_now(), wp_dashboard_setup(), wp_edit_attachments_query_vars(), wp_enqueue_media(), wp_get_archives(), wp_get_shortlink(), wp_xmlrpc_server\wp_getComments(), wp_xmlrpc_server\wp_getPosts(), wp_xmlrpc_server\wp_getPostType(), wp_list_categories(), wp_nav_menu_item_post_type_meta_box(), wp_prepare_attachment_for_js(), wp_setup_nav_menu_item(), wp_title(), wp_update_nav_menu_item(), and wp_write_post().
get_post_types ($args = array(), $output = 'names', $operator = 'and')
Get a list of all registered post type objects.
Since
2.9.0
array $wp_post_types List of post types.
See also
register_post_type() for accepted arguments.
Parameters
array | string $args Optional. An array of key => value arguments to match against the post type objects. Default empty array.
string $output Optional. The type of output to return. Accepts post type 'names' or 'objects'. Default 'names'.
string $operator Optional. The logical operation to perform. 'or' means only one element from the array needs to match; 'and' means all elements must match; 'not' means no elements may match. Default 'and'.
Returns
array A list of post type names or objects.
Definition at line 870 of file wp-includes/post.php.
References $field, $output, and wp_filter_object_list().
Referenced by WP_Terms_List_Table\__construct(), _add_post_type_submenus(), _get_last_post_time(), WP_Customize_Nav_Menus\available_item_types(), WP_Embed\cache_oembed(), export_wp(), WP_Rewrite\generate_rewrite_rules(), get_attachment_link(), get_pages(), get_permalink(), WP_Query\get_posts(), WP\parse_request(), WP_User_Query\prepare_query(), redirect_guess_404_permalink(), WP_Screen\render_view_mode(), WP_UnitTestCase\reset_post_types(), WP_Customize_Nav_Menus\search_available_items_query(), set_screen_options(), upgrade_350(), url_to_postid(), wp_admin_bar_new_content_menu(), wp_ajax_find_posts(), wp_ajax_menu_get_metabox(), wp_delete_user(), wp_edit_posts_query(), wp_xmlrpc_server\wp_getPostTypes(), _WP_Editors\wp_link_query(), and wp_nav_menu_post_type_meta_boxes().
get_posts ($args = null)
Retrieve list of latest posts or posts matching criteria.
The defaults are as follows:
Since
1.2.0
See also
WP_Query::parse_query()
Parameters
array $args { Optional. Arguments to retrieve posts. See WP_Query::parse_query() for all available arguments.
int $numberposts Total number of posts to retrieve. Is an alias of $posts_per_page in WP_Query. Accepts -1 for all. Default 5. int|string $category Category ID or comma-separated list of IDs (this or any children). Is an alias of $cat in WP_Query. Default 0. array $include An array of post IDs to retrieve, sticky posts will be included. Is an alias of $post__in in WP_Query. Default empty array. array $exclude An array of post IDs not to retrieve. Default empty array. bool $suppress_filters Whether to suppress filters. Default true. }
Returns
array List of posts.
Definition at line 1618 of file wp-includes/post.php.
References elseif, WP_Query\query(), wp_parse_args(), and wp_parse_id_list().
Referenced by GravityView_Uninstall_Test\_check_posts(), GravityView_Admin_Add_Shortcode\add_shortcode_popup(), GravityView_Uninstall\delete_posts(), GravityView_Recent_Entries_Widget\form(), gallery_shortcode(), GVCommon\get_all_views(), get_boundary_post(), get_children(), GVCommon\get_connected_views(), Featured_Content\get_featured_post_ids(), Featured_Content\get_featured_posts(), GravityView_oEmbed\get_postid_from_url_and_slug(), get_uploaded_header_images(), WP_Customize_Nav_Menus\load_available_items_query(), twentyeleven_get_gallery_images(), twentyten_get_gallery_images(), GravityView_Migrate\update_search_on_views(), Twenty_Fourteen_Ephemera_Widget\widget(), wp_ajax_find_posts(), wp_dashboard_recent_drafts(), wp_generate_attachment_metadata(), wp_get_nav_menu_items(), wp_get_recent_posts(), wp_xmlrpc_server\wp_getMediaLibrary(), wp_xmlrpc_server\wp_getPages(), wp_nav_menu_item_post_type_meta_box(), and wp_playlist_shortcode().
get_posts_by_author_sql ($post_type, $full = true, $post_author = null, $public_only = false)
Retrieve the post SQL based on capability, author, and type.
Since
3.0.0
4.3.0 Introduced the ability to pass an array of post types to $post_type.
See also
get_private_posts_cap_sql() wpdb $wpdb WordPress database abstraction object.
Parameters
array | string $post_type Single post type or an array of post types.
bool $full Optional. Returns a full WHERE statement instead of just an 'andalso' term. Default true.
int $post_author Optional. Query posts having a single author ID. Default null.
bool $public_only Optional. Only return public posts. Skips cap checks for $current_user. Default false.
Returns
string SQL WHERE code that can be added to a query.
Filter the capability to read private posts for a custom post type when generating SQL for getting posts by author.
Since
2.2.0
Parameters
string $cap Capability.
Definition at line 5257 of file wp-includes/post.php.
References $id, $post_type, $wpdb, apply_filters(), current_user_can(), elseif, get_current_user_id(), get_post_type_object(), and null.
Referenced by count_many_users_posts(), count_user_posts(), get_private_posts_cap_sql(), and WP_User_Query\parse_orderby().
get_private_posts_cap_sql ($post_type)
Retrieve the private post SQL based on capability.
This function provides a standardized way to appropriately select on the post_status of a post type. The function will return a piece of SQL code that can be added to a WHERE clause; this SQL is constructed to allow all published posts, and all private posts to which the user has access.
Since
2.2.0
4.3.0 Added the ability to pass an array to $post_type.
Parameters
string | array $post_type Single post type or an array of post types. Currently only supports 'post' or 'page'.
Returns
string SQL code that can be added to a where clause.
Definition at line 5236 of file wp-includes/post.php.
References $post_type, and get_posts_by_author_sql().
Referenced by wp_list_authors().
get_pung ($post_id)
Retrieve URLs already pinged for a post.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Post ID.
Returns
array
Filter the list of already-pinged URLs for the given post.
Since
2.0.0
Parameters
array $pung Array of URLs already pinged for the given post.
Definition at line 3962 of file wp-includes/post.php.
References $post_id, $wpdb, and apply_filters().
Referenced by do_trackbacks(), and pingback().
get_to_ping ($post_id)
Retrieve URLs that need to be pinged.
Since
1.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Post ID
Returns
array
Filter the list of URLs yet to ping for the given post.
Since
2.0.0
Parameters
array $to_ping List of URLs yet to ping.
Definition at line 3988 of file wp-includes/post.php.
References $post_id, $wpdb, apply_filters(), and sanitize_trackback_urls().
Referenced by do_trackbacks().
is_local_attachment ($url)
Check if the attachment URI is local one and is really an attachment.
Since
2.0.0
Parameters
string $url URL to check
Returns
bool True on success, false on failure.
Definition at line 4628 of file wp-includes/post.php.
References $id, $post, $url, get_post(), home_url(), and url_to_postid().
Referenced by pingback().
is_post_type_hierarchical ($post_type)
Whether the post type is hierarchical.
A false return value might also mean that the post type does not exist.
Since
3.0.0
See also
get_post_type_object()
Parameters
string $post_type Post type name
Returns
bool Whether post type is hierarchical.
Definition at line 793 of file wp-includes/post.php.
References $post_type, get_post_type_object(), and post_type_exists().
Referenced by _wp_menu_item_classes_by_context(), WP_Posts_List_Table\column_default(), WP_Posts_List_Table\column_title(), WP_Rewrite\generate_rewrite_rules(), WP_Posts_List_Table\get_table_classes(), WP_Posts_List_Table\handle_row_actions(), WP_Posts_List_Table\prepare_items(), wp_check_for_changed_slugs(), wp_delete_post(), wp_edit_posts_query(), wp_list_pages(), wp_nav_menu_item_post_type_meta_box(), wp_old_slug_redirect(), and wp_unique_post_slug().
is_post_type_viewable ($post_type_object)
Determines whether a post type is considered "viewable".
For built-in post types such as posts and pages, the 'public' value will be evaluated. For all others, the 'publicly_queryable' value will be used.
Since
4.4.0
Parameters
object $post_type_object Post type object.
Returns
bool Whether the post type should be considered viewable.
Definition at line 1590 of file wp-includes/post.php.
References $post_type_object.
Referenced by get_preview_post_link(), WP_Posts_List_Table\handle_row_actions(), WP\parse_request(), post_submit_meta_box(), register_post_type(), and wp_get_archives().
is_sticky ($post_id = 0)
Check if post is sticky.
Sticky posts should remain at the top of The Loop. If the post ID is not given, then The Loop ID for the current post will be used.
Since
2.7.0
Parameters
int $post_id Optional. Post ID. Default is ID of the global $post.
Returns
bool Whether post is sticky.
Definition at line 1824 of file wp-includes/post.php.
References $post_id, absint(), get_option(), and get_the_ID().
Referenced by _post_states(), wp_xmlrpc_server\_prepare_post(), get_inline_data(), get_post_class(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), post_submit_meta_box(), and sticky_class().
post_type_exists ($post_type)
Check if a post type is registered.
Since
3.0.0
See also
get_post_type_object()
Parameters
string $post_type Post type name.
Returns
bool Whether post type is registered.
Definition at line 811 of file wp-includes/post.php.
References $post_type, and get_post_type_object().
Referenced by _wp_ajax_menu_quick_search(), export_wp(), WP_Screen\get(), get_ancestors(), is_post_type_hierarchical(), WP_Customize_Nav_Menu_Item_Setting\populate_value(), wp_count_posts(), and wp_xmlrpc_server\wp_getPostType().
post_type_supports ($post_type, $feature)
Check a post type's support for a given feature.
Since
3.0.0
array $_wp_post_type_features
Parameters
string $post_type The post type being checked.
string $feature The feature being checked.
Returns
bool Whether the post type supports the given feature.
Definition at line 1548 of file wp-includes/post.php.
References $post_type.
Referenced by edit_post(), _WP_Editors\editor_settings(), get_body_class(), WP_Media_List_Table\get_columns(), WP_Posts_List_Table\get_columns(), get_default_comment_status(), get_default_post_to_edit(), get_inline_data(), get_media_item(), get_post_class(), get_post_format(), WP_Press_This\html(), WP_Posts_List_Table\inline_edit(), post_format_meta_box(), WP_Press_This\post_formats_html(), wp_delete_user(), wp_enqueue_media(), wp_generate_attachment_metadata(), wp_xmlrpc_server\wp_getComments(), wp_insert_post(), wp_print_media_templates(), wp_revisions_to_keep(), and wp_save_post_revision().
register_post_status ($post_status, $args = array())
Register a post status.
Do not use before init.
A simple function for creating or modifying a post status based on the parameters given. The function will accept an array (second optional parameter), along with a string for the post status name.
Arguments prefixed with an _underscore shouldn't be used by plugins and themes.
Since
3.0.0 array $wp_post_statuses Inserts new post status object into the list
Parameters
string $post_status Name of the post status.
array | string $args { Optional. Array or string of post status arguments.
bool|string $label A descriptive name for the post status marked for translation. Defaults to value of $post_status. bool|array $label_count Descriptive text to use for nooped plurals. Default array of $label, twice bool $exclude_from_search Whether to exclude posts with this post status from search results. Default is value of $internal. bool $_builtin Whether the status is built-in. Core-use only. Default false. bool $public Whether posts of this status should be shown in the front end of the site. Default false. bool $internal Whether the status is for internal use only. Default false. bool $protected Whether posts with this status should be protected. Default false. bool $private Whether posts with this status should be private. Default false. bool $publicly_queryable Whether posts with this status should be publicly- queryable. Default is value of $public. bool $show_in_admin_all_list Whether to include posts in the edit listing for their post type. Default is value of $internal. bool $show_in_admin_status_list Show in the list of statuses with post counts at the top of the edit listings, e.g. All (12) | Published (9) | My Custom Status (2) Default is value of $internal. }
Returns
object
Definition at line 670 of file wp-includes/post.php.
References null, object, sanitize_key(), and wp_parse_args().
Referenced by create_initial_post_types().
register_post_type ($post_type, $args = array())
Register a post type.
Do not use before init.
A function for creating or modifying a post type based on the parameters given. The function will accept an array (second optional parameter), along with a string for the post type name.
Since
2.9.0
3.0.0 The show_ui argument is now enforced on the new post screen.
4.4.0 The show_ui argument is now enforced on the post type listing screen and post editing screen.
array $wp_post_types List of post types. WP_Rewrite $wp_rewrite Used for default feeds. WP $wp Used to add query vars.
Parameters
string $post_type Post type key, must not exceed 20 characters.
array | string $args { Array or string of arguments for registering a post type.
string $label Name of the post type shown in the menu. Usually plural. Default is value of $labels['name']. array $labels An array of labels for this post type. If not set, post labels are inherited for non-hierarchical types and page labels for hierarchical ones. {
See also
get_post_type_labels()}. string $description A short descriptive summary of what the post type is. Default empty. bool $public Whether a post type is intended for use publicly either via the admin interface or by front-end users. While the default settings of $exclude_from_search, $publicly_queryable, $show_ui, and $show_in_nav_menus are inherited from public, each does not rely on this relationship and controls a very specific intention. Default false. bool $hierarchical Whether the post type is hierarchical (e.g. page). Default false. bool $exclude_from_search Whether to exclude posts with this post type from front end search results. Default is the opposite value of $public. bool $publicly_queryable Whether queries can be performed on the front end for the post type as part of {
parse_request()}. Endpoints would include:
?post_type={post_type_key}
?{post_type_key}={single_post_slug}
?{post_type_query_var}={single_post_slug} If not set, the default is inherited from $public. bool $show_ui Whether to generate and allow a UI for managing this post type in the admin. Default is value of $public. bool $show_in_menu Where to show the post type in the admin menu. To work, $show_ui must be true. If true, the post type is shown in its own top level menu. If false, no menu is shown. If a string of an existing top level menu (eg. 'tools.php' or 'edit.php?post_type=page'), the post type will be placed as a sub-menu of that. Default is value of $show_ui. bool $show_in_nav_menus Makes this post type available for selection in navigation menus. Default is value $public. bool $show_in_admin_bar Makes this post type available via the admin bar. Default is value of $show_in_menu. int $menu_position The position in the menu order the post type should appear. To work, $show_in_menu must be true. Default null (at the bottom). string $menu_icon The url to the icon to be used for this menu. Pass a base64-encoded SVG using a data URI, which will be colored to match the color scheme – this should begin with 'data:image/svg+xml;base64,'. Pass the name of a Dashicons helper class to use a font icon, e.g. 'dashicons-chart-pie'. Pass 'none' to leave div.wp-menu-image empty so an icon can be added via CSS. Defaults to use the posts icon. string $capability_type The string to use to build the read, edit, and delete capabilities. May be passed as an array to allow for alternative plurals when using this argument as a base to construct the capabilities, e.g. array('story', 'stories'). Default 'post'. array $capabilities Array of capabilities for this post type. $capability_type is used as a base to construct capabilities by default. {
get_post_type_capabilities()}. bool $map_meta_cap Whether to use the internal default meta capability handling. Default false. array $supports An alias for calling {
add_post_type_support()} directly. Defaults to array containing 'title' & 'editor'. callable $register_meta_box_cb Provide a callback function that sets up the meta boxes for the edit form. Do remove_meta_box() and add_meta_box() calls in the callback. Default null. array $taxonomies An array of taxonomy identifiers that will be registered for the post type. Taxonomies can be registered later with {
register_taxonomy()} or {
register_taxonomy_for_object_type()}. Default empty array. bool|string $has_archive Whether there should be post type archives, or if a string, the archive slug to use. Will generate the proper rewrite rules if $rewrite is enabled. Default false. bool|array $rewrite { Triggers the handling of rewrites for this post type. To prevent rewrite, set to false. Defaults to true, using $post_type as slug. To specify rewrite rules, an array can be passed with any of these keys:
string $slug Customize the permastruct slug. Defaults to $post_type key. bool $with_front Whether the permastruct should be prepended with WP_Rewrite::$front. Default true. bool $feeds Whether the feed permastruct should be built for this post type. Default is value of $has_archive. bool $pages Whether the permastruct should provide for pagination. Default true. const $ep_mask Endpoint mask to assign. If not specified and permalink_epmask is set, inherits from $permalink_epmask. If not specified and permalink_epmask is not set, defaults to EP_PERMALINK. } string|bool $query_var Sets the query_var key for this post type. Defaults to $post_type key. If false, a post type cannot be loaded at ?{query_var}={post_slug}. If specified as a string, the query ?{query_var_string}={post_slug} will be valid. bool $can_export Whether to allow this post type to be exported. Default true. bool $delete_with_user Whether to delete posts of this type when deleting a user. If true, posts of this type belonging to the user will be moved to trash when then user is deleted. If false, posts of this type belonging to the user will not be trashed or deleted. If not set (the default), posts are trashed if post_type_supports('author'). Otherwise posts are not trashed or deleted. Default null. bool $_builtin FOR INTERNAL USE ONLY! True if this post type is a native or "built-in" post_type. Default false. string $_edit_link FOR INTERNAL USE ONLY! URL segment to use for edit link of this post type. Default 'post.php?post=d'. }
Returns
object|WP_Error The registered post type object, or an error object.
Filter the arguments for registering a post type.
Since
4.4.0
Parameters
array $args Array of arguments for registering a post type.
string $post_type Post type key.
Fires after a post type is registered.
Since
3.3.0
Parameters
string $post_type Post type.
object $args Arguments used to register the post type.
Definition at line 993 of file wp-includes/post.php.
References $post_type, $wp, $wp_rewrite, __, _doing_it_wrong(), add_action(), add_permastruct(), add_post_type_support(), add_rewrite_rule(), add_rewrite_tag(), apply_filters(), do_action(), elseif, EP_PERMALINK, get_option(), get_post_type_capabilities(), get_post_type_labels(), if, is_admin(), is_post_type_viewable(), null, object, register_taxonomy_for_object_type(), sanitize_key(), sanitize_title_with_dashes(), and wp_parse_args().
Referenced by create_initial_post_types(), and GravityView_Post_Types\init_post_types().
remove_post_type_support ($post_type, $feature)
Remove support for a feature from a post type.
Since
3.0.0
array $_wp_post_type_features
Parameters
string $post_type The post type for which to remove the feature.
string $feature The feature being removed.
Definition at line 1512 of file wp-includes/post.php.
References $post_type.
sanitize_post ($post, $context = 'display')
Sanitize every post field.
If the context is 'raw', then the post object or array will get minimal sanitization of the integer fields.
Since
2.3.0
See also
sanitize_post_field()
Parameters
object | WP_Post | array $post The Post Object or Array
string $context Optional. How to sanitize post fields. Accepts 'raw', 'edit', 'db', or 'display'. Default 'display'.
Returns
object|WP_Post|array The now sanitized Post Object or Array (will be the same type as $post).
Definition at line 1858 of file wp-includes/post.php.
References $field, $post, elseif, and sanitize_post_field().
Referenced by _set_preview(), WP_Post\filter(), get_attachment_fields_to_edit(), WP_Post\get_instance(), get_pages(), get_post(), and wp_insert_post().
sanitize_post_field ($field, $value, $post_id, $context = 'display')
Sanitize post field based on context.
Possible context values are: 'raw', 'edit', 'db', 'display', 'attribute' and 'js'. The 'display' context is used by default. 'attribute' and 'js' contexts are treated like 'display' when calling filters.
Since
2.3.0
4.4.0 Like sanitize_post(), $context defaults to 'display'.
Parameters
string $field The Post Object field name.
mixed $value The Post Object value.
int $post_id Post ID.
string $context Optional. How to sanitize post fields. Looks for 'raw', 'edit', 'db', 'display', 'attribute' and 'js'. Default 'display'.
Returns
mixed Sanitized value.
Filter the value of a specific post field to edit.
The dynamic portion of the hook name, $field, refers to the post field name.
Since
2.3.0
Parameters
mixed $value Value of the post field.
int $post_id Post ID.
Filter the value of a specific post field to edit.
The dynamic portion of the hook name, $field_no_prefix, refers to the post field name.
Since
2.3.0
Parameters
mixed $value Value of the post field.
int $post_id Post ID.
Filter the value of a specific post field before saving.
The dynamic portion of the hook name, $field, refers to the post field name.
Since
2.3.0
Parameters
mixed $value Value of the post field.
Filter the value of a specific field before saving.
The dynamic portion of the hook name, $field_no_prefix, refers to the post field name.
Since
2.3.0
Parameters
mixed $value Value of the post field.
Filter the value of a specific post field before saving.
The dynamic portion of the hook name, $field, refers to the post field name.
Since
2.3.0
Parameters
mixed $value Value of the post field.
Filter the value of a specific post field for display.
The dynamic portion of the hook name, $field, refers to the post field name.
Since
2.3.0
Parameters
mixed $value Value of the prefixed post field.
int $post_id Post ID.
string $context Context for how to sanitize the field. Possible values include 'raw', 'edit', 'db', 'display', 'attribute' and 'js'.
Definition at line 1898 of file wp-includes/post.php.
References $field, $post_id, $value, apply_filters(), elseif, esc_attr(), esc_js(), format_to_edit(), str_replace, and user_can_richedit().
Referenced by WP_Post\__get(), get_post_field(), post_exists(), sanitize_post(), and set_post_type().
set_post_thumbnail ($post, $thumbnail_id)
Set a post thumbnail.
Since
3.1.0
Parameters
int | WP_Post $post Post ID or post object where thumbnail should be attached.
int $thumbnail_id Thumbnail to attach.
Returns
int|bool True on success, false on failure.
Definition at line 5814 of file wp-includes/post.php.
References $post, $thumbnail_id, absint(), delete_post_meta(), get_post(), update_post_meta(), and wp_get_attachment_image().
Referenced by wp_xmlrpc_server\_insert_post(), GFFormsModel\create_post(), wp_xmlrpc_server\mw_editPost(), wp_xmlrpc_server\mw_newPost(), wp_ajax_set_attachment_thumbnail(), and wp_ajax_set_post_thumbnail().
set_post_type ($post_id = 0, $post_type = 'post')
Update the post type for the post ID.
The page or post cache will be cleaned for the post ID.
Since
2.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Optional. Post ID to change post type. Default 0.
string $post_type Optional. Post type. Accepts 'post' or 'page' to name a few. Default 'post'.
Returns
int|false Amount of rows changed. Should be 1 for success and 0 for failure.
Definition at line 1568 of file wp-includes/post.php.
References $post_id, $post_type, $wpdb, clean_post_cache(), and sanitize_post_field().
stick_post ($post_id)
Make a post sticky.
Sticky posts should be displayed at the top of the front page.
Since
2.7.0
Parameters
int $post_id Post ID.
Definition at line 2044 of file wp-includes/post.php.
References $post_id, get_option(), and update_option().
Referenced by wp_xmlrpc_server\_toggle_sticky(), bulk_edit_posts(), and edit_post().
trackback_url_list ($tb_list, $post_id)
Do trackbacks for a list of URLs.
Since
1.0.0
Parameters
string $tb_list Comma separated list of URLs.
int $post_id Post ID.
Definition at line 4012 of file wp-includes/post.php.
References $excerpt, $post_id, $tb_url, ARRAY_A, get_post(), trackback(), and wp_unslash().
unstick_post ($post_id)
Un-stick a post.
Sticky posts should be displayed at the top of the front page.
Since
2.7.0
Parameters
int $post_id Post ID.
Definition at line 2065 of file wp-includes/post.php.
References $post_id, get_option(), and update_option().
Referenced by _reset_front_page_settings_for_post(), wp_xmlrpc_server\_toggle_sticky(), bulk_edit_posts(), and edit_post().
update_attached_file ($attachment_id, $file)
Update attachment file path based on attachment ID.
Used to update the file path of the attachment, which uses post meta name '_wp_attached_file' to store the path of the attachment.
Since
2.1.0
Parameters
int $attachment_id Attachment ID.
string $file File path for the attachment.
Returns
bool True on success, false on failure.
Filter the path to the attached file to update.
Since
2.1.0
Parameters
string $file Path to the attached file to update.
int $attachment_id Attachment ID.
Definition at line 218 of file wp-includes/post.php.
References $file, _wp_relative_upload_path(), apply_filters(), delete_post_meta(), get_post(), and update_post_meta().
Referenced by upgrade_160(), wp_insert_post(), wp_restore_image(), and wp_save_image().
update_post_cache (& $posts)
Updates posts in cache.
Since
1.5.1
Parameters
array $posts Array of post objects, passed by reference.
Definition at line 5474 of file wp-includes/post.php.
References $post, and wp_cache_add().
Referenced by get_children(), get_pages(), update_page_cache(), and update_post_caches().
update_post_caches (& $posts, $post_type = 'post', $update_term_cache = true, $update_meta_cache = true)
Call major cache updating functions for list of Post objects.
Since
1.5.0
Parameters
array $posts Array of Post objects
string $post_type Optional. Post type. Default 'post'.
bool $update_term_cache Optional. Whether to update the term cache. Default true.
bool $update_meta_cache Optional. Whether to update the meta cache. Default true.
Definition at line 5550 of file wp-includes/post.php.
References $post, $post_type, elseif, update_object_term_cache(), update_post_cache(), and update_postmeta_cache().
Referenced by _prime_post_caches(), and WP_Query\get_posts().
update_post_meta ($post_id, $meta_key, $meta_value, $prev_value = '')
Update post meta field based on post ID.
Use the $prev_value parameter to differentiate between meta fields with the same key and post ID.
If the meta field for the post does not exist, it will be added.
Since
1.5.0
Parameters
int $post_id Post ID.
string $meta_key Metadata key.
mixed $meta_value Metadata value. Must be serializable if non-scalar.
mixed $prev_value Optional. Previous value to check before removing. Default empty.
Returns
int|bool Meta ID if the key didn't exist, true on successful update, false on failure.
Definition at line 1733 of file wp-includes/post.php.
References $post_id, update_metadata(), and wp_is_post_revision().
Referenced by GravityView_API_Test\_get_new_view_id(), _wp_check_split_terms_in_menus(), Custom_Image_Header\ajax_header_add(), GV_UnitTest_Factory_For_View\create_object(), Custom_Image_Header\customize_set_last_used(), edit_post(), GravityView_Edit_Entry_Render\maybe_update_post_fields(), media_upload_form_handler(), GravityView_Admin_Views\save_postdata(), Custom_Image_Header\set_header_image(), set_post_thumbnail(), WP_Embed\shortcode(), update_attached_file(), GravityView_Migrate\update_search_on_views(), wp_ajax_save_attachment(), wp_ajax_upload_attachment(), wp_ajax_wp_remove_post_lock(), wp_generate_attachment_metadata(), wp_insert_post(), wp_restore_image(), wp_restore_post_revision(), wp_save_image(), wp_update_attachment_metadata(), and wp_update_nav_menu_item().
update_postmeta_cache ($post_ids)
Updates metadata cache for list of post IDs.
Performs SQL query to retrieve the metadata for the post IDs and updates the metadata cache for the posts. Therefore, the functions, which call this function, do not need to perform SQL queries on their own.
Since
2.1.0
Parameters
array $post_ids List of post IDs.
Returns
array|false Returns false if there is nothing to update or an array of metadata.
Definition at line 5599 of file wp-includes/post.php.
References update_meta_cache().
Referenced by update_post_caches().
wp_add_post_tags ($post_id = 0, $tags = '')
Add tags to a post.
See also
wp_set_post_tags()
Since
2.3.0
Parameters
int $post_id Optional. The Post ID. Does not default to the ID of the global $post.
string | array $tags Optional. An array of tags to set for the post, or a string of tags separated by commas. Default empty.
Returns
array|false|WP_Error Array of affected term IDs. WP_Error or false on failure.
Definition at line 3714 of file wp-includes/post.php.
References $post_id, $tags, and wp_set_post_tags().
wp_attachment_is ($type, $post_id = 0)
Verifies an attachment is of a given type.
Since
4.2.0
Parameters
string $type Attachment type. Accepts 'image', 'audio', or 'video'.
int | WP_Post $post_id Optional. Attachment ID. Default 0.
Returns
bool True if one of the accepted types, false otherwise.
Definition at line 4997 of file wp-includes/post.php.
References $file, $post, $post_id, get_attached_file(), get_post(), wp_check_filetype(), wp_get_audio_extensions(), and wp_get_video_extensions().
Referenced by edit_form_image_editor(), get_oembed_response_data_rich(), prepend_attachment(), wp_ajax_save_attachment(), wp_ajax_send_attachment_to_editor(), wp_attachment_is_image(), wp_enqueue_media(), and wp_generate_attachment_metadata().
wp_attachment_is_image ($post = 0)
Checks if the attachment is an image.
Since
2.1.0
4.2.0 Modified into wrapper for wp_attachment_is() and allowed WP_Post object to be passed.
Parameters
int | WP_Post $post Optional. Attachment ID. Default 0.
Returns
bool Whether the attachment is an image.
Definition at line 5047 of file wp-includes/post.php.
References $post, and wp_attachment_is().
Referenced by edit_form_image_editor(), get_attachment_icon_src(), get_media_item(), get_oembed_response_data_rich(), image_downsize(), twentyfifteen_scripts(), twentyfourteen_content_width(), and twentyfourteen_scripts().
wp_check_for_changed_slugs ($post_id, $post, $post_before)
Check for changed slugs for published post objects and save the old slug.
The function is used when a post object of any type is updated, by comparing the current and previous post objects.
If the slug was changed and not already part of the old slugs then it will be added to the post meta field ('_wp_old_slug') for storing old slugs for that post.
The most logically usage of this function is redirecting changed post objects, so that those that linked to an changed post will be redirected to the new post.
Since
2.1.0
Parameters
int $post_id Post ID.
WP_Post $post The Post Object
WP_Post $post_before The Previous Post Object
Definition at line 5198 of file wp-includes/post.php.
References $post, $post_id, add_post_meta(), delete_post_meta(), get_post_meta(), get_post_type(), and is_post_type_hierarchical().
wp_check_post_hierarchy_for_loops ($post_parent, $post_ID)
Check the given subset of the post hierarchy for hierarchy loops.
Prevents loops from forming and breaks those that it finds. Attached to the 'wp_insert_post_parent' filter.
Since
3.1.0
See also
wp_find_hierarchy_loop()
Parameters
int $post_parent ID of the parent for the post we're checking.
int $post_ID ID of the post we're checking.
Returns
int The new post_parent for the post, 0 otherwise.
Definition at line 5777 of file wp-includes/post.php.
References $post_ID, wp_find_hierarchy_loop(), and wp_update_post().
wp_count_attachments ($mime_type = '')
Count number of attachments for the mime type(s).
If you set the optional mime_type parameter, then an array will still be returned, but will only have the item you are looking for. It does not give you the number of attachments that are children of a post. You can get that by counting the number of children that post has.
Since
2.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string | array $mime_type Optional. Array or comma-separated list of MIME patterns. Default empty.
Returns
object An object containing the attachment counts by mime type.
Modify returned attachment counts by mime type.
Since
3.7.0
Parameters
object $counts An object containing the attachment counts by mime type.
string $mime_type The mime type pattern used to filter the attachments counted.
Definition at line 2187 of file wp-includes/post.php.
References $count, $wpdb, apply_filters(), ARRAY_A, and wp_post_mime_type_where().
Referenced by media_upload_library_form().
wp_count_posts ($type = 'post', $perm = '')
Count number of posts of a post type and if user has permissions to view.
This function provides an efficient method of finding the amount of post's type a blog has. Another method is to count the amount of items in get_posts(), but that method has a lot of overhead with doing so. Therefore, when developing for 2.5+, use this function instead.
The $perm parameter checks for 'readable' value and if the user can read private posts, it will display that for the user that is signed in.
Since
2.5.0
wpdb $wpdb WordPress database abstraction object.
Parameters
string $type Optional. Post type to retrieve count. Default 'post'.
string $perm Optional. 'readable' or empty. Default empty.
Returns
object Number of posts for each status.
This filter is documented in wp-includes/post.php
Modify returned post counts by status for the current post type.
Since
3.7.0
Parameters
object $counts An object containing the current post_type's post counts by status.
string $type Post type.
string $perm The permission to determine if the posts are 'readable' by the current user.
Definition at line 2122 of file wp-includes/post.php.
References $post_type_object, $wpdb, _count_posts_cache_key(), apply_filters(), ARRAY_A, current_user_can(), get_current_user_id(), get_post_stati(), get_post_type_object(), object, post_type_exists(), wp_cache_get(), and wp_cache_set().
Referenced by get_available_post_statuses(), WP_Posts_List_Table\get_views(), WP_Posts_List_Table\prepare_items(), and wp_dashboard_right_now().
wp_delete_attachment ($post_id, $force_delete = false)
Trash or delete an attachment.
When an attachment is permanently deleted, the file will also be removed. Deletion removes all post meta fields, taxonomy, comments, etc. associated with the attachment (except the main post).
The attachment is moved to the trash instead of permanently deleted unless trash for media is disabled, item is already in the trash, or $force_delete is true.
Since
2.0.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int $post_id Attachment ID.
bool $force_delete Optional. Whether to bypass trash and force deletion. Default false.
Returns
mixed False on failure. Post data on success.
Fires before an attachment is deleted, at the start of wp_delete_attachment().
Since
2.0.0
Parameters
int $post_id Attachment ID.
This action is documented in wp-includes/post.php
This action is documented in wp-includes/post.php
This filter is documented in wp-includes/functions.php
This filter is documented in wp-includes/functions.php
This filter is documented in wp-includes/functions.php
Definition at line 4700 of file wp-includes/post.php.
References $file, $post, $post_id, $size, $wpdb, apply_filters(), clean_post_cache(), delete_metadata(), delete_metadata_by_mid(), delete_post_meta(), delete_transient(), do_action(), get_attached_file(), get_object_taxonomies(), get_post_meta(), is_multisite(), null, path_join(), str_replace, wp_defer_comment_counting(), wp_delete_comment(), wp_delete_file(), wp_delete_object_term_relationships(), wp_get_attachment_metadata(), wp_trash_post(), and wp_upload_dir().
Referenced by File_Upload_Upgrader\cleanup(), wp_delete_post(), and wp_import_cleanup().
wp_delete_auto_drafts ()
Delete auto-drafts for new posts that are > 7 days old.
Since
3.4.0
wpdb $wpdb WordPress database abstraction object.
Definition at line 5848 of file wp-includes/post.php.
References $wpdb, and wp_delete_post().
wp_delete_post ($postid = 0, $force_delete = false)
Trash or delete a post or page.
When the post and page is permanently deleted, everything that is tied to it is deleted also. This includes comments, post meta fields, and terms associated with the post.
The post or page is moved to trash instead of permanently deleted unless trash is disabled, item is already in the trash, or $force_delete is true.
Since
1.0.0
wpdb $wpdb WordPress database abstraction object.
See also
wp_delete_attachment()
wp_trash_post()
Parameters
int $postid Optional. Post ID. Default 0.
bool $force_delete Optional. Whether to bypass trash and force deletion. Default false.
Returns
array|false|WP_Post False on failure.
Filter whether a post deletion should take place.
Since
4.4.0
Parameters
bool $delete Whether to go forward with deletion.
WP_Post $post Post object.
bool $force_delete Whether to bypass the trash.
Fires before a post is deleted, at the start of wp_delete_post().
Since
3.2.0
See also
wp_delete_post()
Parameters
int $postid Post ID.
Fires immediately before a post is deleted from the database.
Since
1.2.0
Parameters
int $postid Post ID.
Fires immediately after a post is deleted from the database.
Since
2.2.0
Parameters
int $postid Post ID.
Fires after a post is deleted, at the conclusion of wp_delete_post().
Since
3.2.0
See also
wp_delete_post()
Parameters
int $postid Post ID.
Definition at line 2359 of file wp-includes/post.php.
References $post, $revision_id, $wpdb, apply_filters(), clean_post_cache(), delete_metadata_by_mid(), delete_post_meta(), do_action(), get_object_taxonomies(), get_post_status(), is_post_type_hierarchical(), null, wp_clear_scheduled_hook(), wp_defer_comment_counting(), wp_delete_attachment(), wp_delete_comment(), wp_delete_object_term_relationships(), wp_delete_post_revision(), and wp_trash_post().
Referenced by _delete_all_posts(), _wp_delete_orphaned_draft_menu_items(), _wp_delete_post_menu_item(), _wp_delete_tax_menu_item(), wp_xmlrpc_server\blogger_deletePost(), GravityView_Uninstall\delete_posts(), WP_Canonical_UnitTestCase\delete_shared_fixtures(), WP_Customize_Nav_Menu_Item_Setting\update(), wp_ajax_delete_page(), wp_ajax_delete_post(), wp_ajax_save_attachment(), wp_delete_auto_drafts(), wp_delete_nav_menu(), wp_delete_post_revision(), wp_delete_user(), wp_xmlrpc_server\wp_deletePage(), wp_xmlrpc_server\wp_deletePost(), wp_nav_menu_update_menu_items(), wp_scheduled_delete(), wp_trash_post(), and wpmu_delete_user().
wp_get_attachment_metadata ($post_id = 0, $unfiltered = false)
Retrieve attachment meta field for attachment ID.
Since
2.1.0
Parameters
int $post_id Attachment ID. Default 0.
bool $unfiltered Optional. If true, filters are not run. Default false.
Returns
mixed Attachment meta field. False on failure.
Filter the attachment meta data.
Since
2.1.0
Parameters
array | bool $data Array of meta data for the given attachment, or false if the object does not exist.
int $post_id Attachment ID.
Definition at line 4806 of file wp-includes/post.php.
References $post, $post_id, apply_filters(), get_post(), and get_post_meta().
Referenced by wp_xmlrpc_server\_prepare_media_item(), attachment_id3_data_meta_box(), attachment_submitbox_metadata(), edit_form_image_editor(), edit_post(), gallery_shortcode(), get_media_item(), get_uploaded_header_images(), image_downsize(), image_get_intermediate_size(), prepend_attachment(), Custom_Image_Header\step_2(), wp_ajax_save_attachment(), wp_delete_attachment(), wp_get_attachment_thumb_file(), wp_image_editor(), wp_maybe_generate_attachment_metadata(), wp_playlist_shortcode(), wp_prepare_attachment_for_js(), wp_restore_image(), and wp_save_image().
wp_get_attachment_thumb_file ($post_id = 0)
Retrieve thumbnail for an attachment.
Since
2.1.0
Parameters
int $post_id Optional. Attachment ID. Default 0.
Returns
string|false False on failure. Thumbnail file path on success.
Filter the attachment thumbnail file path.
Since
2.1.0
Parameters
string $thumbfile File path to the attachment thumbnail.
int $post_id Attachment ID.
Definition at line 4930 of file wp-includes/post.php.
References $file, $post, $post_id, apply_filters(), get_attached_file(), get_post(), str_replace, and wp_get_attachment_metadata().
Referenced by image_downsize(), and wp_get_attachment_thumb_url().
wp_get_attachment_thumb_url ($post_id = 0)
Retrieve URL for an attachment thumbnail.
Since
2.1.0
Parameters
int $post_id Optional. Attachment ID. Default 0.
Returns
string|false False on failure. Thumbnail URL on success.
Filter the attachment thumbnail URL.
Since
2.1.0
Parameters
string $url URL for the attachment thumbnail.
int $post_id Attachment ID.
Definition at line 4961 of file wp-includes/post.php.
References $post, $post_id, $url, apply_filters(), get_post(), image_downsize(), str_replace, wp_get_attachment_thumb_file(), and wp_get_attachment_url().
Referenced by get_attachment_icon_src().
wp_get_attachment_url ($post_id = 0)
Retrieve the URL for an attachment.
Since
2.1.0
string $pagenow
Parameters
int $post_id Optional. Attachment ID. Default 0.
Returns
string|false Attachment URL, otherwise false.
Filter the attachment URL.
Since
2.1.0
Parameters
string $url URL for the given attachment.
int $post_id Attachment ID.
Definition at line 4866 of file wp-includes/post.php.
References $file, $GLOBALS, $post, $post_id, $url, _wp_get_attachment_relative_path(), apply_filters(), elseif, get_post(), get_post_meta(), get_the_guid(), is_admin(), is_ssl(), set_url_scheme(), str_replace, trailingslashit(), and wp_upload_dir().
Referenced by _delete_attachment_theme_mod(), _load_image_to_edit_path(), wp_xmlrpc_server\_prepare_media_item(), Custom_Image_Header\ajax_header_crop(), attachment_submitbox_metadata(), WP_Site_Icon\create_attachment_object(), Custom_Image_Header\create_attachment_object(), edit_form_image_editor(), get_attachment_fields_to_edit(), get_attachment_icon_src(), get_the_attachment_link(), get_uploaded_header_images(), image_downsize(), image_get_intermediate_size(), image_link_input_fields(), media_sideload_image(), prepend_attachment(), Custom_Image_Header\step_3(), wp_ajax_crop_image(), wp_audio_shortcode(), wp_get_attachment_link(), wp_get_attachment_thumb_url(), wp_playlist_shortcode(), wp_prepare_attachment_for_js(), wp_save_image(), and wp_video_shortcode().
wp_get_post_categories ($post_id = 0, $args = array())
Retrieve the list of categories for a post.
Compatibility layer for themes and plugins. Also an easy layer of abstraction away from the complexity of the taxonomy layer.
Since
2.1.0
See also
wp_get_object_terms()
Parameters
int $post_id Optional. The Post ID. Does not default to the ID of the global $post. Default 0.
array $args Optional. Category arguments. Default empty.
Returns
array List of categories.
Definition at line 2740 of file wp-includes/post.php.
References $cats, $post_id, wp_get_object_terms(), and wp_parse_args().
Referenced by wp_xmlrpc_server\_prepare_page(), wp_xmlrpc_server\blogger_getPost(), wp_xmlrpc_server\blogger_getRecentPosts(), bulk_edit_posts(), wp_xmlrpc_server\mt_getPostCategories(), wp_xmlrpc_server\mt_publishPost(), wp_xmlrpc_server\mw_getPost(), wp_xmlrpc_server\mw_getRecentPosts(), and wp_get_post_cats().
wp_get_post_parent_id ($post_ID)
Return the post's parent's post_ID.
Since
3.1.0
Parameters
int $post_ID
Returns
int|false Post parent ID, otherwise false.
Definition at line 5756 of file wp-includes/post.php.
References $post, $post_ID, get_post(), and is_wp_error().
wp_get_post_tags ($post_id = 0, $args = array())
Retrieve the tags for a post.
There is only one default for this function, called 'fields' and by default is set to 'all'. There are other defaults that can be overridden in wp_get_object_terms().
Since
2.3.0
Parameters
int $post_id Optional. The Post ID. Does not default to the ID of the global $post. Default 0.
array $args Optional. Overwrite the defaults
Returns
array List of post tags.
Definition at line 2764 of file wp-includes/post.php.
References $post_id, and wp_get_post_terms().
Referenced by wp_xmlrpc_server\mw_getPost(), and wp_xmlrpc_server\mw_getRecentPosts().
wp_get_post_terms ($post_id = 0, $taxonomy = 'post_tag', $args = array())
Retrieve the terms for a post.
There is only one default for this function, called 'fields' and by default is set to 'all'. There are other defaults that can be overridden in wp_get_object_terms().
Since
2.8.0
Parameters
int $post_id Optional. The Post ID. Does not default to the ID of the global $post. Default 0.
string $taxonomy Optional. The taxonomy for which to retrieve terms. Default 'post_tag'.
array $args Optional. wp_get_object_terms() arguments. Default empty array.
Returns
array|WP_Error List of post terms or empty array if no terms were found. WP_Error object if $taxonomy doesn't exist.
Definition at line 2784 of file wp-includes/post.php.
References $post_id, $tags, wp_get_object_terms(), and wp_parse_args().
Referenced by WP_Customize_Nav_Menu_Item_Setting\populate_value(), and wp_get_post_tags().
wp_get_recent_posts ($args = array(), $output = ARRAY_A)
Retrieve a number of recent posts.
Since
1.0.0
See also
get_posts()
Parameters
array $args Optional. Arguments to retrieve posts. Default empty array.
string $output Optional. Type of output. Accepts ARRAY_A or ''. Default ARRAY_A.
Returns
array|false Associative array if $output equals ARRAY_A, array or false if no results.
Definition at line 2806 of file wp-includes/post.php.
References $output, __, _deprecated_argument(), absint(), ARRAY_A, get_posts(), and wp_parse_args().
Referenced by wp_xmlrpc_server\blogger_getRecentPosts(), wp_xmlrpc_server\mt_getRecentPostTitles(), wp_xmlrpc_server\mw_getRecentPosts(), and wp_xmlrpc_server\wp_getPosts().
wp_insert_attachment ($args, $file = false, $parent = 0)
Insert an attachment.
If you set the 'ID' in the $args parameter, it will mean that you are updating and attempt to update the attachment. You can also set the attachment name or title by setting the key 'post_name' or 'post_title'.
You can set the dates for the attachment manually by setting the 'post_date' and 'post_date_gmt' keys' values.
By default, the comments will use the default settings for whether the comments are allowed. You can close them manually or keep them open by setting the value for the 'comment_status' key.
Since
2.0.0
See also
wp_insert_post()
Parameters
string | array $args Arguments for inserting an attachment.
string $file Optional. Filename.
int $parent Optional. Parent post ID.
Returns
int Attachment ID.
Definition at line 4664 of file wp-includes/post.php.
References $file, wp_insert_post(), and wp_parse_args().
Referenced by File_Upload_Upgrader\__construct(), WP_UnitTestCase\_make_attachment(), WP_UnitTest_Factory_For_Attachment\create_object(), WP_UnitTest_Factory_For_Attachment\create_upload_object(), WP_Site_Icon\insert_attachment(), Custom_Image_Header\insert_attachment(), media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), wp_xmlrpc_server\mw_newMediaObject(), Custom_Image_Header\step_2_manage_upload(), wp_ajax_crop_image(), wp_generate_attachment_metadata(), wp_import_handle_upload(), and wp_update_post().
wp_insert_post ($postarr, $wp_error = false)
Insert or update a post.
If the $postarr parameter has 'ID' set to a value, then post will be updated.
You can set the post date manually, by setting the values for 'post_date' and 'post_date_gmt' keys. You can close the comments or open the comments by setting the value for 'comment_status' key.
Since
1.0.0
4.2.0 Support was added for encoding emoji in the post title, content, and excerpt.
4.4.0 A 'meta_input' array can now be passed to $postarr to add post meta data.
See also
sanitize_post() wpdb $wpdb WordPress database abstraction object.
Parameters
array $postarr { An array of elements that make up a post to update or insert.
int $ID The post ID. If equal to something other than 0, the post with that ID will be updated. Default 0. int $post_author The ID of the user who added the post. Default is the current user ID. string $post_date The date of the post. Default is the current time. string $post_date_gmt The date of the post in the GMT timezone. Default is the value of $post_date. mixed $post_content The post content. Default empty. string $post_content_filtered The filtered post content. Default empty. string $post_title The post title. Default empty. string $post_excerpt The post excerpt. Default empty. string $post_status The post status. Default 'draft'. string $post_type The post type. Default 'post'. string $comment_status Whether the post can accept comments. Accepts 'open' or 'closed'. Default is the value of 'default_comment_status' option. string $ping_status Whether the post can accept pings. Accepts 'open' or 'closed'. Default is the value of 'default_ping_status' option. string $post_password The password to access the post. Default empty. string $post_name The post name. Default is the sanitized post title when creating a new post. string $to_ping Space or carriage return-separated list of URLs to ping. Default empty. string $pinged Space or carriage return-separated list of URLs that have been pinged. Default empty. string $post_modified The date when the post was last modified. Default is the current time. string $post_modified_gmt The date when the post was last modified in the GMT timezone. Default is the current time. int $post_parent Set this for the post it belongs to, if any. Default 0. int $menu_order The order the post should be displayed in. Default 0. string $post_mime_type The mime type of the post. Default empty. string $guid Global Unique ID for referencing the post. Default empty. array $tax_input Array of taxonomy terms keyed by their taxonomy name. Default empty. array $meta_input Array of post meta values keyed by their post meta key. Default empty. }
Parameters
bool $wp_error Optional. Whether to allow return of WP_Error on failure. Default false.
Returns
int|WP_Error The post ID on success. The value 0 or WP_Error on failure.
Filter whether the post should be considered "empty".
The post is considered "empty" if both:
The post type supports the title, editor, and excerpt fields
The title, editor, and excerpt fields are all empty
Returning a truthy value to the filter will effectively short-circuit the new post being inserted, returning 0. If $wp_error is true, a WP_Error will be returned instead.
Since
3.3.0
Parameters
bool $maybe_empty Whether the post should be considered "empty".
array $postarr Array of post data.
Filter the post parent – used to check for and prevent hierarchy loops.
Since
3.1.0
Parameters
int $post_parent Post parent ID.
int $post_ID Post ID.
array $new_postarr Array of parsed post data.
array $postarr Array of sanitized, but otherwise unmodified post data.
Filter attachment post data before it is updated in or added to the database.
Since
3.9.0
Parameters
array $data An array of sanitized attachment post data.
array $postarr An array of unsanitized attachment post data.
Filter slashed post data just before it is inserted into the database.
Since
2.7.0
Parameters
array $data An array of slashed post data.
array $postarr An array of sanitized, but otherwise unmodified post data.
Fires immediately before an existing post is updated in the database.
Since
2.5.0
Parameters
int $post_ID Post ID.
array $data Array of unslashed post data.
Fires once an existing attachment has been updated.
Since
2.0.0
Parameters
int $post_ID Attachment ID.
Fires once an existing attachment has been updated.
Since
4.4.0
Parameters
int $post_ID Post ID.
WP_Post $post_after Post object following the update.
WP_Post $post_before Post object before the update.
Fires once an attachment has been added.
Since
2.0.0
Parameters
int $post_ID Attachment ID.
Fires once an existing post has been updated.
Since
1.2.0
Parameters
int $post_ID Post ID.
WP_Post $post Post object.
Fires once an existing post has been updated.
Since
3.0.0
Parameters
int $post_ID Post ID.
WP_Post $post_after Post object following the update.
WP_Post $post_before Post object before the update.
Fires once a post has been saved.
The dynamic portion of the hook name, $post->post_type, refers to the post type slug.
Since
3.7.0
Parameters
int $post_ID Post ID.
WP_Post $post Post object.
bool $update Whether this is an existing post being updated or not.
Fires once a post has been saved.
Since
1.5.0
Parameters
int $post_ID Post ID.
WP_Post $post Post object.
bool $update Whether this is an existing post being updated or not.
Fires once a post has been saved.
Since
2.0.0
Parameters
int $post_ID Post ID.
WP_Post $post Post object.
bool $update Whether this is an existing post being updated or not.
Definition at line 2896 of file wp-includes/post.php.
References $charset, $field, $now, $post, $post_ID, $post_title, $post_type, $tags, $update, $user_id, $value, $wpdb, __, _doing_it_wrong(), add_post_meta(), apply_filters(), clean_post_cache(), current_time(), current_user_can(), do_action(), elseif, get_current_user_id(), get_date_from_gmt(), get_default_comment_status(), get_gmt_from_date(), get_option(), get_permalink(), get_post(), get_post_field(), get_taxonomy(), is_object_in_taxonomy(), mysql2date(), post_type_supports(), sanitize_post(), sanitize_title(), sanitize_trackback_urls(), update_attached_file(), update_post_meta(), wp_checkdate(), wp_encode_emoji(), wp_get_theme(), wp_parse_args(), wp_set_post_categories(), wp_set_post_tags(), wp_set_post_terms(), wp_transition_post_status(), wp_unique_post_slug(), and wp_unslash().
Referenced by GravityView_API_Test\_get_new_view_id(), wp_xmlrpc_server\_insert_post(), _wp_put_post_revision(), wp_xmlrpc_server\blogger_newPost(), GravityView_Admin_Duplicate_View\create_duplicate(), WP_UnitTest_Factory_For_Post\create_object(), GFFormsModel\create_post(), get_default_post_to_edit(), wp_xmlrpc_server\mw_newPost(), GravityView_API_Test\test_directory_link(), wp_insert_attachment(), wp_trash_post(), wp_untrash_post(), wp_update_nav_menu_item(), wp_update_post(), and wp_write_post().
wp_match_mime_types ($wildcard_mime_types, $real_mime_types)
Check a MIME-Type against a list.
If the wildcard_mime_types parameter is a string, it must be comma separated list. If the real_mime_types is a string, it is also comma separated to create the list.
Since
2.5.0
Parameters
string | array $wildcard_mime_types Mime types, e.g. audio/mpeg or image (same as image/*) or flash (same as flash).
string | array $real_mime_types Real post mime type values.
Returns
array array(wildcard=>array(real types)).
Definition at line 2250 of file wp-includes/post.php.
References $mime, and str_replace.
Referenced by get_media_item(), WP_Media_List_Table\get_views(), media_upload_library_form(), Custom_Image_Header\step_2_manage_upload(), wp_ajax_upload_attachment(), and wp_mime_type_icon().
wp_mime_type_icon ($mime = 0)
Retrieve the icon for a MIME type.
Since
2.1.0
Parameters
string | int $mime MIME type or attachment ID.
Returns
string|false Icon, false otherwise.
Filter the icon directory path.
Since
2.0.0
Parameters
string $path Icon directory absolute path.
Filter the icon directory URI.
Since
2.0.0
Parameters
string $uri Icon directory URI.
Filter the list of icon directory URIs.
Since
2.5.0
Parameters
array $uris List of icon directory URIs.
Filter the mime type icon.
Since
2.1.0
Parameters
string $icon Path to the mime type icon.
string $mime Mime type.
int $post_id Attachment ID. Will equal 0 if the function passed the mime type.
Definition at line 5059 of file wp-includes/post.php.
References $dir, $file, $keys, $mime, $post, $post_id, $types, ABSPATH, apply_filters(), get_attached_file(), get_post(), includes_url(), str_replace, wp_cache_add(), wp_cache_get(), wp_ext2type(), wp_match_mime_types(), and WPINC.
Referenced by get_attachment_icon_src(), WP_Customize_Media_Control\to_json(), wp_get_attachment_image_src(), wp_playlist_shortcode(), and wp_prepare_attachment_for_js().
wp_post_mime_type_where ($post_mime_types, $table_alias = '')
Convert MIME types into SQL.
Since
2.5.0
Parameters
string | array $post_mime_types List of mime types or comma separated string of mime types.
string $table_alias Optional. Specify a table alias, if needed. Default empty.
Returns
string The SQL AND clause for mime searching.
Definition at line 2298 of file wp-includes/post.php.
References str_replace.
Referenced by WP_Query\get_posts(), and wp_count_attachments().
wp_publish_post ($post)
Publish a post by transitioning the post status.
Since
2.1.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | WP_Post $post Post ID or post object.
This action is documented in wp-includes/post.php
This action is documented in wp-includes/post.php
This action is documented in wp-includes/post.php
This action is documented in wp-includes/post.php
Definition at line 3475 of file wp-includes/post.php.
References $post, $wpdb, clean_post_cache(), do_action(), get_post(), and wp_transition_post_status().
Referenced by check_and_publish_future_post().
wp_set_post_categories ($post_ID = 0, $post_categories = array(), $append = false)
Set categories for a post.
If the post categories parameter is not set, then the default category is going used.
Since
2.1.0
Parameters
int $post_ID Optional. The Post ID. Does not default to the ID of the global $post. Default 0.
array | int $post_categories Optional. List of categories or ID of category. Default empty array.
bool $append If true, don't delete existing categories, just add on. If false, replace the categories with the new categories.
Returns
array|bool|WP_Error
Definition at line 3794 of file wp-includes/post.php.
References $post_ID, $post_type, elseif, get_option(), get_post_status(), get_post_type(), and wp_set_post_terms().
Referenced by GravityView_Edit_Entry_Render\maybe_update_post_fields(), wp_xmlrpc_server\mt_setPostCategories(), wp_create_categories(), wp_insert_post(), and wp_set_post_cats().
wp_set_post_tags ($post_id = 0, $tags = '', $append = false)
Set the tags for a post.
Since
2.3.0
See also
wp_set_object_terms()
Parameters
int $post_id Optional. The Post ID. Does not default to the ID of the global $post.
string | array $tags Optional. An array of tags to set for the post, or a string of tags separated by commas. Default empty.
bool $append Optional. If true, don't delete existing tags, just add on. If false, replace the tags with the new tags. Default false.
Returns
array|false|WP_Error Array of affected term IDs. WP_Error or false on failure.
Definition at line 3732 of file wp-includes/post.php.
References $post_id, $tags, and wp_set_post_terms().
Referenced by GravityView_Edit_Entry_Render\maybe_update_post_fields(), wp_add_post_tags(), and wp_insert_post().
wp_set_post_terms ($post_id = 0, $tags = '', $taxonomy = 'post_tag', $append = false)
Set the terms for a post.
Since
2.8.0
See also
wp_set_object_terms()
Parameters
int $post_id Optional. The Post ID. Does not default to the ID of the global $post.
string | array $tags Optional. An array of terms to set for the post, or a string of terms separated by commas. Default empty.
string $taxonomy Optional. Taxonomy name. Default 'post_tag'.
bool $append Optional. If true, don't delete existing terms, just add on. If false, replace the terms with the new terms. Default false.
Returns
array|false|WP_Error Array of affected term IDs. WP_Error or false on failure.
Definition at line 3751 of file wp-includes/post.php.
References $post_id, $tags, _x, is_taxonomy_hierarchical(), str_replace, and wp_set_object_terms().
Referenced by WP_UnitTest_Factory_For_Term\add_post_terms(), set_post_format(), wp_insert_post(), wp_set_post_categories(), and wp_set_post_tags().
wp_transition_post_status ($new_status, $old_status, $post)
Fires actions related to the transitioning of a post's status.
When a post is saved, the post status is "transitioned" from one status to another, though this does not always mean the status has actually changed before and after the save. This function fires a number of action hooks related to that transition: the generic 'transition_post_status' action, as well as the dynamic hooks "{$old_status}_to_{$new_status}" and "{$new_status}_{$post-\>post_type}". Note that the function does not transition the post object in the database.
For instance: When publishing a post for the first time, the post status may transition from 'draft' or some other status to 'publish'. However, if a post is already published and is simply being updated, the "old" and "new" statuses may both be 'publish' before and after the transition.
Since
2.3.0
Parameters
string $new_status Transition to this post status.
string $old_status Previous post status.
WP_Post $post Post data.
Fires when a post is transitioned from one status to another.
Since
2.3.0
Parameters
string $new_status New post status.
string $old_status Old post status.
WP_Post $post Post object.
Fires when a post is transitioned from one status to another.
The dynamic portions of the hook name, $new_status and $old status, refer to the old and new post statuses, respectively.
Since
2.3.0
Parameters
WP_Post $post Post object.
Fires when a post is transitioned from one status to another.
The dynamic portions of the hook name, $new_status and $post->post_type, refer to the new post status and post type, respectively.
Please note: When this action is hooked using a particular post status (like 'publish', as publish_{$post->post_type}), it will fire both when a post is first transitioned to that status from something else, as well as upon subsequent post updates (old and new status are both the same).
Therefore, if you are looking to only fire a callback when a post is first transitioned to a status, use the {
See also
'transition_post_status'} hook instead.
Since
2.3.0
Parameters
int $post_id Post ID.
WP_Post $post Post object.
Definition at line 3835 of file wp-includes/post.php.
References $post, and do_action().
Referenced by wp_insert_post(), and wp_publish_post().
wp_trash_post ($post_id = 0)
Move a post or page to the Trash.
If trash is disabled, the post or page is permanently deleted.
Since
2.9.0
See also
wp_delete_post()
Parameters
int $post_id Optional. Post ID. Default is ID of the global $post if EMPTY_TRASH_DAYS equals true.
Returns
false|array|WP_Post|null Post data array, otherwise false.
Fires before a post is sent to the trash.
Since
3.3.0
Parameters
int $post_id Post ID.
Fires after a post is sent to the trash.
Since
2.9.0
Parameters
int $post_id Post ID.
Definition at line 2522 of file wp-includes/post.php.
References $post, $post_id, add_post_meta(), ARRAY_A, do_action(), get_post(), wp_delete_post(), wp_insert_post(), wp_slash(), and wp_trash_post_comments().
Referenced by wp_ajax_trash_post(), wp_delete_attachment(), and wp_delete_post().
wp_trash_post_comments ($post = null)
Moves comments for a post to the trash.
Since
2.9.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | WP_Post | null $post Optional. Post ID or post object. Defaults to global $post.
Returns
mixed|void False on failure.
Fires before comments are sent to the trash.
Since
2.9.0
Parameters
int $post_id Post ID.
Fires after comments are sent to the trash.
Since
2.9.0
Parameters
int $post_id Post ID.
array $statuses Array of comment statuses.
Definition at line 2618 of file wp-includes/post.php.
References $comment, $post, $post_id, $wpdb, add_post_meta(), clean_comment_cache(), do_action(), and get_post().
Referenced by wp_trash_post().
wp_unique_post_slug ($slug, $post_ID, $post_status, $post_type, $post_parent)
Computes a unique slug for the post, when given the desired slug and some post details.
Since
2.8.0
wpdb $wpdb WordPress database abstraction object. WP_Rewrite $wp_rewrite
Parameters
string $slug The desired slug (post_name).
int $post_ID Post ID.
string $post_status No uniqueness checks are made if the post is still draft or pending.
string $post_type Post type.
int $post_parent Post parent ID.
Returns
string Unique slug for the post, based on $post_name (with a -1, -2, etc. suffix)
Filter whether the post slug would make a bad attachment slug.
Since
3.1.0
Parameters
bool $bad_slug Whether the slug would be bad as an attachment slug.
string $slug The post slug.
Filter whether the post slug would make a bad hierarchical post slug.
Since
3.1.0
Parameters
bool $bad_slug Whether the post slug would be bad in a hierarchical post context.
string $slug The post slug.
string $post_type Post type.
int $post_parent Post parent ID.
Filter whether the post slug would be bad as a flat slug.
Since
3.1.0
Parameters
bool $bad_slug Whether the post slug would be bad as a flat slug.
string $slug The post slug.
string $post_type Post type.
Filter the unique post slug.
Since
3.3.0
Parameters
string $slug The post slug.
int $post_ID Post ID.
string $post_status The post status.
string $post_type Post type.
int $post_parent Post parent ID
string $original_slug The original post slug.
Definition at line 3552 of file wp-includes/post.php.
References $post, $post_ID, $post_type, $wp_rewrite, $wpdb, _truncate_post_slug(), apply_filters(), elseif, get_option(), get_post(), and is_post_type_hierarchical().
Referenced by GravityView_Admin_Duplicate_View\create_duplicate(), get_sample_permalink(), wp_ajax_inline_save(), and wp_insert_post().
wp_untrash_post ($post_id = 0)
Restore a post or page from the Trash.
Since
2.9.0
Parameters
int $post_id Optional. Post ID. Default is ID of the global $post.
Returns
WP_Post|false WP_Post object. False on failure.
Fires before a post is restored from the trash.
Since
2.9.0
Parameters
int $post_id Post ID.
Fires after a post is restored from the trash.
Since
2.9.0
Parameters
int $post_id Post ID.
Definition at line 2569 of file wp-includes/post.php.
References $post, $post_id, ARRAY_A, delete_post_meta(), do_action(), get_post(), get_post_meta(), wp_insert_post(), wp_slash(), and wp_untrash_post_comments().
Referenced by wp_ajax_trash_post().
wp_untrash_post_comments ($post = null)
Restore comments for a post from the trash.
Since
2.9.0
wpdb $wpdb WordPress database abstraction object.
Parameters
int | WP_Post | null $post Optional. Post ID or post object. Defaults to global $post.
Returns
true|void
Fires before comments are restored for a post from the trash.
Since
2.9.0
Parameters
int $post_id Post ID.
Fires after comments are restored for a post from the trash.
Since
2.9.0
Parameters
int $post_id Post ID.
Definition at line 2674 of file wp-includes/post.php.
References $post, $post_id, $wpdb, clean_comment_cache(), delete_post_meta(), do_action(), get_post(), and get_post_meta().
Referenced by wp_untrash_post().
wp_update_attachment_metadata ($post_id, $data)
Update metadata for an attachment.
Since
2.1.0
Parameters
int $post_id Attachment ID.
array $data Attachment data.
Returns
int|bool False if $post is invalid.
Filter the updated attachment meta data.
Since
2.1.0
Parameters
array $data Array of updated attachment meta data.
int $post_id Attachment ID.
Definition at line 4837 of file wp-includes/post.php.
References $post, $post_id, apply_filters(), delete_post_meta(), get_post(), and update_post_meta().
Referenced by WP_UnitTestCase\_make_attachment(), WP_UnitTest_Factory_For_Attachment\create_upload_object(), edit_post(), WP_Site_Icon\insert_attachment(), Custom_Image_Header\insert_attachment(), media_handle_sideload(), media_handle_upload(), GFFormsModel\media_handle_upload(), wp_xmlrpc_server\mw_newMediaObject(), Custom_Image_Header\step_2(), wp_ajax_crop_image(), wp_ajax_save_attachment(), wp_generate_attachment_metadata(), wp_maybe_generate_attachment_metadata(), wp_restore_image(), and wp_save_image().
wp_update_post ($postarr = array(), $wp_error = false)
Update a post with new post data.
The date does not have to be set for drafts. You can set the date and it will not be overridden.
Since
1.0.0
Parameters
array | object $postarr Optional. Post data. Arrays are expected to be escaped, objects are not. Default array.
bool $wp_error Optional. Allow return of WP_Error on failure. Default false.
Returns
int|WP_Error The value 0 or WP_Error on failure. The post ID on success.
Definition at line 3419 of file wp-includes/post.php.
References $post, __, ARRAY_A, current_time(), get_post(), wp_insert_attachment(), wp_insert_post(), and wp_slash().
Referenced by _fix_attachment_links(), wp_xmlrpc_server\_insert_post(), wp_xmlrpc_server\blogger_editPost(), bulk_edit_posts(), GravityView_Admin_Duplicate_View\create_duplicate(), GFFormsModel\create_post(), edit_post(), media_upload_form_handler(), wp_xmlrpc_server\mt_publishPost(), wp_xmlrpc_server\mw_editPost(), WP_Press_This\save_post(), WP_UnitTest_Factory_For_Post\update_object(), wp_ajax_save_attachment(), wp_ajax_save_attachment_compat(), wp_ajax_save_attachment_order(), wp_ajax_send_attachment_to_editor(), wp_check_post_hierarchy_for_loops(), wp_restore_post_revision(), and wp_update_nav_menu_item().