GravityView: wp-links-opml.php File Reference
wp-links-opml.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$bookmarks = get_bookmarks(array("category" => $cat->term_id))
else $cats = get_categories(array('taxonomy' => 'link_category', 'hierarchical' => 0, 'include' => $link_cat))
$link_cat = ''
endforeach
if (!empty($_GET['link_cat']))
Variable Documentation
$bookmarks = get_bookmarks(array("category" => $cat->term_id))
Definition at line 60 of file wp-links-opml.php.
Referenced by _walk_bookmarks(), get_bookmarks(), and wp_list_bookmarks().
else $cats = get_categories(array('taxonomy' => 'link_category', 'hierarchical' => 0, 'include' => $link_cat))
Definition at line 45 of file wp-links-opml.php.
Referenced by bulk_edit_posts(), export_wp(), get_linkcatname(), get_links_list(), get_permalink(), wp_xmlrpc_server\mt_getCategoryList(), wp_xmlrpc_server\mt_publishPost(), wp_xmlrpc_server\mw_getCategories(), wp_get_link_cats(), wp_get_post_categories(), and wp_list_bookmarks().
$link_cat = ''
Definition at line 18 of file wp-links-opml.php.
Referenced by WP_Widget_Links\form().
endforeach
Definition at line 73 of file wp-links-opml.php.
if(!empty($_GET['link_cat']))
Definition at line 19 of file wp-links-opml.php.