GravityView: wp-load.php File Reference
wp-load.php File Reference
Variables
$die
$path = wp_guess_url() . '/wp-admin/setup-config.php'
const ABSPATH dirname(__FILE__) . '/'
Bootstrap file for setting the ABSPATH constant and loading the wp-config.php file.
if(file_exists(ABSPATH. 'wp-config.php')) elseif(@file_exists(dirname(ABSPATH). '/wp-config.php')&&!@file_exists(dirname(ABSPATH). '/wp-settings.php')) else
const WP_CONTENT_DIR (false===strpos($_SERVER['REQUEST_URI'], 'setup-config')) ABSPATH . 'wp-content'
Variable Documentation
$die
Initial value:
= sprintf(
        __( "There doesn't seem to be a %s file. I need this before we can get started." ),
        '<code>wp-config.php</code>'
    ) . '</p>'
Definition at line 75 of file wp-load.php.
$path = wp_guess_url() . '/wp-admin/setup-config.php'
Definition at line 56 of file wp-load.php.
Referenced by GF_Installation_Wizard\__construct(), GFAutoUpgrade\__construct(), wp_xmlrpc_server\_multisite_getUsersBlogs(), _wp_relative_upload_path(), WP_Filesystem_MockFS\abspath(), PHPMailer\addAttachment(), PHPMailer\addEmbeddedImage(), admin_url(), PHPMailer\attachAll(), attachment_url_to_postid(), WP_Filesystem_MockFS\chdir(), WP_MS_Users_List_Table\column_blogs(), SimplePie_Misc\compress_parse_url(), content_url(), GFFormsModel\copy_post_image(), create_empty_blog(), WP_UnitTestCase\delete_folders(), WP_Filesystem_MockFS\dirlist(), WP_Filesystem_Direct\dirlist(), WP_Filesystem_ftpsockets\dirlist(), WP_Filesystem_FTPext\dirlist(), WP_Filesystem_SSH2\dirlist(), WP_REST_Server\dispatch(), do_robots(), domain_exists(), _WP_Editors\editor_settings(), PHPMailer\encodeFile(), WP_Filesystem_MockFS\exists(), file_is_displayable_image(), file_is_valid_image(), get_admin_url(), get_admin_users_for_domain(), get_blog_id_from_url(), get_blogaddress_by_domain(), GF_Field_CAPTCHA\get_captcha(), get_category_by_path(), get_dashboard_url(), get_file(), get_home_url(), GFEntryList\get_icon_url(), get_id_from_blogname(), GF_Field_CAPTCHA\get_math_captcha(), get_network_by_path(), get_rest_url(), get_site_by_path(), get_site_url(), getid3_lib\getFileSizeSyscall(), ftp_base\glob(), gravityview_register_default_templates(), home_url(), includes_url(), RGXML\indent(), insert_blog(), RGXML\is_attribute(), WP_Filesystem_MockFS\is_dir(), WP_Filesystem_Direct\is_dir(), WP_Filesystem_FTPext\is_dir(), WP_Filesystem_ftpsockets\is_dir(), WP_Filesystem_SSH2\is_dir(), load_child_theme_textdomain(), load_muplugin_textdomain(), GravityView_Extension\load_plugin_textdomain(), load_plugin_textdomain(), WP_Theme\load_textdomain(), load_theme_textdomain(), WP_Filesystem_MockFS\locate_node(), WP_Filesystem_MockFS\locate_parent_node(), WP_Http\make_absolute_url(), getid3_lib\mb_basename(), PHPMailer\mb_pathinfo(), WP_Filesystem_MockFS\mkdir(), WP_Filesystem_Direct\mkdir(), WP_Filesystem_FTPext\mkdir(), WP_Filesystem_ftpsockets\mkdir(), WP_Filesystem_SSH2\mkdir(), ms_not_installed(), network_admin_url(), network_home_url(), network_site_url(), path_is_absolute(), path_join(), plugins_url(), populate_network(), WP_Filesystem_MockFS\put_contents(), recurse_dirsize(), GravityView_Metabox_Tab\render(), rest_url(), WP_Filesystem_Direct\rmdir(), WP_Filesystem_FTPext\rmdir(), WP_Filesystem_ftpsockets\rmdir(), WP_Filesystem_SSH2\rmdir(), WP_UnitTestCase\rmdir(), WP_UnitTestCase\scandir(), WP_Theme\scandir(), self_admin_url(), RGXML\serialize(), Spy_REST_Server\serve_request(), WP_REST_Server\serve_request(), GF_Field_FileUpload\set_permissions(), GFFormsModel\set_permissions(), WP_Filesystem_MockFS\setfs(), WP_Filesystem_SSH2\sftp_path(), site_url(), unzip_file(), user_admin_url(), weblog_ping(), win_is_writable(), wp_basename(), wp_get_image_editor(), wp_guess_url(), wp_is_stream(), wp_is_writable(), wp_normalize_path(), wp_save_image(), wpmu_create_blog(), wpmu_signup_blog(), wpmu_signup_blog_notification(), and wpmu_validate_blog_signup().
const ABSPATH dirname(__FILE__) . '/'
Bootstrap file for setting the ABSPATH constant and loading the wp-config.php file.
The wp-config.php file will then load the wp-settings.php file, which will then set up the WordPress environment.
If the wp-config.php file is not found then an error will be displayed asking the visitor to set up the wp-config.php file.
Will also search for wp-config.php in WordPress' parent directory to allow the WordPress directory to remain untouched.Define ABSPATH as this file's directory
Definition at line 22 of file wp-load.php.
if (file_exists(ABSPATH. 'wp-config.php')) elseif (@file_exists(dirname(ABSPATH). '/wp-config.php')&&!@file_exists(dirname(ABSPATH). '/wp-settings.php')) else
Initial value:
{
    define( 'WPINC', 'wp-includes' )
The config file resides in ABSPATH
The config file resides one level above ABSPATH but is not part of another install
Definition at line 44 of file wp-load.php.
const WP_CONTENT_DIR(false===strpos($_SERVER['REQUEST_URI'], 'setup-config')) ABSPATH . 'wp-content'
Definition at line 68 of file wp-load.php.
Referenced by RSSCache\__construct(), _unzip_file_pclzip(), _unzip_file_ziparchive(), Language_Pack_Upgrader\async_upgrade(), Plugin_Upgrader\bulk_upgrade(), Theme_Upgrader\bulk_upgrade(), Language_Pack_Upgrader\bulk_upgrade(), Plugin_Upgrader\check_package(), Theme_Upgrader\check_package(), wpdb\db_connect(), dead_db(), GFFormsModel\delete_physical_file(), _WP_Editors\editor_settings(), WP_Plugins_List_Table\extra_tablenav(), WP_Filesystem_Base\find_folder(), WP_Upgrader\fs_connect(), get_dropins(), get_filesystem_method(), get_real_file_to_edit(), get_temp_dir(), get_theme_root(), get_theme_root_uri(), WP_Upgrader\install_package(), list_core_update(), make_site_theme(), make_site_theme_from_default(), make_site_theme_from_oldschool(), ms_site_check(), ms_upload_constants(), network_step1(), network_step2(), register_theme_directory(), require_wp_db(), WP_Upgrader\run(), search_theme_directories(), WP_Automatic_Updater\should_update(), WP_Automatic_Updater\update(), update_core(), Core_Upgrader\upgrade(), wp_can_install_language_pack(), wp_check_php_mysql_versions(), WP_Filesystem_Base\wp_content_dir(), wp_debug_backtrace_summary(), wp_debug_mode(), wp_get_theme(), wp_get_themes(), wp_load_translations_early(), wp_maintenance(), wp_plugin_directory_constants(), wp_set_lang_dir(), wp_start_object_cache(), WP_Filesystem_Base\wp_themes_dir(), and wp_upload_dir().