GravityView: wp-login.php File Reference
wp-login.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
login_footer ($input_id= '')
Outputs the footer for the login page.
if(force_ssl_admin()&&!is_ssl()) login_header ($title= 'Log In', $message= '', $wp_error= '')
Make sure that the WordPress bootstrap has run before continuing.
retrieve_password ()
Handles sending password retrieval email to user.
wp_login_viewport_meta ()
wp_shake_js ()
Variables
$action = isset($_REQUEST['action']) ? $_REQUEST['action'] : 'login'
$errors = new WP_Error()
$http_post = ('POST' == $_SERVER['REQUEST_METHOD'])
$interim_login = isset($_REQUEST['interim-login'])
if(defined('RELOCATE')&&RELOCATE) $secure = ('https' === parse_url(wp_login_url(), PHP_URL_SCHEME))
COOKIE_DOMAIN
if (SITECOOKIEPATH!=COOKIEPATH) setcookie(TEST_COOKIE
SITECOOKIEPATH
Function Documentation
login_footer ($input_id = '')
Outputs the footer for the login page.
Parameters
string $input_id Which input to auto-focus
Fires in the login page footer.
Since
3.1.0
Definition at line 214 of file wp-login.php.
References $interim_login, __, do_action(), endif, and get_bloginfo().
if (force_ssl_admin()&&!is_ssl()) login_header ($title = 'Log In', $message = '', $wp_error = '')
Make sure that the WordPress bootstrap has run before continuing.
Output the login page header.
Parameters
string $title Optional. WordPress login Page title to display in the <title> element. Default 'Log In'.
string $message Optional. Message to display in header. Default empty.
WP_Error $wp_error Optional. The error to pass. Default empty.
Filter the error codes array for shaking the login form.
Since
3.0.0
Parameters
array $shake_error_codes Error codes that shake the login form.
Enqueue scripts and styles for the login page.
Since
3.1.0
Fires in the login page header after scripts are enqueued.
Since
2.1.0
Filter link URL of the header logo above login form.
Since
2.1.0
Parameters
string $login_header_url Login header logo URL.
Filter the title attribute of the header logo above login form.
Since
2.1.0
Parameters
string $login_header_title Login header logo title attribute.
Filter the login page body classes.
Since
3.5.0
Parameters
array $classes An array of body classes.
string $action The action that brought the visitor to the login page.
Filter the message to display above the login form.
Since
2.1.0
Parameters
string $message Login message text.
Filter the error messages displayed above the login form.
Since
2.1.0
Parameters
string $errors Login error message.
Filter instructional messages displayed above the login form.
Since
2.5.0
Parameters
string $messages Login messages.
Definition at line 33 of file wp-login.php.
References $action, $errors, $interim_login, $message, $messages, $title, __, add_action(), apply_filters(), bloginfo(), color, do_action(), endif, get_current_site(), get_locale(), is_multisite(), is_rtl(), language_attributes(), network_home_url(), sanitize_html_class(), str_replace, wp_admin_css(), and wp_is_mobile().
retrieve_password ()
Handles sending password retrieval email to user.
wpdb $wpdb WordPress database abstraction object. PasswordHash $wp_hasher Portable PHP password hashing framework.
Returns
bool|WP_Error True: when finish. WP_Error on error
Fires before errors are returned from a password reset request.
Since
2.1.0
4.4.0 Added the $errors parameter.
Parameters
WP_Error $errors A WP_Error object containing any errors generated by using invalid credentials.
Filter the subject of the password reset email.
Since
2.8.0
4.4.0 Added the $user_login and $user_data parameters.
Parameters
string $title Default email title.
string $user_login The username for the user.
WP_User $user_data WP_User object.
Filter the message body of the password reset mail.
Since
2.8.0
4.1.0 Added $user_login and $user_data parameters.
Parameters
string $message Default mail message.
string $key The activation key.
string $user_login The username for the user.
WP_User $user_data WP_User object.
Filter the life span of the post password cookie.
By default, the cookie expires 10 days from creation. To turn this into a session cookie, return 0.
Since
3.7.0
Parameters
int $expires The expiry time, as passed to setcookie().
Filter the log out redirect URL.
Since
4.2.0
Parameters
string $redirect_to The redirect destination URL.
string $requested_redirect_to The requested redirect destination URL passed as a parameter.
WP_User $user The WP_User object for the user that's logging out.
Filter the URL redirected to after submitting the lostpassword/retrievepassword form.
Since
3.0.0
Parameters
string $lostpassword_redirect The redirect destination URL.
Fires before the lost password form.
Since
1.5.1
Fires inside the lostpassword form tags, before the hidden fields.
Since
2.1.0
This filter is documented in wp-includes/general-template.php
Fires before the password reset procedure is validated.
Since
3.5.0
Parameters
object $errors WP Error object.
WP_User | WP_Error $user WP_User object if the login and reset key match. WP_Error object otherwise.
Fires following the 'Strength indicator' meter in the user password reset form.
Since
3.9.0
Parameters
WP_User $user User object of the user whose password is being reset.
This filter is documented in wp-includes/general-template.php
Filter the Multisite sign up URL.
Since
3.0.0
Parameters
string $sign_up_url The sign up URL.
Filter the registration redirect URL.
Since
3.0.0
Parameters
string $registration_redirect The redirect destination URL.
Fires following the 'Email' field in the user registration form.
Since
2.1.0
Filter the login redirect URL.
Since
3.0.0
Parameters
string $redirect_to The redirect destination URL.
string $requested_redirect_to The requested redirect destination URL passed as a parameter.
WP_User | WP_Error $user WP_User object if login was successful, WP_Error object otherwise.
This action is documented in wp-login.php
Filter the login page errors.
Since
3.6.0
Parameters
object $errors WP Error object.
string $redirect_to Redirect destination URL.
Fires following the 'Password' field in the login form.
Since
2.1.0
This filter is documented in wp-includes/general-template.php
Definition at line 278 of file wp-login.php.
References $errors, $GLOBALS, $message, $title, $wpdb, __, apply_filters(), do_action(), elseif, get_option(), get_password_reset_key(), is_multisite(), is_wp_error(), network_home_url(), network_site_url(), wp_die(), and wp_specialchars_decode().
wp_login_viewport_meta ()
Since
3.7.0
Definition at line 264 of file wp-login.php.
References name.
wp_shake_js ()
Since
3.0.0
Definition at line 247 of file wp-login.php.
References wp_is_mobile().
Variable Documentation
$action = isset($_REQUEST['action']) ? $_REQUEST['action'] : 'login'
Definition at line 375 of file wp-login.php.
Referenced by login_header().
$errors = new WP_Error()
Definition at line 376 of file wp-login.php.
Referenced by login_header(), and retrieve_password().
$http_post = ('POST' == $_SERVER['REQUEST_METHOD'])
Definition at line 421 of file wp-login.php.
$interim_login = isset($_REQUEST['interim-login'])
Definition at line 422 of file wp-login.php.
Referenced by login_footer(), and login_header().
$secure = ('https' === parse_url(wp_login_url(), PHP_URL_SCHEME))
Definition at line 399 of file wp-login.php.
Referenced by random_bytes(), PHPMailer\smtpConnect(), wp_set_comment_cookies(), and wp_user_settings().
COOKIE_DOMAIN
Definition at line 401 of file wp-login.php.
Referenced by wp_set_comment_cookies().
if(SITECOOKIEPATH!=COOKIEPATH) setcookie(TEST_COOKIE
Definition at line 401 of file wp-login.php.
SITECOOKIEPATH
Definition at line 401 of file wp-login.php.
Referenced by delete_all_user_settings(), ms_cookie_constants(), wp_cookie_constants(), wp_default_scripts(), and wp_user_settings().