GravityView: wp-trackback.php File Reference
wp-trackback.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Functions
if(empty($wp)) trackback_response ($error=0, $error_message= '')
Response to a trackback.
Variables
$blog_name = isset($_POST['blog_name']) ? wp_unslash($_POST['blog_name']) : ''
$charset = isset($_POST['charset']) ? $_POST['charset'] : ''
$excerpt = isset($_POST['excerpt']) ? wp_unslash($_POST['excerpt']) : ''
$request_array = 'HTTP_POST_VARS'
if(!isset($_GET['tb_id'])||!$_GET['tb_id']) $tb_url = isset($_POST['url']) ? $_POST['url'] : ''
$title = isset($_POST['title']) ? wp_unslash($_POST['title']) : ''
if (!isset($tb_id)||!intval($tb_id)) trackback_response(1
Function Documentation
if (empty($wp)) trackback_response ($error = 0, $error_message = '')
Response to a trackback.
Responds with an error or success XML message.
Since
0.71
Parameters
mixed $error Whether there was an error. Default '0'. Accepts '0' or '1', true or false.
string $error_message Error message if an error occurred.
Fires after a trackback is added to a post.
Since
1.2.0
Parameters
int $trackback_id Trackback ID.
Definition at line 27 of file wp-trackback.php.
References get_option().
Variable Documentation
$blog_name = isset($_POST['blog_name']) ? wp_unslash($_POST['blog_name']) : ''
Definition at line 58 of file wp-trackback.php.
Referenced by _access_denied_splash(), and wp_update_user().
else $charset = isset($_POST['charset']) ? $_POST['charset'] : ''
Definition at line 53 of file wp-trackback.php.
Referenced by _canonical_charset(), _wp_specialchars(), SimplePie_Misc\encoding(), SimplePie\init(), maybe_convert_table_to_utf8mb4(), GFExport\maybe_export(), getid3_lib\MultiByteCharString2HTML(), IXR_Server\output(), getid3_lib\recursiveMultiByteCharString2HTML(), wp_insert_post(), wp_set_internal_encoding(), and wp_staticize_emoji_for_email().
$excerpt = isset($_POST['excerpt']) ? wp_unslash($_POST['excerpt']) : ''
Definition at line 57 of file wp-trackback.php.
Referenced by do_trackbacks(), get_comment_excerpt(), media_handle_upload(), wp_xmlrpc_server\pingback_ping(), the_content_rss(), trackback(), trackback_url_list(), and wp_html_excerpt().
$request_array = 'HTTP_POST_VARS'
Definition at line 45 of file wp-trackback.php.
if (!isset($_GET['tb_id'])||!$_GET['tb_id']) $tb_url = isset($_POST['url']) ? $_POST['url'] : ''
Definition at line 52 of file wp-trackback.php.
Referenced by get_trackback_url(), and trackback_url_list().
if (function_exists('mb_convert_encoding')) $title = isset($_POST['title']) ? wp_unslash($_POST['title']) : ''
Definition at line 56 of file wp-trackback.php.
if(!isset($tb_id)||!intval($tb_id)) trackback_response(1
Definition at line 84 of file wp-trackback.php.