GravityView: xmlrpc.php File Reference
xmlrpc.php File Reference
Namespaces
WordPress
Bootstrap the plugin unit testing environment.
Variables
$_COOKIE = array()
if (isset($_GET['rsd']))
Include the bootstrap for setting up WordPress environment.
const XMLRPC_REQUEST true
post_default_title
Posts submitted via the XML-RPC interface get that title
$post_default_title = ""
$wp_xmlrpc_server_class = apply_filters('wp_xmlrpc_server_class', 'wp_xmlrpc_server')
Filter the class used for handling XML-RPC requests.
$wp_xmlrpc_server = new $wp_xmlrpc_server_class
exit
logIO ($io, $msg)
logIO() - Writes logging info to a file.
Function Documentation
logIO ($io, $msg)
logIO() - Writes logging info to a file.
Parameters
string $io Whether input or output
string $msg Information describing logging reason.
Definition at line 97 of file xmlrpc.php.
References $GLOBALS, $msg, and _deprecated_function().
Variable Documentation
$_COOKIE = array()
Definition at line 16 of file xmlrpc.php.
Referenced by get_all_user_settings(), GFEntryDetail\lead_detail_grid(), WP_Ajax_UnitTestCase\logout(), post_password_required(), sanitize_comment_cookies(), wp_authenticate_cookie(), wp_get_current_commenter(), wp_magic_quotes(), wp_unregister_GLOBALS(), wp_user_settings(), and wp_validate_logged_in_cookie().
$post_default_title = ""
Definition at line 71 of file xmlrpc.php.
Referenced by xmlrpc_getposttitle().
$wp_xmlrpc_server = new $wp_xmlrpc_server_class
Definition at line 81 of file xmlrpc.php.
Referenced by _xmlrpc_wp_die_handler().
$wp_xmlrpc_server_class = apply_filters('wp_xmlrpc_server_class', 'wp_xmlrpc_server')
Filter the class used for handling XML-RPC requests.
Since
3.1.0
Parameters
string $class The name of the XML-RPC server class.
Definition at line 80 of file xmlrpc.php.
exit
Definition at line 86 of file xmlrpc.php.
if(isset($_GET['rsd']))
Include the bootstrap for setting up WordPress environment.
Definition at line 31 of file xmlrpc.php.
const XMLRPC_REQUEST true
Definition at line 13 of file xmlrpc.php.
Referenced by wp_die().