GravityView: GravityView_oEmbed Class Reference
GravityView_oEmbed Class Reference
Register oEmbed handlers for embedding GravityView data and render that data.
Public Member Functions
add_provider ()
Become an oEmbed provider for GravityView.
get_entry_id ()
Get the entry id for the current oEmbedded entry.
register_handler ()
Register the oEmbed handler.
render_handler ($matches, $attr, $url, $rawattr)
render_provider_request ()
Output a response as a provider for an entry oEmbed URL.
set_single_entry_id ($is_single_entry=false)
Tell get_gravityview() to display a single entry.
Static Public Member Functions
static getInstance ()
Static Public Attributes
static $instance = NULL
Protected Attributes
$entry_id = NULL
Set entry_id and view_id from the data sent to render_handler.
$is_full_oembed_preview = false
$output = array()
$view_id = NULL
Private Member Functions
__construct ()
generate_entry_output ()
generate_preview_notice ()
Generate a warning to users when previewing oEmbed in the Add Media modal.
get_handler_regex ()
Generate the Regular expression that matches embedded entries.
get_postid_from_url_and_slug ($url='', $slug='')
Get the post ID from an URL.
initialize ()
render_admin ($matches, $attr, $url, $rawattr)
Display a nice placeholder in the admin for the entry.
set_vars ($matches, $attr, $url, $rawattr)
Detailed Description
Register oEmbed handlers for embedding GravityView data and render that data.
Since
1.6
Definition at line 22 of file class-oembed.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Definition at line 31 of file class-oembed.php.
Member Function Documentation
add_provider()
add_provider ()
Become an oEmbed provider for GravityView.
Since
1.21.5.3
Returns
void
Definition at line 77 of file class-oembed.php.
References get_handler_regex().
generate_entry_output()
generate_entry_output () private
Definition at line 354 of file class-oembed.php.
References the_gravityview().
Referenced by set_single_entry_id().
generate_preview_notice()
generate_preview_notice () private
Generate a warning to users when previewing oEmbed in the Add Media modal.
Returns
string HTML notice
Definition at line 270 of file class-oembed.php.
References $title, and GravityView_Admin\get_floaty().
Referenced by render_handler(), and render_provider_request().
get_entry_id()
get_entry_id ()
Get the entry id for the current oEmbedded entry.
Since
1.6
Returns
int|null
Definition at line 211 of file class-oembed.php.
References $entry_id.
get_handler_regex()
get_handler_regex () private
Generate the Regular expression that matches embedded entries.
Generates different regex if using permalinks and if not using permalinks
Since
1.6
Returns
string Regex code
Deprecated. Use ::get_endpoint_name instead.
Runs Filter:
gravityview_slug Modify the url part for a View. Read the doc
Parameters
string $rewrite_slug The slug shown in the URL
Definition at line 138 of file class-oembed.php.
References Entry\get_endpoint_name(), and GravityView_Post_Types\get_entry_var_name().
Referenced by add_provider(), register_handler(), and render_provider_request().
get_postid_from_url_and_slug()
get_postid_from_url_and_slug ($url = '', $slug = '') private
Get the post ID from an URL.
This is necessary because url_to_postid() doesn't work with permalinks off for custom post types
url_to_postid()
Since
1.6
Parameters
string $url URL to get the post ID from
string $slug The name of a post, used as backup way of checking for post ID
Returns
int 0 if not found; int of URL post ID otherwise
Definition at line 180 of file class-oembed.php.
References $url.
Referenced by set_vars().
getInstance()
static getInstance () static
Returns
GravityView_oEmbed
Since
1.6
Definition at line 47 of file class-oembed.php.
Referenced by set_single_entry_id(), and GravityView_Edit_Entry_Render\user_can_edit_entry().
initialize()
initialize () private
Definition at line 33 of file class-oembed.php.
register_handler()
register_handler ()
Register the oEmbed handler.
Since
1.6 get_handler_regex
Definition at line 64 of file class-oembed.php.
References get_handler_regex().
render_admin()
render_admin ($matches, $attr, $url, $rawattr) private
Display a nice placeholder in the admin for the entry.
Parameters
array $matches The regex matches from the provided regex when calling wp_embed_register_handler()
array $attr Embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Returns
string The embed HTML.
Definition at line 333 of file class-oembed.php.
References $image, and GravityView_Admin\get_floaty().
Referenced by render_handler().
render_handler()
render_handler ($matches, $attr, $url, $rawattr)
Since
1.6
See also
GravityView_oEmbed::add_providers() for the regex
Parameters
array $matches The regex matches from the provided regex when calling wp_embed_register_handler()
array $attr Embed attributes.
string $url The original URL that was matched by the regex.
array $rawattr The original unmodified attributes.
Returns
string The embed HTML.
Definition at line 227 of file class-oembed.php.
References $url, generate_preview_notice(), render_admin(), and set_vars().
render_provider_request()
render_provider_request ()
Output a response as a provider for an entry oEmbed URL.
For now we only output the JSON format and don't care about the size (width, height). Our only current use-case is for it to provide output to the Add Media / From URL box in WordPress 4.8.
Since
1.21.5.3
Returns
void
Definition at line 92 of file class-oembed.php.
References $url, generate_preview_notice(), get_handler_regex(), and set_vars().
set_single_entry_id()
set_single_entry_id ($is_single_entry = false)
Tell get_gravityview() to display a single entry.
REQUIRED FOR THE VIEW TO OUTPUT A SINGLE ENTRY
Parameters
bool | int $is_single_entry Existing single entry. False, because GV thinks we're in a post or page.
Returns
int The current entry ID
Definition at line 385 of file class-oembed.php.
References $entry_id, $output, $url, generate_entry_output(), and getInstance().
set_vars()
set_vars ($matches, $attr, $url, $rawattr) private
maybe_get_view_id has a side-effect that adds retrieved views to the global scope
Deprecated.
Definition at line 285 of file class-oembed.php.
References $post, $url, View_Collection\from_post(), get_postid_from_url_and_slug(), GravityView_View_Data\getInstance(), and gravityview().
Referenced by render_handler(), and render_provider_request().
Field Documentation
$entry_id
$entry_id = NULL protected
Set entry_id and view_id from the data sent to render_handler.
Definition at line 25 of file class-oembed.php.
Referenced by get_entry_id(), and set_single_entry_id().
$instance
$instance = NULL static
Definition at line 29 of file class-oembed.php.
$is_full_oembed_preview
$is_full_oembed_preview = false protected
Definition at line 27 of file class-oembed.php.
$output
$output = array() protected
Definition at line 24 of file class-oembed.php.
Referenced by set_single_entry_id().
$view_id
$view_id = NULL protected
See also
render_handler
Definition at line 26 of file class-oembed.php.
The documentation for this class was generated from the following file:
class-oembed.php