GravityView: class-common.php File Reference
class-common.php File Reference
Data Structures
class GVCommon
If this file is called directly, abort.
Namespaces
GravityView
includes
Functions
gravityview_get_link ($href='', $anchor_text='', $atts=array())
Generate an HTML anchor tag with a list of supported attributes.
Function Documentation
gravityview_get_link()
gravityview_get_link ($href = '', $anchor_text = '', $atts = array())
Generate an HTML anchor tag with a list of supported attributes.
See also
GVCommon::get_link_html()
Since
1.6
Parameters
string $href URL of the link.
string $anchor_text The text or HTML inside the anchor. This is not sanitized in the function.
array | string $atts Attributes to be added to the anchor tag
Returns
string HTML output of anchor link. If empty $href, returns NULL
Definition at line 1723 of file class-common.php.
References $href, and GVCommon\get_link_html().
Referenced by GravityView_Delete_Entry\add_delete_button(), GravityView_Admin\connected_form_warning(), GravityView_API\entry_link_html(), GravityView_Field_FileUpload\get_field_input(), GravityView_Entry_List\get_item_output(), gravityview_back_link(), gravityview_convert_value_to_term_list(), gravityview_get_map_link(), GravityView_View_Data\is_valid_embed_id(), GravityView_Admin_Duplicate_View\make_duplicate_link_row(), GravityView_Entry_Link_Shortcode\shortcode(), GravityView_Widget_Search\the_clear_search_button(), and GravityView_Edit_Entry_Render\user_can_edit_entry().