GravityView: GravityView_Post_Types Class Reference
GravityView_Post_Types Class Reference
Public Member Functions
__construct ()
Static Public Member Functions
static get_entry_var_name ()
Return the query var / end point name for the entry.
static init_post_types ()
Init plugin components such as register own custom post types.
static init_rewrite ()
Register rewrite rules to capture the single entry view.
Detailed Description
Definition at line 15 of file class-post-types.php.
Constructor & Destructor Documentation
__construct()
__construct ()
Deprecated. Handled by from here on after.
Definition at line 17 of file class-post-types.php.
References GravityView_Compatibility\is_valid().
Member Function Documentation
get_entry_var_name()
static get_entry_var_name () static
Return the query var / end point name for the entry.
public
Deprecated:
See also
::get_endpoint_name
Returns
string Default: "entry"
Runs Filter:
gravityview_directory_endpoint Change the slug used for single entries
Parameters
[in,out] string $endpoint Slug to use when accessing single entry. Default: entry
Definition at line 162 of file class-post-types.php.
Referenced by GravityView_API\entry_link(), GravityView_oEmbed\get_handler_regex(), and GravityView_frontend\is_single_entry().
init_post_types()
static init_post_types () static
Init plugin components such as register own custom post types.
public
Deprecated:
See also
::register_post_type
Returns
void
Runs Filter:
gravityview_is_hierarchical Make GravityView Views hierarchical by returning TRUE This will allow for Views to be nested with Parents and also allows for menu order to be set in the Page Attributes metabox
Since
1.13
Parameters
boolean $is_hierarchical Default: false
Runs Filter:
gravityview_post_type_supports Modify post type support values for gravityview post type
See also
add_post_type_support()
Since
1.15.2
Parameters
array $supports Array of features associated with a functional area of the edit screen. Default: 'title', 'revisions'. If $is_hierarchical, also 'page-attributes'
[in] boolean $is_hierarchical Do Views support parent/child relationships? See gravityview_is_hierarchical filter.
Runs Filter:
gravityview_direct_access Should Views be directly accessible, or only visible using the shortcode?
See also
https://codex.wordpress.org/Function_Reference/register_post_type#public
Since
1.15.2
Parameters
[in,out] boolean true: allow Views to be accessible directly. false: Only allow Views to be embedded via shortcode. Default: true
int $view_id The ID of the View currently being requested. 0 for general setting
Runs Filter:
gravityview_has_archive Enable Custom Post Type archive?
Since
1.7.3
Parameters
boolean False: don't have frontend archive; True: yes, have archive. Default: false
Runs Filter:
gravityview_slug Modify the url part for a View.
See also
http://docs.gravityview.co/article/62-changing-the-view-slug
Parameters
string $slug The slug shown in the URL
Definition at line 40 of file class-post-types.php.
References $labels, GravityView_Compatibility\is_valid(), and GravityView_Admin\no_views_text().
Referenced by GravityView_Plugin\activate().
init_rewrite()
static init_rewrite () static
Register rewrite rules to capture the single entry view.
public
Deprecated:
See also
::add_rewrite_endpoint
Returns
void
Definition at line 142 of file class-post-types.php.
Referenced by GravityView_Plugin\activate().
The documentation for this class was generated from the following file:
class-post-types.php