GravityView: class-gravityview-settings.php File Reference
class-gravityview-settings.php File Reference
Data Structures
class GravityView_Settings
GravityView Settings class (get/set/license validation) using the Gravity Forms App framework.
Functions
_load_license_handler ()
Make sure the license handler is available.
add_network_menu ()
Add global Settings page for Multisite.
app_settings_fields ()
Specify the settings fields to be rendered on the plugin settings page.
app_settings_icon ()
Prevent displaying of any icon.
app_settings_tab ()
app_settings_title ()
The Settings title.
app_settings_uninstall_tab ()
create_app_menu ()
Add Settings link to GravityView menu.
get_app_setting ($setting_name)
Make protected public public.
get_app_settings ()
Returns the currently saved plugin settings.
get_default_settings ()
Get the default settings for the plugin.
get_license_handler ()
Allow public access to the GV_License_Handler class.
get_posted_settings ()
When the settings are saved, make sure the license key matches the previously activated key.
get_required_indicator ($field)
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
static getSetting ($key)
Get the setting for GravityView by name.
init_admin ()
Run actions when initializing admin.
init_ajax ()
Load license handler in admin-ajax.php.
license_key_notice ()
Display a notice if the plugin is inactive.
maybe_save_app_settings ()
Check for the gravityview_edit_settings capability before saving plugin settings.
modify_app_settings_menu_title ($setting_tabs)
Change the settings page header title to "GravityView".
scripts ()
Add tooltip script to app settings page.
set_field_error ($field, $error_message='')
Make protected public public.
settings_edd_license ($field, $echo=true)
Register the settings field for the EDD License field type.
settings_save ($field, $echo=true)
Allow customizing the Save field parameters.
settings_submit ($field, $echo=true)
single_setting_label ($field)
The same as the parent, except added support for field descriptions .
single_setting_row ($field)
Keep GravityView styling for `$field['description']`, even though Gravity Forms added support for it.
styles ()
Register styles in the app admin page.
update_app_settings ($settings)
Updates app settings with the provided settings.
Variables
$form = ob_get_clean()
$i = 0
$reasons = $this->get_uninstall_reasons()
padding bottom
scale description p description
padding top
scale description ul
gv form field wrapper
Function Documentation
_load_license_handler()
_load_license_handler () private
Make sure the license handler is available.
Definition at line 408 of file class-gravityview-settings.php.
add_network_menu()
add_network_menu ()
Add global Settings page for Multisite.
Since
1.7.6
Returns
void
Definition at line 546 of file class-gravityview-settings.php.
References GravityView_Plugin\is_network_activated().
app_settings_fields()
app_settings_fields ()
Specify the settings fields to be rendered on the plugin settings page.
Returns
array
Since
1.15 Added Support Port support
Redux backward compatibility
Since
1.7.4
Runs Filter:
gravityview/settings/extension/sections Modify the GravityView settings page Extensions can tap in here to insert their own section and settings. $sections[] = array('title' => __('GravityView My Extension Settings', 'gravityview'), 'fields' => $settings,);
Parameters
array $extension_settings Empty array, ready for extension settings!
Definition at line 896 of file class-gravityview-settings.php.
References $field, get_app_setting(), get_default_settings(), get_license_handler(), GRAVITYVIEW_FILE, GVCommon\has_cap(), and GravityView_Plugin\version.
app_settings_icon()
app_settings_icon ()
Prevent displaying of any icon.
Returns
string
Definition at line 590 of file class-gravityview-settings.php.
app_settings_tab()
app_settings_tab ()
Definition at line 594 of file class-gravityview-settings.php.
References GravityView_Settings\uninstall_form().
app_settings_title()
app_settings_title ()
The Settings title.
Returns
string
Definition at line 582 of file class-gravityview-settings.php.
app_settings_uninstall_tab()
app_settings_uninstall_tab ()
Definition at line 317 of file class-gravityview-settings.php.
References GravityView_Settings\current_user_can_any(), and GravityView_Settings\uninstall_warning_message().
Referenced by settings_save().
create_app_menu()
create_app_menu ()
Add Settings link to GravityView menu.
Returns
void
If not multisite, always show. If multisite and the plugin is network activated, show; we need to register the submenu page for the Network Admin settings to work. If multisite and not network admin, we don't want the settings to show.
Since
1.7.6
Override whether to show the Settings menu on a per-blog basis.
Since
1.7.6
Parameters
bool $hide_if_network_activated Default: true
Definition at line 556 of file class-gravityview-settings.php.
References GravityView_Plugin\is_network_activated().
get_app_setting()
get_app_setting ($setting_name)
Make protected public public.
Backward compatibility with Redux
Definition at line 607 of file class-gravityview-settings.php.
Referenced by app_settings_fields().
get_app_settings()
get_app_settings ()
Returns the currently saved plugin settings.
Different from GFAddon in two ways:
Makes protected method public
Use default settings if the original settings don't exist
public
Returns
array
Definition at line 634 of file class-gravityview-settings.php.
References get_default_settings().
get_default_settings()
get_default_settings () private
Get the default settings for the plugin.
Merges previous settings created when using the Redux Framework
Returns
array Settings with defaults set
Definition at line 819 of file class-gravityview-settings.php.
Referenced by app_settings_fields(), and get_app_settings().
get_license_handler()
get_license_handler ()
Allow public access to the GV_License_Handler class.
Since
1.7.4
Returns
GV_License_Handler
Definition at line 700 of file class-gravityview-settings.php.
References GravityView_Settings\$License_Handler.
Referenced by app_settings_fields().
get_posted_settings()
get_posted_settings ()
When the settings are saved, make sure the license key matches the previously activated key.
Returns
array settings from parent::get_posted_settings(), with license_key_response and license_key_status potentially unset
Definition at line 861 of file class-gravityview-settings.php.
get_required_indicator()
get_required_indicator ($field)
Gets the required indicator Gets the markup of the required indicator symbol to highlight fields that are required.
Parameters
$field - The field meta.
Returns
string - Returns markup of the required indicator symbol
Definition at line 888 of file class-gravityview-settings.php.
getSetting()
static getSetting ($key) static
Get the setting for GravityView by name.
Parameters
string $key Option key to fetch
Returns
mixed
Definition at line 1071 of file class-gravityview-settings.php.
References GravityView_Settings\get_instance().
Referenced by GravityView_Support_Port\_localize_script(), GravityView_Extension\get_license(), GravityView_Admin_No_Conflict\no_conflict_scripts(), GravityView_Admin_No_Conflict\no_conflict_styles(), GravityView_Support_Port\show_for_user(), and GravityView_Support_Port\user_field().
init_admin()
init_admin ()
Run actions when initializing admin.
Triggers the license key notice
Returns
void
Since
1.7.6
Definition at line 370 of file class-gravityview-settings.php.
init_ajax()
init_ajax ()
Load license handler in admin-ajax.php.
Definition at line 401 of file class-gravityview-settings.php.
license_key_notice()
license_key_notice ()
Display a notice if the plugin is inactive.
Returns
void
I wanted to remove the period from after the buttons in the string, but didn't want to mess up the translation strings for the translators.
Since
1.17
PhpMissingBreakStatementInspection
Definition at line 423 of file class-gravityview-settings.php.
maybe_save_app_settings()
maybe_save_app_settings ()
Check for the gravityview_edit_settings capability before saving plugin settings.
Gravity Forms says you're able to edit if you're able to view settings. GravityView allows two different permissions.
Since
1.15
Returns
void
Definition at line 843 of file class-gravityview-settings.php.
References GVCommon\has_cap().
modify_app_settings_menu_title()
modify_app_settings_menu_title ($setting_tabs)
Change the settings page header title to "GravityView".
Parameters
$setting_tabs
Returns
array
Definition at line 391 of file class-gravityview-settings.php.
scripts()
scripts ()
Add tooltip script to app settings page.
Not enqueued by Gravity Forms for some reason.
Since
1.21.5
See also
GFAddOn::scripts()
Returns
array Array of scripts
Definition at line 498 of file class-gravityview-settings.php.
set_field_error()
set_field_error ($field, $error_message = '')
Make protected public public.
Definition at line 664 of file class-gravityview-settings.php.
References $field.
settings_edd_license()
settings_edd_license ($field, $echo = true) protected
Register the settings field for the EDD License field type.
Parameters
array $field
bool $echo Whether to echo the
Returns
string
Definition at line 675 of file class-gravityview-settings.php.
References $field.
settings_save()
settings_save ($field, $echo = true)
Allow customizing the Save field parameters.
Parameters
array $field
bool $echo
Returns
string
Definition at line 752 of file class-gravityview-settings.php.
References $field, $output, app_settings_uninstall_tab(), and settings_submit().
settings_submit()
settings_submit ($field, $echo = true)
Definition at line 712 of file class-gravityview-settings.php.
References $attributes, $field, $name, and $value.
Referenced by settings_save().
single_setting_label()
single_setting_label ($field)
The same as the parent, except added support for field descriptions .
Parameters
$field array
Definition at line 803 of file class-gravityview-settings.php.
References $description, and $field.
single_setting_row()
single_setting_row ($field)
Keep GravityView styling for `$field['description']`, even though Gravity Forms added support for it.
Converts `$field['description']to$field['gv_description'] Converts$field['subtitle']to$field['description']`
See also
GravityView_Settings::single_setting_label Converts gv_description back to description
http://share.gravityview.co/P28uGp/2OIRKxog for image that shows subtitle vs description
Since
1.21.5.2
Parameters
array $field
Returns
void
Definition at line 790 of file class-gravityview-settings.php.
References $field.
styles()
styles ()
Register styles in the app admin page.
Returns
array
Definition at line 517 of file class-gravityview-settings.php.
References GRAVITYVIEW_FILE, and GravityView_Plugin\version.
update_app_settings()
update_app_settings ($settings)
Updates app settings with the provided settings.
Same as the GVAddon, except it returns the value from update_option()
Parameters
array $settings - App settings to be saved
Returns
boolean False if value was not updated and true if value was updated.
Definition at line 655 of file class-gravityview-settings.php.
Variable Documentation
$form
return $form = ob_get_clean()
Definition at line 311 of file class-gravityview-settings.php.
Referenced by GravityView_Field_List\_filter_field_label(), GravityView_Field\_filter_gform_custom_merge_tags(), GravityView_Field\_filter_gform_replace_merge_tags(), GravityView_Field_Time\_get_time_format_for_field(), GravityView_frontend\_override_sorting_id_by_field_type(), Form_Collection\add(), GravityView_frontend\add_columns_sort_links(), GravityView_Admin_Views\add_custom_column_content(), GravityView_Plugin_Hooks_Gravity_Forms_Quiz\add_form_fields(), GravityView_Field_List\add_form_fields(), GravityView_Field_Address\add_hooks(), GravityView_Edit_Entry_User_Registration\add_hooks(), GravityView_Field_Total\add_to_blacklist(), GravityView_Admin_Views\add_view_dropdown(), GravityView_Plugin_Hooks_Gravity_Forms_Signature\after_edit_entry(), GravityView_Entry_Approval\after_submission(), GravityView_Entry_Approval\after_update_entry_update_approved_meta(), GravityView_Recent_Entries_Widget\ajax_get_view_merge_tag_data(), GF_Form\by_id(), GVCommon\check_entry_display(), GravityView_Field_Product\clear_product_info_cache(), GravityView_Ajax\create_preset_form(), GravityView_Field_Is_Approved\custom_merge_tags(), GravityView_Plugin_Hooks_Gravity_Forms_Coupon\edit_entry_field_value(), GravityView_Cache\entry_added(), GravityView_Cache\entry_created(), GravityView_Cache\entry_updated(), GravityView_Field_Post_Image\explode_value(), GravityView_API\field_class(), GravityView_API\field_html_attr_id(), GravityView_API\field_label(), GravityView_Field_Password\field_label(), GravityView_API\field_value(), GravityView_Admin_ApproveEntries\filter_links_entry_list(), GravityView_HTML_Elements\form_dropdown(), Form_Collection\get(), GravityView_Admin_ApproveEntries\get_approved_column(), GravityView_Entry_Approval\get_approved_column_input_label(), GravityView_Admin_Views\get_available_fields(), GravityView_Ajax\get_available_fields_html(), GravityView_Field_Address\get_choices_state(), GravityView_Admin_Views\get_connected_form_links(), GF_Form\get_entries(), GravityView_Admin_Views\get_entry_default_fields(), GVCommon\get_field(), GravityView_Field_FileUpload\get_field_input(), GVCommon\get_field_label(), GVCommon\get_field_type(), GravityView_Admin\get_floaty(), GVCommon\get_form_fields(), GVCommon\get_form_from_entry_id(), GravityView_GFFormsModel\get_post_field_images(), GravityView_GFFormsModel\get_post_fields(), GravityView_frontend\get_search_criteria_paging(), GravityView_Migrate\get_search_fields(), GravityView_Widget_Search\get_search_filter_details(), GravityView_Widget_Search\get_searchable_fields(), GravityView_Ajax\get_sortable_fields(), GV\Mocks\GravityView_frontend_get_view_entries(), gravityview_get_field(), gravityview_get_field_label(), gravityview_get_field_type(), gravityview_get_form_fields(), gravityview_is_single_entry(), gv_class(), GVCommon\has_product_field(), GravityView_Field\is_choice_value_enabled(), GVCommon\is_field_numeric(), GravityView_frontend\is_field_sortable(), GravityView_GFFormsModel\is_value_match(), GravityView_Field_Notes\maybe_send_entry_notes(), View\offsetGet(), GravityView_Ajax\pre_get_form_fields(), GravityView_Widget_Search\prepare_field_filter(), GravityView_Admin_Views\render_active_areas(), GravityView_Admin_Views\render_available_fields(), GravityView_Admin_Metaboxes\render_merge_tags_scripts(), GravityView_Merge_Tags\replace_get_variables(), GravityView_Merge_Tags\replace_gv_merge_tags(), GravityView_API\replace_variables(), GravityView_Merge_Tags\replace_variables(), GravityView_Field_Post_Category\set_post_categories(), GravityView_Field_Custom\show_field_in_edit_entry(), GravityView_Entry_Approval\update_approved_meta(), and GravityView_Recent_Entries_Widget\widget().
$i
$i = 0
Definition at line 280 of file class-gravityview-settings.php.
Referenced by Entry_Collection\fetch(), GravityView_Admin_ApproveEntries\get_bulk_actions(), and GravityView_Field_Custom\show_field_in_edit_entry().
$reasons
$reasons = $this->get_uninstall_reasons()
Definition at line 266 of file class-gravityview-settings.php.
Referenced by GravityView_Settings\get_uninstall_reasons().
bottom
padding bottom
Definition at line 208 of file class-gravityview-settings.php.
description
scale description p description
Initial value:
{
            margin-top: 0!important
Definition at line 210 of file class-gravityview-settings.php.
Referenced by GravityView_Field_Entry_Approval\__construct(), GravityView_Field_Payment_Date\__construct(), GravityView_Field_Payment_Status\__construct(), GravityView_Field_Other_Entries\__construct(), GravityView_Field_Date_Created\__construct(), GravityView_Field_Payment_Method\__construct(), GravityView_Field_Entry_Link\__construct(), GravityView_Field_Transaction_Type\__construct(), GravityView_Field_Is_Approved\__construct(), GravityView_Field_Is_Approved\add_default_field(), and GravityView_Field_Entry_Approval\filter_gravityview_entry_default_field().
top
padding top
Definition at line 212 of file class-gravityview-settings.php.
Referenced by GravityView_Admin_Bar\add_floaty_icon().
ul
scale description ul
Initial value:
{
            margin-bottom: 0
Definition at line 206 of file class-gravityview-settings.php.
Referenced by GravityView_Welcome\getting_started_screen(), and GravityView_FieldType_checkboxes\render_input().
wrapper
gv form field wrapper
Initial value:
{
            margin-top: 30px
Definition at line 214 of file class-gravityview-settings.php.