GravityView: entry_approval.php File Reference
entry_approval.php File Reference
Namespaces
GravityView
includes
Variables
$anchor = GravityView_Field_Entry_Approval::get_anchor_text($current_status)
$class = GravityView_Field_Entry_Approval::get_css_class($current_status)
$current_status = GravityView_Entry_Approval::get_entry_status($entry, 'value')
$entry = GravityView_View::getInstance()->getCurrentEntry()
$entry_slug = GravityView_API::get_entry_slug($entry['id'], $entry)
$title = GravityView_Field_Entry_Approval::get_title_attr($current_status)
Variable Documentation
$anchor
$anchor = GravityView_Field_Entry_Approval::get_anchor_text($current_status)
Definition at line 22 of file entry_approval.php.
Referenced by GravityView_Debug_Bar\render_item().
$class
$class = GravityView_Field_Entry_Approval::get_css_class($current_status)
Definition at line 24 of file entry_approval.php.
Referenced by GravityView_frontend\add_columns_sort_links(), GravityView_Compatibility\check_gravityforms(), GravityView_Fields\create(), GravityView_Delete_Entry\display_message(), GV_License_Handler\generate_license_box(), GVCommon\generate_notice(), GravityView_Field_Post_Content\get_field_input(), GravityView_Admin_View_Item\get_item_info(), GV_License_Handler\get_license_message(), gravityview_get_floaty(), GravityView_Widget_Page_Links\render_frontend(), GravityView_Widget_Pagination_Info\render_frontend(), GravityView_Widget_Custom_Content\render_frontend(), GravityView_FieldType_hidden\render_input(), GravityView_FieldType_number\render_input(), GravityView_FieldType_text\render_input(), GravityView_FieldType_textarea\render_input(), GravityView_Render_Settings\render_text_option(), GravityView_Render_Settings\render_textarea_option(), GravityView_HTML_Elements\select(), and GV_License_Handler\settings_edd_license_activation().
$current_status
$current_status = GravityView_Entry_Approval::get_entry_status($entry, 'value')
Definition at line 21 of file entry_approval.php.
Referenced by GravityView_Entry_Approval\ajax_update_approved().
$entry
$entry = GravityView_View::getInstance()->getCurrentEntry()
Definition at line 19 of file entry_approval.php.
$entry_slug
$entry_slug = GravityView_API::get_entry_slug($entry['id'], $entry)
Definition at line 20 of file entry_approval.php.
$title
$title = GravityView_Field_Entry_Approval::get_title_attr($current_status)
Definition at line 23 of file entry_approval.php.
Referenced by GravityView_Admin_Add_Shortcode\add_shortcode_popup(), GravityView_frontend\context_not_configured_warning(), GravityView_Field_Post_Image\explode_value(), GravityView_Search_WP_Widget\form(), GravityView_Recent_Entries_Widget\form(), GravityView_oEmbed\generate_preview_notice(), GravityView_frontend\single_entry_title(), GravityView_Admin_Views\tooltips(), GravityView_Search_WP_Widget\widget(), and GravityView_Recent_Entries_Widget\widget().