GravityView: post_image.php File Reference
post_image.php File Reference
Namespaces
GravityView
includes
Variables
$ary = explode("|:|", $value)
$caption = count($ary) > 2 ? $ary[2] : ""
$description = count($ary) > 3 ? $ary[3] : ""
$gravityview_view = GravityView_View::getInstance()
$image = new GravityView_Image($image_atts)
$image_atts
$image_meta
$link_atts = array()
if($gravityview_view->getAtts('lightbox')) $link_atts ['href'] = $href
$link_atts ['title'] = $title
$output = '<'.$wrappertag.' class="gv-image">'
$showlabels = apply_filters('gravityview_post_image_meta_show_labels', true)
$title = count($ary) > 1 ? $ary[1] : ""
$url = count($ary) > 0 ? $ary[0] : ""
$wrappertag = GFFormsModel::is_html5_enabled() ? 'figure' : 'div'
if(!empty($field['postFeaturedImage']) &&!empty($field_settings['dynamic_data']) &&!empty($entry['post_id']) &&has_post_thumbnail($entry['post_id'])) if(!empty($field_settings['link_to_post'])) else if(!empty($field_settings['show_as_link'])) else
Variable Documentation
$ary
$ary = explode("|:|", $value)
Definition at line 24 of file post_image.php.
Referenced by GravityView_Edit_Entry_Render\update_post_image().
$caption
$caption = count($ary) > 2 ? $ary[2] : ""
Definition at line 27 of file post_image.php.
Referenced by GravityView_Field_Post_Image\explode_value().
$description
$description = count($ary) > 3 ? $ary[3] : ""
Definition at line 28 of file post_image.php.
Referenced by single_setting_label().
$gravityview_view
$gravityview_view = GravityView_View::getInstance()
Definition at line 9 of file post_image.php.
$image
$image = new GravityView_Image($image_atts)
Definition at line 98 of file post_image.php.
Referenced by GravityView_frontend\context_not_configured_warning(), GravityView_Field_FileUpload\get_field_input(), GravityView_Admin\get_floaty(), GravityView_Admin\no_views_text(), and GravityView_oEmbed\render_admin().
$image_atts
$image_atts
Initial value:
= array(
    'src'   => $url,
    'alt'   => ( !empty( $caption ) ? $caption : $title ),
    'validate_src'  => false,
)
Definition at line 92 of file post_image.php.
$image_meta
$image_meta
Initial value:
= apply_filters('gravityview_post_image_meta', array(
    'title' => array(
        'label' => esc_attr_x( 'Title:', 'Post Image field title heading', 'gravityview'),
        'value' => $title,
        'tag_label' => 'span',
        'tag_value' => 'div'
    ),
    'caption' => array(
        'label' => esc_attr_x( 'Caption:', 'Post Image field caption heading', 'gravityview'),
        'value' => $caption,
        'tag_label' => 'span',
        'tag_value' => GFFormsModel::is_html5_enabled() ? 'figcaption' : 'div',
    ),
    'description' => array(
        'label' => esc_attr_x( 'Description:', 'Post Image field description heading', 'gravityview'),
        'value' => $description,
        'tag_label' => 'span',
        'tag_value' => 'div'
    ),
))
Definition at line 106 of file post_image.php.
Referenced by GravityView_Edit_Entry_Render\update_post_image().
$link_atts [1/3]
$link_atts = array()
Definition at line 30 of file post_image.php.
$link_atts [2/3]
if ($gravityview_view->getAtts('lightbox')) $link_atts[ 'href'] = $href
Definition at line 83 of file post_image.php.
$link_atts [3/3]
$link_atts[ 'title'] = $title
Definition at line 86 of file post_image.php.
$output
foreach ((array) $image_meta as $key=> $meta) $output = '<'.$wrappertag.' class="gv-image">'
Definition at line 138 of file post_image.php.
$showlabels
$showlabels = apply_filters('gravityview_post_image_meta_show_labels', true)
Definition at line 135 of file post_image.php.
$title
$title = count($ary) > 1 ? $ary[1] : ""
Definition at line 26 of file post_image.php.
$url
$url = count($ary) > 0 ? $ary[0] : ""
Definition at line 25 of file post_image.php.
Referenced by GV_License_Handler\_license_get_remote_response(), GravityView_frontend\add_columns_sort_links(), GravityView_Admin_Notices\admin_notice(), GravityView_GFFormsModel\copy_post_image(), GravityView_Field_Post_Image\explode_value(), GravityView_Delete_Entry\get_delete_link(), GravityView_Edit_Entry\get_edit_link(), GravityView_Field_Notes\get_email_footer(), GravityView_oEmbed\get_postid_from_url_and_slug(), GravityView_Widget_Search\get_search_form_action(), GravityView_Entry_Link_Shortcode\get_url(), gravityview_get_map_link(), GravityView_Entry_Link_Shortcode\maybe_add_field_values_query_args(), GravityView_GFFormsModel\media_handle_upload(), GravityView_oEmbed\render_handler(), GravityView_oEmbed\render_provider_request(), GravityView_oEmbed\set_single_entry_id(), GravityView_oEmbed\set_vars(), GravityView_Entry_Link_Shortcode\shortcode(), and GravityView_Widget_Search\the_clear_search_button().
$wrappertag
$wrappertag = GFFormsModel::is_html5_enabled() ? 'figure' : 'div'
Definition at line 128 of file post_image.php.
else
if (!empty($field[ 'postFeaturedImage']) &&!empty($field_settings[ 'dynamic_data']) &&!empty($entry[ 'post_id']) &&has_post_thumbnail($entry[ 'post_id'])) if (!empty($field_settings[ 'link_to_post'])) else if (!empty($field_settings[ 'show_as_link'])) else
Initial value:
{
    $href = $url
Since
1.5.4
$field['postFeaturedImage'] - holds if the Post Image field is set as post featured image $field_settings['dynamic_data'] - whether the field content should be fetched from the Post (dynamic data) or from the GF entry
Dynamic data (get post featured image instead of GF entry field)
Definition at line 70 of file post_image.php.